TTKMusicPlayer: QDeviceWatcher Class Reference
QDeviceWatcher Class Reference
The class of the device watcher.
#include <qdevicewatcher.h>
Signals
void deviceAdded (const QString &dev)
void deviceChanged (bool state)
void deviceChanged (const QString &dev)
void deviceRemoved (const QString &dev)
Public Member Functions
QDeviceWatcher (QObject *parent=nullptr)
~QDeviceWatcher ()
bool start ()
bool stop ()
bool isRunning () const
void appendEventReceiver (QObject *receiver)
Protected Attributes
bool running
QDeviceWatcherPrivate * d_ptr
Detailed Description
The class of the device watcher.
Author
WangBin wbsec.nosp@m.g1@g.nosp@m.mail..nosp@m.com
Definition at line 31 of file qdevicewatcher.h.
Constructor & Destructor Documentation
QDeviceWatcher::QDeviceWatcher (QObject * parent = nullptr) explicit
Definition at line 4 of file qdevicewatcher.cpp.
QDeviceWatcher::~QDeviceWatcher ()
Definition at line 13 of file qdevicewatcher.cpp.
References d_ptr.
Member Function Documentation
void QDeviceWatcher::appendEventReceiver (QObject * receiver)
Definition at line 44 of file qdevicewatcher.cpp.
Referenced by MusicApplicationModule::MusicApplicationModule().
void QDeviceWatcher::deviceAdded (const QString & dev) signal
void QDeviceWatcher::deviceChanged (bool state) signal
void QDeviceWatcher::deviceChanged (const QString & dev) signal
void QDeviceWatcher::deviceRemoved (const QString & dev) signal
bool QDeviceWatcher::isRunning () const
Definition at line 39 of file qdevicewatcher.cpp.
References running.
bool QDeviceWatcher::start ()
Definition at line 21 of file qdevicewatcher.cpp.
References running, and stop().
Referenced by MusicApplicationModule::MusicApplicationModule().
bool QDeviceWatcher::stop ()
Definition at line 32 of file qdevicewatcher.cpp.
References running.
Referenced by start().
Member Data Documentation
QDeviceWatcherPrivate* QDeviceWatcher::d_ptr protected
Definition at line 53 of file qdevicewatcher.h.
Referenced by ~QDeviceWatcher().
bool QDeviceWatcher::running protected
Definition at line 52 of file qdevicewatcher.h.
Referenced by isRunning(), start(), and stop().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKWatcher/qdevicewatcher.h
TTKThirdParty/TTKWatcher/qdevicewatcher.cpp