TTKMusicplayer: MusicDownloadWidget Class Reference
MusicDownloadWidget Class Reference
The class of the download widget.
#include <musicdownloadwidget.h>
Public Slots
void show ()
void queryAllFinished ()
void downloadDirSelected ()
void startToDownload ()
void dataDownloadFinished ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void dataDownloadChanged ()
Public Member Functions
MusicDownloadWidget (QWidget *parent=nullptr)
virtual ~MusicDownloadWidget ()
void setSongName (const QString &name, MusicDownLoadQueryThreadAbstract::QueryType type)
void setSongName (const MusicObject::MusicSongInformation &info, MusicDownLoadQueryThreadAbstract::QueryType type)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void initWidget ()
void controlEnable (bool enable)
void resizeWindow ()
void setFixedHeightWidget (QWidget *w, int height)
void setMoveWidget (QWidget *w, int pos)
MusicObject::MusicSongInformation getMatchMusicSongInformation ()
void queryAllFinishedMusic ()
void queryAllFinishedMusic (const MusicObject::MusicSongAttributes &attrs)
void queryAllFinishedMovie ()
void queryAllFinishedMovie (const MusicObject::MusicSongAttributes &attrs)
void startToDownloadMusic ()
void startToDownloadMusic (const MusicObject::MusicSongInformation &musicSongInfo)
void startToDownloadMovie ()
void startToDownloadMovie (const MusicObject::MusicSongInformation &musicSongInfo)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicDownloadWidget * m_ui
bool m_querySingleInfo
int m_downloadOffset
int m_downloadTotal
MusicDownLoadQueryThreadAbstract * m_downloadThread
MusicDownLoadQueryThreadAbstract::QueryType m_queryType
MusicObject::MusicSongInformation m_singleSongInfo
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the download widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 142 of file musicdownloadwidget.h.
Constructor & Destructor Documentation
MusicDownloadWidget::MusicDownloadWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 111 of file musicdownloadwidget.cpp.
References downloadDirSelected(), MusicGifLabelWidget::Gif_Cicle_Blue, M_DOWNLOAD_QUERY_PTR, m_downloadOffset, m_downloadThread, m_downloadTotal, m_querySingleInfo, m_queryType, m_ui, MusicUIObject::MLineEditStyle01, MusicUIObject::MPushButtonStyle03, MusicUIObject::MPushButtonStyle06, MusicUIObject::MToolButtonStyle04, MusicDownLoadQueryThreadAbstract::MusicQuery, queryAllFinished(), and startToDownload().
MusicDownloadWidget::~MusicDownloadWidget () virtual
Definition at line 148 of file musicdownloadwidget.cpp.
References m_downloadThread, and m_ui.
Member Function Documentation
void MusicDownloadWidget::controlEnable (bool enable) protected
Enable or disable control state.
Definition at line 170 of file musicdownloadwidget.cpp.
References m_ui.
Referenced by initWidget(), and startToDownload().
void MusicDownloadWidget::dataDownloadChanged () signal
Data download changed.
Referenced by dataDownloadFinished().
void MusicDownloadWidget::dataDownloadFinished () slot
Data download is finished.
Definition at line 430 of file musicdownloadwidget.cpp.
References dataDownloadChanged(), m_downloadOffset, and m_downloadTotal.
Referenced by startToDownloadMovie(), and startToDownloadMusic().
void MusicDownloadWidget::downloadDirSelected () slot
Change data download save path.
Definition at line 387 of file musicdownloadwidget.cpp.
References MusicSettingManager::DownloadMusicPathDirChoiced, m_queryType, M_SETTING_PTR, m_ui, and MusicDownLoadQueryThreadAbstract::MusicQuery.
Referenced by MusicDownloadWidget().
MusicObject::MusicSongInformation MusicDownloadWidget::getMatchMusicSongInformation () protected
Get match music song infomation.
Definition at line 231 of file musicdownloadwidget.cpp.
References MusicUtils::String::artistName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicDownLoadQueryThreadAbstract::getSearchedText(), m_downloadThread, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, and MusicUtils::String::songName().
Referenced by queryAllFinishedMovie(), queryAllFinishedMusic(), startToDownloadMovie(), and startToDownloadMusic().
void MusicDownloadWidget::initWidget () protected
Create all widget in layout.
Definition at line 154 of file musicdownloadwidget.cpp.
References controlEnable(), MusicSettingManager::DownloadMusicPathDirChoiced, m_queryType, M_SETTING_PTR, m_ui, MOVIE_DIR_FULL, and MusicDownLoadQueryThreadAbstract::MovieQuery.
Referenced by setSongName().
void MusicDownloadWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 213 of file musicdownloadwidget.cpp.
References M_NETWORK_PTR, m_queryType, m_ui, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicDownLoadQueryThreadAbstract::MusicQuery, queryAllFinishedMovie(), and queryAllFinishedMusic().
Referenced by MusicDownloadWidget().
void MusicDownloadWidget::queryAllFinishedMovie () protected
Query all quality that movies is finished.
Definition at line 307 of file musicdownloadwidget.cpp.
References MusicMessageBox::exec(), getMatchMusicSongInformation(), MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, and MusicObject::MusicSongInformation::m_songName.
Referenced by queryAllFinished(), and setSongName().
void MusicDownloadWidget::queryAllFinishedMovie (const MusicObject::MusicSongAttributes & attrs) protected
Query all quality that movies is finished.
st
sd
hd
sq
Definition at line 322 of file musicdownloadwidget.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, m_ui, MB_1000, MB_250, MB_500, MB_750, and resizeWindow().
void MusicDownloadWidget::queryAllFinishedMusic () protected
Query all quality that musics is finished.
Definition at line 255 of file musicdownloadwidget.cpp.
References MusicMessageBox::exec(), getMatchMusicSongInformation(), MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, and MusicObject::MusicSongInformation::m_songName.
Referenced by queryAllFinished(), and setSongName().
void MusicDownloadWidget::queryAllFinishedMusic (const MusicObject::MusicSongAttributes & attrs) protected
Query all quality that musics is finished.
st
sd
hd
sq
cd
Definition at line 270 of file musicdownloadwidget.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, m_ui, MB_128, MB_192, MB_320, and resizeWindow().
void MusicDownloadWidget::resizeWindow () protected
Automatically adjust the height according to searched items.
Definition at line 355 of file musicdownloadwidget.cpp.
References ITEM_ROW_HEIGHT_S, m_ui, MusicAbstractMoveWidget::setBackgroundPixmap(), setFixedHeightWidget(), and setMoveWidget().
Referenced by queryAllFinishedMovie(), and queryAllFinishedMusic().
void MusicDownloadWidget::setFixedHeightWidget (QWidget * w, int height) protected
Set widget fixed height.
Definition at line 376 of file musicdownloadwidget.cpp.
Referenced by resizeWindow().
void MusicDownloadWidget::setMoveWidget (QWidget * w, int pos) protected
Set widget moved into given pos.
Definition at line 381 of file musicdownloadwidget.cpp.
Referenced by resizeWindow().
void MusicDownloadWidget::setSongName (const QString & name, MusicDownLoadQueryThreadAbstract::QueryType type)
Set current name to search and download musics.
Definition at line 178 of file musicdownloadwidget.cpp.
References MusicUtils::Widget::elidedText(), initWidget(), m_downloadThread, m_queryType, m_ui, MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicVideoSearchTableWidget::downloadLocalMovie(), MusicWebMVRadioInfoTableWidget::musicDownloadLocal(), MusicQueryFoundTableWidget::musicDownloadLocal(), MusicSongSearchTableWidget::musicDownloadLocal(), MusicIdentifySongsWidget::musicSongDownload(), MusicSongsListAbstractTableWidget::musicSongDownload(), MusicWebMusicRadioPlayWidget::radioResourceDownload(), MusicDownloadResetWidget::restartToDownload(), and MusicDownloadMgmtWidget::setSongName().
void MusicDownloadWidget::setSongName (const MusicObject::MusicSongInformation & info, MusicDownLoadQueryThreadAbstract::QueryType type)
Set current name to search and download musics.
Definition at line 188 of file musicdownloadwidget.cpp.
References MusicUtils::Widget::elidedText(), initWidget(), m_querySingleInfo, m_queryType, MusicObject::MusicSongInformation::m_singerName, m_singleSongInfo, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, m_ui, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicDownLoadQueryThreadAbstract::MusicQuery, queryAllFinishedMovie(), and queryAllFinishedMusic().
void MusicDownloadWidget::show () slot
Override show function.
Definition at line 207 of file musicdownloadwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Referenced by MusicVideoSearchTableWidget::downloadLocalMovie(), MusicWebMVRadioInfoTableWidget::musicDownloadLocal(), MusicQueryFoundTableWidget::musicDownloadLocal(), MusicSongSearchTableWidget::musicDownloadLocal(), MusicIdentifySongsWidget::musicSongDownload(), MusicSongsListAbstractTableWidget::musicSongDownload(), MusicWebMusicRadioPlayWidget::radioResourceDownload(), MusicDownloadResetWidget::restartToDownload(), and MusicDownloadMgmtWidget::setSongName().
void MusicDownloadWidget::startToDownload () slot
Start to download music data.
hide download widget
Definition at line 406 of file musicdownloadwidget.cpp.
References controlEnable(), MusicMessageBox::exec(), m_downloadOffset, m_downloadTotal, m_querySingleInfo, m_queryType, m_singleSongInfo, m_ui, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicDownLoadQueryThreadAbstract::MusicQuery, startToDownloadMovie(), and startToDownloadMusic().
Referenced by MusicDownloadWidget().
void MusicDownloadWidget::startToDownloadMovie () protected
Strat to download movie.
Definition at line 517 of file musicdownloadwidget.cpp.
References getMatchMusicSongInformation(), MusicObject::MusicSongInformation::m_singerName, and MusicObject::MusicSongInformation::m_songName.
Referenced by startToDownload().
void MusicDownloadWidget::startToDownloadMovie (const MusicObject::MusicSongInformation & musicSongInfo) protected
Strat to download movie.
Definition at line 526 of file musicdownloadwidget.cpp.
References dataDownloadFinished(), MusicObject::DownloadVideo, MusicDownloadTableItemRole::isEqual(), MusicObject::MusicSongAttribute::m_bitrate, m_downloadTotal, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_multiPart, M_NETWORK_PTR, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, m_ui, MusicObject::MusicSongAttribute::m_url, MOVIE_DIR_FULL, MusicDataDownloadThread::startToDownload(), and TTK_STR_SPLITER.
void MusicDownloadWidget::startToDownloadMusic () protected
Strat to download music.
Definition at line 439 of file musicdownloadwidget.cpp.
References getMatchMusicSongInformation(), MusicObject::MusicSongInformation::m_singerName, and MusicObject::MusicSongInformation::m_songName.
Referenced by startToDownload().
void MusicDownloadWidget::startToDownloadMusic (const MusicObject::MusicSongInformation & musicSongInfo) protected
Strat to download music.
Definition at line 448 of file musicdownloadwidget.cpp.
References dataDownloadFinished(), MusicObject::DownloadMusic, MusicDownloadTableItemRole::isEqual(), MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongAttribute::m_bitrate, m_downloadTotal, MusicObject::MusicSongAttribute::m_format, M_NETWORK_PTR, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_trackNumber, m_ui, MusicObject::MusicSongAttribute::m_url, MusicObject::MusicSongInformation::m_year, MUSIC_DIR_FULL, MusicDownloadRecordConfigManager::readConfig(), MusicDownloadRecordConfigManager::readDownloadData(), MusicObject::RecordNormalDownload, MusicSongTag::setAlbum(), MusicSongTag::setArtist(), MusicSongTag::setComment(), MusicSong::setMusicAddTimeStr(), MusicSong::setMusicName(), MusicSong::setMusicPath(), MusicSong::setMusicSizeStr(), MusicDataDownloadThread::setRecordType(), MusicDataTagDownloadThread::setSongTag(), MusicSongTag::setTitle(), MusicSongTag::setTrackNum(), MusicSongTag::setYear(), MusicDataTagDownloadThread::startToDownload(), and MusicDownloadRecordConfigManager::writeDownloadData().
Member Data Documentation
int MusicDownloadWidget::m_downloadOffset protected
Definition at line 252 of file musicdownloadwidget.h.
Referenced by dataDownloadFinished(), MusicDownloadWidget(), and startToDownload().
MusicDownLoadQueryThreadAbstract* MusicDownloadWidget::m_downloadThread protected
Definition at line 253 of file musicdownloadwidget.h.
Referenced by getMatchMusicSongInformation(), MusicDownloadWidget(), setSongName(), and ~MusicDownloadWidget().
int MusicDownloadWidget::m_downloadTotal protected
Definition at line 252 of file musicdownloadwidget.h.
Referenced by dataDownloadFinished(), MusicDownloadWidget(), startToDownload(), startToDownloadMovie(), and startToDownloadMusic().
bool MusicDownloadWidget::m_querySingleInfo protected
Definition at line 251 of file musicdownloadwidget.h.
Referenced by MusicDownloadWidget(), setSongName(), and startToDownload().
MusicDownLoadQueryThreadAbstract::QueryType MusicDownloadWidget::m_queryType protected
Definition at line 254 of file musicdownloadwidget.h.
Referenced by downloadDirSelected(), initWidget(), MusicDownloadWidget(), queryAllFinished(), setSongName(), and startToDownload().
MusicObject::MusicSongInformation MusicDownloadWidget::m_singleSongInfo protected
Definition at line 255 of file musicdownloadwidget.h.
Referenced by setSongName(), and startToDownload().
Ui::MusicDownloadWidget* MusicDownloadWidget::m_ui protected
Definition at line 250 of file musicdownloadwidget.h.
Referenced by controlEnable(), downloadDirSelected(), initWidget(), MusicDownloadWidget(), queryAllFinished(), queryAllFinishedMovie(), queryAllFinishedMusic(), resizeWindow(), setSongName(), show(), startToDownload(), startToDownloadMovie(), startToDownloadMusic(), and ~MusicDownloadWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadwidget.cpp