TTKMusicplayer: MusicWebFMRadioWidget Class Reference
MusicWebFMRadioWidget Class Reference
The class of the web music radio list widget.
#include <musicwebfmradiowidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
void itemDoubleClicked (int row, int column)
void addListWidgetItem ()
void downLoadFinished (const QByteArray &bytes)
void musicPlayClicked ()
void sendToDesktopLink ()
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Public Member Functions
MusicWebFMRadioWidget (QWidget *parent=nullptr)
~MusicWebFMRadioWidget ()
void initialize (int index)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
void clear ()
TTKIntList multiSelectedIndex () const
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
int m_outerIndex
MusicWebFMRadioPlayWidget * m_fmRadio
MusicFMRadioChannelRequest * m_channelThread
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_backgroundColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the web music radio list widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicwebfmradiowidget.h.
Constructor & Destructor Documentation
MusicWebFMRadioWidget::MusicWebFMRadioWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 18 of file musicwebfmradiowidget.cpp.
References ICON_SIZE, itemDoubleClicked(), m_outerIndex, MusicUIObject::MQSSScrollBarStyle03, and MusicUtils::Widget::setTransparent().
MusicWebFMRadioWidget::~MusicWebFMRadioWidget ()
Definition at line 41 of file musicwebfmradiowidget.cpp.
References m_channelThread, and m_fmRadio.
Member Function Documentation
void MusicWebFMRadioWidget::addListWidgetItem () slot
Add radio list into list widget.
Definition at line 116 of file musicwebfmradiowidget.cpp.
References DEFAULT_NORMAL_LEVEL, downLoadFinished(), ITEM_ROW_HEIGHT_XL, itemDoubleClicked(), m_channelThread, m_outerIndex, MUSIC_DATA_ROLE, MusicFMRadioChannelRequest::musicChannel(), MusicUtils::Image::pixmapToRound(), MusicAbstractNetwork::setHeader(), MusicDownloadSourceRequest::startToDownload(), and TTK_NULL_STR.
Referenced by initialize().
void MusicWebFMRadioWidget::contextMenuEvent (QContextMenuEvent * event) final override protected virtual
Override the widget event.
Definition at line 227 of file musicwebfmradiowidget.cpp.
References MusicUIObject::MQSSMenuStyle02, musicPlayClicked(), and sendToDesktopLink().
void MusicWebFMRadioWidget::downLoadFinished (const QByteArray & bytes) slot
Send recieved data from net.
Definition at line 166 of file musicwebfmradiowidget.cpp.
References MusicAbstractNetwork::header(), MusicUtils::Image::pixmapToRound(), TTK_LOGGER_ERROR, and TTKStatic_cast.
Referenced by addListWidgetItem().
void MusicWebFMRadioWidget::initialize (int index)
To init list items.
Definition at line 47 of file musicwebfmradiowidget.cpp.
References addListWidgetItem(), m_channelThread, m_outerIndex, and MusicFMRadioChannelRequest::startToDownload().
Referenced by MusicWebRadioView::initialize().
void MusicWebFMRadioWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 84 of file musicwebfmradiowidget.cpp.
References DEFAULT_NORMAL_LEVEL, and itemDoubleClicked().
void MusicWebFMRadioWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 59 of file musicwebfmradiowidget.cpp.
References MusicAbstractTableWidget::itemCellEntered(), and MusicAbstractTableWidget::m_previousColorRow.
void MusicWebFMRadioWidget::itemDoubleClicked (int row, int column) slot
Table widget item cell double click.
Definition at line 94 of file musicwebfmradiowidget.cpp.
References m_channelThread, m_fmRadio, MusicFMRadioChannelRequest::musicChannel(), MusicWebFMRadioPlayWidget::show(), and MusicWebFMRadioPlayWidget::updateRadioSong().
Referenced by addListWidgetItem(), itemCellClicked(), musicPlayClicked(), and MusicWebFMRadioWidget().
void MusicWebFMRadioWidget::musicPlayClicked () slot
Music item has been clicked.
Definition at line 189 of file musicwebfmradiowidget.cpp.
References DEFAULT_NORMAL_LEVEL, and itemDoubleClicked().
Referenced by contextMenuEvent().
void MusicWebFMRadioWidget::sendToDesktopLink () slot
Send to desktop link.
Definition at line 198 of file musicwebfmradiowidget.cpp.
References APP_EXE_NAME, APP_NAME, MusicObject::applicationPath(), MAIN_DIR_FULL, MUSIC_OUTSIDE_RADIO, MusicPlatformManager::setFileLink(), and TTK_SEPARATOR.
Referenced by contextMenuEvent().
Member Data Documentation
MusicFMRadioChannelRequest* MusicWebFMRadioWidget::m_channelThread protected
Definition at line 84 of file musicwebfmradiowidget.h.
Referenced by addListWidgetItem(), initialize(), itemDoubleClicked(), and ~MusicWebFMRadioWidget().
MusicWebFMRadioPlayWidget* MusicWebFMRadioWidget::m_fmRadio protected
Definition at line 83 of file musicwebfmradiowidget.h.
Referenced by itemDoubleClicked(), and ~MusicWebFMRadioWidget().
int MusicWebFMRadioWidget::m_outerIndex protected
Definition at line 82 of file musicwebfmradiowidget.h.
Referenced by addListWidgetItem(), initialize(), and MusicWebFMRadioWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebfmradiowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebfmradiowidget.cpp