TTKMusicplayer: MusicAbstractMoveWidget Class Reference
MusicAbstractMoveWidget Class Reference
The class of the moving widget base.
#include <musicabstractmovewidget.h>
Public Slots
void backgroundChanged ()
Public Member Functions
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the moving widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 19 of file musicabstractmovewidget.h.
Constructor & Destructor Documentation
MusicAbstractMoveWidget::MusicAbstractMoveWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 12 of file musicabstractmovewidget.cpp.
MusicAbstractMoveWidget::MusicAbstractMoveWidget (bool transparent, QWidget * parent = 0) explicit
Object contsructor.
Remove the title bar
Definition at line 18 of file musicabstractmovewidget.cpp.
References m_background, M_BACKGROUND_PTR, m_leftButtonPress, m_moveOption, and m_showShadow.
MusicAbstractMoveWidget::~MusicAbstractMoveWidget () virtual
Definition at line 33 of file musicabstractmovewidget.cpp.
References M_BACKGROUND_PTR.
Member Function Documentation
void MusicAbstractMoveWidget::backgroundChanged () slot
Background image changed.
Definition at line 43 of file musicabstractmovewidget.cpp.
References m_background, and setBackgroundPixmap().
void MusicAbstractMoveWidget::blockMoveOption (bool block) inline
Set or not block widget moving.
Definition at line 45 of file musicabstractmovewidget.h.
Referenced by MusicSoundKMicroSearchWidget::MusicSoundKMicroSearchWidget(), MusicSourceUpdateNotifyWidget::MusicSourceUpdateNotifyWidget(), MusicRightAreaWidget::musicVideoFullscreen(), and MusicVideoPlayWidget::popup().
void MusicAbstractMoveWidget::drawWindowShadow (bool show) inline
Set or not draw window bound shadow.
Definition at line 41 of file musicabstractmovewidget.h.
Referenced by MusicNetworkSpeedSuspensionWidget::MusicNetworkSpeedSuspensionWidget(), and MusicRemoteWidget::MusicRemoteWidget().
QString MusicAbstractMoveWidget::getClassName () static
Get class object name.
Definition at line 38 of file musicabstractmovewidget.cpp.
void MusicAbstractMoveWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Not press the left key
Reimplemented in MusicSoundKMicroWidget.
Definition at line 85 of file musicabstractmovewidget.cpp.
References m_leftButtonPress, and m_pressAt.
Referenced by MusicSoundKMicroWidget::mouseMoveEvent().
void MusicAbstractMoveWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Press the left key
Definition at line 75 of file musicabstractmovewidget.cpp.
References m_leftButtonPress, m_moveOption, and m_pressAt.
void MusicAbstractMoveWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 99 of file musicabstractmovewidget.cpp.
References m_leftButtonPress, and m_pressAt.
void MusicAbstractMoveWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicSoundKMicroWidget, MusicNetworkSpeedSuspensionWidget, MusicRemoteWidgetForCircle, and MusicRemoteWidgetForDiamond.
Definition at line 51 of file musicabstractmovewidget.cpp.
References HEIGHT, m_showShadow, and WIDTH.
Referenced by MusicRemoteWidgetForCircle::paintEvent(), MusicRemoteWidgetForDiamond::paintEvent(), MusicNetworkSpeedSuspensionWidget::paintEvent(), and MusicSoundKMicroWidget::paintEvent().
void MusicAbstractMoveWidget::setBackgroundPixmap (QLabel * label, const QSize & size) protected
Set background pixmap.
Definition at line 106 of file musicabstractmovewidget.cpp.
References m_background.
Referenced by MusicSpectrumWidget::adjustWidgetLayout(), backgroundChanged(), MusicDownloadWidget::resizeWindow(), MusicSoundTouchWidget::show(), MusicDownloadResetWidget::show(), MusicToolSetsWidget::show(), MusicSpectrumWidget::show(), MusicVolumeGainWidget::show(), MusicDesktopWallpaperWidget::show(), MusicAudioRecorderWidget::show(), MusicWebMusicRadioWidget::show(), MusicNetworkConnectionTestWidget::show(), MusicSongCheckToolsWidget::show(), MusicLrcMakerWidget::show(), MusicLocalSongsManagerWidget::show(), and MusicDownloadWidget::show().
void MusicAbstractMoveWidget::setBackgroundPixmap (const QSize & size) protected
Set background pixmap.
Definition at line 112 of file musicabstractmovewidget.cpp.
References m_background, M_BACKGROUND_PTR, MusicBackgroundImage::m_pix, MStatic_cast, and MusicExtractWrap::outputSkin().
Member Data Documentation
QWidget* MusicAbstractMoveWidget::m_background protected
Definition at line 73 of file musicabstractmovewidget.h.
Referenced by backgroundChanged(), MusicAbstractMoveWidget(), and setBackgroundPixmap().
bool MusicAbstractMoveWidget::m_leftButtonPress protected
Definition at line 72 of file musicabstractmovewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and MusicAbstractMoveWidget().
bool MusicAbstractMoveWidget::m_moveOption protected
Definition at line 71 of file musicabstractmovewidget.h.
Referenced by mousePressEvent(), and MusicAbstractMoveWidget().
QPoint MusicAbstractMoveWidget::m_pressAt protected
Definition at line 70 of file musicabstractmovewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool MusicAbstractMoveWidget::m_showShadow protected
Definition at line 71 of file musicabstractmovewidget.h.
Referenced by MusicAbstractMoveWidget(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicabstractmovewidget.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicabstractmovewidget.cpp