TTKMusicPlayer: MusicConnectLocalWidget Class Reference
MusicConnectLocalWidget Class Reference
The class of the connect local widget.
#include <musicconnectlocalwidget.h>
Public Member Functions
MusicConnectLocalWidget (QWidget *parent=nullptr)
~MusicConnectLocalWidget ()
Private Slots
void changeStatckedWidgetFirst ()
void changeStatckedWidgetSecond ()
void changeStatckedWidgetThird ()
void openTransferFilesToMobile ()
void deviceTypeChanged (QAction *action)
void updateDeviceInfo ()
Private Member Functions
void initFirstWidget ()
void initSecondWidget ()
void updateDeviceDisplay (const QString &text)
Private Attributes
QLabel * m_deviceInfoLabel
QPushButton * m_deviceButton
MusicTextSliderWidget * m_deviceSizeLabel
MusicDeviceInfoItem m_currentDeviceItem
MusicDeviceInfoModule * m_deviceInfo
MusicLocalManagerWidget * m_mediaWidget
MusicAnimationStackedWidget * m_stackedWidget
Detailed Description
The class of the connect local widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicconnectlocalwidget.h.
Constructor & Destructor Documentation
MusicConnectLocalWidget::MusicConnectLocalWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 12 of file musicconnectlocalwidget.cpp.
References LEFT_SIDE_WIDTH_MIN, and MusicAnimationStackedWidget::LeftToRight.
MusicConnectLocalWidget::~MusicConnectLocalWidget ()
Object destructor.
Definition at line 31 of file musicconnectlocalwidget.cpp.
References m_deviceInfo, m_mediaWidget, and m_stackedWidget.
Member Function Documentation
void MusicConnectLocalWidget::changeStatckedWidgetFirst () private slot
Change to main widget.
Definition at line 174 of file musicconnectlocalwidget.cpp.
References m_stackedWidget, and MusicAnimationStackedWidget::start().
Referenced by initSecondWidget().
void MusicConnectLocalWidget::changeStatckedWidgetSecond () private slot
Change to wireless widget.
Definition at line 179 of file musicconnectlocalwidget.cpp.
References m_stackedWidget, and MusicAnimationStackedWidget::start().
Referenced by initFirstWidget().
void MusicConnectLocalWidget::changeStatckedWidgetThird () private slot
Change to media library widget.
Definition at line 184 of file musicconnectlocalwidget.cpp.
References MusicRightAreaWidget::functionClicked(), MusicRightAreaWidget::instance(), MusicRightAreaWidget::LocalManagerWidget, and m_mediaWidget.
Referenced by initFirstWidget().
void MusicConnectLocalWidget::deviceTypeChanged (QAction * action) private slot
Device type changed.
Definition at line 206 of file musicconnectlocalwidget.cpp.
References m_currentDeviceItem, and updateDeviceDisplay().
Referenced by initSecondWidget().
void MusicConnectLocalWidget::initFirstWidget () private
Init main widget.
Definition at line 38 of file musicconnectlocalwidget.cpp.
References changeStatckedWidgetSecond(), changeStatckedWidgetThird(), TTK::UI::ColorStyle02, TTK::UI::FontStyle04, m_stackedWidget, TTK::UI::PushButtonStyle08, and TTK::UI::PushButtonStyle13.
void MusicConnectLocalWidget::initSecondWidget () private
Init connect to wireless widget.
Definition at line 78 of file musicconnectlocalwidget.cpp.
References changeStatckedWidgetFirst(), deviceTypeChanged(), TTK::UI::FontStyle03, m_deviceButton, m_deviceInfoLabel, m_deviceSizeLabel, m_stackedWidget, TTK::UI::MenuStyle02, openTransferFilesToMobile(), TTK::UI::PushButtonStyle09, TTK::UI::TransferChangedDev, TTK::UI::TransferRefreshDev, TTK::UI::TransferRing, TTK::UI::TransferSong, and updateDeviceInfo().
void MusicConnectLocalWidget::openTransferFilesToMobile () private slot
Open transfer files to mobile widget.
Definition at line 194 of file musicconnectlocalwidget.cpp.
References MusicAbstractMoveDialog::exec(), MusicDeviceInfoItem::isValid(), m_currentDeviceItem, and MusicConnectTransferWidget::setDeviceInfoItem().
Referenced by initSecondWidget().
void MusicConnectLocalWidget::updateDeviceDisplay (const QString & text) private
Update device label display.
Definition at line 163 of file musicconnectlocalwidget.cpp.
References TTK::Widget::elidedText(), m_currentDeviceItem, m_deviceInfoLabel, m_deviceSizeLabel, MusicDeviceInfoItem::m_totalBytes, MusicDeviceInfoItem::m_usedBytes, MusicTextSliderWidget::setBackText(), MusicTextSliderWidget::setFrontText(), MusicTextSliderWidget::setMaxValue(), and MusicTextSliderWidget::setValue().
Referenced by deviceTypeChanged(), and updateDeviceInfo().
void MusicConnectLocalWidget::updateDeviceInfo () private slot
Update device info.
Definition at line 212 of file musicconnectlocalwidget.cpp.
References MusicDeviceInfoItem::clear(), m_currentDeviceItem, m_deviceButton, m_deviceInfo, MusicDeviceInfoModule::removableDrive(), and updateDeviceDisplay().
Referenced by initSecondWidget().
Member Data Documentation
MusicDeviceInfoItem MusicConnectLocalWidget::m_currentDeviceItem private
Definition at line 89 of file musicconnectlocalwidget.h.
Referenced by deviceTypeChanged(), openTransferFilesToMobile(), updateDeviceDisplay(), and updateDeviceInfo().
QPushButton* MusicConnectLocalWidget::m_deviceButton private
Definition at line 87 of file musicconnectlocalwidget.h.
Referenced by initSecondWidget(), and updateDeviceInfo().
MusicDeviceInfoModule* MusicConnectLocalWidget::m_deviceInfo private
Definition at line 90 of file musicconnectlocalwidget.h.
Referenced by updateDeviceInfo(), and ~MusicConnectLocalWidget().
QLabel* MusicConnectLocalWidget::m_deviceInfoLabel private
Definition at line 86 of file musicconnectlocalwidget.h.
Referenced by initSecondWidget(), and updateDeviceDisplay().
MusicTextSliderWidget* MusicConnectLocalWidget::m_deviceSizeLabel private
Definition at line 88 of file musicconnectlocalwidget.h.
Referenced by initSecondWidget(), and updateDeviceDisplay().
MusicLocalManagerWidget* MusicConnectLocalWidget::m_mediaWidget private
Definition at line 91 of file musicconnectlocalwidget.h.
Referenced by changeStatckedWidgetThird(), and ~MusicConnectLocalWidget().
MusicAnimationStackedWidget* MusicConnectLocalWidget::m_stackedWidget private
Definition at line 92 of file musicconnectlocalwidget.h.
Referenced by changeStatckedWidgetFirst(), changeStatckedWidgetSecond(), initFirstWidget(), initSecondWidget(), and ~MusicConnectLocalWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicconnectlocalwidget.h
TTKModule/TTKWidget/musicToolsKits/musicconnectlocalwidget.cpp