TTKMusicplayer: MusicKWQueryInterface Class Reference
MusicKWQueryInterface Class Reference
The class of kuwo query interface.
#include <musickwqueryinterface.h>
Public Member Functions
void readFromMusicHighProperty (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate) const
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate) const
void readFromMusicSongPropertyNew (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate) const
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, const QString &format, MusicObject::QueryQuality quality, bool all) const
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, const QVariantList &format, MusicObject::QueryQuality quality, bool all) const
Detailed Description
The class of kuwo query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 77 of file musickwqueryinterface.h.
Member Function Documentation
void MusicKWQueryInterface::readFromMusicHighProperty (MusicObject::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) const
Read high info property from query results.
Definition at line 13 of file musickwqueryinterface.cpp.
References _SIGN, ALG_UNIMP_KEY, QAlgorithm::Des::encrypt(), KW_MOVIE_URL, KW_SONG_DETAIL_DATA_URL, MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongProperty::m_size, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::syncNetworkQueryForGet(), and TTK_DEFAULT_STR.
Referenced by readFromMusicSongProperty(), and readFromMusicSongPropertyNew().
void MusicKWQueryInterface::readFromMusicSongProperty (MusicObject::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) const
Read tags(size) from query results.
Definition at line 55 of file musickwqueryinterface.cpp.
References APE_FILE_PREFIX, FLAC_FILE_PREFIX, KW_SONG_DETAIL_URL, MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongProperty::m_size, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), MP3_FILE_PREFIX, readFromMusicHighProperty(), and TTK_DEFAULT_STR.
Referenced by MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), and readFromMusicSongProperty().
void MusicKWQueryInterface::readFromMusicSongProperty (MusicObject::MusicSongInformation * info, const QString & format, MusicObject::QueryQuality quality, bool all) const
Read tags(size) from query results.
Definition at line 133 of file musickwqueryinterface.cpp.
References APE_FILE_PREFIX, FLAC_FILE_PREFIX, MusicObject::High, MusicObject::Lossless, MB_1000, MB_128, MB_192, MB_320, MB_750, MP3_FILE_PREFIX, readFromMusicSongProperty(), MusicObject::Standard, and MusicObject::Super.
void MusicKWQueryInterface::readFromMusicSongProperty (MusicObject::MusicSongInformation * info, const QVariantList & format, MusicObject::QueryQuality quality, bool all) const
Read tags(size) from query results.
Definition at line 165 of file musickwqueryinterface.cpp.
References APE_FILE_PREFIX, FLAC_FILE_PREFIX, MusicObject::High, MusicObject::Lossless, MB_1000, MB_128, MB_192, MB_320, MB_750, MP3_FILE_PREFIX, readFromMusicSongPropertyNew(), MusicObject::Standard, and MusicObject::Super.
void MusicKWQueryInterface::readFromMusicSongPropertyNew (MusicObject::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) const
Read tags(size) from query results.
Definition at line 94 of file musickwqueryinterface.cpp.
References APE_FILE_PREFIX, FLAC_FILE_PREFIX, KW_SONG_DETAIL_URL, MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongProperty::m_size, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), MP3_FILE_PREFIX, readFromMusicHighProperty(), and TTK_DEFAULT_STR.
Referenced by readFromMusicSongProperty().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryinterface.cpp