TTKMusicPlayer: TTK::Image Namespace Reference
TTK::Image Namespace Reference
Functions
TTK_MODULE_EXPORT QPixmap roundedPixmap (const QPixmap &input, int ratioX, int ratioY)
TTK_MODULE_EXPORT QPixmap roundedPixmap (const QPixmap &input, const QSize &size, int ratioX, int ratioY)
TTK_MODULE_EXPORT QPixmap roundedPixmap (const QPixmap &input, const QRect &rect, int ratioX, int ratioY)
TTK_MODULE_EXPORT QPixmap roundedPixmap (const QPixmap &input, const QPixmap &mask, const QSize &size)
TTK_MODULE_EXPORT QBitmap generateMask (const QRect &rect, int ratioX, int ratioY)
TTK_MODULE_EXPORT QByteArray generatePixmapData (const QPixmap &input)
TTK_MODULE_EXPORT void fusionPixmap (QImage &back, const QImage &front, const QPoint &pt)
TTK_MODULE_EXPORT void fusionPixmap (QPixmap &back, const QPixmap &front, const QPoint &pt)
TTK_MODULE_EXPORT unsigned int colorContrast (const unsigned int color)
TTK_MODULE_EXPORT QPixmap grayScalePixmap (const QPixmap &input, int radius=0)
template<typename T >
TTK_MODULE_EXPORT T boundValue (const T &key, const T &alpha, const T &value)
TTK_MODULE_EXPORT void reRenderImage (int delta, const QImage *input, QImage *output)
Function Documentation
template<typename T > TTK_MODULE_EXPORT T TTK::Image::boundValue (const T & key, const T & alpha, const T & value)
Rerender the bound value.
Definition at line 79 of file musicimageutils.h.
References alpha, key, TTK_RN_MAX, and TTK_RN_MIN.
TTK_MODULE_EXPORT unsigned int TTK::Image::colorContrast (const unsigned int color)
Counting the perceptive luminance.
Referenced by MusicSongDailyWidget::downLoadImageFinished().
void TTK::Image::fusionPixmap (QImage & back, const QImage & front, const QPoint & pt)
Set fusion two image.
Definition at line 72 of file musicimageutils.cpp.
Referenced by MusicScreenSaverBackgroundWidget::backgroundTimeout(), and MusicAbstractItemQueryWidget::downLoadFinished().
void TTK::Image::fusionPixmap (QPixmap & back, const QPixmap & front, const QPoint & pt)
Set fusion two pixmap.
Definition at line 84 of file musicimageutils.cpp.
QBitmap TTK::Image::generateMask (const QRect & rect, int ratioX, int ratioY)
Get bitmap mask from rect.
Definition at line 44 of file musicimageutils.cpp.
Referenced by roundedPixmap(), and TTK::Widget::widgetToRound().
QByteArray TTK::Image::generatePixmapData (const QPixmap & input)
Get pximap data.
Definition at line 55 of file musicimageutils.cpp.
References JPG_FILE_SUFFIX.
Referenced by MusicExtractWrapper::inputSkin().
QPixmap TTK::Image::grayScalePixmap (const QPixmap & input, int radius = 0)
Image gray scale.
Definition at line 105 of file musicimageutils.cpp.
Referenced by MusicScreenSaverHoverItem::switchButtonState().
void TTK::Image::reRenderImage (int delta, const QImage * input, QImage * output)
Rerender the image by color burn transform.
Definition at line 140 of file musicimageutils.cpp.
References colorBurnTransform().
Referenced by MusicTopAreaWidget::drawWindowBackground().
QPixmap TTK::Image::roundedPixmap (const QPixmap & input, int ratioX, int ratioY)
Set pixmap to round by ratio.
Definition at line 7 of file musicimageutils.cpp.
Referenced by MusicSpectrumLayoutItem::addCellItem(), MusicWebFMRadioWidget::addCelltItems(), MusicLrcPosterItemWidget::drawTheme6(), MusicWebFMRadioPlayWidget::picDownloadStateChanged(), roundedPixmap(), MusicLrcFloatPhotoItem::setPath(), and MusicTopAreaWidget::setupUi().
QPixmap TTK::Image::roundedPixmap (const QPixmap & input, const QSize & size, int ratioX, int ratioY)
Set pixmap to round by ratio.
Definition at line 12 of file musicimageutils.cpp.
References roundedPixmap().
QPixmap TTK::Image::roundedPixmap (const QPixmap & input, const QRect & rect, int ratioX, int ratioY)
Set pixmap to round by ratio.
Definition at line 17 of file musicimageutils.cpp.
References generateMask().
QPixmap TTK::Image::roundedPixmap (const QPixmap & input, const QPixmap & mask, const QSize & size)
Set pixmap to round by ratio.
Definition at line 29 of file musicimageutils.cpp.