TTKMusicplayer: MusicSongsListPlayedWidget Class Reference
MusicSongsListPlayedWidget Class Reference
The class of the song list played widget.
#include <musicsongslistplayedwidget.h>
Public Slots
void setDeleteItemAt ()
Signals
void enterChanged (int row, int column)
Public Member Functions
MusicSongsListPlayedWidget (int index, QWidget *parent=nullptr)
~MusicSongsListPlayedWidget ()
void setParameter (const QString &name)
Protected Member Functions
virtual void enterEvent (QEvent *event) overridefinal
void createMoreMenu (QMenu *menu)
Protected Attributes
int m_currentPlayIndex
QWidget * m_parentClass
QLabel * m_textLabel
MusicGifLabelWidget * m_gifLabel
QPushButton * m_deleteButton
QPushButton * m_downloadButton
QPushButton * m_moreButton
Detailed Description
The class of the song list played widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicsongslistplayedwidget.h.
Constructor & Destructor Documentation
MusicSongsListPlayedWidget::MusicSongsListPlayedWidget (int index, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicsongslistplayedwidget.cpp.
References createMoreMenu(), enterChanged(), MusicGifLabelWidget::Gif_Radio_Blue, MusicLeftAreaWidget::instance(), m_currentPlayIndex, m_deleteButton, m_downloadButton, m_gifLabel, m_moreButton, m_parentClass, m_textLabel, MusicUIObject::MQSSColorStyle11, MusicUIObject::MQSSPushButtonStyle13, MusicUIObject::MQSSTinyBtnDelete, MusicUIObject::MQSSTinyBtnMore, MusicUIObject::MQSSTinyBtnUnDownload, setDeleteItemAt(), and MusicGifLabelWidget::setInterval().
MusicSongsListPlayedWidget::~MusicSongsListPlayedWidget ()
Definition at line 62 of file musicsongslistplayedwidget.cpp.
References m_deleteButton, m_downloadButton, m_gifLabel, m_moreButton, and m_textLabel.
Member Function Documentation
void MusicSongsListPlayedWidget::createMoreMenu (QMenu * menu) protected
Create more menu information.
Definition at line 93 of file musicsongslistplayedwidget.cpp.
References m_parentClass, and MusicUIObject::MQSSMenuStyle02.
Referenced by MusicSongsListPlayedWidget().
void MusicSongsListPlayedWidget::enterChanged (int row, int column) signal
Mouse is the item geometry, emit row and column.
Referenced by MusicSongsListPlayedWidget().
void MusicSongsListPlayedWidget::enterEvent (QEvent * event) final override protected virtual
Override the widget event.
Definition at line 86 of file musicsongslistplayedwidget.cpp.
void MusicSongsListPlayedWidget::setDeleteItemAt () slot
Delete item from list at current row.
Definition at line 78 of file musicsongslistplayedwidget.cpp.
References m_parentClass, and MT_MS.
Referenced by MusicSongsListPlayedWidget().
void MusicSongsListPlayedWidget::setParameter (const QString & name)
Update item artist label by name.
Definition at line 71 of file musicsongslistplayedwidget.cpp.
References MusicUtils::Widget::elidedText(), m_gifLabel, m_textLabel, and MusicGifLabelWidget::start().
Referenced by MusicSongsListPlayedTableWidget::selectRow().
Member Data Documentation
int MusicSongsListPlayedWidget::m_currentPlayIndex protected
Definition at line 74 of file musicsongslistplayedwidget.h.
Referenced by MusicSongsListPlayedWidget().
QPushButton* MusicSongsListPlayedWidget::m_deleteButton protected
Definition at line 78 of file musicsongslistplayedwidget.h.
Referenced by MusicSongsListPlayedWidget(), and ~MusicSongsListPlayedWidget().
QPushButton * MusicSongsListPlayedWidget::m_downloadButton protected
Definition at line 78 of file musicsongslistplayedwidget.h.
Referenced by MusicSongsListPlayedWidget(), and ~MusicSongsListPlayedWidget().
MusicGifLabelWidget* MusicSongsListPlayedWidget::m_gifLabel protected
Definition at line 77 of file musicsongslistplayedwidget.h.
Referenced by MusicSongsListPlayedWidget(), setParameter(), and ~MusicSongsListPlayedWidget().
QPushButton * MusicSongsListPlayedWidget::m_moreButton protected
Definition at line 78 of file musicsongslistplayedwidget.h.
Referenced by MusicSongsListPlayedWidget(), and ~MusicSongsListPlayedWidget().
QWidget* MusicSongsListPlayedWidget::m_parentClass protected
Definition at line 75 of file musicsongslistplayedwidget.h.
Referenced by createMoreMenu(), MusicSongsListPlayedWidget(), and setDeleteItemAt().
QLabel* MusicSongsListPlayedWidget::m_textLabel protected
Definition at line 76 of file musicsongslistplayedwidget.h.
Referenced by MusicSongsListPlayedWidget(), setParameter(), and ~MusicSongsListPlayedWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplayedwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplayedwidget.cpp