TTKMusicPlayer: TTK::Core Namespace Reference
TTK::Core Namespace Reference
Functions
TTK_MODULE_EXPORT void sleep (int ms)
TTK_MODULE_EXPORT bool appVersionCheck (const QString &o, const QString &d)
TTK_MODULE_EXPORT void resetBreakPoint ()
TTK_MODULE_EXPORT void enableBreakPoint (bool enable)
TTK_MODULE_EXPORT bool isBreakPointEnabled ()
Function Documentation
bool TTK::Core::appVersionCheck (const QString & o, const QString & d)
App version check.
Definition at line 46 of file musiccoreutils.cpp.
References TTK_DOT, and versionCheck().
Referenced by MusicSourceUpdateNotifyWidget::downLoadFinished(), and MusicSourceUpdateWidget::downLoadFinished().
void TTK::Core::enableBreakPoint (bool enable)
Enable break point.
Definition at line 64 of file musiccoreutils.cpp.
References __BreakPoint__.
Referenced by MusicApplication::quitWindow(), and MusicLocalManagerWidget::refreshItems().
bool TTK::Core::isBreakPointEnabled ()
Break point enabled or not.
Definition at line 69 of file musiccoreutils.cpp.
References __BreakPoint__.
Referenced by TTK::File::copyPath(), TTK::File::fileInfoListByPath(), TTK::File::fileListByPath(), MusicLocalManagerWidget::refreshItems(), and TTK::File::removeRecursively().
void TTK::Core::resetBreakPoint ()
Reset break point.
Definition at line 59 of file musiccoreutils.cpp.
References __BreakPoint__.
void TTK::Core::sleep (int ms)
Sleep by millisecond.
Definition at line 37 of file musiccoreutils.cpp.
References TTK_DN_MS2US.
Referenced by MusicLrcPhotoWidget::exportButtonClicked(), MusicNetworkTestThread::run(), MusicTimerAutoModule::setShutdown(), MusicAbstractDownLoadRequest::updateDownloadSpeed(), and MusicCloudManagerTableWidget::uploadFilesToServer().