TTKMusicplayer: MusicWebRadioObject Class Reference
MusicWebRadioObject Class Reference
The class of the web radio object.
#include <musicwebradioobject.h>
Public Slots
void dataDownloadFinished ()
Signals
void resetFlag (MusicObject::ToolsType flag)
Public Member Functions
MusicWebRadioObject (QObject *parent=0)
void raise ()
void show ()
Static Public Member Functions
static QString getClassName ()
Detailed Description
The class of the web radio object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwebradioobject.h.
Constructor & Destructor Documentation
MusicWebRadioObject::MusicWebRadioObject (QObject * parent = 0) explicit
Object contsructor.
Definition at line 16 of file musicwebradioobject.cpp.
Member Function Documentation
void MusicWebRadioObject::dataDownloadFinished () slot
Send recieved data from net.
Definition at line 49 of file musicwebradioobject.cpp.
References DOWNLOAD_NAME, MusicUtils::Algorithm::mdII(), MusicExtractWrap::outputData(), PLUGINS_DIR_FULL, RADIO_NAME, resetFlag(), MusicAutoTest::run(), and MusicObject::TT_WebRadio.
Referenced by show().
QString MusicWebRadioObject::getClassName () static
Get class object name.
Definition at line 22 of file musicwebradioobject.cpp.
void MusicWebRadioObject::raise ()
Null function.
Definition at line 27 of file musicwebradioobject.cpp.
void MusicWebRadioObject::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by dataDownloadFinished().
void MusicWebRadioObject::show ()
Start to run object.
Definition at line 32 of file musicwebradioobject.cpp.
References dataDownloadFinished(), DOWNLOAD_NAME, DOWNLOAD_URL, MusicDownLoadThreadAbstract::DownloadOther, MusicUtils::Algorithm::mdII(), PLUGINS_DIR_FULL, and MusicDataDownloadThread::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicwebradioobject.h
TTKModule/TTKCore/musicToolsSetsKits/musicwebradioobject.cpp