TTKMusicPlayer: MusicMessageAboutDialog Class Reference
MusicMessageAboutDialog Class Reference
The class of the about application info dialog.
#include <musicmessageaboutdialog.h>
Public Slots
void downloadFinished (const QString &bytes)
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Public Member Functions
MusicMessageAboutDialog (QWidget *parent=nullptr)
~MusicMessageAboutDialog ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockOption (bool block)
Private Attributes
Ui::MusicMessageAboutDialog * m_ui
MusicPVCounterRequest * m_networkRequest
Additional Inherited Members
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Detailed Description
The class of the about application info dialog.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicmessageaboutdialog.h.
Constructor & Destructor Documentation
MusicMessageAboutDialog::MusicMessageAboutDialog (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicmessageaboutdialog.cpp.
References downloadFinished(), m_networkRequest, m_ui, TTK::Algorithm::md5(), TTK::UI::PushButtonStyle04, MusicWidgetRenderer::setBackgroundLabel(), TTK::Algorithm::sha1(), MusicPVCounterRequest::startToRequest(), TTK::UI::ToolButtonStyle04, and TTK_VERSION_STR.
MusicMessageAboutDialog::~MusicMessageAboutDialog ()
Object destructor.
Definition at line 47 of file musicmessageaboutdialog.cpp.
References m_networkRequest, and m_ui.
Member Function Documentation
void MusicMessageAboutDialog::downloadFinished (const QString & bytes) slot
Download data from net finished.
Definition at line 53 of file musicmessageaboutdialog.cpp.
References m_ui.
Referenced by MusicMessageAboutDialog().
Member Data Documentation
MusicPVCounterRequest* MusicMessageAboutDialog::m_networkRequest private
Definition at line 54 of file musicmessageaboutdialog.h.
Referenced by MusicMessageAboutDialog(), and ~MusicMessageAboutDialog().
Ui::MusicMessageAboutDialog* MusicMessageAboutDialog::m_ui private
Definition at line 53 of file musicmessageaboutdialog.h.
Referenced by downloadFinished(), MusicMessageAboutDialog(), and ~MusicMessageAboutDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicmessageaboutdialog.h
TTKModule/TTKWidget/musicWidgetKits/musicmessageaboutdialog.cpp