TTKMusicplayer: MusicDownLoadQueryKGThread Class Reference
MusicDownLoadQueryKGThread Class Reference
The class to kugou query download data from net.
#include <musicdownloadquerykgthread.h>
Public Slots
virtual void downLoadFinished () override
void singleDownLoadFinished ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadQueryKGThread (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToPage (int offset) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=nullptr)
virtual ~MusicDownLoadQueryThreadAbstract ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=nullptr)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
QVariantMap m_headerData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadKGInterface
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &hash)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongLrcAndPic (MusicObject::MusicSongInformation *info)
void readFromMusicSongAlbumInfo (MusicResultsItem *info, const QString &album)
Detailed Description
The class to kugou query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadquerykgthread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryKGThread::MusicDownLoadQueryKGThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdownloadquerykgthread.cpp.
References MusicDownLoadPagingThread::m_pageSize, MusicDownLoadQueryThreadAbstract::m_queryServer, and QUERY_KG_INTERFACE.
Member Function Documentation
void MusicDownLoadQueryKGThread::downLoadFinished () override virtual slot
Download data from net finished.
Get all the data obtained by request
Definition at line 74 of file musicdownloadquerykgthread.cpp.
References MusicDownLoadQueryThreadAbstract::createSearchedItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicUtils::String::illegalCharactersReplaced(), MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_discNumber, MusicNetworkAbstract::m_interrupt, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadPagingThread::m_pageTotal, MusicDownLoadQueryThreadAbstract::m_queryAllRecords, MusicDownLoadQueryThreadAbstract::m_querySimplify, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkQuery, QJson::Parser::parse(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), and TTK_LOGGER_INFO.
Referenced by startToPage().
void MusicDownLoadQueryKGThread::singleDownLoadFinished () slot
Download single data from net finished.
Get all the data obtained by request
Definition at line 154 of file musicdownloadquerykgthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicUtils::String::illegalCharactersReplaced(), KG_SONG_LRC_URL, MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicObject::MusicSongInformation::m_discNumber, MusicNetworkAbstract::m_interrupt, MusicObject::MusicSongInformation::m_lrcUrl, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_searchQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkQuery, QJson::Parser::parse(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), TTK_LOGGER_INFO, and TTKObject_cast.
Referenced by startToSingleSearch().
void MusicDownLoadQueryKGThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 27 of file musicdownloadquerykgthread.cpp.
References ALG_UA_KEY, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), KG_SONG_SEARCH_URL, KG_UA_URL_1, MusicNetworkAbstract::m_interrupt, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageIndex, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicNetworkAbstract::replyError(), MusicObject::setSslConfiguration(), MusicUtils::Codec::toUtf8(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicDownLoadQueryKGThread::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicDownLoadQueryThreadAbstract.
Definition at line 10 of file musicdownloadquerykgthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::m_currentType, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_searchText, startToPage(), and TTK_LOGGER_INFO.
Referenced by MusicKGSongCommentsThread::startToSearch().
void MusicDownLoadQueryKGThread::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicDownLoadQueryThreadAbstract.
Definition at line 52 of file musicdownloadquerykgthread.cpp.
References ALG_UA_KEY, KG_SONG_INFO_URL, KG_UA_URL_1, MusicNetworkAbstract::m_interrupt, MusicNetworkAbstract::m_manager, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicNetworkAbstract::replyError(), MusicObject::setSslConfiguration(), singleDownLoadFinished(), MusicUtils::Codec::toUtf8(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/kg/musicdownloadquerykgthread.h
TTKModule/TTKCore/musicNetworkKits/kg/musicdownloadquerykgthread.cpp