TTKMusicPlayer: TTKModule/TTKCore/musicNetworkKits/music/zed/musicunityqueryinterface.cpp File Reference
musicunityqueryinterface.cpp File Reference
#include "musicunityqueryinterface.h"
Classes
struct Data
The class of the music meta.
Functions
static bool checkModule (const QString &module)
static void parseSongPropertyX (QNetworkRequest *request, TTK::MusicSongInformation *info, int bitrate)
static void parseSongPropertyA (QNetworkRequest *request, TTK::MusicSongInformation *info, int bitrate, const QString &quality)
static void parseSongPropertyB (QNetworkRequest *request, TTK::MusicSongInformation *info, int bitrate)
static void parseSongPropertyC (QNetworkRequest *request, TTK::MusicSongInformation *info, int bitrate, const QString &quality)
static void parseSongPropertyD (QNetworkRequest *request, TTK::MusicSongInformation *info, int bitrate)
static void parseSongPropertyE (QNetworkRequest *request, const QString &body, TTK::MusicSongInformation *info, int bitrate)
Variables
static constexpr const char * QUERY_MODULE_X = "*"
static constexpr const char * QUERY_MODULE_A = "A"
static constexpr const char * QUERY_MODULE_B = "B"
static constexpr const char * QUERY_MODULE_C = "C"
static constexpr const char * QUERY_MODULE_D = "D"
static constexpr const char * QUERY_MODULE_E = "E"
static constexpr const char * QUERY_PLUGINS_URL = "resource/plugins"
Function Documentation
static bool checkModule (const QString & module) static
Definition at line 11 of file musicunityqueryinterface.cpp.
References QUERY_MODULE_A, QUERY_MODULE_B, QUERY_MODULE_C, QUERY_MODULE_D, QUERY_MODULE_E, and QUERY_MODULE_X.
Referenced by ReqUnityInterface::parseFromSongProperty().
static void parseSongPropertyA (QNetworkRequest * request, TTK::MusicSongInformation * info, int bitrate, const QString & quality) static
Definition at line 72 of file musicunityqueryinterface.cpp.
References QJsonParseError::error, FLAC_FILE_SUFFIX, QJsonDocument::fromJson(), TTK::MusicSongProperty::isEmpty(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MP3_FILE_SUFFIX, QJsonParseError::NoError, TTK::syncNetworkQueryForGet(), TTK::toString(), QJsonDocument::toVariant(), TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by ReqUnityInterface::parseFromSongProperty().
static void parseSongPropertyB (QNetworkRequest * request, TTK::MusicSongInformation * info, int bitrate) static
Definition at line 121 of file musicunityqueryinterface.cpp.
References QJsonParseError::error, FLAC_FILE_SUFFIX, QJsonDocument::fromJson(), TTK::MusicSongProperty::isEmpty(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MP3_FILE_SUFFIX, QJsonParseError::NoError, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by ReqUnityInterface::parseFromSongProperty().
static void parseSongPropertyC (QNetworkRequest * request, TTK::MusicSongInformation * info, int bitrate, const QString & quality) static
Definition at line 162 of file musicunityqueryinterface.cpp.
References QJsonParseError::error, FLAC_FILE_SUFFIX, QJsonDocument::fromJson(), TTK::MusicSongProperty::isEmpty(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MP3_FILE_SUFFIX, QJsonParseError::NoError, TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by ReqUnityInterface::parseFromSongProperty().
static void parseSongPropertyD (QNetworkRequest * request, TTK::MusicSongInformation * info, int bitrate) static
Definition at line 204 of file musicunityqueryinterface.cpp.
References FLAC_FILE_SUFFIX, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MP3_FILE_SUFFIX, TTK::syncNetworkQueryForGet(), TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by ReqUnityInterface::parseFromSongProperty().
static void parseSongPropertyE (QNetworkRequest * request, const QString & body, TTK::MusicSongInformation * info, int bitrate) static
Definition at line 226 of file musicunityqueryinterface.cpp.
References QJsonParseError::error, FLAC_FILE_SUFFIX, QJsonDocument::fromJson(), TTK::MusicSongProperty::isEmpty(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MP3_FILE_SUFFIX, QJsonParseError::NoError, TTK::syncNetworkQueryForPost(), QJsonDocument::toVariant(), TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by ReqUnityInterface::parseFromSongProperty().
static void parseSongPropertyX (QNetworkRequest * request, TTK::MusicSongInformation * info, int bitrate) static
Definition at line 31 of file musicunityqueryinterface.cpp.
References QJsonParseError::error, FLAC_FILE_SUFFIX, QJsonDocument::fromJson(), TTK::MusicSongProperty::isEmpty(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MP3_FILE_SUFFIX, QJsonParseError::NoError, TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by ReqUnityInterface::parseFromSongProperty().
Variable Documentation
constexpr const char* QUERY_MODULE_A = "A" static
Definition at line 4 of file musicunityqueryinterface.cpp.
Referenced by checkModule(), and ReqUnityInterface::parseFromSongProperty().
constexpr const char* QUERY_MODULE_B = "B" static
Definition at line 5 of file musicunityqueryinterface.cpp.
Referenced by checkModule(), and ReqUnityInterface::parseFromSongProperty().
constexpr const char* QUERY_MODULE_C = "C" static
Definition at line 6 of file musicunityqueryinterface.cpp.
Referenced by checkModule(), and ReqUnityInterface::parseFromSongProperty().
constexpr const char* QUERY_MODULE_D = "D" static
Definition at line 7 of file musicunityqueryinterface.cpp.
Referenced by checkModule(), and ReqUnityInterface::parseFromSongProperty().
constexpr const char* QUERY_MODULE_E = "E" static
Definition at line 8 of file musicunityqueryinterface.cpp.
Referenced by checkModule(), and ReqUnityInterface::parseFromSongProperty().
constexpr const char* QUERY_MODULE_X = "*" static
Definition at line 3 of file musicunityqueryinterface.cpp.
Referenced by checkModule(), and ReqUnityInterface::parseFromSongProperty().
constexpr const char* QUERY_PLUGINS_URL = "resource/plugins" static
Definition at line 9 of file musicunityqueryinterface.cpp.
Referenced by ReqUnityInterface::parseFromSongProperty().