TTKMusicPlayer: ToolFM Class Reference
ToolFM Class Reference
The class of the qingting fm radio tool.
#include <toolfm.h>
Public Member Functions
ToolFM (QObject *parent=nullptr)
void startToRequest ()
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageTotalSize () const noexcept
int pageSize () const noexcept
int totalSize () const noexcept
int pageIndex () const noexcept
bool pageValid () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Slots
virtual void downLoadFinished () overridefinal
Private Member Functions
void startToListRequest (int id, MusicFMChannelList *channels)
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the qingting fm radio tool.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file toolfm.h.
Constructor & Destructor Documentation
ToolFM::ToolFM (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 15 of file toolfm.cpp.
References MusicPageQueryRequest::m_pageSize.
Member Function Documentation
void ToolFM::downLoadFinished () final override private virtual slot
Download data from net finished.
Definition at line 36 of file toolfm.cpp.
References TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), TTKAbstractNetwork::downLoadFinished(), TTKAbstractXml::load(), MusicFMCategory::m_category, MusicFMCategory::m_items, MusicPageQueryRequest::m_pageIndex, TTKAbstractNetwork::m_reply, QJson::Parser::parse(), qAsConst, startToListRequest(), TTK_INFO_STREAM, TTK_NETWORK_QUERY_CHECK, and MusicFMConfigManager::writeBuffer().
Referenced by startToRequest().
void ToolFM::startToListRequest (int id, MusicFMChannelList * channels) private
Start to download radio list data.
Definition at line 86 of file toolfm.cpp.
References MusicFMChannel::m_name, MusicPageQueryRequest::m_pageIndex, MusicPageQueryRequest::m_totalSize, MusicFMChannel::m_url, makeRequestRawHeader(), TTK::Algorithm::mdII(), MusicPageQueryRequest::pageValid(), QJson::Parser::parse(), qAsConst, QT_CHANNEL_URL, QT_SONG_URL, TTK::syncNetworkQueryForPost(), and TTK_NETWORK_QUERY_CHECK.
Referenced by downLoadFinished().
void ToolFM::startToRequest ()
Start to download radio data.
Definition at line 21 of file toolfm.cpp.
References TTKAbstractNetwork::deleteAll(), downLoadFinished(), TTKAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageIndex, TTKAbstractNetwork::m_reply, makeRequestRawHeader(), TTK::Algorithm::mdII(), QT_CATEGORY_URL, QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK_INFO_STREAM, and TTK_SLOT.
Referenced by main().
The documentation for this class was generated from the following files:
TTKRun/TTKTools/GenerateFM/toolfm.h
TTKRun/TTKTools/GenerateFM/toolfm.cpp