TTKMusicPlayer: MusicCoverRequest Class Reference
MusicCoverRequest Class Reference abstract
The class of the cover data download request.
#include <musiccoverrequest.h>
Public Member Functions
MusicCoverRequest (QObject *parent=nullptr)
virtual void startToRequest (const QString &url)=0
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the cover data download request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musiccoverrequest.h.
Constructor & Destructor Documentation
MusicCoverRequest::MusicCoverRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musiccoverrequest.cpp.
Member Function Documentation
virtual void MusicCoverRequest::startToRequest (const QString & url) pure virtual
Start to download data. Subclass should implement this function.
Implemented in MusicKWCoverSourceRequest, and MusicCoverSourceRequest.
Referenced by MusicCommentsItem::addCellItem(), MusicAlbumQueryWidget::createAlbumItem(), MusicArtistQueryWidget::createArtistItem(), MusicWebMVRadioInfoWidget::createMVRadioProgramItem(), MusicWebDJRadioInfoWidget::createProgramCategoryItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicToplistQueryWidget::createToplistItem(), MusicDownloadMetaDataRequest::downLoadFinished(), MusicSongSharingWidget::initialize(), MusicArtistAlbumsItemWidget::setResultDataItem(), MusicWebDJRadioQueryItemWidget::setResultDataItem(), MusicWebMVRadioQueryItemWidget::setResultDataItem(), MusicWebDJRadioCategoryItemWidget::setResultDataItem(), MusicPlaylistQueryItemWidget::setResultDataItem(), and MusicPlaylistQueryInfoWidget::setResultDataItem().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/core/musiccoverrequest.h
TTKModule/TTKCore/musicNetworkKits/music/core/musiccoverrequest.cpp