TTKMusicplayer: MusicSourceUpdateNotifyWidget Class Reference
MusicSourceUpdateNotifyWidget Class Reference
The class of the application upgrade notify widget.
#include <musicsourceupdatewidget.h>
Public Slots
void updateSourceClicked ()
void downLoadFinished (const QVariant &bytes)
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicSourceUpdateNotifyWidget (QWidget *parent=nullptr)
~MusicSourceUpdateNotifyWidget ()
void start ()
Public Member Functions inherited from MusicAbstractMoveSingleWidget
MusicAbstractMoveSingleWidget (QWidget *parent=nullptr)
MusicAbstractMoveSingleWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveSingleWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
QLabel * m_textLabel
Protected Attributes inherited from MusicAbstractMoveSingleWidget
QWidget * m_container
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the application upgrade notify widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicsourceupdatewidget.h.
Constructor & Destructor Documentation
MusicSourceUpdateNotifyWidget::MusicSourceUpdateNotifyWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 17 of file musicsourceupdatewidget.cpp.
References MusicAbstractMoveWidget::blockMoveOption(), G_SETTING_PTR, MusicAbstractMoveSingleWidget::m_container, m_textLabel, MusicUIObject::MQSSBackgroundStyle17, MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSPushButtonStyle04, MusicSettingManager::ScreenSize, and updateSourceClicked().
MusicSourceUpdateNotifyWidget::~MusicSourceUpdateNotifyWidget ()
Definition at line 63 of file musicsourceupdatewidget.cpp.
References m_textLabel.
Member Function Documentation
void MusicSourceUpdateNotifyWidget::downLoadFinished (const QVariant & bytes) slot
Download data from kuwo net finished.
Definition at line 81 of file musicsourceupdatewidget.cpp.
References MusicUtils::Core::appVersionCheck(), m_textLabel, and TTKMUSIC_VERSION_STR.
Referenced by start().
void MusicSourceUpdateNotifyWidget::start ()
Start update.
Definition at line 68 of file musicsourceupdatewidget.cpp.
References downLoadFinished(), and MusicSourceUpdateRequest::startToDownload().
Referenced by MusicApplicationModule::soureUpdateCheck().
void MusicSourceUpdateNotifyWidget::updateSourceClicked () slot
Update source clicked.
Definition at line 75 of file musicsourceupdatewidget.cpp.
References MusicSourceUpdateWidget::exec().
Referenced by MusicSourceUpdateNotifyWidget().
Member Data Documentation
QLabel* MusicSourceUpdateNotifyWidget::m_textLabel protected
Definition at line 62 of file musicsourceupdatewidget.h.
Referenced by downLoadFinished(), MusicSourceUpdateNotifyWidget(), and ~MusicSourceUpdateNotifyWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsourceupdatewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsourceupdatewidget.cpp