TTKMusicplayer: MusicKGQueryRequest Class Reference
MusicKGQueryRequest Class Reference
The class of kugou query download data from net.
#include <musickgqueryrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void singleDownLoadFinished ()
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKGQueryRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &text) overridefinal
virtual void startToPage (int offset) overridefinal
virtual void startToSingleSearch (const QString &text) overridefinal
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
void setQueryQuality (const QString &qual)
QString queryQuality () const
void setQueryAllRecords (bool state)
bool queryAllRecords () const
void setQuerySimplify (bool state)
bool querySimplify () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & musicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 urlFileSize (const QString &url)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicKGQueryInterface
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &hash)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongLrcAndPicture (MusicObject::MusicSongInformation *info)
void readFromMusicSongAlbumInfo (MusicResultsItem *info, const QString &album)
Detailed Description
The class of kugou query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musickgqueryrequest.h.
Constructor & Destructor Documentation
MusicKGQueryRequest::MusicKGQueryRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musickgqueryrequest.cpp.
References MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_KG_INTERFACE.
Member Function Documentation
void MusicKGQueryRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 61 of file musickgqueryrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_discNumber, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_queryQuality, MusicAbstractQueryRequest::m_querySimplify, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicPageQueryRequest::m_totalSize, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicKGQueryInterface::readFromMusicSongAttribute(), MusicKGQueryInterface::readFromMusicSongLrcAndPicture(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToPage().
void MusicKGQueryRequest::singleDownLoadFinished () slot
Download single data from net finished.
Definition at line 135 of file musickgqueryrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), KG_SONG_LRC_URL, MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicObject::MusicSongInformation::m_discNumber, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicObject::MusicSongInformation::m_lrcUrl, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractQueryRequest::m_queryQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicKGQueryInterface::readFromMusicSongAttribute(), TTK_LOGGER_INFO, TTK_NETWORK_QUERY_CHECK, and TTKObject_cast.
Referenced by startToSingleSearch().
void MusicKGQueryRequest::startToPage (int offset) final override virtual
Start to search data from name and type bt page.
Reimplemented from MusicPageQueryRequest.
Definition at line 21 of file musickgqueryrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KG_SONG_SEARCH_URL, MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageIndex, MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryText, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicKGQueryRequest::startToSearch (QueryType type, const QString & text) final override virtual
Start to search data from name and type.
Implements MusicAbstractQueryRequest.
Definition at line 10 of file musickgqueryrequest.cpp.
References MusicAbstractQueryRequest::downLoadFinished(), MusicAbstractQueryRequest::m_currentType, MusicAbstractQueryRequest::m_queryText, startToPage(), and TTK_LOGGER_INFO.
Referenced by MusicKGSongCommentsRequest::startToSearch().
void MusicKGQueryRequest::startToSingleSearch (const QString & text) final override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 42 of file musickgqueryrequest.cpp.
References MusicAbstractNetwork::deleteAll(), KG_SONG_INFO_URL, MusicAbstractNetwork::m_manager, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), singleDownLoadFinished(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryrequest.cpp