TTKMusicplayer: TTKThirdParty/Zlib/zlib/inffast.c File Reference
inffast.c File Reference
#include "zutil.h"
#include "inftrees.h"
#include "inflate.h"
#include "inffast.h"
Functions
void ZLIB_INTERNAL inflate_fast (z_streamp strm, unsigned start)
Function Documentation
void ZLIB_INTERNAL inflate_fast (z_streamp strm, unsigned start)
Definition at line 50 of file inffast.c.
References BAD, code::bits, inflate_state::bits, inflate_state::distbits, inflate_state::distcode, inflate_state::dmax, inflate_state::hold, inflate_state::last, inflate_state::lenbits, inflate_state::lencode, long(), inflate_state::mode, code::op, inflate_state::sane, Tracevv, TYPE, code::val, inflate_state::whave, inflate_state::window, inflate_state::wnext, inflate_state::wsize, and z_const.
Referenced by inflate(), and inflateBack().