TTKMusicplayer: MusicFileSenderServer Class Reference
MusicFileSenderServer Class Reference
The class of the file sender server.
#include <musicfilesenderserver.h>
Signals
void fileSendFinished ()
Public Member Functions
MusicFileSenderServer (QObject *parent=0)
~MusicFileSenderServer ()
void start ()
void setSendFile (const QString &file)
void setSendFiles (const QStringList &files)
void setReceiveAddress (const QString &ip)
QString getReceiveAddress () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
void sendData ()
Protected Attributes
bool m_nextFile
QUdpSocket * m_sendSocket
QFile * m_file
QStringList m_files
QString m_receiveIp
Private Slots
void readPendingDatagrams ()
Detailed Description
The class of the file sender server.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicfilesenderserver.h.
Constructor & Destructor Documentation
MusicFileSenderServer::MusicFileSenderServer (QObject * parent = 0) explicit
Object contsructor.
Definition at line 4 of file musicfilesenderserver.cpp.
References m_file, m_nextFile, m_sendSocket, readPendingDatagrams(), and SEND_PORT.
MusicFileSenderServer::~MusicFileSenderServer ()
Definition at line 16 of file musicfilesenderserver.cpp.
References m_file, and m_sendSocket.
Member Function Documentation
void MusicFileSenderServer::fileSendFinished () signal
Send file just has finished.
Referenced by sendData().
QString MusicFileSenderServer::getClassName () static
Get class object name.
Definition at line 22 of file musicfilesenderserver.cpp.
QString MusicFileSenderServer::getReceiveAddress () const
Get receive address.
Definition at line 42 of file musicfilesenderserver.cpp.
References m_receiveIp.
void MusicFileSenderServer::readPendingDatagrams () private slot
Read pending datagrams.
Definition at line 86 of file musicfilesenderserver.cpp.
References DATAGRAM, m_file, m_nextFile, m_sendSocket, sendData(), and start().
Referenced by MusicFileSenderServer().
void MusicFileSenderServer::sendData () protected
Send file data.
Definition at line 72 of file musicfilesenderserver.cpp.
References fileSendFinished(), m_file, m_nextFile, m_receiveIp, m_sendSocket, MAX_DATA, and RECEVIE_PORT.
Referenced by readPendingDatagrams().
void MusicFileSenderServer::setReceiveAddress (const QString & ip)
Set receive address.
Definition at line 37 of file musicfilesenderserver.cpp.
References m_receiveIp.
void MusicFileSenderServer::setSendFile (const QString & file)
Set send file.
Definition at line 27 of file musicfilesenderserver.cpp.
References m_files.
void MusicFileSenderServer::setSendFiles (const QStringList & files)
Set send file list.
Definition at line 32 of file musicfilesenderserver.cpp.
References m_files.
Referenced by MusicConnectTransferWidget::startToTransferWIFIFiles().
void MusicFileSenderServer::start ()
Start to transfer file.
Definition at line 47 of file musicfilesenderserver.cpp.
References m_file, m_files, m_receiveIp, m_sendSocket, RECEVIE_PORT, and STRING_SPLITER.
Referenced by readPendingDatagrams(), and MusicConnectTransferWidget::startToTransferWIFIFiles().
Member Data Documentation
QFile* MusicFileSenderServer::m_file protected
Definition at line 91 of file musicfilesenderserver.h.
Referenced by MusicFileSenderServer(), readPendingDatagrams(), sendData(), start(), and ~MusicFileSenderServer().
QStringList MusicFileSenderServer::m_files protected
Definition at line 92 of file musicfilesenderserver.h.
Referenced by setSendFile(), setSendFiles(), and start().
bool MusicFileSenderServer::m_nextFile protected
Definition at line 89 of file musicfilesenderserver.h.
Referenced by MusicFileSenderServer(), readPendingDatagrams(), and sendData().
QString MusicFileSenderServer::m_receiveIp protected
Definition at line 93 of file musicfilesenderserver.h.
Referenced by getReceiveAddress(), sendData(), setReceiveAddress(), and start().
QUdpSocket* MusicFileSenderServer::m_sendSocket protected
Definition at line 90 of file musicfilesenderserver.h.
Referenced by MusicFileSenderServer(), readPendingDatagrams(), sendData(), start(), and ~MusicFileSenderServer().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsKits/musicfilesenderserver.h
TTKModule/TTKCore/musicToolsKits/musicfilesenderserver.cpp