TTKMusicplayer: QRandom Namespace Reference
QRandom Namespace Reference
The class of the random wrapper.
Functions
TTK_MODULE_EXPORT void initRandom ()
TTK_MODULE_EXPORT int random (int value)
Detailed Description
The class of the random wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void QRandom::initRandom ()
Init random value seed.
Definition at line 7 of file random.cpp.
Referenced by QImageWrapper::CubeWavePrivate::CubeWavePrivate(), and MusicTime::initRandom().
int QRandom::random (int value)
Get random value.
Definition at line 14 of file random.cpp.
Referenced by QImageWrapper::CubeWave::input(), MusicTime::random(), and MusicDesktopWallpaperThread::setRandom().