TTKMusicPlayer: MusicDownloadThunderSkinRequest Class Reference
MusicDownloadThunderSkinRequest Class Reference
The class of the download thunder skin background.
#include <musicdownloadthunderskinrequest.h>
Public Slots
virtual void downLoadFinished (const QByteArray &bytes) overridefinal
Public Slots inherited from MusicAbstractDownloadSkinRequest
virtual void downLoadFinished (const QByteArray &bytes)=0
Public Member Functions
MusicDownloadThunderSkinRequest (QObject *parent=nullptr)
virtual void startRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownloadSkinRequest
MusicAbstractDownloadSkinRequest (QObject *parent=nullptr)
virtual void startRequest (const QString &id)
Additional Inherited Members
Signals inherited from MusicAbstractDownloadSkinRequest
void downLoadDataChanged (const MusicSkinRemoteGroupList &bytes)
Detailed Description
The class of the download thunder skin background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 48 of file musicdownloadthunderskinrequest.h.
Constructor & Destructor Documentation
MusicDownloadThunderSkinRequest::MusicDownloadThunderSkinRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 67 of file musicdownloadthunderskinrequest.cpp.
Member Function Documentation
void MusicDownloadThunderSkinRequest::downLoadFinished (const QByteArray & bytes) final override virtual slot
Download data from net finished.
Definition at line 80 of file musicdownloadthunderskinrequest.cpp.
References MusicAbstractDownloadSkinRequest::downLoadDataChanged(), TTKAbstractXml::fromByteArray(), and MusicThunderSkinConfigManager::readBuffer().
Referenced by startRequest().
void MusicDownloadThunderSkinRequest::startRequest () final override virtual
Start to download data from net.
Reimplemented from MusicAbstractDownloadSkinRequest.
Definition at line 73 of file musicdownloadthunderskinrequest.cpp.
References downLoadFinished(), MusicUtils::Algorithm::mdII(), QUERY_URL, and MusicDownloadSourceRequest::startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadthunderskinrequest.h
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadthunderskinrequest.cpp