TTKMusicplayer: MusicTTKFMRadioInformationWidget Class Reference
MusicTTKFMRadioInformationWidget Class Reference
The class of the web music radio information widget.
#include <musicttkfmradioplaywidget.h>
Public Slots
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicTTKFMRadioInformationWidget (QWidget *parent=nullptr)
~MusicTTKFMRadioInformationWidget ()
void setReadOnly (bool mode)
void setChannelInformation (const MusicFMChannel &channel)
MusicFMChannel channelInformation () const
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicTTKFMRadioInformationWidget * m_ui
bool m_readOnly
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the web music radio information widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 85 of file musicttkfmradioplaywidget.h.
Constructor & Destructor Documentation
MusicTTKFMRadioInformationWidget::MusicTTKFMRadioInformationWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 65 of file musicttkfmradioplaywidget.cpp.
References m_ui, MusicUIObject::MQSSPushButtonStyle04, and MusicUIObject::MQSSToolButtonStyle04.
MusicTTKFMRadioInformationWidget::~MusicTTKFMRadioInformationWidget ()
Definition at line 86 of file musicttkfmradioplaywidget.cpp.
References m_ui.
Member Function Documentation
MusicFMChannel MusicTTKFMRadioInformationWidget::channelInformation () const
Get channel information.
Definition at line 98 of file musicttkfmradioplaywidget.cpp.
References m_ui.
Referenced by MusicTTKFMRadioPlayWidget::addButtonClicked().
int MusicTTKFMRadioInformationWidget::exec () virtual slot
Override exec function.
Definition at line 111 of file musicttkfmradioplaywidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicTTKFMRadioPlayWidget::addButtonClicked(), and MusicTTKFMRadioPlayWidget::infoButtonClicked().
void MusicTTKFMRadioInformationWidget::setChannelInformation (const MusicFMChannel & channel)
Set channel information.
Definition at line 91 of file musicttkfmradioplaywidget.cpp.
References MusicFMChannel::m_location, MusicFMChannel::m_name, m_ui, and MusicFMChannel::m_url.
Referenced by MusicTTKFMRadioPlayWidget::infoButtonClicked().
void MusicTTKFMRadioInformationWidget::setReadOnly (bool mode)
Set read only mode.
Definition at line 103 of file musicttkfmradioplaywidget.cpp.
References m_readOnly, and m_ui.
Referenced by MusicTTKFMRadioPlayWidget::addButtonClicked().
Member Data Documentation
bool MusicTTKFMRadioInformationWidget::m_readOnly protected
Definition at line 117 of file musicttkfmradioplaywidget.h.
Referenced by setReadOnly().
Ui::MusicTTKFMRadioInformationWidget* MusicTTKFMRadioInformationWidget::m_ui protected
Definition at line 116 of file musicttkfmradioplaywidget.h.
Referenced by channelInformation(), exec(), MusicTTKFMRadioInformationWidget(), setChannelInformation(), setReadOnly(), and ~MusicTTKFMRadioInformationWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicttkfmradioplaywidget.h
TTKModule/TTKWidget/musicToolsKits/musicttkfmradioplaywidget.cpp