TTKMusicplayer: MusicCryptographicHash Class Reference
MusicCryptographicHash Class Reference
The class of the string cryptographic hash.
#include <musiccryptographichash.h>
Public Member Functions
MusicCryptographicHash ()
QString encrypt (const QString &data, const QString &key)
QString decrypt (const QString &data, const QString &key)
Protected Member Functions
std::string xxteaEncrypt (std::string data, std::string key)
QString xxteaEncrypt (const QString &data, const QString &key)
std::string xxteaDecrypt (std::string data, std::string key)
QString xxteaDecrypt (const QString &data, const QString &key)
bool isBase64 (unsigned char c)
unsigned char * doXxteaEncrypt (unsigned char *data, xxtea_uint len, unsigned char *key, xxtea_uint *ret_len)
unsigned char * doXxteaDecrypt (unsigned char *data, xxtea_uint len, unsigned char *key, xxtea_uint *ret_len)
void xxteaUintEncrypt (xxtea_uint *v, xxtea_uint len, xxtea_uint *k)
void xxteaUintDecrypt (xxtea_uint *v, xxtea_uint len, xxtea_uint *k)
unsigned char * fixKeyLength (unsigned char *key, xxtea_uint key_len)
xxtea_uint * xxteaToUintArray (unsigned char *data, xxtea_uint len, int include_length, xxtea_uint *ret_len)
unsigned char * xxteaToByteArray (xxtea_uint *data, xxtea_uint len, int include_length, xxtea_uint *ret_len)
std::string base64Encode (unsigned char const *, unsigned int len)
std::string base64Decode (std::string const &s)
unsigned char * xxteaEncrypt (unsigned char *data, xxtea_uint data_len, unsigned char *key, xxtea_uint key_len, xxtea_uint *ret_length)
unsigned char * xxteaDecrypt (unsigned char *data, xxtea_uint data_len, unsigned char *key, xxtea_uint key_len, xxtea_uint *ret_length)
Detailed Description
The class of the string cryptographic hash.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 44 of file musiccryptographichash.h.
Constructor & Destructor Documentation
MusicCryptographicHash::MusicCryptographicHash ()
Object contsructor.
Definition at line 8 of file musiccryptographichash.cpp.
Member Function Documentation
std::string MusicCryptographicHash::base64Decode (std::string const & s) protected
Base64 dncode.
Definition at line 126 of file musiccryptographichash.cpp.
References base64_chars, and isBase64().
Referenced by xxteaDecrypt().
std::string MusicCryptographicHash::base64Encode (unsigned char const * bytes_to_encode, unsigned int len) protected
Base64 encode.
Definition at line 76 of file musiccryptographichash.cpp.
References base64_chars.
Referenced by xxteaEncrypt().
QString MusicCryptographicHash::decrypt (const QString & data, const QString & key)
decrypt by QString data.
Definition at line 18 of file musiccryptographichash.cpp.
References xxteaDecrypt().
Referenced by MusicUtils::Algorithm::mdII().
unsigned char * MusicCryptographicHash::doXxteaDecrypt (unsigned char * data, xxtea_uint len, unsigned char * key, xxtea_uint * ret_len) protected
Do XXTEA decrypt.
Definition at line 296 of file musiccryptographichash.cpp.
References xxteaToByteArray(), xxteaToUintArray(), and xxteaUintDecrypt().
Referenced by xxteaDecrypt().
unsigned char * MusicCryptographicHash::doXxteaEncrypt (unsigned char * data, xxtea_uint len, unsigned char * key, xxtea_uint * ret_len) protected
Do XXTEA encrypt.
Definition at line 281 of file musiccryptographichash.cpp.
References xxteaToByteArray(), xxteaToUintArray(), and xxteaUintEncrypt().
Referenced by xxteaEncrypt().
QString MusicCryptographicHash::encrypt (const QString & data, const QString & key)
encrypt by QString data.
Definition at line 13 of file musiccryptographichash.cpp.
References xxteaEncrypt().
Referenced by MusicUtils::Algorithm::mdII(), xxteaDecrypt(), and xxteaEncrypt().
unsigned char * MusicCryptographicHash::fixKeyLength (unsigned char * key, xxtea_uint key_len) protected
Fix key length.
Definition at line 222 of file musiccryptographichash.cpp.
Referenced by xxteaDecrypt(), and xxteaEncrypt().
bool MusicCryptographicHash::isBase64 (unsigned char c) protected
Check current char is base64.
Definition at line 71 of file musiccryptographichash.cpp.
References isalnum.
Referenced by base64Decode().
std::string MusicCryptographicHash::xxteaDecrypt (std::string data, std::string key) protected
XXTEA decrypt by std::string data.
Definition at line 37 of file musiccryptographichash.cpp.
References base64Decode(), and encrypt().
Referenced by decrypt(), and xxteaDecrypt().
QString MusicCryptographicHash::xxteaDecrypt (const QString & data, const QString & key) protected
XXTEA decrypt by QString data.
Definition at line 66 of file musiccryptographichash.cpp.
References xxteaDecrypt().
unsigned char * MusicCryptographicHash::xxteaDecrypt (unsigned char * data, xxtea_uint data_len, unsigned char * key, xxtea_uint key_len, xxtea_uint * ret_length) protected
XXTEA decrypt by unsigned char * data.
Definition at line 331 of file musiccryptographichash.cpp.
References doXxteaDecrypt(), and fixKeyLength().
std::string MusicCryptographicHash::xxteaEncrypt (std::string data, std::string key) protected
XXTEA encrypt by std::string data.
Definition at line 23 of file musiccryptographichash.cpp.
References base64Encode(), encrypt(), and MusicUtils::Codec::toUtf8().
Referenced by encrypt(), and xxteaEncrypt().
QString MusicCryptographicHash::xxteaEncrypt (const QString & data, const QString & key) protected
XXTEA encrypt by QString data.
Definition at line 61 of file musiccryptographichash.cpp.
References xxteaEncrypt().
unsigned char * MusicCryptographicHash::xxteaEncrypt (unsigned char * data, xxtea_uint data_len, unsigned char * key, xxtea_uint key_len, xxtea_uint * ret_length) protected
XXTEA encrypt by unsigned char * data.
Definition at line 311 of file musiccryptographichash.cpp.
References doXxteaEncrypt(), and fixKeyLength().
unsigned char * MusicCryptographicHash::xxteaToByteArray (xxtea_uint * data, xxtea_uint len, int include_length, xxtea_uint * ret_len) protected
XXTEA to byte array.
Definition at line 255 of file musiccryptographichash.cpp.
Referenced by doXxteaDecrypt(), and doXxteaEncrypt().
xxtea_uint * MusicCryptographicHash::xxteaToUintArray (unsigned char * data, xxtea_uint len, int include_length, xxtea_uint * ret_len) protected
XXTEA to uint array.
Definition at line 230 of file musiccryptographichash.cpp.
Referenced by doXxteaDecrypt(), and doXxteaEncrypt().
void MusicCryptographicHash::xxteaUintDecrypt (xxtea_uint * v, xxtea_uint len, xxtea_uint * k) protected
XXTEA uint decrypt.
Definition at line 201 of file musiccryptographichash.cpp.
References XXTEA_DELTA, and XXTEA_MX.
Referenced by doXxteaDecrypt().
void MusicCryptographicHash::xxteaUintEncrypt (xxtea_uint * v, xxtea_uint len, xxtea_uint * k) protected
XXTEA uint encrypt.
Definition at line 180 of file musiccryptographichash.cpp.
References XXTEA_DELTA, and XXTEA_MX.
Referenced by doXxteaEncrypt().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musiccryptographichash.h
TTKModule/TTKCore/musicCoreKits/musiccryptographichash.cpp