TTKMusicplayer: MusicDownloadBackgroundRemoteRequest Class Reference
MusicDownloadBackgroundRemoteRequest Class Reference abstract
The class of download skin remote background.
#include <musicdownloadbackgroundskinrequest.h>
Public Slots
virtual void downLoadFinished (const QByteArray &bytes)=0
Signals
void downLoadDataChanged (const MusicSkinRemoteGroups &bytes)
Public Member Functions
MusicDownloadBackgroundRemoteRequest (QObject *parent=nullptr)
virtual void startToDownload ()=0
Detailed Description
The class of download skin remote background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 88 of file musicdownloadbackgroundskinrequest.h.
Constructor & Destructor Documentation
MusicDownloadBackgroundRemoteRequest::MusicDownloadBackgroundRemoteRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 62 of file musicdownloadbackgroundskinrequest.cpp.
Member Function Documentation
void MusicDownloadBackgroundRemoteRequest::downLoadDataChanged (const MusicSkinRemoteGroups & bytes) signal
Send download data from net.
Referenced by MusicDownloadBackgroundThunderRequest::downLoadFinished(), and MusicDownloadBackgroundBingRequest::downLoadFinished().
virtual void MusicDownloadBackgroundRemoteRequest::downLoadFinished (const QByteArray & bytes) pure virtual slot
Download data from net finished.
virtual void MusicDownloadBackgroundRemoteRequest::startToDownload () pure virtual
Start to download data from net.
Implemented in MusicDownloadBackgroundBingRequest, and MusicDownloadBackgroundThunderRequest.
Referenced by MusicBackgroundThunderWidget::initialize(), and MusicBackgroundDailyWidget::initialize().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadbackgroundskinrequest.h
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadbackgroundskinrequest.cpp