TTKMusicplayer: MusicConnectTransferWidget Class Reference
MusicConnectTransferWidget Class Reference
The class of the transfer file to mobile widget.
#include <musicconnecttransferwidget.h>
Public Slots
void currentPlayListSelected (int index)
void selectedAllItems (bool check)
void startToTransferUSBFiles ()
void startToTransferWIFIFiles ()
void reflashRemovableDir ()
void switchDiffDevice ()
void musicSearchIndexChanged (int row, int col)
void initColumns ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void getMusicLists (MusicSongItems &songs)
Public Member Functions
MusicConnectTransferWidget (QWidget *parent=0)
virtual ~MusicConnectTransferWidget ()
void openTransferFiles (int mode)
void redirectToCurrentSong (int toolIndex, int songIndex)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void createAllItems (const MusicSongs &songs)
QStringList getSelectedFiles ()
QString getRemovableDrive ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicConnectTransferWidget * m_ui
int m_currentIndex
MusicSongs m_currentSongs
QButtonGroup * m_buttonGroup
MusicObject::MIntsListMap m_searchfileListCache
MusicFileSenderServer * m_sendServer
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the transfer file to mobile widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicconnecttransferwidget.h.
Constructor & Destructor Documentation
MusicConnectTransferWidget::MusicConnectTransferWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 18 of file musicconnecttransferwidget.cpp.
References initColumns(), m_buttonGroup, M_CONNECTION_PTR, m_currentIndex, m_sendServer, m_ui, MusicUIObject::MCheckBoxStyle03, MusicUIObject::MLineEditStyle01, MusicUIObject::MLineEditStyle05, MusicUIObject::MPushButtonStyle04, MusicUIObject::MScrollBarStyle01, MT_MS, MusicUIObject::MToolButtonStyle04, musicSearchIndexChanged(), reflashRemovableDir(), selectedAllItems(), startToTransferUSBFiles(), startToTransferWIFIFiles(), and switchDiffDevice().
MusicConnectTransferWidget::~MusicConnectTransferWidget () virtual
Definition at line 75 of file musicconnecttransferwidget.cpp.
References m_buttonGroup, M_CONNECTION_PTR, m_sendServer, and m_ui.
Member Function Documentation
void MusicConnectTransferWidget::createAllItems (const MusicSongs & songs) protected
Create all items.
Definition at line 127 of file musicconnecttransferwidget.cpp.
References m_ui.
Referenced by currentPlayListSelected(), and musicSearchIndexChanged().
void MusicConnectTransferWidget::currentPlayListSelected (int index) slot
Current playList selected.
Definition at line 184 of file musicconnecttransferwidget.cpp.
References createAllItems(), getMusicLists(), m_currentIndex, m_currentSongs, m_searchfileListCache, and m_ui.
Referenced by initColumns(), and redirectToCurrentSong().
int MusicConnectTransferWidget::exec () virtual slot
Override exec function.
Definition at line 309 of file musicconnecttransferwidget.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicToolSetsWidget::itemHasClicked(), MusicSongsListAbstractTableWidget::musicSongTransferWidget(), MusicConnectMobileWidget::openTransferFiles2Mobile(), and MusicConnectMobileWidget::openTransferFiles2Wifi().
void MusicConnectTransferWidget::getMusicLists (MusicSongItems & songs) signal
Get music datas from container.
Referenced by currentPlayListSelected(), and initColumns().
QString MusicConnectTransferWidget::getRemovableDrive () protected
Get removable drive name.
Definition at line 168 of file musicconnecttransferwidget.cpp.
Referenced by reflashRemovableDir(), and startToTransferUSBFiles().
QStringList MusicConnectTransferWidget::getSelectedFiles () protected
Get selected files.
Definition at line 138 of file musicconnecttransferwidget.cpp.
References MusicMessageBox::exec(), m_currentIndex, m_currentSongs, m_searchfileListCache, m_ui, and MusicMessageBox::setText().
Referenced by startToTransferUSBFiles(), and startToTransferWIFIFiles().
void MusicConnectTransferWidget::initColumns () slot
Create the left button column
Definition at line 102 of file musicconnecttransferwidget.cpp.
References currentPlayListSelected(), getMusicLists(), m_buttonGroup, m_ui, MusicUIObject::MBackgroundStyle01, MusicUIObject::MPushButtonStyle04, and reflashRemovableDir().
Referenced by MusicConnectTransferWidget().
void MusicConnectTransferWidget::musicSearchIndexChanged (int row, int col) slot
Search file from list.
Definition at line 289 of file musicconnecttransferwidget.cpp.
References createAllItems(), m_currentSongs, m_searchfileListCache, and m_ui.
Referenced by MusicConnectTransferWidget().
void MusicConnectTransferWidget::openTransferFiles (int mode)
Open transfer files by mode.
Definition at line 83 of file musicconnecttransferwidget.cpp.
References switchDiffDevice().
Referenced by MusicConnectMobileWidget::openTransferFiles2Mobile(), and MusicConnectMobileWidget::openTransferFiles2Wifi().
void MusicConnectTransferWidget::redirectToCurrentSong (int toolIndex, int songIndex)
Redirect to current song.
Definition at line 91 of file musicconnecttransferwidget.cpp.
References currentPlayListSelected(), and m_ui.
Referenced by MusicSongsListAbstractTableWidget::musicSongTransferWidget().
void MusicConnectTransferWidget::reflashRemovableDir () slot
Reflash removable dir.
Definition at line 271 of file musicconnecttransferwidget.cpp.
References MusicSettingManager::ExtraDevicePathChoiced, getRemovableDrive(), M_SETTING_PTR, and m_ui.
Referenced by initColumns(), and MusicConnectTransferWidget().
void MusicConnectTransferWidget::selectedAllItems (bool check) slot
Select all items.
Definition at line 199 of file musicconnecttransferwidget.cpp.
References m_ui.
Referenced by MusicConnectTransferWidget().
void MusicConnectTransferWidget::startToTransferUSBFiles () slot
Start to transfer usb files.
Definition at line 205 of file musicconnecttransferwidget.cpp.
References MusicSettingManager::ExtraDevicePathChoiced, getRemovableDrive(), getSelectedFiles(), M_SETTING_PTR, m_ui, MusicProgressWidget::setTitle(), and MusicProgressWidget::show().
Referenced by MusicConnectTransferWidget().
void MusicConnectTransferWidget::startToTransferWIFIFiles () slot
Start to transfer wifi files.
Definition at line 237 of file musicconnecttransferwidget.cpp.
References MusicMessageBox::exec(), getSelectedFiles(), m_sendServer, m_ui, MusicFileSenderServer::setSendFiles(), MusicMessageBox::setText(), and MusicFileSenderServer::start().
Referenced by MusicConnectTransferWidget().
void MusicConnectTransferWidget::switchDiffDevice () slot
Switch to different device.
Definition at line 282 of file musicconnecttransferwidget.cpp.
References m_ui.
Referenced by MusicConnectTransferWidget(), and openTransferFiles().
Member Data Documentation
QButtonGroup* MusicConnectTransferWidget::m_buttonGroup protected
Definition at line 117 of file musicconnecttransferwidget.h.
Referenced by initColumns(), MusicConnectTransferWidget(), and ~MusicConnectTransferWidget().
int MusicConnectTransferWidget::m_currentIndex protected
Definition at line 115 of file musicconnecttransferwidget.h.
Referenced by currentPlayListSelected(), getSelectedFiles(), and MusicConnectTransferWidget().
MusicSongs MusicConnectTransferWidget::m_currentSongs protected
Definition at line 116 of file musicconnecttransferwidget.h.
Referenced by currentPlayListSelected(), getSelectedFiles(), and musicSearchIndexChanged().
MusicObject::MIntsListMap MusicConnectTransferWidget::m_searchfileListCache protected
Definition at line 118 of file musicconnecttransferwidget.h.
Referenced by currentPlayListSelected(), getSelectedFiles(), and musicSearchIndexChanged().
MusicFileSenderServer* MusicConnectTransferWidget::m_sendServer protected
Definition at line 119 of file musicconnecttransferwidget.h.
Referenced by MusicConnectTransferWidget(), startToTransferWIFIFiles(), and ~MusicConnectTransferWidget().
Ui::MusicConnectTransferWidget* MusicConnectTransferWidget::m_ui protected
Definition at line 114 of file musicconnecttransferwidget.h.
Referenced by createAllItems(), currentPlayListSelected(), exec(), getSelectedFiles(), initColumns(), MusicConnectTransferWidget(), musicSearchIndexChanged(), redirectToCurrentSong(), reflashRemovableDir(), selectedAllItems(), startToTransferUSBFiles(), startToTransferWIFIFiles(), switchDiffDevice(), and ~MusicConnectTransferWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicconnecttransferwidget.h
TTKModule/TTKWidget/musicToolsKits/musicconnecttransferwidget.cpp