TTKMusicplayer: QmmpSettings Class Reference
QmmpSettings Class Reference
The QmmpSettings class provides access to global settings.
#include <qmmpsettings.h>
Public Types
enum ReplayGainMode { REPLAYGAIN_TRACK = 0, REPLAYGAIN_ALBUM, REPLAYGAIN_DISABLED }
enum ProxyType { HTTP_PROXY = 0, SOCKS5_PROXY }
Signals
void replayGainSettingsChanged ()
void audioSettingsChanged ()
void coverSettingsChanged ()
void networkSettingsChanged ()
void eqSettingsChanged ()
Public Member Functions
QmmpSettings (QObject *parent=nullptr)
virtual ~QmmpSettings ()
QmmpSettings::ReplayGainMode replayGainMode () const
double replayGainPreamp () const
double replayGainDefaultGain () const
bool replayGainPreventClipping () const
void setReplayGainSettings (ReplayGainMode mode, double preamp, double default_gain, bool clip)
bool useSoftVolume () const
Qmmp::AudioFormat outputFormat () const
bool useDithering () const
void setAudioSettings (bool soft_volume, Qmmp::AudioFormat format, bool use_dithering)
const QStringList & coverNameFilters (bool include=true) const
int coverSearchDepth () const
bool useCoverFiles () const
void setCoverSettings (QStringList inc, QStringList exc, int depth, bool use_files)
bool isProxyEnabled () const
bool useProxyAuth () const
const QUrl & proxy () const
ProxyType proxyType () const
void setNetworkSettings (bool use_proxy, bool auth, ProxyType type, const QUrl &proxy)
const EqSettings & eqSettings () const
void setEqSettings (const EqSettings &settings)
void readEqSettings (EqSettings::Bands bands=EqSettings::EQ_BANDS_10)
int bufferSize () const
void setBufferSize (int msec)
void setVolumeStep (int step)
int volumeStep () const
void setAverageBitrate (bool enabled)
bool averageBitrate () const
void setDetermineFileTypeByContent (bool enabled)
bool determineFileTypeByContent () const
Static Public Member Functions
static QmmpSettings * instance ()
Private Slots
void sync ()
Private Attributes
QmmpSettings::ReplayGainMode m_rg_mode
double m_rg_preamp
double m_rg_defaut_gain
bool m_rg_prevent_clipping
bool m_aud_software_volume
bool m_aud_dithering
Qmmp::AudioFormat m_aud_format
int m_volume_step
bool m_average_bitrate
QStringList m_cover_inc
QStringList m_cover_exclude
int m_cover_depth
bool m_cover_use_files
bool m_proxy_enabled
bool m_proxy_auth
QUrl m_proxy_url
ProxyType m_proxy_type
EqSettings m_eq_settings
int m_buffer_size
bool m_determine_by_content
QTimer * m_timer
Static Private Attributes
static QmmpSettings * m_instance
Detailed Description
The QmmpSettings class provides access to global settings.
Author
Ilya Kotov forko.nosp@m.tov0.nosp@m.2@ya..nosp@m.ru
Definition at line 35 of file qmmpsettings.h.
Member Enumeration Documentation
enum QmmpSettings::ProxyType
This enum describes proxy types.
Enumerator
HTTP_PROXY
HTTP proxy
SOCKS5_PROXY
SOCKS5 proxy
Definition at line 52 of file qmmpsettings.h.
enum QmmpSettings::ReplayGainMode
This enum describes possible replaygain modes.
Enumerator
REPLAYGAIN_TRACK
Use track gain/peak
REPLAYGAIN_ALBUM
Use album gain/peak
REPLAYGAIN_DISABLED
Disable ReplayGain
Definition at line 42 of file qmmpsettings.h.
Constructor & Destructor Documentation
QmmpSettings::QmmpSettings (QObject * parent = nullptr) explicit
Constructor.
Parameters
parent Parent object. This functions is for internal usage only, use QmmpSettings::instance() instead.
virtual QmmpSettings::~QmmpSettings () virtual
Destructor.
Member Function Documentation
void QmmpSettings::audioSettingsChanged () signal
Emitted when audio settings are changed.
bool QmmpSettings::averageBitrate () const
Returns true if average bitrate displaying is enabled, otherwise returns false
int QmmpSettings::bufferSize () const
Returns buffer size in milliseconds.
Referenced by MusicSettingWidget::initControllerParameter().
const QStringList& QmmpSettings::coverNameFilters (bool include = true) const
If include is true, this function returns include cover file name filters, otherwise returns exclude filters.
int QmmpSettings::coverSearchDepth () const
Returns a depth of recursive cover file search.
void QmmpSettings::coverSettingsChanged () signal
Emitted when cover settings are changed.
bool QmmpSettings::determineFileTypeByContent () const
Return true if content based file type determination is enabled. Otherwise returns false.
const EqSettings& QmmpSettings::eqSettings () const
Returns equalizer settings.
void QmmpSettings::eqSettingsChanged () signal
Emitted when equalizer settings are changed.
static QmmpSettings* QmmpSettings::instance () static
Returns a pointer to the QmmpSettings instance.
Referenced by MusicSettingWidget::initControllerParameter(), and MusicSettingWidget::saveParameterSettings().
bool QmmpSettings::isProxyEnabled () const
Returns true if global proxy is enabled, otherwise returns false
void QmmpSettings::networkSettingsChanged () signal
Emitted when network settings are changed.
Qmmp::AudioFormat QmmpSettings::outputFormat () const
Returns preferd output format.
Referenced by MusicSettingWidget::initControllerParameter().
const QUrl& QmmpSettings::proxy () const
Returns global proxy url.
ProxyType QmmpSettings::proxyType () const
Returls global proxy type.
void QmmpSettings::readEqSettings (EqSettings::Bands bands = EqSettings::EQ_BANDS_10)
Reads equalizer settings. Call this function before equalizer usage.
Parameters
bands Number of bands.
double QmmpSettings::replayGainDefaultGain () const
Returns default gain in dB.
Referenced by MusicSettingWidget::initControllerParameter().
QmmpSettings::ReplayGainMode QmmpSettings::replayGainMode () const
Returns current ReplayGain mode.
Referenced by MusicSettingWidget::initControllerParameter().
double QmmpSettings::replayGainPreamp () const
Returns preamp in dB.
Referenced by MusicSettingWidget::initControllerParameter().
bool QmmpSettings::replayGainPreventClipping () const
Returns true if clipping prevention is enabled; otherwise returns false.
Referenced by MusicSettingWidget::initControllerParameter().
void QmmpSettings::replayGainSettingsChanged () signal
Emitted when ReplayGain settings are changed.
void QmmpSettings::setAudioSettings (bool soft_volume, Qmmp::AudioFormat format, bool use_dithering)
Sets audio settings.
Parameters
soft_volume State of software volume.
format Preferd output format. Supported values: Qmmp::PCM_S16LE, Qmmp::PCM_S24LE, Qmmp::PCM_S32LE.
use_dithering Enable/Disable audio dithering.
Referenced by MusicSettingWidget::saveParameterSettings().
void QmmpSettings::setAverageBitrate (bool enabled)
Enables/Disables average bitrate displaying.
Parameters
enabled State of the average bitrate displaying (true - enabled, false - disabled). This function emits audioSettingsChanged() signal.
void QmmpSettings::setBufferSize (int msec)
Sets buffer size.
Parameters
msec Buffer size in milliseconds.
Referenced by MusicSettingWidget::saveParameterSettings().
void QmmpSettings::setCoverSettings (QStringList inc, QStringList exc, int depth, bool use_files)
Sets cover search options.
Parameters
inc Include cover name filters
exc Exclude cover name filters
depth Depth of recursive cover file search. Recursive cover file search can be disabled by setting depth to 0.
use_files Use or not use files with covers. This parameter doesn't take effect in embedded covers.
void QmmpSettings::setDetermineFileTypeByContent (bool enabled)
Enables/Disables file type determination by content.
Parameters
enabled State of the content based type determination. (true - enabled, false - disabled).
void QmmpSettings::setEqSettings (const EqSettings & settings)
Changes equalizer settings to settings.
void QmmpSettings::setNetworkSettings (bool use_proxy, bool auth, ProxyType type, const QUrl & proxy)
Sets network settings.
Parameters
use_proxy Enables or disables global proxy.
auth Enables or disables proxy authentication.
type Proxy type.
proxy Proxy url.
void QmmpSettings::setReplayGainSettings (ReplayGainMode mode, double preamp, double default_gain, bool clip)
Sets ReplayGains settings.
Parameters
mode ReplayGain mode.
preamp Preamp in dB.
default_gain Default gain in dB.
clip Clipping prevention state.
Referenced by MusicSettingWidget::saveParameterSettings().
void QmmpSettings::setVolumeStep (int step)
Sets volume adjustment step.
Parameters
step Volume adjustment step in percent.
Referenced by MusicSettingWidget::saveParameterSettings().
void QmmpSettings::sync () private slot
Writes all unsaved settings to configuration file
bool QmmpSettings::useCoverFiles () const
Returns true if cover file search is enabled; otherwise returns false.
bool QmmpSettings::useDithering () const
Returns true if dithering is enabled; otherwise returns false.
Referenced by MusicSettingWidget::initControllerParameter().
bool QmmpSettings::useProxyAuth () const
Returns true if global proxy authentication is enabled, otherwise returns false
bool QmmpSettings::useSoftVolume () const
Returns true if software volume is enabled; otherwise returns false.
Referenced by MusicSettingWidget::initControllerParameter().
int QmmpSettings::volumeStep () const
Returns volume adjustment step.
Referenced by MusicSettingWidget::initControllerParameter().
Member Data Documentation
bool QmmpSettings::m_aud_dithering private
Definition at line 250 of file qmmpsettings.h.
Qmmp::AudioFormat QmmpSettings::m_aud_format private
Definition at line 251 of file qmmpsettings.h.
bool QmmpSettings::m_aud_software_volume private
Definition at line 249 of file qmmpsettings.h.
bool QmmpSettings::m_average_bitrate private
Definition at line 253 of file qmmpsettings.h.
int QmmpSettings::m_buffer_size private
Definition at line 267 of file qmmpsettings.h.
int QmmpSettings::m_cover_depth private
Definition at line 257 of file qmmpsettings.h.
QStringList QmmpSettings::m_cover_exclude private
Definition at line 256 of file qmmpsettings.h.
QStringList QmmpSettings::m_cover_inc private
Definition at line 255 of file qmmpsettings.h.
bool QmmpSettings::m_cover_use_files private
Definition at line 258 of file qmmpsettings.h.
bool QmmpSettings::m_determine_by_content private
Definition at line 269 of file qmmpsettings.h.
EqSettings QmmpSettings::m_eq_settings private
Definition at line 265 of file qmmpsettings.h.
QmmpSettings* QmmpSettings::m_instance static private
Definition at line 273 of file qmmpsettings.h.
bool QmmpSettings::m_proxy_auth private
Definition at line 261 of file qmmpsettings.h.
bool QmmpSettings::m_proxy_enabled private
Definition at line 260 of file qmmpsettings.h.
ProxyType QmmpSettings::m_proxy_type private
Definition at line 263 of file qmmpsettings.h.
QUrl QmmpSettings::m_proxy_url private
Definition at line 262 of file qmmpsettings.h.
double QmmpSettings::m_rg_defaut_gain private
Definition at line 246 of file qmmpsettings.h.
QmmpSettings::ReplayGainMode QmmpSettings::m_rg_mode private
Definition at line 244 of file qmmpsettings.h.
double QmmpSettings::m_rg_preamp private
Definition at line 245 of file qmmpsettings.h.
bool QmmpSettings::m_rg_prevent_clipping private
Definition at line 247 of file qmmpsettings.h.
QTimer* QmmpSettings::m_timer private
Definition at line 271 of file qmmpsettings.h.
int QmmpSettings::m_volume_step private
Definition at line 252 of file qmmpsettings.h.
The documentation for this class was generated from the following file:
TTKExtra/qmmp/qmmpsettings.h