TTKMusicPlayer: MusicQualityWidget Class Reference
MusicQualityWidget Class Reference
The class of the quality widget.
#include <musicqualitywidget.h>
Public Member Functions
MusicQualityWidget (QWidget *parent=nullptr)
void updateQuality ()
Detailed Description
The class of the quality widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicqualitywidget.h.
Constructor & Destructor Documentation
MusicQualityWidget::MusicQualityWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicqualitywidget.cpp.
References TTK::UI::LabelQuality.
Member Function Documentation
void MusicQualityWidget::updateQuality ()
Update quality by song bitrate.
Definition at line 15 of file musicqualitywidget.cpp.
References Qmmp::BITRATE, TTK::Number::bitrateToLevel(), TTK::High, SoundCore::instance(), TTK::Lossless, TrackInfo::properties(), TTK::Standard, TTK::Super, and SoundCore::trackInfo().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicqualitywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicqualitywidget.cpp