TTKMusicplayer: MusicAbstractXml Class Reference
MusicAbstractXml Class Reference
The class of the base class of xml interface.
#include <musicabstractxml.h>
Public Member Functions
MusicAbstractXml (QObject *parent=0)
~MusicAbstractXml ()
bool readConfig (const QString &name)
bool writeConfig (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagNameValue (const QString &tagName) const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName) const
QString readXmlTextByTagName (const QString &tagName) const
MusicObject::MStriantMap readXmlAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const MusicXmlAttribute &attr)
QDomElement createRoot (const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDom (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const MusicXmlAttribute &attr)
QDomElement writeDomElementMutil (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const MusicXmlAttribute &attr, const QString &text)
QDomElement writeDomElementMutilText (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const MusicXmlAttribute &attr)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
QFile * m_file
QDomDocument * m_ddom
Detailed Description
The class of the base class of xml interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 49 of file musicabstractxml.h.
Constructor & Destructor Documentation
MusicAbstractXml::MusicAbstractXml (QObject * parent = 0) explicit
Object contsructor.
Definition at line 7 of file musicabstractxml.cpp.
References m_ddom, and m_file.
MusicAbstractXml::~MusicAbstractXml ()
Definition at line 14 of file musicabstractxml.cpp.
References m_ddom, and m_file.
Member Function Documentation
void MusicAbstractXml::createProcessingInstruction ()
Create processing instruction in header.
Definition at line 145 of file musicabstractxml.cpp.
References m_ddom.
Referenced by MusicBarrageRecordConfigManager::writeBarrageConfig(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicListConfigManager::writeMusicSongsConfig(), MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicSkinConfigManager::writeSkinXMLConfig(), MusicUserConfigManager::writeUserXMLConfig(), MusicSysConfigManager::writeXMLConfig(), and MusicXSPFConfigManager::writeXSPFXMLConfig().
QDomElement MusicAbstractXml::createRoot (const QString & node)
Create xml node nodes by node name.
Definition at line 151 of file musicabstractxml.cpp.
References m_ddom.
Referenced by MusicASXConfigManager::writeASXXMLConfig(), MusicBarrageRecordConfigManager::writeBarrageConfig(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicListConfigManager::writeMusicSongsConfig(), MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicSkinConfigManager::writeSkinXMLConfig(), MusicUserConfigManager::writeUserXMLConfig(), MusicWPLConfigManager::writeWPLXMLConfig(), MusicSysConfigManager::writeXMLConfig(), and MusicXSPFConfigManager::writeXSPFXMLConfig().
QDomElement MusicAbstractXml::createRoot (const QString & node, const MusicXmlAttribute & attr)
Create xml node nodes by node atrr.
Definition at line 158 of file musicabstractxml.cpp.
References m_ddom, and writeAttribute().
QDomElement MusicAbstractXml::createRoot (const QString & node, const MusicXmlAttributes & attrs)
Create xml node nodes by node atrrs.
Definition at line 166 of file musicabstractxml.cpp.
References m_ddom, and writeAttribute().
bool MusicAbstractXml::fromByteArray (const QByteArray & data)
Xml stream data from byteArray.
Definition at line 71 of file musicabstractxml.cpp.
References m_ddom, and m_file.
Referenced by MusicDownloadBackgroundThunderThread::downLoadDataFinished(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicExtractWrap::outputSkin(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), and MusicDownLoadQueryKWThread::singleDownLoadFinished().
bool MusicAbstractXml::fromString (const QString & data)
Xml stream data from string.
Definition at line 58 of file musicabstractxml.cpp.
References m_ddom, and m_file.
QString MusicAbstractXml::getClassName () static
Get class object name.
Definition at line 20 of file musicabstractxml.cpp.
bool MusicAbstractXml::readConfig (const QString & name)
Read datas from xml file by given name.
Definition at line 25 of file musicabstractxml.cpp.
References m_ddom, and m_file.
Referenced by MusicPlayListManager::readASXList(), MusicCategoryConfigManager::readCategoryConfig(), MusicKWLConfigManager::readConfig(), MusicPlayListManager::readKGLList(), MusicPlayListManager::readLisList(), MusicListConfigManager::readMusicXMLConfig(), MusicPlayListManager::readWPLList(), MusicSysConfigManager::readXMLConfig(), and MusicPlayListManager::readXSPFList().
QString MusicAbstractXml::readXmlAttributeByTagName (const QString & tagName, const QString & attrName) const
Read xml attribute by tagName and attribute name.
Definition at line 107 of file musicabstractxml.cpp.
References m_ddom.
Referenced by readXmlAttributeByTagNameValue().
QString MusicAbstractXml::readXmlAttributeByTagNameValue (const QString & tagName) const
Read xml attribute by tagName and default name "value".
Definition at line 102 of file musicabstractxml.cpp.
References readXmlAttributeByTagName().
Referenced by MusicSysConfigManager::readShowDLrcGeometry(), MusicSkinConfigManager::readSkinXMLConfig(), and MusicSysConfigManager::readSysLoadConfig().
MusicObject::MStriantMap MusicAbstractXml::readXmlAttributesByTagName (const QString & tagName) const
Read xml attributes by tagName and default name "value".
Definition at line 128 of file musicabstractxml.cpp.
References m_ddom.
QString MusicAbstractXml::readXmlTextByTagName (const QString & tagName) const
Read xml attribute's text by tagName.
Definition at line 118 of file musicabstractxml.cpp.
References m_ddom.
Referenced by MusicKWMusicInfoConfigManager::readMusicInfoConfig(), and MusicXMMVInfoConfigManager::readMVInfoConfig().
QByteArray MusicAbstractXml::toByteArray () const
Xml stream data to byteArray.
Definition at line 93 of file musicabstractxml.cpp.
References m_ddom.
Referenced by MusicExtractWrap::inputSkin().
QString MusicAbstractXml::toString () const
Xml stream data to string.
Definition at line 84 of file musicabstractxml.cpp.
References m_ddom.
void MusicAbstractXml::writeAttribute (QDomElement & element, const MusicXmlAttribute & attr)
Append xml element nodes key name and value.
Definition at line 208 of file musicabstractxml.cpp.
References MusicXmlAttribute::m_key, and MusicXmlAttribute::m_value.
Referenced by createRoot(), writeDomElement(), and writeDomElementMutil().
bool MusicAbstractXml::writeConfig (const QString & name)
Write datas into xml file by given name.
Definition at line 45 of file musicabstractxml.cpp.
References m_ddom, and m_file.
Referenced by MusicASXConfigManager::writeASXXMLConfig(), MusicBarrageRecordConfigManager::writeBarrageConfig(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicListConfigManager::writeMusicSongsConfig(), MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicSkinConfigManager::writeSkinXMLConfig(), MusicUserConfigManager::writeUserXMLConfig(), MusicWPLConfigManager::writeWPLXMLConfig(), MusicSysConfigManager::writeXMLConfig(), and MusicXSPFConfigManager::writeXSPFXMLConfig().
QDomElement MusicAbstractXml::writeDom (QDomElement & element, const QString & node)
Append xml element nodes by node name.
Definition at line 177 of file musicabstractxml.cpp.
References m_ddom.
Referenced by MusicASXConfigManager::writeASXXMLConfig(), MusicBarrageRecordConfigManager::writeBarrageConfig(), writeDomElement(), writeDomText(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicWPLConfigManager::writeWPLXMLConfig(), and MusicSysConfigManager::writeXMLConfig().
QDomElement MusicAbstractXml::writeDomElement (QDomElement & element, const QString & node, const MusicXmlAttribute & attr)
Append xml element nodes by node name\ key name and value.
Definition at line 184 of file musicabstractxml.cpp.
References writeAttribute(), and writeDom().
Referenced by MusicASXConfigManager::writeASXXMLConfig(), writeDomElementMutil(), writeDomElementText(), MusicSkinConfigManager::writeSkinXMLConfig(), and MusicSysConfigManager::writeXMLConfig().
QDomElement MusicAbstractXml::writeDomElementMutil (QDomElement & element, const QString & node, const MusicXmlAttributes & attrs)
Append xml elements nodes by node name\ keys name and values.
Definition at line 192 of file musicabstractxml.cpp.
References writeAttribute(), and writeDomElement().
Referenced by MusicASXConfigManager::writeASXXMLConfig(), writeDomElementMutilText(), MusicListConfigManager::writeMusicSongsConfig(), MusicWPLConfigManager::writeWPLXMLConfig(), and MusicXSPFConfigManager::writeXSPFXMLConfig().
QDomElement MusicAbstractXml::writeDomElementMutilText (QDomElement & element, const QString & node, const MusicXmlAttributes & attrs, const QString & text)
Append xml elements nodes by node name\ keys name \ values and attribute's text.
Definition at line 236 of file musicabstractxml.cpp.
References m_ddom, and writeDomElementMutil().
Referenced by MusicBarrageRecordConfigManager::writeBarrageConfig(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicListConfigManager::writeMusicSongsConfig(), and MusicUserConfigManager::writeUserXMLConfig().
QDomElement MusicAbstractXml::writeDomElementText (QDomElement & element, const QString & node, const MusicXmlAttribute & attr, const QString & text)
Append xml element nodes by node name\ key name \ value and attribute's text.
Definition at line 227 of file musicabstractxml.cpp.
References m_ddom, and writeDomElement().
Referenced by MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicSysConfigManager::writeXMLConfig(), and MusicXSPFConfigManager::writeXSPFXMLConfig().
QDomElement MusicAbstractXml::writeDomText (QDomElement & element, const QString & node, const QString & text)
Append xml element nodes by node name and attribute's text.
Definition at line 250 of file musicabstractxml.cpp.
References m_ddom, and writeDom().
Referenced by MusicASXConfigManager::writeASXXMLConfig(), and MusicXSPFConfigManager::writeXSPFXMLConfig().
Member Data Documentation
QDomDocument* MusicAbstractXml::m_ddom protected
Definition at line 159 of file musicabstractxml.h.
Referenced by createProcessingInstruction(), createRoot(), fromByteArray(), fromString(), MusicAbstractXml(), MusicQQArtistInfoConfigManager::readArtistInfoConfig(), MusicASXConfigManager::readASXXMLConfig(), MusicBarrageRecordConfigManager::readBarrageConfig(), MusicCategoryConfigManager::readCategoryConfig(), readConfig(), MusicDownloadRecordConfigManager::readDownloadConfig(), MusicKGLConfigManager::readKGLXMLConfig(), MusicKWLConfigManager::readKWLXMLConfig(), MusicListConfigManager::readMusicSongsConfig(), MusicXMMVInfoConfigManager::readMVInfoConfig(), MusicLocalSongSearchRecordConfigManager::readSearchConfig(), MusicSkinThunderConfigManager::readSkinRemoteXMLConfig(), MusicSysConfigManager::readSystemLastPlayIndexConfig(), MusicUserConfigManager::readUserConfig(), MusicSysConfigManager::readWindowGeometry(), MusicWPLConfigManager::readWPLXMLConfig(), readXmlAttributeByTagName(), readXmlAttributesByTagName(), readXmlTextByTagName(), MusicXSPFConfigManager::readXSPFXMLConfig(), toByteArray(), toString(), MusicASXConfigManager::writeASXXMLConfig(), MusicBarrageRecordConfigManager::writeBarrageConfig(), writeConfig(), writeDom(), writeDomElementMutilText(), writeDomElementText(), writeDomText(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicListConfigManager::writeMusicSongsConfig(), MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicSkinConfigManager::writeSkinXMLConfig(), MusicUserConfigManager::writeUserXMLConfig(), MusicWPLConfigManager::writeWPLXMLConfig(), MusicSysConfigManager::writeXMLConfig(), MusicXSPFConfigManager::writeXSPFXMLConfig(), and ~MusicAbstractXml().
QFile* MusicAbstractXml::m_file protected
Definition at line 158 of file musicabstractxml.h.
Referenced by fromByteArray(), fromString(), MusicAbstractXml(), readConfig(), MusicKWLConfigManager::readConfig(), MusicKGLConfigManager::readKGLXMLConfig(), MusicKWLConfigManager::readKWLXMLConfig(), MusicASXConfigManager::writeASXXMLConfig(), MusicBarrageRecordConfigManager::writeBarrageConfig(), writeConfig(), MusicDownloadRecordConfigManager::writeDownloadConfig(), MusicListConfigManager::writeMusicSongsConfig(), MusicLocalSongSearchRecordConfigManager::writeSearchConfig(), MusicSkinConfigManager::writeSkinXMLConfig(), MusicUserConfigManager::writeUserXMLConfig(), MusicWPLConfigManager::writeWPLXMLConfig(), MusicSysConfigManager::writeXMLConfig(), MusicXSPFConfigManager::writeXSPFXMLConfig(), and ~MusicAbstractXml().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicabstractxml.h
TTKModule/TTKCore/musicCoreKits/musicabstractxml.cpp