TTKMusicplayer: MusicNetworkSpeedSuspensionWidget Class Reference
MusicNetworkSpeedSuspensionWidget Class Reference
The class of the network speed suspension widget.
#include <musicnetworkspeedsuspensionwidget.h>
Public Member Functions
MusicNetworkSpeedSuspensionWidget (QWidget *parent=0)
virtual ~MusicNetworkSpeedSuspensionWidget ()
void setAvailableNewtworkNames (const QStringList &names)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
MusicNetworkSpeedTestThread * m_thread
QString m_upload
QString m_download
QActionGroup * m_actionGroup
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Private Slots
void networkData (ulong upload, ulong download)
void actionTriggered (QAction *action)
Additional Inherited Members
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Detailed Description
The class of the network speed suspension widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 20 of file musicnetworkspeedsuspensionwidget.h.
Constructor & Destructor Documentation
MusicNetworkSpeedSuspensionWidget::MusicNetworkSpeedSuspensionWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 12 of file musicnetworkspeedsuspensionwidget.cpp.
References actionTriggered(), MusicAbstractMoveWidget::drawWindowShadow(), m_actionGroup, m_download, m_thread, m_upload, networkData(), and MusicNetworkSpeedTestThread::start().
MusicNetworkSpeedSuspensionWidget::~MusicNetworkSpeedSuspensionWidget () virtual
Definition at line 42 of file musicnetworkspeedsuspensionwidget.cpp.
References m_actionGroup, and m_thread.
Member Function Documentation
void MusicNetworkSpeedSuspensionWidget::actionTriggered (QAction * action) private slot
Select diff network interface action.
Definition at line 123 of file musicnetworkspeedsuspensionwidget.cpp.
References m_actionGroup.
Referenced by MusicNetworkSpeedSuspensionWidget().
void MusicNetworkSpeedSuspensionWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 53 of file musicnetworkspeedsuspensionwidget.cpp.
References MusicNetworkSpeedTestThread::getAvailableNewtworkNames(), MusicNetworkSpeedTestThread::getNewtworkNames(), m_actionGroup, m_thread, and MusicUIObject::MMenuStyle02.
QString MusicNetworkSpeedSuspensionWidget::getClassName () static
Get class object name.
Definition at line 48 of file musicnetworkspeedsuspensionwidget.cpp.
void MusicNetworkSpeedSuspensionWidget::networkData (ulong upload, ulong download) private slot
Send current upload and download speed data.
Definition at line 116 of file musicnetworkspeedsuspensionwidget.cpp.
References m_download, m_upload, and MusicUtils::Number::speed2Label().
Referenced by MusicNetworkSpeedSuspensionWidget().
void MusicNetworkSpeedSuspensionWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
redraw background color
Reimplemented from MusicAbstractMoveWidget.
Definition at line 78 of file musicnetworkspeedsuspensionwidget.cpp.
References m_download, m_upload, and MusicAbstractMoveWidget::paintEvent().
void MusicNetworkSpeedSuspensionWidget::setAvailableNewtworkNames (const QStringList & names)
Set available newtwork names.
Definition at line 111 of file musicnetworkspeedsuspensionwidget.cpp.
References m_thread, and MusicNetworkSpeedTestThread::setAvailableNewtworkNames().
Referenced by MusicNetworkSpeedTestWidget::suspensionOpen().
Member Data Documentation
QActionGroup* MusicNetworkSpeedSuspensionWidget::m_actionGroup protected
Definition at line 60 of file musicnetworkspeedsuspensionwidget.h.
Referenced by actionTriggered(), contextMenuEvent(), MusicNetworkSpeedSuspensionWidget(), and ~MusicNetworkSpeedSuspensionWidget().
QString MusicNetworkSpeedSuspensionWidget::m_download protected
Definition at line 59 of file musicnetworkspeedsuspensionwidget.h.
Referenced by MusicNetworkSpeedSuspensionWidget(), networkData(), and paintEvent().
MusicNetworkSpeedTestThread* MusicNetworkSpeedSuspensionWidget::m_thread protected
Definition at line 58 of file musicnetworkspeedsuspensionwidget.h.
Referenced by contextMenuEvent(), MusicNetworkSpeedSuspensionWidget(), setAvailableNewtworkNames(), and ~MusicNetworkSpeedSuspensionWidget().
QString MusicNetworkSpeedSuspensionWidget::m_upload protected
Definition at line 59 of file musicnetworkspeedsuspensionwidget.h.
Referenced by MusicNetworkSpeedSuspensionWidget(), networkData(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkspeedsuspensionwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkspeedsuspensionwidget.cpp