TTKMusicplayer: TTKThirdParty/Zlib/zlib/inftrees.c File Reference
inftrees.c File Reference
#include "zutil.h"
#include "inftrees.h"
Macros
#define MAXBITS 15
Functions
int ZLIB_INTERNAL inflate_table (codetype type, unsigned short FAR *lens, unsigned codes, code FAR *FAR *table, unsigned FAR *bits, unsigned short FAR *work)
Variables
const char inflate_copyright []
Macro Definition Documentation
#define MAXBITS 15
Definition at line 9 of file inftrees.c.
Referenced by inflate_table().
Function Documentation
int ZLIB_INTERNAL inflate_table (codetype type, unsigned short FAR * lens, unsigned codes, code FAR * FAR * table, unsigned FAR * bits, unsigned short FAR * work)
Definition at line 32 of file inftrees.c.
References code::bits, CODES, DISTS, ENOUGH_DISTS, ENOUGH_LENS, FAR, int(), LENS, MAXBITS, code::op, and code::val.
Referenced by fixedtables(), inflate(), and inflateBack().
Variable Documentation
const char inflate_copyright[]
Initial value:
=
   " inflate 1.2.11 Copyright 1995-2017 Mark Adler "
Definition at line 11 of file inftrees.c.