TTKMusicplayer: QNSimpleDeleteData Class Reference
QNSimpleDeleteData Class Reference
The namespace of the qiniu simple delete data.
#include <qnsimpledeletedata.h>
Signals
void deleteFileFinished (bool state)
Public Member Functions
QNSimpleDeleteData (QNetworkAccessManager *networkManager, QObject *parent=0)
void deleteDataToServer (const QString &bucket, const QString &key)
Private Slots
void receiveDataFromServer ()
void handleError (QNetworkReply::NetworkError error)
Detailed Description
The namespace of the qiniu simple delete data.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 31 of file qnsimpledeletedata.h.
Constructor & Destructor Documentation
QNSimpleDeleteData::QNSimpleDeleteData (QNetworkAccessManager * networkManager, QObject * parent = 0) explicit
Object contsructor.
Definition at line 24 of file qnsimpledeletedata.cpp.
References MUSIC_D, and MUSIC_INIT_PRIVATE.
Member Function Documentation
void QNSimpleDeleteData::deleteDataToServer (const QString & bucket, const QString & key)
Delete data to server.
Definition at line 32 of file qnsimpledeletedata.cpp.
References QNConf::ACCESS_KEY, QNIOHelper::deleteRequest(), handleError(), MUSIC_D, receiveDataFromServer(), and QNConf::SECRET_KEY.
Referenced by MusicCloudSharedSongTableWidget::deleteFilesToServer(), and MusicCloudSharedSongTableWidget::deleteFileToServer().
void QNSimpleDeleteData::deleteFileFinished (bool state) signal
Delete file finished.
Referenced by receiveDataFromServer().
void QNSimpleDeleteData::handleError (QNetworkReply::NetworkError error) private slot
Get handle error.
Definition at line 57 of file qnsimpledeletedata.cpp.
Referenced by deleteDataToServer().
void QNSimpleDeleteData::receiveDataFromServer () private slot
Receive data from server.
Definition at line 43 of file qnsimpledeletedata.cpp.
References deleteFileFinished(), and MObject_cast.
Referenced by deleteDataToServer().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnsimpledeletedata.h
TTKThirdParty/TTKExtras/qiniu/qnsimpledeletedata.cpp