TTKMusicPlayer: TTKAbstractMoveResizeWidget Class Reference
TTKAbstractMoveResizeWidget Class Reference
The class of the moving resize widget base.
#include <ttkabstractmoveresizewidget.h>
Public Types
enum Direction {
Direction::No = 0, Direction::Left = 1, Direction::Top = 2, Direction::Right = 4,
Direction::Bottom = 8, Direction::LeftTop = Direction::Left | Direction::Top, Direction::LeftBottom = Direction::Left | Direction::Bottom, Direction::RightTop = Direction::Right | Direction::Top,
Direction::RightBottom = Direction::Right | Direction::Bottom
}
Public Member Functions
TTKAbstractMoveResizeWidget (QWidget *parent=nullptr)
Protected Member Functions
virtual bool eventFilter (QObject *object, QEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void sizeDirection ()
void moveDirection ()
QObjectList foreachWidget (QObject *object)
Protected Attributes
MoveResizeData m_struct
Direction m_direction
Detailed Description
The class of the moving resize widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com Lverson what9.nosp@m.5100.nosp@m.6@163.nosp@m..com
Definition at line 42 of file ttkabstractmoveresizewidget.h.
Member Enumeration Documentation
enum TTKAbstractMoveResizeWidget::Direction strong
Enumerator
No
Left
Top
Right
Bottom
LeftTop
LeftBottom
RightTop
RightBottom
Definition at line 47 of file ttkabstractmoveresizewidget.h.
Constructor & Destructor Documentation
TTKAbstractMoveResizeWidget::TTKAbstractMoveResizeWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 13 of file ttkabstractmoveresizewidget.cpp.
References MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, and m_struct.
Member Function Documentation
bool TTKAbstractMoveResizeWidget::eventFilter (QObject * object, QEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicApplication.
Definition at line 26 of file ttkabstractmoveresizewidget.cpp.
References TTKStatic_cast.
Referenced by MusicApplication::eventFilter().
QObjectList TTKAbstractMoveResizeWidget::foreachWidget (QObject * object) protected
Get all inside widgets.
Definition at line 279 of file ttkabstractmoveresizewidget.cpp.
void TTKAbstractMoveResizeWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 76 of file ttkabstractmoveresizewidget.cpp.
References MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, MoveResizeData::m_mousePos, m_struct, MoveResizeData::m_windowPos, moveDirection(), QtMouseEventGlobalPos, and sizeDirection().
void TTKAbstractMoveResizeWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Reimplemented in MusicApplication.
Definition at line 53 of file ttkabstractmoveresizewidget.cpp.
References DISTANCE, MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, MoveResizeData::m_mousePos, MoveResizeData::m_pressedSize, m_struct, MoveResizeData::m_windowPos, and QtMouseEventGlobalPos.
Referenced by MusicApplication::mousePressEvent().
void TTKAbstractMoveResizeWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Reimplemented in MusicApplication.
Definition at line 87 of file ttkabstractmoveresizewidget.cpp.
References m_direction, MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, m_struct, and No.
Referenced by MusicApplication::mouseReleaseEvent().
void TTKAbstractMoveResizeWidget::moveDirection () protected
Move direction to be.
Definition at line 146 of file ttkabstractmoveresizewidget.cpp.
References Bottom, Left, LeftBottom, LeftTop, m_direction, MoveResizeData::m_pressedSize, m_struct, MoveResizeData::m_windowPos, Right, RightBottom, RightTop, SET_GEOMETRY, and Top.
Referenced by mouseMoveEvent().
void TTKAbstractMoveResizeWidget::paintEvent (QPaintEvent * event) override protected virtual
Definition at line 37 of file ttkabstractmoveresizewidget.cpp.
References DISTANCE, m_direction, MoveResizeData::m_isPressBorder, m_struct, and No.
void TTKAbstractMoveResizeWidget::sizeDirection () protected
Size direction detected.
Definition at line 96 of file ttkabstractmoveresizewidget.cpp.
References Bottom, DISTANCE, Left, LeftBottom, LeftTop, m_direction, No, Right, RightBottom, RightTop, and Top.
Referenced by mouseMoveEvent().
Member Data Documentation
Direction TTKAbstractMoveResizeWidget::m_direction protected
Definition at line 88 of file ttkabstractmoveresizewidget.h.
Referenced by mouseReleaseEvent(), moveDirection(), paintEvent(), and sizeDirection().
MoveResizeData TTKAbstractMoveResizeWidget::m_struct protected
Definition at line 87 of file ttkabstractmoveresizewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveDirection(), paintEvent(), and TTKAbstractMoveResizeWidget().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractmoveresizewidget.h
TTKCommon/TTKLibrary/ttkabstractmoveresizewidget.cpp