TTKMusicplayer: DecoderFactory Class Reference
DecoderFactory Class Reference abstract
Input plugin interface (decoder factory).
#include <decoderfactory.h>
Public Member Functions
virtual ~DecoderFactory ()
virtual bool canDecode (QIODevice *d) const =0
virtual const DecoderProperties properties () const =0
virtual Decoder * create (const QString &path, QIODevice *input=0)=0
virtual QList< FileInfo * > createPlayList (const QString &fileName, bool useMetaData, QStringList *ignoredPaths)=0
virtual MetaDataModel * createMetaDataModel (const QString &path, QObject *parent=0)=0
virtual ~DecoderFactory ()
virtual bool canDecode (QIODevice *d) const =0
virtual const DecoderProperties properties () const =0
virtual Decoder * create (const QString &path, QIODevice *input=0)=0
virtual QList< FileInfo * > createPlayList (const QString &fileName, bool useMetaData, QStringList *ignoredPaths)=0
virtual MetaDataModel * createMetaDataModel (const QString &path, QObject *parent=0)=0
Detailed Description
Input plugin interface (decoder factory).
Author
Ilya Kotov forko.nosp@m.tov0.nosp@m.2@ya..nosp@m.ru
Definition at line 67 of file decoderfactory.h.
Constructor & Destructor Documentation
virtual DecoderFactory::~DecoderFactory () inline virtual
Object destructor.
Definition at line 73 of file decoderfactory.h.
virtual DecoderFactory::~DecoderFactory () inline virtual
Object destructor.
Definition at line 74 of file decoderfactory.h.
Member Function Documentation
virtual bool DecoderFactory::canDecode (QIODevice * d) const pure virtual
Returns true if plugin can decode data provided by d, otherwise returns false
virtual bool DecoderFactory::canDecode (QIODevice * d) const pure virtual
Returns true if plugin can decode data provided by d, otherwise returns false
virtual Decoder* DecoderFactory::create (const QString & path, QIODevice * input = 0) pure virtual
Creates decoder object.
Parameters
path File path
input Input data (if required)
virtual Decoder* DecoderFactory::create (const QString & path, QIODevice * input = 0) pure virtual
Creates decoder object.
Parameters
path File path
input Input data (if required)
virtual MetaDataModel* DecoderFactory::createMetaDataModel (const QString & path, QObject * parent = 0) pure virtual
Creats metadata object, which provides full access to file tags.
Parameters
path File path.
parent Parent object.
Returns
MetaDataModel pointer.
Referenced by MusicSongTag::readOtherTaglib(), and MusicSongTag::saveOtherTaglib().
virtual MetaDataModel* DecoderFactory::createMetaDataModel (const QString & path, QObject * parent = 0) pure virtual
Creats metadata object, which provides full access to file tags.
Parameters
path File path.
parent Parent object.
Returns
MetaDataModel pointer.
virtual QList<FileInfo *> DecoderFactory::createPlayList (const QString & fileName, bool useMetaData, QStringList * ignoredPaths) pure virtual
Extracts metadata and audio information from file path and returns a list of FileInfo items. One file may contain several playlist items (for example: cda disk or flac with embedded cue)
Parameters
fileName File path.
useMetaData Metadata usage (true - use, - do not use)
ignoredPaths Pointer to a list of the files which should be ignored by the recursive search (useful to exclude cue data files from playlist)
Referenced by MusicSongTag::readOtherTaglib().
virtual QList<FileInfo *> DecoderFactory::createPlayList (const QString & fileName, bool useMetaData, QStringList * ignoredPaths) pure virtual
Extracts metadata and audio information from file path and returns a list of FileInfo items. One file may contain several playlist items (for example: cda disk or flac with embedded cue)
Parameters
fileName File path.
useMetaData Metadata usage (true - use, - do not use)
ignoredPaths Pointer to a list of the files which should be ignored by the recursive search (useful to exclude cue data files from playlist)
virtual const DecoderProperties DecoderFactory::properties () const pure virtual
Returns general plugin properties.
virtual const DecoderProperties DecoderFactory::properties () const pure virtual
Returns general plugin properties.
The documentation for this class was generated from the following file:
TTKExtra/Qt4/decoderfactory.h