TTKMusicPlayer: MusicLocalManagerSongsTableWidget Class Reference
MusicLocalManagerSongsTableWidget Class Reference
The class of the local manager songs table widget.
#include <musiclocalmanagerwidget.h>
Public Slots
virtual void removeItems () overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Public Slots inherited from MusicAbstractSongsListTableWidget
virtual void removeItemAt ()
void playClicked ()
void clearItems ()
void openFileDir ()
void showFileInformation ()
void showMovieQueryWidget ()
void showAlbumQueryWidget ()
void showSimilarQueryWidget ()
void showSongSharedWidget ()
void showDownloadWidget ()
void showPlayedMovieQueryWidget ()
void showPlayedSimilarQueryWidget ()
void showPlayedSongSharedWidget ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicLocalManagerSongsTableWidget (QWidget *parent=nullptr)
~MusicLocalManagerSongsTableWidget ()
void addCellItems (const MusicSongInfoItemList &songs)
void resizeSection () const
Public Member Functions inherited from MusicAbstractSongsListTableWidget
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
MusicAbstractSongsListTableWidget (int index, QWidget *parent=nullptr)
~MusicAbstractSongsListTableWidget ()
virtual void setSongsList (MusicSongList *songs)
virtual void updateSongsList (const MusicSongList &songs)
virtual void selectRow (int index)
int totalHeight () const
void setPlaylistRow (int index)
void setPlayRowIndex (int index)
int playRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Additional Inherited Members
Signals inherited from MusicAbstractSongsListTableWidget
void isCurrentPlaylistRow (bool &state)
Protected Member Functions inherited from MusicAbstractSongsListTableWidget
void createMoreMenu (QMenu *menu)
QString currentSongPath () const
QString songPath (int index) const
QString currentSongName () const
QString songName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from MusicAbstractSongsListTableWidget
int m_playlistRow
int m_playRowIndex
MusicSongList * m_songs
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_initialized
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the local manager songs table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 74 of file musiclocalmanagerwidget.h.
Constructor & Destructor Documentation
MusicLocalManagerSongsTableWidget::MusicLocalManagerSongsTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 107 of file musiclocalmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::m_songs, and TTK::UI::ScrollBarStyle04.
MusicLocalManagerSongsTableWidget::~MusicLocalManagerSongsTableWidget ()
Object destructor.
Definition at line 135 of file musiclocalmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::m_songs, and removeItems().
Member Function Documentation
void MusicLocalManagerSongsTableWidget::addCellItems (const MusicSongInfoItemList & songs)
Create cell items by input data.
Definition at line 141 of file musiclocalmanagerwidget.cpp.
References MusicSongInfoItem::m_album, MusicSongInfoItem::m_artist, MusicSongInfoItem::m_genre, MusicSongInfoItem::m_path, MusicAbstractSongsListTableWidget::m_songs, MusicSongInfoItem::m_title, MusicSongInfoItem::m_track, MusicSongInfoItem::m_year, and QtItemSetTextAlignment.
Referenced by MusicLocalManagerWidget::refreshItems(), and MusicLocalManagerWidget::searchResultChanged().
void MusicLocalManagerSongsTableWidget::contextMenuEvent (QContextMenuEvent * event) final override virtual slot
Override the widget event.
Definition at line 211 of file musiclocalmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::createMoreMenu(), MusicAbstractSongsListTableWidget::currentSongPath(), TTK::String::isNetworkUrl(), MusicAbstractSongsListTableWidget::m_songs, TTK::UI::MenuStyle02, MusicAbstractSongsListTableWidget::openFileDir(), MusicAbstractSongsListTableWidget::playClicked(), MusicAbstractSongsListTableWidget::showAlbumQueryWidget(), and MusicAbstractSongsListTableWidget::showFileInformation().
void MusicLocalManagerSongsTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 205 of file musiclocalmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::m_songs, and TTKAbstractTableWidget::removeItems().
Referenced by MusicLocalManagerWidget::refreshItems(), MusicLocalManagerWidget::searchResultChanged(), and ~MusicLocalManagerSongsTableWidget().
void MusicLocalManagerSongsTableWidget::resizeSection () const
Resize section bound by resize called.
Definition at line 195 of file musiclocalmanagerwidget.cpp.
References G_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicLocalManagerWidget::resizeWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiclocalmanagerwidget.h
TTKModule/TTKWidget/musicToolsKits/musiclocalmanagerwidget.cpp