TTKMusicPlayer: QJsonRoot Class Reference
QJsonRoot Class Reference abstract
#include <QJsonRoot.h>
Public Member Functions
virtual ~QJsonRoot ()
virtual QJsonRoot * clone () const =0
virtual QJsonArray * toArray ()=0
virtual QJsonObject * toObject ()=0
virtual const QJsonArray * toArray () const =0
virtual const QJsonObject * toObject () const =0
Detailed Description
Definition at line 32 of file QJsonRoot.h.
Constructor & Destructor Documentation
virtual QJsonRoot::~QJsonRoot () inline virtual
Definition at line 34 of file QJsonRoot.h.
Member Function Documentation
virtual QJsonRoot* QJsonRoot::clone () const pure virtual
Implemented in QJsonArray, and QJsonObject.
Referenced by QJsonDocument::QJsonDocument(), QJsonValue::QJsonValue(), and QJsonDocument::setRoot().
virtual QJsonArray* QJsonRoot::toArray () pure virtual
Implemented in QJsonArray, and QJsonObject.
Referenced by QJsonDocument::array(), QJsonDocument::isArray(), QJsonValueRef::operator=(), QJsonValue::operator==(), QJsonValue::toArray(), QJsonValueRef::toValue(), QJsonDocument::toVariant(), and QJsonValue::toVariant().
virtual const QJsonArray* QJsonRoot::toArray () const pure virtual
Implemented in QJsonArray, and QJsonObject.
virtual QJsonObject* QJsonRoot::toObject () pure virtual
Implemented in QJsonArray, and QJsonObject.
Referenced by QJsonDocument::isObject(), QJsonDocument::object(), QJsonValueRef::operator=(), QJsonValue::operator==(), QJsonValue::toObject(), QJsonValueRef::toValue(), QJsonDocument::toVariant(), and QJsonValue::toVariant().
virtual const QJsonObject* QJsonRoot::toObject () const pure virtual
Implemented in QJsonArray, and QJsonObject.
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qjson/QJsonRoot.h