TTKMusicplayer: MusicFuntionAnimationWidget Class Reference
MusicFuntionAnimationWidget Class Reference
The class of the function animation widget.
#include <musicfuntionanimationwidget.h>
Public Slots
virtual void switchToSelectedItemStyle (int index) override
Public Slots inherited from MusicBaseAnimationWidget
virtual void switchToSelectedItemStyle (int index)
void animationChanged (const QVariant &value)
void finished ()
Public Member Functions
MusicFuntionAnimationWidget (QWidget *parent=0)
Public Member Functions inherited from MusicBaseAnimationWidget
MusicBaseAnimationWidget (QWidget *parent=0)
~MusicBaseAnimationWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicBaseAnimationWidget
static QString getClassName ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Signals inherited from MusicBaseAnimationWidget
void buttonClicked (int index)
Protected Attributes inherited from MusicBaseAnimationWidget
QPixmap m_pix
int m_curIndex
int m_preIndex
int m_x
float m_perWidth
float m_totalWidth
bool m_isAnimation
bool m_showState
bool m_showLine
QPropertyAnimation * m_animation
QList< QWidget * > m_container
QButtonGroup * m_group
Detailed Description
The class of the function animation widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 153 of file musicfuntionanimationwidget.h.
Constructor & Destructor Documentation
MusicFuntionAnimationWidget::MusicFuntionAnimationWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 166 of file musicfuntionanimationwidget.cpp.
References MusicBaseAnimationWidget::m_container, MusicBaseAnimationWidget::m_group, MStatic_cast, and switchToSelectedItemStyle().
Member Function Documentation
QString MusicFuntionAnimationWidget::getClassName () static
Get class object name.
Definition at line 187 of file musicfuntionanimationwidget.cpp.
void MusicFuntionAnimationWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicBaseAnimationWidget.
Definition at line 192 of file musicfuntionanimationwidget.cpp.
References MusicBaseAnimationWidget::m_totalWidth, and MusicBaseAnimationWidget::paintEvent().
void MusicFuntionAnimationWidget::switchToSelectedItemStyle (int index) override virtual slot
Switch to selected item style.
Definition at line 198 of file musicfuntionanimationwidget.cpp.
References MusicBaseAnimationWidget::m_container, MusicUIObject::MKGItemDownload, MusicUIObject::MKGItemDownloadClicked, MusicUIObject::MKGItemFavourite, MusicUIObject::MKGItemFavouriteClicked, MusicUIObject::MKGItemMobile, MusicUIObject::MKGItemMobileClicked, MusicUIObject::MKGItemMusic, MusicUIObject::MKGItemMusicClicked, MusicUIObject::MKGItemRadio, MusicUIObject::MKGItemRadioClicked, and MusicBaseAnimationWidget::switchToSelectedItemStyle().
Referenced by MusicFuntionAnimationWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicfuntionanimationwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicfuntionanimationwidget.cpp