TTKMusicplayer: MusicKGSongCommentsThread Class Reference
MusicKGSongCommentsThread Class Reference
The class to kugou query song comments download data from net.
#include <musickgcommentsthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKGSongCommentsThread (QObject *parent=0)
QJson import.
virtual void startToSearch (const QString &name) override
virtual void startToPage (int offset) override
Public Member Functions inherited from MusicDownLoadCommentsThread
MusicDownLoadCommentsThread (QObject *parent=0)
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadCommentsThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadCommentsThread
void createSearchedItem (const MusicResultsItem &comments)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class to kugou query song comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickgcommentsthread.h.
Constructor & Destructor Documentation
MusicKGSongCommentsThread::MusicKGSongCommentsThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 8 of file musickgcommentsthread.cpp.
References MusicDownLoadPagingThread::m_pageSize.
Member Function Documentation
void MusicKGSongCommentsThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 63 of file musickgcommentsthread.cpp.
References MusicDownLoadCommentsThread::createSearchedItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicResultsItem::m_nickName, MusicDownLoadPagingThread::m_pageTotal, MusicResultsItem::m_playCount, MusicNetworkAbstract::m_reply, MusicResultsItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToPage().
QString MusicKGSongCommentsThread::getClassName () static
Get class object name.
Definition at line 14 of file musickgcommentsthread.cpp.
Referenced by downLoadFinished(), startToPage(), and startToSearch().
void MusicKGSongCommentsThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 38 of file musickgcommentsthread.cpp.
References ALG_UA_KEY, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), KG_SG_COMMIT_URL, KG_UA_URL_1, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_rawData, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), and MusicUtils::Codec::toUtf8().
Referenced by startToSearch().
void MusicKGSongCommentsThread::startToSearch (const QString & name) override virtual
Start to Search data from name.
Implements MusicDownLoadCommentsThread.
Definition at line 19 of file musickgcommentsthread.cpp.
References MusicNetworkAbstract::downLoadDataChanged(), MusicSemaphoreLoop::exec(), getClassName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), M_LOGGER_INFO, MusicNetworkAbstract::m_rawData, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), MusicDownLoadQueryThreadAbstract::setQuerySimplify(), startToPage(), and MusicDownLoadQueryKGThread::startToSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/kg/musickgcommentsthread.h
TTKModule/TTKCore/musicNetworkKits/kg/musickgcommentsthread.cpp