TTKMusicplayer: MusicLrcColorWidget Class Reference
MusicLrcColorWidget Class Reference
The class of the lrc color picker widget.
#include <musiclrccolorwidget.h>
Public Slots
void addButtonClicked ()
void deleteButtonClicked ()
void modifyButtonClicked ()
void upButtonClicked ()
void downButtonClicked ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicLrcColorWidget (QWidget *parent=nullptr)
~MusicLrcColorWidget ()
void setColors (const QList< QColor > &colors)
QList< QColor > colors () const
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicLrcColorWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the lrc color picker widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrccolorwidget.h.
Constructor & Destructor Documentation
MusicLrcColorWidget::MusicLrcColorWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musiclrccolorwidget.cpp.
References addButtonClicked(), deleteButtonClicked(), downButtonClicked(), m_ui, modifyButtonClicked(), MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, and upButtonClicked().
MusicLrcColorWidget::~MusicLrcColorWidget ()
Definition at line 47 of file musiclrccolorwidget.cpp.
References m_ui.
Member Function Documentation
void MusicLrcColorWidget::addButtonClicked () slot
Add button clicked.
Definition at line 80 of file musiclrccolorwidget.cpp.
References MusicColorDialog::color(), MusicColorDialog::exec(), and m_ui.
Referenced by MusicLrcColorWidget().
QList< QColor > MusicLrcColorWidget::colors () const
Get selected colors.
Definition at line 66 of file musiclrccolorwidget.cpp.
References m_ui.
Referenced by MusicSettingWidget::lcrColorValue().
void MusicLrcColorWidget::deleteButtonClicked () slot
Delete button clicked.
Definition at line 96 of file musiclrccolorwidget.cpp.
References m_ui.
Referenced by MusicLrcColorWidget().
void MusicLrcColorWidget::downButtonClicked () slot
Down button clicked.
Definition at line 138 of file musiclrccolorwidget.cpp.
References m_ui.
Referenced by MusicLrcColorWidget().
int MusicLrcColorWidget::exec () virtual slot
Override exec function.
Definition at line 153 of file musiclrccolorwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicSettingWidget::lcrColorValue().
void MusicLrcColorWidget::modifyButtonClicked () slot
Modify button clicked.
Definition at line 105 of file musiclrccolorwidget.cpp.
References MusicColorDialog::color(), MusicColorDialog::exec(), and m_ui.
Referenced by MusicLrcColorWidget().
void MusicLrcColorWidget::setColors (const QList< QColor > & colors)
Set current colors.
Definition at line 52 of file musiclrccolorwidget.cpp.
References m_ui.
Referenced by MusicSettingWidget::lcrColorValue().
void MusicLrcColorWidget::upButtonClicked () slot
Up button clicked.
Definition at line 123 of file musiclrccolorwidget.cpp.
References m_ui.
Referenced by MusicLrcColorWidget().
Member Data Documentation
Ui::MusicLrcColorWidget* MusicLrcColorWidget::m_ui protected
Definition at line 78 of file musiclrccolorwidget.h.
Referenced by addButtonClicked(), colors(), deleteButtonClicked(), downButtonClicked(), exec(), modifyButtonClicked(), MusicLrcColorWidget(), setColors(), upButtonClicked(), and ~MusicLrcColorWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccolorwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrccolorwidget.cpp