TTKMusicplayer: MusicRightAreaWidget Class Reference
MusicRightAreaWidget Class Reference
The class of the app right area widget.
#include <musicrightareawidget.h>
Public Types
enum MusicFunction {
KugGouSongWidget, KugGouRadioWidget, kugouListWidget, VideoWidget,
kugouLiveWidget, LrcWidget, SearchWidget, SearchSingleWidget,
SimilarWidget, AlbumWidget, ArtistWidget, ArtistCategoryWidget,
ToplistWidget, PlaylistWidget, AdvancedSearchWidget, RecommendWidget,
IndentifyWidget, KuiSheWidget, WebDJRadioWidget, WebMVRadioWidget,
CloudManagerWidget, ScreenSaverWidget
}
Public Slots
void functionClicked (int index, QWidget *widget=nullptr)
void musicSongCommentsWidget ()
void musicSimilarFound (const QString &text)
void musicAlbumFound (const QString &text, const QString &id)
void musicArtistCategoryFound ()
void musicArtistSearchFound ()
void musicAlbumSearchFound ()
void musicMovieSearchFound ()
void musicMovieSearchRadioFound ()
void musicArtistFound (const QString &text, const QString &id)
void musicToplistFound ()
void musicPlaylistFound (const QString &id)
void musicRecommendFound ()
void musicAdvancedSearch ()
void musicSongSearchedFound (const QString &text)
void musicSingleSearchedFound (const QString &id)
void musicLoadSongIndexWidget ()
void deleteStackedFuncWidget ()
void setDestopLrcVisible (bool visible) const
void setWindowLockedChanged ()
void setWindowLrcTypeChanged ()
void researchQueryByQuality (const QString &quality)
void musicVideoButtonSearched (const QString &name, const QString &id)
void musicVideoSetPopup (bool popup)
void musicVideoActiveWindow ()
void musicVideoClosed ()
void musicVideoFullscreen (bool full)
void musicLrcDisplayAllButtonClicked ()
void musicContainerForWallpaperClicked ()
void musicChangeDownloadFulllyWidget ()
void musicChangeDownloadCustumWidget ()
Signals
void updateBackgroundThemeDownload ()
void updateBackgroundTheme ()
Public Member Functions
MusicRightAreaWidget (QWidget *parent=nullptr)
~MusicRightAreaWidget ()
void setupUi (Ui::MusicApplication *ui)
void startDrawLrc () const
void stopDrawLrc () const
void setCurrentPlayStatus (bool status) const
bool destopLrcVisible () const
void setInteriorLrcVisible (bool status) const
bool interiorLrcVisible () const
void applySettingParameter ()
bool checkSettingParameterValue () const
void updateCurrentLrc (qint64 current, qint64 total, bool playStatus) const
void loadCurrentSongLrc (const QString &name, const QString &path) const
void setSongSpeedAndSlow (qint64 time) const
void checkLrcValid () const
void showSettingWidget () const
void musicArtistSearch (const QString &id)
void musicAlbumSearch (const QString &id)
void musicMovieSearch (const QString &id)
void musicMovieRadioSearch (const QVariant &data)
void resizeWindow ()
Static Public Member Functions
static MusicRightAreaWidget * instance ()
Protected Member Functions
void functionParameterInit ()
void createkWindow (int type)
Protected Attributes
QVariant m_rawData
bool m_lowPowerMode
MusicFunction m_funcIndex
QWidget * m_stackedFuncWidget
QWidget * m_stackedAutoWidget
Ui::MusicApplication * m_ui
MusicSettingWidget * m_settingWidget
MusicVideoPlayWidget * m_videoPlayerWidget
MusicLrcAnalysis * m_lrcAnalysis
MusicLrcContainerForInterior * m_musicLrcForInterior
MusicLrcContainerForDesktop * m_musicLrcForDesktop
MusicLrcContainerForWallpaper * m_musicLrcForWallpaper
MusicDownloadStatusModule * m_downloadStatusObject
Static Protected Attributes
static MusicRightAreaWidget * m_instance = nullptr
Detailed Description
The class of the app right area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 41 of file musicrightareawidget.h.
Member Enumeration Documentation
enum MusicRightAreaWidget::MusicFunction
Enumerator
KugGouSongWidget
insert kugou song widget
KugGouRadioWidget
insert kugou radio widget
kugouListWidget
insert kugou list widget
VideoWidget
insert video widget
kugouLiveWidget
insert kugou live widget
LrcWidget
insert lrc display widget
SearchWidget
insert search display widget
SearchSingleWidget
insert search single display widget
SimilarWidget
insert similar found widget
AlbumWidget
insert album found widget
ArtistWidget
insert artist found widget
ArtistCategoryWidget
insert artist category found widget
ToplistWidget
insert toplist found widget
PlaylistWidget
insert playlist found widget
AdvancedSearchWidget
insert advanced search widget
RecommendWidget
insert recommend found widget
IndentifyWidget
insert indentify songs widget
KuiSheWidget
insert kugou kuishe widget
WebDJRadioWidget
insert web dj radio widget
WebMVRadioWidget
insert web mv radio widget
CloudManagerWidget
insert cloud manager widget
ScreenSaverWidget
insert screen saver widget
Definition at line 46 of file musicrightareawidget.h.
Constructor & Destructor Documentation
MusicRightAreaWidget::MusicRightAreaWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 35 of file musicrightareawidget.cpp.
References applySettingParameter(), KugGouSongWidget, m_downloadStatusObject, m_funcIndex, m_instance, m_lowPowerMode, m_lrcAnalysis, m_musicLrcForDesktop, m_musicLrcForInterior, m_musicLrcForWallpaper, m_settingWidget, m_stackedAutoWidget, m_stackedFuncWidget, m_videoPlayerWidget, MUSIC_LRC_INTERIOR_MAX_LINE, and MusicLrcAnalysis::setLineMax().
MusicRightAreaWidget::~MusicRightAreaWidget ()
Definition at line 56 of file musicrightareawidget.cpp.
References m_downloadStatusObject, m_lrcAnalysis, m_musicLrcForDesktop, m_musicLrcForWallpaper, m_settingWidget, and m_videoPlayerWidget.
Member Function Documentation
void MusicRightAreaWidget::applySettingParameter ()
Apply settings parameters.
Definition at line 329 of file musicrightareawidget.cpp.
References MusicLrcContainerForWallpaper::applySettingParameter(), MusicLrcContainerForInterior::applySettingParameter(), MusicLrcContainerForDesktop::applySettingParameter(), functionClicked(), G_SETTING_PTR, KugGouRadioWidget, KugGouSongWidget, kugouListWidget, kugouLiveWidget, KuiSheWidget, m_funcIndex, m_lowPowerMode, m_musicLrcForDesktop, m_musicLrcForInterior, m_musicLrcForWallpaper, m_stackedFuncWidget, m_ui, MusicSettingManager::RippleLowPowerMode, MusicSettingManager::ShowDesktopLrc, MusicSettingManager::ShowInteriorLrc, and TTKObject_cast.
Referenced by MusicApplication::applySettingParameter(), MusicRightAreaWidget(), and MusicApplication::readSystemConfigFromFile().
void MusicRightAreaWidget::checkLrcValid () const
Check the current song already has lrc or not, if not just download it.
Definition at line 237 of file musicrightareawidget.cpp.
References MusicDownloadStatusModule::checkLrcValid(), and m_downloadStatusObject.
Referenced by MusicApplication::musicCurrentLrcUpdated(), and MusicApplication::showCurrentSong().
bool MusicRightAreaWidget::checkSettingParameterValue () const
Check the setting has open interior or desktop lrc on or not.
Definition at line 156 of file musicrightareawidget.cpp.
References G_SETTING_PTR, MusicSettingManager::ShowDesktopLrc, and MusicSettingManager::ShowInteriorLrc.
Referenced by loadCurrentSongLrc(), startDrawLrc(), and stopDrawLrc().
void MusicRightAreaWidget::createkWindow (int type) protected
Create kugou window.
Definition at line 900 of file musicrightareawidget.cpp.
References G_SETTING_PTR, m_stackedFuncWidget, m_ui, MusicUIObject::MQSSBackgroundStyle17, MusicSettingManager::RippleLowPowerMode, and TTKStatic_cast.
Referenced by functionClicked().
void MusicRightAreaWidget::deleteStackedFuncWidget () slot
Delete current stacked widget.
Definition at line 682 of file musicrightareawidget.cpp.
References m_stackedFuncWidget.
Referenced by functionParameterInit().
bool MusicRightAreaWidget::destopLrcVisible () const
Get destop lrc visible state.
Definition at line 141 of file musicrightareawidget.cpp.
References m_musicLrcForDesktop.
Referenced by MusicApplication::writeSystemConfigToFile().
void MusicRightAreaWidget::functionClicked (int index, QWidget * widget = nullptr) slot
Function button clicked.
Definition at line 360 of file musicrightareawidget.cpp.
References AdvancedSearchWidget, AlbumWidget, ArtistCategoryWidget, ArtistWidget, createkWindow(), functionParameterInit(), IndentifyWidget, MusicWebDJRadioWidget::initialize(), KugGouRadioWidget, KugGouSongWidget, QKugouWindow::KuGouList, kugouListWidget, kugouLiveWidget, QKugouWindow::KugouMovie, QKugouWindow::KuGouRadio, QKugouWindow::KuGouSingle, QKugouWindow::KuGouSong, KuiSheWidget, LrcWidget, m_funcIndex, m_stackedAutoWidget, m_stackedFuncWidget, m_ui, m_videoPlayerWidget, MusicUIObject::MQSSBackgroundStyle17, MusicUIObject::MQSSTinyBtnLrcCollapse, musicVideoFullscreen(), musicVideoSetPopup(), PlaylistWidget, MusicToastLabel::popup(), MusicVideoPlayWidget::popupMode(), MusicIdentifySongsWidget::queryIdentifyKey(), RecommendWidget, ScreenSaverWidget, SearchSingleWidget, SearchWidget, MusicWebMVRadioQueryWidget::setSongName(), SimilarWidget, ToplistWidget, TTKStatic_cast, updateBackgroundTheme(), updateBackgroundThemeDownload(), VideoWidget, WebDJRadioWidget, and WebMVRadioWidget.
Referenced by applySettingParameter(), MusicEnhancedPopWidget::helpButtonClicked(), MusicToolSetsWidget::itemHasClicked(), musicAdvancedSearch(), musicAlbumFound(), musicArtistCategoryFound(), musicArtistFound(), musicLoadSongIndexWidget(), musicMovieSearchRadioFound(), musicPlaylistFound(), musicRecommendFound(), musicSimilarFound(), musicSingleSearchedFound(), musicSongCommentsWidget(), musicSongSearchedFound(), musicToplistFound(), musicVideoButtonSearched(), musicVideoClosed(), musicVideoSetPopup(), MusicWebRadioView::openDJRadioWindow(), MusicWebRadioView::openMVRadioWindow(), setupUi(), and MusicCloudSharedSongWidget::showMainWindow().
void MusicRightAreaWidget::functionParameterInit () protected
Function parameter init.
lrc option
Definition at line 872 of file musicrightareawidget.cpp.
References deleteStackedFuncWidget(), G_SETTING_PTR, MusicApplication::instance(), MusicLrcContainerForInterior::lrcDisplayExpand(), LrcWidget, m_funcIndex, m_musicLrcForInterior, m_stackedAutoWidget, m_ui, musicLrcDisplayAllButtonClicked(), MusicApplication::musicWindowConciseChanged(), and MusicSettingManager::WindowConciseMode.
Referenced by functionClicked(), and researchQueryByQuality().
MusicRightAreaWidget * MusicRightAreaWidget::instance () static
Get class object instance.
Definition at line 71 of file musicrightareawidget.cpp.
References m_instance.
Referenced by MusicSongSearchTableWidget::actionGroupClick(), MusicArtistListQueryWidget::currentArtistListClicked(), MusicArtistMvsQueryWidget::currentItemClicked(), MusicArtistSimilarQueryWidget::currentItemClicked(), MusicArtistAlbumsQueryWidget::currentItemClicked(), MusicMoreFunctionsPopWidget::functionClicked(), MusicEnhancedPopWidget::helpButtonClicked(), MusicWebMVRadioInfoTableWidget::itemCellClicked(), MusicQualityChoicePopWidget::itemCellClicked(), MusicToolSetsWidget::itemHasClicked(), MusicBottomAreaWidget::lrcWidgetShowFullScreen(), MusicItemQueryTableWidget::menuActionChanged(), MusicSplitItemClickedLabel::mousePressEvent(), MusicAbstractSongsListTableWidget::musicAlbumQueryWidget(), MusicLrcFloatWidget::musicContainerForWallpaperClicked(), MusicApplication::musicCreateRightMenu(), MusicAbstractSongsListTableWidget::musicPlayedSimilarQueryWidget(), MusicSongsListTableWidget::musicSearchQuery(), MusicAbstractSongsListTableWidget::musicSimilarQueryWidget(), MusicLrcContainerForInterior::musicSongMovieClicked(), MusicAbstractSongsListTableWidget::musicSongMovieFound(), MusicAbstractSongsListTableWidget::musicSongPlayedMovieFound(), MusicSongSearchOnlineWidget::MusicSongSearchOnlineWidget(), MusicWebRadioView::openDJRadioWindow(), MusicWebRadioView::openMVRadioWindow(), MusicAdvancedSearchedWidget::searchButtonClicked(), MusicSystemTrayMenu::setWindowLockedChanged(), MusicSystemTrayMenu::showDesktopLrc(), MusicCloudSharedSongWidget::showMainWindow(), and MusicLeftAreaWidget::switchToSelectedItemStyle().
bool MusicRightAreaWidget::interiorLrcVisible () const
Get interior lrc visible state.
Definition at line 151 of file musicrightareawidget.cpp.
References m_musicLrcForInterior.
void MusicRightAreaWidget::loadCurrentSongLrc (const QString & name, const QString & path) const
Load current song lrc by name and path.
Definition at line 190 of file musicrightareawidget.cpp.
References checkSettingParameterValue(), MusicLrcAnalysis::Failed, KRC_FILE_PREFIX, m_lrcAnalysis, m_musicLrcForDesktop, m_musicLrcForInterior, m_musicLrcForWallpaper, MusicLrcAnalysis::readFromKrcFile(), MusicLrcAnalysis::readFromLrcFile(), MusicLrcContainer::setCurrentSongName(), MusicLrcContainerForWallpaper::start(), MusicLrcContainerForWallpaper::stopDrawLrc(), MusicLrcContainerForInterior::stopDrawLrc(), MusicLrcContainerForDesktop::stopDrawLrc(), TTK_LOGGER_INFO, MusicLrcContainerForInterior::updateCurrentLrc(), MusicLrcContainerForWallpaper::updateCurrentLrc(), and MusicLrcContainerForDesktop::updateCurrentLrc().
Referenced by MusicApplication::musicLoadCurrentSongLrc(), and MusicApplication::showCurrentSong().
void MusicRightAreaWidget::musicAdvancedSearch () slot
Music advanced search function.
Definition at line 656 of file musicrightareawidget.cpp.
References AdvancedSearchWidget, and functionClicked().
Referenced by MusicMoreFunctionsPopWidget::functionClicked().
void MusicRightAreaWidget::musicAlbumFound (const QString & text, const QString & id) slot
Music album function that by string.
Definition at line 588 of file musicrightareawidget.cpp.
References AlbumWidget, functionClicked(), m_stackedFuncWidget, MusicAlbumQueryWidget::setSongName(), MusicAlbumQueryWidget::setSongNameById(), and TTKStatic_cast.
Referenced by MusicSongSearchTableWidget::actionGroupClick(), MusicMoreFunctionsPopWidget::functionClicked(), MusicItemQueryTableWidget::menuActionChanged(), MusicAbstractSongsListTableWidget::musicAlbumQueryWidget(), musicAlbumSearchFound(), and MusicAdvancedSearchedWidget::searchButtonClicked().
void MusicRightAreaWidget::musicAlbumSearch (const QString & id)
Music album search function.
Definition at line 254 of file musicrightareawidget.cpp.
References m_rawData, MT_MS, and musicAlbumSearchFound().
Referenced by MusicArtistAlbumsQueryWidget::currentItemClicked().
void MusicRightAreaWidget::musicAlbumSearchFound () slot
Music album search function.
Definition at line 606 of file musicrightareawidget.cpp.
References m_rawData, and musicAlbumFound().
Referenced by musicAlbumSearch().
void MusicRightAreaWidget::musicArtistCategoryFound () slot
Music artist category function.
Definition at line 595 of file musicrightareawidget.cpp.
References ArtistCategoryWidget, functionClicked(), m_stackedFuncWidget, and TTKStatic_cast.
Referenced by MusicMoreFunctionsPopWidget::functionClicked().
void MusicRightAreaWidget::musicArtistFound (const QString & text, const QString & id) slot
Music artist function that by string.
Definition at line 630 of file musicrightareawidget.cpp.
References ArtistWidget, functionClicked(), m_stackedFuncWidget, MusicArtistQueryWidget::setSongName(), MusicArtistQueryWidget::setSongNameById(), and TTKStatic_cast.
Referenced by MusicSongSearchTableWidget::actionGroupClick(), MusicMoreFunctionsPopWidget::functionClicked(), MusicItemQueryTableWidget::menuActionChanged(), musicArtistSearchFound(), and MusicAdvancedSearchedWidget::searchButtonClicked().
void MusicRightAreaWidget::musicArtistSearch (const QString & id)
Music artist search function.
Definition at line 248 of file musicrightareawidget.cpp.
References m_rawData, MT_MS, and musicArtistSearchFound().
Referenced by MusicArtistListQueryWidget::currentArtistListClicked(), and MusicArtistSimilarQueryWidget::currentItemClicked().
void MusicRightAreaWidget::musicArtistSearchFound () slot
Music artist search function.
Definition at line 601 of file musicrightareawidget.cpp.
References m_rawData, and musicArtistFound().
Referenced by musicArtistSearch().
void MusicRightAreaWidget::musicChangeDownloadCustumWidget () slot
Change to download custum widget.
Definition at line 865 of file musicrightareawidget.cpp.
References MusicSettingWidget::changeDownloadWidget(), MusicSettingManager::DownloadLimitEnable, G_SETTING_PTR, m_settingWidget, and showSettingWidget().
void MusicRightAreaWidget::musicChangeDownloadFulllyWidget () slot
Change to download fully widget.
Definition at line 860 of file musicrightareawidget.cpp.
References MusicSettingManager::DownloadLimitEnable, and G_SETTING_PTR.
void MusicRightAreaWidget::musicContainerForWallpaperClicked () slot
Lrc desktop wallpaper button clicked.
Definition at line 834 of file musicrightareawidget.cpp.
References MusicLrcContainerForWallpaper::applySettingParameter(), MusicTopAreaWidget::instance(), MusicApplication::instance(), m_lrcAnalysis, m_musicLrcForInterior, m_musicLrcForWallpaper, MusicTopAreaWidget::musicWallpaperRemote(), and MusicLrcContainerForWallpaper::setLrcAnalysisModel().
Referenced by MusicLrcFloatWidget::musicContainerForWallpaperClicked().
void MusicRightAreaWidget::musicLoadSongIndexWidget () slot
Music load song index widget.
To prevent concise state changed while function musicWindowConciseChanged first called
Definition at line 673 of file musicrightareawidget.cpp.
References functionClicked(), G_SETTING_PTR, KugGouSongWidget, and MusicSettingManager::WindowConciseMode.
void MusicRightAreaWidget::musicLrcDisplayAllButtonClicked () slot
Lrc display all button clicked.
Definition at line 817 of file musicrightareawidget.cpp.
References LEFT_SIDE_WIDTH_MIN, MusicLrcContainerForInterior::lrcDisplayExpand(), m_musicLrcForInterior, m_ui, MusicUIObject::MQSSTinyBtnLrcCollapse, MusicUIObject::MQSSTinyBtnLrcExpand, and MusicLrcContainerForInterior::setLrcDisplayExpand().
Referenced by functionParameterInit(), MusicBottomAreaWidget::lrcWidgetShowFullScreen(), setupUi(), and MusicLeftAreaWidget::switchToSelectedItemStyle().
void MusicRightAreaWidget::musicMovieRadioSearch (const QVariant & data)
Music movie radio search function.
Definition at line 266 of file musicrightareawidget.cpp.
References m_rawData, MT_MS, and musicMovieSearchRadioFound().
Referenced by MusicWebMVRadioInfoTableWidget::itemCellClicked().
void MusicRightAreaWidget::musicMovieSearch (const QString & id)
Music movie search function.
Definition at line 260 of file musicrightareawidget.cpp.
References m_rawData, MT_MS, and musicMovieSearchFound().
Referenced by MusicArtistMvsQueryWidget::currentItemClicked().
void MusicRightAreaWidget::musicMovieSearchFound () slot
Music movie search function.
Definition at line 611 of file musicrightareawidget.cpp.
References m_rawData, and musicVideoButtonSearched().
Referenced by musicMovieSearch().
void MusicRightAreaWidget::musicMovieSearchRadioFound () slot
Music movie search radio function.
Definition at line 616 of file musicrightareawidget.cpp.
References functionClicked(), MusicVideoPlayWidget::isPopupMode(), m_rawData, m_videoPlayerWidget, MusicVideoPlayWidget::videoResearchButtonSearched(), and VideoWidget.
Referenced by musicMovieRadioSearch().
void MusicRightAreaWidget::musicPlaylistFound (const QString & id) slot
Music playlist function.
Definition at line 643 of file musicrightareawidget.cpp.
References functionClicked(), m_stackedFuncWidget, PlaylistWidget, MusicPlaylistQueryWidget::setSongName(), MusicPlaylistQueryWidget::setSongNameById(), and TTKStatic_cast.
Referenced by MusicMoreFunctionsPopWidget::functionClicked(), and MusicAdvancedSearchedWidget::searchButtonClicked().
void MusicRightAreaWidget::musicRecommendFound () slot
Music recommend function.
Definition at line 650 of file musicrightareawidget.cpp.
References functionClicked(), m_stackedFuncWidget, RecommendWidget, and TTKStatic_cast.
Referenced by MusicMoreFunctionsPopWidget::functionClicked().
void MusicRightAreaWidget::musicSimilarFound (const QString & text) slot
Music similar function that by string.
Definition at line 582 of file musicrightareawidget.cpp.
References functionClicked(), m_stackedFuncWidget, SimilarWidget, and TTKStatic_cast.
Referenced by MusicMoreFunctionsPopWidget::functionClicked(), MusicAbstractSongsListTableWidget::musicPlayedSimilarQueryWidget(), and MusicAbstractSongsListTableWidget::musicSimilarQueryWidget().
void MusicRightAreaWidget::musicSingleSearchedFound (const QString & id) slot
Music song search by given id.
Definition at line 667 of file musicrightareawidget.cpp.
References functionClicked(), m_ui, and SearchSingleWidget.
Referenced by MusicAdvancedSearchedWidget::searchButtonClicked().
void MusicRightAreaWidget::musicSongCommentsWidget () slot
Music song comments widget.
Definition at line 567 of file musicrightareawidget.cpp.
References APP_WINDOW_INDEX_1, functionClicked(), G_SETTING_PTR, MusicApplication::instance(), LrcWidget, m_musicLrcForInterior, m_ui, MusicApplication::musicWindowConciseChanged(), MusicLrcContainerForInterior::showSongCommentsWidget(), and MusicSettingManager::WindowConciseMode.
Referenced by MusicMoreFunctionsPopWidget::functionClicked().
void MusicRightAreaWidget::musicSongSearchedFound (const QString & text) slot
Music song research button searched by name.
Definition at line 661 of file musicrightareawidget.cpp.
References functionClicked(), m_ui, and SearchWidget.
Referenced by MusicItemQueryTableWidget::menuActionChanged(), MusicSplitItemClickedLabel::mousePressEvent(), MusicSongsListTableWidget::musicSearchQuery(), and setupUi().
void MusicRightAreaWidget::musicToplistFound () slot
Music toplist function.
Definition at line 637 of file musicrightareawidget.cpp.
References functionClicked(), m_stackedFuncWidget, ToplistWidget, and TTKStatic_cast.
Referenced by MusicMoreFunctionsPopWidget::functionClicked().
void MusicRightAreaWidget::musicVideoActiveWindow () slot
Set video widget actived window.
Definition at line 788 of file musicrightareawidget.cpp.
References MusicApplication::instance(), and m_videoPlayerWidget.
Referenced by musicVideoSetPopup().
void MusicRightAreaWidget::musicVideoButtonSearched (const QString & name, const QString & id) slot
Video button clicked by name to search.
Definition at line 750 of file musicrightareawidget.cpp.
References functionClicked(), MusicVideoPlayWidget::isPopupMode(), m_videoPlayerWidget, MusicVideoPlayWidget::startSearchSingleQuery(), MusicVideoPlayWidget::videoResearchButtonSearched(), and VideoWidget.
Referenced by musicMovieSearchFound(), MusicLrcContainerForInterior::musicSongMovieClicked(), MusicAbstractSongsListTableWidget::musicSongMovieFound(), MusicAbstractSongsListTableWidget::musicSongPlayedMovieFound(), and MusicAdvancedSearchedWidget::searchButtonClicked().
void MusicRightAreaWidget::musicVideoClosed () slot
Set video widget close and delete.
Definition at line 797 of file musicrightareawidget.cpp.
References functionClicked(), KugGouSongWidget, m_ui, and m_videoPlayerWidget.
void MusicRightAreaWidget::musicVideoFullscreen (bool full) slot
Set video widget fullScreen or not.
Definition at line 806 of file musicrightareawidget.cpp.
References MusicAbstractMoveWidget::blockMoveOption(), m_videoPlayerWidget, and MusicVideoPlayWidget::resizeWindow().
Referenced by functionClicked().
void MusicRightAreaWidget::musicVideoSetPopup (bool popup) slot
Set video widget popop or not.
Definition at line 764 of file musicrightareawidget.cpp.
References functionClicked(), m_stackedFuncWidget, m_ui, m_videoPlayerWidget, MT_MS, musicVideoActiveWindow(), MusicVideoPlayWidget::popupMode(), and VideoWidget.
Referenced by functionClicked().
void MusicRightAreaWidget::researchQueryByQuality (const QString & quality) slot
Research query by quality it changed.
Definition at line 734 of file musicrightareawidget.cpp.
References APP_WINDOW_INDEX_0, functionParameterInit(), m_funcIndex, m_ui, SearchWidget, and updateBackgroundTheme().
Referenced by MusicQualityChoicePopWidget::itemCellClicked().
void MusicRightAreaWidget::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 272 of file musicrightareawidget.cpp.
References MusicVideoPlayWidget::isPopupMode(), m_musicLrcForInterior, m_stackedAutoWidget, m_stackedFuncWidget, m_ui, m_videoPlayerWidget, MusicVideoPlayWidget::resizeWindow(), MusicLrcContainerForInterior::resizeWindow(), and TTKObject_cast.
Referenced by MusicApplication::resizeEvent().
void MusicRightAreaWidget::setCurrentPlayStatus (bool status) const
Set current play state button.
Definition at line 136 of file musicrightareawidget.cpp.
References m_musicLrcForDesktop, and MusicLrcContainerForDesktop::setCurrentPlayStatus().
Referenced by MusicApplication::musicStatePlay(), MusicApplication::readSystemConfigFromFile(), and MusicApplication::showCurrentSong().
void MusicRightAreaWidget::setDestopLrcVisible (bool visible) const slot
Set destop lrc visible or invisible.
Definition at line 688 of file musicrightareawidget.cpp.
References G_SETTING_PTR, MusicLrcContainerForDesktop::initCurrentLrc(), m_musicLrcForDesktop, m_ui, and MusicSettingManager::ShowDesktopLrc.
Referenced by MusicApplication::readSystemConfigFromFile(), and MusicSystemTrayMenu::showDesktopLrc().
void MusicRightAreaWidget::setInteriorLrcVisible (bool status) const
Set interior lrc visible by string.
Definition at line 146 of file musicrightareawidget.cpp.
References m_musicLrcForInterior.
Referenced by MusicApplication::readSystemConfigFromFile().
void MusicRightAreaWidget::setSongSpeedAndSlow (qint64 time) const
Set song speed and slow by given time.
Definition at line 232 of file musicrightareawidget.cpp.
References m_musicLrcForInterior, and MusicLrcContainerForInterior::setSongSpeedChanged().
Referenced by MusicApplication::musicPlayAnyTimeAt(), and MusicApplication::resetCurrentSongLrcIndex().
void MusicRightAreaWidget::setupUi (Ui::MusicApplication * ui)
Set up app ui.
Definition at line 76 of file musicrightareawidget.cpp.
References functionClicked(), IndentifyWidget, MusicLrcContainerForInterior::initFunctionLabel(), MusicApplication::instance(), m_lrcAnalysis, m_musicLrcForInterior, m_settingWidget, m_ui, MusicUIObject::MQSSBtnBackBack, MusicUIObject::MQSSBtnBackFresh, musicLrcDisplayAllButtonClicked(), musicSongSearchedFound(), SearchWidget, MusicLrcContainer::setLrcAnalysisModel(), and updateBackgroundThemeDownload().
Referenced by MusicApplication::MusicApplication().
void MusicRightAreaWidget::setWindowLockedChanged () slot
Lock current desktop lrc state changed.
Definition at line 696 of file musicrightareawidget.cpp.
References m_musicLrcForDesktop, and MusicLrcContainerForDesktop::setWindowLockedChanged().
Referenced by MusicSystemTrayMenu::setWindowLockedChanged().
void MusicRightAreaWidget::setWindowLrcTypeChanged () slot
Set current desktop lrc window type changed.
Definition at line 701 of file musicrightareawidget.cpp.
References MusicLrcContainerForDesktop::applySettingParameter(), MusicSettingManager::DLrcGeometry, MusicSettingManager::DLrcWindowMode, G_SETTING_PTR, MusicLrcContainerForDesktop::initCurrentLrc(), MusicApplication::instance(), MusicLrcContainerForDesktop::isVerticalWindowType(), m_lrcAnalysis, m_musicLrcForDesktop, m_settingWidget, MusicLrcContainerForDesktop::makeStatusCopy(), MusicLrcContainer::setLrcAnalysisModel(), MusicSettingManager::ShowDesktopLrc, and TTKStatic_cast.
Referenced by MusicApplication::readSystemConfigFromFile().
void MusicRightAreaWidget::showSettingWidget () const
Show setting widget.
Definition at line 242 of file musicrightareawidget.cpp.
References MusicSettingWidget::exec(), MusicSettingWidget::initControllerParameter(), and m_settingWidget.
Referenced by musicChangeDownloadCustumWidget(), and MusicApplication::musicSetting().
void MusicRightAreaWidget::startDrawLrc () const
Start timer clock to draw lrc.
Definition at line 110 of file musicrightareawidget.cpp.
References checkSettingParameterValue(), m_musicLrcForDesktop, m_musicLrcForInterior, m_musicLrcForWallpaper, MusicLrcContainerForWallpaper::startDrawLrc(), MusicLrcContainerForInterior::startDrawLrc(), and MusicLrcContainerForDesktop::startDrawLrc().
Referenced by MusicApplication::musicStatePlay().
void MusicRightAreaWidget::stopDrawLrc () const
Stop timer clock to draw lrc.
Definition at line 123 of file musicrightareawidget.cpp.
References checkSettingParameterValue(), m_musicLrcForDesktop, m_musicLrcForInterior, m_musicLrcForWallpaper, MusicLrcContainerForWallpaper::stopDrawLrc(), MusicLrcContainerForInterior::stopDrawLrc(), and MusicLrcContainerForDesktop::stopDrawLrc().
Referenced by MusicApplication::musicStatePlay(), and MusicApplication::showCurrentSong().
void MusicRightAreaWidget::updateBackgroundTheme () signal
Current background transparent changed.
Referenced by functionClicked(), and researchQueryByQuality().
void MusicRightAreaWidget::updateBackgroundThemeDownload () signal
Current background skin download.
Referenced by functionClicked(), and setupUi().
void MusicRightAreaWidget::updateCurrentLrc (qint64 current, qint64 total, bool playStatus) const
Update current lrc by current time time and play state.
Definition at line 161 of file musicrightareawidget.cpp.
References MusicLrcAnalysis::findText(), m_lrcAnalysis, m_musicLrcForDesktop, m_musicLrcForInterior, m_musicLrcForWallpaper, MusicLrcContainer::setCurrentTime(), MusicLrcContainerForInterior::text(), MusicLrcContainerForInterior::updateCurrentLrc(), MusicLrcContainerForWallpaper::updateCurrentLrc(), and MusicLrcContainerForDesktop::updateCurrentLrc().
Referenced by MusicApplication::positionChanged().
Member Data Documentation
MusicDownloadStatusModule* MusicRightAreaWidget::m_downloadStatusObject protected
Definition at line 319 of file musicrightareawidget.h.
Referenced by checkLrcValid(), MusicRightAreaWidget(), and ~MusicRightAreaWidget().
MusicFunction MusicRightAreaWidget::m_funcIndex protected
Definition at line 309 of file musicrightareawidget.h.
Referenced by applySettingParameter(), functionClicked(), functionParameterInit(), MusicRightAreaWidget(), and researchQueryByQuality().
MusicRightAreaWidget * MusicRightAreaWidget::m_instance = nullptr static protected
Definition at line 321 of file musicrightareawidget.h.
Referenced by instance(), and MusicRightAreaWidget().
bool MusicRightAreaWidget::m_lowPowerMode protected
Definition at line 308 of file musicrightareawidget.h.
Referenced by applySettingParameter(), and MusicRightAreaWidget().
MusicLrcAnalysis* MusicRightAreaWidget::m_lrcAnalysis protected
Definition at line 315 of file musicrightareawidget.h.
Referenced by loadCurrentSongLrc(), musicContainerForWallpaperClicked(), MusicRightAreaWidget(), setupUi(), setWindowLrcTypeChanged(), updateCurrentLrc(), and ~MusicRightAreaWidget().
MusicLrcContainerForDesktop* MusicRightAreaWidget::m_musicLrcForDesktop protected
Definition at line 317 of file musicrightareawidget.h.
Referenced by applySettingParameter(), destopLrcVisible(), loadCurrentSongLrc(), MusicRightAreaWidget(), setCurrentPlayStatus(), setDestopLrcVisible(), setWindowLockedChanged(), setWindowLrcTypeChanged(), startDrawLrc(), stopDrawLrc(), updateCurrentLrc(), and ~MusicRightAreaWidget().
MusicLrcContainerForInterior* MusicRightAreaWidget::m_musicLrcForInterior protected
Definition at line 316 of file musicrightareawidget.h.
Referenced by applySettingParameter(), functionParameterInit(), interiorLrcVisible(), loadCurrentSongLrc(), musicContainerForWallpaperClicked(), musicLrcDisplayAllButtonClicked(), MusicRightAreaWidget(), musicSongCommentsWidget(), resizeWindow(), setInteriorLrcVisible(), setSongSpeedAndSlow(), setupUi(), startDrawLrc(), stopDrawLrc(), and updateCurrentLrc().
MusicLrcContainerForWallpaper* MusicRightAreaWidget::m_musicLrcForWallpaper protected
Definition at line 318 of file musicrightareawidget.h.
Referenced by applySettingParameter(), loadCurrentSongLrc(), musicContainerForWallpaperClicked(), MusicRightAreaWidget(), startDrawLrc(), stopDrawLrc(), updateCurrentLrc(), and ~MusicRightAreaWidget().
QVariant MusicRightAreaWidget::m_rawData protected
Definition at line 307 of file musicrightareawidget.h.
Referenced by musicAlbumSearch(), musicAlbumSearchFound(), musicArtistSearch(), musicArtistSearchFound(), musicMovieRadioSearch(), musicMovieSearch(), musicMovieSearchFound(), and musicMovieSearchRadioFound().
MusicSettingWidget* MusicRightAreaWidget::m_settingWidget protected
Definition at line 312 of file musicrightareawidget.h.
Referenced by musicChangeDownloadCustumWidget(), MusicRightAreaWidget(), setupUi(), setWindowLrcTypeChanged(), showSettingWidget(), and ~MusicRightAreaWidget().
QWidget * MusicRightAreaWidget::m_stackedAutoWidget protected
Definition at line 310 of file musicrightareawidget.h.
Referenced by functionClicked(), functionParameterInit(), MusicRightAreaWidget(), and resizeWindow().
QWidget* MusicRightAreaWidget::m_stackedFuncWidget protected
Definition at line 310 of file musicrightareawidget.h.
Referenced by applySettingParameter(), createkWindow(), deleteStackedFuncWidget(), functionClicked(), musicAlbumFound(), musicArtistCategoryFound(), musicArtistFound(), musicPlaylistFound(), musicRecommendFound(), MusicRightAreaWidget(), musicSimilarFound(), musicToplistFound(), musicVideoSetPopup(), and resizeWindow().
Ui::MusicApplication* MusicRightAreaWidget::m_ui protected
Definition at line 311 of file musicrightareawidget.h.
Referenced by applySettingParameter(), createkWindow(), functionClicked(), functionParameterInit(), musicLrcDisplayAllButtonClicked(), musicSingleSearchedFound(), musicSongCommentsWidget(), musicSongSearchedFound(), musicVideoClosed(), musicVideoSetPopup(), researchQueryByQuality(), resizeWindow(), setDestopLrcVisible(), and setupUi().
MusicVideoPlayWidget* MusicRightAreaWidget::m_videoPlayerWidget protected
Definition at line 313 of file musicrightareawidget.h.
Referenced by functionClicked(), musicMovieSearchRadioFound(), MusicRightAreaWidget(), musicVideoActiveWindow(), musicVideoButtonSearched(), musicVideoClosed(), musicVideoFullscreen(), musicVideoSetPopup(), resizeWindow(), and ~MusicRightAreaWidget().
The documentation for this class was generated from the following files:
TTKModule/musicrightareawidget.h
TTKModule/musicrightareawidget.cpp