TTKMusicplayer: QxtGlobalShortcutPrivate Class Reference
QxtGlobalShortcutPrivate Class Reference
The namespace of the qxt global shortcut private.
#include <qxtglobalshortcut_p.h>
Public Member Functions
QxtGlobalShortcutPrivate ()
~QxtGlobalShortcutPrivate ()
bool setShortcut (const QKeySequence &shortcut)
bool unsetShortcut ()
Public Member Functions inherited from QxtPrivate< QxtGlobalShortcut >
virtual ~QxtPrivate ()
void QXT_setPublic (QxtGlobalShortcut *pub)
Static Public Member Functions
static bool eventFilter (void *message)
Public Attributes
bool enabled
Qt::Key key
Qt::KeyboardModifiers mods
Static Public Attributes
static bool error = false
static int ref = 0
static QAbstractEventDispatcher::EventFilter prevEventFilter = 0
Static Private Member Functions
static quint32 nativeKeycode (Qt::Key keycode)
static quint32 nativeModifiers (Qt::KeyboardModifiers modifiers)
static bool registerShortcut (quint32 nativeKey, quint32 nativeMods)
static bool unregisterShortcut (quint32 nativeKey, quint32 nativeMods)
static void activateShortcut (quint32 nativeKey, quint32 nativeMods)
Static Private Attributes
static QHash< QPair< quint32, quint32 >, QxtGlobalShortcut * > shortcuts
Additional Inherited Members
Protected Member Functions inherited from QxtPrivate< QxtGlobalShortcut >
QxtGlobalShortcut & qxt_p ()
const QxtGlobalShortcut & qxt_p () const
Detailed Description
The namespace of the qxt global shortcut private.
Author
libqxt found.nosp@m.atio.nosp@m.n@lib.nosp@m.qxt..nosp@m.org
Definition at line 47 of file qxtglobalshortcut_p.h.
Constructor & Destructor Documentation
QxtGlobalShortcutPrivate::QxtGlobalShortcutPrivate ()
Definition at line 39 of file qxtglobalshortcut.cpp.
References eventFilter(), prevEventFilter, and ref.
QxtGlobalShortcutPrivate::~QxtGlobalShortcutPrivate ()
Definition at line 50 of file qxtglobalshortcut.cpp.
References prevEventFilter, and ref.
Member Function Documentation
void QxtGlobalShortcutPrivate::activateShortcut (quint32 nativeKey, quint32 nativeMods) static private
Definition at line 88 of file qxtglobalshortcut.cpp.
References QxtGlobalShortcut::activated(), QxtGlobalShortcut::isEnabled(), and shortcuts.
Referenced by eventFilter().
bool QxtGlobalShortcutPrivate::eventFilter (void * message) static
Definition at line 46 of file qxtglobalshortcut_mac.cpp.
References activateShortcut(), and keyIDs.
Referenced by QxtGlobalShortcutPrivate().
quint32 QxtGlobalShortcutPrivate::nativeKeycode (Qt::Key keycode) static private
Definition at line 89 of file qxtglobalshortcut_mac.cpp.
References key.
Referenced by setShortcut(), and unsetShortcut().
quint32 QxtGlobalShortcutPrivate::nativeModifiers (Qt::KeyboardModifiers modifiers) static private
Definition at line 73 of file qxtglobalshortcut_mac.cpp.
Referenced by setShortcut(), and unsetShortcut().
bool QxtGlobalShortcutPrivate::registerShortcut (quint32 nativeKey, quint32 nativeMods) static private
Definition at line 187 of file qxtglobalshortcut_mac.cpp.
References hotKeySerial, keyIDs, keyRefs, qxt_mac_handle_hot_key(), qxt_mac_handler_installed, and ref.
Referenced by setShortcut().
bool QxtGlobalShortcutPrivate::setShortcut (const QKeySequence & shortcut)
Definition at line 61 of file qxtglobalshortcut.cpp.
References key, mods, nativeKeycode(), nativeModifiers(), QxtPrivate< QxtGlobalShortcut >::qxt_p(), registerShortcut(), and shortcuts.
bool QxtGlobalShortcutPrivate::unregisterShortcut (quint32 nativeKey, quint32 nativeMods) static private
Definition at line 212 of file qxtglobalshortcut_mac.cpp.
References keyIDs, keyRefs, and ref.
Referenced by unsetShortcut().
bool QxtGlobalShortcutPrivate::unsetShortcut ()
Definition at line 75 of file qxtglobalshortcut.cpp.
References key, mods, nativeKeycode(), nativeModifiers(), shortcuts, and unregisterShortcut().
Member Data Documentation
bool QxtGlobalShortcutPrivate::enabled
Definition at line 57 of file qxtglobalshortcut_p.h.
bool QxtGlobalShortcutPrivate::error = false static
Definition at line 64 of file qxtglobalshortcut_p.h.
Referenced by qxt_x_errhandler().
Qt::Key QxtGlobalShortcutPrivate::key
Definition at line 58 of file qxtglobalshortcut_p.h.
Referenced by nativeKeycode(), setShortcut(), and unsetShortcut().
Qt::KeyboardModifiers QxtGlobalShortcutPrivate::mods
Definition at line 59 of file qxtglobalshortcut_p.h.
Referenced by setShortcut(), and unsetShortcut().
QAbstractEventDispatcher::EventFilter QxtGlobalShortcutPrivate::prevEventFilter = 0 static
Definition at line 67 of file qxtglobalshortcut_p.h.
Referenced by QxtGlobalShortcutPrivate(), and ~QxtGlobalShortcutPrivate().
int QxtGlobalShortcutPrivate::ref = 0 static
Definition at line 65 of file qxtglobalshortcut_p.h.
Referenced by QxtGlobalShortcutPrivate(), registerShortcut(), unregisterShortcut(), and ~QxtGlobalShortcutPrivate().
QHash< QPair< quint32, quint32 >, QxtGlobalShortcut * > QxtGlobalShortcutPrivate::shortcuts static private
Definition at line 80 of file qxtglobalshortcut_p.h.
Referenced by activateShortcut(), setShortcut(), and unsetShortcut().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut_p.h
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut.cpp
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut_mac.cpp
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut_win.cpp
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut_x11.cpp