TTKMusicplayer: MusicPagingRequest Class Reference
MusicPagingRequest Class Reference
The class to abstract download paing request.
#include <musicpagingrequest.h>
Public Member Functions
MusicPagingRequest (QObject *parent=nullptr)
virtual ~MusicPagingRequest ()
virtual void deleteAll () override
virtual void startToPage (int offset)
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Attributes
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
QVariantMap m_headerData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Detailed Description
The class to abstract download paing request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicpagingrequest.h.
Constructor & Destructor Documentation
MusicPagingRequest::MusicPagingRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicpagingrequest.cpp.
References MusicAbstractNetwork::m_manager, m_pageIndex, m_pageSize, m_pageTotal, and MusicAbstractNetwork::sslErrors().
MusicPagingRequest::~MusicPagingRequest () virtual
Definition at line 16 of file musicpagingrequest.cpp.
References deleteAll().
Member Function Documentation
void MusicPagingRequest::deleteAll () override virtual
Release the network object.
Reimplemented from MusicAbstractNetwork.
Definition at line 21 of file musicpagingrequest.cpp.
References MusicAbstractNetwork::m_reply.
Referenced by MusicMVRadioCategoryRequest::downLoadFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicBDDiscoverListRequest::downLoadFinished(), MusicBDQueryLearnRequest::downLoadFinished(), MusicBDSongSuggestRequest::downLoadFinished(), MusicKGSongSuggestRequest::downLoadFinished(), MusicKWArtistSimilarRequest::downLoadFinished(), MusicKGArtistSimilarRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWSongSuggestRequest::downLoadFinished(), MusicBDArtistSimilarRequest::downLoadFinished(), MusicQQArtistSimilarRequest::downLoadFinished(), MusicQQDiscoverListRequest::downLoadFinished(), MusicQQSongSuggestRequest::downLoadFinished(), MusicWYArtistSimilarRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicWYSongSuggestRequest::downLoadFinished(), MusicXMArtistSimilarRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicXMDiscoverListRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMSongSuggestRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicBDSongCommentsRequest::downLoadFinished(), MusicKGSongCommentsRequest::downLoadFinished(), MusicQQSongCommentsRequest::downLoadFinished(), MusicKWQueryArtistListRequest::downLoadFinished(), MusicXMQueryArtistListRequest::downLoadFinished(), MusicKGQueryArtistListRequest::downLoadFinished(), MusicQQQueryArtistListRequest::downLoadFinished(), MusicBDQueryArtistListRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicWYQueryArtistListRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicXMSongCommentsRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicWYQueryMovieRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryMovieRequest::downLoadFinished(), MusicBDQueryMovieRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::downLoadFinished(), MusicXMQueryPlaylistRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), MusicQQPlaylistCommentsRequest::downLoadFinished(), MusicBDPlaylistCommentsRequest::downLoadFinished(), MusicWYPlaylistCommentsRequest::downLoadFinished(), MusicXMPlaylistCommentsRequest::downLoadFinished(), MusicKWQueryMovieRequest::pageDownLoadFinished(), MusicKGQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryMovieRequest::pageDownLoadFinished(), MusicWYQueryMovieRequest::pageDownLoadFinished(), MusicXMQueryMovieRequest::pageDownLoadFinished(), MusicBDQueryMovieRequest::pageDownLoadFinished(), MusicKGQueryAlbumRequest::singleDownLoadFinished(), MusicWYQueryAlbumRequest::singleDownLoadFinished(), MusicKWQueryAlbumRequest::singleDownLoadFinished(), MusicXMQueryAlbumRequest::singleDownLoadFinished(), MusicBDQueryAlbumRequest::singleDownLoadFinished(), MusicQQQueryAlbumRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicXMQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicBDQueryRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::singleDownLoadFinished(), MusicXMQueryMovieRequest::singleDownLoadFinished(), MusicBDQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), MusicXMQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicBDQueryArtistListRequest::startToPage(), MusicQQQueryArtistListRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicBDSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicXMQueryPlaylistRequest::startToPage(), MusicBDQueryMovieRequest::startToPage(), MusicXMQueryMovieRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicXMQueryRequest::startToPage(), MusicBDQueryPlaylistRequest::startToPage(), MusicXMSongCommentsRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicBDQueryRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicBDPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicXMPlaylistCommentsRequest::startToPage(), MusicAbstractMVRadioRequest::startToSearch(), MusicQQArtistSimilarRequest::startToSearch(), MusicBDSongSuggestRequest::startToSearch(), MusicKGArtistSimilarRequest::startToSearch(), MusicKWSongSuggestRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicBDQueryLearnRequest::startToSearch(), MusicQQDiscoverListRequest::startToSearch(), MusicBDArtistSimilarRequest::startToSearch(), MusicQQSongSuggestRequest::startToSearch(), MusicBDDiscoverListRequest::startToSearch(), MusicKWArtistSimilarRequest::startToSearch(), MusicKGSongSuggestRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicXMArtistSimilarRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSearch(), MusicWYSongSuggestRequest::startToSearch(), MusicXMQueryMovieRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicXMSongSuggestRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicBDQueryRecommendRequest::startToSearch(), MusicKGQueryArtistRequest::startToSearch(), MusicBDQueryArtistRequest::startToSearch(), MusicBDQueryAlbumRequest::startToSearch(), MusicXMDiscoverListRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicXMQueryRecommendRequest::startToSearch(), MusicBDQueryMovieRequest::startToSearch(), MusicXMQueryArtistRequest::startToSearch(), MusicKGQueryAlbumRequest::startToSearch(), MusicXMQueryAlbumRequest::startToSearch(), MusicWYArtistSimilarRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicBDQueryToplistRequest::startToSearch(), MusicKGQueryToplistRequest::startToSearch(), MusicXMQueryToplistRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicQQQueryToplistRequest::startToSearch(), MusicKWQueryToplistRequest::startToSearch(), MusicQQQueryArtistRequest::startToSearch(), MusicBDQueryAlbumRequest::startToSingleSearch(), MusicBDQueryMovieRequest::startToSingleSearch(), MusicAbstractQueryRequest::~MusicAbstractQueryRequest(), and ~MusicPagingRequest().
int MusicPagingRequest::getPageIndex () const inline
Return the page index number.
Definition at line 59 of file musicpagingrequest.h.
Referenced by MusicItemSearchTableWidget::createFinishedItem(), and MusicItemSearchTableWidget::itemCellClicked().
int MusicPagingRequest::getPageSize () const inline
Return the each page max size.
Definition at line 51 of file musicpagingrequest.h.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicArtistMvsQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), MusicPlaylistQueryWidget::buttonClicked(), MusicArtistListQueryWidget::createArtistListItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicItemSearchTableWidget::createFinishedItem(), MusicCommentsWidget::createPagingWidget(), MusicPlaylistQueryWidget::createPlaylistItem(), and MusicWebDJRadioQueryWidget::createProgramItem().
int MusicPagingRequest::getPageTotal () const inline
Return the page total number.
Definition at line 55 of file musicpagingrequest.h.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicArtistMvsQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), MusicPlaylistQueryWidget::buttonClicked(), MusicArtistListQueryWidget::createArtistListItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicItemSearchTableWidget::createFinishedItem(), MusicCommentsWidget::createPagingWidget(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), and MusicCommentsWidget::setCurrentSongName().
void MusicPagingRequest::startToPage (int offset) virtual
Start to search data from name and type bt paging.
Reimplemented in MusicWYPlaylistCommentsRequest, MusicXMPlaylistCommentsRequest, MusicBDPlaylistCommentsRequest, MusicKGPlaylistCommentsRequest, MusicKWPlaylistCommentsRequest, MusicQQPlaylistCommentsRequest, MusicKWQueryRequest, MusicBDQueryMovieRequest, MusicBDQueryPlaylistRequest, MusicBDQueryRequest, MusicKGQueryPlaylistRequest, MusicKGQueryRequest, MusicKWQueryPlaylistRequest, MusicQQQueryPlaylistRequest, MusicQQQueryRequest, MusicWYSongCommentsRequest, MusicWYQueryMovieRequest, MusicWYQueryPlaylistRequest, MusicWYQueryRequest, MusicXMSongCommentsRequest, MusicXMQueryMovieRequest, MusicXMQueryPlaylistRequest, MusicXMQueryRequest, MusicDJRadioProgramCategoryRequest, MusicKGQueryMovieRequest, MusicKWQueryMovieRequest, MusicQQQueryMovieRequest, MusicBDSongCommentsRequest, MusicKGSongCommentsRequest, MusicKWSongCommentsRequest, MusicQQSongCommentsRequest, MusicWYQueryArtistListRequest, MusicBDQueryArtistListRequest, MusicKGQueryArtistListRequest, MusicKWQueryArtistListRequest, MusicQQQueryArtistListRequest, and MusicXMQueryArtistListRequest.
Definition at line 30 of file musicpagingrequest.cpp.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicArtistMvsQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), MusicPlaylistQueryWidget::buttonClicked(), MusicItemSearchTableWidget::itemCellClicked(), and MusicQueryMovieRequest::startToSearch().
Member Data Documentation
int MusicPagingRequest::m_pageIndex protected
Definition at line 62 of file musicpagingrequest.h.
Referenced by MusicPagingRequest(), MusicXMQueryRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicBDQueryRequest::startToPage(), and MusicKWQueryRequest::startToPage().
int MusicPagingRequest::m_pageSize protected
Definition at line 62 of file musicpagingrequest.h.
Referenced by MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicXMQueryPlaylistRequest::getPlaylistInfo(), MusicBDDiscoverListRequest::MusicBDDiscoverListRequest(), MusicBDPlaylistCommentsRequest::MusicBDPlaylistCommentsRequest(), MusicBDQueryArtistListRequest::MusicBDQueryArtistListRequest(), MusicBDQueryMovieRequest::MusicBDQueryMovieRequest(), MusicBDQueryPlaylistRequest::MusicBDQueryPlaylistRequest(), MusicBDQueryRequest::MusicBDQueryRequest(), MusicBDQueryToplistRequest::MusicBDQueryToplistRequest(), MusicBDSongCommentsRequest::MusicBDSongCommentsRequest(), MusicDJRadioProgramCategoryRequest::MusicDJRadioProgramCategoryRequest(), MusicKGPlaylistCommentsRequest::MusicKGPlaylistCommentsRequest(), MusicKGQueryArtistListRequest::MusicKGQueryArtistListRequest(), MusicKGQueryMovieRequest::MusicKGQueryMovieRequest(), MusicKGQueryPlaylistRequest::MusicKGQueryPlaylistRequest(), MusicKGQueryRequest::MusicKGQueryRequest(), MusicKGSongCommentsRequest::MusicKGSongCommentsRequest(), MusicKWPlaylistCommentsRequest::MusicKWPlaylistCommentsRequest(), MusicKWQueryArtistListRequest::MusicKWQueryArtistListRequest(), MusicKWQueryMovieRequest::MusicKWQueryMovieRequest(), MusicKWQueryPlaylistRequest::MusicKWQueryPlaylistRequest(), MusicKWQueryRequest::MusicKWQueryRequest(), MusicKWSongCommentsRequest::MusicKWSongCommentsRequest(), MusicPagingRequest(), MusicQQPlaylistCommentsRequest::MusicQQPlaylistCommentsRequest(), MusicQQQueryArtistListRequest::MusicQQQueryArtistListRequest(), MusicQQQueryMovieRequest::MusicQQQueryMovieRequest(), MusicQQQueryPlaylistRequest::MusicQQQueryPlaylistRequest(), MusicQQQueryRequest::MusicQQQueryRequest(), MusicQQSongCommentsRequest::MusicQQSongCommentsRequest(), MusicWYPlaylistCommentsRequest::MusicWYPlaylistCommentsRequest(), MusicWYQueryArtistListRequest::MusicWYQueryArtistListRequest(), MusicWYQueryMovieRequest::MusicWYQueryMovieRequest(), MusicWYQueryPlaylistRequest::MusicWYQueryPlaylistRequest(), MusicWYQueryRequest::MusicWYQueryRequest(), MusicWYSongCommentsRequest::MusicWYSongCommentsRequest(), MusicXMArtistSimilarRequest::MusicXMArtistSimilarRequest(), MusicXMPlaylistCommentsRequest::MusicXMPlaylistCommentsRequest(), MusicXMQueryArtistListRequest::MusicXMQueryArtistListRequest(), MusicXMQueryMovieRequest::MusicXMQueryMovieRequest(), MusicXMQueryPlaylistRequest::MusicXMQueryPlaylistRequest(), MusicXMQueryRequest::MusicXMQueryRequest(), MusicXMSongCommentsRequest::MusicXMSongCommentsRequest(), MusicXMQueryArtistListRequest::startToPage(), MusicBDQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicQQQueryArtistListRequest::startToPage(), MusicBDSongCommentsRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicXMQueryRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicXMSongCommentsRequest::startToPage(), MusicXMQueryPlaylistRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicBDQueryMovieRequest::startToPage(), MusicXMQueryMovieRequest::startToPage(), MusicBDQueryPlaylistRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicBDQueryRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicBDPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicXMPlaylistCommentsRequest::startToPage(), MusicBDDiscoverListRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicXMQueryMovieRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicXMArtistSimilarRequest::startToSearch(), MusicBDQueryMovieRequest::startToSearch(), MusicBDQueryToplistRequest::startToSearch(), and MusicXMQueryPlaylistRequest::startToSearch().
int MusicPagingRequest::m_pageTotal protected
Definition at line 62 of file musicpagingrequest.h.
Referenced by MusicBDSongCommentsRequest::downLoadFinished(), MusicQQSongCommentsRequest::downLoadFinished(), MusicKGSongCommentsRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicQQQueryArtistListRequest::downLoadFinished(), MusicBDQueryArtistListRequest::downLoadFinished(), MusicKWQueryArtistListRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicXMSongCommentsRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryPlaylistRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), MusicQQPlaylistCommentsRequest::downLoadFinished(), MusicBDPlaylistCommentsRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicWYPlaylistCommentsRequest::downLoadFinished(), MusicXMPlaylistCommentsRequest::downLoadFinished(), MusicWYQueryMovieRequest::getArtistMvsCount(), MusicKGQueryArtistListRequest::MusicKGQueryArtistListRequest(), MusicPagingRequest(), MusicWYQueryArtistListRequest::MusicWYQueryArtistListRequest(), MusicXMQueryArtistListRequest::MusicXMQueryArtistListRequest(), MusicKGQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryMovieRequest::pageDownLoadFinished(), MusicKWQueryMovieRequest::pageDownLoadFinished(), MusicXMQueryMovieRequest::pageDownLoadFinished(), MusicBDQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryArtistListRequest::startToPage(), MusicBDQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicBDSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicBDQueryMovieRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicBDQueryPlaylistRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicXMSongCommentsRequest::startToPage(), MusicXMQueryRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicBDQueryRequest::startToPage(), MusicXMQueryMovieRequest::startToPage(), MusicXMQueryPlaylistRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicBDPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicXMPlaylistCommentsRequest::startToPage(), and MusicWYPlaylistCommentsRequest::startToPage().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicpagingrequest.h
TTKModule/TTKCore/musicNetworkKits/musicpagingrequest.cpp