TTKMusicPlayer: MusicLabelQueryItemWidget Class Reference
MusicLabelQueryItemWidget Class Reference
The class of the label query item widget.
#include <musicqueryitemwidget.h>
Public Slots
void downloadFinished (const QByteArray &bytes)
void itemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Signals inherited from TTKClickedLabel
void clicked ()
Public Member Functions
MusicLabelQueryItemWidget (QWidget *parent=nullptr)
~MusicLabelQueryItemWidget ()
void setResultDataItem (const MusicResultDataItem &item)
Public Member Functions inherited from TTKClickedLabel
TTKClickedLabel (QWidget *parent=nullptr)
TTKClickedLabel (const QString &text, QWidget *parent=nullptr)
void setBlockOption (bool block) noexcept
Static Public Attributes
static constexpr int WIDTH_LABEL_SIZE = 60
static constexpr int HEIGHT_LABEL_SIZE = 105
static constexpr int LINE_SPACING_SIZE = 105
Private Attributes
MusicResultDataItem m_itemData
QLabel * m_iconLabel
QLabel * m_nameLabel
Additional Inherited Members
Protected Member Functions inherited from TTKClickedLabel
virtual void mousePressEvent (QMouseEvent *event) overridefinal
Protected Attributes inherited from TTKClickedLabel
bool m_blockOption
Detailed Description
The class of the label query item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 161 of file musicqueryitemwidget.h.
Constructor & Destructor Documentation
MusicLabelQueryItemWidget::MusicLabelQueryItemWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 220 of file musicqueryitemwidget.cpp.
References TTKClickedLabel::clicked(), HEIGHT_LABEL_SIZE, itemClicked(), m_iconLabel, m_nameLabel, TTK_DEFAULT_STR, and WIDTH_LABEL_SIZE.
MusicLabelQueryItemWidget::~MusicLabelQueryItemWidget ()
Object destructor.
Definition at line 236 of file musicqueryitemwidget.cpp.
References m_iconLabel, and m_nameLabel.
Member Function Documentation
void MusicLabelQueryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
Referenced by itemClicked().
void MusicLabelQueryItemWidget::downloadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 256 of file musicqueryitemwidget.cpp.
References m_iconLabel, TTK_ERROR_STREAM, and WIDTH_LABEL_SIZE.
Referenced by setResultDataItem().
void MusicLabelQueryItemWidget::itemClicked () slot
Current item clicked.
Definition at line 272 of file musicqueryitemwidget.cpp.
References currentItemClicked(), and m_itemData.
Referenced by MusicLabelQueryItemWidget().
void MusicLabelQueryItemWidget::setResultDataItem (const MusicResultDataItem & item)
Set media results item.
Definition at line 242 of file musicqueryitemwidget.cpp.
References downloadFinished(), TTK::Widget::elidedText(), TTK::isCoverValid(), MusicResultDataItem::m_coverUrl, m_itemData, MusicResultDataItem::m_name, m_nameLabel, MusicCoverRequest::startToRequest(), and WIDTH_LABEL_SIZE.
Referenced by MusicWebDJRadioCategoryWidget::createCategoryItems().
Member Data Documentation
constexpr int MusicLabelQueryItemWidget::HEIGHT_LABEL_SIZE = 105 static
Definition at line 166 of file musicqueryitemwidget.h.
Referenced by MusicLabelQueryItemWidget().
constexpr int MusicLabelQueryItemWidget::LINE_SPACING_SIZE = 105 static
Definition at line 167 of file musicqueryitemwidget.h.
Referenced by MusicWebDJRadioCategoryWidget::createCategoryItems(), and MusicWebDJRadioCategoryWidget::resizeGeometry().
QLabel* MusicLabelQueryItemWidget::m_iconLabel private
Definition at line 202 of file musicqueryitemwidget.h.
Referenced by downloadFinished(), MusicLabelQueryItemWidget(), and ~MusicLabelQueryItemWidget().
MusicResultDataItem MusicLabelQueryItemWidget::m_itemData private
Definition at line 201 of file musicqueryitemwidget.h.
Referenced by itemClicked(), and setResultDataItem().
QLabel * MusicLabelQueryItemWidget::m_nameLabel private
Definition at line 202 of file musicqueryitemwidget.h.
Referenced by MusicLabelQueryItemWidget(), setResultDataItem(), and ~MusicLabelQueryItemWidget().
constexpr int MusicLabelQueryItemWidget::WIDTH_LABEL_SIZE = 60 static
Definition at line 165 of file musicqueryitemwidget.h.
Referenced by downloadFinished(), MusicLabelQueryItemWidget(), and setResultDataItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicqueryitemwidget.h
TTKModule/TTKWidget/musicCoreKits/musicqueryitemwidget.cpp