TTKMusicplayer: MusicAbstractDelegate Class Reference
MusicAbstractDelegate Class Reference abstract
The class of the abstract item delegate.
#include <musicitemdelegate.h>
Public Member Functions
MusicAbstractDelegate (QObject *parent=nullptr)
~MusicAbstractDelegate ()
void setTextMode (bool mode)
void setElideMode (bool mode)
void setTreeModel (bool tree)
virtual void setStyleSheet (const QString &style) const =0
Protected Attributes
bool m_textMode
bool m_elideMode
bool m_treeMode
Detailed Description
The class of the abstract item delegate.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 40 of file musicitemdelegate.h.
Constructor & Destructor Documentation
MusicAbstractDelegate::MusicAbstractDelegate (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicitemdelegate.cpp.
MusicAbstractDelegate::~MusicAbstractDelegate ()
Definition at line 15 of file musicitemdelegate.cpp.
Member Function Documentation
void MusicAbstractDelegate::setElideMode (bool mode) inline
Set align mode.
Definition at line 58 of file musicitemdelegate.h.
Referenced by MusicPluginWidget::MusicPluginWidget().
virtual void MusicAbstractDelegate::setStyleSheet (const QString & style) const pure virtual
Set delegate item style.
Implemented in MusicPushButtonDelegate, MusicLabelDelegate, MusicProgressBarDelegate, and MusicCheckBoxDelegate.
void MusicAbstractDelegate::setTextMode (bool mode) inline
Set text mode.
Definition at line 54 of file musicitemdelegate.h.
Referenced by MusicPluginWidget::MusicPluginWidget().
void MusicAbstractDelegate::setTreeModel (bool tree) inline
Set tree model.
Definition at line 62 of file musicitemdelegate.h.
Referenced by MusicPluginWidget::MusicPluginWidget().
Member Data Documentation
bool MusicAbstractDelegate::m_elideMode protected
Definition at line 71 of file musicitemdelegate.h.
Referenced by MusicLabelDelegate::paint().
bool MusicAbstractDelegate::m_textMode protected
Definition at line 70 of file musicitemdelegate.h.
Referenced by MusicCheckBoxDelegate::paint().
bool MusicAbstractDelegate::m_treeMode protected
Definition at line 72 of file musicitemdelegate.h.
Referenced by MusicCheckBoxDelegate::paint(), MusicProgressBarDelegate::paint(), MusicLabelDelegate::paint(), and MusicPushButtonDelegate::paint().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicitemdelegate.h
TTKModule/TTKWidget/musicCoreKits/musicitemdelegate.cpp