TTKMusicPlayer: TTKCommon/TTKLibrary/ttkinitialization.cpp File Reference
ttkinitialization.cpp File Reference
#include "ttkinitialization.h"
#include "ttkdesktopscreen.h"
#include "ttklogoutput.h"
#include "ttkversion.h"
#include "ttkdumper.h"
#include <QTextCodec>
#include <QApplication>
#include <QFontDatabase>
Functions
bool qEnvironmentVariableIsSet (const char *v) noexcept
static QString message (const TTK::Attribute attr)
Function Documentation
static QString message (const TTK::Attribute attr) static
Definition at line 30 of file ttkinitialization.cpp.
References TTK::DisbaleFFmpeg, TTK::ScaleFactor, TTK::UseLog, and TTK::UseXCB.
Referenced by MusicLrcMakerWidget::backToMakeLrcWidget(), MusicDownloadBatchWidget::close(), MusicApplicationModule::closeCurrentEqualizer(), MusicTTKFMRadioPlayWidget::deleteButtonClicked(), MusicSongsContainerWidget::deleteRowItem(), MusicSongsContainerWidget::deleteRowItems(), MusicSettingWidget::downloadCacheClean(), MusicCoreMPlayer::durationRecieved(), MusicPlaylistBackupWidget::exportButtonClicked(), TTK::initialize(), TTKLogOutput::loggerHandler(), ReqWYInterface::makeTokenRequest(), MusicCoreMPlayer::positionRecieved(), TTKLocalPeer::receiveConnection(), MusicLrcMakerWidget::reMakeButtonClicked(), MusicAbstractDownloadTableWidget::removeItemAt(), MusicSongsListPlayTableWidget::removeItemAt(), MusicPlaylistBackupWidget::restoreButtonClicked(), MusicSettingWidget::saveParameterSettings(), MusicFileInformationWidget::saveTag(), MusicLrcContainerForInterior::setTimePosition(), and MusicCoreMPlayer::standardRecieved().
bool qEnvironmentVariableIsSet (const char * v) noexcept
Definition at line 18 of file ttkinitialization.cpp.
Referenced by TTK::initialize().