TTKMusicPlayer: MusicNetworkConnectionTestWidget Class Reference
MusicNetworkConnectionTestWidget Class Reference
The class of the network connection test widget.
#include <musicnetworkconnectiontestwidget.h>
Public Slots
void show ()
void buttonStateChanged ()
void testFinshed ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
void show ()
Public Member Functions
MusicNetworkConnectionTestWidget (QWidget *parent=nullptr)
~MusicNetworkConnectionTestWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
Public Member Functions inherited from TTKAbstractMoveWidget
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Private Attributes
Ui::MusicNetworkConnectionTestWidget * m_ui
int m_countIndex
QList< MusicNetworkConnectionItem * > m_connectionItems
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Protected Attributes inherited from TTKAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Detailed Description
The class of the network connection test widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 84 of file musicnetworkconnectiontestwidget.h.
Constructor & Destructor Documentation
MusicNetworkConnectionTestWidget::MusicNetworkConnectionTestWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 98 of file musicnetworkconnectiontestwidget.cpp.
References buttonStateChanged(), CHECK_DOWNLOAD_VISIT, CHECK_NORMAL_VISIT, CHECK_SERVER_VISIT, CHECK_VIP_VISIT, CHECK_WWW_VISIT, MusicGifLabelWidget::CheckBlue, m_connectionItems, m_ui, MusicUtils::Algorithm::mdII(), MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, MusicWidgetRenderer::setBackgroundLabel(), MusicNetworkConnectionItem::setText(), and testFinshed().
MusicNetworkConnectionTestWidget::~MusicNetworkConnectionTestWidget ()
Definition at line 162 of file musicnetworkconnectiontestwidget.cpp.
References G_SINGLE_MANAGER_PTR, m_connectionItems, and m_ui.
Member Function Documentation
void MusicNetworkConnectionTestWidget::buttonStateChanged () slot
Button state changed.
Definition at line 175 of file musicnetworkconnectiontestwidget.cpp.
References m_connectionItems, m_countIndex, and m_ui.
Referenced by MusicNetworkConnectionTestWidget().
void MusicNetworkConnectionTestWidget::show () slot
Override show function.
Definition at line 169 of file musicnetworkconnectiontestwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::show().
void MusicNetworkConnectionTestWidget::testFinshed () slot
Test network finished.
Definition at line 198 of file musicnetworkconnectiontestwidget.cpp.
References m_countIndex, and m_ui.
Referenced by MusicNetworkConnectionTestWidget().
Member Data Documentation
QList<MusicNetworkConnectionItem*> MusicNetworkConnectionTestWidget::m_connectionItems private
Definition at line 113 of file musicnetworkconnectiontestwidget.h.
Referenced by buttonStateChanged(), MusicNetworkConnectionTestWidget(), and ~MusicNetworkConnectionTestWidget().
int MusicNetworkConnectionTestWidget::m_countIndex private
Definition at line 112 of file musicnetworkconnectiontestwidget.h.
Referenced by buttonStateChanged(), and testFinshed().
Ui::MusicNetworkConnectionTestWidget* MusicNetworkConnectionTestWidget::m_ui private
Definition at line 110 of file musicnetworkconnectiontestwidget.h.
Referenced by buttonStateChanged(), MusicNetworkConnectionTestWidget(), show(), testFinshed(), and ~MusicNetworkConnectionTestWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkconnectiontestwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkconnectiontestwidget.cpp