TTKMusicplayer: MusicSpeedMeterWidget Class Reference
MusicSpeedMeterWidget Class Reference
The class of the speed meter widget.
#include <musicspeedmeterwidget.h>
Public Member Functions
MusicSpeedMeterWidget (QWidget *parent=0)
void setValue (qreal value)
qreal value () const
void setRatio (qreal value)
qreal ratio () const
void setAnimating (bool enable)
bool isAnimating () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
QSize sizeHint () const
QSize minimumSizeHint () const
Private Slots
void updateGraph ()
Private Member Functions
void initVariables ()
void resetVariables ()
void drawOuterCircle (QPainter *painter)
void drawInnerCircle (QPainter *painter)
void drawMark (QPainter *painter)
void drawCoverCircle (QPainter *painter)
void drawColorPie (QPainter *painter)
void drawIndicator (QPainter *painter)
void drawCoverBall (QPainter *painter)
void drawTextRect (QPainter *painter)
Private Attributes
qreal m_outerRadius
qreal m_innerRadius
qreal m_coverCircleRadius
qreal m_colorCircleRadius
qreal m_coverBallRadius
QPointF m_center
QRectF m_colorCircleRect
qreal m_value
qreal m_ratio
qreal m_currentValue
QTimer * updateTimer
bool m_bReverse
QTimer * singleTimer
bool m_bAnimating
Detailed Description
The class of the speed meter widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicspeedmeterwidget.h.
Constructor & Destructor Documentation
MusicSpeedMeterWidget::MusicSpeedMeterWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 4 of file musicspeedmeterwidget.cpp.
References initVariables().
Member Function Documentation
void MusicSpeedMeterWidget::drawColorPie (QPainter * painter) private
Draw color pie.
Definition at line 247 of file musicspeedmeterwidget.cpp.
References m_center, m_colorCircleRadius, m_colorCircleRect, and m_innerRadius.
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawCoverBall (QPainter * painter) private
Draw cover ball.
Definition at line 196 of file musicspeedmeterwidget.cpp.
References m_center, m_coverBallRadius, and m_outerRadius.
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawCoverCircle (QPainter * painter) private
Draw cover circle.
Definition at line 238 of file musicspeedmeterwidget.cpp.
References m_center, and m_coverCircleRadius.
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawIndicator (QPainter * painter) private
Draw indicator.
Definition at line 272 of file musicspeedmeterwidget.cpp.
References m_center, m_colorCircleRadius, m_coverBallRadius, m_currentValue, and S_LONG.
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawInnerCircle (QPainter * painter) private
Draw inner circle.
Definition at line 132 of file musicspeedmeterwidget.cpp.
References m_center, and m_innerRadius.
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawMark (QPainter * painter) private
Draw mark.
Definition at line 146 of file musicspeedmeterwidget.cpp.
References m_center, m_colorCircleRadius, m_ratio, MA_180, S_LONG, S_SHORT, S_SPACE, S_SPAOK, and value().
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawOuterCircle (QPainter * painter) private
Draw outer circle.
Definition at line 116 of file musicspeedmeterwidget.cpp.
References m_center, and m_outerRadius.
Referenced by paintEvent().
void MusicSpeedMeterWidget::drawTextRect (QPainter * painter) private
Draw text rect.
Definition at line 213 of file musicspeedmeterwidget.cpp.
References m_center, m_coverCircleRadius, m_ratio, m_value, and S_ANGLE.
Referenced by paintEvent().
QString MusicSpeedMeterWidget::getClassName () static
Get class object name.
Definition at line 10 of file musicspeedmeterwidget.cpp.
void MusicSpeedMeterWidget::initVariables () private
Init variablesn.
Definition at line 90 of file musicspeedmeterwidget.cpp.
References m_currentValue, m_ratio, m_value, resetVariables(), singleTimer, updateGraph(), and updateTimer.
Referenced by MusicSpeedMeterWidget().
bool MusicSpeedMeterWidget::isAnimating () const inline
Get meter animation.
Definition at line 71 of file musicspeedmeterwidget.h.
QSize MusicSpeedMeterWidget::minimumSizeHint () const protected
Override the minimumSizeHint function.
Definition at line 85 of file musicspeedmeterwidget.cpp.
void MusicSpeedMeterWidget::paintEvent (QPaintEvent * event) protected virtual
Override the widget event.
Definition at line 63 of file musicspeedmeterwidget.cpp.
References drawColorPie(), drawCoverBall(), drawCoverCircle(), drawIndicator(), drawInnerCircle(), drawMark(), drawOuterCircle(), drawTextRect(), and resetVariables().
qreal MusicSpeedMeterWidget::ratio () const inline
Get meter ratio.
Definition at line 63 of file musicspeedmeterwidget.h.
void MusicSpeedMeterWidget::resetVariables () private
Reset variables.
Definition at line 107 of file musicspeedmeterwidget.cpp.
References m_center, m_colorCircleRadius, m_coverCircleRadius, m_innerRadius, and m_outerRadius.
Referenced by initVariables(), and paintEvent().
void MusicSpeedMeterWidget::setAnimating (bool enable)
Set meter animation.
Definition at line 36 of file musicspeedmeterwidget.cpp.
References m_bAnimating.
void MusicSpeedMeterWidget::setRatio (qreal value)
Set meter ratio.
Definition at line 31 of file musicspeedmeterwidget.cpp.
References m_ratio, and value().
void MusicSpeedMeterWidget::setValue (qreal value)
Set meter value.
Definition at line 15 of file musicspeedmeterwidget.cpp.
References m_bAnimating, m_bReverse, m_currentValue, m_ratio, m_value, and updateTimer.
QSize MusicSpeedMeterWidget::sizeHint () const protected
Override the sizeHint function.
Definition at line 80 of file musicspeedmeterwidget.cpp.
void MusicSpeedMeterWidget::updateGraph () private slot
Update graph path.
Definition at line 42 of file musicspeedmeterwidget.cpp.
References m_bReverse, m_currentValue, m_value, and updateTimer.
Referenced by initVariables().
qreal MusicSpeedMeterWidget::value () const inline
Get meter value.
Definition at line 55 of file musicspeedmeterwidget.h.
Referenced by drawMark(), and setRatio().
Member Data Documentation
bool MusicSpeedMeterWidget::m_bAnimating private
Definition at line 144 of file musicspeedmeterwidget.h.
Referenced by setAnimating(), and setValue().
bool MusicSpeedMeterWidget::m_bReverse private
Definition at line 142 of file musicspeedmeterwidget.h.
Referenced by setValue(), and updateGraph().
QPointF MusicSpeedMeterWidget::m_center private
Definition at line 138 of file musicspeedmeterwidget.h.
Referenced by drawColorPie(), drawCoverBall(), drawCoverCircle(), drawIndicator(), drawInnerCircle(), drawMark(), drawOuterCircle(), drawTextRect(), and resetVariables().
qreal MusicSpeedMeterWidget::m_colorCircleRadius private
Definition at line 136 of file musicspeedmeterwidget.h.
Referenced by drawColorPie(), drawIndicator(), drawMark(), and resetVariables().
QRectF MusicSpeedMeterWidget::m_colorCircleRect private
Definition at line 139 of file musicspeedmeterwidget.h.
Referenced by drawColorPie().
qreal MusicSpeedMeterWidget::m_coverBallRadius private
Definition at line 137 of file musicspeedmeterwidget.h.
Referenced by drawCoverBall(), and drawIndicator().
qreal MusicSpeedMeterWidget::m_coverCircleRadius private
Definition at line 136 of file musicspeedmeterwidget.h.
Referenced by drawCoverCircle(), drawTextRect(), and resetVariables().
qreal MusicSpeedMeterWidget::m_currentValue private
Definition at line 140 of file musicspeedmeterwidget.h.
Referenced by drawIndicator(), initVariables(), setValue(), and updateGraph().
qreal MusicSpeedMeterWidget::m_innerRadius private
Definition at line 135 of file musicspeedmeterwidget.h.
Referenced by drawColorPie(), drawInnerCircle(), and resetVariables().
qreal MusicSpeedMeterWidget::m_outerRadius private
Definition at line 135 of file musicspeedmeterwidget.h.
Referenced by drawCoverBall(), drawOuterCircle(), and resetVariables().
qreal MusicSpeedMeterWidget::m_ratio private
Definition at line 140 of file musicspeedmeterwidget.h.
Referenced by drawMark(), drawTextRect(), initVariables(), setRatio(), and setValue().
qreal MusicSpeedMeterWidget::m_value private
Definition at line 140 of file musicspeedmeterwidget.h.
Referenced by drawTextRect(), initVariables(), setValue(), and updateGraph().
QTimer* MusicSpeedMeterWidget::singleTimer private
Definition at line 143 of file musicspeedmeterwidget.h.
Referenced by initVariables().
QTimer* MusicSpeedMeterWidget::updateTimer private
Definition at line 141 of file musicspeedmeterwidget.h.
Referenced by initVariables(), setValue(), and updateGraph().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicspeedmeterwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicspeedmeterwidget.cpp