TTKMusicplayer: MusicDownloadResetWidget Class Reference
MusicDownloadResetWidget Class Reference
The class of the download file exist widget.
#include <musicdownloadmgmtwidget.h>
Public Slots
void show ()
void restartToDownload ()
void openDetailInfo ()
void openFileLocation ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void openStackedDownloadWidget ()
Public Member Functions
MusicDownloadResetWidget (QWidget *parent=nullptr)
~MusicDownloadResetWidget ()
void setSongName (const QString &name)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicDownloadResetWidget * m_ui
QWidget * m_parentClass
QString m_currentName
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the download file exist widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicdownloadmgmtwidget.h.
Constructor & Destructor Documentation
MusicDownloadResetWidget::MusicDownloadResetWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 9 of file musicdownloadmgmtwidget.cpp.
References MusicLeftAreaWidget::instance(), m_parentClass, m_ui, MusicUIObject::MQSSPushButtonStyle03, MusicUIObject::MQSSToolButtonStyle04, openDetailInfo(), openFileLocation(), openStackedDownloadWidget(), and restartToDownload().
MusicDownloadResetWidget::~MusicDownloadResetWidget ()
Definition at line 41 of file musicdownloadmgmtwidget.cpp.
References m_ui.
Member Function Documentation
void MusicDownloadResetWidget::openDetailInfo () slot
Open file details information by song.
Definition at line 66 of file musicdownloadmgmtwidget.cpp.
References openStackedDownloadWidget().
Referenced by MusicDownloadResetWidget().
void MusicDownloadResetWidget::openFileLocation () slot
Open file location in dir.
Definition at line 72 of file musicdownloadmgmtwidget.cpp.
References MusicApplication::instance(), MusicApplication::musicDownloadContains(), and MusicUtils::Url::openUrl().
Referenced by MusicDownloadResetWidget().
void MusicDownloadResetWidget::openStackedDownloadWidget () signal
To open stacked download widget once.
Referenced by MusicDownloadResetWidget(), and openDetailInfo().
void MusicDownloadResetWidget::restartToDownload () slot
Restart to dwonload music data.
Definition at line 57 of file musicdownloadmgmtwidget.cpp.
References m_currentName, m_parentClass, MusicAbstractQueryRequest::MusicQuery, MusicDownloadWidget::setSongName(), and MusicDownloadWidget::show().
Referenced by MusicDownloadResetWidget().
void MusicDownloadResetWidget::setSongName (const QString & name)
Set current name to search and download musics.
Definition at line 46 of file musicdownloadmgmtwidget.cpp.
References m_currentName, and name.
Referenced by MusicDownloadMgmtWidget::setSongName().
void MusicDownloadResetWidget::show () slot
Override show function.
Definition at line 51 of file musicdownloadmgmtwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicDownloadMgmtWidget::setSongName().
Member Data Documentation
QString MusicDownloadResetWidget::m_currentName protected
Definition at line 76 of file musicdownloadmgmtwidget.h.
Referenced by restartToDownload(), and setSongName().
QWidget* MusicDownloadResetWidget::m_parentClass protected
Definition at line 75 of file musicdownloadmgmtwidget.h.
Referenced by MusicDownloadResetWidget(), and restartToDownload().
Ui::MusicDownloadResetWidget* MusicDownloadResetWidget::m_ui protected
Definition at line 73 of file musicdownloadmgmtwidget.h.
Referenced by MusicDownloadResetWidget(), show(), and ~MusicDownloadResetWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadmgmtwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadmgmtwidget.cpp