TTKMusicPlayer: MusicItemSearchTableWidget Class Reference
MusicItemSearchTableWidget Class Reference
The class of the search item table widget.
#include <musicitemsearchtablewidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) override
virtual void removeItems () override
virtual void actionGroupClick (QAction *action)
void createFinishedItem ()
Public Slots inherited from MusicQueryTableWidget
virtual void itemDoubleClicked (int row, int column)=0
virtual void createSearchedItem (const MusicResultInfoItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicItemSearchTableWidget (QWidget *parent=nullptr)
~MusicItemSearchTableWidget ()
virtual void startSearchQuery (const QString &text) override
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
virtual void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * queryInput () const
virtual void downloadQuery (int row)=0
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
void createContextMenu (QMenu &menu)
QString randSimulation () const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes
MusicGifLabelWidget * m_loadingLabel
QActionGroup * m_actionGroup
TTKLabelItemDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void songBufferToPlaylist (const MusicResultDataItem &songItem)
void restartSearchQuery (const QString &name)
Detailed Description
The class of the search item table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicitemsearchtablewidget.h.
Constructor & Destructor Documentation
MusicItemSearchTableWidget::MusicItemSearchTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicitemsearchtablewidget.cpp.
References actionGroupClick(), TTK::UI::BackgroundStyle13, MusicGifLabelWidget::CicleBlue, m_actionGroup, m_labelDelegate, m_loadingLabel, and TTKAbstractItemDelegate::setStyleSheet().
MusicItemSearchTableWidget::~MusicItemSearchTableWidget ()
Definition at line 20 of file musicitemsearchtablewidget.cpp.
References m_actionGroup, m_labelDelegate, and m_loadingLabel.
Member Function Documentation
void MusicItemSearchTableWidget::actionGroupClick (QAction * action) virtual slot
Left context menu action group click by action.
Definition at line 63 of file musicitemsearchtablewidget.cpp.
References TTK::String::artistName(), MusicQueryTableWidget::downloadQuery(), MusicQueryTableWidget::restartSearchQuery(), and TTK::String::songName().
Referenced by MusicItemSearchTableWidget().
void MusicItemSearchTableWidget::createContextMenu (QMenu & menu) protected
Create context menu.
Definition at line 112 of file musicitemsearchtablewidget.cpp.
References m_actionGroup, MusicQueryTableWidget::m_networkRequest, TTK::MusicSongInformation::m_singerName, TTK::MusicSongInformation::m_songName, TTK::UI::MenuStyle02, and MusicAbstractQueryRequest::songInfoList().
Referenced by MusicLrcSearchTableWidget::contextMenuEvent(), MusicSongSearchTableWidget::contextMenuEvent(), and MusicVideoSearchTableWidget::contextMenuEvent().
void MusicItemSearchTableWidget::createFinishedItem () slot
Create the search finished item.
Definition at line 84 of file musicitemsearchtablewidget.cpp.
References m_labelDelegate, m_loadingLabel, MusicQueryTableWidget::m_networkRequest, MusicPageQueryRequest::pageIndex(), MusicPageQueryRequest::pageSize(), MusicGifLabelWidget::run(), MusicPageQueryRequest::totalSize(), and TTK_DISPLAY_ROLE.
Referenced by startSearchQuery(), MusicVideoSearchTableWidget::startSearchQuery(), and MusicVideoSearchTableWidget::startSearchSingleQuery().
void MusicItemSearchTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 35 of file musicitemsearchtablewidget.cpp.
References MusicFillItemTableWidget::itemCellClicked(), m_loadingLabel, MusicQueryTableWidget::m_networkRequest, MusicPageQueryRequest::pageIndex(), MusicGifLabelWidget::run(), MusicPageQueryRequest::startToPage(), and TTK_DISPLAY_ROLE.
Referenced by MusicLrcSearchTableWidget::itemCellClicked(), MusicSongSearchTableWidget::itemCellClicked(), and MusicVideoSearchTableWidget::itemCellClicked().
QString MusicItemSearchTableWidget::randSimulation () const protected
Get current random simulation.
Definition at line 136 of file musicitemsearchtablewidget.cpp.
References TTK::random().
Referenced by MusicLrcSearchTableWidget::createSearchedItem(), MusicSongSearchTableWidget::createSearchedItem(), and MusicVideoSearchTableWidget::createSearchedItem().
void MusicItemSearchTableWidget::removeItems () override virtual slot
Remove all items.
Definition at line 54 of file musicitemsearchtablewidget.cpp.
References MusicAbstractTableWidget::removeItems().
Referenced by MusicLrcSearchTableWidget::removeItems(), MusicSongSearchTableWidget::removeItems(), and MusicVideoSearchTableWidget::removeItems().
void MusicItemSearchTableWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Definition at line 106 of file musicitemsearchtablewidget.cpp.
References m_loadingLabel.
void MusicItemSearchTableWidget::startSearchQuery (const QString & text) override virtual
Start search query by text.
Implements MusicQueryTableWidget.
Reimplemented in MusicVideoSearchTableWidget, MusicSongSearchTableWidget, and MusicLrcSearchTableWidget.
Definition at line 27 of file musicitemsearchtablewidget.cpp.
References createFinishedItem(), G_DOWNLOAD_QUERY_PTR, and MusicQueryTableWidget::setQueryInput().
Referenced by MusicSongSearchTableWidget::setSearchQuality(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchQuery(), and MusicSongSearchTableWidget::startSearchSingleQuery().
Member Data Documentation
QActionGroup* MusicItemSearchTableWidget::m_actionGroup protected
Definition at line 79 of file musicitemsearchtablewidget.h.
Referenced by MusicSongSearchTableWidget::contextMenuEvent(), createContextMenu(), MusicItemSearchTableWidget(), and ~MusicItemSearchTableWidget().
TTKLabelItemDelegate* MusicItemSearchTableWidget::m_labelDelegate protected
Definition at line 80 of file musicitemsearchtablewidget.h.
Referenced by createFinishedItem(), MusicItemSearchTableWidget(), and ~MusicItemSearchTableWidget().
MusicGifLabelWidget* MusicItemSearchTableWidget::m_loadingLabel protected
Definition at line 78 of file musicitemsearchtablewidget.h.
Referenced by createFinishedItem(), itemCellClicked(), MusicItemSearchTableWidget(), resizeEvent(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchQuery(), MusicVideoSearchTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchSingleQuery(), MusicVideoSearchTableWidget::startSearchSingleQuery(), and ~MusicItemSearchTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicitemsearchtablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicitemsearchtablewidget.cpp