TTKMusicPlayer: MusicDownloadQueryFactory Class Reference
MusicDownloadQueryFactory Class Reference
The class of the produce the download query class by type.
#include <musicdownloadqueryfactory.h>
Public Member Functions
MusicAbstractQueryRequest * makeSongRequest (QObject *parent)
MusicAbstractQueryRequest * makeNewSongRequest (QObject *parent)
MusicAbstractQueryRequest * makeMovieRequest (QObject *parent)
MusicAbstractQueryRequest * makeAlbumRequest (QObject *parent)
MusicAbstractQueryRequest * makeNewAlbumRequest (QObject *parent)
MusicAbstractQueryRequest * makeArtistRequest (QObject *parent)
MusicAbstractQueryRequest * makeArtistListRequest (QObject *parent)
MusicAbstractQueryRequest * makeHotArtistListRequest (QObject *parent)
MusicAbstractQueryRequest * makeArtistAlbumRequest (QObject *parent)
MusicAbstractQueryRequest * makeArtistMovieRequest (QObject *parent)
MusicAbstractQueryRequest * makeToplistRequest (QObject *parent)
MusicAbstractQueryRequest * makePlaylistRequest (QObject *parent)
MusicAbstractQueryRequest * makePlaylistRecommendRequest (QObject *parent)
MusicAbstractQueryRequest * makePlaylistHighRequest (QObject *parent)
MusicCommentsRequest * makeSongCommentRequest (QObject *parent)
MusicCommentsRequest * makePlaylistCommentRequest (QObject *parent)
MusicDiscoverListRequest * makeDiscoverListRequest (QObject *parent)
MusicCoverRequest * makeCoverRequest (QObject *parent)
MusicAbstractDownloadRequest * makeLrcRequest (const QString &url, const QString &path, QObject *parent)
MusicAbstractDownloadRequest * makeCoverRequest (const QString &url, const QString &path, QObject *parent)
MusicDownloadBackgroundRequest * makeBackgroundRequest (const QString &name, const QString &path, QObject *parent)
Detailed Description
The class of the produce the download query class by type.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicdownloadqueryfactory.h.
Member Function Documentation
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeAlbumRequest (QObject * parent)
Make album request object by type.
Definition at line 96 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeArtistAlbumRequest (QObject * parent)
Make artist album request object by type.
Definition at line 171 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeArtistListRequest (QObject * parent)
Make artist category request object by type.
Definition at line 141 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeArtistMovieRequest (QObject * parent)
Make artist movie request object by type.
Definition at line 186 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeArtistRequest (QObject * parent)
Make artist request object by type.
Definition at line 126 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicDownloadBackgroundRequest * MusicDownloadQueryFactory::makeBackgroundRequest (const QString & name, const QString & path, QObject * parent)
Make download art background object by type.
Definition at line 340 of file musicdownloadqueryfactory.cpp.
MusicCoverRequest * MusicDownloadQueryFactory::makeCoverRequest (QObject * parent)
Make cover object by type.
Definition at line 303 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KW, and TTKStaticCast.
MusicAbstractDownloadRequest * MusicDownloadQueryFactory::makeCoverRequest (const QString & url, const QString & path, QObject * parent)
Make download art cover object by type.
Definition at line 328 of file musicdownloadqueryfactory.cpp.
References TTK::Cover, MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KW, and TTKStaticCast.
MusicDiscoverListRequest * MusicDownloadQueryFactory::makeDiscoverListRequest (QObject * parent)
Make discover list request object by type.
Definition at line 289 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeHotArtistListRequest (QObject * parent)
Make hot artist category request object by type.
Definition at line 156 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractDownloadRequest * MusicDownloadQueryFactory::makeLrcRequest (const QString & url, const QString & path, QObject * parent)
Make download lrc object by type.
Definition at line 315 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeMovieRequest (QObject * parent)
Make movie request object by type.
Definition at line 81 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeNewAlbumRequest (QObject * parent)
Make new album request object by type.
Definition at line 111 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeNewSongRequest (QObject * parent)
Make new song request object by type.
Definition at line 66 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicCommentsRequest * MusicDownloadQueryFactory::makePlaylistCommentRequest (QObject * parent)
Make playlist comment request object by type.
Definition at line 275 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makePlaylistHighRequest (QObject * parent)
Make playlist high request object by type.
Definition at line 246 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makePlaylistRecommendRequest (QObject * parent)
Make playlist recommend request object by type.
Definition at line 231 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makePlaylistRequest (QObject * parent)
Make playlist request object by type.
Definition at line 216 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicCommentsRequest * MusicDownloadQueryFactory::makeSongCommentRequest (QObject * parent)
Make song comment request object by type.
Definition at line 261 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeSongRequest (QObject * parent)
Make song request object by type.
Definition at line 51 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
MusicAbstractQueryRequest * MusicDownloadQueryFactory::makeToplistRequest (QObject * parent)
Make toplist request object by type.
Definition at line 201 of file musicdownloadqueryfactory.cpp.
References MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, MusicAbstractQueryRequest::queryServer(), TTK_INFO_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadqueryfactory.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadqueryfactory.cpp