TTKMusicPlayer: MusicCiBaRequest Class Reference
MusicCiBaRequest Class Reference
The class of the ciba request.
#include <musiccibarequest.h>
Public Slots
virtual void downloadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downloadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicCiBaRequest (QObject *parent=nullptr)
void startToRequest ()
QString note () const noexcept
QString content () const noexcept
QString image () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value) noexcept
const QVariant header (const QString &key) const noexcept
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downloadDataChanged (const QString &bytes)
void downloadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the ciba request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musiccibarequest.h.
Constructor & Destructor Documentation
MusicCiBaRequest::MusicCiBaRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musiccibarequest.cpp.
Member Function Documentation
QString MusicCiBaRequest::content () const noexcept
Get content data.
Definition at line 29 of file musiccibarequest.cpp.
References TTKAbstractNetwork::m_rawData.
Referenced by MusicSongDailyWidget::downloadImageFinished().
void MusicCiBaRequest::downloadFinished () final override virtual slot
Download data from net finished.
Definition at line 39 of file musiccibarequest.cpp.
References TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downloadFinished(), TTKAbstractNetwork::downloadRawDataChanged(), QJsonParseError::error, QJsonDocument::fromJson(), image(), TTKAbstractNetwork::m_rawData, TTKAbstractNetwork::m_reply, QJsonParseError::NoError, MusicDataSourceRequest::startToRequest(), QJsonDocument::toVariant(), TTK_ERROR_STREAM, and TTK_INFO_STREAM.
Referenced by startToRequest().
QString MusicCiBaRequest::image () const noexcept
Get image data.
Definition at line 34 of file musiccibarequest.cpp.
References TTKAbstractNetwork::m_rawData.
Referenced by downloadFinished().
QString MusicCiBaRequest::note () const noexcept
Get note data.
Definition at line 24 of file musiccibarequest.cpp.
References TTKAbstractNetwork::m_rawData.
Referenced by MusicSongDailyWidget::downloadImageFinished().
void MusicCiBaRequest::startToRequest ()
Start to download counter data.
Definition at line 12 of file musiccibarequest.cpp.
References downloadFinished(), TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, TTK::Algorithm::mdII(), QtNetworkErrorConnect, QUERY_URL, MusicAbstractNetwork::replyError(), TTK::setContentTypeHeader(), TTK::setSslConfiguration(), TTK::toString(), TTK_DATE_FORMAT, and TTK_SLOT.
Referenced by MusicSongDailyWidget::MusicSongDailyWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musiccibarequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musiccibarequest.cpp