TTKMusicplayer: MusicAbstractQueryRequest Class Reference
MusicAbstractQueryRequest Class Reference abstract
The class to abstract query download data from net.
#include <musicabstractqueryrequest.h>
Public Types
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual ~MusicAbstractQueryRequest ()
virtual void startToSearch (QueryType type, const QString &text)=0
virtual void startToSingleSearch (const QString &text)
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
virtual ~MusicPagingRequest ()
virtual void deleteAll () override
virtual void startToPage (int offset)
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Attributes
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
QVariantMap m_headerData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Detailed Description
The class to abstract query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 100 of file musicabstractqueryrequest.h.
Member Enumeration Documentation
enum MusicAbstractQueryRequest::QueryType
Enumerator
MusicQuery
query music
MovieQuery
query movie
LrcQuery
query lrc
OtherQuery
query external
Definition at line 105 of file musicabstractqueryrequest.h.
Constructor & Destructor Documentation
MusicAbstractQueryRequest::MusicAbstractQueryRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicabstractqueryrequest.cpp.
References m_queryAllRecords, m_queryServer, m_querySimplify, and m_searchQuality.
MusicAbstractQueryRequest::~MusicAbstractQueryRequest () virtual
Definition at line 14 of file musicabstractqueryrequest.cpp.
References MusicPagingRequest::deleteAll().
Member Function Documentation
void MusicAbstractQueryRequest::clearAllItems () signal
Clear all items before the new query start.
Referenced by MusicBDQueryLearnRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicQQQueryArtistListRequest::downLoadFinished(), MusicKWQueryArtistListRequest::downLoadFinished(), MusicXMQueryArtistListRequest::downLoadFinished(), MusicBDQueryArtistListRequest::downLoadFinished(), MusicKGQueryArtistListRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicWYQueryArtistListRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicBDQueryMovieRequest::downLoadFinished(), MusicWYQueryMovieRequest::downLoadFinished(), MusicXMQueryMovieRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicXMQueryPlaylistRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicBDQueryRequest::singleDownLoadFinished(), MusicXMQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicXMQueryMovieRequest::singleDownLoadFinished(), MusicBDQueryMovieRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::startToSearch(), MusicXMQueryRequest::startToSearch(), MusicQQQueryRequest::startToSearch(), MusicWYQueryRequest::startToSearch(), MusicBDQueryRequest::startToSearch(), and MusicKWQueryRequest::startToSearch().
void MusicAbstractQueryRequest::createSearchedItem (const MusicSearchedItem & songItem) signal
Create the current items by song name\ artist name and time.
Referenced by MusicMVRadioProgramRequest::downLoadFinished(), MusicBDQueryLearnRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicBDQueryMovieRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryMovieRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicXMQueryMovieRequest::readFromMusicMVAttribute(), MusicXMQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicBDQueryRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicBDQueryMovieRequest::singleDownLoadFinished(), MusicXMQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), and MusicWYQueryMovieRequest::startMVListQuery().
QString MusicAbstractQueryRequest::findTimeStringByAttrs (const MusicObject::MusicSongAttributes & attrs) protected
Find time string by attrs.
Definition at line 43 of file musicabstractqueryrequest.cpp.
Referenced by MusicBDQueryMovieRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicBDQueryMovieRequest::readFromMusicMVAttributeIQY(), MusicBDQueryRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), and MusicBDQueryMovieRequest::singleDownLoadFinished().
bool MusicAbstractQueryRequest::findUrlFileSize (MusicObject::MusicSongAttribute * attr) protected
Find download file size.
Definition at line 56 of file musicabstractqueryrequest.cpp.
References getUrlFileSize(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicObject::MusicSongAttribute::m_size, MusicAbstractNetwork::m_stateCode, MusicObject::MusicSongAttribute::m_url, MusicObject::NetworkQuery, and MusicUtils::Number::size2Label().
Referenced by MusicKWQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), findUrlFileSize(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryMovieRequest::readFromMusicMVAttribute(), MusicKWQueryMovieRequest::readFromMusicMVAttribute(), MusicBDQueryMovieRequest::readFromMusicMVAttributeWeb(), MusicBDQueryLearnRequest::readFromMusicSongAttribute(), MusicKWQueryRequest::singleDownLoadFinished(), and MusicWYQueryMovieRequest::startMVListQuery().
bool MusicAbstractQueryRequest::findUrlFileSize (MusicObject::MusicSongAttributes * attrs) protected
Find download file size.
Definition at line 68 of file musicabstractqueryrequest.cpp.
References findUrlFileSize().
const MusicObject::MusicSongInformations& MusicAbstractQueryRequest::getMusicSongInfos () const inline
Get the current song container.
Definition at line 179 of file musicabstractqueryrequest.h.
Referenced by MusicSongSearchTableWidget::actionGroupClick(), MusicItemQueryTableWidget::addSearchMusicToPlaylist(), MusicSongSearchTableWidget::addSearchMusicToPlaylist(), MusicSongSearchOnlineWidget::buttonClicked(), MusicSongSharingWidget::confirmButtonClicked(), MusicItemQueryTableWidget::contextMenuEvent(), MusicItemSearchTableWidget::createContextMenu(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicDownloadStatusObject::currentLrcDataDownload(), MusicSoundKMicroSearchTableWidget::dataDownloadPlay(), MusicItemQueryTableWidget::downloadBatchData(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicItemQueryTableWidget::downloadDataFrom(), MusicVideoSearchTableWidget::downloadLocalMovie(), MusicDownloadWidget::getMatchMusicSongInformation(), MusicVideoSearchTableWidget::getMusicMediaInfo(), MusicWebMVRadioInfoTableWidget::itemCellClicked(), MusicVideoSearchTableWidget::itemDoubleClicked(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicWebMVRadioInfoTableWidget::musicDownloadLocal(), MusicSoundKMicroSearchTableWidget::musicDownloadLocal(), MusicItemQueryTableWidget::musicDownloadLocal(), MusicSongSearchTableWidget::musicDownloadLocal(), MusicSongSearchTableWidget::musicSongDownload(), MusicAlbumQueryWidget::queryAlbumFinished(), MusicAlbumQueryWidget::queryAllFinished(), MusicArtistQueryWidget::queryAllFinished(), MusicArtistQueryWidget::queryArtistFinished(), MusicItemQueryTableWidget::searchChanged(), MusicAbstractItemQueryWidget::setSongCountText(), MusicWYTranslationRequest::startToDownload(), MusicBDSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicXMSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
bool MusicAbstractQueryRequest::getQueryAllRecords () const inline
Get query all records flag.
Definition at line 147 of file musicabstractqueryrequest.h.
QString MusicAbstractQueryRequest::getQueryServer () const inline
Return the current song query server.
Definition at line 167 of file musicabstractqueryrequest.h.
Referenced by MusicSongSharingWidget::confirmButtonClicked(), MusicArtistListQueryWidget::createArtistListItem(), MusicToplistQueryWidget::createLabels(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicDownLoadQueryFactory::getAlbumRequest(), MusicDownLoadQueryFactory::getArtistListRequest(), MusicDownLoadQueryFactory::getArtistRequest(), MusicDownLoadQueryFactory::getMovieRequest(), MusicDownLoadQueryFactory::getPlaylistRequest(), MusicDownLoadQueryFactory::getQueryRequest(), MusicDownLoadQueryFactory::getRecommendRequest(), MusicDownLoadQueryFactory::getToplistRequest(), MusicVideoSearchTableWidget::itemDoubleClicked(), and MusicAbstractItemQueryWidget::shareButtonClicked().
bool MusicAbstractQueryRequest::getQuerySimplify () const inline
Get query simplify flag.
Definition at line 155 of file musicabstractqueryrequest.h.
QueryType MusicAbstractQueryRequest::getQueryType () const inline
Return the current song query type.
Definition at line 163 of file musicabstractqueryrequest.h.
QString MusicAbstractQueryRequest::getSearchedText () const inline
Return the current song name.
Definition at line 171 of file musicabstractqueryrequest.h.
Referenced by MusicDownloadWidget::getMatchMusicSongInformation(), and MusicLrcSearchTableWidget::musicDownloadLocal().
QString MusicAbstractQueryRequest::getSearchQuality () const inline
Get search data quality.
Definition at line 139 of file musicabstractqueryrequest.h.
Referenced by MusicSongSearchTableWidget::startSearchQuery(), and MusicSongSearchTableWidget::startSearchSingleQuery().
qint64 MusicAbstractQueryRequest::getUrlFileSize (const QString & url) protected
Get download file size.
Definition at line 81 of file musicabstractqueryrequest.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::NetworkError, and MusicObject::setSslConfiguration().
Referenced by findUrlFileSize().
bool MusicAbstractQueryRequest::isEmpty () const inline
Check the current song container is empty.
Definition at line 183 of file musicabstractqueryrequest.h.
Referenced by MusicSongSharingWidget::confirmButtonClicked(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicWYTranslationRequest::startToDownload(), MusicQQSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), MusicBDSongCommentsRequest::startToSearch(), MusicXMSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
QString MusicAbstractQueryRequest::mapQueryServerString () const
Map query server string.
Definition at line 24 of file musicabstractqueryrequest.cpp.
References m_queryServer, QUERY_BD_INTERFACE, QUERY_KG_INTERFACE, QUERY_KW_INTERFACE, QUERY_QQ_INTERFACE, QUERY_WY_INTERFACE, and QUERY_XM_INTERFACE.
Referenced by MusicBDQueryLearnRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicBDQueryMovieRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryMovieRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicXMQueryMovieRequest::readFromMusicMVAttribute(), MusicXMQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicBDQueryRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicBDQueryMovieRequest::singleDownLoadFinished(), MusicXMQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), and MusicWYQueryMovieRequest::startMVListQuery().
void MusicAbstractQueryRequest::setMusicSongInfos (const MusicObject::MusicSongInformations & infos) inline
Set the current song container.
Definition at line 175 of file musicabstractqueryrequest.h.
Referenced by MusicVideoSearchTableWidget::startSearchSingleQuery().
void MusicAbstractQueryRequest::setQueryAllRecords (bool state) inline
Set wheather query all quality of records.
Definition at line 143 of file musicabstractqueryrequest.h.
Referenced by MusicToplistQueryWidget::categoryChanged(), MusicAlbumQueryWidget::setSongName(), MusicToplistQueryWidget::setSongName(), MusicDownloadWidget::setSongName(), MusicArtistQueryWidget::setSongName(), MusicItemQueryTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchSingleQuery(), MusicWYTranslationRequest::startToDownload(), MusicQQSongCommentsRequest::startToSearch(), MusicBDSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), MusicXMSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
void MusicAbstractQueryRequest::setQuerySimplify (bool state) inline
Set query simplify mode.
Definition at line 151 of file musicabstractqueryrequest.h.
Referenced by MusicAlbumQueryWidget::setSongName(), MusicArtistQueryWidget::setSongName(), MusicWYTranslationRequest::startToDownload(), MusicQQSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), MusicBDSongCommentsRequest::startToSearch(), MusicXMSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
void MusicAbstractQueryRequest::setQueryType (QueryType type) inline
Return the current song query type.
Definition at line 159 of file musicabstractqueryrequest.h.
Referenced by MusicVideoSearchTableWidget::startSearchSingleQuery().
void MusicAbstractQueryRequest::setSearchQuality (const QString & qual) inline
Set search data quality.
Definition at line 135 of file musicabstractqueryrequest.h.
Referenced by MusicSongSearchTableWidget::setSearchQuality(), MusicSongSearchTableWidget::startSearchQuery(), and MusicSongSearchTableWidget::startSearchSingleQuery().
virtual void MusicAbstractQueryRequest::startToSearch (QueryType type, const QString & text) pure virtual
Start to search data from name and type. Subclass should implement this function.
Implemented in MusicKWQueryRequest, MusicBDQueryMovieRequest, MusicBDQueryPlaylistRequest, MusicBDQueryRequest, MusicBDQueryToplistRequest, MusicKGQueryPlaylistRequest, MusicKGQueryRequest, MusicKGQueryToplistRequest, MusicKWQueryPlaylistRequest, MusicKWQueryToplistRequest, MusicQQQueryPlaylistRequest, MusicQQQueryRequest, MusicQQQueryToplistRequest, MusicWYQueryMovieRequest, MusicWYQueryPlaylistRequest, MusicWYQueryRequest, MusicWYQueryToplistRequest, MusicXMQueryMovieRequest, MusicXMQueryPlaylistRequest, MusicXMQueryRequest, MusicXMQueryToplistRequest, MusicDJRadioProgramCategoryRequest, MusicKGQueryMovieRequest, MusicKWQueryMovieRequest, MusicQQQueryMovieRequest, MusicQueryMovieRequest, MusicBDQueryLearnRequest, MusicQueryAlbumRequest, MusicQueryArtistListRequest, MusicQueryArtistRequest, MusicQueryRecommendRequest, MusicQueryToplistRequest, and MusicAbstractMVRadioRequest.
Referenced by MusicToplistQueryWidget::categoryChanged(), MusicPlaylistQueryWidget::categoryChanged(), MusicWebMVRadioQueryWidget::categoryChanged(), MusicDownloadStatusObject::checkLrcValid(), MusicSongSharingWidget::confirmButtonClicked(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicArtistListQueryWidget::numberButtonClicked(), MusicAlbumQueryWidget::setSongName(), MusicToplistQueryWidget::setSongName(), MusicArtistListQueryWidget::setSongName(), MusicWebDJRadioQueryWidget::setSongName(), MusicPlaylistQueryWidget::setSongName(), MusicWebMVRadioQueryWidget::setSongName(), MusicDownloadWidget::setSongName(), MusicArtistQueryWidget::setSongName(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSoundKMicroSearchTableWidget::startSearchQuery(), MusicItemQueryTableWidget::startSearchQuery(), MusicVideoSearchTableWidget::startSearchQuery(), and MusicSongSearchTableWidget::startSearchQuery().
void MusicAbstractQueryRequest::startToSingleSearch (const QString & text) virtual
Start to search single data from id. Subclass should implement this function.
Reimplemented in MusicKWQueryRequest, MusicBDQueryMovieRequest, MusicBDQueryRequest, MusicKGQueryRequest, MusicQQQueryRequest, MusicWYQueryMovieRequest, MusicWYQueryRequest, MusicXMQueryMovieRequest, MusicXMQueryRequest, MusicKGQueryMovieRequest, MusicKWQueryMovieRequest, MusicQQQueryMovieRequest, MusicBDQueryAlbumRequest, MusicKGQueryAlbumRequest, MusicKWQueryAlbumRequest, MusicQQQueryAlbumRequest, MusicWYQueryAlbumRequest, and MusicXMQueryAlbumRequest.
Definition at line 19 of file musicabstractqueryrequest.cpp.
Referenced by MusicArtistAlbumsQueryWidget::setSongName(), MusicArtistAlbumsQueryWidget::setSongNameById(), MusicVideoSearchTableWidget::startSearchSingleQuery(), and MusicSongSearchTableWidget::startSearchSingleQuery().
Member Data Documentation
QueryType MusicAbstractQueryRequest::m_currentType protected
Definition at line 220 of file musicabstractqueryrequest.h.
Referenced by MusicKGQueryMovieRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicWYQueryRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicKGQueryRequest::startToSearch(), MusicBDQueryMovieRequest::startToSearch(), MusicXMQueryRequest::startToSearch(), MusicBDQueryRequest::startToSearch(), MusicQQQueryRequest::startToSearch(), MusicXMQueryMovieRequest::startToSearch(), and MusicKWQueryRequest::startToSearch().
MusicObject::MusicSongInformations MusicAbstractQueryRequest::m_musicSongInfos protected
Definition at line 217 of file musicabstractqueryrequest.h.
Referenced by MusicMVRadioProgramRequest::downLoadFinished(), MusicBDQueryLearnRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistListRequest::downLoadFinished(), MusicQQQueryArtistListRequest::downLoadFinished(), MusicKWQueryArtistListRequest::downLoadFinished(), MusicBDQueryArtistListRequest::downLoadFinished(), MusicKGQueryArtistListRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicWYQueryArtistListRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicXMQueryMovieRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicBDQueryMovieRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicWYQueryMovieRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryPlaylistRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicXMQueryMovieRequest::readFromMusicMVAttribute(), MusicWYQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicBDQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicXMQueryRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::singleDownLoadFinished(), MusicBDQueryMovieRequest::singleDownLoadFinished(), MusicXMQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::startMVListQuery(), MusicWYQueryRequest::startToSearch(), MusicXMQueryRequest::startToSearch(), MusicQQQueryRequest::startToSearch(), MusicKGQueryRequest::startToSearch(), MusicBDQueryRequest::startToSearch(), and MusicKWQueryRequest::startToSearch().
bool MusicAbstractQueryRequest::m_queryAllRecords protected
Definition at line 221 of file musicabstractqueryrequest.h.
Referenced by MusicBDQueryArtistRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicAbstractQueryRequest(), and MusicXMQueryRequest::singleDownLoadFinished().
QString MusicAbstractQueryRequest::m_queryServer protected
Definition at line 219 of file musicabstractqueryrequest.h.
Referenced by mapQueryServerString(), MusicAbstractQueryRequest(), MusicBDQueryAlbumRequest::MusicBDQueryAlbumRequest(), MusicBDQueryArtistListRequest::MusicBDQueryArtistListRequest(), MusicBDQueryArtistRequest::MusicBDQueryArtistRequest(), MusicBDQueryLearnRequest::MusicBDQueryLearnRequest(), MusicBDQueryMovieRequest::MusicBDQueryMovieRequest(), MusicBDQueryPlaylistRequest::MusicBDQueryPlaylistRequest(), MusicBDQueryRecommendRequest::MusicBDQueryRecommendRequest(), MusicBDQueryRequest::MusicBDQueryRequest(), MusicBDQueryToplistRequest::MusicBDQueryToplistRequest(), MusicDJRadioProgramCategoryRequest::MusicDJRadioProgramCategoryRequest(), MusicKGQueryAlbumRequest::MusicKGQueryAlbumRequest(), MusicKGQueryArtistListRequest::MusicKGQueryArtistListRequest(), MusicKGQueryArtistRequest::MusicKGQueryArtistRequest(), MusicKGQueryMovieRequest::MusicKGQueryMovieRequest(), MusicKGQueryPlaylistRequest::MusicKGQueryPlaylistRequest(), MusicKGQueryRecommendRequest::MusicKGQueryRecommendRequest(), MusicKGQueryRequest::MusicKGQueryRequest(), MusicKGQueryToplistRequest::MusicKGQueryToplistRequest(), MusicKWQueryAlbumRequest::MusicKWQueryAlbumRequest(), MusicKWQueryArtistListRequest::MusicKWQueryArtistListRequest(), MusicKWQueryArtistRequest::MusicKWQueryArtistRequest(), MusicKWQueryMovieRequest::MusicKWQueryMovieRequest(), MusicKWQueryPlaylistRequest::MusicKWQueryPlaylistRequest(), MusicKWQueryRecommendRequest::MusicKWQueryRecommendRequest(), MusicKWQueryRequest::MusicKWQueryRequest(), MusicKWQueryToplistRequest::MusicKWQueryToplistRequest(), MusicQQQueryAlbumRequest::MusicQQQueryAlbumRequest(), MusicQQQueryArtistListRequest::MusicQQQueryArtistListRequest(), MusicQQQueryArtistRequest::MusicQQQueryArtistRequest(), MusicQQQueryMovieRequest::MusicQQQueryMovieRequest(), MusicQQQueryPlaylistRequest::MusicQQQueryPlaylistRequest(), MusicQQQueryRecommendRequest::MusicQQQueryRecommendRequest(), MusicQQQueryRequest::MusicQQQueryRequest(), MusicQQQueryToplistRequest::MusicQQQueryToplistRequest(), MusicWYQueryAlbumRequest::MusicWYQueryAlbumRequest(), MusicWYQueryArtistListRequest::MusicWYQueryArtistListRequest(), MusicWYQueryArtistRequest::MusicWYQueryArtistRequest(), MusicWYQueryMovieRequest::MusicWYQueryMovieRequest(), MusicWYQueryPlaylistRequest::MusicWYQueryPlaylistRequest(), MusicWYQueryRecommendRequest::MusicWYQueryRecommendRequest(), MusicWYQueryRequest::MusicWYQueryRequest(), MusicWYQueryToplistRequest::MusicWYQueryToplistRequest(), MusicXMQueryAlbumRequest::MusicXMQueryAlbumRequest(), MusicXMQueryArtistListRequest::MusicXMQueryArtistListRequest(), MusicXMQueryArtistRequest::MusicXMQueryArtistRequest(), MusicXMQueryMovieRequest::MusicXMQueryMovieRequest(), MusicXMQueryPlaylistRequest::MusicXMQueryPlaylistRequest(), MusicXMQueryRecommendRequest::MusicXMQueryRecommendRequest(), MusicXMQueryRequest::MusicXMQueryRequest(), and MusicXMQueryToplistRequest::MusicXMQueryToplistRequest().
bool MusicAbstractQueryRequest::m_querySimplify protected
Definition at line 221 of file musicabstractqueryrequest.h.
Referenced by MusicBDQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), and MusicAbstractQueryRequest().
QString MusicAbstractQueryRequest::m_searchQuality protected
Definition at line 218 of file musicabstractqueryrequest.h.
Referenced by MusicBDQueryArtistRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicAbstractQueryRequest(), MusicXMQueryRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicBDQueryRequest::singleDownLoadFinished(), and MusicKGQueryRequest::singleDownLoadFinished().
QString MusicAbstractQueryRequest::m_searchText protected
Definition at line 218 of file musicabstractqueryrequest.h.
Referenced by MusicMVRadioCategoryRequest::downLoadFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKWQueryArtistRequest::getDownLoadIntro(), MusicBDQueryArtistRequest::getDownLoadIntro(), MusicXMQueryArtistRequest::getDownLoadIntro(), MusicKGQueryArtistRequest::getDownLoadIntro(), MusicWYQueryArtistRequest::getDownLoadIntro(), MusicQQQueryArtistRequest::getDownLoadIntro(), MusicAbstractMVRadioRequest::MusicAbstractMVRadioRequest(), MusicWYQueryMovieRequest::pageDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicBDQueryMovieRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::singleDownLoadFinished(), MusicXMQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryArtistListRequest::startToPage(), MusicXMQueryArtistListRequest::startToPage(), MusicQQQueryArtistListRequest::startToPage(), MusicBDQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicXMQueryMovieRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicXMQueryPlaylistRequest::startToPage(), MusicXMQueryRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicBDQueryPlaylistRequest::startToPage(), MusicBDQueryMovieRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicBDQueryRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicAbstractMVRadioRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicBDQueryPlaylistRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicXMQueryAlbumRequest::startToSearch(), MusicXMQueryArtistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicKGQueryAlbumRequest::startToSearch(), MusicXMQueryPlaylistRequest::startToSearch(), MusicXMQueryMovieRequest::startToSearch(), MusicBDQueryArtistRequest::startToSearch(), MusicKGQueryArtistRequest::startToSearch(), MusicXMQueryRequest::startToSearch(), MusicQQQueryRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicQQQueryPlaylistRequest::startToSearch(), MusicBDQueryRequest::startToSearch(), MusicWYQueryRequest::startToSearch(), MusicBDQueryRecommendRequest::startToSearch(), MusicBDQueryMovieRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicKGQueryRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicXMQueryArtistListRequest::startToSearch(), MusicKWQueryArtistListRequest::startToSearch(), MusicBDQueryArtistListRequest::startToSearch(), MusicKGQueryArtistListRequest::startToSearch(), MusicQQQueryArtistListRequest::startToSearch(), MusicQueryMovieRequest::startToSearch(), MusicWYQueryArtistListRequest::startToSearch(), MusicKWQueryRequest::startToSearch(), MusicQQQueryArtistRequest::startToSearch(), MusicKWQueryMovieRequest::startToSingleSearch(), MusicQQQueryMovieRequest::startToSingleSearch(), MusicKGQueryMovieRequest::startToSingleSearch(), MusicBDQueryMovieRequest::startToSingleSearch(), MusicXMQueryMovieRequest::startToSingleSearch(), and MusicWYQueryMovieRequest::startToSingleSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicabstractqueryrequest.h
TTKModule/TTKCore/musicNetworkKits/musicabstractqueryrequest.cpp