TTKMusicPlayer: QDlnaXml Class Reference
QDlnaXml Class Reference
The class of the dlna xml.
#include <qdlnaxml.h>
Public Member Functions
QDlnaXml ()
bool fromString (const QString &data)
QString toString () const
QString tagNameToLower (const QString &data) const
QString readTagNameValue (const QString &tagName) const
QDlnaService readServiceTag (const QString &type, const QString &tagName) const
Detailed Description
The class of the dlna xml.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file qdlnaxml.h.
Constructor & Destructor Documentation
QDlnaXml::QDlnaXml ()
Definition at line 31 of file qdlnaxml.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
bool QDlnaXml::fromString (const QString & data)
Definition at line 36 of file qdlnaxml.cpp.
References TTK_D.
Referenced by QDlnaClientPrivate::connectServer().
QDlnaService QDlnaXml::readServiceTag (const QString & type, const QString & tagName) const
Definition at line 86 of file qdlnaxml.cpp.
References QDlnaService::m_controlURL, QDlnaService::m_eventSubURL, QDlnaService::m_scpdURL, QDlnaService::m_serviceID, QDlnaService::m_serviceType, TTK_D, and TTK_SEPARATOR.
Referenced by QDlnaClientPrivate::connectServer().
QString QDlnaXml::readTagNameValue (const QString & tagName) const
Definition at line 75 of file qdlnaxml.cpp.
References TTK_D.
Referenced by QDlnaClientPrivate::connectServer().
QString QDlnaXml::tagNameToLower (const QString & data) const
Definition at line 56 of file qdlnaxml.cpp.
Referenced by QDlnaClientPrivate::connectServer().
QString QDlnaXml::toString () const
Definition at line 46 of file qdlnaxml.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/qdlnaxml.h
TTKThirdParty/TTKExtras/qdlna/qdlnaxml.cpp