TTKMusicPlayer: MusicBarrageWidget Class Reference
MusicBarrageWidget Class Reference
The class of the barrage widget.
#include <musicbarragewidget.h>
Public Slots
void barrageStateChanged (bool on)
void addBarrage (const MusicBarrageRecord &record)
Public Member Functions
MusicBarrageWidget (QObject *parent=nullptr)
~MusicBarrageWidget ()
void start ()
void pause ()
void stop ()
void setSize (const QSize &size)
void setBarrage (const QString &name, const QString &id)
Private Slots
void sizeChanged ()
void downLoadFinished (const QByteArray &bytes)
Private Member Functions
void clearItems ()
void createLabel ()
void clearBarrages ()
QLabel * createLabel (const MusicBarrageRecord &record)
void createAnimation ()
void createAnimation (QLabel *label)
Private Attributes
bool m_state
QSize m_parentSize
QWidget * m_parent
QTimer * m_sizeTimer
QString m_lastQueryID
QList< QLabel * > m_labels
QList< MusicBarrageAnimation * > m_animations
MusicBarrageRecordList m_barrageRecords
MusicBarrageRequest * m_networkRequest
Detailed Description
The class of the barrage widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 68 of file musicbarragewidget.h.
Constructor & Destructor Documentation
MusicBarrageWidget::MusicBarrageWidget (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 41 of file musicbarragewidget.cpp.
References downLoadFinished(), m_networkRequest, m_sizeTimer, sizeChanged(), and TTK_DN_S2MS.
MusicBarrageWidget::~MusicBarrageWidget ()
Object destructor.
Definition at line 56 of file musicbarragewidget.cpp.
References clearItems(), m_networkRequest, and m_sizeTimer.
Member Function Documentation
void MusicBarrageWidget::addBarrage (const MusicBarrageRecord & record) slot
Add barrage record.
Definition at line 136 of file musicbarragewidget.cpp.
References createAnimation(), createLabel(), TTK::initRandom(), m_barrageRecords, m_state, and start().
Referenced by downLoadFinished().
void MusicBarrageWidget::barrageStateChanged (bool on) slot
Set current barrage animation on or not.
Definition at line 120 of file musicbarragewidget.cpp.
References clearItems(), createAnimation(), createLabel(), m_barrageRecords, m_state, start(), and stop().
void MusicBarrageWidget::clearBarrages () private
Clear all barrage.
Definition at line 231 of file musicbarragewidget.cpp.
References clearItems(), and m_barrageRecords.
Referenced by setBarrage().
void MusicBarrageWidget::clearItems () private
Clear all items.
Definition at line 214 of file musicbarragewidget.cpp.
References m_animations, and m_labels.
Referenced by barrageStateChanged(), clearBarrages(), and ~MusicBarrageWidget().
void MusicBarrageWidget::createAnimation () private
Create barrage animation.
Definition at line 250 of file musicbarragewidget.cpp.
References m_labels, and qAsConst.
Referenced by addBarrage(), and barrageStateChanged().
void MusicBarrageWidget::createAnimation (QLabel * label) private
Create barrage animation by object.
Definition at line 258 of file musicbarragewidget.cpp.
References m_animations, m_parentSize, and MusicBarrageAnimation::setSize().
void MusicBarrageWidget::createLabel () private
Create barrage item label.
Definition at line 222 of file musicbarragewidget.cpp.
References TTK::initRandom(), m_barrageRecords, and qAsConst.
Referenced by addBarrage(), and barrageStateChanged().
QLabel * MusicBarrageWidget::createLabel (const MusicBarrageRecord & record) private
Create barrage item label by object.
Definition at line 237 of file musicbarragewidget.cpp.
References TTK::Widget::fontTextHeight(), TTK::Widget::fontTextWidth(), MusicBarrageRecord::m_color, m_labels, m_parent, MusicBarrageRecord::m_size, MusicBarrageRecord::m_value, and TTK::Widget::setFontSize().
void MusicBarrageWidget::downLoadFinished (const QByteArray & bytes) private slot
Download data from net finished.
Definition at line 160 of file musicbarragewidget.cpp.
References addBarrage(), TTKAbstractXml::fromByteArray(), m_barrageRecords, MusicBarrageRecord::m_color, MusicBarrageRecord::m_size, MusicBarrageRecord::m_value, qAsConst, TTKAbstractXml::readMultiNodeByTagName(), and TTKAbstractXml::toString().
Referenced by MusicBarrageWidget().
void MusicBarrageWidget::pause ()
Pause barrage animation.
Definition at line 78 of file musicbarragewidget.cpp.
References m_animations, m_labels, and m_state.
Referenced by MusicVideoView::play().
void MusicBarrageWidget::setBarrage (const QString & name, const QString & id)
Set barrage play data.
Definition at line 108 of file musicbarragewidget.cpp.
References clearBarrages(), m_lastQueryID, m_networkRequest, and MusicBarrageRequest::startToRequest().
Referenced by MusicVideoView::setBarrage().
void MusicBarrageWidget::setSize (const QSize & size)
Set animation region size.
Definition at line 101 of file musicbarragewidget.cpp.
References m_parentSize, m_sizeTimer, and stop().
Referenced by MusicVideoView::resizeGeometry().
void MusicBarrageWidget::sizeChanged () private slot
Region size changed.
Definition at line 150 of file musicbarragewidget.cpp.
References m_animations, m_parentSize, qAsConst, and start().
Referenced by MusicBarrageWidget().
void MusicBarrageWidget::start ()
Start barrage animation.
Definition at line 64 of file musicbarragewidget.cpp.
References m_animations, m_labels, and m_state.
Referenced by addBarrage(), barrageStateChanged(), MusicVideoView::play(), and sizeChanged().
void MusicBarrageWidget::stop ()
Stop barrage animation.
Definition at line 92 of file musicbarragewidget.cpp.
References m_animations, and m_labels.
Referenced by barrageStateChanged(), setSize(), and MusicVideoView::stop().
Member Data Documentation
QList<MusicBarrageAnimation*> MusicBarrageWidget::m_animations private
Definition at line 156 of file musicbarragewidget.h.
Referenced by clearItems(), createAnimation(), pause(), sizeChanged(), start(), and stop().
MusicBarrageRecordList MusicBarrageWidget::m_barrageRecords private
Definition at line 157 of file musicbarragewidget.h.
Referenced by addBarrage(), barrageStateChanged(), clearBarrages(), createLabel(), and downLoadFinished().
QList<QLabel*> MusicBarrageWidget::m_labels private
Definition at line 155 of file musicbarragewidget.h.
Referenced by clearItems(), createAnimation(), createLabel(), pause(), start(), and stop().
QString MusicBarrageWidget::m_lastQueryID private
Definition at line 154 of file musicbarragewidget.h.
Referenced by setBarrage().
MusicBarrageRequest* MusicBarrageWidget::m_networkRequest private
Definition at line 158 of file musicbarragewidget.h.
Referenced by MusicBarrageWidget(), setBarrage(), and ~MusicBarrageWidget().
QWidget* MusicBarrageWidget::m_parent private
Definition at line 152 of file musicbarragewidget.h.
Referenced by createLabel().
QSize MusicBarrageWidget::m_parentSize private
Definition at line 151 of file musicbarragewidget.h.
Referenced by createAnimation(), setSize(), and sizeChanged().
QTimer* MusicBarrageWidget::m_sizeTimer private
Definition at line 153 of file musicbarragewidget.h.
Referenced by MusicBarrageWidget(), setSize(), and ~MusicBarrageWidget().
bool MusicBarrageWidget::m_state private
Definition at line 150 of file musicbarragewidget.h.
Referenced by addBarrage(), barrageStateChanged(), pause(), and start().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicbarragewidget.h
TTKModule/TTKWidget/musicVideoKits/musicbarragewidget.cpp