TTKMusicPlayer: MusicSpectrumLayoutWidget Class Reference
MusicSpectrumLayoutWidget Class Reference abstract
The class of the music spectrum layout widget.
#include <musicspectrumlayoutwidget.h>
Public Slots
virtual void popupMenu () overridefinal
void labelClicked (int index)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Signals
void stateChanged (bool &state, const QString &name)
Public Member Functions
MusicSpectrumLayoutWidget (QWidget *parent=nullptr)
~MusicSpectrumLayoutWidget ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Types
using SpectrumInfo = QPair< QString, QString >
using SpectrumInfoList = QList< SpectrumInfo >
Protected Member Functions
virtual QStringList spectrumTypeList () const =0
void initialize ()
void addCellItems (const SpectrumInfoList &items)
Protected Attributes
bool m_exclusive
QVBoxLayout * m_containLayout
QList< MusicSpectrumLayoutItem * > m_items
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the music spectrum layout widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 66 of file musicspectrumlayoutwidget.h.
Member Typedef Documentation
using MusicSpectrumLayoutWidget::SpectrumInfo = QPair<QString, QString> protected
Definition at line 97 of file musicspectrumlayoutwidget.h.
using MusicSpectrumLayoutWidget::SpectrumInfoList = QList<SpectrumInfo> protected
Definition at line 98 of file musicspectrumlayoutwidget.h.
Constructor & Destructor Documentation
MusicSpectrumLayoutWidget::MusicSpectrumLayoutWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 44 of file musicspectrumlayoutwidget.cpp.
References initialize().
MusicSpectrumLayoutWidget::~MusicSpectrumLayoutWidget ()
Object destructor.
Definition at line 50 of file musicspectrumlayoutwidget.cpp.
References m_items.
Member Function Documentation
void MusicSpectrumLayoutWidget::addCellItems (const SpectrumInfoList & items) protected
Create cell items by input data.
Definition at line 114 of file musicspectrumlayoutwidget.cpp.
References MusicSpectrumLayoutItem::addCellItem(), labelClicked(), m_containLayout, m_items, and TTKClickedGroup::mapped().
Referenced by MusicSpectrumFloridLayoutWidget::MusicSpectrumFloridLayoutWidget(), MusicSpectrumFlowLayoutWidget::MusicSpectrumFlowLayoutWidget(), MusicSpectrumNormalLayoutWidget::MusicSpectrumNormalLayoutWidget(), MusicSpectrumPlusLayoutWidget::MusicSpectrumPlusLayoutWidget(), and MusicSpectrumWaveLayoutWidget::MusicSpectrumWaveLayoutWidget().
void MusicSpectrumLayoutWidget::initialize () protected
Create all widget in layout.
Definition at line 82 of file musicspectrumlayoutwidget.cpp.
References TTK::UI::BackgroundStyle10, TTK::UI::BorderStyle03, TTK::Widget::generateVScrollAreaFormat(), m_containLayout, MusicToolMenuWidget::m_containWidget, and m_exclusive.
Referenced by MusicSpectrumLayoutWidget().
void MusicSpectrumLayoutWidget::labelClicked (int index) slot
Label selected state changed.
Definition at line 60 of file musicspectrumlayoutwidget.cpp.
References m_exclusive, m_items, MusicToolMenuWidget::m_menu, qAsConst, spectrumTypeList(), and stateChanged().
Referenced by addCellItems().
void MusicSpectrumLayoutWidget::popupMenu () final override virtual slot
To popup menu.
Definition at line 55 of file musicspectrumlayoutwidget.cpp.
References MusicToolMenuWidget::m_containWidget, and MusicToolMenuWidget::m_menu.
virtual QStringList MusicSpectrumLayoutWidget::spectrumTypeList () const protected pure virtual
Spectrum types list.
Implemented in MusicSpectrumFloridLayoutWidget, MusicSpectrumWaveLayoutWidget, MusicSpectrumFlowLayoutWidget, MusicSpectrumPlusLayoutWidget, and MusicSpectrumNormalLayoutWidget.
Referenced by labelClicked().
void MusicSpectrumLayoutWidget::stateChanged (bool & state, const QString & name) signal
Spectrum item check state changed.
Referenced by labelClicked().
Member Data Documentation
QVBoxLayout* MusicSpectrumLayoutWidget::m_containLayout protected
Definition at line 115 of file musicspectrumlayoutwidget.h.
Referenced by addCellItems(), and initialize().
bool MusicSpectrumLayoutWidget::m_exclusive protected
Definition at line 114 of file musicspectrumlayoutwidget.h.
Referenced by initialize(), labelClicked(), MusicSpectrumFloridLayoutWidget::MusicSpectrumFloridLayoutWidget(), and MusicSpectrumFlowLayoutWidget::MusicSpectrumFlowLayoutWidget().
QList<MusicSpectrumLayoutItem*> MusicSpectrumLayoutWidget::m_items protected
Definition at line 116 of file musicspectrumlayoutwidget.h.
Referenced by addCellItems(), labelClicked(), and ~MusicSpectrumLayoutWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicspectrumlayoutwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicspectrumlayoutwidget.cpp