TTKMusicplayer: MusicWebMusicRadioPlayWidget Class Reference
MusicWebMusicRadioPlayWidget Class Reference
The class of the web music radio widget.
#include <musicwebmusicradioplaywidget.h>
Public Slots
void mediaAutionPlayError (int code)
void radioPlay ()
void radioPrevious ()
void radioNext ()
void radioVolume (int num)
void radioResourceDownload ()
void getPlaylistFinished ()
void getSongInfoFinished ()
void lrcDownloadStateChanged ()
void picDownloadStateChanged ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicWebMusicRadioPlayWidget (QWidget *parent=nullptr)
virtual ~MusicWebMusicRadioPlayWidget ()
void setNetworkCookie (QNetworkCookieJar *jar)
void updateRadioList (const QString &category)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
void createCoreModule ()
void startToPlay ()
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicWebMusicRadioPlayWidget * m_ui
int m_currentPlaylistIndex
bool m_isPlaying
MusicLrcAnalysis * m_analysis
MusicCoreMPlayer * m_mediaPlayer
MusicRadioPlaylistThread * m_playListThread
MusicRadioSongsThread * m_songsThread
QStringList m_playListIds
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the web music radio widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicwebmusicradioplaywidget.h.
Constructor & Destructor Documentation
MusicWebMusicRadioPlayWidget::MusicWebMusicRadioPlayWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 16 of file musicwebmusicradioplaywidget.cpp.
References createCoreModule(), m_analysis, m_currentPlaylistIndex, m_isPlaying, m_ui, MusicUIObject::MBackgroundStyle01, MusicUIObject::MKGBtnMore, MusicUIObject::MKGBtnUnDownload, MusicUIObject::MSliderStyle10, MusicUIObject::MToolButtonStyle04, radioNext(), radioPlay(), radioPrevious(), radioResourceDownload(), radioVolume(), and MusicLrcAnalysis::setLineMax().
MusicWebMusicRadioPlayWidget::~MusicWebMusicRadioPlayWidget () virtual
Definition at line 73 of file musicwebmusicradioplaywidget.cpp.
References m_analysis, m_mediaPlayer, m_playListThread, m_songsThread, and m_ui.
Member Function Documentation
void MusicWebMusicRadioPlayWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 82 of file musicwebmusicradioplaywidget.cpp.
References m_mediaPlayer.
void MusicWebMusicRadioPlayWidget::createCoreModule () protected
Create core module.
Definition at line 220 of file musicwebmusicradioplaywidget.cpp.
References durationChanged(), m_mediaPlayer, mediaAutionPlayError(), and positionChanged().
Referenced by MusicWebMusicRadioPlayWidget(), and startToPlay().
void MusicWebMusicRadioPlayWidget::durationChanged (qint64 duration) slot
Current duration changed.
Definition at line 360 of file musicwebmusicradioplaywidget.cpp.
References m_mediaPlayer, m_ui, MusicTime::msecTime2LabelJustified(), and MT_S2MS.
Referenced by createCoreModule().
void MusicWebMusicRadioPlayWidget::getPlaylistFinished () slot
Get playList finished.
Definition at line 204 of file musicwebmusicradioplaywidget.cpp.
References MusicRadioPlaylistThread::getMusicPlaylist(), m_currentPlaylistIndex, m_playListIds, m_playListThread, m_songsThread, and MusicRadioSongsThread::startToDownload().
Referenced by setNetworkCookie().
void MusicWebMusicRadioPlayWidget::getSongInfoFinished () slot
Get song information finished.
Definition at line 214 of file musicwebmusicradioplaywidget.cpp.
References m_isPlaying, and startToPlay().
Referenced by setNetworkCookie().
void MusicWebMusicRadioPlayWidget::lrcDownloadStateChanged () slot
Lrc download state changed.
Definition at line 279 of file musicwebmusicradioplaywidget.cpp.
References MusicRadioSongsThread::getMusicSongInfo(), LRC_FILE, MusicUtils::String::lrcPrefix(), m_analysis, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, m_songsThread, m_ui, name, and MusicLrcAnalysis::transLrcFileToTime().
Referenced by startToPlay().
void MusicWebMusicRadioPlayWidget::mediaAutionPlayError (int code) slot
Media aution play error.
Definition at line 108 of file musicwebmusicradioplaywidget.cpp.
References DEFAULT_LEVEL_NORMAL, and radioNext().
Referenced by createCoreModule().
void MusicWebMusicRadioPlayWidget::picDownloadStateChanged () slot
Small pic download state changed.
Definition at line 297 of file musicwebmusicradioplaywidget.cpp.
References ART_DIR_FULL, MusicRadioSongsThread::getMusicSongInfo(), MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, m_songsThread, m_ui, MusicUtils::Widget::pixmapToRound(), and SKN_FILE.
Referenced by startToPlay().
void MusicWebMusicRadioPlayWidget::positionChanged (qint64 position) slot
Current position changed.
Definition at line 320 of file musicwebmusicradioplaywidget.cpp.
References MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), MusicLrcAnalysis::isEmpty(), m_analysis, m_mediaPlayer, m_ui, MusicTime::msecTime2LabelJustified(), MT_S2MS, and MusicLrcAnalysis::setCurrentIndex().
Referenced by createCoreModule().
void MusicWebMusicRadioPlayWidget::radioNext () slot
Set radio to next.
Definition at line 153 of file musicwebmusicradioplaywidget.cpp.
References m_currentPlaylistIndex, m_isPlaying, m_playListIds, m_songsThread, m_ui, and MusicRadioSongsThread::startToDownload().
Referenced by mediaAutionPlayError(), and MusicWebMusicRadioPlayWidget().
void MusicWebMusicRadioPlayWidget::radioPlay () slot
Set radio to play.
Definition at line 116 of file musicwebmusicradioplaywidget.cpp.
References m_isPlaying, m_mediaPlayer, m_ui, and MusicCoreMPlayer::play().
Referenced by MusicWebMusicRadioPlayWidget().
void MusicWebMusicRadioPlayWidget::radioPrevious () slot
Set radio to previous.
Definition at line 128 of file musicwebmusicradioplaywidget.cpp.
References m_currentPlaylistIndex, m_isPlaying, m_playListIds, m_songsThread, m_ui, and MusicRadioSongsThread::startToDownload().
Referenced by MusicWebMusicRadioPlayWidget().
void MusicWebMusicRadioPlayWidget::radioResourceDownload () slot
Radio resource download.
Definition at line 186 of file musicwebmusicradioplaywidget.cpp.
References MusicRadioSongsThread::getMusicSongInfo(), MusicObject::MusicSongInformation::m_songAttrs, m_songsThread, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownloadWidget::setSongName(), and MusicDownloadWidget::show().
Referenced by MusicWebMusicRadioPlayWidget().
void MusicWebMusicRadioPlayWidget::radioVolume (int num) slot
Set radio volume.
Definition at line 178 of file musicwebmusicradioplaywidget.cpp.
References m_mediaPlayer, and MusicCoreMPlayer::setVolume().
Referenced by MusicWebMusicRadioPlayWidget().
void MusicWebMusicRadioPlayWidget::setNetworkCookie (QNetworkCookieJar * jar)
Set network cookie.
Definition at line 89 of file musicwebmusicradioplaywidget.cpp.
References getPlaylistFinished(), getSongInfoFinished(), m_playListThread, and m_songsThread.
Referenced by MusicWebMusicRadioWidget::itemCellDoubleClicked().
void MusicWebMusicRadioPlayWidget::show () slot
Override show function.
Definition at line 369 of file musicwebmusicradioplaywidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Referenced by MusicWebMusicRadioWidget::itemCellDoubleClicked().
void MusicWebMusicRadioPlayWidget::startToPlay () protected
Start to play music radio.
fix current play volume temporary
Definition at line 228 of file musicwebmusicradioplaywidget.cpp.
References ART_DIR_FULL, createCoreModule(), MusicObject::DownloadLrc, MusicObject::DownloadSmallBackground, MusicRadioSongsThread::getMusicSongInfo(), LRC_FILE, lrcDownloadStateChanged(), MusicUtils::String::lrcPrefix(), MusicObject::MusicSongInformation::m_lrcUrl, m_mediaPlayer, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, m_songsThread, m_ui, MusicCoreMPlayer::MusicCategory, name, picDownloadStateChanged(), MusicCoreMPlayer::play(), MusicCoreMPlayer::setMedia(), SKN_FILE, MusicTextDownLoadThread::startToDownload(), and MusicDataDownloadThread::startToDownload().
Referenced by getSongInfoFinished().
void MusicWebMusicRadioPlayWidget::updateRadioList (const QString & category)
Update radio list by given category.
Definition at line 100 of file musicwebmusicradioplaywidget.cpp.
References m_playListThread, and MusicRadioPlaylistThread::startToDownload().
Referenced by MusicWebMusicRadioWidget::itemCellDoubleClicked().
Member Data Documentation
MusicLrcAnalysis* MusicWebMusicRadioPlayWidget::m_analysis protected
Definition at line 130 of file musicwebmusicradioplaywidget.h.
Referenced by lrcDownloadStateChanged(), MusicWebMusicRadioPlayWidget(), positionChanged(), and ~MusicWebMusicRadioPlayWidget().
int MusicWebMusicRadioPlayWidget::m_currentPlaylistIndex protected
Definition at line 128 of file musicwebmusicradioplaywidget.h.
Referenced by getPlaylistFinished(), MusicWebMusicRadioPlayWidget(), radioNext(), and radioPrevious().
bool MusicWebMusicRadioPlayWidget::m_isPlaying protected
Definition at line 129 of file musicwebmusicradioplaywidget.h.
Referenced by getSongInfoFinished(), MusicWebMusicRadioPlayWidget(), radioNext(), radioPlay(), and radioPrevious().
MusicCoreMPlayer* MusicWebMusicRadioPlayWidget::m_mediaPlayer protected
Definition at line 131 of file musicwebmusicradioplaywidget.h.
Referenced by closeEvent(), createCoreModule(), durationChanged(), positionChanged(), radioPlay(), radioVolume(), startToPlay(), and ~MusicWebMusicRadioPlayWidget().
QStringList MusicWebMusicRadioPlayWidget::m_playListIds protected
Definition at line 134 of file musicwebmusicradioplaywidget.h.
Referenced by getPlaylistFinished(), radioNext(), and radioPrevious().
MusicRadioPlaylistThread* MusicWebMusicRadioPlayWidget::m_playListThread protected
Definition at line 132 of file musicwebmusicradioplaywidget.h.
Referenced by getPlaylistFinished(), setNetworkCookie(), updateRadioList(), and ~MusicWebMusicRadioPlayWidget().
MusicRadioSongsThread* MusicWebMusicRadioPlayWidget::m_songsThread protected
Definition at line 133 of file musicwebmusicradioplaywidget.h.
Referenced by getPlaylistFinished(), lrcDownloadStateChanged(), picDownloadStateChanged(), radioNext(), radioPrevious(), radioResourceDownload(), setNetworkCookie(), startToPlay(), and ~MusicWebMusicRadioPlayWidget().
Ui::MusicWebMusicRadioPlayWidget* MusicWebMusicRadioPlayWidget::m_ui protected
Definition at line 127 of file musicwebmusicradioplaywidget.h.
Referenced by durationChanged(), lrcDownloadStateChanged(), MusicWebMusicRadioPlayWidget(), picDownloadStateChanged(), positionChanged(), radioNext(), radioPlay(), radioPrevious(), show(), startToPlay(), and ~MusicWebMusicRadioPlayWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmusicradioplaywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmusicradioplaywidget.cpp