TTKMusicPlayer: TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryinterface.cpp File Reference
musickwqueryinterface.cpp File Reference
#include "musickwqueryinterface.h"
#include "musicunityqueryinterface.h"
#include "qalgorithm/deswrapper.h"
Functions
static void parseSongPropertyV1 (TTK::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
static void parseSongPropertyV2 (TTK::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
static void parseSongPropertyV3 (TTK::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
static void parseSongPropertyUnity (TTK::MusicSongInformation *info, const QString &format, int bitrate)
static void parseSongProperty (TTK::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
Variables
static constexpr const char * KW_SONG_PATH_V1_URL = "eVZwd0d3aGhUSmNoNHBHZTFFYldyOGZjY0trcldsMlphUWtNL0thR3AyTjRkU0xyZGJuSlBGQTBueURhaDM3bTVrNUE5S0I5dWpjcWRHeTNaanJPUXc1YkNOQm9pNlJrbVFFTWI3YVdpcFFWS2tUSGNoSk5RUDl3WDhSZlZaUzd2TnRpaDBTS0psbVE0Tmk5YlJHQXdtY2tGaGlERmU4RnFXSGVZdWFWeGo4dUFpbm4zWUJTemlFYVhkREM0Q0pSNytUK05VYlBVcUdVRnhLSUJ3TXg3ZEc2UzBxVGVMOFZqdnJJN1E9PQ=="
static constexpr const char * KW_SONG_PATH_V2_URL = "VlpjeWIxQkZNbDdkNHA3eUFRMHVnNmVVanpITWJ6MEp1T1ZraElNc2JXaGIvVytMcmFNZVFKNEQ2UXRrcHZyV2dXTjJqQT09"
static constexpr const char * KW_SONG_PATH_V2_DATA_URL = "NUVnZE5SbWFmNHRGemdTeHd6RHlwYjF2TllaR1R5TkNKRUt6NWpxcDVEcW9JdkREN0QzRmNGOVM0R0lQK29wTTZwaHBHa3FkR3dWbEx6M3ZHVnZBM1NseWF1eUoyN0wwZmQwT3BJaXFzbWcraDlISnAyVnN0VTdGT3ZxZWlicVFGcjFkYWc3QlJ0czlGdFVrTW1WeTd3U1c1S0wwQjRrNDM0S0EySU9pOVg4QmVYSW5GUUIwWWcwMlM5Sng2YVIvYmpYL0xib2NnRlFLV3A2aXBJMWxEalNMNVpnPQ=="
static constexpr const char * KW_SONG_PATH_V3_URL = "UElteEluQm8zUnRXTERvMkkwYTVhNitEUG9rRVA0Wk80VFFOb3dKL1ZsNldLc1RDVFJQZ3llaTN1MXhzL3NSM3ovaVhTTld5L1NpTE9hdTlBM3NuNjBQbWpOTT0="
static constexpr const char * KW_ALBUM_COVER_URL = "NkhRaDluWTFxV2wvTEl6ZkszRmRUa1MvS0JlQUl6MDJVUkpqcjFnYzJ4djZ0b0xmcjhzZHJnV0xscW89"
static constexpr const char * KW_ARTIST_COVER_URL = "YW4xU3FFQnprWG11R0J5QjVGREFHdy9Yd0w3dEZZcFJIWm5FMXQ5QkJJN0EzQTd4TnBwR1BQZ0d5Qzg9"
Function Documentation
static void parseSongProperty (TTK::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) static
Definition at line 280 of file musickwqueryinterface.cpp.
References MusicSettingManager::DownloadServerPriority, G_SETTING_PTR, parseSongPropertyUnity(), parseSongPropertyV1(), parseSongPropertyV2(), and parseSongPropertyV3().
Referenced by ReqKWInterface::parseFromSongProperty().
static void parseSongPropertyUnity (TTK::MusicSongInformation * info, const QString & format, int bitrate) static
Definition at line 260 of file musickwqueryinterface.cpp.
References TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, ReqUnityInterface::parseFromSongProperty(), qAsConst, QUERY_KW_INTERFACE, TTK_BN_1000, TTK_BN_128, TTK_BN_320, and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV1 (TTK::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) static
Definition at line 52 of file musickwqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), KW_SONG_PATH_V1_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqKWInterface::makeRequestRawHeader(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::String::suffix(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), TTK_BN_1000, TTK_BN_128, TTK_BN_192, TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV2 (TTK::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) static
Definition at line 123 of file musickwqueryinterface.cpp.
References TTKRegularExpression::captured(), QAlgorithm::Des::encrypt(), TTK::MusicSongProperty::isEmpty(), KW_SONG_PATH_V2_DATA_URL, KW_SONG_PATH_V2_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqKWInterface::makeRequestRawHeader(), TTKRegularExpression::match(), TTK::Algorithm::mdII(), MDII_SHR_KEY, qAsConst, TTK::String::suffix(), TTK::syncNetworkQueryForGet(), TTK_BN_1000, TTK_BN_128, TTK_BN_192, TTK_BN_320, TTK_DEFAULT_STR, and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV3 (TTK::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate) static
Definition at line 193 of file musickwqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), KW_SONG_PATH_V3_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqKWInterface::makeRequestRawHeader(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::String::suffix(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), TTK_BN_1000, TTK_BN_128, TTK_BN_192, TTK_BN_320, and TTK_INFO_STREAM.
Referenced by parseSongProperty().
Variable Documentation
constexpr const char* KW_ALBUM_COVER_URL = "NkhRaDluWTFxV2wvTEl6ZkszRmRUa1MvS0JlQUl6MDJVUkpqcjFnYzJ4djZ0b0xmcjhzZHJnV0xscW89" static
Definition at line 10 of file musickwqueryinterface.cpp.
Referenced by ReqKWInterface::makeCoverPixmapUrl().
constexpr const char* KW_ARTIST_COVER_URL = "YW4xU3FFQnprWG11R0J5QjVGREFHdy9Yd0w3dEZZcFJIWm5FMXQ5QkJJN0EzQTd4TnBwR1BQZ0d5Qzg9" static
Definition at line 11 of file musickwqueryinterface.cpp.
Referenced by ReqKWInterface::makeArtistPixmapUrl().
constexpr const char* KW_SONG_PATH_V1_URL = "eVZwd0d3aGhUSmNoNHBHZTFFYldyOGZjY0trcldsMlphUWtNL0thR3AyTjRkU0xyZGJuSlBGQTBueURhaDM3bTVrNUE5S0I5dWpjcWRHeTNaanJPUXc1YkNOQm9pNlJrbVFFTWI3YVdpcFFWS2tUSGNoSk5RUDl3WDhSZlZaUzd2TnRpaDBTS0psbVE0Tmk5YlJHQXdtY2tGaGlERmU4RnFXSGVZdWFWeGo4dUFpbm4zWUJTemlFYVhkREM0Q0pSNytUK05VYlBVcUdVRnhLSUJ3TXg3ZEc2UzBxVGVMOFZqdnJJN1E9PQ==" static
Definition at line 6 of file musickwqueryinterface.cpp.
Referenced by parseSongPropertyV1().
constexpr const char* KW_SONG_PATH_V2_DATA_URL = "NUVnZE5SbWFmNHRGemdTeHd6RHlwYjF2TllaR1R5TkNKRUt6NWpxcDVEcW9JdkREN0QzRmNGOVM0R0lQK29wTTZwaHBHa3FkR3dWbEx6M3ZHVnZBM1NseWF1eUoyN0wwZmQwT3BJaXFzbWcraDlISnAyVnN0VTdGT3ZxZWlicVFGcjFkYWc3QlJ0czlGdFVrTW1WeTd3U1c1S0wwQjRrNDM0S0EySU9pOVg4QmVYSW5GUUIwWWcwMlM5Sng2YVIvYmpYL0xib2NnRlFLV3A2aXBJMWxEalNMNVpnPQ==" static
Definition at line 8 of file musickwqueryinterface.cpp.
Referenced by parseSongPropertyV2().
constexpr const char* KW_SONG_PATH_V2_URL = "VlpjeWIxQkZNbDdkNHA3eUFRMHVnNmVVanpITWJ6MEp1T1ZraElNc2JXaGIvVytMcmFNZVFKNEQ2UXRrcHZyV2dXTjJqQT09" static
Definition at line 7 of file musickwqueryinterface.cpp.
Referenced by parseSongPropertyV2().
constexpr const char* KW_SONG_PATH_V3_URL = "UElteEluQm8zUnRXTERvMkkwYTVhNitEUG9rRVA0Wk80VFFOb3dKL1ZsNldLc1RDVFJQZ3llaTN1MXhzL3NSM3ovaVhTTld5L1NpTE9hdTlBM3NuNjBQbWpOTT0=" static
Definition at line 9 of file musickwqueryinterface.cpp.
Referenced by parseSongPropertyV3().