TTKMusicplayer: MusicBDQueryInterface Class Reference
MusicBDQueryInterface Class Reference
The class to baidu query interface.
#include <musicbdqueryinterface.h>
Public Member Functions
void makeTokenQueryUrl (QNetworkRequest *request, const QString &id)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &bit)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicPayAttribute (MusicObject::MusicSongInformation *info)
Detailed Description
The class to baidu query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 74 of file musicbdqueryinterface.h.
Member Function Documentation
void MusicBDQueryInterface::makeTokenQueryUrl (QNetworkRequest * request, const QString & id)
Make token query url string.
Definition at line 15 of file musicbdqueryinterface.cpp.
References ALG_UA_KEY, BD_SONG_INFO_DATA_URL, BD_SONG_INFO_URL, BD_UA_URL, key, MusicUtils::Algorithm::mdII(), MusicObject::setSslConfiguration(), MusicTime::timestamp(), MusicUtils::Codec::toUtf8(), and MusicUtils::Url::urlEncode().
Referenced by readFromMusicSongAttribute(), and MusicBDQueryRequest::startToSingleSearch().
void MusicBDQueryInterface::readFromMusicLLAttribute (MusicObject::MusicSongInformation * info)
Read tags(size) from query results.
Definition at line 141 of file musicbdqueryinterface.cpp.
References ALG_UA_KEY, BD_SONG_DETAIL_URL, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_duration, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkError, QJson::Parser::parse(), MusicObject::setSslConfiguration(), MusicUtils::Number::size2Label(), MusicUtils::Codec::toUtf8(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by readFromMusicSongAttribute().
void MusicBDQueryInterface::readFromMusicPayAttribute (MusicObject::MusicSongInformation * info)
Read tags(size) from query results.
Definition at line 202 of file musicbdqueryinterface.cpp.
References ALG_UA_KEY, BD_LISTEN_STRING, BD_PREFIX_STRING, BD_SONG_PATH_URL, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QJson::Parser::parse(), MusicObject::setSslConfiguration(), MusicUtils::Number::size2Label(), MusicUtils::Codec::toUtf8(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by readFromMusicSongAttribute().
void MusicBDQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & bit)
Read tags(size) from query results.
Definition at line 27 of file musicbdqueryinterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_duration, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, makeTokenQueryUrl(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkError, QJson::Parser::parse(), readFromMusicPayAttribute(), MusicUtils::Number::size2Label(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by MusicBDQueryArtistRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicBDQueryRequest::downLoadFinished(), MusicBDQueryPlaylistRequest::getDetailsFinished(), readFromMusicSongAttribute(), and MusicBDQueryRequest::singleDownLoadFinished().
void MusicBDQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & format, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 96 of file musicbdqueryinterface.cpp.
References FLC_FILE_PREFIX, MB_128, MB_192, MB_320, MB_64, readFromMusicLLAttribute(), readFromMusicSongAttribute(), and MusicUtils::Number::transfromBitrateToNormal().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdqueryinterface.cpp