TTKMusicPlayer: MusicPlaylist::Shuffle Class Reference
MusicPlaylist::Shuffle Class Reference
Public Member Functions
Shuffle () noexcept
void setEnabled (bool enable) noexcept
bool isEnabled () const noexcept
void initialize (const MusicPlayItemList &items) noexcept
void setCurrentIndex (const MusicPlayItem &item) noexcept
MusicPlayItem setCurrentIndex (int index) noexcept
Private Attributes
int m_index
bool m_enable
MusicPlayItemList m_data
Detailed Description
Definition at line 201 of file musicplaylist.h.
Constructor & Destructor Documentation
MusicPlaylist::Shuffle::Shuffle () noexcept
Object constructor.
Definition at line 6 of file musicplaylist.cpp.
Member Function Documentation
void MusicPlaylist::Shuffle::initialize (const MusicPlayItemList & items) noexcept
Init parameter.
Definition at line 22 of file musicplaylist.cpp.
Referenced by MusicPlaylist::setCurrentIndex().
bool MusicPlaylist::Shuffle::isEnabled () const noexcept
Get shuffle enable or disable.
Definition at line 17 of file musicplaylist.cpp.
Referenced by MusicPlaylist::setCurrentIndex().
void MusicPlaylist::Shuffle::setCurrentIndex (const MusicPlayItem & item) noexcept
Set current play index.
Definition at line 32 of file musicplaylist.cpp.
Referenced by MusicPlaylist::setCurrentIndex().
MusicPlayItem MusicPlaylist::Shuffle::setCurrentIndex (int index) noexcept
Set current play index.
Definition at line 37 of file musicplaylist.cpp.
References PLAY_NEXT_LEVEL, PLAY_PREVIOUS_LEVEL, and TTK_LOW_LEVEL.
void MusicPlaylist::Shuffle::setEnabled (bool enable) noexcept
Set shuffle enable or disable.
Definition at line 12 of file musicplaylist.cpp.
Member Data Documentation
MusicPlayItemList MusicPlaylist::Shuffle::m_data private
Definition at line 233 of file musicplaylist.h.
bool MusicPlaylist::Shuffle::m_enable private
Definition at line 232 of file musicplaylist.h.
int MusicPlaylist::Shuffle::m_index private
Definition at line 231 of file musicplaylist.h.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicplaylist.h
TTKModule/TTKCore/musicCoreKits/musicplaylist.cpp