TTKMusicPlayer: MusicPlaylistBackupModule Class Reference
MusicPlaylistBackupModule Class Reference
The class of the playlist backup module.
#include <musicbackupmodule.h>
Public Slots
virtual void runBackup () overridefinal
Public Slots inherited from MusicAbstractBackup
virtual void runBackup ()=0
Public Member Functions
MusicPlaylistBackupModule (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractBackup
MusicAbstractBackup (int interval, QObject *parent=nullptr)
void start ()
void stop ()
Detailed Description
The class of the playlist backup module.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 61 of file musicbackupmodule.h.
Constructor & Destructor Documentation
MusicPlaylistBackupModule::MusicPlaylistBackupModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 26 of file musicbackupmodule.cpp.
Member Function Documentation
void MusicPlaylistBackupModule::runBackup () final override virtual slot
Backup timeout.
Definition at line 32 of file musicbackupmodule.cpp.
References APPBACKUP_DIR_FULL, TTKDateTime::currentTimestamp(), MusicSongsContainerWidget::instance(), TTKAbstractXml::load(), TTK::File::removeRecursively(), TKF_FILE, TTK_DATE_FORMAT, and MusicTKPLConfigManager::writeBuffer().
Referenced by MusicPlaylistBackupWidget::initialize().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicbackupmodule.h
TTKModule/TTKCore/musicToolsSetsKits/musicbackupmodule.cpp