TTKMusicplayer: TTKLocalPeer Class Reference
TTKLocalPeer Class Reference
The class of the ttk local peer.
#include <ttklocalpeer.h>
Signals
void messageReceived (const QString &message)
Public Member Functions
TTKLocalPeer (QObject *parent=nullptr, const QString &appId=QString())
bool isClient () const
bool sendMessage (const QString &message, int timeout) const
QString applicationId () const
Protected Slots
void receiveConnection ()
Detailed Description
The class of the ttk local peer.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttklocalpeer.h.
Constructor & Destructor Documentation
TTKLocalPeer::TTKLocalPeer (QObject * parent = nullptr, const QString & appId = QString()) explicit
Object contsructor.
Definition at line 61 of file ttklocalpeer.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
QString TTKLocalPeer::applicationId () const
Get current server id.
Definition at line 184 of file ttklocalpeer.cpp.
References TTK_D.
bool TTKLocalPeer::isClient () const
Current client is running or not.
Definition at line 105 of file ttklocalpeer.cpp.
References qPrintable, receiveConnection(), TTK_D, TTK_LOGGER_WARN, and TTKLockedPrivate::TTKLockedFile::WriteLock.
Referenced by sendMessage().
void TTKLocalPeer::messageReceived (const QString & message) signal
Emit when the current message received.
Referenced by receiveConnection().
void TTKLocalPeer::receiveConnection () protected slot
Current message received.
Definition at line 190 of file ttklocalpeer.cpp.
References messageReceived(), TTK_D, and TTK_LOGGER_WARN.
Referenced by isClient().
bool TTKLocalPeer::sendMessage (const QString & message, int timeout) const
Send current message when the client in.
Definition at line 136 of file ttklocalpeer.cpp.
References isClient(), and TTK_D.
The documentation for this class was generated from the following files:
TTKRun/TTKApp/ttklocalpeer.h
TTKRun/TTKApp/ttklocalpeer.cpp