TTKMusicPlayer: TTKAbstractTableWidget Class Reference
TTKAbstractTableWidget Class Reference
The class of the ttk abstract table widget.
#include <ttkabstracttablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Protected Member Functions
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the ttk abstract table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttkabstracttablewidget.h.
Constructor & Destructor Documentation
TTKAbstractTableWidget::TTKAbstractTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file ttkabstracttablewidget.cpp.
References itemCellClicked(), and itemCellEntered().
TTKAbstractTableWidget::~TTKAbstractTableWidget ()
Object destructor.
Definition at line 47 of file ttkabstracttablewidget.cpp.
Member Function Documentation
bool TTKAbstractTableWidget::isValid () const inline protected
Check item row is valid or not.
Definition at line 77 of file ttkabstracttablewidget.h.
Referenced by MusicWebMVRadioInfoTableWidget::actionChanged(), MusicSongSearchTableWidget::addSearchMusicToPlaylist(), MusicItemQueryTableWidget::addSearchMusicToPlaylist(), MusicWebMVRadioInfoTableWidget::contextMenuEvent(), MusicItemQueryTableWidget::contextMenuEvent(), MusicItemSearchTableWidget::createContextMenu(), MusicAbstractSongsListTableWidget::currentSongName(), MusicAbstractSongsListTableWidget::currentSongPath(), MusicCloudManagerTableWidget::deleteFileToServer(), MusicCloudManagerTableWidget::downloadFileToServer(), MusicVideoSearchTableWidget::downloadLocalMovie(), MusicLrcSearchTableWidget::downloadQueryResult(), MusicWebMVRadioInfoTableWidget::downloadQueryResult(), MusicItemQueryTableWidget::downloadQueryResult(), MusicSongSearchTableWidget::downloadQueryResult(), MusicVideoSearchTableWidget::downloadQueryResult(), MusicWebMVRadioInfoTableWidget::itemCellClicked(), MusicPlaylistBackupTableWidget::itemDoubleClicked(), MusicAbstractDownloadTableWidget::itemDoubleClicked(), MusicItemQueryTableWidget::menuActionChanged(), MusicAbstractSongsListTableWidget::openFileDir(), MusicAbstractSongsListTableWidget::playClicked(), MusicSongCheckToolsDuplicateTableWidget::playSong(), MusicSongCheckToolsQualityTableWidget::playSong(), MusicSongCheckToolsRenameTableWidget::removeCurrentRow(), MusicSongCheckToolsDuplicateTableWidget::removeCurrentRow(), MusicSongCheckToolsQualityTableWidget::removeCurrentRow(), MusicSongsListPlayTableWidget::removeItemAt(), MusicCloudUploadTableWidget::reuploadFile(), MusicCloudUploadTableWidget::reuploadFiles(), MusicItemSearchTableWidget::searchActionClicked(), MusicSongsListPlayTableWidget::setChangSongName(), MusicAbstractSongsListTableWidget::showAlbumQueryWidget(), MusicAbstractSongsListTableWidget::showDownloadWidget(), MusicAbstractSongsListTableWidget::showFileInformation(), MusicCloudManagerTableWidget::showFileInformationWidget(), MusicSongsListPlayTableWidget::showMakeRingWidget(), MusicAbstractSongsListTableWidget::showMovieQueryWidget(), MusicAbstractSongsListTableWidget::showPlayedMovieQueryWidget(), MusicAbstractSongsListTableWidget::showPlayedSimilarQueryWidget(), MusicAbstractSongsListTableWidget::showPlayedSongSharedWidget(), MusicAbstractSongsListTableWidget::showSimilarQueryWidget(), MusicAbstractSongsListTableWidget::showSongSharedWidget(), and MusicSongsListPlayTableWidget::showTransformWidget().
void TTKAbstractTableWidget::itemCellClicked (int row, int column) virtual slot
Table widget item cell click.
Definition at line 80 of file ttkabstracttablewidget.cpp.
Referenced by MusicSongSearchPopTableWidget::itemCellClicked(), and TTKAbstractTableWidget().
void TTKAbstractTableWidget::itemCellEntered (int row, int column) virtual slot
Table widget item cell enter.
Definition at line 65 of file ttkabstracttablewidget.cpp.
References m_backgroundColor, m_previousColorRow, and setRowColor().
Referenced by MusicWebFMRadioWidget::itemCellEntered(), MusicMobileSongsTableWidget::itemCellEntered(), MusicLrcSearchTableWidget::itemCellEntered(), MusicWebDJRadioProgramTableWidget::itemCellEntered(), MusicItemQueryTableWidget::itemCellEntered(), MusicSongSearchTableWidget::itemCellEntered(), MusicSongsListPlayedTableWidget::itemCellEntered(), MusicVideoSearchTableWidget::itemCellEntered(), MusicSongsListPlayTableWidget::itemCellEntered(), leaveEvent(), and TTKAbstractTableWidget().
void TTKAbstractTableWidget::leaveEvent (QEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicSongsListPlayTableWidget.
Definition at line 96 of file ttkabstracttablewidget.cpp.
References itemCellEntered().
Referenced by MusicSongsListPlayTableWidget::leaveEvent().
void TTKAbstractTableWidget::removeItems () virtual slot
Remove all items.
Definition at line 86 of file ttkabstracttablewidget.cpp.
References m_backgroundColor, m_previousClickRow, and m_previousColorRow.
Referenced by MusicCloudManagerTableWidget::receiveDataFinshed(), MusicMobileSongsTableWidget::removeItems(), MusicSongSearchPopTableWidget::removeItems(), MusicSongsListPlayedTableWidget::removeItems(), MusicQueryTableWidget::removeItems(), MusicDownloadTableWidget::removeItems(), MusicLocalManagerSongsTableWidget::removeItems(), MusicDownloadBatchTableWidget::removeItems(), MusicSongsListPlayTableWidget::removeItems(), MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget(), MusicFillItemTableWidget::~MusicFillItemTableWidget(), MusicLocalManagerStatisticTableWidget::~MusicLocalManagerStatisticTableWidget(), and MusicPlaylistBackupTableWidget::~MusicPlaylistBackupTableWidget().
TTKIntList TTKAbstractTableWidget::selectedIndexList () const
Get selected item index list.
Definition at line 52 of file ttkabstracttablewidget.cpp.
Referenced by MusicCloudManagerTableWidget::deleteFilesToServer(), MusicAbstractDownloadTableWidget::removeItemAt(), MusicSongsListPlayedTableWidget::removeItemAt(), MusicSongsListPlayTableWidget::removeItemAt(), and MusicCloudUploadTableWidget::reuploadFiles().
void TTKAbstractTableWidget::setRowColor (int row, const QColor & color) const protected
Set selected item row color.
Definition at line 102 of file ttkabstracttablewidget.cpp.
Referenced by itemCellEntered().
Member Data Documentation
QColor TTKAbstractTableWidget::m_backgroundColor protected
Definition at line 84 of file ttkabstracttablewidget.h.
Referenced by MusicVideoSearchTableWidget::createResultItem(), itemCellEntered(), and removeItems().
int TTKAbstractTableWidget::m_previousClickRow protected
Definition at line 83 of file ttkabstracttablewidget.h.
Referenced by MusicVideoSearchTableWidget::downloadLocalFromControl(), MusicFillItemTableWidget::itemCellClicked(), MusicVideoSearchTableWidget::queryMediaProps(), and removeItems().
int TTKAbstractTableWidget::m_previousColorRow protected
Definition at line 82 of file ttkabstracttablewidget.h.
Referenced by MusicWebFMRadioWidget::itemCellEntered(), itemCellEntered(), MusicSongsListPlayedTableWidget::itemCellEntered(), MusicSongsListPlayTableWidget::itemCellEntered(), removeItems(), and MusicSongsListPlayTableWidget::showTimeOut().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstracttablewidget.h
TTKCommon/TTKLibrary/ttkabstracttablewidget.cpp