TTKMusicplayer: MusicSoundEffectsItemWidget Class Reference
MusicSoundEffectsItemWidget Class Reference
The class of the sound effect item widget.
#include <musicsoundeffectswidget.h>
Public Types
enum Type {
Null, BS2B, Crossfade, Stereo,
LADSPA, SoX
}
Public Slots
void setPluginEnable ()
void soundEffectCheckBoxChanged (bool state)
void soundEffectValueChanged ()
Public Member Functions
MusicSoundEffectsItemWidget (QWidget *parent=0)
qmmp incldue
~MusicSoundEffectsItemWidget ()
void setText (const QString &text)
void setType (Type type)
void setPluginEnable (bool enable)
bool pluginEnable () const
Static Public Member Functions
static QString getClassName ()
static void soundEffectChanged (Type type, bool enable)
Static Protected Member Functions
static QString transformQStringFromEnum (Type type)
Protected Attributes
Type m_type
bool m_enable
QLabel * m_textLabel
QPushButton * m_settingButton
QPushButton * m_openButton
Detailed Description
The class of the sound effect item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicsoundeffectswidget.h.
Member Enumeration Documentation
enum MusicSoundEffectsItemWidget::Type
Enumerator
Null
sound null effect
BS2B
sound BS2B effect
Crossfade
sound Crossfade effect
Stereo
sound Stereo effect
LADSPA
sound LADSPA effect
SoX
sound SoX Resampler effect
Definition at line 35 of file musicsoundeffectswidget.h.
Constructor & Destructor Documentation
MusicSoundEffectsItemWidget::MusicSoundEffectsItemWidget (QWidget * parent = 0) explicit
qmmp incldue
Object contsructor.
Definition at line 14 of file musicsoundeffectswidget.cpp.
References m_enable, m_openButton, m_settingButton, m_textLabel, m_type, MusicUIObject::MBackgroundStyle01, MusicUIObject::MBackgroundStyle04, MusicUIObject::MBackgroundStyle08, MusicUIObject::MPushButtonStyle01, Null, setPluginEnable(), setText(), and soundEffectValueChanged().
MusicSoundEffectsItemWidget::~MusicSoundEffectsItemWidget ()
Definition at line 72 of file musicsoundeffectswidget.cpp.
References m_openButton, m_settingButton, and m_textLabel.
Member Function Documentation
QString MusicSoundEffectsItemWidget::getClassName () static
Get class object name.
Definition at line 79 of file musicsoundeffectswidget.cpp.
bool MusicSoundEffectsItemWidget::pluginEnable () const
Get plugin enable or not.
Definition at line 100 of file musicsoundeffectswidget.cpp.
References m_enable.
void MusicSoundEffectsItemWidget::setPluginEnable (bool enable)
Set plugin enable or not.
Definition at line 94 of file musicsoundeffectswidget.cpp.
References m_enable, and setPluginEnable().
void MusicSoundEffectsItemWidget::setPluginEnable () slot
Set plugin enable or not.
Definition at line 118 of file musicsoundeffectswidget.cpp.
References m_enable, m_openButton, m_settingButton, and soundEffectCheckBoxChanged().
Referenced by MusicSoundEffectsItemWidget(), and setPluginEnable().
void MusicSoundEffectsItemWidget::setText (const QString & text)
Set sound effect plugin name.
Definition at line 84 of file musicsoundeffectswidget.cpp.
References m_textLabel.
Referenced by MusicSoundEffectsItemWidget().
void MusicSoundEffectsItemWidget::setType (Type type)
Set sound effect plugin type.
Definition at line 89 of file musicsoundeffectswidget.cpp.
References m_type.
void MusicSoundEffectsItemWidget::soundEffectChanged (Type type, bool enable) static
Sound effect changed.
Definition at line 105 of file musicsoundeffectswidget.cpp.
References Effect::factories(), EffectProperties::name, EffectFactory::properties(), Effect::setEnabled(), and transformQStringFromEnum().
Referenced by MusicApplicationObject::musicEffectChanged(), and soundEffectCheckBoxChanged().
void MusicSoundEffectsItemWidget::soundEffectCheckBoxChanged (bool state) slot
Sound effect checkBox changed.
Definition at line 138 of file musicsoundeffectswidget.cpp.
References m_type, and soundEffectChanged().
Referenced by setPluginEnable().
void MusicSoundEffectsItemWidget::soundEffectValueChanged () slot
Sound effect button value changed.
Definition at line 143 of file musicsoundeffectswidget.cpp.
References Effect::factories(), m_type, EffectProperties::name, EffectFactory::properties(), EffectFactory::showSettings(), and transformQStringFromEnum().
Referenced by MusicSoundEffectsItemWidget().
QString MusicSoundEffectsItemWidget::transformQStringFromEnum (Type type) static protected
Transform string from enum.
Definition at line 156 of file musicsoundeffectswidget.cpp.
References BS2B, Crossfade, LADSPA, SoX, and Stereo.
Referenced by soundEffectChanged(), and soundEffectValueChanged().
Member Data Documentation
bool MusicSoundEffectsItemWidget::m_enable protected
Definition at line 100 of file musicsoundeffectswidget.h.
Referenced by MusicSoundEffectsItemWidget(), pluginEnable(), and setPluginEnable().
QPushButton * MusicSoundEffectsItemWidget::m_openButton protected
Definition at line 102 of file musicsoundeffectswidget.h.
Referenced by MusicSoundEffectsItemWidget(), setPluginEnable(), and ~MusicSoundEffectsItemWidget().
QPushButton* MusicSoundEffectsItemWidget::m_settingButton protected
Definition at line 102 of file musicsoundeffectswidget.h.
Referenced by MusicSoundEffectsItemWidget(), setPluginEnable(), and ~MusicSoundEffectsItemWidget().
QLabel* MusicSoundEffectsItemWidget::m_textLabel protected
Definition at line 101 of file musicsoundeffectswidget.h.
Referenced by MusicSoundEffectsItemWidget(), setText(), and ~MusicSoundEffectsItemWidget().
Type MusicSoundEffectsItemWidget::m_type protected
Definition at line 99 of file musicsoundeffectswidget.h.
Referenced by MusicSoundEffectsItemWidget(), setType(), soundEffectCheckBoxChanged(), and soundEffectValueChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsoundeffectswidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsoundeffectswidget.cpp