TTKMusicplayer: MusicDownLoadMGInterface Class Reference
MusicDownLoadMGInterface Class Reference
The class to migu query download interface.
#include <musicdownloadmginterface.h>
Public Member Functions
void makeTokenQueryUrl (QNetworkRequest *request, const QString &id)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bit, const QString &format, int type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info, const QString &param)
Detailed Description
The class to migu query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 64 of file musicdownloadmginterface.h.
Member Function Documentation
void MusicDownLoadMGInterface::makeTokenQueryUrl (QNetworkRequest * request, const QString & id)
Make token query url string.
Definition at line 19 of file musicdownloadmginterface.cpp.
References ALG_UA_KEY, MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), MG_INFO_CHL, MG_INFO_ID, MG_INFO_KEY, MG_INFO_MODE, MG_INFO_RDK, MG_UA_URL_1, and MusicUtils::Core::toUtf8().
Referenced by readFromMusicLLAttribute(), and MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute().
void MusicDownLoadMGInterface::readFromMusicLLAttribute (MusicObject::MusicSongInformation * info)
Read tags(size) from query results.
Definition at line 81 of file musicdownloadmginterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongInformation::m_songId, makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MG_SONG_LL_INFO_URL, and QJson::Parser::parse().
Referenced by readFromMusicSongAttribute().
void MusicDownLoadMGInterface::readFromMusicLLAttribute (MusicObject::MusicSongInformation * info, const QString & param)
Read tags(size) from query results.
Definition at line 128 of file musicdownloadmginterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, makeTokenQueryUrl(), MB_1000, MusicUtils::Algorithm::mdII(), MG_SONG_LL_DATA_URL, MG_SONG_LL_PATH_URL, QJson::Parser::parse(), and MusicUtils::Number::size2Label().
void MusicDownLoadMGInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, int bit, const QString & format, int type)
Read tags(size) from query results.
Definition at line 34 of file musicdownloadmginterface.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), and MG_SONG_PATH_URL.
Referenced by MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), readFromMusicSongAttribute(), and MusicDownLoadQueryMGThread::singleDownLoadFinished().
void MusicDownLoadMGInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & format, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 44 of file musicdownloadmginterface.cpp.
References MB_128, MB_320, readFromMusicLLAttribute(), and readFromMusicSongAttribute().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/mg/musicdownloadmginterface.h
TTKModule/TTKCore/musicNetworkKits/mg/musicdownloadmginterface.cpp