TTKMusicplayer: MusicDownloadCounterPVThread Class Reference
MusicDownloadCounterPVThread Class Reference
The class of get counter pv of player.
#include <musicdownloadcounterpvthread.h>
Public Slots
virtual void downLoadFinished ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownloadCounterPVThread (QObject *parent=0)
QJson import.
virtual ~MusicDownloadCounterPVThread ()
void startToDownload ()
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of get counter pv of player.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 22 of file musicdownloadcounterpvthread.h.
Constructor & Destructor Documentation
MusicDownloadCounterPVThread::MusicDownloadCounterPVThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 5 of file musicdownloadcounterpvthread.cpp.
MusicDownloadCounterPVThread::~MusicDownloadCounterPVThread () virtual
Definition at line 11 of file musicdownloadcounterpvthread.cpp.
References MusicNetworkAbstract::deleteAll().
Member Function Documentation
void MusicDownloadCounterPVThread::downLoadFinished () virtual slot
Download data from net finished.
Definition at line 44 of file musicdownloadcounterpvthread.cpp.
References MusicNetworkAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), M_LOGGER_ERROR, MusicNetworkAbstract::m_reply, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicDownloadCounterPVThread::getClassName () static
Get class object name.
Definition at line 16 of file musicdownloadcounterpvthread.cpp.
Referenced by startToDownload().
void MusicDownloadCounterPVThread::startToDownload ()
Start to download counter pv from net.
Definition at line 21 of file musicdownloadcounterpvthread.cpp.
References COOKIE_URL, downLoadFinished(), getClassName(), HOST_URL, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::mdII(), QURTY_URL, REFER_URL, MusicNetworkAbstract::sslErrors(), and MusicUtils::Core::toUtf8().
Referenced by MusicMessageAboutDialog::MusicMessageAboutDialog(), and MusicTopAreaWidget::MusicTopAreaWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadcounterpvthread.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadcounterpvthread.cpp