TTKMusicPlayer: MusicSongsManagerThread Class Reference
MusicSongsManagerThread Class Reference
The class of the songs manager thread.
#include <musicsongsmanagerthread.h>
Signals
void searchFilePathChanged (const QStringList &name)
Public Member Functions
MusicSongsManagerThread (QObject *parent=nullptr)
void setFindFilePath (const QString &path)
void setFindFilePath (const QStringList &path)
Public Member Functions inherited from TTKAbstractThread
TTKAbstractThread (QObject *parent=nullptr)
Private Member Functions
virtual void run () overridefinal
Private Attributes
QStringList m_path
Additional Inherited Members
Public Slots inherited from TTKAbstractThread
void start ()
void stop ()
Protected Attributes inherited from TTKAbstractThread
bool m_running
Detailed Description
The class of the songs manager thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicsongsmanagerthread.h.
Constructor & Destructor Documentation
MusicSongsManagerThread::MusicSongsManagerThread (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musicsongsmanagerthread.cpp.
Member Function Documentation
void MusicSongsManagerThread::run () final override private virtual
Thread run now.
The name and path search ended when sending the corresponding
Reimplemented from TTKAbstractThread.
Definition at line 21 of file musicsongsmanagerthread.cpp.
References TTK::File::fileListByPath(), m_path, TTKAbstractThread::m_running, qAsConst, searchFilePathChanged(), and MusicFormats::supportMusicInputFilterFormats().
void MusicSongsManagerThread::searchFilePathChanged (const QStringList & name) signal
Send the searched file or path.
Referenced by run().
void MusicSongsManagerThread::setFindFilePath (const QString & path)
Set find file path by given path.
Definition at line 11 of file musicsongsmanagerthread.cpp.
Referenced by MusicMobileSongsManagerWidget::findExtraDevicePath().
void MusicSongsManagerThread::setFindFilePath (const QStringList & path)
Set find file path by given path list.
Definition at line 16 of file musicsongsmanagerthread.cpp.
References m_path.
Member Data Documentation
QStringList MusicSongsManagerThread::m_path private
Definition at line 58 of file musicsongsmanagerthread.h.
Referenced by run(), and setFindFilePath().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongsmanagerthread.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongsmanagerthread.cpp