TTKMusicPlayer: MusicQmmpPluginItem Class Reference
MusicQmmpPluginItem Class Reference
The class of the qmmp plugin item widget.
Public Types
enum Module {
PluginDecoder = QTreeWidgetItem::UserType, PluginEffect, PluginVisual, PluginTransports,
PluginOutput
}
Public Member Functions
MusicQmmpPluginItem (QTreeWidgetItem *parent, DecoderFactory *factory, const QString &path)
MusicQmmpPluginItem (QTreeWidgetItem *parent, EffectFactory *factory, const QString &path)
MusicQmmpPluginItem (QTreeWidgetItem *parent, VisualFactory *factory, const QString &path)
MusicQmmpPluginItem (QTreeWidgetItem *parent, InputSourceFactory *factory, const QString &path)
MusicQmmpPluginItem (QTreeWidgetItem *parent, OutputFactory *factory, const QString &path)
bool hasSettings () const
void showSettingWidget (QWidget *parent) const
void setEnabled (bool enabled)
void initialize (bool state, bool enabled, const MusicPluginProperty &property)
Private Attributes
void * m_factory
Detailed Description
The class of the qmmp plugin item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 26 of file musicpluginwidget.cpp.
Member Enumeration Documentation
enum MusicQmmpPluginItem::Module
Enumerator
PluginDecoder
PluginEffect
PluginVisual
PluginTransports
PluginOutput
Definition at line 85 of file musicpluginwidget.cpp.
Constructor & Destructor Documentation
MusicQmmpPluginItem::MusicQmmpPluginItem (QTreeWidgetItem * parent, DecoderFactory * factory, const QString & path) inline
Definition at line 29 of file musicpluginwidget.cpp.
References DecoderProperties::description, DecoderProperties::hasSettings, initialize(), Decoder::isEnabled(), MusicPluginProperty::m_type, DecoderProperties::name, and DecoderFactory::properties().
MusicQmmpPluginItem::MusicQmmpPluginItem (QTreeWidgetItem * parent, EffectFactory * factory, const QString & path) inline
Definition at line 41 of file musicpluginwidget.cpp.
References EffectProperties::hasSettings, initialize(), Effect::isEnabled(), MusicPluginProperty::m_type, EffectProperties::name, and EffectFactory::properties().
MusicQmmpPluginItem::MusicQmmpPluginItem (QTreeWidgetItem * parent, VisualFactory * factory, const QString & path) inline
Definition at line 52 of file musicpluginwidget.cpp.
References VisualProperties::hasSettings, initialize(), Visual::isEnabled(), MusicPluginProperty::m_type, VisualProperties::name, and VisualFactory::properties().
MusicQmmpPluginItem::MusicQmmpPluginItem (QTreeWidgetItem * parent, InputSourceFactory * factory, const QString & path) inline
Definition at line 63 of file musicpluginwidget.cpp.
References InputSourceProperties::hasSettings, initialize(), InputSource::isEnabled(), MusicPluginProperty::m_type, InputSourceProperties::name, and InputSourceFactory::properties().
MusicQmmpPluginItem::MusicQmmpPluginItem (QTreeWidgetItem * parent, OutputFactory * factory, const QString & path) inline
Definition at line 74 of file musicpluginwidget.cpp.
References Output::currentFactory(), OutputProperties::hasSettings, initialize(), MusicPluginProperty::m_type, OutputProperties::name, and OutputFactory::properties().
Member Function Documentation
bool MusicQmmpPluginItem::hasSettings () const inline
Definition at line 94 of file musicpluginwidget.cpp.
References m_factory, PluginDecoder, PluginEffect, PluginOutput, PluginTransports, PluginVisual, and TTKStaticCast.
Referenced by MusicQmmpPluginWidget::pluginItemChanged().
void MusicQmmpPluginItem::initialize (bool state, bool enabled, const MusicPluginProperty & property) inline
Definition at line 148 of file musicpluginwidget.cpp.
References MusicPluginProperty::m_description, MusicPluginProperty::m_hasSettings, MusicPluginProperty::m_name, MusicPluginProperty::m_type, TTK_CHECKED_ROLE, TTK_DISPLAY_ROLE, and TTK_ENABLED_ROLE.
Referenced by MusicQmmpPluginItem().
void MusicQmmpPluginItem::setEnabled (bool enabled) inline
Definition at line 128 of file musicpluginwidget.cpp.
References m_factory, PluginDecoder, PluginEffect, PluginOutput, PluginTransports, PluginVisual, Output::setCurrentFactory(), InputSource::setEnabled(), Decoder::setEnabled(), and TTKStaticCast.
void MusicQmmpPluginItem::showSettingWidget (QWidget * parent) const inline
Definition at line 107 of file musicpluginwidget.cpp.
References m_factory, PluginDecoder, PluginEffect, PluginOutput, PluginTransports, PluginVisual, and TTKStaticCast.
Referenced by MusicQmmpPluginWidget::pluginButtonClicked().
Member Data Documentation
void* MusicQmmpPluginItem::m_factory private
Definition at line 172 of file musicpluginwidget.cpp.
Referenced by hasSettings(), setEnabled(), and showSettingWidget().
The documentation for this class was generated from the following file:
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.cpp