TTKMusicplayer: MusicLrcDownloadBatchWidget Class Reference
MusicLrcDownloadBatchWidget Class Reference
The class of the lrc batch download widget.
#include <musiclrcdownloadbatchwidget.h>
Public Slots
void addButtonClicked ()
void downloadButtonClicked ()
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicLrcDownloadBatchWidget (QWidget *parent=nullptr)
~MusicLrcDownloadBatchWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicLrcDownloadBatchWidget * m_ui
MusicSongs m_localSongs
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the lrc batch download widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 60 of file musiclrcdownloadbatchwidget.h.
Constructor & Destructor Documentation
MusicLrcDownloadBatchWidget::MusicLrcDownloadBatchWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 72 of file musiclrcdownloadbatchwidget.cpp.
References addButtonClicked(), downloadButtonClicked(), m_ui, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSRadioButtonStyle01, and MusicUIObject::MQSSToolButtonStyle04.
MusicLrcDownloadBatchWidget::~MusicLrcDownloadBatchWidget ()
Definition at line 106 of file musiclrcdownloadbatchwidget.cpp.
References G_SINGLE_MANAGER_PTR, and m_ui.
Member Function Documentation
void MusicLrcDownloadBatchWidget::addButtonClicked () slot
Add button clicked.
Definition at line 112 of file musiclrcdownloadbatchwidget.cpp.
References m_localSongs, and m_ui.
Referenced by MusicLrcDownloadBatchWidget().
void MusicLrcDownloadBatchWidget::downloadButtonClicked () slot
Download button clicked.
Definition at line 118 of file musiclrcdownloadbatchwidget.cpp.
References MusicObject::DownloadLrc, MusicSemaphoreLoop::exec(), G_DOWNLOAD_QUERY_PTR, MusicSong::getMusicName(), MusicSong::getMusicPath(), MusicAbstractQueryRequest::getMusicSongInfos(), MusicAbstractQueryRequest::isEmpty(), LRC_FILE, MusicUtils::String::lrcPrefix(), m_localSongs, m_ui, MusicAbstractQueryRequest::MusicQuery, and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicLrcDownloadBatchWidget().
void MusicLrcDownloadBatchWidget::show () slot
Override show function.
Definition at line 193 of file musiclrcdownloadbatchwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Member Data Documentation
MusicSongs MusicLrcDownloadBatchWidget::m_localSongs protected
Definition at line 88 of file musiclrcdownloadbatchwidget.h.
Referenced by addButtonClicked(), and downloadButtonClicked().
Ui::MusicLrcDownloadBatchWidget* MusicLrcDownloadBatchWidget::m_ui protected
Definition at line 86 of file musiclrcdownloadbatchwidget.h.
Referenced by addButtonClicked(), downloadButtonClicked(), MusicLrcDownloadBatchWidget(), show(), and ~MusicLrcDownloadBatchWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcdownloadbatchwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcdownloadbatchwidget.cpp