TTKMusicplayer: TTKThirdParty/TTKExtras/qalgorithm/aes_cbc.cpp File Reference
aes_cbc.cpp File Reference
#include "aes.h"
#include "cbc128.h"
Functions
void AES_cbc_encrypt (const unsigned char *in, unsigned char *out, size_t len, const AES_KEY *key, unsigned char *ivec, const int enc)
Function Documentation
void AES_cbc_encrypt (const unsigned char * in, unsigned char * out, size_t len, const AES_KEY * key, unsigned char * ivec, const int enc)
Definition at line 4 of file aes_cbc.cpp.
References AES_decrypt(), AES_encrypt(), CRYPTO_cbc128_decrypt(), and CRYPTO_cbc128_encrypt().
Referenced by QAlgorithm::Aes::decryptCBC(), and QAlgorithm::Aes::encryptCBC().