TTKMusicPlayer: MusicMainRecommendWidget Class Reference
MusicMainRecommendWidget Class Reference
The class of the main recommend widget.
#include <musicmainrecommendwidget.h>
Public Member Functions
MusicMainRecommendWidget (QWidget *parent=nullptr)
~MusicMainRecommendWidget ()
virtual void resizeGeometry () overridefinal
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Slots
void areaItemChangedToMore (int id)
void moreItemChangedToArea ()
Private Member Functions
void createHomeWidget ()
void createTopWidget ()
void createContainerWidget ()
void createContainerTopWidget ()
void createContainerMiddleTopWidget ()
void createContainerMiddleWidget ()
void createContainerMiddleBottomWidget ()
Private Attributes
QStackedWidget * m_mainWidget
TTKClickedGroup * m_areasGroup
QWidget * m_homeWidget
QWidget * m_homeContainer
MusicNewSongRecommendQueryTableWidget * m_newSongsWidget
MusicItemRecommendQueryWidget * m_newAlbumsWidget
MusicItemRecommendQueryWidget * m_artistsWidget
MusicItemRecommendQueryWidget * m_hqPlaylistWidget
MusicItemRecommendQueryWidget * m_playlistWidget
MusicItemMoreRecommendQueryWidget * m_itemMoreWidget
Detailed Description
The class of the main recommend widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 210 of file musicmainrecommendwidget.h.
Constructor & Destructor Documentation
MusicMainRecommendWidget::MusicMainRecommendWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 696 of file musicmainrecommendwidget.cpp.
References TTK::UI::BackgroundStyle10, createHomeWidget(), and m_mainWidget.
MusicMainRecommendWidget::~MusicMainRecommendWidget ()
Object destructor.
Definition at line 713 of file musicmainrecommendwidget.cpp.
References m_areasGroup, m_artistsWidget, m_homeContainer, m_homeWidget, m_hqPlaylistWidget, m_itemMoreWidget, m_mainWidget, m_newAlbumsWidget, m_newSongsWidget, and m_playlistWidget.
Member Function Documentation
void MusicMainRecommendWidget::areaItemChangedToMore (int id) private slot
Change area item to more.
Definition at line 741 of file musicmainrecommendwidget.cpp.
References m_homeWidget, m_itemMoreWidget, m_mainWidget, and TTKStaticCast.
Referenced by createHomeWidget().
void MusicMainRecommendWidget::createContainerMiddleBottomWidget () private
Create container middle bottom widget.
Definition at line 996 of file musicmainrecommendwidget.cpp.
References TTKClickedGroup::addWidget(), TTK::UI::BackgroundStyle13, TTK::UI::FontStyle04, G_DOWNLOAD_QUERY_PTR, m_areasGroup, m_homeContainer, m_homeWidget, m_playlistWidget, Playlist, MusicPageQueryRequest::setPageSize(), MusicItemRecommendQueryWidget::setQueryInput(), and MusicAbstractQueryRequest::startToSearch().
Referenced by createContainerWidget().
void MusicMainRecommendWidget::createContainerMiddleTopWidget () private
Create container middle top widget.
Definition at line 920 of file musicmainrecommendwidget.cpp.
References TTKClickedGroup::addWidget(), Artist, TTK::UI::BackgroundStyle13, TTK::UI::FontStyle04, G_DOWNLOAD_QUERY_PTR, m_areasGroup, m_artistsWidget, m_homeContainer, m_homeWidget, MusicPageQueryRequest::setPageSize(), MusicItemRecommendQueryWidget::setQueryInput(), and MusicAbstractQueryRequest::startToSearch().
Referenced by createContainerWidget().
void MusicMainRecommendWidget::createContainerMiddleWidget () private
Create container middle widget.
Definition at line 958 of file musicmainrecommendwidget.cpp.
References TTKClickedGroup::addWidget(), TTK::UI::BackgroundStyle13, TTK::UI::FontStyle04, G_DOWNLOAD_QUERY_PTR, m_areasGroup, m_homeContainer, m_homeWidget, m_hqPlaylistWidget, PlaylistHQ, MusicPageQueryRequest::setPageSize(), MusicItemRecommendQueryWidget::setQueryInput(), and MusicAbstractQueryRequest::startToSearch().
Referenced by createContainerWidget().
void MusicMainRecommendWidget::createContainerTopWidget () private
Create container top widget.
Definition at line 839 of file musicmainrecommendwidget.cpp.
References TTKClickedGroup::addWidget(), Album, TTK::UI::BackgroundStyle03, TTK::UI::BackgroundStyle13, TTK::UI::FontStyle04, G_DOWNLOAD_QUERY_PTR, m_areasGroup, m_homeContainer, m_homeWidget, m_newAlbumsWidget, m_newSongsWidget, MusicPageQueryRequest::setPageSize(), MusicQueryTableWidget::setQueryInput(), MusicItemRecommendQueryWidget::setQueryInput(), MusicAbstractQueryRequest::startToSearch(), and MusicNewSongRecommendQueryTableWidget::startToSearchByValue().
Referenced by createContainerWidget().
void MusicMainRecommendWidget::createContainerWidget () private
Create container widget.
Definition at line 818 of file musicmainrecommendwidget.cpp.
References createContainerMiddleBottomWidget(), createContainerMiddleTopWidget(), createContainerMiddleWidget(), createContainerTopWidget(), TTK::Widget::generateVScrollAreaStyle(), m_homeContainer, and m_homeWidget.
Referenced by createHomeWidget().
void MusicMainRecommendWidget::createHomeWidget () private
Create home widget.
Definition at line 758 of file musicmainrecommendwidget.cpp.
References areaItemChangedToMore(), TTK::UI::BackgroundStyle01, createContainerWidget(), createTopWidget(), m_areasGroup, m_homeWidget, and m_mainWidget.
Referenced by MusicMainRecommendWidget().
void MusicMainRecommendWidget::createTopWidget () private
Create top widget.
Definition at line 776 of file musicmainrecommendwidget.cpp.
References TTKClickedGroup::addWidget(), MusicRightAreaWidget::ArtistCategoryWidget, TTK::UI::FontStyle03, MusicRightAreaWidget::instance(), m_homeWidget, MusicRightAreaWidget::MainRecommendWidget, MusicRightAreaWidget::PlaylistCategoryWidget, TTK::UI::PushButtonStyle01, TTK::UI::PushButtonStyle13, MusicRightAreaWidget::SongRecommendWidget, and MusicRightAreaWidget::ToplistWidget.
Referenced by createHomeWidget().
void MusicMainRecommendWidget::moreItemChangedToArea () private slot
Change more item to area.
Definition at line 751 of file musicmainrecommendwidget.cpp.
References m_homeWidget, m_itemMoreWidget, and m_mainWidget.
void MusicMainRecommendWidget::resizeGeometry () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 727 of file musicmainrecommendwidget.cpp.
References m_artistsWidget, m_hqPlaylistWidget, m_itemMoreWidget, m_newAlbumsWidget, m_newSongsWidget, m_playlistWidget, MusicNewSongRecommendQueryTableWidget::resizeGeometry(), MusicItemRecommendQueryWidget::resizeGeometry(), and MusicItemMoreRecommendQueryWidget::resizeGeometry().
Member Data Documentation
TTKClickedGroup* MusicMainRecommendWidget::m_areasGroup private
Definition at line 269 of file musicmainrecommendwidget.h.
Referenced by createContainerMiddleBottomWidget(), createContainerMiddleTopWidget(), createContainerMiddleWidget(), createContainerTopWidget(), createHomeWidget(), and ~MusicMainRecommendWidget().
MusicItemRecommendQueryWidget* MusicMainRecommendWidget::m_artistsWidget private
Definition at line 273 of file musicmainrecommendwidget.h.
Referenced by createContainerMiddleTopWidget(), resizeGeometry(), and ~MusicMainRecommendWidget().
QWidget * MusicMainRecommendWidget::m_homeContainer private
Definition at line 270 of file musicmainrecommendwidget.h.
Referenced by createContainerMiddleBottomWidget(), createContainerMiddleTopWidget(), createContainerMiddleWidget(), createContainerTopWidget(), createContainerWidget(), and ~MusicMainRecommendWidget().
QWidget* MusicMainRecommendWidget::m_homeWidget private
Definition at line 270 of file musicmainrecommendwidget.h.
Referenced by areaItemChangedToMore(), createContainerMiddleBottomWidget(), createContainerMiddleTopWidget(), createContainerMiddleWidget(), createContainerTopWidget(), createContainerWidget(), createHomeWidget(), createTopWidget(), moreItemChangedToArea(), and ~MusicMainRecommendWidget().
MusicItemRecommendQueryWidget* MusicMainRecommendWidget::m_hqPlaylistWidget private
Definition at line 274 of file musicmainrecommendwidget.h.
Referenced by createContainerMiddleWidget(), resizeGeometry(), and ~MusicMainRecommendWidget().
MusicItemMoreRecommendQueryWidget* MusicMainRecommendWidget::m_itemMoreWidget private
Definition at line 276 of file musicmainrecommendwidget.h.
Referenced by areaItemChangedToMore(), moreItemChangedToArea(), resizeGeometry(), and ~MusicMainRecommendWidget().
QStackedWidget* MusicMainRecommendWidget::m_mainWidget private
Definition at line 268 of file musicmainrecommendwidget.h.
Referenced by areaItemChangedToMore(), createHomeWidget(), moreItemChangedToArea(), MusicMainRecommendWidget(), and ~MusicMainRecommendWidget().
MusicItemRecommendQueryWidget* MusicMainRecommendWidget::m_newAlbumsWidget private
Definition at line 272 of file musicmainrecommendwidget.h.
Referenced by createContainerTopWidget(), resizeGeometry(), and ~MusicMainRecommendWidget().
MusicNewSongRecommendQueryTableWidget* MusicMainRecommendWidget::m_newSongsWidget private
Definition at line 271 of file musicmainrecommendwidget.h.
Referenced by createContainerTopWidget(), resizeGeometry(), and ~MusicMainRecommendWidget().
MusicItemRecommendQueryWidget* MusicMainRecommendWidget::m_playlistWidget private
Definition at line 275 of file musicmainrecommendwidget.h.
Referenced by createContainerMiddleBottomWidget(), resizeGeometry(), and ~MusicMainRecommendWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.cpp