TTKMusicplayer: MusicArtistListFoundCategoryItem Class Reference
MusicArtistListFoundCategoryItem Class Reference
The class of the artist list found category item.
#include <musicartistlistfoundcategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicResultsCategoryItem &category)
Public Member Functions
MusicArtistListFoundCategoryItem (QWidget *parent=0)
void setCategory (const MusicResultsCategory &category)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
MusicResultsCategory m_category
Detailed Description
The class of the artist list found category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicartistlistfoundcategorypopwidget.h.
Constructor & Destructor Documentation
MusicArtistListFoundCategoryItem::MusicArtistListFoundCategoryItem (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 13 of file musicartistlistfoundcategorypopwidget.cpp.
Member Function Documentation
void MusicArtistListFoundCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 56 of file musicartistlistfoundcategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicResultsCategory::m_items.
Referenced by setCategory().
void MusicArtistListFoundCategoryItem::categoryChanged (const MusicResultsCategoryItem & category) signal
Current category changed.
Referenced by buttonClicked().
QString MusicArtistListFoundCategoryItem::getClassName () static
Get class object name.
Definition at line 19 of file musicartistlistfoundcategorypopwidget.cpp.
void MusicArtistListFoundCategoryItem::setCategory (const MusicResultsCategory & category)
Set current category.
Definition at line 24 of file musicartistlistfoundcategorypopwidget.cpp.
References buttonClicked(), ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicResultsCategory::m_category, m_category, MusicResultsCategory::m_items, MusicUIObject::MColorStyle03, MusicUIObject::MColorStyle08, and MusicUIObject::MFontStyle03.
Referenced by MusicArtistListFoundCategoryPopWidget::setCategory().
Member Data Documentation
MusicResultsCategory MusicArtistListFoundCategoryItem::m_category protected
Definition at line 60 of file musicartistlistfoundcategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistfoundcategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistfoundcategorypopwidget.cpp