TTKMusicplayer: filter::bitmap_t Class Reference
filter::bitmap_t Class Reference
#include <imagefilter.h>
Classes
struct buff_t
struct pixel_t
Public Types
typedef unsigned char channel_t
Public Member Functions
bitmap_t ()
void set (pixel_t *bits, long w, long h)
long w ()
long h ()
long size ()
pixel_t & operator[] (long num)
Protected Attributes
pixel_t * _bits
long _w
long _h
long _size
Detailed Description
Definition at line 56 of file imagefilter.h.
Member Typedef Documentation
typedef unsigned char filter::bitmap_t::channel_t
Definition at line 59 of file imagefilter.h.
Constructor & Destructor Documentation
filter::bitmap_t::bitmap_t () inline
Definition at line 78 of file imagefilter.h.
Member Function Documentation
long filter::bitmap_t::h () inline
Definition at line 89 of file imagefilter.h.
References _h.
Referenced by filter::Blur1D(), filter::Blur2D(), and set().
pixel_t& filter::bitmap_t::operator[] (long num) inline
Definition at line 97 of file imagefilter.h.
void filter::bitmap_t::set (pixel_t * bits, long w, long h) inline
Definition at line 80 of file imagefilter.h.
References h(), and w().
Referenced by QImageWrap::GaussFilter().
long filter::bitmap_t::size () inline
Definition at line 91 of file imagefilter.h.
References _h, and _size.
long filter::bitmap_t::w () inline
Definition at line 88 of file imagefilter.h.
References _w.
Referenced by filter::Blur1D(), filter::Blur2D(), and set().
Member Data Documentation
pixel_t* filter::bitmap_t::_bits protected
Definition at line 74 of file imagefilter.h.
long filter::bitmap_t::_h protected
Definition at line 75 of file imagefilter.h.
Referenced by h(), and size().
long filter::bitmap_t::_size protected
Definition at line 75 of file imagefilter.h.
Referenced by size().
long filter::bitmap_t::_w protected
Definition at line 75 of file imagefilter.h.
Referenced by w().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKImage/imagefilter.h