TTKMusicplayer: MusicM3UConfigManager Class Reference
MusicM3UConfigManager Class Reference
The class of the m3u playlist config manager.
#include <musicm3uconfigmanager.h>
Public Member Functions
MusicM3UConfigManager ()
virtual bool readBuffer (MusicSongItemList &items) overridefinal
virtual bool writeBuffer (const MusicSongItemList &items, const QString &path) overridefinal
Public Member Functions inherited from MusicPlaylistReader
MusicPlaylistReader ()
virtual ~MusicPlaylistReader ()
bool fromFile (const QString &name)
Additional Inherited Members
Protected Attributes inherited from MusicPlaylistReader
QFile m_file
Private Member Functions inherited from MusicPlaylistInterface
MusicPlaylistInterface ()
virtual ~MusicPlaylistInterface ()
Detailed Description
The class of the m3u playlist config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicm3uconfigmanager.h.
Constructor & Destructor Documentation
MusicM3UConfigManager::MusicM3UConfigManager () explicit
Object contsructor.
Definition at line 3 of file musicm3uconfigmanager.cpp.
Member Function Documentation
bool MusicM3UConfigManager::readBuffer (MusicSongItemList & items) final override virtual
Read datas from config file.
Implements MusicPlaylistInterface.
Definition at line 10 of file musicm3uconfigmanager.cpp.
References MusicPlaylistReader::m_file, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicTime::msecTime2LabelJustified(), and MT_S2MS.
Referenced by MusicPlaylistManager::readM3UConfig().
bool MusicM3UConfigManager::writeBuffer (const MusicSongItemList & items, const QString & path) final override virtual
Write datas into config file.
Implements MusicPlaylistInterface.
Definition at line 55 of file musicm3uconfigmanager.cpp.
References MusicTime::labelJustified2MsecTime(), MusicPlaylistReader::m_file, MusicSongItem::m_songs, and MT_S2MS.
Referenced by MusicPlaylistManager::writeM3UConfig().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musicm3uconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musicm3uconfigmanager.cpp