TTKMusicplayer: MusicToplistFoundCategoryPopWidget Class Reference
MusicToplistFoundCategoryPopWidget Class Reference
The class of the toplist music found category pop widget.
#include <musictoplistfoundcategorypopwidget.h>
Public Slots
void popupMenu ()
Public Slots inherited from MusicToolMenuWidget
void popupMenu ()
Public Member Functions
MusicToplistFoundCategoryPopWidget (QWidget *parent=0)
void setCategory (const QString &server, QObject *obj)
void closeMenu ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=0)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicToolMenuWidget
static QString getClassName ()
Protected Member Functions
void initWidget ()
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the toplist music found category pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 69 of file musictoplistfoundcategorypopwidget.h.
Constructor & Destructor Documentation
MusicToplistFoundCategoryPopWidget::MusicToplistFoundCategoryPopWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 65 of file musictoplistfoundcategorypopwidget.cpp.
References initWidget(), and popupMenu().
Member Function Documentation
void MusicToplistFoundCategoryPopWidget::closeMenu ()
Close the menu dialog.
Definition at line 110 of file musictoplistfoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
Referenced by MusicTopListFoundWidget::categoryChanged().
QString MusicToplistFoundCategoryPopWidget::getClassName () static
Get class object name.
Definition at line 74 of file musictoplistfoundcategorypopwidget.cpp.
void MusicToplistFoundCategoryPopWidget::initWidget () protected
Create all widget in layout.
Definition at line 120 of file musictoplistfoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, MusicUIObject::MBackgroundStyle17, MusicUIObject::MBorderStyle04, MusicUIObject::MMenuStyle05, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicToplistFoundCategoryPopWidget().
void MusicToplistFoundCategoryPopWidget::popupMenu () slot
To popup menu.
Definition at line 115 of file musictoplistfoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
Referenced by MusicToplistFoundCategoryPopWidget().
void MusicToplistFoundCategoryPopWidget::setCategory (const QString & server, QObject * obj)
Set current category by input server.
Definition at line 79 of file musictoplistfoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicUIObject::MBackgroundStyle17, MusicUIObject::MScrollBarStyle01, MusicToplistCategoryConfigManager::readCategoryConfig(), and MusicToplistFoundCategoryItem::setCategory().
Referenced by MusicTopListFoundWidget::createLabels().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musictoplistfoundcategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musictoplistfoundcategorypopwidget.cpp