TTKMusicPlayer: MusicDownloadQueueRequest Class Reference
MusicDownloadQueueRequest Class Reference
The class of the download data from queue request.
#include <musicdownloadqueuerequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void handleReadyRead ()
void handleError (QNetworkReply::NetworkError code)
Public Slots inherited from MusicAbstractDownLoadRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownloadQueueRequest (TTK::Download type, QObject *parent=nullptr)
MusicDownloadQueueRequest (const MusicDownloadQueueData &data, TTK::Download type, QObject *parent=nullptr)
MusicDownloadQueueRequest (const MusicDownloadQueueDataList &datas, TTK::Download type, QObject *parent=nullptr)
~MusicDownloadQueueRequest ()
void addImageQueue (const MusicDownloadQueueDataList &datas)
virtual void startToRequest () overridefinal
void abort ()
void clear ()
Public Member Functions inherited from MusicAbstractDownLoadRequest
MusicAbstractDownLoadRequest (const QString &url, const QString &path, TTK::Download type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Member Functions
void startDownload (const QString &url)
void startOrderImageQueue ()
Private Attributes
bool m_isDownload
bool m_isAbort
MusicDownloadQueueDataList m_imageQueue
QNetworkRequest * m_request
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicAbstractDownLoadRequest
QString mapCurrentQueryData () const
Protected Attributes inherited from MusicAbstractDownLoadRequest
QFile * m_file
QString m_url
QString m_savePath
TTK::Download m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the download data from queue request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicdownloadqueuerequest.h.
Constructor & Destructor Documentation
MusicDownloadQueueRequest::MusicDownloadQueueRequest (TTK::Download type, QObject * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musicdownloadqueuerequest.cpp.
MusicDownloadQueueRequest::MusicDownloadQueueRequest (const MusicDownloadQueueData & data, TTK::Download type, QObject * parent = nullptr)
Definition at line 11 of file musicdownloadqueuerequest.cpp.
References m_request, TTK::makeContentTypeHeader(), and TTK::setSslConfiguration().
MusicDownloadQueueRequest::MusicDownloadQueueRequest (const MusicDownloadQueueDataList & datas, TTK::Download type, QObject * parent = nullptr)
Definition at line 21 of file musicdownloadqueuerequest.cpp.
References addImageQueue().
MusicDownloadQueueRequest::~MusicDownloadQueueRequest ()
Object destructor.
Definition at line 27 of file musicdownloadqueuerequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), and m_request.
Member Function Documentation
void MusicDownloadQueueRequest::abort ()
Abort current download request.
Definition at line 42 of file musicdownloadqueuerequest.cpp.
References clear(), MusicAbstractDownLoadRequest::m_file, m_isAbort, m_isDownload, and TTKAbstractNetwork::m_reply.
Referenced by MusicBackgroundRemoteWidget::abort(), and MusicBackgroundOnlineWidget::currentTypeChanged().
void MusicDownloadQueueRequest::addImageQueue (const MusicDownloadQueueDataList & datas)
Add image download url and save path to download queue.
Definition at line 62 of file musicdownloadqueuerequest.cpp.
References m_imageQueue.
Referenced by MusicScreenSaverWidget::initialize(), MusicDownloadQueueRequest(), and MusicBackgroundRemoteWidget::startToRequest().
void MusicDownloadQueueRequest::clear ()
Clear image download url queue.
Definition at line 57 of file musicdownloadqueuerequest.cpp.
References m_imageQueue.
Referenced by abort().
void MusicDownloadQueueRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 112 of file musicdownloadqueuerequest.cpp.
References TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), MusicAbstractDownLoadRequest::downLoadFinished(), MusicAbstractDownLoadRequest::m_file, m_imageQueue, m_isAbort, m_isDownload, TTKAbstractNetwork::m_reply, m_request, and startOrderImageQueue().
Referenced by startDownload().
void MusicDownloadQueueRequest::handleError (QNetworkReply::NetworkError code) slot
Download reply error.
Definition at line 141 of file musicdownloadqueuerequest.cpp.
References TTKAbstractNetwork::deleteAll(), MusicAbstractDownLoadRequest::m_file, m_isAbort, TTKAbstractNetwork::m_reply, startToRequest(), and TTK_ERROR_STREAM.
Referenced by startDownload().
void MusicDownloadQueueRequest::handleReadyRead () slot
Download received data ready.
Definition at line 130 of file musicdownloadqueuerequest.cpp.
References MusicAbstractDownLoadRequest::m_file, and TTKAbstractNetwork::m_reply.
Referenced by startDownload().
void MusicDownloadQueueRequest::startDownload (const QString & url) private
Start to download data from net.
Definition at line 85 of file musicdownloadqueuerequest.cpp.
References downLoadFinished(), handleError(), handleReadyRead(), MusicAbstractDownLoadRequest::m_file, m_imageQueue, m_isDownload, TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, m_request, MusicAbstractDownLoadRequest::m_speedTimer, QtNetworkErrorConnect, and TTK_SLOT.
Referenced by startOrderImageQueue().
void MusicDownloadQueueRequest::startOrderImageQueue () private
Start to download data in order.
Definition at line 67 of file musicdownloadqueuerequest.cpp.
References TTKAbstractNetwork::downLoadDataChanged(), G_NETWORK_PTR, m_imageQueue, and startDownload().
Referenced by downLoadFinished(), and startToRequest().
void MusicDownloadQueueRequest::startToRequest () final override virtual
Start to download queue data.
Implements MusicAbstractDownLoadRequest.
Definition at line 34 of file musicdownloadqueuerequest.cpp.
References m_imageQueue, and startOrderImageQueue().
Referenced by handleError(), MusicScreenSaverWidget::initialize(), and MusicBackgroundRemoteWidget::startToRequest().
Member Data Documentation
MusicDownloadQueueDataList MusicDownloadQueueRequest::m_imageQueue private
Definition at line 97 of file musicdownloadqueuerequest.h.
Referenced by addImageQueue(), clear(), downLoadFinished(), startDownload(), startOrderImageQueue(), and startToRequest().
bool MusicDownloadQueueRequest::m_isAbort private
Definition at line 96 of file musicdownloadqueuerequest.h.
Referenced by abort(), downLoadFinished(), and handleError().
bool MusicDownloadQueueRequest::m_isDownload private
Definition at line 96 of file musicdownloadqueuerequest.h.
Referenced by abort(), downLoadFinished(), and startDownload().
QNetworkRequest* MusicDownloadQueueRequest::m_request private
Definition at line 98 of file musicdownloadqueuerequest.h.
Referenced by downLoadFinished(), MusicDownloadQueueRequest(), startDownload(), and ~MusicDownloadQueueRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadqueuerequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadqueuerequest.cpp