TTKMusicPlayer: QJsonDocument Class Reference
QJsonDocument Class Reference
#include <QJsonDocument.h>
Public Types
enum DataValidation { Validate = 0, BypassValidation = 1 }
enum JsonFormat { Indented, Compact }
Public Member Functions
QJsonDocument ()
QJsonDocument (const QJsonObject &object)
QJsonDocument (const QJsonArray &array)
QJsonDocument (const QJsonDocument &other)
~QJsonDocument ()
QJsonDocument & operator= (const QJsonDocument &other)
bool operator!= (const QJsonDocument &other) const
bool operator== (const QJsonDocument &other) const
bool isArray () const
bool isEmpty () const
bool isNull () const
bool isObject () const
QByteArray toBinaryData () const
QByteArray toJson (JsonFormat format=Indented) const
QVariant toVariant () const
QJsonArray array () const
QJsonObject object () const
const char * rawData (int *size) const
void setArray (const QJsonArray &array)
void setObject (const QJsonObject &object)
Static Public Member Functions
static QJsonDocument fromBinaryData (const QByteArray &data, DataValidation validation=Validate)
static QJsonDocument fromJson (const QByteArray &json, QJsonParseError *error=0)
static QJsonDocument fromRawData (const char *data, int size, DataValidation validation=Validate)
static QJsonDocument fromVariant (const QVariant &variant)
Private Member Functions
void setRoot (const QJsonRoot &root)
QString toJson (const QJsonValue &v, JsonFormat format, int indent=1) const
QString escapeString (const QString &s) const
void swap (QJsonDocument &other)
Private Attributes
QJsonRoot * root_
Detailed Description
Definition at line 37 of file QJsonDocument.h.
Member Enumeration Documentation
enum QJsonDocument::DataValidation
Enumerator
Validate
BypassValidation
Definition at line 39 of file QJsonDocument.h.
enum QJsonDocument::JsonFormat
Enumerator
Indented
Compact
Definition at line 44 of file QJsonDocument.h.
Constructor & Destructor Documentation
QJsonDocument::QJsonDocument ()
Definition at line 36 of file QJsonDocument.cpp.
Referenced by operator=().
QJsonDocument::QJsonDocument (const QJsonObject & object)
Definition at line 42 of file QJsonDocument.cpp.
References setObject().
QJsonDocument::QJsonDocument (const QJsonArray & array)
Definition at line 49 of file QJsonDocument.cpp.
References setArray().
QJsonDocument::QJsonDocument (const QJsonDocument & other)
Definition at line 56 of file QJsonDocument.cpp.
References QJsonRoot::clone(), and root_.
QJsonDocument::~QJsonDocument ()
Definition at line 65 of file QJsonDocument.cpp.
References root_.
Member Function Documentation
QJsonArray QJsonDocument::array () const
Definition at line 321 of file QJsonDocument.cpp.
References isEmpty(), root_, and QJsonRoot::toArray().
Referenced by operator==(), toJson(), and toVariant().
QString QJsonDocument::escapeString (const QString & s) const private
Definition at line 175 of file QJsonDocument.cpp.
Referenced by toJson().
QJsonDocument QJsonDocument::fromBinaryData (const QByteArray & data, DataValidation validation = Validate) static
Definition at line 358 of file QJsonDocument.cpp.
Referenced by fromRawData().
QJsonDocument QJsonDocument::fromJson (const QByteArray & json, QJsonParseError * error = 0) static
Definition at line 370 of file QJsonDocument.cpp.
References QJsonParser::parse(), root_, and QJsonParser::state().
Referenced by MusicServerPluginTableWidget::addCellItems(), MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicMVRadioCategoryRequest::downloadFinished(), MusicMVRadioProgramRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicWYCoverSourceRequest::downloadFinished(), MusicWYDownloadTextRequest::downloadFinished(), MusicKWDownloadTextRequest::downloadFinished(), MusicKGDownloadBackgroundRequest::downloadFinished(), MusicDownloadBingSkinRequest::downloadFinished(), MusicKGDiscoverListRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicDJRadioCategoryRequest::downloadFinished(), MusicBPDownloadBackgroundRequest::downloadFinished(), MusicPVCounterRequest::downloadFinished(), MusicResourceRequest::downloadFinished(), MusicBDTranslationRequest::downloadFinished(), MusicKWDownloadBackgroundRequest::downloadFinished(), MusicWYTranslationRequest::downloadFinished(), MusicYDTranslationRequest::downloadFinished(), MusicBingTranslationRequest::downloadFinished(), ToolQTFM::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicWYQueryArtistListRequest::downloadFinished(), MusicKWQueryArtistListRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYSongCommentsRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKGQueryAlbumRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicKGQueryArtistListRequest::downloadFinished(), MusicNetworkOperator::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicDownloadBirdSkinRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicKGQueryPlaylistRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicNewAlbumsRecommendRequest::downloadFinished(), MusicWYQueryPlaylistRequest::downloadFinished(), MusicKWQueryPlaylistRequest::downloadFinished(), MusicTXDownloadBackgroundRequest::downloadFinished(), MusicSourceUpdateRequest::downloadFinished(), MusicDJRadioProgramCategoryRequest::downloadFinished(), MusicWYQueryHotArtistListRequest::downloadFinished(), MusicKWQueryHotArtistListRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicWYPlaylistCommentsRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), MusicKGQueryArtistAlbumRequest::downloadFinished(), MusicKGQueryHotArtistListRequest::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicKGQueryArtistMovieRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicWYQueryArtistMovieRequest::downloadFinished(), MusicKGQueryPlaylistRecommendRequest::downloadFinished(), MusicArtistsRecommendRequest::downloadFinished(), MusicWYQueryNewAlbumRequest::downloadFinished(), MusicKWQueryNewAlbumRequest::downloadFinished(), MusicWYQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryNewAlbumRequest::downloadFinished(), MusicXFIdentifyRequest::downloadFinished(), MusicKWQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryPlaylistHighRequest::downloadFinished(), MusicWYQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistRecommendRequest::downloadFinished(), MusicKWQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistHQRecommendRequest::downloadFinished(), MusicDownloadBirdSkinRequest::downloadItemsFinished(), MusicCloudManagerTableWidget::downloadKeyFinished(), MusicIdentifySongRequest::downloadKeyFinished(), MusicKWQueryPlaylistRequest::downloadMoreDetailsFinished(), MusicKGQuerySongRequest::downloadSingleFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicWYQueryArtistMovieRequest::parseFromArtistMoviesCount(), ReqKWInterface::parseFromMovieInfo(), ReqBLInterface::parseFromMovieInfo(), MusicWYQueryMovieRequest::parseFromMovieList(), ReqKGInterface::parseFromMovieProperty(), ReqWYInterface::parseFromMovieProperty(), ReqBLInterface::parseFromMovieProperty(), ReqKGInterface::parseFromSongAlbumInfo(), ReqKGInterface::parseFromSongAlbumLrc(), ReqUnityInterface::parseFromSongProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyA(), parseSongPropertyB(), parseSongPropertyC(), parseSongPropertyE(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), parseSongPropertyX(), MusicKGQueryArtistRequest::queryArtistIntro(), MusicWYQueryArtistRequest::queryArtistIntro(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicKWQueryToplistRequest::queryToplistInfo(), MusicKGQueryToplistRequest::queryToplistInfo(), MusicJSPFConfigManager::readBuffer(), MusicServerPluginTableWidget::save(), ToolQTFM::startToListRequest(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicKWQueryPlaylistRequest::startToQueryInfo(), MusicWYQueryPlaylistRequest::startToQueryInfo(), and MusicBingTranslationRequest::startToRequest().
QJsonDocument QJsonDocument::fromRawData (const char * data, int size, DataValidation validation = Validate) static
Definition at line 390 of file QJsonDocument.cpp.
References fromBinaryData().
QJsonDocument QJsonDocument::fromVariant (const QVariant & variant) static
Definition at line 401 of file QJsonDocument.cpp.
References QJsonArray::fromStringList(), QJsonObject::fromVariantHash(), QJsonArray::fromVariantList(), QJsonObject::fromVariantMap(), setArray(), and setObject().
Referenced by MusicServerPluginTableWidget::save(), and MusicJSPFConfigManager::writeBuffer().
bool QJsonDocument::isArray () const
Definition at line 111 of file QJsonDocument.cpp.
References root_, and QJsonRoot::toArray().
Referenced by operator==(), and toJson().
bool QJsonDocument::isEmpty () const
Definition at line 118 of file QJsonDocument.cpp.
References root_.
Referenced by array(), object(), operator==(), and toVariant().
bool QJsonDocument::isNull () const
Definition at line 130 of file QJsonDocument.cpp.
References root_.
Referenced by operator==().
bool QJsonDocument::isObject () const
Definition at line 137 of file QJsonDocument.cpp.
References root_, and QJsonRoot::toObject().
Referenced by operator==(), and toJson().
QJsonObject QJsonDocument::object () const
Definition at line 335 of file QJsonDocument.cpp.
References isEmpty(), root_, and QJsonRoot::toObject().
Referenced by operator==().
bool QJsonDocument::operator!= (const QJsonDocument & other) const
Definition at line 80 of file QJsonDocument.cpp.
QJsonDocument & QJsonDocument::operator= (const QJsonDocument & other)
Definition at line 72 of file QJsonDocument.cpp.
References QJsonDocument().
bool QJsonDocument::operator== (const QJsonDocument & other) const
Definition at line 87 of file QJsonDocument.cpp.
References array(), isArray(), isEmpty(), isNull(), isObject(), and object().
const char * QJsonDocument::rawData (int * size) const
Definition at line 349 of file QJsonDocument.cpp.
void QJsonDocument::setArray (const QJsonArray & array)
Definition at line 144 of file QJsonDocument.cpp.
References setRoot().
Referenced by fromVariant(), and QJsonDocument().
void QJsonDocument::setObject (const QJsonObject & object)
Definition at line 151 of file QJsonDocument.cpp.
References setRoot().
Referenced by fromVariant(), and QJsonDocument().
void QJsonDocument::setRoot (const QJsonRoot & root) private
Definition at line 158 of file QJsonDocument.cpp.
References QJsonRoot::clone(), and root_.
Referenced by setArray(), and setObject().
void QJsonDocument::swap (QJsonDocument & other) private
Definition at line 421 of file QJsonDocument.cpp.
References root_.
QByteArray QJsonDocument::toBinaryData () const
Definition at line 166 of file QJsonDocument.cpp.
QByteArray QJsonDocument::toJson (JsonFormat format = Indented) const
Definition at line 283 of file QJsonDocument.cpp.
References array(), isArray(), and isObject().
Referenced by MusicServerPluginTableWidget::save(), toJson(), and MusicJSPFConfigManager::writeBuffer().
QString QJsonDocument::toJson (const QJsonValue & v, JsonFormat format, int indent = 1) const private
Definition at line 203 of file QJsonDocument.cpp.
References QJsonValue::Array, QJsonObject::begin(), QJsonArray::begin(), QJsonValue::Bool, Compact, QJsonValue::Double, QJsonObject::empty(), QJsonArray::empty(), QJsonObject::end(), QJsonArray::end(), escapeString(), QJsonValue::Null, QJsonValue::Object, QJsonValue::String, QJsonValue::toArray(), QJsonValue::toBool(), QJsonValue::toDouble(), toJson(), QJsonValue::toObject(), QJsonValue::toString(), QJsonValue::type(), and QJsonValue::Undefined.
QVariant QJsonDocument::toVariant () const
Definition at line 303 of file QJsonDocument.cpp.
References array(), isEmpty(), root_, QJsonRoot::toArray(), QJsonRoot::toObject(), and QJsonArray::toVariantList().
Referenced by MusicServerPluginTableWidget::addCellItems(), MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicMVRadioCategoryRequest::downloadFinished(), MusicMVRadioProgramRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicWYCoverSourceRequest::downloadFinished(), MusicWYDownloadTextRequest::downloadFinished(), MusicKWDownloadTextRequest::downloadFinished(), MusicKGDownloadBackgroundRequest::downloadFinished(), MusicDownloadBingSkinRequest::downloadFinished(), MusicKGDiscoverListRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicDJRadioCategoryRequest::downloadFinished(), MusicBPDownloadBackgroundRequest::downloadFinished(), MusicPVCounterRequest::downloadFinished(), MusicResourceRequest::downloadFinished(), MusicBDTranslationRequest::downloadFinished(), MusicKWDownloadBackgroundRequest::downloadFinished(), MusicWYTranslationRequest::downloadFinished(), MusicYDTranslationRequest::downloadFinished(), MusicBingTranslationRequest::downloadFinished(), ToolQTFM::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicWYQueryArtistListRequest::downloadFinished(), MusicKWQueryArtistListRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYSongCommentsRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKGQueryAlbumRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicKGQueryArtistListRequest::downloadFinished(), MusicNetworkOperator::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicDownloadBirdSkinRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicKGQueryPlaylistRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicNewAlbumsRecommendRequest::downloadFinished(), MusicWYQueryPlaylistRequest::downloadFinished(), MusicKWQueryPlaylistRequest::downloadFinished(), MusicTXDownloadBackgroundRequest::downloadFinished(), MusicSourceUpdateRequest::downloadFinished(), MusicDJRadioProgramCategoryRequest::downloadFinished(), MusicWYQueryHotArtistListRequest::downloadFinished(), MusicKWQueryHotArtistListRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicWYPlaylistCommentsRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), MusicKGQueryArtistAlbumRequest::downloadFinished(), MusicKGQueryHotArtistListRequest::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicKGQueryArtistMovieRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicWYQueryArtistMovieRequest::downloadFinished(), MusicKGQueryPlaylistRecommendRequest::downloadFinished(), MusicArtistsRecommendRequest::downloadFinished(), MusicWYQueryNewAlbumRequest::downloadFinished(), MusicKWQueryNewAlbumRequest::downloadFinished(), MusicWYQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryNewAlbumRequest::downloadFinished(), MusicXFIdentifyRequest::downloadFinished(), MusicKWQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryPlaylistHighRequest::downloadFinished(), MusicWYQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistRecommendRequest::downloadFinished(), MusicKWQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistHQRecommendRequest::downloadFinished(), MusicDownloadBirdSkinRequest::downloadItemsFinished(), MusicCloudManagerTableWidget::downloadKeyFinished(), MusicIdentifySongRequest::downloadKeyFinished(), MusicKWQueryPlaylistRequest::downloadMoreDetailsFinished(), MusicKGQuerySongRequest::downloadSingleFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicWYQueryArtistMovieRequest::parseFromArtistMoviesCount(), ReqKWInterface::parseFromMovieInfo(), ReqBLInterface::parseFromMovieInfo(), MusicWYQueryMovieRequest::parseFromMovieList(), ReqKGInterface::parseFromMovieProperty(), ReqWYInterface::parseFromMovieProperty(), ReqBLInterface::parseFromMovieProperty(), ReqKGInterface::parseFromSongAlbumInfo(), ReqKGInterface::parseFromSongAlbumLrc(), ReqUnityInterface::parseFromSongProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyA(), parseSongPropertyB(), parseSongPropertyC(), parseSongPropertyE(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), parseSongPropertyX(), MusicKGQueryArtistRequest::queryArtistIntro(), MusicWYQueryArtistRequest::queryArtistIntro(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicKWQueryToplistRequest::queryToplistInfo(), MusicKGQueryToplistRequest::queryToplistInfo(), MusicJSPFConfigManager::readBuffer(), MusicServerPluginTableWidget::save(), ToolQTFM::startToListRequest(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicKWQueryPlaylistRequest::startToQueryInfo(), MusicWYQueryPlaylistRequest::startToQueryInfo(), and MusicBingTranslationRequest::startToRequest().
Member Data Documentation
QJsonRoot* QJsonDocument::root_ private
Definition at line 98 of file QJsonDocument.h.
Referenced by array(), fromJson(), isArray(), isEmpty(), isNull(), isObject(), object(), QJsonDocument(), setRoot(), swap(), toVariant(), and ~QJsonDocument().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/QJsonDocument.h
TTKThirdParty/TTKExtras/qjson/QJsonDocument.cpp