TTKMusicplayer: MusicScreenSaverBackgroundWidget Class Reference
MusicScreenSaverBackgroundWidget Class Reference
The class of the screen saver background widget.
#include <musicscreensaverwidget.h>
Public Member Functions
MusicScreenSaverBackgroundWidget (QWidget *parent=nullptr)
~MusicScreenSaverBackgroundWidget ()
void applySettingParameter ()
Public Member Functions inherited from MusicTransitionAnimationLabel
MusicTransitionAnimationLabel (QWidget *parent=nullptr)
~MusicTransitionAnimationLabel ()
void setAnimation (bool on)
bool noAnimation () const
QPixmap rendererPixmap () const
void stop ()
Private Slots
void runningTimeout ()
void backgroundTimeout ()
Private Member Functions
virtual bool eventFilter (QObject *watched, QEvent *event) overridefinal
Private Attributes
bool m_state
bool m_isRunning
QTimer * m_runningTimer
QTimer * m_backgroundTimer
Additional Inherited Members
Public Types inherited from MusicTransitionAnimationLabel
enum AnimationType {
FadeEffect, BlindsEffect, CubeEffect, WaterEffect,
LeftToRightEffect, TopToBottomEffect
}
Public Slots inherited from MusicTransitionAnimationLabel
void setPixmap (const QPixmap &pix)
Protected Member Functions inherited from MusicTransitionAnimationLabel
virtual void paintEvent (QPaintEvent *event) overridefinal
Protected Attributes inherited from MusicTransitionAnimationLabel
AnimationType m_type
bool m_isAnimating
int m_currentValue
bool m_noAnimationSet
QPixmap m_rendererPixmap
QPixmap m_currentPixmap
QPixmap m_previousPixmap
QPropertyAnimation * m_animation
QAlgorithm::SharpeImage * m_cubeWave
QAlgorithm::SharpeImage * m_waterWave
Detailed Description
The class of the screen saver background widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 221 of file musicscreensaverwidget.h.
Constructor & Destructor Documentation
MusicScreenSaverBackgroundWidget::MusicScreenSaverBackgroundWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 399 of file musicscreensaverwidget.cpp.
References backgroundTimeout(), m_backgroundTimer, m_isRunning, m_runningTimer, m_state, MT_S2MS, and runningTimeout().
MusicScreenSaverBackgroundWidget::~MusicScreenSaverBackgroundWidget ()
Definition at line 418 of file musicscreensaverwidget.cpp.
References m_backgroundTimer, and m_runningTimer.
Member Function Documentation
void MusicScreenSaverBackgroundWidget::applySettingParameter ()
Apply settings parameters.
Definition at line 433 of file musicscreensaverwidget.cpp.
References G_SETTING_PTR, m_backgroundTimer, m_runningTimer, m_state, MT_M2MS, MusicSettingManager::OtherScreenSaverEnable, and MusicSettingManager::OtherScreenSaverTime.
Referenced by MusicApplicationModule::applySettingParameter().
void MusicScreenSaverBackgroundWidget::backgroundTimeout () private slot
Screen saver time out.
Definition at line 465 of file musicscreensaverwidget.cpp.
References CACHE_DIR_FULL, MusicUtils::Image::fusionPixmap(), OS_COUNT, OS_SCREEN_DIR, OS_WALLBAR_NAME, OS_WALLPAPER_NAME, MusicScreenSaverWidget::parseSettingParameter(), MusicTime::random(), and MusicTransitionAnimationLabel::setPixmap().
Referenced by MusicScreenSaverBackgroundWidget(), and runningTimeout().
bool MusicScreenSaverBackgroundWidget::eventFilter (QObject * watched, QEvent * event) final override private virtual
Override the widget event.
Definition at line 488 of file musicscreensaverwidget.cpp.
References m_backgroundTimer, m_isRunning, m_runningTimer, and m_state.
void MusicScreenSaverBackgroundWidget::runningTimeout () private slot
Screen saver time out.
Definition at line 451 of file musicscreensaverwidget.cpp.
References backgroundTimeout(), m_backgroundTimer, m_isRunning, and TTKDesktopWrapper::screenGeometry().
Referenced by MusicScreenSaverBackgroundWidget().
Member Data Documentation
QTimer* MusicScreenSaverBackgroundWidget::m_backgroundTimer private
Definition at line 257 of file musicscreensaverwidget.h.
Referenced by applySettingParameter(), eventFilter(), MusicScreenSaverBackgroundWidget(), runningTimeout(), and ~MusicScreenSaverBackgroundWidget().
bool MusicScreenSaverBackgroundWidget::m_isRunning private
Definition at line 255 of file musicscreensaverwidget.h.
Referenced by eventFilter(), MusicScreenSaverBackgroundWidget(), and runningTimeout().
QTimer* MusicScreenSaverBackgroundWidget::m_runningTimer private
Definition at line 256 of file musicscreensaverwidget.h.
Referenced by applySettingParameter(), eventFilter(), MusicScreenSaverBackgroundWidget(), and ~MusicScreenSaverBackgroundWidget().
bool MusicScreenSaverBackgroundWidget::m_state private
Definition at line 254 of file musicscreensaverwidget.h.
Referenced by applySettingParameter(), eventFilter(), and MusicScreenSaverBackgroundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.cpp