TTKMusicplayer: MusicKWQueryArtistRequest Class Reference
MusicKWQueryArtistRequest Class Reference
The class of kuwo query artist download data from net.
#include <musickwqueryartistrequest.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWQueryArtistRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &artist) override
Public Member Functions inherited from MusicQueryArtistRequest
MusicQueryArtistRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &artist) override
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSingleSearch (const QString &text)
void setQueryQuality (const QString &qual)
QString getQueryQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getQueryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int getPageSize () const
int getTotalSize () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
void getDownLoadIntro (MusicResultsItem *item)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryArtistRequest
void createArtistInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 getUrlFileSize (const QString &url)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicKWQueryInterface
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantList &format, const QString &quality, bool all)
void readFromMusicSongPicture (MusicObject::MusicSongInformation *info)
Detailed Description
The class of kuwo query artist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musickwqueryartistrequest.h.
Constructor & Destructor Documentation
MusicKWQueryArtistRequest::MusicKWQueryArtistRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musickwqueryartistrequest.cpp.
References MusicAbstractQueryRequest::m_queryServer, and QUERY_KW_INTERFACE.
Member Function Documentation
void MusicKWQueryArtistRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 29 of file musickwqueryartistrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicQueryArtistRequest::createArtistInfoItem(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicAbstractQueryRequest::findUrlFileSize(), getDownLoadIntro(), KW_SONG_LRC_URL, MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicResultsItem::m_coverUrl, MusicObject::MusicSongInformation::m_discNumber, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicResultsItem::m_id, MusicObject::MusicSongInformation::m_lrcUrl, MusicAbstractQueryRequest::m_musicSongInfos, MusicResultsItem::m_name, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_queryQuality, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicKWQueryInterface::readFromMusicSongAttribute(), MusicKWQueryInterface::readFromMusicSongPicture(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicKWQueryArtistRequest::getDownLoadIntro (MusicResultsItem * item) protected
Get Download introduction data from net.
Definition at line 115 of file musickwqueryartistrequest.cpp.
References MusicUtils::String::convertHtmlToPlain(), KW_ARTIST_INFO_URL, MusicResultsItem::m_description, MusicResultsItem::m_nickName, MusicAbstractQueryRequest::m_queryText, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicObject::syncNetworkQueryForGet().
Referenced by downLoadFinished().
void MusicKWQueryArtistRequest::startToSearch (const QString & artist) override virtual
Start to Search data from name and type.
Implements MusicQueryArtistRequest.
Definition at line 9 of file musickwqueryartistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KW_ARTIST_URL, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_queryText, MusicAbstractNetwork::m_reply, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryartistrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryartistrequest.cpp