TTKMusicplayer: MusicConnectionPool Class Reference
MusicConnectionPool Class Reference
The class of the qt signal and slot connection pool.
#include <musicconnectionpool.h>
Public Member Functions
void setValue (const QString &type, QObject *object)
QObject * value (const QString &type) const
const QObject * operator[] (const QString &type) const
QObject *& operator[] (const QString &type)
void setNetworkMultiValue (QObject *object)
void removeNetworkMultiValue (QObject *object)
void connectMusicDownload (QObject *object)
void poolConnect (const QObject *from, const QObject *to)
void poolConnect (const QString &from, const QString &to)
void removeValue (const QObject *object)
void removeValue (const QString &name)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
MusicConnectionPool ()
Protected Attributes
QMap< QString, QObject * > m_para
QList< QObject * > m_queueList
Detailed Description
The class of the qt signal and slot connection pool.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 21 of file musicconnectionpool.h.
Constructor & Destructor Documentation
MusicConnectionPool::MusicConnectionPool () protected
Object contsructor.
Definition at line 27 of file musicconnectionpool.cpp.
Member Function Documentation
void MusicConnectionPool::connectMusicDownload (QObject * object)
Set music data network connection object.
Definition at line 48 of file musicconnectionpool.cpp.
References MusicDownloadRecordWidget::getClassName(), MusicCloudDownloadTableWidget::getClassName(), and m_para.
QString MusicConnectionPool::getClassName () static
Get class object name.
Definition at line 33 of file musicconnectionpool.cpp.
const QObject* MusicConnectionPool::operator[] (const QString & type) const inline
Get connection object by type name in operator[].
Definition at line 46 of file musicconnectionpool.h.
QObject* & MusicConnectionPool::operator[] (const QString & type) inline
Set connection object and type name in operator[].
Definition at line 53 of file musicconnectionpool.h.
void MusicConnectionPool::poolConnect (const QObject * from, const QObject * to)
Set connection by two object.
Definition at line 144 of file musicconnectionpool.cpp.
void MusicConnectionPool::poolConnect (const QString & from, const QString & to)
Set connection by two object type name.
Definition at line 78 of file musicconnectionpool.cpp.
References MusicNetworkThread::getClassName(), MusicQueryFoundTableWidget::getClassName(), MusicVideoQualityPopWidget::getClassName(), MusicVideoTableWidget::getClassName(), MusicDownloadStatusObject::getClassName(), MusicDownloadRecordWidget::getClassName(), MusicConnectTransferWidget::getClassName(), MusicSongsSummariziedWidget::getClassName(), MusicSongCheckToolsWidget::getClassName(), MusicEqualizerDialog::getClassName(), MusicLocalSongsManagerWidget::getClassName(), MusicPlayer::getClassName(), MusicSongSearchOnlineTableWidget::getClassName(), MusicCloudDownloadTableWidget::getClassName(), MusicSongCheckToolsDuplicateTableWidget::getClassName(), MusicLrcLocalLinkWidget::getClassName(), MusicLrcMakerWidget::getClassName(), MusicSoundEffectsWidget::getClassName(), MusicSongCheckToolsQualityTableWidget::getClassName(), and m_para.
void MusicConnectionPool::removeNetworkMultiValue (QObject * object)
Remove mutiple network connection object.
Definition at line 69 of file musicconnectionpool.cpp.
References m_queueList.
void MusicConnectionPool::removeValue (const QObject * object)
Remove connection object by object.
Definition at line 154 of file musicconnectionpool.cpp.
References m_para.
void MusicConnectionPool::removeValue (const QString & name)
Remove connection object by object name.
Definition at line 149 of file musicconnectionpool.cpp.
References m_para.
void MusicConnectionPool::setNetworkMultiValue (QObject * object)
Set mutiple network connection object.
Definition at line 38 of file musicconnectionpool.cpp.
References MusicDownloadStatusObject::getClassName(), m_para, and m_queueList.
void MusicConnectionPool::setValue (const QString & type, QObject * object) inline
Set connection object and type name.
Definition at line 32 of file musicconnectionpool.h.
QObject* MusicConnectionPool::value (const QString & type) const inline
Get connection object by type name.
Definition at line 39 of file musicconnectionpool.h.
Member Data Documentation
QMap<QString, QObject*> MusicConnectionPool::m_para protected
Definition at line 89 of file musicconnectionpool.h.
Referenced by connectMusicDownload(), poolConnect(), removeValue(), and setNetworkMultiValue().
QList<QObject*> MusicConnectionPool::m_queueList protected
Definition at line 90 of file musicconnectionpool.h.
Referenced by removeNetworkMultiValue(), and setNetworkMultiValue().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicconnectionpool.h
TTKModule/TTKCore/musicCoreKits/musicconnectionpool.cpp