TTKMusicplayer: MusicQueryPlaylistRequest Class Reference
MusicQueryPlaylistRequest Class Reference abstract
The class of query playlist download data from net.
#include <musicqueryplaylistrequest.h>
Signals
void createPlaylistItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Public Member Functions
MusicQueryPlaylistRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value)=0
virtual void queryPlaylistInfo (MusicResultsItem &item)=0
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &value)=0
virtual void startToSingleSearch (const QString &value)
void setQueryQuality (MusicObject::QueryQuality quality)
MusicObject::QueryQuality queryQuality () const
void setQueryAllRecords (bool state)
bool queryAllRecords () const
void setQueryLite (bool state)
bool queryLite () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryValue () const
void setSongInfoList (const MusicObject::MusicSongInformationList &songInfos)
const MusicObject::MusicSongInformationList & songInfoList () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryServer { WYQueryServer, QQQueryServer, KWQueryServer, KGQueryServer }
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 fileSizeByUrl (const QString &url)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongProperty *prop) const
bool findUrlFileSize (MusicObject::MusicSongPropertyList *props) const
Protected Attributes inherited from MusicAbstractQueryRequest
QString m_queryValue
QString m_queryServer
QueryType m_queryType
MusicObject::QueryQuality m_queryQuality
bool m_queryAllRecords
bool m_queryLite
MusicObject::MusicSongInformationList m_songInfos
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of query playlist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicqueryplaylistrequest.h.
Constructor & Destructor Documentation
MusicQueryPlaylistRequest::MusicQueryPlaylistRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicqueryplaylistrequest.cpp.
Member Function Documentation
void MusicQueryPlaylistRequest::createPlaylistItem (const MusicResultsItem & item) signal
Create the current playlist item.
Referenced by MusicKGQueryPlaylistRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), and MusicKWQueryPlaylistRequest::downloadMoreDetailsFinished().
virtual void MusicQueryPlaylistRequest::queryPlaylistInfo (MusicResultsItem & item) pure virtual
Query playlist info.
Implemented in MusicKGQueryPlaylistRequest, MusicKWQueryPlaylistRequest, MusicQQQueryPlaylistRequest, and MusicWYQueryPlaylistRequest.
Referenced by MusicPlaylistQueryWidget::currentPlaylistClicked().
virtual void MusicQueryPlaylistRequest::startToSearch (const QString & value) pure virtual
Start to Search data.
Implemented in MusicKGQueryPlaylistRequest, MusicKWQueryPlaylistRequest, MusicQQQueryPlaylistRequest, and MusicWYQueryPlaylistRequest.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicqueryplaylistrequest.h
TTKModule/TTKCore/musicNetworkKits/musicqueryplaylistrequest.cpp