TTKMusicPlayer: MusicNetworkOperator Class Reference
MusicNetworkOperator Class Reference
The class of the music network operator.
#include <musicnetworkoperator.h>
Signals
void queryNetworkOperatorFinished (const QString &name)
Public Member Functions
MusicNetworkOperator (QObject *parent=nullptr)
void startRequest ()
Private Slots
void downLoadFinished (const QByteArray &bytes)
Detailed Description
The class of the music network operator.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicnetworkoperator.h.
Constructor & Destructor Documentation
MusicNetworkOperator::MusicNetworkOperator (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicnetworkoperator.cpp.
Member Function Documentation
void MusicNetworkOperator::downLoadFinished (const QByteArray & bytes) private slot
Download data from net finished.
Definition at line 19 of file musicnetworkoperator.cpp.
References QJson::Parser::parse(), queryNetworkOperatorFinished(), and TTK_ERROR_STREAM.
Referenced by startRequest().
void MusicNetworkOperator::queryNetworkOperatorFinished (const QString & name) signal
Query network operator is finished.
Referenced by downLoadFinished().
void MusicNetworkOperator::startRequest ()
Start to download data from net.
Definition at line 12 of file musicnetworkoperator.cpp.
References downLoadFinished(), IP_CHECK_URL, MusicUtils::Algorithm::mdII(), and MusicDownloadSourceRequest::startRequest().
Referenced by MusicSettingWidget::testNetworkConnection().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicnetworkoperator.h
TTKModule/TTKCore/musicNetworkKits/tools/musicnetworkoperator.cpp