TTKMusicPlayer: TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryinterface.cpp File Reference
musickgqueryinterface.cpp File Reference
#include "musickgqueryinterface.h"
#include "musicunityqueryinterface.h"
Functions
static void parseSongPropertyV1 (TTK::MusicSongInformation *info, const QString &hash, int bitrate)
static void parseSongPropertyV2 (TTK::MusicSongInformation *info, const QString &hash, int bitrate)
static void parseSongPropertyV3 (TTK::MusicSongInformation *info, const QString &module, QString &id, int bitrate)
static void parseSongPropertyV3 (TTK::MusicSongInformation *info, const QString &hash, int bitrate)
static void parseSongPropertyUnity (TTK::MusicSongInformation *info, const QString &hash, int bitrate)
static void parseSongProperty (TTK::MusicSongInformation *info, const QString &hash, int bitrate)
Variables
static constexpr const char * KG_UA_URL = "cGhYNDZVdmNaVG5KZk50NVFvcUJyYWVQdmdNTkFTMmM="
static constexpr const char * KG_COOKIE_URL = "M1BlYjdvWUlwdHJIYXgzeGpUVDlWbnB6ZGZPaUxWVzhKdEZ2RHBHR1RBckFUbG82ZzlOOHRnMW0wUUZpVmdDNGNQMFFjTXd1OVhidmwvdHh6NjNkZ08reXEzWUl0ZXl3d21Ka3ErM1Q1eEp3WUs0YkYvV3dWVUFDSVd3YmI3c3U3c09pZTlIM1FQRFUyMG43Z2ZqRXJVTHhubkhjRC9EN3hVbzhia1QzdUZQU3orRzZZRmRncGZLazhkMD0="
static constexpr const char * KG_SONG_PATH_V1_URL = "c0FiK1UzOWFtRGNobi9oYlo1WmpEbWUwRzR0UStHd1lkZFFRakxkSGlMZmpHMmoxOWc4NGtGa3NJRUtiVXJEYlJqYzNYNmRHNlZ0dUZIR05Rb0RZcUgyb2lFMm5pNU9KaDhMeHNkQnJzcWJqeHhwQWdpUXBPV1ZEQ05RT0kvNE5IWG9qZ2hYYk9BMG8yQ25qbzFYUGFYeUVMWVk9"
static constexpr const char * KG_SONG_PATH_V2_URL = "Q3dWL3pJbVlWTDY1Nk0vT3BkYWNGNC9ObWEyVmtyQ3lqVFlUZjE1VjU2V0ZhZFN2L1hFUXlob1JxM2Zjak9KcjBPZGE1QkxQRlhUaFpEMWxQNDMzbmdjWG5kMVNxRy9zR0tvVXB5SDlZUHl1OVUzaGlVM2NHUTBTY0l4cG1GNjY0alYzdmI5eU1ldXB2KzFzU2JHMkgrTHdxaUdSL3pwY0o1bk9kSk1GcG4yK2JVSndqUFRYNXRTbkk5VHBQcVM0Y256ZElxV1BCcy80NGpXaXNvWWZvQT09"
static constexpr const char * KG_SONG_PATH_V3_URL = "b1VyUUJFN3l5RG0wZkhxZ2RHazUyRDVraGNXK21oODUvVWZCUHJ0TWx0VFJsdEwyemdzd0JmdnFRNFJQRitRb1NIVkZuTWZmUjlya2UrWi9pQ0Z0MjVFV2FZU1lDU3lieXBOb0RaVXVVcU5DR0xEYlQySXFHbXhKWjZ5ZkFuOEJmNzdGQ0tTNVFGMkg3eldDR3VqOUUxQWJKNzh6YWZPZzkyYUtKeFNORnB6bVlzZ1grYWduWXNBN1BDdENrb0ZEMklhSDVacmhBNkZiRWFPUDh6VXFIcnMzQUZqY0FYaG5ZbytGZkJUTnpJNTlLRHVZZitkYVlDVXR3Slh5U1IrSU9TbmF5TUxJZ0dJeGRxL0EwaDB2Qm1RUnBnTHM2bVdFQUsyRzZqeC83bTBjQ1RsSlB3dEVLcFlqdUU2c095aGN1cVJhR1E9PQ=="
static constexpr const char * KG_SONG_PATH_V3_DATA_URL = "V1RsSGgvREcwWDBLNGdHeE5weEdoRWZCYVFhL2RlZDRBTUcxQXJqZlFIRXhsQzkzaldUclNodG1kSDJtekJXSjVlVGtEYUU1bkxYcTBrRjM1dHd0dFhhM2ZZd1B4N255Wk5MYWRBTWQwclF2dEIwenlLcFNVSXZGY1RZRXNVcDcwSUdJaVlQNmh1RnNQQVpMTVRrZ003YmI4RmcwTS9Jc1lFZ2VvbnFNYU1ZN0RMUVNwVkFoZFhsOVk1UXJGanpNbUpZWmpjdlZUQjlVc3FraENVMGF4SFIvOEVSS0o4ZVBEWC9iME52Q3lWNDdKYTFadXlCQ20rM0JueWtZVjBCZGdtM2NMakRSQzl3YlZRZEFPQnRvZEU3aHhiVnZ0aEJNemtUWWE5amFOaVk3RVBGdFBkSzRPQTRsYklZYTltNy9rRUNVc3dMZmI4WT0="
static constexpr const char * KG_ALBUM_INFO_URL = "ejhjT0JOd0RyMWtmaTdTa2x4REdsMXlucDkyYk8wT3RTZ21DOVVTeU15MFQ1Z1k0SVJ6bHdiY2hNVURKRE91NGdWSWc2NTJNZEsyNnF0b0YrK0E0TSs3UjRKam40VmhqM0JxTWI1dmtyR1ZQWk1tOGFnR1NGcnAzVzJ4M3dvZWU2YlhMR0IvZWVSND0="
Function Documentation
static void parseSongProperty (TTK::MusicSongInformation * info, const QString & hash, int bitrate) static
Definition at line 298 of file musickgqueryinterface.cpp.
References MusicSettingManager::DownloadServerPriority, G_SETTING_PTR, parseSongPropertyUnity(), parseSongPropertyV1(), parseSongPropertyV2(), and parseSongPropertyV3().
Referenced by ReqKGInterface::parseFromSongProperty().
static void parseSongPropertyUnity (TTK::MusicSongInformation * info, const QString & hash, int bitrate) static
Definition at line 280 of file musickgqueryinterface.cpp.
References TTK::MusicSongInformation::m_songProps, ReqUnityInterface::parseFromSongProperty(), qAsConst, QUERY_KG_INTERFACE, TTK_BN_1000, TTK_BN_128, TTK_BN_320, and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV1 (TTK::MusicSongInformation * info, const QString & hash, int bitrate) static
Definition at line 134 of file musickgqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), key, KG_SONG_PATH_V1_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqKGInterface::makeRequestRawHeader(), TTK::Algorithm::md5(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV2 (TTK::MusicSongInformation * info, const QString & hash, int bitrate) static
Definition at line 173 of file musickgqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), key, KG_SONG_PATH_V2_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqKGInterface::makeRequestRawHeader(), TTK::Algorithm::md5(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV3 (TTK::MusicSongInformation * info, const QString & module, QString & id, int bitrate) static
Definition at line 220 of file musickgqueryinterface.cpp.
References TTKDateTime::currentTimestamp(), QJsonParseError::error, FLAC_FILE_SUFFIX, QJsonDocument::fromJson(), key, KG_SONG_PATH_V3_DATA_URL, KG_SONG_PATH_V3_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqKGInterface::makeRequestRawHeader(), TTK::Algorithm::md5(), TTK::Algorithm::mdII(), MP3_FILE_SUFFIX, QJsonParseError::NoError, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), and TTK_BN_320.
Referenced by parseSongProperty(), and parseSongPropertyV3().
static void parseSongPropertyV3 (TTK::MusicSongInformation * info, const QString & hash, int bitrate) static
Definition at line 259 of file musickgqueryinterface.cpp.
References TTK::MusicSongInformation::m_songProps, parseSongPropertyV3(), qAsConst, and TTK_INFO_STREAM.
Variable Documentation
constexpr const char* KG_ALBUM_INFO_URL = "ejhjT0JOd0RyMWtmaTdTa2x4REdsMXlucDkyYk8wT3RTZ21DOVVTeU15MFQ1Z1k0SVJ6bHdiY2hNVURKRE91NGdWSWc2NTJNZEsyNnF0b0YrK0E0TSs3UjRKam40VmhqM0JxTWI1dmtyR1ZQWk1tOGFnR1NGcnAzVzJ4M3dvZWU2YlhMR0IvZWVSND0=" static
Definition at line 11 of file musickgqueryinterface.cpp.
Referenced by ReqKGInterface::parseFromSongAlbumInfo().
constexpr const char* KG_COOKIE_URL = "M1BlYjdvWUlwdHJIYXgzeGpUVDlWbnB6ZGZPaUxWVzhKdEZ2RHBHR1RBckFUbG82ZzlOOHRnMW0wUUZpVmdDNGNQMFFjTXd1OVhidmwvdHh6NjNkZ08reXEzWUl0ZXl3d21Ka3ErM1Q1eEp3WUs0YkYvV3dWVUFDSVd3YmI3c3U3c09pZTlIM1FQRFUyMG43Z2ZqRXJVTHhubkhjRC9EN3hVbzhia1QzdUZQU3orRzZZRmRncGZLazhkMD0=" static
Definition at line 5 of file musickgqueryinterface.cpp.
Referenced by ReqKGInterface::makeRequestRawHeader().
constexpr const char* KG_SONG_PATH_V1_URL = "c0FiK1UzOWFtRGNobi9oYlo1WmpEbWUwRzR0UStHd1lkZFFRakxkSGlMZmpHMmoxOWc4NGtGa3NJRUtiVXJEYlJqYzNYNmRHNlZ0dUZIR05Rb0RZcUgyb2lFMm5pNU9KaDhMeHNkQnJzcWJqeHhwQWdpUXBPV1ZEQ05RT0kvNE5IWG9qZ2hYYk9BMG8yQ25qbzFYUGFYeUVMWVk9" static
Definition at line 7 of file musickgqueryinterface.cpp.
Referenced by parseSongPropertyV1().
constexpr const char* KG_SONG_PATH_V2_URL = "Q3dWL3pJbVlWTDY1Nk0vT3BkYWNGNC9ObWEyVmtyQ3lqVFlUZjE1VjU2V0ZhZFN2L1hFUXlob1JxM2Zjak9KcjBPZGE1QkxQRlhUaFpEMWxQNDMzbmdjWG5kMVNxRy9zR0tvVXB5SDlZUHl1OVUzaGlVM2NHUTBTY0l4cG1GNjY0alYzdmI5eU1ldXB2KzFzU2JHMkgrTHdxaUdSL3pwY0o1bk9kSk1GcG4yK2JVSndqUFRYNXRTbkk5VHBQcVM0Y256ZElxV1BCcy80NGpXaXNvWWZvQT09" static
Definition at line 8 of file musickgqueryinterface.cpp.
Referenced by parseSongPropertyV2().
constexpr const char* KG_SONG_PATH_V3_DATA_URL = "V1RsSGgvREcwWDBLNGdHeE5weEdoRWZCYVFhL2RlZDRBTUcxQXJqZlFIRXhsQzkzaldUclNodG1kSDJtekJXSjVlVGtEYUU1bkxYcTBrRjM1dHd0dFhhM2ZZd1B4N255Wk5MYWRBTWQwclF2dEIwenlLcFNVSXZGY1RZRXNVcDcwSUdJaVlQNmh1RnNQQVpMTVRrZ003YmI4RmcwTS9Jc1lFZ2VvbnFNYU1ZN0RMUVNwVkFoZFhsOVk1UXJGanpNbUpZWmpjdlZUQjlVc3FraENVMGF4SFIvOEVSS0o4ZVBEWC9iME52Q3lWNDdKYTFadXlCQ20rM0JueWtZVjBCZGdtM2NMakRSQzl3YlZRZEFPQnRvZEU3aHhiVnZ0aEJNemtUWWE5amFOaVk3RVBGdFBkSzRPQTRsYklZYTltNy9rRUNVc3dMZmI4WT0=" static
Definition at line 10 of file musickgqueryinterface.cpp.
Referenced by parseSongPropertyV3().
constexpr const char* KG_SONG_PATH_V3_URL = "b1VyUUJFN3l5RG0wZkhxZ2RHazUyRDVraGNXK21oODUvVWZCUHJ0TWx0VFJsdEwyemdzd0JmdnFRNFJQRitRb1NIVkZuTWZmUjlya2UrWi9pQ0Z0MjVFV2FZU1lDU3lieXBOb0RaVXVVcU5DR0xEYlQySXFHbXhKWjZ5ZkFuOEJmNzdGQ0tTNVFGMkg3eldDR3VqOUUxQWJKNzh6YWZPZzkyYUtKeFNORnB6bVlzZ1grYWduWXNBN1BDdENrb0ZEMklhSDVacmhBNkZiRWFPUDh6VXFIcnMzQUZqY0FYaG5ZbytGZkJUTnpJNTlLRHVZZitkYVlDVXR3Slh5U1IrSU9TbmF5TUxJZ0dJeGRxL0EwaDB2Qm1RUnBnTHM2bVdFQUsyRzZqeC83bTBjQ1RsSlB3dEVLcFlqdUU2c095aGN1cVJhR1E9PQ==" static
Definition at line 9 of file musickgqueryinterface.cpp.
Referenced by parseSongPropertyV3().
constexpr const char* KG_UA_URL = "cGhYNDZVdmNaVG5KZk50NVFvcUJyYWVQdmdNTkFTMmM=" static
Definition at line 4 of file musickgqueryinterface.cpp.
Referenced by ReqKGInterface::makeRequestRawHeader().