TTKMusicplayer: MusicDataTagDownloadThread Class Reference
MusicDataTagDownloadThread Class Reference
The class of downloading the type of data by custom tags.
#include <musicdatatagdownloadthread.h>
Public Slots
virtual void downLoadFinished () override
void downLoadFinished (const QByteArray &data)
Public Slots inherited from MusicDataDownloadThread
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal) override
virtual void updateDownloadSpeed () override
void downLoadReadyRead ()
Public Slots inherited from MusicDownLoadThreadAbstract
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void finished ()
Signals inherited from MusicDataDownloadThread
void downloadUrlChanged (const QString &url)
void downloadSpeedLabelChanged (const QString &speed, qint64 timeLeft)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDataTagDownloadThread (const QString &url, const QString &save, Download_Type type, QObject *parent=0)
void setTags (const QString &smlUrl, const QString &title, const QString &artist)
virtual void startToDownload () override
Public Member Functions inherited from MusicDataDownloadThread
MusicDataDownloadThread (const QString &url, const QString &save, Download_Type type, QObject *parent=0)
Public Member Functions inherited from MusicDownLoadThreadAbstract
MusicDownLoadThreadAbstract (const QString &url, const QString &save, Download_Type type, QObject *parent=0)
virtual ~MusicDownLoadThreadAbstract ()
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDataDownloadThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Attributes
QString m_smallPicUrl
QString m_title
QString m_artist
Protected Attributes inherited from MusicDataDownloadThread
qint64 m_createItemTime
bool m_redirection
bool m_needUpdate
Protected Attributes inherited from MusicDownLoadThreadAbstract
QFile * m_file
QString m_url
QString m_savePathName
Download_Type m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_timer
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicDownLoadThreadAbstract
enum Download_Type {
Download_Music, Download_Lrc, Download_SmlBG, Download_BigBG,
Download_Video, Download_Other
}
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Protected Member Functions inherited from MusicDataDownloadThread
void startRequest (const QUrl &url)
Protected Member Functions inherited from MusicDownLoadThreadAbstract
QString transferData () const
Detailed Description
The class of downloading the type of data by custom tags.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdatatagdownloadthread.h.
Constructor & Destructor Documentation
MusicDataTagDownloadThread::MusicDataTagDownloadThread (const QString & url, const QString & save, Download_Type type, QObject * parent = 0)
Object contsructor provide download URL\ save local path and download type.
Definition at line 8 of file musicdatatagdownloadthread.cpp.
References MusicDataDownloadThread::m_needUpdate.
Member Function Documentation
void MusicDataTagDownloadThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 52 of file musicdatatagdownloadthread.cpp.
References MusicNetworkAbstract::downLoadDataChanged(), MusicDataDownloadThread::downLoadFinished(), MusicSemaphoreLoop::exec(), finished(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_INFO, MusicDataDownloadThread::m_redirection, m_smallPicUrl, MusicDownloadSourceThread::startToDownload(), and MusicDownLoadThreadAbstract::transferData().
Referenced by startToDownload().
void MusicDataTagDownloadThread::downLoadFinished (const QByteArray & data) slot
Send download byte data from net.
Definition at line 76 of file musicdatatagdownloadthread.cpp.
References finished(), m_artist, M_LOGGER_INFO, MusicDownLoadThreadAbstract::m_savePathName, m_title, MusicSongTag::read(), MusicSongTag::save(), MusicSongTag::setArtist(), MusicSongTag::setCover(), and MusicSongTag::setTitle().
void MusicDataTagDownloadThread::finished () signal
Modify tag finished.
Referenced by downLoadFinished(), and startToDownload().
QString MusicDataTagDownloadThread::getClassName () static
Get class object name.
Definition at line 15 of file musicdatatagdownloadthread.cpp.
Referenced by startToDownload().
void MusicDataTagDownloadThread::setTags (const QString & smlUrl, const QString & title, const QString & artist)
Set custom tags.
Definition at line 20 of file musicdatatagdownloadthread.cpp.
References m_artist, m_smallPicUrl, and m_title.
Referenced by MusicDownloadBatchTableItem::startToDownload(), and MusicDownloadWidget::startToDownloadMusic().
void MusicDataTagDownloadThread::startToDownload () override virtual
Start to download data.
Reimplemented from MusicDataDownloadThread.
Definition at line 27 of file musicdatatagdownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), downLoadFinished(), finished(), getClassName(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_ERROR, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_url, MusicDownLoadThreadAbstract::sslErrors(), and MusicDataDownloadThread::startRequest().
Referenced by MusicDownloadBatchTableItem::startToDownload(), and MusicDownloadWidget::startToDownloadMusic().
Member Data Documentation
QString MusicDataTagDownloadThread::m_artist protected
Definition at line 69 of file musicdatatagdownloadthread.h.
Referenced by downLoadFinished(), and setTags().
QString MusicDataTagDownloadThread::m_smallPicUrl protected
Definition at line 68 of file musicdatatagdownloadthread.h.
Referenced by downLoadFinished(), and setTags().
QString MusicDataTagDownloadThread::m_title protected
Definition at line 69 of file musicdatatagdownloadthread.h.
Referenced by downLoadFinished(), and setTags().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/nr/musicdatatagdownloadthread.h
TTKModule/TTKCore/musicNetworkKits/nr/musicdatatagdownloadthread.cpp