TTKMusicplayer: MusicAudioRecorderCore Class Reference
MusicAudioRecorderCore Class Reference
The class of the audio recorder core.
#include <musicaudiorecordercore.h>
Classes
struct HEADER
The class of the audio file tag header.
Public Types
typedef struct MUSIC_TOOLSET_EXPORT MusicAudioRecorderCore::HEADER HEADER
The class of the audio file tag header.
Public Slots
void onRecordStart ()
void onRecordStop ()
void onRecordPlay ()
void onStateChange (QAudio::State state)
Public Member Functions
MusicAudioRecorderCore (QObject *parent=0)
~MusicAudioRecorderCore ()
int addWavHeader (const char *filename)
void setVolume (int volume)
int volume () const
void setFileName (const QString &name)
QString getFileName () const
bool error () const
Static Public Member Functions
static QString getClassName ()
Protected Attributes
int m_inputVolume
QAudioFormat m_mFormatFile
QFile * m_mpOutputFile
QAudioInput * m_mpAudioInputFile
QAudioOutput * m_mpAudioOutputFile
Detailed Description
The class of the audio recorder core.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 22 of file musicaudiorecordercore.h.
Member Typedef Documentation
typedef struct MUSIC_TOOLSET_EXPORT MusicAudioRecorderCore::HEADER MusicAudioRecorderCore::HEADER
The class of the audio file tag header.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Constructor & Destructor Documentation
MusicAudioRecorderCore::MusicAudioRecorderCore (QObject * parent = 0) explicit
Object contsructor.
Definition at line 10 of file musicaudiorecordercore.cpp.
References m_inputVolume, M_LOGGER_INFO, M_LOGGER_WARN, m_mFormatFile, m_mpAudioInputFile, m_mpAudioOutputFile, m_mpOutputFile, and MUSIC_RECORD_FILE.
MusicAudioRecorderCore::~MusicAudioRecorderCore ()
Definition at line 45 of file musicaudiorecordercore.cpp.
References m_mpAudioInputFile, m_mpAudioOutputFile, m_mpOutputFile, MUSIC_RECORD_FILE, MUSIC_RECORD_IN_FILE, and MUSIC_RECORD_OUT_FILE.
Member Function Documentation
int MusicAudioRecorderCore::addWavHeader (const char * filename)
Add the header of wav.
Definition at line 61 of file musicaudiorecordercore.cpp.
References MusicAudioRecorderCore::HEADER::DATANAME, MusicAudioRecorderCore::HEADER::FMTNAME, m_mpOutputFile, MusicAudioRecorderCore::HEADER::nAudioFormat, MusicAudioRecorderCore::HEADER::nBitsPerSample, MusicAudioRecorderCore::HEADER::nBytesPerSample, MusicAudioRecorderCore::HEADER::nBytesPerSecond, MusicAudioRecorderCore::HEADER::nChannleNumber, MusicAudioRecorderCore::HEADER::nDataLength, MusicAudioRecorderCore::HEADER::nFMTLength, MusicAudioRecorderCore::HEADER::nRIFFLength, MusicAudioRecorderCore::HEADER::nSampleRate, OPEN_FILE_ERROR, REWRITE_FILE_ERROR, MusicAudioRecorderCore::HEADER::RIFFNAME, SAVE_FILE_ERROR, SEEK_SET, MusicUtils::Core::toLocal8Bit(), MusicAudioRecorderCore::HEADER::WAVNAME, and WRITE_FILE_ERROR.
Referenced by MusicIdentifySongsWidget::detectedTimeOut(), MusicAudioRecorderWidget::onRecordSave(), MusicSoundKMicroWidget::playFinished(), and MusicSoundTouchWidget::transformButtonClicked().
bool MusicAudioRecorderCore::error () const
Current input device error or not.
Definition at line 170 of file musicaudiorecordercore.cpp.
References m_mpAudioInputFile.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), MusicAudioRecorderWidget::onRecordStart(), MusicSoundTouchWidget::onRecordStart(), and MusicSoundKMicroWidget::recordStateChanged().
QString MusicAudioRecorderCore::getClassName () static
Get class object name.
Definition at line 56 of file musicaudiorecordercore.cpp.
QString MusicAudioRecorderCore::getFileName () const
Get output file name.
Definition at line 165 of file musicaudiorecordercore.cpp.
References m_mpOutputFile.
Referenced by MusicSoundTouchWidget::transformButtonClicked().
void MusicAudioRecorderCore::onRecordPlay () slot
Recorder play play.
Definition at line 198 of file musicaudiorecordercore.cpp.
References MusicMessageBox::exec(), m_mFormatFile, m_mpAudioOutputFile, m_mpOutputFile, onStateChange(), and MusicMessageBox::setText().
Referenced by MusicAudioRecorderWidget::onRecordPlay().
void MusicAudioRecorderCore::onRecordStart () slot
Recorder play start.
Definition at line 180 of file musicaudiorecordercore.cpp.
References MusicMessageBox::exec(), m_inputVolume, m_mFormatFile, m_mpAudioInputFile, m_mpOutputFile, and MusicMessageBox::setText().
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), MusicAudioRecorderWidget::onRecordStart(), MusicSoundTouchWidget::onRecordStart(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicAudioRecorderCore::onRecordStop () slot
Recorder play stop.
Definition at line 215 of file musicaudiorecordercore.cpp.
References m_mpAudioInputFile, m_mpAudioOutputFile, and m_mpOutputFile.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), MusicAudioRecorderWidget::onRecordStop(), MusicSoundTouchWidget::onRecordStop(), onStateChange(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicAudioRecorderCore::onStateChange (QAudio::State state) slot
Recorder play state changed.
Definition at line 234 of file musicaudiorecordercore.cpp.
References onRecordStop().
Referenced by onRecordPlay().
void MusicAudioRecorderCore::setFileName (const QString & name)
Set output file name.
Definition at line 160 of file musicaudiorecordercore.cpp.
References m_mpOutputFile.
Referenced by MusicSoundTouchWidget::openWavButtonClicked().
void MusicAudioRecorderCore::setVolume (int volume)
Set volume by value.
Definition at line 144 of file musicaudiorecordercore.cpp.
References m_inputVolume, m_mpAudioInputFile, and volume().
Referenced by MusicSoundKMicroSettingPopWidget::volumeChanged().
int MusicAudioRecorderCore::volume () const
Get volume by value.
Definition at line 155 of file musicaudiorecordercore.cpp.
References m_inputVolume.
Referenced by setVolume().
Member Data Documentation
int MusicAudioRecorderCore::m_inputVolume protected
Definition at line 104 of file musicaudiorecordercore.h.
Referenced by MusicAudioRecorderCore(), onRecordStart(), setVolume(), and volume().
QAudioFormat MusicAudioRecorderCore::m_mFormatFile protected
Definition at line 105 of file musicaudiorecordercore.h.
Referenced by MusicAudioRecorderCore(), onRecordPlay(), and onRecordStart().
QAudioInput* MusicAudioRecorderCore::m_mpAudioInputFile protected
Definition at line 107 of file musicaudiorecordercore.h.
Referenced by error(), MusicAudioRecorderCore(), onRecordStart(), onRecordStop(), setVolume(), and ~MusicAudioRecorderCore().
QAudioOutput* MusicAudioRecorderCore::m_mpAudioOutputFile protected
Definition at line 108 of file musicaudiorecordercore.h.
Referenced by MusicAudioRecorderCore(), onRecordPlay(), onRecordStop(), and ~MusicAudioRecorderCore().
QFile* MusicAudioRecorderCore::m_mpOutputFile protected
Definition at line 106 of file musicaudiorecordercore.h.
Referenced by addWavHeader(), getFileName(), MusicAudioRecorderCore(), onRecordPlay(), onRecordStart(), onRecordStop(), setFileName(), and ~MusicAudioRecorderCore().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicaudiorecordercore.h
TTKModule/TTKCore/musicToolsSetsKits/musicaudiorecordercore.cpp