TTKMusicplayer: MusicQQInterface Namespace Reference
MusicQQInterface Namespace Reference
Functions
void makeRequestRawHeader (QNetworkRequest *request)
Function Documentation
void MusicQQInterface::makeRequestRawHeader (QNetworkRequest * request)
Make request query data.
Definition at line 6 of file musicqqqueryinterface.cpp.
References ALG_UA_KEY, MusicUtils::Algorithm::mdII(), QQ_COOKIE_URL, QQ_UA_URL, and MusicObject::setSslConfiguration().
Referenced by MusicQQQueryArtistRequest::downLoadIntro(), MusicQQDownloadImageRequest::downLoadUrl(), MusicQQQueryMovieRequest::generateMovieKey(), MusicQQQueryInterface::generateMusicPath(), MusicQQQueryPlaylistRequest::moreDetails(), MusicQQQueryPlaylistRequest::queryPlaylistInfo(), MusicQQQueryMovieRequest::readFromMusicMVAttribute(), MusicQQDownloadImageRequest::startToDownload(), MusicQQQueryArtistListRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicQQArtistSimilarRequest::startToSearch(), MusicQQSongSuggestRequest::startToSearch(), MusicQQDiscoverListRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicQQQueryToplistRequest::startToSearch(), MusicQQQueryPlaylistRequest::startToSearch(), MusicQQQueryArtistRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSingleSearch(), and MusicQQQueryRequest::startToSingleSearch().