TTKMusicplayer: MusicVLayoutAnimationWidget Class Reference
MusicVLayoutAnimationWidget Class Reference
The class of the vertical layout float animation widget.
#include <musiclayoutanimationwidget.h>
Public Member Functions
MusicVLayoutAnimationWidget (QWidget *parent=nullptr)
virtual void start () override
Public Member Functions inherited from MusicLayoutAnimationWidget
MusicLayoutAnimationWidget (QWidget *parent=nullptr)
~MusicLayoutAnimationWidget ()
void stop ()
void connectTo (QObject *parent)
void addStretch (int stretch=0)
void addWidget (QWidget *widget, int stretch=0, Qt::Alignment alignment=Qt::Alignment())
void removeWidget (QWidget *widget)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Protected Attributes inherited from MusicLayoutAnimationWidget
bool m_isAnimating
float m_currentValue
QWidget * m_mainWidget
QBoxLayout * m_widgetLayout
QPropertyAnimation * m_animation
Detailed Description
The class of the vertical layout float animation widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 91 of file musiclayoutanimationwidget.h.
Constructor & Destructor Documentation
MusicVLayoutAnimationWidget::MusicVLayoutAnimationWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 95 of file musiclayoutanimationwidget.cpp.
References MusicLayoutAnimationWidget::m_mainWidget, and MusicLayoutAnimationWidget::m_widgetLayout.
Member Function Documentation
void MusicVLayoutAnimationWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 116 of file musiclayoutanimationwidget.cpp.
References MusicLayoutAnimationWidget::m_currentValue, MusicLayoutAnimationWidget::m_isAnimating, and MusicLayoutAnimationWidget::m_mainWidget.
void MusicVLayoutAnimationWidget::start () override virtual
Start to anmiation.
Reimplemented from MusicLayoutAnimationWidget.
Definition at line 104 of file musiclayoutanimationwidget.cpp.
References MusicLayoutAnimationWidget::m_animation, MusicLayoutAnimationWidget::m_isAnimating, MusicLayoutAnimationWidget::m_widgetLayout, and MusicLayoutAnimationWidget::start().
Referenced by MusicLrcContainerForInterior::updateCurrentLrc(), and MusicLrcContainerForWallpaper::updateCurrentLrc().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musiclayoutanimationwidget.h
TTKModule/TTKWidget/musicCoreKits/musiclayoutanimationwidget.cpp