TTKMusicPlayer: MusicConfigObject Class Reference
MusicConfigObject Class Reference
The class of the music initialize object.
#include <musicconfigobject.h>
Public Member Functions
MusicConfigObject (QObject *parent=nullptr)
void valid () const
QString appPath () const
void initialize () const
void reset () const
Private Member Functions
void directoryExist (const QString &name) const
void checkDirectoryExist () const
void checkFileNeededExist () const
void copyFileOverwrite (const QString &origin, const QString &des) const
void copyFile (const QString &origin, const QString &des) const
void copyLinuxShellFile (const QString &name, const QString &path) const
Detailed Description
The class of the music initialize object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicconfigobject.h.
Constructor & Destructor Documentation
MusicConfigObject::MusicConfigObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicconfigobject.cpp.
Member Function Documentation
QString MusicConfigObject::appPath () const
Get app path.
Definition at line 17 of file musicconfigobject.cpp.
References TTK_SERVICE_FULL.
void MusicConfigObject::checkDirectoryExist () const private
Check related dir is exist.
Definition at line 48 of file musicconfigobject.cpp.
References directoryExist(), TTK_ART_DIR_FULL, TTK_BACKGROUND_DIR_FULL, TTK_CACHE_DIR_FULL, TTK_LANGUAGE_DIR_FULL, TTK_LRC_DIR_FULL, TTK_MOVIE_DIR_FULL, TTK_MUSIC_DIR_FULL, TTK_PLUGINS_DIR_FULL, TTK_THEME_DIR_FULL, and TTK_USER_THEME_DIR_FULL.
Referenced by valid().
void MusicConfigObject::checkFileNeededExist () const private
Check related file is exist.
Definition at line 65 of file musicconfigobject.cpp.
References copyFile(), copyLinuxShellFile(), TTK_CLOUD_DOWN_PATH_FULL, TTK_CLOUD_UP_PATH_FULL, TTK_COFIG_PATH_FULL, TTK_CONSOLE_FULL, TTK_INIT_FULL, TTK_MUSICPLAYER_FULL, TTK_NORMAL_DOWN_PATH_FULL, TTK_PLAYLIST_PATH_FULL, TTK_ROUTINE_FULL, TTK_ROUTINECOPY_FULL, TTK_SEARCH_PATH_FULL, and TTK_SERVICE_FULL.
Referenced by initialize(), and valid().
void MusicConfigObject::copyFile (const QString & origin, const QString & des) const private
Copy file.
Definition at line 95 of file musicconfigobject.cpp.
Referenced by checkFileNeededExist().
void MusicConfigObject::copyFileOverwrite (const QString & origin, const QString & des) const private
Copy file by overwrite.
Definition at line 84 of file musicconfigobject.cpp.
Referenced by copyLinuxShellFile(), initialize(), and reset().
void MusicConfigObject::copyLinuxShellFile (const QString & name, const QString & path) const private
Copy linux shell file.
Definition at line 104 of file musicconfigobject.cpp.
References copyFileOverwrite(), and MusicUtils::Url::execute().
Referenced by checkFileNeededExist().
void MusicConfigObject::directoryExist (const QString & name) const private
Check current dir is exist, no, just create it.
Definition at line 39 of file musicconfigobject.cpp.
Referenced by checkDirectoryExist().
void MusicConfigObject::initialize () const
Init parameters.
Definition at line 22 of file musicconfigobject.cpp.
References checkFileNeededExist(), copyFileOverwrite(), TTK_CLOUD_DOWN_PATH_FULL, TTK_CLOUD_UP_PATH_FULL, TTK_COFIG_PATH_FULL, TTK_NORMAL_DOWN_PATH_FULL, TTK_PLAYLIST_PATH_FULL, and TTK_SEARCH_PATH_FULL.
Referenced by main().
void MusicConfigObject::reset () const
Reset config parameters.
Definition at line 34 of file musicconfigobject.cpp.
References copyFileOverwrite(), and TTK_COFIG_PATH_FULL.
Referenced by main().
void MusicConfigObject::valid () const
Check current setting file's validation.
Definition at line 11 of file musicconfigobject.cpp.
References checkDirectoryExist(), and checkFileNeededExist().
Referenced by main(), and TTKRunObject::valid().
The documentation for this class was generated from the following files:
TTKConfig/musicconfigobject.h
TTKConfig/musicconfigobject.cpp