TTKMusicPlayer: MusicApplicationModule Class Reference
MusicApplicationModule Class Reference
The class of the app object widget.
#include <musicapplicationmodule.h>
Public Slots
void quit ()
void windowCloseAnimationFinished ()
void showAboutWidget ()
void showBugReportView ()
void showVersionWidget ()
void showTimerWidget ()
void showSpectrumWidget ()
void setWindowToTop ()
void resetWindowGeometry ()
void runTimerAutoModule ()
void deviceNameChanged (const QString &name)
void deviceChanged (bool state)
void showEqualizerWidget ()
void showSoundEffectWidget ()
void soundEffectChanged ()
Signals
void enhancedMusicChanged (int type)
Public Member Functions
MusicApplicationModule (QObject *parent=nullptr)
~MusicApplicationModule ()
bool windowToTop () const
void cleanup ()
bool isLastedVersion () const
void loadNetWorkSetting ()
void windowCloseAnimation ()
void soureUpdateCheck ()
void sideAnimationByOn ()
void sideAnimationByOff ()
void applyParameter ()
Static Public Member Functions
static MusicApplicationModule * instance ()
Private Member Functions
bool closeCurrentEqualizer ()
Private Attributes
bool m_setWindowToTop
TTK::Direction m_direction
QPropertyAnimation * m_quitAnimation
QPropertyAnimation * m_sideAnimation
MusicBackupModule * m_backupModule
MusicTimerAutoModule * m_timerAutoModule
MusicMobileDevicesWidget * m_mobileDeviceWidget
QDeviceWatcher * m_deviceWatcher
QWidget * m_quitContainer
MusicResourceRequest * m_resourceRequest
MusicPVCounterRequest * m_counterRequest
MusicSourceUpdateRequest * m_sourceUpdateRequest
MusicScreenSaverBackgroundWidget * m_screenSaverWidget
Static Private Attributes
static MusicApplicationModule * m_instance = nullptr
Detailed Description
The class of the app object widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 42 of file musicapplicationmodule.h.
Constructor & Destructor Documentation
MusicApplicationModule::MusicApplicationModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 39 of file musicapplicationmodule.cpp.
References QDeviceWatcher::appendEventReceiver(), deviceChanged(), deviceNameChanged(), m_backupModule, m_counterRequest, m_deviceWatcher, m_instance, m_quitAnimation, m_resourceRequest, m_sideAnimation, m_sourceUpdateRequest, m_timerAutoModule, MusicToastLabel::popup(), resetWindowGeometry(), runTimerAutoModule(), and QDeviceWatcher::start().
MusicApplicationModule::~MusicApplicationModule ()
Object destructor.
Definition at line 81 of file musicapplicationmodule.cpp.
References m_backupModule, m_counterRequest, m_deviceWatcher, m_mobileDeviceWidget, m_quitAnimation, m_quitContainer, m_resourceRequest, m_screenSaverWidget, m_sideAnimation, m_sourceUpdateRequest, and m_timerAutoModule.
Member Function Documentation
void MusicApplicationModule::applyParameter ()
Apply settings parameters.
Definition at line 277 of file musicapplicationmodule.cpp.
References MusicSettingManager::FileAssociationMode, G_SETTING_PTR, m_backupModule, m_screenSaverWidget, MusicBackupModule::run(), MusicScreenSaverBackgroundWidget::run(), MusicSettingManager::StartUpMode, TTK::supportAssociations(), TTKConcurrent, and TTK::unsupportAssociations().
Referenced by MusicApplication::applyParameter(), MusicScreenSaverWidget::currentItemClicked(), MusicScreenSaverWidget::inputDataChanged(), and MusicScreenSaverWidget::switchButtonState().
void MusicApplicationModule::cleanup ()
Clean up the system parameter.
Definition at line 103 of file musicapplicationmodule.cpp.
References G_SETTING_PTR, MusicApplication::instance(), m_direction, TTK::No, MusicSettingManager::OtherSideByMode, and TTKDesktopWrapper::screenGeometry().
Referenced by MusicApplication::quitWindow().
bool MusicApplicationModule::closeCurrentEqualizer () private
Close current equalizer.
Definition at line 468 of file musicapplicationmodule.cpp.
References enhancedMusicChanged(), MusicSettingManager::EnhancedMusicIndex, MusicAbstractMoveDialog::exec(), G_SETTING_PTR, and MusicMessageBox::setText().
Referenced by showEqualizerWidget(), and showSoundEffectWidget().
void MusicApplicationModule::deviceChanged (bool state) slot
Detect mobile devices changed.
Definition at line 419 of file musicapplicationmodule.cpp.
References MusicSettingManager::ExtraDevicePath, G_SETTING_PTR, and m_mobileDeviceWidget.
Referenced by MusicApplicationModule().
void MusicApplicationModule::deviceNameChanged (const QString & name) slot
Detect mobile devices name changed.
Definition at line 414 of file musicapplicationmodule.cpp.
References MusicSettingManager::ExtraDevicePath, and G_SETTING_PTR.
Referenced by MusicApplicationModule().
void MusicApplicationModule::enhancedMusicChanged (int type) signal
Set enhanced music config changed.
Referenced by closeCurrentEqualizer().
MusicApplicationModule * MusicApplicationModule::instance () static
Get class object instance.
Definition at line 98 of file musicapplicationmodule.cpp.
References m_instance.
Referenced by MusicScreenSaverWidget::currentItemClicked(), MusicSettingWidget::initSoundEffectWidget(), MusicScreenSaverWidget::inputDataChanged(), MusicBackgroundSkinDialog::MusicBackgroundSkinDialog(), MusicEnhancedPopWidget::MusicEnhancedPopWidget(), MusicTimerWidget::saveParameterSettings(), and MusicScreenSaverWidget::switchButtonState().
bool MusicApplicationModule::isLastedVersion () const
Is lasted version.
Definition at line 114 of file musicapplicationmodule.cpp.
References MusicSourceUpdateRequest::isLastedVersion(), and m_sourceUpdateRequest.
Referenced by MusicApplication::createRightMenu().
void MusicApplicationModule::loadNetWorkSetting ()
load network settings parameters.
Definition at line 119 of file musicapplicationmodule.cpp.
References QSyncConfig::HOST, m_counterRequest, m_resourceRequest, m_sourceUpdateRequest, TTK::Algorithm::mdII(), MusicPVCounterRequest::startToRequest(), MusicResourceRequest::startToRequest(), MusicSourceUpdateRequest::startToRequest(), SYNC_HOST_URL, and TTK_INFO_STREAM.
Referenced by MusicApplication::readSystemConfigFromFile().
void MusicApplicationModule::quit () slot
Application quit.
Definition at line 323 of file musicapplicationmodule.cpp.
Referenced by windowCloseAnimation().
void MusicApplicationModule::resetWindowGeometry () slot
Reset current window geometry.
Definition at line 393 of file musicapplicationmodule.cpp.
References G_SETTING_PTR, MusicApplication::instance(), m_direction, TTK::No, TTKDesktopWrapper::screenGeometry(), MusicSettingManager::ScreenSize, MusicSettingManager::WidgetSize, WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by MusicApplicationModule().
void MusicApplicationModule::runTimerAutoModule () slot
Run timer auto module.
Definition at line 409 of file musicapplicationmodule.cpp.
References m_timerAutoModule, and MusicTimerAutoModule::run().
Referenced by MusicApplicationModule(), and MusicTimerWidget::saveParameterSettings().
void MusicApplicationModule::setWindowToTop () slot
Set current window to top.
Definition at line 385 of file musicapplicationmodule.cpp.
References MusicApplication::instance(), and m_setWindowToTop.
void MusicApplicationModule::showAboutWidget () slot
Show about widget.
Definition at line 355 of file musicapplicationmodule.cpp.
References MusicAbstractMoveDialog::exec().
void MusicApplicationModule::showBugReportView () slot
Show bug report view.
Definition at line 360 of file musicapplicationmodule.cpp.
References TTK::Algorithm::mdII(), TTK::Url::openUrl(), and REPORT_BUG_URL.
void MusicApplicationModule::showEqualizerWidget () slot
Show set equalizer widget.
Definition at line 435 of file musicapplicationmodule.cpp.
References closeCurrentEqualizer(), and MusicAbstractMoveDialog::exec().
void MusicApplicationModule::showSoundEffectWidget () slot
Show set sound effect widget.
Definition at line 446 of file musicapplicationmodule.cpp.
References closeCurrentEqualizer(), MusicAbstractMoveDialog::exec(), and MusicSoundEffectsWidget::setInputModule().
void MusicApplicationModule::showSpectrumWidget () slot
Show spectrum widget.
Definition at line 380 of file musicapplicationmodule.cpp.
References TTKGenerateSingleWidget.
void MusicApplicationModule::showTimerWidget () slot
Show timer widget.
Definition at line 370 of file musicapplicationmodule.cpp.
References MusicApplication::currentPlaylist(), MusicAbstractMoveDialog::exec(), MusicApplication::instance(), and MusicTimerWidget::setSongStringList().
void MusicApplicationModule::showVersionWidget () slot
Show version update widget.
Definition at line 365 of file musicapplicationmodule.cpp.
References MusicSourceUpdateWidget::exec(), and MusicApplication::instance().
void MusicApplicationModule::sideAnimationByOff ()
Side animation by off.
Definition at line 235 of file musicapplicationmodule.cpp.
References TTK::Bottom, G_SETTING_PTR, MusicApplication::instance(), TTK::Left, TTK::LeftBottom, TTK::LeftTop, m_direction, m_sideAnimation, TTK::No, MusicSettingManager::OtherSideByInMode, MusicSettingManager::OtherSideByMode, TTK::Right, TTK::RightBottom, TTK::RightTop, TTKDesktopWrapper::screenGeometry(), and TTK::Top.
Referenced by MusicApplication::enterEvent(), and windowCloseAnimation().
void MusicApplicationModule::sideAnimationByOn ()
Side animation by on.
Definition at line 172 of file musicapplicationmodule.cpp.
References TTK::Bottom, G_SETTING_PTR, MusicApplication::instance(), TTK::Left, TTKPlatformSystem::LinuxUbuntu, TTKDesktopWrapper::TaskbarInfo::m_direction, m_direction, m_sideAnimation, MARGIN_SIDE, MusicSettingManager::OtherSideByInMode, MusicSettingManager::OtherSideByMode, TTK::Right, TTKDesktopWrapper::screenGeometry(), TTKDesktopWrapper::screenTaskbar(), TTKPlatformSystem::systemName(), and TTK::Top.
Referenced by MusicApplication::leaveEvent(), and MusicApplication::mouseReleaseEvent().
void MusicApplicationModule::soundEffectChanged () slot
Sound effect changed.
Definition at line 458 of file musicapplicationmodule.cpp.
References TTK::TTKQmmp::enabledEffectPlugin(), MusicSettingManager::EnhancedEffectValue, G_SETTING_PTR, qAsConst, and QtSkipEmptyParts.
Referenced by MusicApplication::readSystemConfigFromFile().
void MusicApplicationModule::soureUpdateCheck ()
Soure update check.
Definition at line 166 of file musicapplicationmodule.cpp.
References MusicAbstractMoveWidget::show().
Referenced by MusicApplication::readSystemConfigFromFile().
void MusicApplicationModule::windowCloseAnimation ()
Window close animation.
remove fixed size
Definition at line 133 of file musicapplicationmodule.cpp.
References MusicSettingManager::BackgroundTransparent, G_SETTING_PTR, MusicTopAreaWidget::instance(), MusicApplication::instance(), m_quitAnimation, quit(), MusicTopAreaWidget::setBackgroundAnimation(), sideAnimationByOff(), TTK_DN_S2MS, TTK_RN_MAX, TTK_SIGNLE_SHOT, TTK_SLOT, windowCloseAnimationFinished(), and MusicSettingManager::WindowQuitMode.
Referenced by MusicApplication::quitWindow().
void MusicApplicationModule::windowCloseAnimationFinished () slot
Window close animation finished.
Definition at line 328 of file musicapplicationmodule.cpp.
References MusicGifLabelWidget::CloseWhite, MusicApplication::instance(), m_quitContainer, MusicGifLabelWidget::setInfinited(), MusicGifLabelWidget::setInterval(), MusicGifLabelWidget::setType(), and MusicGifLabelWidget::start().
Referenced by windowCloseAnimation().
bool MusicApplicationModule::windowToTop () const inline
Get current window is to top.
Definition at line 64 of file musicapplicationmodule.h.
Referenced by MusicApplication::createRightMenu().
Member Data Documentation
MusicBackupModule* MusicApplicationModule::m_backupModule private
Definition at line 178 of file musicapplicationmodule.h.
Referenced by applyParameter(), MusicApplicationModule(), and ~MusicApplicationModule().
MusicPVCounterRequest* MusicApplicationModule::m_counterRequest private
Definition at line 185 of file musicapplicationmodule.h.
Referenced by loadNetWorkSetting(), MusicApplicationModule(), and ~MusicApplicationModule().
QDeviceWatcher* MusicApplicationModule::m_deviceWatcher private
Definition at line 181 of file musicapplicationmodule.h.
Referenced by MusicApplicationModule(), and ~MusicApplicationModule().
TTK::Direction MusicApplicationModule::m_direction private
Definition at line 176 of file musicapplicationmodule.h.
Referenced by cleanup(), resetWindowGeometry(), sideAnimationByOff(), and sideAnimationByOn().
MusicApplicationModule * MusicApplicationModule::m_instance = nullptr static private
Definition at line 189 of file musicapplicationmodule.h.
Referenced by instance(), and MusicApplicationModule().
MusicMobileDevicesWidget* MusicApplicationModule::m_mobileDeviceWidget private
Definition at line 180 of file musicapplicationmodule.h.
Referenced by deviceChanged(), and ~MusicApplicationModule().
QPropertyAnimation* MusicApplicationModule::m_quitAnimation private
Definition at line 177 of file musicapplicationmodule.h.
Referenced by MusicApplicationModule(), windowCloseAnimation(), and ~MusicApplicationModule().
QWidget* MusicApplicationModule::m_quitContainer private
Definition at line 182 of file musicapplicationmodule.h.
Referenced by windowCloseAnimationFinished(), and ~MusicApplicationModule().
MusicResourceRequest* MusicApplicationModule::m_resourceRequest private
Definition at line 184 of file musicapplicationmodule.h.
Referenced by loadNetWorkSetting(), MusicApplicationModule(), and ~MusicApplicationModule().
MusicScreenSaverBackgroundWidget* MusicApplicationModule::m_screenSaverWidget private
Definition at line 187 of file musicapplicationmodule.h.
Referenced by applyParameter(), and ~MusicApplicationModule().
bool MusicApplicationModule::m_setWindowToTop private
Definition at line 175 of file musicapplicationmodule.h.
Referenced by setWindowToTop().
QPropertyAnimation * MusicApplicationModule::m_sideAnimation private
Definition at line 177 of file musicapplicationmodule.h.
Referenced by MusicApplicationModule(), sideAnimationByOff(), sideAnimationByOn(), and ~MusicApplicationModule().
MusicSourceUpdateRequest* MusicApplicationModule::m_sourceUpdateRequest private
Definition at line 186 of file musicapplicationmodule.h.
Referenced by isLastedVersion(), loadNetWorkSetting(), MusicApplicationModule(), and ~MusicApplicationModule().
MusicTimerAutoModule* MusicApplicationModule::m_timerAutoModule private
Definition at line 179 of file musicapplicationmodule.h.
Referenced by MusicApplicationModule(), runTimerAutoModule(), and ~MusicApplicationModule().
The documentation for this class was generated from the following files:
TTKModule/musicapplicationmodule.h
TTKModule/musicapplicationmodule.cpp