TTKMusicPlayer: MusicLrcContainerForDesktop Class Reference
MusicLrcContainerForDesktop Class Reference abstract
The class of the desktop lrc container.
#include <musiclrccontainerfordesktop.h>
Public Slots
void setWindowLockedChanged ()
void setLrcBiggerChanged ()
void setLrcSmallerChanged ()
void toolStyleChanged ()
virtual void setSingleLineTypeChanged ()
Public Slots inherited from MusicLrcContainer
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
Signals
void setWindowLockedChanged (bool lock)
Signals inherited from MusicLrcContainer
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Public Member Functions
MusicLrcContainerForDesktop (QWidget *parent=nullptr)
~MusicLrcContainerForDesktop ()
virtual void startDrawLrc () overridefinal
virtual void stopDrawLrc () overridefinal
virtual void applyParameter () overridefinal
virtual void initCurrentLrc () const
void setCurrentPlayStatus (bool status) const
void updateCurrentLrc (const QString &first, const QString &second, qint64 time)
bool isVerticalWindowType () const
void makeStatusCopy (MusicLrcContainerForDesktop *other)
Public Member Functions inherited from MusicLrcContainer
MusicLrcContainer (QWidget *parent=nullptr)
~MusicLrcContainer ()
void setLinearGradientColor (MusicLrcColor::Color color)
void setLinearGradientColor (const MusicLrcColor &color)
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 totalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * lrcAnalysisModel () const
Protected Member Functions
void createColorMenu (QMenu &menu)
void setSelfPosition () const
void creatToolBarWidget ()
virtual void resizeLrcSizeArea ()=0
void resizeLrcSizeArea (bool resize)
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
virtual void closeEvent (QCloseEvent *event) overridefinal
Protected Member Functions inherited from MusicLrcContainer
void clearAllMusicLRCManager ()
Protected Attributes
bool m_verticalWindow
bool m_singleLineType
bool m_windowLocked
bool m_reverse
int m_currentLrcFontSize
int m_widgetWidth
QPoint m_offset
QPoint m_geometry
QBoxLayout * m_toolBarLayout
QWidget * m_toolBarWidget
QToolButton * m_toolPlayButton
Protected Attributes inherited from MusicLrcContainer
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_lrcManagers
MusicLrcSearchWidget * m_lrcSearchWidget
Detailed Description
The class of the desktop lrc container.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 36 of file musiclrccontainerfordesktop.h.
Constructor & Destructor Documentation
MusicLrcContainerForDesktop::MusicLrcContainerForDesktop (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musiclrccontainerfordesktop.cpp.
References LRC_DESKTOP_TPYE, and MusicLrcContainer::m_containerType.
MusicLrcContainerForDesktop::~MusicLrcContainerForDesktop ()
Definition at line 27 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::clearAllMusicLRCManager(), m_toolBarLayout, m_toolBarWidget, and m_toolPlayButton.
Member Function Documentation
void MusicLrcContainerForDesktop::applyParameter () final override virtual
Set setting parameter.
Reimplemented from MusicLrcContainer.
Definition at line 48 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::applyParameter(), MusicSettingManager::DLrcGeometry, MusicSettingManager::DLrcLockedMode, MusicSettingManager::DLrcSingleLineMode, MusicSettingManager::DLrcSize, G_SETTING_PTR, m_currentLrcFontSize, MusicLrcContainer::m_lrcManagers, m_singleLineType, m_windowLocked, and setSingleLineTypeChanged().
Referenced by MusicRightAreaWidget::applyParameter(), and MusicRightAreaWidget::setWindowLrcTypeChanged().
void MusicLrcContainerForDesktop::closeEvent (QCloseEvent * event) final override protected virtual
Definition at line 387 of file musiclrccontainerfordesktop.cpp.
References MusicBottomAreaWidget::desktopLrcClosed(), and MusicBottomAreaWidget::instance().
void MusicLrcContainerForDesktop::contextMenuEvent (QContextMenuEvent * event) final override protected virtual
Definition at line 393 of file musiclrccontainerfordesktop.cpp.
References createColorMenu(), MusicLrcContainer::currentLrcCustom(), MusicLrcContainer::currentLrcUpdated(), MusicLrcContainer::linkLrcStateChanged(), MusicLrcContainer::m_linkLocalLrc, m_singleLineType, m_windowLocked, MusicUIObject::MQSSMenuStyle02, MusicLrcContainer::searchMusicLrcs(), setSingleLineTypeChanged(), setWindowLockedChanged(), and MusicLrcContainer::showLrcMakedWidget().
void MusicLrcContainerForDesktop::createColorMenu (QMenu & menu) protected
Create color menu.
Definition at line 165 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::changeCurrentLrcColor(), MusicLrcContainer::currentLrcCustom(), G_SETTING_PTR, and LRC_COLOR_OFFSET.
Referenced by contextMenuEvent(), and toolStyleChanged().
void MusicLrcContainerForDesktop::creatToolBarWidget () protected
Creat toolBar widget.
Definition at line 194 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::currentLrcCustom(), MusicLrcContainer::currentLrcUpdated(), MusicApplication::instance(), m_toolBarLayout, m_toolBarWidget, m_toolPlayButton, m_verticalWindow, MusicUIObject::MQSSBackgroundStyle05, MusicUIObject::MQSSBtnTClose, MusicUIObject::MQSSDeskTopHMakeLrc, MusicUIObject::MQSSDeskTopHorizontal, MusicUIObject::MQSSDeskTopHSearchLrc, MusicUIObject::MQSSDeskTopHUpdateLrc, MusicUIObject::MQSSDeskTopLock, MusicUIObject::MQSSDeskTopNext, MusicUIObject::MQSSDeskTopPlay, MusicUIObject::MQSSDeskTopPrevious, MusicUIObject::MQSSDeskTopSetting, MusicUIObject::MQSSDeskTopSizeDown, MusicUIObject::MQSSDeskTopSizeUp, MusicUIObject::MQSSDeskTopStyle, MusicUIObject::MQSSDeskTopVertical, MusicUIObject::MQSSDeskTopVMakeLrc, MusicUIObject::MQSSDeskTopVSearchLrc, MusicUIObject::MQSSDeskTopVUpdateLrc, MusicUIObject::MQSSPushButtonStyle02, MusicLrcContainer::searchMusicLrcs(), setLrcBiggerChanged(), setLrcSmallerChanged(), setWindowLockedChanged(), MusicLrcContainer::showLrcMakedWidget(), TOOLBAR_HEIGHT, TOOLBAR_TEXT_LENGTH, TOOLBAR_WIDTH, and toolStyleChanged().
Referenced by MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), and MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop().
void MusicLrcContainerForDesktop::enterEvent (QtEnterEvent * event) final override protected virtual
Definition at line 363 of file musiclrccontainerfordesktop.cpp.
References m_toolBarWidget, m_windowLocked, and MusicUIObject::MQSSBackgroundStyle05.
void MusicLrcContainerForDesktop::initCurrentLrc () const virtual
Init current lrc when the first show.
Reimplemented in MusicLrcContainerVerticalDesktop, and MusicLrcContainerHorizontalDesktop.
Definition at line 68 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::m_currentTime, and MusicLrcContainer::m_lrcManagers.
Referenced by MusicLrcContainerHorizontalDesktop::initCurrentLrc(), MusicLrcContainerVerticalDesktop::initCurrentLrc(), MusicRightAreaWidget::setDestopLrcVisible(), and MusicRightAreaWidget::setWindowLrcTypeChanged().
bool MusicLrcContainerForDesktop::isVerticalWindowType () const inline
Get current desktop lrc window type is vertical or not.
Definition at line 76 of file musiclrccontainerfordesktop.h.
Referenced by MusicRightAreaWidget::setWindowLrcTypeChanged().
void MusicLrcContainerForDesktop::leaveEvent (QEvent * event) final override protected virtual
Definition at line 375 of file musiclrccontainerfordesktop.cpp.
References m_toolBarWidget, m_windowLocked, and MusicUIObject::MQSSBackgroundStyle01.
void MusicLrcContainerForDesktop::makeStatusCopy (MusicLrcContainerForDesktop * other)
Make object status copy.
Definition at line 100 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::m_currentSongName, and m_toolPlayButton.
Referenced by MusicRightAreaWidget::setWindowLrcTypeChanged().
void MusicLrcContainerForDesktop::mouseMoveEvent (QMouseEvent * event) final override protected virtual
Definition at line 352 of file musiclrccontainerfordesktop.cpp.
References MusicSettingManager::DLrcGeometry, G_SETTING_PTR, m_offset, m_windowLocked, and QtMouseEventGlobalPos.
void MusicLrcContainerForDesktop::mousePressEvent (QMouseEvent * event) final override protected virtual
Override the widget event.
Definition at line 343 of file musiclrccontainerfordesktop.cpp.
References m_offset, m_windowLocked, and QtMouseEventGlobalPos.
virtual void MusicLrcContainerForDesktop::resizeLrcSizeArea () protected pure virtual
Resize lrc size area by change size. Subclass should implement this function.
Implemented in MusicLrcContainerVerticalDesktop, and MusicLrcContainerHorizontalDesktop.
Referenced by resizeLrcSizeArea(), setLrcBiggerChanged(), setLrcSmallerChanged(), and updateCurrentLrc().
void MusicLrcContainerForDesktop::resizeLrcSizeArea (bool resize) protected
Resize lrc size area to bigger or smaller.
Definition at line 323 of file musiclrccontainerfordesktop.cpp.
References MusicSettingManager::DLrcSize, G_SETTING_PTR, m_currentLrcFontSize, m_geometry, MusicLrcContainer::m_lrcManagers, m_singleLineType, resizeLrcSizeArea(), and setSelfPosition().
void MusicLrcContainerForDesktop::setCurrentPlayStatus (bool status) const
Set current play state button.
Definition at line 76 of file musiclrccontainerfordesktop.cpp.
References m_toolPlayButton, MusicUIObject::MQSSDeskTopPause, and MusicUIObject::MQSSDeskTopPlay.
Referenced by MusicRightAreaWidget::setCurrentPlayStatus().
void MusicLrcContainerForDesktop::setLrcBiggerChanged () slot
Set lrc bigger changed.
Definition at line 118 of file musiclrccontainerfordesktop.cpp.
References m_currentLrcFontSize, and resizeLrcSizeArea().
Referenced by creatToolBarWidget().
void MusicLrcContainerForDesktop::setLrcSmallerChanged () slot
Set lrc smaller changed.
Definition at line 127 of file musiclrccontainerfordesktop.cpp.
References m_currentLrcFontSize, and resizeLrcSizeArea().
Referenced by creatToolBarWidget().
void MusicLrcContainerForDesktop::setSelfPosition () const protected
Set self position.
Definition at line 186 of file musiclrccontainerfordesktop.cpp.
References m_geometry, and MusicLrcContainer::m_lrcManagers.
Referenced by MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), and resizeLrcSizeArea().
void MusicLrcContainerForDesktop::setSingleLineTypeChanged () virtual slot
Set single line type changed.
Definition at line 144 of file musiclrccontainerfordesktop.cpp.
References MusicSettingManager::DLrcSingleLineMode, G_SETTING_PTR, MusicLrcContainer::m_lrcManagers, m_reverse, m_singleLineType, and startDrawLrc().
Referenced by applyParameter(), contextMenuEvent(), MusicLrcContainerHorizontalDesktop::setSingleLineTypeChanged(), and MusicLrcContainerVerticalDesktop::setSingleLineTypeChanged().
void MusicLrcContainerForDesktop::setWindowLockedChanged (bool lock) signal
Lock current desktop lrc state changed.
Referenced by MusicRightAreaWidget::setWindowLockedChanged().
void MusicLrcContainerForDesktop::setWindowLockedChanged () slot
Lock current desktop lrc state changed.
Definition at line 106 of file musiclrccontainerfordesktop.cpp.
References MusicSettingManager::DLrcLockedMode, G_SETTING_PTR, MusicBottomAreaWidget::instance(), MusicBottomAreaWidget::lockDesktopLrc(), m_toolBarWidget, m_windowLocked, and MusicUIObject::MQSSBackgroundStyle01.
Referenced by contextMenuEvent(), and creatToolBarWidget().
void MusicLrcContainerForDesktop::startDrawLrc () final override virtual
Start timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 35 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::m_lrcManagers, m_reverse, and m_singleLineType.
Referenced by setSingleLineTypeChanged(), and MusicRightAreaWidget::startDrawLrc().
void MusicLrcContainerForDesktop::stopDrawLrc () final override virtual
Stop timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 40 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::m_lrcManagers.
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), and MusicRightAreaWidget::stopDrawLrc().
void MusicLrcContainerForDesktop::toolStyleChanged () slot
Set current color style changed.
Definition at line 136 of file musiclrccontainerfordesktop.cpp.
References createColorMenu(), and MusicUIObject::MQSSMenuStyle02.
Referenced by creatToolBarWidget().
void MusicLrcContainerForDesktop::updateCurrentLrc (const QString & first, const QString & second, qint64 time)
Update current lrc by first and second and time.
Definition at line 81 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::m_lrcManagers, m_reverse, m_singleLineType, and resizeLrcSizeArea().
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), and MusicRightAreaWidget::updateCurrentLrc().
Member Data Documentation
int MusicLrcContainerForDesktop::m_currentLrcFontSize protected
Definition at line 144 of file musiclrccontainerfordesktop.h.
Referenced by applyParameter(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), resizeLrcSizeArea(), setLrcBiggerChanged(), and setLrcSmallerChanged().
QPoint MusicLrcContainerForDesktop::m_geometry protected
Definition at line 145 of file musiclrccontainerfordesktop.h.
Referenced by MusicLrcContainerHorizontalDesktop::initCurrentLrc(), MusicLrcContainerVerticalDesktop::initCurrentLrc(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), resizeLrcSizeArea(), MusicLrcContainerHorizontalDesktop::resizeLrcSizeArea(), MusicLrcContainerVerticalDesktop::resizeLrcSizeArea(), and setSelfPosition().
QPoint MusicLrcContainerForDesktop::m_offset protected
Definition at line 145 of file musiclrccontainerfordesktop.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
bool MusicLrcContainerForDesktop::m_reverse protected
Definition at line 143 of file musiclrccontainerfordesktop.h.
Referenced by setSingleLineTypeChanged(), startDrawLrc(), and updateCurrentLrc().
bool MusicLrcContainerForDesktop::m_singleLineType protected
Definition at line 142 of file musiclrccontainerfordesktop.h.
Referenced by applyParameter(), contextMenuEvent(), MusicLrcContainerHorizontalDesktop::initCurrentLrc(), MusicLrcContainerVerticalDesktop::initCurrentLrc(), resizeLrcSizeArea(), MusicLrcContainerHorizontalDesktop::resizeLrcSizeArea(), MusicLrcContainerVerticalDesktop::resizeLrcSizeArea(), setSingleLineTypeChanged(), MusicLrcContainerHorizontalDesktop::setSingleLineTypeChanged(), MusicLrcContainerVerticalDesktop::setSingleLineTypeChanged(), startDrawLrc(), and updateCurrentLrc().
QBoxLayout* MusicLrcContainerForDesktop::m_toolBarLayout protected
Definition at line 147 of file musiclrccontainerfordesktop.h.
Referenced by creatToolBarWidget(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), and ~MusicLrcContainerForDesktop().
QWidget* MusicLrcContainerForDesktop::m_toolBarWidget protected
Definition at line 148 of file musiclrccontainerfordesktop.h.
Referenced by creatToolBarWidget(), enterEvent(), leaveEvent(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), setWindowLockedChanged(), and ~MusicLrcContainerForDesktop().
QToolButton* MusicLrcContainerForDesktop::m_toolPlayButton protected
Definition at line 149 of file musiclrccontainerfordesktop.h.
Referenced by creatToolBarWidget(), makeStatusCopy(), setCurrentPlayStatus(), and ~MusicLrcContainerForDesktop().
bool MusicLrcContainerForDesktop::m_verticalWindow protected
Definition at line 142 of file musiclrccontainerfordesktop.h.
Referenced by creatToolBarWidget(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), and MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop().
int MusicLrcContainerForDesktop::m_widgetWidth protected
Definition at line 144 of file musiclrccontainerfordesktop.h.
Referenced by MusicLrcContainerHorizontalDesktop::initCurrentLrc(), MusicLrcContainerVerticalDesktop::initCurrentLrc(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), MusicLrcContainerHorizontalDesktop::resizeLrcSizeArea(), MusicLrcContainerVerticalDesktop::resizeLrcSizeArea(), MusicLrcContainerHorizontalDesktop::setSingleLineTypeChanged(), and MusicLrcContainerVerticalDesktop::setSingleLineTypeChanged().
bool MusicLrcContainerForDesktop::m_windowLocked protected
Definition at line 143 of file musiclrccontainerfordesktop.h.
Referenced by applyParameter(), contextMenuEvent(), enterEvent(), leaveEvent(), mouseMoveEvent(), mousePressEvent(), and setWindowLockedChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerfordesktop.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerfordesktop.cpp