TTKMusicplayer: QImageWrapper::SharpeImage Class Reference
QImageWrapper::SharpeImage Class Reference abstract
The class of the sharpe image.
#include <qimagewrapper.h>
Public Member Functions
SharpeImage ()
virtual ~SharpeImage ()
virtual void input (const QRect &region)
virtual QPixmap render (const QPixmap &pixmap, int value)=0
Protected Member Functions
SharpeImage (SharpeImagePrivate &pvt)
Detailed Description
The class of the sharpe image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file qimagewrapper.h.
Constructor & Destructor Documentation
QImageWrapper::SharpeImage::SharpeImage ()
Definition at line 31 of file qimagewrapper.cpp.
QImageWrapper::SharpeImage::~SharpeImage () virtual
Definition at line 42 of file qimagewrapper.cpp.
QImageWrapper::SharpeImage::SharpeImage (SharpeImagePrivate & pvt) protected
Definition at line 37 of file qimagewrapper.cpp.
References TTK_INIT_PRIVATE_D.
Member Function Documentation
void QImageWrapper::SharpeImage::input (const QRect & region) virtual
Init item data.
Reimplemented in QImageWrapper::WaterWave, and QImageWrapper::CubeWave.
Definition at line 47 of file qimagewrapper.cpp.
References TTK_D.
Referenced by MusicLrcPosterItemWidget::drawTheme10(), QImageWrapper::CubeWave::input(), QImageWrapper::WaterWave::input(), and MusicTransitionAnimationLabel::setPixmap().
virtual QPixmap QImageWrapper::SharpeImage::render (const QPixmap & pixmap, int value) pure virtual
Render data.
Implemented in QImageWrapper::WaterWave, QImageWrapper::CubeWave, and QImageWrapper::GaussBlur.
Referenced by MusicTransitionAnimationLabel::paintEvent().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/qimagewrapper.h
TTKThirdParty/TTKExtras/qalgorithm/qimagewrapper.cpp