TTKMusicPlayer: MusicLocalManagerWidget Class Reference
MusicLocalManagerWidget Class Reference
The class of the local manager widget.
#include <musiclocalmanagerwidget.h>
Signals
void addSongToPlaylist (const QStringList &items)
Public Member Functions
MusicLocalManagerWidget (QWidget *parent=nullptr)
~MusicLocalManagerWidget ()
virtual void resizeWidget () overridefinal
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Slots
void typeIndexChanged (int index)
void refreshItems ()
void updateMediaLibraryPath ()
void searchResultChanged (int row, int column)
void itemDoubleClicked (int row, int column)
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
void updateStatisticWidget (int index, const MusicSongInfoItemList &items)
Private Member Functions inherited from MusicItemSearchInterface< MusicSongInfoItemList >
MusicItemSearchInterface ()
bool hasSearchResult () const
void clearSearchResult ()
void mappedSearchRow (int pos, int &row) const
Private Attributes
QLabel * m_sizeLabel
TTKTabButton * m_tabButton
MusicItemQueryEdit * m_searchEdit
MusicGifLabelValueWidget * m_loadingLabel
MusicLocalManagerSongsTableWidget * m_songTableWidget
MusicLocalManagerStatisticTableWidget * m_statisticTableWidget
Private Attributes inherited from MusicItemSearchInterface< MusicSongInfoItemList >
MusicSongInfoItemList m_containerItems
int m_searchResultLevel
TTKSearchItems m_searchResultItems
Additional Inherited Members
Private Types inherited from MusicItemSearchInterface< MusicSongInfoItemList >
using TTKSearchItems = QMap< int, TTKIntList >
using MusicItemSearchInterfaceClass = MusicItemSearchInterface< MusicSongInfoItemList >
Detailed Description
The class of the local manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 117 of file musiclocalmanagerwidget.h.
Constructor & Destructor Documentation
MusicLocalManagerWidget::MusicLocalManagerWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 233 of file musiclocalmanagerwidget.cpp.
References TTKTabButton::addButtons(), TTK::UI::BackgroundStyle01, TTK::UI::BackgroundStyle10, TTK::UI::ColorStyle01, TTK::UI::ColorStyle02, MusicItemQueryEdit::editor(), G_CONNECTION_PTR, itemDoubleClicked(), m_loadingLabel, m_searchEdit, m_sizeLabel, m_songTableWidget, m_statisticTableWidget, m_tabButton, TTK::UI::PushButtonStyle03, refreshItems(), searchResultChanged(), TTK_SIGNLE_SHOT, TTK_SLOT, typeIndexChanged(), and updateMediaLibraryPath().
MusicLocalManagerWidget::~MusicLocalManagerWidget ()
Object destructor.
Definition at line 339 of file musiclocalmanagerwidget.cpp.
References G_CONNECTION_PTR, m_loadingLabel, m_searchEdit, m_sizeLabel, m_songTableWidget, and m_statisticTableWidget.
Member Function Documentation
void MusicLocalManagerWidget::addSongToPlaylist (const QStringList & items) signal
Add current selected song to playlist.
Referenced by itemDoubleClicked().
void MusicLocalManagerWidget::itemDoubleClicked (int row, int column) private slot
Item cell on double click by row and col.
Definition at line 483 of file musiclocalmanagerwidget.cpp.
References addSongToPlaylist(), MusicItemQueryEdit::editor(), MusicItemSearchInterface< MusicSongInfoItemList >::m_containerItems, m_searchEdit, and MusicItemSearchInterface< MusicSongInfoItemList >::mappedSearchRow().
Referenced by MusicLocalManagerWidget().
void MusicLocalManagerWidget::refreshItems () private slot
Refresh table items.
Definition at line 374 of file musiclocalmanagerwidget.cpp.
References MusicLocalManagerSongsTableWidget::addCellItems(), MusicSongMeta::album(), MusicSongMeta::artist(), TTKTabButton::currentIndex(), MusicItemQueryEdit::editor(), TTK::Core::enableBreakPoint(), TTK::File::fileListByPath(), G_SETTING_PTR, TTK::generateAlbum(), TTK::generateArtist(), TTK::generateGenre(), TTK::generateSongName(), TTK::generateYear(), MusicSongMeta::genre(), TTK::Core::isBreakPointEnabled(), MusicGifLabelMaskWidget::isRunning(), MusicSongInfoItem::m_album, MusicSongInfoItem::m_artist, MusicItemSearchInterface< MusicSongInfoItemList >::m_containerItems, MusicSongInfoItem::m_genre, m_loadingLabel, MusicSongInfoItem::m_path, m_searchEdit, m_sizeLabel, m_songTableWidget, m_tabButton, MusicSongInfoItem::m_title, MusicSongInfoItem::m_track, MusicSongInfoItem::m_year, MusicSettingManager::MediaLibraryPath, qAsConst, MusicSongMeta::read(), MusicLocalManagerSongsTableWidget::removeItems(), MusicGifLabelMaskWidget::run(), MusicGifLabelValueWidget::setValue(), MusicFormats::supportMusicInputFilterFormats(), MusicSongMeta::title(), MusicSongMeta::trackNum(), TTK_SEPARATOR, TTK_SIGNLE_SHOT, TTK_SLOT, updateStatisticWidget(), and MusicSongMeta::year().
Referenced by MusicLocalManagerWidget(), and updateMediaLibraryPath().
void MusicLocalManagerWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 490 of file musiclocalmanagerwidget.cpp.
References resizeWidget().
void MusicLocalManagerWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 349 of file musiclocalmanagerwidget.cpp.
References m_loadingLabel, m_songTableWidget, m_statisticTableWidget, MusicLocalManagerStatisticTableWidget::resizeSection(), and MusicLocalManagerSongsTableWidget::resizeSection().
Referenced by resizeEvent().
void MusicLocalManagerWidget::searchResultChanged (int row, int column) private slot
Search result from list.
Definition at line 447 of file musiclocalmanagerwidget.cpp.
References MusicLocalManagerSongsTableWidget::addCellItems(), TTKTabButton::currentIndex(), MusicItemQueryEdit::editor(), MusicItemSearchInterface< MusicSongInfoItemList >::m_containerItems, m_searchEdit, MusicItemSearchInterface< MusicSongInfoItemList >::m_searchResultItems, MusicItemSearchInterface< MusicSongInfoItemList >::m_searchResultLevel, m_songTableWidget, m_tabButton, qAsConst, MusicLocalManagerSongsTableWidget::removeItems(), and updateStatisticWidget().
Referenced by MusicLocalManagerWidget().
void MusicLocalManagerWidget::typeIndexChanged (int index) private slot
Type index changed.
Definition at line 356 of file musiclocalmanagerwidget.cpp.
References MusicItemSearchInterface< MusicSongInfoItemList >::clearSearchResult(), MusicItemQueryEdit::editor(), MusicItemSearchInterface< MusicSongInfoItemList >::m_containerItems, m_searchEdit, m_statisticTableWidget, and updateStatisticWidget().
Referenced by MusicLocalManagerWidget().
void MusicLocalManagerWidget::updateMediaLibraryPath () private slot
Update media library path.
Definition at line 437 of file musiclocalmanagerwidget.cpp.
References G_SETTING_PTR, TTK::File::getExistingDirectory(), MusicSettingManager::MediaLibraryPath, and refreshItems().
Referenced by MusicLocalManagerWidget().
void MusicLocalManagerWidget::updateStatisticWidget (int index, const MusicSongInfoItemList & items) private
Update statistic widget.
Definition at line 496 of file musiclocalmanagerwidget.cpp.
References MusicLocalManagerStatisticTableWidget::addCellItem(), m_statisticTableWidget, and qAsConst.
Referenced by refreshItems(), searchResultChanged(), and typeIndexChanged().
Member Data Documentation
MusicGifLabelValueWidget* MusicLocalManagerWidget::m_loadingLabel private
Definition at line 177 of file musiclocalmanagerwidget.h.
Referenced by MusicLocalManagerWidget(), refreshItems(), resizeWidget(), and ~MusicLocalManagerWidget().
MusicItemQueryEdit* MusicLocalManagerWidget::m_searchEdit private
Definition at line 176 of file musiclocalmanagerwidget.h.
Referenced by itemDoubleClicked(), MusicLocalManagerWidget(), refreshItems(), searchResultChanged(), typeIndexChanged(), and ~MusicLocalManagerWidget().
QLabel* MusicLocalManagerWidget::m_sizeLabel private
Definition at line 174 of file musiclocalmanagerwidget.h.
Referenced by MusicLocalManagerWidget(), refreshItems(), and ~MusicLocalManagerWidget().
MusicLocalManagerSongsTableWidget* MusicLocalManagerWidget::m_songTableWidget private
Definition at line 178 of file musiclocalmanagerwidget.h.
Referenced by MusicLocalManagerWidget(), refreshItems(), resizeWidget(), searchResultChanged(), and ~MusicLocalManagerWidget().
MusicLocalManagerStatisticTableWidget* MusicLocalManagerWidget::m_statisticTableWidget private
Definition at line 179 of file musiclocalmanagerwidget.h.
Referenced by MusicLocalManagerWidget(), resizeWidget(), typeIndexChanged(), updateStatisticWidget(), and ~MusicLocalManagerWidget().
TTKTabButton* MusicLocalManagerWidget::m_tabButton private
Definition at line 175 of file musiclocalmanagerwidget.h.
Referenced by MusicLocalManagerWidget(), refreshItems(), and searchResultChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiclocalmanagerwidget.h
TTKModule/TTKWidget/musicToolsKits/musiclocalmanagerwidget.cpp