TTKMusicPlayer: TTKFileInterface Class Reference
TTKFileInterface Class Reference
The class of the ttk file interface.
#include <ttkfileinterface.h>
Public Member Functions
TTKFileInterface ()=default
virtual ~TTKFileInterface ()=default
bool load (const QString &name)
bool fromFile (const QString &name)
Protected Attributes
QFile m_file
Detailed Description
The class of the ttk file interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file ttkfileinterface.h.
Constructor & Destructor Documentation
TTKFileInterface::TTKFileInterface () default
Object constructor.
virtual TTKFileInterface::~TTKFileInterface () virtual default
Object destructor.
Member Function Documentation
bool TTKFileInterface::fromFile (const QString & name) inline
Read datas from file by given name.
Definition at line 52 of file ttkfileinterface.h.
Referenced by MusicPlaylistManager::readCSVConfig(), MusicPlaylistManager::readDBPLConfig(), MusicPlaylistManager::readFPLConfig(), MusicPlaylistManager::readJSPFConfig(), MusicPlaylistManager::readM3UConfig(), MusicPlaylistManager::readPLSConfig(), and MusicPlaylistManager::readTXTConfig().
bool TTKFileInterface::load (const QString & name) inline
Write datas from file by given name.
Definition at line 43 of file ttkfileinterface.h.
Referenced by MusicPlaylistManager::writeCSVConfig(), MusicPlaylistManager::writeJSPFConfig(), MusicPlaylistManager::writeM3UConfig(), MusicPlaylistManager::writePLSConfig(), and MusicPlaylistManager::writeTXTConfig().
Member Data Documentation
QFile TTKFileInterface::m_file protected
Definition at line 59 of file ttkfileinterface.h.
Referenced by MusicCSVConfigManager::readBuffer(), MusicFPLConfigManager::readBuffer(), MusicTXTConfigManager::readBuffer(), MusicPLSConfigManager::readBuffer(), MusicJSPFConfigManager::readBuffer(), MusicDBPLConfigManager::readBuffer(), MusicM3UConfigManager::readBuffer(), MusicJSPFConfigManager::writeBuffer(), MusicPLSConfigManager::writeBuffer(), MusicTXTConfigManager::writeBuffer(), MusicM3UConfigManager::writeBuffer(), and MusicCSVConfigManager::writeBuffer().
The documentation for this class was generated from the following file:
TTKCommon/TTKLibrary/ttkfileinterface.h