TTKMusicPlayer: MusicKWSongCommentsRequest Class Reference
MusicKWSongCommentsRequest Class Reference
The class of the kuwo query song comments download data from net.
#include <musickwcommentsrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWSongCommentsRequest (QObject *parent=nullptr)
virtual void startToPage (int offset) overridefinal
virtual void startToSearch (const QString &value) overridefinal
Public Member Functions inherited from MusicCommentsRequest
MusicCommentsRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
int pageTotalSize () const noexcept
int pageSize () const noexcept
int totalSize () const noexcept
int pageIndex () const noexcept
bool pageValid () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicCommentsRequest
void createCommentItem (const MusicResultDataItem &item)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicCommentsRequest
QString m_id
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the kuwo query song comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickwcommentsrequest.h.
Constructor & Destructor Documentation
MusicKWSongCommentsRequest::MusicKWSongCommentsRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file musickwcommentsrequest.cpp.
References COMMENT_PAGE_SIZE, and MusicPageQueryRequest::m_pageSize.
Member Function Documentation
void MusicKWSongCommentsRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 46 of file musickwcommentsrequest.cpp.
References MusicCommentsRequest::createCommentItem(), TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), TTKAbstractNetwork::downLoadFinished(), TTKDateTime::format(), MusicResultDataItem::m_count, MusicResultDataItem::m_coverUrl, MusicResultDataItem::m_description, MusicResultDataItem::m_nickName, TTKAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicResultDataItem::m_updateTime, QJson::Parser::parse(), qAsConst, TTK::toString(), TTK_INFO_STREAM, TTK_NETWORK_QUERY_CHECK, and TTK_YEAR_TIMEZ_FORMAT.
Referenced by startToPage().
void MusicKWSongCommentsRequest::startToPage (int offset) final override virtual
Start to search data by offset page.
Reimplemented from MusicPageQueryRequest.
Definition at line 10 of file musickwcommentsrequest.cpp.
References TTKAbstractNetwork::deleteAll(), downLoadFinished(), KW_COMMENT_SONG_URL, MusicCommentsRequest::m_id, TTKAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageIndex, MusicPageQueryRequest::m_pageSize, TTKAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, ReqKWInterface::makeRequestRawHeader(), TTK::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK_INFO_STREAM, and TTK_SLOT.
void MusicKWSongCommentsRequest::startToSearch (const QString & value) final override virtual
Start to search data by input data.
Reimplemented from MusicCommentsRequest.
Definition at line 27 of file musickwcommentsrequest.cpp.
References TTKAbstractNetwork::downLoadDataChanged(), TTKSemaphoreLoop::exec(), MusicAbstractQueryRequest::isEmpty(), MusicAbstractQueryRequest::items(), MusicCommentsRequest::m_id, MusicAbstractQueryRequest::Meta, MusicAbstractQueryRequest::Music, MusicAbstractQueryRequest::setQueryMode(), MusicAbstractQueryRequest::setQueryType(), MusicCommentsRequest::startToSearch(), MusicQueryRequest::startToSearch(), and TTK_INFO_STREAM.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwcommentsrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwcommentsrequest.cpp