TTKMusicplayer: MusicWebDJRadioFoundWidget Class Reference
MusicWebDJRadioFoundWidget Class Reference
The class of the dj radio music found widget.
#include <musicwebdjradiofoundwidget.h>
Public Slots
void createProgramItem (const MusicResultsItem &item)
void currentRadioClicked (const MusicResultsItem &item)
void backToMainMenuClicked ()
void buttonClicked (int index)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Signals
void backToMainMenu ()
Public Member Functions
MusicWebDJRadioFoundWidget (QWidget *parent=nullptr)
virtual ~MusicWebDJRadioFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=nullptr)
~MusicFoundAbstractWidget ()
void initWidget ()
Protected Attributes
bool m_firstInit
QGridLayout * m_gridLayout
MusicPagingWidgetObject * m_pagingWidgetObject
MusicWebDJRadioInfoWidget * m_infoWidget
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the dj radio music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 76 of file musicwebdjradiofoundwidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioFoundWidget::MusicWebDJRadioFoundWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 90 of file musicwebdjradiofoundwidget.cpp.
References createProgramItem(), MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, m_infoWidget, MusicFoundAbstractWidget::m_mainWindow, and m_pagingWidgetObject.
MusicWebDJRadioFoundWidget::~MusicWebDJRadioFoundWidget () virtual
Definition at line 106 of file musicwebdjradiofoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, m_infoWidget, and m_pagingWidgetObject.
Member Function Documentation
void MusicWebDJRadioFoundWidget::backToMainMenu () signal
Set current index to main menu page.
Referenced by backToMainMenuClicked(), createProgramItem(), and currentRadioClicked().
void MusicWebDJRadioFoundWidget::backToMainMenuClicked () slot
Set current index to main menu page.
Definition at line 229 of file musicwebdjradiofoundwidget.cpp.
References backToMainMenu(), MusicFoundAbstractWidget::m_container, m_firstInit, and PLAYLIST_WINDOW_INDEX_0.
Referenced by currentRadioClicked().
void MusicWebDJRadioFoundWidget::buttonClicked (int index) slot
Paging widget button has changed.
Definition at line 239 of file musicwebdjradiofoundwidget.cpp.
References MusicPagingWidgetObject::currentIndex(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicPagingWidgetObject::paging(), and MusicDownLoadPagingThread::startToPage().
Referenced by createProgramItem().
void MusicWebDJRadioFoundWidget::createProgramItem (const MusicResultsItem & item) slot
Query all quality musics is finished.
Definition at line 150 of file musicwebdjradiofoundwidget.cpp.
References backToMainMenu(), buttonClicked(), MusicPagingWidgetObject::createPagingWidget(), currentRadioClicked(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), LINE_SPACING_SIZE, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_statusLabel, MusicUIObject::MColorStyle06, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, MStatic_cast, MusicPagingWidgetObject::reset(), and MusicWebDJRadioFoundItemWidget::setMusicResultsItem().
Referenced by MusicWebDJRadioFoundWidget().
void MusicWebDJRadioFoundWidget::currentRadioClicked (const MusicResultsItem & item) slot
Current radio clicked.
Definition at line 218 of file musicwebdjradiofoundwidget.cpp.
References backToMainMenu(), backToMainMenuClicked(), MusicFoundAbstractWidget::m_container, MusicResultsItem::m_id, m_infoWidget, PLAYLIST_WINDOW_INDEX_1, and MusicWebDJRadioInfoWidget::setSongName().
Referenced by createProgramItem(), and setSongNameById().
void MusicWebDJRadioFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 128 of file musicwebdjradiofoundwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, m_infoWidget, MusicFoundAbstractWidget::m_resizeWidgets, and MusicWebDJRadioInfoWidget::resizeWindow().
Referenced by MusicWebDJRadioWidget::resizeWindow().
void MusicWebDJRadioFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 114 of file musicwebdjradiofoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicDownLoadQueryThreadAbstract::OtherQuery, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicWebDJRadioWidget::programItemClicked().
void MusicWebDJRadioFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 120 of file musicwebdjradiofoundwidget.cpp.
References currentRadioClicked(), MusicResultsItem::m_id, and MusicFoundAbstractWidget::setSongName().
Referenced by MusicWebDJRadioWidget::programItemClicked().
Member Data Documentation
bool MusicWebDJRadioFoundWidget::m_firstInit protected
Definition at line 127 of file musicwebdjradiofoundwidget.h.
Referenced by backToMainMenuClicked(), createProgramItem(), and MusicWebDJRadioFoundWidget().
QGridLayout* MusicWebDJRadioFoundWidget::m_gridLayout protected
Definition at line 128 of file musicwebdjradiofoundwidget.h.
Referenced by buttonClicked(), createProgramItem(), MusicWebDJRadioFoundWidget(), resizeWindow(), and ~MusicWebDJRadioFoundWidget().
MusicWebDJRadioInfoWidget* MusicWebDJRadioFoundWidget::m_infoWidget protected
Definition at line 130 of file musicwebdjradiofoundwidget.h.
Referenced by currentRadioClicked(), MusicWebDJRadioFoundWidget(), resizeWindow(), and ~MusicWebDJRadioFoundWidget().
MusicPagingWidgetObject* MusicWebDJRadioFoundWidget::m_pagingWidgetObject protected
Definition at line 129 of file musicwebdjradiofoundwidget.h.
Referenced by buttonClicked(), createProgramItem(), MusicWebDJRadioFoundWidget(), and ~MusicWebDJRadioFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiofoundwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiofoundwidget.cpp