TTKMusicplayer: MusicEqualizerDialog Class Reference
MusicEqualizerDialog Class Reference
The class of the equalizer widget.
#include <musicequalizerdialog.h>
Public Slots
void setEqEnable ()
void resetEq ()
void verticalSliderChanged (int index)
void eqChoiceIndexChanged (int index)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void setEqEffect (const MusicObject::MIntList &effect)
void setEnaleEffect (bool enable)
Public Member Functions
MusicEqualizerDialog (QWidget *parent=0)
virtual ~MusicEqualizerDialog ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Member Functions
void init ()
void initSlider (QSlider *slider, int index)
void setControlEnable (bool enable) const
void readEqInformation ()
void writeEqInformation () const
void initEqualizeValue ()
void emitParameter ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicEqualizerDialog * m_ui
bool m_eable
bool m_eqChoiceSelected
MusicObject::MIntList m_equalizeValue
QSignalMapper * m_signalMapper
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the equalizer widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicequalizerdialog.h.
Constructor & Destructor Documentation
MusicEqualizerDialog::MusicEqualizerDialog (QWidget * parent = 0) explicit
Definition at line 14 of file musicequalizerdialog.cpp.
References eqChoiceIndexChanged(), getClassName(), MusicPlayer::getClassName(), MusicSoundEffectsWidget::getClassName(), init(), initEqualizeValue(), M_CONNECTION_PTR, m_eable, m_eqChoiceSelected, m_ui, MusicUIObject::MComboBoxStyle01, MusicUIObject::MItemView01, MusicUIObject::MKGEqualizerOff, MusicUIObject::MScrollBarStyle01, MusicUIObject::MToolButtonStyle04, readEqInformation(), and setControlEnable().
MusicEqualizerDialog::~MusicEqualizerDialog () virtual
Object contsructor.
Definition at line 57 of file musicequalizerdialog.cpp.
References getClassName(), M_CONNECTION_PTR, m_signalMapper, m_ui, and writeEqInformation().
Member Function Documentation
void MusicEqualizerDialog::emitParameter () protected
Init equalizer parameters value.
Definition at line 170 of file musicequalizerdialog.cpp.
References m_ui, and setEqEffect().
Referenced by setEqEnable(), and verticalSliderChanged().
void MusicEqualizerDialog::eqChoiceIndexChanged (int index) slot
Current equlizer parameters has changed by changed index.
Definition at line 250 of file musicequalizerdialog.cpp.
References m_eqChoiceSelected, m_equalizeValue, and m_ui.
Referenced by MusicEqualizerDialog().
int MusicEqualizerDialog::exec () virtual slot
Equlizer presets index changed by change index.
Definition at line 270 of file musicequalizerdialog.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicApplicationObject::musicSetEqualizer().
QString MusicEqualizerDialog::getClassName () static
Definition at line 65 of file musicequalizerdialog.cpp.
Referenced by MusicEqualizerDialog(), MusicConnectionPool::poolConnect(), and ~MusicEqualizerDialog().
void MusicEqualizerDialog::init () protected
Override exec function.
Definition at line 70 of file musicequalizerdialog.cpp.
References initSlider(), m_signalMapper, m_ui, MusicUIObject::MPushButtonStyle04, resetEq(), setEqEnable(), MusicUtils::Widget::setLabelFontSize(), and verticalSliderChanged().
Referenced by MusicEqualizerDialog().
void MusicEqualizerDialog::initEqualizeValue () protected
Write equalizer info from config.
Definition at line 227 of file musicequalizerdialog.cpp.
References m_equalizeValue.
Referenced by MusicEqualizerDialog().
void MusicEqualizerDialog::initSlider (QSlider * slider, int index) protected
Init widget and parameters.
Definition at line 105 of file musicequalizerdialog.cpp.
References m_signalMapper, and MusicUIObject::MSliderStyle04.
Referenced by init().
void MusicEqualizerDialog::readEqInformation () protected
Enable or disable control state.
Definition at line 113 of file musicequalizerdialog.cpp.
References MusicSettingManager::EqualizerEnableChoiced, MusicSettingManager::EqualizerIndexChoiced, MusicSettingManager::EqualizerValueChoiced, M_SETTING_PTR, m_ui, and resetEq().
Referenced by MusicEqualizerDialog().
void MusicEqualizerDialog::resetEq () slot
Set equlizer enable.
Definition at line 210 of file musicequalizerdialog.cpp.
References m_ui.
Referenced by init(), and readEqInformation().
void MusicEqualizerDialog::setControlEnable (bool enable) const protected
Init and create slider.
Definition at line 193 of file musicequalizerdialog.cpp.
References m_ui.
Referenced by MusicEqualizerDialog(), and setEqEnable().
void MusicEqualizerDialog::setEnaleEffect (bool enable) signal
Current equlizer parameters changed emit.
Referenced by setEqEnable().
void MusicEqualizerDialog::setEqEffect (const MusicObject::MIntList & effect) signal
Get class object name.
Referenced by emitParameter().
void MusicEqualizerDialog::setEqEnable () slot
Set equlizer enable state changed emit.
Definition at line 180 of file musicequalizerdialog.cpp.
References emitParameter(), m_eable, m_ui, MusicUIObject::MKGEqualizerOff, MusicUIObject::MKGEqualizerOn, setControlEnable(), and setEnaleEffect().
Referenced by init().
void MusicEqualizerDialog::verticalSliderChanged (int index) slot
Reset equlizer parameters.
Definition at line 161 of file musicequalizerdialog.cpp.
References emitParameter(), m_eqChoiceSelected, and m_ui.
Referenced by init().
void MusicEqualizerDialog::writeEqInformation () const protected
Read equalizer info from config.
Definition at line 147 of file musicequalizerdialog.cpp.
References MusicSettingManager::EqualizerEnableChoiced, MusicSettingManager::EqualizerIndexChoiced, MusicSettingManager::EqualizerValueChoiced, m_eable, M_SETTING_PTR, and m_ui.
Referenced by ~MusicEqualizerDialog().
Member Data Documentation
bool MusicEqualizerDialog::m_eable protected
Definition at line 105 of file musicequalizerdialog.h.
Referenced by MusicEqualizerDialog(), setEqEnable(), and writeEqInformation().
bool MusicEqualizerDialog::m_eqChoiceSelected protected
Definition at line 106 of file musicequalizerdialog.h.
Referenced by eqChoiceIndexChanged(), MusicEqualizerDialog(), and verticalSliderChanged().
MusicObject::MIntList MusicEqualizerDialog::m_equalizeValue protected
Definition at line 107 of file musicequalizerdialog.h.
Referenced by eqChoiceIndexChanged(), and initEqualizeValue().
QSignalMapper* MusicEqualizerDialog::m_signalMapper protected
Definition at line 108 of file musicequalizerdialog.h.
Referenced by init(), initSlider(), and ~MusicEqualizerDialog().
Ui::MusicEqualizerDialog* MusicEqualizerDialog::m_ui protected
Emit current equalizer parameters value.
Definition at line 104 of file musicequalizerdialog.h.
Referenced by emitParameter(), eqChoiceIndexChanged(), exec(), init(), MusicEqualizerDialog(), readEqInformation(), resetEq(), setControlEnable(), setEqEnable(), verticalSliderChanged(), writeEqInformation(), and ~MusicEqualizerDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicequalizerdialog.h
TTKModule/TTKWidget/musicWidgetKits/musicequalizerdialog.cpp