TTKMusicplayer: MusicRunApplication Class Reference
MusicRunApplication Class Reference
The class of the music run application.
#include <musicrunapplication.h>
Public Slots
bool sendMessage (const QString &message, int timeout=5000)
void activateWindow ()
Signals
void messageReceived (const QString &message)
Public Member Functions
MusicRunApplication (int &argc, char **argv, bool GUIenabled=true)
MusicRunApplication (const QString &id, int &argc, char **argv)
MusicRunApplication (int &argc, char **argv, Type type)
void initialize (bool dummy=true)
bool isRunning () const
QString id () const
void setActivationWindow (QWidget *aw, bool activateOnMessage=true)
QWidget * activationWindow () const
Private Member Functions
void sysInit (const QString &appId=QString())
Detailed Description
The class of the music run application.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicrunapplication.h.
Constructor & Destructor Documentation
MusicRunApplication::MusicRunApplication (int & argc, char ** argv, bool GUIenabled = true)
Object contsructor.
Definition at line 32 of file musicrunapplication.cpp.
References MUSIC_INIT_PRIVATE, and sysInit().
MusicRunApplication::MusicRunApplication (const QString & id, int & argc, char ** argv)
Object contsructor.
Definition at line 39 of file musicrunapplication.cpp.
References MUSIC_INIT_PRIVATE, and sysInit().
MusicRunApplication::MusicRunApplication (int & argc, char ** argv, Type type)
Object contsructor.
Definition at line 47 of file musicrunapplication.cpp.
References MUSIC_INIT_PRIVATE, and sysInit().
Member Function Documentation
void MusicRunApplication::activateWindow () slot
Selected current active window.
Definition at line 123 of file musicrunapplication.cpp.
References MUSIC_D.
Referenced by setActivationWindow().
QWidget * MusicRunApplication::activationWindow () const
Get current active window.
Definition at line 111 of file musicrunapplication.cpp.
References MUSIC_D.
QString MusicRunApplication::id () const
Get current server id.
Definition at line 90 of file musicrunapplication.cpp.
References MUSIC_D.
void MusicRunApplication::initialize (bool dummy = true)
Initialize the current server.
Definition at line 78 of file musicrunapplication.cpp.
References isRunning().
bool MusicRunApplication::isRunning () const
Check the current server is running or not.
Definition at line 84 of file musicrunapplication.cpp.
References MUSIC_D.
Referenced by initialize(), and main().
void MusicRunApplication::messageReceived (const QString & message) signal
Emit when the current message received.
Referenced by setActivationWindow(), and sysInit().
bool MusicRunApplication::sendMessage (const QString & message, int timeout = 5000) slot
Emit when the current message received.
Definition at line 117 of file musicrunapplication.cpp.
References MUSIC_D.
void MusicRunApplication::setActivationWindow (QWidget * aw, bool activateOnMessage = true)
Set current active window.
Definition at line 96 of file musicrunapplication.cpp.
References activateWindow(), messageReceived(), and MUSIC_D.
void MusicRunApplication::sysInit (const QString & appId = QString()) private
Init the system parameter.
Definition at line 134 of file musicrunapplication.cpp.
References messageReceived(), and MUSIC_D.
Referenced by MusicRunApplication().
The documentation for this class was generated from the following files:
TTKRun/TTKApp/musicrunapplication.h
TTKRun/TTKApp/musicrunapplication.cpp