TTKMusicplayer: MusicBackgroundRemoteWidget Class Reference
MusicBackgroundRemoteWidget Class Reference
The class of the remote background widget.
#include <musicbackgroundremotewidget.h>
Public Slots
void buttonClicked (int index)
void downLoadDataChanged (const QString &data)
void downLoadDataChanged (const MusicSkinRemoteGroups &data)
Signals
void showCustomSkin (const QString &path)
Public Member Functions
MusicBackgroundRemoteWidget (QWidget *parent=0)
~MusicBackgroundRemoteWidget ()
void init ()
void abort ()
QWidget * createFunctionsWidget (bool revert, QWidget *object=0)
void outputRemoteSkin (MusicBackgroundImage &image, const QString &data)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
QPushButton * createButton (const QString &name)
void buttonStyleChanged ()
Protected Attributes
int m_currentIndex
QWidget * m_functionsWidget
QList< QPushButton * > m_functionsItems
MusicSkinRemoteGroups m_groups
MusicBackgroundListWidget * m_listWidget
MusicDownloadQueueCache * m_downloadQueue
MusicDownloadBackgroundRemoteThread * m_queryThread
Detailed Description
The class of the remote background widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 23 of file musicbackgroundremotewidget.h.
Constructor & Destructor Documentation
MusicBackgroundRemoteWidget::MusicBackgroundRemoteWidget (QWidget * parent = 0) explicit
Definition at line 10 of file musicbackgroundremotewidget.cpp.
References MusicDownLoadThreadAbstract::Download_BigBG, downLoadDataChanged(), m_currentIndex, m_downloadQueue, m_functionsWidget, m_listWidget, and m_queryThread.
MusicBackgroundRemoteWidget::~MusicBackgroundRemoteWidget ()
Object contsructor.
Definition at line 30 of file musicbackgroundremotewidget.cpp.
References abort(), m_downloadQueue, m_functionsWidget, m_listWidget, and m_queryThread.
Member Function Documentation
void MusicBackgroundRemoteWidget::abort ()
Init the current download object.
Definition at line 54 of file musicbackgroundremotewidget.cpp.
References MusicDownloadQueueCache::abort(), and m_downloadQueue.
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged(), and ~MusicBackgroundRemoteWidget().
void MusicBackgroundRemoteWidget::buttonClicked (int index) slot
Reset the current bg when user click remote bg emit.
Definition at line 137 of file musicbackgroundremotewidget.cpp.
References MusicDownloadQueueCache::abort(), MusicDownloadQueueCache::addImageQueue(), buttonStyleChanged(), CACHE_DIR_FULL, MusicBackgroundListWidget::clearAllItems(), MusicBackgroundListWidget::createItem(), m_currentIndex, m_downloadQueue, m_groups, m_listWidget, MusicDownloadQueueData::m_savePath, MusicDownloadQueueData::m_url, MusicDownloadQueueCache::startToDownload(), and TTS_FILE.
Referenced by createFunctionsWidget().
void MusicBackgroundRemoteWidget::buttonStyleChanged () protected
Create button.
Definition at line 212 of file musicbackgroundremotewidget.cpp.
References m_currentIndex, m_functionsItems, MusicUIObject::MColorStyle08, and MusicUIObject::MPushButtonStyle02.
Referenced by buttonClicked().
QPushButton * MusicBackgroundRemoteWidget::createButton (const QString & name) protected
Send download data from net.
Definition at line 197 of file musicbackgroundremotewidget.cpp.
References m_functionsItems, m_functionsWidget, and MusicUIObject::MPushButtonStyle02.
Referenced by createFunctionsWidget().
QWidget * MusicBackgroundRemoteWidget::createFunctionsWidget (bool revert, QWidget * object = 0)
Abort the current download thread.
Definition at line 59 of file musicbackgroundremotewidget.cpp.
References buttonClicked(), createButton(), m_functionsItems, m_functionsWidget, MusicUIObject::MColorStyle08, and MStatic_cast.
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundRemoteWidget::downLoadDataChanged (const QString & data) slot
Remote bg type selected by index.
Definition at line 171 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundImage::isValid(), m_listWidget, outputRemoteSkin(), and MusicBackgroundListWidget::updateItem().
Referenced by init(), and MusicBackgroundRemoteWidget().
void MusicBackgroundRemoteWidget::downLoadDataChanged (const MusicSkinRemoteGroups & data) slot
Send download data from net.
Definition at line 181 of file musicbackgroundremotewidget.cpp.
References m_functionsItems, MusicSkinRemoteGroup::m_group, and m_groups.
QString MusicBackgroundRemoteWidget::getClassName () static
Definition at line 39 of file musicbackgroundremotewidget.cpp.
void MusicBackgroundRemoteWidget::init ()
Get class object name.
Definition at line 44 of file musicbackgroundremotewidget.cpp.
References downLoadDataChanged(), m_queryThread, and MusicDownloadBackgroundRemoteThread::startToDownload().
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundRemoteWidget::outputRemoteSkin (MusicBackgroundImage & image, const QString & data)
Create functions widget.
Definition at line 124 of file musicbackgroundremotewidget.cpp.
References m_currentIndex, m_groups, MusicBackgroundImage::m_item, MusicSkinRemoteItem::m_name, MusicSkinConfigItem::m_name, MusicBackgroundImage::m_pix, MusicSkinRemoteItem::m_useCount, MusicSkinConfigItem::m_useCount, and MusicExtractWrap::outputThunderSkin().
Referenced by downLoadDataChanged(), and MusicBackgroundSkinDialog::remoteBackgroundListWidgetItemClicked().
void MusicBackgroundRemoteWidget::showCustomSkin (const QString & path) signal
Output remote skin.
Member Data Documentation
int MusicBackgroundRemoteWidget::m_currentIndex protected
Button style changed.
Definition at line 86 of file musicbackgroundremotewidget.h.
Referenced by buttonClicked(), buttonStyleChanged(), MusicBackgroundRemoteWidget(), and outputRemoteSkin().
MusicDownloadQueueCache* MusicBackgroundRemoteWidget::m_downloadQueue protected
Definition at line 91 of file musicbackgroundremotewidget.h.
Referenced by abort(), buttonClicked(), MusicBackgroundRemoteWidget(), and ~MusicBackgroundRemoteWidget().
QList<QPushButton*> MusicBackgroundRemoteWidget::m_functionsItems protected
Definition at line 88 of file musicbackgroundremotewidget.h.
Referenced by buttonStyleChanged(), createButton(), createFunctionsWidget(), and downLoadDataChanged().
QWidget* MusicBackgroundRemoteWidget::m_functionsWidget protected
Definition at line 87 of file musicbackgroundremotewidget.h.
Referenced by createButton(), createFunctionsWidget(), MusicBackgroundRemoteWidget(), and ~MusicBackgroundRemoteWidget().
MusicSkinRemoteGroups MusicBackgroundRemoteWidget::m_groups protected
Definition at line 89 of file musicbackgroundremotewidget.h.
Referenced by buttonClicked(), downLoadDataChanged(), and outputRemoteSkin().
MusicBackgroundListWidget* MusicBackgroundRemoteWidget::m_listWidget protected
Definition at line 90 of file musicbackgroundremotewidget.h.
Referenced by buttonClicked(), downLoadDataChanged(), MusicBackgroundRemoteWidget(), and ~MusicBackgroundRemoteWidget().
MusicDownloadBackgroundRemoteThread* MusicBackgroundRemoteWidget::m_queryThread protected
Definition at line 92 of file musicbackgroundremotewidget.h.
Referenced by init(), MusicBackgroundRemoteWidget(), and ~MusicBackgroundRemoteWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.cpp