TTKMusicplayer: MusicXMQueryMovieRequest Class Reference
MusicXMQueryMovieRequest Class Reference
The class to xiami mv query download data from net.
#include <musicxmquerymovierequest.h>
Public Slots
virtual void downLoadFinished () override
void pageDownLoadFinished ()
void singleDownLoadFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicXMQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToPage (int offset) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicQueryMovieRequest
MusicQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &movie)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual ~MusicAbstractQueryRequest ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
virtual ~MusicPagingRequest ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
void readFromMusicMVAttribute (MusicObject::MusicSongInformation *info)
Protected Member Functions inherited from MusicAbstractQueryRequest
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryMovieRequest
void createMovieInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
QVariantMap m_headerData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicXMQueryInterface
bool makeTokenQueryCookies (QString &tk, QString &tke)
void makeTokenQueryUrl (QNetworkRequest *request, bool mode, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariant &key, const QString &quality, bool all)
void readFromMusicSongLrc (MusicObject::MusicSongInformation *info)
Detailed Description
The class to xiami mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicxmquerymovierequest.h.
Constructor & Destructor Documentation
MusicXMQueryMovieRequest::MusicXMQueryMovieRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicxmquerymovierequest.cpp.
References MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_XM_INTERFACE.
Member Function Documentation
void MusicXMQueryMovieRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 81 of file musicxmquerymovierequest.cpp.
References MusicAbstractQueryRequest::clearAllItems(), MusicAbstractQueryRequest::createSearchedItem(), MusicPagingRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicUtils::String::illegalCharactersReplaced(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkQuery, QJson::Parser::parse(), readFromMusicMVAttribute(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicXMQueryMovieRequest::pageDownLoadFinished () slot
Download page data from net finished.
Definition at line 148 of file musicxmquerymovierequest.cpp.
References MusicQueryMovieRequest::createMovieInfoItem(), MusicPagingRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicResultsItem::m_name, MusicPagingRequest::m_pageTotal, MusicAbstractNetwork::m_reply, MusicResultsItem::m_updateTime, QJson::Parser::parse(), and TTK_LOGGER_INFO.
Referenced by startToPage().
void MusicXMQueryMovieRequest::readFromMusicMVAttribute (MusicObject::MusicSongInformation * info) protected
Read mv info attribute from query results.
Definition at line 233 of file musicxmquerymovierequest.cpp.
References MusicAbstractQueryRequest::createSearchedItem(), MusicSemaphoreLoop::exec(), MusicAbstractQueryRequest::findUrlFileSize(), MusicUtils::String::illegalCharactersReplaced(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_musicSongInfos, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicObject::MusicSongAttribute::m_url, MusicXMQueryInterface::makeTokenQueryUrl(), MusicAbstractQueryRequest::mapQueryServerString(), MB_500, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkError, MusicObject::NetworkQuery, QJson::Parser::parse(), MusicObject::setSslConfiguration(), MusicUtils::String::stringSplitToken(), XM_MOVIE_DATA_URL, and XM_MOVIE_URL.
Referenced by downLoadFinished(), and singleDownLoadFinished().
void MusicXMQueryMovieRequest::singleDownLoadFinished () slot
Download single data from net finished.
Definition at line 204 of file musicxmquerymovierequest.cpp.
References MusicAbstractQueryRequest::clearAllItems(), MusicAbstractQueryRequest::createSearchedItem(), MusicPagingRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractQueryRequest::m_searchText, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MusicObject::NetworkQuery, readFromMusicMVAttribute(), and TTK_LOGGER_INFO.
Referenced by startToSingleSearch().
void MusicXMQueryMovieRequest::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicPagingRequest.
Definition at line 40 of file musicxmquerymovierequest.cpp.
References MusicPagingRequest::deleteAll(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicPagingRequest::m_pageTotal, MusicAbstractNetwork::m_reply, MusicAbstractQueryRequest::m_searchText, MusicAbstractNetwork::m_stateCode, MusicXMQueryInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicObject::NetworkQuery, pageDownLoadFinished(), MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), TTK_LOGGER_INFO, XM_ARTIST_MOVIE_DATA_URL, and XM_ARTIST_MOVIE_URL.
void MusicXMQueryMovieRequest::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicQueryMovieRequest.
Definition at line 13 of file musicxmquerymovierequest.cpp.
References MusicPagingRequest::deleteAll(), downLoadFinished(), MusicAbstractQueryRequest::m_currentType, MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicAbstractNetwork::m_reply, MusicAbstractQueryRequest::m_searchText, MusicAbstractNetwork::m_stateCode, MusicXMQueryInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicObject::NetworkQuery, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), TTK_LOGGER_INFO, XM_SONG_SEARCH_DATA_URL, and XM_SONG_SEARCH_URL.
void MusicXMQueryMovieRequest::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 67 of file musicxmquerymovierequest.cpp.
References MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_searchText, MT_MS, singleDownLoadFinished(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/xm/musicxmquerymovierequest.h
TTKModule/TTKCore/musicNetworkKits/music/xm/musicxmquerymovierequest.cpp