TTKMusicPlayer: MusicVoicePopWidget Class Reference
MusicVoicePopWidget Class Reference
The class of the volume popup widget.
#include <musicvoicepopwidget.h>
Public Slots
void timeToReset ()
void valueChanged (int value)
void updateVoiceRemove (bool v=true)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicVoicePopWidget (QWidget *parent=nullptr)
~MusicVoicePopWidget ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Private Member Functions
virtual void leaveEvent (QEvent *event) overridefinal
virtual void enterEvent (QtEnterEvent *event) overridefinal
void initialize ()
Private Attributes
bool m_menuShown
TTKClickedSlider * m_slider
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the volume popup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicvoicepopwidget.h.
Constructor & Destructor Documentation
MusicVoicePopWidget::MusicVoicePopWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 10 of file musicvoicepopwidget.cpp.
References initialize(), MusicToolMenuWidget::popupMenu(), and updateVoiceRemove().
MusicVoicePopWidget::~MusicVoicePopWidget ()
Object destructor.
Definition at line 20 of file musicvoicepopwidget.cpp.
References m_slider.
Member Function Documentation
void MusicVoicePopWidget::enterEvent (QtEnterEvent * event) final override private virtual
Definition at line 31 of file musicvoicepopwidget.cpp.
References TTK::UI::InteriorMicrophoneOn, m_menuShown, m_slider, MusicToolMenuWidget::popupMenu(), timeToReset(), TTK_DN_S2MS, TTK_SIGNLE_SHOT, TTK_SLOT, and TTK::TTKQmmp::updateVoiceConfig().
void MusicVoicePopWidget::initialize () private
Init widget and parameter.
Definition at line 67 of file musicvoicepopwidget.cpp.
References TTK::UI::InteriorMicrophone, MusicToolMenuWidget::m_containWidget, m_slider, MusicToolMenuWidget::setTranslucentBackground(), TTK::UI::SliderStyle02, and valueChanged().
Referenced by MusicVoicePopWidget().
void MusicVoicePopWidget::leaveEvent (QEvent * event) final override private virtual
Override the widget event.
Definition at line 25 of file musicvoicepopwidget.cpp.
References MusicToolMenuWidget::m_menu, TTK_DN_S2MS, TTK_SIGNLE_SHOT, and TTK_SLOT.
void MusicVoicePopWidget::timeToReset () slot
Timer ot reset show slider.
Definition at line 46 of file musicvoicepopwidget.cpp.
References m_menuShown.
Referenced by enterEvent().
void MusicVoicePopWidget::updateVoiceRemove (bool v = true) slot
Update voice remove mode.
Definition at line 56 of file musicvoicepopwidget.cpp.
References TTK::UI::InteriorMicrophone, TTK::UI::InteriorMicrophoneOn, TTK::TTKQmmp::isEffectEnabled(), and TTK::TTKQmmp::setEffectEnabled().
Referenced by MusicLrcContainerForInterior::applyParameter(), and MusicVoicePopWidget().
void MusicVoicePopWidget::valueChanged (int value) slot
Slider value changed.
Definition at line 51 of file musicvoicepopwidget.cpp.
References TTK::TTKQmmp::updateVoiceConfig().
Referenced by initialize().
Member Data Documentation
bool MusicVoicePopWidget::m_menuShown private
Definition at line 67 of file musicvoicepopwidget.h.
Referenced by enterEvent(), and timeToReset().
TTKClickedSlider* MusicVoicePopWidget::m_slider private
Definition at line 68 of file musicvoicepopwidget.h.
Referenced by enterEvent(), initialize(), and ~MusicVoicePopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musicvoicepopwidget.h
TTKModule/TTKWidget/musicLrcKits/musicvoicepopwidget.cpp