TTKMusicPlayer: MusicLrcSearchTableWidget Class Reference
MusicLrcSearchTableWidget Class Reference
The class of the lrc search table widget.
#include <musiclrcsearchtablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
virtual void itemDoubleClicked (int row, int column) overridefinal
virtual void removeItems () overridefinal
virtual void createResultItem (const MusicResultInfoItem &result) overridefinal
Public Slots inherited from MusicItemSearchTableWidget
virtual void searchActionClicked (QAction *action)
Public Slots inherited from MusicQueryTableWidget
virtual void itemCellClicked (int row, int column) override
virtual void itemDoubleClicked (int row, int column)=0
virtual void removeItems () override
virtual void createResultItem (const MusicResultInfoItem &result)=0
void createFinishedItem ()
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void resolvedSuccess ()
void lrcDownloadStateChanged (const QString &name)
Signals inherited from MusicQueryTableWidget
void startToQueryByText (const QString &text)
Public Member Functions
MusicLrcSearchTableWidget (QWidget *parent=nullptr)
~MusicLrcSearchTableWidget ()
virtual void startToSearchByValue (const QString &value) overridefinal
virtual void downloadQueryResult (int row) overridefinal
Public Member Functions inherited from MusicItemSearchTableWidget
MusicItemSearchTableWidget (QWidget *parent=nullptr)
~MusicItemSearchTableWidget ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * queryInput () const
virtual void resizeGeometry () override
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedItemRows () const
TTKIntList uncheckedItemRows () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
TTKIntList selectedRows () const
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Additional Inherited Members
Protected Member Functions inherited from MusicItemSearchTableWidget
void createContextMenu (QMenu &menu)
QString randSimulation () const noexcept
Protected Member Functions inherited from MusicQueryTableWidget
virtual void resizeEvent (QResizeEvent *event) override
void setLoadingStatus (bool status) const
bool isValid (int row) const noexcept
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes inherited from MusicItemSearchTableWidget
QActionGroup * m_searchActions
Protected Attributes inherited from MusicQueryTableWidget
MusicGifLabelWidget * m_loadingLabel
TTKLabelItemDelegate * m_labelDelegate
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the lrc search table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musiclrcsearchtablewidget.h.
Constructor & Destructor Documentation
MusicLrcSearchTableWidget::MusicLrcSearchTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musiclrcsearchtablewidget.cpp.
MusicLrcSearchTableWidget::~MusicLrcSearchTableWidget ()
Object destructor.
Definition at line 20 of file musiclrcsearchtablewidget.cpp.
References removeItems().
Member Function Documentation
void MusicLrcSearchTableWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Definition at line 135 of file musiclrcsearchtablewidget.cpp.
References MusicItemSearchTableWidget::createContextMenu().
void MusicLrcSearchTableWidget::createResultItem (const MusicResultInfoItem & result) final override virtual slot
Create search result items.
Definition at line 95 of file musiclrcsearchtablewidget.cpp.
References TTK::UI::Color02, TTK::Widget::elidedText(), MusicResultInfoItem::m_artistName, MusicResultInfoItem::m_duration, MusicResultInfoItem::m_songName, MusicResultInfoItem::m_type, MusicItemSearchTableWidget::randSimulation(), and TTK_CHECKED_ROLE.
void MusicLrcSearchTableWidget::downloadQueryResult (int row) final override virtual
Download query result data.
download lrc
Implements MusicQueryTableWidget.
Definition at line 41 of file musiclrcsearchtablewidget.cpp.
References G_DOWNLOAD_QUERY_PTR, TTKAbstractTableWidget::isValid(), MusicAbstractQueryRequest::items(), LRC_FILE, TTK::String::lrcDirPrefix(), lrcDownloadStateChanged(), MusicQueryTableWidget::m_networkRequest, MusicToastLabel::popup(), MusicAbstractQueryRequest::queryValue(), and MusicAbstractDownloadRequest::startToRequest().
Referenced by itemCellClicked(), and itemDoubleClicked().
void MusicLrcSearchTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 69 of file musiclrcsearchtablewidget.cpp.
References downloadQueryResult(), and MusicQueryTableWidget::itemCellClicked().
void MusicLrcSearchTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 56 of file musiclrcsearchtablewidget.cpp.
References TTKAbstractTableWidget::itemCellEntered().
void MusicLrcSearchTableWidget::itemDoubleClicked (int row, int column) final override virtual slot
Table widget item cell double clicked.
Definition at line 79 of file musiclrcsearchtablewidget.cpp.
References downloadQueryResult().
void MusicLrcSearchTableWidget::lrcDownloadStateChanged (const QString & name) signal
Lrc download state is finished.
Referenced by downloadQueryResult().
void MusicLrcSearchTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 89 of file musiclrcsearchtablewidget.cpp.
References MusicQueryTableWidget::removeItems().
Referenced by startToSearchByValue(), and ~MusicLrcSearchTableWidget().
void MusicLrcSearchTableWidget::resolvedSuccess () signal
Lrc search state is finished.
Referenced by startToSearchByValue().
void MusicLrcSearchTableWidget::startToSearchByValue (const QString & value) final override virtual
Start to search query by value.
Implements MusicQueryTableWidget.
Definition at line 25 of file musiclrcsearchtablewidget.cpp.
References G_DOWNLOAD_QUERY_PTR, G_NETWORK_PTR, MusicAbstractQueryRequest::Lrc, MusicQueryTableWidget::m_networkRequest, removeItems(), resolvedSuccess(), MusicQueryTableWidget::setLoadingStatus(), MusicQueryTableWidget::setQueryInput(), MusicAbstractQueryRequest::setQueryType(), and MusicAbstractQueryRequest::startToSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcsearchtablewidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcsearchtablewidget.cpp