TTKMusicplayer: MusicLocalSongSearchEdit Class Reference
MusicLocalSongSearchEdit Class Reference
The class of the local search line edit widget.
#include <musiclocalsongsearchedit.h>
Signals
void enterFinished (const QString &text)
Public Member Functions
MusicLocalSongSearchEdit (QWidget *parent=nullptr)
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void keyPressEvent (QKeyEvent *event) override
virtual void keyReleaseEvent (QKeyEvent *event) override
Detailed Description
The class of the local search line edit widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musiclocalsongsearchedit.h.
Constructor & Destructor Documentation
MusicLocalSongSearchEdit::MusicLocalSongSearchEdit (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musiclocalsongsearchedit.cpp.
References MusicUIObject::MQSSLineEditStyle03.
Member Function Documentation
void MusicLocalSongSearchEdit::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 13 of file musiclocalsongsearchedit.cpp.
References MusicUtils::Widget::adjustMenuPosition(), and MusicUIObject::MQSSMenuStyle02.
void MusicLocalSongSearchEdit::enterFinished (const QString & text) signal
User input the enter key emit.
Referenced by keyReleaseEvent().
void MusicLocalSongSearchEdit::keyPressEvent (QKeyEvent * event) override protected virtual
Definition at line 37 of file musiclocalsongsearchedit.cpp.
void MusicLocalSongSearchEdit::keyReleaseEvent (QKeyEvent * event) override protected virtual
Definition at line 42 of file musiclocalsongsearchedit.cpp.
References enterFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchedit.h
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchedit.cpp