TTKMusicplayer: MusicSongListSharingWidget Class Reference
MusicSongListSharingWidget Class Reference
The class of the song list share widget.
#include <musicsonglistsharingwidget.h>
Public Slots
virtual int exec ()
void switchToDiffWidget (int index)
void writeMainCopyButtonClicked ()
void readMainButtonClicked ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicSongListSharingWidget (QWidget *parent=0)
virtual ~MusicSongListSharingWidget ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Member Functions
void createWriteKey ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicSongListSharingWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the song list share widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicsonglistsharingwidget.h.
Constructor & Destructor Documentation
MusicSongListSharingWidget::MusicSongListSharingWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 10 of file musicsonglistsharingwidget.cpp.
References createWriteKey(), m_ui, MusicUIObject::MBackgroundStyle01, MusicUIObject::MColorStyle03, MusicUIObject::MFontStyle01, MusicUIObject::MFontStyle02, MusicUIObject::MFontStyle05, MusicUIObject::MPushButtonStyle04, MusicUIObject::MToolButtonStyle04, readMainButtonClicked(), switchToDiffWidget(), and writeMainCopyButtonClicked().
MusicSongListSharingWidget::~MusicSongListSharingWidget () virtual
Definition at line 53 of file musicsonglistsharingwidget.cpp.
References m_ui.
Member Function Documentation
void MusicSongListSharingWidget::createWriteKey () protected
Create write key.
Definition at line 91 of file musicsonglistsharingwidget.cpp.
References MusicLicenseCore::getCharacteristicStringNormal(), key, and m_ui.
Referenced by MusicSongListSharingWidget().
int MusicSongListSharingWidget::exec () virtual slot
Override exec function.
Definition at line 63 of file musicsonglistsharingwidget.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicSongsToolBoxTopWidget::showShareListDialog().
QString MusicSongListSharingWidget::getClassName () static
Get class object name.
Definition at line 58 of file musicsonglistsharingwidget.cpp.
void MusicSongListSharingWidget::readMainButtonClicked () slot
Read button clicked.
Definition at line 86 of file musicsonglistsharingwidget.cpp.
Referenced by MusicSongListSharingWidget().
void MusicSongListSharingWidget::switchToDiffWidget (int index) slot
Switch to diff widget.
Definition at line 69 of file musicsonglistsharingwidget.cpp.
References m_ui.
Referenced by MusicSongListSharingWidget().
void MusicSongListSharingWidget::writeMainCopyButtonClicked () slot
Write copy button clicked.
Definition at line 74 of file musicsonglistsharingwidget.cpp.
References m_ui, MusicToastLabel::popup(), MusicToastLabel::setFontMargin(), MusicToastLabel::setFontSize(), and MusicToastLabel::setText().
Referenced by MusicSongListSharingWidget().
Member Data Documentation
Ui::MusicSongListSharingWidget* MusicSongListSharingWidget::m_ui protected
Definition at line 71 of file musicsonglistsharingwidget.h.
Referenced by createWriteKey(), exec(), MusicSongListSharingWidget(), switchToDiffWidget(), writeMainCopyButtonClicked(), and ~MusicSongListSharingWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsonglistsharingwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsonglistsharingwidget.cpp