TTKMusicPlayer: TTKEventLoop Class Reference
TTKEventLoop Class Reference
The class of the ttk event loop.
#include <ttkeventloop.h>
Public Slots
void quit ()
void exit ()
Public Member Functions
TTKEventLoop (QObject *parent=nullptr)
~TTKEventLoop ()
void setTimeout (int msec)
int exec (ProcessEventsFlags flags=AllEvents)
Private Attributes
QTimer m_timer
Detailed Description
The class of the ttk event loop.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttkeventloop.h.
Constructor & Destructor Documentation
TTKEventLoop::TTKEventLoop (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file ttkeventloop.cpp.
References m_timer, quit(), and TTK_DN_S2MS.
TTKEventLoop::~TTKEventLoop ()
Object destructor.
Definition at line 10 of file ttkeventloop.cpp.
References quit().
Member Function Documentation
int TTKEventLoop::exec (ProcessEventsFlags flags = AllEvents)
Event loop start.
Definition at line 20 of file ttkeventloop.cpp.
References m_timer.
Referenced by MusicReplayGainWidget::addFileButtonClicked(), MusicReplayGainWidget::addFilesButtonClicked(), MusicReplayGainWidget::applyButtonClicked(), MusicSongSharingWidget::confirmButtonClicked(), MusicIdentifySongWidget::createDetectedSuccessedWidget(), MusicIdentifySongWidget::detectedTimeOut(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicDownloadMetaDataRequest::downLoadFinished(), TTK::fetchFileSizeByUrl(), MusicAbstractIdentifyRequest::queryCloudKey(), MusicCloudManagerTableWidget::queryCloudKey(), MusicDeviceInfoModule::removableDrive(), MusicCommentsWidget::setCurrentSongName(), MusicWYCoverSourceRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), MusicWYSongCommentsRequest::startToSearch(), TTK::syncNetworkQueryForGet(), TTK::syncNetworkQueryForPatch(), TTK::syncNetworkQueryForPost(), and TTK::syncNetworkQueryForPut().
void TTKEventLoop::exit () slot
Event loop exit.
Definition at line 32 of file ttkeventloop.cpp.
References m_timer.
void TTKEventLoop::quit () slot
Event loop quit.
Definition at line 26 of file ttkeventloop.cpp.
References m_timer.
Referenced by TTKEventLoop(), and ~TTKEventLoop().
void TTKEventLoop::setTimeout (int msec)
Set timeout msec time.
Definition at line 15 of file ttkeventloop.cpp.
References m_timer.
Member Data Documentation
QTimer TTKEventLoop::m_timer private
Definition at line 63 of file ttkeventloop.h.
Referenced by exec(), exit(), quit(), setTimeout(), and TTKEventLoop().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkeventloop.h
TTKCommon/TTKLibrary/ttkeventloop.cpp