TTKMusicplayer: MusicVideoPlayWidget Class Reference
MusicVideoPlayWidget Class Reference
The class of the video play widget.
#include <musicvideoplaywidget.h>
Public Slots
void switchToSearchTable ()
void switchToPlayView ()
void searchButtonClicked ()
void videoResearchButtonSearched (const QString &name)
void videoResearchButtonSearched (const QVariant &data)
void startSearchSingleQuery (const QString &name)
void mediaUrlChanged (const QString &url)
void mediaUrlPathChanged (const MusicVideoItem &item)
void popupButtonClicked ()
void fullscreenButtonClicked ()
void downloadButtonClicked ()
void shareButtonClicked ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void popupButtonClicked (bool popup)
void fullscreenButtonClicked (bool popup)
Public Member Functions
MusicVideoPlayWidget (QWidget *parent=nullptr)
~MusicVideoPlayWidget ()
void popupMode (bool popup)
bool isPopupMode () const
void resizeWindow ()
void resizeWindow (bool resize)
void resizeWindow (int width, int height)
QString getSearchText () const
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
void setTitleText (const QString &text)
void start (int topst, int topend, int ctrlst, int ctrlend)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
QTimer * m_leaverTimer
QParallelAnimationGroup * m_leaverAnimation
QWidget * m_topWidget
QLabel * m_textLabel
QToolButton * m_backButton
QPushButton * m_searchButton
QPushButton * m_closeButton
QStackedWidget * m_stackedWidget
MusicVideoItem m_videoItem
MusicVideoView * m_videoView
MusicVideoSearchTableWidget * m_videoTable
MusicLocalSongSearchEdit * m_searchEdit
MusicVideoFloatWidget * m_videoFloatWidget
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Private Slots
void leaveTimeout ()
Detailed Description
The class of the video play widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicvideoplaywidget.h.
Constructor & Destructor Documentation
MusicVideoPlayWidget::MusicVideoPlayWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 18 of file musicvideoplaywidget.cpp.
References MusicVideoView::controlBarWidget(), downloadButtonClicked(), fullscreenButtonClicked(), leaveTimeout(), m_backButton, m_closeButton, m_leaverAnimation, m_leaverTimer, m_searchButton, m_searchEdit, m_stackedWidget, m_textLabel, m_topWidget, m_videoFloatWidget, m_videoTable, m_videoView, mediaUrlPathChanged(), MusicUIObject::MQSSBackgroundStyle02, MusicUIObject::MQSSBackgroundStyle06, MusicUIObject::MQSSBackgroundStyle11, MusicUIObject::MQSSBorderStyle01, MusicUIObject::MQSSBtnPClose, MusicUIObject::MQSSColorStyle01, MusicUIObject::MQSSColorStyle09, MT_S2MS, popupButtonClicked(), searchButtonClicked(), shareButtonClicked(), switchToSearchTable(), VIDEO_WINDOW_INDEX_0, and videoResearchButtonSearched().
MusicVideoPlayWidget::~MusicVideoPlayWidget ()
Definition at line 127 of file musicvideoplaywidget.cpp.
References m_backButton, m_closeButton, m_leaverAnimation, m_leaverTimer, m_searchButton, m_searchEdit, m_stackedWidget, m_textLabel, and m_videoView.
Member Function Documentation
void MusicVideoPlayWidget::downloadButtonClicked () slot
Download button clicked.
Definition at line 334 of file musicvideoplaywidget.cpp.
References MusicVideoSearchTableWidget::downloadLocalFromControl(), and m_videoTable.
Referenced by MusicVideoPlayWidget().
void MusicVideoPlayWidget::enterEvent (QEvent * event) override protected virtual
Definition at line 380 of file musicvideoplaywidget.cpp.
void MusicVideoPlayWidget::fullscreenButtonClicked (bool popup) signal
Fullscreen button clicked.
void MusicVideoPlayWidget::fullscreenButtonClicked () slot
Fullscreen button clicked.
Definition at line 322 of file musicvideoplaywidget.cpp.
References MusicVideoFloatWidget::fullscreenMode(), MusicVideoFloatWidget::isFullscreenMode(), MusicVideoFloatWidget::isPopupMode(), and m_videoFloatWidget.
Referenced by MusicVideoPlayWidget().
QString MusicVideoPlayWidget::getSearchText () const
Get search text in search line.
Definition at line 222 of file musicvideoplaywidget.cpp.
References m_searchEdit.
Referenced by searchButtonClicked().
bool MusicVideoPlayWidget::isPopupMode () const
Get the window is popup or not.
Definition at line 165 of file musicvideoplaywidget.cpp.
References MusicAbstractMoveWidget::m_moveOption.
Referenced by MusicRightAreaWidget::musicMovieSearchRadioFound(), MusicRightAreaWidget::musicVideoButtonSearched(), resizeWindow(), and MusicRightAreaWidget::resizeWindow().
void MusicVideoPlayWidget::leaveEvent (QEvent * event) override protected virtual
Definition at line 394 of file musicvideoplaywidget.cpp.
References m_leaverTimer.
void MusicVideoPlayWidget::leaveTimeout () private slot
Leave Timeout.
Definition at line 358 of file musicvideoplaywidget.cpp.
References MusicVideoView::controlBarWidget(), m_stackedWidget, m_topWidget, m_videoView, and start().
Referenced by MusicVideoPlayWidget().
void MusicVideoPlayWidget::mediaUrlChanged (const QString & url) slot
Set current media url by selected quality.
stop current media play while mv starts.
Definition at line 291 of file musicvideoplaywidget.cpp.
References MusicApplication::instance(), MusicApplication::isPlaying(), m_videoView, MusicApplication::musicStatePlay(), MusicVideoView::play(), MusicVideoView::setMedia(), and switchToPlayView().
Referenced by mediaUrlPathChanged().
void MusicVideoPlayWidget::mediaUrlPathChanged (const MusicVideoItem & item) slot
Set current media name and url to play.
Definition at line 310 of file musicvideoplaywidget.cpp.
References MusicVideoItem::m_name, MusicVideoItem::m_url, m_videoItem, mediaUrlChanged(), and setTitleText().
Referenced by MusicVideoPlayWidget(), and videoResearchButtonSearched().
void MusicVideoPlayWidget::popupButtonClicked (bool popup) signal
Popup button state changed.
void MusicVideoPlayWidget::popupButtonClicked () slot
Popup button clicked.
Definition at line 317 of file musicvideoplaywidget.cpp.
References MusicVideoFloatWidget::isPopupMode(), and m_videoFloatWidget.
Referenced by MusicVideoPlayWidget().
void MusicVideoPlayWidget::popupMode (bool popup)
Set the window is popup or not.
Definition at line 140 of file musicvideoplaywidget.cpp.
References MusicAbstractMoveWidget::blockMoveOption(), MusicVideoFloatWidget::fullscreenMode(), G_SETTING_PTR, m_videoFloatWidget, MusicVideoFloatWidget::popupMode(), resizeWindow(), MusicSettingManager::ScreenSize, WINDOW_HEIGHT, and WINDOW_WIDTH.
Referenced by MusicRightAreaWidget::functionClicked(), and MusicRightAreaWidget::musicVideoSetPopup().
void MusicVideoPlayWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Definition at line 368 of file musicvideoplaywidget.cpp.
References m_leaverAnimation, m_leaverTimer, and resizeWindow().
void MusicVideoPlayWidget::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 170 of file musicvideoplaywidget.cpp.
References G_SETTING_PTR, isPopupMode(), MusicSettingManager::WidgetSize, WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by MusicRightAreaWidget::musicVideoFullscreen(), popupMode(), resizeEvent(), resizeWindow(), and MusicRightAreaWidget::resizeWindow().
void MusicVideoPlayWidget::resizeWindow (bool resize)
Resize widget size or not.
Definition at line 186 of file musicvideoplaywidget.cpp.
References resizeWindow(), TTKDesktopWrapper::screenGeometry(), WINDOW_HEIGHT, and WINDOW_WIDTH.
void MusicVideoPlayWidget::resizeWindow (int width, int height)
Resize widget size or not.
Definition at line 214 of file musicvideoplaywidget.cpp.
References m_topWidget, m_videoFloatWidget, m_videoTable, m_videoView, MusicVideoFloatWidget::resizeWindow(), MusicVideoSearchTableWidget::resizeWindow(), and MusicVideoView::resizeWindow().
void MusicVideoPlayWidget::searchButtonClicked () slot
Search button clicked.
Definition at line 256 of file musicvideoplaywidget.cpp.
References getSearchText(), and videoResearchButtonSearched().
Referenced by MusicVideoPlayWidget().
void MusicVideoPlayWidget::setTitleText (const QString & text) protected
Set current title text(song name).
Definition at line 400 of file musicvideoplaywidget.cpp.
References MusicUtils::Widget::elidedText(), and m_textLabel.
Referenced by mediaUrlPathChanged(), and switchToPlayView().
void MusicVideoPlayWidget::shareButtonClicked () slot
Share button clicked.
Definition at line 339 of file musicvideoplaywidget.cpp.
References MusicSongSharingWidget::exec(), MusicVideoItem::m_id, MusicVideoItem::m_name, MusicVideoItem::m_server, m_videoItem, MusicSongSharingWidget::Movie, name, and MusicSongSharingWidget::setData().
Referenced by MusicVideoPlayWidget().
void MusicVideoPlayWidget::start (int topst, int topend, int ctrlst, int ctrlend) protected
Start to turn on animation.
Definition at line 405 of file musicvideoplaywidget.cpp.
References m_leaverAnimation, and TTKStatic_cast.
Referenced by leaveTimeout().
void MusicVideoPlayWidget::startSearchSingleQuery (const QString & name) slot
Video search query by given id.
Definition at line 285 of file musicvideoplaywidget.cpp.
References m_videoTable, MusicVideoSearchTableWidget::startSearchSingleQuery(), and switchToSearchTable().
Referenced by MusicRightAreaWidget::musicVideoButtonSearched().
void MusicVideoPlayWidget::switchToPlayView () slot
Switch to play view.
Definition at line 245 of file musicvideoplaywidget.cpp.
References m_backButton, MusicVideoItem::m_name, m_searchButton, m_searchEdit, m_stackedWidget, m_videoItem, setTitleText(), and VIDEO_WINDOW_INDEX_0.
Referenced by mediaUrlChanged(), and switchToSearchTable().
void MusicVideoPlayWidget::switchToSearchTable () slot
Switch to search table.
Definition at line 227 of file musicvideoplaywidget.cpp.
References m_backButton, m_searchButton, m_searchEdit, m_stackedWidget, m_textLabel, m_topWidget, MusicUIObject::MQSSBtnBackBack, switchToPlayView(), TTKStatic_cast, and VIDEO_WINDOW_INDEX_1.
Referenced by MusicVideoPlayWidget(), startSearchSingleQuery(), and videoResearchButtonSearched().
void MusicVideoPlayWidget::videoResearchButtonSearched (const QString & name) slot
Video research button searched by name.
Definition at line 261 of file musicvideoplaywidget.cpp.
References m_searchEdit, m_videoTable, MusicVideoSearchTableWidget::startSearchQuery(), and switchToSearchTable().
Referenced by MusicRightAreaWidget::musicMovieSearchRadioFound(), MusicRightAreaWidget::musicVideoButtonSearched(), MusicVideoPlayWidget(), and searchButtonClicked().
void MusicVideoPlayWidget::videoResearchButtonSearched (const QVariant & data) slot
Video research button searched by name.
Definition at line 268 of file musicvideoplaywidget.cpp.
References MusicVideoItem::m_id, MusicVideoItem::m_name, MusicVideoItem::m_server, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicVideoItem::m_url, MusicObject::MusicSongAttribute::m_url, m_videoTable, mediaUrlPathChanged(), MUSIC_MOVIE_RADIO, and MusicVideoSearchTableWidget::startSearchSingleQuery().
Member Data Documentation
QToolButton* MusicVideoPlayWidget::m_backButton protected
Definition at line 165 of file musicvideoplaywidget.h.
Referenced by MusicVideoPlayWidget(), switchToPlayView(), switchToSearchTable(), and ~MusicVideoPlayWidget().
QPushButton * MusicVideoPlayWidget::m_closeButton protected
Definition at line 166 of file musicvideoplaywidget.h.
Referenced by MusicVideoPlayWidget(), and ~MusicVideoPlayWidget().
QParallelAnimationGroup* MusicVideoPlayWidget::m_leaverAnimation protected
Definition at line 161 of file musicvideoplaywidget.h.
Referenced by MusicVideoPlayWidget(), resizeEvent(), start(), and ~MusicVideoPlayWidget().
QTimer* MusicVideoPlayWidget::m_leaverTimer protected
Definition at line 160 of file musicvideoplaywidget.h.
Referenced by leaveEvent(), MusicVideoPlayWidget(), resizeEvent(), and ~MusicVideoPlayWidget().
QPushButton* MusicVideoPlayWidget::m_searchButton protected
Definition at line 166 of file musicvideoplaywidget.h.
Referenced by MusicVideoPlayWidget(), switchToPlayView(), switchToSearchTable(), and ~MusicVideoPlayWidget().
MusicLocalSongSearchEdit* MusicVideoPlayWidget::m_searchEdit protected
Definition at line 171 of file musicvideoplaywidget.h.
Referenced by getSearchText(), MusicVideoPlayWidget(), switchToPlayView(), switchToSearchTable(), videoResearchButtonSearched(), and ~MusicVideoPlayWidget().
QStackedWidget* MusicVideoPlayWidget::m_stackedWidget protected
Definition at line 167 of file musicvideoplaywidget.h.
Referenced by leaveTimeout(), MusicVideoPlayWidget(), switchToPlayView(), switchToSearchTable(), and ~MusicVideoPlayWidget().
QLabel* MusicVideoPlayWidget::m_textLabel protected
Definition at line 164 of file musicvideoplaywidget.h.
Referenced by MusicVideoPlayWidget(), setTitleText(), switchToSearchTable(), and ~MusicVideoPlayWidget().
QWidget* MusicVideoPlayWidget::m_topWidget protected
Definition at line 163 of file musicvideoplaywidget.h.
Referenced by leaveTimeout(), MusicVideoPlayWidget(), resizeWindow(), and switchToSearchTable().
MusicVideoFloatWidget* MusicVideoPlayWidget::m_videoFloatWidget protected
Definition at line 172 of file musicvideoplaywidget.h.
Referenced by fullscreenButtonClicked(), MusicVideoPlayWidget(), popupButtonClicked(), popupMode(), and resizeWindow().
MusicVideoItem MusicVideoPlayWidget::m_videoItem protected
Definition at line 168 of file musicvideoplaywidget.h.
Referenced by mediaUrlPathChanged(), shareButtonClicked(), and switchToPlayView().
MusicVideoSearchTableWidget* MusicVideoPlayWidget::m_videoTable protected
Definition at line 170 of file musicvideoplaywidget.h.
Referenced by downloadButtonClicked(), MusicVideoPlayWidget(), resizeWindow(), startSearchSingleQuery(), and videoResearchButtonSearched().
MusicVideoView* MusicVideoPlayWidget::m_videoView protected
Definition at line 169 of file musicvideoplaywidget.h.
Referenced by leaveTimeout(), mediaUrlChanged(), MusicVideoPlayWidget(), resizeWindow(), and ~MusicVideoPlayWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideoplaywidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideoplaywidget.cpp