TTKMusicplayer: MusicPLSConfigManager Class Reference
MusicPLSConfigManager Class Reference
The class of the pls playlist Config Manager.
#include <musicplsconfigmanager.h>
Public Member Functions
MusicPLSConfigManager ()
bool readConfig (const QString &name)
virtual bool readPlaylistData (MusicSongItems &items) override
virtual bool writePlaylistData (const MusicSongItems &items, const QString &path) override
Public Member Functions inherited from MusicPlaylistInterface
MusicPlaylistInterface ()
virtual ~MusicPlaylistInterface ()
Private Attributes
QFile m_file
Detailed Description
The class of the pls playlist Config Manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicplsconfigmanager.h.
Constructor & Destructor Documentation
MusicPLSConfigManager::MusicPLSConfigManager () explicit
Object contsructor.
Definition at line 4 of file musicplsconfigmanager.cpp.
Member Function Documentation
bool MusicPLSConfigManager::readConfig (const QString & name)
Read datas from xml file by given name.
Definition at line 10 of file musicplsconfigmanager.cpp.
References m_file.
Referenced by MusicPlaylistManager::readPLSList().
bool MusicPLSConfigManager::readPlaylistData (MusicSongItems & items) override virtual
Read datas from config file.
Implements MusicPlaylistInterface.
Definition at line 16 of file musicplsconfigmanager.cpp.
References m_file, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicTime::msecTime2LabelJustified(), and TTK_LOGGER_ERROR.
Referenced by MusicPlaylistManager::readPLSList().
bool MusicPLSConfigManager::writePlaylistData (const MusicSongItems & items, const QString & path) override virtual
Write datas into config file.
Implements MusicPlaylistInterface.
Definition at line 78 of file musicplsconfigmanager.cpp.
References MusicSong::getMusicName(), MusicSong::getMusicPath(), MusicSong::getMusicPlayTime(), m_file, and MusicSongItem::m_songs.
Referenced by MusicPlaylistManager::writePLSList().
Member Data Documentation
QFile MusicPLSConfigManager::m_file private
Definition at line 51 of file musicplsconfigmanager.h.
Referenced by readConfig(), readPlaylistData(), and writePlaylistData().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musicplsconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musicplsconfigmanager.cpp