TTKMusicplayer: MusicLocalSongSearchDialog Class Reference
MusicLocalSongSearchDialog Class Reference
The class of the local song search widget.
#include <musiclocalsongsearchdialog.h>
Public Slots
bool close ()
Public Member Functions
MusicLocalSongSearchDialog (QWidget *parent=nullptr)
~MusicLocalSongSearchDialog ()
QString getText () const
void clear () const
virtual void setVisible (bool visible) override
Private Attributes
MusicLocalSongSearchEdit * m_searchLine
Detailed Description
The class of the local song search widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musiclocalsongsearchdialog.h.
Constructor & Destructor Documentation
MusicLocalSongSearchDialog::MusicLocalSongSearchDialog (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musiclocalsongsearchdialog.cpp.
References close(), LEFT_SIDE_WIDTH_MIN, m_searchLine, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSBorderStyle02, and MusicUIObject::MQSSTinyBtnClose.
MusicLocalSongSearchDialog::~MusicLocalSongSearchDialog ()
Definition at line 47 of file musiclocalsongsearchdialog.cpp.
References m_searchLine.
Member Function Documentation
void MusicLocalSongSearchDialog::clear () const
Clear the search text.
Definition at line 63 of file musiclocalsongsearchdialog.cpp.
References m_searchLine.
Referenced by close().
bool MusicLocalSongSearchDialog::close () slot
Override the close function.
Definition at line 52 of file musiclocalsongsearchdialog.cpp.
References clear().
Referenced by MusicSongsSummariziedWidget::closeSearchWidget(), and MusicLocalSongSearchDialog().
QString MusicLocalSongSearchDialog::getText () const
Get the search text that the user searched.
Definition at line 58 of file musiclocalsongsearchdialog.cpp.
References m_searchLine.
Referenced by MusicSongsSummariziedWidget::musicSearchResultChanged().
void MusicLocalSongSearchDialog::setVisible (bool visible) override virtual
Set line edit input focus.
Definition at line 68 of file musiclocalsongsearchdialog.cpp.
References m_searchLine.
Referenced by MusicSongsSummariziedWidget::showSearchWidget().
Member Data Documentation
MusicLocalSongSearchEdit* MusicLocalSongSearchDialog::m_searchLine private
Definition at line 61 of file musiclocalsongsearchdialog.h.
Referenced by clear(), getText(), MusicLocalSongSearchDialog(), setVisible(), and ~MusicLocalSongSearchDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchdialog.h
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchdialog.cpp