TTKMusicPlayer: MusicMoreFunctionsPopWidget Class Reference
MusicMoreFunctionsPopWidget Class Reference
The class of the more functions popup widget.
#include <musicmorefunctionspopwidget.h>
Public Member Functions
MusicMoreFunctionsPopWidget (QWidget *parent=nullptr)
void setCurrentSongName (const QString &name)
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Private Slots
void functionClicked (QAction *index)
Private Member Functions
void initialize ()
Private Attributes
QString m_currentSongName
Additional Inherited Members
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the more functions popup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicmorefunctionspopwidget.h.
Constructor & Destructor Documentation
MusicMoreFunctionsPopWidget::MusicMoreFunctionsPopWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file musicmorefunctionspopwidget.cpp.
References initialize().
Member Function Documentation
void MusicMoreFunctionsPopWidget::functionClicked (QAction * index) private slot
Function button clicked.
Definition at line 15 of file musicmorefunctionspopwidget.cpp.
References MusicRightAreaWidget::AdvancedSearchWidget, MusicRightAreaWidget::functionClicked(), MusicRightAreaWidget::instance(), m_currentSongName, MusicRightAreaWidget::showAlbumFound(), MusicRightAreaWidget::showArtistFound(), MusicRightAreaWidget::showCommentsFound(), MusicRightAreaWidget::showSimilarFound(), and MusicRightAreaWidget::SongDailyWidget.
Referenced by initialize().
void MusicMoreFunctionsPopWidget::initialize () private
Create all widget in layout.
Definition at line 29 of file musicmorefunctionspopwidget.cpp.
References functionClicked(), MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicMoreFunctionsPopWidget().
void MusicMoreFunctionsPopWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 10 of file musicmorefunctionspopwidget.cpp.
References m_currentSongName, and name.
Member Data Documentation
QString MusicMoreFunctionsPopWidget::m_currentSongName private
Definition at line 54 of file musicmorefunctionspopwidget.h.
Referenced by functionClicked(), and setCurrentSongName().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicmorefunctionspopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicmorefunctionspopwidget.cpp