TTKMusicplayer: MusicDownloadBackgroundThunderThread Class Reference
MusicDownloadBackgroundThunderThread Class Reference
The class of download thunder skin background.
#include <musicdownloadbackgroundremotethread.h>
Public Slots
virtual void downLoadDataFinished (const QByteArray &bytes) override
Public Slots inherited from MusicDownloadBackgroundRemoteThread
virtual void downLoadDataFinished (const QByteArray &bytes)=0
Public Member Functions
MusicDownloadBackgroundThunderThread (QObject *parent=nullptr)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownloadBackgroundRemoteThread
MusicDownloadBackgroundRemoteThread (QObject *parent=nullptr)
Additional Inherited Members
Signals inherited from MusicDownloadBackgroundRemoteThread
void downLoadDataChanged (const MusicSkinRemoteGroups &data)
Detailed Description
The class of download thunder skin background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 122 of file musicdownloadbackgroundremotethread.h.
Constructor & Destructor Documentation
MusicDownloadBackgroundThunderThread::MusicDownloadBackgroundThunderThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 73 of file musicdownloadbackgroundremotethread.cpp.
Member Function Documentation
void MusicDownloadBackgroundThunderThread::downLoadDataFinished (const QByteArray & bytes) override virtual slot
Download data from net finished.
Definition at line 86 of file musicdownloadbackgroundremotethread.cpp.
References MusicDownloadBackgroundRemoteThread::downLoadDataChanged(), MusicAbstractXml::fromByteArray(), and MusicSkinThunderConfigManager::readSkinRemoteData().
Referenced by startToDownload().
void MusicDownloadBackgroundThunderThread::startToDownload () override virtual
Start to download data from net.
Implements MusicDownloadBackgroundRemoteThread.
Definition at line 79 of file musicdownloadbackgroundremotethread.cpp.
References downLoadDataFinished(), MusicUtils::Algorithm::mdII(), MusicDownloadSourceThread::startToDownload(), and THUD_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadbackgroundremotethread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadbackgroundremotethread.cpp