TTKMusicplayer: MusicRegeditManager Class Reference
MusicRegeditManager Class Reference
The class of the windows regedit manager.
#include <musicregeditmanager.h>
Public Member Functions
bool isFileAssociate ()
void setMusicRegeditAssociateFileIcon ()
void setDesktopWallAutoStart (bool state)
void getDesktopWallControlPanel (QString &originPath, int &originType)
void setDesktopWallControlPanel (const QString &originPath, int originType)
void setLeftWinEnable ()
int getLocalIEVersion () const
void setFileLink (const QString &src, const QString &des, const QString &ico, const QString &args, const QString &description)
Protected Member Functions
bool currentNodeHasExist (const QString &key)
void createMusicRegedit (const QString &key)
Detailed Description
The class of the windows regedit manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicregeditmanager.h.
Member Function Documentation
void MusicRegeditManager::createMusicRegedit (const QString & key) protected
Create music regedit item.
Definition at line 180 of file musicregeditmanager.cpp.
References APPDOT, key, MUSIC_OUTER_LIST, and MUSIC_OUTER_OPEN.
Referenced by setMusicRegeditAssociateFileIcon().
bool MusicRegeditManager::currentNodeHasExist (const QString & key) protected
Check current regedit item has exist.
Definition at line 162 of file musicregeditmanager.cpp.
References APPDOT, and key.
Referenced by isFileAssociate(), and setMusicRegeditAssociateFileIcon().
void MusicRegeditManager::getDesktopWallControlPanel (QString & originPath, int & originType)
Get desktop wall control panel.
Definition at line 43 of file musicregeditmanager.cpp.
int MusicRegeditManager::getLocalIEVersion () const
Get local IE version.
Definition at line 71 of file musicregeditmanager.cpp.
Referenced by MusicApplicationObject::musicToolSetsParameter().
bool MusicRegeditManager::isFileAssociate ()
Check current is file associate.
Definition at line 16 of file musicregeditmanager.cpp.
References currentNodeHasExist(), and MP3_FILE_PREFIX.
Referenced by MusicSettingWidget::initControllerParameter().
void MusicRegeditManager::setDesktopWallAutoStart (bool state)
Set desktop wall auto start.
Definition at line 34 of file musicregeditmanager.cpp.
void MusicRegeditManager::setDesktopWallControlPanel (const QString & originPath, int originType)
Set desktop wall control panel.
Definition at line 50 of file musicregeditmanager.cpp.
void MusicRegeditManager::setFileLink (const QString & src, const QString & des, const QString & ico, const QString & args, const QString & description)
Set file link.
Definition at line 101 of file musicregeditmanager.cpp.
Referenced by MusicWebMusicRadioWidget::sendToDesktopLink().
void MusicRegeditManager::setLeftWinEnable ()
Set left win key enable.
Definition at line 58 of file musicregeditmanager.cpp.
Referenced by MusicRightAreaWidget::musicContainerForWallpaperClicked(), and MusicRightAreaWidget::musicVideoSetPopup().
void MusicRegeditManager::setMusicRegeditAssociateFileIcon ()
Set music regedit associate file icon.
Definition at line 21 of file musicregeditmanager.cpp.
References createMusicRegedit(), currentNodeHasExist(), and MusicFormats::supportFormatsString().
Referenced by MusicApplicationObject::getParameterSetting().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicregeditmanager.h
TTKModule/TTKCore/musicCoreKits/musicregeditmanager.cpp