TTKMusicplayer: MusicSongsToolBoxWidget Class Reference
MusicSongsToolBoxWidget Class Reference
The class of the tool box widget.
#include <musicsongstoolboxwidget.h>
Public Slots
void setCurrentIndex (int index)
void mousePressAt (int index)
void setTransparent (int alpha)
Public Member Functions
MusicSongsToolBoxWidget (QWidget *parent=0)
~MusicSongsToolBoxWidget ()
void addItem (QWidget *item, const QString &text)
void removeItem (QWidget *item)
void swapItem (int before, int after)
void setTitle (QWidget *item, const QString &text)
QString getTitle (QWidget *item) const
void setMusicSort (QWidget *item, MusicSort *sort)
void resizeScrollIndex (int index) const
int currentIndex () const
int count () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
int foundMappingIndex (int index)
Protected Attributes
int m_currentIndex
int m_itemIndexRaise
QVBoxLayout * m_layout
QScrollArea * m_scrollArea
QWidget * m_contentsWidget
QList< MusicToolBoxWidgetItem > m_itemList
Detailed Description
The class of the tool box widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 352 of file musicsongstoolboxwidget.h.
Constructor & Destructor Documentation
MusicSongsToolBoxWidget::MusicSongsToolBoxWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 510 of file musicsongstoolboxwidget.cpp.
References m_contentsWidget, m_currentIndex, m_itemIndexRaise, m_layout, m_scrollArea, MusicUIObject::MBackgroundStyle01, and setTransparent().
MusicSongsToolBoxWidget::~MusicSongsToolBoxWidget ()
Definition at line 544 of file musicsongstoolboxwidget.cpp.
References m_itemList, m_layout, and m_scrollArea.
Member Function Documentation
void MusicSongsToolBoxWidget::addItem (QWidget * item, const QString & text)
Add widget item.
Definition at line 559 of file musicsongstoolboxwidget.cpp.
References MusicSongsToolBoxWidgetItem::addItem(), count(), m_currentIndex, MusicToolBoxWidgetItem::m_itemIndex, m_itemIndexRaise, m_itemList, m_layout, MusicToolBoxWidgetItem::m_widgetItem, and MusicSongsToolBoxWidgetItem::setItemExpand().
Referenced by MusicSongsSummariziedWidget::createWidgetItem().
void MusicSongsToolBoxWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Reimplemented in MusicSongsSummariziedWidget.
Definition at line 724 of file musicsongstoolboxwidget.cpp.
Referenced by MusicSongsSummariziedWidget::contextMenuEvent().
int MusicSongsToolBoxWidget::count () const
Get item's count.
Definition at line 684 of file musicsongstoolboxwidget.cpp.
References m_itemList.
Referenced by addItem(), and swapItem().
int MusicSongsToolBoxWidget::currentIndex () const
Get current index.
Definition at line 679 of file musicsongstoolboxwidget.cpp.
References m_currentIndex.
Referenced by MusicApplication::getCurrentPlayList(), MusicApplication::musicListLovestContains(), MusicApplication::musicPlayIndex(), MusicApplication::musicPlayIndexClicked(), and MusicApplication::setMusicPlayIndex().
int MusicSongsToolBoxWidget::foundMappingIndex (int index) protected
Found mapped index in container.
Definition at line 729 of file musicsongstoolboxwidget.cpp.
References m_itemList.
Referenced by MusicSongsSummariziedWidget::addNewDir(), MusicSongsSummariziedWidget::addNewFiles(), MusicSongsSummariziedWidget::changRowItemName(), MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItemAll(), mousePressAt(), MusicSongsSummariziedWidget::musicListSongSortBy(), MusicSongsSummariziedWidget::resetToolIndex(), and MusicSongsSummariziedWidget::swapDragItemIndex().
QString MusicSongsToolBoxWidget::getClassName () static
Get class object name.
Definition at line 554 of file musicsongstoolboxwidget.cpp.
QString MusicSongsToolBoxWidget::getTitle (QWidget * item) const
Get title text.
Definition at line 638 of file musicsongstoolboxwidget.cpp.
References MusicSongsToolBoxWidgetItem::count(), MusicSongsToolBoxWidgetItem::getTitle(), MusicSongsToolBoxWidgetItem::item(), and m_itemList.
void MusicSongsToolBoxWidget::mousePressAt (int index) slot
Current top widget is pressed.
Definition at line 699 of file musicsongstoolboxwidget.cpp.
References foundMappingIndex(), m_currentIndex, and m_itemList.
Referenced by MusicSongsSummariziedWidget::MusicSongsSummariziedWidget().
void MusicSongsToolBoxWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Definition at line 719 of file musicsongstoolboxwidget.cpp.
void MusicSongsToolBoxWidget::removeItem (QWidget * item)
Remove widget item.
Definition at line 589 of file musicsongstoolboxwidget.cpp.
References MusicSongsToolBoxWidgetItem::count(), MusicSongsToolBoxWidgetItem::item(), m_currentIndex, m_itemList, m_layout, and MUSIC_NORMAL_LIST.
Referenced by MusicSongsSummariziedWidget::deleteRowItem(), and MusicSongsSummariziedWidget::deleteRowItems().
void MusicSongsToolBoxWidget::resizeScrollIndex (int index) const
Reset scroll index by given position.
Definition at line 670 of file musicsongstoolboxwidget.cpp.
References m_scrollArea.
Referenced by MusicSongsSummariziedWidget::playLocation().
void MusicSongsToolBoxWidget::setCurrentIndex (int index) slot
Set current index.
Definition at line 690 of file musicsongstoolboxwidget.cpp.
References m_currentIndex, and m_itemList.
Referenced by MusicSongsSummariziedWidget::addNetMusicSongToList(), MusicSongsSummariziedWidget::addSongToPlayList(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItems(), MusicSongsSummariziedWidget::importOtherMusicSongs(), MusicSongsSummariziedWidget::selectRow(), and MusicSongsSummariziedWidget::setCurrentIndex().
void MusicSongsToolBoxWidget::setMusicSort (QWidget * item, MusicSort * sort)
Set music sort.
Definition at line 654 of file musicsongstoolboxwidget.cpp.
References MusicSongsToolBoxWidgetItem::count(), MusicSongsToolBoxWidgetItem::item(), m_itemList, and MusicSongsToolBoxWidgetItem::setMusicSort().
Referenced by MusicSongsSummariziedWidget::createWidgetItem().
void MusicSongsToolBoxWidget::setTitle (QWidget * item, const QString & text)
Set title text.
Definition at line 622 of file musicsongstoolboxwidget.cpp.
References MusicSongsToolBoxWidgetItem::count(), MusicSongsToolBoxWidgetItem::item(), m_itemList, and MusicSongsToolBoxWidgetItem::setTitle().
Referenced by MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::setItemTitle(), and MusicSongsSummariziedWidget::setRecentMusicSongs().
void MusicSongsToolBoxWidget::setTransparent (int alpha) slot
Set background transparent.
Definition at line 709 of file musicsongstoolboxwidget.cpp.
References m_scrollArea, and MusicUIObject::MScrollBarStyle03.
Referenced by MusicSongsToolBoxWidget().
void MusicSongsToolBoxWidget::swapItem (int before, int after)
Swap widget item.
Definition at line 607 of file musicsongstoolboxwidget.cpp.
References count(), m_itemList, m_layout, and MusicToolBoxWidgetItem::m_widgetItem.
Referenced by MusicSongsSummariziedWidget::swapDragItemIndex().
Member Data Documentation
QWidget* MusicSongsToolBoxWidget::m_contentsWidget protected
Definition at line 436 of file musicsongstoolboxwidget.h.
Referenced by MusicSongsToolBoxWidget().
int MusicSongsToolBoxWidget::m_currentIndex protected
Definition at line 433 of file musicsongstoolboxwidget.h.
Referenced by addItem(), currentIndex(), MusicSongsSummariziedWidget::isCurrentIndexs(), mousePressAt(), MusicSongsSummariziedWidget::musicImportSongsOnlyDir(), MusicSongsSummariziedWidget::musicImportSongsOnlyFile(), MusicSongsSummariziedWidget::musicListSongSortBy(), MusicSongsSummariziedWidget::musicListSongToLovestListAt(), MusicSongsToolBoxWidget(), removeItem(), MusicSongsSummariziedWidget::searchFileListCache(), setCurrentIndex(), MusicSongsSummariziedWidget::setDeleteItemAt(), MusicSongsSummariziedWidget::setMusicIndexSwaped(), MusicSongsSummariziedWidget::sliderValueChanaged(), and MusicSongsSummariziedWidget::swapDragItemIndex().
int MusicSongsToolBoxWidget::m_itemIndexRaise protected
Definition at line 433 of file musicsongstoolboxwidget.h.
Referenced by addItem(), MusicSongsSummariziedWidget::appendMusicLists(), MusicSongsSummariziedWidget::createWidgetItem(), and MusicSongsToolBoxWidget().
QList<MusicToolBoxWidgetItem> MusicSongsToolBoxWidget::m_itemList protected
Definition at line 437 of file musicsongstoolboxwidget.h.
Referenced by addItem(), count(), MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItems(), foundMappingIndex(), getTitle(), mousePressAt(), removeItem(), setCurrentIndex(), setMusicSort(), setTitle(), swapItem(), and ~MusicSongsToolBoxWidget().
QVBoxLayout* MusicSongsToolBoxWidget::m_layout protected
Definition at line 434 of file musicsongstoolboxwidget.h.
Referenced by addItem(), MusicSongsToolBoxWidget(), removeItem(), swapItem(), and ~MusicSongsToolBoxWidget().
QScrollArea* MusicSongsToolBoxWidget::m_scrollArea protected
Definition at line 435 of file musicsongstoolboxwidget.h.
Referenced by MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::MusicSongsSummariziedWidget(), MusicSongsToolBoxWidget(), resizeScrollIndex(), setTransparent(), and ~MusicSongsToolBoxWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicsongstoolboxwidget.h
TTKModule/TTKWidget/musicToolsKits/musicsongstoolboxwidget.cpp