TTKMusicPlayer: MusicWYPlaylistCommentsRequest Class Reference
MusicWYPlaylistCommentsRequest Class Reference
The class of the wangyi query playlist comments download data from net.
#include <musicwycommentsrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYPlaylistCommentsRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value) overridefinal
virtual void startToPage (int offset) overridefinal
Public Member Functions inherited from MusicCommentsRequest
MusicCommentsRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicCommentsRequest
void createCommentItem (const MusicResultDataItem &comments)
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the wangyi query playlist comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 59 of file musicwycommentsrequest.h.
Constructor & Destructor Documentation
MusicWYPlaylistCommentsRequest::MusicWYPlaylistCommentsRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 94 of file musicwycommentsrequest.cpp.
References MusicPageQueryRequest::m_pageSize.
Member Function Documentation
void MusicWYPlaylistCommentsRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 125 of file musicwycommentsrequest.cpp.
References MusicCommentsRequest::createCommentItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultDataItem::m_coverUrl, MusicResultDataItem::m_description, MusicResultDataItem::m_nickName, MusicResultDataItem::m_playCount, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicResultDataItem::m_updateTime, QJson::Parser::parse(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToPage().
void MusicWYPlaylistCommentsRequest::startToPage (int offset) final override virtual
Start to search data from name and type bt page.
Reimplemented from MusicPageQueryRequest.
Definition at line 108 of file musicwycommentsrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageSize, MusicAbstractNetwork::m_rawData, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicWYInterface::makeTokenRequest(), TTK::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK_INFO_STREAM, WY_COMMENT_DATA_URL, and WY_COMMENT_PLAYLIST_URL.
Referenced by startToSearch().
void MusicWYPlaylistCommentsRequest::startToSearch (const QString & value) final override virtual
Start to search data by input data.
Implements MusicCommentsRequest.
Definition at line 100 of file musicwycommentsrequest.cpp.
References MusicAbstractNetwork::m_rawData, startToPage(), and TTK_INFO_STREAM.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwycommentsrequest.h
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwycommentsrequest.cpp