TTKMusicPlayer: TTKAbstractMoveWidget Class Reference
TTKAbstractMoveWidget Class Reference
The class of the ttk moving widget base.
#include <ttkabstractmovewidget.h>
Public Member Functions
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Attributes
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Detailed Description
The class of the ttk moving widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttkabstractmovewidget.h.
Constructor & Destructor Documentation
TTKAbstractMoveWidget::TTKAbstractMoveWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file ttkabstractmovewidget.cpp.
TTKAbstractMoveWidget::TTKAbstractMoveWidget (bool transparent, QWidget * parent = nullptr) explicit
Definition at line 10 of file ttkabstractmovewidget.cpp.
Member Function Documentation
void TTKAbstractMoveWidget::blockMoveOption (bool block) inline
Set or not block widget moving.
Definition at line 47 of file ttkabstractmovewidget.h.
Referenced by MusicSourceUpdateNotifyWidget::MusicSourceUpdateNotifyWidget(), MusicVideoPlayWidget::popupMode(), and MusicRightAreaWidget::videoFullscreen().
void TTKAbstractMoveWidget::drawWindowShadow (bool show) inline
Set or not draw window bound shadow.
Definition at line 43 of file ttkabstractmovewidget.h.
Referenced by MusicRemoteWidget::MusicRemoteWidget().
void TTKAbstractMoveWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 42 of file ttkabstractmovewidget.cpp.
References m_leftButtonPress, m_pressAt, QtMouseGlobalPos, QtMouseGlobalX, and QtMouseGlobalY.
void TTKAbstractMoveWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 31 of file ttkabstractmovewidget.cpp.
References m_leftButtonPress, m_moveOption, m_pressAt, and QtMouseGlobalPos.
void TTKAbstractMoveWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 57 of file ttkabstractmovewidget.cpp.
References m_leftButtonPress, m_pressAt, and QtMouseGlobalPos.
void TTKAbstractMoveWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 20 of file ttkabstractmovewidget.cpp.
References m_showShadow, and TTK::setBorderShadow().
Member Data Documentation
bool TTKAbstractMoveWidget::m_leftButtonPress protected
Definition at line 60 of file ttkabstractmovewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool TTKAbstractMoveWidget::m_moveOption protected
Definition at line 59 of file ttkabstractmovewidget.h.
Referenced by MusicVideoPlayWidget::isPopupMode(), and mousePressEvent().
QPoint TTKAbstractMoveWidget::m_pressAt protected
Definition at line 58 of file ttkabstractmovewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool TTKAbstractMoveWidget::m_showShadow protected
Definition at line 59 of file ttkabstractmovewidget.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractmovewidget.h
TTKCommon/TTKLibrary/ttkabstractmovewidget.cpp