TTKMusicplayer: QHelperDlna Namespace Reference
QHelperDlna Namespace Reference
The class of the dlna helper.
Functions
QString MakeRequest (const QString &methord, const QString &url, int length, const QString &soapAction, const QString &ip, const QString &port)
QString makeSocketGetReply (const QString &ip, const QString &port, const QString &data)
QString removeHttpHeader (const QString &data)
int GetResponseCode (const QString &data)
Detailed Description
The class of the dlna helper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
MUSIC_EXTRAS_EXPORT int QHelperDlna::GetResponseCode (const QString & data)
Definition at line 74 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer().
MUSIC_EXTRAS_EXPORT QString QHelperDlna::MakeRequest (const QString & methord, const QString & url, int length, const QString & soapAction, const QString & ip, const QString & port)
Definition at line 9 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer(), QDlnaClient::getPosition(), QDlnaClient::pause(), QDlnaClient::startPlay(), QDlnaClient::stopPlay(), and QDlnaClient::uploadFileToPlay().
MUSIC_EXTRAS_EXPORT QString QHelperDlna::makeSocketGetReply (const QString & ip, const QString & port, const QString & data)
Definition at line 40 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer(), QDlnaClient::getPosition(), QDlnaClient::pause(), QDlnaClient::startPlay(), QDlnaClient::stopPlay(), and QDlnaClient::uploadFileToPlay().
MUSIC_EXTRAS_EXPORT QString QHelperDlna::removeHttpHeader (const QString & data)
Definition at line 68 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer().