TTKMusicplayer: MusicPlatformManager Class Reference
MusicPlatformManager Class Reference
The class of the platform system manager.
#include <musicplatformmanager.h>
Public Types
enum SystemType {
System_Win10, System_Win8_1, System_Win8, System_Win7,
System_WinVista, System_WinXP, System_WinXP_Professional_x64_Edition, System_Win2000,
System_WinNT_4_0, System_Win95, System_Win98, System_WinMe,
System_WinServer_2003, System_WinServer_2003_R2, System_WinServer_2008, System_WinServer_2008_R2,
System_WinServer_2012, System_Linux, System_Linux_Ubuntu, System_Linux_Debian,
System_Linux_Arch, System_Linux_CentOS, System_Mac, System_Unkown
}
Public Member Functions
int logicalDotsPerInchX () const
int logicalDotsPerInchY () const
int logicalDotsPerInch () const
SystemType systemName () const
void setFileLink (const QString &src, const QString &des, const QString &ico, const QString &args, const QString &description)
Detailed Description
The class of the platform system manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicplatformmanager.h.
Member Enumeration Documentation
enum MusicPlatformManager::SystemType
Enumerator
System_Win10
System_Win8_1
System_Win8
System_Win7
System_WinVista
System_WinXP
System_WinXP_Professional_x64_Edition
System_Win2000
System_WinNT_4_0
System_Win95
System_Win98
System_WinMe
System_WinServer_2003
System_WinServer_2003_R2
System_WinServer_2008
System_WinServer_2008_R2
System_WinServer_2012
System_Linux
System_Linux_Ubuntu
System_Linux_Debian
System_Linux_Arch
System_Linux_CentOS
System_Mac
System_Unkown
Definition at line 32 of file musicplatformmanager.h.
Member Function Documentation
int MusicPlatformManager::logicalDotsPerInch () const
Get local DPI.
Definition at line 129 of file musicplatformmanager.cpp.
References generateDPIValue().
Referenced by loadAppScaledFactor().
int MusicPlatformManager::logicalDotsPerInchX () const
Get local DPI x.
Definition at line 117 of file musicplatformmanager.cpp.
References generateDPIValue().
int MusicPlatformManager::logicalDotsPerInchY () const
Get local DPI y.
Definition at line 123 of file musicplatformmanager.cpp.
References generateDPIValue().
void MusicPlatformManager::setFileLink (const QString & src, const QString & des, const QString & ico, const QString & args, const QString & description)
Set file link.
Definition at line 247 of file musicplatformmanager.cpp.
Referenced by MusicWebFMRadioWidget::sendToDesktopLink().
MusicPlatformManager::SystemType MusicPlatformManager::systemName () const
Get system name.
Definition at line 135 of file musicplatformmanager.cpp.
References System_Linux, System_Linux_Arch, System_Linux_CentOS, System_Linux_Debian, System_Linux_Ubuntu, System_Mac, System_Unkown, System_Win10, System_Win2000, System_Win7, System_Win8, System_Win8_1, System_Win95, System_Win98, System_WinMe, System_WinNT_4_0, System_WinServer_2003, System_WinServer_2003_R2, System_WinServer_2008, System_WinServer_2008_R2, System_WinServer_2012, System_WinVista, System_WinXP, and System_WinXP_Professional_x64_Edition.
Referenced by MusicUtils::Url::openUrl().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicplatformmanager.h
TTKModule/TTKCore/musicCoreKits/musicplatformmanager.cpp