TTKMusicplayer: filter::auto_t< TypeT, AllocT > Class Template Reference
filter::auto_t< TypeT, AllocT > Class Template Reference
#include <imagefilter.h>
Public Member Functions
auto_t ()
auto_t (long size)
virtual ~auto_t ()
void set (long size)
long size ()
TypeT & operator[] (long num)
Protected Attributes
TypeT * _point
long _size
Detailed Description
template<typename TypeT, typename AllocT = FILTER_ALLOC>
class filter::auto_t< TypeT, AllocT >
Definition at line 23 of file imagefilter.h.
Constructor & Destructor Documentation
template<typename TypeT, typename AllocT = FILTER_ALLOC> filter::auto_t< TypeT, AllocT >::auto_t () inline
Definition at line 30 of file imagefilter.h.
Referenced by filter::auto_t< bitmap_t::buff_t >::set().
template<typename TypeT, typename AllocT = FILTER_ALLOC> filter::auto_t< TypeT, AllocT >::auto_t (long size) inline
Definition at line 31 of file imagefilter.h.
template<typename TypeT, typename AllocT = FILTER_ALLOC> virtual filter::auto_t< TypeT, AllocT >::~auto_t () inline virtual
Definition at line 34 of file imagefilter.h.
Referenced by filter::auto_t< bitmap_t::buff_t >::set().
Member Function Documentation
template<typename TypeT, typename AllocT = FILTER_ALLOC> TypeT& filter::auto_t< TypeT, AllocT >::operator[] (long num) inline
Definition at line 51 of file imagefilter.h.
template<typename TypeT, typename AllocT = FILTER_ALLOC> void filter::auto_t< TypeT, AllocT >::set (long size) inline
Definition at line 43 of file imagefilter.h.
template<typename TypeT, typename AllocT = FILTER_ALLOC> long filter::auto_t< TypeT, AllocT >::size () inline
Definition at line 49 of file imagefilter.h.
Referenced by filter::Average(), filter::Blur2D(), filter::Linear(), and filter::Normalization().
Member Data Documentation
template<typename TypeT, typename AllocT = FILTER_ALLOC> TypeT* filter::auto_t< TypeT, AllocT >::_point protected
Definition at line 26 of file imagefilter.h.
template<typename TypeT, typename AllocT = FILTER_ALLOC> long filter::auto_t< TypeT, AllocT >::_size protected
Definition at line 27 of file imagefilter.h.
Referenced by filter::auto_t< bitmap_t::buff_t >::size(), and filter::auto_t< bitmap_t::buff_t >::~auto_t().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKImage/imagefilter.h