TTKMusicplayer: TTKThirdParty/TTKExtras/qalgorithm/aes.h File Reference
aes.h File Reference
#include <stddef.h>
Classes
struct aes_key_st
Macros
#define AES_ENCRYPT 1
#define AES_DECRYPT 0
#define AES_MAXNR 14
#define AES_BLOCK_SIZE 16
Typedefs
typedef struct aes_key_st AES_KEY
Functions
const char * AES_options (void)
int AES_set_encrypt_key (const unsigned char *userKey, const int bits, AES_KEY *key)
Expand the cipher key into the encryption key schedule.
int AES_set_decrypt_key (const unsigned char *userKey, const int bits, AES_KEY *key)
Expand the cipher key into the decryption key schedule.
void AES_encrypt (const unsigned char *in, unsigned char *out, const AES_KEY *key)
void AES_decrypt (const unsigned char *in, unsigned char *out, const AES_KEY *key)
void AES_ecb_encrypt (const unsigned char *in, unsigned char *out, const AES_KEY *key, const int enc)
void AES_cbc_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, unsigned char *ivec, const int enc)
void AES_cfb128_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, unsigned char *ivec, int *num, const int enc)
void AES_cfb1_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, unsigned char *ivec, int *num, const int enc)
void AES_cfb8_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, unsigned char *ivec, int *num, const int enc)
void AES_ofb128_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, unsigned char *ivec, int *num)
void AES_ige_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, unsigned char *ivec, const int enc)
void AES_bi_ige_encrypt (const unsigned char *in, unsigned char *out, size_t length, const AES_KEY *key, const AES_KEY *key2, const unsigned char *ivec, const int enc)
int AES_wrap_key (AES_KEY *key, const unsigned char *iv, unsigned char *out, const unsigned char *in, unsigned int inlen)
int AES_unwrap_key (AES_KEY *key, const unsigned char *iv, unsigned char *out, const unsigned char *in, unsigned int inlen)
Macro Definition Documentation
#define AES_BLOCK_SIZE 16
Definition at line 27 of file aes.h.
Referenced by QAesWrapper::encryptCBC(), and QAesWrapper::encryptECB().
#define AES_DECRYPT 0
Definition at line 20 of file aes.h.
Referenced by AES_ecb_encrypt(), QAesWrapper::decryptCBC(), and QAesWrapper::decryptECB().
#define AES_ENCRYPT 1
Definition at line 19 of file aes.h.
Referenced by AES_ecb_encrypt(), QAesWrapper::encryptCBC(), and QAesWrapper::encryptECB().
#define AES_MAXNR 14
Definition at line 26 of file aes.h.
Typedef Documentation
typedef struct aes_key_st AES_KEY
Definition at line 38 of file aes.h.
Function Documentation
void AES_bi_ige_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, const AES_KEY * key2, const unsigned char * ivec, const int enc)
void AES_cbc_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, unsigned char * ivec, const int enc)
Definition at line 4 of file aes_cbc.cpp.
References AES_decrypt(), AES_encrypt(), CRYPTO_cbc128_decrypt(), and CRYPTO_cbc128_encrypt().
Referenced by QAesWrapper::decryptCBC(), and QAesWrapper::encryptCBC().
void AES_cfb128_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, unsigned char * ivec, int * num, const int enc)
void AES_cfb1_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, unsigned char * ivec, int * num, const int enc)
void AES_cfb8_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, unsigned char * ivec, int * num, const int enc)
void AES_decrypt (const unsigned char * in, unsigned char * out, const AES_KEY * key)
Definition at line 983 of file aes_core.cpp.
References GETU32, PUTU32, aes_key_st::rd_key, aes_key_st::rounds, Td0, Td1, Td2, Td3, and Td4.
Referenced by AES_cbc_encrypt(), and AES_ecb_encrypt().
void AES_ecb_encrypt (const unsigned char * in, unsigned char * out, const AES_KEY * key, const int enc)
Definition at line 15 of file aes_ecb.cpp.
References AES_DECRYPT, AES_decrypt(), AES_ENCRYPT, and AES_encrypt().
Referenced by QAesWrapper::decryptECB(), and QAesWrapper::encryptECB().
void AES_encrypt (const unsigned char * in, unsigned char * out, const AES_KEY * key)
Definition at line 792 of file aes_core.cpp.
References GETU32, PUTU32, aes_key_st::rd_key, aes_key_st::rounds, Te0, Te1, Te2, and Te3.
Referenced by AES_cbc_encrypt(), and AES_ecb_encrypt().
void AES_ige_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, unsigned char * ivec, const int enc)
void AES_ofb128_encrypt (const unsigned char * in, unsigned char * out, size_t length, const AES_KEY * key, unsigned char * ivec, int * num)
const char* AES_options (void)
int AES_set_decrypt_key (const unsigned char * userKey, const int bits, AES_KEY * key)
Expand the cipher key into the decryption key schedule.
Definition at line 732 of file aes_core.cpp.
References AES_set_encrypt_key(), aes_key_st::rd_key, aes_key_st::rounds, Td0, Td1, Td2, Td3, and Te1.
Referenced by QAesWrapper::decryptCBC(), and QAesWrapper::decryptECB().
int AES_set_encrypt_key (const unsigned char * userKey, const int bits, AES_KEY * key)
Expand the cipher key into the encryption key schedule.
Definition at line 631 of file aes_core.cpp.
References GETU32, rcon, aes_key_st::rd_key, aes_key_st::rounds, Te0, Te1, Te2, and Te3.
Referenced by AES_set_decrypt_key(), QAesWrapper::encryptCBC(), and QAesWrapper::encryptECB().
int AES_unwrap_key (AES_KEY * key, const unsigned char * iv, unsigned char * out, const unsigned char * in, unsigned int inlen)
int AES_wrap_key (AES_KEY * key, const unsigned char * iv, unsigned char * out, const unsigned char * in, unsigned int inlen)