TTKMusicPlayer: TTK::Algorithm Namespace Reference
TTK::Algorithm Namespace Reference
Functions
TTK_MODULE_EXPORT QByteArray md5 (const QByteArray &data, bool base64=false)
TTK_MODULE_EXPORT QByteArray sha1 (const QByteArray &data)
TTK_MODULE_EXPORT QByteArray hmacSha1 (const QByteArray &data, const QByteArray &key)
TTK_MODULE_EXPORT QString mdII (const QString &data, bool encode)
TTK_MODULE_EXPORT QString mdII (const QString &data, const char *key, bool encode)
Function Documentation
QByteArray TTK::Algorithm::hmacSha1 (const QByteArray & data, const QByteArray & key)
Encode the data into sha1.
Definition at line 17 of file musicalgorithmutils.cpp.
References key, and sha1().
Referenced by MusicACRIdentifyRequest::startToRequest().
QByteArray TTK::Algorithm::md5 (const QByteArray & data, bool base64 = false)
Get md5 algorithm.
Definition at line 6 of file musicalgorithmutils.cpp.
Referenced by MusicSongsContainerWidget::addSongBufferToPlaylist(), ReqWYInterface::makeCoverPixmapUrl(), MusicMessageAboutDialog::MusicMessageAboutDialog(), ReqKGInterface::parseFromMovieProperty(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), and MusicXFIdentifyRequest::startToRequest().
QString TTK::Algorithm::mdII (const QString & data, bool encode)
Get mdII ttk algorithm.
Definition at line 42 of file musicalgorithmutils.cpp.
References TTKCryptographicHash::decrypt(), TTKCryptographicHash::encrypt(), and MDII_URL_KEY.
Referenced by ToolUrl::decodeClicked(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicDownloadBingSkinRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicKGQuerySongRequest::downloadSingleFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicTXDownloadBackgroundRequest::downloadUrl(), ToolUrl::encodeClicked(), MusicApplicationModule::loadNetWorkSetting(), ReqKWInterface::makeArtistPixmapUrl(), ReqWYInterface::makeCoverPixmapUrl(), ReqKWInterface::makeCoverPixmapUrl(), ReqBLInterface::makeRequestRawHeader(), ReqWYInterface::makeRequestRawHeader(), ReqKGInterface::makeRequestRawHeader(), makeUser(), MusicKWQueryPlaylistRequest::morePlaylistDetails(), MusicNetworkConnectionTestWidget::MusicNetworkConnectionTestWidget(), MusicWYQueryArtistMovieRequest::parseFromArtistMoviesCount(), ReqKGInterface::parseFromMovieInfo(), ReqKWInterface::parseFromMovieInfo(), ReqBLInterface::parseFromMovieInfo(), MusicWYQueryMovieRequest::parseFromMovieList(), ReqKGInterface::parseFromMovieProperty(), ReqWYInterface::parseFromMovieProperty(), ReqKWInterface::parseFromMovieProperty(), ReqBLInterface::parseFromMovieProperty(), ReqKGInterface::parseFromSongAlbumInfo(), ReqKGInterface::parseFromSongAlbumLrc(), ReqLQInterface::parseFromSongProperty(), ReqUnityInterface::parseFromSongProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), MusicKGQueryArtistRequest::queryArtistIntro(), MusicWYQueryArtistRequest::queryArtistIntro(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicKWQueryToplistRequest::queryToplistInfo(), MusicKGQueryToplistRequest::queryToplistInfo(), MusicSongSharingWidget::sendToShare(), MusicApplicationModule::showBugReportView(), ToolQTFM::startToListRequest(), MusicUnityQueryMovieRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicKWQuerySongRequest::startToPage(), MusicKGQuerySongRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicKWQueryToplistRequest::startToPage(), MusicKGQueryArtistRequest::startToPage(), MusicNewAlbumsRecommendRequest::startToPage(), MusicKGQueryToplistRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicWYQueryAlbumRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicWYQueryArtistRequest::startToPage(), MusicKWQueryAlbumRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicKWQueryArtistRequest::startToPage(), MusicKGQueryAlbumRequest::startToPage(), MusicWYQuerySongRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicWYQueryToplistRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicWYQueryHotArtistListRequest::startToPage(), MusicKWQueryHotArtistListRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKGQueryHotArtistListRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicWYQueryArtistAlbumRequest::startToPage(), MusicKGQueryArtistAlbumRequest::startToPage(), MusicKWQueryArtistAlbumRequest::startToPage(), MusicKGQueryArtistMovieRequest::startToPage(), MusicKWQueryArtistMovieRequest::startToPage(), MusicKGQueryNewSongRequest::startToPage(), MusicArtistsRecommendRequest::startToPage(), MusicKWQueryNewSongRequest::startToPage(), MusicWYQueryNewSongRequest::startToPage(), MusicKGQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryArtistMovieRequest::startToPage(), MusicKGQueryNewAlbumRequest::startToPage(), MusicWYQueryNewAlbumRequest::startToPage(), MusicKWQueryNewAlbumRequest::startToPage(), MusicKWQueryPlaylistRecommendRequest::startToPage(), MusicKGQueryPlaylistHighRequest::startToPage(), MusicPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistHighRequest::startToPage(), MusicKWQueryPlaylistHighRequest::startToPage(), MusicPlaylistHQRecommendRequest::startToPage(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicKWQueryPlaylistRequest::startToQueryInfo(), MusicWYQueryPlaylistRequest::startToQueryInfo(), MusicDownloadBingSkinRequest::startToRequest(), MusicWYCoverSourceRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicBarrageRequest::startToRequest(), MusicBDTranslationRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicFMRadioSongRequest::startToRequest(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicCiBaRequest::startToRequest(), MusicNetworkOperator::startToRequest(), MusicWYTranslationRequest::startToRequest(), MusicDownloadBirdSkinRequest::startToRequest(), MusicDJRadioCategoryRequest::startToRequest(), MusicBPDownloadBackgroundRequest::startToRequest(), ToolQTFM::startToRequest(), MusicKWCoverSourceRequest::startToRequest(), MusicDJRadioProgramRequest::startToRequest(), MusicDownloadThunderSkinRequest::startToRequest(), MusicTXDownloadBackgroundRequest::startToRequest(), MusicKWDownloadCoverRequest::startToRequest(), ToolXIFM::startToRequest(), MusicACRIdentifyRequest::startToRequest(), MusicXFIdentifyRequest::startToRequest(), MusicKGDiscoverListRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicSongRecommendRequest::startToSearch(), MusicSongSuggestRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicKWQuerySongRequest::startToSearchByID(), MusicKGQuerySongRequest::startToSearchByID(), MusicWYQuerySongRequest::startToSearchByID(), MusicAdvancedSearchedWidget::typeIndexChanged(), and MusicSourceUpdateWidget::upgradeButtonClicked().
QString TTK::Algorithm::mdII (const QString & data, const char * key, bool encode)
Get mdII ttk algorithm.
Definition at line 48 of file musicalgorithmutils.cpp.
References TTKCryptographicHash::decrypt(), and TTKCryptographicHash::encrypt().
QByteArray TTK::Algorithm::sha1 (const QByteArray & data)
Get sha1 algorithm.
Definition at line 12 of file musicalgorithmutils.cpp.
Referenced by hmacSha1(), MusicSettingWidget::initialize(), and MusicMessageAboutDialog::MusicMessageAboutDialog().