TTKMusicPlayer: TTKXmlDocument Class Reference
TTKXmlDocument Class Reference
The class of the ttk xml interface.
#include <ttkabstractxml.h>
Public Member Functions
TTKXmlDocument (QObject *parent=nullptr)
~TTKXmlDocument ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
bool toFile (const QString &name)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readXmlTextByTagName (const QString &tagName) const
TTKXmlAttributeList readXmlAttributesByTagName (const QString &tagName) const
QStringList readXmlMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readXmlMultiTextByTagName (const QString &tagName) const
TTKXmlAttributesList readXmlMultiAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const TTKXmlAttribute &attr)
QDomElement createRoot (const QString &node, const TTKXmlAttributeList &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr)
QDomElement writeDomMutilElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const TTKXmlAttribute &attr, const QString &text)
QDomElement writeDomMutilElementText (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const TTKXmlAttribute &attr)
Protected Attributes
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the ttk xml interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 86 of file ttkabstractxml.h.
Constructor & Destructor Documentation
TTKXmlDocument::TTKXmlDocument (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 81 of file ttkabstractxml.cpp.
TTKXmlDocument::~TTKXmlDocument ()
Definition at line 89 of file ttkabstractxml.cpp.
References m_document, and m_file.
Member Function Documentation
void TTKXmlDocument::createProcessingInstruction ()
Create processing instruction in header.
Definition at line 251 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicXSPFConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and MusicSkinConfigManager::writeBuffer().
QDomElement TTKXmlDocument::createRoot (const QString & node)
Create xml node nodes by node name.
Definition at line 257 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicASXConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and MusicSkinConfigManager::writeBuffer().
QDomElement TTKXmlDocument::createRoot (const QString & node, const TTKXmlAttribute & attr)
Create xml node nodes by node atrr.
Definition at line 264 of file ttkabstractxml.cpp.
References m_document, and writeAttribute().
QDomElement TTKXmlDocument::createRoot (const QString & node, const TTKXmlAttributeList & attrs)
Create xml node nodes by node atrrs.
Definition at line 272 of file ttkabstractxml.cpp.
References m_document, and writeAttribute().
bool TTKXmlDocument::fromByteArray (const QByteArray & data)
Xml stream data from byteArray.
Definition at line 132 of file ttkabstractxml.cpp.
References m_document, m_file, and TTKStaticCast.
Referenced by MusicCounterPVRequest::downLoadFinished(), MusicDownloadThunderSkinRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicExtractWrapper::outputSkin().
bool TTKXmlDocument::fromFile (const QString & name)
Read datas from xml file by given name.
Definition at line 95 of file ttkabstractxml.cpp.
References m_document, and m_file.
Referenced by MusicTKPLConfigManager::fromFile(), MusicConfigManager::fromFile(), MusicDownloadRecordConfigManager::fromFile(), MusicSongSearchRecordConfigManager::fromFile(), MusicCategoryConfigManager::fromFile(), MusicTTKFMRadioPlayWidget::initialize(), MusicPlaylistManager::readASXConfig(), MusicPlaylistManager::readWPLConfig(), and MusicPlaylistManager::readXSPFConfig().
bool TTKXmlDocument::fromString (const QString & data)
Xml stream data from string.
Definition at line 118 of file ttkabstractxml.cpp.
References m_document, m_file, and TTKStaticCast.
QString TTKXmlDocument::readXmlAttributeByTagName (const QString & tagName, const QString & attrName = "value") const
Read xml attribute by tagName and attribute name.
Definition at line 166 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicConfigManager::readBuffer(), MusicSkinConfigManager::readBuffer(), and MusicConfigManager::readShowDesktopLrcGeometry().
TTKXmlAttributeList TTKXmlDocument::readXmlAttributesByTagName (const QString & tagName) const
Read xml attributes by tagName.
Definition at line 178 of file ttkabstractxml.cpp.
References m_document.
QStringList TTKXmlDocument::readXmlMultiAttributeByTagName (const QString & tagName, const QString & attrName = "value") const
Read xml multi attribute by tagName and attribute name.
Definition at line 196 of file ttkabstractxml.cpp.
References m_document.
TTKXmlAttributesList TTKXmlDocument::readXmlMultiAttributesByTagName (const QString & tagName) const
Read xml multi attributes by multi tagName.
Definition at line 228 of file ttkabstractxml.cpp.
References m_document.
QStringList TTKXmlDocument::readXmlMultiTextByTagName (const QString & tagName) const
Read xml multi attribute's text by multi tagName.
Definition at line 212 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicCounterPVRequest::downLoadFinished().
QString TTKXmlDocument::readXmlTextByTagName (const QString & tagName) const
Read xml attribute's text by tagName.
Definition at line 172 of file ttkabstractxml.cpp.
References m_document.
QByteArray TTKXmlDocument::toByteArray () const
Xml stream data to byteArray.
Definition at line 161 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicExtractWrapper::inputSkin().
bool TTKXmlDocument::toFile (const QString & name)
Write datas into xml file by given name.
Definition at line 146 of file ttkabstractxml.cpp.
References m_document, and m_file.
Referenced by MusicASXConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and MusicSkinConfigManager::writeBuffer().
QString TTKXmlDocument::toString () const
Xml stream data to string.
Definition at line 156 of file ttkabstractxml.cpp.
References m_document.
void TTKXmlDocument::writeAttribute (QDomElement & element, const TTKXmlAttribute & attr)
Append xml element nodes key name and value.
Definition at line 341 of file ttkabstractxml.cpp.
References TTKXmlAttribute::m_key, TTKXmlAttribute::m_value, and QtVariantType.
Referenced by createRoot(), writeDomElement(), and writeDomMutilElement().
QDomElement TTKXmlDocument::writeDomElement (QDomElement & element, const QString & node, const TTKXmlAttribute & attr)
Append xml element nodes by node name\ key name and value.
Definition at line 290 of file ttkabstractxml.cpp.
References writeAttribute(), and writeDomNode().
Referenced by MusicASXConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), MusicSkinConfigManager::writeBuffer(), writeDomElementText(), and writeDomMutilElement().
QDomElement TTKXmlDocument::writeDomElementText (QDomElement & element, const QString & node, const TTKXmlAttribute & attr, const QString & text)
Append xml element nodes by node name\ key name \ value and attribute's text.
Definition at line 312 of file ttkabstractxml.cpp.
References m_document, and writeDomElement().
Referenced by MusicXSPFConfigManager::writeBuffer(), and MusicSongSearchRecordConfigManager::writeBuffer().
QDomElement TTKXmlDocument::writeDomMutilElement (QDomElement & element, const QString & node, const TTKXmlAttributeList & attrs)
Append xml elements nodes by node name\ keys name and values.
Definition at line 297 of file ttkabstractxml.cpp.
References writeAttribute(), and writeDomElement().
Referenced by MusicWPLConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and writeDomMutilElementText().
QDomElement TTKXmlDocument::writeDomMutilElementText (QDomElement & element, const QString & node, const TTKXmlAttributeList & attrs, const QString & text)
Append xml elements nodes by node name\ keys name \ values and attribute's text.
Definition at line 320 of file ttkabstractxml.cpp.
References m_document, and writeDomMutilElement().
Referenced by MusicTKPLConfigManager::writeBuffer(), and MusicDownloadRecordConfigManager::writeBuffer().
QDomElement TTKXmlDocument::writeDomNode (QDomElement & element, const QString & node)
Append xml element nodes by node name.
Definition at line 283 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicASXConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), writeDomElement(), and writeDomText().
QDomElement TTKXmlDocument::writeDomText (QDomElement & element, const QString & node, const QString & text)
Append xml element nodes by node name and attribute's text.
Definition at line 333 of file ttkabstractxml.cpp.
References m_document, and writeDomNode().
Referenced by MusicASXConfigManager::writeBuffer(), and MusicXSPFConfigManager::writeBuffer().
Member Data Documentation
QDomDocument* TTKXmlDocument::m_document protected
Definition at line 197 of file ttkabstractxml.h.
Referenced by createProcessingInstruction(), createRoot(), fromByteArray(), fromFile(), fromString(), MusicThunderSkinConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), MusicTXImageConfigManager::readBuffer(), MusicASXConfigManager::readBuffer(), MusicWPLConfigManager::readBuffer(), MusicTKPLConfigManager::readBuffer(), MusicSongSearchRecordConfigManager::readBuffer(), MusicDownloadRecordConfigManager::readBuffer(), MusicFMConfigManager::readBuffer(), MusicCategoryConfigManager::readBuffer(), MusicConfigManager::readWindowGeometry(), readXmlAttributeByTagName(), readXmlAttributesByTagName(), readXmlMultiAttributeByTagName(), readXmlMultiAttributesByTagName(), readXmlMultiTextByTagName(), readXmlTextByTagName(), toByteArray(), toFile(), toString(), MusicXSPFConfigManager::writeBuffer(), MusicASXConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), MusicSkinConfigManager::writeBuffer(), writeDomElementText(), writeDomMutilElementText(), writeDomNode(), writeDomText(), and ~TTKXmlDocument().
QFile* TTKXmlDocument::m_file protected
Definition at line 196 of file ttkabstractxml.h.
Referenced by fromByteArray(), fromFile(), fromString(), MusicASXConfigManager::readBuffer(), MusicWPLConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), toFile(), MusicASXConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), MusicSkinConfigManager::writeBuffer(), and ~TTKXmlDocument().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractxml.h
TTKCommon/TTKLibrary/ttkabstractxml.cpp