TTKMusicPlayer: TTKAbstractXml Class Reference
TTKAbstractXml Class Reference
The class of the ttk xml interface.
#include <ttkabstractxml.h>
Public Member Functions
TTKAbstractXml ()
virtual ~TTKAbstractXml ()
bool load (const QString &name)
void save () const
bool reset ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
void createProcessingInstruction () const
QString readAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readTextByTagName (const QString &tagName) const
TTKXmlNode readNodeByTagName (const QString &tagName) const
QStringList readMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readMultiTextByTagName (const QString &tagName) const
TTKXmlNodeList readMultiNodeByTagName (const QString &tagName) const
QDomElement createRoot (const QString &node) const
QDomElement createRoot (const QString &node, const TTKXmlAttr &attr) const
QDomElement createRoot (const QString &node, const TTKXmlAttrList &attrs) const
QDomElement writeDomElement (QDomElement &element, const QString &node) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const QString &text) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlNode &attr) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttr &attr) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttr &attr, const QString &text) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlNode &attrs) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttrList &attrs) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttrList &attrs, const QString &text) const
void writeAttribute (QDomElement &element, const TTKXmlAttr &attr) const
void writeAttribute (QDomElement &element, const TTKXmlAttrList &attr) const
Protected Attributes
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the ttk xml interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 105 of file ttkabstractxml.h.
Constructor & Destructor Documentation
TTKAbstractXml::TTKAbstractXml ()
Object constructor.
Definition at line 81 of file ttkabstractxml.cpp.
TTKAbstractXml::~TTKAbstractXml () virtual
Object destructor.
Definition at line 88 of file ttkabstractxml.cpp.
References m_document, and m_file.
Member Function Documentation
void TTKAbstractXml::createProcessingInstruction () const
Create processing instruction in header.
Definition at line 186 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicTKPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and MusicSkinConfigManager::writeBuffer().
QDomElement TTKAbstractXml::createRoot (const QString & node) const
Create xml node nodes by node name.
Definition at line 285 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicASXConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and MusicSkinConfigManager::writeBuffer().
QDomElement TTKAbstractXml::createRoot (const QString & node, const TTKXmlAttr & attr) const
Create xml node nodes by node atrr.
Definition at line 292 of file ttkabstractxml.cpp.
References m_document, and writeAttribute().
QDomElement TTKAbstractXml::createRoot (const QString & node, const TTKXmlAttrList & attrs) const
Create xml node nodes by node atrrs.
Definition at line 300 of file ttkabstractxml.cpp.
References m_document, and writeAttribute().
bool TTKAbstractXml::fromByteArray (const QByteArray & data)
Xml stream data from byteArray.
Definition at line 162 of file ttkabstractxml.cpp.
References m_document, m_file, and TTKStaticCast.
Referenced by MusicPVCounterRequest::downLoadFinished(), MusicDownloadThunderSkinRequest::downLoadFinished(), MusicBarrageWidget::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicExtractWrapper::outputSkin().
bool TTKAbstractXml::fromFile (const QString & name)
Read datas from xml file by given name.
Definition at line 125 of file ttkabstractxml.cpp.
References m_document, and m_file.
Referenced by MusicTTKFMRadioPlayWidget::closeEvent(), MusicPlaylistBackupWidget::currentTimeChanged(), MusicCategoryConfigManager::fromFile(), MusicConsoleModule::initialize(), MusicSongSearchPopWidget::initialize(), MusicTTKFMRadioPlayWidget::initialize(), MusicPlaylistManager::readASXConfig(), MusicApplication::readSystemConfigFromFile(), MusicPlaylistManager::readTKPLConfig(), MusicPlaylistManager::readWPLConfig(), MusicPlaylistManager::readXSPFConfig(), MusicRunTimeManager::run(), MusicDownloadWidget::startToRequestMusic(), MusicSongSearchTableWidget::startToSearchByText(), and MusicAbstractDownloadTableWidget::updateSongsList().
bool TTKAbstractXml::fromString (const QString & data)
Xml stream data from string.
Definition at line 148 of file ttkabstractxml.cpp.
References m_document, m_file, and TTKStaticCast.
bool TTKAbstractXml::load (const QString & name)
Init document by given name.
Definition at line 94 of file ttkabstractxml.cpp.
References m_document, and m_file.
Referenced by MusicSongSearchPopWidget::clearButtonClicked(), ToolFM::downLoadFinished(), MusicExtractWrapper::inputSkin(), reset(), MusicPlaylistBackupModule::runBackup(), MusicPlaylistManager::writeASXConfig(), MusicApplication::writeSystemConfigToFile(), MusicPlaylistManager::writeTKPLConfig(), MusicPlaylistManager::writeWPLConfig(), MusicPlaylistManager::writeXSPFConfig(), and MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget().
QString TTKAbstractXml::readAttributeByTagName (const QString & tagName, const QString & attrName = "value") const
Read xml attribute by tagName and attribute name.
Definition at line 192 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicConfigManager::readBuffer(), MusicSkinConfigManager::readBuffer(), and MusicConfigManager::readShowDesktopLrcGeometry().
QStringList TTKAbstractXml::readMultiAttributeByTagName (const QString & tagName, const QString & attrName = "value") const
Read xml multi attribute by tagName and attribute name.
Definition at line 226 of file ttkabstractxml.cpp.
References m_document.
TTKXmlNodeList TTKAbstractXml::readMultiNodeByTagName (const QString & tagName) const
Read xml multi node by tagName.
Definition at line 258 of file ttkabstractxml.cpp.
References TTKXmlNode::m_attrs, m_document, and TTKXmlNode::m_text.
Referenced by MusicBarrageWidget::downLoadFinished().
QStringList TTKAbstractXml::readMultiTextByTagName (const QString & tagName) const
Read xml multi attribute's text by tagName.
Definition at line 242 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicPVCounterRequest::downLoadFinished().
TTKXmlNode TTKAbstractXml::readNodeByTagName (const QString & tagName) const
Read xml node by tagName.
Definition at line 204 of file ttkabstractxml.cpp.
References TTKXmlNode::m_attrs, m_document, and TTKXmlNode::m_text.
QString TTKAbstractXml::readTextByTagName (const QString & tagName) const
Read xml attribute's text by tagName.
Definition at line 198 of file ttkabstractxml.cpp.
References m_document.
bool TTKAbstractXml::reset ()
Reset xml stream data.
Definition at line 115 of file ttkabstractxml.cpp.
References load(), m_document, and m_file.
Referenced by MusicTTKFMRadioPlayWidget::closeEvent(), MusicDownloadWidget::startToRequestMusic(), and MusicSongSearchTableWidget::startToSearchByText().
void TTKAbstractXml::save () const
Save xml stream data to local.
Definition at line 104 of file ttkabstractxml.cpp.
References m_document, and m_file.
Referenced by MusicASXConfigManager::writeBuffer(), MusicTKPLConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), and MusicSkinConfigManager::writeBuffer().
QByteArray TTKAbstractXml::toByteArray () const
Xml stream data to byteArray.
Definition at line 181 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicExtractWrapper::inputSkin().
QString TTKAbstractXml::toString () const
Xml stream data to string.
Definition at line 176 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicBarrageWidget::downLoadFinished().
void TTKAbstractXml::writeAttribute (QDomElement & element, const TTKXmlAttr & attr) const
Write xml element node key name and value.
Definition at line 373 of file ttkabstractxml.cpp.
References TTKXmlAttr::m_key, TTKXmlAttr::m_value, and QtVariantType.
Referenced by createRoot(), writeAttribute(), writeDomElement(), and writeDomMultiElement().
void TTKAbstractXml::writeAttribute (QDomElement & element, const TTKXmlAttrList & attr) const
Write xml element nodes key name and value.
Definition at line 387 of file ttkabstractxml.cpp.
References qAsConst, and writeAttribute().
QDomElement TTKAbstractXml::writeDomElement (QDomElement & element, const QString & node) const
Write xml element node by node name.
Definition at line 308 of file ttkabstractxml.cpp.
References m_document.
Referenced by MusicASXConfigManager::writeBuffer(), MusicXSPFConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicSongSearchRecordConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), MusicSkinConfigManager::writeBuffer(), writeDomElement(), and writeDomMultiElement().
QDomElement TTKAbstractXml::writeDomElement (QDomElement & element, const QString & node, const QString & text) const
Write xml element node by node name and attribute's text.
Definition at line 315 of file ttkabstractxml.cpp.
References m_document, and writeDomElement().
QDomElement TTKAbstractXml::writeDomElement (QDomElement & element, const QString & node, const TTKXmlNode & attr) const
Write xml element node by node name key name value and attribute's text.
Definition at line 323 of file ttkabstractxml.cpp.
References writeDomMultiElement().
QDomElement TTKAbstractXml::writeDomElement (QDomElement & element, const QString & node, const TTKXmlAttr & attr) const
Write xml element node by node name key name and value.
Definition at line 328 of file ttkabstractxml.cpp.
References writeAttribute(), and writeDomElement().
QDomElement TTKAbstractXml::writeDomElement (QDomElement & element, const QString & node, const TTKXmlAttr & attr, const QString & text) const
Write xml element node by node name key name value and attribute's text.
Definition at line 335 of file ttkabstractxml.cpp.
References m_document, and writeDomElement().
QDomElement TTKAbstractXml::writeDomMultiElement (QDomElement & element, const QString & node, const TTKXmlNode & attrs) const
Write xml elements nodes by node name keys name and values.
Definition at line 343 of file ttkabstractxml.cpp.
References TTKXmlNode::m_attrs, and TTKXmlNode::m_text.
Referenced by MusicTKPLConfigManager::writeBuffer(), MusicWPLConfigManager::writeBuffer(), MusicDownloadRecordConfigManager::writeBuffer(), MusicFMConfigManager::writeBuffer(), writeDomElement(), and writeDomMultiElement().
QDomElement TTKAbstractXml::writeDomMultiElement (QDomElement & element, const QString & node, const TTKXmlAttrList & attrs) const
Write xml elements nodes by node name keys name and values.
Definition at line 348 of file ttkabstractxml.cpp.
References writeAttribute(), and writeDomElement().
QDomElement TTKAbstractXml::writeDomMultiElement (QDomElement & element, const QString & node, const TTKXmlAttrList & attrs, const QString & text) const
Write xml elements nodes by node name keys name values and attribute's text.
Definition at line 360 of file ttkabstractxml.cpp.
References m_document, and writeDomMultiElement().
Member Data Documentation
QDomDocument* TTKAbstractXml::m_document protected
Definition at line 242 of file ttkabstractxml.h.
Referenced by createProcessingInstruction(), createRoot(), fromByteArray(), fromFile(), fromString(), load(), readAttributeByTagName(), MusicThunderSkinConfigManager::readBuffer(), MusicTXImageConfigManager::readBuffer(), MusicASXConfigManager::readBuffer(), MusicTKPLConfigManager::readBuffer(), MusicWPLConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), MusicSongSearchRecordConfigManager::readBuffer(), MusicDownloadRecordConfigManager::readBuffer(), MusicFMConfigManager::readBuffer(), MusicCategoryConfigManager::readBuffer(), readMultiAttributeByTagName(), readMultiNodeByTagName(), readMultiTextByTagName(), readNodeByTagName(), readTextByTagName(), MusicConfigManager::readWindowGeometry(), reset(), save(), toByteArray(), toString(), MusicWPLConfigManager::writeBuffer(), writeDomElement(), writeDomMultiElement(), and ~TTKAbstractXml().
QFile* TTKAbstractXml::m_file protected
Definition at line 241 of file ttkabstractxml.h.
Referenced by fromByteArray(), fromFile(), fromString(), load(), MusicASXConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), MusicWPLConfigManager::readBuffer(), reset(), save(), and ~TTKAbstractXml().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractxml.h
TTKCommon/TTKLibrary/ttkabstractxml.cpp