TTKMusicPlayer: TTKDateTime Class Reference
TTKDateTime Class Reference
The class of the ttk date time object.
#include <ttktime.h>
Static Public Member Functions
static qint64 currentTimestamp () noexcept
static QString format (const QString &time, const QString &format)
static QString format (qint64 time, const QString &format)
Detailed Description
The class of the ttk date time object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 193 of file ttktime.h.
Member Function Documentation
qint64 TTKDateTime::currentTimestamp () static noexcept
Get current timestamp(ms).
Definition at line 249 of file ttktime.cpp.
Referenced by MusicRecommendQueryWidget::createLabels(), MusicLrcPhotoWidget::exportButtonClicked(), parseSongPropertyV3(), MusicCloudManagerTableWidget::receiveDataFinshed(), MusicPlaylistBackupModule::runBackup(), MusicACRIdentifyRequest::startToRequest(), MusicDownloadDataRequest::startToRequest(), MusicXFIdentifyRequest::startToRequest(), MusicSongSearchTableWidget::startToSearchByValue(), MusicCloudUploadTableWidget::uploadFileError(), MusicCloudManagerTableWidget::uploadFilesToServer(), and MusicSongSearchPopWidget::utcTimeToLocal().
QString TTKDateTime::format (const QString & time, const QString & format) static
Transform string time format to timestamp(ms) string.
Definition at line 254 of file ttktime.cpp.
Referenced by MusicCommentsItem::addCellItem(), MusicRecommendQueryWidget::createLabels(), MusicPlaylistBackupWidget::currentDateChanged(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicWYQueryToplistRequest::queryToplistInfo(), MusicKGQueryToplistRequest::queryToplistInfo(), MusicWYQueryPlaylistRequest::startToQueryInfo(), and MusicKWQueryPlaylistRequest::startToQueryInfo().
QString TTKDateTime::format (qint64 time, const QString & format) static
Transform timestamp(ms) to string time format.
Definition at line 259 of file ttktime.cpp.
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttktime.h
TTKCommon/TTKLibrary/ttktime.cpp