TTKMusicplayer: MusicDownLoadThreadAbstract Class Reference
MusicDownLoadThreadAbstract Class Reference abstract
The class of abstract downloading data.
#include <musicdownloadthreadabstract.h>
Public Slots
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadThreadAbstract (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
virtual ~MusicDownLoadThreadAbstract ()
virtual void deleteAll () override
virtual void startToDownload ()=0
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Protected Member Functions
QString transferData () const
Protected Attributes
QFile * m_file
QString m_url
QString m_savePathName
MusicObject::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_timer
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Detailed Description
The class of abstract downloading data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicdownloadthreadabstract.h.
Constructor & Destructor Documentation
MusicDownLoadThreadAbstract::MusicDownLoadThreadAbstract (const QString & url, const QString & save, MusicObject::DownloadType type, QObject * parent = nullptr)
Object contsructor provide download URL\ save local path and download type.
Definition at line 14 of file musicdownloadthreadabstract.cpp.
References m_currentReceived, M_DOWNLOAD_MANAGER_PTR, m_downloadType, m_file, m_hasReceived, m_savePathName, m_timer, m_url, MT_S2MS, and updateDownloadSpeed().
MusicDownLoadThreadAbstract::~MusicDownLoadThreadAbstract () virtual
Definition at line 34 of file musicdownloadthreadabstract.cpp.
References M_DOWNLOAD_MANAGER_PTR.
Member Function Documentation
void MusicDownLoadThreadAbstract::deleteAll () override virtual
Release the network object.
Reimplemented from MusicNetworkAbstract.
Definition at line 39 of file musicdownloadthreadabstract.cpp.
References MusicNetworkAbstract::deleteAll(), and m_file.
Referenced by MusicKWTextDownLoadThread::downLoadFinished(), MusicTextDownLoadThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicXMTextDownLoadThread::downLoadFinished(), MusicDataDownloadThread::downLoadFinished(), replyError(), sslErrors(), MusicKWTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicDataDownloadThread::startToDownload(), MusicDataTagDownloadThread::startToDownload(), and MusicDownloadQueueCache::~MusicDownloadQueueCache().
void MusicDownLoadThreadAbstract::downloadProgress (qint64 bytesReceived, qint64 bytesTotal) virtual slot
Get download received and total data.
Definition at line 66 of file musicdownloadthreadabstract.cpp.
References m_currentReceived, and m_totalSize.
Referenced by MusicDataDownloadThread::downloadProgress(), MusicXMTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), and MusicKWTextDownLoadThread::startToDownload().
void MusicDownLoadThreadAbstract::replyError (QNetworkReply::NetworkError error) override virtual slot
Download reply error.
Definition at line 50 of file musicdownloadthreadabstract.cpp.
References deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), and M_LOGGER_ERROR.
Referenced by MusicDataDownloadThread::startRequest(), MusicXMTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), and MusicKWTextDownLoadThread::startToDownload().
void MusicDownLoadThreadAbstract::sslErrors (QNetworkReply * reply, const QList< QSslError > & errors) override virtual slot
Download ssl reply error.
Definition at line 58 of file musicdownloadthreadabstract.cpp.
References deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), and MusicNetworkAbstract::sslErrorsString().
Referenced by MusicDownloadQueueCache::MusicDownloadQueueCache(), MusicTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicDataDownloadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), and MusicDataTagDownloadThread::startToDownload().
virtual void MusicDownLoadThreadAbstract::startToDownload () pure virtual
Start to download data. Subclass should implement this function.
Implemented in MusicDownloadQueueCache, MusicDataTagDownloadThread, MusicKWTextDownLoadThread, MusicDataDownloadThread, MusicTextDownLoadThread, MusicQQTextDownLoadThread, MusicWYTextDownLoadThread, and MusicXMTextDownLoadThread.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget().
QString MusicDownLoadThreadAbstract::transferData () const protected
Transfer the enum type to string.
Definition at line 94 of file musicdownloadthreadabstract.cpp.
References MusicObject::DownloadBigBG, MusicObject::DownloadLrc, MusicObject::DownloadMusic, MusicObject::DownloadOther, MusicObject::DownloadSmallBG, MusicObject::DownloadVideo, and m_downloadType.
Referenced by MusicKWTextDownLoadThread::downLoadFinished(), MusicXMTextDownLoadThread::downLoadFinished(), MusicTextDownLoadThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicDataTagDownloadThread::downLoadFinished(), and MusicDataDownloadThread::downLoadFinished().
void MusicDownLoadThreadAbstract::updateDownloadSpeed () virtual slot
Updata download speed due the user mod the net speed limited.
limit speed
Definition at line 72 of file musicdownloadthreadabstract.cpp.
References MusicSettingManager::DownloadDLoadLimitChoiced, MusicSettingManager::DownloadLimitChoiced, m_currentReceived, m_hasReceived, M_SETTING_PTR, MH_KB, and MT_S2MS.
Referenced by MusicDownLoadThreadAbstract(), and MusicDataDownloadThread::updateDownloadSpeed().
Member Data Documentation
qint64 MusicDownLoadThreadAbstract::m_currentReceived protected
Definition at line 83 of file musicdownloadthreadabstract.h.
Referenced by downloadProgress(), MusicDownLoadThreadAbstract(), updateDownloadSpeed(), and MusicDataDownloadThread::updateDownloadSpeed().
MusicObject::DownloadType MusicDownLoadThreadAbstract::m_downloadType protected
Definition at line 82 of file musicdownloadthreadabstract.h.
Referenced by MusicDataDownloadThread::downloadProgress(), MusicDownLoadThreadAbstract(), MusicDataDownloadThread::startRequest(), and transferData().
QFile* MusicDownLoadThreadAbstract::m_file protected
Definition at line 80 of file musicdownloadthreadabstract.h.
Referenced by MusicDownloadQueueCache::abort(), deleteAll(), MusicKWTextDownLoadThread::downLoadFinished(), MusicXMTextDownLoadThread::downLoadFinished(), MusicTextDownLoadThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicDataTagDownloadThread::downLoadFinished(), MusicDataDownloadThread::downLoadFinished(), MusicDownloadQueueCache::downLoadFinished(), MusicDataDownloadThread::downLoadReadyRead(), MusicDownloadQueueCache::errorSlot(), MusicDownLoadThreadAbstract(), MusicDownloadQueueCache::readyReadSlot(), MusicDownloadQueueCache::startDownload(), MusicDataDownloadThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), and MusicDataTagDownloadThread::startToDownload().
qint64 MusicDownLoadThreadAbstract::m_hasReceived protected
Definition at line 83 of file musicdownloadthreadabstract.h.
Referenced by MusicDownLoadThreadAbstract(), updateDownloadSpeed(), and MusicDataDownloadThread::updateDownloadSpeed().
QString MusicDownLoadThreadAbstract::m_savePathName protected
Definition at line 81 of file musicdownloadthreadabstract.h.
Referenced by MusicDataTagDownloadThread::downLoadFinished(), MusicDownLoadThreadAbstract(), and MusicDataDownloadThread::startRequest().
QTimer MusicDownLoadThreadAbstract::m_timer protected
Definition at line 84 of file musicdownloadthreadabstract.h.
Referenced by MusicKWTextDownLoadThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicTextDownLoadThread::downLoadFinished(), MusicXMTextDownLoadThread::downLoadFinished(), MusicDataDownloadThread::downLoadFinished(), MusicDownloadQueueCache::downLoadFinished(), MusicDownLoadThreadAbstract(), MusicDownloadQueueCache::startDownload(), MusicDataDownloadThread::startRequest(), MusicTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), and MusicXMTextDownLoadThread::startToDownload().
qint64 MusicDownLoadThreadAbstract::m_totalSize protected
Definition at line 83 of file musicdownloadthreadabstract.h.
Referenced by downloadProgress(), and MusicDataDownloadThread::updateDownloadSpeed().
QString MusicDownLoadThreadAbstract::m_url protected
Definition at line 81 of file musicdownloadthreadabstract.h.
Referenced by MusicDownLoadThreadAbstract(), MusicKWTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicDataDownloadThread::startToDownload(), and MusicDataTagDownloadThread::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadthreadabstract.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadthreadabstract.cpp