TTKMusicplayer: MusicMoveButton Class Reference
MusicMoveButton Class Reference
The class of the move button.
#include <musiccutsliderwidget.h>
Signals
void moveChanged ()
void buttonRelease ()
Public Member Functions
MusicMoveButton (QWidget *parent=nullptr)
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Attributes
QPoint m_pressAt
bool m_leftButtonPress
Detailed Description
The class of the move button.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musiccutsliderwidget.h.
Constructor & Destructor Documentation
MusicMoveButton::MusicMoveButton (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 13 of file musiccutsliderwidget.cpp.
References MusicUIObject::MQSSPushButtonStyle02.
Member Function Documentation
void MusicMoveButton::buttonRelease () signal
Moving button released.
Referenced by mouseReleaseEvent().
void MusicMoveButton::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 38 of file musiccutsliderwidget.cpp.
References m_leftButtonPress, m_pressAt, and moveChanged().
void MusicMoveButton::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Definition at line 24 of file musiccutsliderwidget.cpp.
References m_leftButtonPress, and m_pressAt.
void MusicMoveButton::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 57 of file musiccutsliderwidget.cpp.
References buttonRelease(), m_leftButtonPress, and m_pressAt.
void MusicMoveButton::moveChanged () signal
Moving button pos updated.
Referenced by mouseMoveEvent().
Member Data Documentation
bool MusicMoveButton::m_leftButtonPress protected
Definition at line 57 of file musiccutsliderwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint MusicMoveButton::m_pressAt protected
Definition at line 56 of file musiccutsliderwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musiccutsliderwidget.h
TTKModule/TTKWidget/musicCoreKits/musiccutsliderwidget.cpp