TTKMusicPlayer: aes_key_st Struct Reference
aes_key_st Struct Reference
#include <aes.h>
Public Attributes
unsigned int rd_key [4 *(AES_MAXNR+1)]
int rounds
Detailed Description
Definition at line 30 of file aes.h.
Member Data Documentation
unsigned int aes_key_st::rd_key[4 *(AES_MAXNR+1)]
Definition at line 34 of file aes.h.
Referenced by AES_decrypt(), AES_encrypt(), AES_set_decrypt_key(), and AES_set_encrypt_key().
int aes_key_st::rounds
Definition at line 36 of file aes.h.
Referenced by AES_decrypt(), AES_encrypt(), AES_set_decrypt_key(), and AES_set_encrypt_key().
The documentation for this struct was generated from the following file:
TTKThirdParty/TTKExtras/qalgorithm/aes.h