TTKMusicplayer: MusicMovingClickedSlider Class Reference
MusicMovingClickedSlider Class Reference
The class of the slider moving clicked slider.
#include <musicmovingclickedslider.h>
Public Slots
void setValue (int value)
Signals
void sliderReleasedAt (int pos)
Signals inherited from MusicClickedSlider
void clicked ()
Public Member Functions
MusicMovingClickedSlider (QWidget *parent=nullptr)
MusicMovingClickedSlider (Qt::Orientation orientation, QWidget *parent=nullptr)
bool isMoving () const
void setMoving (bool m)
Public Member Functions inherited from MusicClickedSlider
MusicClickedSlider (QWidget *parent=nullptr)
MusicClickedSlider (Qt::Orientation orientation, QWidget *parent=nullptr)
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicClickedSlider
virtual bool event (QEvent *event) overridefinal
Protected Attributes
bool m_isMoving
Qt::Orientation m_orientation
Protected Attributes inherited from MusicClickedSlider
int m_value
bool m_mousePress
Detailed Description
The class of the slider moving clicked slider.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicmovingclickedslider.h.
Constructor & Destructor Documentation
MusicMovingClickedSlider::MusicMovingClickedSlider (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicmovingclickedslider.cpp.
MusicMovingClickedSlider::MusicMovingClickedSlider (Qt::Orientation orientation, QWidget * parent = nullptr) explicit
Object contsructor by slider orientation.
Definition at line 11 of file musicmovingclickedslider.cpp.
References m_isMoving, and m_orientation.
Member Function Documentation
bool MusicMovingClickedSlider::isMoving () const inline
Slider is now moving or not.
Definition at line 44 of file musicmovingclickedslider.h.
Referenced by MusicTimeSliderWidget::setValue().
void MusicMovingClickedSlider::mouseMoveEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicClickedSlider.
Reimplemented in MusicMovingLabelSlider.
Definition at line 38 of file musicmovingclickedslider.cpp.
References m_isMoving, MusicClickedSlider::m_mousePress, MusicClickedSlider::m_value, and MusicClickedSlider::mouseMoveEvent().
Referenced by MusicMovingLabelSlider::mouseMoveEvent().
void MusicMovingClickedSlider::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicClickedSlider.
Reimplemented in MusicMovingLabelSlider.
Definition at line 28 of file musicmovingclickedslider.cpp.
References m_isMoving, MusicClickedSlider::m_value, and MusicClickedSlider::mousePressEvent().
Referenced by MusicMovingLabelSlider::mousePressEvent().
void MusicMovingClickedSlider::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicClickedSlider.
Definition at line 48 of file musicmovingclickedslider.cpp.
References m_isMoving, MusicClickedSlider::m_value, MusicClickedSlider::mouseReleaseEvent(), and sliderReleasedAt().
void MusicMovingClickedSlider::setMoving (bool m) inline
Set slider moving or not.
Definition at line 48 of file musicmovingclickedslider.h.
void MusicMovingClickedSlider::setValue (int value) slot
Set slider current value.
Definition at line 20 of file musicmovingclickedslider.cpp.
References m_isMoving.
Referenced by MusicTimeSliderWidget::MusicTimeSliderWidget(), MusicTimeSliderWidget::setValue(), and MusicVideoControlWidget::setValue().
void MusicMovingClickedSlider::sliderReleasedAt (int pos) signal
Slider handle release at pos emit.
Referenced by mouseReleaseEvent().
Member Data Documentation
bool MusicMovingClickedSlider::m_isMoving protected
Definition at line 70 of file musicmovingclickedslider.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), MusicMovingClickedSlider(), and setValue().
Qt::Orientation MusicMovingClickedSlider::m_orientation protected
Definition at line 71 of file musicmovingclickedslider.h.
Referenced by MusicMovingLabelSlider::mouseMoveEvent(), and MusicMovingClickedSlider().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicmovingclickedslider.h
TTKModule/TTKWidget/musicCoreKits/musicmovingclickedslider.cpp