TTKMusicplayer: MusicAutoTest Namespace Reference
MusicAutoTest Namespace Reference
Typedefs
typedef QList< QObject * > TestList
Functions
TestList & testList ()
bool findObject (QObject *object)
void addTest (QObject *object)
int run (int argc, char *argv[])
Typedef Documentation
typedef QList<QObject*> MusicAutoTest::TestList
Definition at line 29 of file musicautotest.h.
Function Documentation
void MusicAutoTest::addTest (QObject * object) inline
Definition at line 54 of file musicautotest.h.
References findObject(), and testList().
Referenced by MusicTest< T >::MusicTest().
bool MusicAutoTest::findObject (QObject * object) inline
Definition at line 37 of file musicautotest.h.
References testList().
Referenced by addTest().
int MusicAutoTest::run (int argc, char * argv[]) inline
Definition at line 63 of file musicautotest.h.
References testList().
Referenced by CodeLinesTest::codeLines(), MusicWebRadioObject::dataDownloadFinished(), MusicNetworkThread::networkStateChanged(), MusicLocalSongsManagerWidget::setShowAlbumButton(), MusicLocalSongsManagerWidget::setShowArtButton(), Split_eat8(), Split_eatAn(), Split_eatKanji(), and Split_eatNum().
TestList& MusicAutoTest::testList () inline
Definition at line 31 of file musicautotest.h.
Referenced by addTest(), findObject(), and run().