TTKMusicplayer: MusicLicenseObject Class Reference
MusicLicenseObject Class Reference
The class of the license core module.
#include <musiclicenseobject.h>
Public Member Functions
MusicLicenseObject (QObject *parent=nullptr)
bool checkLicense (const QString &str)
QString getCharacteristicString ()
QString getCharacteristicStringNormal ()
QString getEncodeKey (const QString &key)
Private Member Functions
QStringList getCharacteristicStrings ()
QString splitString (const QByteArray &data, const QByteArray &key)
Detailed Description
The class of the license core module.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musiclicenseobject.h.
Constructor & Destructor Documentation
MusicLicenseObject::MusicLicenseObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musiclicenseobject.cpp.
Member Function Documentation
bool MusicLicenseObject::checkLicense (const QString & str)
Check license string.
Definition at line 21 of file musiclicenseobject.cpp.
References getCharacteristicStrings(), getEncodeKey(), and key.
QString MusicLicenseObject::getCharacteristicString ()
Get characteristic string.
Definition at line 33 of file musiclicenseobject.cpp.
References splitString(), and VALUE0.
QString MusicLicenseObject::getCharacteristicStringNormal ()
Get characteristic normal string.
Definition at line 44 of file musiclicenseobject.cpp.
References MusicUtils::Algorithm::hmacSha1(), and VALUE0.
Referenced by MusicSongListSharingWidget::createWriteKey().
QStringList MusicLicenseObject::getCharacteristicStrings () private
Get characteristic strings.
Definition at line 55 of file musiclicenseobject.cpp.
References splitString(), and VALUE0.
Referenced by checkLicense().
QString MusicLicenseObject::getEncodeKey (const QString & key)
Get encode key.
Definition at line 16 of file musiclicenseobject.cpp.
References splitString(), and VALUE1.
Referenced by checkLicense().
QString MusicLicenseObject::splitString (const QByteArray & data, const QByteArray & key) private
Split hmac string.
Definition at line 65 of file musiclicenseobject.cpp.
References MusicUtils::Algorithm::hmacSha1().
Referenced by getCharacteristicString(), getCharacteristicStrings(), and getEncodeKey().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musiclicenseobject.h
TTKModule/TTKCore/musicCoreKits/musiclicenseobject.cpp