TTKMusicplayer: MusicUtils::Number Namespace Reference
MusicUtils::Number Namespace Reference
Functions
MUSIC_UTILS_EXPORT QString size2Number (qint64 size)
MUSIC_UTILS_EXPORT QString size2NumberInt (qint64 size)
MUSIC_UTILS_EXPORT QString size2Label (qint64 size)
MUSIC_UTILS_EXPORT QString speed2Label (qint64 size)
MUSIC_UTILS_EXPORT QString speed2LabelInt (qint64 size)
MUSIC_UTILS_EXPORT qreal sizeByte2KByte (qint64 size)
MUSIC_UTILS_EXPORT qreal sizeByte2MByte (qint64 size)
MUSIC_UTILS_EXPORT qreal sizeByte2TByte (qint64 size)
MUSIC_UTILS_EXPORT QString speed2LabelFromLabel (qint64 size, const QString &label)
MUSIC_UTILS_EXPORT void transfromBitrateToQuality (int level, QString &bitString, QColor &color)
MUSIC_UTILS_EXPORT void transfromBitrateToQuality (int level, QString &bitString)
MUSIC_UTILS_EXPORT QString transfromBitrateToQuality (int level)
MUSIC_UTILS_EXPORT int transfromBitrateToLevel (const QString &bitrate)
MUSIC_UTILS_EXPORT int transfromBitrateToNormal (int bitrate)
MUSIC_UTILS_EXPORT int transfromBitrateToNormal (const QString &bitrate)
Function Documentation
QString MusicUtils::Number::size2Label (qint64 size)
Transform value to cp value.
Definition at line 41 of file musicnumberutils.cpp.
References MH_GB2B, MH_KB2B, MH_MB2B, MH_TB2B, and size2Number().
Referenced by MusicLocalSongsTableWidget::addItems(), MusicCloudManagerTableWidget::createItem(), MusicRadioSongsThread::downLoadFinished(), MusicDataDownloadThread::downloadProgress(), MusicDownLoadQueryThreadAbstract::findUrlFileSize(), MusicSong::MusicSong(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadQQInterface::readFromMusicSongAttribute(), MusicDownLoadBDInterface::readFromMusicSongAttribute(), MusicDownLoadXMInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttributeNew(), MusicDownLoadQQInterface::readFromMusicSongAttributePlus(), MusicFileInformationWidget::setFileInformation(), MusicCloudFileInformationWidget::setFileInformation(), MusicCloudManagerWidget::updataSizeLabel(), and MusicCloudUploadTableWidget::uploadFileError().
QString MusicUtils::Number::size2Number (qint64 size)
Transform value to cp float value.
Definition at line 7 of file musicnumberutils.cpp.
References MH_GB2B, MH_KB2B, MH_MB2B, and MH_TB2B.
Referenced by size2Label(), size2NumberInt(), and speed2Label().
QString MusicUtils::Number::size2NumberInt (qint64 size)
Transform value to cp int value.
Definition at line 31 of file musicnumberutils.cpp.
References size2Number().
Referenced by speed2LabelInt().
qreal MusicUtils::Number::sizeByte2KByte (qint64 size)
Transform value to kb entity.
Definition at line 81 of file musicnumberutils.cpp.
References MH_KB.
Referenced by sizeByte2MByte().
qreal MusicUtils::Number::sizeByte2MByte (qint64 size)
Transform value to mb entity.
Definition at line 86 of file musicnumberutils.cpp.
References MH_MB, and sizeByte2KByte().
Referenced by MusicSongCheckToolsDuplicateTableWidget::createAllItems(), MusicSongCheckToolsQualityTableWidget::createAllItems(), MusicSongsListItemInfoWidget::setMusicSongInformation(), and sizeByte2TByte().
qreal MusicUtils::Number::sizeByte2TByte (qint64 size)
Transform value to tb entity.
Definition at line 91 of file musicnumberutils.cpp.
References MH_GB, and sizeByte2MByte().
QString MusicUtils::Number::speed2Label (qint64 size)
Transform value to speed float value.
Definition at line 71 of file musicnumberutils.cpp.
References size2Number(), and speed2LabelFromLabel().
Referenced by MusicDataDownloadThread::updateDownloadSpeed().
QString MusicUtils::Number::speed2LabelFromLabel (qint64 size, const QString & label)
Transform value to speed value base.
Definition at line 96 of file musicnumberutils.cpp.
References MH_GB2B, MH_KB2B, MH_MB2B, and MH_TB2B.
Referenced by speed2Label(), and speed2LabelInt().
QString MusicUtils::Number::speed2LabelInt (qint64 size)
Transform value to speed int value.
Definition at line 76 of file musicnumberutils.cpp.
References size2NumberInt(), and speed2LabelFromLabel().
int MusicUtils::Number::transfromBitrateToLevel (const QString & bitrate)
Transfrom bitrate to level.
Definition at line 160 of file musicnumberutils.cpp.
References MB_192, MB_320, and MB_96.
Referenced by MusicSongCheckToolsQualityTableWidget::createAllItems(), and MusicFileInformationWidget::setFileInformation().
int MusicUtils::Number::transfromBitrateToNormal (int bitrate)
Transfrom bitrate to normal.
Definition at line 185 of file musicnumberutils.cpp.
References MB_0, MB_128, MB_192, MB_32, MB_320, MB_500, and MB_64.
Referenced by MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadBDInterface::readFromMusicSongAttribute(), and MusicDownLoadXMInterface::readFromMusicSongAttribute().
int MusicUtils::Number::transfromBitrateToNormal (const QString & bitrate)
Transfrom bitrate to normal.
Definition at line 201 of file musicnumberutils.cpp.
References MB_128, MB_192, MB_32, MB_320, and MB_500.
void MusicUtils::Number::transfromBitrateToQuality (int level, QString & bitString, QColor & color)
Transfrom bitrate to quality.
Definition at line 120 of file musicnumberutils.cpp.
Referenced by MusicSongCheckToolsQualityTableWidget::createAllItems(), MusicFileInformationWidget::setFileInformation(), and transfromBitrateToQuality().
void MusicUtils::Number::transfromBitrateToQuality (int level, QString & bitString)
Transfrom bitrate to quality.
Definition at line 146 of file musicnumberutils.cpp.
References transfromBitrateToQuality().
QString MusicUtils::Number::transfromBitrateToQuality (int level)
Transfrom bitrate to quality.
Definition at line 152 of file musicnumberutils.cpp.
References transfromBitrateToQuality().