TTKMusicplayer: MusicKWBackgroundThread Class Reference
MusicKWBackgroundThread Class Reference
The class of kuwo download art background image.
#include <musickwbackgroundthread.h>
Public Slots
void downLoadDataFinished (const QByteArray &bytes)
Public Slots inherited from MusicDownloadBackgroundThread
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWBackgroundThread (const QString &name, const QString &save, QObject *parent=0)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownloadBackgroundThread
MusicDownloadBackgroundThread (const QString &name, const QString &save, QObject *parent=0)
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownloadBackgroundThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicDownloadBackgroundThread
QString m_artName
QString m_savePath
int m_index
int m_counter
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of kuwo download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickwbackgroundthread.h.
Constructor & Destructor Documentation
MusicKWBackgroundThread::MusicKWBackgroundThread (const QString & name, const QString & save, QObject * parent = 0)
Object contsructor provide artist name and save local path.
Definition at line 10 of file musickwbackgroundthread.cpp.
Member Function Documentation
void MusicKWBackgroundThread::downLoadDataFinished (const QByteArray & bytes) slot
Download data from kuwo net finished.
Definition at line 30 of file musickwbackgroundthread.cpp.
References BACKGROUND_DIR_FULL, MusicDownLoadThreadAbstract::Download_BigBG, MusicNetworkAbstract::downLoadDataChanged(), MusicDownloadBackgroundThread::downLoadFinished(), MusicDownloadBackgroundThread::m_counter, M_LOGGER_ERROR, MusicDownloadBackgroundThread::m_savePath, QJson::Parser::parse(), SKN_FILE, and MusicDataDownloadThread::startToDownload().
Referenced by startToDownload().
QString MusicKWBackgroundThread::getClassName () static
Get class object name.
Definition at line 17 of file musickwbackgroundthread.cpp.
void MusicKWBackgroundThread::startToDownload () override virtual
Start to download artist picture from net.
Set search image API
Implements MusicDownloadBackgroundThread.
Definition at line 22 of file musickwbackgroundthread.cpp.
References BIG_ART_URL, downLoadDataFinished(), MusicDownloadBackgroundThread::m_artName, MusicUtils::Algorithm::mdII(), and MusicDownloadSourceThread::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/kw/musickwbackgroundthread.h
TTKModule/TTKCore/musicNetworkKits/kw/musickwbackgroundthread.cpp