TTKMusicplayer: MusicUserDialog Class Reference
MusicUserDialog Class Reference
The class of the user dialog.
#include <musicuserdialog.h>
Public Slots
void userLogin ()
void checkUserLogin ()
void registerUser ()
void checkRegisterUser ()
void userForgotPasswd ()
void checkUserForgotPasswd ()
void changeVerificationCode ()
void userComboBoxChanged (const QString &name)
void userEditTextChanged (const QString &name)
void buttonClicked (int index)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void userLoginSuccess (const QString &uid, const QString &icon)
Public Member Functions
MusicUserDialog (QWidget *parent=0)
~MusicUserDialog ()
void checkToAutoLogin (QString &name, QString &icon)
void setUserModel (MusicUserModel *model)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Member Functions
void firstStatckWidget ()
void secondStatckWidget ()
void thirdStatckWidget ()
void clearOriginData ()
void readFromUserConfig ()
int findUserNameIndex (const QString &name)
void readFromUserSettings ()
void writeToUserConfig ()
void writeToUserSettings ()
void windowRectChanged (int index, int height)
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicUserDialog * m_ui
MusicUserModel * m_userModel
MusicUserRecords m_records
QString m_userName
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the user dialog.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicuserdialog.h.
Constructor & Destructor Documentation
MusicUserDialog::MusicUserDialog (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 13 of file musicuserdialog.cpp.
References buttonClicked(), changeVerificationCode(), firstStatckWidget(), m_ui, m_userName, MusicUIObject::MToolButtonStyle04, readFromUserConfig(), secondStatckWidget(), thirdStatckWidget(), MusicTime::timeSRand(), userComboBoxChanged(), and userEditTextChanged().
MusicUserDialog::~MusicUserDialog ()
Definition at line 52 of file musicuserdialog.cpp.
References m_ui.
Member Function Documentation
void MusicUserDialog::buttonClicked (int index) slot
Other login way, but now there is no supported.
Definition at line 235 of file musicuserdialog.cpp.
References MusicMessageBox::exec(), and MusicMessageBox::setText().
Referenced by MusicUserDialog().
void MusicUserDialog::changeVerificationCode () slot
Set current verification code.
Definition at line 207 of file musicuserdialog.cpp.
References m_ui.
Referenced by MusicUserDialog(), and thirdStatckWidget().
void MusicUserDialog::checkRegisterUser () slot
Check user register mod.
Definition at line 117 of file musicuserdialog.cpp.
References MusicUserModel::addUser(), MusicMessageBox::exec(), m_ui, m_userModel, MusicMessageBox::setText(), and userLogin().
Referenced by secondStatckWidget().
void MusicUserDialog::checkToAutoLogin (QString & name, QString & icon)
Check current user to login auto automatic.
Definition at line 62 of file musicuserdialog.cpp.
References MusicUserModel::getUserIcon(), MusicUserModel::getUserPWDMD5(), m_ui, m_userModel, and m_userName.
Referenced by MusicUserWindow::checkToAutoLogin().
void MusicUserDialog::checkUserForgotPasswd () slot
Check user forgot password mod.
Definition at line 166 of file musicuserdialog.cpp.
References MusicMessageBox::exec(), m_ui, m_userModel, MusicUserModel::mailCheck(), MusicMessageBox::setText(), MusicUserModel::updateUser(), and userLogin().
Referenced by thirdStatckWidget().
void MusicUserDialog::checkUserLogin () slot
Check the current user login state.
Definition at line 83 of file musicuserdialog.cpp.
References MusicMessageBox::exec(), MusicUserModel::getUserIcon(), MusicUserModel::getUserPWDMD5(), m_ui, m_userModel, m_userName, MusicUserModel::passwordCheck(), MusicMessageBox::setText(), userLoginSuccess(), and writeToUserConfig().
Referenced by firstStatckWidget().
void MusicUserDialog::clearOriginData () protected
Clear origin data in need.
Definition at line 340 of file musicuserdialog.cpp.
References m_ui.
Referenced by windowRectChanged().
int MusicUserDialog::exec () virtual slot
Override exec function.
Definition at line 242 of file musicuserdialog.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicUserWindow::musicUserLogin().
int MusicUserDialog::findUserNameIndex (const QString & name) protected
To find current username in the record list.
Definition at line 383 of file musicuserdialog.cpp.
References m_records, and m_userName.
Referenced by readFromUserSettings(), and writeToUserSettings().
void MusicUserDialog::firstStatckWidget () protected
Init user login widget.
Definition at line 248 of file musicuserdialog.cpp.
References checkUserLogin(), m_ui, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MComboBoxStyle01, MusicUIObject::MItemView01, MusicUIObject::MLineEditStyle01, MusicUIObject::MPushButtonStyle04, MusicUIObject::MPushButtonStyle05, MusicUIObject::MScrollBarStyle01, registerUser(), and userForgotPasswd().
Referenced by MusicUserDialog().
QString MusicUserDialog::getClassName () static
Get class object name.
Definition at line 57 of file musicuserdialog.cpp.
void MusicUserDialog::readFromUserConfig () protected
Read user setting to config file.
Definition at line 372 of file musicuserdialog.cpp.
References m_records, readFromUserSettings(), MusicUserConfigManager::readUserConfig(), and MusicUserConfigManager::readUserXMLConfig().
Referenced by MusicUserDialog().
void MusicUserDialog::readFromUserSettings () protected
Read user info from setting.
Definition at line 396 of file musicuserdialog.cpp.
References findUserNameIndex(), m_records, m_ui, and m_userName.
Referenced by readFromUserConfig(), userComboBoxChanged(), and userEditTextChanged().
void MusicUserDialog::registerUser () slot
Change to user register widget.
Definition at line 112 of file musicuserdialog.cpp.
References windowRectChanged().
Referenced by firstStatckWidget().
void MusicUserDialog::secondStatckWidget () protected
Init user register widget.
Definition at line 275 of file musicuserdialog.cpp.
References checkRegisterUser(), m_ui, MusicUserLineEdit::Mail, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MLineEditStyle01, MusicUIObject::MPushButtonStyle04, MusicUIObject::MPushButtonStyle05, MusicUserLineEdit::Passwd, MusicUserLineEdit::PwdConfirm, MusicUserLineEdit::User, and userLogin().
Referenced by MusicUserDialog().
void MusicUserDialog::setUserModel (MusicUserModel * model)
Set user model.
Definition at line 72 of file musicuserdialog.cpp.
References MusicUserModel::getAllUsers(), m_ui, and m_userModel.
Referenced by MusicUserWindow::checkToAutoLogin(), and MusicUserWindow::musicUserLogin().
void MusicUserDialog::thirdStatckWidget () protected
Init user forgot pwd widget.
Definition at line 311 of file musicuserdialog.cpp.
References changeVerificationCode(), checkUserForgotPasswd(), m_ui, MusicUIObject::MLineEditStyle01, MusicUIObject::MPushButtonStyle04, MusicUserLineEdit::Passwd, and userLogin().
Referenced by MusicUserDialog().
void MusicUserDialog::userComboBoxChanged (const QString & name) slot
Selected new user to login.
Definition at line 214 of file musicuserdialog.cpp.
References m_userName, and readFromUserSettings().
Referenced by MusicUserDialog().
void MusicUserDialog::userEditTextChanged (const QString & name) slot
Input a new user to login.
Definition at line 220 of file musicuserdialog.cpp.
References MusicUserModel::getAllUsers(), m_ui, m_userModel, m_userName, and readFromUserSettings().
Referenced by MusicUserDialog().
void MusicUserDialog::userForgotPasswd () slot
Change to user forgot pwd widget.
Definition at line 161 of file musicuserdialog.cpp.
References windowRectChanged().
Referenced by firstStatckWidget().
void MusicUserDialog::userLogin () slot
Change to user login widget.
Definition at line 78 of file musicuserdialog.cpp.
References windowRectChanged().
Referenced by checkRegisterUser(), checkUserForgotPasswd(), secondStatckWidget(), and thirdStatckWidget().
void MusicUserDialog::userLoginSuccess (const QString & uid, const QString & icon) signal
User login success emit.
Referenced by checkUserLogin().
void MusicUserDialog::windowRectChanged (int index, int height) protected
Reset window rect by diff index and geometry.
Definition at line 436 of file musicuserdialog.cpp.
References clearOriginData(), and m_ui.
Referenced by registerUser(), userForgotPasswd(), and userLogin().
void MusicUserDialog::writeToUserConfig () protected
Write user setting to config file.
Definition at line 407 of file musicuserdialog.cpp.
References m_records, writeToUserSettings(), and MusicUserConfigManager::writeUserXMLConfig().
Referenced by checkUserLogin().
void MusicUserDialog::writeToUserSettings () protected
Write user info to setting.
Definition at line 415 of file musicuserdialog.cpp.
References findUserNameIndex(), MusicUserModel::getUserPWDMD5(), MusicUserRecord::m_autoLogin, MusicUserRecord::m_password, m_records, MusicUserRecord::m_rememberPWD, m_ui, m_userModel, MusicUserRecord::m_userName, and m_userName.
Referenced by writeToUserConfig().
Member Data Documentation
MusicUserRecords MusicUserDialog::m_records protected
Definition at line 155 of file musicuserdialog.h.
Referenced by findUserNameIndex(), readFromUserConfig(), readFromUserSettings(), writeToUserConfig(), and writeToUserSettings().
Ui::MusicUserDialog* MusicUserDialog::m_ui protected
Definition at line 153 of file musicuserdialog.h.
Referenced by changeVerificationCode(), checkRegisterUser(), checkToAutoLogin(), checkUserForgotPasswd(), checkUserLogin(), clearOriginData(), exec(), firstStatckWidget(), MusicUserDialog(), readFromUserSettings(), secondStatckWidget(), setUserModel(), thirdStatckWidget(), userEditTextChanged(), windowRectChanged(), writeToUserSettings(), and ~MusicUserDialog().
MusicUserModel* MusicUserDialog::m_userModel protected
Definition at line 154 of file musicuserdialog.h.
Referenced by checkRegisterUser(), checkToAutoLogin(), checkUserForgotPasswd(), checkUserLogin(), setUserModel(), userEditTextChanged(), and writeToUserSettings().
QString MusicUserDialog::m_userName protected
Definition at line 156 of file musicuserdialog.h.
Referenced by checkToAutoLogin(), checkUserLogin(), findUserNameIndex(), MusicUserDialog(), readFromUserSettings(), userComboBoxChanged(), userEditTextChanged(), and writeToUserSettings().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicUserKits/musicuserdialog.h
TTKModule/TTKWidget/musicUserKits/musicuserdialog.cpp