TTKMusicPlayer: TTKObject Namespace Reference
TTKObject Namespace Reference
Functions
TTK_MODULE_EXPORT void killProcessByName (const QString &process)
TTK_MODULE_EXPORT void killProcessByName (const QStringList &processes)
TTK_MODULE_EXPORT void setApplicationFont (QApplication *app)
TTK_MODULE_EXPORT void setBorderShadow (QWidget *widget, QPainter *painter)
TTK_MODULE_EXPORT void initRandom ()
TTK_MODULE_EXPORT int random (int value=RAND_MAX)
Function Documentation
void TTKObject::initRandom ()
Init random value seed.
Definition at line 7 of file ttktime.cpp.
Referenced by MusicBarrageWidget::addBarrage(), MusicBarrageWidget::createLabel(), QAlgorithm::CubeWavePrivate::CubeWavePrivate(), MusicDesktopWallpaperThread::MusicDesktopWallpaperThread(), MusicDiscoverListRequest::MusicDiscoverListRequest(), MusicMPRISPlayerCore::MusicMPRISPlayerCore(), MusicNetworkTestThread::MusicNetworkTestThread(), MusicPlaylist::MusicPlaylist(), MusicTransitionAnimationLabel::MusicTransitionAnimationLabel(), and MusicVideoSearchTableWidget::MusicVideoSearchTableWidget().
TTK_MODULE_EXPORT void TTKObject::killProcessByName (const QString & process)
Kill process by name.
Referenced by cleanAppicationCache(), and MusicCoreMPlayer::closeModule().
TTK_MODULE_EXPORT void TTKObject::killProcessByName (const QStringList & processes)
Kill process by name list.
int TTKObject::random (int value = RAND_MAX)
Get random value.
Definition at line 14 of file ttktime.cpp.
Referenced by MusicBarrageAnimation::animationFinished(), MusicScreenSaverBackgroundWidget::backgroundTimeout(), MusicAlbumQueryWidget::createLabels(), MusicArtistQueryWidget::createLabels(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicBarrageAnimation::initialize(), QAlgorithm::CubeWave::input(), MusicItemSearchTableWidget::randSimulation(), MusicNetworkTestThread::run(), MusicPlaylist::setCurrentIndex(), MusicTransitionAnimationLabel::setPixmap(), MusicDesktopWallpaperThread::setRandom(), MusicPlaylistQueryInfoWidget::setResultDataItem(), MusicBarrageAnimation::setSize(), MusicDesktopWallpaperThread::timeout(), and MusicMPRISPlayerCore::updateTrackID().
void TTKObject::setApplicationFont (QApplication * app)
Set application font.
Definition at line 10 of file ttkglobalhelper.cpp.
References TTK_INFO_STREAM.
Referenced by main().
void TTKObject::setBorderShadow (QWidget * widget, QPainter * painter)
Set widget border shadow.
Definition at line 25 of file ttkglobalhelper.cpp.
References HEIGHT, and WIDTH.
Referenced by TTKAbstractMoveDialog::paintEvent(), TTKAbstractMoveWidget::paintEvent(), MusicProgressWidget::paintEvent(), and MusicScreenSaverHoverItem::paintEvent().