TTKMusicplayer: Visual Class Reference
Visual Class Reference abstract
The Visual class provides the base interface class of visualizations.
#include <visual.h>
Signals
void closedByUser ()
void closedByUser ()
Public Member Functions
Visual (QWidget *parent, Qt::WindowFlags f=0)
virtual ~Visual ()
virtual void add (float *data, size_t samples, int chan)=0
virtual void clear ()=0
QMutex * mutex ()
Visual (QWidget *parent, Qt::WindowFlags f=0)
virtual ~Visual ()
virtual void add (float *data, size_t samples, int chan)=0
virtual void clear ()=0
QMutex * mutex ()
Static Public Member Functions
static QList< VisualFactory * > factories ()
static QString file (VisualFactory *factory)
static void setEnabled (VisualFactory *factory, bool enable=true)
static bool isEnabled (VisualFactory *factory)
static void add (Visual *visual)
static void remove (Visual *)
static void initialize (QWidget *parent, QObject *receiver=0, const char *member=0)
static QList< Visual * > * visuals ()
static QList< VisualFactory * > factories ()
static QString file (VisualFactory *factory)
static void setEnabled (VisualFactory *factory, bool enable=true)
static bool isEnabled (VisualFactory *factory)
static void add (Visual *visual)
static void remove (Visual *)
static void initialize (QWidget *parent, QObject *receiver=0, const char *member=0)
static QList< Visual * > * visuals ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event)
virtual void closeEvent (QCloseEvent *event)
Static Private Member Functions
static void checkFactories ()
static void checkFactories ()
Private Attributes
Decoder * m_decoder
Output * m_output
QMutex m_mutex
Static Private Attributes
static QList< VisualFactory * > * m_factories
static QHash< VisualFactory *, QString > * m_files
static QList< Visual * > m_visuals
static QHash< VisualFactory *, Visual * > m_vis_map
static QWidget * m_parentWidget
static QObject * m_receiver
static const char * m_member
Detailed Description
The Visual class provides the base interface class of visualizations.
Author
Ilya Kotov forko.nosp@m.tov0.nosp@m.2@hot.nosp@m.mail.nosp@m..ru
Definition at line 37 of file visual.h.
Constructor & Destructor Documentation
Visual::Visual (QWidget * parent, Qt::WindowFlags f = 0)
Object contsructor.
Parameters
parent Parent object.
f Widget flags.
virtual Visual::~Visual () virtual
Destructor.
Visual::Visual (QWidget * parent, Qt::WindowFlags f = 0)
Object contsructor.
Parameters
parent Parent object.
f Widget flags.
virtual Visual::~Visual () virtual
Destructor.
Member Function Documentation
virtual void Visual::add (float * data, size_t samples, int chan) pure virtual
Adds data for visualization. Subclass should reimplement this function.
Parameters
data Audio data.
samples Number of samples.
chan Number of channels.
virtual void Visual::add (float * data, size_t samples, int chan) pure virtual
Adds data for visualization. Subclass should reimplement this function.
Parameters
data Audio data.
samples Number of samples.
chan Number of channels.
static void Visual::add (Visual * visual) static
Adds external visualization visual.
static void Visual::add (Visual * visual) static
Adds external visualization visual.
static void Visual::checkFactories () static private
static void Visual::checkFactories () static private
virtual void Visual::clear () pure virtual
Resets visual plugin buffers and widgets. Subclass should reimplement this function.
virtual void Visual::clear () pure virtual
Resets visual plugin buffers and widgets. Subclass should reimplement this function.
void Visual::closedByUser () signal
Emitted when visual widget is closed by user.
void Visual::closedByUser () signal
Emitted when visual widget is closed by user.
virtual void Visual::closeEvent (QCloseEvent * event) protected virtual
QWidget's close event. Reimplementation should call base function.
Parameters
event QCloseEvent insatance.
virtual void Visual::closeEvent (QCloseEvent * event) protected virtual
QWidget's close event. Reimplementation should call base function.
Parameters
event QCloseEvent insatance.
static QList<VisualFactory*> Visual::factories () static
Returns a list of visual factories.
Referenced by MusicRemoteWidgetForRipples::enableRipples(), and MusicSpectrumWidget::showSpectrum().
static QList<VisualFactory*> Visual::factories () static
Returns a list of visual factories.
static QString Visual::file (VisualFactory * factory) static
Returns plugin file path.
Parameters
factory Visual plugin factory.
static QString Visual::file (VisualFactory * factory) static
Returns plugin file path.
Parameters
factory Visual plugin factory.
static void Visual::initialize (QWidget * parent, QObject * receiver = 0, const char * member = 0) static
Prepares visual plugins for usage.
Parameters
parent Parent widget.
receiver Receiver object.
member A slot to receive changes of active visualizations list.
Referenced by MusicLeftAreaWidget::MusicLeftAreaWidget().
static void Visual::initialize (QWidget * parent, QObject * receiver = 0, const char * member = 0) static
Prepares visual plugins for usage.
Parameters
parent Parent widget.
receiver Receiver object.
member A slot to receive changes of active visualizations list.
static bool Visual::isEnabled (VisualFactory * factory) static
Returns true if visual plugin is enabled, otherwise returns false
Parameters
factory Effect plugin factory.
static bool Visual::isEnabled (VisualFactory * factory) static
Returns true if visual plugin is enabled, otherwise returns false
Parameters
factory Effect plugin factory.
QMutex* Visual::mutex ()
Returns mutex pointer.
QMutex* Visual::mutex ()
Returns mutex pointer.
static void Visual::remove (Visual *) static
Removes external visualization visual.
static void Visual::remove (Visual *) static
Removes external visualization visual.
static void Visual::setEnabled (VisualFactory * factory, bool enable = true) static
Sets whether the visual plugin is enabled.
Parameters
factory Visual plugin factory.
enable Plugin enable state (true - enable, false - disable)
Referenced by MusicRemoteWidgetForRipples::enableRipples(), and MusicSpectrumWidget::showSpectrum().
static void Visual::setEnabled (VisualFactory * factory, bool enable = true) static
Sets whether the visual plugin is enabled.
Parameters
factory Visual plugin factory.
enable Plugin enable state (true - enable, false - disable)
static QList<Visual *>* Visual::visuals () static
Returns a pointer to a list of created visual objects.
static QList<Visual *>* Visual::visuals () static
Returns a pointer to a list of created visual objects.
Referenced by MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), and MusicSpectrumWidget::newSpectrumWidget().
Member Data Documentation
Decoder * Visual::m_decoder private
Definition at line 122 of file visual.h.
static QList< VisualFactory * > * Visual::m_factories static private
Definition at line 126 of file visual.h.
static QHash< VisualFactory *, QString > * Visual::m_files static private
Definition at line 127 of file visual.h.
static const char * Visual::m_member static private
Definition at line 133 of file visual.h.
QMutex Visual::m_mutex private
Definition at line 124 of file visual.h.
Output * Visual::m_output private
Definition at line 123 of file visual.h.
static QWidget * Visual::m_parentWidget static private
Definition at line 131 of file visual.h.
static QObject * Visual::m_receiver static private
Definition at line 132 of file visual.h.
static QHash< VisualFactory *, Visual * > Visual::m_vis_map static private
Definition at line 130 of file visual.h.
static QList< Visual * > Visual::m_visuals static private
Definition at line 129 of file visual.h.
The documentation for this class was generated from the following file:
TTKExtra/Qt4/visual.h