TTKMusicplayer: MusicWYArtistSimilarRequest Class Reference
MusicWYArtistSimilarRequest Class Reference
The class of query wangyi artist similar download data from net.
#include <musicwyartistsimilarrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYArtistSimilarRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value) overridefinal
Public Member Functions inherited from MusicSimilarRequest
MusicSimilarRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicSimilarRequest
void createSimilarItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicWYQueryInterface
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type) const
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, int bitrate) const
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, const QVariantMap &key, MusicObject::QueryQuality quality, bool all) const
void readFromMusicSongPropertyNew (MusicObject::MusicSongInformation *info, int bitrate) const
void readFromMusicSongPropertyNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, MusicObject::QueryQuality quality, bool all) const
Detailed Description
The class of query wangyi artist similar download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwyartistsimilarrequest.h.
Constructor & Destructor Documentation
MusicWYArtistSimilarRequest::MusicWYArtistSimilarRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicwyartistsimilarrequest.cpp.
Member Function Documentation
void MusicWYArtistSimilarRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 29 of file musicwyartistsimilarrequest.cpp.
References MusicSimilarRequest::createSimilarItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicAbstractNetwork::m_reply, MusicResultsItem::m_updateTime, QJson::Parser::parse(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicWYArtistSimilarRequest::startToSearch (const QString & value) final override virtual
Start to Search data from name.
Implements MusicSimilarRequest.
Definition at line 9 of file musicwyartistsimilarrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicWYQueryInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), TTK_LOGGER_INFO, WY_ARTIST_SIMILAR_DATA_URL, and WY_ARTIST_SIMILAR_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyartistsimilarrequest.h
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyartistsimilarrequest.cpp