TTKMusicPlayer: MusicCategoryConfigManager Class Reference
MusicCategoryConfigManager Class Reference
The class of the category config manager.
#include <musiccategoryconfigmanager.h>
Public Types
enum Category { Category::PlayList, Category::TopList, Category::ArtistList, Category::MovieList }
Public Member Functions
MusicCategoryConfigManager (const QString &key)
bool fromFile (Category type)
virtual bool readBuffer (MusicResultsCategoryList &items) overridefinal
Public Member Functions inherited from TTKAbstractXml
TTKAbstractXml ()
~TTKAbstractXml ()
bool load (const QString &name)
void save () const
bool reset ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
void createProcessingInstruction () const
QString readAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readTextByTagName (const QString &tagName) const
TTKXmlAttributeList readAttributesByTagName (const QString &tagName) const
QStringList readMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readMultiTextByTagName (const QString &tagName) const
TTKXmlAttributesList readMultiAttributesByTagName (const QString &tagName) const
QDomElement createRoot (const QString &node) const
QDomElement createRoot (const QString &node, const TTKXmlAttribute &attr) const
QDomElement createRoot (const QString &node, const TTKXmlAttributeList &attrs) const
QDomElement writeDomElement (QDomElement &element, const QString &node) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const QString &text) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr, const QString &text) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs, const QString &text) const
void writeAttribute (QDomElement &element, const TTKXmlAttribute &attr) const
void writeAttribute (QDomElement &element, const TTKXmlAttributeList &attr) const
Private Attributes
QString m_type
Additional Inherited Members
Protected Attributes inherited from TTKAbstractXml
QFile * m_file
QDomDocument * m_document
Private Member Functions inherited from TTKAbstractReadInterface< MusicResultsCategoryList >
virtual ~TTKAbstractReadInterface ()=default
Detailed Description
The class of the category config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 49 of file musiccategoryconfigmanager.h.
Member Enumeration Documentation
enum MusicCategoryConfigManager::Category strong
Enumerator
PlayList
PlayList Category
TopList
TopList Category
ArtistList
ArtistList Category
MovieList
MovieList Category
Definition at line 53 of file musiccategoryconfigmanager.h.
Constructor & Destructor Documentation
MusicCategoryConfigManager::MusicCategoryConfigManager (const QString & key) explicit
Object constructor.
Definition at line 3 of file musiccategoryconfigmanager.cpp.
Member Function Documentation
bool MusicCategoryConfigManager::fromFile (Category type)
Read datas from xml file by given name.
Definition at line 10 of file musiccategoryconfigmanager.cpp.
References ArtistList, TTKAbstractXml::fromFile(), MovieList, PlayList, and TopList.
Referenced by MusicWebMVRadioQueryCategoryPopWidget::setCategory(), MusicToplistQueryCategoryPopWidget::setCategory(), MusicPlaylistFoundCategoryPopWidget::setCategory(), and MusicArtistListQueryCategoryPopWidget::setCategory().
bool MusicCategoryConfigManager::readBuffer (MusicResultsCategoryList & items) final override virtual
Read datas from buffer.
Implements TTKAbstractReadInterface< MusicResultsCategoryList >.
Definition at line 25 of file musiccategoryconfigmanager.cpp.
References MusicResultsCategory::m_category, TTKAbstractXml::m_document, MusicResultsCategory::m_items, MusicResultsCategoryItem::m_key, m_type, and MusicResultsCategoryItem::m_value.
Referenced by MusicWebMVRadioQueryCategoryPopWidget::setCategory(), MusicToplistQueryCategoryPopWidget::setCategory(), MusicPlaylistFoundCategoryPopWidget::setCategory(), and MusicArtistListQueryCategoryPopWidget::setCategory().
Member Data Documentation
QString MusicCategoryConfigManager::m_type private
Definition at line 77 of file musiccategoryconfigmanager.h.
Referenced by readBuffer().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musiccategoryconfigmanager.h
TTKModule/TTKCore/musicCoreKits/musiccategoryconfigmanager.cpp