TTKMusicPlayer: MusicWebMVRadioQueryCategoryPopWidget Class Reference
MusicWebMVRadioQueryCategoryPopWidget Class Reference
The class of the music mv category pop widget.
#include <musicwebmvradioquerycategorypopwidget.h>
Public Slots
virtual void popupMenu () overridefinal
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicWebMVRadioQueryCategoryPopWidget (QWidget *parent=nullptr)
void setCategory (const QString &server, QObject *obj)
void closeMenu ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Private Member Functions
void initialize ()
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the music mv category pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 65 of file musicwebmvradioquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioQueryCategoryPopWidget::MusicWebMVRadioQueryCategoryPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 58 of file musicwebmvradioquerycategorypopwidget.cpp.
References initialize().
Member Function Documentation
void MusicWebMVRadioQueryCategoryPopWidget::closeMenu ()
Close the menu dialog.
Definition at line 91 of file musicwebmvradioquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
Referenced by MusicWebMVRadioQueryWidget::categoryChanged().
void MusicWebMVRadioQueryCategoryPopWidget::initialize () private
Create all widget in layout.
Definition at line 101 of file musicwebmvradioquerycategorypopwidget.cpp.
References TTK::UI::BackgroundStyle10, TTK::UI::BorderStyle03, MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, TTK::UI::MenuStyle05, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicWebMVRadioQueryCategoryPopWidget().
void MusicWebMVRadioQueryCategoryPopWidget::popupMenu () final override virtual slot
To popup menu.
Definition at line 96 of file musicwebmvradioquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
void MusicWebMVRadioQueryCategoryPopWidget::setCategory (const QString & server, QObject * obj)
Set current category by input server.
Definition at line 64 of file musicwebmvradioquerycategorypopwidget.cpp.
References TTK::UI::BackgroundStyle10, MusicCategoryConfigManager::fromFile(), TTK::Widget::generateVScrollAreaFormat(), MusicToolMenuWidget::m_containWidget, MusicCategoryConfigManager::MovieList, MusicCategoryConfigManager::readBuffer(), and MusicWebMVRadioQueryCategoryItem::setCategory().
Referenced by MusicWebMVRadioQueryWidget::createMVRadioCategoryItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerycategorypopwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerycategorypopwidget.cpp