TTKMusicplayer: MusicPhotoGrabLabel Class Reference
MusicPhotoGrabLabel Class Reference
The class of the photo grab label.
#include <musicphotograblabel.h>
Public Slots
void rectChanged ()
Signals
void intersectedPixmap (const QPixmap &pix)
Public Member Functions
MusicPhotoGrabLabel (QWidget *parent=nullptr)
~MusicPhotoGrabLabel ()
void setImagePath (const QString &path)
QPixmap pixmap ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
Protected Attributes
float m_ratio
QString m_path
QRect m_imgRect
MusicPhotoGrabItem * m_grabItem
Detailed Description
The class of the photo grab label.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 49 of file musicphotograblabel.h.
Constructor & Destructor Documentation
MusicPhotoGrabLabel::MusicPhotoGrabLabel (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 26 of file musicphotograblabel.cpp.
References m_grabItem, m_ratio, rectChanged(), and MusicResizeGrabItemWidget::setGeometricStretch().
MusicPhotoGrabLabel::~MusicPhotoGrabLabel ()
Definition at line 36 of file musicphotograblabel.cpp.
References m_grabItem.
Member Function Documentation
void MusicPhotoGrabLabel::intersectedPixmap (const QPixmap & pix) signal
Send intersected pixmap if intersected flag set.
Referenced by rectChanged().
void MusicPhotoGrabLabel::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 75 of file musicphotograblabel.cpp.
References m_imgRect, m_path, PIX_HEIGHT, and PIX_WIDTH.
QPixmap MusicPhotoGrabLabel::pixmap ()
Get changed pixmap.
Definition at line 64 of file musicphotograblabel.cpp.
References m_grabItem, m_imgRect, m_path, and m_ratio.
Referenced by rectChanged().
void MusicPhotoGrabLabel::rectChanged () slot
Current rect changed.
Definition at line 70 of file musicphotograblabel.cpp.
References intersectedPixmap(), and pixmap().
Referenced by MusicPhotoGrabLabel().
void MusicPhotoGrabLabel::setImagePath (const QString & path)
Set song image path.
Definition at line 41 of file musicphotograblabel.cpp.
References m_grabItem, m_imgRect, m_path, m_ratio, and MusicPhotoGrabItem::setBorderRect().
Member Data Documentation
MusicPhotoGrabItem* MusicPhotoGrabLabel::m_grabItem protected
Definition at line 90 of file musicphotograblabel.h.
Referenced by MusicPhotoGrabLabel(), pixmap(), setImagePath(), and ~MusicPhotoGrabLabel().
QRect MusicPhotoGrabLabel::m_imgRect protected
Definition at line 89 of file musicphotograblabel.h.
Referenced by paintEvent(), pixmap(), and setImagePath().
QString MusicPhotoGrabLabel::m_path protected
Definition at line 88 of file musicphotograblabel.h.
Referenced by paintEvent(), pixmap(), and setImagePath().
float MusicPhotoGrabLabel::m_ratio protected
Definition at line 87 of file musicphotograblabel.h.
Referenced by MusicPhotoGrabLabel(), pixmap(), and setImagePath().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicphotograblabel.h
TTKModule/TTKWidget/musicCoreKits/musicphotograblabel.cpp