TTKMusicplayer: MusicArtistListFoundWidget Class Reference
MusicArtistListFoundWidget Class Reference
The class of the artist list music found widget.
#include <musicartistlistfoundwidget.h>
Public Slots
void createArtistListItem (const MusicResultsItem &item)
void currentArtistListClicked (const MusicResultsItem &item)
void categoryChanged (const MusicResultsCategoryItem &category)
void buttonClicked (int index)
void numberButtonClicked (int index)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistListFoundWidget (QWidget *parent=0)
virtual ~MusicArtistListFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
void initWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Attributes
bool m_firstInit
bool m_categoryChanged
QString m_categoryId
QGridLayout * m_gridLayout
MusicPagingWidgetObject * m_pagingWidgetObject
MusicArtistListFoundCategoryPopWidget * m_categoryButton
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the artist list music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 74 of file musicartistlistfoundwidget.h.
Constructor & Destructor Documentation
MusicArtistListFoundWidget::MusicArtistListFoundWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 47 of file musicartistlistfoundwidget.cpp.
References createArtistListItem(), m_categoryButton, m_categoryChanged, MusicFoundAbstractWidget::m_container, M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, and m_pagingWidgetObject.
MusicArtistListFoundWidget::~MusicArtistListFoundWidget () virtual
Definition at line 64 of file musicartistlistfoundwidget.cpp.
References m_categoryButton, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, and m_pagingWidgetObject.
Member Function Documentation
void MusicArtistListFoundWidget::buttonClicked (int index) slot
Paging widget button has changed.
Definition at line 213 of file musicartistlistfoundwidget.cpp.
References MusicPagingWidgetObject::currentIndex(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicPagingWidgetObject::paging(), and MusicDownLoadPagingThread::startToPage().
Referenced by createArtistListItem().
void MusicArtistListFoundWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 199 of file musicartistlistfoundwidget.cpp.
References MusicArtistListFoundCategoryPopWidget::closeMenu(), m_categoryButton, m_categoryId, MusicResultsCategoryItem::m_id, MusicResultsCategoryItem::m_name, MusicFoundAbstractWidget::m_songNameFull, and numberButtonClicked().
void MusicArtistListFoundWidget::createArtistListItem (const MusicResultsItem & item) slot
Query all quality musics is finished.
Definition at line 105 of file musicartistlistfoundwidget.cpp.
References buttonClicked(), MusicPagingWidgetObject::createPagingWidget(), currentArtistListClicked(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicDownLoadQueryThreadAbstract::getQueryServer(), LINE_SPACING_SIZE, m_categoryButton, m_categoryChanged, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_statusLabel, MusicUIObject::MColorStyle06, MusicUIObject::MColorStyle08, MusicUIObject::MColorStyle11, MusicUIObject::MScrollBarStyle01, MStatic_cast, numberButtonClicked(), MusicPagingWidgetObject::reset(), MusicArtistListFoundCategoryPopWidget::setCategory(), and MusicArtistListFoundItemWidget::setMusicResultsItem().
Referenced by MusicArtistListFoundWidget().
void MusicArtistListFoundWidget::currentArtistListClicked (const MusicResultsItem & item) slot
Current artist list clicked.
Definition at line 194 of file musicartistlistfoundwidget.cpp.
References MusicRightAreaWidget::instance(), MusicResultsItem::m_id, and MusicRightAreaWidget::musicArtistSearch().
Referenced by createArtistListItem().
QString MusicArtistListFoundWidget::getClassName () static
Get class object name.
Definition at line 72 of file musicartistlistfoundwidget.cpp.
void MusicArtistListFoundWidget::numberButtonClicked (int index) slot
Number type button has changed.
Definition at line 227 of file musicartistlistfoundwidget.cpp.
References m_categoryChanged, m_categoryId, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, MusicFoundAbstractWidget::m_resizeWidgets, MusicDownLoadQueryThreadAbstract::OtherQuery, MusicDownLoadQueryThreadAbstract::startToSearch(), and STRING_SPLITER.
Referenced by categoryChanged(), and createArtistListItem().
void MusicArtistListFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 88 of file musicartistlistfoundwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and MusicFoundAbstractWidget::m_resizeWidgets.
void MusicArtistListFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 77 of file musicartistlistfoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicDownLoadQueryThreadAbstract::OtherQuery, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by setSongNameById().
void MusicArtistListFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 83 of file musicartistlistfoundwidget.cpp.
References setSongName().
Member Data Documentation
MusicArtistListFoundCategoryPopWidget* MusicArtistListFoundWidget::m_categoryButton protected
Definition at line 131 of file musicartistlistfoundwidget.h.
Referenced by categoryChanged(), createArtistListItem(), MusicArtistListFoundWidget(), and ~MusicArtistListFoundWidget().
bool MusicArtistListFoundWidget::m_categoryChanged protected
Definition at line 127 of file musicartistlistfoundwidget.h.
Referenced by createArtistListItem(), MusicArtistListFoundWidget(), and numberButtonClicked().
QString MusicArtistListFoundWidget::m_categoryId protected
Definition at line 128 of file musicartistlistfoundwidget.h.
Referenced by categoryChanged(), and numberButtonClicked().
bool MusicArtistListFoundWidget::m_firstInit protected
Definition at line 127 of file musicartistlistfoundwidget.h.
Referenced by createArtistListItem(), and MusicArtistListFoundWidget().
QGridLayout* MusicArtistListFoundWidget::m_gridLayout protected
Definition at line 129 of file musicartistlistfoundwidget.h.
Referenced by buttonClicked(), createArtistListItem(), MusicArtistListFoundWidget(), numberButtonClicked(), resizeWindow(), and ~MusicArtistListFoundWidget().
MusicPagingWidgetObject* MusicArtistListFoundWidget::m_pagingWidgetObject protected
Definition at line 130 of file musicartistlistfoundwidget.h.
Referenced by buttonClicked(), createArtistListItem(), MusicArtistListFoundWidget(), and ~MusicArtistListFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistfoundwidget.cpp