TTKMusicplayer: MusicWebFMRadioPlayWidget Class Reference
MusicWebFMRadioPlayWidget Class Reference
The class of the web music radio widget.
#include <musicwebfmradioplaywidget.h>
Public Slots
void mediaAutionPlayError (int code)
void radioPlay ()
void radioPrevious ()
void radioNext ()
void radioVolume (int num)
void radioResourceDownload ()
void querySongInfoFinished ()
void lrcDownloadStateChanged ()
void picDownloadStateChanged ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicWebFMRadioPlayWidget (QWidget *parent=nullptr)
~MusicWebFMRadioPlayWidget ()
void updateRadioSong (const QString &id)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) overridefinal
void createCoreModule ()
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
Ui::MusicWebFMRadioPlayWidget * m_ui
bool m_isPlaying
QString m_currentIndex
MusicLrcAnalysis * m_analysis
MusicCoreMPlayer * m_player
MusicFMRadioSongsRequest * m_songThread
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the web music radio widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicwebfmradioplaywidget.h.
Constructor & Destructor Documentation
MusicWebFMRadioPlayWidget::MusicWebFMRadioPlayWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicwebfmradioplaywidget.cpp.
References createCoreModule(), m_analysis, m_isPlaying, m_ui, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSBtnUnDownload, MusicUIObject::MQSSSliderStyle10, MusicUIObject::MQSSToolButtonStyle04, MusicUtils::Widget::positionInCenter(), radioNext(), radioPlay(), radioPrevious(), radioResourceDownload(), radioVolume(), and MusicLrcAnalysis::setLineMax().
MusicWebFMRadioPlayWidget::~MusicWebFMRadioPlayWidget ()
Definition at line 68 of file musicwebfmradioplaywidget.cpp.
References m_analysis, m_player, m_songThread, and m_ui.
Member Function Documentation
void MusicWebFMRadioPlayWidget::closeEvent (QCloseEvent * event) final override protected virtual
Override the widget event.
Definition at line 210 of file musicwebfmradioplaywidget.cpp.
References m_player.
void MusicWebFMRadioPlayWidget::createCoreModule () protected
Create core module.
Definition at line 217 of file musicwebfmradioplaywidget.cpp.
References durationChanged(), m_player, m_songThread, mediaAutionPlayError(), positionChanged(), and querySongInfoFinished().
Referenced by MusicWebFMRadioPlayWidget(), and querySongInfoFinished().
void MusicWebFMRadioPlayWidget::durationChanged (qint64 duration) slot
Current duration changed.
Definition at line 311 of file musicwebfmradioplaywidget.cpp.
References m_player, m_ui, MusicTime::msecTime2LabelJustified(), and MT_S2MS.
Referenced by createCoreModule().
void MusicWebFMRadioPlayWidget::lrcDownloadStateChanged () slot
Lrc download state changed.
Definition at line 228 of file musicwebfmradioplaywidget.cpp.
References LRC_FILE, MusicUtils::String::lrcDirPrefix(), m_analysis, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, m_songThread, m_ui, name, MusicLrcAnalysis::readFromLrcFile(), and MusicFMRadioSongsRequest::songInfo().
Referenced by querySongInfoFinished().
void MusicWebFMRadioPlayWidget::mediaAutionPlayError (int code) slot
Media aution play error.
Definition at line 82 of file musicwebfmradioplaywidget.cpp.
References DEFAULT_LOW_LEVEL, and radioNext().
Referenced by createCoreModule().
void MusicWebFMRadioPlayWidget::picDownloadStateChanged () slot
Small pic download state changed.
Definition at line 246 of file musicwebfmradioplaywidget.cpp.
References ART_DIR_FULL, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songProps, m_songThread, m_ui, MusicUtils::Image::pixmapToRound(), SKN_FILE, and MusicFMRadioSongsRequest::songInfo().
Referenced by querySongInfoFinished().
void MusicWebFMRadioPlayWidget::positionChanged (qint64 position) slot
Current position changed.
Definition at line 270 of file musicwebfmradioplaywidget.cpp.
References MusicLrcAnalysis::currentIndex(), MusicLrcAnalysis::findTime(), MusicLrcAnalysis::isEmpty(), MusicLrcAnalysis::lineMax(), MusicLrcAnalysis::lineMiddle(), m_analysis, m_player, m_ui, MusicTime::msecTime2LabelJustified(), MT_S2MS, MusicLrcAnalysis::setCurrentIndex(), and MusicLrcAnalysis::text().
Referenced by createCoreModule().
void MusicWebFMRadioPlayWidget::querySongInfoFinished () slot
Query song information finished.
fix current play volume temporary
Definition at line 158 of file musicwebfmradioplaywidget.cpp.
References ART_DIR_FULL, createCoreModule(), MusicObject::DownloadLrc, MusicObject::DownloadSmallBackground, LRC_FILE, MusicUtils::String::lrcDirPrefix(), lrcDownloadStateChanged(), MusicObject::MusicSongInformation::m_coverUrl, m_isPlaying, MusicObject::MusicSongInformation::m_lrcUrl, m_player, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, m_songThread, m_ui, MusicCoreMPlayer::MusicCategory, name, picDownloadStateChanged(), MusicCoreMPlayer::play(), MusicCoreMPlayer::setMedia(), SKN_FILE, MusicFMRadioSongsRequest::songInfo(), MusicDownloadDataRequest::startToDownload(), and MusicFMRadioDownLoadTextRequest::startToDownload().
Referenced by createCoreModule().
void MusicWebFMRadioPlayWidget::radioNext () slot
Set radio to next.
Definition at line 117 of file musicwebfmradioplaywidget.cpp.
References m_currentIndex, m_isPlaying, m_songThread, m_ui, and MusicFMRadioSongsRequest::startToDownload().
Referenced by mediaAutionPlayError(), and MusicWebFMRadioPlayWidget().
void MusicWebFMRadioPlayWidget::radioPlay () slot
Set radio to play.
Definition at line 90 of file musicwebfmradioplaywidget.cpp.
References m_isPlaying, m_player, m_ui, and MusicCoreMPlayer::play().
Referenced by MusicWebFMRadioPlayWidget().
void MusicWebFMRadioPlayWidget::radioPrevious () slot
Set radio to previous.
Definition at line 102 of file musicwebfmradioplaywidget.cpp.
References m_currentIndex, m_isPlaying, m_songThread, m_ui, and MusicFMRadioSongsRequest::startToDownload().
Referenced by MusicWebFMRadioPlayWidget().
void MusicWebFMRadioPlayWidget::radioResourceDownload () slot
Radio resource download.
Definition at line 140 of file musicwebfmradioplaywidget.cpp.
References MusicObject::MusicSongInformation::m_songProps, m_songThread, MusicAbstractQueryRequest::MusicQuery, MusicDownloadWidget::setSongName(), MusicDownloadWidget::show(), and MusicFMRadioSongsRequest::songInfo().
Referenced by MusicWebFMRadioPlayWidget().
void MusicWebFMRadioPlayWidget::radioVolume (int num) slot
Set radio volume.
Definition at line 132 of file musicwebfmradioplaywidget.cpp.
References m_player, and MusicCoreMPlayer::setVolume().
Referenced by MusicWebFMRadioPlayWidget().
void MusicWebFMRadioPlayWidget::show () slot
Override show function.
Definition at line 320 of file musicwebfmradioplaywidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicWebFMRadioWidget::itemDoubleClicked().
void MusicWebFMRadioPlayWidget::updateRadioSong (const QString & id)
Update radio song by given id.
Definition at line 76 of file musicwebfmradioplaywidget.cpp.
References m_currentIndex, m_songThread, and MusicFMRadioSongsRequest::startToDownload().
Referenced by MusicWebFMRadioWidget::itemDoubleClicked().
Member Data Documentation
MusicLrcAnalysis* MusicWebFMRadioPlayWidget::m_analysis protected
Definition at line 114 of file musicwebfmradioplaywidget.h.
Referenced by lrcDownloadStateChanged(), MusicWebFMRadioPlayWidget(), positionChanged(), and ~MusicWebFMRadioPlayWidget().
QString MusicWebFMRadioPlayWidget::m_currentIndex protected
Definition at line 113 of file musicwebfmradioplaywidget.h.
Referenced by radioNext(), radioPrevious(), and updateRadioSong().
bool MusicWebFMRadioPlayWidget::m_isPlaying protected
Definition at line 112 of file musicwebfmradioplaywidget.h.
Referenced by MusicWebFMRadioPlayWidget(), querySongInfoFinished(), radioNext(), radioPlay(), and radioPrevious().
MusicCoreMPlayer* MusicWebFMRadioPlayWidget::m_player protected
Definition at line 115 of file musicwebfmradioplaywidget.h.
Referenced by closeEvent(), createCoreModule(), durationChanged(), positionChanged(), querySongInfoFinished(), radioPlay(), radioVolume(), and ~MusicWebFMRadioPlayWidget().
MusicFMRadioSongsRequest* MusicWebFMRadioPlayWidget::m_songThread protected
Definition at line 116 of file musicwebfmradioplaywidget.h.
Referenced by createCoreModule(), lrcDownloadStateChanged(), picDownloadStateChanged(), querySongInfoFinished(), radioNext(), radioPrevious(), radioResourceDownload(), updateRadioSong(), and ~MusicWebFMRadioPlayWidget().
Ui::MusicWebFMRadioPlayWidget* MusicWebFMRadioPlayWidget::m_ui protected
Definition at line 111 of file musicwebfmradioplaywidget.h.
Referenced by durationChanged(), lrcDownloadStateChanged(), MusicWebFMRadioPlayWidget(), picDownloadStateChanged(), positionChanged(), querySongInfoFinished(), radioNext(), radioPlay(), radioPrevious(), show(), and ~MusicWebFMRadioPlayWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebfmradioplaywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebfmradioplaywidget.cpp