TTKMusicplayer: MusicSoundEffectsWidget Class Reference
MusicSoundEffectsWidget Class Reference
The class of the sound effect widget.
#include <musicsoundeffectswidget.h>
Public Slots
void equalizerButtonChanged (bool state)
void equalizerButtonChanged ()
void stateComboBoxChanged (int index)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void setEqInformation ()
Public Member Functions
MusicSoundEffectsWidget (QWidget *parent=nullptr)
~MusicSoundEffectsWidget ()
void setInputObject (QObject *object)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void readSoundEffect ()
void writeSoundEffect ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicSoundEffectsWidget * m_ui
QList< MusicSoundEffectsItemWidget * > m_items
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the sound effect widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 82 of file musicsoundeffectswidget.h.
Constructor & Destructor Documentation
MusicSoundEffectsWidget::MusicSoundEffectsWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 126 of file musicsoundeffectswidget.cpp.
References G_CONNECTION_PTR, MusicUtils::Widget::generateVScrollAreaFormat(), m_ui, MusicUIObject::MQSSComboBoxStyle01, MusicUIObject::MQSSItemView01, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSScrollBarStyle01, MusicUIObject::MQSSToolButtonStyle04, readSoundEffect(), and stateComboBoxChanged().
MusicSoundEffectsWidget::~MusicSoundEffectsWidget ()
Definition at line 161 of file musicsoundeffectswidget.cpp.
References G_CONNECTION_PTR, m_items, m_ui, and writeSoundEffect().
Member Function Documentation
void MusicSoundEffectsWidget::equalizerButtonChanged (bool state) slot
Equalizer button state changed.
Definition at line 184 of file musicsoundeffectswidget.cpp.
References m_ui.
void MusicSoundEffectsWidget::equalizerButtonChanged () slot
Equalizer button state changed.
Definition at line 189 of file musicsoundeffectswidget.cpp.
References MusicSettingManager::EqualizerEnable, G_SETTING_PTR, and setEqInformation().
Referenced by setInputObject().
int MusicSoundEffectsWidget::exec () virtual slot
Override exec function.
Definition at line 214 of file musicsoundeffectswidget.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicApplicationModule::musicSetSoundEffect().
void MusicSoundEffectsWidget::readSoundEffect () protected
Read sound effect function.
Definition at line 220 of file musicsoundeffectswidget.cpp.
References MusicUtils::QMMP::effectPlugins(), MusicSettingManager::EnhancedEffectValue, G_SETTING_PTR, m_items, m_ui, and MusicSoundEffectsItemWidget::setPluginEnabled().
Referenced by MusicSoundEffectsWidget().
void MusicSoundEffectsWidget::setEqInformation () signal
Read equalizer effect from config file.
Referenced by equalizerButtonChanged().
void MusicSoundEffectsWidget::setInputObject (QObject * object)
Set input connection.
Definition at line 169 of file musicsoundeffectswidget.cpp.
References equalizerButtonChanged(), MusicSettingManager::EqualizerEnable, G_SETTING_PTR, and m_ui.
Referenced by MusicApplicationModule::musicSetSoundEffect().
void MusicSoundEffectsWidget::stateComboBoxChanged (int index) slot
State combobox index changed.
Definition at line 199 of file musicsoundeffectswidget.cpp.
References m_items, and m_ui.
Referenced by MusicSoundEffectsWidget().
void MusicSoundEffectsWidget::writeSoundEffect () protected
Write sound effect function.
Definition at line 246 of file musicsoundeffectswidget.cpp.
References MusicSettingManager::EnhancedEffectValue, G_SETTING_PTR, and m_items.
Referenced by ~MusicSoundEffectsWidget().
Member Data Documentation
QList<MusicSoundEffectsItemWidget*> MusicSoundEffectsWidget::m_items protected
Definition at line 133 of file musicsoundeffectswidget.h.
Referenced by readSoundEffect(), stateComboBoxChanged(), writeSoundEffect(), and ~MusicSoundEffectsWidget().
Ui::MusicSoundEffectsWidget* MusicSoundEffectsWidget::m_ui protected
Definition at line 132 of file musicsoundeffectswidget.h.
Referenced by equalizerButtonChanged(), exec(), MusicSoundEffectsWidget(), readSoundEffect(), setInputObject(), stateComboBoxChanged(), and ~MusicSoundEffectsWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsoundeffectswidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsoundeffectswidget.cpp