TTKMusicplayer: MusicQQTextDownLoadThread Class Reference
MusicQQTextDownLoadThread Class Reference
The class of downloading the type of qq txt.
#include <musicqqtextdownloadthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicDownLoadThreadAbstract
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicQQTextDownLoadThread (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownLoadThreadAbstract
MusicDownLoadThreadAbstract (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
virtual ~MusicDownLoadThreadAbstract ()
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Additional Inherited Members
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicDownLoadThreadAbstract
QString transferData () const
Protected Attributes inherited from MusicDownLoadThreadAbstract
QFile * m_file
QString m_url
QString m_savePathName
MusicObject::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_timer
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of downloading the type of qq txt.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicqqtextdownloadthread.h.
Constructor & Destructor Documentation
MusicQQTextDownLoadThread::MusicQQTextDownLoadThread (const QString & url, const QString & save, MusicObject::DownloadType type, QObject * parent = nullptr)
Object contsructor provide download URL\ save local path and download type.
Definition at line 9 of file musicqqtextdownloadthread.cpp.
Member Function Documentation
void MusicQQTextDownLoadThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 47 of file musicqqtextdownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_ERROR, M_LOGGER_INFO, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_timer, QJson::Parser::parse(), MusicUtils::Codec::toUtf8(), and MusicDownLoadThreadAbstract::transferData().
Referenced by startToDownload().
void MusicQQTextDownLoadThread::startToDownload () override virtual
Start to download data.
Implements MusicDownLoadThreadAbstract.
Definition at line 15 of file musicqqtextdownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), downLoadFinished(), MusicDownLoadThreadAbstract::downloadProgress(), HOST_URL, MusicDownLoadThreadAbstract::m_file, M_LOGGER_ERROR, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_timer, MusicDownLoadThreadAbstract::m_url, MusicUtils::Algorithm::mdII(), MT_S2MS, MusicObject::NetworkError, REFER_URL, MusicDownLoadThreadAbstract::replyError(), MusicObject::setSslConfiguration(), MusicDownLoadThreadAbstract::sslErrors(), and MusicUtils::Codec::toUtf8().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/qq/musicqqtextdownloadthread.h
TTKModule/TTKCore/musicNetworkKits/qq/musicqqtextdownloadthread.cpp