TTKMusicPlayer: QDlnaFileServer Class Reference
QDlnaFileServer Class Reference
The class of the dlna file server.
#include <qdlnafileserver.h>
Public Member Functions
QDlnaFileServer (QObject *parent=nullptr)
void start ()
void setPrefixPath (const QString &path)
QString localAddress (const QString &prefix) const
Private Slots
void handleRequest (QHttpRequest *request, QHttpResponse *response)
Detailed Description
The class of the dlna file server.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file qdlnafileserver.h.
Constructor & Destructor Documentation
QDlnaFileServer::QDlnaFileServer (QObject * parent = nullptr) explicit
Definition at line 39 of file qdlnafileserver.cpp.
References handleRequest(), TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
void QDlnaFileServer::handleRequest (QHttpRequest * request, QHttpResponse * response) private slot
Definition at line 74 of file qdlnafileserver.cpp.
References TTKRegularExpression::captured(), QHttpResponse::end(), TTKRegularExpression::match(), name, QHttpRequest::path, QHttpResponse::setHeader(), TTK_D, TTK_SEPARATOR, and QHttpResponse::writeHead().
Referenced by QDlnaFileServer().
QString QDlnaFileServer::localAddress (const QString & prefix) const
Definition at line 59 of file qdlnafileserver.cpp.
References TTK_DOT.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
void QDlnaFileServer::setPrefixPath (const QString & path)
Definition at line 53 of file qdlnafileserver.cpp.
References TTK_D.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
void QDlnaFileServer::start ()
Definition at line 47 of file qdlnafileserver.cpp.
References TTK_D.
Referenced by MusicSongDlnaTransferWidget::MusicSongDlnaTransferWidget().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/qdlnafileserver.h
TTKThirdParty/TTKExtras/qdlna/qdlnafileserver.cpp