TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/split.h File Reference
split.h File Reference
#include "qrencode.h"
Functions
int Split_splitStringToQRinput (const char *string, QRinput *input, QRencodeMode hint, int casesensitive)
Split the input string (null terminated) into QRinput.
Function Documentation
int Split_splitStringToQRinput (const char * string, QRinput * input, QRencodeMode hint, int casesensitive)
Split the input string (null terminated) into QRinput.
Parameters
string input string
hint give QR_MODE_KANJI if the input string contains Kanji character encoded in Shift-JIS. If not, give QR_MODE_8.
casesensitive 0 for case-insensitive encoding (all alphabet characters are replaced to UPPER-CASE CHARACTERS.
Return values
0 success.
-1 an error occurred. errno is set to indicate the error. See Exceptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
Definition at line 304 of file split.c.
References dupAndToUpper(), and Split_splitString().
Referenced by QRcode_encodeDataStructuredReal(), and QRcode_encodeStringReal().