TTKMusicplayer: QNSimpleListData Class Reference
QNSimpleListData Class Reference
The namespace of the qiniu simple list data.
#include <qnsimplelistdata.h>
Signals
void receiveFinshed (const QNDataItems &items)
Public Member Functions
QNSimpleListData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void listDataToServer (const QString &bucket)
Private Slots
void receiveDataFromServer ()
void handleError (QNetworkReply::NetworkError error)
Detailed Description
The namespace of the qiniu simple list data.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 31 of file qnsimplelistdata.h.
Constructor & Destructor Documentation
QNSimpleListData::QNSimpleListData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 25 of file qnsimplelistdata.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
void QNSimpleListData::handleError (QNetworkReply::NetworkError error) private slot
Get handle error.
Definition at line 80 of file qnsimplelistdata.cpp.
Referenced by listDataToServer().
void QNSimpleListData::listDataToServer (const QString & bucket)
List data to server.
Definition at line 33 of file qnsimplelistdata.cpp.
References QNConf::ACCESS_KEY, handleError(), QNIOHelper::listRequest(), MusicObject::NetworkError, receiveDataFromServer(), QNConf::SECRET_KEY, and TTK_D.
Referenced by MusicCloudManagerTableWidget::updateListToServer().
void QNSimpleListData::receiveDataFromServer () private slot
Receive data from server finshed.
Definition at line 43 of file qnsimplelistdata.cpp.
References QNDataItem::m_hash, QNDataItem::m_mimeType, QNDataItem::m_name, QNDataItem::m_putTime, QNDataItem::m_size, MObject_cast, QJson::Parser::parse(), and receiveFinshed().
Referenced by listDataToServer().
void QNSimpleListData::receiveFinshed (const QNDataItems & items) signal
Receive data finshed.
Referenced by receiveDataFromServer().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnsimplelistdata.h
TTKThirdParty/TTKExtras/qiniu/qnsimplelistdata.cpp