TTKMusicplayer: MusicAbstractMoveDialog Class Reference
MusicAbstractMoveDialog Class Reference
The class of the moving dialog base.
#include <musicabstractmovedialog.h>
Public Slots
void backgroundChanged ()
Public Member Functions
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the moving dialog base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicabstractmovedialog.h.
Constructor & Destructor Documentation
MusicAbstractMoveDialog::MusicAbstractMoveDialog (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 12 of file musicabstractmovedialog.cpp.
MusicAbstractMoveDialog::MusicAbstractMoveDialog (bool transparent, QWidget * parent = 0) explicit
Object contsructor.
Remove the title bar
Definition at line 18 of file musicabstractmovedialog.cpp.
References m_background, M_BACKGROUND_PTR, m_leftButtonPress, m_moveOption, and m_showShadow.
MusicAbstractMoveDialog::~MusicAbstractMoveDialog () virtual
Definition at line 33 of file musicabstractmovedialog.cpp.
References M_BACKGROUND_PTR.
Member Function Documentation
void MusicAbstractMoveDialog::backgroundChanged () slot
Background image changed.
Definition at line 43 of file musicabstractmovedialog.cpp.
References m_background, and setBackgroundPixmap().
void MusicAbstractMoveDialog::blockMoveOption (bool block) inline
Set or not block widget moving.
Definition at line 55 of file musicabstractmovedialog.h.
void MusicAbstractMoveDialog::drawWindowShadow (bool show) inline
Set or not draw window bound shadow.
Definition at line 51 of file musicabstractmovedialog.h.
QString MusicAbstractMoveDialog::getClassName () static
Get class object name.
Definition at line 38 of file musicabstractmovedialog.cpp.
void MusicAbstractMoveDialog::mouseMoveEvent (QMouseEvent * event) override protected virtual
Not press the left key
Definition at line 85 of file musicabstractmovedialog.cpp.
References m_leftButtonPress, and m_pressAt.
void MusicAbstractMoveDialog::mousePressEvent (QMouseEvent * event) override protected virtual
Press the left key
Definition at line 75 of file musicabstractmovedialog.cpp.
References m_leftButtonPress, m_moveOption, and m_pressAt.
void MusicAbstractMoveDialog::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 100 of file musicabstractmovedialog.cpp.
References m_leftButtonPress, and m_pressAt.
void MusicAbstractMoveDialog::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 51 of file musicabstractmovedialog.cpp.
References HEIGHT, m_showShadow, and WIDTH.
void MusicAbstractMoveDialog::setBackgroundPixmap (QLabel * label, const QSize & size) protected
Set background pixmap.
Definition at line 107 of file musicabstractmovedialog.cpp.
References m_background.
Referenced by backgroundChanged(), MusicSongListEnhanceLosslessWidget::exec(), MusicSongListSharingWidget::exec(), MusicMessageAboutDialog::exec(), MusicCloudFileInformationWidget::exec(), MusicLrcArtPhotoUploadWidget::exec(), MusicLrcErrorWidget::exec(), MusicTimerWidget::exec(), MusicLrcSearchWidget::exec(), MusicFileInformationWidget::exec(), MusicLrcColorWidget::exec(), MusicMessageBox::exec(), MusicEqualizerDialog::exec(), MusicSongCheckToolsItemSelectedDialog::exec(), MusicSongRingtoneMaker::exec(), MusicTransformWidget::exec(), MusicConnectTransferWidget::exec(), MusicCloudFileManagerDialog::exec(), MusicUserRecordWidget::exec(), MusicSongSharingWidget::exec(), MusicUserDialog::exec(), MusicLrcLocalLinkWidget::exec(), MusicSourceUpdateWidget::exec(), MusicBackgroundSkinDialog::exec(), MusicSoundEffectsWidget::exec(), MusicColorDialog::exec(), MusicSettingWidget::exec(), MusicLrcPosterWidget::exec(), MusicFileInformationWidget::musicAdvanceClicked(), MusicMessageBox::show(), and MusicCloudFileManagerDialog::show().
void MusicAbstractMoveDialog::setBackgroundPixmap (const QSize & size) protected
Set background pixmap.
Definition at line 113 of file musicabstractmovedialog.cpp.
References m_background, M_BACKGROUND_PTR, MusicBackgroundImage::m_pix, MStatic_cast, and MusicExtractWrap::outputSkin().
Member Data Documentation
QWidget* MusicAbstractMoveDialog::m_background protected
Definition at line 83 of file musicabstractmovedialog.h.
Referenced by backgroundChanged(), MusicAbstractMoveDialog(), and setBackgroundPixmap().
bool MusicAbstractMoveDialog::m_leftButtonPress protected
Definition at line 82 of file musicabstractmovedialog.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and MusicAbstractMoveDialog().
bool MusicAbstractMoveDialog::m_moveOption protected
Definition at line 81 of file musicabstractmovedialog.h.
Referenced by mousePressEvent(), and MusicAbstractMoveDialog().
QPoint MusicAbstractMoveDialog::m_pressAt protected
Definition at line 80 of file musicabstractmovedialog.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool MusicAbstractMoveDialog::m_showShadow protected
Definition at line 81 of file musicabstractmovedialog.h.
Referenced by MusicAbstractMoveDialog(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicabstractmovedialog.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicabstractmovedialog.cpp