TTKMusicPlayer: MusicKGInterface Namespace Reference
MusicKGInterface Namespace Reference
The namespace of the kugou request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request)
void parseFromSongAlbumLrc (TTK::MusicSongInformation *info)
void parseFromSongAlbumInfo (TTK::MusicSongInformation *info, const QString &album)
void parseFromSongAlbumInfo (MusicResultDataItem *info, const QString &hash, const QString &album)
void parseFromSongProperty (TTK::MusicSongInformation *info, int bitrate)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QVariantMap &key)
static void parseFromMovieInfo (TTK::MusicSongInformation *info)
static void parseFromMovieProperty (TTK::MusicSongInformation *info, bool more)
static void parseFromMovieProperty (TTK::MusicSongInformation *info, const QVariantMap &key)
static void parseFromMovieProperty (TTK::MusicSongInformation *info)
static void parseFromMovieProperty (TTK::MusicSongInformation *info, const QVariantMap &key)
Detailed Description
The namespace of the kugou request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void MusicKGInterface::makeRequestRawHeader (QNetworkRequest * request)
Make request query data.
Definition at line 4 of file musickgqueryinterface.cpp.
References ALG_UA_KEY, KG_UA_URL, TTK::makeContentTypeHeader(), TTK::Algorithm::mdII(), and TTK::setSslConfiguration().
Referenced by parseFromMovieInfo(), parseFromMovieProperty(), parseFromSongAlbumInfo(), parseFromSongAlbumLrc(), parseSongProperty(), MusicKGQueryArtistRequest::queryArtistIntro(), MusicKGQueryToplistRequest::queryToplistInfo(), MusicKGSongCommentsRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicKGQueryAlbumRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicKGQueryToplistRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicKGQueryArtistRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKGQueryArtistAlbumRequest::startToPage(), MusicKGQueryArtistMovieRequest::startToPage(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicKGDiscoverListRequest::startToSearch(), MusicSongSuggestRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), and MusicKGQueryRequest::startToSearchByID().
void MusicKGInterface::parseFromMovieInfo (TTK::MusicSongInformation * info) static
Read mv infos from query results.
Definition at line 20 of file musickgquerymovierequest.cpp.
References KG_MOVIE_URL, TTK::MusicSongInformation::m_songId, makeRequestRawHeader(), TTK::Algorithm::mdII(), and TTK::syncNetworkQueryForGet().
Referenced by MusicKGQueryMovieRequest::downLoadSingleFinished().
void MusicKGInterface::parseFromMovieProperty (TTK::MusicSongInformation * info) static
Read mv tags(size) from query results.
Definition at line 17 of file musicmvradioprogramrequest.cpp.
References KG_MOVIE_INFO_URL, TTK::MusicSongInformation::m_songId, makeRequestRawHeader(), TTK::Algorithm::md5(), TTK::Algorithm::mdII(), QJson::Parser::parse(), parseFromMovieProperty(), and TTK::syncNetworkQueryForGet().
void MusicKGInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, bool more) static
Read mv tags(size) from query results.
Definition at line 46 of file musickgquerymovierequest.cpp.
References KG_MOVIE_INFO_URL, TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songName, makeRequestRawHeader(), TTK::Algorithm::md5(), TTK::Algorithm::mdII(), QJson::Parser::parse(), parseFromMovieProperty(), and TTK::syncNetworkQueryForGet().
Referenced by MusicMVRadioProgramRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), and MusicKGQueryMovieRequest::downLoadSingleFinished().
void MusicKGInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, const QVariantMap & key) static
Read mv tags(size) from query results.
Definition at line 73 of file musicmvradioprogramrequest.cpp.
References TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, TTK::Number::sizeByteToLabel(), TTK::String::splitToken(), TTK_BN_1000, TTK_BN_250, TTK_BN_500, and TTK_BN_750.
Referenced by parseFromMovieProperty().
void MusicKGInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, const QVariantMap & key) static
Read mv tags(size) from query results.
Definition at line 108 of file musickgquerymovierequest.cpp.
References TTKTime::formatDuration(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongInformation::m_duration, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, TTK::Number::sizeByteToLabel(), TTK::String::splitToken(), TTK_BN_1000, TTK_BN_250, TTK_BN_500, and TTK_BN_750.
Referenced by parseFromMovieProperty().
void MusicKGInterface::parseFromSongAlbumInfo (TTK::MusicSongInformation * info, const QString & album)
Read album id and name.
Definition at line 46 of file musickgqueryinterface.cpp.
References TTK::MusicSongInformation::m_albumId, TTK::MusicSongInformation::m_albumName, MusicResultDataItem::m_id, MusicResultDataItem::m_name, and TTK::MusicSongInformation::m_songId.
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), and MusicKGQueryRequest::downLoadSingleFinished().
void MusicKGInterface::parseFromSongAlbumInfo (MusicResultDataItem * info, const QString & hash, const QString & album)
Read tags(album info) from query results.
Definition at line 60 of file musickgqueryinterface.cpp.
References TTK::String::charactersReplace(), KG_ALBUM_INFO_URL, MusicResultDataItem::m_category, MusicResultDataItem::m_description, MusicResultDataItem::m_id, MusicResultDataItem::m_name, MusicResultDataItem::m_updateTime, makeRequestRawHeader(), TTK::Algorithm::mdII(), QJson::Parser::parse(), qAsConst, TTK::syncNetworkQueryForGet(), and TTK::toString().
void MusicKGInterface::parseFromSongAlbumLrc (TTK::MusicSongInformation * info)
Read tags(lrc pic) from query results.
Definition at line 11 of file musickgqueryinterface.cpp.
References TTK::String::charactersReplace(), KG_SONG_INFO_URL, KG_SONG_LRC_URL, TTK::MusicSongInformation::m_artistId, TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_coverUrl, TTK::MusicSongInformation::m_lrcUrl, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songName, makeRequestRawHeader(), TTK::Algorithm::mdII(), QJson::Parser::parse(), TTK::syncNetworkQueryForGet(), TTK::toString(), and TTK_DN_S2MS.
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), and MusicKGQueryToplistRequest::downLoadFinished().
void MusicKGInterface::parseFromSongProperty (TTK::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 200 of file musickgqueryinterface.cpp.
References TTK::MusicSongInformation::m_formatProps, TTK::MusicSongInformation::m_songId, parseSongProperty(), TTK_BN_0, TTK_BN_1000, TTK_BN_128, TTK_BN_192, and TTK_BN_320.
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicKGQueryRequest::downLoadSingleFinished(), MusicKGQueryAlbumRequest::startToQueryResult(), MusicKGQueryArtistRequest::startToQueryResult(), MusicKGQueryRequest::startToQueryResult(), MusicKGQueryPlaylistRequest::startToQueryResult(), and MusicKGQueryToplistRequest::startToQueryResult().
void MusicKGInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QVariantMap & key)
Read tags(size) from query results.
Definition at line 231 of file musickgqueryinterface.cpp.
References TTK::MusicSongInformation::m_formatProps.