TTKMusicPlayer: MusicLrcPosterTableWidget Class Reference
MusicLrcPosterTableWidget Class Reference
The class of the lrc art poster table widget.
#include <musiclrcposterwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void textChanged (const QStringList &data)
Public Member Functions
MusicLrcPosterTableWidget (QWidget *parent=nullptr)
void addCellItems (const QStringList &lrcs)
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
TTKIntList uncheckedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the lrc art poster table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 172 of file musiclrcposterwidget.h.
Constructor & Destructor Documentation
MusicLrcPosterTableWidget::MusicLrcPosterTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 834 of file musiclrcposterwidget.cpp.
References TTK::UI::ScrollBarStyle01.
Member Function Documentation
void MusicLrcPosterTableWidget::addCellItems (const QStringList & lrcs)
Create cell items by input data.
Definition at line 847 of file musiclrcposterwidget.cpp.
References QtItemSetTextAlignment, and TTK_CHECKED_ROLE.
void MusicLrcPosterTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 864 of file musiclrcposterwidget.cpp.
References MusicFillItemTableWidget::itemCellClicked(), textChanged(), TTK_CHECKED_ROLE, and TTKStaticCast.
void MusicLrcPosterTableWidget::textChanged (const QStringList & data) signal
Lrc text changed.
Referenced by itemCellClicked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcposterwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcposterwidget.cpp