TTKMusicplayer: MusicQueryFoundTableWidget Class Reference
MusicQueryFoundTableWidget Class Reference
The class of the query found table widget.
#include <musicqueryfoundtablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) override
virtual void itemCellClicked (int row, int column) override
virtual void clearAllItems () override
virtual void createSearchedItem (const MusicSearchedItem &songItem) override
void createFinishedItem ()
void searchChanged (QAction *action)
Public Slots inherited from MusicQueryTableWidget
virtual void clearAllItems ()=0
virtual void createSearchedItem (const MusicSearchedItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void setSelectedAllItems (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Public Member Functions
MusicQueryFoundTableWidget (QWidget *parent=nullptr)
virtual ~MusicQueryFoundTableWidget ()
virtual void setQueryInput (MusicDownLoadQueryThreadAbstract *query)
virtual void startSearchQuery (const QString &text) override
virtual void musicDownloadLocal (int row) override
void downloadDataFrom (bool play)
void downloadBatchData (bool music)
void resizeWindow ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
virtual ~MusicQueryTableWidget ()
MusicDownLoadQueryThreadAbstract * getQueryInput ()
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
virtual ~MusicFillItemTableWidget ()
TTKIntList getSelectedItems () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractTableWidget ()
void clear ()
TTKIntList getMultiSelectedIndexs () const
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
void addSearchMusicToPlaylist (int row, bool play)
bool downloadDataFrom (const MusicObject::MusicSongInformation &downloadInfo, bool play)
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
MusicLabelDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicDownLoadQueryThreadAbstract * m_downLoadManager
Protected Attributes inherited from MusicFillItemTableWidget
MusicCheckBoxDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void musicSongToPlaylistChanged (const QString &name, const QString &time, const QString &format, bool play)
void showDownLoadInfoFor (MusicObject::DownLoadMode type)
void restartSearchQuery (const QString &name)
Detailed Description
The class of the query found table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicqueryfoundtablewidget.h.
Constructor & Destructor Documentation
MusicQueryFoundTableWidget::MusicQueryFoundTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 13 of file musicqueryfoundtablewidget.cpp.
References M_CONNECTION_PTR, and m_labelDelegate.
MusicQueryFoundTableWidget::~MusicQueryFoundTableWidget () virtual
Definition at line 35 of file musicqueryfoundtablewidget.cpp.
References clearAllItems(), M_CONNECTION_PTR, and m_labelDelegate.
Member Function Documentation
void MusicQueryFoundTableWidget::addSearchMusicToPlaylist (int row, bool play) protected
Add search music to play list by index.
Definition at line 317 of file musicqueryfoundtablewidget.cpp.
References downloadDataFrom(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicQueryTableWidget::m_downLoadManager, and MusicToastLabel::popup().
Referenced by itemCellClicked(), and searchChanged().
void MusicQueryFoundTableWidget::clearAllItems () override virtual slot
Clear All Items.
Definition at line 226 of file musicqueryfoundtablewidget.cpp.
References MusicAbstractTableWidget::clear().
Referenced by startSearchQuery(), MusicAlbumFoundTableWidget::~MusicAlbumFoundTableWidget(), MusicArtistFoundTableWidget::~MusicArtistFoundTableWidget(), MusicPlaylistFoundTableWidget::~MusicPlaylistFoundTableWidget(), ~MusicQueryFoundTableWidget(), MusicRecommendFoundTableWidget::~MusicRecommendFoundTableWidget(), MusicSimilarFoundTableWidget::~MusicSimilarFoundTableWidget(), MusicToplistFoundTableWidget::~MusicToplistFoundTableWidget(), MusicWebDJRadioInfoTableWidget::~MusicWebDJRadioInfoTableWidget(), and MusicWebMVRadioInfoTableWidget::~MusicWebMVRadioInfoTableWidget().
void MusicQueryFoundTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 164 of file musicqueryfoundtablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicObject::MusicSongInformation::m_albumName, MusicQueryTableWidget::m_downLoadManager, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, MusicUIObject::MQSSMenuStyle02, and searchChanged().
void MusicQueryFoundTableWidget::createFinishedItem () slot
Create the search finished item.
Definition at line 297 of file musicqueryfoundtablewidget.cpp.
References m_labelDelegate, and MUSIC_TEXTS_ROLE.
Referenced by setQueryInput().
void MusicQueryFoundTableWidget::createSearchedItem (const MusicSearchedItem & songItem) override virtual slot
Create searched items.
Definition at line 236 of file musicqueryfoundtablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSearchedItem::m_albumName, MusicSearchedItem::m_singerName, MusicSearchedItem::m_songName, MusicSearchedItem::m_time, MusicSearchedItem::m_type, and MUSIC_CHECK_ROLE.
Referenced by MusicRecommendFoundTableWidget::createSearchedItem(), and MusicSimilarFoundTableWidget::createSearchedItem().
void MusicQueryFoundTableWidget::downloadBatchData (bool music)
Download batch data from net.
Definition at line 92 of file musicqueryfoundtablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicFillItemTableWidget::getSelectedItems(), MusicQueryTableWidget::m_downLoadManager, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicToastLabel::popup(), MusicDownloadBatchWidget::setSongName(), and MusicDownloadBatchWidget::show().
Referenced by MusicFoundAbstractWidget::downloadButtonClicked(), and MusicWebMVRadioInfoWidget::downloadMVsButtonClicked().
void MusicQueryFoundTableWidget::downloadDataFrom (bool play)
Download data from net and just play or not.
Definition at line 73 of file musicqueryfoundtablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicFillItemTableWidget::getSelectedItems(), MusicQueryTableWidget::m_downLoadManager, and MusicToastLabel::popup().
Referenced by MusicFoundAbstractWidget::addButtonClicked(), addSearchMusicToPlaylist(), MusicFoundAbstractWidget::playAllButtonClicked(), and MusicFoundAbstractWidget::playButtonClicked().
bool MusicQueryFoundTableWidget::downloadDataFrom (const MusicObject::MusicSongInformation & downloadInfo, bool play) protected
Download data from net and just play or not.
Definition at line 334 of file musicqueryfoundtablewidget.cpp.
References ALG_DOWNLOAD_KEY, CACHE_DIR_FULL, MusicObject::DownloadMusic, MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_format, M_NETWORK_PTR, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), MusicQueryTableWidget::musicSongToPlaylistChanged(), and MusicDataDownloadThread::startToDownload().
void MusicQueryFoundTableWidget::itemCellClicked (int row, int column) override virtual slot
Subclass should implement this function.
Definition at line 207 of file musicqueryfoundtablewidget.cpp.
References addSearchMusicToPlaylist(), MusicFillItemTableWidget::itemCellClicked(), and musicDownloadLocal().
void MusicQueryFoundTableWidget::itemCellEntered (int row, int column) override virtual slot
Table widget item cell enter.
Definition at line 194 of file musicqueryfoundtablewidget.cpp.
References MusicAbstractTableWidget::itemCellEntered().
void MusicQueryFoundTableWidget::musicDownloadLocal (int row) override virtual
Data download to local file.
Implements MusicQueryTableWidget.
Reimplemented in MusicWebMVRadioInfoTableWidget.
Definition at line 60 of file musicqueryfoundtablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicQueryTableWidget::m_downLoadManager, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownloadWidget::setSongName(), and MusicDownloadWidget::show().
Referenced by itemCellClicked(), and searchChanged().
void MusicQueryFoundTableWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Definition at line 158 of file musicqueryfoundtablewidget.cpp.
References resizeWindow().
void MusicQueryFoundTableWidget::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 118 of file musicqueryfoundtablewidget.cpp.
References MusicUtils::Widget::elidedText(), M_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), MusicPlaylistFoundInfoWidget::resizeWindow(), MusicWebDJRadioInfoWidget::resizeWindow(), MusicAlbumFoundWidget::resizeWindow(), MusicToplistFoundWidget::resizeWindow(), MusicRecommendFoundWidget::resizeWindow(), MusicSimilarFoundWidget::resizeWindow(), MusicWebMVRadioInfoWidget::resizeWindow(), and MusicArtistFoundWidget::resizeWindow().
void MusicQueryFoundTableWidget::searchChanged (QAction * action) slot
Search menu type changed.
Definition at line 135 of file musicqueryfoundtablewidget.cpp.
References addSearchMusicToPlaylist(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicRightAreaWidget::instance(), MusicObject::MusicSongInformation::m_albumId, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicQueryTableWidget::m_downLoadManager, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, MusicRightAreaWidget::musicAlbumFound(), MusicRightAreaWidget::musicArtistFound(), musicDownloadLocal(), and MusicRightAreaWidget::musicSongSearchedFound().
Referenced by contextMenuEvent().
void MusicQueryFoundTableWidget::setQueryInput (MusicDownLoadQueryThreadAbstract * query) virtual
Set network query input.
Reimplemented from MusicQueryTableWidget.
Reimplemented in MusicArtistFoundTableWidget, MusicToplistFoundTableWidget, MusicRecommendFoundTableWidget, MusicSimilarFoundTableWidget, MusicWebDJRadioInfoTableWidget, MusicWebMVRadioInfoTableWidget, MusicAlbumFoundTableWidget, and MusicPlaylistFoundTableWidget.
Definition at line 42 of file musicqueryfoundtablewidget.cpp.
References createFinishedItem(), and MusicQueryTableWidget::setQueryInput().
Referenced by MusicToplistFoundWidget::MusicToplistFoundWidget(), MusicWebDJRadioInfoWidget::MusicWebDJRadioInfoWidget(), MusicWebMVRadioInfoWidget::MusicWebMVRadioInfoWidget(), MusicPlaylistFoundTableWidget::setQueryInput(), MusicWebDJRadioInfoTableWidget::setQueryInput(), MusicAlbumFoundTableWidget::setQueryInput(), MusicWebMVRadioInfoTableWidget::setQueryInput(), MusicRecommendFoundTableWidget::setQueryInput(), MusicSimilarFoundTableWidget::setQueryInput(), MusicToplistFoundTableWidget::setQueryInput(), MusicPlaylistFoundInfoWidget::setQueryInput(), MusicArtistFoundTableWidget::setQueryInput(), MusicRecommendFoundWidget::setSongName(), MusicSimilarFoundWidget::setSongName(), MusicAlbumFoundWidget::setSongNameById(), and MusicArtistFoundWidget::setSongNameById().
void MusicQueryFoundTableWidget::startSearchQuery (const QString & text) override virtual
Start search query by text.
Implements MusicQueryTableWidget.
Definition at line 48 of file musicqueryfoundtablewidget.cpp.
References clearAllItems(), MusicObject::DW_DisConnection, MusicQueryTableWidget::m_downLoadManager, M_NETWORK_PTR, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), MusicQueryTableWidget::showDownLoadInfoFor(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicPlaylistFoundInfoWidget::setMusicResultsItem(), MusicWebDJRadioInfoWidget::setSongName(), MusicRecommendFoundWidget::setSongName(), MusicSimilarFoundWidget::setSongName(), MusicWebMVRadioInfoWidget::setSongName(), MusicAlbumFoundWidget::setSongNameById(), and MusicArtistFoundWidget::setSongNameById().
Member Data Documentation
MusicLabelDelegate* MusicQueryFoundTableWidget::m_labelDelegate protected
Definition at line 106 of file musicqueryfoundtablewidget.h.
Referenced by createFinishedItem(), MusicQueryFoundTableWidget(), and ~MusicQueryFoundTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicqueryfoundtablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicqueryfoundtablewidget.cpp