TTKMusicPlayer: MusicSongsListItemInfoWidget Class Reference
MusicSongsListItemInfoWidget Class Reference
The class of the song list item info widget.
#include <musicsongslistiteminfowidget.h>
Public Member Functions
MusicSongsListItemInfoWidget (QWidget *parent=nullptr)
~MusicSongsListItemInfoWidget ()
void setMusicSongInformation (const MusicSong &song)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
Public Member Functions inherited from TTKAbstractMoveWidget
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Private Member Functions
bool showArtistPicture (const QString &name)
Private Attributes
Ui::MusicSongsListItemInfoWidget * m_ui
Additional Inherited Members
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
void show ()
Protected Member Functions inherited from TTKAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Protected Attributes inherited from TTKAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Detailed Description
The class of the song list item info widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicsongslistiteminfowidget.h.
Constructor & Destructor Documentation
MusicSongsListItemInfoWidget::MusicSongsListItemInfoWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicsongslistiteminfowidget.cpp.
References MusicUIObject::ColorStyle03, and m_ui.
MusicSongsListItemInfoWidget::~MusicSongsListItemInfoWidget ()
Definition at line 22 of file musicsongslistiteminfowidget.cpp.
References m_ui.
Member Function Documentation
void MusicSongsListItemInfoWidget::setMusicSongInformation (const MusicSong & song)
Set music song information.
Definition at line 38 of file musicsongslistiteminfowidget.cpp.
References MusicSong::artistBack(), MusicSong::artistFront(), MusicSongMeta::cover(), MusicUtils::Widget::elidedText(), MusicSong::format(), G_SETTING_PTR, m_ui, MusicSong::name(), MusicSettingManager::OtherReadAlbumCover, MusicSong::path(), MusicSong::playCount(), MusicSongMeta::read(), showArtistPicture(), MusicSong::sizeStr(), and TTK_DEFAULT_STR.
Referenced by MusicSongsListPlayTableWidget::showTimeOut().
bool MusicSongsListItemInfoWidget::showArtistPicture (const QString & name) private
Show artist small picture, if no exsit there is default pic.
Definition at line 27 of file musicsongslistiteminfowidget.cpp.
References ART_DIR_FULL, m_ui, and SKN_FILE.
Referenced by setMusicSongInformation().
Member Data Documentation
Ui::MusicSongsListItemInfoWidget* MusicSongsListItemInfoWidget::m_ui private
Definition at line 54 of file musicsongslistiteminfowidget.h.
Referenced by MusicSongsListItemInfoWidget(), setMusicSongInformation(), showArtistPicture(), and ~MusicSongsListItemInfoWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslistiteminfowidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslistiteminfowidget.cpp