TTKMusicplayer: TTKThirdParty/TTKWatcher/qdevicewatcher_mac.cpp File Reference
qdevicewatcher_mac.cpp File Reference
#include "qdevicewatcher_p.h"
#include <QtCore/QStringList>
#include <CoreServices/CoreServices.h>
#include <IOKit/storage/IOCDMedia.h>
#include <IOKit/storage/IODVDMedia.h>
Functions
static void onDiskAppear (DADiskRef disk, void *context)
static void onDiskDisappear (DADiskRef disk, void *context)
Variables
static QStringList sDevices
Function Documentation
static void onDiskAppear (DADiskRef disk, void * context) static
Definition at line 10 of file qdevicewatcher_mac.cpp.
References QDeviceWatcherPrivate::emitDeviceAdded(), sDevices, and TTKStatic_cast.
Referenced by QDeviceWatcherPrivate::initialize(), and QDeviceWatcherPrivate::stop().
static void onDiskDisappear (DADiskRef disk, void * context) static
Definition at line 20 of file qdevicewatcher_mac.cpp.
References QDeviceWatcherPrivate::emitDeviceRemoved(), sDevices, and TTKStatic_cast.
Referenced by QDeviceWatcherPrivate::initialize(), and QDeviceWatcherPrivate::stop().
Variable Documentation
QStringList sDevices static
Definition at line 8 of file qdevicewatcher_mac.cpp.
Referenced by onDiskAppear(), and onDiskDisappear().