TTKMusicplayer: MusicImageRenderer Class Reference
MusicImageRenderer Class Reference
The class of the image render thread.
#include <musicimagerenderer.h>
Signals
void renderFinished (const QPixmap &data)
Public Member Functions
MusicImageRenderer (QObject *parent=nullptr)
~MusicImageRenderer ()
void setInputData (const QByteArray &data, const QSize &size)
Public Member Functions inherited from MusicAbstractThread
MusicAbstractThread (QObject *parent=nullptr)
virtual ~MusicAbstractThread ()
void stopAndQuitThread ()
Protected Member Functions
virtual void run () override
Private Attributes
QSize m_size
QByteArray m_buffer
Additional Inherited Members
Public Slots inherited from MusicAbstractThread
void start ()
Protected Attributes inherited from MusicAbstractThread
bool m_running
Detailed Description
The class of the image render thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicimagerenderer.h.
Constructor & Destructor Documentation
MusicImageRenderer::MusicImageRenderer (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicimagerenderer.cpp.
MusicImageRenderer::~MusicImageRenderer ()
Definition at line 12 of file musicimagerenderer.cpp.
References MusicAbstractThread::stopAndQuitThread().
Member Function Documentation
void MusicImageRenderer::renderFinished (const QPixmap & data) signal
Image render finished.
Referenced by run().
void MusicImageRenderer::run () override protected virtual
Thread run now.
Reimplemented from MusicAbstractThread.
Definition at line 23 of file musicimagerenderer.cpp.
References MusicUtils::Image::fusionPixmap(), m_buffer, MusicAbstractThread::m_running, m_size, renderFinished(), and MusicAbstractThread::run().
void MusicImageRenderer::setInputData (const QByteArray & data, const QSize & size)
Set input data array.
Definition at line 17 of file musicimagerenderer.cpp.
References m_buffer, and m_size.
Referenced by MusicArtistAlbumsItemWidget::downLoadFinished(), MusicWebMVRadioQueryItemWidget::downLoadFinished(), MusicWebDJRadioQueryItemWidget::downLoadFinished(), and MusicPlaylistQueryItemWidget::downLoadFinished().
Member Data Documentation
QByteArray MusicImageRenderer::m_buffer private
Definition at line 58 of file musicimagerenderer.h.
Referenced by run(), and setInputData().
QSize MusicImageRenderer::m_size private
Definition at line 57 of file musicimagerenderer.h.
Referenced by run(), and setInputData().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicimagerenderer.h
TTKModule/TTKCore/musicCoreKits/musicimagerenderer.cpp