TTKMusicPlayer: MusicAbstractTableWidget Class Reference
MusicAbstractTableWidget Class Reference
The class of the table widget base.
#include <musicabstracttablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Protected Member Functions
void setRowColor (int row, const QColor &color) const
Protected Attributes
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the table widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicabstracttablewidget.h.
Constructor & Destructor Documentation
MusicAbstractTableWidget::MusicAbstractTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicabstracttablewidget.cpp.
References itemCellClicked(), itemCellEntered(), MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSScrollBarStyle01, MusicUIObject::MQSSTableWidgetStyle01, and MusicUtils::Widget::setTransparent().
MusicAbstractTableWidget::~MusicAbstractTableWidget ()
Definition at line 45 of file musicabstracttablewidget.cpp.
Member Function Documentation
void MusicAbstractTableWidget::itemCellClicked (int row, int column) virtual slot
Table widget item cell click.
Definition at line 78 of file musicabstracttablewidget.cpp.
Referenced by MusicQualityChoiceTableWidget::itemCellClicked(), MusicSongSearchPopTableWidget::itemCellClicked(), and MusicAbstractTableWidget().
void MusicAbstractTableWidget::itemCellEntered (int row, int column) virtual slot
Table widget item cell enter.
Definition at line 63 of file musicabstracttablewidget.cpp.
References m_backgroundColor, m_previousColorRow, and setRowColor().
Referenced by MusicQualityChoiceTableWidget::itemCellEntered(), MusicWebFMRadioWidget::itemCellEntered(), MusicMobileSongsTableWidget::itemCellEntered(), MusicLrcSearchTableWidget::itemCellEntered(), MusicWebDJRadioProgramTableWidget::itemCellEntered(), MusicSoundKMicroSearchTableWidget::itemCellEntered(), MusicItemQueryTableWidget::itemCellEntered(), MusicSongSearchTableWidget::itemCellEntered(), MusicSongsListPlayedTableWidget::itemCellEntered(), MusicVideoSearchTableWidget::itemCellEntered(), MusicSongsListPlayTableWidget::itemCellEntered(), MusicFunctionTableWidget::leaveEvent(), and MusicAbstractTableWidget().
TTKIntList MusicAbstractTableWidget::multiSelectedIndexList () const
Get multi selected item index set.
Definition at line 50 of file musicabstracttablewidget.cpp.
Referenced by MusicCloudManagerTableWidget::deleteFilesToServer(), MusicCloudUploadTableWidget::reuploadFiles(), MusicAbstractDownloadTableWidget::setDeleteItemAt(), MusicSongsListPlayedTableWidget::setDeleteItemAt(), and MusicSongsListPlayTableWidget::setDeleteItemAt().
void MusicAbstractTableWidget::removeItems () virtual slot
Remove all items.
Definition at line 84 of file musicabstracttablewidget.cpp.
References m_backgroundColor, m_previousClickRow, and m_previousColorRow.
Referenced by MusicCloudManagerTableWidget::receiveDataFinshed(), MusicMobileSongsTableWidget::removeItems(), MusicItemSearchTableWidget::removeItems(), MusicSongSearchPopTableWidget::removeItems(), MusicItemQueryTableWidget::removeItems(), MusicSongsListPlayedTableWidget::removeItems(), MusicLocalManagerSongsTableWidget::removeItems(), MusicDownloadBatchTableWidget::removeItems(), MusicSongsListPlayTableWidget::removeItems(), MusicDownloadTableWidget::removeItems(), MusicQueryTableWidget::setQueryInput(), MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget(), MusicFillItemTableWidget::~MusicFillItemTableWidget(), MusicLocalManagerStatisticTableWidget::~MusicLocalManagerStatisticTableWidget(), and MusicQualityChoiceTableWidget::~MusicQualityChoiceTableWidget().
void MusicAbstractTableWidget::setRowColor (int row, const QColor & color) const protected
Set selected item row color.
Definition at line 94 of file musicabstracttablewidget.cpp.
References QtItemSetBackgroundColor.
Referenced by MusicQualityChoiceTableWidget::itemCellEntered(), and itemCellEntered().
Member Data Documentation
QColor MusicAbstractTableWidget::m_backgroundColor protected
Definition at line 69 of file musicabstracttablewidget.h.
Referenced by MusicSoundKMicroSearchTableWidget::createSearchedItem(), MusicVideoSearchTableWidget::createSearchedItem(), itemCellEntered(), MusicSoundKMicroSearchTableWidget::MusicSoundKMicroSearchTableWidget(), and removeItems().
int MusicAbstractTableWidget::m_previousClickRow protected
Definition at line 68 of file musicabstracttablewidget.h.
Referenced by MusicVideoSearchTableWidget::downloadLocalFromControl(), MusicQualityChoiceTableWidget::itemCellClicked(), MusicFillItemTableWidget::itemCellClicked(), MusicVideoSearchTableWidget::musicMediaInfo(), MusicQualityChoiceTableWidget::MusicQualityChoiceTableWidget(), and removeItems().
int MusicAbstractTableWidget::m_previousColorRow protected
Definition at line 67 of file musicabstracttablewidget.h.
Referenced by MusicQualityChoiceTableWidget::itemCellEntered(), MusicWebFMRadioWidget::itemCellEntered(), itemCellEntered(), MusicSongsListPlayedTableWidget::itemCellEntered(), MusicSongsListPlayTableWidget::itemCellEntered(), removeItems(), and MusicSongsListPlayTableWidget::showTimeOut().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicabstracttablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicabstracttablewidget.cpp