TTKMusicplayer: MusicQualityChoiceTableWidget Class Reference
MusicQualityChoiceTableWidget Class Reference
The class of the quality choice table widget.
#include <musicqualitychoicepopwidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) override
virtual void itemCellClicked (int row, int column) override
void createItems ()
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Public Member Functions
MusicQualityChoiceTableWidget (QWidget *parent=nullptr)
~MusicQualityChoiceTableWidget ()
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractTableWidget ()
void clear ()
TTKIntList getMultiSelectedIndex () const
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the quality choice table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicqualitychoicepopwidget.h.
Constructor & Destructor Documentation
MusicQualityChoiceTableWidget::MusicQualityChoiceTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicqualitychoicepopwidget.cpp.
References createItems(), MusicAbstractTableWidget::m_previousClickRow, MusicUIObject::MQSSCheckBoxStyle02, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSTableWidgetStyle03, MusicUIObject::MQSSTableWidgetStyle04, MusicCheckBoxDelegate::setStyleSheet(), and MusicUtils::Widget::setTransparent().
MusicQualityChoiceTableWidget::~MusicQualityChoiceTableWidget ()
Definition at line 31 of file musicqualitychoicepopwidget.cpp.
References MusicAbstractTableWidget::clear().
Member Function Documentation
void MusicQualityChoiceTableWidget::createItems () slot
Create Table widget item.
Definition at line 36 of file musicqualitychoicepopwidget.cpp.
References MUSIC_CHECK_ROLE, and PREVIOUS_COLOR.
Referenced by MusicQualityChoiceTableWidget().
void MusicQualityChoiceTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 135 of file musicqualitychoicepopwidget.cpp.
References MusicAbstractTableWidget::m_previousClickRow, and MUSIC_CHECK_ROLE.
void MusicQualityChoiceTableWidget::itemCellEntered (int row, int column) override virtual slot
Table widget item cell enter.
Definition at line 109 of file musicqualitychoicepopwidget.cpp.
References HOVER_COLOR, MusicAbstractTableWidget::itemCellEntered(), MusicAbstractTableWidget::m_previousColorRow, PREVIOUS_COLOR, and MusicAbstractTableWidget::setRowColor().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicqualitychoicepopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicqualitychoicepopwidget.cpp