TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/qrencode_inner.h File Reference
qrencode_inner.h File Reference
Classes
struct RSblock
qrencode - QR Code encoder
struct QRRawCode
struct MQRRawCode
Functions
QRRawCode * QRraw_new (QRinput *input)
unsigned char QRraw_getCode (QRRawCode *raw)
Return a code (byte).
void QRraw_free (QRRawCode *raw)
MQRRawCode * MQRraw_new (QRinput *input)
unsigned char MQRraw_getCode (MQRRawCode *raw)
Return a code (byte).
void MQRraw_free (MQRRawCode *raw)
unsigned char * FrameFiller_test (int version)
unsigned char * FrameFiller_testMQR (int version)
QRcode * QRcode_encodeMask (QRinput *input, int mask)
QRcode * QRcode_encodeMaskMQR (QRinput *input, int mask)
QRcode * QRcode_new (int version, int width, unsigned char *data)
Function Documentation
unsigned char* FrameFiller_test (int version)
unsigned char* FrameFiller_testMQR (int version)
void MQRraw_free (MQRRawCode * raw)
Definition at line 261 of file qrencode.c.
References MQRRawCode::datacode, MQRRawCode::ecccode, free(), and MQRRawCode::rsblock.
Referenced by MQRraw_new(), and QRcode_encodeMaskMQR().
unsigned char MQRraw_getCode (MQRRawCode * raw)
Return a code (byte).
This function can be called iteratively.
Parameters
raw raw code.
Returns
code
Definition at line 246 of file qrencode.c.
References MQRRawCode::count, MQRRawCode::datacode, MQRRawCode::dataLength, MQRRawCode::ecccode, and MQRRawCode::eccLength.
Referenced by QRcode_encodeMaskMQR().
MQRRawCode* MQRraw_new (QRinput * input)
Definition at line 204 of file qrencode.c.
References calloc(), MQRRawCode::count, MQRRawCode::datacode, MQRRawCode::dataLength, MQRRawCode::ecccode, MQRRawCode::eccLength, free(), _QRinput::level, malloc(), MQRraw_free(), MQRspec_getDataLength(), MQRspec_getDataLengthBit(), MQRspec_getECCLength(), MQRRawCode::oddbits, QRinput_getByteStream(), MQRRawCode::rsblock, RSblock_initBlock(), _QRinput::version, and MQRRawCode::version.
Referenced by QRcode_encodeMaskMQR().
QRcode* QRcode_encodeMask (QRinput * input, int mask)
Definition at line 429 of file qrencode.c.
References QRRawCode::dataLength, QRRawCode::eccLength, FrameFiller_next(), FrameFiller_set(), free(), _QRinput::level, malloc(), Mask_makeMask(), Mask_mask(), _QRinput::mqr, QR_ECLEVEL_H, QR_ECLEVEL_L, QRcode_new(), QRraw_free(), QRraw_getCode(), QRraw_new(), QRspec_getRemainder(), QRspec_getWidth(), QRspec_newFrame(), QRSPEC_VERSION_MAX, _QRinput::version, and QRRawCode::version.
Referenced by QRcode_encodeInput().
QRcode* QRcode_encodeMaskMQR (QRinput * input, int mask)
Definition at line 517 of file qrencode.c.
References MQRRawCode::dataLength, MQRRawCode::eccLength, FrameFiller_next(), FrameFiller_set(), free(), _QRinput::level, malloc(), MMask_makeMask(), MMask_mask(), _QRinput::mqr, MQRraw_free(), MQRraw_getCode(), MQRraw_new(), MQRspec_getWidth(), MQRspec_newFrame(), MQRSPEC_VERSION_MAX, MQRRawCode::oddbits, QR_ECLEVEL_L, QR_ECLEVEL_Q, QRcode_new(), _QRinput::version, and MQRRawCode::version.
Referenced by QRcode_encodeInput().
QRcode* QRcode_new (int version, int width, unsigned char * data)
Definition at line 407 of file qrencode.c.
References QRcode::data, malloc(), QRcode::version, and QRcode::width.
Referenced by QRcode_encodeMask(), and QRcode_encodeMaskMQR().
void QRraw_free (QRRawCode * raw)
Definition at line 178 of file qrencode.c.
References QRRawCode::datacode, QRRawCode::ecccode, free(), and QRRawCode::rsblock.
Referenced by QRcode_encodeMask(), and QRraw_new().
unsigned char QRraw_getCode (QRRawCode * raw)
Return a code (byte).
This function can be called iteratively.
Parameters
raw raw code.
Returns
code
Definition at line 155 of file qrencode.c.
References QRRawCode::b1, QRRawCode::blocks, QRRawCode::count, RSblock::data, RSblock::dataLength, QRRawCode::dataLength, RSblock::ecc, QRRawCode::eccLength, and QRRawCode::rsblock.
Referenced by QRcode_encodeMask().
QRRawCode* QRraw_new (QRinput * input)
Definition at line 105 of file qrencode.c.
References QRRawCode::b1, QRRawCode::blocks, calloc(), QRRawCode::count, QRRawCode::datacode, QRRawCode::dataLength, QRRawCode::ecccode, QRRawCode::eccLength, free(), _QRinput::level, malloc(), QRinput_getByteStream(), QRraw_free(), QRspec_getEccSpec(), QRspec_rsBlockNum, QRspec_rsBlockNum1, QRspec_rsDataLength, QRspec_rsEccLength, QRRawCode::rsblock, RSblock_init(), _QRinput::version, and QRRawCode::version.
Referenced by QRcode_encodeMask().