TTKMusicPlayer: MusicPlayedListPopWidget Class Reference
MusicPlayedListPopWidget Class Reference
The class of the played list pop widget.
#include <musicplayedlistpopwidget.h>
Public Slots
virtual void popupMenu () overridefinal
void removeItemAt (const TTKIntList &index)
void clearItems ()
void itemDoubleClicked ()
void itemDoubleClicked (int row, int column)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicPlayedListPopWidget (QWidget *parent=nullptr)
~MusicPlayedListPopWidget ()
void setPlaylist (MusicPlaylist *playlist)
void clear ()
void clearQueueState ()
void updatePlayedList (const TTK::IndexPropertyList &indexs)
void remove (int index)
void remove (int playlistRow, const QString &path)
void remove (int playlistRow, const MusicSong &song)
void remove (int playlistRow, const MusicSongList &songs)
void append (const MusicSongList &songs)
void append (int playlistRow, const MusicSong &song)
void append (int playlistRow, const MusicSongList &songs)
void insert (int playlistRow, const MusicSong &song)
void insert (int playlistRow, const MusicSongList &songs)
void insert (int playlistRow, int index, const MusicSong &song)
void insert (int playlistRow, int index, const MusicSongList &song)
void selectCurrentIndex ()
void selectCurrentIndex (int playlistRow, const MusicSong &song)
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Static Public Member Functions
static MusicPlayedListPopWidget * instance ()
Private Member Functions
void initialize ()
QWidget * createContainerWidget ()
void setPlaylistSongs ()
void setPlaylistCount (int count)
void clearPlaylist ()
Private Attributes
QList< QLabel * > m_labels
MusicPlaylist * m_playlist
MusicSongList m_songList
QScrollArea * m_scrollArea
MusicSongsListPlayedTableWidget * m_tableWidget
Static Private Attributes
static MusicPlayedListPopWidget * m_instance = nullptr
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the played list pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 55 of file musicplayedlistpopwidget.h.
Constructor & Destructor Documentation
MusicPlayedListPopWidget::MusicPlayedListPopWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 38 of file musicplayedlistpopwidget.cpp.
References TTK::UI::BtnPlayedList, initialize(), and m_instance.
MusicPlayedListPopWidget::~MusicPlayedListPopWidget ()
Object destructor.
Definition at line 50 of file musicplayedlistpopwidget.cpp.
References m_labels, and m_tableWidget.
Member Function Documentation
void MusicPlayedListPopWidget::append (const MusicSongList & songs)
Append music to data list.
Definition at line 146 of file musicplayedlistpopwidget.cpp.
References clear(), m_songList, and setPlaylistSongs().
Referenced by MusicSongsContainerWidget::addToPlayedList(), and MusicSongsListPlayTableWidget::addToPlayedList().
void MusicPlayedListPopWidget::append (int playlistRow, const MusicSong & song)
Append music to data list.
Definition at line 153 of file musicplayedlistpopwidget.cpp.
References MusicPlaylist::append(), m_playlist, m_songList, MusicSong::path(), and setPlaylistSongs().
void MusicPlayedListPopWidget::append (int playlistRow, const MusicSongList & songs)
Append music to data list.
Definition at line 160 of file musicplayedlistpopwidget.cpp.
References MusicPlaylist::append(), m_playlist, m_songList, qAsConst, and setPlaylistSongs().
void MusicPlayedListPopWidget::clear ()
Clear music data list.
Definition at line 66 of file musicplayedlistpopwidget.cpp.
References m_songList, m_tableWidget, MusicSongsListPlayedTableWidget::removeItems(), and setPlaylistCount().
Referenced by append(), and MusicSongsContainerWidget::updateSongItem().
void MusicPlayedListPopWidget::clearItems () slot
Remove all items from list.
Definition at line 309 of file musicplayedlistpopwidget.cpp.
References MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), clearPlaylist(), m_songList, and m_tableWidget.
Referenced by createContainerWidget().
void MusicPlayedListPopWidget::clearPlaylist () private
Set play state to pause or stop.
Definition at line 469 of file musicplayedlistpopwidget.cpp.
References MusicApplication::instance(), m_songList, m_tableWidget, MusicApplication::playIndexBy(), setPlaylistCount(), MusicAbstractSongsListTableWidget::setPlayRowIndex(), and TTK_NORMAL_LEVEL.
Referenced by clearItems(), and removeItemAt().
void MusicPlayedListPopWidget::clearQueueState ()
Clear play queue state.
Definition at line 73 of file musicplayedlistpopwidget.cpp.
References MusicSongsListPlayedTableWidget::clearQueueState(), and m_tableWidget.
Referenced by itemDoubleClicked(), and removeItemAt().
QWidget * MusicPlayedListPopWidget::createContainerWidget () private
Create container widget.
Definition at line 397 of file musicplayedlistpopwidget.cpp.
References TTK::UI::BackgroundStyle10, clearItems(), TTK::UI::ColorStyle08, TTK::UI::FontStyle01, TTK::UI::FontStyle03, MusicToolMenuWidget::m_menu, TTK::UI::TinyBtnClose, TTK::UI::TinyBtnDelete, and TTK::UI::TinyBtnShare.
Referenced by initialize().
void MusicPlayedListPopWidget::initialize () private
Create all widget in layout.
Definition at line 346 of file musicplayedlistpopwidget.cpp.
References TTK::UI::BackgroundStyle10, createContainerWidget(), TTK::Widget::generateVScrollAreaStyle(), itemDoubleClicked(), LEFT_SIDE_WIDTH_MIN, MusicToolMenuWidget::m_containWidget, m_labels, m_scrollArea, m_songList, m_tableWidget, MAX_SIZE, removeItemAt(), MusicSmoothMovingTableWidget::setMovedScrollBar(), and MusicAbstractSongsListTableWidget::setSongsList().
Referenced by MusicPlayedListPopWidget().
void MusicPlayedListPopWidget::insert (int playlistRow, const MusicSong & song)
Insert music after played music index.
Definition at line 171 of file musicplayedlistpopwidget.cpp.
References m_tableWidget, and MusicAbstractSongsListTableWidget::playRowIndex().
Referenced by MusicSongsContainerWidget::addToPlayLater(), MusicSongsListPlayTableWidget::addToPlayLater(), and insert().
void MusicPlayedListPopWidget::insert (int playlistRow, const MusicSongList & songs)
Insert music by given index.
Definition at line 176 of file musicplayedlistpopwidget.cpp.
References insert(), m_tableWidget, and MusicAbstractSongsListTableWidget::playRowIndex().
void MusicPlayedListPopWidget::insert (int playlistRow, int index, const MusicSong & song)
Insert music by given index.
Definition at line 181 of file musicplayedlistpopwidget.cpp.
References MusicPlaylist::appendQueue(), m_playlist, m_songList, m_tableWidget, MusicSong::path(), MusicAbstractSongsListTableWidget::playRowIndex(), qAsConst, MusicPlaylist::queueList(), MusicSongsListPlayedTableWidget::removeItems(), MusicSongsListPlayedTableWidget::selectPlayedRow(), setPlaylistSongs(), MusicAbstractSongsListTableWidget::setPlayRowIndex(), and MusicSongsListPlayedTableWidget::setQueueState().
void MusicPlayedListPopWidget::insert (int playlistRow, int index, const MusicSongList & song)
Insert music by given index.
Definition at line 204 of file musicplayedlistpopwidget.cpp.
References MusicPlaylist::appendQueue(), m_playlist, m_songList, m_tableWidget, MusicSong::path(), MusicAbstractSongsListTableWidget::playRowIndex(), qAsConst, MusicPlaylist::queueList(), MusicSongsListPlayedTableWidget::removeItems(), MusicSongsListPlayedTableWidget::selectPlayedRow(), setPlaylistSongs(), MusicAbstractSongsListTableWidget::setPlayRowIndex(), and MusicSongsListPlayedTableWidget::setQueueState().
MusicPlayedListPopWidget * MusicPlayedListPopWidget::instance () static
Get class object instance.
Definition at line 56 of file musicplayedlistpopwidget.cpp.
References m_instance.
Referenced by MusicSongsContainerWidget::addToPlayedList(), MusicSongsListPlayTableWidget::addToPlayedList(), MusicSongsContainerWidget::addToPlayLater(), MusicSongsListPlayTableWidget::addToPlayLater(), MusicSongsContainerWidget::deleteRowItem(), MusicSongsContainerWidget::itemIndexSwaped(), MusicSongsContainerWidget::updatePlayedList(), and MusicSongsContainerWidget::updateSongItem().
void MusicPlayedListPopWidget::itemDoubleClicked () slot
List cell item double clicked.
Definition at line 326 of file musicplayedlistpopwidget.cpp.
References clearQueueState(), MusicApplication::instance(), m_playlist, m_tableWidget, MusicApplication::playedIndexBy(), and MusicPlaylist::removeQueue().
Referenced by initialize(), and itemDoubleClicked().
void MusicPlayedListPopWidget::itemDoubleClicked (int row, int column) slot
List cell double clicked.
Definition at line 339 of file musicplayedlistpopwidget.cpp.
References itemDoubleClicked(), TTK_SIGNLE_SHOT, and TTK_SLOT.
void MusicPlayedListPopWidget::popupMenu () final override virtual slot
To popup menu.
Definition at line 243 of file musicplayedlistpopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, m_tableWidget, and MusicSongsListPlayedTableWidget::selectPlayedRow().
void MusicPlayedListPopWidget::remove (int index)
Remove music from data list.
Definition at line 83 of file musicplayedlistpopwidget.cpp.
References MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), m_playlist, m_songList, m_tableWidget, MusicPlaylist::remove(), setPlaylistSongs(), MusicAbstractSongsListTableWidget::setPlayRowIndex(), and TTK_NORMAL_LEVEL.
Referenced by MusicSongsContainerWidget::deleteRowItem().
void MusicPlayedListPopWidget::remove (int playlistRow, const QString & path)
Remove music from data list.
Definition at line 100 of file musicplayedlistpopwidget.cpp.
References MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), m_playlist, m_songList, m_tableWidget, MusicPlaylist::remove(), setPlaylistSongs(), MusicAbstractSongsListTableWidget::setPlayRowIndex(), and TTK_NORMAL_LEVEL.
void MusicPlayedListPopWidget::remove (int playlistRow, const MusicSong & song)
Remove music from data list.
Definition at line 119 of file musicplayedlistpopwidget.cpp.
References MusicSong::path().
void MusicPlayedListPopWidget::remove (int playlistRow, const MusicSongList & songs)
Remove music from data list.
Definition at line 124 of file musicplayedlistpopwidget.cpp.
References MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), m_playlist, m_songList, m_tableWidget, qAsConst, MusicPlaylist::remove(), setPlaylistSongs(), MusicAbstractSongsListTableWidget::setPlayRowIndex(), and TTK_NORMAL_LEVEL.
void MusicPlayedListPopWidget::removeItemAt (const TTKIntList & index) slot
Remove items from indexs.
Definition at line 253 of file musicplayedlistpopwidget.cpp.
References clearPlaylist(), clearQueueState(), MusicApplication::instance(), MusicPlaylist::isEmpty(), MusicApplication::isPlaying(), m_playlist, m_songList, m_tableWidget, MusicApplication::playNext(), MusicAbstractSongsListTableWidget::playRowIndex(), MusicPlaylist::remove(), MusicSongsListPlayedTableWidget::selectRow(), MusicPlaylist::setCurrentIndex(), setPlaylistCount(), and TTK_LOW_LEVEL.
Referenced by initialize().
void MusicPlayedListPopWidget::selectCurrentIndex ()
Set current select played music index.
Definition at line 231 of file musicplayedlistpopwidget.cpp.
References MusicPlaylist::currentIndex(), m_playlist, m_tableWidget, and MusicSongsListPlayedTableWidget::selectRow().
Referenced by MusicSongsContainerWidget::itemIndexSwaped(), and selectCurrentIndex().
void MusicPlayedListPopWidget::selectCurrentIndex (int playlistRow, const MusicSong & song)
Set current select played music index.
Definition at line 237 of file musicplayedlistpopwidget.cpp.
References m_playlist, MusicSong::path(), selectCurrentIndex(), and MusicPlaylist::setCurrentIndex().
void MusicPlayedListPopWidget::setPlaylist (MusicPlaylist * playlist)
Set current play list.
Definition at line 61 of file musicplayedlistpopwidget.cpp.
References m_playlist.
void MusicPlayedListPopWidget::setPlaylistCount (int count) private
Set play list count.
Definition at line 450 of file musicplayedlistpopwidget.cpp.
References m_labels, and MAX_SIZE.
Referenced by clear(), clearPlaylist(), removeItemAt(), and setPlaylistSongs().
void MusicPlayedListPopWidget::setPlaylistSongs () private
Set play list songs files.
Definition at line 444 of file musicplayedlistpopwidget.cpp.
References m_songList, m_tableWidget, setPlaylistCount(), and MusicSongsListPlayedTableWidget::updateSongsList().
Referenced by append(), insert(), and remove().
void MusicPlayedListPopWidget::updatePlayedList (const TTK::IndexPropertyList & indexs)
Update current played item list.
Definition at line 78 of file musicplayedlistpopwidget.cpp.
References m_playlist, and MusicPlaylist::update().
Referenced by MusicSongsContainerWidget::updatePlayedList().
Member Data Documentation
MusicPlayedListPopWidget * MusicPlayedListPopWidget::m_instance = nullptr static private
Definition at line 198 of file musicplayedlistpopwidget.h.
Referenced by instance(), and MusicPlayedListPopWidget().
QList<QLabel*> MusicPlayedListPopWidget::m_labels private
Definition at line 192 of file musicplayedlistpopwidget.h.
Referenced by initialize(), setPlaylistCount(), and ~MusicPlayedListPopWidget().
MusicPlaylist* MusicPlayedListPopWidget::m_playlist private
Definition at line 193 of file musicplayedlistpopwidget.h.
Referenced by append(), insert(), itemDoubleClicked(), remove(), removeItemAt(), selectCurrentIndex(), setPlaylist(), and updatePlayedList().
QScrollArea* MusicPlayedListPopWidget::m_scrollArea private
Definition at line 195 of file musicplayedlistpopwidget.h.
Referenced by initialize().
MusicSongList MusicPlayedListPopWidget::m_songList private
Definition at line 194 of file musicplayedlistpopwidget.h.
Referenced by append(), clear(), clearItems(), clearPlaylist(), initialize(), insert(), remove(), removeItemAt(), and setPlaylistSongs().
MusicSongsListPlayedTableWidget* MusicPlayedListPopWidget::m_tableWidget private
Definition at line 196 of file musicplayedlistpopwidget.h.
Referenced by clear(), clearItems(), clearPlaylist(), clearQueueState(), initialize(), insert(), itemDoubleClicked(), popupMenu(), remove(), removeItemAt(), selectCurrentIndex(), setPlaylistSongs(), and ~MusicPlayedListPopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplayedlistpopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplayedlistpopwidget.cpp