TTKMusicplayer: MusicToplistQueryCategoryPopWidget Class Reference
MusicToplistQueryCategoryPopWidget Class Reference
The class of the toplist music query category pop widget.
#include <musictoplistquerycategorypopwidget.h>
Public Slots
virtual void popupMenu () overridefinal
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicToplistQueryCategoryPopWidget (QWidget *parent=nullptr)
void setCategory (const QString &server, QObject *obj)
void closeMenu ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initialize ()
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the toplist music query category pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 65 of file musictoplistquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicToplistQueryCategoryPopWidget::MusicToplistQueryCategoryPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 57 of file musictoplistquerycategorypopwidget.cpp.
References initialize().
Member Function Documentation
void MusicToplistQueryCategoryPopWidget::closeMenu ()
Close the menu dialog.
Definition at line 90 of file musictoplistquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
Referenced by MusicToplistQueryWidget::categoryChanged().
void MusicToplistQueryCategoryPopWidget::initialize () protected
Create all widget in layout.
Definition at line 100 of file musictoplistquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, MusicUIObject::MQSSBackgroundStyle12, MusicUIObject::MQSSBorderStyle03, MusicUIObject::MQSSMenuStyle05, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicToplistQueryCategoryPopWidget().
void MusicToplistQueryCategoryPopWidget::popupMenu () final override virtual slot
To popup menu.
Definition at line 95 of file musictoplistquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
void MusicToplistQueryCategoryPopWidget::setCategory (const QString & server, QObject * obj)
Set current category by input server.
Definition at line 63 of file musictoplistquerycategorypopwidget.cpp.
References MusicCategoryConfigManager::fromFile(), MusicUtils::Widget::generateVScrollAreaFormat(), MusicToolMenuWidget::m_containWidget, MusicUIObject::MQSSBackgroundStyle12, MusicCategoryConfigManager::readBuffer(), MusicToplistQueryCategoryItem::setCategory(), and MusicCategoryConfigManager::TopList.
Referenced by MusicToplistQueryWidget::createLabels().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musictoplistquerycategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musictoplistquerycategorypopwidget.cpp