TTKMusicplayer: MusicAbstractMVRadioRequest Class Reference
MusicAbstractMVRadioRequest Class Reference
The class of music mv radio request abstract.
#include <musicabstractmvradiorequest.h>
Signals
void createCategoryItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Public Member Functions
MusicAbstractMVRadioRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &text) override
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSingleSearch (const QString &text)
void setQueryQuality (const QString &qual)
QString getQueryQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getQueryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int getPageSize () const
int getTotalSize () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 getUrlFileSize (const QString &url)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of music mv radio request abstract.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicabstractmvradiorequest.h.
Constructor & Destructor Documentation
MusicAbstractMVRadioRequest::MusicAbstractMVRadioRequest (QObject * parent = nullptr) explicit
Definition at line 4 of file musicabstractmvradiorequest.cpp.
References MusicAbstractQueryRequest::m_queryText.
Member Function Documentation
void MusicAbstractMVRadioRequest::createCategoryItem (const MusicResultsItem & item) signal
Create the current category item.
Referenced by MusicMVRadioCategoryRequest::downLoadFinished(), and MusicMVRadioProgramRequest::downLoadFinished().
void MusicAbstractMVRadioRequest::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicAbstractQueryRequest.
Definition at line 10 of file musicabstractmvradiorequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractQueryRequest::downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_queryText, MusicAbstractNetwork::m_reply, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MV_CATEGORY_URL, MusicObject::NetworkError, and MusicAbstractNetwork::replyError().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/mv/musicabstractmvradiorequest.h
TTKModule/TTKCore/musicNetworkKits/radio/mv/musicabstractmvradiorequest.cpp