TTKMusicPlayer: QSyncUploadData Class Reference
QSyncUploadData Class Reference
The class of the sync cloud upload data.
#include <qsyncuploaddata.h>
Signals
void uploadFileFinished (const QString &time)
void uploadProgressChanged (const QString &time, qint64 bytesSent, qint64 bytesTotal)
Public Member Functions
QSyncUploadData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void request (const QString &time, const QString &bucket, const QString &fileName, const QString &filePath)
Public Member Functions inherited from QSyncDataInterface
QSyncDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Private Slots
virtual void receiveDataFromServer () overridefinal
void uploadProgress (qint64 percent, qint64 total)
Additional Inherited Members
Protected Slots inherited from QSyncDataInterface
virtual void receiveDataFromServer ()=0
void replyError (QNetworkReply::NetworkError error)
Protected Member Functions inherited from QSyncDataInterface
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
QSyncDataInterface (QSyncDataInterfacePrivate &pvt, QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Detailed Description
The class of the sync cloud upload data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qsyncuploaddata.h.
Constructor & Destructor Documentation
QSyncUploadData::QSyncUploadData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object constructor.
Definition at line 22 of file qsyncuploaddata.cpp.
References TTK_D.
Member Function Documentation
void QSyncUploadData::receiveDataFromServer () final override private virtual slot
Receive data from server finshed.
Definition at line 74 of file qsyncuploaddata.cpp.
References TTK_D, TTK_NAN_STR, TTKObjectCast, and uploadFileFinished().
Referenced by request().
void QSyncUploadData::request (const QString & time, const QString & bucket, const QString & fileName, const QString & filePath)
Get uplaod data operator.
Definition at line 29 of file qsyncuploaddata.cpp.
References QSyncUtils::GMT(), QSyncConfig::HOST, HTTP_PROTOCOL, QtNetworkErrorConnect, receiveDataFromServer(), QSyncDataInterface::replyError(), TTK_D, TTK_DOT, TTK_SEPARATOR, TTK_SLOT, uploadProgress(), and uploadProgressChanged().
Referenced by MusicCloudManagerTableWidget::startToUploadFile().
void QSyncUploadData::uploadFileFinished (const QString & time) signal
Uplaod file finshed.
Referenced by receiveDataFromServer().
void QSyncUploadData::uploadProgress (qint64 percent, qint64 total) private slot
Show upload progress.
Definition at line 96 of file qsyncuploaddata.cpp.
References TTK_D, and uploadProgressChanged().
Referenced by request().
void QSyncUploadData::uploadProgressChanged (const QString & time, qint64 bytesSent, qint64 bytesTotal) signal
Show upload progress.
Referenced by request(), and uploadProgress().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncuploaddata.h
TTKThirdParty/TTKExtras/qsync/qsyncuploaddata.cpp