TTKMusicPlayer: MusicCloudToolBoxWidget Class Reference
MusicCloudToolBoxWidget Class Reference
The class of the cloud tool box widget.
#include <musiccloudtoolboxwidget.h>
Public Slots
void updateItemTitle (int index)
Public Slots inherited from MusicFunctionToolBoxWidget
void setCurrentIndex (int index)
void itemIndexChanged (int index)
void setTransparent (int alpha)
Public Member Functions
MusicCloudToolBoxWidget (QWidget *parent=nullptr)
~MusicCloudToolBoxWidget ()
Public Member Functions inherited from MusicFunctionToolBoxWidget
MusicFunctionToolBoxWidget (QWidget *parent=nullptr)
~MusicFunctionToolBoxWidget ()
void addCellItem (QWidget *item, const QString &text)
void removeItem (QWidget *item)
void swapItem (int start, int end)
void setTitle (QWidget *item, const QString &text)
void resizeScrollIndex (int index) const
int currentIndex () const
int count () const
Private Member Functions
void createWidgetItem (MusicAbstractDownloadTableWidget *widget, const QString &text, int index)
virtual MusicFunctionToolBoxWidgetItem * initialItem (QWidget *item, const QString &text) overridefinal
Private Attributes
MusicSongItemList m_songItems
Additional Inherited Members
Protected Member Functions inherited from MusicFunctionToolBoxWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
int foundMappedIndex (int index)
Protected Attributes inherited from MusicFunctionToolBoxWidget
int m_currentIndex
int m_itemIndexRaise
QVBoxLayout * m_layout
QScrollArea * m_scrollArea
QWidget * m_contentsWidget
MusicToolBoxWidgetItemList m_itemList
Detailed Description
The class of the cloud tool box widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musiccloudtoolboxwidget.h.
Constructor & Destructor Documentation
MusicCloudToolBoxWidget::MusicCloudToolBoxWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file musiccloudtoolboxwidget.cpp.
References createWidgetItem(), m_songItems, and updateItemTitle().
MusicCloudToolBoxWidget::~MusicCloudToolBoxWidget ()
Object destructor.
Definition at line 19 of file musiccloudtoolboxwidget.cpp.
References m_songItems.
Member Function Documentation
void MusicCloudToolBoxWidget::createWidgetItem (MusicAbstractDownloadTableWidget * widget, const QString & text, int index) private
Create widget item.
Definition at line 39 of file musiccloudtoolboxwidget.cpp.
References MusicFunctionToolBoxWidget::addCellItem(), MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, MusicSongItem::m_itemWidget, m_songItems, MusicSongItem::m_songs, MusicAbstractSongsListTableWidget::setPlaylistRow(), MusicAbstractSongsListTableWidget::setSongsList(), and MusicFunctionToolBoxWidget::setTitle().
Referenced by MusicCloudToolBoxWidget().
MusicFunctionToolBoxWidgetItem * MusicCloudToolBoxWidget::initialItem (QWidget * item, const QString & text) final override private virtual
Create item.
Implements MusicFunctionToolBoxWidget.
Definition at line 53 of file musiccloudtoolboxwidget.cpp.
References MusicFunctionToolBoxWidgetItem::addCellItem(), MusicFunctionToolBoxWidget::m_itemIndexRaise, and MusicFunctionToolBoxWidgetItem::setExpand().
void MusicCloudToolBoxWidget::updateItemTitle (int index) slot
Update item title.
Definition at line 28 of file musiccloudtoolboxwidget.cpp.
References MusicSongItem::m_itemName, MusicSongItem::m_itemWidget, m_songItems, MusicSongItem::m_songs, and MusicFunctionToolBoxWidget::setTitle().
Referenced by MusicCloudToolBoxWidget().
Member Data Documentation
MusicSongItemList MusicCloudToolBoxWidget::m_songItems private
Definition at line 62 of file musiccloudtoolboxwidget.h.
Referenced by createWidgetItem(), MusicCloudToolBoxWidget(), updateItemTitle(), and ~MusicCloudToolBoxWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudtoolboxwidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudtoolboxwidget.cpp