TTKMusicPlayer: MusicWebMVRadioQueryWidget Class Reference
MusicWebMVRadioQueryWidget Class Reference
The class of the music mv query widget.
#include <musicwebmvradioquerywidget.h>
Public Slots
void createMVRadioCategoryItem (const MusicResultDataItem &item)
void currentRadioClicked (const MusicResultDataItem &item)
void backToMainMenuClicked ()
void categoryChanged (const MusicResultsCategoryItem &category)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicWebMVRadioQueryWidget (QWidget *parent=nullptr)
~MusicWebMVRadioQueryWidget ()
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameByID (const QString &id) overridefinal
virtual void resizeWidget () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Public Member Functions inherited from TTKAbstractResizeInterface
TTKAbstractResizeInterface ()=default
Private Attributes
bool m_initialized
QGridLayout * m_gridLayout
MusicWebMVRadioInfoWidget * m_infoWidget
MusicWebMVRadioQueryCategoryPopWidget * m_categoryButton
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultDataItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Module m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of the music mv query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 85 of file musicwebmvradioquerywidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioQueryWidget::MusicWebMVRadioQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 103 of file musicwebmvradioquerywidget.cpp.
References createMVRadioCategoryItem(), m_categoryButton, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_infoWidget, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, and MusicAbstractItemQueryWidget::m_networkRequest.
MusicWebMVRadioQueryWidget::~MusicWebMVRadioQueryWidget ()
Definition at line 120 of file musicwebmvradioquerywidget.cpp.
References m_categoryButton, m_gridLayout, and m_infoWidget.
Member Function Documentation
void MusicWebMVRadioQueryWidget::backToMainMenuClicked () slot
Set current index to main menu page.
Definition at line 220 of file musicwebmvradioquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_container.
Referenced by currentRadioClicked().
void MusicWebMVRadioQueryWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 225 of file musicwebmvradioquerywidget.cpp.
References MusicWebMVRadioQueryCategoryPopWidget::closeMenu(), m_categoryButton, m_gridLayout, MusicResultsCategoryItem::m_key, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songNameFull, MusicResultsCategoryItem::m_value, MusicAbstractQueryRequest::Other, and MusicAbstractQueryRequest::startToSearch().
void MusicWebMVRadioQueryWidget::createMVRadioCategoryItem (const MusicResultDataItem & item) slot
Create the current category item.
Definition at line 160 of file musicwebmvradioquerywidget.cpp.
References TTK::UI::ColorStyle06, currentRadioClicked(), TTK::Widget::generateVScrollAreaFormat(), LINE_SPACING_SIZE, m_categoryButton, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_statusLabel, MUSIC_MOVIE_RADIO, QUERY_WIDGET_WIDTH, MusicWebMVRadioQueryCategoryPopWidget::setCategory(), MusicWebMVRadioQueryItemWidget::setResultDataItem(), and TTKObjectCast.
Referenced by MusicWebMVRadioQueryWidget().
void MusicWebMVRadioQueryWidget::currentRadioClicked (const MusicResultDataItem & item) slot
Current item clicked.
Definition at line 209 of file musicwebmvradioquerywidget.cpp.
References backToMainMenuClicked(), MusicAbstractItemQueryWidget::m_container, MusicResultDataItem::m_id, m_infoWidget, and MusicWebMVRadioInfoWidget::setSongName().
Referenced by createMVRadioCategoryItem().
void MusicWebMVRadioQueryWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 138 of file musicwebmvradioquerywidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, m_infoWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, QUERY_WIDGET_WIDTH, and MusicWebMVRadioInfoWidget::resizeWidget().
void MusicWebMVRadioQueryWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 127 of file musicwebmvradioquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractQueryRequest::Other, MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicRightAreaWidget::functionClicked().
void MusicWebMVRadioQueryWidget::setSongNameByID (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 133 of file musicwebmvradioquerywidget.cpp.
Member Data Documentation
MusicWebMVRadioQueryCategoryPopWidget* MusicWebMVRadioQueryWidget::m_categoryButton private
Definition at line 131 of file musicwebmvradioquerywidget.h.
Referenced by categoryChanged(), createMVRadioCategoryItem(), MusicWebMVRadioQueryWidget(), and ~MusicWebMVRadioQueryWidget().
QGridLayout* MusicWebMVRadioQueryWidget::m_gridLayout private
Definition at line 129 of file musicwebmvradioquerywidget.h.
Referenced by categoryChanged(), createMVRadioCategoryItem(), MusicWebMVRadioQueryWidget(), resizeWidget(), and ~MusicWebMVRadioQueryWidget().
MusicWebMVRadioInfoWidget* MusicWebMVRadioQueryWidget::m_infoWidget private
Definition at line 130 of file musicwebmvradioquerywidget.h.
Referenced by currentRadioClicked(), MusicWebMVRadioQueryWidget(), resizeWidget(), and ~MusicWebMVRadioQueryWidget().
bool MusicWebMVRadioQueryWidget::m_initialized private
Definition at line 128 of file musicwebmvradioquerywidget.h.
Referenced by createMVRadioCategoryItem(), and MusicWebMVRadioQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerywidget.cpp