TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/mask.h File Reference
mask.h File Reference
Functions
unsigned char * Mask_makeMask (int width, unsigned char *frame, int mask, QRecLevel level)
unsigned char * Mask_mask (int width, unsigned char *frame, QRecLevel level)
Function Documentation
unsigned char* Mask_makeMask (int width, unsigned char * frame, int mask, QRecLevel level)
Definition at line 162 of file mask.c.
References malloc(), Mask_writeFormatInformation(), maskMakers, and maskNum.
Referenced by QRcode_encodeMask().
unsigned char* Mask_mask (int width, unsigned char * frame, QRecLevel level)
Definition at line 320 of file mask.c.
References free(), malloc(), Mask_evaluateSymbol(), Mask_writeFormatInformation(), maskMakers, maskNum, and N4.
Referenced by QRcode_encodeMask().