TTKMusicplayer: MusicRemoteWidgetForSimpleStyle Class Reference
MusicRemoteWidgetForSimpleStyle Class Reference
The class of the desktop simple remote widget.
#include <musicremotewidgetforsimplestyle.h>
Public Member Functions
MusicRemoteWidgetForSimpleStyle (QWidget *parent=0)
virtual ~MusicRemoteWidgetForSimpleStyle ()
virtual void setLabelText (const QString &value) override
Public Member Functions inherited from MusicRemoteWidget
MusicRemoteWidget (QWidget *parent=0)
virtual ~MusicRemoteWidget ()
void showPlayStatus (bool status) const
void setVolumeValue (int index)
int mapRemoteTypeIndex ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicRemoteWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Attributes
MusicMarqueeWidget * m_songNameLabel
Protected Attributes inherited from MusicRemoteWidget
QPushButton * m_showMainWindow
QPushButton * m_PreSongButton
QPushButton * m_NextSongButton
QPushButton * m_PlayButton
QPushButton * m_SettingButton
QWidget * m_mainWidget
QWidget * m_volumeWidget
QToolButton * m_volumeButton
MusicClickedSlider * m_volumeSlider
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Public Types inherited from MusicRemoteWidget
enum RemoteType {
Null = 0, Circle, Square, Rectangle,
SimpleStyle, ComplexStyle, Diamond, Ripples
}
Public Slots inherited from MusicRemoteWidget
void musicVolumeChanged (int value)
void show ()
bool close ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals inherited from MusicRemoteWidget
void musicWindowSignal ()
void musicKeySignal ()
void musicPlayPreviousSignal ()
void musicPlayNextSignal ()
void musicVolumeSignal (int value)
void musicSettingSignal ()
void musicRemoteTypeChanged (QAction *type)
Protected Member Functions inherited from MusicRemoteWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
void adjustPostion (QWidget *w)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the desktop simple remote widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 19 of file musicremotewidgetforsimplestyle.h.
Constructor & Destructor Documentation
MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 5 of file musicremotewidgetforsimplestyle.cpp.
References MusicRemoteWidget::adjustPostion(), MusicRemoteWidget::m_mainWidget, MusicRemoteWidget::m_NextSongButton, MusicRemoteWidget::m_PlayButton, MusicRemoteWidget::m_PreSongButton, MusicRemoteWidget::m_SettingButton, MusicRemoteWidget::m_showMainWindow, m_songNameLabel, MusicRemoteWidget::m_volumeWidget, and MusicUIObject::MWidgetStyle01.
MusicRemoteWidgetForSimpleStyle::~MusicRemoteWidgetForSimpleStyle () virtual
Definition at line 32 of file musicremotewidgetforsimplestyle.cpp.
References m_songNameLabel.
Member Function Documentation
QString MusicRemoteWidgetForSimpleStyle::getClassName () static
Get class object name.
Definition at line 37 of file musicremotewidgetforsimplestyle.cpp.
void MusicRemoteWidgetForSimpleStyle::setLabelText (const QString & value) override virtual
Set current song text.
Reimplemented from MusicRemoteWidget.
Definition at line 42 of file musicremotewidgetforsimplestyle.cpp.
References MusicUtils::Widget::elidedText(), m_songNameLabel, and MusicMarqueeWidget::setText().
Member Data Documentation
MusicMarqueeWidget* MusicRemoteWidgetForSimpleStyle::m_songNameLabel protected
Definition at line 40 of file musicremotewidgetforsimplestyle.h.
Referenced by MusicRemoteWidgetForSimpleStyle(), setLabelText(), and ~MusicRemoteWidgetForSimpleStyle().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforsimplestyle.h
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforsimplestyle.cpp