TTKMusicplayer: MusicSemaphoreLoop Class Reference
MusicSemaphoreLoop Class Reference
The class of the semaphore event loop.
#include <musicsemaphoreloop.h>
Public Member Functions
MusicSemaphoreLoop (QObject *parent=0)
~MusicSemaphoreLoop ()
int exec (ProcessEventsFlags flags=AllEvents)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
QTimer m_timer
Detailed Description
The class of the semaphore event loop.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicsemaphoreloop.h.
Constructor & Destructor Documentation
MusicSemaphoreLoop::MusicSemaphoreLoop (QObject * parent = 0) explicit
Object contsructor.
Definition at line 4 of file musicsemaphoreloop.cpp.
References m_timer, and MT_S2MS.
MusicSemaphoreLoop::~MusicSemaphoreLoop ()
Definition at line 11 of file musicsemaphoreloop.cpp.
References m_timer.
Member Function Documentation
int MusicSemaphoreLoop::exec (ProcessEventsFlags flags = AllEvents)
Event loop start.
Definition at line 22 of file musicsemaphoreloop.cpp.
References m_timer.
Referenced by MusicVolumeGainWidget::addFileButtonClicked(), MusicVolumeGainWidget::addFilesButtonClicked(), MusicVolumeGainWidget::applyButtonClicked(), MusicSongSharingWidget::confirmButtonClicked(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicIdentifySongsWidget::detectedTimeOut(), MusicQueryFoundTableWidget::downloadDataFrom(), MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDataTagDownloadThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicKWArtistSimilarThread::getArtistIdName(), MusicMGArtistSimilarThread::getArtistInfo(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryWSArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicCloudSharedSongTableWidget::getKey(), MusicIdentifySongsThread::getKey(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryWSPlaylistThread::getMoreDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQQInterface::getMusicKey(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryMGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), MusicWSDiscoverListThread::getUpdateTime(), MusicDownLoadQueryWSToplistThread::getUpdateTime(), MusicDownLoadQueryThreadAbstract::getUrlFileSize(), MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicDownLoadKWInterface::readFromMusicLLAttribute(), MusicDownLoadMGInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAlbumInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadWSInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadBDInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttributeNew(), MusicDownLoadXMInterface::readFromMusicSongLrc(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), MusicDownLoadKWInterface::readFromMusicSongPic(), MusicCommentsWidget::setCurrentSongName(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicWYTranslationThread::startToDownload(), MusicMGSongCommentsThread::startToSearch(), MusicQQSongCommentsThread::startToSearch(), MusicWSSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicBDSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicWYSongCommentsThread::startToSearch(), and MusicXMSongCommentsThread::startToSearch().
QString MusicSemaphoreLoop::getClassName () static
Get class object name.
Definition at line 17 of file musicsemaphoreloop.cpp.
Member Data Documentation
QTimer MusicSemaphoreLoop::m_timer protected
Definition at line 51 of file musicsemaphoreloop.h.
Referenced by exec(), MusicSemaphoreLoop(), and ~MusicSemaphoreLoop().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicsemaphoreloop.h
TTKModule/TTKCore/musicCoreKits/musicsemaphoreloop.cpp