TTKMusicPlayer: MusicSplitItemClickedLabel Class Reference
MusicSplitItemClickedLabel Class Reference
The class of the split item clicked widget.
#include <musicsplititemclickedlabel.h>
Public Member Functions
MusicSplitItemClickedLabel (QWidget *parent=nullptr)
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void paintEvent (QPaintEvent *event) overridefinal
Private Attributes
QRectF m_lineGeometry
QString m_currentString
Detailed Description
The class of the split item clicked widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicsplititemclickedlabel.h.
Constructor & Destructor Documentation
MusicSplitItemClickedLabel::MusicSplitItemClickedLabel (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicsplititemclickedlabel.cpp.
Member Function Documentation
void MusicSplitItemClickedLabel::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Definition at line 14 of file musicsplititemclickedlabel.cpp.
References m_currentString, and m_lineGeometry.
void MusicSplitItemClickedLabel::leaveEvent (QEvent * event) final override private virtual
Definition at line 22 of file musicsplititemclickedlabel.cpp.
References m_currentString, and m_lineGeometry.
void MusicSplitItemClickedLabel::mouseMoveEvent (QMouseEvent * event) final override private virtual
Definition at line 39 of file musicsplititemclickedlabel.cpp.
References TTK::Widget::fontTextWidth(), m_currentString, m_lineGeometry, qAsConst, and TTK::String::split().
void MusicSplitItemClickedLabel::mousePressEvent (QMouseEvent * event) final override private virtual
Definition at line 30 of file musicsplititemclickedlabel.cpp.
References MusicRightAreaWidget::instance(), m_currentString, and MusicRightAreaWidget::showSongSearchedFound().
void MusicSplitItemClickedLabel::paintEvent (QPaintEvent * event) final override private virtual
Definition at line 65 of file musicsplititemclickedlabel.cpp.
References m_lineGeometry.
Member Data Documentation
QString MusicSplitItemClickedLabel::m_currentString private
Definition at line 49 of file musicsplititemclickedlabel.h.
Referenced by enterEvent(), leaveEvent(), mouseMoveEvent(), and mousePressEvent().
QRectF MusicSplitItemClickedLabel::m_lineGeometry private
Definition at line 48 of file musicsplititemclickedlabel.h.
Referenced by enterEvent(), leaveEvent(), mouseMoveEvent(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicsplititemclickedlabel.h
TTKModule/TTKWidget/musicCoreKits/musicsplititemclickedlabel.cpp