TTKMusicPlayer: MusicKWQueryAlbumRequest Class Reference
MusicKWQueryAlbumRequest Class Reference
The class of the kuwo query album download data from net.
#include <musickwqueryalbumrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadSingleFinished ()
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWQueryAlbumRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value) overridefinal
virtual void startToSingleSearch (const QString &id) overridefinal
Public Member Functions inherited from MusicQueryAlbumRequest
MusicQueryAlbumRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &value) overridefinal
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
void setQueryQuality (MusicObject::QueryQuality quality)
MusicObject::QueryQuality queryQuality () const
void setQueryAllRecords (bool state)
bool queryAllRecords () const
void setQueryLite (bool state)
bool queryLite () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryValue () const
void setSongInfoList (const MusicObject::MusicSongInformationList &songInfos)
const MusicObject::MusicSongInformationList & songInfoList () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryServer { QueryServer::WY, QueryServer::KW, QueryServer::KG }
enum QueryType { QueryType::Music, QueryType::Movie, QueryType::Lrc, QueryType::Other }
Signals inherited from MusicQueryAlbumRequest
void createAlbumItem (const MusicResultDataItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicResultInfoItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongProperty *prop) const
bool findUrlFileSize (MusicObject::MusicSongPropertyList *props) const
Protected Attributes inherited from MusicAbstractQueryRequest
QString m_queryValue
QString m_queryServer
QueryType m_queryType
MusicObject::QueryQuality m_queryQuality
bool m_queryAllRecords
bool m_queryLite
MusicObject::MusicSongInformationList m_songInfos
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicKWQueryInterface
void parseFromSongHighProperty (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate) const
void parseFromSongProperty (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate) const
void parseFromSongPropertyNew (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate) const
void parseFromSongProperty (MusicObject::MusicSongInformation *info, const QString &format, MusicObject::QueryQuality quality, bool all) const
void parseFromSongProperty (MusicObject::MusicSongInformation *info, const QVariantList &format, MusicObject::QueryQuality quality, bool all) const
Detailed Description
The class of the kuwo query album download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musickwqueryalbumrequest.h.
Constructor & Destructor Documentation
MusicKWQueryAlbumRequest::MusicKWQueryAlbumRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musickwqueryalbumrequest.cpp.
References MusicAbstractQueryRequest::m_queryServer, and QUERY_KW_INTERFACE.
Member Function Documentation
void MusicKWQueryAlbumRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 40 of file musickwqueryalbumrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicQueryAlbumRequest::createAlbumItem(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicAbstractQueryRequest::findUrlFileSize(), MusicUtils::String::isNetworkUrl(), KW_ALBUM_COVER_PREFIX_URL, KW_ALBUM_COVER_URL, KW_SONG_LRC_URL, MusicObject::MusicSongInformation::m_albumId, MusicResultInfoItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicResultDataItem::m_coverUrl, MusicObject::MusicSongInformation::m_coverUrl, MusicResultDataItem::m_description, MusicResultInfoItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicResultDataItem::m_id, MusicObject::MusicSongInformation::m_lrcUrl, MusicResultDataItem::m_name, MusicResultDataItem::m_nickName, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_queryQuality, MusicAbstractNetwork::m_reply, MusicResultInfoItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicAbstractQueryRequest::m_songInfos, MusicResultInfoItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongInformation::m_trackNumber, MusicResultInfoItem::m_type, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicKWQueryInterface::parseFromSongProperty(), TTK_DEFAULT_STR, TTK_INFO_STREAM, TTK_NETWORK_QUERY_CHECK, TTK_NULL_STR, and TTK_SPLITER.
Referenced by startToSearch().
void MusicKWQueryAlbumRequest::downLoadSingleFinished () slot
Download single data from net finished.
Definition at line 132 of file musickwqueryalbumrequest.cpp.
References MusicQueryAlbumRequest::createAlbumItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicUtils::String::isNetworkUrl(), KW_ALBUM_COVER_PREFIX_URL, MusicResultDataItem::m_coverUrl, MusicResultDataItem::m_id, MusicResultDataItem::m_name, MusicResultDataItem::m_updateTime, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), TTK_DEFAULT_STR, TTK_DOT, TTK_INFO_STREAM, TTK_NETWORK_QUERY_CHECK, TTK_NULL_STR, and TTKObject_cast.
Referenced by startToSingleSearch().
void MusicKWQueryAlbumRequest::startToSearch (const QString & value) final override virtual
Start to search data by input data.
Implements MusicQueryAlbumRequest.
Definition at line 9 of file musickwqueryalbumrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KW_ALBUM_URL, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_queryValue, MusicAbstractNetwork::m_reply, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and TTK_INFO_STREAM.
void MusicKWQueryAlbumRequest::startToSingleSearch (const QString & id) final override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 25 of file musickwqueryalbumrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadSingleFinished(), KW_ARTIST_ALBUM_URL, MusicAbstractNetwork::m_manager, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and TTK_INFO_STREAM.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryalbumrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwqueryalbumrequest.cpp