TTKMusicPlayer: MusicLrcDownloadBatchTableWidget Class Reference
MusicLrcDownloadBatchTableWidget Class Reference
The class of the the lrc batch download table widget.
#include <musiclrcdownloadbatchwidget.h>
Public Member Functions
MusicLrcDownloadBatchTableWidget (QWidget *parent=nullptr)
void addCellItems (const MusicSongList &items)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Additional Inherited Members
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the the lrc batch download table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musiclrcdownloadbatchwidget.h.
Constructor & Destructor Documentation
MusicLrcDownloadBatchTableWidget::MusicLrcDownloadBatchTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musiclrcdownloadbatchwidget.cpp.
References MusicUIObject::MQSSScrollBarStyle01.
Member Function Documentation
void MusicLrcDownloadBatchTableWidget::addCellItems (const MusicSongList & items)
Create cell items by input data.
Definition at line 24 of file musiclrcdownloadbatchwidget.cpp.
References MusicSong::artistBack(), MusicSong::artistFront(), MusicUtils::Widget::elidedText(), MusicSong::name(), MusicSong::path(), and QtItemSetTextAlignment.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcdownloadbatchwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcdownloadbatchwidget.cpp