TTKMusicPlayer: MusicMobileSongsManagerWidget Class Reference
MusicMobileSongsManagerWidget Class Reference
The class of the mobile songs manager widget.
#include <musicmobilesongsmanagerwidget.h>
Public Slots
void selectedAllItems (bool checked)
void auditionButtonClick ()
void itemCellClicked (int row, int column)
void itemDoubleClicked (int row, int column)
void searchFilePathChanged (const QStringList &path)
void searchResultChanged (int row, int column)
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
void show ()
Signals
void addSongToPlaylist (const QStringList &items)
Public Member Functions
MusicMobileSongsManagerWidget (QWidget *parent=nullptr)
~MusicMobileSongsManagerWidget ()
void findExtraDevicePath (const QString &dir)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
Public Member Functions inherited from TTKAbstractMoveWidget
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Private Member Functions
void clearAllItems ()
void selectedItemsToPlaylist ()
Private Member Functions inherited from MusicItemSearchInterface< QStringList >
MusicItemSearchInterface ()
bool hasSearchResult () const
void clearSearchResult ()
void mappedSearchRow (int pos, int &row) const
Private Attributes
Ui::MusicMobileSongsManagerWidget * m_ui
MusicSongsManagerThread * m_thread
Private Attributes inherited from MusicItemSearchInterface< QStringList >
QStringList m_containerItems
int m_searchResultLevel
TTKIntListMap m_searchResultCache
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Protected Attributes inherited from TTKAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Private Types inherited from MusicItemSearchInterface< QStringList >
using TTKIntListMap = QMap< int, TTKIntList >
using MusicItemSearchInterfaceClass = MusicItemSearchInterface< QStringList >
Detailed Description
The class of the mobile songs manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 71 of file musicmobilesongsmanagerwidget.h.
Constructor & Destructor Documentation
MusicMobileSongsManagerWidget::MusicMobileSongsManagerWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 110 of file musicmobilesongsmanagerwidget.cpp.
References auditionButtonClick(), TTK::UI::BackgroundStyle03, TTK::UI::BackgroundStyle10, TTK::UI::CheckBoxStyle03, MusicGifLabelWidget::CicleBlue, G_CONNECTION_PTR, itemCellClicked(), itemDoubleClicked(), m_thread, m_ui, searchFilePathChanged(), searchResultChanged(), selectedAllItems(), MusicWidgetRenderer::setBackgroundLabel(), TTK::UI::ToolButtonStyle01, TTK::UI::ToolButtonStyle02, and TTK::UI::ToolButtonStyle04.
MusicMobileSongsManagerWidget::~MusicMobileSongsManagerWidget ()
Definition at line 162 of file musicmobilesongsmanagerwidget.cpp.
References clearAllItems(), G_CONNECTION_PTR, G_SINGLE_MANAGER_PTR, m_thread, m_ui, and TTKAbstractThread::stop().
Member Function Documentation
void MusicMobileSongsManagerWidget::addSongToPlaylist (const QStringList & items) signal
Add current selected song to playlist.
Referenced by itemDoubleClicked(), and selectedItemsToPlaylist().
void MusicMobileSongsManagerWidget::auditionButtonClick () slot
Music song audition play.
Definition at line 194 of file musicmobilesongsmanagerwidget.cpp.
References m_ui, MusicToastLabel::popup(), and selectedItemsToPlaylist().
Referenced by MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::clearAllItems () private
Clear All Items.
Definition at line 265 of file musicmobilesongsmanagerwidget.cpp.
References m_ui.
Referenced by searchFilePathChanged(), searchResultChanged(), and ~MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::findExtraDevicePath (const QString & dir)
Find extra device path.
Definition at line 172 of file musicmobilesongsmanagerwidget.cpp.
References m_thread, m_ui, MusicSongsManagerThread::setFindFilePath(), TTKAbstractThread::start(), TTKAbstractThread::stop(), and TTK_INFO_STREAM.
Referenced by MusicMobileDevicesWidget::showMobileManager().
void MusicMobileSongsManagerWidget::itemCellClicked (int row, int column) slot
Item cell on click by row and col.
Definition at line 211 of file musicmobilesongsmanagerwidget.cpp.
References itemDoubleClicked().
Referenced by MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::itemDoubleClicked (int row, int column) slot
Item cell on double click by row and col.
Definition at line 221 of file musicmobilesongsmanagerwidget.cpp.
References addSongToPlaylist(), MusicItemSearchInterface< QStringList >::m_containerItems, m_ui, and MusicItemSearchInterface< QStringList >::mappedSearchRow().
Referenced by itemCellClicked(), and MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::searchFilePathChanged (const QStringList & path) slot
Send the searched file or path.
Definition at line 228 of file musicmobilesongsmanagerwidget.cpp.
References clearAllItems(), MusicItemSearchInterface< QStringList >::clearSearchResult(), MusicItemSearchInterface< QStringList >::m_containerItems, m_ui, and TTK_INFO_STREAM.
Referenced by MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::searchResultChanged (int row, int column) slot
Search result from list.
Definition at line 241 of file musicmobilesongsmanagerwidget.cpp.
References clearAllItems(), MusicItemSearchInterface< QStringList >::m_containerItems, MusicItemSearchInterface< QStringList >::m_searchResultCache, MusicItemSearchInterface< QStringList >::m_searchResultLevel, and m_ui.
Referenced by MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::selectedAllItems (bool checked) slot
Select all items.
Definition at line 181 of file musicmobilesongsmanagerwidget.cpp.
References m_ui.
Referenced by MusicMobileSongsManagerWidget().
void MusicMobileSongsManagerWidget::selectedItemsToPlaylist () private
Set current item or items selected.
Definition at line 274 of file musicmobilesongsmanagerwidget.cpp.
References addSongToPlaylist(), MusicItemSearchInterface< QStringList >::m_containerItems, m_ui, and MusicItemSearchInterface< QStringList >::mappedSearchRow().
Referenced by auditionButtonClick().
Member Data Documentation
MusicSongsManagerThread* MusicMobileSongsManagerWidget::m_thread private
Definition at line 131 of file musicmobilesongsmanagerwidget.h.
Referenced by findExtraDevicePath(), MusicMobileSongsManagerWidget(), and ~MusicMobileSongsManagerWidget().
Ui::MusicMobileSongsManagerWidget* MusicMobileSongsManagerWidget::m_ui private
Definition at line 129 of file musicmobilesongsmanagerwidget.h.
Referenced by auditionButtonClick(), clearAllItems(), findExtraDevicePath(), itemDoubleClicked(), MusicMobileSongsManagerWidget(), searchFilePathChanged(), searchResultChanged(), selectedAllItems(), selectedItemsToPlaylist(), and ~MusicMobileSongsManagerWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicmobilesongsmanagerwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicmobilesongsmanagerwidget.cpp