TTKMusicplayer: MusicSimilarFoundWidget Class Reference
MusicSimilarFoundWidget Class Reference
The class of similar music found widget.
#include <musicsimilarfoundwidget.h>
Public Slots
void queryAllFinished ()
void downLoadFinished (const QByteArray &data)
void downloadUrlChanged (const QString &imageUrl)
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicSimilarFoundWidget (QWidget *parent=0)
virtual ~MusicSimilarFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Member Functions
void createLabels ()
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
Protected Attributes
MusicSimilarFoundTableWidget * m_similarTableWidget
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QLabel * m_statusLabel
QList< QLabel * > m_resizeWidget
Detailed Description
The class of similar music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 51 of file musicsimilarfoundwidget.h.
Constructor & Destructor Documentation
MusicSimilarFoundWidget::MusicSimilarFoundWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 48 of file musicsimilarfoundwidget.cpp.
References m_similarTableWidget.
MusicSimilarFoundWidget::~MusicSimilarFoundWidget () virtual
Definition at line 54 of file musicsimilarfoundwidget.cpp.
References m_similarTableWidget.
Member Function Documentation
void MusicSimilarFoundWidget::addButtonClicked () slot
Add button clicked now.
Definition at line 227 of file musicsimilarfoundwidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), and m_similarTableWidget.
Referenced by createLabels().
void MusicSimilarFoundWidget::createLabels () protected
Create init interface lables.
Definition at line 93 of file musicsimilarfoundwidget.cpp.
References addButtonClicked(), MusicUtils::String::artistName(), downloadButtonClicked(), downloadUrlChanged(), MusicUtils::Widget::elidedText(), MusicQueryFoundTableWidget::getMusicSongInfos(), MusicFoundAbstractWidget::m_mainWindow, MusicFoundAbstractWidget::m_resizeWidget, m_similarTableWidget, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicFoundAbstractWidget::m_songNameFull, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, and playButtonClicked().
Referenced by queryAllFinished().
void MusicSimilarFoundWidget::downloadButtonClicked () slot
Download button clicked now.
Definition at line 219 of file musicsimilarfoundwidget.cpp.
References MusicFillItemTableWidget::getSelectedItems(), m_similarTableWidget, and MusicQueryFoundTableWidget::musicDownloadLocal().
Referenced by createLabels().
void MusicSimilarFoundWidget::downLoadFinished (const QByteArray & data) slot
Send recieved data from net.
Definition at line 192 of file musicsimilarfoundwidget.cpp.
References MusicFoundAbstractWidget::m_resizeWidget.
Referenced by downloadUrlChanged().
void MusicSimilarFoundWidget::downloadUrlChanged (const QString & imageUrl) slot
Data download finished and send to shared on web.
Definition at line 207 of file musicsimilarfoundwidget.cpp.
References downLoadFinished(), and MusicDownloadSourceThread::startToDownload().
Referenced by createLabels().
QString MusicSimilarFoundWidget::getClassName () static
Get class object name.
Definition at line 59 of file musicsimilarfoundwidget.cpp.
void MusicSimilarFoundWidget::playButtonClicked () slot
Play button clicked now.
Definition at line 214 of file musicsimilarfoundwidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), and m_similarTableWidget.
Referenced by createLabels().
void MusicSimilarFoundWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 77 of file musicsimilarfoundwidget.cpp.
References createLabels(), MusicQueryFoundTableWidget::getMusicSongInfos(), m_similarTableWidget, and MusicFoundAbstractWidget::m_statusLabel.
void MusicSimilarFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 72 of file musicsimilarfoundwidget.cpp.
References m_similarTableWidget, and MusicQueryFoundTableWidget::resizeWindow().
void MusicSimilarFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 64 of file musicsimilarfoundwidget.cpp.
References M_DOWNLOAD_QUERY_PTR, m_similarTableWidget, MusicSimilarFoundTableWidget::setQueryInput(), MusicFoundAbstractWidget::setSongName(), MusicUtils::String::songName(), and MusicQueryFoundTableWidget::startSearchQuery().
Member Data Documentation
MusicSimilarFoundTableWidget* MusicSimilarFoundWidget::m_similarTableWidget protected
Definition at line 109 of file musicsimilarfoundwidget.h.
Referenced by addButtonClicked(), createLabels(), downloadButtonClicked(), MusicSimilarFoundWidget(), playButtonClicked(), queryAllFinished(), resizeWindow(), setSongName(), and ~MusicSimilarFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsimilarfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsimilarfoundwidget.cpp