TTKMusicplayer: MusicSongCheckToolsDuplicateThread Class Reference
MusicSongCheckToolsDuplicateThread Class Reference
The class of the song check tools duplicate thread.
#include <musicsongchecktoolsthread.h>
Signals
void finished (const MusicSongCheckToolsDuplicateList &items)
Public Member Functions
MusicSongCheckToolsDuplicateThread (QObject *parent=nullptr)
void setMode (MusicObject::MusicSongCheckToolsMode mode)
MusicObject::MusicSongCheckToolsMode mode () const
void setItemList (const TTKIntList &items)
void setDuplicateSongs (MusicSongList *songs)
Public Member Functions inherited from MusicAbstractThread
MusicAbstractThread (QObject *parent=nullptr)
~MusicAbstractThread ()
void stopAndQuitThread ()
Protected Member Functions
virtual void run () overridefinal
Protected Attributes
bool m_run
MusicSongList * m_songItems
TTKIntList m_itemIDs
MusicSongCheckToolsDuplicateList m_datas
MusicObject::MusicSongCheckToolsMode m_operateMode
Protected Attributes inherited from MusicAbstractThread
bool m_running
Additional Inherited Members
Public Slots inherited from MusicAbstractThread
void start ()
Detailed Description
The class of the song check tools duplicate thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 80 of file musicsongchecktoolsthread.h.
Constructor & Destructor Documentation
MusicSongCheckToolsDuplicateThread::MusicSongCheckToolsDuplicateThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 67 of file musicsongchecktoolsthread.cpp.
References m_songItems.
Member Function Documentation
void MusicSongCheckToolsDuplicateThread::finished (const MusicSongCheckToolsDuplicateList & items) signal
Duplicate check finished.
Referenced by run().
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsDuplicateThread::mode () const inline
Get music song check tool mode.
Definition at line 97 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsWidget::duplicateCheckFinished().
void MusicSongCheckToolsDuplicateThread::run () final override protected virtual
Thread run now.
Reimplemented from MusicAbstractThread.
Definition at line 78 of file musicsongchecktoolsthread.cpp.
References MusicSongMeta::bitrate(), MusicObject::Check, finished(), m_datas, m_itemIDs, m_operateMode, m_run, MusicSongCheckToolsDuplicate::m_song, m_songItems, MusicSong::path(), MusicSongMeta::read(), and MusicAbstractThread::run().
void MusicSongCheckToolsDuplicateThread::setDuplicateSongs (MusicSongList * songs)
Set find file path by given path.
Definition at line 73 of file musicsongchecktoolsthread.cpp.
References m_songItems.
Referenced by MusicSongCheckToolsWidget::duplicateReCheckButtonClicked().
void MusicSongCheckToolsDuplicateThread::setItemList (const TTKIntList & items) inline
Set item list.
Definition at line 101 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked().
void MusicSongCheckToolsDuplicateThread::setMode (MusicObject::MusicSongCheckToolsMode mode) inline
Set music song check tool mode.
Definition at line 93 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), and MusicSongCheckToolsWidget::duplicateReCheckButtonClicked().
Member Data Documentation
MusicSongCheckToolsDuplicateList MusicSongCheckToolsDuplicateThread::m_datas protected
Definition at line 124 of file musicsongchecktoolsthread.h.
Referenced by run().
TTKIntList MusicSongCheckToolsDuplicateThread::m_itemIDs protected
Definition at line 123 of file musicsongchecktoolsthread.h.
Referenced by run().
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsDuplicateThread::m_operateMode protected
Definition at line 125 of file musicsongchecktoolsthread.h.
Referenced by run().
bool MusicSongCheckToolsDuplicateThread::m_run protected
Thread run now.
Definition at line 121 of file musicsongchecktoolsthread.h.
Referenced by run().
MusicSongList* MusicSongCheckToolsDuplicateThread::m_songItems protected
Definition at line 122 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsDuplicateThread(), run(), and setDuplicateSongs().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolsthread.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolsthread.cpp