TTKMusicplayer: MusicDownLoadWYInterface Class Reference
MusicDownLoadWYInterface Class Reference
The class to wangyi query download interface.
#include <musicdownloadwyinterface.h>
Public Member Functions
void makeTokenQueryRequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate, const QString &suffix)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate, const QString &suffix)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to wangyi query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 89 of file musicdownloadwyinterface.h.
Member Function Documentation
QString MusicDownLoadWYInterface::encryptedId (qint64 id)
Encrypted music info id.
Definition at line 328 of file musicdownloadwyinterface.cpp.
Referenced by readFromMusicSongAttribute(), and readFromMusicSongAttributeNew().
QString MusicDownLoadWYInterface::encryptedId (const QString & string)
Encrypted music info id.
Definition at line 333 of file musicdownloadwyinterface.cpp.
References MusicUtils::Algorithm::md5(), and WY_ENCRYPT_STRING.
void MusicDownLoadWYInterface::makeTokenQueryRequest (QNetworkRequest * request)
QJson import.
Make token query url string.
Definition at line 17 of file musicdownloadwyinterface.cpp.
References ALG_UA_KEY, M_SETTING_PTR, MusicUtils::Algorithm::mdII(), MusicSettingManager::NetworkCookie, MusicObject::setSslConfiguration(), MusicUtils::Codec::toUtf8(), WY_BASE_URL, WY_COOKIE_URL, WY_NNID_URL, WY_NUID_URL, WY_UA_URL_1, and WY_WYYY_URL.
Referenced by makeTokenQueryUrl(), and readFromMusicSongAttribute().
QByteArray MusicDownLoadWYInterface::makeTokenQueryUrl (QNetworkRequest * request, const QString & query, const QString & type)
Make token query url string.
Definition at line 32 of file musicdownloadwyinterface.cpp.
References QAesWrap::encryptCBC(), makeTokenQueryRequest(), MusicUtils::Url::urlEncode(), and WY_SECKRY.
Referenced by MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), readFromMusicSongAttributeNew(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicDJRadioCategoryThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), and MusicDownLoadQueryWYThread::startToSingleSearch().
void MusicDownLoadWYInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 45 of file musicdownloadwyinterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, makeTokenQueryRequest(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QJson::Parser::parse(), readFromMusicSongAttributeNew(), MusicUtils::Number::size2Label(), and WY_SONG_INFO_URL.
Referenced by MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), readFromMusicSongAttribute(), readFromMusicSongAttributeNew(), and MusicDownLoadQueryWYThread::singleDownLoadFinished().
void MusicDownLoadWYInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate, const QString & suffix)
Read tags(size) from query results.
Definition at line 102 of file musicdownloadwyinterface.cpp.
References encryptedId(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), readFromMusicSongAttribute(), MusicUtils::Number::size2Label(), and WY_SONG_PATH_URL.
Referenced by readFromMusicSongAttribute().
void MusicDownLoadWYInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 124 of file musicdownloadwyinterface.cpp.
References FLC_FILE_PREFIX, MB_128, MB_192, MB_320, MB_999, MP3_FILE_PREFIX, and readFromMusicSongAttribute().
void MusicDownLoadWYInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 189 of file musicdownloadwyinterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QJson::Parser::parse(), MusicUtils::Number::size2Label(), WY_SONG_INFO_N_URL, and WY_SONG_INFO_NDT_URL.
Referenced by MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), readFromMusicSongAttribute(), and readFromMusicSongAttributeNew().
void MusicDownLoadWYInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate, const QString & suffix)
Read tags(size) from query results.
Definition at line 241 of file musicdownloadwyinterface.cpp.
References encryptedId(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), readFromMusicSongAttribute(), MusicUtils::Number::size2Label(), and WY_SONG_PATH_URL.
void MusicDownLoadWYInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 263 of file musicdownloadwyinterface.cpp.
References FLC_FILE_PREFIX, MB_128, MB_192, MB_320, MB_999, MP3_FILE_PREFIX, and readFromMusicSongAttributeNew().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicdownloadwyinterface.h
TTKModule/TTKCore/musicNetworkKits/wy/musicdownloadwyinterface.cpp