TTKMusicplayer: MusicSourceUpdateThread Class Reference
MusicSourceUpdateThread Class Reference
The class of source data query pdate thread.
#include <musicsourceupdatethread.h>
Public Slots
void downLoadFinished (const QByteArray &data)
Signals
void downLoadDataChanged (const QVariant &data)
Public Member Functions
MusicSourceUpdateThread (QObject *parent=0)
QJson import.
void startToDownload ()
QString getLastedVersion () const
bool isLastedVersion () const
QString getLastedVersionDes () const
Static Public Member Functions
static QString getClassName ()
Protected Attributes
QVariantMap m_rawData
Detailed Description
The class of source data query pdate thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 22 of file musicsourceupdatethread.h.
Constructor & Destructor Documentation
MusicSourceUpdateThread::MusicSourceUpdateThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 6 of file musicsourceupdatethread.cpp.
Member Function Documentation
void MusicSourceUpdateThread::downLoadDataChanged (const QVariant & data) signal
Send download data from net.
Referenced by downLoadFinished().
void MusicSourceUpdateThread::downLoadFinished (const QByteArray & data) slot
Download data from kuwo net finished.
Definition at line 39 of file musicsourceupdatethread.cpp.
References downLoadDataChanged(), m_rawData, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicSourceUpdateThread::getClassName () static
Get class object name.
Definition at line 12 of file musicsourceupdatethread.cpp.
QString MusicSourceUpdateThread::getLastedVersion () const
Get lasted version.
Definition at line 24 of file musicsourceupdatethread.cpp.
References m_rawData.
Referenced by isLastedVersion().
QString MusicSourceUpdateThread::getLastedVersionDes () const
Get lasted version description.
Definition at line 34 of file musicsourceupdatethread.cpp.
References m_rawData.
bool MusicSourceUpdateThread::isLastedVersion () const
Is lasted version.
Definition at line 29 of file musicsourceupdatethread.cpp.
References getLastedVersion(), and TTKMUSIC_VERSION_STR.
void MusicSourceUpdateThread::startToDownload ()
Start to download data.
Definition at line 17 of file musicsourceupdatethread.cpp.
References downLoadFinished(), MusicUtils::Algorithm::mdII(), MusicDownloadSourceThread::startToDownload(), and VERSION_URL.
Referenced by MusicSourceUpdateNotifyWidget::start(), and MusicSourceUpdateWidget::start().
Member Data Documentation
QVariantMap MusicSourceUpdateThread::m_rawData protected
Definition at line 66 of file musicsourceupdatethread.h.
Referenced by downLoadFinished(), getLastedVersion(), and getLastedVersionDes().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicsourceupdatethread.h
TTKModule/TTKCore/musicNetworkKits/musicsourceupdatethread.cpp