TTKMusicPlayer: MusicSongSearchInteriorEdit Class Reference
MusicSongSearchInteriorEdit Class Reference
The class of the net search interior edit widget.
#include <musicsongsearchinterioredit.h>
Public Slots
void setText (const QString &text)
void textChanged (const QString &text)
void selectedTextChanged (const QString &text, bool update)
void suggestDataChanged ()
void searchToplistInfoFinished (const QString &bytes)
Public Member Functions
MusicSongSearchInteriorEdit (QWidget *parent=nullptr)
~MusicSongSearchInteriorEdit ()
void initialize (QWidget *parent)
Public Member Functions inherited from MusicSearchEdit
MusicSearchEdit (QWidget *parent=nullptr)
Private Member Functions
virtual void keyReleaseEvent (QKeyEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void focusOutEvent (QFocusEvent *event) overridefinal
void setPopWidgetVisible (bool show)
Private Attributes
MusicSongSearchPopWidget * m_popWidget
MusicDiscoverListRequest * m_discoverRequest
MusicSongSuggestRequest * m_suggestRequest
Additional Inherited Members
Signals inherited from MusicSearchEdit
void enterFinished (const QString &text)
Protected Member Functions inherited from MusicSearchEdit
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Detailed Description
The class of the net search interior edit widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicsongsearchinterioredit.h.
Constructor & Destructor Documentation
MusicSongSearchInteriorEdit::MusicSongSearchInteriorEdit (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicsongsearchinterioredit.cpp.
References G_DOWNLOAD_QUERY_PTR, m_discoverRequest, searchToplistInfoFinished(), MusicDiscoverListRequest::startToSearch(), and textChanged().
MusicSongSearchInteriorEdit::~MusicSongSearchInteriorEdit ()
Object destructor.
Definition at line 19 of file musicsongsearchinterioredit.cpp.
References m_discoverRequest, and m_suggestRequest.
Member Function Documentation
void MusicSongSearchInteriorEdit::focusOutEvent (QFocusEvent * event) final override private virtual
Definition at line 138 of file musicsongsearchinterioredit.cpp.
References m_popWidget.
void MusicSongSearchInteriorEdit::initialize (QWidget * parent)
Create all widget in layout.
Definition at line 25 of file musicsongsearchinterioredit.cpp.
References m_popWidget, and setPopWidgetVisible().
void MusicSongSearchInteriorEdit::keyReleaseEvent (QKeyEvent * event) final override private virtual
Override the widget event.
Reimplemented from MusicSearchEdit.
Definition at line 103 of file musicsongsearchinterioredit.cpp.
References MusicSearchEdit::keyReleaseEvent(), m_popWidget, and MusicSongSearchPopWidget::selectRow().
void MusicSongSearchInteriorEdit::mousePressEvent (QMouseEvent * event) final override private virtual
Definition at line 129 of file musicsongsearchinterioredit.cpp.
References m_popWidget, and textChanged().
void MusicSongSearchInteriorEdit::searchToplistInfoFinished (const QString & bytes) slot
Search top list information finished.
Definition at line 98 of file musicsongsearchinterioredit.cpp.
Referenced by MusicSongSearchInteriorEdit().
void MusicSongSearchInteriorEdit::selectedTextChanged (const QString & text, bool update) slot
Selected row text changed.
Definition at line 61 of file musicsongsearchinterioredit.cpp.
References setText().
void MusicSongSearchInteriorEdit::setPopWidgetVisible (bool show) private
Set pop widget visible.
Definition at line 147 of file musicsongsearchinterioredit.cpp.
References m_popWidget.
Referenced by initialize(), setText(), suggestDataChanged(), and textChanged().
void MusicSongSearchInteriorEdit::setText (const QString & text) slot
Selected text changed.
Definition at line 34 of file musicsongsearchinterioredit.cpp.
References setPopWidgetVisible().
Referenced by selectedTextChanged().
void MusicSongSearchInteriorEdit::suggestDataChanged () slot
Suggest data changed.
Definition at line 75 of file musicsongsearchinterioredit.cpp.
References MusicSongSearchPopWidget::createSuggestItems(), m_popWidget, m_suggestRequest, MusicSongSuggestRequest::searchedItems(), and setPopWidgetVisible().
Referenced by textChanged().
void MusicSongSearchInteriorEdit::textChanged (const QString & text) slot
Input changed text changed.
Definition at line 43 of file musicsongsearchinterioredit.cpp.
References G_DOWNLOAD_QUERY_PTR, MusicSongSearchPopWidget::initialize(), m_popWidget, m_suggestRequest, setPopWidgetVisible(), MusicSongSuggestRequest::startToSearch(), and suggestDataChanged().
Referenced by mousePressEvent(), and MusicSongSearchInteriorEdit().
Member Data Documentation
MusicDiscoverListRequest* MusicSongSearchInteriorEdit::m_discoverRequest private
Definition at line 86 of file musicsongsearchinterioredit.h.
Referenced by MusicSongSearchInteriorEdit(), and ~MusicSongSearchInteriorEdit().
MusicSongSearchPopWidget* MusicSongSearchInteriorEdit::m_popWidget private
Definition at line 85 of file musicsongsearchinterioredit.h.
Referenced by focusOutEvent(), initialize(), keyReleaseEvent(), mousePressEvent(), setPopWidgetVisible(), suggestDataChanged(), and textChanged().
MusicSongSuggestRequest* MusicSongSearchInteriorEdit::m_suggestRequest private
Definition at line 87 of file musicsongsearchinterioredit.h.
Referenced by suggestDataChanged(), textChanged(), and ~MusicSongSearchInteriorEdit().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicsongsearchinterioredit.h
TTKModule/TTKWidget/musicSearchKits/musicsongsearchinterioredit.cpp