TTKMusicPlayer: MusicIdentifySongRequest Class Reference
MusicIdentifySongRequest Class Reference
The class of the song identify query request.
#include <musicidentifysongrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadFinished (const QByteArray &bytes)
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void finished ()
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Public Member Functions
MusicIdentifySongRequest (QObject *parent=nullptr)
bool queryIdentifyKey ()
void startToRequest (const QString &path)
const MusicSongIdentifyDataList & items () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Attributes
MusicSongIdentifyDataList m_items
QString m_accessKey
QString m_accessSecret
Additional Inherited Members
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the song identify query request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicidentifysongrequest.h.
Constructor & Destructor Documentation
MusicIdentifySongRequest::MusicIdentifySongRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 11 of file musicidentifysongrequest.cpp.
Member Function Documentation
void MusicIdentifySongRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 80 of file musicidentifysongrequest.cpp.
References TTK::String::charactersReplace(), TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), TTKAbstractNetwork::downLoadFinished(), MusicSongIdentifyData::m_artistName, m_items, TTKAbstractNetwork::m_reply, MusicSongIdentifyData::m_songName, QJson::Parser::parse(), qAsConst, TTK::toString(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by queryIdentifyKey(), and startToRequest().
void MusicIdentifySongRequest::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 129 of file musicidentifysongrequest.cpp.
References finished(), m_accessKey, m_accessSecret, QJson::Parser::parse(), TTK::toString(), TTK_DATE_TIMES_FORMAT, and TTK_ERROR_STREAM.
void MusicIdentifySongRequest::finished () signal
Get key data from net finished.
Referenced by downLoadFinished(), queryIdentifyKey(), and startToRequest().
const MusicSongIdentifyDataList& MusicIdentifySongRequest::items () const inline
Get identify songs.
Definition at line 59 of file musicidentifysongrequest.h.
Referenced by MusicIdentifySongWidget::createDetectedSuccessedWidget(), and MusicIdentifySongWidget::detectedTimeOut().
bool MusicIdentifySongRequest::queryIdentifyKey ()
Get query song id keys.
Definition at line 17 of file musicidentifysongrequest.cpp.
References downLoadFinished(), TTKAbstractNetwork::downLoadRawDataChanged(), TTKSemaphoreLoop::exec(), finished(), m_accessKey, m_accessSecret, QSyncUtils::makeDataBucketUrl(), OS_ACRCLOUD_URL, and MusicDataSourceRequest::startToRequest().
Referenced by MusicIdentifySongWidget::queryIdentifyKey().
void MusicIdentifySongRequest::startToRequest (const QString & path)
Start to download identify data.
Definition at line 30 of file musicidentifysongrequest.cpp.
References TTKDateTime::currentTimestamp(), downLoadFinished(), finished(), TTK::Algorithm::hmacSha1(), m_accessKey, m_accessSecret, TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, TTK::makeContentTypeHeader(), TTK::Algorithm::mdII(), QtNetworkErrorConnect, QUERY_URL, MusicAbstractNetwork::replyError(), TTK::setSslConfiguration(), TTK_ERROR_STREAM, and TTK_SLOT.
Referenced by MusicIdentifySongWidget::detectedTimeOut().
Member Data Documentation
QString MusicIdentifySongRequest::m_accessKey private
Definition at line 79 of file musicidentifysongrequest.h.
Referenced by downLoadFinished(), queryIdentifyKey(), and startToRequest().
QString MusicIdentifySongRequest::m_accessSecret private
Definition at line 79 of file musicidentifysongrequest.h.
Referenced by downLoadFinished(), queryIdentifyKey(), and startToRequest().
MusicSongIdentifyDataList MusicIdentifySongRequest::m_items private
Definition at line 78 of file musicidentifysongrequest.h.
Referenced by downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicidentifysongrequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicidentifysongrequest.cpp