TTKMusicPlayer: MusicTimeSliderWidget Class Reference
MusicTimeSliderWidget Class Reference
The class of the time slider widget.
#include <musictimesliderwidget.h>
Public Slots
void sliderMovedAt (int pos) const
void setSliderStyleByType (int type)
Public Member Functions
MusicTimeSliderWidget (QWidget *parent=nullptr)
~MusicTimeSliderWidget ()
void setPlayState (bool state)
void setValue (qint64 value) const
void setRange (int min, int max)
void setInputModule (QObject *object) const
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
MusicGifLabelWidget * m_label
MusicMovingLabelSlider * m_slider
Detailed Description
The class of the time slider widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musictimesliderwidget.h.
Constructor & Destructor Documentation
MusicTimeSliderWidget::MusicTimeSliderWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musictimesliderwidget.cpp.
References MusicGifLabelWidget::BallonWhite, m_label, m_slider, MusicGifLabelWidget::setType(), MusicMovingClickedSlider::setValue(), and TTK::UI::SliderStyle07.
MusicTimeSliderWidget::~MusicTimeSliderWidget ()
Object destructor.
Definition at line 29 of file musictimesliderwidget.cpp.
References m_label, and m_slider.
Member Function Documentation
void MusicTimeSliderWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 110 of file musictimesliderwidget.cpp.
References m_label, m_slider, and sliderMovedAt().
void MusicTimeSliderWidget::setInputModule (QObject * object) const
Set input connection.
Definition at line 23 of file musictimesliderwidget.cpp.
References m_slider, and sliderMovedAt().
void MusicTimeSliderWidget::setPlayState (bool state)
Set current play state.
Definition at line 35 of file musictimesliderwidget.cpp.
References m_label, MusicGifLabelWidget::start(), and MusicGifLabelWidget::stop().
void MusicTimeSliderWidget::setRange (int min, int max)
Set current play range from min and max.
Definition at line 59 of file musictimesliderwidget.cpp.
References m_slider.
void MusicTimeSliderWidget::setSliderStyleByType (int type) slot
Set slider style diff by diff enhanced effect.
Definition at line 74 of file musictimesliderwidget.cpp.
References m_slider, and TTK::UI::SliderStyle07.
void MusicTimeSliderWidget::setValue (qint64 value) const
Set current play index value.
Definition at line 50 of file musictimesliderwidget.cpp.
References MusicMovingClickedSlider::isMoving(), m_slider, MusicMovingClickedSlider::setValue(), and sliderMovedAt().
void MusicTimeSliderWidget::sliderMovedAt (int pos) const slot
Current slider move at pos.
Definition at line 64 of file musictimesliderwidget.cpp.
References m_label, m_slider, and TTK::max().
Referenced by resizeEvent(), setInputModule(), and setValue().
Member Data Documentation
MusicGifLabelWidget* MusicTimeSliderWidget::m_label private
Definition at line 78 of file musictimesliderwidget.h.
Referenced by MusicTimeSliderWidget(), resizeEvent(), setPlayState(), sliderMovedAt(), and ~MusicTimeSliderWidget().
MusicMovingLabelSlider* MusicTimeSliderWidget::m_slider private
Definition at line 79 of file musictimesliderwidget.h.
Referenced by MusicTimeSliderWidget(), resizeEvent(), setInputModule(), setRange(), setSliderStyleByType(), setValue(), sliderMovedAt(), and ~MusicTimeSliderWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musictimesliderwidget.h
TTKModule/TTKWidget/musicCoreKits/musictimesliderwidget.cpp