TTKMusicplayer: MusicVolumeGainWidget Class Reference
MusicVolumeGainWidget Class Reference
The class of the volume gain widget.
#include <musicvolumegainwidget.h>
Public Slots
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void resetFlag (MusicObject::ToolsType flag)
Public Member Functions
MusicVolumeGainWidget (QWidget *parent=0)
virtual ~MusicVolumeGainWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
void createItemFinished (const QString &track, const QString &album)
void setControlEnable (bool enable)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicVolumeGainWidget * m_ui
QProcess * m_process
QStringList m_paths
int m_currentIndex
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Private Slots
void addFileButtonClicked ()
void addFilesButtonClicked ()
void rmFileButtonClicked ()
void rmFilesButtonClicked ()
void analysisButtonClicked ()
void applyButtonClicked ()
void volumeLineTextChanged (const QString &text)
void analysisOutput ()
void applyOutput ()
Detailed Description
The class of the volume gain widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 50 of file musicvolumegainwidget.h.
Constructor & Destructor Documentation
MusicVolumeGainWidget::MusicVolumeGainWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 43 of file musicvolumegainwidget.cpp.
References addFileButtonClicked(), addFilesButtonClicked(), analysisButtonClicked(), analysisOutput(), applyButtonClicked(), m_currentIndex, m_process, m_ui, MusicUIObject::MLineEditStyle01, MusicUIObject::MToolButtonStyle04, rmFileButtonClicked(), rmFilesButtonClicked(), and volumeLineTextChanged().
MusicVolumeGainWidget::~MusicVolumeGainWidget () virtual
Definition at line 111 of file musicvolumegainwidget.cpp.
References m_process, and m_ui.
Member Function Documentation
void MusicVolumeGainWidget::addFileButtonClicked () private slot
Add input file button clicked.
Definition at line 175 of file musicvolumegainwidget.cpp.
References MusicSemaphoreLoop::exec(), m_currentIndex, m_paths, m_process, MAKE_GAIN_FULL, and setControlEnable().
Referenced by MusicVolumeGainWidget().
void MusicVolumeGainWidget::addFilesButtonClicked () private slot
Add input files button clicked.
Definition at line 204 of file musicvolumegainwidget.cpp.
References MusicSemaphoreLoop::exec(), m_currentIndex, m_paths, m_process, MAKE_GAIN_FULL, and setControlEnable().
Referenced by MusicVolumeGainWidget().
void MusicVolumeGainWidget::analysisButtonClicked () private slot
Analysis input files button clicked.
do nothing here
Definition at line 251 of file musicvolumegainwidget.cpp.
Referenced by MusicVolumeGainWidget().
void MusicVolumeGainWidget::analysisOutput () private slot
Analysis output by process.
Definition at line 303 of file musicvolumegainwidget.cpp.
References createItemFinished(), GAIN_ALBUMDB, GAIN_TRACKDB, and m_process.
Referenced by applyButtonClicked(), and MusicVolumeGainWidget().
void MusicVolumeGainWidget::applyButtonClicked () private slot
Apply input files button clicked.
Definition at line 256 of file musicvolumegainwidget.cpp.
References analysisOutput(), applyOutput(), MusicSemaphoreLoop::exec(), MusicMessageBox::exec(), m_paths, m_process, m_ui, MAKE_GAIN_FULL, rmFilesButtonClicked(), setControlEnable(), and MusicMessageBox::setText().
Referenced by MusicVolumeGainWidget().
void MusicVolumeGainWidget::applyOutput () private slot
Apply output by process.
Definition at line 329 of file musicvolumegainwidget.cpp.
References m_process, and m_ui.
Referenced by applyButtonClicked().
void MusicVolumeGainWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 122 of file musicvolumegainwidget.cpp.
References resetFlag(), and MusicObject::TT_SoundGain.
void MusicVolumeGainWidget::createItemFinished (const QString & track, const QString & album) protected
Create table item finished.
Definition at line 128 of file musicvolumegainwidget.cpp.
References MusicUtils::Widget::elidedText(), GAIN_DEFAULT, m_currentIndex, m_paths, and m_ui.
Referenced by analysisOutput().
QString MusicVolumeGainWidget::getClassName () static
Get class object name.
Definition at line 117 of file musicvolumegainwidget.cpp.
void MusicVolumeGainWidget::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by closeEvent().
void MusicVolumeGainWidget::rmFileButtonClicked () private slot
Remove input file button clicked.
Definition at line 231 of file musicvolumegainwidget.cpp.
References MusicMessageBox::exec(), m_ui, and MusicMessageBox::setText().
Referenced by MusicVolumeGainWidget().
void MusicVolumeGainWidget::rmFilesButtonClicked () private slot
Remove input files button clicked.
Definition at line 244 of file musicvolumegainwidget.cpp.
References m_currentIndex, m_paths, and m_ui.
Referenced by applyButtonClicked(), and MusicVolumeGainWidget().
void MusicVolumeGainWidget::setControlEnable (bool enable) protected
Enable or disable control state.
Definition at line 165 of file musicvolumegainwidget.cpp.
References m_ui.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), and applyButtonClicked().
void MusicVolumeGainWidget::show () slot
Override show function.
Definition at line 349 of file musicvolumegainwidget.cpp.
References MusicMessageBox::exec(), m_ui, MAKE_GAIN_FULL, MusicAbstractMoveWidget::setBackgroundPixmap(), and MusicMessageBox::setText().
void MusicVolumeGainWidget::volumeLineTextChanged (const QString & text) private slot
Music gain volume input value changed.
Definition at line 291 of file musicvolumegainwidget.cpp.
References m_ui.
Referenced by MusicVolumeGainWidget().
Member Data Documentation
int MusicVolumeGainWidget::m_currentIndex protected
Definition at line 133 of file musicvolumegainwidget.h.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), createItemFinished(), MusicVolumeGainWidget(), and rmFilesButtonClicked().
QStringList MusicVolumeGainWidget::m_paths protected
Definition at line 132 of file musicvolumegainwidget.h.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), applyButtonClicked(), createItemFinished(), and rmFilesButtonClicked().
QProcess* MusicVolumeGainWidget::m_process protected
Definition at line 131 of file musicvolumegainwidget.h.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), analysisOutput(), applyButtonClicked(), applyOutput(), MusicVolumeGainWidget(), and ~MusicVolumeGainWidget().
Ui::MusicVolumeGainWidget* MusicVolumeGainWidget::m_ui protected
Definition at line 130 of file musicvolumegainwidget.h.
Referenced by applyButtonClicked(), applyOutput(), createItemFinished(), MusicVolumeGainWidget(), rmFileButtonClicked(), rmFilesButtonClicked(), setControlEnable(), show(), volumeLineTextChanged(), and ~MusicVolumeGainWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicvolumegainwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicvolumegainwidget.cpp