TTKMusicPlayer: MusicPlaylistQueryWidget Class Reference
MusicPlaylistQueryWidget Class Reference
The class of the playlist music query widget.
#include <musicplaylistquerywidget.h>
Public Slots
void createPlaylistItem (const MusicResultDataItem &item)
void currentPlaylistClicked (const MusicResultDataItem &item)
void backToPlaylistMenu ()
void categoryChanged (const MusicResultsCategoryItem &category)
void buttonClicked (int index)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicPlaylistQueryWidget (QWidget *parent=nullptr)
~MusicPlaylistQueryWidget ()
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameByID (const QString &id) overridefinal
virtual void resizeWidget () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Public Member Functions inherited from TTKAbstractResizeInterface
TTKAbstractResizeInterface ()=default
Private Attributes
bool m_initialized
bool m_categoryChanged
QGridLayout * m_gridLayout
MusicPageQueryWidget * m_pageQueryWidget
MusicPlaylistQueryInfoWidget * m_infoWidget
MusicPlaylistFoundCategoryPopWidget * m_categoryButton
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultDataItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Module m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of the playlist music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 81 of file musicplaylistquerywidget.h.
Constructor & Destructor Documentation
MusicPlaylistQueryWidget::MusicPlaylistQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 122 of file musicplaylistquerywidget.cpp.
References createPlaylistItem(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_mainWindow, and MusicAbstractItemQueryWidget::m_networkRequest.
MusicPlaylistQueryWidget::~MusicPlaylistQueryWidget ()
Definition at line 140 of file musicplaylistquerywidget.cpp.
References m_categoryButton, m_gridLayout, m_infoWidget, and m_pageQueryWidget.
Member Function Documentation
void MusicPlaylistQueryWidget::backToPlaylistMenu () slot
Set current index to playlist menu page.
Definition at line 276 of file musicplaylistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_container.
void MusicPlaylistQueryWidget::buttonClicked (int index) slot
Page widget button has changed.
Definition at line 300 of file musicplaylistquerywidget.cpp.
References MusicPageQueryWidget::currentIndex(), m_gridLayout, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicPageQueryWidget::page(), MusicPageQueryRequest::pageSize(), MusicPageQueryRequest::startToPage(), and MusicPageQueryRequest::totalSize().
Referenced by createPlaylistItem().
void MusicPlaylistQueryWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 281 of file musicplaylistquerywidget.cpp.
References MusicPlaylistFoundCategoryPopWidget::closeMenu(), m_categoryButton, m_categoryChanged, m_gridLayout, MusicResultsCategoryItem::m_key, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songNameFull, MusicResultsCategoryItem::m_value, MusicAbstractQueryRequest::Other, and MusicAbstractQueryRequest::startToSearch().
void MusicPlaylistQueryWidget::createPlaylistItem (const MusicResultDataItem & item) slot
Query all quality musics is finished.
Definition at line 185 of file musicplaylistquerywidget.cpp.
References buttonClicked(), TTK::UI::ColorStyle06, TTK::UI::ColorStyle08, MusicPageQueryWidget::createPageWidget(), currentPlaylistClicked(), TTK::Widget::generateVScrollAreaFormat(), LINE_SPACING_SIZE, m_categoryButton, m_categoryChanged, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_statusLabel, MusicPageQueryRequest::pageSize(), QUERY_WIDGET_WIDTH, MusicAbstractQueryRequest::queryServer(), MusicPageQueryWidget::reset(), MusicPlaylistFoundCategoryPopWidget::setCategory(), MusicPlaylistQueryItemWidget::setResultDataItem(), MusicPageQueryRequest::totalSize(), and TTKObjectCast.
Referenced by MusicPlaylistQueryWidget().
void MusicPlaylistQueryWidget::currentPlaylistClicked (const MusicResultDataItem & item) slot
Current play list clicked.
Definition at line 258 of file musicplaylistquerywidget.cpp.
References G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_container, m_infoWidget, MusicQueryPlaylistRequest::queryPlaylistInfo(), MusicPlaylistQueryInfoWidget::setQueryInput(), MusicPlaylistQueryInfoWidget::setResultDataItem(), and TTKObjectCast.
Referenced by createPlaylistItem(), and setSongNameByID().
void MusicPlaylistQueryWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 163 of file musicplaylistquerywidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, m_infoWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, QUERY_WIDGET_WIDTH, and MusicPlaylistQueryInfoWidget::resizeWidget().
void MusicPlaylistQueryWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 148 of file musicplaylistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractQueryRequest::Other, MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSearch().
Referenced by setSongNameByID(), and MusicRightAreaWidget::showPlaylistFound().
void MusicPlaylistQueryWidget::setSongNameByID (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 154 of file musicplaylistquerywidget.cpp.
References currentPlaylistClicked(), MusicResultDataItem::m_id, and setSongName().
Referenced by MusicRightAreaWidget::showPlaylistFound().
Member Data Documentation
MusicPlaylistFoundCategoryPopWidget* MusicPlaylistQueryWidget::m_categoryButton private
Definition at line 132 of file musicplaylistquerywidget.h.
Referenced by categoryChanged(), createPlaylistItem(), and ~MusicPlaylistQueryWidget().
bool MusicPlaylistQueryWidget::m_categoryChanged private
Definition at line 128 of file musicplaylistquerywidget.h.
Referenced by categoryChanged(), and createPlaylistItem().
QGridLayout* MusicPlaylistQueryWidget::m_gridLayout private
Definition at line 129 of file musicplaylistquerywidget.h.
Referenced by buttonClicked(), categoryChanged(), createPlaylistItem(), resizeWidget(), and ~MusicPlaylistQueryWidget().
MusicPlaylistQueryInfoWidget* MusicPlaylistQueryWidget::m_infoWidget private
Definition at line 131 of file musicplaylistquerywidget.h.
Referenced by currentPlaylistClicked(), resizeWidget(), and ~MusicPlaylistQueryWidget().
bool MusicPlaylistQueryWidget::m_initialized private
Definition at line 128 of file musicplaylistquerywidget.h.
Referenced by createPlaylistItem().
MusicPageQueryWidget* MusicPlaylistQueryWidget::m_pageQueryWidget private
Definition at line 130 of file musicplaylistquerywidget.h.
Referenced by buttonClicked(), createPlaylistItem(), and ~MusicPlaylistQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistquerywidget.cpp