TTKMusicplayer: MusicTKPLConfigManager Class Reference
MusicTKPLConfigManager Class Reference
The class of the tkpl config manager.
#include <musictkplconfigmanager.h>
Public Member Functions
MusicTKPLConfigManager ()
bool readConfig (const QString &name=MUSICPATH_FULL)
virtual bool readPlaylistData (MusicSongItems &items) override
virtual bool writePlaylistData (const MusicSongItems &items, const QString &path) override
Public Member Functions inherited from MusicAbstractXml
MusicAbstractXml (QObject *parent=nullptr)
virtual ~MusicAbstractXml ()
bool readConfig (const QString &name)
bool writeConfig (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagNameValue (const QString &tagName) const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName) const
QString readXmlTextByTagName (const QString &tagName) const
TTKVariantMap readXmlAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const MusicXmlAttribute &attr)
QDomElement createRoot (const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const MusicXmlAttribute &attr)
QDomElement writeDomElementMutil (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const MusicXmlAttribute &attr, const QString &text)
QDomElement writeDomElementMutilText (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const MusicXmlAttribute &attr)
Protected Member Functions
MusicSongs readMusicFilePath (const QDomNode &node) const
Additional Inherited Members
Protected Attributes inherited from MusicAbstractXml
QFile * m_file
QDomDocument * m_document
Private Member Functions inherited from MusicPlaylistInterface
MusicPlaylistInterface ()
virtual ~MusicPlaylistInterface ()
Detailed Description
The class of the tkpl config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musictkplconfigmanager.h.
Constructor & Destructor Documentation
MusicTKPLConfigManager::MusicTKPLConfigManager () explicit
Object contsructor.
Definition at line 3 of file musictkplconfigmanager.cpp.
Member Function Documentation
bool MusicTKPLConfigManager::readConfig (const QString & name = MUSICPATH_FULL) inline
Read config datas from xml file by given name.
Definition at line 41 of file musictkplconfigmanager.h.
References name, and MusicAbstractXml::readConfig().
Referenced by MusicConsoleModule::init(), MusicApplication::readSystemConfigFromFile(), and MusicPlaylistManager::readTKPLConfig().
MusicSongs MusicTKPLConfigManager::readMusicFilePath (const QDomNode & node) const protected
Read Music File Path.
Definition at line 61 of file musictkplconfigmanager.cpp.
Referenced by readPlaylistData().
bool MusicTKPLConfigManager::readPlaylistData (MusicSongItems & items) override virtual
Read datas from config file.
Implements MusicPlaylistInterface.
Definition at line 10 of file musictkplconfigmanager.cpp.
References MusicAbstractXml::m_document, MusicSongSort::m_index, MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicSongItem::m_sort, MusicSongSort::m_sortType, readMusicFilePath(), and TTKStatic_cast.
Referenced by MusicConsoleModule::init(), MusicApplication::readSystemConfigFromFile(), and MusicPlaylistManager::readTKPLConfig().
bool MusicTKPLConfigManager::writePlaylistData (const MusicSongItems & items, const QString & path) override virtual
Write datas into config file.
Implements MusicPlaylistInterface.
Definition at line 31 of file musictkplconfigmanager.cpp.
References APP_NAME, MusicAbstractXml::createProcessingInstruction(), MusicAbstractXml::createRoot(), MusicAbstractXml::m_document, MusicAbstractXml::m_file, MusicSongSort::m_index, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicSongItem::m_sort, MusicSongSort::m_sortType, MusicAbstractXml::writeConfig(), MusicAbstractXml::writeDomElementMutil(), and MusicAbstractXml::writeDomElementMutilText().
Referenced by MusicApplication::writeSystemConfigToFile(), and MusicPlaylistManager::writeTKPLConfig().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musictkplconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musictkplconfigmanager.cpp