TTKMusicPlayer: MusicSongSharingWidget Class Reference
MusicSongSharingWidget Class Reference
The class of the song share widget.
#include <musicsongsharingwidget.h>
Classes
struct Item
Public Types
enum Module {
Module::Song, Module::Movie, Module::Artist, Module::Album,
Module::Playlist, Module::Null
}
Public Slots
void textAreaChanged ()
void confirmButtonClicked ()
void shareTimeout ()
void downLoadFinished (const QByteArray &bytes)
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Public Member Functions
MusicSongSharingWidget (QWidget *parent=nullptr)
~MusicSongSharingWidget ()
void initialize (Module type, const MusicSongSharingWidget::Item &data)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show) noexcept
void blockOption (bool block) noexcept
Private Member Functions
void sendToShare (const QString &playUrl, const QString &imageUrl)
void sendToShare (const QString &a, const QString &b, const QString &c)
Private Attributes
Ui::MusicSongSharingWidget * m_ui
Module m_type
QRCodeQWidget * m_qrCodeWidget
MusicSongSharingWidget::Item m_data
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label) noexcept
Protected Attributes inherited from TTKAbstractMoveDialog
QPoint m_mousePressedAt
bool m_blockOption
bool m_shadowOption
bool m_mouseLeftPressed
Detailed Description
The class of the song share widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 57 of file musicsongsharingwidget.h.
Member Enumeration Documentation
enum MusicSongSharingWidget::Module strong
Enumerator
Song
song type
Movie
Movie type
Artist
artist type
Album
album type
Playlist
playlist type
Null
null type
Definition at line 62 of file musicsongsharingwidget.h.
Constructor & Destructor Documentation
MusicSongSharingWidget::MusicSongSharingWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 12 of file musicsongsharingwidget.cpp.
References confirmButtonClicked(), m_qrCodeWidget, m_ui, MusicWidgetRenderer::setBackgroundLabel(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), textAreaChanged(), TTK::UI::TextEditStyle01, and TTK::UI::ToolButtonStyle04.
MusicSongSharingWidget::~MusicSongSharingWidget ()
Object destructor.
Definition at line 49 of file musicsongsharingwidget.cpp.
References m_qrCodeWidget, and m_ui.
Member Function Documentation
void MusicSongSharingWidget::confirmButtonClicked () slot
Confirm button clicked.
Definition at line 76 of file musicsongsharingwidget.cpp.
References Album, Artist, TTKEventLoop::exec(), G_DOWNLOAD_QUERY_PTR, MusicAbstractQueryRequest::isEmpty(), MusicAbstractQueryRequest::items(), KG_AL_SHARE, KG_AR_SHARE, KG_MV_SHARE, KG_PL_SHARE, KG_SG_SHARE, KW_AL_SHARE, KW_AR_SHARE, KW_MV_SHARE, KW_PL_SHARE, KW_SG_SHARE, MusicSongSharingWidget::Item::m_cover, TTK::MusicSongInformation::m_coverUrl, m_data, MusicSongSharingWidget::Item::m_id, MusicSongSharingWidget::Item::m_server, TTK::MusicSongInformation::m_songId, m_type, m_ui, MusicAbstractQueryRequest::Meta, Movie, Playlist, MusicAbstractQueryRequest::queryServer(), sendToShare(), MusicAbstractQueryRequest::setQueryMode(), shareTimeout(), Song, MusicAbstractQueryRequest::startToSearch(), TTK_DN_S2MS, TTK_SIGNLE_SHOT, TTK_SLOT, WY_AL_SHARE, WY_AR_SHARE, WY_MV_SHARE, WY_PL_SHARE, and WY_SG_SHARE.
Referenced by MusicSongSharingWidget().
void MusicSongSharingWidget::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 209 of file musicsongsharingwidget.cpp.
References m_ui, and TTK_ERROR_STREAM.
Referenced by initialize().
void MusicSongSharingWidget::initialize (Module type, const MusicSongSharingWidget::Item & data)
Set current data to share.
Definition at line 55 of file musicsongsharingwidget.cpp.
References ART_DIR_FULL, downLoadFinished(), TTK::Widget::elidedText(), G_DOWNLOAD_QUERY_PTR, TTK::generateSongArtist(), TTK::isCoverValid(), MusicSongSharingWidget::Item::m_cover, m_data, MusicSongSharingWidget::Item::m_name, m_type, m_ui, name, SKN_FILE, and MusicCoverRequest::startToRequest().
Referenced by MusicAbstractItemQueryWidget::shareButtonClicked(), MusicVideoPlayWidget::shareButtonClicked(), MusicAbstractSongsListTableWidget::showPlayedSongSharedWidget(), MusicAbstractSongsListTableWidget::showSongSharedWidget(), and MusicIdentifySongWidget::showSongShareWidget().
void MusicSongSharingWidget::sendToShare (const QString & playUrl, const QString & imageUrl) private
Send to shared on web.
Definition at line 132 of file musicsongsharingwidget.cpp.
References m_qrCodeWidget, m_ui, TTK::Algorithm::mdII(), MDII_SHR_KEY, TTK::Url::openUrl(), QQ_SHARE, QZONE_SHARE, QRCodeQWidget::setText(), SINA_SHARE, TTK_DN_S2MS, TTK_SIGNLE_SHOT, and TTK_SLOT.
Referenced by confirmButtonClicked(), and sendToShare().
void MusicSongSharingWidget::sendToShare (const QString & a, const QString & b, const QString & c) private
Send to shared on web.
Definition at line 164 of file musicsongsharingwidget.cpp.
References MusicSongSharingWidget::Item::m_cover, m_data, MusicSongSharingWidget::Item::m_id, MusicSongSharingWidget::Item::m_server, TTK::Algorithm::mdII(), MDII_SHR_KEY, QUERY_KG_INTERFACE, QUERY_KW_INTERFACE, QUERY_WY_INTERFACE, sendToShare(), shareTimeout(), TTK_DN_S2MS, TTK_SIGNLE_SHOT, and TTK_SLOT.
void MusicSongSharingWidget::shareTimeout () slot
Query url time out, that means share failed.
Definition at line 127 of file musicsongsharingwidget.cpp.
References MusicToastLabel::popup().
Referenced by confirmButtonClicked(), and sendToShare().
void MusicSongSharingWidget::textAreaChanged () slot
User custom the current share text.
Definition at line 188 of file musicsongsharingwidget.cpp.
References m_ui, and TTK::max().
Referenced by MusicSongSharingWidget().
Member Data Documentation
MusicSongSharingWidget::Item MusicSongSharingWidget::m_data private
Definition at line 126 of file musicsongsharingwidget.h.
Referenced by confirmButtonClicked(), initialize(), and sendToShare().
QRCodeQWidget* MusicSongSharingWidget::m_qrCodeWidget private
Definition at line 125 of file musicsongsharingwidget.h.
Referenced by MusicSongSharingWidget(), sendToShare(), and ~MusicSongSharingWidget().
Module MusicSongSharingWidget::m_type private
Definition at line 124 of file musicsongsharingwidget.h.
Referenced by confirmButtonClicked(), and initialize().
Ui::MusicSongSharingWidget* MusicSongSharingWidget::m_ui private
Definition at line 123 of file musicsongsharingwidget.h.
Referenced by confirmButtonClicked(), downLoadFinished(), initialize(), MusicSongSharingWidget(), sendToShare(), textAreaChanged(), and ~MusicSongSharingWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongsharingwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongsharingwidget.cpp