TTKMusicplayer: MusicWYSongCommentsThread Class Reference
MusicWYSongCommentsThread Class Reference
The class to wangyi query song comments download data from net.
#include <musicwycommentsthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYSongCommentsThread (QObject *parent=0)
QJson import.
virtual void startToSearch (const QString &name) override
virtual void startToPage (int offset) override
Public Member Functions inherited from MusicDownLoadCommentsThread
MusicDownLoadCommentsThread (QObject *parent=0)
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadCommentsThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadCommentsThread
void createSearchedItem (const MusicResultsItem &comments)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to wangyi query song comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwycommentsthread.h.
Constructor & Destructor Documentation
MusicWYSongCommentsThread::MusicWYSongCommentsThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 8 of file musicwycommentsthread.cpp.
References MusicDownLoadPagingThread::m_pageSize.
Member Function Documentation
void MusicWYSongCommentsThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 63 of file musicwycommentsthread.cpp.
References MusicDownLoadCommentsThread::createSearchedItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicResultsItem::m_nickName, MusicDownLoadPagingThread::m_pageTotal, MusicResultsItem::m_playCount, MusicNetworkAbstract::m_reply, MusicResultsItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToPage().
QString MusicWYSongCommentsThread::getClassName () static
Get class object name.
Definition at line 14 of file musicwycommentsthread.cpp.
Referenced by downLoadFinished(), startToPage(), and startToSearch().
void MusicWYSongCommentsThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 38 of file musicwycommentsthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_rawData, MusicNetworkAbstract::m_reply, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), WY_COMMIT_NDT_URL, and WY_SG_COMMIT_N_URL.
Referenced by startToSearch().
void MusicWYSongCommentsThread::startToSearch (const QString & name) override virtual
Start to Search data from name.
Implements MusicDownLoadCommentsThread.
Definition at line 19 of file musicwycommentsthread.cpp.
References MusicNetworkAbstract::downLoadDataChanged(), MusicSemaphoreLoop::exec(), getClassName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), M_LOGGER_INFO, MusicNetworkAbstract::m_rawData, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), MusicDownLoadQueryThreadAbstract::setQuerySimplify(), startToPage(), and MusicDownLoadQueryWYThread::startToSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicwycommentsthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicwycommentsthread.cpp