TTKMusicplayer: MusicUtils::Codec Namespace Reference
MusicUtils::Codec Namespace Reference
Functions
MUSIC_UTILS_EXPORT QString toUnicode (const char *chars, const char *format="GBK")
MUSIC_UTILS_EXPORT QString toUnicode (const QByteArray &chars, const char *format="GBK")
MUSIC_UTILS_EXPORT QByteArray fromUnicode (const QString &chars, const char *format="GBK")
MUSIC_UTILS_EXPORT void setLocalCodec (const char *format="utf-8")
MUSIC_UTILS_EXPORT const char * toLocal8Bit (const QString &str)
MUSIC_UTILS_EXPORT const char * toUtf8 (const QString &str)
Function Documentation
QByteArray MusicUtils::Codec::fromUnicode (const QString & chars, const char * format = "GBK")
Set string from unicode string by format.
Definition at line 18 of file musiccodecutils.cpp.
void MusicUtils::Codec::setLocalCodec (const char * format = "utf-8")
Set local codec by format.
Definition at line 24 of file musiccodecutils.cpp.
Referenced by MusicRunTimeManager::run().
const char * MusicUtils::Codec::toLocal8Bit (const QString & str)
Trasform string to local 8bit char.
Definition at line 34 of file musiccodecutils.cpp.
Referenced by MusicAudioRecorderCore::addWavHeader(), MusicLrcFromKrc::decode(), MusicExtractWrap::inputSkin(), MusicAudioRecorderWidget::onRecordSave(), and MusicSoundKMicroWidget::playFinished().
QString MusicUtils::Codec::toUnicode (const char * chars, const char * format = "GBK")
Set string to unicode string by format.
Definition at line 6 of file musiccodecutils.cpp.
QString MusicUtils::Codec::toUnicode (const QByteArray & chars, const char * format = "GBK")
Set string to unicode string by format.
Definition at line 12 of file musiccodecutils.cpp.
const char * MusicUtils::Codec::toUtf8 (const QString & str)
Trasform string to utf8 char.
Definition at line 39 of file musiccodecutils.cpp.
Referenced by QAesWrap::decrypt(), MusicQQTextDownLoadThread::downLoadFinished(), MusicQQBackgroundThread::downLoadUrl(), MusicKWArtistSimilarThread::getArtistIdName(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQQInterface::getMusicKey(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadWYInterface::makeTokenQueryQequest(), MusicDownLoadBDInterface::makeTokenQueryUrl(), MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicDownLoadKWInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAlbumInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), MusicDownLoadKWInterface::readFromMusicSongPic(), MusicCoreMPlayer::setLeftVolume(), MusicCoreMPlayer::setMultiVoice(), MusicCoreMPlayer::setMute(), MusicCoreMPlayer::setPosition(), MusicCoreMPlayer::setRightVolume(), MusicCoreMPlayer::setVolume(), MusicQQTextDownLoadThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicDownLoadQueryYYTThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicMVRadioThreadAbstract::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryKWThread::startToSingleSearch(), and MusicCryptographicHash::xxteaEncrypt().