TTKMusicPlayer: MusicScreenSaverListItem Class Reference
MusicScreenSaverListItem Class Reference
The class of the screen saver list item.
#include <musicscreensaverwidget.h>
Public Member Functions
MusicScreenSaverListItem (QObject *object, QWidget *parent=nullptr)
~MusicScreenSaverListItem ()
void setFilePath (const QString &path)
void setStatus (int index, bool status)
void setHoverVisible (bool v)
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
Private Attributes
MusicScreenSaverHoverItem * m_hoverItem
Detailed Description
The class of the screen saver list item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 87 of file musicscreensaverwidget.h.
Constructor & Destructor Documentation
MusicScreenSaverListItem::MusicScreenSaverListItem (QObject * object, QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 111 of file musicscreensaverwidget.cpp.
References m_hoverItem.
MusicScreenSaverListItem::~MusicScreenSaverListItem ()
Object destructor.
Definition at line 121 of file musicscreensaverwidget.cpp.
References m_hoverItem.
Member Function Documentation
void MusicScreenSaverListItem::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Definition at line 148 of file musicscreensaverwidget.cpp.
References setHoverVisible().
void MusicScreenSaverListItem::setFilePath (const QString & path)
Set item file name.
Definition at line 126 of file musicscreensaverwidget.cpp.
References m_hoverItem, and MusicScreenSaverHoverItem::setFilePath().
Referenced by MusicScreenSaverListWidget::addCellItem().
void MusicScreenSaverListItem::setHoverVisible (bool v)
Set item visible or not.
Definition at line 136 of file musicscreensaverwidget.cpp.
References MusicScreenSaverHoverItem::display(), and m_hoverItem.
Referenced by enterEvent().
void MusicScreenSaverListItem::setStatus (int index, bool status)
Set item status.
Definition at line 131 of file musicscreensaverwidget.cpp.
References m_hoverItem, and MusicScreenSaverHoverItem::setStatus().
Referenced by MusicScreenSaverListWidget::addCellItem().
Member Data Documentation
MusicScreenSaverHoverItem* MusicScreenSaverListItem::m_hoverItem private
Definition at line 120 of file musicscreensaverwidget.h.
Referenced by MusicScreenSaverListItem(), setFilePath(), setHoverVisible(), setStatus(), and ~MusicScreenSaverListItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.cpp