TTKMusicplayer: MusicWYTranslationThread Class Reference
MusicWYTranslationThread Class Reference
The class of wangyi translation words thread.
#include <musicwytranslationthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYTranslationThread (QObject *parent=0)
QJson import.
virtual ~MusicWYTranslationThread ()
virtual void startToDownload (const QString &data) override
Public Member Functions inherited from MusicTranslationThreadAbstract
MusicTranslationThreadAbstract (QObject *parent=0)
void setRawData (const QVariantMap &data)
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicTranslationThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicTranslationThreadAbstract
void downLoadDataChanged (const QString &data)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicTranslationThreadAbstract
QVariantMap m_rawData
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of wangyi translation words thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicwytranslationthread.h.
Constructor & Destructor Documentation
MusicWYTranslationThread::MusicWYTranslationThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 8 of file musicwytranslationthread.cpp.
MusicWYTranslationThread::~MusicWYTranslationThread () virtual
Definition at line 14 of file musicwytranslationthread.cpp.
References MusicTranslationThreadAbstract::deleteAll().
Member Function Documentation
void MusicWYTranslationThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 55 of file musicwytranslationthread.cpp.
References MusicTranslationThreadAbstract::deleteAll(), MusicTranslationThreadAbstract::downLoadDataChanged(), M_LOGGER_ERROR, MusicNetworkAbstract::m_reply, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicWYTranslationThread::getClassName () static
Get class object name.
Definition at line 19 of file musicwytranslationthread.cpp.
Referenced by startToDownload().
void MusicWYTranslationThread::startToDownload (const QString & data) override virtual
Start to translation data.
Implements MusicTranslationThreadAbstract.
Definition at line 24 of file musicwytranslationthread.cpp.
References MusicTranslationThreadAbstract::downLoadDataChanged(), downLoadFinished(), MusicSemaphoreLoop::exec(), getClassName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicTranslationThreadAbstract::m_rawData, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::mdII(), MusicDownLoadQueryThreadAbstract::MusicQuery, MusicNetworkAbstract::replyError(), MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), MusicDownLoadQueryThreadAbstract::setQuerySimplify(), MusicNetworkAbstract::setSslConfiguration(), MusicNetworkAbstract::sslErrors(), MusicDownLoadQueryWYThread::startToSearch(), and WY_SONG_LRC_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicwytranslationthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicwytranslationthread.cpp