TTKMusicPlayer: MusicBarrageAnimation Class Reference
MusicBarrageAnimation Class Reference
The class of the barrage animation.
#include <musicbarragewidget.h>
Public Member Functions
MusicBarrageAnimation (QObject *parent=nullptr)
MusicBarrageAnimation (QObject *target, const QByteArray &name, QObject *parent=nullptr)
void setSize (const QSize &size)
Private Slots
void animationFinished ()
Private Member Functions
void initialize ()
Private Attributes
QSize m_parentSize
Detailed Description
The class of the barrage animation.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicbarragewidget.h.
Constructor & Destructor Documentation
MusicBarrageAnimation::MusicBarrageAnimation (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musicbarragewidget.cpp.
References initialize().
MusicBarrageAnimation::MusicBarrageAnimation (QObject * target, const QByteArray & name, QObject * parent = nullptr)
Object contsructor by tagrget and name.
Definition at line 10 of file musicbarragewidget.cpp.
References initialize().
Member Function Documentation
void MusicBarrageAnimation::animationFinished () private slot
Current animation is finished.
Definition at line 16 of file musicbarragewidget.cpp.
References m_parentSize, MT_S2MS, TTKObject::random(), and setSize().
Referenced by initialize().
void MusicBarrageAnimation::initialize () private
Init parameters.
Definition at line 31 of file musicbarragewidget.cpp.
References animationFinished(), MT_S2MS, and TTKObject::random().
Referenced by MusicBarrageAnimation().
void MusicBarrageAnimation::setSize (const QSize & size)
Set animation region size.
Definition at line 23 of file musicbarragewidget.cpp.
References m_parentSize, and TTKObject::random().
Referenced by animationFinished(), and MusicBarrageWidget::createAnimation().
Member Data Documentation
QSize MusicBarrageAnimation::m_parentSize private
Definition at line 61 of file musicbarragewidget.h.
Referenced by animationFinished(), and setSize().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicVideoKits/musicbarragewidget.h
TTKModule/TTKCore/musicVideoKits/musicbarragewidget.cpp