TTKMusicPlayer: MusicWebDJRadioQueryItemWidget Class Reference
MusicWebDJRadioQueryItemWidget Class Reference
The class of the dj radio music item widget.
#include <musicwebdjradioquerywidget.h>
Public Slots
void downLoadFinished (const QByteArray &bytes)
void renderFinished (const QPixmap &data)
void currentItemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicWebDJRadioQueryItemWidget (QWidget *parent=nullptr)
~MusicWebDJRadioQueryItemWidget ()
void setResultDataItem (const MusicResultDataItem &item)
Private Attributes
MusicResultDataItem m_itemData
QPushButton * m_playButton
QLabel * m_iconLabel
QLabel * m_nameLabel
QLabel * m_creatorLabel
Detailed Description
The class of the dj radio music item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicwebdjradioquerywidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioQueryItemWidget::MusicWebDJRadioQueryItemWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 15 of file musicwebdjradioquerywidget.cpp.
References currentItemClicked(), HEIGHT_LABEL_SIZE, m_creatorLabel, m_iconLabel, m_nameLabel, m_playButton, MusicUIObject::TinyBtnPlaylist, and WIDTH_LABEL_SIZE.
MusicWebDJRadioQueryItemWidget::~MusicWebDJRadioQueryItemWidget ()
Definition at line 42 of file musicwebdjradioquerywidget.cpp.
References m_creatorLabel, m_iconLabel, m_nameLabel, and m_playButton.
Member Function Documentation
void MusicWebDJRadioQueryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
void MusicWebDJRadioQueryItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 86 of file musicwebdjradioquerywidget.cpp.
References m_itemData.
Referenced by MusicWebDJRadioQueryItemWidget().
void MusicWebDJRadioQueryItemWidget::downLoadFinished (const QByteArray & bytes) slot
Send recieved data from net.
Definition at line 66 of file musicwebdjradioquerywidget.cpp.
References m_iconLabel, renderFinished(), MusicImageRenderer::setInputData(), TTKAbstractThread::start(), and TTK_ERROR_STREAM.
Referenced by setResultDataItem().
void MusicWebDJRadioQueryItemWidget::renderFinished (const QPixmap & data) slot
Image render finished.
Definition at line 80 of file musicwebdjradioquerywidget.cpp.
References m_iconLabel, and m_playButton.
Referenced by downLoadFinished().
void MusicWebDJRadioQueryItemWidget::setResultDataItem (const MusicResultDataItem & item)
Set music results item.
Definition at line 50 of file musicwebdjradioquerywidget.cpp.
References downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultDataItem::m_coverUrl, m_creatorLabel, m_itemData, MusicResultDataItem::m_name, m_nameLabel, MusicResultDataItem::m_nickName, MusicDownloadSourceRequest::startRequest(), TTK_NULL_STR, and WIDTH_LABEL_SIZE.
Referenced by MusicWebDJRadioQueryWidget::createProgramItem().
Member Data Documentation
QLabel * MusicWebDJRadioQueryItemWidget::m_creatorLabel private
Definition at line 70 of file musicwebdjradioquerywidget.h.
Referenced by MusicWebDJRadioQueryItemWidget(), setResultDataItem(), and ~MusicWebDJRadioQueryItemWidget().
QLabel* MusicWebDJRadioQueryItemWidget::m_iconLabel private
Definition at line 70 of file musicwebdjradioquerywidget.h.
Referenced by downLoadFinished(), MusicWebDJRadioQueryItemWidget(), renderFinished(), and ~MusicWebDJRadioQueryItemWidget().
MusicResultDataItem MusicWebDJRadioQueryItemWidget::m_itemData private
Definition at line 68 of file musicwebdjradioquerywidget.h.
Referenced by currentItemClicked(), and setResultDataItem().
QLabel * MusicWebDJRadioQueryItemWidget::m_nameLabel private
Definition at line 70 of file musicwebdjradioquerywidget.h.
Referenced by MusicWebDJRadioQueryItemWidget(), setResultDataItem(), and ~MusicWebDJRadioQueryItemWidget().
QPushButton* MusicWebDJRadioQueryItemWidget::m_playButton private
Definition at line 69 of file musicwebdjradioquerywidget.h.
Referenced by MusicWebDJRadioQueryItemWidget(), renderFinished(), and ~MusicWebDJRadioQueryItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradioquerywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradioquerywidget.cpp