TTKMusicplayer: QImageWrap Class Reference
QImageWrap Class Reference
The namespace of the image wrapper.
#include <qimagewrap.h>
Public Member Functions
QImage GaussFilter (const QImage &image, int radius=10)
Detailed Description
The namespace of the image wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 17 of file qimagewrap.h.
Member Function Documentation
QImage QImageWrap::GaussFilter (const QImage & image, int radius = 10)
Image gauss filter.
Definition at line 6 of file qimagewrap.cpp.
References filter::Average(), filter::Blur1D(), filter::Blur2D(), filter::Filter(), filter::Gauss(), filter::Gauss2(), filter::Linear(), and filter::bitmap_t::set().
Referenced by MusicLrcPosterItemWidget::drawTheme10().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKImage/qimagewrap.h
TTKThirdParty/TTKImage/qimagewrap.cpp