TTKMusicplayer: OSSDeleteData Class Reference
OSSDeleteData Class Reference
The class of the alioss cloud data item.
#include <ossdeletedata.h>
Signals
void deleteFileFinished (bool state)
Public Member Functions
OSSDeleteData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void deleteDataOperator (const QString &bucket, const QString &file)
Public Member Functions inherited from OSSDataInterface
OSSDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Protected Slots
virtual void receiveDataFromServer () override
Protected Slots inherited from OSSDataInterface
virtual void receiveDataFromServer ()=0
void handleError (QNetworkReply::NetworkError error)
Detailed Description
The class of the alioss cloud data item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file ossdeletedata.h.
Constructor & Destructor Documentation
OSSDeleteData::OSSDeleteData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file ossdeletedata.cpp.
Member Function Documentation
void OSSDeleteData::deleteDataOperator (const QString & bucket, const QString & file)
Delete data operater.
Definition at line 10 of file ossdeletedata.cpp.
References OSSUtils::getGMT(), OSSDataInterface::handleError(), MusicObject::NetworkError, OSSConf::OSS_HOST, receiveDataFromServer(), and TTK_D.
Referenced by MusicCloudManagerTableWidget::deleteFilesToServer(), and MusicCloudManagerTableWidget::deleteFileToServer().
void OSSDeleteData::deleteFileFinished (bool state) signal
Delete file finished.
Referenced by receiveDataFromServer().
void OSSDeleteData::receiveDataFromServer () override protected virtual slot
Receive data from server.
Definition at line 39 of file ossdeletedata.cpp.
References deleteFileFinished(), and MObject_cast.
Referenced by deleteDataOperator().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qoss/ossdeletedata.h
TTKThirdParty/TTKExtras/qoss/ossdeletedata.cpp