TTKMusicPlayer: MusicToolMenu Class Reference
MusicToolMenu Class Reference
The class of the tool menu.
#include <musictoolmenuwidget.h>
Signals
void windowStateChanged (bool state)
Public Member Functions
MusicToolMenu (QWidget *parent=nullptr)
Private Member Functions
virtual void showEvent (QShowEvent *event) overridefinal
virtual void hideEvent (QHideEvent *event) overridefinal
Detailed Description
The class of the tool menu.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musictoolmenuwidget.h.
Constructor & Destructor Documentation
MusicToolMenu::MusicToolMenu (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musictoolmenuwidget.cpp.
Member Function Documentation
void MusicToolMenu::hideEvent (QHideEvent * event) final override private virtual
Definition at line 17 of file musictoolmenuwidget.cpp.
References windowStateChanged().
void MusicToolMenu::showEvent (QShowEvent * event) final override private virtual
Override the widget event.
Definition at line 11 of file musictoolmenuwidget.cpp.
References windowStateChanged().
void MusicToolMenu::windowStateChanged (bool state) signal
Window state changed.
Referenced by hideEvent(), and showEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musictoolmenuwidget.h
TTKModule/TTKWidget/musicCoreKits/musictoolmenuwidget.cpp