TTKMusicPlayer: MusicVolumePopWidget Class Reference
MusicVolumePopWidget Class Reference
The class of the volume popup widget.
#include <musicvolumepopwidget.h>
Public Slots
void timeToReset ()
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Signals
void musicVolumeChanged (int volume)
Public Member Functions
MusicVolumePopWidget (QWidget *parent=nullptr)
~MusicVolumePopWidget ()
void setValue (int value)
int value () const
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Private Member Functions
virtual void leaveEvent (QEvent *event) overridefinal
virtual void enterEvent (QtEnterEvent *event) overridefinal
void initialize ()
Private Attributes
bool m_menuShown
TTKClickedSlider * m_volumeSlider
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the volume popup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicvolumepopwidget.h.
Constructor & Destructor Documentation
MusicVolumePopWidget::MusicVolumePopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicvolumepopwidget.cpp.
References initialize(), and MusicToolMenuWidget::popupMenu().
MusicVolumePopWidget::~MusicVolumePopWidget ()
Definition at line 17 of file musicvolumepopwidget.cpp.
References m_volumeSlider.
Member Function Documentation
void MusicVolumePopWidget::enterEvent (QtEnterEvent * event) final override private virtual
Definition at line 60 of file musicvolumepopwidget.cpp.
References m_menuShown, MT_S2MS, MusicToolMenuWidget::popupMenu(), and timeToReset().
void MusicVolumePopWidget::initialize () private
Create all widget in layout.
Definition at line 76 of file musicvolumepopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, m_volumeSlider, musicVolumeChanged(), MusicToolMenuWidget::setTranslucentBackground(), and MusicUIObject::SliderStyle02.
Referenced by MusicVolumePopWidget().
void MusicVolumePopWidget::leaveEvent (QEvent * event) final override private virtual
Override the widget event.
Definition at line 54 of file musicvolumepopwidget.cpp.
References MusicToolMenuWidget::m_menu, and MT_S2MS.
void MusicVolumePopWidget::musicVolumeChanged (int volume) signal
Current play volume changed.
Referenced by initialize().
void MusicVolumePopWidget::setValue (int value)
Set slider value.
Definition at line 22 of file musicvolumepopwidget.cpp.
References MusicUIObject::BtnSound, and m_volumeSlider.
Referenced by MusicVideoControlWidget::MusicVideoControlWidget().
void MusicVolumePopWidget::timeToReset () slot
Timer ot reset show slider.
Definition at line 71 of file musicvolumepopwidget.cpp.
References m_menuShown.
Referenced by enterEvent().
int MusicVolumePopWidget::value () const
Get slider value.
Definition at line 49 of file musicvolumepopwidget.cpp.
References m_volumeSlider.
Member Data Documentation
bool MusicVolumePopWidget::m_menuShown private
Definition at line 72 of file musicvolumepopwidget.h.
Referenced by enterEvent(), and timeToReset().
TTKClickedSlider* MusicVolumePopWidget::m_volumeSlider private
Definition at line 73 of file musicvolumepopwidget.h.
Referenced by initialize(), setValue(), value(), and ~MusicVolumePopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicvolumepopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicvolumepopwidget.cpp