TTKMusicPlayer: TTKAbstractItemDelegate Class Reference
TTKAbstractItemDelegate Class Reference
The class of the abstract item delegate.
#include <ttkitemdelegate.h>
Public Types
enum Module { Null = 0x0, DisplayMode = 0x1, ElideMode = 0x2, TreeMode = 0x4 }
Public Member Functions
TTKAbstractItemDelegate (QObject *parent=nullptr)
void setModuleMode (TTKUInt8 mode)
void setStyleSheet (const QString &style) const
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &) const overridefinal
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Protected Attributes
TTKUInt8 m_mode
QWidget * m_container
Detailed Description
The class of the abstract item delegate.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 40 of file ttkitemdelegate.h.
Member Enumeration Documentation
enum TTKAbstractItemDelegate::Module
Enumerator
Null
DisplayMode
ElideMode
TreeMode
Definition at line 45 of file ttkitemdelegate.h.
Constructor & Destructor Documentation
TTKAbstractItemDelegate::TTKAbstractItemDelegate (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 9 of file ttkitemdelegate.cpp.
Member Function Documentation
void TTKAbstractItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Override paint.
Reimplemented in TTKPushButtonItemDelegate, TTKLabelItemDelegate, TTKProgressBarItemDelegate, and TTKCheckBoxItemDelegate.
Definition at line 32 of file ttkitemdelegate.cpp.
Referenced by TTKCheckBoxItemDelegate::paint(), TTKProgressBarItemDelegate::paint(), TTKLabelItemDelegate::paint(), and TTKPushButtonItemDelegate::paint().
void TTKAbstractItemDelegate::setModuleMode (TTKUInt8 mode) inline
Set module mode.
Definition at line 61 of file ttkitemdelegate.h.
Referenced by MusicPluginWidget::MusicPluginWidget(), and MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget().
void TTKAbstractItemDelegate::setStyleSheet (const QString & style) const
Set delegate item style.
Definition at line 17 of file ttkitemdelegate.cpp.
References m_container.
Referenced by makeButtonItemDelegate(), MusicAbstractDownloadTableWidget::MusicAbstractDownloadTableWidget(), MusicFillItemTableWidget::MusicFillItemTableWidget(), MusicPluginWidget::MusicPluginWidget(), MusicQueryTableWidget::MusicQueryTableWidget(), and MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget().
QSize TTKAbstractItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex &) const final override virtual
Override size hint.
Definition at line 25 of file ttkitemdelegate.cpp.
Member Data Documentation
QWidget* TTKAbstractItemDelegate::m_container protected
Definition at line 79 of file ttkitemdelegate.h.
Referenced by setStyleSheet(), TTKCheckBoxItemDelegate::TTKCheckBoxItemDelegate(), TTKLabelItemDelegate::TTKLabelItemDelegate(), TTKProgressBarItemDelegate::TTKProgressBarItemDelegate(), and TTKPushButtonItemDelegate::TTKPushButtonItemDelegate().
TTKUInt8 TTKAbstractItemDelegate::m_mode protected
Definition at line 78 of file ttkitemdelegate.h.
Referenced by TTKCheckBoxItemDelegate::paint(), TTKProgressBarItemDelegate::paint(), TTKLabelItemDelegate::paint(), and TTKPushButtonItemDelegate::paint().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkitemdelegate.h
TTKCommon/TTKLibrary/ttkitemdelegate.cpp