TTKMusicPlayer: MusicPlaylistQueryItemWidget Class Reference
MusicPlaylistQueryItemWidget Class Reference
The class of the playlist music item widget.
#include <musicplaylistquerywidget.h>
Public Slots
void downLoadFinished (const QByteArray &bytes)
void renderFinished (const QPixmap &data)
void currentItemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicPlaylistQueryItemWidget (QWidget *parent=nullptr)
~MusicPlaylistQueryItemWidget ()
void setResultDataItem (const MusicResultDataItem &item)
Private Attributes
MusicResultDataItem m_itemData
QPushButton * m_topListenButton
QPushButton * m_playButton
QLabel * m_iconLabel
QLabel * m_nameLabel
QLabel * m_creatorLabel
Detailed Description
The class of the playlist music item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicplaylistquerywidget.h.
Constructor & Destructor Documentation
MusicPlaylistQueryItemWidget::MusicPlaylistQueryItemWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 16 of file musicplaylistquerywidget.cpp.
References TTK::UI::BackgroundStyle04, TTK::UI::BorderStyle01, TTK::UI::ColorStyle06, currentItemClicked(), HEIGHT_LABEL_SIZE, m_creatorLabel, m_iconLabel, m_nameLabel, m_playButton, m_topListenButton, TTK::UI::TinyBtnPlaylist, TTK_DEFAULT_STR, and WIDTH_LABEL_SIZE.
MusicPlaylistQueryItemWidget::~MusicPlaylistQueryItemWidget ()
Object destructor.
Definition at line 50 of file musicplaylistquerywidget.cpp.
References m_creatorLabel, m_iconLabel, m_nameLabel, m_playButton, and m_topListenButton.
Member Function Documentation
void MusicPlaylistQueryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
void MusicPlaylistQueryItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 114 of file musicplaylistquerywidget.cpp.
References m_itemData.
Referenced by MusicPlaylistQueryItemWidget().
void MusicPlaylistQueryItemWidget::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 93 of file musicplaylistquerywidget.cpp.
References m_iconLabel, renderFinished(), MusicImageRenderer::setInputData(), TTKAbstractThread::start(), and TTK_ERROR_STREAM.
Referenced by setResultDataItem().
void MusicPlaylistQueryItemWidget::renderFinished (const QPixmap & data) slot
Image render finished.
Definition at line 107 of file musicplaylistquerywidget.cpp.
References m_iconLabel, m_playButton, and m_topListenButton.
Referenced by downLoadFinished().
void MusicPlaylistQueryItemWidget::setResultDataItem (const MusicResultDataItem & item)
Set music results item.
Definition at line 59 of file musicplaylistquerywidget.cpp.
References downLoadFinished(), TTK::Widget::elidedText(), G_DOWNLOAD_QUERY_PTR, TTK::isCoverValid(), MusicResultDataItem::m_count, MusicResultDataItem::m_coverUrl, m_creatorLabel, m_itemData, MusicResultDataItem::m_name, m_nameLabel, MusicResultDataItem::m_nickName, m_topListenButton, MusicCoverRequest::startToRequest(), and WIDTH_LABEL_SIZE.
Referenced by MusicPlaylistQueryWidget::createPlaylistItem().
Member Data Documentation
QLabel * MusicPlaylistQueryItemWidget::m_creatorLabel private
Definition at line 75 of file musicplaylistquerywidget.h.
Referenced by MusicPlaylistQueryItemWidget(), setResultDataItem(), and ~MusicPlaylistQueryItemWidget().
QLabel* MusicPlaylistQueryItemWidget::m_iconLabel private
Definition at line 75 of file musicplaylistquerywidget.h.
Referenced by downLoadFinished(), MusicPlaylistQueryItemWidget(), renderFinished(), and ~MusicPlaylistQueryItemWidget().
MusicResultDataItem MusicPlaylistQueryItemWidget::m_itemData private
Definition at line 73 of file musicplaylistquerywidget.h.
Referenced by currentItemClicked(), and setResultDataItem().
QLabel * MusicPlaylistQueryItemWidget::m_nameLabel private
Definition at line 75 of file musicplaylistquerywidget.h.
Referenced by MusicPlaylistQueryItemWidget(), setResultDataItem(), and ~MusicPlaylistQueryItemWidget().
QPushButton * MusicPlaylistQueryItemWidget::m_playButton private
Definition at line 74 of file musicplaylistquerywidget.h.
Referenced by MusicPlaylistQueryItemWidget(), renderFinished(), and ~MusicPlaylistQueryItemWidget().
QPushButton* MusicPlaylistQueryItemWidget::m_topListenButton private
Definition at line 74 of file musicplaylistquerywidget.h.
Referenced by MusicPlaylistQueryItemWidget(), renderFinished(), setResultDataItem(), and ~MusicPlaylistQueryItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistquerywidget.cpp