TTKMusicPlayer: MusicDownloadBingSkinRequest Class Reference
MusicDownloadBingSkinRequest Class Reference
The class of the download bing daily skin background.
#include <musicdownloadbingskinrequest.h>
Public Slots
virtual void downLoadFinished (const QByteArray &bytes) overridefinal
Public Slots inherited from MusicAbstractDownloadSkinRequest
virtual void downLoadFinished (const QByteArray &bytes)=0
Public Member Functions
MusicDownloadBingSkinRequest (QObject *parent=nullptr)
virtual void startToRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownloadSkinRequest
MusicAbstractDownloadSkinRequest (QObject *parent=nullptr)
virtual void startToRequest (const QString &id)
Additional Inherited Members
Signals inherited from MusicAbstractDownloadSkinRequest
void downLoadDataChanged (const MusicSkinRemoteGroupList &bytes)
Detailed Description
The class of the download bing daily skin background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadbingskinrequest.h.
Constructor & Destructor Documentation
MusicDownloadBingSkinRequest::MusicDownloadBingSkinRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicdownloadbingskinrequest.cpp.
Member Function Documentation
void MusicDownloadBingSkinRequest::downLoadFinished (const QByteArray & bytes) final override virtual slot
Download data from net finished.
Definition at line 20 of file musicdownloadbingskinrequest.cpp.
References MusicAbstractDownloadSkinRequest::downLoadDataChanged(), MusicSkinRemoteItem::isValid(), MusicSkinRemoteGroup::isValid(), MusicSkinRemoteGroup::m_group, MusicSkinRemoteGroup::m_id, MusicSkinRemoteItem::m_index, MusicSkinRemoteGroup::m_items, MusicSkinRemoteItem::m_name, MusicSkinRemoteItem::m_url, MusicSkinRemoteItem::m_useCount, TTK::Algorithm::mdII(), MUSIC_BING_DIR, QJson::Parser::parse(), PREFIX_URL, qAsConst, TTK::toString(), and TTK_DEFAULT_STR.
Referenced by startToRequest().
void MusicDownloadBingSkinRequest::startToRequest () final override virtual
Start to download skin data.
Reimplemented from MusicAbstractDownloadSkinRequest.
Definition at line 13 of file musicdownloadbingskinrequest.cpp.
References downLoadFinished(), TTK::Algorithm::mdII(), QUERY_URL, and MusicDataSourceRequest::startToRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadbingskinrequest.h
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadbingskinrequest.cpp