TTKMusicplayer: MusicUtils::File Namespace Reference
MusicUtils::File Namespace Reference
Functions
TTK_MODULE_EXPORT quint64 dirSize (const QString &dirName)
TTK_MODULE_EXPORT void checkCacheSize (quint64 cacheSize, bool disabled, const QString &path)
TTK_MODULE_EXPORT QFileInfoList getFileListByDir (const QString &dpath, bool recursively)
TTK_MODULE_EXPORT QFileInfoList getFileListByDir (const QString &dpath, const QStringList &filter, bool recursively)
TTK_MODULE_EXPORT bool removeRecursively (const QString &dir, bool self=true)
TTK_MODULE_EXPORT QString getOpenFileDialog (QWidget *obj, const QString &title, const QString &filter)
TTK_MODULE_EXPORT QString getOpenFileDialog (QWidget *obj, const QString &filter)
TTK_MODULE_EXPORT QString getOpenFileDialog (QWidget *obj)
TTK_MODULE_EXPORT QString getOpenDirectoryDialog (QWidget *obj)
TTK_MODULE_EXPORT QStringList getOpenFilesDialog (QWidget *obj, const QString &title, const QString &filter)
TTK_MODULE_EXPORT QStringList getOpenFilesDialog (QWidget *obj, const QString &filter)
TTK_MODULE_EXPORT QStringList getOpenFilesDialog (QWidget *obj)
TTK_MODULE_EXPORT QString getSaveFileDialog (QWidget *obj, const QString &title, const QString &filter)
TTK_MODULE_EXPORT QString getSaveFileDialog (QWidget *obj, const QString &filter)
TTK_MODULE_EXPORT QString getSaveFileDialog (QWidget *obj)
Function Documentation
void MusicUtils::File::checkCacheSize (quint64 cacheSize, bool disabled, const QString & path)
Check given dir size is bigger than given size.
Definition at line 29 of file musicfileutils.cpp.
References dirSize().
Referenced by MusicRunTimeManager::run().
quint64 MusicUtils::File::dirSize (const QString & dirName)
Get given dir size.
Definition at line 6 of file musicfileutils.cpp.
Referenced by checkCacheSize().
QFileInfoList MusicUtils::File::getFileListByDir (const QString & dpath, bool recursively)
Get all files in given dir.
Definition at line 50 of file musicfileutils.cpp.
Referenced by MusicReplayGainWidget::addFilesButtonClicked(), getFileListByDir(), MusicConsoleModule::init(), MusicTransformWidget::initInputPath(), MusicApplication::musicImportSongsOnlyDir(), MusicLocalSongsManagerThread::run(), and MusicCloudManagerTableWidget::uploadFileDirToServer().
QFileInfoList MusicUtils::File::getFileListByDir (const QString & dpath, const QStringList & filter, bool recursively)
Get all files in given dir.
Definition at line 55 of file musicfileutils.cpp.
References getFileListByDir().
QString MusicUtils::File::getOpenDirectoryDialog (QWidget * obj)
Get open dir dialog.
Definition at line 142 of file musicfileutils.cpp.
Referenced by MusicReplayGainWidget::addFilesButtonClicked(), MusicSettingWidget::downloadDirSelected(), MusicDownloadWidget::downloadDirSelected(), MusicLocalSongsManagerWidget::filterIndexCustChanged(), MusicTransformWidget::initInputPath(), MusicTransformWidget::initOutputPath(), MusicApplication::musicImportSongsOnlyDir(), and MusicCloudManagerTableWidget::uploadFileDirToServer().
QString MusicUtils::File::getOpenFileDialog (QWidget * obj, const QString & title, const QString & filter)
Get open file dialog.
Definition at line 127 of file musicfileutils.cpp.
Referenced by MusicLrcLocalLinkWidget::findInLocalFile(), getOpenFileDialog(), ToolsSkin::imageClicked(), MusicSongRingtoneMaker::initInputPath(), MusicTransformWidget::initInputPath(), MusicLrcPosterWidget::openButtonClicked(), MusicUserRecordWidget::openFileButtonClickedS(), MusicFileInformationWidget::openImageFileDir(), ToolsSkin::readClicked(), MusicLrcArtPhotoUploadWidget::selectButtonClicked(), and MusicBackgroundSkinDialog::showCustomSkinDialog().
QString MusicUtils::File::getOpenFileDialog (QWidget * obj, const QString & filter)
Get open file dialog.
Definition at line 132 of file musicfileutils.cpp.
References getOpenFileDialog().
QString MusicUtils::File::getOpenFileDialog (QWidget * obj)
Get open file dialog.
Definition at line 137 of file musicfileutils.cpp.
References getOpenFileDialog().
QStringList MusicUtils::File::getOpenFilesDialog (QWidget * obj, const QString & title, const QString & filter)
Get open files dialog.
Definition at line 147 of file musicfileutils.cpp.
Referenced by getOpenFilesDialog(), and MusicCloudManagerTableWidget::uploadFilesToServer().
QStringList MusicUtils::File::getOpenFilesDialog (QWidget * obj, const QString & filter)
Get open files dialog.
Definition at line 152 of file musicfileutils.cpp.
References getOpenFilesDialog().
QStringList MusicUtils::File::getOpenFilesDialog (QWidget * obj)
Get open files dialog.
Definition at line 157 of file musicfileutils.cpp.
References getOpenFilesDialog().
QString MusicUtils::File::getSaveFileDialog (QWidget * obj, const QString & title, const QString & filter)
Get save file dialog.
Definition at line 162 of file musicfileutils.cpp.
Referenced by MusicLrcFloatPhotoItem::exportArtPixmap(), getSaveFileDialog(), MusicSongRingtoneMaker::initOutputPath(), MusicApplication::musicExportSongsItemList(), MusicSoundKMicroWidget::playFinished(), MusicFileInformationWidget::saveAlbumPicture(), MusicLrcPosterWidget::saveButtonClicked(), and ToolsSkin::writeClicked().
QString MusicUtils::File::getSaveFileDialog (QWidget * obj, const QString & filter)
Get save file dialog.
Definition at line 167 of file musicfileutils.cpp.
References getSaveFileDialog().
QString MusicUtils::File::getSaveFileDialog (QWidget * obj)
Get save file dialog.
Definition at line 172 of file musicfileutils.cpp.
References getSaveFileDialog().
bool MusicUtils::File::removeRecursively (const QString & dir, bool self = true)
Dir remove recursively.
Definition at line 76 of file musicfileutils.cpp.
Referenced by MusicApplicationModule::cleanUp(), and MusicSettingWidget::downloadCachedClean().