TTKMusicplayer: MusicRunTimeManager Class Reference
MusicRunTimeManager Class Reference
The class of the app run time needed.
#include <musicruntimemanager.h>
Public Member Functions
MusicRunTimeManager ()
void run () const
QString translator () const
Static Public Member Functions
static QString getClassName ()
Detailed Description
The class of the app run time needed.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicruntimemanager.h.
Constructor & Destructor Documentation
MusicRunTimeManager::MusicRunTimeManager ()
Object contsructor.
Definition at line 12 of file musicruntimemanager.cpp.
Member Function Documentation
QString MusicRunTimeManager::getClassName () static
Get class object name.
Definition at line 17 of file musicruntimemanager.cpp.
void MusicRunTimeManager::run () const
Run.
Definition at line 22 of file musicruntimemanager.cpp.
References MusicUtils::Core::checkCacheSize(), MusicSettingManager::CloseNetWorkChoiced, MusicSettingManager::DownloadCacheLimitChoiced, MusicSettingManager::DownloadCacheSizeChoiced, MusicSettingManager::DownloadMusicPathDirChoiced, M_LOGGER_INFO, M_NETWORK_PTR, M_SETTING_PTR, MH_MB2B, MusicUtils::QMMP::midTransferFile(), MusicSysConfigManager::readSysLoadConfig(), MusicSysConfigManager::readXMLConfig(), and MusicUtils::Codec::setLocalCodec().
Referenced by main().
QString MusicRunTimeManager::translator () const
Get translator path.
Definition at line 58 of file musicruntimemanager.cpp.
References MusicSettingManager::CurrentLanIndexChoiced, MusicUtils::Core::getLanguageName(), and M_SETTING_PTR.
Referenced by main().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicruntimemanager.h
TTKModule/TTKCore/musicCoreKits/musicruntimemanager.cpp