TTKMusicPlayer: TTKCommon/TTKLibrary/ttkoptional.h File Reference
ttkoptional.h File Reference
#include "ttksmartptr.h"
Classes
struct TTKOptional< T >
The class of the optional module.
Namespaces
std
Typedefs
template<typename T >
using std::optional = TTKOptional< T >
Functions
template<typename T >
bool operator== (const TTKOptional< T > &v, const T &other)
template<typename T >
bool operator== (const T &other, const TTKOptional< T > &v)
template<typename T >
bool operator!= (const TTKOptional< T > &v, const T &other)
template<typename T >
bool operator!= (const T &other, const TTKOptional< T > &v)
Function Documentation
template<typename T > bool operator!= (const TTKOptional< T > & v, const T & other) inline
Definition at line 156 of file ttkoptional.h.
References operator==().
template<typename T > bool operator!= (const T & other, const TTKOptional< T > & v) inline
Definition at line 162 of file ttkoptional.h.
References operator==().
template<typename T > bool operator== (const TTKOptional< T > & v, const T & other) inline
Definition at line 144 of file ttkoptional.h.
References TTKOptional< T >::has_value().
Referenced by operator!=().
template<typename T > bool operator== (const T & other, const TTKOptional< T > & v) inline
Definition at line 150 of file ttkoptional.h.
References TTKOptional< T >::has_value().