TTKMusicplayer: MusicDownloadAbstractTableWidget Class Reference
MusicDownloadAbstractTableWidget Class Reference abstract
The class of the download abstract table widget.
#include <musicdownloadabstracttablewidget.h>
Public Slots
void musicPlay ()
virtual void setDeleteItemAt () override
virtual void listCellClicked (int row, int column) override
void listCellDoubleClicked (int row, int column)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Public Slots inherited from MusicSongsListAbstractTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
void musicSongMovieFoundPy ()
void musicSimilarFoundWidgetPy ()
void musicSongSharedWidgetPy ()
void musicSongKMicroWidgetPy ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void addSongToPlay (const QStringList &list)
void updateItemTitle (int index)
Signals inherited from MusicSongsListAbstractTableWidget
void isCurrentIndex (bool &state)
Public Member Functions
MusicDownloadAbstractTableWidget (QWidget *parent=nullptr)
virtual ~MusicDownloadAbstractTableWidget ()
virtual void updateSongsFileName (const MusicSongs &songs) override
Public Member Functions inherited from MusicSongsListAbstractTableWidget
MusicSongsListAbstractTableWidget (QWidget *parent=nullptr)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void selectRow (int index)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
virtual ~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractTableWidget ()
void clear ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void createItem (int index, const MusicSong &record)=0
Protected Member Functions inherited from MusicSongsListAbstractTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
MIntList getMultiIndexSet ()
Protected Attributes
MusicProgressBarDelegate * m_delegate
MusicObject::RecordType m_type
Protected Attributes inherited from MusicSongsListAbstractTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_firstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the download abstract table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicdownloadabstracttablewidget.h.
Constructor & Destructor Documentation
MusicDownloadAbstractTableWidget::MusicDownloadAbstractTableWidget (QWidget * parent = nullptr) explicit
Definition at line 9 of file musicdownloadabstracttablewidget.cpp.
References listCellDoubleClicked(), M_CONNECTION_PTR, and m_delegate.
MusicDownloadAbstractTableWidget::~MusicDownloadAbstractTableWidget () virtual
Definition at line 20 of file musicdownloadabstracttablewidget.cpp.
References MusicAbstractTableWidget::clear(), M_CONNECTION_PTR, m_delegate, MusicSongsListAbstractTableWidget::m_musicSongs, m_type, and MusicDownloadRecordConfigManager::writeDownloadData().
Member Function Documentation
void MusicDownloadAbstractTableWidget::addSongToPlay (const QStringList & list) signal
Add current selected song to play lists.
Referenced by musicPlay().
void MusicDownloadAbstractTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicCloudUploadTableWidget.
Definition at line 130 of file musicdownloadabstracttablewidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicUIObject::MMenuStyle02, MusicSongsListAbstractTableWidget::musicAlbumFoundWidget(), MusicSongsListAbstractTableWidget::musicFileInformation(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicPlayClicked(), MusicSongsListAbstractTableWidget::musicSongDownload(), MusicSongsListAbstractTableWidget::setDeleteItemAll(), and setDeleteItemAt().
void MusicDownloadAbstractTableWidget::createDownloadItem (const QString & name, qint64 time) slot
Create download item from download name and total time.
Definition at line 113 of file musicdownloadabstracttablewidget.cpp.
References createItem(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicSongsListAbstractTableWidget::m_parentToolIndex, MusicUtils::Core::musicPrefix(), MusicSong::setMusicAddTimeStr(), MusicSong::setMusicName(), MusicSong::setMusicPath(), MusicSong::setMusicSizeStr(), and updateItemTitle().
virtual void MusicDownloadAbstractTableWidget::createItem (int index, const MusicSong & record) protected pure virtual
Create item by index and name and size and time.
Implemented in MusicCloudUploadTableWidget, MusicCloudDownloadTableWidget, and MusicDownloadRecordTableWidget.
Referenced by createDownloadItem(), and updateSongsFileName().
void MusicDownloadAbstractTableWidget::downloadProgressChanged (float percent, const QString & total, qint64 time) slot
Update download percent\ total time and current time progress.
Definition at line 97 of file musicdownloadabstracttablewidget.cpp.
References MUSIC_PROCS_ROLE, and MUSIC_TIMES_ROLE.
void MusicDownloadAbstractTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 83 of file musicdownloadabstracttablewidget.cpp.
void MusicDownloadAbstractTableWidget::listCellDoubleClicked (int row, int column) slot
Table widget list cell double click.
Definition at line 89 of file musicdownloadabstracttablewidget.cpp.
References musicPlay().
Referenced by MusicDownloadAbstractTableWidget().
void MusicDownloadAbstractTableWidget::musicPlay () slot
Add selected music song path to list.
Definition at line 50 of file musicdownloadabstracttablewidget.cpp.
References addSongToPlay().
Referenced by listCellDoubleClicked().
void MusicDownloadAbstractTableWidget::setDeleteItemAt () override virtual slot
Delete item from list at current row.
Definition at line 61 of file musicdownloadabstracttablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicMessageBox::exec(), MusicAbstractTableWidget::getMultiIndexSet(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicSongsListAbstractTableWidget::m_parentToolIndex, MusicMessageBox::setText(), and updateItemTitle().
Referenced by contextMenuEvent(), and MusicCloudUploadTableWidget::contextMenuEvent().
void MusicDownloadAbstractTableWidget::updateItemTitle (int index) signal
Update item title.
Referenced by createDownloadItem(), and setDeleteItemAt().
void MusicDownloadAbstractTableWidget::updateSongsFileName (const MusicSongs & songs) override virtual
Read all config from file and insert items.
Reimplemented from MusicSongsListAbstractTableWidget.
Definition at line 30 of file musicdownloadabstracttablewidget.cpp.
References createItem(), MusicSong::getMusicAddTimeStr(), M_DOWNLOAD_MANAGER_PTR, MusicSongsListAbstractTableWidget::m_musicSongs, m_type, MusicDownloadRecordConfigManager::readConfig(), and MusicDownloadRecordConfigManager::readDownloadData().
Member Data Documentation
MusicProgressBarDelegate* MusicDownloadAbstractTableWidget::m_delegate protected
Definition at line 90 of file musicdownloadabstracttablewidget.h.
Referenced by MusicDownloadAbstractTableWidget(), MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget(), and ~MusicDownloadAbstractTableWidget().
MusicObject::RecordType MusicDownloadAbstractTableWidget::m_type protected
Definition at line 91 of file musicdownloadabstracttablewidget.h.
Referenced by MusicCloudUploadTableWidget::MusicCloudUploadTableWidget(), MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget(), updateSongsFileName(), and ~MusicDownloadAbstractTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicdownloadabstracttablewidget.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicdownloadabstracttablewidget.cpp