TTKMusicPlayer: MusicAbstractSongsListTableWidget Class Reference
MusicAbstractSongsListTableWidget Class Reference
The class of the songs list abstract table widget.
#include <musicabstractsongslisttablewidget.h>
Public Slots
virtual void removeItemAt ()
void playClicked ()
void clearItems ()
void openFileDir ()
void showFileInformation ()
void showMovieQueryWidget ()
void showAlbumQueryWidget ()
void showSimilarQueryWidget ()
void showSongSharedWidget ()
void showDownloadWidget ()
void showPlayedMovieQueryWidget ()
void showPlayedSimilarQueryWidget ()
void showPlayedSongSharedWidget ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void isCurrentPlaylistRow (bool &state)
Public Member Functions
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
MusicAbstractSongsListTableWidget (int index, QWidget *parent=nullptr)
~MusicAbstractSongsListTableWidget ()
virtual void setSongsList (MusicSongList *songs)
virtual void updateSongsList (const MusicSongList &songs)
virtual void selectRow (int index)
int totalHeight () const
void setPlaylistRow (int index)
void setPlayRowIndex (int index)
int playRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Protected Member Functions
void createMoreMenu (QMenu *menu)
QString currentSongPath () const
QString songPath (int index) const
QString currentSongName () const
QString songName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes
int m_playlistRow
int m_playRowIndex
MusicSongList * m_songs
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_initialized
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the songs list abstract table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicabstractsongslisttablewidget.h.
Constructor & Destructor Documentation
MusicAbstractSongsListTableWidget::MusicAbstractSongsListTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 10 of file musicabstractsongslisttablewidget.cpp.
MusicAbstractSongsListTableWidget::MusicAbstractSongsListTableWidget (int index, QWidget * parent = nullptr) explicit
Definition at line 16 of file musicabstractsongslisttablewidget.cpp.
MusicAbstractSongsListTableWidget::~MusicAbstractSongsListTableWidget ()
Object destructor.
Definition at line 25 of file musicabstractsongslisttablewidget.cpp.
Member Function Documentation
void MusicAbstractSongsListTableWidget::clearItems () slot
Remove all items from list.
Definition at line 76 of file musicabstractsongslisttablewidget.cpp.
References MusicApplication::instance(), isCurrentPlaylistRow(), MusicApplication::playIndexBy(), removeItemAt(), and TTK_NORMAL_LEVEL.
Referenced by MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicCloudUploadTableWidget::contextMenuEvent(), MusicSongsListPlayTableWidget::contextMenuEvent(), and MusicSongsContainerWidget::deleteAllItems().
void MusicAbstractSongsListTableWidget::createMoreMenu (QMenu * menu) protected
Create more menu information.
Definition at line 208 of file musicabstractsongslisttablewidget.cpp.
References TTK::UI::MenuStyle02, showSimilarQueryWidget(), and showSongSharedWidget().
Referenced by MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), MusicSongsListPlayTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::itemCellClicked(), and MusicSongsListPlayTableWidget::itemCellClicked().
QString MusicAbstractSongsListTableWidget::currentSongName () const protected
Get current song name.
Definition at line 225 of file musicabstractsongslisttablewidget.cpp.
References TTKAbstractTableWidget::isValid(), and songName().
Referenced by MusicSongsListPlayTableWidget::contextMenuEvent(), showAlbumQueryWidget(), showDownloadWidget(), showMovieQueryWidget(), showSimilarQueryWidget(), and showSongSharedWidget().
QString MusicAbstractSongsListTableWidget::currentSongPath () const protected
Get current song path.
Definition at line 215 of file musicabstractsongslisttablewidget.cpp.
References TTKAbstractTableWidget::isValid(), and songPath().
Referenced by MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicCloudUploadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), MusicSongsListPlayTableWidget::contextMenuEvent(), and showFileInformation().
void MusicAbstractSongsListTableWidget::isCurrentPlaylistRow (bool & state) signal
Check is current play list row.
Referenced by clearItems(), MusicSongsListPlayTableWidget::showTimeOut(), and MusicSongsListPlayTableWidget::startToDrag().
void MusicAbstractSongsListTableWidget::openFileDir () slot
Open the music at local path.
Definition at line 90 of file musicabstractsongslisttablewidget.cpp.
References TTKAbstractTableWidget::isValid(), m_songs, TTK::Url::openUrl(), and MusicToastLabel::popup().
Referenced by MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicCloudUploadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), and MusicSongsListPlayTableWidget::contextMenuEvent().
void MusicAbstractSongsListTableWidget::playClicked () slot
Music item has been clicked.
Definition at line 66 of file musicabstractsongslisttablewidget.cpp.
References TTKAbstractTableWidget::isValid().
Referenced by MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), and MusicSongsListPlayTableWidget::contextMenuEvent().
int MusicAbstractSongsListTableWidget::playRowIndex () const inline
Get the current play row.
Definition at line 73 of file musicabstractsongslisttablewidget.h.
Referenced by MusicPlayedListPopWidget::insert(), and MusicPlayedListPopWidget::removeItemAt().
void MusicAbstractSongsListTableWidget::removeItemAt () virtual slot
Remove item from list at current row.
Definition at line 61 of file musicabstractsongslisttablewidget.cpp.
Referenced by clearItems().
void MusicAbstractSongsListTableWidget::selectRow (int index) virtual
Select the current play row by given index.
Reimplemented in MusicSongsListPlayTableWidget, and MusicSongsListPlayedTableWidget.
Definition at line 41 of file musicabstractsongslisttablewidget.cpp.
Referenced by MusicSongsListPlayedTableWidget::selectRow(), and MusicSongsListPlayTableWidget::selectRow().
void MusicAbstractSongsListTableWidget::setPlaylistRow (int index)
Set playlist row index.
Definition at line 56 of file musicabstractsongslisttablewidget.cpp.
References m_playlistRow.
Referenced by MusicCloudToolBoxWidget::createWidgetItem(), MusicDownloadToolBoxWidget::createWidgetItem(), and MusicSongsContainerWidget::createWidgetItem().
void MusicAbstractSongsListTableWidget::setPlayRowIndex (int index) inline
Get the current play row.
Definition at line 69 of file musicabstractsongslisttablewidget.h.
Referenced by MusicPlayedListPopWidget::clearPlaylist(), MusicPlayedListPopWidget::insert(), and MusicPlayedListPopWidget::remove().
void MusicAbstractSongsListTableWidget::setSongsList (MusicSongList * songs) virtual
Set songs files.
Definition at line 30 of file musicabstractsongslisttablewidget.cpp.
References m_songs, and updateSongsList().
Referenced by MusicCloudToolBoxWidget::createWidgetItem(), MusicDownloadToolBoxWidget::createWidgetItem(), MusicSongsContainerWidget::createWidgetItem(), MusicPlaylistBackupWidget::currentItemChanged(), MusicPlayedListPopWidget::initialize(), and MusicSongsContainerWidget::songListSortBy().
void MusicAbstractSongsListTableWidget::showAlbumQueryWidget () slot
Open music album query widget.
Definition at line 126 of file musicabstractsongslisttablewidget.cpp.
References currentSongName(), MusicRightAreaWidget::instance(), TTKAbstractTableWidget::isValid(), and MusicRightAreaWidget::showAlbumFound().
Referenced by MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), and MusicSongsListPlayTableWidget::contextMenuEvent().
void MusicAbstractSongsListTableWidget::showDownloadWidget () slot
Open music song download widget.
Definition at line 161 of file musicabstractsongslisttablewidget.cpp.
References currentSongName(), MusicDownloadWidget::initialize(), TTKAbstractTableWidget::isValid(), and MusicAbstractMoveWidget::show().
Referenced by MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicSongsListPlayTableWidget::contextMenuEvent(), and MusicSongsListPlayedTableWidget::itemCellClicked().
void MusicAbstractSongsListTableWidget::showFileInformation () slot
Open music file information widget.
Definition at line 104 of file musicabstractsongslisttablewidget.cpp.
References currentSongPath(), MusicAbstractMoveDialog::exec(), MusicFileInformationWidget::initialize(), and TTKAbstractTableWidget::isValid().
Referenced by MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicCloudUploadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), and MusicSongsListPlayTableWidget::contextMenuEvent().
void MusicAbstractSongsListTableWidget::showMovieQueryWidget () slot
To search song mv by song name.
Definition at line 116 of file musicabstractsongslisttablewidget.cpp.
References currentSongName(), MusicRightAreaWidget::instance(), TTKAbstractTableWidget::isValid(), and MusicRightAreaWidget::showVideoSearchedFound().
Referenced by MusicSongsListPlayTableWidget::contextMenuEvent(), and MusicSongsListPlayTableWidget::itemCellClicked().
void MusicAbstractSongsListTableWidget::showPlayedMovieQueryWidget () slot
To search song mv by song name in play widget.
Definition at line 173 of file musicabstractsongslisttablewidget.cpp.
References MusicRightAreaWidget::instance(), TTKAbstractTableWidget::isValid(), m_playRowIndex, MusicRightAreaWidget::showVideoSearchedFound(), and songName().
void MusicAbstractSongsListTableWidget::showPlayedSimilarQueryWidget () slot
Open music similar query widget in play widget.
Definition at line 183 of file musicabstractsongslisttablewidget.cpp.
References MusicRightAreaWidget::instance(), TTKAbstractTableWidget::isValid(), m_playRowIndex, MusicRightAreaWidget::showSimilarFound(), and songName().
void MusicAbstractSongsListTableWidget::showPlayedSongSharedWidget () slot
Open music song shared widget in play widget.
Definition at line 193 of file musicabstractsongslisttablewidget.cpp.
References MusicAbstractMoveDialog::exec(), MusicSongSharingWidget::initialize(), TTKAbstractTableWidget::isValid(), MusicSongSharingWidget::Item::m_name, m_playRowIndex, MusicSongSharingWidget::Song, and songName().
void MusicAbstractSongsListTableWidget::showSimilarQueryWidget () slot
Open music similar query widget.
Definition at line 136 of file musicabstractsongslisttablewidget.cpp.
References currentSongName(), MusicRightAreaWidget::instance(), TTKAbstractTableWidget::isValid(), and MusicRightAreaWidget::showSimilarFound().
Referenced by createMoreMenu().
void MusicAbstractSongsListTableWidget::showSongSharedWidget () slot
Open music song shared widget.
Definition at line 146 of file musicabstractsongslisttablewidget.cpp.
References currentSongName(), MusicAbstractMoveDialog::exec(), MusicSongSharingWidget::initialize(), TTKAbstractTableWidget::isValid(), MusicSongSharingWidget::Item::m_name, and MusicSongSharingWidget::Song.
Referenced by createMoreMenu().
QString MusicAbstractSongsListTableWidget::songName (int index) const protected
Get song name.
Definition at line 230 of file musicabstractsongslisttablewidget.cpp.
References m_songs.
Referenced by MusicSongsListPlayTableWidget::contextMenuEvent(), currentSongName(), showPlayedMovieQueryWidget(), showPlayedSimilarQueryWidget(), and showPlayedSongSharedWidget().
QString MusicAbstractSongsListTableWidget::songPath (int index) const protected
Get song path.
Definition at line 220 of file musicabstractsongslisttablewidget.cpp.
References m_songs.
Referenced by currentSongPath().
int MusicAbstractSongsListTableWidget::totalHeight () const
Get all rows height.
Definition at line 46 of file musicabstractsongslisttablewidget.cpp.
Referenced by MusicCloudDownloadTableWidget::addCellItem(), MusicDownloadRecordTableWidget::addCellItem(), MusicCloudUploadTableWidget::addCellItem(), MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayTableWidget::adjustPlayWidgetRow(), MusicAbstractDownloadTableWidget::removeItemAt(), MusicSongsListPlayedTableWidget::removeItemAt(), MusicSongsListPlayTableWidget::removeItemAt(), MusicSongsListPlayedTableWidget::selectRow(), MusicSongsListPlayTableWidget::selectRow(), MusicSongsListPlayTableWidget::updateSearchFileName(), MusicSongsListPlayedTableWidget::updateSongsList(), and MusicSongsListPlayTableWidget::updateSongsList().
void MusicAbstractSongsListTableWidget::updateSongsList (const MusicSongList & songs) virtual
Update songs files in table.
Reimplemented in MusicSongsListPlayTableWidget, MusicAbstractDownloadTableWidget, MusicSongsListPlayedTableWidget, and MusicPlaylistBackupTableWidget.
Definition at line 36 of file musicabstractsongslisttablewidget.cpp.
Referenced by MusicSongsContainerWidget::addSongBufferToPlaylist(), MusicSongsContainerWidget::importSongsByPath(), MusicSongsContainerWidget::importSongsByUrl(), MusicSongsContainerWidget::searchResultChanged(), setSongsList(), and MusicSongsContainerWidget::updateSongItem().
Member Data Documentation
int MusicAbstractSongsListTableWidget::m_playlistRow protected
Definition at line 157 of file musicabstractsongslisttablewidget.h.
Referenced by MusicSongsListPlayTableWidget::addToPlayedList(), MusicSongsListPlayTableWidget::addToPlayLater(), MusicAbstractDownloadTableWidget::createDownloadItem(), MusicSongsListPlayTableWidget::createUploadFileModule(), MusicAbstractDownloadTableWidget::removeItemAt(), setPlaylistRow(), MusicSongsListPlayTableWidget::showTimeOut(), and MusicSongsListPlayTableWidget::songListSortBy().
int MusicAbstractSongsListTableWidget::m_playRowIndex protected
Definition at line 158 of file musicabstractsongslisttablewidget.h.
Referenced by MusicSongsListPlayTableWidget::addToPlayLater(), MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayedTableWidget::itemCellClicked(), MusicSongsListPlayTableWidget::itemCellClicked(), MusicSongsListPlayTableWidget::itemRenameFinished(), MusicSongsListPlayedTableWidget::removeItemAt(), MusicSongsListPlayTableWidget::removeItemAt(), MusicSongsListPlayedTableWidget::removeItems(), MusicSongsListPlayTableWidget::removeItems(), MusicSongsListPlayedTableWidget::selectPlayedRow(), MusicSongsListPlayedTableWidget::selectRow(), MusicSongsListPlayTableWidget::selectRow(), MusicSongsListPlayTableWidget::setChangSongName(), showPlayedMovieQueryWidget(), showPlayedSimilarQueryWidget(), showPlayedSongSharedWidget(), and MusicSongsListPlayTableWidget::startToDrag().
MusicSongList* MusicAbstractSongsListTableWidget::m_songs protected
Definition at line 159 of file musicabstractsongslisttablewidget.h.
Referenced by MusicMobileSongsTableWidget::addCellItems(), MusicLocalManagerSongsTableWidget::addCellItems(), MusicSongsListPlayTableWidget::addToPlayedList(), MusicSongsListPlayTableWidget::addToPlayLater(), MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayTableWidget::adjustPlayWidgetRow(), MusicPlaylistBackupTableWidget::contextMenuEvent(), MusicMobileSongsTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::contextMenuEvent(), MusicCloudUploadTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicLocalManagerSongsTableWidget::contextMenuEvent(), MusicSongsListPlayTableWidget::contextMenuEvent(), MusicAbstractDownloadTableWidget::createDownloadItem(), MusicSongsListPlayTableWidget::createUploadFileModule(), MusicSongsListPlayedTableWidget::itemCellEntered(), MusicSongsListPlayTableWidget::itemCellEntered(), MusicPlaylistBackupTableWidget::itemDoubleClicked(), MusicAbstractDownloadTableWidget::itemDoubleClicked(), MusicLocalManagerSongsTableWidget::MusicLocalManagerSongsTableWidget(), MusicMobileSongsTableWidget::MusicMobileSongsTableWidget(), openFileDir(), MusicAbstractDownloadTableWidget::removeItemAt(), MusicSongsListPlayedTableWidget::removeItemAt(), MusicMobileSongsTableWidget::removeItems(), MusicLocalManagerSongsTableWidget::removeItems(), MusicSongsListPlayedTableWidget::selectRow(), MusicSongsListPlayTableWidget::selectRow(), MusicSongsListPlayTableWidget::setChangSongName(), setSongsList(), MusicSongsListPlayTableWidget::showTimeOut(), songName(), songPath(), MusicSongsListPlayTableWidget::updateSearchFileName(), MusicAbstractDownloadTableWidget::updateSongsList(), MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget(), MusicLocalManagerSongsTableWidget::~MusicLocalManagerSongsTableWidget(), and MusicMobileSongsTableWidget::~MusicMobileSongsTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicabstractsongslisttablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicabstractsongslisttablewidget.cpp