TTKMusicplayer: MusicDownloadBatchTableItem Class Reference
MusicDownloadBatchTableItem Class Reference
The class of the download batch table item.
#include <musicdownloadbatchwidget.h>
Public Slots
void currentQualityChanged (int index)
Public Member Functions
MusicDownloadBatchTableItem (QWidget *parent=nullptr)
~MusicDownloadBatchTableItem ()
void createItem (const MusicObject::MusicSongInformation &info, MusicAbstractQueryRequest::QueryType type)
void startToDownload ()
void setCurrentQuality (int index)
Protected Member Functions
void startToDownloadMusic ()
void startToDownloadMovie ()
Protected Attributes
QObject * m_supperClass
QComboBox * m_qulity
MusicObject::MusicSongInformation m_songInfo
QLabel * m_songName
QLabel * m_singer
QLabel * m_information
MusicAbstractQueryRequest::QueryType m_queryType
Detailed Description
The class of the download batch table item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicdownloadbatchwidget.h.
Constructor & Destructor Documentation
MusicDownloadBatchTableItem::MusicDownloadBatchTableItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicdownloadbatchwidget.cpp.
References MusicUtils::Widget::generateComboBoxFormat(), ITEM_ROW_HEIGHT_S, MusicUIObject::MQSSComboBoxStyle02, MusicUIObject::MQSSItemView01, and MusicAbstractQueryRequest::MusicQuery.
MusicDownloadBatchTableItem::~MusicDownloadBatchTableItem ()
Definition at line 32 of file musicdownloadbatchwidget.cpp.
References m_information, m_qulity, m_singer, and m_songName.
Member Function Documentation
void MusicDownloadBatchTableItem::createItem (const MusicObject::MusicSongInformation & info, MusicAbstractQueryRequest::QueryType type)
Create current item by song info.
sd
hd
sq
cd
Definition at line 40 of file musicdownloadbatchwidget.cpp.
References DEFAULT_NORMAL_LEVEL, MusicUtils::Widget::elidedText(), m_information, m_queryType, m_qulity, m_singer, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, m_songInfo, m_songName, MusicObject::MusicSongInformation::m_songName, MB_1000, MB_128, MB_192, MB_250, MB_320, MB_500, MB_750, MusicAbstractQueryRequest::MovieQuery, and MusicAbstractQueryRequest::MusicQuery.
Referenced by MusicDownloadBatchTableWidget::createItem().
void MusicDownloadBatchTableItem::currentQualityChanged (int index) slot
Table widget item cell click.
sd
hd
sq
cd
Definition at line 150 of file musicdownloadbatchwidget.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, m_information, m_queryType, m_qulity, MusicObject::MusicSongAttribute::m_size, MB_1000, MB_128, MB_192, MB_250, MB_320, MB_500, MB_750, MusicAbstractQueryRequest::MovieQuery, and MusicAbstractQueryRequest::MusicQuery.
void MusicDownloadBatchTableItem::setCurrentQuality (int index)
Set current quality by index.
Definition at line 107 of file musicdownloadbatchwidget.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, m_queryType, m_qulity, MB_1000, MB_128, MB_192, MB_250, MB_320, MB_500, MB_750, MusicAbstractQueryRequest::MovieQuery, and MusicAbstractQueryRequest::MusicQuery.
void MusicDownloadBatchTableItem::startToDownload ()
Start to download data.
Definition at line 90 of file musicdownloadbatchwidget.cpp.
References G_NETWORK_PTR, m_queryType, m_qulity, MusicAbstractQueryRequest::MovieQuery, MusicAbstractQueryRequest::MusicQuery, startToDownloadMovie(), and startToDownloadMusic().
void MusicDownloadBatchTableItem::startToDownloadMovie () protected
Start to download movie data.
Definition at line 236 of file musicdownloadbatchwidget.cpp.
References MusicObject::DownloadVideo, MusicObject::MusicSongAttribute::m_format, m_qulity, m_singer, m_songName, MusicObject::MusicSongAttribute::m_url, MOVIE_DIR_FULL, and MusicDownloadDataRequest::startToDownload().
Referenced by startToDownload().
void MusicDownloadBatchTableItem::startToDownloadMusic () protected
Start to download music data.
Definition at line 180 of file musicdownloadbatchwidget.cpp.
References MusicObject::DownloadMusic, MusicSettingManager::DownloadMusicDirPath, G_SETTING_PTR, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongAttribute::m_format, m_qulity, m_singer, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_smallPicUrl, m_songInfo, m_songName, MusicObject::MusicSongInformation::m_songName, m_supperClass, MusicObject::MusicSongInformation::m_trackNumber, MusicObject::MusicSongAttribute::m_url, MusicObject::MusicSongInformation::m_year, MusicDownloadRecordConfigManager::readConfig(), MusicDownloadRecordConfigManager::readDownloadData(), MusicObject::RecordNormalDownload, MusicSongMeta::setAlbum(), MusicSongMeta::setArtist(), MusicSongMeta::setComment(), MusicSong::setMusicAddTimeStr(), MusicSong::setMusicName(), MusicSong::setMusicPath(), MusicSong::setMusicSizeStr(), MusicDownloadDataRequest::setRecordType(), MusicDownloadTagDataRequest::setSongMeta(), MusicSongMeta::setTitle(), MusicSongMeta::setTrackNum(), MusicSongMeta::setYear(), MusicDownloadTagDataRequest::startToDownload(), and MusicDownloadRecordConfigManager::writeDownloadData().
Referenced by startToDownload().
Member Data Documentation
QLabel * MusicDownloadBatchTableItem::m_information protected
Definition at line 76 of file musicdownloadbatchwidget.h.
Referenced by createItem(), currentQualityChanged(), and ~MusicDownloadBatchTableItem().
MusicAbstractQueryRequest::QueryType MusicDownloadBatchTableItem::m_queryType protected
Definition at line 77 of file musicdownloadbatchwidget.h.
Referenced by createItem(), currentQualityChanged(), setCurrentQuality(), and startToDownload().
QComboBox* MusicDownloadBatchTableItem::m_qulity protected
Definition at line 74 of file musicdownloadbatchwidget.h.
Referenced by createItem(), currentQualityChanged(), setCurrentQuality(), startToDownload(), startToDownloadMovie(), startToDownloadMusic(), and ~MusicDownloadBatchTableItem().
QLabel * MusicDownloadBatchTableItem::m_singer protected
Definition at line 76 of file musicdownloadbatchwidget.h.
Referenced by createItem(), startToDownloadMovie(), startToDownloadMusic(), and ~MusicDownloadBatchTableItem().
MusicObject::MusicSongInformation MusicDownloadBatchTableItem::m_songInfo protected
Definition at line 75 of file musicdownloadbatchwidget.h.
Referenced by createItem(), and startToDownloadMusic().
QLabel* MusicDownloadBatchTableItem::m_songName protected
Definition at line 76 of file musicdownloadbatchwidget.h.
Referenced by createItem(), startToDownloadMovie(), startToDownloadMusic(), and ~MusicDownloadBatchTableItem().
QObject* MusicDownloadBatchTableItem::m_supperClass protected
Definition at line 73 of file musicdownloadbatchwidget.h.
Referenced by startToDownloadMusic().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadbatchwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadbatchwidget.cpp