TTKMusicPlayer: MusicBDInterface Namespace Reference
MusicBDInterface Namespace Reference
The namespace of the baidu request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request)
Detailed Description
The namespace of the baidu request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void MusicBDInterface::makeRequestRawHeader (QNetworkRequest * request)
Make request query data.
Definition at line 4 of file musicbdqueryinterface.cpp.
References ALG_UA_KEY, BD_UA_URL, MusicUtils::Algorithm::mdII(), and MusicObject::setSslConfiguration().
Referenced by MusicBDQueryLearnRequest::parseFromLrcProperty(), MusicBDQueryLearnRequest::parseFromSongProperty(), and MusicBDQueryLearnRequest::startToSearch().