TTKMusicplayer: MusicWebMusicRadioListView Class Reference
MusicWebMusicRadioListView Class Reference
The class of the web music radio list widget.
#include <musicwebmusicradiolistview.h>
Public Slots
void itemHasClicked (QListWidgetItem *item)
void addListWidgetItem ()
Public Member Functions
MusicWebMusicRadioListView (QWidget *parent=0)
~MusicWebMusicRadioListView ()
void initListItems ()
Static Public Member Functions
static QString getClassName ()
Protected Attributes
QNetworkCookieJar * m_cookJar
MusicRadioChannelThread * m_getChannelThread
MusicWebMusicRadioWidget * m_musicRadio
Detailed Description
The class of the web music radio list widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 22 of file musicwebmusicradiolistview.h.
Constructor & Destructor Documentation
MusicWebMusicRadioListView::MusicWebMusicRadioListView (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 9 of file musicwebmusicradiolistview.cpp.
References itemHasClicked(), m_cookJar, MusicUIObject::MScrollBarStyle03, and MusicUtils::Widget::setTransparent().
MusicWebMusicRadioListView::~MusicWebMusicRadioListView ()
Definition at line 30 of file musicwebmusicradiolistview.cpp.
References m_cookJar, m_getChannelThread, and m_musicRadio.
Member Function Documentation
void MusicWebMusicRadioListView::addListWidgetItem () slot
Add radio list into list widget.
Definition at line 53 of file musicwebmusicradiolistview.cpp.
References MusicRadioChannelThread::getMusicChannel(), m_getChannelThread, MusicRadioChannelInfo::m_name, and MusicUIObject::MColorStyle12_S.
Referenced by initListItems().
QString MusicWebMusicRadioListView::getClassName () static
Get class object name.
Definition at line 37 of file musicwebmusicradiolistview.cpp.
void MusicWebMusicRadioListView::initListItems ()
To init list items.
Definition at line 42 of file musicwebmusicradiolistview.cpp.
References addListWidgetItem(), m_cookJar, m_getChannelThread, and MusicRadioChannelThread::startToDownload().
Referenced by MusicLeftAreaWidget::musicStackedRadioWidgetChanged().
void MusicWebMusicRadioListView::itemHasClicked (QListWidgetItem * item) slot
Radio list item has clicked.
Definition at line 66 of file musicwebmusicradiolistview.cpp.
References MusicRadioChannelThread::getMusicChannel(), m_cookJar, m_getChannelThread, m_musicRadio, MusicWebMusicRadioWidget::setNetworkCookie(), MusicWebMusicRadioWidget::show(), and MusicWebMusicRadioWidget::updateRadioList().
Referenced by MusicWebMusicRadioListView().
Member Data Documentation
QNetworkCookieJar* MusicWebMusicRadioListView::m_cookJar protected
Definition at line 53 of file musicwebmusicradiolistview.h.
Referenced by initListItems(), itemHasClicked(), MusicWebMusicRadioListView(), and ~MusicWebMusicRadioListView().
MusicRadioChannelThread* MusicWebMusicRadioListView::m_getChannelThread protected
Definition at line 54 of file musicwebmusicradiolistview.h.
Referenced by addListWidgetItem(), initListItems(), itemHasClicked(), and ~MusicWebMusicRadioListView().
MusicWebMusicRadioWidget* MusicWebMusicRadioListView::m_musicRadio protected
Definition at line 55 of file musicwebmusicradiolistview.h.
Referenced by itemHasClicked(), and ~MusicWebMusicRadioListView().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmusicradiolistview.h
TTKModule/TTKWidget/musicToolsKits/musicwebmusicradiolistview.cpp