TTKMusicPlayer: MusicAbstractDJRadioRequest Class Reference
MusicAbstractDJRadioRequest Class Reference
The class of the music dj radio request abstract.
#include <musicabstractdjradiorequest.h>
Signals
void createProgramItem (const MusicResultDataItem &item)
Signals inherited from TTKAbstractNetwork
void downloadDataChanged (const QString &bytes)
void downloadRawDataChanged (const QByteArray &bytes)
Public Member Functions
MusicAbstractDJRadioRequest (QObject *parent=nullptr)
const MusicResultDataItemList & items () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value) noexcept
const QVariant header (const QString &key) const noexcept
Protected Attributes
MusicResultDataItemList m_items
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downloadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Detailed Description
The class of the music dj radio request abstract.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicabstractdjradiorequest.h.
Constructor & Destructor Documentation
MusicAbstractDJRadioRequest::MusicAbstractDJRadioRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musicabstractdjradiorequest.cpp.
Member Function Documentation
void MusicAbstractDJRadioRequest::createProgramItem (const MusicResultDataItem & item) signal
Create the current category item.
Referenced by MusicDJRadioProgramRequest::downloadFinished().
const MusicResultDataItemList& MusicAbstractDJRadioRequest::items () const inline noexcept
Get suggest list items.
Definition at line 49 of file musicabstractdjradiorequest.h.
Referenced by MusicWebDJRadioCategoryWidget::createCategoryItems(), and MusicWebDJRadioProgramTableWidget::itemCellClicked().
Member Data Documentation
MusicResultDataItemList MusicAbstractDJRadioRequest::m_items protected
Definition at line 58 of file musicabstractdjradiorequest.h.
Referenced by MusicDJRadioCategoryRequest::downloadFinished(), and MusicDJRadioProgramRequest::downloadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicabstractdjradiorequest.h
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicabstractdjradiorequest.cpp