TTKMusicPlayer: MusicWebDJRadioProgramWidget Class Reference
MusicWebDJRadioProgramWidget Class Reference
The class of the music dj radio program widget.
#include <musicwebdjradiowidget.h>
Public Member Functions
MusicWebDJRadioProgramWidget (MusicObject::Program type, QWidget *parent=nullptr)
~MusicWebDJRadioProgramWidget ()
void initialize ()
void resizeWindow ()
Private Attributes
MusicObject::Program m_type
MusicWebDJRadioProgramTableWidget * m_tableWidget
Detailed Description
The class of the music dj radio program widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 85 of file musicwebdjradiowidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioProgramWidget::MusicWebDJRadioProgramWidget (MusicObject::Program type, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 151 of file musicwebdjradiowidget.cpp.
References MusicUIObject::ColorStyle05, m_tableWidget, MusicUIObject::PushButtonStyle03, and MusicObject::Recommed.
MusicWebDJRadioProgramWidget::~MusicWebDJRadioProgramWidget ()
Definition at line 194 of file musicwebdjradiowidget.cpp.
References m_tableWidget.
Member Function Documentation
void MusicWebDJRadioProgramWidget::initialize ()
Init parameters.
Definition at line 199 of file musicwebdjradiowidget.cpp.
References MusicWebDJRadioProgramTableWidget::initialize(), m_tableWidget, and m_type.
Referenced by MusicWebDJRadioWidget::createProgramWidget(), and MusicWebDJRadioWidget::createRecommendWidget().
void MusicWebDJRadioProgramWidget::resizeWindow ()
Resize window bound by resize called.
Definition at line 204 of file musicwebdjradiowidget.cpp.
References m_tableWidget, and MusicWebDJRadioProgramTableWidget::resizeSection().
Referenced by MusicWebDJRadioWidget::resizeWidget().
Member Data Documentation
MusicWebDJRadioProgramTableWidget* MusicWebDJRadioProgramWidget::m_tableWidget private
Definition at line 107 of file musicwebdjradiowidget.h.
Referenced by initialize(), MusicWebDJRadioProgramWidget(), resizeWindow(), and ~MusicWebDJRadioProgramWidget().
MusicObject::Program MusicWebDJRadioProgramWidget::m_type private
Definition at line 106 of file musicwebdjradiowidget.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiowidget.cpp