TTKMusicPlayer: MusicDownloadRecordTableWidget Class Reference
MusicDownloadRecordTableWidget Class Reference
The class of the download record table widget.
#include <musicdownloadrecordwidget.h>
Public Member Functions
MusicDownloadRecordTableWidget (QWidget *parent=nullptr)
~MusicDownloadRecordTableWidget ()
Public Member Functions inherited from MusicAbstractDownloadTableWidget
MusicAbstractDownloadTableWidget (QWidget *parent=nullptr)
~MusicAbstractDownloadTableWidget ()
virtual void updateSongsList (const MusicSongList &songs) overridefinal
Public Member Functions inherited from MusicAbstractSongsListTableWidget
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
~MusicAbstractSongsListTableWidget ()
virtual void setSongsList (MusicSongList *songs)
virtual void selectRow (int index)
void setPlaylistRow (int index) noexcept
void setPlayRowIndex (int index) noexcept
int playRowIndex () const noexcept
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Private Member Functions
virtual void addCellItem (int index, const MusicSong &record) overridefinal
Additional Inherited Members
Public Slots inherited from MusicAbstractDownloadTableWidget
virtual void removeItemAt () overridefinal
void itemDoubleClicked (int row, int column)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Public Slots inherited from MusicAbstractSongsListTableWidget
virtual void removeItemAt ()
void playClicked ()
void clearItems ()
void openFileDir ()
void showFileInformation ()
void showMovieQueryWidget ()
void showAlbumQueryWidget ()
void showSimilarQueryWidget ()
void showSongSharedWidget ()
void showDownloadWidget ()
void showPlayedMovieQueryWidget ()
void showPlayedSimilarQueryWidget ()
void showPlayedSongSharedWidget ()
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals inherited from MusicAbstractDownloadTableWidget
void updateItemTitle (int index)
Signals inherited from MusicAbstractSongsListTableWidget
void isCurrentPlaylistRow (bool &state)
Protected Member Functions inherited from MusicAbstractDownloadTableWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicAbstractSongsListTableWidget
int totalRowHeight () const
void createMoreMenu (QMenu *menu)
QString currentSongPath () const
QString songPath (int index) const
QString currentSongName () const
QString songName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
QScrollBar * scrollBar () const noexcept
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes inherited from MusicAbstractDownloadTableWidget
TTK::Record m_type
TTKProgressBarItemDelegate * m_progressBarDelegate
Protected Attributes inherited from MusicAbstractSongsListTableWidget
int m_playlistRow
int m_playRowIndex
MusicSongList * m_songs
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the download record table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadrecordwidget.h.
Constructor & Destructor Documentation
MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musicdownloadrecordwidget.cpp.
References G_CONNECTION_PTR, MusicAbstractDownloadTableWidget::m_progressBarDelegate, MusicAbstractDownloadTableWidget::m_type, TTK::NormalDownload, TTK::UI::ScrollBarStyle03, and TTK::Widget::setTransparent().
MusicDownloadRecordTableWidget::~MusicDownloadRecordTableWidget ()
Object destructor.
Definition at line 26 of file musicdownloadrecordwidget.cpp.
References G_CONNECTION_PTR.
Member Function Documentation
void MusicDownloadRecordTableWidget::addCellItem (int index, const MusicSong & record) final override private virtual
Create cell item by input record.
Implements MusicAbstractDownloadTableWidget.
Definition at line 31 of file musicdownloadrecordwidget.cpp.
References MusicSong::addTimeStr(), TTK::UI::Color01, TTK::Widget::elidedText(), MusicSong::name(), QtItemSetTextAlignment, MusicSong::sizeStr(), MusicAbstractSongsListTableWidget::totalRowHeight(), TTK_PROGRESS_ROLE, and TTK_TIME_ROLE.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicdownloadrecordwidget.h
TTKModule/TTKWidget/musicToolsKits/musicdownloadrecordwidget.cpp