TTKMusicplayer: MusicLrcContainerForCortana Class Reference
MusicLrcContainerForCortana Class Reference
The class of the wall paper lrc container.
#include <musiclrccontainerforcortana.h>
Public Slots
void changeCurrentLrcColor ()
Public Slots inherited from MusicLrcContainer
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
void showLrcErrorWidget ()
Public Member Functions
MusicLrcContainerForCortana (QWidget *parent=nullptr)
virtual ~MusicLrcContainerForCortana ()
virtual void startTimerClock () override
virtual void stopLrcMask () override
virtual void setSettingParameter () override
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
void updateCurrentLrc (qint64 time)
void updateCurrentLrc (const QString &text)
Public Member Functions inherited from MusicLrcContainer
MusicLrcContainer (QWidget *parent=nullptr)
virtual ~MusicLrcContainer ()
void setLinearGradientColor (MusicLrcColor::LrcColorType lrcColorType)
void setLinearGradientColor (const MusicLrcColor &color)
QString getCurrentSongName () const
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 getTotalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * getLrcAnalysisModel () const
Protected Member Functions
void initCurrentLrc (const QString &str)
void setItemStyleSheet (int index, int size, int transparent)
Protected Member Functions inherited from MusicLrcContainer
void clearAllMusicLRCManager ()
void setSettingParameter (const QString &t)
Protected Attributes
int m_animationFreshTime
MusicVLayoutAnimationWidget * m_layoutWidget
MusicTransitionAnimationLabel * m_background
Protected Attributes inherited from MusicLrcContainer
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_musicLrcContainer
MusicLrcSearchWidget * m_musicLrcSearchWidget
Private Slots
void updateAnimationLrc ()
Additional Inherited Members
Signals inherited from MusicLrcContainer
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Detailed Description
The class of the wall paper lrc container.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musiclrccontainerforcortana.h.
Constructor & Destructor Documentation
MusicLrcContainerForCortana::MusicLrcContainerForCortana (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 9 of file musiclrccontainerforcortana.cpp.
References MusicLayoutAnimationWidget::connectTo(), LRC_WALLPAPER_TPYE, m_animationFreshTime, m_background, MusicLrcContainer::m_containerType, and m_layoutWidget.
MusicLrcContainerForCortana::~MusicLrcContainerForCortana () virtual
Definition at line 53 of file musiclrccontainerforcortana.cpp.
References MusicLrcContainer::clearAllMusicLRCManager().
Member Function Documentation
void MusicLrcContainerForCortana::changeCurrentLrcColor () slot
Change current lrc linear color.
Definition at line 125 of file musiclrccontainerforcortana.cpp.
References setSettingParameter().
void MusicLrcContainerForCortana::initCurrentLrc (const QString & str) protected
Init current lrc when the first show.
Definition at line 140 of file musiclrccontainerforcortana.cpp.
References MusicLrcAnalysis::getLineMax(), MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, and MUSIC_LRC_INTERIOR_MAX_LINE.
Referenced by setLrcAnalysisModel().
void MusicLrcContainerForCortana::setItemStyleSheet (int index, int size, int transparent) protected
Set per lrc line style sheet by index and size and transparent.
Definition at line 149 of file musiclrccontainerforcortana.cpp.
References MusicLrcContainer::m_musicLrcContainer, M_SETTING_PTR, MStatic_cast, MusicUtils::String::readColorConfig(), MusicLrcManagerForInterior::setFontSize(), MusicLrcManager::setFontTransparent(), MusicLrcContainer::setLinearGradientColor(), and MusicLrcManagerForInterior::setTransparent().
Referenced by setSettingParameter().
void MusicLrcContainerForCortana::setLrcAnalysisModel (MusicLrcAnalysis * analysis)
Set lrc analysis model.
Definition at line 92 of file musiclrccontainerforcortana.cpp.
References MusicLayoutAnimationWidget::addStretch(), MusicLayoutAnimationWidget::addWidget(), initCurrentLrc(), m_layoutWidget, MusicLrcContainer::m_musicLrcContainer, MUSIC_LRC_INTERIOR_MAX_LINE, and MusicLrcContainer::setLrcAnalysisModel().
void MusicLrcContainerForCortana::setSettingParameter () override virtual
Set setting parameter.
Reimplemented from MusicLrcContainer.
Definition at line 69 of file musiclrccontainerforcortana.cpp.
References LRC_PER_WIDTH, MusicLrcContainer::m_musicLrcContainer, M_SETTING_PTR, MStatic_cast, MUSIC_LRC_INTERIOR_MAX_LINE, MusicSettingManager::ScreenSize, setItemStyleSheet(), MusicLrcManager::setLrcFontSize(), MusicLrcManagerForInterior::setLrcPerWidth(), and MusicLrcManager::setY().
Referenced by changeCurrentLrcColor().
void MusicLrcContainerForCortana::startTimerClock () override virtual
Start timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 58 of file musiclrccontainerforcortana.cpp.
References MusicLrcContainer::m_musicLrcContainer, and MUSIC_LRC_INTERIOR_MAX_LINE.
void MusicLrcContainerForCortana::stopLrcMask () override virtual
Stop timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 63 of file musiclrccontainerforcortana.cpp.
References m_layoutWidget, MusicLrcContainer::m_musicLrcContainer, MUSIC_LRC_INTERIOR_MAX_LINE, and MusicLayoutAnimationWidget::stop().
void MusicLrcContainerForCortana::updateAnimationLrc () private slot
Animation finished.
Definition at line 130 of file musiclrccontainerforcortana.cpp.
References MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getText(), m_animationFreshTime, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, and MUSIC_LRC_INTERIOR_MAX_LINE.
void MusicLrcContainerForCortana::updateCurrentLrc (qint64 time)
Update current lrc by given time.
Definition at line 107 of file musiclrccontainerforcortana.cpp.
References MusicLrcAnalysis::isValid(), m_animationFreshTime, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, and MusicVLayoutAnimationWidget::start().
void MusicLrcContainerForCortana::updateCurrentLrc (const QString & text)
Update current lrc by given text.
Definition at line 116 of file musiclrccontainerforcortana.cpp.
References MusicLrcContainer::m_musicLrcContainer, and MUSIC_LRC_INTERIOR_MAX_LINE.
Member Data Documentation
int MusicLrcContainerForCortana::m_animationFreshTime protected
Definition at line 90 of file musiclrccontainerforcortana.h.
Referenced by MusicLrcContainerForCortana(), updateAnimationLrc(), and updateCurrentLrc().
MusicTransitionAnimationLabel* MusicLrcContainerForCortana::m_background protected
Definition at line 92 of file musiclrccontainerforcortana.h.
Referenced by MusicLrcContainerForCortana().
MusicVLayoutAnimationWidget* MusicLrcContainerForCortana::m_layoutWidget protected
Definition at line 91 of file musiclrccontainerforcortana.h.
Referenced by MusicLrcContainerForCortana(), setLrcAnalysisModel(), stopLrcMask(), and updateCurrentLrc().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforcortana.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforcortana.cpp