TTKMusicplayer: MusicDownLoadQueryXMArtistListThread Class Reference
MusicDownLoadQueryXMArtistListThread Class Reference
The class to xiami query artist list download data from net.
#include <musicdownloadqueryxmartistlistthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadQueryXMArtistListThread (QObject *parent=0)
virtual void startToPage (int offset) override
virtual void startToSearch (const QString &artistlist) override
Public Member Functions inherited from MusicDownLoadQueryArtistListThread
MusicDownLoadQueryArtistListThread (QObject *parent=0)
virtual void startToSearch (QueryType type, const QString &artistlist) override
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
virtual void startToSingleSearch (const QString &text)
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryArtistListThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadQueryArtistListThread
void createArtistListItem (const MusicResultsItem &item)
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class to xiami query artist list download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadqueryxmartistlistthread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryXMArtistListThread::MusicDownLoadQueryXMArtistListThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 8 of file musicdownloadqueryxmartistlistthread.cpp.
References MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicDownLoadQueryThreadAbstract::m_queryServer, and MU_MAX.
Member Function Documentation
void MusicDownLoadQueryXMArtistListThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 63 of file musicdownloadqueryxmartistlistthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryArtistListThread::createArtistListItem(), MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicResultsItem::m_id, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicResultsItem::m_name, MusicNetworkAbstract::m_reply, and QJson::Parser::parse().
Referenced by startToPage().
QString MusicDownLoadQueryXMArtistListThread::getClassName () static
Get class object name.
Definition at line 16 of file musicdownloadqueryxmartistlistthread.cpp.
Referenced by downLoadFinished(), and startToPage().
void MusicDownLoadQueryXMArtistListThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 21 of file musicdownloadqueryxmartistlistthread.cpp.
References ALG_UA_KEY, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicUtils::Algorithm::mdII(), REFER_URL, MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), STRING_SPLITER, MusicUtils::Codec::toUtf8(), XM_AR_LIST_URL, and XM_UA_URL_1.
Referenced by startToSearch().
void MusicDownLoadQueryXMArtistListThread::startToSearch (const QString & artistlist) override virtual
Start to Search data.
Implements MusicDownLoadQueryArtistListThread.
Definition at line 56 of file musicdownloadqueryxmartistlistthread.cpp.
References MusicDownLoadQueryThreadAbstract::m_searchText, and startToPage().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/xm/musicdownloadqueryxmartistlistthread.h
TTKModule/TTKCore/musicNetworkKits/xm/musicdownloadqueryxmartistlistthread.cpp