TTKMusicPlayer: MusicDeviceInfoModule Class Reference
MusicDeviceInfoModule Class Reference
The class of the system device info.
#include <musicdeviceinfomodule.h>
Public Member Functions
MusicDeviceInfoModule (QObject *parent=nullptr)
~MusicDeviceInfoModule ()
bool disksProperty (const QString &drive) const
MusicDeviceInfoItemList removableDrive ()
Private Attributes
MusicDeviceInfoItemList m_items
Detailed Description
The class of the system device info.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 54 of file musicdeviceinfomodule.h.
Constructor & Destructor Documentation
MusicDeviceInfoModule::MusicDeviceInfoModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 11 of file musicdeviceinfomodule.cpp.
MusicDeviceInfoModule::~MusicDeviceInfoModule ()
Object destructor.
Definition at line 20 of file musicdeviceinfomodule.cpp.
Member Function Documentation
bool MusicDeviceInfoModule::disksProperty (const QString & drive) const
Get removable drive property.
Definition at line 27 of file musicdeviceinfomodule.cpp.
References free(), INVALID_HANDLE_VALUE, malloc(), and name.
Referenced by removableDrive().
MusicDeviceInfoItemList MusicDeviceInfoModule::removableDrive ()
Get removable drive name.
Definition at line 103 of file musicdeviceinfomodule.cpp.
References disksProperty(), TTKSemaphoreLoop::exec(), m_items, MusicDeviceInfoItem::m_name, MusicDeviceInfoItem::m_path, MusicDeviceInfoItem::m_totalBytes, MusicDeviceInfoItem::m_usedBytes, QtProcessVoidConnect, TTK_SLOT, and TTK_SN_GB2B.
Referenced by MusicConnectLocalWidget::updateDeviceInfo().
Member Data Documentation
MusicDeviceInfoItemList MusicDeviceInfoModule::m_items private
Definition at line 88 of file musicdeviceinfomodule.h.
Referenced by removableDrive().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsKits/musicdeviceinfomodule.h
TTKModule/TTKCore/musicToolsKits/musicdeviceinfomodule.cpp