TTKMusicPlayer: MusicBingTranslationRequest Class Reference
MusicBingTranslationRequest Class Reference
The class of the bing translation words request.
#include <musicbingtranslationrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBingTranslationRequest (QObject *parent=nullptr)
virtual void startToRequest (const QString &data) overridefinal
Public Member Functions inherited from MusicAbstractTranslationRequest
MusicAbstractTranslationRequest (QObject *parent=nullptr)
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Member Functions
QString mapToString (Language type) const
Additional Inherited Members
Public Types inherited from MusicAbstractTranslationRequest
enum Language { Language::Auto, Language::Chinese }
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the bing translation words request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicbingtranslationrequest.h.
Constructor & Destructor Documentation
MusicBingTranslationRequest::MusicBingTranslationRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musicbingtranslationrequest.cpp.
Member Function Documentation
void MusicBingTranslationRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 76 of file musicbingtranslationrequest.cpp.
References MusicAbstractTranslationRequest::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), TTKAbstractNetwork::downLoadFinished(), TTKAbstractNetwork::m_reply, QJson::Parser::parse(), TTK::toString(), TTK_ERROR_STREAM, and TTK_INFO_STREAM.
Referenced by startToRequest().
QString MusicBingTranslationRequest::mapToString (Language type) const private
Map type from enum to string.
Definition at line 117 of file musicbingtranslationrequest.cpp.
References MusicAbstractTranslationRequest::Auto, and MusicAbstractTranslationRequest::Chinese.
Referenced by startToRequest().
void MusicBingTranslationRequest::startToRequest (const QString & data) final override virtual
Start to download translation data.
Implements MusicAbstractTranslationRequest.
Definition at line 14 of file musicbingtranslationrequest.cpp.
References MusicAbstractTranslationRequest::Auto, MusicAbstractTranslationRequest::Chinese, MusicAbstractTranslationRequest::deleteAll(), TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), downLoadFinished(), key, TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, TTK::makeContentTypeHeader(), TTK::makeUserAgentHeader(), mapToString(), TTK::Algorithm::mdII(), PARAM_URL, QJson::Parser::parse(), QtNetworkErrorConnect, QUERY_URL, MusicAbstractNetwork::replyError(), TTK::setSslConfiguration(), TTK::syncNetworkQueryForGet(), TRANSLATION_URL, TTK_INFO_STREAM, TTK_SLOT, and TTK::Url::urlPrettyEncode().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/translation/musicbingtranslationrequest.h
TTKModule/TTKCore/musicNetworkKits/translation/musicbingtranslationrequest.cpp