TTKMusicplayer: MusicWebDJRadioFoundItemWidget Class Reference
MusicWebDJRadioFoundItemWidget Class Reference
The class of the dj radio music item widget.
#include <musicwebdjradiofoundwidget.h>
Public Slots
void downLoadFinished (const QByteArray &data)
void currentRadioClicked ()
Signals
void currentRadioClicked (const MusicResultsItem &item)
Public Member Functions
MusicWebDJRadioFoundItemWidget (QWidget *parent=0)
virtual ~MusicWebDJRadioFoundItemWidget ()
void setMusicResultsItem (const MusicResultsItem &item)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
MusicResultsItem m_itemData
QPushButton * m_playButton
QLabel * m_iconLabel
QLabel * m_nameLabel
QLabel * m_creatorLabel
Detailed Description
The class of the dj radio music item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 119 of file musicwebdjradiofoundwidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioFoundItemWidget::MusicWebDJRadioFoundItemWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 238 of file musicwebdjradiofoundwidget.cpp.
References currentRadioClicked(), HEIGHT_LABEL_SIZE, m_creatorLabel, m_iconLabel, m_nameLabel, m_playButton, MusicUIObject::MKGTinyBtnPlaylist, and WIDTH_LABEL_SIZE.
MusicWebDJRadioFoundItemWidget::~MusicWebDJRadioFoundItemWidget () virtual
Definition at line 265 of file musicwebdjradiofoundwidget.cpp.
References m_creatorLabel, m_iconLabel, m_nameLabel, and m_playButton.
Member Function Documentation
void MusicWebDJRadioFoundItemWidget::currentRadioClicked (const MusicResultsItem & item) signal
Current radio clicked.
void MusicWebDJRadioFoundItemWidget::currentRadioClicked () slot
Current radio clicked.
Definition at line 311 of file musicwebdjradiofoundwidget.cpp.
References m_itemData.
Referenced by MusicWebDJRadioFoundItemWidget().
void MusicWebDJRadioFoundItemWidget::downLoadFinished (const QByteArray & data) slot
Send recieved data from net.
Definition at line 296 of file musicwebdjradiofoundwidget.cpp.
References MusicUtils::Widget::fusionPixmap(), m_iconLabel, and m_playButton.
Referenced by setMusicResultsItem().
QString MusicWebDJRadioFoundItemWidget::getClassName () static
Get class object name.
Definition at line 273 of file musicwebdjradiofoundwidget.cpp.
void MusicWebDJRadioFoundItemWidget::setMusicResultsItem (const MusicResultsItem & item)
Set music item.
Definition at line 278 of file musicwebdjradiofoundwidget.cpp.
References downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, m_creatorLabel, m_itemData, MusicResultsItem::m_name, m_nameLabel, MusicResultsItem::m_nickName, MusicDownloadSourceThread::startToDownload(), and WIDTH_LABEL_SIZE.
Referenced by MusicWebDJRadioFoundWidget::createProgramItem().
Member Data Documentation
QLabel * MusicWebDJRadioFoundItemWidget::m_creatorLabel protected
Definition at line 159 of file musicwebdjradiofoundwidget.h.
Referenced by MusicWebDJRadioFoundItemWidget(), setMusicResultsItem(), and ~MusicWebDJRadioFoundItemWidget().
QLabel* MusicWebDJRadioFoundItemWidget::m_iconLabel protected
Definition at line 159 of file musicwebdjradiofoundwidget.h.
Referenced by downLoadFinished(), MusicWebDJRadioFoundItemWidget(), and ~MusicWebDJRadioFoundItemWidget().
MusicResultsItem MusicWebDJRadioFoundItemWidget::m_itemData protected
Definition at line 157 of file musicwebdjradiofoundwidget.h.
Referenced by currentRadioClicked(), and setMusicResultsItem().
QLabel * MusicWebDJRadioFoundItemWidget::m_nameLabel protected
Definition at line 159 of file musicwebdjradiofoundwidget.h.
Referenced by MusicWebDJRadioFoundItemWidget(), setMusicResultsItem(), and ~MusicWebDJRadioFoundItemWidget().
QPushButton* MusicWebDJRadioFoundItemWidget::m_playButton protected
Definition at line 158 of file musicwebdjradiofoundwidget.h.
Referenced by downLoadFinished(), MusicWebDJRadioFoundItemWidget(), and ~MusicWebDJRadioFoundItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiofoundwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiofoundwidget.cpp