TTKMusicplayer: QImageWrap::QSharpeImage Class Reference
QImageWrap::QSharpeImage Class Reference abstract
The class of the sharpe image.
#include <qimagewrap.h>
Public Member Functions
QSharpeImage ()
virtual ~QSharpeImage ()
virtual void input (const QRect &rectangle)
virtual QPixmap render (const QPixmap &pixmap, int value)=0
Protected Attributes
QRect m_rectangle
Detailed Description
The class of the sharpe image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 46 of file qimagewrap.h.
Constructor & Destructor Documentation
QImageWrap::QSharpeImage::QSharpeImage ()
Definition at line 115 of file qimagewrap.cpp.
QImageWrap::QSharpeImage::~QSharpeImage () virtual
Definition at line 121 of file qimagewrap.cpp.
Member Function Documentation
void QImageWrap::QSharpeImage::input (const QRect & rectangle) virtual
Init item data.
Reimplemented in QImageWrap::QWaterWave, and QImageWrap::QCubeWave.
Definition at line 126 of file qimagewrap.cpp.
References m_rectangle.
Referenced by QImageWrap::QCubeWave::input(), QImageWrap::QWaterWave::input(), and MusicTransitionAnimationLabel::setPixmap().
virtual QPixmap QImageWrap::QSharpeImage::render (const QPixmap & pixmap, int value) pure virtual
Render data.
Implemented in QImageWrap::QWaterWave, and QImageWrap::QCubeWave.
Referenced by MusicTransitionAnimationLabel::paintEvent().
Member Data Documentation
QRect QImageWrap::QSharpeImage::m_rectangle protected
Definition at line 62 of file qimagewrap.h.
Referenced by input(), QImageWrap::QCubeWave::render(), and QImageWrap::QWaterWave::render().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalg/qimagewrap.h
TTKThirdParty/TTKExtras/qalg/qimagewrap.cpp