TTKMusicplayer: QNPutPolicy Class Reference
QNPutPolicy Class Reference
The namespace of the qiniu policy.
#include <qnputpolicy.h>
Public Member Functions
QNPutPolicy (const QString &scope)
QByteArray toJSON (bool compact=true)
QString makeUploadToken (const QNMac *mac=0)
QString makeDownloadToken (const QNMac *mac=0)
QString getScope () const
void setScope (const QString &value)
qint32 getDeadline () const
void setDeadline (qint32 value)
quint16 getInsertOnly () const
void setInsertOnly (quint16 value)
QString getSaveKey () const
void setSaveKey (const QString &value)
QString getEndUser () const
void setEndUser (const QString &value)
qint32 getFSizeLimit () const
void setFSizeLimit (qint32 value)
qint16 getDetectMime () const
void setDetectMime (qint16 value)
QString getMimeLimit () const
void setMimeLimit (const QString &value)
QString getCallbackUrl () const
void setCallbackUrl (const QString &value)
QString getCallbackHost () const
void setCallbackHost (const QString &value)
QString getCallbackBody () const
void setCallbackBody (const QString &value)
qint16 getCallbackFetchKey () const
void setCallbackFetchKey (qint16 value)
QString getReturnUrl () const
void setReturnUrl (const QString &value)
QString getReturnBody () const
void setReturnBody (const QString &value)
QString getPersistentOps () const
void setPersistentOps (const QString &value)
QString getPersistentNotifyUrl () const
void setPersistentNotifyUrl (const QString &value)
QString getPersistentPipeline () const
void setPersistentPipeline (const QString &value)
Detailed Description
The namespace of the qiniu policy.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 22 of file qnputpolicy.h.
Constructor & Destructor Documentation
QNPutPolicy::QNPutPolicy (const QString & scope)
Object contsructor.
Definition at line 143 of file qnputpolicy.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
QString QNPutPolicy::getCallbackBody () const
Get call back body.
Definition at line 320 of file qnputpolicy.cpp.
References TTK_D.
qint16 QNPutPolicy::getCallbackFetchKey () const
Get call back fetch key.
Definition at line 332 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getCallbackHost () const
Get call back host.
Definition at line 308 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getCallbackUrl () const
Get call back url.
Definition at line 296 of file qnputpolicy.cpp.
References TTK_D.
qint32 QNPutPolicy::getDeadline () const
Get deadline.
Definition at line 200 of file qnputpolicy.cpp.
References TTK_D.
qint16 QNPutPolicy::getDetectMime () const
Get detect mime.
Definition at line 272 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getEndUser () const
Get end user.
Definition at line 248 of file qnputpolicy.cpp.
References TTK_D.
qint32 QNPutPolicy::getFSizeLimit () const
Get file size limit.
Definition at line 260 of file qnputpolicy.cpp.
References TTK_D.
quint16 QNPutPolicy::getInsertOnly () const
Get insert only.
Definition at line 224 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getMimeLimit () const
Get mime limit.
Definition at line 284 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getPersistentNotifyUrl () const
Get persistent notify url.
Definition at line 380 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getPersistentOps () const
Get persistent ops.
Definition at line 368 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getPersistentPipeline () const
Get persistent pipe line.
Definition at line 392 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getReturnBody () const
Get return body.
Definition at line 356 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getReturnUrl () const
Get return url.
Definition at line 344 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getSaveKey () const
Get save key.
Definition at line 236 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::getScope () const
Get scope.
Definition at line 212 of file qnputpolicy.cpp.
References TTK_D.
QString QNPutPolicy::makeDownloadToken (const QNMac * mac = 0)
Make download token.
Definition at line 178 of file qnputpolicy.cpp.
References QNConf::ACCESS_KEY, QNUtils::expireInSeconds(), QNConf::SECRET_KEY, QNMac::signWithData2(), and TTK_D.
Referenced by QNSimpleUploadData::getDownloadUrl().
QString QNPutPolicy::makeUploadToken (const QNMac * mac = 0)
Make uplaod token.
Definition at line 156 of file qnputpolicy.cpp.
References QNConf::ACCESS_KEY, QNUtils::expireInSeconds(), QNConf::SECRET_KEY, QNMac::signWithData(), toJSON(), and TTK_D.
Referenced by QNSimpleUploadData::uploadDataToServer().
void QNPutPolicy::setCallbackBody (const QString & value)
Set call back body.
Definition at line 326 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setCallbackFetchKey (qint16 value)
Set call back fetch key.
Definition at line 338 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setCallbackHost (const QString & value)
Set call back host.
Definition at line 314 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setCallbackUrl (const QString & value)
Set call back url.
Definition at line 302 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setDeadline (qint32 value)
Set deadline.
Definition at line 206 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setDetectMime (qint16 value)
Set detect mime.
Definition at line 278 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setEndUser (const QString & value)
Set end user.
Definition at line 254 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setFSizeLimit (qint32 value)
Set file size limit.
Definition at line 266 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setInsertOnly (quint16 value)
Set insert only.
Definition at line 230 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setMimeLimit (const QString & value)
Set mime limit.
Definition at line 290 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setPersistentNotifyUrl (const QString & value)
Set persistent notify url.
Definition at line 386 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setPersistentOps (const QString & value)
Set persistent ops.
Definition at line 374 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setPersistentPipeline (const QString & value)
Set persistent pipe line.
Definition at line 398 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setReturnBody (const QString & value)
Set return body.
Definition at line 362 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setReturnUrl (const QString & value)
Set return url.
Definition at line 350 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setSaveKey (const QString & value)
Set save key.
Definition at line 242 of file qnputpolicy.cpp.
References TTK_D.
void QNPutPolicy::setScope (const QString & value)
Set scope.
Definition at line 218 of file qnputpolicy.cpp.
References TTK_D.
QByteArray QNPutPolicy::toJSON (bool compact = true)
Transfer data to json.
Definition at line 150 of file qnputpolicy.cpp.
References TTK_D.
Referenced by makeUploadToken().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnputpolicy.h
TTKThirdParty/TTKExtras/qiniu/qnputpolicy.cpp