TTKMusicPlayer: MusicOpenFileWidget Class Reference
MusicOpenFileWidget Class Reference
The class of the open file widget.
#include <musicopenfilewidget.h>
Signals
void uploadFileClicked ()
void uploadDirClicked ()
Public Member Functions
MusicOpenFileWidget (QWidget *parent=nullptr)
void adjustWidgetRect (int w, int h)
Detailed Description
The class of the open file widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicopenfilewidget.h.
Constructor & Destructor Documentation
MusicOpenFileWidget::MusicOpenFileWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicopenfilewidget.cpp.
References MusicUtils::Widget::setLabelFontStyle(), MusicObject::Underline, uploadDirClicked(), and uploadFileClicked().
Member Function Documentation
void MusicOpenFileWidget::adjustWidgetRect (int w, int h)
Adjust the widget rect in the parent widget.
Definition at line 35 of file musicopenfilewidget.cpp.
Referenced by MusicSongsListPlayTableWidget::createUploadFileModule(), MusicCloudManagerTableWidget::createUploadFileModule(), and MusicCloudManagerTableWidget::resizeSection().
void MusicOpenFileWidget::uploadDirClicked () signal
Upload dir button clicked.
Referenced by MusicOpenFileWidget().
void MusicOpenFileWidget::uploadFileClicked () signal
Upload file button clicked.
Referenced by MusicOpenFileWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicopenfilewidget.h
TTKModule/TTKWidget/musicCoreKits/musicopenfilewidget.cpp