TTKMusicplayer: MusicAudioRecorderWidget Class Reference
MusicAudioRecorderWidget Class Reference
The class of the audio recorder widget.
#include <musicaudiorecorderwidget.h>
Public Slots
void onRecordStart ()
void onRecordStop ()
void onRecordPlay ()
void onRecordSave ()
void onStateChange (QAudio::State state)
void onReadMore ()
void onSliderValueChanged (int value)
void onTimeOut ()
void onTimerout ()
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicAudioRecorderWidget (QWidget *parent=nullptr)
virtual ~MusicAudioRecorderWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
int applyVolumeToSample (short iSample)
void initMonitor ()
void createAudioInput ()
void createAudioOutput ()
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicAudioRecorderWidget * m_ui
QTimer m_timer
qint64 m_time
QMovie * m_movie
int m_miVolume
int m_miMaxValue
MusicAudioRecorderCore * m_recordCore
QAudioFormat m_mFormatSound
QAudioInput * m_mpAudioInputSound
QAudioOutput * m_mpAudioOutputSound
QIODevice * m_mpInputDevSound
QIODevice * m_mpOutputDevSound
QByteArray m_mBuffer
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the audio recorder widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 43 of file musicaudiorecorderwidget.h.
Constructor & Destructor Documentation
MusicAudioRecorderWidget::MusicAudioRecorderWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicaudiorecorderwidget.cpp.
References initMonitor(), m_miMaxValue, m_miVolume, m_movie, m_mpAudioInputSound, m_mpAudioOutputSound, m_mpInputDevSound, m_mpOutputDevSound, m_recordCore, m_time, m_timer, m_ui, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MProgressBar02, MusicUIObject::MPushButtonStyle04, MusicUIObject::MSliderStyle01, MusicUIObject::MToolButtonStyle04, onRecordPlay(), onRecordSave(), onRecordStart(), onRecordStop(), and onTimerout().
MusicAudioRecorderWidget::~MusicAudioRecorderWidget () virtual
Definition at line 93 of file musicaudiorecorderwidget.cpp.
References m_movie, m_mpAudioInputSound, m_mpAudioOutputSound, m_mpInputDevSound, m_mpOutputDevSound, m_recordCore, M_SINGLE_MANAGER_PTR, and m_ui.
Member Function Documentation
int MusicAudioRecorderWidget::applyVolumeToSample (short iSample) protected
Apply volume to sample.
Definition at line 216 of file musicaudiorecorderwidget.cpp.
References m_miVolume.
Referenced by onReadMore().
void MusicAudioRecorderWidget::createAudioInput () protected
Create audio input.
Definition at line 199 of file musicaudiorecorderwidget.cpp.
References m_mFormatSound, m_mpAudioInputSound, and m_mpInputDevSound.
Referenced by initMonitor().
void MusicAudioRecorderWidget::createAudioOutput () protected
Create audio output.
Definition at line 210 of file musicaudiorecorderwidget.cpp.
References m_mFormatSound, and m_mpAudioOutputSound.
Referenced by initMonitor().
void MusicAudioRecorderWidget::initMonitor () protected
Init parameter monitor.
Definition at line 111 of file musicaudiorecorderwidget.cpp.
References createAudioInput(), createAudioOutput(), m_mFormatSound, m_mpAudioInputSound, m_mpAudioOutputSound, m_mpInputDevSound, m_mpOutputDevSound, m_ui, onReadMore(), and onSliderValueChanged().
Referenced by MusicAudioRecorderWidget().
void MusicAudioRecorderWidget::onReadMore () slot
Recorder to read more data.
Definition at line 227 of file musicaudiorecorderwidget.cpp.
References applyVolumeToSample(), m_mBuffer, m_miMaxValue, m_mpAudioInputSound, m_mpInputDevSound, m_mpOutputDevSound, MT_S2MS, and onTimeOut().
Referenced by initMonitor().
void MusicAudioRecorderWidget::onRecordPlay () slot
Recorder play play.
Definition at line 163 of file musicaudiorecorderwidget.cpp.
References m_movie, m_recordCore, and MusicAudioRecorderCore::onRecordPlay().
Referenced by MusicAudioRecorderWidget().
void MusicAudioRecorderWidget::onRecordSave () slot
Recorder play save.
Definition at line 182 of file musicaudiorecorderwidget.cpp.
References MusicAudioRecorderCore::addWavHeader(), MusicUtils::Widget::getSaveFileDialog(), m_recordCore, and MusicUtils::Codec::toLocal8Bit().
Referenced by MusicAudioRecorderWidget().
void MusicAudioRecorderWidget::onRecordStart () slot
Recorder play start.
Definition at line 141 of file musicaudiorecorderwidget.cpp.
References MusicAudioRecorderCore::error(), m_movie, m_recordCore, m_timer, m_ui, MT_S2MS, and MusicAudioRecorderCore::onRecordStart().
Referenced by MusicAudioRecorderWidget().
void MusicAudioRecorderWidget::onRecordStop () slot
Recorder play stop.
Definition at line 169 of file musicaudiorecorderwidget.cpp.
References m_movie, m_recordCore, m_time, m_timer, m_ui, and MusicAudioRecorderCore::onRecordStop().
Referenced by MusicAudioRecorderWidget(), and onStateChange().
void MusicAudioRecorderWidget::onSliderValueChanged (int value) slot
Change current volume to set to recorder.
Definition at line 222 of file musicaudiorecorderwidget.cpp.
References m_miVolume.
Referenced by initMonitor().
void MusicAudioRecorderWidget::onStateChange (QAudio::State state) slot
Recorder play state changed.
Definition at line 191 of file musicaudiorecorderwidget.cpp.
References onRecordStop().
void MusicAudioRecorderWidget::onTimeOut () slot
To detect current record state value.
Definition at line 272 of file musicaudiorecorderwidget.cpp.
References m_miMaxValue, and m_ui.
Referenced by onReadMore().
void MusicAudioRecorderWidget::onTimerout () slot
Change current to label show.
Definition at line 105 of file musicaudiorecorderwidget.cpp.
References m_time, m_ui, and MusicTime::normalTime2Label().
Referenced by MusicAudioRecorderWidget().
void MusicAudioRecorderWidget::show () slot
Override show function.
Definition at line 277 of file musicaudiorecorderwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Member Data Documentation
QByteArray MusicAudioRecorderWidget::m_mBuffer protected
Definition at line 126 of file musicaudiorecorderwidget.h.
Referenced by onReadMore().
QAudioFormat MusicAudioRecorderWidget::m_mFormatSound protected
Definition at line 122 of file musicaudiorecorderwidget.h.
Referenced by createAudioInput(), createAudioOutput(), and initMonitor().
int MusicAudioRecorderWidget::m_miMaxValue protected
Definition at line 120 of file musicaudiorecorderwidget.h.
Referenced by MusicAudioRecorderWidget(), onReadMore(), and onTimeOut().
int MusicAudioRecorderWidget::m_miVolume protected
Definition at line 120 of file musicaudiorecorderwidget.h.
Referenced by applyVolumeToSample(), MusicAudioRecorderWidget(), and onSliderValueChanged().
QMovie* MusicAudioRecorderWidget::m_movie protected
Definition at line 118 of file musicaudiorecorderwidget.h.
Referenced by MusicAudioRecorderWidget(), onRecordPlay(), onRecordStart(), onRecordStop(), and ~MusicAudioRecorderWidget().
QAudioInput* MusicAudioRecorderWidget::m_mpAudioInputSound protected
Definition at line 123 of file musicaudiorecorderwidget.h.
Referenced by createAudioInput(), initMonitor(), MusicAudioRecorderWidget(), onReadMore(), and ~MusicAudioRecorderWidget().
QAudioOutput* MusicAudioRecorderWidget::m_mpAudioOutputSound protected
Definition at line 124 of file musicaudiorecorderwidget.h.
Referenced by createAudioOutput(), initMonitor(), MusicAudioRecorderWidget(), and ~MusicAudioRecorderWidget().
QIODevice* MusicAudioRecorderWidget::m_mpInputDevSound protected
Definition at line 125 of file musicaudiorecorderwidget.h.
Referenced by createAudioInput(), initMonitor(), MusicAudioRecorderWidget(), onReadMore(), and ~MusicAudioRecorderWidget().
QIODevice * MusicAudioRecorderWidget::m_mpOutputDevSound protected
Definition at line 125 of file musicaudiorecorderwidget.h.
Referenced by initMonitor(), MusicAudioRecorderWidget(), onReadMore(), and ~MusicAudioRecorderWidget().
MusicAudioRecorderCore* MusicAudioRecorderWidget::m_recordCore protected
Definition at line 121 of file musicaudiorecorderwidget.h.
Referenced by MusicAudioRecorderWidget(), onRecordPlay(), onRecordSave(), onRecordStart(), onRecordStop(), and ~MusicAudioRecorderWidget().
qint64 MusicAudioRecorderWidget::m_time protected
Definition at line 117 of file musicaudiorecorderwidget.h.
Referenced by MusicAudioRecorderWidget(), onRecordStop(), and onTimerout().
QTimer MusicAudioRecorderWidget::m_timer protected
Definition at line 116 of file musicaudiorecorderwidget.h.
Referenced by MusicAudioRecorderWidget(), onRecordStart(), and onRecordStop().
Ui::MusicAudioRecorderWidget* MusicAudioRecorderWidget::m_ui protected
Definition at line 115 of file musicaudiorecorderwidget.h.
Referenced by initMonitor(), MusicAudioRecorderWidget(), onRecordStart(), onRecordStop(), onTimeOut(), onTimerout(), show(), and ~MusicAudioRecorderWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicaudiorecorderwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicaudiorecorderwidget.cpp