TTKMusicplayer: MusicScreenSaverWidget Class Reference
MusicScreenSaverWidget Class Reference
The class of the screen saver widget.
#include <musicscreensaverwidget.h>
Public Member Functions
MusicScreenSaverWidget (QWidget *parent=nullptr)
void applySettingParameter ()
virtual void resizeWindow ()
Static Public Member Functions
static QVector< bool > parseSettingParameter ()
Private Slots
void inputDataChanged ()
void caseButtonOnAndOff ()
void downLoadFinished (const QString &bytes)
void itemHasClicked (int index, bool status)
Private Member Functions
void initialize ()
Private Attributes
bool m_currentState
QLineEdit * m_inputEdit
QPushButton * m_caseButton
MusicDownloadQueueRequest * m_downloadQueue
MusicScreenSaverListWidget * m_backgroundList
Detailed Description
The class of the screen saver widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 165 of file musicscreensaverwidget.h.
Constructor & Destructor Documentation
MusicScreenSaverWidget::MusicScreenSaverWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 197 of file musicscreensaverwidget.cpp.
References applySettingParameter(), caseButtonOnAndOff(), initialize(), inputDataChanged(), m_backgroundList, m_caseButton, m_currentState, m_inputEdit, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSBackgroundStyle17, MusicUIObject::MQSSColorStyle09, MusicUIObject::MQSSColorStyle13, MusicUIObject::MQSSColorStyle14, MusicUIObject::MQSSLineEditStyle01, and MusicUIObject::MQSSScreenSaverOff.
Member Function Documentation
void MusicScreenSaverWidget::applySettingParameter ()
Apply settings parameters.
Definition at line 282 of file musicscreensaverwidget.cpp.
References caseButtonOnAndOff(), G_SETTING_PTR, m_currentState, m_inputEdit, MusicSettingManager::OtherScreenSaverEnable, and MusicSettingManager::OtherScreenSaverTime.
Referenced by MusicScreenSaverWidget().
void MusicScreenSaverWidget::caseButtonOnAndOff () private slot
Case button on and off.
Definition at line 329 of file musicscreensaverwidget.cpp.
References MusicApplicationModule::applySettingParameter(), G_SETTING_PTR, MusicApplicationModule::instance(), m_caseButton, m_currentState, m_inputEdit, MusicUIObject::MQSSScreenSaverOff, MusicUIObject::MQSSScreenSaverOn, MusicSettingManager::OtherScreenSaverEnable, and MusicSettingManager::OtherScreenSaverTime.
Referenced by applySettingParameter(), and MusicScreenSaverWidget().
void MusicScreenSaverWidget::downLoadFinished (const QString & bytes) private slot
Send download data from net.
Definition at line 348 of file musicscreensaverwidget.cpp.
References MusicScreenSaverListWidget::createItem(), m_backgroundList, OS_SCREEN_DIR, OS_WALLNAIL_NAME, parseSettingParameter(), MusicUtils::String::stringSplitToken(), and TTK_SEPARATOR.
Referenced by initialize().
void MusicScreenSaverWidget::initialize () private
Init parameters.
Definition at line 376 of file musicscreensaverwidget.cpp.
References MusicDownloadQueueRequest::addImageQueue(), CACHE_DIR_FULL, MusicObject::DownloadBigBackground, downLoadFinished(), m_downloadQueue, MusicDownloadQueueData::m_savePath, MusicDownloadQueueData::m_url, QSyncUtils::makeDataBucketUrl(), OS_COUNT, OS_SCREEN_DIR, OS_SCREENSAVER_URL, OS_WALLBAR_NAME, OS_WALLNAIL_NAME, OS_WALLPAPER_NAME, and MusicDownloadQueueRequest::startToDownload().
Referenced by MusicScreenSaverWidget().
void MusicScreenSaverWidget::inputDataChanged () private slot
Input data changed
Definition at line 319 of file musicscreensaverwidget.cpp.
References MusicApplicationModule::applySettingParameter(), G_SETTING_PTR, MusicApplicationModule::instance(), m_inputEdit, MusicSettingManager::OtherScreenSaverEnable, and MusicSettingManager::OtherScreenSaverTime.
Referenced by MusicScreenSaverWidget().
void MusicScreenSaverWidget::itemHasClicked (int index, bool status) private slot
Current item has clicked.
Definition at line 362 of file musicscreensaverwidget.cpp.
References MusicApplicationModule::applySettingParameter(), G_SETTING_PTR, MusicApplicationModule::instance(), MusicSettingManager::OtherScreenSaverIndex, and parseSettingParameter().
QVector< bool > MusicScreenSaverWidget::parseSettingParameter () static
Parse settings parameters.
Definition at line 294 of file musicscreensaverwidget.cpp.
References G_SETTING_PTR, OS_COUNT, and MusicSettingManager::OtherScreenSaverIndex.
Referenced by MusicScreenSaverBackgroundWidget::backgroundTimeout(), downLoadFinished(), and itemHasClicked().
void MusicScreenSaverWidget::resizeWindow () virtual
Resize window bound by widget resize called.
Definition at line 314 of file musicscreensaverwidget.cpp.
References m_backgroundList, and MusicScreenSaverListWidget::resizeWindow().
Member Data Documentation
MusicScreenSaverListWidget* MusicScreenSaverWidget::m_backgroundList private
Definition at line 217 of file musicscreensaverwidget.h.
Referenced by downLoadFinished(), MusicScreenSaverWidget(), and resizeWindow().
QPushButton* MusicScreenSaverWidget::m_caseButton private
Definition at line 215 of file musicscreensaverwidget.h.
Referenced by caseButtonOnAndOff(), and MusicScreenSaverWidget().
bool MusicScreenSaverWidget::m_currentState private
Definition at line 213 of file musicscreensaverwidget.h.
Referenced by applySettingParameter(), caseButtonOnAndOff(), and MusicScreenSaverWidget().
MusicDownloadQueueRequest* MusicScreenSaverWidget::m_downloadQueue private
Definition at line 216 of file musicscreensaverwidget.h.
Referenced by initialize().
QLineEdit* MusicScreenSaverWidget::m_inputEdit private
Definition at line 214 of file musicscreensaverwidget.h.
Referenced by applySettingParameter(), caseButtonOnAndOff(), inputDataChanged(), and MusicScreenSaverWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.cpp