TTKMusicplayer: MusicCloudFileManagerDialog Class Reference
MusicCloudFileManagerDialog Class Reference
The class of the cloud file manager dialog.
#include <musiccloudfilemanagerdialog.h>
Public Slots
void downloadStateChanged ()
virtual int exec ()
void show ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicCloudFileManagerDialog (QWidget *parent=0)
virtual ~MusicCloudFileManagerDialog ()
void setReuploadState (bool state)
void creatFileManager (const MusicUploadData &data)
void creatFilesManager (const MusicUploadDatas &datas)
void updateItemProgress (int percent, const MusicUploadData &data)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Member Functions
QIcon getIconByDataState (MusicUploadData::State state)
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicCloudFileManagerDialog * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the cloud file manager dialog.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 51 of file musiccloudfilemanagerdialog.h.
Constructor & Destructor Documentation
MusicCloudFileManagerDialog::MusicCloudFileManagerDialog (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 8 of file musiccloudfilemanagerdialog.cpp.
References downloadStateChanged(), m_ui, MusicUIObject::MPushButtonStyle04, and MusicUIObject::MToolButtonStyle04.
MusicCloudFileManagerDialog::~MusicCloudFileManagerDialog () virtual
Definition at line 33 of file musiccloudfilemanagerdialog.cpp.
References m_ui.
Member Function Documentation
void MusicCloudFileManagerDialog::creatFileManager (const MusicUploadData & data)
Creat file manager item.
Definition at line 48 of file musiccloudfilemanagerdialog.cpp.
References MusicUtils::Widget::elidedText(), getIconByDataState(), MusicUploadData::m_name, MusicUploadData::m_state, m_ui, MUSIC_PROCS_ROLE, and MusicUploadData::Successed.
Referenced by creatFilesManager(), MusicCloudSharedSongTableWidget::uploadFilesToServer(), and MusicCloudSharedSongTableWidget::uploadFileToServer().
void MusicCloudFileManagerDialog::creatFilesManager (const MusicUploadDatas & datas)
Creat file manager items.
Definition at line 71 of file musiccloudfilemanagerdialog.cpp.
References creatFileManager(), and m_ui.
Referenced by MusicCloudSharedSongTableWidget::deleteFilesToServer(), MusicCloudSharedSongTableWidget::deleteFileToServer(), and MusicCloudSharedSongTableWidget::openFileManagerDialog().
void MusicCloudFileManagerDialog::downloadStateChanged () slot
Download button state changed.
Definition at line 93 of file musiccloudfilemanagerdialog.cpp.
References CLOUD_MANAGER_INDEX_0, CLOUD_MANAGER_INDEX_1, and m_ui.
Referenced by MusicCloudFileManagerDialog().
int MusicCloudFileManagerDialog::exec () virtual slot
Override exec function.
Definition at line 107 of file musiccloudfilemanagerdialog.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
QString MusicCloudFileManagerDialog::getClassName () static
Get class object name.
Definition at line 38 of file musiccloudfilemanagerdialog.cpp.
QIcon MusicCloudFileManagerDialog::getIconByDataState (MusicUploadData::State state) protected
Get icon by data state.
Definition at line 119 of file musiccloudfilemanagerdialog.cpp.
References MusicUploadData::Errored, MusicUploadData::Successed, and MusicUploadData::Waited.
Referenced by creatFileManager(), and updateItemProgress().
void MusicCloudFileManagerDialog::setReuploadState (bool state)
Set reupload state.
Definition at line 43 of file musiccloudfilemanagerdialog.cpp.
References m_ui.
Referenced by MusicCloudSharedSongTableWidget::uploadDone().
void MusicCloudFileManagerDialog::show () slot
Override exec function.
Definition at line 113 of file musiccloudfilemanagerdialog.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicCloudSharedSongTableWidget::openFileManagerDialog().
void MusicCloudFileManagerDialog::updateItemProgress (int percent, const MusicUploadData & data)
Update item progress.
Definition at line 80 of file musiccloudfilemanagerdialog.cpp.
References getIconByDataState(), MusicUploadData::m_name, MusicUploadData::m_state, m_ui, and MUSIC_PROCS_ROLE.
Referenced by MusicCloudSharedSongTableWidget::uploadFileFinished(), and MusicCloudSharedSongTableWidget::uploadProgress().
Member Data Documentation
Ui::MusicCloudFileManagerDialog* MusicCloudFileManagerDialog::m_ui protected
Definition at line 104 of file musiccloudfilemanagerdialog.h.
Referenced by creatFileManager(), creatFilesManager(), downloadStateChanged(), exec(), MusicCloudFileManagerDialog(), setReuploadState(), show(), updateItemProgress(), and ~MusicCloudFileManagerDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudfilemanagerdialog.h
TTKModule/TTKWidget/musicToolsKits/musiccloudfilemanagerdialog.cpp