TTKMusicPlayer: MusicSpectrumWidget Class Reference
MusicSpectrumWidget Class Reference
The class of the music spectrum widget all.
#include <musicspectrumwidget.h>
Classes
struct MusicSpectrum
Public Slots
void spectrumNormalTypeChanged (bool &state, const QString &name)
void spectrumPlusTypeChanged (bool &state, const QString &name)
void spectrumWaveTypeChanged (bool &state, const QString &name)
void spectrumFlowTypeChanged (bool &state, const QString &name)
void spectrumFloridTypeChanged (bool &state, const QString &name)
void localFileButtonClicked ()
void openFileButtonClicked ()
void fullscreenByUser (QWidget *widget, bool state)
Public Slots inherited from MusicAbstractMoveResizePlainWidget
void backgroundChanged ()
void show ()
Public Member Functions
MusicSpectrumWidget (QWidget *parent=nullptr)
~MusicSpectrumWidget ()
Public Member Functions inherited from MusicAbstractMoveResizePlainWidget
MusicAbstractMoveResizePlainWidget (QWidget *parent=nullptr)
~MusicAbstractMoveResizePlainWidget ()
Public Member Functions inherited from TTKAbstractMoveResizeWidget
TTKAbstractMoveResizeWidget (QWidget *parent=nullptr)
TTKAbstractMoveResizeWidget (bool transparent, QWidget *parent=nullptr)
Private Member Functions
TTK_DECLARE_LIST (MusicSpectrum)
virtual void mouseDoubleClickEvent (QMouseEvent *event) overridefinal
void createSpectrumWidget (MusicSpectrum::Module spectrum, bool &state, const QString &name, QLayout *layout)
void createFlowWidget (MusicSpectrum::Module spectrum, bool &state, const QString &name, QLayout *layout)
void createFloridWidget (MusicSpectrum::Module spectrum, bool &state, const QString &name, QLayout *layout)
void createModuleWidget (MusicSpectrum::Module spectrum, bool &state, const QString &name, QLayout *layout, bool florid)
void createLightWidget (MusicSpectrum::Module spectrum, bool &state, const QString &name, QLayout *layout, const QString &url={})
int findSpectrumWidget (const QString &name)
void showMessageBoxWidget ()
Private Attributes
Ui::MusicSpectrumWidget * m_ui
QLayout * m_spectrumLayout
QString m_lastFlowName
QString m_lastFloridName
MusicSpectrumList m_types
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveResizeWidget
virtual bool eventFilter (QObject *object, QEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void sizeDirection ()
void moveDirection ()
void setObjectsTracking (const QWidgetList &objects)
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label) noexcept
Protected Attributes inherited from TTKAbstractMoveResizeWidget
MoveResizeData m_struct
TTK::Direction m_direction
Detailed Description
The class of the music spectrum widget all.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicspectrumwidget.h.
Constructor & Destructor Documentation
MusicSpectrumWidget::MusicSpectrumWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 20 of file musicspectrumwidget.cpp.
References localFileButtonClicked(), m_ui, TTK::UI::MenuStyle02, openFileButtonClicked(), TTK::UI::PushButtonStyle04, MusicWidgetRenderer::setBackgroundLabel(), TTKAbstractMoveResizeWidget::setObjectsTracking(), spectrumFloridTypeChanged(), spectrumFlowTypeChanged(), spectrumNormalTypeChanged(), spectrumPlusTypeChanged(), spectrumWaveTypeChanged(), TTK::UI::TabWidgetStyle01, TTK::UI::ToolButtonStyle04, and TTK::UI::ToolButtonStyle05.
MusicSpectrumWidget::~MusicSpectrumWidget ()
Object destructor.
Definition at line 72 of file musicspectrumwidget.cpp.
References TTK::TTKQmmp::enabledVisualPlugin(), m_types, m_ui, qAsConst, and TTKRemoveSingleWidget.
Member Function Documentation
void MusicSpectrumWidget::createFloridWidget (MusicSpectrum::Module spectrum, bool & state, const QString & name, QLayout * layout) private
Create florid widget.
Definition at line 269 of file musicspectrumwidget.cpp.
References createModuleWidget().
Referenced by fullscreenByUser(), and spectrumFloridTypeChanged().
void MusicSpectrumWidget::createFlowWidget (MusicSpectrum::Module spectrum, bool & state, const QString & name, QLayout * layout) private
Create flow widget.
Definition at line 264 of file musicspectrumwidget.cpp.
References createModuleWidget().
Referenced by fullscreenByUser(), and spectrumFlowTypeChanged().
void MusicSpectrumWidget::createLightWidget (MusicSpectrum::Module spectrum, bool & state, const QString & name, QLayout * layout, const QString & url = {}) private
Create light widget.
Definition at line 332 of file musicspectrumwidget.cpp.
References LightFactory::create(), findSpectrumWidget(), SoundCore::instance(), LIGHT_SPECTROGRAM_MODULE, LIGHT_WAVEFORM_MODULE, MusicSpectrumWidget::MusicSpectrum::m_module, MusicSpectrumWidget::MusicSpectrum::m_object, MusicSpectrumWidget::MusicSpectrum::m_type, m_types, name, Light::open(), SoundCore::path(), TTK::TTKQmmp::pluginPath(), MusicToastLabel::popup(), TTK::String::suffix(), MusicFormats::supportSpekInputFilterFormats(), TTK_FILE_SUFFIX, and TTKObjectCast.
Referenced by fullscreenByUser(), localFileButtonClicked(), openFileButtonClicked(), and spectrumWaveTypeChanged().
void MusicSpectrumWidget::createModuleWidget (MusicSpectrum::Module spectrum, bool & state, const QString & name, QLayout * layout, bool florid) private
Create module widget.
Definition at line 274 of file musicspectrumwidget.cpp.
References TTK::TTKQmmp::enabledVisualPlugin(), findSpectrumWidget(), fullscreenByUser(), MusicTopAreaWidget::instance(), m_lastFloridName, m_lastFlowName, MusicSpectrumWidget::MusicSpectrum::m_module, MusicSpectrumWidget::MusicSpectrum::m_object, MusicSpectrumWidget::MusicSpectrum::m_type, m_types, TTK::UI::MenuStyle02, name, showMessageBoxWidget(), TTKObjectCast, and Visual::visuals().
Referenced by createFloridWidget(), and createFlowWidget().
void MusicSpectrumWidget::createSpectrumWidget (MusicSpectrum::Module spectrum, bool & state, const QString & name, QLayout * layout) private
Create spectrum widget.
Definition at line 220 of file musicspectrumwidget.cpp.
References TTK::TTKQmmp::enabledVisualPlugin(), findSpectrumWidget(), fullscreenByUser(), MusicSpectrumWidget::MusicSpectrum::m_module, MusicSpectrumWidget::MusicSpectrum::m_object, MusicSpectrumWidget::MusicSpectrum::m_type, m_types, TTK::UI::MenuStyle02, name, showMessageBoxWidget(), and Visual::visuals().
Referenced by fullscreenByUser(), spectrumNormalTypeChanged(), spectrumPlusTypeChanged(), and spectrumWaveTypeChanged().
int MusicSpectrumWidget::findSpectrumWidget (const QString & name) private
Find spectrum widget index by name.
Definition at line 398 of file musicspectrumwidget.cpp.
References m_types.
Referenced by createLightWidget(), createModuleWidget(), and createSpectrumWidget().
void MusicSpectrumWidget::fullscreenByUser (QWidget * widget, bool state) slot
Emitted when visual widget is show fullscreen by user.
Definition at line 130 of file musicspectrumwidget.cpp.
References createFloridWidget(), createFlowWidget(), createLightWidget(), createSpectrumWidget(), TTK::TTKQmmp::enabledVisualPlugin(), MusicSpectrumWidget::MusicSpectrum::Florid, MusicSpectrumWidget::MusicSpectrum::Flow, MusicSpectrumWidget::MusicSpectrum::Light, m_lastFloridName, m_lastFlowName, MusicSpectrumWidget::MusicSpectrum::m_module, m_spectrumLayout, MusicSpectrumWidget::MusicSpectrum::m_type, m_types, MusicSpectrumWidget::MusicSpectrum::Normal, MusicSpectrumWidget::MusicSpectrum::Plus, TTKObjectCast, and MusicSpectrumWidget::MusicSpectrum::Wave.
Referenced by createModuleWidget(), and createSpectrumWidget().
void MusicSpectrumWidget::localFileButtonClicked () slot
Local file button clicked.
Definition at line 114 of file musicspectrumwidget.cpp.
References createLightWidget(), MusicSpectrumWidget::MusicSpectrum::Light, LIGHT_SPECTROGRAM_MODULE, and m_ui.
Referenced by MusicSpectrumWidget().
void MusicSpectrumWidget::mouseDoubleClickEvent (QMouseEvent * event) final override private virtual
Override the widget event.
Definition at line 211 of file musicspectrumwidget.cpp.
void MusicSpectrumWidget::openFileButtonClicked () slot
Open file button clicked.
Definition at line 120 of file musicspectrumwidget.cpp.
References createLightWidget(), TTK::File::getOpenFileName(), MusicSpectrumWidget::MusicSpectrum::Light, LIGHT_SPECTROGRAM_MODULE, m_ui, and MusicFormats::supportSpekInputFormats().
Referenced by MusicSpectrumWidget().
void MusicSpectrumWidget::showMessageBoxWidget () private
Show message box widget.
Definition at line 416 of file musicspectrumwidget.cpp.
References MusicToastLabel::popup().
Referenced by createModuleWidget(), and createSpectrumWidget().
void MusicSpectrumWidget::spectrumFloridTypeChanged (bool & state, const QString & name) slot
Spectrum Florid Type Changed.
Definition at line 109 of file musicspectrumwidget.cpp.
References createFloridWidget(), MusicSpectrumWidget::MusicSpectrum::Florid, and m_ui.
Referenced by MusicSpectrumWidget().
void MusicSpectrumWidget::spectrumFlowTypeChanged (bool & state, const QString & name) slot
Spectrum Flow Type Changed.
Definition at line 104 of file musicspectrumwidget.cpp.
References createFlowWidget(), MusicSpectrumWidget::MusicSpectrum::Flow, and m_ui.
Referenced by MusicSpectrumWidget().
void MusicSpectrumWidget::spectrumNormalTypeChanged (bool & state, const QString & name) slot
Spectrum Normal Type Changed.
Definition at line 82 of file musicspectrumwidget.cpp.
References createSpectrumWidget(), m_ui, and MusicSpectrumWidget::MusicSpectrum::Normal.
Referenced by MusicSpectrumWidget().
void MusicSpectrumWidget::spectrumPlusTypeChanged (bool & state, const QString & name) slot
Spectrum Plus Type Changed.
Definition at line 87 of file musicspectrumwidget.cpp.
References createSpectrumWidget(), m_ui, and MusicSpectrumWidget::MusicSpectrum::Plus.
Referenced by MusicSpectrumWidget().
void MusicSpectrumWidget::spectrumWaveTypeChanged (bool & state, const QString & name) slot
Spectrum Wave Type Changed.
Definition at line 92 of file musicspectrumwidget.cpp.
References createLightWidget(), createSpectrumWidget(), MusicSpectrumWidget::MusicSpectrum::Light, LIGHT_WAVEFORM_MODULE, m_ui, and MusicSpectrumWidget::MusicSpectrum::Wave.
Referenced by MusicSpectrumWidget().
MusicSpectrumWidget::TTK_DECLARE_LIST (MusicSpectrum) private
Member Data Documentation
QString MusicSpectrumWidget::m_lastFloridName private
Definition at line 137 of file musicspectrumwidget.h.
Referenced by createModuleWidget(), and fullscreenByUser().
QString MusicSpectrumWidget::m_lastFlowName private
Definition at line 136 of file musicspectrumwidget.h.
Referenced by createModuleWidget(), and fullscreenByUser().
QLayout* MusicSpectrumWidget::m_spectrumLayout private
Definition at line 135 of file musicspectrumwidget.h.
Referenced by fullscreenByUser().
MusicSpectrumList MusicSpectrumWidget::m_types private
Definition at line 138 of file musicspectrumwidget.h.
Referenced by createLightWidget(), createModuleWidget(), createSpectrumWidget(), findSpectrumWidget(), fullscreenByUser(), and ~MusicSpectrumWidget().
Ui::MusicSpectrumWidget* MusicSpectrumWidget::m_ui private
Definition at line 134 of file musicspectrumwidget.h.
Referenced by localFileButtonClicked(), MusicSpectrumWidget(), openFileButtonClicked(), spectrumFloridTypeChanged(), spectrumFlowTypeChanged(), spectrumNormalTypeChanged(), spectrumPlusTypeChanged(), spectrumWaveTypeChanged(), and ~MusicSpectrumWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicspectrumwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicspectrumwidget.cpp