TTKMusicplayer: MusicSongDlnaTransferWidget Class Reference
MusicSongDlnaTransferWidget Class Reference
The class of the song dlna transfer widget.
#include <musicsongdlnatransferwidget.h>
Public Slots
void startToScan ()
void scanFinished ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void musicPlay ()
void musicPrevious ()
void musicNext ()
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void queryMusicItemList (MusicSongItemList &songs)
Public Member Functions
MusicSongDlnaTransferWidget (QWidget *parent=nullptr)
~MusicSongDlnaTransferWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Private Attributes
Ui::MusicSongDlnaTransferWidget * m_ui
bool m_isPlaying
int m_currentPlayIndex
MusicSongList * m_songs
QDlnaFinder * m_dlnaFinder
QDlnaFileServer * m_dlnaFileServer
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the song dlna transfer widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicsongdlnatransferwidget.h.
Constructor & Destructor Documentation
MusicSongDlnaTransferWidget::MusicSongDlnaTransferWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicsongdlnatransferwidget.cpp.
References G_CONNECTION_PTR, m_currentPlayIndex, m_dlnaFileServer, m_dlnaFinder, m_isPlaying, m_songs, m_ui, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSComboBoxStyle02, MusicUIObject::MQSSSliderStyle10, MusicUIObject::MQSSToolButtonStyle04, musicNext(), musicPlay(), musicPrevious(), scanFinished(), QDlnaFileServer::start(), and startToScan().
MusicSongDlnaTransferWidget::~MusicSongDlnaTransferWidget ()
Definition at line 79 of file musicsongdlnatransferwidget.cpp.
References G_CONNECTION_PTR, G_SINGLE_MANAGER_PTR, m_dlnaFinder, and m_ui.
Member Function Documentation
void MusicSongDlnaTransferWidget::durationChanged (qint64 duration) slot
Set current player duration.
Definition at line 115 of file musicsongdlnatransferwidget.cpp.
References m_ui.
void MusicSongDlnaTransferWidget::musicNext () slot
Set music to next.
Definition at line 161 of file musicsongdlnatransferwidget.cpp.
References m_currentPlayIndex.
Referenced by MusicSongDlnaTransferWidget().
void MusicSongDlnaTransferWidget::musicPlay () slot
Set music to play.
Definition at line 120 of file musicsongdlnatransferwidget.cpp.
References QDlnaFinder::client(), QDlnaFileServer::localAddress(), m_currentPlayIndex, m_dlnaFileServer, m_dlnaFinder, m_songs, m_ui, MusicSong::path(), queryMusicItemList(), and QDlnaFileServer::setPrefixPath().
Referenced by MusicSongDlnaTransferWidget().
void MusicSongDlnaTransferWidget::musicPrevious () slot
Set music to previous.
Definition at line 156 of file musicsongdlnatransferwidget.cpp.
References m_currentPlayIndex.
Referenced by MusicSongDlnaTransferWidget().
void MusicSongDlnaTransferWidget::positionChanged (qint64 position) slot
Set current player position.
Definition at line 110 of file musicsongdlnatransferwidget.cpp.
References m_ui.
void MusicSongDlnaTransferWidget::queryMusicItemList (MusicSongItemList & songs) signal
Query music datas from container.
Referenced by musicPlay().
void MusicSongDlnaTransferWidget::scanFinished () slot
Scan dlna devices finished.
Definition at line 92 of file musicsongdlnatransferwidget.cpp.
References QDlnaFinder::clientNames(), m_dlnaFinder, m_ui, and name.
Referenced by MusicSongDlnaTransferWidget().
void MusicSongDlnaTransferWidget::show () slot
Override show function.
Definition at line 166 of file musicsongdlnatransferwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
void MusicSongDlnaTransferWidget::startToScan () slot
Start to scan dlna devices.
Definition at line 87 of file musicsongdlnatransferwidget.cpp.
References QDlnaFinder::find(), and m_dlnaFinder.
Referenced by MusicSongDlnaTransferWidget().
Member Data Documentation
int MusicSongDlnaTransferWidget::m_currentPlayIndex private
Definition at line 89 of file musicsongdlnatransferwidget.h.
Referenced by musicNext(), musicPlay(), musicPrevious(), and MusicSongDlnaTransferWidget().
QDlnaFileServer* MusicSongDlnaTransferWidget::m_dlnaFileServer private
Definition at line 92 of file musicsongdlnatransferwidget.h.
Referenced by musicPlay(), and MusicSongDlnaTransferWidget().
QDlnaFinder* MusicSongDlnaTransferWidget::m_dlnaFinder private
Definition at line 91 of file musicsongdlnatransferwidget.h.
Referenced by musicPlay(), MusicSongDlnaTransferWidget(), scanFinished(), startToScan(), and ~MusicSongDlnaTransferWidget().
bool MusicSongDlnaTransferWidget::m_isPlaying private
Definition at line 88 of file musicsongdlnatransferwidget.h.
Referenced by MusicSongDlnaTransferWidget().
MusicSongList* MusicSongDlnaTransferWidget::m_songs private
Definition at line 90 of file musicsongdlnatransferwidget.h.
Referenced by musicPlay(), and MusicSongDlnaTransferWidget().
Ui::MusicSongDlnaTransferWidget* MusicSongDlnaTransferWidget::m_ui private
Definition at line 87 of file musicsongdlnatransferwidget.h.
Referenced by durationChanged(), musicPlay(), MusicSongDlnaTransferWidget(), positionChanged(), scanFinished(), show(), and ~MusicSongDlnaTransferWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsongdlnatransferwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsongdlnatransferwidget.cpp