TTKMusicplayer: MusicNetworkSpeedTestThread Class Reference
MusicNetworkSpeedTestThread Class Reference
The class of the network speed test thread.
#include <musicnetworkspeedtestthread.h>
Public Slots
void start ()
virtual void run () override
Signals
void networkData (ulong upload, ulong download)
Public Member Functions
MusicNetworkSpeedTestThread (QObject *parent=0)
~MusicNetworkSpeedTestThread ()
void stopAndQuitThread ()
void setAvailableNewtworkNames (const QStringList &names)
QStringList getAvailableNewtworkNames () const
QStringList getNewtworkNames () const
Static Public Member Functions
static QString getClassName ()
Protected Attributes
bool m_run
QStringList m_names
QProcess * m_process
Private Slots
void outputRecieved ()
Detailed Description
The class of the network speed test thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 21 of file musicnetworkspeedtestthread.h.
Constructor & Destructor Documentation
MusicNetworkSpeedTestThread::MusicNetworkSpeedTestThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 17 of file musicnetworkspeedtestthread.cpp.
References m_process, m_run, and setAvailableNewtworkNames().
MusicNetworkSpeedTestThread::~MusicNetworkSpeedTestThread ()
Definition at line 27 of file musicnetworkspeedtestthread.cpp.
References m_process, and stopAndQuitThread().
Member Function Documentation
QStringList MusicNetworkSpeedTestThread::getAvailableNewtworkNames () const
Get available newtwork names.
Definition at line 71 of file musicnetworkspeedtestthread.cpp.
References m_names.
Referenced by MusicNetworkSpeedSuspensionWidget::contextMenuEvent(), and MusicNetworkSpeedTestWidget::suspensionOpen().
QString MusicNetworkSpeedTestThread::getClassName () static
Get class object name.
Definition at line 37 of file musicnetworkspeedtestthread.cpp.
QStringList MusicNetworkSpeedTestThread::getNewtworkNames () const
Get newtwork names.
Definition at line 76 of file musicnetworkspeedtestthread.cpp.
References MReinterpret_cast.
Referenced by MusicNetworkSpeedSuspensionWidget::contextMenuEvent(), and MusicNetworkSpeedTestWidget::settingButton().
void MusicNetworkSpeedTestThread::networkData (ulong upload, ulong download) signal
Send current upload and download speed data.
Referenced by outputRecieved(), and run().
void MusicNetworkSpeedTestThread::outputRecieved () private slot
Get output recieved data on linux network.
Definition at line 124 of file musicnetworkspeedtestthread.cpp.
References m_process, and networkData().
Referenced by setAvailableNewtworkNames().
void MusicNetworkSpeedTestThread::run () override virtual slot
Thread run now.
Definition at line 149 of file musicnetworkspeedtestthread.cpp.
References m_names, m_run, MReinterpret_cast, and networkData().
void MusicNetworkSpeedTestThread::setAvailableNewtworkNames (const QStringList & names)
Set available newtwork names.
Definition at line 52 of file musicnetworkspeedtestthread.cpp.
References m_names, m_process, and outputRecieved().
Referenced by MusicNetworkSpeedTestThread(), and MusicNetworkSpeedSuspensionWidget::setAvailableNewtworkNames().
void MusicNetworkSpeedTestThread::start () slot
Strat thread now.
Definition at line 143 of file musicnetworkspeedtestthread.cpp.
References m_run.
Referenced by MusicNetworkSpeedSuspensionWidget::MusicNetworkSpeedSuspensionWidget(), and MusicNetworkSpeedTestWidget::MusicNetworkSpeedTestWidget().
void MusicNetworkSpeedTestThread::stopAndQuitThread ()
Stop and quit current thread.
Definition at line 42 of file musicnetworkspeedtestthread.cpp.
References m_run.
Referenced by ~MusicNetworkSpeedTestThread().
Member Data Documentation
QStringList MusicNetworkSpeedTestThread::m_names protected
Definition at line 78 of file musicnetworkspeedtestthread.h.
Referenced by getAvailableNewtworkNames(), run(), and setAvailableNewtworkNames().
QProcess* MusicNetworkSpeedTestThread::m_process protected
Definition at line 79 of file musicnetworkspeedtestthread.h.
Referenced by MusicNetworkSpeedTestThread(), outputRecieved(), setAvailableNewtworkNames(), and ~MusicNetworkSpeedTestThread().
bool MusicNetworkSpeedTestThread::m_run protected
Definition at line 77 of file musicnetworkspeedtestthread.h.
Referenced by MusicNetworkSpeedTestThread(), run(), start(), and stopAndQuitThread().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicnetworkspeedtestthread.h
TTKModule/TTKCore/musicToolsSetsKits/musicnetworkspeedtestthread.cpp