TTKMusicplayer: MusicDownLoadKGInterface Class Reference
MusicDownLoadKGInterface Class Reference
The class to kugou query download interface.
#include <musicdownloadkginterface.h>
Public Member Functions
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &hash)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongLrcAndPic (MusicObject::MusicSongInformation *info)
void readFromMusicSongAlbumInfo (MusicResultsItem *info, const QString &album)
Detailed Description
The class to kugou query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 66 of file musicdownloadkginterface.h.
Member Function Documentation
void MusicDownLoadKGInterface::readFromMusicSongAlbumInfo (MusicResultsItem * info, const QString & album)
Read tags(album info) from query results.
Definition at line 146 of file musicdownloadkginterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), KG_ALBUM_INFO_URL, KG_UA_URL_1, MusicResultsItem::m_description, MusicResultsItem::m_nickName, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicUtils::Codec::toUtf8().
Referenced by MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), and MusicDownLoadQueryKGPlaylistThread::getDetailsFinished().
void MusicDownLoadKGInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & hash)
QJson import.
Read tags(size) from query results.
Definition at line 15 of file musicdownloadkginterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), KG_SONG_ATTR_URL, KG_UA_URL_1, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicUtils::Number::size2Label(), MusicUtils::Codec::toUtf8(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), readFromMusicSongAttribute(), and MusicDownLoadQueryKGThread::singleDownLoadFinished().
void MusicDownLoadKGInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 70 of file musicdownloadkginterface.cpp.
References readFromMusicSongAttribute().
Referenced by readFromMusicSongAttribute().
void MusicDownLoadKGInterface::readFromMusicSongLrcAndPic (MusicObject::MusicSongInformation * info)
Read tags(lrc) from query results.
Definition at line 98 of file musicdownloadkginterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), KG_SONG_INFO_URL, KG_SONG_LRC_URL, KG_UA_URL_1, MusicObject::MusicSongInformation::m_artistId, MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songId, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicUtils::Codec::toUtf8().
Referenced by MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), and MusicDownLoadQueryKGPlaylistThread::getDetailsFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/kg/musicdownloadkginterface.h
TTKModule/TTKCore/musicNetworkKits/kg/musicdownloadkginterface.cpp