TTKMusicPlayer: ReqBLInterface Namespace Reference
ReqBLInterface Namespace Reference
The namespace of the bl request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request) noexcept
void parseFromMovieInfo (TTK::MusicSongInformation *info, QString &cid)
void parseFromMovieProperty (TTK::MusicSongInformation *info, const QString &cid)
Variables
static constexpr const char * MODULE = "BL"
Detailed Description
The namespace of the bl request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void ReqBLInterface::makeRequestRawHeader (QNetworkRequest * request) noexcept
Make request query data.
Definition at line 8 of file musicblqueryinterface.cpp.
References BL_COOKIE_URL, TTK::Algorithm::mdII(), TTK::setContentTypeHeader(), and TTK::setSslConfiguration().
Referenced by parseFromMovieInfo(), parseFromMovieProperty(), MusicUnityQueryMovieRequest::startToPage(), and MusicBarrageRequest::startToRequest().
void ReqBLInterface::parseFromMovieInfo (TTK::MusicSongInformation * info, QString & cid)
Read mv cid from query results.
Definition at line 16 of file musicblqueryinterface.cpp.
References BL_MOVIE_DATA_URL, QJsonParseError::error, QJsonDocument::fromJson(), TTK::MusicSongInformation::m_songId, makeRequestRawHeader(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::syncNetworkQueryForGet(), and QJsonDocument::toVariant().
Referenced by MusicBarrageRequest::downloadFinished(), and MusicUnityQueryMovieRequest::downloadUnityFinished().
void ReqBLInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, const QString & cid)
Read mv tags(size and bitrate and url) from query results.
Definition at line 52 of file musicblqueryinterface.cpp.
References BL_MOVIE_PLAY_URL, QJsonParseError::error, TTKTime::formatDuration(), QJsonDocument::fromJson(), HTTP_PROTOCOL, HTTPS_PROTOCOL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongInformation::m_duration, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, makeRequestRawHeader(), TTK::Algorithm::mdII(), MP4_FILE_SUFFIX, QJsonParseError::NoError, qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), and TTK_BN_250.
Referenced by MusicUnityQueryMovieRequest::downloadUnityFinished().
Variable Documentation
constexpr const char* ReqBLInterface::MODULE = "BL" static
Definition at line 19 of file musicunityquerymovierequest.cpp.
Referenced by MusicUnityQueryMovieRequest::startToPage().