TTKMusicPlayer: MusicVideoView Class Reference
MusicVideoView Class Reference
The class of the video view widget.
#include <musicvideoview.h>
Public Slots
void play ()
Signals
void searchButtonClicked ()
void popupButtonClicked ()
void fullscreenButtonClicked ()
void downloadButtonClicked ()
void shareButtonClicked ()
Public Member Functions
MusicVideoView (QWidget *parent=nullptr)
~MusicVideoView ()
void setMedia (const QString &data)
void resizeGeometry (int width, int height)
void createRightMenu ()
MusicVideoControlWidget * controlBarWidget () const
Private Slots
void stop ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void setPosition (int position)
void volumeChanged (int volume)
void mediaChanged (const QString &data)
void mediaAutionPlayError (int code)
void addBarrageChanged (const MusicBarrageRecord &record)
void pushBarrageChanged (bool on)
void fullscreenButtonTrigger ()
Private Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Private Attributes
MusicViewWidget * m_videoWidget
MusicCoreMPlayer * m_player
MusicVideoControlWidget * m_videoControl
MusicBarrageWidget * m_barrageCore
Detailed Description
The class of the video view widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 71 of file musicvideoview.h.
Constructor & Destructor Documentation
MusicVideoView::MusicVideoView (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 66 of file musicvideoview.cpp.
References addBarrageChanged(), MusicUIObject::BackgroundStyle02, durationChanged(), fullscreenButtonClicked(), m_barrageCore, m_player, m_videoControl, m_videoWidget, mediaAutionPlayError(), mediaChanged(), play(), positionChanged(), pushBarrageChanged(), resizeGeometry(), and setPosition().
MusicVideoView::~MusicVideoView ()
Definition at line 93 of file musicvideoview.cpp.
References m_barrageCore, m_player, m_videoControl, and m_videoWidget.
Member Function Documentation
void MusicVideoView::addBarrageChanged (const MusicBarrageRecord & record) private slot
Add barrage text to mv.
Definition at line 200 of file musicvideoview.cpp.
References MusicBarrageWidget::addBarrage(), and m_barrageCore.
Referenced by MusicVideoView().
void MusicVideoView::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Definition at line 101 of file musicvideoview.cpp.
References createRightMenu().
MusicVideoControlWidget* MusicVideoView::controlBarWidget () const inline
Get control bar widget.
Definition at line 97 of file musicvideoview.h.
Referenced by MusicVideoPlayWidget::enterEvent(), MusicVideoPlayWidget::leaveTimeout(), and MusicVideoPlayWidget::MusicVideoPlayWidget().
void MusicVideoView::createRightMenu ()
Create right menu.
Definition at line 120 of file musicvideoview.cpp.
References MusicUtils::Widget::adjustMenuPosition(), downloadButtonClicked(), fullscreenButtonTrigger(), MusicCoreMPlayer::isPlaying(), m_player, MusicUIObject::MenuStyle02, play(), popupButtonClicked(), searchButtonClicked(), shareButtonClicked(), and stop().
Referenced by contextMenuEvent().
void MusicVideoView::downloadButtonClicked () signal
Download button clicked.
Referenced by createRightMenu().
void MusicVideoView::durationChanged (qint64 duration) private slot
Current duration changed.
Definition at line 171 of file musicvideoview.cpp.
References MusicVideoControlWidget::durationChanged(), and m_videoControl.
Referenced by MusicVideoView().
void MusicVideoView::fullscreenButtonClicked () signal
Fullscreen button clicked.
Referenced by fullscreenButtonTrigger(), and MusicVideoView().
void MusicVideoView::fullscreenButtonTrigger () private slot
Fullscreen action trigger.
Definition at line 210 of file musicvideoview.cpp.
References fullscreenButtonClicked(), and MT_ONCE.
Referenced by createRightMenu().
void MusicVideoView::mediaAutionPlayError (int code) private slot
Media aution play error.
Definition at line 191 of file musicvideoview.cpp.
References MusicToastLabel::popup(), stop(), and TTK_LOW_LEVEL.
Referenced by MusicVideoView().
void MusicVideoView::mediaChanged (const QString & data) private slot
Current media changed.
Definition at line 186 of file musicvideoview.cpp.
References m_videoControl, and MusicVideoControlWidget::mediaChanged().
Referenced by MusicVideoView().
void MusicVideoView::play () slot
Player to play.
Definition at line 138 of file musicvideoview.cpp.
References m_barrageCore, m_player, m_videoControl, MusicBarrageWidget::pause(), MusicObject::Paused, MusicCoreMPlayer::play(), MusicObject::Playing, MusicVideoControlWidget::setButtonStyle(), MusicBarrageWidget::start(), and MusicCoreMPlayer::state().
Referenced by createRightMenu(), MusicVideoPlayWidget::mediaUrlChanged(), and MusicVideoView().
void MusicVideoView::popupButtonClicked () signal
Popup button clicked.
Referenced by createRightMenu().
void MusicVideoView::positionChanged (qint64 position) private slot
Current position changed.
Definition at line 166 of file musicvideoview.cpp.
References m_videoControl, and MusicVideoControlWidget::setValue().
Referenced by MusicVideoView().
void MusicVideoView::pushBarrageChanged (bool on) private slot
Open barrage on or not.
Definition at line 205 of file musicvideoview.cpp.
References MusicBarrageWidget::barrageStateChanged(), and m_barrageCore.
Referenced by MusicVideoView().
void MusicVideoView::resizeGeometry (int width, int height)
Resize geometry bound by resize called.
Definition at line 113 of file musicvideoview.cpp.
References m_barrageCore, m_videoControl, m_videoWidget, and MusicBarrageWidget::setSize().
Referenced by MusicVideoView(), and MusicVideoPlayWidget::resizeGeometry().
void MusicVideoView::searchButtonClicked () signal
Search button clicked.
Referenced by createRightMenu().
void MusicVideoView::setMedia (const QString & data)
Set video play data.
Definition at line 107 of file musicvideoview.cpp.
References m_player, m_videoControl, m_videoWidget, MusicCoreMPlayer::setMedia(), MusicVideoControlWidget::setQualityActionState(), and MusicCoreMPlayer::Video.
Referenced by MusicVideoPlayWidget::mediaUrlChanged().
void MusicVideoView::setPosition (int position) private slot
Set current play pos.
Definition at line 176 of file musicvideoview.cpp.
References m_player, MT_S2MS, and MusicCoreMPlayer::setPosition().
Referenced by MusicVideoView().
void MusicVideoView::shareButtonClicked () signal
Share button clicked.
Referenced by createRightMenu().
void MusicVideoView::stop () private slot
Player to stop.
Definition at line 159 of file musicvideoview.cpp.
References m_barrageCore, m_player, MusicBarrageWidget::stop(), and MusicCoreMPlayer::stop().
Referenced by createRightMenu(), and mediaAutionPlayError().
void MusicVideoView::volumeChanged (int volume) private slot
Current volume changed.
Definition at line 181 of file musicvideoview.cpp.
References m_player, and MusicCoreMPlayer::setVolume().
Member Data Documentation
MusicBarrageWidget* MusicVideoView::m_barrageCore private
Definition at line 180 of file musicvideoview.h.
Referenced by addBarrageChanged(), MusicVideoView(), play(), pushBarrageChanged(), resizeGeometry(), stop(), and ~MusicVideoView().
MusicCoreMPlayer* MusicVideoView::m_player private
Definition at line 178 of file musicvideoview.h.
Referenced by createRightMenu(), MusicVideoView(), play(), setMedia(), setPosition(), stop(), volumeChanged(), and ~MusicVideoView().
MusicVideoControlWidget* MusicVideoView::m_videoControl private
Definition at line 179 of file musicvideoview.h.
Referenced by durationChanged(), mediaChanged(), MusicVideoView(), play(), positionChanged(), resizeGeometry(), setMedia(), and ~MusicVideoView().
MusicViewWidget* MusicVideoView::m_videoWidget private
Definition at line 177 of file musicvideoview.h.
Referenced by MusicVideoView(), resizeGeometry(), setMedia(), and ~MusicVideoView().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideoview.h
TTKModule/TTKWidget/musicVideoKits/musicvideoview.cpp