TTKMusicplayer: MusicSongRingtoneMaker Class Reference
MusicSongRingtoneMaker Class Reference
The class of the song ringtone maker widget.
#include <musicsongringtonemakerwidget.h>
Public Slots
void initInputPath ()
void initOutputPath ()
void playInputSong ()
void playRingtone ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void posChanged (qint64 start, qint64 end)
void buttonReleaseChanged (qint64 pos)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicSongRingtoneMaker (QWidget *parent=nullptr)
~MusicSongRingtoneMaker ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void initControlParameter () const
void playButtonStateChanged ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
Ui::MusicSongRingtoneMaker * m_ui
bool m_playRingtone
QString m_inputFilePath
MusicCoreMPlayer * m_mediaPlayer
qint64 m_startPos
qint64 m_stopPos
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the song ringtone maker widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicsongringtonemakerwidget.h.
Constructor & Destructor Documentation
MusicSongRingtoneMaker::MusicSongRingtoneMaker (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 13 of file musicsongringtonemakerwidget.cpp.
References buttonReleaseChanged(), DEFAULT_HIGHER_LEVEL, durationChanged(), MusicUtils::Widget::generateComboBoxFormat(), initControlParameter(), initInputPath(), initOutputPath(), m_mediaPlayer, m_playRingtone, m_startPos, m_stopPos, m_ui, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, playInputSong(), playRingtone(), posChanged(), and positionChanged().
MusicSongRingtoneMaker::~MusicSongRingtoneMaker ()
Definition at line 64 of file musicsongringtonemakerwidget.cpp.
References m_mediaPlayer, and m_ui.
Member Function Documentation
void MusicSongRingtoneMaker::buttonReleaseChanged (qint64 pos) slot
Moving button pos release changed.
Definition at line 170 of file musicsongringtonemakerwidget.cpp.
References MusicCoreMPlayer::isPlaying(), m_mediaPlayer, m_ui, and MusicCoreMPlayer::setPosition().
Referenced by MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::durationChanged (qint64 duration) slot
Current duration changed.
Definition at line 156 of file musicsongringtonemakerwidget.cpp.
References m_ui.
Referenced by MusicSongRingtoneMaker().
int MusicSongRingtoneMaker::exec () virtual slot
Override exec function.
Definition at line 179 of file musicsongringtonemakerwidget.cpp.
References m_ui, MAKE_TRANSFORM_FULL, MusicToastLabel::popup(), and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicToolSetsWidget::itemHasClicked(), and MusicSongsListTableWidget::musicMakeRingWidget().
void MusicSongRingtoneMaker::initControlParameter () const protected
Init control parameter.
Definition at line 191 of file musicsongringtonemakerwidget.cpp.
References m_ui.
Referenced by MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::initInputPath () slot
Selected input path.
Definition at line 70 of file musicsongringtonemakerwidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSongMeta::getBitrate(), MusicSongMeta::getLengthString(), MusicUtils::File::getOpenFileDialog(), MusicSongMeta::getSampleRate(), m_inputFilePath, m_mediaPlayer, m_ui, MusicCoreMPlayer::MusicCategory, name, playInputSong(), MusicSongMeta::read(), and MusicCoreMPlayer::setMedia().
Referenced by MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::initOutputPath () slot
Selected save path.
Definition at line 112 of file musicsongringtonemakerwidget.cpp.
References MusicUtils::File::getSaveFileDialog(), m_inputFilePath, m_startPos, m_stopPos, m_ui, and MAKE_TRANSFORM_FULL.
Referenced by MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::playButtonStateChanged () protected
Play button state changed.
Definition at line 202 of file musicsongringtonemakerwidget.cpp.
References MusicCoreMPlayer::isPlaying(), m_mediaPlayer, and m_ui.
Referenced by playInputSong().
void MusicSongRingtoneMaker::playInputSong () slot
Start to play input song.
Definition at line 129 of file musicsongringtonemakerwidget.cpp.
References m_mediaPlayer, m_playRingtone, MusicCoreMPlayer::play(), and playButtonStateChanged().
Referenced by initInputPath(), and MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::playRingtone () slot
Start to play ringtone.
Definition at line 136 of file musicsongringtonemakerwidget.cpp.
References MusicCoreMPlayer::isPlaying(), m_mediaPlayer, m_playRingtone, m_startPos, m_ui, and MusicCoreMPlayer::setPosition().
Referenced by MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::posChanged (qint64 start, qint64 end) slot
Moving button pos changed.
Definition at line 161 of file musicsongringtonemakerwidget.cpp.
References MusicTime::All_Sec, m_startPos, m_stopPos, m_ui, and MusicTime::toString().
Referenced by MusicSongRingtoneMaker().
void MusicSongRingtoneMaker::positionChanged (qint64 position) slot
Current position changed.
Definition at line 146 of file musicsongringtonemakerwidget.cpp.
References m_mediaPlayer, m_playRingtone, m_stopPos, m_ui, and MusicCoreMPlayer::play().
Referenced by MusicSongRingtoneMaker().
Member Data Documentation
QString MusicSongRingtoneMaker::m_inputFilePath protected
Definition at line 94 of file musicsongringtonemakerwidget.h.
Referenced by initInputPath(), and initOutputPath().
MusicCoreMPlayer* MusicSongRingtoneMaker::m_mediaPlayer protected
Definition at line 95 of file musicsongringtonemakerwidget.h.
Referenced by buttonReleaseChanged(), initInputPath(), MusicSongRingtoneMaker(), playButtonStateChanged(), playInputSong(), playRingtone(), positionChanged(), and ~MusicSongRingtoneMaker().
bool MusicSongRingtoneMaker::m_playRingtone protected
Definition at line 93 of file musicsongringtonemakerwidget.h.
Referenced by MusicSongRingtoneMaker(), playInputSong(), playRingtone(), and positionChanged().
qint64 MusicSongRingtoneMaker::m_startPos protected
Definition at line 96 of file musicsongringtonemakerwidget.h.
Referenced by initOutputPath(), MusicSongRingtoneMaker(), playRingtone(), and posChanged().
qint64 MusicSongRingtoneMaker::m_stopPos protected
Definition at line 96 of file musicsongringtonemakerwidget.h.
Referenced by initOutputPath(), MusicSongRingtoneMaker(), posChanged(), and positionChanged().
Ui::MusicSongRingtoneMaker* MusicSongRingtoneMaker::m_ui protected
Definition at line 92 of file musicsongringtonemakerwidget.h.
Referenced by buttonReleaseChanged(), durationChanged(), exec(), initControlParameter(), initInputPath(), initOutputPath(), MusicSongRingtoneMaker(), playButtonStateChanged(), playRingtone(), posChanged(), positionChanged(), and ~MusicSongRingtoneMaker().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsongringtonemakerwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsongringtonemakerwidget.cpp