TTKMusicplayer: MusicRippleSpecturmObject Class Reference
MusicRippleSpecturmObject Class Reference
The class of the ripples spectrum object.
#include <musicripplespecturmobject.h>
Public Member Functions
MusicRippleSpecturmObject (QObject *parent=nullptr)
~MusicRippleSpecturmObject ()
void setVisible (bool v)
void show ()
void close ()
void update (bool up)
void init (QVBoxLayout *layout, QWidget *widget)
Private Member Functions
void removeSpectrum ()
Private Attributes
QVBoxLayout * m_topAreaLayout
QWidget * m_topAreaWidget
QWidget * m_visualWidget
Detailed Description
The class of the ripples spectrum object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicripplespecturmobject.h.
Constructor & Destructor Documentation
MusicRippleSpecturmObject::MusicRippleSpecturmObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musicripplespecturmobject.cpp.
References m_topAreaLayout, m_topAreaWidget, and m_visualWidget.
MusicRippleSpecturmObject::~MusicRippleSpecturmObject ()
Definition at line 15 of file musicripplespecturmobject.cpp.
References removeSpectrum().
Member Function Documentation
void MusicRippleSpecturmObject::close ()
Set ripples spectrum hide.
Definition at line 58 of file musicripplespecturmobject.cpp.
References m_topAreaLayout, m_topAreaWidget, m_visualWidget, and removeSpectrum().
Referenced by update().
void MusicRippleSpecturmObject::init (QVBoxLayout * layout, QWidget * widget)
Init ripples spectrum paramters.
Definition at line 87 of file musicripplespecturmobject.cpp.
References m_topAreaLayout, and m_topAreaWidget.
Referenced by MusicBottomAreaWidget::setupUi().
void MusicRippleSpecturmObject::removeSpectrum () private
Remove ripples spectrum object.
Definition at line 93 of file musicripplespecturmobject.cpp.
References MusicUtils::QMMP::enableVisualPlugin(), and m_visualWidget.
Referenced by close(), and ~MusicRippleSpecturmObject().
void MusicRippleSpecturmObject::setVisible (bool v)
Set ripples spectrum show or not.
Definition at line 20 of file musicripplespecturmobject.cpp.
References m_topAreaLayout, m_topAreaWidget, and m_visualWidget.
Referenced by MusicBottomAreaWidget::lrcWidgetShowFullScreen().
void MusicRippleSpecturmObject::show ()
Set ripples spectrum show.
Definition at line 30 of file musicripplespecturmobject.cpp.
References CONCISE_WIDTH_MIN, MusicUtils::QMMP::enableVisualPlugin(), m_topAreaLayout, m_topAreaWidget, m_visualWidget, and Visual::visuals().
Referenced by update().
void MusicRippleSpecturmObject::update (bool up)
Update ripples spectrum paramters.
Definition at line 71 of file musicripplespecturmobject.cpp.
References close(), m_visualWidget, MStatic_cast, show(), Visual::start(), and MusicUtils::QMMP::updateRippleSpectrumConfigFile().
Referenced by MusicBottomAreaWidget::getParameterSetting().
Member Data Documentation
QVBoxLayout* MusicRippleSpecturmObject::m_topAreaLayout private
Definition at line 68 of file musicripplespecturmobject.h.
Referenced by close(), init(), MusicRippleSpecturmObject(), setVisible(), and show().
QWidget* MusicRippleSpecturmObject::m_topAreaWidget private
Definition at line 69 of file musicripplespecturmobject.h.
Referenced by close(), init(), MusicRippleSpecturmObject(), setVisible(), and show().
QWidget * MusicRippleSpecturmObject::m_visualWidget private
Definition at line 69 of file musicripplespecturmobject.h.
Referenced by close(), MusicRippleSpecturmObject(), removeSpectrum(), setVisible(), show(), and update().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicripplespecturmobject.h
TTKModule/TTKWidget/musicWidgetKits/musicripplespecturmobject.cpp