TTKMusicplayer: MusicXMLConfigManager Class Reference
MusicXMLConfigManager Class Reference
The class of the XML Config Manager.
#include <musicxmlconfigmanager.h>
Public Member Functions
MusicXMLConfigManager (QObject *parent=0)
bool readXMLConfig ()
bool readMusicXMLConfig ()
void writeXMLConfig ()
void writeMusicSongsConfig (const MusicSongItems &musics, const QString &path=MUSICPATH_FULL)
void readMusicSongsConfig (MusicSongItems &musics)
void readSystemLastPlayIndexConfig (QStringList &key) const
QRect readWindowGeometry () const
QPoint readShowDLrcGeometry () const
void readSysLoadConfig () const
Public Member Functions inherited from MusicAbstractXml
MusicAbstractXml (QObject *parent=0)
~MusicAbstractXml ()
bool readConfig (const QString &name)
bool writeConfig (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagNameValue (const QString &tagName) const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName) const
QString readXmlTextByTagName (const QString &tagName) const
MusicObject::MStriantMap readXmlAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const MusicXmlAttribute &attr)
QDomElement createRoot (const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDom (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const MusicXmlAttribute &attr)
QDomElement writeDomElementMutil (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const MusicXmlAttribute &attr, const QString &text)
QDomElement writeDomElementMutilText (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const MusicXmlAttribute &attr)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractXml
static QString getClassName ()
Protected Member Functions
MusicSongs readMusicFilePath (const QDomNode &node) const
Additional Inherited Members
Protected Attributes inherited from MusicAbstractXml
QFile * m_file
QDomDocument * m_ddom
Detailed Description
The class of the XML Config Manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 18 of file musicxmlconfigmanager.h.
Constructor & Destructor Documentation
MusicXMLConfigManager::MusicXMLConfigManager (QObject * parent = 0) explicit
Object contsructor.
Definition at line 7 of file musicxmlconfigmanager.cpp.
Member Function Documentation
QString MusicXMLConfigManager::getClassName () static
Get class object name.
Definition at line 13 of file musicxmlconfigmanager.cpp.
MusicSongs MusicXMLConfigManager::readMusicFilePath (const QDomNode & node) const protected
Read Music File Path.
Definition at line 525 of file musicxmlconfigmanager.cpp.
Referenced by readMusicSongsConfig().
void MusicXMLConfigManager::readMusicSongsConfig (MusicSongItems & musics)
Read music datas into xml file.
Definition at line 48 of file musicxmlconfigmanager.cpp.
References MusicAbstractXml::m_ddom, MusicSort::m_index, MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicSongItem::m_sort, MusicSort::m_sortType, MStatic_cast, and readMusicFilePath().
Referenced by MusicPlayListManager::readLisList(), and MusicApplication::readXMLConfigFromText().
bool MusicXMLConfigManager::readMusicXMLConfig () inline
Read music datas from xml file by given name.
Definition at line 38 of file musicxmlconfigmanager.h.
References MUSICPATH_FULL, and MusicAbstractXml::readConfig().
Referenced by MusicApplication::readXMLConfigFromText().
QPoint MusicXMLConfigManager::readShowDLrcGeometry () const
Read Show Desktop Lrc Geometry Config.
Definition at line 336 of file musicxmlconfigmanager.cpp.
References MusicAbstractXml::readXmlAttributeByTagNameValue().
Referenced by MusicApplication::readXMLConfigFromText().
void MusicXMLConfigManager::readSysLoadConfig () const
Read Sys Load Config.
Definition at line 346 of file musicxmlconfigmanager.cpp.
References MusicSettingManager::AutoPlayChoiced, MusicSettingManager::BgListTransparentChoiced, MusicSettingManager::BgThemeChoiced, MusicSettingManager::BgTransparentChoiced, MusicSettingManager::BgTransparentEnableChoiced, MusicSettingManager::CloseEventChoiced, MusicSettingManager::CloseNetWorkChoiced, MusicSettingManager::CurrentLanIndexChoiced, MusicSettingManager::DLrcBgColorChoiced, MusicSettingManager::DLrcColorChoiced, MusicSettingManager::DLrcColorTransChoiced, MusicSettingManager::DLrcFamilyChoiced, MusicSettingManager::DLrcFgColorChoiced, MusicSettingManager::DLrcLockedChoiced, MusicSettingManager::DLrcSingleLineTypeChoiced, MusicSettingManager::DLrcSizeChoiced, MusicSettingManager::DLrcTypeChoiced, MusicSettingManager::DLrcWindowTypeChoiced, MusicSettingManager::DownloadCacheLimitChoiced, MusicSettingManager::DownloadCacheSizeChoiced, MusicSettingManager::DownloadDLoadLimitChoiced, MusicSettingManager::DownloadLimitChoiced, MusicSettingManager::DownloadLrcPathDirChoiced, MusicSettingManager::DownloadMusicPathDirChoiced, MusicSettingManager::DownloadServerChoiced, MusicSettingManager::DownloadULoadLimitChoiced, MusicSettingManager::EnhancedBalanceChoiced, MusicSettingManager::EnhancedBS2BChoiced, MusicSettingManager::EnhancedCrossfadeChoiced, MusicSettingManager::EnhancedFadeEnableChoiced, MusicSettingManager::EnhancedFadeInValueChoiced, MusicSettingManager::EnhancedFadeOutValueChoiced, MusicSettingManager::EnhancedLADSPAChoiced, MusicSettingManager::EnhancedMusicChoiced, MusicSettingManager::EnhancedSOXChoiced, MusicSettingManager::EnhancedStereoChoiced, MusicSettingManager::EqualizerEnableChoiced, MusicSettingManager::EqualizerIndexChoiced, MusicSettingManager::EqualizerValueChoiced, MusicSettingManager::FileAssociationChoiced, MusicSettingManager::HotkeyEnableChoiced, MusicSettingManager::HotkeyStringChoiced, MusicSettingManager::LrcBgColorChoiced, MusicSettingManager::LrcColorChoiced, MusicSettingManager::LrcColorTransChoiced, MusicSettingManager::LrcFamilyChoiced, MusicSettingManager::LrcFgColorChoiced, MusicUtils::Core::lrcPrefix(), MusicSettingManager::LrcSizeChoiced, MusicSettingManager::LrcTypeChoiced, M_SETTING_PTR, MusicUtils::Core::musicPrefix(), MusicSettingManager::OtherAlbumChoiced, MusicSettingManager::OtherBgLosslessChoiced, MusicSettingManager::OtherInfoChoiced, MusicSettingManager::OtherSearchChoiced, MusicSettingManager::OtherSideByChoiced, MusicSettingManager::OtherUpdateChoiced, MusicSettingManager::PlayModeChoiced, MusicAbstractXml::readXmlAttributeByTagNameValue(), MusicSettingManager::RemoteWidgetModeChoiced, MusicSettingManager::ShowDesktopLrcChoiced, MusicSettingManager::ShowInlineLrcChoiced, MusicSettingManager::TimerAutoIndexChoiced, MusicSettingManager::TimerAutoPlayChoiced, MusicSettingManager::TimerAutoPlayHourChoiced, MusicSettingManager::TimerAutoPlayItemIndexChoiced, MusicSettingManager::TimerAutoPlayRepeatChoiced, MusicSettingManager::TimerAutoPlaySecondChoiced, MusicSettingManager::TimerAutoPlaySongIndexChoiced, MusicSettingManager::TimerAutoShutdownChoiced, MusicSettingManager::TimerAutoShutdownHourChoiced, MusicSettingManager::TimerAutoShutdownRepeatChoiced, MusicSettingManager::TimerAutoShutdownSecondChoiced, MusicSettingManager::TimerAutoStopChoiced, MusicSettingManager::TimerAutoStopHourChoiced, MusicSettingManager::TimerAutoStopRepeatChoiced, MusicSettingManager::TimerAutoStopSecondChoiced, MusicSettingManager::VolumeChoiced, MusicSettingManager::WindowConciseChoiced, and MusicSettingManager::WindowQuitModeChoiced.
Referenced by MusicApplication::readXMLConfigFromText(), and MusicRunTimeManager::run().
void MusicXMLConfigManager::readSystemLastPlayIndexConfig (QStringList & key) const
Read System Last Play Index Config.
Definition at line 296 of file musicxmlconfigmanager.cpp.
References MusicAbstractXml::m_ddom.
Referenced by MusicApplication::readXMLConfigFromText().
QRect MusicXMLConfigManager::readWindowGeometry () const
Read window widget Geometry Config.
Definition at line 314 of file musicxmlconfigmanager.cpp.
References MusicAbstractXml::m_ddom, WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by MusicApplication::readXMLConfigFromText().
bool MusicXMLConfigManager::readXMLConfig () inline
Read config datas from xml file by given name.
Definition at line 34 of file musicxmlconfigmanager.h.
References COFIGPATH_FULL, and MusicAbstractXml::readConfig().
Referenced by MusicApplication::readXMLConfigFromText(), and MusicRunTimeManager::run().
void MusicXMLConfigManager::writeMusicSongsConfig (const MusicSongItems & musics, const QString & path = MUSICPATH_FULL)
Write music datas into xml file.
Definition at line 18 of file musicxmlconfigmanager.cpp.
References APPNAME, MusicAbstractXml::createProcessingInstruction(), MusicAbstractXml::createRoot(), MusicSong::getMusicName(), MusicSong::getMusicPath(), MusicSong::getMusicPlayCount(), MusicSong::getMusicTime(), MusicAbstractXml::m_ddom, MusicAbstractXml::m_file, MusicSort::m_index, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicSongItem::m_sort, MusicSort::m_sortType, MusicAbstractXml::writeConfig(), MusicAbstractXml::writeDomElementMutil(), and MusicAbstractXml::writeDomElementMutilText().
Referenced by MusicPlayListManager::writeLisList(), and MusicApplication::writeXMLConfigToText().
void MusicXMLConfigManager::writeXMLConfig ()
Write datas into xml file.
Definition at line 67 of file musicxmlconfigmanager.cpp.
References APPNAME, MusicSettingManager::AutoPlayChoiced, MusicSettingManager::BgListTransparentChoiced, MusicSettingManager::BgThemeChoiced, MusicSettingManager::BgTransparentChoiced, MusicSettingManager::BgTransparentEnableChoiced, MusicSettingManager::CloseEventChoiced, MusicSettingManager::CloseNetWorkChoiced, COFIGPATH_FULL, MusicAbstractXml::createProcessingInstruction(), MusicAbstractXml::createRoot(), MusicSettingManager::CurrentLanIndexChoiced, MusicSettingManager::DLrcBgColorChoiced, MusicSettingManager::DLrcColorChoiced, MusicSettingManager::DLrcColorTransChoiced, MusicSettingManager::DLrcFamilyChoiced, MusicSettingManager::DLrcFgColorChoiced, MusicSettingManager::DLrcGeometryChoiced, MusicSettingManager::DLrcLockedChoiced, MusicSettingManager::DLrcSingleLineTypeChoiced, MusicSettingManager::DLrcSizeChoiced, MusicSettingManager::DLrcTypeChoiced, MusicSettingManager::DLrcWindowTypeChoiced, MusicSettingManager::DownloadCacheLimitChoiced, MusicSettingManager::DownloadCacheSizeChoiced, MusicSettingManager::DownloadDLoadLimitChoiced, MusicSettingManager::DownloadLimitChoiced, MusicSettingManager::DownloadLrcPathDirChoiced, MusicSettingManager::DownloadMusicPathDirChoiced, MusicSettingManager::DownloadServerChoiced, MusicSettingManager::DownloadULoadLimitChoiced, MusicSettingManager::EnhancedBalanceChoiced, MusicSettingManager::EnhancedBS2BChoiced, MusicSettingManager::EnhancedCrossfadeChoiced, MusicSettingManager::EnhancedFadeEnableChoiced, MusicSettingManager::EnhancedFadeInValueChoiced, MusicSettingManager::EnhancedFadeOutValueChoiced, MusicSettingManager::EnhancedLADSPAChoiced, MusicSettingManager::EnhancedMusicChoiced, MusicSettingManager::EnhancedSOXChoiced, MusicSettingManager::EnhancedStereoChoiced, MusicSettingManager::EqualizerEnableChoiced, MusicSettingManager::EqualizerIndexChoiced, MusicSettingManager::EqualizerValueChoiced, MusicSettingManager::FileAssociationChoiced, MusicSettingManager::HotkeyEnableChoiced, MusicSettingManager::HotkeyStringChoiced, MusicSettingManager::LastPlayIndexChoiced, MusicSettingManager::LrcBgColorChoiced, MusicSettingManager::LrcColorChoiced, MusicSettingManager::LrcColorTransChoiced, MusicSettingManager::LrcFamilyChoiced, MusicSettingManager::LrcFgColorChoiced, MusicSettingManager::LrcSizeChoiced, MusicSettingManager::LrcTypeChoiced, MusicAbstractXml::m_ddom, MusicAbstractXml::m_file, M_SETTING_PTR, MusicSettingManager::OtherAlbumChoiced, MusicSettingManager::OtherBgLosslessChoiced, MusicSettingManager::OtherInfoChoiced, MusicSettingManager::OtherSearchChoiced, MusicSettingManager::OtherSideByChoiced, MusicSettingManager::OtherUpdateChoiced, MusicSettingManager::PlayModeChoiced, MusicSettingManager::RemoteWidgetModeChoiced, MusicSettingManager::ShowDesktopLrcChoiced, MusicSettingManager::ShowInlineLrcChoiced, MusicSettingManager::TimerAutoIndexChoiced, MusicSettingManager::TimerAutoPlayChoiced, MusicSettingManager::TimerAutoPlayHourChoiced, MusicSettingManager::TimerAutoPlayItemIndexChoiced, MusicSettingManager::TimerAutoPlayRepeatChoiced, MusicSettingManager::TimerAutoPlaySecondChoiced, MusicSettingManager::TimerAutoPlaySongIndexChoiced, MusicSettingManager::TimerAutoShutdownChoiced, MusicSettingManager::TimerAutoShutdownHourChoiced, MusicSettingManager::TimerAutoShutdownRepeatChoiced, MusicSettingManager::TimerAutoShutdownSecondChoiced, MusicSettingManager::TimerAutoStopChoiced, MusicSettingManager::TimerAutoStopHourChoiced, MusicSettingManager::TimerAutoStopRepeatChoiced, MusicSettingManager::TimerAutoStopSecondChoiced, MusicSettingManager::VolumeChoiced, MusicSettingManager::WidgetPosition, MusicSettingManager::WidgetSize, MusicSettingManager::WindowConciseChoiced, MusicSettingManager::WindowQuitModeChoiced, MusicAbstractXml::writeConfig(), MusicAbstractXml::writeDom(), MusicAbstractXml::writeDomElement(), and MusicAbstractXml::writeDomElementText().
Referenced by MusicApplication::writeXMLConfigToText().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicxmlconfigmanager.h
TTKModule/TTKCore/musicCoreKits/musicxmlconfigmanager.cpp