TTKMusicplayer: MusicDownloadBackgroundBingThread Class Reference
MusicDownloadBackgroundBingThread Class Reference
The class of download bing daily skin background.
#include <musicdownloadbackgroundremotethread.h>
Public Slots
virtual void downLoadDataFinished (const QByteArray &bytes) override
Public Slots inherited from MusicDownloadBackgroundRemoteThread
virtual void downLoadDataFinished (const QByteArray &bytes)=0
Public Member Functions
MusicDownloadBackgroundBingThread (QObject *parent=0)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownloadBackgroundRemoteThread
MusicDownloadBackgroundRemoteThread (QObject *parent=0)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownloadBackgroundRemoteThread
static QString getClassName ()
Additional Inherited Members
Signals inherited from MusicDownloadBackgroundRemoteThread
void downLoadDataChanged (const MusicSkinRemoteGroups &data)
Detailed Description
The class of download bing daily skin background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 160 of file musicdownloadbackgroundremotethread.h.
Constructor & Destructor Documentation
MusicDownloadBackgroundBingThread::MusicDownloadBackgroundBingThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 116 of file musicdownloadbackgroundremotethread.cpp.
Member Function Documentation
void MusicDownloadBackgroundBingThread::downLoadDataFinished (const QByteArray & bytes) override virtual slot
Download data from net finished.
Definition at line 134 of file musicdownloadbackgroundremotethread.cpp.
References BIGU_URL, MusicDownloadBackgroundRemoteThread::downLoadDataChanged(), MusicSkinRemoteItem::isValid(), MusicSkinRemoteGroup::isValid(), MusicSkinRemoteGroup::m_group, MusicSkinRemoteGroup::m_items, MusicSkinRemoteItem::m_name, MusicSkinRemoteItem::m_url, MusicSkinRemoteItem::m_useCount, MusicUtils::Algorithm::mdII(), MUSIC_DAILY_DIR, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicDownloadBackgroundBingThread::getClassName () static
Get class object name.
Definition at line 122 of file musicdownloadbackgroundremotethread.cpp.
void MusicDownloadBackgroundBingThread::startToDownload () override virtual
Start to download data from net.
Implements MusicDownloadBackgroundRemoteThread.
Definition at line 127 of file musicdownloadbackgroundremotethread.cpp.
References BING_URL, downLoadDataFinished(), MusicUtils::Algorithm::mdII(), and MusicDownloadSourceThread::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadbackgroundremotethread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadbackgroundremotethread.cpp