TTKMusicplayer: MusicKWArtistSimilarRequest Class Reference
MusicKWArtistSimilarRequest Class Reference
The class of query kuwo artist similar download data from net.
#include <musickwartistsimilarrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWArtistSimilarRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value) overridefinal
Public Member Functions inherited from MusicSimilarRequest
MusicSimilarRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Member Functions
QString artistNameById (const QString &id) const
QString artistIdName (const QString &name) const
Additional Inherited Members
Signals inherited from MusicSimilarRequest
void createSimilarItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of query kuwo artist similar download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickwartistsimilarrequest.h.
Constructor & Destructor Documentation
MusicKWArtistSimilarRequest::MusicKWArtistSimilarRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musickwartistsimilarrequest.cpp.
Member Function Documentation
QString MusicKWArtistSimilarRequest::artistIdName (const QString & name) const protected
Get id by artist name.
Definition at line 94 of file musickwartistsimilarrequest.cpp.
References KW_ARTIST_INFO_NAME_URL, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicObject::syncNetworkQueryForGet().
Referenced by downLoadFinished().
QString MusicKWArtistSimilarRequest::artistNameById (const QString & id) const protected
Get artist name by id.
Definition at line 64 of file musickwartistsimilarrequest.cpp.
References KW_ARTIST_INFO_URL, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), name, QJson::Parser::parse(), and MusicObject::syncNetworkQueryForGet().
Referenced by startToSearch().
void MusicKWArtistSimilarRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 29 of file musickwartistsimilarrequest.cpp.
References artistIdName(), MusicSimilarRequest::createSimilarItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicAbstractNetwork::m_reply, MusicResultsItem::m_updateTime, TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicKWArtistSimilarRequest::startToSearch (const QString & value) final override virtual
Start to Search data from name.
Implements MusicSimilarRequest.
Definition at line 10 of file musickwartistsimilarrequest.cpp.
References artistNameById(), MusicAbstractNetwork::deleteAll(), downLoadFinished(), KW_ARTIST_SIMILAR_URL, MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwartistsimilarrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwartistsimilarrequest.cpp