TTKMusicplayer: MusicBackgroundOnlineWidget Class Reference
MusicBackgroundOnlineWidget Class Reference
The class of the online background widget.
#include <musicbackgroundremotewidget.h>
Public Slots
void currentTypeChanged (int index)
virtual void downLoadFinished (const MusicSkinRemoteGroups &bytes) override
Public Slots inherited from MusicBackgroundRemoteWidget
void downLoadFinished (const QString &bytes)
virtual void downLoadFinished (const MusicSkinRemoteGroups &bytes)
Public Member Functions
MusicBackgroundOnlineWidget (QWidget *parent=nullptr)
~MusicBackgroundOnlineWidget ()
void initialize ()
QWidget * createFunctionsWidget (bool revert, QWidget *object=nullptr)
virtual void outputRemoteSkin (MusicBackgroundImage &image, const QString &data) override
Public Member Functions inherited from MusicBackgroundRemoteWidget
MusicBackgroundRemoteWidget (QWidget *parent=nullptr)
~MusicBackgroundRemoteWidget ()
void abort ()
Protected Attributes
QWidget * m_functionsWidget
QPushButton * m_allButton
QComboBox * m_typeBox
Protected Attributes inherited from MusicBackgroundRemoteWidget
int m_currentIndex
MusicSkinRemoteGroups m_groups
MusicBackgroundListWidget * m_backgroundList
MusicDownloadQueueRequest * m_downloadQueue
MusicAbstractDownloadSkinRequest * m_downloadRequest
Additional Inherited Members
Protected Member Functions inherited from MusicBackgroundRemoteWidget
void startToDownload (const QString &suffix)
Detailed Description
The class of the online background widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 116 of file musicbackgroundremotewidget.h.
Constructor & Destructor Documentation
MusicBackgroundOnlineWidget::MusicBackgroundOnlineWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 138 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundListWidget::Four, MusicBackgroundRemoteWidget::m_backgroundList, m_functionsWidget, and MusicBackgroundListWidget::setType().
MusicBackgroundOnlineWidget::~MusicBackgroundOnlineWidget ()
Definition at line 145 of file musicbackgroundremotewidget.cpp.
References m_functionsWidget.
Member Function Documentation
QWidget * MusicBackgroundOnlineWidget::createFunctionsWidget (bool revert, QWidget * object = nullptr)
Create functions widget.
Definition at line 169 of file musicbackgroundremotewidget.cpp.
References currentTypeChanged(), MusicUtils::Widget::generateComboBoxFormat(), m_allButton, m_functionsWidget, m_typeBox, MusicUIObject::MQSSColorStyle08, MusicUIObject::MQSSPushButtonStyle02, and TTKStatic_cast.
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundOnlineWidget::currentTypeChanged (int index) slot
Remote background type selected by index.
Definition at line 237 of file musicbackgroundremotewidget.cpp.
References MusicDownloadQueueRequest::abort(), MusicBackgroundRemoteWidget::m_currentIndex, MusicBackgroundRemoteWidget::m_downloadQueue, MusicBackgroundRemoteWidget::m_groups, MusicBackgroundRemoteWidget::startToDownload(), and TTS_FILE.
Referenced by createFunctionsWidget().
void MusicBackgroundOnlineWidget::downLoadFinished (const MusicSkinRemoteGroups & bytes) override virtual slot
Send download data from net.
Definition at line 254 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::downLoadFinished(), MusicBackgroundRemoteWidget::m_groups, m_typeBox, MUSIC_THUNDER_DIR, and TTK_STRCAT.
Referenced by initialize().
void MusicBackgroundOnlineWidget::initialize ()
Init parameters.
Definition at line 150 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundListWidget::clearAllItems(), downLoadFinished(), MusicBackgroundRemoteWidget::m_backgroundList, MusicBackgroundRemoteWidget::m_downloadRequest, m_typeBox, and MusicAbstractDownloadSkinRequest::startToDownload().
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundOnlineWidget::outputRemoteSkin (MusicBackgroundImage & image, const QString & data) override virtual
Output remote skin.
Implements MusicBackgroundRemoteWidget.
Definition at line 219 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::m_currentIndex, MusicBackgroundRemoteWidget::m_groups, MusicBackgroundImage::m_item, MusicSkinRemoteItem::m_name, MusicSkinConfigItem::m_name, MusicBackgroundImage::m_pix, MusicSkinRemoteItem::m_useCount, MusicSkinConfigItem::m_useCount, and MusicExtractWrapper::outputThunderSkin().
Member Data Documentation
QPushButton* MusicBackgroundOnlineWidget::m_allButton protected
Definition at line 153 of file musicbackgroundremotewidget.h.
Referenced by createFunctionsWidget().
QWidget* MusicBackgroundOnlineWidget::m_functionsWidget protected
Definition at line 152 of file musicbackgroundremotewidget.h.
Referenced by createFunctionsWidget(), MusicBackgroundOnlineWidget(), and ~MusicBackgroundOnlineWidget().
QComboBox* MusicBackgroundOnlineWidget::m_typeBox protected
Definition at line 154 of file musicbackgroundremotewidget.h.
Referenced by createFunctionsWidget(), downLoadFinished(), and initialize().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.cpp