TTKMusicPlayer: TTKSingleton< T > Class Template Reference
TTKSingleton< T > Class Template Reference
The class of the singleton base.
#include <ttksingleton.h>
Static Public Member Functions
static T * instance ()
Private Member Functions
TTKSingleton ()=default
~TTKSingleton ()=default
Static Private Attributes
static QMutex m_mutex
                                         //
Singleton Implementation // //
static QScopedPointer< T > m_instance
Detailed Description
template<typename T>
class TTKSingleton< T >
The class of the singleton base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttksingleton.h.
Constructor & Destructor Documentation
template<typename T > TTKSingleton< T >::TTKSingleton () private default
Object constructor.
template<typename T > TTKSingleton< T >::~TTKSingleton () private default
Object destructor.
Member Function Documentation
template<typename T > T * TTKSingleton< T >::instance () static
Get object instance ptr.
Definition at line 64 of file ttksingleton.h.
References T.
Referenced by TTK::installLogHandler(), TTKLogOutput::loggerHandler(), makeMusicBackgroundManager(), makeMusicConnectionPool(), makeMusicDispatchManager(), makeMusicDownLoadManager(), makeMusicDownLoadQueryFactory(), makeMusicHotKeyManager(), makeMusicNetworkThread(), makeMusicSettingManager(), makeMusicSingleManager(), and TTK::removeLogHandler().
Member Data Documentation
template<typename T > QScopedPointer< T > TTKSingleton< T >::m_instance static private
Definition at line 49 of file ttksingleton.h.
template<typename T > QMutex TTKSingleton< T >::m_mutex static private
                                         //
Singleton Implementation // //
Definition at line 48 of file ttksingleton.h.
The documentation for this class was generated from the following file:
TTKCommon/ttksingleton.h