TTKMusicplayer: MusicEnhancedPopWidget Class Reference
MusicEnhancedPopWidget Class Reference
The class of the enhanced pop widget.
#include <musicenhancedpopwidget.h>
Public Slots
void setEnhancedMusicConfig (int type)
void caseButtonOnAndOff ()
void buttonAnimationChanged (bool state)
void helpButtonClicked ()
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Signals
void enhancedMusicChanged (int type)
Public Member Functions
MusicEnhancedPopWidget (QWidget *parent=nullptr)
~MusicEnhancedPopWidget ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initialize ()
Protected Attributes
int m_lastSelectedIndex
QToolButton * m_caseButton
QList< MusicEnhancedToolButton * > m_buttons
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the enhanced pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 79 of file musicenhancedpopwidget.h.
Constructor & Destructor Documentation
MusicEnhancedPopWidget::MusicEnhancedPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 95 of file musicenhancedpopwidget.cpp.
References buttonAnimationChanged(), enhancedMusicChanged(), initialize(), MusicApplicationModule::instance(), MusicToolMenuWidget::m_menu, and setEnhancedMusicConfig().
MusicEnhancedPopWidget::~MusicEnhancedPopWidget ()
Definition at line 106 of file musicenhancedpopwidget.cpp.
References m_buttons, and m_caseButton.
Member Function Documentation
void MusicEnhancedPopWidget::buttonAnimationChanged (bool state) slot
Button animation state changed.
Definition at line 152 of file musicenhancedpopwidget.cpp.
References MusicSettingManager::EnhancedMusicIndex, G_SETTING_PTR, and m_buttons.
Referenced by MusicEnhancedPopWidget().
void MusicEnhancedPopWidget::caseButtonOnAndOff () slot
Case button on and off.
Definition at line 147 of file musicenhancedpopwidget.cpp.
References m_caseButton, m_lastSelectedIndex, and setEnhancedMusicConfig().
Referenced by initialize().
void MusicEnhancedPopWidget::enhancedMusicChanged (int type) signal
Set enhanced music config changed return selected index.
Referenced by MusicEnhancedPopWidget(), and setEnhancedMusicConfig().
void MusicEnhancedPopWidget::helpButtonClicked () slot
Help button clicked.
Definition at line 163 of file musicenhancedpopwidget.cpp.
References MusicRightAreaWidget::functionClicked(), MusicRightAreaWidget::instance(), MusicRightAreaWidget::KuiSheWidget, and MusicToolMenuWidget::m_menu.
Referenced by initialize().
void MusicEnhancedPopWidget::initialize () protected
Create all widget in layout.
Definition at line 169 of file musicenhancedpopwidget.cpp.
References caseButtonOnAndOff(), MusicSettingManager::EnhancedMusicIndex, G_SETTING_PTR, helpButtonClicked(), LABEL_BUTTON_HEIGHT, LABEL_BUTTON_WIDGET, m_buttons, m_caseButton, MusicToolMenuWidget::m_containWidget, m_lastSelectedIndex, MusicToolMenuWidget::m_menu, MusicUIObject::MQSSBorderStyle01, MusicUIObject::MQSSEnhanceClose, MusicUIObject::MQSSEnhanceHelp, MusicUIObject::MQSSEnhanceOn, MusicUIObject::MQSSEnhanceShare, MusicUIObject::MQSSEnhanceTitle, MusicUIObject::MQSSMenuStyle05, setEnhancedMusicConfig(), MusicEnhancedToolButton::setStyleSheet(), and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicEnhancedPopWidget().
void MusicEnhancedPopWidget::setEnhancedMusicConfig (int type) slot
Set enhanced music config.
Definition at line 112 of file musicenhancedpopwidget.cpp.
References MusicUtils::TTKQmmp::enabledEffectPlugin(), enhancedMusicChanged(), MusicSettingManager::EnhancedMusicIndex, MusicSettingManager::EqualizerEnable, G_SETTING_PTR, m_buttons, m_caseButton, m_lastSelectedIndex, MusicToolMenuWidget::m_menu, MusicUIObject::MQSSBtnMagic, MusicUIObject::MQSSEnhanceOff, and MusicUIObject::MQSSEnhanceOn.
Referenced by caseButtonOnAndOff(), initialize(), and MusicEnhancedPopWidget().
Member Data Documentation
QList<MusicEnhancedToolButton*> MusicEnhancedPopWidget::m_buttons protected
Definition at line 122 of file musicenhancedpopwidget.h.
Referenced by buttonAnimationChanged(), initialize(), setEnhancedMusicConfig(), and ~MusicEnhancedPopWidget().
QToolButton* MusicEnhancedPopWidget::m_caseButton protected
Definition at line 121 of file musicenhancedpopwidget.h.
Referenced by caseButtonOnAndOff(), initialize(), setEnhancedMusicConfig(), and ~MusicEnhancedPopWidget().
int MusicEnhancedPopWidget::m_lastSelectedIndex protected
Definition at line 120 of file musicenhancedpopwidget.h.
Referenced by caseButtonOnAndOff(), initialize(), and setEnhancedMusicConfig().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicenhancedpopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicenhancedpopwidget.cpp