TTKMusicplayer: MusicAdvancedSearchedWidget Class Reference
MusicAdvancedSearchedWidget Class Reference
The class of the advance search widget.
#include <musicadvancedsearchedwidget.h>
Public Member Functions
MusicAdvancedSearchedWidget (QWidget *parent=0)
virtual ~MusicAdvancedSearchedWidget ()
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
QWidget * createSearchPairWidget (MusicLocalSongSearchEdit **input)
void updateServerPlaceholderText ()
QString getSearchedKeyWork (int type, const QString &url)
Protected Attributes
QTabWidget * m_tabWidget
MusicLocalSongSearchEdit * m_songEdit
MusicLocalSongSearchEdit * m_artistEdit
MusicLocalSongSearchEdit * m_albumEdit
MusicLocalSongSearchEdit * m_playlistEdit
MusicLocalSongSearchEdit * m_movieEdit
Private Slots
void searchButtonClicked ()
Detailed Description
The class of the advance search widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicadvancedsearchedwidget.h.
Constructor & Destructor Documentation
MusicAdvancedSearchedWidget::MusicAdvancedSearchedWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 14 of file musicadvancedsearchedwidget.cpp.
References createSearchPairWidget(), m_albumEdit, m_artistEdit, m_movieEdit, m_playlistEdit, m_songEdit, m_tabWidget, MusicUIObject::MBackgroundStyle17, MusicUIObject::MFontStyle05, MusicUIObject::MPushButtonStyle03, MusicUIObject::MTabWidgetStyle01, searchButtonClicked(), and updateServerPlaceholderText().
MusicAdvancedSearchedWidget::~MusicAdvancedSearchedWidget () virtual
Definition at line 112 of file musicadvancedsearchedwidget.cpp.
References m_tabWidget.
Member Function Documentation
QWidget * MusicAdvancedSearchedWidget::createSearchPairWidget (MusicLocalSongSearchEdit ** input) protected
Create search pair widget.
Definition at line 175 of file musicadvancedsearchedwidget.cpp.
References MusicUIObject::MBackgroundStyle01, and MusicUIObject::MBorderStyle02.
Referenced by MusicAdvancedSearchedWidget().
QString MusicAdvancedSearchedWidget::getClassName () static
Get class object name.
Definition at line 117 of file musicadvancedsearchedwidget.cpp.
QString MusicAdvancedSearchedWidget::getSearchedKeyWork (int type, const QString & url) protected
Get search key.
Definition at line 264 of file musicadvancedsearchedwidget.cpp.
References MusicSettingManager::DownloadServerChoiced, key, and M_SETTING_PTR.
Referenced by searchButtonClicked().
void MusicAdvancedSearchedWidget::searchButtonClicked () private slot
Search button clicked.
Definition at line 123 of file musicadvancedsearchedwidget.cpp.
References MusicSettingManager::DownloadServerChoiced, MusicMessageBox::exec(), getSearchedKeyWork(), MusicRightAreaWidget::instance(), key, m_albumEdit, m_artistEdit, m_movieEdit, m_playlistEdit, M_SETTING_PTR, m_songEdit, m_tabWidget, MusicRightAreaWidget::musicAlbumFound(), MusicRightAreaWidget::musicArtistFound(), MusicRightAreaWidget::musicPlaylistFound(), MusicRightAreaWidget::musicSingleSearchedFound(), MusicRightAreaWidget::musicVideoButtonSearched(), and MusicMessageBox::setText().
Referenced by MusicAdvancedSearchedWidget().
void MusicAdvancedSearchedWidget::updateServerPlaceholderText () protected
Update placeholder text.
Definition at line 193 of file musicadvancedsearchedwidget.cpp.
References ALG_LOW_KEY, BD_AL_SHARE, BD_AR_SHARE, BD_MV_SHARE, BD_PL_SHARE, BD_SG_SHARE, MusicSettingManager::DownloadServerChoiced, KG_AL_SHARE, KG_AR_SHARE, KG_MV_SHARE, KG_PL_SHARE, KG_SG_SHARE, KW_AL_SHARE, KW_AR_SHARE, KW_MV_SHARE, KW_PL_SHARE, KW_SG_SHARE, m_albumEdit, m_artistEdit, m_movieEdit, m_playlistEdit, M_SETTING_PTR, m_songEdit, MusicUtils::Algorithm::mdII(), MG_AL_SHARE, MG_AR_SHARE, MG_MV_SHARE, MG_PL_SHARE, MG_SG_SHARE, QQ_AL_SHARE, QQ_AR_SHARE, QQ_MV_SHARE, QQ_PL_SHARE, QQ_SG_SHARE, WY_AL_SHARE, WY_AR_SHARE, WY_MV_SHARE, WY_PL_SHARE, WY_SG_SHARE, XM_AL_SHARE, XM_AR_SHARE, XM_MV_SHARE, XM_PL_SHARE, and XM_SG_SHARE.
Referenced by MusicAdvancedSearchedWidget().
Member Data Documentation
MusicLocalSongSearchEdit* MusicAdvancedSearchedWidget::m_albumEdit protected
Definition at line 68 of file musicadvancedsearchedwidget.h.
Referenced by MusicAdvancedSearchedWidget(), searchButtonClicked(), and updateServerPlaceholderText().
MusicLocalSongSearchEdit * MusicAdvancedSearchedWidget::m_artistEdit protected
Definition at line 67 of file musicadvancedsearchedwidget.h.
Referenced by MusicAdvancedSearchedWidget(), searchButtonClicked(), and updateServerPlaceholderText().
MusicLocalSongSearchEdit * MusicAdvancedSearchedWidget::m_movieEdit protected
Definition at line 68 of file musicadvancedsearchedwidget.h.
Referenced by MusicAdvancedSearchedWidget(), searchButtonClicked(), and updateServerPlaceholderText().
MusicLocalSongSearchEdit * MusicAdvancedSearchedWidget::m_playlistEdit protected
Definition at line 68 of file musicadvancedsearchedwidget.h.
Referenced by MusicAdvancedSearchedWidget(), searchButtonClicked(), and updateServerPlaceholderText().
MusicLocalSongSearchEdit* MusicAdvancedSearchedWidget::m_songEdit protected
Definition at line 67 of file musicadvancedsearchedwidget.h.
Referenced by MusicAdvancedSearchedWidget(), searchButtonClicked(), and updateServerPlaceholderText().
QTabWidget* MusicAdvancedSearchedWidget::m_tabWidget protected
Definition at line 66 of file musicadvancedsearchedwidget.h.
Referenced by MusicAdvancedSearchedWidget(), searchButtonClicked(), and ~MusicAdvancedSearchedWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicadvancedsearchedwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicadvancedsearchedwidget.cpp