TTKMusicplayer: MusicSongItemSelectedDialog Class Reference
MusicSongItemSelectedDialog Class Reference
The class of the song item selected dialog widget.
#include <musicsongitemselectedareawidget.h>
Public Slots
void confirmButtonClicked ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void itemListChanged (const TTKIntList &items)
Public Member Functions
MusicSongItemSelectedDialog (QWidget *parent=nullptr)
~MusicSongItemSelectedDialog ()
void createAllItems (MusicSongItems *items)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicSongItemSelectedDialog * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the song item selected dialog widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 63 of file musicsongitemselectedareawidget.h.
Constructor & Destructor Documentation
MusicSongItemSelectedDialog::MusicSongItemSelectedDialog (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 88 of file musicsongitemselectedareawidget.cpp.
References confirmButtonClicked(), m_ui, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSPushButtonStyle04, and MusicUIObject::MQSSToolButtonStyle04.
MusicSongItemSelectedDialog::~MusicSongItemSelectedDialog ()
Definition at line 112 of file musicsongitemselectedareawidget.cpp.
References m_ui.
Member Function Documentation
void MusicSongItemSelectedDialog::confirmButtonClicked () slot
Confirm button clicked.
Definition at line 122 of file musicsongitemselectedareawidget.cpp.
References itemListChanged(), and m_ui.
Referenced by MusicSongItemSelectedDialog().
void MusicSongItemSelectedDialog::createAllItems (MusicSongItems * items)
Create all items.
Definition at line 117 of file musicsongitemselectedareawidget.cpp.
References m_ui.
Referenced by MusicSongItemSelectedAreaWidget::modifiedItemButtonClicked().
int MusicSongItemSelectedDialog::exec () virtual slot
Override exec function.
Definition at line 128 of file musicsongitemselectedareawidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicSongItemSelectedAreaWidget::modifiedItemButtonClicked().
void MusicSongItemSelectedDialog::itemListChanged (const TTKIntList & items) signal
Item list changed.
Referenced by confirmButtonClicked().
Member Data Documentation
Ui::MusicSongItemSelectedDialog* MusicSongItemSelectedDialog::m_ui protected
Definition at line 96 of file musicsongitemselectedareawidget.h.
Referenced by confirmButtonClicked(), createAllItems(), exec(), MusicSongItemSelectedDialog(), and ~MusicSongItemSelectedDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicsongitemselectedareawidget.h
TTKModule/TTKWidget/musicCoreKits/musicsongitemselectedareawidget.cpp