TTKMusicPlayer: QJson::ParserRunnable Class Reference
QJson::ParserRunnable Class Reference
Convenience class for converting JSON data to QVariant objects using a dedicated thread.
#include <parserrunnable.h>
Classes
class ParserRunnablePrivate
Convenience class for converting JSON data to QVariant objects using a dedicated thread private.
Signals
void parsingFinished (const QVariant &json, bool ok, const QString &error_msg)
This signal is emitted when the parsing process has been completed.
Public Member Functions
ParserRunnable (QObject *parent=nullptr)
void setData (const QByteArray &data)
void run ()
Detailed Description
Convenience class for converting JSON data to QVariant objects using a dedicated thread.
Definition at line 37 of file parserrunnable.h.
Constructor & Destructor Documentation
ParserRunnable::ParserRunnable (QObject * parent = nullptr) explicit
Definition at line 38 of file parserrunnable.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
void QJson::ParserRunnable::parsingFinished (const QVariant & json, bool ok, const QString & error_msg) signal
This signal is emitted when the parsing process has been completed.
Parameters
json contains the result of the parsing
ok if a parsing error occurs ok is set to false, otherwise it's set to true.
error_msg contains a string explaining the failure reason
Referenced by run().
void ParserRunnable::run ()
Definition at line 52 of file parserrunnable.cpp.
References QJson::Parser::errorString(), QJson::Parser::parse(), parsingFinished(), TTK_D, TTK_ERROR_STREAM, and TTK_INFO_STREAM.
void ParserRunnable::setData (const QByteArray & data)
Definition at line 46 of file parserrunnable.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/parserrunnable.h
TTKThirdParty/TTKExtras/qjson/parserrunnable.cpp