TTKMusicPlayer: ToolsUrl Class Reference
ToolsUrl Class Reference
#include <toolsurl.h>
Public Member Functions
ToolsUrl (QWidget *parent=nullptr)
~ToolsUrl ()
Private Slots
void encodeClicked ()
void decodeClicked ()
Private Attributes
Ui::ToolsUrl * m_ui
Detailed Description
Definition at line 28 of file toolsurl.h.
Constructor & Destructor Documentation
ToolsUrl::ToolsUrl (QWidget * parent = nullptr) explicit
Definition at line 5 of file toolsurl.cpp.
References decodeClicked(), encodeClicked(), and m_ui.
ToolsUrl::~ToolsUrl ()
Definition at line 18 of file toolsurl.cpp.
References m_ui.
Member Function Documentation
void ToolsUrl::decodeClicked () private slot
Definition at line 36 of file toolsurl.cpp.
References ALG_URL_KEY, key, m_ui, and TTK::Algorithm::mdII().
Referenced by ToolsUrl().
void ToolsUrl::encodeClicked () private slot
Definition at line 23 of file toolsurl.cpp.
References ALG_URL_KEY, key, m_ui, and TTK::Algorithm::mdII().
Referenced by ToolsUrl().
Member Data Documentation
Ui::ToolsUrl* ToolsUrl::m_ui private
Definition at line 40 of file toolsurl.h.
Referenced by decodeClicked(), encodeClicked(), ToolsUrl(), and ~ToolsUrl().
The documentation for this class was generated from the following files:
TTKRun/TTKTools/GenerateUrl/toolsurl.h
TTKRun/TTKTools/GenerateUrl/toolsurl.cpp