TTKMusicplayer: TTKThirdParty/Zlib/ttkzip/iowin32.c File Reference
iowin32.c File Reference
#include <stdlib.h>
#include "zlib/zlib.h"
#include "ioapi.h"
#include "iowin32.h"
Classes
struct WIN32FILE_IOWIN
Macros
#define INVALID_HANDLE_VALUE (0xFFFFFFFF)
#define INVALID_SET_FILE_POINTER ((DWORD)-1)
Functions
voidpf ZCALLBACK win32_open_file_func OF ((voidpf opaque, const char *filename, int mode))
uLong ZCALLBACK win32_read_file_func OF ((voidpf opaque, voidpf stream, void *buf, uLong size))
uLong ZCALLBACK win32_write_file_func OF ((voidpf opaque, voidpf stream, const void *buf, uLong size))
ZPOS64_T ZCALLBACK win32_tell64_file_func OF ((voidpf opaque, voidpf stream))
long ZCALLBACK win32_seek64_file_func OF ((voidpf opaque, voidpf stream, ZPOS64_T offset, int origin))
static void win32_translate_open_mode (int mode, DWORD *lpdwDesiredAccess, DWORD *lpdwCreationDisposition, DWORD *lpdwShareMode, DWORD *lpdwFlagsAndAttributes)
static voidpf win32_build_iowin (HANDLE hFile)
voidpf ZCALLBACK win32_open64_file_func (voidpf opaque, const void *filename, int mode)
voidpf ZCALLBACK win32_open64_file_funcA (voidpf opaque, const void *filename, int mode)
voidpf ZCALLBACK win32_open64_file_funcW (voidpf opaque, const void *filename, int mode)
voidpf ZCALLBACK win32_open_file_func (voidpf opaque, const char *filename, int mode)
uLong ZCALLBACK win32_read_file_func (voidpf opaque, voidpf stream, void *buf, uLong size)
uLong ZCALLBACK win32_write_file_func (voidpf opaque, voidpf stream, const void *buf, uLong size)
static BOOL MySetFilePointerEx (HANDLE hFile, LARGE_INTEGER pos, LARGE_INTEGER *newPos, DWORD dwMoveMethod)
long ZCALLBACK win32_tell_file_func (voidpf opaque, voidpf stream)
ZPOS64_T ZCALLBACK win32_tell64_file_func (voidpf opaque, voidpf stream)
long ZCALLBACK win32_seek_file_func (voidpf opaque, voidpf stream, uLong offset, int origin)
long ZCALLBACK win32_seek64_file_func (voidpf opaque, voidpf stream, ZPOS64_T offset, int origin)
int ZCALLBACK win32_close_file_func (voidpf opaque, voidpf stream)
int ZCALLBACK win32_error_file_func (voidpf opaque, voidpf stream)
void fill_win32_filefunc (zlib_filefunc_def *pzlib_filefunc_def)
void fill_win32_filefunc64 (zlib_filefunc64_def *pzlib_filefunc_def)
void fill_win32_filefunc64A (zlib_filefunc64_def *pzlib_filefunc_def)
void fill_win32_filefunc64W (zlib_filefunc64_def *pzlib_filefunc_def)
Macro Definition Documentation
#define INVALID_HANDLE_VALUE (0xFFFFFFFF)
Definition at line 21 of file iowin32.c.
Referenced by MusicDeviceInfoModule::disksProperty(), and win32_build_iowin().
#define INVALID_SET_FILE_POINTER ((DWORD)-1)
Definition at line 25 of file iowin32.c.
Function Documentation
void fill_win32_filefunc (zlib_filefunc_def * pzlib_filefunc_def)
Definition at line 414 of file iowin32.c.
References zlib_filefunc_def_s::opaque, win32_close_file_func(), win32_error_file_func(), win32_open_file_func(), win32_read_file_func(), win32_seek_file_func(), win32_tell_file_func(), win32_write_file_func(), zlib_filefunc_def_s::zclose_file, zlib_filefunc_def_s::zerror_file, zlib_filefunc_def_s::zopen_file, zlib_filefunc_def_s::zread_file, zlib_filefunc_def_s::zseek_file, zlib_filefunc_def_s::ztell_file, and zlib_filefunc_def_s::zwrite_file.
void fill_win32_filefunc64 (zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 426 of file iowin32.c.
References zlib_filefunc64_def_s::opaque, win32_close_file_func(), win32_error_file_func(), win32_open64_file_func(), win32_read_file_func(), win32_seek64_file_func(), win32_tell64_file_func(), win32_write_file_func(), zlib_filefunc64_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_def_s::ztell64_file, and zlib_filefunc64_def_s::zwrite_file.
void fill_win32_filefunc64A (zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 439 of file iowin32.c.
References zlib_filefunc64_def_s::opaque, win32_close_file_func(), win32_error_file_func(), win32_open64_file_funcA(), win32_read_file_func(), win32_seek64_file_func(), win32_tell64_file_func(), win32_write_file_func(), zlib_filefunc64_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_def_s::ztell64_file, and zlib_filefunc64_def_s::zwrite_file.
void fill_win32_filefunc64W (zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 452 of file iowin32.c.
References zlib_filefunc64_def_s::opaque, win32_close_file_func(), win32_error_file_func(), win32_open64_file_funcW(), win32_read_file_func(), win32_seek64_file_func(), win32_tell64_file_func(), win32_write_file_func(), zlib_filefunc64_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_def_s::ztell64_file, and zlib_filefunc64_def_s::zwrite_file.
static BOOL MySetFilePointerEx (HANDLE hFile, LARGE_INTEGER pos, LARGE_INTEGER * newPos, DWORD dwMoveMethod) static
Definition at line 241 of file iowin32.c.
Referenced by win32_seek64_file_func(), win32_seek_file_func(), win32_tell64_file_func(), and win32_tell_file_func().
voidpf ZCALLBACK win32_open_file_func OF ((voidpf opaque, const char *filename, int mode))
uLong ZCALLBACK win32_read_file_func OF ((voidpf opaque, voidpf stream, void *buf, uLong size))
uLong ZCALLBACK win32_write_file_func OF ((voidpf opaque, voidpf stream, const void *buf, uLong size))
ZPOS64_T ZCALLBACK win32_tell64_file_func OF ((voidpf opaque, voidpf stream))
long ZCALLBACK win32_seek64_file_func OF ((voidpf opaque, voidpf stream, ZPOS64_T offset, int origin))
static voidpf win32_build_iowin (HANDLE hFile) static
Definition at line 77 of file iowin32.c.
References WIN32FILE_IOWIN::error, WIN32FILE_IOWIN::hf, and INVALID_HANDLE_VALUE.
Referenced by win32_open64_file_func(), win32_open64_file_funcA(), win32_open64_file_funcW(), and win32_open_file_func().
int ZCALLBACK win32_close_file_func (voidpf opaque, voidpf stream)
Definition at line 386 of file iowin32.c.
Referenced by fill_win32_filefunc(), fill_win32_filefunc64(), fill_win32_filefunc64A(), and fill_win32_filefunc64W().
int ZCALLBACK win32_error_file_func (voidpf opaque, voidpf stream)
Definition at line 404 of file iowin32.c.
Referenced by fill_win32_filefunc(), fill_win32_filefunc64(), fill_win32_filefunc64A(), and fill_win32_filefunc64W().
voidpf ZCALLBACK win32_open64_file_func (voidpf opaque, const void * filename, int mode)
Definition at line 96 of file iowin32.c.
References win32_build_iowin(), and win32_translate_open_mode().
Referenced by fill_win32_filefunc64().
voidpf ZCALLBACK win32_open64_file_funcA (voidpf opaque, const void * filename, int mode)
Definition at line 125 of file iowin32.c.
References win32_build_iowin(), and win32_translate_open_mode().
Referenced by fill_win32_filefunc64A().
voidpf ZCALLBACK win32_open64_file_funcW (voidpf opaque, const void * filename, int mode)
Definition at line 149 of file iowin32.c.
References win32_build_iowin(), and win32_translate_open_mode().
Referenced by fill_win32_filefunc64W().
voidpf ZCALLBACK win32_open_file_func (voidpf opaque, const char * filename, int mode)
Definition at line 169 of file iowin32.c.
References win32_build_iowin(), and win32_translate_open_mode().
Referenced by fill_win32_filefunc().
uLong ZCALLBACK win32_read_file_func (voidpf opaque, voidpf stream, void * buf, uLong size)
Definition at line 198 of file iowin32.c.
References int().
Referenced by fill_win32_filefunc(), fill_win32_filefunc64(), fill_win32_filefunc64A(), and fill_win32_filefunc64W().
long ZCALLBACK win32_seek64_file_func (voidpf opaque, voidpf stream, ZPOS64_T offset, int origin)
Definition at line 347 of file iowin32.c.
References int(), MySetFilePointerEx(), ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_win32_filefunc64(), fill_win32_filefunc64A(), and fill_win32_filefunc64W().
long ZCALLBACK win32_seek_file_func (voidpf opaque, voidpf stream, uLong offset, int origin)
Definition at line 309 of file iowin32.c.
References int(), MySetFilePointerEx(), ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_win32_filefunc().
ZPOS64_T ZCALLBACK win32_tell64_file_func (voidpf opaque, voidpf stream)
Definition at line 284 of file iowin32.c.
References int(), and MySetFilePointerEx().
Referenced by fill_win32_filefunc64(), fill_win32_filefunc64A(), and fill_win32_filefunc64W().
long ZCALLBACK win32_tell_file_func (voidpf opaque, voidpf stream)
Definition at line 261 of file iowin32.c.
References int(), long(), and MySetFilePointerEx().
Referenced by fill_win32_filefunc().
static void win32_translate_open_mode (int mode, DWORD * lpdwDesiredAccess, DWORD * lpdwCreationDisposition, DWORD * lpdwShareMode, DWORD * lpdwFlagsAndAttributes) static
Definition at line 51 of file iowin32.c.
References ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, and ZLIB_FILEFUNC_MODE_READWRITEFILTER.
Referenced by win32_open64_file_func(), win32_open64_file_funcA(), win32_open64_file_funcW(), and win32_open_file_func().
uLong ZCALLBACK win32_write_file_func (voidpf opaque, voidpf stream, const void * buf, uLong size)
Definition at line 220 of file iowin32.c.
References int().
Referenced by fill_win32_filefunc(), fill_win32_filefunc64(), fill_win32_filefunc64A(), and fill_win32_filefunc64W().