TTKMusicPlayer: MusicFMConfigManager Class Reference
MusicFMConfigManager Class Reference
The class of the fm config manager.
#include <musicttkfmradioplaywidget.h>
Public Member Functions
MusicFMConfigManager (QObject *parent=nullptr)
void readBuffer (MusicFMCategoryList &items)
void writeBuffer (const MusicFMCategoryList &items)
Public Member Functions inherited from TTKXmlDocument
TTKXmlDocument (QObject *parent=nullptr)
~TTKXmlDocument ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
bool toFile (const QString &name)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readXmlTextByTagName (const QString &tagName) const
TTKXmlAttributeList readXmlAttributesByTagName (const QString &tagName) const
QStringList readXmlMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readXmlMultiTextByTagName (const QString &tagName) const
TTKXmlAttributesList readXmlMultiAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const TTKXmlAttribute &attr)
QDomElement createRoot (const QString &node, const TTKXmlAttributeList &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr)
QDomElement writeDomMutilElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const TTKXmlAttribute &attr, const QString &text)
QDomElement writeDomMutilElementText (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const TTKXmlAttribute &attr)
Additional Inherited Members
Protected Attributes inherited from TTKXmlDocument
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the fm config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 60 of file musicttkfmradioplaywidget.h.
Constructor & Destructor Documentation
MusicFMConfigManager::MusicFMConfigManager (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicttkfmradioplaywidget.cpp.
Member Function Documentation
void MusicFMConfigManager::readBuffer (MusicFMCategoryList & items)
Read datas from config file.
Definition at line 17 of file musicttkfmradioplaywidget.cpp.
References MusicFMCategory::m_category, TTKXmlDocument::m_document, MusicFMCategory::m_items, MusicFMChannel::m_location, MusicFMChannel::m_name, and MusicFMChannel::m_url.
Referenced by MusicTTKFMRadioPlayWidget::initialize().
void MusicFMConfigManager::writeBuffer (const MusicFMCategoryList & items)
Write datas from config file.
Definition at line 41 of file musicttkfmradioplaywidget.cpp.
References APP_NAME, TTKXmlDocument::createProcessingInstruction(), TTKXmlDocument::createRoot(), FMRADIO_PATH_FULL, MusicFMCategory::m_category, TTKXmlDocument::m_document, TTKXmlDocument::m_file, MusicFMCategory::m_items, TTKXmlDocument::toFile(), TTKXmlDocument::writeDomElement(), and TTKXmlDocument::writeDomMutilElement().
Referenced by MusicTTKFMRadioPlayWidget::addButtonClicked(), and MusicTTKFMRadioPlayWidget::deleteButtonClicked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicttkfmradioplaywidget.h
TTKModule/TTKWidget/musicToolsKits/musicttkfmradioplaywidget.cpp