TTKMusicplayer: MusicRadioChannelThread Class Reference
MusicRadioChannelThread Class Reference
The class of music radio thread of song channel.
#include <musicradiochannelthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicRadioChannelThread (QObject *parent=0, QNetworkCookieJar *cookie=0)
QJson import.
virtual ~MusicRadioChannelThread ()
virtual void startToDownload (const QString &id) override
const MusicRadioChannelInfos & getMusicChannel () const
Public Member Functions inherited from MusicRadioThreadAbstract
MusicRadioThreadAbstract (QObject *parent=0, QNetworkCookieJar *cookie=0)
virtual ~MusicRadioThreadAbstract ()
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Protected Attributes
MusicRadioChannelInfos m_channels
Protected Attributes inherited from MusicRadioThreadAbstract
QNetworkCookieJar * m_cookJar
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicNetwork::StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Detailed Description
The class of music radio thread of song channel.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicradiochannelthread.h.
Constructor & Destructor Documentation
MusicRadioChannelThread::MusicRadioChannelThread (QObject * parent = 0, QNetworkCookieJar * cookie = 0) explicit
QJson import.
Object contsructor.
Definition at line 9 of file musicradiochannelthread.cpp.
MusicRadioChannelThread::~MusicRadioChannelThread () virtual
Definition at line 15 of file musicradiochannelthread.cpp.
References MusicNetworkAbstract::deleteAll().
Member Function Documentation
void MusicRadioChannelThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 42 of file musicradiochannelthread.cpp.
References MusicNetworkAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), m_channels, MusicRadioChannelInfo::m_coverUrl, MusicRadioChannelInfo::m_id, MusicRadioChannelInfo::m_name, MusicNetworkAbstract::m_reply, and QJson::Parser::parse().
Referenced by startToDownload().
const MusicRadioChannelInfos& MusicRadioChannelThread::getMusicChannel () const inline
Get music channel.
Definition at line 57 of file musicradiochannelthread.h.
Referenced by MusicWebMusicRadioWidget::addListWidgetItem(), and MusicWebMusicRadioWidget::listCellDoubleClicked().
void MusicRadioChannelThread::startToDownload (const QString & id) override virtual
Start to download data.
Implements MusicRadioThreadAbstract.
Definition at line 20 of file musicradiochannelthread.cpp.
References downLoadFinished(), MusicRadioThreadAbstract::m_cookJar, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::mdII(), RADIO_CHANNEL_URL, MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), and MusicNetworkAbstract::sslErrors().
Referenced by MusicWebMusicRadioWidget::initListItems().
Member Data Documentation
MusicRadioChannelInfos MusicRadioChannelThread::m_channels protected
Definition at line 66 of file musicradiochannelthread.h.
Referenced by downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicradiochannelthread.h
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicradiochannelthread.cpp