TTKMusicplayer: EqSettings Class Reference
EqSettings Class Reference
The EqSettings class helps to work with equalizer settings.
#include <eqsettings.h>
Public Types
enum BANDS {
EQ_BANDS_10 = 10, EQ_BANDS_15 = 15, EQ_BANDS_25 = 25, EQ_BANDS_31 = 31,
EQ_BANDS_10 = 10, EQ_BANDS_15 = 15, EQ_BANDS_25 = 25, EQ_BANDS_31 = 31
}
enum BANDS {
EQ_BANDS_10 = 10, EQ_BANDS_15 = 15, EQ_BANDS_25 = 25, EQ_BANDS_31 = 31,
EQ_BANDS_10 = 10, EQ_BANDS_15 = 15, EQ_BANDS_25 = 25, EQ_BANDS_31 = 31
}
Public Member Functions
EqSettings (int bands=EQ_BANDS_10)
bool isEnabled () const
double gain (int chan) const
double preamp () const
int bands () const
void setEnabled (bool enabled=true)
void setGain (int band, double gain)
void setPreamp (double preamp)
void operator= (const EqSettings &s)
bool operator== (const EqSettings &s) const
bool operator!= (const EqSettings &s) const
EqSettings (int bands=EQ_BANDS_10)
bool isEnabled () const
double gain (int chan) const
double preamp () const
int bands () const
void setEnabled (bool enabled=true)
void setGain (int band, double gain)
void setPreamp (double preamp)
void operator= (const EqSettings &s)
bool operator== (const EqSettings &s) const
bool operator!= (const EqSettings &s) const
Private Attributes
double m_gains [31]
double m_preamp
bool m_is_enabled
int m_bands
Detailed Description
The EqSettings class helps to work with equalizer settings.
Author
Ilya Kotov forko.nosp@m.tov0.nosp@m.2@hot.nosp@m.mail.nosp@m..ru
Definition at line 27 of file eqsettings.h.
Member Enumeration Documentation
enum EqSettings::BANDS
Equalizer bands number
Enumerator
EQ_BANDS_10
10 bands
EQ_BANDS_15
15 bands
EQ_BANDS_25
25 bands
EQ_BANDS_31
31 bands
EQ_BANDS_10
10 bands
EQ_BANDS_15
15 bands
EQ_BANDS_25
25 bands
EQ_BANDS_31
31 bands
Definition at line 80 of file eqsettings.h.
enum EqSettings::BANDS
Equalizer bands number
Enumerator
EQ_BANDS_10
10 bands
EQ_BANDS_15
15 bands
EQ_BANDS_25
25 bands
EQ_BANDS_31
31 bands
EQ_BANDS_10
10 bands
EQ_BANDS_15
15 bands
EQ_BANDS_25
25 bands
EQ_BANDS_31
31 bands
Definition at line 82 of file eqsettings.h.
Constructor & Destructor Documentation
EqSettings::EqSettings (int bands = EQ_BANDS_10)
Constructs an empty equalizer settings (0 dB, disabled)
Parameters
bands - Number of bands (supported: 10, 15, 25, 31)
EqSettings::EqSettings (int bands = EQ_BANDS_10)
Constructs an empty equalizer settings (0 dB, disabled)
Parameters
bands - Number of bands (supported: 10, 15, 25, 31)
Member Function Documentation
int EqSettings::bands () const
Returns number of bands
int EqSettings::bands () const
Returns number of bands
double EqSettings::gain (int chan) const
Returns gain of the channel number chan.
double EqSettings::gain (int chan) const
Returns gain of the channel number chan.
bool EqSettings::isEnabled () const
Returns true if equalizer os enabled, otherwise returns false.
bool EqSettings::isEnabled () const
Returns true if equalizer os enabled, otherwise returns false.
bool EqSettings::operator!= (const EqSettings & s) const
Returns true if equalizer settins s is not equal to this settings; otherwise returns false.
bool EqSettings::operator!= (const EqSettings & s) const
Returns true if equalizer settins s is not equal to this settings; otherwise returns false.
void EqSettings::operator= (const EqSettings & s)
Assigns equalizer settings s to this settings.
void EqSettings::operator= (const EqSettings & s)
Assigns equalizer settings s to this settings.
bool EqSettings::operator== (const EqSettings & s) const
Returns true if equalizer settins s is equal to this settings; otherwise returns false.
bool EqSettings::operator== (const EqSettings & s) const
Returns true if equalizer settins s is equal to this settings; otherwise returns false.
double EqSettings::preamp () const
Returns equalizer preamp.
double EqSettings::preamp () const
Returns equalizer preamp.
void EqSettings::setEnabled (bool enabled = true)
Enables equalizer if enabled is true or disables it if enabled is false.
Referenced by MusicPlayer::setEqEffect().
void EqSettings::setEnabled (bool enabled = true)
Enables equalizer if enabled is true or disables it if enabled is false.
void EqSettings::setGain (int band, double gain)
Sets gain of the equalizer channel.
Parameters
band Number of equalizer band.
gain Channel gain (-20.0..20.0 dB)
Referenced by MusicPlayer::setEqEffect().
void EqSettings::setGain (int band, double gain)
Sets gain of the equalizer channel.
Parameters
band Number of equalizer band.
gain Channel gain (-20.0..20.0 dB)
void EqSettings::setPreamp (double preamp)
Sets equalizer preamp to preamp.
Referenced by MusicPlayer::setEqEffect().
void EqSettings::setPreamp (double preamp)
Sets equalizer preamp to preamp.
Member Data Documentation
int EqSettings::m_bands private
Definition at line 92 of file eqsettings.h.
double EqSettings::m_gains private
Definition at line 89 of file eqsettings.h.
bool EqSettings::m_is_enabled private
Definition at line 91 of file eqsettings.h.
double EqSettings::m_preamp private
Definition at line 90 of file eqsettings.h.
The documentation for this class was generated from the following file:
TTKExtra/Qt4/eqsettings.h