TTKMusicPlayer: MusicExtractManager Class Reference
MusicExtractManager Class Reference
The class of the extract data manager.
#include <musicextractmanager.h>
Static Public Member Functions
static bool outputThunderSkin (QPixmap &image, const QString &input)
static bool outputBinary (const QString &input, const QString &output, QStringList &path)
static bool outputSkin (MusicBackgroundImage *image, const QString &input)
static bool inputSkin (MusicBackgroundImage *image, const QString &output)
static bool outputData (QByteArray &data, const QString &input)
static bool inputData (const QByteArray &data, const QString &output)
Detailed Description
The class of the extract data manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicextractmanager.h.
Member Function Documentation
bool MusicExtractManager::inputData (const QByteArray & data, const QString & output) static
Transfer data to file.
Definition at line 320 of file musicextractmanager.cpp.
References zip_fileinfo::external_fa, FILE_ATTRIBUTE_ARCHIVE, qPrintable, TTK_ERROR_STREAM, Z_DEFLATED, zipClose(), zipCloseFileInZip(), zipOpen64(), zipOpenNewFileInZip(), and zipWriteInFileInZip().
bool MusicExtractManager::inputSkin (MusicBackgroundImage * image, const QString & output) static
Transfer image data to file.
Definition at line 232 of file musicextractmanager.cpp.
References zip_fileinfo::external_fa, FILE_ATTRIBUTE_ARCHIVE, TTK::Image::generatePixmapData(), TTKAbstractXml::load(), MusicBackgroundImage::m_item, MusicBackgroundImage::m_pix, qPrintable, SKN_FILE, TTKAbstractXml::toByteArray(), TTK_IMAGE_FILE, MusicSkinConfigManager::writeBuffer(), XML_FILE, Z_DEFLATED, zipClose(), zipCloseFileInZip(), zipOpen64(), zipOpenNewFileInZip(), and zipWriteInFileInZip().
Referenced by MusicBackgroundSkinDialog::cpoyFileToLocal(), MusicBackgroundSkinDialog::listWidgetItemClicked(), and ToolSkin::writeClicked().
bool MusicExtractManager::outputBinary (const QString & input, const QString & output, QStringList & path) static
Transfer file to normal data.
Definition at line 78 of file musicextractmanager.cpp.
References unz_file_info64_s::external_fa, FILE_ATTRIBUTE_DIRECTORY, name, unz_global_info64_s::number_entry, qPrintable, TTK_HIGH_BUFFER, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
bool MusicExtractManager::outputData (QByteArray & data, const QString & input) static
Transfer file to data.
Definition at line 266 of file musicextractmanager.cpp.
References name, unz_global_info64_s::number_entry, qPrintable, TTK_HIGH_BUFFER, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
bool MusicExtractManager::outputSkin (MusicBackgroundImage * image, const QString & input) static
Transfer file to image data.
Definition at line 149 of file musicextractmanager.cpp.
References TTKAbstractXml::fromByteArray(), MusicBackgroundImage::m_item, MusicBackgroundImage::m_pix, name, unz_global_info64_s::number_entry, qPrintable, MusicSkinConfigManager::readBuffer(), SKN_FILE, TTK_HIGH_BUFFER, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), WIN_NAME_MAX_LENGTH, and XML_FILE.
Referenced by MusicLrcPosterItemWidget::MusicLrcPosterItemWidget(), ToolSkin::readClicked(), MusicWidgetRenderer::setBackgroundPixmap(), MusicBackgroundSkinDialog::setBackgroundUrl(), MusicProgressWidget::show(), MusicDesktopWallpaperThread::timeout(), MusicBackgroundPaletteWidget::updateBackground(), and MusicBackgroundListItem::updatePixmap().
bool MusicExtractManager::outputThunderSkin (QPixmap & image, const QString & input) static
Transfer file to image data.
Definition at line 18 of file musicextractmanager.cpp.
References name, unz_global_info64_s::number_entry, qPrintable, TTK_HIGH_BUFFER, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
Referenced by MusicBackgroundOnlineWidget::outputRemoteSkin().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicextractmanager.h
TTKModule/TTKCore/musicCoreKits/musicextractmanager.cpp