TTKMusicPlayer: MusicEnhancedToolButton Class Reference
MusicEnhancedToolButton Class Reference
The class of the enhanced tool button.
#include <musicenhancedpopwidget.h>
Public Member Functions
MusicEnhancedToolButton (QWidget *parent=nullptr)
~MusicEnhancedToolButton ()
void setStyleSheet (const QString &styleSheet, bool state=false)
void start ()
void stop ()
Private Slots
void finished ()
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
Private Attributes
bool m_state
QLabel * m_foreLabel
QLabel * m_animationLabel
QPropertyAnimation * m_animation
Detailed Description
The class of the enhanced tool button.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicenhancedpopwidget.h.
Constructor & Destructor Documentation
MusicEnhancedToolButton::MusicEnhancedToolButton (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 16 of file musicenhancedpopwidget.cpp.
References finished(), LABEL_ANIMAT_WIDGET, LABEL_BUTTON_HEIGHT, m_animation, m_animationLabel, m_foreLabel, and TTK_DN_S2MS.
MusicEnhancedToolButton::~MusicEnhancedToolButton ()
Object destructor.
Definition at line 35 of file musicenhancedpopwidget.cpp.
References m_animation, m_animationLabel, and m_foreLabel.
Member Function Documentation
void MusicEnhancedToolButton::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Definition at line 79 of file musicenhancedpopwidget.cpp.
References m_state, and start().
void MusicEnhancedToolButton::finished () private slot
Label animation just finished.
Definition at line 71 of file musicenhancedpopwidget.cpp.
References m_state, and start().
Referenced by MusicEnhancedToolButton().
void MusicEnhancedToolButton::setStyleSheet (const QString & styleSheet, bool state = false)
Set object style sheet.
Definition at line 42 of file musicenhancedpopwidget.cpp.
References m_animation, m_animationLabel, m_foreLabel, m_state, and TTK_DN_S2MS.
Referenced by MusicEnhancedPopWidget::initialize().
void MusicEnhancedToolButton::start ()
Start label animation .
Definition at line 61 of file musicenhancedpopwidget.cpp.
References m_animation.
Referenced by enterEvent(), and finished().
void MusicEnhancedToolButton::stop ()
Stop label animation.
Definition at line 66 of file musicenhancedpopwidget.cpp.
References m_animation.
Member Data Documentation
QPropertyAnimation* MusicEnhancedToolButton::m_animation private
Definition at line 71 of file musicenhancedpopwidget.h.
Referenced by MusicEnhancedToolButton(), setStyleSheet(), start(), stop(), and ~MusicEnhancedToolButton().
QLabel * MusicEnhancedToolButton::m_animationLabel private
Definition at line 70 of file musicenhancedpopwidget.h.
Referenced by MusicEnhancedToolButton(), setStyleSheet(), and ~MusicEnhancedToolButton().
QLabel* MusicEnhancedToolButton::m_foreLabel private
Definition at line 70 of file musicenhancedpopwidget.h.
Referenced by MusicEnhancedToolButton(), setStyleSheet(), and ~MusicEnhancedToolButton().
bool MusicEnhancedToolButton::m_state private
Definition at line 69 of file musicenhancedpopwidget.h.
Referenced by enterEvent(), finished(), and setStyleSheet().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicenhancedpopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicenhancedpopwidget.cpp