TTKMusicplayer: MusicSongsListPlayWidget Class Reference
MusicSongsListPlayWidget Class Reference
The class of the song list play widget.
#include <musicsongslistplaywidget.h>
Public Slots
void deleteRenameItem ()
void setChangItemName (const QString &name)
void currentLoveStateClicked ()
void currentDownloadStateClicked ()
Signals
void renameFinished (const QString &text)
void enterChanged (int row, int column)
Public Member Functions
MusicSongsListPlayWidget (int index, QWidget *parent=nullptr)
~MusicSongsListPlayWidget ()
void updateTimeLabel (const QString &current, const QString &total)
void updateCurrentArtist ()
void setParameter (const QString &name, const QString &path, QString &time)
void setItemRename ()
bool getItemRenameState ()
void setCurrentPlayIndex (int index)
int getCurrentPlayIndex () const
Protected Member Functions
virtual void enterEvent (QEvent *event) override
void createMoreMenu (QMenu *menu)
bool showArtistPicture (const QString &name) const
Protected Attributes
bool m_noCover
int m_currentPlayIndex
QString m_totalTimeLabel
QLabel * m_artistPictureLabel
QLabel * m_timeLabel
MusicSplitItemClickedLabel * m_songNameLabel
QPushButton * m_loveButton
QPushButton * m_deleteButton
QPushButton * m_showMVButton
QPushButton * m_downloadButton
QPushButton * m_moreButton
MusicSongsToolItemRenamedWidget * m_renameLine
Detailed Description
The class of the song list play widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicsongslistplaywidget.h.
Constructor & Destructor Documentation
MusicSongsListPlayWidget::MusicSongsListPlayWidget (int index, QWidget * parent = nullptr) explicit
Object contsructor by index.
Definition at line 17 of file musicsongslistplaywidget.cpp.
References createMoreMenu(), currentDownloadStateClicked(), currentLoveStateClicked(), enterChanged(), MusicLeftAreaWidget::instance(), MusicApplication::instance(), m_artistPictureLabel, m_currentPlayIndex, m_deleteButton, m_downloadButton, m_loveButton, m_moreButton, m_noCover, m_showMVButton, m_songNameLabel, m_timeLabel, m_totalTimeLabel, MusicUIObject::MQSSColorStyle01, MusicUIObject::MQSSPushButtonStyle13, MusicUIObject::MQSSTinyBtnDelete, MusicUIObject::MQSSTinyBtnMore, MusicUIObject::MQSSTinyBtnMV, MusicUIObject::MQSSTinyBtnPlayLater, MUSIC_TIME_INIT, and renameFinished().
MusicSongsListPlayWidget::~MusicSongsListPlayWidget ()
Definition at line 106 of file musicsongslistplaywidget.cpp.
References m_artistPictureLabel, m_deleteButton, m_downloadButton, m_loveButton, m_moreButton, m_renameLine, m_showMVButton, m_songNameLabel, and m_timeLabel.
Member Function Documentation
void MusicSongsListPlayWidget::createMoreMenu (QMenu * menu) protected
Create more menu information.
Definition at line 222 of file musicsongslistplaywidget.cpp.
References MusicUIObject::MQSSMenuStyle02.
Referenced by MusicSongsListPlayWidget().
void MusicSongsListPlayWidget::currentDownloadStateClicked () slot
Reset current music download icon state.
Definition at line 205 of file musicsongslistplaywidget.cpp.
References MusicApplication::instance(), m_downloadButton, MusicUIObject::MQSSTinyBtnDownload, MusicUIObject::MQSSTinyBtnUnDownload, and MusicApplication::musicDownloadContains().
Referenced by MusicSongsListPlayWidget().
void MusicSongsListPlayWidget::currentLoveStateClicked () slot
Reset current music love icon state.
Definition at line 199 of file musicsongslistplaywidget.cpp.
References MusicApplication::instance(), m_loveButton, MusicUIObject::MQSSTinyBtnLove, MusicUIObject::MQSSTinyBtnUnLove, and MusicApplication::musicLovestContains().
Referenced by MusicSongsListPlayWidget().
void MusicSongsListPlayWidget::deleteRenameItem () slot
Delete rename item.
Definition at line 185 of file musicsongslistplaywidget.cpp.
References m_renameLine.
Referenced by setChangItemName().
void MusicSongsListPlayWidget::enterChanged (int row, int column) signal
Mouse is the item geometry, emit row and column.
Referenced by MusicSongsListPlayWidget().
void MusicSongsListPlayWidget::enterEvent (QEvent * event) override protected virtual
Override the widget event.
Definition at line 215 of file musicsongslistplaywidget.cpp.
int MusicSongsListPlayWidget::getCurrentPlayIndex () const inline
Get current play index.
Definition at line 72 of file musicsongslistplaywidget.h.
bool MusicSongsListPlayWidget::getItemRenameState () inline
Get rename item artist label state.
Definition at line 64 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListTableWidget::showTimeOut().
void MusicSongsListPlayWidget::renameFinished (const QString & text) signal
Rename item artist label is finised it emit.
Referenced by MusicSongsListPlayWidget(), setChangItemName(), and setItemRename().
void MusicSongsListPlayWidget::setChangItemName (const QString & name) slot
Rename item artist label is finised.
Definition at line 191 of file musicsongslistplaywidget.cpp.
References deleteRenameItem(), MusicUtils::Widget::elidedText(), m_songNameLabel, MT_MS, and renameFinished().
Referenced by setItemRename().
void MusicSongsListPlayWidget::setCurrentPlayIndex (int index) inline
Set current play index.
Definition at line 68 of file musicsongslistplaywidget.h.
void MusicSongsListPlayWidget::setItemRename ()
Rename item artist label name.
Definition at line 177 of file musicsongslistplaywidget.cpp.
References m_renameLine, m_songNameLabel, renameFinished(), and setChangItemName().
Referenced by MusicSongsListTableWidget::setChangSongName().
void MusicSongsListPlayWidget::setParameter (const QString & name, const QString & path, QString & time)
Update item artist label by name.
Definition at line 142 of file musicsongslistplaywidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicSongMeta::getCover(), MusicSongMeta::getLengthString(), m_artistPictureLabel, m_noCover, m_songNameLabel, m_timeLabel, m_totalTimeLabel, MUSIC_TIME_INIT, MusicSettingManager::OtherUseAlbumCover, MusicSongMeta::read(), showArtistPicture(), and MusicUtils::String::songName().
Referenced by MusicSongsListTableWidget::selectRow().
bool MusicSongsListPlayWidget::showArtistPicture (const QString & name) const protected
Show artist small picture, if no exsit there is default pic.
Definition at line 230 of file musicsongslistplaywidget.cpp.
References ART_DIR_FULL, m_artistPictureLabel, and SKN_FILE.
Referenced by setParameter(), and updateCurrentArtist().
void MusicSongsListPlayWidget::updateCurrentArtist ()
Update current artist when it download finished.
Definition at line 128 of file musicsongslistplaywidget.cpp.
References MusicUtils::String::artistName(), G_SETTING_PTR, m_artistPictureLabel, m_noCover, m_songNameLabel, name, MusicSettingManager::OtherUseAlbumCover, showArtistPicture(), and MusicUtils::String::songName().
Referenced by MusicSongsListTableWidget::updateCurrentArtist().
void MusicSongsListPlayWidget::updateTimeLabel (const QString & current, const QString & total)
Update item time label time.
Definition at line 119 of file musicsongslistplaywidget.cpp.
References m_timeLabel, m_totalTimeLabel, and MUSIC_TIME_INIT.
Referenced by MusicSongsListTableWidget::updateTimeLabel().
Member Data Documentation
QLabel* MusicSongsListPlayWidget::m_artistPictureLabel protected
Definition at line 123 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), setParameter(), showArtistPicture(), updateCurrentArtist(), and ~MusicSongsListPlayWidget().
int MusicSongsListPlayWidget::m_currentPlayIndex protected
Definition at line 121 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget().
QPushButton * MusicSongsListPlayWidget::m_deleteButton protected
Definition at line 125 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), and ~MusicSongsListPlayWidget().
QPushButton* MusicSongsListPlayWidget::m_downloadButton protected
Definition at line 126 of file musicsongslistplaywidget.h.
Referenced by currentDownloadStateClicked(), MusicSongsListPlayWidget(), and ~MusicSongsListPlayWidget().
QPushButton* MusicSongsListPlayWidget::m_loveButton protected
Definition at line 125 of file musicsongslistplaywidget.h.
Referenced by currentLoveStateClicked(), MusicSongsListPlayWidget(), and ~MusicSongsListPlayWidget().
QPushButton * MusicSongsListPlayWidget::m_moreButton protected
Definition at line 126 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), and ~MusicSongsListPlayWidget().
bool MusicSongsListPlayWidget::m_noCover protected
Definition at line 120 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), setParameter(), and updateCurrentArtist().
MusicSongsToolItemRenamedWidget* MusicSongsListPlayWidget::m_renameLine protected
Definition at line 127 of file musicsongslistplaywidget.h.
Referenced by deleteRenameItem(), setItemRename(), and ~MusicSongsListPlayWidget().
QPushButton * MusicSongsListPlayWidget::m_showMVButton protected
Definition at line 125 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), and ~MusicSongsListPlayWidget().
MusicSplitItemClickedLabel* MusicSongsListPlayWidget::m_songNameLabel protected
Definition at line 124 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), setChangItemName(), setItemRename(), setParameter(), updateCurrentArtist(), and ~MusicSongsListPlayWidget().
QLabel * MusicSongsListPlayWidget::m_timeLabel protected
Definition at line 123 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), setParameter(), updateTimeLabel(), and ~MusicSongsListPlayWidget().
QString MusicSongsListPlayWidget::m_totalTimeLabel protected
Definition at line 122 of file musicsongslistplaywidget.h.
Referenced by MusicSongsListPlayWidget(), setParameter(), and updateTimeLabel().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplaywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplaywidget.cpp