TTKMusicplayer: MusicSongTag Class Reference
MusicSongTag Class Reference
The class of the music song tag.
#include <musicsongtag.h>
Public Member Functions
MusicSongTag ()
qmmp incldue
MusicSongTag (const QString &file)
bool read ()
bool read (const QString &file)
bool save ()
QString getDecoder () const
QString getFilePath () const
QString getArtist () const
QString getTitle () const
QString getAlbum () const
QString getComment () const
QString getYear () const
QString getTrackNum () const
QString getGenre () const
QString getAlbumArtist () const
QString getComposer () const
QString getChannel () const
QString getURL () const
void setArtist (const QString &artist)
void setTitle (const QString &title)
void setAlbum (const QString &album)
void setComment (const QString &comment)
void setYear (const QString &year)
void setTrackNum (const QString &track)
void setGenre (const QString &genre)
void setCover (const QPixmap &pix)
void setCover (const QByteArray &data)
QPixmap getCover () const
QString getSampleRate () const
QString getFormat () const
QString getMode () const
QString getBitrate () const
QString getLengthString () const
Protected Member Functions
QString findLegalDataString (TagWrapper::TagType type) const
QString findPluginPath () const
bool readOtherTaglib ()
bool saveOtherTaglib ()
Protected Attributes
QString m_filePath
QMap< TagWrapper::TagType, QVariant > m_parameters
Detailed Description
The class of the music song tag.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicsongtag.h.
Constructor & Destructor Documentation
MusicSongTag::MusicSongTag ()
qmmp incldue
Object contsructor.
Definition at line 18 of file musicsongtag.cpp.
MusicSongTag::MusicSongTag (const QString & file) explicit
Object contsructor.
Definition at line 23 of file musicsongtag.cpp.
References m_filePath.
Member Function Documentation
QString MusicSongTag::findLegalDataString (TagWrapper::TagType type) const protected
Find legal data string.
Definition at line 222 of file musicsongtag.cpp.
References MusicUtils::String::illegalCharactersReplaced(), and m_parameters.
Referenced by getAlbum(), getAlbumArtist(), getArtist(), getComposer(), getGenre(), getTitle(), and getURL().
QString MusicSongTag::findPluginPath () const protected
Find current pluin store path.
Definition at line 228 of file musicsongtag.cpp.
References key, m_filePath, MusicUtils::QMMP::pluginPath(), and MusicFormats::supportFormatsStringMap().
Referenced by getDecoder(), readOtherTaglib(), and saveOtherTaglib().
QString MusicSongTag::getAlbum () const
Get song album.
Definition at line 77 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_ALBUM.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), saveOtherTaglib(), MusicFileInformationWidget::setFileInformation(), and MusicLocalSongsManagerWidget::setShowAlbumButton().
QString MusicSongTag::getAlbumArtist () const
Get song album artist.
Definition at line 108 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_ALBUMARTIST.
QString MusicSongTag::getArtist () const
Get artist name.
Definition at line 67 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_ARTIST.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicSongsSummariziedWidget::importMusicSongsByPath(), MusicSongCheckToolsRenameThread::run(), saveOtherTaglib(), MusicFileInformationWidget::setFileInformation(), and MusicLocalSongsManagerWidget::setShowArtButton().
QString MusicSongTag::getBitrate () const
Get song bitrate.
Definition at line 212 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_BITRATE.
Referenced by MusicSongRingtoneMaker::initInputPath(), MusicSongCheckToolsDuplicateThread::run(), MusicSongCheckToolsQualityThread::run(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getChannel () const
Get song channel.
Definition at line 118 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_CHANNEL.
Referenced by MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getComment () const
Get song comment.
Definition at line 82 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_COMMENT.
Referenced by MusicDownloadDataTagRequest::downLoadFinished().
QString MusicSongTag::getComposer () const
Get song composer.
Definition at line 113 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_COMPOSER.
QPixmap MusicSongTag::getCover () const
Get song image cover artist.
Definition at line 188 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_COVER.
Referenced by MusicFileInformationWidget::advanceClicked(), MusicFileInformationWidget::saveAlbumPicture(), saveOtherTaglib(), MusicSongsListItemInfoWidget::setMusicSongInformation(), and MusicSongsListPlayWidget::setParameter().
QString MusicSongTag::getDecoder () const
Read music decoder name.
Definition at line 56 of file musicsongtag.cpp.
References findPluginPath().
Referenced by MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getFilePath () const
Read music file path.
Definition at line 62 of file musicsongtag.cpp.
References m_filePath.
QString MusicSongTag::getFormat () const
Get song format.
Definition at line 202 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_FORMAT.
QString MusicSongTag::getGenre () const
Get song genre.
Definition at line 103 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_GENRE.
Referenced by saveOtherTaglib(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getLengthString () const
Get song time length.
Definition at line 217 of file musicsongtag.cpp.
References m_parameters, MusicTime::msecTime2LabelJustified(), and TagWrapper::TAG_LENGTH.
Referenced by MusicSongsSummariziedWidget::importMusicSongsByPath(), MusicSongRingtoneMaker::initInputPath(), MusicFileInformationWidget::setFileInformation(), and MusicSongsListPlayWidget::setParameter().
QString MusicSongTag::getMode () const
Get song mode.
Definition at line 207 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_MODE.
QString MusicSongTag::getSampleRate () const
Get song sample rate.
Definition at line 197 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_SAMPLERATE.
Referenced by MusicSongRingtoneMaker::initInputPath(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getTitle () const
Get song title.
Definition at line 72 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_TITLE.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicSongsSummariziedWidget::importMusicSongsByPath(), MusicSongCheckToolsRenameThread::run(), saveOtherTaglib(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getTrackNum () const
Get song track number.
Definition at line 92 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_TRACK.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), saveOtherTaglib(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongTag::getURL () const
Get song file path.
Definition at line 123 of file musicsongtag.cpp.
References findLegalDataString(), and TagWrapper::TAG_URL.
QString MusicSongTag::getYear () const
Get song year.
Definition at line 87 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_YEAR.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), saveOtherTaglib(), and MusicFileInformationWidget::setFileInformation().
bool MusicSongTag::read ()
Read music file to anaylsis.
Definition at line 29 of file musicsongtag.cpp.
References m_filePath.
Referenced by MusicFileInformationWidget::advanceClicked(), MusicDownloadDataTagRequest::downLoadFinished(), MusicSongsSummariziedWidget::importMusicSongsByPath(), MusicSongRingtoneMaker::initInputPath(), MusicSongCheckToolsRenameThread::run(), MusicSongCheckToolsDuplicateThread::run(), MusicSongCheckToolsQualityThread::run(), MusicFileInformationWidget::saveAlbumPicture(), MusicFileInformationWidget::saveTag(), MusicFileInformationWidget::setFileInformation(), MusicSongsListItemInfoWidget::setMusicSongInformation(), MusicSongsListPlayWidget::setParameter(), MusicLocalSongsManagerWidget::setShowAlbumButton(), and MusicLocalSongsManagerWidget::setShowArtButton().
bool MusicSongTag::read (const QString & file)
Read music file to anaylsis.
Definition at line 39 of file musicsongtag.cpp.
References m_filePath, and readOtherTaglib().
bool MusicSongTag::readOtherTaglib () protected
Read other taglib not by plugin.
Definition at line 244 of file musicsongtag.cpp.
References Qmmp::ALBUM, TrackInfo::AllParts, Qmmp::ARTIST, Qmmp::BITRATE, Qmmp::CHANNELS, Qmmp::COMMENT, MetaDataModel::cover(), DecoderFactory::createMetaDataModel(), DecoderFactory::createPlayList(), TrackInfo::duration(), findPluginPath(), Qmmp::GENRE, TagWrapper::getMusicTags(), m_filePath, m_parameters, TagWrapper::readFile(), Qmmp::SAMPLERATE, TagWrapper::TAG_ALBUM, TagWrapper::TAG_ARTIST, TagWrapper::TAG_BITRATE, TagWrapper::TAG_CHANNEL, TagWrapper::TAG_COMMENT, TagWrapper::TAG_COVER, TagWrapper::TAG_GENRE, TagWrapper::TAG_LENGTH, TagWrapper::TAG_SAMPLERATE, TagWrapper::TAG_TITLE, TagWrapper::TAG_TRACK, TagWrapper::TAG_YEAR, Qmmp::TITLE, Qmmp::TRACK, TTKObject_cast, TrackInfo::value(), and Qmmp::YEAR.
Referenced by read().
bool MusicSongTag::save ()
Save music tags to music file.
Definition at line 51 of file musicsongtag.cpp.
References saveOtherTaglib().
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), and MusicFileInformationWidget::saveTag().
bool MusicSongTag::saveOtherTaglib () protected
Save other taglib not by plugin.
Definition at line 301 of file musicsongtag.cpp.
References Qmmp::ALBUM, Qmmp::ARTIST, DecoderFactory::createMetaDataModel(), findPluginPath(), Qmmp::GENRE, getAlbum(), getArtist(), getCover(), getGenre(), getTitle(), getTrackNum(), getYear(), m_filePath, MetaDataModel::removeCover(), TagModel::save(), MetaDataModel::setCover(), TagModel::setValue(), MetaDataModel::tags(), Qmmp::TITLE, Qmmp::TRACK, TTKObject_cast, and Qmmp::YEAR.
Referenced by save().
void MusicSongTag::setAlbum (const QString & album)
Set song album.
Definition at line 138 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_ALBUM.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicSongTag::setArtist (const QString & artist)
Set artist name.
Definition at line 128 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_ARTIST.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicSongTag::setComment (const QString & comment)
Set song comment.
Definition at line 143 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_COMMENT.
Referenced by MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicSongTag::setCover (const QPixmap & pix)
Set song image cover artist.
Definition at line 163 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_COVER.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), and setCover().
void MusicSongTag::setCover (const QByteArray & data)
Set song image cover artist.
Definition at line 177 of file musicsongtag.cpp.
References setCover().
void MusicSongTag::setGenre (const QString & genre)
Set song genre.
Definition at line 158 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_GENRE.
Referenced by MusicFileInformationWidget::saveTag().
void MusicSongTag::setTitle (const QString & title)
Set song title.
Definition at line 133 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_TITLE.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicSongTag::setTrackNum (const QString & track)
Set song track number.
Definition at line 153 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_TRACK.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicSongTag::setYear (const QString & year)
Set song year.
Definition at line 148 of file musicsongtag.cpp.
References m_parameters, and TagWrapper::TAG_YEAR.
Referenced by MusicDownloadDataTagRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
Member Data Documentation
QString MusicSongTag::m_filePath protected
Definition at line 187 of file musicsongtag.h.
Referenced by findPluginPath(), getFilePath(), MusicSongTag(), read(), readOtherTaglib(), and saveOtherTaglib().
QMap<TagWrapper::TagType, QVariant> MusicSongTag::m_parameters protected
Definition at line 188 of file musicsongtag.h.
Referenced by findLegalDataString(), getBitrate(), getChannel(), getComment(), getCover(), getFormat(), getLengthString(), getMode(), getSampleRate(), getTrackNum(), getYear(), readOtherTaglib(), setAlbum(), setArtist(), setComment(), setCover(), setGenre(), setTitle(), setTrackNum(), and setYear().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicsongtag.h
TTKModule/TTKCore/musicCoreKits/musicsongtag.cpp