TTKMusicplayer: MusicArtistListFoundItemWidget Class Reference
MusicArtistListFoundItemWidget Class Reference
The class of the artist list music item widget.
#include <musicartistlistfoundwidget.h>
Public Slots
void currentArtistListClicked ()
Signals
void currentArtistListClicked (const MusicResultsItem &item)
Signals inherited from MusicClickedLabel
void clicked ()
Public Member Functions
MusicArtistListFoundItemWidget (QWidget *parent=0)
void setMusicResultsItem (const MusicResultsItem &item)
Public Member Functions inherited from MusicClickedLabel
MusicClickedLabel (QWidget *parent=0)
MusicClickedLabel (const QString &text, QWidget *parent=0)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicClickedLabel
static QString getClassName ()
Protected Attributes
MusicResultsItem m_itemData
Additional Inherited Members
Protected Member Functions inherited from MusicClickedLabel
virtual void mousePressEvent (QMouseEvent *event) override
Detailed Description
The class of the artist list music item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicartistlistfoundwidget.h.
Constructor & Destructor Documentation
MusicArtistListFoundItemWidget::MusicArtistListFoundItemWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 17 of file musicartistlistfoundwidget.cpp.
References MusicClickedLabel::clicked(), currentArtistListClicked(), HEIGHT_LABEL_SIZE, MusicUIObject::MColorStyle09, and WIDTH_LABEL_SIZE.
Member Function Documentation
void MusicArtistListFoundItemWidget::currentArtistListClicked (const MusicResultsItem & item) signal
Current artist list clicked.
void MusicArtistListFoundItemWidget::currentArtistListClicked () slot
Current artist list clicked.
Definition at line 39 of file musicartistlistfoundwidget.cpp.
References m_itemData.
Referenced by MusicArtistListFoundItemWidget().
QString MusicArtistListFoundItemWidget::getClassName () static
Get class object name.
Definition at line 27 of file musicartistlistfoundwidget.cpp.
void MusicArtistListFoundItemWidget::setMusicResultsItem (const MusicResultsItem & item)
Set music playlist item.
Definition at line 32 of file musicartistlistfoundwidget.cpp.
References MusicUtils::Widget::elidedText(), m_itemData, MusicResultsItem::m_name, and WIDTH_LABEL_SIZE.
Referenced by MusicArtistListFoundWidget::createArtistListItems().
Member Data Documentation
MusicResultsItem MusicArtistListFoundItemWidget::m_itemData protected
Definition at line 65 of file musicartistlistfoundwidget.h.
Referenced by currentArtistListClicked(), and setMusicResultsItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistfoundwidget.cpp