TTKMusicplayer: MusicLrcColor Class Reference
MusicLrcColor Class Reference
The class of the lrc color.
#include <musiclrcmanager.h>
Public Types
enum LrcColorType {
Null = -1, IYellow, IBlue, IGray,
IPink, IGreen, IRed, IPurple,
IOrange, IIndigo, DWhite, DBlue,
DRed, DBlack, DYellow, DPurple,
DGreen
}
Public Member Functions
MusicLrcColor ()
MusicLrcColor (const QList< QColor > &front, const QList< QColor > &back, MusicLrcColor::LrcColorType index=MusicLrcColor::Null)
Static Public Member Functions
static MusicLrcColor mapIndexToColor (MusicLrcColor::LrcColorType index)
static QList< QColor > readColorConfig (const QString &value)
static QString writeColorConfig (const QList< QColor > &colors)
Public Attributes
QList< QColor > m_frontColor
QList< QColor > m_backColor
MusicLrcColor::LrcColorType m_index
Detailed Description
The class of the lrc color.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musiclrcmanager.h.
Member Enumeration Documentation
enum MusicLrcColor::LrcColorType
Enumerator
Null
color null
IYellow
color yellow
IBlue
color blue
IGray
color gray
IPink
color pink
IGreen
color green
IRed
color red
IPurple
color purple
IOrange
color orange
IIndigo
color indigo
DWhite
color white
DBlue
color blue
DRed
color red
DBlack
color black
DYellow
color yellow
DPurple
color purple
DGreen
color green
Definition at line 38 of file musiclrcmanager.h.
Constructor & Destructor Documentation
MusicLrcColor::MusicLrcColor ()
Object contsructor.
Definition at line 7 of file musiclrcmanager.cpp.
Referenced by mapIndexToColor().
MusicLrcColor::MusicLrcColor (const QList< QColor > & front, const QList< QColor > & back, MusicLrcColor::LrcColorType index = MusicLrcColor::Null)
Object contsructor.
Definition at line 12 of file musiclrcmanager.cpp.
References m_backColor, m_frontColor, and m_index.
Member Function Documentation
MusicLrcColor MusicLrcColor::mapIndexToColor (MusicLrcColor::LrcColorType index) static
Map index to color.
Definition at line 19 of file musiclrcmanager.cpp.
References DBlack, DBlue, DGreen, DPurple, DRed, DWhite, DYellow, IBlue, IGray, IGreen, IIndigo, IOrange, IPink, IPurple, IRed, IYellow, and MusicLrcColor().
Referenced by MusicSettingWidget::lrcColorByDefault(), MusicSoundKMicroWidget::setItemStyleSheet(), MusicLrcMakerWidget::setItemStyleSheet(), and MusicLrcContainer::setLinearGradientColor().
QList< QColor > MusicLrcColor::readColorConfig (const QString & value) static
Transform colors string to color list.
Definition at line 126 of file musiclrcmanager.cpp.
Referenced by MusicLrcContainer::applySettingParameter(), MusicSettingWidget::initControllerParameter(), MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicSoundKMicroWidget::setItemStyleSheet(), MusicLrcContainerForInterior::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
QString MusicLrcColor::writeColorConfig (const QList< QColor > & colors) static
Transform color list to colors string.
Definition at line 146 of file musiclrcmanager.cpp.
Referenced by MusicSettingWidget::saveParameterSettings().
Member Data Documentation
QList<QColor> MusicLrcColor::m_backColor
Definition at line 84 of file musiclrcmanager.h.
Referenced by MusicSettingWidget::lrcColorByDefault(), MusicLrcColor(), and MusicLrcManager::setLinearGradientColor().
QList<QColor> MusicLrcColor::m_frontColor
Definition at line 83 of file musiclrcmanager.h.
Referenced by MusicSettingWidget::lrcColorByDefault(), MusicLrcColor(), and MusicLrcManager::setLinearGradientColor().
MusicLrcColor::LrcColorType MusicLrcColor::m_index
Definition at line 85 of file musiclrcmanager.h.
Referenced by MusicLrcColor(), and MusicLrcContainer::setLinearGradientColor().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcmanager.h
TTKModule/TTKWidget/musicLrcKits/musiclrcmanager.cpp