TTKMusicplayer: MusicAbstractNetwork Class Reference
MusicAbstractNetwork Class Reference
The class of abstract downloading data.
#include <musicabstractnetwork.h>
Public Slots
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Attributes
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of abstract downloading data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicabstractnetwork.h.
Constructor & Destructor Documentation
MusicAbstractNetwork::MusicAbstractNetwork (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicabstractnetwork.cpp.
References m_interrupt, m_manager, m_reply, m_stateCode, MusicObject::NetworkQuery, and sslErrors().
MusicAbstractNetwork::~MusicAbstractNetwork () virtual
Definition at line 15 of file musicabstractnetwork.cpp.
References deleteAll(), m_interrupt, m_manager, m_stateCode, and MusicObject::NetworkError.
Member Function Documentation
void MusicAbstractNetwork::deleteAll () virtual
Release the network object.
Reimplemented in MusicAbstractDownLoadRequest.
Definition at line 28 of file musicabstractnetwork.cpp.
References m_interrupt, and m_reply.
Referenced by MusicAbstractDownLoadRequest::deleteAll(), MusicMVRadioCategoryRequest::downLoadFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicBDQueryLearnRequest::downLoadFinished(), MusicKGArtistSimilarRequest::downLoadFinished(), MusicWYTranslationRequest::downLoadFinished(), MusicKWSongSuggestRequest::downLoadFinished(), MusicQQArtistSimilarRequest::downLoadFinished(), MusicDJRadioCategoryRequest::downLoadFinished(), MusicDownloadSourceRequest::downLoadFinished(), MusicKGSongSuggestRequest::downLoadFinished(), MusicQQDiscoverListRequest::downLoadFinished(), MusicKWArtistSimilarRequest::downLoadFinished(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicQQSongSuggestRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicWYSongSuggestRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYArtistSimilarRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicFMRadioSongsRequest::downLoadFinished(), MusicQQSongCommentsRequest::downLoadFinished(), MusicKGSongCommentsRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicWYQueryArtistListRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicKGQueryArtistListRequest::downLoadFinished(), MusicQQQueryArtistListRequest::downLoadFinished(), MusicKWQueryArtistListRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicDownloadCounterPVRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicWYQueryMovieRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicDJRadioProgramRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), MusicFMRadioChannelRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicIdentifySongsRequest::downLoadFinished(), MusicBDTranslationRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicQQPlaylistCommentsRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), MusicWYPlaylistCommentsRequest::downLoadFinished(), MusicQQDownloadBackgroundRequest::downLoadUrl(), MusicWYQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryMovieRequest::pageDownLoadFinished(), MusicKGQueryMovieRequest::pageDownLoadFinished(), MusicKWQueryMovieRequest::pageDownLoadFinished(), replyError(), MusicKGQueryAlbumRequest::singleDownLoadFinished(), MusicQQQueryAlbumRequest::singleDownLoadFinished(), MusicKWQueryAlbumRequest::singleDownLoadFinished(), MusicWYQueryAlbumRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), sslErrors(), MusicWYTranslationRequest::startToDownload(), MusicDJRadioCategoryRequest::startToDownload(), MusicQQDownloadBackgroundRequest::startToDownload(), MusicDJRadioProgramRequest::startToDownload(), MusicBDTranslationRequest::startToDownload(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicQQQueryArtistListRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicKGArtistSimilarRequest::startToSearch(), MusicKWSongSuggestRequest::startToSearch(), MusicBDQueryLearnRequest::startToSearch(), MusicKGSongSuggestRequest::startToSearch(), MusicQQDiscoverListRequest::startToSearch(), MusicKWArtistSimilarRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicQQArtistSimilarRequest::startToSearch(), MusicQQSongSuggestRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicWYSongSuggestRequest::startToSearch(), MusicKGQueryAlbumRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSearch(), MusicKWQueryRecommendRequest::startToSearch(), MusicWYArtistSimilarRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicKGQueryArtistRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicKGQueryRecommendRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicKGQueryToplistRequest::startToSearch(), MusicKWQueryToplistRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicQQQueryToplistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicQQQueryPlaylistRequest::startToSearch(), MusicQQQueryArtistRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSingleSearch(), MusicKWQueryAlbumRequest::startToSingleSearch(), MusicWYQueryAlbumRequest::startToSingleSearch(), MusicKGQueryAlbumRequest::startToSingleSearch(), MusicKWQueryMovieRequest::startToSingleSearch(), MusicWYQueryMovieRequest::startToSingleSearch(), MusicQQQueryRequest::startToSingleSearch(), MusicKGQueryRequest::startToSingleSearch(), MusicKGQueryMovieRequest::startToSingleSearch(), MusicWYQueryRequest::startToSingleSearch(), MusicQQQueryMovieRequest::startToSingleSearch(), MusicKWQueryRequest::startToSingleSearch(), and ~MusicAbstractNetwork().
void MusicAbstractNetwork::downLoadDataChanged (const QString & data) signal
Send download data from net.
Referenced by MusicMVRadioCategoryRequest::downLoadFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicBDQueryLearnRequest::downLoadFinished(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicQQSongSuggestRequest::downLoadFinished(), MusicKWDownLoadTextRequest::downLoadFinished(), MusicWYDownLoadTextRequest::downLoadFinished(), MusicWYTranslationRequest::downLoadFinished(), MusicDJRadioCategoryRequest::downLoadFinished(), MusicFMRadioDownLoadTextRequest::downLoadFinished(), MusicDownLoadTextRequest::downLoadFinished(), MusicKGArtistSimilarRequest::downLoadFinished(), MusicKWSongSuggestRequest::downLoadFinished(), MusicQQArtistSimilarRequest::downLoadFinished(), MusicQQDiscoverListRequest::downLoadFinished(), MusicKGSongSuggestRequest::downLoadFinished(), MusicQQDownLoadTextRequest::downLoadFinished(), MusicKWArtistSimilarRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicWYArtistSimilarRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicWYSongSuggestRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicFMRadioSongsRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicQQSongCommentsRequest::downLoadFinished(), MusicKGSongCommentsRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicDownloadCounterPVRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicWYQueryMovieRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicDownloadTagDataRequest::downLoadFinished(), MusicDJRadioProgramRequest::downLoadFinished(), MusicFMRadioChannelRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicDownloadDataRequest::downLoadFinished(), MusicIdentifySongsRequest::downLoadFinished(), MusicBDTranslationRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicDownloadQueueRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), MusicQQPlaylistCommentsRequest::downLoadFinished(), MusicWYPlaylistCommentsRequest::downLoadFinished(), MusicQQDownloadBackgroundRequest::downLoadUrlFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicKWQueryMovieRequest::pageDownLoadFinished(), MusicWYQueryMovieRequest::pageDownLoadFinished(), MusicKGQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryMovieRequest::pageDownLoadFinished(), MusicAbstractDownLoadRequest::replyError(), replyError(), MusicKGQueryAlbumRequest::singleDownLoadFinished(), MusicWYQueryAlbumRequest::singleDownLoadFinished(), MusicKWQueryAlbumRequest::singleDownLoadFinished(), MusicQQQueryAlbumRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicKWQueryMovieRequest::singleDownLoadFinished(), MusicWYQueryMovieRequest::singleDownLoadFinished(), MusicQQQueryMovieRequest::singleDownLoadFinished(), MusicKGQueryMovieRequest::singleDownLoadFinished(), MusicKWQueryRequest::singleDownLoadFinished(), MusicAbstractDownLoadRequest::sslErrors(), sslErrors(), MusicDownloadQueueRequest::startOrderImageQueue(), MusicKWDownLoadTextRequest::startToDownload(), MusicDownloadDataRequest::startToDownload(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicWYTranslationRequest::startToDownload(), MusicDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicDownloadTagDataRequest::startToDownload(), MusicKGSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicQQSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
void MusicAbstractNetwork::downLoadFinished () virtual slot
Download data from net finished. Subclass should implement this function.
Definition at line 38 of file musicabstractnetwork.cpp.
References m_interrupt.
Referenced by MusicQQDownloadBackgroundRequest::downLoadDataFinished(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicQQSongSuggestRequest::downLoadFinished(), MusicKWSongSuggestRequest::downLoadFinished(), MusicWYTranslationRequest::downLoadFinished(), MusicDJRadioCategoryRequest::downLoadFinished(), MusicDownloadSourceRequest::downLoadFinished(), MusicQQArtistSimilarRequest::downLoadFinished(), MusicQQDiscoverListRequest::downLoadFinished(), MusicKGArtistSimilarRequest::downLoadFinished(), MusicKGSongSuggestRequest::downLoadFinished(), MusicKWArtistSimilarRequest::downLoadFinished(), MusicWYArtistSimilarRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicWYSongSuggestRequest::downLoadFinished(), MusicDownloadBackgroundRequest::downLoadFinished(), MusicFMRadioSongsRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicQQSongCommentsRequest::downLoadFinished(), MusicKGSongCommentsRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicDownloadCounterPVRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicAbstractDownLoadRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicDJRadioProgramRequest::downLoadFinished(), MusicFMRadioChannelRequest::downLoadFinished(), MusicIdentifySongsRequest::downLoadFinished(), MusicBDTranslationRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicQQPlaylistCommentsRequest::downLoadFinished(), MusicWYPlaylistCommentsRequest::downLoadFinished(), MusicAbstractQueryRequest::downLoadFinished(), MusicQQDownloadBackgroundRequest::downLoadUrlFinished(), MusicKGQueryPlaylistRequest::getPlaylistInfo(), MusicWYQueryPlaylistRequest::getPlaylistInfo(), MusicKWQueryPlaylistRequest::getPlaylistInfo(), MusicQQQueryPlaylistRequest::getPlaylistInfo(), MusicKGQueryMovieRequest::pageDownLoadFinished(), MusicWYQueryMovieRequest::pageDownLoadFinished(), MusicKWQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryAlbumRequest::singleDownLoadFinished(), MusicWYQueryAlbumRequest::singleDownLoadFinished(), MusicKWQueryAlbumRequest::singleDownLoadFinished(), and MusicKGQueryAlbumRequest::singleDownLoadFinished().
void MusicAbstractNetwork::downLoadRawDataChanged (const QByteArray & data) signal
Send download raw data changed.
Referenced by MusicDownloadSourceRequest::downLoadFinished(), MusicDownloadTagDataRequest::downLoadFinished(), MusicIdentifySongsRequest::getKey(), and MusicKWDownloadBackgroundRequest::startToDownload().
const QVariant MusicAbstractNetwork::getHeader (const QString & key) const inline
Get the current raw data.
Definition at line 57 of file musicabstractnetwork.h.
References key.
Referenced by MusicWebFMRadioWidget::downLoadFinished(), MusicWebDJRadioProgramTableWidget::downLoadFinished(), MusicWebFMRadioWidget::itemCellDoubleClicked(), MusicFMRadioSongsRequest::startToDownload(), and MusicQQSongCommentsRequest::startToSearch().
void MusicAbstractNetwork::replyError (QNetworkReply::NetworkError error) virtual slot
Download reply error.
Definition at line 43 of file musicabstractnetwork.cpp.
References deleteAll(), downLoadDataChanged(), and TTK_LOGGER_ERROR.
Referenced by MusicQQDownloadBackgroundRequest::downLoadUrl(), MusicKWQueryPlaylistRequest::getMorePlaylistDetails(), MusicWYTranslationRequest::startToDownload(), MusicDJRadioCategoryRequest::startToDownload(), MusicQQDownloadBackgroundRequest::startToDownload(), MusicFMRadioSongsRequest::startToDownload(), MusicFMRadioChannelRequest::startToDownload(), MusicDJRadioProgramRequest::startToDownload(), MusicBDTranslationRequest::startToDownload(), MusicKGQueryArtistListRequest::startToPage(), MusicQQQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicQQArtistSimilarRequest::startToSearch(), MusicKWSongSuggestRequest::startToSearch(), MusicBDQueryLearnRequest::startToSearch(), MusicKGSongSuggestRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicQQDiscoverListRequest::startToSearch(), MusicKWArtistSimilarRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicKGArtistSimilarRequest::startToSearch(), MusicQQSongSuggestRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicKWQueryRecommendRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicWYSongSuggestRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicWYArtistSimilarRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicKGQueryArtistRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSearch(), MusicKGQueryAlbumRequest::startToSearch(), MusicKGQueryRecommendRequest::startToSearch(), MusicKGQueryToplistRequest::startToSearch(), MusicKWQueryToplistRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicQQQueryToplistRequest::startToSearch(), MusicQQQueryPlaylistRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicQQQueryArtistRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSingleSearch(), MusicWYQueryAlbumRequest::startToSingleSearch(), MusicKGQueryAlbumRequest::startToSingleSearch(), MusicKWQueryAlbumRequest::startToSingleSearch(), MusicKGQueryRequest::startToSingleSearch(), MusicQQQueryRequest::startToSingleSearch(), MusicWYQueryRequest::startToSingleSearch(), and MusicKWQueryRequest::startToSingleSearch().
void MusicAbstractNetwork::setHeader (const QString & key, const QVariant & value) inline
Set the current raw data.
Definition at line 53 of file musicabstractnetwork.h.
References key.
Referenced by MusicWebFMRadioWidget::addListWidgetItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicFMRadioChannelRequest::downLoadFinished(), MusicLrcAnalysis::getTranslatedLrc(), and MusicWebFMRadioPlayWidget::updateRadioSong().
void MusicAbstractNetwork::sslErrors (QNetworkReply * reply, const QList< QSslError > & errors) virtual slot
Download ssl reply error.
Definition at line 51 of file musicabstractnetwork.cpp.
References deleteAll(), downLoadDataChanged(), and sslErrorsString().
Referenced by MusicAbstractNetwork().
void MusicAbstractNetwork::sslErrorsString (QNetworkReply * reply, const QList< QSslError > & errors) slot
Download ssl reply error strings.
Definition at line 58 of file musicabstractnetwork.cpp.
References TTK_LOGGER_ERROR.
Referenced by MusicAbstractDownLoadRequest::sslErrors(), and sslErrors().
Member Data Documentation
volatile bool MusicAbstractNetwork::m_interrupt protected
Definition at line 92 of file musicabstractnetwork.h.
Referenced by deleteAll(), downLoadFinished(), MusicAbstractNetwork(), and ~MusicAbstractNetwork().
QNetworkAccessManager* MusicAbstractNetwork::m_manager protected
Definition at line 95 of file musicabstractnetwork.h.
Referenced by MusicDownloadQueueRequest::downLoadFinished(), MusicQQDownloadBackgroundRequest::downLoadUrl(), MusicKWArtistSimilarRequest::getArtistIdName(), MusicWYQueryMovieRequest::getArtistMoviesCount(), MusicKWArtistSimilarRequest::getArtistNameById(), MusicKGQueryArtistRequest::getDownLoadIntro(), MusicKWQueryArtistRequest::getDownLoadIntro(), MusicWYQueryArtistRequest::getDownLoadIntro(), MusicQQQueryArtistRequest::getDownLoadIntro(), MusicQQQueryPlaylistRequest::getMoreDetails(), MusicKWQueryPlaylistRequest::getMorePlaylistDetails(), MusicQQQueryMovieRequest::getMovieKey(), MusicQQQueryPlaylistRequest::getPlaylistInfo(), MusicKGQueryPlaylistRequest::getPlaylistInfo(), MusicKWQueryPlaylistRequest::getPlaylistInfo(), MusicWYQueryPlaylistRequest::getPlaylistInfo(), MusicDJRadioProgramCategoryRequest::getProgramInfo(), MusicAbstractNetwork(), MusicWYQueryMovieRequest::queryMovieList(), MusicWYQueryMovieRequest::queryVideoList(), MusicWYQueryMovieRequest::queryVideoUrlPath(), MusicBDQueryLearnRequest::readFromMusicLrcAttribute(), MusicMVRadioProgramRequest::readFromMusicMVAttribute(), MusicQQQueryMovieRequest::readFromMusicMVAttribute(), MusicKWQueryMovieRequest::readFromMusicMVAttribute(), MusicKGQueryMovieRequest::readFromMusicMVAttribute(), MusicKGQueryMovieRequest::readFromMusicMVInfo(), MusicKWQueryMovieRequest::readFromMusicMVInfo(), MusicBDQueryLearnRequest::readFromMusicSongAttribute(), MusicDownloadQueueRequest::startDownload(), MusicDownloadDataRequest::startRequest(), MusicQQDownloadBackgroundRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicDownloadSourceRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicDownLoadTextRequest::startToDownload(), MusicWYTranslationRequest::startToDownload(), MusicDJRadioCategoryRequest::startToDownload(), MusicFMRadioSongsRequest::startToDownload(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicDownloadCounterPVRequest::startToDownload(), MusicFMRadioChannelRequest::startToDownload(), MusicDJRadioProgramRequest::startToDownload(), MusicIdentifySongsRequest::startToDownload(), MusicBDTranslationRequest::startToDownload(), MusicQQQueryArtistListRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicQQDiscoverListRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicBDQueryLearnRequest::startToSearch(), MusicKGSongSuggestRequest::startToSearch(), MusicKWArtistSimilarRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicQQSongSuggestRequest::startToSearch(), MusicQQArtistSimilarRequest::startToSearch(), MusicKGArtistSimilarRequest::startToSearch(), MusicKWSongSuggestRequest::startToSearch(), MusicWYQueryRequest::startToSearch(), MusicKGQueryAlbumRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicKGQueryRequest::startToSearch(), MusicKGQueryArtistRequest::startToSearch(), MusicKGQueryRecommendRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicQQQueryRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSearch(), MusicKWQueryRecommendRequest::startToSearch(), MusicWYSongSuggestRequest::startToSearch(), MusicWYArtistSimilarRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicQQQueryToplistRequest::startToSearch(), MusicKWQueryToplistRequest::startToSearch(), MusicKGQueryToplistRequest::startToSearch(), MusicQQQueryPlaylistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicKWQueryRequest::startToSearch(), MusicQQQueryArtistRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSingleSearch(), MusicKWQueryAlbumRequest::startToSingleSearch(), MusicKGQueryAlbumRequest::startToSingleSearch(), MusicWYQueryAlbumRequest::startToSingleSearch(), MusicWYQueryRequest::startToSingleSearch(), MusicQQQueryMovieRequest::startToSingleSearch(), MusicKGQueryRequest::startToSingleSearch(), MusicKWQueryMovieRequest::startToSingleSearch(), MusicKGQueryMovieRequest::startToSingleSearch(), MusicWYQueryMovieRequest::startToSingleSearch(), MusicQQQueryRequest::startToSingleSearch(), MusicKWQueryRequest::startToSingleSearch(), and ~MusicAbstractNetwork().
QVariantMap MusicAbstractNetwork::m_rawData protected
Definition at line 91 of file musicabstractnetwork.h.
Referenced by MusicQQQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistListRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicWYTranslationRequest::startToDownload(), MusicKGQueryArtistListRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToSearch(), MusicQQSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicWYSongCommentsRequest::startToSearch(), MusicQQPlaylistCommentsRequest::startToSearch(), MusicKWPlaylistCommentsRequest::startToSearch(), MusicKGPlaylistCommentsRequest::startToSearch(), and MusicWYPlaylistCommentsRequest::startToSearch().
QNetworkReply* MusicAbstractNetwork::m_reply protected
Definition at line 94 of file musicabstractnetwork.h.
Referenced by MusicDownloadQueueRequest::abort(), deleteAll(), MusicQQDownloadBackgroundRequest::downLoadDataFinished(), MusicMVRadioCategoryRequest::downLoadFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicKWSongSuggestRequest::downLoadFinished(), MusicWYTranslationRequest::downLoadFinished(), MusicDJRadioCategoryRequest::downLoadFinished(), MusicFMRadioDownLoadTextRequest::downLoadFinished(), MusicBDQueryLearnRequest::downLoadFinished(), MusicQQArtistSimilarRequest::downLoadFinished(), MusicQQDiscoverListRequest::downLoadFinished(), MusicKGArtistSimilarRequest::downLoadFinished(), MusicQQDownLoadTextRequest::downLoadFinished(), MusicDownloadSourceRequest::downLoadFinished(), MusicKGSongSuggestRequest::downLoadFinished(), MusicKWArtistSimilarRequest::downLoadFinished(), MusicDownLoadTextRequest::downLoadFinished(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicQQSongSuggestRequest::downLoadFinished(), MusicKWDownLoadTextRequest::downLoadFinished(), MusicWYDownLoadTextRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicWYSongSuggestRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicWYArtistSimilarRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicFMRadioSongsRequest::downLoadFinished(), MusicQQSongCommentsRequest::downLoadFinished(), MusicKGSongCommentsRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicKGQueryArtistListRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicQQQueryArtistListRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicKWQueryArtistListRequest::downLoadFinished(), MusicWYQueryArtistListRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicDownloadCounterPVRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicWYQueryMovieRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicDJRadioProgramRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::downLoadFinished(), MusicKWQueryPlaylistRequest::downLoadFinished(), MusicKGQueryPlaylistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::downLoadFinished(), MusicFMRadioChannelRequest::downLoadFinished(), MusicDownloadDataRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicIdentifySongsRequest::downLoadFinished(), MusicBDTranslationRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicDownloadQueueRequest::downLoadFinished(), MusicQQPlaylistCommentsRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicWYPlaylistCommentsRequest::downLoadFinished(), MusicQQDownloadBackgroundRequest::downLoadUrl(), MusicQQDownloadBackgroundRequest::downLoadUrlFinished(), MusicDownloadQueueRequest::handleError(), MusicDownloadDataRequest::handleReadyRead(), MusicDownloadQueueRequest::handleReadyRead(), MusicAbstractNetwork(), MusicTranslationRequest::MusicTranslationRequest(), MusicWYQueryMovieRequest::pageDownLoadFinished(), MusicKWQueryMovieRequest::pageDownLoadFinished(), MusicKGQueryMovieRequest::pageDownLoadFinished(), MusicQQQueryMovieRequest::pageDownLoadFinished(), MusicDownloadQueueRequest::startDownload(), MusicDownloadDataRequest::startRequest(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicWYTranslationRequest::startToDownload(), MusicFMRadioSongsRequest::startToDownload(), MusicQQDownloadBackgroundRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicDownloadSourceRequest::startToDownload(), MusicDJRadioCategoryRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), MusicDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicDownloadTagDataRequest::startToDownload(), MusicDownloadCounterPVRequest::startToDownload(), MusicFMRadioChannelRequest::startToDownload(), MusicDJRadioProgramRequest::startToDownload(), MusicIdentifySongsRequest::startToDownload(), MusicBDTranslationRequest::startToDownload(), MusicKGQueryArtistListRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicQQQueryArtistListRequest::startToPage(), MusicQQSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicKGQueryRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicQQQueryMovieRequest::startToPage(), MusicQQQueryPlaylistRequest::startToPage(), MusicQQQueryRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicQQPlaylistCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicKWDiscoverListRequest::startToSearch(), MusicKGArtistSimilarRequest::startToSearch(), MusicQQSongSuggestRequest::startToSearch(), MusicKWArtistSimilarRequest::startToSearch(), MusicQQDiscoverListRequest::startToSearch(), MusicKGSongSuggestRequest::startToSearch(), MusicKWSongSuggestRequest::startToSearch(), MusicBDQueryLearnRequest::startToSearch(), MusicQQArtistSimilarRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicQQQueryAlbumRequest::startToSearch(), MusicWYArtistSimilarRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicKGQueryArtistRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSearch(), MusicKWQueryRecommendRequest::startToSearch(), MusicQQQueryRecommendRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicKGQueryAlbumRequest::startToSearch(), MusicKGQueryRecommendRequest::startToSearch(), MusicKGQueryMovieRequest::startToSearch(), MusicWYSongSuggestRequest::startToSearch(), MusicQQQueryMovieRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicKGQueryToplistRequest::startToSearch(), MusicKWQueryToplistRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicQQQueryToplistRequest::startToSearch(), and MusicQQQueryArtistRequest::startToSearch().
volatile MusicObject::NetworkCode MusicAbstractNetwork::m_stateCode protected
Definition at line 93 of file musicabstractnetwork.h.
Referenced by MusicAbstractNetwork(), and ~MusicAbstractNetwork().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicabstractnetwork.h
TTKModule/TTKCore/musicNetworkKits/musicabstractnetwork.cpp