TTKMusicplayer: MusicTranslationThreadAbstract Class Reference
MusicTranslationThreadAbstract Class Reference abstract
The class of translation words abstract thread.
#include <musictranslationthreadabstract.h>
Signals
void downLoadDataChanged (const QString &data)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicTranslationThreadAbstract (QObject *parent=0)
void setRawData (const QVariantMap &data)
virtual void deleteAll () override
virtual void startToDownload (const QString &data)=0
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Attributes
QVariantMap m_rawData
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Detailed Description
The class of translation words abstract thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musictranslationthreadabstract.h.
Constructor & Destructor Documentation
MusicTranslationThreadAbstract::MusicTranslationThreadAbstract (QObject * parent = 0) explicit
Object contsructor.
Definition at line 3 of file musictranslationthreadabstract.cpp.
References MusicNetworkAbstract::m_manager, and MusicNetworkAbstract::m_reply.
Member Function Documentation
void MusicTranslationThreadAbstract::deleteAll () override virtual
Release the network object.
Reimplemented from MusicNetworkAbstract.
Definition at line 20 of file musictranslationthreadabstract.cpp.
References MusicNetworkAbstract::m_reply.
Referenced by MusicWYTranslationThread::downLoadFinished(), MusicTranslationThread::downLoadFinished(), MusicTranslationThread::~MusicTranslationThread(), and MusicWYTranslationThread::~MusicWYTranslationThread().
void MusicTranslationThreadAbstract::downLoadDataChanged (const QString & data) signal
Send translated data from net.
Referenced by MusicWYTranslationThread::downLoadFinished(), MusicTranslationThread::downLoadFinished(), and MusicWYTranslationThread::startToDownload().
QString MusicTranslationThreadAbstract::getClassName () static
Get class object name.
Definition at line 10 of file musictranslationthreadabstract.cpp.
void MusicTranslationThreadAbstract::setRawData (const QVariantMap & data)
Set the current raw data.
Definition at line 15 of file musictranslationthreadabstract.cpp.
References m_rawData.
Referenced by MusicLrcAnalysis::getTranslatedLrc().
virtual void MusicTranslationThreadAbstract::startToDownload (const QString & data) pure virtual
Start to translation data. Subclass should implement this function.
Implemented in MusicTranslationThread, and MusicWYTranslationThread.
Referenced by MusicLrcAnalysis::getTranslatedLrc().
Member Data Documentation
QVariantMap MusicTranslationThreadAbstract::m_rawData protected
Definition at line 61 of file musictranslationthreadabstract.h.
Referenced by setRawData(), and MusicWYTranslationThread::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musictranslationthreadabstract.h
TTKModule/TTKCore/musicNetworkKits/ztl/musictranslationthreadabstract.cpp