TTKMusicplayer: MusicArtistListQueryCategoryItem Class Reference
MusicArtistListQueryCategoryItem Class Reference
The class of the artist list query category item.
#include <musicartistlistquerycategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicResultsCategoryItem &category)
Public Member Functions
MusicArtistListQueryCategoryItem (QWidget *parent=nullptr)
void setCategory (const MusicResultsCategory &category)
Protected Attributes
MusicResultsCategory m_category
Detailed Description
The class of the artist list query category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicartistlistquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicArtistListQueryCategoryItem::MusicArtistListQueryCategoryItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicartistlistquerycategorypopwidget.cpp.
Member Function Documentation
void MusicArtistListQueryCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 49 of file musicartistlistquerycategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicResultsCategory::m_items.
Referenced by setCategory().
void MusicArtistListQueryCategoryItem::categoryChanged (const MusicResultsCategoryItem & category) signal
Current category changed.
Referenced by buttonClicked().
void MusicArtistListQueryCategoryItem::setCategory (const MusicResultsCategory & category)
Set current category.
Definition at line 17 of file musicartistlistquerycategorypopwidget.cpp.
References buttonClicked(), ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicResultsCategory::m_category, m_category, MusicResultsCategory::m_items, MusicClickedGroup::mapped(), MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSColorStyle08, and MusicUIObject::MQSSFontStyle03.
Referenced by MusicArtistListQueryCategoryPopWidget::setCategory().
Member Data Documentation
MusicResultsCategory MusicArtistListQueryCategoryItem::m_category protected
Definition at line 56 of file musicartistlistquerycategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerycategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerycategorypopwidget.cpp