TTKMusicplayer: MusicConnectMobileWidget Class Reference
MusicConnectMobileWidget Class Reference
The class of the connect mobile widget.
#include <musicconnectmobilewidget.h>
Public Member Functions
MusicConnectMobileWidget (QWidget *parent=nullptr)
~MusicConnectMobileWidget ()
Protected Member Functions
void initFirstWidget ()
void initSecondWidget ()
void initThirdWidget ()
Protected Attributes
QMenu m_popMenu
QLabel * m_deviceInfoLabel
MusicTextSliderWidget * m_deviceSizeLabel
MusicDeviceInfoItem m_currentDeviceItem
MusicDeviceInfoModule * m_deviceInfo
MusicAnimationStackedWidget * m_stackedWidget
Private Slots
void changeStatckedWidgetFirst ()
void changeStatckedWidgetSecond ()
void changeStatckedWidgetThird ()
void openTransferFiles2Mobile ()
void deviceTypeChanged (QAction *action)
void updateDeviceInfo ()
Detailed Description
The class of the connect mobile widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicconnectmobilewidget.h.
Constructor & Destructor Documentation
MusicConnectMobileWidget::MusicConnectMobileWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicconnectmobilewidget.cpp.
References CONNECT_MOBILE_INDEX_0, LEFT_SIDE_WIDTH_MIN, and MusicAnimationStackedWidget::LeftToRight.
MusicConnectMobileWidget::~MusicConnectMobileWidget ()
Definition at line 32 of file musicconnectmobilewidget.cpp.
References m_deviceInfo, and m_stackedWidget.
Member Function Documentation
void MusicConnectMobileWidget::changeStatckedWidgetFirst () private slot
Change to main widget.
Definition at line 203 of file musicconnectmobilewidget.cpp.
References m_stackedWidget, and MusicAnimationStackedWidget::start().
Referenced by initSecondWidget(), and initThirdWidget().
void MusicConnectMobileWidget::changeStatckedWidgetSecond () private slot
Change to wireless widget.
Definition at line 208 of file musicconnectmobilewidget.cpp.
References m_stackedWidget, and MusicAnimationStackedWidget::start().
Referenced by initFirstWidget().
void MusicConnectMobileWidget::changeStatckedWidgetThird () private slot
Change to wire widget.
Definition at line 213 of file musicconnectmobilewidget.cpp.
References m_stackedWidget, and MusicAnimationStackedWidget::start().
Referenced by initFirstWidget().
void MusicConnectMobileWidget::deviceTypeChanged (QAction * action) private slot
Device type changed.
Definition at line 230 of file musicconnectmobilewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicDeviceInfoItem::m_availableBytes, m_currentDeviceItem, m_deviceInfoLabel, m_deviceSizeLabel, MusicDeviceInfoItem::m_totalBytes, MusicTextSliderWidget::setBackText(), MusicTextSliderWidget::setFrontText(), MusicTextSliderWidget::setMaxValue(), and MusicTextSliderWidget::setValue().
Referenced by initSecondWidget().
void MusicConnectMobileWidget::initFirstWidget () protected
Init main widget.
Definition at line 38 of file musicconnectmobilewidget.cpp.
References changeStatckedWidgetSecond(), changeStatckedWidgetThird(), m_stackedWidget, MusicUIObject::MQSSColorStyle12, MusicUIObject::MQSSFontStyle05, and MusicUIObject::MQSSPushButtonStyle11.
void MusicConnectMobileWidget::initSecondWidget () protected
Init connect to wireless widget.
Definition at line 78 of file musicconnectmobilewidget.cpp.
References changeStatckedWidgetFirst(), deviceTypeChanged(), m_deviceInfoLabel, m_deviceSizeLabel, m_popMenu, m_stackedWidget, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSPushButtonStyle12, MusicUIObject::MQSSTransferChangedDev, MusicUIObject::MQSSTransferRefreshDev, MusicUIObject::MQSSTransferRing, MusicUIObject::MQSSTransferSong, openTransferFiles2Mobile(), and updateDeviceInfo().
void MusicConnectMobileWidget::initThirdWidget () protected
Init connect to wire widget.
Definition at line 162 of file musicconnectmobilewidget.cpp.
References changeStatckedWidgetFirst(), m_stackedWidget, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSFontStyle05, MusicUIObject::MQSSPushButtonStyle12, QRCodeQWidget::setIcon(), and QRCodeQWidget::setMargin().
void MusicConnectMobileWidget::openTransferFiles2Mobile () private slot
Open transfer files to mobile widget.
Definition at line 218 of file musicconnectmobilewidget.cpp.
References MusicConnectTransferWidget::exec(), m_currentDeviceItem, MusicDeviceInfoItem::m_path, and MusicConnectTransferWidget::setDeviceInfoItem().
Referenced by initSecondWidget().
void MusicConnectMobileWidget::updateDeviceInfo () private slot
Update device info.
Definition at line 242 of file musicconnectmobilewidget.cpp.
References m_deviceInfo, m_popMenu, and MusicDeviceInfoModule::removableDrive().
Referenced by initSecondWidget().
Member Data Documentation
MusicDeviceInfoItem MusicConnectMobileWidget::m_currentDeviceItem protected
Definition at line 86 of file musicconnectmobilewidget.h.
Referenced by deviceTypeChanged(), and openTransferFiles2Mobile().
MusicDeviceInfoModule* MusicConnectMobileWidget::m_deviceInfo protected
Definition at line 87 of file musicconnectmobilewidget.h.
Referenced by updateDeviceInfo(), and ~MusicConnectMobileWidget().
QLabel* MusicConnectMobileWidget::m_deviceInfoLabel protected
Definition at line 84 of file musicconnectmobilewidget.h.
Referenced by deviceTypeChanged(), and initSecondWidget().
MusicTextSliderWidget* MusicConnectMobileWidget::m_deviceSizeLabel protected
Definition at line 85 of file musicconnectmobilewidget.h.
Referenced by deviceTypeChanged(), and initSecondWidget().
QMenu MusicConnectMobileWidget::m_popMenu protected
Definition at line 83 of file musicconnectmobilewidget.h.
Referenced by initSecondWidget(), and updateDeviceInfo().
MusicAnimationStackedWidget* MusicConnectMobileWidget::m_stackedWidget protected
Definition at line 88 of file musicconnectmobilewidget.h.
Referenced by changeStatckedWidgetFirst(), changeStatckedWidgetSecond(), changeStatckedWidgetThird(), initFirstWidget(), initSecondWidget(), initThirdWidget(), and ~MusicConnectMobileWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicconnectmobilewidget.h
TTKModule/TTKWidget/musicToolsKits/musicconnectmobilewidget.cpp