TTKMusicPlayer: TTKAbstractThread Class Reference
TTKAbstractThread Class Reference
The class of the ttk abstract thread.
#include <ttkabstractthread.h>
Public Slots
void start ()
void stop ()
Public Member Functions
TTKAbstractThread (QObject *parent=nullptr)
~TTKAbstractThread ()
Protected Member Functions
virtual void run () override
Protected Attributes
bool m_running
Detailed Description
The class of the ttk abstract thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttkabstractthread.h.
Constructor & Destructor Documentation
TTKAbstractThread::TTKAbstractThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file ttkabstractthread.cpp.
TTKAbstractThread::~TTKAbstractThread ()
Definition at line 10 of file ttkabstractthread.cpp.
Member Function Documentation
void TTKAbstractThread::run () override protected virtual
Thread run now.
Reimplemented in MusicSongCheckToolsQualityThread, MusicSongCheckToolsDuplicateThread, MusicSongCheckToolsRenameThread, MusicSongsManagerThread, MusicImageRenderer, MusicConnectTransferThread, and MusicNetworkTestThread.
Definition at line 31 of file ttkabstractthread.cpp.
Referenced by MusicImageRenderer::run().
void TTKAbstractThread::start () slot
Strat thread now.
Definition at line 25 of file ttkabstractthread.cpp.
References m_running.
Referenced by MusicArtistAlbumsItemWidget::downLoadFinished(), MusicWebDJRadioQueryItemWidget::downLoadFinished(), MusicWebMVRadioQueryItemWidget::downLoadFinished(), MusicPlaylistQueryItemWidget::downLoadFinished(), MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), MusicSongCheckToolsWidget::duplicateReCheckButtonClicked(), MusicMobileSongsManagerWidget::findExtraDevicePath(), MusicSongCheckToolsWidget::qualityReCheckButtonClicked(), MusicSongCheckToolsWidget::renameButtonCheckClicked(), MusicSongCheckToolsWidget::renameReCheckButtonClicked(), MusicNetworkConnectionItem::start(), and MusicConnectTransferWidget::startToTransferFiles().
void TTKAbstractThread::stop () slot
Stop and quit current thread.
Definition at line 15 of file ttkabstractthread.cpp.
References m_running.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), MusicSongCheckToolsWidget::duplicateReCheckButtonClicked(), MusicMobileSongsManagerWidget::findExtraDevicePath(), MusicSongCheckToolsWidget::qualityButtonCheckClicked(), MusicSongCheckToolsWidget::qualityReCheckButtonClicked(), MusicSongCheckToolsWidget::renameButtonCheckClicked(), MusicSongCheckToolsWidget::renameReCheckButtonClicked(), MusicNetworkConnectionItem::stop(), MusicImageRenderer::~MusicImageRenderer(), MusicMobileSongsManagerWidget::~MusicMobileSongsManagerWidget(), and MusicNetworkConnectionItem::~MusicNetworkConnectionItem().
Member Data Documentation
bool TTKAbstractThread::m_running protected
Definition at line 58 of file ttkabstractthread.h.
Referenced by MusicConnectTransferThread::run(), MusicSongsManagerThread::run(), MusicSongCheckToolsRenameThread::run(), MusicSongCheckToolsDuplicateThread::run(), MusicSongCheckToolsQualityThread::run(), start(), and stop().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractthread.h
TTKCommon/TTKLibrary/ttkabstractthread.cpp