TTKMusicplayer: MusicSystemEnvironment Class Reference
MusicSystemEnvironment Class Reference
The class of the system environment object.
#include <musicsystemenvironment.h>
Static Public Member Functions
static QString getData (const QString &data)
static QString getSystemDrive ()
static QString getSystemRoot ()
static QString getProgramData ()
static QString getWinDir ()
static QString getUserName ()
static QString getPublic ()
static QString getLocalAppData ()
static QString getAppData ()
static QString getTMP ()
static QString getTEMP ()
static QString getCommonProgramFiles ()
static QString getCommonProgramW64 ()
static QString getOS ()
Detailed Description
The class of the system environment object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicsystemenvironment.h.
Member Function Documentation
QString MusicSystemEnvironment::getAppData () static
Get app data roming path.
Definition at line 51 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getCommonProgramFiles () static
Get common program files path.
Definition at line 66 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getCommonProgramW64 () static
Get common program w64 path.
Definition at line 71 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getData (const QString & data) static
Get variant data from system environment.
Definition at line 4 of file musicsystemenvironment.cpp.
Referenced by getAppData(), getCommonProgramFiles(), getCommonProgramW64(), getLocalAppData(), getOS(), getProgramData(), getPublic(), getSystemDrive(), getSystemRoot(), getTEMP(), getTMP(), getUserName(), and getWinDir().
QString MusicSystemEnvironment::getLocalAppData () static
Get app data local path.
Definition at line 46 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getOS () static
Get operator system name.
Definition at line 76 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getProgramData () static
Get program data.
Definition at line 26 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getPublic () static
Get public path.
Definition at line 41 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getSystemDrive () static
Get system drive path.
Definition at line 16 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getSystemRoot () static
Get system root path.
Definition at line 21 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getTEMP () static
Get temp path.
Definition at line 61 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getTMP () static
Get temp path.
Definition at line 56 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getUserName () static
Get user name.
Definition at line 36 of file musicsystemenvironment.cpp.
References getData().
QString MusicSystemEnvironment::getWinDir () static
Get win dir path.
Definition at line 31 of file musicsystemenvironment.cpp.
References getData().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicsystemenvironment.h
TTKModule/TTKCore/musicCoreKits/musicsystemenvironment.cpp