TTKMusicPlayer: MusicFunctionToolBoxWidgetItem Class Reference
MusicFunctionToolBoxWidgetItem Class Reference
The class of the function tool box widget item.
#include <musicfunctiontoolboxwidget.h>
Signals
void swapDragItemIndex (int before, int after)
Public Member Functions
MusicFunctionToolBoxWidgetItem (QWidget *parent=nullptr)
MusicFunctionToolBoxWidgetItem (int index, const QString &text, QWidget *parent=nullptr)
~MusicFunctionToolBoxWidgetItem ()
QWidget * item () const
void addCellItem (QWidget *item)
void setTitle (const QString &text)
void setItemExpand (bool expand)
bool itemExpand () const
Protected Member Functions
void initialize ()
virtual void mousePressEvent (QMouseEvent *event) overridefinal
Protected Attributes
QVBoxLayout * m_layout
QWidget * m_item
MusicFunctionToolBoxTopWidget * m_topWidget
Detailed Description
The class of the function tool box widget item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 109 of file musicfunctiontoolboxwidget.h.
Constructor & Destructor Documentation
MusicFunctionToolBoxWidgetItem::MusicFunctionToolBoxWidgetItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 183 of file musicfunctiontoolboxwidget.cpp.
MusicFunctionToolBoxWidgetItem::MusicFunctionToolBoxWidgetItem (int index, const QString & text, QWidget * parent = nullptr) explicit
Definition at line 192 of file musicfunctiontoolboxwidget.cpp.
MusicFunctionToolBoxWidgetItem::~MusicFunctionToolBoxWidgetItem ()
Definition at line 199 of file musicfunctiontoolboxwidget.cpp.
References m_layout, and m_topWidget.
Member Function Documentation
void MusicFunctionToolBoxWidgetItem::addCellItem (QWidget * item)
Create cell item by input item.
Definition at line 210 of file musicfunctiontoolboxwidget.cpp.
References item(), m_item, and m_layout.
Referenced by MusicCloudToolBoxWidget::initialItem(), MusicDownloadToolBoxWidget::initialItem(), MusicSongsToolBoxWidget::initialItem(), and MusicFunctionToolBoxWidget::initialItem().
void MusicFunctionToolBoxWidgetItem::initialize () protected
Init parameter.
Definition at line 239 of file musicfunctiontoolboxwidget.cpp.
References m_layout, m_topWidget, and swapDragItemIndex().
Referenced by MusicNormalToolBoxWidgetItem::MusicNormalToolBoxWidgetItem(), and MusicSongsToolBoxWidgetItem::MusicSongsToolBoxWidgetItem().
QWidget * MusicFunctionToolBoxWidgetItem::item () const
Get widget item.
Definition at line 205 of file musicfunctiontoolboxwidget.cpp.
References m_item.
Referenced by addCellItem(), MusicFunctionToolBoxWidget::removeItem(), MusicSongsToolBoxWidget::setSongSort(), and MusicFunctionToolBoxWidget::setTitle().
bool MusicFunctionToolBoxWidgetItem::itemExpand () const
Get item widget expand state.
Definition at line 230 of file musicfunctiontoolboxwidget.cpp.
References m_item.
void MusicFunctionToolBoxWidgetItem::mousePressEvent (QMouseEvent * event) final override protected virtual
Override the widget event.
Definition at line 251 of file musicfunctiontoolboxwidget.cpp.
void MusicFunctionToolBoxWidgetItem::setItemExpand (bool expand)
Set item widget to hide or not.
Definition at line 221 of file musicfunctiontoolboxwidget.cpp.
References m_item, m_topWidget, and MusicFunctionToolBoxTopWidget::setItemExpand().
Referenced by MusicCloudToolBoxWidget::initialItem(), MusicDownloadToolBoxWidget::initialItem(), MusicSongsToolBoxWidget::initialItem(), and MusicFunctionToolBoxWidget::initialItem().
void MusicFunctionToolBoxWidgetItem::setTitle (const QString & text)
Set title text.
Definition at line 216 of file musicfunctiontoolboxwidget.cpp.
References m_topWidget, and MusicFunctionToolBoxTopWidget::setTitle().
Referenced by MusicFunctionToolBoxWidget::setTitle().
void MusicFunctionToolBoxWidgetItem::swapDragItemIndex (int before, int after) signal
Swap the item index by drag adn drop.
Referenced by initialize().
Member Data Documentation
QWidget* MusicFunctionToolBoxWidgetItem::m_item protected
Definition at line 161 of file musicfunctiontoolboxwidget.h.
Referenced by addCellItem(), item(), itemExpand(), and setItemExpand().
QVBoxLayout* MusicFunctionToolBoxWidgetItem::m_layout protected
Definition at line 160 of file musicfunctiontoolboxwidget.h.
Referenced by addCellItem(), initialize(), and ~MusicFunctionToolBoxWidgetItem().
MusicFunctionToolBoxTopWidget* MusicFunctionToolBoxWidgetItem::m_topWidget protected
Definition at line 162 of file musicfunctiontoolboxwidget.h.
Referenced by initialize(), MusicNormalToolBoxWidgetItem::MusicNormalToolBoxWidgetItem(), MusicSongsToolBoxWidgetItem::MusicSongsToolBoxWidgetItem(), setItemExpand(), MusicSongsToolBoxWidgetItem::setSongSort(), setTitle(), and ~MusicFunctionToolBoxWidgetItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicfunctiontoolboxwidget.h
TTKModule/TTKWidget/musicCoreKits/musicfunctiontoolboxwidget.cpp