TTKMusicPlayer: MusicDispatchManager Class Reference
MusicDispatchManager Class Reference
The class of the functions dispatch manager.
#include <musicdispatchmanager.h>
Public Types
enum Module { Module::Null = -1, Module::FileRemove }
Public Member Functions
void dispatch (Module type)
void dispatch (Module type, void *funcs)
void dispatch (Module type, const TTKVariantList &args)
void dispatch (Module type, const QVariant &arg1)
void dispatch (Module type, const QVariant &arg1, const QVariant &arg2)
void dispatch (Module type, const QVariant &arg1, const QVariant &arg2, const QVariant &arg3)
void dispatch (Module type, const QVariant &arg1, const QVariant &arg2, const QVariant &arg3, const QVariant &arg4)
Private Slots
void activeFunctions ()
Private Member Functions
MusicDispatchManager ()
~MusicDispatchManager ()
Private Attributes
QMutex m_mutex
QTimer * m_timer
QList< MusicDispatchItem * > m_observer
Detailed Description
The class of the functions dispatch manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicdispatchmanager.h.
Member Enumeration Documentation
enum MusicDispatchManager::Module strong
Enumerator
Null
FileRemove
Definition at line 36 of file musicdispatchmanager.h.
Constructor & Destructor Documentation
MusicDispatchManager::MusicDispatchManager () private
Object contsructor.
Definition at line 6 of file musicdispatchmanager.cpp.
References activeFunctions(), and m_timer.
MusicDispatchManager::~MusicDispatchManager () private
Definition at line 16 of file musicdispatchmanager.cpp.
References m_observer, and m_timer.
Member Function Documentation
void MusicDispatchManager::activeFunctions () private slot
Active functions.
Definition at line 78 of file musicdispatchmanager.cpp.
References FileRemove, MusicDispatchItem::isValid(), MusicDispatchItem::m_args, m_mutex, m_observer, MusicDispatchItem::m_times, and MusicDispatchItem::m_type.
Referenced by MusicDispatchManager().
void MusicDispatchManager::dispatch (Module type)
Set dispatch.
Definition at line 23 of file musicdispatchmanager.cpp.
References m_observer, and MusicDispatchItem::m_type.
void MusicDispatchManager::dispatch (Module type, void * funcs)
Definition at line 38 of file musicdispatchmanager.cpp.
References MusicDispatchItem::m_args, m_observer, and MusicDispatchItem::m_type.
void MusicDispatchManager::dispatch (Module type, const TTKVariantList & args)
Definition at line 30 of file musicdispatchmanager.cpp.
References MusicDispatchItem::m_args, m_observer, and MusicDispatchItem::m_type.
void MusicDispatchManager::dispatch (Module type, const QVariant & arg1)
Set dispatch.
Definition at line 46 of file musicdispatchmanager.cpp.
References MusicDispatchItem::m_args, m_observer, and MusicDispatchItem::m_type.
void MusicDispatchManager::dispatch (Module type, const QVariant & arg1, const QVariant & arg2)
Definition at line 54 of file musicdispatchmanager.cpp.
References MusicDispatchItem::m_args, m_observer, and MusicDispatchItem::m_type.
void MusicDispatchManager::dispatch (Module type, const QVariant & arg1, const QVariant & arg2, const QVariant & arg3)
Definition at line 62 of file musicdispatchmanager.cpp.
References MusicDispatchItem::m_args, m_observer, and MusicDispatchItem::m_type.
void MusicDispatchManager::dispatch (Module type, const QVariant & arg1, const QVariant & arg2, const QVariant & arg3, const QVariant & arg4)
Definition at line 70 of file musicdispatchmanager.cpp.
References MusicDispatchItem::m_args, m_observer, and MusicDispatchItem::m_type.
Member Data Documentation
QMutex MusicDispatchManager::m_mutex private
Definition at line 71 of file musicdispatchmanager.h.
Referenced by activeFunctions().
QList<MusicDispatchItem*> MusicDispatchManager::m_observer private
Definition at line 73 of file musicdispatchmanager.h.
Referenced by activeFunctions(), dispatch(), and ~MusicDispatchManager().
QTimer* MusicDispatchManager::m_timer private
Definition at line 72 of file musicdispatchmanager.h.
Referenced by MusicDispatchManager(), and ~MusicDispatchManager().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicdispatchmanager.h
TTKModule/TTKCore/musicCoreKits/musicdispatchmanager.cpp