TTKMusicPlayer: MusicArtistAlbumsQueryWidget Class Reference
MusicArtistAlbumsQueryWidget Class Reference
The class of the artist albums query widget.
#include <musicartistquerywidget.h>
Public Slots
void createArtistAlbumsItem (const MusicResultDataItem &item)
void currentItemClicked (const QString &id)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistAlbumsQueryWidget (QWidget *parent=nullptr)
~MusicArtistAlbumsQueryWidget ()
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameByID (const QString &id) overridefinal
virtual void resizeWidget () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Public Member Functions inherited from TTKAbstractResizeInterface
TTKAbstractResizeInterface ()=default
Private Attributes
QGridLayout * m_gridLayout
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultDataItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Module m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of the artist albums query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 124 of file musicartistquerywidget.h.
Constructor & Destructor Documentation
MusicArtistAlbumsQueryWidget::MusicArtistAlbumsQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 194 of file musicartistquerywidget.cpp.
References MusicSongSharingWidget::Artist, createArtistAlbumsItem(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_container, m_gridLayout, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_shareType, and MusicAbstractItemQueryWidget::m_statusLabel.
MusicArtistAlbumsQueryWidget::~MusicArtistAlbumsQueryWidget ()
Definition at line 212 of file musicartistquerywidget.cpp.
References m_gridLayout.
Member Function Documentation
void MusicArtistAlbumsQueryWidget::createArtistAlbumsItem (const MusicResultDataItem & item) slot
Create the current albums item.
Definition at line 246 of file musicartistquerywidget.cpp.
References currentItemClicked(), LINE_SPACING_SIZE, m_gridLayout, MusicAbstractItemQueryWidget::m_resizeWidgets, and MusicArtistAlbumsItemWidget::setResultDataItem().
Referenced by MusicArtistAlbumsQueryWidget().
void MusicArtistAlbumsQueryWidget::currentItemClicked (const QString & id) slot
Current item clicked.
Definition at line 258 of file musicartistquerywidget.cpp.
References MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicAlbumSearch().
Referenced by createArtistAlbumsItem().
void MusicArtistAlbumsQueryWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 229 of file musicartistquerywidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and MusicAbstractItemQueryWidget::m_resizeWidgets.
Referenced by MusicArtistQueryWidget::resizeWidget().
void MusicArtistAlbumsQueryWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 217 of file musicartistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_songNameFull, MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSingleSearch().
Referenced by MusicArtistQueryWidget::initThirdWidget().
void MusicArtistAlbumsQueryWidget::setSongNameByID (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 223 of file musicartistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_songNameFull, MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSingleSearch().
Member Data Documentation
QGridLayout* MusicArtistAlbumsQueryWidget::m_gridLayout private
Definition at line 159 of file musicartistquerywidget.h.
Referenced by createArtistAlbumsItem(), MusicArtistAlbumsQueryWidget(), resizeWidget(), and ~MusicArtistAlbumsQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.cpp