TTKMusicplayer: MusicToplistFoundCategoryItem Class Reference
MusicToplistFoundCategoryItem Class Reference
The class of the toplist music found category item.
#include <musictoplistfoundcategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicPlaylistCategoryItem &category)
Public Member Functions
MusicToplistFoundCategoryItem (QWidget *parent=0)
void setCategory (const MusicPlaylistCategory &category)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
MusicPlaylistCategory m_category
Detailed Description
The class of the toplist music found category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musictoplistfoundcategorypopwidget.h.
Constructor & Destructor Documentation
MusicToplistFoundCategoryItem::MusicToplistFoundCategoryItem (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 13 of file musictoplistfoundcategorypopwidget.cpp.
Member Function Documentation
void MusicToplistFoundCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 56 of file musictoplistfoundcategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicPlaylistCategory::m_items.
Referenced by setCategory().
void MusicToplistFoundCategoryItem::categoryChanged (const MusicPlaylistCategoryItem & category) signal
Current category changed.
Referenced by buttonClicked().
QString MusicToplistFoundCategoryItem::getClassName () static
Get class object name.
Definition at line 19 of file musictoplistfoundcategorypopwidget.cpp.
void MusicToplistFoundCategoryItem::setCategory (const MusicPlaylistCategory & category)
Set current category.
Definition at line 24 of file musictoplistfoundcategorypopwidget.cpp.
References buttonClicked(), ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicPlaylistCategory::m_category, m_category, MusicPlaylistCategory::m_items, MusicUIObject::MColorStyle03, MusicUIObject::MColorStyle08, and MusicUIObject::MFontStyle03.
Referenced by MusicToplistFoundCategoryPopWidget::setCategory().
Member Data Documentation
MusicPlaylistCategory MusicToplistFoundCategoryItem::m_category protected
Definition at line 60 of file musictoplistfoundcategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musictoplistfoundcategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musictoplistfoundcategorypopwidget.cpp