TTKMusicplayer: MusicExtractWrapper Class Reference
MusicExtractWrapper Class Reference
The class of the extract data wrapper.
#include <musicextractwrapper.h>
Static Public Member Functions
static bool outputThunderSkin (QPixmap &image, const QString &input)
static bool outputBinary (const QString &input)
static bool outputBinary (const QString &input, const QString &output)
static bool outputBinary (const QString &input, const QString &output, QStringList &path)
static bool outputSkin (MusicBackgroundImage *image, const QString &input)
static bool inputSkin (MusicBackgroundImage *image, const QString &output)
static bool outputData (QByteArray &data, const QString &input)
static bool inputData (const QByteArray &data, const QString &output)
Detailed Description
The class of the extract data wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicextractwrapper.h.
Member Function Documentation
bool MusicExtractWrapper::inputData (const QByteArray & data, const QString & output) static
Transfer data to file.
Definition at line 333 of file musicextractwrapper.cpp.
References qPrintable, TTK_LOGGER_ERROR, Z_DEFLATED, zipClose(), zipCloseFileInZip(), zipOpen64(), zipOpenNewFileInZip(), and zipWriteInFileInZip().
bool MusicExtractWrapper::inputSkin (MusicBackgroundImage * image, const QString & output) static
Transfer image data to file.
Definition at line 243 of file musicextractwrapper.cpp.
References MusicUtils::Image::generatePixmapData(), MusicBackgroundImage::m_item, MusicBackgroundImage::m_pix, MUSIC_IMAGE_FILE, qPrintable, SKN_FILE, MusicAbstractXml::toByteArray(), MusicSkinConfigManager::writeSkinData(), XML_FILE, Z_DEFLATED, zipClose(), zipCloseFileInZip(), zipOpen64(), zipOpenNewFileInZip(), and zipWriteInFileInZip().
Referenced by MusicBackgroundSkinDialog::cpoyFileToLocal(), MusicBackgroundSkinDialog::listWidgetItemClicked(), and ToolsSkin::writeClicked().
bool MusicExtractWrapper::outputBinary (const QString & input) static
Transfer file to normal data.
Definition at line 77 of file musicextractwrapper.cpp.
Referenced by MusicObject::generateMusicSongList(), and outputBinary().
bool MusicExtractWrapper::outputBinary (const QString & input, const QString & output) static
Transfer file to normal data.
Definition at line 82 of file musicextractwrapper.cpp.
References outputBinary().
bool MusicExtractWrapper::outputBinary (const QString & input, const QString & output, QStringList & path) static
Transfer file to normal data.
Definition at line 88 of file musicextractwrapper.cpp.
References MH_KB, unz_global_info64_s::number_entry, qPrintable, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
bool MusicExtractWrapper::outputData (QByteArray & data, const QString & input) static
Transfer file to data.
Definition at line 276 of file musicextractwrapper.cpp.
References MH_KB, unz_global_info64_s::number_entry, qPrintable, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
bool MusicExtractWrapper::outputSkin (MusicBackgroundImage * image, const QString & input) static
Transfer file to image data.
Definition at line 158 of file musicextractwrapper.cpp.
References MusicAbstractXml::fromByteArray(), MusicBackgroundImage::m_item, MusicBackgroundImage::m_pix, MH_KB, unz_global_info64_s::number_entry, qPrintable, MusicSkinConfigManager::readSkinData(), SKN_FILE, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), WIN_NAME_MAX_LENGTH, and XML_FILE.
Referenced by MusicLrcPosterItemWidget::MusicLrcPosterItemWidget(), ToolsSkin::readClicked(), MusicWidgetRenderer::setBackgroundPixmap(), MusicBackgroundSkinDialog::setBackgroundUrl(), MusicProgressWidget::show(), MusicDesktopWallpaperThread::timeout(), MusicBackgroundPaletteWidget::updateBackground(), and MusicBackgroundListItem::updatePixImage().
bool MusicExtractWrapper::outputThunderSkin (QPixmap & image, const QString & input) static
Transfer file to image data.
Definition at line 15 of file musicextractwrapper.cpp.
References MH_KB, unz_global_info64_s::number_entry, qPrintable, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
Referenced by MusicBackgroundOnlineWidget::outputRemoteSkin().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicextractwrapper.h
TTKModule/TTKCore/musicCoreKits/musicextractwrapper.cpp