TTKMusicplayer: MusicLrcCommentsWidget Class Reference
MusicLrcCommentsWidget Class Reference
The class of the song comment widget.
#include <musiclrccommentswidget.h>
Public Slots
void createSearchedItems (const MusicSongCommentItem &comments)
void buttonClicked (int index)
void createEMOJILabelWidget ()
void currentEMOJIchanged (const QString &data)
Public Member Functions
MusicLrcCommentsWidget (QWidget *parent=0)
~MusicLrcCommentsWidget ()
void setCurrentSongName (const QString &name)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void wheelEvent (QWheelEvent *event) override
void initLabel (const QString &name, int total)
void deleteCommentsItems ()
void createPagingWidget ()
Protected Attributes
QTextEdit * m_messageEdit
QLabel * m_topLabel
QLabel * m_commentsLabel
QWidget * m_messageComments
MusicDownLoadCommentsThread * m_commentsThread
QList< MusicLrcCommentsItem * > m_commentsItems
MusicPagingWidgetObject * m_pagingWidgetObject
Detailed Description
The class of the song comment widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 58 of file musiclrccommentswidget.h.
Constructor & Destructor Documentation
MusicLrcCommentsWidget::MusicLrcCommentsWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 156 of file musiclrccommentswidget.cpp.
References createEMOJILabelWidget(), createSearchedItems(), initLabel(), m_commentsLabel, m_commentsThread, M_DOWNLOAD_QUERY_PTR, m_messageComments, m_messageEdit, m_pagingWidgetObject, m_topLabel, MusicUIObject::MBackgroundStyle01, MusicUIObject::MBackgroundStyle19, MusicUIObject::MBorderStyle02, MusicUIObject::MColorStyle03, MusicUIObject::MColorStyle04, MusicUIObject::MKGBtnPClose, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, and MusicUIObject::MScrollBarStyle03.
MusicLrcCommentsWidget::~MusicLrcCommentsWidget ()
Definition at line 270 of file musiclrccommentswidget.cpp.
References deleteCommentsItems(), m_commentsLabel, m_commentsThread, m_messageComments, m_messageEdit, m_pagingWidgetObject, and m_topLabel.
Member Function Documentation
void MusicLrcCommentsWidget::buttonClicked (int index) slot
Paging widget button has changed.
Definition at line 310 of file musiclrccommentswidget.cpp.
References MusicPagingWidgetObject::currentIndex(), deleteCommentsItems(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), m_commentsThread, m_pagingWidgetObject, MusicPagingWidgetObject::paging(), and MusicDownLoadPagingThread::startToPage().
Referenced by createPagingWidget().
void MusicLrcCommentsWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 331 of file musiclrccommentswidget.cpp.
void MusicLrcCommentsWidget::createEMOJILabelWidget () slot
Create emoji label widget.
Definition at line 318 of file musiclrccommentswidget.cpp.
References currentEMOJIchanged().
Referenced by MusicLrcCommentsWidget().
void MusicLrcCommentsWidget::createPagingWidget () protected
Create paging items.
Definition at line 370 of file musiclrccommentswidget.cpp.
References buttonClicked(), MusicPagingWidgetObject::createPagingWidget(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), m_commentsThread, m_messageComments, and m_pagingWidgetObject.
Referenced by setCurrentSongName().
void MusicLrcCommentsWidget::createSearchedItems (const MusicSongCommentItem & comments) slot
Create the current song comment.
Definition at line 301 of file musiclrccommentswidget.cpp.
References MusicLrcCommentsItem::createSearchedItems(), m_commentsItems, m_messageComments, and MStatic_cast.
Referenced by MusicLrcCommentsWidget().
void MusicLrcCommentsWidget::currentEMOJIchanged (const QString & data) slot
Current EMOJI changed.
Definition at line 326 of file musiclrccommentswidget.cpp.
References m_messageEdit.
Referenced by createEMOJILabelWidget().
void MusicLrcCommentsWidget::deleteCommentsItems () protected
Delete comments items.
Definition at line 364 of file musiclrccommentswidget.cpp.
References m_commentsItems.
Referenced by buttonClicked(), setCurrentSongName(), and ~MusicLrcCommentsWidget().
QString MusicLrcCommentsWidget::getClassName () static
Get class object name.
Definition at line 281 of file musiclrccommentswidget.cpp.
void MusicLrcCommentsWidget::initLabel (const QString & name, int total) protected
Int current comment label text.
Definition at line 356 of file musiclrccommentswidget.cpp.
References m_commentsLabel, and m_topLabel.
Referenced by MusicLrcCommentsWidget(), and setCurrentSongName().
void MusicLrcCommentsWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 336 of file musiclrccommentswidget.cpp.
void MusicLrcCommentsWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 341 of file musiclrccommentswidget.cpp.
void MusicLrcCommentsWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 346 of file musiclrccommentswidget.cpp.
void MusicLrcCommentsWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 286 of file musiclrccommentswidget.cpp.
References createPagingWidget(), deleteCommentsItems(), MusicSemaphoreLoop::exec(), MusicDownLoadPagingThread::getPageTotal(), initLabel(), m_commentsThread, m_messageComments, MStatic_cast, and MusicDownLoadCommentsThread::startToSearch().
Referenced by MusicLrcContainerForInline::showSongCommentsWidget().
void MusicLrcCommentsWidget::wheelEvent (QWheelEvent * event) override protected virtual
Definition at line 351 of file musiclrccommentswidget.cpp.
Member Data Documentation
QList<MusicLrcCommentsItem*> MusicLrcCommentsWidget::m_commentsItems protected
Definition at line 123 of file musiclrccommentswidget.h.
Referenced by createSearchedItems(), and deleteCommentsItems().
QLabel * MusicLrcCommentsWidget::m_commentsLabel protected
Definition at line 120 of file musiclrccommentswidget.h.
Referenced by initLabel(), MusicLrcCommentsWidget(), and ~MusicLrcCommentsWidget().
MusicDownLoadCommentsThread* MusicLrcCommentsWidget::m_commentsThread protected
Definition at line 122 of file musiclrccommentswidget.h.
Referenced by buttonClicked(), createPagingWidget(), MusicLrcCommentsWidget(), setCurrentSongName(), and ~MusicLrcCommentsWidget().
QWidget* MusicLrcCommentsWidget::m_messageComments protected
Definition at line 121 of file musiclrccommentswidget.h.
Referenced by createPagingWidget(), createSearchedItems(), MusicLrcCommentsWidget(), setCurrentSongName(), and ~MusicLrcCommentsWidget().
QTextEdit* MusicLrcCommentsWidget::m_messageEdit protected
Definition at line 119 of file musiclrccommentswidget.h.
Referenced by currentEMOJIchanged(), MusicLrcCommentsWidget(), and ~MusicLrcCommentsWidget().
MusicPagingWidgetObject* MusicLrcCommentsWidget::m_pagingWidgetObject protected
Definition at line 124 of file musiclrccommentswidget.h.
Referenced by buttonClicked(), createPagingWidget(), MusicLrcCommentsWidget(), and ~MusicLrcCommentsWidget().
QLabel* MusicLrcCommentsWidget::m_topLabel protected
Definition at line 120 of file musiclrccommentswidget.h.
Referenced by initLabel(), MusicLrcCommentsWidget(), and ~MusicLrcCommentsWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccommentswidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrccommentswidget.cpp