TTKMusicplayer: QSyncDeleteData Class Reference
QSyncDeleteData Class Reference
The class of the sync cloud delete data.
#include <qsyncdeletedata.h>
Signals
void deleteFileFinished (bool state)
Public Member Functions
QSyncDeleteData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void deleteDataOperator (const QString &bucket, const QString &fileName)
Public Member Functions inherited from QSyncDataInterface
QSyncDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Protected Slots
virtual void receiveDataFromServer () overridefinal
Protected Slots inherited from QSyncDataInterface
virtual void receiveDataFromServer ()=0
void replyError (QNetworkReply::NetworkError error)
Additional Inherited Members
Protected Member Functions inherited from QSyncDataInterface
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
QSyncDataInterface (QSyncDataInterfacePrivate &pvt, QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Detailed Description
The class of the sync cloud delete data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qsyncdeletedata.h.
Constructor & Destructor Documentation
QSyncDeleteData::QSyncDeleteData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file qsyncdeletedata.cpp.
Member Function Documentation
void QSyncDeleteData::deleteDataOperator (const QString & bucket, const QString & fileName)
Delete data operater.
Definition at line 10 of file qsyncdeletedata.cpp.
References QSyncUtils::GMT(), QSyncConfig::HOST, MusicObject::NetworkError, receiveDataFromServer(), QSyncDataInterface::replyError(), TTK_D, TTK_DOT, and TTK_SEPARATOR.
Referenced by MusicCloudManagerTableWidget::deleteFilesToServer(), and MusicCloudManagerTableWidget::deleteFileToServer().
void QSyncDeleteData::deleteFileFinished (bool state) signal
Delete file finished.
Referenced by receiveDataFromServer().
void QSyncDeleteData::receiveDataFromServer () final override protected virtual slot
Receive data from server.
Definition at line 44 of file qsyncdeletedata.cpp.
References deleteFileFinished(), and TTKObject_cast.
Referenced by deleteDataOperator().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncdeletedata.h
TTKThirdParty/TTKExtras/qsync/qsyncdeletedata.cpp