TTKMusicPlayer: MusicFunctionTableWidget Class Reference
MusicFunctionTableWidget Class Reference
The class of the list table widget.
#include <musicsettingwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void currentIndexChanged (int index)
Public Member Functions
MusicFunctionTableWidget (QWidget *parent=nullptr)
void addFunctionItems (int index, const MusicFunctionItemList &items)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
virtual void leaveEvent (QEvent *event) overridefinal
Private Attributes
int m_listIndex
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the list table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 52 of file musicsettingwidget.h.
Constructor & Destructor Documentation
MusicFunctionTableWidget::MusicFunctionTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 30 of file musicsettingwidget.cpp.
Member Function Documentation
void MusicFunctionTableWidget::addFunctionItems (int index, const MusicFunctionItemList & items)
Add table list items by index and icons and paths.
Definition at line 44 of file musicsettingwidget.cpp.
References MusicFunctionItem::m_icon, m_listIndex, MusicFunctionItem::m_name, MusicUIObject::MQSSColor02, and QtItemSetTextAlignment.
void MusicFunctionTableWidget::currentIndexChanged (int index) signal
Current list index changed.
Referenced by itemCellClicked().
void MusicFunctionTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 67 of file musicsettingwidget.cpp.
References currentIndexChanged(), and m_listIndex.
void MusicFunctionTableWidget::leaveEvent (QEvent * event) final override private virtual
Override the widget event.
Definition at line 74 of file musicsettingwidget.cpp.
References MusicAbstractTableWidget::itemCellEntered().
Member Data Documentation
int MusicFunctionTableWidget::m_listIndex private
Definition at line 85 of file musicsettingwidget.h.
Referenced by addFunctionItems(), and itemCellClicked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsettingwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsettingwidget.cpp