TTKMusicplayer: MusicQueryItemTableWidget Class Reference
MusicQueryItemTableWidget Class Reference abstract
The class of the query item table widget.
#include <musicquerytablewidget.h>
Public Slots
virtual void listCellClicked (int row, int column) override
virtual void clearAllItems () override
virtual void actionGroupClick (QAction *action)
virtual void itemDoubleClicked (int row, int column)=0
void createFinishedItem ()
Public Slots inherited from MusicQueryTableWidget
virtual void clearAllItems ()=0
virtual void createSearchedItem (const MusicSearchedItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void listCellClicked (int row, int column) override
void setSelectedAllItems (bool all)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Public Member Functions
MusicQueryItemTableWidget (QWidget *parent=0)
virtual ~MusicQueryItemTableWidget ()
virtual void startSearchQuery (const QString &text)
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=0)
virtual ~MusicQueryTableWidget ()
virtual void setQueryInput (MusicDownLoadQueryThreadAbstract *query)
MusicDownLoadQueryThreadAbstract * getQueryInput ()
virtual void musicDownloadLocal (int row)=0
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=0)
virtual ~MusicFillItemTableWidget ()
MusicObject::MIntList getSelectedItems () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicQueryTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicFillItemTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
void createContextMenu (QMenu &menu)
virtual void resizeEvent (QResizeEvent *event) override
QString randToGetStrength () const
Protected Member Functions inherited from MusicQueryTableWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
MusicGifLabelWidget * m_loadingLabel
QActionGroup * m_actionGroup
MusicLabelDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicDownLoadQueryThreadAbstract * m_downLoadManager
Protected Attributes inherited from MusicFillItemTableWidget
MusicQueryTableDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void muiscSongToPlayListChanged (const QString &name, const QString &time, const QString &format, bool play)
void showDownLoadInfoFor (MusicObject::DownLoadMode type)
void restartSearchQuery (const QString &name)
Detailed Description
The class of the query item table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 110 of file musicquerytablewidget.h.
Constructor & Destructor Documentation
MusicQueryItemTableWidget::MusicQueryItemTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 45 of file musicquerytablewidget.cpp.
References actionGroupClick(), MusicGifLabelWidget::Gif_Cicle_Blue, itemDoubleClicked(), m_actionGroup, m_labelDelegate, and m_loadingLabel.
MusicQueryItemTableWidget::~MusicQueryItemTableWidget () virtual
Definition at line 56 of file musicquerytablewidget.cpp.
References m_actionGroup, m_labelDelegate, and m_loadingLabel.
Member Function Documentation
void MusicQueryItemTableWidget::actionGroupClick (QAction * action) virtual slot
Left context menu action group click by action.
Definition at line 104 of file musicquerytablewidget.cpp.
References MusicUtils::String::artistName(), MusicQueryTableWidget::musicDownloadLocal(), MusicQueryTableWidget::restartSearchQuery(), and MusicUtils::String::songName().
Referenced by MusicQueryItemTableWidget().
void MusicQueryItemTableWidget::clearAllItems () override virtual slot
Clear All Items.
Definition at line 95 of file musicquerytablewidget.cpp.
References MusicAbstractTableWidget::clear().
Referenced by MusicSoundKMicroSearchTableWidget::clearAllItems(), MusicLrcSearchTableWidget::clearAllItems(), MusicVideoTableWidget::clearAllItems(), and MusicSongSearchOnlineTableWidget::clearAllItems().
void MusicQueryItemTableWidget::createContextMenu (QMenu & menu) protected
Create context menu.
Definition at line 147 of file musicquerytablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), m_actionGroup, MusicQueryTableWidget::m_downLoadManager, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, and MusicUIObject::MMenuStyle02.
Referenced by MusicLrcSearchTableWidget::contextMenuEvent(), MusicSoundKMicroSearchTableWidget::contextMenuEvent(), MusicVideoTableWidget::contextMenuEvent(), and MusicSongSearchOnlineTableWidget::contextMenuEvent().
void MusicQueryItemTableWidget::createFinishedItem () slot
Create the search finished item.
Definition at line 125 of file musicquerytablewidget.cpp.
References MusicDownLoadPagingThread::getPageIndex(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicQueryTableWidget::m_downLoadManager, m_labelDelegate, m_loadingLabel, MUSIC_TEXTS_ROLE, and MusicGifLabelWidget::run().
Referenced by MusicSoundKMicroSearchTableWidget::startSearchQuery(), MusicVideoTableWidget::startSearchQuery(), startSearchQuery(), and MusicVideoTableWidget::startSearchSingleQuery().
QString MusicQueryItemTableWidget::getClassName () static
Get class object name.
Definition at line 63 of file musicquerytablewidget.cpp.
virtual void MusicQueryItemTableWidget::itemDoubleClicked (int row, int column) pure virtual slot
Item has double clicked. Subclass should implement this function.
Referenced by MusicQueryItemTableWidget().
void MusicQueryItemTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 76 of file musicquerytablewidget.cpp.
References MusicDownLoadPagingThread::getPageIndex(), MusicFillItemTableWidget::listCellClicked(), MusicQueryTableWidget::m_downLoadManager, m_loadingLabel, MUSIC_TEXTS_ROLE, MusicGifLabelWidget::run(), and MusicDownLoadPagingThread::startToPage().
Referenced by MusicLrcSearchTableWidget::listCellClicked(), MusicSoundKMicroSearchTableWidget::listCellClicked(), MusicVideoTableWidget::listCellClicked(), and MusicSongSearchOnlineTableWidget::listCellClicked().
QString MusicQueryItemTableWidget::randToGetStrength () const protected
Get current random video hotter(simulate).
Definition at line 173 of file musicquerytablewidget.cpp.
Referenced by MusicSoundKMicroSearchTableWidget::createSearchedItem(), MusicLrcSearchTableWidget::createSearchedItem(), MusicVideoTableWidget::createSearchedItem(), and MusicSongSearchOnlineTableWidget::createSearchedItem().
void MusicQueryItemTableWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicSongSearchOnlineTableWidget.
Definition at line 167 of file musicquerytablewidget.cpp.
References m_loadingLabel.
Referenced by MusicSongSearchOnlineTableWidget::resizeEvent().
void MusicQueryItemTableWidget::startSearchQuery (const QString & text) virtual
Start search query by text.
Implements MusicQueryTableWidget.
Reimplemented in MusicSongSearchOnlineTableWidget, MusicVideoTableWidget, MusicSoundKMicroSearchTableWidget, and MusicLrcSearchTableWidget.
Definition at line 68 of file musicquerytablewidget.cpp.
References createFinishedItem(), M_DOWNLOAD_QUERY_PTR, and MusicQueryTableWidget::setQueryInput().
Referenced by MusicSongSearchOnlineTableWidget::setSearchQuality(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSongSearchOnlineTableWidget::startSearchQuery(), and MusicSongSearchOnlineTableWidget::startSearchSingleQuery().
Member Data Documentation
QActionGroup* MusicQueryItemTableWidget::m_actionGroup protected
Definition at line 168 of file musicquerytablewidget.h.
Referenced by MusicSongSearchOnlineTableWidget::contextMenuEvent(), createContextMenu(), MusicQueryItemTableWidget(), and ~MusicQueryItemTableWidget().
MusicLabelDelegate* MusicQueryItemTableWidget::m_labelDelegate protected
Definition at line 169 of file musicquerytablewidget.h.
Referenced by createFinishedItem(), MusicQueryItemTableWidget(), and ~MusicQueryItemTableWidget().
MusicGifLabelWidget* MusicQueryItemTableWidget::m_loadingLabel protected
Definition at line 167 of file musicquerytablewidget.h.
Referenced by createFinishedItem(), listCellClicked(), MusicQueryItemTableWidget(), resizeEvent(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSoundKMicroSearchTableWidget::startSearchQuery(), MusicVideoTableWidget::startSearchQuery(), MusicSongSearchOnlineTableWidget::startSearchQuery(), MusicVideoTableWidget::startSearchSingleQuery(), MusicSongSearchOnlineTableWidget::startSearchSingleQuery(), and ~MusicQueryItemTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicquerytablewidget.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicquerytablewidget.cpp