TTKMusicplayer: MusicRemoteWidget Class Reference
MusicRemoteWidget Class Reference
The class of the desktop remote widget base.
#include <musicremotewidget.h>
Public Types
enum RemoteType {
Null = 0, Circle, Square, Rectangle,
SimpleStyle, ComplexStyle, Diamond, Ripples
}
Public Slots
void musicVolumeChanged (int value)
void show ()
bool close ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void musicWindowSignal ()
void musicKeySignal ()
void musicPlayPreviousSignal ()
void musicPlayNextSignal ()
void musicVolumeSignal (int value)
void musicSettingSignal ()
void musicRemoteTypeChanged (QAction *type)
Public Member Functions
MusicRemoteWidget (QWidget *parent=0)
virtual ~MusicRemoteWidget ()
void showPlayStatus (bool status) const
void setVolumeValue (int index)
virtual void setLabelText (const QString &text)
int mapRemoteTypeIndex ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
void adjustPostion (QWidget *w)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
QPushButton * m_showMainWindow
QPushButton * m_PreSongButton
QPushButton * m_NextSongButton
QPushButton * m_PlayButton
QPushButton * m_SettingButton
QWidget * m_mainWidget
QWidget * m_volumeWidget
QToolButton * m_volumeButton
MusicClickedSlider * m_volumeSlider
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the desktop remote widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 26 of file musicremotewidget.h.
Member Enumeration Documentation
enum MusicRemoteWidget::RemoteType
Enumerator
Null
Romote Null type
Circle
Romote Circle type
Square
Romote Square type
Rectangle
Romote Rectangle type
SimpleStyle
Romote SimpleStyle type
ComplexStyle
Romote ComplexStyle type
Diamond
Romote Diamond type
Ripples
Romote Ripples type
Definition at line 30 of file musicremotewidget.h.
Constructor & Destructor Documentation
MusicRemoteWidget::MusicRemoteWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 14 of file musicremotewidget.cpp.
References MusicAbstractMoveWidget::drawWindowShadow(), m_mainWidget, m_NextSongButton, m_PlayButton, m_PreSongButton, m_SettingButton, m_showMainWindow, m_volumeButton, m_volumeSlider, m_volumeWidget, MusicUIObject::MBackgroundStyle04, MusicUIObject::MKGTinyBtnNext, MusicUIObject::MKGTinyBtnPlay, MusicUIObject::MKGTinyBtnPrevious, MusicUIObject::MKGTinyBtnSetting, MusicUIObject::MPushButtonStyle02, MusicUIObject::MSliderStyle01, musicKeySignal(), musicPlayNextSignal(), musicPlayPreviousSignal(), musicSettingSignal(), musicVolumeChanged(), and musicWindowSignal().
MusicRemoteWidget::~MusicRemoteWidget () virtual
Definition at line 92 of file musicremotewidget.cpp.
References m_mainWidget, m_NextSongButton, m_PlayButton, m_PreSongButton, m_SettingButton, m_showMainWindow, m_volumeButton, m_volumeSlider, and m_volumeWidget.
Member Function Documentation
void MusicRemoteWidget::adjustPostion (QWidget * w) protected
Adjust the widget postion.
Definition at line 214 of file musicremotewidget.cpp.
References M_SETTING_PTR, and MusicSettingManager::ScreenSize.
Referenced by MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), and MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip().
bool MusicRemoteWidget::close () slot
Override close function.
Definition at line 170 of file musicremotewidget.cpp.
References M_SETTING_PTR, Null, and MusicSettingManager::RemoteWidgetModeChoiced.
Referenced by contextMenuEvent().
void MusicRemoteWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicRemoteWidgetForStrip.
Definition at line 176 of file musicremotewidget.cpp.
References Circle, close(), ComplexStyle, Diamond, MusicUIObject::MMenuStyle03, MObject_cast, musicRemoteTypeChanged(), musicWindowSignal(), Rectangle, Ripples, SimpleStyle, and Square.
QString MusicRemoteWidget::getClassName () static
Get class object name.
Definition at line 105 of file musicremotewidget.cpp.
int MusicRemoteWidget::mapRemoteTypeIndex ()
Map remote type to index.
Definition at line 128 of file musicremotewidget.cpp.
References Circle, ComplexStyle, Diamond, MObject_cast, Null, Rectangle, Ripples, SimpleStyle, and Square.
Referenced by MusicTopAreaWidget::musicWallpaperRemote(), and show().
void MusicRemoteWidget::musicKeySignal () signal
Set current play state.
Referenced by MusicRemoteWidget().
void MusicRemoteWidget::musicPlayNextSignal () signal
Set current play to next.
Referenced by MusicRemoteWidget().
void MusicRemoteWidget::musicPlayPreviousSignal () signal
Set current play to previous.
Referenced by MusicRemoteWidget().
void MusicRemoteWidget::musicRemoteTypeChanged (QAction * type) signal
Change diff remote style by type.
Referenced by contextMenuEvent().
void MusicRemoteWidget::musicSettingSignal () signal
Show current setting widget.
Referenced by MusicRemoteWidget().
void MusicRemoteWidget::musicVolumeChanged (int value) slot
Set current play volume change by value.
Definition at line 140 of file musicremotewidget.cpp.
References m_volumeButton, MusicUIObject::MKGTinyBtnSoundWhite, and musicVolumeSignal().
Referenced by MusicRemoteWidget(), and setVolumeValue().
void MusicRemoteWidget::musicVolumeSignal (int value) signal
Set current play volume by value.
Referenced by musicVolumeChanged().
void MusicRemoteWidget::musicWindowSignal () signal
Set show application normal.
Referenced by MusicRemoteWidgetForStrip::contextMenuEvent(), contextMenuEvent(), and MusicRemoteWidget().
void MusicRemoteWidget::setLabelText (const QString & text) virtual
Set current song text.
Reimplemented in MusicRemoteWidgetForRectangle, MusicRemoteWidgetForRipples, MusicRemoteWidgetForSimpleStyle, MusicRemoteWidgetForStrip, and MusicRemoteWidgetForComplexStyle.
Definition at line 123 of file musicremotewidget.cpp.
Referenced by MusicTopAreaWidget::musicComplexStyleRemote(), MusicTopAreaWidget::musicRectangleRemote(), MusicTopAreaWidget::musicRipplesRemote(), MusicTopAreaWidget::musicSimpleStyleRemote(), MusicTopAreaWidget::musicWallpaperRemote(), and MusicTopAreaWidget::setLabelText().
void MusicRemoteWidget::setVolumeValue (int index)
Set current volume value by index.
Definition at line 115 of file musicremotewidget.cpp.
References m_volumeSlider, and musicVolumeChanged().
Referenced by MusicTopAreaWidget::createRemoteWidget(), and MusicTopAreaWidget::setVolumeValue().
void MusicRemoteWidget::show () slot
Override show function.
Definition at line 164 of file musicremotewidget.cpp.
References M_SETTING_PTR, mapRemoteTypeIndex(), and MusicSettingManager::RemoteWidgetModeChoiced.
Referenced by MusicTopAreaWidget::createRemoteWidget().
void MusicRemoteWidget::showPlayStatus (bool status) const
Set current play state button.
Definition at line 110 of file musicremotewidget.cpp.
References m_PlayButton, MusicUIObject::MKGTinyBtnPause, and MusicUIObject::MKGTinyBtnPlay.
Referenced by MusicTopAreaWidget::createRemoteWidget(), and MusicTopAreaWidget::showPlayStatus().
Member Data Documentation
QWidget* MusicRemoteWidget::m_mainWidget protected
Definition at line 127 of file musicremotewidget.h.
Referenced by MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), and ~MusicRemoteWidget().
QPushButton* MusicRemoteWidget::m_NextSongButton protected
Definition at line 125 of file musicremotewidget.h.
Referenced by MusicRemoteWidgetForSquare::enterTimeout(), MusicRemoteWidgetForSquare::leaveTimeout(), MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), and ~MusicRemoteWidget().
QPushButton * MusicRemoteWidget::m_PlayButton protected
Definition at line 125 of file musicremotewidget.h.
Referenced by MusicRemoteWidgetForSquare::enterTimeout(), MusicRemoteWidgetForSquare::leaveTimeout(), MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), showPlayStatus(), and ~MusicRemoteWidget().
QPushButton * MusicRemoteWidget::m_PreSongButton protected
Definition at line 124 of file musicremotewidget.h.
Referenced by MusicRemoteWidgetForSquare::enterTimeout(), MusicRemoteWidgetForSquare::leaveTimeout(), MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), and ~MusicRemoteWidget().
QPushButton* MusicRemoteWidget::m_SettingButton protected
Definition at line 126 of file musicremotewidget.h.
Referenced by MusicRemoteWidgetForSquare::enterTimeout(), MusicRemoteWidgetForSquare::leaveTimeout(), MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), and ~MusicRemoteWidget().
QPushButton* MusicRemoteWidget::m_showMainWindow protected
Definition at line 124 of file musicremotewidget.h.
Referenced by MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), and ~MusicRemoteWidget().
QToolButton* MusicRemoteWidget::m_volumeButton protected
Definition at line 128 of file musicremotewidget.h.
Referenced by MusicRemoteWidget(), musicVolumeChanged(), and ~MusicRemoteWidget().
MusicClickedSlider* MusicRemoteWidget::m_volumeSlider protected
Definition at line 129 of file musicremotewidget.h.
Referenced by MusicRemoteWidget(), setVolumeValue(), and ~MusicRemoteWidget().
QWidget * MusicRemoteWidget::m_volumeWidget protected
Definition at line 127 of file musicremotewidget.h.
Referenced by MusicRemoteWidget(), MusicRemoteWidgetForCircle::MusicRemoteWidgetForCircle(), MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle(), MusicRemoteWidgetForDiamond::MusicRemoteWidgetForDiamond(), MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle(), MusicRemoteWidgetForRipples::MusicRemoteWidgetForRipples(), MusicRemoteWidgetForSimpleStyle::MusicRemoteWidgetForSimpleStyle(), MusicRemoteWidgetForSquare::MusicRemoteWidgetForSquare(), MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip(), and ~MusicRemoteWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicRemoteKits/musicremotewidget.h
TTKModule/TTKWidget/musicRemoteKits/musicremotewidget.cpp