TTKMusicplayer: MusicItemSearchEdit Class Reference
MusicItemSearchEdit Class Reference
The class of the search line edit widget.
#include <musicitemsearchedit.h>
Public Member Functions
MusicItemSearchEdit (QWidget *parent=nullptr)
~MusicItemSearchEdit ()
MusicSearchEdit * editor () const
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
Private Attributes
MusicSearchEdit * m_searchEdit
Detailed Description
The class of the search line edit widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicitemsearchedit.h.
Constructor & Destructor Documentation
MusicItemSearchEdit::MusicItemSearchEdit (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musicitemsearchedit.cpp.
References m_searchEdit, and MusicUIObject::MQSSBackgroundStyle01.
MusicItemSearchEdit::~MusicItemSearchEdit ()
Definition at line 20 of file musicitemsearchedit.cpp.
References m_searchEdit.
Member Function Documentation
MusicSearchEdit* MusicItemSearchEdit::editor () const inline
Get the line eidtor.
Definition at line 41 of file musicitemsearchedit.h.
Referenced by MusicSongSearchDialog::clear(), MusicSongSearchDialog::MusicSongSearchDialog(), MusicAdvancedSearchedWidget::searchButtonClicked(), MusicSongSearchDialog::setVisible(), MusicSongSearchDialog::text(), and MusicAdvancedSearchedWidget::updateServerPlaceholderText().
void MusicItemSearchEdit::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 25 of file musicitemsearchedit.cpp.
Member Data Documentation
MusicSearchEdit* MusicItemSearchEdit::m_searchEdit private
Definition at line 49 of file musicitemsearchedit.h.
Referenced by MusicItemSearchEdit(), and ~MusicItemSearchEdit().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicitemsearchedit.h
TTKModule/TTKWidget/musicSearchKits/musicitemsearchedit.cpp