TTKMusicplayer: MusicAlbumFoundWidget Class Reference
MusicAlbumFoundWidget Class Reference
The class of album music found widget.
#include <musicalbumfoundwidget.h>
Public Slots
void queryAllFinished ()
void queryAlbumFinished ()
void createAlbumInfoItem (const MusicResultsItem &item)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicAlbumFoundWidget (QWidget *parent=nullptr)
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=nullptr)
~MusicFoundAbstractWidget ()
void initWidget ()
Protected Member Functions
void createLabels ()
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Additional Inherited Members
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Detailed Description
The class of album music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 50 of file musicalbumfoundwidget.h.
Constructor & Destructor Documentation
MusicAlbumFoundWidget::MusicAlbumFoundWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 34 of file musicalbumfoundwidget.cpp.
References MusicSongSharingWidget::Album, M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_downloadThread, MusicFoundAbstractWidget::m_foundTableWidget, MusicFoundAbstractWidget::m_shareType, and queryAllFinished().
Member Function Documentation
void MusicAlbumFoundWidget::createAlbumInfoItem (const MusicResultsItem & item) slot
Create the current album info item.
Definition at line 131 of file musicalbumfoundwidget.cpp.
References COVER_URL_NULL, createLabels(), MusicFoundAbstractWidget::downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, MusicFoundAbstractWidget::m_currentPlaylistItem, MusicResultsItem::m_description, MusicResultsItem::m_name, MusicFoundAbstractWidget::m_resizeWidgets, MusicDownloadSourceThread::startToDownload(), and TTK_STR_SPLITER.
Referenced by setSongNameById().
void MusicAlbumFoundWidget::createLabels () protected
Create init interface lables.
Definition at line 185 of file musicalbumfoundwidget.cpp.
References MusicFoundAbstractWidget::initFirstWidget(), MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_iconLabel, MusicFoundAbstractWidget::m_mainWindow, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_songButton, MusicFoundAbstractWidget::m_statusLabel, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSColorStyle05, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSFontStyle06, MusicUIObject::MQSSPushButtonStyle03, MusicUIObject::MQSSScrollBarStyle01, MusicFoundAbstractWidget::playAllButtonClicked(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), and MusicFoundAbstractWidget::shareButtonClicked().
Referenced by createAlbumInfoItem().
void MusicAlbumFoundWidget::queryAlbumFinished () slot
Query album musics is finished.
Definition at line 112 of file musicalbumfoundwidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicQueryTableWidget::getQueryInput(), MusicFoundAbstractWidget::m_foundTableWidget, MusicFoundAbstractWidget::m_statusLabel, and MusicFoundAbstractWidget::setSongCountText().
void MusicAlbumFoundWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 85 of file musicalbumfoundwidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicObject::MusicSongInformation::m_albumId, MusicFoundAbstractWidget::m_downloadThread, MusicObject::MusicSongInformation::m_songName, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::m_statusLabel, and setSongNameById().
Referenced by MusicAlbumFoundWidget().
void MusicAlbumFoundWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicFoundAbstractWidget.
Definition at line 60 of file musicalbumfoundwidget.cpp.
References MusicUtils::Widget::elidedText(), MusicFoundAbstractWidget::m_foundTableWidget, MusicFoundAbstractWidget::m_resizeWidgets, M_SETTING_PTR, MusicQueryFoundTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
void MusicAlbumFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 44 of file musicalbumfoundwidget.cpp.
References MusicUtils::String::artistName(), MusicFoundAbstractWidget::m_downloadThread, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), MusicDownLoadQueryThreadAbstract::setQuerySimplify(), MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicRightAreaWidget::musicAlbumFound().
void MusicAlbumFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 52 of file musicalbumfoundwidget.cpp.
References createAlbumInfoItem(), M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_foundTableWidget, MusicQueryFoundTableWidget::setQueryInput(), and MusicQueryFoundTableWidget::startSearchQuery().
Referenced by MusicRightAreaWidget::musicAlbumFound(), and queryAllFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicalbumfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicalbumfoundwidget.cpp