TTKMusicplayer: MusicASXConfigManager Class Reference
MusicASXConfigManager Class Reference
The class of the asx playlist Config Manager.
#include <musicasxconfigmanager.h>
Public Member Functions
MusicASXConfigManager ()
virtual bool readPlaylistData (MusicSongItems &items) overridefinal
virtual bool writePlaylistData (const MusicSongItems &items, const QString &path) overridefinal
Public Member Functions inherited from MusicAbstractXml
MusicAbstractXml (QObject *parent=nullptr)
~MusicAbstractXml ()
bool readConfig (const QString &name)
bool writeConfig (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagNameValue (const QString &tagName) const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName) const
QString readXmlTextByTagName (const QString &tagName) const
TTKVariantMap readXmlAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const MusicXmlAttribute &attr)
QDomElement createRoot (const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const MusicXmlAttribute &attr)
QDomElement writeDomElementMutil (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const MusicXmlAttribute &attr, const QString &text)
QDomElement writeDomElementMutilText (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const MusicXmlAttribute &attr)
Additional Inherited Members
Protected Attributes inherited from MusicAbstractXml
QFile * m_file
QDomDocument * m_document
Private Member Functions inherited from MusicPlaylistInterface
MusicPlaylistInterface ()
virtual ~MusicPlaylistInterface ()
Detailed Description
The class of the asx playlist Config Manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicasxconfigmanager.h.
Constructor & Destructor Documentation
MusicASXConfigManager::MusicASXConfigManager () explicit
Object contsructor.
Definition at line 3 of file musicasxconfigmanager.cpp.
Member Function Documentation
bool MusicASXConfigManager::readPlaylistData (MusicSongItems & items) final override virtual
Read datas from config file.
Implements MusicPlaylistInterface.
Definition at line 10 of file musicasxconfigmanager.cpp.
References MusicXmlNodeHelper::load(), MusicAbstractXml::m_document, MusicAbstractXml::m_file, MusicSongItem::m_itemName, and MusicSongItem::m_songs.
Referenced by MusicPlaylistManager::readASXConfig().
bool MusicASXConfigManager::writePlaylistData (const MusicSongItems & items, const QString & path) final override virtual
Write datas into config file.
Implements MusicPlaylistInterface.
Definition at line 52 of file musicasxconfigmanager.cpp.
References APP_NAME, MusicAbstractXml::createRoot(), MusicAbstractXml::m_document, MusicAbstractXml::m_file, MusicSongItem::m_itemName, MusicAbstractXml::writeConfig(), MusicAbstractXml::writeDomElement(), MusicAbstractXml::writeDomNode(), and MusicAbstractXml::writeDomText().
Referenced by MusicPlaylistManager::writeASXConfig().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musicasxconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musicasxconfigmanager.cpp