TTKMusicplayer: MusicPlayedlist Class Reference
MusicPlayedlist Class Reference
The class of the music playedlist.
#include <musicplayedlist.h>
Public Slots
void setCurrentIndex (int index=DEFAULT_INDEX_LEVEL1)
void setCurrentIndex (int toolIndex, const QString &path)
Signals
void currentIndexChanged (int index)
void playbackModeChanged (MusicObject::PlayMode mode)
Public Member Functions
MusicPlayedlist (QObject *parent=0)
MusicObject::PlayMode playbackMode () const
void setPlaybackMode (MusicObject::PlayMode mode)
int mapItemIndex (const MusicPlayedItem &item) const
int currentIndex () const
MusicPlayedItem currentItem () const
QString currentMediaString () const
MusicPlayedItems mediaListConst () const
MusicPlayedItems * mediaList ()
int mediaCount () const
bool isEmpty () const
bool clear ()
int find (int toolIndex, const QString &content, int from=0)
void addMedia (int toolIndex, const QString &content)
void addMedia (int toolIndex, const QStringList &items)
void addMedia (const MusicPlayedItem &item)
void addMedia (const MusicPlayedItems &items)
void appendMedia (int toolIndex, const QString &content)
void appendMedia (int toolIndex, const QStringList &items)
void appendMedia (const MusicPlayedItem &item)
void appendMedia (const MusicPlayedItems &items)
MusicPlayedItems laterListConst () const
void insertLaterMedia (int toolIndex, const QString &content)
void laterListClear ()
bool removeMedia (int pos)
int removeMedia (int toolIndex, const QString &content)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
int m_currentIndex
MusicPlayedItems m_mediaList
MusicPlayedItems m_laterMediaList
MusicObject::PlayMode m_playbackMode
Detailed Description
The class of the music playedlist.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 60 of file musicplayedlist.h.
Constructor & Destructor Documentation
MusicPlayedlist::MusicPlayedlist (QObject * parent = 0) explicit
Definition at line 4 of file musicplayedlist.cpp.
References m_currentIndex, m_playbackMode, MusicObject::PM_PlayOrder, and MusicTime::timeSRand().
Member Function Documentation
void MusicPlayedlist::addMedia (int toolIndex, const QString & content)
Add music media, not append remember.
Definition at line 93 of file musicplayedlist.cpp.
References m_laterMediaList, and m_mediaList.
Referenced by MusicApplication::readXMLConfigFromText(), and MusicApplication::setMusicPlayIndex().
void MusicPlayedlist::addMedia (int toolIndex, const QStringList & items)
Add music media list, not append remember.
Definition at line 100 of file musicplayedlist.cpp.
References m_laterMediaList, and m_mediaList.
void MusicPlayedlist::addMedia (const MusicPlayedItem & item)
Add music media list, not append remember.
Definition at line 110 of file musicplayedlist.cpp.
References m_laterMediaList, and m_mediaList.
void MusicPlayedlist::addMedia (const MusicPlayedItems & items)
Add music media list, not append remember.
Definition at line 117 of file musicplayedlist.cpp.
References m_laterMediaList, and m_mediaList.
void MusicPlayedlist::appendMedia (int toolIndex, const QString & content)
Append music medias.
Definition at line 123 of file musicplayedlist.cpp.
References m_mediaList.
Referenced by MusicPlayedListPopWidget::append().
void MusicPlayedlist::appendMedia (int toolIndex, const QStringList & items)
Append music medias.
Definition at line 128 of file musicplayedlist.cpp.
References m_mediaList.
void MusicPlayedlist::appendMedia (const MusicPlayedItem & item)
Append music media.
Definition at line 136 of file musicplayedlist.cpp.
References m_mediaList.
void MusicPlayedlist::appendMedia (const MusicPlayedItems & items)
Append music medias.
Definition at line 141 of file musicplayedlist.cpp.
References m_mediaList.
bool MusicPlayedlist::clear ()
Clear current medias.
Definition at line 82 of file musicplayedlist.cpp.
References isEmpty(), and m_mediaList.
Referenced by MusicApplication::musicPlayIndex(), and MusicApplication::setMusicPlayIndex().
int MusicPlayedlist::currentIndex () const
Get current play index.
Definition at line 43 of file musicplayedlist.cpp.
References m_currentIndex.
Referenced by MusicApplication::checkMusicListCurrentIndex(), MusicApplication::getCurrentFileName(), MusicApplication::getCurrentFilePath(), MusicPlayer::playNext(), MusicPlayer::playPrevious(), MusicPlayedListPopWidget::setCurrentIndex(), MusicApplication::setDeleteItemAt(), and MusicPlayer::update().
void MusicPlayedlist::currentIndexChanged (int index) signal
Current play index changed emit.
Referenced by setCurrentIndex().
MusicPlayedItem MusicPlayedlist::currentItem () const
Get current play item.
Definition at line 48 of file musicplayedlist.cpp.
References m_currentIndex, and m_mediaList.
Referenced by currentMediaString(), MusicApplication::musicAddSongToLovestListAt(), MusicApplication::musicCurrentPlayLocation(), MusicApplication::musicDownloadContains(), MusicApplication::musicLovestContains(), MusicApplication::setDeleteItemAt(), MusicApplication::showCurrentSong(), and MusicApplication::writeXMLConfigToText().
QString MusicPlayedlist::currentMediaString () const
Get current play music media path.
Definition at line 57 of file musicplayedlist.cpp.
References currentItem(), and MusicPlayedItem::m_path.
Referenced by MusicApplication::getCurrentFileName(), MusicApplication::getCurrentFilePath(), and MusicPlayer::play().
int MusicPlayedlist::find (int toolIndex, const QString & content, int from = 0)
Find item by index and content.
Definition at line 88 of file musicplayedlist.cpp.
References m_mediaList.
Referenced by removeMedia(), and MusicApplication::setDeleteItemAt().
QString MusicPlayedlist::getClassName () static
Get class object name.
Definition at line 12 of file musicplayedlist.cpp.
void MusicPlayedlist::insertLaterMedia (int toolIndex, const QString & content)
Insert music media by index and content.
Definition at line 151 of file musicplayedlist.cpp.
References m_currentIndex, m_laterMediaList, and m_mediaList.
Referenced by MusicPlayedListPopWidget::insert().
bool MusicPlayedlist::isEmpty () const
Check current medias is empty.
Definition at line 77 of file musicplayedlist.cpp.
References m_mediaList.
Referenced by clear(), MusicApplication::musicAddSongToLovestListAt(), MusicApplication::musicCurrentPlayLocation(), MusicApplication::musicPlayNext(), MusicApplication::musicPlayPrevious(), MusicApplication::musicStatePlay(), MusicPlayer::play(), MusicApplication::positionChanged(), MusicPlayedListPopWidget::setDeleteItemAt(), and MusicApplication::setPlaySongChanged().
void MusicPlayedlist::laterListClear ()
Remove music all media.
Definition at line 162 of file musicplayedlist.cpp.
References m_laterMediaList.
Referenced by MusicPlayedListPopWidget::cellDoubleClicked(), and removeMedia().
MusicPlayedItems MusicPlayedlist::laterListConst () const
Get later music media path.
Definition at line 146 of file musicplayedlist.cpp.
References m_laterMediaList.
Referenced by MusicPlayedListPopWidget::insert().
int MusicPlayedlist::mapItemIndex (const MusicPlayedItem & item) const
Map item index at container.
Definition at line 27 of file musicplayedlist.cpp.
References m_mediaList.
Referenced by setCurrentIndex().
int MusicPlayedlist::mediaCount () const
Get current medias count.
Definition at line 72 of file musicplayedlist.cpp.
References m_mediaList.
Referenced by MusicApplication::musicImportPlay(), MusicApplication::musicPlayIndex(), MusicPlayer::playNext(), MusicApplication::setDeleteItemAt(), and MusicApplication::setPlaySongChanged().
MusicPlayedItems * MusicPlayedlist::mediaList ()
Get all music media path.
Definition at line 67 of file musicplayedlist.cpp.
References m_mediaList.
Referenced by MusicPlayedListPopWidget::resetToolIndex().
MusicPlayedItems MusicPlayedlist::mediaListConst () const
Get all music media path.
Definition at line 62 of file musicplayedlist.cpp.
References m_mediaList.
MusicObject::PlayMode MusicPlayedlist::playbackMode () const
Get current play mode.
Definition at line 17 of file musicplayedlist.cpp.
References m_playbackMode.
Referenced by MusicApplication::getPlayMode(), MusicApplication::musicCreateRightMenu(), MusicApplication::musicPlayNext(), MusicApplication::musicPlayPrevious(), MusicPlayer::update(), and MusicApplication::writeXMLConfigToText().
void MusicPlayedlist::playbackModeChanged (MusicObject::PlayMode mode) signal
Current play mode changed emit.
bool MusicPlayedlist::removeMedia (int pos)
Remove music media from current medias by index pos.
Definition at line 167 of file musicplayedlist.cpp.
References laterListClear(), and m_mediaList.
Referenced by MusicPlayedListPopWidget::remove(), and MusicPlayedListPopWidget::setDeleteItemAt().
int MusicPlayedlist::removeMedia (int toolIndex, const QString & content)
Remove music media from current medias by index pos.
Definition at line 178 of file musicplayedlist.cpp.
References find(), laterListClear(), and m_mediaList.
void MusicPlayedlist::setCurrentIndex (int index = DEFAULT_INDEX_LEVEL1) slot
Set current play index.
Definition at line 190 of file musicplayedlist.cpp.
References currentIndexChanged(), DEFAULT_INDEX_LEVEL1, m_currentIndex, m_laterMediaList, m_mediaList, m_playbackMode, MusicPlayedItem::m_toolIndex, MusicObject::PM_PlayListLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, and MusicObject::PM_PlayRandom.
Referenced by MusicApplication::musicPlayedIndex(), MusicApplication::musicPlayIndex(), MusicApplication::musicPlayNext(), MusicApplication::musicPlayPrevious(), MusicApplication::musicPlaySort(), MusicPlayer::playNext(), MusicPlayer::playPrevious(), MusicApplication::readXMLConfigFromText(), MusicPlayedListPopWidget::setCurrentIndex(), setCurrentIndex(), MusicPlayedListPopWidget::setDeleteItemAt(), MusicApplication::setDeleteItemAt(), and MusicPlayer::update().
void MusicPlayedlist::setCurrentIndex (int toolIndex, const QString & path) slot
Set current play index.
Definition at line 234 of file musicplayedlist.cpp.
References mapItemIndex(), and setCurrentIndex().
void MusicPlayedlist::setPlaybackMode (MusicObject::PlayMode mode)
Set current play mode.
Definition at line 22 of file musicplayedlist.cpp.
References m_playbackMode.
Referenced by MusicApplication::MusicApplication(), MusicApplication::musicPlayItemOnce(), MusicApplication::musicPlayListLoop(), MusicApplication::musicPlayOneLoop(), MusicApplication::musicPlayOrder(), and MusicApplication::musicPlayRandom().
Member Data Documentation
int MusicPlayedlist::m_currentIndex protected
Definition at line 199 of file musicplayedlist.h.
Referenced by currentIndex(), currentItem(), insertLaterMedia(), MusicPlayedlist(), and setCurrentIndex().
MusicPlayedItems MusicPlayedlist::m_laterMediaList protected
Definition at line 201 of file musicplayedlist.h.
Referenced by addMedia(), insertLaterMedia(), laterListClear(), laterListConst(), and setCurrentIndex().
MusicPlayedItems MusicPlayedlist::m_mediaList protected
Definition at line 200 of file musicplayedlist.h.
Referenced by addMedia(), appendMedia(), clear(), currentItem(), find(), insertLaterMedia(), isEmpty(), mapItemIndex(), mediaCount(), mediaList(), mediaListConst(), removeMedia(), and setCurrentIndex().
MusicObject::PlayMode MusicPlayedlist::m_playbackMode protected
Definition at line 202 of file musicplayedlist.h.
Referenced by MusicPlayedlist(), playbackMode(), setCurrentIndex(), and setPlaybackMode().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicplayedlist.h
TTKModule/TTKCore/musicCoreKits/musicplayedlist.cpp