TTKMusicplayer: MusicUtils::Url Namespace Reference
MusicUtils::Url Namespace Reference
Functions
TTK_MODULE_EXPORT bool execute (const QString &path)
TTK_MODULE_EXPORT bool openUrl (const QString &path, bool local=true)
TTK_MODULE_EXPORT void urlEncode (QString &data)
TTK_MODULE_EXPORT void urlDecode (QString &data)
TTK_MODULE_EXPORT void urlEncode (QByteArray &data)
TTK_MODULE_EXPORT void urlDecode (QByteArray &data)
TTK_MODULE_EXPORT void urlPrettyEncode (QString &data)
TTK_MODULE_EXPORT void urlPrettyDecode (QString &data)
TTK_MODULE_EXPORT void urlPrettyEncode (QByteArray &data)
TTK_MODULE_EXPORT void urlPrettyDecode (QByteArray &data)
Function Documentation
bool MusicUtils::Url::execute (const QString & path)
Execute file from local by path or other url.
Definition at line 12 of file musicurlutils.cpp.
Referenced by MusicConfigObject::copyLinuxShellFile(), and MusicSongRingtoneMaker::initOutputPath().
bool MusicUtils::Url::openUrl (const QString & path, bool local = true)
Open file from local by path or other url.
Definition at line 22 of file musicurlutils.cpp.
References MusicPlatformManager::System_Linux_Ubuntu, MusicPlatformManager::systemName(), and TTK_SEPARATOR.
Referenced by MusicSongSharingWidget::downLoadFinished(), MusicLrcContainerForInterior::lrcOpenFileDir(), MusicApplicationModule::musicBugReportView(), MusicAbstractSongsListTableWidget::musicOpenFileDir(), MusicFileInformationWidget::openFileDir(), MusicDownloadResetWidget::openFileLocation(), and MusicSourceUpdateWidget::upgradeButtonClicked().
void MusicUtils::Url::urlDecode (QString & data)
Decode the data into url.
Definition at line 55 of file musicurlutils.cpp.
void MusicUtils::Url::urlDecode (QByteArray & data)
Decode the data into url.
Definition at line 69 of file musicurlutils.cpp.
void MusicUtils::Url::urlEncode (QString & data)
Encode the data into url.
Definition at line 48 of file musicurlutils.cpp.
Referenced by MusicWYQueryInterface::makeTokenQueryUrl(), and MusicBDQueryLearnRequest::readFromMusicSongAttribute().
void MusicUtils::Url::urlEncode (QByteArray & data)
Encode the data into url.
Definition at line 62 of file musicurlutils.cpp.
void MusicUtils::Url::urlPrettyDecode (QString & data)
Pretty decode the data into url.
Definition at line 85 of file musicurlutils.cpp.
void MusicUtils::Url::urlPrettyDecode (QByteArray & data)
Pretty decode the data into url.
Definition at line 103 of file musicurlutils.cpp.
void MusicUtils::Url::urlPrettyEncode (QString & data)
Pretty encode the data into url.
Definition at line 76 of file musicurlutils.cpp.
void MusicUtils::Url::urlPrettyEncode (QByteArray & data)
Pretty encode the data into url.
Definition at line 94 of file musicurlutils.cpp.