TTKMusicplayer: MusicArtistSimilarFoundWidget Class Reference
MusicArtistSimilarFoundWidget Class Reference
The class of the artist similar found widget.
#include <musicartistfoundwidget.h>
Public Slots
void createArtistSimilarItem (const MusicResultsItem &item)
void currentItemClicked (const QString &id)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistSimilarFoundWidget (QWidget *parent=0)
virtual ~MusicArtistSimilarFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
void initWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Attributes
QGridLayout * m_gridLayout
MusicDownLoadSimilarThread * m_similarThread
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the artist similar found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 131 of file musicartistfoundwidget.h.
Constructor & Destructor Documentation
MusicArtistSimilarFoundWidget::MusicArtistSimilarFoundWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 199 of file musicartistfoundwidget.cpp.
References MusicSongSharingWidget::Artist, createArtistSimilarItem(), MusicFoundAbstractWidget::m_container, M_DOWNLOAD_QUERY_PTR, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, MusicFoundAbstractWidget::m_shareType, m_similarThread, and MusicFoundAbstractWidget::m_statusLabel.
MusicArtistSimilarFoundWidget::~MusicArtistSimilarFoundWidget () virtual
Definition at line 215 of file musicartistfoundwidget.cpp.
References m_gridLayout.
Member Function Documentation
void MusicArtistSimilarFoundWidget::createArtistSimilarItem (const MusicResultsItem & item) slot
Create the current similar item.
Definition at line 254 of file musicartistfoundwidget.cpp.
References currentItemClicked(), LINE_SPACING_SIZE, m_gridLayout, MusicFoundAbstractWidget::m_resizeWidgets, and MusicArtistAlbumsItemWidget::setMusicResultsItem().
Referenced by MusicArtistSimilarFoundWidget().
void MusicArtistSimilarFoundWidget::currentItemClicked (const QString & id) slot
Current item clicked.
Definition at line 266 of file musicartistfoundwidget.cpp.
References MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicArtistSearch().
Referenced by createArtistSimilarItem().
QString MusicArtistSimilarFoundWidget::getClassName () static
Get class object name.
Definition at line 220 of file musicartistfoundwidget.cpp.
void MusicArtistSimilarFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 237 of file musicartistfoundwidget.cpp.
References HEIGHT_LABEL_SIZE, m_gridLayout, and MusicFoundAbstractWidget::m_resizeWidgets.
Referenced by MusicArtistFoundWidget::resizeWindow().
void MusicArtistSimilarFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 225 of file musicartistfoundwidget.cpp.
References m_similarThread, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadSimilarThread::startToSearch().
Referenced by MusicArtistFoundWidget::initFivethWidget().
void MusicArtistSimilarFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 231 of file musicartistfoundwidget.cpp.
References m_similarThread, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadSimilarThread::startToSearch().
Member Data Documentation
QGridLayout* MusicArtistSimilarFoundWidget::m_gridLayout protected
Definition at line 171 of file musicartistfoundwidget.h.
Referenced by createArtistSimilarItem(), MusicArtistSimilarFoundWidget(), resizeWindow(), and ~MusicArtistSimilarFoundWidget().
MusicDownLoadSimilarThread* MusicArtistSimilarFoundWidget::m_similarThread protected
Definition at line 172 of file musicartistfoundwidget.h.
Referenced by MusicArtistSimilarFoundWidget(), setSongName(), and setSongNameById().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.cpp