TTKMusicPlayer: MusicLrcFloatPlayWidget Class Reference
MusicLrcFloatPlayWidget Class Reference
The class of the lrc play float widget.
#include <musiclrcfloatplaywidget.h>
Public Slots
void switchToPlayState ()
Public Member Functions
MusicLrcFloatPlayWidget (QWidget *parent=nullptr)
~MusicLrcFloatPlayWidget ()
void resizeGeometry (int width, int height)
Public Member Functions inherited from MusicAbstractFloatWidget
MusicAbstractFloatWidget (QWidget *parent=nullptr)
~MusicAbstractFloatWidget ()
void setBlockAnimation (bool b) noexcept
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
void setCurrentPlayState () const
Private Attributes
QToolButton * m_buttonPrevious
QToolButton * m_buttonNext
QToolButton * m_buttonKey
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractFloatWidget
virtual void leaveEvent (QEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *) overridefinal
virtual void mousePressEvent (QMouseEvent *) overridefinal
virtual void mouseMoveEvent (QMouseEvent *) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *) overridefinal
void animationEnter ()
void animationLeave ()
Protected Attributes inherited from MusicAbstractFloatWidget
QPropertyAnimation * m_animation
QRect m_rectEnter
QRect m_rectLeave
bool m_blockAnimation
Detailed Description
The class of the lrc play float widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musiclrcfloatplaywidget.h.
Constructor & Destructor Documentation
MusicLrcFloatPlayWidget::MusicLrcFloatPlayWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musiclrcfloatplaywidget.cpp.
References TTK::UI::BtnNext, TTK::UI::BtnPrevious, MusicApplication::instance(), m_buttonKey, m_buttonNext, m_buttonPrevious, resizeGeometry(), setCurrentPlayState(), and switchToPlayState().
MusicLrcFloatPlayWidget::~MusicLrcFloatPlayWidget ()
Object destructor.
Definition at line 47 of file musiclrcfloatplaywidget.cpp.
References m_buttonKey, m_buttonNext, and m_buttonPrevious.
Member Function Documentation
void MusicLrcFloatPlayWidget::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Reimplemented from MusicAbstractFloatWidget.
Definition at line 73 of file musiclrcfloatplaywidget.cpp.
References MusicAbstractFloatWidget::enterEvent(), and setCurrentPlayState().
void MusicLrcFloatPlayWidget::resizeGeometry (int width, int height)
Resize geometry bound by given width and height.
Definition at line 54 of file musiclrcfloatplaywidget.cpp.
References MusicAbstractFloatWidget::animationEnter(), MusicAbstractFloatWidget::m_blockAnimation, MusicAbstractFloatWidget::m_rectEnter, and MusicAbstractFloatWidget::m_rectLeave.
Referenced by MusicLrcContainerForInterior::createFloatPlayWidget(), MusicLrcFloatPlayWidget(), and MusicLrcContainerForInterior::resizeWidth().
void MusicLrcFloatPlayWidget::setCurrentPlayState () const private
Set current play state icon.
Definition at line 79 of file musiclrcfloatplaywidget.cpp.
References TTK::UI::BtnPause, TTK::UI::BtnPlay, MusicApplication::instance(), and m_buttonKey.
Referenced by enterEvent(), MusicLrcFloatPlayWidget(), and switchToPlayState().
void MusicLrcFloatPlayWidget::switchToPlayState () slot
Set current player to play or not.
Definition at line 67 of file musiclrcfloatplaywidget.cpp.
References MusicApplication::instance(), setCurrentPlayState(), and MusicApplication::switchToPlayState().
Referenced by MusicLrcFloatPlayWidget().
Member Data Documentation
QToolButton * MusicLrcFloatPlayWidget::m_buttonKey private
Definition at line 64 of file musiclrcfloatplaywidget.h.
Referenced by MusicLrcFloatPlayWidget(), setCurrentPlayState(), and ~MusicLrcFloatPlayWidget().
QToolButton * MusicLrcFloatPlayWidget::m_buttonNext private
Definition at line 64 of file musiclrcfloatplaywidget.h.
Referenced by MusicLrcFloatPlayWidget(), and ~MusicLrcFloatPlayWidget().
QToolButton* MusicLrcFloatPlayWidget::m_buttonPrevious private
Definition at line 64 of file musiclrcfloatplaywidget.h.
Referenced by MusicLrcFloatPlayWidget(), and ~MusicLrcFloatPlayWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatplaywidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatplaywidget.cpp