TTKMusicPlayer: QDeviceWatcherPrivate Class Reference
QDeviceWatcherPrivate Class Reference
The class of the device watcher private.
#include <qdevicewatcher_p.h>
Public Member Functions
QDeviceWatcherPrivate (QObject *parent=nullptr)
~QDeviceWatcherPrivate ()
void setWatcher (QDeviceWatcher *w)
bool start ()
bool stop ()
void emitDeviceAdded (const QString &dev)
void emitDeviceChanged (const QString &dev)
void emitDeviceRemoved (const QString &dev)
void emitDeviceAction (const QString &dev, const QString &action)
Public Attributes
QObjectList event_receivers
Private Slots
void parseDeviceInfo ()
Private Member Functions
bool initialize ()
Private Attributes
QDeviceWatcher * watcher
Detailed Description
The class of the device watcher private.
Author
WangBin wbsec.nosp@m.g1@g.nosp@m.mail..nosp@m.com
Definition at line 52 of file qdevicewatcher_p.h.
Constructor & Destructor Documentation
QDeviceWatcherPrivate::QDeviceWatcherPrivate (QObject * parent = nullptr) inline
Definition at line 61 of file qdevicewatcher_p.h.
QDeviceWatcherPrivate::~QDeviceWatcherPrivate ()
Definition at line 28 of file qdevicewatcher_mac.cpp.
References stop().
Member Function Documentation
void QDeviceWatcherPrivate::emitDeviceAction (const QString & dev, const QString & action)
Definition at line 72 of file qdevicewatcher.cpp.
References emitDeviceAdded(), emitDeviceChanged(), and emitDeviceRemoved().
void QDeviceWatcherPrivate::emitDeviceAdded (const QString & dev)
Definition at line 50 of file qdevicewatcher.cpp.
References watcher.
Referenced by emitDeviceAction(), and onDiskAppear().
void QDeviceWatcherPrivate::emitDeviceChanged (const QString & dev)
Definition at line 58 of file qdevicewatcher.cpp.
References watcher.
Referenced by emitDeviceAction().
void QDeviceWatcherPrivate::emitDeviceRemoved (const QString & dev)
Definition at line 64 of file qdevicewatcher.cpp.
References watcher.
Referenced by emitDeviceAction(), and onDiskDisappear().
bool QDeviceWatcherPrivate::initialize () private
Definition at line 52 of file qdevicewatcher_mac.cpp.
References onDiskAppear(), and onDiskDisappear().
Referenced by start().
void QDeviceWatcherPrivate::parseDeviceInfo () private slot
Definition at line 48 of file qdevicewatcher_mac.cpp.
void QDeviceWatcherPrivate::setWatcher (QDeviceWatcher * w) inline
Definition at line 72 of file qdevicewatcher_p.h.
bool QDeviceWatcherPrivate::start ()
Definition at line 33 of file qdevicewatcher_mac.cpp.
References initialize().
bool QDeviceWatcherPrivate::stop ()
Definition at line 39 of file qdevicewatcher_mac.cpp.
References onDiskAppear(), and onDiskDisappear().
Referenced by ~QDeviceWatcherPrivate().
Member Data Documentation
QObjectList QDeviceWatcherPrivate::event_receivers
Definition at line 82 of file qdevicewatcher_p.h.
QDeviceWatcher* QDeviceWatcherPrivate::watcher private
Definition at line 88 of file qdevicewatcher_p.h.
Referenced by emitDeviceAdded(), emitDeviceChanged(), and emitDeviceRemoved().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKWatcher/qdevicewatcher_p.h
TTKThirdParty/TTKWatcher/qdevicewatcher.cpp
TTKThirdParty/TTKWatcher/qdevicewatcher_mac.cpp