TTKMusicPlayer: MusicSongSearchPopTableWidget Class Reference
MusicSongSearchPopTableWidget Class Reference
The class of the search popup table widget.
#include <musicsongsearchpopwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
virtual void removeItems () overridefinal
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void setText (const QString &text, bool update)
Public Member Functions
MusicSongSearchPopTableWidget (QWidget *parent=nullptr)
~MusicSongSearchPopTableWidget ()
void selectRow (bool up)
void addCellItem (int index, const QString &name, const QString &time)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the search popup table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicsongsearchpopwidget.h.
Constructor & Destructor Documentation
MusicSongSearchPopTableWidget::MusicSongSearchPopTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicsongsearchpopwidget.cpp.
References TTK::Widget::setTransparent().
MusicSongSearchPopTableWidget::~MusicSongSearchPopTableWidget ()
Object destructor.
Definition at line 19 of file musicsongsearchpopwidget.cpp.
References removeItems().
Member Function Documentation
void MusicSongSearchPopTableWidget::addCellItem (int index, const QString & name, const QString & time)
Create cell item by input data.
Definition at line 54 of file musicsongsearchpopwidget.cpp.
References TTK::UI::Color02, TTK::Widget::elidedText(), QtItemSetTextAlignment, and TTK_ITEM_SIZE_M.
Referenced by MusicSongSearchPopWidget::addCellItems(), and MusicSongSearchPopWidget::initialize().
void MusicSongSearchPopTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 71 of file musicsongsearchpopwidget.cpp.
References TTKAbstractTableWidget::itemCellClicked(), and setText().
void MusicSongSearchPopTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 77 of file musicsongsearchpopwidget.cpp.
References TTKAbstractTableWidget::removeItems().
Referenced by MusicSongSearchPopWidget::addCellItems(), MusicSongSearchPopWidget::initialize(), and ~MusicSongSearchPopTableWidget().
void MusicSongSearchPopTableWidget::selectRow (bool up)
Select search history table items.
Definition at line 24 of file musicsongsearchpopwidget.cpp.
References setText().
Referenced by MusicSongSearchPopWidget::selectRow().
void MusicSongSearchPopTableWidget::setText (const QString & text, bool update) signal
User click the current item.
Referenced by itemCellClicked(), and selectRow().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicsongsearchpopwidget.h
TTKModule/TTKWidget/musicSearchKits/musicsongsearchpopwidget.cpp