TTKMusicplayer: MusicVideoFloatWidget Class Reference
MusicVideoFloatWidget Class Reference
The class of the video float widget.
#include <musicvideofloatwidget.h>
Public Types
enum Type {
SearchType, FreshType, FullscreenType, DownloadType,
ShareType
}
Signals
void searchButtonClicked ()
void freshButtonClicked ()
void fullscreenButtonClicked ()
void downloadButtonClicked ()
void shareButtonClicked ()
Public Member Functions
MusicVideoFloatWidget (QWidget *parent=nullptr)
virtual ~MusicVideoFloatWidget ()
virtual void resizeWindow (int width, int height) override
void setText (Type type, const QString &text)
QString getText (Type type) const
Public Member Functions inherited from MusicFloatAbstractWidget
MusicFloatAbstractWidget (QWidget *parent=nullptr)
virtual ~MusicFloatAbstractWidget ()
void setBlockAnimation (bool b)
Protected Attributes
QPushButton * m_search
QPushButton * m_fresh
QPushButton * m_fullscreen
QPushButton * m_download
QPushButton * m_share
Protected Attributes inherited from MusicFloatAbstractWidget
QPropertyAnimation * m_animation
QRect m_rectIn
QRect m_rectOut
bool m_blockAnimation
Additional Inherited Members
Protected Member Functions inherited from MusicFloatAbstractWidget
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *) override
virtual void mouseMoveEvent (QMouseEvent *) override
virtual void mousePressEvent (QMouseEvent *) override
virtual void mouseReleaseEvent (QMouseEvent *) override
void animationIn ()
void animationOut ()
Detailed Description
The class of the video float widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicvideofloatwidget.h.
Member Enumeration Documentation
enum MusicVideoFloatWidget::Type
Enumerator
SearchType
search text type
FreshType
fresh text type
FullscreenType
fullscreen text type
DownloadType
download text type
ShareType
share text type
Definition at line 34 of file musicvideofloatwidget.h.
Constructor & Destructor Documentation
MusicVideoFloatWidget::MusicVideoFloatWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicvideofloatwidget.cpp.
References downloadButtonClicked(), freshButtonClicked(), fullscreenButtonClicked(), m_download, m_fresh, m_fullscreen, m_search, m_share, MusicUIObject::MBackgroundStyle06, MusicUIObject::MKGVideoFloatDownload, MusicUIObject::MKGVideoFloatFresh, MusicUIObject::MKGVideoFloatFullscreen, MusicUIObject::MKGVideoFloatSearch, MusicUIObject::MKGVideoFloatShare, MusicUIObject::MPushButtonStyle09, resizeWindow(), searchButtonClicked(), and shareButtonClicked().
MusicVideoFloatWidget::~MusicVideoFloatWidget () virtual
Definition at line 51 of file musicvideofloatwidget.cpp.
References m_download, m_fresh, m_fullscreen, m_search, and m_share.
Member Function Documentation
void MusicVideoFloatWidget::downloadButtonClicked () signal
Download button clicked.
Referenced by MusicVideoFloatWidget().
void MusicVideoFloatWidget::freshButtonClicked () signal
Fresh button clicked.
Referenced by MusicVideoFloatWidget().
void MusicVideoFloatWidget::fullscreenButtonClicked () signal
Fullscreen button clicked.
Referenced by MusicVideoFloatWidget().
QString MusicVideoFloatWidget::getText (Type type) const
Get tool button text by type.
Definition at line 80 of file musicvideofloatwidget.cpp.
References DownloadType, FreshType, FullscreenType, m_download, m_fresh, m_fullscreen, m_search, m_share, SearchType, and ShareType.
Referenced by MusicVideoPlayWidget::freshButtonClicked(), and MusicVideoPlayWidget::fullscreenButtonClicked().
void MusicVideoFloatWidget::resizeWindow (int width, int height) override virtual
Resize window bound by given width and height.
Implements MusicFloatAbstractWidget.
Definition at line 60 of file musicvideofloatwidget.cpp.
References MusicFloatAbstractWidget::m_rectIn, and MusicFloatAbstractWidget::m_rectOut.
Referenced by MusicVideoFloatWidget(), and MusicVideoPlayWidget::resizeWindow().
void MusicVideoFloatWidget::searchButtonClicked () signal
Search button clicked.
Referenced by MusicVideoFloatWidget().
void MusicVideoFloatWidget::setText (Type type, const QString & text)
Set tool button text by type.
Definition at line 67 of file musicvideofloatwidget.cpp.
References DownloadType, FreshType, FullscreenType, m_download, m_fresh, m_fullscreen, m_search, m_share, SearchType, and ShareType.
Referenced by MusicVideoPlayWidget::fullscreenButtonClicked(), MusicVideoPlayWidget::MusicVideoPlayWidget(), and MusicVideoPlayWidget::popup().
void MusicVideoFloatWidget::shareButtonClicked () signal
Share button clicked.
Referenced by MusicVideoFloatWidget().
Member Data Documentation
QPushButton* MusicVideoFloatWidget::m_download protected
Definition at line 88 of file musicvideofloatwidget.h.
Referenced by getText(), MusicVideoFloatWidget(), setText(), and ~MusicVideoFloatWidget().
QPushButton * MusicVideoFloatWidget::m_fresh protected
Definition at line 87 of file musicvideofloatwidget.h.
Referenced by getText(), MusicVideoFloatWidget(), setText(), and ~MusicVideoFloatWidget().
QPushButton * MusicVideoFloatWidget::m_fullscreen protected
Definition at line 87 of file musicvideofloatwidget.h.
Referenced by getText(), MusicVideoFloatWidget(), setText(), and ~MusicVideoFloatWidget().
QPushButton* MusicVideoFloatWidget::m_search protected
Definition at line 87 of file musicvideofloatwidget.h.
Referenced by getText(), MusicVideoFloatWidget(), setText(), and ~MusicVideoFloatWidget().
QPushButton * MusicVideoFloatWidget::m_share protected
Definition at line 88 of file musicvideofloatwidget.h.
Referenced by getText(), MusicVideoFloatWidget(), setText(), and ~MusicVideoFloatWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideofloatwidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideofloatwidget.cpp