TTKMusicplayer: MusicBackgroundManager Class Reference
MusicBackgroundManager Class Reference
The class of the manager of dealing with artist pictures.
#include <musicbackgroundmanager.h>
Signals
void backgroundChanged ()
void artHasChanged ()
void userSelectIndexChanged ()
Public Member Functions
void setArtName (const QString &name)
void clearArtName ()
int getCurrentIndex () const
void setCurrentIndex (int index)
int count () const
bool isEmpty () const
void indexIncrease ()
void indexDecrease ()
QString getArtPhotoPath ()
QString getArtPhotoPathNoIndex ()
QString getArtPhotoPathByIndex (int index=-1) const
QStringList getArtPhotoPathList () const
void setArtPhotoPathList (const QStringList &list)
void setUserSelectArtIndex (int index)
void addObserver (QObject *object)
void removeObserver (QObject *object)
void setMBackground (const QString &path)
QString getMBackground () const
void backgroundHasChanged ()
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
MusicBackgroundManager ()
Protected Attributes
int m_currentIndex
QStringList m_photos
QList< QObject * > m_observer
QString m_currentArtName
QString m_background
Detailed Description
The class of the manager of dealing with artist pictures.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicbackgroundmanager.h.
Constructor & Destructor Documentation
MusicBackgroundManager::MusicBackgroundManager () protected
Object contsructor.
Definition at line 4 of file musicbackgroundmanager.cpp.
References m_currentIndex.
Member Function Documentation
void MusicBackgroundManager::addObserver (QObject * object)
Add observer.
Definition at line 104 of file musicbackgroundmanager.cpp.
References backgroundChanged(), and m_observer.
void MusicBackgroundManager::artHasChanged () signal
New art has been set emit.
Referenced by setArtName().
void MusicBackgroundManager::backgroundChanged () signal
Background image changed.
Referenced by addObserver(), backgroundHasChanged(), and removeObserver().
void MusicBackgroundManager::backgroundHasChanged ()
Get artist background picture path.
Definition at line 126 of file musicbackgroundmanager.cpp.
References backgroundChanged().
void MusicBackgroundManager::clearArtName ()
Remove current artist name.
Definition at line 34 of file musicbackgroundmanager.cpp.
References m_currentArtName.
int MusicBackgroundManager::count () const inline
Get artist photo count.
Definition at line 60 of file musicbackgroundmanager.h.
QString MusicBackgroundManager::getArtPhotoPath ()
Get artist photo path.
Definition at line 49 of file musicbackgroundmanager.cpp.
References m_currentIndex, and m_photos.
QString MusicBackgroundManager::getArtPhotoPathByIndex (int index = -1) const
Get artist photo path by given index.
Definition at line 77 of file musicbackgroundmanager.cpp.
References m_currentIndex, M_LOGGER_ERROR, and m_photos.
QStringList MusicBackgroundManager::getArtPhotoPathList () const
Get artist photo path list.
Definition at line 88 of file musicbackgroundmanager.cpp.
References m_photos.
QString MusicBackgroundManager::getArtPhotoPathNoIndex ()
Get artist photo path no index.
Definition at line 61 of file musicbackgroundmanager.cpp.
References m_currentIndex, and m_photos.
QString MusicBackgroundManager::getClassName () static
Get class object name.
Definition at line 9 of file musicbackgroundmanager.cpp.
int MusicBackgroundManager::getCurrentIndex () const inline
Get artist photo current index.
Definition at line 52 of file musicbackgroundmanager.h.
QString MusicBackgroundManager::getMBackground () const
Get artist background picture path.
Definition at line 121 of file musicbackgroundmanager.cpp.
References m_background.
void MusicBackgroundManager::indexDecrease ()
Set artist photo current index - 1.
Definition at line 44 of file musicbackgroundmanager.cpp.
References m_currentIndex.
void MusicBackgroundManager::indexIncrease ()
Set artist photo current index + 1.
Definition at line 39 of file musicbackgroundmanager.cpp.
References m_currentIndex.
bool MusicBackgroundManager::isEmpty () const inline
Get artist photo count is 0.
Definition at line 64 of file musicbackgroundmanager.h.
void MusicBackgroundManager::removeObserver (QObject * object)
Remove observer.
Definition at line 110 of file musicbackgroundmanager.cpp.
References backgroundChanged(), and m_observer.
void MusicBackgroundManager::setArtName (const QString & name)
Set current artist name.
Definition at line 14 of file musicbackgroundmanager.cpp.
References artHasChanged(), MusicUtils::String::artistName(), BACKGROUND_DIR_FULL, m_currentArtName, m_photos, MAX_INDEX, and SKN_FILE.
void MusicBackgroundManager::setArtPhotoPathList (const QStringList & list)
Set artist photo path by given path list.
Definition at line 93 of file musicbackgroundmanager.cpp.
References m_photos.
void MusicBackgroundManager::setCurrentIndex (int index) inline
Set artist photo current index.
Definition at line 56 of file musicbackgroundmanager.h.
void MusicBackgroundManager::setMBackground (const QString & path)
Set artist background picture by path.
Definition at line 116 of file musicbackgroundmanager.cpp.
References m_background.
void MusicBackgroundManager::setUserSelectArtIndex (int index)
Set user select current index.
Definition at line 98 of file musicbackgroundmanager.cpp.
References m_currentIndex, and userSelectIndexChanged().
void MusicBackgroundManager::userSelectIndexChanged () signal
User selected index changed emit.
Referenced by setUserSelectArtIndex().
Member Data Documentation
QString MusicBackgroundManager::m_background protected
Definition at line 146 of file musicbackgroundmanager.h.
Referenced by getMBackground(), and setMBackground().
QString MusicBackgroundManager::m_currentArtName protected
Definition at line 146 of file musicbackgroundmanager.h.
Referenced by clearArtName(), and setArtName().
int MusicBackgroundManager::m_currentIndex protected
Definition at line 143 of file musicbackgroundmanager.h.
Referenced by getArtPhotoPath(), getArtPhotoPathByIndex(), getArtPhotoPathNoIndex(), indexDecrease(), indexIncrease(), MusicBackgroundManager(), and setUserSelectArtIndex().
QList<QObject*> MusicBackgroundManager::m_observer protected
Definition at line 145 of file musicbackgroundmanager.h.
Referenced by addObserver(), and removeObserver().
QStringList MusicBackgroundManager::m_photos protected
Definition at line 144 of file musicbackgroundmanager.h.
Referenced by getArtPhotoPath(), getArtPhotoPathByIndex(), getArtPhotoPathList(), getArtPhotoPathNoIndex(), setArtName(), and setArtPhotoPathList().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicbackgroundmanager.h
TTKModule/TTKCore/musicCoreKits/musicbackgroundmanager.cpp