TTKMusicplayer: QImageWrap::QWaterWave Class Reference
QImageWrap::QWaterWave Class Reference
The class of the water wave wrapper.
#include <qimagewrap.h>
Public Member Functions
QWaterWave (const QImage &image, int radius)
int * data ()
void render ()
void input (int x, int y)
Detailed Description
The class of the water wave wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 47 of file qimagewrap.h.
Constructor & Destructor Documentation
QImageWrap::QWaterWave::QWaterWave (const QImage & image, int radius)
Definition at line 306 of file qimagewrap.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
int * QImageWrap::QWaterWave::data ()
Definition at line 313 of file qimagewrap.cpp.
References TTK_D.
Referenced by MusicTransitionAnimationLabel::paintEvent().
void QImageWrap::QWaterWave::input (int x, int y)
Definition at line 325 of file qimagewrap.cpp.
References TTK_D.
Referenced by MusicTransitionAnimationLabel::setPixmap().
void QImageWrap::QWaterWave::render ()
Definition at line 319 of file qimagewrap.cpp.
References TTK_D.
Referenced by MusicTransitionAnimationLabel::paintEvent().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalg/qimagewrap.h
TTKThirdParty/TTKExtras/qalg/qimagewrap.cpp