TTKMusicPlayer: MusicRectQueryItemWidget Class Reference
MusicRectQueryItemWidget Class Reference
The class of the rect query item widget.
#include <musicqueryitemwidget.h>
Public Slots
void downloadFinished (const QByteArray &bytes)
void renderFinished (const QPixmap &data)
void itemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicRectQueryItemWidget (QWidget *parent=nullptr)
~MusicRectQueryItemWidget ()
void setResultDataItem (const MusicResultDataItem &item)
Static Public Attributes
static constexpr int WIDTH_LABEL_SIZE = 150
static constexpr int HEIGHT_LABEL_SIZE = 100
static constexpr int LINE_SPACING_SIZE = 150
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
Private Attributes
TTKClickedLabel * m_iconLabel
QLabel * m_nameLabel
QPushButton * m_playButton
MusicResultDataItem m_itemData
Detailed Description
The class of the rect query item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 100 of file musicqueryitemwidget.h.
Constructor & Destructor Documentation
MusicRectQueryItemWidget::MusicRectQueryItemWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 129 of file musicqueryitemwidget.cpp.
References TTK::UI::ColorStyle06, TTK::UI::FontStyle01, TTK::UI::FontStyle05, HEIGHT_LABEL_SIZE, itemClicked(), m_iconLabel, m_nameLabel, m_playButton, TTK::UI::TinyBtnPlaylist, TTK_DEFAULT_STR, and WIDTH_LABEL_SIZE.
MusicRectQueryItemWidget::~MusicRectQueryItemWidget ()
Object destructor.
Definition at line 155 of file musicqueryitemwidget.cpp.
References m_iconLabel, m_nameLabel, and m_playButton.
Member Function Documentation
void MusicRectQueryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
Referenced by itemClicked().
void MusicRectQueryItemWidget::downloadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 178 of file musicqueryitemwidget.cpp.
References m_iconLabel, renderFinished(), MusicImageRenderer::setInputData(), TTKAbstractThread::start(), and TTK_ERROR_STREAM.
Referenced by setResultDataItem().
void MusicRectQueryItemWidget::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Definition at line 203 of file musicqueryitemwidget.cpp.
References m_nameLabel, and m_playButton.
void MusicRectQueryItemWidget::itemClicked () slot
Current item clicked.
Definition at line 198 of file musicqueryitemwidget.cpp.
References currentItemClicked(), and m_itemData.
Referenced by MusicRectQueryItemWidget().
void MusicRectQueryItemWidget::leaveEvent (QEvent * event) final override private virtual
Definition at line 211 of file musicqueryitemwidget.cpp.
References m_nameLabel, and m_playButton.
void MusicRectQueryItemWidget::renderFinished (const QPixmap & data) slot
Image render finished.
Definition at line 192 of file musicqueryitemwidget.cpp.
References m_iconLabel, and m_playButton.
Referenced by downloadFinished().
void MusicRectQueryItemWidget::setResultDataItem (const MusicResultDataItem & item)
Set media results item.
Definition at line 162 of file musicqueryitemwidget.cpp.
References downloadFinished(), TTK::Widget::elidedText(), TTK::isCoverValid(), MusicResultDataItem::m_coverUrl, m_itemData, MusicResultDataItem::m_name, m_nameLabel, m_playButton, MusicCoverRequest::startToRequest(), and WIDTH_LABEL_SIZE.
Referenced by MusicWebMVRadioQueryWidget::createMVRadioCategoryItem().
Member Data Documentation
constexpr int MusicRectQueryItemWidget::HEIGHT_LABEL_SIZE = 100 static
Definition at line 105 of file musicqueryitemwidget.h.
Referenced by MusicRectQueryItemWidget().
constexpr int MusicRectQueryItemWidget::LINE_SPACING_SIZE = 150 static
Definition at line 106 of file musicqueryitemwidget.h.
Referenced by MusicWebMVRadioQueryWidget::createMVRadioCategoryItem(), and MusicWebMVRadioQueryWidget::resizeGeometry().
TTKClickedLabel* MusicRectQueryItemWidget::m_iconLabel private
Definition at line 150 of file musicqueryitemwidget.h.
Referenced by downloadFinished(), MusicRectQueryItemWidget(), renderFinished(), and ~MusicRectQueryItemWidget().
MusicResultDataItem MusicRectQueryItemWidget::m_itemData private
Definition at line 153 of file musicqueryitemwidget.h.
Referenced by itemClicked(), and setResultDataItem().
QLabel* MusicRectQueryItemWidget::m_nameLabel private
Definition at line 151 of file musicqueryitemwidget.h.
Referenced by enterEvent(), leaveEvent(), MusicRectQueryItemWidget(), setResultDataItem(), and ~MusicRectQueryItemWidget().
QPushButton* MusicRectQueryItemWidget::m_playButton private
Definition at line 152 of file musicqueryitemwidget.h.
Referenced by enterEvent(), leaveEvent(), MusicRectQueryItemWidget(), renderFinished(), setResultDataItem(), and ~MusicRectQueryItemWidget().
constexpr int MusicRectQueryItemWidget::WIDTH_LABEL_SIZE = 150 static
Definition at line 104 of file musicqueryitemwidget.h.
Referenced by MusicRectQueryItemWidget(), and setResultDataItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicqueryitemwidget.h
TTKModule/TTKWidget/musicCoreKits/musicqueryitemwidget.cpp