TTKMusicplayer: MusicDownloadTableItem Class Reference
MusicDownloadTableItem Class Reference
The class of the download table item.
#include <musicdownloadwidget.h>
Public Member Functions
MusicDownloadTableItem (QWidget *parent=nullptr)
~MusicDownloadTableItem ()
void setIcon (const QString &name)
void setInformation (const QString &info)
void setText (const QString &text)
Protected Attributes
QLabel * m_text
QLabel * m_information
QLabel * m_icon
Detailed Description
The class of the download table item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 69 of file musicdownloadwidget.h.
Constructor & Destructor Documentation
MusicDownloadTableItem::MusicDownloadTableItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 14 of file musicdownloadwidget.cpp.
References ITEM_ROW_HEIGHT_S.
MusicDownloadTableItem::~MusicDownloadTableItem ()
Definition at line 26 of file musicdownloadwidget.cpp.
References m_icon, m_information, and m_text.
Member Function Documentation
void MusicDownloadTableItem::setIcon (const QString & name)
Set current item icon.
Definition at line 33 of file musicdownloadwidget.cpp.
References m_icon.
Referenced by MusicDownloadTableWidget::createItem().
void MusicDownloadTableItem::setInformation (const QString & info)
Set current item other infomation(size).
Definition at line 38 of file musicdownloadwidget.cpp.
References m_information.
Referenced by MusicDownloadTableWidget::createItem().
void MusicDownloadTableItem::setText (const QString & text)
Set current item text name.
Definition at line 43 of file musicdownloadwidget.cpp.
References m_text.
Referenced by MusicDownloadTableWidget::createItem().
Member Data Documentation
QLabel * MusicDownloadTableItem::m_icon protected
Definition at line 94 of file musicdownloadwidget.h.
Referenced by setIcon(), and ~MusicDownloadTableItem().
QLabel * MusicDownloadTableItem::m_information protected
Definition at line 94 of file musicdownloadwidget.h.
Referenced by setInformation(), and ~MusicDownloadTableItem().
QLabel* MusicDownloadTableItem::m_text protected
Definition at line 94 of file musicdownloadwidget.h.
Referenced by setText(), and ~MusicDownloadTableItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadwidget.cpp