TTKMusicplayer: MusicBackgroundListWidget Class Reference
MusicBackgroundListWidget Class Reference
The class of the background list widget.
#include <musicbackgroundlistwidget.h>
Public Types
enum Type { First, Second, Third, Four }
Signals
void itemClicked (int type, const QString &name)
Public Member Functions
MusicBackgroundListWidget (QWidget *parent=nullptr)
~MusicBackgroundListWidget ()
void setCurrentItemName (const QString &name)
void setType (Type type)
Type getType () const
void clearSelectState ()
void clearAllItems ()
void createItem (const QString &name, const QString &path, bool state)
void createItem (const QString &icon, bool state)
void updateItem (const MusicBackgroundImage &image, const QString &path)
bool contains (const QString &name) const
bool contains (const MusicBackgroundImage &image) const
int find (MusicBackgroundListItem *item) const
MusicBackgroundListItem * find (const QString &name) const
MusicBackgroundListItem * find (const MusicBackgroundImage &image) const
void updateLastedItem ()
int count () const
Protected Attributes
Type m_type
QGridLayout * m_gridLayout
MusicBackgroundListItem * m_currentItem
QList< MusicBackgroundListItem * > m_items
Private Slots
void itemCloseClicked (MusicBackgroundListItem *item)
void itemHasClicked (MusicBackgroundListItem *item)
Detailed Description
The class of the background list widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 140 of file musicbackgroundlistwidget.h.
Member Enumeration Documentation
enum MusicBackgroundListWidget::Type
Enumerator
First
Second
Third
Four
Definition at line 145 of file musicbackgroundlistwidget.h.
Constructor & Destructor Documentation
MusicBackgroundListWidget::MusicBackgroundListWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 149 of file musicbackgroundlistwidget.cpp.
References First, m_currentItem, m_gridLayout, and m_type.
MusicBackgroundListWidget::~MusicBackgroundListWidget ()
Definition at line 160 of file musicbackgroundlistwidget.cpp.
References clearAllItems().
Member Function Documentation
void MusicBackgroundListWidget::clearAllItems ()
Clear All Items.
Definition at line 186 of file musicbackgroundlistwidget.cpp.
References m_currentItem, and m_items.
Referenced by MusicBackgroundDailyWidget::initialize(), MusicBackgroundOnlineWidget::initialize(), and ~MusicBackgroundListWidget().
void MusicBackgroundListWidget::clearSelectState ()
Clear select state.
Definition at line 178 of file musicbackgroundlistwidget.cpp.
References m_items.
Referenced by MusicBackgroundSkinDialog::listWidgetItemClicked().
bool MusicBackgroundListWidget::contains (const QString & name) const
Current item contains or not.
Definition at line 234 of file musicbackgroundlistwidget.cpp.
References m_items, and name.
Referenced by MusicBackgroundSkinDialog::classicalListWidgetItemClicked(), and MusicBackgroundSkinDialog::listWidgetItemClicked().
bool MusicBackgroundListWidget::contains (const MusicBackgroundImage & image) const
Current item contains or not.
Definition at line 247 of file musicbackgroundlistwidget.cpp.
References MusicBackgroundImage::m_item, and m_items.
int MusicBackgroundListWidget::count () const inline
Item count.
Definition at line 226 of file musicbackgroundlistwidget.h.
void MusicBackgroundListWidget::createItem (const QString & name, const QString & path, bool state)
Create item by name and path.
Definition at line 193 of file musicbackgroundlistwidget.cpp.
References ITEM_COUNT, itemClicked(), itemCloseClicked(), itemHasClicked(), m_gridLayout, m_items, MusicBackgroundListItem::setCloseEnabled(), MusicBackgroundListItem::setFileName(), MusicBackgroundListItem::setFilePath(), and MusicBackgroundListItem::updatePixImage().
Referenced by MusicBackgroundSkinDialog::addThemeListWidgetItem(), MusicBackgroundSkinDialog::classicalListWidgetItemClicked(), MusicBackgroundSkinDialog::cpoyFileFromLocal(), MusicBackgroundSkinDialog::listWidgetItemClicked(), MusicBackgroundSkinDialog::showCustomSkinDialog(), MusicBackgroundRemoteWidget::startToDownload(), and MusicBackgroundSkinDialog::updateArtistFileTheme().
void MusicBackgroundListWidget::createItem (const QString & icon, bool state)
Create item by icon.
Definition at line 207 of file musicbackgroundlistwidget.cpp.
References ITEM_COUNT, itemClicked(), itemCloseClicked(), itemHasClicked(), m_gridLayout, m_items, and MusicBackgroundListItem::setCloseEnabled().
int MusicBackgroundListWidget::find (MusicBackgroundListItem * item) const
Current item index at container.
Definition at line 260 of file musicbackgroundlistwidget.cpp.
References m_items.
Referenced by itemCloseClicked(), and MusicBackgroundSkinDialog::listWidgetItemClicked().
MusicBackgroundListItem * MusicBackgroundListWidget::find (const QString & name) const
Find item by name.
Definition at line 273 of file musicbackgroundlistwidget.cpp.
References m_items, and name.
MusicBackgroundListItem * MusicBackgroundListWidget::find (const MusicBackgroundImage & image) const
Find item by image.
Definition at line 286 of file musicbackgroundlistwidget.cpp.
References MusicBackgroundImage::m_item, and m_items.
Type MusicBackgroundListWidget::getType () const inline
Get background list rtpe.
Definition at line 171 of file musicbackgroundlistwidget.h.
void MusicBackgroundListWidget::itemClicked (int type, const QString & name) signal
Current item clicked.
Referenced by createItem(), and itemHasClicked().
void MusicBackgroundListWidget::itemCloseClicked (MusicBackgroundListItem * item) private slot
Current item close clicked.
Definition at line 307 of file musicbackgroundlistwidget.cpp.
References find(), MusicBackgroundListItem::getFilePath(), ITEM_COUNT, itemHasClicked(), m_currentItem, m_gridLayout, m_items, and MusicToastLabel::popup().
Referenced by createItem().
void MusicBackgroundListWidget::itemHasClicked (MusicBackgroundListItem * item) private slot
Current item has clicked.
Definition at line 336 of file musicbackgroundlistwidget.cpp.
References MusicBackgroundListItem::getFileName(), itemClicked(), m_currentItem, m_type, and MusicBackgroundListItem::setSelect().
Referenced by createItem(), itemCloseClicked(), and updateLastedItem().
void MusicBackgroundListWidget::setCurrentItemName (const QString & name)
Select current item by name when the widget show.
Definition at line 165 of file musicbackgroundlistwidget.cpp.
References m_currentItem, m_items, and name.
Referenced by MusicBackgroundSkinDialog::listWidgetItemClicked(), and MusicBackgroundSkinDialog::setCurrentBackgroundTheme().
void MusicBackgroundListWidget::setType (Type type) inline
Set background list rtpe.
Definition at line 167 of file musicbackgroundlistwidget.h.
Referenced by MusicBackgroundDailyWidget::MusicBackgroundDailyWidget(), MusicBackgroundOnlineWidget::MusicBackgroundOnlineWidget(), and MusicBackgroundSkinDialog::MusicBackgroundSkinDialog().
void MusicBackgroundListWidget::updateItem (const MusicBackgroundImage & image, const QString & path)
Update item by backgroud image.
Definition at line 219 of file musicbackgroundlistwidget.cpp.
References m_items.
Referenced by MusicBackgroundRemoteWidget::downLoadFinished().
void MusicBackgroundListWidget::updateLastedItem ()
Update lasted item state.
Definition at line 299 of file musicbackgroundlistwidget.cpp.
References itemHasClicked(), and m_items.
Referenced by MusicBackgroundSkinDialog::showCustomSkinDialog(), MusicBackgroundSkinDialog::showPaletteDialog(), and MusicBackgroundSkinDialog::updateArtistFileTheme().
Member Data Documentation
MusicBackgroundListItem* MusicBackgroundListWidget::m_currentItem protected
Definition at line 247 of file musicbackgroundlistwidget.h.
Referenced by clearAllItems(), itemCloseClicked(), itemHasClicked(), MusicBackgroundListWidget(), and setCurrentItemName().
QGridLayout* MusicBackgroundListWidget::m_gridLayout protected
Definition at line 246 of file musicbackgroundlistwidget.h.
Referenced by createItem(), itemCloseClicked(), and MusicBackgroundListWidget().
QList<MusicBackgroundListItem*> MusicBackgroundListWidget::m_items protected
Definition at line 248 of file musicbackgroundlistwidget.h.
Referenced by clearAllItems(), clearSelectState(), contains(), createItem(), find(), itemCloseClicked(), setCurrentItemName(), updateItem(), and updateLastedItem().
Type MusicBackgroundListWidget::m_type protected
Definition at line 245 of file musicbackgroundlistwidget.h.
Referenced by itemHasClicked(), and MusicBackgroundListWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundlistwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundlistwidget.cpp