TTKMusicPlayer: TTKTime Class Reference
TTKTime Class Reference
The class of the ttk time object.
#include <ttktime.h>
Public Types
enum Entity { Entity::Second, Entity::Millisecond }
Public Member Functions
TTKTime ()
TTKTime (const TTKTime &other)
TTKTime (qint64 value, Entity type)
TTKTime (int day, int hour, int min, int sec, int msec)
void setHMSM (int day, int hour, int min, int sec, int msec=0)
bool isNull () const
bool isValid () const
void setType (Entity type)
Entity type () const
void setGreedyMode (bool mode)
bool greedyMode () const
void setDay (int day)
void setHour (int hour)
void setMinute (int min)
void setSecond (int sec)
void setMillionSecond (int msec)
int day () const
int hour () const
int minute () const
int second () const
int millionSecond () const
QString toString (const QString &format) const
qint64 timestamp (Entity type) const
QString msecTime2LabelJustified ()
TTKTime & operator= (const TTKTime &other)
TTKTime & operator+= (const TTKTime &other)
TTKTime & operator+= (const int other)
TTKTime & operator-= (const TTKTime &other)
TTKTime & operator-= (const int other)
TTKTime & operator*= (const int other)
TTKTime & operator/= (const int other)
TTKTime operator+ (const TTKTime &other)
TTKTime operator+ (const int other)
TTKTime operator- (const TTKTime &other)
TTKTime operator- (const int other)
TTKTime operator* (const int other)
TTKTime operator/ (const int other)
bool operator== (const TTKTime &other) const
bool operator!= (const TTKTime &other) const
Static Public Member Functions
static TTKTime fromString (const QString &s, const QString &format)
static QString toString (qint64 value, Entity type, const QString &format)
static qint64 timestamp (bool ms=true)
static qint64 labelJustified2MsecTime (const QString &time)
static QString msecTime2LabelJustified (qint64 time, bool greedy=true)
Private Member Functions
void initialize ()
void copyToThis (const TTKTime &other)
void fromTimeStamp (qint64 value, int delta)
Private Attributes
bool m_greedyMode
Entity m_defaultType
int m_day
int m_hour
int m_min
int m_sec
int m_msec
Friends
QDataStream & operator<< (QDataStream &stream, const TTKTime &other)
QDataStream & operator>> (QDataStream &stream, TTKTime &other)
Detailed Description
The class of the ttk time object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttktime.h.
Member Enumeration Documentation
enum TTKTime::Entity strong
Enumerator
Second
Current time entity is sec
Millisecond
Current time entity is msec
Definition at line 33 of file ttktime.h.
Constructor & Destructor Documentation
TTKTime::TTKTime ()
Object contsructor.
Definition at line 25 of file ttktime.cpp.
References initialize().
Referenced by operator*(), operator+(), operator-(), operator/(), and toString().
TTKTime::TTKTime (const TTKTime & other)
Object contsructor.
Definition at line 32 of file ttktime.cpp.
References copyToThis().
TTKTime::TTKTime (qint64 value, Entity type)
Object contsructor by value and type.
Definition at line 37 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, MT_S, MT_S2MS, Second, and type().
TTKTime::TTKTime (int day, int hour, int min, int sec, int msec)
Object contsructor by day and hour and min and sec and msec.
Definition at line 44 of file ttktime.cpp.
References m_defaultType, Millisecond, and setHMSM().
Member Function Documentation
void TTKTime::copyToThis (const TTKTime & other) private
Copy other time data to this obejct;
Definition at line 251 of file ttktime.cpp.
References m_day, m_defaultType, m_greedyMode, m_hour, m_min, m_msec, and m_sec.
Referenced by operator=(), and TTKTime().
int TTKTime::day () const inline
Get current day.
Definition at line 111 of file ttktime.h.
Referenced by msecTime2LabelJustified(), and setHMSM().
TTKTime TTKTime::fromString (const QString & s, const QString & format) static
Transform time from string by time format.
Definition at line 84 of file ttktime.cpp.
References setHMSM().
Referenced by labelJustified2MsecTime().
void TTKTime::fromTimeStamp (qint64 value, int delta) private
Transform time value by different time type;
Definition at line 262 of file ttktime.cpp.
References initialize(), m_day, m_hour, m_min, m_msec, m_sec, MT_D2S, MT_H2S, MT_M2S, and MT_S2MS.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), and TTKTime().
bool TTKTime::greedyMode () const inline
Get current greedy mode.
Definition at line 85 of file ttktime.h.
int TTKTime::hour () const inline
Get current hour.
Definition at line 115 of file ttktime.h.
Referenced by msecTime2LabelJustified().
void TTKTime::initialize () private
Init parameters;
Definition at line 242 of file ttktime.cpp.
References m_day, m_hour, m_min, m_msec, and m_sec.
Referenced by fromTimeStamp(), setHMSM(), and TTKTime().
bool TTKTime::isNull () const
Check current time is null.
Definition at line 74 of file ttktime.cpp.
References m_hour, m_min, m_msec, and m_sec.
Referenced by isValid().
bool TTKTime::isValid () const
Check current time is valid.
Definition at line 79 of file ttktime.cpp.
References isNull().
qint64 TTKTime::labelJustified2MsecTime (const QString & time) static
Transform string format(mm:ss) to msec time.
Definition at line 115 of file ttktime.cpp.
References fromString(), Millisecond, and timestamp().
Referenced by MusicM3UConfigManager::writeBuffer().
int TTKTime::millionSecond () const inline
Get current millionSecond.
Definition at line 127 of file ttktime.h.
Referenced by MusicLrcMakerWidget::translateTimeString().
int TTKTime::minute () const inline
Get current second.
Definition at line 119 of file ttktime.h.
Referenced by msecTime2LabelJustified().
QString TTKTime::msecTime2LabelJustified ()
Transform msec time to string format(mm:ss).
Definition at line 121 of file ttktime.cpp.
References m_day, m_greedyMode, m_hour, m_min, m_sec, MT_H, MT_H2S, and toString().
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadSingleFinished(), MusicWYQueryRequest::downLoadSingleFinished(), MusicVideoControlWidget::durationChanged(), MusicSoundKMicroWidget::durationChanged(), MusicWebFMRadioPlayWidget::durationChanged(), MusicApplication::durationChanged(), MusicMovingLabelSlider::mouseMoveEvent(), MusicLrcContainerForInterior::paintEvent(), MusicKGQueryMovieRequest::parseFromMovieProperty(), MusicSoundKMicroWidget::positionChanged(), MusicWebFMRadioPlayWidget::positionChanged(), MusicLrcMakerWidget::positionChanged(), MusicApplication::positionChanged(), MusicTTKFMRadioPlayWidget::positionChanged(), MusicConsoleModule::print(), MusicWYQueryMovieRequest::queryMovieList(), MusicWYQueryMovieRequest::queryVideoList(), MusicFPLConfigManager::readBuffer(), MusicDBPLConfigManager::readBuffer(), MusicPLSConfigManager::readBuffer(), MusicM3UConfigManager::readBuffer(), MusicSongMeta::readInformation(), and MusicVideoControlWidget::setValue().
QString TTKTime::msecTime2LabelJustified (qint64 time, bool greedy = true) static
Transform msec time to string format(mm:ss).
Definition at line 134 of file ttktime.cpp.
References day(), hour(), Millisecond, minute(), MT_H, MT_H2S, MT_S2MS, second(), and toString().
bool TTKTime::operator!= (const TTKTime & other) const
Definition at line 237 of file ttktime.cpp.
References Millisecond, and timestamp().
TTKTime TTKTime::operator* (const int other)
Definition at line 220 of file ttktime.cpp.
References m_defaultType, Millisecond, timestamp(), and TTKTime().
TTKTime & TTKTime::operator*= (const int other)
Definition at line 182 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, Millisecond, MT_S, MT_S2MS, Second, and timestamp().
TTKTime TTKTime::operator+ (const TTKTime & other)
Definition at line 196 of file ttktime.cpp.
References m_defaultType, Millisecond, timestamp(), and TTKTime().
TTKTime TTKTime::operator+ (const int other)
Definition at line 202 of file ttktime.cpp.
References m_defaultType, Millisecond, timestamp(), and TTKTime().
TTKTime & TTKTime::operator+= (const TTKTime & other)
Definition at line 154 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, Millisecond, MT_S, MT_S2MS, Second, and timestamp().
TTKTime & TTKTime::operator+= (const int other)
Definition at line 161 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, Millisecond, MT_S, MT_S2MS, Second, and timestamp().
TTKTime TTKTime::operator- (const TTKTime & other)
Definition at line 208 of file ttktime.cpp.
References m_defaultType, Millisecond, timestamp(), and TTKTime().
TTKTime TTKTime::operator- (const int other)
Definition at line 214 of file ttktime.cpp.
References m_defaultType, Millisecond, timestamp(), and TTKTime().
TTKTime & TTKTime::operator-= (const TTKTime & other)
Definition at line 168 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, Millisecond, MT_S, MT_S2MS, Second, and timestamp().
TTKTime & TTKTime::operator-= (const int other)
Definition at line 175 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, Millisecond, MT_S, MT_S2MS, Second, and timestamp().
TTKTime TTKTime::operator/ (const int other)
Definition at line 226 of file ttktime.cpp.
References m_defaultType, Millisecond, timestamp(), and TTKTime().
TTKTime & TTKTime::operator/= (const int other)
Definition at line 189 of file ttktime.cpp.
References fromTimeStamp(), m_defaultType, Millisecond, MT_S, MT_S2MS, Second, and timestamp().
TTKTime & TTKTime::operator= (const TTKTime & other)
Definition at line 148 of file ttktime.cpp.
References copyToThis().
bool TTKTime::operator== (const TTKTime & other) const
Definition at line 232 of file ttktime.cpp.
References Millisecond, and timestamp().
int TTKTime::second () const inline
Get current second.
Definition at line 123 of file ttktime.h.
Referenced by msecTime2LabelJustified().
void TTKTime::setDay (int day) inline
Set current day.
Definition at line 90 of file ttktime.h.
void TTKTime::setGreedyMode (bool mode) inline
Set current greedy mode.
Definition at line 81 of file ttktime.h.
void TTKTime::setHMSM (int day, int hour, int min, int sec, int msec = 0)
Set current day and hour and min and sec and msec.
Definition at line 51 of file ttktime.cpp.
References day(), initialize(), m_day, m_hour, m_min, m_msec, m_sec, MT_D2H, MT_H2M, MT_M2S, and MT_S2MS.
Referenced by fromString(), and TTKTime().
void TTKTime::setHour (int hour) inline
Set current hour.
Definition at line 94 of file ttktime.h.
void TTKTime::setMillionSecond (int msec) inline
Set current millionSecond.
Definition at line 106 of file ttktime.h.
void TTKTime::setMinute (int min) inline
Set current minute.
Definition at line 98 of file ttktime.h.
void TTKTime::setSecond (int sec) inline
Set current second.
Definition at line 102 of file ttktime.h.
void TTKTime::setType (Entity type) inline
Set current time type, see Type.
Definition at line 72 of file ttktime.h.
qint64 TTKTime::timestamp (Entity type) const
Get all time value by type.
Definition at line 102 of file ttktime.cpp.
References m_day, m_hour, m_min, m_msec, m_sec, MT_D2S, MT_H2S, MT_M2S, MT_S, MT_S2MS, and Second.
Referenced by labelJustified2MsecTime(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), MusicBDQueryLearnRequest::parseFromSongProperty(), MusicCloudManagerTableWidget::receiveDataFinshed(), MusicDownloadDataRequest::startRequest(), MusicSongSearchTableWidget::startSearchQuery(), MusicCloudManagerTableWidget::uploadFilesToServer(), and MusicSongSearchPopWidget::utcTimeToLocal().
qint64 TTKTime::timestamp (bool ms = true) static
Transform ms time from utc since epoch.
Definition at line 109 of file ttktime.cpp.
QString TTKTime::toString (qint64 value, Entity type, const QString & format) static
Transform time from value to string time format.
Definition at line 92 of file ttktime.cpp.
References TTKTime().
Referenced by msecTime2LabelJustified(), MusicSongRingtoneMaker::posChanged(), MusicLrcAnalysis::saveData(), and MusicLrcMakerWidget::translateTimeString().
QString TTKTime::toString (const QString & format) const
Transform time to string time format.
Definition at line 97 of file ttktime.cpp.
References m_hour, m_min, m_msec, and m_sec.
Entity TTKTime::type () const inline
Get current time type, see Type.
Definition at line 76 of file ttktime.h.
Referenced by TTKTime().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream & stream, const TTKTime & other) friend
Definition at line 196 of file ttktime.h.
QDataStream& operator>> (QDataStream & stream, TTKTime & other) friend
Definition at line 203 of file ttktime.h.
Member Data Documentation
int TTKTime::m_day private
Definition at line 227 of file ttktime.h.
Referenced by copyToThis(), fromTimeStamp(), initialize(), msecTime2LabelJustified(), setHMSM(), and timestamp().
Entity TTKTime::m_defaultType private
Definition at line 226 of file ttktime.h.
Referenced by copyToThis(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and TTKTime().
bool TTKTime::m_greedyMode private
Definition at line 225 of file ttktime.h.
Referenced by copyToThis(), and msecTime2LabelJustified().
int TTKTime::m_hour private
Definition at line 227 of file ttktime.h.
Referenced by copyToThis(), fromTimeStamp(), initialize(), isNull(), msecTime2LabelJustified(), setHMSM(), timestamp(), and toString().
int TTKTime::m_min private
Definition at line 228 of file ttktime.h.
Referenced by copyToThis(), fromTimeStamp(), initialize(), isNull(), msecTime2LabelJustified(), setHMSM(), timestamp(), and toString().
int TTKTime::m_msec private
Definition at line 228 of file ttktime.h.
Referenced by copyToThis(), fromTimeStamp(), initialize(), isNull(), setHMSM(), timestamp(), and toString().
int TTKTime::m_sec private
Definition at line 228 of file ttktime.h.
Referenced by copyToThis(), fromTimeStamp(), initialize(), isNull(), msecTime2LabelJustified(), setHMSM(), timestamp(), and toString().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttktime.h
TTKCommon/TTKLibrary/ttktime.cpp