TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/qrinput.h File Reference
qrinput.h File Reference
#include "qrencode.h"
#include "bitstream.h"
Classes
struct _QRinput_List
struct _QRinput
struct _QRinput_InputList
struct _QRinput_Struct
Macros
#define QRinput_lookAnTable(__c__) ((__c__ & 0x80)?-1:QRinput_anTable[(int)__c__])
Look up the alphabet-numeric convesion table (see JIS X0510:2004, pp.19).
#define MODE_INDICATOR_SIZE 4
Length of a standard mode indicator in bits.
#define STRUCTURE_HEADER_SIZE 20
Length of a segment of structured-append header.
#define MAX_STRUCTURED_SYMBOLS 16
Maximum number of symbols in a set of structured-appended symbols.
Typedefs
typedef struct _QRinput_List QRinput_List
typedef struct _QRinput_InputList QRinput_InputList
Functions
int QRinput_isSplittableMode (QRencodeMode mode)
unsigned char * QRinput_getByteStream (QRinput *input)
Pack all bit streams padding bits into a byte array.
int QRinput_estimateBitsModeNum (int size)
Estimate the length of the encoded bit stream of numeric data.
int QRinput_estimateBitsModeAn (int size)
Estimate the length of the encoded bit stream of alphabet-numeric data.
int QRinput_estimateBitsMode8 (int size)
Estimate the length of the encoded bit stream of 8 bit data.
int QRinput_estimateBitsModeKanji (int size)
Estimate the length of the encoded bit stream of kanji data.
QRinput * QRinput_dup (QRinput *input)
Variables
const signed char QRinput_anTable [128]
Macro Definition Documentation
#define MAX_STRUCTURED_SYMBOLS 16
Maximum number of symbols in a set of structured-appended symbols.
Definition at line 112 of file qrinput.h.
Referenced by QRinput_insertStructuredAppendHeader(), and QRinput_splitQRinputToStruct().
#define MODE_INDICATOR_SIZE 4
Length of a standard mode indicator in bits.
Definition at line 102 of file qrinput.h.
Referenced by QRinput_estimateBitsModeECI(), and QRinput_estimateBitStreamSizeOfEntry().
#define QRinput_lookAnTable (__c__) ((__c__ & 0x80)?-1:QRinput_anTable[(int)__c__])
Look up the alphabet-numeric convesion table (see JIS X0510:2004, pp.19).
Parameters
<strong>c</strong> character
Returns
value
Definition at line 95 of file qrinput.h.
Referenced by QRinput_checkModeAn(), and QRinput_encodeModeAn().
#define STRUCTURE_HEADER_SIZE 20
Length of a segment of structured-append header.
Definition at line 107 of file qrinput.h.
Referenced by QRinput_estimateBitStreamSizeOfEntry(), and QRinput_splitQRinputToStruct().
Typedef Documentation
typedef struct _QRinput_InputList QRinput_InputList
Definition at line 59 of file qrinput.h.
typedef struct _QRinput_List QRinput_List
Definition at line 33 of file qrinput.h.
Function Documentation
QRinput* QRinput_dup (QRinput * input)
Definition at line 326 of file qrinput.c.
References _QRinput::head, _QRinput::level, _QRinput::mqr, _QRinput_List::next, QRinput_appendEntry(), QRinput_free(), QRinput_List_dup(), QRinput_new2(), QRinput_newMQR(), and _QRinput::version.
Referenced by QRinput_splitQRinputToStruct().
int QRinput_estimateBitsMode8 (int size)
Estimate the length of the encoded bit stream of 8 bit data.
Parameters
size
Returns
number of bits
Definition at line 564 of file qrinput.c.
Referenced by QRinput_estimateBitStreamSizeOfEntry(), Split_eat8(), Split_eatAn(), and Split_eatNum().
int QRinput_estimateBitsModeAn (int size)
Estimate the length of the encoded bit stream of alphabet-numeric data.
Parameters
size
Returns
number of bits
Definition at line 491 of file qrinput.c.
Referenced by QRinput_estimateBitStreamSizeOfEntry(), Split_eat8(), Split_eatAn(), and Split_eatNum().
int QRinput_estimateBitsModeKanji (int size)
Estimate the length of the encoded bit stream of kanji data.
Parameters
size
Returns
number of bits
Definition at line 614 of file qrinput.c.
Referenced by QRinput_estimateBitStreamSizeOfEntry().
int QRinput_estimateBitsModeNum (int size)
Estimate the length of the encoded bit stream of numeric data.
Parameters
size
Returns
number of bits
Definition at line 379 of file qrinput.c.
Referenced by QRinput_estimateBitStreamSizeOfEntry(), Split_eat8(), Split_eatAn(), and Split_eatNum().
unsigned char* QRinput_getByteStream (QRinput * input)
Pack all bit streams padding bits into a byte array.
Parameters
input input data.
Returns
padded merged byte stream
Definition at line 1324 of file qrinput.c.
References BitStream_free(), BitStream_new(), BitStream_toByte(), and QRinput_getBitStream().
Referenced by MQRraw_new(), and QRraw_new().
int QRinput_isSplittableMode (QRencodeMode mode)
Definition at line 37 of file qrinput.c.
References QR_MODE_KANJI, and QR_MODE_NUM.
Referenced by QRspec_lengthIndicator(), and QRspec_maximumWords().
Variable Documentation
const signed char QRinput_anTable[128]
Definition at line 457 of file qrinput.c.