TTKMusicplayer: MusicLrcLocalLinkWidget Class Reference
MusicLrcLocalLinkWidget Class Reference
The class of the local lrc link widget.
#include <musiclrclocallinkwidget.h>
Public Slots
void fuzzyStateChanged ()
void findInLocalFile ()
void deleteFoundLrc ()
void confirmButtonClicked ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void currentLrcChanged (const QString &data)
Public Member Functions
MusicLrcLocalLinkWidget (QWidget *parent=nullptr)
~MusicLrcLocalLinkWidget ()
void setCurrentSongName (const QString &name)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void searchInLocalLrc ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
QString m_currentName
Ui::MusicLrcLocalLinkWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the local lrc link widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 73 of file musiclrclocallinkwidget.h.
Constructor & Destructor Documentation
MusicLrcLocalLinkWidget::MusicLrcLocalLinkWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 61 of file musiclrclocallinkwidget.cpp.
References confirmButtonClicked(), deleteFoundLrc(), findInLocalFile(), fuzzyStateChanged(), G_CONNECTION_PTR, m_ui, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle04, and MusicUIObject::MQSSToolButtonStyle04.
MusicLrcLocalLinkWidget::~MusicLrcLocalLinkWidget ()
Definition at line 101 of file musiclrclocallinkwidget.cpp.
References G_CONNECTION_PTR, and m_ui.
Member Function Documentation
void MusicLrcLocalLinkWidget::confirmButtonClicked () slot
Confirm button clicked.
Definition at line 172 of file musiclrclocallinkwidget.cpp.
References currentLrcChanged(), LRC_FILE, MusicUtils::String::lrcPrefix(), m_currentName, m_ui, MusicToastLabel::popup(), and TTK_LOGGER_ERROR.
Referenced by MusicLrcLocalLinkWidget().
void MusicLrcLocalLinkWidget::currentLrcChanged (const QString & data) signal
Current lrc changed by user, and emit Lrc flag.
Referenced by confirmButtonClicked().
void MusicLrcLocalLinkWidget::deleteFoundLrc () slot
Delete found lrc button clicked.
Definition at line 160 of file musiclrclocallinkwidget.cpp.
References m_ui, and MusicToastLabel::popup().
Referenced by MusicLrcLocalLinkWidget().
int MusicLrcLocalLinkWidget::exec () virtual slot
Override exec function.
Definition at line 211 of file musiclrclocallinkwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicLrcContainerForInterior::showLocalLinkWidget().
void MusicLrcLocalLinkWidget::findInLocalFile () slot
Find in local file button clicked.
Definition at line 145 of file musiclrclocallinkwidget.cpp.
References MusicLocalDataItem::m_name, MusicLocalDataItem::m_path, m_ui, and MusicUtils::File::openFileDialog().
Referenced by MusicLrcLocalLinkWidget().
void MusicLrcLocalLinkWidget::fuzzyStateChanged () slot
Search fuzzy state changed.
Definition at line 139 of file musiclrclocallinkwidget.cpp.
References m_ui, and searchInLocalLrc().
Referenced by MusicLrcLocalLinkWidget().
void MusicLrcLocalLinkWidget::searchInLocalLrc () protected
Search local lrc in dir.
Definition at line 114 of file musiclrclocallinkwidget.cpp.
References MusicUtils::String::lrcPrefix(), MusicLocalDataItem::m_name, MusicLocalDataItem::m_path, and m_ui.
Referenced by fuzzyStateChanged(), and setCurrentSongName().
void MusicLrcLocalLinkWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 107 of file musiclrclocallinkwidget.cpp.
References m_currentName, m_ui, name, and searchInLocalLrc().
Referenced by MusicLrcContainerForInterior::showLocalLinkWidget().
Member Data Documentation
QString MusicLrcLocalLinkWidget::m_currentName protected
Definition at line 123 of file musiclrclocallinkwidget.h.
Referenced by confirmButtonClicked(), and setCurrentSongName().
Ui::MusicLrcLocalLinkWidget* MusicLrcLocalLinkWidget::m_ui protected
Definition at line 124 of file musiclrclocallinkwidget.h.
Referenced by confirmButtonClicked(), deleteFoundLrc(), exec(), findInLocalFile(), fuzzyStateChanged(), MusicLrcLocalLinkWidget(), searchInLocalLrc(), setCurrentSongName(), and ~MusicLrcLocalLinkWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrclocallinkwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrclocallinkwidget.cpp