TTKMusicPlayer: MusicRemoteWidgetForRectangle Class Reference
MusicRemoteWidgetForRectangle Class Reference
The class of the desktop rectangle remote widget.
#include <musicremotewidgetforrectangle.h>
Public Member Functions
MusicRemoteWidgetForRectangle (QWidget *parent=nullptr)
~MusicRemoteWidgetForRectangle ()
virtual void setLabelText (const QString &value) overridefinal
Public Member Functions inherited from MusicRemoteWidget
MusicRemoteWidget (QWidget *parent=nullptr)
~MusicRemoteWidget ()
void setCurrentPlayStatus (bool status) const
void setVolumeValue (int index)
int mapRemoteTypeIndex ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
Public Member Functions inherited from TTKAbstractMoveWidget
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Private Attributes
MusicMarqueeWidget * m_songNameLabel
QWidget * m_toolWidget
Additional Inherited Members
Public Types inherited from MusicRemoteWidget
enum Module {
Null = 0, Square, Rectangle, SimpleStyle,
ComplexStyle, Ripple
}
Public Slots inherited from MusicRemoteWidget
void musicVolumeSliderChanged (int value)
void show ()
bool close ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
void show ()
Signals inherited from MusicRemoteWidget
void musicWindowChanged ()
void musicKeyChanged ()
void musicPlayPreviousChanged ()
void musicPlayNextChanged ()
void musicVolumeChanged (int value)
void musicSettingChanged ()
void musicRemoteTypeChanged (QAction *type)
Protected Member Functions inherited from MusicRemoteWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
void adjustPosition (QWidget *w)
Protected Member Functions inherited from TTKAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Protected Attributes inherited from MusicRemoteWidget
QPushButton * m_showMainWindowButton
QPushButton * m_preSongButton
QPushButton * m_nextSongButton
QPushButton * m_playButton
QPushButton * m_settingButton
QWidget * m_mainWidget
QWidget * m_volumeWidget
QToolButton * m_volumeButton
TTKClickedSlider * m_volumeSlider
Protected Attributes inherited from TTKAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Detailed Description
The class of the desktop rectangle remote widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicremotewidgetforrectangle.h.
Constructor & Destructor Documentation
MusicRemoteWidgetForRectangle::MusicRemoteWidgetForRectangle (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musicremotewidgetforrectangle.cpp.
References MusicRemoteWidget::adjustPosition(), MusicRemoteWidget::m_mainWidget, MusicRemoteWidget::m_nextSongButton, MusicRemoteWidget::m_playButton, MusicRemoteWidget::m_preSongButton, MusicRemoteWidget::m_settingButton, MusicRemoteWidget::m_showMainWindowButton, m_songNameLabel, m_toolWidget, MusicRemoteWidget::m_volumeWidget, MusicUIObject::MQSSBackgroundStyle04, and MusicUIObject::MQSSWidgetStyle01.
MusicRemoteWidgetForRectangle::~MusicRemoteWidgetForRectangle ()
Definition at line 40 of file musicremotewidgetforrectangle.cpp.
References m_songNameLabel.
Member Function Documentation
void MusicRemoteWidgetForRectangle::setLabelText (const QString & value) final override virtual
Set current song text.
Reimplemented from MusicRemoteWidget.
Definition at line 45 of file musicremotewidgetforrectangle.cpp.
References MusicUtils::Widget::elidedText(), m_songNameLabel, and MusicMarqueeWidget::setText().
Member Data Documentation
MusicMarqueeWidget* MusicRemoteWidgetForRectangle::m_songNameLabel private
Definition at line 46 of file musicremotewidgetforrectangle.h.
Referenced by MusicRemoteWidgetForRectangle(), setLabelText(), and ~MusicRemoteWidgetForRectangle().
QWidget* MusicRemoteWidgetForRectangle::m_toolWidget private
Definition at line 47 of file musicremotewidgetforrectangle.h.
Referenced by MusicRemoteWidgetForRectangle().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforrectangle.h
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforrectangle.cpp