TTKMusicPlayer: TTKUnsortedMap< _Key, _Value > Class Template Reference
TTKUnsortedMap< _Key, _Value > Class Template Reference
The class of the ttk unsorted map module.
#include <ttkunsortedmap.h>
Public Types
using key_type = _Key
using mapped_type = _Value
using value_type = std::pair< key_type, _Value >
using reference = _Value &
using const_reference = const _Value &
using _Container = std::vector< value_type >
using size_type = typename _Container::size_type
using iterator = typename _Container::iterator
using const_iterator = typename _Container::const_iterator
using reverse_iterator = typename _Container::reverse_iterator
using const_reverse_iterator = typename _Container::const_reverse_iterator
Public Member Functions
_CONSTEXPR_CONTAINER TTKUnsortedMap () noexcept
_CONSTEXPR_CONTAINER TTKUnsortedMap (const TTKUnsortedMap &_Right) noexcept
_CONSTEXPR_CONTAINER TTKUnsortedMap (TTKUnsortedMap &&_Right) noexcept
template<class _Iter >
_CONSTEXPR_CONTAINER TTKUnsortedMap (_Iter _First, _Iter _Last) noexcept
_CONSTEXPR_CONTAINER TTKUnsortedMap & operator= (const TTKUnsortedMap &_Right) noexcept
_CONSTEXPR_CONTAINER TTKUnsortedMap & operator= (TTKUnsortedMap &&_Right) noexcept
_CONSTEXPR_CONTAINER void swap (TTKUnsortedMap &_Right) noexcept
_CONSTEXPR_CONTAINER void clear () noexcept
_CONSTEXPR_CONTAINER bool empty () const noexcept
_CONSTEXPR_CONTAINER size_type size () const noexcept
template<class _Iter = iterator, typename std::enable_if<!std::is_same< _Iter, const_iterator >::value, int >::type = 0>
_CONSTEXPR_CONTAINER iterator erase (iterator _Where) noexcept
_CONSTEXPR_CONTAINER iterator erase (const_iterator _Where) noexcept
_CONSTEXPR_CONTAINER iterator erase (const_iterator _First, const_iterator _Last) noexcept
_CONSTEXPR_CONTAINER size_type erase (const key_type &_Keyval) noexcept
_CONSTEXPR_CONTAINER iterator begin () noexcept
_CONSTEXPR_CONTAINER const_iterator begin () const noexcept
_CONSTEXPR_CONTAINER iterator end () noexcept
_CONSTEXPR_CONTAINER const_iterator end () const noexcept
_CONSTEXPR_CONTAINER reverse_iterator rbegin () noexcept
_CONSTEXPR_CONTAINER const_reverse_iterator rbegin () const noexcept
_CONSTEXPR_CONTAINER reverse_iterator rend () noexcept
_CONSTEXPR_CONTAINER const_reverse_iterator rend () const noexcept
_CONSTEXPR_CONTAINER const_iterator cbegin () const noexcept
_CONSTEXPR_CONTAINER const_iterator cend () const noexcept
_CONSTEXPR_CONTAINER const_reverse_iterator crbegin () const noexcept
_CONSTEXPR_CONTAINER const_reverse_iterator crend () const noexcept
_CONSTEXPR_CONTAINER reference operator[] (const key_type &_Keyval)
_CONSTEXPR_CONTAINER reference at (const key_type &_Keyval)
_CONSTEXPR_CONTAINER const_reference at (const key_type &_Keyval) const
_CONSTEXPR_CONTAINER iterator find (const key_type &_Keyval) noexcept
_CONSTEXPR_CONTAINER const_iterator find (const key_type &_Keyval) const noexcept
_CONSTEXPR_CONTAINER size_type count (const key_type &_Keyval) const noexcept
_CONSTEXPR_CONTAINER iterator lower_bound (const key_type &_Keyval) noexcept
_CONSTEXPR_CONTAINER const_iterator lower_bound (const key_type &_Keyval) const noexcept
_CONSTEXPR_CONTAINER iterator upper_bound (const key_type &_Keyval) noexcept
_CONSTEXPR_CONTAINER const_iterator upper_bound (const key_type &_Keyval) const noexcept
_CONSTEXPR_CONTAINER std::pair< iterator, iterator > equal_range (const key_type &_Keyval) noexcept
_CONSTEXPR_CONTAINER std::pair< const_iterator, const_iterator > equal_range (const key_type &_Keyval) const noexcept
template<class... _Valtys>
_CONSTEXPR_CONTAINER std::pair< iterator, bool > emplace (_Valtys &&..._Vals)
template<class... _Valtys>
_CONSTEXPR_CONTAINER iterator emplace_hint (const_iterator _Where, _Valtys &&..._Vals)
_CONSTEXPR_CONTAINER iterator insert (const value_type &_Val)
_CONSTEXPR_CONTAINER iterator insert (value_type &&_Val)
_CONSTEXPR_CONTAINER iterator insert (const_iterator _Where, const value_type &_Val)
_CONSTEXPR_CONTAINER iterator insert (const_iterator _Where, value_type &&_Val)
template<class _Iter >
_CONSTEXPR_CONTAINER void insert (_Iter _First, _Iter _Last)
_CONSTEXPR_CONTAINER void insert (std::initializer_list< value_type > _Ilist)
Private Attributes
_Container m_conatiner
Detailed Description
template<class _Key, class _Value>
class TTKUnsortedMap< _Key, _Value >
The class of the ttk unsorted map module.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file ttkunsortedmap.h.
Member Typedef Documentation
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::_Container = std::vector<value_type>
Definition at line 45 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::const_iterator = typename _Container::const_iterator
Definition at line 50 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::const_reference = const _Value&
Definition at line 44 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::const_reverse_iterator = typename _Container::const_reverse_iterator
Definition at line 52 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::iterator = typename _Container::iterator
Definition at line 49 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::key_type = _Key
Definition at line 40 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::mapped_type = _Value
Definition at line 41 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::reference = _Value&
Definition at line 43 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::reverse_iterator = typename _Container::reverse_iterator
Definition at line 51 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::size_type = typename _Container::size_type
Definition at line 46 of file ttkunsortedmap.h.
template<class _Key, class _Value> using TTKUnsortedMap< _Key, _Value >::value_type = std::pair<key_type, _Value>
Definition at line 42 of file ttkunsortedmap.h.
Constructor & Destructor Documentation
template<class _Key, class _Value> _CONSTEXPR_CONTAINER TTKUnsortedMap< _Key, _Value >::TTKUnsortedMap () inline noexcept
Definition at line 55 of file ttkunsortedmap.h.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER TTKUnsortedMap< _Key, _Value >::TTKUnsortedMap (const TTKUnsortedMap< _Key, _Value > & _Right) inline noexcept
Definition at line 56 of file ttkunsortedmap.h.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER TTKUnsortedMap< _Key, _Value >::TTKUnsortedMap (TTKUnsortedMap< _Key, _Value > && _Right) inline noexcept
Definition at line 57 of file ttkunsortedmap.h.
template<class _Key, class _Value> template<class _Iter > _CONSTEXPR_CONTAINER TTKUnsortedMap< _Key, _Value >::TTKUnsortedMap (_Iter _First, _Iter _Last) inline noexcept
Definition at line 60 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::insert().
Member Function Documentation
template<class _Key, class _Value> _CONSTEXPR_CONTAINER reference TTKUnsortedMap< _Key, _Value >::at (const key_type & _Keyval) inline
Definition at line 202 of file ttkunsortedmap.h.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_reference TTKUnsortedMap< _Key, _Value >::at (const key_type & _Keyval) const inline
Definition at line 207 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::begin () inline noexcept
Definition at line 127 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
Referenced by TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::begin () const inline noexcept
Definition at line 132 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::cbegin () const inline noexcept
Definition at line 167 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::cend () const inline noexcept
Definition at line 172 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER void TTKUnsortedMap< _Key, _Value >::clear () inline noexcept
Definition at line 83 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER size_type TTKUnsortedMap< _Key, _Value >::count (const key_type & _Keyval) const inline noexcept
Definition at line 247 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), and TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_reverse_iterator TTKUnsortedMap< _Key, _Value >::crbegin () const inline noexcept
Definition at line 177 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_reverse_iterator TTKUnsortedMap< _Key, _Value >::crend () const inline noexcept
Definition at line 182 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> template<class... _Valtys> _CONSTEXPR_CONTAINER std::pair<iterator, bool> TTKUnsortedMap< _Key, _Value >::emplace (_Valtys &&... _Vals) inline
Definition at line 321 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::find(), and TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> template<class... _Valtys> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::emplace_hint (const_iterator _Where, _Valtys &&... _Vals) inline
Definition at line 337 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::find(), and TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER bool TTKUnsortedMap< _Key, _Value >::empty () const inline noexcept
Definition at line 88 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::end () inline noexcept
Definition at line 137 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
Referenced by TTKUnsortedMap< _Key, _Value >::count(), TTKUnsortedMap< _Key, _Value >::emplace(), TTKUnsortedMap< _Key, _Value >::emplace_hint(), TTKUnsortedMap< _Key, _Value >::equal_range(), TTKUnsortedMap< _Key, _Value >::erase(), TTKUnsortedMap< _Key, _Value >::find(), TTKUnsortedMap< _Key, _Value >::insert(), and TTKUnsortedMap< _Key, _Value >::upper_bound().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::end () const inline noexcept
Definition at line 142 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER std::pair<iterator, iterator> TTKUnsortedMap< _Key, _Value >::equal_range (const key_type & _Keyval) inline noexcept
Definition at line 281 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), and TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER std::pair<const_iterator, const_iterator> TTKUnsortedMap< _Key, _Value >::equal_range (const key_type & _Keyval) const inline noexcept
Definition at line 300 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), and TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> template<class _Iter = iterator, typename std::enable_if<!std::is_same< _Iter, const_iterator >::value, int >::type = 0> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::erase (iterator _Where) inline noexcept
Definition at line 99 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
Referenced by TTKUnsortedMap< _Key, _Value >::erase().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::erase (const_iterator _Where) inline noexcept
Definition at line 104 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::erase (const_iterator _First, const_iterator _Last) inline noexcept
Definition at line 109 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER size_type TTKUnsortedMap< _Key, _Value >::erase (const key_type & _Keyval) inline noexcept
Definition at line 114 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::erase(), and TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::find (const key_type & _Keyval) inline noexcept
Definition at line 221 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::begin(), and TTKUnsortedMap< _Key, _Value >::end().
Referenced by TTKUnsortedMap< _Key, _Value >::count(), TTKUnsortedMap< _Key, _Value >::emplace(), TTKUnsortedMap< _Key, _Value >::emplace_hint(), TTKUnsortedMap< _Key, _Value >::equal_range(), TTKUnsortedMap< _Key, _Value >::erase(), TTKUnsortedMap< _Key, _Value >::insert(), TTKUnsortedMap< _Key, _Value >::lower_bound(), and TTKUnsortedMap< _Key, _Value >::upper_bound().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::find (const key_type & _Keyval) const inline noexcept
Definition at line 234 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::begin(), and TTKUnsortedMap< _Key, _Value >::end().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::insert (const value_type & _Val) inline
Definition at line 352 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::find(), and TTKUnsortedMap< _Key, _Value >::m_conatiner.
Referenced by TTKUnsortedMap< _Key, _Value >::insert(), and TTKUnsortedMap< _Key, _Value >::TTKUnsortedMap().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::insert (value_type && _Val) inline
Definition at line 364 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::find(), and TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::insert (const_iterator _Where, const value_type & _Val) inline
Definition at line 376 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::find(), and TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::insert (const_iterator _Where, value_type && _Val) inline
Definition at line 387 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::find(), and TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> template<class _Iter > _CONSTEXPR_CONTAINER void TTKUnsortedMap< _Key, _Value >::insert (_Iter _First, _Iter _Last) inline
Definition at line 399 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::insert().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER void TTKUnsortedMap< _Key, _Value >::insert (std::initializer_list< value_type > _Ilist) inline
Definition at line 411 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::insert().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::lower_bound (const key_type & _Keyval) inline noexcept
Definition at line 259 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::lower_bound (const key_type & _Keyval) const inline noexcept
Definition at line 264 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER TTKUnsortedMap& TTKUnsortedMap< _Key, _Value >::operator= (const TTKUnsortedMap< _Key, _Value > & _Right) inline noexcept
Definition at line 65 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER TTKUnsortedMap& TTKUnsortedMap< _Key, _Value >::operator= (TTKUnsortedMap< _Key, _Value > && _Right) inline noexcept
Definition at line 71 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER reference TTKUnsortedMap< _Key, _Value >::operator[] (const key_type & _Keyval) inline
Definition at line 188 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER reverse_iterator TTKUnsortedMap< _Key, _Value >::rbegin () inline noexcept
Definition at line 147 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_reverse_iterator TTKUnsortedMap< _Key, _Value >::rbegin () const inline noexcept
Definition at line 152 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER reverse_iterator TTKUnsortedMap< _Key, _Value >::rend () inline noexcept
Definition at line 157 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_reverse_iterator TTKUnsortedMap< _Key, _Value >::rend () const inline noexcept
Definition at line 162 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER size_type TTKUnsortedMap< _Key, _Value >::size () const inline noexcept
Definition at line 93 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER void TTKUnsortedMap< _Key, _Value >::swap (TTKUnsortedMap< _Key, _Value > & _Right) inline noexcept
Definition at line 77 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::m_conatiner.
template<class _Key, class _Value> _CONSTEXPR_CONTAINER iterator TTKUnsortedMap< _Key, _Value >::upper_bound (const key_type & _Keyval) inline noexcept
Definition at line 269 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), and TTKUnsortedMap< _Key, _Value >::find().
template<class _Key, class _Value> _CONSTEXPR_CONTAINER const_iterator TTKUnsortedMap< _Key, _Value >::upper_bound (const key_type & _Keyval) const inline noexcept
Definition at line 275 of file ttkunsortedmap.h.
References TTKUnsortedMap< _Key, _Value >::end(), and TTKUnsortedMap< _Key, _Value >::find().
Member Data Documentation
template<class _Key, class _Value> _Container TTKUnsortedMap< _Key, _Value >::m_conatiner private
Definition at line 417 of file ttkunsortedmap.h.
Referenced by TTKUnsortedMap< _Key, _Value >::at(), TTKUnsortedMap< _Key, _Value >::begin(), TTKUnsortedMap< _Key, _Value >::cbegin(), TTKUnsortedMap< _Key, _Value >::cend(), TTKUnsortedMap< _Key, _Value >::clear(), TTKUnsortedMap< _Key, _Value >::crbegin(), TTKUnsortedMap< _Key, _Value >::crend(), TTKUnsortedMap< _Key, _Value >::emplace(), TTKUnsortedMap< _Key, _Value >::emplace_hint(), TTKUnsortedMap< _Key, _Value >::empty(), TTKUnsortedMap< _Key, _Value >::end(), TTKUnsortedMap< _Key, _Value >::erase(), TTKUnsortedMap< _Key, _Value >::insert(), TTKUnsortedMap< _Key, _Value >::operator=(), TTKUnsortedMap< _Key, _Value >::operator[](), TTKUnsortedMap< _Key, _Value >::rbegin(), TTKUnsortedMap< _Key, _Value >::rend(), TTKUnsortedMap< _Key, _Value >::size(), and TTKUnsortedMap< _Key, _Value >::swap().
The documentation for this class was generated from the following file:
TTKCommon/TTKLibrary/ttkunsortedmap.h