TTKMusicplayer: MusicTopAreaWidget Class Reference
MusicTopAreaWidget Class Reference
The class of the app top area widget.
#include <musictopareawidget.h>
Public Slots
void musicSearchTopListInfoFinished (const QString &data)
void musicShowSkinChangedWindow ()
void musicUserContextLogin ()
void musicSetAsArtBackground ()
void musicBgTransparentChanged ()
void musicBgTransparentChanged (int index)
void musicBgTransparentChanged (const QString &fileName)
void musicBackgroundSkinChanged (const QString &fileName)
void musicBackgroundSkinCustumChanged (const QString &fileName)
void musicBackgroundChanged ()
void musicBackgroundSliderStateChanged (bool state)
void musicBgThemeDownloadFinished ()
void musicBgThemeChangedByResize ()
void musicPlayListTransparent (int index)
void musicCircleRemote ()
void musicDiamondRemote ()
void musicSquareRemote ()
void musicRectangleRemote ()
void musicSimpleStyleRemote ()
void musicComplexStyleRemote ()
void musicWallpaperRemote (bool create)
void musicRipplesRemote ()
void musicDeleteRemote ()
void musicRemoteTypeChanged (QAction *type)
void musicRemoteTypeChanged (int type)
void musicStackedToolsWidgetChanged ()
Signals
void setTransparent (int index)
void musicSearchButtonClicked ()
Public Member Functions
MusicTopAreaWidget (QWidget *parent=0)
~MusicTopAreaWidget ()
void setupUi (Ui::MusicApplication *ui)
void setParameters (const QString &skin, int alpha, int list)
QString getBackgroundPath () const
int getBackgroundAlpha () const
int getBackgroundListAlpha ()
bool getBackgroundTransparentEnable () const
QPixmap getRendererPixmap () const
bool getUserLoginState () const
void setTimerStop ()
void showPlayStatus (bool status)
void setLabelText (const QString &name) const
void setVolumeValue (int value) const
Static Public Member Functions
static QString getClassName ()
static MusicTopAreaWidget * instance ()
Protected Member Functions
void createRemoteWidget ()
void drawWindowBackgroundRect ()
void drawWindowBackgroundRect (const QImage &image)
void drawWindowBackgroundRectString ()
void drawWindowBackgroundRectString (const QString &path)
Protected Attributes
Ui::MusicApplication * m_ui
MusicUserWindow * m_musicUserWindow
MusicBackgroundSkinDialog * m_musicBackgroundWidget
MusicRemoteWidget * m_musicRemoteWidget
MusicDownloadCounterPVThread * m_counterPVThread
QImage m_backgroundImage
int m_lastRemoteBeforeWallpaper
QString m_backgroundImagePath
int m_backgroundAlpha
int m_backgroundAListlpha
QTimer m_pictureCarouselTimer
Static Protected Attributes
static MusicTopAreaWidget * m_instance = nullptr
Detailed Description
The class of the app top area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musictopareawidget.h.
Constructor & Destructor Documentation
MusicTopAreaWidget::MusicTopAreaWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 26 of file musictopareawidget.cpp.
References M_BACKGROUND_PTR, m_backgroundAListlpha, m_counterPVThread, M_DOWNLOAD_QUERY_PTR, m_instance, m_lastRemoteBeforeWallpaper, m_musicUserWindow, m_pictureCarouselTimer, MT_S2MS, musicBackgroundChanged(), musicSearchTopListInfoFinished(), MusicDownloadCounterPVThread::startToDownload(), and MusicDownLoadDiscoverListThread::startToSearch().
MusicTopAreaWidget::~MusicTopAreaWidget ()
Definition at line 47 of file musictopareawidget.cpp.
References m_counterPVThread, m_musicBackgroundWidget, m_musicRemoteWidget, and m_musicUserWindow.
Member Function Documentation
void MusicTopAreaWidget::createRemoteWidget () protected
Create remote widget.
Definition at line 453 of file musictopareawidget.cpp.
References MusicApplication::instance(), m_musicRemoteWidget, m_ui, musicRemoteTypeChanged(), MusicRemoteWidget::setVolumeValue(), MusicRemoteWidget::show(), and MusicRemoteWidget::showPlayStatus().
Referenced by musicCircleRemote(), musicComplexStyleRemote(), musicDiamondRemote(), musicRectangleRemote(), musicRipplesRemote(), musicSimpleStyleRemote(), musicSquareRemote(), and musicWallpaperRemote().
void MusicTopAreaWidget::drawWindowBackgroundRect () protected
Draw window background rect.
Definition at line 472 of file musictopareawidget.cpp.
References m_backgroundImagePath, m_pictureCarouselTimer, and MusicBackgroundSkinDialog::setMBackground().
Referenced by drawWindowBackgroundRectString(), musicBackgroundChanged(), musicBgThemeDownloadFinished(), musicBgTransparentChanged(), and setParameters().
void MusicTopAreaWidget::drawWindowBackgroundRect (const QImage & image) protected
Draw window background rect.
Definition at line 478 of file musictopareawidget.cpp.
References drawWindowBackgroundRectString(), m_backgroundImage, and MusicUtils::Widget::reRenderImage().
void MusicTopAreaWidget::drawWindowBackgroundRectString () protected
Draw window background rect by qimage.
Definition at line 496 of file musictopareawidget.cpp.
References MusicApplication::instance(), m_backgroundAListlpha, m_backgroundAlpha, m_backgroundImage, M_SETTING_PTR, m_ui, setTransparent(), and MusicSettingManager::WidgetSize.
Referenced by drawWindowBackgroundRect(), musicBackgroundChanged(), musicBgThemeChangedByResize(), and musicBgTransparentChanged().
void MusicTopAreaWidget::drawWindowBackgroundRectString (const QString & path) protected
Draw window background rect by picture.
Definition at line 512 of file musictopareawidget.cpp.
References drawWindowBackgroundRect().
int MusicTopAreaWidget::getBackgroundAlpha () const inline
Get background skin alpha.
Definition at line 63 of file musictopareawidget.h.
Referenced by MusicApplication::writeXMLConfigToText().
int MusicTopAreaWidget::getBackgroundListAlpha ()
Get list background skin alpha.
Definition at line 125 of file musictopareawidget.cpp.
References MusicBackgroundSkinDialog::getBackgroundListAlpha(), m_backgroundAListlpha, and m_musicBackgroundWidget.
Referenced by MusicApplication::writeXMLConfigToText().
QString MusicTopAreaWidget::getBackgroundPath () const inline
Get background skin name.
Definition at line 59 of file musictopareawidget.h.
Referenced by MusicApplication::writeXMLConfigToText().
bool MusicTopAreaWidget::getBackgroundTransparentEnable () const
Get bg window skin enable.
Definition at line 134 of file musictopareawidget.cpp.
References MusicBackgroundSkinDialog::getBackgroundTransparentEnable(), and m_musicBackgroundWidget.
Referenced by MusicApplication::writeXMLConfigToText().
QString MusicTopAreaWidget::getClassName () static
Get class object name.
Definition at line 55 of file musictopareawidget.cpp.
QPixmap MusicTopAreaWidget::getRendererPixmap () const
Get background skin pixmap.
Definition at line 143 of file musictopareawidget.cpp.
References m_ui.
bool MusicTopAreaWidget::getUserLoginState () const
Check if the user is login now.
Definition at line 148 of file musictopareawidget.cpp.
References MusicUserWindow::isUserLogin(), and m_musicUserWindow.
Referenced by MusicApplication::musicCreateRightMenu(), and MusicSystemTrayMenu::showEvent().
MusicTopAreaWidget * MusicTopAreaWidget::instance () static
Get class object instance.
Definition at line 60 of file musictopareawidget.cpp.
References m_instance.
Referenced by MusicLrcContainerForInline::contextMenuEvent(), MusicBackgroundSkinDialog::currentColorChanged(), MusicDownloadBackgroundThread::downLoadFinished(), MusicBackgroundSkinDialog::listWidgetItemClicked(), MusicBackgroundSkinDialog::MusicBackgroundSkinDialog(), MusicRightAreaWidget::musicContainerForWallpaperClicked(), MusicSystemTrayMenu::MusicSystemTrayMenu(), MusicSongsToolBoxMaskWidget::paintEvent(), MusicSystemTrayMenu::showEvent(), MusicApplicationObject::windowCloseAnimation(), and MusicBackgroundSkinDialog::windowTransparentChanged().
void MusicTopAreaWidget::musicBackgroundChanged () slot
Changed current background skin.
Definition at line 267 of file musictopareawidget.cpp.
References drawWindowBackgroundRect(), drawWindowBackgroundRectString(), and M_BACKGROUND_PTR.
Referenced by musicBgThemeDownloadFinished(), and MusicTopAreaWidget().
void MusicTopAreaWidget::musicBackgroundSkinChanged (const QString & fileName) slot
Current background skin changed by new path.
Definition at line 251 of file musictopareawidget.cpp.
References m_backgroundImagePath, and musicBgTransparentChanged().
Referenced by MusicBackgroundSkinDialog::listWidgetItemClicked(), musicBackgroundSkinCustumChanged(), and musicSetAsArtBackground().
void MusicTopAreaWidget::musicBackgroundSkinCustumChanged (const QString & fileName) slot
Current background skin custum changed by new path.
Definition at line 257 of file musictopareawidget.cpp.
References APP_WINDOW_INDEX_1, m_ui, and musicBackgroundSkinChanged().
Referenced by MusicBackgroundSkinDialog::currentColorChanged().
void MusicTopAreaWidget::musicBackgroundSliderStateChanged (bool state) slot
Current slider state changed.
Definition at line 281 of file musictopareawidget.cpp.
References m_ui.
Referenced by MusicApplication::MusicApplication().
void MusicTopAreaWidget::musicBgThemeChangedByResize () slot
Resize current background skin when geometry changed.
Definition at line 300 of file musictopareawidget.cpp.
References drawWindowBackgroundRectString().
Referenced by MusicApplication::resizeEvent().
void MusicTopAreaWidget::musicBgThemeDownloadFinished () slot
Current background skin download is finished.
Definition at line 286 of file musictopareawidget.cpp.
References APP_WINDOW_INDEX_1, drawWindowBackgroundRect(), m_pictureCarouselTimer, m_ui, and musicBackgroundChanged().
Referenced by MusicDownloadBackgroundThread::downLoadFinished(), MusicApplication::musicLoadCurrentSongLrc(), MusicApplication::musicStatePlay(), MusicApplication::musicWindowConciseChanged(), and MusicApplication::showCurrentSong().
void MusicTopAreaWidget::musicBgTransparentChanged () slot
Current background transparent changed.
Definition at line 246 of file musictopareawidget.cpp.
References drawWindowBackgroundRect().
Referenced by MusicBackgroundSkinDialog::currentColorChanged(), musicBackgroundSkinChanged(), and MusicBackgroundSkinDialog::windowTransparentChanged().
void MusicTopAreaWidget::musicBgTransparentChanged (int index) slot
Current background transparent changed by index.
Definition at line 202 of file musictopareawidget.cpp.
References APP_WINDOW_INDEX_1, drawWindowBackgroundRectString(), m_backgroundAlpha, m_musicBackgroundWidget, m_ui, and MusicBackgroundSkinDialog::setSkinTransToolText().
void MusicTopAreaWidget::musicBgTransparentChanged (const QString & fileName) slot
Current background transparent changed by string.
Definition at line 217 of file musictopareawidget.cpp.
References APP_WINDOW_INDEX_1, drawWindowBackgroundRectString(), and m_ui.
void MusicTopAreaWidget::musicCircleRemote () slot
Changed current remote to circle mode.
Definition at line 314 of file musictopareawidget.cpp.
References createRemoteWidget(), and m_musicRemoteWidget.
Referenced by musicRemoteTypeChanged().
void MusicTopAreaWidget::musicComplexStyleRemote () slot
Changed current remote to complex style mode.
Definition at line 366 of file musictopareawidget.cpp.
References createRemoteWidget(), m_musicRemoteWidget, m_ui, and MusicRemoteWidget::setLabelText().
Referenced by musicRemoteTypeChanged().
void MusicTopAreaWidget::musicDeleteRemote () slot
Delete current remote.
Definition at line 410 of file musictopareawidget.cpp.
References m_musicRemoteWidget.
void MusicTopAreaWidget::musicDiamondRemote () slot
Changed current remote to diamond mode.
Definition at line 324 of file musictopareawidget.cpp.
References createRemoteWidget(), and m_musicRemoteWidget.
Referenced by musicRemoteTypeChanged().
void MusicTopAreaWidget::musicPlayListTransparent (int index) slot
Current list background transparent changed.
Definition at line 305 of file musictopareawidget.cpp.
References m_backgroundAListlpha, m_musicBackgroundWidget, MusicBackgroundSkinDialog::setListTransToolText(), and setTransparent().
void MusicTopAreaWidget::musicRectangleRemote () slot
Changed current remote to rectangle mode.
Definition at line 344 of file musictopareawidget.cpp.
References createRemoteWidget(), m_musicRemoteWidget, m_ui, and MusicRemoteWidget::setLabelText().
Referenced by musicRemoteTypeChanged().
void MusicTopAreaWidget::musicRemoteTypeChanged (QAction * type) slot
Switch to diff remote type.
Definition at line 416 of file musictopareawidget.cpp.
References m_musicRemoteWidget.
Referenced by createRemoteWidget(), musicWallpaperRemote(), and MusicApplication::readXMLConfigFromText().
void MusicTopAreaWidget::musicRemoteTypeChanged (int type) slot
Switch to diff remote type.
Definition at line 434 of file musictopareawidget.cpp.
References MusicRemoteWidget::Circle, MusicRemoteWidget::ComplexStyle, MusicRemoteWidget::Diamond, musicCircleRemote(), musicComplexStyleRemote(), musicDiamondRemote(), musicRectangleRemote(), musicRipplesRemote(), musicSimpleStyleRemote(), musicSquareRemote(), MusicRemoteWidget::Rectangle, MusicRemoteWidget::Ripples, MusicRemoteWidget::SimpleStyle, and MusicRemoteWidget::Square.
void MusicTopAreaWidget::musicRipplesRemote () slot
Changed current remote to ripples mode.
Definition at line 399 of file musictopareawidget.cpp.
References createRemoteWidget(), m_musicRemoteWidget, m_ui, and MusicRemoteWidget::setLabelText().
Referenced by musicRemoteTypeChanged().
void MusicTopAreaWidget::musicSearchButtonClicked () signal
Search current music song from net.
void MusicTopAreaWidget::musicSearchTopListInfoFinished (const QString & data) slot
Search top list information finished.
Definition at line 182 of file musictopareawidget.cpp.
References m_ui.
Referenced by MusicTopAreaWidget().
void MusicTopAreaWidget::musicSetAsArtBackground () slot
Set background as art big picture.
Definition at line 227 of file musictopareawidget.cpp.
References MusicBackgroundSkinDialog::cpoyArtFileToLocal(), M_BACKGROUND_PTR, m_musicBackgroundWidget, musicBackgroundSkinChanged(), and MusicBackgroundSkinDialog::updateArtFileTheme().
void MusicTopAreaWidget::musicShowSkinChangedWindow () slot
Show change background skin dailog.
Definition at line 187 of file musictopareawidget.cpp.
References MusicBackgroundSkinDialog::exec(), m_backgroundAListlpha, m_backgroundAlpha, m_backgroundImagePath, m_musicBackgroundWidget, and MusicBackgroundSkinDialog::setCurrentBgTheme().
Referenced by setupUi().
void MusicTopAreaWidget::musicSimpleStyleRemote () slot
Changed current remote to simple style mode.
Definition at line 355 of file musictopareawidget.cpp.
References createRemoteWidget(), m_musicRemoteWidget, m_ui, and MusicRemoteWidget::setLabelText().
Referenced by musicRemoteTypeChanged().
void MusicTopAreaWidget::musicSquareRemote () slot
Changed current remote to square mode.
Definition at line 334 of file musictopareawidget.cpp.
References createRemoteWidget(), and m_musicRemoteWidget.
Referenced by musicRemoteTypeChanged(), and setupUi().
void MusicTopAreaWidget::musicStackedToolsWidgetChanged () slot
Change to tool sets widget.
Definition at line 448 of file musictopareawidget.cpp.
Referenced by setupUi().
void MusicTopAreaWidget::musicUserContextLogin () slot
Send user to login.
Definition at line 197 of file musictopareawidget.cpp.
References m_musicUserWindow, and MusicUserWindow::musicUserContextLogin().
void MusicTopAreaWidget::musicWallpaperRemote (bool create) slot
Changed current remote to wallpaper mode.
Definition at line 377 of file musictopareawidget.cpp.
References createRemoteWidget(), m_lastRemoteBeforeWallpaper, m_musicRemoteWidget, m_ui, MusicRemoteWidget::mapRemoteTypeIndex(), musicRemoteTypeChanged(), and MusicRemoteWidget::setLabelText().
Referenced by MusicRightAreaWidget::musicContainerForWallpaperClicked().
void MusicTopAreaWidget::setLabelText (const QString & name) const
Set current song text.
Definition at line 166 of file musictopareawidget.cpp.
References m_musicRemoteWidget, and MusicRemoteWidget::setLabelText().
Referenced by MusicApplication::showCurrentSong().
void MusicTopAreaWidget::setParameters (const QString & skin, int alpha, int list)
Set background skin and alpha and list alpha parameter.
Definition at line 117 of file musictopareawidget.cpp.
References drawWindowBackgroundRect(), m_backgroundAListlpha, m_backgroundAlpha, and m_backgroundImagePath.
Referenced by MusicApplication::readXMLConfigFromText().
void MusicTopAreaWidget::setTimerStop ()
Stop background skin change tiemr.
Definition at line 153 of file musictopareawidget.cpp.
References m_pictureCarouselTimer.
Referenced by MusicApplication::musicStatePlay(), and MusicApplicationObject::windowCloseAnimation().
void MusicTopAreaWidget::setTransparent (int index) signal
Set list background skin transparent emit.
Referenced by drawWindowBackgroundRectString(), and musicPlayListTransparent().
void MusicTopAreaWidget::setupUi (Ui::MusicApplication * ui)
Set up app ui.
Definition at line 65 of file musictopareawidget.cpp.
References MusicApplication::instance(), m_musicUserWindow, m_ui, MusicUIObject::MKGBtnConciseIn, MusicUIObject::MKGBtnIdentify, MusicUIObject::MKGBtnMinimum, MusicUIObject::MKGBtnRemote, MusicUIObject::MKGBtnSetting, MusicUIObject::MKGBtnSkin, MusicUIObject::MKGBtnTClose, MusicUIObject::MKGBtnTools, MusicUIObject::MKGTinyBtnMainSearch, MusicUIObject::MLineEditStyle03, musicShowSkinChangedWindow(), musicSquareRemote(), and musicStackedToolsWidgetChanged().
Referenced by MusicApplication::MusicApplication().
void MusicTopAreaWidget::setVolumeValue (int value) const
Set current volume value by index.
Definition at line 174 of file musictopareawidget.cpp.
References m_musicRemoteWidget, and MusicRemoteWidget::setVolumeValue().
Referenced by MusicApplication::musicVolumeChanged(), and MusicApplication::musicVolumeMute().
void MusicTopAreaWidget::showPlayStatus (bool status)
Set current play state button.
Definition at line 158 of file musictopareawidget.cpp.
References m_musicRemoteWidget, and MusicRemoteWidget::showPlayStatus().
Referenced by MusicApplication::musicStatePlay(), MusicApplication::readXMLConfigFromText(), and MusicApplication::showCurrentSong().
Member Data Documentation
int MusicTopAreaWidget::m_backgroundAListlpha protected
Definition at line 246 of file musictopareawidget.h.
Referenced by drawWindowBackgroundRectString(), getBackgroundListAlpha(), musicPlayListTransparent(), musicShowSkinChangedWindow(), MusicTopAreaWidget(), and setParameters().
int MusicTopAreaWidget::m_backgroundAlpha protected
Definition at line 246 of file musictopareawidget.h.
Referenced by drawWindowBackgroundRectString(), musicBgTransparentChanged(), musicShowSkinChangedWindow(), and setParameters().
QImage MusicTopAreaWidget::m_backgroundImage protected
Definition at line 243 of file musictopareawidget.h.
Referenced by drawWindowBackgroundRect(), and drawWindowBackgroundRectString().
QString MusicTopAreaWidget::m_backgroundImagePath protected
Definition at line 245 of file musictopareawidget.h.
Referenced by drawWindowBackgroundRect(), musicBackgroundSkinChanged(), musicShowSkinChangedWindow(), and setParameters().
MusicDownloadCounterPVThread* MusicTopAreaWidget::m_counterPVThread protected
Definition at line 241 of file musictopareawidget.h.
Referenced by MusicTopAreaWidget(), and ~MusicTopAreaWidget().
MusicTopAreaWidget * MusicTopAreaWidget::m_instance = nullptr static protected
Definition at line 249 of file musictopareawidget.h.
Referenced by instance(), and MusicTopAreaWidget().
int MusicTopAreaWidget::m_lastRemoteBeforeWallpaper protected
Definition at line 244 of file musictopareawidget.h.
Referenced by MusicTopAreaWidget(), and musicWallpaperRemote().
MusicBackgroundSkinDialog* MusicTopAreaWidget::m_musicBackgroundWidget protected
Definition at line 239 of file musictopareawidget.h.
Referenced by getBackgroundListAlpha(), getBackgroundTransparentEnable(), musicBgTransparentChanged(), musicPlayListTransparent(), musicSetAsArtBackground(), musicShowSkinChangedWindow(), and ~MusicTopAreaWidget().
MusicRemoteWidget* MusicTopAreaWidget::m_musicRemoteWidget protected
Definition at line 240 of file musictopareawidget.h.
Referenced by createRemoteWidget(), musicCircleRemote(), musicComplexStyleRemote(), musicDeleteRemote(), musicDiamondRemote(), musicRectangleRemote(), musicRemoteTypeChanged(), musicRipplesRemote(), musicSimpleStyleRemote(), musicSquareRemote(), musicWallpaperRemote(), setLabelText(), setVolumeValue(), showPlayStatus(), and ~MusicTopAreaWidget().
MusicUserWindow* MusicTopAreaWidget::m_musicUserWindow protected
Definition at line 238 of file musictopareawidget.h.
Referenced by getUserLoginState(), MusicTopAreaWidget(), musicUserContextLogin(), setupUi(), and ~MusicTopAreaWidget().
QTimer MusicTopAreaWidget::m_pictureCarouselTimer protected
Definition at line 247 of file musictopareawidget.h.
Referenced by drawWindowBackgroundRect(), musicBgThemeDownloadFinished(), MusicTopAreaWidget(), and setTimerStop().
Ui::MusicApplication* MusicTopAreaWidget::m_ui protected
Definition at line 237 of file musictopareawidget.h.
Referenced by createRemoteWidget(), drawWindowBackgroundRectString(), getRendererPixmap(), musicBackgroundSkinCustumChanged(), musicBackgroundSliderStateChanged(), musicBgThemeDownloadFinished(), musicBgTransparentChanged(), musicComplexStyleRemote(), musicRectangleRemote(), musicRipplesRemote(), musicSearchTopListInfoFinished(), musicSimpleStyleRemote(), musicWallpaperRemote(), and setupUi().
The documentation for this class was generated from the following files:
TTKModule/musictopareawidget.h
TTKModule/musictopareawidget.cpp