TTKMusicplayer: QNIOHelper Class Reference
QNIOHelper Class Reference
The namespace of the qiniu io helper.
#include <qniohelper.h>
Static Public Member Functions
static QHttpMultiPart * createPutDataMultiPart (const QString &uploadToken, const QByteArray &data, const QString &key=0, const QString &fileName=0, const QNPutExtra *putExtra=0)
static QNetworkRequest listRequest (const QString &bucket, const QNMac *mac=0)
static QNetworkRequest deleteRequest (const QString &bucket, const QString &key, const QNMac *mac=0)
Detailed Description
The namespace of the qiniu io helper.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 31 of file qniohelper.h.
Member Function Documentation
QHttpMultiPart * QNIOHelper::createPutDataMultiPart (const QString & uploadToken, const QByteArray & data, const QString & key = 0, const QString & fileName = 0, const QNPutExtra * putExtra = 0) static
Create put data multi part.
Definition at line 8 of file qniohelper.cpp.
References QNPutExtra::getMimeType(), key, and QNUtils::randomFileName().
Referenced by QNSimpleUploadData::uploadDataToServer().
QNetworkRequest QNIOHelper::deleteRequest (const QString & bucket, const QString & key, const QNMac * mac = 0) static
Delete requestt.
Definition at line 103 of file qniohelper.cpp.
References QNConf::ACCESS_KEY, QNConf::RS_HOST, QNConf::SECRET_KEY, QNMac::signRequest(), and QNUtils::urlSafeBase64Encode().
Referenced by QNSimpleDeleteData::deleteDataToServer().
QNetworkRequest QNIOHelper::listRequest (const QString & bucket, const QNMac * mac = 0) static
List request.
Definition at line 72 of file qniohelper.cpp.
References QNConf::ACCESS_KEY, QNConf::RSF_HOST, QNConf::SECRET_KEY, and QNMac::signRequest().
Referenced by QNSimpleListData::listDataToServer().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qniohelper.h
TTKThirdParty/TTKExtras/qiniu/qniohelper.cpp