TTKMusicplayer: MusicDownLoadCommentsThread Class Reference
MusicDownLoadCommentsThread Class Reference abstract
The class to query song comments download data from net.
#include <musicdownloadcommentsthread.h>
Signals
void createSearchedItems (const MusicSongCommentItem &comments)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDownLoadCommentsThread (QObject *parent=0)
virtual void startToSearch (const QString &name)=0
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class to query song comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicdownloadcommentsthread.h.
Constructor & Destructor Documentation
MusicDownLoadCommentsThread::MusicDownLoadCommentsThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 3 of file musicdownloadcommentsthread.cpp.
Member Function Documentation
void MusicDownLoadCommentsThread::createSearchedItems (const MusicSongCommentItem & comments) signal
Create the current song comment.
Referenced by MusicQQCommentsThread::downLoadFinished(), MusicBDCommentsThread::downLoadFinished(), MusicWYCommentsThread::downLoadFinished(), MusicKGCommentsThread::downLoadFinished(), MusicKWCommentsThread::downLoadFinished(), and MusicXMCommentsThread::downLoadFinished().
static QString MusicDownLoadCommentsThread::getClassName () static
Get class object name.
virtual void MusicDownLoadCommentsThread::startToSearch (const QString & name) pure virtual
Start to Search data from name. Subclass should implement this function.
Implemented in MusicXMCommentsThread, MusicBDCommentsThread, MusicKGCommentsThread, MusicKWCommentsThread, MusicWYCommentsThread, and MusicQQCommentsThread.
Referenced by MusicLrcCommentsWidget::setCurrentSongName().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadcommentsthread.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadcommentsthread.cpp