TTKMusicplayer: MusicQQQueryMovieRequest Class Reference
MusicQQQueryMovieRequest Class Reference
The class of qq mv query download data from net.
#include <musicqqquerymovierequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadPageFinished ()
void downLoadSingleFinished ()
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicQQQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &value) overridefinal
virtual void startToPage (int offset) overridefinal
virtual void startToSingleSearch (const QString &value) overridefinal
Public Member Functions inherited from MusicQueryMovieRequest
MusicQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
void setQueryQuality (MusicObject::QueryQuality quality)
MusicObject::QueryQuality queryQuality () const
void setQueryAllRecords (bool state)
bool queryAllRecords () const
void setQueryLite (bool state)
bool queryLite () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryValue () const
void setSongInfoList (const MusicObject::MusicSongInformationList &songInfos)
const MusicObject::MusicSongInformationList & songInfoList () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Member Functions
void readFromMusicMVProperty (MusicObject::MusicSongInformation *info, bool more) const
QString generateMovieKey (int id, const QString &videoId) const
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongProperty *prop) const
bool findUrlFileSize (MusicObject::MusicSongPropertyList *props) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryServer { WYQueryServer, QQQueryServer, KWQueryServer, KGQueryServer }
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryMovieRequest
void createMovieInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 fileSizeByUrl (const QString &url)
Protected Attributes inherited from MusicAbstractQueryRequest
QString m_queryValue
QString m_queryServer
QueryType m_queryType
MusicObject::QueryQuality m_queryQuality
bool m_queryAllRecords
bool m_queryLite
MusicObject::MusicSongInformationList m_songInfos
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of qq mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicqqquerymovierequest.h.
Constructor & Destructor Documentation
MusicQQQueryMovieRequest::MusicQQQueryMovieRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicqqquerymovierequest.cpp.
References MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_QQ_INTERFACE.
Member Function Documentation
void MusicQQQueryMovieRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 62 of file musicqqquerymovierequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicObject::MusicSongInformation::m_artistId, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicAbstractQueryRequest::m_songInfos, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), name, QJson::Parser::parse(), readFromMusicMVProperty(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicQQQueryMovieRequest::downLoadPageFinished () slot
Download page data from net finished.
Definition at line 132 of file musicqqquerymovierequest.cpp.
References MusicQueryMovieRequest::createMovieInfoItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicResultsItem::m_updateTime, QJson::Parser::parse(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToPage().
void MusicQQQueryMovieRequest::downLoadSingleFinished () slot
Download single data from net finished.
Definition at line 175 of file musicqqquerymovierequest.cpp.
References MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractQueryRequest::m_queryValue, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicAbstractQueryRequest::m_songInfos, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), readFromMusicMVProperty(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSingleSearch().
QString MusicQQQueryMovieRequest::generateMovieKey (int id, const QString & videoId) const protected
Get movie key.
Definition at line 292 of file musicqqquerymovierequest.cpp.
References MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), QQ_MOVIE_KEY_URL, and MusicObject::syncNetworkQueryForGet().
Referenced by readFromMusicMVProperty().
void MusicQQQueryMovieRequest::readFromMusicMVProperty (MusicObject::MusicSongInformation * info, bool more) const protected
Read mv tags(size) from query results.
Definition at line 202 of file musicqqquerymovierequest.cpp.
References generateMovieKey(), key, MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongInformation::m_duration, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongProperty::m_size, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MusicQQInterface::makeRequestRawHeader(), MB_1000, MB_250, MB_500, MB_750, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), QQ_MOVIE_INFO_URL, MusicUtils::Number::sizeByte2Label(), MusicObject::syncNetworkQueryForGet(), TTK_NETWORK_QUERY_CHECK, and TTKStatic_cast.
Referenced by downLoadFinished(), and downLoadSingleFinished().
void MusicQQQueryMovieRequest::startToPage (int offset) final override virtual
Start to search data from name and type bt page.
Reimplemented from MusicPageQueryRequest.
Definition at line 31 of file musicqqquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadPageFinished(), MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryValue, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QQ_ARTIST_MOVIE_URL, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
void MusicQQQueryMovieRequest::startToSearch (QueryType type, const QString & value) final override virtual
Start to search data from name and type.
Implements MusicQueryMovieRequest.
Definition at line 10 of file musicqqquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryType, MusicAbstractQueryRequest::m_queryValue, MusicAbstractNetwork::m_reply, MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QQ_SONG_SEARCH_URL, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
void MusicQQQueryMovieRequest::startToSingleSearch (const QString & value) final override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 52 of file musicqqquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadSingleFinished(), MusicAbstractQueryRequest::m_queryValue, MT_MS, and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqquerymovierequest.h
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqquerymovierequest.cpp