TTKMusicplayer: MusicUserModel Class Reference
MusicUserModel Class Reference
The class of the user data model.
#include <musicusermodel.h>
Public Member Functions
MusicUserModel (QObject *parent=nullptr, QSqlDatabase db=QSqlDatabase::database("user-data"))
bool addUser (const MusicUserUIDItem &uid, const QString &pwd, const QString &mail, bool pwdMask=false)
bool addUser (const MusicUserInfoRecord &info)
bool updateUser (const MusicUserUIDItem &uid, const QString &pwd, const QString &mail, const QString &name, const QString &time, bool pwdMask=false)
bool updateUser (const MusicUserUIDItem &uid, const QString &name, const QString &sex, const QString &birth, const QString &city, const QString &country, const QString &sign)
bool updateUser (const MusicUserInfoRecord &info)
bool updateUserIcon (const MusicUserUIDItem &uid, const QString &icon)
bool updateUserPwd (const MusicUserUIDItem &uid, const QString &pwd, bool pwdMask=false)
bool deleteUser (const MusicUserUIDItem &uid)
bool passwordCheck (const MusicUserUIDItem &uid, const QString &pwd, bool pwdMask=false)
bool mailCheck (const MusicUserUIDItem &uid, const QString &mail)
QString userPasswordEncryption (const QString &pwd) const
QString getUserLogTime (const MusicUserUIDItem &uid)
QString getUserName (const MusicUserUIDItem &uid)
QString getUserSex (const MusicUserUIDItem &uid)
QString getUserCity (const MusicUserUIDItem &uid)
QString getUserCountry (const MusicUserUIDItem &uid)
QString getUserBirthday (const MusicUserUIDItem &uid)
QString getUserSignature (const MusicUserUIDItem &uid)
QString getUserPWDMD5 (const MusicUserUIDItem &uid)
QString getUserIcon (const MusicUserUIDItem &uid)
QStringList getAllUsers ()
QStringList getAllCities ()
QStringList getAllCountries (const QString &city)
Protected Member Functions
QString getRecordData (const MusicUserUIDItem &uid, const QString &field)
bool updateRecordData (const MusicUserUIDItem &uid, const TTKVariantMap &data)
bool databaseSelectedFilter (const MusicUserUIDItem &uid)
Detailed Description
The class of the user data model.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicusermodel.h.
Constructor & Destructor Documentation
MusicUserModel::MusicUserModel (QObject * parent = nullptr, QSqlDatabase db = QSqlDatabase::database("user-data")) explicit
Object contsructor.
Definition at line 9 of file musicusermodel.cpp.
Member Function Documentation
bool MusicUserModel::addUser (const MusicUserUIDItem & uid, const QString & pwd, const QString & mail, bool pwdMask = false)
Insert user into databse by uid and pwd and mail.
Definition at line 15 of file musicusermodel.cpp.
References databaseSelectedFilter(), MusicUserUIDItem::m_server, MusicUserUIDItem::m_uid, TTK_LOGGER_INFO, and userPasswordEncryption().
Referenced by MusicUserDialog::checkRegisterUser().
bool MusicUserModel::addUser (const MusicUserInfoRecord & info)
Insert user into databse by user info record.
Definition at line 48 of file musicusermodel.cpp.
References databaseSelectedFilter(), MusicUserInfoRecord::m_item, MusicUserInfoRecord::m_nickName, MusicUserInfoRecord::m_password, MusicUserUIDItem::m_server, MusicUserUIDItem::m_uid, TTK_LOGGER_INFO, and userPasswordEncryption().
bool MusicUserModel::databaseSelectedFilter (const MusicUserUIDItem & uid) protected
Set current database table by given uid.
Definition at line 231 of file musicusermodel.cpp.
References MusicUserUIDItem::m_server, and MusicUserUIDItem::m_uid.
Referenced by addUser(), deleteUser(), getRecordData(), mailCheck(), passwordCheck(), and updateRecordData().
bool MusicUserModel::deleteUser (const MusicUserUIDItem & uid)
Delete user by given uid.
Definition at line 123 of file musicusermodel.cpp.
References databaseSelectedFilter().
QStringList MusicUserModel::getAllCities ()
Get all cities.
Definition at line 173 of file musicusermodel.cpp.
Referenced by MusicUserRecordWidget::initTabF().
QStringList MusicUserModel::getAllCountries (const QString & city)
Get all countries.
Definition at line 187 of file musicusermodel.cpp.
Referenced by MusicUserRecordWidget::cityComboBoxIndexChanged().
QStringList MusicUserModel::getAllUsers ()
Get all user ids.
Definition at line 159 of file musicusermodel.cpp.
Referenced by MusicUserDialog::setUserModel(), and MusicUserDialog::userEditTextChanged().
QString MusicUserModel::getRecordData (const MusicUserUIDItem & uid, const QString & field) protected
Get record data by uid and field.
Definition at line 202 of file musicusermodel.cpp.
References databaseSelectedFilter().
QString MusicUserModel::getUserBirthday (const MusicUserUIDItem & uid) inline
Get user birthday.
Definition at line 111 of file musicusermodel.h.
Referenced by MusicUserRecordWidget::initTabF().
QString MusicUserModel::getUserCity (const MusicUserUIDItem & uid) inline
Get user city.
Definition at line 103 of file musicusermodel.h.
Referenced by MusicUserRecordWidget::initTabF().
QString MusicUserModel::getUserCountry (const MusicUserUIDItem & uid) inline
Get user country.
Definition at line 107 of file musicusermodel.h.
Referenced by MusicUserRecordWidget::initTabF().
QString MusicUserModel::getUserIcon (const MusicUserUIDItem & uid) inline
Get user icon.
Definition at line 123 of file musicusermodel.h.
Referenced by MusicUserDialog::checkUserLogin(), MusicUserRecordWidget::initTabS(), and MusicUserManagerDialog::setUserUID().
QString MusicUserModel::getUserLogTime (const MusicUserUIDItem & uid) inline
Get user logintime.
Definition at line 91 of file musicusermodel.h.
Referenced by MusicUserManagerDialog::createUserTime(), MusicUserRecordWidget::initTabF(), MusicUserManagerDialog::musicUserLogoff(), and MusicUserManagerDialog::~MusicUserManagerDialog().
QString MusicUserModel::getUserName (const MusicUserUIDItem & uid) inline
Get user name.
Definition at line 95 of file musicusermodel.h.
Referenced by MusicUserRecordWidget::confirmButtonClickedF(), MusicUserRecordWidget::initTabF(), MusicUserManagerDialog::setUserUID(), and MusicUserWindow::userStateChanged().
QString MusicUserModel::getUserPWDMD5 (const MusicUserUIDItem & uid) inline
Get user password by md5 mut.
Definition at line 119 of file musicusermodel.h.
Referenced by MusicUserDialog::checkUserLogin(), and MusicUserDialog::writeToUserSettings().
QString MusicUserModel::getUserSex (const MusicUserUIDItem & uid) inline
Get user sex.
Definition at line 99 of file musicusermodel.h.
Referenced by MusicUserRecordWidget::initTabF().
QString MusicUserModel::getUserSignature (const MusicUserUIDItem & uid) inline
Get user signature.
Definition at line 115 of file musicusermodel.h.
Referenced by MusicUserRecordWidget::initTabF().
bool MusicUserModel::mailCheck (const MusicUserUIDItem & uid, const QString & mail)
Check mail exsit or not by given uid and mail.
Definition at line 144 of file musicusermodel.cpp.
References databaseSelectedFilter().
Referenced by MusicUserDialog::checkUserForgotPasswd().
bool MusicUserModel::passwordCheck (const MusicUserUIDItem & uid, const QString & pwd, bool pwdMask = false)
Check password valid or invalid by given uid and password.
Definition at line 134 of file musicusermodel.cpp.
References databaseSelectedFilter(), and userPasswordEncryption().
Referenced by MusicUserDialog::checkUserLogin(), and MusicUserRecordWidget::confirmButtonClickedT().
bool MusicUserModel::updateRecordData (const MusicUserUIDItem & uid, const TTKVariantMap & data) protected
Update record data by uid and field and data.
Definition at line 211 of file musicusermodel.cpp.
References databaseSelectedFilter(), and key.
Referenced by updateUser(), updateUserIcon(), and updateUserPwd().
bool MusicUserModel::updateUser (const MusicUserUIDItem & uid, const QString & pwd, const QString & mail, const QString & name, const QString & time, bool pwdMask = false)
Update user into databse by uid and pwd and mail and name and logintime.
Definition at line 80 of file musicusermodel.cpp.
References name, updateRecordData(), and userPasswordEncryption().
Referenced by MusicUserDialog::checkUserForgotPasswd(), MusicUserRecordWidget::confirmButtonClickedF(), MusicUserManagerDialog::musicUserLogoff(), and MusicUserManagerDialog::~MusicUserManagerDialog().
bool MusicUserModel::updateUser (const MusicUserUIDItem & uid, const QString & name, const QString & sex, const QString & birth, const QString & city, const QString & country, const QString & sign)
Update user into databse by uid and name and sex and birth and city and country nad sign.
Definition at line 90 of file musicusermodel.cpp.
References name, and updateRecordData().
bool MusicUserModel::updateUser (const MusicUserInfoRecord & info)
Update user into databse by user info record.
Definition at line 102 of file musicusermodel.cpp.
References MusicUserInfoRecord::m_item, MusicUserInfoRecord::m_nickName, and updateRecordData().
bool MusicUserModel::updateUserIcon (const MusicUserUIDItem & uid, const QString & icon)
Update user icon by uid and icon path.
Definition at line 109 of file musicusermodel.cpp.
References updateRecordData().
Referenced by MusicUserRecordWidget::saveFileButtonClickedS().
bool MusicUserModel::updateUserPwd (const MusicUserUIDItem & uid, const QString & pwd, bool pwdMask = false)
Update user password by uid and new password.
Definition at line 116 of file musicusermodel.cpp.
References updateRecordData(), and userPasswordEncryption().
Referenced by MusicUserRecordWidget::confirmButtonClickedT().
QString MusicUserModel::userPasswordEncryption (const QString & pwd) const
To encrypt user password by md5.
Definition at line 154 of file musicusermodel.cpp.
References MusicUtils::Algorithm::md5().
Referenced by addUser(), passwordCheck(), updateUser(), and updateUserPwd().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicUserKits/musicusermodel.h
TTKModule/TTKCore/musicUserKits/musicusermodel.cpp