TTKMusicplayer: TTKThirdParty/TTKExtras/qrencode/rscode.h File Reference
rscode.h File Reference
Typedefs
typedef struct _RS RS
Functions
RS * init_rs (int symsize, int gfpoly, int fcr, int prim, int nroots, int pad)
void encode_rs_char (RS *rs, const unsigned char *data, unsigned char *parity)
void free_rs_char (RS *rs)
void free_rs_cache (void)
Typedef Documentation
typedef struct _RS RS
Definition at line 34 of file rscode.h.
Function Documentation
void encode_rs_char (RS * rs, const unsigned char * data, unsigned char * parity)
Definition at line 299 of file rscode.c.
References A0, ALPHA_TO, GENPOLY, INDEX_OF, MODNN, NN, NROOTS, and PAD.
Referenced by RSblock_initBlock().
void free_rs_cache (void)
Definition at line 249 of file rscode.c.
References free_rs_char(), _RS::next, rslist, and rslist_mutex.
Referenced by QRcode_clearCache().
void free_rs_char (RS * rs)
Definition at line 241 of file rscode.c.
References _RS::alpha_to, _RS::genpoly, and _RS::index_of.
Referenced by free_rs_cache().
RS* init_rs (int symsize, int gfpoly, int fcr, int prim, int nroots, int pad)
Definition at line 210 of file rscode.c.
References DONE, _RS::fcr, _RS::gfpoly, init_rs_char(), _RS::mm, _RS::next, _RS::nroots, _RS::pad, _RS::prim, rslist, and rslist_mutex.
Referenced by MQRraw_new(), and RSblock_init().