TTKMusicplayer: MusicFunctionToolBoxWidget Class Reference
MusicFunctionToolBoxWidget Class Reference
The class of the function tool box widget.
#include <musicfunctiontoolboxwidget.h>
Public Slots
void setCurrentIndex (int index)
void mousePressAt (int index)
void setTransparent (int alpha)
Public Member Functions
MusicFunctionToolBoxWidget (QWidget *parent=nullptr)
~MusicFunctionToolBoxWidget ()
void addItem (QWidget *item, const QString &text)
void removeItem (QWidget *item)
void swapItem (int before, int after)
void setTitle (QWidget *item, const QString &text)
QString getTitle (QWidget *item) const
void resizeScrollIndex (int index) const
int currentIndex () const
int count () const
Protected Member Functions
virtual MusicFunctionToolBoxWidgetItem * createItem (QWidget *item, const QString &text)
virtual void mousePressEvent (QMouseEvent *event) override
int foundMappingIndex (int index)
Protected Attributes
int m_currentIndex
int m_itemIndexRaise
QVBoxLayout * m_layout
QScrollArea * m_scrollArea
QWidget * m_contentsWidget
QList< MusicToolBoxWidgetItem > m_itemList
Detailed Description
The class of the function tool box widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 217 of file musicfunctiontoolboxwidget.h.
Constructor & Destructor Documentation
MusicFunctionToolBoxWidget::MusicFunctionToolBoxWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 291 of file musicfunctiontoolboxwidget.cpp.
References MusicUtils::Widget::generateVScrollAreaFormat(), m_contentsWidget, m_currentIndex, m_itemIndexRaise, m_layout, m_scrollArea, and setTransparent().
MusicFunctionToolBoxWidget::~MusicFunctionToolBoxWidget ()
Definition at line 321 of file musicfunctiontoolboxwidget.cpp.
References m_itemList, m_layout, and m_scrollArea.
Member Function Documentation
void MusicFunctionToolBoxWidget::addItem (QWidget * item, const QString & text)
Add widget item.
Definition at line 331 of file musicfunctiontoolboxwidget.cpp.
References count(), createItem(), m_currentIndex, MusicToolBoxWidgetItem::m_itemIndex, m_itemIndexRaise, m_itemList, m_layout, and MusicToolBoxWidgetItem::m_widgetItem.
Referenced by MusicCloudToolBoxWidget::createWidgetItem(), MusicDownloadToolBoxWidget::createWidgetItem(), and MusicSongsSummariziedWidget::createWidgetItem().
int MusicFunctionToolBoxWidget::count () const
Get item's count.
Definition at line 436 of file musicfunctiontoolboxwidget.cpp.
References m_itemList.
Referenced by addItem(), and swapItem().
MusicFunctionToolBoxWidgetItem * MusicFunctionToolBoxWidget::createItem (QWidget * item, const QString & text) protected virtual
Create item.
Reimplemented in MusicSongsToolBoxWidget, MusicDownloadToolBoxWidget, and MusicCloudToolBoxWidget.
Definition at line 476 of file musicfunctiontoolboxwidget.cpp.
References MusicFunctionToolBoxWidgetItem::addItem(), m_itemIndexRaise, and MusicFunctionToolBoxWidgetItem::setItemExpand().
Referenced by addItem().
int MusicFunctionToolBoxWidget::currentIndex () const
Get current index.
Definition at line 431 of file musicfunctiontoolboxwidget.cpp.
References m_currentIndex.
Referenced by MusicApplication::getCurrentPlaylist(), MusicApplication::musicListLovestContains(), MusicApplication::musicPlayIndex(), MusicApplication::musicPlayIndexClicked(), MusicSongsSummariziedWidget::setDeleteItemAt(), and MusicApplication::setMusicPlayIndex().
int MusicFunctionToolBoxWidget::foundMappingIndex (int index) protected
Found mapped index in container.
Definition at line 489 of file musicfunctiontoolboxwidget.cpp.
References m_itemList.
Referenced by MusicSongsSummariziedWidget::addNewDir(), MusicSongsSummariziedWidget::addNewFiles(), MusicSongsSummariziedWidget::addToPlayedList(), MusicSongsSummariziedWidget::addToPlayLater(), MusicSongsSummariziedWidget::changRowItemName(), MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItemAll(), mousePressAt(), MusicSongsSummariziedWidget::musicListSongSortBy(), MusicSongsSummariziedWidget::resetToolIndex(), and MusicSongsSummariziedWidget::swapDragItemIndex().
QString MusicFunctionToolBoxWidget::getTitle (QWidget * item) const
Get title text.
Definition at line 406 of file musicfunctiontoolboxwidget.cpp.
References MusicFunctionToolBoxWidgetItem::count(), MusicFunctionToolBoxWidgetItem::getTitle(), MusicFunctionToolBoxWidgetItem::item(), and m_itemList.
void MusicFunctionToolBoxWidget::mousePressAt (int index) slot
Current top widget is pressed.
Definition at line 450 of file musicfunctiontoolboxwidget.cpp.
References foundMappingIndex(), m_currentIndex, and m_itemList.
Referenced by MusicSongsSummariziedWidget::MusicSongsSummariziedWidget().
void MusicFunctionToolBoxWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Definition at line 484 of file musicfunctiontoolboxwidget.cpp.
void MusicFunctionToolBoxWidget::removeItem (QWidget * item)
Remove widget item.
Definition at line 357 of file musicfunctiontoolboxwidget.cpp.
References MusicFunctionToolBoxWidgetItem::count(), MusicFunctionToolBoxWidgetItem::item(), m_currentIndex, m_itemList, and m_layout.
Referenced by MusicSongsSummariziedWidget::deleteRowItem(), and MusicSongsSummariziedWidget::deleteRowItems().
void MusicFunctionToolBoxWidget::resizeScrollIndex (int index) const
Reset scroll index by given position.
Definition at line 422 of file musicfunctiontoolboxwidget.cpp.
References m_scrollArea.
Referenced by MusicSongsSummariziedWidget::playLocation().
void MusicFunctionToolBoxWidget::setCurrentIndex (int index) slot
Set current index.
Definition at line 441 of file musicfunctiontoolboxwidget.cpp.
References m_currentIndex, and m_itemList.
Referenced by MusicSongsSummariziedWidget::addNetMusicSongToList(), MusicSongsSummariziedWidget::addSongToPlaylist(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItems(), MusicSongsSummariziedWidget::importMusicSongsByPath(), MusicSongsSummariziedWidget::selectRow(), and MusicSongsSummariziedWidget::setCurrentIndex().
void MusicFunctionToolBoxWidget::setTitle (QWidget * item, const QString & text)
Set title text.
Definition at line 390 of file musicfunctiontoolboxwidget.cpp.
References MusicFunctionToolBoxWidgetItem::count(), MusicFunctionToolBoxWidgetItem::item(), m_itemList, and MusicFunctionToolBoxWidgetItem::setTitle().
Referenced by MusicCloudToolBoxWidget::createWidgetItem(), MusicDownloadToolBoxWidget::createWidgetItem(), MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::setItemTitle(), MusicSongsSummariziedWidget::setRecentMusicSongs(), MusicCloudToolBoxWidget::updateItemTitle(), and MusicDownloadToolBoxWidget::updateItemTitle().
void MusicFunctionToolBoxWidget::setTransparent (int alpha) slot
Set background transparent.
Definition at line 460 of file musicfunctiontoolboxwidget.cpp.
References m_scrollArea.
Referenced by MusicFunctionToolBoxWidget().
void MusicFunctionToolBoxWidget::swapItem (int before, int after)
Swap widget item.
Definition at line 375 of file musicfunctiontoolboxwidget.cpp.
References count(), m_itemList, m_layout, and MusicToolBoxWidgetItem::m_widgetItem.
Referenced by MusicSongsSummariziedWidget::swapDragItemIndex().
Member Data Documentation
QWidget* MusicFunctionToolBoxWidget::m_contentsWidget protected
Definition at line 294 of file musicfunctiontoolboxwidget.h.
Referenced by MusicFunctionToolBoxWidget().
int MusicFunctionToolBoxWidget::m_currentIndex protected
Definition at line 291 of file musicfunctiontoolboxwidget.h.
Referenced by addItem(), currentIndex(), MusicSongsSummariziedWidget::isCurrentIndex(), mousePressAt(), MusicFunctionToolBoxWidget(), MusicSongsSummariziedWidget::musicImportSongsOnlyDir(), MusicSongsSummariziedWidget::musicImportSongsOnlyFile(), MusicSongsSummariziedWidget::musicListSongSortBy(), MusicSongsSummariziedWidget::musicListSongToLovestListAt(), removeItem(), MusicSongsSummariziedWidget::searchFileListCache(), setCurrentIndex(), MusicSongsSummariziedWidget::setDeleteItemAt(), MusicSongsSummariziedWidget::setMusicIndexSwaped(), MusicSongsSummariziedWidget::sliderValueChanaged(), and MusicSongsSummariziedWidget::swapDragItemIndex().
int MusicFunctionToolBoxWidget::m_itemIndexRaise protected
Definition at line 291 of file musicfunctiontoolboxwidget.h.
Referenced by addItem(), MusicSongsSummariziedWidget::appendMusicItemList(), MusicCloudToolBoxWidget::createItem(), MusicDownloadToolBoxWidget::createItem(), MusicSongsToolBoxWidget::createItem(), createItem(), MusicSongsSummariziedWidget::createWidgetItem(), and MusicFunctionToolBoxWidget().
QList<MusicToolBoxWidgetItem> MusicFunctionToolBoxWidget::m_itemList protected
Definition at line 295 of file musicfunctiontoolboxwidget.h.
Referenced by addItem(), count(), MusicSongsSummariziedWidget::createWidgetItem(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItems(), foundMappingIndex(), getTitle(), mousePressAt(), removeItem(), setCurrentIndex(), MusicSongsToolBoxWidget::setMusicSongSort(), setTitle(), swapItem(), and ~MusicFunctionToolBoxWidget().
QVBoxLayout* MusicFunctionToolBoxWidget::m_layout protected
Definition at line 292 of file musicfunctiontoolboxwidget.h.
Referenced by addItem(), MusicFunctionToolBoxWidget(), removeItem(), swapItem(), and ~MusicFunctionToolBoxWidget().
QScrollArea* MusicFunctionToolBoxWidget::m_scrollArea protected
Definition at line 293 of file musicfunctiontoolboxwidget.h.
Referenced by MusicSongsSummariziedWidget::createWidgetItem(), MusicFunctionToolBoxWidget(), MusicSongsSummariziedWidget::MusicSongsSummariziedWidget(), resizeScrollIndex(), setTransparent(), and ~MusicFunctionToolBoxWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicfunctiontoolboxwidget.h
TTKModule/TTKWidget/musicCoreKits/musicfunctiontoolboxwidget.cpp