TTKMusicPlayer: MusicSongsListPlayTableWidget Class Reference
MusicSongsListPlayTableWidget Class Reference
The class of the songs list play table widget.
#include <musicsongslistplaytablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
virtual void removeItems () overridefinal
virtual void setDeleteItemAt () overridefinal
void setDeleteItemWithFile ()
void showTimeOut ()
void stayTimeOut ()
void setChangSongName ()
void musicMakeRingWidget ()
void musicTransformWidget ()
void musicSearchQuery (QAction *action)
void musicAddToPlayLater ()
void musicAddToPlayedList ()
void setItemRenameFinished (const QString &name)
void musicListSongSortBy (QAction *action)
Public Slots inherited from MusicAbstractSongsListTableWidget
virtual void setDeleteItemAt ()
void musicPlayClicked ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumQueryWidget ()
void musicSimilarQueryWidget ()
void musicSongSharedWidget ()
void musicSongDownload ()
void musicSongPlayedMovieFound ()
void musicPlayedSimilarQueryWidget ()
void musicSongPlayedSharedWidget ()
void musicSongPlayedKMicroWidget ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void isSearchResultEmpty (bool &empty)
void deleteItemAt (const TTKIntList &index, bool fileRemove)
void queryMusicIndexSwaped (int before, int after, int play, MusicSongList &songs)
void addSongToLovestListAt (bool state, int row)
void showFloatWidget ()
void musicListSongSortBy (int index)
Signals inherited from MusicAbstractSongsListTableWidget
void isCurrentIndex (bool &state)
Public Member Functions
MusicSongsListPlayTableWidget (int index, QWidget *parent=nullptr)
~MusicSongsListPlayTableWidget ()
virtual void updateSongsList (const MusicSongList &songs) overridefinal
virtual void selectRow (int index) overridefinal
void updateSearchFileName (MusicSongList *songs, const TTKIntList &result)
void setSongSort (MusicSongSort *sort)
void updateTimeLabel (const QString &current, const QString &total) const
void updateCurrentArtist ()
void adjustPlayWidgetRow ()
bool createUploadFileModule ()
Public Member Functions inherited from MusicAbstractSongsListTableWidget
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
MusicAbstractSongsListTableWidget (int index, QWidget *parent=nullptr)
~MusicAbstractSongsListTableWidget ()
virtual void setSongsList (MusicSongList *songs)
int totalHeight () const
void setToolIndex (int index)
void setPlayRowIndex (int index)
int playRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
virtual void wheelEvent (QWheelEvent *event) overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
void closeRenameItem ()
void startToDrag ()
void createContextMenu (QMenu &menu)
Private Attributes
QWidget * m_parentClass
int m_dragStartIndex
QPoint m_dragStartPoint
bool m_mouseMoved
QTimer m_timerShow
QTimer m_timerStay
MusicOpenFileWidget * m_openFileWidget
MusicSongsListItemInfoWidget * m_songsInfoWidget
MusicSongsListPlayWidget * m_songsPlayWidget
bool m_leftButtonPressed
bool m_renameActived
bool m_deleteItemWithFile
MusicSongList m_searchedSongs
QTableWidgetItem * m_renameItem
MusicLineEditDelegate * m_renameEditDelegate
MusicSongSort * m_songSort
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractSongsListTableWidget
void createMoreMenu (QMenu *menu)
QString currentSongPath () const
QString songPath (int index) const
QString currentSongName () const
QString songName (int index) const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicAbstractSongsListTableWidget
int m_toolIndex
int m_playRowIndex
MusicSongList * m_songs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_initialized
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the songs list play table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicsongslistplaytablewidget.h.
Constructor & Destructor Documentation
MusicSongsListPlayTableWidget::MusicSongsListPlayTableWidget (int index, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 31 of file musicsongslistplaytablewidget.cpp.
References MusicApplication::instance(), m_timerShow, m_timerStay, MusicUtils::Widget::setTransparent(), showTimeOut(), and stayTimeOut().
MusicSongsListPlayTableWidget::~MusicSongsListPlayTableWidget ()
Definition at line 65 of file musicsongslistplaytablewidget.cpp.
References m_openFileWidget, m_renameEditDelegate, m_songsInfoWidget, m_songsPlayWidget, and removeItems().
Member Function Documentation
void MusicSongsListPlayTableWidget::addSongToLovestListAt (bool state, int row) signal
Add or remove music list song to lovest list by row.
Referenced by itemCellClicked().
void MusicSongsListPlayTableWidget::adjustPlayWidgetRow ()
Adjust current play widget row.
Definition at line 197 of file musicsongslistplaytablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicAbstractSongsListTableWidget::m_playRowIndex, MusicAbstractSongsListTableWidget::m_songs, m_songsPlayWidget, MusicUIObject::MQSSColor01, name, QtItemSetForegroundColor, QtItemSetTextAlignment, MusicAbstractSongsListTableWidget::totalHeight(), and TTK_ITEM_SIZE_M.
Referenced by selectRow(), MusicSongsSummariziedWidget::setCurrentMusicSongTreeIndex(), and setDeleteItemAt().
void MusicSongsListPlayTableWidget::closeRenameItem () private
Close rename item.
Definition at line 745 of file musicsongslistplaytablewidget.cpp.
References MusicUtils::Widget::elidedText(), m_renameActived, m_renameEditDelegate, and m_renameItem.
Referenced by leaveEvent(), mousePressEvent(), and wheelEvent().
void MusicSongsListPlayTableWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Definition at line 683 of file musicsongslistplaytablewidget.cpp.
References MusicUtils::Widget::adjustMenuPosition(), createContextMenu(), MusicAbstractSongsListTableWidget::createMoreMenu(), isSearchResultEmpty(), MusicSongSort::m_order, m_songSort, MusicAbstractSongsListTableWidget::m_toolIndex, MusicSongSort::m_type, MusicUIObject::MQSSMenuStyle02, MUSIC_NETWORK_LIST, musicAddToPlayedList(), musicAddToPlayLater(), MusicAbstractSongsListTableWidget::musicAlbumQueryWidget(), MusicAbstractSongsListTableWidget::musicFileInformation(), musicListSongSortBy(), musicMakeRingWidget(), MusicAbstractSongsListTableWidget::musicOpenFileDir(), MusicAbstractSongsListTableWidget::musicPlayClicked(), MusicAbstractSongsListTableWidget::musicSongDownload(), MusicAbstractSongsListTableWidget::musicSongMovieFound(), musicTransformWidget(), setChangSongName(), MusicAbstractSongsListTableWidget::setDeleteItemAll(), setDeleteItemAt(), and setDeleteItemWithFile().
void MusicSongsListPlayTableWidget::createContextMenu (QMenu & menu) private
Create context menu.
Definition at line 827 of file musicsongslistplaytablewidget.cpp.
References MusicAbstractSongsListTableWidget::currentSongName(), musicSearchQuery(), MusicAbstractSongsListTableWidget::songName(), MusicUtils::String::stringSplit(), and TTK_LOW_LEVEL.
Referenced by contextMenuEvent().
bool MusicSongsListPlayTableWidget::createUploadFileModule ()
Create upload file module.
Definition at line 237 of file musicsongslistplaytablewidget.cpp.
References MusicOpenFileWidget::adjustWidgetRect(), LEFT_SIDE_WIDTH_MIN, m_openFileWidget, m_parentClass, MusicAbstractSongsListTableWidget::m_songs, MusicAbstractSongsListTableWidget::m_toolIndex, and MusicObject::playlistRowValid().
Referenced by updateSongsList().
void MusicSongsListPlayTableWidget::deleteItemAt (const TTKIntList & index, bool fileRemove) signal
Delete items from indexs and check remove file or not.
Referenced by setDeleteItemAt().
void MusicSongsListPlayTableWidget::isSearchResultEmpty (bool & empty) signal
Check current list is searched or not.
Referenced by contextMenuEvent(), itemCellClicked(), and startToDrag().
void MusicSongsListPlayTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 349 of file musicsongslistplaytablewidget.cpp.
References addSongToLovestListAt(), MusicAbstractSongsListTableWidget::createMoreMenu(), MusicApplication::instance(), isSearchResultEmpty(), MusicAbstractSongsListTableWidget::m_playRowIndex, musicAddToPlayLater(), MusicApplication::musicLovestContains(), MusicAbstractSongsListTableWidget::musicSongMovieFound(), and setDeleteItemAt().
void MusicSongsListPlayTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
draw new table item state
Definition at line 265 of file musicsongslistplaytablewidget.cpp.
References MusicApplication::instance(), MusicAbstractTableWidget::itemCellEntered(), MusicAbstractTableWidget::m_previousColorRow, MusicAbstractSongsListTableWidget::m_songs, m_songsInfoWidget, m_timerShow, m_timerStay, MT_S2MS, and MusicApplication::musicLovestContains().
Referenced by leaveEvent().
void MusicSongsListPlayTableWidget::leaveEvent (QEvent * event) final override private virtual
Definition at line 666 of file musicsongslistplaytablewidget.cpp.
References closeRenameItem(), itemCellEntered(), and m_songsInfoWidget.
void MusicSongsListPlayTableWidget::mouseMoveEvent (QMouseEvent * event) final override private virtual
Definition at line 644 of file musicsongslistplaytablewidget.cpp.
References m_dragStartPoint, m_leftButtonPressed, and m_mouseMoved.
void MusicSongsListPlayTableWidget::mousePressEvent (QMouseEvent * event) final override private virtual
Override the widget event.
Definition at line 631 of file musicsongslistplaytablewidget.cpp.
References closeRenameItem(), m_dragStartIndex, m_dragStartPoint, and m_leftButtonPressed.
void MusicSongsListPlayTableWidget::mouseReleaseEvent (QMouseEvent * event) final override private virtual
Definition at line 655 of file musicsongslistplaytablewidget.cpp.
References m_leftButtonPressed, m_mouseMoved, and startToDrag().
void MusicSongsListPlayTableWidget::musicAddToPlayedList () slot
Add music to played list.
Definition at line 584 of file musicsongslistplaytablewidget.cpp.
References MusicPlayedListPopWidget::append(), MusicPlayedListPopWidget::instance(), MusicAbstractSongsListTableWidget::m_songs, and MusicAbstractSongsListTableWidget::m_toolIndex.
Referenced by contextMenuEvent().
void MusicSongsListPlayTableWidget::musicAddToPlayLater () slot
Add music to played list and play later.
Definition at line 573 of file musicsongslistplaytablewidget.cpp.
References MusicPlayedListPopWidget::insert(), MusicPlayedListPopWidget::instance(), MusicAbstractSongsListTableWidget::m_songs, and MusicAbstractSongsListTableWidget::m_toolIndex.
Referenced by contextMenuEvent(), and itemCellClicked().
void MusicSongsListPlayTableWidget::musicListSongSortBy (int index) signal
Music list songs sort by type.
Referenced by contextMenuEvent(), and musicListSongSortBy().
void MusicSongsListPlayTableWidget::musicListSongSortBy (QAction * action) slot
Music list songs sort by type.
Definition at line 605 of file musicsongslistplaytablewidget.cpp.
References MusicSongSort::m_order, m_songSort, MusicAbstractSongsListTableWidget::m_toolIndex, MusicSongSort::m_type, and musicListSongSortBy().
void MusicSongsListPlayTableWidget::musicMakeRingWidget () slot
Open music make ring widget.
Definition at line 534 of file musicsongslistplaytablewidget.cpp.
References MusicSongRingtoneMaker::exec().
Referenced by contextMenuEvent().
void MusicSongsListPlayTableWidget::musicSearchQuery (QAction * action) slot
Open music song search query.
Definition at line 554 of file musicsongslistplaytablewidget.cpp.
References MusicAbstractSongsListTableWidget::currentSongName(), MusicRightAreaWidget::instance(), MusicRightAreaWidget::musicSongSearchedFound(), SEARCH_ITEM_DEFINED, MusicAbstractSongsListTableWidget::songName(), MusicUtils::String::stringSplit(), and TTK_LOW_LEVEL.
Referenced by createContextMenu().
void MusicSongsListPlayTableWidget::musicTransformWidget () slot
Open music transform widget.
Definition at line 544 of file musicsongslistplaytablewidget.cpp.
References MusicTransformWidget::exec().
Referenced by contextMenuEvent().
void MusicSongsListPlayTableWidget::queryMusicIndexSwaped (int before, int after, int play, MusicSongList & songs) signal
Swap the current play index when user drag and drop.
Referenced by startToDrag().
void MusicSongsListPlayTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 409 of file musicsongslistplaytablewidget.cpp.
References MusicAbstractSongsListTableWidget::m_playRowIndex, m_songsPlayWidget, MusicAbstractTableWidget::removeItems(), and TTK_ITEM_SIZE_M.
Referenced by MusicSongsSummariziedWidget::addSongToLovestListAt(), MusicSongsSummariziedWidget::musicListSongSortBy(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), MusicSongsSummariziedWidget::setRecentMusicSongs(), updateSearchFileName(), and ~MusicSongsListPlayTableWidget().
void MusicSongsListPlayTableWidget::selectRow (int index) final override virtual
Select the current play row.
Reimplemented from MusicAbstractSongsListTableWidget.
Definition at line 116 of file musicsongslistplaytablewidget.cpp.
References adjustPlayWidgetRow(), MusicAbstractSongsListTableWidget::m_playRowIndex, MusicAbstractSongsListTableWidget::m_songs, m_songsPlayWidget, MUSIC_TIME_INIT, name, MusicSong::playTime(), MusicAbstractSongsListTableWidget::selectRow(), MusicSongsListPlayWidget::setParameter(), MusicSong::setPlayTime(), MusicAbstractSongsListTableWidget::totalHeight(), and TTK_ITEM_SIZE_XL.
Referenced by startToDrag().
void MusicSongsListPlayTableWidget::setChangSongName () slot
Reset item name by current row.
Definition at line 508 of file musicsongslistplaytablewidget.cpp.
References MusicAbstractSongsListTableWidget::m_playRowIndex, m_renameActived, m_renameEditDelegate, m_renameItem, MusicAbstractSongsListTableWidget::m_songs, m_songsPlayWidget, and MusicSongsListPlayWidget::setItemRename().
Referenced by contextMenuEvent().
void MusicSongsListPlayTableWidget::setDeleteItemAt () final override virtual slot
Delete item from list at current row.
Definition at line 429 of file musicsongslistplaytablewidget.cpp.
References adjustPlayWidgetRow(), deleteItemAt(), MusicAbstractMoveDialog::exec(), m_deleteItemWithFile, MusicAbstractSongsListTableWidget::m_playRowIndex, MusicAbstractTableWidget::multiSelectedIndexList(), MusicMessageBox::setText(), MusicProgressWidget::setTitle(), MusicProgressWidget::show(), and MusicAbstractSongsListTableWidget::totalHeight().
Referenced by contextMenuEvent(), itemCellClicked(), and setDeleteItemWithFile().
void MusicSongsListPlayTableWidget::setDeleteItemWithFile () slot
Delete item or items from list with file.
Definition at line 474 of file musicsongslistplaytablewidget.cpp.
References m_deleteItemWithFile, and setDeleteItemAt().
Referenced by contextMenuEvent().
void MusicSongsListPlayTableWidget::setItemRenameFinished (const QString & name) slot
Rename item artist label is finised.
Definition at line 595 of file musicsongslistplaytablewidget.cpp.
References MusicAbstractSongsListTableWidget::m_playRowIndex.
void MusicSongsListPlayTableWidget::setSongSort (MusicSongSort * sort) inline
Set music sort.
Definition at line 62 of file musicsongslistplaytablewidget.h.
void MusicSongsListPlayTableWidget::showFloatWidget () signal
Show the float function widget.
Referenced by wheelEvent().
void MusicSongsListPlayTableWidget::showTimeOut () slot
Show play item information widget.
Definition at line 481 of file musicsongslistplaytablewidget.cpp.
References MusicAbstractSongsListTableWidget::isCurrentIndex(), MusicSongsListPlayWidget::itemRenameState(), MusicAbstractTableWidget::m_previousColorRow, MusicAbstractSongsListTableWidget::m_songs, m_songsInfoWidget, m_songsPlayWidget, m_timerShow, and MusicSongsListItemInfoWidget::setMusicSongInformation().
Referenced by MusicSongsListPlayTableWidget().
void MusicSongsListPlayTableWidget::startToDrag () private
Start to drag to play list.
Definition at line 774 of file musicsongslistplaytablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicAbstractSongsListTableWidget::isCurrentIndex(), isSearchResultEmpty(), m_dragStartIndex, m_leftButtonPressed, m_mouseMoved, MusicAbstractSongsListTableWidget::m_playRowIndex, name, queryMusicIndexSwaped(), and selectRow().
Referenced by mouseReleaseEvent().
void MusicSongsListPlayTableWidget::stayTimeOut () slot
Hide play item information widget.
Definition at line 501 of file musicsongslistplaytablewidget.cpp.
References m_songsInfoWidget, and m_timerStay.
Referenced by MusicSongsListPlayTableWidget().
void MusicSongsListPlayTableWidget::updateCurrentArtist ()
Update current artist when it download finished.
Definition at line 189 of file musicsongslistplaytablewidget.cpp.
References m_songsPlayWidget, and MusicSongsListPlayWidget::updateCurrentArtist().
void MusicSongsListPlayTableWidget::updateSearchFileName (MusicSongList * songs, const TTKIntList & result)
Set current search result indexs.
Definition at line 154 of file musicsongslistplaytablewidget.cpp.
References m_searchedSongs, MusicAbstractSongsListTableWidget::m_songs, removeItems(), MusicAbstractSongsListTableWidget::totalHeight(), and updateSongsList().
void MusicSongsListPlayTableWidget::updateSongsList (const MusicSongList & songs) final override virtual
Update songs files in table.
Reimplemented from MusicAbstractSongsListTableWidget.
Definition at line 74 of file musicsongslistplaytablewidget.cpp.
References createUploadFileModule(), MusicUtils::Widget::elidedText(), MusicUIObject::MQSSColor01, MusicSong::name(), MusicSong::playTime(), QtItemSetForegroundColor, QtItemSetTextAlignment, and MusicAbstractSongsListTableWidget::totalHeight().
Referenced by MusicSongsSummariziedWidget::addSongToLovestListAt(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), MusicSongsSummariziedWidget::setRecentMusicSongs(), and updateSearchFileName().
void MusicSongsListPlayTableWidget::updateTimeLabel (const QString & current, const QString & total) const
Update item time label time.
Definition at line 181 of file musicsongslistplaytablewidget.cpp.
References m_songsPlayWidget, and MusicSongsListPlayWidget::updateTimeLabel().
void MusicSongsListPlayTableWidget::wheelEvent (QWheelEvent * event) final override private virtual
Override the widget event.
Reimplemented from MusicSmoothMovingTableWidget.
Definition at line 676 of file musicsongslistplaytablewidget.cpp.
References closeRenameItem(), showFloatWidget(), and MusicSmoothMovingTableWidget::wheelEvent().
Member Data Documentation
bool MusicSongsListPlayTableWidget::m_deleteItemWithFile private
Definition at line 202 of file musicsongslistplaytablewidget.h.
Referenced by setDeleteItemAt(), and setDeleteItemWithFile().
int MusicSongsListPlayTableWidget::m_dragStartIndex private
Definition at line 192 of file musicsongslistplaytablewidget.h.
Referenced by mousePressEvent(), and startToDrag().
QPoint MusicSongsListPlayTableWidget::m_dragStartPoint private
Definition at line 193 of file musicsongslistplaytablewidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
bool MusicSongsListPlayTableWidget::m_leftButtonPressed private
Definition at line 201 of file musicsongslistplaytablewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and startToDrag().
bool MusicSongsListPlayTableWidget::m_mouseMoved private
Definition at line 194 of file musicsongslistplaytablewidget.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), and startToDrag().
MusicOpenFileWidget* MusicSongsListPlayTableWidget::m_openFileWidget private
Definition at line 197 of file musicsongslistplaytablewidget.h.
Referenced by createUploadFileModule(), and ~MusicSongsListPlayTableWidget().
QWidget* MusicSongsListPlayTableWidget::m_parentClass private
Definition at line 191 of file musicsongslistplaytablewidget.h.
Referenced by createUploadFileModule().
bool MusicSongsListPlayTableWidget::m_renameActived private
Definition at line 202 of file musicsongslistplaytablewidget.h.
Referenced by closeRenameItem(), and setChangSongName().
MusicLineEditDelegate* MusicSongsListPlayTableWidget::m_renameEditDelegate private
Definition at line 205 of file musicsongslistplaytablewidget.h.
Referenced by closeRenameItem(), setChangSongName(), and ~MusicSongsListPlayTableWidget().
QTableWidgetItem* MusicSongsListPlayTableWidget::m_renameItem private
Definition at line 204 of file musicsongslistplaytablewidget.h.
Referenced by closeRenameItem(), and setChangSongName().
MusicSongList MusicSongsListPlayTableWidget::m_searchedSongs private
Definition at line 203 of file musicsongslistplaytablewidget.h.
Referenced by updateSearchFileName().
MusicSongsListItemInfoWidget* MusicSongsListPlayTableWidget::m_songsInfoWidget private
Definition at line 198 of file musicsongslistplaytablewidget.h.
Referenced by itemCellEntered(), leaveEvent(), showTimeOut(), stayTimeOut(), and ~MusicSongsListPlayTableWidget().
MusicSongSort* MusicSongsListPlayTableWidget::m_songSort private
Definition at line 206 of file musicsongslistplaytablewidget.h.
Referenced by contextMenuEvent(), and musicListSongSortBy().
MusicSongsListPlayWidget* MusicSongsListPlayTableWidget::m_songsPlayWidget private
Definition at line 199 of file musicsongslistplaytablewidget.h.
Referenced by adjustPlayWidgetRow(), removeItems(), selectRow(), setChangSongName(), showTimeOut(), updateCurrentArtist(), updateTimeLabel(), and ~MusicSongsListPlayTableWidget().
QTimer MusicSongsListPlayTableWidget::m_timerShow private
Definition at line 196 of file musicsongslistplaytablewidget.h.
Referenced by itemCellEntered(), MusicSongsListPlayTableWidget(), and showTimeOut().
QTimer MusicSongsListPlayTableWidget::m_timerStay private
Definition at line 196 of file musicsongslistplaytablewidget.h.
Referenced by itemCellEntered(), MusicSongsListPlayTableWidget(), and stayTimeOut().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplaytablewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplaytablewidget.cpp