TTKMusicplayer: MusicUserWindow Class Reference
MusicUserWindow Class Reference
The class of the user window.
#include <musicuserwindow.h>
Public Slots
void musicUserLogin ()
void userStateChanged (const MusicUserUIDItem &uid, const QString &icon)
void musicUserContextLogin ()
void checkToAutoLogin ()
Public Member Functions
MusicUserWindow (QWidget *parent=nullptr)
~MusicUserWindow ()
bool isUserLogin () const
Protected Member Functions
bool connectDatabase ()
bool disConnectDatabase ()
Protected Attributes
Ui::MusicUserWindow * m_ui
MusicUserModel * m_userModel
MusicUserManagerDialog * m_userManager
Detailed Description
The class of the user window.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 36 of file musicuserwindow.h.
Constructor & Destructor Documentation
MusicUserWindow::MusicUserWindow (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 14 of file musicuserwindow.cpp.
References checkToAutoLogin(), connectDatabase(), m_ui, m_userManager, m_userModel, MusicUIObject::MQSSPushButtonStyle07, MT_MS, musicUserLogin(), MusicUserManagerDialog::setUserModel(), and userStateChanged().
MusicUserWindow::~MusicUserWindow ()
Definition at line 45 of file musicuserwindow.cpp.
References disConnectDatabase(), m_ui, m_userManager, and m_userModel.
Member Function Documentation
void MusicUserWindow::checkToAutoLogin () slot
Check current user to login auto automatic.
Definition at line 157 of file musicuserwindow.cpp.
References MusicUserDialog::checkToAutoLogin(), MusicUserDialog::exec(), m_userModel, MusicUserDialog::setUserModel(), and userStateChanged().
Referenced by MusicUserWindow().
bool MusicUserWindow::connectDatabase () protected
Connect to database.
Definition at line 77 of file musicuserwindow.cpp.
References DARABASEPATH_FULL, DB_EMAIL, DB_LOGINTIME, DB_PASSWD, DB_SERVER, DB_SEX, DB_SQLITE_DATABASE, DB_USERID, DB_USERNAME, and MusicToastLabel::popup().
Referenced by MusicUserWindow().
bool MusicUserWindow::disConnectDatabase () protected
Disconnect to database.
Definition at line 58 of file musicuserwindow.cpp.
Referenced by ~MusicUserWindow().
bool MusicUserWindow::isUserLogin () const
Check if the user is login now.
Definition at line 53 of file musicuserwindow.cpp.
Referenced by MusicTopAreaWidget::getUserLoginState().
void MusicUserWindow::musicUserContextLogin () slot
Send user to login.
Definition at line 147 of file musicuserwindow.cpp.
References m_userManager, MT_MS, musicUserLogin(), and MusicUserManagerDialog::musicUserLogoff().
Referenced by MusicTopAreaWidget::musicUserContextLogin().
void MusicUserWindow::musicUserLogin () slot
User widget button clicked.
Definition at line 139 of file musicuserwindow.cpp.
References MusicUserDialog::exec(), m_userModel, MusicUserDialog::setUserModel(), and userStateChanged().
Referenced by musicUserContextLogin(), and MusicUserWindow().
void MusicUserWindow::userStateChanged (const MusicUserUIDItem & uid, const QString & icon) slot
User login state changed.
Definition at line 121 of file musicuserwindow.cpp.
References MusicUtils::Widget::elidedText(), MusicUserModel::getUserName(), m_ui, MusicUserUIDItem::m_uid, m_userManager, m_userModel, MusicUtils::Image::pixmapToRound(), MusicUserManagerDialog::setUserUID(), USER_WINDOW_INDEX_0, and USER_WINDOW_INDEX_1.
Referenced by checkToAutoLogin(), musicUserLogin(), and MusicUserWindow().
Member Data Documentation
Ui::MusicUserWindow* MusicUserWindow::m_ui protected
Definition at line 80 of file musicuserwindow.h.
Referenced by MusicUserWindow(), userStateChanged(), and ~MusicUserWindow().
MusicUserManagerDialog* MusicUserWindow::m_userManager protected
Definition at line 82 of file musicuserwindow.h.
Referenced by musicUserContextLogin(), MusicUserWindow(), userStateChanged(), and ~MusicUserWindow().
MusicUserModel* MusicUserWindow::m_userModel protected
Definition at line 81 of file musicuserwindow.h.
Referenced by checkToAutoLogin(), musicUserLogin(), MusicUserWindow(), userStateChanged(), and ~MusicUserWindow().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicUserKits/musicuserwindow.h
TTKModule/TTKWidget/musicUserKits/musicuserwindow.cpp