TTKMusicPlayer: MusicPlaylistCategoryWidget Class Reference
MusicPlaylistCategoryWidget Class Reference
The class of the playlist music category widget.
#include <musicplaylistcategorywidget.h>
Public Member Functions
MusicPlaylistCategoryWidget (QWidget *parent=nullptr)
~MusicPlaylistCategoryWidget ()
virtual void resizeWidget () overridefinal
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Member Functions
void initialize ()
Private Attributes
QList< MusicPlaylistCategoryItem * > m_items
Detailed Description
The class of the playlist music category widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 72 of file musicplaylistcategorywidget.h.
Constructor & Destructor Documentation
MusicPlaylistCategoryWidget::MusicPlaylistCategoryWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 173 of file musicplaylistcategorywidget.cpp.
References initialize().
MusicPlaylistCategoryWidget::~MusicPlaylistCategoryWidget ()
Object destructor.
Definition at line 179 of file musicplaylistcategorywidget.cpp.
References m_items.
Member Function Documentation
void MusicPlaylistCategoryWidget::initialize () private
Create all widget in layout.
Definition at line 192 of file musicplaylistcategorywidget.cpp.
References TTK::UI::BackgroundStyle10, TTK::UI::ColorStyle12, MusicSettingManager::DownloadServerIndex, MusicCategoryConfigManager::fromFile(), G_SETTING_PTR, TTK::Widget::generateVScrollAreaStyle(), CategoryProperty::Hot, MusicAbstractQueryRequest::KG, MusicAbstractQueryRequest::KW, m_items, CategoryProperty::New, MusicCategoryConfigManager::PlayList, QUERY_KG_INTERFACE, QUERY_KW_INTERFACE, QUERY_WY_INTERFACE, MusicCategoryConfigManager::readBuffer(), TTK_ERROR_STREAM, TTKStaticCast, and MusicAbstractQueryRequest::WY.
Referenced by MusicPlaylistCategoryWidget().
void MusicPlaylistCategoryWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 184 of file musicplaylistcategorywidget.cpp.
References m_items, and qAsConst.
Member Data Documentation
QList<MusicPlaylistCategoryItem*> MusicPlaylistCategoryWidget::m_items private
Definition at line 97 of file musicplaylistcategorywidget.h.
Referenced by initialize(), resizeWidget(), and ~MusicPlaylistCategoryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistcategorywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistcategorywidget.cpp