TTKMusicplayer: MusicSong Class Reference
MusicSong Class Reference
The class of the music song info.
#include <musicsong.h>
Public Types
enum Sort {
SortByFileName, SortBySinger, SortByFileSize, SortByAddTime,
SortByPlayTime, SortByPlayCount
}
Public Member Functions
MusicSong ()
MusicSong (const QString &musicPath, const QString &musicName=QString())
MusicSong (const QString &musicPath, int playCount, const QString &musicName=QString())
MusicSong (const QString &musicPath, const QString &type, int playCount, const QString &musicName=QString())
MusicSong (const QString &musicPath, const QString &type, const QString &playTime, int playCount, const QString &musicName=QString())
MusicSong (const QString &musicPath, int playCount, const QString &playTime, const QString &musicName)
QString getMusicArtistFront () const
QString getMusicArtistBack () const
void setMusicAddTimeStr (const QString &t)
QString getMusicAddTimeStr () const
void setMusicSizeStr (const QString &s)
QString getMusicSizeStr () const
void setMusicName (const QString &n)
QString getMusicName () const
void setMusicPath (const QString &p)
QString getMusicPath () const
void setMusicType (const QString &t)
QString getMusicType () const
void setMusicPlayTime (const QString &t)
QString getMusicPlayTime () const
void setMusicAddTime (const qint64 t)
qint64 getMusicAddTime () const
void setMusicSize (const qint64 s)
qint64 getMusicSize () const
void setMusicPlayCount (const int c)
int getMusicPlayCount () const
void setMusicSort (const Sort s)
Sort getMusicSort () const
bool operator== (const MusicSong &other) const
bool operator< (const MusicSong &other) const
bool operator> (const MusicSong &other) const
Protected Attributes
Sort m_sortType
qint64 m_musicSize
qint64 m_musicAddTime
QString m_musicSizeStr
QString m_musicAddTimeStr
int m_musicPlayCount
QString m_musicName
QString m_musicPath
QString m_musicType
QString m_musicPlayTime
Detailed Description
The class of the music song info.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicsong.h.
Member Enumeration Documentation
enum MusicSong::Sort
Enumerator
SortByFileName
Sort by file name
SortBySinger
Sort by singer name
SortByFileSize
Sort by file size
SortByAddTime
Sort by add time
SortByPlayTime
Sort by play time
SortByPlayCount
Sort by play count
Definition at line 33 of file musicsong.h.
Constructor & Destructor Documentation
MusicSong::MusicSong ()
Object contsructor.
Definition at line 9 of file musicsong.cpp.
References m_musicAddTime, m_musicPlayCount, m_musicSize, m_sortType, and SortByFileName.
MusicSong::MusicSong (const QString & musicPath, const QString & musicName = QString()) explicit
Object contsructor by music path and name.
Definition at line 18 of file musicsong.cpp.
References m_musicAddTime, m_musicAddTimeStr, m_musicName, m_musicPath, m_musicSize, m_musicSizeStr, m_musicType, and MusicUtils::Number::sizeByte2Label().
MusicSong::MusicSong (const QString & musicPath, int playCount, const QString & musicName = QString())
Object contsructor by music path and name and playcout.
Definition at line 39 of file musicsong.cpp.
References m_musicPlayCount.
MusicSong::MusicSong (const QString & musicPath, const QString & type, int playCount, const QString & musicName = QString())
Object contsructor by music path and name and playcout and format.
Definition at line 45 of file musicsong.cpp.
References m_musicType.
MusicSong::MusicSong (const QString & musicPath, const QString & type, const QString & playTime, int playCount, const QString & musicName = QString())
Object contsructor by music path and name and playcout and format and time.
Definition at line 51 of file musicsong.cpp.
References m_musicPlayTime.
MusicSong::MusicSong (const QString & musicPath, int playCount, const QString & playTime, const QString & musicName)
Object contsructor by music path and name and playcout and time.
Definition at line 57 of file musicsong.cpp.
References m_musicPlayTime.
Member Function Documentation
qint64 MusicSong::getMusicAddTime () const inline
Get music add time.
Definition at line 134 of file musicsong.h.
QString MusicSong::getMusicAddTimeStr () const inline
Get music add time string.
Definition at line 85 of file musicsong.h.
Referenced by MusicCloudDownloadTableWidget::createItem(), MusicDownloadRecordTableWidget::createItem(), MusicCloudUploadTableWidget::createItem(), and MusicAbstractDownloadTableWidget::updateSongsFileName().
QString MusicSong::getMusicArtistBack () const
Get music song name.
Definition at line 68 of file musicsong.cpp.
References m_musicName, and MusicUtils::String::songName().
Referenced by MusicLrcDownloadBatchTableWidget::createAllItems(), and MusicSongsListItemInfoWidget::setMusicSongInformation().
QString MusicSong::getMusicArtistFront () const
Get music artist name.
Definition at line 63 of file musicsong.cpp.
References MusicUtils::String::artistName(), and m_musicName.
Referenced by MusicLrcDownloadBatchTableWidget::createAllItems(), operator<(), operator>(), and MusicSongsListItemInfoWidget::setMusicSongInformation().
QString MusicSong::getMusicName () const inline
Get music name.
Definition at line 102 of file musicsong.h.
Referenced by MusicLrcDownloadBatchTableWidget::createAllItems(), MusicSongCheckToolsDuplicateTableWidget::createAllItems(), MusicSongCheckToolsQualityTableWidget::createAllItems(), MusicCloudDownloadTableWidget::createItem(), MusicDownloadRecordTableWidget::createItem(), MusicCloudUploadTableWidget::createItem(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicApplication::musicDownloadContains(), and MusicSongsListItemInfoWidget::setMusicSongInformation().
QString MusicSong::getMusicPath () const inline
Get music path.
Definition at line 110 of file musicsong.h.
Referenced by MusicSongsSummariziedWidget::addSongToLovestListAt(), MusicPlayedListPopWidget::append(), MusicConnectTransferTableWidget::createAllItems(), MusicLrcDownloadBatchTableWidget::createAllItems(), MusicSongCheckToolsDuplicateTableWidget::createAllItems(), MusicSongCheckToolsQualityTableWidget::createAllItems(), MusicCloudUploadTableWidget::createItem(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicPlayedListPopWidget::insert(), MusicSongDlnaTransferWidget::musicPlay(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), MusicPlayedListPopWidget::remove(), MusicSongCheckToolsDuplicateThread::run(), MusicPlayedListPopWidget::setCurrentIndex(), MusicSongsSummariziedWidget::setDeleteItemAt(), and MusicSongsListItemInfoWidget::setMusicSongInformation().
int MusicSong::getMusicPlayCount () const inline
Get music play count.
Definition at line 150 of file musicsong.h.
Referenced by MusicSongsSummariziedWidget::setMusicPlayCount(), MusicSongsListItemInfoWidget::setMusicSongInformation(), and MusicSongsSummariziedWidget::setRecentMusicSongs().
QString MusicSong::getMusicPlayTime () const inline
Get music time.
Definition at line 126 of file musicsong.h.
Referenced by MusicConnectTransferTableWidget::createAllItems(), MusicSongCheckToolsDuplicateTableWidget::createAllItems(), MusicSongCheckToolsQualityTableWidget::createAllItems(), and MusicSongsListTableWidget::selectRow().
qint64 MusicSong::getMusicSize () const inline
Get music size.
Definition at line 142 of file musicsong.h.
QString MusicSong::getMusicSizeStr () const inline
Get music size string.
Definition at line 93 of file musicsong.h.
Referenced by MusicSongCheckToolsDuplicateTableWidget::createAllItems(), MusicSongCheckToolsQualityTableWidget::createAllItems(), MusicCloudDownloadTableWidget::createItem(), MusicDownloadRecordTableWidget::createItem(), MusicCloudUploadTableWidget::createItem(), and MusicSongsListItemInfoWidget::setMusicSongInformation().
Sort MusicSong::getMusicSort () const inline
Get music sort type.
Definition at line 158 of file musicsong.h.
QString MusicSong::getMusicType () const inline
Get music format.
Definition at line 118 of file musicsong.h.
Referenced by MusicApplication::musicDownloadContains(), and MusicSongsListItemInfoWidget::setMusicSongInformation().
bool MusicSong::operator< (const MusicSong & other) const
Operator < function.
Definition at line 78 of file musicsong.cpp.
References getMusicArtistFront(), m_musicAddTime, m_musicName, m_musicPlayCount, m_musicPlayTime, m_musicSize, m_sortType, SortByAddTime, SortByFileName, SortByFileSize, SortByPlayCount, SortByPlayTime, and SortBySinger.
bool MusicSong::operator== (const MusicSong & other) const
Operator == function.
Definition at line 73 of file musicsong.cpp.
References m_musicPath.
bool MusicSong::operator> (const MusicSong & other) const
Operator > function.
Definition at line 93 of file musicsong.cpp.
References getMusicArtistFront(), m_musicAddTime, m_musicName, m_musicPlayCount, m_musicPlayTime, m_musicSize, m_sortType, SortByAddTime, SortByFileName, SortByFileSize, SortByPlayCount, SortByPlayTime, and SortBySinger.
void MusicSong::setMusicAddTime (const qint64 t) inline
Set music add time.
Definition at line 130 of file musicsong.h.
void MusicSong::setMusicAddTimeStr (const QString & t) inline
Set music add time string.
Definition at line 81 of file musicsong.h.
Referenced by MusicAbstractDownloadTableWidget::createDownloadItem(), MusicDownloadRecordConfigManager::readDownloadData(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicSong::setMusicName (const QString & n) inline
Set music name.
Definition at line 98 of file musicsong.h.
Referenced by MusicAbstractDownloadTableWidget::createDownloadItem(), MusicDownloadRecordConfigManager::readDownloadData(), MusicCSVConfigManager::readPlaylistData(), MusicDownloadBatchTableItem::startToDownloadMusic(), MusicDownloadWidget::startToDownloadMusic(), and MusicCloudUploadTableWidget::uploadFileError().
void MusicSong::setMusicPath (const QString & p) inline
Set music path.
Definition at line 106 of file musicsong.h.
Referenced by MusicAbstractDownloadTableWidget::createDownloadItem(), MusicDownloadRecordConfigManager::readDownloadData(), MusicCSVConfigManager::readPlaylistData(), MusicDownloadBatchTableItem::startToDownloadMusic(), MusicDownloadWidget::startToDownloadMusic(), and MusicCloudUploadTableWidget::uploadFileError().
void MusicSong::setMusicPlayCount (const int c) inline
Set music play count.
Definition at line 146 of file musicsong.h.
Referenced by MusicSongsSummariziedWidget::setMusicPlayCount(), and MusicSongsSummariziedWidget::setRecentMusicSongs().
void MusicSong::setMusicPlayTime (const QString & t) inline
Set music time.
Definition at line 122 of file musicsong.h.
Referenced by MusicCSVConfigManager::readPlaylistData(), MusicTXTConfigManager::readPlaylistData(), and MusicSongsListTableWidget::selectRow().
void MusicSong::setMusicSize (const qint64 s) inline
Set music size.
Definition at line 138 of file musicsong.h.
void MusicSong::setMusicSizeStr (const QString & s) inline
Set music size string.
Definition at line 89 of file musicsong.h.
Referenced by MusicAbstractDownloadTableWidget::createDownloadItem(), MusicDownloadRecordConfigManager::readDownloadData(), MusicDownloadBatchTableItem::startToDownloadMusic(), MusicDownloadWidget::startToDownloadMusic(), and MusicCloudUploadTableWidget::uploadFileError().
void MusicSong::setMusicSort (const Sort s) inline
Set music sort type.
Definition at line 154 of file musicsong.h.
void MusicSong::setMusicType (const QString & t) inline
Set music format.
Definition at line 114 of file musicsong.h.
Referenced by MusicObject::generateMusicSongList().
Member Data Documentation
qint64 MusicSong::m_musicAddTime protected
Definition at line 175 of file musicsong.h.
Referenced by MusicSong(), operator<(), and operator>().
QString MusicSong::m_musicAddTimeStr protected
Definition at line 176 of file musicsong.h.
Referenced by MusicSong().
QString MusicSong::m_musicName protected
Definition at line 178 of file musicsong.h.
Referenced by getMusicArtistBack(), getMusicArtistFront(), MusicSong(), operator<(), and operator>().
QString MusicSong::m_musicPath protected
Definition at line 178 of file musicsong.h.
Referenced by MusicSong(), and operator==().
int MusicSong::m_musicPlayCount protected
Definition at line 177 of file musicsong.h.
Referenced by MusicSong(), operator<(), and operator>().
QString MusicSong::m_musicPlayTime protected
Definition at line 178 of file musicsong.h.
Referenced by MusicSong(), operator<(), and operator>().
qint64 MusicSong::m_musicSize protected
Definition at line 175 of file musicsong.h.
Referenced by MusicSong(), operator<(), and operator>().
QString MusicSong::m_musicSizeStr protected
Definition at line 176 of file musicsong.h.
Referenced by MusicSong().
QString MusicSong::m_musicType protected
Definition at line 178 of file musicsong.h.
Referenced by MusicSong().
Sort MusicSong::m_sortType protected
Definition at line 174 of file musicsong.h.
Referenced by MusicSong(), operator<(), and operator>().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicsong.h
TTKModule/TTKCore/musicCoreKits/musicsong.cpp