TTKMusicplayer: MusicLocalPeer Class Reference
MusicLocalPeer Class Reference
The class of the music local peer.
#include <musiclocalpeer.h>
Signals
void messageReceived (const QString &message)
Public Member Functions
MusicLocalPeer (QObject *parent=0, const QString &appId=QString())
bool isClient ()
bool sendMessage (const QString &message, int timeout)
QString applicationId () const
Protected Slots
void receiveConnection ()
Detailed Description
The class of the music local peer.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclocalpeer.h.
Constructor & Destructor Documentation
MusicLocalPeer::MusicLocalPeer (QObject * parent = 0, const QString & appId = QString()) explicit
Object contsructor.
Definition at line 61 of file musiclocalpeer.cpp.
References MUSIC_D, and MUSIC_INIT_PRIVATE.
Member Function Documentation
QString MusicLocalPeer::applicationId () const
Get current server id.
Definition at line 187 of file musiclocalpeer.cpp.
References MUSIC_D.
bool MusicLocalPeer::isClient ()
Current client is running or not.
Definition at line 108 of file musiclocalpeer.cpp.
References MUSIC_D, receiveConnection(), and MusicLockedPrivate::MusicLockedFile::WriteLock.
Referenced by sendMessage().
void MusicLocalPeer::messageReceived (const QString & message) signal
Emit when the current message received.
Referenced by receiveConnection().
void MusicLocalPeer::receiveConnection () protected slot
Current message received.
Definition at line 193 of file musiclocalpeer.cpp.
References messageReceived(), and MUSIC_D.
Referenced by isClient().
bool MusicLocalPeer::sendMessage (const QString & message, int timeout)
Send current message when the client in.
Definition at line 139 of file musiclocalpeer.cpp.
References isClient(), and MUSIC_D.
The documentation for this class was generated from the following files:
TTKRun/TTKApp/musiclocalpeer.h
TTKRun/TTKApp/musiclocalpeer.cpp