TTKMusicplayer: MusicLRCManagerForInline Class Reference
MusicLRCManagerForInline Class Reference
The class of the inline lrc manager.
#include <musiclrcmanagerforinline.h>
Public Member Functions
MusicLRCManagerForInline (QWidget *parent=0)
void setLrcPerWidth (int width)
void setFontSize (int size)
void setTransparent (int tran)
void setCenterOnLrc (bool status)
Public Member Functions inherited from MusicLRCManager
MusicLRCManager (QWidget *parent=0)
virtual ~MusicLRCManager ()
void startTimerClock ()
void startLrcMask (qint64 intervaltime)
void stopLrcMask ()
void setLinearGradientColor (const MusicLRCColor &color)
void setFontFamily (int index)
void setFontType (int type)
void setFontTransparent (int t)
void setSpeedLevel (int l)
void setSelfGeometry (const QPoint &point)
void setSelfGeometry (int x, int y)
int x () const
int y () const
void setX (int x)
void setY (int y)
void reset ()
void setLrcFontSize (int size)
int getFirstFontSize () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicLRCManager
static QString getClassName ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
Protected Attributes
int m_gradientFontSize
int m_gradientTransparent
bool m_centerOnLrc
Protected Attributes inherited from MusicLRCManager
QLinearGradient m_linearGradient
QLinearGradient m_maskLinearGradient
QFont m_font
QTimer * m_timer
qreal m_lrcMaskWidth
qreal m_lrcMaskWidthInterval
qreal m_intervalCount
int m_lrcPerWidth
int m_transparent
int m_speedLevel
QPoint m_geometry
Additional Inherited Members
Public Slots inherited from MusicLRCManager
void setUpdateMask ()
void setText (const QString &str)
Detailed Description
The class of the inline lrc manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 19 of file musiclrcmanagerforinline.h.
Constructor & Destructor Documentation
MusicLRCManagerForInline::MusicLRCManagerForInline (QWidget * parent = 0) explicit
Definition at line 3 of file musiclrcmanagerforinline.cpp.
References LRC_PER_WIDTH, m_centerOnLrc, MusicLRCManager::m_font, MusicLRCManager::m_geometry, m_gradientFontSize, m_gradientTransparent, MusicLRCManager::m_lrcPerWidth, and MusicLRCManager::m_speedLevel.
Member Function Documentation
QString MusicLRCManagerForInline::getClassName () static
Object contsructor.
Definition at line 16 of file musiclrcmanagerforinline.cpp.
void MusicLRCManagerForInline::paintEvent (QPaintEvent * event) override protected virtual
Set center current lrc on or not.
Definition at line 21 of file musiclrcmanagerforinline.cpp.
References m_centerOnLrc, MusicLRCManager::m_font, MusicLRCManager::m_geometry, m_gradientFontSize, m_gradientTransparent, MusicLRCManager::m_intervalCount, MusicLRCManager::m_linearGradient, MusicLRCManager::m_lrcMaskWidth, MusicLRCManager::m_lrcMaskWidthInterval, MusicLRCManager::m_lrcPerWidth, and MusicLRCManager::m_maskLinearGradient.
void MusicLRCManagerForInline::setCenterOnLrc (bool status) inline
Set adjust transparent by value.
Definition at line 44 of file musiclrcmanagerforinline.h.
Referenced by MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicSoundKMicroWidget::setItemStyleSheet(), MusicLrcContainerForInline::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
void MusicLRCManagerForInline::setFontSize (int size) inline
Set lrc per width.
Definition at line 36 of file musiclrcmanagerforinline.h.
Referenced by MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicSoundKMicroWidget::setItemStyleSheet(), MusicLrcContainerForInline::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
void MusicLRCManagerForInline::setLrcPerWidth (int width) inline
Get class object name.
Definition at line 32 of file musiclrcmanagerforinline.h.
References LRC_PER_WIDTH.
Referenced by MusicLrcMakerWidget::createThirdWidget(), MusicSoundKMicroWidget::MusicSoundKMicroWidget(), and MusicLrcContainerForWallpaper::setSettingParameter().
void MusicLRCManagerForInline::setTransparent (int tran) inline
Set adjust font size.
Definition at line 40 of file musiclrcmanagerforinline.h.
Referenced by MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicSoundKMicroWidget::setItemStyleSheet(), MusicLrcContainerForInline::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
Member Data Documentation
bool MusicLRCManagerForInline::m_centerOnLrc protected
Definition at line 57 of file musiclrcmanagerforinline.h.
Referenced by MusicLRCManagerForInline(), and paintEvent().
int MusicLRCManagerForInline::m_gradientFontSize protected
Override the widget event.
Definition at line 55 of file musiclrcmanagerforinline.h.
Referenced by MusicLRCManagerForInline(), and paintEvent().
int MusicLRCManagerForInline::m_gradientTransparent protected
Definition at line 56 of file musiclrcmanagerforinline.h.
Referenced by MusicLRCManagerForInline(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcmanagerforinline.h
TTKModule/TTKWidget/musicLrcKits/musiclrcmanagerforinline.cpp