TTKMusicPlayer: MusicSourceUpdateRequest Class Reference
MusicSourceUpdateRequest Class Reference
The class of the source data query update request.
#include <musicsourceupdaterequest.h>
Public Slots
void downLoadFinished (const QByteArray &bytes)
Signals
void downLoadDataChanged (const QString &bytes)
Public Member Functions
MusicSourceUpdateRequest (QObject *parent=nullptr)
void startToRequest ()
QString version () const
QString description () const
bool isLastedVersion () const
Private Attributes
QVariantMap m_rawData
Detailed Description
The class of the source data query update request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicsourceupdaterequest.h.
Constructor & Destructor Documentation
MusicSourceUpdateRequest::MusicSourceUpdateRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musicsourceupdaterequest.cpp.
Member Function Documentation
QString MusicSourceUpdateRequest::description () const
Get lasted version description.
Definition at line 26 of file musicsourceupdaterequest.cpp.
References m_rawData.
Referenced by MusicSourceUpdateWidget::downLoadFinished().
void MusicSourceUpdateRequest::downLoadDataChanged (const QString & bytes) signal
Send download data from net.
Referenced by downLoadFinished().
void MusicSourceUpdateRequest::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 44 of file musicsourceupdaterequest.cpp.
References downLoadDataChanged(), m_rawData, QJson::Parser::parse(), and TTK_ERROR_STREAM.
Referenced by startToRequest().
bool MusicSourceUpdateRequest::isLastedVersion () const
Is lasted version.
Definition at line 31 of file musicsourceupdaterequest.cpp.
References TTK_VERSION_STR, and version().
Referenced by MusicApplicationModule::isLastedVersion().
void MusicSourceUpdateRequest::startToRequest ()
Start to download update data.
Definition at line 14 of file musicsourceupdaterequest.cpp.
References downLoadFinished(), QSyncUtils::makeDataBucketUrl(), OS_VERSION_URL, and MusicDataSourceRequest::startToRequest().
Referenced by MusicApplicationModule::loadNetWorkSetting(), MusicSourceUpdateNotifyWidget::MusicSourceUpdateNotifyWidget(), and MusicSourceUpdateWidget::start().
QString MusicSourceUpdateRequest::version () const
Get lasted version.
Definition at line 21 of file musicsourceupdaterequest.cpp.
References m_rawData.
Referenced by MusicSourceUpdateNotifyWidget::downLoadFinished(), MusicSourceUpdateWidget::downLoadFinished(), and isLastedVersion().
Member Data Documentation
QVariantMap MusicSourceUpdateRequest::m_rawData private
Definition at line 71 of file musicsourceupdaterequest.h.
Referenced by description(), downLoadFinished(), and version().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicsourceupdaterequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicsourceupdaterequest.cpp