TTKMusicplayer: QNUtils Class Reference
QNUtils Class Reference
The namespace of the qiniu utils.
#include <qnutils.h>
Static Public Member Functions
static QString urlSafeBase64Encode (const QByteArray &data)
static QByteArray urlSafeBase64Decode (const QString &data)
static QByteArray sha1 (const QByteArray &data)
static QByteArray hmacSha1 (const QByteArray &data, const QByteArray &secretKey)
static QString escapeKey (const QString &key)
static bool isParamValid (const QString &param)
static uint expireInSeconds (const uint seconds)
static uint crc32 (const QByteArray &data)
static QString randomFileName ()
static QString urlQuery (const QString &url)
Static Public Attributes
static const char KEY_ESCAPE_RESERVE_BYTES [] = {'?'}
static const char KEY_ESCAPE_UNRESERVE_BYTES []
Detailed Description
The namespace of the qiniu utils.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 28 of file qnutils.h.
Member Function Documentation
uint QNUtils::crc32 (const QByteArray & data) static
Crc32 Encode.
Definition at line 94 of file qnutils.cpp.
References int().
QString QNUtils::escapeKey (const QString & key) static
Get escape key.
Definition at line 71 of file qnutils.cpp.
References KEY_ESCAPE_RESERVE_BYTES, and KEY_ESCAPE_UNRESERVE_BYTES.
uint QNUtils::expireInSeconds (const uint seconds) static
Get expire in seconds.
now.setOffsetFromUtc(3600*8);
Definition at line 83 of file qnutils.cpp.
Referenced by QNSimpleUploadData::getDownloadUrl(), QNPutPolicy::makeDownloadToken(), and QNPutPolicy::makeUploadToken().
QByteArray QNUtils::hmacSha1 (const QByteArray & data, const QByteArray & secretKey) static
Get hmac in sha1.
Definition at line 43 of file qnutils.cpp.
Referenced by QNMac::sign(), QNMac::signRequest(), QNMac::signWithData(), and QNMac::signWithData2().
bool QNUtils::isParamValid (const QString & param) static
Current parameter is valid or not.
Definition at line 77 of file qnutils.cpp.
Referenced by QNPutPolicyPrivate::toJSON().
QString QNUtils::randomFileName () static
Get random file name.
now.setOffsetFromUtc(3600*8);
Definition at line 118 of file qnutils.cpp.
Referenced by QNIOHelper::createPutDataMultiPart().
QByteArray QNUtils::sha1 (const QByteArray & data) static
Sha1 Encode.
Definition at line 35 of file qnutils.cpp.
QString QNUtils::urlQuery (const QString & url) static
Get url query string.
Definition at line 127 of file qnutils.cpp.
Referenced by QNMac::signRequest().
QByteArray QNUtils::urlSafeBase64Decode (const QString & data) static
Url safe base64 decode.
Definition at line 26 of file qnutils.cpp.
QString QNUtils::urlSafeBase64Encode (const QByteArray & data) static
Url safe base64 encode.
Definition at line 13 of file qnutils.cpp.
Referenced by QNIOHelper::deleteRequest(), QNMac::sign(), QNMac::signRequest(), QNMac::signWithData(), and QNMac::signWithData2().
Member Data Documentation
const char QNUtils::KEY_ESCAPE_RESERVE_BYTES = {'?'} static
Definition at line 72 of file qnutils.h.
Referenced by escapeKey().
const char QNUtils::KEY_ESCAPE_UNRESERVE_BYTES static
Initial value:
= {'!', '*', '\'', '(', ')', ';', ':', '@',
                                                    '&', '=', '+', '$', ',', '/', '#', '[', ']' }
Definition at line 73 of file qnutils.h.
Referenced by escapeKey().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnutils.h
TTKThirdParty/TTKExtras/qiniu/qnutils.cpp