TTKMusicPlayer: MusicItemRecommendQueryWidget Class Reference
MusicItemRecommendQueryWidget Class Reference
The class of the item recommend query widget.
#include <musicmainrecommendwidget.h>
Public Slots
void createResultItem (const MusicResultDataItem &item)
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicItemRecommendQueryWidget (RecommendModule module, QWidget *parent=nullptr)
~MusicItemRecommendQueryWidget ()
void setQueryInput (MusicAbstractQueryRequest *query)
void resizeGeometry ()
Private Attributes
RecommendModule m_module
QGridLayout * m_gridLayout
QWidgetList m_resizeWidgets
MusicAbstractQueryRequest * m_networkRequest
Detailed Description
The class of the item recommend query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 105 of file musicmainrecommendwidget.h.
Constructor & Destructor Documentation
MusicItemRecommendQueryWidget::MusicItemRecommendQueryWidget (RecommendModule module, QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 232 of file musicmainrecommendwidget.cpp.
References m_gridLayout.
MusicItemRecommendQueryWidget::~MusicItemRecommendQueryWidget ()
Object destructor.
Definition at line 243 of file musicmainrecommendwidget.cpp.
References m_gridLayout, and m_networkRequest.
Member Function Documentation
void MusicItemRecommendQueryWidget::createResultItem (const MusicResultDataItem & item) slot
Create the current item info.
Definition at line 262 of file musicmainrecommendwidget.cpp.
References Album, Artist, currentItemClicked(), MusicSquareQueryItemWidget::LINE_SPACING_SIZE, m_gridLayout, m_module, m_networkRequest, m_resizeWidgets, MusicPageQueryRequest::pageSize(), QUERY_WIDGET_WIDTH, MusicSquareQueryItemWidget::setResultDataItem(), MusicSquareQueryItemWidget::setShowCount(), MusicSquareQueryItemWidget::setShowTime(), and MusicSquareQueryItemWidget::setValueLabel().
Referenced by setQueryInput().
void MusicItemRecommendQueryWidget::currentItemClicked (const MusicResultDataItem & item) slot
Current playlist item clicked.
Definition at line 301 of file musicmainrecommendwidget.cpp.
References Album, Artist, MusicRightAreaWidget::instance(), MusicResultDataItem::m_id, m_module, Playlist, PlaylistHQ, MusicRightAreaWidget::showAlbumFound(), MusicRightAreaWidget::showArtistFound(), and MusicRightAreaWidget::showPlaylistFound().
Referenced by createResultItem().
void MusicItemRecommendQueryWidget::resizeGeometry ()
Resize widget bound by resize called.
Definition at line 313 of file musicmainrecommendwidget.cpp.
References Album, MusicSquareQueryItemWidget::LINE_SPACING_SIZE, m_gridLayout, m_module, m_networkRequest, m_resizeWidgets, MusicPageQueryRequest::pageSize(), qAsConst, QUERY_WIDGET_WIDTH, and TTK_RN_MAX.
Referenced by MusicMainRecommendWidget::resizeGeometry().
void MusicItemRecommendQueryWidget::setQueryInput (MusicAbstractQueryRequest * query)
Set network query input.
Definition at line 249 of file musicmainrecommendwidget.cpp.
References Album, Artist, createResultItem(), m_module, m_networkRequest, Playlist, and PlaylistHQ.
Referenced by MusicMainRecommendWidget::createContainerMiddleBottomWidget(), MusicMainRecommendWidget::createContainerMiddleTopWidget(), MusicMainRecommendWidget::createContainerMiddleWidget(), and MusicMainRecommendWidget::createContainerTopWidget().
Member Data Documentation
QGridLayout* MusicItemRecommendQueryWidget::m_gridLayout private
Definition at line 139 of file musicmainrecommendwidget.h.
Referenced by createResultItem(), MusicItemRecommendQueryWidget(), resizeGeometry(), and ~MusicItemRecommendQueryWidget().
RecommendModule MusicItemRecommendQueryWidget::m_module private
Definition at line 138 of file musicmainrecommendwidget.h.
Referenced by createResultItem(), currentItemClicked(), resizeGeometry(), and setQueryInput().
MusicAbstractQueryRequest* MusicItemRecommendQueryWidget::m_networkRequest private
Definition at line 141 of file musicmainrecommendwidget.h.
Referenced by createResultItem(), resizeGeometry(), setQueryInput(), and ~MusicItemRecommendQueryWidget().
QWidgetList MusicItemRecommendQueryWidget::m_resizeWidgets private
Definition at line 140 of file musicmainrecommendwidget.h.
Referenced by createResultItem(), and resizeGeometry().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.cpp