TTKMusicplayer: MusicDownLoadQueryXMThread Class Reference
MusicDownLoadQueryXMThread Class Reference
The class to xiami query download data from net.
#include <musicdownloadqueryxmthread.h>
Public Slots
virtual void downLoadFinished () override
void singleDownLoadFinished ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadQueryXMThread (QObject *parent=0)
QJson import.
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
const MusicObject::MusicSongInformations & getMusicSongInfos () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItems (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
QString mapQueryServerString () const
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadXMInterface
void makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariant &key, const QString &quality, bool all)
void readFromMusicSongLrc (MusicObject::MusicSongInformation *info)
Detailed Description
The class to xiami query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadqueryxmthread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryXMThread::MusicDownLoadQueryXMThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 6 of file musicdownloadqueryxmthread.cpp.
References MusicDownLoadQueryThreadAbstract::m_queryServer.
Member Function Documentation
void MusicDownLoadQueryXMThread::downLoadFinished () override virtual slot
Download data from net finished.
Clear origin items
Empty the last search to songsInfo
Get all the data obtained by request
Definition at line 73 of file musicdownloadqueryxmthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::Init, MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_queryAllRecords, MusicDownLoadQueryThreadAbstract::m_querySimplify, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicDownLoadXMInterface::readFromMusicSongAttribute(), and MusicDownLoadXMInterface::readFromMusicSongLrc().
Referenced by startToSearch().
QString MusicDownLoadQueryXMThread::getClassName () static
Get class object name.
Definition at line 12 of file musicdownloadqueryxmthread.cpp.
Referenced by downLoadFinished(), singleDownLoadFinished(), startToSearch(), and startToSingleSearch().
void MusicDownLoadQueryXMThread::singleDownLoadFinished () slot
Download single data from net finished.
Clear origin items
Empty the last search to songsInfo
Get all the data obtained by request
Definition at line 152 of file musicdownloadqueryxmthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::Init, MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_queryAllRecords, MusicDownLoadQueryThreadAbstract::m_searchQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MObject_cast, MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicDownLoadXMInterface::readFromMusicSongAttribute(), and MusicDownLoadXMInterface::readFromMusicSongLrc().
Referenced by startToSingleSearch().
void MusicDownLoadQueryXMThread::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicDownLoadQueryThreadAbstract.
Definition at line 17 of file musicdownloadqueryxmthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicNetworkAbstract::Init, MusicDownLoadQueryThreadAbstract::m_currentType, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicNetworkAbstract::m_stateCode, MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), XM_SONG_DATA_URL, and XM_SONG_URL.
Referenced by MusicXMSongCommentsThread::startToSearch().
void MusicDownLoadQueryXMThread::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicDownLoadQueryThreadAbstract.
Definition at line 46 of file musicdownloadqueryxmthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_stateCode, MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), singleDownLoadFinished(), XM_SONG_DATA_INFO_URL, and XM_SONG_INFO_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/xm/musicdownloadqueryxmthread.h
TTKModule/TTKCore/musicNetworkKits/xm/musicdownloadqueryxmthread.cpp