TTKMusicplayer: MusicUtils::QMMP Namespace Reference
MusicUtils::QMMP Namespace Reference
Functions
TTK_MODULE_EXPORT QString pluginPath (const QString &module, const QString &format)
TTK_MODULE_EXPORT void updateMidConfigFile ()
TTK_MODULE_EXPORT void enabledVisualPlugin (const QString &name, bool enable)
TTK_MODULE_EXPORT void enabledEffectPlugin (bool enable)
TTK_MODULE_EXPORT void enabledEffectPlugin (const QString &name, bool enable)
TTK_MODULE_EXPORT QStringList effectPlugins ()
TTK_MODULE_EXPORT bool effectHasSetting (const QString &name)
TTK_MODULE_EXPORT void showEffectSetting (const QString &name, QWidget *parent)
TTK_MODULE_EXPORT void updateRippleSpectrumConfigFile ()
Function Documentation
bool MusicUtils::QMMP::effectHasSetting (const QString & name)
Check effect has setting.
Definition at line 92 of file musicqmmputils.cpp.
References Effect::factories(), and name.
Referenced by MusicSoundEffectsItemWidget::setPluginEnabled().
QStringList MusicUtils::QMMP::effectPlugins ()
Check effect is valid.
Definition at line 79 of file musicqmmputils.cpp.
References Effect::factories().
Referenced by MusicSoundEffectsWidget::readSoundEffect().
void MusicUtils::QMMP::enabledEffectPlugin (bool enable)
Enable effect module control.
Definition at line 59 of file musicqmmputils.cpp.
References Effect::factories(), and Effect::setEnabled().
Referenced by MusicEnhancedPopWidget::setEnhancedMusicConfig(), and MusicSoundEffectsItemWidget::soundEffectChanged().
void MusicUtils::QMMP::enabledEffectPlugin (const QString & name, bool enable)
Enable effect module control.
Definition at line 67 of file musicqmmputils.cpp.
References Effect::factories(), name, and Effect::setEnabled().
void MusicUtils::QMMP::enabledVisualPlugin (const QString & name, bool enable)
Enable visual module control.
Definition at line 47 of file musicqmmputils.cpp.
References Visual::factories(), name, and Visual::setEnabled().
Referenced by MusicSpectrumWidget::createModuleWidget(), MusicSpectrumWidget::createSpectrumWidget(), MusicRemoteWidgetForRipple::createVisualWidget(), MusicSpectrumWidget::fullscreenByUser(), MusicRippleSpecturmModule::removeSpectrum(), MusicRemoteWidgetForRipple::removeVisualWidget(), MusicRippleSpecturmModule::show(), and MusicSpectrumWidget::~MusicSpectrumWidget().
QString MusicUtils::QMMP::pluginPath (const QString & module, const QString & format)
Get qmmp plugin dir path.
Definition at line 12 of file musicqmmputils.cpp.
References MusicObject::getAppDir().
Referenced by MusicSpectrumWidget::createLightWidget(), MusicSongMeta::getDecoder(), and MusicReplayGainWidget::initialize().
void MusicUtils::QMMP::showEffectSetting (const QString & name, QWidget * parent)
Show effect setting control.
Definition at line 104 of file musicqmmputils.cpp.
References Effect::factories(), and name.
Referenced by MusicSoundEffectsItemWidget::soundEffectValueChanged().
void MusicUtils::QMMP::updateMidConfigFile ()
Update mid config file transfer.
Definition at line 23 of file musicqmmputils.cpp.
References Qmmp::configFile(), and MAKE_CONFIG_DIR_FULL.
Referenced by MusicRunTimeManager::run().
void MusicUtils::QMMP::updateRippleSpectrumConfigFile ()
Update ripple spectrum config file transfer.
Definition at line 116 of file musicqmmputils.cpp.
References Qmmp::configFile(), G_SETTING_PTR, and MusicSettingManager::RippleSpectrumColor.
Referenced by MusicRippleSpecturmModule::update().