TTKMusicPlayer: TTKCommon/TTKLibrary/ttkplatformsystem.cpp File Reference
ttkplatformsystem.cpp File Reference
#include "ttkplatformsystem.h"
#include <QSize>
#include <QFile>
#include <QRegExp>
Functions
static QSize generateDPIValue ()
Variables
static constexpr int DEFAULT_DPI = 96
Function Documentation
static QSize generateDPIValue () static
Definition at line 17 of file ttkplatformsystem.cpp.
References DEFAULT_DPI.
Referenced by TTKPlatformSystem::logicalDotsPerInch(), TTKPlatformSystem::logicalDotsPerInchX(), and TTKPlatformSystem::logicalDotsPerInchY().
Variable Documentation
constexpr int DEFAULT_DPI = 96 static
Definition at line 15 of file ttkplatformsystem.cpp.
Referenced by generateDPIValue().