TTKMusicPlayer: TTKService/musicservicemain.cpp File Reference
musicservicemain.cpp File Reference
#include "musicapplication.h"
#include "musicruntimemanager.h"
#include "musicconfigobject.h"
#include "musicplatformmanager.h"
#include "ttkglobalhelper.h"
#include "ttkdumper.h"
#include <QTranslator>
#include <QApplication>
Macros
#define TTK_DEBUG
Functions
static void cleanAppicationCache ()
static void loadAppScaledFactor (int argc, char *argv[])
int main (int argc, char *argv[])
Macro Definition Documentation
#define TTK_DEBUG
Definition at line 15 of file musicservicemain.cpp.
Function Documentation
static void cleanAppicationCache () static
clean thirdparty process
Definition at line 17 of file musicservicemain.cpp.
References TTKObject::killProcessByName(), MAKE_GAIN_NAME, MAKE_PLAYER_NAME, MAKE_TRANSFORM_NAME, MUSIC_COLOR_FILE, MUSIC_IMAGE_FILE, MUSIC_RECORD_DATA_FILE, and MUSIC_RECORD_FILE.
Referenced by main().
static void loadAppScaledFactor (int argc, char * argv[]) static
Definition at line 32 of file musicservicemain.cpp.
References MusicPlatformManager::logicalDotsPerInch().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 55 of file musicservicemain.cpp.
References APP_COME_NAME, APP_NAME, cleanAppicationCache(), MusicRunTimeManager::configVersionCheck(), loadAppScaledFactor(), MusicApplication::musicImportSongsPathOutside(), MusicConfigObject::reset(), MusicRunTimeManager::run(), TTKDumper::run(), MusicMPRISPlayer::run(), TTKObject::setApplicationFont(), MusicRunTimeManager::translator(), TTK_ERROR_STREAM, and MusicConfigObject::valid().