TTKMusicplayer: MusicBackgroundPopWidget Class Reference
MusicBackgroundPopWidget Class Reference
The class of the background popup widget.
#include <musicbackgroundpopwidget.h>
Signals
void valueChanged (int value)
void sliderStateChanged (bool state)
Public Member Functions
MusicBackgroundPopWidget (QWidget *parent=nullptr)
~MusicBackgroundPopWidget ()
void setValue (int value)
int value () const
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initialize ()
Protected Attributes
MusicClickedSlider * m_slider
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Private Slots
void sliderPressed ()
void sliderReleased ()
Additional Inherited Members
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Detailed Description
The class of the background popup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicbackgroundpopwidget.h.
Constructor & Destructor Documentation
MusicBackgroundPopWidget::MusicBackgroundPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicbackgroundpopwidget.cpp.
References initialize().
MusicBackgroundPopWidget::~MusicBackgroundPopWidget ()
Definition at line 11 of file musicbackgroundpopwidget.cpp.
References m_slider.
Member Function Documentation
void MusicBackgroundPopWidget::initialize () protected
Create all widget in layout.
Definition at line 36 of file musicbackgroundpopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, m_slider, MusicUIObject::MQSSColorStyle02, MusicUIObject::MQSSMenuStyle02, MusicUIObject::MQSSSliderStyle03, sliderPressed(), sliderReleased(), and valueChanged().
Referenced by MusicBackgroundPopWidget().
void MusicBackgroundPopWidget::setValue (int value)
Set slider value.
Definition at line 16 of file musicbackgroundpopwidget.cpp.
References m_slider.
void MusicBackgroundPopWidget::sliderPressed () private slot
Current slider pressed changed.
Definition at line 26 of file musicbackgroundpopwidget.cpp.
References sliderStateChanged().
Referenced by initialize().
void MusicBackgroundPopWidget::sliderReleased () private slot
Current slider released changed.
Definition at line 31 of file musicbackgroundpopwidget.cpp.
References sliderStateChanged().
Referenced by initialize().
void MusicBackgroundPopWidget::sliderStateChanged (bool state) signal
Current slider state changed.
Referenced by sliderPressed(), and sliderReleased().
int MusicBackgroundPopWidget::value () const
Get slider value.
Definition at line 21 of file musicbackgroundpopwidget.cpp.
References m_slider.
void MusicBackgroundPopWidget::valueChanged (int value) signal
Current play transparent changed.
Referenced by initialize().
Member Data Documentation
MusicClickedSlider* MusicBackgroundPopWidget::m_slider protected
Definition at line 75 of file musicbackgroundpopwidget.h.
Referenced by initialize(), setValue(), value(), and ~MusicBackgroundPopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundpopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundpopwidget.cpp