TTKMusicplayer: MusicUtils::Algorithm Namespace Reference
MusicUtils::Algorithm Namespace Reference
Functions
MUSIC_UTILS_EXPORT QByteArray md5 (const QByteArray &data)
MUSIC_UTILS_EXPORT QByteArray sha1 (const QByteArray &data)
MUSIC_UTILS_EXPORT QByteArray hmacSha1 (const QByteArray &data, const QByteArray &key)
MUSIC_UTILS_EXPORT QString mdII (const QString &data, bool encode)
MUSIC_UTILS_EXPORT QString mdII (const QString &data, const QString &key, bool encode)
Function Documentation
QByteArray MusicUtils::Algorithm::hmacSha1 (const QByteArray & data, const QByteArray & key)
Encode the data into sha1.
Definition at line 16 of file musicalgorithmutils.cpp.
References key, and sha1().
Referenced by MusicLicenseCore::getCharacteristicStringNormal(), MusicLicenseCore::splitString(), and MusicIdentifySongsThread::startToDownload().
QByteArray MusicUtils::Algorithm::md5 (const QByteArray & data)
Get md5 algorithm.
Definition at line 6 of file musicalgorithmutils.cpp.
Referenced by MusicDownLoadWYInterface::encryptedId(), MusicDownLoadMGInterface::makeTokenQueryUrl(), MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicUserRecordWidget::saveFileButtonClickedS(), MusicBDSongCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), and MusicUserModel::userPasswordEncryption().
QString MusicUtils::Algorithm::mdII (const QString & data, bool encode)
Get mdII(greedysky) algorithm.
Definition at line 42 of file musicalgorithmutils.cpp.
References ALG_URL_KEY, MusicCryptographicHash::decrypt(), and MusicCryptographicHash::encrypt().
Referenced by MusicSongsSummariziedWidget::addNetMusicSongToList(), MusicSongSearchOnlineTableWidget::addSearchMusicToPlayList(), MusicSongSharingWidget::confirmButtonClicked(), ToolsUrl::decodeClicked(), MusicSongSharingWidget::downLoadDataChanged(), MusicDownloadBackgroundBingThread::downLoadDataFinished(), MusicQueryFoundTableWidget::downloadDataFrom(), MusicCloudSharedSongTableWidget::downloadFileToServer(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicRadioSongsThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicQQBackgroundThread::downLoadUrl(), ToolsUrl::encodeClicked(), MusicKWArtistSimilarThread::getArtistIdName(), MusicMGArtistSimilarThread::getArtistInfo(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryWSArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicCloudSharedSongTableWidget::getKey(), MusicIdentifySongsThread::getKey(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryWSPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQQInterface::getMusicKey(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryMGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), MusicWSDiscoverListThread::getUpdateTime(), MusicDownLoadQueryWSToplistThread::getUpdateTime(), MusicDownLoadWYInterface::makeTokenQueryQequest(), MusicDownLoadMGInterface::makeTokenQueryUrl(), MusicDownLoadBDInterface::makeTokenQueryUrl(), MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicApplicationObject::musicBugReportView(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicNetworkSpeedTestWidget::networkTestStart(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadKWInterface::readFromMusicLLAttribute(), MusicDownLoadMGInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAlbumInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadWSInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadMGInterface::readFromMusicSongAttribute(), MusicDownLoadKWInterface::readFromMusicSongAttribute(), MusicDownLoadQQInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttributeNew(), MusicDownLoadKWInterface::readFromMusicSongAttributePlus(), MusicDownLoadQQInterface::readFromMusicSongAttributePlus(), MusicDownLoadXMInterface::readFromMusicSongLrc(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), MusicDownLoadKWInterface::readFromMusicSongPic(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryQQAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryKWAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicQQTextDownLoadThread::startToDownload(), MusicDJRadioCategoryThread::startToDownload(), MusicKWBackgroundThread::startToDownload(), MusicWYTranslationThread::startToDownload(), MusicRadioPlayListThread::startToDownload(), MusicNetworkOperator::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicSourceUpdateThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicRadioChannelThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicRadioSongsThread::startToDownload(), MusicIdentifySongsThread::startToDownload(), MusicTranslationThread::startToDownload(), MusicVoiceTtsThread::startToDownload(), MusicDownloadBackgroundThunderThread::startToDownload(), MusicDownloadBackgroundBingThread::startToDownload(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryMGArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicWSSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicMGSongCommentsThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryMGMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryWSPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryMGPlaylistThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicMGPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicWSPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicMGDiscoverListThread::startToSearch(), MusicDownLoadQueryYYTThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicWSDiscoverListThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicMGSongSuggestThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicWSSongSuggestThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicMGArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicDownLoadQueryWSThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryQQThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryMGMovieThread::startToSearch(), MusicDownLoadQueryWYThread::startToSearch(), MusicDownLoadQueryMGThread::startToSearch(), MusicDownLoadQueryBDThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryWSArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryWSRecommendThread::startToSearch(), MusicDownLoadQueryMGAlbumThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryXMThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryMGArtistThread::startToSearch(), MusicDownLoadQueryKGThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryMGRecommendThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryWSToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryMGToplistThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryMGPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryWSPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryKWThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryMGThread::startToSingleSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryMGAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), MusicDownLoadQueryKWThread::startToSingleSearch(), MusicAdvancedSearchedWidget::updateServerPlaceholderText(), MusicSourceUpdateWidget::upgradeButtonClicked(), and MusicSourceUpdateWidget::upgradeFailedClicked().
QString MusicUtils::Algorithm::mdII (const QString & data, const QString & key, bool encode)
Get mdII(greedysky) algorithm.
Definition at line 48 of file musicalgorithmutils.cpp.
References MusicCryptographicHash::decrypt(), and MusicCryptographicHash::encrypt().
QByteArray MusicUtils::Algorithm::sha1 (const QByteArray & data)
Get sha1 algorithm.
Definition at line 11 of file musicalgorithmutils.cpp.
Referenced by hmacSha1().