TTKMusicPlayer: MusicCloudManagerWidget Class Reference
MusicCloudManagerWidget Class Reference
The class of the cloud manager widget.
#include <musiccloudmanagerwidget.h>
Public Slots
void updataSizeLabel (qint64 size)
void downloadFileFromServer ()
void deleteFileFromServer ()
void uploadFilesToServer ()
Public Member Functions
MusicCloudManagerWidget (QWidget *parent=nullptr)
~MusicCloudManagerWidget ()
void initialize () const
virtual void resizeWidget () overridefinal
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
QLabel * m_sizeValueLabel
QWidgetList m_resizeWidgets
QProgressBar * m_sizeValueBar
MusicCloudManagerTableWidget * m_tableWidget
Detailed Description
The class of the cloud manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 196 of file musiccloudmanagerwidget.h.
Constructor & Destructor Documentation
MusicCloudManagerWidget::MusicCloudManagerWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 558 of file musiccloudmanagerwidget.cpp.
References TTK::UI::BackgroundStyle09, TTK::UI::BackgroundStyle10, TTK::UI::ColorStyle01, TTK::UI::ColorStyle02, TTK::UI::ColorStyle03, deleteFileFromServer(), downloadFileFromServer(), TTK::UI::FontStyle01, m_resizeWidgets, m_sizeValueBar, m_sizeValueLabel, m_tableWidget, TTK::UI::ProgressBar01, TTK::UI::PushButtonStyle03, updataSizeLabel(), and uploadFilesToServer().
MusicCloudManagerWidget::~MusicCloudManagerWidget ()
Object destructor.
Definition at line 679 of file musiccloudmanagerwidget.cpp.
References m_sizeValueBar, m_sizeValueLabel, and m_tableWidget.
Member Function Documentation
void MusicCloudManagerWidget::deleteFileFromServer () slot
Delete file from server.
Definition at line 713 of file musiccloudmanagerwidget.cpp.
References MusicCloudManagerTableWidget::deleteFileFromServer(), and m_tableWidget.
Referenced by MusicCloudManagerWidget().
void MusicCloudManagerWidget::downloadFileFromServer () slot
Download file from server.
Definition at line 708 of file musiccloudmanagerwidget.cpp.
References MusicCloudManagerTableWidget::downloadFileFromServer(), and m_tableWidget.
Referenced by MusicCloudManagerWidget().
void MusicCloudManagerWidget::initialize () const
Initialize cloud main widget.
Definition at line 686 of file musiccloudmanagerwidget.cpp.
References m_tableWidget, and MusicCloudManagerTableWidget::queryCloudKey().
Referenced by MusicCloudSharedSongWidget::initialize().
void MusicCloudManagerWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 723 of file musiccloudmanagerwidget.cpp.
References resizeWidget().
void MusicCloudManagerWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 691 of file musiccloudmanagerwidget.cpp.
References G_SETTING_PTR, m_resizeWidgets, m_tableWidget, MusicCloudManagerTableWidget::resizeSection(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent().
void MusicCloudManagerWidget::updataSizeLabel (qint64 size) slot
Update size label.
Definition at line 702 of file musiccloudmanagerwidget.cpp.
References m_sizeValueBar, m_sizeValueLabel, TTK::Number::sizeByteToLabel(), TTK_RN_MAX, and TTK_SN_GB2B.
Referenced by MusicCloudManagerWidget().
void MusicCloudManagerWidget::uploadFilesToServer () slot
Upload files to server.
Definition at line 718 of file musiccloudmanagerwidget.cpp.
References m_tableWidget, and MusicCloudManagerTableWidget::uploadFilesToServer().
Referenced by MusicCloudManagerWidget().
Member Data Documentation
QWidgetList MusicCloudManagerWidget::m_resizeWidgets private
Definition at line 244 of file musiccloudmanagerwidget.h.
Referenced by MusicCloudManagerWidget(), and resizeWidget().
QProgressBar* MusicCloudManagerWidget::m_sizeValueBar private
Definition at line 245 of file musiccloudmanagerwidget.h.
Referenced by MusicCloudManagerWidget(), updataSizeLabel(), and ~MusicCloudManagerWidget().
QLabel* MusicCloudManagerWidget::m_sizeValueLabel private
Definition at line 243 of file musiccloudmanagerwidget.h.
Referenced by MusicCloudManagerWidget(), updataSizeLabel(), and ~MusicCloudManagerWidget().
MusicCloudManagerTableWidget* MusicCloudManagerWidget::m_tableWidget private
Definition at line 246 of file musiccloudmanagerwidget.h.
Referenced by deleteFileFromServer(), downloadFileFromServer(), initialize(), MusicCloudManagerWidget(), resizeWidget(), uploadFilesToServer(), and ~MusicCloudManagerWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudmanagerwidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudmanagerwidget.cpp