TTKMusicplayer: MusicInputDialog Class Reference
MusicInputDialog Class Reference
The class of the input widget.
#include <musicinputdialog.h>
Public Slots
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicInputDialog (QWidget *parent=nullptr)
~MusicInputDialog ()
QString text () const
void setPlaceholderText (const QString &text)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicInputDialog * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the input widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicinputdialog.h.
Constructor & Destructor Documentation
MusicInputDialog::MusicInputDialog (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musicinputdialog.cpp.
References m_ui, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle04, and MusicUIObject::MQSSToolButtonStyle04.
MusicInputDialog::~MusicInputDialog ()
Definition at line 25 of file musicinputdialog.cpp.
References m_ui.
Member Function Documentation
int MusicInputDialog::exec () virtual slot
Override exec function.
Definition at line 40 of file musicinputdialog.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicApplication::musicImportSongsByUrl().
void MusicInputDialog::setPlaceholderText (const QString & text)
Set placeholder text.
Definition at line 35 of file musicinputdialog.cpp.
References m_ui.
Referenced by MusicApplication::musicImportSongsByUrl().
QString MusicInputDialog::text () const
Get the text that the user input.
Definition at line 30 of file musicinputdialog.cpp.
References m_ui.
Referenced by MusicApplication::musicImportSongsByUrl().
Member Data Documentation
Ui::MusicInputDialog* MusicInputDialog::m_ui protected
Definition at line 58 of file musicinputdialog.h.
Referenced by exec(), MusicInputDialog(), setPlaceholderText(), text(), and ~MusicInputDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicinputdialog.h
TTKModule/TTKWidget/musicCoreKits/musicinputdialog.cpp