TTKMusicplayer: TTKThirdParty/Zlib/ttkzip/crypt.h File Reference
crypt.h File Reference
Macros
#define CRC32(c, b) ((*(pcrc_32_tab+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
#define zdecode(pkeys, pcrc_32_tab, c) (update_keys(pkeys,pcrc_32_tab,c ^= decrypt_byte(pkeys,pcrc_32_tab)))
#define zencode(pkeys, pcrc_32_tab, c, t) (t=decrypt_byte(pkeys,pcrc_32_tab), update_keys(pkeys,pcrc_32_tab,c), t^(c))
Functions
static int decrypt_byte (unsigned long *pkeys, const z_crc_t *pcrc_32_tab)
static int update_keys (unsigned long *pkeys, const z_crc_t *pcrc_32_tab, int c)
static void init_keys (const char *passwd, unsigned long *pkeys, const z_crc_t *pcrc_32_tab)
Macro Definition Documentation
#define CRC32 (c, b) ((*(pcrc_32_tab+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
Definition at line 30 of file crypt.h.
Referenced by update_keys().
#define zdecode (pkeys, pcrc_32_tab, c) (update_keys(pkeys,pcrc_32_tab,c ^= decrypt_byte(pkeys,pcrc_32_tab)))
Definition at line 76 of file crypt.h.
Referenced by unzOpenCurrentFile3(), and unzReadCurrentFile().
#define zencode (pkeys, pcrc_32_tab, c, t) (t=decrypt_byte(pkeys,pcrc_32_tab), update_keys(pkeys,pcrc_32_tab,c), t^(c))
Definition at line 79 of file crypt.h.
Referenced by zip64FlushWriteBuffer().
Function Documentation
static int decrypt_byte (unsigned long * pkeys, const z_crc_t * pcrc_32_tab) static
Definition at line 35 of file crypt.h.
static void init_keys (const char * passwd, unsigned long * pkeys, const z_crc_t * pcrc_32_tab) static
Definition at line 65 of file crypt.h.
References update_keys().
Referenced by unzOpenCurrentFile3().
static int update_keys (unsigned long * pkeys, const z_crc_t * pcrc_32_tab, int c) static
Definition at line 48 of file crypt.h.
References CRC32, and int().
Referenced by init_keys().