TTKMusicPlayer: ReqLQInterface Namespace Reference
ReqLQInterface Namespace Reference
The namespace of the lq request interface.
Functions
static void parseFromSongProperty (TTK::MusicSongInformation *info, const QVariantMap &key)
static void parseFromSongProperty (TTK::MusicSongInformation *info, const QString &key, int length, int bitrate)
Variables
static constexpr const char * LQ_BASE_URL = "VzJWczlXM2hMeCtTZzhLRFJvZWxUUTVmZUVBLzlMWmo="
static constexpr const char * LQ_RECOMMEND_URL = "NDhiOGZ6dUJWNTBvN3R5OHNOQmkyQVVwOXdWbDNBOG14MmVXWVJxWlVXRkxuNUxxdzdYTEpUYVZRNVE9"
Detailed Description
The namespace of the lq request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void ReqLQInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QVariantMap & key) static
Read tags(size and bitrate and url) from query results.
Definition at line 22 of file musicsongrecommendrequest.cpp.
References TTK::MusicSongInformation::m_songProps, parseFromSongProperty(), TTK::toString(), TTK_BN_1000, TTK_BN_128, TTK_BN_192, TTK_BN_320, and TTK_BN_750.
Referenced by MusicSongRecommendRequest::downLoadFinished().
void ReqLQInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QString & key, int length, int bitrate) static
Read tags(size and bitrate and url) from query results.
Definition at line 38 of file musicsongrecommendrequest.cpp.
References APE_FILE_SUFFIX, FLAC_FILE_SUFFIX, key, LQ_BASE_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, TTK::Algorithm::mdII(), MP3_FILE_SUFFIX, TTK::Number::sizeByteToLabel(), TTK_BN_1000, TTK_BN_128, TTK_BN_192, TTK_BN_320, and TTK_BN_750.
Referenced by parseFromSongProperty().
Variable Documentation
constexpr const char* ReqLQInterface::LQ_BASE_URL = "VzJWczlXM2hMeCtTZzhLRFJvZWxUUTVmZUVBLzlMWmo=" static
Definition at line 8 of file musicsongrecommendrequest.cpp.
Referenced by MusicSongRecommendRequest::downLoadFinished(), and parseFromSongProperty().
constexpr const char* ReqLQInterface::LQ_RECOMMEND_URL = "NDhiOGZ6dUJWNTBvN3R5OHNOQmkyQVVwOXdWbDNBOG14MmVXWVJxWlVXRkxuNUxxdzdYTEpUYVZRNVE9" static
Definition at line 9 of file musicsongrecommendrequest.cpp.
Referenced by MusicSongRecommendRequest::startToSearch().