TTKMusicplayer: MusicGrabWidget Class Reference
MusicGrabWidget Class Reference
The class of the grab area widget.
#include <musicgrabwidget.h>
Signals
void resetFlag (MusicObject::ToolsType flag)
Public Member Functions
MusicGrabWidget (QWidget *parent=0)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void keyPressEvent (QKeyEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
void grabPixmap ()
Protected Attributes
bool m_isDrawing
QPixmap m_originPixmap
QPixmap m_grabPixmap
QPoint m_ptCursor
QPoint m_ptStart
QPoint m_ptEnd
Private Slots
void musicCreateRightMenu ()
void musicCreateRightMenu (const QString &path)
Detailed Description
The class of the grab area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicgrabwidget.h.
Constructor & Destructor Documentation
MusicGrabWidget::MusicGrabWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 15 of file musicgrabwidget.cpp.
References m_isDrawing, and m_originPixmap.
Member Function Documentation
void MusicGrabWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 68 of file musicgrabwidget.cpp.
References resetFlag(), and MusicObject::TT_GrabWindow.
void MusicGrabWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 154 of file musicgrabwidget.cpp.
References musicCreateRightMenu().
QString MusicGrabWidget::getClassName () static
Get class object name.
Definition at line 37 of file musicgrabwidget.cpp.
void MusicGrabWidget::grabPixmap () protected
Grab pixmap.
Definition at line 162 of file musicgrabwidget.cpp.
References m_grabPixmap, m_ptEnd, and m_ptStart.
Referenced by mouseReleaseEvent().
void MusicGrabWidget::keyPressEvent (QKeyEvent * event) override protected virtual
Definition at line 140 of file musicgrabwidget.cpp.
References MusicObject::getAppDir(), JPG_FILE, and musicCreateRightMenu().
void MusicGrabWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 42 of file musicgrabwidget.cpp.
References m_ptCursor.
void MusicGrabWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 117 of file musicgrabwidget.cpp.
References m_isDrawing, m_ptCursor, and m_ptStart.
void MusicGrabWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 129 of file musicgrabwidget.cpp.
References grabPixmap(), m_isDrawing, and m_ptEnd.
void MusicGrabWidget::musicCreateRightMenu () private slot
Create right menu.
Definition at line 50 of file musicgrabwidget.cpp.
References MusicUtils::Widget::getSaveFileDialog().
Referenced by contextMenuEvent(), and keyPressEvent().
void MusicGrabWidget::musicCreateRightMenu (const QString & path) private slot
Create right menu.
Definition at line 59 of file musicgrabwidget.cpp.
References m_grabPixmap.
void MusicGrabWidget::paintEvent (QPaintEvent * event) override protected virtual
Definition at line 74 of file musicgrabwidget.cpp.
References m_isDrawing, m_originPixmap, m_ptCursor, m_ptEnd, and m_ptStart.
void MusicGrabWidget::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by closeEvent().
Member Data Documentation
QPixmap MusicGrabWidget::m_grabPixmap protected
Definition at line 76 of file musicgrabwidget.h.
Referenced by grabPixmap(), and musicCreateRightMenu().
bool MusicGrabWidget::m_isDrawing protected
Definition at line 75 of file musicgrabwidget.h.
Referenced by mousePressEvent(), mouseReleaseEvent(), MusicGrabWidget(), and paintEvent().
QPixmap MusicGrabWidget::m_originPixmap protected
Definition at line 76 of file musicgrabwidget.h.
Referenced by MusicGrabWidget(), and paintEvent().
QPoint MusicGrabWidget::m_ptCursor protected
Definition at line 77 of file musicgrabwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and paintEvent().
QPoint MusicGrabWidget::m_ptEnd protected
Definition at line 77 of file musicgrabwidget.h.
Referenced by grabPixmap(), mouseReleaseEvent(), and paintEvent().
QPoint MusicGrabWidget::m_ptStart protected
Definition at line 77 of file musicgrabwidget.h.
Referenced by grabPixmap(), mousePressEvent(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicgrabwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicgrabwidget.cpp