TTKMusicplayer: MusicAbstractThread Class Reference
MusicAbstractThread Class Reference
The class of the abstract thread.
#include <musicabstractthread.h>
Public Slots
void start ()
Public Member Functions
MusicAbstractThread (QObject *parent=nullptr)
~MusicAbstractThread ()
void stopAndQuitThread ()
Protected Member Functions
virtual void run () override
Protected Attributes
bool m_running
Detailed Description
The class of the abstract thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicabstractthread.h.
Constructor & Destructor Documentation
MusicAbstractThread::MusicAbstractThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicabstractthread.cpp.
References m_running.
MusicAbstractThread::~MusicAbstractThread ()
Definition at line 9 of file musicabstractthread.cpp.
Member Function Documentation
void MusicAbstractThread::run () override protected virtual
Thread run now.
Reimplemented in MusicSongCheckToolsQualityThread, MusicSongCheckToolsDuplicateThread, MusicSongCheckToolsRenameThread, MusicLocalSongsManagerThread, MusicImageRenderer, MusicConnectTransferThread, and MusicNetworkTestThread.
Definition at line 30 of file musicabstractthread.cpp.
Referenced by MusicConnectTransferThread::run(), MusicNetworkTestThread::run(), MusicImageRenderer::run(), MusicLocalSongsManagerThread::run(), MusicSongCheckToolsRenameThread::run(), MusicSongCheckToolsDuplicateThread::run(), and MusicSongCheckToolsQualityThread::run().
void MusicAbstractThread::start () slot
Strat thread now.
Definition at line 24 of file musicabstractthread.cpp.
References m_running.
Referenced by MusicArtistAlbumsItemWidget::downLoadFinished(), MusicWebDJRadioQueryItemWidget::downLoadFinished(), MusicWebMVRadioQueryItemWidget::downLoadFinished(), MusicPlaylistQueryItemWidget::downLoadFinished(), MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), MusicSongCheckToolsWidget::duplicateReCheckButtonClicked(), MusicLocalSongsManagerWidget::filterScanChanged(), MusicSongCheckToolsWidget::qualityReCheckButtonClicked(), MusicSongCheckToolsWidget::renameButtonCheckClicked(), MusicSongCheckToolsWidget::renameReCheckButtonClicked(), MusicNetworkConnectionItem::start(), and MusicConnectTransferWidget::startToTransferFiles().
void MusicAbstractThread::stopAndQuitThread ()
Stop and quit current thread.
Definition at line 14 of file musicabstractthread.cpp.
References m_running.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), MusicSongCheckToolsWidget::duplicateReCheckButtonClicked(), MusicLocalSongsManagerWidget::filterScanChanged(), MusicSongCheckToolsWidget::qualityButtonCheckClicked(), MusicSongCheckToolsWidget::qualityReCheckButtonClicked(), MusicSongCheckToolsWidget::renameButtonCheckClicked(), MusicSongCheckToolsWidget::renameReCheckButtonClicked(), MusicNetworkConnectionItem::stop(), MusicImageRenderer::~MusicImageRenderer(), MusicLocalSongsManagerWidget::~MusicLocalSongsManagerWidget(), and MusicNetworkConnectionItem::~MusicNetworkConnectionItem().
Member Data Documentation
bool MusicAbstractThread::m_running protected
Definition at line 58 of file musicabstractthread.h.
Referenced by MusicAbstractThread(), MusicConnectTransferThread::run(), MusicNetworkTestThread::run(), MusicImageRenderer::run(), MusicLocalSongsManagerThread::run(), MusicSongCheckToolsRenameThread::run(), MusicSongCheckToolsQualityThread::run(), start(), and stopAndQuitThread().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicabstractthread.h
TTKModule/TTKCore/musicCoreKits/musicabstractthread.cpp