TTKMusicplayer: QDesWrap Class Reference
QDesWrap Class Reference
The namespace of the des wrapper.
#include <qdeswrap.h>
Public Types
enum Mode { ENCRYPT = 0, DECRYPT = 1 }
Public Member Functions
QByteArray encrypt (const QByteArray &in, const QByteArray &key)
QByteArray decrypt (const QByteArray &in, const QByteArray &key)
Protected Member Functions
qint64 bitTransform (int *array, int len, qint64 source)
void DESSubKeys (qint64 key, qint64 *K, Mode mode)
qint64 DES64 (qint64 *subkeys, qint64 data)
char * encrypt (char *src, int srcLength, char *key)
Protected Attributes
Mode m_mode
Detailed Description
The namespace of the des wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qdeswrap.h.
Member Enumeration Documentation
enum QDesWrap::Mode
Enumerator
ENCRYPT
DECRYPT
Definition at line 30 of file qdeswrap.h.
Member Function Documentation
qint64 QDesWrap::bitTransform (int * array, int len, qint64 source) protected
Definition at line 199 of file qdeswrap.cpp.
References ARRAYMASK.
Referenced by DES64(), and DESSubKeys().
QByteArray QDesWrap::decrypt (const QByteArray & in, const QByteArray & key)
Decrypt des by input.
Definition at line 186 of file qdeswrap.cpp.
References Base64Decode(), DECRYPT, encrypt(), and m_mode.
qint64 QDesWrap::DES64 (qint64 * subkeys, qint64 data) protected
Definition at line 234 of file qdeswrap.cpp.
References ARRAYE, ARRAYIP, ARRAYIP_1, ARRAYP, bitTransform(), int(), and MATRIXNSBOX.
Referenced by encrypt().
void QDesWrap::DESSubKeys (qint64 key, qint64 * K, Mode mode) protected
Definition at line 212 of file qdeswrap.cpp.
References ARRAYLS, ARRAYLSMASK, ARRAYPC_1, ARRAYPC_2, bitTransform(), and DECRYPT.
Referenced by encrypt().
QByteArray QDesWrap::encrypt (const QByteArray & in, const QByteArray & key)
Encrypt des by input.
Definition at line 173 of file qdeswrap.cpp.
References Base64Encode(), ENCRYPT, and m_mode.
Referenced by decrypt(), MusicDownLoadKWInterface::readFromMusicLLAttribute(), and MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute().
char * QDesWrap::encrypt (char * src, int srcLength, char * key) protected
Definition at line 283 of file qdeswrap.cpp.
References DES64(), DESSubKeys(), and m_mode.
Member Data Documentation
Mode QDesWrap::m_mode protected
Definition at line 51 of file qdeswrap.h.
Referenced by decrypt(), and encrypt().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalg/qdeswrap.h
TTKThirdParty/TTKExtras/qalg/qdeswrap.cpp