TTKMusicplayer: QNSimpleUploadData Class Reference
QNSimpleUploadData Class Reference
The namespace of the qiniu simple upload data.
#include <qnsimpleuploaddata.h>
Signals
void uploadFileFinished (const QString &time)
void uploadProgressChanged (const QString &time, qint64 bytesSent, qint64 bytesTotal)
Public Member Functions
QNSimpleUploadData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void uploadDataToServer (const QString &time, const QByteArray &data, const QString &bucket, const QString &key, const QString &name)
QString getDownloadUrl (const QString &domain, const QString &key)
Private Slots
void receiveDataFromServer ()
void handleError (QNetworkReply::NetworkError error)
void uploadProgress (qint64 bytesSent, qint64 bytesTotal)
Detailed Description
The namespace of the qiniu simple upload data.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 31 of file qnsimpleuploaddata.h.
Constructor & Destructor Documentation
QNSimpleUploadData::QNSimpleUploadData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 30 of file qnsimpleuploaddata.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
QString QNSimpleUploadData::getDownloadUrl (const QString & domain, const QString & key)
Get download url request.
Definition at line 60 of file qnsimpleuploaddata.cpp.
References QNConf::ACCESS_KEY, QNUtils::expireInSeconds(), QNPutPolicy::makeDownloadToken(), and QNConf::SECRET_KEY.
Referenced by MusicCloudManagerTableWidget::downloadFileToServer().
void QNSimpleUploadData::handleError (QNetworkReply::NetworkError error) private slot
Get handle error.
Definition at line 97 of file qnsimpleuploaddata.cpp.
Referenced by uploadDataToServer().
void QNSimpleUploadData::receiveDataFromServer () private slot
Receive data from server finshed.
Definition at line 75 of file qnsimpleuploaddata.cpp.
References MObject_cast, TTK_D, TTK_ERROR_STR, and uploadFileFinished().
Referenced by uploadDataToServer().
void QNSimpleUploadData::uploadDataToServer (const QString & time, const QByteArray & data, const QString & bucket, const QString & key, const QString & name)
Get uplaod data to server request.
Definition at line 38 of file qnsimpleuploaddata.cpp.
References QNConf::ACCESS_KEY, QNIOHelper::createPutDataMultiPart(), handleError(), QNPutPolicy::makeUploadToken(), MusicObject::NetworkError, receiveDataFromServer(), QNConf::SECRET_KEY, TTK_D, QNConf::UPLOAD_HOST, uploadProgress(), and uploadProgressChanged().
Referenced by MusicCloudManagerTableWidget::startToUploadFile().
void QNSimpleUploadData::uploadFileFinished (const QString & time) signal
Uplaod file finshed.
Referenced by receiveDataFromServer().
void QNSimpleUploadData::uploadProgress (qint64 bytesSent, qint64 bytesTotal) private slot
Show upload progress.
Definition at line 102 of file qnsimpleuploaddata.cpp.
References TTK_D, and uploadProgressChanged().
Referenced by uploadDataToServer().
void QNSimpleUploadData::uploadProgressChanged (const QString & time, qint64 bytesSent, qint64 bytesTotal) signal
Show upload progress.
Referenced by uploadDataToServer(), and uploadProgress().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnsimpleuploaddata.h
TTKThirdParty/TTKExtras/qiniu/qnsimpleuploaddata.cpp