TTKMusicplayer: QAesWrap Class Reference
QAesWrap Class Reference
The namespace of the aes wrapper.
#include <qaeswrap.h>
Static Public Member Functions
static QByteArray encrypt (const QByteArray &in, const QByteArray &key, const QByteArray &iv)
static QByteArray decrypt (const QByteArray &in, const QByteArray &key, const QByteArray &iv)
Detailed Description
The namespace of the aes wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qaeswrap.h.
Member Function Documentation
QByteArray QAesWrap::decrypt (const QByteArray & in, const QByteArray & key, const QByteArray & iv) static
Decrypt aes by input.
Definition at line 39 of file qaeswrap.cpp.
References AES_cbc_encrypt(), AES_DECRYPT, AES_set_decrypt_key(), Base64Decode(), CACHE_SIZE, and MusicUtils::Codec::toUtf8().
QByteArray QAesWrap::encrypt (const QByteArray & in, const QByteArray & key, const QByteArray & iv) static
Encrypt aes by input.
Definition at line 9 of file qaeswrap.cpp.
References AES_BLOCK_SIZE, AES_cbc_encrypt(), AES_ENCRYPT, AES_set_encrypt_key(), Base64Encode(), and CACHE_SIZE.
Referenced by MusicDownLoadBDInterface::makeTokenQueryUrl(), MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicBDSongCommentsThread::startToPage(), and MusicBDPlaylistCommentsThread::startToPage().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalg/qaeswrap.h
TTKThirdParty/TTKExtras/qalg/qaeswrap.cpp