TTKMusicplayer: QImageWrap::SharpeImage Class Reference
QImageWrap::SharpeImage Class Reference abstract
The class of the sharpe image.
#include <qimagewrap.h>
Public Member Functions
SharpeImage ()
virtual ~SharpeImage ()
virtual void input (const QRect &rectangle)
virtual QPixmap render (const QPixmap &pixmap, int value)=0
Protected Member Functions
SharpeImage (SharpeImagePrivate &pvt)
Detailed Description
The class of the sharpe image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 47 of file qimagewrap.h.
Constructor & Destructor Documentation
QImageWrap::SharpeImage::SharpeImage ()
Definition at line 135 of file qimagewrap.cpp.
QImageWrap::SharpeImage::~SharpeImage () virtual
Definition at line 146 of file qimagewrap.cpp.
QImageWrap::SharpeImage::SharpeImage (SharpeImagePrivate & pvt) protected
Definition at line 141 of file qimagewrap.cpp.
References TTK_INIT_PRIVATE_D.
Member Function Documentation
void QImageWrap::SharpeImage::input (const QRect & rectangle) virtual
Init item data.
Reimplemented in QImageWrap::WaterWave, and QImageWrap::CubeWave.
Definition at line 151 of file qimagewrap.cpp.
References TTK_D.
Referenced by QImageWrap::CubeWave::input(), QImageWrap::WaterWave::input(), and MusicTransitionAnimationLabel::setPixmap().
virtual QPixmap QImageWrap::SharpeImage::render (const QPixmap & pixmap, int value) pure virtual
Render data.
Implemented in QImageWrap::WaterWave, and QImageWrap::CubeWave.
Referenced by MusicTransitionAnimationLabel::paintEvent().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/qimagewrap.h
TTKThirdParty/TTKExtras/qalgorithm/qimagewrap.cpp