TTKMusicplayer: MusicAuthenticationThread Class Reference
MusicAuthenticationThread Class Reference abstract
The class to login authentication.
#include <musicauthenticationthread.h>
Public Member Functions
MusicAuthenticationThread (QObject *parent=nullptr)
virtual ~MusicAuthenticationThread ()
virtual void deleteAll () override
virtual void startToDownload (const QString &usr, const QString &pwd)=0
const MusicUserInfoRecord & getInfoRecord () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Attributes
MusicUserInfoRecord m_info
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
QVariantMap m_headerData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Detailed Description
The class to login authentication.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicauthenticationthread.h.
Constructor & Destructor Documentation
MusicAuthenticationThread::MusicAuthenticationThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicauthenticationthread.cpp.
References MusicNetworkAbstract::m_manager, and MusicNetworkAbstract::m_reply.
MusicAuthenticationThread::~MusicAuthenticationThread () virtual
Definition at line 10 of file musicauthenticationthread.cpp.
References deleteAll().
Member Function Documentation
void MusicAuthenticationThread::deleteAll () override virtual
Release the network object.
Reimplemented from MusicNetworkAbstract.
Definition at line 15 of file musicauthenticationthread.cpp.
References MusicNetworkAbstract::m_reply.
Referenced by MusicWYAuthenticationThread::downLoadFinished(), MusicWYAuthenticationThread::startToDownload(), and ~MusicAuthenticationThread().
const MusicUserInfoRecord& MusicAuthenticationThread::getInfoRecord () const inline
Get info record.
Definition at line 52 of file musicauthenticationthread.h.
virtual void MusicAuthenticationThread::startToDownload (const QString & usr, const QString & pwd) pure virtual
Start to translation data. Subclass should implement this function.
Implemented in MusicWYAuthenticationThread.
Member Data Documentation
MusicUserInfoRecord MusicAuthenticationThread::m_info protected
Definition at line 55 of file musicauthenticationthread.h.
Referenced by MusicWYAuthenticationThread::downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicauthenticationthread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicauthenticationthread.cpp