TTKMusicplayer: QHttpConnection Class Reference
QHttpConnection Class Reference
The class of the http connection.
#include <qhttpconnection.h>
Signals
void newRequest (QHttpRequest *request, QHttpResponse *response)
void allBytesWritten ()
Public Member Functions
QHttpConnection (QTcpSocket *socket, QObject *parent=nullptr)
void write (const QByteArray &data)
void flush ()
void waitForBytesWritten ()
Private Slots
void parseRequest ()
void responseDone ()
void socketDisconnected ()
void invalidateRequest ()
void updateWriteCount (qint64)
Detailed Description
The class of the http connection.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file qhttpconnection.h.
Constructor & Destructor Documentation
QHttpConnection::QHttpConnection (QTcpSocket * socket, QObject * parent = nullptr) explicit
Definition at line 130 of file qhttpconnection.cpp.
References parseRequest(), socketDisconnected(), TTK_D, TTK_INIT_PRIVATE, and updateWriteCount().
Member Function Documentation
void QHttpConnection::allBytesWritten () signal
Referenced by QHttpConnectionPrivate::writeCount().
void QHttpConnection::flush ()
Definition at line 173 of file qhttpconnection.cpp.
References TTK_D.
void QHttpConnection::invalidateRequest () private slot
Definition at line 149 of file qhttpconnection.cpp.
References TTK_D.
Referenced by socketDisconnected().
void QHttpConnection::newRequest (QHttpRequest * request, QHttpResponse * response) signal
Referenced by QHttpConnectionPrivate::HeadersComplete().
void QHttpConnection::parseRequest () private slot
Definition at line 161 of file qhttpconnection.cpp.
References TTK_D.
Referenced by QHttpConnection().
void QHttpConnection::responseDone () private slot
Definition at line 185 of file qhttpconnection.cpp.
References QHttpResponse::isLast(), TTK_D, and TTKObject_cast.
void QHttpConnection::socketDisconnected () private slot
Definition at line 143 of file qhttpconnection.cpp.
References invalidateRequest().
Referenced by QHttpConnection().
void QHttpConnection::updateWriteCount (qint64 count) private slot
Definition at line 155 of file qhttpconnection.cpp.
References TTK_D.
Referenced by QHttpConnection().
void QHttpConnection::waitForBytesWritten ()
Definition at line 179 of file qhttpconnection.cpp.
References TTK_D.
void QHttpConnection::write (const QByteArray & data)
Definition at line 167 of file qhttpconnection.cpp.
References TTK_D.
Referenced by QHttpResponsePrivate::write(), QHttpResponsePrivate::writeHead(), and QHttpResponsePrivate::writeHeader().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qhttpserver/qhttpconnection.h
TTKThirdParty/TTKExtras/qhttpserver/qhttpconnection.cpp