TTKMusicPlayer: ToolSkin Class Reference
ToolSkin Class Reference
The class of the skin tool.
#include <toolskin.h>
Public Member Functions
ToolSkin (QWidget *parent=nullptr)
~ToolSkin ()
Private Slots
void imageClicked ()
void paletteClicked ()
void readClicked ()
void writeClicked ()
Private Attributes
Ui::ToolSkin * m_ui
QPixmap m_pixmap
Detailed Description
The class of the skin tool.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file toolskin.h.
Constructor & Destructor Documentation
ToolSkin::ToolSkin (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file toolskin.cpp.
References imageClicked(), m_pixmap, m_ui, paletteClicked(), readClicked(), and writeClicked().
ToolSkin::~ToolSkin ()
Object destructor.
Definition at line 25 of file toolskin.cpp.
References m_ui.
Member Function Documentation
void ToolSkin::imageClicked () private slot
Definition at line 30 of file toolskin.cpp.
References TTK::File::getOpenFileName(), m_pixmap, and m_ui.
Referenced by ToolSkin().
void ToolSkin::paletteClicked () private slot
Definition at line 42 of file toolskin.cpp.
References m_pixmap, m_ui, and MusicColorDialog::popup().
Referenced by ToolSkin().
void ToolSkin::readClicked () private slot
Definition at line 55 of file toolskin.cpp.
References TTK::File::getOpenFileName(), MusicBackgroundImage::m_item, MusicSkinItem::m_name, MusicBackgroundImage::m_pix, m_pixmap, m_ui, MusicSkinItem::m_useCount, and MusicExtractManager::outputSkin().
Referenced by ToolSkin().
void ToolSkin::writeClicked () private slot
Definition at line 73 of file toolskin.cpp.
References TTK::File::getSaveFileName(), MusicExtractManager::inputSkin(), MusicBackgroundImage::m_item, MusicSkinItem::m_name, MusicBackgroundImage::m_pix, m_pixmap, m_ui, MusicSkinItem::m_useCount, and TTK_INFO_STREAM.
Referenced by ToolSkin().
Member Data Documentation
QPixmap ToolSkin::m_pixmap private
Definition at line 52 of file toolskin.h.
Referenced by imageClicked(), paletteClicked(), readClicked(), ToolSkin(), and writeClicked().
Ui::ToolSkin* ToolSkin::m_ui private
Definition at line 51 of file toolskin.h.
Referenced by imageClicked(), paletteClicked(), readClicked(), ToolSkin(), writeClicked(), and ~ToolSkin().
The documentation for this class was generated from the following files:
TTKRun/TTKTools/GenerateSkin/toolskin.h
TTKRun/TTKTools/GenerateSkin/toolskin.cpp