TTKMusicplayer: MusicToplistQueryWidget Class Reference
MusicToplistQueryWidget Class Reference
The class of toplist music query widget.
#include <musictoplistquerywidget.h>
Public Slots
void queryAllFinished ()
void createToplistInfoItem (const MusicResultsItem &item)
void categoryChanged (const MusicResultsCategoryItem &category)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicToplistQueryWidget (QWidget *parent=nullptr)
~MusicToplistQueryWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractItemQueryWidget ()
void initWidget ()
Protected Member Functions
void createLabels ()
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes
MusicToplistQueryCategoryPopWidget * m_categoryButton
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of toplist music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 52 of file musictoplistquerywidget.h.
Constructor & Destructor Documentation
MusicToplistQueryWidget::MusicToplistQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 30 of file musictoplistquerywidget.cpp.
References createToplistInfoItem(), G_DOWNLOAD_QUERY_PTR, m_categoryButton, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_queryTableWidget, and MusicItemQueryTableWidget::setQueryInput().
MusicToplistQueryWidget::~MusicToplistQueryWidget ()
Definition at line 44 of file musictoplistquerywidget.cpp.
References m_categoryButton.
Member Function Documentation
void MusicToplistQueryWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 222 of file musictoplistquerywidget.cpp.
References MusicToplistQueryCategoryPopWidget::closeMenu(), m_categoryButton, MusicResultsCategoryItem::m_key, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_songButton, MusicResultsCategoryItem::m_value, MusicAbstractQueryRequest::OtherQuery, MusicAbstractQueryRequest::setQueryAllRecords(), and MusicAbstractQueryRequest::startToSearch().
void MusicToplistQueryWidget::createLabels () protected
Create init interface lables.
Definition at line 92 of file musictoplistquerywidget.cpp.
References MusicUtils::Widget::generateVScrollAreaFormat(), MusicAbstractQueryRequest::getQueryServer(), MusicAbstractItemQueryWidget::initFirstWidget(), m_categoryButton, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_iconLabel, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songButton, MusicAbstractItemQueryWidget::m_statusLabel, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSPushButtonStyle03, and MusicToplistQueryCategoryPopWidget::setCategory().
Referenced by setSongName().
void MusicToplistQueryWidget::createToplistInfoItem (const MusicResultsItem & item) slot
Create the current toplist info item.
Definition at line 193 of file musictoplistquerywidget.cpp.
References COVER_URL_NULL, MusicAbstractItemQueryWidget::downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicResultsItem::m_name, MusicResultsItem::m_playCount, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicResultsItem::m_updateTime, and MusicDownloadSourceRequest::startToDownload().
Referenced by MusicToplistQueryWidget().
void MusicToplistQueryWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 87 of file musictoplistquerywidget.cpp.
References MusicAbstractItemQueryWidget::setSongCountText().
void MusicToplistQueryWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 64 of file musictoplistquerywidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicItemQueryTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
void MusicToplistQueryWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 49 of file musictoplistquerywidget.cpp.
References createLabels(), MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractQueryRequest::OtherQuery, MusicAbstractQueryRequest::setQueryAllRecords(), MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSearch().
void MusicToplistQueryWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 59 of file musictoplistquerywidget.cpp.
Member Data Documentation
MusicToplistQueryCategoryPopWidget* MusicToplistQueryWidget::m_categoryButton protected
Definition at line 97 of file musictoplistquerywidget.h.
Referenced by categoryChanged(), createLabels(), MusicToplistQueryWidget(), and ~MusicToplistQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musictoplistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musictoplistquerywidget.cpp