TTKMusicplayer: OSSDataInterface Class Reference
OSSDataInterface Class Reference abstract
The class of the alioss cloud data item.
#include <ossdatainterface.h>
Public Member Functions
OSSDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Protected Slots
virtual void receiveDataFromServer ()=0
void handleError (QNetworkReply::NetworkError error)
Protected Member Functions
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
Detailed Description
The class of the alioss cloud data item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file ossdatainterface.h.
Constructor & Destructor Documentation
OSSDataInterface::OSSDataInterface (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file ossdatainterface.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
void OSSDataInterface::handleError (QNetworkReply::NetworkError error) protected slot
Get handle error.
Definition at line 12 of file ossdatainterface.cpp.
References M_LOGGER_ERROR.
Referenced by OSSDeleteData::deleteDataOperator(), OSSDownloadData::downloadDataOperator(), OSSListData::listDataOperator(), and OSSUploadData::uploadDataOperator().
QString OSSDataInterface::pathDecode (const QString & data) const protected
Pretty decode the data into url.
Definition at line 26 of file ossdatainterface.cpp.
QString OSSDataInterface::pathEncode (const QString & data) const protected
Pretty encode the data into url.
Definition at line 17 of file ossdatainterface.cpp.
Referenced by OSSDownloadData::getDownloadUrl().
virtual void OSSDataInterface::receiveDataFromServer () protected pure virtual slot
Receive data from server finshed. Subclass should implement this function.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qoss/ossdatainterface.h
TTKThirdParty/TTKExtras/qoss/ossdatainterface.cpp