TTKMusicPlayer: MusicNetworkConnectionItem Class Reference
MusicNetworkConnectionItem Class Reference
The class of the network connection item Widget.
#include <musicnetworkconnectiontestwidget.h>
Signals
void networkConnectionTestChanged ()
Public Member Functions
MusicNetworkConnectionItem (QWidget *parent=nullptr)
~MusicNetworkConnectionItem ()
void setText (const QString &text)
void setUrl (const QString &url)
void start ()
void stop ()
Private Slots
void testFinshed (bool state)
Private Attributes
MusicNetworkTestThread * m_thread
QLabel * m_iconLabel
QLabel * m_nameText
QLabel * m_stateText
Detailed Description
The class of the network connection item Widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicnetworkconnectiontestwidget.h.
Constructor & Destructor Documentation
MusicNetworkConnectionItem::MusicNetworkConnectionItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicnetworkconnectiontestwidget.cpp.
References m_iconLabel, m_nameText, m_stateText, m_thread, networkConnectionTestChanged(), stop(), and testFinshed().
MusicNetworkConnectionItem::~MusicNetworkConnectionItem ()
Definition at line 38 of file musicnetworkconnectiontestwidget.cpp.
References m_iconLabel, m_nameText, m_stateText, m_thread, and TTKAbstractThread::stopAndQuitThread().
Member Function Documentation
void MusicNetworkConnectionItem::networkConnectionTestChanged () signal
Network connection test changed.
Referenced by MusicNetworkConnectionItem(), and testFinshed().
void MusicNetworkConnectionItem::setText (const QString & text)
Set label text name.
Definition at line 50 of file musicnetworkconnectiontestwidget.cpp.
References m_nameText.
Referenced by MusicNetworkConnectionTestWidget::MusicNetworkConnectionTestWidget().
void MusicNetworkConnectionItem::setUrl (const QString & url)
Set current test url.
Definition at line 55 of file musicnetworkconnectiontestwidget.cpp.
References m_thread, and MusicNetworkTestThread::setUrl().
void MusicNetworkConnectionItem::start ()
Start to test network.
Definition at line 60 of file musicnetworkconnectiontestwidget.cpp.
References MusicUIObject::ColorStyle08, m_stateText, m_thread, and TTKAbstractThread::start().
void MusicNetworkConnectionItem::stop ()
Stop to test network.
Definition at line 67 of file musicnetworkconnectiontestwidget.cpp.
References MusicUIObject::ColorStyle03, m_iconLabel, m_stateText, m_thread, and TTKAbstractThread::stopAndQuitThread().
Referenced by MusicNetworkConnectionItem().
void MusicNetworkConnectionItem::testFinshed (bool state) private slot
Test network finished.
Definition at line 79 of file musicnetworkconnectiontestwidget.cpp.
References MusicUIObject::ColorStyle05, MusicUIObject::ColorStyle07, m_iconLabel, m_stateText, and networkConnectionTestChanged().
Referenced by MusicNetworkConnectionItem().
Member Data Documentation
QLabel* MusicNetworkConnectionItem::m_iconLabel private
Definition at line 72 of file musicnetworkconnectiontestwidget.h.
Referenced by MusicNetworkConnectionItem(), stop(), testFinshed(), and ~MusicNetworkConnectionItem().
QLabel * MusicNetworkConnectionItem::m_nameText private
Definition at line 72 of file musicnetworkconnectiontestwidget.h.
Referenced by MusicNetworkConnectionItem(), setText(), and ~MusicNetworkConnectionItem().
QLabel * MusicNetworkConnectionItem::m_stateText private
Definition at line 72 of file musicnetworkconnectiontestwidget.h.
Referenced by MusicNetworkConnectionItem(), start(), stop(), testFinshed(), and ~MusicNetworkConnectionItem().
MusicNetworkTestThread* MusicNetworkConnectionItem::m_thread private
Definition at line 71 of file musicnetworkconnectiontestwidget.h.
Referenced by MusicNetworkConnectionItem(), setUrl(), start(), stop(), and ~MusicNetworkConnectionItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkconnectiontestwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkconnectiontestwidget.cpp