TTKMusicPlayer: MusicDownLoadTextRequest Class Reference
MusicDownLoadTextRequest Class Reference
The class of the download the type of txt.
#include <musicdownloadtextrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractDownLoadRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadTextRequest (const QString &url, const QString &path, QObject *parent=nullptr)
virtual void startToRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownLoadRequest
MusicAbstractDownLoadRequest (const QString &url, const QString &path, TTK::Download type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicAbstractDownLoadRequest
QString mapCurrentQueryData () const
Protected Attributes inherited from MusicAbstractDownLoadRequest
QFile * m_file
QString m_url
QString m_savePath
TTK::Download m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the download the type of txt.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadtextrequest.h.
Constructor & Destructor Documentation
MusicDownLoadTextRequest::MusicDownLoadTextRequest (const QString & url, const QString & path, QObject * parent = nullptr)
Object constructor provide download url save local path and download type.
Definition at line 3 of file musicdownloadtextrequest.cpp.
Member Function Documentation
void MusicDownLoadTextRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 32 of file musicdownloadtextrequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), MusicAbstractDownLoadRequest::downLoadFinished(), MusicAbstractDownLoadRequest::m_file, TTKAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::mapCurrentQueryData(), QtNamespace, TTK_ERROR_STREAM, and TTK_INFO_STREAM.
Referenced by startToRequest().
void MusicDownLoadTextRequest::startToRequest () final override virtual
Start to download text data.
Implements MusicAbstractDownLoadRequest.
Definition at line 9 of file musicdownloadtextrequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), downLoadFinished(), MusicAbstractDownLoadRequest::downloadProgress(), MusicAbstractDownLoadRequest::m_file, TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::m_speedTimer, MusicAbstractDownLoadRequest::m_url, TTK::makeContentTypeHeader(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK::setSslConfiguration(), TTK_ERROR_STREAM, and TTK_SLOT.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadtextrequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadtextrequest.cpp