TTKMusicplayer: TTKExtra/qmmp/equ/iir_cfs.c File Reference
iir_cfs.c File Reference
#include "iir_cfs.h"
#include <stdio.h>
#include <math.h>
Macros
#define GAIN_F0 1.0
#define GAIN_F1 GAIN_F0 / M_SQRT2
#define SAMPLING_FREQ 44100.0
#define TETA(f) (2*M_PI*(double)f/iir_bands[n].sfreq)
#define TWOPOWER(value) (value * value)
#define BETA2(tf0, tf)
#define BETA1(tf0, tf)
#define BETA0(tf0, tf)
#define GAMMA(beta, tf0) ((0.5 + beta) * cos(tf0))
#define ALPHA(beta) ((0.5 - beta)/2.0)
Functions
static sIIRCoefficients iir_cf10_11k_11025[10] __attribute__ ((aligned))
sIIRCoefficients * get_coeffs (int *bands, unsigned int sfreq)
static void find_f1_and_f2 (double f0, double octave_percent, double *f1, double *f2)
static int find_root (double a, double b, double c, double *x0)
void calc_coeffs ()
Variables
static const double band_f011k []
static const double band_f022k []
static const double band_f010 []
static const double band_original_f010 []
static const double band_f015 []
static const double band_f025 []
static const double band_f031 []
struct {
sIIRCoefficients * coeffs
const double * cfs
double octave
int band_count
double sfreq
} iir_bands []
Macro Definition Documentation
#define ALPHA (beta) ((0.5 - beta)/2.0)
Definition at line 106 of file iir_cfs.c.
Referenced by calc_coeffs().
#define BETA0 (tf0, tf)
Value:
(0.25 * TWOPOWER(GAIN_F1) * TWOPOWER(cos(tf0)) \
     - 0.5 * TWOPOWER(GAIN_F1) * cos(tf) * cos(tf0) \
     + 0.25 * TWOPOWER(GAIN_F1) \
     - 0.25 * TWOPOWER(GAIN_F0) * TWOPOWER(sin(tf)))
Definition at line 99 of file iir_cfs.c.
Referenced by calc_coeffs().
#define BETA1 (tf0, tf)
Value:
(2.0 * TWOPOWER(GAIN_F1) * TWOPOWER(cos(tf)) \
     + TWOPOWER(GAIN_F1) * TWOPOWER(cos(tf0)) \
     - 2.0 * TWOPOWER(GAIN_F1) * cos(tf) * cos(tf0) \
     - TWOPOWER(GAIN_F1) + TWOPOWER(GAIN_F0) * TWOPOWER(sin(tf)))
Definition at line 94 of file iir_cfs.c.
Referenced by calc_coeffs().
#define BETA2 (tf0, tf)
Value:
(TWOPOWER(GAIN_F1)*TWOPOWER(cos(tf0)) \
 - 2.0 * TWOPOWER(GAIN_F1) * cos(tf) * cos(tf0) \
 + TWOPOWER(GAIN_F1) \
 - TWOPOWER(GAIN_F0) * TWOPOWER(sin(tf)))
Definition at line 89 of file iir_cfs.c.
Referenced by calc_coeffs().
#define GAIN_F0 1.0
Definition at line 82 of file iir_cfs.c.
#define GAIN_F1 GAIN_F0 / M_SQRT2
Definition at line 83 of file iir_cfs.c.
#define GAMMA (beta, tf0) ((0.5 + beta) * cos(tf0))
Definition at line 105 of file iir_cfs.c.
Referenced by calc_coeffs().
#define SAMPLING_FREQ 44100.0
Definition at line 85 of file iir_cfs.c.
#define TETA (f) (2*M_PI*(double)f/iir_bands[n].sfreq)
Definition at line 86 of file iir_cfs.c.
Referenced by calc_coeffs().
#define TWOPOWER (value) (value * value)
Definition at line 87 of file iir_cfs.c.
Function Documentation
static sIIRCoefficients iir_cf10_11k_11025 [10] __attribute__ ((aligned)) static
void calc_coeffs ()
Definition at line 206 of file iir_cfs.c.
References ALPHA, BETA0, BETA1, BETA2, cfs, coeffs, find_f1_and_f2(), find_root(), GAMMA, iir_bands, octave, and TETA.
Referenced by eq_init_iir().
static void find_f1_and_f2 (double f0, double octave_percent, double * f1, double * f2) static
Definition at line 183 of file iir_cfs.c.
Referenced by calc_coeffs().
static int find_root (double a, double b, double c, double * x0) static
Definition at line 192 of file iir_cfs.c.
Referenced by calc_coeffs().
sIIRCoefficients* get_coeffs (int * bands, unsigned int sfreq)
Definition at line 139 of file iir_cfs.c.
References iir_cf.
Referenced by eq_init_iir().
Variable Documentation
int band_count
Definition at line 112 of file iir_cfs.c.
const double band_f010[] static
Initial value:
=
{ 31, 62, 125, 250, 500, 1000, 2000, 4000, 8000, 16000
}
Definition at line 64 of file iir_cfs.c.
const double band_f011k[] static
Initial value:
=
{ 31, 62, 125, 250, 500, 1000, 2000, 3000, 4000, 5500
}
Definition at line 58 of file iir_cfs.c.
const double band_f015[] static
Initial value:
=
{ 25,40,63,100,160,250,400,630,1000,1600,2500,4000,6300,10000,16000
}
Definition at line 70 of file iir_cfs.c.
const double band_f022k[] static
Initial value:
=
{ 31, 62, 125, 250, 500, 1000, 2000, 4000, 8000, 11000
}
Definition at line 61 of file iir_cfs.c.
const double band_f025[] static
Initial value:
=
{ 20,31.5,40,50,80,100,125,160,250,315,400,500,800,
  1000,1250,1600,2500,3150,4000,5000,8000,10000,12500,16000,20000
}
Definition at line 73 of file iir_cfs.c.
const double band_f031[] static
Initial value:
=
{ 20,25,31.5,40,50,63,80,100,125,160,200,250,315,400,500,630,800,
  1000,1250,1600,2000,2500,3150,4000,5000,6300,8000,10000,12500,16000,20000
}
Definition at line 77 of file iir_cfs.c.
const double band_original_f010[] static
Initial value:
=
{ 60, 170, 310, 600, 1000, 3000, 6000, 12000, 14000, 16000
}
Definition at line 67 of file iir_cfs.c.
const double* cfs
Definition at line 110 of file iir_cfs.c.
Referenced by calc_coeffs().
sIIRCoefficients* coeffs
Definition at line 109 of file iir_cfs.c.
Referenced by calc_coeffs().
struct { ... } iir_bands[]
Initial value:
= {
  { iir_cf10_11k_11025,     band_f011k,         1.0,     10, 11025.0 },
  { iir_cf10_22k_22050,     band_f022k,         1.0,     10, 22050.0 },
  { iir_cforiginal10_44100, band_original_f010, 1.0,     10, 44100.0 },
  { iir_cforiginal10_48000, band_original_f010, 1.0,     10, 48000.0 },
  { iir_cf10_44100,         band_f010,          1.0,     10, 44100.0 },
  { iir_cf10_48000,         band_f010,          1.0,     10, 48000.0 },
  { iir_cf10_96000,         band_f010,          1.0,     10, 96000.0 },
  { iir_cf15_44100,         band_f015,          2.0/3.0, 15, 44100.0 },
  { iir_cf15_48000,         band_f015,          2.0/3.0, 15, 48000.0 },
  { iir_cf15_96000,         band_f015,          2.0/3.0, 15, 96000.0 },
  { iir_cf25_44100,         band_f025,          1.0/3.0, 25, 44100.0 },
  { iir_cf25_48000,         band_f025,          1.0/3.0, 25, 48000.0 },
  { iir_cf25_96000,         band_f025,          1.0/3.0, 25, 96000.0 },
  { iir_cf31_44100,         band_f031,          1.0/3.0, 31, 44100.0 },
  { iir_cf31_48000,         band_f031,          1.0/3.0, 31, 48000.0 },
  { iir_cf31_96000,         band_f031,          1.0/3.0, 31, 96000.0 },
  { 0, 0, 0, 0, 0 }
}
Referenced by calc_coeffs().
double octave
Definition at line 111 of file iir_cfs.c.
Referenced by calc_coeffs().
double sfreq
Definition at line 113 of file iir_cfs.c.