TTKMusicplayer: MusicPluginWidget Class Reference
MusicPluginWidget Class Reference
The class of the plugin manager widget.
#include <musicpluginwidget.h>
Public Slots
void pluginItemChanged (QTreeWidgetItem *item, int column)
void pluginButtonClicked ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicPluginWidget (QWidget *parent=nullptr)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void loadPluginsInfo ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
Ui::MusicPluginWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the plugin manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicpluginwidget.h.
Constructor & Destructor Documentation
MusicPluginWidget::MusicPluginWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 166 of file musicpluginwidget.cpp.
References loadPluginsInfo(), m_ui, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSComboBoxStyle01, MusicUIObject::MQSSGroupBoxStyle01, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle03, MusicUIObject::MQSSPushButtonStyle13, MusicUIObject::MQSSRadioButtonStyle01, MusicUIObject::MQSSScrollBarStyle03, MusicUIObject::MQSSSliderStyle06, MusicUIObject::MQSSSpinBoxStyle01, MusicUIObject::MQSSToolButtonStyle04, pluginButtonClicked(), pluginItemChanged(), MusicLabelDelegate::setAlignment(), MusicLabelDelegate::setStyleSheet(), MusicCheckBoxDelegate::setTreeModel(), and MusicCheckBoxDelegate::showTextMode().
Member Function Documentation
int MusicPluginWidget::exec () virtual slot
Override exec function.
Definition at line 270 of file musicpluginwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicSettingWidget::otherPluginManagerChanged().
void MusicPluginWidget::loadPluginsInfo () protected
Load plugins info.
Definition at line 276 of file musicpluginwidget.cpp.
References Visual::factories(), Effect::factories(), Output::factories(), InputSource::factories(), Decoder::factories(), Visual::file(), Effect::file(), Output::file(), InputSource::file(), Decoder::file(), and m_ui.
Referenced by MusicPluginWidget().
void MusicPluginWidget::pluginButtonClicked () slot
Plugin item setting button click.
Definition at line 261 of file musicpluginwidget.cpp.
References m_ui, MusicPluginItem::showSettingWidget(), and TTKDynamic_cast.
Referenced by MusicPluginWidget().
void MusicPluginWidget::pluginItemChanged (QTreeWidgetItem * item, int column) slot
Plugin item clicked changed.
Definition at line 227 of file musicpluginwidget.cpp.
References MusicPluginItem::hasSettings(), m_ui, MUSIC_CHECK_ROLE, MusicPluginItem::PDecoder, MusicPluginItem::POutput, MusicPluginItem::PTransports, TTKDynamic_cast, and TTKStatic_cast.
Referenced by MusicPluginWidget().
Member Data Documentation
Ui::MusicPluginWidget* MusicPluginWidget::m_ui protected
Definition at line 62 of file musicpluginwidget.h.
Referenced by exec(), loadPluginsInfo(), MusicPluginWidget(), pluginButtonClicked(), and pluginItemChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.cpp