TTKMusicPlayer: TTKXmlHelper Class Reference
TTKXmlHelper Class Reference
The class of the ttk xml hepler.
#include <ttkabstractxml.h>
Public Member Functions
TTKXmlHelper (const QDomNode &root)
void load ()
bool hasNext ()
QDomNode next () const
QString nodeName (const QString &name) const
Private Attributes
QDomNode m_root
QDomNode m_current
QSet< QString > m_nodeNames
Detailed Description
The class of the ttk xml hepler.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 69 of file ttkabstractxml.h.
Constructor & Destructor Documentation
TTKXmlHelper::TTKXmlHelper (const QDomNode & root) explicit
Object constructor.
Definition at line 5 of file ttkabstractxml.cpp.
Member Function Documentation
bool TTKXmlHelper::hasNext ()
Check xml has next node.
Definition at line 23 of file ttkabstractxml.cpp.
References m_current, and m_root.
Referenced by load().
void TTKXmlHelper::load ()
Load xml helper.
Definition at line 12 of file ttkabstractxml.cpp.
References hasNext(), m_current, and m_nodeNames.
Referenced by MusicASXConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), and MusicWPLConfigManager::readBuffer().
QDomNode TTKXmlHelper::next () const
Get xml next node.
Definition at line 62 of file ttkabstractxml.cpp.
References m_current.
QString TTKXmlHelper::nodeName (const QString & name) const
Get match node name case insensitive.
Definition at line 67 of file ttkabstractxml.cpp.
References m_nodeNames, name, and qAsConst.
Member Data Documentation
QDomNode TTKXmlHelper::m_current private
Definition at line 96 of file ttkabstractxml.h.
Referenced by hasNext(), load(), and next().
QSet<QString> TTKXmlHelper::m_nodeNames private
Definition at line 97 of file ttkabstractxml.h.
Referenced by load(), and nodeName().
QDomNode TTKXmlHelper::m_root private
Definition at line 96 of file ttkabstractxml.h.
Referenced by hasNext().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractxml.h
TTKCommon/TTKLibrary/ttkabstractxml.cpp