TTKMusicplayer: MusicBDPlaylistCommentsThread Class Reference
MusicBDPlaylistCommentsThread Class Reference
The class to baidu query playlist comments download data from net.
#include <musicbdcommentsthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBDPlaylistCommentsThread (QObject *parent=0)
virtual void startToSearch (const QString &name) override
virtual void startToPage (int offset) override
Public Member Functions inherited from MusicDownLoadCommentsThread
MusicDownLoadCommentsThread (QObject *parent=0)
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadCommentsThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadCommentsThread
void createSearchedItem (const MusicResultsItem &comments)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class to baidu query playlist comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 62 of file musicbdcommentsthread.h.
Constructor & Destructor Documentation
MusicBDPlaylistCommentsThread::MusicBDPlaylistCommentsThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 131 of file musicbdcommentsthread.cpp.
References MusicDownLoadPagingThread::m_pageSize.
Member Function Documentation
void MusicBDPlaylistCommentsThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 183 of file musicbdcommentsthread.cpp.
References MusicDownLoadCommentsThread::createSearchedItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicResultsItem::m_nickName, MusicDownLoadPagingThread::m_pageTotal, MusicResultsItem::m_playCount, MusicNetworkAbstract::m_reply, MusicResultsItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToPage().
QString MusicBDPlaylistCommentsThread::getClassName () static
Get class object name.
Definition at line 137 of file musicbdcommentsthread.cpp.
Referenced by downLoadFinished(), startToPage(), and startToSearch().
void MusicBDPlaylistCommentsThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 150 of file musicbdcommentsthread.cpp.
References ALG_UA_KEY, BD_COMMIT_URL, BD_PL_COMMIT_DATA_URL, BD_UA_URL_1, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), QAesWrap::encrypt(), getClassName(), key, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_rawData, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), and MusicUtils::Codec::toUtf8().
Referenced by startToSearch().
void MusicBDPlaylistCommentsThread::startToSearch (const QString & name) override virtual
Start to Search data from name.
Implements MusicDownLoadCommentsThread.
Definition at line 142 of file musicbdcommentsthread.cpp.
References getClassName(), M_LOGGER_INFO, MusicNetworkAbstract::m_rawData, and startToPage().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/bd/musicbdcommentsthread.h
TTKModule/TTKCore/musicNetworkKits/bd/musicbdcommentsthread.cpp