TTKMusicplayer: MusicCoreMPlayer Class Reference
MusicCoreMPlayer Class Reference
The class of the mplayer core.
#include <musiccoremplayer.h>
Public Types
enum Category { NullCategory, RadioCategory, MusicCategory, VideoCategory }
Public Slots
void play ()
void stop ()
Signals
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void mediaChanged (const QString &data)
void finished (int code)
Public Member Functions
MusicCoreMPlayer (QObject *parent=nullptr)
~MusicCoreMPlayer ()
void setMedia (Category type, const QString &data, int winId=-1)
void setPosition (qint64 pos)
void setLeftVolume ()
void setRightVolume ()
void setMultiVoice (int number)
void setMute (bool mute)
void setVolume (int value)
bool isPlaying () const
MusicObject::PlayState state () const
Category category () const
Protected Member Functions
void closeModule ()
void setRadioMedia (const QString &data)
void setMusicMedia (const QString &data)
void setVideoMedia (const QString &data, int winId)
Protected Attributes
QProcess * m_process
MusicObject::PlayState m_playState
Category m_category
QTimer m_timer
QTimer m_checkTimer
Private Slots
void dataRecieve ()
void positionRecieve ()
void durationRecieve ()
void standardRecieve ()
void timeout ()
void checkTimerout ()
Detailed Description
The class of the mplayer core.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musiccoremplayer.h.
Member Enumeration Documentation
enum MusicCoreMPlayer::Category
Enumerator
NullCategory
no category
RadioCategory
radio category
MusicCategory
music category
VideoCategory
video category
Definition at line 35 of file musiccoremplayer.h.
Constructor & Destructor Documentation
MusicCoreMPlayer::MusicCoreMPlayer (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musiccoremplayer.cpp.
References checkTimerout(), m_category, m_checkTimer, m_playState, m_process, m_timer, MT_S2MS, NullCategory, MusicObject::StoppedState, and timeout().
MusicCoreMPlayer::~MusicCoreMPlayer ()
Definition at line 21 of file musiccoremplayer.cpp.
References closeModule().
Member Function Documentation
Category MusicCoreMPlayer::category () const inline
Get current player category.
Definition at line 90 of file musiccoremplayer.h.
void MusicCoreMPlayer::checkTimerout () private slot
Check thread time out.
Definition at line 276 of file musiccoremplayer.cpp.
References DEFAULT_LOW_LEVEL, finished(), m_checkTimer, and m_process.
Referenced by MusicCoreMPlayer().
void MusicCoreMPlayer::closeModule () protected
Close output media module.
Definition at line 56 of file musiccoremplayer.cpp.
References killProcessByName(), m_checkTimer, m_process, m_timer, and MAKE_PLAYER_FULL.
Referenced by setMedia(), and ~MusicCoreMPlayer().
void MusicCoreMPlayer::dataRecieve () private slot
Player data has recieved.
Definition at line 225 of file musiccoremplayer.cpp.
References m_category, MusicCategory, NullCategory, positionRecieve(), RadioCategory, standardRecieve(), and VideoCategory.
Referenced by setMusicMedia(), and setRadioMedia().
void MusicCoreMPlayer::durationChanged (qint64 duration) signal
Current duration changed.
Referenced by durationRecieve(), and standardRecieve().
void MusicCoreMPlayer::durationRecieve () private slot
Player duration data has recieved.
Definition at line 210 of file musiccoremplayer.cpp.
References durationChanged(), and m_process.
Referenced by setVideoMedia().
void MusicCoreMPlayer::finished (int code) signal
Current media is finished.
Referenced by checkTimerout(), and setMedia().
bool MusicCoreMPlayer::isPlaying () const
Get current player is playing or not.
Definition at line 167 of file musiccoremplayer.cpp.
References m_playState, and MusicObject::PlayingState.
Referenced by MusicSongRingtoneMaker::buttonReleaseChanged(), MusicVideoView::createRightMenu(), MusicSongRingtoneMaker::playButtonStateChanged(), and MusicSongRingtoneMaker::playRingtone().
void MusicCoreMPlayer::mediaChanged (const QString & data) signal
Current media data path changed.
Referenced by setMusicMedia(), setRadioMedia(), and setVideoMedia().
void MusicCoreMPlayer::play () slot
Player to play or pause.
Definition at line 172 of file musiccoremplayer.cpp.
References m_checkTimer, m_playState, m_process, m_timer, MusicObject::PausedState, MusicObject::PlayingState, positionRecieve(), and MusicObject::StoppedState.
Referenced by MusicSoundKMicroWidget::mediaUrlChanged(), MusicVideoView::play(), MusicSoundKMicroWidget::playButtonChanged(), MusicSongRingtoneMaker::playInputSong(), MusicSongRingtoneMaker::positionChanged(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), MusicWebFMRadioPlayWidget::radioPlay(), and MusicTTKFMRadioPlayWidget::radioPlay().
void MusicCoreMPlayer::positionChanged (qint64 position) signal
Current position changed.
Referenced by positionRecieve(), and standardRecieve().
void MusicCoreMPlayer::positionRecieve () private slot
Player position data has recieved.
Definition at line 237 of file musiccoremplayer.cpp.
References m_process, m_timer, and positionChanged().
Referenced by dataRecieve(), and play().
void MusicCoreMPlayer::setLeftVolume ()
Set left player volume mode.
Definition at line 117 of file musiccoremplayer.cpp.
References m_process.
Referenced by MusicSoundKMicroWidget::multiMediaChanged().
void MusicCoreMPlayer::setMedia (Category type, const QString & data, int winId = -1)
Set media by type and data path.
Definition at line 26 of file musiccoremplayer.cpp.
References closeModule(), finished(), HTTP_PREFIX, HTTPS_PREFIX, m_category, m_playState, m_process, MAKE_PLAYER_FULL, MusicCategory, NullCategory, RadioCategory, setMusicMedia(), setRadioMedia(), setVideoMedia(), MusicObject::StoppedState, TTK_LOGGER_ERROR, and VideoCategory.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicSongRingtoneMaker::initInputPath(), MusicSoundKMicroWidget::mediaUrlChanged(), MusicIdentifySongsWidget::musicSongPlay(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), MusicVideoView::setMedia(), and MusicTTKFMRadioPlayWidget::startCoreModule().
void MusicCoreMPlayer::setMultiVoice (int number)
Set single voice from multi voice by id.
Definition at line 137 of file musiccoremplayer.cpp.
References m_process.
Referenced by MusicSoundKMicroWidget::multiMediaChanged().
void MusicCoreMPlayer::setMusicMedia (const QString & data) protected
Set player to music media data.
Definition at line 80 of file musiccoremplayer.cpp.
References dataRecieve(), m_process, MAKE_PLAYER_FULL, and mediaChanged().
Referenced by setMedia().
void MusicCoreMPlayer::setMute (bool mute)
Set current player mute or not.
Definition at line 147 of file musiccoremplayer.cpp.
References m_process.
void MusicCoreMPlayer::setPosition (qint64 pos)
Set current play pos.
Definition at line 107 of file musiccoremplayer.cpp.
References m_process.
Referenced by MusicSongRingtoneMaker::buttonReleaseChanged(), MusicSongRingtoneMaker::playRingtone(), MusicSoundKMicroWidget::setPosition(), and MusicVideoView::setPosition().
void MusicCoreMPlayer::setRadioMedia (const QString & data) protected
Set player to radio media data.
Definition at line 70 of file musiccoremplayer.cpp.
References dataRecieve(), m_process, MAKE_PLAYER_FULL, and mediaChanged().
Referenced by setMedia().
void MusicCoreMPlayer::setRightVolume ()
Set right player volume mode.
Definition at line 127 of file musiccoremplayer.cpp.
References m_process.
Referenced by MusicSoundKMicroWidget::multiMediaChanged().
void MusicCoreMPlayer::setVideoMedia (const QString & data, int winId) protected
Set player to video media data.
Definition at line 90 of file musiccoremplayer.cpp.
References durationRecieve(), m_process, MAKE_PLAYER_FULL, and mediaChanged().
Referenced by setMedia().
void MusicCoreMPlayer::setVolume (int value)
Set current player volume.
Definition at line 157 of file musiccoremplayer.cpp.
References m_process.
Referenced by MusicWebFMRadioPlayWidget::radioVolume(), MusicTTKFMRadioPlayWidget::radioVolume(), MusicSoundKMicroWidget::volumeChanged(), and MusicVideoView::volumeChanged().
void MusicCoreMPlayer::standardRecieve () private slot
Player music data has recieved.
Definition at line 251 of file musiccoremplayer.cpp.
References durationChanged(), m_process, and positionChanged().
Referenced by dataRecieve().
MusicObject::PlayState MusicCoreMPlayer::state () const inline
Get current player state.
Definition at line 86 of file musiccoremplayer.h.
Referenced by MusicVideoView::play(), MusicSoundKMicroWidget::playButtonChanged(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicCoreMPlayer::stop () slot
Player to stop.
Definition at line 196 of file musiccoremplayer.cpp.
References m_checkTimer, m_playState, m_process, m_timer, and MusicObject::StoppedState.
Referenced by MusicSoundKMicroWidget::playFinished(), MusicIdentifySongsWidget::reDetectButtonClicked(), and MusicVideoView::stop().
void MusicCoreMPlayer::timeout () private slot
Player one second time out.
Definition at line 270 of file musiccoremplayer.cpp.
References m_process.
Referenced by MusicCoreMPlayer().
Member Data Documentation
Category MusicCoreMPlayer::m_category protected
Definition at line 166 of file musiccoremplayer.h.
Referenced by dataRecieve(), MusicCoreMPlayer(), and setMedia().
QTimer MusicCoreMPlayer::m_checkTimer protected
Definition at line 167 of file musiccoremplayer.h.
Referenced by checkTimerout(), closeModule(), MusicCoreMPlayer(), play(), and stop().
MusicObject::PlayState MusicCoreMPlayer::m_playState protected
Definition at line 165 of file musiccoremplayer.h.
Referenced by isPlaying(), MusicCoreMPlayer(), play(), setMedia(), and stop().
QProcess* MusicCoreMPlayer::m_process protected
Definition at line 164 of file musiccoremplayer.h.
Referenced by checkTimerout(), closeModule(), durationRecieve(), MusicCoreMPlayer(), play(), positionRecieve(), setLeftVolume(), setMedia(), setMultiVoice(), setMusicMedia(), setMute(), setPosition(), setRadioMedia(), setRightVolume(), setVideoMedia(), setVolume(), standardRecieve(), stop(), and timeout().
QTimer MusicCoreMPlayer::m_timer protected
Definition at line 167 of file musiccoremplayer.h.
Referenced by closeModule(), MusicCoreMPlayer(), play(), positionRecieve(), and stop().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musiccoremplayer.h
TTKModule/TTKCore/musicCoreKits/musiccoremplayer.cpp