TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/mqrspec.h File Reference
mqrspec.h File Reference
#include "qrencode.h"
Macros
#define MQRSPEC_WIDTH_MAX 17
Maximum width of a symbol.
#define MQRSPEC_MODEID_NUM 0
Mode indicator.
#define MQRSPEC_MODEID_AN 1
#define MQRSPEC_MODEID_8 2
#define MQRSPEC_MODEID_KANJI 3
Functions
int MQRspec_getDataLengthBit (int version, QRecLevel level)
Return maximum data code length (bits) for the version.
int MQRspec_getDataLength (int version, QRecLevel level)
Return maximum data code length (bytes) for the version.
int MQRspec_getECCLength (int version, QRecLevel level)
Return maximum error correction code length (bytes) for the version.
int MQRspec_getMinimumVersion (int size, QRecLevel level)
Return a version number that satisfies the input code length.
int MQRspec_getWidth (int version)
Return the width of the symbol for the version.
int MQRspec_getRemainder (int version)
Return the numer of remainder bits.
int MQRspec_lengthIndicator (QRencodeMode mode, int version)
Return the size of length indicator for the mode and version.
int MQRspec_maximumWords (QRencodeMode mode, int version)
Return the maximum length for the mode and version.
unsigned int MQRspec_getVersionPattern (int version)
Return BCH encoded version information pattern that is used for the symbol of version 7 or greater.
unsigned int MQRspec_getFormatInfo (int mask, int version, QRecLevel level)
Return BCH encoded format information pattern.
unsigned char * MQRspec_newFrame (int version)
Return a copy of initialized frame.
Macro Definition Documentation
#define MQRSPEC_MODEID_8 2
Definition at line 147 of file mqrspec.h.
Referenced by QRinput_encodeMode8().
#define MQRSPEC_MODEID_AN 1
Definition at line 146 of file mqrspec.h.
Referenced by QRinput_encodeModeAn().
#define MQRSPEC_MODEID_KANJI 3
Definition at line 148 of file mqrspec.h.
Referenced by QRinput_encodeModeKanji().
#define MQRSPEC_MODEID_NUM 0
Mode indicator.
See Table 2 in Appendix 1 of JIS X0510:2004, pp.107.
Definition at line 145 of file mqrspec.h.
Referenced by QRinput_encodeModeNum().
#define MQRSPEC_WIDTH_MAX 17
Maximum width of a symbol.
Definition at line 34 of file mqrspec.h.
Function Documentation
int MQRspec_getDataLength (int version, QRecLevel level)
Return maximum data code length (bytes) for the version.
Parameters
version version of the symbol
level error correction level
Returns
maximum size (bytes)
Definition at line 68 of file mqrspec.c.
References MQRspec_getDataLengthBit().
Referenced by MQRraw_new().
int MQRspec_getDataLengthBit (int version, QRecLevel level)
Return maximum data code length (bits) for the version.
Parameters
version version of the symbol
level error correction level
Returns
maximum size (bits)
Definition at line 57 of file mqrspec.c.
References MQRspec_Capacity::ec, and MQRspec_Capacity::width.
Referenced by MQRraw_new(), MQRspec_getDataLength(), and QRinput_appendPaddingBitMQR().
int MQRspec_getECCLength (int version, QRecLevel level)
Return maximum error correction code length (bytes) for the version.
Parameters
version version of the symbol
level error correction level
Returns
ECC size (bytes)
Definition at line 73 of file mqrspec.c.
References MQRspec_Capacity::ec.
Referenced by MQRraw_new(), QRinput_newMQR(), and QRinput_setVersionAndErrorCorrectionLevel().
unsigned int MQRspec_getFormatInfo (int mask, int version, QRecLevel level)
Return BCH encoded format information pattern.
Parameters
mask mask number
version version of the symbol
level error correction level
Returns
BCH encoded format information pattern
Definition at line 137 of file mqrspec.c.
References formatInfo, MQRSPEC_VERSION_MAX, QR_ECLEVEL_H, and typeTable.
Referenced by MMask_writeFormatInformation().
int MQRspec_getMinimumVersion (int size, QRecLevel level)
Return a version number that satisfies the input code length.
Parameters
size input code length (byte)
level error correction level
Returns
version number
int MQRspec_getRemainder (int version)
Return the numer of remainder bits.
Parameters
version version of the symbol
Returns
number of remainder bits
unsigned int MQRspec_getVersionPattern (int version)
Return BCH encoded version information pattern that is used for the symbol of version 7 or greater.
Use lower 18 bits.
Parameters
version vesion of the symbol
Returns
BCH encoded version information pattern
int MQRspec_getWidth (int version)
Return the width of the symbol for the version.
Parameters
version version of the symbol
Returns
width
Definition at line 78 of file mqrspec.c.
References MQRspec_Capacity::width.
Referenced by MMask_makeMask(), MMask_mask(), and QRcode_encodeMaskMQR().
int MQRspec_lengthIndicator (QRencodeMode mode, int version)
Return the size of length indicator for the mode and version.
Parameters
mode encode mode
version vesion of the symbol
Returns
the size of the appropriate length indicator (bits).
Definition at line 97 of file mqrspec.c.
References lengthTableBits.
Referenced by QRinput_encodeMode8(), QRinput_encodeModeAn(), QRinput_encodeModeKanji(), QRinput_encodeModeNum(), and QRinput_estimateBitStreamSizeOfEntry().
int MQRspec_maximumWords (QRencodeMode mode, int version)
Return the maximum length for the mode and version.
Parameters
mode encode mode
version vesion of the symbol
Returns
the maximum length (bytes)
Definition at line 102 of file mqrspec.c.
References lengthTableBits, and QR_MODE_KANJI.
Referenced by QRinput_encodeBitStream().
unsigned char* MQRspec_newFrame (int version)
Return a copy of initialized frame.
Parameters
version version of the symbol
Returns
Array of unsigned char. You can free it by free().
Definition at line 225 of file mqrspec.c.
References MQRspec_createFrame(), and MQRSPEC_VERSION_MAX.
Referenced by QRcode_encodeMaskMQR().