TTKMusicPlayer: QDlnaFinderPrivate Class Reference
QDlnaFinderPrivate Class Reference
The class of the dlna finder private.
Public Member Functions
QDlnaFinderPrivate ()
~QDlnaFinderPrivate ()
void find ()
void removeClients ()
bool findClient (const QString &server)
Public Member Functions inherited from TTKPrivate< QDlnaFinder >
TTKPrivate ()
virtual ~TTKPrivate ()=default
void setPublic (QDlnaFinder *pub)
Public Attributes
QUdpSocket * m_udpSock
QList< QDlnaClient * > m_clients
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QDlnaFinder >
QDlnaFinder * ttk_q () const
Detailed Description
The class of the dlna finder private.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 12 of file qdlnafinder.cpp.
Constructor & Destructor Documentation
QDlnaFinderPrivate::QDlnaFinderPrivate ()
Definition at line 27 of file qdlnafinder.cpp.
References m_udpSock.
QDlnaFinderPrivate::~QDlnaFinderPrivate ()
Definition at line 33 of file qdlnafinder.cpp.
References m_udpSock, and removeClients().
Member Function Documentation
void QDlnaFinderPrivate::find ()
Definition at line 39 of file qdlnafinder.cpp.
References m_udpSock, and removeClients().
bool QDlnaFinderPrivate::findClient (const QString & server)
Definition at line 55 of file qdlnafinder.cpp.
References m_clients, and qAsConst.
void QDlnaFinderPrivate::removeClients ()
Definition at line 50 of file qdlnafinder.cpp.
References m_clients.
Referenced by find(), and ~QDlnaFinderPrivate().
Member Data Documentation
QList<QDlnaClient*> QDlnaFinderPrivate::m_clients
Definition at line 23 of file qdlnafinder.cpp.
Referenced by findClient(), and removeClients().
QUdpSocket* QDlnaFinderPrivate::m_udpSock
Definition at line 22 of file qdlnafinder.cpp.
Referenced by find(), QDlnaFinderPrivate(), and ~QDlnaFinderPrivate().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qdlna/qdlnafinder.cpp