TTKMusicPlayer: TTK::File Namespace Reference
TTK::File Namespace Reference
Functions
TTK_MODULE_EXPORT QStringList fileListByPath (const QString &dpath, const QStringList &filter={}, bool recursively=true)
TTK_MODULE_EXPORT QFileInfoList fileInfoListByPath (const QString &dpath, const QStringList &filter={}, bool recursively=true)
TTK_MODULE_EXPORT bool copyPath (const QString &srcPath, const QString &dstPath, bool overwrite)
TTK_MODULE_EXPORT bool removeRecursively (const QString &dir, bool self=true)
TTK_MODULE_EXPORT QString getExistingDirectory (QWidget *parent)
TTK_MODULE_EXPORT QString getOpenFileName (QWidget *parent, const QString &filter="Image Files (*.png *.bmp *.jpg)")
TTK_MODULE_EXPORT QStringList getOpenFileNames (QWidget *parent, const QString &filter="Image Files (*.png *.bmp *.jpg)")
TTK_MODULE_EXPORT QString getSaveFileName (QWidget *parent, const QString &filter="Image Files (*.png *.bmp *.jpg)")
Function Documentation
bool TTK::File::copyPath (const QString & srcPath, const QString & dstPath, bool overwrite)
Copy path from srcPath to dstPath.
Definition at line 54 of file musicfileutils.cpp.
References TTK::Core::isBreakPointEnabled().
Referenced by MusicPlaylistBackupWidget::exportButtonClicked().
QFileInfoList TTK::File::fileInfoListByPath (const QString & dpath, const QStringList & filter = {}, bool recursively = true)
Get all files infos in given dir.
Definition at line 34 of file musicfileutils.cpp.
References TTK::Core::isBreakPointEnabled(), and qAsConst.
Referenced by MusicReplayGainWidget::addFilesButtonClicked(), MusicSongsContainerWidget::importSongsByUrl(), MusicConsoleModule::initialize(), and MusicTransformWidget::initInputPath().
QStringList TTK::File::fileListByPath (const QString & dpath, const QStringList & filter = {}, bool recursively = true)
Get all files in given dir.
Definition at line 7 of file musicfileutils.cpp.
References TTK::Core::isBreakPointEnabled(), qAsConst, and TTK_SEPARATOR.
Referenced by MusicSongsContainerWidget::dropEvent(), MusicLocalManagerWidget::refreshItems(), MusicSongsManagerThread::run(), and MusicCloudManagerTableWidget::uploadFileDirToServer().
QString TTK::File::getExistingDirectory (QWidget * parent)
Get open existing directory dialog.
Definition at line 161 of file musicfileutils.cpp.
References G_SETTING_PTR, MusicSettingManager::LastFileDialogPath, and TTK_SEPARATOR.
Referenced by MusicReplayGainWidget::addFilesButtonClicked(), MusicSettingWidget::downloadDirChanged(), MusicPlaylistBackupWidget::exportButtonClicked(), MusicLrcPhotoWidget::exportButtonClicked(), MusicApplication::importSongsByDir(), MusicTransformWidget::initInputPath(), MusicTransformWidget::initOutputPath(), MusicLocalManagerWidget::updateMediaLibraryPath(), and MusicCloudManagerTableWidget::uploadFileDirToServer().
QString TTK::File::getOpenFileName (QWidget * parent, const QString & filter = "Image Files (*.png *.bmp *.jpg)")
Get open file name dialog.
Definition at line 173 of file musicfileutils.cpp.
References G_SETTING_PTR, and MusicSettingManager::LastFileDialogPath.
Referenced by MusicLrcLocalLinkWidget::findInLocalFile(), ToolSkin::imageClicked(), MusicSongRingtoneMaker::initInputPath(), MusicTransformWidget::initInputPath(), MusicLrcPosterWidget::openButtonClicked(), MusicSpectrumWidget::openFileButtonClicked(), MusicFileInformationWidget::openImageFileDir(), ToolSkin::readClicked(), and MusicBackgroundSkinDialog::showCustomSkinDialog().
QStringList TTK::File::getOpenFileNames (QWidget * parent, const QString & filter = "Image Files (*.png *.bmp *.jpg)")
Get open file names dialog.
Definition at line 184 of file musicfileutils.cpp.
References G_SETTING_PTR, and MusicSettingManager::LastFileDialogPath.
Referenced by MusicLrcPhotoWidget::addButtonClicked(), MusicReplayGainWidget::addFileButtonClicked(), MusicApplication::importSongsByFiles(), MusicApplication::importSongsItemList(), and MusicCloudManagerTableWidget::uploadFilesToServer().
QString TTK::File::getSaveFileName (QWidget * parent, const QString & filter = "Image Files (*.png *.bmp *.jpg)")
Get save file name dialog.
Definition at line 199 of file musicfileutils.cpp.
References G_SETTING_PTR, MusicSettingManager::LastFileDialogPath, and TTK::String::suffix().
Referenced by MusicApplication::exportSongsItem(), MusicApplication::exportSongsItemList(), MusicSongRingtoneMaker::initOutputPath(), MusicFileInformationWidget::saveAlbumImage(), MusicLrcPosterWidget::saveButtonClicked(), and ToolSkin::writeClicked().
bool TTK::File::removeRecursively (const QString & dir, bool self = true)
Dir remove recursively.
Definition at line 111 of file musicfileutils.cpp.
References TTK::Core::isBreakPointEnabled().
Referenced by MusicSettingWidget::downloadCacheClean(), and MusicPlaylistBackupModule::runBackup().