TTKMusicplayer: MusicVideoTableWidget Class Reference
MusicVideoTableWidget Class Reference
The class of the video search table widget.
#include <musicvideotablewidget.h>
Public Slots
virtual void listCellEntered (int row, int column) override
virtual void listCellClicked (int row, int column) override
virtual void clearAllItems () override
virtual void createSearchedItems (const MusicSearchedItem &songItem) override
virtual void itemDoubleClicked (int row, int column) override
void getMusicMvInfo (MusicObject::MusicSongAttributes &data)
void downloadLocalFromControl ()
Public Slots inherited from MusicQueryItemTableWidget
virtual void clearAllItems () override
virtual void actionGroupClick (QAction *action)
virtual void itemDoubleClicked (int row, int column)=0
void createFinishedItem ()
Public Slots inherited from MusicQueryTableWidget
virtual void clearAllItems ()=0
virtual void createSearchedItems (const MusicSearchedItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void listCellClicked (int row, int column) override
void setSelectedAllItems (bool all)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void mvURLNameChanged (const MusicVideoItem &item)
Signals inherited from MusicQueryTableWidget
void muiscSongToPlayListChanged (const QString &name, const QString &time, const QString &format, bool play)
void showDownLoadInfoFor (MusicObject::DownLoadMode type)
void restartSearchQuery (const QString &name)
Public Member Functions
MusicVideoTableWidget (QWidget *parent=0)
virtual ~MusicVideoTableWidget ()
virtual void startSearchQuery (const QString &text) override
void startSearchSingleQuery (const QString &text)
virtual void musicDownloadLocal (int row) override
void resizeWindow (int delta)
Public Member Functions inherited from MusicQueryItemTableWidget
MusicQueryItemTableWidget (QWidget *parent=0)
virtual ~MusicQueryItemTableWidget ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=0)
virtual ~MusicQueryTableWidget ()
virtual void setQueryInput (MusicDownLoadQueryThreadAbstract *query)
MusicDownLoadQueryThreadAbstract * getQueryInput ()
const MusicObject::MusicSongInformations & getMusicSongInfos () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=0)
virtual ~MusicFillItemTableWidget ()
MusicObject::MIntList getSelectedItems () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicQueryItemTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicQueryTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicFillItemTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
void downloadLocalMovie (int row)
Protected Member Functions inherited from MusicQueryItemTableWidget
void createContextMenu (QMenu &menu)
virtual void resizeEvent (QResizeEvent *event) override
QString randToGetStrength () const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
QString m_currentSongName
Protected Attributes inherited from MusicQueryItemTableWidget
MusicGifLabelWidget * m_loadingLabel
QActionGroup * m_actionGroup
MusicLabelDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicDownLoadQueryThreadAbstract * m_downLoadManager
Protected Attributes inherited from MusicFillItemTableWidget
MusicQueryTableDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the video search table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 40 of file musicvideotablewidget.h.
Constructor & Destructor Documentation
MusicVideoTableWidget::MusicVideoTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 10 of file musicvideotablewidget.cpp.
References getClassName(), M_CONNECTION_PTR, resizeWindow(), and MusicTime::timeSRand().
MusicVideoTableWidget::~MusicVideoTableWidget () virtual
Definition at line 20 of file musicvideotablewidget.cpp.
References clearAllItems(), getClassName(), and M_CONNECTION_PTR.
Member Function Documentation
void MusicVideoTableWidget::clearAllItems () override virtual slot
Clear All Items.
Definition at line 134 of file musicvideotablewidget.cpp.
References MusicQueryItemTableWidget::clearAllItems().
Referenced by startSearchQuery(), startSearchSingleQuery(), and ~MusicVideoTableWidget().
void MusicVideoTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicQueryTableWidget.
Definition at line 235 of file musicvideotablewidget.cpp.
References MusicQueryTableWidget::contextMenuEvent(), and MusicQueryItemTableWidget::createContextMenu().
void MusicVideoTableWidget::createSearchedItems (const MusicSearchedItem & songItem) override virtual slot
Create searched items.
Definition at line 140 of file musicvideotablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSearchedItem::m_singerName, MusicSearchedItem::m_songName, MusicSearchedItem::m_time, MusicSearchedItem::m_type, MUSIC_CHECK_ROLE, and MusicQueryItemTableWidget::randToGetStrength().
void MusicVideoTableWidget::downloadLocalFromControl () slot
Download current mv by controller.
Definition at line 227 of file musicvideotablewidget.cpp.
References downloadLocalMovie(), and MusicAbstractTableWidget::m_previousClickRow.
Referenced by MusicVideoPlayWidget::downloadButtonClicked().
void MusicVideoTableWidget::downloadLocalMovie (int row) protected
Download movie to local file by index.
Definition at line 244 of file musicvideotablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicQueryTableWidget::m_downLoadManager, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicDownloadWidget::setSongName(), and MusicDownloadWidget::show().
Referenced by downloadLocalFromControl(), and musicDownloadLocal().
QString MusicVideoTableWidget::getClassName () static
Get class object name.
Definition at line 26 of file musicvideotablewidget.cpp.
Referenced by MusicVideoQualityPopWidget::MusicVideoQualityPopWidget(), MusicVideoTableWidget(), MusicConnectionPool::poolConnect(), and ~MusicVideoTableWidget().
void MusicVideoTableWidget::getMusicMvInfo (MusicObject::MusicSongAttributes & data) slot
Get music mv information data.
Definition at line 216 of file musicvideotablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicQueryTableWidget::m_downLoadManager, and MusicAbstractTableWidget::m_previousClickRow.
void MusicVideoTableWidget::itemDoubleClicked (int row, int column) override virtual slot
Item has double clicked.
Definition at line 194 of file musicvideotablewidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicDownLoadQueryThreadAbstract::getQueryServer(), MusicQueryTableWidget::m_downLoadManager, MusicVideoItem::m_id, MusicObject::MusicSongAttribute::m_multiParts, MusicVideoItem::m_name, MusicVideoItem::m_server, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicVideoItem::m_url, MusicObject::MusicSongAttribute::m_url, mvURLNameChanged(), and STRING_SPLITER.
Referenced by listCellClicked().
void MusicVideoTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 118 of file musicvideotablewidget.cpp.
References itemDoubleClicked(), MusicFillItemTableWidget::listCellClicked(), and musicDownloadLocal().
void MusicVideoTableWidget::listCellEntered (int row, int column) override virtual slot
Table widget list cell enter.
Definition at line 105 of file musicvideotablewidget.cpp.
References MusicAbstractTableWidget::listCellEntered().
void MusicVideoTableWidget::musicDownloadLocal (int row) override virtual
Data download to local file.
Implements MusicQueryTableWidget.
Definition at line 68 of file musicvideotablewidget.cpp.
References downloadLocalMovie(), MusicMessageBox::exec(), and MusicMessageBox::setText().
Referenced by listCellClicked().
void MusicVideoTableWidget::mvURLNameChanged (const MusicVideoItem & item) signal
Set current media name and url to play.
Referenced by itemDoubleClicked().
void MusicVideoTableWidget::resizeWindow (int delta)
Resize widget size by delta.
Definition at line 80 of file musicvideotablewidget.cpp.
References MusicUtils::Widget::elidedText().
Referenced by MusicVideoTableWidget(), and MusicVideoPlayWidget::resizeWindow().
void MusicVideoTableWidget::startSearchQuery (const QString & text) override virtual
Start search query by text.
Reimplemented from MusicQueryItemTableWidget.
Definition at line 31 of file musicvideotablewidget.cpp.
References clearAllItems(), MusicQueryItemTableWidget::createFinishedItem(), MusicObject::DW_DisConnection, M_DOWNLOAD_QUERY_PTR, MusicQueryTableWidget::m_downLoadManager, MusicQueryItemTableWidget::m_loadingLabel, M_NETWORK_PTR, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicQueryTableWidget::setQueryInput(), MusicQueryTableWidget::showDownLoadInfoFor(), MusicGifLabelWidget::start(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicVideoPlayWidget::videoResearchButtonSearched().
void MusicVideoTableWidget::startSearchSingleQuery (const QString & text)
Start search query by given id.
Definition at line 49 of file musicvideotablewidget.cpp.
References clearAllItems(), MusicQueryItemTableWidget::createFinishedItem(), MusicObject::DW_DisConnection, M_DOWNLOAD_QUERY_PTR, MusicQueryTableWidget::m_downLoadManager, MusicQueryItemTableWidget::m_loadingLabel, M_NETWORK_PTR, MusicDownLoadQueryThreadAbstract::MovieQuery, MusicQueryTableWidget::setQueryInput(), MusicDownLoadQueryThreadAbstract::setQueryType(), MusicQueryTableWidget::showDownLoadInfoFor(), MusicGifLabelWidget::start(), and MusicDownLoadQueryThreadAbstract::startToSingleSearch().
Referenced by MusicVideoPlayWidget::startSearchSingleQuery().
Member Data Documentation
QString MusicVideoTableWidget::m_currentSongName protected
Definition at line 118 of file musicvideotablewidget.h.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideotablewidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideotablewidget.cpp