TTKMusicplayer: MusicIdentifySongsWidget Class Reference
MusicIdentifySongsWidget Class Reference
The class of the song identify widget.
#include <musicidentifysongswidget.h>
Public Slots
void detectedButtonClicked ()
void reDetectButtonClicked ()
void detectedTimeOut ()
void musicSongPlay ()
void musicSongDownload ()
void musicSongShare ()
void positionChanged (qint64 position)
Public Member Functions
MusicIdentifySongsWidget (QWidget *parent=0)
~MusicIdentifySongsWidget ()
void getKey ()
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
void createDetectedWidget ()
void createDetectedSuccessedWidget ()
void createDetectedFailedWidget ()
Protected Attributes
QTimer * m_timer
QStackedWidget * m_mainWindow
QLabel * m_detectedLabel
QLabel * m_lrcLabel
QMovie * m_detectedMovie
QPushButton * m_detectedButton
MusicCoreMPlayer * m_songPlayer
MusicLrcAnalysis * m_analysis
MusicAudioRecorderCore * m_recordCore
MusicIdentifySongsThread * m_detectedThread
MusicObject::MusicSongInformation m_currentSong
Detailed Description
The class of the song identify widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicidentifysongswidget.h.
Constructor & Destructor Documentation
MusicIdentifySongsWidget::MusicIdentifySongsWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 23 of file musicidentifysongswidget.cpp.
References createDetectedWidget(), detectedButtonClicked(), detectedTimeOut(), m_analysis, m_detectedButton, m_detectedThread, m_lrcLabel, m_mainWindow, m_recordCore, m_songPlayer, m_timer, MusicUIObject::MBackgroundStyle17, and MT_S2MS.
MusicIdentifySongsWidget::~MusicIdentifySongsWidget ()
Definition at line 53 of file musicidentifysongswidget.cpp.
References m_analysis, m_detectedButton, m_detectedLabel, m_detectedMovie, m_detectedThread, m_mainWindow, m_recordCore, m_songPlayer, and m_timer.
Member Function Documentation
void MusicIdentifySongsWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 218 of file musicidentifysongswidget.cpp.
void MusicIdentifySongsWidget::createDetectedFailedWidget () protected
Create the detected failed widget.
Definition at line 420 of file musicidentifysongswidget.cpp.
References m_mainWindow, MusicUIObject::MColorStyle03, MusicUIObject::MFontStyle03, MusicUIObject::MFontStyle05, MusicUIObject::MKGSongsRedetectBtn, and reDetectButtonClicked().
Referenced by detectedTimeOut().
void MusicIdentifySongsWidget::createDetectedSuccessedWidget () protected
Create the detected successed widget.
Definition at line 262 of file musicidentifysongswidget.cpp.
References ART_DIR_FULL, MusicDownLoadThreadAbstract::Download_Lrc, MusicDownLoadThreadAbstract::Download_SmlBG, MusicSemaphoreLoop::exec(), MusicIdentifySongsThread::getIdentifySongs(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), LRC_FILE, MusicUtils::Core::lrcPrefix(), m_analysis, m_currentSong, m_detectedThread, M_DOWNLOAD_QUERY_PTR, m_lrcLabel, MusicObject::MusicSongInformation::m_lrcUrl, m_mainWindow, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songName, m_songPlayer, MusicUIObject::MColorStyle03, MusicUIObject::MFontStyle03, MusicUIObject::MFontStyle05, MusicUIObject::MKGSongsDetectDownloadBtn, MusicUIObject::MKGSongsDetectPlayBtn, MusicUIObject::MKGSongsDetectShareBtn, MusicUIObject::MKGSongsDetectUnloveBtn, MusicUIObject::MKGSongsRedetectBtn, MusicCoreMPlayer::MusicCategory, MusicDownLoadQueryThreadAbstract::MusicQuery, musicSongDownload(), musicSongPlay(), musicSongShare(), positionChanged(), reDetectButtonClicked(), MusicLrcAnalysis::setLineMax(), MusicCoreMPlayer::setMedia(), SKN_FILE, MusicDataDownloadThread::startToDownload(), MusicDownLoadThreadAbstract::startToDownload(), MusicDownLoadQueryThreadAbstract::startToSearch(), and MusicLrcAnalysis::transLrcFileToTime().
Referenced by detectedTimeOut().
void MusicIdentifySongsWidget::createDetectedWidget () protected
Create the detected widget.
Definition at line 223 of file musicidentifysongswidget.cpp.
References detectedButtonClicked(), m_detectedButton, m_detectedLabel, m_detectedMovie, m_mainWindow, MusicUIObject::MColorStyle03, MusicUIObject::MFontStyle03, MusicUIObject::MFontStyle05, and MusicUIObject::MKGSongsDetectStartBtn.
Referenced by MusicIdentifySongsWidget().
void MusicIdentifySongsWidget::detectedButtonClicked () slot
Detected the song button clicked.
Definition at line 87 of file musicidentifysongswidget.cpp.
References MusicAudioRecorderCore::error(), m_detectedButton, m_detectedLabel, m_detectedMovie, m_recordCore, m_timer, MusicUIObject::MKGSongsDetectStartBtn, MusicUIObject::MKGSongsDetectStopBtn, MusicAudioRecorderCore::onRecordStart(), and MusicAudioRecorderCore::onRecordStop().
Referenced by createDetectedWidget(), detectedTimeOut(), and MusicIdentifySongsWidget().
void MusicIdentifySongsWidget::detectedTimeOut () slot
Detected the song finished.
Definition at line 126 of file musicidentifysongswidget.cpp.
References MusicAudioRecorderCore::addWavHeader(), createDetectedFailedWidget(), createDetectedSuccessedWidget(), detectedButtonClicked(), MusicSemaphoreLoop::exec(), MusicIdentifySongsThread::getIdentifySongs(), m_detectedThread, m_recordCore, MUSIC_RECORD_IN_FILE, and MusicIdentifySongsThread::startToDownload().
Referenced by MusicIdentifySongsWidget().
QString MusicIdentifySongsWidget::getClassName () static
Get class object name.
Definition at line 66 of file musicidentifysongswidget.cpp.
void MusicIdentifySongsWidget::getKey ()
Get query song id keys.
Definition at line 71 of file musicidentifysongswidget.cpp.
References MusicIdentifySongsThread::getKey(), m_detectedButton, m_detectedThread, MusicToastLabel::popup(), MusicToastLabel::setFontMargin(), MusicToastLabel::setFontSize(), and MusicToastLabel::setText().
Referenced by MusicRightAreaWidget::musicFunctionClicked().
void MusicIdentifySongsWidget::musicSongDownload () slot
Set music song to download.
Definition at line 159 of file musicidentifysongswidget.cpp.
References m_currentSong, MusicObject::MusicSongInformation::m_singerName, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownloadWidget::setSongName(), and MusicDownloadWidget::show().
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongsWidget::musicSongPlay () slot
Set music song to play.
Definition at line 146 of file musicidentifysongswidget.cpp.
References m_currentSong, MusicObject::MusicSongInformation::m_songAttrs, m_songPlayer, MusicCoreMPlayer::MusicCategory, and MusicCoreMPlayer::setMedia().
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongsWidget::musicSongShare () slot
Set music song to share.
Definition at line 169 of file musicidentifysongswidget.cpp.
References MusicSongSharingWidget::exec(), m_currentSong, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, MusicSongSharingWidget::setData(), and MusicSongSharingWidget::Song.
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongsWidget::positionChanged (qint64 position) slot
Current position changed.
Definition at line 182 of file musicidentifysongswidget.cpp.
References MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), MusicLrcAnalysis::isEmpty(), m_analysis, m_lrcLabel, m_songPlayer, MT_S2MS, and MusicLrcAnalysis::setCurrentIndex().
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongsWidget::reDetectButtonClicked () slot
Retected the song button clicked.
Definition at line 117 of file musicidentifysongswidget.cpp.
References IDENTIFY_SONGS_INDEX_0, m_mainWindow, m_songPlayer, and MusicCoreMPlayer::stop().
Referenced by createDetectedFailedWidget(), and createDetectedSuccessedWidget().
Member Data Documentation
MusicLrcAnalysis* MusicIdentifySongsWidget::m_analysis protected
Definition at line 111 of file musicidentifysongswidget.h.
Referenced by createDetectedSuccessedWidget(), MusicIdentifySongsWidget(), positionChanged(), and ~MusicIdentifySongsWidget().
MusicObject::MusicSongInformation MusicIdentifySongsWidget::m_currentSong protected
Definition at line 114 of file musicidentifysongswidget.h.
Referenced by createDetectedSuccessedWidget(), musicSongDownload(), musicSongPlay(), and musicSongShare().
QPushButton* MusicIdentifySongsWidget::m_detectedButton protected
Definition at line 109 of file musicidentifysongswidget.h.
Referenced by createDetectedWidget(), detectedButtonClicked(), getKey(), MusicIdentifySongsWidget(), and ~MusicIdentifySongsWidget().
QLabel* MusicIdentifySongsWidget::m_detectedLabel protected
Definition at line 107 of file musicidentifysongswidget.h.
Referenced by createDetectedWidget(), detectedButtonClicked(), and ~MusicIdentifySongsWidget().
QMovie* MusicIdentifySongsWidget::m_detectedMovie protected
Definition at line 108 of file musicidentifysongswidget.h.
Referenced by createDetectedWidget(), detectedButtonClicked(), and ~MusicIdentifySongsWidget().
MusicIdentifySongsThread* MusicIdentifySongsWidget::m_detectedThread protected
Definition at line 113 of file musicidentifysongswidget.h.
Referenced by createDetectedSuccessedWidget(), detectedTimeOut(), getKey(), MusicIdentifySongsWidget(), and ~MusicIdentifySongsWidget().
QLabel * MusicIdentifySongsWidget::m_lrcLabel protected
Definition at line 107 of file musicidentifysongswidget.h.
Referenced by createDetectedSuccessedWidget(), MusicIdentifySongsWidget(), and positionChanged().
QStackedWidget* MusicIdentifySongsWidget::m_mainWindow protected
Definition at line 106 of file musicidentifysongswidget.h.
Referenced by createDetectedFailedWidget(), createDetectedSuccessedWidget(), createDetectedWidget(), MusicIdentifySongsWidget(), reDetectButtonClicked(), and ~MusicIdentifySongsWidget().
MusicAudioRecorderCore* MusicIdentifySongsWidget::m_recordCore protected
Definition at line 112 of file musicidentifysongswidget.h.
Referenced by detectedButtonClicked(), detectedTimeOut(), MusicIdentifySongsWidget(), and ~MusicIdentifySongsWidget().
MusicCoreMPlayer* MusicIdentifySongsWidget::m_songPlayer protected
Definition at line 110 of file musicidentifysongswidget.h.
Referenced by createDetectedSuccessedWidget(), MusicIdentifySongsWidget(), musicSongPlay(), positionChanged(), reDetectButtonClicked(), and ~MusicIdentifySongsWidget().
QTimer* MusicIdentifySongsWidget::m_timer protected
Definition at line 105 of file musicidentifysongswidget.h.
Referenced by detectedButtonClicked(), MusicIdentifySongsWidget(), and ~MusicIdentifySongsWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicidentifysongswidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicidentifysongswidget.cpp