TTKMusicPlayer: QJsonArray Class Reference
QJsonArray Class Reference
#include <QJsonArray.h>
Public Types
typedef QList< QJsonValue >::const_iterator const_iterator
typedef QList< QJsonValue >::iterator iterator
typedef const_iterator ConstIterator
typedef iterator Iterator
typedef QList< QJsonValue >::const_pointer const_pointer
typedef QList< QJsonValue >::const_reference const_reference
typedef QList< QJsonValue >::difference_type difference_type
typedef QList< QJsonValue >::pointer pointer
typedef QList< QJsonValue >::reference reference
typedef QList< QJsonValue >::size_type size_type
typedef QList< QJsonValue >::value_type value_type
Public Member Functions
QJsonArray ()
QJsonArray (const QJsonArray &other)
~QJsonArray ()
QJsonArray & operator= (const QJsonArray &other)
bool operator!= (const QJsonArray &other) const
bool operator== (const QJsonArray &other) const
QJsonArray operator+ (const QJsonValue &value) const
QJsonArray & operator+= (const QJsonValue &value)
QJsonArray & operator<< (const QJsonValue &value)
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
const_iterator constBegin () const
const_iterator constEnd () const
QJsonValueRef operator[] (int i)
QJsonValue operator[] (int i) const
QJsonValue at (int i) const
QJsonValue first () const
QJsonValue last () const
int size () const
int count () const
bool empty () const
bool isEmpty () const
void pop_back ()
void pop_front ()
void push_back (const QJsonValue &value)
void push_front (const QJsonValue &value)
void append (const QJsonValue &value)
bool contains (const QJsonValue &value) const
iterator erase (iterator it)
void insert (int i, const QJsonValue &value)
iterator insert (iterator before, const QJsonValue &value)
void prepend (const QJsonValue &value)
void removeAt (int i)
void removeFirst ()
void removeLast ()
void replace (int i, const QJsonValue &value)
QJsonValue takeAt (int i)
QVariantList toVariantList () const
Public Member Functions inherited from QJsonRoot
virtual ~QJsonRoot ()
Static Public Member Functions
static QJsonArray fromStringList (const QStringList &list)
static QJsonArray fromVariantList (const QVariantList &list)
Private Member Functions
virtual QJsonRoot * clone () const
virtual QJsonArray * toArray ()
virtual QJsonObject * toObject ()
virtual const QJsonArray * toArray () const
virtual const QJsonObject * toObject () const
void swap (QJsonArray &other)
Private Attributes
QList< QJsonValue > values_
Friends
class QJsonDocument
class QJsonValue
class QJsonValueRef
class QJsonParser
Detailed Description
Definition at line 35 of file QJsonArray.h.
Member Typedef Documentation
typedef QList<QJsonValue>::const_iterator QJsonArray::const_iterator
Definition at line 46 of file QJsonArray.h.
typedef QList<QJsonValue>::const_pointer QJsonArray::const_pointer
Definition at line 50 of file QJsonArray.h.
typedef QList<QJsonValue>::const_reference QJsonArray::const_reference
Definition at line 51 of file QJsonArray.h.
typedef const_iterator QJsonArray::ConstIterator
Definition at line 48 of file QJsonArray.h.
typedef QList<QJsonValue>::difference_type QJsonArray::difference_type
Definition at line 52 of file QJsonArray.h.
typedef QList<QJsonValue>::iterator QJsonArray::iterator
Definition at line 47 of file QJsonArray.h.
typedef iterator QJsonArray::Iterator
Definition at line 49 of file QJsonArray.h.
typedef QList<QJsonValue>::pointer QJsonArray::pointer
Definition at line 53 of file QJsonArray.h.
typedef QList<QJsonValue>::reference QJsonArray::reference
Definition at line 54 of file QJsonArray.h.
typedef QList<QJsonValue>::size_type QJsonArray::size_type
Definition at line 55 of file QJsonArray.h.
typedef QList<QJsonValue>::value_type QJsonArray::value_type
Definition at line 56 of file QJsonArray.h.
Constructor & Destructor Documentation
QJsonArray::QJsonArray ()
Definition at line 31 of file QJsonArray.cpp.
Referenced by clone(), and operator=().
QJsonArray::QJsonArray (const QJsonArray & other)
Definition at line 39 of file QJsonArray.cpp.
QJsonArray::~QJsonArray ()
Definition at line 59 of file QJsonArray.cpp.
Member Function Documentation
void QJsonArray::append (const QJsonValue & value)
Definition at line 262 of file QJsonArray.cpp.
References values_.
Referenced by operator+().
QJsonValue QJsonArray::at (int i) const
Definition at line 199 of file QJsonArray.cpp.
References values_.
QJsonArray::const_iterator QJsonArray::begin () const
Definition at line 120 of file QJsonArray.cpp.
References values_.
Referenced by constBegin(), and QJsonDocument::toJson().
QJsonArray::iterator QJsonArray::begin ()
Definition at line 136 of file QJsonArray.cpp.
References values_.
QJsonRoot * QJsonArray::clone () const private virtual
Implements QJsonRoot.
Definition at line 372 of file QJsonArray.cpp.
References QJsonArray().
Referenced by QJsonValue::QJsonValue().
QJsonArray::const_iterator QJsonArray::constBegin () const
Definition at line 152 of file QJsonArray.cpp.
References begin().
QJsonArray::const_iterator QJsonArray::constEnd () const
Definition at line 160 of file QJsonArray.cpp.
References end().
bool QJsonArray::contains (const QJsonValue & value) const
Definition at line 269 of file QJsonArray.cpp.
References values_.
int QJsonArray::count () const
Definition at line 213 of file QJsonArray.cpp.
References size().
bool QJsonArray::empty () const
Definition at line 220 of file QJsonArray.cpp.
References values_.
Referenced by first(), isEmpty(), last(), and QJsonDocument::toJson().
QJsonArray::const_iterator QJsonArray::end () const
Definition at line 128 of file QJsonArray.cpp.
References values_.
Referenced by constEnd(), and QJsonDocument::toJson().
QJsonArray::iterator QJsonArray::end ()
Definition at line 144 of file QJsonArray.cpp.
References values_.
QJsonArray::iterator QJsonArray::erase (iterator it)
Definition at line 276 of file QJsonArray.cpp.
References values_.
QJsonValue QJsonArray::first () const
Definition at line 168 of file QJsonArray.cpp.
References empty(), and values_.
QJsonArray QJsonArray::fromStringList (const QStringList & list) static
Definition at line 350 of file QJsonArray.cpp.
References push_back(), and QJsonValue.
Referenced by QJsonDocument::fromVariant(), and QJsonValue::fromVariant().
QJsonArray QJsonArray::fromVariantList (const QVariantList & list) static
Definition at line 361 of file QJsonArray.cpp.
References QJsonValue::fromVariant(), and push_back().
Referenced by QJsonDocument::fromVariant(), and QJsonValue::fromVariant().
void QJsonArray::insert (int i, const QJsonValue & value)
Definition at line 283 of file QJsonArray.cpp.
References values_.
QJsonArray::iterator QJsonArray::insert (iterator before, const QJsonValue & value)
Definition at line 290 of file QJsonArray.cpp.
References values_.
bool QJsonArray::isEmpty () const
Definition at line 227 of file QJsonArray.cpp.
References empty().
QJsonValue QJsonArray::last () const
Definition at line 177 of file QJsonArray.cpp.
References empty(), and values_.
bool QJsonArray::operator!= (const QJsonArray & other) const
Definition at line 104 of file QJsonArray.cpp.
References values_.
QJsonArray QJsonArray::operator+ (const QJsonValue & value) const
Definition at line 94 of file QJsonArray.cpp.
References append().
QJsonArray & QJsonArray::operator+= (const QJsonValue & value)
Definition at line 76 of file QJsonArray.cpp.
References values_.
QJsonArray & QJsonArray::operator<< (const QJsonValue & value)
Definition at line 85 of file QJsonArray.cpp.
References values_.
QJsonArray & QJsonArray::operator= (const QJsonArray & other)
Definition at line 67 of file QJsonArray.cpp.
References QJsonArray().
bool QJsonArray::operator== (const QJsonArray & other) const
Definition at line 112 of file QJsonArray.cpp.
References values_.
QJsonValueRef QJsonArray::operator[] (int i)
Definition at line 185 of file QJsonArray.cpp.
References QJsonValueRef.
QJsonValue QJsonArray::operator[] (int i) const
Definition at line 192 of file QJsonArray.cpp.
References values_.
void QJsonArray::pop_back ()
Definition at line 234 of file QJsonArray.cpp.
References values_.
void QJsonArray::pop_front ()
Definition at line 241 of file QJsonArray.cpp.
References values_.
void QJsonArray::prepend (const QJsonValue & value)
Definition at line 297 of file QJsonArray.cpp.
References values_.
void QJsonArray::push_back (const QJsonValue & value)
Definition at line 248 of file QJsonArray.cpp.
References values_.
Referenced by fromStringList(), and fromVariantList().
void QJsonArray::push_front (const QJsonValue & value)
Definition at line 255 of file QJsonArray.cpp.
References values_.
void QJsonArray::removeAt (int i)
Definition at line 304 of file QJsonArray.cpp.
References values_.
void QJsonArray::removeFirst ()
Definition at line 311 of file QJsonArray.cpp.
References values_.
void QJsonArray::removeLast ()
Definition at line 318 of file QJsonArray.cpp.
References values_.
void QJsonArray::replace (int i, const QJsonValue & value)
Definition at line 325 of file QJsonArray.cpp.
References values_.
int QJsonArray::size () const
Definition at line 206 of file QJsonArray.cpp.
References values_.
Referenced by count().
void QJsonArray::swap (QJsonArray & other) private
Definition at line 407 of file QJsonArray.cpp.
References values_.
QJsonValue QJsonArray::takeAt (int i)
Definition at line 332 of file QJsonArray.cpp.
References values_.
QJsonArray * QJsonArray::toArray () private virtual
Implements QJsonRoot.
Definition at line 393 of file QJsonArray.cpp.
const QJsonArray * QJsonArray::toArray () const private virtual
Implements QJsonRoot.
Definition at line 400 of file QJsonArray.cpp.
QJsonObject * QJsonArray::toObject () private virtual
Implements QJsonRoot.
Definition at line 386 of file QJsonArray.cpp.
const QJsonObject * QJsonArray::toObject () const private virtual
Implements QJsonRoot.
Definition at line 379 of file QJsonArray.cpp.
QVariantList QJsonArray::toVariantList () const
Definition at line 339 of file QJsonArray.cpp.
References QJsonValue::toVariant().
Referenced by QJsonDocument::toVariant(), and QJsonValue::toVariant().
Friends And Related Function Documentation
friend class QJsonDocument friend
Definition at line 36 of file QJsonArray.h.
friend class QJsonParser friend
Definition at line 39 of file QJsonArray.h.
friend class QJsonValue friend
Definition at line 37 of file QJsonArray.h.
Referenced by fromStringList().
friend class QJsonValueRef friend
Definition at line 38 of file QJsonArray.h.
Referenced by operator[]().
Member Data Documentation
QList<QJsonValue> QJsonArray::values_ private
Definition at line 134 of file QJsonArray.h.
Referenced by append(), at(), begin(), contains(), empty(), end(), erase(), first(), insert(), last(), operator!=(), operator+=(), operator<<(), operator==(), operator[](), pop_back(), pop_front(), prepend(), push_back(), push_front(), removeAt(), removeFirst(), removeLast(), replace(), size(), swap(), and takeAt().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/QJsonArray.h
TTKThirdParty/TTKExtras/qjson/QJsonArray.cpp