TTKMusicPlayer: TTKGuiApplication Class Reference
TTKGuiApplication Class Reference
The class of the ttk gui application.
#include <ttkguiapplication.h>
Public Slots
bool sendMessage (const QString &message, int timeout=5000)
Signals
void messageReceived (const QString &message)
Public Member Functions
TTKGuiApplication (int &argc, char **argv)
TTKGuiApplication (const QString &id, int &argc, char **argv)
bool isRunning () const
QString id () const
Private Member Functions
void initialize (const QString &id={})
Detailed Description
The class of the ttk gui application.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttkguiapplication.h.
Constructor & Destructor Documentation
TTKGuiApplication::TTKGuiApplication (int & argc, char ** argv)
Object constructor.
Definition at line 31 of file ttkguiapplication.cpp.
References initialize(), and TTK_INIT_PRIVATE.
TTKGuiApplication::TTKGuiApplication (const QString & id, int & argc, char ** argv)
Definition at line 38 of file ttkguiapplication.cpp.
References initialize(), and TTK_INIT_PRIVATE.
Member Function Documentation
QString TTKGuiApplication::id () const
Get current server id.
Definition at line 51 of file ttkguiapplication.cpp.
References TTK_D.
void TTKGuiApplication::initialize (const QString & id = {}) private
Init the system parameter.
Definition at line 63 of file ttkguiapplication.cpp.
References messageReceived(), and TTK_D.
Referenced by TTKGuiApplication().
bool TTKGuiApplication::isRunning () const
Check the current server is running or not.
Definition at line 45 of file ttkguiapplication.cpp.
References TTK_D.
void TTKGuiApplication::messageReceived (const QString & message) signal
Emit when the current message received.
Referenced by initialize().
bool TTKGuiApplication::sendMessage (const QString & message, int timeout = 5000) slot
Emit when the current message received.
Definition at line 57 of file ttkguiapplication.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKCommon/TTKApplication/ttkguiapplication.h
TTKCommon/TTKApplication/ttkguiapplication.cpp