TTKMusicPlayer: TTK Namespace Reference
TTK Namespace Reference
The namespace of the application object.
Namespaces
Algorithm
Core
File
Image
Number
String
TTKQmmp
UI
Url
Widget
Classes
struct IndexProperty
The class of the index property.
struct MusicArtistProperty
The class of the music artist property.
struct MusicSongInformation
The class of the music song information.
struct MusicSongProperty
The class of the music song property.
Typedefs
template<typename T >
using remove_cvr = typename std::remove_cv< typename std::remove_reference< T >::type >::type
Enumerations
enum NetworkCode { NetworkCode::Query = 0xFF00, NetworkCode::Success = 0, NetworkCode::Error = -1, NetworkCode::UnKnow = 2 }
enum ScopeGuardOnExit
enum Attribute {
UseLog = 0x0001, ScaleFactor = 0x0002, UseXCB = 0x0004, DisbaleFFmpeg = 0x0008,
All = 0x000F
}
enum Direction {
Direction::No = 0, Direction::Left = 1, Direction::Top = 2, Direction::Right = 4,
Direction::Bottom = 8, Direction::LeftTop = Direction::Left | Direction::Top, Direction::LeftBottom = Direction::Left | Direction::Bottom, Direction::RightTop = Direction::Right | Direction::Top,
Direction::RightBottom = Direction::Right | Direction::Bottom
}
enum PlayState { PlayState::Stopped, PlayState::Playing, PlayState::Paused }
enum PlayMode {
PlayMode::Order, PlayMode::Random, PlayMode::ListLoop, PlayMode::OneLoop,
PlayMode::Once
}
enum FontStyleMode {
FontStyleMode::Bold = 0x0001, FontStyleMode::Italic = 0x0002, FontStyleMode::Underline = 0x0004, FontStyleMode::Overline = 0x0008,
FontStyleMode::StrikeOut = 0x0010, FontStyleMode::FixedPitch = 0x0020, FontStyleMode::Kerningt = 0x0040
}
enum QueryQuality {
QueryQuality::None, QueryQuality::Standard, QueryQuality::High, QueryQuality::Super,
QueryQuality::Lossless
}
enum Enhance {
Enhance::Off, Enhance::M3D, Enhance::NICAM, Enhance::Subwoofer,
Enhance::Vocal
}
enum Download {
Download::Music, Download::Lrc, Download::Cover, Download::Background,
Download::Video, Download::Extra
}
enum Record { Record::NormalDownload, Record::CloudDownload, Record::CloudUpload, Record::Null }
enum Program { Program::Recommed, Program::Rank }
enum Mode { Mode::Check, Mode::Apply }
Functions
template<typename _Tp >
constexpr const _Tp & min (const _Tp &a, const _Tp &b) noexcept
template<typename _Tp >
constexpr const _Tp & max (const _Tp &a, const _Tp &b) noexcept
static QString applicationPath ()
TTK_MODULE_EXPORT void setUserAgentHeader (QNetworkRequest *request, const QByteArray &data={}) noexcept
TTK_MODULE_EXPORT void setContentTypeHeader (QNetworkRequest *request, const QByteArray &data={}) noexcept
TTK_MODULE_EXPORT void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode mode=QSslSocket::VerifyNone) noexcept
TTK_MODULE_EXPORT qint64 fetchFileSizeByUrl (const QString &url)
TTK_MODULE_EXPORT QByteArray syncNetworkQueryForGet (QNetworkRequest *request)
TTK_MODULE_EXPORT QByteArray syncNetworkQueryForPost (QNetworkRequest *request, const QByteArray &data)
TTK_MODULE_EXPORT QByteArray syncNetworkQueryForPut (QNetworkRequest *request, const QByteArray &data)
TTK_MODULE_EXPORT QByteArray syncNetworkQueryForPatch (QNetworkRequest *request, const QByteArray &data)
template<typename T , typename... Args>
TTKAny make_any (Args &&...args)
template<typename T , typename _TYPE = remove_cvr<T>>
_TYPE any_cast (const TTKAny &other)
template<typename T , typename _TYPE = remove_cvr<T>>
_TYPE any_cast (TTKAny &other)
template<typename T , typename _TYPE = remove_cvr<T>>
_TYPE any_cast (TTKAny &&other)
template<typename T , typename _TYPE = remove_cvr<T>>
_TYPE any_cast (const TTKAny *const other) noexcept
template<typename T , typename _TYPE = remove_cvr<T>>
_TYPE any_cast (TTKAny *const other) noexcept
static bool isBase64 (unsigned char c)
TTK_MODULE_EXPORT TTKString base64Encode (const unsigned char *bytes, unsigned int len)
TTK_MODULE_EXPORT TTKString base64Decode (const TTKString &bytes)
TTK_MODULE_EXPORT void setBorderShadow (QWidget *widget, QPainter *painter)
TTK_MODULE_EXPORT void initialize (TTK::Attribute attr)
template<typename _Output , typename _Input >
_Output lexical_cast (const _Input &input)
TTK_MODULE_EXPORT void initiailizeLog (const QString &module)
TTK_MODULE_EXPORT void installLogHandler ()
TTK_MODULE_EXPORT void removeLogHandler ()
TTK_MODULE_EXPORT void setLogMaxSize (qint64 maxSize)
TTK_MODULE_EXPORT void setExpireSecond (qint64 maxSecond)
TTK_MODULE_EXPORT void setOutputPath (const QString &dir)
TTK_MODULE_EXPORT void killProcessByName (const QString &process, bool more=false)
TTK_MODULE_EXPORT void killProcessByName (const QStringList &processes, bool more=false)
template<typename T , typename... Args>
TTKSharedPtr< T > make_shared (Args &&...args)
template<typename T , typename U >
TTKSharedPtr< T > static_pointer_cast (const TTKSharedPtr< U > &p) noexcept
template<typename T , typename U >
TTKSharedPtr< T > const_pointer_cast (const TTKSharedPtr< U > &p) noexcept
template<typename T , typename U >
TTKSharedPtr< T > dynamic_pointer_cast (const TTKSharedPtr< U > &p) noexcept
template<typename T , typename U >
TTKSharedPtr< T > reinterpret_pointer_cast (const TTKSharedPtr< U > &p) noexcept
template<typename T >
std::shared_ptr< T > makeCopy (const T *&source)
template<typename T >
std::shared_ptr< T > makeCopy (const std::shared_ptr< T > &source)
TTK_MODULE_EXPORT void initRandom ()
TTK_MODULE_EXPORT int random (int value=RAND_MAX)
static bool endWith (const TTKString &value, const TTKString &tail)
TTK_DECLARE_LIST (IndexProperty)
TTK_DECLARE_LIST (MusicSongProperty)
TTK_DECLARE_LIST (MusicArtistProperty)
TTK_DECLARE_LIST (MusicSongInformation)
static QString configPath ()
static quint64 directorySize (const QString &dirName)
static void checkCacheSize ()
static QString languageCore (int index)
static QString languageQmmp (int index)
TTK_MODULE_EXPORT MusicSongList generateSongList (const QString &path)
TTK_MODULE_EXPORT bool playlistRowValid (int index) noexcept
TTK_MODULE_EXPORT QString trackRelatedPath (const QString &path)
TTK_MODULE_EXPORT QString generateSongName (const QString &title, const QString &artist) noexcept
TTK_MODULE_EXPORT QString generateSongTitle (const QString &name, const QString &key=TTK_DEFAULT_STR)
TTK_MODULE_EXPORT QString generateSongArtist (const QString &name, const QString &key=TTK_DEFAULT_STR)
TTK_MODULE_EXPORT QString generateNetworkSongTime (const QString &path, bool format)
TTK_MODULE_EXPORT QString generateNetworkSongPath (const QString &path)
TTK_MODULE_EXPORT QString generateNetworkSongMetaPath (const QString &path)
TTK_MODULE_EXPORT void generateNetworkSongMeta (const QString &id, const MusicResultDataItem &item)
static bool isCoverValid (const QString &url) noexcept
TTK_MODULE_EXPORT QString toString (Record type) noexcept
MusicLrcColor mapIndexToColor (MusicLrcColor::Color index)
QList< QColor > readColorConfig (const QString &value)
QString writeColorConfig (const QList< QColor > &colors)
static QString generateArtist (const QString &v) noexcept
static QString generateAlbum (const QString &v) noexcept
static QString generateYear (const QString &v) noexcept
static QString generateGenre (const QString &v) noexcept
TTK_MODULE_EXPORT QStringList supportAssociations ()
TTK_MODULE_EXPORT QStringList unsupportAssociations ()
Variables
static constexpr const char * base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Detailed Description
The namespace of the application object.
The namespace of the association helper.
The namespace of the application ui object.
The namespace of the lrc color helper.
The namespace of the utils widget.
The namespace of the utils url.
The namespace of the utils string.
The namespace of the utils ttk qmmp.
The namespace of the utils number.
The namespace of the utils image.
The namespace of the utils file.
The namespace of the utils core.
The namespace of the utils algorithm.
The namespace of the mode type data.
The namespace of the record type helper.
The namespace of the program type.
The namespace of the cover helper.
The namespace of the song helper.
The namespace of the playlist helper.
The namespace of the random helper.
The namespace of the process utils.
The namespace of the log output.
The namespace of the global defines.
The class of the ttk lexical cast.
The namespace of the ttk initialization.
The namespace of the global interface.
The namespace of the defer helper.
The namespace of the base64 helper.
The namespace of the any helper.
The namespace of the network helper.
The namespace of the network data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Typedef Documentation
template<typename T > using TTK::remove_cvr = typedef typename std::remove_cv<typename std::remove_reference<T>::type>::type
Definition at line 175 of file ttkany.h.
Enumeration Type Documentation
enum TTK::Attribute
Enumerator
UseLog
Use log option
ScaleFactor
Use scale factor option
UseXCB
Use xcb (x11 only) option
DisbaleFFmpeg
Use ffmpeg backend option
All
Use all option
Definition at line 30 of file ttkinitialization.h.
enum TTK::Direction strong
Enumerator
No
Left
Top
Right
Bottom
LeftTop
LeftBottom
RightTop
RightBottom
Definition at line 27 of file ttklibrary.h.
enum TTK::Download strong
Enumerator
Music
Type of dwonlaod music
Lrc
Type of dwonlaod lrc
Cover
Type of dwonlaod cover
Background
Type of dwonlaod background
Video
Type of dwonlaod video
Extra
Type of dwonlaod extra user module
Definition at line 27 of file musicnetworkdefines.h.
enum TTK::Enhance strong
Enumerator
Off
enhance off, no any effect
M3D
3d media effect
NICAM
nicam media effect
Subwoofer
subwoofer media effect
Vocal
vocal media effect
Definition at line 33 of file musicplayer.h.
enum TTK::FontStyleMode strong
Enumerator
Bold
font bold mode
Italic
font italic mode
Underline
font underline mode
Overline
font overline mode
StrikeOut
font strikeOut mode
FixedPitch
font fixedPitch mode
Kerningt
font kerningt mode
Definition at line 199 of file musicobject.h.
enum TTK::Mode strong
Enumerator
Check
Song check mode
Apply
Song apply mode
Definition at line 29 of file musicsongchecktoolsunit.h.
enum TTK::NetworkCode strong
Enumerator
Query
Network state query
Success
Network state success
Error
Network state error
UnKnow
Network state unknow
Definition at line 33 of file ttkabstractnetwork.h.
enum TTK::PlayMode strong
Enumerator
Order
play order mode
Random
play random mode
ListLoop
play list loop mode
OneLoop
play single loop mode
Once
play just once mode
Definition at line 190 of file musicobject.h.
enum TTK::PlayState strong
Enumerator
Stopped
stop state
Playing
play state
Paused
pause state
Definition at line 183 of file musicobject.h.
enum TTK::Program strong
Enumerator
Recommed
Rank
Definition at line 29 of file musicdjradioprogramrequest.h.
enum TTK::QueryQuality strong
Enumerator
None
none quality
Standard
sd quality
High
hq quality
Super
sq quality
Lossless
cd quality
Definition at line 210 of file musicobject.h.
enum TTK::Record strong
Enumerator
NormalDownload
Local download file config
CloudDownload
Cloud download file config
CloudUpload
Cloud upload failed file config
Null
None file config
Definition at line 37 of file musicnetworkdefines.h.
enum TTK::ScopeGuardOnExit strong
Definition at line 68 of file ttkdefer.h.
Function Documentation
template<typename T , typename _TYPE = remove_cvr<T>> _TYPE TTK::any_cast (const TTKAny & other) inline
Make any cast helper.
Definition at line 181 of file ttkany.h.
References TTKAny::cast(), and TTKAny::isSame().
template<typename T , typename _TYPE = remove_cvr<T>> _TYPE TTK::any_cast (TTKAny & other) inline
Make any cast helper.
Definition at line 189 of file ttkany.h.
References TTKAny::cast(), and TTKAny::isSame().
template<typename T , typename _TYPE = remove_cvr<T>> _TYPE TTK::any_cast (TTKAny && other) inline
Make any cast helper.
Definition at line 197 of file ttkany.h.
template<typename T , typename _TYPE = remove_cvr<T>> _TYPE TTK::any_cast (const TTKAny *const other) inline noexcept
Make any cast helper.
Definition at line 205 of file ttkany.h.
template<typename T , typename _TYPE = remove_cvr<T>> _TYPE TTK::any_cast (TTKAny *const other) inline noexcept
Make any cast helper.
Definition at line 213 of file ttkany.h.
static QString TTK::applicationPath () inline static
Get application work dir.
Definition at line 44 of file ttkqtobject.h.
References TTK_SEPARATOR.
Referenced by MusicApplicationModule::applyParameter(), MusicRunTimeManager::execute(), and Miniblink::initialize().
TTKString TTK::base64Decode (const TTKString & bytes)
Base64 dncode.
Definition at line 69 of file ttkcryptographichash.cpp.
References base64_chars, and isBase64().
Referenced by TTKCryptographicHash::decrypt(), QAlgorithm::Des::decrypt(), and TTKCryptographicHash::xxteaDecrypt().
TTKString TTK::base64Encode (const unsigned char * bytes, unsigned int len)
Base64 encode.
Definition at line 19 of file ttkcryptographichash.cpp.
References base64_chars.
Referenced by TTKCryptographicHash::encrypt(), QAlgorithm::Des::encrypt(), and TTKCryptographicHash::xxteaEncrypt().
void TTK::checkCacheSize () static
Check download cachce size.
Definition at line 54 of file musicruntimemanager.cpp.
References directorySize(), MusicSettingManager::DownloadCacheEnable, MusicSettingManager::DownloadCacheSize, MusicSettingManager::DownloadMusicDirPath, G_SETTING_PTR, qAsConst, and TTK_SN_MB2B.
Referenced by MusicRunTimeManager::execute().
static QString TTK::configPath () inline static
Get application config dir.
Definition at line 322 of file musicobject.h.
References MAIN_DIR_FULL, and TTK_SEPARATOR.
template<typename T , typename U > TTKSharedPtr<T> TTK::const_pointer_cast (const TTKSharedPtr< U > & p) inline noexcept
Definition at line 188 of file ttksmartptr.h.
References T.
quint64 TTK::directorySize (const QString & dirName) static
Generate input directory size.
Definition at line 32 of file musicruntimemanager.cpp.
References qAsConst.
Referenced by checkCacheSize().
template<typename T , typename U > TTKSharedPtr<T> TTK::dynamic_pointer_cast (const TTKSharedPtr< U > & p) inline noexcept
Definition at line 195 of file ttksmartptr.h.
References T.
static bool TTK::endWith (const TTKString & value, const TTKString & tail) static
Definition at line 18 of file ttkrunobject.cpp.
Referenced by TTKRunObject::execute().
qint64 TTK::fetchFileSizeByUrl (const QString & url)
Fetch download file size by url.
Definition at line 96 of file ttkabstractnetwork.cpp.
References TTKEventLoop::exec(), QtNetworkErrorVoidConnect, setContentTypeHeader(), setSslConfiguration(), TTK_INFO_STREAM, and TTK_SLOT.
Referenced by MusicAbstractQueryRequest::fetchUrlPathSize(), and MusicSongsContainerWidget::importSongsByUrl().
static QString TTK::generateAlbum (const QString & v) inline static noexcept
Generate song album.
Definition at line 29 of file musiclocalmanagerwidget.cpp.
Referenced by MusicLocalManagerWidget::refreshItems().
static QString TTK::generateArtist (const QString & v) inline static noexcept
Generate song artist.
Definition at line 22 of file musiclocalmanagerwidget.cpp.
Referenced by MusicLocalManagerWidget::refreshItems().
static QString TTK::generateGenre (const QString & v) inline static noexcept
Generate song genre.
Definition at line 43 of file musiclocalmanagerwidget.cpp.
Referenced by MusicLocalManagerWidget::refreshItems().
void TTK::generateNetworkSongMeta (const QString & id, const MusicResultDataItem & item)
Generate network song meta.
Definition at line 110 of file musicsonghelper.cpp.
References CACHE_DIR_FULL, MusicResultDataItem::m_count, MusicResultDataItem::m_description, MusicResultDataItem::m_id, MusicResultDataItem::m_name, MusicResultDataItem::m_nickName, MusicResultDataItem::m_time, and TKB_FILE.
Referenced by MusicSongsContainerWidget::addSongBufferToPlaylist().
QString TTK::generateNetworkSongMetaPath (const QString & path)
Generate network song meta path.
Definition at line 91 of file musicsonghelper.cpp.
References CACHE_DIR_FULL, TTK::String::isNetworkUrl(), TTK::String::pefix(), and TKB_FILE.
Referenced by generateNetworkSongTime(), MusicSongsContainerWidget::removeItemAt(), and MusicApplication::removeItemAt().
QString TTK::generateNetworkSongPath (const QString & path)
Generate network song path.
Definition at line 72 of file musicsonghelper.cpp.
References CACHE_DIR_FULL, and TTK::String::isNetworkUrl().
Referenced by generateNetworkSongTime(), MusicSongsListItemInfoWidget::initialize(), MusicPlayer::play(), MusicSongsContainerWidget::removeItemAt(), and MusicApplication::removeItemAt().
QString TTK::generateNetworkSongTime (const QString & path, bool format)
Generate network song play time.
Definition at line 46 of file musicsonghelper.cpp.
References MusicSongMeta::duration(), TTKTime::formatDuration(), generateNetworkSongMetaPath(), generateNetworkSongPath(), MusicSongMeta::read(), and TTK_DEFAULT_STR.
Referenced by MusicPlayer::generateDuration(), and MusicTKPLConfigManager::writeBuffer().
QString TTK::generateSongArtist (const QString & name, const QString & key = TTK_DEFAULT_STR)
Get song artist name.
Definition at line 35 of file musicsonghelper.cpp.
References name, and TTK::String::split().
Referenced by MusicSong::artist(), MusicDownloadStatusModule::checkArtistBackgroundValid(), MusicDownloadStatusModule::checkArtistCoverValid(), MusicSongsListPlayTableWidget::contextMenuEvent(), MusicDownloadStatusModule::currentMetaDataDownload(), MusicDownloadWidget::downloadNormalFinished(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicSongsListPlayWidget::initialize(), MusicSongSharingWidget::initialize(), MusicBackgroundManager::setArtistName(), MusicLrcMakerWidget::setCurrentSongName(), MusicArtistQueryWidget::setCurrentValue(), MusicRemoteWidgetForComplexStyle::setLabelText(), and MusicSongsListPlayWidget::updateCurrentArtist().
MusicSongList TTK::generateSongList (const QString & path)
Generate song playlist.
Definition at line 92 of file musicsong.cpp.
References MusicSongMeta::artist(), MusicSongMeta::duration(), MusicSongMeta::fileBasePath(), G_SETTING_PTR, generateSongName(), MusicFormats::isTrack(), LRC_FILE, TTK::String::lrcDirPrefix(), MusicSongMeta::lyrics(), name, MusicSettingManager::OtherReadFileInfo, MusicSongMeta::read(), MusicSongMeta::setSongMetaIndex(), MusicSongMeta::songMetaCount(), and MusicSongMeta::title().
Referenced by MusicSongsContainerWidget::importSongsWithProgress().
QString TTK::generateSongName (const QString & title, const QString & artist) noexcept
Generate song name.
Definition at line 19 of file musicsonghelper.cpp.
Referenced by MusicSongSearchTableWidget::addSearchMusicToPlaylist(), MusicIdentifySongWidget::createDetectedSuccessedWidget(), MusicItemQueryTableWidget::createResultItem(), MusicNewSongRecommendQueryTableWidget::createResultItem(), MusicNewSongRecommendQueryTableWidget::downloadDataFrom(), MusicItemQueryTableWidget::downloadDataFrom(), generateSongList(), MusicVideoSearchTableWidget::itemDoubleClicked(), MusicWebFMRadioPlayWidget::lrcDownloadStateChanged(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), MusicLocalManagerWidget::refreshItems(), MusicSongCheckToolsRenameThread::run(), MusicItemSearchTableWidget::searchActionClicked(), MusicSongSearchTableWidget::searchActionClicked(), and MusicVideoPlayWidget::videoResearchButtonSearched().
QString TTK::generateSongTitle (const QString & name, const QString & key = TTK_DEFAULT_STR)
Get song title name.
Definition at line 24 of file musicsonghelper.cpp.
References name, and TTK::String::split().
Referenced by MusicSongsListPlayTableWidget::contextMenuEvent(), MusicDownloadStatusModule::currentMetaDataDownload(), MusicDownloadWidget::downloadNormalFinished(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicSongsListPlayWidget::initialize(), MusicLrcMakerWidget::setCurrentSongName(), MusicRecommendQueryWidget::setCurrentValue(), MusicSimilarQueryWidget::setCurrentValue(), MusicRemoteWidgetForComplexStyle::setLabelText(), MusicSong::title(), and MusicSongsListPlayWidget::updateCurrentArtist().
static QString TTK::generateYear (const QString & v) inline static noexcept
Generate song year.
Definition at line 36 of file musiclocalmanagerwidget.cpp.
Referenced by MusicLocalManagerWidget::refreshItems().
void TTK::initiailizeLog (const QString & module)
Initiailize log module.
Definition at line 279 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance().
Referenced by initialize().
void TTK::initialize (TTK::Attribute attr)
Initialization before qApp.
Definition at line 41 of file ttkinitialization.cpp.
References TTKDesktopScreen::currentPixelRatio(), DisbaleFFmpeg, initiailizeLog(), installLogHandler(), message(), qEnvironmentVariableIsSet(), ScaleFactor, TTK_APP_NAME, TTK_INFO_STREAM, UseLog, and UseXCB.
Referenced by main(), and TTKTime::TTKTime().
void TTK::initRandom ()
Init random value seed.
Definition at line 7 of file ttktime.cpp.
Referenced by MusicBarrageWidget::addBarrage(), MusicBarrageWidget::createLabel(), QAlgorithm::CubeWavePrivate::CubeWavePrivate(), MusicDesktopWallpaperThread::MusicDesktopWallpaperThread(), MusicDiscoverListRequest::MusicDiscoverListRequest(), MusicDownloadBatchTableWidget::MusicDownloadBatchTableWidget(), MusicMPRISPlayerCore::MusicMPRISPlayerCore(), MusicNetworkTestThread::MusicNetworkTestThread(), MusicPlaylist::MusicPlaylist(), MusicTransitionAnimationLabel::MusicTransitionAnimationLabel(), and MusicVideoSearchTableWidget::MusicVideoSearchTableWidget().
void TTK::installLogHandler ()
Install log output handler.
Definition at line 284 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance().
Referenced by MusicApplicationModule::applyParameter(), and initialize().
static bool TTK::isBase64 (unsigned char c) inline static
Char is base64 or not.
Definition at line 13 of file ttkcryptographichash.cpp.
References isalnum.
Referenced by base64Decode().
static bool TTK::isCoverValid (const QString & url) inline static noexcept
Check current url is valid or not.
Definition at line 58 of file musiccoverrequest.h.
References TTK_DEFAULT_STR, and TTK_NULL_STR.
Referenced by MusicCommentsItem::addCellItem(), MusicAlbumQueryWidget::createAlbumItem(), MusicArtistQueryWidget::createArtistItem(), MusicWebMVRadioInfoWidget::createMVRadioProgramItem(), MusicWebDJRadioInfoWidget::createProgramCategoryItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicToplistQueryWidget::createToplistItem(), MusicSongSharingWidget::initialize(), MusicPlaylistQueryInfoWidget::setResultDataItem(), MusicPersonalRadioQueryWidget::setResultDataItem(), MusicSquareQueryItemWidget::setResultDataItem(), MusicRectQueryItemWidget::setResultDataItem(), and MusicLabelQueryItemWidget::setResultDataItem().
TTK_MODULE_EXPORT void TTK::killProcessByName (const QString & process, bool more = false)
Kill process by name.
Referenced by cleanupCache(), and MusicCoreMPlayer::closeModule().
TTK_MODULE_EXPORT void TTK::killProcessByName (const QStringList & processes, bool more = false)
Kill process by name list.
QString TTK::languageCore (int index) static
Generate core language resource.
Definition at line 80 of file musicruntimemanager.cpp.
References LANGUAGE_DIR_FULL.
Referenced by MusicRunTimeManager::translator().
QString TTK::languageQmmp (int index) static
Generate qmmp language resource.
Definition at line 92 of file musicruntimemanager.cpp.
References LANGUAGE_DIR_FULL.
Referenced by MusicRunTimeManager::translator().
template<typename _Output , typename _Input > _Output TTK::lexical_cast (const _Input & input)
Definition at line 30 of file ttklexicalcast.h.
template<typename T , typename... Args> TTKAny TTK::make_any (Args &&... args) inline
Make any helper.
Definition at line 169 of file ttkany.h.
References T.
template<typename T , typename... Args> TTKSharedPtr<T> TTK::make_shared (Args &&... args) inline
Definition at line 175 of file ttksmartptr.h.
template<typename T > std::shared_ptr<T> TTK::makeCopy (const T *& source) inline
Definition at line 221 of file ttksmartptr.h.
Referenced by TTKTime::operator=(), and TTKTime::TTKTime().
template<typename T > std::shared_ptr<T> TTK::makeCopy (const std::shared_ptr< T > & source) inline
Definition at line 227 of file ttksmartptr.h.
MusicLrcColor TTK::mapIndexToColor (MusicLrcColor::Color index)
Map index to color.
Definition at line 20 of file musiclrcmanager.cpp.
References MusicLrcColor::DBlack, MusicLrcColor::DBlue, MusicLrcColor::DGreen, MusicLrcColor::DPurple, MusicLrcColor::DRed, MusicLrcColor::DWhite, MusicLrcColor::DYellow, MusicLrcColor::IBlue, MusicLrcColor::IGray, MusicLrcColor::IGreen, MusicLrcColor::IIndigo, MusicLrcColor::IOrange, MusicLrcColor::IPink, MusicLrcColor::IPurple, MusicLrcColor::IRed, and MusicLrcColor::IYellow.
Referenced by MusicSettingWidget::lrcColorByDefault(), MusicLrcMakerWidget::setItemStyleSheet(), and MusicLrcContainer::setLinearGradientColor().
template<typename _Tp > constexpr const _Tp& TTK::max (const _Tp & a, const _Tp & b) inline noexcept
Definition at line 33 of file ttkcompat.h.
Referenced by std::clamp(), compress2(), gz_comp(), gz_load(), inflate_table(), MusicLrcAnalysis::setMaximum(), MusicTextSliderWidget::setMaxValue(), MusicTimeSliderWidget::sliderMovedAt(), MusicSongSharingWidget::textAreaChanged(), and uncompress2().
template<typename _Tp > constexpr const _Tp& TTK::min (const _Tp & a, const _Tp & b) inline noexcept
Definition at line 27 of file ttkcompat.h.
Referenced by std::clamp(), TTKBaseStringView< _CharT, _Traits >::compare(), TTKTime::formatDuration(), TTKTime::fromValue(), inflate_table(), TTKTime::setMinute(), and TTKTime::TTKTime().
bool TTK::playlistRowValid (int index) noexcept
Check current song playlist row is valid or not.
Definition at line 9 of file musicsonghelper.cpp.
References MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, and MUSIC_RECENT_LIST.
Referenced by MusicSongsListPlayTableWidget::createUploadFileModule(), MusicSongsContainerWidget::deleteRowItems(), MusicSongsContainerWidget::dragMoveEvent(), MusicSongsContainerWidget::dropEvent(), MusicSongsToolBoxTopWidget::isItemEnabled(), MusicSongsToolBoxWidget::makeValidIndex(), MusicSongsToolBoxTopWidget::paintEvent(), MusicSongItemSelectedAreaWidget::selectedSongItems(), and MusicSongsToolBoxTopWidget::showMenu().
int TTK::random (int value = RAND_MAX)
Get random value.
Definition at line 14 of file ttktime.cpp.
Referenced by MusicBarrageAnimation::animationFinished(), MusicScreenSaverBackgroundWidget::backgroundTimeout(), MusicAlbumQueryWidget::createLabels(), MusicArtistQueryWidget::createLabels(), MusicKGDiscoverListRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicDownloadBatchTableWidget::generateTimer(), MusicBarrageAnimation::initialize(), QAlgorithm::CubeWave::input(), MusicItemSearchTableWidget::randSimulation(), MusicNetworkTestThread::run(), MusicTransitionAnimationLabel::setPixmap(), MusicDesktopWallpaperThread::setRandom(), MusicPlaylistQueryInfoWidget::setResultDataItem(), MusicBarrageAnimation::setSize(), MusicDesktopWallpaperThread::timeout(), and MusicMPRISPlayerCore::updateTrackID().
QList< QColor > TTK::readColorConfig (const QString & value)
Transform colors string to color list.
Definition at line 127 of file musiclrcmanager.cpp.
References qAsConst, and QtSkipEmptyParts.
Referenced by MusicLrcContainer::applyParameter(), MusicSettingWidget::initialize(), MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicLrcContainerForInterior::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
template<typename T , typename U > TTKSharedPtr<T> TTK::reinterpret_pointer_cast (const TTKSharedPtr< U > & p) inline noexcept
Definition at line 202 of file ttksmartptr.h.
References T.
void TTK::removeLogHandler ()
Remove log output handler.
Definition at line 289 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance().
Referenced by MusicApplicationModule::applyParameter().
void TTK::setBorderShadow (QWidget * widget, QPainter * painter)
Set widget border shadow.
Definition at line 8 of file ttkglobalinterface.cpp.
References HEIGHT, and WIDTH.
Referenced by TTKAbstractMoveDialog::paintEvent(), TTKAbstractMoveWidget::paintEvent(), MusicProgressWidget::paintEvent(), and MusicScreenSaverHoverItem::paintEvent().
void TTK::setContentTypeHeader (QNetworkRequest * request, const QByteArray & data = {}) noexcept
Set request Content-Type header.
Definition at line 79 of file ttkabstractnetwork.cpp.
Referenced by MusicTXDownloadBackgroundRequest::downloadUrl(), fetchFileSizeByUrl(), ReqBLInterface::makeRequestRawHeader(), ReqWYInterface::makeRequestRawHeader(), ReqKWInterface::makeRequestRawHeader(), ReqKGInterface::makeRequestRawHeader(), MusicDownloadQueueRequest::MusicDownloadQueueRequest(), ReqUnityInterface::parseFromSongProperty(), ToolQTFM::startToListRequest(), MusicUnityQueryMovieRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicResourceRequest::startToRequest(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicKWDownloadTextRequest::startToRequest(), MusicCiBaRequest::startToRequest(), MusicBPDownloadBackgroundRequest::startToRequest(), MusicDownloadTextRequest::startToRequest(), MusicBDTranslationRequest::startToRequest(), MusicWYDownloadTextRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicPVCounterRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), ToolQTFM::startToRequest(), MusicDataSourceRequest::startToRequest(), MusicTXDownloadBackgroundRequest::startToRequest(), MusicKWDownloadCoverRequest::startToRequest(), ToolXIFM::startToRequest(), MusicACRIdentifyRequest::startToRequest(), MusicDownloadDataRequest::startToRequest(), MusicXFIdentifyRequest::startToRequest(), and MusicSongRecommendRequest::startToSearch().
void TTK::setExpireSecond (qint64 maxSecond)
Remove log file after max second.
Definition at line 299 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance().
void TTK::setLogMaxSize (qint64 maxSize)
Set max size for log file.
Definition at line 294 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance().
void TTK::setOutputPath (const QString & dir)
Set log output dir path.
Definition at line 304 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance().
void TTK::setSslConfiguration (QNetworkRequest * request, QSslSocket::PeerVerifyMode mode = QSslSocket::VerifyNone) noexcept
Set request ssl configuration.
Definition at line 84 of file ttkabstractnetwork.cpp.
Referenced by MusicTXDownloadBackgroundRequest::downloadUrl(), fetchFileSizeByUrl(), ReqBLInterface::makeRequestRawHeader(), ReqWYInterface::makeRequestRawHeader(), ReqKWInterface::makeRequestRawHeader(), ReqKGInterface::makeRequestRawHeader(), MusicDownloadQueueRequest::MusicDownloadQueueRequest(), ReqUnityInterface::parseFromSongProperty(), ToolQTFM::startToListRequest(), MusicUnityQueryMovieRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicResourceRequest::startToRequest(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicKWDownloadTextRequest::startToRequest(), MusicCiBaRequest::startToRequest(), MusicBPDownloadBackgroundRequest::startToRequest(), MusicDownloadTextRequest::startToRequest(), MusicBDTranslationRequest::startToRequest(), MusicWYDownloadTextRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicPVCounterRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), ToolQTFM::startToRequest(), MusicDataSourceRequest::startToRequest(), MusicTXDownloadBackgroundRequest::startToRequest(), MusicKWDownloadCoverRequest::startToRequest(), ToolXIFM::startToRequest(), MusicACRIdentifyRequest::startToRequest(), MusicDownloadDataRequest::startToRequest(), MusicXFIdentifyRequest::startToRequest(), and MusicSongRecommendRequest::startToSearch().
void TTK::setUserAgentHeader (QNetworkRequest * request, const QByteArray & data = {}) noexcept
Set request User-Agent header.
Definition at line 74 of file ttkabstractnetwork.cpp.
Referenced by ReqKWInterface::makeRequestRawHeader(), MusicBingTranslationRequest::startToRequest(), and MusicDataSourceRequest::startToRequest().
template<typename T , typename U > TTKSharedPtr<T> TTK::static_pointer_cast (const TTKSharedPtr< U > & p) inline noexcept
Definition at line 181 of file ttksmartptr.h.
References T.
QStringList TTK::supportAssociations ()
Get current support association files.
Definition at line 125 of file musicfileassociationwidget.cpp.
References MusicFormats::supportMusicFormats(), and unsupportAssociations().
Referenced by MusicApplicationModule::applyParameter().
QByteArray TTK::syncNetworkQueryForGet (QNetworkRequest * request)
Sync network query for get.
Definition at line 129 of file ttkabstractnetwork.cpp.
References TTKEventLoop::exec(), QtNetworkErrorVoidConnect, TTK_INFO_STREAM, and TTK_SLOT.
Referenced by ReqKGInterface::parseFromMovieInfo(), ReqKWInterface::parseFromMovieInfo(), ReqBLInterface::parseFromMovieInfo(), ReqKGInterface::parseFromMovieProperty(), ReqKWInterface::parseFromMovieProperty(), ReqBLInterface::parseFromMovieProperty(), ReqKGInterface::parseFromSongAlbumInfo(), ReqKGInterface::parseFromSongAlbumLrc(), parseSongPropertyA(), parseSongPropertyB(), parseSongPropertyC(), parseSongPropertyD(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), parseSongPropertyX(), MusicKGQueryArtistRequest::queryArtistIntro(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicKWQueryToplistRequest::queryToplistInfo(), MusicKGQueryToplistRequest::queryToplistInfo(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicKWQueryPlaylistRequest::startToQueryInfo(), MusicPVCounterRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), and MusicKWDownloadCoverRequest::startToRequest().
QByteArray TTK::syncNetworkQueryForPatch (QNetworkRequest * request, const QByteArray & data)
Sync network query for patch.
Definition at line 196 of file ttkabstractnetwork.cpp.
References TTKEventLoop::exec(), QtNetworkErrorVoidConnect, TTK_INFO_STREAM, and TTK_SLOT.
QByteArray TTK::syncNetworkQueryForPost (QNetworkRequest * request, const QByteArray & data)
Sync network query for post.
Definition at line 156 of file ttkabstractnetwork.cpp.
References TTKEventLoop::exec(), QtNetworkErrorVoidConnect, TTK_INFO_STREAM, and TTK_SLOT.
Referenced by MusicWYQueryArtistMovieRequest::parseFromArtistMoviesCount(), MusicWYQueryMovieRequest::parseFromMovieList(), ReqWYInterface::parseFromMovieProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyE(), parseSongPropertyV2(), parseSongPropertyV3(), MusicWYQueryArtistRequest::queryArtistIntro(), ToolQTFM::startToListRequest(), and MusicWYQueryPlaylistRequest::startToQueryInfo().
QByteArray TTK::syncNetworkQueryForPut (QNetworkRequest * request, const QByteArray & data)
Sync network query for put.
Definition at line 176 of file ttkabstractnetwork.cpp.
References TTKEventLoop::exec(), QtNetworkErrorVoidConnect, TTK_INFO_STREAM, and TTK_SLOT.
QString TTK::toString (Record type) noexcept
Mapping file path from enum type.
Definition at line 3 of file musicdownloadrecordconfigmanager.cpp.
References CLOUD_DOWN_PATH_FULL, CLOUD_UP_PATH_FULL, CloudDownload, CloudUpload, NORMAL_DOWN_PATH_FULL, and NormalDownload.
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicMVRadioCategoryRequest::downloadFinished(), MusicMVRadioProgramRequest::downloadFinished(), MusicBingTranslationRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicKWDownloadTextRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicDownloadBingSkinRequest::downloadFinished(), MusicResourceRequest::downloadFinished(), MusicBDTranslationRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKGQueryArtistListRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicDownloadBirdSkinRequest::downloadFinished(), MusicNewAlbumsRecommendRequest::downloadFinished(), MusicKWQueryPlaylistRequest::downloadFinished(), MusicKWQueryHotArtistListRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicWYQueryNewAlbumRequest::downloadFinished(), MusicKWQueryPlaylistRequest::downloadMoreDetailsFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicKGQuerySongRequest::downloadSingleFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicTranslationRequest::findAllPlugins(), MusicMPRISPlayerCore::metadata(), ReqKWInterface::parseFromMovieInfo(), MusicWYQueryMovieRequest::parseFromMovieList(), ReqKGInterface::parseFromMovieProperty(), ReqKGInterface::parseFromSongAlbumInfo(), ReqKGInterface::parseFromSongAlbumLrc(), ReqLQInterface::parseFromSongProperty(), ReqUnityInterface::parseFromSongProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyA(), MusicWYQueryArtistRequest::queryArtistIntro(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicJSPFConfigManager::readBuffer(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicWYTranslationRequest::startToRequest(), MusicCiBaRequest::startToRequest(), MusicDownloadWidget::startToRequestMusic(), MusicAbstractDownloadTableWidget::updateSongsList(), QHttpResponsePrivate::writeHeaders(), and MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget().
QString TTK::trackRelatedPath (const QString & path)
Remove track info in path.
Definition at line 14 of file musicsonghelper.cpp.
References MusicFormats::isTrack(), and TrackInfo::pathFromUrl().
Referenced by MusicSong::MusicSong(), MusicFileInformationWidget::openFileDir(), and MusicAbstractSongsListTableWidget::openFileDir().
TTK::TTK_DECLARE_LIST (IndexProperty)
TTK::TTK_DECLARE_LIST (MusicSongProperty)
TTK::TTK_DECLARE_LIST (MusicArtistProperty)
TTK::TTK_DECLARE_LIST (MusicSongInformation)
QStringList TTK::unsupportAssociations ()
Get current unsupport association files.
Definition at line 139 of file musicfileassociationwidget.cpp.
References MusicSettingManager::FileAssociationValue, and G_SETTING_PTR.
Referenced by MusicApplicationModule::applyParameter(), and supportAssociations().
QString TTK::writeColorConfig (const QList< QColor > & colors)
Transform color list to colors string.
Definition at line 143 of file musiclrcmanager.cpp.
References qAsConst.
Referenced by MusicSettingWidget::saveParameterSettings().
Variable Documentation
constexpr const char* TTK::base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" static
Definition at line 8 of file ttkcryptographichash.cpp.
Referenced by base64Decode(), and base64Encode().