TTKMusicplayer: MusicKWPlaylistCommentsRequest Class Reference
MusicKWPlaylistCommentsRequest Class Reference
The class of kuwo query playlist comments download data from net.
#include <musickwcommentsrequest.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWPlaylistCommentsRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &name) override
virtual void startToPage (int offset) override
Public Member Functions inherited from MusicCommentsRequest
MusicCommentsRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
int getPageSize () const
int getTotalSize () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Signals inherited from MusicCommentsRequest
void createSearchedItem (const MusicResultsItem &comments)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of kuwo query playlist comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 58 of file musickwcommentsrequest.h.
Constructor & Destructor Documentation
MusicKWPlaylistCommentsRequest::MusicKWPlaylistCommentsRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 96 of file musickwcommentsrequest.cpp.
References MusicPageQueryRequest::m_pageSize.
Member Function Documentation
void MusicKWPlaylistCommentsRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 130 of file musickwcommentsrequest.cpp.
References MusicCommentsRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicResultsItem::m_updateTime, MUSIC_YEAR_STIME_FORMAT, QJson::Parser::parse(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToPage().
void MusicKWPlaylistCommentsRequest::startToPage (int offset) override virtual
Start to search data from name and type bt page.
Reimplemented from MusicPageQueryRequest.
Definition at line 110 of file musickwcommentsrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KW_COMMENT_PLAYLIST_URL, MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageSize, MusicAbstractNetwork::m_rawData, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicKWPlaylistCommentsRequest::startToSearch (const QString & name) override virtual
Start to Search data from name.
Implements MusicCommentsRequest.
Definition at line 102 of file musickwcommentsrequest.cpp.
References MusicAbstractNetwork::m_rawData, name, startToPage(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwcommentsrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwcommentsrequest.cpp