TTKMusicPlayer: MusicNetworkThread Class Reference
MusicNetworkThread Class Reference
The class of thread to check current network.
#include <musicnetworkthread.h>
Public Slots
void networkStateChanged ()
Signals
void networkConnectionStateChanged (bool state)
Public Member Functions
void start ()
void setBlockNetWork (int block)
void setNetWorkState (bool state)
bool isOnline () const
Private Member Functions
MusicNetworkThread ()
~MusicNetworkThread ()
Private Attributes
QTimer m_timer
bool m_networkState
Detailed Description
The class of thread to check current network.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicnetworkthread.h.
Constructor & Destructor Documentation
MusicNetworkThread::MusicNetworkThread () private
Object contsructor.
Definition at line 15 of file musicnetworkthread.cpp.
References G_CONNECTION_PTR, m_timer, and networkStateChanged().
MusicNetworkThread::~MusicNetworkThread () private
Definition at line 24 of file musicnetworkthread.cpp.
References m_timer.
Member Function Documentation
bool MusicNetworkThread::isOnline () const inline
Check current network is on.
Definition at line 48 of file musicnetworkthread.h.
void MusicNetworkThread::networkConnectionStateChanged (bool state) signal
Network connection state changed. default status is true, means connected network.
Referenced by networkStateChanged().
void MusicNetworkThread::networkStateChanged () slot
Network connection state changed.
Definition at line 41 of file musicnetworkthread.cpp.
References MusicSettingManager::CloseNetWorkMode, G_SETTING_PTR, m_networkState, NETWORK_REQUEST_ADDRESS, and networkConnectionStateChanged().
Referenced by MusicNetworkThread(), and start().
void MusicNetworkThread::setBlockNetWork (int block)
Set flag wheather to block current network.
Definition at line 36 of file musicnetworkthread.cpp.
References MusicSettingManager::CloseNetWorkMode, and G_SETTING_PTR.
void MusicNetworkThread::setNetWorkState (bool state) inline
Set current network state.
Definition at line 44 of file musicnetworkthread.h.
void MusicNetworkThread::start ()
Strat thread now.
Definition at line 29 of file musicnetworkthread.cpp.
References m_timer, NETWORK_DETECT_INTERVAL, networkStateChanged(), and TTK_INFO_STREAM.
Member Data Documentation
bool MusicNetworkThread::m_networkState private
Definition at line 71 of file musicnetworkthread.h.
Referenced by networkStateChanged().
QTimer MusicNetworkThread::m_timer private
Definition at line 70 of file musicnetworkthread.h.
Referenced by MusicNetworkThread(), start(), and ~MusicNetworkThread().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicnetworkthread.h
TTKModule/TTKCore/musicNetworkKits/tools/musicnetworkthread.cpp