TTKMusicPlayer: QJson::SerializerRunnable Class Reference
QJson::SerializerRunnable Class Reference
Convenience class for converting JSON data to QVariant objects using a dedicated thread.
#include <serializerrunnable.h>
Classes
class SerializerRunnablePrivate
Convenience class for converting JSON data to QVariant objects using a dedicated thread private.
Signals
void parsingFinished (const QByteArray &serialized, bool ok, const QString &error_msg)
This signal is emitted when the serialization process has been completed.
Public Member Functions
SerializerRunnable (QObject *parent=nullptr)
void setJsonObject (const QVariant &json)
Sets the json object to serialize.
void run ()
Detailed Description
Convenience class for converting JSON data to QVariant objects using a dedicated thread.
Definition at line 39 of file serializerrunnable.h.
Constructor & Destructor Documentation
SerializerRunnable::SerializerRunnable (QObject * parent = nullptr) explicit
Definition at line 41 of file serializerrunnable.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
void QJson::SerializerRunnable::parsingFinished (const QByteArray & serialized, bool ok, const QString & error_msg) signal
This signal is emitted when the serialization process has been completed.
Parameters
serialized contains the result of the serialization
ok if a serialization error occurs ok is set to false, otherwise it's set to true.
error_msg contains a string explaining the failure reason
Referenced by run().
void SerializerRunnable::run ()
Definition at line 55 of file serializerrunnable.cpp.
References QJson::Serializer::errorMessage(), parsingFinished(), QJson::Serializer::serialize(), and TTK_D.
void SerializerRunnable::setJsonObject (const QVariant & json)
Sets the json object to serialize.
Parameters
json QVariant containing the json representation to be serialized
Definition at line 49 of file serializerrunnable.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/serializerrunnable.h
TTKThirdParty/TTKExtras/qjson/serializerrunnable.cpp