TTKMusicplayer: MusicWebDJRadioWidget Class Reference
MusicWebDJRadioWidget Class Reference
The class of music dj radio widget.
#include <musicwebdjradiowidget.h>
Public Slots
void backToMainMenu ()
void createRecommendWidget ()
void createProgramWidget ()
void programItemClicked (const QString &rid, const QString &cid)
void currentCategoryClicked (const MusicResultsItem &item)
Public Member Functions
MusicWebDJRadioWidget (QWidget *parent=nullptr)
~MusicWebDJRadioWidget ()
void initialize ()
virtual void resizeWindow ()
Protected Member Functions
void initFirstWidget ()
Protected Attributes
MusicWebDJRadioCategoryWidget * m_categoryWidget
MusicWebDJRadioProgramWidget * m_recommendWidget
MusicWebDJRadioProgramWidget * m_programWidget
MusicWebDJRadioQueryWidget * m_queryTableWidget
Detailed Description
The class of music dj radio widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 115 of file musicwebdjradiowidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioWidget::MusicWebDJRadioWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 224 of file musicwebdjradiowidget.cpp.
References initFirstWidget(), m_programWidget, m_queryTableWidget, m_recommendWidget, and MusicUIObject::MQSSBackgroundStyle17.
MusicWebDJRadioWidget::~MusicWebDJRadioWidget ()
Definition at line 237 of file musicwebdjradiowidget.cpp.
References m_categoryWidget, m_programWidget, m_queryTableWidget, and m_recommendWidget.
Member Function Documentation
void MusicWebDJRadioWidget::backToMainMenu () slot
Set current index to main menu page.
Definition at line 273 of file musicwebdjradiowidget.cpp.
Referenced by programItemClicked().
void MusicWebDJRadioWidget::createProgramWidget () slot
Create program widget.
Definition at line 287 of file musicwebdjradiowidget.cpp.
References MusicWebDJRadioProgramWidget::initialize(), m_programWidget, and MusicObject::Rank.
Referenced by initFirstWidget().
void MusicWebDJRadioWidget::createRecommendWidget () slot
Create recommend widget.
Definition at line 278 of file musicwebdjradiowidget.cpp.
References MusicWebDJRadioProgramWidget::initialize(), m_recommendWidget, and MusicObject::Recommed.
Referenced by initFirstWidget().
void MusicWebDJRadioWidget::currentCategoryClicked (const MusicResultsItem & item) slot
Current category clicked.
Definition at line 315 of file musicwebdjradiowidget.cpp.
References MusicResultsItem::m_id, and programItemClicked().
Referenced by initFirstWidget().
void MusicWebDJRadioWidget::initFirstWidget () protected
Init the first widget.
Definition at line 320 of file musicwebdjradiowidget.cpp.
References createProgramWidget(), createRecommendWidget(), currentCategoryClicked(), m_categoryWidget, MusicUIObject::MQSSColorStyle04, and MusicUIObject::MQSSColorStyle05.
Referenced by MusicWebDJRadioWidget().
void MusicWebDJRadioWidget::initialize ()
Init parameters.
Definition at line 245 of file musicwebdjradiowidget.cpp.
References MusicWebDJRadioCategoryWidget::initialize(), and m_categoryWidget.
Referenced by MusicRightAreaWidget::functionClicked().
void MusicWebDJRadioWidget::programItemClicked (const QString & rid, const QString & cid) slot
Program item clicked.
Definition at line 296 of file musicwebdjradiowidget.cpp.
References backToMainMenu(), m_queryTableWidget, MusicWebDJRadioQueryWidget::setSongName(), and MusicWebDJRadioQueryWidget::setSongNameById().
Referenced by currentCategoryClicked().
void MusicWebDJRadioWidget::resizeWindow () virtual
Resize window bound by widget resize called.
Definition at line 250 of file musicwebdjradiowidget.cpp.
References m_categoryWidget, m_programWidget, m_queryTableWidget, m_recommendWidget, MusicWebDJRadioCategoryWidget::resizeWindow(), MusicWebDJRadioQueryWidget::resizeWindow(), and MusicWebDJRadioProgramWidget::resizeWindow().
Member Data Documentation
MusicWebDJRadioCategoryWidget* MusicWebDJRadioWidget::m_categoryWidget protected
Definition at line 163 of file musicwebdjradiowidget.h.
Referenced by initFirstWidget(), initialize(), resizeWindow(), and ~MusicWebDJRadioWidget().
MusicWebDJRadioProgramWidget * MusicWebDJRadioWidget::m_programWidget protected
Definition at line 164 of file musicwebdjradiowidget.h.
Referenced by createProgramWidget(), MusicWebDJRadioWidget(), resizeWindow(), and ~MusicWebDJRadioWidget().
MusicWebDJRadioQueryWidget* MusicWebDJRadioWidget::m_queryTableWidget protected
Definition at line 165 of file musicwebdjradiowidget.h.
Referenced by MusicWebDJRadioWidget(), programItemClicked(), resizeWindow(), and ~MusicWebDJRadioWidget().
MusicWebDJRadioProgramWidget* MusicWebDJRadioWidget::m_recommendWidget protected
Definition at line 164 of file musicwebdjradiowidget.h.
Referenced by createRecommendWidget(), MusicWebDJRadioWidget(), resizeWindow(), and ~MusicWebDJRadioWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiowidget.cpp