TTKMusicplayer: QNMac Class Reference
QNMac Class Reference
The namespace of the qiniu mac.
#include <qnmac.h>
Public Member Functions
QNMac (const QString &accessKey, const QByteArray &secretKey)
QString sign (const QByteArray &data) const
QString signWithData (const QByteArray &data) const
QString signWithData2 (const QByteArray &data) const
QString signRequest (const QUrl &reqestUrl, const QByteArray &bodyData=0) const
QString signRequest (const QNetworkRequest &request, const QByteArray &bodyData=0) const
Detailed Description
The namespace of the qiniu mac.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 31 of file qnmac.h.
Constructor & Destructor Documentation
QNMac::QNMac (const QString & accessKey, const QByteArray & secretKey)
Object contsructor.
Definition at line 23 of file qnmac.cpp.
References MUSIC_D, and MUSIC_INIT_PRIVATE.
Member Function Documentation
QString QNMac::sign (const QByteArray & data) const
Qiniu to sign.
Definition at line 37 of file qnmac.cpp.
References QNUtils::hmacSha1(), MUSIC_D, and QNUtils::urlSafeBase64Encode().
QString QNMac::signRequest (const QUrl & reqestUrl, const QByteArray & bodyData = 0) const
Qiniu to sign request.
Definition at line 84 of file qnmac.cpp.
References QNUtils::hmacSha1(), MUSIC_D, QNUtils::urlQuery(), and QNUtils::urlSafeBase64Encode().
Referenced by QNIOHelper::deleteRequest(), QNIOHelper::listRequest(), and signRequest().
QString QNMac::signRequest (const QNetworkRequest & request, const QByteArray & bodyData = 0) const
Qiniu to sign request.
Definition at line 110 of file qnmac.cpp.
References signRequest().
QString QNMac::signWithData (const QByteArray & data) const
Qiniu to sign with data.
Definition at line 55 of file qnmac.cpp.
References QNUtils::hmacSha1(), MUSIC_D, and QNUtils::urlSafeBase64Encode().
Referenced by QNPutPolicy::makeUploadToken().
QString QNMac::signWithData2 (const QByteArray & data) const
Qiniu to sign with data2.
Definition at line 67 of file qnmac.cpp.
References QNUtils::hmacSha1(), MUSIC_D, and QNUtils::urlSafeBase64Encode().
Referenced by QNPutPolicy::makeDownloadToken().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnmac.h
TTKThirdParty/TTKExtras/qiniu/qnmac.cpp