TTKMusicplayer: QHttpConnectionPrivate Class Reference
QHttpConnectionPrivate Class Reference
The class of the http connection private.
Public Member Functions
QHttpConnectionPrivate ()
~QHttpConnectionPrivate ()
void invalidateRequest ()
void writeCount (qint64 count)
void write (const QByteArray &data)
void parseRequest ()
Public Member Functions inherited from TTKPrivate< QHttpConnection >
TTKPrivate ()
virtual ~TTKPrivate ()
void setPublic (QHttpConnection *pub)
Static Public Member Functions
static int MessageBegin (http_parser *parser)
static int Url (http_parser *parser, const char *at, size_t length)
static int HeaderField (http_parser *parser, const char *at, size_t length)
static int HeaderValue (http_parser *parser, const char *at, size_t length)
static int HeadersComplete (http_parser *parser)
static int Body (http_parser *parser, const char *at, size_t length)
static int MessageComplete (http_parser *parser)
Public Attributes
QHttpConnection * m_parentClass
QTcpSocket * m_socket
http_parser * m_parser
http_parser_settings * m_parserSettings
QHttpRequest * m_request
QByteArray m_currentUrl
HeaderHash m_currentHeaders
QString m_currentHeaderField
QString m_currentHeaderValue
qint64 m_transmitLen
qint64 m_transmitPos
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QHttpConnection >
QHttpConnection * ttk_q () const
Detailed Description
The class of the http connection private.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 13 of file qhttpconnection.cpp.
Constructor & Destructor Documentation
QHttpConnectionPrivate::QHttpConnectionPrivate ()
Definition at line 52 of file qhttpconnection.cpp.
References Body(), http_parser::data, HeaderField(), HeadersComplete(), HeaderValue(), http_parser_init(), HTTP_REQUEST, m_parser, m_parserSettings, MessageBegin(), MessageComplete(), http_parser_settings::on_body, http_parser_settings::on_header_field, http_parser_settings::on_header_value, http_parser_settings::on_headers_complete, http_parser_settings::on_message_begin, http_parser_settings::on_message_complete, http_parser_settings::on_url, and Url().
QHttpConnectionPrivate::~QHttpConnectionPrivate ()
Definition at line 75 of file qhttpconnection.cpp.
References m_parser, m_parserSettings, and m_socket.
Member Function Documentation
int QHttpConnectionPrivate::Body (http_parser * parser, const char * at, size_t length) static
Definition at line 353 of file qhttpconnection.cpp.
References QHttpRequest::data(), http_parser::data, m_request, and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
int QHttpConnectionPrivate::HeaderField (http_parser * parser, const char * at, size_t length) static
Definition at line 320 of file qhttpconnection.cpp.
References http_parser::data, m_currentHeaderField, m_currentHeaders, m_currentHeaderValue, m_request, and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
int QHttpConnectionPrivate::HeadersComplete (http_parser * parser) static
set method
set version
get parsed url
set client information
Definition at line 257 of file qhttpconnection.cpp.
References createUrl(), http_parser::data, http_parser::http_major, http_parser::http_minor, http_parser_parse_url(), m_currentHeaderField, m_currentHeaders, m_currentHeaderValue, m_currentUrl, m_parentClass, m_request, m_socket, http_parser::method, QHttpConnection::newRequest(), QHttpRequest::setHeaders(), QHttpResponse::setKeepAlive(), QHttpRequest::setMethod(), QHttpRequest::setRemoteAddress(), QHttpRequest::setRemotePort(), QHttpRequest::setUrl(), QHttpRequest::setVersion(), and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
int QHttpConnectionPrivate::HeaderValue (http_parser * parser, const char * at, size_t length) static
Definition at line 343 of file qhttpconnection.cpp.
References http_parser::data, m_currentHeaderValue, m_request, and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
void QHttpConnectionPrivate::invalidateRequest ()
Definition at line 87 of file qhttpconnection.cpp.
References QHttpRequest::end(), m_request, and QHttpRequest::successful().
Referenced by MessageBegin().
int QHttpConnectionPrivate::MessageBegin (http_parser * parser) static
Definition at line 239 of file qhttpconnection.cpp.
References http_parser::data, invalidateRequest(), m_currentHeaders, m_currentUrl, m_parentClass, m_request, and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
int QHttpConnectionPrivate::MessageComplete (http_parser * parser) static
Definition at line 300 of file qhttpconnection.cpp.
References http_parser::data, QHttpRequest::end(), m_request, QHttpRequest::setSuccessful(), and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
void QHttpConnectionPrivate::parseRequest ()
Definition at line 111 of file qhttpconnection.cpp.
References http_parser_execute(), m_parser, m_parserSettings, and m_socket.
int QHttpConnectionPrivate::Url (http_parser * parser, const char * at, size_t length) static
Definition at line 311 of file qhttpconnection.cpp.
References http_parser::data, m_currentUrl, m_request, and TTKStatic_cast.
Referenced by QHttpConnectionPrivate().
void QHttpConnectionPrivate::write (const QByteArray & data)
Definition at line 122 of file qhttpconnection.cpp.
References m_socket, and m_transmitLen.
void QHttpConnectionPrivate::writeCount (qint64 count)
Definition at line 97 of file qhttpconnection.cpp.
References QHttpConnection::allBytesWritten(), m_parentClass, m_transmitLen, and m_transmitPos.
Member Data Documentation
QString QHttpConnectionPrivate::m_currentHeaderField
Definition at line 43 of file qhttpconnection.cpp.
Referenced by HeaderField(), and HeadersComplete().
HeaderHash QHttpConnectionPrivate::m_currentHeaders
Definition at line 42 of file qhttpconnection.cpp.
Referenced by HeaderField(), HeadersComplete(), and MessageBegin().
QString QHttpConnectionPrivate::m_currentHeaderValue
Definition at line 44 of file qhttpconnection.cpp.
Referenced by HeaderField(), HeadersComplete(), and HeaderValue().
QByteArray QHttpConnectionPrivate::m_currentUrl
Definition at line 40 of file qhttpconnection.cpp.
Referenced by HeadersComplete(), MessageBegin(), and Url().
QHttpConnection* QHttpConnectionPrivate::m_parentClass
Definition at line 32 of file qhttpconnection.cpp.
Referenced by HeadersComplete(), MessageBegin(), and writeCount().
http_parser* QHttpConnectionPrivate::m_parser
Definition at line 34 of file qhttpconnection.cpp.
Referenced by parseRequest(), QHttpConnectionPrivate(), and ~QHttpConnectionPrivate().
http_parser_settings* QHttpConnectionPrivate::m_parserSettings
Definition at line 35 of file qhttpconnection.cpp.
Referenced by parseRequest(), QHttpConnectionPrivate(), and ~QHttpConnectionPrivate().
QHttpRequest* QHttpConnectionPrivate::m_request
Definition at line 38 of file qhttpconnection.cpp.
Referenced by Body(), HeaderField(), HeadersComplete(), HeaderValue(), invalidateRequest(), MessageBegin(), MessageComplete(), and Url().
QTcpSocket* QHttpConnectionPrivate::m_socket
Definition at line 33 of file qhttpconnection.cpp.
Referenced by HeadersComplete(), parseRequest(), write(), and ~QHttpConnectionPrivate().
qint64 QHttpConnectionPrivate::m_transmitLen
Definition at line 47 of file qhttpconnection.cpp.
Referenced by write(), and writeCount().
qint64 QHttpConnectionPrivate::m_transmitPos
Definition at line 48 of file qhttpconnection.cpp.
Referenced by writeCount().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qhttpserver/qhttpconnection.cpp