TTKMusicPlayer: TTK::String Namespace Reference
TTK::String Namespace Reference
Functions
TTK_MODULE_EXPORT QString lrcDirPrefix ()
TTK_MODULE_EXPORT QString musicDirPrefix ()
TTK_MODULE_EXPORT QString pefix (const QString &name)
TTK_MODULE_EXPORT QString pefix (const QString &name, const QString &prefix)
TTK_MODULE_EXPORT QString suffix (const QString &name)
TTK_MODULE_EXPORT QString suffix (const QString &name, const QString &suffix)
TTK_MODULE_EXPORT QString slitToken (const QString &name)
TTK_MODULE_EXPORT QString slitToken (const QString &name, const QString &prefix, const QString &suffix, bool revert=true)
TTK_MODULE_EXPORT QStringList split (const QString &value, const QString &key=TTK_DEFAULT_STR)
TTK_MODULE_EXPORT QString removeToken (const QString &value, const QString &key=" ")
TTK_MODULE_EXPORT bool isChinese (const QChar &c)
TTK_MODULE_EXPORT bool isNetworkUrl (const QString &path)
TTK_MODULE_EXPORT QString songName (const QString &value, const QString &key=TTK_DEFAULT_STR)
TTK_MODULE_EXPORT QString artistName (const QString &value, const QString &key=TTK_DEFAULT_STR)
TTK_MODULE_EXPORT QString convertHtmlToPlain (const QString &value)
TTK_MODULE_EXPORT QStringList illegalCharacters ()
TTK_MODULE_EXPORT bool isCharacterValid (const QString &value)
TTK_MODULE_EXPORT QString charactersReplace (const QString &value)
Function Documentation
QString TTK::String::artistName (const QString & value, const QString & key = TTK_DEFAULT_STR)
Get song artist name.
Definition at line 121 of file musicstringutils.cpp.
References split().
Referenced by MusicItemSearchTableWidget::actionGroupClick(), MusicSong::artistFront(), MusicDownloadStatusModule::checkArtistBackgroundValid(), MusicDownloadStatusModule::checkArtistCoverValid(), MusicDownloadStatusModule::currentMetaDataDownload(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicDownloadWidget::matchMusicSongInformation(), MusicBackgroundManager::setArtistName(), MusicLrcMakerWidget::setCurrentSongName(), MusicSongSharingWidget::setData(), MusicRemoteWidgetForComplexStyle::setLabelText(), MusicSongsListPlayWidget::setParameter(), MusicAlbumQueryWidget::setSongName(), MusicArtistQueryWidget::setSongName(), and MusicSongsListPlayWidget::updateCurrentArtist().
QString TTK::String::charactersReplace (const QString & value)
Illegal characters replaced.
Definition at line 159 of file musicstringutils.cpp.
References convertHtmlToPlain(), and illegalCharacters().
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicMVRadioProgramRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicSongRecommendRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicFMRadioSongRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicSongSuggestRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicKWQueryRequest::downLoadSingleFinished(), MusicWYQueryRequest::downLoadSingleFinished(), MusicKGQueryRequest::downLoadSingleFinished(), MusicSongMeta::findLegalDataString(), MusicWYQueryMovieRequest::parseFromMovieList(), and MusicWYQueryMovieRequest::parseFromVideoList().
QString TTK::String::convertHtmlToPlain (const QString & value)
Html string to plain.
Definition at line 132 of file musicstringutils.cpp.
Referenced by charactersReplace(), and MusicKWQueryArtistRequest::queryArtistIntro().
QStringList TTK::String::illegalCharacters ()
Illegal characters.
Definition at line 139 of file musicstringutils.cpp.
Referenced by charactersReplace(), isCharacterValid(), and MusicItemRenameEidt::textChanged().
bool TTK::String::isCharacterValid (const QString & value)
Illegal characters check.
Definition at line 146 of file musicstringutils.cpp.
References illegalCharacters().
Referenced by MusicItemRenameEidt::textChanged().
bool TTK::String::isChinese (const QChar & c)
Check the given char is or not chinese character.
Definition at line 96 of file musicstringutils.cpp.
Referenced by MusicLrcPosterItemWidget::drawTheme16().
bool TTK::String::isNetworkUrl (const QString & path)
Check input url path is network path or not.
Definition at line 105 of file musicstringutils.cpp.
References HTTP_PREFIX, and HTTPS_PREFIX.
Referenced by MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicKWQueryMovieRequest::downLoadPageFinished(), TTK::generateNetworkSongPath(), MusicSongsSummariziedWidget::importMusicSongsByUrl(), and MusicKWInterface::makeCoverPixmapUrl().
QString TTK::String::lrcDirPrefix ()
Get lrc dir prefix path.
Definition at line 26 of file musicstringutils.cpp.
References MusicSettingManager::DownloadLrcDirPath, LRC_DIR_FULL, and makeFilePrefix().
Referenced by MusicDownloadStatusModule::checkLrcValid(), MusicLrcLocalLinkWidget::confirmButtonClicked(), MusicIdentifySongWidget::createDetectedSuccessedWidget(), MusicApplication::currentLrcUpdated(), MusicDownloadStatusModule::currentMetaDataDownload(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicLrcSearchTableWidget::downloadQuery(), TTK::generateSongList(), MusicApplication::loadCurrentSongLrc(), MusicWebFMRadioPlayWidget::lrcDownloadStateChanged(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), MusicConfigManager::readBuffer(), MusicLrcLocalLinkWidget::searchInLocalLrc(), and MusicLrcMakerWidget::setCurrentSongName().
QString TTK::String::musicDirPrefix ()
Get music dir prefix path.
Definition at line 31 of file musicstringutils.cpp.
References MusicSettingManager::DownloadMusicDirPath, makeFilePrefix(), and MUSIC_DIR_FULL.
Referenced by MusicAbstractDownloadTableWidget::createDownloadItem(), MusicCloudManagerTableWidget::downloadFileToServer(), and MusicConfigManager::readBuffer().
QString TTK::String::pefix (const QString & name)
Get string prefix path.
Definition at line 36 of file musicstringutils.cpp.
References TTK_DOT.
Referenced by MusicSongsSummariziedWidget::importMusicSongsByUrl(), and slitToken().
QString TTK::String::pefix (const QString & name, const QString & prefix)
Get string prefix path.
Definition at line 41 of file musicstringutils.cpp.
QString TTK::String::removeToken (const QString & value, const QString & key = " ")
Remove given key in string, default is space.
Definition at line 85 of file musicstringutils.cpp.
QString TTK::String::slitToken (const QString & name)
Get string splite path.
Definition at line 56 of file musicstringutils.cpp.
References TTK_DOT.
Referenced by MusicScreenSaverWidget::downLoadFinished(), MusicSongsSummariziedWidget::importMusicSongsByUrl(), MusicWYQueryMovieRequest::parseFromMovieList(), MusicMVRadioProgramRequest::parseFromMovieProperty(), MusicKGQueryMovieRequest::parseFromMovieProperty(), and MusicWYQueryMovieRequest::parseFromVideoList().
QString TTK::String::slitToken (const QString & name, const QString & prefix, const QString & suffix, bool revert = true)
Get string splite path.
Definition at line 61 of file musicstringutils.cpp.
References pefix(), and suffix().
QString TTK::String::songName (const QString & value, const QString & key = TTK_DEFAULT_STR)
Get song name.
Definition at line 110 of file musicstringutils.cpp.
References split().
Referenced by MusicItemSearchTableWidget::actionGroupClick(), MusicSong::artistBack(), MusicDownloadStatusModule::currentMetaDataDownload(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicDownloadWidget::matchMusicSongInformation(), MusicLrcMakerWidget::setCurrentSongName(), MusicRemoteWidgetForComplexStyle::setLabelText(), MusicSongsListPlayWidget::setParameter(), MusicRecommendQueryWidget::setSongName(), MusicSimilarQueryWidget::setSongName(), and MusicSongsListPlayWidget::updateCurrentArtist().
QStringList TTK::String::split (const QString & value, const QString & key = TTK_DEFAULT_STR)
Get split string value.
Definition at line 75 of file musicstringutils.cpp.
Referenced by artistName(), MusicSongsListPlayTableWidget::contextMenuEvent(), MusicDownloadStatusModule::currentMetaDataDownload(), MusicKGQueryAlbumRequest::downLoadSingleFinished(), MusicSplitItemClickedLabel::mouseMoveEvent(), MusicEMOJILabelWidget::MusicEMOJILabelWidget(), MusicCSVConfigManager::readBuffer(), MusicPLSConfigManager::readBuffer(), MusicTXTConfigManager::readBuffer(), MusicM3UConfigManager::readBuffer(), MusicSongsListPlayTableWidget::searchQueryByName(), MusicRemoteWidgetForComplexStyle::setLabelText(), and songName().
QString TTK::String::suffix (const QString & name)
Get string suffix path.
Definition at line 46 of file musicstringutils.cpp.
References TTK_DOT.
Referenced by MusicSpectrumWidget::createLightWidget(), MusicKWInterface::parseFromSongProperty(), MusicPlaylistManager::readSongItems(), MusicCloudFileInformationWidget::setFileInformation(), slitToken(), and MusicPlaylistManager::writeSongItem().
QString TTK::String::suffix (const QString & name, const QString & suffix)
Get string suffix path.
Definition at line 51 of file musicstringutils.cpp.