TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/split.c File Reference
split.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "qrencode.h"
#include "qrinput.h"
#include "qrspec.h"
#include "split.h"
Macros
#define isdigit(__c__) ((unsigned char)((signed char)(__c__) - '0') < 10)
#define isalnum(__c__) (QRinput_lookAnTable(__c__) >= 0)
Functions
char * strdup (const char *s)
static QRencodeMode Split_identifyMode (const char *string, QRencodeMode hint)
static int Split_eatAn (const char *string, QRinput *input, QRencodeMode hint)
static int Split_eat8 (const char *string, QRinput *input, QRencodeMode hint)
static int Split_eatNum (const char *string, QRinput *input, QRencodeMode hint)
static int Split_eatKanji (const char *string, QRinput *input, QRencodeMode hint)
static int Split_splitString (const char *string, QRinput *input, QRencodeMode hint)
static char * dupAndToUpper (const char *str, QRencodeMode hint)
int Split_splitStringToQRinput (const char *string, QRinput *input, QRencodeMode hint, int casesensitive)
Split the input string (null terminated) into QRinput.
Macro Definition Documentation
#define isalnum (__c__) (QRinput_lookAnTable(__c__) >= 0)
Definition at line 38 of file split.c.
Referenced by QAlgorithm::isBase64(), TTK::isBase64(), Split_eat8(), Split_eatAn(), and Split_identifyMode().
#define isdigit (__c__) ((unsigned char)((signed char)(__c__) - '0') < 10)
Definition at line 37 of file split.c.
Referenced by Split_eat8(), Split_eatAn(), Split_eatNum(), and Split_identifyMode().
Function Documentation
static char* dupAndToUpper (const char * str, QRencodeMode hint) static
Definition at line 277 of file split.c.
References QR_MODE_KANJI, Split_identifyMode(), and strdup().
Referenced by Split_splitStringToQRinput().
static int Split_eat8 (const char * string, QRinput * input, QRencodeMode hint) static
Definition at line 184 of file split.c.
References int(), isalnum, isdigit, QR_MODE_8, QR_MODE_AN, QR_MODE_KANJI, QR_MODE_NUM, QRinput_append(), QRinput_estimateBitsMode8(), QRinput_estimateBitsModeAn(), QRinput_estimateBitsModeNum(), QRspec_lengthIndicator(), Split_identifyMode(), and _QRinput::version.
Referenced by Split_eatAn(), Split_eatNum(), and Split_splitString().
static int Split_eatAn (const char * string, QRinput * input, QRencodeMode hint) static
Definition at line 119 of file split.c.
References int(), isalnum, isdigit, QR_MODE_AN, QR_MODE_NUM, QRinput_append(), QRinput_estimateBitsMode8(), QRinput_estimateBitsModeAn(), QRinput_estimateBitsModeNum(), QRspec_lengthIndicator(), Split_eat8(), and _QRinput::version.
Referenced by Split_eatNum(), and Split_splitString().
static int Split_eatKanji (const char * string, QRinput * input, QRencodeMode hint) static
Definition at line 167 of file split.c.
References int(), QR_MODE_KANJI, QRinput_append(), and Split_identifyMode().
Referenced by Split_splitString().
static int Split_eatNum (const char * string, QRinput * input, QRencodeMode hint) static
Definition at line 79 of file split.c.
References int(), isdigit, QR_MODE_8, QR_MODE_AN, QR_MODE_NUM, QRinput_append(), QRinput_estimateBitsMode8(), QRinput_estimateBitsModeAn(), QRinput_estimateBitsModeNum(), QRspec_lengthIndicator(), Split_eat8(), Split_eatAn(), Split_identifyMode(), and _QRinput::version.
Referenced by Split_splitString().
static QRencodeMode Split_identifyMode (const char * string, QRencodeMode hint) static
Definition at line 51 of file split.c.
References int(), isalnum, isdigit, QR_MODE_8, QR_MODE_AN, QR_MODE_KANJI, QR_MODE_NUL, and QR_MODE_NUM.
Referenced by dupAndToUpper(), Split_eat8(), Split_eatKanji(), Split_eatNum(), and Split_splitString().
static int Split_splitString (const char * string, QRinput * input, QRencodeMode hint) static
Definition at line 252 of file split.c.
References QR_MODE_AN, QR_MODE_KANJI, QR_MODE_NUM, Split_eat8(), Split_eatAn(), Split_eatKanji(), Split_eatNum(), and Split_identifyMode().
Referenced by Split_splitStringToQRinput().
int Split_splitStringToQRinput (const char * string, QRinput * input, QRencodeMode hint, int casesensitive)
Split the input string (null terminated) into QRinput.
Parameters
string input string
hint give QR_MODE_KANJI if the input string contains Kanji character encoded in Shift-JIS. If not, give QR_MODE_8.
casesensitive 0 for case-insensitive encoding (all alphabet characters are replaced to UPPER-CASE CHARACTERS.
Return values
0 success.
-1 an error occurred. errno is set to indicate the error. See Exceptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
Definition at line 301 of file split.c.
References dupAndToUpper(), free(), and Split_splitString().
Referenced by QRcode_encodeDataStructuredReal(), and QRcode_encodeStringReal().
char* strdup (const char * s)
Definition at line 42 of file split.c.
References malloc().
Referenced by dupAndToUpper().