TTKMusicplayer: MusicSongsToolBoxWidgetItem Class Reference
MusicSongsToolBoxWidgetItem Class Reference
The class of the tool box widget item.
#include <musicsongstoolboxwidget.h>
Signals
void addNewRowItem ()
void deleteRowItem (int index)
void deleteRowItemAll (int index)
void changRowItemName (int index, const QString &name)
void addNewFiles (int index)
void addNewDir (int index)
void musicListSongSortBy (int index)
void swapDragItemIndex (int before, int after)
Public Member Functions
MusicSongsToolBoxWidgetItem (int index, const QString &text, QWidget *parent=0)
~MusicSongsToolBoxWidgetItem ()
QWidget * item (int index)
void addItem (QWidget *item)
void removeItem (QWidget *item)
void setTitle (const QString &text)
QString getTitle () const
void setMusicSort (MusicSort *sort)
void setItemExpand (bool expand)
bool itemExpand () const
int count () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Attributes
QVBoxLayout * m_layout
QList< QWidget * > m_itemList
MusicSongsToolBoxTopWidget * m_topWidget
Detailed Description
The class of the tool box widget item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 227 of file musicsongstoolboxwidget.h.
Constructor & Destructor Documentation
MusicSongsToolBoxWidgetItem::MusicSongsToolBoxWidgetItem (int index, const QString & text, QWidget * parent = 0) explicit
Object contsructor.
Definition at line 408 of file musicsongstoolboxwidget.cpp.
References addNewDir(), addNewFiles(), addNewRowItem(), changRowItemName(), deleteRowItem(), deleteRowItemAll(), m_layout, m_topWidget, musicListSongSortBy(), and swapDragItemIndex().
MusicSongsToolBoxWidgetItem::~MusicSongsToolBoxWidgetItem ()
Definition at line 429 of file musicsongstoolboxwidget.cpp.
References m_layout, and m_topWidget.
Member Function Documentation
void MusicSongsToolBoxWidgetItem::addItem (QWidget * item)
Add widget item.
Definition at line 449 of file musicsongstoolboxwidget.cpp.
References m_itemList, and m_layout.
Referenced by MusicSongsToolBoxWidget::addItem().
void MusicSongsToolBoxWidgetItem::addNewDir (int index) signal
Add new music dir to list.
Referenced by MusicSongsToolBoxWidgetItem().
void MusicSongsToolBoxWidgetItem::addNewFiles (int index) signal
Add new music file or files to list.
Referenced by MusicSongsToolBoxWidgetItem().
void MusicSongsToolBoxWidgetItem::addNewRowItem () signal
Add new play list item.
Referenced by MusicSongsToolBoxWidgetItem().
void MusicSongsToolBoxWidgetItem::changRowItemName (int index, const QString & name) signal
Open rename selected play list item widget.
Referenced by MusicSongsToolBoxWidgetItem().
void MusicSongsToolBoxWidgetItem::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 504 of file musicsongstoolboxwidget.cpp.
int MusicSongsToolBoxWidgetItem::count () const
Get item's count.
Definition at line 494 of file musicsongstoolboxwidget.cpp.
References m_itemList.
Referenced by MusicSongsToolBoxWidget::getTitle(), MusicSongsToolBoxWidget::removeItem(), MusicSongsToolBoxWidget::setMusicSort(), and MusicSongsToolBoxWidget::setTitle().
void MusicSongsToolBoxWidgetItem::deleteRowItem (int index) signal
Delete selected play list item.
Referenced by MusicSongsToolBoxWidgetItem().
void MusicSongsToolBoxWidgetItem::deleteRowItemAll (int index) signal
Delete all items in play list item.
Referenced by MusicSongsToolBoxWidgetItem().
QString MusicSongsToolBoxWidgetItem::getClassName () static
Get class object name.
Definition at line 435 of file musicsongstoolboxwidget.cpp.
QString MusicSongsToolBoxWidgetItem::getTitle () const
Get title text.
Definition at line 466 of file musicsongstoolboxwidget.cpp.
References MusicSongsToolBoxTopWidget::getTitle(), and m_topWidget.
Referenced by MusicSongsToolBoxWidget::getTitle().
QWidget * MusicSongsToolBoxWidgetItem::item (int index)
Get widget item.
Definition at line 440 of file musicsongstoolboxwidget.cpp.
References m_itemList.
Referenced by MusicSongsToolBoxWidget::getTitle(), MusicSongsToolBoxWidget::removeItem(), MusicSongsToolBoxWidget::setMusicSort(), and MusicSongsToolBoxWidget::setTitle().
bool MusicSongsToolBoxWidgetItem::itemExpand () const
Get item widget expand state.
Definition at line 485 of file musicsongstoolboxwidget.cpp.
References m_itemList.
void MusicSongsToolBoxWidgetItem::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Definition at line 499 of file musicsongstoolboxwidget.cpp.
void MusicSongsToolBoxWidgetItem::musicListSongSortBy (int index) signal
Music list songs sort by type.
Referenced by MusicSongsToolBoxWidgetItem().
void MusicSongsToolBoxWidgetItem::removeItem (QWidget * item)
Remove widget item.
Definition at line 455 of file musicsongstoolboxwidget.cpp.
References m_itemList, and m_layout.
void MusicSongsToolBoxWidgetItem::setItemExpand (bool expand)
Set item widget to hide or not.
Definition at line 476 of file musicsongstoolboxwidget.cpp.
References m_itemList, m_topWidget, and MusicSongsToolBoxTopWidget::setItemExpand().
Referenced by MusicSongsToolBoxWidget::addItem().
void MusicSongsToolBoxWidgetItem::setMusicSort (MusicSort * sort)
Set music sort.
Definition at line 471 of file musicsongstoolboxwidget.cpp.
References m_topWidget, and MusicSongsToolBoxTopWidget::setMusicSort().
Referenced by MusicSongsToolBoxWidget::setMusicSort().
void MusicSongsToolBoxWidgetItem::setTitle (const QString & text)
Set title text.
Definition at line 461 of file musicsongstoolboxwidget.cpp.
References m_topWidget, and MusicSongsToolBoxTopWidget::setTitle().
Referenced by MusicSongsToolBoxWidget::setTitle().
void MusicSongsToolBoxWidgetItem::swapDragItemIndex (int before, int after) signal
Swap the item index by drag adn drop.
Referenced by MusicSongsToolBoxWidgetItem().
Member Data Documentation
QList<QWidget*> MusicSongsToolBoxWidgetItem::m_itemList protected
Definition at line 326 of file musicsongstoolboxwidget.h.
Referenced by addItem(), count(), item(), itemExpand(), removeItem(), and setItemExpand().
QVBoxLayout* MusicSongsToolBoxWidgetItem::m_layout protected
Definition at line 325 of file musicsongstoolboxwidget.h.
Referenced by addItem(), MusicSongsToolBoxWidgetItem(), removeItem(), and ~MusicSongsToolBoxWidgetItem().
MusicSongsToolBoxTopWidget* MusicSongsToolBoxWidgetItem::m_topWidget protected
Definition at line 327 of file musicsongstoolboxwidget.h.
Referenced by getTitle(), MusicSongsToolBoxWidgetItem(), setItemExpand(), setMusicSort(), setTitle(), and ~MusicSongsToolBoxWidgetItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicsongstoolboxwidget.h
TTKModule/TTKWidget/musicToolsKits/musicsongstoolboxwidget.cpp