TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/bitstream.h File Reference
bitstream.h File Reference
Classes
struct BitStream
Macros
#define BitStream_size(__bstream__) (__bstream__->length)
#define BitStream_reset(__bstream__) (__bstream__->length = 0)
Functions
BitStream * BitStream_new (void)
int BitStream_append (BitStream *bstream, BitStream *arg)
int BitStream_appendNum (BitStream *bstream, size_t bits, unsigned int num)
int BitStream_appendBytes (BitStream *bstream, size_t size, unsigned char *data)
unsigned char * BitStream_toByte (BitStream *bstream)
void BitStream_free (BitStream *bstream)
Macro Definition Documentation
#define BitStream_reset (__bstream__) (__bstream__->length = 0)
Definition at line 39 of file bitstream.h.
Referenced by QRinput_convertData(), and QRinput_splitQRinputToStruct().
#define BitStream_size (__bstream__) (__bstream__->length)
Definition at line 38 of file bitstream.h.
Referenced by BitStream_toByte(), QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), and QRinput_encodeBitStream().
Function Documentation
int BitStream_append (BitStream * bstream, BitStream * arg)
Definition at line 128 of file bitstream.c.
References BitStream_expand(), BitStream::data, BitStream::datasize, and BitStream::length.
int BitStream_appendBytes (BitStream * bstream, size_t size, unsigned char * data)
Definition at line 166 of file bitstream.c.
References BitStream_expand(), BitStream_writeBytes(), BitStream::data, BitStream::datasize, and BitStream::length.
Referenced by QRinput_encodeMode8(), and QRinput_encodeModeFNC1Second().
int BitStream_appendNum (BitStream * bstream, size_t bits, unsigned int num)
Definition at line 150 of file bitstream.c.
References BitStream_expand(), BitStream_writeNum(), BitStream::data, BitStream::datasize, and BitStream::length.
Referenced by QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), QRinput_encodeMode8(), QRinput_encodeModeAn(), QRinput_encodeModeECI(), QRinput_encodeModeFNC1Second(), QRinput_encodeModeKanji(), QRinput_encodeModeNum(), and QRinput_encodeModeStructure().
void BitStream_free (BitStream * bstream)
Definition at line 223 of file bitstream.c.
References BitStream::data, and free().
Referenced by QRinput_getByteStream(), QRinput_List_freeEntry(), and QRinput_splitQRinputToStruct().
BitStream* BitStream_new (void)
Definition at line 31 of file bitstream.c.
References BitStream::data, BitStream::datasize, DEFAULT_BUFSIZE, free(), BitStream::length, and malloc().
Referenced by QRinput_getByteStream(), and QRinput_splitQRinputToStruct().
unsigned char* BitStream_toByte (BitStream * bstream)
Definition at line 182 of file bitstream.c.
References BitStream_size, BitStream::data, and malloc().
Referenced by QRinput_getByteStream().