TTKMusicPlayer: MusicSongSuggestRequest Class Reference
MusicSongSuggestRequest Class Reference
The class of the query suggest data from net.
#include <musicsongsuggestrequest.h>
Public Slots
virtual void downloadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downloadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicSongSuggestRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value)
const MusicResultDataItemList & items () const noexcept
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageTotalSize () const noexcept
int pageSize () const noexcept
void setPageSize (int page) noexcept
int totalSize () const noexcept
void setTotalSize (int size) noexcept
int pageIndex () const noexcept
void setPageIndex (int index) noexcept
bool pageValid () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value) noexcept
const QVariant header (const QString &key) const noexcept
Protected Attributes
MusicResultDataItemList m_items
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downloadDataChanged (const QString &bytes)
void downloadRawDataChanged (const QByteArray &bytes)
Detailed Description
The class of the query suggest data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicsongsuggestrequest.h.
Constructor & Destructor Documentation
MusicSongSuggestRequest::MusicSongSuggestRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicsongsuggestrequest.cpp.
Member Function Documentation
void MusicSongSuggestRequest::downloadFinished () final override virtual slot
Download data from net finished.
Definition at line 27 of file musicsongsuggestrequest.cpp.
References TTK::String::charactersReplace(), TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downloadDataChanged(), TTKAbstractNetwork::downloadFinished(), QJsonParseError::error, QJsonDocument::fromJson(), m_items, MusicResultDataItem::m_name, TTKAbstractNetwork::m_reply, QJsonParseError::NoError, qAsConst, TTK::toString(), QJsonDocument::toVariant(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
const MusicResultDataItemList& MusicSongSuggestRequest::items () const inline noexcept
Get suggest list items.
Definition at line 44 of file musicsongsuggestrequest.h.
Referenced by MusicSongSearchInteriorEdit::suggestDataChanged().
void MusicSongSuggestRequest::startToSearch (const QString & value) virtual
Start to search data by input data.
Definition at line 12 of file musicsongsuggestrequest.cpp.
References TTKAbstractNetwork::deleteAll(), downloadFinished(), TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, ReqKGInterface::makeRequestRawHeader(), TTK::Algorithm::mdII(), QtNetworkErrorConnect, QUERY_URL, MusicAbstractNetwork::replyError(), TTK_INFO_STREAM, and TTK_SLOT.
Referenced by MusicSongSearchInteriorEdit::textChanged().
Member Data Documentation
MusicResultDataItemList MusicSongSuggestRequest::m_items protected
Definition at line 53 of file musicsongsuggestrequest.h.
Referenced by downloadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/musicsongsuggestrequest.h
TTKModule/TTKCore/musicNetworkKits/music/musicsongsuggestrequest.cpp