TTKMusicPlayer: MusicConfigModule Class Reference
MusicConfigModule Class Reference
The class of the initialize module.
#include <musicconfigmodule.h>
Public Member Functions
MusicConfigModule (QObject *parent=nullptr)
void valid () const
void initialize () const
void reset () const
Private Member Functions
void directoryExist (const QString &name) const
void checkDirectoryExist () const
void checkFileNeededExist () const
void copyFileOverwrite (const QString &origin, const QString &des) const
void copyFile (const QString &origin, const QString &des) const
Detailed Description
The class of the initialize module.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicconfigmodule.h.
Constructor & Destructor Documentation
MusicConfigModule::MusicConfigModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musicconfigmodule.cpp.
Member Function Documentation
void MusicConfigModule::checkDirectoryExist () const private
Check related dir is exist.
Definition at line 43 of file musicconfigmodule.cpp.
References directoryExist(), TTK_ART_DIR_FULL, TTK_BACKGROUND_DIR_FULL, TTK_CACHE_DIR_FULL, TTK_LANGUAGE_DIR_FULL, TTK_LRC_DIR_FULL, TTK_MUSIC_DIR_FULL, TTK_PLUGINS_DIR_FULL, TTK_THEME_DIR_FULL, and TTK_USER_THEME_DIR_FULL.
Referenced by valid().
void MusicConfigModule::checkFileNeededExist () const private
Check related file is exist.
Definition at line 59 of file musicconfigmodule.cpp.
References copyFile(), MAIN_DIR_FULL, TTK_APP_MAIN_FULL, TTK_CLOUD_DOWN_PATH_FULL, TTK_CLOUD_UP_PATH_FULL, TTK_COFIG_PATH_FULL, TTK_NORMAL_DOWN_PATH_FULL, TTK_PLAYLIST_PATH_FULL, TTK_RESOURCE_DIR_FULL, TTK_SEARCH_PATH_FULL, and TTK_SERVICE_FULL.
Referenced by valid().
void MusicConfigModule::copyFile (const QString & origin, const QString & des) const private
Copy file.
Definition at line 98 of file musicconfigmodule.cpp.
Referenced by checkFileNeededExist().
void MusicConfigModule::copyFileOverwrite (const QString & origin, const QString & des) const private
Copy file by overwrite.
Definition at line 87 of file musicconfigmodule.cpp.
Referenced by initialize(), and reset().
void MusicConfigModule::directoryExist (const QString & name) const private
Check current dir is exist, no, just create it.
Definition at line 34 of file musicconfigmodule.cpp.
Referenced by checkDirectoryExist().
void MusicConfigModule::initialize () const
Init parameters.
Definition at line 17 of file musicconfigmodule.cpp.
References copyFileOverwrite(), TTK_CLOUD_DOWN_PATH_FULL, TTK_CLOUD_UP_PATH_FULL, TTK_COFIG_PATH_FULL, TTK_NORMAL_DOWN_PATH_FULL, TTK_PLAYLIST_PATH_FULL, TTK_SEARCH_PATH_FULL, and valid().
Referenced by main().
void MusicConfigModule::reset () const
Reset config parameters.
Definition at line 29 of file musicconfigmodule.cpp.
References copyFileOverwrite(), and TTK_COFIG_PATH_FULL.
Referenced by main().
void MusicConfigModule::valid () const
Check current setting file's validation.
Definition at line 11 of file musicconfigmodule.cpp.
References checkDirectoryExist(), and checkFileNeededExist().
Referenced by initialize(), and main().
The documentation for this class was generated from the following files:
TTKConfig/musicconfigmodule.h
TTKConfig/musicconfigmodule.cpp