TTKMusicPlayer: MusicDownLoadManager Class Reference
MusicDownLoadManager Class Reference
The class of the produce the download manager.
#include <musicdownloadmanager.h>
Public Member Functions
void connectNetworkMultiValue (QObject *object)
void removeNetworkMultiValue (QObject *object)
void connectMusicDownload (const MusicDownLoadPairData &pair)
void reconnectMusicDownload (const MusicDownLoadPairData &pair)
void removeMusicDownload (const MusicDownLoadPairData &pair)
Private Slots
void downloadProgressChanged (float percent, const QString &total, qint64 time)
Private Attributes
QObjectList m_queueList
QList< MusicDownLoadPairData > m_pairList
Detailed Description
The class of the produce the download manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 70 of file musicdownloadmanager.h.
Member Function Documentation
void MusicDownLoadManager::connectMusicDownload (const MusicDownLoadPairData & pair)
Set music data network connection object.
Definition at line 26 of file musicdownloadmanager.cpp.
References MusicObject::CloudDownload, MusicObject::CloudUpload, downloadProgressChanged(), G_CONNECTION_PTR, MusicDownLoadPairData::m_object, m_pairList, MusicDownLoadPairData::m_type, and MusicObject::NormalDownload.
void MusicDownLoadManager::connectNetworkMultiValue (QObject * object)
Set mutiple network connection object.
Definition at line 7 of file musicdownloadmanager.cpp.
References G_CONNECTION_PTR, and m_queueList.
void MusicDownLoadManager::downloadProgressChanged (float percent, const QString & total, qint64 time) private slot
Update download percent total time and current time progress.
Definition at line 71 of file musicdownloadmanager.cpp.
References removeMusicDownload().
Referenced by connectMusicDownload(), and reconnectMusicDownload().
void MusicDownLoadManager::reconnectMusicDownload (const MusicDownLoadPairData & pair)
Reset music data network connection object.
Definition at line 48 of file musicdownloadmanager.cpp.
References downloadProgressChanged(), MusicDownLoadPairData::m_object, and m_pairList.
void MusicDownLoadManager::removeMusicDownload (const MusicDownLoadPairData & pair)
Remove music data network connection object.
Definition at line 62 of file musicdownloadmanager.cpp.
References m_pairList.
Referenced by downloadProgressChanged().
void MusicDownLoadManager::removeNetworkMultiValue (QObject * object)
Remove mutiple network connection object.
Definition at line 17 of file musicdownloadmanager.cpp.
References m_queueList.
Member Data Documentation
QList<MusicDownLoadPairData> MusicDownLoadManager::m_pairList private
Definition at line 105 of file musicdownloadmanager.h.
Referenced by connectMusicDownload(), reconnectMusicDownload(), and removeMusicDownload().
QObjectList MusicDownLoadManager::m_queueList private
Definition at line 104 of file musicdownloadmanager.h.
Referenced by connectNetworkMultiValue(), and removeNetworkMultiValue().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadmanager.h
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadmanager.cpp