TTKMusicPlayer: MusicScreenSaverListWidget Class Reference
MusicScreenSaverListWidget Class Reference
The class of the screen saver list widget.
#include <musicscreensaverwidget.h>
Public Member Functions
MusicScreenSaverListWidget (QWidget *parent=nullptr)
~MusicScreenSaverListWidget ()
void addCellItem (QObject *object, const QString &path, int index, bool status)
void resizeWindow ()
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
QGridLayout * m_gridLayout
QList< MusicScreenSaverListItem * > m_items
Detailed Description
The class of the screen saver list widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 129 of file musicscreensaverwidget.h.
Constructor & Destructor Documentation
MusicScreenSaverListWidget::MusicScreenSaverListWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 156 of file musicscreensaverwidget.cpp.
References m_gridLayout.
MusicScreenSaverListWidget::~MusicScreenSaverListWidget ()
Object destructor.
Definition at line 165 of file musicscreensaverwidget.cpp.
References m_items.
Member Function Documentation
void MusicScreenSaverListWidget::addCellItem (QObject * object, const QString & path, int index, bool status)
Create cell item by input data.
Definition at line 170 of file musicscreensaverwidget.cpp.
References m_gridLayout, m_items, MusicScreenSaverListItem::setFilePath(), and MusicScreenSaverListItem::setStatus().
Referenced by MusicScreenSaverWidget::downLoadFinished().
void MusicScreenSaverListWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 195 of file musicscreensaverwidget.cpp.
References resizeWindow().
void MusicScreenSaverListWidget::resizeWindow ()
Resize window bound by resize called.
Definition at line 180 of file musicscreensaverwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, m_items, and qAsConst.
Referenced by resizeEvent(), and MusicScreenSaverWidget::resizeWidget().
Member Data Documentation
QGridLayout* MusicScreenSaverListWidget::m_gridLayout private
Definition at line 158 of file musicscreensaverwidget.h.
Referenced by addCellItem(), MusicScreenSaverListWidget(), and resizeWindow().
QList<MusicScreenSaverListItem*> MusicScreenSaverListWidget::m_items private
Definition at line 159 of file musicscreensaverwidget.h.
Referenced by addCellItem(), resizeWindow(), and ~MusicScreenSaverListWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.cpp