TTKMusicPlayer: MusicQmmpPluginWidget Class Reference
MusicQmmpPluginWidget Class Reference
The class of the qmmp plugin manager widget.
#include <musicpluginwidget.h>
Public Slots
void pluginItemChanged (QTreeWidgetItem *item, int column)
void pluginButtonClicked ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Public Member Functions
MusicQmmpPluginWidget (QWidget *parent=nullptr)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show) noexcept
void blockOption (bool block) noexcept
Private Member Functions
void loadPluginsInfo ()
Private Attributes
Ui::MusicQmmpPluginWidget * m_ui
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label) noexcept
Protected Attributes inherited from TTKAbstractMoveDialog
QPoint m_mousePressedAt
bool m_blockOption
bool m_shadowOption
bool m_mouseLeftPressed
Detailed Description
The class of the qmmp plugin manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicpluginwidget.h.
Constructor & Destructor Documentation
MusicQmmpPluginWidget::MusicQmmpPluginWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 178 of file musicpluginwidget.cpp.
References TTK::UI::BackgroundStyle01, TTK::UI::CheckBoxStyle01, TTK::UI::ComboBoxStyle01, TTKAbstractItemDelegate::DisplayMode, TTKAbstractItemDelegate::ElideMode, TTK::UI::GroupBoxStyle01, TTK::UI::LineEditStyle01, loadPluginsInfo(), m_ui, pluginButtonClicked(), pluginItemChanged(), TTK::UI::PushButtonStyle03, TTK::UI::PushButtonStyle12, TTK::UI::RadioButtonStyle01, TTK::UI::ScrollBarStyle01, TTK::UI::ScrollBarStyle03, TTKLabelItemDelegate::setAlignment(), MusicWidgetRenderer::setBackgroundLabel(), TTKAbstractItemDelegate::setModuleMode(), TTKAbstractItemDelegate::setStyleSheet(), TTK::UI::SliderStyle06, TTK::UI::SpinBoxStyle01, TTK::UI::ToolButtonStyle04, and TTKAbstractItemDelegate::TreeMode.
Member Function Documentation
void MusicQmmpPluginWidget::loadPluginsInfo () private
Load plugins info.
Definition at line 283 of file musicpluginwidget.cpp.
References Visual::factories(), Effect::factories(), Output::factories(), InputSource::factories(), Decoder::factories(), Visual::file(), Effect::file(), Output::file(), InputSource::file(), Decoder::file(), and m_ui.
Referenced by MusicQmmpPluginWidget().
void MusicQmmpPluginWidget::pluginButtonClicked () slot
Plugin item setting button click.
Definition at line 274 of file musicpluginwidget.cpp.
References m_ui, MusicQmmpPluginItem::showSettingWidget(), and TTKDynamicCast.
Referenced by MusicQmmpPluginWidget().
void MusicQmmpPluginWidget::pluginItemChanged (QTreeWidgetItem * item, int column) slot
Plugin item clicked changed.
Definition at line 240 of file musicpluginwidget.cpp.
References MusicQmmpPluginItem::hasSettings(), m_ui, MusicQmmpPluginItem::PluginDecoder, MusicQmmpPluginItem::PluginOutput, MusicQmmpPluginItem::PluginTransports, TTK_CHECKED_ROLE, TTKDynamicCast, and TTKStaticCast.
Referenced by MusicQmmpPluginWidget().
Member Data Documentation
Ui::MusicQmmpPluginWidget* MusicQmmpPluginWidget::m_ui private
Definition at line 60 of file musicpluginwidget.h.
Referenced by loadPluginsInfo(), MusicQmmpPluginWidget(), pluginButtonClicked(), and pluginItemChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.cpp