TTKMusicPlayer: QDlnaFinder Class Reference
QDlnaFinder Class Reference
The class of the dlna finder.
#include <qdlnafinder.h>
Public Slots
void handleReadyRead ()
Signals
void finished ()
Public Member Functions
QDlnaFinder (QObject *parent=nullptr)
void find ()
QDlnaClient * client (int index) const
QList< QDlnaClient * > clients () const
QStringList clientNames () const
Detailed Description
The class of the dlna finder.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file qdlnafinder.h.
Constructor & Destructor Documentation
QDlnaFinder::QDlnaFinder (QObject * parent = nullptr) explicit
Definition at line 69 of file qdlnafinder.cpp.
References handleReadyRead(), TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
QDlnaClient * QDlnaFinder::client (int index) const
Definition at line 83 of file qdlnafinder.cpp.
References TTK_D.
Referenced by clientNames(), handleReadyRead(), and MusicSongDlnaTransferWidget::musicPlay().
QStringList QDlnaFinder::clientNames () const
Definition at line 100 of file qdlnafinder.cpp.
References client(), QDlnaClient::serverName(), and TTK_D.
Referenced by MusicSongDlnaTransferWidget::scanFinished().
QList< QDlnaClient * > QDlnaFinder::clients () const
Definition at line 94 of file qdlnafinder.cpp.
References TTK_D.
void QDlnaFinder::find ()
Definition at line 77 of file qdlnafinder.cpp.
References TTK_D.
Referenced by MusicSongDlnaTransferWidget::startToScan().
void QDlnaFinder::finished () signal
Referenced by handleReadyRead().
void QDlnaFinder::handleReadyRead () slot
Definition at line 111 of file qdlnafinder.cpp.
References client(), QDlnaClient::connect(), DEFAULT_ROUTER_IP, finished(), QDlnaClient::isConnected(), QDlnaClient::server(), and TTK_D.
Referenced by QDlnaFinder().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/qdlnafinder.h
TTKThirdParty/TTKExtras/qdlna/qdlnafinder.cpp