TTKMusicPlayer: MusicPVCounterRequest Class Reference
MusicPVCounterRequest Class Reference
The class of the pv counter.
#include <musicpvcounterrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicPVCounterRequest (QObject *parent=nullptr)
void startToRequest ()
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the pv counter.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicpvcounterrequest.h.
Constructor & Destructor Documentation
MusicPVCounterRequest::MusicPVCounterRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musicpvcounterrequest.cpp.
Member Function Documentation
void MusicPVCounterRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 49 of file musicpvcounterrequest.cpp.
References TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), TTKAbstractNetwork::downLoadFinished(), TTKAbstractXml::fromByteArray(), TTKAbstractNetwork::m_reply, TTKAbstractXml::readMultiTextByTagName(), TTK_DEFAULT_STR, and TTK_ERROR_STREAM.
Referenced by startToRequest().
void MusicPVCounterRequest::startToRequest ()
Start to download counter data.
Definition at line 14 of file musicpvcounterrequest.cpp.
References APPCACHE_DIR_FULL, TTKAbstractNetwork::downLoadDataChanged(), downLoadFinished(), TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, TTK::makeContentTypeHeader(), QSyncUtils::makeDataBucketUrl(), OS_COUNTER_URL, QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK::setSslConfiguration(), TTK::syncNetworkQueryForGet(), TTK_DEFAULT_STR, TTK_ERROR_STREAM, and TTK_SLOT.
Referenced by MusicApplicationModule::loadNetWorkSetting(), and MusicMessageAboutDialog::MusicMessageAboutDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicpvcounterrequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicpvcounterrequest.cpp