TTKMusicPlayer: MusicBackgroundDailyWidget Class Reference
MusicBackgroundDailyWidget Class Reference
The class of the daily background widget.
#include <musicbackgroundremotewidget.h>
Public Slots
virtual void downLoadFinished (const MusicSkinRemoteGroupList &bytes) overridefinal
Public Slots inherited from MusicBackgroundRemoteWidget
void downLoadFinished (const QString &bytes)
virtual void downLoadFinished (const MusicSkinRemoteGroupList &bytes)
Public Member Functions
MusicBackgroundDailyWidget (QWidget *parent=nullptr)
void initialize ()
virtual void outputRemoteSkin (MusicBackgroundImage &image, const QString &data) overridefinal
Public Member Functions inherited from MusicBackgroundRemoteWidget
MusicBackgroundRemoteWidget (QWidget *parent=nullptr)
~MusicBackgroundRemoteWidget ()
void abort ()
Additional Inherited Members
Protected Member Functions inherited from MusicBackgroundRemoteWidget
void startRequest (const QString &suffix)
Protected Attributes inherited from MusicBackgroundRemoteWidget
int m_currentIndex
MusicSkinRemoteGroupList m_groups
MusicBackgroundListWidget * m_backgroundList
MusicDownloadQueueRequest * m_downloadQueue
MusicAbstractDownloadSkinRequest * m_downloadRequest
Detailed Description
The class of the daily background widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 84 of file musicbackgroundremotewidget.h.
Constructor & Destructor Documentation
MusicBackgroundDailyWidget::MusicBackgroundDailyWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 90 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::m_backgroundList, MusicBackgroundRemoteWidget::m_currentIndex, MusicBackgroundListWidget::setType(), and MusicBackgroundListWidget::Third.
Member Function Documentation
void MusicBackgroundDailyWidget::downLoadFinished (const MusicSkinRemoteGroupList & bytes) final override virtual slot
Send download data from net.
Definition at line 131 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::downLoadFinished(), MusicBackgroundRemoteWidget::startRequest(), and TKM_FILE.
Referenced by initialize().
void MusicBackgroundDailyWidget::initialize ()
Init parameters.
Definition at line 97 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundListWidget::clearAllItems(), downLoadFinished(), MusicBackgroundRemoteWidget::m_backgroundList, MusicBackgroundRemoteWidget::m_downloadRequest, MusicBackgroundRemoteWidget::startRequest(), MusicAbstractDownloadSkinRequest::startRequest(), and TKM_FILE.
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundDailyWidget::outputRemoteSkin (MusicBackgroundImage & image, const QString & data) final override virtual
Output remote skin.
Implements MusicBackgroundRemoteWidget.
Definition at line 112 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::m_currentIndex, MusicBackgroundRemoteWidget::m_groups, MusicBackgroundImage::m_item, MusicSkinItem::m_name, MusicBackgroundImage::m_pix, and MusicSkinItem::m_useCount.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.cpp