TTKMusicplayer: TTKThirdParty/TTKExtras/qrencode/qrspec.h File Reference
qrspec.h File Reference
#include "qrencode.h"
Macros
#define QRSPEC_WIDTH_MAX 177
Maximum width of a symbol.
#define QRspec_rsBlockNum(__spec__) (__spec__[0] + __spec__[3])
#define QRspec_rsBlockNum1(__spec__) (__spec__[0])
#define QRspec_rsDataCodes1(__spec__) (__spec__[1])
#define QRspec_rsEccCodes1(__spec__) (__spec__[2])
#define QRspec_rsBlockNum2(__spec__) (__spec__[3])
#define QRspec_rsDataCodes2(__spec__) (__spec__[4])
#define QRspec_rsEccCodes2(__spec__) (__spec__[2])
#define QRspec_rsDataLength(__spec__)
#define QRspec_rsEccLength(__spec__) (QRspec_rsBlockNum(__spec__) * QRspec_rsEccCodes1(__spec__))
#define QRSPEC_MODEID_ECI 7
Mode indicator.
#define QRSPEC_MODEID_NUM 1
#define QRSPEC_MODEID_AN 2
#define QRSPEC_MODEID_8 4
#define QRSPEC_MODEID_KANJI 8
#define QRSPEC_MODEID_FNC1FIRST 5
#define QRSPEC_MODEID_FNC1SECOND 9
#define QRSPEC_MODEID_STRUCTURE 3
#define QRSPEC_MODEID_TERMINATOR 0
Functions
int QRspec_getDataLength (int version, QRecLevel level)
Return maximum data code length (bytes) for the version.
int QRspec_getECCLength (int version, QRecLevel level)
Return maximum error correction code length (bytes) for the version.
int QRspec_getMinimumVersion (int size, QRecLevel level)
Return a version number that satisfies the input code length.
int QRspec_getWidth (int version)
Return the width of the symbol for the version.
int QRspec_getRemainder (int version)
Return the numer of remainder bits.
int QRspec_lengthIndicator (QRencodeMode mode, int version)
Return the size of lenght indicator for the mode and version.
int QRspec_maximumWords (QRencodeMode mode, int version)
Return the maximum length for the mode and version.
void QRspec_getEccSpec (int version, QRecLevel level, int spec[5])
Return an array of ECC specification.
unsigned int QRspec_getVersionPattern (int version)
Return BCH encoded version information pattern that is used for the symbol of version 7 or greater.
unsigned int QRspec_getFormatInfo (int mask, QRecLevel level)
Return BCH encoded format information pattern.
unsigned char * QRspec_newFrame (int version)
Return a copy of initialized frame.
void QRspec_clearCache (void)
Clear the frame cache.
Macro Definition Documentation
#define QRSPEC_MODEID_8 4
Definition at line 174 of file qrspec.h.
Referenced by QRinput_encodeMode8().
#define QRSPEC_MODEID_AN 2
Definition at line 173 of file qrspec.h.
Referenced by QRinput_encodeModeAn().
#define QRSPEC_MODEID_ECI 7
Mode indicator.
See Table 2 of JIS X0510:2004, pp.16.
Definition at line 171 of file qrspec.h.
Referenced by QRinput_encodeModeECI().
#define QRSPEC_MODEID_FNC1FIRST 5
Definition at line 176 of file qrspec.h.
#define QRSPEC_MODEID_FNC1SECOND 9
Definition at line 177 of file qrspec.h.
Referenced by QRinput_encodeModeFNC1Second().
#define QRSPEC_MODEID_KANJI 8
Definition at line 175 of file qrspec.h.
Referenced by QRinput_encodeModeKanji().
#define QRSPEC_MODEID_NUM 1
Definition at line 172 of file qrspec.h.
Referenced by QRinput_encodeModeNum().
#define QRSPEC_MODEID_STRUCTURE 3
Definition at line 178 of file qrspec.h.
Referenced by QRinput_encodeModeStructure().
#define QRSPEC_MODEID_TERMINATOR 0
Definition at line 179 of file qrspec.h.
#define QRspec_rsBlockNum (__spec__) (__spec__[0] + __spec__[3])
Definition at line 108 of file qrspec.h.
Referenced by QRraw_new().
#define QRspec_rsBlockNum1 (__spec__) (__spec__[0])
Definition at line 109 of file qrspec.h.
Referenced by QRraw_new(), and RSblock_init().
#define QRspec_rsBlockNum2 (__spec__) (__spec__[3])
Definition at line 112 of file qrspec.h.
Referenced by RSblock_init().
#define QRspec_rsDataCodes1 (__spec__) (__spec__[1])
Definition at line 110 of file qrspec.h.
Referenced by RSblock_init().
#define QRspec_rsDataCodes2 (__spec__) (__spec__[4])
Definition at line 113 of file qrspec.h.
Referenced by RSblock_init().
#define QRspec_rsDataLength (__spec__)
Value:
((QRspec_rsBlockNum1(__spec__) * QRspec_rsDataCodes1(__spec__)) + \
         (QRspec_rsBlockNum2(__spec__) * QRspec_rsDataCodes2(__spec__)))
Definition at line 116 of file qrspec.h.
Referenced by QRraw_new().
#define QRspec_rsEccCodes1 (__spec__) (__spec__[2])
Definition at line 111 of file qrspec.h.
Referenced by RSblock_init().
#define QRspec_rsEccCodes2 (__spec__) (__spec__[2])
Definition at line 114 of file qrspec.h.
Referenced by RSblock_init().
#define QRspec_rsEccLength (__spec__) (QRspec_rsBlockNum(__spec__) * QRspec_rsEccCodes1(__spec__))
Definition at line 119 of file qrspec.h.
Referenced by QRraw_new().
#define QRSPEC_WIDTH_MAX 177
Maximum width of a symbol.
Definition at line 34 of file qrspec.h.
Referenced by Mask_evaluateSymbol().
Function Documentation
void QRspec_clearCache (void)
Clear the frame cache.
Typically for debug.
Definition at line 546 of file qrspec.c.
References frames, frames_mutex, and QRSPEC_VERSION_MAX.
Referenced by QRcode_clearCache().
int QRspec_getDataLength (int version, QRecLevel level)
Return maximum data code length (bytes) for the version.
Parameters
version
level
Returns
maximum size (bytes)
Definition at line 99 of file qrspec.c.
References QRspec_Capacity::ec, and QRspec_Capacity::words.
Referenced by QRinput_appendPaddingBit(), QRinput_splitQRinputToStruct(), and QRspec_getEccSpec().
int QRspec_getECCLength (int version, QRecLevel level)
Return maximum error correction code length (bytes) for the version.
Parameters
version
level
Returns
ECC size (bytes)
Definition at line 104 of file qrspec.c.
References QRspec_Capacity::ec.
Referenced by QRspec_getEccSpec().
void QRspec_getEccSpec (int version, QRecLevel level, int spec[5])
Return an array of ECC specification.
Parameters
version
level
spec an array of ECC specification contains as following: {# of type1 blocks, # of data code, # of ecc code,
of type2 blocks, # of data code}
Definition at line 235 of file qrspec.c.
References eccTable, QRspec_getDataLength(), and QRspec_getECCLength().
Referenced by QRraw_new().
unsigned int QRspec_getFormatInfo (int mask, QRecLevel level)
Return BCH encoded format information pattern.
Parameters
mask
level
Returns
BCH encoded format information pattern
Definition at line 384 of file qrspec.c.
References formatInfo.
Referenced by Mask_writeFormatInformation().
int QRspec_getMinimumVersion (int size, QRecLevel level)
Return a version number that satisfies the input code length.
Parameters
size input code length (byte)
level
Returns
version number
Definition at line 109 of file qrspec.c.
References QRspec_Capacity::ec, QRSPEC_VERSION_MAX, and QRspec_Capacity::words.
Referenced by QRinput_convertData(), and QRinput_estimateVersion().
int QRspec_getRemainder (int version)
Return the numer of remainder bits.
Parameters
version
Returns
number of remainder bits
Definition at line 127 of file qrspec.c.
References QRspec_Capacity::remainder.
Referenced by QRcode_encodeMask().
unsigned int QRspec_getVersionPattern (int version)
Return BCH encoded version information pattern that is used for the symbol of version 7 or greater.
Use lower 18 bits.
Parameters
version
Returns
BCH encoded version information pattern
Definition at line 365 of file qrspec.c.
References QRSPEC_VERSION_MAX, and versionPattern.
Referenced by QRspec_createFrame().
int QRspec_getWidth (int version)
Return the width of the symbol for the version.
Parameters
version
Returns
width
Definition at line 122 of file qrspec.c.
References QRspec_Capacity::width.
Referenced by QRcode_encodeMask().
int QRspec_lengthIndicator (QRencodeMode mode, int version)
Return the size of lenght indicator for the mode and version.
Parameters
mode
version
Returns
the size of the appropriate length indicator (bits).
Definition at line 143 of file qrspec.c.
References lengthTableBits, and QRinput_isSplittableMode().
Referenced by QRinput_encodeMode8(), QRinput_encodeModeAn(), QRinput_encodeModeKanji(), QRinput_encodeModeNum(), QRinput_estimateBitStreamSizeOfEntry(), QRinput_lengthOfCode(), Split_eat8(), Split_eatAn(), and Split_eatNum().
int QRspec_maximumWords (QRencodeMode mode, int version)
Return the maximum length for the mode and version.
Parameters
mode
version
Returns
the maximum length (bytes)
Definition at line 159 of file qrspec.c.
References lengthTableBits, QR_MODE_KANJI, and QRinput_isSplittableMode().
Referenced by QRinput_encodeBitStream(), and QRinput_lengthOfCode().
unsigned char* QRspec_newFrame (int version)
Return a copy of initialized frame.
When the same version is requested twice or more, a copy of cached frame is returned.
Parameters
version
Returns
Array of unsigned char. You can free it by free().
Definition at line 520 of file qrspec.c.
References frames, frames_mutex, QRspec_createFrame(), QRSPEC_VERSION_MAX, and QRspec_Capacity::width.
Referenced by QRcode_encodeMask().