TTKMusicPlayer: TTK::Url Namespace Reference
TTK::Url Namespace Reference
Functions
TTK_MODULE_EXPORT bool execute (const QString &path)
TTK_MODULE_EXPORT bool openUrl (const QString &path, bool local=true)
TTK_MODULE_EXPORT QString urlEncode (QString &data)
TTK_MODULE_EXPORT QString urlDecode (QString &data)
TTK_MODULE_EXPORT QByteArray urlEncode (QByteArray &data)
TTK_MODULE_EXPORT QByteArray urlDecode (QByteArray &data)
TTK_MODULE_EXPORT QString urlPrettyEncode (QString &data)
TTK_MODULE_EXPORT QString urlPrettyDecode (QString &data)
TTK_MODULE_EXPORT QByteArray urlPrettyEncode (QByteArray &data)
TTK_MODULE_EXPORT QByteArray urlPrettyDecode (QByteArray &data)
Function Documentation
bool TTK::Url::execute (const QString & path)
Execute file from local by path or other url.
Definition at line 13 of file musicurlutils.cpp.
Referenced by MusicSongRingtoneMaker::initOutputPath().
bool TTK::Url::openUrl (const QString & path, bool local = true)
Open file from local by path or other url.
Definition at line 23 of file musicurlutils.cpp.
References TTKPlatformSystem::LinuxUbuntu, TTKPlatformSystem::systemName(), and TTK_SEPARATOR.
Referenced by MusicLrcContainerForInterior::lrcOpenFileDir(), MusicFileInformationWidget::openFileDir(), MusicAbstractSongsListTableWidget::openFileDir(), MusicDownloadResetWidget::openFileLocation(), MusicSongSharingWidget::sendToShare(), MusicApplicationModule::showBugReportView(), and MusicSourceUpdateWidget::upgradeButtonClicked().
QString TTK::Url::urlDecode (QString & data)
Decode the data into url.
Definition at line 56 of file musicurlutils.cpp.
QByteArray TTK::Url::urlDecode (QByteArray & data)
Decode the data into url.
Definition at line 72 of file musicurlutils.cpp.
QString TTK::Url::urlEncode (QString & data)
Encode the data into url.
Definition at line 48 of file musicurlutils.cpp.
Referenced by ReqWYInterface::makeTokenRequest().
QByteArray TTK::Url::urlEncode (QByteArray & data)
Encode the data into url.
Definition at line 64 of file musicurlutils.cpp.
QString TTK::Url::urlPrettyDecode (QString & data)
Pretty decode the data into url.
Definition at line 90 of file musicurlutils.cpp.
QByteArray TTK::Url::urlPrettyDecode (QByteArray & data)
Pretty decode the data into url.
Definition at line 110 of file musicurlutils.cpp.
QString TTK::Url::urlPrettyEncode (QString & data)
Pretty encode the data into url.
Definition at line 80 of file musicurlutils.cpp.
Referenced by MusicBingTranslationRequest::startToRequest().
QByteArray TTK::Url::urlPrettyEncode (QByteArray & data)
Pretty encode the data into url.
Definition at line 100 of file musicurlutils.cpp.