TTKMusicPlayer: MusicItemQueryEdit Class Reference
MusicItemQueryEdit Class Reference
The class of the query line edit widget.
#include <musicitemsearchedit.h>
Signals
void trigger (const QString &text)
Public Member Functions
MusicItemQueryEdit (QWidget *parent=nullptr)
~MusicItemQueryEdit ()
MusicSearchEdit * editor () const
MusicSearchEdit * operator() () const
Private Slots
void enterFinished ()
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
Private Attributes
MusicSearchEdit * m_searchEdit
Detailed Description
The class of the query line edit widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 58 of file musicitemsearchedit.h.
Constructor & Destructor Documentation
MusicItemQueryEdit::MusicItemQueryEdit (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 38 of file musicitemsearchedit.cpp.
References MusicUIObject::BackgroundStyle01, enterFinished(), and m_searchEdit.
MusicItemQueryEdit::~MusicItemQueryEdit ()
Definition at line 62 of file musicitemsearchedit.cpp.
References m_searchEdit.
Member Function Documentation
MusicSearchEdit* MusicItemQueryEdit::editor () const inline
Get the line eidtor.
Definition at line 72 of file musicitemsearchedit.h.
Referenced by MusicLocalManagerWidget::itemDoubleClicked(), MusicLocalManagerWidget::MusicLocalManagerWidget(), MusicLocalManagerWidget::refreshItems(), MusicLocalManagerWidget::searchResultChanged(), MusicVideoPlayWidget::searchText(), MusicLocalManagerWidget::typeIndexChanged(), and MusicVideoPlayWidget::videoResearchButtonSearched().
void MusicItemQueryEdit::enterFinished () private slot
User input the enter key.
Definition at line 67 of file musicitemsearchedit.cpp.
References m_searchEdit, and trigger().
Referenced by MusicItemQueryEdit().
MusicSearchEdit* MusicItemQueryEdit::operator() () const inline
Definition at line 73 of file musicitemsearchedit.h.
void MusicItemQueryEdit::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 72 of file musicitemsearchedit.cpp.
void MusicItemQueryEdit::trigger (const QString & text) signal
Trigger the item.
Referenced by enterFinished().
Member Data Documentation
MusicSearchEdit* MusicItemQueryEdit::m_searchEdit private
Definition at line 93 of file musicitemsearchedit.h.
Referenced by enterFinished(), MusicItemQueryEdit(), and ~MusicItemQueryEdit().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicitemsearchedit.h
TTKModule/TTKWidget/musicSearchKits/musicitemsearchedit.cpp