TTKMusicPlayer: QDlnaClient Class Reference
QDlnaClient Class Reference
The class of the dlna client.
#include <qdlnaclient.h>
Public Member Functions
QDlnaClient (const QString &data)
QString server () const
QString serverName () const
bool connect () const
bool isConnected () const
bool openUri (const QString &url, const QString &name, int instance=0) const
bool openUris (const QString &url, const QString &name, int instance=0) const
bool nextUri (const QString &url, const QString &name, int instance=0) const
bool positionInfo (QDlna::PositionInfo &info, int instance=0) const
bool transportInfo (QDlna::TransportInfo &info, int instance=0) const
bool mediaInfo (QDlna::MediaInfo &info, int instance=0) const
bool play (int instance=0) const
bool pause (int instance=0) const
bool stop (int instance=0) const
bool remove (int instance=0) const
bool previous (int instance=0) const
bool next (int instance=0) const
bool setPlayMode (const QString &mode, int instance) const
Detailed Description
The class of the dlna client.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file qdlnaclient.h.
Constructor & Destructor Documentation
QDlnaClient::QDlnaClient (const QString & data) explicit
Definition at line 151 of file qdlnaclient.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
bool QDlnaClient::connect () const
Definition at line 170 of file qdlnaclient.cpp.
References TTK_D.
Referenced by QDlnaFinder::handleReadyRead().
bool QDlnaClient::isConnected () const
Definition at line 176 of file qdlnaclient.cpp.
References TTK_D.
Referenced by QDlnaFinder::handleReadyRead().
bool QDlnaClient::mediaInfo (QDlna::MediaInfo & info, int instance = 0) const
Definition at line 303 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::MediaInfo::duration, QDlnaXml::fromString(), QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), QDlna::MediaInfo::medium, QDlna::MediaInfo::nextURI, QDlnaXml::readTagNameValue(), QDlna::removeHttpHeader(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
bool QDlnaClient::next (int instance = 0) const
Definition at line 403 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
bool QDlnaClient::nextUri (const QString & url, const QString & name, int instance = 0) const
Definition at line 222 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), META_DATA, TTK_D, XML_FOOT, and XML_HEAD.
bool QDlnaClient::openUri (const QString & url, const QString & name, int instance = 0) const
Definition at line 182 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), META_DATA, TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
bool QDlnaClient::openUris (const QString & url, const QString & name, int instance = 0) const
Definition at line 201 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), META_DATA, TTK_D, XML_FOOT, and XML_HEAD.
bool QDlnaClient::pause (int instance = 0) const
Definition at line 347 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
bool QDlnaClient::play (int instance = 0) const
Definition at line 332 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
bool QDlnaClient::positionInfo (QDlna::PositionInfo & info, int instance = 0) const
Definition at line 246 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::PositionInfo::duration, QDlnaXml::fromString(), QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), QDlna::PositionInfo::position, QDlnaXml::readTagNameValue(), QDlna::removeHttpHeader(), TTK_D, valueToSecond(), XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::playSongAction().
bool QDlnaClient::previous (int instance = 0) const
Definition at line 389 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
bool QDlnaClient::remove (int instance = 0) const
Definition at line 375 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::~MusicSongDlnaTransferWidget().
QString QDlnaClient::server () const
Definition at line 158 of file qdlnaclient.cpp.
References TTK_D.
Referenced by QDlnaFinder::handleReadyRead(), and MusicSongDlnaTransferWidget::playSongAction().
QString QDlnaClient::serverName () const
Definition at line 164 of file qdlnaclient.cpp.
References TTK_D.
Referenced by QDlnaFinder::clientNames().
bool QDlnaClient::setPlayMode (const QString & mode, int instance) const
Definition at line 417 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
bool QDlnaClient::stop (int instance = 0) const
Definition at line 361 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::~MusicSongDlnaTransferWidget().
bool QDlnaClient::transportInfo (QDlna::TransportInfo & info, int instance = 0) const
Definition at line 274 of file qdlnaclient.cpp.
References AVTSCHEMA, QDlnaXml::fromString(), QDlna::isValid(), QDlna::makeRequest(), QDlna::makeSocketGetReply(), QDlnaXml::readTagNameValue(), QDlna::removeHttpHeader(), QDlna::TransportInfo::speed, QDlna::TransportInfo::state, QDlna::TransportInfo::status, TTK_D, XML_FOOT, and XML_HEAD.
Referenced by MusicSongDlnaTransferWidget::timeout().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/qdlnaclient.h
TTKThirdParty/TTKExtras/qdlna/qdlnaclient.cpp