TTKMusicplayer: MusicArtistMvsFoundWidget Class Reference
MusicArtistMvsFoundWidget Class Reference
The class of the artist mvs found widget.
#include <musicartistfoundwidget.h>
Public Slots
void createArtistMvsItem (const MusicResultsItem &item)
void currentItemClicked (const QString &id)
void buttonClicked (int index)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistMvsFoundWidget (QWidget *parent=nullptr)
virtual ~MusicArtistMvsFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=nullptr)
~MusicFoundAbstractWidget ()
void initWidget ()
Protected Attributes
QGridLayout * m_gridLayout
bool m_firstInit
MusicPagingWidgetObject * m_pagingWidgetObject
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the artist mvs found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 72 of file musicartistfoundwidget.h.
Constructor & Destructor Documentation
MusicArtistMvsFoundWidget::MusicArtistMvsFoundWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 93 of file musicartistfoundwidget.cpp.
References MusicSongSharingWidget::Artist, createArtistMvsItem(), MusicFoundAbstractWidget::m_container, M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, m_pagingWidgetObject, MusicFoundAbstractWidget::m_shareType, and MusicFoundAbstractWidget::m_statusLabel.
MusicArtistMvsFoundWidget::~MusicArtistMvsFoundWidget () virtual
Definition at line 112 of file musicartistfoundwidget.cpp.
References m_gridLayout.
Member Function Documentation
void MusicArtistMvsFoundWidget::buttonClicked (int index) slot
Paging widget button has changed.
Definition at line 172 of file musicartistfoundwidget.cpp.
References MusicPagingWidgetObject::currentIndex(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicPagingWidgetObject::paging(), and MusicDownLoadPagingThread::startToPage().
Referenced by createArtistMvsItem().
void MusicArtistMvsFoundWidget::createArtistMvsItem (const MusicResultsItem & item) slot
Create the current albums item.
Definition at line 146 of file musicartistfoundwidget.cpp.
References buttonClicked(), MusicPagingWidgetObject::createPagingWidget(), currentItemClicked(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), LINE_SPACING_SIZE, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, and MusicArtistAlbumsItemWidget::setMusicResultsItem().
Referenced by MusicArtistMvsFoundWidget().
void MusicArtistMvsFoundWidget::currentItemClicked (const QString & id) slot
Current item clicked.
Definition at line 167 of file musicartistfoundwidget.cpp.
References MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicMovieSearch().
Referenced by createArtistMvsItem().
void MusicArtistMvsFoundWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicFoundAbstractWidget.
Definition at line 129 of file musicartistfoundwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and MusicFoundAbstractWidget::m_resizeWidgets.
Referenced by MusicArtistFoundWidget::resizeWindow().
void MusicArtistMvsFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 117 of file musicartistfoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::setSongName(), MusicDownLoadQueryMovieThread::startToSearch(), and TTKStatic_cast.
Referenced by MusicArtistFoundWidget::initFourthWidget(), and setSongNameById().
void MusicArtistMvsFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 124 of file musicartistfoundwidget.cpp.
References setSongName().
Member Data Documentation
bool MusicArtistMvsFoundWidget::m_firstInit protected
Definition at line 113 of file musicartistfoundwidget.h.
Referenced by createArtistMvsItem(), and MusicArtistMvsFoundWidget().
QGridLayout* MusicArtistMvsFoundWidget::m_gridLayout protected
Definition at line 112 of file musicartistfoundwidget.h.
Referenced by buttonClicked(), createArtistMvsItem(), MusicArtistMvsFoundWidget(), resizeWindow(), and ~MusicArtistMvsFoundWidget().
MusicPagingWidgetObject* MusicArtistMvsFoundWidget::m_pagingWidgetObject protected
Definition at line 114 of file musicartistfoundwidget.h.
Referenced by buttonClicked(), createArtistMvsItem(), and MusicArtistMvsFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.cpp