TTKMusicplayer: MusicDataDownloadThread Class Reference
MusicDataDownloadThread Class Reference
The class of downloading the type of data.
#include <musicdatadownloadthread.h>
Public Slots
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal) override
virtual void updateDownloadSpeed () override
void downLoadReadyRead ()
Public Slots inherited from MusicDownLoadThreadAbstract
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void downloadUrlChanged (const QString &url)
void downloadSpeedLabelChanged (const QString &speed, qint64 timeLeft)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDataDownloadThread (const QString &url, const QString &save, Download_Type type, QObject *parent=0)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownLoadThreadAbstract
MusicDownLoadThreadAbstract (const QString &url, const QString &save, Download_Type type, QObject *parent=0)
virtual ~MusicDownLoadThreadAbstract ()
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Member Functions
void startRequest (const QUrl &url)
Protected Member Functions inherited from MusicDownLoadThreadAbstract
QString transferData () const
Protected Attributes
qint64 m_createItemTime
bool m_redirection
bool m_needUpdate
Protected Attributes inherited from MusicDownLoadThreadAbstract
QFile * m_file
QString m_url
QString m_savePathName
Download_Type m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_timer
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicDownLoadThreadAbstract
enum Download_Type {
Download_Music, Download_Lrc, Download_SmlBG, Download_BigBG,
Download_Video, Download_Other
}
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Detailed Description
The class of downloading the type of data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdatadownloadthread.h.
Constructor & Destructor Documentation
MusicDataDownloadThread::MusicDataDownloadThread (const QString & url, const QString & save, Download_Type type, QObject * parent = 0)
Object contsructor provide download URL\ save local path and download type.
Definition at line 6 of file musicdatadownloadthread.cpp.
References m_createItemTime, m_needUpdate, and m_redirection.
Member Function Documentation
void MusicDataDownloadThread::createDownloadItem (const QString & name, qint64 time) signal
Create download item from download name and total time.
Referenced by startRequest().
void MusicDataDownloadThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 72 of file musicdatadownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_INFO, m_needUpdate, m_redirection, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_timer, startRequest(), and MusicDownLoadThreadAbstract::transferData().
Referenced by MusicDataTagDownloadThread::downLoadFinished(), and startRequest().
void MusicDataDownloadThread::downloadProgress (qint64 bytesReceived, qint64 bytesTotal) override virtual slot
Get download received and total data.
only download music data or oather type can that show progress
Definition at line 116 of file musicdatadownloadthread.cpp.
References MusicDownLoadThreadAbstract::Download_Music, MusicDownLoadThreadAbstract::Download_Other, MusicDownLoadThreadAbstract::downloadProgress(), downloadProgressChanged(), m_createItemTime, MusicDownLoadThreadAbstract::m_downloadType, and MusicUtils::Number::size2Label().
Referenced by startRequest().
void MusicDataDownloadThread::downloadProgressChanged (float percent, const QString & total, qint64 time) signal
Update download percent\ total time and current time progress.
Referenced by downloadProgress().
void MusicDataDownloadThread::downLoadReadyRead () slot
Download received data ready.
Definition at line 108 of file musicdatadownloadthread.cpp.
References MusicDownLoadThreadAbstract::m_file, and MusicNetworkAbstract::m_reply.
Referenced by startRequest().
void MusicDataDownloadThread::downloadSpeedLabelChanged (const QString & speed, qint64 timeLeft) signal
Update download speed label.
Referenced by updateDownloadSpeed().
void MusicDataDownloadThread::downloadUrlChanged (const QString & url) signal
Update download url finished.
QString MusicDataDownloadThread::getClassName () static
Get class object name.
Definition at line 15 of file musicdatadownloadthread.cpp.
Referenced by startToDownload().
void MusicDataDownloadThread::startRequest (const QUrl & url) protected
Start to download data from url.
only download music data can that show progress
Definition at line 43 of file musicdatadownloadthread.cpp.
References createDownloadItem(), MusicDownLoadThreadAbstract::Download_Music, downLoadFinished(), downloadProgress(), downLoadReadyRead(), M_CONNECTION_PTR, m_createItemTime, MusicDownLoadThreadAbstract::m_downloadType, MusicNetworkAbstract::m_manager, m_redirection, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_savePathName, MusicDownLoadThreadAbstract::m_timer, MT_S2MS, MusicDownLoadThreadAbstract::replyError(), and MusicTime::timeStamp().
Referenced by downLoadFinished(), startToDownload(), and MusicDataTagDownloadThread::startToDownload().
void MusicDataDownloadThread::startToDownload () override virtual
Start to download data.
Implements MusicDownLoadThreadAbstract.
Reimplemented in MusicDataTagDownloadThread.
Definition at line 20 of file musicdatadownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_ERROR, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadThreadAbstract::m_url, MusicDownLoadThreadAbstract::sslErrors(), and startRequest().
Referenced by MusicSongSearchOnlineTableWidget::addSearchMusicToPlayList(), MusicDesktopWallpaperWidget::confirmButtonPressed(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicKWBackgroundThread::downLoadDataFinished(), MusicQueryFoundTableWidget::downloadDataFrom(), MusicQQBackgroundThread::downLoadUrlFinished(), MusicNetworkSpeedTestWidget::networkTestStart(), MusicDownloadWidget::startToDownloadMovie(), MusicWebMusicRadioWidget::startToPlay(), and MusicSourceUpdateWidget::upgradeButtonClicked().
void MusicDataDownloadThread::updateDownloadSpeed () override virtual slot
Updata download speed due the user mod the net speed limited.
Definition at line 127 of file musicdatadownloadthread.cpp.
References downloadSpeedLabelChanged(), MusicDownLoadThreadAbstract::m_currentReceived, MusicDownLoadThreadAbstract::m_hasReceived, MusicDownLoadThreadAbstract::m_totalSize, MusicUtils::Number::speed2Label(), and MusicDownLoadThreadAbstract::updateDownloadSpeed().
Member Data Documentation
qint64 MusicDataDownloadThread::m_createItemTime protected
Definition at line 88 of file musicdatadownloadthread.h.
Referenced by downloadProgress(), MusicDataDownloadThread(), and startRequest().
bool MusicDataDownloadThread::m_needUpdate protected
Definition at line 89 of file musicdatadownloadthread.h.
Referenced by downLoadFinished(), MusicDataDownloadThread(), and MusicDataTagDownloadThread::MusicDataTagDownloadThread().
bool MusicDataDownloadThread::m_redirection protected
Definition at line 89 of file musicdatadownloadthread.h.
Referenced by MusicDataTagDownloadThread::downLoadFinished(), downLoadFinished(), MusicDataDownloadThread(), and startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/nr/musicdatadownloadthread.h
TTKModule/TTKCore/musicNetworkKits/nr/musicdatadownloadthread.cpp