TTKMusicplayer: MusicDownLoadPagingThread Class Reference
MusicDownLoadPagingThread Class Reference
The class to abstract download paing thread.
#include <musicdownloadpagingthread.h>
Public Member Functions
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Attributes
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Detailed Description
The class to abstract download paing thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadpagingthread.h.
Constructor & Destructor Documentation
MusicDownLoadPagingThread::MusicDownLoadPagingThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 3 of file musicdownloadpagingthread.cpp.
References getClassName(), M_LOGGER_INFO, MusicNetworkAbstract::m_manager, m_pageSize, m_pageTotal, and MusicNetworkAbstract::sslErrors().
MusicDownLoadPagingThread::~MusicDownLoadPagingThread () virtual
Definition at line 17 of file musicdownloadpagingthread.cpp.
References deleteAll().
Member Function Documentation
void MusicDownLoadPagingThread::deleteAll () override virtual
Release the network object.
Reimplemented from MusicNetworkAbstract.
Definition at line 27 of file musicdownloadpagingthread.cpp.
References MusicNetworkAbstract::m_reply.
Referenced by MusicBDDiscoverListThread::downLoadFinished(), MusicKWDiscoverListThread::downLoadFinished(), MusicQQDiscoverListThread::downLoadFinished(), MusicWSDiscoverListThread::downLoadFinished(), MusicKGDiscoverListThread::downLoadFinished(), MusicMGDiscoverListThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicKGSongSuggestThread::downLoadFinished(), MusicMGSongSuggestThread::downLoadFinished(), MusicQQArtistSimilarThread::downLoadFinished(), MusicBDArtistSimilarThread::downLoadFinished(), MusicQQSongSuggestThread::downLoadFinished(), MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicWSArtistSimilarThread::downLoadFinished(), MusicBDSongSuggestThread::downLoadFinished(), MusicWSSongSuggestThread::downLoadFinished(), MusicKWArtistSimilarThread::downLoadFinished(), MusicKWSongSuggestThread::downLoadFinished(), MusicXMArtistSimilarThread::downLoadFinished(), MusicKGArtistSimilarThread::downLoadFinished(), MusicXMSongSuggestThread::downLoadFinished(), MusicMGArtistSimilarThread::downLoadFinished(), MusicDownLoadQueryWSThread::downLoadFinished(), MusicWYDiscoverListThread::downLoadFinished(), MusicXMDiscoverListThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWSAlbumThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicWYArtistSimilarThread::downLoadFinished(), MusicWYSongSuggestThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicBDSongCommentsThread::downLoadFinished(), MusicQQSongCommentsThread::downLoadFinished(), MusicKWSongCommentsThread::downLoadFinished(), MusicWSSongCommentsThread::downLoadFinished(), MusicKGSongCommentsThread::downLoadFinished(), MusicMGSongCommentsThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicWYSongCommentsThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicXMSongCommentsThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryWSPlaylistThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicQQPlaylistCommentsThread::downLoadFinished(), MusicKWPlaylistCommentsThread::downLoadFinished(), MusicBDPlaylistCommentsThread::downLoadFinished(), MusicKGPlaylistCommentsThread::downLoadFinished(), MusicMGPlaylistCommentsThread::downLoadFinished(), MusicWSPlaylistCommentsThread::downLoadFinished(), MusicWYPlaylistCommentsThread::downLoadFinished(), MusicXMPlaylistCommentsThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryMGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::pageDownLoadFinished(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryXMMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryKGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryQQAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKWAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryWYAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryXMAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryMGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryBDAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryMGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), MusicMGSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicWSSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryMGMovieThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryWSPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryMGPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicMGPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicWSPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicBDDiscoverListThread::startToSearch(), MusicDownLoadQueryYYTThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicMGDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicMGArtistSimilarThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicMGSongSuggestThread::startToSearch(), MusicDownLoadQueryWSMovieThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicWSSongSuggestThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryWSThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryQQThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryMGThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryMGMovieThread::startToSearch(), MusicDownLoadQueryWYThread::startToSearch(), MusicDownLoadQueryBDThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryKGThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryXMThread::startToSearch(), MusicDownLoadQueryWSArtistThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryMGAlbumThread::startToSearch(), MusicDownLoadQueryMGRecommendThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryMGArtistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryMGToplistThread::startToSearch(), MusicDownLoadQueryKWThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryBDThread::startToSingleSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryMGThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryMGAlbumThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryKWMovieThread::startToSingleSearch(), MusicDownLoadQueryQQMovieThread::startToSingleSearch(), MusicDownLoadQueryKGMovieThread::startToSingleSearch(), MusicDownLoadQueryWYMovieThread::startToSingleSearch(), MusicDownLoadQueryBDMovieThread::startToSingleSearch(), MusicDownLoadQueryMGMovieThread::startToSingleSearch(), MusicDownLoadQueryKWThread::startToSingleSearch(), MusicDownLoadQueryXMMovieThread::startToSingleSearch(), ~MusicDownLoadPagingThread(), and MusicDownLoadQueryThreadAbstract::~MusicDownLoadQueryThreadAbstract().
QString MusicDownLoadPagingThread::getClassName () static
Get class object name.
Definition at line 22 of file musicdownloadpagingthread.cpp.
Referenced by MusicDownLoadPagingThread().
int MusicDownLoadPagingThread::getPageSize () const inline
Return the each page max size.
Definition at line 58 of file musicdownloadpagingthread.h.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsFoundWidget::buttonClicked(), MusicPlaylistFoundWidget::buttonClicked(), MusicArtistMvsFoundWidget::createArtistMvsItem(), MusicCommentsWidget::createPagingWidget(), and MusicPlaylistFoundWidget::createPlaylistItems().
int MusicDownLoadPagingThread::getPageTotal () const inline
Return the page total number.
Definition at line 62 of file musicdownloadpagingthread.h.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsFoundWidget::buttonClicked(), MusicPlaylistFoundWidget::buttonClicked(), MusicArtistMvsFoundWidget::createArtistMvsItem(), MusicCommentsWidget::createPagingWidget(), MusicPlaylistFoundWidget::createPlaylistItems(), and MusicCommentsWidget::setCurrentSongName().
QVariantMap MusicDownLoadPagingThread::getRawData () const inline
Return the current raw data.
Definition at line 54 of file musicdownloadpagingthread.h.
Referenced by MusicQQSongCommentsThread::startToSearch().
void MusicDownLoadPagingThread::startToPage (int offset) virtual
Start to search data from name and type bt paging.
Reimplemented in MusicWSPlaylistCommentsThread, MusicWYPlaylistCommentsThread, MusicXMPlaylistCommentsThread, MusicBDPlaylistCommentsThread, MusicKGPlaylistCommentsThread, MusicKWPlaylistCommentsThread, MusicMGPlaylistCommentsThread, MusicQQPlaylistCommentsThread, MusicDownLoadQueryXMMovieThread, MusicDownLoadQueryBDPlaylistThread, MusicDownLoadQueryKGPlaylistThread, MusicDownLoadQueryKWPlaylistThread, MusicDownLoadQueryMGPlaylistThread, MusicDownLoadQueryQQPlaylistThread, MusicDownLoadQueryWSPlaylistThread, MusicDownLoadQueryWYPlaylistThread, MusicWYSongCommentsThread, MusicDownLoadQueryXMPlaylistThread, MusicXMSongCommentsThread, MusicDownLoadQueryBDMovieThread, MusicDownLoadQueryKGMovieThread, MusicDownLoadQueryMGMovieThread, MusicDownLoadQueryWYMovieThread, MusicBDSongCommentsThread, MusicKGSongCommentsThread, MusicDownLoadQueryKWMovieThread, MusicKWSongCommentsThread, MusicMGSongCommentsThread, MusicDownLoadQueryQQMovieThread, MusicQQSongCommentsThread, and MusicWSSongCommentsThread.
Definition at line 36 of file musicdownloadpagingthread.cpp.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsFoundWidget::buttonClicked(), MusicPlaylistFoundWidget::buttonClicked(), and MusicDownLoadQueryMovieThread::startToSearch().
Member Data Documentation
int MusicDownLoadPagingThread::m_pageSize protected
Definition at line 66 of file musicdownloadpagingthread.h.
Referenced by MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicBDDiscoverListThread::MusicBDDiscoverListThread(), MusicBDPlaylistCommentsThread::MusicBDPlaylistCommentsThread(), MusicBDSongCommentsThread::MusicBDSongCommentsThread(), MusicDownLoadPagingThread(), MusicDownLoadQueryBDPlaylistThread::MusicDownLoadQueryBDPlaylistThread(), MusicDownLoadQueryBDToplistThread::MusicDownLoadQueryBDToplistThread(), MusicDownLoadQueryKGPlaylistThread::MusicDownLoadQueryKGPlaylistThread(), MusicDownLoadQueryKWPlaylistThread::MusicDownLoadQueryKWPlaylistThread(), MusicDownLoadQueryMGPlaylistThread::MusicDownLoadQueryMGPlaylistThread(), MusicDownLoadQueryMGToplistThread::MusicDownLoadQueryMGToplistThread(), MusicDownLoadQueryQQPlaylistThread::MusicDownLoadQueryQQPlaylistThread(), MusicDownLoadQueryWSPlaylistThread::MusicDownLoadQueryWSPlaylistThread(), MusicDownLoadQueryWYPlaylistThread::MusicDownLoadQueryWYPlaylistThread(), MusicDownLoadQueryXMPlaylistThread::MusicDownLoadQueryXMPlaylistThread(), MusicKGPlaylistCommentsThread::MusicKGPlaylistCommentsThread(), MusicKGSongCommentsThread::MusicKGSongCommentsThread(), MusicKWPlaylistCommentsThread::MusicKWPlaylistCommentsThread(), MusicKWSongCommentsThread::MusicKWSongCommentsThread(), MusicMGDiscoverListThread::MusicMGDiscoverListThread(), MusicMGPlaylistCommentsThread::MusicMGPlaylistCommentsThread(), MusicMGSongCommentsThread::MusicMGSongCommentsThread(), MusicQQPlaylistCommentsThread::MusicQQPlaylistCommentsThread(), MusicQQSongCommentsThread::MusicQQSongCommentsThread(), MusicWSPlaylistCommentsThread::MusicWSPlaylistCommentsThread(), MusicWSSongCommentsThread::MusicWSSongCommentsThread(), MusicWYPlaylistCommentsThread::MusicWYPlaylistCommentsThread(), MusicWYSongCommentsThread::MusicWYSongCommentsThread(), MusicXMPlaylistCommentsThread::MusicXMPlaylistCommentsThread(), MusicXMSongCommentsThread::MusicXMSongCommentsThread(), MusicMGSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicWSSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryMGMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryWSPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicMGPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicWSPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicBDDiscoverListThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), and MusicDownLoadQueryXMPlaylistThread::startToSearch().
int MusicDownLoadPagingThread::m_pageTotal protected
Definition at line 66 of file musicdownloadpagingthread.h.
Referenced by MusicBDSongCommentsThread::downLoadFinished(), MusicKWSongCommentsThread::downLoadFinished(), MusicQQSongCommentsThread::downLoadFinished(), MusicWSSongCommentsThread::downLoadFinished(), MusicKGSongCommentsThread::downLoadFinished(), MusicMGSongCommentsThread::downLoadFinished(), MusicWYSongCommentsThread::downLoadFinished(), MusicXMSongCommentsThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDownLoadQueryWSPlaylistThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicKGPlaylistCommentsThread::downLoadFinished(), MusicMGPlaylistCommentsThread::downLoadFinished(), MusicBDPlaylistCommentsThread::downLoadFinished(), MusicQQPlaylistCommentsThread::downLoadFinished(), MusicKWPlaylistCommentsThread::downLoadFinished(), MusicWSPlaylistCommentsThread::downLoadFinished(), MusicWYPlaylistCommentsThread::downLoadFinished(), MusicXMPlaylistCommentsThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicDownLoadPagingThread(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryMGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryXMMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicKGSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicWSSongCommentsThread::startToPage(), MusicMGSongCommentsThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryMGMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryMGPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryWSPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicMGPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), and MusicWSPlaylistCommentsThread::startToPage().
QVariantMap MusicDownLoadPagingThread::m_rawData protected
Definition at line 65 of file musicdownloadpagingthread.h.
Referenced by MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGAlbumThread::MusicDownLoadQueryMGAlbumThread(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryMGAlbumThread::singleDownLoadFinished(), MusicMGSongCommentsThread::startToPage(), MusicWSSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicMGPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicWSPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicMGSongCommentsThread::startToSearch(), MusicBDSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicQQSongCommentsThread::startToSearch(), MusicWSSongCommentsThread::startToSearch(), MusicWYSongCommentsThread::startToSearch(), MusicXMSongCommentsThread::startToSearch(), MusicMGPlaylistCommentsThread::startToSearch(), MusicBDPlaylistCommentsThread::startToSearch(), MusicKWPlaylistCommentsThread::startToSearch(), MusicQQPlaylistCommentsThread::startToSearch(), MusicKGPlaylistCommentsThread::startToSearch(), MusicWSPlaylistCommentsThread::startToSearch(), MusicWYPlaylistCommentsThread::startToSearch(), MusicXMPlaylistCommentsThread::startToSearch(), and MusicDownLoadQueryMGAlbumThread::startToSingleSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadpagingthread.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadpagingthread.cpp