TTKMusicPlayer: MusicSongsSummariziedWidget Class Reference
MusicSongsSummariziedWidget Class Reference
The class of the songs summarizied widget.
#include <musicsongssummariziedwidget.h>
Public Slots
void addNewRowItem ()
void deleteRowItem (int index)
void deleteRowItems ()
void deleteRowItemAll (int index)
void changRowItemName (int index, const QString &name)
void swapDragItemIndex (int start, int end)
void addToPlayLater (int index)
void addToPlayedList (int index)
void importSongsByFiles (int index=TTK_LOW_LEVEL)
void importSongsByDir (int index=TTK_LOW_LEVEL)
void showSongCheckToolsWidget ()
void showLrcDownloadBatchWidget ()
void searchResultChanged (int row, int column)
void updateCurrentIndex ()
void songToLovestListAt (bool state, int row)
void addSongToLovestList (bool state, int row)
void addSongBufferToPlaylist (const MusicResultDataItem &songItem)
void addSongToPlaylist (const QStringList &items)
void removeItemAt (const TTKIntList &del, bool fileRemove)
void itemIndexSwaped (int start, int end, int play, MusicSongList &songs)
void isCurrentPlaylistRow (bool &state)
void isSearchedResultEmpty (bool &empty)
void setMusicPlayCount (int index)
void setRecentMusicSongs (int index)
void queryMusicItemList (MusicSongItemList &songs)
void updateCurrentArtist ()
void showFloatWidget ()
void songListSortBy (int index)
Public Slots inherited from MusicFunctionToolBoxWidget
void setCurrentIndex (int index)
void itemIndexChanged (int index)
void setTransparent (int alpha)
Public Member Functions
MusicSongsSummariziedWidget (QWidget *parent=nullptr)
~MusicSongsSummariziedWidget ()
bool addMusicItemList (const MusicSongItemList &items)
void appendMusicItemList (const MusicSongItemList &items)
const MusicSongItemList & musicItemList () const
void importMusicSongsByUrl (const QString &path, int playlistRow)
void importMusicSongsByPath (const QStringList &files, int playlistRow)
QStringList musicSongsFileName (int index) const
QStringList musicSongsFilePath (int index) const
int mapSongIndexByFilePath (int playlistRow, const QString &path) const
QString mapFilePathBySongIndex (int playlistRow, int index) const
void removeSearchResult (int &row)
int playRowIndex () const
void setCurrentSongTreeIndex (int index)
void playLocation (int index)
void selectRow (int index)
void updateTimeLabel (const QString &current, const QString &total) const
Public Member Functions inherited from MusicSongsToolBoxWidget
MusicSongsToolBoxWidget (QWidget *parent=nullptr)
void setSongSort (QWidget *item, MusicSongSort *sort)
int makeValidIndex () const
Public Member Functions inherited from MusicFunctionToolBoxWidget
MusicFunctionToolBoxWidget (QWidget *parent=nullptr)
~MusicFunctionToolBoxWidget ()
void addCellItem (QWidget *item, const QString &text)
void removeItem (QWidget *item)
void swapItem (int start, int end)
void setTitle (QWidget *item, const QString &text)
void resizeScrollIndex (int index) const
int currentIndex () const
int count () const
Private Slots
void showSearchWidget ()
void sliderValueChanaged (int value)
void deleteFloatWidget ()
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
virtual void dragEnterEvent (QDragEnterEvent *event) overridefinal
virtual void dragMoveEvent (QDragMoveEvent *event) overridefinal
virtual void dropEvent (QDropEvent *event) overridefinal
bool isSearchPlayIndex () const
void closeSearchWidget ()
void closeSearchWidgetInNeed ()
void checkCurrentNameExist (QString &name)
void addNewRowItem (const QString &name)
void createWidgetItem (MusicSongItem *item)
void setItemTitle (MusicSongItem *item)
void setInputModule (QObject *object) const
void resizeWindow ()
void updatePlayedList (int start, int end)
Private Member Functions inherited from MusicItemSearchInterface< MusicSongItemList >
MusicItemSearchInterface ()
bool hasSearchResult () const
void clearSearchResult ()
void mappedSearchRow (int pos, int &row) const
Private Attributes
int m_playRowIndex
int m_lastSearchIndex
int m_selectDeleteIndex
MusicSongsToolBoxMaskWidget * m_listMaskWidget
MusicSongsListFunctionWidget * m_listFunctionWidget
MusicSongSearchDialog * m_songSearchWidget
Private Attributes inherited from MusicItemSearchInterface< MusicSongItemList >
MusicSongItemList m_containerItems
int m_searchResultLevel
TTKIntListMap m_searchResultCache
Additional Inherited Members
Protected Member Functions inherited from MusicFunctionToolBoxWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
int foundMappedIndex (int index)
Protected Attributes inherited from MusicFunctionToolBoxWidget
int m_currentIndex
int m_itemIndexRaise
QVBoxLayout * m_layout
QScrollArea * m_scrollArea
QWidget * m_contentsWidget
MusicToolBoxWidgetItemList m_itemList
Private Types inherited from MusicItemSearchInterface< MusicSongItemList >
using TTKIntListMap = QMap< int, TTKIntList >
using MusicItemSearchInterfaceClass = MusicItemSearchInterface< MusicSongItemList >
Detailed Description
The class of the songs summarizied widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicsongssummariziedwidget.h.
Constructor & Destructor Documentation
MusicSongsSummariziedWidget::MusicSongsSummariziedWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 22 of file musicsongssummariziedwidget.cpp.
References G_CONNECTION_PTR, MusicFunctionToolBoxWidget::itemIndexChanged(), m_listMaskWidget, MusicFunctionToolBoxWidget::m_scrollArea, setInputModule(), and sliderValueChanaged().
MusicSongsSummariziedWidget::~MusicSongsSummariziedWidget ()
Object destructor.
Definition at line 43 of file musicsongssummariziedwidget.cpp.
References G_CONNECTION_PTR, MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_listFunctionWidget, m_listMaskWidget, and m_songSearchWidget.
Member Function Documentation
bool MusicSongsSummariziedWidget::addMusicItemList (const MusicSongItemList & items)
Add music datas into container.
Definition at line 56 of file musicsongssummariziedwidget.cpp.
References createWidgetItem(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, MUSIC_NORMAL_LIST, MUSIC_RECENT_LIST, and qAsConst.
Referenced by MusicApplication::readSystemConfigFromFile().
void MusicSongsSummariziedWidget::addNewRowItem () slot
Add new play list item.
Definition at line 355 of file musicsongssummariziedwidget.cpp.
References checkCurrentNameExist(), ITEM_MAX_COUNT, MusicItemSearchInterface< MusicSongItemList >::m_containerItems, and name.
Referenced by contextMenuEvent(), and setInputModule().
void MusicSongsSummariziedWidget::addNewRowItem (const QString & name) private
Add new play list item by name.
Definition at line 1144 of file musicsongssummariziedwidget.cpp.
References createWidgetItem(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemName, and name.
void MusicSongsSummariziedWidget::addSongBufferToPlaylist (const MusicResultDataItem & songItem) slot
Add current network music buffer to playlist.
when download finished just play it at once
Definition at line 726 of file musicsongssummariziedwidget.cpp.
References MusicApplication::instance(), MusicResultDataItem::m_category, MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicResultDataItem::m_count, MusicResultDataItem::m_description, MusicResultDataItem::m_id, MusicSongItem::m_itemObject, MusicResultDataItem::m_name, MusicResultDataItem::m_nickName, MusicSongItem::m_songs, MusicResultDataItem::m_updateTime, TTK::Algorithm::md5(), MUSIC_NETWORK_LIST, MUSIC_PLAY_NOW, MusicApplication::playIndexClicked(), MusicFunctionToolBoxWidget::setCurrentIndex(), setItemTitle(), and MusicAbstractSongsListTableWidget::updateSongsList().
void MusicSongsSummariziedWidget::addSongToLovestList (bool state, int row) slot
Add or remove music list song to lovest list by row.
if current play list contains, call main add and remove function
Add to lovest list
Remove to lovest list
Definition at line 690 of file musicsongssummariziedwidget.cpp.
References MusicApplication::addSongToLovestList(), MusicItemSearchInterface< MusicSongItemList >::hasSearchResult(), MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, MusicSongItem::m_itemObject, m_playRowIndex, MusicSongItem::m_songs, MUSIC_LOVEST_LIST, MusicSong::path(), MusicSongsListPlayTableWidget::removeItems(), MusicApplication::removeLoveItemAt(), setItemTitle(), TTKObjectCast, and MusicSongsListPlayTableWidget::updateSongsList().
Referenced by createWidgetItem().
void MusicSongsSummariziedWidget::addSongToPlaylist (const QStringList & items) slot
Add current selected song to play list.
just play it at once
Definition at line 751 of file musicsongssummariziedwidget.cpp.
References importMusicSongsByPath(), MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_songs, MusicSongsToolBoxWidget::makeValidIndex(), MusicApplication::playIndexClicked(), and MusicFunctionToolBoxWidget::setCurrentIndex().
void MusicSongsSummariziedWidget::addToPlayedList (int index) slot
Add music to played list.
Definition at line 524 of file musicsongssummariziedwidget.cpp.
References MusicPlayedListPopWidget::append(), MusicFunctionToolBoxWidget::foundMappedIndex(), MusicPlayedListPopWidget::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemIndex, MusicSongItem::m_songs, and qAsConst.
Referenced by setInputModule().
void MusicSongsSummariziedWidget::addToPlayLater (int index) slot
Add music to played list and play later.
Definition at line 508 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), MusicPlayedListPopWidget::insert(), MusicPlayedListPopWidget::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemIndex, and MusicSongItem::m_songs.
Referenced by setInputModule().
void MusicSongsSummariziedWidget::appendMusicItemList (const MusicSongItemList & items)
Append music datas into container.
Definition at line 117 of file musicsongssummariziedwidget.cpp.
References checkCurrentNameExist(), createWidgetItem(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemIndex, MusicFunctionToolBoxWidget::m_itemIndexRaise, and MusicSongItem::m_itemName.
Referenced by MusicApplication::importSongsItemList().
void MusicSongsSummariziedWidget::changRowItemName (int index, const QString & name) slot
Open rename selected play list item widget.
Definition at line 455 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemName, name, and setItemTitle().
Referenced by setInputModule().
void MusicSongsSummariziedWidget::checkCurrentNameExist (QString & name) private
Check current name exist.
Definition at line 1120 of file musicsongssummariziedwidget.cpp.
References ITEM_MAX_COUNT, MusicItemSearchInterface< MusicSongItemList >::m_containerItems, name, and qAsConst.
Referenced by addNewRowItem(), and appendMusicItemList().
void MusicSongsSummariziedWidget::closeSearchWidget () private
Close searched text widget.
Definition at line 1104 of file musicsongssummariziedwidget.cpp.
References MusicSongSearchDialog::close(), and m_songSearchWidget.
Referenced by closeSearchWidgetInNeed(), and removeSearchResult().
void MusicSongsSummariziedWidget::closeSearchWidgetInNeed () private
Close searched text widget in need.
Definition at line 1112 of file musicsongssummariziedwidget.cpp.
References closeSearchWidget(), and MusicItemSearchInterface< MusicSongItemList >::hasSearchResult().
Referenced by deleteRowItemAll(), importMusicSongsByPath(), importMusicSongsByUrl(), selectRow(), and songListSortBy().
void MusicSongsSummariziedWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Definition at line 1088 of file musicsongssummariziedwidget.cpp.
References addNewRowItem(), TTK::Widget::adjustMenuPosition(), deleteRowItems(), MusicApplication::instance(), ITEM_MIN_COUNT, MusicItemSearchInterface< MusicSongItemList >::m_containerItems, TTK::UI::MenuStyle02, showLrcDownloadBatchWidget(), and showSongCheckToolsWidget().
void MusicSongsSummariziedWidget::createWidgetItem (MusicSongItem * item) private
Create widget item.
connect to items
Definition at line 1152 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::addCellItem(), addSongToLovestList(), MusicFunctionToolBoxWidget::foundMappedIndex(), isCurrentPlaylistRow(), isSearchedResultEmpty(), itemIndexSwaped(), MusicSongItem::m_itemIndex, MusicFunctionToolBoxWidget::m_itemIndexRaise, MusicFunctionToolBoxWidget::m_itemList, MusicSongItem::m_itemName, MusicSongItem::m_itemObject, MusicFunctionToolBoxWidget::m_scrollArea, MusicSongItem::m_songs, MusicSongItem::m_sort, removeItemAt(), setInputModule(), MusicSmoothMovingTableWidget::setMovedScrollBar(), MusicAbstractSongsListTableWidget::setPlaylistRow(), MusicAbstractSongsListTableWidget::setSongsList(), MusicSongsListPlayTableWidget::setSongSort(), MusicSongsToolBoxWidget::setSongSort(), MusicFunctionToolBoxWidget::setTitle(), showFloatWidget(), songListSortBy(), and TTK_NORMAL_LEVEL.
Referenced by addMusicItemList(), addNewRowItem(), and appendMusicItemList().
void MusicSongsSummariziedWidget::deleteFloatWidget () private slot
Delete the float function widget.
Definition at line 1018 of file musicsongssummariziedwidget.cpp.
References m_listFunctionWidget.
Referenced by showFloatWidget().
void MusicSongsSummariziedWidget::deleteRowItem (int index) slot
Delete selected play list item.
Definition at line 365 of file musicsongssummariziedwidget.cpp.
References MusicAbstractMoveDialog::exec(), MusicFunctionToolBoxWidget::foundMappedIndex(), MusicApplication::instance(), MusicPlayedListPopWidget::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemIndex, MusicFunctionToolBoxWidget::m_itemList, MusicSongItem::m_itemObject, m_playRowIndex, MusicSongItem::m_songs, MUSIC_NORMAL_LIST, MusicApplication::playIndexBy(), qAsConst, MusicPlayedListPopWidget::remove(), MusicFunctionToolBoxWidget::removeItem(), MusicFunctionToolBoxWidget::setCurrentIndex(), MusicMessageBox::setText(), TTK_NORMAL_LEVEL, and updatePlayedList().
Referenced by setInputModule().
void MusicSongsSummariziedWidget::deleteRowItemAll (int index) slot
Delete all items in play list item.
Definition at line 428 of file musicsongssummariziedwidget.cpp.
References MusicAbstractSongsListTableWidget::clearItems(), closeSearchWidgetInNeed(), MusicFunctionToolBoxWidget::foundMappedIndex(), MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_playRowIndex, m_selectDeleteIndex, MUSIC_NONE_LIST, MusicApplication::playIndexBy(), TTK_NORMAL_LEVEL, and TTKObjectCast.
Referenced by setInputModule().
void MusicSongsSummariziedWidget::deleteRowItems () slot
Delete all other item, left than three item.
Definition at line 404 of file musicsongssummariziedwidget.cpp.
References MusicAbstractMoveDialog::exec(), MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_itemList, MusicSongItem::m_itemObject, m_playRowIndex, MUSIC_NORMAL_LIST, MusicApplication::playIndexBy(), TTK::playlistRowValid(), MusicFunctionToolBoxWidget::removeItem(), MusicFunctionToolBoxWidget::setCurrentIndex(), MusicMessageBox::setText(), and TTK_NORMAL_LEVEL.
Referenced by contextMenuEvent().
void MusicSongsSummariziedWidget::dragEnterEvent (QDragEnterEvent * event) final override private virtual
Definition at line 1030 of file musicsongssummariziedwidget.cpp.
void MusicSongsSummariziedWidget::dragMoveEvent (QDragMoveEvent * event) final override private virtual
Definition at line 1037 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::m_itemList, TTK::playlistRowValid(), and qAsConst.
void MusicSongsSummariziedWidget::dropEvent (QDropEvent * event) final override private virtual
Definition at line 1060 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), importMusicSongsByPath(), MusicFunctionToolBoxWidget::m_itemList, TTK::playlistRowValid(), and qAsConst.
void MusicSongsSummariziedWidget::importMusicSongsByPath (const QStringList & files, int playlistRow)
Input imported music datas into container.
Definition at line 185 of file musicsongssummariziedwidget.cpp.
References closeSearchWidgetInNeed(), TTK::generateSongList(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemObject, MusicSongItem::m_songs, MusicSongsToolBoxWidget::makeValidIndex(), MusicToastLabel::popup(), qAsConst, MusicFunctionToolBoxWidget::setCurrentIndex(), setItemTitle(), MusicProgressWidget::setTitle(), MusicProgressWidget::show(), and MusicAbstractSongsListTableWidget::updateSongsList().
Referenced by addSongToPlaylist(), dropEvent(), importMusicSongsByUrl(), MusicApplication::importSongsByFiles(), and MusicApplication::importSongsOutsideMode().
void MusicSongsSummariziedWidget::importMusicSongsByUrl (const QString & path, int playlistRow)
Input imported music urls into container.
Definition at line 129 of file musicsongssummariziedwidget.cpp.
References closeSearchWidgetInNeed(), TTK::File::fileInfoListByPath(), importMusicSongsByPath(), TTK::String::isNetworkUrl(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemObject, MusicSongItem::m_songs, MusicSongsToolBoxWidget::makeValidIndex(), TTK::Algorithm::md5(), MUSIC_NETWORK_LIST, TTK::String::pefix(), setItemTitle(), TTK::String::splitToken(), MusicFormats::supportMusicFormats(), TTK_DEFAULT_STR, TTK_FILE_SUFFIX, TTK_SEPARATOR, and MusicAbstractSongsListTableWidget::updateSongsList().
Referenced by MusicApplication::importSongsByDir(), and MusicApplication::importSongsByUrl().
void MusicSongsSummariziedWidget::importSongsByDir (int index = TTK_LOW_LEVEL) slot
Import music songs by dir.
Definition at line 559 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), MusicApplication::importSongsByDir(), MusicApplication::instance(), MusicFunctionToolBoxWidget::m_currentIndex, and TTK_LOW_LEVEL.
Referenced by setInputModule().
void MusicSongsSummariziedWidget::importSongsByFiles (int index = TTK_LOW_LEVEL) slot
Import music songs by files.
Definition at line 539 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), MusicApplication::importSongsByFiles(), MusicApplication::instance(), MusicFunctionToolBoxWidget::m_currentIndex, and TTK_LOW_LEVEL.
Referenced by setInputModule().
void MusicSongsSummariziedWidget::isCurrentPlaylistRow (bool & state) slot
Check is current play stack widget.
Definition at line 842 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::currentIndex(), MusicFunctionToolBoxWidget::m_currentIndex, m_playRowIndex, m_selectDeleteIndex, and MUSIC_NONE_LIST.
Referenced by createWidgetItem().
void MusicSongsSummariziedWidget::isSearchedResultEmpty (bool & empty) slot
Check current list is searched or not.
Definition at line 848 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::hasSearchResult().
Referenced by createWidgetItem().
bool MusicSongsSummariziedWidget::isSearchPlayIndex () const inline private
Current index is searched or not.
Definition at line 255 of file musicsongssummariziedwidget.h.
References MusicFunctionToolBoxWidget::m_currentIndex.
Referenced by removeSearchResult(), and searchResultChanged().
void MusicSongsSummariziedWidget::itemIndexSwaped (int start, int end, int play, MusicSongList & songs) slot
Swap the current play index when user drag and drop.
Definition at line 817 of file musicsongssummariziedwidget.cpp.
References MusicPlayedListPopWidget::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, m_playRowIndex, QtContainerSwap, and MusicPlayedListPopWidget::setCurrentIndex().
Referenced by createWidgetItem().
QString MusicSongsSummariziedWidget::mapFilePathBySongIndex (int playlistRow, int index) const
Map music file path by song index.
Definition at line 274 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems.
Referenced by MusicApplication::playIndexBy(), MusicApplication::playSortBy(), and MusicApplication::readSystemConfigFromFile().
int MusicSongsSummariziedWidget::mapSongIndexByFilePath (int playlistRow, const QString & path) const
Map music song index by file path.
Definition at line 256 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems.
Referenced by MusicApplication::addSongToLovestList(), MusicApplication::containsLovestItem(), MusicApplication::currentFileName(), MusicApplication::currentFilePath(), MusicApplication::currentPlayLocation(), MusicApplication::showCurrentSong(), and MusicApplication::writeSystemConfigToFile().
const MusicSongItemList& MusicSongsSummariziedWidget::musicItemList () const inline
Query music datas from container.
Definition at line 59 of file musicsongssummariziedwidget.h.
References MusicItemSearchInterface< T >::m_containerItems.
Referenced by MusicApplication::containsLovestItem(), MusicApplication::currentFileName(), MusicApplication::currentFilePath(), MusicApplication::exportSongsItemList(), MusicApplication::playIndexBy(), MusicApplication::playIndexClicked(), and MusicApplication::writeSystemConfigToFile().
QStringList MusicSongsSummariziedWidget::musicSongsFileName (int index) const
Get music songs file name by index.
Definition at line 225 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, and qAsConst.
Referenced by MusicApplication::currentPlaylist(), and searchResultChanged().
QStringList MusicSongsSummariziedWidget::musicSongsFilePath (int index) const
Get music songs file path by index.
Definition at line 241 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, and qAsConst.
Referenced by MusicApplication::readSystemConfigFromFile(), and MusicApplication::setPlayIndex().
void MusicSongsSummariziedWidget::playLocation (int index)
Show current play index.
Definition at line 325 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::hasSearchResult(), MusicFunctionToolBoxWidget::resizeScrollIndex(), and selectRow().
Referenced by MusicApplication::currentPlayLocation().
int MusicSongsSummariziedWidget::playRowIndex () const inline
Get current play row index.
Definition at line 95 of file musicsongssummariziedwidget.h.
Referenced by MusicApplication::containsDownloadItem(), and MusicApplication::containsLovestItem().
void MusicSongsSummariziedWidget::queryMusicItemList (MusicSongItemList & songs) slot
Query music datas from container.
Definition at line 913 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems.
void MusicSongsSummariziedWidget::removeItemAt (const TTKIntList & del, bool fileRemove) slot
Remove items from indexs and check remove file or not.
Definition at line 777 of file musicsongssummariziedwidget.cpp.
References MusicApplication::addSongToLovestList(), MusicFunctionToolBoxWidget::currentIndex(), TTK::generateNetworkSongPath(), MusicItemSearchInterface< MusicSongItemList >::hasSearchResult(), MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, MusicSongItem::m_itemObject, m_playRowIndex, m_selectDeleteIndex, MusicSongItem::m_songs, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, MUSIC_NONE_LIST, MusicSong::path(), MusicApplication::removeItemAt(), setItemTitle(), and TTKObjectCast.
Referenced by createWidgetItem().
void MusicSongsSummariziedWidget::removeSearchResult (int & row)
Get search result index from list by given row and clear cache.
Definition at line 290 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::clearSearchResult(), closeSearchWidget(), MusicItemSearchInterface< MusicSongItemList >::hasSearchResult(), isSearchPlayIndex(), MusicItemSearchInterface< MusicSongItemList >::m_searchResultCache, and MusicItemSearchInterface< MusicSongItemList >::m_searchResultLevel.
Referenced by MusicApplication::playIndexBy().
void MusicSongsSummariziedWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 1024 of file musicsongssummariziedwidget.cpp.
References resizeWindow().
void MusicSongsSummariziedWidget::resizeWindow () private
Resize window bound by resize called.
Definition at line 1205 of file musicsongssummariziedwidget.cpp.
References m_listFunctionWidget, and m_songSearchWidget.
Referenced by resizeEvent(), showFloatWidget(), and showSearchWidget().
void MusicSongsSummariziedWidget::searchResultChanged (int row, int column) slot
Search result from list.
Definition at line 589 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::clearSearchResult(), isSearchPlayIndex(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, MusicSongItem::m_itemObject, m_lastSearchIndex, MusicItemSearchInterface< MusicSongItemList >::m_searchResultCache, MusicItemSearchInterface< MusicSongItemList >::m_searchResultLevel, MusicSongItem::m_songs, m_songSearchWidget, musicSongsFileName(), MusicSongSearchDialog::text(), TTKObjectCast, and MusicAbstractSongsListTableWidget::updateSongsList().
void MusicSongsSummariziedWidget::selectRow (int index)
Select the current play row.
Definition at line 334 of file musicsongssummariziedwidget.cpp.
References closeSearchWidgetInNeed(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_playRowIndex, and MusicFunctionToolBoxWidget::setCurrentIndex().
Referenced by playLocation(), and MusicApplication::showCurrentSong().
void MusicSongsSummariziedWidget::setCurrentSongTreeIndex (int index)
Set current song tree index.
Definition at line 310 of file musicsongssummariziedwidget.cpp.
References MusicSongsListPlayTableWidget::adjustPlayWidgetRow(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_playRowIndex, and TTKObjectCast.
Referenced by MusicApplication::setPlayIndex(), and MusicApplication::showCurrentSong().
void MusicSongsSummariziedWidget::setInputModule (QObject * object) const private
Set input connection.
Definition at line 1191 of file musicsongssummariziedwidget.cpp.
References addNewRowItem(), addToPlayedList(), addToPlayLater(), changRowItemName(), deleteRowItem(), deleteRowItemAll(), importSongsByDir(), importSongsByFiles(), songListSortBy(), and swapDragItemIndex().
Referenced by createWidgetItem(), and MusicSongsSummariziedWidget().
void MusicSongsSummariziedWidget::setItemTitle (MusicSongItem * item) private
Set item title.
Definition at line 1180 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxTopWidget::index(), MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, MusicSongItem::m_itemObject, m_listMaskWidget, MusicSongItem::m_songs, MusicFunctionToolBoxTopWidget::setTitle(), and MusicFunctionToolBoxWidget::setTitle().
Referenced by addSongBufferToPlaylist(), addSongToLovestList(), changRowItemName(), importMusicSongsByPath(), importMusicSongsByUrl(), removeItemAt(), and songToLovestListAt().
void MusicSongsSummariziedWidget::setMusicPlayCount (int index) slot
Set current music song play count by given song index.
Definition at line 853 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_playRowIndex, MusicSong::playCount(), and MusicSong::setPlayCount().
Referenced by MusicApplication::showCurrentSong(), and updateCurrentIndex().
void MusicSongsSummariziedWidget::setRecentMusicSongs (int index) slot
Input recent imported music datas into container.
Definition at line 868 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemName, MusicSongItem::m_itemObject, m_playRowIndex, MusicSongItem::m_songs, MUSIC_NETWORK_LIST, MUSIC_RECENT_LIST, RECENT_ITEM_MAX_COUNT, MusicSongsListPlayTableWidget::removeItems(), MusicFunctionToolBoxWidget::setTitle(), TTKObjectCast, and MusicSongsListPlayTableWidget::updateSongsList().
Referenced by MusicApplication::showCurrentSong().
void MusicSongsSummariziedWidget::showFloatWidget () slot
Show the float function widget.
Definition at line 928 of file musicsongssummariziedwidget.cpp.
References MusicSongsListFunctionWidget::active(), deleteFloatWidget(), m_listFunctionWidget, and resizeWindow().
Referenced by createWidgetItem().
void MusicSongsSummariziedWidget::showLrcDownloadBatchWidget () slot
Open lrc batch download.
Definition at line 584 of file musicsongssummariziedwidget.cpp.
References TTKGenerateSingleWidget.
Referenced by contextMenuEvent().
void MusicSongsSummariziedWidget::showSearchWidget () private slot
Show searched text widget.
Definition at line 989 of file musicsongssummariziedwidget.cpp.
References m_songSearchWidget, resizeWindow(), and MusicSongSearchDialog::setVisible().
void MusicSongsSummariziedWidget::showSongCheckToolsWidget () slot
Open music songs check test tools.
Definition at line 579 of file musicsongssummariziedwidget.cpp.
References TTKGenerateSingleWidget.
Referenced by contextMenuEvent().
void MusicSongsSummariziedWidget::sliderValueChanaged (int value) private slot
Current vertical slider value chanaged.
Definition at line 1000 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, m_listMaskWidget, MusicSongItem::m_songs, MusicSongItem::m_sort, MusicFunctionToolBoxTopWidget::setExpand(), MusicFunctionToolBoxTopWidget::setIndex(), MusicSongsToolBoxTopWidget::setSongSort(), and MusicFunctionToolBoxTopWidget::setTitle().
Referenced by MusicSongsSummariziedWidget().
void MusicSongsSummariziedWidget::songListSortBy (int index) slot
Music list songs sort by type.
Definition at line 944 of file musicsongssummariziedwidget.cpp.
References MusicSong::ByFileName, closeSearchWidgetInNeed(), MusicFunctionToolBoxWidget::foundMappedIndex(), MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, m_playRowIndex, MusicApplication::playSortBy(), MusicSongsListPlayTableWidget::removeItems(), MusicAbstractSongsListTableWidget::setSongsList(), TTKObjectCast, and TTKStaticCast.
Referenced by createWidgetItem(), and setInputModule().
void MusicSongsSummariziedWidget::songToLovestListAt (bool state, int row) slot
Add or remove music song to lovest list by row.
Add to lovest list
Remove to lovest list
Definition at line 661 of file musicsongssummariziedwidget.cpp.
References MusicApplication::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicSongItem::m_itemObject, m_playRowIndex, MusicSongItem::m_songs, MUSIC_LOVEST_LIST, MusicSong::path(), MusicSongsListPlayTableWidget::removeItems(), MusicApplication::removeLoveItemAt(), setItemTitle(), TTKObjectCast, and MusicSongsListPlayTableWidget::updateSongsList().
Referenced by MusicApplication::addSongToLovestList().
void MusicSongsSummariziedWidget::swapDragItemIndex (int start, int end) slot
Swap the item index by drag adn drop.
Definition at line 468 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, MusicFunctionToolBoxWidget::m_currentIndex, m_playRowIndex, MusicFunctionToolBoxWidget::swapItem(), and updatePlayedList().
Referenced by setInputModule().
void MusicSongsSummariziedWidget::updateCurrentArtist () slot
Update current artist when it download finished.
Definition at line 918 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_playRowIndex, and TTKObjectCast.
Referenced by MusicApplication::updateCurrentArtist().
void MusicSongsSummariziedWidget::updateCurrentIndex () slot
Update current play index from config file.
Definition at line 645 of file musicsongssummariziedwidget.cpp.
References G_SETTING_PTR, MusicApplication::instance(), MusicSettingManager::LastPlayIndex, m_playRowIndex, MusicFunctionToolBoxWidget::setCurrentIndex(), setMusicPlayCount(), and MusicApplication::showCurrentSong().
void MusicSongsSummariziedWidget::updatePlayedList (int start, int end) private
Update current played list.
Definition at line 1218 of file musicsongssummariziedwidget.cpp.
References MusicFunctionToolBoxWidget::foundMappedIndex(), MusicPlayedListPopWidget::instance(), MusicItemSearchInterface< MusicSongItemList >::m_containerItems, qAsConst, and MusicPlayedListPopWidget::updatePlayedList().
Referenced by deleteRowItem(), and swapDragItemIndex().
void MusicSongsSummariziedWidget::updateTimeLabel (const QString & current, const QString & total) const
Update item time label time.
Definition at line 346 of file musicsongssummariziedwidget.cpp.
References MusicItemSearchInterface< MusicSongItemList >::m_containerItems, m_playRowIndex, and TTKObjectCast.
Referenced by MusicApplication::positionChanged().
Member Data Documentation
int MusicSongsSummariziedWidget::m_lastSearchIndex private
Definition at line 294 of file musicsongssummariziedwidget.h.
Referenced by searchResultChanged().
MusicSongsListFunctionWidget* MusicSongsSummariziedWidget::m_listFunctionWidget private
Definition at line 298 of file musicsongssummariziedwidget.h.
Referenced by deleteFloatWidget(), resizeWindow(), showFloatWidget(), and ~MusicSongsSummariziedWidget().
MusicSongsToolBoxMaskWidget* MusicSongsSummariziedWidget::m_listMaskWidget private
Definition at line 297 of file musicsongssummariziedwidget.h.
Referenced by MusicSongsSummariziedWidget(), setItemTitle(), sliderValueChanaged(), and ~MusicSongsSummariziedWidget().
int MusicSongsSummariziedWidget::m_playRowIndex private
Definition at line 293 of file musicsongssummariziedwidget.h.
Referenced by addSongToLovestList(), deleteRowItem(), deleteRowItemAll(), deleteRowItems(), isCurrentPlaylistRow(), itemIndexSwaped(), removeItemAt(), selectRow(), setCurrentSongTreeIndex(), setMusicPlayCount(), setRecentMusicSongs(), songListSortBy(), songToLovestListAt(), swapDragItemIndex(), updateCurrentArtist(), updateCurrentIndex(), and updateTimeLabel().
int MusicSongsSummariziedWidget::m_selectDeleteIndex private
Definition at line 295 of file musicsongssummariziedwidget.h.
Referenced by deleteRowItemAll(), isCurrentPlaylistRow(), and removeItemAt().
MusicSongSearchDialog* MusicSongsSummariziedWidget::m_songSearchWidget private
Definition at line 299 of file musicsongssummariziedwidget.h.
Referenced by closeSearchWidget(), resizeWindow(), searchResultChanged(), showSearchWidget(), and ~MusicSongsSummariziedWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicsongssummariziedwidget.h
TTKModule/TTKWidget/musicToolsKits/musicsongssummariziedwidget.cpp