TTKMusicplayer: MusicBackgroundSkinDialog Class Reference
MusicBackgroundSkinDialog Class Reference
The class of the local background widget.
#include <musicbackgroundskindialog.h>
Public Slots
void showPaletteDialog ()
void showPaletteDialog (const QString &path)
void showCustomSkinDialog ()
void backgroundListWidgetChanged (int index)
void classicalListWidgetItemClicked (int type, const QString &name)
void remoteListWidgetItemClicked (int type, const QString &name)
void currentColorChanged (const QString &path)
void windowTransparentChanged (bool state)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void currentTextChanged (const QString &text)
Public Member Functions
MusicBackgroundSkinDialog (QWidget *parent=nullptr)
~MusicBackgroundSkinDialog ()
void updateArtistFileTheme (const QString &theme)
void setCurrentBackgroundTheme (const QString &theme, int skin, int list)
int backgroundListAlpha () const
bool backgroundTransparentEnable () const
void setSkinTransToolText (int value)
void setListTransToolText (int value)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QPixmap setBackgroundUrl (QString &name)
static bool themeValidCheck (QString &name, QString &path)
static QString cpoyArtistFileToLocal (const QString &path)
Protected Member Functions
void listWidgetItemClicked (MusicBackgroundListWidget *item, const QString &name)
void listWidgetItemClicked (MusicBackgroundRemoteWidget *item, const QString &name)
void addThemeListWidgetItem ()
void addThemeListWidgetItem (MusicBackgroundListWidget *item, const QString &dir, bool state)
void cpoyFileFromLocal (const QString &path)
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Static Protected Member Functions
static void findThemeListByPath (const QString &dir, TTKIntList &data)
static int cpoyFileToLocalIndex ()
static int cpoyFileToLocal (const QString &path)
Protected Attributes
Ui::MusicBackgroundSkinDialog * m_ui
int m_stackThemeIndex
MusicBackgroundListWidget * m_cacheBackgroundList
MusicBackgroundListWidget * m_stackBackgroundList
MusicBackgroundDailyWidget * m_dailyBackgroundList
MusicBackgroundOnlineWidget * m_onlineBackgroundList
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the local background widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 36 of file musicbackgroundskindialog.h.
Constructor & Destructor Documentation
MusicBackgroundSkinDialog::MusicBackgroundSkinDialog (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 15 of file musicbackgroundskindialog.cpp.
References addThemeListWidgetItem(), backgroundListWidgetChanged(), classicalListWidgetItemClicked(), MusicBackgroundListWidget::First, MusicUtils::Widget::generateVScrollAreaFormat(), MusicApplicationModule::instance(), MusicTopAreaWidget::instance(), m_cacheBackgroundList, m_dailyBackgroundList, m_onlineBackgroundList, m_stackBackgroundList, m_ui, MusicUIObject::MQSSBtnResetWindow, MusicUIObject::MQSSCheckBoxStyle04, MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, MusicUIObject::MQSSToolButtonStyle06, MusicAnimationStackedWidget::RightToLeft, MusicBackgroundListWidget::Second, MusicBackgroundListWidget::setType(), showCustomSkinDialog(), showPaletteDialog(), and windowTransparentChanged().
MusicBackgroundSkinDialog::~MusicBackgroundSkinDialog ()
Definition at line 77 of file musicbackgroundskindialog.cpp.
References m_cacheBackgroundList, m_dailyBackgroundList, m_onlineBackgroundList, m_stackBackgroundList, and m_ui.
Member Function Documentation
void MusicBackgroundSkinDialog::addThemeListWidgetItem () protected
Add all theme into list.
Definition at line 339 of file musicbackgroundskindialog.cpp.
References m_cacheBackgroundList, m_stackBackgroundList, THEME_DIR_FULL, and USER_THEME_DIR_FULL.
Referenced by MusicBackgroundSkinDialog().
void MusicBackgroundSkinDialog::addThemeListWidgetItem (MusicBackgroundListWidget * item, const QString & dir, bool state) protected
Add all theme into list.
Definition at line 345 of file musicbackgroundskindialog.cpp.
References MusicBackgroundListWidget::createItem(), findThemeListByPath(), and TKM_FILE.
int MusicBackgroundSkinDialog::backgroundListAlpha () const
Get list background skin alpha.
Definition at line 144 of file musicbackgroundskindialog.cpp.
References m_ui.
Referenced by MusicTopAreaWidget::backgroundListAlpha().
void MusicBackgroundSkinDialog::backgroundListWidgetChanged (int index) slot
Background list widget changed.
Definition at line 204 of file musicbackgroundskindialog.cpp.
References MusicBackgroundRemoteWidget::abort(), MusicBackgroundOnlineWidget::createFunctionsWidget(), MusicBackgroundDailyWidget::initialize(), MusicBackgroundOnlineWidget::initialize(), m_dailyBackgroundList, m_onlineBackgroundList, and m_ui.
Referenced by MusicBackgroundSkinDialog().
bool MusicBackgroundSkinDialog::backgroundTransparentEnable () const
Get background window skin enable.
Definition at line 149 of file musicbackgroundskindialog.cpp.
References m_ui.
Referenced by MusicTopAreaWidget::backgroundTransparentEnable().
void MusicBackgroundSkinDialog::classicalListWidgetItemClicked (int type, const QString & name) slot
Classical list widget item has clicked.
Definition at line 235 of file musicbackgroundskindialog.cpp.
References MusicBackgroundListWidget::contains(), MusicBackgroundListWidget::createItem(), MusicBackgroundListWidget::First, listWidgetItemClicked(), m_cacheBackgroundList, m_stackBackgroundList, THEME_DIR_FULL, TKM_FILE, and USER_THEME_DIR_FULL.
Referenced by MusicBackgroundSkinDialog().
QString MusicBackgroundSkinDialog::cpoyArtistFileToLocal (const QString & path) static
Copy art file to local themes dir path.
Definition at line 116 of file musicbackgroundskindialog.cpp.
References cpoyFileToLocal().
Referenced by MusicTopAreaWidget::musicSetAsArtistBackground().
void MusicBackgroundSkinDialog::cpoyFileFromLocal (const QString & path) protected
Copy custom file to local themes dir path.
Definition at line 358 of file musicbackgroundskindialog.cpp.
References cpoyFileToLocal(), MusicBackgroundListWidget::createItem(), m_stackBackgroundList, m_stackThemeIndex, TKM_FILE, and USER_THEME_DIR_FULL.
Referenced by showCustomSkinDialog(), and showPaletteDialog().
int MusicBackgroundSkinDialog::cpoyFileToLocal (const QString & path) static protected
Copy custom file .
Definition at line 412 of file musicbackgroundskindialog.cpp.
References cpoyFileToLocalIndex(), MusicExtractWrapper::inputSkin(), MusicBackgroundImage::m_pix, TKM_FILE, and USER_THEME_DIR_FULL.
Referenced by cpoyArtistFileToLocal(), and cpoyFileFromLocal().
int MusicBackgroundSkinDialog::cpoyFileToLocalIndex () static protected
Copy custom file index.
Definition at line 393 of file musicbackgroundskindialog.cpp.
References CURRENT_ITEMS_COUNT, findThemeListByPath(), and USER_THEME_DIR_FULL.
Referenced by cpoyFileToLocal(), listWidgetItemClicked(), and showCustomSkinDialog().
void MusicBackgroundSkinDialog::currentColorChanged (const QString & path) slot
Update app background when user change the current background emit.
Definition at line 263 of file musicbackgroundskindialog.cpp.
References G_BACKGROUND_PTR, MusicTopAreaWidget::instance(), MUSIC_COLOR_FILE, MusicTopAreaWidget::musicBackgroundSkinChanged(), and MusicTopAreaWidget::musicBackgroundTransparentChanged().
Referenced by showPaletteDialog().
void MusicBackgroundSkinDialog::currentTextChanged (const QString & text) signal
Update app background when user change the current background emit.
int MusicBackgroundSkinDialog::exec () virtual slot
Override exec function.
Definition at line 289 of file musicbackgroundskindialog.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicTopAreaWidget::musicShowSkinChangedWindow().
void MusicBackgroundSkinDialog::findThemeListByPath (const QString & dir, TTKIntList & data) static protected
Find all theme in local directory.
Definition at line 369 of file musicbackgroundskindialog.cpp.
References FILE_SUFFIX, TKM_FILE_PREFIX, and TTK_DEFAULT_STR.
Referenced by addThemeListWidgetItem(), and cpoyFileToLocalIndex().
void MusicBackgroundSkinDialog::listWidgetItemClicked (MusicBackgroundListWidget * item, const QString & name) protected
Background list widget item has clicked changed.
Definition at line 295 of file musicbackgroundskindialog.cpp.
References MusicBackgroundListWidget::clearSelectState(), G_BACKGROUND_PTR, MusicTopAreaWidget::instance(), MusicTopAreaWidget::musicBackgroundSkinChanged(), MusicBackgroundListWidget::setCurrentItemName(), themeValidCheck(), TKM_FILE, and USER_THEME_DIR_FULL.
Referenced by classicalListWidgetItemClicked(), listWidgetItemClicked(), and remoteListWidgetItemClicked().
void MusicBackgroundSkinDialog::listWidgetItemClicked (MusicBackgroundRemoteWidget * item, const QString & name) protected
Background list widget item has clicked changed.
Definition at line 309 of file musicbackgroundskindialog.cpp.
References MusicBackgroundListWidget::clearSelectState(), MusicBackgroundListWidget::contains(), cpoyFileToLocalIndex(), MusicBackgroundListWidget::createItem(), MusicBackgroundListItem::fileName(), MusicBackgroundListWidget::find(), MusicExtractWrapper::inputSkin(), MusicBackgroundImage::isValid(), listWidgetItemClicked(), m_cacheBackgroundList, m_stackBackgroundList, MusicBackgroundRemoteWidget::outputRemoteSkin(), TKM_FILE, and USER_THEME_DIR_FULL.
void MusicBackgroundSkinDialog::remoteListWidgetItemClicked (int type, const QString & name) slot
Remote background list widget item has clicked.
Definition at line 253 of file musicbackgroundskindialog.cpp.
References MusicBackgroundListWidget::Four, listWidgetItemClicked(), m_dailyBackgroundList, m_onlineBackgroundList, and MusicBackgroundListWidget::Third.
QPixmap MusicBackgroundSkinDialog::setBackgroundUrl (QString & name) static
Set artist background picture by name.
Definition at line 86 of file musicbackgroundskindialog.cpp.
References G_BACKGROUND_PTR, MusicBackgroundImage::m_pix, MusicExtractWrapper::outputSkin(), themeValidCheck(), TKM_FILE, and USER_THEME_DIR_FULL.
Referenced by MusicTopAreaWidget::drawWindowBackgroundRect().
void MusicBackgroundSkinDialog::setCurrentBackgroundTheme (const QString & theme, int skin, int list)
Select current item by name when the widget show.
Definition at line 129 of file musicbackgroundskindialog.cpp.
References MusicSettingManager::BackgroundTransparentEnable, G_SETTING_PTR, m_cacheBackgroundList, m_stackBackgroundList, m_ui, MusicBackgroundListWidget::setCurrentItemName(), setListTransToolText(), and setSkinTransToolText().
Referenced by MusicTopAreaWidget::musicShowSkinChangedWindow().
void MusicBackgroundSkinDialog::setListTransToolText (int value)
Set list transparent tool text.
Definition at line 159 of file musicbackgroundskindialog.cpp.
References m_ui.
Referenced by MusicTopAreaWidget::musicPlaylistTransparent(), and setCurrentBackgroundTheme().
void MusicBackgroundSkinDialog::setSkinTransToolText (int value)
Set skin transparent tool text.
Definition at line 154 of file musicbackgroundskindialog.cpp.
References m_ui.
Referenced by MusicTopAreaWidget::musicBackgroundTransparentChanged(), and setCurrentBackgroundTheme().
void MusicBackgroundSkinDialog::showCustomSkinDialog () slot
Change index to custom skin dialog.
Definition at line 178 of file musicbackgroundskindialog.cpp.
References cpoyFileFromLocal(), cpoyFileToLocalIndex(), MusicBackgroundListWidget::createItem(), FILE_SUFFIX, m_stackBackgroundList, m_stackThemeIndex, MusicUtils::File::openFileDialog(), TKM_FILE, TKM_FILE_PREFIX, MusicBackgroundListWidget::updateLastedItem(), and USER_THEME_DIR_FULL.
Referenced by MusicBackgroundSkinDialog().
void MusicBackgroundSkinDialog::showPaletteDialog () slot
Change index to palette dialog.
Definition at line 164 of file musicbackgroundskindialog.cpp.
References currentColorChanged(), and MusicBackgroundPaletteWidget::exec().
Referenced by MusicBackgroundSkinDialog().
void MusicBackgroundSkinDialog::showPaletteDialog (const QString & path) slot
Change index to palette dialog.
Definition at line 172 of file musicbackgroundskindialog.cpp.
References cpoyFileFromLocal(), m_stackBackgroundList, and MusicBackgroundListWidget::updateLastedItem().
bool MusicBackgroundSkinDialog::themeValidCheck (QString & name, QString & path) static
Theme valid check.
Definition at line 96 of file musicbackgroundskindialog.cpp.
References THEME_DIR_FULL, TKM_FILE, and USER_THEME_DIR_FULL.
Referenced by listWidgetItemClicked(), and setBackgroundUrl().
void MusicBackgroundSkinDialog::updateArtistFileTheme (const QString & theme)
Update artist file theme.
Definition at line 122 of file musicbackgroundskindialog.cpp.
References MusicBackgroundListWidget::createItem(), m_stackBackgroundList, TKM_FILE, MusicBackgroundListWidget::updateLastedItem(), and USER_THEME_DIR_FULL.
Referenced by MusicTopAreaWidget::musicSetAsArtistBackground().
void MusicBackgroundSkinDialog::windowTransparentChanged (bool state) slot
Window transparent changed.
Definition at line 278 of file musicbackgroundskindialog.cpp.
References MusicSettingManager::BackgroundTransparentEnable, G_SETTING_PTR, MusicTopAreaWidget::instance(), m_ui, and MusicTopAreaWidget::musicBackgroundTransparentChanged().
Referenced by MusicBackgroundSkinDialog().
Member Data Documentation
MusicBackgroundListWidget* MusicBackgroundSkinDialog::m_cacheBackgroundList protected
Definition at line 167 of file musicbackgroundskindialog.h.
Referenced by addThemeListWidgetItem(), classicalListWidgetItemClicked(), listWidgetItemClicked(), MusicBackgroundSkinDialog(), setCurrentBackgroundTheme(), and ~MusicBackgroundSkinDialog().
MusicBackgroundDailyWidget* MusicBackgroundSkinDialog::m_dailyBackgroundList protected
Definition at line 169 of file musicbackgroundskindialog.h.
Referenced by backgroundListWidgetChanged(), MusicBackgroundSkinDialog(), remoteListWidgetItemClicked(), and ~MusicBackgroundSkinDialog().
MusicBackgroundOnlineWidget* MusicBackgroundSkinDialog::m_onlineBackgroundList protected
Definition at line 170 of file musicbackgroundskindialog.h.
Referenced by backgroundListWidgetChanged(), MusicBackgroundSkinDialog(), remoteListWidgetItemClicked(), and ~MusicBackgroundSkinDialog().
MusicBackgroundListWidget* MusicBackgroundSkinDialog::m_stackBackgroundList protected
Definition at line 168 of file musicbackgroundskindialog.h.
Referenced by addThemeListWidgetItem(), classicalListWidgetItemClicked(), cpoyFileFromLocal(), listWidgetItemClicked(), MusicBackgroundSkinDialog(), setCurrentBackgroundTheme(), showCustomSkinDialog(), showPaletteDialog(), updateArtistFileTheme(), and ~MusicBackgroundSkinDialog().
int MusicBackgroundSkinDialog::m_stackThemeIndex protected
Definition at line 166 of file musicbackgroundskindialog.h.
Referenced by cpoyFileFromLocal(), and showCustomSkinDialog().
Ui::MusicBackgroundSkinDialog* MusicBackgroundSkinDialog::m_ui protected
Definition at line 165 of file musicbackgroundskindialog.h.
Referenced by backgroundListAlpha(), backgroundListWidgetChanged(), backgroundTransparentEnable(), exec(), MusicBackgroundSkinDialog(), setCurrentBackgroundTheme(), setListTransToolText(), setSkinTransToolText(), windowTransparentChanged(), and ~MusicBackgroundSkinDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundskindialog.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundskindialog.cpp