TTKMusicPlayer: MusicDownloadBirdSkinRequest Class Reference
MusicDownloadBirdSkinRequest Class Reference
The class of the download bird skin background.
#include <musicdownloadbirdskinrequest.h>
Public Slots
virtual void downLoadFinished (const QByteArray &bytes) overridefinal
void downLoadItemsFinished (const QByteArray &bytes)
Public Slots inherited from MusicAbstractDownloadSkinRequest
virtual void downLoadFinished (const QByteArray &bytes)=0
Signals
void downLoadItemsChanged (const MusicSkinRemoteGroup &bytes)
Signals inherited from MusicAbstractDownloadSkinRequest
void downLoadDataChanged (const MusicSkinRemoteGroupList &bytes)
Public Member Functions
MusicDownloadBirdSkinRequest (QObject *parent=nullptr)
virtual void startRequest () overridefinal
virtual void startRequest (const QString &id) overridefinal
Public Member Functions inherited from MusicAbstractDownloadSkinRequest
MusicAbstractDownloadSkinRequest (QObject *parent=nullptr)
Detailed Description
The class of the download bird skin background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadbirdskinrequest.h.
Constructor & Destructor Documentation
MusicDownloadBirdSkinRequest::MusicDownloadBirdSkinRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musicdownloadbirdskinrequest.cpp.
Member Function Documentation
void MusicDownloadBirdSkinRequest::downLoadFinished (const QByteArray & bytes) final override virtual slot
Download data from net finished.
Definition at line 27 of file musicdownloadbirdskinrequest.cpp.
References MusicAbstractDownloadSkinRequest::downLoadDataChanged(), MusicSkinRemoteGroup::m_group, MusicSkinRemoteGroup::m_id, MUSIC_BIRD_DIR, and QJson::Parser::parse().
Referenced by startRequest().
void MusicDownloadBirdSkinRequest::downLoadItemsChanged (const MusicSkinRemoteGroup & bytes) signal
Send download data from net.
Referenced by downLoadItemsFinished().
void MusicDownloadBirdSkinRequest::downLoadItemsFinished (const QByteArray & bytes) slot
Download item data from net finished.
Definition at line 60 of file musicdownloadbirdskinrequest.cpp.
References downLoadItemsChanged(), MusicSkinRemoteItem::isValid(), MusicSkinRemoteGroup::m_id, MusicSkinRemoteItem::m_index, MusicSkinRemoteGroup::m_items, MusicSkinRemoteItem::m_name, MusicSkinRemoteItem::m_url, MusicSkinRemoteItem::m_useCount, and QJson::Parser::parse().
Referenced by startRequest().
void MusicDownloadBirdSkinRequest::startRequest () final override virtual
Start to download data from net.
Reimplemented from MusicAbstractDownloadSkinRequest.
Definition at line 13 of file musicdownloadbirdskinrequest.cpp.
References downLoadFinished(), MAIN_URL, TTK::Algorithm::mdII(), and MusicDataSourceRequest::startRequest().
void MusicDownloadBirdSkinRequest::startRequest (const QString & id) final override virtual
Start to download data from net.
Reimplemented from MusicAbstractDownloadSkinRequest.
Definition at line 20 of file musicdownloadbirdskinrequest.cpp.
References downLoadItemsFinished(), TTK::Algorithm::mdII(), QUERY_URL, and MusicDataSourceRequest::startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadbirdskinrequest.h
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadbirdskinrequest.cpp