TTKMusicplayer: MusicClickedLabel Class Reference
MusicClickedLabel Class Reference
The class of the label widget that can click.
#include <musicclickedlabel.h>
Signals
void clicked ()
Public Member Functions
MusicClickedLabel (QWidget *parent=0)
MusicClickedLabel (const QString &text, QWidget *parent=0)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
Detailed Description
The class of the label widget that can click.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicclickedlabel.h.
Constructor & Destructor Documentation
MusicClickedLabel::MusicClickedLabel (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 5 of file musicclickedlabel.cpp.
MusicClickedLabel::MusicClickedLabel (const QString & text, QWidget * parent = 0) explicit
Definition at line 11 of file musicclickedlabel.cpp.
Member Function Documentation
void MusicClickedLabel::clicked () signal
Click the label emit.
Referenced by mousePressEvent(), and MusicLrcFloatPhotoItem::MusicLrcFloatPhotoItem().
QString MusicClickedLabel::getClassName () static
Get class object name.
Definition at line 17 of file musicclickedlabel.cpp.
void MusicClickedLabel::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Definition at line 22 of file musicclickedlabel.cpp.
References clicked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicclickedlabel.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicclickedlabel.cpp