TTKMusicPlayer: TTKCoreApplication Class Reference
TTKCoreApplication Class Reference
The class of the ttk core application.
#include <ttkcoreapplication.h>
Public Slots
bool sendMessage (const QString &message, int timeout=5000)
Signals
void messageReceived (const QString &message)
Public Member Functions
TTKCoreApplication (int &argc, char **argv)
TTKCoreApplication (const QString &id, int &argc, char **argv)
bool isRunning () const
QString id () const noexcept
Private Member Functions
void initialize (const QString &id={})
Detailed Description
The class of the ttk core application.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttkcoreapplication.h.
Constructor & Destructor Documentation
TTKCoreApplication::TTKCoreApplication (int & argc, char ** argv)
Object constructor.
Definition at line 29 of file ttkcoreapplication.cpp.
References initialize(), and TTK_INIT_PRIVATE.
TTKCoreApplication::TTKCoreApplication (const QString & id, int & argc, char ** argv)
Definition at line 36 of file ttkcoreapplication.cpp.
References initialize(), and TTK_INIT_PRIVATE.
Member Function Documentation
QString TTKCoreApplication::id () const noexcept
Get current server id.
Definition at line 49 of file ttkcoreapplication.cpp.
References TTK_D.
void TTKCoreApplication::initialize (const QString & id = {}) private
Init the system parameter.
Definition at line 61 of file ttkcoreapplication.cpp.
References messageReceived(), and TTK_D.
Referenced by TTKCoreApplication().
bool TTKCoreApplication::isRunning () const
Check the current server is running or not.
Definition at line 43 of file ttkcoreapplication.cpp.
References TTK_D.
void TTKCoreApplication::messageReceived (const QString & message) signal
Emit when the current message received.
Referenced by initialize().
bool TTKCoreApplication::sendMessage (const QString & message, int timeout = 5000) slot
Emit when the current message received.
Definition at line 55 of file ttkcoreapplication.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKCommon/TTKApplication/ttkcoreapplication.h
TTKCommon/TTKApplication/ttkcoreapplication.cpp