TTKMusicPlayer: MusicLrcContainerForWallpaper Class Reference
MusicLrcContainerForWallpaper Class Reference
The class of the wall paper lrc container.
#include <musiclrccontainerforwallpaper.h>
Public Slots
void changeCurrentLrcColor ()
void updateBackground (const QPixmap &pix)
Public Slots inherited from MusicLrcContainer
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
Public Member Functions
MusicLrcContainerForWallpaper (QWidget *parent=nullptr)
~MusicLrcContainerForWallpaper ()
virtual void startDrawLrc () overridefinal
virtual void stopDrawLrc () overridefinal
virtual void applyParameter () overridefinal
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
void updateCurrentLrc (qint64 time)
void updateCurrentLrc (const QString &text)
void start (bool immediate)
Public Member Functions inherited from MusicLrcContainer
MusicLrcContainer (QWidget *parent=nullptr)
~MusicLrcContainer ()
void setLinearGradientColor (MusicLrcColor::Color color)
void setLinearGradientColor (const MusicLrcColor &color)
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 totalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * lrcAnalysisModel () const
Private Slots
void updateAnimationLrc ()
Private Member Functions
void initCurrentLrc (const QString &str)
void setItemStyleSheet (int index, int size, int transparent)
Private Attributes
int m_animationFreshTime
MusicVLayoutAnimationWidget * m_layoutWidget
MusicDesktopWallpaperThread * m_wallThread
MusicTransitionAnimationLabel * m_background
Additional Inherited Members
Signals inherited from MusicLrcContainer
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Protected Member Functions inherited from MusicLrcContainer
void clearAllMusicLRCManager ()
Protected Attributes inherited from MusicLrcContainer
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_lrcManagers
MusicLrcSearchWidget * m_lrcSearchWidget
Detailed Description
The class of the wall paper lrc container.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrccontainerforwallpaper.h.
Constructor & Destructor Documentation
MusicLrcContainerForWallpaper::MusicLrcContainerForWallpaper (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musiclrccontainerforwallpaper.cpp.
References MusicLayoutAnimationWidget::connectTo(), LRC_WALLPAPER_TPYE, m_background, MusicLrcContainer::m_containerType, m_layoutWidget, m_wallThread, and updateBackground().
MusicLrcContainerForWallpaper::~MusicLrcContainerForWallpaper ()
Definition at line 40 of file musiclrccontainerforwallpaper.cpp.
References MusicLrcContainer::clearAllMusicLRCManager(), and m_wallThread.
Member Function Documentation
void MusicLrcContainerForWallpaper::applyParameter () final override virtual
Set setting parameter.
Reimplemented from MusicLrcContainer.
Definition at line 57 of file musiclrccontainerforwallpaper.cpp.
References G_SETTING_PTR, LRC_PER_WIDTH, MusicLrcContainer::m_lrcManagers, MUSIC_LRC_INTERIOR_MAX_LINE, MusicSettingManager::ScreenSize, setItemStyleSheet(), MusicLrcManager::setLrcFontSize(), MusicLrcManagerForInterior::setLrcPerWidth(), MusicLrcManager::setY(), and TTKObject_cast.
Referenced by MusicRightAreaWidget::applyParameter(), changeCurrentLrcColor(), and MusicRightAreaWidget::musicContainerForWallpaperClicked().
void MusicLrcContainerForWallpaper::changeCurrentLrcColor () slot
Change current lrc linear color.
Definition at line 153 of file musiclrccontainerforwallpaper.cpp.
References applyParameter().
void MusicLrcContainerForWallpaper::initCurrentLrc (const QString & str) private
Init current lrc when the first show.
Definition at line 175 of file musiclrccontainerforwallpaper.cpp.
References MusicLrcAnalysis::lineMax(), MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_lrcManagers, and MUSIC_LRC_INTERIOR_MAX_LINE.
Referenced by setLrcAnalysisModel().
void MusicLrcContainerForWallpaper::setItemStyleSheet (int index, int size, int transparent) private
Set per lrc line style sheet by index and size and transparent.
Definition at line 184 of file musiclrccontainerforwallpaper.cpp.
References G_SETTING_PTR, MusicLrcContainer::m_lrcManagers, MusicLrcColor::readColorConfig(), MusicLrcManagerForInterior::setFontSize(), MusicLrcManager::setFontTransparent(), MusicLrcContainer::setLinearGradientColor(), MusicLrcManagerForInterior::setTransparent(), TTKObject_cast, and TTKStatic_cast.
Referenced by applyParameter().
void MusicLrcContainerForWallpaper::setLrcAnalysisModel (MusicLrcAnalysis * analysis)
Set lrc analysis model.
Definition at line 98 of file musiclrccontainerforwallpaper.cpp.
References MusicLayoutAnimationWidget::addStretch(), MusicLayoutAnimationWidget::addWidget(), initCurrentLrc(), m_layoutWidget, MusicLrcContainer::m_lrcManagers, MUSIC_LRC_INTERIOR_MAX_LINE, MusicLrcContainer::setLrcAnalysisModel(), and start().
Referenced by MusicRightAreaWidget::musicContainerForWallpaperClicked().
void MusicLrcContainerForWallpaper::start (bool immediate)
Strat now.
Definition at line 135 of file musiclrccontainerforwallpaper.cpp.
References G_BACKGROUND_PTR, MusicDesktopWallpaperThread::isRunning(), m_wallThread, MusicDesktopWallpaperThread::setImagePath(), MusicDesktopWallpaperThread::start(), and MusicDesktopWallpaperThread::timeout().
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), setLrcAnalysisModel(), and updateCurrentLrc().
void MusicLrcContainerForWallpaper::startDrawLrc () final override virtual
Start timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 46 of file musiclrccontainerforwallpaper.cpp.
References MusicLrcContainer::m_lrcManagers, and MUSIC_LRC_INTERIOR_MAX_LINE.
Referenced by MusicRightAreaWidget::startDrawLrc().
void MusicLrcContainerForWallpaper::stopDrawLrc () final override virtual
Stop timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 51 of file musiclrccontainerforwallpaper.cpp.
References m_layoutWidget, MusicLrcContainer::m_lrcManagers, MUSIC_LRC_INTERIOR_MAX_LINE, and MusicLayoutAnimationWidget::stop().
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), and MusicRightAreaWidget::stopDrawLrc().
void MusicLrcContainerForWallpaper::updateAnimationLrc () private slot
Animation finished.
Definition at line 165 of file musiclrccontainerforwallpaper.cpp.
References MusicLrcAnalysis::lineMax(), m_animationFreshTime, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_lrcManagers, MUSIC_LRC_INTERIOR_MAX_LINE, and MusicLrcAnalysis::text().
void MusicLrcContainerForWallpaper::updateBackground (const QPixmap & pix) slot
Update background pixmap.
Definition at line 158 of file musiclrccontainerforwallpaper.cpp.
References G_SETTING_PTR, m_background, MusicSettingManager::ScreenSize, and MusicTransitionAnimationLabel::setPixmap().
Referenced by MusicLrcContainerForWallpaper().
void MusicLrcContainerForWallpaper::updateCurrentLrc (qint64 time)
Update current lrc by given time.
Definition at line 115 of file musiclrccontainerforwallpaper.cpp.
References MusicLrcAnalysis::isValid(), m_animationFreshTime, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, start(), and MusicVLayoutAnimationWidget::start().
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), and MusicRightAreaWidget::updateCurrentLrc().
void MusicLrcContainerForWallpaper::updateCurrentLrc (const QString & text)
Update current lrc by given text.
Definition at line 126 of file musiclrccontainerforwallpaper.cpp.
References MusicLrcContainer::m_lrcManagers, and MUSIC_LRC_INTERIOR_MAX_LINE.
Member Data Documentation
int MusicLrcContainerForWallpaper::m_animationFreshTime private
Definition at line 98 of file musiclrccontainerforwallpaper.h.
Referenced by updateAnimationLrc(), and updateCurrentLrc().
MusicTransitionAnimationLabel* MusicLrcContainerForWallpaper::m_background private
Definition at line 101 of file musiclrccontainerforwallpaper.h.
Referenced by MusicLrcContainerForWallpaper(), and updateBackground().
MusicVLayoutAnimationWidget* MusicLrcContainerForWallpaper::m_layoutWidget private
Definition at line 99 of file musiclrccontainerforwallpaper.h.
Referenced by MusicLrcContainerForWallpaper(), setLrcAnalysisModel(), stopDrawLrc(), and updateCurrentLrc().
MusicDesktopWallpaperThread* MusicLrcContainerForWallpaper::m_wallThread private
Definition at line 100 of file musiclrccontainerforwallpaper.h.
Referenced by MusicLrcContainerForWallpaper(), start(), and ~MusicLrcContainerForWallpaper().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforwallpaper.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforwallpaper.cpp