TTKMusicPlayer: MusicPlaylistManager Class Reference
MusicPlaylistManager Class Reference
The class of the playlist manager.
#include <musicplaylistmanager.h>
Public Member Functions
void writeSongItem (const QString &path, const MusicSongItemList &item)
void readSongItems (const QStringList &paths, MusicSongItemList &items)
Private Member Functions
bool readTKPLConfig (const QString &path, MusicSongItemList &items)
bool writeTKPLConfig (const QString &path, const MusicSongItemList &item)
bool readM3UConfig (const QString &path, MusicSongItemList &items)
bool writeM3UConfig (const QString &path, const MusicSongItemList &item)
bool readPLSConfig (const QString &path, MusicSongItemList &items)
bool writePLSConfig (const QString &path, const MusicSongItemList &item)
bool readWPLConfig (const QString &path, MusicSongItemList &items)
bool writeWPLConfig (const QString &path, const MusicSongItemList &item)
bool readXSPFConfig (const QString &path, MusicSongItemList &items)
bool writeXSPFConfig (const QString &path, const MusicSongItemList &item)
bool readJSPFConfig (const QString &path, MusicSongItemList &items)
bool writeJSPFConfig (const QString &path, const MusicSongItemList &item)
bool readASXConfig (const QString &path, MusicSongItemList &items)
bool writeASXConfig (const QString &path, const MusicSongItemList &item)
bool readFPLConfig (const QString &path, MusicSongItemList &items)
bool readDBPLConfig (const QString &path, MusicSongItemList &items)
bool readCSVConfig (const QString &path, MusicSongItemList &items)
bool writeCSVConfig (const QString &path, const MusicSongItemList &item)
bool readTXTConfig (const QString &path, MusicSongItemList &items)
bool writeTXTConfig (const QString &path, const MusicSongItemList &item)
Detailed Description
The class of the playlist manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicplaylistmanager.h.
Member Function Documentation
bool MusicPlaylistManager::readASXConfig (const QString & path, MusicSongItemList & items) private
Read asx music playlist data from file.
Definition at line 183 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicASXConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readCSVConfig (const QString & path, MusicSongItemList & items) private
Read csv music playlist data from file.
Definition at line 207 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicCSVConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readDBPLConfig (const QString & path, MusicSongItemList & items) private
Read deadbeef music playlist data from file.
Definition at line 201 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicDBPLConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readFPLConfig (const QString & path, MusicSongItemList & items) private
Read foobar2k music playlist data from file.
Definition at line 195 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicFPLConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readJSPFConfig (const QString & path, MusicSongItemList & items) private
Read jspf music playlist data from file.
Definition at line 171 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicJSPFConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readM3UConfig (const QString & path, MusicSongItemList & items) private
Read m3u music playlist data from file.
Definition at line 123 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicM3UConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readPLSConfig (const QString & path, MusicSongItemList & items) private
Read pls music playlist data from file.
Definition at line 135 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicPLSConfigManager::readBuffer().
Referenced by readSongItems().
void MusicPlaylistManager::readSongItems (const QStringList & paths, MusicSongItemList & items)
Read music playlist data from file.
Definition at line 57 of file musicplaylistmanager.cpp.
References ASX_FILE_SUFFIX, CSV_FILE_SUFFIX, DBPL_FILE_SUFFIX, FPL_FILE_SUFFIX, JSPF_FILE_SUFFIX, M3U8_FILE_SUFFIX, M3U_FILE_SUFFIX, PLS_FILE_SUFFIX, qAsConst, readASXConfig(), readCSVConfig(), readDBPLConfig(), readFPLConfig(), readJSPFConfig(), readM3UConfig(), readPLSConfig(), readTKPLConfig(), readTXTConfig(), readWPLConfig(), readXSPFConfig(), TTK::String::suffix(), TPL_FILE_SUFFIX, TTK_FILE_SUFFIX, TXT_FILE_SUFFIX, WPL_FILE_SUFFIX, and XSPF_FILE_SUFFIX.
Referenced by MusicApplication::importSongsItemList().
bool MusicPlaylistManager::readTKPLConfig (const QString & path, MusicSongItemList & items) private
Read ttk music playlist data from file.
Definition at line 111 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicTKPLConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readTXTConfig (const QString & path, MusicSongItemList & items) private
Read txt music playlist data from file.
Definition at line 219 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicTXTConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readWPLConfig (const QString & path, MusicSongItemList & items) private
Read wpl music playlist data from file.
Definition at line 147 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicWPLConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::readXSPFConfig (const QString & path, MusicSongItemList & items) private
Read xspf music playlist data from file.
Definition at line 159 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicXSPFConfigManager::readBuffer().
Referenced by readSongItems().
bool MusicPlaylistManager::writeASXConfig (const QString & path, const MusicSongItemList & item) private
Write asx music playlist data to file.
Definition at line 189 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicASXConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writeCSVConfig (const QString & path, const MusicSongItemList & item) private
Write csv music playlist data to file.
Definition at line 213 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicCSVConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writeJSPFConfig (const QString & path, const MusicSongItemList & item) private
Write jspf music playlist data to file.
Definition at line 177 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicJSPFConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writeM3UConfig (const QString & path, const MusicSongItemList & item) private
Write m3u music playlist data to file.
Definition at line 129 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicM3UConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writePLSConfig (const QString & path, const MusicSongItemList & item) private
Write pls music playlist data to file.
Definition at line 141 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicPLSConfigManager::writeBuffer().
Referenced by writeSongItem().
void MusicPlaylistManager::writeSongItem (const QString & path, const MusicSongItemList & item)
Write music playlist data to file.
Definition at line 14 of file musicplaylistmanager.cpp.
References ASX_FILE_SUFFIX, CSV_FILE_SUFFIX, JSPF_FILE_SUFFIX, M3U8_FILE_SUFFIX, M3U_FILE_SUFFIX, PLS_FILE_SUFFIX, TTK::String::suffix(), TPL_FILE_SUFFIX, TTK_FILE_SUFFIX, TXT_FILE_SUFFIX, WPL_FILE_SUFFIX, writeASXConfig(), writeCSVConfig(), writeJSPFConfig(), writeM3UConfig(), writePLSConfig(), writeTKPLConfig(), writeTXTConfig(), writeWPLConfig(), writeXSPFConfig(), and XSPF_FILE_SUFFIX.
Referenced by MusicApplication::exportSongsItem(), and MusicApplication::exportSongsItemList().
bool MusicPlaylistManager::writeTKPLConfig (const QString & path, const MusicSongItemList & item) private
Write ttk music playlist data to file.
Definition at line 117 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicTKPLConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writeTXTConfig (const QString & path, const MusicSongItemList & item) private
Write txt music playlist data to file.
Definition at line 225 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicTXTConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writeWPLConfig (const QString & path, const MusicSongItemList & item) private
Write wpl music playlist data to file.
Definition at line 153 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicWPLConfigManager::writeBuffer().
Referenced by writeSongItem().
bool MusicPlaylistManager::writeXSPFConfig (const QString & path, const MusicSongItemList & item) private
Write xspf music playlist data to file.
Definition at line 165 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicXSPFConfigManager::writeBuffer().
Referenced by writeSongItem().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicplaylistmanager.h
TTKModule/TTKCore/musicCoreKits/musicplaylistmanager.cpp