TTKMusicplayer: MusicWindowsManager Class Reference
MusicWindowsManager Class Reference
The class of the windows system manager.
#include <musicwindowsmanager.h>
Public Types
enum SystemType {
Windows_10, Windows_8_1, Windows_8, Windows_7,
Windows_Vista, Windows_XP, Windows_XP_Professional_x64_Edition, Windows_2000,
Windows_NT_4_0, Windows_95, Windows_98, Windows_Me,
Windows_Server_2003, Windows_Server_2003_R2, Windows_Server_2008, Windows_Server_2008_R2,
Windows_Server_2012, Windows_Unkown
}
Public Member Functions
bool isFileAssociate ()
void setMusicRegeditAssociateFileIcon ()
void setLeftWinEnable ()
int getLocalIEVersion () const
SystemType getWindowSystemName () const
void setFileLink (const QString &src, const QString &des, const QString &ico, const QString &args, const QString &description)
Protected Member Functions
bool currentNodeHasExist (const QString &key)
void createMusicRegedit (const QString &key)
Detailed Description
The class of the windows system manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwindowsmanager.h.
Member Enumeration Documentation
enum MusicWindowsManager::SystemType
Enumerator
Windows_10
Windows_8_1
Windows_8
Windows_7
Windows_Vista
Windows_XP
Windows_XP_Professional_x64_Edition
Windows_2000
Windows_NT_4_0
Windows_95
Windows_98
Windows_Me
Windows_Server_2003
Windows_Server_2003_R2
Windows_Server_2008
Windows_Server_2008_R2
Windows_Server_2012
Windows_Unkown
Definition at line 32 of file musicwindowsmanager.h.
Member Function Documentation
void MusicWindowsManager::createMusicRegedit (const QString & key) protected
Create music regedit item.
Definition at line 241 of file musicwindowsmanager.cpp.
References APP_DOT_NAME, key, MUSIC_OUTER_LIST, and MUSIC_OUTER_OPEN.
Referenced by setMusicRegeditAssociateFileIcon().
bool MusicWindowsManager::currentNodeHasExist (const QString & key) protected
Check current regedit item has exist.
Definition at line 223 of file musicwindowsmanager.cpp.
References APP_DOT_NAME, and key.
Referenced by isFileAssociate(), and setMusicRegeditAssociateFileIcon().
int MusicWindowsManager::getLocalIEVersion () const
Get local IE version.
Definition at line 47 of file musicwindowsmanager.cpp.
Referenced by MusicApplicationObject::musicToolSetsParameter().
MusicWindowsManager::SystemType MusicWindowsManager::getWindowSystemName () const
Get local system name.
Definition at line 77 of file musicwindowsmanager.cpp.
References Windows_10, Windows_2000, Windows_7, Windows_8, Windows_8_1, Windows_95, Windows_98, Windows_Me, Windows_NT_4_0, Windows_Server_2003, Windows_Server_2003_R2, Windows_Server_2008, Windows_Server_2008_R2, Windows_Server_2012, Windows_Unkown, Windows_Vista, Windows_XP, and Windows_XP_Professional_x64_Edition.
Referenced by MusicSettingWidget::initControllerParameter().
bool MusicWindowsManager::isFileAssociate ()
Check current is file associate.
Definition at line 16 of file musicwindowsmanager.cpp.
References currentNodeHasExist(), and MP3_FILE_PREFIX.
Referenced by MusicSettingWidget::initControllerParameter().
void MusicWindowsManager::setFileLink (const QString & src, const QString & des, const QString & ico, const QString & args, const QString & description)
Set file link.
Definition at line 163 of file musicwindowsmanager.cpp.
Referenced by MusicWebMusicRadioWidget::sendToDesktopLink().
void MusicWindowsManager::setLeftWinEnable ()
Set left win key enable.
Definition at line 34 of file musicwindowsmanager.cpp.
Referenced by MusicRightAreaWidget::musicContainerForWallpaperClicked(), and MusicRightAreaWidget::musicVideoSetPopup().
void MusicWindowsManager::setMusicRegeditAssociateFileIcon ()
Set music regedit associate file icon.
Definition at line 21 of file musicwindowsmanager.cpp.
References createMusicRegedit(), currentNodeHasExist(), and MusicFormats::supportFormatsString().
Referenced by MusicApplicationObject::getParameterSetting().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicwindowsmanager.h
TTKModule/TTKCore/musicCoreKits/musicwindowsmanager.cpp