TTKMusicplayer: MusicArtistQueryWidget Class Reference
MusicArtistQueryWidget Class Reference
The class of artist music query widget.
#include <musicartistquerywidget.h>
Public Slots
void queryAllFinished ()
void queryArtistFinished ()
void createArtistInfoItem (const MusicResultsItem &item)
void setCurrentIndex (int index)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistQueryWidget (QWidget *parent=nullptr)
~MusicArtistQueryWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractItemQueryWidget ()
void initWidget ()
Protected Member Functions
void createLabels ()
void initThirdWidget ()
void initFourthWidget ()
void initFivethWidget ()
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes
MusicArtistAlbumsQueryWidget * m_artistAlbums
MusicArtistMvsQueryWidget * m_artistMvs
MusicArtistSimilarQueryWidget * m_artistSim
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of artist music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 234 of file musicartistquerywidget.h.
Constructor & Destructor Documentation
MusicArtistQueryWidget::MusicArtistQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 353 of file musicartistquerywidget.cpp.
References MusicSongSharingWidget::Artist, G_DOWNLOAD_QUERY_PTR, m_artistAlbums, m_artistMvs, m_artistSim, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_shareType, and queryAllFinished().
MusicArtistQueryWidget::~MusicArtistQueryWidget ()
Definition at line 366 of file musicartistquerywidget.cpp.
References m_artistAlbums, m_artistMvs, and m_artistSim.
Member Function Documentation
void MusicArtistQueryWidget::createArtistInfoItem (const MusicResultsItem & item) slot
Create the current artist info item.
Definition at line 473 of file musicartistquerywidget.cpp.
References createLabels(), MusicAbstractItemQueryWidget::downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicResultsItem::m_description, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::m_infoLabel, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MusicDownloadSourceRequest::startToDownload(), and TTK_NULL_STR.
Referenced by setSongNameById().
void MusicArtistQueryWidget::createLabels () protected
Create init interface lables.
Definition at line 554 of file musicartistquerywidget.cpp.
References MusicUtils::Widget::generateVScrollAreaFormat(), MusicAbstractItemQueryWidget::initFirstWidget(), MusicAbstractItemQueryWidget::initSecondWidget(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_iconLabel, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songButton, MusicAbstractItemQueryWidget::m_statusLabel, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSColorStyle05, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSFontStyle06, MusicUIObject::MQSSPushButtonStyle03, MusicAbstractItemQueryWidget::playAllButtonClicked(), setCurrentIndex(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), MusicAbstractItemQueryWidget::shareButtonClicked(), and TTK_DEFAULT_STR.
Referenced by createArtistInfoItem().
void MusicArtistQueryWidget::initFivethWidget () protected
Init the five widget.
Definition at line 756 of file musicartistquerywidget.cpp.
References m_artistSim, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_songNameFull, and MusicArtistSimilarQueryWidget::setSongName().
Referenced by setCurrentIndex().
void MusicArtistQueryWidget::initFourthWidget () protected
Init the fourth widget.
Definition at line 749 of file musicartistquerywidget.cpp.
References m_artistMvs, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_songNameFull, and MusicArtistMvsQueryWidget::setSongName().
Referenced by setCurrentIndex().
void MusicArtistQueryWidget::initThirdWidget () protected
Init the third widget.
Definition at line 742 of file musicartistquerywidget.cpp.
References m_artistAlbums, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_songNameFull, and MusicArtistAlbumsQueryWidget::setSongName().
Referenced by setCurrentIndex().
void MusicArtistQueryWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 427 of file musicartistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_songNameFull, MusicAbstractItemQueryWidget::m_statusLabel, MusicAbstractQueryRequest::musicSongInfos(), and setSongNameById().
Referenced by MusicArtistQueryWidget().
void MusicArtistQueryWidget::queryArtistFinished () slot
Query artist musics is finished.
Definition at line 454 of file musicartistquerywidget.cpp.
References MusicQueryTableWidget::getQueryInput(), MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_statusLabel, MusicAbstractQueryRequest::musicSongInfos(), and MusicAbstractItemQueryWidget::setSongCountText().
void MusicArtistQueryWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 390 of file musicartistquerywidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, m_artistAlbums, m_artistMvs, m_artistSim, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicItemQueryTableWidget::resizeWindow(), MusicArtistMvsQueryWidget::resizeWindow(), MusicArtistSimilarQueryWidget::resizeWindow(), MusicArtistAlbumsQueryWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
void MusicArtistQueryWidget::setCurrentIndex (int index) slot
Set current container index.
Definition at line 511 of file musicartistquerywidget.cpp.
References initFivethWidget(), initFourthWidget(), initThirdWidget(), m_artistAlbums, m_artistMvs, m_artistSim, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_infoLabel, and MusicAbstractItemQueryWidget::m_queryTableWidget.
Referenced by createLabels().
void MusicArtistQueryWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 373 of file musicartistquerywidget.cpp.
References MusicUtils::String::artistName(), MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractQueryRequest::MusicQuery, MusicAbstractQueryRequest::setQueryAllRecords(), MusicAbstractQueryRequest::setQuerySimplify(), MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicRightAreaWidget::musicArtistFound().
void MusicArtistQueryWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 381 of file musicartistquerywidget.cpp.
References createArtistInfoItem(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicItemQueryTableWidget::setQueryInput(), MusicAbstractItemQueryWidget::setSongName(), and MusicItemQueryTableWidget::startSearchQuery().
Referenced by MusicRightAreaWidget::musicArtistFound(), and queryAllFinished().
Member Data Documentation
MusicArtistAlbumsQueryWidget* MusicArtistQueryWidget::m_artistAlbums protected
Definition at line 295 of file musicartistquerywidget.h.
Referenced by initThirdWidget(), MusicArtistQueryWidget(), resizeWindow(), setCurrentIndex(), and ~MusicArtistQueryWidget().
MusicArtistMvsQueryWidget* MusicArtistQueryWidget::m_artistMvs protected
Definition at line 296 of file musicartistquerywidget.h.
Referenced by initFourthWidget(), MusicArtistQueryWidget(), resizeWindow(), setCurrentIndex(), and ~MusicArtistQueryWidget().
MusicArtistSimilarQueryWidget* MusicArtistQueryWidget::m_artistSim protected
Definition at line 297 of file musicartistquerywidget.h.
Referenced by initFivethWidget(), MusicArtistQueryWidget(), resizeWindow(), setCurrentIndex(), and ~MusicArtistQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.cpp