TTKMusicplayer: MusicQQDownloadImageRequest Class Reference
MusicQQDownloadImageRequest Class Reference
The class of qq download art background image.
#include <musicqqdownloadimagerequest.h>
Public Slots
void downLoadDataFinished ()
void downLoadUrlFinished ()
Public Slots inherited from MusicDownloadImageRequest
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicQQDownloadImageRequest (const QString &name, const QString &save, QObject *parent=nullptr)
virtual void startToDownload () overridefinal
Public Member Functions inherited from MusicDownloadImageRequest
MusicDownloadImageRequest (const QString &name, const QString &save, QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Member Functions
void downLoadUrl (const QString &id)
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicDownloadImageRequest
int m_index
int m_counter
QString m_artName
QString m_savePath
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of qq download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicqqdownloadimagerequest.h.
Constructor & Destructor Documentation
MusicQQDownloadImageRequest::MusicQQDownloadImageRequest (const QString & name, const QString & save, QObject * parent = nullptr)
Object contsructor provide artist name and save local path.
Definition at line 8 of file musicqqdownloadimagerequest.cpp.
Member Function Documentation
void MusicQQDownloadImageRequest::downLoadDataFinished () slot
Download data from net finished.
Definition at line 33 of file musicqqdownloadimagerequest.cpp.
References MusicAbstractNetwork::downLoadFinished(), downLoadUrl(), MusicAbstractNetwork::m_reply, QJson::Parser::parse(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToDownload().
void MusicQQDownloadImageRequest::downLoadUrl (const QString & id) protected
Download data from net.
Definition at line 110 of file musicqqdownloadimagerequest.cpp.
References BIG_ART_URL, MusicAbstractNetwork::deleteAll(), downLoadUrlFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
Referenced by downLoadDataFinished().
void MusicQQDownloadImageRequest::downLoadUrlFinished () slot
Download data from net finished.
Definition at line 72 of file musicqqdownloadimagerequest.cpp.
References BACKGROUND_DIR_FULL, MusicAbstractNetwork::deleteAll(), MusicObject::DownloadBigBackground, MusicAbstractNetwork::downLoadDataChanged(), MusicDownloadImageRequest::downLoadFinished(), MusicAbstractNetwork::downLoadFinished(), MusicDownloadImageRequest::m_counter, MusicAbstractNetwork::m_reply, MusicDownloadImageRequest::m_savePath, SKN_FILE, MusicDownloadDataRequest::startToDownload(), and TTK_LOGGER_INFO.
Referenced by downLoadUrl().
void MusicQQDownloadImageRequest::startToDownload () final override virtual
Start to download artist picture from net.
Implements MusicDownloadImageRequest.
Definition at line 14 of file musicqqdownloadimagerequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadDataFinished(), MusicDownloadImageRequest::m_artName, MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QQ_SONG_SEARCH_URL, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqdownloadimagerequest.h
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqdownloadimagerequest.cpp