TTKMusicplayer: MusicIdentifySongsThread Class Reference
MusicIdentifySongsThread Class Reference
The class of the song identify query thread.
#include <musicidentifysongsthread.h>
Public Slots
virtual void downLoadFinished () override
void keyDownLoadFinished (const QByteArray &data)
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void getKeyFinished ()
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicIdentifySongsThread (QObject *parent=0)
virtual void deleteAll () override
bool getKey ()
void startToDownload (const QString &path)
const MusicSongIdentifys & getIdentifySongs () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Attributes
MusicSongIdentifys m_songIdentifys
QString m_accessKey
QString m_accessSecret
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Detailed Description
The class of the song identify query thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicidentifysongsthread.h.
Constructor & Destructor Documentation
MusicIdentifySongsThread::MusicIdentifySongsThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 13 of file musicidentifysongsthread.cpp.
References getClassName(), M_LOGGER_INFO, MusicNetworkAbstract::m_manager, and MusicNetworkAbstract::sslErrors().
Member Function Documentation
void MusicIdentifySongsThread::deleteAll () override virtual
Release the network object.
Reimplemented from MusicNetworkAbstract.
Definition at line 28 of file musicidentifysongsthread.cpp.
References MusicNetworkAbstract::m_reply.
Referenced by downLoadFinished().
void MusicIdentifySongsThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 97 of file musicidentifysongsthread.cpp.
References deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicNetworkAbstract::m_reply, MusicSongIdentify::m_singerName, m_songIdentifys, MusicSongIdentify::m_songName, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicIdentifySongsThread::getClassName () static
Get class object name.
Definition at line 23 of file musicidentifysongsthread.cpp.
Referenced by MusicIdentifySongsThread().
const MusicSongIdentifys& MusicIdentifySongsThread::getIdentifySongs () const inline
Get identify songs.
Definition at line 67 of file musicidentifysongsthread.h.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget(), and MusicIdentifySongsWidget::detectedTimeOut().
bool MusicIdentifySongsThread::getKey ()
Get query song id keys.
Definition at line 37 of file musicidentifysongsthread.cpp.
References ACRUA_URL, MusicSemaphoreLoop::exec(), getKeyFinished(), keyDownLoadFinished(), m_accessKey, m_accessSecret, MusicUtils::Algorithm::mdII(), and MusicDownloadSourceThread::startToDownload().
Referenced by MusicIdentifySongsWidget::getKey().
void MusicIdentifySongsThread::getKeyFinished () signal
Get key data from net finished.
Referenced by getKey(), and keyDownLoadFinished().
void MusicIdentifySongsThread::keyDownLoadFinished (const QByteArray & data) slot
Download key data from net finished.
Definition at line 135 of file musicidentifysongsthread.cpp.
References getKeyFinished(), m_accessKey, m_accessSecret, and QJson::Parser::parse().
Referenced by getKey().
void MusicIdentifySongsThread::startToDownload (const QString & path)
To query song by input path.
Definition at line 51 of file musicidentifysongsthread.cpp.
References downLoadFinished(), MusicUtils::Algorithm::hmacSha1(), m_accessKey, m_accessSecret, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::mdII(), QUERY_URL, and MusicNetworkAbstract::setSslConfiguration().
Referenced by MusicIdentifySongsWidget::detectedTimeOut().
Member Data Documentation
QString MusicIdentifySongsThread::m_accessKey protected
Definition at line 87 of file musicidentifysongsthread.h.
Referenced by getKey(), keyDownLoadFinished(), and startToDownload().
QString MusicIdentifySongsThread::m_accessSecret protected
Definition at line 87 of file musicidentifysongsthread.h.
Referenced by getKey(), keyDownLoadFinished(), and startToDownload().
MusicSongIdentifys MusicIdentifySongsThread::m_songIdentifys protected
Definition at line 86 of file musicidentifysongsthread.h.
Referenced by downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicidentifysongsthread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicidentifysongsthread.cpp