TTKMusicPlayer: MusicDownloadBackgroundRequest Class Reference
MusicDownloadBackgroundRequest Class Reference
The class of the download art background image manager request.
#include <musicdownloadbackgroundrequest.h>
Public Slots
void downLoadFinished (const QString &bytes)
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownloadBackgroundRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void startRequest ()
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Member Functions
void findAllPlugins ()
Private Attributes
int m_pluginIndex
QString m_name
QString m_path
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the download art background image manager request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadbackgroundrequest.h.
Constructor & Destructor Documentation
MusicDownloadBackgroundRequest::MusicDownloadBackgroundRequest (const QString & name, const QString & path, QObject * parent = nullptr)
Object contsructor provide artist name and save local path.
Definition at line 6 of file musicdownloadbackgroundrequest.cpp.
Member Function Documentation
void MusicDownloadBackgroundRequest::downLoadFinished (const QString & bytes) slot
Download data from net finished.
Definition at line 21 of file musicdownloadbackgroundrequest.cpp.
References findAllPlugins(), and TTK_DEFAULT_STR.
void MusicDownloadBackgroundRequest::findAllPlugins () private
Find all plugins.
Definition at line 34 of file musicdownloadbackgroundrequest.cpp.
References MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), m_name, m_path, m_pluginIndex, and MusicAbstractDownloadImageRequest::startRequest().
Referenced by downLoadFinished(), and startRequest().
void MusicDownloadBackgroundRequest::startRequest () virtual
Start to download data from net.
Definition at line 15 of file musicdownloadbackgroundrequest.cpp.
References findAllPlugins(), and m_pluginIndex.
Member Data Documentation
QString MusicDownloadBackgroundRequest::m_name private
Definition at line 56 of file musicdownloadbackgroundrequest.h.
Referenced by findAllPlugins().
QString MusicDownloadBackgroundRequest::m_path private
Definition at line 56 of file musicdownloadbackgroundrequest.h.
Referenced by findAllPlugins().
int MusicDownloadBackgroundRequest::m_pluginIndex private
Definition at line 55 of file musicdownloadbackgroundrequest.h.
Referenced by findAllPlugins(), and startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/photo/musicdownloadbackgroundrequest.h
TTKModule/TTKCore/musicNetworkKits/image/photo/musicdownloadbackgroundrequest.cpp