TTKMusicplayer: MusicPlaylist Class Reference
MusicPlaylist Class Reference
The class of the music play list.
#include <musicplaylist.h>
Public Slots
void setCurrentIndex (int index=DEFAULT_NORMAL_LEVEL)
void setCurrentIndex (int toolIndex, const QString &path)
Signals
void currentIndexChanged (int index)
void playbackModeChanged (MusicObject::PlayMode mode)
Public Member Functions
MusicPlaylist (QObject *parent=nullptr)
MusicObject::PlayMode playbackMode () const
void setPlaybackMode (MusicObject::PlayMode mode)
int mapItemIndex (const MusicPlayItem &item) const
int currentIndex () const
MusicPlayItem currentItem () const
QString currentMediaPath () const
MusicPlayItems * mediaList ()
int mediaCount () const
bool isEmpty () const
bool clear ()
int find (int toolIndex, const QString &content, int from=0)
void addMedia (int toolIndex, const QString &content)
void addMedia (int toolIndex, const QStringList &items)
void addMedia (const MusicPlayItem &item)
void addMedia (const MusicPlayItems &items)
void appendMedia (int toolIndex, const QString &content)
void appendMedia (int toolIndex, const QStringList &items)
void appendMedia (const MusicPlayItem &item)
void appendMedia (const MusicPlayItems &items)
bool removeMedia (int pos)
int removeMedia (int toolIndex, const QString &content)
MusicPlayItems * queueMediaList ()
void insertQueueMedia (int toolIndex, const QString &content)
void removeQueueList ()
Protected Attributes
int m_currentIndex
MusicPlayItems m_mediaList
MusicPlayItems m_queueMediaList
MusicObject::PlayMode m_playbackMode
Detailed Description
The class of the music play list.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 60 of file musicplaylist.h.
Constructor & Destructor Documentation
MusicPlaylist::MusicPlaylist (QObject * parent = nullptr) explicit
Definition at line 4 of file musicplaylist.cpp.
References MusicTime::initRandom(), m_currentIndex, m_playbackMode, and MusicObject::PM_PlayOrder.
Member Function Documentation
void MusicPlaylist::addMedia (int toolIndex, const QString & content)
Add music media, not append remember.
Definition at line 84 of file musicplaylist.cpp.
References m_mediaList, and m_queueMediaList.
Referenced by MusicConsoleModule::init(), MusicApplication::readSystemConfigFromFile(), and MusicApplication::setMusicPlayIndex().
void MusicPlaylist::addMedia (int toolIndex, const QStringList & items)
Add music media list, not append remember.
Definition at line 91 of file musicplaylist.cpp.
References m_mediaList, and m_queueMediaList.
void MusicPlaylist::addMedia (const MusicPlayItem & item)
Add music media list, not append remember.
Definition at line 101 of file musicplaylist.cpp.
References m_mediaList, and m_queueMediaList.
void MusicPlaylist::addMedia (const MusicPlayItems & items)
Add music media list, not append remember.
Definition at line 108 of file musicplaylist.cpp.
References m_mediaList, and m_queueMediaList.
void MusicPlaylist::appendMedia (int toolIndex, const QString & content)
Append music medias.
Definition at line 114 of file musicplaylist.cpp.
References m_mediaList.
Referenced by MusicPlayedListPopWidget::append(), and MusicConsoleModule::init().
void MusicPlaylist::appendMedia (int toolIndex, const QStringList & items)
Append music medias.
Definition at line 119 of file musicplaylist.cpp.
References m_mediaList.
void MusicPlaylist::appendMedia (const MusicPlayItem & item)
Append music media.
Definition at line 127 of file musicplaylist.cpp.
References m_mediaList.
void MusicPlaylist::appendMedia (const MusicPlayItems & items)
Append music medias.
Definition at line 132 of file musicplaylist.cpp.
References m_mediaList.
bool MusicPlaylist::clear ()
Clear current medias.
Definition at line 73 of file musicplaylist.cpp.
References isEmpty(), and m_mediaList.
Referenced by MusicApplication::musicPlayIndex(), and MusicApplication::setMusicPlayIndex().
int MusicPlaylist::currentIndex () const
Get current play index.
Definition at line 39 of file musicplaylist.cpp.
References m_currentIndex.
Referenced by MusicApplication::checkMusicListCurrentIndex(), MusicApplication::getCurrentFileName(), MusicApplication::getCurrentFilePath(), MusicPlayer::playNext(), MusicPlayer::playPrevious(), MusicPlayedListPopWidget::setCurrentIndex(), MusicApplication::setDeleteItemAt(), MusicPlayer::update(), and MusicApplicationMPRISPlayer::updateTrackID().
void MusicPlaylist::currentIndexChanged (int index) signal
Current play index changed emit.
Referenced by setCurrentIndex().
MusicPlayItem MusicPlaylist::currentItem () const
Get current play item.
Definition at line 44 of file musicplaylist.cpp.
References m_currentIndex, and m_mediaList.
Referenced by currentMediaPath(), MusicApplication::musicAddSongToLovestListAt(), MusicApplication::musicCurrentPlayLocation(), MusicApplication::musicDownloadContains(), MusicApplication::musicLovestContains(), MusicApplication::setDeleteItemAt(), MusicApplication::showCurrentSong(), and MusicApplication::writeSystemConfigToFile().
QString MusicPlaylist::currentMediaPath () const
Get current play music media path.
Definition at line 53 of file musicplaylist.cpp.
References currentItem(), and MusicPlayItem::m_path.
Referenced by MusicApplication::getCurrentFileName(), MusicApplication::getCurrentFilePath(), MusicPlayer::play(), and MusicConsoleModule::print().
int MusicPlaylist::find (int toolIndex, const QString & content, int from = 0)
Find item by index and content.
Definition at line 79 of file musicplaylist.cpp.
References m_mediaList.
Referenced by removeMedia(), and MusicApplication::setDeleteItemAt().
void MusicPlaylist::insertQueueMedia (int toolIndex, const QString & content)
Insert music media by index and content.
Definition at line 166 of file musicplaylist.cpp.
References m_currentIndex, m_mediaList, and m_queueMediaList.
Referenced by MusicPlayedListPopWidget::insert().
bool MusicPlaylist::isEmpty () const
Check current medias is empty.
Definition at line 68 of file musicplaylist.cpp.
References m_mediaList.
Referenced by MusicApplicationMPRISPlayer::canGoNext(), MusicApplicationMPRISPlayer::canGoPrevious(), MusicApplicationMPRISPlayer::canPause(), MusicApplicationMPRISPlayer::canPlay(), clear(), MusicConsoleModule::init(), MusicApplication::musicAddSongToLovestListAt(), MusicApplication::musicCurrentPlayLocation(), MusicConsoleModule::musicPlayNext(), MusicApplication::musicPlayNext(), MusicConsoleModule::musicPlayPrevious(), MusicApplication::musicPlayPrevious(), MusicConsoleModule::musicStatePlay(), MusicApplication::musicStatePlay(), MusicPlayer::play(), MusicApplication::positionChanged(), MusicPlayedListPopWidget::setDeleteItemAt(), and MusicApplication::setPlaySongChanged().
int MusicPlaylist::mapItemIndex (const MusicPlayItem & item) const
Map item index at container.
Definition at line 23 of file musicplaylist.cpp.
References m_mediaList.
Referenced by setCurrentIndex().
int MusicPlaylist::mediaCount () const
Get current medias count.
Definition at line 63 of file musicplaylist.cpp.
References m_mediaList.
Referenced by MusicConsoleModule::init(), MusicApplication::musicImportSongsPathOuter(), MusicApplication::musicPlayIndex(), MusicPlayer::playNext(), MusicApplication::setDeleteItemAt(), and MusicApplication::setPlaySongChanged().
MusicPlayItems * MusicPlaylist::mediaList ()
Get all music media path.
Definition at line 58 of file musicplaylist.cpp.
References m_mediaList.
Referenced by MusicPlayedListPopWidget::resetToolIndex().
MusicObject::PlayMode MusicPlaylist::playbackMode () const
Get current play mode.
Definition at line 12 of file musicplaylist.cpp.
References m_playbackMode.
Referenced by MusicApplication::getPlayMode(), MusicApplication::musicCreateRightMenu(), MusicConsoleModule::musicPlayNext(), MusicApplication::musicPlayNext(), MusicConsoleModule::musicPlayPrevious(), MusicApplication::musicPlayPrevious(), MusicPlayer::update(), and MusicApplication::writeSystemConfigToFile().
void MusicPlaylist::playbackModeChanged (MusicObject::PlayMode mode) signal
Current play mode changed emit.
Referenced by setPlaybackMode().
MusicPlayItems * MusicPlaylist::queueMediaList ()
Get queue music media path.
Definition at line 161 of file musicplaylist.cpp.
References m_queueMediaList.
Referenced by MusicPlayedListPopWidget::insert().
bool MusicPlaylist::removeMedia (int pos)
Remove music media from current medias by index pos.
Definition at line 137 of file musicplaylist.cpp.
References m_mediaList, and removeQueueList().
Referenced by MusicPlayedListPopWidget::remove(), and MusicPlayedListPopWidget::setDeleteItemAt().
int MusicPlaylist::removeMedia (int toolIndex, const QString & content)
Remove music media from current medias by index pos.
Definition at line 149 of file musicplaylist.cpp.
References find(), m_mediaList, and removeQueueList().
void MusicPlaylist::removeQueueList ()
Remove music all media.
Definition at line 177 of file musicplaylist.cpp.
References m_queueMediaList.
Referenced by MusicPlayedListPopWidget::cellDoubleClicked(), and removeMedia().
void MusicPlaylist::setCurrentIndex (int index = DEFAULT_NORMAL_LEVEL) slot
Set current play index.
Definition at line 182 of file musicplaylist.cpp.
References currentIndexChanged(), DEFAULT_NORMAL_LEVEL, m_currentIndex, m_mediaList, m_playbackMode, m_queueMediaList, MusicPlayItem::m_toolIndex, MusicObject::PM_PlaylistLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, MusicObject::PM_PlayRandom, and MusicTime::random().
Referenced by MusicConsoleModule::init(), MusicApplication::musicPlayedIndex(), MusicApplication::musicPlayIndex(), MusicConsoleModule::musicPlayNext(), MusicApplication::musicPlayNext(), MusicConsoleModule::musicPlayPrevious(), MusicApplication::musicPlayPrevious(), MusicApplication::musicPlaySort(), MusicApplication::musicStateStop(), MusicPlayer::playNext(), MusicPlayer::playPrevious(), MusicApplication::readSystemConfigFromFile(), MusicPlayedListPopWidget::setCurrentIndex(), setCurrentIndex(), MusicPlayedListPopWidget::setDeleteItemAt(), MusicApplication::setDeleteItemAt(), and MusicPlayer::update().
void MusicPlaylist::setCurrentIndex (int toolIndex, const QString & path) slot
Set current play index.
Definition at line 227 of file musicplaylist.cpp.
References mapItemIndex(), and setCurrentIndex().
void MusicPlaylist::setPlaybackMode (MusicObject::PlayMode mode)
Set current play mode.
Definition at line 17 of file musicplaylist.cpp.
References m_playbackMode, and playbackModeChanged().
Referenced by MusicApplication::MusicApplication(), MusicConsoleModule::MusicConsoleModule(), MusicConsoleModule::musicPlaylistLoop(), MusicApplication::musicPlaylistLoop(), MusicConsoleModule::musicPlayOnce(), MusicApplication::musicPlayOnce(), MusicConsoleModule::musicPlayOneLoop(), MusicApplication::musicPlayOneLoop(), MusicConsoleModule::musicPlayOrder(), MusicApplication::musicPlayOrder(), MusicConsoleModule::musicPlayRandom(), MusicApplication::musicPlayRandom(), and MusicApplicationMPRISPlayer::setShuffle().
Member Data Documentation
int MusicPlaylist::m_currentIndex protected
Definition at line 191 of file musicplaylist.h.
Referenced by currentIndex(), currentItem(), insertQueueMedia(), MusicPlaylist(), and setCurrentIndex().
MusicPlayItems MusicPlaylist::m_mediaList protected
Definition at line 192 of file musicplaylist.h.
Referenced by addMedia(), appendMedia(), clear(), currentItem(), find(), insertQueueMedia(), isEmpty(), mapItemIndex(), mediaCount(), mediaList(), removeMedia(), and setCurrentIndex().
MusicObject::PlayMode MusicPlaylist::m_playbackMode protected
Definition at line 194 of file musicplaylist.h.
Referenced by MusicPlaylist(), playbackMode(), setCurrentIndex(), and setPlaybackMode().
MusicPlayItems MusicPlaylist::m_queueMediaList protected
Definition at line 193 of file musicplaylist.h.
Referenced by addMedia(), insertQueueMedia(), queueMediaList(), removeQueueList(), and setCurrentIndex().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicplaylist.h
TTKModule/TTKCore/musicCoreKits/musicplaylist.cpp