TTKMusicplayer: MusicWebMVRadioFoundCategoryPopWidget Class Reference
MusicWebMVRadioFoundCategoryPopWidget Class Reference
The class of the music mv category pop widget.
#include <musicwebmvradiofoundcategorypopwidget.h>
Public Slots
virtual void popupMenu () override
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicWebMVRadioFoundCategoryPopWidget (QWidget *parent=nullptr)
void setCategory (const QString &server, QObject *obj)
void closeMenu ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initWidget ()
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the music mv category pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 65 of file musicwebmvradiofoundcategorypopwidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioFoundCategoryPopWidget::MusicWebMVRadioFoundCategoryPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 59 of file musicwebmvradiofoundcategorypopwidget.cpp.
References initWidget().
Member Function Documentation
void MusicWebMVRadioFoundCategoryPopWidget::closeMenu ()
Close the menu dialog.
Definition at line 96 of file musicwebmvradiofoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
Referenced by MusicWebMVRadioFoundWidget::categoryChanged().
void MusicWebMVRadioFoundCategoryPopWidget::initWidget () protected
Create all widget in layout.
Definition at line 106 of file musicwebmvradiofoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, MusicUIObject::MQSSBackgroundStyle17, MusicUIObject::MQSSBorderStyle04, MusicUIObject::MQSSMenuStyle05, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicWebMVRadioFoundCategoryPopWidget().
void MusicWebMVRadioFoundCategoryPopWidget::popupMenu () override virtual slot
To popup menu.
Definition at line 101 of file musicwebmvradiofoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
void MusicWebMVRadioFoundCategoryPopWidget::setCategory (const QString & server, QObject * obj)
Set current category by input server.
Definition at line 65 of file musicwebmvradiofoundcategorypopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicCategoryConfigManager::MovieList, MusicUIObject::MQSSBackgroundStyle17, MusicUIObject::MQSSScrollBarStyle01, MusicCategoryConfigManager::readCategoryData(), MusicCategoryConfigManager::readConfig(), and MusicWebMVRadioFoundCategoryItem::setCategory().
Referenced by MusicWebMVRadioFoundWidget::createCategoryItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradiofoundcategorypopwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradiofoundcategorypopwidget.cpp