TTKMusicplayer: QJson::Parser Class Reference
QJson::Parser Class Reference
Main class used to convert JSON data to QVariant objects.
#include <parser.h>
Public Member Functions
Parser ()
QVariant parse (QIODevice *io, bool *ok=0)
Read JSON string from the I/O Device and converts it to a QVariant object.
QVariant parse (const QByteArray &jsonData, bool *ok=0)
This is a method provided for convenience.
QString errorString () const
This method returns the error message.
int errorLine () const
This method returns line number where the error occurred.
void allowSpecialNumbers (bool allowSpecialNumbers)
Sets whether special numbers (Infinity, -Infinity, NaN) are allowed as an extension to the standard.
bool specialNumbersAllowed () const
Detailed Description
Main class used to convert JSON data to QVariant objects.
Definition at line 42 of file parser.h.
Constructor & Destructor Documentation
Parser::Parser ()
Definition at line 64 of file parser.cpp.
References MUSIC_INIT_PRIVATE.
Member Function Documentation
void QJson::Parser::allowSpecialNumbers (bool allowSpecialNumbers)
Sets whether special numbers (Infinity, -Infinity, NaN) are allowed as an extension to the standard.
Parameters
allowSpecialNumbers new value of whether special numbers are allowed
See also
specialNumbersAllowed
Definition at line 134 of file parser.cpp.
References MUSIC_D.
int Parser::errorLine () const
This method returns line number where the error occurred.
Returns
the line number where the error occurred
See also
errorString
Definition at line 128 of file parser.cpp.
References MUSIC_D.
QString Parser::errorString () const
This method returns the error message.
Returns
a QString object containing the error message of the last parse operation
See also
errorLine
Definition at line 122 of file parser.cpp.
References MUSIC_D.
Referenced by QJson::ParserRunnable::run().
QVariant Parser::parse (QIODevice * io, bool * ok = 0)
Read JSON string from the I/O Device and converts it to a QVariant object.
Parameters
io Input output device
ok if a conversion error occurs, *ok is set to false; otherwise *ok is set to true.
Returns
a QVariant object generated from the JSON string
Definition at line 69 of file parser.cpp.
References MUSIC_D.
Referenced by MusicKWBackgroundThread::downLoadDataFinished(), MusicQQBackgroundThread::downLoadDataFinished(), MusicKGDiscoverListThread::downLoadFinished(), MusicMGDiscoverListThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicBDDiscoverListThread::downLoadFinished(), MusicQQDiscoverListThread::downLoadFinished(), MusicKWDiscoverListThread::downLoadFinished(), MusicWSDiscoverListThread::downLoadFinished(), MusicKWSongSuggestThread::downLoadFinished(), MusicKWTextDownLoadThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicBDSongSuggestThread::downLoadFinished(), MusicMGSongSuggestThread::downLoadFinished(), MusicXMSongSuggestThread::downLoadFinished(), MusicMGTextDownLoadThread::downLoadFinished(), MusicKGSongSuggestThread::downLoadFinished(), MusicQQSongSuggestThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicWSSongSuggestThread::downLoadFinished(), MusicWYDiscoverListThread::downLoadFinished(), MusicXMDiscoverListThread::downLoadFinished(), MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicWYSongSuggestThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicMGSongCommentsThread::downLoadFinished(), MusicKGSongCommentsThread::downLoadFinished(), MusicBDSongCommentsThread::downLoadFinished(), MusicQQSongCommentsThread::downLoadFinished(), MusicKWSongCommentsThread::downLoadFinished(), MusicWSSongCommentsThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicWYSongCommentsThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicXMSongCommentsThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownloadCounterPVThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicRadioPlayListThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryWSPlaylistThread::downLoadFinished(), MusicRadioChannelThread::downLoadFinished(), MusicRadioSongsThread::downLoadFinished(), MusicSourceUpdateThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicIdentifySongsThread::downLoadFinished(), MusicTranslationThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicBDPlaylistCommentsThread::downLoadFinished(), MusicMGPlaylistCommentsThread::downLoadFinished(), MusicKGPlaylistCommentsThread::downLoadFinished(), MusicQQPlaylistCommentsThread::downLoadFinished(), MusicKWPlaylistCommentsThread::downLoadFinished(), MusicWYPlaylistCommentsThread::downLoadFinished(), MusicXMPlaylistCommentsThread::downLoadFinished(), QNPutRet::fromJSON(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryWSArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryWSPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetailsFinished(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQQInterface::getMusicKey(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryMGPlaylistThread::getPlaylistInfo(), MusicWSDiscoverListThread::getUpdateTime(), MusicDownLoadQueryWSToplistThread::getUpdateTime(), MusicCloudSharedSongTableWidget::keyDownLoadFinished(), MusicIdentifySongsThread::keyDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::pageDownLoadFinished(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryMGMovieThread::pageDownLoadFinished(), parse(), MusicDownLoadMGInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAlbumInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadWSInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadBDInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttribute(), MusicDownLoadWYInterface::readFromMusicSongAttributeNew(), MusicDownLoadXMInterface::readFromMusicSongLrc(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), MusicDownLoadKWInterface::readFromMusicSongPic(), QNSimpleListData::receiveDataFromServer(), QJson::ParserRunnable::run(), MusicDownLoadQueryKGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryWYAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryMGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryXMAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKWAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryBDAlbumThread::singleDownLoadFinished(), and MusicDownLoadQueryWYMovieThread::startMVListQuery().
QVariant Parser::parse (const QByteArray & jsonData, bool * ok = 0)
This is a method provided for convenience.
Parameters
jsonData data containing the JSON object representation
ok if a conversion error occurs, *ok is set to false; otherwise *ok is set to true.
Returns
a QVariant object generated from the JSON string
See also
errorString
errorLine
Definition at line 114 of file parser.cpp.
References parse().
bool Parser::specialNumbersAllowed () const
Returns
whether special numbers (Infinity, -Infinity, NaN) are allowed
See also
allowSpecialNumbers
Definition at line 140 of file parser.cpp.
References MUSIC_D.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/parser.h
TTKThirdParty/TTKExtras/qjson/parser.cpp