TTKMusicplayer: MusicDownloadBatchWidget Class Reference
MusicDownloadBatchWidget Class Reference
The class of the download batch widget.
#include <musicdownloadbatchwidget.h>
Public Slots
void show ()
void startToDownload ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicDownloadBatchWidget (QWidget *parent=nullptr)
~MusicDownloadBatchWidget ()
void setSongName (const MusicObject::MusicSongInformations &infos, MusicAbstractQueryRequest::QueryType type)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicDownloadBatchWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the download batch widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 138 of file musicdownloadbatchwidget.h.
Constructor & Destructor Documentation
MusicDownloadBatchWidget::MusicDownloadBatchWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 349 of file musicdownloadbatchwidget.cpp.
References MusicUtils::Widget::generateComboBoxFormat(), m_ui, MusicUIObject::MQSSComboBoxStyle02, MusicUIObject::MQSSItemView01, MusicUIObject::MQSSPushButtonStyle06, MusicUIObject::MQSSToolButtonStyle04, and startToDownload().
MusicDownloadBatchWidget::~MusicDownloadBatchWidget ()
Definition at line 378 of file musicdownloadbatchwidget.cpp.
References G_SINGLE_MANAGER_PTR, and m_ui.
Member Function Documentation
void MusicDownloadBatchWidget::setSongName (const MusicObject::MusicSongInformations & infos, MusicAbstractQueryRequest::QueryType type)
Set current name to search and download musics.
Definition at line 384 of file musicdownloadbatchwidget.cpp.
References m_ui.
Referenced by MusicSongSearchOnlineWidget::buttonClicked(), and MusicItemQueryTableWidget::downloadBatchData().
void MusicDownloadBatchWidget::show () slot
Override show function.
Definition at line 393 of file musicdownloadbatchwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
void MusicDownloadBatchWidget::startToDownload () slot
Start to download music data.
Definition at line 399 of file musicdownloadbatchwidget.cpp.
References m_ui.
Referenced by MusicDownloadBatchWidget().
Member Data Documentation
Ui::MusicDownloadBatchWidget* MusicDownloadBatchWidget::m_ui protected
Definition at line 165 of file musicdownloadbatchwidget.h.
Referenced by MusicDownloadBatchWidget(), setSongName(), show(), startToDownload(), and ~MusicDownloadBatchWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadbatchwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadbatchwidget.cpp