TTKMusicplayer: MusicDownLoadSimilarThread Class Reference
MusicDownLoadSimilarThread Class Reference abstract
The class to query similar download data from net.
#include <musicdownloadsimilarthread.h>
Signals
void createSimilarItem (const MusicResultsItem &item)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDownLoadSimilarThread (QObject *parent=nullptr)
virtual void startToSearch (const QString &text)=0
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=nullptr)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Additional Inherited Members
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class to query similar download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadsimilarthread.h.
Constructor & Destructor Documentation
MusicDownLoadSimilarThread::MusicDownLoadSimilarThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdownloadsimilarthread.cpp.
Member Function Documentation
void MusicDownLoadSimilarThread::createSimilarItem (const MusicResultsItem & item) signal
Create the current similar item.
Referenced by MusicBDArtistSimilarThread::downLoadFinished(), MusicXMArtistSimilarThread::downLoadFinished(), MusicKGArtistSimilarThread::downLoadFinished(), MusicQQArtistSimilarThread::downLoadFinished(), MusicKWArtistSimilarThread::downLoadFinished(), and MusicWYArtistSimilarThread::downLoadFinished().
virtual void MusicDownLoadSimilarThread::startToSearch (const QString & text) pure virtual
Start to Search data from name. Subclass should implement this function.
Implemented in MusicWYArtistSimilarThread, MusicBDArtistSimilarThread, MusicKGArtistSimilarThread, MusicKWArtistSimilarThread, MusicQQArtistSimilarThread, and MusicXMArtistSimilarThread.
Referenced by MusicArtistSimilarFoundWidget::setSongName(), and MusicArtistSimilarFoundWidget::setSongNameById().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadsimilarthread.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadsimilarthread.cpp