TTKMusicplayer: MusicSongCheckToolsRenameCore Class Reference
MusicSongCheckToolsRenameCore Class Reference
The class of the song check tools rename thread.
#include <musicsongchecktoolscore.h>
Public Slots
void start ()
virtual void run () override
Signals
void finished (const MusicSongCheckToolsRenames &items)
Public Member Functions
MusicSongCheckToolsRenameCore (QObject *parent=0)
~MusicSongCheckToolsRenameCore ()
void setMode (MusicObject::MusicSongCheckToolsMode mode)
MusicObject::MusicSongCheckToolsMode getMode () const
void setItemLists (const MusicObject::MIntList &items)
void setRenameSongs (MusicSongs *songs)
void stopAndQuitThread ()
Static Public Member Functions
static QString getClassName ()
Protected Attributes
bool m_run
MusicSongs * m_songItems
MusicObject::MIntList m_itemIDs
MusicSongCheckToolsRenames m_datas
MusicObject::MusicSongCheckToolsMode m_operateMode
Detailed Description
The class of the song check tools rename thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 11 of file musicsongchecktoolscore.h.
Constructor & Destructor Documentation
MusicSongCheckToolsRenameCore::MusicSongCheckToolsRenameCore (QObject * parent = 0) explicit
Object contsructor.
Definition at line 4 of file musicsongchecktoolscore.cpp.
References MusicObject::Check, m_operateMode, m_run, and m_songItems.
MusicSongCheckToolsRenameCore::~MusicSongCheckToolsRenameCore ()
Definition at line 12 of file musicsongchecktoolscore.cpp.
References stopAndQuitThread().
Member Function Documentation
void MusicSongCheckToolsRenameCore::finished (const MusicSongCheckToolsRenames & items) signal
Rename check finished.
Referenced by run().
QString MusicSongCheckToolsRenameCore::getClassName () static
Get class object name.
Definition at line 17 of file musicsongchecktoolscore.cpp.
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsRenameCore::getMode () const inline
Get music song check tool mode.
Definition at line 34 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsWidget::renameCheckFinished().
void MusicSongCheckToolsRenameCore::run () override virtual slot
Thread run now.
Definition at line 43 of file musicsongchecktoolscore.cpp.
References MusicObject::Check, finished(), MusicSongTag::getArtist(), MusicSong::getMusicArtistBack(), MusicSong::getMusicArtistFront(), MusicSong::getMusicName(), MusicSong::getMusicPath(), MusicSongTag::getTitle(), m_datas, MusicSongCheckToolsRename::m_filePath, m_itemIDs, m_operateMode, MusicSongCheckToolsRename::m_RecommendName, m_run, m_songItems, and MusicSongTag::read().
void MusicSongCheckToolsRenameCore::setItemLists (const MusicObject::MIntList & items) inline
Set item lists.
Definition at line 38 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsWidget::renameButtonCheckClicked().
void MusicSongCheckToolsRenameCore::setMode (MusicObject::MusicSongCheckToolsMode mode) inline
Set music song check tool mode.
Definition at line 30 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsWidget::renameButtonCheckClicked(), and MusicSongCheckToolsWidget::renameReCheckButtonClicked().
void MusicSongCheckToolsRenameCore::setRenameSongs (MusicSongs * songs)
Set find file path by given path.
Definition at line 22 of file musicsongchecktoolscore.cpp.
References m_songItems.
Referenced by MusicSongCheckToolsWidget::renameReCheckButtonClicked().
void MusicSongCheckToolsRenameCore::start () slot
Strat thread now.
Definition at line 37 of file musicsongchecktoolscore.cpp.
References m_run.
Referenced by MusicSongCheckToolsWidget::renameButtonCheckClicked(), and MusicSongCheckToolsWidget::renameReCheckButtonClicked().
void MusicSongCheckToolsRenameCore::stopAndQuitThread ()
Stop and quit current thread.
Definition at line 27 of file musicsongchecktoolscore.cpp.
References m_run.
Referenced by MusicSongCheckToolsWidget::renameButtonCheckClicked(), MusicSongCheckToolsWidget::renameReCheckButtonClicked(), and ~MusicSongCheckToolsRenameCore().
Member Data Documentation
MusicSongCheckToolsRenames MusicSongCheckToolsRenameCore::m_datas protected
Definition at line 69 of file musicsongchecktoolscore.h.
Referenced by run().
MusicObject::MIntList MusicSongCheckToolsRenameCore::m_itemIDs protected
Definition at line 68 of file musicsongchecktoolscore.h.
Referenced by run().
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsRenameCore::m_operateMode protected
Definition at line 70 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsRenameCore(), and run().
bool MusicSongCheckToolsRenameCore::m_run protected
Definition at line 66 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsRenameCore(), run(), start(), and stopAndQuitThread().
MusicSongs* MusicSongCheckToolsRenameCore::m_songItems protected
Definition at line 67 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsRenameCore(), run(), and setRenameSongs().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolscore.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolscore.cpp