TTKMusicplayer: PinyinHelper Class Reference
PinyinHelper Class Reference
The class of the chinese characters to pinyin.
#include <pinyinhelper.h>
Public Types
enum Format { WITH_TONE_MARK = 0, WITH_TONE_NUMBER, WITHOUT_TONE }
Public Member Functions
PinyinHelper ()
QStringList convertToPinyinArray (const QChar &c)
Converting a single Chinese character into a tone format.
QString convertToPinyinString (const QString &s, const QString &separator, Format pinyinFormat)
Convert the string into the corresponding format of the Pinyin.
QString convertToPinyinString (const QString &str, const QString &separator)
Converts a string into a tone format.
bool hasMultiPinyin (char c)
A judge whether the Chinese Chinese characters.
Private Member Functions
QStringList formatPinyin (QString pinyinString, Format pinyinFormat)
The phonetic alphabet is formatted into the corresponding format.
QStringList convertToPinyinArray (const QChar &c, Format pinyinFormat)
Converting a single Chinese character into the corresponding format.
Detailed Description
The class of the chinese characters to pinyin.
Author
jiangXiaoBai 24999.nosp@m.7190.nosp@m.6@qq..nosp@m.com
Definition at line 29 of file pinyinhelper.h.
Member Enumeration Documentation
enum PinyinHelper::Format
Enumerator
WITH_TONE_MARK
With tone
WITH_TONE_NUMBER
The number represents the tone
WITHOUT_TONE
Without tone
Definition at line 32 of file pinyinhelper.h.
Constructor & Destructor Documentation
PinyinHelper::PinyinHelper ()
Object contsructor.
Definition at line 118 of file pinyinhelper.cpp.
References MUSIC_INIT_PRIVATE.
Member Function Documentation
QStringList PinyinHelper::convertToPinyinArray (const QChar & c)
Converting a single Chinese character into a tone format.
Parameters
c Needs to be converted into phonetic characters
Returns
String Pinyin
Definition at line 123 of file pinyinhelper.cpp.
References WITH_TONE_MARK.
Referenced by convertToPinyinString(), and hasMultiPinyin().
QStringList PinyinHelper::convertToPinyinArray (const QChar & c, Format pinyinFormat) private
Converting a single Chinese character into the corresponding format.
Parameters
c Needs to be converted into phonetic characters
pinyinFormat
Returns
Pinyin of Chinese characters
Definition at line 218 of file pinyinhelper.cpp.
References formatPinyin(), and MUSIC_D.
QString PinyinHelper::convertToPinyinString (const QString & s, const QString & separator, Format pinyinFormat)
Convert the string into the corresponding format of the Pinyin.
Parameters
str String that needs to be converted
separator Phonetic separator
pinyinFormat
Returns
String Pinyin
Definition at line 128 of file pinyinhelper.cpp.
References convertToPinyinArray(), formatPinyin(), and MUSIC_D.
Referenced by convertToPinyinString().
QString PinyinHelper::convertToPinyinString (const QString & str, const QString & separator)
Converts a string into a tone format.
Parameters
str String that needs to be converted
separator Phonetic separator
Returns
Pinyin with tone after conversion
Definition at line 191 of file pinyinhelper.cpp.
References convertToPinyinString(), and WITH_TONE_MARK.
QStringList PinyinHelper::formatPinyin (QString pinyinString, Format pinyinFormat) private
The phonetic alphabet is formatted into the corresponding format.
Parameters
pinyinString Pinyin with tone
pinyinFormat
Returns
Pinyin after format conversion
Definition at line 206 of file pinyinhelper.cpp.
References MUSIC_D, WITH_TONE_MARK, WITH_TONE_NUMBER, and WITHOUT_TONE.
Referenced by convertToPinyinArray(), and convertToPinyinString().
bool PinyinHelper::hasMultiPinyin (char c)
A judge whether the Chinese Chinese characters.
Parameters
c chinese characters
Returns
Judge the result, is the Chinese character returns true, otherwise returns false
Definition at line 196 of file pinyinhelper.cpp.
References convertToPinyinArray().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qhz2py/pinyinhelper.h
TTKThirdParty/TTKExtras/qhz2py/pinyinhelper.cpp