TTKMusicplayer: MusicKGQueryMovieRequest Class Reference
MusicKGQueryMovieRequest Class Reference
The class of kugou mv query download data from net.
#include <musickgquerymovierequest.h>
Public Slots
virtual void downLoadFinished () override
void pageDownLoadFinished ()
void singleDownLoadFinished ()
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKGQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToPage (int offset) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicQueryMovieRequest
MusicQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &movie)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
void setQueryQuality (const QString &qual)
QString getQueryQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getQueryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
int getPageSize () const
int getTotalSize () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
void readFromMusicMVAttribute (MusicObject::MusicSongInformation *info, bool more)
void readFromMusicMVInfo (MusicObject::MusicSongInformation *info)
void readFromMusicMVAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryMovieRequest
void createMovieInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 getUrlFileSize (const QString &url)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of kugou mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musickgquerymovierequest.h.
Constructor & Destructor Documentation
MusicKGQueryMovieRequest::MusicKGQueryMovieRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musickgquerymovierequest.cpp.
References MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_KG_INTERFACE.
Member Function Documentation
void MusicKGQueryMovieRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 62 of file musickgquerymovierequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), readFromMusicMVAttribute(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicKGQueryMovieRequest::pageDownLoadFinished () slot
Download page data from net finished.
Definition at line 120 of file musickgquerymovierequest.cpp.
References MusicQueryMovieRequest::createMovieInfoItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicAbstractNetwork::m_reply, MusicPagingRequest::m_totalSize, MusicResultsItem::m_updateTime, QJson::Parser::parse(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToPage().
void MusicKGQueryMovieRequest::readFromMusicMVAttribute (MusicObject::MusicSongInformation * info, bool more) protected
Read mv tags(size) from query results.
Definition at line 193 of file musickgquerymovierequest.cpp.
References KG_MOVIE_INFO_URL, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicObject::syncNetworkQueryForGet().
Referenced by downLoadFinished(), and singleDownLoadFinished().
void MusicKGQueryMovieRequest::readFromMusicMVAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key) protected
Read mv info attribute from query results.
Definition at line 277 of file musickgquerymovierequest.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongInformation::m_duration, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_250, MB_500, MB_750, MusicTime::msecTime2LabelJustified(), MusicUtils::Number::sizeByte2Label(), and MusicUtils::String::stringSplitToken().
void MusicKGQueryMovieRequest::readFromMusicMVInfo (MusicObject::MusicSongInformation * info) protected
Read mv infos from query results.
Definition at line 251 of file musickgquerymovierequest.cpp.
References KG_MOVIE_URL, MusicObject::MusicSongInformation::m_songId, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), and MusicObject::syncNetworkQueryForGet().
Referenced by singleDownLoadFinished().
void MusicKGQueryMovieRequest::singleDownLoadFinished () slot
Download single data from net finished.
Definition at line 164 of file musickgquerymovierequest.cpp.
References MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractQueryRequest::m_queryText, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), readFromMusicMVAttribute(), readFromMusicMVInfo(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSingleSearch().
void MusicKGQueryMovieRequest::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicPagingRequest.
Definition at line 31 of file musickgquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), KG_ARTIST_MOVIE_URL, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryText, MusicAbstractNetwork::m_reply, MusicPagingRequest::m_totalSize, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, pageDownLoadFinished(), MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
void MusicKGQueryMovieRequest::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicQueryMovieRequest.
Definition at line 10 of file musickgquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KG_SONG_SEARCH_URL, MusicAbstractQueryRequest::m_currentType, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryText, MusicAbstractNetwork::m_reply, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
void MusicKGQueryMovieRequest::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 52 of file musickgquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractQueryRequest::m_queryText, MT_MS, singleDownLoadFinished(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgquerymovierequest.h
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgquerymovierequest.cpp