TTKMusicplayer: MusicDownLoadQQInterface Class Reference
MusicDownLoadQQInterface Class Reference
The class to qq query download interface.
#include <musicdownloadqqinterface.h>
Public Member Functions
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributePlus (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributePlus (MusicObject::MusicSongInformation *info, const QVariantMap &key)
QString getMusicKey (const QString &time)
Detailed Description
The class to qq query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 74 of file musicdownloadqqinterface.h.
Member Function Documentation
QString MusicDownLoadQQInterface::getMusicKey (const QString & time)
Get music key.
Definition at line 236 of file musicdownloadqqinterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), QQ_SONG_KEY_URL, QQ_UA_URL_1, and MusicUtils::Codec::toUtf8().
Referenced by readFromMusicSongAttribute(), and readFromMusicSongAttributePlus().
void MusicDownLoadQQInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate)
QJson import.
Read tags(size) from query results.
Definition at line 15 of file musicdownloadqqinterface.cpp.
References getMusicKey(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), QQ_SONG_128_URL, QQ_SONG_192_URL, QQ_SONG_320_URL, QQ_SONG_APE_URL, QQ_SONG_FLAC_URL, MusicUtils::Number::size2Label(), and MusicTime::timeSRand().
Referenced by MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), and readFromMusicSongAttribute().
void MusicDownLoadQQInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 107 of file musicdownloadqqinterface.cpp.
References MB_1000, MB_128, MB_192, MB_320, MB_750, and readFromMusicSongAttribute().
void MusicDownLoadQQInterface::readFromMusicSongAttributePlus (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate)
Read tags(size) from query results.
Definition at line 140 of file musicdownloadqqinterface.cpp.
References getMusicKey(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), QQ_SONG_128_URL, QQ_SONG_192_URL, QQ_SONG_320_URL, QQ_SONG_APE_URL, QQ_SONG_FLAC_URL, MusicUtils::Number::size2Label(), and MusicTime::timeSRand().
Referenced by MusicDownLoadQueryQQRecommendThread::downLoadFinished(), readFromMusicSongAttributePlus(), and MusicDownLoadQueryQQThread::singleDownLoadFinished().
void MusicDownLoadQQInterface::readFromMusicSongAttributePlus (MusicObject::MusicSongInformation * info, const QVariantMap & key)
Read tags(size) from query results.
Definition at line 227 of file musicdownloadqqinterface.cpp.
References MB_1000, MB_128, MB_192, MB_320, MB_750, and readFromMusicSongAttributePlus().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/qq/musicdownloadqqinterface.h
TTKModule/TTKCore/musicNetworkKits/qq/musicdownloadqqinterface.cpp