TTKMusicplayer: MusicExtractWrap Class Reference
MusicExtractWrap Class Reference
The class of the extract data wrap.
#include <musicextractwrap.h>
Static Public Member Functions
static bool outputThunderSkin (QPixmap &image, const QString &input)
static bool outputBinary (const QString &input)
static bool outputBinary (const QString &input, const QString &output)
static bool outputBinary (const QString &input, const QString &output, QStringList &path)
static bool outputSkin (MusicBackgroundImage *image, const QString &input)
static bool inputSkin (MusicBackgroundImage *image, const QString &output)
static bool outputData (QByteArray &data, const QString &input)
static bool inputData (const QByteArray &data, const QString &output)
Detailed Description
The class of the extract data wrap.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicextractwrap.h.
Member Function Documentation
bool MusicExtractWrap::inputData (const QByteArray & data, const QString & output) static
Transfer data to file.
Definition at line 334 of file musicextractwrap.cpp.
References Z_DEFLATED, zipClose(), zipCloseFileInZip(), zipOpen64(), zipOpenNewFileInZip(), and zipWriteInFileInZip().
bool MusicExtractWrap::inputSkin (MusicBackgroundImage * image, const QString & output) static
Transfer image data to file.
Definition at line 244 of file musicextractwrap.cpp.
References MusicUtils::Image::getPixmapData(), MusicBackgroundImage::m_item, MusicBackgroundImage::m_pix, MUSIC_IMAGE_FILE, SKN_FILE, MusicAbstractXml::toByteArray(), MusicUtils::Codec::toLocal8Bit(), MusicSkinConfigManager::writeSkinData(), XML_FILE, Z_DEFLATED, zipClose(), zipCloseFileInZip(), zipOpen64(), zipOpenNewFileInZip(), and zipWriteInFileInZip().
Referenced by MusicBackgroundSkinDialog::cpoyFileToLocal(), MusicBackgroundSkinDialog::listWidgetItemClicked(), and ToolsSkin::writeClicked().
bool MusicExtractWrap::outputBinary (const QString & input) static
Transfer file to normal data.
Definition at line 78 of file musicextractwrap.cpp.
Referenced by MusicApplication::musicImportSongsPath(), and outputBinary().
bool MusicExtractWrap::outputBinary (const QString & input, const QString & output) static
Transfer file to normal data.
Definition at line 83 of file musicextractwrap.cpp.
References outputBinary().
bool MusicExtractWrap::outputBinary (const QString & input, const QString & output, QStringList & path) static
Transfer file to normal data.
Definition at line 89 of file musicextractwrap.cpp.
References MH_KB, unz_global_info64_s::number_entry, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
bool MusicExtractWrap::outputData (QByteArray & data, const QString & input) static
Transfer file to data.
Definition at line 277 of file musicextractwrap.cpp.
References MH_KB, unz_global_info64_s::number_entry, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
bool MusicExtractWrap::outputSkin (MusicBackgroundImage * image, const QString & input) static
Transfer file to image data.
Definition at line 159 of file musicextractwrap.cpp.
References MusicAbstractXml::fromByteArray(), MusicBackgroundImage::m_item, MusicBackgroundImage::m_pix, MH_KB, unz_global_info64_s::number_entry, MusicSkinConfigManager::readSkinData(), SKN_FILE, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), WIN_NAME_MAX_LENGTH, and XML_FILE.
Referenced by MusicLrcPosterItemWidget::MusicLrcPosterItemWidget(), ToolsSkin::readClicked(), MusicAbstractMoveDialog::setBackgroundPixmap(), MusicAbstractMoveWidget::setBackgroundPixmap(), MusicBackgroundSkinDialog::setBackgroundUrl(), MusicProgressWidget::show(), MusicDesktopWallpaperThread::timeout(), MusicBackgroundPaletteWidget::updateBackground(), and MusicBackgroundListItem::updatePixImage().
bool MusicExtractWrap::outputThunderSkin (QPixmap & image, const QString & input) static
Transfer file to image data.
Definition at line 16 of file musicextractwrap.cpp.
References MH_KB, unz_global_info64_s::number_entry, UNZ_OK, unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo64(), unzGetGlobalInfo64(), unzGoToNextFile(), unzOpen64(), unzOpenCurrentFile(), unzReadCurrentFile(), and WIN_NAME_MAX_LENGTH.
Referenced by MusicBackgroundThunderWidget::outputRemoteSkin().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicextractwrap.h
TTKModule/TTKCore/musicCoreKits/musicextractwrap.cpp