TTKMusicPlayer: MusicMPRISPlayerCore Class Reference
MusicMPRISPlayerCore Class Reference
The class of the app mpris player object.
#include <musicmprisplayer.h>
Public Slots
void Next ()
void Previous ()
void OpenUri (const QString &uri)
void Pause ()
void Play ()
void PlayPause ()
void Stop ()
void Seek (qlonglong offset)
void SetPosition (const QDBusObjectPath &trackId, qlonglong position)
Signals
void Seeked (qlonglong position)
Public Member Functions
MusicMPRISPlayerCore (QObject *parent=nullptr)
bool canControl () const
bool canGoNext () const
bool canGoPrevious () const
bool canPause () const
bool canPlay () const
bool canSeek () const
QString loopStatus () const
void setLoopStatus (const QString &value)
double maximumRate () const
QVariantMap metadata () const
double minimumRate () const
QString playbackStatus () const
qlonglong position () const
double rate () const
void setRate (double value)
bool shuffle () const
void setShuffle (bool value)
double volume () const
void setVolume (double value)
Properties
bool CanControl
bool CanGoNext
bool CanGoPrevious
bool CanPause
bool CanPlay
bool CanSeek
QString LoopStatus
double MaximumRate
QVariantMap Metadata
double MinimumRate
QString PlaybackStatus
qlonglong Position
double Rate
bool Shuffle
double Volume
Private Slots
void trackInfoChanged ()
void stateChanged ()
void volumeChanged ()
void elapsedChanged (qint64 elapsed)
void playbackModeChanged ()
Private Member Functions
void updateTrackID ()
void syncProperties ()
void sendProperties ()
Private Attributes
int m_prevTrack
qint64 m_prevPos
SoundCore * m_core
MusicApplication * m_application
QDBusObjectPath m_trackID
TTKVariantMap m_properties
Detailed Description
The class of the app mpris player object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 92 of file musicmprisplayer.h.
Constructor & Destructor Documentation
MusicMPRISPlayerCore::MusicMPRISPlayerCore (QObject * parent = nullptr)
Definition at line 100 of file musicmprisplayer.cpp.
References elapsedChanged(), TTKObject::initRandom(), MusicApplication::instance(), SoundCore::instance(), m_application, m_core, MusicApplication::m_playlist, m_prevPos, m_prevTrack, playbackModeChanged(), stateChanged(), syncProperties(), trackInfoChanged(), updateTrackID(), and volumeChanged().
Member Function Documentation
bool MusicMPRISPlayerCore::canControl () const
Definition at line 120 of file musicmprisplayer.cpp.
bool MusicMPRISPlayerCore::canGoNext () const
Definition at line 125 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), m_application, and MusicApplication::m_playlist.
Referenced by syncProperties().
bool MusicMPRISPlayerCore::canGoPrevious () const
Definition at line 130 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), m_application, and MusicApplication::m_playlist.
Referenced by syncProperties().
bool MusicMPRISPlayerCore::canPause () const
Definition at line 135 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), m_application, and MusicApplication::m_playlist.
Referenced by syncProperties().
bool MusicMPRISPlayerCore::canPlay () const
Definition at line 139 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), m_application, and MusicApplication::m_playlist.
Referenced by syncProperties().
bool MusicMPRISPlayerCore::canSeek () const
Definition at line 144 of file musicmprisplayer.cpp.
References SoundCore::duration(), and m_core.
Referenced by syncProperties().
void MusicMPRISPlayerCore::elapsedChanged (qint64 elapsed) private slot
Tracks elapesed time.
Definition at line 386 of file musicmprisplayer.cpp.
References m_prevPos, and Seeked().
Referenced by MusicMPRISPlayerCore().
QString MusicMPRISPlayerCore::loopStatus () const
Definition at line 149 of file musicmprisplayer.cpp.
References MusicObject::ListLoop, m_application, MusicObject::OneLoop, and MusicApplication::playMode().
Referenced by syncProperties().
double MusicMPRISPlayerCore::maximumRate () const
Definition at line 175 of file musicmprisplayer.cpp.
Referenced by syncProperties().
QVariantMap MusicMPRISPlayerCore::metadata () const
Definition at line 180 of file musicmprisplayer.cpp.
References Qmmp::ALBUM, Qmmp::ALBUMARTIST, Qmmp::ARTIST, Qmmp::COMMENT, Qmmp::COMPOSER, Qmmp::DISCNUMBER, SoundCore::duration(), Qmmp::GENRE, MetaDataManager::getCoverPath(), MetaDataManager::instance(), m_core, m_trackID, TrackInfo::path(), SoundCore::path(), Qmmp::TITLE, Qmmp::TRACK, SoundCore::trackInfo(), TTK_SEPARATOR, TrackInfo::value(), and Qmmp::YEAR.
Referenced by syncProperties().
double MusicMPRISPlayerCore::minimumRate () const
Definition at line 250 of file musicmprisplayer.cpp.
Referenced by syncProperties().
void MusicMPRISPlayerCore::Next () slot
Definition at line 308 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicPlayNext().
void MusicMPRISPlayerCore::OpenUri (const QString & uri) slot
Definition at line 313 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicImportSongsPathOutside().
void MusicMPRISPlayerCore::Pause () slot
Definition at line 328 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicStatePlay().
void MusicMPRISPlayerCore::Play () slot
Definition at line 333 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicStatePlay().
void MusicMPRISPlayerCore::playbackModeChanged () private slot
Current play mode changed.
Definition at line 395 of file musicmprisplayer.cpp.
References sendProperties().
Referenced by MusicMPRISPlayerCore().
QString MusicMPRISPlayerCore::playbackStatus () const
Definition at line 255 of file musicmprisplayer.cpp.
References m_core, Qmmp::Paused, Qmmp::Playing, and SoundCore::state().
Referenced by syncProperties().
void MusicMPRISPlayerCore::PlayPause () slot
Definition at line 338 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicStatePlay().
qlonglong MusicMPRISPlayerCore::position () const
Definition at line 268 of file musicmprisplayer.cpp.
References SoundCore::elapsed(), and m_core.
void MusicMPRISPlayerCore::Previous () slot
Definition at line 303 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicPlayPrevious().
double MusicMPRISPlayerCore::rate () const
Definition at line 273 of file musicmprisplayer.cpp.
Referenced by syncProperties().
void MusicMPRISPlayerCore::Seek (qlonglong offset) slot
Definition at line 348 of file musicmprisplayer.cpp.
References SoundCore::elapsed(), m_core, and SoundCore::seek().
void MusicMPRISPlayerCore::Seeked (qlonglong position) signal
Referenced by elapsedChanged().
void MusicMPRISPlayerCore::sendProperties () private
Definition at line 426 of file musicmprisplayer.cpp.
References m_properties, and syncProperties().
Referenced by playbackModeChanged(), stateChanged(), trackInfoChanged(), and volumeChanged().
void MusicMPRISPlayerCore::setLoopStatus (const QString & value)
Definition at line 159 of file musicmprisplayer.cpp.
References m_application, MusicApplication::musicPlaylistLoop(), MusicApplication::musicPlayOneLoop(), and MusicApplication::musicPlayOrder().
void MusicMPRISPlayerCore::SetPosition (const QDBusObjectPath & trackId, qlonglong position) slot
Definition at line 353 of file musicmprisplayer.cpp.
References m_core, m_trackID, SoundCore::seek(), and TTK_WARN_STREAM.
void MusicMPRISPlayerCore::setRate (double value)
Definition at line 278 of file musicmprisplayer.cpp.
void MusicMPRISPlayerCore::setShuffle (bool value)
Definition at line 288 of file musicmprisplayer.cpp.
References m_application, MusicApplication::m_playlist, MusicObject::Order, MusicObject::Random, and MusicPlaylist::setPlaybackMode().
void MusicMPRISPlayerCore::setVolume (double value)
Definition at line 298 of file musicmprisplayer.cpp.
References m_application, MusicApplication::m_player, and MusicPlayer::setVolume().
bool MusicMPRISPlayerCore::shuffle () const
Definition at line 283 of file musicmprisplayer.cpp.
References m_application, MusicApplication::playMode(), and MusicObject::Random.
Referenced by syncProperties().
void MusicMPRISPlayerCore::stateChanged () private slot
When the state of the SoundCore has changed.
Definition at line 371 of file musicmprisplayer.cpp.
References m_core, m_prevPos, Qmmp::Playing, sendProperties(), SoundCore::state(), and updateTrackID().
Referenced by MusicMPRISPlayerCore().
void MusicMPRISPlayerCore::Stop () slot
Definition at line 343 of file musicmprisplayer.cpp.
References m_application, and MusicApplication::musicStateStop().
void MusicMPRISPlayerCore::syncProperties () private
Definition at line 409 of file musicmprisplayer.cpp.
References canGoNext(), canGoPrevious(), canPause(), canPlay(), canSeek(), loopStatus(), m_properties, maximumRate(), metadata(), minimumRate(), playbackStatus(), rate(), shuffle(), and volume().
Referenced by MusicMPRISPlayerCore(), and sendProperties().
void MusicMPRISPlayerCore::trackInfoChanged () private slot
When new track information is available.
Definition at line 365 of file musicmprisplayer.cpp.
References sendProperties(), and updateTrackID().
Referenced by MusicMPRISPlayerCore().
void MusicMPRISPlayerCore::updateTrackID () private
Definition at line 400 of file musicmprisplayer.cpp.
References MusicPlaylist::currentIndex(), m_application, MusicApplication::m_playlist, m_prevTrack, m_trackID, and TTKObject::random().
Referenced by MusicMPRISPlayerCore(), stateChanged(), and trackInfoChanged().
double MusicMPRISPlayerCore::volume () const
Definition at line 293 of file musicmprisplayer.cpp.
References m_application, MusicApplication::m_player, and MusicPlayer::volume().
Referenced by syncProperties().
void MusicMPRISPlayerCore::volumeChanged () private slot
When the highest volume of the left and right channels has changed.
Definition at line 381 of file musicmprisplayer.cpp.
References sendProperties().
Referenced by MusicMPRISPlayerCore().
Member Data Documentation
MusicApplication* MusicMPRISPlayerCore::m_application private
Definition at line 179 of file musicmprisplayer.h.
Referenced by canGoNext(), canGoPrevious(), canPause(), canPlay(), loopStatus(), MusicMPRISPlayerCore(), Next(), OpenUri(), Pause(), Play(), PlayPause(), Previous(), setLoopStatus(), setShuffle(), setVolume(), shuffle(), Stop(), updateTrackID(), and volume().
SoundCore* MusicMPRISPlayerCore::m_core private
Definition at line 178 of file musicmprisplayer.h.
Referenced by canSeek(), metadata(), MusicMPRISPlayerCore(), playbackStatus(), position(), Seek(), SetPosition(), and stateChanged().
qint64 MusicMPRISPlayerCore::m_prevPos private
Definition at line 177 of file musicmprisplayer.h.
Referenced by elapsedChanged(), MusicMPRISPlayerCore(), and stateChanged().
int MusicMPRISPlayerCore::m_prevTrack private
Definition at line 176 of file musicmprisplayer.h.
Referenced by MusicMPRISPlayerCore(), and updateTrackID().
TTKVariantMap MusicMPRISPlayerCore::m_properties private
Definition at line 181 of file musicmprisplayer.h.
Referenced by sendProperties(), and syncProperties().
QDBusObjectPath MusicMPRISPlayerCore::m_trackID private
Definition at line 180 of file musicmprisplayer.h.
Referenced by metadata(), SetPosition(), and updateTrackID().
Property Documentation
bool MusicMPRISPlayerCore::CanControl read
Definition at line 96 of file musicmprisplayer.h.
bool MusicMPRISPlayerCore::CanGoNext read
Definition at line 97 of file musicmprisplayer.h.
bool MusicMPRISPlayerCore::CanGoPrevious read
Definition at line 98 of file musicmprisplayer.h.
bool MusicMPRISPlayerCore::CanPause read
Definition at line 99 of file musicmprisplayer.h.
bool MusicMPRISPlayerCore::CanPlay read
Definition at line 100 of file musicmprisplayer.h.
bool MusicMPRISPlayerCore::CanSeek read
Definition at line 101 of file musicmprisplayer.h.
QString MusicMPRISPlayerCore::LoopStatus read write
Definition at line 102 of file musicmprisplayer.h.
double MusicMPRISPlayerCore::MaximumRate read
Definition at line 103 of file musicmprisplayer.h.
QVariantMap MusicMPRISPlayerCore::Metadata read
Definition at line 104 of file musicmprisplayer.h.
double MusicMPRISPlayerCore::MinimumRate read
Definition at line 105 of file musicmprisplayer.h.
QString MusicMPRISPlayerCore::PlaybackStatus read
Definition at line 106 of file musicmprisplayer.h.
qlonglong MusicMPRISPlayerCore::Position read
Definition at line 107 of file musicmprisplayer.h.
double MusicMPRISPlayerCore::Rate read write
Definition at line 108 of file musicmprisplayer.h.
bool MusicMPRISPlayerCore::Shuffle read write
Definition at line 109 of file musicmprisplayer.h.
double MusicMPRISPlayerCore::Volume read write
Definition at line 110 of file musicmprisplayer.h.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicmprisplayer.h
TTKModule/TTKCore/musicCoreKits/musicmprisplayer.cpp