TTKMusicPlayer: MusicFileInformationWidget Class Reference
MusicFileInformationWidget Class Reference
The class of the file information widget.
#include <musicfileinformationwidget.h>
Public Slots
void openFileDir ()
void openImageFileDir ()
void deleteAlbumImage ()
void saveAlbumImage ()
void openDynamicImage ()
void currentTabChanged (int index)
void downLoadFinished (const QString &bytes)
void editTag ()
void saveTag ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Public Member Functions
MusicFileInformationWidget (QWidget *parent=nullptr)
~MusicFileInformationWidget ()
void initialize (const QString &name)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show) noexcept
void blockOption (bool block) noexcept
Private Member Functions
virtual void mouseMoveEvent (QMouseEvent *event) override
void setEditLineEnabled (bool enabled)
Private Attributes
Ui::MusicFileInformationWidget * m_ui
QString m_path
QString m_imagePath
bool m_deleteImage
QWidget * m_container
MusicCoreMPlayer * m_player
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label) noexcept
Protected Attributes inherited from TTKAbstractMoveDialog
QPoint m_mousePressedAt
bool m_blockOption
bool m_shadowOption
bool m_mouseLeftPressed
Detailed Description
The class of the file information widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicfileinformationwidget.h.
Constructor & Destructor Documentation
MusicFileInformationWidget::MusicFileInformationWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 12 of file musicfileinformationwidget.cpp.
References currentTabChanged(), deleteAlbumImage(), editTag(), TTK::UI::LineEditStyle01, m_ui, openDynamicImage(), openFileDir(), openImageFileDir(), TTK::UI::PushButtonStyle04, saveAlbumImage(), saveTag(), TTK::UI::ScrollBarStyle03, MusicWidgetRenderer::setBackgroundLabel(), setEditLineEnabled(), TTK::UI::TabWidgetStyle01, and TTK::UI::ToolButtonStyle04.
MusicFileInformationWidget::~MusicFileInformationWidget ()
Object destructor.
Definition at line 66 of file musicfileinformationwidget.cpp.
References m_container, m_player, and m_ui.
Member Function Documentation
void MusicFileInformationWidget::currentTabChanged (int index) slot
Current tab index changed.
Definition at line 210 of file musicfileinformationwidget.cpp.
References m_container, m_player, and openDynamicImage().
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::deleteAlbumImage () slot
Delete album image.
Definition at line 155 of file musicfileinformationwidget.cpp.
References m_deleteImage, m_ui, and rendererPixmap().
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::downLoadFinished (const QString & bytes) slot
Download data from net finished.
Definition at line 218 of file musicfileinformationwidget.cpp.
References m_container, m_player, m_ui, MusicCoreMPlayer::Movie, MusicCoreMPlayer::play(), MusicToastLabel::popup(), and MusicCoreMPlayer::setMedia().
Referenced by openDynamicImage().
void MusicFileInformationWidget::editTag () slot
Music modify tag start.
Definition at line 246 of file musicfileinformationwidget.cpp.
References m_ui, and setEditLineEnabled().
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::initialize (const QString & name)
Set music file song information.
Definition at line 88 of file musicfileinformationwidget.cpp.
References MusicSongMeta::album(), MusicSongMeta::artist(), MusicSongMeta::bitrate(), TTK::Number::bitrateToLevel(), TTK::Number::bitrateToQuality(), CACHE_DIR_FULL, MusicSongMeta::channel(), MusicSongMeta::cover(), MusicSongMeta::description(), MusicSongMeta::duration(), MusicSongMeta::fileRelatedPath(), MusicSongMeta::genre(), m_path, m_ui, MusicSongMeta::rating(), MusicSongMeta::read(), rendererPixmap(), MusicSongMeta::sampleRate(), TTK::Number::sizeByteToLabel(), MusicSongMeta::title(), MusicSongMeta::trackNum(), TTK_DEFAULT_STR, TTK_FILE_SUFFIX, and MusicSongMeta::year().
Referenced by MusicAbstractSongsListTableWidget::showFileInformation().
void MusicFileInformationWidget::mouseMoveEvent (QMouseEvent * event) override private virtual
Override the widget event.
Reimplemented from TTKAbstractMoveDialog.
Definition at line 309 of file musicfileinformationwidget.cpp.
References m_container, m_ui, and TTKAbstractMoveDialog::mouseMoveEvent().
void MusicFileInformationWidget::openDynamicImage () slot
Dynamic album image.
Definition at line 180 of file musicfileinformationwidget.cpp.
References MusicSongMeta::cover(), downLoadFinished(), MusicCoreMPlayer::isPlaying(), m_container, m_path, m_player, m_ui, MusicSongMeta::read(), rendererPixmap(), MusicWYCoverSourceRequest::startToRequest(), and MusicCoreMPlayer::stop().
Referenced by currentTabChanged(), and MusicFileInformationWidget().
void MusicFileInformationWidget::openFileDir () slot
Open the music at local path.
Definition at line 134 of file musicfileinformationwidget.cpp.
References m_path, TTK::Url::openUrl(), MusicToastLabel::popup(), and TTK::trackRelatedPath().
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::openImageFileDir () slot
Open the selected user pixmap.
Definition at line 142 of file musicfileinformationwidget.cpp.
References TTK::File::getOpenFileName(), m_imagePath, m_ui, and rendererPixmap().
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::saveAlbumImage () slot
Save album image.
Definition at line 161 of file musicfileinformationwidget.cpp.
References MusicSongMeta::cover(), TTK::File::getSaveFileName(), m_path, and MusicSongMeta::read().
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::saveTag () slot
Music modify tag save.
Definition at line 251 of file musicfileinformationwidget.cpp.
References MusicAbstractMoveDialog::exec(), m_deleteImage, m_imagePath, m_path, m_ui, MusicToastLabel::popup(), MusicSongMeta::read(), MusicSongMeta::save(), MusicSongMeta::setAlbum(), MusicSongMeta::setArtist(), MusicSongMeta::setCover(), MusicSongMeta::setGenre(), MusicMessageBox::setText(), MusicSongMeta::setTitle(), MusicSongMeta::setYear(), and TTK_DEFAULT_STR.
Referenced by MusicFileInformationWidget().
void MusicFileInformationWidget::setEditLineEnabled (bool enabled) private
Eet editLine enable.
Definition at line 320 of file musicfileinformationwidget.cpp.
References m_ui.
Referenced by editTag(), and MusicFileInformationWidget().
Member Data Documentation
QWidget* MusicFileInformationWidget::m_container private
Definition at line 105 of file musicfileinformationwidget.h.
Referenced by currentTabChanged(), downLoadFinished(), mouseMoveEvent(), openDynamicImage(), and ~MusicFileInformationWidget().
bool MusicFileInformationWidget::m_deleteImage private
Definition at line 104 of file musicfileinformationwidget.h.
Referenced by deleteAlbumImage(), and saveTag().
QString MusicFileInformationWidget::m_imagePath private
Definition at line 103 of file musicfileinformationwidget.h.
Referenced by openImageFileDir(), and saveTag().
QString MusicFileInformationWidget::m_path private
Definition at line 103 of file musicfileinformationwidget.h.
Referenced by initialize(), openDynamicImage(), openFileDir(), saveAlbumImage(), and saveTag().
MusicCoreMPlayer* MusicFileInformationWidget::m_player private
Definition at line 106 of file musicfileinformationwidget.h.
Referenced by currentTabChanged(), downLoadFinished(), openDynamicImage(), and ~MusicFileInformationWidget().
Ui::MusicFileInformationWidget* MusicFileInformationWidget::m_ui private
Definition at line 102 of file musicfileinformationwidget.h.
Referenced by deleteAlbumImage(), downLoadFinished(), editTag(), initialize(), mouseMoveEvent(), MusicFileInformationWidget(), openDynamicImage(), openImageFileDir(), saveTag(), setEditLineEnabled(), and ~MusicFileInformationWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicfileinformationwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicfileinformationwidget.cpp