TTKMusicplayer: QDeviceChangeEvent Class Reference
QDeviceChangeEvent Class Reference
The class of the device watcher event.
#include <qdevicewatcher.h>
Public Types
enum Action { Add, Remove, Change }
Public Member Functions
QDeviceChangeEvent (Action action, const QString &device)
Action action () const
QString device () const
Static Public Member Functions
static Type registeredType ()
Private Attributes
Action m_action
QString m_device
Detailed Description
The class of the device watcher event.
Author
WangBin wbsec.nosp@m.g1@g.nosp@m.mail..nosp@m.com
Definition at line 59 of file qdevicewatcher.h.
Member Enumeration Documentation
enum QDeviceChangeEvent::Action
Enumerator
Add
Remove
Change
Definition at line 62 of file qdevicewatcher.h.
Constructor & Destructor Documentation
QDeviceChangeEvent::QDeviceChangeEvent (Action action, const QString & device) explicit
Definition at line 81 of file qdevicewatcher.cpp.
References action(), device(), m_action, and m_device.
Member Function Documentation
Action QDeviceChangeEvent::action () const inline
Definition at line 67 of file qdevicewatcher.h.
Referenced by QDeviceChangeEvent().
QString QDeviceChangeEvent::device () const inline
Definition at line 68 of file qdevicewatcher.h.
Referenced by QDeviceChangeEvent().
static Type QDeviceChangeEvent::registeredType () inline static
Definition at line 69 of file qdevicewatcher.h.
References TTKStatic_cast.
Member Data Documentation
Action QDeviceChangeEvent::m_action private
Definition at line 76 of file qdevicewatcher.h.
Referenced by QDeviceChangeEvent().
QString QDeviceChangeEvent::m_device private
Definition at line 77 of file qdevicewatcher.h.
Referenced by QDeviceChangeEvent().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKWatcher/qdevicewatcher.h
TTKThirdParty/TTKWatcher/qdevicewatcher.cpp