TTKMusicPlayer: MusicAbstractDownloadSkinRequest Class Reference
MusicAbstractDownloadSkinRequest Class Reference abstract
The class of the download skin remote background.
#include <musicabstractdownloadskinrequest.h>
Public Slots
virtual void downLoadFinished (const QByteArray &bytes)=0
Signals
void downLoadDataChanged (const MusicSkinRemoteGroupList &bytes)
Public Member Functions
MusicAbstractDownloadSkinRequest (QObject *parent=nullptr)
virtual void startToRequest ()
virtual void startToRequest (const QString &id)
Detailed Description
The class of the download skin remote background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 71 of file musicabstractdownloadskinrequest.h.
Constructor & Destructor Documentation
MusicAbstractDownloadSkinRequest::MusicAbstractDownloadSkinRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musicabstractdownloadskinrequest.cpp.
Member Function Documentation
void MusicAbstractDownloadSkinRequest::downLoadDataChanged (const MusicSkinRemoteGroupList & bytes) signal
Send download data from net.
Referenced by MusicDownloadBingSkinRequest::downLoadFinished(), MusicDownloadBirdSkinRequest::downLoadFinished(), and MusicDownloadThunderSkinRequest::downLoadFinished().
virtual void MusicAbstractDownloadSkinRequest::downLoadFinished (const QByteArray & bytes) pure virtual slot
Download data from net finished. Subclass should implement this function.
void MusicAbstractDownloadSkinRequest::startToRequest () virtual
Start to download skin data.
Reimplemented in MusicDownloadThunderSkinRequest, MusicDownloadBingSkinRequest, and MusicDownloadBirdSkinRequest.
Definition at line 9 of file musicabstractdownloadskinrequest.cpp.
Referenced by MusicBackgroundDailyWidget::initialize(), and MusicBackgroundOnlineWidget::initialize().
void MusicAbstractDownloadSkinRequest::startToRequest (const QString & id) virtual
Start to download skin data.
Reimplemented in MusicDownloadBirdSkinRequest.
Definition at line 14 of file musicabstractdownloadskinrequest.cpp.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/skin/musicabstractdownloadskinrequest.h
TTKModule/TTKCore/musicNetworkKits/image/skin/musicabstractdownloadskinrequest.cpp