TTKMusicPlayer: QJsonObject Class Reference
QJsonObject Class Reference
#include <QJsonObject.h>
Public Types
typedef QMap< QString, QJsonValue >::const_iterator const_iterator
typedef QMap< QString, QJsonValue >::iterator iterator
typedef const_iterator ConstIterator
typedef iterator Iterator
typedef QMap< QString, QJsonValue >::key_type key_type
typedef QMap< QString, QJsonValue >::mapped_type mapped_type
typedef QMap< QString, QJsonValue >::size_type size_type
Public Member Functions
QJsonObject ()
QJsonObject (const QJsonObject &other)
~QJsonObject ()
QJsonObject & operator= (const QJsonObject &other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator constBegin () const
const_iterator constEnd () const
int count () const
int length () const
int size () const
bool empty () const
bool isEmpty () const
const_iterator constFind (const QString &key) const
bool contains (const QString &key) const
iterator find (const QString &key)
const_iterator find (const QString &key) const
iterator erase (iterator it)
iterator insert (const QString &key, const QJsonValue &value)
QStringList keys () const
void remove (const QString &key)
QJsonValue take (const QString &key)
QJsonValue value (const QString &key) const
bool operator!= (const QJsonObject &other) const
bool operator== (const QJsonObject &other) const
QJsonValue operator[] (const QString &key) const
QJsonValueRef operator[] (const QString &key)
QVariantMap toVariantMap () const
QVariantHash toVariantHash () const
Public Member Functions inherited from QJsonRoot
virtual ~QJsonRoot ()
Static Public Member Functions
static QJsonObject fromVariantMap (const QVariantMap &map)
static QJsonObject fromVariantHash (const QVariantHash &hash)
Private Member Functions
virtual QJsonRoot * clone () const
virtual QJsonArray * toArray ()
virtual QJsonObject * toObject ()
virtual const QJsonArray * toArray () const
virtual const QJsonObject * toObject () const
void swap (QJsonObject &other)
Private Attributes
QMap< QString, QJsonValue > values_
Friends
class QJsonDocument
class QJsonValue
class QJsonValueRef
class QJsonParser
Detailed Description
Definition at line 36 of file QJsonObject.h.
Member Typedef Documentation
typedef QMap<QString, QJsonValue>::const_iterator QJsonObject::const_iterator
Definition at line 47 of file QJsonObject.h.
typedef const_iterator QJsonObject::ConstIterator
Definition at line 49 of file QJsonObject.h.
typedef QMap<QString, QJsonValue>::iterator QJsonObject::iterator
Definition at line 48 of file QJsonObject.h.
typedef iterator QJsonObject::Iterator
Definition at line 50 of file QJsonObject.h.
typedef QMap<QString, QJsonValue>::key_type QJsonObject::key_type
Definition at line 51 of file QJsonObject.h.
typedef QMap<QString, QJsonValue>::mapped_type QJsonObject::mapped_type
Definition at line 52 of file QJsonObject.h.
typedef QMap<QString, QJsonValue>::size_type QJsonObject::size_type
Definition at line 53 of file QJsonObject.h.
Constructor & Destructor Documentation
QJsonObject::QJsonObject ()
Definition at line 26 of file QJsonObject.cpp.
Referenced by clone(), and operator=().
QJsonObject::QJsonObject (const QJsonObject & other)
Definition at line 32 of file QJsonObject.cpp.
QJsonObject::~QJsonObject ()
Definition at line 50 of file QJsonObject.cpp.
Member Function Documentation
QJsonObject::iterator QJsonObject::begin ()
Definition at line 64 of file QJsonObject.cpp.
References values_.
Referenced by constBegin(), QJsonDocument::toJson(), toVariantHash(), and toVariantMap().
QJsonObject::const_iterator QJsonObject::begin () const
Definition at line 71 of file QJsonObject.cpp.
References values_.
QJsonRoot * QJsonObject::clone () const private virtual
Implements QJsonRoot.
Definition at line 283 of file QJsonObject.cpp.
References QJsonObject().
Referenced by QJsonValue::QJsonValue().
QJsonObject::const_iterator QJsonObject::constBegin () const
Definition at line 92 of file QJsonObject.cpp.
References begin().
QJsonObject::const_iterator QJsonObject::constEnd () const
Definition at line 99 of file QJsonObject.cpp.
References end().
QJsonObject::const_iterator QJsonObject::constFind (const QString & key) const
Definition at line 141 of file QJsonObject.cpp.
References values_.
bool QJsonObject::contains (const QString & key) const
Definition at line 148 of file QJsonObject.cpp.
References values_.
int QJsonObject::count () const
Definition at line 106 of file QJsonObject.cpp.
References size().
bool QJsonObject::empty () const
Definition at line 127 of file QJsonObject.cpp.
References values_.
Referenced by isEmpty(), and QJsonDocument::toJson().
QJsonObject::iterator QJsonObject::end ()
Definition at line 78 of file QJsonObject.cpp.
References values_.
Referenced by constEnd(), QJsonDocument::toJson(), toVariantHash(), and toVariantMap().
QJsonObject::const_iterator QJsonObject::end () const
Definition at line 85 of file QJsonObject.cpp.
References values_.
QJsonObject::iterator QJsonObject::erase (iterator it)
Definition at line 169 of file QJsonObject.cpp.
References values_.
QJsonObject::iterator QJsonObject::find (const QString & key)
Definition at line 155 of file QJsonObject.cpp.
References values_.
QJsonObject::const_iterator QJsonObject::find (const QString & key) const
Definition at line 162 of file QJsonObject.cpp.
References values_.
QJsonObject QJsonObject::fromVariantHash (const QVariantHash & hash) static
Definition at line 272 of file QJsonObject.cpp.
References QJsonValue::fromVariant(), and insert().
Referenced by QJsonDocument::fromVariant().
QJsonObject QJsonObject::fromVariantMap (const QVariantMap & map) static
Definition at line 261 of file QJsonObject.cpp.
References QJsonValue::fromVariant(), and insert().
Referenced by QJsonDocument::fromVariant(), and QJsonValue::fromVariant().
QJsonObject::iterator QJsonObject::insert (const QString & key, const QJsonValue & value)
Definition at line 176 of file QJsonObject.cpp.
References values_.
Referenced by fromVariantHash(), and fromVariantMap().
bool QJsonObject::isEmpty () const
Definition at line 134 of file QJsonObject.cpp.
References empty().
QStringList QJsonObject::keys () const
Definition at line 183 of file QJsonObject.cpp.
References values_.
int QJsonObject::length () const
Definition at line 113 of file QJsonObject.cpp.
References size().
bool QJsonObject::operator!= (const QJsonObject & other) const
Definition at line 211 of file QJsonObject.cpp.
References values_.
QJsonObject & QJsonObject::operator= (const QJsonObject & other)
Definition at line 56 of file QJsonObject.cpp.
References QJsonObject().
bool QJsonObject::operator== (const QJsonObject & other) const
Definition at line 218 of file QJsonObject.cpp.
References values_.
QJsonValue QJsonObject::operator[] (const QString & key) const
Definition at line 225 of file QJsonObject.cpp.
References key, and values_.
QJsonValueRef QJsonObject::operator[] (const QString & key)
Definition at line 232 of file QJsonObject.cpp.
References QJsonValueRef.
void QJsonObject::remove (const QString & key)
Definition at line 190 of file QJsonObject.cpp.
References values_.
int QJsonObject::size () const
Definition at line 120 of file QJsonObject.cpp.
References values_.
Referenced by count(), and length().
void QJsonObject::swap (QJsonObject & other) private
Definition at line 318 of file QJsonObject.cpp.
References values_.
QJsonValue QJsonObject::take (const QString & key)
Definition at line 197 of file QJsonObject.cpp.
References values_.
QJsonArray * QJsonObject::toArray () private virtual
Implements QJsonRoot.
Definition at line 304 of file QJsonObject.cpp.
const QJsonArray * QJsonObject::toArray () const private virtual
Implements QJsonRoot.
Definition at line 311 of file QJsonObject.cpp.
QJsonObject * QJsonObject::toObject () private virtual
Implements QJsonRoot.
Definition at line 297 of file QJsonObject.cpp.
const QJsonObject * QJsonObject::toObject () const private virtual
Implements QJsonRoot.
Definition at line 290 of file QJsonObject.cpp.
QVariantHash QJsonObject::toVariantHash () const
Definition at line 250 of file QJsonObject.cpp.
References begin(), and end().
QVariantMap QJsonObject::toVariantMap () const
Definition at line 239 of file QJsonObject.cpp.
References begin(), and end().
Referenced by QJsonValue::toVariant().
QJsonValue QJsonObject::value (const QString & key) const
Definition at line 204 of file QJsonObject.cpp.
References values_.
Friends And Related Function Documentation
friend class QJsonDocument friend
Definition at line 37 of file QJsonObject.h.
friend class QJsonParser friend
Definition at line 40 of file QJsonObject.h.
friend class QJsonValue friend
Definition at line 38 of file QJsonObject.h.
friend class QJsonValueRef friend
Definition at line 39 of file QJsonObject.h.
Referenced by operator[]().
Member Data Documentation
QMap<QString, QJsonValue> QJsonObject::values_ private
Definition at line 116 of file QJsonObject.h.
Referenced by begin(), constFind(), contains(), empty(), end(), erase(), find(), insert(), keys(), operator!=(), operator==(), operator[](), remove(), size(), swap(), take(), and value().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/QJsonObject.h
TTKThirdParty/TTKExtras/qjson/QJsonObject.cpp