TTKMusicplayer: MusicConsoleModule Class Reference
MusicConsoleModule Class Reference
The class of the music console module.
#include <musicconsolemodule.h>
Public Member Functions
MusicConsoleModule (QObject *parent=nullptr)
~MusicConsoleModule ()
bool init (const QCoreApplication &app)
Protected Member Functions
void print (qint64 position, qint64 duration)
Protected Attributes
MusicPlayer * m_musicPlayer
MusicPlaylist * m_musicPlaylist
int m_volume
QString m_playbackMode
QString m_enhanced
Private Slots
void durationChanged (qint64 duration)
void positionChanged (qint64 position)
void currentIndexChanged (int index)
void musicStatePlay ()
void musicPlayPrevious ()
void musicPlayNext ()
void resetVolume ()
void musicActionVolumeSub ()
void musicActionVolumePlus ()
void musicPlayOrder ()
void musicPlayRandom ()
void musicPlaylistLoop ()
void musicPlayOneLoop ()
void musicPlayOnce ()
void musicEnhancedOff ()
void musicEnhanced3D ()
void musicEnhancedNICAM ()
void musicEnhancedSubwoofer ()
void musicEnhancedVocal ()
Detailed Description
The class of the music console module.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicconsolemodule.h.
Constructor & Destructor Documentation
MusicConsoleModule::MusicConsoleModule (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 14 of file musicconsolemodule.cpp.
References currentIndexChanged(), durationChanged(), G_HOTKEY_PTR, m_enhanced, m_musicPlayer, m_musicPlaylist, m_playbackMode, m_volume, musicActionVolumePlus(), musicActionVolumeSub(), musicEnhanced3D(), musicEnhancedNICAM(), musicEnhancedOff(), musicEnhancedSubwoofer(), musicEnhancedVocal(), musicPlaylistLoop(), musicPlayNext(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayPrevious(), musicPlayRandom(), musicStatePlay(), MusicObject::PM_PlayOrder, positionChanged(), MusicPlaylist::setPlaybackMode(), and MusicPlayer::setPlaylist().
MusicConsoleModule::~MusicConsoleModule ()
Definition at line 70 of file musicconsolemodule.cpp.
References m_musicPlayer, m_musicPlaylist, and TTK_LOGGER_INFO.
Member Function Documentation
void MusicConsoleModule::currentIndexChanged (int index) private slot
Current playlist index changed.
Definition at line 203 of file musicconsolemodule.cpp.
References MT_S2MS, resetVolume(), and TTK_LOGGER_INFO.
Referenced by MusicConsoleModule().
void MusicConsoleModule::durationChanged (qint64 duration) private slot
Current duration changed.
Definition at line 193 of file musicconsolemodule.cpp.
References print().
Referenced by MusicConsoleModule().
bool MusicConsoleModule::init (const QCoreApplication & app)
Init all parameter.
Definition at line 77 of file musicconsolemodule.cpp.
References MusicPlaylist::addMedia(), MusicPlaylist::appendMedia(), MusicUtils::File::getFileListByDir(), MusicPlaylist::isEmpty(), LST_FILE_PREFIX, m_musicPlayer, m_musicPlaylist, m_volume, MusicPlaylist::mediaCount(), MusicPlayer::play(), MusicTKPLConfigManager::readConfig(), MusicTKPLConfigManager::readPlaylistData(), MusicPlaylist::setCurrentIndex(), MusicPlayer::setVolume(), MusicFormats::supportMusicInputFilterFormats(), TTK_LOGGER_ERROR, and TTK_LOGGER_INFO.
Referenced by main().
void MusicConsoleModule::musicActionVolumePlus () private slot
Set current player volume up.
Definition at line 284 of file musicconsolemodule.cpp.
References m_musicPlayer, m_volume, MusicPlayer::setVolume(), and MusicPlayer::volume().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicActionVolumeSub () private slot
Set current player volume down.
Definition at line 272 of file musicconsolemodule.cpp.
References m_musicPlayer, m_volume, MusicPlayer::setVolume(), and MusicPlayer::volume().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicEnhanced3D () private slot
Set current music 3d music effect.
Definition at line 332 of file musicconsolemodule.cpp.
References MusicPlayer::Enhanced3D, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicEnhancedNICAM () private slot
Set current music nicam music effect.
Definition at line 338 of file musicconsolemodule.cpp.
References MusicPlayer::EnhancedNICAM, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicEnhancedOff () private slot
Set current music enhanced off, no any effect.
Definition at line 326 of file musicconsolemodule.cpp.
References MusicPlayer::EnhancedOff, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicEnhancedSubwoofer () private slot
Set current music subwoofer music effect.
Definition at line 344 of file musicconsolemodule.cpp.
References MusicPlayer::EnhancedSubwoofer, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicEnhancedVocal () private slot
Set current music vocal music effect.
Definition at line 350 of file musicconsolemodule.cpp.
References MusicPlayer::EnhancedVocal, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlaylistLoop () private slot
Set current play mdoe to list loop.
Definition at line 308 of file musicconsolemodule.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlaylistLoop, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlayNext () private slot
Set current player to play next.
Definition at line 247 of file musicconsolemodule.cpp.
References MusicPlaylist::isEmpty(), m_musicPlayer, m_musicPlaylist, m_volume, MusicPlayer::play(), MusicPlaylist::playbackMode(), MusicPlayer::playNext(), MusicObject::PM_PlayRandom, MusicPlaylist::setCurrentIndex(), and MusicPlayer::setVolume().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlayOnce () private slot
Set current play mdoe to just once.
Definition at line 320 of file musicconsolemodule.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayOnce, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlayOneLoop () private slot
Set current play mdoe to single loop.
Definition at line 314 of file musicconsolemodule.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayOneLoop, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlayOrder () private slot
Set current play mdoe to order.
Definition at line 296 of file musicconsolemodule.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayOrder, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlayPrevious () private slot
Set current player to play previous.
Definition at line 227 of file musicconsolemodule.cpp.
References MusicPlaylist::isEmpty(), m_musicPlayer, m_musicPlaylist, m_volume, MusicPlayer::play(), MusicPlaylist::playbackMode(), MusicPlayer::playPrevious(), MusicObject::PM_PlayRandom, MusicPlaylist::setCurrentIndex(), and MusicPlayer::setVolume().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicPlayRandom () private slot
Set current play mdoe to random.
Definition at line 302 of file musicconsolemodule.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayRandom, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleModule().
void MusicConsoleModule::musicStatePlay () private slot
Set current player to play or not.
Definition at line 209 of file musicconsolemodule.cpp.
References MusicPlaylist::isEmpty(), MusicPlayer::isPlaying(), m_musicPlayer, m_musicPlaylist, m_volume, MusicPlayer::pause(), MusicPlayer::play(), and MusicPlayer::setVolume().
Referenced by MusicConsoleModule().
void MusicConsoleModule::positionChanged (qint64 position) private slot
Current position changed.
Definition at line 198 of file musicconsolemodule.cpp.
References MusicPlayer::duration(), m_musicPlayer, and print().
Referenced by MusicConsoleModule().
void MusicConsoleModule::print (qint64 position, qint64 duration) protected
Print debug info.
Definition at line 356 of file musicconsolemodule.cpp.
References MusicPlaylist::currentMediaPath(), m_enhanced, m_musicPlayer, m_musicPlaylist, m_playbackMode, MusicTime::msecTime2LabelJustified(), TTK_LOGGER_INFO, and MusicPlayer::volume().
Referenced by durationChanged(), and positionChanged().
void MusicConsoleModule::resetVolume () private slot
Reset player volume.
Definition at line 267 of file musicconsolemodule.cpp.
References m_musicPlayer, m_volume, and MusicPlayer::setVolume().
Referenced by currentIndexChanged().
Member Data Documentation
QString MusicConsoleModule::m_enhanced protected
Definition at line 138 of file musicconsolemodule.h.
Referenced by MusicConsoleModule(), musicEnhanced3D(), musicEnhancedNICAM(), musicEnhancedOff(), musicEnhancedSubwoofer(), musicEnhancedVocal(), and print().
MusicPlayer* MusicConsoleModule::m_musicPlayer protected
Definition at line 135 of file musicconsolemodule.h.
Referenced by init(), musicActionVolumePlus(), musicActionVolumeSub(), MusicConsoleModule(), musicEnhanced3D(), musicEnhancedNICAM(), musicEnhancedOff(), musicEnhancedSubwoofer(), musicEnhancedVocal(), musicPlayNext(), musicPlayPrevious(), musicStatePlay(), positionChanged(), print(), resetVolume(), and ~MusicConsoleModule().
MusicPlaylist* MusicConsoleModule::m_musicPlaylist protected
Definition at line 136 of file musicconsolemodule.h.
Referenced by init(), MusicConsoleModule(), musicPlaylistLoop(), musicPlayNext(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayPrevious(), musicPlayRandom(), musicStatePlay(), print(), and ~MusicConsoleModule().
QString MusicConsoleModule::m_playbackMode protected
Definition at line 138 of file musicconsolemodule.h.
Referenced by MusicConsoleModule(), musicPlaylistLoop(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayRandom(), and print().
int MusicConsoleModule::m_volume protected
Definition at line 137 of file musicconsolemodule.h.
Referenced by init(), musicActionVolumePlus(), musicActionVolumeSub(), MusicConsoleModule(), musicPlayNext(), musicPlayPrevious(), musicStatePlay(), and resetVolume().
The documentation for this class was generated from the following files:
TTKRun/TTKConsole/musicconsolemodule.h
TTKRun/TTKConsole/musicconsolemodule.cpp