TTKMusicPlayer: MusicPageQueryWidget Class Reference
MusicPageQueryWidget Class Reference
The class of the page query widget.
#include <musicpagequerywidget.h>
Signals
void clicked (int index)
Public Member Functions
MusicPageQueryWidget (QObject *parent=nullptr)
~MusicPageQueryWidget ()
QWidget * createPageWidget (QWidget *parent, int total)
void reset (int total)
void page (int index, int total)
int currentIndex () const
Private Member Functions
void updateStatus ()
Private Attributes
int m_currentPage
QWidget * m_pageWidget
QList< TTKClickedLabel * > m_pageItems
Detailed Description
The class of the page query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicpagequerywidget.h.
Constructor & Destructor Documentation
MusicPageQueryWidget::MusicPageQueryWidget (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 9 of file musicpagequerywidget.cpp.
MusicPageQueryWidget::~MusicPageQueryWidget ()
Object destructor.
Definition at line 17 of file musicpagequerywidget.cpp.
References m_pageItems, and m_pageWidget.
Member Function Documentation
void MusicPageQueryWidget::clicked (int index) signal
Mapped the clicked page index.
Referenced by createPageWidget().
QWidget * MusicPageQueryWidget::createPageWidget (QWidget * parent, int total)
Create page items.
Definition at line 23 of file musicpagequerywidget.cpp.
References clicked(), TTK::UI::ColorStyle04, TTK::UI::FontStyle01, TTK::UI::FontStyle05, TTK::Widget::fontTextWidth(), m_pageItems, m_pageWidget, MAX_PAGE_SIZE, and qAsConst.
Referenced by MusicArtistAlbumsQueryWidget::createArtistAlbumsItem(), MusicArtistListQueryWidget::createArtistListItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicCommentsWidget::createPageWidget(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), and MusicItemMoreRecommendQueryWidget::createResultItem().
int MusicPageQueryWidget::currentIndex () const
Get current page index.
Definition at line 209 of file musicpagequerywidget.cpp.
References m_currentPage, and m_pageItems.
Referenced by MusicArtistMvsQueryWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), MusicPlaylistQueryWidget::buttonClicked(), MusicCommentsWidget::buttonClicked(), MusicArtistAlbumsQueryWidget::buttonClicked(), and MusicItemMoreRecommendQueryWidget::buttonClicked().
void MusicPageQueryWidget::page (int index, int total)
Start to page by given index and total.
Definition at line 124 of file musicpagequerywidget.cpp.
References m_currentPage, m_pageItems, MAX_PAGE_SIZE, and updateStatus().
Referenced by MusicArtistMvsQueryWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), MusicPlaylistQueryWidget::buttonClicked(), MusicCommentsWidget::buttonClicked(), MusicArtistAlbumsQueryWidget::buttonClicked(), and MusicItemMoreRecommendQueryWidget::buttonClicked().
void MusicPageQueryWidget::reset (int total)
Reset page to origin.
Definition at line 96 of file musicpagequerywidget.cpp.
References m_currentPage, m_pageItems, MAX_PAGE_SIZE, qAsConst, and updateStatus().
Referenced by MusicArtistListQueryWidget::createArtistListItem(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), and MusicItemMoreRecommendQueryWidget::createResultItem().
void MusicPageQueryWidget::updateStatus () private
Update button status.
Definition at line 214 of file musicpagequerywidget.cpp.
References TTK::UI::ColorStyle04, TTK::UI::FontStyle01, TTK::Widget::fontTextWidth(), m_currentPage, and m_pageItems.
Referenced by page(), and reset().
Member Data Documentation
int MusicPageQueryWidget::m_currentPage private
Definition at line 73 of file musicpagequerywidget.h.
Referenced by currentIndex(), page(), reset(), and updateStatus().
QList<TTKClickedLabel*> MusicPageQueryWidget::m_pageItems private
Definition at line 75 of file musicpagequerywidget.h.
Referenced by createPageWidget(), currentIndex(), page(), reset(), updateStatus(), and ~MusicPageQueryWidget().
QWidget* MusicPageQueryWidget::m_pageWidget private
Definition at line 74 of file musicpagequerywidget.h.
Referenced by createPageWidget(), and ~MusicPageQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicpagequerywidget.h
TTKModule/TTKWidget/musicCoreKits/musicpagequerywidget.cpp