TTKMusicplayer: DlnaClient Class Reference
DlnaClient Class Reference
The class of the dlna client.
#include <dlnaclient.h>
Public Member Functions
DlnaClient (const QString &data)
QString server ()
QString serverName ()
bool connect ()
bool isConnected () const
QString tryToPlayFile (const QString &url)
QString uploadFileToPlay (const QString &url)
QString startPlay (int instance)
QString stopPlay (int instance)
QString pause (int instance)
QString getPosition ()
int totalSeconds (const QString &value)
Detailed Description
The class of the dlna client.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file dlnaclient.h.
Constructor & Destructor Documentation
DlnaClient::DlnaClient (const QString & data) explicit
Definition at line 141 of file dlnaclient.cpp.
References TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
bool DlnaClient::connect ()
Definition at line 160 of file dlnaclient.cpp.
References TTK_D.
Referenced by DlnaFinder::readResponse().
QString DlnaClient::getPosition ()
Definition at line 231 of file dlnaclient.cpp.
References HelperDlna::MakeRequest(), HelperDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
bool DlnaClient::isConnected () const
Definition at line 166 of file dlnaclient.cpp.
References TTK_D.
Referenced by DlnaFinder::readResponse().
QString DlnaClient::pause (int instance)
Definition at line 220 of file dlnaclient.cpp.
References HelperDlna::MakeRequest(), HelperDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
QString DlnaClient::server ()
Definition at line 148 of file dlnaclient.cpp.
References TTK_D.
Referenced by DlnaFinderPrivate::findClient(), and DlnaFinder::readResponse().
QString DlnaClient::serverName ()
Definition at line 154 of file dlnaclient.cpp.
References TTK_D.
Referenced by DlnaFinder::clientNames().
QString DlnaClient::startPlay (int instance)
Definition at line 198 of file dlnaclient.cpp.
References HelperDlna::MakeRequest(), HelperDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by tryToPlayFile().
QString DlnaClient::stopPlay (int instance)
Definition at line 209 of file dlnaclient.cpp.
References HelperDlna::MakeRequest(), HelperDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
int DlnaClient::totalSeconds (const QString & value)
Definition at line 240 of file dlnaclient.cpp.
QString DlnaClient::tryToPlayFile (const QString & url)
Definition at line 172 of file dlnaclient.cpp.
References M_LOGGER_INFO, startPlay(), TTK_D, and uploadFileToPlay().
QString DlnaClient::uploadFileToPlay (const QString & url)
Definition at line 182 of file dlnaclient.cpp.
References M_LOGGER_INFO, HelperDlna::MakeRequest(), HelperDlna::makeSocketGetReply(), TTK_D, XML_FOOT, and XML_HEAD.
Referenced by tryToPlayFile().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/dlnaclient.h
TTKThirdParty/TTKExtras/qdlna/dlnaclient.cpp