TTKMusicPlayer: TTKApplication Class Reference
TTKApplication Class Reference
The class of the ttk application.
#include <ttkapplication.h>
Public Slots
bool sendMessage (const QString &message, int timeout=5000)
void activateWindow ()
Signals
void messageReceived (const QString &message)
Public Member Functions
TTKApplication (int &argc, char **argv)
TTKApplication (const QString &id, int &argc, char **argv)
bool isRunning () const
QString id () const
void setActivationWindow (QWidget *aw, bool activateOnMessage=true) const
QWidget * activationWindow () const
Private Member Functions
void initialize (const QString &id={})
Detailed Description
The class of the ttk application.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttkapplication.h.
Constructor & Destructor Documentation
TTKApplication::TTKApplication (int & argc, char ** argv)
Object constructor.
Definition at line 33 of file ttkapplication.cpp.
References initialize(), and TTK_INIT_PRIVATE.
TTKApplication::TTKApplication (const QString & id, int & argc, char ** argv)
Definition at line 40 of file ttkapplication.cpp.
References initialize(), and TTK_INIT_PRIVATE.
Member Function Documentation
void TTKApplication::activateWindow () slot
Selected current active window.
Definition at line 86 of file ttkapplication.cpp.
References TTK_D.
Referenced by setActivationWindow().
QWidget * TTKApplication::activationWindow () const
Get current active window.
Definition at line 74 of file ttkapplication.cpp.
References TTK_D.
QString TTKApplication::id () const
Get current server id.
Definition at line 53 of file ttkapplication.cpp.
References TTK_D.
void TTKApplication::initialize (const QString & id = {}) private
Init the system parameter.
Definition at line 97 of file ttkapplication.cpp.
References messageReceived(), and TTK_D.
Referenced by TTKApplication().
bool TTKApplication::isRunning () const
Check the current server is running or not.
Definition at line 47 of file ttkapplication.cpp.
References TTK_D.
Referenced by main().
void TTKApplication::messageReceived (const QString & message) signal
Emit when the current message received.
Referenced by initialize(), and setActivationWindow().
bool TTKApplication::sendMessage (const QString & message, int timeout = 5000) slot
Emit when the current message received.
Definition at line 80 of file ttkapplication.cpp.
References TTK_D.
void TTKApplication::setActivationWindow (QWidget * aw, bool activateOnMessage = true) const
Set current active window.
Definition at line 59 of file ttkapplication.cpp.
References activateWindow(), messageReceived(), and TTK_D.
The documentation for this class was generated from the following files:
TTKCommon/TTKApplication/ttkapplication.h
TTKCommon/TTKApplication/ttkapplication.cpp