TTKMusicPlayer: MusicWebMVRadioQueryItemWidget Class Reference
MusicWebMVRadioQueryItemWidget Class Reference
The class of the music mv query item widget.
#include <musicwebmvradioquerywidget.h>
Public Slots
void downLoadFinished (const QByteArray &bytes)
void renderFinished (const QPixmap &data)
void currentItemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicWebMVRadioQueryItemWidget (QWidget *parent=nullptr)
~MusicWebMVRadioQueryItemWidget ()
void setResultDataItem (const MusicResultDataItem &item)
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
Private Attributes
MusicResultDataItem m_itemData
QPushButton * m_playButton
QLabel * m_iconLabel
QLabel * m_nameLabel
Detailed Description
The class of the music mv query item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicwebmvradioquerywidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioQueryItemWidget::MusicWebMVRadioQueryItemWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 13 of file musicwebmvradioquerywidget.cpp.
References TTK::UI::ColorStyle06, currentItemClicked(), TTK::UI::FontStyle01, TTK::UI::FontStyle04, HEIGHT_LABEL_SIZE, m_iconLabel, m_nameLabel, m_playButton, TTK::UI::TinyBtnPlaylist, TTK_DEFAULT_STR, and WIDTH_LABEL_SIZE.
MusicWebMVRadioQueryItemWidget::~MusicWebMVRadioQueryItemWidget ()
Object destructor.
Definition at line 38 of file musicwebmvradioquerywidget.cpp.
References m_iconLabel, m_nameLabel, and m_playButton.
Member Function Documentation
void MusicWebMVRadioQueryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
void MusicWebMVRadioQueryItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 81 of file musicwebmvradioquerywidget.cpp.
References m_itemData.
Referenced by MusicWebMVRadioQueryItemWidget().
void MusicWebMVRadioQueryItemWidget::downLoadFinished (const QByteArray & bytes) slot
Send recieved data from net.
Definition at line 61 of file musicwebmvradioquerywidget.cpp.
References m_iconLabel, renderFinished(), MusicImageRenderer::setInputData(), TTKAbstractThread::start(), and TTK_ERROR_STREAM.
Referenced by setResultDataItem().
void MusicWebMVRadioQueryItemWidget::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Definition at line 86 of file musicwebmvradioquerywidget.cpp.
References m_nameLabel, and m_playButton.
void MusicWebMVRadioQueryItemWidget::leaveEvent (QEvent * event) final override private virtual
Definition at line 94 of file musicwebmvradioquerywidget.cpp.
References m_nameLabel, and m_playButton.
void MusicWebMVRadioQueryItemWidget::renderFinished (const QPixmap & data) slot
Image render finished.
Definition at line 75 of file musicwebmvradioquerywidget.cpp.
References m_iconLabel, and m_playButton.
Referenced by downLoadFinished().
void MusicWebMVRadioQueryItemWidget::setResultDataItem (const MusicResultDataItem & item)
Set music results item.
Definition at line 45 of file musicwebmvradioquerywidget.cpp.
References downLoadFinished(), TTK::Widget::elidedText(), G_DOWNLOAD_QUERY_PTR, TTK::isCoverValid(), MusicResultDataItem::m_coverUrl, m_itemData, MusicResultDataItem::m_name, m_nameLabel, m_playButton, MusicCoverRequest::startToRequest(), and WIDTH_LABEL_SIZE.
Referenced by MusicWebMVRadioQueryWidget::createMVRadioCategoryItem().
Member Data Documentation
QLabel* MusicWebMVRadioQueryItemWidget::m_iconLabel private
Definition at line 79 of file musicwebmvradioquerywidget.h.
Referenced by downLoadFinished(), MusicWebMVRadioQueryItemWidget(), renderFinished(), and ~MusicWebMVRadioQueryItemWidget().
MusicResultDataItem MusicWebMVRadioQueryItemWidget::m_itemData private
Definition at line 77 of file musicwebmvradioquerywidget.h.
Referenced by currentItemClicked(), and setResultDataItem().
QLabel * MusicWebMVRadioQueryItemWidget::m_nameLabel private
Definition at line 79 of file musicwebmvradioquerywidget.h.
Referenced by enterEvent(), leaveEvent(), MusicWebMVRadioQueryItemWidget(), setResultDataItem(), and ~MusicWebMVRadioQueryItemWidget().
QPushButton* MusicWebMVRadioQueryItemWidget::m_playButton private
Definition at line 78 of file musicwebmvradioquerywidget.h.
Referenced by enterEvent(), leaveEvent(), MusicWebMVRadioQueryItemWidget(), renderFinished(), setResultDataItem(), and ~MusicWebMVRadioQueryItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerywidget.cpp