TTKMusicplayer: MusicInitObject Class Reference
MusicInitObject Class Reference
The class of the music init object.
#include <musicinitobject.h>
Public Member Functions
MusicInitObject (QObject *parent=0)
void checkValid ()
void init ()
void dirIsExist (const QString &name)
void checkTheDirectoryExist ()
void checkTheFileNeededExist ()
void copyFileOverwrite (const QString &origin, const QString &des)
void copyFile (const QString &origin, const QString &des)
Detailed Description
The class of the music init object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 66 of file musicinitobject.h.
Constructor & Destructor Documentation
MusicInitObject::MusicInitObject (QObject * parent = 0) explicit
Object contsructor.
Definition at line 5 of file musicinitobject.cpp.
Member Function Documentation
void MusicInitObject::checkTheDirectoryExist ()
Check the related dir is exist.
Definition at line 41 of file musicinitobject.cpp.
References dirIsExist(), S_APPDATA_DIR_FULL, S_ART_DIR_FULL, S_AVATAR_DIR_FULL, S_BACKGROUND_DIR_FULL, S_CACHE_DIR_FULL, S_DOWNLOADS_DIR_FULL, S_LANGUAGE_DIR_FULL, S_LRC_DIR_FULL, S_MOVIE_DIR_FULL, S_MUSIC_DIR_FULL, S_PLUGINS_DIR_FULL, S_THEME_DIR_FULL, S_UPDATE_DIR_FULL, and S_USER_THEME_DIR_FULL.
Referenced by checkValid().
void MusicInitObject::checkTheFileNeededExist ()
Check the related file is exist.
Definition at line 62 of file musicinitobject.cpp.
References copyFile(), S_BARRAGEPATH_FULL, S_CLOUDDOWNPATH_FULL, S_CLOUDUPPATH_FULL, S_COFIGPATH_FULL, S_DARABASEPATH_FULL, S_MUSICPATH_FULL, S_MUSICSEARCH_FULL, S_NORMALDOWNPATH_FULL, S_TTKDD_FULL, S_TTKSERVICE_FULL, and S_USERPATH_FULL.
Referenced by checkValid(), and init().
void MusicInitObject::checkValid ()
Check current setting file's validation.
Definition at line 11 of file musicinitobject.cpp.
References checkTheDirectoryExist(), and checkTheFileNeededExist().
Referenced by TTKRunObject::checkValid().
void MusicInitObject::copyFile (const QString & origin, const QString & des)
Copy file.
Definition at line 101 of file musicinitobject.cpp.
Referenced by checkTheFileNeededExist().
void MusicInitObject::copyFileOverwrite (const QString & origin, const QString & des)
Copy file by overwrite.
Definition at line 91 of file musicinitobject.cpp.
Referenced by init().
void MusicInitObject::dirIsExist (const QString & name)
Check current dir is exist, no, just create it.
Definition at line 32 of file musicinitobject.cpp.
Referenced by checkTheDirectoryExist().
void MusicInitObject::init ()
Init all parameter.
Definition at line 17 of file musicinitobject.cpp.
References checkTheFileNeededExist(), copyFileOverwrite(), S_BARRAGEPATH_FULL, S_CLOUDDOWNPATH_FULL, S_CLOUDUPPATH_FULL, S_COFIGPATH_FULL, S_DARABASEPATH_FULL, S_MUSICPATH_FULL, S_MUSICSEARCH_FULL, S_NORMALDOWNPATH_FULL, and S_USERPATH_FULL.
Referenced by main().
The documentation for this class was generated from the following files:
TTKRun/TTKInit/musicinitobject.h
TTKRun/TTKInit/musicinitobject.cpp