TTKMusicplayer: MusicArtistListQueryCategoryPopWidget Class Reference
MusicArtistListQueryCategoryPopWidget Class Reference
The class of the artist list query category pop widget.
#include <musicartistlistquerycategorypopwidget.h>
Public Slots
virtual void popupMenu () override
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicArtistListQueryCategoryPopWidget (QWidget *parent=nullptr)
void setCategory (const QString &server, QObject *obj)
void closeMenu ()
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initWidget ()
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the artist list query category pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 65 of file musicartistlistquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicArtistListQueryCategoryPopWidget::MusicArtistListQueryCategoryPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 57 of file musicartistlistquerycategorypopwidget.cpp.
References initWidget().
Member Function Documentation
void MusicArtistListQueryCategoryPopWidget::closeMenu ()
Close the menu dialog.
Definition at line 90 of file musicartistlistquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
Referenced by MusicArtistListQueryWidget::categoryChanged().
void MusicArtistListQueryCategoryPopWidget::initWidget () protected
Create all widget in layout.
Definition at line 100 of file musicartistlistquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, MusicUIObject::MQSSBackgroundStyle17, MusicUIObject::MQSSBorderStyle04, MusicUIObject::MQSSMenuStyle05, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicArtistListQueryCategoryPopWidget().
void MusicArtistListQueryCategoryPopWidget::popupMenu () override virtual slot
To popup menu.
Definition at line 95 of file musicartistlistquerycategorypopwidget.cpp.
References MusicToolMenuWidget::m_menu.
void MusicArtistListQueryCategoryPopWidget::setCategory (const QString & server, QObject * obj)
Set current category by input server.
Definition at line 63 of file musicartistlistquerycategorypopwidget.cpp.
References MusicCategoryConfigManager::ArtistList, MusicUtils::Widget::generateVScrollAreaFormat(), MusicToolMenuWidget::m_containWidget, MusicUIObject::MQSSBackgroundStyle17, MusicCategoryConfigManager::readCategoryData(), MusicCategoryConfigManager::readConfig(), and MusicArtistListQueryCategoryItem::setCategory().
Referenced by MusicArtistListQueryWidget::createArtistListItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerycategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerycategorypopwidget.cpp