TTKMusicplayer: MusicSoundTouchWidget Class Reference
MusicSoundTouchWidget Class Reference
The class of the sound touch widget.
#include <musicsoundtouchwidget.h>
Public Slots
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicSoundTouchWidget (QWidget *parent=nullptr)
virtual ~MusicSoundTouchWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void setText (const QString &text)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicSoundTouchWidget * m_ui
QProcess * m_process
MusicAudioRecorderCore * m_recordCore
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Private Slots
void onRecordStart ()
void onRecordStop ()
void onRecordPlay ()
void tempoSliderValueChanged (int value)
void pitchSliderValueChanged (int value)
void rateSliderValueChanged (int value)
void openWavButtonClicked ()
void transformButtonClicked ()
void finished (int code)
Detailed Description
The class of the sound touch widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicsoundtouchwidget.h.
Constructor & Destructor Documentation
MusicSoundTouchWidget::MusicSoundTouchWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicsoundtouchwidget.cpp.
References finished(), MusicObject::getAppDir(), m_process, m_recordCore, m_ui, MusicUIObject::MPushButtonStyle04, MusicUIObject::MSliderStyle01, MusicUIObject::MToolButtonStyle04, MUSIC_RECORD_FILE, onRecordPlay(), onRecordStart(), onRecordStop(), openWavButtonClicked(), pitchSliderValueChanged(), rateSliderValueChanged(), setText(), tempoSliderValueChanged(), and transformButtonClicked().
MusicSoundTouchWidget::~MusicSoundTouchWidget () virtual
Definition at line 76 of file musicsoundtouchwidget.cpp.
References m_process, m_recordCore, M_SINGLE_MANAGER_PTR, and m_ui.
Member Function Documentation
void MusicSoundTouchWidget::finished (int code) private slot
Transform finished.
Definition at line 167 of file musicsoundtouchwidget.cpp.
References MusicMessageBox::exec(), m_ui, and MusicMessageBox::setText().
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::onRecordPlay () private slot
Recorder play play.
Definition at line 118 of file musicsoundtouchwidget.cpp.
References MusicObject::getAppDir(), and MUSIC_RECORD_OUT_FILE.
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::onRecordStart () private slot
Recorder play start.
Definition at line 98 of file musicsoundtouchwidget.cpp.
References MusicAudioRecorderCore::error(), m_recordCore, m_ui, and MusicAudioRecorderCore::onRecordStart().
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::onRecordStop () private slot
Recorder play stop.
Definition at line 110 of file musicsoundtouchwidget.cpp.
References m_recordCore, m_ui, and MusicAudioRecorderCore::onRecordStop().
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::openWavButtonClicked () private slot
Load wav file button clicked.
Definition at line 139 of file musicsoundtouchwidget.cpp.
References MusicUtils::Widget::getOpenFileDialog(), m_recordCore, m_ui, MusicAudioRecorderCore::setFileName(), and setText().
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::pitchSliderValueChanged (int value) private slot
Set pitch slider value.
Definition at line 129 of file musicsoundtouchwidget.cpp.
References m_ui.
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::rateSliderValueChanged (int value) private slot
Set rate slider value.
Definition at line 134 of file musicsoundtouchwidget.cpp.
References m_ui.
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::setText (const QString & text) protected
Set label text.
Definition at line 179 of file musicsoundtouchwidget.cpp.
References MusicUtils::Widget::elidedText(), and m_ui.
Referenced by MusicSoundTouchWidget(), and openWavButtonClicked().
void MusicSoundTouchWidget::show () slot
Override show function.
Definition at line 84 of file musicsoundtouchwidget.cpp.
References MusicMessageBox::exec(), m_ui, MAKE_SOUNDTOUCH_FULL, MusicAbstractMoveWidget::setBackgroundPixmap(), and MusicMessageBox::setText().
void MusicSoundTouchWidget::tempoSliderValueChanged (int value) private slot
Set tempo slider value.
Definition at line 124 of file musicsoundtouchwidget.cpp.
References m_ui.
Referenced by MusicSoundTouchWidget().
void MusicSoundTouchWidget::transformButtonClicked () private slot
Transform button clicked.
Definition at line 150 of file musicsoundtouchwidget.cpp.
References MusicAudioRecorderCore::addWavHeader(), MusicObject::getAppDir(), MusicAudioRecorderCore::getFileName(), key, m_process, m_recordCore, m_ui, MAKE_SOUNDTOUCH_FULL, MUSIC_RECORD_FILE, MUSIC_RECORD_IN_FILE, and MUSIC_RECORD_OUT_FILE.
Referenced by MusicSoundTouchWidget().
Member Data Documentation
QProcess* MusicSoundTouchWidget::m_process protected
Definition at line 98 of file musicsoundtouchwidget.h.
Referenced by MusicSoundTouchWidget(), transformButtonClicked(), and ~MusicSoundTouchWidget().
MusicAudioRecorderCore* MusicSoundTouchWidget::m_recordCore protected
Definition at line 99 of file musicsoundtouchwidget.h.
Referenced by MusicSoundTouchWidget(), onRecordStart(), onRecordStop(), openWavButtonClicked(), transformButtonClicked(), and ~MusicSoundTouchWidget().
Ui::MusicSoundTouchWidget* MusicSoundTouchWidget::m_ui protected
Definition at line 97 of file musicsoundtouchwidget.h.
Referenced by finished(), MusicSoundTouchWidget(), onRecordStart(), onRecordStop(), openWavButtonClicked(), pitchSliderValueChanged(), rateSliderValueChanged(), setText(), show(), tempoSliderValueChanged(), transformButtonClicked(), and ~MusicSoundTouchWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundtouchwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundtouchwidget.cpp