TTKMusicplayer: QAlgorithm::Des Class Reference
QAlgorithm::Des Class Reference
The class of the des wrapper.
#include <deswrapper.h>
Public Types
enum Mode { Encrypt = 0, Decrypt = 1 }
Public Member Functions
Des ()
QByteArray encrypt (const QByteArray &in, const QByteArray &key)
QByteArray decrypt (const QByteArray &in, const QByteArray &key)
Detailed Description
The class of the des wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file deswrapper.h.
Member Enumeration Documentation
enum QAlgorithm::Des::Mode
Enumerator
Encrypt
Decrypt
Definition at line 34 of file deswrapper.h.
Constructor & Destructor Documentation
QAlgorithm::Des::Des ()
Object contsructor.
Definition at line 344 of file deswrapper.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
QByteArray QAlgorithm::Des::decrypt (const QByteArray & in, const QByteArray & key)
Decrypt des by input.
Definition at line 361 of file deswrapper.cpp.
References QAlgorithm::base64Decode(), Decrypt, and TTK_D.
QByteArray QAlgorithm::Des::encrypt (const QByteArray & in, const QByteArray & key)
Encrypt des by input.
Definition at line 349 of file deswrapper.cpp.
References QAlgorithm::base64Encode(), Encrypt, and TTK_D.
Referenced by MusicKWQueryInterface::readFromMusicLLAttribute(), and MusicKWQueryMovieRequest::readFromMusicMVAttribute().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/deswrapper.h
TTKThirdParty/TTKExtras/qalgorithm/deswrapper.cpp