TTKMusicplayer: MusicKGQueryPlaylistRequest Class Reference
MusicKGQueryPlaylistRequest Class Reference
The class of kugou query playlist download data from net.
#include <musickgqueryplaylistrequest.h>
Public Slots
virtual void downLoadFinished () override
void getDetailsFinished ()
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKGQueryPlaylistRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &playlist) override
virtual void startToPage (int offset) override
virtual void startToSearch (const QString &playlist) override
virtual void getPlaylistInfo (MusicResultsItem &item) override
Public Member Functions inherited from MusicQueryPlaylistRequest
MusicQueryPlaylistRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSingleSearch (const QString &text)
void setQueryQuality (const QString &qual)
QString getQueryQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getQueryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
int getPageSize () const
int getTotalSize () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryPlaylistRequest
void createPlaylistItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 getUrlFileSize (const QString &url)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicKGQueryInterface
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &hash)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongLrcAndPicture (MusicObject::MusicSongInformation *info)
void readFromMusicSongAlbumInfo (MusicResultsItem *info, const QString &album)
Detailed Description
The class of kugou query playlist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musickgqueryplaylistrequest.h.
Constructor & Destructor Documentation
MusicKGQueryPlaylistRequest::MusicKGQueryPlaylistRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musickgqueryplaylistrequest.cpp.
References MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_KG_INTERFACE.
Member Function Documentation
void MusicKGQueryPlaylistRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 112 of file musickgqueryplaylistrequest.cpp.
References MusicQueryPlaylistRequest::createPlaylistItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractQueryRequest::downLoadFinished(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicAbstractNetwork::m_reply, MusicResultsItem::m_tags, MusicPagingRequest::m_totalSize, MusicResultsItem::m_updateTime, QJson::Parser::parse(), STRING_NULL, TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToPage().
void MusicKGQueryPlaylistRequest::getDetailsFinished () slot
Download details data from net finished.
Definition at line 161 of file musickgqueryplaylistrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_discNumber, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractQueryRequest::m_musicSongInfos, MusicResultsItem::m_nickName, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_queryQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicKGQueryInterface::readFromMusicSongAlbumInfo(), MusicKGQueryInterface::readFromMusicSongAttribute(), MusicKGQueryInterface::readFromMusicSongLrcAndPicture(), STRING_NULL, TTK_LOGGER_INFO, TTK_NETWORK_QUERY_CHECK, and TTKObject_cast.
Referenced by startToSearch().
void MusicKGQueryPlaylistRequest::getPlaylistInfo (MusicResultsItem & item) override virtual
Get playlist info.
Implements MusicQueryPlaylistRequest.
Definition at line 62 of file musickgqueryplaylistrequest.cpp.
References MusicAbstractNetwork::downLoadFinished(), KG_PLAYLIST_DETAIL_URL, MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicObject::syncNetworkQueryForGet(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
void MusicKGQueryPlaylistRequest::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicPagingRequest.
Definition at line 23 of file musickgqueryplaylistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KG_PLAYLIST_URL, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryText, MusicAbstractNetwork::m_reply, MusicPagingRequest::m_totalSize, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicKGQueryPlaylistRequest::startToSearch (QueryType type, const QString & playlist) override virtual
Start to Search data from name and type.
Implements MusicAbstractQueryRequest.
Definition at line 10 of file musickgqueryplaylistrequest.cpp.
References MusicAbstractQueryRequest::m_queryText, MusicAbstractQueryRequest::MusicQuery, and startToPage().
void MusicKGQueryPlaylistRequest::startToSearch (const QString & playlist) override virtual
Start to Search data.
Implements MusicQueryPlaylistRequest.
Definition at line 43 of file musickgqueryplaylistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), getDetailsFinished(), KG_PLAYLIST_INFO_URL, MusicAbstractNetwork::m_manager, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryplaylistrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryplaylistrequest.cpp