TTKMusicplayer: MusicWebMVRadioFoundWidget Class Reference
MusicWebMVRadioFoundWidget Class Reference
The class of the music mv found widget.
#include <musicwebmvradiofoundwidget.h>
Public Slots
void createCategoryItem (const MusicResultsItem &item)
void currentRadioClicked (const MusicResultsItem &item)
void backToMainMenuClicked ()
void categoryChanged (const MusicResultsCategoryItem &category)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicWebMVRadioFoundWidget (QWidget *parent=0)
virtual ~MusicWebMVRadioFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
void initWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Attributes
bool m_firstInit
QGridLayout * m_gridLayout
MusicWebMVRadioInfoWidget * m_infoWidget
MusicWebMVRadioFoundCategoryPopWidget * m_categoryButton
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the music mv found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 86 of file musicwebmvradiofoundwidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioFoundWidget::MusicWebMVRadioFoundWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 106 of file musicwebmvradiofoundwidget.cpp.
References createCategoryItem(), m_categoryButton, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, m_infoWidget, and MusicFoundAbstractWidget::m_mainWindow.
MusicWebMVRadioFoundWidget::~MusicWebMVRadioFoundWidget () virtual
Definition at line 123 of file musicwebmvradiofoundwidget.cpp.
References m_categoryButton, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, and m_infoWidget.
Member Function Documentation
void MusicWebMVRadioFoundWidget::backToMainMenuClicked () slot
Set current index to main menu page.
Definition at line 232 of file musicwebmvradiofoundwidget.cpp.
References MusicFoundAbstractWidget::m_container, and PLAYLIST_WINDOW_INDEX_0.
Referenced by currentRadioClicked().
void MusicWebMVRadioFoundWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 237 of file musicwebmvradiofoundwidget.cpp.
References MusicWebMVRadioFoundCategoryPopWidget::closeMenu(), m_categoryButton, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, MusicResultsCategoryItem::m_id, MusicResultsCategoryItem::m_name, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_songNameFull, MusicDownLoadQueryThreadAbstract::OtherQuery, and MusicDownLoadQueryThreadAbstract::startToSearch().
void MusicWebMVRadioFoundWidget::createCategoryItem (const MusicResultsItem & item) slot
Create the current category item.
Definition at line 169 of file musicwebmvradiofoundwidget.cpp.
References currentRadioClicked(), LINE_SPACING_SIZE, m_categoryButton, MusicFoundAbstractWidget::m_container, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_statusLabel, MusicUIObject::MColorStyle06, MusicUIObject::MScrollBarStyle01, MStatic_cast, MUSIC_MOVIE_RADIO, MusicWebMVRadioFoundCategoryPopWidget::setCategory(), and MusicWebMVRadioFoundItemWidget::setMusicResultsItem().
Referenced by MusicWebMVRadioFoundWidget().
void MusicWebMVRadioFoundWidget::currentRadioClicked (const MusicResultsItem & item) slot
Current item clicked.
Definition at line 221 of file musicwebmvradiofoundwidget.cpp.
References backToMainMenuClicked(), MusicFoundAbstractWidget::m_container, MusicResultsItem::m_id, m_infoWidget, PLAYLIST_WINDOW_INDEX_1, and MusicWebMVRadioInfoWidget::setSongName().
Referenced by createCategoryItem().
QString MusicWebMVRadioFoundWidget::getClassName () static
Get class object name.
Definition at line 131 of file musicwebmvradiofoundwidget.cpp.
void MusicWebMVRadioFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 147 of file musicwebmvradiofoundwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, m_infoWidget, MusicFoundAbstractWidget::m_resizeWidgets, and MusicWebMVRadioInfoWidget::resizeWindow().
void MusicWebMVRadioFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 136 of file musicwebmvradiofoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicDownLoadQueryThreadAbstract::OtherQuery, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicRightAreaWidget::musicFunctionClicked().
void MusicWebMVRadioFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 142 of file musicwebmvradiofoundwidget.cpp.
Member Data Documentation
MusicWebMVRadioFoundCategoryPopWidget* MusicWebMVRadioFoundWidget::m_categoryButton protected
Definition at line 138 of file musicwebmvradiofoundwidget.h.
Referenced by categoryChanged(), createCategoryItem(), MusicWebMVRadioFoundWidget(), and ~MusicWebMVRadioFoundWidget().
bool MusicWebMVRadioFoundWidget::m_firstInit protected
Definition at line 135 of file musicwebmvradiofoundwidget.h.
Referenced by createCategoryItem(), and MusicWebMVRadioFoundWidget().
QGridLayout* MusicWebMVRadioFoundWidget::m_gridLayout protected
Definition at line 136 of file musicwebmvradiofoundwidget.h.
Referenced by categoryChanged(), createCategoryItem(), MusicWebMVRadioFoundWidget(), resizeWindow(), and ~MusicWebMVRadioFoundWidget().
MusicWebMVRadioInfoWidget* MusicWebMVRadioFoundWidget::m_infoWidget protected
Definition at line 137 of file musicwebmvradiofoundwidget.h.
Referenced by currentRadioClicked(), MusicWebMVRadioFoundWidget(), resizeWindow(), and ~MusicWebMVRadioFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradiofoundwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradiofoundwidget.cpp