TTKMusicPlayer: TTK::Number Namespace Reference
TTK::Number Namespace Reference
Functions
TTK_MODULE_EXPORT QString sizeByteToLabel (qint64 size)
TTK_MODULE_EXPORT QString sizeByteToLabel (const QString &duration, int bitrate)
TTK_MODULE_EXPORT QString speedByteToLabel (qint64 size)
TTK_MODULE_EXPORT int bitrateToNormal (int bitrate)
TTK_MODULE_EXPORT TTK::QueryQuality bitrateToLevel (int bitrate)
TTK_MODULE_EXPORT TTK::QueryQuality bitrateToLevel (const QString &bitrate)
TTK_MODULE_EXPORT void bitrateToQuality (TTK::QueryQuality level, QString &bitrate, QColor &color)
Function Documentation
TTK::QueryQuality TTK::Number::bitrateToLevel (int bitrate)
Transfrom bitrate to level.
Definition at line 128 of file musicnumberutils.cpp.
References TTK_BN_128, TTK_BN_192, and TTK_BN_320.
Referenced by MusicSongCheckToolsQualityTableWidget::addCellItems(), bitrateToLevel(), MusicFileInformationWidget::initialize(), and MusicQualityWidget::updateQuality().
TTK::QueryQuality TTK::Number::bitrateToLevel (const QString & bitrate)
Transfrom bitrate to level.
Definition at line 152 of file musicnumberutils.cpp.
References bitrateToLevel(), and TTK_SPACE.
int TTK::Number::bitrateToNormal (int bitrate)
Transfrom bitrate to normal.
Definition at line 100 of file musicnumberutils.cpp.
References TTK_BN_0, TTK_BN_1000, TTK_BN_128, TTK_BN_192, TTK_BN_32, TTK_BN_320, and TTK_BN_64.
Referenced by parseSongPropertyV1(), and parseSongPropertyV2().
void TTK::Number::bitrateToQuality (TTK::QueryQuality level, QString & bitrate, QColor & color)
Transfrom bitrate to quality.
Definition at line 168 of file musicnumberutils.cpp.
Referenced by MusicSongCheckToolsQualityTableWidget::addCellItems(), and MusicFileInformationWidget::initialize().
QString TTK::Number::sizeByteToLabel (qint64 size)
Transform value to size label value.
Definition at line 31 of file musicnumberutils.cpp.
References size2Number(), TTK_SN_GB2B, TTK_SN_KB2B, TTK_SN_MB2B, and TTK_SN_TB2B.
Referenced by MusicCloudManagerTableWidget::addCellItem(), MusicMobileSongsTableWidget::addCellItems(), MusicDownloadBatchTableItem::currentQualityChanged(), MusicDownloadDataRequest::downloadProgress(), MusicAbstractQueryRequest::fetchUrlPathSize(), MusicFileInformationWidget::initialize(), MusicSongsListItemInfoWidget::initialize(), MusicSong::MusicSong(), ReqKGInterface::parseFromMovieProperty(), ReqBLInterface::parseFromMovieProperty(), ReqLQInterface::parseFromSongProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), MusicCloudFileInformationWidget::setFileInformation(), sizeByteToLabel(), MusicCloudManagerWidget::updataSizeLabel(), and MusicCloudUploadTableWidget::uploadFileError().
QString TTK::Number::sizeByteToLabel (const QString & duration, int bitrate)
Transform value to size label value.
Definition at line 61 of file musicnumberutils.cpp.
References TTKTime::formatDuration(), sizeByteToLabel(), and TTK_DEFAULT_STR.
QString TTK::Number::speedByteToLabel (qint64 size)
Transform value to speed label value.
Definition at line 70 of file musicnumberutils.cpp.
References size2Number(), TTK_SN_GB2B, TTK_SN_KB2B, TTK_SN_MB2B, and TTK_SN_TB2B.
Referenced by MusicDownloadDataRequest::updateDownloadSpeed().