TTKMusicplayer: DlnaFileServer Class Reference
DlnaFileServer Class Reference
The class of the dlna file server.
#include <dlnafileserver.h>
Public Member Functions
DlnaFileServer (QObject *parent=nullptr)
void start ()
void setPrefixPath (const QString &path)
QString getLocalAddress () const
Private Slots
void handleRequest (QHttpRequest *request, QHttpResponse *response)
Detailed Description
The class of the dlna file server.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file dlnafileserver.h.
Constructor & Destructor Documentation
DlnaFileServer::DlnaFileServer (QObject * parent = nullptr)
Definition at line 35 of file dlnafileserver.cpp.
References handleRequest(), TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
QString DlnaFileServer::getLocalAddress () const
Definition at line 55 of file dlnafileserver.cpp.
Referenced by MusicSongDlnaTransferWidget::musicPlay().
void DlnaFileServer::handleRequest (QHttpRequest * request, QHttpResponse * response) private slot
Definition at line 67 of file dlnafileserver.cpp.
References QHttpResponse::end(), name, QHttpRequest::path, QHttpResponse::setHeader(), TTK_D, and QHttpResponse::writeHead().
Referenced by DlnaFileServer().
void DlnaFileServer::setPrefixPath (const QString & path)
Definition at line 49 of file dlnafileserver.cpp.
References TTK_D.
Referenced by MusicSongDlnaTransferWidget::musicPlay().
void DlnaFileServer::start ()
Definition at line 43 of file dlnafileserver.cpp.
References TTK_D.
Referenced by MusicSongDlnaTransferWidget::MusicSongDlnaTransferWidget().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/dlnafileserver.h
TTKThirdParty/TTKExtras/qdlna/dlnafileserver.cpp