TTKMusicplayer: MusicApplication Class Reference
MusicApplication Class Reference
The class of the app main widget.
#include <musicapplication.h>
Public Slots
void quitWindowClose ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void stateChanged ()
void showCurrentSong ()
void musicStatePlay ()
void musicStateStop ()
void musicPlayPrevious ()
void musicPlayNext ()
void musicPlayOrder ()
void musicPlayRandom ()
void musicPlaylistLoop ()
void musicPlayOneLoop ()
void musicPlayOnce ()
void musicVolumeMute ()
void musicVolumeChanged (int volume)
void musicImportSongs ()
void musicImportSongsOnlyFile ()
void musicImportSongsOnlyDir ()
void musicImportSongsItemList ()
void musicExportSongsItemList (int index)
void musicPlaySort (int row)
void musicPlayedIndex (int row)
void musicPlayIndex (int row)
void musicPlayIndex (int row, int col)
void musicPlayIndexClicked (int row, int col)
void musicPlayAnyTimeAt (int posValue)
void musicActionVolumeSub ()
void musicActionVolumePlus ()
void musicSetting ()
void musicCurrentPlayLocation ()
void musicAddSongToLovestList ()
void musicAddSongToLovestList (bool state)
void musicWindowConciseChanged ()
void musicEnhancedMusicChanged (int type)
void musicCreateRightMenu ()
void applySettingParameter ()
void setLoveDeleteItemAt (const QString &path, bool current)
void setDeleteItemAt (const QStringList &path, bool remove, bool current, int toolIndex)
void musicCurrentLrcUpdated ()
void resetCurrentSongLrcIndex ()
void updateCurrentTime (qint64 pos)
void setPlaySongChanged (int index)
void getCurrentPlaylist (QStringList &list)
Public Member Functions
MusicApplication (QWidget *parent=nullptr)
~MusicApplication ()
QString getCurrentFileName () const
QString getCurrentFilePath () const
bool checkMusicListCurrentIndex () const
void musicLoadCurrentSongLrc ()
void radioExecuteOuter (const QString &path)
void musicImportSongsPathOuter (const QStringList &files, bool play)
QString musicDownloadContains (bool &contains) const
bool musicLovestContains () const
bool musicLovestContains (int index) const
void updateCurrentArtist ()
bool isPlaying () const
qint64 duration () const
MusicObject::PlayMode getPlayMode () const
Public Member Functions inherited from MusicAbstractMoveResizeWidget
MusicAbstractMoveResizeWidget (QWidget *parent=nullptr)
Static Public Member Functions
static MusicApplication * instance ()
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
virtual void closeEvent (QCloseEvent *event) override
virtual void dragEnterEvent (QDragEnterEvent *event) override
virtual void dragMoveEvent (QDragMoveEvent *event) override
virtual void dropEvent (QDropEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual bool eventFilter (QObject *object, QEvent *event) override
void musicImportSongsPath (const QStringList &files)
void setMusicPlayIndex ()
void readSystemConfigFromFile ()
void writeSystemConfigToFile ()
Protected Member Functions inherited from MusicAbstractMoveResizeWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void sizeDirection ()
void moveDirection ()
Private Attributes
Ui::MusicApplication * m_ui
bool m_quitWindowClose
int m_currentMusicSongTreeIndex
MusicPlayer * m_musicPlayer
MusicPlaylist * m_musicPlaylist
MusicSongsSummariziedWidget * m_musicSongTreeWidget
MusicBottomAreaWidget * m_bottomAreaWidget
MusicTopAreaWidget * m_topAreaWidget
MusicRightAreaWidget * m_rightAreaWidget
MusicLeftAreaWidget * m_leftAreaWidget
MusicApplicationModule * m_applicationObject
Static Private Attributes
static MusicApplication * m_instance = nullptr
Friends
class MusicApplicationMPRISPlayer
Additional Inherited Members
Public Types inherited from MusicAbstractMoveResizeWidget
enum Direction {
Direction_No = 0, Direction_Left = 1, Direction_Top = 2, Direction_Right = 4,
Direction_Bottom = 8, Direction_LeftTop = Direction_Left + Direction_Top, Direction_LeftBottom = Direction_Left + Direction_Bottom, Direction_RightTop = Direction_Right + Direction_Top,
Direction_RightBottom = Direction_Right + Direction_Bottom
}
Protected Attributes inherited from MusicAbstractMoveResizeWidget
MoveResizeData m_struct
Direction m_direction
Detailed Description
The class of the app main widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 42 of file musicapplication.h.
Constructor & Destructor Documentation
MusicApplication::MusicApplication (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 30 of file musicapplication.cpp.
References APP_WINDOW_INDEX_0, DEFAULT_LOWER_LEVEL, durationChanged(), G_HOTKEY_PTR, G_SETTING_PTR, m_applicationObject, m_bottomAreaWidget, m_currentMusicSongTreeIndex, m_instance, m_leftAreaWidget, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, m_quitWindowClose, m_rightAreaWidget, m_topAreaWidget, m_ui, MT_MS, MusicTopAreaWidget::musicBackgroundAnimationChanged(), MusicObject::PM_PlayOrder, positionChanged(), readSystemConfigFromFile(), MusicSettingManager::ScreenSize, MusicPlaylist::setPlaybackMode(), MusicLeftAreaWidget::setupUi(), MusicTopAreaWidget::setupUi(), MusicBottomAreaWidget::setupUi(), MusicRightAreaWidget::setupUi(), showCurrentSong(), stateChanged(), WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
MusicApplication::~MusicApplication ()
Definition at line 99 of file musicapplication.cpp.
References m_applicationObject, m_bottomAreaWidget, m_leftAreaWidget, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, m_rightAreaWidget, m_topAreaWidget, and m_ui.
Member Function Documentation
void MusicApplication::applySettingParameter () slot
Apply settings parameters.
Definition at line 806 of file musicapplication.cpp.
References MusicApplicationModule::applySettingParameter(), MusicBottomAreaWidget::applySettingParameter(), MusicRightAreaWidget::applySettingParameter(), m_applicationObject, m_bottomAreaWidget, and m_rightAreaWidget.
bool MusicApplication::checkMusicListCurrentIndex () const
Check current list index is -1 or not.
Definition at line 151 of file musicapplication.cpp.
References MusicPlaylist::currentIndex(), DEFAULT_LOWER_LEVEL, and m_musicPlaylist.
Referenced by MusicDownloadStatusModule::checkLrcValid(), and musicLoadCurrentSongLrc().
void MusicApplication::closeEvent (QCloseEvent * event) override protected virtual
Definition at line 960 of file musicapplication.cpp.
References MusicBottomAreaWidget::getSystemCloseConfig(), m_bottomAreaWidget, quitWindowClose(), MusicBottomAreaWidget::showMessage(), and MusicBottomAreaWidget::systemTrayIsVisible().
void MusicApplication::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 1003 of file musicapplication.cpp.
References musicCreateRightMenu().
void MusicApplication::dragEnterEvent (QDragEnterEvent * event) override protected virtual
Definition at line 975 of file musicapplication.cpp.
void MusicApplication::dragMoveEvent (QDragMoveEvent * event) override protected virtual
Definition at line 982 of file musicapplication.cpp.
void MusicApplication::dropEvent (QDropEvent * event) override protected virtual
Definition at line 989 of file musicapplication.cpp.
References musicImportSongsPath().
qint64 MusicApplication::duration () const
Get current player duration.
Definition at line 258 of file musicapplication.cpp.
References MusicPlayer::duration(), and m_musicPlayer.
Referenced by MusicLrcAnalysis::setLrcData().
void MusicApplication::durationChanged (qint64 duration) slot
Set current player duration.
Definition at line 293 of file musicapplication.cpp.
References m_ui, MusicTime::msecTime2LabelJustified(), and musicLoadCurrentSongLrc().
Referenced by MusicApplication(), and showCurrentSong().
void MusicApplication::enterEvent (QEvent * event) override protected virtual
Definition at line 1012 of file musicapplication.cpp.
bool MusicApplication::eventFilter (QObject * object, QEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicAbstractMoveResizeWidget.
Definition at line 1049 of file musicapplication.cpp.
References MusicAbstractMoveResizeWidget::eventFilter(), and m_ui.
QString MusicApplication::getCurrentFileName () const
Get current file name.
Definition at line 117 of file musicapplication.cpp.
References MusicPlaylist::currentIndex(), MusicPlaylist::currentMediaPath(), MusicSongsSummariziedWidget::getMusicItemList(), m_currentMusicSongTreeIndex, m_musicPlaylist, m_musicSongTreeWidget, and MusicSongsSummariziedWidget::mapSongIndexByFilePath().
Referenced by MusicDownloadStatusModule::checkLrcValid(), musicCurrentLrcUpdated(), musicLoadCurrentSongLrc(), and showCurrentSong().
QString MusicApplication::getCurrentFilePath () const
Get current file path.
Definition at line 134 of file musicapplication.cpp.
References MusicPlaylist::currentIndex(), MusicPlaylist::currentMediaPath(), MusicSongsSummariziedWidget::getMusicItemList(), m_currentMusicSongTreeIndex, m_musicPlaylist, m_musicSongTreeWidget, and MusicSongsSummariziedWidget::mapSongIndexByFilePath().
void MusicApplication::getCurrentPlaylist (QStringList & list) slot
Get current play list.
Definition at line 937 of file musicapplication.cpp.
References MusicFunctionToolBoxWidget::currentIndex(), MusicSongsSummariziedWidget::getMusicSongsFileName(), and m_musicSongTreeWidget.
Referenced by MusicToolSetsWidget::itemHasClicked(), and MusicApplicationModule::musicTimerWidget().
MusicObject::PlayMode MusicApplication::getPlayMode () const
Get current play mode.
Definition at line 263 of file musicapplication.cpp.
References m_musicPlaylist, and MusicPlaylist::playbackMode().
Referenced by MusicApplicationMPRISPlayer::loopStatus(), MusicLrcMakerWidget::MusicLrcMakerWidget(), and MusicApplicationMPRISPlayer::shuffle().
MusicApplication * MusicApplication::instance () static
Get class object instance.
Definition at line 112 of file musicapplication.cpp.
References m_instance.
Referenced by MusicSongsSummariziedWidget::addNetMusicSongToList(), MusicSongsSummariziedWidget::addSongToLovestListAt(), MusicSongsSummariziedWidget::addSongToPlaylist(), MusicLrcMakerWidget::backToMakeLrcWidget(), MusicPlayedListPopWidget::cellDoubleClicked(), MusicSongsSummariziedWidget::contextMenuEvent(), MusicLrcMakerWidget::createCurrentLine(), MusicLrcMakerWidget::createFirstWidget(), MusicTopAreaWidget::createRemoteWidget(), MusicBottomAreaWidget::createSystemTrayIcon(), MusicLrcMakerWidget::createThirdWidget(), MusicLrcContainerForDesktop::creatToolBarWidget(), MusicSongsListPlayWidget::currentDownloadStateClicked(), MusicSongsListPlayWidget::currentLoveStateClicked(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItemAll(), MusicSongsSummariziedWidget::deleteRowItems(), MusicTopAreaWidget::drawWindowBackgroundRectString(), MusicSongsToolBoxTopWidget::exportSongsItemList(), MusicLrcMakerWidget::firstWidgetStateButtonClicked(), MusicRightAreaWidget::functionParameterInit(), MusicBottomAreaWidget::iconActivated(), MusicPlayBackModePopWidget::initWidget(), MusicSongsListTableWidget::itemCellClicked(), MusicSongsListTableWidget::itemCellEntered(), MusicToolSetsWidget::itemHasClicked(), MusicBottomAreaWidget::lrcWidgetShowFullScreen(), MusicVideoPlayWidget::mediaUrlChanged(), MusicSongsSummariziedWidget::musicAddNewDir(), MusicSongsSummariziedWidget::musicAddNewFiles(), MusicApplicationMPRISPlayer::MusicApplicationMPRISPlayer(), MusicRightAreaWidget::musicContainerForWallpaperClicked(), MusicLeftAreaWidget::musicDownloadSongFinished(), MusicSongsSummariziedWidget::musicImportSongsOnlyDir(), MusicSongsSummariziedWidget::musicImportSongsOnlyFile(), MusicSongsSummariziedWidget::musicListSongSortBy(), MusicLrcFloatPlayWidget::MusicLrcFloatPlayWidget(), MusicLrcMakerWidget::MusicLrcMakerWidget(), MusicRemoteWidget::MusicRemoteWidget(), MusicApplicationModule::musicResetWindow(), MusicApplicationModule::musicSetWindowToTop(), MusicRightAreaWidget::musicSongCommentsWidget(), MusicSongsListFunctionWidget::MusicSongsListFunctionWidget(), MusicSongsListPlayWidget::MusicSongsListPlayWidget(), MusicSongsListTableWidget::MusicSongsListTableWidget(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), MusicLrcFloatPlayWidget::musicStatePlay(), MusicApplicationModule::musicTimerWidget(), MusicTopAreaWidget::MusicTopAreaWidget(), MusicApplicationModule::musicVersionUpdate(), MusicRightAreaWidget::musicVideoActiveWindow(), MusicDownloadResetWidget::openFileLocation(), MusicToastLabel::popup(), MusicApplicationMPRISRoot::Quit(), MusicApplicationMPRISRoot::Raise(), MusicLrcMakerWidget::reMakeButtonClicked(), MusicLrcMakerWidget::resetToOriginPlayMode(), MusicLrcFloatPlayWidget::setCurrentPlayState(), MusicLrcMakerWidget::setCurrentSecondWidget(), MusicLrcMakerWidget::setCurrentThirdWidget(), MusicAbstractSongsListTableWidget::setDeleteItemAll(), MusicPlayedListPopWidget::setDeleteItemAt(), MusicSongsSummariziedWidget::setDeleteItemAt(), MusicLrcAnalysis::setLrcData(), MusicPlayedListPopWidget::setPlaylistEmpty(), MusicDownloadMgmtWidget::setSongName(), MusicLeftAreaWidget::setupUi(), MusicTopAreaWidget::setupUi(), MusicRightAreaWidget::setupUi(), MusicBottomAreaWidget::setWindowConcise(), MusicRightAreaWidget::setWindowLrcTypeChanged(), MusicApplicationModule::sideAnimationByOff(), MusicApplicationModule::sideAnimationByOn(), MusicApplicationModule::sideAnimationReset(), MusicLrcMakerWidget::thirdWidgetStateButtonClicked(), MusicTimerAutoModule::timeout(), MusicLrcMakerWidget::timeSliderValueChanged(), MusicSongsSummariziedWidget::updateCurrentIndex(), MusicApplicationModule::windowCloseAnimation(), and MusicApplicationModule::windowCloseAnimationFinished().
bool MusicApplication::isPlaying () const
Get current play state.
Definition at line 253 of file musicapplication.cpp.
References MusicPlayer::isPlaying(), and m_musicPlayer.
Referenced by MusicVideoPlayWidget::mediaUrlChanged(), musicStatePlay(), musicStateStop(), positionChanged(), readSystemConfigFromFile(), MusicLrcMakerWidget::setCurrentSecondWidget(), MusicPlayedListPopWidget::setDeleteItemAt(), MusicBottomAreaWidget::setWindowConcise(), showCurrentSong(), and updateCurrentTime().
void MusicApplication::leaveEvent (QEvent * event) override protected virtual
Definition at line 1019 of file musicapplication.cpp.
References m_applicationObject, and MusicApplicationModule::sideAnimationByOn().
void MusicApplication::mouseDoubleClickEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicAbstractMoveResizeWidget.
Definition at line 1037 of file musicapplication.cpp.
References G_SETTING_PTR, m_ui, MusicAbstractMoveResizeWidget::mouseDoubleClickEvent(), and MusicSettingManager::WindowConciseMode.
void MusicApplication::mousePressEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicAbstractMoveResizeWidget.
Definition at line 1025 of file musicapplication.cpp.
References m_ui, and MusicAbstractMoveResizeWidget::mousePressEvent().
void MusicApplication::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicAbstractMoveResizeWidget.
Definition at line 1031 of file musicapplication.cpp.
References m_applicationObject, MusicAbstractMoveResizeWidget::mouseReleaseEvent(), and MusicApplicationModule::sideAnimationByOn().
void MusicApplication::musicActionVolumePlus () slot
Set current player volume up.
Definition at line 643 of file musicapplication.cpp.
References m_musicPlayer, musicVolumeChanged(), and MusicPlayer::volume().
void MusicApplication::musicActionVolumeSub () slot
Set current player volume down.
Definition at line 632 of file musicapplication.cpp.
References m_musicPlayer, musicVolumeChanged(), and MusicPlayer::volume().
void MusicApplication::musicAddSongToLovestList () slot
Add music song to lovest list.
Definition at line 671 of file musicapplication.cpp.
Referenced by MusicSongsSummariziedWidget::addSongToLovestListAt(), and MusicSongsSummariziedWidget::setDeleteItemAt().
void MusicApplication::musicAddSongToLovestList (bool state) slot
Add music song to lovest list.
Definition at line 676 of file musicapplication.cpp.
References MusicPlaylist::currentItem(), MusicPlaylist::isEmpty(), m_leftAreaWidget, m_musicPlaylist, m_musicSongTreeWidget, MusicPlayItem::m_path, MusicPlayItem::m_toolIndex, MusicSongsSummariziedWidget::mapSongIndexByFilePath(), musicLovestContains(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), MusicLeftAreaWidget::musictLoveStateClicked(), and MusicToastLabel::popup().
void MusicApplication::musicCreateRightMenu () slot
Create right menu.
Definition at line 720 of file musicapplication.cpp.
References MusicUtils::Widget::adjustMenuPosition(), DEFAULT_LOWER_LEVEL, MusicSettingManager::DownloadLimitEnable, G_SETTING_PTR, MusicApplicationModule::getWindowToTop(), MusicRightAreaWidget::instance(), MusicApplicationModule::isLastedVersion(), m_applicationObject, m_musicPlaylist, m_topAreaWidget, MusicUIObject::MQSSMenuStyle02, musicImportSongsOnlyDir(), musicImportSongsOnlyFile(), musicPlaylistLoop(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayRandom(), musicSetting(), MusicPlaylist::playbackMode(), MusicObject::PM_PlaylistLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, MusicObject::PM_PlayRandom, quitWindowClose(), TTKMUSIC_VER_TIME_STR, and TTKMUSIC_VERSION_STR.
Referenced by contextMenuEvent().
void MusicApplication::musicCurrentLrcUpdated () slot
The current lrc should update, emit it.
Definition at line 899 of file musicapplication.cpp.
References MusicRightAreaWidget::checkLrcValid(), getCurrentFileName(), LRC_FILE, MusicUtils::String::lrcPrefix(), and m_rightAreaWidget.
void MusicApplication::musicCurrentPlayLocation () slot
Show current play index.
Definition at line 659 of file musicapplication.cpp.
References MusicPlaylist::currentItem(), MusicPlaylist::isEmpty(), m_musicPlaylist, m_musicSongTreeWidget, MusicPlayItem::m_path, MusicPlayItem::m_toolIndex, MusicSongsSummariziedWidget::mapSongIndexByFilePath(), and MusicSongsSummariziedWidget::playLocation().
QString MusicApplication::musicDownloadContains (bool & contains) const
Get music current song download contains.
Definition at line 198 of file musicapplication.cpp.
References MusicPlaylist::currentItem(), DEFAULT_LOWER_LEVEL, MusicSettingManager::DownloadMusicDirPath, G_SETTING_PTR, MusicSong::getMusicName(), MusicSong::getMusicType(), MusicSongsSummariziedWidget::getPlayToolIndex(), MusicPlayItem::isValid(), m_musicPlaylist, m_musicSongTreeWidget, and MusicPlayItem::m_path.
Referenced by MusicSongsListPlayWidget::currentDownloadStateClicked(), MusicLeftAreaWidget::musicDownloadSongFinished(), MusicDownloadResetWidget::openFileLocation(), MusicDownloadMgmtWidget::setSongName(), and showCurrentSong().
void MusicApplication::musicEnhancedMusicChanged (int type) slot
Set current music enhanced effect by type.
Definition at line 715 of file musicapplication.cpp.
References m_musicPlayer, MusicPlayer::setMusicEnhanced(), and TTKStatic_cast.
void MusicApplication::musicExportSongsItemList (int index) slot
Export music songs by item list.
Definition at line 544 of file musicapplication.cpp.
References MusicSongsSummariziedWidget::getMusicItemList(), MusicUtils::File::getSaveFileDialog(), m_musicSongTreeWidget, MusicPlaylistManager::setMusicSongItem(), and MusicFormats::supportPlaylistOutputFormats().
Referenced by MusicSongsToolBoxTopWidget::exportSongsItemList().
void MusicApplication::musicImportSongs () slot
Import music songs.
Definition at line 492 of file musicapplication.cpp.
References MusicUtils::Widget::adjustMenuPosition(), MusicUIObject::MQSSMenuStyle02, musicImportSongsOnlyDir(), and musicImportSongsOnlyFile().
void MusicApplication::musicImportSongsItemList () slot
Import music songs by item list.
Definition at line 532 of file musicapplication.cpp.
References MusicSongsSummariziedWidget::appendMusicItemList(), MusicPlaylistManager::getMusicSongItems(), MusicUtils::File::getOpenFilesDialog(), m_musicSongTreeWidget, and MusicFormats::supportPlaylistInputFormats().
void MusicApplication::musicImportSongsOnlyDir () slot
Import music songs by dir.
Definition at line 514 of file musicapplication.cpp.
References MusicUtils::File::getFileListByDir(), MusicUtils::File::getOpenDirectoryDialog(), musicImportSongsPath(), and MusicFormats::supportMusicFormats().
Referenced by MusicSongsSummariziedWidget::musicAddNewDir(), musicCreateRightMenu(), musicImportSongs(), and MusicSongsSummariziedWidget::musicImportSongsOnlyDir().
void MusicApplication::musicImportSongsOnlyFile () slot
Import music songs by file.
Definition at line 505 of file musicapplication.cpp.
References MusicUtils::File::getOpenFilesDialog(), musicImportSongsPath(), and MusicFormats::supportMusicInputFormats().
Referenced by MusicSongsSummariziedWidget::musicAddNewFiles(), musicCreateRightMenu(), musicImportSongs(), and MusicSongsSummariziedWidget::musicImportSongsOnlyFile().
void MusicApplication::musicImportSongsPath (const QStringList & files) protected
Import music datas into container.
Definition at line 188 of file musicapplication.cpp.
References MusicSongsSummariziedWidget::importMusicSongsByPath(), and m_musicSongTreeWidget.
Referenced by dropEvent(), musicImportSongsOnlyDir(), musicImportSongsOnlyFile(), and musicImportSongsPathOuter().
void MusicApplication::musicImportSongsPathOuter (const QStringList & files, bool play)
Import outer music datas into container.
Definition at line 178 of file musicapplication.cpp.
References m_musicPlaylist, MusicPlaylist::mediaCount(), musicImportSongsPath(), and musicPlayIndex().
Referenced by main(), and MusicApplicationMPRISPlayer::OpenUri().
void MusicApplication::musicLoadCurrentSongLrc ()
Load current song lrc.
Definition at line 156 of file musicapplication.cpp.
References checkMusicListCurrentIndex(), getCurrentFileName(), MusicRightAreaWidget::loadCurrentSongLrc(), LRC_FILE, MusicUtils::String::lrcPrefix(), m_rightAreaWidget, m_topAreaWidget, MT_S2MS, MusicTopAreaWidget::musicBackgroundThemeDownloadFinished(), and resetCurrentSongLrcIndex().
Referenced by durationChanged(), and MusicDownloadStatusModule::showDownLoadInfoFinished().
bool MusicApplication::musicLovestContains () const
Get music current song lovest contains.
Definition at line 216 of file musicapplication.cpp.
References MusicPlaylist::currentItem(), DEFAULT_LOWER_LEVEL, MusicSongsSummariziedWidget::getMusicItemList(), MusicSongsSummariziedWidget::getPlayToolIndex(), MusicPlayItem::isValid(), m_musicPlaylist, m_musicSongTreeWidget, MusicPlayItem::m_path, MusicPlayItem::m_toolIndex, MusicSongsSummariziedWidget::mapSongIndexByFilePath(), and MUSIC_LOVEST_LIST.
Referenced by MusicSongsListPlayWidget::currentLoveStateClicked(), MusicSongsListTableWidget::itemCellClicked(), MusicSongsListTableWidget::itemCellEntered(), musicAddSongToLovestList(), and showCurrentSong().
bool MusicApplication::musicLovestContains (int index) const
Get music list current song lovest contains.
Definition at line 233 of file musicapplication.cpp.
References MusicFunctionToolBoxWidget::currentIndex(), DEFAULT_LOWER_LEVEL, MusicSongsSummariziedWidget::getMusicItemList(), m_musicSongTreeWidget, and MUSIC_LOVEST_LIST.
void MusicApplication::musicPlayAnyTimeAt (int posValue) slot
Set song speed and slow by given pos.
Definition at line 624 of file musicapplication.cpp.
References m_musicPlayer, m_rightAreaWidget, MusicPlayer::setPosition(), and MusicRightAreaWidget::setSongSpeedAndSlow().
Referenced by MusicLrcMakerWidget::backToMakeLrcWidget(), MusicLrcMakerWidget::createCurrentLine(), MusicLrcMakerWidget::reMakeButtonClicked(), MusicLrcMakerWidget::setCurrentSecondWidget(), MusicLrcMakerWidget::setCurrentThirdWidget(), and MusicLrcMakerWidget::timeSliderValueChanged().
void MusicApplication::musicPlayedIndex (int row) slot
Set played list row index music to play.
Definition at line 566 of file musicapplication.cpp.
References m_musicPlayer, m_musicPlaylist, musicStatePlay(), MusicPlaylist::setCurrentIndex(), and MusicPlayer::stop().
Referenced by MusicPlayedListPopWidget::cellDoubleClicked().
void MusicApplication::musicPlayIndex (int row) slot
Set current row index music to play.
Definition at line 573 of file musicapplication.cpp.
References MusicPlaylist::clear(), m_currentMusicSongTreeIndex, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, MusicSongsSummariziedWidget::mapFilePathBySongIndex(), MusicPlaylist::setCurrentIndex(), setMusicPlayIndex(), and MusicPlayer::stop().
Referenced by MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItemAll(), MusicSongsSummariziedWidget::deleteRowItems(), musicImportSongsPathOuter(), musicPlayIndexClicked(), MusicAbstractSongsListTableWidget::setDeleteItemAll(), MusicPlayedListPopWidget::setPlaylistEmpty(), and setPlaySongChanged().
void MusicApplication::musicPlayIndex (int row, int col) slot
Set current row index music to play.
Definition at line 590 of file musicapplication.cpp.
References MusicSongsSummariziedWidget::cleanSearchResult(), MusicFunctionToolBoxWidget::currentIndex(), MusicSongsSummariziedWidget::getMusicItemList(), m_currentMusicSongTreeIndex, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, m_ui, MusicSongsSummariziedWidget::mapFilePathBySongIndex(), MusicPlaylist::mediaCount(), musicStatePlay(), MusicPlaylist::setCurrentIndex(), setMusicPlayIndex(), and MusicPlayer::stop().
void MusicApplication::musicPlayIndexClicked (int row, int col) slot
Set current row index music to play.
Definition at line 609 of file musicapplication.cpp.
References MusicFunctionToolBoxWidget::currentIndex(), MusicSongsSummariziedWidget::getMusicItemList(), m_currentMusicSongTreeIndex, m_musicSongTreeWidget, m_ui, musicPlayIndex(), and setMusicPlayIndex().
Referenced by MusicSongsSummariziedWidget::addNetMusicSongToList(), and MusicSongsSummariziedWidget::addSongToPlaylist().
void MusicApplication::musicPlaylistLoop () slot
Set current play mdoe to list loop.
Definition at line 454 of file musicapplication.cpp.
References m_musicPlaylist, m_ui, MusicObject::PM_PlaylistLoop, and MusicPlaylist::setPlaybackMode().
Referenced by musicCreateRightMenu(), readSystemConfigFromFile(), MusicLrcMakerWidget::resetToOriginPlayMode(), and MusicApplicationMPRISPlayer::setLoopStatus().
void MusicApplication::musicPlayNext () slot
Set current player to play next.
Definition at line 422 of file musicapplication.cpp.
References MusicPlaylist::isEmpty(), m_musicPlayer, m_musicPlaylist, musicStatePlay(), MusicPlaylist::playbackMode(), MusicPlayer::playNext(), MusicObject::PM_PlayRandom, MusicPlaylist::setCurrentIndex(), and MusicPlayer::stop().
Referenced by MusicApplicationMPRISPlayer::Next(), and MusicPlayedListPopWidget::setDeleteItemAt().
void MusicApplication::musicPlayOnce () slot
Set current play mdoe to just once.
Definition at line 466 of file musicapplication.cpp.
References m_musicPlaylist, m_ui, MusicObject::PM_PlayOnce, and MusicPlaylist::setPlaybackMode().
Referenced by musicCreateRightMenu(), readSystemConfigFromFile(), and MusicLrcMakerWidget::resetToOriginPlayMode().
void MusicApplication::musicPlayOneLoop () slot
Set current play mdoe to single loop.
Definition at line 460 of file musicapplication.cpp.
References m_musicPlaylist, m_ui, MusicObject::PM_PlayOneLoop, and MusicPlaylist::setPlaybackMode().
Referenced by musicCreateRightMenu(), MusicLrcMakerWidget::MusicLrcMakerWidget(), readSystemConfigFromFile(), MusicLrcMakerWidget::resetToOriginPlayMode(), and MusicApplicationMPRISPlayer::setLoopStatus().
void MusicApplication::musicPlayOrder () slot
Set current play mdoe to order.
Definition at line 442 of file musicapplication.cpp.
References m_musicPlaylist, m_ui, MusicObject::PM_PlayOrder, and MusicPlaylist::setPlaybackMode().
Referenced by musicCreateRightMenu(), readSystemConfigFromFile(), MusicLrcMakerWidget::resetToOriginPlayMode(), and MusicApplicationMPRISPlayer::setLoopStatus().
void MusicApplication::musicPlayPrevious () slot
Set current player to play previous.
Definition at line 402 of file musicapplication.cpp.
References MusicPlaylist::isEmpty(), m_musicPlayer, m_musicPlaylist, musicStatePlay(), MusicPlaylist::playbackMode(), MusicPlayer::playPrevious(), MusicObject::PM_PlayRandom, MusicPlaylist::setCurrentIndex(), and MusicPlayer::stop().
Referenced by MusicApplicationMPRISPlayer::Previous().
void MusicApplication::musicPlayRandom () slot
Set current play mdoe to random.
Definition at line 448 of file musicapplication.cpp.
References m_musicPlaylist, m_ui, MusicObject::PM_PlayRandom, and MusicPlaylist::setPlaybackMode().
Referenced by musicCreateRightMenu(), readSystemConfigFromFile(), and MusicLrcMakerWidget::resetToOriginPlayMode().
void MusicApplication::musicPlaySort (int row) slot
Set current music play list sort.
Definition at line 560 of file musicapplication.cpp.
References m_currentMusicSongTreeIndex, m_musicPlaylist, m_musicSongTreeWidget, MusicSongsSummariziedWidget::mapFilePathBySongIndex(), and MusicPlaylist::setCurrentIndex().
Referenced by MusicSongsSummariziedWidget::musicListSongSortBy().
void MusicApplication::musicSetting () slot
Show setting widget.
Definition at line 654 of file musicapplication.cpp.
References m_rightAreaWidget, and MusicRightAreaWidget::showSettingWidget().
Referenced by musicCreateRightMenu().
void MusicApplication::musicStatePlay () slot
Set current player to play or not.
Definition at line 363 of file musicapplication.cpp.
References G_SETTING_PTR, MusicPlaylist::isEmpty(), isPlaying(), m_bottomAreaWidget, m_musicPlayer, m_musicPlaylist, m_rightAreaWidget, m_topAreaWidget, m_ui, MusicUIObject::MQSSBtnPause, MusicUIObject::MQSSBtnPlay, MusicUIObject::MQSSTinyBtnPause, MusicUIObject::MQSSTinyBtnPlay, MusicTopAreaWidget::musicBackgroundThemeDownloadFinished(), MusicPlayer::pause(), MusicPlayer::play(), MusicTopAreaWidget::setBackgroundAnimation(), MusicBottomAreaWidget::setCurrentPlayStatus(), MusicTopAreaWidget::setCurrentPlayStatus(), MusicRightAreaWidget::setCurrentPlayStatus(), MusicRightAreaWidget::startDrawLrc(), MusicRightAreaWidget::stopDrawLrc(), and MusicSettingManager::WindowConciseMode.
Referenced by MusicLrcMakerWidget::firstWidgetStateButtonClicked(), MusicVideoPlayWidget::mediaUrlChanged(), musicPlayedIndex(), musicPlayIndex(), musicPlayNext(), musicPlayPrevious(), MusicLrcFloatPlayWidget::musicStatePlay(), MusicApplicationMPRISPlayer::Pause(), MusicApplicationMPRISPlayer::Play(), MusicApplicationMPRISPlayer::PlayPause(), readSystemConfigFromFile(), setDeleteItemAt(), and MusicLrcMakerWidget::thirdWidgetStateButtonClicked().
void MusicApplication::musicStateStop () slot
Set current player to stop.
Definition at line 392 of file musicapplication.cpp.
References DEFAULT_LOWER_LEVEL, isPlaying(), m_musicPlaylist, and MusicPlaylist::setCurrentIndex().
Referenced by MusicApplicationMPRISPlayer::Stop(), and MusicTimerAutoModule::timeout().
void MusicApplication::musicVolumeChanged (int volume) slot
Current play volume changed.
Definition at line 483 of file musicapplication.cpp.
References G_SETTING_PTR, m_bottomAreaWidget, m_musicPlayer, m_topAreaWidget, m_ui, MusicPlayer::setVolume(), MusicBottomAreaWidget::setVolumeValue(), MusicTopAreaWidget::setVolumeValue(), and MusicSettingManager::Volume.
Referenced by musicActionVolumePlus(), musicActionVolumeSub(), and readSystemConfigFromFile().
void MusicApplication::musicVolumeMute () slot
Set current play volume to 0.
Definition at line 472 of file musicapplication.cpp.
References G_SETTING_PTR, MusicPlayer::isMuted(), m_bottomAreaWidget, m_musicPlayer, m_topAreaWidget, m_ui, MusicPlayer::setMuted(), MusicBottomAreaWidget::setVolumeValue(), MusicTopAreaWidget::setVolumeValue(), MusicSettingManager::Volume, and MusicPlayer::volume().
void MusicApplication::musicWindowConciseChanged () slot
Set window concise.
Definition at line 709 of file musicapplication.cpp.
References m_bottomAreaWidget, m_topAreaWidget, MusicTopAreaWidget::musicBackgroundThemeDownloadFinished(), and MusicBottomAreaWidget::setWindowConcise().
Referenced by MusicRightAreaWidget::functionParameterInit(), MusicRightAreaWidget::musicSongCommentsWidget(), and readSystemConfigFromFile().
void MusicApplication::positionChanged (qint64 position) slot
Set current player position.
Definition at line 276 of file musicapplication.cpp.
References MusicPlayer::duration(), MusicPlaylist::isEmpty(), isPlaying(), m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, m_rightAreaWidget, m_ui, MusicTime::msecTime2LabelJustified(), MUSIC_TIME_INIT, MusicRightAreaWidget::updateCurrentLrc(), and MusicSongsSummariziedWidget::updateTimeLabel().
Referenced by MusicApplication(), and showCurrentSong().
void MusicApplication::quitWindowClose () slot
Application window close.
Definition at line 268 of file musicapplication.cpp.
References m_applicationObject, m_quitWindowClose, MusicApplicationModule::windowCloseAnimation(), and writeSystemConfigToFile().
Referenced by closeEvent(), musicCreateRightMenu(), and MusicApplicationMPRISRoot::Quit().
void MusicApplication::radioExecuteOuter (const QString & path)
Execute outer radio by type.
Definition at line 173 of file musicapplication.cpp.
References m_leftAreaWidget, and MusicLeftAreaWidget::radioExecuteOuter().
Referenced by main().
void MusicApplication::readSystemConfigFromFile () protected
Read system config from file.
Definition at line 1066 of file musicapplication.cpp.
References MusicPlaylist::addMedia(), MusicSongsSummariziedWidget::addMusicItemList(), MusicApplicationModule::applySettingParameter(), MusicBottomAreaWidget::applySettingParameter(), MusicRightAreaWidget::applySettingParameter(), MusicSettingManager::AutoPlayMode, MusicSettingManager::BackgroundListTransparent, MusicSettingManager::BackgroundThemeValue, MusicSettingManager::BackgroundTransparent, DEFAULT_LOWER_LEVEL, MusicSettingManager::DLrcGeometry, MusicSettingManager::DLrcLockedMode, MusicSettingManager::EnhancedFadeEnable, MusicSettingManager::EnhancedMusicIndex, MusicSettingManager::EqualizerEnable, G_HOTKEY_PTR, G_SETTING_PTR, MusicSongsSummariziedWidget::getMusicSongsFilePath(), MusicSettingManager::HotkeyEnable, MusicSettingManager::HotkeyValue, isPlaying(), MusicSettingManager::LastPlayIndex, MusicApplicationModule::loadNetWorkSetting(), MusicBottomAreaWidget::lockDesktopLrc(), m_applicationObject, m_bottomAreaWidget, m_currentMusicSongTreeIndex, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, m_rightAreaWidget, m_topAreaWidget, m_ui, MusicSongsSummariziedWidget::mapFilePathBySongIndex(), MT_MS, MusicApplicationModule::musicEffectChanged(), musicPlaylistLoop(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayRandom(), MusicTopAreaWidget::musicRemoteTypeChanged(), musicStatePlay(), musicVolumeChanged(), musicWindowConciseChanged(), MusicSettingManager::OtherCheckUpdateEnable, MusicSettingManager::OtherSideByInMode, MusicSettingManager::PlayMode, MusicObject::PM_PlaylistLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, MusicObject::PM_PlayRandom, MusicTKPLConfigManager::readConfig(), MusicConfigManager::readConfig(), MusicTKPLConfigManager::readPlaylistData(), MusicConfigManager::readShowDLrcGeometry(), MusicConfigManager::readSysConfigData(), MusicConfigManager::readWindowGeometry(), MusicSettingManager::RemoteWidgetMode, MusicTopAreaWidget::setBackgroundParams(), MusicPlaylist::setCurrentIndex(), MusicBottomAreaWidget::setCurrentPlayStatus(), MusicTopAreaWidget::setCurrentPlayStatus(), MusicRightAreaWidget::setCurrentPlayStatus(), MusicBottomAreaWidget::setDestopLrcVisible(), MusicRightAreaWidget::setDestopLrcVisible(), MusicPlayer::setEqInformation(), MusicRightAreaWidget::setInteriorLrcVisible(), MusicRightAreaWidget::setWindowLrcTypeChanged(), MusicSettingManager::ShowDesktopLrc, MusicSettingManager::ShowInteriorLrc, MusicApplicationModule::soureUpdateCheck(), TTK_STR_SPLITER, MusicSettingManager::Volume, MusicSettingManager::WindowConciseMode, and MusicSettingManager::WindowQuitMode.
Referenced by MusicApplication().
void MusicApplication::resetCurrentSongLrcIndex () slot
Reset current song lrc index.
Definition at line 910 of file musicapplication.cpp.
References m_musicPlayer, m_rightAreaWidget, MusicPlayer::position(), and MusicRightAreaWidget::setSongSpeedAndSlow().
Referenced by musicLoadCurrentSongLrc().
void MusicApplication::resizeEvent (QResizeEvent * event) override protected virtual
remove fixed size
Definition at line 942 of file musicapplication.cpp.
References G_SETTING_PTR, m_bottomAreaWidget, m_quitWindowClose, m_rightAreaWidget, m_topAreaWidget, m_ui, MusicTopAreaWidget::musicBackgroundThemeChangedByResize(), MusicBottomAreaWidget::resizeWindow(), MusicRightAreaWidget::resizeWindow(), and MusicSettingManager::WidgetSize.
void MusicApplication::setDeleteItemAt (const QStringList & path, bool remove, bool current, int toolIndex) slot
Delete items from indexs.
the play one is delete list
check if delete one that the play one
other ways
Play index error correction
Definition at line 819 of file musicapplication.cpp.
References MusicPlaylist::currentIndex(), MusicPlaylist::currentItem(), MusicPlaylist::find(), G_DISPATCH_PTR, m_musicPlayer, m_musicPlaylist, MusicPlayItem::m_path, MusicPlayItem::m_toolIndex, m_ui, MusicPlaylist::mediaCount(), musicStatePlay(), MusicPlaylist::setCurrentIndex(), and MusicPlayer::stop().
Referenced by MusicSongsSummariziedWidget::setDeleteItemAt(), and setLoveDeleteItemAt().
void MusicApplication::setLoveDeleteItemAt (const QString & path, bool current) slot
Delete love item from indexs.
Definition at line 814 of file musicapplication.cpp.
References MUSIC_LOVEST_LIST, and setDeleteItemAt().
Referenced by MusicSongsSummariziedWidget::addSongToLovestListAt(), and MusicSongsSummariziedWidget::musicSongToLovestListAt().
void MusicApplication::setMusicPlayIndex () protected
Set music current play index.
Definition at line 1058 of file musicapplication.cpp.
References MusicPlaylist::addMedia(), MusicPlaylist::clear(), MusicFunctionToolBoxWidget::currentIndex(), MusicSongsSummariziedWidget::getMusicSongsFilePath(), m_currentMusicSongTreeIndex, m_musicPlaylist, m_musicSongTreeWidget, and MusicSongsSummariziedWidget::setCurrentMusicSongTreeIndex().
Referenced by musicPlayIndex(), and musicPlayIndexClicked().
void MusicApplication::setPlaySongChanged (int index) slot
Set current song to play in play list.
Definition at line 928 of file musicapplication.cpp.
References MusicPlaylist::isEmpty(), m_musicPlaylist, MusicPlaylist::mediaCount(), and musicPlayIndex().
Referenced by MusicTimerAutoModule::timeout().
void MusicApplication::showCurrentSong () slot
Show current song some information.
detecting whether the file has been downloaded
Definition at line 308 of file musicapplication.cpp.
References MusicRightAreaWidget::checkLrcValid(), MusicPlaylist::currentItem(), DEFAULT_LOWER_LEVEL, durationChanged(), G_BACKGROUND_PTR, G_SETTING_PTR, getCurrentFileName(), isPlaying(), MusicRightAreaWidget::loadCurrentSongLrc(), m_bottomAreaWidget, m_currentMusicSongTreeIndex, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, MusicPlayItem::m_path, m_rightAreaWidget, MusicPlayItem::m_toolIndex, m_topAreaWidget, m_ui, MusicSongsSummariziedWidget::mapSongIndexByFilePath(), MusicUIObject::MQSSBtnDownload, MusicUIObject::MQSSBtnLove, MusicUIObject::MQSSBtnPlay, MusicUIObject::MQSSBtnUnDownload, MusicUIObject::MQSSBtnUnLove, MusicUIObject::MQSSTinyBtnPlay, MusicTopAreaWidget::musicBackgroundThemeDownloadFinished(), musicDownloadContains(), musicLovestContains(), name, positionChanged(), MusicSongsSummariziedWidget::selectRow(), MusicSongsSummariziedWidget::setCurrentMusicSongTreeIndex(), MusicBottomAreaWidget::setCurrentPlayStatus(), MusicTopAreaWidget::setCurrentPlayStatus(), MusicRightAreaWidget::setCurrentPlayStatus(), MusicBottomAreaWidget::setLabelText(), MusicTopAreaWidget::setLabelText(), MusicSongsSummariziedWidget::setMusicPlayCount(), MusicSongsSummariziedWidget::setRecentMusicSongs(), MusicPlayer::stop(), MusicRightAreaWidget::stopDrawLrc(), and MusicSettingManager::WindowConciseMode.
Referenced by MusicApplication(), and MusicSongsSummariziedWidget::updateCurrentIndex().
void MusicApplication::stateChanged () slot
Current state changed.
Definition at line 302 of file musicapplication.cpp.
References G_SETTING_PTR, m_ui, MusicUIObject::MQSSBtnPlay, MusicUIObject::MQSSTinyBtnPlay, and MusicSettingManager::WindowConciseMode.
Referenced by MusicApplication().
void MusicApplication::updateCurrentArtist ()
Update current artist when it download finished.
Definition at line 248 of file musicapplication.cpp.
References m_musicSongTreeWidget, and MusicSongsSummariziedWidget::updateCurrentArtist().
Referenced by MusicDownloadStatusModule::showDownLoadInfoFinished().
void MusicApplication::updateCurrentTime (qint64 pos) slot
Update current play time when user adjust the progress.
Definition at line 920 of file musicapplication.cpp.
References isPlaying(), m_musicPlayer, and MusicPlayer::setPosition().
void MusicApplication::writeSystemConfigToFile () protected
Write system config to file.
Definition at line 1206 of file musicapplication.cpp.
References MusicSettingManager::BackgroundListTransparent, MusicSettingManager::BackgroundThemeValue, MusicSettingManager::BackgroundTransparent, MusicSettingManager::BackgroundTransparentEnable, MusicPlaylist::currentItem(), MusicSettingManager::EnhancedMusicIndex, G_SETTING_PTR, MusicTopAreaWidget::getBackgroundAlpha(), MusicTopAreaWidget::getBackgroundListAlpha(), MusicTopAreaWidget::getBackgroundPath(), MusicTopAreaWidget::getBackgroundTransparentEnable(), MusicRightAreaWidget::getDestopLrcVisible(), MusicPlayer::getMusicEnhanced(), MusicSongsSummariziedWidget::getMusicItemList(), MusicSettingManager::LastPlayIndex, m_applicationObject, m_musicPlayer, m_musicPlaylist, m_musicSongTreeWidget, MusicPlayItem::m_path, m_rightAreaWidget, MusicPlayItem::m_toolIndex, m_topAreaWidget, m_ui, MusicSongsSummariziedWidget::mapSongIndexByFilePath(), MusicPlaylist::playbackMode(), PLAYLIST_PATH_FULL, MusicSettingManager::PlayMode, MusicSettingManager::ShowDesktopLrc, MusicApplicationModule::sideAnimationReset(), MusicSettingManager::Volume, MusicSettingManager::WidgetPosition, MusicTKPLConfigManager::writePlaylistData(), and MusicConfigManager::writeSysConfigData().
Referenced by quitWindowClose().
Friends And Related Function Documentation
friend class MusicApplicationMPRISPlayer friend
Definition at line 342 of file musicapplication.h.
Member Data Documentation
MusicApplicationModule* MusicApplication::m_applicationObject private
Definition at line 340 of file musicapplication.h.
Referenced by applySettingParameter(), leaveEvent(), mouseReleaseEvent(), MusicApplication(), musicCreateRightMenu(), quitWindowClose(), readSystemConfigFromFile(), writeSystemConfigToFile(), and ~MusicApplication().
MusicBottomAreaWidget* MusicApplication::m_bottomAreaWidget private
Definition at line 336 of file musicapplication.h.
Referenced by applySettingParameter(), closeEvent(), MusicApplication(), musicStatePlay(), musicVolumeChanged(), musicVolumeMute(), musicWindowConciseChanged(), readSystemConfigFromFile(), resizeEvent(), showCurrentSong(), and ~MusicApplication().
int MusicApplication::m_currentMusicSongTreeIndex private
Definition at line 331 of file musicapplication.h.
Referenced by getCurrentFileName(), getCurrentFilePath(), MusicApplication(), musicPlayIndex(), musicPlayIndexClicked(), musicPlaySort(), readSystemConfigFromFile(), setMusicPlayIndex(), and showCurrentSong().
MusicApplication * MusicApplication::m_instance = nullptr static private
Definition at line 343 of file musicapplication.h.
Referenced by instance(), and MusicApplication().
MusicLeftAreaWidget* MusicApplication::m_leftAreaWidget private
Definition at line 339 of file musicapplication.h.
Referenced by musicAddSongToLovestList(), MusicApplication(), radioExecuteOuter(), and ~MusicApplication().
MusicPlayer* MusicApplication::m_musicPlayer private
Definition at line 333 of file musicapplication.h.
Referenced by duration(), isPlaying(), musicActionVolumePlus(), musicActionVolumeSub(), MusicApplication(), musicEnhancedMusicChanged(), musicPlayAnyTimeAt(), musicPlayedIndex(), musicPlayIndex(), musicPlayNext(), musicPlayPrevious(), musicStatePlay(), musicVolumeChanged(), musicVolumeMute(), positionChanged(), readSystemConfigFromFile(), resetCurrentSongLrcIndex(), setDeleteItemAt(), MusicApplicationMPRISPlayer::setVolume(), showCurrentSong(), updateCurrentTime(), MusicApplicationMPRISPlayer::volume(), writeSystemConfigToFile(), and ~MusicApplication().
MusicPlaylist* MusicApplication::m_musicPlaylist private
Definition at line 334 of file musicapplication.h.
Referenced by MusicApplicationMPRISPlayer::canGoNext(), MusicApplicationMPRISPlayer::canGoPrevious(), MusicApplicationMPRISPlayer::canPause(), MusicApplicationMPRISPlayer::canPlay(), checkMusicListCurrentIndex(), getCurrentFileName(), getCurrentFilePath(), getPlayMode(), musicAddSongToLovestList(), MusicApplication(), MusicApplicationMPRISPlayer::MusicApplicationMPRISPlayer(), musicCreateRightMenu(), musicCurrentPlayLocation(), musicDownloadContains(), musicImportSongsPathOuter(), musicLovestContains(), musicPlayedIndex(), musicPlayIndex(), musicPlaylistLoop(), musicPlayNext(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayPrevious(), musicPlayRandom(), musicPlaySort(), musicStatePlay(), musicStateStop(), positionChanged(), readSystemConfigFromFile(), setDeleteItemAt(), setMusicPlayIndex(), setPlaySongChanged(), MusicApplicationMPRISPlayer::setShuffle(), showCurrentSong(), MusicApplicationMPRISPlayer::updateTrackID(), writeSystemConfigToFile(), and ~MusicApplication().
MusicSongsSummariziedWidget* MusicApplication::m_musicSongTreeWidget private
Definition at line 335 of file musicapplication.h.
Referenced by getCurrentFileName(), getCurrentFilePath(), getCurrentPlaylist(), musicAddSongToLovestList(), MusicApplication(), musicCurrentPlayLocation(), musicDownloadContains(), musicExportSongsItemList(), musicImportSongsItemList(), musicImportSongsPath(), musicLovestContains(), musicPlayIndex(), musicPlayIndexClicked(), musicPlaySort(), positionChanged(), readSystemConfigFromFile(), setMusicPlayIndex(), showCurrentSong(), updateCurrentArtist(), writeSystemConfigToFile(), and ~MusicApplication().
bool MusicApplication::m_quitWindowClose private
Definition at line 330 of file musicapplication.h.
Referenced by MusicApplication(), quitWindowClose(), and resizeEvent().
MusicRightAreaWidget* MusicApplication::m_rightAreaWidget private
Definition at line 338 of file musicapplication.h.
Referenced by applySettingParameter(), MusicApplication(), musicCurrentLrcUpdated(), musicLoadCurrentSongLrc(), musicPlayAnyTimeAt(), musicSetting(), musicStatePlay(), positionChanged(), readSystemConfigFromFile(), resetCurrentSongLrcIndex(), resizeEvent(), showCurrentSong(), writeSystemConfigToFile(), and ~MusicApplication().
MusicTopAreaWidget* MusicApplication::m_topAreaWidget private
Definition at line 337 of file musicapplication.h.
Referenced by MusicApplication(), musicCreateRightMenu(), musicLoadCurrentSongLrc(), musicStatePlay(), musicVolumeChanged(), musicVolumeMute(), musicWindowConciseChanged(), readSystemConfigFromFile(), resizeEvent(), showCurrentSong(), writeSystemConfigToFile(), and ~MusicApplication().
Ui::MusicApplication* MusicApplication::m_ui private
Definition at line 329 of file musicapplication.h.
Referenced by durationChanged(), eventFilter(), mouseDoubleClickEvent(), mousePressEvent(), MusicApplication(), musicPlayIndex(), musicPlayIndexClicked(), musicPlaylistLoop(), musicPlayOnce(), musicPlayOneLoop(), musicPlayOrder(), musicPlayRandom(), musicStatePlay(), musicVolumeChanged(), musicVolumeMute(), positionChanged(), readSystemConfigFromFile(), resizeEvent(), setDeleteItemAt(), showCurrentSong(), stateChanged(), writeSystemConfigToFile(), and ~MusicApplication().
The documentation for this class was generated from the following files:
TTKModule/musicapplication.h
TTKModule/musicapplication.cpp