TTKMusicplayer: MusicFMRadioDownLoadTextRequest Class Reference
MusicFMRadioDownLoadTextRequest Class Reference
The class of fm radio request of download text.
#include <musicfmradiodownloadtextrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractDownLoadRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) overridefinal
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) overridefinal
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicFMRadioDownLoadTextRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
virtual void startToDownload () overridefinal
Public Member Functions inherited from MusicAbstractDownLoadRequest
MusicAbstractDownLoadRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Member Functions inherited from MusicAbstractDownLoadRequest
QString mapCurrentQueryData () const
Protected Attributes inherited from MusicAbstractDownLoadRequest
QFile * m_file
QString m_url
QString m_savePath
MusicObject::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of fm radio request of download text.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicfmradiodownloadtextrequest.h.
Constructor & Destructor Documentation
MusicFMRadioDownLoadTextRequest::MusicFMRadioDownLoadTextRequest (const QString & url, const QString & save, MusicObject::DownloadType type, QObject * parent = nullptr)
Object contsructor provide download URL\ save local path and download type.
Definition at line 3 of file musicfmradiodownloadtextrequest.cpp.
Member Function Documentation
void MusicFMRadioDownLoadTextRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 35 of file musicfmradiodownloadtextrequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractDownLoadRequest::downLoadFinished(), MusicAbstractDownLoadRequest::m_file, MusicAbstractNetwork::m_reply, QJson::Parser::parse(), QtStreamEndl, TTK_LOGGER_ERROR, and TTK_LOGGER_INFO.
Referenced by startToDownload().
void MusicFMRadioDownLoadTextRequest::startToDownload () final override virtual
Start to download data.
Implements MusicAbstractDownLoadRequest.
Definition at line 9 of file musicfmradiodownloadtextrequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), downLoadFinished(), MusicAbstractDownLoadRequest::downloadProgress(), MusicAbstractDownLoadRequest::m_file, MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::m_speedTimer, MusicAbstractDownLoadRequest::m_url, QtNetworkErrorConnect, MusicAbstractDownLoadRequest::replyError(), MusicObject::setSslConfiguration(), and TTK_LOGGER_ERROR.
Referenced by MusicWebFMRadioPlayWidget::querySongInfoFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicfmradiodownloadtextrequest.h
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicfmradiodownloadtextrequest.cpp