TTKMusicplayer: MusicSongCheckToolsWidget Class Reference
MusicSongCheckToolsWidget Class Reference
The class of the song check tools widget.
#include <musicsongchecktoolswidget.h>
Public Slots
void modifiedItemButtonClicked ()
void itemListsChanged (const MusicObject::MIntList &items)
void renameButtonClicked ()
void renameButtonCheckClicked ()
void renameReCheckButtonClicked ()
void renameCheckFinished (const MusicSongCheckToolsRenames &items)
void qualityButtonClicked ()
void qualityButtonCheckClicked ()
void qualityReCheckButtonClicked ()
void qualityCheckFinished (const MusicSongCheckToolsQualitys &items)
void duplicateButtonClicked ()
void duplicateButtonCheckClicked ()
void duplicateReCheckButtonClicked ()
void duplicateCheckFinished (const MusicSongCheckToolsDuplicates &items)
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void getMusicLists (MusicSongItems &songs)
Public Member Functions
MusicSongCheckToolsWidget (QWidget *parent=0)
virtual ~MusicSongCheckToolsWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
void getSelectedSongItems ()
void renameWidgetInit ()
void qualityWidgetInit ()
void duplicateWidgetInit ()
void switchToSelectedItemStyle (int index)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicSongCheckToolsWidget * m_ui
MusicSongs m_localSongs
bool m_selectedItemIdFlag
MusicObject::MIntList m_selectedItemIds
MusicSongCheckToolsRenameCore * m_renameCore
MusicSongCheckToolsDuplicateCore * m_duplicateCore
MusicSongCheckToolsQualityCore * m_qualityCore
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the song check tools widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 26 of file musicsongchecktoolswidget.h.
Constructor & Destructor Documentation
MusicSongCheckToolsWidget::MusicSongCheckToolsWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 12 of file musicsongchecktoolswidget.cpp.
References duplicateWidgetInit(), MusicSongsSummariziedWidget::getClassName(), getClassName(), M_CONNECTION_PTR, m_selectedItemIdFlag, m_ui, modifiedItemButtonClicked(), MusicUIObject::MToolButtonStyle04, qualityWidgetInit(), renameWidgetInit(), and switchToSelectedItemStyle().
MusicSongCheckToolsWidget::~MusicSongCheckToolsWidget () virtual
Definition at line 40 of file musicsongchecktoolswidget.cpp.
References getClassName(), M_CONNECTION_PTR, m_duplicateCore, m_qualityCore, m_renameCore, and m_ui.
Member Function Documentation
void MusicSongCheckToolsWidget::duplicateButtonCheckClicked () slot
Duplicate button check clicked.
Definition at line 198 of file musicsongchecktoolswidget.cpp.
References MusicObject::Apply, MusicObject::Check, duplicateReCheckButtonClicked(), m_duplicateCore, m_ui, MusicSongCheckToolsDuplicateCore::setItemLists(), MusicSongCheckToolsDuplicateCore::setMode(), MusicSongCheckToolsDuplicateCore::start(), and MusicSongCheckToolsDuplicateCore::stopAndQuitThread().
Referenced by duplicateWidgetInit().
void MusicSongCheckToolsWidget::duplicateButtonClicked () slot
Duplicate button clicked.
Definition at line 193 of file musicsongchecktoolswidget.cpp.
References switchToSelectedItemStyle().
Referenced by duplicateWidgetInit().
void MusicSongCheckToolsWidget::duplicateCheckFinished (const MusicSongCheckToolsDuplicates & items) slot
Duplicate check finished.
Definition at line 241 of file musicsongchecktoolswidget.cpp.
References MusicObject::Apply, MusicObject::Check, MusicMessageBox::exec(), MusicSongCheckToolsDuplicateCore::getMode(), m_duplicateCore, m_ui, and MusicMessageBox::setText().
Referenced by duplicateWidgetInit().
void MusicSongCheckToolsWidget::duplicateReCheckButtonClicked () slot
Duplicate reCheck button clicked.
Definition at line 226 of file musicsongchecktoolswidget.cpp.
References MusicObject::Check, getSelectedSongItems(), m_duplicateCore, m_localSongs, m_qualityCore, m_ui, MusicSongCheckToolsDuplicateCore::setDuplicateSongs(), MusicSongCheckToolsDuplicateCore::setMode(), MusicSongCheckToolsDuplicateCore::start(), and MusicSongCheckToolsQualityCore::stopAndQuitThread().
Referenced by duplicateButtonCheckClicked(), and duplicateWidgetInit().
void MusicSongCheckToolsWidget::duplicateWidgetInit () protected
Duplicate widget init.
Definition at line 340 of file musicsongchecktoolswidget.cpp.
References duplicateButtonCheckClicked(), duplicateButtonClicked(), duplicateCheckFinished(), duplicateReCheckButtonClicked(), MusicGifLabelWidget::Gif_Cicle_Blue, m_duplicateCore, m_ui, MusicUIObject::MCheckBoxStyle01, and MusicUIObject::MPushButtonStyle04.
Referenced by MusicSongCheckToolsWidget().
QString MusicSongCheckToolsWidget::getClassName () static
Get class object name.
Definition at line 49 of file musicsongchecktoolswidget.cpp.
Referenced by MusicSongCheckToolsWidget(), MusicConnectionPool::poolConnect(), and ~MusicSongCheckToolsWidget().
void MusicSongCheckToolsWidget::getMusicLists (MusicSongItems & songs) signal
Get music datas from container.
Referenced by getSelectedSongItems(), and modifiedItemButtonClicked().
void MusicSongCheckToolsWidget::getSelectedSongItems () protected
Get selected song items.
Definition at line 269 of file musicsongchecktoolswidget.cpp.
References getMusicLists(), MusicSongItem::m_itemIndex, m_localSongs, m_selectedItemIdFlag, m_selectedItemIds, MusicSongItem::m_songs, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, and MUSIC_RECENT_LIST.
Referenced by duplicateReCheckButtonClicked(), qualityReCheckButtonClicked(), and renameReCheckButtonClicked().
void MusicSongCheckToolsWidget::itemListsChanged (const MusicObject::MIntList & items) slot
Item lists changed.
Definition at line 66 of file musicsongchecktoolswidget.cpp.
References m_selectedItemIds, and m_ui.
Referenced by modifiedItemButtonClicked().
void MusicSongCheckToolsWidget::modifiedItemButtonClicked () slot
Modified item button clicked.
Definition at line 54 of file musicsongchecktoolswidget.cpp.
References MusicSongCheckToolsItemSelectedDialog::createAllItems(), MusicSongCheckToolsItemSelectedDialog::exec(), getMusicLists(), itemListsChanged(), and m_selectedItemIdFlag.
Referenced by MusicSongCheckToolsWidget().
void MusicSongCheckToolsWidget::qualityButtonCheckClicked () slot
Quality button check clicked.
Definition at line 148 of file musicsongchecktoolswidget.cpp.
References m_qualityCore, m_ui, qualityReCheckButtonClicked(), and MusicSongCheckToolsQualityCore::stopAndQuitThread().
Referenced by qualityWidgetInit().
void MusicSongCheckToolsWidget::qualityButtonClicked () slot
Quality button clicked.
Definition at line 143 of file musicsongchecktoolswidget.cpp.
References switchToSelectedItemStyle().
Referenced by qualityWidgetInit().
void MusicSongCheckToolsWidget::qualityCheckFinished (const MusicSongCheckToolsQualitys & items) slot
Quality check finished.
Definition at line 182 of file musicsongchecktoolswidget.cpp.
References m_ui.
Referenced by qualityWidgetInit().
void MusicSongCheckToolsWidget::qualityReCheckButtonClicked () slot
Quality reCheck button clicked.
Definition at line 169 of file musicsongchecktoolswidget.cpp.
References getSelectedSongItems(), m_localSongs, m_qualityCore, m_ui, MusicSongCheckToolsQualityCore::setQualitySongs(), MusicSongCheckToolsQualityCore::start(), and MusicSongCheckToolsQualityCore::stopAndQuitThread().
Referenced by qualityButtonCheckClicked(), and qualityWidgetInit().
void MusicSongCheckToolsWidget::qualityWidgetInit () protected
Quality widget init.
Definition at line 320 of file musicsongchecktoolswidget.cpp.
References MusicGifLabelWidget::Gif_Cicle_Blue, m_qualityCore, m_ui, MusicUIObject::MPushButtonStyle04, qualityButtonCheckClicked(), qualityButtonClicked(), qualityCheckFinished(), and qualityReCheckButtonClicked().
Referenced by MusicSongCheckToolsWidget().
void MusicSongCheckToolsWidget::renameButtonCheckClicked () slot
Rename button check clicked.
Definition at line 77 of file musicsongchecktoolswidget.cpp.
References MusicObject::Apply, MusicObject::Check, m_renameCore, m_ui, renameReCheckButtonClicked(), MusicSongCheckToolsRenameCore::setItemLists(), MusicSongCheckToolsRenameCore::setMode(), MusicSongCheckToolsRenameCore::start(), and MusicSongCheckToolsRenameCore::stopAndQuitThread().
Referenced by renameWidgetInit().
void MusicSongCheckToolsWidget::renameButtonClicked () slot
Rename button clicked.
Definition at line 72 of file musicsongchecktoolswidget.cpp.
References switchToSelectedItemStyle().
Referenced by renameWidgetInit().
void MusicSongCheckToolsWidget::renameCheckFinished (const MusicSongCheckToolsRenames & items) slot
Rename check finished.
Definition at line 121 of file musicsongchecktoolswidget.cpp.
References MusicObject::Apply, MusicObject::Check, MusicMessageBox::exec(), MusicSongCheckToolsRenameCore::getMode(), m_renameCore, m_ui, and MusicMessageBox::setText().
Referenced by renameWidgetInit().
void MusicSongCheckToolsWidget::renameReCheckButtonClicked () slot
Rename reCheck button clicked.
Definition at line 105 of file musicsongchecktoolswidget.cpp.
References MusicObject::Check, getSelectedSongItems(), m_localSongs, m_renameCore, m_ui, MusicSongCheckToolsRenameCore::setMode(), MusicSongCheckToolsRenameCore::setRenameSongs(), MusicSongCheckToolsRenameCore::start(), and MusicSongCheckToolsRenameCore::stopAndQuitThread().
Referenced by renameButtonCheckClicked(), and renameWidgetInit().
void MusicSongCheckToolsWidget::renameWidgetInit () protected
Rename widget init.
Definition at line 296 of file musicsongchecktoolswidget.cpp.
References MusicGifLabelWidget::Gif_Cicle_Blue, m_renameCore, m_ui, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MPushButtonStyle04, renameButtonCheckClicked(), renameButtonClicked(), renameCheckFinished(), and renameReCheckButtonClicked().
Referenced by MusicSongCheckToolsWidget().
void MusicSongCheckToolsWidget::show () slot
Override show function.
Definition at line 263 of file musicsongchecktoolswidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Referenced by MusicSongsSummariziedWidget::musicSongsCheckTestTools().
void MusicSongCheckToolsWidget::switchToSelectedItemStyle (int index) protected
Switch to selected item style.
Definition at line 364 of file musicsongchecktoolswidget.cpp.
References m_ui, MusicUIObject::MKGCheckTestDuplicate, MusicUIObject::MKGCheckTestDuplicateClicked, MusicUIObject::MKGCheckTestQuality, MusicUIObject::MKGCheckTestQualityClicked, MusicUIObject::MKGCheckTestRename, and MusicUIObject::MKGCheckTestRenameClicked.
Referenced by duplicateButtonClicked(), MusicSongCheckToolsWidget(), qualityButtonClicked(), and renameButtonClicked().
Member Data Documentation
MusicSongCheckToolsDuplicateCore* MusicSongCheckToolsWidget::m_duplicateCore protected
Definition at line 138 of file musicsongchecktoolswidget.h.
Referenced by duplicateButtonCheckClicked(), duplicateCheckFinished(), duplicateReCheckButtonClicked(), duplicateWidgetInit(), and ~MusicSongCheckToolsWidget().
MusicSongs MusicSongCheckToolsWidget::m_localSongs protected
Definition at line 134 of file musicsongchecktoolswidget.h.
Referenced by duplicateReCheckButtonClicked(), getSelectedSongItems(), qualityReCheckButtonClicked(), and renameReCheckButtonClicked().
MusicSongCheckToolsQualityCore* MusicSongCheckToolsWidget::m_qualityCore protected
Definition at line 139 of file musicsongchecktoolswidget.h.
Referenced by duplicateReCheckButtonClicked(), qualityButtonCheckClicked(), qualityReCheckButtonClicked(), qualityWidgetInit(), and ~MusicSongCheckToolsWidget().
MusicSongCheckToolsRenameCore* MusicSongCheckToolsWidget::m_renameCore protected
Definition at line 137 of file musicsongchecktoolswidget.h.
Referenced by renameButtonCheckClicked(), renameCheckFinished(), renameReCheckButtonClicked(), renameWidgetInit(), and ~MusicSongCheckToolsWidget().
bool MusicSongCheckToolsWidget::m_selectedItemIdFlag protected
Definition at line 135 of file musicsongchecktoolswidget.h.
Referenced by getSelectedSongItems(), modifiedItemButtonClicked(), and MusicSongCheckToolsWidget().
MusicObject::MIntList MusicSongCheckToolsWidget::m_selectedItemIds protected
Definition at line 136 of file musicsongchecktoolswidget.h.
Referenced by getSelectedSongItems(), and itemListsChanged().
Ui::MusicSongCheckToolsWidget* MusicSongCheckToolsWidget::m_ui protected
Definition at line 132 of file musicsongchecktoolswidget.h.
Referenced by duplicateButtonCheckClicked(), duplicateCheckFinished(), duplicateReCheckButtonClicked(), duplicateWidgetInit(), itemListsChanged(), MusicSongCheckToolsWidget(), qualityButtonCheckClicked(), qualityCheckFinished(), qualityReCheckButtonClicked(), qualityWidgetInit(), renameButtonCheckClicked(), renameCheckFinished(), renameReCheckButtonClicked(), renameWidgetInit(), show(), switchToSelectedItemStyle(), and ~MusicSongCheckToolsWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolswidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolswidget.cpp