TTKMusicPlayer: MusicTXDownloadBackgroundRequest Class Reference
MusicTXDownloadBackgroundRequest Class Reference
The class of the tencent download art background image.
#include <musictxdownloadimagerequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadUrlFinished ()
Public Slots inherited from MusicAbstractDownloadImageRequest
void downLoadDataFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicTXDownloadBackgroundRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void startRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownloadImageRequest
MusicAbstractDownloadImageRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Member Functions
void downLoadUrl (const QString &id)
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicAbstractDownloadImageRequest
int m_index
int m_counter
QString m_name
QString m_path
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the tencent download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 49 of file musictxdownloadimagerequest.h.
Constructor & Destructor Documentation
MusicTXDownloadBackgroundRequest::MusicTXDownloadBackgroundRequest (const QString & name, const QString & path, QObject * parent = nullptr)
Object contsructor provide artist name and save local path.
Definition at line 25 of file musictxdownloadimagerequest.cpp.
Member Function Documentation
void MusicTXDownloadBackgroundRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 46 of file musictxdownloadimagerequest.cpp.
References MusicAbstractDownloadImageRequest::deleteAll(), MusicAbstractNetwork::downLoadFinished(), downLoadUrl(), MusicAbstractNetwork::m_reply, QJson::Parser::parse(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startRequest().
void MusicTXDownloadBackgroundRequest::downLoadUrl (const QString & id) private
Download data from net.
Definition at line 127 of file musictxdownloadimagerequest.cpp.
References ART_BACKGROUND_URL, MusicAbstractNetwork::deleteAll(), downLoadUrlFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), and TTK_INFO_STREAM.
Referenced by downLoadFinished().
void MusicTXDownloadBackgroundRequest::downLoadUrlFinished () slot
Download data from net finished.
Definition at line 95 of file musictxdownloadimagerequest.cpp.
References MusicObject::Background, BACKGROUND_DIR_FULL, MusicAbstractDownloadImageRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractDownloadImageRequest::downLoadDataFinished(), MusicAbstractNetwork::downLoadFinished(), TTKAbstractXml::fromByteArray(), MusicAbstractDownloadImageRequest::m_counter, MusicAbstractDownloadImageRequest::m_path, MusicAbstractNetwork::m_reply, MAX_IMAGE_COUNTER, MusicTXImageConfigManager::readBuffer(), SKN_FILE, MusicDownloadDataRequest::startRequest(), and TTK_INFO_STREAM.
Referenced by downLoadUrl().
void MusicTXDownloadBackgroundRequest::startRequest () final override virtual
Start to download data from net.
Implements MusicAbstractDownloadImageRequest.
Definition at line 31 of file musictxdownloadimagerequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractDownloadImageRequest::m_name, MusicAbstractNetwork::m_reply, MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), TTK_INFO_STREAM, TX_SEARCH_DATA_URL, and TX_SEARCH_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/photo/musictxdownloadimagerequest.h
TTKModule/TTKCore/musicNetworkKits/image/photo/musictxdownloadimagerequest.cpp