TTKMusicplayer: MusicDownloadDataRequest Class Reference
MusicDownloadDataRequest Class Reference
The class of download the type of data.
#include <musicdownloaddatarequest.h>
Public Slots
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal) overridefinal
virtual void updateDownloadSpeed () overridefinal
void handleReadyRead ()
Public Slots inherited from MusicAbstractDownLoadRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) overridefinal
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) overridefinal
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void downloadUrlChanged (const QString &url)
void downloadSpeedLabelChanged (const QString &speed, qint64 timeLeft)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Public Member Functions
MusicDownloadDataRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
virtual void startToDownload () override
void setRecordType (MusicObject::RecordType type)
Public Member Functions inherited from MusicAbstractDownLoadRequest
MusicAbstractDownLoadRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Member Functions
void startRequest (const QString &url)
Protected Member Functions inherited from MusicAbstractDownLoadRequest
QString mapCurrentQueryData () const
Protected Attributes
qint64 m_createItemTime
bool m_redirection
bool m_needUpdate
MusicObject::RecordType m_recordType
Protected Attributes inherited from MusicAbstractDownLoadRequest
QFile * m_file
QString m_url
QString m_savePath
MusicObject::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of download the type of data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloaddatarequest.h.
Constructor & Destructor Documentation
MusicDownloadDataRequest::MusicDownloadDataRequest (const QString & url, const QString & save, MusicObject::DownloadType type, QObject * parent = nullptr)
Object contsructor provide download URL\ save local path and download type.
Definition at line 4 of file musicdownloaddatarequest.cpp.
References m_createItemTime, m_needUpdate, m_recordType, m_redirection, and MusicObject::RecordNull.
Member Function Documentation
void MusicDownloadDataRequest::createDownloadItem (const QString & name, qint64 time) signal
Create download item from download name and total time.
Referenced by startRequest().
void MusicDownloadDataRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 62 of file musicdownloaddatarequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractDownLoadRequest::downLoadFinished(), MusicAbstractDownLoadRequest::m_file, m_needUpdate, m_redirection, MusicAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::mapCurrentQueryData(), startRequest(), and TTK_LOGGER_INFO.
Referenced by MusicDownloadTagDataRequest::downLoadFinished(), and startRequest().
void MusicDownloadDataRequest::downloadProgress (qint64 bytesReceived, qint64 bytesTotal) final override virtual slot
Get download received and total data.
only download music data or oather type can that show progress
Definition at line 108 of file musicdownloaddatarequest.cpp.
References MusicObject::DownloadMusic, MusicObject::DownloadOther, MusicAbstractDownLoadRequest::downloadProgress(), downloadProgressChanged(), m_createItemTime, MusicAbstractDownLoadRequest::m_downloadType, and MusicUtils::Number::sizeByte2Label().
Referenced by startRequest().
void MusicDownloadDataRequest::downloadProgressChanged (float percent, const QString & total, qint64 time) signal
Update download percent\ total time and current time progress.
Referenced by downloadProgress().
void MusicDownloadDataRequest::downloadSpeedLabelChanged (const QString & speed, qint64 timeLeft) signal
Update download speed label.
Referenced by updateDownloadSpeed().
void MusicDownloadDataRequest::downloadUrlChanged (const QString & url) signal
Update download url finished.
void MusicDownloadDataRequest::handleReadyRead () slot
Download received data ready.
Definition at line 100 of file musicdownloaddatarequest.cpp.
References MusicAbstractDownLoadRequest::m_file, and MusicAbstractNetwork::m_reply.
Referenced by startRequest().
void MusicDownloadDataRequest::setRecordType (MusicObject::RecordType type)
Set record type.
Definition at line 30 of file musicdownloaddatarequest.cpp.
References m_recordType.
Referenced by MusicCloudManagerTableWidget::downloadFileToServer(), MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicDownloadDataRequest::startRequest (const QString & url) protected
Start to download data from url.
only download music data can that show progress
Definition at line 35 of file musicdownloaddatarequest.cpp.
References createDownloadItem(), downLoadFinished(), MusicObject::DownloadMusic, downloadProgress(), G_DOWNLOAD_MANAGER_PTR, handleReadyRead(), m_createItemTime, MusicAbstractDownLoadRequest::m_downloadType, MusicAbstractNetwork::m_manager, m_recordType, m_redirection, MusicAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::m_savePath, MusicAbstractDownLoadRequest::m_speedTimer, MusicObject::NetworkError, MusicAbstractDownLoadRequest::replyError(), MusicObject::setSslConfiguration(), and MusicTime::timestamp().
Referenced by downLoadFinished(), startToDownload(), and MusicDownloadTagDataRequest::startToDownload().
void MusicDownloadDataRequest::startToDownload () override virtual
Start to download data.
Implements MusicAbstractDownLoadRequest.
Reimplemented in MusicDownloadTagDataRequest.
Definition at line 13 of file musicdownloaddatarequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractDownLoadRequest::m_file, MusicAbstractDownLoadRequest::m_url, startRequest(), and TTK_LOGGER_ERROR.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicCloudManagerTableWidget::downloadFileToServer(), MusicKWDownloadImageRequest::downLoadFinished(), MusicQQDownloadImageRequest::downLoadUrlFinished(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), MusicDownloadBatchTableItem::startToDownloadMovie(), and MusicDownloadWidget::startToDownloadMovie().
void MusicDownloadDataRequest::updateDownloadSpeed () final override virtual slot
Updata download speed due the user mod the net speed limited.
Definition at line 119 of file musicdownloaddatarequest.cpp.
References downloadSpeedLabelChanged(), MusicAbstractDownLoadRequest::m_currentReceived, MusicAbstractDownLoadRequest::m_hasReceived, MusicAbstractDownLoadRequest::m_totalSize, MusicUtils::Number::speedByte2Label(), and MusicAbstractDownLoadRequest::updateDownloadSpeed().
Member Data Documentation
qint64 MusicDownloadDataRequest::m_createItemTime protected
Definition at line 89 of file musicdownloaddatarequest.h.
Referenced by downloadProgress(), MusicDownloadDataRequest(), and startRequest().
bool MusicDownloadDataRequest::m_needUpdate protected
Definition at line 90 of file musicdownloaddatarequest.h.
Referenced by downLoadFinished(), MusicDownloadDataRequest(), and MusicDownloadTagDataRequest::MusicDownloadTagDataRequest().
MusicObject::RecordType MusicDownloadDataRequest::m_recordType protected
Definition at line 91 of file musicdownloaddatarequest.h.
Referenced by MusicDownloadDataRequest(), setRecordType(), and startRequest().
bool MusicDownloadDataRequest::m_redirection protected
Definition at line 90 of file musicdownloaddatarequest.h.
Referenced by MusicDownloadTagDataRequest::downLoadFinished(), downLoadFinished(), MusicDownloadDataRequest(), and startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/common/musicdownloaddatarequest.h
TTKModule/TTKCore/musicNetworkKits/common/musicdownloaddatarequest.cpp