TTKMusicPlayer: MusicSmoothMovingTableWidget Class Reference
MusicSmoothMovingTableWidget Class Reference
The class of the slider smooth moving table widget.
#include <musicsmoothmovingwidget.h>
Public Member Functions
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Protected Member Functions
virtual void wheelEvent (QWheelEvent *event) override
QScrollBar * scrollBar () const noexcept
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Private Attributes
MusicSmoothMovingInterface m_interface
Additional Inherited Members
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the slider smooth moving table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 83 of file musicsmoothmovingwidget.h.
Constructor & Destructor Documentation
MusicSmoothMovingTableWidget::MusicSmoothMovingTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 83 of file musicsmoothmovingwidget.cpp.
References TTK::UI::ScrollBarStyle03.
Member Function Documentation
QScrollBar* MusicSmoothMovingTableWidget::scrollBar () const inline protected noexcept
Get current moved scroll bar.
Definition at line 107 of file musicsmoothmovingwidget.h.
Referenced by MusicSongsListPlayedTableWidget::selectRow().
void MusicSmoothMovingTableWidget::setMovedScrollBar (QScrollBar * bar = nullptr)
Set current moved scroll bar.
Definition at line 89 of file musicsmoothmovingwidget.cpp.
References m_interface, and MusicSmoothMovingInterface::setScrollBar().
Referenced by MusicSongsContainerWidget::createWidgetItem(), and MusicPlayedListPopWidget::initialize().
void MusicSmoothMovingTableWidget::wheelEvent (QWheelEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicSongsListPlayTableWidget.
Definition at line 94 of file musicsmoothmovingwidget.cpp.
References m_interface, QtWheelDelta, and MusicSmoothMovingInterface::updateValue().
Referenced by MusicSongsListPlayTableWidget::wheelEvent().
Member Data Documentation
MusicSmoothMovingInterface MusicSmoothMovingTableWidget::m_interface private
Definition at line 110 of file musicsmoothmovingwidget.h.
Referenced by setMovedScrollBar(), and wheelEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicsmoothmovingwidget.h
TTKModule/TTKWidget/musicCoreKits/musicsmoothmovingwidget.cpp