TTKMusicPlayer: MusicAbstractFloatWidget Class Reference
MusicAbstractFloatWidget Class Reference
The class of the float widget base.
#include <musicabstractfloatwidget.h>
Public Member Functions
MusicAbstractFloatWidget (QWidget *parent=nullptr)
~MusicAbstractFloatWidget ()
void setBlockAnimation (bool b)
Protected Member Functions
virtual void enterEvent (QtEnterEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *) overridefinal
virtual void mousePressEvent (QMouseEvent *) overridefinal
virtual void mouseMoveEvent (QMouseEvent *) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *) overridefinal
void animationEnter ()
void animationLeave ()
Protected Attributes
QPropertyAnimation * m_animation
QRect m_rectEnter
QRect m_rectLeave
bool m_blockAnimation
Detailed Description
The class of the float widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicabstractfloatwidget.h.
Constructor & Destructor Documentation
MusicAbstractFloatWidget::MusicAbstractFloatWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musicabstractfloatwidget.cpp.
References m_animation, and TTK_DN_S2MS.
MusicAbstractFloatWidget::~MusicAbstractFloatWidget ()
Object destructor.
Definition at line 11 of file musicabstractfloatwidget.cpp.
References m_animation.
Member Function Documentation
void MusicAbstractFloatWidget::animationEnter () protected
Show animation in case.
Definition at line 16 of file musicabstractfloatwidget.cpp.
References m_animation, m_rectEnter, and m_rectLeave.
Referenced by MusicLrcFloatPhotoWidget::close(), enterEvent(), MusicLrcFloatPlayWidget::resizeGeometry(), and MusicLrcFloatSettingWidget::show().
void MusicAbstractFloatWidget::animationLeave () protected
Show animation out case.
Definition at line 23 of file musicabstractfloatwidget.cpp.
References m_animation, m_rectEnter, and m_rectLeave.
Referenced by leaveEvent(), MusicLrcFloatSettingWidget::leaveEvent(), MusicLrcFloatPhotoWidget::show(), and MusicLrcFloatWidget::showFloatSettingWidget().
virtual void MusicAbstractFloatWidget::contextMenuEvent (QContextMenuEvent *) inline final override protected virtual
Definition at line 55 of file musicabstractfloatwidget.h.
void MusicAbstractFloatWidget::enterEvent (QtEnterEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicLrcFloatPhotoWidget, MusicLrcFloatSettingWidget, and MusicLrcFloatPlayWidget.
Definition at line 30 of file musicabstractfloatwidget.cpp.
References animationEnter(), and m_blockAnimation.
Referenced by MusicLrcFloatPlayWidget::enterEvent().
void MusicAbstractFloatWidget::leaveEvent (QEvent * event) override protected virtual
Reimplemented in MusicLrcFloatPhotoWidget, and MusicLrcFloatSettingWidget.
Definition at line 39 of file musicabstractfloatwidget.cpp.
References animationLeave(), and m_blockAnimation.
virtual void MusicAbstractFloatWidget::mouseMoveEvent (QMouseEvent *) inline final override protected virtual
Definition at line 57 of file musicabstractfloatwidget.h.
virtual void MusicAbstractFloatWidget::mousePressEvent (QMouseEvent *) inline final override protected virtual
Definition at line 56 of file musicabstractfloatwidget.h.
virtual void MusicAbstractFloatWidget::mouseReleaseEvent (QMouseEvent *) inline final override protected virtual
Definition at line 58 of file musicabstractfloatwidget.h.
void MusicAbstractFloatWidget::setBlockAnimation (bool b) inline
Set block animation state or not.
Definition at line 47 of file musicabstractfloatwidget.h.
Referenced by MusicLrcFloatWidget::closeFloatSettingWidget(), and MusicLrcFloatWidget::showFloatSettingWidget().
Member Data Documentation
QPropertyAnimation* MusicAbstractFloatWidget::m_animation protected
Definition at line 68 of file musicabstractfloatwidget.h.
Referenced by animationEnter(), animationLeave(), MusicLrcFloatPhotoWidget::close(), MusicLrcFloatSettingWidget::leaveEvent(), MusicAbstractFloatWidget(), and ~MusicAbstractFloatWidget().
bool MusicAbstractFloatWidget::m_blockAnimation protected
Definition at line 70 of file musicabstractfloatwidget.h.
Referenced by enterEvent(), leaveEvent(), and MusicLrcFloatPlayWidget::resizeGeometry().
QRect MusicAbstractFloatWidget::m_rectEnter protected
Definition at line 69 of file musicabstractfloatwidget.h.
Referenced by animationEnter(), animationLeave(), MusicLrcFloatSettingWidget::resizeGeometry(), MusicLrcFloatPlayWidget::resizeGeometry(), MusicVideoFloatWidget::resizeGeometry(), MusicLrcFloatWidget::resizeGeometry(), and MusicLrcFloatPhotoWidget::resizeGeometry().
QRect MusicAbstractFloatWidget::m_rectLeave protected
Definition at line 69 of file musicabstractfloatwidget.h.
Referenced by animationEnter(), animationLeave(), MusicLrcFloatSettingWidget::resizeGeometry(), MusicLrcFloatPlayWidget::resizeGeometry(), MusicVideoFloatWidget::resizeGeometry(), MusicLrcFloatWidget::resizeGeometry(), and MusicLrcFloatPhotoWidget::resizeGeometry().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicabstractfloatwidget.h
TTKModule/TTKWidget/musicCoreKits/musicabstractfloatwidget.cpp