TTKMusicplayer: MusicSongCheckToolsQualityThread Class Reference
MusicSongCheckToolsQualityThread Class Reference
The class of the song check tools quality thread.
#include <musicsongchecktoolsthread.h>
Signals
void finished (const MusicSongCheckToolsQualitys &items)
Public Member Functions
MusicSongCheckToolsQualityThread (QObject *parent=nullptr)
void setQualitySongs (MusicSongs *songs)
Public Member Functions inherited from MusicAbstractThread
MusicAbstractThread (QObject *parent=nullptr)
virtual ~MusicAbstractThread ()
void stopAndQuitThread ()
Protected Member Functions
virtual void run () override
Protected Attributes
MusicSongs * m_songItems
Protected Attributes inherited from MusicAbstractThread
bool m_running
Additional Inherited Members
Public Slots inherited from MusicAbstractThread
void start ()
Detailed Description
The class of the song check tools quality thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 133 of file musicsongchecktoolsthread.h.
Constructor & Destructor Documentation
MusicSongCheckToolsQualityThread::MusicSongCheckToolsQualityThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 125 of file musicsongchecktoolsthread.cpp.
References m_songItems.
Member Function Documentation
void MusicSongCheckToolsQualityThread::finished (const MusicSongCheckToolsQualitys & items) signal
Quality check finished.
Referenced by run().
void MusicSongCheckToolsQualityThread::run () override protected virtual
Thread run now.
Reimplemented from MusicAbstractThread.
Definition at line 136 of file musicsongchecktoolsthread.cpp.
References MusicSongMeta::bitrate(), finished(), MusicAbstractThread::m_running, m_songItems, MusicSongMeta::read(), and MusicAbstractThread::run().
void MusicSongCheckToolsQualityThread::setQualitySongs (MusicSongs * songs)
Set find file path by given path.
Definition at line 131 of file musicsongchecktoolsthread.cpp.
References m_songItems.
Referenced by MusicSongCheckToolsWidget::qualityReCheckButtonClicked().
Member Data Documentation
MusicSongs* MusicSongCheckToolsQualityThread::m_songItems protected
Definition at line 161 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsQualityThread(), run(), and setQualitySongs().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolsthread.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolsthread.cpp