TTKMusicPlayer: MusicConnectTransferThread Class Reference
MusicConnectTransferThread Class Reference
The class of the connect transfer thread.
#include <musicconnecttransferthread.h>
Signals
void transferFileFinished (const QString &name)
Public Member Functions
MusicConnectTransferThread (QObject *parent=nullptr)
void setFilePath (const QString &target, const QStringList &path)
Public Member Functions inherited from TTKAbstractThread
TTKAbstractThread (QObject *parent=nullptr)
Private Member Functions
virtual void run () overridefinal
Private Attributes
QString m_target
QStringList m_path
Additional Inherited Members
Public Slots inherited from TTKAbstractThread
void start ()
void stop ()
Protected Attributes inherited from TTKAbstractThread
bool m_running
Detailed Description
The class of the connect transfer thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicconnecttransferthread.h.
Constructor & Destructor Documentation
MusicConnectTransferThread::MusicConnectTransferThread (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musicconnecttransferthread.cpp.
Member Function Documentation
void MusicConnectTransferThread::run () final override private virtual
Thread run now.
Reimplemented from TTKAbstractThread.
Definition at line 17 of file musicconnecttransferthread.cpp.
References m_path, TTKAbstractThread::m_running, m_target, qAsConst, and transferFileFinished().
void MusicConnectTransferThread::setFilePath (const QString & target, const QStringList & path)
Set copy file path list.
Definition at line 11 of file musicconnecttransferthread.cpp.
References m_path, and m_target.
Referenced by MusicConnectTransferWidget::startToTransferFiles().
void MusicConnectTransferThread::transferFileFinished (const QString & name) signal
Send the transfer file or path.
Referenced by run().
Member Data Documentation
QStringList MusicConnectTransferThread::m_path private
Definition at line 55 of file musicconnecttransferthread.h.
Referenced by run(), and setFilePath().
QString MusicConnectTransferThread::m_target private
Definition at line 54 of file musicconnecttransferthread.h.
Referenced by run(), and setFilePath().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsKits/musicconnecttransferthread.h
TTKModule/TTKCore/musicToolsKits/musicconnecttransferthread.cpp