TTKMusicPlayer: MusicFormats Class Reference
MusicFormats Class Reference
The class of the music formats.
#include <musicformats.h>
Static Public Member Functions
static bool isTrack (const QString &url) noexcept
static bool isRedirection (const QString &url) noexcept
static QStringList supportMusicFormats () noexcept
static QStringList supportMusicInputFilterFormats () noexcept
static QString supportMusicInputFormats () noexcept
static QStringList supportSpekInputFilterFormats () noexcept
static QString supportSpekInputFormats () noexcept
static QString supportPlaylistInputFormats () noexcept
static QString supportPlaylistOutputFormats () noexcept
Detailed Description
The class of the music formats.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicformats.h.
Member Function Documentation
bool MusicFormats::isRedirection (const QString & url) static noexcept
Check song is dedirection valid or not.
Definition at line 10 of file musicformats.cpp.
References Format::isRedirection().
Referenced by MusicSongsListItemInfoWidget::initialize().
bool MusicFormats::isTrack (const QString & url) static noexcept
Check song is track valid or not.
Definition at line 5 of file musicformats.cpp.
References Format::isTrack().
Referenced by TTK::generateSongList(), MusicSongMeta::read(), and TTK::trackRelatedPath().
QStringList MusicFormats::supportMusicFormats () static noexcept
Get player supported formats.
Definition at line 15 of file musicformats.cpp.
References Format::supportMusicFormats().
Referenced by MusicFileAssociationTableWidget::addCellItems(), MusicSongsContainerWidget::importSongsByUrl(), and TTK::supportAssociations().
QStringList MusicFormats::supportMusicInputFilterFormats () static noexcept
Get player supported input filter formats.
Definition at line 20 of file musicformats.cpp.
References Format::supportMusicInputFilterFormats().
Referenced by MusicSongsContainerWidget::dropEvent(), MusicConsoleModule::initialize(), MusicLocalManagerWidget::refreshItems(), MusicSongsManagerThread::run(), and MusicCloudManagerTableWidget::uploadFileDirToServer().
QString MusicFormats::supportMusicInputFormats () static noexcept
Get player supported input format .
Definition at line 25 of file musicformats.cpp.
References Format::supportMusicInputFormats().
Referenced by MusicApplication::importSongsByFiles(), and MusicCloudManagerTableWidget::uploadFilesToServer().
QString MusicFormats::supportPlaylistInputFormats () static noexcept
Get playlist supported input formats.
Definition at line 46 of file musicformats.cpp.
Referenced by MusicApplication::importSongsItemList().
QString MusicFormats::supportPlaylistOutputFormats () static noexcept
Get playlist supported output formats.
Definition at line 65 of file musicformats.cpp.
Referenced by MusicApplication::exportSongsItem(), and MusicApplication::exportSongsItemList().
QStringList MusicFormats::supportSpekInputFilterFormats () static noexcept
Get spek supported input filter formats.
Definition at line 31 of file musicformats.cpp.
Referenced by MusicSpectrumWidget::createLightWidget(), and supportSpekInputFormats().
QString MusicFormats::supportSpekInputFormats () static noexcept
Get spek supported input formats.
Definition at line 41 of file musicformats.cpp.
References supportSpekInputFilterFormats(), and TTK_SPACE.
Referenced by MusicSpectrumWidget::openFileButtonClicked().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicformats.h
TTKModule/TTKCore/musicCoreKits/musicformats.cpp