TTKMusicplayer: MusicObject Namespace Reference
MusicObject Namespace Reference
The namespace of the application object.
Classes
struct MusicSongAttribute
The class of the music song atrribute.
struct MusicSongInformation
The class of the music song information.
Typedefs
typedef struct MusicObject::MusicSongAttribute MusicSongAttribute
The class of the music song atrribute.
typedef struct MusicObject::MusicSongInformation MusicSongInformation
The class of the music song information.
Enumerations
enum PlayState { PS_StoppedState, PS_PlayingState, PS_PausedState }
enum PlayMode {
PM_PlayOrder, PM_PlayRandom, PM_PlaylistLoop, PM_PlayOneLoop,
PM_PlayOnce
}
enum DownLoadMode {
DW_Null, DW_DisConnection, DW_DownLoading, DW_Buffing,
DW_Waiting
}
enum FontStyleMode {
FT_Bold = 0x00001, FT_Italic = 0x00002, FT_Underline = 0x00004, FT_Overline = 0x00008,
FT_StrikeOut = 0x00010, FT_FixedPitch = 0x00020, FT_Kerningt = 0x00040
}
enum NetworkCode { NetworkInit = 0xFFFFF00, NetworkSuccess = 0, NetworkError = -1, NetworkUnKnow = 2 }
enum DownloadType {
DownloadMusic, DownloadLrc, DownloadSmallBackground, DownloadBigBackground,
DownloadVideo, DownloadOther
}
enum RecordType { RecordNull, RecordNormalDownload, RecordCloudDownload, RecordCloudUpload }
enum Program { Recommed, Rank }
enum MusicSongCheckToolsMode { Check, Apply }
Functions
static QString getAppDir ()
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode mode)
Detailed Description
The namespace of the application object.
The namespace of the program type.
The namespace of the network data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Typedef Documentation
typedef struct MusicObject::MusicSongAttribute MusicObject::MusicSongAttribute
The class of the music song atrribute.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
typedef struct MusicObject::MusicSongInformation MusicObject::MusicSongInformation
The class of the music song information.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Enumeration Type Documentation
enum MusicObject::DownLoadMode
Enumerator
DW_Null
network null
DW_DisConnection
network disable
DW_DownLoading
network download
DW_Buffing
network buffing
DW_Waiting
network waiting
Definition at line 275 of file musicobject.h.
enum MusicObject::DownloadType
Enumerator
DownloadMusic
type of dwonlaod music
DownloadLrc
type of dwonlaod lrc
DownloadSmallBackground
type of dwonlaod small background
DownloadBigBackground
type of dwonlaod big background
DownloadVideo
type of dwonlaod video
DownloadOther
type of dwonlaod other user mod
Definition at line 35 of file musicnetworkdefines.h.
enum MusicObject::FontStyleMode
Enumerator
FT_Bold
font bold
FT_Italic
font italic
FT_Underline
font underline
FT_Overline
font overline
FT_StrikeOut
font strikeOut
FT_FixedPitch
font fixedPitch
FT_Kerningt
font kerningt
Definition at line 284 of file musicobject.h.
enum MusicObject::MusicSongCheckToolsMode
Enumerator
Check
Song Check Mode
Apply
Song Apply Mode
Definition at line 9 of file musicsongchecktoolsunit.h.
enum MusicObject::NetworkCode
Enumerator
NetworkInit
Network state init
NetworkSuccess
Network state success
NetworkError
Network state error
NetworkUnKnow
Network state unknow
Definition at line 27 of file musicnetworkdefines.h.
enum MusicObject::PlayMode
Enumerator
PM_PlayOrder
play order
PM_PlayRandom
play random
PM_PlaylistLoop
play list loop
PM_PlayOneLoop
play single loop
PM_PlayOnce
play just once
Definition at line 266 of file musicobject.h.
enum MusicObject::PlayState
Enumerator
PS_StoppedState
stop state
PS_PlayingState
play state
PS_PausedState
pause state
Definition at line 259 of file musicobject.h.
enum MusicObject::Program
Enumerator
Recommed
Rank
Definition at line 29 of file musicdjradioprogramthread.h.
enum MusicObject::RecordType
Enumerator
RecordNull
None File Config
RecordNormalDownload
Local Download File Config
RecordCloudDownload
Cloud Download File Config
RecordCloudUpload
Cloud Upload Failed File Config
Definition at line 45 of file musicnetworkdefines.h.
Function Documentation
static QString MusicObject::getAppDir () static
Get application dir.
Definition at line 298 of file musicobject.h.
Referenced by MusicUtils::QMMP::pluginPath(), and MusicWebMusicRadioWidget::sendToDesktopLink().
MUSIC_NETWORK_EXPORT void MusicObject::setSslConfiguration (QNetworkRequest * request, QSslSocket::PeerVerifyMode mode = QSslSocket::VerifyNone)
Set request ssl configuration.
Definition at line 65 of file musicnetworkabstract.cpp.
Referenced by MusicQQBackgroundThread::downLoadUrl(), MusicKWArtistSimilarThread::getArtistIdName(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQQInterface::getMusicKey(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), MusicDownLoadQueryThreadAbstract::getUrlFileSize(), MusicDownLoadWYInterface::makeTokenQueryRequest(), MusicDownLoadBDInterface::makeTokenQueryUrl(), MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicDownloadQueueCache::MusicDownloadQueueCache(), MusicDownLoadKWInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAlbumInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), MusicDownLoadKWInterface::readFromMusicSongPic(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicDataDownloadThread::startRequest(), MusicWYTextDownLoadThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicDJRadioCategoryThread::startToDownload(), MusicDownloadSourceThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicWYTranslationThread::startToDownload(), MusicRadioSongsThread::startToDownload(), MusicRadioPlaylistThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicRadioChannelThread::startToDownload(), MusicIdentifySongsThread::startToDownload(), MusicTranslationThread::startToDownload(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicMVRadioThreadAbstract::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicDownLoadQueryYYTThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), and MusicDownLoadQueryKWThread::startToSingleSearch().