TTKMusicplayer: MusicFloatAbstractWidget Class Reference
MusicFloatAbstractWidget Class Reference abstract
The class of the float widget base.
#include <musicfloatabstractwidget.h>
Public Member Functions
MusicFloatAbstractWidget (QWidget *parent=nullptr)
virtual ~MusicFloatAbstractWidget ()
void setBlockAnimation (bool b)
virtual void resizeWindow (int width, int height)=0
Protected Member Functions
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *) override
virtual void mouseMoveEvent (QMouseEvent *) override
virtual void mousePressEvent (QMouseEvent *) override
virtual void mouseReleaseEvent (QMouseEvent *) override
void animationIn ()
void animationOut ()
Protected Attributes
QPropertyAnimation * m_animation
QRect m_rectIn
QRect m_rectOut
bool m_blockAnimation
Detailed Description
The class of the float widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicfloatabstractwidget.h.
Constructor & Destructor Documentation
MusicFloatAbstractWidget::MusicFloatAbstractWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicfloatabstractwidget.cpp.
References m_animation, and m_blockAnimation.
MusicFloatAbstractWidget::~MusicFloatAbstractWidget () virtual
Definition at line 11 of file musicfloatabstractwidget.cpp.
References m_animation.
Member Function Documentation
void MusicFloatAbstractWidget::animationIn () protected
Show animation in case.
Definition at line 16 of file musicfloatabstractwidget.cpp.
References m_animation, m_rectIn, and m_rectOut.
Referenced by MusicLrcFloatPhotoWidget::close(), enterEvent(), MusicLrcFloatPlayWidget::resizeWindow(), and MusicLrcFloatSettingWidget::show().
void MusicFloatAbstractWidget::animationOut () protected
Show animation out case.
Definition at line 23 of file musicfloatabstractwidget.cpp.
References m_animation, m_rectIn, and m_rectOut.
Referenced by leaveEvent(), MusicLrcFloatSettingWidget::leaveEvent(), MusicLrcFloatPhotoWidget::show(), and MusicLrcFloatWidget::showFloatSettingWidget().
virtual void MusicFloatAbstractWidget::contextMenuEvent (QContextMenuEvent *) inline override protected virtual
Definition at line 59 of file musicfloatabstractwidget.h.
void MusicFloatAbstractWidget::enterEvent (QEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicLrcFloatPhotoWidget, MusicLrcFloatSettingWidget, and MusicLrcFloatPlayWidget.
Definition at line 30 of file musicfloatabstractwidget.cpp.
References animationIn(), and m_blockAnimation.
Referenced by MusicLrcFloatPlayWidget::enterEvent().
void MusicFloatAbstractWidget::leaveEvent (QEvent * event) override protected virtual
Reimplemented in MusicLrcFloatPhotoWidget, and MusicLrcFloatSettingWidget.
Definition at line 39 of file musicfloatabstractwidget.cpp.
References animationOut(), and m_blockAnimation.
virtual void MusicFloatAbstractWidget::mouseMoveEvent (QMouseEvent *) inline override protected virtual
Reimplemented in MusicLrcFloatPlayWidget.
Definition at line 60 of file musicfloatabstractwidget.h.
virtual void MusicFloatAbstractWidget::mousePressEvent (QMouseEvent *) inline override protected virtual
Reimplemented in MusicLrcFloatPlayWidget.
Definition at line 61 of file musicfloatabstractwidget.h.
virtual void MusicFloatAbstractWidget::mouseReleaseEvent (QMouseEvent *) inline override protected virtual
Reimplemented in MusicLrcFloatPlayWidget.
Definition at line 62 of file musicfloatabstractwidget.h.
virtual void MusicFloatAbstractWidget::resizeWindow (int width, int height) pure virtual
Resize window bound by given width and height. Subclass should implement this function.
Implemented in MusicLrcFloatPhotoWidget, MusicVideoFloatWidget, MusicLrcFloatWidget, MusicLrcFloatPlayWidget, and MusicLrcFloatSettingWidget.
void MusicFloatAbstractWidget::setBlockAnimation (bool b) inline
Set block animation state or not.
Definition at line 46 of file musicfloatabstractwidget.h.
Referenced by MusicLrcFloatWidget::closeFloatSettingWidget(), and MusicLrcFloatWidget::showFloatSettingWidget().
Member Data Documentation
QPropertyAnimation* MusicFloatAbstractWidget::m_animation protected
Definition at line 72 of file musicfloatabstractwidget.h.
Referenced by animationIn(), animationOut(), MusicLrcFloatPhotoWidget::close(), MusicLrcFloatSettingWidget::leaveEvent(), MusicFloatAbstractWidget(), and ~MusicFloatAbstractWidget().
bool MusicFloatAbstractWidget::m_blockAnimation protected
Definition at line 74 of file musicfloatabstractwidget.h.
Referenced by enterEvent(), leaveEvent(), MusicFloatAbstractWidget(), and MusicLrcFloatPlayWidget::resizeWindow().
QRect MusicFloatAbstractWidget::m_rectIn protected
Definition at line 73 of file musicfloatabstractwidget.h.
Referenced by animationIn(), animationOut(), MusicLrcFloatSettingWidget::resizeWindow(), MusicLrcFloatPlayWidget::resizeWindow(), MusicLrcFloatWidget::resizeWindow(), MusicVideoFloatWidget::resizeWindow(), and MusicLrcFloatPhotoWidget::resizeWindow().
QRect MusicFloatAbstractWidget::m_rectOut protected
Definition at line 73 of file musicfloatabstractwidget.h.
Referenced by animationIn(), animationOut(), MusicLrcFloatSettingWidget::resizeWindow(), MusicLrcFloatPlayWidget::resizeWindow(), MusicLrcFloatWidget::resizeWindow(), MusicVideoFloatWidget::resizeWindow(), and MusicLrcFloatPhotoWidget::resizeWindow().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicfloatabstractwidget.h
TTKModule/TTKWidget/musicCoreKits/musicfloatabstractwidget.cpp