TTKMusicPlayer: MusicSongCheckToolsQualityTableWidget Class Reference
MusicSongCheckToolsQualityTableWidget Class Reference
The class of the song check tools quality table widget.
#include <musicsongchecktoolstablewidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void addSongToPlaylist (const QStringList &items)
Public Member Functions
MusicSongCheckToolsQualityTableWidget (QWidget *parent=nullptr)
~MusicSongCheckToolsQualityTableWidget ()
void addCellItems (const MusicSongCheckToolsQualityList &songs)
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
TTKIntList uncheckedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Private Member Functions
void playSong ()
void removeCurrentRow ()
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the song check tools quality table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 110 of file musicsongchecktoolstablewidget.h.
Constructor & Destructor Documentation
MusicSongCheckToolsQualityTableWidget::MusicSongCheckToolsQualityTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 200 of file musicsongchecktoolstablewidget.cpp.
References G_CONNECTION_PTR, and makeButtonItemDelegate().
MusicSongCheckToolsQualityTableWidget::~MusicSongCheckToolsQualityTableWidget ()
Object destructor.
Definition at line 228 of file musicsongchecktoolstablewidget.cpp.
References G_CONNECTION_PTR.
Member Function Documentation
void MusicSongCheckToolsQualityTableWidget::addCellItems (const MusicSongCheckToolsQualityList & songs)
Create cell items by input data.
Definition at line 233 of file musicsongchecktoolstablewidget.cpp.
References TTK::Number::bitrateToLevel(), TTK::Number::bitrateToQuality(), MusicSong::duration(), TTK::Widget::elidedText(), MusicSongCheckToolsQuality::m_bitrate, MusicSongCheckToolsQuality::m_song, MusicSong::name(), MusicSong::path(), QtItemSetTextAlignment, MusicSong::sizeStr(), TTK_CHECKED_ROLE, TTK_DATA_ROLE, and TTK_DISPLAY_ROLE.
void MusicSongCheckToolsQualityTableWidget::addSongToPlaylist (const QStringList & items) signal
Add current selected song to playlist.
Referenced by playSong().
void MusicSongCheckToolsQualityTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 287 of file musicsongchecktoolstablewidget.cpp.
References MusicFillItemTableWidget::itemCellClicked(), playSong(), and removeCurrentRow().
void MusicSongCheckToolsQualityTableWidget::playSong () private
Add selected music song path to list.
Definition at line 298 of file musicsongchecktoolstablewidget.cpp.
References addSongToPlaylist(), TTKAbstractTableWidget::isValid(), and TTK_DATA_ROLE.
Referenced by itemCellClicked().
void MusicSongCheckToolsQualityTableWidget::removeCurrentRow () private
Remove current selected row.
Definition at line 313 of file musicsongchecktoolstablewidget.cpp.
References TTKAbstractTableWidget::isValid().
Referenced by itemCellClicked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolstablewidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolstablewidget.cpp