TTKMusicPlayer: MusicWebMVRadioInfoTableWidget Class Reference
MusicWebMVRadioInfoTableWidget Class Reference
The class of the music mv info table widget.
#include <musicwebmvradioinfowidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
virtual void itemDoubleClicked (int row, int column) overridefinal
void actionChanged (QAction *action)
Public Slots inherited from MusicItemQueryTableWidget
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) override
virtual void itemDoubleClicked (int row, int column) override
virtual void removeItems () overridefinal
virtual void createSearchedItem (const MusicResultInfoItem &songItem) override
void createFinishedItem ()
void menuActionChanged (QAction *action)
Public Slots inherited from MusicQueryTableWidget
virtual void itemDoubleClicked (int row, int column)=0
virtual void createSearchedItem (const MusicResultInfoItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool check)
void checkedItemsStatus (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicWebMVRadioInfoTableWidget (QWidget *parent=nullptr)
~MusicWebMVRadioInfoTableWidget ()
virtual void setQueryInput (MusicAbstractQueryRequest *query) overridefinal
virtual void musicDownloadLocal (int row) overridefinal
Public Member Functions inherited from MusicItemQueryTableWidget
MusicItemQueryTableWidget (QWidget *parent=nullptr)
~MusicItemQueryTableWidget ()
virtual void startSearchQuery (const QString &text) overridefinal
void downloadDataFrom (bool play)
void downloadBatchData (bool music)
void resizeSection ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
MusicAbstractQueryRequest * getQueryInput () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void songBufferToPlaylist (const MusicResultDataItem &songItem)
void restartSearchQuery (const QString &name)
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicQueryTableWidget
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
MusicCheckBoxDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the music mv info table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicwebmvradioinfowidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioInfoTableWidget::MusicWebMVRadioInfoTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicwebmvradioinfowidget.cpp.
MusicWebMVRadioInfoTableWidget::~MusicWebMVRadioInfoTableWidget ()
Definition at line 17 of file musicwebmvradioinfowidget.cpp.
References MusicItemQueryTableWidget::removeItems().
Member Function Documentation
void MusicWebMVRadioInfoTableWidget::actionChanged (QAction * action) slot
Menu action type changed.
Definition at line 71 of file musicwebmvradioinfowidget.cpp.
References itemCellClicked(), MusicQueryTableWidget::m_networkRequest, and MusicAbstractQueryRequest::songInfoList().
Referenced by contextMenuEvent().
void MusicWebMVRadioInfoTableWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Reimplemented from MusicItemQueryTableWidget.
Definition at line 88 of file musicwebmvradioinfowidget.cpp.
References actionChanged(), MusicQueryTableWidget::m_networkRequest, MusicUIObject::MQSSMenuStyle02, and MusicAbstractQueryRequest::songInfoList().
void MusicWebMVRadioInfoTableWidget::itemCellClicked (int row, int column) final override virtual slot
Subclass should implement this function.
Definition at line 44 of file musicwebmvradioinfowidget.cpp.
References MusicRightAreaWidget::instance(), MusicFillItemTableWidget::itemCellClicked(), MusicQueryTableWidget::m_networkRequest, musicDownloadLocal(), MusicRightAreaWidget::musicMovieRadioSearch(), and MusicAbstractQueryRequest::songInfoList().
Referenced by actionChanged(), and itemDoubleClicked().
void MusicWebMVRadioInfoTableWidget::itemDoubleClicked (int row, int column) final override virtual slot
Table widget item cell double clicked.
Definition at line 65 of file musicwebmvradioinfowidget.cpp.
References itemCellClicked().
void MusicWebMVRadioInfoTableWidget::musicDownloadLocal (int row) final override virtual
Data download to local file.
Reimplemented from MusicItemQueryTableWidget.
Definition at line 31 of file musicwebmvradioinfowidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::Movie, MusicDownloadWidget::setSongName(), MusicAbstractMoveWidget::show(), and MusicAbstractQueryRequest::songInfoList().
Referenced by itemCellClicked().
void MusicWebMVRadioInfoTableWidget::setQueryInput (MusicAbstractQueryRequest * query) final override virtual
Set network query input.
Reimplemented from MusicItemQueryTableWidget.
Definition at line 22 of file musicwebmvradioinfowidget.cpp.
References MusicQueryTableWidget::m_networkRequest, and MusicItemQueryTableWidget::setQueryInput().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioinfowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioinfowidget.cpp