TTKMusicplayer: MusicWYQueryInterface Class Reference
MusicWYQueryInterface Class Reference
The class of wangyi query interface.
#include <musicwyqueryinterface.h>
Public Member Functions
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
Detailed Description
The class of wangyi query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 97 of file musicwyqueryinterface.h.
Member Function Documentation
QByteArray MusicWYQueryInterface::makeTokenQueryUrl (QNetworkRequest * request, const QString & query, const QString & type)
Make token query url string.
Definition at line 19 of file musicwyqueryinterface.cpp.
References QAlgorithm::Aes::encryptCBC(), MusicWYInterface::makeRequestRawHeader(), MusicUtils::Url::urlEncode(), and WY_SECKRY_STRING.
Referenced by MusicWYQueryArtistRequest::downLoadIntro(), MusicWYQueryMovieRequest::queryArtistMoviesCount(), MusicWYQueryMovieRequest::queryMovieList(), MusicWYQueryPlaylistRequest::queryPlaylistInfo(), MusicDJRadioProgramCategoryRequest::queryProgramInfo(), MusicWYQueryMovieRequest::queryVideoList(), MusicWYQueryMovieRequest::queryVideoUrlPath(), readFromMusicSongAttributeNew(), MusicDJRadioCategoryRequest::startToDownload(), MusicDJRadioProgramRequest::startToDownload(), MusicWYQueryArtistListRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicWYArtistSimilarRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicWYQueryRecommendRequest::startToSearch(), MusicWYSongSuggestRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSingleSearch(), and MusicWYQueryRequest::startToSingleSearch().
void MusicWYQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 32 of file musicwyqueryinterface.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicWYInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), readFromMusicSongAttributeNew(), MusicUtils::Number::sizeByte2Label(), MusicObject::syncNetworkQueryForGet(), and WY_SONG_INFO_OLD_URL.
Referenced by MusicWYQueryRecommendRequest::downLoadFinished(), MusicDJRadioProgramCategoryRequest::queryDetailsFinished(), readFromMusicSongAttribute(), readFromMusicSongAttributeNew(), and MusicWYQueryRequest::singleDownLoadFinished().
void MusicWYQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 80 of file musicwyqueryinterface.cpp.
References MB_1000, MB_128, MB_192, MB_320, and readFromMusicSongAttribute().
Referenced by readFromMusicSongAttribute().
void MusicWYQueryInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 151 of file musicwyqueryinterface.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicUtils::Number::sizeByte2Label(), MusicObject::syncNetworkQueryForPost(), WY_SONG_PATH_DATA_URL, and WY_SONG_PATH_URL.
Referenced by MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicWYQueryPlaylistRequest::queryDetailsFinished(), and readFromMusicSongAttribute().
void MusicWYQueryInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 197 of file musicwyqueryinterface.cpp.
References MB_1000, MB_128, MB_192, MB_320, and readFromMusicSongAttribute().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyqueryinterface.cpp