TTKMusicPlayer: MusicPlaylistBackupWidget Class Reference
MusicPlaylistBackupWidget Class Reference
The class of the playlist backup widget.
#include <musicplaylistbackupwidget.h>
Public Member Functions
MusicPlaylistBackupWidget (QWidget *parent=nullptr)
~MusicPlaylistBackupWidget ()
virtual void resizeWidget () overridefinal
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Slots
void exportButtonClicked ()
void restoreButtonClicked ()
void currentDateChanged (const QString &text)
void currentTimeChanged (int index)
void currentItemChanged (int index)
Private Member Functions
void initialize ()
Private Attributes
QComboBox * m_dateBox
QComboBox * m_timeBox
QLabel * m_titleLabel
QListWidget * m_listWidget
MusicSongItemList m_items
MusicPlaylistBackupTableWidget * m_tableWidget
Detailed Description
The class of the playlist backup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 67 of file musicplaylistbackupwidget.h.
Constructor & Destructor Documentation
MusicPlaylistBackupWidget::MusicPlaylistBackupWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 86 of file musicplaylistbackupwidget.cpp.
References TTK::UI::BackgroundStyle10, TTK::UI::BorderStyle02, TTK::UI::ColorStyle01, TTK::UI::ColorStyle02, TTK::UI::ColorStyle03, TTK::UI::ColorStyle05, TTK::UI::ColorStyle08, currentDateChanged(), currentItemChanged(), currentTimeChanged(), exportButtonClicked(), TTK::Widget::generateComboBoxStyle(), initialize(), TTK::UI::ListWidgetStyle02, m_dateBox, m_listWidget, m_tableWidget, m_timeBox, m_titleLabel, TTK::UI::PushButtonStyle03, restoreButtonClicked(), and TTK::UI::ScrollBarStyle03.
MusicPlaylistBackupWidget::~MusicPlaylistBackupWidget ()
Definition at line 229 of file musicplaylistbackupwidget.cpp.
References m_dateBox, m_listWidget, m_tableWidget, m_timeBox, and m_titleLabel.
Member Function Documentation
void MusicPlaylistBackupWidget::currentDateChanged (const QString & text) private slot
Current backup date changed.
Definition at line 286 of file musicplaylistbackupwidget.cpp.
References TTKDateTime::format(), m_listWidget, m_timeBox, ROOT_PATH, and TTK_TIMES_FORMAT.
Referenced by MusicPlaylistBackupWidget().
void MusicPlaylistBackupWidget::currentItemChanged (int index) private slot
Current backup list item changed.
Definition at line 334 of file musicplaylistbackupwidget.cpp.
References TTK::Widget::elidedTitleText(), G_SETTING_PTR, MusicSongItem::m_itemName, m_items, MusicSongItem::m_songs, m_tableWidget, m_titleLabel, MusicAbstractSongsListTableWidget::setSongsList(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicPlaylistBackupWidget().
void MusicPlaylistBackupWidget::currentTimeChanged (int index) private slot
Current backup time changed.
Definition at line 301 of file musicplaylistbackupwidget.cpp.
References TTK::Widget::elidedTitleText(), TTKAbstractXml::fromFile(), m_dateBox, m_items, m_listWidget, m_timeBox, qAsConst, MusicTKPLConfigManager::readBuffer(), ROOT_PATH, TKF_FILE, TTK_LOG_STREAM, TTK_SEPARATOR, and TTKStaticCast.
Referenced by MusicPlaylistBackupWidget().
void MusicPlaylistBackupWidget::exportButtonClicked () private slot
Export button clicked.
Definition at line 252 of file musicplaylistbackupwidget.cpp.
References TTK::File::copyPath(), MusicAbstractMoveDialog::exec(), TTK::File::getExistingDirectory(), ROOT_PATH, and MusicMessageBox::setText().
Referenced by MusicPlaylistBackupWidget().
void MusicPlaylistBackupWidget::initialize () private
Init parameters.
Definition at line 350 of file musicplaylistbackupwidget.cpp.
References m_dateBox, ROOT_PATH, and MusicPlaylistBackupModule::runBackup().
Referenced by MusicPlaylistBackupWidget().
void MusicPlaylistBackupWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 238 of file musicplaylistbackupwidget.cpp.
References TTK::Widget::elidedTitleText(), G_SETTING_PTR, m_tableWidget, m_titleLabel, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
void MusicPlaylistBackupWidget::restoreButtonClicked () private slot
Restore button clicked.
Definition at line 268 of file musicplaylistbackupwidget.cpp.
References MusicAbstractMoveDialog::exec(), MusicSongsContainerWidget::instance(), m_items, m_listWidget, MusicMessageBox::setText(), and MusicSongsContainerWidget::updateSongItem().
Referenced by MusicPlaylistBackupWidget().
Member Data Documentation
QComboBox* MusicPlaylistBackupWidget::m_dateBox private
Definition at line 111 of file musicplaylistbackupwidget.h.
Referenced by currentTimeChanged(), initialize(), MusicPlaylistBackupWidget(), and ~MusicPlaylistBackupWidget().
MusicSongItemList MusicPlaylistBackupWidget::m_items private
Definition at line 114 of file musicplaylistbackupwidget.h.
Referenced by currentItemChanged(), currentTimeChanged(), and restoreButtonClicked().
QListWidget* MusicPlaylistBackupWidget::m_listWidget private
Definition at line 113 of file musicplaylistbackupwidget.h.
Referenced by currentDateChanged(), currentTimeChanged(), MusicPlaylistBackupWidget(), restoreButtonClicked(), and ~MusicPlaylistBackupWidget().
MusicPlaylistBackupTableWidget* MusicPlaylistBackupWidget::m_tableWidget private
Definition at line 115 of file musicplaylistbackupwidget.h.
Referenced by currentItemChanged(), MusicPlaylistBackupWidget(), resizeWidget(), and ~MusicPlaylistBackupWidget().
QComboBox * MusicPlaylistBackupWidget::m_timeBox private
Definition at line 111 of file musicplaylistbackupwidget.h.
Referenced by currentDateChanged(), currentTimeChanged(), MusicPlaylistBackupWidget(), and ~MusicPlaylistBackupWidget().
QLabel* MusicPlaylistBackupWidget::m_titleLabel private
Definition at line 112 of file musicplaylistbackupwidget.h.
Referenced by currentItemChanged(), MusicPlaylistBackupWidget(), resizeWidget(), and ~MusicPlaylistBackupWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicplaylistbackupwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicplaylistbackupwidget.cpp