TTKMusicplayer: MusicXMQueryInterface Class Reference
MusicXMQueryInterface Class Reference
The class to xiami query interface.
#include <musicxmqueryinterface.h>
Public Member Functions
bool makeTokenQueryCookies (QString &tk, QString &tke)
void makeTokenQueryUrl (QNetworkRequest *request, bool mode, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariant &key, const QString &quality, bool all)
void readFromMusicSongLrc (MusicObject::MusicSongInformation *info)
Detailed Description
The class to xiami query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 83 of file musicxmqueryinterface.h.
Member Function Documentation
bool MusicXMQueryInterface::makeTokenQueryCookies (QString & tk, QString & tke)
Make token query cookies string.
Definition at line 15 of file musicxmqueryinterface.cpp.
References ALG_UA_KEY, APP_KEY, MusicSemaphoreLoop::exec(), MusicUtils::Algorithm::mdII(), MusicUtils::Codec::toUtf8(), XM_COOKIE_URL, and XM_UA_URL.
Referenced by makeTokenQueryUrl().
void MusicXMQueryInterface::makeTokenQueryUrl (QNetworkRequest * request, bool mode, const QString & query, const QString & type)
Make token query url string.
Definition at line 53 of file musicxmqueryinterface.cpp.
References ALG_UA_KEY, APP_KEY, makeTokenQueryCookies(), MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), MusicObject::setSslConfiguration(), MusicTime::timestamp(), MusicUtils::Codec::toUtf8(), XM_ACS_BASE_URL, XM_BASE_DATA_URL, XM_BASE_URL, and XM_UA_URL.
Referenced by MusicXMQueryArtistRequest::getDownLoadIntro(), MusicXMQueryPlaylistRequest::getPlaylistInfo(), MusicXMQueryMovieRequest::readFromMusicMVAttribute(), readFromMusicSongLrc(), MusicXMSongCommentsRequest::startToPage(), MusicXMQueryRequest::startToPage(), MusicXMQueryMovieRequest::startToPage(), MusicXMQueryPlaylistRequest::startToPage(), MusicXMPlaylistCommentsRequest::startToPage(), MusicXMQueryArtistRequest::startToSearch(), MusicXMQueryAlbumRequest::startToSearch(), MusicXMDiscoverListRequest::startToSearch(), MusicXMQueryRecommendRequest::startToSearch(), MusicXMArtistSimilarRequest::startToSearch(), MusicXMQueryMovieRequest::startToSearch(), MusicXMSongSuggestRequest::startToSearch(), MusicXMQueryToplistRequest::startToSearch(), MusicXMQueryPlaylistRequest::startToSearch(), MusicXMQueryAlbumRequest::startToSingleSearch(), and MusicXMQueryRequest::startToSingleSearch().
void MusicXMQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate)
Read tags(size) from query results.
Definition at line 123 of file musicxmqueryinterface.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, and MusicUtils::Number::size2Label().
Referenced by MusicXMQueryArtistRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), readFromMusicSongAttribute(), and MusicXMQueryRequest::singleDownLoadFinished().
void MusicXMQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariant & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 143 of file musicxmqueryinterface.cpp.
References MB_128, MB_192, MB_32, MB_320, MB_500, readFromMusicSongAttribute(), and MusicUtils::Number::transfromBitrateToNormal().
void MusicXMQueryInterface::readFromMusicSongLrc (MusicObject::MusicSongInformation * info)
Read tags(lrc) from query results.
Definition at line 74 of file musicxmqueryinterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongInformation::m_songId, makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QJson::Parser::parse(), XM_SONG_LRC_DATA_URL, and XM_SONG_LRC_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/xm/musicxmqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/xm/musicxmqueryinterface.cpp