TTKMusicplayer: MusicSongsListTableWidget Class Reference
MusicSongsListTableWidget Class Reference
The class of the songs list table widget.
#include <musicsongslisttablewidget.h>
Public Slots
virtual void listCellEntered (int row, int column) override
virtual void listCellClicked (int row, int column) override
virtual void setDeleteItemAt () override
void setDeleteItemWithFile ()
void showTimeOut ()
void stayTimeOut ()
void setChangSongName ()
void musicMakeRingWidget ()
void musicTransformWidget ()
void musicSongMovieFoundPy ()
void musicSimilarFoundWidgetPy ()
void musicSongSharedWidgetPy ()
void musicSongKMicroWidgetPy ()
void musicSearchQuery (QAction *action)
void musicAddToPlayLater ()
void musicAddToPlayedList ()
void setItemRenameFinished (const QString &name)
void musicListSongSortBy (QAction *action)
Public Slots inherited from MusicSongsListAbstractTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
Public Slots inherited from MusicSlowMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void musicAddNewFiles ()
void musicAddNewDir ()
void isSearchFileListEmpty (bool &empty)
void deleteItemAt (const MusicObject::MIntList &index, bool fileRemove)
void getMusicIndexSwaped (int before, int after, int play, MusicSongs &songs)
void musicListSongToLovestListAt (bool oper, int row)
void showFloatWidget ()
void musicListSongSortBy (int index)
Signals inherited from MusicSongsListAbstractTableWidget
void isCurrentIndexs (bool &state)
Public Member Functions
MusicSongsListTableWidget (int index, QWidget *parent=0)
virtual ~MusicSongsListTableWidget ()
virtual void updateSongsFileName (const MusicSongs &songs) override
void clearAllItems ()
void setMusicSongsSearchedFileName (MusicSongs *songs, const MusicObject::MIntList &fileIndexs)
virtual void selectRow (int index) override
int getPlayRowIndex () const
void setMusicSort (MusicSort *sort)
void setTimerLabel (const QString &time, const QString &total) const
void updateCurrentArtist ()
void replacePlayWidgetRow ()
bool createUploadFileWidget ()
Public Member Functions inherited from MusicSongsListAbstractTableWidget
MusicSongsListAbstractTableWidget (QWidget *parent=0)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSlowMovingTableWidget
MusicSlowMovingTableWidget (QWidget *parent=0)
virtual ~MusicSlowMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicSongsListAbstractTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicSlowMovingTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void wheelEvent (QWheelEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
void closeRenameItem ()
void startToDrag ()
void createContextMenu (QMenu &menu)
Protected Member Functions inherited from MusicSongsListAbstractTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
int m_dragStartIndex
QPoint m_dragStartPoint
bool m_mouseMoved
QTimer m_timerShow
QTimer m_timerStay
MusicOpenFileWidget * m_openFileWidget
MusicSongsListItemInfoWidget * m_musicSongsInfoWidget
MusicSongsListPlayWidget * m_musicSongsPlayWidget
bool m_leftButtonPressed
bool m_listHasSearched
bool m_renameActived
bool m_deleteItemWithFile
QTableWidgetItem * m_renameItem
MusicSort * m_musicSort
Protected Attributes inherited from MusicSongsListAbstractTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSlowMovingTableWidget
bool m_isFirstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the songs list table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 23 of file musicsongslisttablewidget.h.
Constructor & Destructor Documentation
MusicSongsListTableWidget::MusicSongsListTableWidget (int index, QWidget * parent = 0) explicit
Definition at line 36 of file musicsongslisttablewidget.cpp.
References m_deleteItemWithFile, m_dragStartIndex, m_leftButtonPressed, m_listHasSearched, m_mouseMoved, m_musicSort, MusicSongsListAbstractTableWidget::m_parentToolIndex, m_renameActived, m_renameItem, m_timerShow, m_timerStay, MusicUtils::Widget::setTransparent(), showTimeOut(), and stayTimeOut().
MusicSongsListTableWidget::~MusicSongsListTableWidget () virtual
Object contsructor.
Definition at line 68 of file musicsongslisttablewidget.cpp.
References clearAllItems(), m_listHasSearched, MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsInfoWidget, m_musicSongsPlayWidget, and m_openFileWidget.
Member Function Documentation
void MusicSongsListTableWidget::clearAllItems ()
Update songs file names in table.
Definition at line 119 of file musicsongslisttablewidget.cpp.
References MusicAbstractTableWidget::clear(), m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, and ROW_HIGHT.
Referenced by MusicSongsSummariziedWidget::musicListSongSortBy(), MusicSongsSummariziedWidget::musicListSongToLovestListAt(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), setMusicSongsSearchedFileName(), MusicSongsSummariziedWidget::setRecentMusicSongs(), and ~MusicSongsListTableWidget().
void MusicSongsListTableWidget::closeRenameItem () protected
Override the widget event.
Definition at line 778 of file musicsongslisttablewidget.cpp.
References MusicUtils::Widget::elidedText(), m_renameActived, and m_renameItem.
Referenced by leaveEvent(), mousePressEvent(), and wheelEvent().
void MusicSongsListTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 689 of file musicsongslisttablewidget.cpp.
References createContextMenu(), MusicSongsListAbstractTableWidget::createMoreMenu(), MusicApplication::getPlayMode(), MusicApplication::instance(), isSearchFileListEmpty(), MusicSort::m_index, m_musicSort, MusicSongsListAbstractTableWidget::m_parentToolIndex, MusicSort::m_sortType, MusicUIObject::MMenuStyle02, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, musicAddNewDir(), musicAddNewFiles(), musicAddToPlayedList(), musicAddToPlayLater(), MusicSongsListAbstractTableWidget::musicAlbumFoundWidget(), MusicSongsListAbstractTableWidget::musicFileInformation(), musicListSongSortBy(), musicMakeRingWidget(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicPlayClicked(), MusicSongsListAbstractTableWidget::musicSongDownload(), MusicSongsListAbstractTableWidget::musicSongMovieFound(), musicTransformWidget(), MusicObject::PM_PlayListLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, MusicObject::PM_PlayRandom, setChangSongName(), MusicSongsListAbstractTableWidget::setDeleteItemAll(), setDeleteItemAt(), and setDeleteItemWithFile().
void MusicSongsListTableWidget::createContextMenu (QMenu & menu) protected
Start to drag to play list.
Definition at line 853 of file musicsongslisttablewidget.cpp.
References DEFAULT_INDEX_LEVEL1, DEFAULT_INDEX_LEVEL5, MusicSongsListAbstractTableWidget::getCurrentSongName(), musicSearchQuery(), MusicUtils::String::songName(), and MusicUtils::String::splitString().
Referenced by contextMenuEvent().
bool MusicSongsListTableWidget::createUploadFileWidget ()
Replace current play widget row.
Definition at line 250 of file musicsongslisttablewidget.cpp.
References MusicOpenFileWidget::adjustRect(), MusicSongsListAbstractTableWidget::m_musicSongs, m_openFileWidget, MusicSongsListAbstractTableWidget::m_parentToolIndex, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, MUSIC_RECENT_LIST, musicAddNewDir(), and musicAddNewFiles().
Referenced by MusicSongsSummariziedWidget::setDeleteItemAt(), and updateSongsFileName().
void MusicSongsListTableWidget::deleteItemAt (const MusicObject::MIntList & index, bool fileRemove) signal
Check current list is searched or not.
Referenced by setDeleteItemAt().
QString MusicSongsListTableWidget::getClassName () static
Definition at line 80 of file musicsongslisttablewidget.cpp.
void MusicSongsListTableWidget::getMusicIndexSwaped (int before, int after, int play, MusicSongs & songs) signal
Delete items from indexs and check remove file or not.
Referenced by startToDrag().
int MusicSongsListTableWidget::getPlayRowIndex () const inline
Select the current play row.
Definition at line 55 of file musicsongslisttablewidget.h.
References MusicSongsListAbstractTableWidget::m_playRowIndex.
void MusicSongsListTableWidget::isSearchFileListEmpty (bool & empty) signal
Add new music dir to list.
Referenced by contextMenuEvent(), listCellClicked(), and startToDrag().
void MusicSongsListTableWidget::leaveEvent (QEvent * event) override protected virtual
Definition at line 672 of file musicsongslisttablewidget.cpp.
References closeRenameItem(), listCellEntered(), and m_musicSongsInfoWidget.
void MusicSongsListTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell enter.
Definition at line 352 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicApplication::instance(), isSearchFileListEmpty(), musicAddToPlayLater(), MusicApplication::musicListLovestContains(), musicListSongToLovestListAt(), MusicSongsListAbstractTableWidget::musicSongMovieFound(), and setDeleteItemAt().
void MusicSongsListTableWidget::listCellEntered (int row, int column) override virtual slot
Music list songs sort by type.
clear previous table item state
draw new table item state
Definition at line 275 of file musicsongslisttablewidget.cpp.
References MusicApplication::instance(), MusicAbstractTableWidget::listCellEntered(), MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsInfoWidget, MusicAbstractTableWidget::m_previousColorRow, m_timerShow, m_timerStay, MT_S2MS, and MusicApplication::musicListLovestContains().
Referenced by leaveEvent().
void MusicSongsListTableWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 650 of file musicsongslisttablewidget.cpp.
References m_dragStartPoint, m_leftButtonPressed, and m_mouseMoved.
void MusicSongsListTableWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Music list songs sort by type.
Definition at line 637 of file musicsongslisttablewidget.cpp.
References closeRenameItem(), m_dragStartIndex, m_dragStartPoint, and m_leftButtonPressed.
void MusicSongsListTableWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 661 of file musicsongslisttablewidget.cpp.
References m_leftButtonPressed, m_mouseMoved, and startToDrag().
void MusicSongsListTableWidget::musicAddNewDir () signal
Add new music file or files to list.
Referenced by contextMenuEvent(), and createUploadFileWidget().
void MusicSongsListTableWidget::musicAddNewFiles () signal
Create upload file widget.
Referenced by contextMenuEvent(), and createUploadFileWidget().
void MusicSongsListTableWidget::musicAddToPlayedList () slot
Add music to played list and play later.
Definition at line 601 of file musicsongslisttablewidget.cpp.
References MusicPlayedListPopWidget::append(), MusicPlayedListPopWidget::instance(), MusicSongsListAbstractTableWidget::m_musicSongs, and MusicSongsListAbstractTableWidget::m_parentToolIndex.
Referenced by contextMenuEvent().
void MusicSongsListTableWidget::musicAddToPlayLater () slot
Open music song search query.
Definition at line 590 of file musicsongslisttablewidget.cpp.
References MusicPlayedListPopWidget::insert(), MusicPlayedListPopWidget::instance(), MusicSongsListAbstractTableWidget::m_musicSongs, and MusicSongsListAbstractTableWidget::m_parentToolIndex.
Referenced by contextMenuEvent(), and listCellClicked().
void MusicSongsListTableWidget::musicListSongSortBy (int index) signal
Show the float function widget.
Referenced by contextMenuEvent(), and musicListSongSortBy().
void MusicSongsListTableWidget::musicListSongSortBy (QAction * action) slot
Rename item artist label is finised.
Definition at line 617 of file musicsongslisttablewidget.cpp.
References MusicSort::m_index, m_musicSort, MusicSongsListAbstractTableWidget::m_parentToolIndex, MusicSort::m_sortType, and musicListSongSortBy().
void MusicSongsListTableWidget::musicListSongToLovestListAt (bool oper, int row) signal
Swap the current play index when user drag and drop.
Referenced by listCellClicked().
void MusicSongsListTableWidget::musicMakeRingWidget () slot
Reset item name by current row.
Definition at line 508 of file musicsongslisttablewidget.cpp.
References MusicSongRingtoneMaker::exec().
Referenced by contextMenuEvent().
void MusicSongsListTableWidget::musicSearchQuery (QAction * action) slot
Open music song KMicro widget in play widget.
Definition at line 570 of file musicsongslisttablewidget.cpp.
References DEFAULT_INDEX_LEVEL1, MusicSongsListAbstractTableWidget::getCurrentSongName(), MusicRightAreaWidget::instance(), SEARCH_ITEM_DEFINE, MusicUtils::String::songName(), MusicRightAreaWidget::songResearchButtonSearched(), and MusicUtils::String::splitString().
Referenced by createContextMenu().
void MusicSongsListTableWidget::musicSimilarFoundWidgetPy () slot
To search song mv by song name in play widget.
Definition at line 538 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::getSongName(), MusicRightAreaWidget::instance(), MusicSongsListAbstractTableWidget::m_playRowIndex, and MusicRightAreaWidget::musicSimilarFound().
void MusicSongsListTableWidget::musicSongKMicroWidgetPy () slot
Open music song shared widget in play widget.
Definition at line 560 of file musicsongslisttablewidget.cpp.
References MusicLeftAreaWidget::createSoundKMicroWidget(), MusicSongsListAbstractTableWidget::getSongName(), MusicLeftAreaWidget::instance(), and MusicSongsListAbstractTableWidget::m_playRowIndex.
void MusicSongsListTableWidget::musicSongMovieFoundPy () slot
Open music transform widget.
Definition at line 528 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::getSongName(), MusicRightAreaWidget::instance(), MusicSongsListAbstractTableWidget::m_playRowIndex, and MusicRightAreaWidget::musicVideoButtonSearched().
void MusicSongsListTableWidget::musicSongSharedWidgetPy () slot
Open music similar found widget in play widget.
Definition at line 548 of file musicsongslisttablewidget.cpp.
References MusicSongSharingWidget::exec(), MusicSongsListAbstractTableWidget::getSongName(), MusicSongsListAbstractTableWidget::m_playRowIndex, and MusicSongSharingWidget::setSongName().
void MusicSongsListTableWidget::musicTransformWidget () slot
Open music make ring widget.
Definition at line 518 of file musicsongslisttablewidget.cpp.
References MusicTransformWidget::exec().
Referenced by contextMenuEvent().
void MusicSongsListTableWidget::replacePlayWidgetRow ()
Update current artist when it download finished.
Definition at line 215 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicUtils::Widget::elidedText(), MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, MusicUIObject::MColorStyle12_S, and ROW_HIGHT.
Referenced by selectRow(), and setDeleteItemAt().
void MusicSongsListTableWidget::selectRow (int index) override virtual
Set current searched file indexs.
Reimplemented from MusicSongsListAbstractTableWidget.
Definition at line 170 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, replacePlayWidgetRow(), ROW_HIGHT, MusicSongsListAbstractTableWidget::selectRow(), and MusicSongsListPlayWidget::setParameter().
Referenced by startToDrag().
void MusicSongsListTableWidget::setChangSongName () slot
Hide play item information widget.
Definition at line 488 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, m_renameActived, m_renameItem, and MusicSongsListPlayWidget::setItemRename().
Referenced by contextMenuEvent().
void MusicSongsListTableWidget::setDeleteItemAt () override virtual slot
Table widget list cell click.
Definition at line 408 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), deleteItemAt(), MusicMessageBox::exec(), MusicPlayedListPopWidget::instance(), m_deleteItemWithFile, MusicSongsListAbstractTableWidget::m_musicSongs, MusicSongsListAbstractTableWidget::m_parentToolIndex, MusicSongsListAbstractTableWidget::m_playRowIndex, MusicPlayedListPopWidget::remove(), replacePlayWidgetRow(), MusicMessageBox::setText(), MusicProgressWidget::setTitle(), and MusicProgressWidget::show().
Referenced by contextMenuEvent(), listCellClicked(), and setDeleteItemWithFile().
void MusicSongsListTableWidget::setDeleteItemWithFile () slot
Delete item from list at current row.
Definition at line 459 of file musicsongslisttablewidget.cpp.
References m_deleteItemWithFile, and setDeleteItemAt().
Referenced by contextMenuEvent().
void MusicSongsListTableWidget::setItemRenameFinished (const QString & name) slot
Add music to played list.
Definition at line 612 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::m_playRowIndex.
void MusicSongsListTableWidget::setMusicSongsSearchedFileName (MusicSongs * songs, const MusicObject::MIntList & fileIndexs)
Clear All Items.
Definition at line 134 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), clearAllItems(), m_listHasSearched, MusicSongsListAbstractTableWidget::m_musicSongs, and updateSongsFileName().
Referenced by MusicSongsSummariziedWidget::searchFileListCache().
void MusicSongsListTableWidget::setMusicSort (MusicSort * sort) inline
Get the current play row.
Definition at line 59 of file musicsongslisttablewidget.h.
Referenced by MusicSongsSummariziedWidget::createWidgetItem().
void MusicSongsListTableWidget::setTimerLabel (const QString & time, const QString & total) const
Set music sort.
Definition at line 199 of file musicsongslisttablewidget.cpp.
References MusicSongsListPlayWidget::insertTimerLabel(), and m_musicSongsPlayWidget.
void MusicSongsListTableWidget::showFloatWidget () signal
Add or remove music list song to lovest list by row.
Referenced by wheelEvent().
void MusicSongsListTableWidget::showTimeOut () slot
Delete item or items from list with file.
Definition at line 466 of file musicsongslisttablewidget.cpp.
References MusicSongsListPlayWidget::getItemRenameState(), MusicSongsListAbstractTableWidget::isCurrentIndexs(), m_musicSongsInfoWidget, m_musicSongsPlayWidget, MusicAbstractTableWidget::m_previousColorRow, m_timerShow, and MusicSongsListItemInfoWidget::setMusicSongInformation().
Referenced by MusicSongsListTableWidget().
void MusicSongsListTableWidget::startToDrag () protected
Close rename item.
Definition at line 801 of file musicsongslisttablewidget.cpp.
References MusicUtils::Widget::elidedText(), getMusicIndexSwaped(), MusicSongsListAbstractTableWidget::isCurrentIndexs(), isSearchFileListEmpty(), m_dragStartIndex, m_leftButtonPressed, m_mouseMoved, MusicSongsListAbstractTableWidget::m_playRowIndex, and selectRow().
Referenced by mouseReleaseEvent().
void MusicSongsListTableWidget::stayTimeOut () slot
Show play item information widget.
Definition at line 481 of file musicsongslisttablewidget.cpp.
References m_musicSongsInfoWidget, and m_timerStay.
Referenced by MusicSongsListTableWidget().
void MusicSongsListTableWidget::updateCurrentArtist ()
Update item time label time.
Definition at line 207 of file musicsongslisttablewidget.cpp.
References m_musicSongsPlayWidget, and MusicSongsListPlayWidget::updateCurrentArtist().
void MusicSongsListTableWidget::updateSongsFileName (const MusicSongs & songs) override virtual
Get class object name.
Reimplemented from MusicSongsListAbstractTableWidget.
Definition at line 85 of file musicsongslisttablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), createUploadFileWidget(), MusicUtils::Widget::elidedText(), and MusicUIObject::MColorStyle12_S.
Referenced by MusicSongsSummariziedWidget::addNetMusicSongToList(), MusicSongsSummariziedWidget::importOtherMusicSongs(), MusicSongsSummariziedWidget::musicListSongToLovestListAt(), MusicSongsSummariziedWidget::musicSongToLovestListAt(), setMusicSongsSearchedFileName(), and MusicSongsSummariziedWidget::setRecentMusicSongs().
void MusicSongsListTableWidget::wheelEvent (QWheelEvent * event) override protected virtual
Current scroll bar value changed.
Reimplemented from MusicSlowMovingTableWidget.
Definition at line 682 of file musicsongslisttablewidget.cpp.
References closeRenameItem(), showFloatWidget(), and MusicSlowMovingTableWidget::wheelEvent().
Member Data Documentation
bool MusicSongsListTableWidget::m_deleteItemWithFile protected
Definition at line 222 of file musicsongslisttablewidget.h.
Referenced by MusicSongsListTableWidget(), setDeleteItemAt(), and setDeleteItemWithFile().
int MusicSongsListTableWidget::m_dragStartIndex protected
Create context menu.
Definition at line 212 of file musicsongslisttablewidget.h.
Referenced by mousePressEvent(), MusicSongsListTableWidget(), and startToDrag().
QPoint MusicSongsListTableWidget::m_dragStartPoint protected
Definition at line 213 of file musicsongslisttablewidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
bool MusicSongsListTableWidget::m_leftButtonPressed protected
Definition at line 221 of file musicsongslisttablewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), MusicSongsListTableWidget(), and startToDrag().
bool MusicSongsListTableWidget::m_listHasSearched protected
Definition at line 221 of file musicsongslisttablewidget.h.
Referenced by MusicSongsListTableWidget(), setMusicSongsSearchedFileName(), and ~MusicSongsListTableWidget().
bool MusicSongsListTableWidget::m_mouseMoved protected
Definition at line 214 of file musicsongslisttablewidget.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), MusicSongsListTableWidget(), and startToDrag().
MusicSongsListItemInfoWidget* MusicSongsListTableWidget::m_musicSongsInfoWidget protected
Definition at line 218 of file musicsongslisttablewidget.h.
Referenced by leaveEvent(), listCellEntered(), showTimeOut(), stayTimeOut(), and ~MusicSongsListTableWidget().
MusicSongsListPlayWidget* MusicSongsListTableWidget::m_musicSongsPlayWidget protected
Definition at line 219 of file musicsongslisttablewidget.h.
Referenced by clearAllItems(), replacePlayWidgetRow(), selectRow(), setChangSongName(), setTimerLabel(), showTimeOut(), updateCurrentArtist(), and ~MusicSongsListTableWidget().
MusicSort* MusicSongsListTableWidget::m_musicSort protected
Definition at line 224 of file musicsongslisttablewidget.h.
Referenced by contextMenuEvent(), musicListSongSortBy(), and MusicSongsListTableWidget().
MusicOpenFileWidget* MusicSongsListTableWidget::m_openFileWidget protected
Definition at line 217 of file musicsongslisttablewidget.h.
Referenced by createUploadFileWidget(), and ~MusicSongsListTableWidget().
bool MusicSongsListTableWidget::m_renameActived protected
Definition at line 222 of file musicsongslisttablewidget.h.
Referenced by closeRenameItem(), MusicSongsListTableWidget(), and setChangSongName().
QTableWidgetItem* MusicSongsListTableWidget::m_renameItem protected
Definition at line 223 of file musicsongslisttablewidget.h.
Referenced by closeRenameItem(), MusicSongsListTableWidget(), and setChangSongName().
QTimer MusicSongsListTableWidget::m_timerShow protected
Definition at line 216 of file musicsongslisttablewidget.h.
Referenced by listCellEntered(), MusicSongsListTableWidget(), and showTimeOut().
QTimer MusicSongsListTableWidget::m_timerStay protected
Definition at line 216 of file musicsongslisttablewidget.h.
Referenced by listCellEntered(), MusicSongsListTableWidget(), and stayTimeOut().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslisttablewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslisttablewidget.cpp