TTKMusicPlayer: MusicLocalManagerStatisticTableWidget Class Reference
MusicLocalManagerStatisticTableWidget Class Reference
The class of the local manager statistic table widget.
#include <musiclocalmanagerwidget.h>
Public Member Functions
MusicLocalManagerStatisticTableWidget (QWidget *parent=nullptr)
~MusicLocalManagerStatisticTableWidget ()
void addCellItem (const MusicSongStatisticItem &song)
void resizeSection () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Additional Inherited Members
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the local manager statistic table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 45 of file musiclocalmanagerwidget.h.
Constructor & Destructor Documentation
MusicLocalManagerStatisticTableWidget::MusicLocalManagerStatisticTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 51 of file musiclocalmanagerwidget.cpp.
References TTK::UI::ScrollBarStyle04.
MusicLocalManagerStatisticTableWidget::~MusicLocalManagerStatisticTableWidget ()
Object destructor.
Definition at line 71 of file musiclocalmanagerwidget.cpp.
References TTKAbstractTableWidget::removeItems().
Member Function Documentation
void MusicLocalManagerStatisticTableWidget::addCellItem (const MusicSongStatisticItem & song)
Create cell items by input data.
Definition at line 76 of file musiclocalmanagerwidget.cpp.
References QtItemSetTextAlignment.
Referenced by MusicLocalManagerWidget::updateStatisticWidget().
void MusicLocalManagerStatisticTableWidget::resizeSection () const
Resize section bound by resize called.
Definition at line 97 of file musiclocalmanagerwidget.cpp.
References G_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicLocalManagerWidget::resizeWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiclocalmanagerwidget.h
TTKModule/TTKWidget/musicToolsKits/musiclocalmanagerwidget.cpp