TTKMusicplayer: MusicDownloadBackgroundBingRequest Class Reference
MusicDownloadBackgroundBingRequest Class Reference
The class of download bing daily skin background.
#include <musicdownloadbackgroundskinrequest.h>
Public Slots
virtual void downLoadFinished (const QByteArray &bytes) override
Public Slots inherited from MusicDownloadBackgroundRemoteRequest
virtual void downLoadFinished (const QByteArray &bytes)=0
Public Member Functions
MusicDownloadBackgroundBingRequest (QObject *parent=nullptr)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownloadBackgroundRemoteRequest
MusicDownloadBackgroundRemoteRequest (QObject *parent=nullptr)
Additional Inherited Members
Signals inherited from MusicDownloadBackgroundRemoteRequest
void downLoadDataChanged (const MusicSkinRemoteGroups &bytes)
Detailed Description
The class of download bing daily skin background.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 148 of file musicdownloadbackgroundskinrequest.h.
Constructor & Destructor Documentation
MusicDownloadBackgroundBingRequest::MusicDownloadBackgroundBingRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 98 of file musicdownloadbackgroundskinrequest.cpp.
Member Function Documentation
void MusicDownloadBackgroundBingRequest::downLoadFinished (const QByteArray & bytes) override virtual slot
Download data from net finished.
Definition at line 111 of file musicdownloadbackgroundskinrequest.cpp.
References BIGU_URL, MusicDownloadBackgroundRemoteRequest::downLoadDataChanged(), MusicSkinRemoteItem::isValid(), MusicSkinRemoteGroup::isValid(), MusicSkinRemoteGroup::m_group, MusicSkinRemoteGroup::m_items, MusicSkinRemoteItem::m_name, MusicSkinRemoteItem::m_url, MusicSkinRemoteItem::m_useCount, MusicUtils::Algorithm::mdII(), MUSIC_DAILY_DIR, and QJson::Parser::parse().
Referenced by startToDownload().
void MusicDownloadBackgroundBingRequest::startToDownload () override virtual
Start to download data from net.
Implements MusicDownloadBackgroundRemoteRequest.
Definition at line 104 of file musicdownloadbackgroundskinrequest.cpp.
References BING_URL, downLoadFinished(), MusicUtils::Algorithm::mdII(), and MusicDownloadSourceRequest::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadbackgroundskinrequest.h
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadbackgroundskinrequest.cpp