TTKMusicplayer: DlnaXml Class Reference
DlnaXml Class Reference
The class of the dlna xml.
#include <dlnaxml.h>
Public Member Functions
DlnaXml ()
bool fromString (const QString &data)
QString toString () const
QString tagNameToLower (const QString &data) const
QString readTagNameValue (const QString &tagName) const
DlnaService readServiceTag (const QString &type, const QString &tagName) const
Detailed Description
The class of the dlna xml.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file dlnaxml.h.
Constructor & Destructor Documentation
DlnaXml::DlnaXml ()
Definition at line 27 of file dlnaxml.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
bool DlnaXml::fromString (const QString & data)
Definition at line 32 of file dlnaxml.cpp.
References TTK_D.
Referenced by DlnaClientPrivate::connectServer().
DlnaService DlnaXml::readServiceTag (const QString & type, const QString & tagName) const
Definition at line 82 of file dlnaxml.cpp.
References DlnaService::m_controlURL, DlnaService::m_eventSubURL, DlnaService::m_scpdURL, DlnaService::m_serviceID, DlnaService::m_serviceType, and TTK_D.
Referenced by DlnaClientPrivate::connectServer().
QString DlnaXml::readTagNameValue (const QString & tagName) const
Definition at line 71 of file dlnaxml.cpp.
References TTK_D.
Referenced by DlnaClientPrivate::connectServer().
QString DlnaXml::tagNameToLower (const QString & data) const
Definition at line 52 of file dlnaxml.cpp.
Referenced by DlnaClientPrivate::connectServer().
QString DlnaXml::toString () const
Definition at line 42 of file dlnaxml.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qdlna/dlnaxml.h
TTKThirdParty/TTKExtras/qdlna/dlnaxml.cpp