TTKMusicPlayer: MusicCommentsRequest Class Reference
MusicCommentsRequest Class Reference
The class of the query song comments download data from net.
#include <musiccommentsrequest.h>
Signals
void createCommentItem (const MusicResultDataItem &item)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Public Member Functions
MusicCommentsRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value)
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageTotalSize () const noexcept
int pageSize () const noexcept
int totalSize () const noexcept
int pageIndex () const noexcept
bool pageValid () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Attributes
QString m_id
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Detailed Description
The class of the query song comments download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musiccommentsrequest.h.
Constructor & Destructor Documentation
MusicCommentsRequest::MusicCommentsRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musiccommentsrequest.cpp.
Member Function Documentation
void MusicCommentsRequest::createCommentItem (const MusicResultDataItem & item) signal
Create the current song comment.
Referenced by MusicKGSongCommentsRequest::downLoadFinished(), MusicKWSongCommentsRequest::downLoadFinished(), MusicWYSongCommentsRequest::downLoadFinished(), MusicKWPlaylistCommentsRequest::downLoadFinished(), MusicKGPlaylistCommentsRequest::downLoadFinished(), and MusicWYPlaylistCommentsRequest::downLoadFinished().
void MusicCommentsRequest::startToSearch (const QString & value) virtual
Start to search data by input data.
Reimplemented in MusicWYSongCommentsRequest, MusicKGSongCommentsRequest, and MusicKWSongCommentsRequest.
Definition at line 9 of file musiccommentsrequest.cpp.
References m_id, MusicPageQueryRequest::startToPage(), and TTK_INFO_STREAM.
Referenced by MusicCommentsWidget::setCurrentSongName(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
Member Data Documentation
QString MusicCommentsRequest::m_id protected
Definition at line 49 of file musiccommentsrequest.h.
Referenced by MusicKGSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/core/musiccommentsrequest.h
TTKModule/TTKCore/musicNetworkKits/music/core/musiccommentsrequest.cpp