TTKMusicPlayer: MusicConfigManager Class Reference
MusicConfigManager Class Reference
The class of the xml config manager.
#include <musicconfigmanager.h>
Public Member Functions
MusicConfigManager ()
bool readBuffer ()
bool writeBuffer ()
QRect readWindowGeometry () const
QPoint readShowDesktopLrcGeometry () const
Public Member Functions inherited from TTKAbstractXml
TTKAbstractXml ()
~TTKAbstractXml ()
bool load (const QString &name)
void save () const
bool reset ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
void createProcessingInstruction () const
QString readAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readTextByTagName (const QString &tagName) const
TTKXmlAttributeList readAttributesByTagName (const QString &tagName) const
QStringList readMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readMultiTextByTagName (const QString &tagName) const
TTKXmlAttributesList readMultiAttributesByTagName (const QString &tagName) const
QDomElement createRoot (const QString &node) const
QDomElement createRoot (const QString &node, const TTKXmlAttribute &attr) const
QDomElement createRoot (const QString &node, const TTKXmlAttributeList &attrs) const
QDomElement writeDomElement (QDomElement &element, const QString &node) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const QString &text) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr, const QString &text) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs, const QString &text) const
void writeAttribute (QDomElement &element, const TTKXmlAttribute &attr) const
void writeAttribute (QDomElement &element, const TTKXmlAttributeList &attr) const
Private Member Functions
virtual bool readBuffer (int &items) overridefinal
virtual bool writeBuffer (const int &items) overridefinal
Private Member Functions inherited from TTKAbstractReadWriteInterface< int >
virtual ~TTKAbstractReadWriteInterface ()=default
Additional Inherited Members
Protected Attributes inherited from TTKAbstractXml
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the xml config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicconfigmanager.h.
Constructor & Destructor Documentation
MusicConfigManager::MusicConfigManager ()
Object constructor.
Definition at line 8 of file musicconfigmanager.cpp.
Member Function Documentation
bool MusicConfigManager::readBuffer ()
Read datas from buffer.
Definition at line 14 of file musicconfigmanager.cpp.
Referenced by MusicApplication::readSystemConfigFromFile(), and MusicRunTimeManager::run().
bool MusicConfigManager::readBuffer (int & items) final override private virtual
Read datas from buffer.
Implements TTKAbstractReadInterface< int >.
Definition at line 26 of file musicconfigmanager.cpp.
References MusicSettingManager::BackgroundListTransparent, MusicSettingManager::BackgroundThemeValue, MusicSettingManager::BackgroundTransparent, MusicSettingManager::BackgroundTransparentEnable, MusicSettingManager::CloseEventMode, MusicSettingManager::CloseNetWorkMode, MusicSettingManager::ConfigVersion, MusicSettingManager::DLrcBackgroundColor, MusicSettingManager::DLrcColor, MusicSettingManager::DLrcColorTransparent, MusicSettingManager::DLrcFamily, MusicSettingManager::DLrcFrontgroundColor, MusicSettingManager::DLrcLockedMode, MusicSettingManager::DLrcSingleLineMode, MusicSettingManager::DLrcSize, MusicSettingManager::DLrcType, MusicSettingManager::DLrcWindowMode, MusicSettingManager::DownloadCacheEnable, MusicSettingManager::DownloadCacheSize, MusicSettingManager::DownloadDownloadLimitSize, MusicSettingManager::DownloadFileNameRule, MusicSettingManager::DownloadLimitEnable, MusicSettingManager::DownloadLrcDirPath, MusicSettingManager::DownloadMusicDirPath, MusicSettingManager::DownloadServerIndex, MusicSettingManager::DownloadUploadLimitSize, MusicSettingManager::EnhancedEffectValue, MusicSettingManager::EnhancedFadeEnable, MusicSettingManager::EnhancedFadeInValue, MusicSettingManager::EnhancedFadeOutValue, MusicSettingManager::EnhancedMusicIndex, MusicSettingManager::EqualizerEnable, MusicSettingManager::EqualizerIndex, MusicSettingManager::EqualizerValue, MusicSettingManager::FileAssociationMode, MusicSettingManager::FileAssociationValue, G_SETTING_PTR, MusicSettingManager::HotkeyEnable, MusicSettingManager::HotkeyValue, MusicSettingManager::LanguageIndex, MusicSettingManager::LastFileDialogPath, MusicSettingManager::LastPlayIndex, MusicSettingManager::LrcBackgroundColor, MusicSettingManager::LrcColor, MusicSettingManager::LrcColorTransparent, TTK::String::lrcDirPrefix(), MusicSettingManager::LrcFamily, MusicSettingManager::LrcFrontgroundColor, MusicSettingManager::LrcSize, MusicSettingManager::LrcType, MusicSettingManager::MediaLibraryPath, TTK::String::musicDirPrefix(), MusicSettingManager::OtherCheckUpdateEnable, MusicSettingManager::OtherLrcKTVMode, MusicSettingManager::OtherPlaylistAutoSaveEnable, MusicSettingManager::OtherRandomShuffleMode, MusicSettingManager::OtherReadAlbumCover, MusicSettingManager::OtherReadFileInfo, MusicSettingManager::OtherScreenSaverEnable, MusicSettingManager::OtherScreenSaverIndex, MusicSettingManager::OtherScreenSaverTime, MusicSettingManager::OtherSideByMode, MusicSettingManager::OtherWriteAlbumCover, MusicSettingManager::OtherWriteFileInfo, MusicSettingManager::PlayMode, TTKAbstractXml::readAttributeByTagName(), MusicSettingManager::RemoteWidgetMode, MusicSettingManager::RippleLowPowerMode, MusicSettingManager::RippleSpectrumColor, MusicSettingManager::RippleSpectrumEnable, MusicSettingManager::ShowDesktopLrc, MusicSettingManager::StartUpMode, MusicSettingManager::StartUpPlayMode, MusicSettingManager::TimerAutoIndex, MusicSettingManager::TimerAutoPlayHour, MusicSettingManager::TimerAutoPlayItemIndex, MusicSettingManager::TimerAutoPlayMode, MusicSettingManager::TimerAutoPlayRepeat, MusicSettingManager::TimerAutoPlaySecond, MusicSettingManager::TimerAutoPlaySongIndex, MusicSettingManager::TimerAutoShutdownHour, MusicSettingManager::TimerAutoShutdownMode, MusicSettingManager::TimerAutoShutdownRepeat, MusicSettingManager::TimerAutoShutdownSecond, MusicSettingManager::TimerAutoStopHour, MusicSettingManager::TimerAutoStopMode, MusicSettingManager::TimerAutoStopRepeat, MusicSettingManager::TimerAutoStopSecond, MusicSettingManager::Volume, MusicSettingManager::WindowConciseMode, and MusicSettingManager::WindowQuitMode.
QPoint MusicConfigManager::readShowDesktopLrcGeometry () const
Read Show Desktop Lrc Geometry Config.
Definition at line 400 of file musicconfigmanager.cpp.
References TTKAbstractXml::readAttributeByTagName().
Referenced by MusicApplication::readSystemConfigFromFile().
QRect MusicConfigManager::readWindowGeometry () const
Read window widget Geometry Config.
Definition at line 376 of file musicconfigmanager.cpp.
References TTKAbstractXml::m_document, WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by MusicApplication::readSystemConfigFromFile().
bool MusicConfigManager::writeBuffer ()
Write datas into buffer.
Definition at line 20 of file musicconfigmanager.cpp.
Referenced by MusicApplication::writeSystemConfigToFile().
bool MusicConfigManager::writeBuffer (const int & items) final override private virtual
Write datas into buffer.
Implements TTKAbstractWriteInterface< int >.
Definition at line 153 of file musicconfigmanager.cpp.
References MusicSettingManager::BackgroundListTransparent, MusicSettingManager::BackgroundThemeValue, MusicSettingManager::BackgroundTransparent, MusicSettingManager::BackgroundTransparentEnable, MusicSettingManager::CloseEventMode, MusicSettingManager::CloseNetWorkMode, TTKAbstractXml::createProcessingInstruction(), TTKAbstractXml::createRoot(), MusicSettingManager::DLrcBackgroundColor, MusicSettingManager::DLrcColor, MusicSettingManager::DLrcColorTransparent, MusicSettingManager::DLrcFamily, MusicSettingManager::DLrcFrontgroundColor, MusicSettingManager::DLrcGeometry, MusicSettingManager::DLrcLockedMode, MusicSettingManager::DLrcSingleLineMode, MusicSettingManager::DLrcSize, MusicSettingManager::DLrcType, MusicSettingManager::DLrcWindowMode, MusicSettingManager::DownloadCacheEnable, MusicSettingManager::DownloadCacheSize, MusicSettingManager::DownloadDownloadLimitSize, MusicSettingManager::DownloadFileNameRule, MusicSettingManager::DownloadLimitEnable, MusicSettingManager::DownloadLrcDirPath, MusicSettingManager::DownloadMusicDirPath, MusicSettingManager::DownloadServerIndex, MusicSettingManager::DownloadUploadLimitSize, MusicSettingManager::EnhancedEffectValue, MusicSettingManager::EnhancedFadeEnable, MusicSettingManager::EnhancedFadeInValue, MusicSettingManager::EnhancedFadeOutValue, MusicSettingManager::EnhancedMusicIndex, MusicSettingManager::EqualizerEnable, MusicSettingManager::EqualizerIndex, MusicSettingManager::EqualizerValue, MusicSettingManager::FileAssociationMode, MusicSettingManager::FileAssociationValue, G_SETTING_PTR, MusicSettingManager::HotkeyEnable, MusicSettingManager::HotkeyValue, MusicSettingManager::LanguageIndex, MusicSettingManager::LastFileDialogPath, MusicSettingManager::LastPlayIndex, MusicSettingManager::LrcBackgroundColor, MusicSettingManager::LrcColor, MusicSettingManager::LrcColorTransparent, MusicSettingManager::LrcFamily, MusicSettingManager::LrcFrontgroundColor, MusicSettingManager::LrcSize, MusicSettingManager::LrcType, MusicSettingManager::MediaLibraryPath, MusicSettingManager::OtherCheckUpdateEnable, MusicSettingManager::OtherLrcKTVMode, MusicSettingManager::OtherPlaylistAutoSaveEnable, MusicSettingManager::OtherRandomShuffleMode, MusicSettingManager::OtherReadAlbumCover, MusicSettingManager::OtherReadFileInfo, MusicSettingManager::OtherScreenSaverEnable, MusicSettingManager::OtherScreenSaverIndex, MusicSettingManager::OtherScreenSaverTime, MusicSettingManager::OtherSideByMode, MusicSettingManager::OtherWriteAlbumCover, MusicSettingManager::OtherWriteFileInfo, MusicSettingManager::PlayMode, MusicSettingManager::RemoteWidgetMode, MusicSettingManager::RippleLowPowerMode, MusicSettingManager::RippleSpectrumColor, MusicSettingManager::RippleSpectrumEnable, TTKAbstractXml::save(), MusicSettingManager::ShowDesktopLrc, MusicSettingManager::StartUpMode, MusicSettingManager::StartUpPlayMode, MusicSettingManager::TimerAutoIndex, MusicSettingManager::TimerAutoPlayHour, MusicSettingManager::TimerAutoPlayItemIndex, MusicSettingManager::TimerAutoPlayMode, MusicSettingManager::TimerAutoPlayRepeat, MusicSettingManager::TimerAutoPlaySecond, MusicSettingManager::TimerAutoPlaySongIndex, MusicSettingManager::TimerAutoShutdownHour, MusicSettingManager::TimerAutoShutdownMode, MusicSettingManager::TimerAutoShutdownRepeat, MusicSettingManager::TimerAutoShutdownSecond, MusicSettingManager::TimerAutoStopHour, MusicSettingManager::TimerAutoStopMode, MusicSettingManager::TimerAutoStopRepeat, MusicSettingManager::TimerAutoStopSecond, TTK_APP_NAME, TTK_CONFIG_VERSION_STR, MusicSettingManager::Volume, MusicSettingManager::WidgetPosition, MusicSettingManager::WidgetSize, MusicSettingManager::WindowConciseMode, MusicSettingManager::WindowQuitMode, and TTKAbstractXml::writeDomElement().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicconfigmanager.h
TTKModule/TTKCore/musicCoreKits/musicconfigmanager.cpp