TTKMusicplayer: MusicSongCheckToolsDuplicateTableWidget Class Reference
MusicSongCheckToolsDuplicateTableWidget Class Reference
The class of the song check tools duplicate table widget.
#include <musicsongchecktoolstablewidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
void selectedAllItems (bool check)
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void setSelectedAllItems (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Signals
void addSongToPlaylist (const QStringList &list)
Public Member Functions
MusicSongCheckToolsDuplicateTableWidget (QWidget *parent=nullptr)
~MusicSongCheckToolsDuplicateTableWidget ()
void createAllItems (const MusicSongCheckToolsDuplicateList &songs)
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList selectedItems () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
void clear ()
TTKIntList multiSelectedIndex () const
Protected Member Functions
void musicPlay ()
void deleteCurrentRow ()
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Additional Inherited Members
Protected Attributes inherited from MusicFillItemTableWidget
MusicCheckBoxDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the song check tools duplicate table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 66 of file musicsongchecktoolstablewidget.h.
Constructor & Destructor Documentation
MusicSongCheckToolsDuplicateTableWidget::MusicSongCheckToolsDuplicateTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 95 of file musicsongchecktoolstablewidget.cpp.
References G_CONNECTION_PTR.
MusicSongCheckToolsDuplicateTableWidget::~MusicSongCheckToolsDuplicateTableWidget ()
Definition at line 122 of file musicsongchecktoolstablewidget.cpp.
References G_CONNECTION_PTR.
Member Function Documentation
void MusicSongCheckToolsDuplicateTableWidget::addSongToPlaylist (const QStringList & list) signal
Add current selected song to playlist.
Referenced by musicPlay().
void MusicSongCheckToolsDuplicateTableWidget::createAllItems (const MusicSongCheckToolsDuplicateList & songs)
Create all items.
Definition at line 127 of file musicsongchecktoolstablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSongCheckToolsDuplicate::m_bitrate, MusicSongCheckToolsDuplicate::m_song, MUSIC_CHECK_ROLE, MUSIC_DATA_ROLE, MUSIC_TEXT_ROLE, MusicSong::name(), MusicSong::path(), MusicSong::playTime(), QtItemSetTextAlignment, and MusicSong::sizeStr().
void MusicSongCheckToolsDuplicateTableWidget::deleteCurrentRow () protected
Delete current selected row.
Definition at line 215 of file musicsongchecktoolstablewidget.cpp.
Referenced by itemCellClicked().
void MusicSongCheckToolsDuplicateTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 171 of file musicsongchecktoolstablewidget.cpp.
References deleteCurrentRow(), MusicFillItemTableWidget::itemCellClicked(), and musicPlay().
void MusicSongCheckToolsDuplicateTableWidget::musicPlay () protected
Add selected music song path to list.
Definition at line 200 of file musicsongchecktoolstablewidget.cpp.
References addSongToPlaylist(), and MUSIC_DATA_ROLE.
Referenced by itemCellClicked().
void MusicSongCheckToolsDuplicateTableWidget::selectedAllItems (bool check) slot
Select all items.
Definition at line 182 of file musicsongchecktoolstablewidget.cpp.
References MUSIC_CHECK_ROLE.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolstablewidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolstablewidget.cpp