TTKMusicPlayer: MusicTranslationRequest Class Reference
MusicTranslationRequest Class Reference
The class of the translation words manager request.
#include <musictranslationrequest.h>
Public Slots
void downLoadFinished (const QString &bytes)
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicTranslationRequest (const QString &data, QObject *parent=nullptr)
virtual void startRequest ()
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Member Functions
void findAllPlugins ()
Private Attributes
QString m_data
int m_pluginIndex
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the translation words manager request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musictranslationrequest.h.
Constructor & Destructor Documentation
MusicTranslationRequest::MusicTranslationRequest (const QString & data, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musictranslationrequest.cpp.
Member Function Documentation
void MusicTranslationRequest::downLoadFinished (const QString & bytes) slot
Download data from net finished.
Definition at line 22 of file musictranslationrequest.cpp.
References MusicAbstractNetwork::downLoadDataChanged(), and findAllPlugins().
void MusicTranslationRequest::findAllPlugins () private
Find all plugins.
Definition at line 36 of file musictranslationrequest.cpp.
References MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicSettingManager::DownloadServerIndex, G_SETTING_PTR, MusicAbstractNetwork::header(), m_data, m_pluginIndex, MusicAbstractNetwork::setHeader(), MusicAbstractTranslationRequest::startRequest(), TTKStatic_cast, and MusicAbstractQueryRequest::WY.
Referenced by downLoadFinished(), and startRequest().
void MusicTranslationRequest::startRequest () virtual
Start to translation data.
Definition at line 16 of file musictranslationrequest.cpp.
References findAllPlugins(), and m_pluginIndex.
Referenced by MusicLrcContainerForInterior::translatedLrcData().
Member Data Documentation
QString MusicTranslationRequest::m_data private
Definition at line 55 of file musictranslationrequest.h.
Referenced by findAllPlugins().
int MusicTranslationRequest::m_pluginIndex private
Definition at line 56 of file musictranslationrequest.h.
Referenced by findAllPlugins(), and startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/translation/musictranslationrequest.h
TTKModule/TTKCore/musicNetworkKits/translation/musictranslationrequest.cpp