TTKMusicplayer: MusicPlaylistQueryInfoWidget Class Reference
MusicPlaylistQueryInfoWidget Class Reference
The class of the playlist music query info widget.
#include <musicplaylistqueryinfowidget.h>
Public Slots
void setCurrentIndex (int index)
void queryAllFinished ()
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicPlaylistQueryInfoWidget (QWidget *parent=nullptr)
~MusicPlaylistQueryInfoWidget ()
virtual void resizeWindow () override
virtual void setSongNameById (const QString &id) override
void setMusicResultsItem (const MusicResultsItem &item, QObject *obj)
void setQueryInput (MusicAbstractQueryRequest *query)
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractItemQueryWidget ()
virtual void setSongName (const QString &name)
void initWidget ()
Protected Member Functions
void initThirdWidget ()
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes
MusicPlaylistQueryCommentsWidget * m_commentsWidget
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of the playlist music query info widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicplaylistqueryinfowidget.h.
Constructor & Destructor Documentation
MusicPlaylistQueryInfoWidget::MusicPlaylistQueryInfoWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicplaylistqueryinfowidget.cpp.
References MusicAbstractItemQueryWidget::initFirstWidget(), MusicAbstractItemQueryWidget::initSecondWidget(), m_commentsWidget, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_shareType, and MusicSongSharingWidget::Playlist.
MusicPlaylistQueryInfoWidget::~MusicPlaylistQueryInfoWidget ()
Definition at line 23 of file musicplaylistqueryinfowidget.cpp.
References m_commentsWidget.
Member Function Documentation
void MusicPlaylistQueryInfoWidget::initThirdWidget () protected
Init the third widget.
Definition at line 288 of file musicplaylistqueryinfowidget.cpp.
References MusicPlaylistQueryCommentsWidget::initWidget(), m_commentsWidget, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_songNameFull, and MusicCommentsWidget::setCurrentSongName().
Referenced by setCurrentIndex().
void MusicPlaylistQueryInfoWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 283 of file musicplaylistqueryinfowidget.cpp.
References MusicAbstractItemQueryWidget::setSongCountText().
void MusicPlaylistQueryInfoWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 28 of file musicplaylistqueryinfowidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicItemQueryTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicPlaylistQueryWidget::resizeWindow(), and setMusicResultsItem().
void MusicPlaylistQueryInfoWidget::setCurrentIndex (int index) slot
Set current container index.
Definition at line 252 of file musicplaylistqueryinfowidget.cpp.
References initThirdWidget(), m_commentsWidget, MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_infoLabel, and MusicAbstractItemQueryWidget::m_queryTableWidget.
Referenced by setMusicResultsItem().
void MusicPlaylistQueryInfoWidget::setMusicResultsItem (const MusicResultsItem & item, QObject * obj)
Set music playlist item.
Definition at line 55 of file musicplaylistqueryinfowidget.cpp.
References MusicAbstractItemQueryWidget::downLoadFinished(), MusicUtils::Widget::generateVScrollAreaFormat(), MusicAbstractItemQueryWidget::m_container, MusicResultsItem::m_coverUrl, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicResultsItem::m_description, MusicAbstractItemQueryWidget::m_iconLabel, MusicResultsItem::m_id, MusicAbstractItemQueryWidget::m_infoLabel, MusicAbstractItemQueryWidget::m_mainWindow, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songButton, MusicAbstractItemQueryWidget::m_statusLabel, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSColorStyle05, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSFontStyle06, MusicUIObject::MQSSPushButtonStyle03, MusicAbstractItemQueryWidget::playAllButtonClicked(), resizeWindow(), setCurrentIndex(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), MusicAbstractItemQueryWidget::setSongName(), MusicAbstractItemQueryWidget::shareButtonClicked(), MusicItemQueryTableWidget::startSearchQuery(), MusicDownloadSourceRequest::startToDownload(), and TTK_NULL_STR.
Referenced by MusicPlaylistQueryWidget::currentPlaylistClicked().
void MusicPlaylistQueryInfoWidget::setQueryInput (MusicAbstractQueryRequest * query)
Set network query input.
Definition at line 246 of file musicplaylistqueryinfowidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget, MusicItemQueryTableWidget::setQueryInput(), and TTKStatic_cast.
Referenced by MusicPlaylistQueryWidget::currentPlaylistClicked().
void MusicPlaylistQueryInfoWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 50 of file musicplaylistqueryinfowidget.cpp.
Member Data Documentation
MusicPlaylistQueryCommentsWidget* MusicPlaylistQueryInfoWidget::m_commentsWidget protected
Definition at line 79 of file musicplaylistqueryinfowidget.h.
Referenced by initThirdWidget(), MusicPlaylistQueryInfoWidget(), setCurrentIndex(), and ~MusicPlaylistQueryInfoWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistqueryinfowidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistqueryinfowidget.cpp