TTKMusicPlayer: MusicMobileSongsTableWidget Class Reference
MusicMobileSongsTableWidget Class Reference
The class of the mobile songs table widget.
#include <musicmobilesongsmanagerwidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void removeItems () overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Public Slots inherited from MusicAbstractSongsListTableWidget
virtual void removeItemAt ()
void playClicked ()
void clearItems ()
void openFileDir ()
void showFileInformation ()
void showMovieQueryWidget ()
void showAlbumQueryWidget ()
void showSimilarQueryWidget ()
void showSongSharedWidget ()
void showDownloadWidget ()
void showPlayedMovieQueryWidget ()
void showPlayedSimilarQueryWidget ()
void showPlayedSongSharedWidget ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicMobileSongsTableWidget (QWidget *parent=nullptr)
~MusicMobileSongsTableWidget ()
void addCellItems (const QStringList &songs)
Public Member Functions inherited from MusicAbstractSongsListTableWidget
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
MusicAbstractSongsListTableWidget (int index, QWidget *parent=nullptr)
~MusicAbstractSongsListTableWidget ()
virtual void setSongsList (MusicSongList *songs)
virtual void updateSongsList (const MusicSongList &songs)
virtual void selectRow (int index)
int totalHeight () const
void setPlaylistRow (int index)
void setPlayRowIndex (int index)
int playRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Additional Inherited Members
Signals inherited from MusicAbstractSongsListTableWidget
void isCurrentPlaylistRow (bool &state)
Protected Member Functions inherited from MusicAbstractSongsListTableWidget
void createMoreMenu (QMenu *menu)
QString currentSongPath () const
QString songPath (int index) const
QString currentSongName () const
QString songName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from MusicAbstractSongsListTableWidget
int m_playlistRow
int m_playRowIndex
MusicSongList * m_songs
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_initialized
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the mobile songs table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicmobilesongsmanagerwidget.h.
Constructor & Destructor Documentation
MusicMobileSongsTableWidget::MusicMobileSongsTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musicmobilesongsmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::m_songs, and TTK::Widget::setTransparent().
MusicMobileSongsTableWidget::~MusicMobileSongsTableWidget ()
Object destructor.
Definition at line 25 of file musicmobilesongsmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::m_songs, and removeItems().
Member Function Documentation
void MusicMobileSongsTableWidget::addCellItems (const QStringList & songs)
Create cell items by input data.
Definition at line 31 of file musicmobilesongsmanagerwidget.cpp.
References TTK::Widget::elidedText(), MusicAbstractSongsListTableWidget::m_songs, QtItemSetTextAlignment, and TTK::Number::sizeByteToLabel().
void MusicMobileSongsTableWidget::contextMenuEvent (QContextMenuEvent * event) final override virtual slot
Override the widget event.
Definition at line 87 of file musicmobilesongsmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::createMoreMenu(), MusicAbstractSongsListTableWidget::currentSongPath(), TTK::String::isNetworkUrl(), MusicAbstractSongsListTableWidget::m_songs, TTK::UI::MenuStyle02, MusicAbstractSongsListTableWidget::openFileDir(), MusicAbstractSongsListTableWidget::playClicked(), MusicAbstractSongsListTableWidget::showAlbumQueryWidget(), and MusicAbstractSongsListTableWidget::showFileInformation().
void MusicMobileSongsTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 68 of file musicmobilesongsmanagerwidget.cpp.
References TTKAbstractTableWidget::itemCellEntered().
void MusicMobileSongsTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 81 of file musicmobilesongsmanagerwidget.cpp.
References MusicAbstractSongsListTableWidget::m_songs, and TTKAbstractTableWidget::removeItems().
Referenced by ~MusicMobileSongsTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicmobilesongsmanagerwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicmobilesongsmanagerwidget.cpp