TTKMusicplayer: OSSDownloadData Class Reference
OSSDownloadData Class Reference
The class of the alioss cloud data item.
#include <ossdownloaddata.h>
Signals
void downloadFileFinished (const QString &time)
void downloadProgressChanged (const QString &time, qint64 bytesSent, qint64 bytesTotal)
Public Member Functions
OSSDownloadData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void downloadDataOperator (const QString &time, const QString &bucket, const QString &fileName, const QString &filePath)
QString getDownloadUrl (const QString &bucket, const QString &fileName)
QString getDownloadUrl (const QString &bucket, const QString &fileName, const QString &contentType)
Public Member Functions inherited from OSSDataInterface
OSSDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Protected Slots
virtual void receiveDataFromServer () override
void downloadProgress (qint64 bytesSent, qint64 bytesTotal)
Protected Slots inherited from OSSDataInterface
virtual void receiveDataFromServer ()=0
void handleError (QNetworkReply::NetworkError error)
Detailed Description
The class of the alioss cloud data item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file ossdownloaddata.h.
Constructor & Destructor Documentation
OSSDownloadData::OSSDownloadData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 20 of file ossdownloaddata.cpp.
References TTK_D, TTK_INIT_PRIVATE, and TTK_INIT_PUBLIC.
Member Function Documentation
void OSSDownloadData::downloadDataOperator (const QString & time, const QString & bucket, const QString & fileName, const QString & filePath)
Get download data operator.
Definition at line 29 of file ossdownloaddata.cpp.
References downloadProgress(), downloadProgressChanged(), OSSUtils::getGMT(), OSSDataInterface::handleError(), MusicObject::NetworkError, OSSConf::OSS_HOST, receiveDataFromServer(), and TTK_D.
void OSSDownloadData::downloadFileFinished (const QString & time) signal
download file finshed.
Referenced by receiveDataFromServer().
void OSSDownloadData::downloadProgress (qint64 bytesSent, qint64 bytesTotal) protected slot
Show download progress.
Definition at line 121 of file ossdownloaddata.cpp.
References downloadProgressChanged(), and TTK_D.
Referenced by downloadDataOperator().
void OSSDownloadData::downloadProgressChanged (const QString & time, qint64 bytesSent, qint64 bytesTotal) signal
Show download progress.
Referenced by downloadDataOperator(), and downloadProgress().
QString OSSDownloadData::getDownloadUrl (const QString & bucket, const QString & fileName)
Get download url request.
Definition at line 67 of file ossdownloaddata.cpp.
Referenced by MusicCloudManagerTableWidget::downloadFileToServer().
QString OSSDownloadData::getDownloadUrl (const QString & bucket, const QString & fileName, const QString & contentType)
Get download url request by content type.
Definition at line 72 of file ossdownloaddata.cpp.
References OSSConf::ACCESS_KEY, OSSUtils::getAuthorizationCode(), OSSConf::OSS_HOST, and OSSConf::SECRET_KEY.
void OSSDownloadData::receiveDataFromServer () override protected virtual slot
Receive data from server finshed.
Definition at line 93 of file ossdownloaddata.cpp.
References downloadFileFinished(), MObject_cast, TTK_D, and TTK_ERROR_STR.
Referenced by downloadDataOperator().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qoss/ossdownloaddata.h
TTKThirdParty/TTKExtras/qoss/ossdownloaddata.cpp