TTKMusicPlayer: MusicRippleSpecturmModule Class Reference
MusicRippleSpecturmModule Class Reference
The class of the ripples spectrum object.
#include <musicripplespecturmmodule.h>
Public Member Functions
MusicRippleSpecturmModule (QObject *parent=nullptr)
~MusicRippleSpecturmModule ()
void setVisible (bool v)
void show ()
void close ()
void update (bool up)
void initialize (QVBoxLayout *layout, QWidget *widget)
Private Member Functions
void removeSpectrum ()
Private Attributes
QVBoxLayout * m_topAreaLayout
QWidget * m_topAreaWidget
QWidget * m_visualWidget
Detailed Description
The class of the ripples spectrum object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicripplespecturmmodule.h.
Constructor & Destructor Documentation
MusicRippleSpecturmModule::MusicRippleSpecturmModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicripplespecturmmodule.cpp.
MusicRippleSpecturmModule::~MusicRippleSpecturmModule ()
Object destructor.
Definition at line 15 of file musicripplespecturmmodule.cpp.
References removeSpectrum().
Member Function Documentation
void MusicRippleSpecturmModule::close ()
Set ripple spectrum hide.
Definition at line 57 of file musicripplespecturmmodule.cpp.
References m_topAreaLayout, m_topAreaWidget, m_visualWidget, and removeSpectrum().
Referenced by update().
void MusicRippleSpecturmModule::initialize (QVBoxLayout * layout, QWidget * widget)
Init ripple spectrum paramters.
Definition at line 85 of file musicripplespecturmmodule.cpp.
References m_topAreaLayout, and m_topAreaWidget.
Referenced by MusicBottomAreaWidget::setupUi().
void MusicRippleSpecturmModule::removeSpectrum () private
Remove ripple spectrum object.
Definition at line 91 of file musicripplespecturmmodule.cpp.
References TTK::TTKQmmp::enabledVisualPlugin(), and m_visualWidget.
Referenced by close(), and ~MusicRippleSpecturmModule().
void MusicRippleSpecturmModule::setVisible (bool v)
Set ripple spectrum show or not.
Definition at line 20 of file musicripplespecturmmodule.cpp.
References m_topAreaLayout, m_topAreaWidget, and m_visualWidget.
Referenced by MusicBottomAreaWidget::lrcWidgetShowFullScreen().
void MusicRippleSpecturmModule::show ()
Set ripple spectrum show.
Definition at line 30 of file musicripplespecturmmodule.cpp.
References CONCISE_WIDTH_MIN, TTK::TTKQmmp::enabledVisualPlugin(), m_topAreaLayout, m_topAreaWidget, m_visualWidget, and Visual::visuals().
Referenced by update().
void MusicRippleSpecturmModule::update (bool up)
Update ripple spectrum paramters.
Definition at line 70 of file musicripplespecturmmodule.cpp.
References close(), m_visualWidget, show(), Visual::start(), TTKObjectCast, and TTK::TTKQmmp::updateRippleConfig().
Referenced by MusicBottomAreaWidget::applyParameter().
Member Data Documentation
QVBoxLayout* MusicRippleSpecturmModule::m_topAreaLayout private
Definition at line 70 of file musicripplespecturmmodule.h.
Referenced by close(), initialize(), setVisible(), and show().
QWidget* MusicRippleSpecturmModule::m_topAreaWidget private
Definition at line 71 of file musicripplespecturmmodule.h.
Referenced by close(), initialize(), setVisible(), and show().
QWidget * MusicRippleSpecturmModule::m_visualWidget private
Definition at line 71 of file musicripplespecturmmodule.h.
Referenced by close(), removeSpectrum(), setVisible(), show(), and update().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicripplespecturmmodule.h
TTKModule/TTKWidget/musicWidgetKits/musicripplespecturmmodule.cpp