TTKMusicPlayer: QJsonValueRef Class Reference
QJsonValueRef Class Reference
#include <QJsonValueRef.h>
Public Member Functions
QJsonValueRef (QJsonArray *array, int idx)
QJsonValueRef (QJsonObject *object, const QString &key)
operator QJsonValue () const
QJsonValueRef & operator= (const QJsonValue &val)
QJsonValueRef & operator= (const QJsonValueRef &val)
QJsonValue::Type type () const
bool isNull () const
bool isBool () const
bool isDouble () const
bool isString () const
bool isArray () const
bool isObject () const
bool isUndefined () const
bool toBool () const
double toDouble () const
QString toString () const
QJsonArray toArray () const
QJsonObject toObject () const
int toInt (int defaultValue=0) const
bool operator== (const QJsonValue &other) const
bool operator!= (const QJsonValue &other) const
Private Member Functions
QJsonValue toValue () const
void swap (QJsonValueRef &other)
Private Attributes
QJsonRoot * p_
int index_
QString key_
Detailed Description
Definition at line 31 of file QJsonValueRef.h.
Constructor & Destructor Documentation
QJsonValueRef::QJsonValueRef (QJsonArray * array, int idx)
Definition at line 30 of file QJsonValueRef.cpp.
QJsonValueRef::QJsonValueRef (QJsonObject * object, const QString & key)
Definition at line 37 of file QJsonValueRef.cpp.
Member Function Documentation
bool QJsonValueRef::isArray () const
Definition at line 120 of file QJsonValueRef.cpp.
References QJsonValue::isArray(), and toValue().
bool QJsonValueRef::isBool () const
Definition at line 96 of file QJsonValueRef.cpp.
References QJsonValue::isBool(), and toValue().
bool QJsonValueRef::isDouble () const
Definition at line 104 of file QJsonValueRef.cpp.
References QJsonValue::isDouble(), and toValue().
bool QJsonValueRef::isNull () const
Definition at line 88 of file QJsonValueRef.cpp.
References QJsonValue::isNull(), and toValue().
bool QJsonValueRef::isObject () const
Definition at line 128 of file QJsonValueRef.cpp.
References QJsonValue::isObject(), and toValue().
bool QJsonValueRef::isString () const
Definition at line 112 of file QJsonValueRef.cpp.
References QJsonValue::isString(), and toValue().
bool QJsonValueRef::isUndefined () const
Definition at line 136 of file QJsonValueRef.cpp.
References QJsonValue::isUndefined(), and toValue().
QJsonValueRef::operator QJsonValue () const
Definition at line 44 of file QJsonValueRef.cpp.
bool QJsonValueRef::operator!= (const QJsonValue & other) const
Definition at line 200 of file QJsonValueRef.cpp.
References toValue().
QJsonValueRef & QJsonValueRef::operator= (const QJsonValue & val)
Definition at line 52 of file QJsonValueRef.cpp.
References index_, key_, p_, QJsonRoot::toArray(), and QJsonRoot::toObject().
QJsonValueRef & QJsonValueRef::operator= (const QJsonValueRef & val)
Definition at line 66 of file QJsonValueRef.cpp.
References index_, key_, p_, QJsonRoot::toArray(), and QJsonRoot::toObject().
bool QJsonValueRef::operator== (const QJsonValue & other) const
Definition at line 192 of file QJsonValueRef.cpp.
References toValue().
void QJsonValueRef::swap (QJsonValueRef & other) private
Definition at line 222 of file QJsonValueRef.cpp.
References index_, key_, and p_.
QJsonArray QJsonValueRef::toArray () const
Definition at line 176 of file QJsonValueRef.cpp.
References QJsonValue::toArray(), and toValue().
bool QJsonValueRef::toBool () const
Definition at line 144 of file QJsonValueRef.cpp.
References QJsonValue::toBool(), and toValue().
double QJsonValueRef::toDouble () const
Definition at line 152 of file QJsonValueRef.cpp.
References QJsonValue::toDouble(), and toValue().
int QJsonValueRef::toInt (int defaultValue = 0) const
Definition at line 160 of file QJsonValueRef.cpp.
References QJsonValue::toInt(), and toValue().
QJsonObject QJsonValueRef::toObject () const
Definition at line 184 of file QJsonValueRef.cpp.
References QJsonValue::toObject(), and toValue().
QString QJsonValueRef::toString () const
Definition at line 168 of file QJsonValueRef.cpp.
References QJsonValue::toString(), and toValue().
QJsonValue QJsonValueRef::toValue () const private
Definition at line 208 of file QJsonValueRef.cpp.
References index_, key_, p_, QJsonRoot::toArray(), and QJsonRoot::toObject().
Referenced by isArray(), isBool(), isDouble(), isNull(), isObject(), isString(), isUndefined(), operator!=(), operator==(), toArray(), toBool(), toDouble(), toInt(), toObject(), toString(), and type().
QJsonValue::Type QJsonValueRef::type () const
Definition at line 80 of file QJsonValueRef.cpp.
References toValue(), and QJsonValue::type().
Member Data Documentation
int QJsonValueRef::index_ private
Definition at line 73 of file QJsonValueRef.h.
Referenced by operator=(), swap(), and toValue().
QString QJsonValueRef::key_ private
Definition at line 74 of file QJsonValueRef.h.
Referenced by operator=(), swap(), and toValue().
QJsonRoot* QJsonValueRef::p_ private
Definition at line 72 of file QJsonValueRef.h.
Referenced by operator=(), swap(), and toValue().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/QJsonValueRef.h
TTKThirdParty/TTKExtras/qjson/QJsonValueRef.cpp