TTKMusicplayer: MusicDJRadioThreadAbstract Class Reference
MusicDJRadioThreadAbstract Class Reference
The class of music dj radio thread abstract.
#include <musicdjradiothreadabstract.h>
Signals
void createProgramItem (const MusicResultsItem &item)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDJRadioThreadAbstract (QObject *parent=nullptr)
virtual void deleteAll () override
const MusicResultsItems & getSearchedItems () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Protected Attributes
MusicResultsItems m_items
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Protected Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryRequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate, const QString &suffix)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate, const QString &suffix)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class of music dj radio thread abstract.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 39 of file musicdjradiothreadabstract.h.
Constructor & Destructor Documentation
MusicDJRadioThreadAbstract::MusicDJRadioThreadAbstract (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdjradiothreadabstract.cpp.
References M_LOGGER_INFO, MusicNetworkAbstract::m_manager, and MusicNetworkAbstract::sslErrors().
Member Function Documentation
void MusicDJRadioThreadAbstract::createProgramItem (const MusicResultsItem & item) signal
Create the current category item.
Referenced by MusicDJRadioProgramThread::downLoadFinished().
void MusicDJRadioThreadAbstract::deleteAll () override virtual
Release the network object.
Reimplemented from MusicNetworkAbstract.
Definition at line 13 of file musicdjradiothreadabstract.cpp.
References MusicNetworkAbstract::m_reply.
Referenced by MusicDJRadioCategoryThread::downLoadFinished(), MusicDJRadioProgramThread::downLoadFinished(), MusicDJRadioCategoryThread::startToDownload(), and MusicDJRadioProgramThread::startToDownload().
const MusicResultsItems& MusicDJRadioThreadAbstract::getSearchedItems () const inline
Get suggest list items.
Definition at line 57 of file musicdjradiothreadabstract.h.
Referenced by MusicWebDJRadioCategoryWidget::createCategoryItems(), and MusicWebDJRadioProgramTableWidget::listCellClicked().
Member Data Documentation
MusicResultsItems MusicDJRadioThreadAbstract::m_items protected
Definition at line 66 of file musicdjradiothreadabstract.h.
Referenced by MusicDJRadioCategoryThread::downLoadFinished(), and MusicDJRadioProgramThread::downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicdjradiothreadabstract.h
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicdjradiothreadabstract.cpp