TTKMusicplayer: MusicSongCheckToolsDuplicateCore Class Reference
MusicSongCheckToolsDuplicateCore Class Reference
The class of the song check tools duplicate thread.
#include <musicsongchecktoolscore.h>
Public Slots
void start ()
virtual void run () override
Signals
void finished (const MusicSongCheckToolsDuplicates &items)
Public Member Functions
MusicSongCheckToolsDuplicateCore (QObject *parent=0)
~MusicSongCheckToolsDuplicateCore ()
void setMode (MusicObject::MusicSongCheckToolsMode mode)
MusicObject::MusicSongCheckToolsMode getMode () const
void setItemLists (const MusicObject::MIntList &items)
void setDuplicateSongs (MusicSongs *songs)
void stopAndQuitThread ()
Static Public Member Functions
static QString getClassName ()
Protected Attributes
bool m_run
MusicSongs * m_songItems
MusicObject::MIntList m_itemIDs
MusicSongCheckToolsDuplicates m_datas
MusicObject::MusicSongCheckToolsMode m_operateMode
Detailed Description
The class of the song check tools duplicate thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 78 of file musicsongchecktoolscore.h.
Constructor & Destructor Documentation
MusicSongCheckToolsDuplicateCore::MusicSongCheckToolsDuplicateCore (QObject * parent = 0) explicit
Definition at line 96 of file musicsongchecktoolscore.cpp.
References m_run, and m_songItems.
MusicSongCheckToolsDuplicateCore::~MusicSongCheckToolsDuplicateCore ()
Object contsructor.
Definition at line 103 of file musicsongchecktoolscore.cpp.
References stopAndQuitThread().
Member Function Documentation
void MusicSongCheckToolsDuplicateCore::finished (const MusicSongCheckToolsDuplicates & items) signal
Stop and quit current thread.
Referenced by run().
QString MusicSongCheckToolsDuplicateCore::getClassName () static
Definition at line 108 of file musicsongchecktoolscore.cpp.
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsDuplicateCore::getMode () const inline
Set music song check tool mode.
Definition at line 97 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsWidget::duplicateCheckFinished().
void MusicSongCheckToolsDuplicateCore::run () override virtual slot
Strat thread now.
Definition at line 134 of file musicsongchecktoolscore.cpp.
References MusicObject::Check, finished(), MusicSongTag::getBitrate(), MusicSong::getMusicPath(), m_datas, m_itemIDs, m_operateMode, m_run, MusicSongCheckToolsDuplicate::m_song, m_songItems, and MusicSongTag::read().
void MusicSongCheckToolsDuplicateCore::setDuplicateSongs (MusicSongs * songs)
Set item lists.
Definition at line 113 of file musicsongchecktoolscore.cpp.
References m_songItems.
Referenced by MusicSongCheckToolsWidget::duplicateReCheckButtonClicked().
void MusicSongCheckToolsDuplicateCore::setItemLists (const MusicObject::MIntList & items) inline
Get music song check tool mode.
Definition at line 101 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked().
void MusicSongCheckToolsDuplicateCore::setMode (MusicObject::MusicSongCheckToolsMode mode) inline
Get class object name.
Definition at line 93 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), and MusicSongCheckToolsWidget::duplicateReCheckButtonClicked().
void MusicSongCheckToolsDuplicateCore::start () slot
Duplicate check finished.
Definition at line 128 of file musicsongchecktoolscore.cpp.
References m_run.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), and MusicSongCheckToolsWidget::duplicateReCheckButtonClicked().
void MusicSongCheckToolsDuplicateCore::stopAndQuitThread ()
Set find file path by given path.
Definition at line 118 of file musicsongchecktoolscore.cpp.
References m_run.
Referenced by MusicSongCheckToolsWidget::duplicateButtonCheckClicked(), and ~MusicSongCheckToolsDuplicateCore().
Member Data Documentation
MusicSongCheckToolsDuplicates MusicSongCheckToolsDuplicateCore::m_datas protected
Definition at line 135 of file musicsongchecktoolscore.h.
Referenced by run().
MusicObject::MIntList MusicSongCheckToolsDuplicateCore::m_itemIDs protected
Definition at line 134 of file musicsongchecktoolscore.h.
Referenced by run().
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsDuplicateCore::m_operateMode protected
Definition at line 136 of file musicsongchecktoolscore.h.
Referenced by run().
bool MusicSongCheckToolsDuplicateCore::m_run protected
Thread run now.
Definition at line 132 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsDuplicateCore(), run(), start(), and stopAndQuitThread().
MusicSongs* MusicSongCheckToolsDuplicateCore::m_songItems protected
Definition at line 133 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsDuplicateCore(), run(), and setDuplicateSongs().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolscore.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolscore.cpp