TTKMusicPlayer: MusicWebDJRadioCategoryItemWidget Class Reference
MusicWebDJRadioCategoryItemWidget Class Reference
The class of the music dj radio category item widget.
#include <musicwebdjradiocategorywidget.h>
Public Slots
void downLoadFinished (const QByteArray &bytes)
void currentItemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Signals inherited from TTKClickedLabel
void clicked ()
Public Member Functions
MusicWebDJRadioCategoryItemWidget (QWidget *parent=nullptr)
~MusicWebDJRadioCategoryItemWidget ()
void setResultDataItem (const MusicResultDataItem &item)
Public Member Functions inherited from TTKClickedLabel
TTKClickedLabel (QWidget *parent=nullptr)
TTKClickedLabel (const QString &text, QWidget *parent=nullptr)
void blockOption (bool block) noexcept
Private Attributes
QLabel * m_iconLabel
QLabel * m_nameLabel
MusicResultDataItem m_itemData
Additional Inherited Members
Protected Member Functions inherited from TTKClickedLabel
virtual void mousePressEvent (QMouseEvent *event) overridefinal
Protected Attributes inherited from TTKClickedLabel
bool m_blockOption
Detailed Description
The class of the music dj radio category item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicwebdjradiocategorywidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioCategoryItemWidget::MusicWebDJRadioCategoryItemWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 11 of file musicwebdjradiocategorywidget.cpp.
References TTKClickedLabel::clicked(), currentItemClicked(), HEIGHT_LABEL_SIZE, m_iconLabel, m_nameLabel, TTK_DEFAULT_STR, and WIDTH_LABEL_SIZE.
MusicWebDJRadioCategoryItemWidget::~MusicWebDJRadioCategoryItemWidget ()
Object destructor.
Definition at line 27 of file musicwebdjradiocategorywidget.cpp.
References m_iconLabel, and m_nameLabel.
Member Function Documentation
void MusicWebDJRadioCategoryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
void MusicWebDJRadioCategoryItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 63 of file musicwebdjradiocategorywidget.cpp.
References m_itemData.
Referenced by MusicWebDJRadioCategoryItemWidget().
void MusicWebDJRadioCategoryItemWidget::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 47 of file musicwebdjradiocategorywidget.cpp.
References m_iconLabel, TTK_ERROR_STREAM, and WIDTH_LABEL_SIZE.
Referenced by setResultDataItem().
void MusicWebDJRadioCategoryItemWidget::setResultDataItem (const MusicResultDataItem & item)
Set music results item.
Definition at line 33 of file musicwebdjradiocategorywidget.cpp.
References downLoadFinished(), TTK::Widget::elidedText(), G_DOWNLOAD_QUERY_PTR, TTK::isCoverValid(), MusicResultDataItem::m_coverUrl, m_itemData, MusicResultDataItem::m_name, m_nameLabel, MusicCoverRequest::startToRequest(), and WIDTH_LABEL_SIZE.
Referenced by MusicWebDJRadioCategoryWidget::createCategoryItems().
Member Data Documentation
QLabel* MusicWebDJRadioCategoryItemWidget::m_iconLabel private
Definition at line 67 of file musicwebdjradiocategorywidget.h.
Referenced by downLoadFinished(), MusicWebDJRadioCategoryItemWidget(), and ~MusicWebDJRadioCategoryItemWidget().
MusicResultDataItem MusicWebDJRadioCategoryItemWidget::m_itemData private
Definition at line 68 of file musicwebdjradiocategorywidget.h.
Referenced by currentItemClicked(), and setResultDataItem().
QLabel * MusicWebDJRadioCategoryItemWidget::m_nameLabel private
Definition at line 67 of file musicwebdjradiocategorywidget.h.
Referenced by MusicWebDJRadioCategoryItemWidget(), setResultDataItem(), and ~MusicWebDJRadioCategoryItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiocategorywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiocategorywidget.cpp