TTKMusicplayer: DlnaClientPrivate Class Reference
DlnaClientPrivate Class Reference
Public Member Functions
DlnaClientPrivate ()
~DlnaClientPrivate ()
void initData (const QString &data)
bool connectServer ()
Public Member Functions inherited from TTKPrivate< DlnaClient >
TTKPrivate ()
virtual ~TTKPrivate ()
void setPublic (DlnaClient *pub)
Public Attributes
bool m_isConnected
DlnaXml * m_xml
QString m_serverIP
QString m_serverPort
QString m_smp
QString m_controlURL
QString m_friendlyName
QMap< QString, DlnaService > m_services
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< DlnaClient >
DlnaClient * ttk_q () const
Detailed Description
Definition at line 15 of file dlnaclient.cpp.
Constructor & Destructor Documentation
DlnaClientPrivate::DlnaClientPrivate ()
Definition at line 34 of file dlnaclient.cpp.
References m_isConnected, and m_xml.
DlnaClientPrivate::~DlnaClientPrivate ()
Definition at line 40 of file dlnaclient.cpp.
References m_xml.
Member Function Documentation
bool DlnaClientPrivate::connectServer ()
Definition at line 77 of file dlnaclient.cpp.
References AVT_NAMES, AVTRANSPORT, FRIENS_NAMES, DlnaXml::fromString(), HelperDlna::GetResponseCode(), DlnaService::isEmpty(), m_controlURL, m_friendlyName, m_isConnected, M_LOGGER_INFO, m_serverIP, m_serverPort, m_services, m_smp, m_xml, HelperDlna::MakeRequest(), HelperDlna::makeSocketGetReply(), name, DlnaXml::readServiceTag(), DlnaXml::readTagNameValue(), HelperDlna::removeHttpHeader(), and DlnaXml::tagNameToLower().
void DlnaClientPrivate::initData (const QString & data)
Definition at line 45 of file dlnaclient.cpp.
References m_serverIP, m_serverPort, and m_smp.
Member Data Documentation
QString DlnaClientPrivate::m_controlURL
Definition at line 28 of file dlnaclient.cpp.
Referenced by connectServer().
QString DlnaClientPrivate::m_friendlyName
Definition at line 29 of file dlnaclient.cpp.
Referenced by connectServer().
bool DlnaClientPrivate::m_isConnected
Definition at line 24 of file dlnaclient.cpp.
Referenced by connectServer(), and DlnaClientPrivate().
QString DlnaClientPrivate::m_serverIP
Definition at line 27 of file dlnaclient.cpp.
Referenced by connectServer(), and initData().
QString DlnaClientPrivate::m_serverPort
Definition at line 27 of file dlnaclient.cpp.
Referenced by connectServer(), and initData().
QMap<QString, DlnaService> DlnaClientPrivate::m_services
Definition at line 30 of file dlnaclient.cpp.
Referenced by connectServer().
QString DlnaClientPrivate::m_smp
Definition at line 28 of file dlnaclient.cpp.
Referenced by connectServer(), and initData().
DlnaXml* DlnaClientPrivate::m_xml
Definition at line 26 of file dlnaclient.cpp.
Referenced by connectServer(), DlnaClientPrivate(), and ~DlnaClientPrivate().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qdlna/dlnaclient.cpp