TTKMusicplayer: MusicToastLabel Class Reference
MusicToastLabel Class Reference
The class of the toast widget.
#include <musictoastlabel.h>
Public Slots
void setText (const QString &text)
Signals
void animationCloseChanged ()
Public Member Functions
MusicToastLabel (QWidget *parent=nullptr)
MusicToastLabel (const QString &text, QWidget *parent=nullptr)
~MusicToastLabel ()
void setFontMargin (int height, int width)
int timerInterval () const
void setFontSize (int size)
void popup (QWidget *parent=nullptr)
Static Public Member Functions
static void popup (const QString &text)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
Protected Attributes
QTimer m_timer
QFont m_font
QPoint m_margin
Private Slots
void closeAnimation ()
Detailed Description
The class of the toast widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musictoastlabel.h.
Constructor & Destructor Documentation
MusicToastLabel::MusicToastLabel (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musictoastlabel.cpp.
References closeAnimation(), m_font, m_timer, MT_S2MS, setFontMargin(), and setFontSize().
Referenced by popup().
MusicToastLabel::MusicToastLabel (const QString & text, QWidget * parent = nullptr) explicit
Object contsructor by context text.
Definition at line 24 of file musictoastlabel.cpp.
References setText().
MusicToastLabel::~MusicToastLabel ()
Definition at line 30 of file musictoastlabel.cpp.
References m_timer.
Member Function Documentation
void MusicToastLabel::animationCloseChanged () signal
Animation close changed.
Referenced by closeAnimation().
void MusicToastLabel::closeAnimation () private slot
Close animation when tiem out.
Definition at line 81 of file musictoastlabel.cpp.
References animationCloseChanged(), m_timer, and MT_S2MS.
Referenced by MusicToastLabel().
void MusicToastLabel::paintEvent (QPaintEvent * event) final override protected virtual
Override the widget event.
Definition at line 94 of file musictoastlabel.cpp.
References QtDrawRoundedRect.
void MusicToastLabel::popup (QWidget * parent = nullptr)
Popup the toast widget in parent widget.
Definition at line 52 of file musictoastlabel.cpp.
References G_SETTING_PTR, and MusicSettingManager::ScreenSize.
Referenced by MusicLocalSongsManagerWidget::addButtonClick(), MusicTTKFMRadioPlayWidget::addButtonClicked(), MusicItemQueryTableWidget::addSearchMusicToPlaylist(), MusicSongSearchTableWidget::addSearchMusicToPlaylist(), MusicReplayGainWidget::applyButtonClicked(), MusicLocalSongsManagerWidget::auditionButtonClick(), MusicSongSearchOnlineWidget::buttonClicked(), MusicLrcMakerWidget::checkInputValid(), MusicLrcLocalLinkWidget::confirmButtonClicked(), MusicSpectrumWidget::createLightWidget(), MusicSoundKMicroSearchTableWidget::dataDownloadPlay(), MusicTTKFMRadioPlayWidget::deleteButtonClicked(), MusicCloudManagerTableWidget::deleteFileToServer(), MusicLrcLocalLinkWidget::deleteFoundLrc(), MusicIdentifySongsWidget::detectedButtonClicked(), MusicItemQueryTableWidget::downloadBatchData(), MusicSettingWidget::downloadCacheClean(), MusicItemQueryTableWidget::downloadDataFrom(), MusicCloudManagerTableWidget::downloadFileToServer(), MusicDownloadWidget::downLoadFinished(), MusicSongCheckToolsWidget::duplicateCheckFinished(), MusicTransformWidget::exec(), MusicSongRingtoneMaker::exec(), MusicLocalSongsManagerWidget::filterIndexChanged(), MusicRightAreaWidget::functionClicked(), MusicSongsSummariziedWidget::importMusicSongsByPath(), MusicReplayGainWidget::initialize(), MusicBackgroundListWidget::itemCloseClicked(), MusicLrcSearchWidget::lrcSearchDownloadClicked(), MusicVideoView::mediaAutionPlayError(), MusicApplication::musicAddSongToLovestList(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicSoundKMicroSearchTableWidget::musicDownloadLocal(), MusicVideoSearchTableWidget::musicDownloadLocal(), MusicAbstractSongsListTableWidget::musicOpenFileDir(), MusicApplicationModule::musicToolSetsParameter(), MusicFileInformationWidget::openFileDir(), MusicSoundKMicroWidget::playFinished(), popup(), MusicTransformWidget::processTransform(), MusicIdentifySongsWidget::queryIdentifyKey(), MusicSongSharingWidget::queryUrlTimeout(), MusicSoundKMicroWidget::recordButtonClicked(), MusicSoundKMicroWidget::recordStateChanged(), MusicSongCheckToolsWidget::renameCheckFinished(), MusicCloudUploadTableWidget::reuploadFile(), MusicCloudUploadTableWidget::reuploadFiles(), MusicLrcContainerForInterior::revertLrcTimeSpeed(), MusicReplayGainWidget::rmFileButtonClicked(), MusicLrcMakerWidget::saveButtonClicked(), MusicFileInformationWidget::saveTag(), MusicAdvancedSearchedWidget::searchButtonClicked(), MusicConnectTransferWidget::selectedFiles(), MusicSoundKMicroSearchWidget::setCurrentSongName(), MusicLrcMakerWidget::setCurrentThirdWidget(), MusicSettingWidget::setNetworkProxyByType(), MusicReplayGainWidget::show(), MusicSpectrumWidget::showMessageBoxWidget(), MusicDownloadWidget::startToDownload(), MusicSettingWidget::testProxyStateChanged(), MusicSongsToolItemRenamedWidget::textChanged(), and MusicLrcArtPhotoUploadWidget::uploadButtonClicked().
void MusicToastLabel::popup (const QString & text) static
Create default label.
Definition at line 67 of file musictoastlabel.cpp.
References MusicApplication::instance(), MusicToastLabel(), popup(), and setText().
void MusicToastLabel::setFontMargin (int height, int width)
Set text margin in the body.
Definition at line 35 of file musictoastlabel.cpp.
References m_margin.
Referenced by MusicToastLabel().
void MusicToastLabel::setFontSize (int size)
Set context font size.
Definition at line 46 of file musictoastlabel.cpp.
References m_font.
Referenced by MusicToastLabel().
void MusicToastLabel::setText (const QString & text) slot
Set context text.
Definition at line 74 of file musictoastlabel.cpp.
References MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), m_font, and m_margin.
Referenced by MusicToastLabel(), popup(), and MusicSongsToolItemRenamedWidget::textChanged().
int MusicToastLabel::timerInterval () const
Get timer interval.
Definition at line 41 of file musictoastlabel.cpp.
References m_timer.
Member Data Documentation
QFont MusicToastLabel::m_font protected
Definition at line 91 of file musictoastlabel.h.
Referenced by MusicToastLabel(), setFontSize(), and setText().
QPoint MusicToastLabel::m_margin protected
Definition at line 92 of file musictoastlabel.h.
Referenced by setFontMargin(), and setText().
QTimer MusicToastLabel::m_timer protected
Definition at line 90 of file musictoastlabel.h.
Referenced by closeAnimation(), MusicToastLabel(), timerInterval(), and ~MusicToastLabel().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musictoastlabel.h
TTKModule/TTKWidget/musicCoreKits/musictoastlabel.cpp