TTKMusicPlayer: MusicWebDJRadioProgramTableWidget Class Reference
MusicWebDJRadioProgramTableWidget Class Reference
The class of the music dj radio program table widget.
#include <musicwebdjradiowidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
void createProgramItem (const MusicResultDataItem &item)
void downLoadFinished (const QByteArray &bytes)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void programItemClicked (const QString &rid, const QString &cid)
Public Member Functions
MusicWebDJRadioProgramTableWidget (QWidget *parent=nullptr)
~MusicWebDJRadioProgramTableWidget ()
void initialize (TTK::Program type)
void resizeSection () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Private Attributes
MusicDJRadioProgramRequest * m_networkRequest
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the music dj radio program table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicwebdjradiowidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioProgramTableWidget::MusicWebDJRadioProgramTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musicwebdjradiowidget.cpp.
References createProgramItem(), m_networkRequest, TTK::UI::ScrollBarStyle03, and TTK_ITEM_SIZE_L.
MusicWebDJRadioProgramTableWidget::~MusicWebDJRadioProgramTableWidget ()
Object destructor.
Definition at line 28 of file musicwebdjradiowidget.cpp.
References m_networkRequest.
Member Function Documentation
void MusicWebDJRadioProgramTableWidget::createProgramItem (const MusicResultDataItem & item) slot
Create the current program info item.
Definition at line 82 of file musicwebdjradiowidget.cpp.
References TTK::UI::Color02, downLoadFinished(), TTK::Widget::elidedText(), G_DOWNLOAD_QUERY_PTR, TTK::isCoverValid(), MusicResultDataItem::m_category, MusicResultDataItem::m_count, MusicResultDataItem::m_coverUrl, MusicResultDataItem::m_name, MusicResultDataItem::m_time, QtItemSetTextAlignment, TTKAbstractNetwork::setHeader(), MusicCoverRequest::startToRequest(), and TTK_ITEM_SIZE_2XL.
Referenced by MusicWebDJRadioProgramTableWidget().
void MusicWebDJRadioProgramTableWidget::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 127 of file musicwebdjradiowidget.cpp.
References TTKAbstractNetwork::header(), TTK_ERROR_STREAM, and TTKObjectCast.
Referenced by createProgramItem().
void MusicWebDJRadioProgramTableWidget::initialize (TTK::Program type)
Init widget.
Definition at line 33 of file musicwebdjradiowidget.cpp.
References m_networkRequest, and MusicDJRadioProgramRequest::startToRequest().
Referenced by MusicWebDJRadioProgramWidget::initialize().
void MusicWebDJRadioProgramTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 65 of file musicwebdjradiowidget.cpp.
References MusicAbstractDJRadioRequest::items(), m_networkRequest, and programItemClicked().
void MusicWebDJRadioProgramTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 51 of file musicwebdjradiowidget.cpp.
References TTKAbstractTableWidget::itemCellEntered().
void MusicWebDJRadioProgramTableWidget::programItemClicked (const QString & rid, const QString & cid) signal
Program item clicked.
Referenced by itemCellClicked().
void MusicWebDJRadioProgramTableWidget::resizeSection () const
Resize section bound by resize called.
Definition at line 38 of file musicwebdjradiowidget.cpp.
References TTK::Widget::elidedText(), G_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicWebDJRadioProgramWidget::resizeWindow().
Member Data Documentation
MusicDJRadioProgramRequest* MusicWebDJRadioProgramTableWidget::m_networkRequest private
Definition at line 80 of file musicwebdjradiowidget.h.
Referenced by initialize(), itemCellClicked(), MusicWebDJRadioProgramTableWidget(), and ~MusicWebDJRadioProgramTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiowidget.cpp