TTKMusicPlayer: MusicQueryRequest Class Reference
MusicQueryRequest Class Reference
The class of the query download data from net.
#include <musicqueryrequest.h>
Public Member Functions
MusicQueryRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value) override
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSearchByID (const QString &value)
virtual void startToQueryResult (TTK::MusicSongInformation *info, int bitrate)
void setQueryMode (QueryMode mode)
QueryMode queryMode () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryValue () const
void setItems (const TTK::MusicSongInformationList &items)
const TTK::MusicSongInformationList & items () const
bool isEmpty () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageTotalSize () const noexcept
int pageSize () const noexcept
int totalSize () const noexcept
int pageIndex () const noexcept
bool pageValid () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryServer { QueryServer::WY, QueryServer::KW, QueryServer::KG }
enum QueryType { QueryType::Music, QueryType::Movie, QueryType::Lrc, QueryType::Other }
enum QueryMode { QueryMode::Normal, QueryMode::Meta }
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from MusicAbstractQueryRequest
void clearItems ()
void createResultItem (const MusicResultInfoItem &songItem)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicAbstractQueryRequest
QString serverToString () const
bool fetchUrlPathSize (TTK::MusicSongProperty *prop, const QString &duration) const
bool fetchUrlPathSize (TTK::MusicSongPropertyList *props, const QString &duration) const
Protected Attributes inherited from MusicAbstractQueryRequest
QString m_queryValue
QString m_queryServer
QueryType m_queryType
QueryMode m_queryMode
TTK::MusicSongInformationList m_items
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicqueryrequest.h.
Constructor & Destructor Documentation
MusicQueryRequest::MusicQueryRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musicqueryrequest.cpp.
Member Function Documentation
void MusicQueryRequest::startToSearch (const QString & value) override virtual
Start to search data by input data.
Implements MusicAbstractQueryRequest.
Definition at line 9 of file musicqueryrequest.cpp.
References MusicAbstractQueryRequest::downLoadFinished(), MusicAbstractQueryRequest::m_queryValue, MusicPageQueryRequest::startToPage(), and TTK_INFO_STREAM.
Referenced by MusicKGDownloadBackgroundRequest::startToRequest(), MusicWYCoverSourceRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), MusicKWSongCommentsRequest::startToSearch(), MusicKGSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/core/musicqueryrequest.h
TTKModule/TTKCore/musicNetworkKits/music/core/musicqueryrequest.cpp