TTKMusicplayer: MusicGifLabelMaskWidget Class Reference
MusicGifLabelMaskWidget Class Reference
The class of the float gif label mask widget.
#include <musicgiflabelwidget.h>
Public Member Functions
MusicGifLabelMaskWidget (QWidget *parent=nullptr)
~MusicGifLabelMaskWidget ()
void setType (MusicGifLabelWidget::Module type)
MusicGifLabelWidget::Module type () const
void run (bool run)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
Protected Attributes
MusicGifLabelWidget * m_gifLabel
Detailed Description
The class of the float gif label mask widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 132 of file musicgiflabelwidget.h.
Constructor & Destructor Documentation
MusicGifLabelMaskWidget::MusicGifLabelMaskWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 256 of file musicgiflabelwidget.cpp.
References m_gifLabel.
MusicGifLabelMaskWidget::~MusicGifLabelMaskWidget ()
Definition at line 268 of file musicgiflabelwidget.cpp.
References m_gifLabel.
Member Function Documentation
void MusicGifLabelMaskWidget::paintEvent (QPaintEvent * event) final override protected virtual
Override the widget event.
Definition at line 302 of file musicgiflabelwidget.cpp.
void MusicGifLabelMaskWidget::run (bool run)
Run the gif.
Definition at line 283 of file musicgiflabelwidget.cpp.
References MusicGifLabelWidget::isRunning(), m_gifLabel, and MusicGifLabelWidget::run().
void MusicGifLabelMaskWidget::setType (MusicGifLabelWidget::Module type)
Set the gif type.
Definition at line 273 of file musicgiflabelwidget.cpp.
References m_gifLabel, and MusicGifLabelWidget::setType().
MusicGifLabelWidget::Module MusicGifLabelMaskWidget::type () const
Get the gif type.
Definition at line 278 of file musicgiflabelwidget.cpp.
References m_gifLabel, and MusicGifLabelWidget::type().
Member Data Documentation
MusicGifLabelWidget* MusicGifLabelMaskWidget::m_gifLabel protected
Definition at line 163 of file musicgiflabelwidget.h.
Referenced by MusicGifLabelMaskWidget(), run(), setType(), type(), and ~MusicGifLabelMaskWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicgiflabelwidget.h
TTKModule/TTKWidget/musicCoreKits/musicgiflabelwidget.cpp