TTKMusicplayer: MusicDownloadData Struct Reference
MusicDownloadData Struct Reference
The class of the data download item.
#include <musicsongsearchonlinewidget.h>
Public Member Functions
void clear ()
bool isValid () const
Public Attributes
QString m_songName
QString m_timestamp
QString m_format
Detailed Description
The class of the data download item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicsongsearchonlinewidget.h.
Member Function Documentation
void MusicDownloadData::clear () inline
Definition at line 34 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchTableWidget::addSearchMusicToPlaylist(), and MusicSongSearchTableWidget::searchDataDwonloadFinished().
bool MusicDownloadData::isValid () const inline
Definition at line 41 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchTableWidget::searchDataDwonloadFinished().
Member Data Documentation
QString MusicDownloadData::m_format
Definition at line 32 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchTableWidget::addSearchMusicToPlaylist(), and MusicSongSearchTableWidget::searchDataDwonloadFinished().
QString MusicDownloadData::m_songName
Definition at line 30 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchTableWidget::addSearchMusicToPlaylist(), and MusicSongSearchTableWidget::searchDataDwonloadFinished().
QString MusicDownloadData::m_timestamp
Definition at line 31 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchTableWidget::addSearchMusicToPlaylist(), and MusicSongSearchTableWidget::searchDataDwonloadFinished().
The documentation for this struct was generated from the following file:
TTKModule/TTKWidget/musicWidgetKits/musicsongsearchonlinewidget.h