TTKMusicPlayer: QAlgorithm::DesPrivate Class Reference
QAlgorithm::DesPrivate Class Reference
The class of the des wrapper private.
Public Member Functions
quint64 bitTransform (const int *array, int len, quint64 source)
void desSubKeys (quint64 key, quint64 *K, Mode mode)
quint64 des64 (quint64 *subkeys, quint64 data)
char * encrypt (char *src, int length, char *key)
Public Member Functions inherited from TTKPrivate< Des >
TTKPrivate ()
virtual ~TTKPrivate ()=default
void setPublic (Des *pub)
Public Attributes
Mode m_mode
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< Des >
Des * ttk_q () const
Detailed Description
The class of the des wrapper private.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 179 of file deswrapper.cpp.
Member Function Documentation
quint64 QAlgorithm::DesPrivate::bitTransform (const int * array, int len, quint64 source)
Definition at line 190 of file deswrapper.cpp.
Referenced by des64(), and desSubKeys().
quint64 QAlgorithm::DesPrivate::des64 (quint64 * subkeys, quint64 data)
Definition at line 227 of file deswrapper.cpp.
References bitTransform(), and int().
Referenced by encrypt().
void QAlgorithm::DesPrivate::desSubKeys (quint64 key, quint64 * K, Mode mode)
Definition at line 205 of file deswrapper.cpp.
References bitTransform(), and QAlgorithm::Decrypt.
Referenced by encrypt().
char * QAlgorithm::DesPrivate::encrypt (char * src, int length, char * key)
Definition at line 276 of file deswrapper.cpp.
References des64(), desSubKeys(), free(), m_mode, and malloc().
Member Data Documentation
Mode QAlgorithm::DesPrivate::m_mode
Definition at line 187 of file deswrapper.cpp.
Referenced by encrypt().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qalgorithm/deswrapper.cpp