TTKMusicplayer: MusicPlatformExtras Class Reference
MusicPlatformExtras Class Reference
The class of the platform extras.
#include <musicplatformextras.h>
Public Member Functions
MusicPlatformExtras (QObject *parent=nullptr)
~MusicPlatformExtras ()
void setCurrentPlayStatus (bool status) const
void disableBlurBehindWindow (bool enable)
bool isDisableBlurBehindWindow () const
Protected Attributes
bool m_disableBlurBehindWindow
MusicAbstractPlatformExtras * m_platformExtras
Detailed Description
The class of the platform extras.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicplatformextras.h.
Constructor & Destructor Documentation
MusicPlatformExtras::MusicPlatformExtras (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 187 of file musicplatformextras.cpp.
References m_disableBlurBehindWindow, and m_platformExtras.
MusicPlatformExtras::~MusicPlatformExtras ()
Definition at line 200 of file musicplatformextras.cpp.
References m_platformExtras.
Member Function Documentation
void MusicPlatformExtras::disableBlurBehindWindow (bool enable)
Enable or disable blur behind window.
Definition at line 210 of file musicplatformextras.cpp.
References MusicAbstractPlatformExtras::action(), m_disableBlurBehindWindow, and m_platformExtras.
Referenced by MusicBottomAreaWidget::setWindowConcise().
bool MusicPlatformExtras::isDisableBlurBehindWindow () const inline
Get blur behind window state.
Definition at line 51 of file musicplatformextras.h.
Referenced by MusicBottomAreaWidget::setWindowConcise().
void MusicPlatformExtras::setCurrentPlayStatus (bool status) const
Set current play state button.
Definition at line 205 of file musicplatformextras.cpp.
References m_platformExtras, and MusicAbstractPlatformExtras::setStatus().
Referenced by MusicBottomAreaWidget::setCurrentPlayStatus().
Member Data Documentation
bool MusicPlatformExtras::m_disableBlurBehindWindow protected
Definition at line 54 of file musicplatformextras.h.
Referenced by disableBlurBehindWindow(), and MusicPlatformExtras().
MusicAbstractPlatformExtras* MusicPlatformExtras::m_platformExtras protected
Definition at line 55 of file musicplatformextras.h.
Referenced by disableBlurBehindWindow(), MusicPlatformExtras(), setCurrentPlayStatus(), and ~MusicPlatformExtras().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplatformextras.h
TTKModule/TTKWidget/musicWidgetKits/musicplatformextras.cpp