TTKMusicplayer: MusicBackgroundListItem Class Reference
MusicBackgroundListItem Class Reference
The class of the background list item.
#include <musicbackgroundlistwidget.h>
Signals
void closeClicked (MusicBackgroundListItem *item)
void itemClicked (MusicBackgroundListItem *item)
Public Member Functions
MusicBackgroundListItem (QWidget *parent=nullptr)
void setFileName (const QString &name)
QString fileName () const
void setFilePath (const QString &path)
QString filePath () const
void updatePixImage ()
void updatePixImage (const MusicBackgroundImage &image)
bool contains (const MusicSkinItem &item) const
void setSelect (bool s)
bool isSelect () const
void setSelectEnabled (bool s)
bool isSelectEnabled () const
void setCloseEnabled (bool s)
bool isCloseEnabled () const
void setShowNameEnabled (bool s)
bool isShowNameEnabled () const
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void paintEvent (QPaintEvent *event) overridefinal
Protected Attributes
bool m_printMask
bool m_isSelected
bool m_selectedMask
bool m_closeMask
bool m_closeSet
bool m_showNameMask
QString m_name
QString m_path
MusicSkinItem m_imageInfo
Detailed Description
The class of the background list item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicbackgroundlistwidget.h.
Constructor & Destructor Documentation
MusicBackgroundListItem::MusicBackgroundListItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicbackgroundlistwidget.cpp.
Member Function Documentation
void MusicBackgroundListItem::closeClicked (MusicBackgroundListItem * item) signal
Current item close clicked.
Referenced by mousePressEvent().
bool MusicBackgroundListItem::contains (const MusicSkinItem & item) const
Current item contains or not.
Definition at line 41 of file musicbackgroundlistwidget.cpp.
References MusicSkinItem::isValid(), m_imageInfo, and MusicSkinItem::m_name.
Referenced by mousePressEvent().
void MusicBackgroundListItem::enterEvent (QtEnterEvent * event) final override protected virtual
Definition at line 95 of file musicbackgroundlistwidget.cpp.
References m_closeMask, and m_printMask.
QString MusicBackgroundListItem::fileName () const inline
Get item file name.
Definition at line 46 of file musicbackgroundlistwidget.h.
Referenced by MusicBackgroundListWidget::itemHasClicked(), and MusicBackgroundSkinDialog::listWidgetItemClicked().
QString MusicBackgroundListItem::filePath () const inline
Get item file name.
Definition at line 54 of file musicbackgroundlistwidget.h.
Referenced by MusicBackgroundListWidget::itemCloseClicked().
bool MusicBackgroundListItem::isCloseEnabled () const inline
Get close option set the current item.
Definition at line 94 of file musicbackgroundlistwidget.h.
bool MusicBackgroundListItem::isSelect () const inline
Get current selected item state.
Definition at line 76 of file musicbackgroundlistwidget.h.
bool MusicBackgroundListItem::isSelectEnabled () const inline
Get current selected item state.
Definition at line 85 of file musicbackgroundlistwidget.h.
bool MusicBackgroundListItem::isShowNameEnabled () const inline
Get show title name set the current item.
Definition at line 103 of file musicbackgroundlistwidget.h.
void MusicBackgroundListItem::itemClicked (MusicBackgroundListItem * item) signal
Current item clicked.
Referenced by mousePressEvent().
void MusicBackgroundListItem::leaveEvent (QEvent * event) final override protected virtual
Definition at line 87 of file musicbackgroundlistwidget.cpp.
References m_closeMask, and m_printMask.
void MusicBackgroundListItem::mousePressEvent (QMouseEvent * event) final override protected virtual
Override the widget event.
Definition at line 74 of file musicbackgroundlistwidget.cpp.
References closeClicked(), contains(), itemClicked(), and m_closeSet.
void MusicBackgroundListItem::paintEvent (QPaintEvent * event) final override protected virtual
Definition at line 103 of file musicbackgroundlistwidget.cpp.
References MusicUtils::Widget::fontTextWidth(), m_closeMask, m_closeSet, m_imageInfo, m_isSelected, MusicSkinItem::m_name, m_name, m_printMask, m_selectedMask, m_showNameMask, and MusicSkinItem::m_useCount.
void MusicBackgroundListItem::setCloseEnabled (bool s)
Close option set the current item.
Definition at line 62 of file musicbackgroundlistwidget.cpp.
References m_closeSet.
Referenced by MusicBackgroundListWidget::createItem().
void MusicBackgroundListItem::setFileName (const QString & name) inline
Set item file name.
Definition at line 42 of file musicbackgroundlistwidget.h.
References name.
Referenced by MusicBackgroundListWidget::createItem().
void MusicBackgroundListItem::setFilePath (const QString & path) inline
Set item file name.
Definition at line 50 of file musicbackgroundlistwidget.h.
Referenced by MusicBackgroundListWidget::createItem().
void MusicBackgroundListItem::setSelect (bool s)
Select the current item.
Definition at line 50 of file musicbackgroundlistwidget.cpp.
References m_isSelected.
Referenced by MusicBackgroundListWidget::itemHasClicked().
void MusicBackgroundListItem::setSelectEnabled (bool s)
Select the current item enable or not.
Definition at line 56 of file musicbackgroundlistwidget.cpp.
References m_selectedMask.
void MusicBackgroundListItem::setShowNameEnabled (bool s)
Show title name set the current item.
Definition at line 68 of file musicbackgroundlistwidget.cpp.
References m_showNameMask.
void MusicBackgroundListItem::updatePixImage ()
Update pix image.
Definition at line 23 of file musicbackgroundlistwidget.cpp.
References m_path, and MusicExtractWrapper::outputSkin().
Referenced by MusicBackgroundListWidget::createItem().
void MusicBackgroundListItem::updatePixImage (const MusicBackgroundImage & image)
Update pix image.
Definition at line 35 of file musicbackgroundlistwidget.cpp.
References m_imageInfo, MusicBackgroundImage::m_item, and MusicBackgroundImage::m_pix.
Member Data Documentation
bool MusicBackgroundListItem::m_closeMask protected
Definition at line 125 of file musicbackgroundlistwidget.h.
Referenced by enterEvent(), leaveEvent(), and paintEvent().
bool MusicBackgroundListItem::m_closeSet protected
Definition at line 125 of file musicbackgroundlistwidget.h.
Referenced by mousePressEvent(), paintEvent(), and setCloseEnabled().
MusicSkinItem MusicBackgroundListItem::m_imageInfo protected
Definition at line 127 of file musicbackgroundlistwidget.h.
Referenced by contains(), paintEvent(), and updatePixImage().
bool MusicBackgroundListItem::m_isSelected protected
Definition at line 124 of file musicbackgroundlistwidget.h.
Referenced by paintEvent(), and setSelect().
QString MusicBackgroundListItem::m_name protected
Definition at line 126 of file musicbackgroundlistwidget.h.
Referenced by paintEvent().
QString MusicBackgroundListItem::m_path protected
Definition at line 126 of file musicbackgroundlistwidget.h.
Referenced by updatePixImage().
bool MusicBackgroundListItem::m_printMask protected
Definition at line 124 of file musicbackgroundlistwidget.h.
Referenced by enterEvent(), leaveEvent(), and paintEvent().
bool MusicBackgroundListItem::m_selectedMask protected
Definition at line 124 of file musicbackgroundlistwidget.h.
Referenced by paintEvent(), and setSelectEnabled().
bool MusicBackgroundListItem::m_showNameMask protected
Definition at line 125 of file musicbackgroundlistwidget.h.
Referenced by paintEvent(), and setShowNameEnabled().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundlistwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundlistwidget.cpp