TTKMusicplayer: MusicPlaylistQueryCategoryItem Class Reference
MusicPlaylistQueryCategoryItem Class Reference
The class of the playlist music query category item.
#include <musicplaylistquerycategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicResultsCategoryItem &category)
Public Member Functions
MusicPlaylistQueryCategoryItem (QWidget *parent=nullptr)
void setCategory (const MusicResultsCategory &category)
Protected Attributes
MusicResultsCategory m_category
Detailed Description
The class of the playlist music query category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicplaylistquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicPlaylistQueryCategoryItem::MusicPlaylistQueryCategoryItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicplaylistquerycategorypopwidget.cpp.
Member Function Documentation
void MusicPlaylistQueryCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 48 of file musicplaylistquerycategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicResultsCategory::m_items.
Referenced by setCategory().
void MusicPlaylistQueryCategoryItem::categoryChanged (const MusicResultsCategoryItem & category) signal
Current category changed.
Referenced by buttonClicked().
void MusicPlaylistQueryCategoryItem::setCategory (const MusicResultsCategory & category)
Set current category.
Definition at line 16 of file musicplaylistquerycategorypopwidget.cpp.
References buttonClicked(), ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicResultsCategory::m_category, m_category, MusicResultsCategory::m_items, MusicClickedGroup::mapped(), MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSColorStyle08, and MusicUIObject::MQSSFontStyle03.
Referenced by MusicPlaylistFoundCategoryPopWidget::setCategory().
Member Data Documentation
MusicResultsCategory MusicPlaylistQueryCategoryItem::m_category protected
Definition at line 56 of file musicplaylistquerycategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistquerycategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistquerycategorypopwidget.cpp