TTKMusicPlayer: ToolUrl Class Reference
ToolUrl Class Reference
The class of the url tool.
#include <toolurl.h>
Public Member Functions
ToolUrl (QWidget *parent=nullptr)
~ToolUrl ()
Private Slots
void encodeClicked ()
void decodeClicked ()
Private Attributes
Ui::ToolUrl * m_ui
Detailed Description
The class of the url tool.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file toolurl.h.
Constructor & Destructor Documentation
ToolUrl::ToolUrl (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file toolurl.cpp.
References decodeClicked(), encodeClicked(), and m_ui.
ToolUrl::~ToolUrl ()
Object destructor.
Definition at line 18 of file toolurl.cpp.
References m_ui.
Member Function Documentation
void ToolUrl::decodeClicked () private slot
Definition at line 36 of file toolurl.cpp.
References key, m_ui, TTK::Algorithm::mdII(), and MDII_URL_KEY.
Referenced by ToolUrl().
void ToolUrl::encodeClicked () private slot
Definition at line 23 of file toolurl.cpp.
References key, m_ui, TTK::Algorithm::mdII(), and MDII_URL_KEY.
Referenced by ToolUrl().
Member Data Documentation
Ui::ToolUrl* ToolUrl::m_ui private
Definition at line 49 of file toolurl.h.
Referenced by decodeClicked(), encodeClicked(), ToolUrl(), and ~ToolUrl().
The documentation for this class was generated from the following files:
TTKRun/TTKTools/GenerateUrl/toolurl.h
TTKRun/TTKTools/GenerateUrl/toolurl.cpp