TTKMusicplayer: MusicLrcAnalysis Class Reference
MusicLrcAnalysis Class Reference
The class of the core lrc analysis.
#include <musiclrcanalysis.h>
Public Types
enum State { Null, OpenFileSuccess, OpenFileFail, LrcEmpty }
enum LrcFormat {
Type01, Type02, Type03, Type04,
Type05, Type06, Type07, Type08,
Type09, Type10, Type11, Type12,
Type13, Type14
}
Public Slots
void getTranslatedLrc ()
Public Member Functions
MusicLrcAnalysis (QObject *parent=0)
~MusicLrcAnalysis ()
void setLineMax (int max)
int getLineMax () const
int getMiddle () const
State setLrcData (const QByteArray &data)
State setLrcData (const MusicObject::MIntStringMap &data)
State transLrcFileToTime (const QString &lrcFileName)
State transKrcFileToTime (const QString &krcFileName)
qint64 setSongSpeedAndSlow (qint64 time)
void revertLrcTime (qint64 pos)
void saveLrcTimeChanged ()
void setCurrentIndex (int index)
int getCurrentIndex () const
void setCurrentFileName (const QString &name)
QString getCurrentFileName () const
bool isValid () const
bool isEmpty () const
int count () const
QString getText (int index) const
bool findText (qint64 current, qint64 total, QString &pre, QString &last, qint64 &interval) const
qint64 findTime (int index) const
qint64 findTime (const QStringList &ts) const
QStringList getAllLrcList () const
QString getAllLrcString () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
void matchLrcLine (const QString &oneLine)
void matchLrcLine (const QString &oneLine, const QString &cap, const QString &first, const QString &second)
void matchLrcLine (const QString &oneLine, QString cap, const QString &splite)
void matchLrcLine (const QString &oneLine, const QString &cap, const QString &first, const QString &second, const QString &third)
Protected Attributes
int m_lineMax
int m_currentLrcIndex
QString m_currentLrcFileName
MusicObject::MIntStringMap m_lrcContainer
QStringList m_currentShowLrcContainer
MusicTranslationThread * m_translationThread
Detailed Description
The class of the core lrc analysis.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musiclrcanalysis.h.
Member Enumeration Documentation
enum MusicLrcAnalysis::LrcFormat
Enumerator
Type01
[xx:xx.xxx]
Type02
[xx:xx.xx]
Type03
[xx:xx.x]
Type04
[xx:xx:xxx]
Type05
[xx:xx:xx]
Type06
[xx:xx:x]
Type07
[xx:xx]
Type08
[xx.xx.xxx]
Type09
[xx.xx.xx]
Type10
[xx.xx.x]
Type11
[xx.xx:xxx]
Type12
[xx.xx:xx]
Type13
[xx.xx:x]
Type14
[xx.xx]
Definition at line 44 of file musiclrcanalysis.h.
enum MusicLrcAnalysis::State
Enumerator
Null
no any operator
OpenFileSuccess
open file success
OpenFileFail
open file failed
LrcEmpty
current lrc empty
Definition at line 36 of file musiclrcanalysis.h.
Constructor & Destructor Documentation
MusicLrcAnalysis::MusicLrcAnalysis (QObject * parent = 0) explicit
Object contsructor.
Definition at line 9 of file musiclrcanalysis.cpp.
References m_currentLrcIndex, m_lineMax, and m_translationThread.
MusicLrcAnalysis::~MusicLrcAnalysis ()
Definition at line 17 of file musiclrcanalysis.cpp.
References m_translationThread.
Member Function Documentation
int MusicLrcAnalysis::count () const
Check current container count.
Definition at line 447 of file musiclrcanalysis.cpp.
References m_lrcContainer.
Referenced by MusicLrcContainerForInline::mouseMoveEvent(), and MusicLrcContainerForInline::paintEvent().
bool MusicLrcAnalysis::findText (qint64 current, qint64 total, QString & pre, QString & last, qint64 & interval) const
Get current lrc and next lrc in container by current time.
Definition at line 467 of file musiclrcanalysis.cpp.
References isEmpty(), and m_lrcContainer.
Referenced by MusicLrcContainerForInline::findText(), MusicSoundKMicroWidget::positionChanged(), and MusicLrcMakerWidget::positionChanged().
qint64 MusicLrcAnalysis::findTime (int index) const
Get current time by index.
Definition at line 507 of file musiclrcanalysis.cpp.
References m_currentShowLrcContainer, m_lineMax, and m_lrcContainer.
Referenced by findTime(), MusicLrcContainerForInline::mouseReleaseEvent(), MusicLrcContainerForInline::paintEvent(), MusicIdentifySongsWidget::positionChanged(), and MusicWebMusicRadioWidget::positionChanged().
qint64 MusicLrcAnalysis::findTime (const QStringList & ts) const
Get current time by texts.
Definition at line 527 of file musiclrcanalysis.cpp.
References findTime(), getMiddle(), and m_currentShowLrcContainer.
QStringList MusicLrcAnalysis::getAllLrcList () const
Get all lrcs from container.
Definition at line 545 of file musiclrcanalysis.cpp.
References m_lrcContainer.
Referenced by MusicLrcContainerForInline::showLrcPosterWidget().
QString MusicLrcAnalysis::getAllLrcString () const
Get all lrcs from container.
Definition at line 550 of file musiclrcanalysis.cpp.
References m_lrcContainer.
Referenced by MusicLrcContainerForInline::lrcCopyClipboard().
QString MusicLrcAnalysis::getClassName () static
Get class object name.
Definition at line 22 of file musiclrcanalysis.cpp.
QString MusicLrcAnalysis::getCurrentFileName () const inline
Get current file name.
Definition at line 132 of file musiclrcanalysis.h.
Referenced by MusicLrcContainerForInline::contextMenuEvent(), and MusicLrcContainerForInline::lrcOpenFileDir().
int MusicLrcAnalysis::getCurrentIndex () const inline
Get current middle index.
Definition at line 124 of file musiclrcanalysis.h.
Referenced by MusicLrcContainerForInline::mouseMoveEvent(), MusicLrcContainerForInline::mouseReleaseEvent(), MusicLrcContainerForInline::paintEvent(), MusicIdentifySongsWidget::positionChanged(), MusicWebMusicRadioWidget::positionChanged(), MusicLrcContainerForInline::resizeWidth(), MusicLrcContainerForInline::setLrcSize(), MusicSoundKMicroWidget::updateAnimationLrc(), MusicLrcMakerWidget::updateAnimationLrc(), and MusicLrcContainerForInline::updateAnimationLrc().
int MusicLrcAnalysis::getLineMax () const inline
Get current line maximum value.
Definition at line 81 of file musiclrcanalysis.h.
Referenced by MusicLrcMakerWidget::createThirdWidget(), MusicSoundKMicroWidget::downLoadFinished(), MusicLrcContainerForWallpaper::initCurrentLrc(), MusicLrcContainerForInline::initCurrentLrc(), MusicLrcContainerForInline::mouseMoveEvent(), MusicLrcContainerForInline::MusicLrcContainerForInline(), MusicSoundKMicroWidget::MusicSoundKMicroWidget(), MusicIdentifySongsWidget::positionChanged(), MusicWebMusicRadioWidget::positionChanged(), MusicLrcContainerForInline::resizeWidth(), MusicLrcMakerWidget::setCurrentThirdWidget(), MusicLrcContainerForInline::setItemStyleSheet(), MusicLrcContainerForInline::setLrcSize(), MusicLrcContainerForInline::showNoLrcCurrentInfo(), MusicLrcContainerForInline::transLyricFileToTime(), MusicLrcContainerForWallpaper::updateAnimationLrc(), MusicSoundKMicroWidget::updateAnimationLrc(), MusicLrcMakerWidget::updateAnimationLrc(), and MusicLrcContainerForInline::updateAnimationLrc().
int MusicLrcAnalysis::getMiddle () const inline
Get current line middle number.
Definition at line 85 of file musiclrcanalysis.h.
Referenced by findTime(), MusicLrcContainerForInline::initCurrentLrc(), MusicLrcContainerForInline::mouseMoveEvent(), MusicLrcContainerForInline::paintEvent(), MusicSoundKMicroWidget::playButtonChanged(), MusicSoundKMicroWidget::positionChanged(), MusicIdentifySongsWidget::positionChanged(), MusicWebMusicRadioWidget::positionChanged(), MusicLrcMakerWidget::positionChanged(), setLrcData(), setSongSpeedAndSlow(), MusicLrcContainerForInline::showNoLrcCurrentInfo(), MusicLrcContainerForInline::startTimerClock(), MusicLrcContainerForInline::stopLrcMask(), MusicLrcContainerForInline::text(), MusicLrcMakerWidget::thirdWidgetStateButtonClicked(), transKrcFileToTime(), MusicLrcContainerForInline::transLyricFileToTime(), MusicSoundKMicroWidget::updateAnimationLrc(), MusicLrcMakerWidget::updateAnimationLrc(), and MusicLrcContainerForInline::updateAnimationLrc().
QString MusicLrcAnalysis::getText (int index) const
Get current lrc text by index.
Definition at line 452 of file musiclrcanalysis.cpp.
References m_currentLrcIndex, and m_currentShowLrcContainer.
Referenced by MusicLrcContainerForInline::mouseMoveEvent(), MusicIdentifySongsWidget::positionChanged(), MusicWebMusicRadioWidget::positionChanged(), MusicLrcContainerForInline::setLrcSize(), MusicLrcContainerForWallpaper::updateAnimationLrc(), MusicSoundKMicroWidget::updateAnimationLrc(), MusicLrcMakerWidget::updateAnimationLrc(), and MusicLrcContainerForInline::updateAnimationLrc().
void MusicLrcAnalysis::getTranslatedLrc () slot
Get all lrcs from tr container.
Definition at line 560 of file musiclrcanalysis.cpp.
References m_lrcContainer, m_translationThread, MusicTranslationThread::startToDownload(), MusicTranslationThread::Type_Auto, and MusicTranslationThread::Type_Zh.
bool MusicLrcAnalysis::isEmpty () const
Check current container is empty or not.
Definition at line 442 of file musiclrcanalysis.cpp.
References m_lrcContainer.
Referenced by MusicLrcContainerForInline::contextMenuEvent(), findText(), isValid(), MusicSoundKMicroWidget::positionChanged(), MusicIdentifySongsWidget::positionChanged(), MusicWebMusicRadioWidget::positionChanged(), MusicLrcMakerWidget::positionChanged(), and MusicLrcContainerForInline::resizeWidth().
bool MusicLrcAnalysis::isValid () const
Check current index is valid or not.
Definition at line 436 of file musiclrcanalysis.cpp.
References isEmpty(), m_currentLrcIndex, m_currentShowLrcContainer, and m_lineMax.
Referenced by MusicLrcContainerForInline::mouseMoveEvent(), MusicLrcContainerForInline::mouseReleaseEvent(), MusicSoundKMicroWidget::positionChanged(), MusicLrcContainerForWallpaper::updateCurrentLrc(), MusicLrcContainerForInline::updateCurrentLrc(), and MusicLrcMakerWidget::updateCurrentLrc().
void MusicLrcAnalysis::matchLrcLine (const QString & oneLine) protected
Lrc analysis by match lrc line base.
Definition at line 170 of file musiclrcanalysis.cpp.
References Type01, Type02, Type03, Type04, Type05, Type06, Type07, Type08, Type09, Type10, Type11, Type12, Type13, and Type14.
Referenced by setLrcData(), and transKrcFileToTime().
void MusicLrcAnalysis::matchLrcLine (const QString & oneLine, const QString & cap, const QString & first, const QString & second) protected
Lrc analysis by match lrc line two[xx.(:)xx].
Definition at line 336 of file musiclrcanalysis.cpp.
References m_lrcContainer, MT_M2MS, and MT_S2MS.
void MusicLrcAnalysis::matchLrcLine (const QString & oneLine, QString cap, const QString & splite) protected
Lrc analysis by match lrc line three[xx.xx.x(xx)][xx:xx:x(xx)].
Definition at line 350 of file musiclrcanalysis.cpp.
References m_lrcContainer, MT_M2MS, and MT_S2MS.
void MusicLrcAnalysis::matchLrcLine (const QString & oneLine, const QString & cap, const QString & first, const QString & second, const QString & third) protected
Lrc analysis by match lrc line three[xx.(:)xx.(:)x(xx)].
Definition at line 318 of file musiclrcanalysis.cpp.
References m_lrcContainer, MT_M2MS, and MT_S2MS.
void MusicLrcAnalysis::revertLrcTime (qint64 pos)
Revert lrc time by pos, both + or - the same pos.
Definition at line 401 of file musiclrcanalysis.cpp.
References m_lrcContainer.
Referenced by MusicLrcMakerWidget::lrcSpeedFaster(), MusicLrcMakerWidget::lrcSpeedSlower(), and MusicLrcContainerForInline::revertLrcTimeSpeed().
void MusicLrcAnalysis::saveLrcTimeChanged ()
Save lrc time changed to current lrc file.
Definition at line 413 of file musiclrcanalysis.cpp.
References MusicTime::All_Msec, APPNAME, m_currentLrcFileName, m_lrcContainer, and MusicTime::toString().
Referenced by MusicLrcMakerWidget::saveButtonClicked(), and MusicLrcContainerForInline::saveLrcTimeChanged().
void MusicLrcAnalysis::setCurrentFileName (const QString & name) inline
Set current file name.
Definition at line 128 of file musiclrcanalysis.h.
Referenced by MusicLrcMakerWidget::setCurrentSongName().
void MusicLrcAnalysis::setCurrentIndex (int index) inline
Set current middle index.
Definition at line 120 of file musiclrcanalysis.h.
Referenced by MusicLrcContainerForInline::mouseMoveEvent(), MusicIdentifySongsWidget::positionChanged(), MusicWebMusicRadioWidget::positionChanged(), MusicLrcContainerForInline::setLrcSize(), MusicSoundKMicroWidget::updateAnimationLrc(), MusicLrcMakerWidget::updateAnimationLrc(), and MusicLrcContainerForInline::updateAnimationLrc().
void MusicLrcAnalysis::setLineMax (int max) inline
Set current line maximum value.
Definition at line 77 of file musiclrcanalysis.h.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicLrcMakerWidget::createThirdWidget(), MusicLrcContainerForInline::MusicLrcContainerForInline(), MusicSoundKMicroWidget::MusicSoundKMicroWidget(), MusicWebMusicRadioWidget::MusicWebMusicRadioWidget(), and MusicLrcContainerForInline::setLrcSizeProperty().
MusicLrcAnalysis::State MusicLrcAnalysis::setLrcData (const QByteArray & data)
Set lrc container data from other raw data.
Definition at line 27 of file musiclrcanalysis.cpp.
References getMiddle(), LrcEmpty, m_currentLrcIndex, m_currentShowLrcContainer, m_lrcContainer, matchLrcLine(), and OpenFileSuccess.
Referenced by MusicSoundKMicroWidget::downLoadFinished(), MusicLrcMakerWidget::setCurrentThirdWidget(), and transLrcFileToTime().
MusicLrcAnalysis::State MusicLrcAnalysis::setLrcData (const MusicObject::MIntStringMap & data)
Set lrc container data from other raw data.
Definition at line 67 of file musiclrcanalysis.cpp.
References getMiddle(), LrcEmpty, m_currentLrcIndex, m_currentShowLrcContainer, m_lrcContainer, and OpenFileSuccess.
qint64 MusicLrcAnalysis::setSongSpeedAndSlow (qint64 time)
Set song speed and slow by given time, return new time.
Definition at line 368 of file musiclrcanalysis.cpp.
References getMiddle(), m_currentLrcIndex, m_currentShowLrcContainer, and m_lrcContainer.
Referenced by MusicLrcMakerWidget::lrcSpeedFaster(), MusicLrcMakerWidget::lrcSpeedSlower(), MusicSoundKMicroWidget::setPosition(), MusicLrcContainerForInline::setSongSpeedAndSlow(), and MusicLrcMakerWidget::timeSliderValueChanged().
MusicLrcAnalysis::State MusicLrcAnalysis::transKrcFileToTime (const QString & krcFileName)
Analysis krc file to map return the state.
Definition at line 116 of file musiclrcanalysis.cpp.
References MusicLrcFromKrc::decode(), MusicLrcFromKrc::getDecodeString(), getMiddle(), LrcEmpty, m_currentLrcFileName, m_currentLrcIndex, m_currentShowLrcContainer, m_lrcContainer, matchLrcLine(), OpenFileFail, and OpenFileSuccess.
Referenced by MusicLrcContainerForInline::transLyricFileToTime().
MusicLrcAnalysis::State MusicLrcAnalysis::transLrcFileToTime (const QString & lrcFileName)
Analysis lrc file to map return the state.
Definition at line 101 of file musiclrcanalysis.cpp.
References m_currentLrcFileName, OpenFileFail, and setLrcData().
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicWebMusicRadioWidget::lrcDownloadStateChanged(), and MusicLrcContainerForInline::transLyricFileToTime().
Member Data Documentation
QString MusicLrcAnalysis::m_currentLrcFileName protected
Definition at line 202 of file musiclrcanalysis.h.
Referenced by saveLrcTimeChanged(), transKrcFileToTime(), and transLrcFileToTime().
int MusicLrcAnalysis::m_currentLrcIndex protected
Definition at line 201 of file musiclrcanalysis.h.
Referenced by getText(), isValid(), MusicLrcAnalysis(), setLrcData(), setSongSpeedAndSlow(), and transKrcFileToTime().
QStringList MusicLrcAnalysis::m_currentShowLrcContainer protected
Definition at line 204 of file musiclrcanalysis.h.
Referenced by findTime(), getText(), isValid(), setLrcData(), setSongSpeedAndSlow(), and transKrcFileToTime().
int MusicLrcAnalysis::m_lineMax protected
Definition at line 201 of file musiclrcanalysis.h.
Referenced by findTime(), isValid(), and MusicLrcAnalysis().
MusicObject::MIntStringMap MusicLrcAnalysis::m_lrcContainer protected
Definition at line 203 of file musiclrcanalysis.h.
Referenced by count(), findText(), findTime(), getAllLrcList(), getAllLrcString(), getTranslatedLrc(), isEmpty(), matchLrcLine(), revertLrcTime(), saveLrcTimeChanged(), setLrcData(), setSongSpeedAndSlow(), and transKrcFileToTime().
MusicTranslationThread* MusicLrcAnalysis::m_translationThread protected
Definition at line 205 of file musiclrcanalysis.h.
Referenced by getTranslatedLrc(), MusicLrcAnalysis(), and ~MusicLrcAnalysis().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicLrcKits/musiclrcanalysis.h
TTKModule/TTKCore/musicLrcKits/musiclrcanalysis.cpp