TTKMusicplayer: MusicArtistListQueryWidget Class Reference
MusicArtistListQueryWidget Class Reference
The class of the artist list music query widget.
#include <musicartistlistquerywidget.h>
Public Slots
void createArtistListItem (const MusicResultsItem &item)
void currentArtistListClicked (const MusicResultsItem &item)
void categoryChanged (const MusicResultsCategoryItem &category)
void buttonClicked (int index)
void numberButtonClicked (int index)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistListQueryWidget (QWidget *parent=nullptr)
~MusicArtistListQueryWidget ()
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameById (const QString &id) overridefinal
virtual void resizeWindow () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Protected Attributes
bool m_initialized
bool m_categoryChanged
QString m_categoryId
QGridLayout * m_gridLayout
MusicPageQueryWidget * m_pageQueryWidget
MusicArtistListQueryCategoryPopWidget * m_categoryButton
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the artist list music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 70 of file musicartistlistquerywidget.h.
Constructor & Destructor Documentation
MusicArtistListQueryWidget::MusicArtistListQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 40 of file musicartistlistquerywidget.cpp.
References createArtistListItem(), G_DOWNLOAD_QUERY_PTR, m_categoryButton, m_categoryChanged, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, and m_pageQueryWidget.
MusicArtistListQueryWidget::~MusicArtistListQueryWidget ()
Definition at line 57 of file musicartistlistquerywidget.cpp.
References m_categoryButton, m_gridLayout, MusicAbstractItemQueryWidget::m_networkRequest, and m_pageQueryWidget.
Member Function Documentation
void MusicArtistListQueryWidget::buttonClicked (int index) slot
Page widget button has changed.
Definition at line 201 of file musicartistlistquerywidget.cpp.
References MusicPageQueryWidget::currentIndex(), m_gridLayout, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicPageQueryWidget::page(), MusicPageQueryRequest::pageSize(), MusicPageQueryRequest::startToPage(), and MusicPageQueryRequest::totalSize().
Referenced by createArtistListItem().
void MusicArtistListQueryWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 187 of file musicartistlistquerywidget.cpp.
References MusicArtistListQueryCategoryPopWidget::closeMenu(), DEFAULT_NORMAL_LEVEL, m_categoryButton, m_categoryId, MusicResultsCategoryItem::m_key, MusicAbstractItemQueryWidget::m_songNameFull, MusicResultsCategoryItem::m_value, and numberButtonClicked().
void MusicArtistListQueryWidget::createArtistListItem (const MusicResultsItem & item) slot
Query all quality musics is finished.
Definition at line 93 of file musicartistlistquerywidget.cpp.
References buttonClicked(), MusicPageQueryWidget::createPageWidget(), currentArtistListClicked(), MusicUtils::Widget::generateVScrollAreaFormat(), LINE_SPACING_SIZE, m_categoryButton, m_categoryChanged, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_statusLabel, MusicClickedGroup::mapped(), MusicUIObject::MQSSColorStyle06, MusicUIObject::MQSSColorStyle08, MusicUIObject::MQSSColorStyle10, numberButtonClicked(), MusicPageQueryRequest::pageSize(), MusicAbstractQueryRequest::queryServer(), MusicPageQueryWidget::reset(), MusicArtistListQueryCategoryPopWidget::setCategory(), MusicArtistListQueryItemWidget::setMusicResultsItem(), MusicPageQueryRequest::totalSize(), and TTKStatic_cast.
Referenced by MusicArtistListQueryWidget().
void MusicArtistListQueryWidget::currentArtistListClicked (const MusicResultsItem & item) slot
Current artist list clicked.
Definition at line 182 of file musicartistlistquerywidget.cpp.
References MusicRightAreaWidget::instance(), MusicResultsItem::m_id, and MusicRightAreaWidget::musicArtistSearch().
Referenced by createArtistListItem().
void MusicArtistListQueryWidget::numberButtonClicked (int index) slot
Number type button has changed.
Definition at line 215 of file musicartistlistquerywidget.cpp.
References m_categoryChanged, m_categoryId, m_gridLayout, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractQueryRequest::OtherQuery, MusicAbstractQueryRequest::startToSearch(), and TTK_SPLITER.
Referenced by categoryChanged(), and createArtistListItem().
void MusicArtistListQueryWidget::resizeWindow () final override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 76 of file musicartistlistquerywidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and MusicAbstractItemQueryWidget::m_resizeWidgets.
void MusicArtistListQueryWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 65 of file musicartistlistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractQueryRequest::OtherQuery, MusicAbstractItemQueryWidget::setSongName(), and MusicAbstractQueryRequest::startToSearch().
Referenced by setSongNameById().
void MusicArtistListQueryWidget::setSongNameById (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 71 of file musicartistlistquerywidget.cpp.
References setSongName().
Member Data Documentation
MusicArtistListQueryCategoryPopWidget* MusicArtistListQueryWidget::m_categoryButton protected
Definition at line 122 of file musicartistlistquerywidget.h.
Referenced by categoryChanged(), createArtistListItem(), MusicArtistListQueryWidget(), and ~MusicArtistListQueryWidget().
bool MusicArtistListQueryWidget::m_categoryChanged protected
Definition at line 118 of file musicartistlistquerywidget.h.
Referenced by createArtistListItem(), MusicArtistListQueryWidget(), and numberButtonClicked().
QString MusicArtistListQueryWidget::m_categoryId protected
Definition at line 119 of file musicartistlistquerywidget.h.
Referenced by categoryChanged(), and numberButtonClicked().
QGridLayout* MusicArtistListQueryWidget::m_gridLayout protected
Definition at line 120 of file musicartistlistquerywidget.h.
Referenced by buttonClicked(), createArtistListItem(), MusicArtistListQueryWidget(), numberButtonClicked(), resizeWindow(), and ~MusicArtistListQueryWidget().
bool MusicArtistListQueryWidget::m_initialized protected
Definition at line 118 of file musicartistlistquerywidget.h.
Referenced by createArtistListItem(), and MusicArtistListQueryWidget().
MusicPageQueryWidget* MusicArtistListQueryWidget::m_pageQueryWidget protected
Definition at line 121 of file musicartistlistquerywidget.h.
Referenced by buttonClicked(), createArtistListItem(), MusicArtistListQueryWidget(), and ~MusicArtistListQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerywidget.cpp