TTKMusicPlayer: QGlobalShortcut Class Reference
QGlobalShortcut Class Reference
The class of the qglobal shortcut.
#include <qglobalshortcut.h>
Public Slots
void setEnabled (bool enabled=true)
void setDisabled (bool disabled=true)
Signals
void activated ()
Public Member Functions
QGlobalShortcut (QObject *parent=nullptr)
QGlobalShortcut (const QKeySequence &shortcut, QObject *parent=nullptr)
~QGlobalShortcut ()
QKeySequence shortcut () const
bool setShortcut (const QKeySequence &shortcut)
void unsetShortcut ()
bool isEnabled () const
Properties
bool enabled
QKeySequence shortcut
Detailed Description
The class of the qglobal shortcut.
Author
libqxt found.nosp@m.atio.nosp@m.n@lib.nosp@m.qxt..nosp@m.org
Definition at line 31 of file qglobalshortcut.h.
Constructor & Destructor Documentation
QGlobalShortcut::QGlobalShortcut (QObject * parent = nullptr) explicit
Definition at line 101 of file qglobalshortcut.cpp.
References TTK_INIT_PRIVATE.
QGlobalShortcut::QGlobalShortcut (const QKeySequence & shortcut, QObject * parent = nullptr) explicit
Definition at line 107 of file qglobalshortcut.cpp.
References setShortcut().
QGlobalShortcut::~QGlobalShortcut ()
Definition at line 113 of file qglobalshortcut.cpp.
References unsetShortcut().
Member Function Documentation
void QGlobalShortcut::activated () signal
Referenced by QGlobalShortcutPrivate::activateShortcut().
bool QGlobalShortcut::isEnabled () const
Definition at line 140 of file qglobalshortcut.cpp.
References TTK_D.
Referenced by QGlobalShortcutPrivate::activateShortcut().
void QGlobalShortcut::setDisabled (bool disabled = true) slot
Definition at line 152 of file qglobalshortcut.cpp.
References TTK_D.
void QGlobalShortcut::setEnabled (bool enabled = true) slot
Definition at line 146 of file qglobalshortcut.cpp.
References enabled, and TTK_D.
bool QGlobalShortcut::setShortcut (const QKeySequence & shortcut)
Definition at line 124 of file qglobalshortcut.cpp.
References TTK_D, and unsetShortcut().
Referenced by QGlobalShortcut().
QKeySequence QGlobalShortcut::shortcut () const
void QGlobalShortcut::unsetShortcut ()
Definition at line 131 of file qglobalshortcut.cpp.
References TTK_D.
Referenced by setShortcut(), and ~QGlobalShortcut().
Property Documentation
bool QGlobalShortcut::enabled read write
Definition at line 34 of file qglobalshortcut.h.
Referenced by setEnabled().
QKeySequence QGlobalShortcut::shortcut read write
Definition at line 35 of file qglobalshortcut.h.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut.h
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut.cpp