TTKMusicplayer: MusicLrcArtPhotoUploadWidget Class Reference
MusicLrcArtPhotoUploadWidget Class Reference
The class of the lrc art photo upload.
#include <musiclrcartphotouploadwidget.h>
Public Slots
void deltaValueChanged (float v)
void selectButtonClicked ()
void uploadButtonClicked ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicLrcArtPhotoUploadWidget (QWidget *parent=nullptr)
~MusicLrcArtPhotoUploadWidget ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicLrcArtPhotoUploadWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the lrc art photo upload.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrcartphotouploadwidget.h.
Constructor & Destructor Documentation
MusicLrcArtPhotoUploadWidget::MusicLrcArtPhotoUploadWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musiclrcartphotouploadwidget.cpp.
References deltaValueChanged(), m_ui, MusicUIObject::MQSSBackgroundStyle05, MusicUIObject::MQSSColorStyle07, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, selectButtonClicked(), and uploadButtonClicked().
MusicLrcArtPhotoUploadWidget::~MusicLrcArtPhotoUploadWidget ()
Definition at line 46 of file musiclrcartphotouploadwidget.cpp.
References m_ui.
Member Function Documentation
void MusicLrcArtPhotoUploadWidget::deltaValueChanged (float v) slot
Delta value changed.
Definition at line 51 of file musiclrcartphotouploadwidget.cpp.
References m_ui, and TTKStatic_cast.
Referenced by MusicLrcArtPhotoUploadWidget().
int MusicLrcArtPhotoUploadWidget::exec () virtual slot
Override exec function.
Definition at line 107 of file musiclrcartphotouploadwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicLrcContainerForInterior::showArtistBackgroundUploadedWidget().
void MusicLrcArtPhotoUploadWidget::selectButtonClicked () slot
Select button clicked.
Definition at line 56 of file musiclrcartphotouploadwidget.cpp.
References m_ui, MusicUtils::File::openFileDialog(), WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by MusicLrcArtPhotoUploadWidget().
void MusicLrcArtPhotoUploadWidget::uploadButtonClicked () slot
Upload button clicked.
Definition at line 82 of file musiclrcartphotouploadwidget.cpp.
References BACKGROUND_DIR_FULL, JPG_FILE, m_ui, name, MusicToastLabel::popup(), and SKN_FILE.
Referenced by MusicLrcArtPhotoUploadWidget().
Member Data Documentation
Ui::MusicLrcArtPhotoUploadWidget* MusicLrcArtPhotoUploadWidget::m_ui protected
Definition at line 61 of file musiclrcartphotouploadwidget.h.
Referenced by deltaValueChanged(), exec(), MusicLrcArtPhotoUploadWidget(), selectButtonClicked(), uploadButtonClicked(), and ~MusicLrcArtPhotoUploadWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcartphotouploadwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcartphotouploadwidget.cpp