TTKMusicPlayer: TTKThirdParty/Zlib/zlib/zlib.h File Reference
zlib.h File Reference
#include "zconf.h"
Classes
struct z_stream_s
struct gz_header_s
struct gzFile_s
Macros
#define ZLIB_VERSION "1.3.1"
#define ZLIB_VERNUM 0x1310
#define ZLIB_VER_MAJOR 1
#define ZLIB_VER_MINOR 3
#define ZLIB_VER_REVISION 1
#define ZLIB_VER_SUBREVISION 0
#define Z_NO_FLUSH 0
#define Z_PARTIAL_FLUSH 1
#define Z_SYNC_FLUSH 2
#define Z_FULL_FLUSH 3
#define Z_FINISH 4
#define Z_BLOCK 5
#define Z_TREES 6
#define Z_OK 0
#define Z_STREAM_END 1
#define Z_NEED_DICT 2
#define Z_ERRNO (-1)
#define Z_STREAM_ERROR (-2)
#define Z_DATA_ERROR (-3)
#define Z_MEM_ERROR (-4)
#define Z_BUF_ERROR (-5)
#define Z_VERSION_ERROR (-6)
#define Z_NO_COMPRESSION 0
#define Z_BEST_SPEED 1
#define Z_BEST_COMPRESSION 9
#define Z_DEFAULT_COMPRESSION (-1)
#define Z_FILTERED 1
#define Z_HUFFMAN_ONLY 2
#define Z_RLE 3
#define Z_FIXED 4
#define Z_DEFAULT_STRATEGY 0
#define Z_BINARY 0
#define Z_TEXT 1
#define Z_ASCII Z_TEXT /* for compatibility with 1.2.2 and earlier */
#define Z_UNKNOWN 2
#define Z_DEFLATED 8
#define Z_NULL 0 /* for initializing zalloc, zfree, opaque */
#define zlib_version zlibVersion()
#define deflateInit(strm, level) deflateInit_((strm), (level), ZLIB_VERSION, (int)sizeof(z_stream))
#define inflateInit(strm) inflateInit_((strm), ZLIB_VERSION, (int)sizeof(z_stream))
#define deflateInit2(strm, level, method, windowBits, memLevel, strategy)
#define inflateInit2(strm, windowBits)
#define inflateBackInit(strm, windowBits, window)
#define gzgetc(g) ((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : (gzgetc)(g))
Typedefs
typedef voidpf(* alloc_func) (voidpf opaque, uInt items, uInt size)
typedef void(* free_func) (voidpf opaque, voidpf address)
typedef struct z_stream_s z_stream
typedef z_stream FAR * z_streamp
typedef struct gz_header_s gz_header
typedef gz_header FAR * gz_headerp
typedef unsigned(* in_func) (void FAR *, z_const unsigned char FAR *FAR *)
typedef int(* out_func) (void FAR *, unsigned char FAR *, unsigned)
typedef struct gzFile_s * gzFile
Functions
ZEXTERN const char *ZEXPORT zlibVersion (void)
ZEXTERN int ZEXPORT deflate (z_streamp strm, int flush)
ZEXTERN int ZEXPORT deflateEnd (z_streamp strm)
ZEXTERN int ZEXPORT inflate (z_streamp strm, int flush)
ZEXTERN int ZEXPORT inflateEnd (z_streamp strm)
ZEXTERN int ZEXPORT deflateSetDictionary (z_streamp strm, const Bytef *dictionary, uInt dictLength)
ZEXTERN int ZEXPORT deflateGetDictionary (z_streamp strm, Bytef *dictionary, uInt *dictLength)
ZEXTERN int ZEXPORT deflateCopy (z_streamp dest, z_streamp source)
ZEXTERN int ZEXPORT deflateReset (z_streamp strm)
ZEXTERN int ZEXPORT deflateParams (z_streamp strm, int level, int strategy)
ZEXTERN int ZEXPORT deflateTune (z_streamp strm, int good_length, int max_lazy, int nice_length, int max_chain)
ZEXTERN uLong ZEXPORT deflateBound (z_streamp strm, uLong sourceLen)
ZEXTERN int ZEXPORT deflatePending (z_streamp strm, unsigned *pending, int *bits)
ZEXTERN int ZEXPORT deflatePrime (z_streamp strm, int bits, int value)
ZEXTERN int ZEXPORT deflateSetHeader (z_streamp strm, gz_headerp head)
ZEXTERN int ZEXPORT inflateSetDictionary (z_streamp strm, const Bytef *dictionary, uInt dictLength)
ZEXTERN int ZEXPORT inflateGetDictionary (z_streamp strm, Bytef *dictionary, uInt *dictLength)
ZEXTERN int ZEXPORT inflateSync (z_streamp strm)
ZEXTERN int ZEXPORT inflateCopy (z_streamp dest, z_streamp source)
ZEXTERN int ZEXPORT inflateReset (z_streamp strm)
ZEXTERN int ZEXPORT inflateReset2 (z_streamp strm, int windowBits)
ZEXTERN int ZEXPORT inflatePrime (z_streamp strm, int bits, int value)
ZEXTERN long ZEXPORT inflateMark (z_streamp strm)
ZEXTERN int ZEXPORT inflateGetHeader (z_streamp strm, gz_headerp head)
ZEXTERN int ZEXPORT inflateBack (z_streamp strm, in_func in, void FAR *in_desc, out_func out, void FAR *out_desc)
ZEXTERN int ZEXPORT inflateBackEnd (z_streamp strm)
ZEXTERN uLong ZEXPORT zlibCompileFlags (void)
ZEXTERN int ZEXPORT compress (Bytef *dest, uLongf *destLen, const Bytef *source, uLong sourceLen)
ZEXTERN int ZEXPORT compress2 (Bytef *dest, uLongf *destLen, const Bytef *source, uLong sourceLen, int level)
ZEXTERN uLong ZEXPORT compressBound (uLong sourceLen)
ZEXTERN int ZEXPORT uncompress (Bytef *dest, uLongf *destLen, const Bytef *source, uLong sourceLen)
ZEXTERN int ZEXPORT uncompress2 (Bytef *dest, uLongf *destLen, const Bytef *source, uLong *sourceLen)
ZEXTERN gzFile ZEXPORT gzdopen (int fd, const char *mode)
ZEXTERN int ZEXPORT gzbuffer (gzFile file, unsigned size)
ZEXTERN int ZEXPORT gzsetparams (gzFile file, int level, int strategy)
ZEXTERN int ZEXPORT gzread (gzFile file, voidp buf, unsigned len)
ZEXTERN z_size_t ZEXPORT gzfread (voidp buf, z_size_t size, z_size_t nitems, gzFile file)
ZEXTERN int ZEXPORT gzwrite (gzFile file, voidpc buf, unsigned len)
ZEXTERN z_size_t ZEXPORT gzfwrite (voidpc buf, z_size_t size, z_size_t nitems, gzFile file)
ZEXTERN int ZEXPORTVA gzprintf (gzFile file, const char *format,...)
ZEXTERN int ZEXPORT gzputs (gzFile file, const char *s)
ZEXTERN char *ZEXPORT gzgets (gzFile file, char *buf, int len)
ZEXTERN int ZEXPORT gzputc (gzFile file, int c)
ZEXTERN int ZEXPORT gzgetc (gzFile file)
ZEXTERN int ZEXPORT gzungetc (int c, gzFile file)
ZEXTERN int ZEXPORT gzflush (gzFile file, int flush)
ZEXTERN int ZEXPORT gzrewind (gzFile file)
ZEXTERN int ZEXPORT gzeof (gzFile file)
ZEXTERN int ZEXPORT gzdirect (gzFile file)
ZEXTERN int ZEXPORT gzclose (gzFile file)
ZEXTERN int ZEXPORT gzclose_r (gzFile file)
ZEXTERN int ZEXPORT gzclose_w (gzFile file)
ZEXTERN const char *ZEXPORT gzerror (gzFile file, int *errnum)
ZEXTERN void ZEXPORT gzclearerr (gzFile file)
ZEXTERN uLong ZEXPORT adler32 (uLong adler, const Bytef *buf, uInt len)
ZEXTERN uLong ZEXPORT adler32_z (uLong adler, const Bytef *buf, z_size_t len)
ZEXTERN uLong ZEXPORT crc32 (uLong crc, const Bytef *buf, uInt len)
ZEXTERN uLong ZEXPORT crc32_z (uLong crc, const Bytef *buf, z_size_t len)
ZEXTERN uLong ZEXPORT crc32_combine_op (uLong crc1, uLong crc2, uLong op)
ZEXTERN int ZEXPORT deflateInit_ (z_streamp strm, int level, const char *version, int stream_size)
ZEXTERN int ZEXPORT inflateInit_ (z_streamp strm, const char *version, int stream_size)
ZEXTERN int ZEXPORT deflateInit2_ (z_streamp strm, int level, int method, int windowBits, int memLevel, int strategy, const char *version, int stream_size)
ZEXTERN int ZEXPORT inflateInit2_ (z_streamp strm, int windowBits, const char *version, int stream_size)
ZEXTERN int ZEXPORT inflateBackInit_ (z_streamp strm, int windowBits, unsigned char FAR *window, const char *version, int stream_size)
ZEXTERN int ZEXPORT gzgetc_ (gzFile file)
ZEXTERN gzFile ZEXPORT gzopen (const char *, const char *)
ZEXTERN z_off_t ZEXPORT gzseek (gzFile, z_off_t, int)
ZEXTERN z_off_t ZEXPORT gztell (gzFile)
ZEXTERN z_off_t ZEXPORT gzoffset (gzFile)
ZEXTERN uLong ZEXPORT adler32_combine (uLong, uLong, z_off_t)
ZEXTERN uLong ZEXPORT crc32_combine (uLong, uLong, z_off_t)
ZEXTERN uLong ZEXPORT crc32_combine_gen (z_off_t)
ZEXTERN const char *ZEXPORT zError (int)
ZEXTERN int ZEXPORT inflateSyncPoint (z_streamp)
ZEXTERN const z_crc_t FAR *ZEXPORT get_crc_table (void)
ZEXTERN int ZEXPORT inflateUndermine (z_streamp, int)
ZEXTERN int ZEXPORT inflateValidate (z_streamp, int)
ZEXTERN unsigned long ZEXPORT inflateCodesUsed (z_streamp)
ZEXTERN int ZEXPORT inflateResetKeep (z_streamp)
ZEXTERN int ZEXPORT deflateResetKeep (z_streamp)
Macro Definition Documentation
#define deflateInit (strm, level) deflateInit_((strm), (level), ZLIB_VERSION, (int)sizeof(z_stream))
Definition at line 1813 of file zlib.h.
Referenced by compress2().
#define deflateInit2 (strm, level, method, windowBits, memLevel, strategy)
Value:
deflateInit2_((strm),(level),(method),(windowBits),(memLevel),\
                        (strategy), ZLIB_VERSION, (int)sizeof(z_stream))
Definition at line 1817 of file zlib.h.
Referenced by gz_init(), and zipOpenNewFileInZip4_64().
#define gzgetc (g) ((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : (gzgetc)(g))
Definition at line 1848 of file zlib.h.
#define inflateBackInit (strm, windowBits, window)
Value:
inflateBackInit_((strm), (windowBits), (window), \
                           ZLIB_VERSION, (int)sizeof(z_stream))
Definition at line 1823 of file zlib.h.
#define inflateInit (strm) inflateInit_((strm), ZLIB_VERSION, (int)sizeof(z_stream))
Definition at line 1815 of file zlib.h.
Referenced by uncompress2().
#define inflateInit2 (strm, windowBits)
Value:
inflateInit2_((strm), (windowBits), ZLIB_VERSION, \
                        (int)sizeof(z_stream))
Definition at line 1820 of file zlib.h.
Referenced by gz_look(), and unzOpenCurrentFile3().
#define Z_ASCII Z_TEXT /* for compatibility with 1.2.2 and earlier */
Definition at line 205 of file zlib.h.
Referenced by zipCloseFileInZipRaw64().
#define Z_BEST_COMPRESSION 9
Definition at line 192 of file zlib.h.
#define Z_BEST_SPEED 1
Definition at line 191 of file zlib.h.
#define Z_BINARY 0
Definition at line 203 of file zlib.h.
Referenced by detect_data_type(), and zipOpenNewFileInZip4_64().
#define Z_BLOCK 5
Definition at line 173 of file zlib.h.
Referenced by deflate(), deflateParams(), gzsetparams(), and inflate().
#define Z_BUF_ERROR (-5)
Definition at line 184 of file zlib.h.
Referenced by deflate(), deflateParams(), deflatePrime(), gz_avail(), gz_decomp(), gz_error(), gzclose_r(), gzfread(), gzgetc(), gzgets(), gzread(), gzrewind(), gzseek64(), gzungetc(), inflate(), inflateBack(), inflateSync(), and uncompress2().
#define Z_DATA_ERROR (-3)
Definition at line 182 of file zlib.h.
Referenced by deflateEnd(), gz_decomp(), gzungetc(), gzwrite(), inflate(), inflateBack(), inflateSetDictionary(), inflateSync(), inflateUndermine(), uncompress2(), and unzReadCurrentFile().
#define Z_DEFAULT_COMPRESSION (-1)
Definition at line 193 of file zlib.h.
Referenced by compress(), deflateInit2_(), deflateParams(), and gz_open().
#define Z_DEFAULT_STRATEGY 0
Definition at line 200 of file zlib.h.
Referenced by deflateInit_(), gz_open(), zipOpenNewFileInZip(), zipOpenNewFileInZip2(), zipOpenNewFileInZip2_64(), and zipOpenNewFileInZip64().
#define Z_DEFLATED 8
Definition at line 209 of file zlib.h.
Referenced by deflate(), deflateInit2_(), deflateInit_(), gz_init(), inflate(), MusicExtractWrapper::inputData(), MusicExtractWrapper::inputSkin(), unz64local_CheckCurrentFileCoherencyHeader(), unzCloseCurrentFile(), unzOpenCurrentFile3(), zipCloseFileInZipRaw64(), zipOpenNewFileInZip4_64(), and zipWriteInFileInZip().
#define Z_ERRNO (-1)
Definition at line 180 of file zlib.h.
Referenced by gz_comp(), gz_load(), gzclose_r(), gzclose_w(), and unzRepair().
#define Z_FILTERED 1
Definition at line 196 of file zlib.h.
Referenced by deflate_slow(), and gz_open().
#define Z_FINISH 4
Definition at line 172 of file zlib.h.
Referenced by compress2(), deflate(), deflate_fast(), deflate_huff(), deflate_rle(), deflate_slow(), deflate_stored(), gz_comp(), gzclose_w(), gzflush(), inflate(), and zipCloseFileInZipRaw64().
#define Z_FIXED 4
Definition at line 199 of file zlib.h.
Referenced by _tr_flush_block(), deflateInit2_(), deflateParams(), and gz_open().
#define Z_FULL_FLUSH 3
Definition at line 171 of file zlib.h.
Referenced by deflate().
#define Z_HUFFMAN_ONLY 2
Definition at line 197 of file zlib.h.
Referenced by deflate(), and gz_open().
#define Z_MEM_ERROR (-4)
Definition at line 183 of file zlib.h.
Referenced by deflateCopy(), deflateInit2_(), gz_decomp(), gz_error(), gz_init(), gz_look(), gzerror(), inflate(), inflateBackInit_(), inflateCopy(), inflateInit2_(), inflateSetDictionary(), and unzRepair().
#define Z_NEED_DICT 2
Definition at line 179 of file zlib.h.
Referenced by gz_decomp(), inflate(), and uncompress2().
#define Z_NO_COMPRESSION 0
Definition at line 190 of file zlib.h.
#define Z_NO_FLUSH 0
Definition at line 168 of file zlib.h.
Referenced by compress2(), deflate(), deflate_fast(), deflate_huff(), deflate_rle(), deflate_slow(), deflate_stored(), gz_comp(), gz_decomp(), gz_write(), gz_zero(), gzprintf(), uncompress2(), and zipWriteInFileInZip().
#define Z_NULL 0 /* for initializing zalloc, zfree, opaque */
Definition at line 212 of file zlib.h.
Referenced by adler32_z(), crc32_z(), deflate(), deflateBound(), deflateCopy(), deflateEnd(), deflateGetDictionary(), deflateInit2_(), deflatePending(), deflateResetKeep(), deflateSetDictionary(), deflateStateCheck(), gz_init(), gz_look(), inflate(), inflateBack(), inflateBackEnd(), inflateBackInit_(), inflateCopy(), inflateEnd(), inflateGetDictionary(), inflateInit2_(), inflateReset2(), inflateResetKeep(), inflateSetDictionary(), inflateStateCheck(), and updatewindow().
#define Z_OK 0
Definition at line 177 of file zlib.h.
Referenced by compress2(), MusicLrcFromKrc::decompression(), deflate(), deflateCopy(), deflateEnd(), deflateGetDictionary(), deflateParams(), deflatePending(), deflatePrime(), deflateReset(), deflateResetKeep(), deflateSetDictionary(), deflateSetHeader(), deflateTune(), gz_avail(), gz_comp(), gz_decomp(), gz_error(), gz_init(), gz_look(), gz_reset(), gzclearerr(), gzclose_r(), gzclose_w(), gzflush(), gzfread(), gzfwrite(), gzgetc(), gzgets(), gzprintf(), gzputc(), gzputs(), gzread(), gzrewind(), gzseek64(), gzsetparams(), gzungetc(), gzwrite(), inflate(), inflateBackEnd(), inflateBackInit_(), inflateCopy(), inflateEnd(), inflateGetDictionary(), inflateGetHeader(), inflateInit2_(), inflatePrime(), inflateResetKeep(), inflateSetDictionary(), inflateSync(), inflateUndermine(), inflateValidate(), uncompress2(), unzOpenCurrentFile3(), unzReadCurrentFile(), unzRepair(), and zipOpenNewFileInZip4_64().
#define Z_PARTIAL_FLUSH 1
Definition at line 169 of file zlib.h.
Referenced by deflate().
#define Z_RLE 3
Definition at line 198 of file zlib.h.
Referenced by deflate(), and gz_open().
#define Z_STREAM_END 1
Definition at line 178 of file zlib.h.
Referenced by compress2(), deflate(), gz_comp(), gz_decomp(), inflate(), inflateBack(), uncompress2(), unzReadCurrentFile(), and zipCloseFileInZipRaw64().
#define Z_STREAM_ERROR (-2)
Definition at line 181 of file zlib.h.
Referenced by deflate(), deflateCopy(), deflateEnd(), deflateGetDictionary(), deflateInit2_(), deflateParams(), deflatePending(), deflatePrime(), deflateResetKeep(), deflateSetDictionary(), deflateSetHeader(), deflateTune(), gz_comp(), gz_decomp(), gzclose(), gzclose_r(), gzclose_w(), gzflush(), gzfread(), gzfwrite(), gzprintf(), gzputs(), gzread(), gzsetparams(), inflate(), inflateBack(), inflateBackEnd(), inflateBackInit_(), inflateCopy(), inflateEnd(), inflateGetDictionary(), inflateGetHeader(), inflateInit2_(), inflatePrime(), inflateReset(), inflateReset2(), inflateResetKeep(), inflateSetDictionary(), inflateSync(), inflateSyncPoint(), inflateUndermine(), inflateValidate(), and unzRepair().
#define Z_SYNC_FLUSH 2
Definition at line 170 of file zlib.h.
Referenced by unzReadCurrentFile().
#define Z_TEXT 1
Definition at line 204 of file zlib.h.
Referenced by detect_data_type().
#define Z_TREES 6
Definition at line 174 of file zlib.h.
Referenced by inflate().
#define Z_UNKNOWN 2
Definition at line 206 of file zlib.h.
Referenced by _tr_flush_block(), and deflateResetKeep().
#define Z_VERSION_ERROR (-6)
Definition at line 185 of file zlib.h.
Referenced by deflateInit2_(), inflateBackInit_(), and inflateInit2_().
#define ZLIB_VER_MAJOR 1
Definition at line 42 of file zlib.h.
#define ZLIB_VER_MINOR 3
Definition at line 43 of file zlib.h.
#define ZLIB_VER_REVISION 1
Definition at line 44 of file zlib.h.
#define ZLIB_VER_SUBREVISION 0
Definition at line 45 of file zlib.h.
#define ZLIB_VERNUM 0x1310
Definition at line 41 of file zlib.h.
#define ZLIB_VERSION "1.3.1"
Definition at line 40 of file zlib.h.
Referenced by deflateInit2_(), inflateBackInit_(), inflateInit2_(), and zlibVersion().
#define zlib_version zlibVersion()
Definition at line 214 of file zlib.h.
Typedef Documentation
typedef voidpf(* alloc_func) (voidpf opaque, uInt items, uInt size)
Definition at line 81 of file zlib.h.
typedef void(* free_func) (voidpf opaque, voidpf address)
Definition at line 82 of file zlib.h.
typedef struct gz_header_s gz_header
typedef gz_header FAR* gz_headerp
Definition at line 131 of file zlib.h.
typedef struct gzFile_s* gzFile
Definition at line 1305 of file zlib.h.
typedef unsigned(* in_func) (void FAR *, z_const unsigned char FAR *FAR *)
Definition at line 1097 of file zlib.h.
typedef int(* out_func) (void FAR *, unsigned char FAR *, unsigned)
Definition at line 1099 of file zlib.h.
typedef struct z_stream_s z_stream
typedef z_stream FAR* z_streamp
Definition at line 108 of file zlib.h.
Function Documentation
ZEXTERN uLong ZEXPORT adler32 (uLong adler, const Bytef * buf, uInt len)
Definition at line 128 of file adler32.c.
References adler32_z().
Referenced by deflate(), deflateResetKeep(), deflateSetDictionary(), inflate(), inflateSetDictionary(), and read_buf().
ZEXTERN uLong ZEXPORT adler32_combine (uLong , uLong , z_off_t)
Definition at line 158 of file adler32.c.
References adler32_combine_().
ZEXTERN uLong ZEXPORT adler32_z (uLong adler, const Bytef * buf, z_size_t len)
Definition at line 61 of file adler32.c.
References BASE, DO16, MOD, MOD28, NMAX, and Z_NULL.
Referenced by adler32().
ZEXTERN int ZEXPORT compress (Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen)
Definition at line 63 of file compress.c.
References compress2(), and Z_DEFAULT_COMPRESSION.
ZEXTERN int ZEXPORT compress2 (Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen, int level)
Definition at line 22 of file compress.c.
References z_stream_s::avail_in, z_stream_s::avail_out, deflate(), deflateEnd(), deflateInit, TTK::max(), z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, z_stream_s::total_out, z_const, Z_FINISH, Z_NO_FLUSH, Z_OK, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by compress().
ZEXTERN uLong ZEXPORT compressBound (uLong sourceLen)
Definition at line 72 of file compress.c.
ZEXTERN uLong ZEXPORT crc32 (uLong crc, const Bytef * buf, uInt len)
ZEXTERN uLong ZEXPORT crc32_combine (uLong , uLong , z_off_t)
Definition at line 1029 of file crc32.c.
References crc32_combine64(), and z_off64_t.
ZEXTERN uLong ZEXPORT crc32_combine_gen (z_off_t)
Definition at line 1042 of file crc32.c.
References crc32_combine_gen64(), and z_off64_t.
ZEXTERN uLong ZEXPORT crc32_combine_op (uLong crc1, uLong crc2, uLong op)
Definition at line 1047 of file crc32.c.
References multmodp().
ZEXTERN uLong ZEXPORT crc32_z (uLong crc, const Bytef * buf, z_size_t len)
ZEXTERN int ZEXPORT deflate (z_streamp strm, int flush)
Definition at line 946 of file deflate.c.
References _tr_align(), _tr_stored_block(), adler32(), block_done, internal_state::block_start, BUSY_STATE, CLEAR_HASH, COMMENT_STATE, configuration_table, crc32(), deflate_huff(), deflate_rle(), deflate_stored(), deflateStateCheck(), ERR_RETURN, EXTRA_STATE, finish_done, finish_started, FINISH_STATE, flush_pending(), config_s::func, internal_state::gzhead, internal_state::gzindex, GZIP_STATE, HCRC_STATE, HCRC_UPDATE, INIT_STATE, internal_state::insert, internal_state::last_flush, internal_state::level, internal_state::lookahead, NAME_STATE, need_more, OS_CODE, internal_state::pending, internal_state::pending_buf, internal_state::pending_buf_size, PRESET_DICT, put_byte, putShortMSB(), RANK, internal_state::status, internal_state::strategy, internal_state::strstart, internal_state::w_bits, internal_state::wrap, Z_BLOCK, Z_BUF_ERROR, Z_DEFLATED, Z_FINISH, Z_FULL_FLUSH, Z_HUFFMAN_ONLY, Z_NO_FLUSH, Z_NULL, Z_OK, Z_PARTIAL_FLUSH, Z_RLE, Z_STREAM_END, Z_STREAM_ERROR, and zmemcpy().
Referenced by compress2(), deflateParams(), gz_comp(), zipCloseFileInZipRaw64(), and zipWriteInFileInZip().
ZEXTERN uLong ZEXPORT deflateBound (z_streamp strm, uLong sourceLen)
Definition at line 834 of file deflate.c.
References deflateStateCheck(), internal_state::gzhead, internal_state::hash_bits, internal_state::level, internal_state::strstart, internal_state::w_bits, internal_state::wrap, and Z_NULL.
ZEXTERN int ZEXPORT deflateCopy (z_streamp dest, z_streamp source)
Definition at line 1282 of file deflate.c.
References deflateEnd(), deflateStateCheck(), LIT_BUFS, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, ZALLOC, and zmemcpy().
ZEXTERN int ZEXPORT deflateEnd (z_streamp strm)
Definition at line 1258 of file deflate.c.
References BUSY_STATE, deflateStateCheck(), internal_state::status, TRY_FREE, Z_DATA_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, and ZFREE.
Referenced by compress2(), deflateCopy(), deflateInit2_(), gzclose_w(), and zipCloseFileInZipRaw64().
ZEXTERN int ZEXPORT deflateGetDictionary (z_streamp strm, Bytef * dictionary, uInt * dictLength)
Definition at line 616 of file deflate.c.
References deflateStateCheck(), internal_state::lookahead, internal_state::strstart, internal_state::w_size, internal_state::window, Z_NULL, Z_OK, Z_STREAM_ERROR, and zmemcpy().
ZEXTERN int ZEXPORT deflateInit2_ (z_streamp strm, int level, int method, int windowBits, int memLevel, int strategy, const char * version, int stream_size)
Definition at line 379 of file deflate.c.
References deflateEnd(), deflateReset(), ERR_MSG, FINISH_STATE, internal_state::gzhead, internal_state::hash_bits, internal_state::hash_mask, internal_state::hash_shift, internal_state::hash_size, internal_state::head, internal_state::high_water, INIT_STATE, internal_state::level, LIT_BUFS, internal_state::lit_bufsize, MAX_MEM_LEVEL, internal_state::method, MIN_MATCH, internal_state::pending_buf, internal_state::pending_buf_size, internal_state::prev, internal_state::status, internal_state::strategy, internal_state::strm, internal_state::sym_buf, internal_state::sym_end, internal_state::w_bits, internal_state::w_mask, internal_state::w_size, internal_state::window, internal_state::wrap, Z_DEFAULT_COMPRESSION, Z_DEFLATED, Z_FIXED, Z_MEM_ERROR, Z_NULL, Z_STREAM_ERROR, Z_VERSION_ERROR, ZALLOC, zcalloc(), zcfree(), and ZLIB_VERSION.
Referenced by deflateInit_().
ZEXTERN int ZEXPORT deflateInit_ (z_streamp strm, int level, const char * version, int stream_size)
Definition at line 371 of file deflate.c.
References DEF_MEM_LEVEL, deflateInit2_(), MAX_WBITS, Z_DEFAULT_STRATEGY, and Z_DEFLATED.
ZEXTERN int ZEXPORT deflateParams (z_streamp strm, int level, int strategy)
Definition at line 752 of file deflate.c.
References internal_state::block_start, CLEAR_HASH, configuration_table, deflate(), deflateStateCheck(), config_s::func, config_s::good_length, internal_state::good_match, internal_state::last_flush, internal_state::level, internal_state::lookahead, internal_state::matches, config_s::max_chain, internal_state::max_chain_length, config_s::max_lazy, internal_state::max_lazy_match, config_s::nice_length, internal_state::nice_match, slide_hash(), internal_state::strategy, internal_state::strstart, Z_BLOCK, Z_BUF_ERROR, Z_DEFAULT_COMPRESSION, Z_FIXED, Z_OK, and Z_STREAM_ERROR.
Referenced by gzsetparams().
ZEXTERN int ZEXPORT deflatePending (z_streamp strm, unsigned * pending, int * bits)
Definition at line 713 of file deflate.c.
References deflateStateCheck(), Z_NULL, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT deflatePrime (z_streamp strm, int bits, int value)
Definition at line 723 of file deflate.c.
References _tr_flush_bits(), internal_state::bi_buf, internal_state::bi_valid, Buf_size, deflateStateCheck(), internal_state::pending_out, internal_state::sym_buf, Z_BUF_ERROR, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT deflateReset (z_streamp strm)
Definition at line 695 of file deflate.c.
References deflateResetKeep(), lm_init(), and Z_OK.
Referenced by deflateInit2_(), and gz_comp().
ZEXTERN int ZEXPORT deflateResetKeep (z_streamp)
Definition at line 635 of file deflate.c.
References _tr_init(), adler32(), crc32(), deflateStateCheck(), GZIP_STATE, INIT_STATE, internal_state::last_flush, internal_state::pending, internal_state::pending_buf, internal_state::pending_out, internal_state::status, internal_state::wrap, Z_NULL, Z_OK, Z_STREAM_ERROR, and Z_UNKNOWN.
Referenced by deflateReset().
ZEXTERN int ZEXPORT deflateSetDictionary (z_streamp strm, const Bytef * dictionary, uInt dictLength)
Definition at line 550 of file deflate.c.
References adler32(), internal_state::block_start, CLEAR_HASH, deflateStateCheck(), fill_window(), internal_state::head, INIT_STATE, internal_state::ins_h, internal_state::insert, long(), internal_state::lookahead, internal_state::match_available, internal_state::match_length, MIN_MATCH, internal_state::prev, internal_state::prev_length, internal_state::status, internal_state::strstart, UPDATE_HASH, internal_state::w_mask, internal_state::w_size, internal_state::window, internal_state::wrap, z_const, Z_NULL, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT deflateSetHeader (z_streamp strm, gz_headerp head)
Definition at line 705 of file deflate.c.
References deflateStateCheck(), internal_state::head, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT deflateTune (z_streamp strm, int good_length, int max_lazy, int nice_length, int max_chain)
Definition at line 797 of file deflate.c.
References deflateStateCheck(), internal_state::good_match, internal_state::max_chain_length, internal_state::max_lazy_match, internal_state::nice_match, Z_OK, and Z_STREAM_ERROR.
ZEXTERN const z_crc_t FAR* ZEXPORT get_crc_table (void)
Definition at line 549 of file crc32.c.
References crc_table, and FAR.
Referenced by unzOpenCurrentFile3(), and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT gzbuffer (gzFile file, unsigned size)
Definition at line 294 of file gzlib.c.
References GZ_READ, and GZ_WRITE.
ZEXTERN void ZEXPORT gzclearerr (gzFile file)
Definition at line 505 of file gzlib.c.
References gz_error(), GZ_READ, GZ_WRITE, and Z_OK.
ZEXTERN int ZEXPORT gzclose (gzFile file)
Definition at line 11 of file gzclose.c.
References GZ_READ, gzclose_r(), gzclose_w(), and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT gzclose_r (gzFile file)
Definition at line 577 of file gzread.c.
References free(), gz_error(), GZ_READ, inflateEnd(), Z_BUF_ERROR, Z_ERRNO, Z_OK, and Z_STREAM_ERROR.
Referenced by gzclose().
ZEXTERN int ZEXPORT gzclose_w (gzFile file)
Definition at line 595 of file gzwrite.c.
References deflateEnd(), free(), gz_comp(), gz_error(), GZ_WRITE, gz_zero(), Z_ERRNO, Z_FINISH, Z_OK, and Z_STREAM_ERROR.
Referenced by gzclose().
ZEXTERN int ZEXPORT gzdirect (gzFile file)
Definition at line 559 of file gzread.c.
References gz_look(), GZ_READ, and LOOK.
ZEXTERN gzFile ZEXPORT gzdopen (int fd, const char * mode)
Definition at line 270 of file gzlib.c.
References free(), gz_open(), and malloc().
ZEXTERN int ZEXPORT gzeof (gzFile file)
Definition at line 472 of file gzlib.c.
References GZ_READ, and GZ_WRITE.
ZEXTERN const char* ZEXPORT gzerror (gzFile file, int * errnum)
Definition at line 487 of file gzlib.c.
References GZ_READ, GZ_WRITE, and Z_MEM_ERROR.
ZEXTERN int ZEXPORT gzflush (gzFile file, int flush)
Definition at line 528 of file gzwrite.c.
References gz_comp(), GZ_WRITE, gz_zero(), Z_FINISH, Z_OK, and Z_STREAM_ERROR.
ZEXTERN z_size_t ZEXPORT gzfread (voidp buf, z_size_t size, z_size_t nitems, gzFile file)
Definition at line 377 of file gzread.c.
References gz_error(), GZ_READ, gz_read(), Z_BUF_ERROR, Z_OK, and Z_STREAM_ERROR.
ZEXTERN z_size_t ZEXPORT gzfwrite (voidpc buf, z_size_t size, z_size_t nitems, gzFile file)
Definition at line 261 of file gzwrite.c.
References gz_error(), GZ_WRITE, gz_write(), Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT gzgetc (gzFile file)
Definition at line 408 of file gzread.c.
References GZ_READ, gz_read(), gzFile_s::have, Z_BUF_ERROR, and Z_OK.
Referenced by gzgetc_().
ZEXTERN int ZEXPORT gzgetc_ (gzFile file)
Definition at line 433 of file gzread.c.
References gzgetc().
ZEXTERN char* ZEXPORT gzgets (gzFile file, char * buf, int len)
Definition at line 499 of file gzread.c.
References gz_fetch(), GZ_READ, gz_skip(), Z_BUF_ERROR, and Z_OK.
ZEXTERN z_off_t ZEXPORT gzoffset (gzFile)
Definition at line 464 of file gzlib.c.
References gzoffset64(), z_off64_t, and z_off_t.
ZEXTERN gzFile ZEXPORT gzopen (const char * , const char *)
Definition at line 260 of file gzlib.c.
References gz_open().
ZEXTERN int ZEXPORTVA gzprintf (gzFile file, const char * format, ...)
ZEXTERN int ZEXPORT gzputc (gzFile file, int c)
Definition at line 287 of file gzwrite.c.
References GZ_WRITE, gz_write(), gz_zero(), gzFile_s::have, gzFile_s::pos, and Z_OK.
ZEXTERN int ZEXPORT gzputs (gzFile file, const char * s)
Definition at line 332 of file gzwrite.c.
References gz_error(), GZ_WRITE, gz_write(), int(), Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT gzread (gzFile file, voidp buf, unsigned len)
Definition at line 345 of file gzread.c.
References gz_error(), GZ_READ, gz_read(), Z_BUF_ERROR, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT gzrewind (gzFile file)
Definition at line 318 of file gzlib.c.
References GZ_READ, gz_reset(), LSEEK, SEEK_SET, Z_BUF_ERROR, and Z_OK.
Referenced by gzseek64().
ZEXTERN z_off_t ZEXPORT gzseek (gzFile , z_off_t , int)
Definition at line 412 of file gzlib.c.
References gzseek64(), z_off64_t, and z_off_t.
ZEXTERN int ZEXPORT gzsetparams (gzFile file, int level, int strategy)
Definition at line 557 of file gzwrite.c.
References deflateParams(), gz_comp(), GZ_WRITE, gz_zero(), Z_BLOCK, Z_OK, and Z_STREAM_ERROR.
ZEXTERN z_off_t ZEXPORT gztell (gzFile)
Definition at line 435 of file gzlib.c.
References gztell64(), z_off64_t, and z_off_t.
ZEXTERN int ZEXPORT gzungetc (int c, gzFile file)
Definition at line 438 of file gzread.c.
References gz_error(), gz_look(), GZ_READ, gz_skip(), LOOK, Z_BUF_ERROR, Z_DATA_ERROR, and Z_OK.
ZEXTERN int ZEXPORT gzwrite (gzFile file, voidpc buf, unsigned len)
Definition at line 237 of file gzwrite.c.
References gz_error(), GZ_WRITE, gz_write(), Z_DATA_ERROR, and Z_OK.
ZEXTERN int ZEXPORT inflate (z_streamp strm, int flush)
Definition at line 590 of file inflate.c.
References adler32(), inflate_state::back, BAD, code::bits, inflate_state::bits, BITS, BYTEBITS, CHECK, inflate_state::check, CODELENS, CODES, inflate_state::codes, COMMENT, COPY, COPY_, CRC2, crc32(), CRC4, DICT, DICTID, DIST, inflate_state::distbits, inflate_state::distcode, DISTEXT, DISTS, inflate_state::dmax, DONE, DROPBITS, EXLEN, EXTRA, inflate_state::extra, fixedtables(), FLAGS, inflate_state::flags, GUNZIP, inflate_state::have, inflate_state::havedict, HCRC, HEAD, inflate_state::head, inflate_state::hold, inflate_fast(), inflate_table(), inflateStateCheck(), INITBITS, int(), inflate_state::last, LEN, LEN_, inflate_state::lenbits, inflate_state::lencode, LENEXT, LENGTH, inflate_state::length, LENLENS, LENS, inflate_state::lens, LIT, LOAD, MATCH, MEM, inflate_state::mode, NAME, inflate_state::ncode, inflate_state::ndist, NEEDBITS, inflate_state::next, inflate_state::nlen, inflate_state::offset, code::op, OS, PULLBYTE, RESTORE, inflate_state::sane, STORED, SYNC, TABLE, TIME, inflate_state::total, Trace, Tracev, Tracevv, TYPE, TYPEDO, UPDATE_CHECK, updatewindow(), code::val, inflate_state::was, inflate_state::wbits, inflate_state::whave, inflate_state::window, inflate_state::wnext, inflate_state::work, inflate_state::wrap, inflate_state::wsize, Z_BLOCK, Z_BUF_ERROR, z_const, Z_DATA_ERROR, Z_DEFLATED, Z_FINISH, Z_MEM_ERROR, Z_NEED_DICT, Z_NULL, Z_OK, Z_STREAM_END, Z_STREAM_ERROR, Z_TREES, zmemcpy(), and ZSWAP32.
Referenced by gz_decomp(), uncompress2(), and unzReadCurrentFile().
ZEXTERN int ZEXPORT inflateBack (z_streamp strm, in_func in, void FAR * in_desc, out_func out, void FAR * out_desc)
Definition at line 242 of file infback.c.
References BAD, code::bits, inflate_state::bits, BITS, BYTEBITS, CODES, inflate_state::codes, inflate_state::distbits, inflate_state::distcode, DISTS, DONE, DROPBITS, inflate_state::extra, fixedtables(), inflate_state::have, inflate_state::hold, inflate_fast(), inflate_table(), INITBITS, inflate_state::last, LEN, inflate_state::lenbits, inflate_state::lencode, inflate_state::length, LENS, inflate_state::lens, LOAD, inflate_state::mode, inflate_state::ncode, inflate_state::ndist, NEEDBITS, inflate_state::next, inflate_state::nlen, inflate_state::offset, code::op, PULL, PULLBYTE, RESTORE, ROOM, STORED, TABLE, Tracev, Tracevv, TYPE, code::val, inflate_state::whave, inflate_state::window, inflate_state::work, inflate_state::wsize, Z_BUF_ERROR, z_const, Z_DATA_ERROR, Z_NULL, Z_STREAM_END, Z_STREAM_ERROR, and zmemcpy().
ZEXTERN int ZEXPORT inflateBackEnd (z_streamp strm)
Definition at line 621 of file infback.c.
References Tracev, Z_NULL, Z_OK, Z_STREAM_ERROR, and ZFREE.
ZEXTERN int ZEXPORT inflateBackInit_ (z_streamp strm, int windowBits, unsigned char FAR * window, const char * version, int stream_size)
Definition at line 25 of file infback.c.
References inflate_state::dmax, inflate_state::sane, Tracev, inflate_state::wbits, inflate_state::whave, inflate_state::window, internal_state::window, inflate_state::wnext, inflate_state::wsize, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, Z_VERSION_ERROR, ZALLOC, zcalloc(), zcfree(), and ZLIB_VERSION.
ZEXTERN unsigned long ZEXPORT inflateCodesUsed (z_streamp)
Definition at line 1521 of file inflate.c.
References inflate_state::codes, inflateStateCheck(), and inflate_state::next.
ZEXTERN int ZEXPORT inflateCopy (z_streamp dest, z_streamp source)
Definition at line 1439 of file inflate.c.
References ENOUGH, inflateStateCheck(), inflate_state::wbits, inflate_state::window, inflate_state::wsize, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, ZALLOC, ZFREE, and zmemcpy().
ZEXTERN int ZEXPORT inflateEnd (z_streamp strm)
Definition at line 1266 of file inflate.c.
References inflateStateCheck(), Tracev, inflate_state::window, Z_NULL, Z_OK, Z_STREAM_ERROR, and ZFREE.
Referenced by gzclose_r(), uncompress2(), and unzCloseCurrentFile().
ZEXTERN int ZEXPORT inflateGetDictionary (z_streamp strm, Bytef * dictionary, uInt * dictLength)
Definition at line 1278 of file inflate.c.
References inflateStateCheck(), inflate_state::whave, inflate_state::window, inflate_state::wnext, Z_NULL, Z_OK, Z_STREAM_ERROR, and zmemcpy().
ZEXTERN int ZEXPORT inflateGetHeader (z_streamp strm, gz_headerp head)
Definition at line 1330 of file inflate.c.
References inflate_state::head, inflateStateCheck(), inflate_state::wrap, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT inflateInit2_ (z_streamp strm, int windowBits, const char * version, int stream_size)
Definition at line 178 of file inflate.c.
References HEAD, inflateReset2(), inflate_state::mode, inflate_state::strm, internal_state::strm, Tracev, inflate_state::window, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, Z_VERSION_ERROR, ZALLOC, zcalloc(), zcfree(), ZFREE, and ZLIB_VERSION.
Referenced by inflateInit_().
ZEXTERN int ZEXPORT inflateInit_ (z_streamp strm, const char * version, int stream_size)
Definition at line 218 of file inflate.c.
References DEF_WBITS, and inflateInit2_().
ZEXTERN long ZEXPORT inflateMark (z_streamp strm)
Definition at line 1510 of file inflate.c.
References inflate_state::back, COPY, inflateStateCheck(), inflate_state::length, long(), MATCH, inflate_state::mode, and inflate_state::was.
ZEXTERN int ZEXPORT inflatePrime (z_streamp strm, int bits, int value)
Definition at line 223 of file inflate.c.
References inflate_state::bits, inflate_state::hold, inflateStateCheck(), Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT inflateReset (z_streamp strm)
Definition at line 130 of file inflate.c.
References inflateResetKeep(), inflateStateCheck(), inflate_state::whave, inflate_state::wnext, inflate_state::wsize, and Z_STREAM_ERROR.
Referenced by gz_look(), inflateReset2(), and inflateSync().
ZEXTERN int ZEXPORT inflateReset2 (z_streamp strm, int windowBits)
Definition at line 141 of file inflate.c.
References inflateReset(), inflateStateCheck(), inflate_state::wbits, inflate_state::window, inflate_state::wrap, Z_NULL, Z_STREAM_ERROR, and ZFREE.
Referenced by inflateInit2_().
ZEXTERN int ZEXPORT inflateResetKeep (z_streamp)
Definition at line 106 of file inflate.c.
References inflate_state::back, inflate_state::bits, inflate_state::codes, inflate_state::distcode, inflate_state::dmax, inflate_state::flags, inflate_state::havedict, HEAD, inflate_state::head, inflate_state::hold, inflateStateCheck(), inflate_state::last, inflate_state::lencode, inflate_state::mode, inflate_state::next, inflate_state::sane, inflate_state::total, Tracev, inflate_state::wrap, Z_NULL, Z_OK, and Z_STREAM_ERROR.
Referenced by inflateReset().
ZEXTERN int ZEXPORT inflateSetDictionary (z_streamp strm, const Bytef * dictionary, uInt dictLength)
Definition at line 1298 of file inflate.c.
References adler32(), inflate_state::check, DICT, inflate_state::havedict, inflateStateCheck(), MEM, inflate_state::mode, Tracev, updatewindow(), inflate_state::wrap, Z_DATA_ERROR, Z_MEM_ERROR, Z_NULL, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT inflateSync (z_streamp strm)
Definition at line 1375 of file inflate.c.
References inflate_state::bits, inflate_state::flags, inflate_state::have, inflate_state::hold, inflateReset(), inflateStateCheck(), inflate_state::mode, SYNC, syncsearch(), TYPE, inflate_state::wrap, Z_BUF_ERROR, Z_DATA_ERROR, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT inflateSyncPoint (z_streamp)
Definition at line 1431 of file inflate.c.
References inflate_state::bits, inflateStateCheck(), inflate_state::mode, STORED, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT inflateUndermine (z_streamp , int)
Definition at line 1483 of file inflate.c.
References inflateStateCheck(), inflate_state::sane, Z_DATA_ERROR, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT inflateValidate (z_streamp , int)
Definition at line 1498 of file inflate.c.
References inflateStateCheck(), inflate_state::wrap, Z_OK, and Z_STREAM_ERROR.
ZEXTERN int ZEXPORT uncompress (Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen)
Definition at line 82 of file uncompr.c.
References uncompress2().
Referenced by MusicLrcFromKrc::decompression().
ZEXTERN int ZEXPORT uncompress2 (Bytef * dest, uLongf * destLen, const Bytef * source, uLong * sourceLen)
Definition at line 27 of file uncompr.c.
References z_stream_s::avail_in, z_stream_s::avail_out, inflate(), inflateEnd(), inflateInit, TTK::max(), z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, z_stream_s::total_out, Z_BUF_ERROR, z_const, Z_DATA_ERROR, Z_NEED_DICT, Z_NO_FLUSH, Z_OK, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by uncompress().
ZEXTERN const char* ZEXPORT zError (int)
Definition at line 131 of file zutil.c.
References ERR_MSG.
ZEXTERN uLong ZEXPORT zlibCompileFlags (void)
Definition at line 31 of file zutil.c.
References z_off_t.
ZEXTERN const char* ZEXPORT zlibVersion (void)
Definition at line 27 of file zutil.c.
References ZLIB_VERSION.