TTKMusicplayer: MusicSongsListFunctionWidget Class Reference
MusicSongsListFunctionWidget Class Reference
The class of the songs list function widget.
#include <musicsongslistfunctionwidget.h>
Signals
void deleteObject ()
Public Member Functions
MusicSongsListFunctionWidget (QWidget *parent=nullptr)
~MusicSongsListFunctionWidget ()
void active ()
Protected Member Functions
void start (bool play, int end)
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
Protected Attributes
QTimer m_timer
QWidget * m_mainWidget
QPropertyAnimation * m_animation
float m_currentAnimationValue
Private Slots
void leaveTimeout ()
void animationFinished ()
Detailed Description
The class of the songs list function widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicsongslistfunctionwidget.h.
Constructor & Destructor Documentation
MusicSongsListFunctionWidget::MusicSongsListFunctionWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicsongslistfunctionwidget.cpp.
References animationFinished(), MusicApplication::instance(), leaveTimeout(), m_animation, m_mainWidget, m_timer, MusicUIObject::MQSSTinyBtnLocalSearch, MusicUIObject::MQSSTinyBtnLocation, and MT_S2MS.
MusicSongsListFunctionWidget::~MusicSongsListFunctionWidget ()
Definition at line 48 of file musicsongslistfunctionwidget.cpp.
References m_animation, and m_mainWidget.
Member Function Documentation
void MusicSongsListFunctionWidget::active ()
Set current animation active.
Definition at line 54 of file musicsongslistfunctionwidget.cpp.
References m_timer.
Referenced by MusicSongsSummariziedWidget::showFloatWidget().
void MusicSongsListFunctionWidget::animationFinished () private slot
Animation finished.
Definition at line 80 of file musicsongslistfunctionwidget.cpp.
References deleteObject(), m_animation, m_currentAnimationValue, and MT_MS.
Referenced by MusicSongsListFunctionWidget().
void MusicSongsListFunctionWidget::deleteObject () signal
Delete self object.
Referenced by animationFinished().
void MusicSongsListFunctionWidget::enterEvent (QtEnterEvent * event) final override protected virtual
Override the widget event.
Definition at line 89 of file musicsongslistfunctionwidget.cpp.
References m_currentAnimationValue, m_mainWidget, and start().
void MusicSongsListFunctionWidget::leaveEvent (QEvent * event) final override protected virtual
Definition at line 99 of file musicsongslistfunctionwidget.cpp.
References m_mainWidget, and start().
void MusicSongsListFunctionWidget::leaveTimeout () private slot
Leave Time out.
Definition at line 74 of file musicsongslistfunctionwidget.cpp.
References m_currentAnimationValue, and start().
Referenced by MusicSongsListFunctionWidget().
void MusicSongsListFunctionWidget::start (bool play, int end) protected
Start to turn on animation.
Definition at line 60 of file musicsongslistfunctionwidget.cpp.
References m_animation, m_currentAnimationValue, and m_timer.
Referenced by enterEvent(), leaveEvent(), and leaveTimeout().
Member Data Documentation
QPropertyAnimation* MusicSongsListFunctionWidget::m_animation protected
Definition at line 76 of file musicsongslistfunctionwidget.h.
Referenced by animationFinished(), MusicSongsListFunctionWidget(), start(), and ~MusicSongsListFunctionWidget().
float MusicSongsListFunctionWidget::m_currentAnimationValue protected
Definition at line 77 of file musicsongslistfunctionwidget.h.
Referenced by animationFinished(), enterEvent(), leaveTimeout(), and start().
QWidget* MusicSongsListFunctionWidget::m_mainWidget protected
Definition at line 75 of file musicsongslistfunctionwidget.h.
Referenced by enterEvent(), leaveEvent(), MusicSongsListFunctionWidget(), and ~MusicSongsListFunctionWidget().
QTimer MusicSongsListFunctionWidget::m_timer protected
Definition at line 74 of file musicsongslistfunctionwidget.h.
Referenced by active(), MusicSongsListFunctionWidget(), and start().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslistfunctionwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslistfunctionwidget.cpp