TTKMusicPlayer: TTKAbstractNetwork Class Reference
TTKAbstractNetwork Class Reference
The class of the ttk abstract network.
#include <ttkabstractnetwork.h>
Public Slots
virtual void downloadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void downloadDataChanged (const QString &bytes)
void downloadRawDataChanged (const QByteArray &bytes)
Public Member Functions
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value) noexcept
const QVariant header (const QString &key) const noexcept
Protected Attributes
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the ttk abstract network.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 45 of file ttkabstractnetwork.h.
Constructor & Destructor Documentation
TTKAbstractNetwork::TTKAbstractNetwork (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file ttkabstractnetwork.cpp.
References m_manager, and sslErrors().
TTKAbstractNetwork::~TTKAbstractNetwork ()
Object destructor.
Definition at line 17 of file ttkabstractnetwork.cpp.
References deleteAll(), TTK::Error, m_interrupt, and m_stateCode.
Member Function Documentation
void TTKAbstractNetwork::deleteAll () virtual
Release the network object.
Reimplemented in MusicAbstractTranslationRequest, MusicAbstractDownloadRequest, MusicAbstractDownloadImageRequest, MusicCoverRequest, and MusicDataSourceRequest.
Definition at line 25 of file ttkabstractnetwork.cpp.
References m_interrupt, and m_reply.
Referenced by MusicAbstractDownloadImageRequest::deleteAll(), MusicDataSourceRequest::deleteAll(), MusicCoverRequest::deleteAll(), MusicAbstractDownloadRequest::deleteAll(), MusicAbstractTranslationRequest::deleteAll(), MusicMVRadioCategoryRequest::downloadFinished(), MusicMVRadioProgramRequest::downloadFinished(), MusicKGDiscoverListRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicDJRadioCategoryRequest::downloadFinished(), MusicPVCounterRequest::downloadFinished(), MusicResourceRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicKWQueryArtistListRequest::downloadFinished(), ToolQTFM::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicWYQueryArtistListRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicKGQueryAlbumRequest::downloadFinished(), MusicDataSourceRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYSongCommentsRequest::downloadFinished(), MusicKGQueryArtistListRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicKGQueryPlaylistRequest::downloadFinished(), MusicNewAlbumsRecommendRequest::downloadFinished(), MusicWYQueryPlaylistRequest::downloadFinished(), MusicKWQueryPlaylistRequest::downloadFinished(), MusicDownloadDataRequest::downloadFinished(), MusicDJRadioProgramCategoryRequest::downloadFinished(), MusicKWQueryHotArtistListRequest::downloadFinished(), MusicWYQueryHotArtistListRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicDownloadQueueRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicKGQueryArtistAlbumRequest::downloadFinished(), MusicWYPlaylistCommentsRequest::downloadFinished(), MusicKGQueryHotArtistListRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), ToolXIFM::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKGQueryArtistMovieRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicWYQueryArtistMovieRequest::downloadFinished(), MusicKGQueryPlaylistRecommendRequest::downloadFinished(), MusicArtistsRecommendRequest::downloadFinished(), MusicKWQueryNewAlbumRequest::downloadFinished(), MusicWYQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryNewAlbumRequest::downloadFinished(), MusicWYQueryNewAlbumRequest::downloadFinished(), MusicXFIdentifyRequest::downloadFinished(), MusicKWQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryPlaylistHighRequest::downloadFinished(), MusicWYQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistRecommendRequest::downloadFinished(), MusicKWQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistHQRecommendRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadSingleFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicKWQueryMovieRequest::downloadSingleFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicKGQuerySongRequest::downloadSingleFinished(), MusicWYQueryMovieRequest::downloadSingleFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicTXDownloadBackgroundRequest::downloadUrl(), MusicDownloadQueueRequest::handleError(), MusicAbstractNetwork::replyError(), replyError(), MusicAbstractNetwork::sslErrors(), sslErrors(), MusicUnityQueryMovieRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryToplistRequest::startToPage(), MusicWYQuerySongRequest::startToPage(), MusicKWQuerySongRequest::startToPage(), MusicKGQueryAlbumRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicKWQueryToplistRequest::startToPage(), MusicKGQuerySongRequest::startToPage(), MusicNewAlbumsRecommendRequest::startToPage(), MusicKGQueryToplistRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicWYQueryAlbumRequest::startToPage(), MusicKWQueryArtistRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKWQueryAlbumRequest::startToPage(), MusicWYQueryArtistRequest::startToPage(), MusicKGQueryArtistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryHotArtistListRequest::startToPage(), MusicKWQueryHotArtistListRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKGQueryArtistAlbumRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicWYQueryArtistAlbumRequest::startToPage(), MusicKGQueryHotArtistListRequest::startToPage(), MusicKWQueryArtistAlbumRequest::startToPage(), MusicWYQueryNewSongRequest::startToPage(), MusicKWQueryNewSongRequest::startToPage(), MusicKGQueryNewSongRequest::startToPage(), MusicArtistsRecommendRequest::startToPage(), MusicKWQueryArtistMovieRequest::startToPage(), MusicKGQueryArtistMovieRequest::startToPage(), MusicKGQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryArtistMovieRequest::startToPage(), MusicWYQueryNewAlbumRequest::startToPage(), MusicKWQueryNewAlbumRequest::startToPage(), MusicKGQueryNewAlbumRequest::startToPage(), MusicKWQueryPlaylistRecommendRequest::startToPage(), MusicKGQueryPlaylistHighRequest::startToPage(), MusicPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistHighRequest::startToPage(), MusicKWQueryPlaylistHighRequest::startToPage(), MusicPlaylistHQRecommendRequest::startToPage(), MusicFMRadioSongRequest::startToRequest(), MusicDJRadioCategoryRequest::startToRequest(), MusicBDTranslationRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), MusicBPDownloadBackgroundRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), ToolQTFM::startToRequest(), MusicDJRadioProgramRequest::startToRequest(), MusicTXDownloadBackgroundRequest::startToRequest(), ToolXIFM::startToRequest(), MusicKGDiscoverListRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicSongSuggestRequest::startToSearch(), MusicSongRecommendRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicKWQuerySongRequest::startToSearchByID(), MusicWYQuerySongRequest::startToSearchByID(), MusicKGQuerySongRequest::startToSearchByID(), MusicKWQueryMovieRequest::startToSearchByID(), MusicKGQueryMovieRequest::startToSearchByID(), MusicWYQueryMovieRequest::startToSearchByID(), and ~TTKAbstractNetwork().
void TTKAbstractNetwork::downloadDataChanged (const QString & bytes) signal
Send download data changed.
Referenced by MusicTranslationRequest::downloadDataFinished(), MusicIdentifySongRequest::downloadDataFinished(), MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicMVRadioCategoryRequest::downloadFinished(), MusicMVRadioProgramRequest::downloadFinished(), MusicWYDownloadTextRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicKWDownloadTextRequest::downloadFinished(), MusicDJRadioCategoryRequest::downloadFinished(), MusicBPDownloadBackgroundRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicKGDownloadBackgroundRequest::downloadFinished(), MusicKGDiscoverListRequest::downloadFinished(), MusicDownloadTextRequest::downloadFinished(), MusicPVCounterRequest::downloadFinished(), MusicBDTranslationRequest::downloadFinished(), MusicKWDownloadBackgroundRequest::downloadFinished(), MusicBingTranslationRequest::downloadFinished(), MusicWYTranslationRequest::downloadFinished(), MusicYDTranslationRequest::downloadFinished(), MusicWYCoverSourceRequest::downloadFinished(), ToolQTFM::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYSongCommentsRequest::downloadFinished(), MusicKGQueryAlbumRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicDownloadMetaDataRequest::downloadFinished(), MusicNewAlbumsRecommendRequest::downloadFinished(), MusicDownloadDataRequest::downloadFinished(), MusicTXDownloadBackgroundRequest::downloadFinished(), MusicWYQueryHotArtistListRequest::downloadFinished(), MusicKWQueryHotArtistListRequest::downloadFinished(), MusicKWDownloadCoverRequest::downloadFinished(), MusicDownloadQueueRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicKGQueryHotArtistListRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), MusicKGQueryArtistAlbumRequest::downloadFinished(), MusicWYPlaylistCommentsRequest::downloadFinished(), ToolXIFM::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKGQueryArtistMovieRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicWYQueryArtistMovieRequest::downloadFinished(), MusicKGQueryPlaylistRecommendRequest::downloadFinished(), MusicArtistsRecommendRequest::downloadFinished(), MusicWYQueryNewAlbumRequest::downloadFinished(), MusicWYQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryNewAlbumRequest::downloadFinished(), MusicKWQueryNewAlbumRequest::downloadFinished(), MusicXFIdentifyRequest::downloadFinished(), MusicKWQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryPlaylistHighRequest::downloadFinished(), MusicWYQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistRecommendRequest::downloadFinished(), MusicKWQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistHQRecommendRequest::downloadFinished(), MusicKGQuerySongRequest::downloadSingleFinished(), MusicKGQueryMovieRequest::downloadSingleFinished(), MusicWYQuerySongRequest::downloadSingleFinished(), MusicWYQueryMovieRequest::downloadSingleFinished(), MusicKWQueryMovieRequest::downloadSingleFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicTXDownloadBackgroundRequest::downloadUrlFinished(), MusicTranslationRequest::findAllPlugins(), MusicIdentifySongRequest::findAllPlugins(), MusicKGDownloadBackgroundRequest::parseFromBackgroundProperty(), replyError(), sslErrors(), MusicDownloadQueueRequest::startOrderQueue(), MusicWYTranslationRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicKWDownloadTextRequest::startToRequest(), MusicWYCoverSourceRequest::startToRequest(), MusicDownloadTextRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicPVCounterRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicWYDownloadTextRequest::startToRequest(), MusicDownloadDataRequest::startToRequest(), MusicDownloadMetaDataRequest::startToRequest(), MusicKWDownloadCoverRequest::startToRequest(), MusicKGSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), and MusicWYSongCommentsRequest::startToSearch().
void TTKAbstractNetwork::downloadFinished () virtual slot
Download data from net finished. Subclass should implement this function.
Definition at line 35 of file ttkabstractnetwork.cpp.
References m_interrupt.
Referenced by MusicAbstractDownloadImageRequest::downloadDataFinished(), MusicBPDownloadBackgroundRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicDJRadioCategoryRequest::downloadFinished(), MusicWYTranslationRequest::downloadFinished(), MusicPVCounterRequest::downloadFinished(), MusicKGDownloadBackgroundRequest::downloadFinished(), MusicResourceRequest::downloadFinished(), MusicBDTranslationRequest::downloadFinished(), MusicBingTranslationRequest::downloadFinished(), MusicYDTranslationRequest::downloadFinished(), MusicKGDiscoverListRequest::downloadFinished(), MusicKWDownloadBackgroundRequest::downloadFinished(), MusicWYCoverSourceRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), ToolQTFM::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicDataSourceRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYSongCommentsRequest::downloadFinished(), MusicKGQueryAlbumRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicAbstractDownloadRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicTXDownloadBackgroundRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), MusicWYPlaylistCommentsRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicKGQueryArtistAlbumRequest::downloadFinished(), ToolXIFM::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKGQueryArtistMovieRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicWYQueryArtistMovieRequest::downloadFinished(), MusicXFIdentifyRequest::downloadFinished(), MusicAbstractQueryRequest::downloadFinished(), MusicCoverSourceRequest::downloadRawDataFinished(), MusicKWCoverSourceRequest::downloadRawDataFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicTXDownloadBackgroundRequest::downloadUrlFinished(), MusicKGQueryPlaylistRequest::startToQueryInfo(), MusicKWQueryPlaylistRequest::startToQueryInfo(), MusicWYQueryPlaylistRequest::startToQueryInfo(), MusicSongRecommendRequest::startToQueryResult(), MusicWYQueryAlbumRequest::startToQueryResult(), MusicWYQueryArtistRequest::startToQueryResult(), MusicKWQueryArtistRequest::startToQueryResult(), MusicKGQueryArtistRequest::startToQueryResult(), MusicKGQueryAlbumRequest::startToQueryResult(), MusicKWQueryAlbumRequest::startToQueryResult(), MusicKWQueryToplistRequest::startToQueryResult(), MusicKGQuerySongRequest::startToQueryResult(), MusicWYQuerySongRequest::startToQueryResult(), MusicWYQueryToplistRequest::startToQueryResult(), MusicKWQuerySongRequest::startToQueryResult(), MusicNewAlbumsRecommendRequest::startToQueryResult(), MusicKGQueryPlaylistRequest::startToQueryResult(), MusicKGQueryToplistRequest::startToQueryResult(), MusicWYQueryPlaylistRequest::startToQueryResult(), MusicDJRadioProgramCategoryRequest::startToQueryResult(), MusicKWQueryPlaylistRequest::startToQueryResult(), MusicWYQueryNewSongRequest::startToQueryResult(), MusicKGQueryNewSongRequest::startToQueryResult(), MusicKWQueryNewSongRequest::startToQueryResult(), MusicArtistsRecommendRequest::startToQueryResult(), MusicPlaylistRecommendRequest::startToQueryResult(), and MusicPlaylistHQRecommendRequest::startToQueryResult().
void TTKAbstractNetwork::downloadRawDataChanged (const QByteArray & bytes) signal
Send download raw data changed.
Referenced by MusicBarrageRequest::downloadFinished(), MusicDataSourceRequest::downloadFinished(), MusicDownloadMetaDataRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicCoverSourceRequest::downloadRawDataFinished(), MusicKWCoverSourceRequest::downloadRawDataFinished(), MusicIdentifySongRequest::initialize(), MusicCoverSourceRequest::startToRequest(), and MusicKWCoverSourceRequest::startToRequest().
const QVariant TTKAbstractNetwork::header (const QString & key) const inline noexcept
Get the current raw data.
Definition at line 70 of file ttkabstractnetwork.h.
References key.
Referenced by MusicDownloadStatusModule::currentMetaDataDownload(), MusicWebDJRadioProgramTableWidget::downloadFinished(), MusicTranslationRequest::findAllPlugins(), and MusicWYTranslationRequest::startToRequest().
void TTKAbstractNetwork::replyError (QNetworkReply::NetworkError error) virtual slot
Download reply error.
Definition at line 40 of file ttkabstractnetwork.cpp.
References deleteAll(), downloadDataChanged(), and TTK_ERROR_STREAM.
void TTKAbstractNetwork::setHeader (const QString & key, const QVariant & value) inline noexcept
Set the current raw data.
Definition at line 66 of file ttkabstractnetwork.h.
References key.
Referenced by MusicDownloadStatusModule::checkMetaDataValid(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicTranslationRequest::findAllPlugins(), and MusicLrcTranslatedWidget::setCurrentSongName().
void TTKAbstractNetwork::sslErrors (QNetworkReply * reply, const QList< QSslError > & errors) virtual slot
Download ssl reply error.
Definition at line 48 of file ttkabstractnetwork.cpp.
References deleteAll(), downloadDataChanged(), and sslErrorsString().
Referenced by TTKAbstractNetwork().
void TTKAbstractNetwork::sslErrorsString (QNetworkReply * reply, const QList< QSslError > & errors) slot
Download ssl reply error strings.
Definition at line 55 of file ttkabstractnetwork.cpp.
References qAsConst, and TTK_ERROR_STREAM.
Referenced by MusicAbstractNetwork::sslErrors(), and sslErrors().
Member Data Documentation
volatile bool TTKAbstractNetwork::m_interrupt protected
Definition at line 105 of file ttkabstractnetwork.h.
Referenced by deleteAll(), downloadFinished(), and ~TTKAbstractNetwork().
QNetworkAccessManager TTKAbstractNetwork::m_manager protected
Definition at line 108 of file ttkabstractnetwork.h.
Referenced by MusicTXDownloadBackgroundRequest::downloadUrl(), MusicKWQueryPlaylistRequest::morePlaylistDetails(), MusicDownloadQueueRequest::startDownload(), MusicUnityQueryMovieRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryArtistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicWYQuerySongRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicKWQueryArtistRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicWYQueryToplistRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicKGQueryAlbumRequest::startToPage(), MusicKGQuerySongRequest::startToPage(), MusicKWQuerySongRequest::startToPage(), MusicKWQueryToplistRequest::startToPage(), MusicKGQueryToplistRequest::startToPage(), MusicNewAlbumsRecommendRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKGQueryArtistRequest::startToPage(), MusicWYQueryAlbumRequest::startToPage(), MusicKWQueryAlbumRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKWQueryHotArtistListRequest::startToPage(), MusicWYQueryHotArtistListRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKWQueryArtistAlbumRequest::startToPage(), MusicKGQueryArtistAlbumRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicWYQueryArtistAlbumRequest::startToPage(), MusicKGQueryHotArtistListRequest::startToPage(), MusicKGQueryArtistMovieRequest::startToPage(), MusicWYQueryNewSongRequest::startToPage(), MusicKWQueryArtistMovieRequest::startToPage(), MusicKWQueryNewSongRequest::startToPage(), MusicArtistsRecommendRequest::startToPage(), MusicKGQueryNewSongRequest::startToPage(), MusicKGQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryArtistMovieRequest::startToPage(), MusicKWQueryNewAlbumRequest::startToPage(), MusicKGQueryNewAlbumRequest::startToPage(), MusicWYQueryNewAlbumRequest::startToPage(), MusicKWQueryPlaylistRecommendRequest::startToPage(), MusicKGQueryPlaylistHighRequest::startToPage(), MusicPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistHighRequest::startToPage(), MusicKWQueryPlaylistHighRequest::startToPage(), MusicPlaylistHQRecommendRequest::startToPage(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicWYDownloadTextRequest::startToRequest(), MusicDownloadTextRequest::startToRequest(), MusicBarrageRequest::startToRequest(), MusicDJRadioCategoryRequest::startToRequest(), MusicFMRadioSongRequest::startToRequest(), MusicCiBaRequest::startToRequest(), MusicPVCounterRequest::startToRequest(), MusicBDTranslationRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicResourceRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicBPDownloadBackgroundRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), MusicWYCoverSourceRequest::startToRequest(), MusicKWDownloadTextRequest::startToRequest(), ToolQTFM::startToRequest(), MusicDataSourceRequest::startToRequest(), MusicDJRadioProgramRequest::startToRequest(), MusicTXDownloadBackgroundRequest::startToRequest(), MusicKWDownloadCoverRequest::startToRequest(), ToolXIFM::startToRequest(), MusicACRIdentifyRequest::startToRequest(), MusicDownloadDataRequest::startToRequest(), MusicXFIdentifyRequest::startToRequest(), MusicSongSuggestRequest::startToSearch(), MusicSongRecommendRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), MusicAbstractMVRadioRequest::startToSearch(), MusicKGQueryPlaylistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicKGQuerySongRequest::startToSearchByID(), MusicWYQuerySongRequest::startToSearchByID(), MusicKWQuerySongRequest::startToSearchByID(), and TTKAbstractNetwork().
QVariantMap TTKAbstractNetwork::m_rawData protected
Definition at line 104 of file ttkabstractnetwork.h.
Referenced by MusicCiBaRequest::content(), MusicKGQueryArtistListRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicIdentifySongRequest::downloadKeyFinished(), MusicIdentifySongRequest::findAllPlugins(), MusicCiBaRequest::image(), MusicIdentifySongRequest::initialize(), MusicCiBaRequest::note(), and MusicKGQueryArtistListRequest::startToPage().
QNetworkReply* TTKAbstractNetwork::m_reply protected
Definition at line 107 of file ttkabstractnetwork.h.
Referenced by MusicDownloadQueueRequest::abort(), deleteAll(), MusicMVRadioCategoryRequest::downloadFinished(), MusicMVRadioProgramRequest::downloadFinished(), MusicBarrageRequest::downloadFinished(), MusicDJRadioCategoryRequest::downloadFinished(), MusicKGDiscoverListRequest::downloadFinished(), MusicKGDownloadBackgroundRequest::downloadFinished(), MusicDownloadTextRequest::downloadFinished(), MusicPVCounterRequest::downloadFinished(), MusicResourceRequest::downloadFinished(), MusicBDTranslationRequest::downloadFinished(), MusicBingTranslationRequest::downloadFinished(), MusicWYTranslationRequest::downloadFinished(), MusicYDTranslationRequest::downloadFinished(), MusicBPDownloadBackgroundRequest::downloadFinished(), MusicKWDiscoverListRequest::downloadFinished(), MusicWYCoverSourceRequest::downloadFinished(), MusicKWDownloadTextRequest::downloadFinished(), MusicWYDownloadTextRequest::downloadFinished(), MusicKWDownloadBackgroundRequest::downloadFinished(), ToolQTFM::downloadFinished(), MusicWYDiscoverListRequest::downloadFinished(), MusicWYQueryArtistListRequest::downloadFinished(), MusicKWQueryArtistListRequest::downloadFinished(), MusicKWSongCommentsRequest::downloadFinished(), MusicSongRecommendRequest::downloadFinished(), MusicKGSongCommentsRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicFMRadioSongRequest::downloadFinished(), MusicKGQueryAlbumRequest::downloadFinished(), MusicDataSourceRequest::downloadFinished(), MusicSongSuggestRequest::downloadFinished(), MusicWYSongCommentsRequest::downloadFinished(), MusicKGQueryArtistListRequest::downloadFinished(), MusicWYQueryAlbumRequest::downloadFinished(), MusicKGQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicWYQueryArtistRequest::downloadFinished(), MusicWYQuerySongRequest::downloadFinished(), MusicWYQueryToplistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKGQueryToplistRequest::downloadFinished(), MusicKGQuerySongRequest::downloadFinished(), MusicWYQueryMovieRequest::downloadFinished(), MusicKGQueryMovieRequest::downloadFinished(), MusicDJRadioProgramRequest::downloadFinished(), MusicKGQueryPlaylistRequest::downloadFinished(), MusicCiBaRequest::downloadFinished(), MusicNewAlbumsRecommendRequest::downloadFinished(), MusicKWQueryPlaylistRequest::downloadFinished(), MusicWYQueryPlaylistRequest::downloadFinished(), MusicDownloadDataRequest::downloadFinished(), MusicTXDownloadBackgroundRequest::downloadFinished(), MusicDJRadioProgramCategoryRequest::downloadFinished(), MusicKWQueryHotArtistListRequest::downloadFinished(), MusicWYQueryHotArtistListRequest::downloadFinished(), MusicDownloadQueueRequest::downloadFinished(), MusicKWPlaylistCommentsRequest::downloadFinished(), MusicKWDownloadCoverRequest::downloadFinished(), MusicKGPlaylistCommentsRequest::downloadFinished(), MusicKGQueryArtistAlbumRequest::downloadFinished(), MusicWYPlaylistCommentsRequest::downloadFinished(), MusicKGQueryHotArtistListRequest::downloadFinished(), MusicWYQueryArtistAlbumRequest::downloadFinished(), MusicKWQueryArtistAlbumRequest::downloadFinished(), ToolXIFM::downloadFinished(), MusicACRIdentifyRequest::downloadFinished(), MusicKGQueryArtistMovieRequest::downloadFinished(), MusicKWQueryArtistMovieRequest::downloadFinished(), MusicWYQueryNewSongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicKGQueryNewSongRequest::downloadFinished(), MusicWYQueryArtistMovieRequest::downloadFinished(), MusicKGQueryPlaylistRecommendRequest::downloadFinished(), MusicArtistsRecommendRequest::downloadFinished(), MusicKGQueryNewAlbumRequest::downloadFinished(), MusicWYQueryNewAlbumRequest::downloadFinished(), MusicKWQueryNewAlbumRequest::downloadFinished(), MusicWYQueryPlaylistRecommendRequest::downloadFinished(), MusicXFIdentifyRequest::downloadFinished(), MusicKWQueryPlaylistRecommendRequest::downloadFinished(), MusicKGQueryPlaylistHighRequest::downloadFinished(), MusicWYQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistRecommendRequest::downloadFinished(), MusicKWQueryPlaylistHighRequest::downloadFinished(), MusicPlaylistHQRecommendRequest::downloadFinished(), MusicUnityQueryMovieRequest::downloadUnityFinished(), MusicTXDownloadBackgroundRequest::downloadUrl(), MusicTXDownloadBackgroundRequest::downloadUrlFinished(), MusicDownloadQueueRequest::handleError(), MusicDownloadDataRequest::handleReadyRead(), MusicDownloadQueueRequest::handleReadyRead(), MusicDownloadQueueRequest::startDownload(), MusicUnityQueryMovieRequest::startToPage(), MusicKWSongCommentsRequest::startToPage(), MusicKGSongCommentsRequest::startToPage(), MusicKWQueryAlbumRequest::startToPage(), MusicWYQuerySongRequest::startToPage(), MusicWYQueryToplistRequest::startToPage(), MusicKWQueryArtistRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKGQueryPlaylistRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicKGQueryToplistRequest::startToPage(), MusicKGQueryAlbumRequest::startToPage(), MusicNewAlbumsRecommendRequest::startToPage(), MusicDJRadioProgramCategoryRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicKWQuerySongRequest::startToPage(), MusicKGQueryArtistListRequest::startToPage(), MusicWYQueryAlbumRequest::startToPage(), MusicKGQueryArtistRequest::startToPage(), MusicKGQuerySongRequest::startToPage(), MusicKGQueryMovieRequest::startToPage(), MusicKWQueryToplistRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicWYQueryArtistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicWYQueryHotArtistListRequest::startToPage(), MusicKWQueryHotArtistListRequest::startToPage(), MusicKGPlaylistCommentsRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicKGQueryArtistAlbumRequest::startToPage(), MusicWYQueryArtistAlbumRequest::startToPage(), MusicKGQueryHotArtistListRequest::startToPage(), MusicKWQueryArtistAlbumRequest::startToPage(), MusicWYQueryNewSongRequest::startToPage(), MusicKGQueryArtistMovieRequest::startToPage(), MusicKWQueryNewSongRequest::startToPage(), MusicKWQueryArtistMovieRequest::startToPage(), MusicKGQueryNewSongRequest::startToPage(), MusicArtistsRecommendRequest::startToPage(), MusicKGQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistRecommendRequest::startToPage(), MusicWYQueryArtistMovieRequest::startToPage(), MusicWYQueryNewAlbumRequest::startToPage(), MusicKGQueryNewAlbumRequest::startToPage(), MusicKWQueryNewAlbumRequest::startToPage(), MusicKWQueryPlaylistRecommendRequest::startToPage(), MusicKGQueryPlaylistHighRequest::startToPage(), MusicPlaylistRecommendRequest::startToPage(), MusicWYQueryPlaylistHighRequest::startToPage(), MusicKWQueryPlaylistHighRequest::startToPage(), MusicPlaylistHQRecommendRequest::startToPage(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicWYCoverSourceRequest::startToRequest(), MusicYDTranslationRequest::startToRequest(), MusicWYTranslationRequest::startToRequest(), MusicFMRadioSongRequest::startToRequest(), MusicBarrageRequest::startToRequest(), MusicPVCounterRequest::startToRequest(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicDJRadioCategoryRequest::startToRequest(), MusicKWDownloadTextRequest::startToRequest(), MusicResourceRequest::startToRequest(), MusicBDTranslationRequest::startToRequest(), MusicBPDownloadBackgroundRequest::startToRequest(), MusicWYDownloadTextRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), MusicDownloadTextRequest::startToRequest(), MusicCiBaRequest::startToRequest(), ToolQTFM::startToRequest(), MusicDataSourceRequest::startToRequest(), MusicDownloadMetaDataRequest::startToRequest(), MusicDJRadioProgramRequest::startToRequest(), MusicTXDownloadBackgroundRequest::startToRequest(), MusicKWDownloadCoverRequest::startToRequest(), ToolXIFM::startToRequest(), MusicACRIdentifyRequest::startToRequest(), MusicDownloadDataRequest::startToRequest(), MusicXFIdentifyRequest::startToRequest(), MusicSongSuggestRequest::startToSearch(), MusicKGDiscoverListRequest::startToSearch(), MusicKWDiscoverListRequest::startToSearch(), MusicSongRecommendRequest::startToSearch(), MusicWYDiscoverListRequest::startToSearch(), and MusicAbstractMVRadioRequest::startToSearch().
volatile TTK::NetworkCode TTKAbstractNetwork::m_stateCode protected
Definition at line 106 of file ttkabstractnetwork.h.
Referenced by ~TTKAbstractNetwork().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractnetwork.h
TTKCommon/TTKLibrary/ttkabstractnetwork.cpp