TTKMusicPlayer: MusicWYInterface Namespace Reference
MusicWYInterface Namespace Reference
The namespace of the wangyi request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request)
QByteArray makeTokenRequest (QNetworkRequest *request, const QString &query, const QString &type)
void parseFromSongProperty (TTK::MusicSongInformation *info, int bitrate)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QVariantMap &key, TTK::QueryQuality quality, bool all)
void parseFromSongPropertyNew (TTK::MusicSongInformation *info, int bitrate)
Detailed Description
The namespace of the wangyi request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void MusicWYInterface::makeRequestRawHeader (QNetworkRequest * request)
Make request query data.
Definition at line 7 of file musicwyqueryinterface.cpp.
References ALG_UA_KEY, TTK::Algorithm::mdII(), TTK::setSslConfiguration(), WY_BASE_URL, WY_COOKIE_URL, WY_NMTID_URL, and WY_UA_URL.
Referenced by makeTokenRequest(), and parseFromSongProperty().
QByteArray MusicWYInterface::makeTokenRequest (QNetworkRequest * request, const QString & query, const QString & type)
Make token query request.
Definition at line 17 of file musicwyqueryinterface.cpp.
References QAlgorithm::Aes::encryptCBC(), makeRequestRawHeader(), TTK::Url::urlEncode(), and WY_SECKRY_STRING.
Referenced by MusicWYQueryMovieRequest::parseFromArtistMoviesCount(), MusicWYQueryMovieRequest::parseFromMovieList(), parseFromSongPropertyNew(), MusicWYQueryMovieRequest::parseFromVideoList(), MusicWYQueryMovieRequest::parseFromVideoUrlPath(), MusicWYQueryArtistRequest::queryArtistIntro(), MusicWYQueryPlaylistRequest::queryPlaylistInfo(), MusicDJRadioProgramCategoryRequest::queryProgramInfo(), MusicDJRadioCategoryRequest::startRequest(), MusicFMRadioSongRequest::startRequest(), MusicDJRadioProgramRequest::startRequest(), MusicWYQueryRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicWYSongCommentsRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicWYDiscoverListRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSearch(), MusicWYQueryArtistRequest::startToSearch(), MusicWYQueryMovieRequest::startToSearch(), MusicWYQueryToplistRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), MusicWYQueryAlbumRequest::startToSingleSearch(), and MusicWYQueryRequest::startToSingleSearch().
void MusicWYInterface::parseFromSongProperty (TTK::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 30 of file musicwyqueryinterface.cpp.
References TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, makeRequestRawHeader(), TTK::Algorithm::mdII(), QJson::Parser::parse(), parseFromSongPropertyNew(), TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), and WY_SONG_INFO_OLD_URL.
Referenced by MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicFMRadioSongRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), and MusicWYQueryRequest::downLoadSingleFinished().
void MusicWYInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QVariantMap & key, TTK::QueryQuality quality, bool all)
Read tags(size) from query results.
Definition at line 78 of file musicwyqueryinterface.cpp.
References TTK::High, TTK::Lossless, MB_1000, MB_128, MB_192, MB_320, MusicKGInterface::parseFromSongProperty(), TTK::Standard, and TTK::Super.
void MusicWYInterface::parseFromSongPropertyNew (TTK::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 149 of file musicwyqueryinterface.cpp.
References TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, makeTokenRequest(), TTK::Algorithm::mdII(), QJson::Parser::parse(), TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForPost(), WY_SONG_PATH_DATA_URL, and WY_SONG_PATH_URL.
Referenced by parseFromSongProperty().