TTKMusicPlayer: QSyncDataInterface Class Reference
QSyncDataInterface Class Reference abstract
The class of the sync cloud data interface.
#include <qsyncdatainterface.h>
Public Member Functions
QSyncDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Protected Slots
virtual void receiveDataFromServer ()=0
void replyError (QNetworkReply::NetworkError error)
Protected Member Functions
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
QSyncDataInterface (QSyncDataInterfacePrivate &pvt, QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Detailed Description
The class of the sync cloud data interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file qsyncdatainterface.h.
Constructor & Destructor Documentation
QSyncDataInterface::QSyncDataInterface (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file qsyncdatainterface.cpp.
QSyncDataInterface::QSyncDataInterface (QSyncDataInterfacePrivate & pvt, QNetworkAccessManager * networkManager, QObject * parent = nullptr) protected
Object contsructor.
Definition at line 10 of file qsyncdatainterface.cpp.
References TTK_D, and TTK_INIT_PRIVATE_D.
Member Function Documentation
QString QSyncDataInterface::pathDecode (const QString & data) const protected
Pretty decode the data into url.
Definition at line 32 of file qsyncdatainterface.cpp.
QString QSyncDataInterface::pathEncode (const QString & data) const protected
Pretty encode the data into url.
Definition at line 23 of file qsyncdatainterface.cpp.
Referenced by QSyncDownloadData::downloadUrl().
virtual void QSyncDataInterface::receiveDataFromServer () protected pure virtual slot
Receive data from server finshed. Subclass should implement this function.
void QSyncDataInterface::replyError (QNetworkReply::NetworkError error) protected slot
Get handle error.
Definition at line 18 of file qsyncdatainterface.cpp.
References TTK_ERROR_STREAM.
Referenced by QSyncDeleteData::deleteDataOperator(), QSyncDownloadData::downloadDataOperator(), QSyncListData::listDataOperator(), and QSyncUploadData::uploadDataOperator().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncdatainterface.h
TTKThirdParty/TTKExtras/qsync/qsyncdatainterface.cpp