TTKMusicplayer: MusicWebDJRadioCategoryWidget Class Reference
MusicWebDJRadioCategoryWidget Class Reference
The class of music dj radio category widget.
#include <musicwebdjradiocategorywidget.h>
Public Slots
void createCategoryItems ()
Signals
void currentCategoryClicked (const MusicResultsItem &item)
Public Member Functions
MusicWebDJRadioCategoryWidget (QWidget *parent=nullptr)
~MusicWebDJRadioCategoryWidget ()
void initialize ()
void resizeWindow ()
Protected Attributes
QGridLayout * m_gridLayout
QList< QLabel * > m_resizeWidgets
MusicDJRadioCategoryRequest * m_categoryThread
Detailed Description
The class of music dj radio category widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 73 of file musicwebdjradiocategorywidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioCategoryWidget::MusicWebDJRadioCategoryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 69 of file musicwebdjradiocategorywidget.cpp.
References createCategoryItems(), MusicUtils::Widget::generateVScrollAreaFormat(), m_categoryThread, and m_gridLayout.
MusicWebDJRadioCategoryWidget::~MusicWebDJRadioCategoryWidget ()
Definition at line 91 of file musicwebdjradiocategorywidget.cpp.
References m_categoryThread, and m_gridLayout.
Member Function Documentation
void MusicWebDJRadioCategoryWidget::createCategoryItems () slot
Query all quality musics is finished.
Definition at line 119 of file musicwebdjradiocategorywidget.cpp.
References currentCategoryClicked(), LINE_SPACING_SIZE, m_categoryThread, m_gridLayout, m_resizeWidgets, MusicAbstractDJRadioRequest::searchedItems(), and MusicWebDJRadioCategoryItemWidget::setMusicResultsItem().
Referenced by MusicWebDJRadioCategoryWidget().
void MusicWebDJRadioCategoryWidget::currentCategoryClicked (const MusicResultsItem & item) signal
Current category clicked.
Referenced by createCategoryItems().
void MusicWebDJRadioCategoryWidget::initialize ()
Init parameters.
Definition at line 97 of file musicwebdjradiocategorywidget.cpp.
References m_categoryThread, and MusicDJRadioCategoryRequest::startToDownload().
Referenced by MusicWebDJRadioWidget::initialize().
void MusicWebDJRadioCategoryWidget::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 102 of file musicwebdjradiocategorywidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and m_resizeWidgets.
Referenced by MusicWebDJRadioWidget::resizeWindow().
Member Data Documentation
MusicDJRadioCategoryRequest* MusicWebDJRadioCategoryWidget::m_categoryThread protected
Definition at line 108 of file musicwebdjradiocategorywidget.h.
Referenced by createCategoryItems(), initialize(), MusicWebDJRadioCategoryWidget(), and ~MusicWebDJRadioCategoryWidget().
QGridLayout* MusicWebDJRadioCategoryWidget::m_gridLayout protected
Definition at line 106 of file musicwebdjradiocategorywidget.h.
Referenced by createCategoryItems(), MusicWebDJRadioCategoryWidget(), resizeWindow(), and ~MusicWebDJRadioCategoryWidget().
QList<QLabel*> MusicWebDJRadioCategoryWidget::m_resizeWidgets protected
Definition at line 107 of file musicwebdjradiocategorywidget.h.
Referenced by createCategoryItems(), and resizeWindow().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiocategorywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradiocategorywidget.cpp