TTKMusicplayer: MusicDownloadBatchTableWidget Class Reference
MusicDownloadBatchTableWidget Class Reference
The class of the download batch table widget.
#include <musicdownloadbatchwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
void dataDownloadFinished ()
void currentQualityChanged (int index)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Public Member Functions
MusicDownloadBatchTableWidget (QWidget *parent=nullptr)
~MusicDownloadBatchTableWidget ()
void setParentClass (QWidget *parent)
void clearAllItems ()
void createItem (const MusicObject::MusicSongInformation &info, MusicAbstractQueryRequest::QueryType type)
void startToDownload ()
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
void clear ()
TTKIntList multiSelectedIndex () const
Protected Attributes
QObject * m_supperClass
int m_downloadOffset
QList< MusicDownloadBatchTableItem * > m_items
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_backgroundColor
int m_previousColorRow
int m_previousClickRow
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Detailed Description
The class of the download batch table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 85 of file musicdownloadbatchwidget.h.
Constructor & Destructor Documentation
MusicDownloadBatchTableWidget::MusicDownloadBatchTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 265 of file musicdownloadbatchwidget.cpp.
References m_downloadOffset, m_supperClass, MusicUIObject::MQSSScrollBarStyle01, MusicUIObject::MQSSTableWidgetStyle02, and MusicUtils::Widget::setTransparent().
MusicDownloadBatchTableWidget::~MusicDownloadBatchTableWidget ()
Definition at line 280 of file musicdownloadbatchwidget.cpp.
References clearAllItems().
Member Function Documentation
void MusicDownloadBatchTableWidget::clearAllItems ()
Clear All Items.
Definition at line 290 of file musicdownloadbatchwidget.cpp.
References MusicAbstractTableWidget::clear(), m_downloadOffset, and m_items.
Referenced by ~MusicDownloadBatchTableWidget().
void MusicDownloadBatchTableWidget::createItem (const MusicObject::MusicSongInformation & info, MusicAbstractQueryRequest::QueryType type)
Create current item by song info.
Definition at line 299 of file musicdownloadbatchwidget.cpp.
References MusicDownloadBatchTableItem::createItem(), ITEM_ROW_HEIGHT_S, and m_items.
void MusicDownloadBatchTableWidget::currentQualityChanged (int index) slot
Table widget item cell click.
Remove first null item object
Definition at line 337 of file musicdownloadbatchwidget.cpp.
References m_items.
void MusicDownloadBatchTableWidget::dataDownloadFinished () slot
Data download is finished.
Definition at line 328 of file musicdownloadbatchwidget.cpp.
References m_downloadOffset, m_supperClass, and MT_S2MS.
void MusicDownloadBatchTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 322 of file musicdownloadbatchwidget.cpp.
void MusicDownloadBatchTableWidget::setParentClass (QWidget * parent)
Set parent class.
Definition at line 285 of file musicdownloadbatchwidget.cpp.
References m_supperClass.
void MusicDownloadBatchTableWidget::startToDownload ()
Start to download music data.
Definition at line 314 of file musicdownloadbatchwidget.cpp.
References m_items.
Member Data Documentation
int MusicDownloadBatchTableWidget::m_downloadOffset protected
Definition at line 129 of file musicdownloadbatchwidget.h.
Referenced by clearAllItems(), dataDownloadFinished(), and MusicDownloadBatchTableWidget().
QList<MusicDownloadBatchTableItem*> MusicDownloadBatchTableWidget::m_items protected
Definition at line 130 of file musicdownloadbatchwidget.h.
Referenced by clearAllItems(), createItem(), currentQualityChanged(), and startToDownload().
QObject* MusicDownloadBatchTableWidget::m_supperClass protected
Definition at line 128 of file musicdownloadbatchwidget.h.
Referenced by dataDownloadFinished(), MusicDownloadBatchTableWidget(), and setParentClass().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadbatchwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadbatchwidget.cpp