TTKMusicPlayer: MusicLrcPhotoWidget Class Reference
MusicLrcPhotoWidget Class Reference
The class of the lrc photo widget.
#include <musiclrcphotomanagerwidget.h>
Public Slots
void addButtonClicked ()
void deleteButtonClicked ()
void exportButtonClicked ()
Public Member Functions
MusicLrcPhotoWidget (QWidget *parent=nullptr)
~MusicLrcPhotoWidget ()
void addCellItem (const QString &path)
Private Member Functions
void initialize ()
bool isValid () const
Private Attributes
QGridLayout * m_gridLayout
QList< MusicLrcPhotoItem * > m_items
Detailed Description
The class of the lrc photo widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 77 of file musiclrcphotomanagerwidget.h.
Constructor & Destructor Documentation
MusicLrcPhotoWidget::MusicLrcPhotoWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 46 of file musiclrcphotomanagerwidget.cpp.
References initialize(), and m_gridLayout.
MusicLrcPhotoWidget::~MusicLrcPhotoWidget ()
Object destructor.
Definition at line 57 of file musiclrcphotomanagerwidget.cpp.
References m_gridLayout, and m_items.
Member Function Documentation
void MusicLrcPhotoWidget::addButtonClicked () slot
Add button clicked.
Definition at line 72 of file musiclrcphotomanagerwidget.cpp.
References addCellItem(), BACKGROUND_DIR_FULL, G_BACKGROUND_PTR, TTK::File::getOpenFileNames(), m_items, MAX_IMAGE_COUNT, name, MusicToastLabel::popup(), and SKN_FILE.
void MusicLrcPhotoWidget::addCellItem (const QString & path)
Create cell item by input data.
Definition at line 63 of file musiclrcphotomanagerwidget.cpp.
References m_gridLayout, m_items, MIN_ITEM_COUNT, and MusicLrcPhotoItem::updatePixmap().
Referenced by addButtonClicked(), and initialize().
void MusicLrcPhotoWidget::deleteButtonClicked () slot
Delete button clicked.
Definition at line 104 of file musiclrcphotomanagerwidget.cpp.
References G_BACKGROUND_PTR, MusicLrcPhotoItem::isSelected(), isValid(), m_gridLayout, m_items, MIN_ITEM_COUNT, MusicLrcPhotoItem::path(), MusicLrcPhotoItem::pathRef(), and MusicToastLabel::popup().
void MusicLrcPhotoWidget::exportButtonClicked () slot
Export button clicked.
Definition at line 136 of file musiclrcphotomanagerwidget.cpp.
References TTKDateTime::currentTimestamp(), TTK::File::getExistingDirectory(), isValid(), JPG_FILE, m_items, PNG_FILE, MusicToastLabel::popup(), qAsConst, TTK::Core::sleep(), TTK::String::suffix(), and TTK_DN_MS.
void MusicLrcPhotoWidget::initialize () private
Create all widget in layout.
Definition at line 184 of file musiclrcphotomanagerwidget.cpp.
References addCellItem(), and G_BACKGROUND_PTR.
Referenced by MusicLrcPhotoWidget().
bool MusicLrcPhotoWidget::isValid () const private
Check current selection is valid or not.
Definition at line 192 of file musiclrcphotomanagerwidget.cpp.
References m_items, and qAsConst.
Referenced by deleteButtonClicked(), and exportButtonClicked().
Member Data Documentation
QGridLayout* MusicLrcPhotoWidget::m_gridLayout private
Definition at line 120 of file musiclrcphotomanagerwidget.h.
Referenced by addCellItem(), deleteButtonClicked(), MusicLrcPhotoWidget(), and ~MusicLrcPhotoWidget().
QList<MusicLrcPhotoItem*> MusicLrcPhotoWidget::m_items private
Definition at line 121 of file musiclrcphotomanagerwidget.h.
Referenced by addButtonClicked(), addCellItem(), deleteButtonClicked(), exportButtonClicked(), isValid(), and ~MusicLrcPhotoWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcphotomanagerwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcphotomanagerwidget.cpp