TTKMusicplayer: QDlnaClientPrivate Class Reference
QDlnaClientPrivate Class Reference
The class of the dlna client private.
Public Member Functions
QDlnaClientPrivate ()
~QDlnaClientPrivate ()
void initData (const QString &data)
bool connectServer ()
Public Member Functions inherited from TTKPrivate< QDlnaClient >
TTKPrivate ()
virtual ~TTKPrivate ()
void setPublic (QDlnaClient *pub)
Public Attributes
bool m_isConnected
QDlnaXml * m_xml
QString m_serverIP
QString m_serverPort
QString m_smp
QString m_controlURL
QString m_friendlyName
QMap< QString, QDlnaService > m_services
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QDlnaClient >
QDlnaClient * ttk_q () const
Detailed Description
The class of the dlna client private.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 18 of file qdlnaclient.cpp.
Constructor & Destructor Documentation
QDlnaClientPrivate::QDlnaClientPrivate ()
Definition at line 37 of file qdlnaclient.cpp.
References m_isConnected, and m_xml.
QDlnaClientPrivate::~QDlnaClientPrivate ()
Definition at line 43 of file qdlnaclient.cpp.
References m_xml.
Member Function Documentation
bool QDlnaClientPrivate::connectServer ()
Definition at line 80 of file qdlnaclient.cpp.
References AVT_NAMES, AVTRANSPORT, FRIENS_NAMES, QDlnaXml::fromString(), QHelperDlna::GetResponseCode(), QDlnaService::isEmpty(), m_controlURL, m_friendlyName, m_isConnected, m_serverIP, m_serverPort, m_services, m_smp, m_xml, QHelperDlna::MakeRequest(), QHelperDlna::makeSocketGetReply(), name, QDlnaXml::readServiceTag(), QDlnaXml::readTagNameValue(), QHelperDlna::removeHttpHeader(), QDlnaXml::tagNameToLower(), and TTK_LOGGER_INFO.
void QDlnaClientPrivate::initData (const QString & data)
Definition at line 48 of file qdlnaclient.cpp.
References m_serverIP, m_serverPort, and m_smp.
Member Data Documentation
QString QDlnaClientPrivate::m_controlURL
Definition at line 31 of file qdlnaclient.cpp.
Referenced by connectServer().
QString QDlnaClientPrivate::m_friendlyName
Definition at line 32 of file qdlnaclient.cpp.
Referenced by connectServer().
bool QDlnaClientPrivate::m_isConnected
Definition at line 27 of file qdlnaclient.cpp.
Referenced by connectServer(), and QDlnaClientPrivate().
QString QDlnaClientPrivate::m_serverIP
Definition at line 30 of file qdlnaclient.cpp.
Referenced by connectServer(), and initData().
QString QDlnaClientPrivate::m_serverPort
Definition at line 30 of file qdlnaclient.cpp.
Referenced by connectServer(), and initData().
QMap<QString, QDlnaService> QDlnaClientPrivate::m_services
Definition at line 33 of file qdlnaclient.cpp.
Referenced by connectServer().
QString QDlnaClientPrivate::m_smp
Definition at line 31 of file qdlnaclient.cpp.
Referenced by connectServer(), and initData().
QDlnaXml* QDlnaClientPrivate::m_xml
Definition at line 29 of file qdlnaclient.cpp.
Referenced by connectServer(), QDlnaClientPrivate(), and ~QDlnaClientPrivate().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qdlna/qdlnaclient.cpp