TTKMusicPlayer: MusicSoundKMicroSearchTableWidget Class Reference
MusicSoundKMicroSearchTableWidget Class Reference
The class of the sound kmicro search table widget.
#include <musicsoundkmicrosearchwidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
virtual void itemDoubleClicked (int row, int column) overridefinal
virtual void removeItems () overridefinal
virtual void createSearchedItem (const MusicResultInfoItem &songItem) overridefinal
Public Slots inherited from MusicItemSearchTableWidget
virtual void itemCellClicked (int row, int column) override
virtual void removeItems () override
virtual void actionGroupClick (QAction *action)
void createFinishedItem ()
Public Slots inherited from MusicQueryTableWidget
virtual void itemDoubleClicked (int row, int column)=0
virtual void createSearchedItem (const MusicResultInfoItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool check)
void checkedItemsStatus (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void mediaUrlChanged (bool mv, const QString &url, const QString &lrcUrl)
Signals inherited from MusicQueryTableWidget
void songBufferToPlaylist (const MusicResultDataItem &songItem)
void restartSearchQuery (const QString &name)
Public Member Functions
MusicSoundKMicroSearchTableWidget (QWidget *parent=nullptr)
~MusicSoundKMicroSearchTableWidget ()
virtual void startSearchQuery (const QString &text) overridefinal
virtual void musicDownloadLocal (int row) overridefinal
void setQueryMovieFlag (bool flag)
Public Member Functions inherited from MusicItemSearchTableWidget
MusicItemSearchTableWidget (QWidget *parent=nullptr)
~MusicItemSearchTableWidget ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
virtual void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * getQueryInput () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
void dataDownloadPlay (int row)
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Private Attributes
bool m_queryMovieMode
Additional Inherited Members
Protected Member Functions inherited from MusicItemSearchTableWidget
virtual void resizeEvent (QResizeEvent *event) override
void createContextMenu (QMenu &menu)
QString randSimulation () const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicItemSearchTableWidget
MusicGifLabelWidget * m_loadingLabel
QActionGroup * m_actionGroup
MusicLabelDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
MusicCheckBoxDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the sound kmicro search table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicsoundkmicrosearchwidget.h.
Constructor & Destructor Documentation
MusicSoundKMicroSearchTableWidget::MusicSoundKMicroSearchTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicsoundkmicrosearchwidget.cpp.
References MusicAbstractTableWidget::m_backgroundColor, and MusicUIObject::MQSSBackgroundStyle02.
MusicSoundKMicroSearchTableWidget::~MusicSoundKMicroSearchTableWidget ()
Definition at line 29 of file musicsoundkmicrosearchwidget.cpp.
References removeItems().
Member Function Documentation
void MusicSoundKMicroSearchTableWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Definition at line 164 of file musicsoundkmicrosearchwidget.cpp.
References MusicItemSearchTableWidget::createContextMenu().
void MusicSoundKMicroSearchTableWidget::createSearchedItem (const MusicResultInfoItem & songItem) final override virtual slot
Create searched items.
Definition at line 118 of file musicsoundkmicrosearchwidget.cpp.
References MusicUtils::Widget::elidedText(), MusicAbstractTableWidget::m_backgroundColor, MusicResultInfoItem::m_singerName, MusicResultInfoItem::m_songName, MusicResultInfoItem::m_type, MusicUIObject::MQSSColor02, MUSIC_CHECK_ROLE, QtItemSetBackgroundColor, QtItemSetForegroundColor, and MusicItemSearchTableWidget::randSimulation().
void MusicSoundKMicroSearchTableWidget::dataDownloadPlay (int row) private
Data download to play.
Definition at line 149 of file musicsoundkmicrosearchwidget.cpp.
References MusicQueryTableWidget::m_networkRequest, m_queryMovieMode, mediaUrlChanged(), MusicToastLabel::popup(), and MusicAbstractQueryRequest::songInfoList().
Referenced by itemCellClicked(), and itemDoubleClicked().
void MusicSoundKMicroSearchTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 92 of file musicsoundkmicrosearchwidget.cpp.
References dataDownloadPlay(), and MusicItemSearchTableWidget::itemCellClicked().
void MusicSoundKMicroSearchTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 79 of file musicsoundkmicrosearchwidget.cpp.
References MusicAbstractTableWidget::itemCellEntered().
void MusicSoundKMicroSearchTableWidget::itemDoubleClicked (int row, int column) final override virtual slot
Table widget item cell double clicked.
Definition at line 102 of file musicsoundkmicrosearchwidget.cpp.
References dataDownloadPlay().
void MusicSoundKMicroSearchTableWidget::mediaUrlChanged (bool mv, const QString & url, const QString & lrcUrl) signal
Set current media url.
Referenced by dataDownloadPlay().
void MusicSoundKMicroSearchTableWidget::musicDownloadLocal (int row) final override virtual
Data download to local file.
Implements MusicQueryTableWidget.
Definition at line 60 of file musicsoundkmicrosearchwidget.cpp.
References MusicQueryTableWidget::m_networkRequest, m_queryMovieMode, MusicAbstractQueryRequest::Movie, MusicAbstractQueryRequest::Music, MusicToastLabel::popup(), and MusicAbstractQueryRequest::songInfoList().
void MusicSoundKMicroSearchTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 112 of file musicsoundkmicrosearchwidget.cpp.
References MusicItemSearchTableWidget::removeItems().
Referenced by startSearchQuery(), and ~MusicSoundKMicroSearchTableWidget().
void MusicSoundKMicroSearchTableWidget::setQueryMovieFlag (bool flag)
Set query Movie flag.
Definition at line 74 of file musicsoundkmicrosearchwidget.cpp.
References m_queryMovieMode.
Referenced by MusicSoundKMicroSearchWidget::startToSearch().
void MusicSoundKMicroSearchTableWidget::startSearchQuery (const QString & text) final override virtual
Start search query by text.
Reimplemented from MusicItemSearchTableWidget.
Definition at line 34 of file musicsoundkmicrosearchwidget.cpp.
References MusicItemSearchTableWidget::createFinishedItem(), G_NETWORK_PTR, MusicItemSearchTableWidget::m_loadingLabel, MusicQueryTableWidget::m_networkRequest, m_queryMovieMode, MusicAbstractQueryRequest::Movie, MusicAbstractQueryRequest::Music, removeItems(), MusicGifLabelWidget::run(), MusicQueryTableWidget::setQueryInput(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicSoundKMicroSearchWidget::startToSearch().
Member Data Documentation
bool MusicSoundKMicroSearchTableWidget::m_queryMovieMode private
Definition at line 91 of file musicsoundkmicrosearchwidget.h.
Referenced by dataDownloadPlay(), musicDownloadLocal(), setQueryMovieFlag(), and startSearchQuery().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrosearchwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrosearchwidget.cpp