TTKMusicplayer: filter Namespace Reference
filter Namespace Reference
Classes
struct alloc_t
class auto_t
class bitmap_t
class buffer_t
class filter_t
struct pair_t
Typedefs
typedef void(* mark_t) (filter_t &, long)
typedef void(* blur_t) (bitmap_t &, filter_t &)
Functions
template<typename T1 , typename T2 >
T1 Clamp (T2 n)
template<typename T >
T Diamet (T r)
template<typename T >
bool Equal (T n1, T n2)
template<typename T >
T Edge (T i, T x, T w)
void Normalization (filter_t &kernel)
void Blur1D (bitmap_t &bitmap, filter_t &kernel)
void Blur2D (bitmap_t &bitmap, filter_t &kernel)
void Average (filter_t &kernel, long radius)
void Linear (filter_t &kernel, long radius)
void Gauss (filter_t &kernel, long radius)
void Gauss2 (filter_t &kernel, long radius)
bool Filter (mark_t mark, blur_t blur, bitmap_t &bitmap, long radius)
bool Filter (pair_t &pair, bitmap_t &bitmap, long radius)
Variables
static const double PI = 3.141592653589793
Typedef Documentation
typedef void(* filter::blur_t) (bitmap_t &, filter_t &)
Definition at line 298 of file imagefilter.h.
typedef void(* filter::mark_t) (filter_t &, long)
Definition at line 297 of file imagefilter.h.
Function Documentation
void filter::Average (filter_t & kernel, long radius)
Definition at line 243 of file imagefilter.h.
References Diamet(), filter::filter_t::set(), and filter::auto_t< TypeT, AllocT >::size().
Referenced by QImageWrap::GaussFilter().
void filter::Blur1D (bitmap_t & bitmap, filter_t & kernel)
Definition at line 166 of file imagefilter.h.
References Edge(), filter::bitmap_t::h(), Normalization(), filter::filter_t::radius(), and filter::bitmap_t::w().
Referenced by QImageWrap::GaussFilter().
void filter::Blur2D (bitmap_t & bitmap, filter_t & kernel)
Definition at line 208 of file imagefilter.h.
References Edge(), filter::bitmap_t::h(), Normalization(), filter::filter_t::radius(), filter::auto_t< TypeT, AllocT >::size(), and filter::bitmap_t::w().
Referenced by QImageWrap::GaussFilter().
template<typename T1 , typename T2 > T1 filter::Clamp (T2 n)
Definition at line 136 of file imagefilter.h.
template<typename T > T filter::Diamet (T r)
Definition at line 139 of file imagefilter.h.
Referenced by Average(), Gauss(), Gauss2(), and Linear().
template<typename T > T filter::Edge (T i, T x, T w)
Definition at line 145 of file imagefilter.h.
Referenced by Blur1D(), and Blur2D().
template<typename T > bool filter::Equal (T n1, T n2)
Definition at line 142 of file imagefilter.h.
Referenced by Normalization().
bool filter::Filter (mark_t mark, blur_t blur, bitmap_t & bitmap, long radius)
Definition at line 300 of file imagefilter.h.
Referenced by Filter(), and QImageWrap::GaussFilter().
bool filter::Filter (pair_t & pair, bitmap_t & bitmap, long radius)
Definition at line 317 of file imagefilter.h.
References filter::pair_t::blur, Filter(), and filter::pair_t::mark.
void filter::Gauss (filter_t & kernel, long radius)
Definition at line 264 of file imagefilter.h.
References Diamet(), filter::filter_t::radius(), and filter::filter_t::set().
Referenced by QImageWrap::GaussFilter().
void filter::Gauss2 (filter_t & kernel, long radius)
Definition at line 278 of file imagefilter.h.
References Diamet(), PI, filter::filter_t::radius(), and filter::filter_t::set().
Referenced by QImageWrap::GaussFilter().
void filter::Linear (filter_t & kernel, long radius)
Definition at line 253 of file imagefilter.h.
References Diamet(), filter::filter_t::radius(), filter::filter_t::set(), and filter::auto_t< TypeT, AllocT >::size().
Referenced by MusicLrcMakerWidget::createMainWidget(), QImageWrap::GaussFilter(), MusicBarrageAnimation::init(), MusicAnimationStackedWidget::MusicAnimationStackedWidget(), MusicLayoutAnimationWidget::MusicLayoutAnimationWidget(), and MusicTransitionAnimationLabel::MusicTransitionAnimationLabel().
void filter::Normalization (filter_t & kernel)
Definition at line 154 of file imagefilter.h.
References Equal(), and filter::auto_t< TypeT, AllocT >::size().
Referenced by Blur1D(), and Blur2D().
Variable Documentation
const double filter::PI = 3.141592653589793 static
Definition at line 131 of file imagefilter.h.
Referenced by Gauss2().