TTKMusicPlayer: MusicVideoSearchTableWidget Class Reference
MusicVideoSearchTableWidget Class Reference
The class of the video search table widget.
#include <musicvideosearchtablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
virtual void itemDoubleClicked (int row, int column) overridefinal
virtual void removeItems () overridefinal
virtual void createSearchedItem (const MusicResultInfoItem &songItem) overridefinal
void musicMediaInfo (MusicObject::MusicSongPropertyList &props)
void downloadLocalFromControl ()
Public Slots inherited from MusicItemSearchTableWidget
virtual void itemCellClicked (int row, int column) override
virtual void removeItems () override
virtual void actionGroupClick (QAction *action)
void createFinishedItem ()
Public Slots inherited from MusicQueryTableWidget
virtual void itemDoubleClicked (int row, int column)=0
virtual void createSearchedItem (const MusicResultInfoItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool check)
void checkedItemsStatus (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void mediaUrlPathChanged (const MusicVideoItem &item)
Signals inherited from MusicQueryTableWidget
void songBufferToPlaylist (const MusicResultDataItem &songItem)
void restartSearchQuery (const QString &name)
Public Member Functions
MusicVideoSearchTableWidget (QWidget *parent=nullptr)
~MusicVideoSearchTableWidget ()
virtual void startSearchQuery (const QString &text) overridefinal
virtual void musicDownloadLocal (int row) overridefinal
void startSearchSingleQuery (const QString &text)
void startSearchSingleQuery (const QVariant &data)
void resizeSection (int delta)
Public Member Functions inherited from MusicItemSearchTableWidget
MusicItemSearchTableWidget (QWidget *parent=nullptr)
~MusicItemSearchTableWidget ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
virtual void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * getQueryInput () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
void downloadLocalMovie (int row)
Private Attributes
QString m_currentSongName
bool m_singleRadioMode
Additional Inherited Members
Protected Member Functions inherited from MusicItemSearchTableWidget
virtual void resizeEvent (QResizeEvent *event) override
void createContextMenu (QMenu &menu)
QString randSimulation () const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicItemSearchTableWidget
MusicGifLabelWidget * m_loadingLabel
QActionGroup * m_actionGroup
MusicLabelDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
MusicCheckBoxDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the video search table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 41 of file musicvideosearchtablewidget.h.
Constructor & Destructor Documentation
MusicVideoSearchTableWidget::MusicVideoSearchTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 9 of file musicvideosearchtablewidget.cpp.
References G_CONNECTION_PTR, TTKObject::initRandom(), and resizeSection().
MusicVideoSearchTableWidget::~MusicVideoSearchTableWidget ()
Definition at line 21 of file musicvideosearchtablewidget.cpp.
References G_CONNECTION_PTR, and removeItems().
Member Function Documentation
void MusicVideoSearchTableWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Definition at line 247 of file musicvideosearchtablewidget.cpp.
References MusicItemSearchTableWidget::createContextMenu().
void MusicVideoSearchTableWidget::createSearchedItem (const MusicResultInfoItem & songItem) final override virtual slot
Create searched items.
Definition at line 171 of file musicvideosearchtablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicAbstractTableWidget::m_backgroundColor, MusicResultInfoItem::m_duration, MusicResultInfoItem::m_singerName, MusicResultInfoItem::m_songName, MusicResultInfoItem::m_type, MusicUIObject::MQSSColor02, MUSIC_CHECK_ROLE, QtItemSetBackgroundColor, QtItemSetForegroundColor, and MusicItemSearchTableWidget::randSimulation().
void MusicVideoSearchTableWidget::downloadLocalFromControl () slot
Download current mv by controller.
Definition at line 232 of file musicvideosearchtablewidget.cpp.
References downloadLocalMovie(), MusicAbstractTableWidget::m_previousClickRow, and m_singleRadioMode.
Referenced by MusicVideoPlayWidget::downloadButtonClicked().
void MusicVideoSearchTableWidget::downloadLocalMovie (int row) private
Download movie to local file by index.
Definition at line 256 of file musicvideosearchtablewidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::Movie, MusicDownloadWidget::setSongName(), MusicAbstractMoveWidget::show(), and MusicAbstractQueryRequest::songInfoList().
Referenced by downloadLocalFromControl(), and musicDownloadLocal().
void MusicVideoSearchTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 132 of file musicvideosearchtablewidget.cpp.
References MusicItemSearchTableWidget::itemCellClicked(), itemDoubleClicked(), musicDownloadLocal(), and TTK_HIGH_LEVEL.
void MusicVideoSearchTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 119 of file musicvideosearchtablewidget.cpp.
References MusicAbstractTableWidget::itemCellEntered().
void MusicVideoSearchTableWidget::itemDoubleClicked (int row, int column) final override virtual slot
Table widget item cell double clicked.
Definition at line 144 of file musicvideosearchtablewidget.cpp.
References MusicVideoItem::m_id, MusicVideoItem::m_name, MusicQueryTableWidget::m_networkRequest, MusicVideoItem::m_server, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songProps, MusicVideoItem::m_url, MusicObject::MusicSongProperty::m_url, mediaUrlPathChanged(), MusicAbstractQueryRequest::queryServer(), and MusicAbstractQueryRequest::songInfoList().
Referenced by itemCellClicked().
void MusicVideoSearchTableWidget::mediaUrlPathChanged (const MusicVideoItem & item) signal
Set current media name and url to play.
Referenced by itemDoubleClicked().
void MusicVideoSearchTableWidget::musicDownloadLocal (int row) final override virtual
Data download to local file.
Implements MusicQueryTableWidget.
Definition at line 44 of file musicvideosearchtablewidget.cpp.
References downloadLocalMovie(), m_singleRadioMode, and MusicToastLabel::popup().
Referenced by itemCellClicked().
void MusicVideoSearchTableWidget::musicMediaInfo (MusicObject::MusicSongPropertyList & props) slot
Get music media information data.
Definition at line 220 of file musicvideosearchtablewidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractTableWidget::m_previousClickRow, m_singleRadioMode, and MusicAbstractQueryRequest::songInfoList().
void MusicVideoSearchTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 165 of file musicvideosearchtablewidget.cpp.
References MusicItemSearchTableWidget::removeItems().
Referenced by startSearchQuery(), startSearchSingleQuery(), and ~MusicVideoSearchTableWidget().
void MusicVideoSearchTableWidget::resizeSection (int delta)
Resize section bound by resize called.
Definition at line 95 of file musicvideosearchtablewidget.cpp.
References MusicUtils::Widget::elidedText().
Referenced by MusicVideoSearchTableWidget(), and MusicVideoPlayWidget::resizeGeometry().
void MusicVideoSearchTableWidget::startSearchQuery (const QString & text) final override virtual
Start search query by text.
Reimplemented from MusicItemSearchTableWidget.
Definition at line 27 of file musicvideosearchtablewidget.cpp.
References MusicItemSearchTableWidget::createFinishedItem(), G_DOWNLOAD_QUERY_PTR, G_NETWORK_PTR, MusicItemSearchTableWidget::m_loadingLabel, MusicQueryTableWidget::m_networkRequest, m_singleRadioMode, MusicAbstractQueryRequest::Movie, removeItems(), MusicGifLabelWidget::run(), MusicQueryTableWidget::setQueryInput(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicVideoPlayWidget::videoResearchButtonSearched().
void MusicVideoSearchTableWidget::startSearchSingleQuery (const QString & text)
Start search query by given id.
Definition at line 61 of file musicvideosearchtablewidget.cpp.
References MusicItemSearchTableWidget::createFinishedItem(), G_DOWNLOAD_QUERY_PTR, G_NETWORK_PTR, MusicItemSearchTableWidget::m_loadingLabel, MusicQueryTableWidget::m_networkRequest, m_singleRadioMode, MusicAbstractQueryRequest::Movie, removeItems(), MusicGifLabelWidget::run(), MusicQueryTableWidget::setQueryInput(), MusicAbstractQueryRequest::setQueryType(), and MusicAbstractQueryRequest::startToSingleSearch().
Referenced by MusicVideoPlayWidget::startSearchSingleQuery(), and MusicVideoPlayWidget::videoResearchButtonSearched().
void MusicVideoSearchTableWidget::startSearchSingleQuery (const QVariant & data)
Start search query by given data.
Definition at line 79 of file musicvideosearchtablewidget.cpp.
References MusicItemSearchTableWidget::createFinishedItem(), G_DOWNLOAD_QUERY_PTR, G_NETWORK_PTR, m_singleRadioMode, removeItems(), MusicQueryTableWidget::setQueryInput(), and MusicAbstractQueryRequest::setSongInfoList().
Member Data Documentation
QString MusicVideoSearchTableWidget::m_currentSongName private
Definition at line 120 of file musicvideosearchtablewidget.h.
bool MusicVideoSearchTableWidget::m_singleRadioMode private
Definition at line 121 of file musicvideosearchtablewidget.h.
Referenced by downloadLocalFromControl(), musicDownloadLocal(), musicMediaInfo(), startSearchQuery(), and startSearchSingleQuery().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideosearchtablewidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideosearchtablewidget.cpp