TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/bitstream.c File Reference
bitstream.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "bitstream.h"
Functions
BitStream * BitStream_new (void)
static int BitStream_allocate (BitStream *bstream, int length)
static BitStream * BitStream_newFromNum (int bits, unsigned int num)
static BitStream * BitStream_newFromBytes (int size, unsigned char *data)
int BitStream_append (BitStream *bstream, BitStream *arg)
int BitStream_appendNum (BitStream *bstream, int bits, unsigned int num)
int BitStream_appendBytes (BitStream *bstream, int size, unsigned char *data)
unsigned char * BitStream_toByte (BitStream *bstream)
void BitStream_free (BitStream *bstream)
Function Documentation
static int BitStream_allocate (BitStream * bstream, int length) static
Definition at line 43 of file bitstream.c.
References BitStream::data, and BitStream::length.
Referenced by BitStream_append(), BitStream_newFromBytes(), and BitStream_newFromNum().
int BitStream_append (BitStream * bstream, BitStream * arg)
Definition at line 130 of file bitstream.c.
References BitStream_allocate(), BitStream::data, and BitStream::length.
Referenced by BitStream_appendBytes(), BitStream_appendNum(), QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), QRinput_encodeBitStream(), and QRinput_mergeBitStream().
int BitStream_appendBytes (BitStream * bstream, int size, unsigned char * data)
Definition at line 183 of file bitstream.c.
References BitStream_append(), BitStream_free(), and BitStream_newFromBytes().
Referenced by QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), QRinput_encodeMode8(), and QRinput_encodeModeFNC1Second().
int BitStream_appendNum (BitStream * bstream, int bits, unsigned int num)
Definition at line 165 of file bitstream.c.
References BitStream_append(), BitStream_free(), and BitStream_newFromNum().
Referenced by QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), QRinput_encodeMode8(), QRinput_encodeModeAn(), QRinput_encodeModeECI(), QRinput_encodeModeFNC1Second(), QRinput_encodeModeKanji(), QRinput_encodeModeNum(), and QRinput_encodeModeStructure().
void BitStream_free (BitStream * bstream)
Definition at line 243 of file bitstream.c.
References BitStream::data.
Referenced by BitStream_appendBytes(), BitStream_appendNum(), BitStream_newFromBytes(), BitStream_newFromNum(), QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), QRinput_encodeBitStream(), QRinput_encodeMode8(), QRinput_encodeModeAn(), QRinput_encodeModeECI(), QRinput_encodeModeFNC1Second(), QRinput_encodeModeKanji(), QRinput_encodeModeNum(), QRinput_encodeModeStructure(), QRinput_getBitStream(), QRinput_getByteStream(), QRinput_List_freeEntry(), and QRinput_mergeBitStream().
BitStream* BitStream_new (void)
Definition at line 29 of file bitstream.c.
References BitStream::data, and BitStream::length.
Referenced by BitStream_newFromBytes(), BitStream_newFromNum(), QRinput_appendPaddingBit(), QRinput_appendPaddingBitMQR(), QRinput_encodeBitStream(), QRinput_encodeMode8(), QRinput_encodeModeAn(), QRinput_encodeModeECI(), QRinput_encodeModeFNC1Second(), QRinput_encodeModeKanji(), QRinput_encodeModeNum(), QRinput_encodeModeStructure(), and QRinput_mergeBitStream().
static BitStream* BitStream_newFromBytes (int size, unsigned char * data) static
Definition at line 97 of file bitstream.c.
References BitStream_allocate(), BitStream_free(), BitStream_new(), and BitStream::data.
Referenced by BitStream_appendBytes().
static BitStream* BitStream_newFromNum (int bits, unsigned int num) static
Definition at line 66 of file bitstream.c.
References BitStream_allocate(), BitStream_free(), BitStream_new(), and BitStream::data.
Referenced by BitStream_appendNum().
unsigned char* BitStream_toByte (BitStream * bstream)
Definition at line 201 of file bitstream.c.
References BitStream_size, and BitStream::data.
Referenced by QRinput_getByteStream().