TTKMusicPlayer: MusicLrcPhotoItem Class Reference
MusicLrcPhotoItem Class Reference
The class of the lrc photo pixmap item.
#include <musiclrcphotomanagerwidget.h>
Public Member Functions
MusicLrcPhotoItem (QWidget *parent=nullptr)
void updatePixmap (const QString &path)
void setSelected (bool v)
bool isSelected () const
QString path () const
QString & pathRef ()
Private Member Functions
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void paintEvent (QPaintEvent *event) overridefinal
Private Attributes
QString m_path
bool m_isSelected
Detailed Description
The class of the lrc photo pixmap item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musiclrcphotomanagerwidget.h.
Constructor & Destructor Documentation
MusicLrcPhotoItem::MusicLrcPhotoItem (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musiclrcphotomanagerwidget.cpp.
Member Function Documentation
bool MusicLrcPhotoItem::isSelected () const inline
Get current selected item state.
Definition at line 50 of file musiclrcphotomanagerwidget.h.
Referenced by MusicLrcPhotoWidget::deleteButtonClicked().
void MusicLrcPhotoItem::mousePressEvent (QMouseEvent * event) final override private virtual
Override the widget event.
Definition at line 27 of file musiclrcphotomanagerwidget.cpp.
References m_isSelected.
void MusicLrcPhotoItem::paintEvent (QPaintEvent * event) final override private virtual
Definition at line 34 of file musiclrcphotomanagerwidget.cpp.
References m_isSelected.
QString MusicLrcPhotoItem::path () const inline
Get current item apth.
Definition at line 55 of file musiclrcphotomanagerwidget.h.
Referenced by MusicLrcPhotoWidget::deleteButtonClicked(), and updatePixmap().
QString& MusicLrcPhotoItem::pathRef () inline
Get current item apth.
Definition at line 59 of file musiclrcphotomanagerwidget.h.
Referenced by MusicLrcPhotoWidget::deleteButtonClicked().
void MusicLrcPhotoItem::setSelected (bool v)
Select the current item.
Definition at line 22 of file musiclrcphotomanagerwidget.cpp.
References m_isSelected.
void MusicLrcPhotoItem::updatePixmap (const QString & path)
Update pix image.
Definition at line 16 of file musiclrcphotomanagerwidget.cpp.
References m_path, and path().
Referenced by MusicLrcPhotoWidget::addCellItem().
Member Data Documentation
bool MusicLrcPhotoItem::m_isSelected private
Definition at line 69 of file musiclrcphotomanagerwidget.h.
Referenced by mousePressEvent(), paintEvent(), and setSelected().
QString MusicLrcPhotoItem::m_path private
Definition at line 68 of file musiclrcphotomanagerwidget.h.
Referenced by updatePixmap().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcphotomanagerwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcphotomanagerwidget.cpp