TTKMusicPlayer: std Namespace Reference
std Namespace Reference
Classes
struct _MakeUnique
struct _MakeUnique< _Tp[]>
struct _MakeUnique< _Tp[_Bound]>
struct hash< TTKStringView >
struct hash< TTKU16StringView >
struct hash< TTKU32StringView >
struct hash< TTKWStringView >
Typedefs
template<typename _Tp >
using remove_extent_t = typename remove_extent< _Tp >::type
Alias template for remove_extent.
template<typename _Tp >
using remove_all_extents_t = typename remove_all_extents< _Tp >::type
Alias template for remove_all_extents.
using any = TTKAny
template<typename T >
using optional = TTKOptional< T >
template<typename T >
using shared_ptr = TTKSharedPtr< T >
using spin_lock = TTKSpinLock
using spin_lock_guard = TTKSpinLockGuard
using spinlock = spin_lock
using spinlock_guard = spin_lock_guard
using string_view = TTKStringView
using wstring_view = TTKWStringView
using u16string_view = TTKU16StringView
using u32string_view = TTKU32StringView
template<class _Key , class _Value >
using unsorted_map = TTKUnsortedMap< _Key, _Value >
template<typename... Types>
using variant = TTKVariant< Types...>
Functions
template<typename _Tp , typename _Up = _Tp>
_Tp exchange (_Tp &__obj, _Up &&__new_val) noexcept
Assign __new_val to __obj and return its previous value.
template<typename _Tp >
constexpr const _Tp & clamp (const _Tp &_Val, const _Tp &_Min_val, const _Tp &_Max_val) noexcept
template<typename T >
Q_DECL_CONSTEXPR std::add_const< T >::type & as_const (T &t) noexcept
template<typename T >
void as_const (const T &&)=delete
void swap (TTKAny &left, TTKAny &right) noexcept
template<typename _Tp , typename... _Args>
_MakeUnique< _Tp >::__single_object make_unique (_Args &&...__args)
std::make_unique for single objects
template<typename _Tp >
_MakeUnique< _Tp >::__array make_unique (size_t __num)
std::make_unique for arrays of unknown bound
template<typename _Tp , typename... _Args>
_MakeUnique< _Tp >::__invalid_type make_unique (_Args &&...)=delete
Disable std::make_unique for arrays of known bound.
template<class _Key , class _Value >
void swap (TTKUnsortedMap< _Key, _Value > &left, TTKUnsortedMap< _Key, _Value > &right) noexcept
Typedef Documentation
using std::any = typedef TTKAny
Definition at line 230 of file ttkany.h.
template<typename T > using std::optional = typedef TTKOptional<T>
Definition at line 173 of file ttkoptional.h.
template<typename _Tp > using std::remove_all_extents_t = typedef typename remove_all_extents<_Tp>::type
Alias template for remove_all_extents.
Definition at line 48 of file ttkcompat.h.
template<typename _Tp > using std::remove_extent_t = typedef typename remove_extent<_Tp>::type
Alias template for remove_extent.
Definition at line 44 of file ttkcompat.h.
template<typename T > using std::shared_ptr = typedef TTKSharedPtr<T>
Definition at line 213 of file ttksmartptr.h.
using std::spin_lock = typedef TTKSpinLock
Definition at line 85 of file ttkspinlock.h.
using std::spin_lock_guard = typedef TTKSpinLockGuard
Definition at line 86 of file ttkspinlock.h.
using std::spinlock = typedef spin_lock
Definition at line 88 of file ttkspinlock.h.
using std::spinlock_guard = typedef spin_lock_guard
Definition at line 89 of file ttkspinlock.h.
using std::string_view = typedef TTKStringView
Definition at line 579 of file ttkstringview.h.
using std::u16string_view = typedef TTKU16StringView
Definition at line 581 of file ttkstringview.h.
using std::u32string_view = typedef TTKU32StringView
Definition at line 582 of file ttkstringview.h.
template<class _Key , class _Value > using std::unsorted_map = typedef TTKUnsortedMap<_Key, _Value>
Definition at line 433 of file ttkunsortedmap.h.
template<typename... Types> using std::variant = typedef TTKVariant<Types...>
Definition at line 253 of file ttkvariant.h.
using std::wstring_view = typedef TTKWStringView
Definition at line 580 of file ttkstringview.h.
Function Documentation
template<typename T > Q_DECL_CONSTEXPR std::add_const< T >::type & std::as_const (T & t) noexcept
Definition at line 49 of file ttkqtglobal.h.
template<typename T > void std::as_const (const T &&) delete
template<typename _Tp > constexpr const _Tp& std::clamp (const _Tp & _Val, const _Tp & _Min_val, const _Tp & _Max_val) inline noexcept
Definition at line 64 of file ttkcompat.h.
References TTK::max(), and TTK::min().
template<typename _Tp , typename _Up = _Tp> _Tp std::exchange (_Tp & __obj, _Up && __new_val) inline noexcept
Assign __new_val to __obj and return its previous value.
Definition at line 54 of file ttkcompat.h.
Referenced by TTKAny::swap().
template<typename _Tp , typename... _Args> _MakeUnique<_Tp>::__single_object std::make_unique (_Args &&... __args) inline
std::make_unique for single objects
Definition at line 49 of file ttksmartptr.h.
template<typename _Tp > _MakeUnique<_Tp>::__array std::make_unique (size_t __num) inline
std::make_unique for arrays of unknown bound
Definition at line 56 of file ttksmartptr.h.
template<typename _Tp , typename... _Args> _MakeUnique<_Tp>::__invalid_type std::make_unique (_Args && ...) inline delete
Disable std::make_unique for arrays of known bound.
void std::swap (TTKAny & left, TTKAny & right) inline noexcept
Definition at line 224 of file ttkany.h.
Referenced by TTKConcurrentQueue< T >::clear(), and MusicSongMeta::operator=().
template<class _Key , class _Value > void std::swap (TTKUnsortedMap< _Key, _Value > & left, TTKUnsortedMap< _Key, _Value > & right) inline noexcept
Definition at line 427 of file ttkunsortedmap.h.