TTKMusicPlayer: MusicAbstractTranslationRequest Class Reference
MusicAbstractTranslationRequest Class Reference abstract
The class of the translation words request.
#include <musicabstracttranslationrequest.h>
Public Types
enum Language { Language::Auto, Language::Chinese }
Public Member Functions
MusicAbstractTranslationRequest (QObject *parent=nullptr)
virtual void deleteAll () overridefinal
virtual void startToRequest (const QString &data)=0
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the translation words request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicabstracttranslationrequest.h.
Member Enumeration Documentation
enum MusicAbstractTranslationRequest::Language strong
Enumerator
Auto
Chinese
Definition at line 32 of file musicabstracttranslationrequest.h.
Constructor & Destructor Documentation
MusicAbstractTranslationRequest::MusicAbstractTranslationRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musicabstracttranslationrequest.cpp.
Member Function Documentation
void MusicAbstractTranslationRequest::deleteAll () final override virtual
Release the network object.
Reimplemented from TTKAbstractNetwork.
Definition at line 9 of file musicabstracttranslationrequest.cpp.
References TTKAbstractNetwork::deleteAll().
Referenced by MusicBDTranslationRequest::downLoadFinished(), MusicYDTranslationRequest::downLoadFinished(), MusicWYTranslationRequest::downLoadFinished(), MusicBingTranslationRequest::downLoadFinished(), MusicWYTranslationRequest::startToRequest(), MusicBingTranslationRequest::startToRequest(), and MusicYDTranslationRequest::startToRequest().
virtual void MusicAbstractTranslationRequest::startToRequest (const QString & data) pure virtual
Start to download translation data. Subclass should implement this function.
Implemented in MusicBDTranslationRequest, MusicBingTranslationRequest, MusicWYTranslationRequest, and MusicYDTranslationRequest.
Referenced by MusicTranslationRequest::findAllPlugins().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/translation/musicabstracttranslationrequest.h
TTKModule/TTKCore/musicNetworkKits/translation/musicabstracttranslationrequest.cpp