TTKMusicplayer: Base64 Namespace Reference
Base64 Namespace Reference
Functions
MUSIC_EXTRAS_EXPORT std::string base64Encode (const unsigned char *bytes, unsigned int len)
MUSIC_EXTRAS_EXPORT std::string base64Decode (const std::string &bytes)
Function Documentation
std::string Base64::base64Decode (const std::string & bytes)
Base64 dncode.
Definition at line 60 of file base64.cpp.
References base64_chars, and isBase64().
Referenced by QDesWrap::decrypt(), QAesWrap::decryptCBC(), QAesWrap::decryptECB(), and MusicCryptographicHash::xxteaDecrypt().
std::string Base64::base64Encode (const unsigned char * bytes, unsigned int len)
Base64 encode.
Definition at line 10 of file base64.cpp.
References base64_chars.
Referenced by QDesWrap::encrypt(), QAesWrap::encryptCBC(), QAesWrap::encryptECB(), and MusicCryptographicHash::xxteaEncrypt().