TTKMusicplayer: MusicWebMVRadioQueryCategoryItem Class Reference
MusicWebMVRadioQueryCategoryItem Class Reference
The class of the music mv category item.
#include <musicwebmvradioquerycategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicResultsCategoryItem &category)
Public Member Functions
MusicWebMVRadioQueryCategoryItem (QWidget *parent=nullptr)
void setCategory (const MusicResultsCategory &category)
Protected Attributes
MusicResultsCategory m_category
Detailed Description
The class of the music mv category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwebmvradioquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioQueryCategoryItem::MusicWebMVRadioQueryCategoryItem (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicwebmvradioquerycategorypopwidget.cpp.
Member Function Documentation
void MusicWebMVRadioQueryCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 48 of file musicwebmvradioquerycategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicResultsCategory::m_items.
Referenced by setCategory().
void MusicWebMVRadioQueryCategoryItem::categoryChanged (const MusicResultsCategoryItem & category) signal
Current category changed.
Referenced by buttonClicked().
void MusicWebMVRadioQueryCategoryItem::setCategory (const MusicResultsCategory & category)
Set current category.
Definition at line 16 of file musicwebmvradioquerycategorypopwidget.cpp.
References buttonClicked(), ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicResultsCategory::m_category, m_category, MusicResultsCategory::m_items, MusicClickedGroup::mapped(), MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSColorStyle08, and MusicUIObject::MQSSFontStyle03.
Referenced by MusicWebMVRadioQueryCategoryPopWidget::setCategory().
Member Data Documentation
MusicResultsCategory MusicWebMVRadioQueryCategoryItem::m_category protected
Definition at line 56 of file musicwebmvradioquerycategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerycategorypopwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioquerycategorypopwidget.cpp