TTKMusicplayer: MusicApplicationObject Class Reference
MusicApplicationObject Class Reference
The class of the app object widget.
#include <musicapplicationobject.h>
Public Slots
void windowCloseAnimationFinished ()
void musicAboutUs ()
void musicBugReportView ()
void musicVersionUpdate ()
void musicTimerWidget ()
void musicSpectrumWidget ()
void musicSetWindowToTop ()
void musicResetWindow ()
void musicToolSetsParameter ()
void musicDeviceNameChanged (const QString &name)
void musicDeviceChanged (bool state)
void musicSetEqualizer ()
void musicSetSoundEffect ()
void musicEffectChanged ()
Signals
void enhancedMusicChanged (int type)
Public Member Functions
MusicApplicationObject (QObject *parent=nullptr)
~MusicApplicationObject ()
bool getWindowToTop () const
bool isLastedVersion () const
void loadNetWorkSetting ()
void applySettingParameter ()
void windowCloseAnimation ()
void soureUpdateCheck ()
void sideAnimationByOn ()
void sideAnimationByOff ()
void sideAnimationReset ()
Static Public Member Functions
static MusicApplicationObject * instance ()
Protected Member Functions
bool closeCurrentEqualizer ()
void cleanUp ()
Protected Attributes
bool m_setWindowToTop
bool m_leftSideByOn
bool m_rightSideByOn
QPropertyAnimation * m_quitAnimation
QPropertyAnimation * m_sideAnimation
MusicTimerAutoObject * m_musicTimerAutoObject
MusicMobileDevicesWidget * m_mobileDeviceWidget
QDeviceWatcher * m_deviceWatcher
QWidget * m_quitContainer
MusicSourceUpdateRequest * m_sourceUpdatehread
MusicDownloadCounterPVRequest * m_counterPVThread
MusicScreenSaverBackgroundWidget * m_screenSaverWidget
Static Protected Attributes
static MusicApplicationObject * m_instance = nullptr
Detailed Description
The class of the app object widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 36 of file musicapplicationobject.h.
Constructor & Destructor Documentation
MusicApplicationObject::MusicApplicationObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 40 of file musicapplicationobject.cpp.
References QDeviceWatcher::appendEventReceiver(), m_counterPVThread, m_deviceWatcher, m_instance, m_mobileDeviceWidget, m_musicTimerAutoObject, m_quitAnimation, m_quitContainer, m_screenSaverWidget, m_setWindowToTop, m_sideAnimation, m_sourceUpdatehread, MT_MS, musicDeviceChanged(), musicDeviceNameChanged(), musicResetWindow(), musicToolSetsParameter(), and QDeviceWatcher::start().
MusicApplicationObject::~MusicApplicationObject ()
Definition at line 71 of file musicapplicationobject.cpp.
References cleanUp(), m_counterPVThread, m_deviceWatcher, m_mobileDeviceWidget, m_musicTimerAutoObject, m_quitAnimation, m_quitContainer, m_screenSaverWidget, m_sideAnimation, and m_sourceUpdatehread.
Member Function Documentation
void MusicApplicationObject::applySettingParameter ()
Apply settings parameters.
Definition at line 110 of file musicapplicationobject.cpp.
References MusicScreenSaverBackgroundWidget::applySettingParameter(), MusicSettingManager::FileAssociation, m_screenSaverWidget, and M_SETTING_PTR.
Referenced by MusicApplication::applySettingParameter(), MusicScreenSaverWidget::caseButtonOnAndOff(), MusicScreenSaverWidget::inputDataChanged(), MusicScreenSaverWidget::itemHasClicked(), and MusicApplication::readXMLConfigFromText().
void MusicApplicationObject::cleanUp () protected
Something temp clean up.
remove daily pic theme
other remove in ttkdumper
Definition at line 450 of file musicapplicationobject.cpp.
References CACHE_DIR_FULL, MUSIC_DAILY_DIR, MusicUtils::File::removeRecursively(), and TTK_STRCAT.
Referenced by ~MusicApplicationObject().
bool MusicApplicationObject::closeCurrentEqualizer () protected
Close current equalizer.
Definition at line 434 of file musicapplicationobject.cpp.
References MusicSettingManager::EnhancedMusic, enhancedMusicChanged(), MusicMessageBox::exec(), M_SETTING_PTR, and MusicMessageBox::setText().
Referenced by musicSetEqualizer(), and musicSetSoundEffect().
void MusicApplicationObject::enhancedMusicChanged (int type) signal
Set enhanced music config changed.
Referenced by closeCurrentEqualizer().
bool MusicApplicationObject::getWindowToTop () const inline
Get current window is to top.
Definition at line 55 of file musicapplicationobject.h.
Referenced by MusicApplication::musicCreateRightMenu().
MusicApplicationObject * MusicApplicationObject::instance () static
Get class object instance.
Definition at line 87 of file musicapplicationobject.cpp.
References m_instance.
Referenced by MusicScreenSaverWidget::caseButtonOnAndOff(), MusicSettingWidget::initSoundEffectWidget(), MusicScreenSaverWidget::inputDataChanged(), MusicScreenSaverWidget::itemHasClicked(), MusicBackgroundSkinDialog::MusicBackgroundSkinDialog(), MusicEnhancedPopWidget::MusicEnhancedPopWidget(), and MusicTimerWidget::saveResults().
bool MusicApplicationObject::isLastedVersion () const
Is lasted version.
Definition at line 92 of file musicapplicationobject.cpp.
References MusicSourceUpdateRequest::isLastedVersion(), and m_sourceUpdatehread.
Referenced by MusicApplication::musicCreateRightMenu().
void MusicApplicationObject::loadNetWorkSetting ()
load network settings parameters.
Definition at line 97 of file musicapplicationobject.cpp.
References QSyncConf::HOST, m_counterPVThread, m_sourceUpdatehread, MusicUtils::Algorithm::mdII(), MusicSourceUpdateRequest::startToDownload(), MusicDownloadCounterPVRequest::startToDownload(), SYNC_HOST_URL, and TTK_LOGGER_INFO.
Referenced by MusicApplication::readXMLConfigFromText().
void MusicApplicationObject::musicAboutUs () slot
Show about us widget.
Definition at line 276 of file musicapplicationobject.cpp.
References MusicMessageAboutDialog::exec().
void MusicApplicationObject::musicBugReportView () slot
Show bug report view.
Definition at line 281 of file musicapplicationobject.cpp.
References MusicUtils::Algorithm::mdII(), MusicUtils::Url::openUrl(), and REPORT_URL.
void MusicApplicationObject::musicDeviceChanged (bool state) slot
Detect mobile devices changed.
Definition at line 349 of file musicapplicationobject.cpp.
References MusicSettingManager::ExtraDevicePath, m_mobileDeviceWidget, and M_SETTING_PTR.
Referenced by MusicApplicationObject().
void MusicApplicationObject::musicDeviceNameChanged (const QString & name) slot
Detect mobile devices name changed.
Definition at line 344 of file musicapplicationobject.cpp.
References MusicSettingManager::ExtraDevicePath, and M_SETTING_PTR.
Referenced by MusicApplicationObject().
void MusicApplicationObject::musicEffectChanged () slot
Sound effect changed.
Definition at line 388 of file musicapplicationobject.cpp.
References MusicSoundEffectsItemWidget::BS2B, MusicSoundEffectsItemWidget::Crossfade, MusicSettingManager::EnhancedBS2B, MusicSettingManager::EnhancedCrossfade, MusicSettingManager::EnhancedLADSPA, MusicSettingManager::EnhancedMono, MusicSettingManager::EnhancedMonoStereo, MusicSettingManager::EnhancedSOX, MusicSettingManager::EnhancedSRC, MusicSettingManager::EnhancedStereo, MusicSoundEffectsItemWidget::LADSPA, M_SETTING_PTR, MusicSoundEffectsItemWidget::Mono, MusicSoundEffectsItemWidget::MonoStereo, MusicSoundEffectsItemWidget::soundEffectChanged(), MusicSoundEffectsItemWidget::Soxr, MusicSoundEffectsItemWidget::SrcConverter, and MusicSoundEffectsItemWidget::Stereo.
Referenced by MusicApplication::readXMLConfigFromText().
void MusicApplicationObject::musicResetWindow () slot
Reset current window geometry.
Definition at line 314 of file musicapplicationobject.cpp.
References MusicApplication::instance(), m_leftSideByOn, m_rightSideByOn, M_SETTING_PTR, MusicSettingManager::ScreenSize, MusicSettingManager::WidgetSize, WINDOW_HEIGHT_MIN, WINDOW_WIDTH_MIN, and MusicUtils::Widget::windowScreenGeometry().
Referenced by MusicApplicationObject().
void MusicApplicationObject::musicSetEqualizer () slot
Show set equalizer widget.
Definition at line 365 of file musicapplicationobject.cpp.
References closeCurrentEqualizer(), and MusicEqualizerDialog::exec().
void MusicApplicationObject::musicSetSoundEffect () slot
Show set sound effect widget.
Definition at line 376 of file musicapplicationobject.cpp.
References closeCurrentEqualizer(), MusicSoundEffectsWidget::exec(), and MusicSoundEffectsWidget::setInputObject().
void MusicApplicationObject::musicSetWindowToTop () slot
Set current window to top.
Definition at line 306 of file musicapplicationobject.cpp.
References MusicApplication::instance(), and m_setWindowToTop.
void MusicApplicationObject::musicSpectrumWidget () slot
Show spectrum widget.
Definition at line 301 of file musicapplicationobject.cpp.
References M_SINGLE_MANAGER_WIDGET_CLASS.
void MusicApplicationObject::musicTimerWidget () slot
Show timer widget.
Definition at line 291 of file musicapplicationobject.cpp.
References MusicTimerWidget::exec(), MusicApplication::getCurrentPlaylist(), MusicApplication::instance(), and MusicTimerWidget::setSongStringList().
void MusicApplicationObject::musicToolSetsParameter () slot
Tools sets parameter changed.
Definition at line 331 of file musicapplicationobject.cpp.
References m_musicTimerAutoObject, MusicToastLabel::popup(), and MusicTimerAutoObject::runTimerAutoConfig().
Referenced by MusicApplicationObject(), and MusicTimerWidget::saveResults().
void MusicApplicationObject::musicVersionUpdate () slot
Show version update widget.
Definition at line 286 of file musicapplicationobject.cpp.
References MusicSourceUpdateWidget::exec(), and MusicApplication::instance().
void MusicApplicationObject::sideAnimationByOff ()
Side animation by off.
Definition at line 200 of file musicapplicationobject.cpp.
References MusicApplication::instance(), m_leftSideByOn, m_rightSideByOn, M_SETTING_PTR, m_sideAnimation, MARGIN_SIDE_BY, MusicSettingManager::OtherSideBy, MusicSettingManager::OtherSideByIn, and MusicUtils::Widget::windowScreenGeometry().
Referenced by MusicApplication::enterEvent().
void MusicApplicationObject::sideAnimationByOn ()
Side animation by on.
Definition at line 163 of file musicapplicationobject.cpp.
References MusicApplication::instance(), m_leftSideByOn, m_rightSideByOn, M_SETTING_PTR, m_sideAnimation, MARGIN_SIDE, MARGIN_SIDE_BY, MusicSettingManager::OtherSideBy, MusicSettingManager::OtherSideByIn, and MusicUtils::Widget::windowScreenGeometry().
Referenced by MusicApplication::leaveEvent(), and MusicApplication::mouseReleaseEvent().
void MusicApplicationObject::sideAnimationReset ()
Side animation reset.
Definition at line 229 of file musicapplicationobject.cpp.
References MusicApplication::instance(), m_leftSideByOn, m_rightSideByOn, M_SETTING_PTR, MARGIN_SIDE_BY, MusicSettingManager::OtherSideBy, and MusicUtils::Widget::windowScreenGeometry().
Referenced by MusicApplication::writeXMLConfigToText().
void MusicApplicationObject::soureUpdateCheck ()
Soure update check.
Definition at line 156 of file musicapplicationobject.cpp.
References MusicSourceUpdateNotifyWidget::start().
Referenced by MusicApplication::readXMLConfigFromText().
void MusicApplicationObject::windowCloseAnimation ()
Window close animation.
remove fixed size
Definition at line 126 of file musicapplicationobject.cpp.
References MusicSettingManager::BackgroundTransparent, MusicTopAreaWidget::instance(), MusicApplication::instance(), m_quitAnimation, M_SETTING_PTR, MT_MS, MT_S2MS, MusicTopAreaWidget::setBackgroundAnimation(), windowCloseAnimationFinished(), and MusicSettingManager::WindowQuitMode.
Referenced by MusicApplication::quitWindowClose().
void MusicApplicationObject::windowCloseAnimationFinished () slot
Window close animation finished.
Definition at line 249 of file musicapplicationobject.cpp.
References MusicGifLabelWidget::Gif_Close_White, MusicApplication::instance(), m_quitContainer, MT_MS, MusicGifLabelWidget::setInfinited(), MusicGifLabelWidget::setInterval(), MusicGifLabelWidget::setType(), and MusicGifLabelWidget::start().
Referenced by windowCloseAnimation().
Member Data Documentation
MusicDownloadCounterPVRequest* MusicApplicationObject::m_counterPVThread protected
Definition at line 174 of file musicapplicationobject.h.
Referenced by loadNetWorkSetting(), MusicApplicationObject(), and ~MusicApplicationObject().
QDeviceWatcher* MusicApplicationObject::m_deviceWatcher protected
Definition at line 170 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), and ~MusicApplicationObject().
MusicApplicationObject * MusicApplicationObject::m_instance = nullptr static protected
Definition at line 177 of file musicapplicationobject.h.
Referenced by instance(), and MusicApplicationObject().
bool MusicApplicationObject::m_leftSideByOn protected
Definition at line 166 of file musicapplicationobject.h.
Referenced by musicResetWindow(), sideAnimationByOff(), sideAnimationByOn(), and sideAnimationReset().
MusicMobileDevicesWidget* MusicApplicationObject::m_mobileDeviceWidget protected
Definition at line 169 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), musicDeviceChanged(), and ~MusicApplicationObject().
MusicTimerAutoObject* MusicApplicationObject::m_musicTimerAutoObject protected
Definition at line 168 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), musicToolSetsParameter(), and ~MusicApplicationObject().
QPropertyAnimation* MusicApplicationObject::m_quitAnimation protected
Definition at line 167 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), windowCloseAnimation(), and ~MusicApplicationObject().
QWidget* MusicApplicationObject::m_quitContainer protected
Definition at line 171 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), windowCloseAnimationFinished(), and ~MusicApplicationObject().
bool MusicApplicationObject::m_rightSideByOn protected
Definition at line 166 of file musicapplicationobject.h.
Referenced by musicResetWindow(), sideAnimationByOff(), sideAnimationByOn(), and sideAnimationReset().
MusicScreenSaverBackgroundWidget* MusicApplicationObject::m_screenSaverWidget protected
Definition at line 175 of file musicapplicationobject.h.
Referenced by applySettingParameter(), MusicApplicationObject(), and ~MusicApplicationObject().
bool MusicApplicationObject::m_setWindowToTop protected
Definition at line 165 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), and musicSetWindowToTop().
QPropertyAnimation * MusicApplicationObject::m_sideAnimation protected
Definition at line 167 of file musicapplicationobject.h.
Referenced by MusicApplicationObject(), sideAnimationByOff(), sideAnimationByOn(), and ~MusicApplicationObject().
MusicSourceUpdateRequest* MusicApplicationObject::m_sourceUpdatehread protected
Definition at line 173 of file musicapplicationobject.h.
Referenced by isLastedVersion(), loadNetWorkSetting(), MusicApplicationObject(), and ~MusicApplicationObject().
The documentation for this class was generated from the following files:
TTKModule/musicapplicationobject.h
TTKModule/musicapplicationobject.cpp