TTKMusicPlayer: Miniblink Class Reference
Miniblink Class Reference
#include <miniblink.h>
Public Slots
void stop ()
void back ()
void forward ()
void reload ()
Signals
void loadFinished (bool ok)
Public Member Functions
Miniblink (QWidget *parent=nullptr)
~Miniblink ()
void load (const QString &url)
void setHtml (const QString &html)
void setUrl (const QString &url)
QString url () const
void finish (bool ok)
Static Public Member Functions
static bool initialize ()
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
wke::CWebView * m_webView
Static Private Attributes
static int m_ref = 0
Detailed Description
Definition at line 28 of file miniblink.h.
Constructor & Destructor Documentation
Miniblink::Miniblink (QWidget * parent = nullptr) explicit
Definition at line 17 of file miniblink.cpp.
References m_webView, onLoadingFinish(), and WKE_WINDOW_TYPE_CONTROL.
Miniblink::~Miniblink ()
Definition at line 25 of file miniblink.cpp.
References m_ref, and m_webView.
Member Function Documentation
void Miniblink::back () slot
Definition at line 86 of file miniblink.cpp.
References m_webView.
void Miniblink::finish (bool ok)
Definition at line 76 of file miniblink.cpp.
References loadFinished().
void Miniblink::forward () slot
Definition at line 94 of file miniblink.cpp.
References m_webView.
bool Miniblink::initialize () static
Definition at line 35 of file miniblink.cpp.
References m_ref, wkeInitialize(), and wkeSetWkeDllPath().
Referenced by QKugouWindow::createWebViewer().
void Miniblink::load (const QString & url)
Definition at line 56 of file miniblink.cpp.
References m_webView.
void Miniblink::loadFinished (bool ok) signal
Referenced by finish().
void Miniblink::reload () slot
Definition at line 102 of file miniblink.cpp.
References m_webView.
Referenced by QKugouWindow::refresh().
void Miniblink::resizeEvent (QResizeEvent * event) final override protected virtual
Definition at line 107 of file miniblink.cpp.
References m_webView.
void Miniblink::setHtml (const QString & html)
Definition at line 61 of file miniblink.cpp.
References m_webView.
void Miniblink::setUrl (const QString & url)
Definition at line 66 of file miniblink.cpp.
References m_webView.
Referenced by QKugouWindow::setUrl().
void Miniblink::stop () slot
Definition at line 81 of file miniblink.cpp.
References m_webView.
QString Miniblink::url () const
Definition at line 71 of file miniblink.cpp.
References m_webView.
Member Data Documentation
int Miniblink::m_ref = 0 static private
Definition at line 58 of file miniblink.h.
Referenced by initialize(), and ~Miniblink().
wke::CWebView* Miniblink::m_webView private
Definition at line 59 of file miniblink.h.
Referenced by back(), forward(), load(), Miniblink(), QKugouWindow::refresh(), reload(), resizeEvent(), setHtml(), setUrl(), QKugouWindow::setUrl(), stop(), url(), and ~Miniblink().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qkugou/miniblink/miniblink.h
TTKThirdParty/TTKExtras/qkugou/miniblink/miniblink.cpp