TTKMusicplayer: File Namespace Reference
File Namespace Reference
Functions
static quint64 directorySize (const QString &dirName)
static void checkCacheSize ()
static QString languageName (int index)
Function Documentation
static void File::checkCacheSize () static
Definition at line 37 of file musicruntimemanager.cpp.
References directorySize(), MusicSettingManager::DownloadCacheEnable, MusicSettingManager::DownloadCacheSize, MusicSettingManager::DownloadMusicDirPath, G_SETTING_PTR, and MH_MB2B.
Referenced by MusicRunTimeManager::run().
static quint64 File::directorySize (const QString & dirName) static
Definition at line 15 of file musicruntimemanager.cpp.
Referenced by checkCacheSize().
static QString File::languageName (int index) static
Definition at line 63 of file musicruntimemanager.cpp.
References LANGUAGE_DIR_FULL.
Referenced by MusicRunTimeManager::translator().