TTKMusicPlayer: TTKLabelItemDelegate Class Reference
TTKLabelItemDelegate Class Reference
The class of the label item delegate.
#include <ttkitemdelegate.h>
Public Member Functions
TTKLabelItemDelegate (QObject *parent=nullptr)
~TTKLabelItemDelegate ()
void setAlignment (Qt::Alignment alignment) const
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const overridefinal
Public Member Functions inherited from TTKAbstractItemDelegate
TTKAbstractItemDelegate (QObject *parent=nullptr)
~TTKAbstractItemDelegate ()
void setModuleMode (TTKUInt8 mode)
void setStyleSheet (const QString &style) const
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &) const overridefinal
Private Attributes
QLabel * m_label
Additional Inherited Members
Public Types inherited from TTKAbstractItemDelegate
enum Module { Null = 0x0, DisplayMode = 0x1, ElideMode = 0x2, TreeMode = 0x4 }
Protected Attributes inherited from TTKAbstractItemDelegate
TTKUInt8 m_mode
QWidget * m_container
Detailed Description
The class of the label item delegate.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 145 of file ttkitemdelegate.h.
Constructor & Destructor Documentation
TTKLabelItemDelegate::TTKLabelItemDelegate (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 134 of file ttkitemdelegate.cpp.
References TTKAbstractItemDelegate::m_container, and m_label.
TTKLabelItemDelegate::~TTKLabelItemDelegate ()
Definition at line 142 of file ttkitemdelegate.cpp.
References m_label.
Member Function Documentation
void TTKLabelItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const final override virtual
Override paint.
Reimplemented from TTKAbstractItemDelegate.
Definition at line 152 of file ttkitemdelegate.cpp.
References TTKAbstractItemDelegate::ElideMode, m_label, TTKAbstractItemDelegate::m_mode, TTKAbstractItemDelegate::paint(), TTKAbstractItemDelegate::TreeMode, and TTK_DISPLAY_ROLE.
void TTKLabelItemDelegate::setAlignment (Qt::Alignment alignment) const
Set text alignment.
Definition at line 147 of file ttkitemdelegate.cpp.
References m_label.
Referenced by MusicPluginWidget::MusicPluginWidget(), and MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget().
Member Data Documentation
QLabel* TTKLabelItemDelegate::m_label private
Definition at line 167 of file ttkitemdelegate.h.
Referenced by paint(), setAlignment(), TTKLabelItemDelegate(), and ~TTKLabelItemDelegate().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkitemdelegate.h
TTKCommon/TTKLibrary/ttkitemdelegate.cpp