TTKMusicPlayer: MusicMobileDevicesWidget Class Reference
MusicMobileDevicesWidget Class Reference
The class of the mobile devices widget.
#include <musicmobiledeviceswidget.h>
Public Slots
void showMobileManager ()
Public Member Functions
MusicMobileDevicesWidget (QWidget *parent=nullptr)
~MusicMobileDevicesWidget ()
Public Member Functions inherited from TTKClickedLabel
TTKClickedLabel (QWidget *parent=nullptr)
TTKClickedLabel (const QString &text, QWidget *parent=nullptr)
void blockOption (bool block) noexcept
Private Attributes
QToolButton * m_closeButton
Additional Inherited Members
Signals inherited from TTKClickedLabel
void clicked ()
Protected Member Functions inherited from TTKClickedLabel
virtual void mousePressEvent (QMouseEvent *event) overridefinal
Protected Attributes inherited from TTKClickedLabel
bool m_blockOption
Detailed Description
The class of the mobile devices widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicmobiledeviceswidget.h.
Constructor & Destructor Documentation
MusicMobileDevicesWidget::MusicMobileDevicesWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicmobiledeviceswidget.cpp.
References TTKClickedLabel::clicked(), G_SETTING_PTR, m_closeButton, MusicSettingManager::ScreenSize, showMobileManager(), and TTK::UI::ToolButtonStyle04.
MusicMobileDevicesWidget::~MusicMobileDevicesWidget ()
Object destructor.
Definition at line 27 of file musicmobiledeviceswidget.cpp.
References m_closeButton.
Member Function Documentation
void MusicMobileDevicesWidget::showMobileManager () slot
Show mobile manager widget.
Definition at line 32 of file musicmobiledeviceswidget.cpp.
References MusicSettingManager::ExtraDevicePath, MusicMobileSongsManagerWidget::findExtraDevicePath(), G_SETTING_PTR, and TTKGenerateSingleWidget.
Referenced by MusicMobileDevicesWidget().
Member Data Documentation
QToolButton* MusicMobileDevicesWidget::m_closeButton private
Definition at line 50 of file musicmobiledeviceswidget.h.
Referenced by MusicMobileDevicesWidget(), and ~MusicMobileDevicesWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicmobiledeviceswidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicmobiledeviceswidget.cpp