TTKMusicPlayer: MusicLrcTranslatedWidget Class Reference
MusicLrcTranslatedWidget Class Reference
The class of the lrc translate widget.
#include <musiclrctranslatedwidget.h>
Public Member Functions
MusicLrcTranslatedWidget (QWidget *parent=nullptr)
~MusicLrcTranslatedWidget ()
void setCurrentSongName (const QString &name)
void setLrcAnalysisModel (MusicLrcAnalysis *analysis) noexcept
Private Slots
void downloadDataFinished (const QString &bytes)
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
virtual void wheelEvent (QWheelEvent *event) overridefinal
Private Attributes
MusicLrcAnalysis * m_lrcAnalysis
QLabel * m_titleName
QLabel * m_plainText
MusicGifLabelWidget * m_loadingLabel
Detailed Description
The class of the lrc translate widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrctranslatedwidget.h.
Constructor & Destructor Documentation
MusicLrcTranslatedWidget::MusicLrcTranslatedWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musiclrctranslatedwidget.cpp.
References TTK::UI::BackgroundStyle01, TTK::UI::BackgroundStyle07, TTK::UI::BtnPClose, MusicGifLabelWidget::CicleBlue, TTK::UI::ColorStyle03, TTK::UI::ColorStyle12, TTK::UI::FontStyle01, TTK::UI::FontStyle03, TTK::UI::FontStyle05, TTK::Widget::generateVScrollAreaStyle(), m_loadingLabel, m_plainText, and m_titleName.
MusicLrcTranslatedWidget::~MusicLrcTranslatedWidget ()
Object destructor.
Definition at line 61 of file musiclrctranslatedwidget.cpp.
References m_loadingLabel, m_plainText, and m_titleName.
Member Function Documentation
void MusicLrcTranslatedWidget::downloadDataFinished (const QString & bytes) private slot
Download data from net finished.
Definition at line 80 of file musiclrctranslatedwidget.cpp.
References MusicLrcAnalysis::dataList(), MusicGifLabelWidget::execute(), m_loadingLabel, m_lrcAnalysis, m_plainText, TTK_AUTHOR_NAME, and TTK_LINEFEED.
Referenced by setCurrentSongName().
void MusicLrcTranslatedWidget::mouseMoveEvent (QMouseEvent * event) final override private virtual
Definition at line 122 of file musiclrctranslatedwidget.cpp.
void MusicLrcTranslatedWidget::mousePressEvent (QMouseEvent * event) final override private virtual
Definition at line 117 of file musiclrctranslatedwidget.cpp.
void MusicLrcTranslatedWidget::mouseReleaseEvent (QMouseEvent * event) final override private virtual
Definition at line 127 of file musiclrctranslatedwidget.cpp.
void MusicLrcTranslatedWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 111 of file musiclrctranslatedwidget.cpp.
References m_loadingLabel.
void MusicLrcTranslatedWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 68 of file musiclrctranslatedwidget.cpp.
References MusicLrcAnalysis::dataString(), downloadDataFinished(), MusicGifLabelWidget::execute(), MusicLrcAnalysis::filePath(), m_loadingLabel, m_lrcAnalysis, m_titleName, TTKAbstractNetwork::setHeader(), and MusicTranslationRequest::startToRequest().
Referenced by MusicLrcContainerForInterior::translatedLrcData().
void MusicLrcTranslatedWidget::setLrcAnalysisModel (MusicLrcAnalysis * analysis) inline noexcept
Set lrc analysis model.
Definition at line 52 of file musiclrctranslatedwidget.h.
Referenced by MusicLrcContainerForInterior::translatedLrcData().
void MusicLrcTranslatedWidget::wheelEvent (QWheelEvent * event) final override private virtual
Definition at line 132 of file musiclrctranslatedwidget.cpp.
Member Data Documentation
MusicGifLabelWidget* MusicLrcTranslatedWidget::m_loadingLabel private
Definition at line 72 of file musiclrctranslatedwidget.h.
Referenced by downloadDataFinished(), MusicLrcTranslatedWidget(), resizeEvent(), setCurrentSongName(), and ~MusicLrcTranslatedWidget().
MusicLrcAnalysis* MusicLrcTranslatedWidget::m_lrcAnalysis private
Definition at line 70 of file musiclrctranslatedwidget.h.
Referenced by downloadDataFinished(), and setCurrentSongName().
QLabel * MusicLrcTranslatedWidget::m_plainText private
Definition at line 71 of file musiclrctranslatedwidget.h.
Referenced by downloadDataFinished(), MusicLrcTranslatedWidget(), and ~MusicLrcTranslatedWidget().
QLabel* MusicLrcTranslatedWidget::m_titleName private
Definition at line 71 of file musiclrctranslatedwidget.h.
Referenced by MusicLrcTranslatedWidget(), setCurrentSongName(), and ~MusicLrcTranslatedWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrctranslatedwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrctranslatedwidget.cpp