TTKMusicplayer: MusicUserLineEdit Class Reference
MusicUserLineEdit Class Reference
The class of the user lineedit.
#include <musicuserlineedit.h>
Public Types
enum LabelType {
User, Passwd, PasswdNew, PasswdConfirm,
Mail
}
Signals
void checkPwdStrength (int code)
Public Member Functions
MusicUserLineEdit (QWidget *parent=nullptr)
void setLabel (LabelType ty, QLabel *t, QLabel *s)
bool getMailStatus () const
bool getStrStatus () const
Protected Slots
void checkPwdStrength ()
Protected Member Functions
virtual void focusInEvent (QFocusEvent *event) override
virtual void focusOutEvent (QFocusEvent *event) override
void checkTheInput ()
void showLabel ()
void showLabel (int s, int e)
void labelCheck (bool check)
Protected Attributes
QLabel * m_tipsLabel
QLabel * m_statusLabel
LabelType m_type
bool m_mailContains
bool m_strContains
Detailed Description
The class of the user lineedit.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicuserlineedit.h.
Member Enumeration Documentation
enum MusicUserLineEdit::LabelType
Enumerator
User
label type is user
Passwd
label type is password
PasswdNew
label type is new password
PasswdConfirm
label type is confirm password
Mail
label type is mail
Definition at line 33 of file musicuserlineedit.h.
Constructor & Destructor Documentation
MusicUserLineEdit::MusicUserLineEdit (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicuserlineedit.cpp.
References m_mailContains, m_statusLabel, m_strContains, and m_tipsLabel.
Member Function Documentation
void MusicUserLineEdit::checkPwdStrength (int code) signal
Check the new password strength. -1 empty string, 0 weak, 1 middle, 2 strong
void MusicUserLineEdit::checkPwdStrength () protected slot
Check the new password strength.
Definition at line 106 of file musicuserlineedit.cpp.
Referenced by setLabel().
void MusicUserLineEdit::checkTheInput () protected
Check the input valied when focus out.
Definition at line 88 of file musicuserlineedit.cpp.
References m_type, Mail, Passwd, PasswdConfirm, showLabel(), and User.
Referenced by focusOutEvent().
void MusicUserLineEdit::focusInEvent (QFocusEvent * event) override protected virtual
Override the widget event.
Definition at line 19 of file musicuserlineedit.cpp.
References m_tipsLabel, and MusicUIObject::MQSSColorStyle04.
void MusicUserLineEdit::focusOutEvent (QFocusEvent * event) override protected virtual
Definition at line 29 of file musicuserlineedit.cpp.
References checkTheInput().
bool MusicUserLineEdit::getMailStatus () const inline
Check the mail type valid.
Definition at line 54 of file musicuserlineedit.h.
bool MusicUserLineEdit::getStrStatus () const inline
Check the string type valid.
Definition at line 58 of file musicuserlineedit.h.
void MusicUserLineEdit::labelCheck (bool check) protected
Show label info that means you input is valid or not.
Definition at line 47 of file musicuserlineedit.cpp.
References m_statusLabel, m_tipsLabel, and MusicUIObject::MQSSColorStyle05.
Referenced by showLabel().
void MusicUserLineEdit::setLabel (LabelType ty, QLabel * t, QLabel * s)
Set label and label type.
Definition at line 35 of file musicuserlineedit.cpp.
References checkPwdStrength(), m_statusLabel, m_tipsLabel, m_type, and PasswdNew.
void MusicUserLineEdit::showLabel () protected
Show mail label.
Definition at line 82 of file musicuserlineedit.cpp.
References labelCheck(), and m_mailContains.
Referenced by checkTheInput().
void MusicUserLineEdit::showLabel (int s, int e) protected
Show string label.
Definition at line 76 of file musicuserlineedit.cpp.
References labelCheck(), and m_strContains.
Member Data Documentation
bool MusicUserLineEdit::m_mailContains protected
Definition at line 99 of file musicuserlineedit.h.
Referenced by MusicUserLineEdit(), and showLabel().
QLabel* MusicUserLineEdit::m_statusLabel protected
Definition at line 97 of file musicuserlineedit.h.
Referenced by labelCheck(), MusicUserLineEdit(), and setLabel().
bool MusicUserLineEdit::m_strContains protected
Definition at line 100 of file musicuserlineedit.h.
Referenced by MusicUserLineEdit(), and showLabel().
QLabel* MusicUserLineEdit::m_tipsLabel protected
Definition at line 96 of file musicuserlineedit.h.
Referenced by focusInEvent(), labelCheck(), MusicUserLineEdit(), and setLabel().
LabelType MusicUserLineEdit::m_type protected
Definition at line 98 of file musicuserlineedit.h.
Referenced by checkTheInput(), and setLabel().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicUserKits/musicuserlineedit.h
TTKModule/TTKWidget/musicUserKits/musicuserlineedit.cpp