TTKMusicPlayer: MusicPlaylistCategoryItem Class Reference
MusicPlaylistCategoryItem Class Reference
The class of the playlist music category item.
#include <musicplaylistcategorywidget.h>
Public Slots
void buttonClicked (int index)
Public Member Functions
MusicPlaylistCategoryItem (CategoryProperty *category, QWidget *parent=nullptr)
~MusicPlaylistCategoryItem ()
void resizeWindow ()
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
QList< QWidget * > m_items
QGridLayout * m_gridLayout
Detailed Description
The class of the playlist music category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicplaylistcategorywidget.h.
Constructor & Destructor Documentation
MusicPlaylistCategoryItem::MusicPlaylistCategoryItem (CategoryProperty * category, QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 67 of file musicplaylistcategorywidget.cpp.
References buttonClicked(), TTK::UI::ColorStyle03, TTK::UI::ColorStyle07, TTK::UI::FontStyle03, ITEM_LABEL_HEIGHT, ITEM_MAX_COLUMN, LINE_SPACING_SIZE, CategoryProperty::m_category, MusicResultsCategory::m_category, m_gridLayout, MusicResultsCategory::m_items, m_items, CategoryProperty::m_property, CategoryProperty::m_tag, TTKClickedGroup::mapped(), CategoryProperty::New, qAsConst, and TTKStaticCast.
MusicPlaylistCategoryItem::~MusicPlaylistCategoryItem ()
Object destructor.
Definition at line 134 of file musicplaylistcategorywidget.cpp.
References m_gridLayout, and m_items.
Member Function Documentation
void MusicPlaylistCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 154 of file musicplaylistcategorywidget.cpp.
References MusicRightAreaWidget::instance(), key, m_items, and MusicRightAreaWidget::showPlaylistCategoryFound().
Referenced by MusicPlaylistCategoryItem().
void MusicPlaylistCategoryItem::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 166 of file musicplaylistcategorywidget.cpp.
References resizeWindow().
void MusicPlaylistCategoryItem::resizeWindow ()
Resize window bound by resize called.
Definition at line 140 of file musicplaylistcategorywidget.cpp.
References G_SETTING_PTR, LEFT_SIDE_WIDTH_MIN, LINE_SPACING_SIZE, m_gridLayout, m_items, qAsConst, and MusicSettingManager::WidgetSize.
Referenced by resizeEvent().
Member Data Documentation
QGridLayout* MusicPlaylistCategoryItem::m_gridLayout private
Definition at line 63 of file musicplaylistcategorywidget.h.
Referenced by MusicPlaylistCategoryItem(), resizeWindow(), and ~MusicPlaylistCategoryItem().
QList<QWidget*> MusicPlaylistCategoryItem::m_items private
Definition at line 62 of file musicplaylistcategorywidget.h.
Referenced by buttonClicked(), MusicPlaylistCategoryItem(), resizeWindow(), and ~MusicPlaylistCategoryItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistcategorywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistcategorywidget.cpp