TTKMusicplayer: QAesWrapper Class Reference
QAesWrapper Class Reference
The class of the aes wrapper.
#include <qaeswrapper.h>
Public Member Functions
QAesWrapper ()
QByteArray encryptECB (const QByteArray &in, const QByteArray &key)
QByteArray decryptECB (const QByteArray &in, const QByteArray &key)
QByteArray encryptCBC (const QByteArray &in, const QByteArray &key, const QByteArray &iv)
QByteArray decryptCBC (const QByteArray &in, const QByteArray &key, const QByteArray &iv)
Detailed Description
The class of the aes wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qaeswrapper.h.
Constructor & Destructor Documentation
QAesWrapper::QAesWrapper ()
Object contsructor.
Definition at line 9 of file qaeswrapper.cpp.
Member Function Documentation
QByteArray QAesWrapper::decryptCBC (const QByteArray & in, const QByteArray & key, const QByteArray & iv)
Decrypt aes CBC by input.
Definition at line 83 of file qaeswrapper.cpp.
References AES_cbc_encrypt(), AES_DECRYPT, AES_set_decrypt_key(), Base64::base64Decode(), and DATA_CACHE_SIZE.
QByteArray QAesWrapper::decryptECB (const QByteArray & in, const QByteArray & key)
Decrypt des ECB by input.
Definition at line 41 of file qaeswrapper.cpp.
References AES_DECRYPT, AES_ecb_encrypt(), AES_set_decrypt_key(), Base64::base64Decode(), and DATA_CACHE_SIZE.
QByteArray QAesWrapper::encryptCBC (const QByteArray & in, const QByteArray & key, const QByteArray & iv)
Encrypt aes CBC by input.
Definition at line 56 of file qaeswrapper.cpp.
References AES_BLOCK_SIZE, AES_cbc_encrypt(), AES_ENCRYPT, AES_set_encrypt_key(), Base64::base64Encode(), and DATA_CACHE_SIZE.
Referenced by MusicWYQueryInterface::makeTokenQueryUrl().
QByteArray QAesWrapper::encryptECB (const QByteArray & in, const QByteArray & key)
Encrypt des ECB by input.
Definition at line 14 of file qaeswrapper.cpp.
References AES_BLOCK_SIZE, AES_ecb_encrypt(), AES_ENCRYPT, AES_set_encrypt_key(), Base64::base64Encode(), and DATA_CACHE_SIZE.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/qaeswrapper.h
TTKThirdParty/TTKExtras/qalgorithm/qaeswrapper.cpp