TTKMusicPlayer: TTKThirdParty/Zlib/zlib/inftrees.h File Reference
inftrees.h File Reference
Classes
struct code
Macros
#define ENOUGH_LENS 852
#define ENOUGH_DISTS 592
#define ENOUGH (ENOUGH_LENS+ENOUGH_DISTS)
Enumerations
enum codetype { CODES, LENS, DISTS }
Functions
int ZLIB_INTERNAL inflate_table (codetype type, unsigned short FAR *lens, unsigned codes, code FAR *FAR *table, unsigned FAR *bits, unsigned short FAR *work)
Macro Definition Documentation
#define ENOUGH (ENOUGH_LENS+ENOUGH_DISTS)
Definition at line 51 of file inftrees.h.
Referenced by inflateCopy().
#define ENOUGH_DISTS 592
Definition at line 50 of file inftrees.h.
Referenced by inflate_table().
#define ENOUGH_LENS 852
Definition at line 49 of file inftrees.h.
Referenced by inflate_table().
Enumeration Type Documentation
enum codetype
Enumerator
CODES
LENS
DISTS
Definition at line 54 of file inftrees.h.
Function Documentation
int ZLIB_INTERNAL inflate_table (codetype type, unsigned short FAR * lens, unsigned codes, code FAR *FAR * table, unsigned FAR * bits, unsigned short FAR * work)
Definition at line 32 of file inftrees.c.
References code::bits, CODES, DISTS, ENOUGH_DISTS, ENOUGH_LENS, FAR, int(), LENS, TTK::max(), MAXBITS, TTK::min(), code::op, and code::val.
Referenced by fixedtables(), inflate(), and inflateBack().