TTKMusicplayer: MusicAudioRecorderObject Class Reference
MusicAudioRecorderObject Class Reference
The class of the audio recorder core.
#include <musicaudiorecorderobject.h>
Classes
struct HEADER
The class of the audio file tag header.
Public Types
typedef struct MUSIC_TOOLSET_EXPORT MusicAudioRecorderObject::HEADER HEADER
The class of the audio file tag header.
Public Slots
void onRecordStart ()
void onRecordStop ()
void onRecordPlay ()
void onStateChange (QAudio::State state)
Public Member Functions
MusicAudioRecorderObject (QObject *parent=nullptr)
~MusicAudioRecorderObject ()
int addWavHeader (const char *filename)
void setVolume (int volume)
int volume () const
void setFileName (const QString &name)
QString getFileName () const
bool error () const
Protected Attributes
int m_inputVolume
QAudioFormat m_mFormatFile
QFile * m_mpOutputFile
QAudioInput * m_mpAudioInputFile
QAudioOutput * m_mpAudioOutputFile
Detailed Description
The class of the audio recorder core.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicaudiorecorderobject.h.
Member Typedef Documentation
typedef struct MUSIC_TOOLSET_EXPORT MusicAudioRecorderObject::HEADER MusicAudioRecorderObject::HEADER
The class of the audio file tag header.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Constructor & Destructor Documentation
MusicAudioRecorderObject::MusicAudioRecorderObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicaudiorecorderobject.cpp.
References m_inputVolume, m_mFormatFile, m_mpAudioInputFile, m_mpAudioOutputFile, m_mpOutputFile, MUSIC_RECORD_FILE, TTK_LOGGER_INFO, and TTK_LOGGER_WARN.
MusicAudioRecorderObject::~MusicAudioRecorderObject ()
Definition at line 47 of file musicaudiorecorderobject.cpp.
References m_mpAudioInputFile, m_mpAudioOutputFile, m_mpOutputFile, MUSIC_RECORD_FILE, MUSIC_RECORD_IN_FILE, and MUSIC_RECORD_OUT_FILE.
Member Function Documentation
int MusicAudioRecorderObject::addWavHeader (const char * filename)
Add the header of wav.
Definition at line 58 of file musicaudiorecorderobject.cpp.
References MusicAudioRecorderObject::HEADER::DATANAME, MusicAudioRecorderObject::HEADER::FMTNAME, m_mpOutputFile, MusicAudioRecorderObject::HEADER::nAudioFormat, MusicAudioRecorderObject::HEADER::nBitsPerSample, MusicAudioRecorderObject::HEADER::nBytesPerSample, MusicAudioRecorderObject::HEADER::nBytesPerSecond, MusicAudioRecorderObject::HEADER::nChannleNumber, MusicAudioRecorderObject::HEADER::nDataLength, MusicAudioRecorderObject::HEADER::nFMTLength, MusicAudioRecorderObject::HEADER::nRIFFLength, MusicAudioRecorderObject::HEADER::nSampleRate, OPEN_FILE_ERROR, qPrintable, REWRITE_FILE_ERROR, MusicAudioRecorderObject::HEADER::RIFFNAME, SAVE_FILE_ERROR, SEEK_SET, MusicAudioRecorderObject::HEADER::WAVNAME, and WRITE_FILE_ERROR.
Referenced by MusicIdentifySongsWidget::detectedTimeOut(), and MusicSoundKMicroWidget::playFinished().
bool MusicAudioRecorderObject::error () const
Current input device error or not.
Definition at line 167 of file musicaudiorecorderobject.cpp.
References m_mpAudioInputFile.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), and MusicSoundKMicroWidget::recordStateChanged().
QString MusicAudioRecorderObject::getFileName () const
Get output file name.
Definition at line 162 of file musicaudiorecorderobject.cpp.
References m_mpOutputFile.
void MusicAudioRecorderObject::onRecordPlay () slot
Recorder play play.
Definition at line 196 of file musicaudiorecorderobject.cpp.
References m_mFormatFile, m_mpAudioOutputFile, m_mpOutputFile, onStateChange(), and TTK_LOGGER_ERROR.
void MusicAudioRecorderObject::onRecordStart () slot
Recorder play start.
Definition at line 177 of file musicaudiorecorderobject.cpp.
References m_inputVolume, m_mFormatFile, m_mpAudioInputFile, m_mpOutputFile, and TTK_LOGGER_ERROR.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicAudioRecorderObject::onRecordStop () slot
Recorder play stop.
Definition at line 211 of file musicaudiorecorderobject.cpp.
References m_mpAudioInputFile, m_mpAudioOutputFile, and m_mpOutputFile.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), onStateChange(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicAudioRecorderObject::onStateChange (QAudio::State state) slot
Recorder play state changed.
Definition at line 230 of file musicaudiorecorderobject.cpp.
References onRecordStop().
Referenced by onRecordPlay().
void MusicAudioRecorderObject::setFileName (const QString & name)
Set output file name.
Definition at line 157 of file musicaudiorecorderobject.cpp.
References m_mpOutputFile.
void MusicAudioRecorderObject::setVolume (int volume)
Set volume by value.
Definition at line 141 of file musicaudiorecorderobject.cpp.
References m_inputVolume, m_mpAudioInputFile, and volume().
Referenced by MusicSoundKMicroSettingPopWidget::volumeChanged().
int MusicAudioRecorderObject::volume () const
Get volume by value.
Definition at line 152 of file musicaudiorecorderobject.cpp.
References m_inputVolume.
Referenced by setVolume().
Member Data Documentation
int MusicAudioRecorderObject::m_inputVolume protected
Definition at line 109 of file musicaudiorecorderobject.h.
Referenced by MusicAudioRecorderObject(), onRecordStart(), setVolume(), and volume().
QAudioFormat MusicAudioRecorderObject::m_mFormatFile protected
Definition at line 110 of file musicaudiorecorderobject.h.
Referenced by MusicAudioRecorderObject(), onRecordPlay(), and onRecordStart().
QAudioInput* MusicAudioRecorderObject::m_mpAudioInputFile protected
Definition at line 112 of file musicaudiorecorderobject.h.
Referenced by error(), MusicAudioRecorderObject(), onRecordStart(), onRecordStop(), setVolume(), and ~MusicAudioRecorderObject().
QAudioOutput* MusicAudioRecorderObject::m_mpAudioOutputFile protected
Definition at line 113 of file musicaudiorecorderobject.h.
Referenced by MusicAudioRecorderObject(), onRecordPlay(), onRecordStop(), and ~MusicAudioRecorderObject().
QFile* MusicAudioRecorderObject::m_mpOutputFile protected
Definition at line 111 of file musicaudiorecorderobject.h.
Referenced by addWavHeader(), getFileName(), MusicAudioRecorderObject(), onRecordPlay(), onRecordStart(), onRecordStop(), setFileName(), and ~MusicAudioRecorderObject().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicaudiorecorderobject.h
TTKModule/TTKCore/musicToolsSetsKits/musicaudiorecorderobject.cpp