TTKMusicplayer: MusicBDQueryPlaylistRequest Class Reference
MusicBDQueryPlaylistRequest Class Reference
The class to baidu query playlist download data from net.
#include <musicbdqueryplaylistrequest.h>
Public Slots
virtual void downLoadFinished () override
void getDetailsFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBDQueryPlaylistRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &playlist) override
virtual void startToPage (int offset) override
virtual void startToSearch (const QString &playlist) override
virtual void getPlaylistInfo (MusicResultsItem &item) override
Public Member Functions inherited from MusicQueryPlaylistRequest
MusicQueryPlaylistRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual ~MusicAbstractQueryRequest ()
virtual void startToSingleSearch (const QString &text)
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
virtual ~MusicPagingRequest ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryPlaylistRequest
void createPlaylistItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicAbstractQueryRequest
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
QVariantMap m_headerData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicBDQueryInterface
void makeTokenQueryUrl (QNetworkRequest *request, const QString &id)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &bit)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicPayAttribute (MusicObject::MusicSongInformation *info)
Detailed Description
The class to baidu query playlist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicbdqueryplaylistrequest.h.
Constructor & Destructor Documentation
MusicBDQueryPlaylistRequest::MusicBDQueryPlaylistRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musicbdqueryplaylistrequest.cpp.
References MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_BD_INTERFACE.
Member Function Documentation
void MusicBDQueryPlaylistRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 115 of file musicbdqueryplaylistrequest.cpp.
References MusicAbstractQueryRequest::clearAllItems(), MusicQueryPlaylistRequest::createPlaylistItem(), MusicPagingRequest::deleteAll(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicResultsItem::m_id, MusicAbstractNetwork::m_interrupt, MusicAbstractQueryRequest::m_musicSongInfos, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicPagingRequest::m_pageTotal, MusicResultsItem::m_playCount, MusicAbstractNetwork::m_reply, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MUSIC_AUTHOR_NAME, MUSIC_YEAR_FORMAT, QJson::Parser::parse(), and TTK_LOGGER_INFO.
Referenced by startToPage().
void MusicBDQueryPlaylistRequest::getDetailsFinished () slot
Download details data from net finished.
Definition at line 172 of file musicbdqueryplaylistrequest.cpp.
References MusicAbstractQueryRequest::clearAllItems(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::findTimeStringByAttrs(), MusicUtils::String::illegalCharactersReplaced(), MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicObject::MusicSongInformation::m_discNumber, MusicAbstractNetwork::m_interrupt, MusicObject::MusicSongInformation::m_lrcUrl, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_searchQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicObject::NetworkQuery, QJson::Parser::parse(), MusicBDQueryInterface::readFromMusicSongAttribute(), TTK_LOGGER_INFO, and TTKObject_cast.
Referenced by startToSearch().
void MusicBDQueryPlaylistRequest::getPlaylistInfo (MusicResultsItem & item) override virtual
Get playlist info.
Implements MusicQueryPlaylistRequest.
Definition at line 70 of file musicbdqueryplaylistrequest.cpp.
References ALG_UA_KEY, BD_PLAYLIST_INFO_URL, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicResultsItem::m_id, MusicAbstractNetwork::m_manager, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MusicUtils::Algorithm::mdII(), MUSIC_AUTHOR_NAME, MUSIC_YEAR_FORMAT, MusicObject::NetworkError, QJson::Parser::parse(), MusicObject::setSslConfiguration(), and TTK_LOGGER_INFO.
void MusicBDQueryPlaylistRequest::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicPagingRequest.
Definition at line 24 of file musicbdqueryplaylistrequest.cpp.
References ALG_UA_KEY, BD_PLAYLIST_URL, BD_UA_URL, MusicPagingRequest::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicPagingRequest::m_pageTotal, MusicAbstractNetwork::m_reply, MusicAbstractQueryRequest::m_searchText, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicBDQueryPlaylistRequest::startToSearch (QueryType type, const QString & playlist) override virtual
Start to Search data from name and type.
Implements MusicAbstractQueryRequest.
Definition at line 11 of file musicbdqueryplaylistrequest.cpp.
References MusicAbstractQueryRequest::m_searchText, MusicAbstractQueryRequest::MusicQuery, and startToPage().
void MusicBDQueryPlaylistRequest::startToSearch (const QString & playlist) override virtual
Start to Search data.
Implements MusicQueryPlaylistRequest.
Definition at line 48 of file musicbdqueryplaylistrequest.cpp.
References ALG_UA_KEY, BD_PLAYLIST_INFO_URL, BD_UA_URL, getDetailsFinished(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdqueryplaylistrequest.h
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdqueryplaylistrequest.cpp