TTKMusicPlayer: MusicWebDJRadioQueryWidget Class Reference
MusicWebDJRadioQueryWidget Class Reference
The class of the dj radio music query widget.
#include <musicwebdjradioquerywidget.h>
Public Slots
void createProgramItem (const MusicResultDataItem &item)
void currentItemClicked (const MusicResultDataItem &item)
void backToMainMenuClicked ()
void buttonClicked (int index)
Public Slots inherited from MusicAbstractItemQueryWidget
void downloadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Signals
void backToMainMenu ()
Public Member Functions
MusicWebDJRadioQueryWidget (QWidget *parent=nullptr)
~MusicWebDJRadioQueryWidget ()
virtual void setCurrentValue (const QString &value) overridefinal
virtual void setCurrentKey (const QString &id) overridefinal
virtual void resizeGeometry () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Attributes
bool m_initialized
QGridLayout * m_gridLayout
MusicPageQueryWidget * m_pageQueryWidget
MusicWebDJRadioInfoWidget * m_infoWidget
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void removeItems (QLayout *layout)
void createFirstWidget ()
void createSecondWidget ()
void setSongCountText ()
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_value
QWidget * m_mainWidget
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultDataItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_tableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Module m_shareType
QList< Data > m_resizeWidgets
Detailed Description
The class of the dj radio music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicwebdjradioquerywidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioQueryWidget::MusicWebDJRadioQueryWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicwebdjradioquerywidget.cpp.
References createProgramItem(), MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_infoWidget, m_initialized, MusicAbstractItemQueryWidget::m_mainWidget, MusicAbstractItemQueryWidget::m_networkRequest, and m_pageQueryWidget.
MusicWebDJRadioQueryWidget::~MusicWebDJRadioQueryWidget ()
Object destructor.
Definition at line 24 of file musicwebdjradioquerywidget.cpp.
References m_gridLayout, m_infoWidget, and m_pageQueryWidget.
Member Function Documentation
void MusicWebDJRadioQueryWidget::backToMainMenu () signal
Set current index to main menu page.
Referenced by backToMainMenuClicked(), createProgramItem(), and currentItemClicked().
void MusicWebDJRadioQueryWidget::backToMainMenuClicked () slot
Set current index to main menu page.
Definition at line 148 of file musicwebdjradioquerywidget.cpp.
References backToMainMenu(), MusicAbstractItemQueryWidget::m_container, and m_initialized.
Referenced by currentItemClicked().
void MusicWebDJRadioQueryWidget::buttonClicked (int index) slot
Page widget button has changed.
Definition at line 158 of file musicwebdjradioquerywidget.cpp.
References MusicPageQueryWidget::currentIndex(), m_gridLayout, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicPageQueryWidget::page(), MusicPageQueryRequest::pageTotalSize(), MusicAbstractItemQueryWidget::removeItems(), and MusicPageQueryRequest::startToPage().
Referenced by createProgramItem().
void MusicWebDJRadioQueryWidget::createProgramItem (const MusicResultDataItem & item) slot
Query all quality musics is finished.
Definition at line 70 of file musicwebdjradioquerywidget.cpp.
References backToMainMenu(), buttonClicked(), TTK::UI::ColorStyle12, MusicPageQueryWidget::createPageWidget(), currentItemClicked(), TTK::Widget::generateVScrollAreaStyle(), MusicSquareQueryItemWidget::LINE_SPACING_SIZE, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWidget, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_statusLabel, MusicPageQueryRequest::pageTotalSize(), TTK::UI::PushButtonStyle03, QUERY_WIDGET_WIDTH, MusicPageQueryWidget::reset(), MusicSquareQueryItemWidget::setResultDataItem(), MusicSquareQueryItemWidget::setShowCount(), MusicSquareQueryItemWidget::setShowTime(), and TTKObjectCast.
Referenced by MusicWebDJRadioQueryWidget().
void MusicWebDJRadioQueryWidget::currentItemClicked (const MusicResultDataItem & item) slot
Current radio clicked.
Definition at line 137 of file musicwebdjradioquerywidget.cpp.
References backToMainMenu(), backToMainMenuClicked(), MusicAbstractItemQueryWidget::m_container, MusicResultDataItem::m_id, m_infoWidget, and MusicWebDJRadioInfoWidget::setCurrentValue().
Referenced by createProgramItem(), and setCurrentKey().
void MusicWebDJRadioQueryWidget::resizeGeometry () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 45 of file musicwebdjradioquerywidget.cpp.
References MusicSquareQueryItemWidget::LINE_SPACING_SIZE, m_gridLayout, m_infoWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, qAsConst, QUERY_WIDGET_WIDTH, and MusicWebDJRadioInfoWidget::resizeGeometry().
Referenced by MusicWebDJRadioWidget::resizeGeometry().
void MusicWebDJRadioQueryWidget::setCurrentKey (const QString & id) final override virtual
Set current key to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 37 of file musicwebdjradioquerywidget.cpp.
References currentItemClicked(), MusicResultDataItem::m_id, and MusicAbstractItemQueryWidget::setCurrentValue().
Referenced by MusicWebDJRadioWidget::programItemClicked().
void MusicWebDJRadioQueryWidget::setCurrentValue (const QString & value) final override virtual
Set current value to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 31 of file musicwebdjradioquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::setCurrentValue(), and MusicAbstractQueryRequest::startToSearchByID().
Referenced by MusicWebDJRadioWidget::programItemClicked().
Member Data Documentation
QGridLayout* MusicWebDJRadioQueryWidget::m_gridLayout private
Definition at line 82 of file musicwebdjradioquerywidget.h.
Referenced by buttonClicked(), createProgramItem(), MusicWebDJRadioQueryWidget(), resizeGeometry(), and ~MusicWebDJRadioQueryWidget().
MusicWebDJRadioInfoWidget* MusicWebDJRadioQueryWidget::m_infoWidget private
Definition at line 84 of file musicwebdjradioquerywidget.h.
Referenced by currentItemClicked(), MusicWebDJRadioQueryWidget(), resizeGeometry(), and ~MusicWebDJRadioQueryWidget().
bool MusicWebDJRadioQueryWidget::m_initialized private
Definition at line 81 of file musicwebdjradioquerywidget.h.
Referenced by backToMainMenuClicked(), createProgramItem(), and MusicWebDJRadioQueryWidget().
MusicPageQueryWidget* MusicWebDJRadioQueryWidget::m_pageQueryWidget private
Definition at line 83 of file musicwebdjradioquerywidget.h.
Referenced by buttonClicked(), createProgramItem(), MusicWebDJRadioQueryWidget(), and ~MusicWebDJRadioQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradioquerywidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradioquerywidget.cpp