TTKMusicPlayer: MusicMPRISPlayerRoot Class Reference
MusicMPRISPlayerRoot Class Reference
The class of the app mpris root object.
#include <musicmprisplayer.h>
Public Slots
void Quit ()
void Raise ()
Public Member Functions
MusicMPRISPlayerRoot (QObject *parent=nullptr)
bool canQuit () const
bool canRaise () const
QString desktopEntry () const
bool hasTrackList () const
QString identity () const
QStringList supportedMimeTypes () const
QStringList supportedUriSchemes () const
Properties
bool CanQuit
bool CanRaise
QString DesktopEntry
bool HasTrackList
QString Identity
QStringList SupportedMimeTypes
QStringList SupportedUriSchemes
Detailed Description
The class of the app mpris root object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 65 of file musicmprisplayer.h.
Constructor & Destructor Documentation
MusicMPRISPlayerRoot::MusicMPRISPlayerRoot (QObject * parent = nullptr)
Object constructor.
Definition at line 37 of file musicmprisplayer.cpp.
Member Function Documentation
bool MusicMPRISPlayerRoot::canQuit () const
Definition at line 43 of file musicmprisplayer.cpp.
bool MusicMPRISPlayerRoot::canRaise () const
Definition at line 48 of file musicmprisplayer.cpp.
QString MusicMPRISPlayerRoot::desktopEntry () const
Definition at line 53 of file musicmprisplayer.cpp.
References TTK_APP_NAME.
bool MusicMPRISPlayerRoot::hasTrackList () const
Definition at line 58 of file musicmprisplayer.cpp.
QString MusicMPRISPlayerRoot::identity () const
Definition at line 63 of file musicmprisplayer.cpp.
References TTK_APP_NAME.
void MusicMPRISPlayerRoot::Quit () slot
Definition at line 87 of file musicmprisplayer.cpp.
References MusicApplication::instance(), and MusicApplication::quitWindow().
void MusicMPRISPlayerRoot::Raise () slot
Definition at line 92 of file musicmprisplayer.cpp.
References MusicApplication::instance().
QStringList MusicMPRISPlayerRoot::supportedMimeTypes () const
Definition at line 68 of file musicmprisplayer.cpp.
References AbstractEngine::contentTypes(), and Decoder::contentTypes().
QStringList MusicMPRISPlayerRoot::supportedUriSchemes () const
Definition at line 77 of file musicmprisplayer.cpp.
References MetaDataManager::instance(), and MetaDataManager::protocols().
Property Documentation
bool MusicMPRISPlayerRoot::CanQuit read
Definition at line 69 of file musicmprisplayer.h.
bool MusicMPRISPlayerRoot::CanRaise read
Definition at line 70 of file musicmprisplayer.h.
QString MusicMPRISPlayerRoot::DesktopEntry read
Definition at line 71 of file musicmprisplayer.h.
bool MusicMPRISPlayerRoot::HasTrackList read
Definition at line 72 of file musicmprisplayer.h.
QString MusicMPRISPlayerRoot::Identity read
Definition at line 73 of file musicmprisplayer.h.
QStringList MusicMPRISPlayerRoot::SupportedMimeTypes read
Definition at line 74 of file musicmprisplayer.h.
QStringList MusicMPRISPlayerRoot::SupportedUriSchemes read
Definition at line 75 of file musicmprisplayer.h.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicmprisplayer.h
TTKModule/TTKCore/musicCoreKits/musicmprisplayer.cpp