TTKMusicplayer: TTKModule/TTKCore/musicUtilsKits/musicurlutils.cpp File Reference
musicurlutils.cpp File Reference
#include "musicurlutils.h"
#include <QUrl>
#include <QProcess>
#include <QDesktopServices>
Functions
const MString ASCII_MAP (R"("%<>[\]^_`{|})")
const MString HEX_NUM_MAP ("0123456789ABCDEF")
unsigned char number2Char (const char h, const char l)
Function Documentation
const MString ASCII_MAP (R"("%<>[\]^_`{|})")
Referenced by MusicUtils::Url::urlPrettyEncode().
const MString HEX_NUM_MAP ("0123456789ABCDEF")
Referenced by number2Char(), and MusicUtils::Url::urlPrettyEncode().
unsigned char number2Char (const char h, const char l)
Definition at line 14 of file musicurlutils.cpp.
References HEX_NUM_MAP().
Referenced by MusicUtils::Url::urlPrettyDecode().