TTKMusicPlayer: MusicKWDownloadBackgroundRequest Class Reference
MusicKWDownloadBackgroundRequest Class Reference
The class of the kuwo download art background image.
#include <musickwdownloadimagerequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractDownloadImageRequest
void downLoadDataFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWDownloadBackgroundRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void startRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownloadImageRequest
MusicAbstractDownloadImageRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicAbstractDownloadImageRequest
int m_index
int m_counter
QString m_name
QString m_path
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the kuwo download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickwdownloadimagerequest.h.
Constructor & Destructor Documentation
MusicKWDownloadBackgroundRequest::MusicKWDownloadBackgroundRequest (const QString & name, const QString & path, QObject * parent = nullptr)
Object contsructor provide artist name and save local path.
Definition at line 6 of file musickwdownloadimagerequest.cpp.
Member Function Documentation
void MusicKWDownloadBackgroundRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 27 of file musickwdownloadimagerequest.cpp.
References TTK::Background, BACKGROUND_DIR_FULL, MusicAbstractDownloadImageRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractDownloadImageRequest::downLoadDataFinished(), MusicAbstractNetwork::downLoadFinished(), MusicAbstractDownloadImageRequest::m_counter, MusicAbstractDownloadImageRequest::m_path, MusicAbstractNetwork::m_reply, MAX_IMAGE_COUNT, QJson::Parser::parse(), SKN_FILE, MusicDownloadDataRequest::startRequest(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startRequest().
void MusicKWDownloadBackgroundRequest::startRequest () final override virtual
Start to download data from net.
Implements MusicAbstractDownloadImageRequest.
Definition at line 12 of file musickwdownloadimagerequest.cpp.
References ART_BACKGROUND_URL, MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractDownloadImageRequest::m_name, MusicAbstractNetwork::m_reply, TTK::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK::setSslConfiguration(), and TTK_INFO_STREAM.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/photo/musickwdownloadimagerequest.h
TTKModule/TTKCore/musicNetworkKits/image/photo/musickwdownloadimagerequest.cpp