TTKMusicplayer: MusicFPLConfigManager Class Reference
MusicFPLConfigManager Class Reference
The class of the foobar2k playlist Config Manager.
#include <musicfplconfigmanager.h>
Classes
struct FPLTrackChunk
Public Types
typedef struct MusicFPLConfigManager::FPLTrackChunk FPLTrackChunk
Public Member Functions
MusicFPLConfigManager ()
bool readConfig (const QString &name)
virtual void readPlaylistData (MusicSongItems &items) override
virtual void writePlaylistData (const MusicSongItems &items, const QString &path) override
Public Member Functions inherited from MusicPlaylistInterface
MusicPlaylistInterface ()
virtual ~MusicPlaylistInterface ()
Private Attributes
QString m_fileName
FPLTrackChunk m_chunkrunner
Detailed Description
The class of the foobar2k playlist Config Manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicfplconfigmanager.h.
Member Typedef Documentation
typedef struct MusicFPLConfigManager::FPLTrackChunk MusicFPLConfigManager::FPLTrackChunk
Constructor & Destructor Documentation
MusicFPLConfigManager::MusicFPLConfigManager () explicit
Object contsructor.
Definition at line 5 of file musicfplconfigmanager.cpp.
Member Function Documentation
bool MusicFPLConfigManager::readConfig (const QString & name)
Read datas from xml file by given name.
Definition at line 11 of file musicfplconfigmanager.cpp.
References m_fileName.
Referenced by MusicPlaylistManager::readFPLList().
void MusicFPLConfigManager::readPlaylistData (MusicSongItems & items) override virtual
Read datas from config file.
Implements MusicPlaylistInterface.
Definition at line 17 of file musicfplconfigmanager.cpp.
References MusicFPLConfigManager::FPLTrackChunk::duration_dbl, MusicFPLConfigManager::FPLTrackChunk::file_ofz, MusicFPLConfigManager::FPLTrackChunk::keys_dex, m_chunkrunner, m_fileName, MusicSongItem::m_itemName, MusicSongItem::m_songs, MusicTime::msecTime2LabelJustified(), MT_S2MS, and MusicUtils::Codec::toLocal8Bit().
Referenced by MusicPlaylistManager::readFPLList().
void MusicFPLConfigManager::writePlaylistData (const MusicSongItems & items, const QString & path) override virtual
Write datas into config file.
Implements MusicPlaylistInterface.
Definition at line 70 of file musicfplconfigmanager.cpp.
Member Data Documentation
FPLTrackChunk MusicFPLConfigManager::m_chunkrunner private
Definition at line 72 of file musicfplconfigmanager.h.
Referenced by readPlaylistData().
QString MusicFPLConfigManager::m_fileName private
Definition at line 71 of file musicfplconfigmanager.h.
Referenced by readConfig(), and readPlaylistData().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musicfplconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musicfplconfigmanager.cpp