TTKMusicplayer: MusicPlaylistFoundWidget Class Reference
MusicPlaylistFoundWidget Class Reference
The class of the playlist music found widget.
#include <musicplaylistfoundwidget.h>
Public Slots
void createPlaylistItem (const MusicResultsItem &item)
void currentPlaylistClicked (const MusicResultsItem &item)
void backToPlaylistMenu ()
void categoryChanged (const MusicResultsCategoryItem &category)
void buttonClicked (int index)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicPlaylistFoundWidget (QWidget *parent=nullptr)
virtual ~MusicPlaylistFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=nullptr)
~MusicFoundAbstractWidget ()
void initWidget ()
Protected Attributes
bool m_firstInit
bool m_categoryChanged
QGridLayout * m_gridLayout
MusicPagingWidgetObject * m_pagingWidgetObject
MusicPlaylistFoundInfoWidget * m_infoWidget
MusicPlaylistFoundCategoryPopWidget * m_categoryButton
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the playlist music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 78 of file musicplaylistfoundwidget.h.
Constructor & Destructor Documentation
MusicPlaylistFoundWidget::MusicPlaylistFoundWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 118 of file musicplaylistfoundwidget.cpp.
References createPlaylistItem(), m_categoryButton, m_categoryChanged, MusicFoundAbstractWidget::m_container, M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, m_infoWidget, MusicFoundAbstractWidget::m_mainWindow, and m_pagingWidgetObject.
MusicPlaylistFoundWidget::~MusicPlaylistFoundWidget () virtual
Definition at line 136 of file musicplaylistfoundwidget.cpp.
References m_categoryButton, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, m_infoWidget, and m_pagingWidgetObject.
Member Function Documentation
void MusicPlaylistFoundWidget::backToPlaylistMenu () slot
Set current index to playlist menu page.
Definition at line 272 of file musicplaylistfoundwidget.cpp.
References MusicFoundAbstractWidget::m_container, and PLAYLIST_WINDOW_INDEX_0.
void MusicPlaylistFoundWidget::buttonClicked (int index) slot
Paging widget button has changed.
Definition at line 296 of file musicplaylistfoundwidget.cpp.
References MusicPagingWidgetObject::currentIndex(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicPagingWidgetObject::paging(), and MusicDownLoadPagingThread::startToPage().
Referenced by createPlaylistItem().
void MusicPlaylistFoundWidget::categoryChanged (const MusicResultsCategoryItem & category) slot
Current category changed.
Definition at line 277 of file musicplaylistfoundwidget.cpp.
References MusicPlaylistFoundCategoryPopWidget::closeMenu(), m_categoryButton, m_categoryChanged, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, MusicResultsCategoryItem::m_id, MusicResultsCategoryItem::m_name, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_songNameFull, MusicDownLoadQueryThreadAbstract::OtherQuery, and MusicDownLoadQueryThreadAbstract::startToSearch().
void MusicPlaylistFoundWidget::createPlaylistItem (const MusicResultsItem & item) slot
Query all quality musics is finished.
Definition at line 182 of file musicplaylistfoundwidget.cpp.
References buttonClicked(), MusicPagingWidgetObject::createPagingWidget(), currentPlaylistClicked(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), MusicDownLoadQueryThreadAbstract::getQueryServer(), LINE_SPACING_SIZE, m_categoryButton, m_categoryChanged, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_downloadThread, m_firstInit, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, m_pagingWidgetObject, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_statusLabel, MusicUIObject::MColorStyle06, MusicUIObject::MColorStyle08, MusicUIObject::MScrollBarStyle01, MStatic_cast, MusicPagingWidgetObject::reset(), MusicPlaylistFoundCategoryPopWidget::setCategory(), and MusicPlaylistFoundItemWidget::setMusicResultsItem().
Referenced by MusicPlaylistFoundWidget().
void MusicPlaylistFoundWidget::currentPlaylistClicked (const MusicResultsItem & item) slot
Current play list clicked.
Definition at line 256 of file musicplaylistfoundwidget.cpp.
References MusicDownLoadQueryPlaylistThread::getPlaylistInfo(), MusicFoundAbstractWidget::m_container, M_DOWNLOAD_QUERY_PTR, m_infoWidget, MStatic_cast, PLAYLIST_WINDOW_INDEX_1, MusicPlaylistFoundInfoWidget::setMusicResultsItem(), and MusicPlaylistFoundInfoWidget::setQueryInput().
Referenced by createPlaylistItem(), and setSongNameById().
void MusicPlaylistFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 160 of file musicplaylistfoundwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, m_infoWidget, MusicFoundAbstractWidget::m_resizeWidgets, and MusicPlaylistFoundInfoWidget::resizeWindow().
void MusicPlaylistFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 145 of file musicplaylistfoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicDownLoadQueryThreadAbstract::OtherQuery, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicRightAreaWidget::musicPlaylistFound(), and setSongNameById().
void MusicPlaylistFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 151 of file musicplaylistfoundwidget.cpp.
References currentPlaylistClicked(), MusicResultsItem::m_id, and setSongName().
Referenced by MusicRightAreaWidget::musicPlaylistFound().
Member Data Documentation
MusicPlaylistFoundCategoryPopWidget* MusicPlaylistFoundWidget::m_categoryButton protected
Definition at line 131 of file musicplaylistfoundwidget.h.
Referenced by categoryChanged(), createPlaylistItem(), MusicPlaylistFoundWidget(), and ~MusicPlaylistFoundWidget().
bool MusicPlaylistFoundWidget::m_categoryChanged protected
Definition at line 127 of file musicplaylistfoundwidget.h.
Referenced by categoryChanged(), createPlaylistItem(), and MusicPlaylistFoundWidget().
bool MusicPlaylistFoundWidget::m_firstInit protected
Definition at line 127 of file musicplaylistfoundwidget.h.
Referenced by createPlaylistItem(), and MusicPlaylistFoundWidget().
QGridLayout* MusicPlaylistFoundWidget::m_gridLayout protected
Definition at line 128 of file musicplaylistfoundwidget.h.
Referenced by buttonClicked(), categoryChanged(), createPlaylistItem(), MusicPlaylistFoundWidget(), resizeWindow(), and ~MusicPlaylistFoundWidget().
MusicPlaylistFoundInfoWidget* MusicPlaylistFoundWidget::m_infoWidget protected
Definition at line 130 of file musicplaylistfoundwidget.h.
Referenced by currentPlaylistClicked(), MusicPlaylistFoundWidget(), resizeWindow(), and ~MusicPlaylistFoundWidget().
MusicPagingWidgetObject* MusicPlaylistFoundWidget::m_pagingWidgetObject protected
Definition at line 129 of file musicplaylistfoundwidget.h.
Referenced by buttonClicked(), createPlaylistItem(), MusicPlaylistFoundWidget(), and ~MusicPlaylistFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistfoundwidget.cpp