TTKMusicplayer: MusicBDTranslationRequest Class Reference
MusicBDTranslationRequest Class Reference
The class of baidu translation words request.
#include <musicbdtranslationrequest.h>
Public Types
enum TranslationType {
Type_Auto, Type_Ara, Type_De, Type_Ru,
Type_Fra, Type_Kor, Type_Nl, Type_Pt,
Type_Jp, Type_Th, Type_Wyw, Type_Spa,
Type_El, Type_It, Type_En, Type_Yue,
Type_Zh
}
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBDTranslationRequest (QObject *parent=nullptr)
virtual void startToDownload (const QString &data) override
void startToDownload (TranslationType from, TranslationType to, const QString &data)
Public Member Functions inherited from MusicTranslationRequest
MusicTranslationRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
QString mapTypeFromEnumToString (TranslationType type)
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of baidu translation words request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicbdtranslationrequest.h.
Member Enumeration Documentation
enum MusicBDTranslationRequest::TranslationType
Enumerator
Type_Auto
automatic detection
Type_Ara
Arabic
Type_De
German
Type_Ru
Russian
Type_Fra
French
Type_Kor
Korean
Type_Nl
Dutch
Type_Pt
Portuguese
Type_Jp
Japanese
Type_Th
Thai
Type_Wyw
Classical
Type_Spa
Spanish
Type_El
Greek
Type_It
Italian
Type_En
English
Type_Yue
Cantonese
Type_Zh
Chinese
Definition at line 32 of file musicbdtranslationrequest.h.
Constructor & Destructor Documentation
MusicBDTranslationRequest::MusicBDTranslationRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicbdtranslationrequest.cpp.
Member Function Documentation
void MusicBDTranslationRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 60 of file musicbdtranslationrequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicAbstractNetwork::m_reply, QJson::Parser::parse(), TTK_LOGGER_ERROR, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToDownload().
QString MusicBDTranslationRequest::mapTypeFromEnumToString (TranslationType type) protected
Map type from enum to string.
Definition at line 35 of file musicbdtranslationrequest.cpp.
References Type_Ara, Type_Auto, Type_De, Type_El, Type_En, Type_Fra, Type_It, Type_Jp, Type_Kor, Type_Nl, Type_Pt, Type_Ru, Type_Spa, Type_Th, Type_Wyw, Type_Yue, and Type_Zh.
Referenced by startToDownload().
void MusicBDTranslationRequest::startToDownload (const QString & data) override virtual
Start to translation data.
Implements MusicTranslationRequest.
Definition at line 11 of file musicbdtranslationrequest.cpp.
References Type_Auto, and Type_Zh.
void MusicBDTranslationRequest::startToDownload (TranslationType from, TranslationType to, const QString & data)
Start to translation data.
Definition at line 16 of file musicbdtranslationrequest.cpp.
References BD_TRANSLATION_URL, MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, mapTypeFromEnumToString(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdtranslationrequest.h
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdtranslationrequest.cpp