TTKMusicPlayer: TTKCommandLineParser Class Reference
TTKCommandLineParser Class Reference
The class of the command line parser.
#include <ttkcommandline.h>
Public Member Functions
TTKCommandLineParser ()=default
void addOption (const TTKCommandLineOption &option)
void process (const QStringList &arguments)
void process (const QCoreApplication &app)
bool isSet (const TTKCommandLineOption &option) const
QString value (const TTKCommandLineOption &option) const
bool isEmpty () const
void printHelp () const
Private Attributes
QHash< QString, QString > m_commands
QList< TTKCommandLineOption > m_options
Detailed Description
The class of the command line parser.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 79 of file ttkcommandline.h.
Constructor & Destructor Documentation
TTKCommandLineParser::TTKCommandLineParser () default
Object contsructor.
Member Function Documentation
void TTKCommandLineParser::addOption (const TTKCommandLineOption & option)
Add command line option.
Definition at line 5 of file ttkcommandline.cpp.
References TTKCommandLineOption::first(), m_options, and TTK_ERROR_STREAM.
Referenced by MusicConsoleModule::initialize(), and main().
bool TTKCommandLineParser::isEmpty () const inline
Current input command is empty.
Definition at line 114 of file ttkcommandline.h.
Referenced by MusicConsoleModule::initialize().
bool TTKCommandLineParser::isSet (const TTKCommandLineOption & option) const
Check current option is set.
Definition at line 38 of file ttkcommandline.cpp.
References TTKCommandLineOption::first(), m_commands, and TTKCommandLineOption::second().
Referenced by MusicConsoleModule::initialize(), and main().
void TTKCommandLineParser::printHelp () const
Print help text.
Definition at line 51 of file ttkcommandline.cpp.
References m_options, and TTK_LOG_STREAM.
Referenced by MusicConsoleModule::initialize().
void TTKCommandLineParser::process (const QStringList & arguments)
Process command line by input.
Definition at line 15 of file ttkcommandline.cpp.
References m_commands.
Referenced by MusicConsoleModule::initialize(), main(), and process().
void TTKCommandLineParser::process (const QCoreApplication & app)
Process command line by input.
Definition at line 33 of file ttkcommandline.cpp.
References process().
QString TTKCommandLineParser::value (const TTKCommandLineOption & option) const
Get command line option value.
Definition at line 44 of file ttkcommandline.cpp.
References TTKCommandLineOption::first(), m_commands, and TTKCommandLineOption::second().
Referenced by MusicConsoleModule::initialize(), and main().
Member Data Documentation
QHash<QString, QString> TTKCommandLineParser::m_commands private
Definition at line 122 of file ttkcommandline.h.
Referenced by isSet(), process(), and value().
QList<TTKCommandLineOption> TTKCommandLineParser::m_options private
Definition at line 123 of file ttkcommandline.h.
Referenced by addOption(), and printHelp().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkcommandline.h
TTKCommon/TTKLibrary/ttkcommandline.cpp