TTKMusicplayer: MusicDownloadTableWidget Class Reference
MusicDownloadTableWidget Class Reference
The class of the download table widget.
#include <musicdownloadwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) overridefinal
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Public Member Functions
MusicDownloadTableWidget (QWidget *parent=nullptr)
~MusicDownloadTableWidget ()
void clearAllItems ()
void createItem (const MusicObject::MusicSongProperty &prop, const QString &type, const QString &icon)
MusicDownloadTableItemRole currentItemRole () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
void clear ()
TTKIntList multiSelectedIndex () const
Protected Attributes
QList< QObject * > m_items
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Detailed Description
The class of the download table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 105 of file musicdownloadwidget.h.
Constructor & Destructor Documentation
MusicDownloadTableWidget::MusicDownloadTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 49 of file musicdownloadwidget.cpp.
References MusicUtils::Widget::setTransparent().
MusicDownloadTableWidget::~MusicDownloadTableWidget ()
Definition at line 60 of file musicdownloadwidget.cpp.
References clearAllItems().
Member Function Documentation
void MusicDownloadTableWidget::clearAllItems ()
Clear All Items.
Definition at line 65 of file musicdownloadwidget.cpp.
References MusicAbstractTableWidget::clear(), and m_items.
Referenced by ~MusicDownloadTableWidget().
void MusicDownloadTableWidget::createItem (const MusicObject::MusicSongProperty & prop, const QString & type, const QString & icon)
Create current item by given bitrate.
Definition at line 73 of file musicdownloadwidget.cpp.
References MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongProperty::m_format, m_items, MusicObject::MusicSongProperty::m_size, MusicDownloadTableItem::setIcon(), MusicDownloadTableItem::setInformation(), MusicDownloadTableItem::setText(), TABLE_ITEM_ROLE, and TTK_ITEM_SIZE_S.
MusicDownloadTableItemRole MusicDownloadTableWidget::currentItemRole () const
Get current bitrate from item.
Definition at line 93 of file musicdownloadwidget.cpp.
References TABLE_ITEM_ROLE.
void MusicDownloadTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 104 of file musicdownloadwidget.cpp.
Member Data Documentation
QList<QObject*> MusicDownloadTableWidget::m_items protected
Definition at line 136 of file musicdownloadwidget.h.
Referenced by clearAllItems(), and createItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadwidget.cpp