TTKMusicplayer: MusicLeftAreaWidget Class Reference
MusicLeftAreaWidget Class Reference
The class of the app left area widget.
#include <musicleftareawidget.h>
Public Slots
void musicDownloadSongToLocal ()
void musicDownloadSongFinished ()
void switchToSelectedItemStyle (int index)
void musicStackedSongListWidgetChanged ()
void musicStackedRadioWidgetChanged ()
void musicStackedMyDownWidgetChanged ()
void musicStackedMobileWidgetChanged ()
void musicStackedCloudWidgetChanged ()
Signals
void currentLoveStateChanged ()
void currentDownloadStateChanged ()
Public Member Functions
MusicLeftAreaWidget (QWidget *parent=nullptr)
~MusicLeftAreaWidget ()
void setupUi (Ui::MusicApplication *ui)
void radioExecuteOutside (const QString &path)
void musictLoveStateClicked (bool state)
void createSoundKMicroWidget (const QString &name)
Static Public Member Functions
static MusicLeftAreaWidget * instance ()
Protected Attributes
Ui::MusicApplication * m_ui
int m_currentIndex
QWidget * m_stackedWidget
MusicQualityChoicePopWidget * m_qualityChoiceWidget
MusicCloudSharedSongWidget * m_cloudSharedSongWidget
Static Protected Attributes
static MusicLeftAreaWidget * m_instance = nullptr
Detailed Description
The class of the app left area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicleftareawidget.h.
Constructor & Destructor Documentation
MusicLeftAreaWidget::MusicLeftAreaWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 18 of file musicleftareawidget.cpp.
References m_cloudSharedSongWidget, m_currentIndex, m_instance, m_qualityChoiceWidget, and m_stackedWidget.
MusicLeftAreaWidget::~MusicLeftAreaWidget ()
Definition at line 28 of file musicleftareawidget.cpp.
References m_cloudSharedSongWidget, m_qualityChoiceWidget, and m_stackedWidget.
Member Function Documentation
void MusicLeftAreaWidget::createSoundKMicroWidget (const QString & name)
Create sound KMicro widget.
Definition at line 102 of file musicleftareawidget.cpp.
References GENERATE_SINGLE_WIDGET_CLASS, and MusicSoundKMicroWidget::startSeachKMicro().
Referenced by MusicAbstractSongsListTableWidget::musicSongPlayedKMicroWidget(), and MusicLrcContainerForInterior::showSoundKMicroWidget().
void MusicLeftAreaWidget::currentDownloadStateChanged () signal
Current music download icon state changed.
Referenced by musicDownloadSongFinished().
void MusicLeftAreaWidget::currentLoveStateChanged () signal
Current music love icon state changed.
Referenced by musictLoveStateClicked().
MusicLeftAreaWidget * MusicLeftAreaWidget::instance () static
Get class object instance.
Definition at line 35 of file musicleftareawidget.cpp.
References m_instance.
Referenced by MusicDownloadResetWidget::MusicDownloadResetWidget(), MusicAbstractSongsListTableWidget::musicSongPlayedKMicroWidget(), MusicSongsListPlayedWidget::MusicSongsListPlayedWidget(), MusicSongsListPlayWidget::MusicSongsListPlayWidget(), and MusicLrcContainerForInterior::showSoundKMicroWidget().
void MusicLeftAreaWidget::musicDownloadSongFinished () slot
To download music data from net finished.
Definition at line 114 of file musicleftareawidget.cpp.
References currentDownloadStateChanged(), MusicApplication::instance(), m_ui, MusicUIObject::MQSSBtnDownload, MusicUIObject::MQSSBtnUnDownload, and MusicApplication::musicDownloadContains().
void MusicLeftAreaWidget::musicDownloadSongToLocal () slot
To download music data from net to load.
Definition at line 108 of file musicleftareawidget.cpp.
References m_ui, MusicAbstractQueryRequest::MusicQuery, and MusicDownloadMgmtWidget::setSongName().
Referenced by setupUi().
void MusicLeftAreaWidget::musicStackedCloudWidgetChanged () slot
Change to shared cloud widget.
Definition at line 184 of file musicleftareawidget.cpp.
References m_cloudSharedSongWidget, m_currentIndex, m_stackedWidget, m_ui, and MusicCloudSharedSongWidget::showMainWindow().
Referenced by switchToSelectedItemStyle().
void MusicLeftAreaWidget::musicStackedMobileWidgetChanged () slot
Change to mobile widget.
Definition at line 169 of file musicleftareawidget.cpp.
References m_currentIndex, m_stackedWidget, and m_ui.
Referenced by switchToSelectedItemStyle().
void MusicLeftAreaWidget::musicStackedMyDownWidgetChanged () slot
Change to my download widget.
Definition at line 154 of file musicleftareawidget.cpp.
References m_currentIndex, m_stackedWidget, and m_ui.
Referenced by switchToSelectedItemStyle().
void MusicLeftAreaWidget::musicStackedRadioWidgetChanged () slot
Change to radio widget.
Definition at line 136 of file musicleftareawidget.cpp.
References DEFAULT_NORMAL_LEVEL, MusicWebRadioView::initialize(), m_currentIndex, m_stackedWidget, and m_ui.
Referenced by radioExecuteOutside(), and switchToSelectedItemStyle().
void MusicLeftAreaWidget::musicStackedSongListWidgetChanged () slot
Change to song list widget.
Definition at line 122 of file musicleftareawidget.cpp.
References m_currentIndex, m_stackedWidget, and m_ui.
Referenced by switchToSelectedItemStyle().
void MusicLeftAreaWidget::musictLoveStateClicked (bool state)
Reset current music love icon state.
Definition at line 96 of file musicleftareawidget.cpp.
References currentLoveStateChanged(), m_ui, MusicUIObject::MQSSBtnLove, and MusicUIObject::MQSSBtnUnLove.
Referenced by MusicApplication::musicAddSongToLovestList().
void MusicLeftAreaWidget::radioExecuteOutside (const QString & path)
Execute outside radio by type.
Definition at line 89 of file musicleftareawidget.cpp.
References MusicWebRadioView::initialize(), m_stackedWidget, musicStackedRadioWidgetChanged(), and TTKStatic_cast.
Referenced by MusicApplication::radioExecuteOutside().
void MusicLeftAreaWidget::setupUi (Ui::MusicApplication * ui)
Set up app ui.
Definition at line 40 of file musicleftareawidget.cpp.
References MusicApplication::instance(), LEFT_SIDE_WIDTH_MIN, MusicAnimationStackedWidget::LeftToRight, m_qualityChoiceWidget, m_ui, MusicUIObject::MQSSBtnDKLrc, MusicUIObject::MQSSBtnMore, MusicUIObject::MQSSBtnNext, MusicUIObject::MQSSBtnPlay, MusicUIObject::MQSSBtnPrevious, MusicUIObject::MQSSBtnUnDownload, MusicUIObject::MQSSBtnUnLove, musicDownloadSongToLocal(), and switchToSelectedItemStyle().
Referenced by MusicApplication::MusicApplication().
void MusicLeftAreaWidget::switchToSelectedItemStyle (int index) slot
Switch to selected item style.
Definition at line 207 of file musicleftareawidget.cpp.
References MusicRightAreaWidget::instance(), m_ui, MusicRightAreaWidget::musicLrcDisplayAllButtonClicked(), musicStackedCloudWidgetChanged(), musicStackedMobileWidgetChanged(), musicStackedMyDownWidgetChanged(), musicStackedRadioWidgetChanged(), and musicStackedSongListWidgetChanged().
Referenced by setupUi().
Member Data Documentation
MusicCloudSharedSongWidget* MusicLeftAreaWidget::m_cloudSharedSongWidget protected
Definition at line 117 of file musicleftareawidget.h.
Referenced by MusicLeftAreaWidget(), musicStackedCloudWidgetChanged(), and ~MusicLeftAreaWidget().
int MusicLeftAreaWidget::m_currentIndex protected
Definition at line 114 of file musicleftareawidget.h.
Referenced by MusicLeftAreaWidget(), musicStackedCloudWidgetChanged(), musicStackedMobileWidgetChanged(), musicStackedMyDownWidgetChanged(), musicStackedRadioWidgetChanged(), and musicStackedSongListWidgetChanged().
MusicLeftAreaWidget * MusicLeftAreaWidget::m_instance = nullptr static protected
Definition at line 119 of file musicleftareawidget.h.
Referenced by instance(), and MusicLeftAreaWidget().
MusicQualityChoicePopWidget* MusicLeftAreaWidget::m_qualityChoiceWidget protected
Definition at line 116 of file musicleftareawidget.h.
Referenced by MusicLeftAreaWidget(), setupUi(), and ~MusicLeftAreaWidget().
QWidget* MusicLeftAreaWidget::m_stackedWidget protected
Definition at line 115 of file musicleftareawidget.h.
Referenced by MusicLeftAreaWidget(), musicStackedCloudWidgetChanged(), musicStackedMobileWidgetChanged(), musicStackedMyDownWidgetChanged(), musicStackedRadioWidgetChanged(), musicStackedSongListWidgetChanged(), radioExecuteOutside(), and ~MusicLeftAreaWidget().
Ui::MusicApplication* MusicLeftAreaWidget::m_ui protected
Definition at line 113 of file musicleftareawidget.h.
Referenced by musicDownloadSongFinished(), musicDownloadSongToLocal(), musicStackedCloudWidgetChanged(), musicStackedMobileWidgetChanged(), musicStackedMyDownWidgetChanged(), musicStackedRadioWidgetChanged(), musicStackedSongListWidgetChanged(), musictLoveStateClicked(), setupUi(), and switchToSelectedItemStyle().
The documentation for this class was generated from the following files:
TTKModule/musicleftareawidget.h
TTKModule/musicleftareawidget.cpp