TTKMusicPlayer: MusicSongMeta Class Reference
MusicSongMeta Class Reference
The class of the music song meta.
#include <musicsongmeta.h>
Public Member Functions
MusicSongMeta ()
~MusicSongMeta ()
bool read (const QString &url)
bool save ()
QString filePath () const
QString fileBasePath ()
QString fileRelatedPath ()
QString artist ()
QString title ()
QString album ()
QString comment ()
QString year ()
QString trackNum ()
QString genre ()
QString rating ()
QString channel ()
QString decoder ()
void setArtist (const QString &artist)
void setTitle (const QString &title)
void setAlbum (const QString &album)
void setComment (const QString &comment)
void setYear (const QString &year)
void setTrackNum (const QString &track)
void setGenre (const QString &genre)
void setRating (const QString &rating)
void setCover (const QPixmap &cover)
void setCover (const QByteArray &data)
QPixmap cover ()
QString lyrics ()
QString sampleRate ()
QString bitrate ()
QString duration ()
MusicSongMeta (const MusicSongMeta &other)
MusicSongMeta (MusicSongMeta &&other)
MusicSongMeta & operator= (const MusicSongMeta &other)
MusicSongMeta & operator= (MusicSongMeta &&other)
void setSongMetaIndex (int index)
int songMetaCount () const
Private Member Functions
void clearSongMeta ()
MusicMeta * songMeta ()
QString findLegalDataString (TagMeta::Type type)
bool readInformation ()
bool saveInformation ()
Private Attributes
int m_offset
QString m_path
QList< MusicMeta * > m_songMetas
Detailed Description
The class of the music song meta.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicsongmeta.h.
Constructor & Destructor Documentation
MusicSongMeta::MusicSongMeta ()
Object contsructor.
Definition at line 23 of file musicsongmeta.cpp.
MusicSongMeta::~MusicSongMeta ()
Definition at line 29 of file musicsongmeta.cpp.
References clearSongMeta().
MusicSongMeta::MusicSongMeta (const MusicSongMeta & other)
Definition at line 242 of file musicsongmeta.cpp.
References m_offset, m_path, and m_songMetas.
MusicSongMeta::MusicSongMeta (MusicSongMeta && other)
Definition at line 258 of file musicsongmeta.cpp.
Member Function Documentation
QString MusicSongMeta::album ()
Get song album.
Definition at line 94 of file musicsongmeta.cpp.
References TagMeta::ALBUM, and findLegalDataString().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicLocalManagerWidget::refreshItems(), saveInformation(), setAlbum(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongMeta::artist ()
Get artist name.
Definition at line 84 of file musicsongmeta.cpp.
References TagMeta::ARTIST, and findLegalDataString().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), TTK::generateSongList(), MusicLocalManagerWidget::refreshItems(), MusicSongCheckToolsRenameThread::run(), saveInformation(), setArtist(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongMeta::bitrate ()
Get song bitrate.
Definition at line 231 of file musicsongmeta.cpp.
References TagMeta::BITRATE, MusicMeta::m_metaData, songMeta(), and TTK_DEFAULT_STR.
Referenced by MusicSongRingtoneMaker::initInputPath(), readInformation(), MusicSongCheckToolsDuplicateThread::run(), MusicSongCheckToolsQualityThread::run(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongMeta::channel ()
Get song channel.
Definition at line 130 of file musicsongmeta.cpp.
References TagMeta::CHANNEL, MusicMeta::m_metaData, and songMeta().
Referenced by MusicFileInformationWidget::setFileInformation().
void MusicSongMeta::clearSongMeta () private
Clear music song meta.
Definition at line 312 of file musicsongmeta.cpp.
References m_offset, and m_songMetas.
Referenced by readInformation(), and ~MusicSongMeta().
QString MusicSongMeta::comment ()
Get song comment.
Definition at line 99 of file musicsongmeta.cpp.
References TagMeta::COMMENT, MusicMeta::m_metaData, and songMeta().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), and setComment().
QPixmap MusicSongMeta::cover ()
Get song image cover artist.
Definition at line 212 of file musicsongmeta.cpp.
References MusicMeta::m_cover, and songMeta().
Referenced by MusicFileInformationWidget::advanceClicked(), MusicFileInformationWidget::saveAlbumPicture(), saveInformation(), setCover(), MusicSongsListPlayWidget::setParameter(), and MusicSongsListItemInfoWidget::setSongInformation().
QString MusicSongMeta::decoder ()
Read music decoder name.
Definition at line 135 of file musicsongmeta.cpp.
References TagMeta::FORMAT, MusicMeta::m_metaData, and songMeta().
Referenced by MusicFileInformationWidget::setFileInformation().
QString MusicSongMeta::duration ()
Get song time duration.
Definition at line 237 of file musicsongmeta.cpp.
References TagMeta::LENGTH, MusicMeta::m_metaData, and songMeta().
Referenced by TTK::generateNetworkSongTime(), TTK::generateSongList(), MusicSongRingtoneMaker::initInputPath(), MusicFileInformationWidget::setFileInformation(), and MusicSongsListPlayWidget::setParameter().
QString MusicSongMeta::fileBasePath ()
Get file url.
Definition at line 74 of file musicsongmeta.cpp.
References MusicMeta::m_path, and songMeta().
Referenced by TTK::generateSongList().
QString MusicSongMeta::filePath () const
Read music file path.
Definition at line 69 of file musicsongmeta.cpp.
References m_path.
QString MusicSongMeta::fileRelatedPath ()
Get file related path.
Definition at line 79 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, songMeta(), and TagMeta::URL.
Referenced by MusicFileInformationWidget::setFileInformation().
QString MusicSongMeta::findLegalDataString (TagMeta::Type type) private
Find legal data string.
Definition at line 335 of file musicsongmeta.cpp.
References TTK::String::charactersReplace(), MusicMeta::m_metaData, and songMeta().
Referenced by album(), artist(), genre(), rating(), and title().
QString MusicSongMeta::genre ()
Get song genre.
Definition at line 120 of file musicsongmeta.cpp.
References findLegalDataString(), and TagMeta::GENRE.
Referenced by MusicLocalManagerWidget::refreshItems(), saveInformation(), MusicFileInformationWidget::setFileInformation(), and setGenre().
QString MusicSongMeta::lyrics ()
Get song lyrics buffer data.
Definition at line 221 of file musicsongmeta.cpp.
References MusicMeta::m_lyrics, and songMeta().
Referenced by TTK::generateSongList().
MusicSongMeta & MusicSongMeta::operator= (const MusicSongMeta & other)
Definition at line 266 of file musicsongmeta.cpp.
References m_offset, m_path, and m_songMetas.
MusicSongMeta & MusicSongMeta::operator= (MusicSongMeta && other)
Definition at line 284 of file musicsongmeta.cpp.
References m_offset, m_path, and m_songMetas.
QString MusicSongMeta::rating ()
Get song rating.
Definition at line 125 of file musicsongmeta.cpp.
References findLegalDataString(), and TagMeta::RATING.
Referenced by MusicFileInformationWidget::setFileInformation(), and setRating().
bool MusicSongMeta::read (const QString & url)
Read music file to anaylsis.
Definition at line 34 of file musicsongmeta.cpp.
References m_path, readInformation(), setSongMetaIndex(), and MusicFormats::songTrackValid().
Referenced by MusicFileInformationWidget::advanceClicked(), MusicDownloadMetaDataRequest::downLoadFinished(), TTK::generateNetworkSongTime(), TTK::generateSongList(), MusicSongRingtoneMaker::initInputPath(), MusicLocalManagerWidget::refreshItems(), MusicSongCheckToolsRenameThread::run(), MusicSongCheckToolsDuplicateThread::run(), MusicSongCheckToolsQualityThread::run(), MusicFileInformationWidget::saveAlbumPicture(), MusicFileInformationWidget::saveTag(), MusicFileInformationWidget::setFileInformation(), MusicSongsListPlayWidget::setParameter(), and MusicSongsListItemInfoWidget::setSongInformation().
bool MusicSongMeta::readInformation () private
Read other taglib not by plugin.
Definition at line 341 of file musicsongmeta.cpp.
References TagMeta::ALBUM, Qmmp::ALBUM, TrackInfo::AllParts, TagMeta::ARTIST, Qmmp::ARTIST, TagMeta::BITRATE, Qmmp::BITRATE, bitrate(), TagMeta::CHANNEL, Qmmp::CHANNELS, clearSongMeta(), TagMeta::COMMENT, Qmmp::COMMENT, MetaDataModel::cover(), DecoderFactory::createMetaDataModel(), DecoderFactory::createPlayList(), MetaDataModel::extraProperties(), Decoder::findByFilePath(), TagMeta::FORMAT, Qmmp::FORMAT_NAME, TTKTime::formatDuration(), TagMeta::GENRE, Qmmp::GENRE, TagMeta::LENGTH, MetaDataModel::lyrics(), MusicMeta::m_cover, MusicMeta::m_lyrics, MusicMeta::m_metaData, m_offset, MusicMeta::m_path, m_path, m_songMetas, TagMeta::musicTags(), TagMeta::RATING, TagMeta::readFile(), TagMeta::SAMPLERATE, Qmmp::SAMPLERATE, songMeta(), TagMeta::TITLE, Qmmp::TITLE, TagMeta::TRACK, Qmmp::TRACK, TagMeta::URL, TagMeta::YEAR, and Qmmp::YEAR.
Referenced by read().
QString MusicSongMeta::sampleRate ()
Get song sample rate.
Definition at line 226 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, TagMeta::SAMPLERATE, and songMeta().
Referenced by MusicSongRingtoneMaker::initInputPath(), and MusicFileInformationWidget::setFileInformation().
bool MusicSongMeta::save ()
Save music tags to music file.
Definition at line 64 of file musicsongmeta.cpp.
References saveInformation().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), and MusicFileInformationWidget::saveTag().
bool MusicSongMeta::saveInformation () private
Save other taglib not by plugin.
Definition at line 421 of file musicsongmeta.cpp.
References album(), Qmmp::ALBUM, artist(), Qmmp::ARTIST, cover(), DecoderFactory::createMetaDataModel(), Decoder::findByFilePath(), genre(), Qmmp::GENRE, m_path, MetaDataModel::removeCover(), TagModel::save(), MetaDataModel::setCover(), TagModel::setValue(), MetaDataModel::tags(), title(), Qmmp::TITLE, Qmmp::TRACK, trackNum(), year(), and Qmmp::YEAR.
Referenced by save().
void MusicSongMeta::setAlbum (const QString & album)
Set song album.
Definition at line 150 of file musicsongmeta.cpp.
References TagMeta::ALBUM, album(), MusicMeta::m_metaData, and songMeta().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startRequestMusic(), and MusicDownloadWidget::startRequestMusic().
void MusicSongMeta::setArtist (const QString & artist)
Set artist name.
Definition at line 140 of file musicsongmeta.cpp.
References TagMeta::ARTIST, artist(), MusicMeta::m_metaData, and songMeta().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startRequestMusic(), and MusicDownloadWidget::startRequestMusic().
void MusicSongMeta::setComment (const QString & comment)
Set song comment.
Definition at line 155 of file musicsongmeta.cpp.
References TagMeta::COMMENT, comment(), MusicMeta::m_metaData, and songMeta().
Referenced by MusicDownloadBatchTableItem::startRequestMusic(), and MusicDownloadWidget::startRequestMusic().
void MusicSongMeta::setCover (const QPixmap & cover)
Set song image cover artist.
Definition at line 180 of file musicsongmeta.cpp.
References cover(), MusicMeta::m_cover, and songMeta().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), and setCover().
void MusicSongMeta::setCover (const QByteArray & data)
Set song image cover artist.
Definition at line 196 of file musicsongmeta.cpp.
References setCover(), and TTK_ERROR_STREAM.
void MusicSongMeta::setGenre (const QString & genre)
Set song genre.
Definition at line 170 of file musicsongmeta.cpp.
References TagMeta::GENRE, genre(), MusicMeta::m_metaData, and songMeta().
Referenced by MusicFileInformationWidget::saveTag().
void MusicSongMeta::setRating (const QString & rating)
Set song rating.
Definition at line 175 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, TagMeta::RATING, rating(), and songMeta().
void MusicSongMeta::setSongMetaIndex (int index)
Set music song meta index offset.
Definition at line 297 of file musicsongmeta.cpp.
References m_offset, and songMetaCount().
Referenced by TTK::generateSongList(), and read().
void MusicSongMeta::setTitle (const QString & title)
Set song title.
Definition at line 145 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, songMeta(), TagMeta::TITLE, and title().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startRequestMusic(), and MusicDownloadWidget::startRequestMusic().
void MusicSongMeta::setTrackNum (const QString & track)
Set song track number.
Definition at line 165 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, songMeta(), and TagMeta::TRACK.
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicDownloadBatchTableItem::startRequestMusic(), and MusicDownloadWidget::startRequestMusic().
void MusicSongMeta::setYear (const QString & year)
Set song year.
Definition at line 160 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, songMeta(), TagMeta::YEAR, and year().
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicFileInformationWidget::saveTag(), MusicDownloadBatchTableItem::startRequestMusic(), and MusicDownloadWidget::startRequestMusic().
MusicMeta * MusicSongMeta::songMeta () private
Get music song meta pointer.
Definition at line 319 of file musicsongmeta.cpp.
References m_offset, m_songMetas, and songMetaCount().
Referenced by bitrate(), channel(), comment(), cover(), decoder(), duration(), fileBasePath(), fileRelatedPath(), findLegalDataString(), lyrics(), readInformation(), sampleRate(), setAlbum(), setArtist(), setComment(), setCover(), setGenre(), setRating(), setTitle(), setTrackNum(), setYear(), trackNum(), and year().
int MusicSongMeta::songMetaCount () const
Get music song meta count.
Definition at line 307 of file musicsongmeta.cpp.
References m_songMetas.
Referenced by TTK::generateSongList(), setSongMetaIndex(), and songMeta().
QString MusicSongMeta::title ()
Get song title.
Definition at line 89 of file musicsongmeta.cpp.
References findLegalDataString(), and TagMeta::TITLE.
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), TTK::generateSongList(), MusicLocalManagerWidget::refreshItems(), MusicSongCheckToolsRenameThread::run(), saveInformation(), MusicFileInformationWidget::setFileInformation(), and setTitle().
QString MusicSongMeta::trackNum ()
Get song track number.
Definition at line 109 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, songMeta(), TagMeta::TRACK, and TTK_DEFAULT_STR.
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), saveInformation(), and MusicFileInformationWidget::setFileInformation().
QString MusicSongMeta::year ()
Get song year.
Definition at line 104 of file musicsongmeta.cpp.
References MusicMeta::m_metaData, songMeta(), and TagMeta::YEAR.
Referenced by MusicDownloadMetaDataRequest::downLoadFinished(), MusicLocalManagerWidget::refreshItems(), saveInformation(), MusicFileInformationWidget::setFileInformation(), and setYear().
Member Data Documentation
int MusicSongMeta::m_offset private
Definition at line 205 of file musicsongmeta.h.
Referenced by clearSongMeta(), MusicSongMeta(), operator=(), readInformation(), setSongMetaIndex(), and songMeta().
QString MusicSongMeta::m_path private
Definition at line 206 of file musicsongmeta.h.
Referenced by filePath(), MusicSongMeta(), operator=(), read(), readInformation(), and saveInformation().
QList<MusicMeta*> MusicSongMeta::m_songMetas private
Definition at line 207 of file musicsongmeta.h.
Referenced by clearSongMeta(), MusicSongMeta(), operator=(), readInformation(), songMeta(), and songMetaCount().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicsongmeta.h
TTKModule/TTKCore/musicCoreKits/musicsongmeta.cpp