TTKMusicPlayer: MusicTransitionAnimationLabel Class Reference
MusicTransitionAnimationLabel Class Reference
The class of the label transition animation.
#include <musictransitionanimationlabel.h>
Public Types
enum Module {
Module::FadeEffect, Module::BlindsEffect, Module::CubeEffect, Module::WaterEffect,
Module::LeftToRightEffect, Module::TopToBottomEffect, Module::MAX = 6
}
Public Slots
void setPixmap (const QPixmap &pix)
Public Member Functions
MusicTransitionAnimationLabel (QWidget *parent=nullptr)
~MusicTransitionAnimationLabel ()
void setAnimation (bool enable) noexcept
bool animation () const noexcept
const QPixmap & renderPixmap () const noexcept
void start ()
void stop ()
bool isRunning () const
Private Slots
void valueChanged (const QVariant &value)
void animationFinished ()
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
Private Attributes
Module m_type
bool m_isAnimating
int m_currentValue
bool m_animationEnabled
QPixmap m_renderPixmap
QPixmap m_currentPixmap
QPixmap m_previousPixmap
QPropertyAnimation * m_animation
QAlgorithm::ImageRender * m_imageRender
Detailed Description
The class of the label transition animation.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musictransitionanimationlabel.h.
Member Enumeration Documentation
enum MusicTransitionAnimationLabel::Module strong
Enumerator
FadeEffect
BlindsEffect
CubeEffect
WaterEffect
LeftToRightEffect
TopToBottomEffect
MAX
Definition at line 39 of file musictransitionanimationlabel.h.
Constructor & Destructor Documentation
MusicTransitionAnimationLabel::MusicTransitionAnimationLabel (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 9 of file musictransitionanimationlabel.cpp.
References animationFinished(), TTK::initRandom(), m_animation, and valueChanged().
MusicTransitionAnimationLabel::~MusicTransitionAnimationLabel ()
Object destructor.
Definition at line 29 of file musictransitionanimationlabel.cpp.
References m_animation, and m_imageRender.
Member Function Documentation
bool MusicTransitionAnimationLabel::animation () const inline noexcept
Get animation state.
Definition at line 66 of file musictransitionanimationlabel.h.
void MusicTransitionAnimationLabel::animationFinished () private slot
Animation finished.
Definition at line 133 of file musictransitionanimationlabel.cpp.
References m_currentPixmap, m_currentValue, m_isAnimating, and m_renderPixmap.
Referenced by MusicTransitionAnimationLabel(), and stop().
bool MusicTransitionAnimationLabel::isRunning () const
Get animation is in run state.
Definition at line 56 of file musictransitionanimationlabel.cpp.
References m_animation.
Referenced by stop().
void MusicTransitionAnimationLabel::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 142 of file musictransitionanimationlabel.cpp.
References BlindsEffect, CubeEffect, FadeEffect, LeftToRightEffect, m_currentPixmap, m_currentValue, m_imageRender, m_isAnimating, m_previousPixmap, m_renderPixmap, m_type, QAlgorithm::ImageRender::render(), TopToBottomEffect, and WaterEffect.
const QPixmap & MusicTransitionAnimationLabel::renderPixmap () const noexcept
Get render pixmap image.
Definition at line 35 of file musictransitionanimationlabel.cpp.
References m_renderPixmap.
void MusicTransitionAnimationLabel::setAnimation (bool enable) inline noexcept
Set animation to start.
Definition at line 62 of file musictransitionanimationlabel.h.
void MusicTransitionAnimationLabel::setPixmap (const QPixmap & pix) slot
Override the setPixmap function.
Definition at line 61 of file musictransitionanimationlabel.cpp.
References BlindsEffect, CubeEffect, FadeEffect, QAlgorithm::ImageRender::input(), LeftToRightEffect, m_animation, m_animationEnabled, m_currentPixmap, m_imageRender, m_isAnimating, m_previousPixmap, m_renderPixmap, m_type, MAX, QtLablePixmap, TTK::random(), stop(), TopToBottomEffect, TTKStaticCast, and WaterEffect.
Referenced by MusicScreenSaverBackgroundWidget::backgroundTimeout(), and MusicLrcContainerForWallpaper::updateBackground().
void MusicTransitionAnimationLabel::start ()
Start renderer pixmap animation.
Definition at line 40 of file musictransitionanimationlabel.cpp.
References m_animation, m_isAnimating, and stop().
void MusicTransitionAnimationLabel::stop ()
Stop renderer pixmap animation.
Definition at line 47 of file musictransitionanimationlabel.cpp.
References animationFinished(), isRunning(), and m_animation.
Referenced by setPixmap(), and start().
void MusicTransitionAnimationLabel::valueChanged (const QVariant & value) private slot
Animation value changed.
Definition at line 127 of file musictransitionanimationlabel.cpp.
References m_currentValue.
Referenced by MusicTransitionAnimationLabel().
Member Data Documentation
QPropertyAnimation* MusicTransitionAnimationLabel::m_animation private
Definition at line 115 of file musictransitionanimationlabel.h.
Referenced by isRunning(), MusicTransitionAnimationLabel(), setPixmap(), start(), stop(), and ~MusicTransitionAnimationLabel().
bool MusicTransitionAnimationLabel::m_animationEnabled private
Definition at line 112 of file musictransitionanimationlabel.h.
Referenced by setPixmap().
QPixmap MusicTransitionAnimationLabel::m_currentPixmap private
Definition at line 114 of file musictransitionanimationlabel.h.
Referenced by animationFinished(), paintEvent(), and setPixmap().
int MusicTransitionAnimationLabel::m_currentValue private
Definition at line 111 of file musictransitionanimationlabel.h.
Referenced by animationFinished(), paintEvent(), and valueChanged().
QAlgorithm::ImageRender* MusicTransitionAnimationLabel::m_imageRender private
Definition at line 116 of file musictransitionanimationlabel.h.
Referenced by paintEvent(), setPixmap(), and ~MusicTransitionAnimationLabel().
bool MusicTransitionAnimationLabel::m_isAnimating private
Definition at line 110 of file musictransitionanimationlabel.h.
Referenced by animationFinished(), paintEvent(), setPixmap(), and start().
QPixmap MusicTransitionAnimationLabel::m_previousPixmap private
Definition at line 114 of file musictransitionanimationlabel.h.
Referenced by paintEvent(), and setPixmap().
QPixmap MusicTransitionAnimationLabel::m_renderPixmap private
Definition at line 113 of file musictransitionanimationlabel.h.
Referenced by animationFinished(), paintEvent(), renderPixmap(), and setPixmap().
Module MusicTransitionAnimationLabel::m_type private
Definition at line 109 of file musictransitionanimationlabel.h.
Referenced by paintEvent(), and setPixmap().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musictransitionanimationlabel.h
TTKModule/TTKWidget/musicCoreKits/musictransitionanimationlabel.cpp