TTKMusicPlayer: MusicDownloadMetaDataRequest Class Reference
MusicDownloadMetaDataRequest Class Reference
The class of the download the type of data by custom tags.
#include <musicdownloadmetadatarequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadFinished (const QByteArray &bytes)
Public Slots inherited from MusicDownloadDataRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal) overridefinal
virtual void updateDownloadSpeed () overridefinal
void handleReadyRead ()
Public Slots inherited from MusicAbstractDownLoadRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void finished ()
Signals inherited from MusicDownloadDataRequest
void downloadUrlChanged (const QString &url)
void downloadSpeedLabelChanged (const QString &speed, qint64 timeLeft)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Public Member Functions
MusicDownloadMetaDataRequest (const QString &url, const QString &path, QObject *parent=nullptr)
MusicDownloadMetaDataRequest (const QString &url, const QString &path, TTK::Record record, QObject *parent=nullptr)
void setSongMeta (MusicSongMeta &meta)
virtual void startToRequest () overridefinal
Public Member Functions inherited from MusicDownloadDataRequest
MusicDownloadDataRequest (const QString &url, const QString &path, TTK::Download type, QObject *parent=nullptr)
MusicDownloadDataRequest (const QString &url, const QString &path, TTK::Download type, TTK::Record record, QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractDownLoadRequest
MusicAbstractDownLoadRequest (const QString &url, const QString &path, TTK::Download type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Attributes
MusicSongMeta m_songMeta
Additional Inherited Members
Protected Member Functions inherited from MusicDownloadDataRequest
void startToRequest (const QString &url)
Protected Member Functions inherited from MusicAbstractDownLoadRequest
QString mapCurrentQueryData () const
Protected Attributes inherited from MusicDownloadDataRequest
qint64 m_createTime
bool m_redirection
bool m_needUpdate
TTK::Record m_recordType
Protected Attributes inherited from MusicAbstractDownLoadRequest
QFile * m_file
QString m_url
QString m_savePath
TTK::Download m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the download the type of data by custom tags.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadmetadatarequest.h.
Constructor & Destructor Documentation
MusicDownloadMetaDataRequest::MusicDownloadMetaDataRequest (const QString & url, const QString & path, QObject * parent = nullptr)
Object constructor provide download url save local path and download type.
Definition at line 5 of file musicdownloadmetadatarequest.cpp.
MusicDownloadMetaDataRequest::MusicDownloadMetaDataRequest (const QString & url, const QString & path, TTK::Record record, QObject * parent = nullptr)
Definition at line 11 of file musicdownloadmetadatarequest.cpp.
References MusicDownloadDataRequest::m_needUpdate.
Member Function Documentation
void MusicDownloadMetaDataRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 37 of file musicdownloadmetadatarequest.cpp.
References MusicSongMeta::comment(), TTKAbstractNetwork::downLoadDataChanged(), MusicDownloadDataRequest::downLoadFinished(), TTKAbstractNetwork::downLoadRawDataChanged(), TTKSemaphoreLoop::exec(), finished(), G_DOWNLOAD_QUERY_PTR, MusicAbstractDownLoadRequest::m_file, MusicDownloadDataRequest::m_redirection, m_songMeta, MusicAbstractDownLoadRequest::mapCurrentQueryData(), MusicCoverRequest::startToRequest(), and TTK_INFO_STREAM.
Referenced by startToRequest().
void MusicDownloadMetaDataRequest::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 62 of file musicdownloadmetadatarequest.cpp.
References MusicSongMeta::album(), MusicSongMeta::artist(), finished(), G_SETTING_PTR, MusicAbstractDownLoadRequest::m_savePath, m_songMeta, MusicSettingManager::OtherWriteAlbumCover, MusicSettingManager::OtherWriteFileInfo, MusicSongMeta::read(), MusicSongMeta::save(), MusicSongMeta::setAlbum(), MusicSongMeta::setArtist(), MusicSongMeta::setCover(), MusicSongMeta::setTitle(), MusicSongMeta::setTrackNum(), MusicSongMeta::setYear(), MusicSongMeta::title(), MusicSongMeta::trackNum(), TTK_ERROR_STREAM, TTK_INFO_STREAM, and MusicSongMeta::year().
void MusicDownloadMetaDataRequest::finished () signal
Modify tag finished.
Referenced by downLoadFinished(), and startToRequest().
void MusicDownloadMetaDataRequest::setSongMeta (MusicSongMeta & meta)
Set custom tags.
Definition at line 17 of file musicdownloadmetadatarequest.cpp.
References m_songMeta.
Referenced by MusicDownloadWidget::startToRequestMusic().
void MusicDownloadMetaDataRequest::startToRequest () final override virtual
Start to download meta data.
Reimplemented from MusicDownloadDataRequest.
Definition at line 22 of file musicdownloadmetadatarequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), downLoadFinished(), finished(), MusicAbstractDownLoadRequest::m_file, TTKAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::m_url, MusicDownloadDataRequest::startToRequest(), and TTK_ERROR_STREAM.
Referenced by MusicDownloadWidget::startToRequestMusic().
Member Data Documentation
MusicSongMeta MusicDownloadMetaDataRequest::m_songMeta private
Definition at line 65 of file musicdownloadmetadatarequest.h.
Referenced by downLoadFinished(), and setSongMeta().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadmetadatarequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicdownloadmetadatarequest.cpp