TTKMusicplayer: MusicProgressWidget Class Reference
MusicProgressWidget Class Reference
The class of the show progress widget.
#include <musicprogresswidget.h>
Public Slots
void show ()
Public Member Functions
MusicProgressWidget (QWidget *parent=nullptr)
~MusicProgressWidget ()
void setTitle (const QString &name)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void resizeEvent (QResizeEvent *event) overridefinal
void initWidget ()
Protected Attributes
QLabel * m_background
QLabel * m_textLabel
QProgressBar * m_progressBar
Detailed Description
The class of the show progress widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicprogresswidget.h.
Constructor & Destructor Documentation
MusicProgressWidget::MusicProgressWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicprogresswidget.cpp.
References initWidget().
MusicProgressWidget::~MusicProgressWidget ()
Definition at line 23 of file musicprogresswidget.cpp.
References m_background, m_progressBar, and m_textLabel.
Member Function Documentation
void MusicProgressWidget::initWidget () protected
Create all widget in layout.
Definition at line 30 of file musicprogresswidget.cpp.
References m_background, m_progressBar, m_textLabel, MusicUIObject::MQSSBackgroundStyle13, MusicUIObject::MQSSColorStyle01, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSProgressBar01, and MusicUIObject::MQSSToolButtonStyle04.
Referenced by MusicProgressWidget().
void MusicProgressWidget::paintEvent (QPaintEvent * event) final override protected virtual
Override the widget event.
Definition at line 69 of file musicprogresswidget.cpp.
References MusicUtils::Widget::setBorderShadow().
void MusicProgressWidget::resizeEvent (QResizeEvent * event) final override protected virtual
Definition at line 63 of file musicprogresswidget.cpp.
References m_progressBar.
void MusicProgressWidget::setTitle (const QString & name)
Set widget title.
Definition at line 58 of file musicprogresswidget.cpp.
References m_textLabel.
Referenced by MusicSongsSummariziedWidget::importMusicSongsByPath(), and MusicSongsListTableWidget::setDeleteItemAt().
void MusicProgressWidget::show () slot
Override show function.
Definition at line 76 of file musicprogresswidget.cpp.
References G_BACKGROUND_PTR, m_background, MusicBackgroundImage::m_pix, and MusicExtractWrapper::outputSkin().
Referenced by MusicSongsSummariziedWidget::importMusicSongsByPath(), and MusicSongsListTableWidget::setDeleteItemAt().
Member Data Documentation
QLabel* MusicProgressWidget::m_background protected
Definition at line 63 of file musicprogresswidget.h.
Referenced by initWidget(), show(), and ~MusicProgressWidget().
QProgressBar* MusicProgressWidget::m_progressBar protected
Definition at line 64 of file musicprogresswidget.h.
Referenced by initWidget(), resizeEvent(), and ~MusicProgressWidget().
QLabel * MusicProgressWidget::m_textLabel protected
Definition at line 63 of file musicprogresswidget.h.
Referenced by initWidget(), setTitle(), and ~MusicProgressWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicprogresswidget.h
TTKModule/TTKWidget/musicCoreKits/musicprogresswidget.cpp