TTKMusicplayer: MusicRemoteWidgetForRipple Class Reference
MusicRemoteWidgetForRipple Class Reference
The class of the desktop ripple remote widget.
#include <musicremotewidgetforripple.h>
Public Slots
void visualModeChanged ()
Public Slots inherited from MusicRemoteWidget
void musicVolumeSliderChanged (int value)
void show ()
bool close ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicRemoteWidgetForRipple (QWidget *parent=nullptr)
~MusicRemoteWidgetForRipple ()
virtual void setLabelText (const QString &value) override
Public Member Functions inherited from MusicRemoteWidget
MusicRemoteWidget (QWidget *parent=nullptr)
~MusicRemoteWidget ()
void setCurrentPlayStatus (bool status) const
void setVolumeValue (int index)
int mapRemoteTypeIndex ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void createVisualWidget ()
void removeVisualWidget ()
Protected Member Functions inherited from MusicRemoteWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
void adjustPosition (QWidget *w)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
bool m_mode
QWidget * m_visual
QVBoxLayout * m_visualLayout
QPushButton * m_visualModeButton
MusicMarqueeWidget * m_songNameLabel
Protected Attributes inherited from MusicRemoteWidget
QPushButton * m_showMainWindowButton
QPushButton * m_preSongButton
QPushButton * m_nextSongButton
QPushButton * m_playButton
QPushButton * m_settingButton
QWidget * m_mainWidget
QWidget * m_volumeWidget
QToolButton * m_volumeButton
MusicClickedSlider * m_volumeSlider
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Public Types inherited from MusicRemoteWidget
enum RemoteType {
Null = 0, Square, Rectangle, SimpleStyle,
ComplexStyle, Ripple
}
Signals inherited from MusicRemoteWidget
void musicWindowChanged ()
void musicKeyChanged ()
void musicPlayPreviousChanged ()
void musicPlayNextChanged ()
void musicVolumeChanged (int value)
void musicSettingChanged ()
void musicRemoteTypeChanged (QAction *type)
Detailed Description
The class of the desktop ripple remote widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicremotewidgetforripple.h.
Constructor & Destructor Documentation
MusicRemoteWidgetForRipple::MusicRemoteWidgetForRipple (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicremotewidgetforripple.cpp.
References MusicRemoteWidget::adjustPosition(), createVisualWidget(), MusicRemoteWidget::m_mainWidget, m_mode, MusicRemoteWidget::m_nextSongButton, MusicRemoteWidget::m_playButton, MusicRemoteWidget::m_preSongButton, MusicRemoteWidget::m_settingButton, MusicRemoteWidget::m_showMainWindowButton, m_songNameLabel, m_visual, m_visualLayout, m_visualModeButton, MusicRemoteWidget::m_volumeWidget, MusicUIObject::MQSSTinyBtnVisual, MusicUIObject::MQSSWidgetStyle01, and visualModeChanged().
MusicRemoteWidgetForRipple::~MusicRemoteWidgetForRipple ()
Definition at line 61 of file musicremotewidgetforripple.cpp.
References m_songNameLabel, m_visualModeButton, and removeVisualWidget().
Member Function Documentation
void MusicRemoteWidgetForRipple::createVisualWidget () protected
Create visual widget.
Definition at line 80 of file musicremotewidgetforripple.cpp.
References MusicUtils::QMMP::enabledVisualPlugin(), m_mode, m_visual, m_visualLayout, and Visual::visuals().
Referenced by MusicRemoteWidgetForRipple(), and visualModeChanged().
void MusicRemoteWidgetForRipple::removeVisualWidget () protected
Remove visual widget.
Definition at line 92 of file musicremotewidgetforripple.cpp.
References MusicUtils::QMMP::enabledVisualPlugin(), m_mode, m_visual, and m_visualLayout.
Referenced by visualModeChanged(), and ~MusicRemoteWidgetForRipple().
void MusicRemoteWidgetForRipple::setLabelText (const QString & value) override virtual
Set current song text.
Reimplemented from MusicRemoteWidget.
Definition at line 68 of file musicremotewidgetforripple.cpp.
References MusicUtils::Widget::elidedText(), m_songNameLabel, and MusicMarqueeWidget::setText().
void MusicRemoteWidgetForRipple::visualModeChanged () slot
Visual mode changed.
Definition at line 73 of file musicremotewidgetforripple.cpp.
References createVisualWidget(), m_mode, and removeVisualWidget().
Referenced by MusicRemoteWidgetForRipple().
Member Data Documentation
bool MusicRemoteWidgetForRipple::m_mode protected
Definition at line 61 of file musicremotewidgetforripple.h.
Referenced by createVisualWidget(), MusicRemoteWidgetForRipple(), removeVisualWidget(), and visualModeChanged().
MusicMarqueeWidget* MusicRemoteWidgetForRipple::m_songNameLabel protected
Definition at line 65 of file musicremotewidgetforripple.h.
Referenced by MusicRemoteWidgetForRipple(), setLabelText(), and ~MusicRemoteWidgetForRipple().
QWidget* MusicRemoteWidgetForRipple::m_visual protected
Definition at line 62 of file musicremotewidgetforripple.h.
Referenced by createVisualWidget(), MusicRemoteWidgetForRipple(), and removeVisualWidget().
QVBoxLayout* MusicRemoteWidgetForRipple::m_visualLayout protected
Definition at line 63 of file musicremotewidgetforripple.h.
Referenced by createVisualWidget(), MusicRemoteWidgetForRipple(), and removeVisualWidget().
QPushButton* MusicRemoteWidgetForRipple::m_visualModeButton protected
Definition at line 64 of file musicremotewidgetforripple.h.
Referenced by MusicRemoteWidgetForRipple(), and ~MusicRemoteWidgetForRipple().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforripple.h
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforripple.cpp