TTKMusicplayer: MusicVideoQualityPopWidget Class Reference
MusicVideoQualityPopWidget Class Reference
The class of the video quality popup widget.
#include <musicvideoqualitypopwidget.h>
Public Slots
void movieQualityChoiced (QAction *action)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Signals
void queryMusicMediaInfo (MusicObject::MusicSongAttributes &data)
void mediaUrlChanged (const QString &data)
Public Member Functions
MusicVideoQualityPopWidget (QWidget *parent=nullptr)
~MusicVideoQualityPopWidget ()
void setQualityActionState ()
void setQualityText (const QString &url)
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initWidget ()
QString findMVUrlByBitrate (int bitrate)
int findMVBitrateByUrl (const QString &url)
bool findExistByBitrate (int bitrate)
Protected Attributes
QActionGroup * m_actionGroup
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the video quality popup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicvideoqualitypopwidget.h.
Constructor & Destructor Documentation
MusicVideoQualityPopWidget::MusicVideoQualityPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicvideoqualitypopwidget.cpp.
References G_CONNECTION_PTR, initWidget(), and MusicUIObject::MQSSVideoBtnSDMode.
MusicVideoQualityPopWidget::~MusicVideoQualityPopWidget ()
Definition at line 18 of file musicvideoqualitypopwidget.cpp.
References G_CONNECTION_PTR, and m_actionGroup.
Member Function Documentation
bool MusicVideoQualityPopWidget::findExistByBitrate (int bitrate) protected
Check given bitrate is exist or not.
Definition at line 112 of file musicvideoqualitypopwidget.cpp.
References queryMusicMediaInfo().
Referenced by setQualityActionState().
int MusicVideoQualityPopWidget::findMVBitrateByUrl (const QString & url) protected
Find mv bitrate by given url.
Definition at line 96 of file musicvideoqualitypopwidget.cpp.
References queryMusicMediaInfo().
Referenced by setQualityText().
QString MusicVideoQualityPopWidget::findMVUrlByBitrate (int bitrate) protected
Find mv url by given bitrate.
Definition at line 81 of file musicvideoqualitypopwidget.cpp.
References queryMusicMediaInfo().
Referenced by movieQualityChoiced().
void MusicVideoQualityPopWidget::initWidget () protected
Create all widget in layout.
Definition at line 65 of file musicvideoqualitypopwidget.cpp.
References m_actionGroup, MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, movieQualityChoiced(), setQualityActionState(), and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicVideoQualityPopWidget().
void MusicVideoQualityPopWidget::mediaUrlChanged (const QString & data) signal
Set current media url by selected quality.
Referenced by movieQualityChoiced().
void MusicVideoQualityPopWidget::movieQualityChoiced (QAction * action) slot
Movie quality choiced by index.
Definition at line 50 of file musicvideoqualitypopwidget.cpp.
References findMVUrlByBitrate(), MB_1000, MB_250, MB_500, MB_750, mediaUrlChanged(), and setQualityText().
Referenced by initWidget().
void MusicVideoQualityPopWidget::queryMusicMediaInfo (MusicObject::MusicSongAttributes & data) signal
Query music media information data.
Referenced by findExistByBitrate(), findMVBitrateByUrl(), and findMVUrlByBitrate().
void MusicVideoQualityPopWidget::setQualityActionState ()
Set quality action state enable or disable.
Definition at line 24 of file musicvideoqualitypopwidget.cpp.
References findExistByBitrate(), m_actionGroup, MB_1000, MB_250, MB_500, and MB_750.
Referenced by initWidget(), and MusicVideoControlWidget::setQualityActionState().
void MusicVideoQualityPopWidget::setQualityText (const QString & url)
Set current media quality text.
Definition at line 36 of file musicvideoqualitypopwidget.cpp.
References findMVBitrateByUrl(), MB_1000, MB_250, MB_500, MB_750, MusicUIObject::MQSSVideoBtnHDMode, MusicUIObject::MQSSVideoBtnSDMode, MusicUIObject::MQSSVideoBtnSQMode, and MusicUIObject::MQSSVideoBtnSTMode.
Referenced by MusicVideoControlWidget::mediaChanged(), and movieQualityChoiced().
Member Data Documentation
QActionGroup* MusicVideoQualityPopWidget::m_actionGroup protected
Definition at line 81 of file musicvideoqualitypopwidget.h.
Referenced by initWidget(), setQualityActionState(), and ~MusicVideoQualityPopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideoqualitypopwidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideoqualitypopwidget.cpp