TTKMusicplayer: MusicApplicationMPRISPlayer Class Reference
MusicApplicationMPRISPlayer Class Reference
The class of the app mpris player object.
#include <musicapplicationmprismodule.h>
Public Slots
void Next ()
void Previous ()
void OpenUri (const QString &uri)
void Pause ()
void Play ()
void PlayPause ()
void Stop ()
void Seek (qlonglong offset)
void SetPosition (const QDBusObjectPath &trackId, qlonglong position)
Signals
void Seeked (qlonglong position)
Public Member Functions
MusicApplicationMPRISPlayer (QObject *parent=nullptr)
bool canControl () const
bool canGoNext () const
bool canGoPrevious () const
bool canPause () const
bool canPlay () const
bool canSeek () const
QString loopStatus () const
void setLoopStatus (const QString &value)
double maximumRate () const
QVariantMap metadata () const
double minimumRate () const
QString playbackStatus () const
qlonglong position () const
double rate () const
void setRate (double value)
bool shuffle () const
void setShuffle (bool value)
double volume () const
void setVolume (double value)
Properties
bool CanControl
bool CanGoNext
bool CanGoPrevious
bool CanPause
bool CanPlay
bool CanSeek
QString LoopStatus
double MaximumRate
QVariantMap Metadata
double MinimumRate
QString PlaybackStatus
qlonglong Position
double Rate
bool Shuffle
double Volume
Private Slots
void trackInfoChanged ()
void stateChanged ()
void volumeChanged ()
void elapsedChanged (qint64 elapsed)
void playbackModeChanged ()
Private Member Functions
void updateTrackID ()
void syncProperties ()
void sendProperties ()
Private Attributes
int m_prev_track
qint64 m_prev_pos
SoundCore * m_music
MusicApplication * m_player
QDBusObjectPath m_trackID
TTKVariantMap m_properties
Detailed Description
The class of the app mpris player object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 68 of file musicapplicationmprismodule.h.
Constructor & Destructor Documentation
MusicApplicationMPRISPlayer::MusicApplicationMPRISPlayer (QObject * parent = nullptr)
Definition at line 12 of file musicapplicationmprismodule.cpp.
References elapsedChanged(), MusicTime::initRandom(), MusicApplication::instance(), SoundCore::instance(), m_music, MusicApplication::m_musicPlaylist, m_player, m_prev_pos, m_prev_track, playbackModeChanged(), stateChanged(), syncProperties(), trackInfoChanged(), updateTrackID(), and volumeChanged().
Member Function Documentation
bool MusicApplicationMPRISPlayer::canControl () const
Definition at line 32 of file musicapplicationmprismodule.cpp.
bool MusicApplicationMPRISPlayer::canGoNext () const
Definition at line 37 of file musicapplicationmprismodule.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicApplicationMPRISPlayer::canGoPrevious () const
Definition at line 42 of file musicapplicationmprismodule.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicApplicationMPRISPlayer::canPause () const
Definition at line 47 of file musicapplicationmprismodule.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicApplicationMPRISPlayer::canPlay () const
Definition at line 51 of file musicapplicationmprismodule.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicApplicationMPRISPlayer::canSeek () const
Definition at line 56 of file musicapplicationmprismodule.cpp.
References SoundCore::duration(), and m_music.
Referenced by syncProperties().
void MusicApplicationMPRISPlayer::elapsedChanged (qint64 elapsed) private slot
Tracks elapesed time.
Definition at line 298 of file musicapplicationmprismodule.cpp.
References m_prev_pos, and Seeked().
Referenced by MusicApplicationMPRISPlayer().
QString MusicApplicationMPRISPlayer::loopStatus () const
Definition at line 61 of file musicapplicationmprismodule.cpp.
References MusicApplication::getPlayMode(), m_player, MusicObject::PM_PlaylistLoop, and MusicObject::PM_PlayOneLoop.
Referenced by syncProperties().
double MusicApplicationMPRISPlayer::maximumRate () const
Definition at line 87 of file musicapplicationmprismodule.cpp.
Referenced by syncProperties().
QVariantMap MusicApplicationMPRISPlayer::metadata () const
Definition at line 92 of file musicapplicationmprismodule.cpp.
References Qmmp::ALBUM, Qmmp::ALBUMARTIST, Qmmp::ARTIST, Qmmp::COMMENT, Qmmp::COMPOSER, Qmmp::DISCNUMBER, SoundCore::duration(), Qmmp::GENRE, MetaDataManager::getCoverPath(), MetaDataManager::instance(), m_music, m_trackID, TrackInfo::path(), SoundCore::path(), Qmmp::TITLE, Qmmp::TRACK, SoundCore::trackInfo(), TrackInfo::value(), and Qmmp::YEAR.
Referenced by syncProperties().
double MusicApplicationMPRISPlayer::minimumRate () const
Definition at line 162 of file musicapplicationmprismodule.cpp.
Referenced by syncProperties().
void MusicApplicationMPRISPlayer::Next () slot
Definition at line 220 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicPlayNext().
void MusicApplicationMPRISPlayer::OpenUri (const QString & uri) slot
Definition at line 225 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicImportSongsPathOuter().
void MusicApplicationMPRISPlayer::Pause () slot
Definition at line 240 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicStatePlay().
void MusicApplicationMPRISPlayer::Play () slot
Definition at line 245 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicStatePlay().
void MusicApplicationMPRISPlayer::playbackModeChanged () private slot
Current play mode changed emit.
Definition at line 307 of file musicapplicationmprismodule.cpp.
References sendProperties().
Referenced by MusicApplicationMPRISPlayer().
QString MusicApplicationMPRISPlayer::playbackStatus () const
Definition at line 167 of file musicapplicationmprismodule.cpp.
References m_music, Qmmp::Paused, Qmmp::Playing, and SoundCore::state().
Referenced by syncProperties().
void MusicApplicationMPRISPlayer::PlayPause () slot
Definition at line 250 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicStatePlay().
qlonglong MusicApplicationMPRISPlayer::position () const
Definition at line 180 of file musicapplicationmprismodule.cpp.
References SoundCore::elapsed(), and m_music.
void MusicApplicationMPRISPlayer::Previous () slot
Definition at line 215 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicPlayPrevious().
double MusicApplicationMPRISPlayer::rate () const
Definition at line 185 of file musicapplicationmprismodule.cpp.
Referenced by syncProperties().
void MusicApplicationMPRISPlayer::Seek (qlonglong offset) slot
Definition at line 260 of file musicapplicationmprismodule.cpp.
References SoundCore::elapsed(), m_music, and SoundCore::seek().
void MusicApplicationMPRISPlayer::Seeked (qlonglong position) signal
Referenced by elapsedChanged().
void MusicApplicationMPRISPlayer::sendProperties () private
Definition at line 338 of file musicapplicationmprismodule.cpp.
References m_properties, and syncProperties().
Referenced by playbackModeChanged(), stateChanged(), trackInfoChanged(), and volumeChanged().
void MusicApplicationMPRISPlayer::setLoopStatus (const QString & value)
Definition at line 71 of file musicapplicationmprismodule.cpp.
References m_player, MusicApplication::musicPlaylistLoop(), MusicApplication::musicPlayOneLoop(), and MusicApplication::musicPlayOrder().
void MusicApplicationMPRISPlayer::SetPosition (const QDBusObjectPath & trackId, qlonglong position) slot
Definition at line 265 of file musicapplicationmprismodule.cpp.
References m_music, m_trackID, SoundCore::seek(), and TTK_LOGGER_WARN.
void MusicApplicationMPRISPlayer::setRate (double value)
Definition at line 190 of file musicapplicationmprismodule.cpp.
void MusicApplicationMPRISPlayer::setShuffle (bool value)
Definition at line 200 of file musicapplicationmprismodule.cpp.
References MusicApplication::m_musicPlaylist, m_player, MusicObject::PM_PlayOrder, MusicObject::PM_PlayRandom, and MusicPlaylist::setPlaybackMode().
void MusicApplicationMPRISPlayer::setVolume (double value)
Definition at line 210 of file musicapplicationmprismodule.cpp.
References MusicApplication::m_musicPlayer, m_player, and MusicPlayer::setVolume().
bool MusicApplicationMPRISPlayer::shuffle () const
Definition at line 195 of file musicapplicationmprismodule.cpp.
References MusicApplication::getPlayMode(), m_player, and MusicObject::PM_PlayRandom.
Referenced by syncProperties().
void MusicApplicationMPRISPlayer::stateChanged () private slot
When the state of the SoundCore has changed.
Definition at line 283 of file musicapplicationmprismodule.cpp.
References m_music, m_prev_pos, Qmmp::Playing, sendProperties(), SoundCore::state(), and updateTrackID().
Referenced by MusicApplicationMPRISPlayer().
void MusicApplicationMPRISPlayer::Stop () slot
Definition at line 255 of file musicapplicationmprismodule.cpp.
References m_player, and MusicApplication::musicStateStop().
void MusicApplicationMPRISPlayer::syncProperties () private
Definition at line 321 of file musicapplicationmprismodule.cpp.
References canGoNext(), canGoPrevious(), canPause(), canPlay(), canSeek(), loopStatus(), m_properties, maximumRate(), metadata(), minimumRate(), playbackStatus(), rate(), shuffle(), and volume().
Referenced by MusicApplicationMPRISPlayer(), and sendProperties().
void MusicApplicationMPRISPlayer::trackInfoChanged () private slot
When new track information is available.
Definition at line 277 of file musicapplicationmprismodule.cpp.
References sendProperties(), and updateTrackID().
Referenced by MusicApplicationMPRISPlayer().
void MusicApplicationMPRISPlayer::updateTrackID () private
Definition at line 312 of file musicapplicationmprismodule.cpp.
References MusicPlaylist::currentIndex(), MusicApplication::m_musicPlaylist, m_player, m_prev_track, m_trackID, and MusicTime::random().
Referenced by MusicApplicationMPRISPlayer(), stateChanged(), and trackInfoChanged().
double MusicApplicationMPRISPlayer::volume () const
Definition at line 205 of file musicapplicationmprismodule.cpp.
References MusicApplication::m_musicPlayer, m_player, and MusicPlayer::volume().
Referenced by syncProperties().
void MusicApplicationMPRISPlayer::volumeChanged () private slot
When the highest volume of the left and right channels has changed.
Definition at line 293 of file musicapplicationmprismodule.cpp.
References sendProperties().
Referenced by MusicApplicationMPRISPlayer().
Member Data Documentation
SoundCore* MusicApplicationMPRISPlayer::m_music private
Definition at line 154 of file musicapplicationmprismodule.h.
Referenced by canSeek(), metadata(), MusicApplicationMPRISPlayer(), playbackStatus(), position(), Seek(), SetPosition(), and stateChanged().
MusicApplication* MusicApplicationMPRISPlayer::m_player private
Definition at line 155 of file musicapplicationmprismodule.h.
Referenced by canGoNext(), canGoPrevious(), canPause(), canPlay(), loopStatus(), MusicApplicationMPRISPlayer(), Next(), OpenUri(), Pause(), Play(), PlayPause(), Previous(), setLoopStatus(), setShuffle(), setVolume(), shuffle(), Stop(), updateTrackID(), and volume().
qint64 MusicApplicationMPRISPlayer::m_prev_pos private
Definition at line 153 of file musicapplicationmprismodule.h.
Referenced by elapsedChanged(), MusicApplicationMPRISPlayer(), and stateChanged().
int MusicApplicationMPRISPlayer::m_prev_track private
Definition at line 152 of file musicapplicationmprismodule.h.
Referenced by MusicApplicationMPRISPlayer(), and updateTrackID().
TTKVariantMap MusicApplicationMPRISPlayer::m_properties private
Definition at line 157 of file musicapplicationmprismodule.h.
Referenced by sendProperties(), and syncProperties().
QDBusObjectPath MusicApplicationMPRISPlayer::m_trackID private
Definition at line 156 of file musicapplicationmprismodule.h.
Referenced by metadata(), SetPosition(), and updateTrackID().
Property Documentation
bool MusicApplicationMPRISPlayer::CanControl read
Definition at line 72 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISPlayer::CanGoNext read
Definition at line 73 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISPlayer::CanGoPrevious read
Definition at line 74 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISPlayer::CanPause read
Definition at line 75 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISPlayer::CanPlay read
Definition at line 76 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISPlayer::CanSeek read
Definition at line 77 of file musicapplicationmprismodule.h.
QString MusicApplicationMPRISPlayer::LoopStatus read write
Definition at line 78 of file musicapplicationmprismodule.h.
double MusicApplicationMPRISPlayer::MaximumRate read
Definition at line 79 of file musicapplicationmprismodule.h.
QVariantMap MusicApplicationMPRISPlayer::Metadata read
Definition at line 80 of file musicapplicationmprismodule.h.
double MusicApplicationMPRISPlayer::MinimumRate read
Definition at line 81 of file musicapplicationmprismodule.h.
QString MusicApplicationMPRISPlayer::PlaybackStatus read
Definition at line 82 of file musicapplicationmprismodule.h.
qlonglong MusicApplicationMPRISPlayer::Position read
Definition at line 83 of file musicapplicationmprismodule.h.
double MusicApplicationMPRISPlayer::Rate read write
Definition at line 84 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISPlayer::Shuffle read write
Definition at line 85 of file musicapplicationmprismodule.h.
double MusicApplicationMPRISPlayer::Volume read write
Definition at line 86 of file musicapplicationmprismodule.h.
The documentation for this class was generated from the following files:
TTKModule/musicapplicationmprismodule.h
TTKModule/musicapplicationmprismodule.cpp