TTKMusicPlayer: MusicIdentifySongWidget Class Reference
MusicIdentifySongWidget Class Reference
The class of the song identify widget.
#include <musicidentifysongwidget.h>
Public Slots
void detectedButtonClicked ()
void reDetectButtonClicked ()
void detectedTimeOut ()
void playSongClicked ()
void showDownloadWidget ()
void showSongShareWidget ()
void positionChanged (qint64 position)
Public Member Functions
MusicIdentifySongWidget (QWidget *parent=nullptr)
~MusicIdentifySongWidget ()
void queryIdentifyKey ()
Private Member Functions
void createDetectedWidget ()
void createDetectedSuccessedWidget ()
void createDetectedFailedWidget ()
Private Attributes
QTimer * m_timer
QStackedWidget * m_mainWindow
QLabel * m_detectedLabel
QLabel * m_lrcLabel
QMovie * m_detectedMovie
QPushButton * m_detectedButton
MusicCoreMPlayer * m_player
MusicLrcAnalysis * m_analysis
MusicAudioRecorderModule * m_recordCore
MusicIdentifySongRequest * m_networkRequest
TTK::MusicSongInformation m_info
Detailed Description
The class of the song identify widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicidentifysongwidget.h.
Constructor & Destructor Documentation
MusicIdentifySongWidget::MusicIdentifySongWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 17 of file musicidentifysongwidget.cpp.
References TTK::UI::BackgroundStyle10, createDetectedWidget(), detectedButtonClicked(), detectedTimeOut(), m_detectedButton, m_mainWindow, m_networkRequest, m_recordCore, m_timer, and TTK_DN_S2MS.
MusicIdentifySongWidget::~MusicIdentifySongWidget ()
Object destructor.
Definition at line 47 of file musicidentifysongwidget.cpp.
References m_analysis, m_detectedButton, m_detectedLabel, m_detectedMovie, m_mainWindow, m_networkRequest, m_player, m_recordCore, and m_timer.
Member Function Documentation
void MusicIdentifySongWidget::createDetectedFailedWidget () private
Create the detected failed widget.
Definition at line 411 of file musicidentifysongwidget.cpp.
References TTK::UI::ColorStyle03, TTK::UI::FontStyle03, TTK::UI::FontStyle04, m_mainWindow, reDetectButtonClicked(), and TTK::UI::SongsRedetectBtn.
Referenced by detectedTimeOut().
void MusicIdentifySongWidget::createDetectedSuccessedWidget () private
Create the detected successed widget.
Definition at line 253 of file musicidentifysongwidget.cpp.
References ART_DIR_FULL, TTK::UI::ColorStyle03, TTK::Cover, TTKSemaphoreLoop::exec(), TTK::UI::FontStyle03, TTK::UI::FontStyle04, G_DOWNLOAD_QUERY_PTR, TTK::generateSongName(), MusicAbstractQueryRequest::isEmpty(), MusicIdentifySongRequest::items(), MusicAbstractQueryRequest::items(), MusicLrcAnalysis::loadFromLrcFile(), LRC_FILE, TTK::String::lrcDirPrefix(), m_analysis, MusicSongIdentifyData::m_artistName, TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_coverUrl, m_info, m_lrcLabel, TTK::MusicSongInformation::m_lrcUrl, m_mainWindow, m_networkRequest, m_player, MusicSongIdentifyData::m_songName, TTK::MusicSongInformation::m_songName, TTK::MusicSongInformation::m_songProps, MusicCoreMPlayer::Music, name, playSongClicked(), positionChanged(), reDetectButtonClicked(), MusicLrcAnalysis::setLineMax(), MusicCoreMPlayer::setMedia(), showDownloadWidget(), showSongShareWidget(), SKN_FILE, TTK::UI::SongsDetectDownloadBtn, TTK::UI::SongsDetectPlayBtn, TTK::UI::SongsDetectShareBtn, TTK::UI::SongsDetectUnloveBtn, TTK::UI::SongsRedetectBtn, MusicAbstractQueryRequest::startToQueryResult(), MusicDownloadDataRequest::startToRequest(), MusicAbstractDownLoadRequest::startToRequest(), MusicAbstractQueryRequest::startToSearch(), and TTK_BN_128.
Referenced by detectedTimeOut().
void MusicIdentifySongWidget::createDetectedWidget () private
Create the detected widget.
Definition at line 209 of file musicidentifysongwidget.cpp.
References TTK::UI::ColorStyle03, detectedButtonClicked(), TTK::UI::FontStyle03, TTK::UI::FontStyle04, m_detectedButton, m_detectedLabel, m_detectedMovie, m_mainWindow, and TTK::UI::SongsDetectStartBtn.
Referenced by MusicIdentifySongWidget().
void MusicIdentifySongWidget::detectedButtonClicked () slot
Detected the song button clicked.
Definition at line 72 of file musicidentifysongwidget.cpp.
References MusicAudioRecorderModule::error(), m_detectedButton, m_detectedLabel, m_detectedMovie, m_recordCore, m_timer, MusicAudioRecorderModule::onRecordStart(), MusicAudioRecorderModule::onRecordStop(), MusicToastLabel::popup(), reDetectButtonClicked(), TTK::UI::SongsDetectStartBtn, and TTK::UI::SongsDetectStopBtn.
Referenced by createDetectedWidget(), detectedTimeOut(), and MusicIdentifySongWidget().
void MusicIdentifySongWidget::detectedTimeOut () slot
Detected the song finished.
Definition at line 114 of file musicidentifysongwidget.cpp.
References MusicAudioRecorderModule::addWavHeader(), createDetectedFailedWidget(), createDetectedSuccessedWidget(), detectedButtonClicked(), TTKSemaphoreLoop::exec(), MusicIdentifySongRequest::items(), m_networkRequest, m_recordCore, MusicIdentifySongRequest::startToRequest(), and TTK_RECORD_DATA_FILE.
Referenced by MusicIdentifySongWidget().
void MusicIdentifySongWidget::playSongClicked () slot
Set music song to play.
Definition at line 134 of file musicidentifysongwidget.cpp.
References m_info, m_player, TTK::MusicSongInformation::m_songProps, MusicCoreMPlayer::Music, and MusicCoreMPlayer::setMedia().
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongWidget::positionChanged (qint64 position) slot
Current position changed.
Definition at line 170 of file musicidentifysongwidget.cpp.
References MusicLrcAnalysis::currentIndex(), MusicLrcAnalysis::findTime(), MusicLrcAnalysis::isEmpty(), MusicLrcAnalysis::lineMax(), MusicLrcAnalysis::lineMiddle(), m_analysis, m_lrcLabel, m_player, MusicLrcAnalysis::setCurrentIndex(), MusicLrcAnalysis::text(), and TTK_DN_S2MS.
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongWidget::queryIdentifyKey ()
Get query song id keys.
Definition at line 60 of file musicidentifysongwidget.cpp.
References m_detectedButton, m_networkRequest, MusicToastLabel::popup(), and MusicIdentifySongRequest::queryIdentifyKey().
Referenced by MusicRightAreaWidget::functionClicked().
void MusicIdentifySongWidget::reDetectButtonClicked () slot
Retected the song button clicked.
Definition at line 105 of file musicidentifysongwidget.cpp.
References m_mainWindow, m_player, and MusicCoreMPlayer::stop().
Referenced by createDetectedFailedWidget(), createDetectedSuccessedWidget(), and detectedButtonClicked().
void MusicIdentifySongWidget::showDownloadWidget () slot
Set music song to download.
Definition at line 147 of file musicidentifysongwidget.cpp.
References MusicDownloadWidget::initialize(), TTK::MusicSongInformation::m_artistName, m_info, and MusicAbstractMoveWidget::show().
Referenced by createDetectedSuccessedWidget().
void MusicIdentifySongWidget::showSongShareWidget () slot
Set music song to share.
Definition at line 157 of file musicidentifysongwidget.cpp.
References MusicAbstractMoveDialog::exec(), MusicSongSharingWidget::initialize(), TTK::MusicSongInformation::m_artistName, m_info, MusicSongSharingWidget::Item::m_name, TTK::MusicSongInformation::m_songName, and MusicSongSharingWidget::Song.
Referenced by createDetectedSuccessedWidget().
Member Data Documentation
MusicLrcAnalysis* MusicIdentifySongWidget::m_analysis private
Definition at line 104 of file musicidentifysongwidget.h.
Referenced by createDetectedSuccessedWidget(), positionChanged(), and ~MusicIdentifySongWidget().
QPushButton* MusicIdentifySongWidget::m_detectedButton private
Definition at line 102 of file musicidentifysongwidget.h.
Referenced by createDetectedWidget(), detectedButtonClicked(), MusicIdentifySongWidget(), queryIdentifyKey(), and ~MusicIdentifySongWidget().
QLabel* MusicIdentifySongWidget::m_detectedLabel private
Definition at line 100 of file musicidentifysongwidget.h.
Referenced by createDetectedWidget(), detectedButtonClicked(), and ~MusicIdentifySongWidget().
QMovie* MusicIdentifySongWidget::m_detectedMovie private
Definition at line 101 of file musicidentifysongwidget.h.
Referenced by createDetectedWidget(), detectedButtonClicked(), and ~MusicIdentifySongWidget().
TTK::MusicSongInformation MusicIdentifySongWidget::m_info private
Definition at line 107 of file musicidentifysongwidget.h.
Referenced by createDetectedSuccessedWidget(), playSongClicked(), showDownloadWidget(), and showSongShareWidget().
QLabel * MusicIdentifySongWidget::m_lrcLabel private
Definition at line 100 of file musicidentifysongwidget.h.
Referenced by createDetectedSuccessedWidget(), and positionChanged().
QStackedWidget* MusicIdentifySongWidget::m_mainWindow private
Definition at line 99 of file musicidentifysongwidget.h.
Referenced by createDetectedFailedWidget(), createDetectedSuccessedWidget(), createDetectedWidget(), MusicIdentifySongWidget(), reDetectButtonClicked(), and ~MusicIdentifySongWidget().
MusicIdentifySongRequest* MusicIdentifySongWidget::m_networkRequest private
Definition at line 106 of file musicidentifysongwidget.h.
Referenced by createDetectedSuccessedWidget(), detectedTimeOut(), MusicIdentifySongWidget(), queryIdentifyKey(), and ~MusicIdentifySongWidget().
MusicCoreMPlayer* MusicIdentifySongWidget::m_player private
Definition at line 103 of file musicidentifysongwidget.h.
Referenced by createDetectedSuccessedWidget(), playSongClicked(), positionChanged(), reDetectButtonClicked(), and ~MusicIdentifySongWidget().
MusicAudioRecorderModule* MusicIdentifySongWidget::m_recordCore private
Definition at line 105 of file musicidentifysongwidget.h.
Referenced by detectedButtonClicked(), detectedTimeOut(), MusicIdentifySongWidget(), and ~MusicIdentifySongWidget().
QTimer* MusicIdentifySongWidget::m_timer private
Definition at line 98 of file musicidentifysongwidget.h.
Referenced by detectedButtonClicked(), MusicIdentifySongWidget(), and ~MusicIdentifySongWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicidentifysongwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicidentifysongwidget.cpp