TTKMusicPlayer: TTKCommandLineOption Class Reference
TTKCommandLineOption Class Reference
The class of the command line option.
#include <ttkcommandline.h>
Public Member Functions
TTKCommandLineOption (const QString &first) noexcept
TTKCommandLineOption (const QString &first, const QString &description) noexcept
TTKCommandLineOption (const QString &first, const QString &second, const QString &description) noexcept
QString first () const noexcept
QString second () const noexcept
QString description () const noexcept
bool operator== (const TTKCommandLineOption &other) const noexcept
bool operator!= (const TTKCommandLineOption &other) const noexcept
Private Attributes
QString m_first
QString m_second
QString m_description
Detailed Description
The class of the command line option.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file ttkcommandline.h.
Constructor & Destructor Documentation
TTKCommandLineOption::TTKCommandLineOption (const QString & first) inline noexcept
Object constructor.
Definition at line 34 of file ttkcommandline.h.
TTKCommandLineOption::TTKCommandLineOption (const QString & first, const QString & description) inline noexcept
Definition at line 40 of file ttkcommandline.h.
TTKCommandLineOption::TTKCommandLineOption (const QString & first, const QString & second, const QString & description) inline noexcept
Definition at line 47 of file ttkcommandline.h.
Member Function Documentation
QString TTKCommandLineOption::description () const inline noexcept
Get option description.
Definition at line 66 of file ttkcommandline.h.
QString TTKCommandLineOption::first () const inline noexcept
Get first option.
Definition at line 58 of file ttkcommandline.h.
Referenced by TTKCommandLineParser::addOption(), TTKCommandLineParser::isSet(), and TTKCommandLineParser::value().
bool TTKCommandLineOption::operator!= (const TTKCommandLineOption & other) const inline noexcept
Definition at line 72 of file ttkcommandline.h.
bool TTKCommandLineOption::operator== (const TTKCommandLineOption & other) const inline noexcept
Definition at line 68 of file ttkcommandline.h.
QString TTKCommandLineOption::second () const inline noexcept
Get second option.
Definition at line 62 of file ttkcommandline.h.
Referenced by TTKCommandLineParser::isSet(), and TTKCommandLineParser::value().
Member Data Documentation
QString TTKCommandLineOption::m_description private
Definition at line 80 of file ttkcommandline.h.
QString TTKCommandLineOption::m_first private
Definition at line 78 of file ttkcommandline.h.
QString TTKCommandLineOption::m_second private
Definition at line 79 of file ttkcommandline.h.
The documentation for this class was generated from the following file:
TTKCommon/TTKLibrary/ttkcommandline.h