TTKMusicPlayer: TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyqueryinterface.cpp File Reference
musicwyqueryinterface.cpp File Reference
#include "musicwyqueryinterface.h"
#include "musicunityqueryinterface.h"
#include "musicurlutils.h"
#include "qalgorithm/aeswrapper.h"
Functions
static QString makeUser () noexcept
static void parseSongPropertyV1 (TTK::MusicSongInformation *info, int bitrate)
static void parseSongPropertyV2 (TTK::MusicSongInformation *info, int bitrate)
static void parseSongPropertyV3 (TTK::MusicSongInformation *info, int bitrate)
static void parseSongPropertyUnity (TTK::MusicSongInformation *info, int bitrate)
static void parseSongProperty (TTK::MusicSongInformation *info, int bitrate)
Variables
static constexpr const char * WY_USER_URL = "resource/user"
static constexpr const char * WY_UA_URL = "Vkloais0Z0Q4Smp1aElYSXFUVy96SXdoZ2VsTURzdDBpZEZjT21jMy9PRE1DMzdwQ0p5MllueTkrRGdzb2VkdlJMemJhWEFReHlUUk9uSEtMTHRLUzRxS3psczJiRW9LZ3BQbHh1Z3lGRlhEQk5JbVVGb1NDN1JzTDhZMjBybllLcndKSHlSNC94QzRJWXlL"
static constexpr const char * WY_COOKIE_URL = "eU5NVy9LRm5jWE9pdUU1MzNQNi9OcjVUbi9vSGhYcGVaQWc0NjlPbCt1WnNDbDlONDg1SSthTi9JUDQ1YVpsRg=="
static constexpr const char * WY_USER1_URL = "VzJpdUVPQ0xkZnp4VENJWjVIVFhQYzZKbnYrSU9pRTFmWXNkcXFaSWorRDRWMjJxUGdZaklZUDNzZXNweXJuczJMeGc2TVFRSEk4SkxCYkxXQ2FFUHpBbENUcjRZZ3RVNGpwRUloVkhVSWhSem50NTM3ZjFGMXdQVXFWN01mNE1GZUg2WFk3anl1Z1hxVkc0eXM3ZFZCVkpGNDZlNVA1MmhvYzZ6UT09"
static constexpr const char * WY_USER2_URL = "TE40MEZBWWJkbkhTbTM2OEVTMkE3VjlJOWZuUjVNQ3BFRGMwYjZ4NW9yeE5QdWozU0ZuSjJrQVdpQkdaT3B4enBMOGpTNUJiVXZDTUxmSWFNRkV5SGVqMXcxaS8rZnlsVmo2bkFJR1BvaGQ2c3llUFlyTVNITWdtcFRpMlA2SEl4VE40RnphRTRza2FPaG5RR3hkeGtZOHVGdHV6Nko3UHNBb25rdz09"
static constexpr const char * WY_USER3_URL = "c0s1RFpDY0Iya1hNOGFob2JLdGNiUFNxVCs0bE44MDBtQWtmTng4SDRqWlZOZWJXbUkySEtrSDNqVnhUOGMrUVpiNk9lc21MRlFTdFdNYlBwdWNtMmo2VUs4b1M4MFUvS2EzYkpjcnJTZHdZNGdsZ0JsU3lhWkoxaFY1czB4THF6anlDWWp5Ym1VKzJERjAvSmx1WXFPY0ErbjJrMnl2OFhGNGFBUT09"
static constexpr const char * WY_USER4_URL = "RGdEcVgrSERYQjErNUovY0hFOVU1dElWR00xRVNiRTRVenlHaVpiMkZ1Z0tXV2ZTZVpjL3RCV2pvajhLNjhINjFaUG5QWGdNcnZlcVlxZm93V01IUUgyWWM3NFFTdGE5K203MG5KeE0rNzFPV1ZFUmJHUnBSSHRXRUx1NEVYcU91VGgzWUh6M0hOcUVaUG9YQU9GNXFIaHlDVk5UVGNISmtmcHllQT09"
static constexpr const char * WY_USER5_URL = "ZmxqdmFXWFlmWFdtYzB2M212VVRaSDhIL1NhYnRySDg5dlV0eWx3YVdZUG82NFlMRlZMNnRHVGFlbVhqaFF0ckJ2YTVRSG12YnYrb1ZqaTJFY2ViK0Y3RG5WbWVHVldzVWk0enFweDd1dkhBNmF1dg=="
static constexpr const char * WY_RAND_URL = "V0Zsb2tGREU1R0thR29GYjRYdk5jbm5NZjEvN1d6WWNiQlZqb2k4eE1nTm9lTHlBRktkQTBOaXNjQ3ZHU0ZMSw=="
static constexpr const char * WY_BASE_URL = "MVNVTXo4bW9WdHhXR1dXeTZmU3k5dmFOcGlua1VOMlE="
static constexpr const char * WY_SECKRY_URL = "411571dca16717d9af5ef1ac97a8d21cb740329890560688b1b624de43f49fdd7702493835141b06ae45f1326e264c98c24ce87199c1a776315e5f25c11056b02dd92791fcc012bff8dd4fc86e37888d5ccc060f7837b836607dbb28bddc703308a0ba67c24c6420dd08eec2b8111067486c907b6e53c027ae1e56c188bc568e"
static constexpr const char * WY_SONG_PATH_V1_URL = "N2NkQWg4V3o0NXYvMlFHamVOWVZ5Y2NnTDk2cTNFdFVROVNwTndJV2REYXM0K01Yd2NIT1pwaGcyTGJ0QVVsNHVxT0lTZHFKNTI2QnlWMnVBWFNDdWYrb09Waz0="
static constexpr const char * WY_SONG_PATH_V2_URL = "M21IV2dlSHNzaE1zZEpyb2hrQ0dqVEY3Ly9DZ3ZteDM1RStuSlJIRVVCRTljbWJKKzRBVnNZY3JEcEZKY045dEJ5KzM0WHArSDVCYXhrMHBoZmlTZXBWdHIvND0="
static constexpr const char * WY_SONG_PATH_V2_DATA_URL = "ei9SdFJqZWlHWlh3eXBsWHJTS09FbUpRU1J4Zi9wZDlOQUMyVTVnL3c0YW9GSjVH"
static constexpr const char * WY_SONG_PATH_V3_URL = "cmNsdVp5dFI1TG5VMVg1N2w1bnZwOEx0TGlUazZuZ1JFMkg0dVcvS0ZKbExPL2d0UW9kT0RaZHNhMzFXcjZiVytiZmtLY2hvYjk0bVEyZDhWaldiTmx6V0pmaz0="
static constexpr const char * WY_SONG_PATH_V3_QUERY_URL = "OCtmZUdQbVRENjVqWGo5eERUbnlnQ3BsLzVoa3p5WnFxYnJKcWZ3K1NCQWtiS01p"
static constexpr const char * WY_SONG_PATH_V3_DATA_URL = "TDlnVTZReGNvWk9YTkFFdVF4bDJJcUk4K1BHRFU1N2I3eHlNNmwwYnIzcEVRdDZVelpRVEpRODNjTDVWdXprVEJtcENlNmFmUHZXYUNsdXkxSHV6elE9PQ=="
Function Documentation
static QString makeUser () static noexcept
Definition at line 28 of file musicwyqueryinterface.cpp.
References TTK::Algorithm::mdII(), WY_USER1_URL, WY_USER2_URL, WY_USER3_URL, WY_USER4_URL, and WY_USER5_URL.
Referenced by ReqWYInterface::makeRequestRawHeader().
static void parseSongProperty (TTK::MusicSongInformation * info, int bitrate) static
Definition at line 294 of file musicwyqueryinterface.cpp.
References MusicSettingManager::DownloadServerPriority, G_SETTING_PTR, parseSongPropertyUnity(), parseSongPropertyV1(), parseSongPropertyV2(), and parseSongPropertyV3().
Referenced by ReqWYInterface::parseFromSongProperty().
static void parseSongPropertyUnity (TTK::MusicSongInformation * info, int bitrate) static
Definition at line 276 of file musicwyqueryinterface.cpp.
References TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, ReqUnityInterface::parseFromSongProperty(), qAsConst, QUERY_WY_INTERFACE, TTK_BN_1000, TTK_BN_128, TTK_BN_320, and TTK_INFO_STREAM.
Referenced by parseSongProperty().
static void parseSongPropertyV1 (TTK::MusicSongInformation * info, int bitrate) static
Definition at line 107 of file musicwyqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqWYInterface::makeRequestRawHeader(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), QJsonDocument::toVariant(), TTK_BN_500, TTK_INFO_STREAM, and WY_SONG_PATH_V1_URL.
Referenced by parseSongProperty().
static void parseSongPropertyV2 (TTK::MusicSongInformation * info, int bitrate) static
Definition at line 156 of file musicwyqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqWYInterface::makeTokenRequest(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForPost(), QJsonDocument::toVariant(), TTK_BN_500, TTK_INFO_STREAM, WY_SONG_PATH_V2_DATA_URL, and WY_SONG_PATH_V2_URL.
Referenced by parseSongProperty().
static void parseSongPropertyV3 (TTK::MusicSongInformation * info, int bitrate) static
Definition at line 211 of file musicwyqueryinterface.cpp.
References QJsonParseError::error, QJsonDocument::fromJson(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, ReqWYInterface::makeTokenRequest(), TTK::Algorithm::mdII(), QJsonParseError::NoError, qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForPost(), QJsonDocument::toVariant(), TTK_BN_1000, TTK_BN_128, TTK_BN_320, TTK_BN_500, TTK_INFO_STREAM, WY_SONG_PATH_V3_DATA_URL, WY_SONG_PATH_V3_QUERY_URL, and WY_SONG_PATH_V3_URL.
Referenced by parseSongProperty().
Variable Documentation
constexpr const char* WY_BASE_URL = "MVNVTXo4bW9WdHhXR1dXeTZmU3k5dmFOcGlua1VOMlE=" static
Definition at line 16 of file musicwyqueryinterface.cpp.
Referenced by ReqWYInterface::makeRequestRawHeader().
constexpr const char* WY_COOKIE_URL = "eU5NVy9LRm5jWE9pdUU1MzNQNi9OcjVUbi9vSGhYcGVaQWc0NjlPbCt1WnNDbDlONDg1SSthTi9JUDQ1YVpsRg==" static
Definition at line 9 of file musicwyqueryinterface.cpp.
Referenced by ReqWYInterface::makeRequestRawHeader().
constexpr const char* WY_RAND_URL = "V0Zsb2tGREU1R0thR29GYjRYdk5jbm5NZjEvN1d6WWNiQlZqb2k4eE1nTm9lTHlBRktkQTBOaXNjQ3ZHU0ZMSw==" static
Definition at line 15 of file musicwyqueryinterface.cpp.
Referenced by ReqWYInterface::makeRequestRawHeader().
constexpr const char* WY_SECKRY_URL = "411571dca16717d9af5ef1ac97a8d21cb740329890560688b1b624de43f49fdd7702493835141b06ae45f1326e264c98c24ce87199c1a776315e5f25c11056b02dd92791fcc012bff8dd4fc86e37888d5ccc060f7837b836607dbb28bddc703308a0ba67c24c6420dd08eec2b8111067486c907b6e53c027ae1e56c188bc568e" static
Definition at line 17 of file musicwyqueryinterface.cpp.
Referenced by ReqWYInterface::makeTokenRequest().
constexpr const char* WY_SONG_PATH_V1_URL = "N2NkQWg4V3o0NXYvMlFHamVOWVZ5Y2NnTDk2cTNFdFVROVNwTndJV2REYXM0K01Yd2NIT1pwaGcyTGJ0QVVsNHVxT0lTZHFKNTI2QnlWMnVBWFNDdWYrb09Waz0=" static
Definition at line 19 of file musicwyqueryinterface.cpp.
Referenced by parseSongPropertyV1().
constexpr const char* WY_SONG_PATH_V2_DATA_URL = "ei9SdFJqZWlHWlh3eXBsWHJTS09FbUpRU1J4Zi9wZDlOQUMyVTVnL3c0YW9GSjVH" static
Definition at line 21 of file musicwyqueryinterface.cpp.
Referenced by parseSongPropertyV2().
constexpr const char* WY_SONG_PATH_V2_URL = "M21IV2dlSHNzaE1zZEpyb2hrQ0dqVEY3Ly9DZ3ZteDM1RStuSlJIRVVCRTljbWJKKzRBVnNZY3JEcEZKY045dEJ5KzM0WHArSDVCYXhrMHBoZmlTZXBWdHIvND0=" static
Definition at line 20 of file musicwyqueryinterface.cpp.
Referenced by parseSongPropertyV2().
constexpr const char* WY_SONG_PATH_V3_DATA_URL = "TDlnVTZReGNvWk9YTkFFdVF4bDJJcUk4K1BHRFU1N2I3eHlNNmwwYnIzcEVRdDZVelpRVEpRODNjTDVWdXprVEJtcENlNmFmUHZXYUNsdXkxSHV6elE9PQ==" static
Definition at line 24 of file musicwyqueryinterface.cpp.
Referenced by parseSongPropertyV3().
constexpr const char* WY_SONG_PATH_V3_QUERY_URL = "OCtmZUdQbVRENjVqWGo5eERUbnlnQ3BsLzVoa3p5WnFxYnJKcWZ3K1NCQWtiS01p" static
Definition at line 23 of file musicwyqueryinterface.cpp.
Referenced by parseSongPropertyV3().
constexpr const char* WY_SONG_PATH_V3_URL = "cmNsdVp5dFI1TG5VMVg1N2w1bnZwOEx0TGlUazZuZ1JFMkg0dVcvS0ZKbExPL2d0UW9kT0RaZHNhMzFXcjZiVytiZmtLY2hvYjk0bVEyZDhWaldiTmx6V0pmaz0=" static
Definition at line 22 of file musicwyqueryinterface.cpp.
Referenced by parseSongPropertyV3().
constexpr const char* WY_UA_URL = "Vkloais0Z0Q4Smp1aElYSXFUVy96SXdoZ2VsTURzdDBpZEZjT21jMy9PRE1DMzdwQ0p5MllueTkrRGdzb2VkdlJMemJhWEFReHlUUk9uSEtMTHRLUzRxS3psczJiRW9LZ3BQbHh1Z3lGRlhEQk5JbVVGb1NDN1JzTDhZMjBybllLcndKSHlSNC94QzRJWXlL" static
Definition at line 8 of file musicwyqueryinterface.cpp.
Referenced by ReqWYInterface::makeRequestRawHeader().
constexpr const char* WY_USER1_URL = "VzJpdUVPQ0xkZnp4VENJWjVIVFhQYzZKbnYrSU9pRTFmWXNkcXFaSWorRDRWMjJxUGdZaklZUDNzZXNweXJuczJMeGc2TVFRSEk4SkxCYkxXQ2FFUHpBbENUcjRZZ3RVNGpwRUloVkhVSWhSem50NTM3ZjFGMXdQVXFWN01mNE1GZUg2WFk3anl1Z1hxVkc0eXM3ZFZCVkpGNDZlNVA1MmhvYzZ6UT09" static
Definition at line 10 of file musicwyqueryinterface.cpp.
Referenced by makeUser().
constexpr const char* WY_USER2_URL = "TE40MEZBWWJkbkhTbTM2OEVTMkE3VjlJOWZuUjVNQ3BFRGMwYjZ4NW9yeE5QdWozU0ZuSjJrQVdpQkdaT3B4enBMOGpTNUJiVXZDTUxmSWFNRkV5SGVqMXcxaS8rZnlsVmo2bkFJR1BvaGQ2c3llUFlyTVNITWdtcFRpMlA2SEl4VE40RnphRTRza2FPaG5RR3hkeGtZOHVGdHV6Nko3UHNBb25rdz09" static
Definition at line 11 of file musicwyqueryinterface.cpp.
Referenced by makeUser().
constexpr const char* WY_USER3_URL = "c0s1RFpDY0Iya1hNOGFob2JLdGNiUFNxVCs0bE44MDBtQWtmTng4SDRqWlZOZWJXbUkySEtrSDNqVnhUOGMrUVpiNk9lc21MRlFTdFdNYlBwdWNtMmo2VUs4b1M4MFUvS2EzYkpjcnJTZHdZNGdsZ0JsU3lhWkoxaFY1czB4THF6anlDWWp5Ym1VKzJERjAvSmx1WXFPY0ErbjJrMnl2OFhGNGFBUT09" static
Definition at line 12 of file musicwyqueryinterface.cpp.
Referenced by makeUser().
constexpr const char* WY_USER4_URL = "RGdEcVgrSERYQjErNUovY0hFOVU1dElWR00xRVNiRTRVenlHaVpiMkZ1Z0tXV2ZTZVpjL3RCV2pvajhLNjhINjFaUG5QWGdNcnZlcVlxZm93V01IUUgyWWM3NFFTdGE5K203MG5KeE0rNzFPV1ZFUmJHUnBSSHRXRUx1NEVYcU91VGgzWUh6M0hOcUVaUG9YQU9GNXFIaHlDVk5UVGNISmtmcHllQT09" static
Definition at line 13 of file musicwyqueryinterface.cpp.
Referenced by makeUser().
constexpr const char* WY_USER5_URL = "ZmxqdmFXWFlmWFdtYzB2M212VVRaSDhIL1NhYnRySDg5dlV0eWx3YVdZUG82NFlMRlZMNnRHVGFlbVhqaFF0ckJ2YTVRSG12YnYrb1ZqaTJFY2ViK0Y3RG5WbWVHVldzVWk0enFweDd1dkhBNmF1dg==" static
Definition at line 14 of file musicwyqueryinterface.cpp.
Referenced by makeUser().
constexpr const char* WY_USER_URL = "resource/user" static
Definition at line 7 of file musicwyqueryinterface.cpp.
Referenced by ReqWYInterface::makeRequestRawHeader().