TTKMusicplayer: MusicGifLabelWidget Class Reference
MusicGifLabelWidget Class Reference
The class of the float gif label widget.
#include <musicgiflabelwidget.h>
Public Types
enum Type {
Gif_Ballon_White, Gif_Cicle_Blue, Gif_Rice_Font_White, Gif_Rice_Font_Black,
Gif_Rice_Font_Black_Big, Gif_Hourglass_White, Gif_Radio_Blue, Gif_Check_Blue,
Gif_Record_red, Gif_Close_White
}
Public Slots
void timeout ()
Public Member Functions
MusicGifLabelWidget (QWidget *parent=nullptr)
MusicGifLabelWidget (Type type, QWidget *parent=nullptr)
~MusicGifLabelWidget ()
void setType (Type type)
Type type () const
void setInterval (int value)
int interval () const
void setInfinited (bool s)
bool infinited () const
void run (bool run)
bool isRunning () const
void start ()
void stop ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
bool infinitedModeCheck ()
Protected Attributes
int m_index
Type m_type
QTimer * m_timer
QPixmap m_renderer
bool m_isRunning
bool m_infinited
Detailed Description
The class of the float gif label widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicgiflabelwidget.h.
Member Enumeration Documentation
enum MusicGifLabelWidget::Type
Enumerator
Gif_Ballon_White
gif ballon white
Gif_Cicle_Blue
gif cicle blue
Gif_Rice_Font_White
gif rice font white
Gif_Rice_Font_Black
gif rice font black
Gif_Rice_Font_Black_Big
gif rice font black big
Gif_Hourglass_White
gif hourglass white
Gif_Radio_Blue
gif radio blue
Gif_Check_Blue
gif check blue
Gif_Record_red
gif record red
Gif_Close_White
gif close white
Definition at line 35 of file musicgiflabelwidget.h.
Constructor & Destructor Documentation
MusicGifLabelWidget::MusicGifLabelWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 19 of file musicgiflabelwidget.cpp.
References GIF_CICLE_BLUE, m_index, m_infinited, m_isRunning, m_timer, and timeout().
MusicGifLabelWidget::MusicGifLabelWidget (Type type, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 33 of file musicgiflabelwidget.cpp.
References setType().
MusicGifLabelWidget::~MusicGifLabelWidget ()
Definition at line 39 of file musicgiflabelwidget.cpp.
References m_timer.
Member Function Documentation
bool MusicGifLabelWidget::infinited () const
Get the gif infinited mode.
Definition at line 83 of file musicgiflabelwidget.cpp.
References m_infinited.
bool MusicGifLabelWidget::infinitedModeCheck () protected
Infinited mode check.
Definition at line 241 of file musicgiflabelwidget.cpp.
References m_index, m_infinited, and stop().
Referenced by timeout().
int MusicGifLabelWidget::interval () const
Get the gif interval.
Definition at line 73 of file musicgiflabelwidget.cpp.
References m_timer.
bool MusicGifLabelWidget::isRunning () const inline
Get current running state.
Definition at line 93 of file musicgiflabelwidget.h.
Referenced by MusicGifLabelMaskWidget::run().
void MusicGifLabelWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 233 of file musicgiflabelwidget.cpp.
References m_renderer.
void MusicGifLabelWidget::run (bool run)
Run the gif.
Definition at line 88 of file musicgiflabelwidget.cpp.
References start(), and stop().
Referenced by MusicItemSearchTableWidget::createFinishedItem(), MusicItemSearchTableWidget::itemCellClicked(), MusicGifLabelMaskWidget::run(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSoundKMicroSearchTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchQuery(), MusicVideoSearchTableWidget::startSearchQuery(), MusicSongSearchTableWidget::startSearchSingleQuery(), and MusicVideoSearchTableWidget::startSearchSingleQuery().
void MusicGifLabelWidget::setInfinited (bool s)
Set the gif infinited mode.
Definition at line 78 of file musicgiflabelwidget.cpp.
References m_infinited.
Referenced by MusicApplicationModule::windowCloseAnimationFinished().
void MusicGifLabelWidget::setInterval (int value)
Set the gif interval.
Definition at line 68 of file musicgiflabelwidget.cpp.
References m_timer.
Referenced by MusicSongsListPlayedWidget::MusicSongsListPlayedWidget(), and MusicApplicationModule::windowCloseAnimationFinished().
void MusicGifLabelWidget::setType (Type type)
Set the gif type.
Definition at line 44 of file musicgiflabelwidget.cpp.
References GIF_BALLON_WHITE, Gif_Ballon_White, GIF_CHECK_BLUE, Gif_Check_Blue, GIF_CICLE_BLUE, Gif_Cicle_Blue, Gif_Close_White, GIF_CLOSE_WHITE_HEIGHT, GIF_CLOSE_WHITE_WIDTH, GIF_HOURGLASS_WHITE, Gif_Hourglass_White, GIF_RADIO_BLUE, Gif_Radio_Blue, GIF_RECORD_RED, Gif_Record_red, GIF_RICE_FONT_BLACK, Gif_Rice_Font_Black, GIF_RICE_FONT_BLACK_BIG, Gif_Rice_Font_Black_Big, GIF_RICE_FONT_WHITE, Gif_Rice_Font_White, m_index, and m_type.
Referenced by MusicGifLabelWidget(), MusicTimeSliderWidget::MusicTimeSliderWidget(), MusicGifLabelMaskWidget::setType(), and MusicApplicationModule::windowCloseAnimationFinished().
void MusicGifLabelWidget::start ()
Start the gif.
Definition at line 102 of file musicgiflabelwidget.cpp.
References m_isRunning, and m_timer.
Referenced by run(), MusicSongsListPlayedWidget::setParameter(), MusicTimeSliderWidget::setPlayState(), and MusicApplicationModule::windowCloseAnimationFinished().
void MusicGifLabelWidget::stop ()
Stop the gif.
Definition at line 108 of file musicgiflabelwidget.cpp.
References m_isRunning, and m_timer.
Referenced by infinitedModeCheck(), run(), and MusicTimeSliderWidget::setPlayState().
void MusicGifLabelWidget::timeout () slot
Change the current gif index.
Definition at line 114 of file musicgiflabelwidget.cpp.
References GIF_BALLON_WHITE, Gif_Ballon_White, GIF_CHECK_BLUE, Gif_Check_Blue, GIF_CICLE_BLUE, Gif_Cicle_Blue, Gif_Close_White, GIF_CLOSE_WHITE_WIDTH, GIF_HOURGLASS_WHITE, Gif_Hourglass_White, GIF_RADIO_BLUE, Gif_Radio_Blue, GIF_RECORD_RED, Gif_Record_red, GIF_RICE_FONT_BLACK, Gif_Rice_Font_Black, GIF_RICE_FONT_BLACK_BIG, Gif_Rice_Font_Black_Big, GIF_RICE_FONT_WHITE, Gif_Rice_Font_White, infinitedModeCheck(), m_index, m_renderer, and m_type.
Referenced by MusicGifLabelWidget().
MusicGifLabelWidget::Type MusicGifLabelWidget::type () const
Get the gif type.
Definition at line 63 of file musicgiflabelwidget.cpp.
References m_type.
Referenced by MusicGifLabelMaskWidget::type().
Member Data Documentation
int MusicGifLabelWidget::m_index protected
Definition at line 120 of file musicgiflabelwidget.h.
Referenced by infinitedModeCheck(), MusicGifLabelWidget(), setType(), and timeout().
bool MusicGifLabelWidget::m_infinited protected
Definition at line 124 of file musicgiflabelwidget.h.
Referenced by infinited(), infinitedModeCheck(), MusicGifLabelWidget(), and setInfinited().
bool MusicGifLabelWidget::m_isRunning protected
Definition at line 124 of file musicgiflabelwidget.h.
Referenced by MusicGifLabelWidget(), start(), and stop().
QPixmap MusicGifLabelWidget::m_renderer protected
Definition at line 123 of file musicgiflabelwidget.h.
Referenced by paintEvent(), and timeout().
QTimer* MusicGifLabelWidget::m_timer protected
Definition at line 122 of file musicgiflabelwidget.h.
Referenced by interval(), MusicGifLabelWidget(), setInterval(), start(), stop(), and ~MusicGifLabelWidget().
Type MusicGifLabelWidget::m_type protected
Definition at line 121 of file musicgiflabelwidget.h.
Referenced by setType(), timeout(), and type().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicgiflabelwidget.h
TTKModule/TTKWidget/musicCoreKits/musicgiflabelwidget.cpp