TTKMusicplayer: MusicLrcFloatPhotoItem Class Reference
MusicLrcFloatPhotoItem Class Reference
The class of the lrc photo float pixmap item.
#include <musiclrcfloatphotowidget.h>
Public Slots
void sendUserBoxClicked ()
void sendUserSelectArt ()
void exportArtPixmap ()
Signals
void itemClicked (int index)
void boxClicked (int index)
Signals inherited from MusicClickedLabel
void clicked ()
Public Member Functions
MusicLrcFloatPhotoItem (int index, QWidget *parent=nullptr)
~MusicLrcFloatPhotoItem ()
void setPhoto (const QString &path)
void setBoxChecked (bool check)
bool boxChecked ()
void setBoxVisible (bool v)
Public Member Functions inherited from MusicClickedLabel
MusicClickedLabel (QWidget *parent=nullptr)
MusicClickedLabel (const QString &text, QWidget *parent=nullptr)
Protected Member Functions
virtual void enterEvent (QEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicClickedLabel
virtual void mousePressEvent (QMouseEvent *event) override
Protected Attributes
int m_index
QString m_pixPath
QCheckBox * m_checkBox
Detailed Description
The class of the lrc photo float pixmap item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrcfloatphotowidget.h.
Constructor & Destructor Documentation
MusicLrcFloatPhotoItem::MusicLrcFloatPhotoItem (int index, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 16 of file musiclrcfloatphotowidget.cpp.
References MusicClickedLabel::clicked(), m_checkBox, m_index, MusicUIObject::MQSSCheckBoxStyle01, PHOTO_HEIGHT, PHOTO_WIDTH, sendUserBoxClicked(), and sendUserSelectArt().
MusicLrcFloatPhotoItem::~MusicLrcFloatPhotoItem ()
Definition at line 33 of file musiclrcfloatphotowidget.cpp.
References m_checkBox.
Member Function Documentation
bool MusicLrcFloatPhotoItem::boxChecked ()
Get check box checked state.
Definition at line 60 of file musiclrcfloatphotowidget.cpp.
References m_checkBox.
void MusicLrcFloatPhotoItem::boxClicked (int index) signal
Current check box clicked.
Referenced by sendUserBoxClicked().
void MusicLrcFloatPhotoItem::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 118 of file musiclrcfloatphotowidget.cpp.
References exportArtPixmap(), and MusicUIObject::MQSSMenuStyle02.
void MusicLrcFloatPhotoItem::enterEvent (QEvent * event) override protected virtual
Override the widget event.
Definition at line 100 of file musiclrcfloatphotowidget.cpp.
void MusicLrcFloatPhotoItem::exportArtPixmap () slot
Export art pixmap.
Definition at line 87 of file musiclrcfloatphotowidget.cpp.
References MusicUtils::File::getSaveFileDialog(), JPG_FILE_PREFIX, and m_pixPath.
Referenced by contextMenuEvent().
void MusicLrcFloatPhotoItem::itemClicked (int index) signal
Current plane item clicked.
Referenced by sendUserSelectArt().
void MusicLrcFloatPhotoItem::sendUserBoxClicked () slot
User selected the check box state.
Definition at line 70 of file musiclrcfloatphotowidget.cpp.
References boxClicked(), and m_index.
Referenced by MusicLrcFloatPhotoItem().
void MusicLrcFloatPhotoItem::sendUserSelectArt () slot
User selected the plane pic.
Definition at line 75 of file musiclrcfloatphotowidget.cpp.
References itemClicked(), and m_index.
Referenced by MusicLrcFloatPhotoItem().
void MusicLrcFloatPhotoItem::setBoxChecked (bool check)
Set check box checked state.
Definition at line 55 of file musiclrcfloatphotowidget.cpp.
References m_checkBox.
void MusicLrcFloatPhotoItem::setBoxVisible (bool v)
Set check box vidible.
Definition at line 65 of file musiclrcfloatphotowidget.cpp.
References m_checkBox.
void MusicLrcFloatPhotoItem::setPhoto (const QString & path)
Set photo path and pix.
Definition at line 38 of file musiclrcfloatphotowidget.cpp.
References m_pixPath.
Member Data Documentation
QCheckBox* MusicLrcFloatPhotoItem::m_checkBox protected
Definition at line 96 of file musiclrcfloatphotowidget.h.
Referenced by boxChecked(), MusicLrcFloatPhotoItem(), setBoxChecked(), setBoxVisible(), and ~MusicLrcFloatPhotoItem().
int MusicLrcFloatPhotoItem::m_index protected
Definition at line 94 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoItem(), sendUserBoxClicked(), and sendUserSelectArt().
QString MusicLrcFloatPhotoItem::m_pixPath protected
Definition at line 95 of file musiclrcfloatphotowidget.h.
Referenced by exportArtPixmap(), and setPhoto().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatphotowidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatphotowidget.cpp