TTKMusicplayer: MusicTopListFoundWidget Class Reference
MusicTopListFoundWidget Class Reference
The class of toplist music found widget.
#include <musictoplistfoundwidget.h>
Public Slots
void queryAllFinished ()
void createToplistInfoItem (const MusicPlaylistItem &item)
void downLoadFinished (const QByteArray &data)
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicTopListFoundWidget (QWidget *parent=0)
virtual ~MusicTopListFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Member Functions
void createLabels ()
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
Protected Attributes
QLabel * m_iconLabel
QLabel * m_nameLabel
QLabel * m_playCountLabel
QLabel * m_updateTimeLabel
QLabel * m_descriptionLabel
QLabel * m_songItemsLabel
MusicTopListFoundTableWidget * m_toplistTableWidget
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QLabel * m_statusLabel
QList< QLabel * > m_resizeWidget
Detailed Description
The class of toplist music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 44 of file musictoplistfoundwidget.h.
Constructor & Destructor Documentation
MusicTopListFoundWidget::MusicTopListFoundWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 40 of file musictoplistfoundwidget.cpp.
References createToplistInfoItem(), M_DOWNLOAD_QUERY_PTR, m_toplistTableWidget, and MusicTopListFoundTableWidget::setQueryInput().
MusicTopListFoundWidget::~MusicTopListFoundWidget () virtual
Definition at line 50 of file musictoplistfoundwidget.cpp.
References m_toplistTableWidget.
Member Function Documentation
void MusicTopListFoundWidget::addButtonClicked () slot
Add button clicked now.
Definition at line 239 of file musictoplistfoundwidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), and m_toplistTableWidget.
Referenced by createLabels().
void MusicTopListFoundWidget::createLabels () protected
Create init interface lables.
Definition at line 86 of file musictoplistfoundwidget.cpp.
References addButtonClicked(), downloadButtonClicked(), m_descriptionLabel, m_iconLabel, MusicFoundAbstractWidget::m_mainWindow, m_nameLabel, m_playCountLabel, m_songItemsLabel, MusicFoundAbstractWidget::m_statusLabel, m_toplistTableWidget, m_updateTimeLabel, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MColorStyle04, MusicUIObject::MFontStyle01, MusicUIObject::MFontStyle03, MusicUIObject::MFontStyle04, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, and playButtonClicked().
Referenced by setSongName().
void MusicTopListFoundWidget::createToplistInfoItem (const MusicPlaylistItem & item) slot
Create the current toplist info item.
Definition at line 194 of file musictoplistfoundwidget.cpp.
References downLoadFinished(), MusicUtils::Widget::elidedText(), MusicPlaylistItem::m_coverUrl, MusicPlaylistItem::m_description, m_descriptionLabel, MusicPlaylistItem::m_name, m_nameLabel, MusicPlaylistItem::m_playCount, m_playCountLabel, MusicPlaylistItem::m_updateTime, m_updateTimeLabel, and MusicDownloadSourceThread::startToDownload().
Referenced by MusicTopListFoundWidget().
void MusicTopListFoundWidget::downloadButtonClicked () slot
Download button clicked now.
Definition at line 231 of file musictoplistfoundwidget.cpp.
References MusicFillItemTableWidget::getSelectedItems(), m_toplistTableWidget, and MusicQueryFoundTableWidget::musicDownloadLocal().
Referenced by createLabels().
void MusicTopListFoundWidget::downLoadFinished (const QByteArray & data) slot
Send recieved data from net.
Definition at line 216 of file musictoplistfoundwidget.cpp.
References m_iconLabel.
Referenced by createToplistInfoItem().
QString MusicTopListFoundWidget::getClassName () static
Get class object name.
Definition at line 55 of file musictoplistfoundwidget.cpp.
void MusicTopListFoundWidget::playButtonClicked () slot
Play button clicked now.
Definition at line 226 of file musictoplistfoundwidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), and m_toplistTableWidget.
Referenced by createLabels().
void MusicTopListFoundWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 80 of file musictoplistfoundwidget.cpp.
References MusicQueryFoundTableWidget::getMusicSongInfos(), m_songItemsLabel, and m_toplistTableWidget.
void MusicTopListFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 68 of file musictoplistfoundwidget.cpp.
References MusicUtils::Widget::elidedText(), m_nameLabel, m_playCountLabel, M_SETTING_PTR, m_toplistTableWidget, m_updateTimeLabel, MusicQueryFoundTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
void MusicTopListFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 60 of file musictoplistfoundwidget.cpp.
References createLabels(), m_toplistTableWidget, MusicFoundAbstractWidget::setSongName(), and MusicQueryFoundTableWidget::startSearchQuery().
Member Data Documentation
QLabel * MusicTopListFoundWidget::m_descriptionLabel protected
Definition at line 103 of file musictoplistfoundwidget.h.
Referenced by createLabels(), and createToplistInfoItem().
QLabel* MusicTopListFoundWidget::m_iconLabel protected
Definition at line 102 of file musictoplistfoundwidget.h.
Referenced by createLabels(), and downLoadFinished().
QLabel * MusicTopListFoundWidget::m_nameLabel protected
Definition at line 102 of file musictoplistfoundwidget.h.
Referenced by createLabels(), createToplistInfoItem(), and resizeWindow().
QLabel * MusicTopListFoundWidget::m_playCountLabel protected
Definition at line 102 of file musictoplistfoundwidget.h.
Referenced by createLabels(), createToplistInfoItem(), and resizeWindow().
QLabel * MusicTopListFoundWidget::m_songItemsLabel protected
Definition at line 103 of file musictoplistfoundwidget.h.
Referenced by createLabels(), and queryAllFinished().
MusicTopListFoundTableWidget* MusicTopListFoundWidget::m_toplistTableWidget protected
Definition at line 105 of file musictoplistfoundwidget.h.
Referenced by addButtonClicked(), createLabels(), downloadButtonClicked(), MusicTopListFoundWidget(), playButtonClicked(), queryAllFinished(), resizeWindow(), setSongName(), and ~MusicTopListFoundWidget().
QLabel* MusicTopListFoundWidget::m_updateTimeLabel protected
Definition at line 103 of file musictoplistfoundwidget.h.
Referenced by createLabels(), createToplistInfoItem(), and resizeWindow().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musictoplistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musictoplistfoundwidget.cpp