TTKMusicplayer: MusicSongSearchOnlineWidget Class Reference
MusicSongSearchOnlineWidget Class Reference
The class of the song search online widget.
#include <musicsongsearchonlinewidget.h>
Public Slots
void buttonClicked (int index)
void auditionIsPlaying (bool play)
Public Member Functions
MusicSongSearchOnlineWidget (QWidget *parent=nullptr)
~MusicSongSearchOnlineWidget ()
void startSearchQuery (const QString &name)
void startSearchQuery (const QString &name, bool all)
void startSearchSingleQuery (const QString &name)
void researchQueryByQuality (const QString &name, const QString &quality)
void resizeWindow ()
void auditionStop ()
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
void createToolWidget (QWidget *widget)
void setResizeLabelText (const QString &name)
Protected Attributes
QLabel * m_textLabel
QPushButton * m_playButton
QList< QWidget * > m_resizeLabels
MusicSongSearchTableWidget * m_searchTableWidget
Detailed Description
The class of the song search online widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 177 of file musicsongsearchonlinewidget.h.
Constructor & Destructor Documentation
MusicSongSearchOnlineWidget::MusicSongSearchOnlineWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 454 of file musicsongsearchonlinewidget.cpp.
References auditionIsPlaying(), createToolWidget(), MusicRightAreaWidget::instance(), and m_searchTableWidget.
MusicSongSearchOnlineWidget::~MusicSongSearchOnlineWidget ()
Definition at line 478 of file musicsongsearchonlinewidget.cpp.
References m_playButton, m_resizeLabels, m_searchTableWidget, and m_textLabel.
Member Function Documentation
void MusicSongSearchOnlineWidget::auditionIsPlaying (bool play) slot
Check current audtion is playing or not.
Definition at line 585 of file musicsongsearchonlinewidget.cpp.
References m_playButton.
Referenced by MusicSongSearchOnlineWidget().
void MusicSongSearchOnlineWidget::auditionStop ()
Stop current audtion.
Definition at line 525 of file musicsongsearchonlinewidget.cpp.
References MusicSongSearchTableWidget::auditionStop(), and m_searchTableWidget.
void MusicSongSearchOnlineWidget::buttonClicked (int index) slot
Set diff button clicked by index.
Definition at line 530 of file musicsongsearchonlinewidget.cpp.
References MusicSongSearchTableWidget::auditionToMusic(), MusicSongSearchTableWidget::auditionToMusicStop(), MusicMessageBox::exec(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicQueryTableWidget::getQueryInput(), MusicFillItemTableWidget::getSelectedItems(), MusicSongSearchTableWidget::listCellClicked(), m_playButton, m_searchTableWidget, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownloadBatchWidget::setSongName(), MusicMessageBox::setText(), and MusicDownloadBatchWidget::show().
Referenced by createToolWidget().
void MusicSongSearchOnlineWidget::createToolWidget (QWidget * widget) protected
Create tool widget.
Definition at line 596 of file musicsongsearchonlinewidget.cpp.
References buttonClicked(), m_playButton, m_resizeLabels, m_searchTableWidget, m_textLabel, MusicUIObject::MBackgroundStyle03, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MColorStyle03, MusicUIObject::MFontStyle01, and MusicUIObject::MPushButtonStyle03.
Referenced by MusicSongSearchOnlineWidget().
void MusicSongSearchOnlineWidget::researchQueryByQuality (const QString & name, const QString & quality)
Research query by quality it changed.
Definition at line 513 of file musicsongsearchonlinewidget.cpp.
References m_searchTableWidget, MusicSongSearchTableWidget::setSearchQuality(), and startSearchQuery().
void MusicSongSearchOnlineWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Definition at line 590 of file musicsongsearchonlinewidget.cpp.
References m_textLabel, and setResizeLabelText().
void MusicSongSearchOnlineWidget::resizeWindow ()
Resize window bound by widgte resize called.
Definition at line 519 of file musicsongsearchonlinewidget.cpp.
References m_searchTableWidget, m_textLabel, MusicSongSearchTableWidget::resizeWindow(), and setResizeLabelText().
void MusicSongSearchOnlineWidget::setResizeLabelText (const QString & name) protected
Set resize labelt ext.
Definition at line 691 of file musicsongsearchonlinewidget.cpp.
References MusicUtils::Widget::elidedText(), m_resizeLabels, M_SETTING_PTR, m_textLabel, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), resizeWindow(), startSearchQuery(), and startSearchSingleQuery().
void MusicSongSearchOnlineWidget::startSearchQuery (const QString & name)
Start search query by text.
Definition at line 486 of file musicsongsearchonlinewidget.cpp.
Referenced by researchQueryByQuality().
void MusicSongSearchOnlineWidget::startSearchQuery (const QString & name, bool all)
Start search query by text.
Definition at line 491 of file musicsongsearchonlinewidget.cpp.
References m_resizeLabels, m_searchTableWidget, MStatic_cast, MusicSongSearchTableWidget::setQueryAllRecords(), setResizeLabelText(), and MusicSongSearchTableWidget::startSearchQuery().
void MusicSongSearchOnlineWidget::startSearchSingleQuery (const QString & name)
Start search query by given id.
Definition at line 502 of file musicsongsearchonlinewidget.cpp.
References m_resizeLabels, m_searchTableWidget, MStatic_cast, MusicSongSearchTableWidget::setQueryAllRecords(), setResizeLabelText(), and MusicSongSearchTableWidget::startSearchSingleQuery().
Member Data Documentation
QPushButton* MusicSongSearchOnlineWidget::m_playButton protected
Definition at line 239 of file musicsongsearchonlinewidget.h.
Referenced by auditionIsPlaying(), buttonClicked(), createToolWidget(), and ~MusicSongSearchOnlineWidget().
QList<QWidget*> MusicSongSearchOnlineWidget::m_resizeLabels protected
Definition at line 240 of file musicsongsearchonlinewidget.h.
Referenced by createToolWidget(), setResizeLabelText(), startSearchQuery(), startSearchSingleQuery(), and ~MusicSongSearchOnlineWidget().
MusicSongSearchTableWidget* MusicSongSearchOnlineWidget::m_searchTableWidget protected
Definition at line 241 of file musicsongsearchonlinewidget.h.
Referenced by auditionStop(), buttonClicked(), createToolWidget(), MusicSongSearchOnlineWidget(), researchQueryByQuality(), resizeWindow(), startSearchQuery(), startSearchSingleQuery(), and ~MusicSongSearchOnlineWidget().
QLabel* MusicSongSearchOnlineWidget::m_textLabel protected
Definition at line 238 of file musicsongsearchonlinewidget.h.
Referenced by createToolWidget(), resizeEvent(), resizeWindow(), setResizeLabelText(), and ~MusicSongSearchOnlineWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongsearchonlinewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongsearchonlinewidget.cpp