TTKMusicplayer: MusicAbstractDownLoadRequest Class Reference
MusicAbstractDownLoadRequest Class Reference abstract
The class of abstract downloading data.
#include <musicabstractdownloadrequest.h>
Public Slots
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicAbstractDownLoadRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () override
virtual void startToDownload ()=0
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
QString mapCurrentQueryData () const
Protected Attributes
QFile * m_file
QString m_url
QString m_savePath
MusicObject::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Detailed Description
The class of abstract downloading data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicabstractdownloadrequest.h.
Constructor & Destructor Documentation
MusicAbstractDownLoadRequest::MusicAbstractDownLoadRequest (const QString & url, const QString & save, MusicObject::DownloadType type, QObject * parent = nullptr)
Object contsructor provide download URL\ save local path and download type.
Definition at line 8 of file musicabstractdownloadrequest.cpp.
References G_DOWNLOAD_MANAGER_PTR, m_currentReceived, m_downloadType, m_file, m_hasReceived, m_savePath, m_speedTimer, m_url, MT_S2MS, and updateDownloadSpeed().
MusicAbstractDownLoadRequest::~MusicAbstractDownLoadRequest ()
Definition at line 29 of file musicabstractdownloadrequest.cpp.
References G_DOWNLOAD_MANAGER_PTR, and m_speedTimer.
Member Function Documentation
void MusicAbstractDownLoadRequest::deleteAll () override virtual
Release the network object.
Reimplemented from MusicAbstractNetwork.
Definition at line 38 of file musicabstractdownloadrequest.cpp.
References MusicAbstractNetwork::deleteAll(), and m_file.
Referenced by MusicDownLoadTextRequest::downLoadFinished(), MusicKWDownLoadTextRequest::downLoadFinished(), MusicFMRadioDownLoadTextRequest::downLoadFinished(), MusicQQDownLoadTextRequest::downLoadFinished(), MusicWYDownLoadTextRequest::downLoadFinished(), MusicDownloadDataRequest::downLoadFinished(), replyError(), sslErrors(), MusicQQDownLoadTextRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicDownloadDataRequest::startToDownload(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicDownLoadTextRequest::startToDownload(), MusicDownloadTagDataRequest::startToDownload(), and MusicDownloadQueueRequest::~MusicDownloadQueueRequest().
void MusicAbstractDownLoadRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 49 of file musicabstractdownloadrequest.cpp.
References MusicAbstractNetwork::downLoadFinished(), and m_speedTimer.
Referenced by MusicDownLoadTextRequest::downLoadFinished(), MusicFMRadioDownLoadTextRequest::downLoadFinished(), MusicKWDownLoadTextRequest::downLoadFinished(), MusicQQDownLoadTextRequest::downLoadFinished(), MusicWYDownLoadTextRequest::downLoadFinished(), MusicDownloadDataRequest::downLoadFinished(), and MusicDownloadQueueRequest::downLoadFinished().
void MusicAbstractDownLoadRequest::downloadProgress (qint64 bytesReceived, qint64 bytesTotal) virtual slot
Get download received and total data.
Definition at line 71 of file musicabstractdownloadrequest.cpp.
References m_currentReceived, and m_totalSize.
Referenced by MusicDownloadDataRequest::downloadProgress(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), and MusicDownLoadTextRequest::startToDownload().
QString MusicAbstractDownLoadRequest::mapCurrentQueryData () const protected
Map the enum type to string.
Definition at line 93 of file musicabstractdownloadrequest.cpp.
References MusicObject::DownloadBigBackground, MusicObject::DownloadLrc, MusicObject::DownloadMusic, MusicObject::DownloadOther, MusicObject::DownloadSmallBackground, MusicObject::DownloadVideo, and m_downloadType.
Referenced by MusicDownLoadTextRequest::downLoadFinished(), MusicKWDownLoadTextRequest::downLoadFinished(), MusicQQDownLoadTextRequest::downLoadFinished(), MusicWYDownLoadTextRequest::downLoadFinished(), MusicDownloadTagDataRequest::downLoadFinished(), and MusicDownloadDataRequest::downLoadFinished().
void MusicAbstractDownLoadRequest::replyError (QNetworkReply::NetworkError error) override virtual slot
Download reply error.
Definition at line 55 of file musicabstractdownloadrequest.cpp.
References deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), and TTK_LOGGER_ERROR.
Referenced by MusicDownloadDataRequest::startRequest(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), and MusicDownLoadTextRequest::startToDownload().
void MusicAbstractDownLoadRequest::sslErrors (QNetworkReply * reply, const QList< QSslError > & errors) override virtual slot
Download ssl reply error.
Definition at line 63 of file musicabstractdownloadrequest.cpp.
References deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), and MusicAbstractNetwork::sslErrorsString().
virtual void MusicAbstractDownLoadRequest::startToDownload () pure virtual
Start to download data. Subclass should implement this function.
Implemented in MusicDownloadQueueRequest, MusicDownloadTagDataRequest, MusicDownloadDataRequest, MusicDownLoadTextRequest, MusicKWDownLoadTextRequest, MusicQQDownLoadTextRequest, MusicWYDownLoadTextRequest, and MusicFMRadioDownLoadTextRequest.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget().
void MusicAbstractDownLoadRequest::updateDownloadSpeed () virtual slot
Updata download speed due the user mod the net speed limited.
limit speed
Definition at line 77 of file musicabstractdownloadrequest.cpp.
References MusicSettingManager::DownloadDownloadLimitSize, MusicSettingManager::DownloadLimitEnable, G_SETTING_PTR, m_currentReceived, m_hasReceived, MH_KB, MT_S2MS, and MusicUtils::Core::sleep().
Referenced by MusicAbstractDownLoadRequest(), and MusicDownloadDataRequest::updateDownloadSpeed().
Member Data Documentation
qint64 MusicAbstractDownLoadRequest::m_currentReceived protected
Definition at line 85 of file musicabstractdownloadrequest.h.
Referenced by downloadProgress(), MusicAbstractDownLoadRequest(), updateDownloadSpeed(), and MusicDownloadDataRequest::updateDownloadSpeed().
MusicObject::DownloadType MusicAbstractDownLoadRequest::m_downloadType protected
Definition at line 84 of file musicabstractdownloadrequest.h.
Referenced by MusicDownloadDataRequest::downloadProgress(), mapCurrentQueryData(), MusicAbstractDownLoadRequest(), and MusicDownloadDataRequest::startRequest().
QFile* MusicAbstractDownLoadRequest::m_file protected
Definition at line 82 of file musicabstractdownloadrequest.h.
Referenced by MusicDownloadQueueRequest::abort(), deleteAll(), MusicWYDownLoadTextRequest::downLoadFinished(), MusicQQDownLoadTextRequest::downLoadFinished(), MusicFMRadioDownLoadTextRequest::downLoadFinished(), MusicDownLoadTextRequest::downLoadFinished(), MusicKWDownLoadTextRequest::downLoadFinished(), MusicDownloadTagDataRequest::downLoadFinished(), MusicDownloadDataRequest::downLoadFinished(), MusicDownloadQueueRequest::downLoadFinished(), MusicDownloadQueueRequest::handleError(), MusicDownloadDataRequest::handleReadyRead(), MusicDownloadQueueRequest::handleReadyRead(), MusicAbstractDownLoadRequest(), MusicDownloadQueueRequest::startDownload(), MusicDownLoadTextRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicDownloadDataRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), MusicFMRadioDownLoadTextRequest::startToDownload(), and MusicDownloadTagDataRequest::startToDownload().
qint64 MusicAbstractDownLoadRequest::m_hasReceived protected
Definition at line 85 of file musicabstractdownloadrequest.h.
Referenced by MusicAbstractDownLoadRequest(), updateDownloadSpeed(), and MusicDownloadDataRequest::updateDownloadSpeed().
QString MusicAbstractDownLoadRequest::m_savePath protected
Definition at line 83 of file musicabstractdownloadrequest.h.
Referenced by MusicDownloadTagDataRequest::downLoadFinished(), MusicAbstractDownLoadRequest(), and MusicDownloadDataRequest::startRequest().
QTimer MusicAbstractDownLoadRequest::m_speedTimer protected
Definition at line 86 of file musicabstractdownloadrequest.h.
Referenced by downLoadFinished(), MusicAbstractDownLoadRequest(), MusicDownloadQueueRequest::startDownload(), MusicDownloadDataRequest::startRequest(), MusicDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicKWDownLoadTextRequest::startToDownload(), and ~MusicAbstractDownLoadRequest().
qint64 MusicAbstractDownLoadRequest::m_totalSize protected
Definition at line 85 of file musicabstractdownloadrequest.h.
Referenced by downloadProgress(), and MusicDownloadDataRequest::updateDownloadSpeed().
QString MusicAbstractDownLoadRequest::m_url protected
Definition at line 83 of file musicabstractdownloadrequest.h.
Referenced by MusicAbstractDownLoadRequest(), MusicKWDownLoadTextRequest::startToDownload(), MusicDownLoadTextRequest::startToDownload(), MusicWYDownLoadTextRequest::startToDownload(), MusicQQDownLoadTextRequest::startToDownload(), MusicFMRadioDownLoadTextRequest::startToDownload(), MusicDownloadDataRequest::startToDownload(), and MusicDownloadTagDataRequest::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicabstractdownloadrequest.h
TTKModule/TTKCore/musicNetworkKits/musicabstractdownloadrequest.cpp