TTKMusicplayer: MusicWebMVRadioFoundItemWidget Class Reference
MusicWebMVRadioFoundItemWidget Class Reference
The class of the music mv found item widget.
#include <musicwebmvradiofoundwidget.h>
Public Slots
void downLoadFinished (const QByteArray &data)
void currentItemClicked ()
Signals
void currentItemClicked (const MusicResultsItem &item)
Public Member Functions
MusicWebMVRadioFoundItemWidget (QWidget *parent=0)
virtual ~MusicWebMVRadioFoundItemWidget ()
void setMusicResultsItem (const MusicResultsItem &item)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
Protected Attributes
MusicResultsItem m_itemData
QPushButton * m_playButton
QLabel * m_iconLabel
QLabel * m_nameLabel
Detailed Description
The class of the music mv found item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicwebmvradiofoundwidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioFoundItemWidget::MusicWebMVRadioFoundItemWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 13 of file musicwebmvradiofoundwidget.cpp.
References currentItemClicked(), HEIGHT_LABEL_SIZE, m_iconLabel, m_nameLabel, m_playButton, MusicUIObject::MColorStyle01, MusicUIObject::MFontStyle01, MusicUIObject::MFontStyle05, MusicUIObject::MKGTinyBtnPlaylist, and WIDTH_LABEL_SIZE.
MusicWebMVRadioFoundItemWidget::~MusicWebMVRadioFoundItemWidget () virtual
Definition at line 38 of file musicwebmvradiofoundwidget.cpp.
References m_iconLabel, m_nameLabel, and m_playButton.
Member Function Documentation
void MusicWebMVRadioFoundItemWidget::currentItemClicked (const MusicResultsItem & item) signal
Current item clicked.
void MusicWebMVRadioFoundItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 83 of file musicwebmvradiofoundwidget.cpp.
References m_itemData.
Referenced by MusicWebMVRadioFoundItemWidget().
void MusicWebMVRadioFoundItemWidget::downLoadFinished (const QByteArray & data) slot
Send recieved data from net.
Definition at line 67 of file musicwebmvradiofoundwidget.cpp.
References MusicUtils::Widget::fusionPixmap(), m_iconLabel, and m_playButton.
Referenced by setMusicResultsItem().
void MusicWebMVRadioFoundItemWidget::enterEvent (QEvent * event) override protected virtual
Override the widget event.
Definition at line 88 of file musicwebmvradiofoundwidget.cpp.
References m_nameLabel, and m_playButton.
QString MusicWebMVRadioFoundItemWidget::getClassName () static
Get class object name.
Definition at line 45 of file musicwebmvradiofoundwidget.cpp.
void MusicWebMVRadioFoundItemWidget::leaveEvent (QEvent * event) override protected virtual
Definition at line 96 of file musicwebmvradiofoundwidget.cpp.
References m_nameLabel, and m_playButton.
void MusicWebMVRadioFoundItemWidget::setMusicResultsItem (const MusicResultsItem & item)
Set music results item.
Definition at line 50 of file musicwebmvradiofoundwidget.cpp.
References downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, m_itemData, MusicResultsItem::m_name, m_nameLabel, m_playButton, MusicDownloadSourceThread::startToDownload(), and WIDTH_LABEL_SIZE.
Referenced by MusicWebMVRadioFoundWidget::createCategoryItem().
Member Data Documentation
QLabel* MusicWebMVRadioFoundItemWidget::m_iconLabel protected
Definition at line 77 of file musicwebmvradiofoundwidget.h.
Referenced by downLoadFinished(), MusicWebMVRadioFoundItemWidget(), and ~MusicWebMVRadioFoundItemWidget().
MusicResultsItem MusicWebMVRadioFoundItemWidget::m_itemData protected
Definition at line 75 of file musicwebmvradiofoundwidget.h.
Referenced by currentItemClicked(), and setMusicResultsItem().
QLabel * MusicWebMVRadioFoundItemWidget::m_nameLabel protected
Definition at line 77 of file musicwebmvradiofoundwidget.h.
Referenced by enterEvent(), leaveEvent(), MusicWebMVRadioFoundItemWidget(), setMusicResultsItem(), and ~MusicWebMVRadioFoundItemWidget().
QPushButton* MusicWebMVRadioFoundItemWidget::m_playButton protected
Definition at line 76 of file musicwebmvradiofoundwidget.h.
Referenced by downLoadFinished(), enterEvent(), leaveEvent(), MusicWebMVRadioFoundItemWidget(), setMusicResultsItem(), and ~MusicWebMVRadioFoundItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradiofoundwidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradiofoundwidget.cpp