TTKMusicplayer: MusicConsoleObject Class Reference
MusicConsoleObject Class Reference
The class of the music console object.
#include <musicconsoleobject.h>
Public Member Functions
MusicConsoleObject (QObject *parent=nullptr)
~MusicConsoleObject ()
bool init (const QCoreApplication &app)
Protected Member Functions
void print (qint64 position, qint64 duration)
Protected Attributes
MusicPlayer * m_musicPlayer
MusicPlaylist * m_musicPlaylist
int m_volume
QString m_playbackMode
QString m_enhanced
Private Slots
void durationChanged (qint64 duration)
void positionChanged (qint64 position)
void currentIndexChanged (int index)
void musicStatePlay ()
void musicPlayPrevious ()
void musicPlayNext ()
void resetVolume ()
void musicActionVolumeSub ()
void musicActionVolumePlus ()
void musicPlayOrder ()
void musicPlayRandom ()
void musicPlaylistLoop ()
void musicPlayOneLoop ()
void musicPlayItemOnce ()
void musicEnhancedOff ()
void musicEnhanced3D ()
void musicEnhancedNICAM ()
void musicEnhancedSubwoofer ()
void musicEnhancedVocal ()
Detailed Description
The class of the music console object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicconsoleobject.h.
Constructor & Destructor Documentation
MusicConsoleObject::MusicConsoleObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 14 of file musicconsoleobject.cpp.
References currentIndexChanged(), durationChanged(), m_enhanced, M_HOTKEY_PTR, m_musicPlayer, m_musicPlaylist, m_playbackMode, m_volume, musicActionVolumePlus(), musicActionVolumeSub(), musicEnhanced3D(), musicEnhancedNICAM(), musicEnhancedOff(), musicEnhancedSubwoofer(), musicEnhancedVocal(), musicPlayItemOnce(), musicPlaylistLoop(), musicPlayNext(), musicPlayOneLoop(), musicPlayOrder(), musicPlayPrevious(), musicPlayRandom(), musicStatePlay(), MusicObject::PM_PlayOrder, positionChanged(), MusicPlaylist::setPlaybackMode(), and MusicPlayer::setPlaylist().
MusicConsoleObject::~MusicConsoleObject ()
Definition at line 70 of file musicconsoleobject.cpp.
References m_musicPlayer, m_musicPlaylist, and TTK_LOGGER_INFO.
Member Function Documentation
void MusicConsoleObject::currentIndexChanged (int index) private slot
Current playlist index changed.
Definition at line 203 of file musicconsoleobject.cpp.
References MT_S2MS, resetVolume(), and TTK_LOGGER_INFO.
Referenced by MusicConsoleObject().
void MusicConsoleObject::durationChanged (qint64 duration) private slot
Current duration changed.
Definition at line 193 of file musicconsoleobject.cpp.
References print().
Referenced by MusicConsoleObject().
bool MusicConsoleObject::init (const QCoreApplication & app)
Init all parameter.
Definition at line 77 of file musicconsoleobject.cpp.
References MusicPlaylist::addMedia(), MusicPlaylist::appendMedia(), MusicUtils::File::getFileListByDir(), MusicSong::getMusicPath(), MusicPlaylist::isEmpty(), LST_FILE_PREFIX, m_musicPlayer, m_musicPlaylist, MusicSongItem::m_songs, m_volume, MusicPlaylist::mediaCount(), MusicPlayer::play(), MusicTKPLConfigManager::readConfig(), MusicTKPLConfigManager::readPlaylistData(), MusicPlaylist::setCurrentIndex(), MusicPlayer::setVolume(), MusicFormats::supportFormatsFilterString(), TTK_LOGGER_ERROR, and TTK_LOGGER_INFO.
Referenced by main().
void MusicConsoleObject::musicActionVolumePlus () private slot
Set current player volume up.
Definition at line 284 of file musicconsoleobject.cpp.
References m_musicPlayer, m_volume, MusicPlayer::setVolume(), and MusicPlayer::volume().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicActionVolumeSub () private slot
Set current player volume down.
Definition at line 272 of file musicconsoleobject.cpp.
References m_musicPlayer, m_volume, MusicPlayer::setVolume(), and MusicPlayer::volume().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicEnhanced3D () private slot
Set current music 3d music effect.
Definition at line 332 of file musicconsoleobject.cpp.
References MusicPlayer::Enhanced3D, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicEnhancedNICAM () private slot
Set current music nicam music effect.
Definition at line 338 of file musicconsoleobject.cpp.
References MusicPlayer::EnhancedNICAM, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicEnhancedOff () private slot
Set current music enhanced off, no any effect.
Definition at line 326 of file musicconsoleobject.cpp.
References MusicPlayer::EnhancedOff, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicEnhancedSubwoofer () private slot
Set current music subwoofer music effect.
Definition at line 344 of file musicconsoleobject.cpp.
References MusicPlayer::EnhancedSubwoofer, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicEnhancedVocal () private slot
Set current music vocal music effect.
Definition at line 350 of file musicconsoleobject.cpp.
References MusicPlayer::EnhancedVocal, m_enhanced, m_musicPlayer, and MusicPlayer::setMusicEnhanced().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlayItemOnce () private slot
Set current play mdoe to just once.
Definition at line 320 of file musicconsoleobject.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayOnce, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlaylistLoop () private slot
Set current play mdoe to list loop.
Definition at line 308 of file musicconsoleobject.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlaylistLoop, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlayNext () private slot
Set current player to play next.
Definition at line 247 of file musicconsoleobject.cpp.
References MusicPlaylist::isEmpty(), m_musicPlayer, m_musicPlaylist, m_volume, MusicPlayer::play(), MusicPlaylist::playbackMode(), MusicPlayer::playNext(), MusicObject::PM_PlayRandom, MusicPlaylist::setCurrentIndex(), and MusicPlayer::setVolume().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlayOneLoop () private slot
Set current play mdoe to single loop.
Definition at line 314 of file musicconsoleobject.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayOneLoop, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlayOrder () private slot
Set current play mdoe to order.
Definition at line 296 of file musicconsoleobject.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayOrder, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlayPrevious () private slot
Set current player to play previous.
Definition at line 227 of file musicconsoleobject.cpp.
References MusicPlaylist::isEmpty(), m_musicPlayer, m_musicPlaylist, m_volume, MusicPlayer::play(), MusicPlaylist::playbackMode(), MusicPlayer::playPrevious(), MusicObject::PM_PlayRandom, MusicPlaylist::setCurrentIndex(), and MusicPlayer::setVolume().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicPlayRandom () private slot
Set current play mdoe to random.
Definition at line 302 of file musicconsoleobject.cpp.
References m_musicPlaylist, m_playbackMode, MusicObject::PM_PlayRandom, and MusicPlaylist::setPlaybackMode().
Referenced by MusicConsoleObject().
void MusicConsoleObject::musicStatePlay () private slot
Set current player to play or not.
Definition at line 209 of file musicconsoleobject.cpp.
References MusicPlaylist::isEmpty(), MusicPlayer::isPlaying(), m_musicPlayer, m_musicPlaylist, m_volume, MusicPlayer::pause(), MusicPlayer::play(), and MusicPlayer::setVolume().
Referenced by MusicConsoleObject().
void MusicConsoleObject::positionChanged (qint64 position) private slot
Current position changed.
Definition at line 198 of file musicconsoleobject.cpp.
References MusicPlayer::duration(), m_musicPlayer, and print().
Referenced by MusicConsoleObject().
void MusicConsoleObject::print (qint64 position, qint64 duration) protected
Print debug info.
Definition at line 356 of file musicconsoleobject.cpp.
References MusicPlaylist::currentMediaPath(), m_enhanced, m_musicPlayer, m_musicPlaylist, m_playbackMode, MusicTime::msecTime2LabelJustified(), TTK_LOGGER_INFO, and MusicPlayer::volume().
Referenced by durationChanged(), and positionChanged().
void MusicConsoleObject::resetVolume () private slot
Reset player volume.
Definition at line 267 of file musicconsoleobject.cpp.
References m_musicPlayer, m_volume, and MusicPlayer::setVolume().
Referenced by currentIndexChanged().
Member Data Documentation
QString MusicConsoleObject::m_enhanced protected
Definition at line 139 of file musicconsoleobject.h.
Referenced by MusicConsoleObject(), musicEnhanced3D(), musicEnhancedNICAM(), musicEnhancedOff(), musicEnhancedSubwoofer(), musicEnhancedVocal(), and print().
MusicPlayer* MusicConsoleObject::m_musicPlayer protected
Definition at line 136 of file musicconsoleobject.h.
Referenced by init(), musicActionVolumePlus(), musicActionVolumeSub(), MusicConsoleObject(), musicEnhanced3D(), musicEnhancedNICAM(), musicEnhancedOff(), musicEnhancedSubwoofer(), musicEnhancedVocal(), musicPlayNext(), musicPlayPrevious(), musicStatePlay(), positionChanged(), print(), resetVolume(), and ~MusicConsoleObject().
MusicPlaylist* MusicConsoleObject::m_musicPlaylist protected
Definition at line 137 of file musicconsoleobject.h.
Referenced by init(), MusicConsoleObject(), musicPlayItemOnce(), musicPlaylistLoop(), musicPlayNext(), musicPlayOneLoop(), musicPlayOrder(), musicPlayPrevious(), musicPlayRandom(), musicStatePlay(), print(), and ~MusicConsoleObject().
QString MusicConsoleObject::m_playbackMode protected
Definition at line 139 of file musicconsoleobject.h.
Referenced by MusicConsoleObject(), musicPlayItemOnce(), musicPlaylistLoop(), musicPlayOneLoop(), musicPlayOrder(), musicPlayRandom(), and print().
int MusicConsoleObject::m_volume protected
Definition at line 138 of file musicconsoleobject.h.
Referenced by init(), musicActionVolumePlus(), musicActionVolumeSub(), MusicConsoleObject(), musicPlayNext(), musicPlayPrevious(), musicStatePlay(), and resetVolume().
The documentation for this class was generated from the following files:
TTKRun/TTKConsole/musicconsoleobject.h
TTKRun/TTKConsole/musicconsoleobject.cpp