TTKMusicPlayer: MusicJSPFConfigManager Class Reference
MusicJSPFConfigManager Class Reference
The class of the jspf playlist config manager.
#include <musicjspfconfigmanager.h>
Public Member Functions
MusicJSPFConfigManager ()
virtual bool readBuffer (MusicSongItemList &items) overridefinal
virtual bool writeBuffer (const MusicSongItemList &items, const QString &path) overridefinal
Public Member Functions inherited from MusicPlaylistRenderer
MusicPlaylistRenderer ()
virtual ~MusicPlaylistRenderer ()
bool fromFile (const QString &name)
bool toFile (const QString &name)
Additional Inherited Members
Protected Attributes inherited from MusicPlaylistRenderer
QFile m_file
Private Member Functions inherited from MusicPlaylistInterface
MusicPlaylistInterface ()
virtual ~MusicPlaylistInterface ()
Detailed Description
The class of the jspf playlist config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicjspfconfigmanager.h.
Constructor & Destructor Documentation
MusicJSPFConfigManager::MusicJSPFConfigManager () explicit
Object contsructor.
Definition at line 6 of file musicjspfconfigmanager.cpp.
Member Function Documentation
bool MusicJSPFConfigManager::readBuffer (MusicSongItemList & items) final override virtual
Read datas from config file.
Implements MusicPlaylistInterface.
Definition at line 13 of file musicjspfconfigmanager.cpp.
References MusicPlaylistRenderer::m_file, MusicSongItem::m_itemName, MusicSongItem::m_songs, and QJson::Parser::parse().
Referenced by MusicPlaylistManager::readJSPFConfig().
bool MusicJSPFConfigManager::writeBuffer (const MusicSongItemList & items, const QString & path) final override virtual
Write datas into config file.
Implements MusicPlaylistInterface.
Definition at line 54 of file musicjspfconfigmanager.cpp.
References MusicPlaylistRenderer::m_file, MusicSongItem::m_songs, QJson::Serializer::serialize(), and MusicPlaylistRenderer::toFile().
Referenced by MusicPlaylistManager::writeJSPFConfig().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musicjspfconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musicjspfconfigmanager.cpp