TTKMusicplayer: MusicLrcSearchWidget Class Reference
MusicLrcSearchWidget Class Reference
The class of the lrc search widget.
#include <musiclrcsearchwidget.h>
Public Slots
void lrcSearchFinished () const
void lrcSearchButtonClicked () const
void lrcSearchDownloadClicked ()
void lrcDownloadStateChanged (const QString &string)
void setCurrentSongName (const QString &name) const
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicLrcSearchWidget (QWidget *parent=nullptr)
~MusicLrcSearchWidget ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicLrcSearchWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the lrc search widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrcsearchwidget.h.
Constructor & Destructor Documentation
MusicLrcSearchWidget::MusicLrcSearchWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musiclrcsearchwidget.cpp.
References lrcDownloadStateChanged(), lrcSearchButtonClicked(), lrcSearchDownloadClicked(), lrcSearchFinished(), m_ui, MusicUIObject::MQSSBackgroundStyle03, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, and setCurrentSongName().
MusicLrcSearchWidget::~MusicLrcSearchWidget ()
Definition at line 48 of file musiclrcsearchwidget.cpp.
References m_ui.
Member Function Documentation
int MusicLrcSearchWidget::exec () virtual slot
Override exec function.
Definition at line 102 of file musiclrcsearchwidget.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicLrcContainer::searchMusicLrcs().
void MusicLrcSearchWidget::lrcDownloadStateChanged (const QString & string) slot
Lrc download state is finished.
Definition at line 94 of file musiclrcsearchwidget.cpp.
References m_ui.
Referenced by MusicLrcSearchWidget().
void MusicLrcSearchWidget::lrcSearchButtonClicked () const slot
Lrc search button clicked.
Definition at line 69 of file musiclrcsearchwidget.cpp.
References MusicUtils::Widget::elidedText(), and m_ui.
Referenced by MusicLrcSearchWidget(), and setCurrentSongName().
void MusicLrcSearchWidget::lrcSearchDownloadClicked () slot
Lrc search download clicked.
Definition at line 77 of file musiclrcsearchwidget.cpp.
References m_ui, and MusicToastLabel::popup().
Referenced by MusicLrcSearchWidget().
void MusicLrcSearchWidget::lrcSearchFinished () const slot
Set lrc search finished.
Definition at line 64 of file musiclrcsearchwidget.cpp.
References m_ui.
Referenced by MusicLrcSearchWidget(), and setCurrentSongName().
void MusicLrcSearchWidget::setCurrentSongName (const QString & name) const slot
Set current song name.
Definition at line 53 of file musiclrcsearchwidget.cpp.
References lrcSearchButtonClicked(), lrcSearchFinished(), and m_ui.
Referenced by MusicLrcSearchWidget(), and MusicLrcContainer::searchMusicLrcs().
Member Data Documentation
Ui::MusicLrcSearchWidget* MusicLrcSearchWidget::m_ui protected
Definition at line 69 of file musiclrcsearchwidget.h.
Referenced by exec(), lrcDownloadStateChanged(), lrcSearchButtonClicked(), lrcSearchDownloadClicked(), lrcSearchFinished(), MusicLrcSearchWidget(), setCurrentSongName(), and ~MusicLrcSearchWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcsearchwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcsearchwidget.cpp