TTKMusicplayer: TTKRunObject Class Reference
TTKRunObject Class Reference
The class of the ttk run object.
#include <ttkrunobject.h>
Public Member Functions
TTKRunObject (QObject *parent=nullptr)
void valid () const
void run (int argc, char **argv) const
Private Slots
void finished (int code)
Detailed Description
The class of the ttk run object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttkrunobject.h.
Constructor & Destructor Documentation
TTKRunObject::TTKRunObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 32 of file ttkrunobject.cpp.
References finished(), TTK_D, and TTK_INIT_PRIVATE.
Member Function Documentation
void TTKRunObject::finished (int code) private slot
Run finished.
Definition at line 62 of file ttkrunobject.cpp.
References TTK_LOGGER_INFO.
Referenced by TTKRunObject().
void TTKRunObject::run (int argc, char ** argv) const
To run main window.
Definition at line 48 of file ttkrunobject.cpp.
References APP_NAME, and TTK_D.
void TTKRunObject::valid () const
Check current setting file's validation.
Definition at line 42 of file ttkrunobject.cpp.
References MusicConfigObject::valid().
Referenced by main().
The documentation for this class was generated from the following files:
TTKRun/TTKApp/ttkrunobject.h
TTKRun/TTKApp/ttkrunobject.cpp