TTKMusicplayer: MusicQQQueryInterface Class Reference
MusicQQQueryInterface Class Reference
The class of qq query interface.
#include <musicqqqueryinterface.h>
Public Member Functions
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key)
QString generateMusicPath (const QString &file, const QString &mid)
Detailed Description
The class of qq query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 74 of file musicqqqueryinterface.h.
Member Function Documentation
QString MusicQQQueryInterface::generateMusicPath (const QString & file, const QString & mid)
Get music key.
Definition at line 185 of file musicqqqueryinterface.cpp.
References MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), QQ_SONG_KEY_URL, REFER_URL, and MusicObject::syncNetworkQueryForGet().
Referenced by readFromMusicSongAttribute(), and readFromMusicSongAttributeNew().
void MusicQQQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate)
Read tags(size) from query results.
Definition at line 14 of file musicqqqueryinterface.cpp.
References APE_FILE, APE_FILE_PREFIX, FLAC_FILE, FLAC_FILE_PREFIX, generateMusicPath(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_320, MB_750, MP3_FILE, MP3_FILE_PREFIX, and MusicUtils::Number::sizeByte2Label().
Referenced by MusicQQQueryToplistRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicQQQueryPlaylistRequest::queryDetailsFinished(), and readFromMusicSongAttribute().
void MusicQQQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 79 of file musicqqqueryinterface.cpp.
References MB_1000, MB_128, MB_192, MB_320, MB_750, and readFromMusicSongAttribute().
Referenced by readFromMusicSongAttribute().
void MusicQQQueryInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate)
Read tags(size) from query results.
Definition at line 111 of file musicqqqueryinterface.cpp.
References APE_FILE, APE_FILE_PREFIX, FLAC_FILE, FLAC_FILE_PREFIX, generateMusicPath(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_320, MB_750, MP3_FILE, MP3_FILE_PREFIX, and MusicUtils::Number::sizeByte2Label().
Referenced by MusicQQQueryRecommendRequest::downLoadFinished(), readFromMusicSongAttributeNew(), and MusicQQQueryRequest::singleDownLoadFinished().
void MusicQQQueryInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, const QVariantMap & key)
Read tags(size) from query results.
Definition at line 176 of file musicqqqueryinterface.cpp.
References MB_1000, MB_128, MB_192, MB_320, MB_750, and readFromMusicSongAttributeNew().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqqueryinterface.cpp