TTKMusicplayer: MusicTime Class Reference
MusicTime Class Reference
The class of the music time object.
#include <musictime.h>
Public Types
enum Type { All_Msec, All_Sec }
Public Member Functions
MusicTime ()
MusicTime (const MusicTime &other)
MusicTime (qint64 value, Type type)
MusicTime (int day, int hour, int min, int sec, int msec)
void setHMSM (int day, int hour, int min, int sec, int msec=0)
bool isNull () const
bool isValid () const
void setType (Type type)
Type getType () const
void setGreedy (bool mode)
bool getGreedy () const
void setDay (int day)
void setHour (int hour)
void setMinute (int min)
void setSecond (int sec)
void setMillionSecond (int msec)
int getDay () const
int getHour () const
int getMinute () const
int getSecond () const
int getMillionSecond () const
QString toString (const QString &format) const
qint64 getTimestamp (Type type) const
QString msecTime2LabelJustified ()
QString normalTime2Label () const
MusicTime & operator= (const MusicTime &other)
MusicTime & operator+= (const MusicTime &other)
MusicTime & operator+= (const int other)
MusicTime & operator-= (const MusicTime &other)
MusicTime & operator-= (const int other)
MusicTime & operator*= (const int other)
MusicTime & operator/= (const int other)
MusicTime operator+ (const MusicTime &other)
MusicTime operator+ (const int other)
MusicTime operator- (const MusicTime &other)
MusicTime operator- (const int other)
MusicTime operator* (const int other)
MusicTime operator/ (const int other)
bool operator== (const MusicTime &other) const
bool operator!= (const MusicTime &other) const
Static Public Member Functions
static MusicTime fromString (const QString &s, const QString &format)
static QString toString (qint64 value, Type type, const QString &format)
static qint64 timestamp (bool ms=true)
static void initRandom ()
static int random (int value=RAND_MAX)
static qint64 labelJustified2MsecTime (const QString &time)
static QString msecTime2LabelJustified (qint64 time, bool greedy=true)
static QString normalTime2Label (qint64 time)
Protected Member Functions
void initialize ()
void copyToThis (const MusicTime &other)
void fromTimeStamp (qint64 value, int delta)
Protected Attributes
bool m_greedyMode
Type m_defaultType
int m_day
int m_hour
int m_min
int m_sec
int m_msec
Friends
QDataStream & operator<< (QDataStream &stream, const MusicTime &other)
QDataStream & operator>> (QDataStream &stream, MusicTime &other)
Detailed Description
The class of the music time object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musictime.h.
Member Enumeration Documentation
enum MusicTime::Type
Enumerator
All_Msec
Current time entity is msec
All_Sec
Current time entity is sec
Definition at line 32 of file musictime.h.
Constructor & Destructor Documentation
MusicTime::MusicTime ()
Object contsructor.
Definition at line 7 of file musictime.cpp.
References All_Msec, initialize(), m_defaultType, and m_greedyMode.
Referenced by operator*(), operator+(), operator-(), operator/(), and toString().
MusicTime::MusicTime (const MusicTime & other)
Object contsructor.
Definition at line 14 of file musictime.cpp.
References copyToThis().
MusicTime::MusicTime (qint64 value, Type type)
Object contsructor by value and type.
Definition at line 19 of file musictime.cpp.
References All_Sec, fromTimeStamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime::MusicTime (int day, int hour, int min, int sec, int msec)
Object contsructor by day and hour and min and sec and msec.
Definition at line 26 of file musictime.cpp.
References All_Msec, m_defaultType, and setHMSM().
Member Function Documentation
void MusicTime::copyToThis (const MusicTime & other) protected
Copy other time data to this obejct;
Definition at line 287 of file musictime.cpp.
References getDay(), getGreedy(), getHour(), getMillionSecond(), getMinute(), getSecond(), getType(), m_day, m_defaultType, m_greedyMode, m_hour, m_min, m_msec, and m_sec.
Referenced by MusicTime(), and operator=().
MusicTime MusicTime::fromString (const QString & s, const QString & format) static
Transform time from string by time format.
Definition at line 66 of file musictime.cpp.
References setHMSM().
Referenced by labelJustified2MsecTime().
void MusicTime::fromTimeStamp (qint64 value, int delta) protected
Transform time value by different time type;
Definition at line 298 of file musictime.cpp.
References initialize(), m_day, m_hour, m_min, m_msec, m_sec, MT_D2S, MT_H2S, MT_M2S, and MT_S2MS.
Referenced by MusicTime(), operator*=(), operator+=(), operator-=(), and operator/=().
int MusicTime::getDay () const inline
Get current day.
Definition at line 109 of file musictime.h.
Referenced by copyToThis(), and msecTime2LabelJustified().
bool MusicTime::getGreedy () const inline
Get current greedy mode.
Definition at line 84 of file musictime.h.
Referenced by copyToThis().
int MusicTime::getHour () const inline
Get current hour.
Definition at line 113 of file musictime.h.
Referenced by copyToThis(), and msecTime2LabelJustified().
int MusicTime::getMillionSecond () const inline
Get current millionSecond.
Definition at line 125 of file musictime.h.
Referenced by copyToThis(), and MusicLrcMakerWidget::translateTimeString().
int MusicTime::getMinute () const inline
Get current second.
Definition at line 117 of file musictime.h.
Referenced by copyToThis(), and msecTime2LabelJustified().
int MusicTime::getSecond () const inline
Get current second.
Definition at line 121 of file musictime.h.
Referenced by copyToThis(), and msecTime2LabelJustified().
qint64 MusicTime::getTimestamp (Type type) const
Get all time value by type.
Definition at line 84 of file musictime.cpp.
References All_Sec, m_day, m_hour, m_min, m_msec, m_sec, MT_D2S, MT_H2S, MT_M2S, MT_S, and MT_S2MS.
Referenced by labelJustified2MsecTime(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and operator==().
Type MusicTime::getType () const inline
Get current time type, see Type.
Definition at line 75 of file musictime.h.
Referenced by copyToThis().
void MusicTime::initialize () protected
Init parameters;
Definition at line 278 of file musictime.cpp.
References m_day, m_hour, m_min, m_msec, and m_sec.
Referenced by fromTimeStamp(), MusicTime(), and setHMSM().
void MusicTime::initRandom () static
Init random value seed.
Definition at line 97 of file musictime.cpp.
References Random::initRandom().
Referenced by MusicBarrageWidget::addBarrage(), MusicBarrageWidget::createLabel(), MusicCodeAreaWidget::MusicCodeAreaWidget(), MusicDesktopWallpaperThread::MusicDesktopWallpaperThread(), MusicDiscoverListRequest::MusicDiscoverListRequest(), MusicNetworkTestThread::MusicNetworkTestThread(), MusicPlaylist::MusicPlaylist(), MusicTransitionAnimationLabel::MusicTransitionAnimationLabel(), MusicUserDialog::MusicUserDialog(), and MusicVideoSearchTableWidget::MusicVideoSearchTableWidget().
bool MusicTime::isNull () const
Check current time is null.
Definition at line 56 of file musictime.cpp.
References m_hour, m_min, m_msec, and m_sec.
Referenced by isValid().
bool MusicTime::isValid () const
Check current time is valid.
Definition at line 61 of file musictime.cpp.
References isNull().
qint64 MusicTime::labelJustified2MsecTime (const QString & time) static
Transform string format(mm:ss) to msec time.
Definition at line 107 of file musictime.cpp.
References All_Msec, fromString(), and getTimestamp().
Referenced by MusicM3UConfigManager::writePlaylistData().
QString MusicTime::msecTime2LabelJustified ()
Transform msec time to string format(mm:ss).
Definition at line 113 of file musictime.cpp.
References m_day, m_greedyMode, m_hour, m_min, m_sec, MT_H, MT_H2S, and toString().
Referenced by MusicMVRadioProgramRequest::downLoadFinished(), MusicBDQueryRecommendRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicQQQueryRecommendRequest::downLoadFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicWYQueryRecommendRequest::downLoadFinished(), MusicXMQueryArtistRequest::downLoadFinished(), MusicBDQueryArtistRequest::downLoadFinished(), MusicKWQueryRecommendRequest::downLoadFinished(), MusicXMQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicQQQueryToplistRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicXMQueryToplistRequest::downLoadFinished(), MusicBDQueryToplistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicXMQueryAlbumRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicBDQueryAlbumRequest::downLoadFinished(), MusicQQQueryAlbumRequest::downLoadFinished(), MusicKWQueryMovieRequest::downLoadFinished(), MusicKGQueryMovieRequest::downLoadFinished(), MusicQQQueryMovieRequest::downLoadFinished(), MusicQQQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicXMQueryMovieRequest::downLoadFinished(), MusicXMQueryRequest::downLoadFinished(), MusicQQQueryArtistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), MusicVideoControlWidget::durationChanged(), MusicSoundKMicroWidget::durationChanged(), MusicWebFMRadioPlayWidget::durationChanged(), MusicApplication::durationChanged(), MusicQQQueryPlaylistRequest::getDetailsFinished(), MusicKGQueryPlaylistRequest::getDetailsFinished(), MusicWYQueryPlaylistRequest::getDetailsFinished(), MusicXMQueryPlaylistRequest::getDetailsFinished(), MusicKWQueryPlaylistRequest::getDetailsFinished(), MusicDJRadioProgramCategoryRequest::getDetailsFinished(), MusicSongTag::getLengthString(), MusicLrcAnalysis::getTranslatedLrc(), MusicMovingLabelSlider::mouseMoveEvent(), MusicLrcContainerForInterior::paintEvent(), MusicSoundKMicroWidget::positionChanged(), MusicWebFMRadioPlayWidget::positionChanged(), MusicLrcMakerWidget::positionChanged(), MusicApplication::positionChanged(), MusicConsoleObject::print(), MusicBDQueryInterface::readFromMusicLLAttribute(), MusicMVRadioProgramRequest::readFromMusicMVAttribute(), MusicQQQueryMovieRequest::readFromMusicMVAttribute(), MusicXMQueryMovieRequest::readFromMusicMVAttribute(), MusicKGQueryMovieRequest::readFromMusicMVAttribute(), MusicBDQueryMovieRequest::readFromMusicMVAttributeIQY(), MusicBDQueryMovieRequest::readFromMusicMVAttributeWeb(), MusicBDQueryInterface::readFromMusicSongAttribute(), MusicKWQueryInterface::readFromMusicSongPic(), MusicKGLConfigManager::readPlaylistData(), MusicPLSConfigManager::readPlaylistData(), MusicM3UConfigManager::readPlaylistData(), MusicFPLConfigManager::readPlaylistData(), MusicVideoControlWidget::setValue(), MusicXMQueryRequest::singleDownLoadFinished(), MusicKGQueryRequest::singleDownLoadFinished(), MusicQQQueryRequest::singleDownLoadFinished(), MusicWYQueryRequest::singleDownLoadFinished(), and MusicWYQueryMovieRequest::startMVListQuery().
QString MusicTime::msecTime2LabelJustified (qint64 time, bool greedy = true) static
Transform msec time to string format(mm:ss).
Definition at line 126 of file musictime.cpp.
References All_Msec, getDay(), getHour(), getMinute(), getSecond(), MT_H, MT_H2S, MT_S2MS, and toString().
QString MusicTime::normalTime2Label () const
Transform msec time to string format(/ ss / mm / hh / dd).
Definition at line 140 of file musictime.cpp.
References m_day, m_hour, m_min, and m_sec.
Referenced by MusicSourceUpdateWidget::downloadSpeedLabelChanged(), and MusicLocalSongSearchPopWidget::utcTimeToLocal().
QString MusicTime::normalTime2Label (qint64 time) static
Transform msec time to string format(/ ss / mm / hh / dd).
Definition at line 164 of file musictime.cpp.
References MT_D2S, MT_H2S, and MT_M2S.
bool MusicTime::operator!= (const MusicTime & other) const
Definition at line 273 of file musictime.cpp.
References All_Msec, and getTimestamp().
MusicTime MusicTime::operator* (const int other)
Definition at line 256 of file musictime.cpp.
References All_Msec, getTimestamp(), m_defaultType, and MusicTime().
MusicTime & MusicTime::operator*= (const int other)
Definition at line 218 of file musictime.cpp.
References All_Msec, All_Sec, fromTimeStamp(), getTimestamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime MusicTime::operator+ (const MusicTime & other)
Definition at line 232 of file musictime.cpp.
References All_Msec, getTimestamp(), m_defaultType, and MusicTime().
MusicTime MusicTime::operator+ (const int other)
Definition at line 238 of file musictime.cpp.
References All_Msec, getTimestamp(), m_defaultType, and MusicTime().
MusicTime & MusicTime::operator+= (const MusicTime & other)
Definition at line 190 of file musictime.cpp.
References All_Msec, All_Sec, fromTimeStamp(), getTimestamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime & MusicTime::operator+= (const int other)
Definition at line 197 of file musictime.cpp.
References All_Msec, All_Sec, fromTimeStamp(), getTimestamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime MusicTime::operator- (const MusicTime & other)
Definition at line 244 of file musictime.cpp.
References All_Msec, getTimestamp(), m_defaultType, and MusicTime().
MusicTime MusicTime::operator- (const int other)
Definition at line 250 of file musictime.cpp.
References All_Msec, getTimestamp(), m_defaultType, and MusicTime().
MusicTime & MusicTime::operator-= (const MusicTime & other)
Definition at line 204 of file musictime.cpp.
References All_Msec, All_Sec, fromTimeStamp(), getTimestamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime & MusicTime::operator-= (const int other)
Definition at line 211 of file musictime.cpp.
References All_Msec, All_Sec, fromTimeStamp(), getTimestamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime MusicTime::operator/ (const int other)
Definition at line 262 of file musictime.cpp.
References All_Msec, getTimestamp(), m_defaultType, and MusicTime().
MusicTime & MusicTime::operator/= (const int other)
Definition at line 225 of file musictime.cpp.
References All_Msec, All_Sec, fromTimeStamp(), getTimestamp(), m_defaultType, MT_S, and MT_S2MS.
MusicTime & MusicTime::operator= (const MusicTime & other)
Definition at line 184 of file musictime.cpp.
References copyToThis().
bool MusicTime::operator== (const MusicTime & other) const
Definition at line 268 of file musictime.cpp.
References All_Msec, and getTimestamp().
int MusicTime::random (int value = RAND_MAX) static
Get random value.
Definition at line 102 of file musictime.cpp.
References Random::random().
Referenced by MusicBarrageAnimation::animationFinished(), MusicScreenSaverBackgroundWidget::backgroundTimeout(), MusicQQDiscoverListRequest::downLoadFinished(), MusicBDDiscoverListRequest::downLoadFinished(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicXMDiscoverListRequest::downLoadFinished(), MusicCodeAreaWidget::drawConversion(), MusicCodeAreaWidget::drawNoisyPoint(), MusicBarrageAnimation::initialize(), MusicCodeAreaWidget::paintEvent(), MusicItemSearchTableWidget::randToGetStrength(), MusicCodeAreaWidget::renderPicture(), MusicNetworkTestThread::run(), MusicTransitionAnimationLabel::setPixmap(), MusicBarrageAnimation::setSize(), and MusicDesktopWallpaperThread::timeout().
void MusicTime::setDay (int day) inline
Set current day.
Definition at line 89 of file musictime.h.
void MusicTime::setGreedy (bool mode) inline
Set current greedy mode.
Definition at line 80 of file musictime.h.
void MusicTime::setHMSM (int day, int hour, int min, int sec, int msec = 0)
Set current day and hour and min and sec and msec.
Definition at line 33 of file musictime.cpp.
References initialize(), m_day, m_hour, m_min, m_msec, m_sec, MT_D2H, MT_H2M, MT_M2S, and MT_S2MS.
Referenced by fromString(), and MusicTime().
void MusicTime::setHour (int hour) inline
Set current hour.
Definition at line 93 of file musictime.h.
void MusicTime::setMillionSecond (int msec) inline
Set current millionSecond.
Definition at line 105 of file musictime.h.
void MusicTime::setMinute (int min) inline
Set current minute.
Definition at line 97 of file musictime.h.
void MusicTime::setSecond (int sec) inline
Set current second.
Definition at line 101 of file musictime.h.
void MusicTime::setType (Type type) inline
Set current time type, see Type.
Definition at line 71 of file musictime.h.
qint64 MusicTime::timestamp (bool ms = true) static
Transform ms time from utc since epoch.
Definition at line 91 of file musictime.cpp.
Referenced by MusicBDQueryInterface::makeTokenQueryUrl(), MusicXMQueryInterface::makeTokenQueryUrl(), MusicBDQueryMovieRequest::readFromMusicMVAttributeIQY(), MusicBDQueryLearnRequest::readFromMusicSongAttribute(), MusicCloudManagerTableWidget::receiveDataFinshed(), MusicDownloadDataRequest::startRequest(), MusicSongSearchTableWidget::startSearchQuery(), MusicCloudManagerTableWidget::uploadFileDirToServer(), MusicCloudManagerTableWidget::uploadFilesToServer(), and MusicLocalSongSearchPopWidget::utcTimeToLocal().
QString MusicTime::toString (qint64 value, Type type, const QString & format) static
Transform time from value to string time format.
Definition at line 74 of file musictime.cpp.
References MusicTime().
Referenced by msecTime2LabelJustified(), MusicSongRingtoneMaker::posChanged(), MusicLrcAnalysis::saveLrcTimeChanged(), and MusicLrcMakerWidget::translateTimeString().
QString MusicTime::toString (const QString & format) const
Transform time to string time format.
Definition at line 79 of file musictime.cpp.
References m_hour, m_min, m_msec, and m_sec.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream & stream, const MusicTime & other) friend
Definition at line 211 of file musictime.h.
QDataStream& operator>> (QDataStream & stream, MusicTime & other) friend
Definition at line 218 of file musictime.h.
Member Data Documentation
int MusicTime::m_day protected
Definition at line 242 of file musictime.h.
Referenced by copyToThis(), fromTimeStamp(), getTimestamp(), initialize(), msecTime2LabelJustified(), normalTime2Label(), and setHMSM().
Type MusicTime::m_defaultType protected
Definition at line 241 of file musictime.h.
Referenced by copyToThis(), MusicTime(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), and operator/=().
bool MusicTime::m_greedyMode protected
Definition at line 240 of file musictime.h.
Referenced by copyToThis(), msecTime2LabelJustified(), and MusicTime().
int MusicTime::m_hour protected
Definition at line 242 of file musictime.h.
Referenced by copyToThis(), fromTimeStamp(), getTimestamp(), initialize(), isNull(), msecTime2LabelJustified(), normalTime2Label(), setHMSM(), and toString().
int MusicTime::m_min protected
Definition at line 243 of file musictime.h.
Referenced by copyToThis(), fromTimeStamp(), getTimestamp(), initialize(), isNull(), msecTime2LabelJustified(), normalTime2Label(), setHMSM(), and toString().
int MusicTime::m_msec protected
Definition at line 243 of file musictime.h.
Referenced by copyToThis(), fromTimeStamp(), getTimestamp(), initialize(), isNull(), setHMSM(), and toString().
int MusicTime::m_sec protected
Definition at line 243 of file musictime.h.
Referenced by copyToThis(), fromTimeStamp(), getTimestamp(), initialize(), isNull(), msecTime2LabelJustified(), normalTime2Label(), setHMSM(), and toString().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musictime.h
TTKModule/TTKCore/musicCoreKits/musictime.cpp