TTKMusicPlayer: ReqKWInterface Namespace Reference
ReqKWInterface Namespace Reference
The namespace of the kuwo request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request) noexcept
QString makeSongArtist (const QString &name)
QString makeSongArtist (const QString &in, const QString &name)
QString makeArtistPixmapUrl (const QString &url)
QString makeCoverPixmapUrl (const QString &url, const QString &id)
void parseFromSongProperty (TTK::MusicSongInformation *info, int bitrate)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QString &format)
static void parseFromMovieInfo (TTK::MusicSongInformation *info)
static void parseFromMovieProperty (TTK::MusicSongInformation *info, const QString &format)
static void parseFromMovieProperty (TTK::MusicSongInformation *info, const QString &format, int bitrate)
Detailed Description
The namespace of the kuwo request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
QString ReqKWInterface::makeArtistPixmapUrl (const QString & url)
Make artist pixmap url.
Definition at line 31 of file musickwqueryinterface.cpp.
References KW_ARTIST_COVER_URL, and TTK::Algorithm::mdII().
Referenced by MusicKWQueryHotArtistListRequest::downloadFinished().
QString ReqKWInterface::makeCoverPixmapUrl (const QString & url, const QString & id)
Make cover pixmap url.
Definition at line 36 of file musickwqueryinterface.cpp.
References TTK::String::isNetworkUrl(), KW_ALBUM_COVER_INFO_URL, KW_ALBUM_COVER_URL, and TTK::Algorithm::mdII().
Referenced by MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), and MusicKWQueryArtistAlbumRequest::downloadFinished().
void ReqKWInterface::makeRequestRawHeader (QNetworkRequest * request) noexcept
Make request query data.
Definition at line 13 of file musickwqueryinterface.cpp.
References TTK::setContentTypeHeader(), TTK::setSslConfiguration(), and TTK::setUserAgentHeader().
Referenced by MusicKWQueryPlaylistRequest::morePlaylistDetails(), parseFromMovieInfo(), parseFromMovieProperty(), parseSongPropertyV1(), parseSongPropertyV2(), parseSongPropertyV3(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicKWQueryToplistRequest::queryToplistInfo(), MusicKWSongCommentsRequest::startToPage(), MusicKWQueryArtistRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicKWQueryToplistRequest::startToPage(), MusicKWQueryAlbumRequest::startToPage(), MusicKWQuerySongRequest::startToPage(), MusicKWQueryHotArtistListRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKWQueryArtistAlbumRequest::startToPage(), MusicKWQueryArtistMovieRequest::startToPage(), MusicKWQueryNewSongRequest::startToPage(), MusicKWQueryNewAlbumRequest::startToPage(), MusicKWQueryPlaylistRecommendRequest::startToPage(), MusicKWQueryPlaylistHighRequest::startToPage(), MusicKWQueryPlaylistRequest::startToQueryInfo(), MusicKWDownloadCoverRequest::startToRequest(), MusicKWDiscoverListRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), and MusicKWQuerySongRequest::startToSearchByID().
QString ReqKWInterface::makeSongArtist (const QString & name)
Make song artist name.
Definition at line 20 of file musickwqueryinterface.cpp.
References TTK::String::charactersReplace().
Referenced by MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKWQueryMovieRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), and parseFromMovieInfo().
QString ReqKWInterface::makeSongArtist (const QString & in, const QString & name)
Make song artist name.
Definition at line 25 of file musickwqueryinterface.cpp.
References TTK::String::charactersReplace().
void ReqKWInterface::parseFromMovieInfo (TTK::MusicSongInformation * info) static
Read mv info property from query results.
Definition at line 27 of file musickwquerymovierequest.cpp.
References TTK::String::charactersReplace(), QJsonParseError::error, TTKTime::formatDuration(), QJsonDocument::fromJson(), KW_SONG_INFO_URL, TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_coverUrl, TTK::MusicSongInformation::m_duration, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songName, makeRequestRawHeader(), makeSongArtist(), TTK::Algorithm::mdII(), QJsonParseError::NoError, TTK::syncNetworkQueryForGet(), TTK::toString(), QJsonDocument::toVariant(), and TTK_DN_S2MS.
Referenced by MusicKWQueryMovieRequest::downloadSingleFinished().
void ReqKWInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, const QString & format) static
Read mv tags(size and bitrate and url) from query results.
Definition at line 63 of file musickwquerymovierequest.cpp.
References TTK::MusicSongInformation::m_songId, parseFromMovieProperty(), TTK_BN_1000, TTK_BN_250, TTK_BN_500, and TTK_BN_750.
Referenced by MusicKWQueryMovieRequest::downloadFinished(), and MusicKWQueryMovieRequest::downloadSingleFinished().
void ReqKWInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, const QString & format, int bitrate) static
Read mv tags(size and bitrate and url) from query results.
Definition at line 91 of file musickwquerymovierequest.cpp.
References TTKRegularExpression::captured(), QAlgorithm::Des::encrypt(), TTK::MusicSongProperty::isEmpty(), KW_MOVIE_ATTR_URL, KW_MOVIE_URL, TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, makeRequestRawHeader(), TTKRegularExpression::match(), TTK::Algorithm::mdII(), MDII_SHR_KEY, MP4_FILE_SUFFIX, TTK::syncNetworkQueryForGet(), and TTK_DEFAULT_STR.
Referenced by parseFromMovieProperty().
void ReqKWInterface::parseFromSongProperty (TTK::MusicSongInformation * info, int bitrate)
Read tags(size and bitrate and url) from query results.
Definition at line 298 of file musickwqueryinterface.cpp.
References FLAC_FILE_SUFFIX, TTK::MusicSongInformation::m_formatProps, TTK::MusicSongInformation::m_songId, MP3_FILE_SUFFIX, parseSongProperty(), TTK_BN_0, TTK_BN_1000, TTK_BN_128, TTK_BN_192, and TTK_BN_320.
Referenced by MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryArtistRequest::downloadFinished(), MusicKWQueryAlbumRequest::downloadFinished(), MusicKWQuerySongRequest::downloadFinished(), MusicKWQueryToplistRequest::downloadFinished(), MusicKWQueryNewSongRequest::downloadFinished(), MusicKWQuerySongRequest::downloadSingleFinished(), MusicKWQueryAlbumRequest::startToQueryResult(), MusicKWQueryArtistRequest::startToQueryResult(), MusicKWQuerySongRequest::startToQueryResult(), MusicKWQueryToplistRequest::startToQueryResult(), MusicKWQueryPlaylistRequest::startToQueryResult(), and MusicKWQueryNewSongRequest::startToQueryResult().
void ReqKWInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QString & format)
Read tags(size and bitrate and url) from query results.
Definition at line 324 of file musickwqueryinterface.cpp.
References TTK::MusicSongInformation::m_formatProps.