TTKMusicplayer: MusicSongItemSelectedAreaWidget Class Reference
MusicSongItemSelectedAreaWidget Class Reference
The class of the song item selected area widget.
#include <musicsongitemselectedareawidget.h>
Public Slots
void modifiedItemButtonClicked ()
void itemListChanged (const TTKIntList &items)
Signals
void queryMusicItemList (MusicSongItems &songs)
void confirmChanged ()
Public Member Functions
MusicSongItemSelectedAreaWidget (QWidget *parent=nullptr)
~MusicSongItemSelectedAreaWidget ()
MusicSongs selectedSongItems ()
Protected Attributes
bool m_selected
TTKIntList m_selectedItems
QLabel * m_label
QLabel * m_itemLabel
MusicClickedLabel * m_modifiedItemButton
Detailed Description
The class of the song item selected area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 106 of file musicsongitemselectedareawidget.h.
Constructor & Destructor Documentation
MusicSongItemSelectedAreaWidget::MusicSongItemSelectedAreaWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 136 of file musicsongitemselectedareawidget.cpp.
References G_CONNECTION_PTR, m_itemLabel, m_label, m_modifiedItemButton, m_selected, modifiedItemButtonClicked(), MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSColorStyle08, MusicUIObject::MQSSColorStyle10, and MusicUIObject::MQSSFontStyle01.
MusicSongItemSelectedAreaWidget::~MusicSongItemSelectedAreaWidget ()
Definition at line 165 of file musicsongitemselectedareawidget.cpp.
References G_CONNECTION_PTR, m_itemLabel, m_label, and m_modifiedItemButton.
Member Function Documentation
void MusicSongItemSelectedAreaWidget::confirmChanged () signal
Confirm changed.
Referenced by modifiedItemButtonClicked().
void MusicSongItemSelectedAreaWidget::itemListChanged (const TTKIntList & items) slot
Item list changed.
Definition at line 214 of file musicsongitemselectedareawidget.cpp.
References m_itemLabel, and m_selectedItems.
Referenced by modifiedItemButtonClicked().
void MusicSongItemSelectedAreaWidget::modifiedItemButtonClicked () slot
Modified item button clicked.
Definition at line 199 of file musicsongitemselectedareawidget.cpp.
References confirmChanged(), MusicSongItemSelectedDialog::createAllItems(), MusicSongItemSelectedDialog::exec(), itemListChanged(), m_selected, and queryMusicItemList().
Referenced by MusicSongItemSelectedAreaWidget().
void MusicSongItemSelectedAreaWidget::queryMusicItemList (MusicSongItems & songs) signal
Query music datas from container.
Referenced by modifiedItemButtonClicked(), and selectedSongItems().
MusicSongs MusicSongItemSelectedAreaWidget::selectedSongItems ()
Get selected song items.
Definition at line 173 of file musicsongitemselectedareawidget.cpp.
References m_selected, m_selectedItems, MusicObject::playlistRowValid(), and queryMusicItemList().
Member Data Documentation
QLabel * MusicSongItemSelectedAreaWidget::m_itemLabel protected
Definition at line 146 of file musicsongitemselectedareawidget.h.
Referenced by itemListChanged(), MusicSongItemSelectedAreaWidget(), and ~MusicSongItemSelectedAreaWidget().
QLabel* MusicSongItemSelectedAreaWidget::m_label protected
Definition at line 146 of file musicsongitemselectedareawidget.h.
Referenced by MusicSongItemSelectedAreaWidget(), and ~MusicSongItemSelectedAreaWidget().
MusicClickedLabel* MusicSongItemSelectedAreaWidget::m_modifiedItemButton protected
Definition at line 147 of file musicsongitemselectedareawidget.h.
Referenced by MusicSongItemSelectedAreaWidget(), and ~MusicSongItemSelectedAreaWidget().
bool MusicSongItemSelectedAreaWidget::m_selected protected
Definition at line 143 of file musicsongitemselectedareawidget.h.
Referenced by modifiedItemButtonClicked(), MusicSongItemSelectedAreaWidget(), and selectedSongItems().
TTKIntList MusicSongItemSelectedAreaWidget::m_selectedItems protected
Definition at line 144 of file musicsongitemselectedareawidget.h.
Referenced by itemListChanged(), and selectedSongItems().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicsongitemselectedareawidget.h
TTKModule/TTKWidget/musicCoreKits/musicsongitemselectedareawidget.cpp