TTKMusicplayer: MusicSourceUpdateWidget Class Reference
MusicSourceUpdateWidget Class Reference
The class of the application upgrade widget.
#include <musicsourceupdatewidget.h>
Public Slots
void upgradeButtonClicked ()
void downLoadFinished (const QVariant &bytes)
void downloadSpeedLabelChanged (const QString &speed, qint64 timeLeft)
void downloadProgressChanged (float percent, const QString &total)
void downloadProgressFinished ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicSourceUpdateWidget (QWidget *parent=nullptr)
~MusicSourceUpdateWidget ()
void start ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicSourceUpdateWidget * m_ui
QString m_newVersionStr
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the application upgrade widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 70 of file musicsourceupdatewidget.h.
Constructor & Destructor Documentation
MusicSourceUpdateWidget::MusicSourceUpdateWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 99 of file musicsourceupdatewidget.cpp.
References m_ui, MusicUIObject::MQSSProgressBar01, MusicUIObject::MQSSPushButtonStyle03, MusicUIObject::MQSSToolButtonStyle04, and upgradeButtonClicked().
MusicSourceUpdateWidget::~MusicSourceUpdateWidget ()
Definition at line 123 of file musicsourceupdatewidget.cpp.
References m_ui.
Member Function Documentation
void MusicSourceUpdateWidget::downLoadFinished (const QVariant & bytes) slot
Download data from kuwo net finished.
Definition at line 151 of file musicsourceupdatewidget.cpp.
References MusicUtils::Core::appVersionCheck(), m_newVersionStr, m_ui, and TTKMUSIC_VERSION_STR.
Referenced by start().
void MusicSourceUpdateWidget::downloadProgressChanged (float percent, const QString & total) slot
Update download percent\ total size progress.
Definition at line 181 of file musicsourceupdatewidget.cpp.
References m_ui.
Referenced by upgradeButtonClicked().
void MusicSourceUpdateWidget::downloadProgressFinished () slot
Update download progress finished.
Definition at line 187 of file musicsourceupdatewidget.cpp.
References EXE_FILE, MusicMessageBox::exec(), m_newVersionStr, MusicUtils::Url::openUrl(), MusicMessageBox::setText(), TTKStatic_cast, and UPDATE_DIR_FULL.
Referenced by upgradeButtonClicked().
void MusicSourceUpdateWidget::downloadSpeedLabelChanged (const QString & speed, qint64 timeLeft) slot
Update download speed label.
Definition at line 175 of file musicsourceupdatewidget.cpp.
References m_ui, and MusicTime::normalTime2Label().
Referenced by upgradeButtonClicked().
int MusicSourceUpdateWidget::exec () virtual slot
Override exec function.
Definition at line 200 of file musicsourceupdatewidget.cpp.
References start().
Referenced by MusicApplicationModule::musicVersionUpdate(), MusicSettingWidget::rippleVersionUpdateChanged(), and MusicSourceUpdateNotifyWidget::updateSourceClicked().
void MusicSourceUpdateWidget::start ()
Start update.
Definition at line 128 of file musicsourceupdatewidget.cpp.
References downLoadFinished(), and MusicSourceUpdateRequest::startToDownload().
Referenced by exec().
void MusicSourceUpdateWidget::upgradeButtonClicked () slot
Upgrade button clicked.
Definition at line 135 of file musicsourceupdatewidget.cpp.
References MusicObject::DownloadOther, downloadProgressChanged(), downloadProgressFinished(), downloadSpeedLabelChanged(), EXE_FILE, QSyncUtils::generateDataBucketUrl(), m_newVersionStr, m_ui, MusicToastLabel::popup(), SOURCE_UPDATE_INDEX_1, MusicDownloadDataRequest::startToDownload(), and UPDATE_DIR_FULL.
Referenced by MusicSourceUpdateWidget().
Member Data Documentation
QString MusicSourceUpdateWidget::m_newVersionStr protected
Definition at line 114 of file musicsourceupdatewidget.h.
Referenced by downLoadFinished(), downloadProgressFinished(), and upgradeButtonClicked().
Ui::MusicSourceUpdateWidget* MusicSourceUpdateWidget::m_ui protected
Definition at line 113 of file musicsourceupdatewidget.h.
Referenced by downLoadFinished(), downloadProgressChanged(), downloadSpeedLabelChanged(), MusicSourceUpdateWidget(), upgradeButtonClicked(), and ~MusicSourceUpdateWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsourceupdatewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsourceupdatewidget.cpp