TTKMusicplayer: MusicArtistFoundWidget Class Reference
MusicArtistFoundWidget Class Reference
The class of artist music found widget.
#include <musicartistfoundwidget.h>
Public Slots
void queryAllFinished ()
void queryArtistFinished ()
void createArtistInfoItem (const MusicResultsItem &item)
void setCurrentIndex (int index)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistFoundWidget (QWidget *parent=0)
virtual ~MusicArtistFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
void initWidget ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Member Functions
void createLabels ()
void initThirdWidget ()
void initFourthWidget ()
void initFivethWidget ()
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes
MusicArtistAlbumsFoundWidget * m_artistAlbums
MusicArtistMvsFoundWidget * m_artistMvs
MusicArtistSimilarFoundWidget * m_artistSim
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Detailed Description
The class of artist music found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 255 of file musicartistfoundwidget.h.
Constructor & Destructor Documentation
MusicArtistFoundWidget::MusicArtistFoundWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 373 of file musicartistfoundwidget.cpp.
References MusicSongSharingWidget::Artist, m_artistAlbums, m_artistMvs, m_artistSim, M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_downloadThread, MusicFoundAbstractWidget::m_foundTableWidget, MusicFoundAbstractWidget::m_shareType, and queryAllFinished().
MusicArtistFoundWidget::~MusicArtistFoundWidget () virtual
Definition at line 386 of file musicartistfoundwidget.cpp.
References m_artistAlbums, m_artistMvs, and m_artistSim.
Member Function Documentation
void MusicArtistFoundWidget::createArtistInfoItem (const MusicResultsItem & item) slot
Create the current artist info item.
Definition at line 465 of file musicartistfoundwidget.cpp.
References createLabels(), MusicFoundAbstractWidget::downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, MusicFoundAbstractWidget::m_currentPlaylistItem, MusicResultsItem::m_description, MusicFoundAbstractWidget::m_infoLabel, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicFoundAbstractWidget::m_resizeWidgets, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, and MusicDownloadSourceThread::startToDownload().
Referenced by setSongNameById().
void MusicArtistFoundWidget::createLabels () protected
Create init interface lables.
Definition at line 539 of file musicartistfoundwidget.cpp.
References MusicFoundAbstractWidget::initFirstWidget(), MusicFoundAbstractWidget::initSecondWidget(), MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_iconLabel, MusicFoundAbstractWidget::m_mainWindow, MusicFoundAbstractWidget::m_resizeWidgets, MusicFoundAbstractWidget::m_songButton, MusicFoundAbstractWidget::m_statusLabel, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MColorStyle04, MusicUIObject::MColorStyle05, MusicUIObject::MFontStyle01, MusicUIObject::MFontStyle03, MusicUIObject::MFontStyle06, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, MusicFoundAbstractWidget::playAllButtonClicked(), setCurrentIndex(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), and MusicFoundAbstractWidget::shareButtonClicked().
Referenced by createArtistInfoItem().
QString MusicArtistFoundWidget::getClassName () static
Get class object name.
Definition at line 393 of file musicartistfoundwidget.cpp.
void MusicArtistFoundWidget::initFivethWidget () protected
Init the five widget.
Definition at line 737 of file musicartistfoundwidget.cpp.
References m_artistSim, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_songNameFull, and MusicArtistSimilarFoundWidget::setSongName().
Referenced by setCurrentIndex().
void MusicArtistFoundWidget::initFourthWidget () protected
Init the fourth widget.
Definition at line 730 of file musicartistfoundwidget.cpp.
References m_artistMvs, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_songNameFull, and MusicArtistMvsFoundWidget::setSongName().
Referenced by setCurrentIndex().
void MusicArtistFoundWidget::initThirdWidget () protected
Init the third widget.
Definition at line 723 of file musicartistfoundwidget.cpp.
References m_artistAlbums, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_songNameFull, and MusicArtistAlbumsFoundWidget::setSongName().
Referenced by setCurrentIndex().
void MusicArtistFoundWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 425 of file musicartistfoundwidget.cpp.
References MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicObject::MusicSongInformation::m_artistId, MusicFoundAbstractWidget::m_downloadThread, MusicObject::MusicSongInformation::m_songName, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::m_statusLabel, and setSongNameById().
Referenced by MusicArtistFoundWidget().
void MusicArtistFoundWidget::queryArtistFinished () slot
Query artist musics is finished.
Definition at line 452 of file musicartistfoundwidget.cpp.
References MusicQueryTableWidget::getMusicSongInfos(), MusicFoundAbstractWidget::m_foundTableWidget, MusicFoundAbstractWidget::m_statusLabel, and MusicFoundAbstractWidget::setSongCountText().
void MusicArtistFoundWidget::resizeWindow () override virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 416 of file musicartistfoundwidget.cpp.
References m_artistAlbums, m_artistMvs, m_artistSim, MusicFoundAbstractWidget::m_foundTableWidget, MusicQueryFoundTableWidget::resizeWindow(), MusicArtistMvsFoundWidget::resizeWindow(), MusicArtistSimilarFoundWidget::resizeWindow(), and MusicArtistAlbumsFoundWidget::resizeWindow().
void MusicArtistFoundWidget::setCurrentIndex (int index) slot
Set current container index.
Definition at line 503 of file musicartistfoundwidget.cpp.
References initFivethWidget(), initFourthWidget(), initThirdWidget(), m_artistAlbums, m_artistMvs, m_artistSim, MusicFoundAbstractWidget::m_container, MusicFoundAbstractWidget::m_foundTableWidget, and MusicFoundAbstractWidget::m_infoLabel.
Referenced by createLabels().
void MusicArtistFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 398 of file musicartistfoundwidget.cpp.
References MusicUtils::String::artistName(), MusicFoundAbstractWidget::m_downloadThread, MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownLoadQueryThreadAbstract::setQueryAllRecords(), MusicDownLoadQueryThreadAbstract::setQuerySimplify(), MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicRightAreaWidget::musicArtistFound().
void MusicArtistFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 407 of file musicartistfoundwidget.cpp.
References createArtistInfoItem(), M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_foundTableWidget, MusicQueryFoundTableWidget::setQueryInput(), MusicFoundAbstractWidget::setSongName(), and MusicQueryFoundTableWidget::startSearchQuery().
Referenced by MusicRightAreaWidget::musicArtistFound(), and queryAllFinished().
Member Data Documentation
MusicArtistAlbumsFoundWidget* MusicArtistFoundWidget::m_artistAlbums protected
Definition at line 321 of file musicartistfoundwidget.h.
Referenced by initThirdWidget(), MusicArtistFoundWidget(), resizeWindow(), setCurrentIndex(), and ~MusicArtistFoundWidget().
MusicArtistMvsFoundWidget* MusicArtistFoundWidget::m_artistMvs protected
Definition at line 322 of file musicartistfoundwidget.h.
Referenced by initFourthWidget(), MusicArtistFoundWidget(), resizeWindow(), setCurrentIndex(), and ~MusicArtistFoundWidget().
MusicArtistSimilarFoundWidget* MusicArtistFoundWidget::m_artistSim protected
Definition at line 323 of file musicartistfoundwidget.h.
Referenced by initFivethWidget(), MusicArtistFoundWidget(), resizeWindow(), setCurrentIndex(), and ~MusicArtistFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.cpp