TTKMusicplayer: MusicWebMVRadioInfoWidget Class Reference
MusicWebMVRadioInfoWidget Class Reference
The class of music mv info widget.
#include <musicwebmvradioinfowidget.h>
Public Slots
void queryAllFinished ()
void createCategoryInfoItem (const MusicResultsItem &item)
void downloadMVsButtonClicked ()
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Signals
void backToMainMenu ()
Public Member Functions
MusicWebMVRadioInfoWidget (QWidget *parent=nullptr)
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameById (const QString &id) overridefinal
virtual void resizeWindow () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Protected Member Functions
void createLabels ()
void initThirdWidget ()
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Additional Inherited Members
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of music mv info widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 69 of file musicwebmvradioinfowidget.h.
Constructor & Destructor Documentation
MusicWebMVRadioInfoWidget::MusicWebMVRadioInfoWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 105 of file musicwebmvradioinfowidget.cpp.
References createCategoryInfoItem(), MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_statusLabel, and MusicItemQueryTableWidget::setQueryInput().
Member Function Documentation
void MusicWebMVRadioInfoWidget::backToMainMenu () signal
Set current index to main menu page.
Referenced by createLabels().
void MusicWebMVRadioInfoWidget::createCategoryInfoItem (const MusicResultsItem & item) slot
Create the current category info item.
Definition at line 151 of file musicwebmvradioinfowidget.cpp.
References createLabels(), MusicAbstractItemQueryWidget::downLoadFinished(), MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicResultsItem::m_coverUrl, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicDownloadSourceRequest::startToDownload(), TTK_NULL_STR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicWebMVRadioInfoWidget().
void MusicWebMVRadioInfoWidget::createLabels () protected
Create init interface lables.
Definition at line 184 of file musicwebmvradioinfowidget.cpp.
References backToMainMenu(), MusicUtils::Widget::generateVScrollAreaFormat(), initThirdWidget(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicAbstractItemQueryWidget::m_iconLabel, MusicAbstractItemQueryWidget::m_mainWindow, MusicResultsItem::m_name, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songButton, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSPushButtonStyle03, QtButtonGroupConnect, and TTK_DEFAULT_STR.
Referenced by createCategoryInfoItem().
void MusicWebMVRadioInfoWidget::downloadMVsButtonClicked () slot
Download button clicked now.
Definition at line 179 of file musicwebmvradioinfowidget.cpp.
References MusicItemQueryTableWidget::downloadBatchData(), and MusicAbstractItemQueryWidget::m_queryTableWidget.
Referenced by initThirdWidget().
void MusicWebMVRadioInfoWidget::initThirdWidget () protected
Init the third widget.
Definition at line 275 of file musicwebmvradioinfowidget.cpp.
References downloadMVsButtonClicked(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_queryTableWidget, and MusicUIObject::MQSSPushButtonStyle03.
Referenced by createLabels().
void MusicWebMVRadioInfoWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 146 of file musicwebmvradioinfowidget.cpp.
References MusicAbstractItemQueryWidget::setSongCountText().
void MusicWebMVRadioInfoWidget::resizeWindow () final override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 130 of file musicwebmvradioinfowidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicItemQueryTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicWebMVRadioQueryWidget::resizeWindow().
void MusicWebMVRadioInfoWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 119 of file musicwebmvradioinfowidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::setSongName(), and MusicItemQueryTableWidget::startSearchQuery().
Referenced by MusicWebMVRadioQueryWidget::currentRadioClicked().
void MusicWebMVRadioInfoWidget::setSongNameById (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 125 of file musicwebmvradioinfowidget.cpp.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioinfowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmvradioinfowidget.cpp