TTKMusicPlayer: QAlgorithm::Aes Class Reference
QAlgorithm::Aes Class Reference
The class of the aes wrapper.
#include <aeswrapper.h>
Public Member Functions
QByteArray encryptECB (const QByteArray &in, const QByteArray &key, bool hex=false)
QByteArray decryptECB (const QByteArray &in, const QByteArray &key, bool hex=false)
QByteArray encryptCBC (const QByteArray &in, const QByteArray &key, const QByteArray &iv, bool hex=false)
QByteArray decryptCBC (const QByteArray &in, const QByteArray &key, const QByteArray &iv, bool hex=false)
Detailed Description
The class of the aes wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file aeswrapper.h.
Member Function Documentation
QByteArray QAlgorithm::Aes::decryptCBC (const QByteArray & in, const QByteArray & key, const QByteArray & iv, bool hex = false)
Decrypt aes CBC by input.
Definition at line 83 of file aeswrapper.cpp.
References AES_cbc_encrypt(), AES_DECRYPT, AES_set_decrypt_key(), and DATA_CACHE_SIZE.
QByteArray QAlgorithm::Aes::decryptECB (const QByteArray & in, const QByteArray & key, bool hex = false)
Decrypt des ECB by input.
Definition at line 35 of file aeswrapper.cpp.
References AES_BLOCK_SIZE, AES_DECRYPT, AES_ecb_encrypt(), and AES_set_decrypt_key().
QByteArray QAlgorithm::Aes::encryptCBC (const QByteArray & in, const QByteArray & key, const QByteArray & iv, bool hex = false)
Encrypt aes CBC by input.
Definition at line 58 of file aeswrapper.cpp.
References AES_BLOCK_SIZE, AES_cbc_encrypt(), AES_ENCRYPT, AES_set_encrypt_key(), and DATA_CACHE_SIZE.
Referenced by ReqWYInterface::makeTokenRequest().
QByteArray QAlgorithm::Aes::encryptECB (const QByteArray & in, const QByteArray & key, bool hex = false)
Encrypt des ECB by input.
Definition at line 6 of file aeswrapper.cpp.
References AES_BLOCK_SIZE, AES_ecb_encrypt(), AES_ENCRYPT, and AES_set_encrypt_key().
Referenced by ReqWYInterface::makeTokenRequest().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/aeswrapper.h
TTKThirdParty/TTKExtras/qalgorithm/aeswrapper.cpp