TTKMusicplayer: MusicSongSearchDialog Class Reference
MusicSongSearchDialog Class Reference
The class of the song search widget.
#include <musicsongsearchdialog.h>
Public Slots
bool close ()
Public Member Functions
MusicSongSearchDialog (QWidget *parent=nullptr)
~MusicSongSearchDialog ()
QString text () const
void clear () const
virtual void setVisible (bool visible) overridefinal
Private Attributes
MusicItemSearchEdit * m_searchLine
Detailed Description
The class of the song search widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicsongsearchdialog.h.
Constructor & Destructor Documentation
MusicSongSearchDialog::MusicSongSearchDialog (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicsongsearchdialog.cpp.
References close(), MusicItemSearchEdit::editor(), LEFT_SIDE_WIDTH_MIN, m_searchLine, and MusicUIObject::MQSSTinyBtnClose.
MusicSongSearchDialog::~MusicSongSearchDialog ()
Definition at line 33 of file musicsongsearchdialog.cpp.
References m_searchLine.
Member Function Documentation
void MusicSongSearchDialog::clear () const
Clear the search text.
Definition at line 49 of file musicsongsearchdialog.cpp.
References MusicItemSearchEdit::editor(), and m_searchLine.
Referenced by close().
bool MusicSongSearchDialog::close () slot
Override the close function.
Definition at line 38 of file musicsongsearchdialog.cpp.
References clear().
Referenced by MusicSongsSummariziedWidget::closeSearchWidget(), and MusicSongSearchDialog().
void MusicSongSearchDialog::setVisible (bool visible) final override virtual
Set line edit input focus.
Definition at line 54 of file musicsongsearchdialog.cpp.
References MusicItemSearchEdit::editor(), and m_searchLine.
Referenced by MusicSongsSummariziedWidget::showSearchWidget().
QString MusicSongSearchDialog::text () const
Get the search text that the user searched.
Definition at line 44 of file musicsongsearchdialog.cpp.
References MusicItemSearchEdit::editor(), and m_searchLine.
Referenced by MusicSongsSummariziedWidget::musicSearchResultChanged().
Member Data Documentation
MusicItemSearchEdit* MusicSongSearchDialog::m_searchLine private
Definition at line 62 of file musicsongsearchdialog.h.
Referenced by clear(), MusicSongSearchDialog(), setVisible(), text(), and ~MusicSongSearchDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicsongsearchdialog.h
TTKModule/TTKWidget/musicSearchKits/musicsongsearchdialog.cpp