TTKMusicplayer: MusicLrcMakerWidget Class Reference
MusicLrcMakerWidget Class Reference
The class of the lrc maker widget.
#include <musiclrcmakerwidget.h>
Public Slots
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void currentLineFinished ()
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicLrcMakerWidget (QWidget *parent=0)
virtual ~MusicLrcMakerWidget ()
void setCurrentSongName (const QString &name)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event) override
virtual void keyReleaseEvent (QKeyEvent *event) override
void createCurrentLine (int key)
void createMainWidget ()
void createFirstWidget ()
void createSecondWidget ()
void createThirdWidget ()
bool checkInputValid ()
void setControlEnable (bool enable) const
QString translateTimeString (qint64 time)
void resetToOriginPlayMode ()
void updateCurrentLrc (qint64 time)
void setItemStyleSheet (int index, int size, int transparent)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicLrcMakerWidget * m_ui
QStringList m_plainText
QMap< int, qint64 > m_times
int m_currentLine
MusicObject::PlayMode m_playMode
qint64 m_intervalTime
MusicLrcMakerWidgetItem * m_lineItem
MusicLrcAnalysis * m_analysis
QList< MusicLrcManagerForInline * > m_musicLrcContainer
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Private Slots
void timeSliderValueChanged (int value)
void saveButtonClicked ()
void reMakeButtonClicked ()
void backToMakeLrcWidget ()
void firstWidgetStateButtonClicked ()
void thirdWidgetStateButtonClicked ()
void setCurrentMainWidget ()
void setCurrentFirstWidget ()
void setCurrentSecondWidget ()
void setCurrentThirdWidget ()
void updateAnimationLrc ()
void lrcSpeedSlower ()
void lrcSpeedFaster ()
Detailed Description
The class of the lrc maker widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 99 of file musiclrcmakerwidget.h.
Constructor & Destructor Documentation
MusicLrcMakerWidget::MusicLrcMakerWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 150 of file musiclrcmakerwidget.cpp.
References createFirstWidget(), createMainWidget(), createSecondWidget(), createThirdWidget(), MusicPlayer::getClassName(), getClassName(), MusicApplication::getPlayMode(), MusicApplication::instance(), M_CONNECTION_PTR, m_currentLine, m_intervalTime, m_playMode, m_ui, MusicUIObject::MBackgroundStyle17, MusicUIObject::MToolButtonStyle04, and MusicApplication::musicPlayOneLoop().
MusicLrcMakerWidget::~MusicLrcMakerWidget () virtual
Definition at line 182 of file musiclrcmakerwidget.cpp.
References getClassName(), m_analysis, M_CONNECTION_PTR, m_lineItem, m_musicLrcContainer, m_ui, and resetToOriginPlayMode().
Member Function Documentation
void MusicLrcMakerWidget::backToMakeLrcWidget () private slot
Back to make lrc widget.
Definition at line 291 of file musiclrcmakerwidget.cpp.
References MusicMessageBox::exec(), MusicApplication::instance(), MusicApplication::musicPlayAnyTimeAt(), setCurrentSecondWidget(), and MusicMessageBox::setText().
Referenced by createThirdWidget().
bool MusicLrcMakerWidget::checkInputValid () protected
Check input valid or not.
Definition at line 686 of file musiclrcmakerwidget.cpp.
References MusicMessageBox::exec(), m_ui, and MusicMessageBox::setText().
Referenced by setCurrentSecondWidget().
void MusicLrcMakerWidget::createCurrentLine (int key) protected
Create current line.
Definition at line 452 of file musiclrcmakerwidget.cpp.
References MusicLrcMakerWidgetItem::biggerThan(), MusicLrcMakerWidgetItem::done(), MusicApplication::instance(), m_currentLine, m_lineItem, m_plainText, m_times, m_ui, MusicLrcMakerWidgetItem::moveDown(), MusicLrcMakerWidgetItem::moveLeft(), MusicLrcMakerWidgetItem::moveRight(), MusicLrcMakerWidgetItem::moveUp(), MusicApplication::musicPlayAnyTimeAt(), and MusicLrcMakerWidgetItem::setText().
Referenced by currentLineFinished(), and keyReleaseEvent().
void MusicLrcMakerWidget::createFirstWidget () protected
Create current first widget.
Definition at line 562 of file musiclrcmakerwidget.cpp.
References firstWidgetStateButtonClicked(), MusicApplication::instance(), m_ui, MusicUIObject::MLineEditStyle01, MusicUIObject::MPushButtonStyle04, MusicUIObject::MScrollBarStyle01, MusicUIObject::MSliderStyle09, MusicUIObject::MTextEditStyle01, setCurrentMainWidget(), setCurrentSecondWidget(), and timeSliderValueChanged().
Referenced by MusicLrcMakerWidget().
void MusicLrcMakerWidget::createMainWidget () protected
Create current main widget.
Definition at line 512 of file musiclrcmakerwidget.cpp.
References filter::Linear(), m_ui, MusicUIObject::MPushButtonStyle04, and setCurrentFirstWidget().
Referenced by MusicLrcMakerWidget().
void MusicLrcMakerWidget::createSecondWidget () protected
Create current second widget.
Definition at line 603 of file musiclrcmakerwidget.cpp.
References m_lineItem, m_ui, MusicUIObject::MPushButtonStyle04, MusicUIObject::MScrollBarStyle01, MusicUIObject::MSliderStyle09, MusicUIObject::MTextEditStyle01, setCurrentFirstWidget(), setCurrentThirdWidget(), and timeSliderValueChanged().
Referenced by MusicLrcMakerWidget().
void MusicLrcMakerWidget::createThirdWidget () protected
Create current third widget.
Definition at line 639 of file musiclrcmakerwidget.cpp.
References backToMakeLrcWidget(), MusicLrcAnalysis::getLineMax(), MusicApplication::instance(), lrcSpeedFaster(), lrcSpeedSlower(), m_analysis, m_musicLrcContainer, m_ui, MusicUIObject::MKGInlineMakeDown, MusicUIObject::MKGInlineMakeUp, MusicUIObject::MPushButtonStyle04, MusicUIObject::MSliderStyle09, reMakeButtonClicked(), saveButtonClicked(), MusicLrcAnalysis::setLineMax(), MusicLrcManagerForInline::setLrcPerWidth(), thirdWidgetStateButtonClicked(), and timeSliderValueChanged().
Referenced by MusicLrcMakerWidget().
void MusicLrcMakerWidget::currentLineFinished () slot
Create current line finished.
Definition at line 250 of file musiclrcmakerwidget.cpp.
References createCurrentLine().
void MusicLrcMakerWidget::durationChanged (qint64 duration) slot
Set current player duration.
Definition at line 243 of file musiclrcmakerwidget.cpp.
References m_ui.
Referenced by MusicLrcContainer::showLrcMakedWidget().
void MusicLrcMakerWidget::firstWidgetStateButtonClicked () private slot
First widget state changed.
Definition at line 302 of file musiclrcmakerwidget.cpp.
References MusicApplication::instance(), m_ui, and MusicApplication::musicStatePlay().
Referenced by createFirstWidget(), keyReleaseEvent(), and setCurrentSecondWidget().
QString MusicLrcMakerWidget::getClassName () static
Get class object name.
Definition at line 192 of file musiclrcmakerwidget.cpp.
Referenced by MusicLrcMakerWidget(), MusicConnectionPool::poolConnect(), and ~MusicLrcMakerWidget().
void MusicLrcMakerWidget::keyPressEvent (QKeyEvent * event) override protected virtual
Override the widget event.
Definition at line 436 of file musiclrcmakerwidget.cpp.
void MusicLrcMakerWidget::keyReleaseEvent (QKeyEvent * event) override protected virtual
Definition at line 441 of file musiclrcmakerwidget.cpp.
References createCurrentLine(), and firstWidgetStateButtonClicked().
void MusicLrcMakerWidget::lrcSpeedFaster () private slot
Set lrc time speed changed faster.
Definition at line 430 of file musiclrcmakerwidget.cpp.
References m_analysis, m_ui, MT_S2MS, MusicLrcAnalysis::revertLrcTime(), MusicLrcAnalysis::setSongSpeedAndSlow(), and updateCurrentLrc().
Referenced by createThirdWidget().
void MusicLrcMakerWidget::lrcSpeedSlower () private slot
Set lrc time speed changed slower.
Definition at line 424 of file musiclrcmakerwidget.cpp.
References m_analysis, m_ui, MT_S2MS, MusicLrcAnalysis::revertLrcTime(), MusicLrcAnalysis::setSongSpeedAndSlow(), and updateCurrentLrc().
Referenced by createThirdWidget().
void MusicLrcMakerWidget::positionChanged (qint64 position) slot
Set current player position.
Definition at line 205 of file musiclrcmakerwidget.cpp.
References MusicLrcAnalysis::findText(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::isEmpty(), m_analysis, m_intervalTime, m_musicLrcContainer, m_ui, MusicTime::msecTime2LabelJustified(), and updateCurrentLrc().
void MusicLrcMakerWidget::reMakeButtonClicked () private slot
Remake lrc button clicked.
Definition at line 280 of file musiclrcmakerwidget.cpp.
References MusicMessageBox::exec(), MusicApplication::instance(), MusicApplication::musicPlayAnyTimeAt(), setCurrentFirstWidget(), and MusicMessageBox::setText().
Referenced by createThirdWidget().
void MusicLrcMakerWidget::resetToOriginPlayMode () protected
Reset to origin play mode.
Definition at line 732 of file musiclrcmakerwidget.cpp.
References MusicApplication::instance(), m_playMode, MusicApplication::musicPlayItemOnce(), MusicApplication::musicPlayListLoop(), MusicApplication::musicPlayOneLoop(), MusicApplication::musicPlayOrder(), MusicApplication::musicPlayRandom(), MusicObject::PM_PlayListLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, and MusicObject::PM_PlayRandom.
Referenced by ~MusicLrcMakerWidget().
void MusicLrcMakerWidget::saveButtonClicked () private slot
Save lrc button clicked.
Definition at line 267 of file musiclrcmakerwidget.cpp.
References MusicMessageBox::exec(), m_analysis, m_plainText, m_times, MusicLrcAnalysis::saveLrcTimeChanged(), and MusicMessageBox::setText().
Referenced by createThirdWidget().
void MusicLrcMakerWidget::setControlEnable (bool enable) const protected
Set controller enable or disable.
Definition at line 716 of file musiclrcmakerwidget.cpp.
References m_ui.
void MusicLrcMakerWidget::setCurrentFirstWidget () private slot
Change current widget to first widget.
Definition at line 335 of file musiclrcmakerwidget.cpp.
References LRC_MAKER_INDEX_1, and m_ui.
Referenced by createMainWidget(), createSecondWidget(), and reMakeButtonClicked().
void MusicLrcMakerWidget::setCurrentMainWidget () private slot
Change current widget to main widget.
Definition at line 330 of file musiclrcmakerwidget.cpp.
References LRC_MAKER_INDEX_0, and m_ui.
Referenced by createFirstWidget().
void MusicLrcMakerWidget::setCurrentSecondWidget () private slot
Change current widget to second widget.
Definition at line 340 of file musiclrcmakerwidget.cpp.
References checkInputValid(), firstWidgetStateButtonClicked(), MusicApplication::instance(), MusicApplication::isPlaying(), LRC_MAKER_INDEX_2, m_currentLine, m_lineItem, m_plainText, m_times, m_ui, MusicApplication::musicPlayAnyTimeAt(), MusicLrcMakerWidgetItem::reset(), and MusicLrcMakerWidgetItem::setText().
Referenced by backToMakeLrcWidget(), and createFirstWidget().
void MusicLrcMakerWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 197 of file musiclrcmakerwidget.cpp.
References MusicUtils::String::artistName(), LRC_FILE, MusicUtils::Core::lrcPrefix(), m_analysis, m_plainText, m_ui, MusicLrcAnalysis::setCurrentFileName(), and MusicUtils::String::songName().
Referenced by MusicLrcContainer::showLrcMakedWidget().
void MusicLrcMakerWidget::setCurrentThirdWidget () private slot
Change current widget to third widget.
Definition at line 379 of file musiclrcmakerwidget.cpp.
References MusicMessageBox::exec(), MusicLrcAnalysis::getLineMax(), MusicApplication::instance(), LRC_MAKER_INDEX_3, m_analysis, m_musicLrcContainer, m_plainText, m_times, m_ui, MusicApplication::musicPlayAnyTimeAt(), setItemStyleSheet(), MusicLrcAnalysis::setLrcData(), and MusicMessageBox::setText().
Referenced by createSecondWidget().
void MusicLrcMakerWidget::setItemStyleSheet (int index, int size, int transparent) protected
Set per lrc line style sheet.
Definition at line 759 of file musiclrcmakerwidget.cpp.
References m_musicLrcContainer, M_SETTING_PTR, MusicLrcColor::mapIndexToColor(), MStatic_cast, MusicUtils::String::readColorConfig(), MusicLrcManagerForInline::setCenterOnLrc(), MusicLrcManagerForInline::setFontSize(), MusicLrcManager::setFontTransparent(), MusicLrcManager::setLinearGradientColor(), and MusicLrcManagerForInline::setTransparent().
Referenced by setCurrentThirdWidget().
void MusicLrcMakerWidget::show () slot
Override show function.
Definition at line 255 of file musiclrcmakerwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Referenced by MusicLrcContainer::showLrcMakedWidget().
void MusicLrcMakerWidget::thirdWidgetStateButtonClicked () private slot
Third widget state changed.
Definition at line 311 of file musiclrcmakerwidget.cpp.
References MusicLrcAnalysis::getMiddle(), MusicApplication::instance(), m_analysis, m_intervalTime, m_musicLrcContainer, m_ui, and MusicApplication::musicStatePlay().
Referenced by createThirdWidget().
void MusicLrcMakerWidget::timeSliderValueChanged (int value) private slot
Time slider value changed.
Definition at line 261 of file musiclrcmakerwidget.cpp.
References MusicApplication::instance(), m_analysis, MusicApplication::musicPlayAnyTimeAt(), and MusicLrcAnalysis::setSongSpeedAndSlow().
Referenced by createFirstWidget(), createSecondWidget(), and createThirdWidget().
QString MusicLrcMakerWidget::translateTimeString (qint64 time) protected
Translate current long time to string.
Definition at line 725 of file musiclrcmakerwidget.cpp.
References MusicTime::All_Msec, MusicTime::getMillionSecond(), and MusicTime::toString().
void MusicLrcMakerWidget::updateAnimationLrc () private slot
Animation finished.
Definition at line 414 of file musiclrcmakerwidget.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), m_analysis, m_intervalTime, m_musicLrcContainer, and MusicLrcAnalysis::setCurrentIndex().
void MusicLrcMakerWidget::updateCurrentLrc (qint64 time) protected
Update current lrc by given time.
Definition at line 750 of file musiclrcmakerwidget.cpp.
References MusicLrcAnalysis::isValid(), m_analysis, m_intervalTime, and m_ui.
Referenced by lrcSpeedFaster(), lrcSpeedSlower(), and positionChanged().
Member Data Documentation
MusicLrcAnalysis* MusicLrcMakerWidget::m_analysis protected
Definition at line 251 of file musiclrcmakerwidget.h.
Referenced by createThirdWidget(), lrcSpeedFaster(), lrcSpeedSlower(), positionChanged(), saveButtonClicked(), setCurrentSongName(), setCurrentThirdWidget(), thirdWidgetStateButtonClicked(), timeSliderValueChanged(), updateAnimationLrc(), updateCurrentLrc(), and ~MusicLrcMakerWidget().
int MusicLrcMakerWidget::m_currentLine protected
Definition at line 247 of file musiclrcmakerwidget.h.
Referenced by createCurrentLine(), MusicLrcMakerWidget(), and setCurrentSecondWidget().
qint64 MusicLrcMakerWidget::m_intervalTime protected
Definition at line 249 of file musiclrcmakerwidget.h.
Referenced by MusicLrcMakerWidget(), positionChanged(), thirdWidgetStateButtonClicked(), updateAnimationLrc(), and updateCurrentLrc().
MusicLrcMakerWidgetItem* MusicLrcMakerWidget::m_lineItem protected
Definition at line 250 of file musiclrcmakerwidget.h.
Referenced by createCurrentLine(), createSecondWidget(), setCurrentSecondWidget(), and ~MusicLrcMakerWidget().
QList<MusicLrcManagerForInline*> MusicLrcMakerWidget::m_musicLrcContainer protected
Definition at line 252 of file musiclrcmakerwidget.h.
Referenced by createThirdWidget(), positionChanged(), setCurrentThirdWidget(), setItemStyleSheet(), thirdWidgetStateButtonClicked(), updateAnimationLrc(), and ~MusicLrcMakerWidget().
QStringList MusicLrcMakerWidget::m_plainText protected
Definition at line 244 of file musiclrcmakerwidget.h.
Referenced by createCurrentLine(), saveButtonClicked(), setCurrentSecondWidget(), setCurrentSongName(), and setCurrentThirdWidget().
MusicObject::PlayMode MusicLrcMakerWidget::m_playMode protected
Definition at line 248 of file musiclrcmakerwidget.h.
Referenced by MusicLrcMakerWidget(), and resetToOriginPlayMode().
QMap<int, qint64> MusicLrcMakerWidget::m_times protected
Definition at line 245 of file musiclrcmakerwidget.h.
Referenced by createCurrentLine(), saveButtonClicked(), setCurrentSecondWidget(), and setCurrentThirdWidget().
Ui::MusicLrcMakerWidget* MusicLrcMakerWidget::m_ui protected
Definition at line 243 of file musiclrcmakerwidget.h.
Referenced by checkInputValid(), createCurrentLine(), createFirstWidget(), createMainWidget(), createSecondWidget(), createThirdWidget(), durationChanged(), firstWidgetStateButtonClicked(), lrcSpeedFaster(), lrcSpeedSlower(), MusicLrcMakerWidget(), positionChanged(), setControlEnable(), setCurrentFirstWidget(), setCurrentMainWidget(), setCurrentSecondWidget(), setCurrentSongName(), setCurrentThirdWidget(), show(), thirdWidgetStateButtonClicked(), updateCurrentLrc(), and ~MusicLrcMakerWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcmakerwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcmakerwidget.cpp