TTKMusicplayer: MusicSongCheckToolsItemSelectedDialog Class Reference
MusicSongCheckToolsItemSelectedDialog Class Reference
The class of the song check tools item selected dialog widget.
#include <musicsongchecktoolsitemselecteddialog.h>
Public Slots
void confirmButtonClicked ()
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void itemListsChanged (const MusicObject::MIntList &items)
Public Member Functions
MusicSongCheckToolsItemSelectedDialog (QWidget *parent=0)
virtual ~MusicSongCheckToolsItemSelectedDialog ()
void createAllItems (MusicSongItems *items)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Attributes
Ui::MusicSongCheckToolsItemSelectedDialog * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the song check tools item selected dialog widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 50 of file musicsongchecktoolsitemselecteddialog.h.
Constructor & Destructor Documentation
MusicSongCheckToolsItemSelectedDialog::MusicSongCheckToolsItemSelectedDialog (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 93 of file musicsongchecktoolsitemselecteddialog.cpp.
References confirmButtonClicked(), m_ui, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MPushButtonStyle04, and MusicUIObject::MToolButtonStyle04.
MusicSongCheckToolsItemSelectedDialog::~MusicSongCheckToolsItemSelectedDialog () virtual
Definition at line 116 of file musicsongchecktoolsitemselecteddialog.cpp.
References m_ui.
Member Function Documentation
void MusicSongCheckToolsItemSelectedDialog::confirmButtonClicked () slot
Confirm button clicked.
Definition at line 131 of file musicsongchecktoolsitemselecteddialog.cpp.
References itemListsChanged(), and m_ui.
Referenced by MusicSongCheckToolsItemSelectedDialog().
void MusicSongCheckToolsItemSelectedDialog::createAllItems (MusicSongItems * items)
Create all items.
Definition at line 126 of file musicsongchecktoolsitemselecteddialog.cpp.
References m_ui.
Referenced by MusicSongCheckToolsWidget::modifiedItemButtonClicked().
int MusicSongCheckToolsItemSelectedDialog::exec () virtual slot
Override exec function.
Definition at line 137 of file musicsongchecktoolsitemselecteddialog.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicSongCheckToolsWidget::modifiedItemButtonClicked().
QString MusicSongCheckToolsItemSelectedDialog::getClassName () static
Get class object name.
Definition at line 121 of file musicsongchecktoolsitemselecteddialog.cpp.
void MusicSongCheckToolsItemSelectedDialog::itemListsChanged (const MusicObject::MIntList & items) signal
Item lists changed.
Referenced by confirmButtonClicked().
Member Data Documentation
Ui::MusicSongCheckToolsItemSelectedDialog* MusicSongCheckToolsItemSelectedDialog::m_ui protected
Definition at line 88 of file musicsongchecktoolsitemselecteddialog.h.
Referenced by confirmButtonClicked(), createAllItems(), exec(), MusicSongCheckToolsItemSelectedDialog(), and ~MusicSongCheckToolsItemSelectedDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolsitemselecteddialog.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsongchecktoolsitemselecteddialog.cpp