TTKMusicplayer: MusicEMOJILabelWidget Class Reference
MusicEMOJILabelWidget Class Reference
The class of the emoji label widget.
#include <musicemojilabelwidget.h>
Signals
void dataChanged (const QString &data)
Public Member Functions
MusicEMOJILabelWidget (QWidget *parent=nullptr)
~MusicEMOJILabelWidget ()
Protected Member Functions
virtual void leaveEvent (QEvent *event) overridefinal
Protected Attributes
int m_currentPage
QList< QLabel * > m_labelItems
QList< QToolButton * > m_buttonItems
QStringList m_datas
Private Slots
void buttonClicked (int index)
void labelClicked (int index)
Detailed Description
The class of the emoji label widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicemojilabelwidget.h.
Constructor & Destructor Documentation
MusicEMOJILabelWidget::MusicEMOJILabelWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicemojilabelwidget.cpp.
References buttonClicked(), labelClicked(), m_buttonItems, m_datas, m_labelItems, MusicClickedGroup::mapped(), MusicUIObject::MQSSBorderStyle04, MusicUIObject::MQSSBorderStyle05, MusicUIObject::MQSSTinyBtnClose, and MusicUtils::String::newlines().
MusicEMOJILabelWidget::~MusicEMOJILabelWidget ()
Definition at line 89 of file musicemojilabelwidget.cpp.
References m_buttonItems, and m_labelItems.
Member Function Documentation
void MusicEMOJILabelWidget::buttonClicked (int index) private slot
Page button changed.
Definition at line 95 of file musicemojilabelwidget.cpp.
References m_buttonItems, m_currentPage, m_labelItems, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSBorderStyle01, and MusicUIObject::MQSSBorderStyle04.
Referenced by MusicEMOJILabelWidget().
void MusicEMOJILabelWidget::dataChanged (const QString & data) signal
Get current label emoji.
Referenced by labelClicked().
void MusicEMOJILabelWidget::labelClicked (int index) private slot
Label selected state changed.
Definition at line 114 of file musicemojilabelwidget.cpp.
References dataChanged(), m_currentPage, and m_datas.
Referenced by MusicEMOJILabelWidget().
void MusicEMOJILabelWidget::leaveEvent (QEvent * event) final override protected virtual
Override the widget event.
Definition at line 125 of file musicemojilabelwidget.cpp.
Member Data Documentation
QList<QToolButton*> MusicEMOJILabelWidget::m_buttonItems protected
Definition at line 65 of file musicemojilabelwidget.h.
Referenced by buttonClicked(), MusicEMOJILabelWidget(), and ~MusicEMOJILabelWidget().
int MusicEMOJILabelWidget::m_currentPage protected
Definition at line 63 of file musicemojilabelwidget.h.
Referenced by buttonClicked(), and labelClicked().
QStringList MusicEMOJILabelWidget::m_datas protected
Definition at line 66 of file musicemojilabelwidget.h.
Referenced by labelClicked(), and MusicEMOJILabelWidget().
QList<QLabel*> MusicEMOJILabelWidget::m_labelItems protected
Definition at line 64 of file musicemojilabelwidget.h.
Referenced by buttonClicked(), MusicEMOJILabelWidget(), and ~MusicEMOJILabelWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicemojilabelwidget.h
TTKModule/TTKWidget/musicCoreKits/musicemojilabelwidget.cpp