TTKMusicplayer: MusicBackgroundThunderWidget Class Reference
MusicBackgroundThunderWidget Class Reference
The class of the thunder background widget.
#include <musicbackgroundremotewidget.h>
Public Slots
void buttonClicked (int index)
virtual void downLoadFinished (const MusicSkinRemoteGroups &bytes) override
Public Slots inherited from MusicBackgroundRemoteWidget
void downLoadFinished (const QString &bytes)
virtual void downLoadFinished (const MusicSkinRemoteGroups &bytes)
Public Member Functions
MusicBackgroundThunderWidget (QWidget *parent=nullptr)
~MusicBackgroundThunderWidget ()
void initialize ()
QWidget * createFunctionsWidget (bool revert, QWidget *object=nullptr)
virtual void outputRemoteSkin (MusicBackgroundImage &image, const QString &data) override
Public Member Functions inherited from MusicBackgroundRemoteWidget
MusicBackgroundRemoteWidget (QWidget *parent=nullptr)
~MusicBackgroundRemoteWidget ()
void abort ()
Protected Member Functions
QPushButton * createButton (const QString &name)
void buttonStyleChanged ()
Protected Member Functions inherited from MusicBackgroundRemoteWidget
void startToDownload (const QString &prefix)
Protected Attributes
QWidget * m_functionsWidget
QList< QPushButton * > m_functionsItems
Protected Attributes inherited from MusicBackgroundRemoteWidget
int m_currentIndex
MusicSkinRemoteGroups m_groups
MusicBackgroundListWidget * m_backgroundList
MusicDownloadQueueRequest * m_downloadQueue
MusicDownloadBackgroundRemoteRequest * m_downloadRequest
Detailed Description
The class of the thunder background widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 82 of file musicbackgroundremotewidget.h.
Constructor & Destructor Documentation
MusicBackgroundThunderWidget::MusicBackgroundThunderWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 89 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::m_backgroundList, and m_functionsWidget.
MusicBackgroundThunderWidget::~MusicBackgroundThunderWidget ()
Definition at line 96 of file musicbackgroundremotewidget.cpp.
References m_functionsWidget.
Member Function Documentation
void MusicBackgroundThunderWidget::buttonClicked (int index) slot
Remote background type selected by index.
Definition at line 199 of file musicbackgroundremotewidget.cpp.
References MusicDownloadQueueRequest::abort(), buttonStyleChanged(), MusicBackgroundRemoteWidget::m_currentIndex, MusicBackgroundRemoteWidget::m_downloadQueue, MusicBackgroundRemoteWidget::m_groups, MusicBackgroundRemoteWidget::startToDownload(), and TTS_FILE.
Referenced by createFunctionsWidget().
void MusicBackgroundThunderWidget::buttonStyleChanged () protected
Button style changed.
Definition at line 249 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::m_currentIndex, m_functionsItems, MusicUIObject::MQSSColorStyle08, and MusicUIObject::MQSSPushButtonStyle02.
Referenced by buttonClicked().
QPushButton * MusicBackgroundThunderWidget::createButton (const QString & name) protected
Create button.
Definition at line 234 of file musicbackgroundremotewidget.cpp.
References m_functionsItems, m_functionsWidget, and MusicUIObject::MQSSPushButtonStyle02.
Referenced by createFunctionsWidget().
QWidget * MusicBackgroundThunderWidget::createFunctionsWidget (bool revert, QWidget * object = nullptr)
Create functions widget.
Definition at line 111 of file musicbackgroundremotewidget.cpp.
References buttonClicked(), createButton(), m_functionsItems, m_functionsWidget, MusicUIObject::MQSSColorStyle08, and TTKStatic_cast.
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundThunderWidget::downLoadFinished (const MusicSkinRemoteGroups & bytes) override virtual slot
Send download data from net.
Definition at line 217 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::downLoadFinished(), m_functionsItems, MusicSkinRemoteGroup::m_group, and MusicBackgroundRemoteWidget::m_groups.
Referenced by initialize().
void MusicBackgroundThunderWidget::initialize ()
Init parameters.
Definition at line 101 of file musicbackgroundremotewidget.cpp.
References downLoadFinished(), MusicBackgroundRemoteWidget::m_downloadRequest, and MusicDownloadBackgroundRemoteRequest::startToDownload().
Referenced by MusicBackgroundSkinDialog::backgroundListWidgetChanged().
void MusicBackgroundThunderWidget::outputRemoteSkin (MusicBackgroundImage & image, const QString & data) override virtual
Output remote skin.
Implements MusicBackgroundRemoteWidget.
Definition at line 181 of file musicbackgroundremotewidget.cpp.
References MusicBackgroundRemoteWidget::m_currentIndex, MusicBackgroundRemoteWidget::m_groups, MusicBackgroundImage::m_item, MusicSkinRemoteItem::m_name, MusicSkinConfigItem::m_name, MusicBackgroundImage::m_pix, MusicSkinRemoteItem::m_useCount, MusicSkinConfigItem::m_useCount, and MusicExtractWrapper::outputThunderSkin().
Member Data Documentation
QList<QPushButton*> MusicBackgroundThunderWidget::m_functionsItems protected
Definition at line 128 of file musicbackgroundremotewidget.h.
Referenced by buttonStyleChanged(), createButton(), createFunctionsWidget(), and downLoadFinished().
QWidget* MusicBackgroundThunderWidget::m_functionsWidget protected
Definition at line 127 of file musicbackgroundremotewidget.h.
Referenced by createButton(), createFunctionsWidget(), MusicBackgroundThunderWidget(), and ~MusicBackgroundThunderWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundremotewidget.cpp