TTKMusicplayer: MusicLabelDelegate Class Reference
MusicLabelDelegate Class Reference
The class of the label item delegate.
#include <musicitemdelegate.h>
Public Member Functions
MusicLabelDelegate (QObject *parent=nullptr)
~MusicLabelDelegate ()
void setAlignment (Qt::Alignment alignment) const
virtual void setStyleSheet (const QString &style) const overridefinal
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &) const overridefinal
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const overridefinal
Public Member Functions inherited from MusicAbstractDelegate
MusicAbstractDelegate (QObject *parent=nullptr)
~MusicAbstractDelegate ()
void setTextMode (bool mode)
void setElideMode (bool mode)
void setTreeModel (bool tree)
Protected Attributes
QLabel * m_label
Protected Attributes inherited from MusicAbstractDelegate
bool m_textMode
bool m_elideMode
bool m_treeMode
Detailed Description
The class of the label item delegate.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 153 of file musicitemdelegate.h.
Constructor & Destructor Documentation
MusicLabelDelegate::MusicLabelDelegate (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 138 of file musicitemdelegate.cpp.
References m_label, and MusicUIObject::MQSSBackgroundStyle13.
MusicLabelDelegate::~MusicLabelDelegate ()
Definition at line 146 of file musicitemdelegate.cpp.
References m_label.
Member Function Documentation
void MusicLabelDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const final override virtual
Override paint.
Definition at line 168 of file musicitemdelegate.cpp.
References MusicUtils::Widget::elidedText(), MusicAbstractDelegate::m_elideMode, m_label, MusicAbstractDelegate::m_treeMode, and MUSIC_TEXT_ROLE.
void MusicLabelDelegate::setAlignment (Qt::Alignment alignment) const
Set text alignment.
Definition at line 151 of file musicitemdelegate.cpp.
References m_label.
Referenced by MusicPluginWidget::MusicPluginWidget(), and MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget().
void MusicLabelDelegate::setStyleSheet (const QString & style) const final override virtual
Set delegate item style.
Implements MusicAbstractDelegate.
Definition at line 156 of file musicitemdelegate.cpp.
References m_label.
Referenced by MusicPluginWidget::MusicPluginWidget(), and MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget().
QSize MusicLabelDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex &) const final override virtual
Override size hint.
Definition at line 161 of file musicitemdelegate.cpp.
Member Data Documentation
QLabel* MusicLabelDelegate::m_label protected
Definition at line 183 of file musicitemdelegate.h.
Referenced by MusicLabelDelegate(), paint(), setAlignment(), setStyleSheet(), and ~MusicLabelDelegate().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicitemdelegate.h
TTKModule/TTKWidget/musicCoreKits/musicitemdelegate.cpp