TTKMusicPlayer: MusicDownloadToolBoxWidget Class Reference
MusicDownloadToolBoxWidget Class Reference
The class of the download tool box widget.
#include <musicdownloadrecordwidget.h>
Public Slots
void updateItemTitle (int index)
Public Slots inherited from MusicFunctionToolBoxWidget
void setCurrentIndex (int index)
void itemIndexChanged (int index)
void setTransparent (int alpha)
Public Member Functions
MusicDownloadToolBoxWidget (QWidget *parent=nullptr)
~MusicDownloadToolBoxWidget ()
Public Member Functions inherited from MusicFunctionToolBoxWidget
MusicFunctionToolBoxWidget (QWidget *parent=nullptr)
~MusicFunctionToolBoxWidget ()
void addCellItem (QWidget *item, const QString &text)
void removeItem (QWidget *item)
void swapItem (int before, int after)
void setTitle (QWidget *item, const QString &text)
void resizeScrollIndex (int index) const
int currentIndex () const
int count () const
Private Member Functions
void createWidgetItem (MusicAbstractDownloadTableWidget *widget, const QString &text, int index)
virtual MusicFunctionToolBoxWidgetItem * initialItem (QWidget *item, const QString &text) overridefinal
Private Attributes
MusicSongItemList m_songItems
MusicDownloadRecordTableWidget * m_downloadTable
Additional Inherited Members
Protected Member Functions inherited from MusicFunctionToolBoxWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
int foundMappedIndex (int index)
Protected Attributes inherited from MusicFunctionToolBoxWidget
int m_currentIndex
int m_itemIndexRaise
QVBoxLayout * m_layout
QScrollArea * m_scrollArea
QWidget * m_contentsWidget
MusicToolBoxWidgetItemList m_itemList
Detailed Description
The class of the download tool box widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 50 of file musicdownloadrecordwidget.h.
Constructor & Destructor Documentation
MusicDownloadToolBoxWidget::MusicDownloadToolBoxWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 60 of file musicdownloadrecordwidget.cpp.
References createWidgetItem(), m_songItems, and updateItemTitle().
MusicDownloadToolBoxWidget::~MusicDownloadToolBoxWidget ()
Definition at line 70 of file musicdownloadrecordwidget.cpp.
References m_songItems.
Member Function Documentation
void MusicDownloadToolBoxWidget::createWidgetItem (MusicAbstractDownloadTableWidget * widget, const QString & text, int index) private
Create widget item.
Definition at line 88 of file musicdownloadrecordwidget.cpp.
References MusicFunctionToolBoxWidget::addCellItem(), MusicSongItem::m_itemIndex, MusicSongItem::m_itemName, MusicSongItem::m_itemObject, m_songItems, MusicSongItem::m_songs, MusicAbstractSongsListTableWidget::setSongsList(), MusicFunctionToolBoxWidget::setTitle(), and MusicAbstractSongsListTableWidget::setToolIndex().
Referenced by MusicDownloadToolBoxWidget().
MusicFunctionToolBoxWidgetItem * MusicDownloadToolBoxWidget::initialItem (QWidget * item, const QString & text) final override private virtual
Create item.
Reimplemented from MusicFunctionToolBoxWidget.
Definition at line 102 of file musicdownloadrecordwidget.cpp.
References MusicFunctionToolBoxWidgetItem::addCellItem(), MusicFunctionToolBoxWidget::m_itemIndexRaise, and MusicFunctionToolBoxWidgetItem::setItemExpand().
void MusicDownloadToolBoxWidget::updateItemTitle (int index) slot
Update item title.
Definition at line 79 of file musicdownloadrecordwidget.cpp.
References MusicSongItem::m_itemName, MusicSongItem::m_itemObject, m_songItems, MusicSongItem::m_songs, and MusicFunctionToolBoxWidget::setTitle().
Referenced by MusicDownloadToolBoxWidget().
Member Data Documentation
MusicDownloadRecordTableWidget* MusicDownloadToolBoxWidget::m_downloadTable private
Definition at line 78 of file musicdownloadrecordwidget.h.
MusicSongItemList MusicDownloadToolBoxWidget::m_songItems private
Definition at line 77 of file musicdownloadrecordwidget.h.
Referenced by createWidgetItem(), MusicDownloadToolBoxWidget(), updateItemTitle(), and ~MusicDownloadToolBoxWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicdownloadrecordwidget.h
TTKModule/TTKWidget/musicToolsKits/musicdownloadrecordwidget.cpp