TTKMusicPlayer: MusicLrcFloatWidget Class Reference
MusicLrcFloatWidget Class Reference
The class of the lrc float widget.
#include <musiclrcfloatwidget.h>
Public Slots
void showArtistPhotoWidget ()
void showFloatSettingWidget ()
void closeFloatSettingWidget ()
void wallpaperButtonClicked ()
Public Member Functions
MusicLrcFloatWidget (QWidget *parent=nullptr)
~MusicLrcFloatWidget ()
void resizeGeometry (int width, int height)
Public Member Functions inherited from MusicAbstractFloatWidget
MusicAbstractFloatWidget (QWidget *parent=nullptr)
~MusicAbstractFloatWidget ()
void setBlockAnimation (bool b)
Private Attributes
QPushButton * m_more
QPushButton * m_update
QPushButton * m_search
QPushButton * m_wallpaper
QPushButton * m_photo
MusicLrcFloatPhotoWidget * m_floatPhotoWidget
MusicLrcFloatSettingWidget * m_floatSettingWidget
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractFloatWidget
virtual void enterEvent (QtEnterEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *) overridefinal
virtual void mousePressEvent (QMouseEvent *) overridefinal
virtual void mouseMoveEvent (QMouseEvent *) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *) overridefinal
void animationEnter ()
void animationLeave ()
Protected Attributes inherited from MusicAbstractFloatWidget
QPropertyAnimation * m_animation
QRect m_rectEnter
QRect m_rectLeave
bool m_blockAnimation
Detailed Description
The class of the lrc float widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclrcfloatwidget.h.
Constructor & Destructor Documentation
MusicLrcFloatWidget::MusicLrcFloatWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 9 of file musiclrcfloatwidget.cpp.
References MusicUIObject::BackgroundStyle05, closeFloatSettingWidget(), MusicUIObject::InteriorFloatMore, MusicUIObject::InteriorFloatPhoto, MusicUIObject::InteriorFloatSearch, MusicUIObject::InteriorFloatUpdate, MusicUIObject::InteriorFloatWallpaper, m_floatPhotoWidget, m_floatSettingWidget, m_more, m_photo, m_search, m_update, m_wallpaper, MusicUIObject::PushButtonStyle01, MusicUIObject::PushButtonStyle07, resizeGeometry(), showArtistPhotoWidget(), showFloatSettingWidget(), and wallpaperButtonClicked().
MusicLrcFloatWidget::~MusicLrcFloatWidget ()
Definition at line 64 of file musiclrcfloatwidget.cpp.
References m_floatPhotoWidget, m_floatSettingWidget, m_more, m_photo, m_search, m_update, and m_wallpaper.
Member Function Documentation
void MusicLrcFloatWidget::closeFloatSettingWidget () slot
Close float setting widget.
Definition at line 100 of file musiclrcfloatwidget.cpp.
References m_floatSettingWidget, and MusicAbstractFloatWidget::setBlockAnimation().
Referenced by MusicLrcFloatWidget().
void MusicLrcFloatWidget::resizeGeometry (int width, int height)
Resize geometry bound by given width and height.
Definition at line 75 of file musiclrcfloatwidget.cpp.
References m_floatPhotoWidget, m_floatSettingWidget, MusicAbstractFloatWidget::m_rectEnter, MusicAbstractFloatWidget::m_rectLeave, MusicLrcFloatSettingWidget::resizeGeometry(), and MusicLrcFloatPhotoWidget::resizeGeometry().
Referenced by MusicLrcFloatWidget(), and MusicLrcContainerForInterior::resizeWidth().
void MusicLrcFloatWidget::showArtistPhotoWidget () slot
Show artist photo widget.
Definition at line 85 of file musiclrcfloatwidget.cpp.
References m_floatPhotoWidget, and MusicLrcFloatPhotoWidget::show().
Referenced by MusicLrcFloatWidget().
void MusicLrcFloatWidget::showFloatSettingWidget () slot
Show float setting widget.
Definition at line 93 of file musiclrcfloatwidget.cpp.
References MusicAbstractFloatWidget::animationLeave(), m_floatSettingWidget, MusicAbstractFloatWidget::setBlockAnimation(), and MusicLrcFloatSettingWidget::show().
Referenced by MusicLrcFloatWidget().
void MusicLrcFloatWidget::wallpaperButtonClicked () slot
Lrc desktop wallpaper button clicked.
Definition at line 106 of file musiclrcfloatwidget.cpp.
References MusicBottomAreaWidget::instance(), MusicRightAreaWidget::instance(), MusicUIObject::InteriorFloatWallpaper, MusicUIObject::InteriorFloatWallpaperOn, MusicBottomAreaWidget::lrcWidgetShowFullScreen(), m_wallpaper, MusicRightAreaWidget::musicContainerForWallpaperClicked(), MusicUIObject::PushButtonStyle01, MusicUIObject::PushButtonStyle07, and MusicUIObject::PushButtonStyle11.
Referenced by MusicLrcFloatWidget().
Member Data Documentation
MusicLrcFloatPhotoWidget* MusicLrcFloatWidget::m_floatPhotoWidget private
Definition at line 68 of file musiclrcfloatwidget.h.
Referenced by MusicLrcFloatWidget(), resizeGeometry(), showArtistPhotoWidget(), and ~MusicLrcFloatWidget().
MusicLrcFloatSettingWidget* MusicLrcFloatWidget::m_floatSettingWidget private
Definition at line 69 of file musiclrcfloatwidget.h.
Referenced by closeFloatSettingWidget(), MusicLrcFloatWidget(), resizeGeometry(), showFloatSettingWidget(), and ~MusicLrcFloatWidget().
QPushButton* MusicLrcFloatWidget::m_more private
Definition at line 66 of file musiclrcfloatwidget.h.
Referenced by MusicLrcFloatWidget(), and ~MusicLrcFloatWidget().
QPushButton * MusicLrcFloatWidget::m_photo private
Definition at line 67 of file musiclrcfloatwidget.h.
Referenced by MusicLrcFloatWidget(), and ~MusicLrcFloatWidget().
QPushButton * MusicLrcFloatWidget::m_search private
Definition at line 66 of file musiclrcfloatwidget.h.
Referenced by MusicLrcFloatWidget(), and ~MusicLrcFloatWidget().
QPushButton * MusicLrcFloatWidget::m_update private
Definition at line 66 of file musiclrcfloatwidget.h.
Referenced by MusicLrcFloatWidget(), and ~MusicLrcFloatWidget().
QPushButton* MusicLrcFloatWidget::m_wallpaper private
Definition at line 67 of file musiclrcfloatwidget.h.
Referenced by MusicLrcFloatWidget(), wallpaperButtonClicked(), and ~MusicLrcFloatWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatwidget.cpp