TTKMusicPlayer: QDlnaHelper Namespace Reference
QDlnaHelper Namespace Reference
The namespace of the dlna helper.
Functions
QString MakeRequest (const QString &methord, const QString &url, int length, const QString &soapAction, const QString &ip, const QString &port)
QString makeSocketGetReply (const QString &ip, const QString &port, const QString &data)
QString removeHttpHeader (const QString &data)
int GetResponseCode (const QString &data)
Detailed Description
The namespace of the dlna helper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
int QDlnaHelper::GetResponseCode (const QString & data)
Get response code.
Definition at line 76 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer().
QString QDlnaHelper::MakeRequest (const QString & methord, const QString & url, int length, const QString & soapAction, const QString & ip, const QString & port)
Make request.
Definition at line 9 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer(), QDlnaClient::pause(), QDlnaClient::position(), QDlnaClient::startPlay(), QDlnaClient::stopPlay(), and QDlnaClient::uploadFileToPlay().
QString QDlnaHelper::makeSocketGetReply (const QString & ip, const QString & port, const QString & data)
Make socket get reply.
Definition at line 40 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer(), QDlnaClient::pause(), QDlnaClient::position(), QDlnaClient::startPlay(), QDlnaClient::stopPlay(), and QDlnaClient::uploadFileToPlay().
QString QDlnaHelper::removeHttpHeader (const QString & data)
Remove http header.
Definition at line 70 of file qdlnahelper.cpp.
Referenced by QDlnaClientPrivate::connectServer().