TTKMusicplayer: MusicDownloadRecordWidget Class Reference
MusicDownloadRecordWidget Class Reference
The class of the download record widget.
#include <musicdownloadrecordwidget.h>
Public Slots
void musicPlay ()
virtual void setDeleteItemAt () override
void listCellClicked (int row, int column)
void listCellDoubleClicked (int row, int column)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Public Slots inherited from MusicSongsListAbstractTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
Public Slots inherited from MusicSlowMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void addSongToPlay (const QStringList &list)
Signals inherited from MusicSongsListAbstractTableWidget
void isCurrentIndexs (bool &state)
Public Member Functions
MusicDownloadRecordWidget (QWidget *parent=0)
virtual ~MusicDownloadRecordWidget ()
void musicSongsFileName ()
void clearAllItems ()
Public Member Functions inherited from MusicSongsListAbstractTableWidget
MusicSongsListAbstractTableWidget (QWidget *parent=0)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void updateSongsFileName (const MusicSongs &songs)
virtual void selectRow (int index)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSlowMovingTableWidget
MusicSlowMovingTableWidget (QWidget *parent=0)
virtual ~MusicSlowMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicSongsListAbstractTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicSlowMovingTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
void createItem (int index, const MusicDownloadRecord &record, qint64 time)
Protected Member Functions inherited from MusicSongsListAbstractTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSlowMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
MusicProgressBarDelegate * m_delegate
MusicDownloadRecords m_musicRecords
int m_loadRecordCount
Protected Attributes inherited from MusicSongsListAbstractTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSlowMovingTableWidget
bool m_isFirstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the download record widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 20 of file musicdownloadrecordwidget.h.
Constructor & Destructor Documentation
MusicDownloadRecordWidget::MusicDownloadRecordWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 11 of file musicdownloadrecordwidget.cpp.
References getClassName(), MusicSongsSummariziedWidget::getClassName(), listCellDoubleClicked(), M_CONNECTION_PTR, m_delegate, MusicUIObject::MScrollBarStyle03, musicSongsFileName(), and MusicUtils::Widget::setTransparent().
MusicDownloadRecordWidget::~MusicDownloadRecordWidget () virtual
Definition at line 35 of file musicdownloadrecordwidget.cpp.
References clearAllItems(), getClassName(), M_CONNECTION_PTR, m_delegate, m_musicRecords, MusicSongsListAbstractTableWidget::m_musicSongs, MusicDownloadRecordConfigManager::Normal, and MusicDownloadRecordConfigManager::writeDownloadConfig().
Member Function Documentation
void MusicDownloadRecordWidget::addSongToPlay (const QStringList & list) signal
Add current selected song to play lists.
Referenced by musicPlay().
void MusicDownloadRecordWidget::clearAllItems ()
Clear All Items.
Definition at line 69 of file musicdownloadrecordwidget.cpp.
References MusicAbstractTableWidget::clear().
Referenced by ~MusicDownloadRecordWidget().
void MusicDownloadRecordWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 161 of file musicdownloadrecordwidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicUIObject::MMenuStyle02, MusicSongsListAbstractTableWidget::musicAlbumFoundWidget(), MusicSongsListAbstractTableWidget::musicFileInformation(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicPlayClicked(), MusicSongsListAbstractTableWidget::musicSongDownload(), MusicSongsListAbstractTableWidget::setDeleteItemAll(), and setDeleteItemAt().
void MusicDownloadRecordWidget::createDownloadItem (const QString & name, qint64 time) slot
Create download item from download name and total time.
Definition at line 146 of file musicdownloadrecordwidget.cpp.
References createItem(), m_musicRecords, MusicDownloadRecord::m_name, MusicDownloadRecord::m_path, MusicDownloadRecord::m_size, and MusicUtils::Core::musicPrefix().
void MusicDownloadRecordWidget::createItem (int index, const MusicDownloadRecord & record, qint64 time) protected
Create item by index and name and size and time.
Definition at line 186 of file musicdownloadrecordwidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicDownloadRecord::m_name, MusicDownloadRecord::m_path, MusicDownloadRecord::m_size, MusicUIObject::MColorStyle12_S, MUSIC_PROCS_ROLE, and MUSIC_TIMES_ROLE.
Referenced by createDownloadItem(), and musicSongsFileName().
void MusicDownloadRecordWidget::downloadProgressChanged (float percent, const QString & total, qint64 time) slot
Update download percent\ total time and current time progress.
Definition at line 127 of file musicdownloadrecordwidget.cpp.
References m_loadRecordCount, m_musicRecords, MUSIC_PROCS_ROLE, and MUSIC_TIMES_ROLE.
QString MusicDownloadRecordWidget::getClassName () static
Get class object name.
Definition at line 46 of file musicdownloadrecordwidget.cpp.
Referenced by MusicConnectionPool::connectMusicDownload(), MusicDownloadRecordWidget(), MusicConnectionPool::poolConnect(), and ~MusicDownloadRecordWidget().
void MusicDownloadRecordWidget::listCellClicked (int row, int column) slot
Table widget list cell click.
Definition at line 113 of file musicdownloadrecordwidget.cpp.
void MusicDownloadRecordWidget::listCellDoubleClicked (int row, int column) slot
Table widget list cell double click.
Definition at line 119 of file musicdownloadrecordwidget.cpp.
References musicPlay().
Referenced by MusicDownloadRecordWidget().
void MusicDownloadRecordWidget::musicPlay () slot
Add selected music song path to list.
Definition at line 76 of file musicdownloadrecordwidget.cpp.
References addSongToPlay(), and m_musicRecords.
Referenced by listCellDoubleClicked().
void MusicDownloadRecordWidget::musicSongsFileName ()
Read all config from file and insert items.
Definition at line 51 of file musicdownloadrecordwidget.cpp.
References createItem(), DEFAULT_INDEX_LEVEL1, m_loadRecordCount, m_musicRecords, MusicSongsListAbstractTableWidget::m_musicSongs, MusicDownloadRecordConfigManager::Normal, MusicDownloadRecordConfigManager::readDownloadConfig(), and MusicDownloadRecordConfigManager::readDownloadXMLConfig().
Referenced by MusicDownloadRecordWidget().
void MusicDownloadRecordWidget::setDeleteItemAt () override virtual slot
Delete item from list at current row.
Definition at line 87 of file musicdownloadrecordwidget.cpp.
References MusicMessageBox::exec(), m_loadRecordCount, m_musicRecords, and MusicMessageBox::setText().
Referenced by contextMenuEvent().
Member Data Documentation
MusicProgressBarDelegate* MusicDownloadRecordWidget::m_delegate protected
Definition at line 86 of file musicdownloadrecordwidget.h.
Referenced by MusicDownloadRecordWidget(), and ~MusicDownloadRecordWidget().
int MusicDownloadRecordWidget::m_loadRecordCount protected
Definition at line 88 of file musicdownloadrecordwidget.h.
Referenced by downloadProgressChanged(), musicSongsFileName(), and setDeleteItemAt().
MusicDownloadRecords MusicDownloadRecordWidget::m_musicRecords protected
Definition at line 87 of file musicdownloadrecordwidget.h.
Referenced by createDownloadItem(), downloadProgressChanged(), musicPlay(), musicSongsFileName(), setDeleteItemAt(), and ~MusicDownloadRecordWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicdownloadrecordwidget.h
TTKModule/TTKWidget/musicToolsKits/musicdownloadrecordwidget.cpp