TTKMusicPlayer: MusicBackgroundPalette Class Reference
MusicBackgroundPalette Class Reference
The class of the background palette label.
#include <musicbackgroundpalettewidget.h>
Signals
void currentColorToFileChanged (const QColor &color)
void currentColorToMemoryChanged (const QString &path)
Public Member Functions
MusicBackgroundPalette (QWidget *parent=nullptr)
~MusicBackgroundPalette ()
void setPixmap (const QColor &color)
Private Member Functions
virtual void enterEvent (QtEnterEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
void copyColorToMemory (const QColor &color)
Private Attributes
QColor m_color
Detailed Description
The class of the background palette label.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicbackgroundpalettewidget.h.
Constructor & Destructor Documentation
MusicBackgroundPalette::MusicBackgroundPalette (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicbackgroundpalettewidget.cpp.
MusicBackgroundPalette::~MusicBackgroundPalette ()
Definition at line 18 of file musicbackgroundpalettewidget.cpp.
References MUSIC_COLOR_FILE.
Member Function Documentation
void MusicBackgroundPalette::copyColorToMemory (const QColor & color) private
Copy color to memory.
Definition at line 30 of file musicbackgroundpalettewidget.cpp.
References currentColorToMemoryChanged(), and MUSIC_COLOR_FILE.
Referenced by enterEvent().
void MusicBackgroundPalette::currentColorToFileChanged (const QColor & color) signal
Current color confirm changed.
Referenced by mousePressEvent().
void MusicBackgroundPalette::currentColorToMemoryChanged (const QString & path) signal
Current color memory confirm changed.
Referenced by copyColorToMemory().
void MusicBackgroundPalette::enterEvent (QtEnterEvent * event) final override private virtual
Override the widget event.
Definition at line 40 of file musicbackgroundpalettewidget.cpp.
References copyColorToMemory(), and m_color.
void MusicBackgroundPalette::mousePressEvent (QMouseEvent * event) final override private virtual
Definition at line 46 of file musicbackgroundpalettewidget.cpp.
References currentColorToFileChanged(), and m_color.
void MusicBackgroundPalette::setPixmap (const QColor & color)
Set current label background by color.
Definition at line 23 of file musicbackgroundpalettewidget.cpp.
References m_color.
Referenced by MusicBackgroundPaletteWidget::MusicBackgroundPaletteWidget().
Member Data Documentation
QColor MusicBackgroundPalette::m_color private
Definition at line 69 of file musicbackgroundpalettewidget.h.
Referenced by enterEvent(), mousePressEvent(), and setPixmap().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundpalettewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundpalettewidget.cpp