TTKMusicPlayer: MusicHlPalette Class Reference
MusicHlPalette Class Reference
The class of the color hl palette.
#include <musiccolordialog.h>
Public Slots
void setSaturation (double dblsaturation)
Signals
void colorChanged (const QColor &color)
Public Member Functions
MusicHlPalette (QWidget *parent=nullptr)
QColor color () const noexcept
void setColor (const QColor &color)
void initialize ()
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void resizeEvent (QResizeEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
void calculateColor ()
Private Attributes
QPoint m_ptVernierPos
QPointF m_ptfVernierPercentPos
QColor m_color
double m_dblSaturation
Detailed Description
The class of the color hl palette.
Author
ToDo 27848.nosp@m.8569.nosp@m.@qq.c.nosp@m.om
Definition at line 27 of file musiccolordialog.h.
Constructor & Destructor Documentation
MusicHlPalette::MusicHlPalette (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 8 of file musiccolordialog.cpp.
Member Function Documentation
void MusicHlPalette::calculateColor () private
Calculate current color.
Definition at line 126 of file musiccolordialog.cpp.
References colorChanged(), m_color, m_dblSaturation, m_ptfVernierPercentPos, m_ptVernierPos, and TTKStaticCast.
Referenced by initialize(), mouseMoveEvent(), mousePressEvent(), and setSaturation().
QColor MusicHlPalette::color () const noexcept
Get color.
Definition at line 16 of file musiccolordialog.cpp.
References m_color.
Referenced by setColor().
void MusicHlPalette::colorChanged (const QColor & color) signal
Current color has changed.
Referenced by calculateColor(), and setColor().
void MusicHlPalette::initialize ()
Init widget and parameter.
Definition at line 36 of file musiccolordialog.cpp.
References calculateColor(), and m_ptVernierPos.
void MusicHlPalette::mouseMoveEvent (QMouseEvent * event) final override private virtual
Definition at line 103 of file musiccolordialog.cpp.
References calculateColor(), and m_ptVernierPos.
void MusicHlPalette::mousePressEvent (QMouseEvent * event) final override private virtual
Definition at line 93 of file musiccolordialog.cpp.
References calculateColor(), and m_ptVernierPos.
void MusicHlPalette::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 50 of file musiccolordialog.cpp.
References m_dblSaturation, and m_ptVernierPos.
void MusicHlPalette::resizeEvent (QResizeEvent * event) final override private virtual
Definition at line 85 of file musiccolordialog.cpp.
References m_ptfVernierPercentPos, and m_ptVernierPos.
void MusicHlPalette::setColor (const QColor & color)
Get color.
Definition at line 21 of file musiccolordialog.cpp.
References color(), colorChanged(), m_color, m_dblSaturation, and m_ptfVernierPercentPos.
void MusicHlPalette::setSaturation (double dblsaturation) slot
Set current color saturation.
Definition at line 43 of file musiccolordialog.cpp.
References calculateColor(), and m_dblSaturation.
Member Data Documentation
QColor MusicHlPalette::m_color private
Definition at line 77 of file musiccolordialog.h.
Referenced by calculateColor(), color(), and setColor().
double MusicHlPalette::m_dblSaturation private
Definition at line 78 of file musiccolordialog.h.
Referenced by calculateColor(), paintEvent(), setColor(), and setSaturation().
QPointF MusicHlPalette::m_ptfVernierPercentPos private
Definition at line 76 of file musiccolordialog.h.
Referenced by calculateColor(), resizeEvent(), and setColor().
QPoint MusicHlPalette::m_ptVernierPos private
Definition at line 75 of file musiccolordialog.h.
Referenced by calculateColor(), initialize(), mouseMoveEvent(), mousePressEvent(), paintEvent(), and resizeEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musiccolordialog.h
TTKModule/TTKWidget/musicCoreKits/musiccolordialog.cpp