TTKMusicplayer: MusicCodeAreaWidget Class Reference
MusicCodeAreaWidget Class Reference
The class of the label show code area widget.
#include <musiccodeareawidget.h>
Public Member Functions
MusicCodeAreaWidget (QWidget *parent=nullptr)
void renderPicture ()
QString getCheckCode () const
void setCodeCount (int nCount)
int getCodeCount () const
void setNoisyPointCount (int nCount)
int getNoisyPointCount () const
Public Member Functions inherited from MusicClickedLabel
MusicClickedLabel (QWidget *parent=nullptr)
MusicClickedLabel (const QString &text, QWidget *parent=nullptr)
Protected Member Functions
void drawOutline (QPainter &painter)
void drawNoisyPoint (QPainter &painter)
void drawConversion (QPainter &painter)
virtual void paintEvent (QPaintEvent *event) override
Protected Member Functions inherited from MusicClickedLabel
virtual void mousePressEvent (QMouseEvent *event) override
Protected Attributes
int m_nNoisyPointCount
int m_nConverseRotate
int m_nConverseScale
int m_nCodeCount
QString m_sCode
QStringList m_slCodeRange
QList< QPainterPath > m_lCodePic
QList< Qt::GlobalColor > m_lCodeColor
Additional Inherited Members
Signals inherited from MusicClickedLabel
void clicked ()
Detailed Description
The class of the label show code area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musiccodeareawidget.h.
Constructor & Destructor Documentation
MusicCodeAreaWidget::MusicCodeAreaWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musiccodeareawidget.cpp.
References DEF_CODECOUNT, DEF_CONVERSEROTATE, DEF_CONVERSESCALE, DEF_NOISYPOINTCOUNT, MusicTime::initRandom(), m_lCodeColor, m_nCodeCount, m_nConverseRotate, m_nConverseScale, m_nNoisyPointCount, and m_slCodeRange.
Member Function Documentation
void MusicCodeAreaWidget::drawConversion (QPainter & painter) protected
Draw conversion.
Definition at line 109 of file musiccodeareawidget.cpp.
References m_nConverseRotate, m_nConverseScale, and MusicTime::random().
Referenced by paintEvent().
void MusicCodeAreaWidget::drawNoisyPoint (QPainter & painter) protected
Draw noisy point.
Definition at line 97 of file musiccodeareawidget.cpp.
References m_nNoisyPointCount, and MusicTime::random().
Referenced by paintEvent().
void MusicCodeAreaWidget::drawOutline (QPainter & painter) protected
Draw outline pie.
Definition at line 89 of file musiccodeareawidget.cpp.
Referenced by paintEvent().
QString MusicCodeAreaWidget::getCheckCode () const inline
Get the verify code string.
Definition at line 46 of file musiccodeareawidget.h.
int MusicCodeAreaWidget::getCodeCount () const inline
Get the verify code count length.
Definition at line 55 of file musiccodeareawidget.h.
int MusicCodeAreaWidget::getNoisyPointCount () const inline
Get the noisy point count.
Definition at line 64 of file musiccodeareawidget.h.
void MusicCodeAreaWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 66 of file musiccodeareawidget.cpp.
References drawConversion(), drawNoisyPoint(), drawOutline(), m_lCodeColor, m_lCodePic, and MusicTime::random().
void MusicCodeAreaWidget::renderPicture ()
Render the verify code picture.
Definition at line 30 of file musiccodeareawidget.cpp.
References m_lCodePic, m_nCodeCount, m_sCode, m_slCodeRange, and MusicTime::random().
void MusicCodeAreaWidget::setCodeCount (int nCount)
Set the verify code count length.
Definition at line 56 of file musiccodeareawidget.cpp.
References m_nCodeCount.
void MusicCodeAreaWidget::setNoisyPointCount (int nCount)
Set the noisy point count.
Definition at line 61 of file musiccodeareawidget.cpp.
References m_nNoisyPointCount.
Member Data Documentation
QList<Qt::GlobalColor> MusicCodeAreaWidget::m_lCodeColor protected
Definition at line 89 of file musiccodeareawidget.h.
Referenced by MusicCodeAreaWidget(), and paintEvent().
QList<QPainterPath> MusicCodeAreaWidget::m_lCodePic protected
Definition at line 88 of file musiccodeareawidget.h.
Referenced by paintEvent(), and renderPicture().
int MusicCodeAreaWidget::m_nCodeCount protected
Definition at line 85 of file musiccodeareawidget.h.
Referenced by MusicCodeAreaWidget(), renderPicture(), and setCodeCount().
int MusicCodeAreaWidget::m_nConverseRotate protected
Definition at line 84 of file musiccodeareawidget.h.
Referenced by drawConversion(), and MusicCodeAreaWidget().
int MusicCodeAreaWidget::m_nConverseScale protected
Definition at line 85 of file musiccodeareawidget.h.
Referenced by drawConversion(), and MusicCodeAreaWidget().
int MusicCodeAreaWidget::m_nNoisyPointCount protected
Definition at line 84 of file musiccodeareawidget.h.
Referenced by drawNoisyPoint(), MusicCodeAreaWidget(), and setNoisyPointCount().
QString MusicCodeAreaWidget::m_sCode protected
Definition at line 86 of file musiccodeareawidget.h.
Referenced by renderPicture().
QStringList MusicCodeAreaWidget::m_slCodeRange protected
Definition at line 87 of file musiccodeareawidget.h.
Referenced by MusicCodeAreaWidget(), and renderPicture().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musiccodeareawidget.h
TTKModule/TTKWidget/musicCoreKits/musiccodeareawidget.cpp