TTKMusicPlayer: QGlobalShortcutPrivate Class Reference
QGlobalShortcutPrivate Class Reference
The class of the qglobal shortcut private.
#include <qglobalshortcut_p.h>
Public Member Functions
QGlobalShortcutPrivate ()
~QGlobalShortcutPrivate ()
bool setShortcut (const QKeySequence &shortcut)
bool unsetShortcut ()
Public Member Functions inherited from TTKPrivate< QGlobalShortcut >
TTKPrivate ()
virtual ~TTKPrivate ()=default
void setPublic (QGlobalShortcut *pub)
Static Public Member Functions
static bool eventFilter (void *message)
Public Attributes
bool m_enabled
Qt::Key m_key
Qt::KeyboardModifiers m_mods
Static Public Attributes
static int m_ref = 0
static bool m_error = false
static QAbstractEventDispatcher::EventFilter m_prevEventFilter = 0
Static Private Member Functions
static quint32 nativeKeycode (Qt::Key keycode)
static quint32 nativeModifiers (Qt::KeyboardModifiers modifiers)
static bool registerShortcut (quint32 nativeKey, quint32 nativeMods)
static bool unregisterShortcut (quint32 nativeKey, quint32 nativeMods)
static void activateShortcut (quint32 nativeKey, quint32 nativeMods)
Static Private Attributes
static QHash< QPair< quint32, quint32 >, QGlobalShortcut * > m_shortcuts
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QGlobalShortcut >
QGlobalShortcut * ttk_q () const
Detailed Description
The class of the qglobal shortcut private.
Author
libqxt found.nosp@m.atio.nosp@m.n@lib.nosp@m.qxt..nosp@m.org
Definition at line 32 of file qglobalshortcut_p.h.
Constructor & Destructor Documentation
QGlobalShortcutPrivate::QGlobalShortcutPrivate ()
Definition at line 12 of file qglobalshortcut.cpp.
References eventFilter(), m_prevEventFilter, and m_ref.
QGlobalShortcutPrivate::~QGlobalShortcutPrivate ()
Definition at line 27 of file qglobalshortcut.cpp.
References m_prevEventFilter, and m_ref.
Member Function Documentation
void QGlobalShortcutPrivate::activateShortcut (quint32 nativeKey, quint32 nativeMods) static private
Definition at line 92 of file qglobalshortcut.cpp.
References QGlobalShortcut::activated(), QGlobalShortcut::isEnabled(), and m_shortcuts.
Referenced by eventFilter().
bool QGlobalShortcutPrivate::eventFilter (void * message) static
Definition at line 21 of file qglobalshortcut_mac.cpp.
References activateShortcut(), and keyIDs.
Referenced by QGlobalShortcutPrivate().
quint32 QGlobalShortcutPrivate::nativeKeycode (Qt::Key keycode) static private
Definition at line 65 of file qglobalshortcut_mac.cpp.
References key, TTKConstCast, and TTKReinterpretCast.
Referenced by setShortcut(), and unsetShortcut().
quint32 QGlobalShortcutPrivate::nativeModifiers (Qt::KeyboardModifiers modifiers) static private
Definition at line 49 of file qglobalshortcut_mac.cpp.
Referenced by setShortcut(), and unsetShortcut().
bool QGlobalShortcutPrivate::registerShortcut (quint32 nativeKey, quint32 nativeMods) static private
Definition at line 163 of file qglobalshortcut_mac.cpp.
References hotKeySerial, keyIDs, keyRefs, q_mac_handle_hot_key(), and q_mac_handler_installed.
Referenced by setShortcut().
bool QGlobalShortcutPrivate::setShortcut (const QKeySequence & shortcut)
Definition at line 39 of file qglobalshortcut.cpp.
References key, m_key, m_mods, m_shortcuts, nativeKeycode(), nativeModifiers(), QtKeyCombine, QtKeySequence, registerShortcut(), and TTKPrivate< QGlobalShortcut >::ttk_q().
bool QGlobalShortcutPrivate::unregisterShortcut (quint32 nativeKey, quint32 nativeMods) static private
Definition at line 188 of file qglobalshortcut_mac.cpp.
References keyIDs, and keyRefs.
Referenced by unsetShortcut().
bool QGlobalShortcutPrivate::unsetShortcut ()
Definition at line 65 of file qglobalshortcut.cpp.
References key, m_key, m_mods, m_shortcuts, nativeKeycode(), nativeModifiers(), QtKeySequence, and unregisterShortcut().
Member Data Documentation
bool QGlobalShortcutPrivate::m_enabled
Definition at line 42 of file qglobalshortcut_p.h.
bool QGlobalShortcutPrivate::m_error = false static
Definition at line 50 of file qglobalshortcut_p.h.
Qt::Key QGlobalShortcutPrivate::m_key
Definition at line 43 of file qglobalshortcut_p.h.
Referenced by setShortcut(), and unsetShortcut().
Qt::KeyboardModifiers QGlobalShortcutPrivate::m_mods
Definition at line 44 of file qglobalshortcut_p.h.
Referenced by setShortcut(), and unsetShortcut().
QAbstractEventDispatcher::EventFilter QGlobalShortcutPrivate::m_prevEventFilter = 0 static
Definition at line 52 of file qglobalshortcut_p.h.
Referenced by QGlobalShortcutPrivate(), and ~QGlobalShortcutPrivate().
int QGlobalShortcutPrivate::m_ref = 0 static
Definition at line 49 of file qglobalshortcut_p.h.
Referenced by QGlobalShortcutPrivate(), and ~QGlobalShortcutPrivate().
QHash< QPair< quint32, quint32 >, QGlobalShortcut * > QGlobalShortcutPrivate::m_shortcuts static private
Definition at line 65 of file qglobalshortcut_p.h.
Referenced by activateShortcut(), setShortcut(), and unsetShortcut().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut_p.h
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut.cpp
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut_mac.cpp
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut_win.cpp
TTKThirdParty/TTKExtras/qshortcut/qglobalshortcut_x11.cpp