TTKMusicplayer: QSyncConfig Struct Reference
QSyncConfig Struct Reference
The class of the sync data config.
#include <qsyncconfig.h>
Static Public Attributes
static QString HOST = QString("<Your Host Key>")
static QString NAME = QString("<Your Name Key>")
static QByteArray KEY = QByteArray("<Your Key>")
static QString VERSION = QString("1.0.0")
Detailed Description
The class of the sync data config.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file qsyncconfig.h.
Member Data Documentation
QString QSyncConfig::HOST = QString("<Your Host Key>") static
Definition at line 32 of file qsyncconfig.h.
Referenced by QSyncDeleteData::deleteDataOperator(), QSyncDownloadData::downloadDataOperator(), QSyncDownloadData::downloadUrl(), QSyncListData::listDataOperator(), MusicApplicationModule::loadNetWorkSetting(), QSyncUtils::makeDataBucketUrl(), and QSyncUploadData::uploadDataOperator().
QByteArray QSyncConfig::KEY = QByteArray("<Your Key>") static
Definition at line 34 of file qsyncconfig.h.
Referenced by MusicCloudManagerTableWidget::downLoadFinished(), QSyncDownloadData::downloadUrl(), QSyncDataInterfacePrivate::insertAuthorization(), and MusicCloudManagerTableWidget::queryCloudKey().
QString QSyncConfig::NAME = QString("<Your Name Key>") static
Definition at line 33 of file qsyncconfig.h.
Referenced by MusicCloudManagerTableWidget::downLoadFinished(), QSyncDownloadData::downloadUrl(), QSyncDataInterfacePrivate::insertAuthorization(), and MusicCloudManagerTableWidget::queryCloudKey().
QString QSyncConfig::VERSION = QString("1.0.0") static
Definition at line 35 of file qsyncconfig.h.
The documentation for this struct was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncconfig.h
TTKThirdParty/TTKExtras/qsync/qsyncconfig.cpp