TTKMusicPlayer: ReqWYInterface Namespace Reference
ReqWYInterface Namespace Reference
The namespace of the wangyi request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request)
QString makeSongArtist (const QString &in, const QString &name)
QString makeCoverPixmapUrl (const QString &url)
QByteArray makeTokenRequest (QNetworkRequest *request, const QString &query, const QString &type)
void parseFromSongProperty (TTK::MusicSongInformation *info, int bitrate)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QVariantMap &key)
static void parseFromMovieProperty (QString &url, const QString &id, int bitrate)
Detailed Description
The namespace of the wangyi request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
QString ReqWYInterface::makeCoverPixmapUrl (const QString & url)
Make cover pixmap url.
Definition at line 23 of file musicwyqueryinterface.cpp.
References TTK::Algorithm::mdII().
Referenced by MusicWYQueryArtistAlbumRequest::downLoadFinished().
void ReqWYInterface::makeRequestRawHeader (QNetworkRequest * request)
Make request query data.
Definition at line 7 of file musicwyqueryinterface.cpp.
References ALG_UA_KEY, TTK::makeContentTypeHeader(), TTK::Algorithm::mdII(), TTK::setSslConfiguration(), WY_BASE_URL, WY_COOKIE_URL, WY_NMTID_URL, and WY_UA_URL.
Referenced by makeTokenRequest(), and parseSongProperty().
QString ReqWYInterface::makeSongArtist (const QString & in, const QString & name)
Make song artist name.
Definition at line 17 of file musicwyqueryinterface.cpp.
References TTK::String::charactersReplace().
Referenced by MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicFMRadioSongRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicWYQueryRequest::downLoadSingleFinished(), MusicWYQueryMovieRequest::parseFromMovieList(), and MusicWYQueryMovieRequest::parseFromVideoList().
QByteArray ReqWYInterface::makeTokenRequest (QNetworkRequest * request, const QString & query, const QString & type)
Make token query request.
Definition at line 28 of file musicwyqueryinterface.cpp.
References QAlgorithm::Aes::encryptCBC(), makeRequestRawHeader(), TTK::Url::urlEncode(), and WY_SECKRY_STRING.
Referenced by MusicWYQueryArtistMovieRequest::parseFromArtistMoviesCount(), MusicWYQueryMovieRequest::parseFromMovieList(), parseFromMovieProperty(), MusicWYQueryMovieRequest::parseFromVideoList(), parseSongPropertyNew(), MusicWYQueryArtistRequest::queryArtistIntro(), MusicWYSongCommentsRequest::startToPage(), MusicWYQueryPlaylistRequest::startToPage(), MusicWYQueryAlbumRequest::startToPage(), MusicWYQueryRequest::startToPage(), MusicWYQueryToplistRequest::startToPage(), MusicWYQueryMovieRequest::startToPage(), MusicWYQueryArtistListRequest::startToPage(), MusicWYQueryArtistRequest::startToPage(), MusicWYPlaylistCommentsRequest::startToPage(), MusicWYQueryArtistAlbumRequest::startToPage(), MusicWYQueryArtistMovieRequest::startToPage(), MusicWYQueryPlaylistRequest::startToQueryInfo(), MusicDJRadioCategoryRequest::startToRequest(), MusicFMRadioSongRequest::startToRequest(), MusicDJRadioProgramRequest::startToRequest(), MusicWYDiscoverListRequest::startToSearch(), MusicWYQueryPlaylistRequest::startToSearch(), MusicDJRadioProgramCategoryRequest::startToSearch(), and MusicWYQueryRequest::startToSearchByID().
void ReqWYInterface::parseFromMovieProperty (QString & url, const QString & id, int bitrate) static
Start to get video url path.
Definition at line 12 of file musicwyquerymovierequest.cpp.
References makeTokenRequest(), TTK::Algorithm::mdII(), QJson::Parser::parse(), qAsConst, TTK::syncNetworkQueryForPost(), WY_VIDEO_PATH_DATA_URL, and WY_VIDEO_PATH_URL.
Referenced by MusicWYQueryMovieRequest::parseFromVideoList().
void ReqWYInterface::parseFromSongProperty (TTK::MusicSongInformation * info, int bitrate)
Read tags(size) from query results.
Definition at line 172 of file musicwyqueryinterface.cpp.
References TTK::MusicSongInformation::m_formatProps, TTK::MusicSongInformation::m_songId, parseSongProperty(), TTK_BN_0, TTK_BN_1000, TTK_BN_128, TTK_BN_192, and TTK_BN_320.
Referenced by MusicWYQueryPlaylistRequest::downloadDetailsFinished(), MusicDJRadioProgramCategoryRequest::downloadDetailsFinished(), MusicWYQueryArtistRequest::downLoadFinished(), MusicWYQueryAlbumRequest::downLoadFinished(), MusicFMRadioSongRequest::downLoadFinished(), MusicWYQueryRequest::downLoadFinished(), MusicWYQueryToplistRequest::downLoadFinished(), MusicWYQueryRequest::downLoadSingleFinished(), MusicWYQueryAlbumRequest::startToQueryResult(), MusicWYQueryArtistRequest::startToQueryResult(), MusicWYQueryRequest::startToQueryResult(), MusicWYQueryToplistRequest::startToQueryResult(), MusicDJRadioProgramCategoryRequest::startToQueryResult(), and MusicWYQueryPlaylistRequest::startToQueryResult().
void ReqWYInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QVariantMap & key)
Read tags(size) from query results.
Definition at line 217 of file musicwyqueryinterface.cpp.
References TTK::MusicSongInformation::m_formatProps, TTK_BN_1000, TTK_BN_128, TTK_BN_192, and TTK_BN_320.