TTKMusicplayer: ToolsSkin Class Reference
ToolsSkin Class Reference
#include <toolsskin.h>
Public Member Functions
ToolsSkin (QWidget *parent=nullptr)
~ToolsSkin ()
Protected Attributes
Ui::ToolsSkin * m_ui
QPixmap m_pixmap
Private Slots
void imageClicked ()
void paletteClicked ()
void readClicked ()
void writeClicked ()
Detailed Description
Definition at line 28 of file toolsskin.h.
Constructor & Destructor Documentation
ToolsSkin::ToolsSkin (QWidget * parent = nullptr) explicit
Definition at line 8 of file toolsskin.cpp.
References imageClicked(), m_pixmap, m_ui, paletteClicked(), readClicked(), and writeClicked().
ToolsSkin::~ToolsSkin ()
Definition at line 25 of file toolsskin.cpp.
References m_ui.
Member Function Documentation
void ToolsSkin::imageClicked () private slot
Definition at line 30 of file toolsskin.cpp.
References m_pixmap, m_ui, and MusicUtils::File::openFileDialog().
Referenced by ToolsSkin().
void ToolsSkin::paletteClicked () private slot
Definition at line 42 of file toolsskin.cpp.
References m_pixmap, m_ui, and MusicColorDialog::popup().
Referenced by ToolsSkin().
void ToolsSkin::readClicked () private slot
Definition at line 55 of file toolsskin.cpp.
References MusicBackgroundImage::m_item, MusicSkinItem::m_name, MusicBackgroundImage::m_pix, m_pixmap, m_ui, MusicSkinItem::m_useCount, MusicUtils::File::openFileDialog(), and MusicExtractWrapper::outputSkin().
Referenced by ToolsSkin().
void ToolsSkin::writeClicked () private slot
Definition at line 73 of file toolsskin.cpp.
References MusicExtractWrapper::inputSkin(), MusicBackgroundImage::m_item, MusicSkinItem::m_name, MusicBackgroundImage::m_pix, m_pixmap, m_ui, MusicSkinItem::m_useCount, MusicUtils::File::saveFileDialog(), and TTK_LOGGER_INFO.
Referenced by ToolsSkin().
Member Data Documentation
QPixmap ToolsSkin::m_pixmap protected
Definition at line 43 of file toolsskin.h.
Referenced by imageClicked(), paletteClicked(), readClicked(), ToolsSkin(), and writeClicked().
Ui::ToolsSkin* ToolsSkin::m_ui protected
Definition at line 42 of file toolsskin.h.
Referenced by imageClicked(), paletteClicked(), readClicked(), ToolsSkin(), writeClicked(), and ~ToolsSkin().
The documentation for this class was generated from the following files:
TTKRun/TTKTools/GenerateSkin/toolsskin.h
TTKRun/TTKTools/GenerateSkin/toolsskin.cpp