TTKMusicPlayer: MusicKWInterface Namespace Reference
MusicKWInterface Namespace Reference
The namespace of the kuwo request interface.
Functions
void makeRequestRawHeader (QNetworkRequest *request)
void makeCoverPixmapUrl (QString &url)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QString &bitrate, QString &url)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QString &format, TTK::QueryQuality quality, bool all)
void parseFromSongProperty (TTK::MusicSongInformation *info, const QVariantList &format, TTK::QueryQuality quality, bool all)
Detailed Description
The namespace of the kuwo request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void MusicKWInterface::makeCoverPixmapUrl (QString & url)
Make cover pixmap url.
Definition at line 43 of file musickwqueryinterface.cpp.
References TTK::String::isNetworkUrl(), KW_ALBUM_COVER_URL, and TTK::Algorithm::mdII().
Referenced by MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), and MusicKWQueryAlbumRequest::downLoadSingleFinished().
void MusicKWInterface::makeRequestRawHeader (QNetworkRequest * request)
Make request query data.
Definition at line 6 of file musickwqueryinterface.cpp.
References ALG_UA_KEY, KW_UA_URL, TTK::Algorithm::mdII(), and TTK::setSslConfiguration().
Referenced by MusicKWQueryPlaylistRequest::morePlaylistDetails(), MusicKWQueryMovieRequest::parseFromMovieInfo(), MusicKWQueryMovieRequest::parseFromMovieProperty(), parseFromSongProperty(), MusicKWQueryArtistRequest::queryArtistIntro(), MusicKWQueryPlaylistRequest::queryPlaylistInfo(), MusicKWQueryToplistRequest::queryToplistInfo(), MusicKWSongCommentsRequest::startToPage(), MusicKWQueryRequest::startToPage(), MusicKWQueryMovieRequest::startToPage(), MusicKWQueryArtistListRequest::startToPage(), MusicKWQueryPlaylistRequest::startToPage(), MusicKWPlaylistCommentsRequest::startToPage(), MusicKWDiscoverListRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSearch(), MusicKWQueryArtistRequest::startToSearch(), MusicKWQueryToplistRequest::startToSearch(), MusicKWQueryMovieRequest::startToSearch(), MusicKWQueryPlaylistRequest::startToSearch(), MusicKWQueryAlbumRequest::startToSingleSearch(), and MusicKWQueryRequest::startToSingleSearch().
void MusicKWInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QString & bitrate, QString & url)
Read tags(size) from query results.
Definition at line 12 of file musickwqueryinterface.cpp.
References KW_SONG_DETAIL_URL, TTK::MusicSongInformation::m_songId, makeRequestRawHeader(), TTK::Algorithm::mdII(), QJson::Parser::parse(), and TTK::syncNetworkQueryForGet().
Referenced by MusicKWQueryPlaylistRequest::downloadDetailsFinished(), MusicKWQueryArtistRequest::downLoadFinished(), MusicKWQueryAlbumRequest::downLoadFinished(), MusicKWQueryToplistRequest::downLoadFinished(), MusicKWQueryRequest::downLoadFinished(), and MusicKWQueryRequest::downLoadSingleFinished().
void MusicKWInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate)
Read tags(size) from query results.
Definition at line 51 of file musickwqueryinterface.cpp.
References TTK::MusicSongProperty::m_bitrate, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, MB_128, MB_192, MB_320, MP3_FILE_SUFFIX, MusicKGInterface::parseFromSongProperty(), TTK::String::suffix(), and TTK_DEFAULT_STR.
void MusicKWInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QString & format, TTK::QueryQuality quality, bool all)
Read tags(size) from query results.
Definition at line 82 of file musickwqueryinterface.cpp.
References MB_128, MP3_FILE_SUFFIX, MusicKGInterface::parseFromSongProperty(), and TTK::Standard.
void MusicKWInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QVariantList & format, TTK::QueryQuality quality, bool all)
Read tags(size) from query results.
Definition at line 114 of file musickwqueryinterface.cpp.
References MusicKGInterface::parseFromSongProperty().