TTKMusicplayer: QNConf Class Reference
QNConf Class Reference
The namespace of the qiniu config.
#include <qnconf.h>
Static Public Attributes
static QString UPLOAD_HOST = QString("http://upload.qiniu.com")
static QString RS_HOST = QString("http://rs.qbox.me")
static QString RSF_HOST = QString("http://rsf.qbox.me")
static QString IOVIP_HOST = QString("http://iovip.qbox.me")
static QString ACCESS_KEY = QString("<Your Access Key>")
static QByteArray SECRET_KEY = QByteArray("<Your Secret Key>")
static QString DEFAULT_STYLE_DELIMITER = QString("-")
static QString VERSION = QString("1.0.0")
Detailed Description
The namespace of the qiniu config.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 28 of file qnconf.h.
Member Data Documentation
QString QNConf::ACCESS_KEY = QString("<Your Access Key>") static
Definition at line 36 of file qnconf.h.
Referenced by QNSimpleDeleteData::deleteDataToServer(), QNIOHelper::deleteRequest(), QNSimpleUploadData::getDownloadUrl(), MusicCloudSharedSongTableWidget::getKey(), MusicCloudSharedSongTableWidget::keyDownLoadFinished(), QNSimpleListData::listDataToServer(), QNIOHelper::listRequest(), QNPutPolicy::makeDownloadToken(), QNPutPolicy::makeUploadToken(), and QNSimpleUploadData::uploadDataToServer().
QString QNConf::DEFAULT_STYLE_DELIMITER = QString("-") static
Definition at line 39 of file qnconf.h.
QString QNConf::IOVIP_HOST = QString("http://iovip.qbox.me") static
Definition at line 34 of file qnconf.h.
QString QNConf::RS_HOST = QString("http://rs.qbox.me") static
Definition at line 32 of file qnconf.h.
Referenced by QNIOHelper::deleteRequest().
QString QNConf::RSF_HOST = QString("http://rsf.qbox.me") static
Definition at line 33 of file qnconf.h.
Referenced by QNIOHelper::listRequest().
QByteArray QNConf::SECRET_KEY = QByteArray("<Your Secret Key>") static
Definition at line 37 of file qnconf.h.
Referenced by QNSimpleDeleteData::deleteDataToServer(), QNIOHelper::deleteRequest(), QNSimpleUploadData::getDownloadUrl(), MusicCloudSharedSongTableWidget::getKey(), MusicCloudSharedSongTableWidget::keyDownLoadFinished(), QNSimpleListData::listDataToServer(), QNIOHelper::listRequest(), QNPutPolicy::makeDownloadToken(), QNPutPolicy::makeUploadToken(), and QNSimpleUploadData::uploadDataToServer().
QString QNConf::UPLOAD_HOST = QString("http://upload.qiniu.com") static
Definition at line 31 of file qnconf.h.
Referenced by QNSimpleUploadData::uploadDataToServer().
QString QNConf::VERSION = QString("1.0.0") static
Definition at line 41 of file qnconf.h.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnconf.h
TTKThirdParty/TTKExtras/qiniu/qnconf.cpp