TTKMusicPlayer: MusicLrcManagerForInterior Class Reference
MusicLrcManagerForInterior Class Reference
The class of the interior lrc manager.
#include <musiclrcmanagerforinterior.h>
Public Member Functions
MusicLrcManagerForInterior (QWidget *parent=nullptr)
void setLrcPerWidth (int width)
void setFontSize (int size)
void setTransparent (int tran)
Public Member Functions inherited from MusicLrcManager
MusicLrcManager (QWidget *parent=nullptr)
~MusicLrcManager ()
void startDrawLrc ()
void startDrawLrcMask (qint64 intervaltime)
void stopDrawLrc ()
void setFontFamily (int index)
void setFontType (int type)
void setLinearGradientColor (const MusicLrcColor &color)
void setSpeedLevel (int l)
void setFontTransparent (int t)
void setSelfPosition (int x, int y)
void setSelfPosition (const QPoint &point)
int x () const
int y () const
void setX (int x)
void setY (int y)
void reset ()
void setLrcFontSize (int size)
int lrcFontSize () const
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
Private Attributes
int m_gradientFontSize
int m_gradientTransparent
Additional Inherited Members
Public Slots inherited from MusicLrcManager
void updateMask ()
void setText (const QString &str)
Protected Attributes inherited from MusicLrcManager
QFont m_font
QTimer * m_timer
QLinearGradient m_linearGradient
QLinearGradient m_maskLinearGradient
float m_lrcMaskWidth
float m_lrcMaskWidthInterval
float m_intervalCount
int m_lrcPerWidth
int m_transparent
int m_speedLevel
QPoint m_position
Detailed Description
The class of the interior lrc manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musiclrcmanagerforinterior.h.
Constructor & Destructor Documentation
MusicLrcManagerForInterior::MusicLrcManagerForInterior (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file musiclrcmanagerforinterior.cpp.
References LRC_PER_WIDTH, MusicLrcManager::m_font, MusicLrcManager::m_lrcPerWidth, MusicLrcManager::m_position, and MusicLrcManager::m_speedLevel.
Member Function Documentation
void MusicLrcManagerForInterior::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 18 of file musiclrcmanagerforinterior.cpp.
References TTK::Widget::fontTextHeight(), TTK::Widget::fontTextWidth(), G_SETTING_PTR, MusicLrcManager::m_font, m_gradientFontSize, m_gradientTransparent, MusicLrcManager::m_intervalCount, MusicLrcManager::m_linearGradient, MusicLrcManager::m_lrcMaskWidth, MusicLrcManager::m_lrcMaskWidthInterval, MusicLrcManager::m_lrcPerWidth, MusicLrcManager::m_maskLinearGradient, MusicLrcManager::m_position, and MusicSettingManager::OtherLrcKTVMode.
void MusicLrcManagerForInterior::setFontSize (int size) inline
Set adjust font size.
Definition at line 46 of file musiclrcmanagerforinterior.h.
Referenced by MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicLrcContainerForInterior::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
void MusicLrcManagerForInterior::setLrcPerWidth (int width) inline
Set lrc per width.
Definition at line 42 of file musiclrcmanagerforinterior.h.
References LRC_PER_WIDTH.
Referenced by MusicLrcContainerForWallpaper::applyParameter(), and MusicLrcMakerWidget::createThirdWidget().
void MusicLrcManagerForInterior::setTransparent (int tran) inline
Set adjust transparent by value.
Definition at line 50 of file musiclrcmanagerforinterior.h.
Referenced by MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicLrcContainerForInterior::setItemStyleSheet(), and MusicLrcMakerWidget::setItemStyleSheet().
Member Data Documentation
int MusicLrcManagerForInterior::m_gradientFontSize private
Definition at line 58 of file musiclrcmanagerforinterior.h.
Referenced by paintEvent().
int MusicLrcManagerForInterior::m_gradientTransparent private
Definition at line 59 of file musiclrcmanagerforinterior.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcmanagerforinterior.h
TTKModule/TTKWidget/musicLrcKits/musiclrcmanagerforinterior.cpp