TTKMusicplayer: MusicWebRadioView Class Reference
MusicWebRadioView Class Reference
The class of the web radio widget.
#include <musicwebradioview.h>
Public Slots
void openFMRadioWindow ()
void openDJRadioWindow ()
void openMVRadioWindow ()
Public Member Functions
MusicWebRadioView (QWidget *parent=nullptr)
~MusicWebRadioView ()
void initialize (int index)
Protected Attributes
MusicWebFMRadioWidget * m_radio
MusicTTKFMRadioPlayWidget * m_ttkRadio
Detailed Description
The class of the web radio widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicwebradioview.h.
Constructor & Destructor Documentation
MusicWebRadioView::MusicWebRadioView (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musicwebradioview.cpp.
References m_radio, m_ttkRadio, MusicUIObject::MQSSPushButtonStyle01, openDJRadioWindow(), openFMRadioWindow(), and openMVRadioWindow().
MusicWebRadioView::~MusicWebRadioView ()
Definition at line 64 of file musicwebradioview.cpp.
References m_radio, and m_ttkRadio.
Member Function Documentation
void MusicWebRadioView::initialize (int index)
To init list items.
Definition at line 70 of file musicwebradioview.cpp.
References MusicWebFMRadioWidget::initialize(), and m_radio.
Referenced by MusicLeftAreaWidget::musicStackedRadioWidgetChanged(), and MusicLeftAreaWidget::radioExecuteOutside().
void MusicWebRadioView::openDJRadioWindow () slot
Open DJ Radio window has clicked.
Definition at line 84 of file musicwebradioview.cpp.
References MusicRightAreaWidget::functionClicked(), MusicRightAreaWidget::instance(), and MusicRightAreaWidget::WebDJRadioWidget.
Referenced by MusicWebRadioView().
void MusicWebRadioView::openFMRadioWindow () slot
Open FM Radio window has clicked.
Definition at line 75 of file musicwebradioview.cpp.
References m_ttkRadio, and MusicTTKFMRadioPlayWidget::show().
Referenced by MusicWebRadioView().
void MusicWebRadioView::openMVRadioWindow () slot
Open MV Radio window has clicked.
Definition at line 89 of file musicwebradioview.cpp.
References MusicRightAreaWidget::functionClicked(), MusicRightAreaWidget::instance(), and MusicRightAreaWidget::WebMVRadioWidget.
Referenced by MusicWebRadioView().
Member Data Documentation
MusicWebFMRadioWidget* MusicWebRadioView::m_radio protected
Definition at line 62 of file musicwebradioview.h.
Referenced by initialize(), MusicWebRadioView(), and ~MusicWebRadioView().
MusicTTKFMRadioPlayWidget* MusicWebRadioView::m_ttkRadio protected
Definition at line 63 of file musicwebradioview.h.
Referenced by MusicWebRadioView(), openFMRadioWindow(), and ~MusicWebRadioView().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebradioview.h
TTKModule/TTKWidget/musicToolsKits/musicwebradioview.cpp