TTKMusicPlayer: MusicWidgetRenderer Class Reference
MusicWidgetRenderer Class Reference
The class of the widget background renderer.
#include <musicwidgetrenderer.h>
Public Member Functions
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Protected Member Functions
void setBackgroundPixmap (const QSize &size)
Private Attributes
QLabel * m_background
Detailed Description
The class of the widget background renderer.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicwidgetrenderer.h.
Constructor & Destructor Documentation
MusicWidgetRenderer::MusicWidgetRenderer ()
Object constructor.
Definition at line 6 of file musicwidgetrenderer.cpp.
Member Function Documentation
void MusicWidgetRenderer::setBackgroundLabel (QLabel * label) inline
Set background label.
Definition at line 41 of file musicwidgetrenderer.h.
Referenced by MusicBackgroundSkinDialog::MusicBackgroundSkinDialog(), MusicCloudFileInformationWidget::MusicCloudFileInformationWidget(), MusicColorDialog::MusicColorDialog(), MusicConnectTransferWidget::MusicConnectTransferWidget(), MusicDownloadBatchWidget::MusicDownloadBatchWidget(), MusicDownloadResetWidget::MusicDownloadResetWidget(), MusicDownloadWidget::MusicDownloadWidget(), MusicEqualizerDialog::MusicEqualizerDialog(), MusicFileAssociationWidget::MusicFileAssociationWidget(), MusicFileInformationWidget::MusicFileInformationWidget(), MusicInputDialog::MusicInputDialog(), MusicLrcColorWidget::MusicLrcColorWidget(), MusicLrcDownloadBatchWidget::MusicLrcDownloadBatchWidget(), MusicLrcLocalLinkWidget::MusicLrcLocalLinkWidget(), MusicLrcMakerWidget::MusicLrcMakerWidget(), MusicLrcPhotoManagerWidget::MusicLrcPhotoManagerWidget(), MusicLrcPosterWidget::MusicLrcPosterWidget(), MusicLrcSearchWidget::MusicLrcSearchWidget(), MusicMessageAboutDialog::MusicMessageAboutDialog(), MusicMessageBox::MusicMessageBox(), MusicMobileSongsManagerWidget::MusicMobileSongsManagerWidget(), MusicNetworkConnectionTestWidget::MusicNetworkConnectionTestWidget(), MusicPluginWidget::MusicPluginWidget(), MusicReplayGainWidget::MusicReplayGainWidget(), MusicSettingWidget::MusicSettingWidget(), MusicSongCheckToolsWidget::MusicSongCheckToolsWidget(), MusicSongDlnaTransferWidget::MusicSongDlnaTransferWidget(), MusicSongItemSelectedDialog::MusicSongItemSelectedDialog(), MusicSongRingtoneMaker::MusicSongRingtoneMaker(), MusicSongSharingWidget::MusicSongSharingWidget(), MusicSoundEffectsWidget::MusicSoundEffectsWidget(), MusicSpectrumWidget::MusicSpectrumWidget(), MusicTimerWidget::MusicTimerWidget(), MusicToolSetsWidget::MusicToolSetsWidget(), MusicTransformWidget::MusicTransformWidget(), MusicTTKFMRadioInformationWidget::MusicTTKFMRadioInformationWidget(), MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget(), and MusicWebFMRadioPlayWidget::MusicWebFMRadioPlayWidget().
void MusicWidgetRenderer::setBackgroundPixmap (const QSize & size) protected
Set background pixmap.
Definition at line 12 of file musicwidgetrenderer.cpp.
References G_BACKGROUND_PTR, m_background, MusicBackgroundImage::m_pix, and MusicExtractWrapper::outputSkin().
Referenced by MusicDownloadWidget::addCellItems(), MusicAbstractMoveResizePlainWidget::backgroundChanged(), MusicAbstractMoveWidget::backgroundChanged(), and MusicAbstractMoveDialog::backgroundChanged().
Member Data Documentation
QLabel* MusicWidgetRenderer::m_background private
Definition at line 50 of file musicwidgetrenderer.h.
Referenced by setBackgroundPixmap().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicwidgetrenderer.h
TTKModule/TTKWidget/musicCoreKits/musicwidgetrenderer.cpp