TTKMusicplayer: MusicWYArtistSimilarThread Class Reference
MusicWYArtistSimilarThread Class Reference
The class to query wangyi artist similar download data from net.
#include <musicwyartistsimilarthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYArtistSimilarThread (QObject *parent=0)
QJson import.
virtual void startToSearch (const QString &text) override
Public Member Functions inherited from MusicDownLoadSimilarThread
MusicDownLoadSimilarThread (QObject *parent=0)
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadSimilarThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadSimilarThread
void createSimilarItem (const MusicResultsItem &item)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to query wangyi artist similar download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwyartistsimilarthread.h.
Constructor & Destructor Documentation
MusicWYArtistSimilarThread::MusicWYArtistSimilarThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 5 of file musicwyartistsimilarthread.cpp.
Member Function Documentation
void MusicWYArtistSimilarThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 40 of file musicwyartistsimilarthread.cpp.
References MusicDownLoadSimilarThread::createSimilarItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicResultsItem::m_name, MusicNetworkAbstract::m_reply, MusicResultsItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToSearch().
QString MusicWYArtistSimilarThread::getClassName () static
Get class object name.
Definition at line 11 of file musicwyartistsimilarthread.cpp.
Referenced by downLoadFinished(), and startToSearch().
void MusicWYArtistSimilarThread::startToSearch (const QString & text) override virtual
Start to Search data from name.
Implements MusicDownLoadSimilarThread.
Definition at line 16 of file musicwyartistsimilarthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), WY_AR_SIM_DATA_N_URL, and WY_AR_SIM_N_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicwyartistsimilarthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicwyartistsimilarthread.cpp