TTKMusicPlayer: MusicKWDownloadTextRequest Class Reference
MusicKWDownloadTextRequest Class Reference
The class of the download the type of kuwo txt.
#include <musickwdownloadtextrequest.h>
Public Slots
virtual void downloadFinished () overridefinal
Public Slots inherited from MusicAbstractDownloadRequest
virtual void downloadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downloadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWDownloadTextRequest (const QString &url, const QString &path, QObject *parent=nullptr)
virtual void startToRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownloadRequest
MusicAbstractDownloadRequest (const QString &url, const QString &path, TTK::Download type, QObject *parent=nullptr)
~MusicAbstractDownloadRequest ()
virtual void deleteAll () overridefinal
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value) noexcept
const QVariant header (const QString &key) const noexcept
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downloadDataChanged (const QString &bytes)
void downloadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicAbstractDownloadRequest
QString mapCurrentQueryData () const
Protected Attributes inherited from MusicAbstractDownloadRequest
QFile * m_file
QString m_url
QString m_savePath
TTK::Download m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the download the type of kuwo txt.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickwdownloadtextrequest.h.
Constructor & Destructor Documentation
MusicKWDownloadTextRequest::MusicKWDownloadTextRequest (const QString & url, const QString & path, QObject * parent = nullptr)
Object constructor provide download url save local path and download type.
Definition at line 3 of file musickwdownloadtextrequest.cpp.
Member Function Documentation
void MusicKWDownloadTextRequest::downloadFinished () final override virtual slot
Download data from net finished.
Definition at line 32 of file musickwdownloadtextrequest.cpp.
References MusicAbstractDownloadRequest::deleteAll(), TTKAbstractNetwork::downloadDataChanged(), MusicAbstractDownloadRequest::downloadFinished(), QJsonParseError::error, QJsonDocument::fromJson(), MusicAbstractDownloadRequest::m_file, TTKAbstractNetwork::m_reply, MusicAbstractDownloadRequest::mapCurrentQueryData(), QJsonParseError::NoError, qAsConst, QtNamespace, TTK::toString(), QJsonDocument::toVariant(), TTK_ERROR_STREAM, TTK_INFO_STREAM, TTK_LINEFEED, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToRequest().
void MusicKWDownloadTextRequest::startToRequest () final override virtual
Start to download text data.
Implements MusicAbstractDownloadRequest.
Definition at line 9 of file musickwdownloadtextrequest.cpp.
References MusicAbstractDownloadRequest::deleteAll(), TTKAbstractNetwork::downloadDataChanged(), downloadFinished(), MusicAbstractDownloadRequest::downloadProgress(), MusicAbstractDownloadRequest::m_file, TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, MusicAbstractDownloadRequest::m_speedTimer, MusicAbstractDownloadRequest::m_url, QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK::setContentTypeHeader(), TTK::setSslConfiguration(), TTK_ERROR_STREAM, and TTK_SLOT.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwdownloadtextrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwdownloadtextrequest.cpp