TTKMusicplayer: MusicKWDiscoverListRequest Class Reference
MusicKWDiscoverListRequest Class Reference
The class of kuwo discover toplist.
#include <musickwdiscoverlistrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWDiscoverListRequest (QObject *parent=nullptr)
virtual void startToSearch () overridefinal
Public Member Functions inherited from MusicDiscoverListRequest
MusicDiscoverListRequest (QObject *parent=nullptr)
const QString & getToplistInfo () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicDiscoverListRequest
QString m_toplistInfo
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of kuwo discover toplist.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musickwdiscoverlistrequest.h.
Constructor & Destructor Documentation
MusicKWDiscoverListRequest::MusicKWDiscoverListRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musickwdiscoverlistrequest.cpp.
Member Function Documentation
void MusicKWDiscoverListRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 30 of file musickwdiscoverlistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicAbstractNetwork::m_reply, MusicDiscoverListRequest::m_toplistInfo, QJson::Parser::parse(), MusicTime::random(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicKWDiscoverListRequest::startToSearch () final override virtual
Start to Search data from toplist.
Implements MusicDiscoverListRequest.
Definition at line 10 of file musickwdiscoverlistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KW_TOPLIST_URL, MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicDiscoverListRequest::m_toplistInfo, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwdiscoverlistrequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwdiscoverlistrequest.cpp