TTKMusicplayer: MusicSongCheckToolsQualityCore Class Reference
MusicSongCheckToolsQualityCore Class Reference
The class of the song check tools quality thread.
#include <musicsongchecktoolscore.h>
Public Slots
void start ()
virtual void run () override
Signals
void finished (const MusicSongCheckToolsQualitys &items)
Public Member Functions
MusicSongCheckToolsQualityCore (QObject *parent=nullptr)
~MusicSongCheckToolsQualityCore ()
void setQualitySongs (MusicSongs *songs)
void stopAndQuitThread ()
Protected Attributes
bool m_run
MusicSongs * m_songItems
Detailed Description
The class of the song check tools quality thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 136 of file musicsongchecktoolscore.h.
Constructor & Destructor Documentation
MusicSongCheckToolsQualityCore::MusicSongCheckToolsQualityCore (QObject * parent = nullptr) explicit
Definition at line 165 of file musicsongchecktoolscore.cpp.
References m_run, and m_songItems.
MusicSongCheckToolsQualityCore::~MusicSongCheckToolsQualityCore ()
Object contsructor.
Definition at line 172 of file musicsongchecktoolscore.cpp.
References stopAndQuitThread().
Member Function Documentation
void MusicSongCheckToolsQualityCore::finished (const MusicSongCheckToolsQualitys & items) signal
Stop and quit current thread.
Referenced by run().
void MusicSongCheckToolsQualityCore::run () override virtual slot
Strat thread now.
Definition at line 198 of file musicsongchecktoolscore.cpp.
References finished(), MusicSongTag::getBitrate(), MusicSong::getMusicPath(), m_run, m_songItems, and MusicSongTag::read().
void MusicSongCheckToolsQualityCore::setQualitySongs (MusicSongs * songs)
Definition at line 177 of file musicsongchecktoolscore.cpp.
References m_songItems.
Referenced by MusicSongCheckToolsWidget::qualityReCheckButtonClicked().
void MusicSongCheckToolsQualityCore::start () slot
Quality check finished.
Definition at line 192 of file musicsongchecktoolscore.cpp.
References m_run.
Referenced by MusicSongCheckToolsWidget::qualityReCheckButtonClicked().
void MusicSongCheckToolsQualityCore::stopAndQuitThread ()
Set find file path by given path.
Definition at line 182 of file musicsongchecktoolscore.cpp.
References m_run.
Referenced by MusicSongCheckToolsWidget::duplicateReCheckButtonClicked(), MusicSongCheckToolsWidget::qualityButtonCheckClicked(), MusicSongCheckToolsWidget::qualityReCheckButtonClicked(), and ~MusicSongCheckToolsQualityCore().
Member Data Documentation
bool MusicSongCheckToolsQualityCore::m_run protected
Thread run now.
Definition at line 173 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsQualityCore(), run(), start(), and stopAndQuitThread().
MusicSongs* MusicSongCheckToolsQualityCore::m_songItems protected
Definition at line 174 of file musicsongchecktoolscore.h.
Referenced by MusicSongCheckToolsQualityCore(), run(), and setQualitySongs().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolscore.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolscore.cpp