TTKMusicplayer: QNPutRet Class Reference
QNPutRet Class Reference
The namespace of the qiniu put return.
#include <qnputret.h>
Public Member Functions
QNPutRet ()
QString getHash () const
void setHash (const QString &value)
QString getKey () const
void setKey (const QString &value)
Static Public Member Functions
static QNPutRet * fromJSON (const QByteArray &json)
Detailed Description
The namespace of the qiniu put return.
Author
Jemy Graw jemyg.nosp@m.raw@.nosp@m.gmail.nosp@m..com
Definition at line 21 of file qnputret.h.
Constructor & Destructor Documentation
QNPutRet::QNPutRet ()
Definition at line 22 of file qnputret.cpp.
References TTK_INIT_PRIVATE.
Referenced by fromJSON().
Member Function Documentation
QNPutRet * QNPutRet::fromJSON (const QByteArray & json) static
Object contsructor.
Definition at line 27 of file qnputret.cpp.
References QJson::Parser::parse(), QNPutRet(), setHash(), and setKey().
Referenced by QNSimpleUploadData::receiveDataFromServer().
QString QNPutRet::getHash () const
Transfer data from json.
Definition at line 42 of file qnputret.cpp.
References TTK_D.
QString QNPutRet::getKey () const
Set hash.
Definition at line 54 of file qnputret.cpp.
References TTK_D.
Referenced by QNSimpleUploadData::receiveDataFromServer().
void QNPutRet::setHash (const QString & value)
Get hash.
Definition at line 48 of file qnputret.cpp.
References TTK_D.
Referenced by fromJSON().
void QNPutRet::setKey (const QString & value)
Get key.
Definition at line 60 of file qnputret.cpp.
References TTK_D.
Referenced by fromJSON().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qiniu/qnputret.h
TTKThirdParty/TTKExtras/qiniu/qnputret.cpp