TTKMusicPlayer: MusicViewWidget Class Reference
MusicViewWidget Class Reference
The class of the video show widget.
#include <musicvideoview.h>
Signals
void fullScreenMode ()
void timeToPlay ()
Public Member Functions
MusicViewWidget (QWidget *parent=nullptr)
~MusicViewWidget ()
Private Member Functions
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseDoubleClickEvent (QMouseEvent *event) overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
Private Attributes
QTimer * m_clickedTimer
bool m_leftPressed
Detailed Description
The class of the video show widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicvideoview.h.
Constructor & Destructor Documentation
MusicViewWidget::MusicViewWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 9 of file musicvideoview.cpp.
References m_clickedTimer, and timeToPlay().
MusicViewWidget::~MusicViewWidget ()
Object destructor.
Definition at line 18 of file musicvideoview.cpp.
References m_clickedTimer.
Member Function Documentation
void MusicViewWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Definition at line 59 of file musicvideoview.cpp.
References TTKObjectCast.
void MusicViewWidget::fullScreenMode () signal
Widget double clicked.
Referenced by mouseDoubleClickEvent().
void MusicViewWidget::mouseDoubleClickEvent (QMouseEvent * event) final override private virtual
Definition at line 46 of file musicvideoview.cpp.
References fullScreenMode(), and m_clickedTimer.
void MusicViewWidget::mouseMoveEvent (QMouseEvent * event) final override private virtual
Definition at line 34 of file musicvideoview.cpp.
References m_clickedTimer, and m_leftPressed.
void MusicViewWidget::mousePressEvent (QMouseEvent * event) final override private virtual
Override the widget event.
Definition at line 23 of file musicvideoview.cpp.
References m_clickedTimer, and m_leftPressed.
void MusicViewWidget::timeToPlay () signal
Widget time to play.
Referenced by MusicViewWidget().
Member Data Documentation
QTimer* MusicViewWidget::m_clickedTimer private
Definition at line 65 of file musicvideoview.h.
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), MusicViewWidget(), and ~MusicViewWidget().
bool MusicViewWidget::m_leftPressed private
Definition at line 66 of file musicvideoview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideoview.h
TTKModule/TTKWidget/musicVideoKits/musicvideoview.cpp