TTKMusicPlayer: TTKDispatchManager Class Reference
TTKDispatchManager Class Reference
The class of the functions dispatch manager.
#include <ttkdispatchmanager.h>
Classes
struct TTKDispatchItem
Public Types
enum Module { Module::Null = -1, Module::FileRemove }
Public Member Functions
void dispatch (Module type)
void dispatch (Module type, void *funcs)
void dispatch (Module type, const TTKVariantList &args)
void dispatch (Module type, const QVariant &arg1)
void dispatch (Module type, const QVariant &arg1, const QVariant &arg2)
void dispatch (Module type, const QVariant &arg1, const QVariant &arg2, const QVariant &arg3)
void dispatch (Module type, const QVariant &arg1, const QVariant &arg2, const QVariant &arg3, const QVariant &arg4)
Private Slots
void activeFunctions ()
Private Member Functions
TTKDispatchManager ()
~TTKDispatchManager ()
Private Attributes
QMutex m_mutex
QTimer * m_timer
QList< TTKDispatchItem * > m_observer
Detailed Description
The class of the functions dispatch manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file ttkdispatchmanager.h.
Member Enumeration Documentation
enum TTKDispatchManager::Module strong
Enumerator
Null
FileRemove
Definition at line 35 of file ttkdispatchmanager.h.
Constructor & Destructor Documentation
TTKDispatchManager::TTKDispatchManager () private
Object constructor.
Definition at line 6 of file ttkdispatchmanager.cpp.
References activeFunctions(), m_timer, and TTK_DN_S2MS.
TTKDispatchManager::~TTKDispatchManager () private
Object destructor.
Definition at line 16 of file ttkdispatchmanager.cpp.
References m_observer, and m_timer.
Member Function Documentation
void TTKDispatchManager::activeFunctions () private slot
Active functions.
Definition at line 78 of file ttkdispatchmanager.cpp.
References FileRemove, TTKDispatchManager::TTKDispatchItem::isValid(), TTKDispatchManager::TTKDispatchItem::m_args, m_mutex, m_observer, TTKDispatchManager::TTKDispatchItem::m_times, and TTKDispatchManager::TTKDispatchItem::m_type.
Referenced by TTKDispatchManager().
void TTKDispatchManager::dispatch (Module type)
Set dispatch.
Definition at line 23 of file ttkdispatchmanager.cpp.
References m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
void TTKDispatchManager::dispatch (Module type, void * funcs)
Definition at line 38 of file ttkdispatchmanager.cpp.
References TTKDispatchManager::TTKDispatchItem::m_args, m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
void TTKDispatchManager::dispatch (Module type, const TTKVariantList & args)
Definition at line 30 of file ttkdispatchmanager.cpp.
References TTKDispatchManager::TTKDispatchItem::m_args, m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
void TTKDispatchManager::dispatch (Module type, const QVariant & arg1)
Set dispatch.
Definition at line 46 of file ttkdispatchmanager.cpp.
References TTKDispatchManager::TTKDispatchItem::m_args, m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
void TTKDispatchManager::dispatch (Module type, const QVariant & arg1, const QVariant & arg2)
Definition at line 54 of file ttkdispatchmanager.cpp.
References TTKDispatchManager::TTKDispatchItem::m_args, m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
void TTKDispatchManager::dispatch (Module type, const QVariant & arg1, const QVariant & arg2, const QVariant & arg3)
Definition at line 62 of file ttkdispatchmanager.cpp.
References TTKDispatchManager::TTKDispatchItem::m_args, m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
void TTKDispatchManager::dispatch (Module type, const QVariant & arg1, const QVariant & arg2, const QVariant & arg3, const QVariant & arg4)
Definition at line 70 of file ttkdispatchmanager.cpp.
References TTKDispatchManager::TTKDispatchItem::m_args, m_observer, and TTKDispatchManager::TTKDispatchItem::m_type.
Member Data Documentation
QMutex TTKDispatchManager::m_mutex private
Definition at line 99 of file ttkdispatchmanager.h.
Referenced by activeFunctions().
QList<TTKDispatchItem*> TTKDispatchManager::m_observer private
Definition at line 101 of file ttkdispatchmanager.h.
Referenced by activeFunctions(), dispatch(), and ~TTKDispatchManager().
QTimer* TTKDispatchManager::m_timer private
Definition at line 100 of file ttkdispatchmanager.h.
Referenced by TTKDispatchManager(), and ~TTKDispatchManager().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkdispatchmanager.h
TTKCommon/TTKLibrary/ttkdispatchmanager.cpp