TTKMusicPlayer: MusicCutSliderWidget Class Reference
MusicCutSliderWidget Class Reference
The class of the cut slider widget.
#include <musiccutsliderwidget.h>
Public Slots
void buttonMoveUpdate ()
void buttonReleaseLeft ()
void buttonReleaseRight ()
Signals
void posChanged (qint64 start, qint64 end)
void buttonReleaseChanged (qint64 pos)
Public Member Functions
MusicCutSliderWidget (QWidget *parent=nullptr)
~MusicCutSliderWidget ()
void setPosition (qint64 position)
void setDuration (qint64 duration)
void resizeGeometry (int width, int height)
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Private Attributes
MusicMoveButton * m_leftControl
MusicMoveButton * m_rightControl
int m_width
int m_height
qint64 m_duration
qint64 m_position
Detailed Description
The class of the cut slider widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 65 of file musiccutsliderwidget.h.
Constructor & Destructor Documentation
MusicCutSliderWidget::MusicCutSliderWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 57 of file musiccutsliderwidget.cpp.
References buttonMoveUpdate(), buttonReleaseLeft(), buttonReleaseRight(), m_leftControl, m_rightControl, PAINT_BUTTON_HEIGHT, PAINT_BUTTON_WIDTH, and resizeGeometry().
MusicCutSliderWidget::~MusicCutSliderWidget ()
Definition at line 75 of file musiccutsliderwidget.cpp.
References m_leftControl, and m_rightControl.
Member Function Documentation
void MusicCutSliderWidget::buttonMoveUpdate () slot
Moving button pos updated.
Definition at line 111 of file musiccutsliderwidget.cpp.
References m_duration, m_leftControl, m_rightControl, m_width, PAINT_BUTTON_WIDTH, and posChanged().
Referenced by MusicCutSliderWidget().
void MusicCutSliderWidget::buttonReleaseChanged (qint64 pos) signal
Moving button pos release changed.
Referenced by buttonReleaseLeft(), and buttonReleaseRight().
void MusicCutSliderWidget::buttonReleaseLeft () slot
Left moving button released.
Definition at line 151 of file musiccutsliderwidget.cpp.
References buttonReleaseChanged(), m_duration, m_leftControl, m_width, and PAINT_BUTTON_WIDTH.
Referenced by MusicCutSliderWidget().
void MusicCutSliderWidget::buttonReleaseRight () slot
Left moving button released.
Definition at line 158 of file musiccutsliderwidget.cpp.
References buttonReleaseChanged(), m_duration, m_rightControl, m_width, and PAINT_BUTTON_WIDTH.
Referenced by MusicCutSliderWidget().
void MusicCutSliderWidget::mouseMoveEvent (QMouseEvent * event) final override private virtual
Definition at line 192 of file musiccutsliderwidget.cpp.
void MusicCutSliderWidget::mousePressEvent (QMouseEvent * event) final override private virtual
Definition at line 187 of file musiccutsliderwidget.cpp.
void MusicCutSliderWidget::mouseReleaseEvent (QMouseEvent * event) final override private virtual
Definition at line 197 of file musiccutsliderwidget.cpp.
void MusicCutSliderWidget::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 165 of file musiccutsliderwidget.cpp.
References m_height, m_leftControl, m_position, m_rightControl, m_width, MusicUIObject::MQSSColor01, PAINT_BUTTON_WIDTH, PAINT_HANDER, and PAINT_SLIDER_HEIGHT.
void MusicCutSliderWidget::posChanged (qint64 start, qint64 end) signal
Moving button pos changed.
Referenced by buttonMoveUpdate().
void MusicCutSliderWidget::resizeGeometry (int width, int height)
Resize geometry bound by resize called.
Definition at line 96 of file musiccutsliderwidget.cpp.
References m_height, m_leftControl, m_rightControl, m_width, PAINT_BUTTON_WIDTH, and PAINT_SLIDER_HEIGHT.
Referenced by MusicCutSliderWidget().
void MusicCutSliderWidget::setDuration (qint64 duration)
Set current duration.
Definition at line 91 of file musiccutsliderwidget.cpp.
References m_duration.
void MusicCutSliderWidget::setPosition (qint64 position)
Set current position.
Definition at line 81 of file musiccutsliderwidget.cpp.
References m_duration, m_position, and m_width.
Member Data Documentation
qint64 MusicCutSliderWidget::m_duration private
Definition at line 124 of file musiccutsliderwidget.h.
Referenced by buttonMoveUpdate(), buttonReleaseLeft(), buttonReleaseRight(), setDuration(), and setPosition().
int MusicCutSliderWidget::m_height private
Definition at line 123 of file musiccutsliderwidget.h.
Referenced by paintEvent(), and resizeGeometry().
MusicMoveButton* MusicCutSliderWidget::m_leftControl private
Definition at line 122 of file musiccutsliderwidget.h.
Referenced by buttonMoveUpdate(), buttonReleaseLeft(), MusicCutSliderWidget(), paintEvent(), resizeGeometry(), and ~MusicCutSliderWidget().
qint64 MusicCutSliderWidget::m_position private
Definition at line 124 of file musiccutsliderwidget.h.
Referenced by paintEvent(), and setPosition().
MusicMoveButton * MusicCutSliderWidget::m_rightControl private
Definition at line 122 of file musiccutsliderwidget.h.
Referenced by buttonMoveUpdate(), buttonReleaseRight(), MusicCutSliderWidget(), paintEvent(), resizeGeometry(), and ~MusicCutSliderWidget().
int MusicCutSliderWidget::m_width private
Definition at line 123 of file musiccutsliderwidget.h.
Referenced by buttonMoveUpdate(), buttonReleaseLeft(), buttonReleaseRight(), paintEvent(), resizeGeometry(), and setPosition().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musiccutsliderwidget.h
TTKModule/TTKWidget/musicCoreKits/musiccutsliderwidget.cpp