TTKMusicPlayer: MusicCloudManagerTableWidget Class Reference
MusicCloudManagerTableWidget Class Reference
The class of the cloud shared song table widget.
#include <musiccloudmanagerwidget.h>
Public Slots
void downLoadKeyFinished (const QByteArray &bytes)
void receiveDataFinshed (const QSyncDataItemList &items)
void uploadFileFinished (const QString &time)
void deleteFileFinished (bool state)
void updateListFromServer ()
void deleteFileFromServer ()
void deleteFilesFromServer ()
void downloadFileFromServer ()
void cancelUploadFilesToServer ()
void uploadFilesToServer ()
void uploadFileDirToServer ()
void reuploadFilesToServer (const QStringList &items)
void uploadProgress (const QString &time, qint64 percent, qint64 total)
void uploadDone ()
void showFileInformationWidget ()
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void updateLabelMessage (const QString &text)
void updataSizeLabel (qint64 size)
void finished ()
void uploadFileError (const MusicCloudDataItem &item)
Public Member Functions
MusicCloudManagerTableWidget (QWidget *parent=nullptr)
~MusicCloudManagerTableWidget ()
bool queryCloudKey ()
void resizeSection () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Private Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
bool cloudConfigValid () const
void addCellItem (const MusicCloudDataItem &data)
void uploadFilesToServer (const QStringList &paths)
void createUploadFileModule ()
void startToUploadFile ()
int FindUploadItemRow (const QString &time) const
MusicCloudDataItem FindWaitedItemRow () const
Private Attributes
bool m_uploading
bool m_cancel
qint64 m_totalFileSzie
QSyncListData * m_syncListData
QSyncDeleteData * m_syncDeleteData
QSyncUploadData * m_syncUploadData
QSyncDownloadData * m_syncDownloadData
QNetworkAccessManager * m_manager
MusicOpenFileWidget * m_openFileWidget
MusicCloudDataItem m_currentDataItem
TTKProgressBarItemDelegate * m_progressBarDelegate
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the cloud shared song table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musiccloudmanagerwidget.h.
Constructor & Destructor Documentation
MusicCloudManagerTableWidget::MusicCloudManagerTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 22 of file musiccloudmanagerwidget.cpp.
References G_CONNECTION_PTR, TTK::UI::ProgressBar01, TTK::UI::ScrollBarStyle03, and TTK::Widget::setTransparent().
MusicCloudManagerTableWidget::~MusicCloudManagerTableWidget ()
Object destructor.
Definition at line 60 of file musiccloudmanagerwidget.cpp.
References G_CONNECTION_PTR, m_manager, m_openFileWidget, m_progressBarDelegate, m_syncDeleteData, m_syncDownloadData, m_syncListData, and m_syncUploadData.
Member Function Documentation
void MusicCloudManagerTableWidget::addCellItem (const MusicCloudDataItem & data) private
Create cell item by input data.
Definition at line 404 of file musiccloudmanagerwidget.cpp.
References TTK::UI::Color01, TTK::Widget::elidedText(), MusicCloudDataItem::m_data, QSyncDataItem::m_hash, QSyncDataItem::m_name, QSyncDataItem::m_putTime, QSyncDataItem::m_size, QtItemSetTextAlignment, TTK::Number::sizeByteToLabel(), TTK_DATA_ROLE, and TTK_PROGRESS_ROLE.
Referenced by receiveDataFinshed(), and uploadFilesToServer().
void MusicCloudManagerTableWidget::cancelUploadFilesToServer () slot
Cancel upload files to server.
Definition at line 301 of file musiccloudmanagerwidget.cpp.
References m_cancel.
Referenced by contextMenuEvent().
bool MusicCloudManagerTableWidget::cloudConfigValid () const private
Check current sync condig is valid.
Definition at line 399 of file musiccloudmanagerwidget.cpp.
References QSyncConfig::KEY, and QSyncConfig::NAME.
Referenced by queryCloudKey().
void MusicCloudManagerTableWidget::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Definition at line 371 of file musiccloudmanagerwidget.cpp.
References TTK::Widget::adjustMenuPosition(), cancelUploadFilesToServer(), deleteFileFromServer(), deleteFilesFromServer(), downloadFileFromServer(), MusicCloudDataItem::isValid(), m_currentDataItem, MusicCloudDataItem::m_state, m_uploading, TTK::UI::MenuStyle02, showFileInformationWidget(), updateListFromServer(), uploadFileDirToServer(), uploadFilesToServer(), and MusicCloudDataItem::Waited.
void MusicCloudManagerTableWidget::createUploadFileModule () private
Create upload file module.
Definition at line 475 of file musiccloudmanagerwidget.cpp.
References MusicOpenFileWidget::adjustWidgetRect(), m_openFileWidget, uploadFileDirToServer(), and uploadFilesToServer().
Referenced by deleteFileFromServer(), deleteFilesFromServer(), receiveDataFinshed(), and uploadFilesToServer().
void MusicCloudManagerTableWidget::deleteFileFinished (bool state) slot
Delete data to sync finshed.
Definition at line 190 of file musiccloudmanagerwidget.cpp.
References updateLabelMessage().
void MusicCloudManagerTableWidget::deleteFileFromServer () slot
Delete file from server.
Definition at line 201 of file musiccloudmanagerwidget.cpp.
References createUploadFileModule(), TTKAbstractTableWidget::isValid(), MusicCloudDataItem::m_data, QSyncDataItem::m_name, QSyncDataItem::m_size, m_syncDeleteData, m_totalFileSzie, m_uploading, MusicToastLabel::popup(), QSyncDeleteData::request(), SYNC_MUSIC_BUCKET, TTK_DATA_ROLE, and updataSizeLabel().
Referenced by contextMenuEvent(), and MusicCloudManagerWidget::deleteFileFromServer().
void MusicCloudManagerTableWidget::deleteFilesFromServer () slot
Delete files from server.
Definition at line 232 of file musiccloudmanagerwidget.cpp.
References createUploadFileModule(), MusicCloudDataItem::m_data, QSyncDataItem::m_name, QSyncDataItem::m_size, m_syncDeleteData, m_totalFileSzie, m_uploading, MusicToastLabel::popup(), QSyncDeleteData::request(), TTKAbstractTableWidget::selectedIndexList(), SYNC_MUSIC_BUCKET, TTK_DATA_ROLE, and updataSizeLabel().
Referenced by contextMenuEvent().
void MusicCloudManagerTableWidget::downloadFileFromServer () slot
Download file from server.
Definition at line 263 of file musiccloudmanagerwidget.cpp.
References TTK::CloudDownload, QSyncDownloadData::downloadUrl(), TTKAbstractTableWidget::isValid(), MusicCloudDataItem::m_data, QSyncDataItem::m_name, m_syncDownloadData, TTK::Music, TTK::String::musicDirPrefix(), MusicToastLabel::popup(), MusicDownloadDataRequest::startToRequest(), SYNC_MUSIC_BUCKET, and TTK_DATA_ROLE.
Referenced by contextMenuEvent(), and MusicCloudManagerWidget::downloadFileFromServer().
void MusicCloudManagerTableWidget::downLoadKeyFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 112 of file musiccloudmanagerwidget.cpp.
References QJsonParseError::error, finished(), QJsonDocument::fromJson(), QSyncConfig::KEY, QSyncConfig::NAME, QJsonParseError::NoError, QJsonDocument::toVariant(), and TTK_ERROR_STREAM.
Referenced by queryCloudKey().
int MusicCloudManagerTableWidget::FindUploadItemRow (const QString & time) const private
Find upload item row.
Definition at line 516 of file musiccloudmanagerwidget.cpp.
References MusicCloudDataItem::m_id, and TTK_DATA_ROLE.
Referenced by uploadFileFinished(), and uploadProgress().
MusicCloudDataItem MusicCloudManagerTableWidget::FindWaitedItemRow () const private
Find waited item row.
Definition at line 535 of file musiccloudmanagerwidget.cpp.
References MusicCloudDataItem::m_state, TTK_DATA_ROLE, and MusicCloudDataItem::Waited.
Referenced by startToUploadFile().
void MusicCloudManagerTableWidget::finished () signal
Get key data from net finished.
Referenced by downLoadKeyFinished(), and queryCloudKey().
bool MusicCloudManagerTableWidget::queryCloudKey ()
Get query cloud id keys.
Definition at line 72 of file musiccloudmanagerwidget.cpp.
References cloudConfigValid(), downLoadKeyFinished(), TTKEventLoop::exec(), finished(), QSyncUtils::makeDataBucketUrl(), QUERY_CLOUD_URL, MusicDataSourceRequest::startToRequest(), and updateListFromServer().
Referenced by MusicCloudManagerWidget::initialize().
void MusicCloudManagerTableWidget::receiveDataFinshed (const QSyncDataItemList & items) slot
Receive data from sync finshed.
Definition at line 133 of file musiccloudmanagerwidget.cpp.
References addCellItem(), createUploadFileModule(), TTKDateTime::currentTimestamp(), MusicCloudDataItem::m_data, MusicCloudDataItem::m_id, MusicCloudDataItem::m_path, MusicCloudDataItem::m_state, m_totalFileSzie, qAsConst, TTKAbstractTableWidget::removeItems(), MusicCloudDataItem::Successed, updataSizeLabel(), and updateLabelMessage().
void MusicCloudManagerTableWidget::resizeSection () const
Resize section bound by resize called.
Definition at line 94 of file musiccloudmanagerwidget.cpp.
References MusicOpenFileWidget::adjustWidgetRect(), TTK::Widget::elidedText(), G_SETTING_PTR, m_openFileWidget, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicCloudManagerWidget::resizeWidget().
void MusicCloudManagerTableWidget::reuploadFilesToServer (const QStringList & items) slot
Reupload files to server.
Definition at line 323 of file musiccloudmanagerwidget.cpp.
References uploadFilesToServer().
void MusicCloudManagerTableWidget::showFileInformationWidget () slot
Show file information widget.
Definition at line 352 of file musiccloudmanagerwidget.cpp.
References MusicAbstractMoveDialog::exec(), TTKAbstractTableWidget::isValid(), MusicCloudDataItem::m_data, MusicCloudFileInformationWidget::setFileInformation(), and TTK_DATA_ROLE.
Referenced by contextMenuEvent().
void MusicCloudManagerTableWidget::startToUploadFile () private
Start to upload files to server.
Definition at line 494 of file musiccloudmanagerwidget.cpp.
References FindWaitedItemRow(), MusicCloudDataItem::isValid(), m_cancel, m_currentDataItem, MusicCloudDataItem::m_data, MusicCloudDataItem::m_id, QSyncDataItem::m_name, MusicCloudDataItem::m_path, m_syncUploadData, m_uploading, QSyncUploadData::request(), SYNC_MUSIC_BUCKET, updateLabelMessage(), and uploadDone().
Referenced by uploadFileFinished(), and uploadFilesToServer().
void MusicCloudManagerTableWidget::updataSizeLabel (qint64 size) signal
Update size label.
Referenced by deleteFileFromServer(), deleteFilesFromServer(), receiveDataFinshed(), and uploadFileFinished().
void MusicCloudManagerTableWidget::updateLabelMessage (const QString & text) signal
To update message label text.
Referenced by deleteFileFinished(), receiveDataFinshed(), startToUploadFile(), and updateListFromServer().
void MusicCloudManagerTableWidget::updateListFromServer () slot
Update list from server.
Definition at line 195 of file musiccloudmanagerwidget.cpp.
References m_syncListData, QSyncListData::request(), SYNC_MUSIC_BUCKET, and updateLabelMessage().
Referenced by contextMenuEvent(), queryCloudKey(), and uploadDone().
void MusicCloudManagerTableWidget::uploadDone () slot
All files upload finsihed.
Definition at line 345 of file musiccloudmanagerwidget.cpp.
References MusicCloudDataItem::clear(), m_currentDataItem, m_uploading, and updateListFromServer().
Referenced by startToUploadFile().
void MusicCloudManagerTableWidget::uploadFileDirToServer () slot
Upload file dir to server.
Definition at line 312 of file musiccloudmanagerwidget.cpp.
References TTK::File::fileListByPath(), TTK::File::getExistingDirectory(), MusicFormats::supportMusicInputFilterFormats(), and uploadFilesToServer().
Referenced by contextMenuEvent(), and createUploadFileModule().
void MusicCloudManagerTableWidget::uploadFileError (const MusicCloudDataItem & item) signal
Upload file error occurred.
Referenced by uploadFileFinished().
void MusicCloudManagerTableWidget::uploadFileFinished (const QString & time) slot
Upload data to sync finshed.
Definition at line 162 of file musiccloudmanagerwidget.cpp.
References FindUploadItemRow(), m_currentDataItem, MusicCloudDataItem::m_data, QSyncDataItem::m_size, MusicCloudDataItem::m_state, m_totalFileSzie, startToUploadFile(), MusicCloudDataItem::Successed, TTK_DATA_ROLE, TTK_NAN_STR, updataSizeLabel(), and uploadFileError().
void MusicCloudManagerTableWidget::uploadFilesToServer () slot
Upload files to server.
Definition at line 306 of file musiccloudmanagerwidget.cpp.
References TTK::File::getOpenFileNames(), and MusicFormats::supportMusicInputFormats().
Referenced by contextMenuEvent(), createUploadFileModule(), reuploadFilesToServer(), uploadFileDirToServer(), and MusicCloudManagerWidget::uploadFilesToServer().
void MusicCloudManagerTableWidget::uploadFilesToServer (const QStringList & paths) private
Upload files to server.
Definition at line 441 of file musiccloudmanagerwidget.cpp.
References addCellItem(), createUploadFileModule(), TTKDateTime::currentTimestamp(), MusicCloudDataItem::m_data, MusicCloudDataItem::m_id, QSyncDataItem::m_name, m_openFileWidget, MusicCloudDataItem::m_path, QSyncDataItem::m_putTime, QSyncDataItem::m_size, MusicCloudDataItem::m_state, m_uploading, qAsConst, TTK::Core::sleep(), startToUploadFile(), TTK_DATE_TIMEM_FORMAT, TTK_DN_MS, and MusicCloudDataItem::Waited.
void MusicCloudManagerTableWidget::uploadProgress (const QString & time, qint64 percent, qint64 total) slot
Show upload progress.
Definition at line 328 of file musiccloudmanagerwidget.cpp.
References FindUploadItemRow(), TTK_PROGRESS_ROLE, and TTKStaticCast.
Member Data Documentation
bool MusicCloudManagerTableWidget::m_cancel private
Definition at line 178 of file musiccloudmanagerwidget.h.
Referenced by cancelUploadFilesToServer(), and startToUploadFile().
MusicCloudDataItem MusicCloudManagerTableWidget::m_currentDataItem private
Definition at line 186 of file musiccloudmanagerwidget.h.
Referenced by contextMenuEvent(), startToUploadFile(), uploadDone(), and uploadFileFinished().
QNetworkAccessManager* MusicCloudManagerTableWidget::m_manager private
Definition at line 184 of file musiccloudmanagerwidget.h.
Referenced by ~MusicCloudManagerTableWidget().
MusicOpenFileWidget* MusicCloudManagerTableWidget::m_openFileWidget private
Definition at line 185 of file musiccloudmanagerwidget.h.
Referenced by createUploadFileModule(), resizeSection(), uploadFilesToServer(), and ~MusicCloudManagerTableWidget().
TTKProgressBarItemDelegate* MusicCloudManagerTableWidget::m_progressBarDelegate private
Definition at line 187 of file musiccloudmanagerwidget.h.
Referenced by ~MusicCloudManagerTableWidget().
QSyncDeleteData* MusicCloudManagerTableWidget::m_syncDeleteData private
Definition at line 181 of file musiccloudmanagerwidget.h.
Referenced by deleteFileFromServer(), deleteFilesFromServer(), and ~MusicCloudManagerTableWidget().
QSyncDownloadData* MusicCloudManagerTableWidget::m_syncDownloadData private
Definition at line 183 of file musiccloudmanagerwidget.h.
Referenced by downloadFileFromServer(), and ~MusicCloudManagerTableWidget().
QSyncListData* MusicCloudManagerTableWidget::m_syncListData private
Definition at line 180 of file musiccloudmanagerwidget.h.
Referenced by updateListFromServer(), and ~MusicCloudManagerTableWidget().
QSyncUploadData* MusicCloudManagerTableWidget::m_syncUploadData private
Definition at line 182 of file musiccloudmanagerwidget.h.
Referenced by startToUploadFile(), and ~MusicCloudManagerTableWidget().
qint64 MusicCloudManagerTableWidget::m_totalFileSzie private
Definition at line 179 of file musiccloudmanagerwidget.h.
Referenced by deleteFileFromServer(), deleteFilesFromServer(), receiveDataFinshed(), and uploadFileFinished().
bool MusicCloudManagerTableWidget::m_uploading private
Definition at line 177 of file musiccloudmanagerwidget.h.
Referenced by contextMenuEvent(), deleteFileFromServer(), deleteFilesFromServer(), startToUploadFile(), uploadDone(), and uploadFilesToServer().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudmanagerwidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudmanagerwidget.cpp