TTKMusicplayer: TTKExtra/qmmp/equ/iir_cfs.h File Reference
iir_cfs.h File Reference
Classes
struct sIIRCoefficients
Functions
sIIRCoefficients * get_coeffs (int *bands, unsigned int sfreq)
void calc_coeffs ()
Function Documentation
void calc_coeffs ()
Definition at line 206 of file iir_cfs.c.
References ALPHA, BETA0, BETA1, BETA2, cfs, coeffs, find_f1_and_f2(), find_root(), GAMMA, iir_bands, octave, and TETA.
Referenced by eq_init_iir().
sIIRCoefficients* get_coeffs (int * bands, unsigned int sfreq)
Definition at line 139 of file iir_cfs.c.
References iir_cf.
Referenced by eq_init_iir().