TTKMusicPlayer: MusicAbstractMoveResizePlainWidget Class Reference
MusicAbstractMoveResizePlainWidget Class Reference
The class of the moving resize widget with plain.
#include <musicabstractmoveresizewidget.h>
Public Slots
void backgroundChanged ()
void show ()
Public Member Functions
MusicAbstractMoveResizePlainWidget (QWidget *parent=nullptr)
~MusicAbstractMoveResizePlainWidget ()
Public Member Functions inherited from TTKAbstractMoveResizeWidget
TTKAbstractMoveResizeWidget (QWidget *parent=nullptr)
TTKAbstractMoveResizeWidget (bool transparent, QWidget *parent=nullptr)
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveResizeWidget
virtual bool eventFilter (QObject *object, QEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void sizeDirection ()
void moveDirection ()
void setObjectsTracking (const QWidgetList &objects)
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Protected Attributes inherited from TTKAbstractMoveResizeWidget
MoveResizeData m_struct
TTK::Direction m_direction
Detailed Description
The class of the moving resize widget with plain.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicabstractmoveresizewidget.h.
Constructor & Destructor Documentation
MusicAbstractMoveResizePlainWidget::MusicAbstractMoveResizePlainWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file musicabstractmoveresizewidget.cpp.
References G_BACKGROUND_PTR.
MusicAbstractMoveResizePlainWidget::~MusicAbstractMoveResizePlainWidget ()
Object destructor.
Definition at line 10 of file musicabstractmoveresizewidget.cpp.
References G_BACKGROUND_PTR.
Member Function Documentation
void MusicAbstractMoveResizePlainWidget::backgroundChanged () slot
Background image changed.
Definition at line 15 of file musicabstractmoveresizewidget.cpp.
References MusicWidgetRenderer::setBackgroundPixmap().
Referenced by resizeEvent(), and show().
void MusicAbstractMoveResizePlainWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 26 of file musicabstractmoveresizewidget.cpp.
References backgroundChanged().
void MusicAbstractMoveResizePlainWidget::show () slot
Override show function.
Definition at line 20 of file musicabstractmoveresizewidget.cpp.
References backgroundChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicabstractmoveresizewidget.h
TTKModule/TTKWidget/musicCoreKits/musicabstractmoveresizewidget.cpp