TTKMusicplayer: MusicRemoteWidgetForStrip Class Reference
MusicRemoteWidgetForStrip Class Reference
The class of the desktop strip remote widget.
#include <musicremotewidgetforstrip.h>
Public Member Functions
MusicRemoteWidgetForStrip (QWidget *parent=nullptr)
~MusicRemoteWidgetForStrip ()
virtual void setLabelText (const QString &value) override
Public Member Functions inherited from MusicRemoteWidget
MusicRemoteWidget (QWidget *parent=nullptr)
~MusicRemoteWidget ()
void setCurrentPlayStatus (bool status) const
void setVolumeValue (int index)
int mapRemoteTypeIndex ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicRemoteWidget
void adjustPosition (QWidget *w)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
QPushButton * m_lrcButton
QPushButton * m_wallPaperButton
QPushButton * m_listButton
QPushButton * m_windowStateButton
QToolButton * m_closeButton
MusicMarqueeWidget * m_songNameLabel
QWidget * m_bottomWidget
Protected Attributes inherited from MusicRemoteWidget
QPushButton * m_showMainWindowButton
QPushButton * m_preSongButton
QPushButton * m_nextSongButton
QPushButton * m_playButton
QPushButton * m_settingButton
QWidget * m_mainWidget
QWidget * m_volumeWidget
QToolButton * m_volumeButton
MusicClickedSlider * m_volumeSlider
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Private Slots
void windowStateChanged ()
void show ()
bool close ()
Additional Inherited Members
Public Types inherited from MusicRemoteWidget
enum RemoteType {
Null = 0, Square, Rectangle, SimpleStyle,
ComplexStyle, Ripple
}
Public Slots inherited from MusicRemoteWidget
void musicVolumeSliderChanged (int value)
void show ()
bool close ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals inherited from MusicRemoteWidget
void musicWindowChanged ()
void musicKeyChanged ()
void musicPlayPreviousChanged ()
void musicPlayNextChanged ()
void musicVolumeChanged (int value)
void musicSettingChanged ()
void musicRemoteTypeChanged (QAction *type)
Detailed Description
The class of the desktop strip remote widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicremotewidgetforstrip.h.
Constructor & Destructor Documentation
MusicRemoteWidgetForStrip::MusicRemoteWidgetForStrip (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicremotewidgetforstrip.cpp.
References MusicRemoteWidget::adjustPosition(), close(), m_bottomWidget, m_closeButton, m_listButton, m_lrcButton, MusicRemoteWidget::m_mainWidget, MusicRemoteWidget::m_nextSongButton, MusicRemoteWidget::m_playButton, MusicRemoteWidget::m_preSongButton, MusicRemoteWidget::m_settingButton, MusicRemoteWidget::m_showMainWindowButton, m_songNameLabel, MusicRemoteWidget::m_volumeWidget, m_wallPaperButton, m_windowStateButton, MusicUIObject::MQSSTinyBtnCollapse, MusicUIObject::MQSSTinyBtnList, MusicUIObject::MQSSTinyBtnLrcOff, MusicUIObject::MQSSTinyBtnWallpaperOff, MusicUIObject::MQSSToolButtonStyle04, MusicUIObject::MQSSWidgetStyle01, and windowStateChanged().
MusicRemoteWidgetForStrip::~MusicRemoteWidgetForStrip ()
Definition at line 92 of file musicremotewidgetforstrip.cpp.
References m_closeButton, m_listButton, m_lrcButton, m_songNameLabel, m_wallPaperButton, and m_windowStateButton.
Member Function Documentation
bool MusicRemoteWidgetForStrip::close () private slot
Override close function.
Definition at line 122 of file musicremotewidgetforstrip.cpp.
Referenced by contextMenuEvent(), and MusicRemoteWidgetForStrip().
void MusicRemoteWidgetForStrip::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicRemoteWidget.
Definition at line 127 of file musicremotewidgetforstrip.cpp.
References close(), MusicUIObject::MQSSMenuStyle03, and MusicRemoteWidget::musicWindowChanged().
void MusicRemoteWidgetForStrip::setLabelText (const QString & value) override virtual
Set current song text.
Reimplemented from MusicRemoteWidget.
Definition at line 103 of file musicremotewidgetforstrip.cpp.
References MusicUtils::Widget::elidedText(), m_songNameLabel, and MusicMarqueeWidget::setText().
void MusicRemoteWidgetForStrip::show () private slot
Override show function.
Definition at line 117 of file musicremotewidgetforstrip.cpp.
void MusicRemoteWidgetForStrip::windowStateChanged () private slot
Window statec hanged.
Definition at line 108 of file musicremotewidgetforstrip.cpp.
References m_bottomWidget, m_windowStateButton, MusicUIObject::MQSSTinyBtnCollapse, and MusicUIObject::MQSSTinyBtnExpand.
Referenced by MusicRemoteWidgetForStrip().
Member Data Documentation
QWidget* MusicRemoteWidgetForStrip::m_bottomWidget protected
Definition at line 69 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), and windowStateChanged().
QToolButton* MusicRemoteWidgetForStrip::m_closeButton protected
Definition at line 67 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), and ~MusicRemoteWidgetForStrip().
QPushButton * MusicRemoteWidgetForStrip::m_listButton protected
Definition at line 65 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), and ~MusicRemoteWidgetForStrip().
QPushButton* MusicRemoteWidgetForStrip::m_lrcButton protected
Definition at line 65 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), and ~MusicRemoteWidgetForStrip().
MusicMarqueeWidget* MusicRemoteWidgetForStrip::m_songNameLabel protected
Definition at line 68 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), setLabelText(), and ~MusicRemoteWidgetForStrip().
QPushButton * MusicRemoteWidgetForStrip::m_wallPaperButton protected
Definition at line 65 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), and ~MusicRemoteWidgetForStrip().
QPushButton* MusicRemoteWidgetForStrip::m_windowStateButton protected
Definition at line 66 of file musicremotewidgetforstrip.h.
Referenced by MusicRemoteWidgetForStrip(), windowStateChanged(), and ~MusicRemoteWidgetForStrip().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforstrip.h
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforstrip.cpp