TTKMusicPlayer: MusicAbstractDownloadImageRequest Class Reference
MusicAbstractDownloadImageRequest Class Reference abstract
The class of the download art background image.
#include <musicabstractdownloadimagerequest.h>
Public Slots
void downLoadDataFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicAbstractDownloadImageRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void deleteAll () overridefinal
virtual void startToRequest ()=0
void setRemainCount (int count)
int foundCount ()
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Attributes
int m_remainCount
int m_index
int m_counter
QString m_name
QString m_path
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Detailed Description
The class of the download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicabstractdownloadimagerequest.h.
Constructor & Destructor Documentation
MusicAbstractDownloadImageRequest::MusicAbstractDownloadImageRequest (const QString & name, const QString & path, QObject * parent = nullptr)
Object constructor provide artist name and save local path.
Definition at line 5 of file musicabstractdownloadimagerequest.cpp.
Member Function Documentation
void MusicAbstractDownloadImageRequest::deleteAll () final override virtual
Release the network object.
Reimplemented from TTKAbstractNetwork.
Definition at line 16 of file musicabstractdownloadimagerequest.cpp.
References TTKAbstractNetwork::deleteAll().
Referenced by downLoadDataFinished(), MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKGDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicKGDownloadBackgroundRequest::startToRequest().
void MusicAbstractDownloadImageRequest::downLoadDataFinished () slot
Download data from net finished.
Definition at line 22 of file musicabstractdownloadimagerequest.cpp.
References MusicTopAreaWidget::backgroundThemeDownloadFinished(), deleteAll(), TTKAbstractNetwork::downLoadFinished(), G_BACKGROUND_PTR, MusicTopAreaWidget::instance(), m_counter, m_index, and m_name.
Referenced by MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicKGDownloadBackgroundRequest::parseFromBackgroundProperty().
int MusicAbstractDownloadImageRequest::foundCount () inline
get the found count.
Definition at line 55 of file musicabstractdownloadimagerequest.h.
References MAX_IMAGE_COUNT.
Referenced by MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicKGDownloadBackgroundRequest::parseFromBackgroundProperty().
void MusicAbstractDownloadImageRequest::setRemainCount (int count) inline
Set the remain count.
Definition at line 51 of file musicabstractdownloadimagerequest.h.
Referenced by MusicDownloadBackgroundRequest::findAllPlugins().
virtual void MusicAbstractDownloadImageRequest::startToRequest () pure virtual
Start to request background data. Subclass should implement this function.
Implemented in MusicTXDownloadBackgroundRequest, MusicBPDownloadBackgroundRequest, MusicKGDownloadBackgroundRequest, and MusicKWDownloadBackgroundRequest.
Referenced by MusicDownloadBackgroundRequest::findAllPlugins().
Member Data Documentation
int MusicAbstractDownloadImageRequest::m_counter protected
Definition at line 65 of file musicabstractdownloadimagerequest.h.
Referenced by downLoadDataFinished(), MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicKGDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicKGDownloadBackgroundRequest::parseFromBackgroundProperty().
int MusicAbstractDownloadImageRequest::m_index protected
Definition at line 65 of file musicabstractdownloadimagerequest.h.
Referenced by downLoadDataFinished().
QString MusicAbstractDownloadImageRequest::m_name protected
Definition at line 66 of file musicabstractdownloadimagerequest.h.
Referenced by downLoadDataFinished(), MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), and MusicTXDownloadBackgroundRequest::startToRequest().
QString MusicAbstractDownloadImageRequest::m_path protected
Definition at line 66 of file musicabstractdownloadimagerequest.h.
Referenced by MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicKGDownloadBackgroundRequest::parseFromBackgroundProperty().
int MusicAbstractDownloadImageRequest::m_remainCount protected
Definition at line 64 of file musicabstractdownloadimagerequest.h.
Referenced by MusicBPDownloadBackgroundRequest::downLoadFinished(), MusicKWDownloadBackgroundRequest::downLoadFinished(), MusicTXDownloadBackgroundRequest::downLoadUrlFinished(), and MusicKGDownloadBackgroundRequest::parseFromBackgroundProperty().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/background/musicabstractdownloadimagerequest.h
TTKModule/TTKCore/musicNetworkKits/image/background/musicabstractdownloadimagerequest.cpp