TTKMusicplayer: QAlgorithm::SharpeImage Class Reference
QAlgorithm::SharpeImage Class Reference abstract
The class of the sharpe image.
#include <imagewrapper.h>
Public Member Functions
SharpeImage ()
virtual ~SharpeImage ()
virtual void input (const QRect &region)
virtual QPixmap render (const QPixmap &pixmap, int value)=0
Protected Member Functions
SharpeImage (SharpeImagePrivate &pvt)
Detailed Description
The class of the sharpe image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file imagewrapper.h.
Constructor & Destructor Documentation
QAlgorithm::SharpeImage::SharpeImage ()
Definition at line 32 of file imagewrapper.cpp.
QAlgorithm::SharpeImage::~SharpeImage () virtual
Definition at line 43 of file imagewrapper.cpp.
QAlgorithm::SharpeImage::SharpeImage (SharpeImagePrivate & pvt) protected
Definition at line 38 of file imagewrapper.cpp.
References TTK_INIT_PRIVATE_D.
Member Function Documentation
void QAlgorithm::SharpeImage::input (const QRect & region) virtual
Init item data.
Reimplemented in QAlgorithm::WaterWave, and QAlgorithm::CubeWave.
Definition at line 48 of file imagewrapper.cpp.
References TTK_D.
Referenced by MusicLrcPosterItemWidget::drawTheme10(), QAlgorithm::CubeWave::input(), QAlgorithm::WaterWave::input(), and MusicTransitionAnimationLabel::setPixmap().
virtual QPixmap QAlgorithm::SharpeImage::render (const QPixmap & pixmap, int value) pure virtual
Render data.
Implemented in QAlgorithm::WaterWave, QAlgorithm::CubeWave, and QAlgorithm::GaussBlur.
Referenced by MusicTransitionAnimationLabel::paintEvent().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/imagewrapper.h
TTKThirdParty/TTKExtras/qalgorithm/imagewrapper.cpp