TTKMusicplayer: MusicLocalSongSearchInteriorEdit Class Reference
MusicLocalSongSearchInteriorEdit Class Reference
The class of the net search interior edit widget.
#include <musiclocalsongsearchinterioredit.h>
Public Slots
void textChanged (const QString &text)
void suggestDataChanged ()
void searchToplistInfoFinished (const QString &bytes)
Public Member Functions
MusicLocalSongSearchInteriorEdit (QWidget *parent=nullptr)
~MusicLocalSongSearchInteriorEdit ()
void initWidget (QWidget *parent)
void closePopWidget ()
Public Member Functions inherited from MusicLocalSongSearchEdit
MusicLocalSongSearchEdit (QWidget *parent=nullptr)
Protected Member Functions
void popWidgetChanged (const QString &text)
virtual void focusInEvent (QFocusEvent *event) override
virtual void leaveEvent (QEvent *event) override
Protected Member Functions inherited from MusicLocalSongSearchEdit
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void keyPressEvent (QKeyEvent *event) override
virtual void keyReleaseEvent (QKeyEvent *event) override
Protected Attributes
MusicLocalSongSearchPopWidget * m_popWidget
MusicDiscoverListRequest * m_discoverRequest
MusicSongSuggestRequest * m_suggestRequest
Additional Inherited Members
Signals inherited from MusicLocalSongSearchEdit
void enterFinished (const QString &text)
Detailed Description
The class of the net search interior edit widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musiclocalsongsearchinterioredit.h.
Constructor & Destructor Documentation
MusicLocalSongSearchInteriorEdit::MusicLocalSongSearchInteriorEdit (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musiclocalsongsearchinterioredit.cpp.
References G_DOWNLOAD_QUERY_PTR, m_discoverRequest, m_popWidget, m_suggestRequest, searchToplistInfoFinished(), MusicDiscoverListRequest::startToSearch(), and textChanged().
MusicLocalSongSearchInteriorEdit::~MusicLocalSongSearchInteriorEdit ()
Definition at line 19 of file musiclocalsongsearchinterioredit.cpp.
References m_discoverRequest, and m_suggestRequest.
Member Function Documentation
void MusicLocalSongSearchInteriorEdit::closePopWidget ()
Close pop widget possible.
Definition at line 35 of file musiclocalsongsearchinterioredit.cpp.
References m_popWidget.
void MusicLocalSongSearchInteriorEdit::focusInEvent (QFocusEvent * event) override protected virtual
Override the widget event.
Definition at line 96 of file musiclocalsongsearchinterioredit.cpp.
References m_popWidget, and popWidgetChanged().
void MusicLocalSongSearchInteriorEdit::initWidget (QWidget * parent)
Create all widget in layout.
Definition at line 25 of file musiclocalsongsearchinterioredit.cpp.
References m_popWidget.
void MusicLocalSongSearchInteriorEdit::leaveEvent (QEvent * event) override protected virtual
Definition at line 105 of file musiclocalsongsearchinterioredit.cpp.
void MusicLocalSongSearchInteriorEdit::popWidgetChanged (const QString & text) protected
Pop widget changed.
Definition at line 82 of file musiclocalsongsearchinterioredit.cpp.
References MusicLocalSongSearchPopWidget::createItems(), and m_popWidget.
Referenced by focusInEvent(), and textChanged().
void MusicLocalSongSearchInteriorEdit::searchToplistInfoFinished (const QString & bytes) slot
Search top list information finished.
Definition at line 77 of file musiclocalsongsearchinterioredit.cpp.
Referenced by MusicLocalSongSearchInteriorEdit().
void MusicLocalSongSearchInteriorEdit::suggestDataChanged () slot
Suggest data changed.
Definition at line 53 of file musiclocalsongsearchinterioredit.cpp.
References MusicLocalSongSearchPopWidget::createSuggestItems(), MusicSongSuggestRequest::getSearchedItems(), m_popWidget, m_suggestRequest, and STRING_NULL.
Referenced by textChanged().
void MusicLocalSongSearchInteriorEdit::textChanged (const QString & text) slot
Input changed text changed.
Definition at line 43 of file musiclocalsongsearchinterioredit.cpp.
References G_DOWNLOAD_QUERY_PTR, m_suggestRequest, popWidgetChanged(), MusicSongSuggestRequest::startToSearch(), and suggestDataChanged().
Referenced by MusicLocalSongSearchInteriorEdit().
Member Data Documentation
MusicDiscoverListRequest* MusicLocalSongSearchInteriorEdit::m_discoverRequest protected
Definition at line 78 of file musiclocalsongsearchinterioredit.h.
Referenced by MusicLocalSongSearchInteriorEdit(), and ~MusicLocalSongSearchInteriorEdit().
MusicLocalSongSearchPopWidget* MusicLocalSongSearchInteriorEdit::m_popWidget protected
Definition at line 77 of file musiclocalsongsearchinterioredit.h.
Referenced by closePopWidget(), focusInEvent(), initWidget(), MusicLocalSongSearchInteriorEdit(), popWidgetChanged(), and suggestDataChanged().
MusicSongSuggestRequest* MusicLocalSongSearchInteriorEdit::m_suggestRequest protected
Definition at line 79 of file musiclocalsongsearchinterioredit.h.
Referenced by MusicLocalSongSearchInteriorEdit(), suggestDataChanged(), textChanged(), and ~MusicLocalSongSearchInteriorEdit().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchinterioredit.h
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchinterioredit.cpp