TTKMusicPlayer: QHttpServerPrivate Class Reference
QHttpServerPrivate Class Reference
The class of the http server private.
Public Member Functions
QHttpServerPrivate ()
bool listen (const QHostAddress &address, quint16 port)
void create ()
void close ()
void free ()
Public Member Functions inherited from TTKPrivate< QHttpServer >
TTKPrivate ()
virtual ~TTKPrivate ()=default
void setPublic (QHttpServer *pub)
Public Attributes
QTcpServer * m_tcpServer
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QHttpServer >
QHttpServer * ttk_q () const
Detailed Description
The class of the http server private.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 14 of file qhttpserver.cpp.
Constructor & Destructor Documentation
QHttpServerPrivate::QHttpServerPrivate ()
Definition at line 28 of file qhttpserver.cpp.
Member Function Documentation
void QHttpServerPrivate::close ()
Definition at line 59 of file qhttpserver.cpp.
References m_tcpServer.
void QHttpServerPrivate::create ()
Definition at line 49 of file qhttpserver.cpp.
References m_tcpServer, and TTKPrivate< QHttpServer >::ttk_q().
void QHttpServerPrivate::free ()
Definition at line 67 of file qhttpserver.cpp.
References m_tcpServer.
Referenced by listen().
bool QHttpServerPrivate::listen (const QHostAddress & address, quint16 port)
Definition at line 34 of file qhttpserver.cpp.
References free(), m_tcpServer, and TTKPrivate< QHttpServer >::ttk_q().
Member Data Documentation
QTcpServer* QHttpServerPrivate::m_tcpServer
Definition at line 24 of file qhttpserver.cpp.
Referenced by close(), create(), free(), and listen().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qhttpserver/qhttpserver.cpp