TTKMusicplayer: MusicBackgroundPaletteWidget Class Reference
MusicBackgroundPaletteWidget Class Reference
The class of the background palette widget.
#include <musicbackgroundpalettewidget.h>
Public Slots
void paletteColorClicked ()
void showPaletteDialog ()
void currentColorToFile (const QColor &color)
void currentColorToMemory (const QString &color)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void currentColorToFileChanged (const QString &path)
void currentColorToMemoryChanged (const QString &path)
Public Member Functions
MusicBackgroundPaletteWidget (QWidget *parent=0)
~MusicBackgroundPaletteWidget ()
void updateBackground (const QString &text)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Attributes
Ui::MusicBackgroundPaletteWidget * m_ui
QList< QWidget * > m_widgets
QColor m_currentColor
QString m_previousBackground
bool m_confirmButtonClicked
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the background palette widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 81 of file musicbackgroundpalettewidget.h.
Constructor & Destructor Documentation
MusicBackgroundPaletteWidget::MusicBackgroundPaletteWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 65 of file musicbackgroundpalettewidget.cpp.
References COLOR_COL, COLOR_ROW, currentColorToFile(), currentColorToFileChanged(), currentColorToMemory(), currentColorToMemoryChanged(), m_confirmButtonClicked, m_ui, m_widgets, MusicUIObject::MPushButtonStyle04, MusicUIObject::MToolButtonStyle04, paletteColorClicked(), MusicBackgroundPalette::setPixmap(), and showPaletteDialog().
MusicBackgroundPaletteWidget::~MusicBackgroundPaletteWidget ()
Definition at line 175 of file musicbackgroundpalettewidget.cpp.
References currentColorToMemoryChanged(), m_confirmButtonClicked, m_previousBackground, m_ui, m_widgets, and MUSIC_COLOR_FILE.
Member Function Documentation
void MusicBackgroundPaletteWidget::currentColorToFile (const QColor & color) slot
Current color confirm.
Definition at line 230 of file musicbackgroundpalettewidget.cpp.
References currentColorToMemory(), m_currentColor, m_ui, and MUSIC_COLOR_FILE.
Referenced by MusicBackgroundPaletteWidget(), and showPaletteDialog().
void MusicBackgroundPaletteWidget::currentColorToFileChanged (const QString & path) signal
Current color path confirm changed.
Referenced by MusicBackgroundPaletteWidget(), and paletteColorClicked().
void MusicBackgroundPaletteWidget::currentColorToMemory (const QString & color) slot
Current color memory confirm.
Definition at line 244 of file musicbackgroundpalettewidget.cpp.
References currentColorToMemoryChanged(), and updateBackground().
Referenced by currentColorToFile(), and MusicBackgroundPaletteWidget().
void MusicBackgroundPaletteWidget::currentColorToMemoryChanged (const QString & path) signal
Current color memory confirm changed.
Referenced by currentColorToMemory(), MusicBackgroundPaletteWidget(), and ~MusicBackgroundPaletteWidget().
int MusicBackgroundPaletteWidget::exec () virtual slot
Override exec function.
Definition at line 250 of file musicbackgroundpalettewidget.cpp.
References M_BACKGROUND_PTR, m_previousBackground, and updateBackground().
Referenced by MusicBackgroundSkinDialog::showPaletteDialog().
QString MusicBackgroundPaletteWidget::getClassName () static
Get class object name.
Definition at line 187 of file musicbackgroundpalettewidget.cpp.
void MusicBackgroundPaletteWidget::paletteColorClicked () slot
Palette color confirm.
Definition at line 205 of file musicbackgroundpalettewidget.cpp.
References currentColorToFileChanged(), m_confirmButtonClicked, m_currentColor, and MUSIC_COLOR_FILE.
Referenced by MusicBackgroundPaletteWidget().
void MusicBackgroundPaletteWidget::showPaletteDialog () slot
Change index to palette dialog.
Definition at line 220 of file musicbackgroundpalettewidget.cpp.
References currentColorToFile(), MusicColorDialog::getColor(), and m_currentColor.
Referenced by MusicBackgroundPaletteWidget().
void MusicBackgroundPaletteWidget::updateBackground (const QString & text)
Update this bg when user change the current bg.
Definition at line 192 of file musicbackgroundpalettewidget.cpp.
References MusicBackgroundImage::m_pix, m_ui, and MusicExtractWrap::outputSkin().
Referenced by currentColorToMemory(), and exec().
Member Data Documentation
bool MusicBackgroundPaletteWidget::m_confirmButtonClicked protected
Definition at line 138 of file musicbackgroundpalettewidget.h.
Referenced by MusicBackgroundPaletteWidget(), paletteColorClicked(), and ~MusicBackgroundPaletteWidget().
QColor MusicBackgroundPaletteWidget::m_currentColor protected
Definition at line 136 of file musicbackgroundpalettewidget.h.
Referenced by currentColorToFile(), paletteColorClicked(), and showPaletteDialog().
QString MusicBackgroundPaletteWidget::m_previousBackground protected
Definition at line 137 of file musicbackgroundpalettewidget.h.
Referenced by exec(), and ~MusicBackgroundPaletteWidget().
Ui::MusicBackgroundPaletteWidget* MusicBackgroundPaletteWidget::m_ui protected
Definition at line 134 of file musicbackgroundpalettewidget.h.
Referenced by currentColorToFile(), MusicBackgroundPaletteWidget(), updateBackground(), and ~MusicBackgroundPaletteWidget().
QList<QWidget*> MusicBackgroundPaletteWidget::m_widgets protected
Definition at line 135 of file musicbackgroundpalettewidget.h.
Referenced by MusicBackgroundPaletteWidget(), and ~MusicBackgroundPaletteWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundpalettewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicbackgroundpalettewidget.cpp