TTKMusicPlayer: MusicLrcFromYrc Class Reference
MusicLrcFromYrc Class Reference
The class of the yrc to lrc.
#include <musiclrcparser.h>
Public Member Functions
virtual bool decode (const QString &input) overridefinal
Public Member Functions inherited from MusicLrcFromInterface
virtual ~MusicLrcFromInterface ()=default
const QByteArray & data () const noexcept
Additional Inherited Members
Protected Attributes inherited from MusicLrcFromInterface
QByteArray m_data
Detailed Description
The class of the yrc to lrc.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 147 of file musiclrcparser.h.
Member Function Documentation
bool MusicLrcFromYrc::decode (const QString & input) final override virtual
Decode file to lrc by input file.
Implements MusicLrcFromInterface.
Definition at line 311 of file musiclrcparser.cpp.
References MusicLrcFromInterface::data(), MusicLrcFromInterface::m_data, TTKTime::toString(), and TTK_LINEFEED.
Referenced by MusicLrcAnalysis::loadFromFile().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicLrcKits/musiclrcparser.h
TTKModule/TTKCore/musicLrcKits/musiclrcparser.cpp