TTKMusicplayer: TTKModule/TTKCore/musicCoreKits/musicsingleton.cpp File Reference
musicsingleton.cpp File Reference
#include "musicconnectionpool.h"
#include "musicbackgroundmanager.h"
#include "musicdispatchmanager.h"
#include "musichotkeymanager.h"
#include "musicsettingmanager.h"
#include "musicsinglemanager.h"
#include "musicdownloadmanager.h"
#include "musicdownloadqueryfactory.h"
Functions
MusicConnectionPool * GetMusicConnectionPool ()
MusicBackgroundManager * GetMusicBackgroundManager ()
MusicDispatchManager * GetMusicDispatchManager ()
MusicHotKeyManager * GetMusicHotKeyManager ()
MusicSettingManager * GetMusicSettingManager ()
MusicSingleManager * GetMusicSingleManager ()
MusicDownLoadManager * GetMusicDownLoadManager ()
MusicDownLoadQueryFactory * GetMusicDownLoadQueryFactory ()
MusicNetworkThread * GetMusicNetworkThread ()
Function Documentation
MusicBackgroundManager* GetMusicBackgroundManager ()
Definition at line 15 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicConnectionPool* GetMusicConnectionPool ()
Definition at line 10 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicDispatchManager* GetMusicDispatchManager ()
Definition at line 20 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicDownLoadManager* GetMusicDownLoadManager ()
Definition at line 40 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicDownLoadQueryFactory* GetMusicDownLoadQueryFactory ()
Definition at line 45 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicHotKeyManager* GetMusicHotKeyManager ()
Definition at line 25 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicNetworkThread* GetMusicNetworkThread ()
Definition at line 50 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicSettingManager* GetMusicSettingManager ()
Definition at line 30 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().
MusicSingleManager* GetMusicSingleManager ()
Definition at line 35 of file musicsingleton.cpp.
References TTKSingleton< T >::createInstance().