TTKMusicplayer: MusicCommentsWidget Class Reference
MusicCommentsWidget Class Reference
The class of the song comment widget.
#include <musiccommentswidget.h>
Public Slots
void createSearchedItems (const MusicSongCommentItem &comments)
void buttonClicked (int index)
void createEMOJILabelWidget ()
void currentEMOJIchanged (const QString &data)
Public Member Functions
MusicCommentsWidget (QWidget *parent=0)
~MusicCommentsWidget ()
virtual void initWidget (bool isPain)
void setCurrentSongName (const QString &name)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void initLabel (const QString &name, int total)
void deleteCommentsItems ()
void createPagingWidget ()
Protected Attributes
bool m_isPain
QTextEdit * m_messageEdit
QLabel * m_topLabel
QLabel * m_commentsLabel
QWidget * m_messageComments
MusicDownLoadCommentsThread * m_commentsThread
QList< MusicCommentsItem * > m_commentsItems
MusicPagingWidgetObject * m_pagingWidgetObject
Detailed Description
The class of the song comment widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 68 of file musiccommentswidget.h.
Constructor & Destructor Documentation
MusicCommentsWidget::MusicCommentsWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 155 of file musiccommentswidget.cpp.
References m_commentsLabel, m_commentsThread, m_isPain, m_messageComments, m_messageEdit, m_pagingWidgetObject, and m_topLabel.
MusicCommentsWidget::~MusicCommentsWidget ()
Definition at line 168 of file musiccommentswidget.cpp.
References deleteCommentsItems(), m_commentsLabel, m_commentsThread, m_messageComments, m_messageEdit, m_pagingWidgetObject, and m_topLabel.
Member Function Documentation
void MusicCommentsWidget::buttonClicked (int index) slot
Paging widget button has changed.
Definition at line 344 of file musiccommentswidget.cpp.
References MusicPagingWidgetObject::currentIndex(), deleteCommentsItems(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), m_commentsThread, m_pagingWidgetObject, MusicPagingWidgetObject::paging(), and MusicDownLoadPagingThread::startToPage().
Referenced by createPagingWidget(), and setCurrentSongName().
void MusicCommentsWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 365 of file musiccommentswidget.cpp.
void MusicCommentsWidget::createEMOJILabelWidget () slot
Create emoji label widget.
Definition at line 352 of file musiccommentswidget.cpp.
References currentEMOJIchanged().
Referenced by initWidget().
void MusicCommentsWidget::createPagingWidget () protected
Create paging items.
Definition at line 404 of file musiccommentswidget.cpp.
References buttonClicked(), MusicPagingWidgetObject::createPagingWidget(), MusicDownLoadPagingThread::getPageSize(), MusicDownLoadPagingThread::getPageTotal(), m_commentsThread, m_messageComments, and m_pagingWidgetObject.
Referenced by setCurrentSongName().
void MusicCommentsWidget::createSearchedItems (const MusicSongCommentItem & comments) slot
Create the current song comment.
Definition at line 330 of file musiccommentswidget.cpp.
References MusicCommentsItem::createSearchedItems(), m_commentsItems, m_isPain, m_messageComments, and MStatic_cast.
Referenced by MusicLrcCommentsWidget::initWidget(), and MusicPlaylistFoundCommentsWidget::initWidget().
void MusicCommentsWidget::currentEMOJIchanged (const QString & data) slot
Current EMOJI changed.
Definition at line 360 of file musiccommentswidget.cpp.
References m_messageEdit.
Referenced by createEMOJILabelWidget().
void MusicCommentsWidget::deleteCommentsItems () protected
Delete comments items.
Definition at line 393 of file musiccommentswidget.cpp.
References m_commentsItems, and m_isPain.
Referenced by buttonClicked(), setCurrentSongName(), and ~MusicCommentsWidget().
QString MusicCommentsWidget::getClassName () static
Get class object name.
Definition at line 179 of file musiccommentswidget.cpp.
void MusicCommentsWidget::initLabel (const QString & name, int total) protected
Int current comment label text.
Definition at line 385 of file musiccommentswidget.cpp.
References m_commentsLabel, and m_topLabel.
Referenced by initWidget(), and setCurrentSongName().
void MusicCommentsWidget::initWidget (bool isPain) virtual
Init widget.
Reimplemented in MusicLrcCommentsWidget, and MusicPlaylistFoundCommentsWidget.
Definition at line 184 of file musiccommentswidget.cpp.
References createEMOJILabelWidget(), initLabel(), m_commentsLabel, m_isPain, m_messageComments, m_messageEdit, m_topLabel, MusicUIObject::MBackgroundStyle01, MusicUIObject::MBackgroundStyle19, MusicUIObject::MBorderStyle02, MusicUIObject::MColorStyle03, MusicUIObject::MColorStyle04, MusicUIObject::MKGBtnPClose, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, and MusicUIObject::MScrollBarStyle03.
Referenced by MusicLrcCommentsWidget::initWidget(), and MusicPlaylistFoundCommentsWidget::initWidget().
void MusicCommentsWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 370 of file musiccommentswidget.cpp.
void MusicCommentsWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 375 of file musiccommentswidget.cpp.
void MusicCommentsWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 380 of file musiccommentswidget.cpp.
void MusicCommentsWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 310 of file musiccommentswidget.cpp.
References buttonClicked(), createPagingWidget(), deleteCommentsItems(), MusicSemaphoreLoop::exec(), MusicDownLoadPagingThread::getPageTotal(), initLabel(), m_commentsThread, m_isPain, m_messageComments, MStatic_cast, and MusicDownLoadCommentsThread::startToSearch().
Referenced by MusicPlaylistFoundInfoWidget::initThirdWidget(), and MusicLrcContainerForInline::showSongCommentsWidget().
Member Data Documentation
QList<MusicCommentsItem*> MusicCommentsWidget::m_commentsItems protected
Definition at line 137 of file musiccommentswidget.h.
Referenced by createSearchedItems(), and deleteCommentsItems().
QLabel * MusicCommentsWidget::m_commentsLabel protected
Definition at line 134 of file musiccommentswidget.h.
Referenced by initLabel(), initWidget(), MusicCommentsWidget(), and ~MusicCommentsWidget().
MusicDownLoadCommentsThread* MusicCommentsWidget::m_commentsThread protected
Definition at line 136 of file musiccommentswidget.h.
Referenced by buttonClicked(), createPagingWidget(), MusicLrcCommentsWidget::initWidget(), MusicPlaylistFoundCommentsWidget::initWidget(), MusicCommentsWidget(), setCurrentSongName(), and ~MusicCommentsWidget().
bool MusicCommentsWidget::m_isPain protected
Definition at line 132 of file musiccommentswidget.h.
Referenced by createSearchedItems(), deleteCommentsItems(), initWidget(), MusicCommentsWidget(), and setCurrentSongName().
QWidget* MusicCommentsWidget::m_messageComments protected
Definition at line 135 of file musiccommentswidget.h.
Referenced by createPagingWidget(), createSearchedItems(), initWidget(), MusicCommentsWidget(), setCurrentSongName(), and ~MusicCommentsWidget().
QTextEdit* MusicCommentsWidget::m_messageEdit protected
Definition at line 133 of file musiccommentswidget.h.
Referenced by currentEMOJIchanged(), initWidget(), MusicCommentsWidget(), and ~MusicCommentsWidget().
MusicPagingWidgetObject* MusicCommentsWidget::m_pagingWidgetObject protected
Definition at line 138 of file musiccommentswidget.h.
Referenced by buttonClicked(), createPagingWidget(), MusicCommentsWidget(), and ~MusicCommentsWidget().
QLabel* MusicCommentsWidget::m_topLabel protected
Definition at line 134 of file musiccommentswidget.h.
Referenced by initLabel(), initWidget(), MusicCommentsWidget(), and ~MusicCommentsWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musiccommentswidget.h
TTKModule/TTKWidget/musicWidgetCoreKits/musiccommentswidget.cpp