TTKMusicplayer: MusicSongCheckToolsRenameThread Class Reference
MusicSongCheckToolsRenameThread Class Reference
The class of the song check tools rename thread.
#include <musicsongchecktoolsthread.h>
Signals
void finished (const MusicSongCheckToolsRenames &items)
Public Member Functions
MusicSongCheckToolsRenameThread (QObject *parent=nullptr)
void setMode (MusicObject::MusicSongCheckToolsMode mode)
MusicObject::MusicSongCheckToolsMode mode () const
void setItemList (const TTKIntList &items)
void setRenameSongs (MusicSongs *songs)
Public Member Functions inherited from MusicAbstractThread
MusicAbstractThread (QObject *parent=nullptr)
virtual ~MusicAbstractThread ()
void stopAndQuitThread ()
Protected Member Functions
virtual void run () override
Protected Attributes
MusicSongs * m_songItems
TTKIntList m_itemIDs
MusicSongCheckToolsRenames m_datas
MusicObject::MusicSongCheckToolsMode m_operateMode
Protected Attributes inherited from MusicAbstractThread
bool m_running
Additional Inherited Members
Public Slots inherited from MusicAbstractThread
void start ()
Detailed Description
The class of the song check tools rename thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicsongchecktoolsthread.h.
Constructor & Destructor Documentation
MusicSongCheckToolsRenameThread::MusicSongCheckToolsRenameThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 4 of file musicsongchecktoolsthread.cpp.
References MusicObject::Check, m_operateMode, and m_songItems.
Member Function Documentation
void MusicSongCheckToolsRenameThread::finished (const MusicSongCheckToolsRenames & items) signal
Rename check finished.
Referenced by run().
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsRenameThread::mode () const inline
Get music song check tool mode.
Definition at line 45 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsWidget::renameCheckFinished().
void MusicSongCheckToolsRenameThread::run () override protected virtual
Thread run now.
Reimplemented from MusicAbstractThread.
Definition at line 16 of file musicsongchecktoolsthread.cpp.
References MusicSongMeta::artist(), MusicObject::Check, finished(), m_datas, m_itemIDs, m_operateMode, MusicSongCheckToolsRename::m_path, MusicSongCheckToolsRename::m_recommendName, MusicAbstractThread::m_running, m_songItems, MusicSongMeta::read(), MusicAbstractThread::run(), and MusicSongMeta::title().
void MusicSongCheckToolsRenameThread::setItemList (const TTKIntList & items) inline
Set item list.
Definition at line 49 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsWidget::renameButtonCheckClicked().
void MusicSongCheckToolsRenameThread::setMode (MusicObject::MusicSongCheckToolsMode mode) inline
Set music song check tool mode.
Definition at line 41 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsWidget::renameButtonCheckClicked(), and MusicSongCheckToolsWidget::renameReCheckButtonClicked().
void MusicSongCheckToolsRenameThread::setRenameSongs (MusicSongs * songs)
Set find file path by given path.
Definition at line 11 of file musicsongchecktoolsthread.cpp.
References m_songItems.
Referenced by MusicSongCheckToolsWidget::renameReCheckButtonClicked().
Member Data Documentation
MusicSongCheckToolsRenames MusicSongCheckToolsRenameThread::m_datas protected
Definition at line 71 of file musicsongchecktoolsthread.h.
Referenced by run().
TTKIntList MusicSongCheckToolsRenameThread::m_itemIDs protected
Definition at line 70 of file musicsongchecktoolsthread.h.
Referenced by run().
MusicObject::MusicSongCheckToolsMode MusicSongCheckToolsRenameThread::m_operateMode protected
Definition at line 72 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsRenameThread(), and run().
MusicSongs* MusicSongCheckToolsRenameThread::m_songItems protected
Definition at line 69 of file musicsongchecktoolsthread.h.
Referenced by MusicSongCheckToolsRenameThread(), run(), and setRenameSongs().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolsthread.h
TTKModule/TTKCore/musicToolsSetsKits/musicsongchecktoolsthread.cpp