TTKMusicPlayer: QDlna Namespace Reference
QDlna Namespace Reference
The namespace of the dlna helper.
Functions
QString makeSocketGetReply (const QString &ip, const QString &port, const QString &data)
QString makeRequest (const QString &methord, const QString &url, int length, const QString &soapAction, const QString &ip, const QString &port)
QString removeHttpHeader (const QString &data)
bool isValid (const QString &data)
int getResponseCode (const QString &data)
Detailed Description
The namespace of the dlna helper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
int QDlna::getResponseCode (const QString & data)
Get response code.
Definition at line 81 of file qdlna.cpp.
References TTK_SPACE.
Referenced by isValid().
bool QDlna::isValid (const QString & data)
Get response code.
Definition at line 76 of file qdlna.cpp.
References getResponseCode().
Referenced by QDlnaClientPrivate::connect(), QDlnaClient::open(), QDlnaClient::pause(), QDlnaClient::play(), QDlnaClient::position(), QDlnaClient::remove(), and QDlnaClient::stop().
QString QDlna::makeRequest (const QString & methord, const QString & url, int length, const QString & soapAction, const QString & ip, const QString & port)
Make request.
Definition at line 39 of file qdlna.cpp.
Referenced by QDlnaClientPrivate::connect(), QDlnaClient::open(), QDlnaClient::pause(), QDlnaClient::play(), QDlnaClient::position(), QDlnaClient::remove(), and QDlnaClient::stop().
QString QDlna::makeSocketGetReply (const QString & ip, const QString & port, const QString & data)
Make socket get reply.
Definition at line 9 of file qdlna.cpp.
Referenced by QDlnaClientPrivate::connect(), QDlnaClient::open(), QDlnaClient::pause(), QDlnaClient::play(), QDlnaClient::position(), QDlnaClient::remove(), and QDlnaClient::stop().
QString QDlna::removeHttpHeader (const QString & data)
Remove http header.
Definition at line 70 of file qdlna.cpp.
Referenced by QDlnaClientPrivate::connect(), and QDlnaClient::position().