TTKMusicplayer: KugouWindow Class Reference
KugouWindow Class Reference
The namespace of the kugou window widget.
#include <kugouwindow.h>
Public Types
enum KuGouType {
KuGouSong, KuGouRadio, KuGouList, KugouMv,
KuGouLive, KuGouLrc, KuGouSingle
}
Public Slots
void goBack ()
void kugouSongIndexChanged (int index)
void kugouRadioIndexChanged (int index)
void kugouMVIndexChanged (int index)
Public Member Functions
KugouWindow (KuGouType type, QWidget *parent=nullptr)
void setUrl (const QString &url)
Protected Member Functions
void createWebViewer ()
void createKugouSongWidget ()
void createKugouRadioWidget ()
void createKugouListWidget ()
void createKugouMVWidget ()
void createKugouSingleWidget ()
void changeClickedButtonStyle (int index)
Detailed Description
The namespace of the kugou window widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file kugouwindow.h.
Member Enumeration Documentation
enum KugouWindow::KuGouType
Enumerator
KuGouSong
KuGou Song
KuGouRadio
KuGou Radio
KuGouList
KuGou List
KugouMv
Kugou Mv
KuGouLive
KuGou Live
KuGouLrc
KuGou Lrc
KuGouSingle
KuGou Single
Definition at line 34 of file kugouwindow.h.
Constructor & Destructor Documentation
KugouWindow::KugouWindow (KuGouType type, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 52 of file kugouwindow.cpp.
References createKugouListWidget(), createKugouMVWidget(), createKugouRadioWidget(), createKugouSingleWidget(), createKugouSongWidget(), KuGouList, KuGouLive, KuGouLrc, KugouMv, KuGouRadio, KuGouSingle, KuGouSong, and TTK_INIT_PRIVATE.
Member Function Documentation
void KugouWindow::changeClickedButtonStyle (int index) protected
Change clicked button style by index.
Definition at line 500 of file kugouwindow.cpp.
References MusicUIObject::MPushButtonStyle01, MusicUIObject::MPushButtonStyle02, and TTK_D.
Referenced by kugouMVIndexChanged(), kugouRadioIndexChanged(), and kugouSongIndexChanged().
void KugouWindow::createKugouListWidget () protected
Create kugou list widget.
Definition at line 407 of file kugouwindow.cpp.
References createWebViewer(), KugouUrl::getListUrl(), MObject_cast, and TTK_D.
Referenced by KugouWindow().
void KugouWindow::createKugouMVWidget () protected
Create kugou mv widget.
Definition at line 435 of file kugouwindow.cpp.
References createWebViewer(), kugouMVIndexChanged(), MusicUIObject::MPushButtonStyle01, MusicUIObject::MWidgetStyle01, and TTK_D.
Referenced by KugouWindow().
void KugouWindow::createKugouRadioWidget () protected
Create kugou radio widget.
Definition at line 357 of file kugouwindow.cpp.
References createWebViewer(), kugouRadioIndexChanged(), MusicUIObject::MPushButtonStyle01, MusicUIObject::MWidgetStyle01, and TTK_D.
Referenced by KugouWindow().
void KugouWindow::createKugouSingleWidget () protected
Create kugou single widget.
Definition at line 481 of file kugouwindow.cpp.
References createWebViewer(), and TTK_D.
Referenced by KugouWindow().
void KugouWindow::createKugouSongWidget () protected
Create kugou song widget.
Definition at line 292 of file kugouwindow.cpp.
References createWebViewer(), kugouSongIndexChanged(), MusicUIObject::MPushButtonStyle01, MusicUIObject::MWidgetStyle01, and TTK_D.
Referenced by KugouWindow().
void KugouWindow::createWebViewer () protected
Create web view widget.
Definition at line 261 of file kugouwindow.cpp.
References TTK_D.
Referenced by createKugouListWidget(), createKugouMVWidget(), createKugouRadioWidget(), createKugouSingleWidget(), and createKugouSongWidget().
void KugouWindow::goBack () slot
Set web index go back.
Definition at line 123 of file kugouwindow.cpp.
References MObject_cast, and TTK_D.
void KugouWindow::kugouMVIndexChanged (int index) slot
Kugou MV index changed.
Definition at line 223 of file kugouwindow.cpp.
References changeClickedButtonStyle(), KugouUrl::getMVFanxingUrl(), KugouUrl::getMVRadioUrl(), KugouUrl::getMVRecommendUrl(), MObject_cast, and TTK_D.
Referenced by createKugouMVWidget().
void KugouWindow::kugouRadioIndexChanged (int index) slot
Kugou radio index changed.
Definition at line 184 of file kugouwindow.cpp.
References changeClickedButtonStyle(), KugouUrl::getRadioFxUrl(), KugouUrl::getRadioHighFmUrl(), KugouUrl::getRadioHomeUrl(), KugouUrl::getRadioPublicUrl(), MObject_cast, and TTK_D.
Referenced by createKugouRadioWidget().
void KugouWindow::kugouSongIndexChanged (int index) slot
Kugou song index changed.
Definition at line 143 of file kugouwindow.cpp.
References changeClickedButtonStyle(), KugouUrl::getSongCategoryUrl(), KugouUrl::getSongHeroesUrl(), KugouUrl::getSongRankUrl(), KugouUrl::getSongRecommendUrl(), KugouUrl::getSongShowUrl(), KugouUrl::getSongSingerUrl(), MObject_cast, and TTK_D.
Referenced by createKugouSongWidget().
void KugouWindow::setUrl (const QString & url)
Set current web viewer url to show.
Definition at line 94 of file kugouwindow.cpp.
References MObject_cast, and TTK_D.
Referenced by MusicRightAreaWidget::musicFunctionClicked().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qkugou/kugouwindow.h
TTKThirdParty/TTKExtras/qkugou/kugouwindow.cpp