TTKMusicplayer: MusicTransformWidget Class Reference
MusicTransformWidget Class Reference
The class of the transform widget.
#include <musictransformwidget.h>
Public Types
enum TransformType { Music, Lrc }
Public Slots
void initInputPath ()
void initOutputPath ()
void startTransform ()
void transformFinish ()
void folderBoxChecked ()
void krc2lrcBoxChecked (bool check)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicTransformWidget (QWidget *parent=nullptr)
~MusicTransformWidget ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
QString transformSongName () const
void initControlParameter () const
bool processTransform (const QString &para)
void setMusicCheckedControl (bool enable)
void setCheckedControl (bool enable)
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
Ui::MusicTransformWidget * m_ui
QProcess * m_process
QStringList m_path
TransformType m_currentType
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the transform widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musictransformwidget.h.
Member Enumeration Documentation
enum MusicTransformWidget::TransformType
Enumerator
Music
Music category
Lrc
Lrc category
Definition at line 40 of file musictransformwidget.h.
Constructor & Destructor Documentation
MusicTransformWidget::MusicTransformWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musictransformwidget.cpp.
References folderBoxChecked(), MusicUtils::Widget::generateComboBoxFormat(), MusicGifLabelWidget::Gif_Cicle_Blue, initControlParameter(), initInputPath(), initOutputPath(), krc2lrcBoxChecked(), m_currentType, m_process, m_ui, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSToolButtonStyle04, Music, startTransform(), and transformFinish().
MusicTransformWidget::~MusicTransformWidget ()
Definition at line 64 of file musictransformwidget.cpp.
References m_process, and m_ui.
Member Function Documentation
int MusicTransformWidget::exec () virtual slot
Override exec function.
Definition at line 269 of file musictransformwidget.cpp.
References m_ui, MAKE_KRC2LRC_FULL, MAKE_TRANSFORM_FULL, MusicToastLabel::popup(), and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicToolSetsWidget::itemHasClicked(), and MusicSongsListTableWidget::musicTransformWidget().
void MusicTransformWidget::folderBoxChecked () slot
Input is dir not file.
Definition at line 235 of file musictransformwidget.cpp.
References m_path, and m_ui.
Referenced by krc2lrcBoxChecked(), and MusicTransformWidget().
void MusicTransformWidget::initControlParameter () const protected
Init control parameter.
Definition at line 71 of file musictransformwidget.cpp.
References m_ui.
Referenced by MusicTransformWidget().
void MusicTransformWidget::initInputPath () slot
Selected input path.
Definition at line 82 of file musictransformwidget.cpp.
References MusicUtils::Widget::elidedText(), MusicUtils::File::fileListByDir(), LINE_WIDTH, m_currentType, m_path, m_ui, Music, MusicUtils::File::openDirectoryDialog(), and MusicUtils::File::openFileDialog().
Referenced by MusicTransformWidget().
void MusicTransformWidget::initOutputPath () slot
Selected out path.
Definition at line 129 of file musictransformwidget.cpp.
References m_ui, and MusicUtils::File::openDirectoryDialog().
Referenced by MusicTransformWidget().
void MusicTransformWidget::krc2lrcBoxChecked (bool check) slot
Transform krc file to lrc file.
Definition at line 242 of file musictransformwidget.cpp.
References folderBoxChecked(), Lrc, m_currentType, Music, and setMusicCheckedControl().
Referenced by MusicTransformWidget().
bool MusicTransformWidget::processTransform (const QString & para) protected
Start a process to transform.
Definition at line 180 of file musictransformwidget.cpp.
References LRC_FILE, m_currentType, m_path, m_process, m_ui, Music, MusicToastLabel::popup(), transformSongName(), and TTK_LOGGER_INFO.
Referenced by startTransform(), and transformFinish().
void MusicTransformWidget::setCheckedControl (bool enable) protected
Set control enable false when it begin.
Definition at line 257 of file musictransformwidget.cpp.
References m_ui, and setMusicCheckedControl().
Referenced by startTransform(), and transformFinish().
void MusicTransformWidget::setMusicCheckedControl (bool enable) protected
Set music control enable or false when trans lrc.
Definition at line 249 of file musictransformwidget.cpp.
References m_ui.
Referenced by krc2lrcBoxChecked(), setCheckedControl(), and transformFinish().
void MusicTransformWidget::startTransform () slot
Start to transform.
Definition at line 222 of file musictransformwidget.cpp.
References m_currentType, m_ui, MAKE_KRC2LRC_FULL, MAKE_TRANSFORM_FULL, Music, processTransform(), and setCheckedControl().
Referenced by MusicTransformWidget().
void MusicTransformWidget::transformFinish () slot
Transform finished.
Definition at line 147 of file musictransformwidget.cpp.
References MusicUtils::Widget::elidedText(), LINE_WIDTH, Lrc, m_currentType, m_path, m_ui, MAKE_KRC2LRC_FULL, MAKE_TRANSFORM_FULL, Music, processTransform(), setCheckedControl(), and setMusicCheckedControl().
Referenced by MusicTransformWidget().
QString MusicTransformWidget::transformSongName () const protected
Get transform song name.
Definition at line 138 of file musictransformwidget.cpp.
References m_path.
Referenced by processTransform().
Member Data Documentation
TransformType MusicTransformWidget::m_currentType protected
Definition at line 106 of file musictransformwidget.h.
Referenced by initInputPath(), krc2lrcBoxChecked(), MusicTransformWidget(), processTransform(), startTransform(), and transformFinish().
QStringList MusicTransformWidget::m_path protected
Definition at line 105 of file musictransformwidget.h.
Referenced by folderBoxChecked(), initInputPath(), processTransform(), transformFinish(), and transformSongName().
QProcess* MusicTransformWidget::m_process protected
Definition at line 104 of file musictransformwidget.h.
Referenced by MusicTransformWidget(), processTransform(), and ~MusicTransformWidget().
Ui::MusicTransformWidget* MusicTransformWidget::m_ui protected
Definition at line 103 of file musictransformwidget.h.
Referenced by exec(), folderBoxChecked(), initControlParameter(), initInputPath(), initOutputPath(), MusicTransformWidget(), processTransform(), setCheckedControl(), setMusicCheckedControl(), startTransform(), transformFinish(), and ~MusicTransformWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musictransformwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musictransformwidget.cpp