TTKMusicplayer: MusicWebDJRadioInfoWidget Class Reference
MusicWebDJRadioInfoWidget Class Reference
The class of dj radio music info widget.
#include <musicwebdjradioinfowidget.h>
Public Slots
void queryAllFinished ()
void createCategoryInfoItem (const MusicResultsItem &item)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Signals
void backToMainMenu ()
Public Member Functions
MusicWebDJRadioInfoWidget (QWidget *parent=nullptr)
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameById (const QString &id) overridefinal
virtual void resizeWindow () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Protected Member Functions
void createLabels ()
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Additional Inherited Members
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of dj radio music info widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 49 of file musicwebdjradioinfowidget.h.
Constructor & Destructor Documentation
MusicWebDJRadioInfoWidget::MusicWebDJRadioInfoWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 30 of file musicwebdjradioinfowidget.cpp.
References createCategoryInfoItem(), MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_statusLabel, and MusicItemQueryTableWidget::setQueryInput().
Member Function Documentation
void MusicWebDJRadioInfoWidget::backToMainMenu () signal
Set current index to main menu page.
Referenced by createLabels().
void MusicWebDJRadioInfoWidget::createCategoryInfoItem (const MusicResultsItem & item) slot
Create the current category info item.
Definition at line 82 of file musicwebdjradioinfowidget.cpp.
References createLabels(), MusicAbstractItemQueryWidget::downLoadFinished(), MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicResultsItem::m_coverUrl, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicResultsItem::m_updateTime, MusicDownloadSourceRequest::startToDownload(), TTK_NULL_STR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicWebDJRadioInfoWidget().
void MusicWebDJRadioInfoWidget::createLabels () protected
Create init interface lables.
Definition at line 118 of file musicwebdjradioinfowidget.cpp.
References backToMainMenu(), MusicUtils::Widget::generateVScrollAreaFormat(), MusicAbstractItemQueryWidget::initFirstWidget(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicAbstractItemQueryWidget::m_iconLabel, MusicAbstractItemQueryWidget::m_mainWindow, MusicResultsItem::m_name, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songButton, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle03, MusicUIObject::MQSSPushButtonStyle03, QtButtonGroupConnect, and TTK_DEFAULT_STR.
Referenced by createCategoryInfoItem().
void MusicWebDJRadioInfoWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 77 of file musicwebdjradioinfowidget.cpp.
References MusicAbstractItemQueryWidget::setSongCountText().
void MusicWebDJRadioInfoWidget::resizeWindow () final override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 55 of file musicwebdjradioinfowidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicItemQueryTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicWebDJRadioQueryWidget::resizeWindow().
void MusicWebDJRadioInfoWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 44 of file musicwebdjradioinfowidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::setSongName(), and MusicItemQueryTableWidget::startSearchQuery().
Referenced by MusicWebDJRadioQueryWidget::currentRadioClicked().
void MusicWebDJRadioInfoWidget::setSongNameById (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 50 of file musicwebdjradioinfowidget.cpp.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebdjradioinfowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebdjradioinfowidget.cpp