TTKMusicplayer: QxtGlobalShortcut Class Reference
QxtGlobalShortcut Class Reference
The namespace of the qxt global shortcut.
#include <qxtglobalshortcut.h>
Public Slots
void setEnabled (bool enabled=true)
void setDisabled (bool disabled=true)
Signals
void activated ()
Public Member Functions
QxtGlobalShortcut (QObject *parent=0)
QxtGlobalShortcut (const QKeySequence &shortcut, QObject *parent=0)
virtual ~QxtGlobalShortcut ()
QKeySequence shortcut () const
bool setShortcut (const QKeySequence &shortcut)
bool isEnabled () const
Properties
bool enabled
whether the shortcut is enabled
QKeySequence shortcut
the shortcut key sequence
Detailed Description
The namespace of the qxt global shortcut.
The QxtGlobalShortcut class provides a global shortcut aka "hotkey".
Author
libqxt found.nosp@m.atio.nosp@m.n@lib.nosp@m.qxt..nosp@m.org
QxtGui A global shortcut triggers even if the application is not active. This makes it easy to implement applications that react to certain shortcuts still if some other application is active or if the application is for example minimized to the system tray.
Example usage:
QxtGlobalShortcut* shortcut = new QxtGlobalShortcut(window);
connect(shortcut, SIGNAL(activated()), window, SLOT(toggleVisibility()));
shortcut->setShortcut(QKeySequence("Ctrl+Shift+F12"));
{Note:} Since Qxt 0.6 QxtGlobalShortcut no more requires QxtApplication.
Definition at line 21 of file qxtglobalshortcut.h.
Constructor & Destructor Documentation
QxtGlobalShortcut::QxtGlobalShortcut (QObject * parent = 0) explicit
Constructs a new QxtGlobalShortcut with parent.
Definition at line 126 of file qxtglobalshortcut.cpp.
References QXT_INIT_PRIVATE.
QxtGlobalShortcut::QxtGlobalShortcut (const QKeySequence & shortcut, QObject * parent = 0) explicit
Constructs a new QxtGlobalShortcut with shortcut and parent.
Definition at line 135 of file qxtglobalshortcut.cpp.
References QXT_INIT_PRIVATE, and setShortcut().
QxtGlobalShortcut::~QxtGlobalShortcut () virtual
Destructs the QxtGlobalShortcut.
Definition at line 145 of file qxtglobalshortcut.cpp.
References key.
Member Function Documentation
QxtGlobalShortcut::activated () signal
This signal is emitted when the user types the shortcut's key sequence.
See also
shortcut
Referenced by QxtGlobalShortcutPrivate::activateShortcut().
bool QxtGlobalShortcut::isEnabled () const
Definition at line 187 of file qxtglobalshortcut.cpp.
Referenced by QxtGlobalShortcutPrivate::activateShortcut().
void QxtGlobalShortcut::setDisabled (bool disabled = true) slot
Sets the shortcut disabled.
See also
enabled
Definition at line 202 of file qxtglobalshortcut.cpp.
void QxtGlobalShortcut::setEnabled (bool enabled = true) slot
Definition at line 192 of file qxtglobalshortcut.cpp.
References enabled.
Referenced by MusicHotKeyManager::enabledAll().
bool QxtGlobalShortcut::setShortcut (const QKeySequence & shortcut)
Definition at line 170 of file qxtglobalshortcut.cpp.
References key.
Referenced by QxtGlobalShortcut().
QKeySequence QxtGlobalShortcut::shortcut () const
Property Documentation
QxtGlobalShortcut::enabled read write
whether the shortcut is enabled
A disabled shortcut does not get activated.
The default value is true.
See also
setDisabled()
Definition at line 25 of file qxtglobalshortcut.h.
Referenced by setEnabled().
QKeySequence QxtGlobalShortcut::shortcut read write
the shortcut key sequence
{Note:} Notice that corresponding key press and release events are not delivered for registered global shortcuts even if they are disabled. Also, comma separated key sequences are not supported. Only the first part is used:
qxtShortcut->setShortcut(QKeySequence("Ctrl+Alt+A,Ctrl+Alt+B"));
Q_ASSERT(qxtShortcut->shortcut() == QKeySequence("Ctrl+Alt+A"));
Definition at line 26 of file qxtglobalshortcut.h.
Referenced by MusicHotKeyManager::getKeys().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut.h
TTKThirdParty/TTKExtras/qshortcut/qxtglobalshortcut.cpp