TTKMusicplayer: MusicSongsListAbstractTableWidget Class Reference
MusicSongsListAbstractTableWidget Class Reference
The class of the songs list abstract table widget.
#include <musicsongslistabstracttablewidget.h>
Public Slots
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
void musicSongMovieFoundPy ()
void musicSimilarFoundWidgetPy ()
void musicSongSharedWidgetPy ()
void musicSongKMicroWidgetPy ()
Public Slots inherited from MusicSlowMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void isCurrentIndexs (bool &state)
Public Member Functions
MusicSongsListAbstractTableWidget (QWidget *parent=0)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void updateSongsFileName (const MusicSongs &songs)
virtual void selectRow (int index)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSlowMovingTableWidget
MusicSlowMovingTableWidget (QWidget *parent=0)
virtual ~MusicSlowMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicSlowMovingTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSlowMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSlowMovingTableWidget
bool m_isFirstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the songs list abstract table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicsongslistabstracttablewidget.h.
Constructor & Destructor Documentation
MusicSongsListAbstractTableWidget::MusicSongsListAbstractTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 12 of file musicsongslistabstracttablewidget.cpp.
References m_hasParentToolIndex, m_parentToolIndex, and m_playRowIndex.
MusicSongsListAbstractTableWidget::~MusicSongsListAbstractTableWidget () virtual
Definition at line 22 of file musicsongslistabstracttablewidget.cpp.
Member Function Documentation
int MusicSongsListAbstractTableWidget::allRowsHeight () const
Get all rows height.
Definition at line 48 of file musicsongslistabstracttablewidget.cpp.
Referenced by MusicSongsListPlayedTableWidget::replacePlayWidgetRow(), MusicSongsListTableWidget::replacePlayWidgetRow(), MusicSongsListPlayedTableWidget::selectRow(), MusicSongsListTableWidget::selectRow(), MusicSongsListPlayedTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setMusicSongsSearchedFileName(), MusicSongsListTableWidget::updateSongsFileName(), and MusicSongsListPlayedTableWidget::updateSongsFileName().
void MusicSongsListAbstractTableWidget::createMoreMenu (QMenu * menu) protected
Create more menu information.
Definition at line 249 of file musicsongslistabstracttablewidget.cpp.
References MusicUIObject::MMenuStyle02, musicSimilarFoundWidget(), musicSongKMicroWidget(), musicSongSharedWidget(), and musicSongTransferWidget().
Referenced by MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), MusicSongsListTableWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::listCellClicked(), and MusicSongsListTableWidget::listCellClicked().
QString MusicSongsListAbstractTableWidget::getClassName () static
Get class object name.
Definition at line 27 of file musicsongslistabstracttablewidget.cpp.
QString MusicSongsListAbstractTableWidget::getCurrentSongName () const protected
Get current song name.
Definition at line 278 of file musicsongslistabstracttablewidget.cpp.
References getSongName().
Referenced by MusicSongsListTableWidget::createContextMenu(), musicAlbumFoundWidget(), musicOpenFileDir(), MusicSongsListTableWidget::musicSearchQuery(), musicSimilarFoundWidget(), musicSongDownload(), musicSongKMicroWidget(), musicSongMovieFound(), and musicSongSharedWidget().
QString MusicSongsListAbstractTableWidget::getCurrentSongPath () const protected
Get current song path.
Definition at line 263 of file musicsongslistabstracttablewidget.cpp.
References getSongPath().
Referenced by musicFileInformation().
int MusicSongsListAbstractTableWidget::getPlayRowIndex () const inline
Get the current play row.
Definition at line 73 of file musicsongslistabstracttablewidget.h.
Referenced by MusicPlayedListPopWidget::insert(), and MusicPlayedListPopWidget::setDeleteItemAt().
QString MusicSongsListAbstractTableWidget::getSongName (int index) const protected
Get song name.
Definition at line 288 of file musicsongslistabstracttablewidget.cpp.
References m_musicSongs.
Referenced by getCurrentSongName(), musicSimilarFoundWidgetPy(), musicSongKMicroWidgetPy(), musicSongMovieFoundPy(), and musicSongSharedWidgetPy().
QString MusicSongsListAbstractTableWidget::getSongPath (int index) const protected
Get song path.
Definition at line 273 of file musicsongslistabstracttablewidget.cpp.
References m_musicSongs.
Referenced by getCurrentSongPath().
void MusicSongsListAbstractTableWidget::isCurrentIndexs (bool & state) signal
Check is current play stack widget.
Referenced by setDeleteItemAll(), MusicSongsListTableWidget::showTimeOut(), and MusicSongsListTableWidget::startToDrag().
void MusicSongsListAbstractTableWidget::musicAlbumFoundWidget () slot
Open music album found widget.
Definition at line 135 of file musicsongslistabstracttablewidget.cpp.
References getCurrentSongName(), MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicAlbumFound().
Referenced by MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), and MusicSongsListTableWidget::contextMenuEvent().
void MusicSongsListAbstractTableWidget::musicFileInformation () slot
Open music file information widget.
Definition at line 113 of file musicsongslistabstracttablewidget.cpp.
References MusicFileInformationWidget::exec(), getCurrentSongPath(), and MusicFileInformationWidget::setFileInformation().
Referenced by MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), and MusicSongsListTableWidget::contextMenuEvent().
void MusicSongsListAbstractTableWidget::musicOpenFileDir () slot
Open the music at local path.
Definition at line 91 of file musicsongslistabstracttablewidget.cpp.
References ALG_DOWNLOAD_KEY, MusicMessageBox::exec(), getCurrentSongName(), m_musicSongs, MusicUtils::Algorithm::mdII(), MusicUtils::Core::openUrl(), and MusicMessageBox::setText().
Referenced by MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), and MusicSongsListTableWidget::contextMenuEvent().
void MusicSongsListAbstractTableWidget::musicPlayClicked () slot
Music item has double been clicked.
Definition at line 63 of file musicsongslistabstracttablewidget.cpp.
Referenced by MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), and MusicSongsListTableWidget::contextMenuEvent().
void MusicSongsListAbstractTableWidget::musicSimilarFoundWidget () slot
Open music similar found widget.
Definition at line 145 of file musicsongslistabstracttablewidget.cpp.
References getCurrentSongName(), MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicSimilarFound().
Referenced by createMoreMenu().
void MusicSongsListAbstractTableWidget::musicSimilarFoundWidgetPy () slot
Open music similar found widget in play widget.
Definition at line 214 of file musicsongslistabstracttablewidget.cpp.
References getSongName(), MusicRightAreaWidget::instance(), m_playRowIndex, and MusicRightAreaWidget::musicSimilarFound().
void MusicSongsListAbstractTableWidget::musicSongDownload () slot
Open music song download widget.
Definition at line 192 of file musicsongslistabstracttablewidget.cpp.
References getCurrentSongName(), MusicDownLoadQueryThreadAbstract::MusicQuery, MusicDownloadWidget::setSongName(), and MusicDownloadWidget::show().
Referenced by MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicSongsListPlayedTableWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), MusicSongsListTableWidget::contextMenuEvent(), and MusicSongsListPlayedTableWidget::listCellClicked().
void MusicSongsListAbstractTableWidget::musicSongKMicroWidget () slot
Open music song KMicro widget.
Definition at line 170 of file musicsongslistabstracttablewidget.cpp.
References MusicLeftAreaWidget::createSoundKMicroWidget(), getCurrentSongName(), and MusicLeftAreaWidget::instance().
Referenced by createMoreMenu().
void MusicSongsListAbstractTableWidget::musicSongKMicroWidgetPy () slot
Open music song KMicro widget in play widget.
Definition at line 239 of file musicsongslistabstracttablewidget.cpp.
References MusicLeftAreaWidget::createSoundKMicroWidget(), getSongName(), MusicLeftAreaWidget::instance(), and m_playRowIndex.
void MusicSongsListAbstractTableWidget::musicSongMovieFound () slot
To search song mv by song name.
Definition at line 125 of file musicsongslistabstracttablewidget.cpp.
References getCurrentSongName(), MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicVideoButtonSearched().
Referenced by MusicSongsListTableWidget::contextMenuEvent(), and MusicSongsListTableWidget::listCellClicked().
void MusicSongsListAbstractTableWidget::musicSongMovieFoundPy () slot
To search song mv by song name in play widget.
Definition at line 204 of file musicsongslistabstracttablewidget.cpp.
References getSongName(), MusicRightAreaWidget::instance(), m_playRowIndex, and MusicRightAreaWidget::musicVideoButtonSearched().
void MusicSongsListAbstractTableWidget::musicSongSharedWidget () slot
Open music song shared widget.
Definition at line 155 of file musicsongslistabstracttablewidget.cpp.
References MusicSongSharingWidget::exec(), getCurrentSongName(), MusicSongSharingWidget::setData(), and MusicSongSharingWidget::Song.
Referenced by createMoreMenu().
void MusicSongsListAbstractTableWidget::musicSongSharedWidgetPy () slot
Open music song shared widget in play widget.
Definition at line 224 of file musicsongslistabstracttablewidget.cpp.
References MusicSongSharingWidget::exec(), getSongName(), m_playRowIndex, MusicSongSharingWidget::setData(), and MusicSongSharingWidget::Song.
void MusicSongsListAbstractTableWidget::musicSongTransferWidget () slot
Open music song transfer widget.
Definition at line 180 of file musicsongslistabstracttablewidget.cpp.
References MusicConnectTransferWidget::exec(), m_hasParentToolIndex, m_musicSongs, m_parentToolIndex, and MusicConnectTransferWidget::redirectToCurrentSong().
Referenced by createMoreMenu().
void MusicSongsListAbstractTableWidget::selectRow (int index) virtual
Select the current play row by given index.
Reimplemented in MusicSongsListPlayedTableWidget, and MusicSongsListTableWidget.
Definition at line 43 of file musicsongslistabstracttablewidget.cpp.
Referenced by MusicSongsListPlayedTableWidget::selectRow(), and MusicSongsListTableWidget::selectRow().
void MusicSongsListAbstractTableWidget::setDeleteItemAll () slot
Delete all items from list.
Definition at line 78 of file musicsongslistabstracttablewidget.cpp.
References MusicApplication::instance(), isCurrentIndexs(), MusicApplication::musicPlayIndex(), and setDeleteItemAt().
Referenced by MusicDownloadRecordWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), MusicSongsListTableWidget::contextMenuEvent(), and MusicSongsSummariziedWidget::deleteRowItemAll().
void MusicSongsListAbstractTableWidget::setDeleteItemAt () virtual slot
Delete item from list at current row.
Definition at line 73 of file musicsongslistabstracttablewidget.cpp.
Referenced by setDeleteItemAll().
void MusicSongsListAbstractTableWidget::setParentToolIndex (int index)
Set parent tool index.
Definition at line 58 of file musicsongslistabstracttablewidget.cpp.
References m_parentToolIndex.
Referenced by MusicSongsSummariziedWidget::createWidgetItem(), and MusicSongsSummariziedWidget::resetToolIndex().
void MusicSongsListAbstractTableWidget::setPlayRowIndex (int index) inline
Get the current play row.
Definition at line 69 of file musicsongslistabstracttablewidget.h.
Referenced by MusicPlayedListPopWidget::insert(), MusicPlayedListPopWidget::remove(), MusicPlayedListPopWidget::setDeleteItemAt(), and MusicPlayedListPopWidget::setPlayEmpty().
void MusicSongsListAbstractTableWidget::setSongsFileName (MusicSongs * songs) virtual
Set songs file names.
Definition at line 32 of file musicsongslistabstracttablewidget.cpp.
References m_musicSongs, and updateSongsFileName().
Referenced by MusicSongsSummariziedWidget::createWidgetItem(), MusicPlayedListPopWidget::initWidget(), and MusicSongsSummariziedWidget::musicListSongSortBy().
void MusicSongsListAbstractTableWidget::updateSongsFileName (const MusicSongs & songs) virtual
Update songs file names in table.
Reimplemented in MusicSongsListPlayedTableWidget, and MusicSongsListTableWidget.
Definition at line 38 of file musicsongslistabstracttablewidget.cpp.
Referenced by setSongsFileName().
Member Data Documentation
bool MusicSongsListAbstractTableWidget::m_hasParentToolIndex protected
Definition at line 171 of file musicsongslistabstracttablewidget.h.
Referenced by MusicSongsListAbstractTableWidget(), MusicSongsListPlayedTableWidget::MusicSongsListPlayedTableWidget(), and musicSongTransferWidget().
MusicSongs* MusicSongsListAbstractTableWidget::m_musicSongs protected
Definition at line 170 of file musicsongslistabstracttablewidget.h.
Referenced by MusicLocalSongsTableWidget::addItems(), MusicLocalSongsTableWidget::clear(), MusicLocalSongsTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::contextMenuEvent(), MusicCloudDownloadTableWidget::contextMenuEvent(), MusicDownloadRecordWidget::createItem(), MusicCloudDownloadTableWidget::createItem(), MusicSongsListTableWidget::createUploadFileWidget(), getSongName(), getSongPath(), MusicSongsListPlayedTableWidget::listCellEntered(), MusicSongsListTableWidget::listCellEntered(), MusicSongsListTableWidget::musicAddToPlayedList(), MusicSongsListTableWidget::musicAddToPlayLater(), musicOpenFileDir(), MusicDownloadRecordWidget::musicSongsFileName(), MusicCloudDownloadTableWidget::musicSongsFileName(), musicSongTransferWidget(), MusicSongsListPlayedTableWidget::replacePlayWidgetRow(), MusicSongsListTableWidget::replacePlayWidgetRow(), MusicSongsListTableWidget::selectRow(), MusicSongsListPlayedTableWidget::selectRow(), MusicSongsListTableWidget::setChangSongName(), MusicDownloadRecordWidget::setDeleteItemAt(), MusicSongsListPlayedTableWidget::setDeleteItemAt(), MusicCloudDownloadTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setMusicSongsSearchedFileName(), setSongsFileName(), MusicSongsListTableWidget::showTimeOut(), MusicCloudDownloadTableWidget::~MusicCloudDownloadTableWidget(), MusicDownloadRecordWidget::~MusicDownloadRecordWidget(), MusicLocalSongsTableWidget::~MusicLocalSongsTableWidget(), and MusicSongsListTableWidget::~MusicSongsListTableWidget().
int MusicSongsListAbstractTableWidget::m_parentToolIndex protected
Definition at line 169 of file musicsongslistabstracttablewidget.h.
Referenced by MusicSongsListTableWidget::contextMenuEvent(), MusicSongsListTableWidget::createUploadFileWidget(), MusicSongsListTableWidget::musicAddToPlayedList(), MusicSongsListTableWidget::musicAddToPlayLater(), MusicSongsListTableWidget::musicListSongSortBy(), MusicSongsListAbstractTableWidget(), MusicSongsListTableWidget::MusicSongsListTableWidget(), musicSongTransferWidget(), and setParentToolIndex().
int MusicSongsListAbstractTableWidget::m_playRowIndex protected
Definition at line 169 of file musicsongslistabstracttablewidget.h.
Referenced by MusicSongsListTableWidget::clearAllItems(), MusicSongsListPlayedTableWidget::clearAllItems(), MusicSongsListTableWidget::getPlayRowIndex(), MusicSongsListPlayedTableWidget::listCellClicked(), MusicSongsListTableWidget::listCellClicked(), musicSimilarFoundWidgetPy(), musicSongKMicroWidgetPy(), musicSongMovieFoundPy(), musicSongSharedWidgetPy(), MusicSongsListAbstractTableWidget(), MusicSongsListPlayedTableWidget::MusicSongsListPlayedTableWidget(), MusicSongsListPlayedTableWidget::replacePlayWidgetRow(), MusicSongsListTableWidget::replacePlayWidgetRow(), MusicSongsListPlayedTableWidget::selectPlayedRow(), MusicSongsListTableWidget::selectRow(), MusicSongsListPlayedTableWidget::selectRow(), MusicSongsListTableWidget::setChangSongName(), MusicSongsListPlayedTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setItemRenameFinished(), and MusicSongsListTableWidget::startToDrag().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicsongslistabstracttablewidget.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicsongslistabstracttablewidget.cpp