TTKMusicplayer: MusicUtils::TTKQmmp Namespace Reference
MusicUtils::TTKQmmp Namespace Reference
Functions
TTK_MODULE_EXPORT QString pluginPath (const QString &module, const QString &format)
TTK_MODULE_EXPORT void updateConfig ()
TTK_MODULE_EXPORT void enabledEffectPlugin (bool enable, const QString &name=QString())
TTK_MODULE_EXPORT MusicPluginPropertyList effectPlugins ()
TTK_MODULE_EXPORT void showEffectSetting (const QString &name, QWidget *parent)
TTK_MODULE_EXPORT void enabledVisualPlugin (const QString &name, bool enable)
TTK_MODULE_EXPORT void updateRippleConfig ()
Function Documentation
MusicPluginPropertyList MusicUtils::TTKQmmp::effectPlugins ()
Check effect is valid.
Definition at line 50 of file musicqmmputils.cpp.
References Effect::factories(), and MusicPluginProperty::m_type.
Referenced by MusicSoundEffectsWidget::readSoundEffect().
void MusicUtils::TTKQmmp::enabledEffectPlugin (bool enable, const QString & name = QString())
Enable effect module control.
Definition at line 34 of file musicqmmputils.cpp.
References Effect::factories(), name, and Effect::setEnabled().
Referenced by MusicApplicationModule::musicEffectChanged(), MusicEnhancedPopWidget::setEnhancedMusicConfig(), and MusicSoundEffectsItemWidget::setPluginEnabled().
void MusicUtils::TTKQmmp::enabledVisualPlugin (const QString & name, bool enable)
Enable visual module control.
Definition at line 82 of file musicqmmputils.cpp.
References Visual::factories(), name, and Visual::setEnabled().
Referenced by MusicSpectrumWidget::createModuleWidget(), MusicSpectrumWidget::createSpectrumWidget(), MusicRemoteWidgetForRipple::createVisualWidget(), MusicSpectrumWidget::fullscreenByUser(), MusicRippleSpecturmModule::removeSpectrum(), MusicRemoteWidgetForRipple::removeVisualWidget(), MusicRippleSpecturmModule::show(), and MusicSpectrumWidget::~MusicSpectrumWidget().
QString MusicUtils::TTKQmmp::pluginPath (const QString & module, const QString & format)
Get qmmp plugin dir path.
Definition at line 11 of file musicqmmputils.cpp.
References MusicObject::applicationPath().
Referenced by MusicSpectrumWidget::createLightWidget(), and MusicReplayGainWidget::initialize().
void MusicUtils::TTKQmmp::showEffectSetting (const QString & name, QWidget * parent)
Show effect setting control.
Definition at line 70 of file musicqmmputils.cpp.
References Effect::factories(), and name.
Referenced by MusicSoundEffectsItemWidget::soundEffectValueChanged().
void MusicUtils::TTKQmmp::updateConfig ()
Update qmmp config file transfer.
Definition at line 22 of file musicqmmputils.cpp.
References ARCHIVE_DIR_DIR_FULL, CACHE_DIR_FULL, and Qmmp::configFile().
Referenced by MusicRunTimeManager::run().
void MusicUtils::TTKQmmp::updateRippleConfig ()
Update ripple spectrum config.
Definition at line 94 of file musicqmmputils.cpp.
References Qmmp::configFile(), G_SETTING_PTR, and MusicSettingManager::RippleSpectrumColor.
Referenced by MusicRippleSpecturmModule::update().