TTKMusicPlayer: QAlgorithm Namespace Reference
QAlgorithm Namespace Reference
Classes
class Aes
The class of the aes wrapper.
class CubeWave
The class of the cube wave.
class CubeWavePrivate
The class of the cube wave private.
class Des
The class of the des wrapper.
class DesPrivate
The class of the des wrapper private.
class GaussBlur
The class of the gauss blur.
class SharpeImage
The class of the sharpe image.
class SharpeImagePrivate
The class of the sharpe image private.
class WaterWave
The class of the water wave.
class WaterWavePrivate
The class of the water wave private.
Functions
static bool isBase64 (unsigned char c)
TTKString base64Encode (const unsigned char *bytes, unsigned int length)
TTKString base64Decode (const TTKString &bytes)
static bool isBase64 (unsigned char c)
void initRandom ()
int random (int value)
Variables
static const char * base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static const char * base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static constexpr quint64 ARRAYMASK []
static constexpr int ARRAYIP []
static constexpr int ARRAYE []
static constexpr char MATRIXNSBOX [8][64]
static constexpr int ARRAYP []
static constexpr int ARRAYIP_1 []
static constexpr int ARRAYPC_1 []
static constexpr int ARRAYPC_2 []
static constexpr int ARRAYLS []
static constexpr quint64 ARRAYLSMASK []
Function Documentation
TTK_MODULE_EXPORT TTKString QAlgorithm::base64Decode (const TTKString & bytes)
Base64 dncode.
Definition at line 65 of file ttkcryptographichash.cpp.
References isBase64().
Referenced by QAlgorithm::Des::decrypt(), QAlgorithm::Aes::decryptCBC(), QAlgorithm::Aes::decryptECB(), and TTKCryptographicHash::xxteaDecrypt().
TTK_MODULE_EXPORT TTKString QAlgorithm::base64Encode (const unsigned char * bytes, unsigned int len)
Base64 encode.
Definition at line 15 of file ttkcryptographichash.cpp.
Referenced by QAlgorithm::Des::encrypt(), QAlgorithm::Aes::encryptCBC(), QAlgorithm::Aes::encryptECB(), and TTKCryptographicHash::xxteaEncrypt().
TTK_MODULE_EXPORT void QAlgorithm::initRandom ()
Init random value seed.
Definition at line 9 of file random.cpp.
Referenced by MusicBarrageWidget::addBarrage(), MusicBarrageWidget::createLabel(), QAlgorithm::CubeWavePrivate::CubeWavePrivate(), MusicDesktopWallpaperThread::MusicDesktopWallpaperThread(), MusicDiscoverListRequest::MusicDiscoverListRequest(), MusicMPRISPlayerCore::MusicMPRISPlayerCore(), MusicNetworkTestThread::MusicNetworkTestThread(), MusicPlaylist::MusicPlaylist(), MusicTransitionAnimationLabel::MusicTransitionAnimationLabel(), and MusicVideoSearchTableWidget::MusicVideoSearchTableWidget().
static bool QAlgorithm::isBase64 (unsigned char c) static
Definition at line 7 of file base64.cpp.
References isalnum.
static bool QAlgorithm::isBase64 (unsigned char c) static
Definition at line 10 of file ttkcryptographichash.cpp.
References isalnum.
Referenced by base64Decode().
TTK_MODULE_EXPORT int QAlgorithm::random (int value)
Get random value.
Definition at line 16 of file random.cpp.
Referenced by MusicBarrageAnimation::animationFinished(), MusicScreenSaverBackgroundWidget::backgroundTimeout(), MusicKGDiscoverListRequest::downLoadFinished(), MusicKWDiscoverListRequest::downLoadFinished(), MusicWYDiscoverListRequest::downLoadFinished(), MusicBarrageAnimation::initialize(), QAlgorithm::CubeWave::input(), MusicItemSearchTableWidget::randSimulation(), MusicNetworkTestThread::run(), MusicPlaylist::setCurrentIndex(), MusicTransitionAnimationLabel::setPixmap(), MusicDesktopWallpaperThread::setRandom(), MusicBarrageAnimation::setSize(), MusicDesktopWallpaperThread::timeout(), and MusicMPRISPlayerCore::updateTrackID().
Variable Documentation
constexpr int QAlgorithm::ARRAYE[] static
Initial value:
= {
    31, 0,   1,  2,  3,  4, -1, -1,
    3,  4,   5,  6,  7,  8, -1, -1,
    7,  8,   9, 10, 11, 12, -1, -1,
    11, 12, 13, 14, 15, 16, -1, -1,
    15, 16, 17, 18, 19, 20, -1, -1,
    19, 20, 21, 22, 23, 24, -1, -1,
    23, 24, 25, 26, 27, 28, -1, -1,
    27, 28, 29, 30, 31, 30, -1, -1
}
Definition at line 36 of file deswrapper.cpp.
constexpr int QAlgorithm::ARRAYIP[] static
Initial value:
= {
    57, 49, 41, 33, 25, 17,  9, 1,
    59, 51, 43, 35, 27, 19, 11, 3,
    61, 53, 45, 37, 29, 21, 13, 5,
    63, 55, 47, 39, 31, 23, 15, 7,
    56, 48, 40, 32, 24, 16,  8, 0,
    58, 50, 42, 34, 26, 18, 10, 2,
    60, 52, 44, 36, 28, 20, 12, 4,
    62, 54, 46, 38, 30, 22, 14, 6
}
Definition at line 25 of file deswrapper.cpp.
constexpr int QAlgorithm::ARRAYIP_1[] static
Initial value:
= {
    39, 7, 47, 15, 55, 23, 63, 31,
    38, 6, 46, 14, 54, 22, 62, 30,
    37, 5, 45, 13, 53, 21, 61, 29,
    36, 4, 44, 12, 52, 20, 60, 28,
    35, 3, 43, 11, 51, 19, 59, 27,
    34, 2, 42, 10, 50, 18, 58, 26,
    33, 1, 41,  9, 49, 17, 57, 25,
    32, 0, 40,  8, 48, 16, 56, 24
}
Definition at line 129 of file deswrapper.cpp.
constexpr int QAlgorithm::ARRAYLS[] static
Initial value:
= {
    1, 1, 2, 2, 2, 2, 2, 2,
    1, 2, 2, 2, 2, 2, 2, 1
}
Definition at line 161 of file deswrapper.cpp.
constexpr quint64 QAlgorithm::ARRAYLSMASK[] static
Initial value:
= {
    0x0000000000000000l, 0x0000000000100001l, 0x0000000000300003l
}
Definition at line 166 of file deswrapper.cpp.
constexpr quint64 QAlgorithm::ARRAYMASK[] static
Initial value:
= {
    0x0000000000000001l, 0x0000000000000002l, 0x0000000000000004l, 0x0000000000000008l,
    0x0000000000000010l, 0x0000000000000020l, 0x0000000000000040l, 0x0000000000000080l,
    0x0000000000000100l, 0x0000000000000200l, 0x0000000000000400l, 0x0000000000000800l,
    0x0000000000001000l, 0x0000000000002000l, 0x0000000000004000l, 0x0000000000008000l,
    0x0000000000010000l, 0x0000000000020000l, 0x0000000000040000l, 0x0000000000080000l,
    0x0000000000100000l, 0x0000000000200000l, 0x0000000000400000l, 0x0000000000800000l,
    0x0000000001000000l, 0x0000000002000000l, 0x0000000004000000l, 0x0000000008000000l,
    0x0000000010000000l, 0x0000000020000000l, 0x0000000040000000l, 0x0000000080000000l,
    0x0000000100000000l, 0x0000000200000000l, 0x0000000400000000l, 0x0000000800000000l,
    0x0000001000000000l, 0x0000002000000000l, 0x0000004000000000l, 0x0000008000000000l,
    0x0000010000000000l, 0x0000020000000000l, 0x0000040000000000l, 0x0000080000000000l,
    0x0000100000000000l, 0x0000200000000000l, 0x0000400000000000l, 0x0000800000000000l,
    0x0001000000000000l, 0x0002000000000000l, 0x0004000000000000l, 0x0008000000000000l,
    0x0010000000000000l, 0x0020000000000000l, 0x0040000000000000l, 0x0080000000000000l,
    0x0100000000000000l, 0x0200000000000000l, 0x0400000000000000l, 0x0800000000000000l,
    0x1000000000000000l, 0x2000000000000000l, 0x4000000000000000l, 0x8000000000000000l
}
Definition at line 6 of file deswrapper.cpp.
constexpr int QAlgorithm::ARRAYP[] static
Initial value:
= {
    15,  6, 19, 20, 28, 11, 27, 16,
     0, 14, 22, 25,  4, 17, 30,  9,
     1,  7, 23, 13, 31, 26,  2,  8,
    18, 12, 29,  5, 21, 10,  3, 24
}
Definition at line 122 of file deswrapper.cpp.
constexpr int QAlgorithm::ARRAYPC_1[] static
Initial value:
= {
    56, 48, 40, 32, 24, 16,  8,  0,
    57, 49, 41, 33, 25, 17,  9,  1,
    58, 50, 42, 34, 26, 18, 10,  2,
    59, 51, 43, 35, 62, 54, 46, 38,
    30, 22, 14,  6, 61, 53, 45, 37,
    29, 21, 13,  5, 60, 52, 44, 36,
    28, 20, 12,  4, 27, 19, 11,  3
}
Definition at line 140 of file deswrapper.cpp.
constexpr int QAlgorithm::ARRAYPC_2[] static
Initial value:
= {
    13, 16, 10, 23,  0,  4, -1, -1,
     2, 27, 14,  5, 20,  9, -1, -1,
    22, 18, 11,  3, 25,  7, -1, -1,
    15,  6, 26, 19, 12,  1, -1, -1,
    40, 51, 30, 36, 46, 54, -1, -1,
    29, 39, 50, 44, 32, 47, -1, -1,
    43, 48, 38, 55, 33, 52, -1, -1,
    45, 41, 49, 35, 28, 31, -1, -1
}
Definition at line 150 of file deswrapper.cpp.
const char* QAlgorithm::base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" static
Definition at line 5 of file base64.cpp.
const char* QAlgorithm::base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" static
Definition at line 8 of file ttkcryptographichash.cpp.
constexpr char QAlgorithm::MATRIXNSBOX[8][64] static
Definition at line 47 of file deswrapper.cpp.