TTKMusicplayer: MusicTimerWidget Class Reference
MusicTimerWidget Class Reference
The class of the timer widget.
#include <musictimerwidget.h>
Public Slots
void changeWidgetIndex (int index)
void saveParameterSettings ()
void buttonClicked (int index)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicTimerWidget (QWidget *parent=nullptr)
~MusicTimerWidget ()
void setSongStringList (const QStringList &list)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Member Functions
void initFirstWidget ()
void initSecondWidget ()
void initThreeWidget ()
void setEnabledFirstControl (bool enable)
void setEnabledSecondControl (bool enable)
void setEnabledThreeControl (bool enable)
void initComboParameter ()
void initParemeter ()
void writeParemeter () const
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Protected Attributes
Ui::MusicTimerWidget * m_ui
QStringList m_hour
QStringList m_second
QStringList m_repeat
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Detailed Description
The class of the timer widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musictimerwidget.h.
Constructor & Destructor Documentation
MusicTimerWidget::MusicTimerWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 9 of file musictimerwidget.cpp.
References buttonClicked(), changeWidgetIndex(), initComboParameter(), initFirstWidget(), initParemeter(), initSecondWidget(), initThreeWidget(), m_ui, MusicUIObject::MQSSPushButtonStyle04, MusicUIObject::MQSSTimeToDown, MusicUIObject::MQSSTimeToPlay, MusicUIObject::MQSSTimeToStop, MusicUIObject::MQSSToolButtonStyle04, and saveParameterSettings().
MusicTimerWidget::~MusicTimerWidget ()
Definition at line 90 of file musictimerwidget.cpp.
References m_ui.
Member Function Documentation
void MusicTimerWidget::buttonClicked (int index) slot
Widget interface control enable or not.
Definition at line 254 of file musictimerwidget.cpp.
References setEnabledFirstControl(), setEnabledSecondControl(), and setEnabledThreeControl().
Referenced by MusicTimerWidget().
void MusicTimerWidget::changeWidgetIndex (int index) slot
Change to index widget.
Definition at line 176 of file musictimerwidget.cpp.
References m_ui, MusicUIObject::MQSSTimeToDown, MusicUIObject::MQSSTimeToDownClicked, MusicUIObject::MQSSTimeToPlay, MusicUIObject::MQSSTimeToPlayClicked, MusicUIObject::MQSSTimeToStop, and MusicUIObject::MQSSTimeToStopClicked.
Referenced by MusicTimerWidget().
int MusicTimerWidget::exec () virtual slot
Override exec function.
Definition at line 291 of file musictimerwidget.cpp.
References m_ui, and MusicWidgetRenderer::setBackgroundPixmap().
Referenced by MusicToolSetsWidget::itemHasClicked(), and MusicApplicationModule::musicTimerWidget().
void MusicTimerWidget::initComboParameter () protected
Init combobox parameter.
Definition at line 163 of file musictimerwidget.cpp.
References m_hour, m_repeat, m_second, MT_D, and MT_H.
Referenced by MusicTimerWidget().
void MusicTimerWidget::initFirstWidget () protected
Init time to play widget.
Definition at line 193 of file musictimerwidget.cpp.
References MusicUtils::Widget::generateComboBoxFormat(), m_hour, m_repeat, m_second, m_ui, and MusicUIObject::MQSSRadioButtonStyle01.
Referenced by MusicTimerWidget().
void MusicTimerWidget::initParemeter () protected
Init widget interface parameter.
Definition at line 95 of file musictimerwidget.cpp.
References G_SETTING_PTR, m_ui, setEnabledFirstControl(), setEnabledSecondControl(), setEnabledThreeControl(), MusicSettingManager::TimerAutoPlayHour, MusicSettingManager::TimerAutoPlayItemIndex, MusicSettingManager::TimerAutoPlayMode, MusicSettingManager::TimerAutoPlayRepeat, MusicSettingManager::TimerAutoPlaySecond, MusicSettingManager::TimerAutoShutdownHour, MusicSettingManager::TimerAutoShutdownMode, MusicSettingManager::TimerAutoShutdownRepeat, MusicSettingManager::TimerAutoShutdownSecond, MusicSettingManager::TimerAutoStopHour, MusicSettingManager::TimerAutoStopMode, MusicSettingManager::TimerAutoStopRepeat, and MusicSettingManager::TimerAutoStopSecond.
Referenced by MusicTimerWidget().
void MusicTimerWidget::initSecondWidget () protected
Init time to stop widget.
Definition at line 213 of file musictimerwidget.cpp.
References MusicUtils::Widget::generateComboBoxFormat(), m_hour, m_repeat, m_second, m_ui, and MusicUIObject::MQSSRadioButtonStyle01.
Referenced by MusicTimerWidget().
void MusicTimerWidget::initThreeWidget () protected
Init time to shutdown widget.
Definition at line 230 of file musictimerwidget.cpp.
References MusicUtils::Widget::generateComboBoxFormat(), m_hour, m_repeat, m_second, m_ui, and MusicUIObject::MQSSRadioButtonStyle01.
Referenced by MusicTimerWidget().
void MusicTimerWidget::saveParameterSettings () slot
Save the parameter setting results.
Definition at line 247 of file musictimerwidget.cpp.
References MusicApplicationModule::instance(), MusicApplicationModule::musicToolSetsParameter(), and writeParemeter().
Referenced by MusicTimerWidget().
void MusicTimerWidget::setEnabledFirstControl (bool enable) protected
Init play widget control enable or not.
Definition at line 268 of file musictimerwidget.cpp.
References m_ui.
Referenced by buttonClicked(), and initParemeter().
void MusicTimerWidget::setEnabledSecondControl (bool enable) protected
Init stop widget control enable or not..
Definition at line 277 of file musictimerwidget.cpp.
References m_ui.
Referenced by buttonClicked(), and initParemeter().
void MusicTimerWidget::setEnabledThreeControl (bool enable) protected
Init shutdown widget control enable or not..
Definition at line 284 of file musictimerwidget.cpp.
References m_ui.
Referenced by buttonClicked(), and initParemeter().
void MusicTimerWidget::setSongStringList (const QStringList & list)
Set current songs path list.
Definition at line 157 of file musictimerwidget.cpp.
References G_SETTING_PTR, m_ui, and MusicSettingManager::TimerAutoPlaySongIndex.
Referenced by MusicToolSetsWidget::itemHasClicked(), and MusicApplicationModule::musicTimerWidget().
void MusicTimerWidget::writeParemeter () const protected
Init widget interface parameter.
Definition at line 138 of file musictimerwidget.cpp.
References G_SETTING_PTR, m_ui, MusicSettingManager::TimerAutoIndex, MusicSettingManager::TimerAutoPlayHour, MusicSettingManager::TimerAutoPlayItemIndex, MusicSettingManager::TimerAutoPlayMode, MusicSettingManager::TimerAutoPlayRepeat, MusicSettingManager::TimerAutoPlaySecond, MusicSettingManager::TimerAutoPlaySongIndex, MusicSettingManager::TimerAutoShutdownHour, MusicSettingManager::TimerAutoShutdownMode, MusicSettingManager::TimerAutoShutdownRepeat, MusicSettingManager::TimerAutoShutdownSecond, MusicSettingManager::TimerAutoStopHour, MusicSettingManager::TimerAutoStopMode, MusicSettingManager::TimerAutoStopRepeat, and MusicSettingManager::TimerAutoStopSecond.
Referenced by saveParameterSettings().
Member Data Documentation
QStringList MusicTimerWidget::m_hour protected
Definition at line 105 of file musictimerwidget.h.
Referenced by initComboParameter(), initFirstWidget(), initSecondWidget(), and initThreeWidget().
QStringList MusicTimerWidget::m_repeat protected
Definition at line 107 of file musictimerwidget.h.
Referenced by initComboParameter(), initFirstWidget(), initSecondWidget(), and initThreeWidget().
QStringList MusicTimerWidget::m_second protected
Definition at line 106 of file musictimerwidget.h.
Referenced by initComboParameter(), initFirstWidget(), initSecondWidget(), and initThreeWidget().
Ui::MusicTimerWidget* MusicTimerWidget::m_ui protected
Definition at line 104 of file musictimerwidget.h.
Referenced by changeWidgetIndex(), exec(), initFirstWidget(), initParemeter(), initSecondWidget(), initThreeWidget(), MusicTimerWidget(), setEnabledFirstControl(), setEnabledSecondControl(), setEnabledThreeControl(), setSongStringList(), writeParemeter(), and ~MusicTimerWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musictimerwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musictimerwidget.cpp