TTKMusicplayer: MusicLocalSongsManagerThread Class Reference
MusicLocalSongsManagerThread Class Reference
The class of the local songs manager thread.
#include <musiclocalsongsmanagerthread.h>
Public Slots
void start ()
virtual void run () override
Signals
void setSongNamePath (const QFileInfoList &name)
Public Member Functions
MusicLocalSongsManagerThread (QObject *parent=nullptr)
~MusicLocalSongsManagerThread ()
void setFindFilePath (const QString &path)
void setFindFilePath (const QStringList &path)
void stopAndQuitThread ()
Protected Attributes
bool m_run
QStringList m_path
Detailed Description
The class of the local songs manager thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musiclocalsongsmanagerthread.h.
Constructor & Destructor Documentation
MusicLocalSongsManagerThread::MusicLocalSongsManagerThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musiclocalsongsmanagerthread.cpp.
References m_run.
MusicLocalSongsManagerThread::~MusicLocalSongsManagerThread ()
Definition at line 11 of file musiclocalsongsmanagerthread.cpp.
References stopAndQuitThread().
Member Function Documentation
void MusicLocalSongsManagerThread::run () override virtual slot
Thread run now.
The name and path search ended when sending the corresponding
Definition at line 16 of file musiclocalsongsmanagerthread.cpp.
References MusicUtils::Core::getFileListByDir(), m_path, m_run, setSongNamePath(), and MusicFormats::supportFormatsFilterString().
void MusicLocalSongsManagerThread::setFindFilePath (const QString & path)
Set find file path by given path.
Definition at line 36 of file musiclocalsongsmanagerthread.cpp.
Referenced by MusicLocalSongsManagerWidget::filterIndexChanged(), MusicLocalSongsManagerWidget::filterIndexCustChanged(), MusicLocalSongsManagerWidget::findExtraDevicePath(), and MusicLocalSongsManagerWidget::watchDirChanged().
void MusicLocalSongsManagerThread::setFindFilePath (const QStringList & path)
Set find file path by given path lists.
Definition at line 41 of file musiclocalsongsmanagerthread.cpp.
References m_path.
void MusicLocalSongsManagerThread::setSongNamePath (const QFileInfoList & name) signal
Send the searched file or path.
Referenced by run().
void MusicLocalSongsManagerThread::start () slot
Strat thread now.
Definition at line 30 of file musiclocalsongsmanagerthread.cpp.
References m_run.
Referenced by MusicLocalSongsManagerWidget::filterScanChanged(), and MusicLocalSongsManagerWidget::watchDirChanged().
void MusicLocalSongsManagerThread::stopAndQuitThread ()
Stop and quit current thread.
Definition at line 47 of file musiclocalsongsmanagerthread.cpp.
References m_run.
Referenced by MusicLocalSongsManagerWidget::filterScanChanged(), MusicLocalSongsManagerWidget::watchDirChanged(), ~MusicLocalSongsManagerThread(), and MusicLocalSongsManagerWidget::~MusicLocalSongsManagerWidget().
Member Data Documentation
QStringList MusicLocalSongsManagerThread::m_path protected
Definition at line 73 of file musiclocalsongsmanagerthread.h.
Referenced by run(), and setFindFilePath().
bool MusicLocalSongsManagerThread::m_run protected
Definition at line 72 of file musiclocalsongsmanagerthread.h.
Referenced by MusicLocalSongsManagerThread(), run(), start(), and stopAndQuitThread().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musiclocalsongsmanagerthread.h
TTKModule/TTKCore/musicToolsSetsKits/musiclocalsongsmanagerthread.cpp