TTKMusicplayer: MusicIdentifySongsRequest Class Reference
MusicIdentifySongsRequest Class Reference
The class of the song identify query request.
#include <musicidentifysongsrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadFinished (const QByteArray &bytes)
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void finished ()
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Public Member Functions
MusicIdentifySongsRequest (QObject *parent=nullptr)
bool queryIdentifyKey ()
void startToDownload (const QString &path)
const MusicSongIdentifyDataList & identifySongs () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Attributes
MusicSongIdentifyDataList m_songIdentifys
QString m_accessKey
QString m_accessSecret
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the song identify query request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicidentifysongsrequest.h.
Constructor & Destructor Documentation
MusicIdentifySongsRequest::MusicIdentifySongsRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicidentifysongsrequest.cpp.
Member Function Documentation
void MusicIdentifySongsRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 80 of file musicidentifysongsrequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicAbstractNetwork::m_reply, MusicSongIdentifyData::m_singerName, m_songIdentifys, MusicSongIdentifyData::m_songName, QJson::Parser::parse(), and TTK_LOGGER_INFO.
Referenced by queryIdentifyKey(), and startToDownload().
void MusicIdentifySongsRequest::downLoadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 124 of file musicidentifysongsrequest.cpp.
References finished(), m_accessKey, m_accessSecret, MUSIC_YEAR_STIME_FORMAT, QJson::Parser::parse(), and TTK_LOGGER_ERROR.
void MusicIdentifySongsRequest::finished () signal
Get key data from net finished.
Referenced by downLoadFinished(), queryIdentifyKey(), and startToDownload().
const MusicSongIdentifyDataList& MusicIdentifySongsRequest::identifySongs () const inline
Get identify songs.
Definition at line 58 of file musicidentifysongsrequest.h.
Referenced by MusicIdentifySongsWidget::createDetectedSuccessedWidget(), and MusicIdentifySongsWidget::detectedTimeOut().
bool MusicIdentifySongsRequest::queryIdentifyKey ()
Get query song id keys.
Definition at line 18 of file musicidentifysongsrequest.cpp.
References downLoadFinished(), MusicAbstractNetwork::downLoadRawDataChanged(), MusicSemaphoreLoop::exec(), finished(), m_accessKey, m_accessSecret, QSyncUtils::makeDataBucketUrl(), OS_ACRUA_URL, and MusicDownloadSourceRequest::startToDownload().
Referenced by MusicIdentifySongsWidget::queryIdentifyKey().
void MusicIdentifySongsRequest::startToDownload (const QString & path)
To query song by input path.
Definition at line 31 of file musicidentifysongsrequest.cpp.
References downLoadFinished(), finished(), MusicUtils::Algorithm::hmacSha1(), m_accessKey, m_accessSecret, MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicUtils::Algorithm::mdII(), QUERY_URL, MusicObject::setSslConfiguration(), and TTK_LOGGER_ERROR.
Referenced by MusicIdentifySongsWidget::detectedTimeOut().
Member Data Documentation
QString MusicIdentifySongsRequest::m_accessKey protected
Definition at line 78 of file musicidentifysongsrequest.h.
Referenced by downLoadFinished(), queryIdentifyKey(), and startToDownload().
QString MusicIdentifySongsRequest::m_accessSecret protected
Definition at line 78 of file musicidentifysongsrequest.h.
Referenced by downLoadFinished(), queryIdentifyKey(), and startToDownload().
MusicSongIdentifyDataList MusicIdentifySongsRequest::m_songIdentifys protected
Definition at line 77 of file musicidentifysongsrequest.h.
Referenced by downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/common/musicidentifysongsrequest.h
TTKModule/TTKCore/musicNetworkKits/common/musicidentifysongsrequest.cpp