TTKMusicPlayer: MusicBPDownloadBackgroundRequest Class Reference
MusicBPDownloadBackgroundRequest Class Reference
The class of the birdpaper download art background image.
#include <musicbpdownloadimagerequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractDownloadImageRequest
void downLoadDataFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBPDownloadBackgroundRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void startToRequest () overridefinal
Public Member Functions inherited from MusicAbstractDownloadImageRequest
MusicAbstractDownloadImageRequest (const QString &name, const QString &path, QObject *parent=nullptr)
virtual void deleteAll () overridefinal
void setRemainCount (int count)
int foundCount ()
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicAbstractDownloadImageRequest
int m_remainCount
int m_index
int m_counter
QString m_name
QString m_path
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the birdpaper download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicbpdownloadimagerequest.h.
Constructor & Destructor Documentation
MusicBPDownloadBackgroundRequest::MusicBPDownloadBackgroundRequest (const QString & name, const QString & path, QObject * parent = nullptr)
Object constructor provide artist name and save local path.
Definition at line 6 of file musicbpdownloadimagerequest.cpp.
Member Function Documentation
void MusicBPDownloadBackgroundRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 28 of file musicbpdownloadimagerequest.cpp.
References TTK::Background, BACKGROUND_DIR_FULL, MusicAbstractDownloadImageRequest::deleteAll(), TTKAbstractNetwork::downLoadDataChanged(), MusicAbstractDownloadImageRequest::downLoadDataFinished(), TTKAbstractNetwork::downLoadFinished(), MusicAbstractDownloadImageRequest::foundCount(), MusicAbstractDownloadImageRequest::m_counter, MusicAbstractDownloadImageRequest::m_name, MusicAbstractDownloadImageRequest::m_path, MusicAbstractDownloadImageRequest::m_remainCount, TTKAbstractNetwork::m_reply, name, QJson::Parser::parse(), qAsConst, SKN_FILE, MusicDownloadDataRequest::startToRequest(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToRequest().
void MusicBPDownloadBackgroundRequest::startToRequest () final override virtual
Start to download background data.
Implements MusicAbstractDownloadImageRequest.
Definition at line 12 of file musicbpdownloadimagerequest.cpp.
References ART_BACKGROUND_URL, TTKAbstractNetwork::deleteAll(), downLoadFinished(), TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, TTK::makeContentTypeHeader(), TTK::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), TTK::setSslConfiguration(), TTK_INFO_STREAM, and TTK_SLOT.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/background/musicbpdownloadimagerequest.h
TTKModule/TTKCore/musicNetworkKits/image/background/musicbpdownloadimagerequest.cpp