TTKMusicplayer: MusicClickedGroup Class Reference
MusicClickedGroup Class Reference
The class of the label widget click group mapper.
#include <musicclickedgroup.h>
Signals
void clicked (int index)
Public Member Functions
MusicClickedGroup (QObject *parent=nullptr)
void mapped (QWidget *widget)
Private Slots
void update ()
Private Attributes
QList< QWidget * > m_container
Detailed Description
The class of the label widget click group mapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicclickedgroup.h.
Constructor & Destructor Documentation
MusicClickedGroup::MusicClickedGroup (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicclickedgroup.cpp.
Member Function Documentation
void MusicClickedGroup::clicked (int index) signal
Index widget click emit.
Referenced by mapped(), and update().
void MusicClickedGroup::mapped (QWidget * widget)
Map the clicked widget.
Definition at line 9 of file musicclickedgroup.cpp.
References clicked(), m_container, and update().
Referenced by MusicSpectrumLayoutWidget::addItems(), MusicArtistListQueryWidget::createArtistListItem(), MusicEqualizerDialog::initialize(), MusicEMOJILabelWidget::MusicEMOJILabelWidget(), MusicWebMVRadioQueryCategoryItem::setCategory(), MusicArtistListQueryCategoryItem::setCategory(), MusicPlaylistQueryCategoryItem::setCategory(), and MusicToplistQueryCategoryItem::setCategory().
void MusicClickedGroup::update () private slot
Update the current clicked state.
Definition at line 15 of file musicclickedgroup.cpp.
References clicked(), m_container, and TTKStatic_cast.
Referenced by mapped().
Member Data Documentation
QList<QWidget*> MusicClickedGroup::m_container private
Definition at line 56 of file musicclickedgroup.h.
Referenced by mapped(), and update().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicclickedgroup.h
TTKModule/TTKWidget/musicCoreKits/musicclickedgroup.cpp