TTKMusicplayer: MusicSimilarQueryWidget Class Reference
MusicSimilarQueryWidget Class Reference
The class of similar music query widget.
#include <musicsimilarquerywidget.h>
Public Slots
void queryAllFinished ()
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicSimilarQueryWidget (QWidget *parent=nullptr)
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractItemQueryWidget ()
void initWidget ()
Protected Member Functions
void createLabels ()
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Additional Inherited Members
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of similar music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 57 of file musicsimilarquerywidget.h.
Constructor & Destructor Documentation
MusicSimilarQueryWidget::MusicSimilarQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 36 of file musicsimilarquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget.
Member Function Documentation
void MusicSimilarQueryWidget::createLabels () protected
Create init interface lables.
Definition at line 67 of file musicsimilarquerywidget.cpp.
References MusicUtils::Widget::generateVScrollAreaFormat(), MusicAbstractItemQueryWidget::initFirstWidget(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_songNameFull, MusicAbstractItemQueryWidget::m_statusLabel, MusicUIObject::MQSSCheckBoxStyle01, and MusicUIObject::MQSSPushButtonStyle03.
Referenced by setSongName().
void MusicSimilarQueryWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 62 of file musicsimilarquerywidget.cpp.
void MusicSimilarQueryWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 57 of file musicsimilarquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget, and MusicItemQueryTableWidget::resizeWindow().
void MusicSimilarQueryWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 43 of file musicsimilarquerywidget.cpp.
References createLabels(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicItemQueryTableWidget::setQueryInput(), MusicAbstractItemQueryWidget::setSongName(), MusicUtils::String::songName(), and MusicItemQueryTableWidget::startSearchQuery().
void MusicSimilarQueryWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 52 of file musicsimilarquerywidget.cpp.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsimilarquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsimilarquerywidget.cpp