TTKMusicPlayer: MusicBlurSpecturmModule Class Reference
MusicBlurSpecturmModule Class Reference
The class of the blur spectrum object.
#include <musicblurspecturmmodule.h>
Public Member Functions
MusicBlurSpecturmModule (QObject *parent=nullptr)
~MusicBlurSpecturmModule ()
void setVisible (bool v)
void show ()
void close ()
void update (bool up)
void initialize (QVBoxLayout *layout, QWidget *widget)
Private Member Functions
void removeSpectrum ()
Private Attributes
QVBoxLayout * m_topAreaLayout
QWidget * m_topAreaWidget
QWidget * m_visualWidget
Detailed Description
The class of the blur spectrum object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicblurspecturmmodule.h.
Constructor & Destructor Documentation
MusicBlurSpecturmModule::MusicBlurSpecturmModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicblurspecturmmodule.cpp.
MusicBlurSpecturmModule::~MusicBlurSpecturmModule ()
Object destructor.
Definition at line 15 of file musicblurspecturmmodule.cpp.
References removeSpectrum().
Member Function Documentation
void MusicBlurSpecturmModule::close ()
Set ripple spectrum hide.
Definition at line 57 of file musicblurspecturmmodule.cpp.
References m_topAreaLayout, m_topAreaWidget, m_visualWidget, and removeSpectrum().
Referenced by update().
void MusicBlurSpecturmModule::initialize (QVBoxLayout * layout, QWidget * widget)
Init ripple spectrum paramters.
Definition at line 85 of file musicblurspecturmmodule.cpp.
References m_topAreaLayout, and m_topAreaWidget.
Referenced by MusicBottomAreaWidget::setupUi().
void MusicBlurSpecturmModule::removeSpectrum () private
Remove ripple spectrum object.
Definition at line 91 of file musicblurspecturmmodule.cpp.
References TTK::TTKQmmp::enabledVisualPlugin(), and m_visualWidget.
Referenced by close(), and ~MusicBlurSpecturmModule().
void MusicBlurSpecturmModule::setVisible (bool v)
Set ripple spectrum show or not.
Definition at line 20 of file musicblurspecturmmodule.cpp.
References m_topAreaLayout, m_topAreaWidget, and m_visualWidget.
Referenced by MusicBottomAreaWidget::lrcWidgetShowFullScreen().
void MusicBlurSpecturmModule::show ()
Set ripple spectrum show.
Definition at line 30 of file musicblurspecturmmodule.cpp.
References CONCISE_WIDTH_MIN, TTK::TTKQmmp::enabledVisualPlugin(), m_topAreaLayout, m_topAreaWidget, m_visualWidget, and Visual::visuals().
Referenced by update().
void MusicBlurSpecturmModule::update (bool up)
Update ripple spectrum paramters.
Definition at line 70 of file musicblurspecturmmodule.cpp.
References close(), m_visualWidget, show(), Visual::start(), TTKObjectCast, and TTK::TTKQmmp::updateBlurConfig().
Referenced by MusicBottomAreaWidget::applyParameter().
Member Data Documentation
QVBoxLayout* MusicBlurSpecturmModule::m_topAreaLayout private
Definition at line 70 of file musicblurspecturmmodule.h.
Referenced by close(), initialize(), setVisible(), and show().
QWidget* MusicBlurSpecturmModule::m_topAreaWidget private
Definition at line 71 of file musicblurspecturmmodule.h.
Referenced by close(), initialize(), setVisible(), and show().
QWidget * MusicBlurSpecturmModule::m_visualWidget private
Definition at line 71 of file musicblurspecturmmodule.h.
Referenced by close(), removeSpectrum(), setVisible(), show(), and update().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicblurspecturmmodule.h
TTKModule/TTKWidget/musicWidgetKits/musicblurspecturmmodule.cpp