TTKMusicplayer: MusicWYQueryToplistRequest Class Reference
MusicWYQueryToplistRequest Class Reference
The class of wangyi query toplist download data from net.
#include <musicwyquerytoplistrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYQueryToplistRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &toplist) overridefinal
virtual void startToSearch (const QString &toplist) overridefinal
Public Member Functions inherited from MusicQueryToplistRequest
MusicQueryToplistRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSingleSearch (const QString &text)
void setQueryQuality (const QString &qual)
QString queryQuality () const
void setQueryAllRecords (bool state)
bool queryAllRecords () const
void setQuerySimplify (bool state)
bool querySimplify () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & musicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryToplistRequest
void createToplistInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 urlFileSize (const QString &url)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicWYQueryInterface
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
Detailed Description
The class of wangyi query toplist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwyquerytoplistrequest.h.
Constructor & Destructor Documentation
MusicWYQueryToplistRequest::MusicWYQueryToplistRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicwyquerytoplistrequest.cpp.
References MusicAbstractQueryRequest::m_queryServer, and QUERY_WY_INTERFACE.
Member Function Documentation
void MusicWYQueryToplistRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 41 of file musicwyquerytoplistrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicQueryToplistRequest::createToplistInfoItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicObject::MusicSongInformation::m_discNumber, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicObject::MusicSongInformation::m_lrcUrl, MusicAbstractQueryRequest::m_musicSongInfos, MusicResultsItem::m_name, MusicResultsItem::m_playCount, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_queryQuality, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicResultsItem::m_updateTime, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), MUSIC_YEAR_FORMAT, QJson::Parser::parse(), MusicWYQueryInterface::readFromMusicSongAttributeNew(), TTK_LOGGER_INFO, TTK_NETWORK_QUERY_CHECK, and WY_SONG_LRC_OLD_URL.
Referenced by startToSearch().
void MusicWYQueryToplistRequest::startToSearch (QueryType type, const QString & toplist) final override virtual
Start to Search data from name and type.
Reimplemented from MusicQueryToplistRequest.
Definition at line 9 of file musicwyquerytoplistrequest.cpp.
References MusicAbstractQueryRequest::MusicQuery.
void MusicWYQueryToplistRequest::startToSearch (const QString & toplist) final override virtual
Start to Search data from name and type.
Implements MusicQueryToplistRequest.
Definition at line 21 of file musicwyquerytoplistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicWYQueryInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), TTK_LOGGER_INFO, WY_TOPLIST_DATA_URL, and WY_TOPLIST_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyquerytoplistrequest.h
TTKModule/TTKCore/musicNetworkKits/music/wy/musicwyquerytoplistrequest.cpp