TTKMusicPlayer: MusicThunderSkinConfigManager Class Reference
MusicThunderSkinConfigManager Class Reference
The class of the thunder skin XML config manager.
#include <musicdownloadthunderskinrequest.h>
Public Member Functions
MusicThunderSkinConfigManager (QObject *parent=nullptr)
void readBuffer (MusicSkinRemoteGroupList &items)
Public Member Functions inherited from TTKXmlDocument
TTKXmlDocument (QObject *parent=nullptr)
~TTKXmlDocument ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
bool toFile (const QString &name)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readXmlTextByTagName (const QString &tagName) const
TTKXmlAttributeList readXmlAttributesByTagName (const QString &tagName) const
QStringList readXmlMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readXmlMultiTextByTagName (const QString &tagName) const
TTKXmlAttributesList readXmlMultiAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const TTKXmlAttribute &attr)
QDomElement createRoot (const QString &node, const TTKXmlAttributeList &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttribute &attr)
QDomElement writeDomMutilElement (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const TTKXmlAttribute &attr, const QString &text)
QDomElement writeDomMutilElementText (QDomElement &element, const QString &node, const TTKXmlAttributeList &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const TTKXmlAttribute &attr)
Additional Inherited Members
Protected Attributes inherited from TTKXmlDocument
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the thunder skin XML config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadthunderskinrequest.h.
Constructor & Destructor Documentation
MusicThunderSkinConfigManager::MusicThunderSkinConfigManager (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 7 of file musicdownloadthunderskinrequest.cpp.
Member Function Documentation
void MusicThunderSkinConfigManager::readBuffer (MusicSkinRemoteGroupList & items)
Read datas from config file.
Definition at line 13 of file musicdownloadthunderskinrequest.cpp.
References MusicSkinRemoteItem::isValid(), MusicSkinRemoteGroup::isValid(), TTKXmlDocument::m_document, MusicSkinRemoteGroup::m_group, MusicSkinRemoteGroup::m_id, MusicSkinRemoteItem::m_index, MusicSkinRemoteGroup::m_items, MusicSkinRemoteItem::m_name, MusicSkinRemoteItem::m_url, MusicSkinRemoteItem::m_useCount, MAX_SIZE, MUSIC_THUNDER_DIR, and TTK_DEFAULT_STR.
Referenced by MusicDownloadThunderSkinRequest::downLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadthunderskinrequest.h
TTKModule/TTKCore/musicNetworkKits/image/skin/musicdownloadthunderskinrequest.cpp