TTKMusicPlayer: MusicNewSongRecommendQueryTableWidget Class Reference
MusicNewSongRecommendQueryTableWidget Class Reference
The class of the new song recommend query item table widget.
#include <musicmainrecommendwidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) override
virtual void itemDoubleClicked (int row, int column) override
virtual void removeItems () overridefinal
virtual void createResultItem (const MusicResultInfoItem &result) override
Public Slots inherited from MusicQueryTableWidget
virtual void itemCellClicked (int row, int column) override
virtual void itemDoubleClicked (int row, int column)=0
virtual void removeItems () override
virtual void createResultItem (const MusicResultInfoItem &result)=0
void createFinishedItem ()
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicNewSongRecommendQueryTableWidget (QWidget *parent=nullptr)
~MusicNewSongRecommendQueryTableWidget ()
virtual void startToSearchByValue (const QString &value) overridefinal
virtual void downloadQueryResult (int row) overridefinal
virtual void resizeGeometry () overridefinal
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * queryInput () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedItemRows () const
TTKIntList uncheckedItemRows () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
TTKIntList selectedRows () const
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Member Functions
void addSearchMusicToPlaylist (int row, bool play)
bool downloadDataFrom (TTK::MusicSongInformation *info, bool play)
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void startToQueryByText (const QString &text)
Protected Member Functions inherited from MusicQueryTableWidget
virtual void resizeEvent (QResizeEvent *event) override
void setLoadingStatus (bool status) const
bool isValid (int row) const noexcept
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes inherited from MusicQueryTableWidget
MusicGifLabelWidget * m_loadingLabel
TTKLabelItemDelegate * m_labelDelegate
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the new song recommend query item table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 41 of file musicmainrecommendwidget.h.
Constructor & Destructor Documentation
MusicNewSongRecommendQueryTableWidget::MusicNewSongRecommendQueryTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 13 of file musicmainrecommendwidget.cpp.
References TTK::UI::LabelStyle03, and MusicQueryTableWidget::m_labelDelegate.
MusicNewSongRecommendQueryTableWidget::~MusicNewSongRecommendQueryTableWidget ()
Object destructor.
Definition at line 32 of file musicmainrecommendwidget.cpp.
References removeItems().
Member Function Documentation
void MusicNewSongRecommendQueryTableWidget::addSearchMusicToPlaylist (int row, bool play) private
Add search media to play list by index.
Definition at line 179 of file musicmainrecommendwidget.cpp.
References downloadDataFrom(), TTKAbstractTableWidget::isValid(), MusicAbstractQueryRequest::items(), and MusicQueryTableWidget::m_networkRequest.
Referenced by itemCellClicked(), and itemDoubleClicked().
void MusicNewSongRecommendQueryTableWidget::createResultItem (const MusicResultInfoItem & result) override virtual slot
Create search result items.
Definition at line 151 of file musicmainrecommendwidget.cpp.
References TTK::UI::Color02, TTK::Widget::elidedText(), TTK::generateSongName(), MusicResultInfoItem::m_artistName, MusicResultInfoItem::m_duration, MusicResultInfoItem::m_songName, and QtItemSetTextAlignment.
bool MusicNewSongRecommendQueryTableWidget::downloadDataFrom (TTK::MusicSongInformation * info, bool play) private
Download data from net and just play or not.
Definition at line 195 of file musicmainrecommendwidget.cpp.
References MusicSongsContainerWidget::addSongBufferToPlaylist(), G_NETWORK_PTR, TTK::generateSongName(), MusicSongsContainerWidget::instance(), TTK::MusicSongInformation::m_artistName, MusicResultDataItem::m_count, MusicResultDataItem::m_description, TTK::MusicSongInformation::m_duration, TTK::MusicSongProperty::m_format, MusicResultDataItem::m_id, MusicResultDataItem::m_name, MusicQueryTableWidget::m_networkRequest, MusicResultDataItem::m_nickName, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songName, TTK::MusicSongInformation::m_songProps, MusicResultDataItem::m_time, MusicResultDataItem::m_title, TTK::MusicSongProperty::m_url, MUSIC_PLAY_LATER, MUSIC_PLAY_NOW, MusicToastLabel::popup(), MusicAbstractQueryRequest::queryServer(), MusicAbstractQueryRequest::startToQueryResult(), and TTK_BN_128.
Referenced by addSearchMusicToPlaylist().
void MusicNewSongRecommendQueryTableWidget::downloadQueryResult (int row) final override virtual
Download query result data.
Implements MusicQueryTableWidget.
Definition at line 48 of file musicmainrecommendwidget.cpp.
References MusicDownloadWidget::initialize(), TTKAbstractTableWidget::isValid(), MusicQueryTableWidget::m_networkRequest, and MusicAbstractMoveWidget::show().
Referenced by itemCellClicked().
void MusicNewSongRecommendQueryTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 132 of file musicmainrecommendwidget.cpp.
References addSearchMusicToPlaylist(), downloadQueryResult(), and MusicQueryTableWidget::itemCellClicked().
void MusicNewSongRecommendQueryTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 83 of file musicmainrecommendwidget.cpp.
References TTKAbstractTableWidget::itemCellEntered(), MusicAbstractQueryRequest::items(), MusicQueryTableWidget::m_networkRequest, and TTKAbstractTableWidget::m_previousColorRow.
void MusicNewSongRecommendQueryTableWidget::itemDoubleClicked (int row, int column) override virtual slot
Table widget item cell double clicked.
Definition at line 73 of file musicmainrecommendwidget.cpp.
References addSearchMusicToPlaylist().
void MusicNewSongRecommendQueryTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 145 of file musicmainrecommendwidget.cpp.
References MusicQueryTableWidget::removeItems().
Referenced by startToSearchByValue(), and ~MusicNewSongRecommendQueryTableWidget().
void MusicNewSongRecommendQueryTableWidget::resizeGeometry () final override virtual
Resize widget bound by resize called.
Reimplemented from MusicQueryTableWidget.
Definition at line 60 of file musicmainrecommendwidget.cpp.
References TTK::Widget::elidedText(), G_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by MusicMainRecommendWidget::resizeGeometry().
void MusicNewSongRecommendQueryTableWidget::startToSearchByValue (const QString & value) final override virtual
Start to search query by value.
Implements MusicQueryTableWidget.
Definition at line 37 of file musicmainrecommendwidget.cpp.
References G_NETWORK_PTR, MusicQueryTableWidget::m_networkRequest, removeItems(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicMainRecommendWidget::createContainerTopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.cpp