TTKMusicplayer: MusicBDQueryMovieRequest Class Reference
MusicBDQueryMovieRequest Class Reference
The class to baidu mv query download data from net.
#include <musicbdquerymovierequest.h>
Public Slots
virtual void downLoadFinished () override
void pageDownLoadFinished ()
void singleDownLoadFinished ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBDQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToPage (int offset) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicQueryMovieRequest
MusicQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &movie)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual ~MusicAbstractQueryRequest ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
virtual ~MusicPagingRequest ()
virtual void deleteAll () override
int getPageSize () const
int getPageTotal () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Member Functions
void readFromMusicMVAttribute (MusicObject::MusicSongInformation *info, bool more)
void readFromMusicMVAttributeWeb (MusicObject::MusicSongInformation *info)
void readFromMusicMVAttributeIQY (MusicObject::MusicSongInformation *info, const QString &var, bool more)
void readFromMusicMVAttributeIQY (MusicObject::MusicSongAttribute *attr)
Protected Member Functions inherited from MusicAbstractQueryRequest
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryMovieRequest
void createMovieInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_pageTotal
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
QVariantMap m_headerData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicBDQueryInterface
void makeTokenQueryUrl (QNetworkRequest *request, const QString &id)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &bit)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicPayAttribute (MusicObject::MusicSongInformation *info)
Detailed Description
The class to baidu mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicbdquerymovierequest.h.
Constructor & Destructor Documentation
MusicBDQueryMovieRequest::MusicBDQueryMovieRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicbdquerymovierequest.cpp.
References MusicPagingRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_BD_INTERFACE.
Member Function Documentation
void MusicBDQueryMovieRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 79 of file musicbdquerymovierequest.cpp.
References MusicAbstractQueryRequest::clearAllItems(), MusicAbstractQueryRequest::createSearchedItem(), MusicPagingRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::findTimeStringByAttrs(), MusicUtils::String::illegalCharactersReplaced(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MusicObject::NetworkQuery, QJson::Parser::parse(), readFromMusicMVAttribute(), and TTK_LOGGER_INFO.
Referenced by startToSearch().
void MusicBDQueryMovieRequest::pageDownLoadFinished () slot
Download page data from net finished.
Definition at line 149 of file musicbdquerymovierequest.cpp.
References MusicQueryMovieRequest::createMovieInfoItem(), DEFAULT_LEVEL_HIGHER, MusicPagingRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicResultsItem::m_name, MusicPagingRequest::m_pageTotal, MusicAbstractNetwork::m_reply, MusicResultsItem::m_updateTime, QJson::Parser::parse(), and TTK_LOGGER_INFO.
Referenced by startToPage().
void MusicBDQueryMovieRequest::readFromMusicMVAttribute (MusicObject::MusicSongInformation * info, bool more) protected
Read mv tags(size) from query results.
Definition at line 301 of file musicbdquerymovierequest.cpp.
References ALG_UA_KEY, BD_MOVIE_URL, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicObject::MusicSongInformation::m_songId, MusicAbstractNetwork::m_stateCode, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicObject::NetworkQuery, QJson::Parser::parse(), readFromMusicMVAttributeIQY(), MusicObject::setSslConfiguration(), and MusicUtils::Codec::toUtf8().
Referenced by downLoadFinished(), and singleDownLoadFinished().
void MusicBDQueryMovieRequest::readFromMusicMVAttributeIQY (MusicObject::MusicSongInformation * info, const QString & var, bool more) protected
Read mv infos from iqy query results.
Definition at line 347 of file musicbdquerymovierequest.cpp.
References ALG_UA_KEY, BD_MOVIE_INFO_DATA_URL, BD_MOVIE_INFO_IQY_URL, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicAbstractQueryRequest::findTimeStringByAttrs(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_duration, MusicObject::MusicSongAttribute::m_format, MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongAttribute::m_url, MB_250, MB_500, MB_750, MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkError, MusicObject::NetworkQuery, QJson::Parser::parse(), MusicObject::setSslConfiguration(), MusicUtils::Number::size2Label(), MusicTime::timestamp(), and MusicUtils::Codec::toUtf8().
Referenced by readFromMusicMVAttribute(), and readFromMusicMVAttributeWeb().
void MusicBDQueryMovieRequest::readFromMusicMVAttributeIQY (MusicObject::MusicSongAttribute * attr) protected
Read mv info attribute from iqy query results.
Definition at line 477 of file musicbdquerymovierequest.cpp.
References ALG_UA_KEY, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicAbstractNetwork::m_manager, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QJson::Parser::parse(), MusicObject::setSslConfiguration(), and MusicUtils::Codec::toUtf8().
void MusicBDQueryMovieRequest::readFromMusicMVAttributeWeb (MusicObject::MusicSongInformation * info) protected
Read mv infos from web query results.
Definition at line 237 of file musicbdquerymovierequest.cpp.
References ALG_UA_KEY, BD_MOVIE_INFO_WEB_URL, BD_UA_URL, MusicSemaphoreLoop::exec(), MusicAbstractQueryRequest::findUrlFileSize(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_duration, MusicObject::MusicSongAttribute::m_format, MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongAttribute::m_url, MB_500, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), MusicObject::NetworkError, MusicObject::NetworkQuery, QJson::Parser::parse(), readFromMusicMVAttributeIQY(), MusicObject::setSslConfiguration(), MusicUtils::String::stringSplitToken(), and MusicUtils::Codec::toUtf8().
Referenced by singleDownLoadFinished().
void MusicBDQueryMovieRequest::singleDownLoadFinished () slot
Download single data from net finished.
found playmv url request
Definition at line 202 of file musicbdquerymovierequest.cpp.
References MusicAbstractQueryRequest::clearAllItems(), MusicAbstractQueryRequest::createSearchedItem(), MusicPagingRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::findTimeStringByAttrs(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_musicSongInfos, MusicAbstractQueryRequest::m_searchText, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicAbstractNetwork::m_stateCode, MusicSearchedItem::m_time, MusicSearchedItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MusicObject::NetworkQuery, readFromMusicMVAttribute(), readFromMusicMVAttributeWeb(), and TTK_LOGGER_INFO.
Referenced by startToSingleSearch().
void MusicBDQueryMovieRequest::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicPagingRequest.
Definition at line 38 of file musicbdquerymovierequest.cpp.
References ALG_UA_KEY, BD_ARTIST_MOVIE_URL, BD_UA_URL, MusicPagingRequest::deleteAll(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicPagingRequest::m_pageTotal, MusicAbstractNetwork::m_reply, MusicAbstractQueryRequest::m_searchText, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, pageDownLoadFinished(), MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), MusicUtils::Codec::toUtf8(), and TTK_LOGGER_INFO.
void MusicBDQueryMovieRequest::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicQueryMovieRequest.
Definition at line 13 of file musicbdquerymovierequest.cpp.
References ALG_UA_KEY, BD_SONG_SEARCH_URL, BD_UA_URL, MusicPagingRequest::deleteAll(), downLoadFinished(), MusicAbstractQueryRequest::m_currentType, MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicPagingRequest::m_pageSize, MusicAbstractNetwork::m_reply, MusicAbstractQueryRequest::m_searchText, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, MusicAbstractNetwork::replyError(), MusicObject::setSslConfiguration(), MusicUtils::Codec::toUtf8(), and TTK_LOGGER_INFO.
void MusicBDQueryMovieRequest::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 63 of file musicbdquerymovierequest.cpp.
References MusicPagingRequest::deleteAll(), MusicAbstractNetwork::m_interrupt, MusicAbstractNetwork::m_manager, MusicAbstractQueryRequest::m_searchText, MT_MS, singleDownLoadFinished(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdquerymovierequest.h
TTKModule/TTKCore/musicNetworkKits/music/bd/musicbdquerymovierequest.cpp