TTKMusicplayer: MusicDownloadSourceThread Class Reference
MusicDownloadSourceThread Class Reference
The class of source data download thread.
#include <musicdownloadsourcethread.h>
Public Slots
virtual void downLoadFinished () override
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void downLoadByteDataChanged (const QByteArray &data)
void downLoadExtDataChanged (const QByteArray &data, const QVariantMap &ext)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDownloadSourceThread (QObject *parent=nullptr)
~MusicDownloadSourceThread ()
void startToDownload (const QString &url)
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Additional Inherited Members
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of source data download thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 26 of file musicdownloadsourcethread.h.
Constructor & Destructor Documentation
MusicDownloadSourceThread::MusicDownloadSourceThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdownloadsourcethread.cpp.
MusicDownloadSourceThread::~MusicDownloadSourceThread ()
Definition at line 9 of file musicdownloadsourcethread.cpp.
References MusicNetworkAbstract::deleteAll().
Member Function Documentation
void MusicDownloadSourceThread::downLoadByteDataChanged (const QByteArray & data) signal
Send download byte data from net.
Referenced by downLoadFinished(), replyError(), and sslErrors().
void MusicDownloadSourceThread::downLoadExtDataChanged (const QByteArray & data, const QVariantMap & ext) signal
Send download ext data from net.
Referenced by downLoadFinished(), replyError(), and sslErrors().
void MusicDownloadSourceThread::downLoadFinished () override virtual slot
Download data from net finished.
redirection target url
Definition at line 30 of file musicdownloadsourcethread.cpp.
References MusicNetworkAbstract::deleteAll(), downLoadByteDataChanged(), downLoadExtDataChanged(), M_LOGGER_ERROR, MusicNetworkAbstract::m_rawData, MusicNetworkAbstract::m_reply, and startToDownload().
Referenced by startToDownload().
void MusicDownloadSourceThread::replyError (QNetworkReply::NetworkError error) override virtual slot
Download reply error.
Definition at line 68 of file musicdownloadsourcethread.cpp.
References MusicNetworkAbstract::deleteAll(), downLoadByteDataChanged(), downLoadExtDataChanged(), M_LOGGER_ERROR, and MusicNetworkAbstract::m_rawData.
void MusicDownloadSourceThread::sslErrors (QNetworkReply * reply, const QList< QSslError > & errors) override virtual slot
Download ssl reply error.
Definition at line 83 of file musicdownloadsourcethread.cpp.
References MusicNetworkAbstract::deleteAll(), downLoadByteDataChanged(), downLoadExtDataChanged(), MusicNetworkAbstract::m_rawData, and MusicNetworkAbstract::sslErrorsString().
Referenced by startToDownload().
void MusicDownloadSourceThread::startToDownload (const QString & url)
Start to download data.
Definition at line 14 of file musicdownloadsourcethread.cpp.
References downLoadFinished(), M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicObject::setSslConfiguration(), and sslErrors().
Referenced by MusicWebMusicRadioWidget::addListWidgetItem(), MusicAlbumFoundWidget::createAlbumInfoItem(), MusicArtistFoundWidget::createArtistInfoItem(), MusicWebDJRadioInfoWidget::createCategoryInfoItem(), MusicWebMVRadioInfoWidget::createCategoryInfoItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicCommentsItem::createSearchedItem(), MusicToplistFoundWidget::createToplistInfoItem(), downLoadFinished(), MusicDataTagDownloadThread::downLoadFinished(), MusicCloudManagerTableWidget::getKey(), MusicIdentifySongsThread::getKey(), MusicSoundKMicroWidget::mediaUrlChanged(), MusicUserDialog::networkLoginChanged(), MusicSongSharingWidget::setData(), MusicArtistAlbumsItemWidget::setMusicResultsItem(), MusicWebMVRadioFoundItemWidget::setMusicResultsItem(), MusicWebDJRadioFoundItemWidget::setMusicResultsItem(), MusicWebDJRadioCategoryItemWidget::setMusicResultsItem(), MusicPlaylistFoundItemWidget::setMusicResultsItem(), MusicPlaylistFoundInfoWidget::setMusicResultsItem(), MusicKWBackgroundThread::startToDownload(), MusicNetworkOperator::startToDownload(), MusicSourceUpdateThread::startToDownload(), MusicVoiceTtsThread::startToDownload(), MusicDownloadBackgroundThunderThread::startToDownload(), and MusicDownloadBackgroundBingThread::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadsourcethread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadsourcethread.cpp