TTKMusicplayer: MusicLocalSongsTableWidget Class Reference
MusicLocalSongsTableWidget Class Reference
The class of the lcal songs table widget.
#include <musiclocalsongstablewidget.h>
Public Slots
virtual void listCellClicked (int row, int column) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
Public Slots inherited from MusicSongsListAbstractTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
void musicSongMovieFoundPy ()
void musicSimilarFoundWidgetPy ()
void musicSongSharedWidgetPy ()
void musicSongKMicroWidgetPy ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Public Member Functions
MusicLocalSongsTableWidget (QWidget *parent=0)
virtual ~MusicLocalSongsTableWidget ()
void clear ()
void addItems (const QFileInfoList &path)
void setFiles (const QFileInfoList &path)
const QFileInfoList & getFiles () const
Public Member Functions inherited from MusicSongsListAbstractTableWidget
MusicSongsListAbstractTableWidget (QWidget *parent=0)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void updateSongsFileName (const MusicSongs &songs)
virtual void selectRow (int index)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=0)
virtual ~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicSongsListAbstractTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicSmoothMovingTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Attributes
QFileInfoList m_fileNames
Protected Attributes inherited from MusicSongsListAbstractTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_isFirstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Additional Inherited Members
Signals inherited from MusicSongsListAbstractTableWidget
void isCurrentIndexs (bool &state)
Protected Member Functions inherited from MusicSongsListAbstractTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Detailed Description
The class of the lcal songs table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musiclocalsongstablewidget.h.
Constructor & Destructor Documentation
MusicLocalSongsTableWidget::MusicLocalSongsTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 8 of file musiclocalsongstablewidget.cpp.
References MusicUtils::Widget::setTransparent().
MusicLocalSongsTableWidget::~MusicLocalSongsTableWidget () virtual
Definition at line 26 of file musiclocalsongstablewidget.cpp.
References clear(), and MusicSongsListAbstractTableWidget::m_musicSongs.
Member Function Documentation
void MusicLocalSongsTableWidget::addItems (const QFileInfoList & path)
Add show list items.
Definition at line 43 of file musiclocalsongstablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSongsListAbstractTableWidget::m_musicSongs, and MusicUtils::Number::size2Label().
void MusicLocalSongsTableWidget::clear ()
Clear current items.
Definition at line 37 of file musiclocalsongstablewidget.cpp.
References MusicAbstractTableWidget::clear(), and MusicSongsListAbstractTableWidget::m_musicSongs.
Referenced by ~MusicLocalSongsTableWidget().
void MusicLocalSongsTableWidget::contextMenuEvent (QContextMenuEvent * event) override virtual slot
Override the widget event.
Definition at line 82 of file musiclocalsongstablewidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicUIObject::MMenuStyle02, MusicSongsListAbstractTableWidget::musicAlbumFoundWidget(), MusicSongsListAbstractTableWidget::musicFileInformation(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicPlayClicked(), and MusicSongsListAbstractTableWidget::musicSongDownload().
QString MusicLocalSongsTableWidget::getClassName () static
Get class object name.
Definition at line 32 of file musiclocalsongstablewidget.cpp.
const QFileInfoList& MusicLocalSongsTableWidget::getFiles () const inline
Get files container.
Definition at line 58 of file musiclocalsongstablewidget.h.
void MusicLocalSongsTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 76 of file musiclocalsongstablewidget.cpp.
void MusicLocalSongsTableWidget::setFiles (const QFileInfoList & path) inline
Set files container.
Definition at line 54 of file musiclocalsongstablewidget.h.
Member Data Documentation
QFileInfoList MusicLocalSongsTableWidget::m_fileNames protected
Definition at line 71 of file musiclocalsongstablewidget.h.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musiclocalsongstablewidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musiclocalsongstablewidget.cpp