TTKMusicPlayer: MusicFMRadioSongRequest Class Reference
MusicFMRadioSongRequest Class Reference
The class of the wangyi fm radio request of song info.
#include <musicfmradiosongrequest.h>
Public Slots
virtual void downloadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
Public Slots inherited from TTKAbstractNetwork
virtual void downloadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicFMRadioSongRequest (QObject *parent=nullptr)
void startToRequest ()
const TTK::MusicSongInformation & item () const noexcept
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
Public Member Functions inherited from TTKAbstractNetwork
TTKAbstractNetwork (QObject *parent=nullptr)
~TTKAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value) noexcept
const QVariant header (const QString &key) const noexcept
Private Attributes
TTK::MusicSongInformation m_item
Additional Inherited Members
Signals inherited from TTKAbstractNetwork
void downloadDataChanged (const QString &bytes)
void downloadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from TTKAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the wangyi fm radio request of song info.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicfmradiosongrequest.h.
Constructor & Destructor Documentation
MusicFMRadioSongRequest::MusicFMRadioSongRequest (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicfmradiosongrequest.cpp.
Member Function Documentation
void MusicFMRadioSongRequest::downloadFinished () final override virtual slot
Download data from net finished.
Definition at line 27 of file musicfmradiosongrequest.cpp.
References TTK::String::charactersReplace(), TTKAbstractNetwork::deleteAll(), TTKAbstractNetwork::downloadDataChanged(), TTKAbstractNetwork::downloadFinished(), QJsonParseError::error, TTKDateTime::format(), TTKTime::formatDuration(), QJsonDocument::fromJson(), TTK::MusicSongInformation::m_albumId, TTK::MusicSongInformation::m_albumName, TTK::MusicSongInformation::m_artistId, TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_coverUrl, TTK::MusicSongInformation::m_duration, m_item, TTK::MusicSongInformation::m_lrcUrl, TTKAbstractNetwork::m_reply, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songName, TTK::MusicSongInformation::m_songProps, TTK::MusicSongInformation::m_trackNumber, TTK::MusicSongInformation::m_year, ReqWYInterface::makeSongArtist(), TTK::Algorithm::mdII(), QJsonParseError::NoError, ReqWYInterface::parseFromSongProperty(), qAsConst, TTK::toString(), QJsonDocument::toVariant(), TTK_BN_128, TTK_INFO_STREAM, TTK_NETWORK_QUERY_CHECK, TTK_YEAR_FORMAT, and WY_SONG_LRC_OLD_URL.
Referenced by startToRequest().
const TTK::MusicSongInformation& MusicFMRadioSongRequest::item () const inline noexcept
Get media song information.
Definition at line 44 of file musicfmradiosongrequest.h.
Referenced by MusicWebFMRadioPlayWidget::lrcDownloadStateChanged(), MusicWebFMRadioPlayWidget::picDownloadStateChanged(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), and MusicWebFMRadioPlayWidget::radioResourceDownload().
void MusicFMRadioSongRequest::startToRequest ()
Start to download radio data.
Definition at line 12 of file musicfmradiosongrequest.cpp.
References TTKAbstractNetwork::deleteAll(), downloadFinished(), FM_DETAIL_URL, m_item, TTKAbstractNetwork::m_manager, TTKAbstractNetwork::m_reply, ReqWYInterface::makeTokenRequest(), TTK::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and TTK_SLOT.
Referenced by MusicWebFMRadioPlayWidget::radioNext(), MusicWebFMRadioPlayWidget::radioPrevious(), and MusicWebFMRadioPlayWidget::show().
Member Data Documentation
TTK::MusicSongInformation MusicFMRadioSongRequest::m_item private
Definition at line 53 of file musicfmradiosongrequest.h.
Referenced by downloadFinished(), and startToRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicfmradiosongrequest.h
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicfmradiosongrequest.cpp