TTKMusicPlayer: MusicFunctionToolBoxTopWidget Class Reference
MusicFunctionToolBoxTopWidget Class Reference
The class of the function tool box top widget.
#include <musicfunctiontoolboxwidget.h>
Signals
void itemIndexChanged (int index)
void swapDragItemIndex (int start, int end)
Public Member Functions
MusicFunctionToolBoxTopWidget (int index, const QString &text, QWidget *parent=nullptr)
~MusicFunctionToolBoxTopWidget ()
void setIndex (int index)
int index () const
bool isActive ()
void setExpand (bool expand)
bool isExpand () const
void setTitle (const QString &text)
QString title (bool suffix=false)
Protected Member Functions
virtual bool isItemEnabled () const
virtual void dragEnterEvent (QDragEnterEvent *event) overridefinal
virtual void dragMoveEvent (QDragMoveEvent *event) overridefinal
virtual void dragLeaveEvent (QDragLeaveEvent *event) overridefinal
virtual void dropEvent (QDropEvent *event) overridefinal
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void paintEvent (QPaintEvent *event) override
Protected Attributes
int m_index
QString m_suffixString
QLabel * m_labelIcon
QLabel * m_labelText
bool m_isDrawTopState
bool m_isDrawMoveState
bool m_isBlockMoveExpand
bool m_isActive
QPoint m_pressAt
Detailed Description
The class of the function tool box top widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicfunctiontoolboxwidget.h.
Constructor & Destructor Documentation
MusicFunctionToolBoxTopWidget::MusicFunctionToolBoxTopWidget (int index, const QString & text, QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 12 of file musicfunctiontoolboxwidget.cpp.
References TTK::Bold, TTK::UI::ColorStyle02, m_labelIcon, m_labelText, and TTK::Widget::setLabelFontStyle().
MusicFunctionToolBoxTopWidget::~MusicFunctionToolBoxTopWidget ()
Object destructor.
Definition at line 42 of file musicfunctiontoolboxwidget.cpp.
References m_labelIcon, and m_labelText.
Member Function Documentation
void MusicFunctionToolBoxTopWidget::dragEnterEvent (QDragEnterEvent * event) final override protected virtual
Override the widget event.
Definition at line 89 of file musicfunctiontoolboxwidget.cpp.
References DRAG_FORMAT.
void MusicFunctionToolBoxTopWidget::dragLeaveEvent (QDragLeaveEvent * event) final override protected virtual
Definition at line 112 of file musicfunctiontoolboxwidget.cpp.
References m_isDrawMoveState, and m_isDrawTopState.
void MusicFunctionToolBoxTopWidget::dragMoveEvent (QDragMoveEvent * event) final override protected virtual
Definition at line 102 of file musicfunctiontoolboxwidget.cpp.
References DRAG_FORMAT, isItemEnabled(), m_isDrawMoveState, and m_isDrawTopState.
void MusicFunctionToolBoxTopWidget::dropEvent (QDropEvent * event) final override protected virtual
Definition at line 120 of file musicfunctiontoolboxwidget.cpp.
References DRAG_FORMAT, isItemEnabled(), m_index, m_isDrawMoveState, and swapDragItemIndex().
int MusicFunctionToolBoxTopWidget::index () const inline
Get index.
Definition at line 51 of file musicfunctiontoolboxwidget.h.
Referenced by MusicSongsSummariziedWidget::setItemTitle(), and title().
bool MusicFunctionToolBoxTopWidget::isActive ()
Get active.
Definition at line 48 of file musicfunctiontoolboxwidget.cpp.
References m_isActive.
Referenced by MusicFunctionToolBoxWidgetItem::isActive().
bool MusicFunctionToolBoxTopWidget::isExpand () const
Get expand.
Definition at line 60 of file musicfunctiontoolboxwidget.cpp.
References m_labelIcon, and QtLablePixmap.
Referenced by mouseMoveEvent().
bool MusicFunctionToolBoxTopWidget::isItemEnabled () const protected virtual
Check the item is enable or not.
Reimplemented in MusicSongsToolBoxTopWidget.
Definition at line 84 of file musicfunctiontoolboxwidget.cpp.
Referenced by dragMoveEvent(), dropEvent(), and mouseMoveEvent().
void MusicFunctionToolBoxTopWidget::itemIndexChanged (int index) signal
Current top widget is pressed.
Referenced by mouseMoveEvent(), and mousePressEvent().
void MusicFunctionToolBoxTopWidget::mouseMoveEvent (QMouseEvent * event) final override protected virtual
Definition at line 141 of file musicfunctiontoolboxwidget.cpp.
References DRAG_FORMAT, TTKDesktopWrapper::grabWidget(), isExpand(), isItemEnabled(), itemIndexChanged(), m_index, m_isBlockMoveExpand, m_pressAt, and title().
void MusicFunctionToolBoxTopWidget::mousePressEvent (QMouseEvent * event) final override protected virtual
Definition at line 131 of file musicfunctiontoolboxwidget.cpp.
References itemIndexChanged(), m_index, and m_pressAt.
void MusicFunctionToolBoxTopWidget::paintEvent (QPaintEvent * event) override protected virtual
Reimplemented in MusicSongsToolBoxMaskWidget, and MusicSongsToolBoxTopWidget.
Definition at line 164 of file musicfunctiontoolboxwidget.cpp.
References m_isDrawMoveState, and m_isDrawTopState.
Referenced by MusicSongsToolBoxTopWidget::paintEvent().
void MusicFunctionToolBoxTopWidget::setExpand (bool expand)
Set expand.
Definition at line 55 of file musicfunctiontoolboxwidget.cpp.
References m_labelIcon.
Referenced by MusicFunctionToolBoxWidgetItem::setExpand(), and MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicFunctionToolBoxTopWidget::setIndex (int index) inline
Set index.
Definition at line 47 of file musicfunctiontoolboxwidget.h.
Referenced by MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicFunctionToolBoxTopWidget::setTitle (const QString & text)
Set top label title.
Definition at line 66 of file musicfunctiontoolboxwidget.cpp.
References TTK::Widget::elidedText(), m_labelText, and RENAME_WIDTH.
Referenced by MusicSongsToolBoxTopWidget::changItemName(), MusicSongsSummariziedWidget::setItemTitle(), MusicFunctionToolBoxWidgetItem::setTitle(), and MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicFunctionToolBoxTopWidget::swapDragItemIndex (int start, int end) signal
Swap the item index by drag adn drop.
Referenced by dropEvent().
QString MusicFunctionToolBoxTopWidget::title (bool suffix = false)
Get top label title.
Definition at line 72 of file musicfunctiontoolboxwidget.cpp.
References index(), m_labelText, and m_suffixString.
Referenced by MusicSongsToolBoxTopWidget::changRowItemNameChanged(), and mouseMoveEvent().
Member Data Documentation
int MusicFunctionToolBoxTopWidget::m_index protected
Definition at line 102 of file musicfunctiontoolboxwidget.h.
Referenced by MusicSongsToolBoxTopWidget::addNewDirChanged(), MusicSongsToolBoxTopWidget::addNewFilesChanged(), MusicSongsToolBoxTopWidget::addToPlayedList(), MusicSongsToolBoxTopWidget::addToPlayLater(), MusicSongsToolBoxTopWidget::changItemName(), MusicSongsToolBoxTopWidget::deleteRowItemAllChanged(), MusicSongsToolBoxTopWidget::deleteRowItemChanged(), dropEvent(), MusicSongsToolBoxTopWidget::exportSongsItemList(), MusicSongsToolBoxTopWidget::isItemEnabled(), mouseMoveEvent(), mousePressEvent(), MusicSongsToolBoxTopWidget::paintEvent(), MusicSongsToolBoxTopWidget::showMenu(), and MusicSongsToolBoxTopWidget::songListSortBy().
bool MusicFunctionToolBoxTopWidget::m_isActive protected
Definition at line 107 of file musicfunctiontoolboxwidget.h.
Referenced by isActive(), and MusicSongsToolBoxTopWidget::paintEvent().
bool MusicFunctionToolBoxTopWidget::m_isBlockMoveExpand protected
Definition at line 107 of file musicfunctiontoolboxwidget.h.
Referenced by mouseMoveEvent().
bool MusicFunctionToolBoxTopWidget::m_isDrawMoveState protected
Definition at line 106 of file musicfunctiontoolboxwidget.h.
Referenced by dragLeaveEvent(), dragMoveEvent(), dropEvent(), and paintEvent().
bool MusicFunctionToolBoxTopWidget::m_isDrawTopState protected
Definition at line 106 of file musicfunctiontoolboxwidget.h.
Referenced by dragLeaveEvent(), dragMoveEvent(), and paintEvent().
QLabel* MusicFunctionToolBoxTopWidget::m_labelIcon protected
Definition at line 104 of file musicfunctiontoolboxwidget.h.
Referenced by MusicSongsToolBoxTopWidget::changRowItemNameChanged(), isExpand(), MusicFunctionToolBoxTopWidget(), setExpand(), and ~MusicFunctionToolBoxTopWidget().
QLabel * MusicFunctionToolBoxTopWidget::m_labelText protected
Definition at line 104 of file musicfunctiontoolboxwidget.h.
Referenced by MusicFunctionToolBoxTopWidget(), setTitle(), title(), and ~MusicFunctionToolBoxTopWidget().
QPoint MusicFunctionToolBoxTopWidget::m_pressAt protected
Definition at line 108 of file musicfunctiontoolboxwidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QString MusicFunctionToolBoxTopWidget::m_suffixString protected
Definition at line 103 of file musicfunctiontoolboxwidget.h.
Referenced by MusicSongsToolBoxTopWidget::changItemName(), and title().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicfunctiontoolboxwidget.h
TTKModule/TTKWidget/musicCoreKits/musicfunctiontoolboxwidget.cpp