TTKMusicplayer: MusicSongsToolBoxTopWidget Class Reference
MusicSongsToolBoxTopWidget Class Reference
The class of the tool box top widget.
#include <musicsongstoolboxwidget.h>
Public Slots
void deleteRowItem ()
void deleteRowItemAll ()
void changRowItemName ()
void setChangItemName (const QString &name)
void addNewFiles ()
void addNewDir ()
void exportSongsItemList ()
void showMenu ()
void musicListSongSortBy (QAction *action)
void showShareListDialog ()
void showEnhanceLosslessDialog ()
Signals
void addNewRowItem ()
void mousePressAt (int index)
void deleteRowItem (int index)
void deleteRowItemAll (int index)
void changRowItemName (int index, const QString &name)
void addNewFiles (int index)
void addNewDir (int index)
void musicListSongSortBy (int index)
void swapDragItemIndex (int before, int after)
Public Member Functions
MusicSongsToolBoxTopWidget (int index, const QString &text, QWidget *parent=0)
~MusicSongsToolBoxTopWidget ()
void setItemIndex (int index)
int getItemIndex () const
void setItemExpand (bool expand)
bool isItemExpand () const
void setTitle (const QString &text)
QString getTitle (bool suffix=false)
void setMusicSort (MusicSort *sort)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
bool isItemEnable () const
virtual void dragLeaveEvent (QDragLeaveEvent *event) override
virtual void dragMoveEvent (QDragMoveEvent *event) override
virtual void dragEnterEvent (QDragEnterEvent *event) override
virtual void dropEvent (QDropEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Attributes
int m_index
QString m_suffixString
QLabel * m_labelIcon
QLabel * m_labelText
MusicSongsToolItemRenamedWidget * m_renameLine
bool m_isDrawTopState
bool m_isDrawMoveState
bool m_isBlockMoveExpand
QPoint m_pressPosAt
MusicSort * m_musicSort
Detailed Description
The class of the tool box top widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicsongstoolboxwidget.h.
Constructor & Destructor Documentation
MusicSongsToolBoxTopWidget::MusicSongsToolBoxTopWidget (int index, const QString & text, QWidget * parent = 0) explicit
Object contsructor.
Definition at line 26 of file musicsongstoolboxwidget.cpp.
References MusicObject::FT_Bold, m_index, m_isBlockMoveExpand, m_isDrawMoveState, m_isDrawTopState, m_labelIcon, m_labelText, m_musicSort, m_renameLine, MusicUIObject::MColorStyle10, MusicUIObject::MKGTinyBtnEnhanceLossless, MusicUIObject::MKGTinyBtnListMenu, MusicUIObject::MKGTinyBtnShare, MusicUtils::Widget::setLabelFontStyle(), showEnhanceLosslessDialog(), showMenu(), and showShareListDialog().
MusicSongsToolBoxTopWidget::~MusicSongsToolBoxTopWidget ()
Definition at line 83 of file musicsongstoolboxwidget.cpp.
References m_labelIcon, m_labelText, and m_renameLine.
Member Function Documentation
void MusicSongsToolBoxTopWidget::addNewDir (int index) signal
Add new music dir to list.
void MusicSongsToolBoxTopWidget::addNewDir () slot
Add new music dir to list.
Definition at line 158 of file musicsongstoolboxwidget.cpp.
References m_index.
Referenced by showMenu().
void MusicSongsToolBoxTopWidget::addNewFiles (int index) signal
Add new music file or files to list.
void MusicSongsToolBoxTopWidget::addNewFiles () slot
Add new music file or files to list.
Definition at line 153 of file musicsongstoolboxwidget.cpp.
References m_index.
Referenced by showMenu().
void MusicSongsToolBoxTopWidget::addNewRowItem () signal
Add new play list item.
Referenced by showMenu().
void MusicSongsToolBoxTopWidget::changRowItemName (int index, const QString & name) signal
Open rename selected play list item widget.
void MusicSongsToolBoxTopWidget::changRowItemName () slot
Open rename selected play list item widget.
Definition at line 132 of file musicsongstoolboxwidget.cpp.
References getTitle(), m_labelIcon, m_renameLine, and setChangItemName().
Referenced by setChangItemName(), and showMenu().
void MusicSongsToolBoxTopWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Definition at line 351 of file musicsongstoolboxwidget.cpp.
References showMenu().
void MusicSongsToolBoxTopWidget::deleteRowItem (int index) signal
Delete selected play list item.
void MusicSongsToolBoxTopWidget::deleteRowItem () slot
Delete selected play list item.
Definition at line 122 of file musicsongstoolboxwidget.cpp.
References m_index.
Referenced by showMenu().
void MusicSongsToolBoxTopWidget::deleteRowItemAll (int index) signal
Delete all items in play list item.
void MusicSongsToolBoxTopWidget::deleteRowItemAll () slot
Delete all items in play list item.
Definition at line 127 of file musicsongstoolboxwidget.cpp.
References m_index.
Referenced by showMenu().
void MusicSongsToolBoxTopWidget::dragEnterEvent (QDragEnterEvent * event) override protected virtual
Definition at line 268 of file musicsongstoolboxwidget.cpp.
References DRAG_FORMAT.
void MusicSongsToolBoxTopWidget::dragLeaveEvent (QDragLeaveEvent * event) override protected virtual
Override the widget event.
Definition at line 250 of file musicsongstoolboxwidget.cpp.
References m_isDrawMoveState, and m_isDrawTopState.
void MusicSongsToolBoxTopWidget::dragMoveEvent (QDragMoveEvent * event) override protected virtual
Definition at line 258 of file musicsongstoolboxwidget.cpp.
References DRAG_FORMAT, isItemEnable(), m_isDrawMoveState, and m_isDrawTopState.
void MusicSongsToolBoxTopWidget::dropEvent (QDropEvent * event) override protected virtual
Definition at line 281 of file musicsongstoolboxwidget.cpp.
References DRAG_FORMAT, isItemEnable(), m_index, m_isDrawMoveState, and swapDragItemIndex().
void MusicSongsToolBoxTopWidget::exportSongsItemList () slot
Export music songs by item list.
Definition at line 163 of file musicsongstoolboxwidget.cpp.
References MusicApplication::instance(), m_index, and MusicApplication::musicExportSongsItemList().
Referenced by showMenu().
QString MusicSongsToolBoxTopWidget::getClassName () static
Get class object name.
Definition at line 90 of file musicsongstoolboxwidget.cpp.
int MusicSongsToolBoxTopWidget::getItemIndex () const inline
Get Item index.
Definition at line 55 of file musicsongstoolboxwidget.h.
Referenced by MusicSongsSummariziedWidget::setItemTitle().
QString MusicSongsToolBoxTopWidget::getTitle (bool suffix = false)
Get top label title.
Definition at line 110 of file musicsongstoolboxwidget.cpp.
References m_labelText, and m_suffixString.
Referenced by changRowItemName(), MusicSongsToolBoxWidgetItem::getTitle(), and mouseMoveEvent().
bool MusicSongsToolBoxTopWidget::isItemEnable () const protected
Check the item is enable or not.
Definition at line 244 of file musicsongstoolboxwidget.cpp.
References m_index, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, MUSIC_NORMAL_LIST, and MUSIC_RECENT_LIST.
Referenced by dragMoveEvent(), dropEvent(), mouseMoveEvent(), and showMenu().
bool MusicSongsToolBoxTopWidget::isItemExpand () const
Get Item expand.
Definition at line 100 of file musicsongstoolboxwidget.cpp.
References m_labelIcon.
Referenced by mouseMoveEvent().
void MusicSongsToolBoxTopWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 302 of file musicsongstoolboxwidget.cpp.
References DRAG_FORMAT, getTitle(), isItemEnable(), isItemExpand(), m_index, m_isBlockMoveExpand, m_pressPosAt, and mousePressAt().
void MusicSongsToolBoxTopWidget::mousePressAt (int index) signal
Current top widget is pressed.
Referenced by mouseMoveEvent(), and mousePressEvent().
void MusicSongsToolBoxTopWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 292 of file musicsongstoolboxwidget.cpp.
References m_index, m_pressPosAt, and mousePressAt().
void MusicSongsToolBoxTopWidget::musicListSongSortBy (int index) signal
Music list songs sort by type.
Referenced by musicListSongSortBy(), and showMenu().
void MusicSongsToolBoxTopWidget::musicListSongSortBy (QAction * action) slot
Music list songs sort by type.
Definition at line 214 of file musicsongstoolboxwidget.cpp.
References MusicSort::m_index, m_index, m_musicSort, MusicSort::m_sortType, and musicListSongSortBy().
void MusicSongsToolBoxTopWidget::paintEvent (QPaintEvent * event) override protected virtual
Reimplemented in MusicSongsToolBoxMaskWidget.
Definition at line 329 of file musicsongstoolboxwidget.cpp.
References m_isDrawMoveState, and m_isDrawTopState.
void MusicSongsToolBoxTopWidget::setChangItemName (const QString & name) slot
Rename item artist label is finised.
Definition at line 143 of file musicsongstoolboxwidget.cpp.
References changRowItemName(), m_index, m_labelText, m_renameLine, and m_suffixString.
Referenced by changRowItemName().
void MusicSongsToolBoxTopWidget::setItemExpand (bool expand)
Set Item expand.
Definition at line 95 of file musicsongstoolboxwidget.cpp.
References m_labelIcon.
Referenced by MusicSongsToolBoxWidgetItem::setItemExpand(), and MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicSongsToolBoxTopWidget::setItemIndex (int index) inline
Set Item index.
Definition at line 51 of file musicsongstoolboxwidget.h.
Referenced by MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicSongsToolBoxTopWidget::setMusicSort (MusicSort * sort) inline
Set music sort.
Definition at line 78 of file musicsongstoolboxwidget.h.
Referenced by MusicSongsToolBoxWidgetItem::setMusicSort(), and MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicSongsToolBoxTopWidget::setTitle (const QString & text)
Set top label title.
Definition at line 105 of file musicsongstoolboxwidget.cpp.
References m_labelText.
Referenced by MusicSongsSummariziedWidget::setItemTitle(), MusicSongsToolBoxWidgetItem::setTitle(), and MusicSongsSummariziedWidget::sliderValueChanaged().
void MusicSongsToolBoxTopWidget::showEnhanceLosslessDialog () slot
Show enhance lossless dialog.
Definition at line 239 of file musicsongstoolboxwidget.cpp.
References MusicSongListEnhanceLosslessWidget::exec().
Referenced by MusicSongsToolBoxTopWidget().
void MusicSongsToolBoxTopWidget::showMenu () slot
Show menu items.
Definition at line 168 of file musicsongstoolboxwidget.cpp.
References addNewDir(), addNewFiles(), addNewRowItem(), changRowItemName(), deleteRowItem(), deleteRowItemAll(), exportSongsItemList(), isItemEnable(), MusicSort::m_index, m_index, m_musicSort, MusicSort::m_sortType, MusicUIObject::MMenuStyle02, MUSIC_LOVEST_LIST, MUSIC_NETWORK_LIST, MUSIC_RECENT_LIST, and musicListSongSortBy().
Referenced by contextMenuEvent(), and MusicSongsToolBoxTopWidget().
void MusicSongsToolBoxTopWidget::showShareListDialog () slot
Show share list dialog.
Definition at line 234 of file musicsongstoolboxwidget.cpp.
References MusicSongListSharingWidget::exec().
Referenced by MusicSongsToolBoxTopWidget().
void MusicSongsToolBoxTopWidget::swapDragItemIndex (int before, int after) signal
Swap the item index by drag adn drop.
Referenced by dropEvent().
Member Data Documentation
int MusicSongsToolBoxTopWidget::m_index protected
Definition at line 181 of file musicsongstoolboxwidget.h.
Referenced by addNewDir(), addNewFiles(), deleteRowItem(), deleteRowItemAll(), dropEvent(), exportSongsItemList(), isItemEnable(), mouseMoveEvent(), mousePressEvent(), musicListSongSortBy(), MusicSongsToolBoxTopWidget(), setChangItemName(), and showMenu().
bool MusicSongsToolBoxTopWidget::m_isBlockMoveExpand protected
Definition at line 187 of file musicsongstoolboxwidget.h.
Referenced by mouseMoveEvent(), MusicSongsToolBoxMaskWidget::MusicSongsToolBoxMaskWidget(), and MusicSongsToolBoxTopWidget().
bool MusicSongsToolBoxTopWidget::m_isDrawMoveState protected
Definition at line 186 of file musicsongstoolboxwidget.h.
Referenced by dragLeaveEvent(), dragMoveEvent(), dropEvent(), MusicSongsToolBoxTopWidget(), and paintEvent().
bool MusicSongsToolBoxTopWidget::m_isDrawTopState protected
Definition at line 186 of file musicsongstoolboxwidget.h.
Referenced by dragLeaveEvent(), dragMoveEvent(), MusicSongsToolBoxTopWidget(), and paintEvent().
QLabel* MusicSongsToolBoxTopWidget::m_labelIcon protected
Definition at line 183 of file musicsongstoolboxwidget.h.
Referenced by changRowItemName(), isItemExpand(), MusicSongsToolBoxTopWidget(), setItemExpand(), and ~MusicSongsToolBoxTopWidget().
QLabel * MusicSongsToolBoxTopWidget::m_labelText protected
Definition at line 183 of file musicsongstoolboxwidget.h.
Referenced by getTitle(), MusicSongsToolBoxTopWidget(), setChangItemName(), setTitle(), and ~MusicSongsToolBoxTopWidget().
MusicSort* MusicSongsToolBoxTopWidget::m_musicSort protected
Definition at line 190 of file musicsongstoolboxwidget.h.
Referenced by musicListSongSortBy(), MusicSongsToolBoxTopWidget(), and showMenu().
QPoint MusicSongsToolBoxTopWidget::m_pressPosAt protected
Definition at line 188 of file musicsongstoolboxwidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
MusicSongsToolItemRenamedWidget* MusicSongsToolBoxTopWidget::m_renameLine protected
Definition at line 184 of file musicsongstoolboxwidget.h.
Referenced by changRowItemName(), MusicSongsToolBoxTopWidget(), setChangItemName(), and ~MusicSongsToolBoxTopWidget().
QString MusicSongsToolBoxTopWidget::m_suffixString protected
Definition at line 182 of file musicsongstoolboxwidget.h.
Referenced by getTitle(), and setChangItemName().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicsongstoolboxwidget.h
TTKModule/TTKWidget/musicToolsKits/musicsongstoolboxwidget.cpp