TTKMusicplayer: MusicRadioSongsThread Class Reference
MusicRadioSongsThread Class Reference
The class of music radio thread of song info.
#include <musicradiosongsthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicRadioSongsThread (QObject *parent=nullptr, QNetworkCookieJar *cookie=nullptr)
QJson import.
virtual ~MusicRadioSongsThread ()
virtual void startToDownload (const QString &id) override
const MusicObject::MusicSongInformation & getMusicSongInfo () const
Public Member Functions inherited from MusicRadioThreadAbstract
MusicRadioThreadAbstract (QObject *parent=nullptr, QNetworkCookieJar *cookie=nullptr)
virtual ~MusicRadioThreadAbstract ()
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Protected Attributes
MusicObject::MusicSongInformation m_songInfo
Protected Attributes inherited from MusicRadioThreadAbstract
QNetworkCookieJar * m_cookJar
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Detailed Description
The class of music radio thread of song info.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicradiosongsthread.h.
Constructor & Destructor Documentation
MusicRadioSongsThread::MusicRadioSongsThread (QObject * parent = nullptr, QNetworkCookieJar * cookie = nullptr) explicit
QJson import.
Object contsructor.
Definition at line 10 of file musicradiosongsthread.cpp.
MusicRadioSongsThread::~MusicRadioSongsThread () virtual
Definition at line 16 of file musicradiosongsthread.cpp.
References MusicNetworkAbstract::deleteAll().
Member Function Documentation
void MusicRadioSongsThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 43 of file musicradiosongsthread.cpp.
References MusicNetworkAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicUtils::String::illegalCharactersReplaced(), MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongInformation::m_lrcUrl, MusicNetworkAbstract::m_reply, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, m_songInfo, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), RADIO_LRC_URL, and MusicUtils::Number::size2Label().
Referenced by startToDownload().
const MusicObject::MusicSongInformation& MusicRadioSongsThread::getMusicSongInfo () const inline
Get music song information.
Definition at line 46 of file musicradiosongsthread.h.
Referenced by MusicWebMusicRadioPlayWidget::lrcDownloadStateChanged(), MusicWebMusicRadioPlayWidget::picDownloadStateChanged(), MusicWebMusicRadioPlayWidget::radioResourceDownload(), and MusicWebMusicRadioPlayWidget::startToPlay().
void MusicRadioSongsThread::startToDownload (const QString & id) override virtual
Start to download data.
Implements MusicRadioThreadAbstract.
Definition at line 21 of file musicradiosongsthread.cpp.
References downLoadFinished(), MusicRadioThreadAbstract::m_cookJar, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, m_songInfo, MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, RADIO_SONG_URL, MusicNetworkAbstract::replyError(), MusicObject::setSslConfiguration(), and MusicNetworkAbstract::sslErrors().
Referenced by MusicWebMusicRadioPlayWidget::getPlayListFinished(), MusicWebMusicRadioPlayWidget::radioNext(), and MusicWebMusicRadioPlayWidget::radioPrevious().
Member Data Documentation
MusicObject::MusicSongInformation MusicRadioSongsThread::m_songInfo protected
Definition at line 55 of file musicradiosongsthread.h.
Referenced by downLoadFinished(), and startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicradiosongsthread.h
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicradiosongsthread.cpp