TTKMusicplayer: MusicArtistAlbumsFoundWidget Class Reference
MusicArtistAlbumsFoundWidget Class Reference
The class of the artist albums found widget.
#include <musicartistfoundwidget.h>
Public Slots
void createArtistAlbumsItem (const MusicResultsItem &item)
void currentItemClicked (const QString &id)
Public Slots inherited from MusicFoundAbstractWidget
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistAlbumsFoundWidget (QWidget *parent=nullptr)
virtual ~MusicArtistAlbumsFoundWidget ()
virtual void setSongName (const QString &name) override
virtual void setSongNameById (const QString &id) override
virtual void resizeWindow () override
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=nullptr)
~MusicFoundAbstractWidget ()
void initWidget ()
Protected Attributes
QGridLayout * m_gridLayout
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicQueryFoundTableWidget * m_foundTableWidget
MusicDownLoadQueryThreadAbstract * m_downloadThread
QList< QLabel * > m_resizeWidgets
MusicSongSharingWidget::Type m_shareType
Additional Inherited Members
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the artist albums found widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 168 of file musicartistfoundwidget.h.
Constructor & Destructor Documentation
MusicArtistAlbumsFoundWidget::MusicArtistAlbumsFoundWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 255 of file musicartistfoundwidget.cpp.
References MusicSongSharingWidget::Artist, createArtistAlbumsItem(), MusicFoundAbstractWidget::m_container, M_DOWNLOAD_QUERY_PTR, MusicFoundAbstractWidget::m_downloadThread, m_gridLayout, MusicFoundAbstractWidget::m_mainWindow, MusicFoundAbstractWidget::m_shareType, and MusicFoundAbstractWidget::m_statusLabel.
MusicArtistAlbumsFoundWidget::~MusicArtistAlbumsFoundWidget () virtual
Definition at line 271 of file musicartistfoundwidget.cpp.
References m_gridLayout.
Member Function Documentation
void MusicArtistAlbumsFoundWidget::createArtistAlbumsItem (const MusicResultsItem & item) slot
Create the current albums item.
Definition at line 305 of file musicartistfoundwidget.cpp.
References currentItemClicked(), LINE_SPACING_SIZE, m_gridLayout, MusicFoundAbstractWidget::m_resizeWidgets, and MusicArtistAlbumsItemWidget::setMusicResultsItem().
Referenced by MusicArtistAlbumsFoundWidget().
void MusicArtistAlbumsFoundWidget::currentItemClicked (const QString & id) slot
Current item clicked.
Definition at line 316 of file musicartistfoundwidget.cpp.
References MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicAlbumSearch().
Referenced by createArtistAlbumsItem().
void MusicArtistAlbumsFoundWidget::resizeWindow () override virtual
Resize window bound by widget resize called.
Implements MusicFoundAbstractWidget.
Definition at line 288 of file musicartistfoundwidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and MusicFoundAbstractWidget::m_resizeWidgets.
Referenced by MusicArtistFoundWidget::resizeWindow().
void MusicArtistAlbumsFoundWidget::setSongName (const QString & name) override virtual
Set current name to search founds.
Reimplemented from MusicFoundAbstractWidget.
Definition at line 276 of file musicartistfoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSingleSearch().
Referenced by MusicArtistFoundWidget::initThirdWidget().
void MusicArtistAlbumsFoundWidget::setSongNameById (const QString & id) override virtual
Set current id to search founds.
Implements MusicFoundAbstractWidget.
Definition at line 282 of file musicartistfoundwidget.cpp.
References MusicFoundAbstractWidget::m_downloadThread, MusicFoundAbstractWidget::m_songNameFull, MusicFoundAbstractWidget::setSongName(), and MusicDownLoadQueryThreadAbstract::startToSingleSearch().
Member Data Documentation
QGridLayout* MusicArtistAlbumsFoundWidget::m_gridLayout protected
Definition at line 204 of file musicartistfoundwidget.h.
Referenced by createArtistAlbumsItem(), MusicArtistAlbumsFoundWidget(), resizeWindow(), and ~MusicArtistAlbumsFoundWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistfoundwidget.cpp