TTKMusicPlayer: TTKXmlNodeHelper Class Reference
TTKXmlNodeHelper Class Reference
The class of the ttk xml node hepler.
#include <ttkabstractxml.h>
Public Member Functions
TTKXmlNodeHelper (const QDomNode &root)
void load ()
bool hasNext ()
QDomNode next () const
QString nodeName (const QString &name) const
Private Attributes
QDomNode m_root
QDomNode m_current
QSet< QString > m_nodeNames
Detailed Description
The class of the ttk xml node hepler.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 51 of file ttkabstractxml.h.
Constructor & Destructor Documentation
TTKXmlNodeHelper::TTKXmlNodeHelper (const QDomNode & root) explicit
Object contsructor.
Definition at line 5 of file ttkabstractxml.cpp.
Member Function Documentation
bool TTKXmlNodeHelper::hasNext ()
Check xml has next node.
Definition at line 23 of file ttkabstractxml.cpp.
References m_current, and m_root.
Referenced by load().
void TTKXmlNodeHelper::load ()
Load xml node helper.
Definition at line 12 of file ttkabstractxml.cpp.
References hasNext(), m_current, and m_nodeNames.
Referenced by MusicASXConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), and MusicWPLConfigManager::readBuffer().
QDomNode TTKXmlNodeHelper::next () const
Get xml next node.
Definition at line 62 of file ttkabstractxml.cpp.
References m_current.
QString TTKXmlNodeHelper::nodeName (const QString & name) const
Get match node name case insensitive.
Definition at line 67 of file ttkabstractxml.cpp.
References m_nodeNames, and name.
Member Data Documentation
QDomNode TTKXmlNodeHelper::m_current private
Definition at line 78 of file ttkabstractxml.h.
Referenced by hasNext(), load(), and next().
QSet<QString> TTKXmlNodeHelper::m_nodeNames private
Definition at line 79 of file ttkabstractxml.h.
Referenced by load(), and nodeName().
QDomNode TTKXmlNodeHelper::m_root private
Definition at line 78 of file ttkabstractxml.h.
Referenced by hasNext().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkabstractxml.h
TTKCommon/TTKLibrary/ttkabstractxml.cpp