TTKMusicplayer: MusicLrcContainer Class Reference
MusicLrcContainer Class Reference abstract
The class of the lrc container base.
#include <musiclrccontainer.h>
Public Slots
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
void showLrcErrorWidget ()
Signals
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Public Member Functions
MusicLrcContainer (QWidget *parent=0)
virtual ~MusicLrcContainer ()
virtual void startTimerClock ()=0
virtual void stopLrcMask ()=0
void setLinearGradientColor (MusicLrcColor::LrcColorType lrcColorType)
void setLinearGradientColor (const MusicLrcColor &color)
virtual void setSettingParameter ()
QString getCurrentSongName () const
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 getTotalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * getLrcAnalysisModel () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
void clearAllMusicLRCManager ()
void setSettingParameter (const QString &t)
Protected Attributes
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_musicLrcContainer
MusicLrcSearchWidget * m_musicLrcSearchWidget
Detailed Description
The class of the lrc container base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 23 of file musiclrccontainer.h.
Constructor & Destructor Documentation
MusicLrcContainer::MusicLrcContainer (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 9 of file musiclrccontainer.cpp.
References m_currentTime, m_linkLocalLrc, m_lrcAnalysis, m_musicLrcSearchWidget, and m_totalTime.
MusicLrcContainer::~MusicLrcContainer () virtual
Definition at line 19 of file musiclrccontainer.cpp.
References m_musicLrcSearchWidget.
Member Function Documentation
void MusicLrcContainer::changeCurrentLrcColor (QAction * action) slot
Change current lrc linear color by action index.
Definition at line 69 of file musiclrccontainer.cpp.
References MusicLrcColor::DBlack, MusicLrcColor::DBlue, MusicLrcColor::DGreen, MusicLrcColor::DPurple, MusicLrcColor::DRed, MusicLrcColor::DWhite, MusicLrcColor::DYellow, MusicLrcColor::IBlue, MusicLrcColor::IGray, MusicLrcColor::IGreen, MusicLrcColor::IIndigo, MusicLrcColor::IOrange, MusicLrcColor::IPink, MusicLrcColor::IPurple, MusicLrcColor::IRed, MusicLrcColor::IYellow, and setLinearGradientColor().
Referenced by MusicLrcContainerForDesktop::createColorMenu(), and MusicLrcContainerForInline::createColorMenu().
void MusicLrcContainer::changeCurrentLrcColor (int index) slot
Change current lrc linear color by index.
Definition at line 93 of file musiclrccontainer.cpp.
References MStatic_cast, and setLinearGradientColor().
void MusicLrcContainer::changeCurrentLrcColorCustom () signal
Change current setting widget to color setting widget.
Referenced by currentLrcCustom().
void MusicLrcContainer::changeCurrentLrcColorSetting () signal
Change current setting widget to setting widget.
Referenced by currentLrcCustom().
void MusicLrcContainer::clearAllMusicLRCManager () protected
Clear all music lrc manager.
Definition at line 128 of file musiclrccontainer.cpp.
References m_musicLrcContainer.
Referenced by MusicLrcContainerForDesktop::~MusicLrcContainerForDesktop(), MusicLrcContainerForInline::~MusicLrcContainerForInline(), and MusicLrcContainerForWallpaper::~MusicLrcContainerForWallpaper().
void MusicLrcContainer::currentLrcCustom () slot
Show current setting widget.
Definition at line 63 of file musiclrccontainer.cpp.
References changeCurrentLrcColorCustom(), and changeCurrentLrcColorSetting().
Referenced by MusicLrcContainerForDesktop::contextMenuEvent(), MusicLrcContainerForInline::contextMenuEvent(), MusicLrcContainerForDesktop::createColorMenu(), MusicLrcContainerForInline::createColorMenu(), and MusicLrcContainerForDesktop::creatToolBarWidget().
void MusicLrcContainer::currentLrcUpdated () signal
The current lrc should update, emit it.
Referenced by MusicLrcContainerForDesktop::contextMenuEvent(), MusicLrcContainerForInline::contextMenuEvent(), and MusicLrcContainerForDesktop::creatToolBarWidget().
QString MusicLrcContainer::getClassName () static
Get class object name.
Definition at line 24 of file musiclrccontainer.cpp.
QString MusicLrcContainer::getCurrentSongName () const inline
Set current song name.
Definition at line 64 of file musiclrccontainer.h.
Referenced by MusicRightAreaWidget::setWindowLrcTypeChanged().
MusicLrcAnalysis* MusicLrcContainer::getLrcAnalysisModel () const inline
Get lrc analysis model.
Definition at line 85 of file musiclrccontainer.h.
qint64 MusicLrcContainer::getTotalTime () const
Get current play total time.
Definition at line 58 of file musiclrccontainer.cpp.
References m_totalTime.
void MusicLrcContainer::linearGradientColorChanged () signal
Linear gradient color changed.
Referenced by setLinearGradientColor().
void MusicLrcContainer::linkLrcStateChanged () slot
Link current lrc state changed.
Definition at line 114 of file musiclrccontainer.cpp.
References m_linkLocalLrc, and m_musicLrcContainer.
Referenced by MusicLrcContainerForDesktop::contextMenuEvent(), and MusicLrcContainerForInline::contextMenuEvent().
void MusicLrcContainer::maskLinearGradientColorChanged () signal
Mask linear gradient color changed.
void MusicLrcContainer::searchMusicLrcs () slot
Show search lrcs widget.
Definition at line 98 of file musiclrccontainer.cpp.
References MusicLrcSearchWidget::exec(), m_currentSongName, m_musicLrcSearchWidget, and MusicLrcSearchWidget::setCurrentSongName().
Referenced by MusicLrcContainerForDesktop::contextMenuEvent(), MusicLrcContainerForInline::contextMenuEvent(), and MusicLrcContainerForDesktop::creatToolBarWidget().
void MusicLrcContainer::setCurrentSongName (const QString & name) inline
Set current song name.
Definition at line 68 of file musiclrccontainer.h.
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), and MusicRightAreaWidget::setWindowLrcTypeChanged().
void MusicLrcContainer::setCurrentTime (qint64 time, qint64 total)
Set current play total time.
Definition at line 52 of file musiclrccontainer.cpp.
References m_currentTime, and m_totalTime.
Referenced by MusicRightAreaWidget::updateCurrentLrc().
void MusicLrcContainer::setLinearGradientColor (MusicLrcColor::LrcColorType lrcColorType)
Set linear gradient color.
Definition at line 29 of file musiclrccontainer.cpp.
References MusicLrcColor::mapIndexToColor().
Referenced by changeCurrentLrcColor(), MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicLrcContainerForInline::setItemStyleSheet(), and setSettingParameter().
void MusicLrcContainer::setLinearGradientColor (const MusicLrcColor & color)
Set linear gradient color.
Definition at line 35 of file musiclrccontainer.cpp.
References MusicSettingManager::DLrcColorChoiced, linearGradientColorChanged(), MusicSettingManager::LrcColorChoiced, m_containerType, MusicLrcColor::m_index, m_musicLrcContainer, M_SETTING_PTR, and MusicLrcManager::setLinearGradientColor().
void MusicLrcContainer::setLrcAnalysisModel (MusicLrcAnalysis * analysis) inline
Set lrc analysis model.
Definition at line 81 of file musiclrccontainer.h.
Referenced by MusicLrcContainerForWallpaper::setLrcAnalysisModel().
void MusicLrcContainer::setSettingParameter () virtual
Set setting parameter.
Reimplemented in MusicLrcContainerForDesktop, MusicLrcContainerForInline, and MusicLrcContainerForWallpaper.
Definition at line 47 of file musiclrccontainer.cpp.
References m_containerType.
Referenced by MusicLrcContainerForInline::setSettingParameter(), and MusicLrcContainerForDesktop::setSettingParameter().
void MusicLrcContainer::setSettingParameter (const QString & t) protected
Set setting parameter by diff type.
Definition at line 134 of file musiclrccontainer.cpp.
References m_musicLrcContainer, M_SETTING_PTR, MStatic_cast, MusicUtils::String::readColorConfig(), MusicLrcManager::setFontFamily(), MusicLrcManager::setFontTransparent(), MusicLrcManager::setFontType(), setLinearGradientColor(), and MusicLrcManager::setLrcFontSize().
void MusicLrcContainer::showLrcErrorWidget () slot
Show making error lrcs widget.
Definition at line 123 of file musiclrccontainer.cpp.
References MusicLrcErrorWidget::exec().
Referenced by MusicLrcContainerForInline::contextMenuEvent(), and MusicLrcContainerForDesktop::creatToolBarWidget().
void MusicLrcContainer::showLrcMakedWidget () slot
Show making lrcs widget.
Definition at line 106 of file musiclrccontainer.cpp.
References MusicLrcMakerWidget::durationChanged(), m_currentSongName, m_totalTime, MusicLrcMakerWidget::setCurrentSongName(), and MusicLrcMakerWidget::show().
Referenced by MusicLrcContainerForDesktop::contextMenuEvent(), MusicLrcContainerForInline::contextMenuEvent(), MusicLrcContainerForInline::createNoLrcCurrentInfo(), and MusicLrcContainerForDesktop::creatToolBarWidget().
virtual void MusicLrcContainer::startTimerClock () pure virtual
Start timer clock to draw lrc. Subclass should implement this function.
Implemented in MusicLrcContainerForDesktop, MusicLrcContainerForInline, and MusicLrcContainerForWallpaper.
virtual void MusicLrcContainer::stopLrcMask () pure virtual
Stop timer clock to draw lrc. Subclass should implement this function.
Implemented in MusicLrcContainerForDesktop, MusicLrcContainerForInline, and MusicLrcContainerForWallpaper.
Member Data Documentation
QString MusicLrcContainer::m_containerType protected
Definition at line 151 of file musiclrccontainer.h.
Referenced by MusicLrcContainerForDesktop::MusicLrcContainerForDesktop(), MusicLrcContainerForInline::MusicLrcContainerForInline(), MusicLrcContainerForWallpaper::MusicLrcContainerForWallpaper(), setLinearGradientColor(), and setSettingParameter().
QString MusicLrcContainer::m_currentSongName protected
Definition at line 151 of file musiclrccontainer.h.
Referenced by MusicLrcContainerForInline::getTranslatedLrcFinished(), MusicLrcContainerForInline::musicSongMovieClicked(), searchMusicLrcs(), MusicLrcContainerForInline::showLocalLinkWidget(), showLrcMakedWidget(), MusicLrcContainerForInline::showLrcPosterWidget(), MusicLrcContainerForInline::showSongCommentsWidget(), and MusicLrcContainerForInline::showSoundKMicroWidget().
qint64 MusicLrcContainer::m_currentTime protected
Definition at line 150 of file musiclrccontainer.h.
Referenced by MusicLrcContainerForInline::findText(), MusicLrcContainerForDesktop::initCurrentLrc(), MusicLrcContainerHorizontalDesktop::initCurrentLrc(), MusicLrcContainerVerticalDesktop::initCurrentLrc(), MusicLrcContainer(), MusicLrcContainerForInline::resizeWidth(), MusicLrcContainerForInline::revertLrcTimeSpeed(), and setCurrentTime().
bool MusicLrcContainer::m_linkLocalLrc protected
Definition at line 149 of file musiclrccontainer.h.
Referenced by MusicLrcContainerForDesktop::contextMenuEvent(), MusicLrcContainerForInline::contextMenuEvent(), linkLrcStateChanged(), and MusicLrcContainer().
MusicLrcAnalysis* MusicLrcContainer::m_lrcAnalysis protected
Definition at line 152 of file musiclrccontainer.h.
Referenced by MusicLrcContainerForInline::contextMenuEvent(), MusicLrcContainerForInline::findText(), MusicLrcContainerForWallpaper::initCurrentLrc(), MusicLrcContainerForInline::initCurrentLrc(), MusicLrcContainerForInline::initFunctionLabel(), MusicLrcContainerForInline::lrcCopyClipboard(), MusicLrcContainerForInline::lrcOpenFileDir(), MusicLrcContainerForInline::mouseMoveEvent(), MusicLrcContainerForInline::mouseReleaseEvent(), MusicLrcContainer(), MusicLrcContainerForInline::MusicLrcContainerForInline(), MusicLrcContainerForInline::paintEvent(), MusicLrcContainerForInline::resizeWidth(), MusicLrcContainerForInline::revertLrcTimeSpeed(), MusicLrcContainerForInline::saveLrcTimeChanged(), MusicLrcContainerForInline::setItemStyleSheet(), MusicLrcContainerForInline::setLrcSize(), MusicLrcContainerForInline::setLrcSizeProperty(), MusicLrcContainerForInline::setSongSpeedAndSlow(), MusicLrcContainerForInline::showLrcPosterWidget(), MusicLrcContainerForInline::showNoLrcCurrentInfo(), MusicLrcContainerForInline::startTimerClock(), MusicLrcContainerForInline::stopLrcMask(), MusicLrcContainerForInline::text(), MusicLrcContainerForInline::transLyricFileToTime(), MusicLrcContainerForWallpaper::updateAnimationLrc(), MusicLrcContainerForInline::updateAnimationLrc(), MusicLrcContainerForWallpaper::updateCurrentLrc(), MusicLrcContainerForInline::updateCurrentLrc(), and MusicLrcContainerForInline::~MusicLrcContainerForInline().
QList<MusicLrcManager*> MusicLrcContainer::m_musicLrcContainer protected
Definition at line 153 of file musiclrccontainer.h.
Referenced by clearAllMusicLRCManager(), MusicLrcContainerForDesktop::initCurrentLrc(), MusicLrcContainerForWallpaper::initCurrentLrc(), MusicLrcContainerHorizontalDesktop::initCurrentLrc(), MusicLrcContainerVerticalDesktop::initCurrentLrc(), MusicLrcContainerForInline::initCurrentLrc(), linkLrcStateChanged(), MusicLrcContainerForInline::mouseMoveEvent(), MusicLrcContainerForInline::MusicLrcContainerForInline(), MusicLrcContainerHorizontalDesktop::MusicLrcContainerHorizontalDesktop(), MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop(), MusicLrcContainerForDesktop::resizeLrcSizeArea(), MusicLrcContainerHorizontalDesktop::resizeLrcSizeArea(), MusicLrcContainerVerticalDesktop::resizeLrcSizeArea(), MusicLrcContainerForInline::resizeWidth(), MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicLrcContainerForInline::setItemStyleSheet(), setLinearGradientColor(), MusicLrcContainerForWallpaper::setLrcAnalysisModel(), MusicLrcContainerForInline::setLrcSize(), MusicLrcContainerForInline::setLrcSizeProperty(), MusicLrcContainerForDesktop::setSelfGeometry(), MusicLrcContainerForWallpaper::setSettingParameter(), MusicLrcContainerForDesktop::setSettingParameter(), setSettingParameter(), MusicLrcContainerForDesktop::setSingleLineTypeChanged(), MusicLrcContainerHorizontalDesktop::setSingleLineTypeChanged(), MusicLrcContainerVerticalDesktop::setSingleLineTypeChanged(), MusicLrcContainerForWallpaper::startTimerClock(), MusicLrcContainerForInline::startTimerClock(), MusicLrcContainerForDesktop::startTimerClock(), MusicLrcContainerForWallpaper::stopLrcMask(), MusicLrcContainerForInline::stopLrcMask(), MusicLrcContainerForDesktop::stopLrcMask(), MusicLrcContainerForInline::text(), MusicLrcContainerForInline::transLyricFileToTime(), MusicLrcContainerForWallpaper::updateAnimationLrc(), MusicLrcContainerForInline::updateAnimationLrc(), and MusicLrcContainerForDesktop::updateCurrentLrc().
MusicLrcSearchWidget* MusicLrcContainer::m_musicLrcSearchWidget protected
Definition at line 154 of file musiclrccontainer.h.
Referenced by MusicLrcContainer(), searchMusicLrcs(), and ~MusicLrcContainer().
qint64 MusicLrcContainer::m_totalTime protected
Definition at line 150 of file musiclrccontainer.h.
Referenced by getTotalTime(), MusicLrcContainer(), setCurrentTime(), and showLrcMakedWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainer.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainer.cpp