TTKMusicplayer: MusicLocalSongsManagerWidget Class Reference
MusicLocalSongsManagerWidget Class Reference
The class of the lcal songs manager widget.
#include <musiclocalsongsmanagerwidget.h>
Public Slots
void selectedAllItems (bool check)
void watchDirEnable (bool enable)
void watchDirSelected ()
void watchDirChanged (const QString &path)
void auditionButtonClick ()
void addButtonClick ()
void itemCellOnClick (int row, int col)
void itemDoubleClicked (int row, int col)
void setSongNamePath (const QFileInfoList &name)
void filterScanChanged (int index)
void musicSearchIndexChanged (int row, int col)
void updateFileLists (const QFileInfoList &list)
void setShowlistButton ()
void setShowArtButton ()
void setShowAlbumButton ()
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void resetFlag (MusicObject::ToolsType flag)
void addSongToPlay (const QStringList &names)
Public Member Functions
MusicLocalSongsManagerWidget (QWidget *parent=0)
virtual ~MusicLocalSongsManagerWidget ()
void findExtraDevicePath (const QString &dir)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
void clearAllItems ()
void addAllItems (const QFileInfoList &name)
void addDrivesList ()
void itemsSelected ()
bool filterIndexChanged ()
bool filterIndexCustChanged ()
void controlEnable (bool state)
void loadingLabelState (bool state)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicLocalSongsManagerWidget * m_ui
QFileInfoList m_fileNames
MusicLocalSongsManagerThread * m_thread
MusicObject::MIntsListMap m_searchfileListCache
QFileSystemWatcher * m_fileSystemWatcher
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the lcal songs manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musiclocalsongsmanagerwidget.h.
Constructor & Destructor Documentation
MusicLocalSongsManagerWidget::MusicLocalSongsManagerWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 16 of file musiclocalsongsmanagerwidget.cpp.
References addButtonClick(), addDrivesList(), auditionButtonClick(), filterScanChanged(), MusicSongsSummariziedWidget::getClassName(), getClassName(), MusicGifLabelWidget::Gif_Cicle_Blue, itemCellOnClick(), itemDoubleClicked(), M_CONNECTION_PTR, m_fileSystemWatcher, m_thread, m_ui, MusicUIObject::MBackgroundStyle07, MusicUIObject::MCheckBoxStyle03, MusicUIObject::MComboBoxStyle01, MusicUIObject::MItemView01, MusicUIObject::MPushButtonStyle04, MusicUIObject::MPushButtonStyle10, MusicUIObject::MScrollBarStyle01, MusicUIObject::MToolButtonStyle01, MusicUIObject::MToolButtonStyle02, MusicUIObject::MToolButtonStyle04, musicSearchIndexChanged(), selectedAllItems(), setShowAlbumButton(), setShowArtButton(), setShowlistButton(), setSongNamePath(), updateFileLists(), watchDirChanged(), watchDirEnable(), and watchDirSelected().
MusicLocalSongsManagerWidget::~MusicLocalSongsManagerWidget () virtual
Definition at line 119 of file musiclocalsongsmanagerwidget.cpp.
References clearAllItems(), getClassName(), M_CONNECTION_PTR, m_fileSystemWatcher, m_thread, m_ui, and MusicLocalSongsManagerThread::stopAndQuitThread().
Member Function Documentation
void MusicLocalSongsManagerWidget::addAllItems (const QFileInfoList & name) protected
Add all file items into list.
Definition at line 431 of file musiclocalsongsmanagerwidget.cpp.
References m_ui.
Referenced by musicSearchIndexChanged(), setShowlistButton(), and updateFileLists().
void MusicLocalSongsManagerWidget::addButtonClick () slot
Add music song to play list.
Definition at line 211 of file musiclocalsongsmanagerwidget.cpp.
References MusicMessageBox::exec(), itemsSelected(), m_ui, and MusicMessageBox::setText().
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::addDrivesList () protected
Add current system all supported drives list.
Definition at line 438 of file musiclocalsongsmanagerwidget.cpp.
References m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::addSongToPlay (const QStringList & names) signal
Add current selected song to play lists.
Referenced by itemCellOnClick(), itemDoubleClicked(), and itemsSelected().
void MusicLocalSongsManagerWidget::auditionButtonClick () slot
Music song audition play.
Definition at line 193 of file musiclocalsongsmanagerwidget.cpp.
References MusicMessageBox::exec(), itemsSelected(), m_ui, and MusicMessageBox::setText().
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::clearAllItems () protected
Clear All Items.
Remove all the original item
Definition at line 415 of file musiclocalsongsmanagerwidget.cpp.
References m_ui.
Referenced by controlEnable(), musicSearchIndexChanged(), and ~MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 409 of file musiclocalsongsmanagerwidget.cpp.
References resetFlag(), and MusicObject::TT_LocalManager.
void MusicLocalSongsManagerWidget::controlEnable (bool state) protected
Control enable or disable.
Definition at line 525 of file musiclocalsongsmanagerwidget.cpp.
References clearAllItems(), m_searchfileListCache, and m_ui.
Referenced by setShowAlbumButton(), setShowArtButton(), setShowlistButton(), and updateFileLists().
bool MusicLocalSongsManagerWidget::filterIndexChanged () protected
Current drive index changed.
Definition at line 480 of file musiclocalsongsmanagerwidget.cpp.
References MusicMessageBox::exec(), m_thread, m_ui, MusicLocalSongsManagerThread::setFindFilePath(), and MusicMessageBox::setText().
Referenced by filterScanChanged().
bool MusicLocalSongsManagerWidget::filterIndexCustChanged () protected
Current custom dir path changed.
Definition at line 508 of file musiclocalsongsmanagerwidget.cpp.
References m_thread, and MusicLocalSongsManagerThread::setFindFilePath().
Referenced by filterScanChanged().
void MusicLocalSongsManagerWidget::filterScanChanged (int index) slot
Start to fetch file or files.
Definition at line 271 of file musiclocalsongsmanagerwidget.cpp.
References filterIndexChanged(), filterIndexCustChanged(), loadingLabelState(), M_LOGGER_INFO, m_thread, MusicLocalSongsManagerThread::start(), and MusicLocalSongsManagerThread::stopAndQuitThread().
Referenced by findExtraDevicePath(), and MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::findExtraDevicePath (const QString & dir)
Find extra device path.
Definition at line 134 of file musiclocalsongsmanagerwidget.cpp.
References DEFAULT_INDEX_LEVEL0, filterScanChanged(), m_thread, m_ui, MusicUtils::Widget::setComboboxText(), and MusicLocalSongsManagerThread::setFindFilePath().
Referenced by MusicMobileDevicesWidget::showMobileManager().
QString MusicLocalSongsManagerWidget::getClassName () static
Get class object name.
Definition at line 129 of file musiclocalsongsmanagerwidget.cpp.
Referenced by MusicLocalSongsManagerWidget(), MusicConnectionPool::poolConnect(), and ~MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::itemCellOnClick (int row, int col) slot
Item cell on click by row and col.
Definition at line 229 of file musiclocalsongsmanagerwidget.cpp.
References addSongToPlay(), m_fileNames, m_searchfileListCache, and m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::itemDoubleClicked (int row, int col) slot
Item cell on double click by row and col.
Definition at line 250 of file musiclocalsongsmanagerwidget.cpp.
References addSongToPlay(), m_fileNames, m_searchfileListCache, and m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::itemsSelected () protected
Set current item or items selected.
Definition at line 450 of file musiclocalsongsmanagerwidget.cpp.
References addSongToPlay(), m_fileNames, m_searchfileListCache, and m_ui.
Referenced by addButtonClick(), and auditionButtonClick().
void MusicLocalSongsManagerWidget::loadingLabelState (bool state) protected
Loading label disable.
Definition at line 538 of file musiclocalsongsmanagerwidget.cpp.
References m_ui.
Referenced by filterScanChanged(), setShowAlbumButton(), setShowArtButton(), setShowlistButton(), and setSongNamePath().
void MusicLocalSongsManagerWidget::musicSearchIndexChanged (int row, int col) slot
Search file from list.
Definition at line 295 of file musiclocalsongsmanagerwidget.cpp.
References addAllItems(), clearAllItems(), m_fileNames, m_searchfileListCache, and m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by closeEvent().
void MusicLocalSongsManagerWidget::selectedAllItems (bool check) slot
Select all items.
Definition at line 141 of file musiclocalsongsmanagerwidget.cpp.
References m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::setShowAlbumButton () slot
Select to show album mode.
Definition at line 368 of file musiclocalsongsmanagerwidget.cpp.
References controlEnable(), MusicSongTag::getAlbum(), loadingLabelState(), LOCAL_MANAGER_INDEX_1, m_ui, and MusicSongTag::read().
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::setShowArtButton () slot
Select to show art mode.
Definition at line 333 of file musiclocalsongsmanagerwidget.cpp.
References controlEnable(), MusicSongTag::getArtist(), loadingLabelState(), LOCAL_MANAGER_INDEX_1, m_ui, and MusicSongTag::read().
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::setShowlistButton () slot
Select to show list mode.
Definition at line 324 of file musiclocalsongsmanagerwidget.cpp.
References addAllItems(), controlEnable(), loadingLabelState(), LOCAL_MANAGER_INDEX_0, m_fileNames, and m_ui.
Referenced by MusicLocalSongsManagerWidget(), and setSongNamePath().
void MusicLocalSongsManagerWidget::setSongNamePath (const QFileInfoList & name) slot
Send the searched file or path.
Definition at line 262 of file musiclocalsongsmanagerwidget.cpp.
References loadingLabelState(), M_LOGGER_INFO, m_ui, and setShowlistButton().
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::show () slot
Override show function.
Definition at line 403 of file musiclocalsongsmanagerwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Referenced by MusicMobileDevicesWidget::showMobileManager().
void MusicLocalSongsManagerWidget::updateFileLists (const QFileInfoList & list) slot
Update file lists.
Definition at line 316 of file musiclocalsongsmanagerwidget.cpp.
References addAllItems(), controlEnable(), LOCAL_MANAGER_INDEX_0, m_fileNames, and m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::watchDirChanged (const QString & path) slot
Watch dir path changed.
Definition at line 186 of file musiclocalsongsmanagerwidget.cpp.
References m_thread, MusicLocalSongsManagerThread::setFindFilePath(), MusicLocalSongsManagerThread::start(), and MusicLocalSongsManagerThread::stopAndQuitThread().
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::watchDirEnable (bool enable) slot
Watch dir enable or not.
Definition at line 156 of file musiclocalsongsmanagerwidget.cpp.
References m_fileSystemWatcher, and m_ui.
Referenced by MusicLocalSongsManagerWidget().
void MusicLocalSongsManagerWidget::watchDirSelected () slot
Watch dir selected.
Definition at line 168 of file musiclocalsongsmanagerwidget.cpp.
References m_fileSystemWatcher, and m_ui.
Referenced by MusicLocalSongsManagerWidget().
Member Data Documentation
QFileInfoList MusicLocalSongsManagerWidget::m_fileNames protected
Definition at line 166 of file musiclocalsongsmanagerwidget.h.
Referenced by itemCellOnClick(), itemDoubleClicked(), itemsSelected(), musicSearchIndexChanged(), setShowlistButton(), and updateFileLists().
QFileSystemWatcher* MusicLocalSongsManagerWidget::m_fileSystemWatcher protected
Definition at line 169 of file musiclocalsongsmanagerwidget.h.
Referenced by MusicLocalSongsManagerWidget(), watchDirEnable(), watchDirSelected(), and ~MusicLocalSongsManagerWidget().
MusicObject::MIntsListMap MusicLocalSongsManagerWidget::m_searchfileListCache protected
Definition at line 168 of file musiclocalsongsmanagerwidget.h.
Referenced by controlEnable(), itemCellOnClick(), itemDoubleClicked(), itemsSelected(), and musicSearchIndexChanged().
MusicLocalSongsManagerThread* MusicLocalSongsManagerWidget::m_thread protected
Definition at line 167 of file musiclocalsongsmanagerwidget.h.
Referenced by filterIndexChanged(), filterIndexCustChanged(), filterScanChanged(), findExtraDevicePath(), MusicLocalSongsManagerWidget(), watchDirChanged(), and ~MusicLocalSongsManagerWidget().
Ui::MusicLocalSongsManagerWidget* MusicLocalSongsManagerWidget::m_ui protected
Definition at line 165 of file musiclocalsongsmanagerwidget.h.
Referenced by addAllItems(), addButtonClick(), addDrivesList(), auditionButtonClick(), clearAllItems(), controlEnable(), filterIndexChanged(), findExtraDevicePath(), itemCellOnClick(), itemDoubleClicked(), itemsSelected(), loadingLabelState(), MusicLocalSongsManagerWidget(), musicSearchIndexChanged(), selectedAllItems(), setShowAlbumButton(), setShowArtButton(), setShowlistButton(), setSongNamePath(), show(), updateFileLists(), watchDirEnable(), watchDirSelected(), and ~MusicLocalSongsManagerWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musiclocalsongsmanagerwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musiclocalsongsmanagerwidget.cpp