TTKMusicplayer: MusicSongsToolItemRenamedWidget Class Reference
MusicSongsToolItemRenamedWidget Class Reference
The class of the song tool item rename widget.
#include <musicsongstoolitemrenamedwidget.h>
Public Slots
void textChanged (const QString &text)
void renameFinished ()
void animationCloseChanged ()
Signals
void renameFinished (const QString &text)
Public Member Functions
MusicSongsToolItemRenamedWidget (QWidget *parent=nullptr)
MusicSongsToolItemRenamedWidget (const QString &text, QWidget *parent=nullptr)
Protected Member Functions
virtual void focusOutEvent (QFocusEvent *event) overridefinal
Protected Attributes
bool m_focusBlock
Detailed Description
The class of the song tool item rename widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicsongstoolitemrenamedwidget.h.
Constructor & Destructor Documentation
MusicSongsToolItemRenamedWidget::MusicSongsToolItemRenamedWidget (QWidget * parent = nullptr) explicit
Object contsructor by index and origin name.
Definition at line 6 of file musicsongstoolitemrenamedwidget.cpp.
References m_focusBlock, MusicUIObject::MQSSLineEditStyle01, renameFinished(), and textChanged().
MusicSongsToolItemRenamedWidget::MusicSongsToolItemRenamedWidget (const QString & text, QWidget * parent = nullptr) explicit
Definition at line 22 of file musicsongstoolitemrenamedwidget.cpp.
Member Function Documentation
void MusicSongsToolItemRenamedWidget::animationCloseChanged () slot
Animation close changed.
Definition at line 47 of file musicsongstoolitemrenamedwidget.cpp.
References m_focusBlock.
Referenced by textChanged().
void MusicSongsToolItemRenamedWidget::focusOutEvent (QFocusEvent * event) final override protected virtual
Override the widget event.
Definition at line 53 of file musicsongstoolitemrenamedwidget.cpp.
References m_focusBlock, and renameFinished().
void MusicSongsToolItemRenamedWidget::renameFinished (const QString & text) signal
Tool rename is finished it emit.
void MusicSongsToolItemRenamedWidget::renameFinished () slot
Tool rename is finished.
Definition at line 42 of file musicsongstoolitemrenamedwidget.cpp.
Referenced by focusOutEvent(), and MusicSongsToolItemRenamedWidget().
void MusicSongsToolItemRenamedWidget::textChanged (const QString & text) slot
Input text data changed.
Definition at line 28 of file musicsongstoolitemrenamedwidget.cpp.
References animationCloseChanged(), MusicUtils::String::illegalCharacters(), MusicUtils::String::isCharacterValid(), m_focusBlock, MusicToastLabel::popup(), and MusicToastLabel::setText().
Referenced by MusicSongsToolItemRenamedWidget().
Member Data Documentation
bool MusicSongsToolItemRenamedWidget::m_focusBlock protected
Definition at line 65 of file musicsongstoolitemrenamedwidget.h.
Referenced by animationCloseChanged(), focusOutEvent(), MusicSongsToolItemRenamedWidget(), and textChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongstoolitemrenamedwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongstoolitemrenamedwidget.cpp