TTKMusicplayer: MusicPluginItem Class Reference
MusicPluginItem Class Reference
The class of the plugin item widget.
Public Types
enum PluginType {
DECODER = QTreeWidgetItem::UserType, EFFECT, VISUAL, TRANSPORTS,
OUTPUT
}
Public Member Functions
MusicPluginItem (QTreeWidgetItem *parent, DecoderFactory *factory, const QString &path)
MusicPluginItem (QTreeWidgetItem *parent, EffectFactory *factory, const QString &path)
MusicPluginItem (QTreeWidgetItem *parent, VisualFactory *factory, const QString &path)
MusicPluginItem (QTreeWidgetItem *parent, InputSourceFactory *factory, const QString &path)
MusicPluginItem (QTreeWidgetItem *parent, OutputFactory *factory, const QString &path)
bool hasSettings () const
void showSettingWidget () const
void setEnabled (bool enabled)
void initialize (bool state, bool enable, const MusicPluginProperty &property)
Private Attributes
void * m_factory
Detailed Description
The class of the plugin item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 22 of file musicpluginwidget.cpp.
Member Enumeration Documentation
enum MusicPluginItem::PluginType
Enumerator
DECODER
EFFECT
VISUAL
TRANSPORTS
OUTPUT
Definition at line 81 of file musicpluginwidget.cpp.
Constructor & Destructor Documentation
MusicPluginItem::MusicPluginItem (QTreeWidgetItem * parent, DecoderFactory * factory, const QString & path) inline
Definition at line 25 of file musicpluginwidget.cpp.
References DecoderProperties::description, DecoderProperties::hasSettings, initialize(), Decoder::isEnabled(), m_factory, MusicPluginProperty::m_name, DecoderProperties::name, and DecoderFactory::properties().
MusicPluginItem::MusicPluginItem (QTreeWidgetItem * parent, EffectFactory * factory, const QString & path) inline
Definition at line 37 of file musicpluginwidget.cpp.
References EffectProperties::hasSettings, initialize(), Effect::isEnabled(), m_factory, MusicPluginProperty::m_name, EffectProperties::name, and EffectFactory::properties().
MusicPluginItem::MusicPluginItem (QTreeWidgetItem * parent, VisualFactory * factory, const QString & path) inline
Definition at line 48 of file musicpluginwidget.cpp.
References VisualProperties::hasSettings, initialize(), Visual::isEnabled(), m_factory, MusicPluginProperty::m_name, VisualProperties::name, and VisualFactory::properties().
MusicPluginItem::MusicPluginItem (QTreeWidgetItem * parent, InputSourceFactory * factory, const QString & path) inline
Definition at line 59 of file musicpluginwidget.cpp.
References InputSourceProperties::hasSettings, initialize(), InputSource::isEnabled(), m_factory, MusicPluginProperty::m_name, InputSourceProperties::name, and InputSourceFactory::properties().
MusicPluginItem::MusicPluginItem (QTreeWidgetItem * parent, OutputFactory * factory, const QString & path) inline
Definition at line 70 of file musicpluginwidget.cpp.
References Output::currentFactory(), OutputProperties::hasSettings, initialize(), m_factory, MusicPluginProperty::m_name, OutputProperties::name, and OutputFactory::properties().
Member Function Documentation
bool MusicPluginItem::hasSettings () const inline
Definition at line 90 of file musicpluginwidget.cpp.
References DECODER, EFFECT, m_factory, OUTPUT, TRANSPORTS, TTKStatic_cast, and VISUAL.
Referenced by MusicPluginWidget::pluginItemChanged().
void MusicPluginItem::initialize (bool state, bool enable, const MusicPluginProperty & property) inline
Definition at line 136 of file musicpluginwidget.cpp.
References MusicPluginProperty::m_description, MusicPluginProperty::m_name, MusicPluginProperty::m_setting, MusicPluginProperty::m_type, MUSIC_CHECK_ROLE, MUSIC_ENABLE_ROLE, and MUSIC_TEXT_ROLE.
Referenced by MusicPluginItem().
void MusicPluginItem::setEnabled (bool enabled) inline
Definition at line 116 of file musicpluginwidget.cpp.
References DECODER, EFFECT, m_factory, OUTPUT, Output::setCurrentFactory(), InputSource::setEnabled(), Decoder::setEnabled(), TRANSPORTS, TTKStatic_cast, and VISUAL.
void MusicPluginItem::showSettingWidget () const inline
Definition at line 103 of file musicpluginwidget.cpp.
References DECODER, EFFECT, m_factory, OUTPUT, TRANSPORTS, TTKStatic_cast, and VISUAL.
Referenced by MusicPluginWidget::pluginButtonClicked().
Member Data Documentation
void* MusicPluginItem::m_factory private
Definition at line 160 of file musicpluginwidget.cpp.
Referenced by hasSettings(), MusicPluginItem(), setEnabled(), and showSettingWidget().
The documentation for this class was generated from the following file:
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.cpp