TTKMusicPlayer: TTK::TTKQmmp Namespace Reference
TTK::TTKQmmp Namespace Reference
Functions
TTK_MODULE_EXPORT QString pluginPath (const QString &module, const QString &format)
TTK_MODULE_EXPORT bool isVisualEnabled (const QString &name)
TTK_MODULE_EXPORT void setVisualEnabled (const QString &name, bool enabled, QWidget *parent)
TTK_MODULE_EXPORT bool isEffectEnabled (const QString &name)
TTK_MODULE_EXPORT void setEffectEnabled (const QString &name, bool enabled)
TTK_MODULE_EXPORT void setEffectsEnabled (bool enabled)
TTK_MODULE_EXPORT MusicPluginPropertyList effectModules ()
TTK_MODULE_EXPORT void showEffectSetting (const QString &name, QWidget *parent)
TTK_MODULE_EXPORT void updateBaseConfig ()
TTK_MODULE_EXPORT void updateBlurConfig ()
TTK_MODULE_EXPORT void updateVoiceConfig (bool update, int &value)
Function Documentation
MusicPluginPropertyList TTK::TTKQmmp::effectModules ()
Get all effect plugin's property.
Definition at line 82 of file musicqmmputils.cpp.
References Effect::factories(), and MusicPluginProperty::m_type.
Referenced by MusicSoundEffectsWidget::initialize(), and MusicSoundEffectsWidget::updateConfig().
bool TTK::TTKQmmp::isEffectEnabled (const QString & name)
Get the effect plugin is enabled or not.
Definition at line 50 of file musicqmmputils.cpp.
References Effect::factories(), Effect::isEnabled(), and name.
Referenced by MusicSoundEffectsWidget::initialize(), MusicSoundEffectsWidget::updateConfig(), and MusicVoicePopWidget::updateVoiceRemove().
bool TTK::TTKQmmp::isVisualEnabled (const QString & name)
Get the visual plugin is enabled or not.
Definition at line 25 of file musicqmmputils.cpp.
References Visual::factories(), Visual::isEnabled(), and name.
QString TTK::TTKQmmp::pluginPath (const QString & module, const QString & format)
Get qmmp plugin dir path.
Definition at line 12 of file musicqmmputils.cpp.
References Qmmp::pluginPath().
Referenced by MusicSpectrumWidget::createLightWidget(), and MusicReplayGainWidget::initialize().
void TTK::TTKQmmp::setEffectEnabled (const QString & name, bool enabled)
Set whether the effect plugin is enabled.
Definition at line 62 of file musicqmmputils.cpp.
References Effect::factories(), name, and Effect::setEnabled().
Referenced by MusicSoundEffectsItemWidget::setPluginEnabled(), MusicSoundEffectsWidget::updateConfig(), and MusicVoicePopWidget::updateVoiceRemove().
void TTK::TTKQmmp::setEffectsEnabled (bool enabled)
Set whether the all effect plugins is enabled.
Definition at line 74 of file musicqmmputils.cpp.
References Effect::factories(), and Effect::setEnabled().
Referenced by MusicEnhancedPopWidget::setEnhancedSongConfig().
void TTK::TTKQmmp::setVisualEnabled (const QString & name, bool enabled, QWidget * parent)
Set whether the visual plugin is enabled.
Definition at line 37 of file musicqmmputils.cpp.
References Visual::factories(), Visual::initialize(), name, and Visual::setEnabled().
Referenced by MusicSpectrumWidget::createModuleWidget(), MusicSpectrumWidget::createSpectrumWidget(), MusicRemoteWidgetForRipple::createVisualWidget(), MusicSpectrumWidget::fullscreenByUser(), MusicBlurSpecturmModule::removeSpectrum(), MusicRemoteWidgetForRipple::removeVisualWidget(), MusicBlurSpecturmModule::show(), and MusicSpectrumWidget::~MusicSpectrumWidget().
void TTK::TTKQmmp::showEffectSetting (const QString & name, QWidget * parent)
Show effect setting control widget.
Definition at line 102 of file musicqmmputils.cpp.
References Effect::factories(), and name.
Referenced by MusicSoundEffectsItemWidget::soundEffectValueChanged().
void TTK::TTKQmmp::updateBaseConfig ()
Update base config.
Definition at line 119 of file musicqmmputils.cpp.
References ARCHIVE_DIR_FULL, CACHE_DIR_FULL, and Qmmp::configFile().
Referenced by MusicRunTimeManager::execute().
void TTK::TTKQmmp::updateBlurConfig ()
Update blur spectrum config.
Definition at line 131 of file musicqmmputils.cpp.
References Qmmp::configFile(), G_SETTING_PTR, MusicSettingManager::RippleSpectrumColor, and MusicSettingManager::RippleSpectrumTransparent.
Referenced by MusicBlurSpecturmModule::update().
void TTK::TTKQmmp::updateVoiceConfig (bool update, int & value)
Update voice effect config.
Definition at line 142 of file musicqmmputils.cpp.
References Qmmp::configFile().
Referenced by MusicVoicePopWidget::enterEvent(), and MusicVoicePopWidget::valueChanged().