TTKMusicplayer: MusicWindowExtras Class Reference
MusicWindowExtras Class Reference
The class of the windows extras.
#include <musicwindowextras.h>
Public Member Functions
MusicWindowExtras (QObject *parent=nullptr)
~MusicWindowExtras ()
void setCurrentPlayStatus (bool status) const
void disableBlurBehindWindow (bool enable)
bool isDisableBlurBehindWindow () const
Protected Attributes
bool m_disableBlurBehindWindow
Detailed Description
The class of the windows extras.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 36 of file musicwindowextras.h.
Constructor & Destructor Documentation
MusicWindowExtras::MusicWindowExtras (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 9 of file musicwindowextras.cpp.
References disableBlurBehindWindow(), m_disableBlurBehindWindow, and TTKStatic_cast.
MusicWindowExtras::~MusicWindowExtras ()
Definition at line 26 of file musicwindowextras.cpp.
Member Function Documentation
void MusicWindowExtras::disableBlurBehindWindow (bool enable)
Enable or disable blur behind window.
Definition at line 36 of file musicwindowextras.cpp.
References m_disableBlurBehindWindow.
Referenced by MusicWindowExtras(), and MusicBottomAreaWidget::setWindowConcise().
bool MusicWindowExtras::isDisableBlurBehindWindow () const inline
Get blur behind window state.
Definition at line 58 of file musicwindowextras.h.
Referenced by MusicBottomAreaWidget::setWindowConcise().
void MusicWindowExtras::setCurrentPlayStatus (bool status) const
Set current play state button.
Definition at line 45 of file musicwindowextras.cpp.
Referenced by MusicBottomAreaWidget::setCurrentPlayStatus().
Member Data Documentation
bool MusicWindowExtras::m_disableBlurBehindWindow protected
Definition at line 73 of file musicwindowextras.h.
Referenced by disableBlurBehindWindow(), and MusicWindowExtras().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicwindowextras.h
TTKModule/TTKWidget/musicWidgetKits/musicwindowextras.cpp