TTKMusicplayer: MusicPlayer Class Reference
MusicPlayer Class Reference
The class of the music player.
#include <musicplayer.h>
Public Types
enum Enhanced {
EnhancedOff, Music3D, MusicNICAM, MusicSubwoofer,
MusicVocal
}
Public Slots
void play ()
void pause ()
void stop ()
void setEqEffect (const MusicObject::MIntList &hz)
void setEnaleEffect (bool enable)
void setEqInformation ()
void setSoundEffectVolume (int value)
void removeCurrentMedia ()
Signals
void stateChanged (MusicObject::PlayState newState)
void durationChanged (qint64 duration)
void positionChanged (qint64 position)
void volumeChanged (int volume)
void mutedChanged (bool muted)
Public Member Functions
MusicPlayer (QObject *parent=0)
qmmp incldue
~MusicPlayer ()
bool isPlaying () const
MusicObject::PlayState state () const
void setPlaylist (MusicPlaylist *playlist)
MusicPlaylist * playlist () const
qint64 duration () const
qint64 position () const
void playNext ()
void playPrevious ()
int volume () const
void setVolume (int volume)
bool isMuted () const
void setMuted (bool muted)
void setPosition (qint64 position)
void setMusicEnhanced (Enhanced type)
Enhanced getMusicEnhanced () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
void setMusicEnhancedCase ()
Protected Attributes
MusicPlaylist * m_playlist
MusicObject::PlayState m_state
SoundCore * m_music
QTimer m_timer
QString m_currentMedia
Enhanced m_musicEnhanced
qint64 m_duration
int m_tryTimes
int m_volumeMusic3D
int m_balance
float m_posOnCircle
Private Slots
void update ()
void getCurrentDuration ()
Detailed Description
The class of the music player.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 26 of file musicplayer.h.
Member Enumeration Documentation
enum MusicPlayer::Enhanced
Enumerator
EnhancedOff
enhanced off, no any effect
Music3D
3d music effect
MusicNICAM
nicam music effect
MusicSubwoofer
subwoofer music effect
MusicVocal
vocal music effect
Definition at line 30 of file musicplayer.h.
Constructor & Destructor Documentation
MusicPlayer::MusicPlayer (QObject * parent = 0) explicit
qmmp incldue
Object contsructor.
Definition at line 11 of file musicplayer.cpp.
References EnhancedOff, getClassName(), m_balance, M_CONNECTION_PTR, m_duration, m_music, m_musicEnhanced, m_playlist, m_posOnCircle, m_state, m_timer, m_tryTimes, m_volumeMusic3D, MusicObject::PS_StoppedState, setEnaleEffect(), and update().
MusicPlayer::~MusicPlayer ()
Definition at line 30 of file musicplayer.cpp.
References m_music.
Member Function Documentation
qint64 MusicPlayer::duration () const
Get current player duration.
Definition at line 61 of file musicplayer.cpp.
References m_music, and SoundCore::totalTime().
Referenced by getCurrentDuration(), and MusicApplication::positionChanged().
void MusicPlayer::durationChanged (qint64 duration) signal
Current duration changed.
Referenced by getCurrentDuration().
QString MusicPlayer::getClassName () static
Get class object name.
Definition at line 35 of file musicplayer.cpp.
Referenced by MusicEqualizerDialog::MusicEqualizerDialog(), MusicLrcMakerWidget::MusicLrcMakerWidget(), MusicPlayer(), MusicSoundEffectsWidget::MusicSoundEffectsWidget(), and MusicConnectionPool::poolConnect().
void MusicPlayer::getCurrentDuration () private slot
Get current duration by time out.
Definition at line 284 of file musicplayer.cpp.
References duration(), durationChanged(), m_duration, m_tryTimes, and MT_MS.
Referenced by play().
MusicPlayer::Enhanced MusicPlayer::getMusicEnhanced () const
Get current music enhanced effect.
Definition at line 127 of file musicplayer.cpp.
References m_musicEnhanced.
Referenced by MusicApplication::writeXMLConfigToText().
bool MusicPlayer::isMuted () const
Get current player mute state.
Definition at line 94 of file musicplayer.cpp.
References SoundCore::isMuted(), and m_music.
Referenced by MusicApplication::musicVolumeMute(), and volume().
bool MusicPlayer::isPlaying () const
Get current player is playing or not.
Definition at line 40 of file musicplayer.cpp.
References m_state, and MusicObject::PS_PlayingState.
Referenced by MusicApplication::isPlaying().
void MusicPlayer::mutedChanged (bool muted) signal
Current mute state changed.
void MusicPlayer::pause () slot
Player to pause.
Definition at line 174 of file musicplayer.cpp.
References m_music, m_state, m_timer, SoundCore::pause(), and MusicObject::PS_PausedState.
Referenced by MusicApplication::musicStatePlay().
void MusicPlayer::play () slot
Player to play.
Get the current state of play
When the pause time for recovery
The current playback path
Every second emits a signal change information
Read the configuration settings for the sound
Definition at line 132 of file musicplayer.cpp.
References MusicPlaylist::currentMediaString(), MusicSettingManager::EnhancedBalanceChoiced, getCurrentDuration(), MusicPlaylist::isEmpty(), m_currentMedia, m_music, m_playlist, M_SETTING_PTR, m_state, m_timer, m_tryTimes, MT_S2MS, SoundCore::pause(), Qmmp::Paused, SoundCore::play(), positionChanged(), MusicObject::PS_PlayingState, MusicObject::PS_StoppedState, setSoundEffectVolume(), setVolume(), state(), SoundCore::state(), volume(), and MusicSettingManager::VolumeChoiced.
Referenced by MusicApplication::musicStatePlay(), and update().
MusicPlaylist * MusicPlayer::playlist () const
Get current play list.
Definition at line 56 of file musicplayer.cpp.
References m_playlist.
Referenced by setPlaylist().
void MusicPlayer::playNext ()
Set current player to next music.
Definition at line 71 of file musicplayer.cpp.
References MusicPlaylist::currentIndex(), m_playlist, MusicPlaylist::mediaCount(), and MusicPlaylist::setCurrentIndex().
Referenced by MusicApplication::musicPlayNext().
void MusicPlayer::playPrevious ()
Set current player to previous music.
Definition at line 77 of file musicplayer.cpp.
References MusicPlaylist::currentIndex(), m_playlist, and MusicPlaylist::setCurrentIndex().
Referenced by MusicApplication::musicPlayPrevious().
qint64 MusicPlayer::position () const
Get current player postion.
Definition at line 66 of file musicplayer.cpp.
References SoundCore::elapsed(), and m_music.
Referenced by update().
void MusicPlayer::positionChanged (qint64 position) signal
Current position changed.
Referenced by play(), and update().
void MusicPlayer::removeCurrentMedia () slot
Remove current music media data.
Definition at line 242 of file musicplayer.cpp.
References m_music, m_timer, and SoundCore::stop().
void MusicPlayer::setEnaleEffect (bool enable) slot
Set enable to set current equalizer effect.
Definition at line 205 of file musicplayer.cpp.
References setEqEffect().
Referenced by MusicPlayer(), setEqInformation(), and update().
void MusicPlayer::setEqEffect (const MusicObject::MIntList & hz) slot
Set current equalizer effect.
Definition at line 188 of file musicplayer.cpp.
References EqSettings::EQ_BANDS_10, SoundCore::eqSettings(), m_music, EqSettings::setEnabled(), SoundCore::setEqSettings(), EqSettings::setGain(), and EqSettings::setPreamp().
Referenced by setEnaleEffect(), setEqInformation(), and setMusicEnhancedCase().
void MusicPlayer::setEqInformation () slot
Read equalizer effect from config file.
Read the equalizer parameters from a configuration file
Definition at line 213 of file musicplayer.cpp.
References MusicSettingManager::EqualizerEnableChoiced, MusicSettingManager::EqualizerValueChoiced, M_SETTING_PTR, setEnaleEffect(), and setEqEffect().
Referenced by MusicApplication::readXMLConfigFromText().
void MusicPlayer::setMusicEnhanced (Enhanced type)
Set current music enhanced effect.
Definition at line 110 of file musicplayer.cpp.
References m_balance, m_music, m_musicEnhanced, m_volumeMusic3D, Music3D, SoundCore::setBalance(), setMusicEnhancedCase(), SoundCore::setVolume(), and volume().
Referenced by MusicApplication::musicEnhancedMusicChanged().
void MusicPlayer::setMusicEnhancedCase () protected
Set current music enhanced effect option.
Definition at line 297 of file musicplayer.cpp.
References EnhancedOff, m_musicEnhanced, MusicNICAM, MusicSubwoofer, MusicVocal, and setEqEffect().
Referenced by setMusicEnhanced().
void MusicPlayer::setMuted (bool muted)
Set current player mute or not.
Definition at line 99 of file musicplayer.cpp.
References m_music, m_volumeMusic3D, SoundCore::setMuted(), and SoundCore::volume().
Referenced by MusicApplication::musicVolumeMute().
void MusicPlayer::setPlaylist (MusicPlaylist * playlist)
Set current play list.
Definition at line 50 of file musicplayer.cpp.
References m_playlist, and playlist().
void MusicPlayer::setPosition (qint64 position)
Set current play pos.
Definition at line 105 of file musicplayer.cpp.
References m_music, and SoundCore::seek().
Referenced by MusicApplication::musicPlayAnyTimeAt(), and MusicApplication::updateCurrentTime().
void MusicPlayer::setSoundEffectVolume (int value) slot
Set current player volume.
Definition at line 236 of file musicplayer.cpp.
References m_balance, m_music, and SoundCore::setBalance().
Referenced by play().
void MusicPlayer::setVolume (int volume)
Set current player volume.
Definition at line 88 of file musicplayer.cpp.
References m_music, m_volumeMusic3D, SoundCore::setVolume(), and volume().
Referenced by MusicApplication::musicVolumeChanged(), and play().
MusicObject::PlayState MusicPlayer::state () const
Get current player state.
Definition at line 45 of file musicplayer.cpp.
References m_state.
Referenced by play(), and update().
void MusicPlayer::stateChanged (MusicObject::PlayState newState) signal
Current state changed.
Referenced by update().
void MusicPlayer::stop () slot
Player to stop.
Definition at line 181 of file musicplayer.cpp.
References m_music, m_state, m_timer, MusicObject::PS_StoppedState, and SoundCore::stop().
Referenced by MusicApplication::musicPlayIndex(), and MusicApplication::showCurrentSong().
void MusicPlayer::update () private slot
Player one second time out.
3D music settings
Definition at line 248 of file musicplayer.cpp.
References MusicPlaylist::currentIndex(), SoundCore::isMuted(), m_music, m_musicEnhanced, m_playlist, m_posOnCircle, m_timer, Music3D, Qmmp::Paused, play(), MusicPlaylist::playbackMode(), Qmmp::Playing, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOrder, position(), positionChanged(), MusicObject::PS_StoppedState, MusicPlaylist::setCurrentIndex(), setEnaleEffect(), SoundCore::setVolume(), state(), SoundCore::state(), stateChanged(), and SoundCore::stop().
Referenced by MusicPlayer().
int MusicPlayer::volume () const
Get current player volume.
Definition at line 83 of file musicplayer.cpp.
References isMuted(), m_music, and SoundCore::volume().
Referenced by MusicApplication::musicActionVolumePlus(), MusicApplication::musicActionVolumeSub(), MusicApplication::musicVolumeMute(), play(), setMusicEnhanced(), and setVolume().
void MusicPlayer::volumeChanged (int volume) signal
Current volume changed.
Member Data Documentation
int MusicPlayer::m_balance protected
Definition at line 197 of file musicplayer.h.
Referenced by MusicPlayer(), setMusicEnhanced(), and setSoundEffectVolume().
QString MusicPlayer::m_currentMedia protected
Definition at line 192 of file musicplayer.h.
Referenced by play().
qint64 MusicPlayer::m_duration protected
Definition at line 194 of file musicplayer.h.
Referenced by getCurrentDuration(), and MusicPlayer().
SoundCore* MusicPlayer::m_music protected
Definition at line 190 of file musicplayer.h.
Referenced by duration(), isMuted(), MusicPlayer(), pause(), play(), position(), removeCurrentMedia(), setEqEffect(), setMusicEnhanced(), setMuted(), setPosition(), setSoundEffectVolume(), setVolume(), stop(), update(), volume(), and ~MusicPlayer().
Enhanced MusicPlayer::m_musicEnhanced protected
Definition at line 193 of file musicplayer.h.
Referenced by getMusicEnhanced(), MusicPlayer(), setMusicEnhanced(), setMusicEnhancedCase(), and update().
MusicPlaylist* MusicPlayer::m_playlist protected
Definition at line 188 of file musicplayer.h.
Referenced by MusicPlayer(), play(), playlist(), playNext(), playPrevious(), setPlaylist(), and update().
float MusicPlayer::m_posOnCircle protected
Definition at line 198 of file musicplayer.h.
Referenced by MusicPlayer(), and update().
MusicObject::PlayState MusicPlayer::m_state protected
Definition at line 189 of file musicplayer.h.
Referenced by isPlaying(), MusicPlayer(), pause(), play(), state(), and stop().
QTimer MusicPlayer::m_timer protected
Definition at line 191 of file musicplayer.h.
Referenced by MusicPlayer(), pause(), play(), removeCurrentMedia(), stop(), and update().
int MusicPlayer::m_tryTimes protected
Definition at line 196 of file musicplayer.h.
Referenced by getCurrentDuration(), MusicPlayer(), and play().
int MusicPlayer::m_volumeMusic3D protected
Definition at line 197 of file musicplayer.h.
Referenced by MusicPlayer(), setMusicEnhanced(), setMuted(), and setVolume().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicplayer.h
TTKModule/TTKCore/musicCoreKits/musicplayer.cpp