TTKMusicPlayer: MusicToplistQueryCategoryItem Class Reference
MusicToplistQueryCategoryItem Class Reference
The class of the toplist music query category item.
#include <musictoplistquerycategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicResultsCategoryItem &category)
Public Member Functions
MusicToplistQueryCategoryItem (QWidget *parent=nullptr)
void setCategory (const MusicResultsCategory &category)
Private Attributes
MusicResultsCategory m_category
Detailed Description
The class of the toplist music query category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musictoplistquerycategorypopwidget.h.
Constructor & Destructor Documentation
MusicToplistQueryCategoryItem::MusicToplistQueryCategoryItem (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 10 of file musictoplistquerycategorypopwidget.cpp.
Member Function Documentation
void MusicToplistQueryCategoryItem::buttonClicked (int index) slot
Current category item clicked.
Definition at line 48 of file musictoplistquerycategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicResultsCategory::m_items.
Referenced by setCategory().
void MusicToplistQueryCategoryItem::categoryChanged (const MusicResultsCategoryItem & category) signal
Current category changed.
Referenced by buttonClicked().
void MusicToplistQueryCategoryItem::setCategory (const MusicResultsCategory & category)
Set current category.
Definition at line 16 of file musictoplistquerycategorypopwidget.cpp.
References buttonClicked(), TTK::UI::ColorStyle03, TTK::UI::ColorStyle07, TTK::UI::FontStyle03, ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicResultsCategory::m_category, m_category, MusicResultsCategory::m_items, and TTKClickedGroup::mapped().
Referenced by MusicToplistQueryCategoryPopWidget::setCategory().
Member Data Documentation
MusicResultsCategory MusicToplistQueryCategoryItem::m_category private
Definition at line 56 of file musictoplistquerycategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musictoplistquerycategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musictoplistquerycategorypopwidget.cpp