TTKMusicplayer: QDesWrapperPrivate Class Reference
QDesWrapperPrivate Class Reference
The class of the des wrapper private.
Public Member Functions
qint64 bitTransform (int *array, int len, qint64 source)
void DESSubKeys (qint64 key, qint64 *K, QDesWrapper::Mode mode)
qint64 DES64 (qint64 *subkeys, qint64 data)
char * encrypt (char *src, int srcLength, char *key)
Public Member Functions inherited from TTKPrivate< QDesWrapper >
TTKPrivate ()
virtual ~TTKPrivate ()
void setPublic (QDesWrapper *pub)
Public Attributes
QDesWrapper::Mode m_mode
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QDesWrapper >
QDesWrapper * ttk_q () const
Detailed Description
The class of the des wrapper private.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 176 of file qdeswrapper.cpp.
Member Function Documentation
qint64 QDesWrapperPrivate::bitTransform (int * array, int len, qint64 source)
Definition at line 187 of file qdeswrapper.cpp.
References ARRAYMASK.
Referenced by DES64(), and DESSubKeys().
qint64 QDesWrapperPrivate::DES64 (qint64 * subkeys, qint64 data)
Definition at line 224 of file qdeswrapper.cpp.
References ARRAYE, ARRAYIP, ARRAYIP_1, ARRAYP, bitTransform(), int(), and MATRIXNSBOX.
Referenced by encrypt().
void QDesWrapperPrivate::DESSubKeys (qint64 key, qint64 * K, QDesWrapper::Mode mode)
Definition at line 202 of file qdeswrapper.cpp.
References ARRAYLS, ARRAYLSMASK, ARRAYPC_1, ARRAYPC_2, bitTransform(), and QDesWrapper::DECRYPT.
Referenced by encrypt().
char * QDesWrapperPrivate::encrypt (char * src, int srcLength, char * key)
Definition at line 273 of file qdeswrapper.cpp.
References DES64(), DESSubKeys(), and m_mode.
Member Data Documentation
QDesWrapper::Mode QDesWrapperPrivate::m_mode
Definition at line 184 of file qdeswrapper.cpp.
Referenced by encrypt().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qalgorithm/qdeswrapper.cpp