TTKMusicplayer: MusicDownloadTagDataRequest Class Reference
MusicDownloadTagDataRequest Class Reference
The class of downloading the type of data by custom tags.
#include <musicdownloadtagdatarequest.h>
Public Slots
virtual void downLoadFinished () override
void downLoadFinished (const QByteArray &bytes)
Public Slots inherited from MusicDownloadDataRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal) override
virtual void updateDownloadSpeed () override
void handleReadyRead ()
Public Slots inherited from MusicAbstractDownLoadRequest
virtual void downLoadFinished () override
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void finished ()
Signals inherited from MusicDownloadDataRequest
void downloadUrlChanged (const QString &url)
void downloadSpeedLabelChanged (const QString &speed, qint64 timeLeft)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Public Member Functions
MusicDownloadTagDataRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
void setSongMeta (MusicSongMeta &meta)
virtual void startToDownload () override
Public Member Functions inherited from MusicDownloadDataRequest
MusicDownloadDataRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
void setRecordType (MusicObject::RecordType type)
Public Member Functions inherited from MusicAbstractDownLoadRequest
MusicAbstractDownLoadRequest (const QString &url, const QString &save, MusicObject::DownloadType type, QObject *parent=nullptr)
~MusicAbstractDownLoadRequest ()
virtual void deleteAll () override
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Attributes
MusicSongMeta m_musicMeta
Protected Attributes inherited from MusicDownloadDataRequest
qint64 m_createItemTime
bool m_redirection
bool m_needUpdate
MusicObject::RecordType m_recordType
Protected Attributes inherited from MusicAbstractDownLoadRequest
QFile * m_file
QString m_url
QString m_savePath
MusicObject::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_speedTimer
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Protected Member Functions inherited from MusicDownloadDataRequest
void startRequest (const QUrl &url)
Protected Member Functions inherited from MusicAbstractDownLoadRequest
QString mapCurrentQueryData () const
Detailed Description
The class of downloading the type of data by custom tags.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadtagdatarequest.h.
Constructor & Destructor Documentation
MusicDownloadTagDataRequest::MusicDownloadTagDataRequest (const QString & url, const QString & save, MusicObject::DownloadType type, QObject * parent = nullptr)
Object contsructor provide download URL\ save local path and download type.
Definition at line 7 of file musicdownloadtagdatarequest.cpp.
References MusicDownloadDataRequest::m_needUpdate.
Member Function Documentation
void MusicDownloadTagDataRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 37 of file musicdownloadtagdatarequest.cpp.
References MusicAbstractNetwork::downLoadDataChanged(), MusicDownloadDataRequest::downLoadFinished(), MusicAbstractNetwork::downLoadRawDataChanged(), MusicSemaphoreLoop::exec(), finished(), MusicSongMeta::getComment(), MusicAbstractDownLoadRequest::m_file, m_musicMeta, MusicDownloadDataRequest::m_redirection, MusicAbstractDownLoadRequest::mapCurrentQueryData(), MusicDownloadSourceRequest::startToDownload(), and TTK_LOGGER_INFO.
Referenced by startToDownload().
void MusicDownloadTagDataRequest::downLoadFinished (const QByteArray & bytes) slot
Send download byte data from net.
Definition at line 61 of file musicdownloadtagdatarequest.cpp.
References finished(), G_SETTING_PTR, MusicSongMeta::getAlbum(), MusicSongMeta::getArtist(), MusicSongMeta::getTitle(), MusicSongMeta::getTrackNum(), MusicSongMeta::getYear(), m_musicMeta, MusicAbstractDownLoadRequest::m_savePath, MusicSettingManager::OtherWriteAlbumCover, MusicSettingManager::OtherWriteFileInfo, MusicSongMeta::read(), MusicSongMeta::save(), MusicSongMeta::setAlbum(), MusicSongMeta::setArtist(), MusicSongMeta::setCover(), MusicSongMeta::setTitle(), MusicSongMeta::setTrackNum(), MusicSongMeta::setYear(), TTK_LOGGER_ERROR, and TTK_LOGGER_INFO.
void MusicDownloadTagDataRequest::finished () signal
Modify tag finished.
Referenced by downLoadFinished(), and startToDownload().
void MusicDownloadTagDataRequest::setSongMeta (MusicSongMeta & meta)
Set custom tags.
Definition at line 13 of file musicdownloadtagdatarequest.cpp.
References m_musicMeta.
Referenced by MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
void MusicDownloadTagDataRequest::startToDownload () override virtual
Start to download data.
Reimplemented from MusicDownloadDataRequest.
Definition at line 18 of file musicdownloadtagdatarequest.cpp.
References MusicAbstractDownLoadRequest::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), downLoadFinished(), finished(), MusicAbstractDownLoadRequest::m_file, MusicAbstractNetwork::m_reply, MusicAbstractDownLoadRequest::m_url, MusicDownloadDataRequest::startRequest(), and TTK_LOGGER_ERROR.
Referenced by MusicDownloadBatchTableItem::startToDownloadMusic(), and MusicDownloadWidget::startToDownloadMusic().
Member Data Documentation
MusicSongMeta MusicDownloadTagDataRequest::m_musicMeta protected
Definition at line 64 of file musicdownloadtagdatarequest.h.
Referenced by downLoadFinished(), and setSongMeta().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadtagdatarequest.h
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadtagdatarequest.cpp