TTKMusicplayer: MusicUtils::Image Namespace Reference
MusicUtils::Image Namespace Reference
Functions
MUSIC_UTILS_EXPORT QPixmap pixmapToRound (const QPixmap &src, int ratioX, int ratioY)
MUSIC_UTILS_EXPORT QPixmap pixmapToRound (const QPixmap &src, const QSize &size, int ratioX, int ratioY)
MUSIC_UTILS_EXPORT QPixmap pixmapToRound (const QPixmap &src, const QRect &rect, int ratioX, int ratioY)
MUSIC_UTILS_EXPORT QPixmap pixmapToRound (const QPixmap &src, const QPixmap &mask, const QSize &size)
MUSIC_UTILS_EXPORT QBitmap getBitmapMask (const QRect &rect, int ratioX, int ratioY)
MUSIC_UTILS_EXPORT QByteArray getPixmapData (const QPixmap &pix)
MUSIC_UTILS_EXPORT void fusionPixmap (QPixmap &back, const QPixmap &front, const QPoint &pt)
MUSIC_UTILS_EXPORT QPixmap grayScalePixmap (const QPixmap &src, int radius=0)
MUSIC_UTILS_EXPORT QImage gaussPixmap (const QImage &image, int radius)
MUSIC_UTILS_EXPORT void gaussPixmap (QImage &image, int radius)
template<typename T >
MUSIC_UTILS_EXPORT T reRenderValue (const T &key, const T &alpha, const T &value)
MUSIC_UTILS_EXPORT int reRenderAlpha (int alpha, int value)
MUSIC_UTILS_EXPORT void reRenderImage (int delta, const QImage *input, QImage *output)
MUSIC_UTILS_EXPORT int colorBurnTransform (int c, int delta)
Function Documentation
int MusicUtils::Image::colorBurnTransform (int c, int delta)
Image color burn transform.
Definition at line 242 of file musicimageutils.cpp.
Referenced by reRenderImage().
void MusicUtils::Image::fusionPixmap (QPixmap & back, const QPixmap & front, const QPoint & pt)
Set fusion two image.
Definition at line 183 of file musicimageutils.cpp.
Referenced by MusicScreenSaverBackgroundWidget::backgroundTimeout(), MusicArtistAlbumsItemWidget::downLoadFinished(), MusicWebDJRadioFoundItemWidget::downLoadFinished(), MusicWebMVRadioFoundItemWidget::downLoadFinished(), MusicPlaylistFoundItemWidget::downLoadFinished(), and MusicFoundAbstractWidget::downLoadFinished().
QImage MusicUtils::Image::gaussPixmap (const QImage & image, int radius)
Image gauss filter.
Definition at line 211 of file musicimageutils.cpp.
Referenced by MusicLrcPosterItemWidget::drawTheme10().
void MusicUtils::Image::gaussPixmap (QImage & image, int radius)
Image gauss filter.
Definition at line 218 of file musicimageutils.cpp.
References GaussianBlur::gaussBlur().
QBitmap MusicUtils::Image::getBitmapMask (const QRect & rect, int ratioX, int ratioY)
Get bitmap mask from rect.
Definition at line 155 of file musicimageutils.cpp.
Referenced by pixmapToRound(), and MusicUtils::Widget::widgetToRound().
QByteArray MusicUtils::Image::getPixmapData (const QPixmap & pix)
Get pximap data.
Definition at line 166 of file musicimageutils.cpp.
References JPG_FILE_PREFIX.
Referenced by MusicExtractWrap::inputSkin().
QPixmap MusicUtils::Image::grayScalePixmap (const QPixmap & src, int radius = 0)
Set fusion two image.
Definition at line 195 of file musicimageutils.cpp.
Referenced by MusicScreenSaverHoverItem::caseButtonOnAndOff().
QPixmap MusicUtils::Image::pixmapToRound (const QPixmap & src, int ratioX, int ratioY)
Set pixmap to round by ratio.
Definition at line 117 of file musicimageutils.cpp.
Referenced by MusicSpectrumLayoutItem::addItem(), MusicWebMusicRadioWidget::addListWidgetItem(), MusicWebMusicRadioWidget::downLoadFinished(), MusicLrcPosterItemWidget::drawTheme6(), MusicWebMusicRadioPlayWidget::picDownloadStateChanged(), pixmapToRound(), and MusicUserWindow::userStateChanged().
QPixmap MusicUtils::Image::pixmapToRound (const QPixmap & src, const QSize & size, int ratioX, int ratioY)
Set pixmap to round by ratio.
Definition at line 122 of file musicimageutils.cpp.
References pixmapToRound().
QPixmap MusicUtils::Image::pixmapToRound (const QPixmap & src, const QRect & rect, int ratioX, int ratioY)
Set pixmap to round by ratio.
Definition at line 127 of file musicimageutils.cpp.
References getBitmapMask().
QPixmap MusicUtils::Image::pixmapToRound (const QPixmap & src, const QPixmap & mask, const QSize & size)
Set pixmap to round by ratio.
Definition at line 139 of file musicimageutils.cpp.
int MusicUtils::Image::reRenderAlpha (int alpha, int value)
Rerender the image alpha.
Definition at line 223 of file musicimageutils.cpp.
void MusicUtils::Image::reRenderImage (int delta, const QImage * input, QImage * output)
Rerender the image by color burn transform.
Definition at line 228 of file musicimageutils.cpp.
References colorBurnTransform().
Referenced by MusicTopAreaWidget::drawWindowBackgroundRect().
template<typename T > MUSIC_UTILS_EXPORT T MusicUtils::Image::reRenderValue (const T & key, const T & alpha, const T & value)
Rerender the custum value.
Definition at line 78 of file musicimageutils.h.
References key.