TTKMusicPlayer: MusicColorDialog Class Reference
MusicColorDialog Class Reference
The class of the get color table widget.
#include <musiccolordialog.h>
Public Slots
void buttonClicked (int index)
void colorChanged (const QColor &color)
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Public Member Functions
MusicColorDialog (QWidget *parent=nullptr)
~MusicColorDialog ()
QColor color () const
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QColor popup (QWidget *parent=nullptr)
Private Attributes
Ui::MusicColorDialog * m_ui
QColor m_color
Additional Inherited Members
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Detailed Description
The class of the get color table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 135 of file musiccolordialog.h.
Constructor & Destructor Documentation
MusicColorDialog::MusicColorDialog (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 233 of file musiccolordialog.cpp.
References buttonClicked(), colorChanged(), m_ui, MusicUIObject::PushButtonStyle04, QtButtonGroupConnect, MusicWidgetRenderer::setBackgroundLabel(), and MusicUIObject::ToolButtonStyle04.
MusicColorDialog::~MusicColorDialog ()
Definition at line 270 of file musiccolordialog.cpp.
References m_ui.
Member Function Documentation
void MusicColorDialog::buttonClicked (int index) slot
Confirm or cancal button clicked, set the state.
Definition at line 286 of file musiccolordialog.cpp.
Referenced by MusicColorDialog().
QColor MusicColorDialog::color () const
Get color.
Definition at line 281 of file musiccolordialog.cpp.
References m_color.
Referenced by MusicLrcColorWidget::addButtonClicked(), colorChanged(), MusicLrcColorWidget::modifyButtonClicked(), popup(), and MusicSettingWidget::rippleSpectrumColorChanged().
void MusicColorDialog::colorChanged (const QColor & color) slot
Current color has changed.
Definition at line 297 of file musiccolordialog.cpp.
References color(), and m_color.
Referenced by MusicColorDialog().
QColor MusicColorDialog::popup (QWidget * parent = nullptr) static
Get color static function.
Definition at line 275 of file musiccolordialog.cpp.
References color(), and MusicAbstractMoveDialog::exec().
Referenced by ToolsSkin::paletteClicked(), and MusicBackgroundPaletteWidget::showPaletteDialog().
Member Data Documentation
QColor MusicColorDialog::m_color private
Definition at line 167 of file musiccolordialog.h.
Referenced by color(), and colorChanged().
Ui::MusicColorDialog* MusicColorDialog::m_ui private
Definition at line 166 of file musiccolordialog.h.
Referenced by MusicColorDialog(), and ~MusicColorDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musiccolordialog.h
TTKModule/TTKWidget/musicCoreKits/musiccolordialog.cpp