TTKMusicplayer: TTKThirdParty/Zlib/ttkzip/ioapi.c File Reference
ioapi.c File Reference
#include "ioapi.h"
Macros
#define FOPEN_FUNC(filename, mode) fopen64(filename, mode)
#define FTELLO_FUNC(stream) ftello64(stream)
#define FSEEKO_FUNC(stream, offset, origin) fseeko64(stream, offset, origin)
Functions
voidpf call_zopen64 (const zlib_filefunc64_32_def *pfilefunc, const void *filename, int mode)
long call_zseek64 (const zlib_filefunc64_32_def *pfilefunc, voidpf filestream, ZPOS64_T offset, int origin)
ZPOS64_T call_ztell64 (const zlib_filefunc64_32_def *pfilefunc, voidpf filestream)
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def *p_filefunc64_32, const zlib_filefunc_def *p_filefunc32)
static voidpf ZCALLBACK fopen_file_func OF ((voidpf opaque, const char *filename, int mode))
static uLong ZCALLBACK fread_file_func OF ((voidpf opaque, voidpf stream, void *buf, uLong size))
static uLong ZCALLBACK fwrite_file_func OF ((voidpf opaque, voidpf stream, const void *buf, uLong size))
static ZPOS64_T ZCALLBACK ftell64_file_func OF ((voidpf opaque, voidpf stream))
static long ZCALLBACK fseek64_file_func OF ((voidpf opaque, voidpf stream, ZPOS64_T offset, int origin))
static voidpf ZCALLBACK fopen_file_func (voidpf opaque, const char *filename, int mode)
static voidpf ZCALLBACK fopen64_file_func (voidpf opaque, const void *filename, int mode)
static uLong ZCALLBACK fread_file_func (voidpf opaque, voidpf stream, void *buf, uLong size)
static uLong ZCALLBACK fwrite_file_func (voidpf opaque, voidpf stream, const void *buf, uLong size)
static long ZCALLBACK ftell_file_func (voidpf opaque, voidpf stream)
static ZPOS64_T ZCALLBACK ftell64_file_func (voidpf opaque, voidpf stream)
static long ZCALLBACK fseek_file_func (voidpf opaque, voidpf stream, uLong offset, int origin)
static long ZCALLBACK fseek64_file_func (voidpf opaque, voidpf stream, ZPOS64_T offset, int origin)
static int ZCALLBACK fclose_file_func (voidpf opaque, voidpf stream)
static int ZCALLBACK ferror_file_func (voidpf opaque, voidpf stream)
void fill_fopen_filefunc (zlib_filefunc_def *pzlib_filefunc_def)
void fill_fopen64_filefunc (zlib_filefunc64_def *pzlib_filefunc_def)
Macro Definition Documentation
#define FOPEN_FUNC (filename, mode) fopen64(filename, mode)
Definition at line 23 of file ioapi.c.
Referenced by fopen64_file_func().
#define FSEEKO_FUNC (stream, offset, origin) fseeko64(stream, offset, origin)
Definition at line 25 of file ioapi.c.
Referenced by fseek64_file_func().
#define FTELLO_FUNC (stream) ftello64(stream)
Definition at line 24 of file ioapi.c.
Referenced by ftell64_file_func().
Function Documentation
voidpf call_zopen64 (const zlib_filefunc64_32_def * pfilefunc, const void * filename, int mode)
Definition at line 31 of file ioapi.c.
References zlib_filefunc64_def_s::opaque, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, and zlib_filefunc64_def_s::zopen64_file.
long call_zseek64 (const zlib_filefunc64_32_def * pfilefunc, voidpf filestream, ZPOS64_T offset, int origin)
Definition at line 41 of file ioapi.c.
References zlib_filefunc64_def_s::opaque, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zseek32_file, and zlib_filefunc64_def_s::zseek64_file.
ZPOS64_T call_ztell64 (const zlib_filefunc64_32_def * pfilefunc, voidpf filestream)
Definition at line 55 of file ioapi.c.
References MAXU32, zlib_filefunc64_def_s::opaque, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_32_def_s::ztell32_file, and zlib_filefunc64_def_s::ztell64_file.
static int ZCALLBACK fclose_file_func (voidpf opaque, voidpf stream) static
Definition at line 210 of file ioapi.c.
Referenced by fill_fopen64_filefunc(), and fill_fopen_filefunc().
static int ZCALLBACK ferror_file_func (voidpf opaque, voidpf stream) static
Definition at line 217 of file ioapi.c.
Referenced by fill_fopen64_filefunc(), and fill_fopen_filefunc().
void fill_fopen64_filefunc (zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 237 of file ioapi.c.
References fclose_file_func(), ferror_file_func(), fopen64_file_func(), fread_file_func(), fseek64_file_func(), ftell64_file_func(), fwrite_file_func(), zlib_filefunc64_def_s::opaque, zlib_filefunc64_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_def_s::ztell64_file, and zlib_filefunc64_def_s::zwrite_file.
Referenced by unzOpenInternal(), and zipOpen3().
void fill_fopen_filefunc (zlib_filefunc_def* pzlib_filefunc_def)
Definition at line 224 of file ioapi.c.
References fclose_file_func(), ferror_file_func(), fopen_file_func(), fread_file_func(), fseek_file_func(), ftell_file_func(), fwrite_file_func(), and zlib_filefunc_def_s::zopen_file.
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def * p_filefunc64_32, const zlib_filefunc_def * p_filefunc32)
Definition at line 69 of file ioapi.c.
References zlib_filefunc_def_s::opaque, zlib_filefunc64_def_s::opaque, zlib_filefunc_def_s::zclose_file, zlib_filefunc64_def_s::zclose_file, zlib_filefunc_def_s::zerror_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc_def_s::zopen_file, zlib_filefunc_def_s::zread_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_32_def_s::zseek32_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc_def_s::zseek_file, zlib_filefunc64_32_def_s::ztell32_file, zlib_filefunc64_def_s::ztell64_file, zlib_filefunc_def_s::ztell_file, zlib_filefunc_def_s::zwrite_file, and zlib_filefunc64_def_s::zwrite_file.
Referenced by unzOpen2(), and zipOpen2().
static voidpf ZCALLBACK fopen64_file_func (voidpf opaque, const void * filename, int mode) static
Definition at line 113 of file ioapi.c.
References FOPEN_FUNC, ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, and ZLIB_FILEFUNC_MODE_READWRITEFILTER.
Referenced by fill_fopen64_filefunc().
static voidpf ZCALLBACK fopen_file_func (voidpf opaque, const char * filename, int mode) static
Definition at line 95 of file ioapi.c.
References ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, and ZLIB_FILEFUNC_MODE_READWRITEFILTER.
Referenced by fill_fopen_filefunc().
static uLong ZCALLBACK fread_file_func (voidpf opaque, voidpf stream, void * buf, uLong size) static
Definition at line 132 of file ioapi.c.
Referenced by fill_fopen64_filefunc(), and fill_fopen_filefunc().
static long ZCALLBACK fseek64_file_func (voidpf opaque, voidpf stream, ZPOS64_T offset, int origin) static
Definition at line 184 of file ioapi.c.
References FSEEKO_FUNC, SEEK_CUR, SEEK_END, SEEK_SET, ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_fopen64_filefunc().
static long ZCALLBACK fseek_file_func (voidpf opaque, voidpf stream, uLong offset, int origin) static
Definition at line 161 of file ioapi.c.
References SEEK_CUR, SEEK_END, SEEK_SET, ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_fopen_filefunc().
static ZPOS64_T ZCALLBACK ftell64_file_func (voidpf opaque, voidpf stream) static
Definition at line 154 of file ioapi.c.
References FTELLO_FUNC.
Referenced by fill_fopen64_filefunc().
static long ZCALLBACK ftell_file_func (voidpf opaque, voidpf stream) static
Definition at line 146 of file ioapi.c.
Referenced by fill_fopen_filefunc().
static uLong ZCALLBACK fwrite_file_func (voidpf opaque, voidpf stream, const void * buf, uLong size) static
Definition at line 139 of file ioapi.c.
Referenced by fill_fopen64_filefunc(), and fill_fopen_filefunc().
static voidpf ZCALLBACK fopen_file_func OF ((voidpf opaque, const char *filename, int mode)) static
static uLong ZCALLBACK fread_file_func OF ((voidpf opaque, voidpf stream, void *buf, uLong size)) static
static uLong ZCALLBACK fwrite_file_func OF ((voidpf opaque, voidpf stream, const void *buf, uLong size)) static
static ZPOS64_T ZCALLBACK ftell64_file_func OF ((voidpf opaque, voidpf stream)) static
static long ZCALLBACK fseek64_file_func OF ((voidpf opaque, voidpf stream, ZPOS64_T offset, int origin)) static