TTKMusicplayer: MusicUtils::Core Namespace Reference
MusicUtils::Core Namespace Reference
Functions
MUSIC_UTILS_EXPORT QString lrcPrefix ()
qmmp incldue
MUSIC_UTILS_EXPORT QString musicPrefix ()
MUSIC_UTILS_EXPORT QString fileSuffix (const QString &name)
MUSIC_UTILS_EXPORT quint64 dirSize (const QString &dirName)
MUSIC_UTILS_EXPORT void checkCacheSize (quint64 cacheSize, bool disabled, const QString &path)
MUSIC_UTILS_EXPORT QFileInfoList findFile (const QString &path, const QStringList &filter)
MUSIC_UTILS_EXPORT QString getLanguageName (int index)
MUSIC_UTILS_EXPORT bool removeRecursively (const QString &dir)
MUSIC_UTILS_EXPORT bool openUrl (const QString &exe, const QString &path)
MUSIC_UTILS_EXPORT bool openUrl (const QString &path, bool local=true)
MUSIC_UTILS_EXPORT QString toUnicode (const char *chars, const char *format="GBK")
MUSIC_UTILS_EXPORT QString toUnicode (const QByteArray &chars, const char *format="GBK")
MUSIC_UTILS_EXPORT QByteArray fromUnicode (const QString &chars, const char *format="GBK")
MUSIC_UTILS_EXPORT void setLocalCodec (const char *format="utf-8")
MUSIC_UTILS_EXPORT const char * toLocal8Bit (const QString &str)
MUSIC_UTILS_EXPORT const char * toUtf8 (const QString &str)
MUSIC_UTILS_EXPORT QString pluginPath (const QString &module, const QString &format)
MUSIC_UTILS_EXPORT void midTransferFile ()
MUSIC_UTILS_EXPORT bool musicVersionCheck (const QStringList &ol, const QStringList &dl, int depth)
MUSIC_UTILS_EXPORT bool musicVersionCheck (const QString &o, const QString &d)
Function Documentation
void MusicUtils::Core::checkCacheSize (quint64 cacheSize, bool disabled, const QString & path)
Check given dir size is bigger than given size.
Definition at line 80 of file musiccoreutils.cpp.
References dirSize().
Referenced by MusicRunTimeManager::run().
quint64 MusicUtils::Core::dirSize (const QString & dirName)
Get given dir size.
Definition at line 57 of file musiccoreutils.cpp.
Referenced by checkCacheSize().
QString MusicUtils::Core::fileSuffix (const QString & name)
Get file suffix path.
Definition at line 52 of file musiccoreutils.cpp.
Referenced by MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadWSInterface::readFromMusicSongAttribute(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), and MusicXMTextDownLoadThread::startToDownload().
QFileInfoList MusicUtils::Core::findFile (const QString & path, const QStringList & filter)
To find file by dir path.
Find the corresponding suffix name
Definition at line 101 of file musiccoreutils.cpp.
Referenced by MusicLocalSongsManagerThread::run(), MusicCloudSharedSongTableWidget::uploadFilesToServer(), and MusicDesktopWallpaperWidget::viewButtonPressed().
QByteArray MusicUtils::Core::fromUnicode (const QString & chars, const char * format = "GBK")
Set string from unicode string by format.
Definition at line 228 of file musiccoreutils.cpp.
QString MusicUtils::Core::getLanguageName (int index)
Get Language Name by given index.
Definition at line 120 of file musiccoreutils.cpp.
References LANGUAGE_DIR_FULL.
Referenced by MusicRunTimeManager::translator().
QString MusicUtils::Core::lrcPrefix ()
qmmp incldue
Get lrc dir prefix path.
Definition at line 18 of file musiccoreutils.cpp.
References MusicSettingManager::DownloadLrcPathDirChoiced, LRC_DIR_FULL, and M_SETTING_PTR.
Referenced by MusicLrcLocalLinkWidget::confirmButtonClicked(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicRadioSongsThread::downLoadFinished(), MusicWebMusicRadioWidget::lrcDownloadStateChanged(), MusicDownloadStatusObject::musicCheckHasLrcAlready(), MusicApplication::musicCurrentLrcUpdated(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicDownloadStatusObject::musicHaveNoLrcAlready(), MusicApplication::musicLoadCurrentSongLrc(), MusicSysConfigManager::readSysLoadConfig(), MusicLrcLocalLinkWidget::searchInLocalMLrc(), MusicLrcMakerWidget::setCurrentSongName(), and MusicWebMusicRadioWidget::startToPlay().
void MusicUtils::Core::midTransferFile ()
Mid config file transfer operator.
Definition at line 265 of file musiccoreutils.cpp.
References Qmmp::configFile(), and MAKE_CONFIG_DIR_FULL.
Referenced by MusicRunTimeManager::run().
QString MusicUtils::Core::musicPrefix ()
Get music dir prefix path.
Definition at line 35 of file musiccoreutils.cpp.
References MusicSettingManager::DownloadMusicPathDirChoiced, M_SETTING_PTR, and MUSIC_DIR_FULL.
Referenced by MusicDownloadRecordWidget::createDownloadItem(), MusicCloudDownloadTableWidget::createDownloadItem(), MusicCloudSharedSongTableWidget::downloadFileToServer(), and MusicSysConfigManager::readSysLoadConfig().
bool MusicUtils::Core::musicVersionCheck (const QStringList & ol, const QStringList & dl, int depth)
Music version check.
Definition at line 289 of file musiccoreutils.cpp.
Referenced by MusicSourceUpdateNotifyWidget::downLoadFinished(), MusicSourceUpdateWidget::downLoadFinished(), and musicVersionCheck().
bool MusicUtils::Core::musicVersionCheck (const QString & o, const QString & d)
Music version check.
Definition at line 313 of file musiccoreutils.cpp.
References musicVersionCheck().
bool MusicUtils::Core::openUrl (const QString & exe, const QString & path)
Open file from local by path or net url.
Definition at line 183 of file musiccoreutils.cpp.
Referenced by MusicSongSharingWidget::downLoadDataChanged(), MusicSourceUpdateWidget::downloadProgressFinished(), MusicLrcContainerForInline::lrcOpenFileDir(), MusicApplicationObject::musicBugReportView(), MusicFileInformationWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicDownloadResetWidget::openFileLocation(), openUrl(), and MusicSourceUpdateWidget::upgradeFailedClicked().
bool MusicUtils::Core::openUrl (const QString & path, bool local = true)
Open file from local by path or net url.
Definition at line 194 of file musiccoreutils.cpp.
References openUrl(), and toLocal8Bit().
QString MusicUtils::Core::pluginPath (const QString & module, const QString & format)
Get qmmp plugin dir path.
Definition at line 254 of file musiccoreutils.cpp.
References MusicObject::getAppDir().
Referenced by MusicSongTag::findPluginPath(), and MusicSpectrumWidget::newSpekWidget().
bool MusicUtils::Core::removeRecursively (const QString & dir)
Dir remove recursively.
Definition at line 132 of file musiccoreutils.cpp.
Referenced by MusicApplicationObject::cleanUp().
void MusicUtils::Core::setLocalCodec (const char * format = "utf-8")
Set local codec by format.
Definition at line 234 of file musiccoreutils.cpp.
Referenced by MusicRunTimeManager::run().
const char * MusicUtils::Core::toLocal8Bit (const QString & str)
Trasform string to local 8bit char.
Definition at line 244 of file musiccoreutils.cpp.
Referenced by MusicAudioRecorderCore::addWavHeader(), MusicLrcFromKrc::decode(), MusicExtractWrap::inputSkin(), MusicAudioRecorderWidget::onRecordSave(), openUrl(), and MusicSoundKMicroWidget::playFinished().
QString MusicUtils::Core::toUnicode (const char * chars, const char * format = "GBK")
Set string to unicode string by format.
Definition at line 216 of file musiccoreutils.cpp.
QString MusicUtils::Core::toUnicode (const QByteArray & chars, const char * format = "GBK")
Set string to unicode string by format.
Definition at line 222 of file musiccoreutils.cpp.
const char * MusicUtils::Core::toUtf8 (const QString & str)
Trasform string to utf8 char.
Definition at line 249 of file musiccoreutils.cpp.
Referenced by QAesWrap::decrypt(), MusicQQTextDownLoadThread::downLoadFinished(), MusicQQBackgroundThread::downLoadUrl(), MusicKWArtistSimilarThread::getArtistIdName(), MusicMGArtistSimilarThread::getArtistInfo(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryWSArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicDownLoadQueryWSPlaylistThread::getMoreDetails(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQQInterface::getMusicKey(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryMGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicWSDiscoverListThread::getUpdateTime(), MusicDownLoadQueryWSToplistThread::getUpdateTime(), MusicDownLoadWYInterface::makeTokenQueryQequest(), MusicDownLoadMGInterface::makeTokenQueryUrl(), MusicDownLoadBDInterface::makeTokenQueryUrl(), MusicDownLoadXMInterface::makeTokenQueryUrl(), MusicDownLoadKWInterface::readFromMusicLLAttribute(), MusicDownLoadBDInterface::readFromMusicLLAttribute(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadBDInterface::readFromMusicPayAttribute(), MusicDownLoadKGInterface::readFromMusicSongAlbumInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadWSInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongAttribute(), MusicDownLoadKGInterface::readFromMusicSongLrcAndPic(), MusicDownLoadKWInterface::readFromMusicSongPic(), MusicCoreMPlayer::setLeftVolume(), MusicCoreMPlayer::setMultiVoice(), MusicCoreMPlayer::setMute(), MusicCoreMPlayer::setPosition(), MusicCoreMPlayer::setRightVolume(), MusicCoreMPlayer::setVolume(), MusicQQTextDownLoadThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicWSSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicMGSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicDownLoadQueryMGMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryWSPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryMGPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicMGPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicWSPlaylistCommentsThread::startToPage(), MusicDownLoadQueryYYTThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicWSDiscoverListThread::startToSearch(), MusicMGDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicWSSongSuggestThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicMGArtistSimilarThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicMGSongSuggestThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryWSThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryWYThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryMGMovieThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryMGThread::startToSearch(), MusicDownLoadQueryQQThread::startToSearch(), MusicDownLoadQueryBDThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryWSRecommendThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryMGArtistThread::startToSearch(), MusicDownLoadQueryMGAlbumThread::startToSearch(), MusicDownLoadQueryMGRecommendThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryWSArtistThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicDownLoadQueryKGThread::startToSearch(), MusicDownLoadQueryWSToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryMGToplistThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryWSPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryMGPlaylistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryKWThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryMGThread::startToSingleSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryMGAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryKWThread::startToSingleSearch(), and MusicCryptographicHash::xxteaEncrypt().