TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/rsecc.h File Reference
rsecc.h File Reference
#include "global.h"
Functions
EXTRAS_EXPORT int RSECC_encode (size_t data_length, size_t ecc_length, const unsigned char *data, unsigned char *ecc)
Function Documentation
EXTRAS_EXPORT int RSECC_encode (size_t data_length, size_t ecc_length, const unsigned char * data, unsigned char * ecc)
Definition at line 103 of file rsecc.c.
References aindex, alpha, generator, generator_init(), generatorInitialized, initialized, int(), max_length, min_length, RSECC_init(), RSECC_mutex, and symbols.
Referenced by RSblock_initBlock().