TTKMusicPlayer: TTKCryptographicHash Class Reference
TTKCryptographicHash Class Reference
The class of the string cryptographic hash.
#include <ttkcryptographichash.h>
Public Member Functions
TTKCryptographicHash ()
QString encrypt (const QString &data, const QString &key)
QString decrypt (const QString &data, const QString &key)
Private Member Functions
TTKString xxteaEncrypt (const TTKString &data, const TTKString &key)
QString xxteaEncrypt (const QString &data, const QString &key)
TTKString xxteaDecrypt (const TTKString &data, const TTKString &key)
QString xxteaDecrypt (const QString &data, const QString &key)
uchar * doXxteaEncrypt (uchar *data, xxtea_uint len, uchar *key, xxtea_uint *retLength)
uchar * doXxteaDecrypt (uchar *data, xxtea_uint len, uchar *key, xxtea_uint *retLength)
void xxteaUintEncrypt (xxtea_uint *v, xxtea_uint len, xxtea_uint *k)
void xxteaUintDecrypt (xxtea_uint *v, xxtea_uint len, xxtea_uint *k)
uchar * fixKeyLength (uchar *key, xxtea_uint keyLength)
xxtea_uint * xxteaToUintArray (uchar *data, xxtea_uint len, int includeLength, xxtea_uint *retLength)
uchar * xxteaToByteArray (xxtea_uint *data, xxtea_uint len, int includeLength, xxtea_uint *retLength)
uchar * xxteaEncrypt (uchar *data, xxtea_uint dataLength, uchar *key, xxtea_uint keyLength, xxtea_uint *retLengthgth)
uchar * xxteaDecrypt (uchar *data, xxtea_uint dataLength, uchar *key, xxtea_uint keyLength, xxtea_uint *retLengthgth)
Detailed Description
The class of the string cryptographic hash.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 39 of file ttkcryptographichash.h.
Constructor & Destructor Documentation
TTKCryptographicHash::TTKCryptographicHash ()
Object contsructor.
Definition at line 123 of file ttkcryptographichash.cpp.
Member Function Documentation
QString TTKCryptographicHash::decrypt (const QString & data, const QString & key)
decrypt by QString data.
Definition at line 133 of file ttkcryptographichash.cpp.
References xxteaDecrypt().
Referenced by MusicUtils::Algorithm::mdII().
uchar * TTKCryptographicHash::doXxteaDecrypt (uchar * data, xxtea_uint len, uchar * key, xxtea_uint * retLength) private
Do XXTEA decrypt.
Definition at line 323 of file ttkcryptographichash.cpp.
References xxteaToByteArray(), xxteaToUintArray(), and xxteaUintDecrypt().
Referenced by xxteaDecrypt().
uchar * TTKCryptographicHash::doXxteaEncrypt (uchar * data, xxtea_uint len, uchar * key, xxtea_uint * retLength) private
Do XXTEA encrypt.
Definition at line 306 of file ttkcryptographichash.cpp.
References xxteaToByteArray(), xxteaToUintArray(), and xxteaUintEncrypt().
Referenced by xxteaEncrypt().
QString TTKCryptographicHash::encrypt (const QString & data, const QString & key)
encrypt by QString data.
Definition at line 128 of file ttkcryptographichash.cpp.
References xxteaEncrypt().
Referenced by MusicUtils::Algorithm::mdII(), xxteaDecrypt(), and xxteaEncrypt().
uchar * TTKCryptographicHash::fixKeyLength (uchar * key, xxtea_uint keyLength) private
Fix key length.
Definition at line 243 of file ttkcryptographichash.cpp.
Referenced by xxteaDecrypt(), and xxteaEncrypt().
TTKString TTKCryptographicHash::xxteaDecrypt (const TTKString & data, const TTKString & key) private
XXTEA decrypt by TTKString data.
Definition at line 156 of file ttkcryptographichash.cpp.
References QAlgorithm::base64Decode(), and encrypt().
Referenced by decrypt(), and xxteaDecrypt().
QString TTKCryptographicHash::xxteaDecrypt (const QString & data, const QString & key) private
XXTEA decrypt by QString data.
Definition at line 190 of file ttkcryptographichash.cpp.
References xxteaDecrypt().
uchar * TTKCryptographicHash::xxteaDecrypt (uchar * data, xxtea_uint dataLength, uchar * key, xxtea_uint keyLength, xxtea_uint * retLengthgth) private
XXTEA decrypt by uchar * data.
Definition at line 359 of file ttkcryptographichash.cpp.
References doXxteaDecrypt(), and fixKeyLength().
TTKString TTKCryptographicHash::xxteaEncrypt (const TTKString & data, const TTKString & key) private
XXTEA encrypt by TTKString data.
Definition at line 138 of file ttkcryptographichash.cpp.
References QAlgorithm::base64Encode(), and encrypt().
Referenced by encrypt(), and xxteaEncrypt().
QString TTKCryptographicHash::xxteaEncrypt (const QString & data, const QString & key) private
XXTEA encrypt by QString data.
Definition at line 185 of file ttkcryptographichash.cpp.
References xxteaEncrypt().
uchar * TTKCryptographicHash::xxteaEncrypt (uchar * data, xxtea_uint dataLength, uchar * key, xxtea_uint keyLength, xxtea_uint * retLengthgth) private
XXTEA encrypt by uchar * data.
Definition at line 340 of file ttkcryptographichash.cpp.
References doXxteaEncrypt(), and fixKeyLength().
uchar * TTKCryptographicHash::xxteaToByteArray (xxtea_uint * data, xxtea_uint len, int includeLength, xxtea_uint * retLength) private
XXTEA to byte array.
Definition at line 278 of file ttkcryptographichash.cpp.
Referenced by doXxteaDecrypt(), and doXxteaEncrypt().
xxtea_uint * TTKCryptographicHash::xxteaToUintArray (uchar * data, xxtea_uint len, int includeLength, xxtea_uint * retLength) private
XXTEA to uint array.
Definition at line 251 of file ttkcryptographichash.cpp.
Referenced by doXxteaDecrypt(), and doXxteaEncrypt().
void TTKCryptographicHash::xxteaUintDecrypt (xxtea_uint * v, xxtea_uint len, xxtea_uint * k) private
XXTEA uint decrypt.
Definition at line 219 of file ttkcryptographichash.cpp.
References XXTEA_DELTA, and XXTEA_MX.
Referenced by doXxteaDecrypt().
void TTKCryptographicHash::xxteaUintEncrypt (xxtea_uint * v, xxtea_uint len, xxtea_uint * k) private
XXTEA uint encrypt.
Definition at line 195 of file ttkcryptographichash.cpp.
References XXTEA_DELTA, and XXTEA_MX.
Referenced by doXxteaEncrypt().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkcryptographichash.h
TTKCommon/TTKLibrary/ttkcryptographichash.cpp