TTKMusicplayer: MusicPlaylistFoundCategoryItem Class Reference
MusicPlaylistFoundCategoryItem Class Reference
The class of the playlist music found category item.
#include <musicplaylistfoundcategorypopwidget.h>
Public Slots
void buttonClicked (int index)
Signals
void categoryChanged (const MusicPlaylistCategoryItem &category)
Public Member Functions
MusicPlaylistFoundCategoryItem (QWidget *parent=0)
void setCategory (const MusicPlaylistCategory &category)
Static Public Member Functions
static QString getClassName ()
Protected Attributes
MusicPlaylistCategory m_category
Detailed Description
The class of the playlist music found category item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 18 of file musicplaylistfoundcategorypopwidget.h.
Constructor & Destructor Documentation
MusicPlaylistFoundCategoryItem::MusicPlaylistFoundCategoryItem (QWidget * parent = 0) explicit
Definition at line 13 of file musicplaylistfoundcategorypopwidget.cpp.
Member Function Documentation
void MusicPlaylistFoundCategoryItem::buttonClicked (int index) slot
Current category changed.
Definition at line 56 of file musicplaylistfoundcategorypopwidget.cpp.
References categoryChanged(), m_category, and MusicPlaylistCategory::m_items.
Referenced by setCategory().
void MusicPlaylistFoundCategoryItem::categoryChanged (const MusicPlaylistCategoryItem & category) signal
Set current category.
Referenced by buttonClicked().
QString MusicPlaylistFoundCategoryItem::getClassName () static
Object contsructor.
Definition at line 19 of file musicplaylistfoundcategorypopwidget.cpp.
void MusicPlaylistFoundCategoryItem::setCategory (const MusicPlaylistCategory & category)
Get class object name.
Definition at line 24 of file musicplaylistfoundcategorypopwidget.cpp.
References buttonClicked(), ITEM_LABEL_WIDTH, ITEM_MAX_COLUMN, MusicPlaylistCategory::m_category, m_category, MusicPlaylistCategory::m_items, MusicUIObject::MColorStyle03, MusicUIObject::MColorStyle08, and MusicUIObject::MFontStyle03.
Referenced by MusicPlaylistFoundCategoryPopWidget::setCategory().
Member Data Documentation
MusicPlaylistCategory MusicPlaylistFoundCategoryItem::m_category protected
Current category item clicked.
Definition at line 50 of file musicplaylistfoundcategorypopwidget.h.
Referenced by buttonClicked(), and setCategory().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistfoundcategorypopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistfoundcategorypopwidget.cpp