TTKMusicPlayer: MusicKWQueryMovieRequest Class Reference
MusicKWQueryMovieRequest Class Reference
The class of the kuwo mv query download data from net.
#include <musickwquerymovierequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
void downLoadPageFinished ()
void downLoadSingleFinished ()
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicKWQueryMovieRequest (QObject *parent=nullptr)
virtual void startToPage (int offset) overridefinal
virtual void startToSearch (QueryType type, const QString &value) overridefinal
virtual void startToSingleSearch (const QString &id) overridefinal
Public Member Functions inherited from MusicQueryMovieRequest
MusicQueryMovieRequest (QObject *parent=nullptr)
virtual void startToSearch (const QString &value)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
void setQueryQuality (MusicObject::QueryQuality quality)
MusicObject::QueryQuality queryQuality () const
void setQueryAllRecords (bool state)
bool queryAllRecords () const
void setQueryLite (bool state)
bool queryLite () const
void setQueryType (QueryType type)
QueryType queryType () const
QString queryServer () const
QString queryValue () const
void setSongInfoList (const MusicObject::MusicSongInformationList &songInfos)
const MusicObject::MusicSongInformationList & songInfoList () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPageQueryRequest
MusicPageQueryRequest (QObject *parent=nullptr)
int pageSize () const
int totalSize () const
int pageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Private Member Functions
void parseFromMovieProperty (MusicObject::MusicSongInformation *info, const QString &format) const
void parseFromMovieProperty (MusicObject::MusicSongInformation *info, const QString &format, int bitrate) const
void parseFromMovieInfo (MusicObject::MusicSongInformation *info) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryServer { QueryServer::WY, QueryServer::KW, QueryServer::KG }
enum QueryType { QueryType::Music, QueryType::Movie, QueryType::Lrc, QueryType::Other }
Signals inherited from MusicQueryMovieRequest
void createMovieItem (const MusicResultDataItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicResultInfoItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongProperty *prop) const
bool findUrlFileSize (MusicObject::MusicSongPropertyList *props) const
Protected Attributes inherited from MusicAbstractQueryRequest
QString m_queryValue
QString m_queryServer
QueryType m_queryType
MusicObject::QueryQuality m_queryQuality
bool m_queryAllRecords
bool m_queryLite
MusicObject::MusicSongInformationList m_songInfos
Protected Attributes inherited from MusicPageQueryRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the kuwo mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musickwquerymovierequest.h.
Constructor & Destructor Documentation
MusicKWQueryMovieRequest::MusicKWQueryMovieRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musickwquerymovierequest.cpp.
References MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryServer, and QUERY_KW_INTERFACE.
Member Function Documentation
void MusicKWQueryMovieRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 56 of file musickwquerymovierequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), TTKTime::formatDuration(), MusicResultInfoItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractNetwork::m_reply, MusicResultInfoItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicAbstractQueryRequest::m_songInfos, MusicResultInfoItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicResultInfoItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), MT_S2MS, QJson::Parser::parse(), parseFromMovieProperty(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicKWQueryMovieRequest::downLoadPageFinished () slot
Download page data from net finished.
Definition at line 113 of file musickwquerymovierequest.cpp.
References MusicQueryMovieRequest::createMovieItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicUtils::String::isNetworkUrl(), KW_MOVIE_COVER_PREFIX_URL, MusicResultDataItem::m_coverUrl, MusicResultDataItem::m_id, MusicResultDataItem::m_name, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicResultDataItem::m_updateTime, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), TTK_INFO_STREAM, TTK_NETWORK_QUERY_CHECK, and TTK_NULL_STR.
Referenced by startToPage().
void MusicKWQueryMovieRequest::downLoadSingleFinished () slot
Download single data from net finished.
Definition at line 159 of file musickwquerymovierequest.cpp.
References MusicAbstractQueryRequest::createSearchedItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicResultInfoItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicAbstractQueryRequest::m_queryValue, MusicResultInfoItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicAbstractQueryRequest::m_songInfos, MusicResultInfoItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicResultInfoItem::m_type, MusicAbstractQueryRequest::mapQueryServerString(), parseFromMovieInfo(), parseFromMovieProperty(), TTK_INFO_STREAM, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSingleSearch().
void MusicKWQueryMovieRequest::parseFromMovieInfo (MusicObject::MusicSongInformation * info) const private
Read mv info property from query results.
Definition at line 264 of file musickwquerymovierequest.cpp.
References KW_SONG_INFO_URL, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicObject::syncNetworkQueryForGet().
Referenced by downLoadSingleFinished().
void MusicKWQueryMovieRequest::parseFromMovieProperty (MusicObject::MusicSongInformation * info, const QString & format) const private
Read mv tags(size) from query results.
Definition at line 188 of file musickwquerymovierequest.cpp.
References MusicObject::MusicSongInformation::m_songId, MB_1000, MB_250, MB_500, and MB_750.
Referenced by downLoadFinished(), and downLoadSingleFinished().
void MusicKWQueryMovieRequest::parseFromMovieProperty (MusicObject::MusicSongInformation * info, const QString & format, int bitrate) const private
Read mv info property from query results.
Definition at line 216 of file musickwquerymovierequest.cpp.
References _SIGN, ALG_SHR_KEY, QAlgorithm::Des::encrypt(), MusicAbstractQueryRequest::findUrlFileSize(), KW_MOVIE_ATTR_URL, KW_MOVIE_URL, MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), and MusicObject::syncNetworkQueryForGet().
void MusicKWQueryMovieRequest::startToPage (int offset) final override virtual
Start to search data from name and type bt page.
Reimplemented from MusicPageQueryRequest.
Definition at line 12 of file musickwquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadPageFinished(), KW_ARTIST_MOVIE_URL, MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryValue, MusicAbstractNetwork::m_reply, MusicPageQueryRequest::m_totalSize, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and TTK_INFO_STREAM.
void MusicKWQueryMovieRequest::startToSearch (QueryType type, const QString & value) final override virtual
Start to search data by type and input data.
Implements MusicAbstractQueryRequest.
Definition at line 29 of file musickwquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), KW_SONG_SEARCH_URL, MusicAbstractNetwork::m_manager, MusicPageQueryRequest::m_pageSize, MusicAbstractQueryRequest::m_queryType, MusicAbstractQueryRequest::m_queryValue, MusicAbstractNetwork::m_reply, MusicKWInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and TTK_INFO_STREAM.
void MusicKWQueryMovieRequest::startToSingleSearch (const QString & id) final override virtual
Start to search data by given id.
Reimplemented from MusicAbstractQueryRequest.
Definition at line 46 of file musickwquerymovierequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadSingleFinished(), MusicAbstractQueryRequest::m_queryValue, MT_MS, and TTK_INFO_STREAM.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwquerymovierequest.h
TTKModule/TTKCore/musicNetworkKits/music/kw/musickwquerymovierequest.cpp