TTKMusicPlayer: MusicRecommendQueryWidget Class Reference
MusicRecommendQueryWidget Class Reference
The class of the recommend music query widget.
#include <musicrecommendquerywidget.h>
Public Slots
void queryAllFinished ()
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicRecommendQueryWidget (QWidget *parent=nullptr)
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameByID (const QString &id) overridefinal
virtual void resizeWidget () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Public Member Functions inherited from TTKAbstractResizeInterface
TTKAbstractResizeInterface ()=default
Private Member Functions
void createLabels ()
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultDataItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Module m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of the recommend music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 56 of file musicrecommendquerywidget.h.
Constructor & Destructor Documentation
MusicRecommendQueryWidget::MusicRecommendQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 36 of file musicrecommendquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget.
Member Function Documentation
void MusicRecommendQueryWidget::createLabels () private
Create init interface lables.
Definition at line 66 of file musicrecommendquerywidget.cpp.
References MusicUIObject::CheckBoxStyle01, MusicUtils::Widget::generateVScrollAreaFormat(), MusicAbstractItemQueryWidget::initFirstWidget(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_statusLabel, and MusicUIObject::PushButtonStyle03.
Referenced by setSongName().
void MusicRecommendQueryWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 61 of file musicrecommendquerywidget.cpp.
void MusicRecommendQueryWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 56 of file musicrecommendquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_queryTableWidget, and MusicItemQueryTableWidget::resizeSection().
void MusicRecommendQueryWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 43 of file musicrecommendquerywidget.cpp.
References createLabels(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicItemQueryTableWidget::setQueryInput(), MusicAbstractItemQueryWidget::setSongName(), MusicUtils::String::songName(), and MusicItemQueryTableWidget::startSearchQuery().
void MusicRecommendQueryWidget::setSongNameByID (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 51 of file musicrecommendquerywidget.cpp.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicrecommendquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicrecommendquerywidget.cpp