TTKMusicplayer: MusicDesktopWallpaperWidget Class Reference
MusicDesktopWallpaperWidget Class Reference
The class of the desktop wallpaper widget.
#include <musicdesktopwallpaperwidget.h>
Public Slots
void netRadioButtonPressed ()
void localRadioButtonPressed ()
void playRadioButtonPressed ()
void viewButtonPressed ()
void confirmButtonPressed ()
void stopButtonPressed ()
void cancelButtonPressed ()
void parameterFinished ()
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void resetFlag (MusicObject::ToolsType flag)
Public Member Functions
MusicDesktopWallpaperWidget (QWidget *parent=0)
~MusicDesktopWallpaperWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
void initWidgetStyle () const
void initParameters () const
void setAutoStart (bool autoStart) const
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicDesktopWallpaperWidget * m_ui
int m_currentMode
QStringList m_path
MusicDesktopWallpaperThread * m_wallThread
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the desktop wallpaper widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musicdesktopwallpaperwidget.h.
Constructor & Destructor Documentation
MusicDesktopWallpaperWidget::MusicDesktopWallpaperWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 14 of file musicdesktopwallpaperwidget.cpp.
References cancelButtonPressed(), confirmButtonPressed(), initParameters(), initWidgetStyle(), localRadioButtonPressed(), m_ui, m_wallThread, MusicUIObject::MToolButtonStyle04, netRadioButtonPressed(), playRadioButtonPressed(), stopButtonPressed(), and viewButtonPressed().
MusicDesktopWallpaperWidget::~MusicDesktopWallpaperWidget ()
Definition at line 47 of file musicdesktopwallpaperwidget.cpp.
References JPG_FILE, m_ui, m_wallThread, MusicDesktopWallpaperThread::stopAndQuitThread(), and TEMPORARY_DIR.
Member Function Documentation
void MusicDesktopWallpaperWidget::cancelButtonPressed () slot
Close current widget.
Definition at line 232 of file musicdesktopwallpaperwidget.cpp.
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 64 of file musicdesktopwallpaperwidget.cpp.
References resetFlag(), and MusicObject::TT_Wallpaper.
void MusicDesktopWallpaperWidget::confirmButtonPressed () slot
Confirm button clicked to start show wallpaper.
Definition at line 180 of file musicdesktopwallpaperwidget.cpp.
References MusicDownLoadThreadAbstract::Download_BigBG, MusicMessageBox::exec(), JPG_FILE, m_currentMode, m_path, m_ui, parameterFinished(), MusicMessageBox::setText(), MusicDataDownloadThread::startToDownload(), and TEMPORARY_DIR.
Referenced by MusicDesktopWallpaperWidget().
QString MusicDesktopWallpaperWidget::getClassName () static
Get class object name.
Definition at line 59 of file musicdesktopwallpaperwidget.cpp.
void MusicDesktopWallpaperWidget::initParameters () const protected
Init parameters.
Definition at line 119 of file musicdesktopwallpaperwidget.cpp.
References m_ui, MT_D, and MT_H.
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::initWidgetStyle () const protected
Create all widget style in layout.
Definition at line 70 of file musicdesktopwallpaperwidget.cpp.
References m_ui, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MComboBoxStyle01, MusicUIObject::MItemView01, MusicUIObject::MLineEditStyle01, MusicUIObject::MPushButtonStyle04, MusicUIObject::MRadioButtonStyle01, and MusicUIObject::MScrollBarStyle01.
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::localRadioButtonPressed () slot
Local button clicked.
Definition at line 163 of file musicdesktopwallpaperwidget.cpp.
References m_currentMode, m_path, and m_ui.
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::netRadioButtonPressed () slot
Net button clicked.
Definition at line 155 of file musicdesktopwallpaperwidget.cpp.
References m_currentMode, m_path, and m_ui.
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::parameterFinished () slot
Set parameters.
Definition at line 209 of file musicdesktopwallpaperwidget.cpp.
References m_currentMode, m_path, m_ui, m_wallThread, MT_H2S, MT_M2S, setAutoStart(), MusicDesktopWallpaperThread::setParamters(), and MusicDesktopWallpaperThread::start().
Referenced by confirmButtonPressed().
void MusicDesktopWallpaperWidget::playRadioButtonPressed () slot
Play button clicked.
Definition at line 171 of file musicdesktopwallpaperwidget.cpp.
References m_currentMode, m_path, and m_ui.
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by closeEvent().
void MusicDesktopWallpaperWidget::setAutoStart (bool autoStart) const protected
Set auto thread to show wallpaper.
Definition at line 237 of file musicdesktopwallpaperwidget.cpp.
References MusicRegeditManager::setDesktopWallAutoStart().
Referenced by parameterFinished().
void MusicDesktopWallpaperWidget::show () slot
Override show function.
Definition at line 246 of file musicdesktopwallpaperwidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
void MusicDesktopWallpaperWidget::stopButtonPressed () slot
Stop show wallpaper.
Definition at line 227 of file musicdesktopwallpaperwidget.cpp.
References m_wallThread, and MusicDesktopWallpaperThread::stopAndQuitThread().
Referenced by MusicDesktopWallpaperWidget().
void MusicDesktopWallpaperWidget::viewButtonPressed () slot
Find local file button clicked.
Definition at line 139 of file musicdesktopwallpaperwidget.cpp.
References MusicUtils::Core::findFile(), m_path, and m_ui.
Referenced by MusicDesktopWallpaperWidget().
Member Data Documentation
int MusicDesktopWallpaperWidget::m_currentMode protected
Definition at line 113 of file musicdesktopwallpaperwidget.h.
Referenced by confirmButtonPressed(), localRadioButtonPressed(), netRadioButtonPressed(), parameterFinished(), and playRadioButtonPressed().
QStringList MusicDesktopWallpaperWidget::m_path protected
Definition at line 114 of file musicdesktopwallpaperwidget.h.
Referenced by confirmButtonPressed(), localRadioButtonPressed(), netRadioButtonPressed(), parameterFinished(), playRadioButtonPressed(), and viewButtonPressed().
Ui::MusicDesktopWallpaperWidget* MusicDesktopWallpaperWidget::m_ui protected
Definition at line 112 of file musicdesktopwallpaperwidget.h.
Referenced by confirmButtonPressed(), initParameters(), initWidgetStyle(), localRadioButtonPressed(), MusicDesktopWallpaperWidget(), netRadioButtonPressed(), parameterFinished(), playRadioButtonPressed(), show(), viewButtonPressed(), and ~MusicDesktopWallpaperWidget().
MusicDesktopWallpaperThread* MusicDesktopWallpaperWidget::m_wallThread protected
Definition at line 115 of file musicdesktopwallpaperwidget.h.
Referenced by MusicDesktopWallpaperWidget(), parameterFinished(), stopButtonPressed(), and ~MusicDesktopWallpaperWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicdesktopwallpaperwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicdesktopwallpaperwidget.cpp