TTKMusicPlayer: TTKPlatformSystem Class Reference
TTKPlatformSystem Class Reference
The class of the platform system.
#include <ttkplatformsystem.h>
Public Types
enum System {
System::Win11, System::Win10, System::Win81, System::Win8,
System::Win7, System::WinVista, System::WinXP, System::WinXPProfessionalEdition,
System::Win2000, System::WinNT40, System::Win95, System::Win98,
System::WinMe, System::WinServer2003, System::WinServer2003R2, System::WinServer2008,
System::WinServer2008R2, System::WinServer2012, System::Linux, System::LinuxUbuntu,
System::LinuxDebian, System::LinuxArch, System::LinuxCentOS, System::Mac,
System::Unkown
}
Public Member Functions
int logicalDotsPerInchX () const
int logicalDotsPerInchY () const
int logicalDotsPerInch () const
System systemName () const
Detailed Description
The class of the platform system.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file ttkplatformsystem.h.
Member Enumeration Documentation
enum TTKPlatformSystem::System strong
Enumerator
Win11
Win10
Win81
Win8
Win7
WinVista
WinXP
WinXPProfessionalEdition
Win2000
WinNT40
Win95
Win98
WinMe
WinServer2003
WinServer2003R2
WinServer2008
WinServer2008R2
WinServer2012
Linux
LinuxUbuntu
LinuxDebian
LinuxArch
LinuxCentOS
Mac
Unkown
Definition at line 31 of file ttkplatformsystem.h.
Member Function Documentation
int TTKPlatformSystem::logicalDotsPerInch () const
Get local DPI.
Definition at line 68 of file ttkplatformsystem.cpp.
References generateDPIValue().
Referenced by loadAppScaledFactor().
int TTKPlatformSystem::logicalDotsPerInchX () const
Get local DPI x.
Definition at line 56 of file ttkplatformsystem.cpp.
References generateDPIValue().
int TTKPlatformSystem::logicalDotsPerInchY () const
Get local DPI y.
Definition at line 62 of file ttkplatformsystem.cpp.
References generateDPIValue().
TTKPlatformSystem::System TTKPlatformSystem::systemName () const
Get system name.
Definition at line 74 of file ttkplatformsystem.cpp.
References Linux, LinuxArch, LinuxCentOS, LinuxDebian, LinuxUbuntu, Mac, TTKVoidCast, Unkown, Win10, Win11, Win2000, Win7, Win8, Win81, Win95, Win98, WinMe, WinNT40, WinServer2003, WinServer2003R2, WinServer2008, WinServer2008R2, WinServer2012, WinVista, WinXP, and WinXPProfessionalEdition.
Referenced by TTK::Url::openUrl(), and MusicApplicationModule::sideAnimationByOn().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkplatformsystem.h
TTKCommon/TTKLibrary/ttkplatformsystem.cpp