TTKMusicplayer: MusicDownLoadKWInterface Class Reference
MusicDownLoadKWInterface Class Reference
The class to kuwo query download interface.
#include <musicdownloadkwinterface.h>
Public Member Functions
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
void readFromMusicSongAttributePlus (MusicObject::MusicSongInformation *info, const QString &suffix, const QString &format, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantList &format, const QString &quality, bool all)
void readFromMusicSongPic (MusicObject::MusicSongInformation *info)
Detailed Description
The class to kuwo query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 69 of file musicdownloadkwinterface.h.
Member Function Documentation
void MusicDownLoadKWInterface::readFromMusicLLAttribute (MusicObject::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate)
QJson import.
Read mv info attribute from query results.
Definition at line 16 of file musicdownloadkwinterface.cpp.
References _SIGN, ALG_LOW_KEY, ALG_UA_KEY, QDesWrap::encrypt(), MusicSemaphoreLoop::exec(), KW_MV_URL, KW_SONG_ATTR_LL_URL, KW_UA_URL_1, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), and MusicUtils::Codec::toUtf8().
Referenced by readFromMusicSongAttribute(), and readFromMusicSongAttributePlus().
void MusicDownLoadKWInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate)
Read tags(size) from query results.
Definition at line 72 of file musicdownloadkwinterface.cpp.
References APE_FILE_PREFIX, FLC_FILE_PREFIX, KW_SONG_ATTR_URL, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), MP3_FILE_PREFIX, and readFromMusicLLAttribute().
Referenced by MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), and readFromMusicSongAttribute().
void MusicDownLoadKWInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & format, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 152 of file musicdownloadkwinterface.cpp.
References APE_FILE_PREFIX, FLC_FILE_PREFIX, MB_1000, MB_128, MB_192, MB_320, MB_750, MP3_FILE_PREFIX, and readFromMusicSongAttribute().
void MusicDownLoadKWInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantList & format, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 185 of file musicdownloadkwinterface.cpp.
References APE_FILE_PREFIX, FLC_FILE_PREFIX, MB_1000, MB_128, MB_192, MB_320, MB_750, MP3_FILE_PREFIX, and readFromMusicSongAttributePlus().
void MusicDownLoadKWInterface::readFromMusicSongAttributePlus (MusicObject::MusicSongInformation * info, const QString & suffix, const QString & format, int bitrate)
Read tags(size) from query results.
Definition at line 112 of file musicdownloadkwinterface.cpp.
References APE_FILE_PREFIX, FLC_FILE_PREFIX, KW_SONG_ATTR_URL, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), MP3_FILE_PREFIX, and readFromMusicLLAttribute().
Referenced by readFromMusicSongAttribute().
void MusicDownLoadKWInterface::readFromMusicSongPic (MusicObject::MusicSongInformation * info)
Read tags(lrc) from query results.
Definition at line 222 of file musicdownloadkwinterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), KW_ALBUM_COVER_URL, KW_SONG_LRC_URL, KW_UA_URL_1, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_timeLength, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), and MusicUtils::Codec::toUtf8().
Referenced by MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), and MusicDownLoadQueryKWThread::singleDownLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/kw/musicdownloadkwinterface.h
TTKModule/TTKCore/musicNetworkKits/kw/musicdownloadkwinterface.cpp