TTKMusicplayer: Random Namespace Reference
Random Namespace Reference
The class of the random wrapper.
Functions
MUSIC_EXTRAS_EXPORT void initRandom ()
MUSIC_EXTRAS_EXPORT int random (int value)
Detailed Description
The class of the random wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void Random::initRandom ()
Init random value seed.
Definition at line 7 of file random.cpp.
Referenced by MusicTime::initRandom(), and QImageWrap::QCubeWavePrivate::QCubeWavePrivate().
int Random::random (int value)
Get random value.
Definition at line 14 of file random.cpp.
Referenced by QImageWrap::QCubeWave::input(), MusicTime::random(), and MusicDesktopWallpaperThread::setRandom().