TTKMusicplayer: TTKModule/TTKCore/musicCoreKits/musicplatformmanager.cpp File Reference
musicplatformmanager.cpp File Reference
#include "musicplatformmanager.h"
#include "musicformats.h"
#include <QScreen>
#include <QSettings>
#include <QProcess>
#include <QStringList>
#include <QApplication>
Macros
#define DEFAULT_DPI 96
Functions
static QSize generateDPIValue ()
Macro Definition Documentation
#define DEFAULT_DPI 96
Definition at line 18 of file musicplatformmanager.cpp.
Referenced by generateDPIValue().
Function Documentation
static QSize generateDPIValue () static
Definition at line 78 of file musicplatformmanager.cpp.
References DEFAULT_DPI.
Referenced by MusicPlatformManager::logicalDotsPerInch(), MusicPlatformManager::logicalDotsPerInchX(), and MusicPlatformManager::logicalDotsPerInchY().