TTKMusicPlayer: QSyncListData Class Reference
QSyncListData Class Reference
The class of the sync cloud list data.
#include <qsynclistdata.h>
Signals
void receiveFinshed (const QSyncDataItemList &items)
Public Member Functions
QSyncListData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void listDataOperator (const QString &bucket)
Public Member Functions inherited from QSyncDataInterface
QSyncDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Private Slots
virtual void receiveDataFromServer () overridefinal
Additional Inherited Members
Protected Slots inherited from QSyncDataInterface
virtual void receiveDataFromServer ()=0
void replyError (QNetworkReply::NetworkError error)
Protected Member Functions inherited from QSyncDataInterface
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
QSyncDataInterface (QSyncDataInterfacePrivate &pvt, QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Detailed Description
The class of the sync cloud list data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qsynclistdata.h.
Constructor & Destructor Documentation
QSyncListData::QSyncListData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file qsynclistdata.cpp.
Member Function Documentation
void QSyncListData::listDataOperator (const QString & bucket)
List data to operator.
Definition at line 13 of file qsynclistdata.cpp.
References QSyncUtils::GMT(), QSyncConfig::HOST, QtNetworkErrorConnect, receiveDataFromServer(), QSyncDataInterface::replyError(), TTK_D, TTK_DOT, TTK_SEPARATOR, and TTK_SLOT.
Referenced by MusicCloudManagerTableWidget::updateListFromServer().
void QSyncListData::receiveDataFromServer () final override private virtual slot
Receive data from server finshed.
Definition at line 41 of file qsynclistdata.cpp.
References QSyncDataItem::clear(), QSyncDataItem::m_hash, QSyncDataItem::m_mimeType, QSyncDataItem::m_name, QSyncDataItem::m_putTime, QSyncDataItem::m_size, name, receiveFinshed(), TTK_DATE_TIMEM_FORMAT, and TTKObjectCast.
Referenced by listDataOperator().
void QSyncListData::receiveFinshed (const QSyncDataItemList & items) signal
Receive data finshed.
Referenced by receiveDataFromServer().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsynclistdata.h
TTKThirdParty/TTKExtras/qsync/qsynclistdata.cpp