TTKMusicplayer: MusicUtils::Widget Namespace Reference
MusicUtils::Widget Namespace Reference
Functions
TTK_MODULE_EXPORT void setBorderShadow (QWidget *widget, QPainter *painter)
TTK_MODULE_EXPORT void setLabelFontSize (QWidget *widget, int size)
TTK_MODULE_EXPORT void setLabelFontStyle (QWidget *widget, MusicObject::FontStyleMode type)
TTK_MODULE_EXPORT QString elidedText (const QFont &font, const QString &text, Qt::TextElideMode mode, int width)
TTK_MODULE_EXPORT int fontTextWidth (const QFont &font, const QString &text)
TTK_MODULE_EXPORT int fontTextHeight (const QFont &font)
TTK_MODULE_EXPORT void adjustMenuPosition (QMenu *menu)
TTK_MODULE_EXPORT void positionInCenter (QWidget *widget)
TTK_MODULE_EXPORT void setTransparent (QWidget *widget, int alpha)
TTK_MODULE_EXPORT void setComboBoxText (QComboBox *widget, const QString &text)
TTK_MODULE_EXPORT void widgetToRound (QWidget *widget, int ratioX, int ratioY)
TTK_MODULE_EXPORT void generateVScrollAreaFormat (QWidget *widget, QWidget *parent, bool background=true)
TTK_MODULE_EXPORT void generateHScrollAreaFormat (QWidget *widget, QWidget *parent, bool background=true)
TTK_MODULE_EXPORT void generateComboBoxFormat (QComboBox *widget, const QString &style=QString())
Function Documentation
void MusicUtils::Widget::adjustMenuPosition (QMenu * menu)
Adjust the menu position.
Definition at line 73 of file musicwidgetutils.cpp.
Referenced by MusicSearchEdit::contextMenuEvent(), MusicCloudManagerTableWidget::contextMenuEvent(), MusicSongsListTableWidget::contextMenuEvent(), MusicLrcContainerForInterior::contextMenuEvent(), MusicSongsSummariziedWidget::contextMenuEvent(), MusicVideoView::createRightMenu(), MusicApplication::musicCreateRightMenu(), MusicApplication::musicImportSongs(), and MusicSongsToolBoxTopWidget::showMenu().
QString MusicUtils::Widget::elidedText (const QFont & font, const QString & text, Qt::TextElideMode mode, int width)
Set text elided text by font.
Definition at line 51 of file musicwidgetutils.cpp.
Referenced by MusicLocalSongsTableWidget::addItems(), MusicLocalSongsInfoTableWidget::addItems(), MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), MusicSongsListTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayWidget::changItemName(), MusicSongsListTableWidget::closeRenameItem(), MusicAlbumQueryWidget::createAlbumInfoItem(), MusicConnectTransferTableWidget::createAllItems(), MusicSongItemSelectedTableWidget::createAllItems(), MusicSongCheckToolsRenameTableWidget::createAllItems(), MusicLrcDownloadBatchTableWidget::createAllItems(), MusicLrcLocalLinkTableWidget::createAllItems(), MusicSongCheckToolsDuplicateTableWidget::createAllItems(), MusicSongCheckToolsQualityTableWidget::createAllItems(), MusicArtistQueryWidget::createArtistInfoItem(), MusicWebDJRadioInfoWidget::createCategoryInfoItem(), MusicWebMVRadioInfoWidget::createCategoryInfoItem(), MusicCloudDownloadTableWidget::createItem(), MusicDownloadRecordTableWidget::createItem(), MusicDownloadBatchTableItem::createItem(), MusicConnectTransferCompleteTableWidget::createItem(), MusicCloudUploadTableWidget::createItem(), MusicCloudManagerTableWidget::createItem(), MusicReplayGainWidget::createItemFinished(), MusicSongSearchPopTableWidget::createItems(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicSoundKMicroSearchTableWidget::createSearchedItem(), MusicLrcSearchTableWidget::createSearchedItem(), MusicItemQueryTableWidget::createSearchedItem(), MusicSongSearchTableWidget::createSearchedItem(), MusicVideoSearchTableWidget::createSearchedItem(), MusicToplistQueryWidget::createToplistInfoItem(), MusicConnectMobileWidget::deviceTypeChanged(), MusicSongRingtoneMaker::initInputPath(), MusicTransformWidget::initInputPath(), MusicLrcSearchWidget::lrcSearchButtonClicked(), MusicPlaylistQueryInfoWidget::resizeWindow(), MusicWebDJRadioProgramTableWidget::resizeWindow(), MusicCloudManagerTableWidget::resizeWindow(), MusicItemQueryTableWidget::resizeWindow(), MusicSongSearchTableWidget::resizeWindow(), MusicWebDJRadioInfoWidget::resizeWindow(), MusicAlbumQueryWidget::resizeWindow(), MusicVideoSearchTableWidget::resizeWindow(), MusicToplistQueryWidget::resizeWindow(), MusicWebMVRadioInfoWidget::resizeWindow(), MusicArtistQueryWidget::resizeWindow(), MusicSongSharingWidget::setData(), MusicConnectTransferWidget::setDeviceInfoItem(), MusicRemoteWidgetForRectangle::setLabelText(), MusicRemoteWidgetForStrip::setLabelText(), MusicRemoteWidgetForRipple::setLabelText(), MusicRemoteWidgetForSimpleStyle::setLabelText(), MusicSystemTrayMenu::setLabelText(), MusicArtistAlbumsItemWidget::setMusicResultsItem(), MusicWebDJRadioCategoryItemWidget::setMusicResultsItem(), MusicWebDJRadioQueryItemWidget::setMusicResultsItem(), MusicWebMVRadioQueryItemWidget::setMusicResultsItem(), MusicArtistListQueryItemWidget::setMusicResultsItem(), MusicPlaylistQueryItemWidget::setMusicResultsItem(), MusicSongsListItemInfoWidget::setMusicSongInformation(), MusicSongsListPlayedWidget::setParameter(), MusicSongsListPlayWidget::setParameter(), MusicSongSearchOnlineWidget::setResizeLabelText(), MusicDownloadWidget::setSongName(), MusicFunctionToolBoxTopWidget::setTitle(), MusicVideoPlayWidget::setTitleText(), MusicSongsListTableWidget::startToDrag(), MusicTransformWidget::transformFinish(), MusicSongsListPlayedTableWidget::updateSongsFileName(), and MusicSongsListTableWidget::updateSongsFileName().
int MusicUtils::Widget::fontTextHeight (const QFont & font)
Get font height by font.
Definition at line 67 of file musicwidgetutils.cpp.
Referenced by MusicBarrageWidget::createLabel(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme10(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicLrcManagerForInterior::paintEvent(), MusicLrcManagerHorizontalDesktop::paintEvent(), MusicLrcManagerVerticalDesktop::paintEvent(), MusicPreviewLabel::paintEvent(), MusicToastLabel::setText(), and MusicLrcContainerForInterior::showNoLrcCurrentInfo().
int MusicUtils::Widget::fontTextWidth (const QFont & font, const QString & text)
Get text width by font.
Definition at line 57 of file musicwidgetutils.cpp.
Referenced by MusicBarrageWidget::createLabel(), MusicPageQueryWidget::createPageWidget(), MusicCommentsItem::createSearchedItem(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme10(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicSplitItemClickedLabel::mouseMoveEvent(), MusicLrcMakerWidgetItem::moveRight(), MusicPageQueryWidget::page(), MusicLrcManagerForInterior::paintEvent(), MusicMarqueeWidget::paintEvent(), MusicLrcMakerWidgetItem::paintEvent(), MusicBackgroundListItem::paintEvent(), MusicThemeLineLabel::paintEvent(), MusicMarqueeWidget::setText(), MusicLrcMakerWidgetItem::setText(), MusicToastLabel::setText(), MusicLrcManager::setText(), MusicLrcContainerForInterior::showNoLrcCurrentInfo(), MusicLrcManager::startDrawLrcMask(), and MusicMarqueeWidget::timerEvent().
void MusicUtils::Widget::generateComboBoxFormat (QComboBox * widget, const QString & style = QString())
Generate combobox format style.
Definition at line 158 of file musicwidgetutils.cpp.
References MusicUIObject::MQSSComboBoxStyle01, MusicUIObject::MQSSItemView01, and MusicUIObject::MQSSScrollBarStyle01.
Referenced by MusicBackgroundOnlineWidget::createFunctionsWidget(), MusicSettingWidget::initAudioSettingWidget(), MusicSettingWidget::initDesktopLrcWidget(), MusicSettingWidget::initDownloadWidget(), MusicTimerWidget::initFirstWidget(), MusicSettingWidget::initInteriorLrcWidget(), MusicSettingWidget::initNetworkWidget(), MusicSettingWidget::initNormalSettingWidget(), MusicTimerWidget::initSecondWidget(), MusicSettingWidget::initSoundEffectWidget(), MusicTimerWidget::initThreeWidget(), MusicSoundKMicroSettingPopWidget::initWidget(), MusicDownloadBatchTableItem::MusicDownloadBatchTableItem(), MusicDownloadBatchWidget::MusicDownloadBatchWidget(), MusicEqualizerDialog::MusicEqualizerDialog(), MusicLocalSongsManagerWidget::MusicLocalSongsManagerWidget(), MusicSongRingtoneMaker::MusicSongRingtoneMaker(), MusicSoundEffectsWidget::MusicSoundEffectsWidget(), and MusicTransformWidget::MusicTransformWidget().
void MusicUtils::Widget::generateHScrollAreaFormat (QWidget * widget, QWidget * parent, bool background = true)
Generate horizontal scrollArea format style.
Definition at line 141 of file musicwidgetutils.cpp.
References MusicUIObject::MQSSScrollBarStyle02, MusicUIObject::MQSSScrollBarStyle04, and TTKStatic_cast.
Referenced by MusicLrcPosterWidget::MusicLrcPosterWidget().
void MusicUtils::Widget::generateVScrollAreaFormat (QWidget * widget, QWidget * parent, bool background = true)
Generate vertical scrollArea format style.
Definition at line 124 of file musicwidgetutils.cpp.
References MusicUIObject::MQSSScrollBarStyle01, MusicUIObject::MQSSScrollBarStyle03, and TTKStatic_cast.
Referenced by MusicArtistListQueryWidget::createArtistListItem(), MusicWebMVRadioQueryWidget::createCategoryItem(), MusicRecommendQueryWidget::createLabels(), MusicSimilarQueryWidget::createLabels(), MusicAlbumQueryWidget::createLabels(), MusicWebDJRadioInfoWidget::createLabels(), MusicToplistQueryWidget::createLabels(), MusicWebMVRadioInfoWidget::createLabels(), MusicArtistQueryWidget::createLabels(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), MusicCommentsWidget::initWidget(), MusicSpectrumLayoutWidget::initWidget(), MusicPlayedListPopWidget::initWidget(), MusicBackgroundSkinDialog::MusicBackgroundSkinDialog(), MusicFunctionToolBoxWidget::MusicFunctionToolBoxWidget(), MusicLrcPosterWidget::MusicLrcPosterWidget(), MusicLrcTranslatedWidget::MusicLrcTranslatedWidget(), MusicSoundEffectsWidget::MusicSoundEffectsWidget(), MusicWebDJRadioCategoryWidget::MusicWebDJRadioCategoryWidget(), MusicPlaylistFoundCategoryPopWidget::setCategory(), MusicToplistQueryCategoryPopWidget::setCategory(), MusicArtistListQueryCategoryPopWidget::setCategory(), MusicWebMVRadioQueryCategoryPopWidget::setCategory(), and MusicPlaylistQueryInfoWidget::setMusicResultsItem().
void MusicUtils::Widget::positionInCenter (QWidget * widget)
Adjust the widget in screen center.
Definition at line 90 of file musicwidgetutils.cpp.
References TTKDesktopWrapper::screenGeometry().
Referenced by MusicDownloadWidget::MusicDownloadWidget(), and MusicWebFMRadioPlayWidget::MusicWebFMRadioPlayWidget().
void MusicUtils::Widget::setBorderShadow (QWidget * widget, QPainter * painter)
Set widget border shadow.
Definition at line 13 of file musicwidgetutils.cpp.
References HEIGHT, and WIDTH.
Referenced by MusicProgressWidget::paintEvent(), MusicAbstractMoveWidget::paintEvent(), MusicAbstractMoveDialog::paintEvent(), and MusicScreenSaverHoverItem::paintEvent().
void MusicUtils::Widget::setComboBoxText (QComboBox * widget, const QString & text)
Set ComboBox text.
Definition at line 103 of file musicwidgetutils.cpp.
Referenced by MusicLocalSongsManagerWidget::findExtraDevicePath(), and MusicSettingWidget::initControllerParameter().
void MusicUtils::Widget::setLabelFontSize (QWidget * widget, int size)
Set widget label font.
Definition at line 27 of file musicwidgetutils.cpp.
Referenced by MusicBarrageWidget::createLabel(), MusicLrcContainerForInterior::createNoLrcCurrentInfo(), and MusicEqualizerDialog::initialize().
void MusicUtils::Widget::setLabelFontStyle (QWidget * widget, MusicObject::FontStyleMode type)
Set widget label font.
Definition at line 34 of file musicwidgetutils.cpp.
References MusicObject::Bold, MusicObject::FixedPitch, MusicObject::Italic, MusicObject::Kerningt, MusicObject::Overline, MusicObject::StrikeOut, and MusicObject::Underline.
Referenced by MusicLrcContainerForInterior::createNoLrcCurrentInfo(), MusicFunctionToolBoxTopWidget::MusicFunctionToolBoxTopWidget(), and MusicOpenFileWidget::MusicOpenFileWidget().
void MusicUtils::Widget::setTransparent (QWidget * widget, int alpha)
Set widget transparent.
Definition at line 96 of file musicwidgetutils.cpp.
Referenced by MusicAbstractTableWidget::MusicAbstractTableWidget(), MusicCloudDownloadTableWidget::MusicCloudDownloadTableWidget(), MusicCloudManagerTableWidget::MusicCloudManagerTableWidget(), MusicCloudUploadTableWidget::MusicCloudUploadTableWidget(), MusicDownloadBatchTableWidget::MusicDownloadBatchTableWidget(), MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget(), MusicDownloadTableWidget::MusicDownloadTableWidget(), MusicFillItemTableWidget::MusicFillItemTableWidget(), MusicLocalSongsInfoTableWidget::MusicLocalSongsInfoTableWidget(), MusicLocalSongsTableWidget::MusicLocalSongsTableWidget(), MusicQualityChoiceTableWidget::MusicQualityChoiceTableWidget(), MusicSongSearchPopTableWidget::MusicSongSearchPopTableWidget(), MusicSongsListPlayedTableWidget::MusicSongsListPlayedTableWidget(), MusicSongsListTableWidget::MusicSongsListTableWidget(), and MusicWebFMRadioWidget::MusicWebFMRadioWidget().
void MusicUtils::Widget::widgetToRound (QWidget * widget, int ratioX, int ratioY)
Set widget to round by ratioX and ratioY.
Definition at line 119 of file musicwidgetutils.cpp.
References MusicUtils::Image::generateMask().