TTKMusicPlayer: MusicRulesAnalysis Class Reference
MusicRulesAnalysis Class Reference
The class of the file name rules analysis.
#include <musicrulesanalysis.h>
Static Public Member Functions
static QStringList rules ()
static QString rule (int index)
static QString parse (const TTK::MusicSongInformation &info, const QString &value)
Detailed Description
The class of the file name rules analysis.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicrulesanalysis.h.
Member Function Documentation
QString MusicRulesAnalysis::parse (const TTK::MusicSongInformation & info, const QString & value) static
Parse rule value string to normal.
Definition at line 31 of file musicrulesanalysis.cpp.
References TTKTime::formatDuration(), TTK::MusicSongInformation::m_albumName, TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_duration, TTK::MusicSongInformation::m_songName, TTK::MusicSongInformation::m_trackNumber, TTK::MusicSongInformation::m_year, RULE_ALBUM, RULE_ARTIST, RULE_DURAION, RULE_TITLE, RULE_TRACK, RULE_YEAR, and TTK_DN_S2MS.
Referenced by MusicDownloadWidget::addCellItems(), MusicDownloadWidget::startToRequestMovie(), and MusicDownloadWidget::startToRequestMusic().
QString MusicRulesAnalysis::rule (int index) static
Get rule filter by index.
Definition at line 17 of file musicrulesanalysis.cpp.
References RULE_ALBUM, RULE_ARTIST, RULE_DURAION, RULE_TITLE, RULE_TRACK, and RULE_YEAR.
Referenced by MusicSettingWidget::downloadFileNameRuleChanged().
QStringList MusicRulesAnalysis::rules () static
Get all rule filters.
Definition at line 11 of file musicrulesanalysis.cpp.
Referenced by MusicSettingWidget::initDownloadWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsKits/musicrulesanalysis.h
TTKModule/TTKCore/musicToolsKits/musicrulesanalysis.cpp