TTKMusicplayer: MusicLrcFloatPhotoWidget Class Reference
MusicLrcFloatPhotoWidget Class Reference
The class of the lrc photo float widget.
#include <musiclrcfloatphotowidget.h>
Public Slots
void show ()
void close ()
void parentClose ()
void confirmButtonClicked ()
void photoPrevious ()
void photoNext ()
void artistNameChanged ()
void sendUserSelectArtBackground (int index)
void userSelectCheckBoxChecked (int index)
void selectAllStateChanged (bool state)
Public Member Functions
MusicLrcFloatPhotoWidget (QWidget *parent=nullptr)
~MusicLrcFloatPhotoWidget ()
virtual void resizeWindow (int width, int height) overridefinal
Public Member Functions inherited from MusicAbstractFloatWidget
MusicAbstractFloatWidget (QWidget *parent=nullptr)
~MusicAbstractFloatWidget ()
void setBlockAnimation (bool b)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void enterEvent (QtEnterEvent *) overridefinal
virtual void leaveEvent (QEvent *) overridefinal
void showPhoto () const
Protected Member Functions inherited from MusicAbstractFloatWidget
virtual void contextMenuEvent (QContextMenuEvent *) overridefinal
virtual void mousePressEvent (QMouseEvent *) overridefinal
virtual void mouseMoveEvent (QMouseEvent *) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *) overridefinal
void animationIn ()
void animationOut ()
Protected Attributes
int m_currentIndex
TTKIntSet m_selectNum
QStringList m_artPath
QWidget * m_filmBackgroundWidget
QCheckBox * m_checkBox
QPushButton * m_previous
QPushButton * m_next
QPushButton * m_confirmButton
QList< MusicLrcFloatPhotoItem * > m_planes
Protected Attributes inherited from MusicAbstractFloatWidget
QPropertyAnimation * m_animation
QRect m_rectIn
QRect m_rectOut
bool m_blockAnimation
Detailed Description
The class of the lrc photo float widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 100 of file musiclrcfloatphotowidget.h.
Constructor & Destructor Documentation
MusicLrcFloatPhotoWidget::MusicLrcFloatPhotoWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 122 of file musiclrcfloatphotowidget.cpp.
References artistNameChanged(), confirmButtonClicked(), G_BACKGROUND_PTR, m_checkBox, m_confirmButton, m_currentIndex, m_filmBackgroundWidget, m_next, m_planes, m_previous, MusicUIObject::MQSSBackgroundStyle08, MusicUIObject::MQSSBackgroundStyle09, MusicUIObject::MQSSBorderStyle01, MusicUIObject::MQSSCheckBoxStyle01, MusicUIObject::MQSSInteriorFloatSetting, MusicUIObject::MQSSPushButtonStyle06, photoNext(), photoPrevious(), selectAllStateChanged(), sendUserSelectArtBackground(), and userSelectCheckBoxChecked().
MusicLrcFloatPhotoWidget::~MusicLrcFloatPhotoWidget ()
Definition at line 184 of file musiclrcfloatphotowidget.cpp.
References m_checkBox, m_confirmButton, m_filmBackgroundWidget, m_next, m_planes, and m_previous.
Member Function Documentation
void MusicLrcFloatPhotoWidget::artistNameChanged () slot
Update current artist pic.
Definition at line 260 of file musiclrcfloatphotowidget.cpp.
References close(), G_BACKGROUND_PTR, m_artPath, m_currentIndex, and m_selectNum.
Referenced by MusicLrcFloatPhotoWidget().
void MusicLrcFloatPhotoWidget::close () slot
Override close function.
Definition at line 213 of file musiclrcfloatphotowidget.cpp.
References MusicAbstractFloatWidget::animationIn(), MusicAbstractFloatWidget::m_animation, and parentClose().
Referenced by artistNameChanged(), and confirmButtonClicked().
void MusicLrcFloatPhotoWidget::confirmButtonClicked () slot
Confirm button clicked that show selected artist pics.
Definition at line 219 of file musiclrcfloatphotowidget.cpp.
References close(), G_BACKGROUND_PTR, m_artPath, and m_selectNum.
Referenced by MusicLrcFloatPhotoWidget().
virtual void MusicLrcFloatPhotoWidget::enterEvent (QtEnterEvent * event) inline final override protected virtual
Override the widget event.
Reimplemented from MusicAbstractFloatWidget.
Definition at line 163 of file musiclrcfloatphotowidget.h.
virtual void MusicLrcFloatPhotoWidget::leaveEvent (QEvent *) inline final override protected virtual
Reimplemented from MusicAbstractFloatWidget.
Definition at line 164 of file musiclrcfloatphotowidget.h.
void MusicLrcFloatPhotoWidget::paintEvent (QPaintEvent * event) final override protected virtual
Override the widget event.
Definition at line 338 of file musiclrcfloatphotowidget.cpp.
References PHOTO_BACKGROUNDG_WIDTH.
void MusicLrcFloatPhotoWidget::parentClose () inline slot
Close current widget.
Definition at line 128 of file musiclrcfloatphotowidget.h.
Referenced by close().
void MusicLrcFloatPhotoWidget::photoNext () slot
To selected next artist pic.
Definition at line 277 of file musiclrcfloatphotowidget.cpp.
References m_artPath, m_currentIndex, PHOTO_PERLINE, and showPhoto().
Referenced by MusicLrcFloatPhotoWidget().
void MusicLrcFloatPhotoWidget::photoPrevious () slot
To selected previous artist pic.
Definition at line 251 of file musiclrcfloatphotowidget.cpp.
References m_currentIndex, and showPhoto().
Referenced by MusicLrcFloatPhotoWidget().
void MusicLrcFloatPhotoWidget::resizeWindow (int width, int height) final override virtual
Resize window bound by given width and height.
Implements MusicAbstractFloatWidget.
Definition at line 194 of file musiclrcfloatphotowidget.cpp.
References m_checkBox, m_confirmButton, m_filmBackgroundWidget, MusicAbstractFloatWidget::m_rectIn, and MusicAbstractFloatWidget::m_rectOut.
Referenced by MusicLrcFloatWidget::resizeWindow().
void MusicLrcFloatPhotoWidget::selectAllStateChanged (bool state) slot
User select check box checked by state.
Definition at line 318 of file musiclrcfloatphotowidget.cpp.
References m_artPath, m_planes, m_selectNum, and showPhoto().
Referenced by MusicLrcFloatPhotoWidget().
void MusicLrcFloatPhotoWidget::sendUserSelectArtBackground (int index) slot
User selected the plane pic.
Definition at line 292 of file musiclrcfloatphotowidget.cpp.
References G_BACKGROUND_PTR, m_currentIndex, and PHOTO_PERLINE.
Referenced by MusicLrcFloatPhotoWidget().
void MusicLrcFloatPhotoWidget::show () slot
Override show function.
Definition at line 206 of file musiclrcfloatphotowidget.cpp.
References MusicAbstractFloatWidget::animationOut(), and showPhoto().
void MusicLrcFloatPhotoWidget::showPhoto () const protected
Show all artist pics in displaying.
Definition at line 230 of file musiclrcfloatphotowidget.cpp.
References m_artPath, m_currentIndex, m_next, m_planes, m_previous, m_selectNum, and PHOTO_PERLINE.
Referenced by photoNext(), photoPrevious(), selectAllStateChanged(), and show().
void MusicLrcFloatPhotoWidget::userSelectCheckBoxChecked (int index) slot
User select check box checked by index.
Definition at line 297 of file musiclrcfloatphotowidget.cpp.
References m_checkBox, m_currentIndex, m_planes, m_selectNum, and PHOTO_PERLINE.
Referenced by MusicLrcFloatPhotoWidget().
Member Data Documentation
QStringList MusicLrcFloatPhotoWidget::m_artPath protected
Definition at line 172 of file musiclrcfloatphotowidget.h.
Referenced by artistNameChanged(), confirmButtonClicked(), photoNext(), selectAllStateChanged(), and showPhoto().
QCheckBox* MusicLrcFloatPhotoWidget::m_checkBox protected
Definition at line 174 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoWidget(), resizeWindow(), userSelectCheckBoxChecked(), and ~MusicLrcFloatPhotoWidget().
QPushButton * MusicLrcFloatPhotoWidget::m_confirmButton protected
Definition at line 175 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoWidget(), resizeWindow(), and ~MusicLrcFloatPhotoWidget().
int MusicLrcFloatPhotoWidget::m_currentIndex protected
Definition at line 170 of file musiclrcfloatphotowidget.h.
Referenced by artistNameChanged(), MusicLrcFloatPhotoWidget(), photoNext(), photoPrevious(), sendUserSelectArtBackground(), showPhoto(), and userSelectCheckBoxChecked().
QWidget* MusicLrcFloatPhotoWidget::m_filmBackgroundWidget protected
Definition at line 173 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoWidget(), resizeWindow(), and ~MusicLrcFloatPhotoWidget().
QPushButton * MusicLrcFloatPhotoWidget::m_next protected
Definition at line 175 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoWidget(), showPhoto(), and ~MusicLrcFloatPhotoWidget().
QList<MusicLrcFloatPhotoItem*> MusicLrcFloatPhotoWidget::m_planes protected
Definition at line 176 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoWidget(), selectAllStateChanged(), showPhoto(), userSelectCheckBoxChecked(), and ~MusicLrcFloatPhotoWidget().
QPushButton* MusicLrcFloatPhotoWidget::m_previous protected
Definition at line 175 of file musiclrcfloatphotowidget.h.
Referenced by MusicLrcFloatPhotoWidget(), showPhoto(), and ~MusicLrcFloatPhotoWidget().
TTKIntSet MusicLrcFloatPhotoWidget::m_selectNum protected
Definition at line 171 of file musiclrcfloatphotowidget.h.
Referenced by artistNameChanged(), confirmButtonClicked(), selectAllStateChanged(), showPhoto(), and userSelectCheckBoxChecked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatphotowidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatphotowidget.cpp