TTKMusicplayer: MusicXmlNodeHelper Class Reference
MusicXmlNodeHelper Class Reference
The class of the xml node hepler.
#include <musicabstractxml.h>
Public Member Functions
MusicXmlNodeHelper (const QDomNode &root)
void load ()
bool hasNext ()
QDomNode next () const
QString nodeName (const QString &name) const
Private Attributes
QDomNode m_root
QDomNode m_current
QSet< QString > m_nodeNames
Detailed Description
The class of the xml node hepler.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 41 of file musicabstractxml.h.
Constructor & Destructor Documentation
MusicXmlNodeHelper::MusicXmlNodeHelper (const QDomNode & root) explicit
Object contsructor.
Definition at line 3 of file musicabstractxml.cpp.
References m_current, and m_root.
Member Function Documentation
bool MusicXmlNodeHelper::hasNext ()
Check xml has next node.
Definition at line 20 of file musicabstractxml.cpp.
References hasNext(), m_current, and m_root.
Referenced by hasNext(), and load().
void MusicXmlNodeHelper::load ()
Load xml node helper.
Definition at line 9 of file musicabstractxml.cpp.
References hasNext(), m_current, and m_nodeNames.
Referenced by MusicASXConfigManager::readBuffer(), MusicXSPFConfigManager::readBuffer(), and MusicWPLConfigManager::readBuffer().
QDomNode MusicXmlNodeHelper::next () const
Get xml next node.
Definition at line 59 of file musicabstractxml.cpp.
References m_current.
QString MusicXmlNodeHelper::nodeName (const QString & name) const
Get match node name case insensitive.
Definition at line 64 of file musicabstractxml.cpp.
References m_nodeNames, and name.
Member Data Documentation
QDomNode MusicXmlNodeHelper::m_current private
Definition at line 68 of file musicabstractxml.h.
Referenced by hasNext(), load(), MusicXmlNodeHelper(), and next().
QSet<QString> MusicXmlNodeHelper::m_nodeNames private
Definition at line 69 of file musicabstractxml.h.
Referenced by load(), and nodeName().
QDomNode MusicXmlNodeHelper::m_root private
Definition at line 68 of file musicabstractxml.h.
Referenced by hasNext(), and MusicXmlNodeHelper().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicabstractxml.h
TTKModule/TTKCore/musicCoreKits/musicabstractxml.cpp