TTKMusicplayer: MusicLicenseCore Class Reference
MusicLicenseCore Class Reference
The class of the license core module.
#include <musiclicensecore.h>
Public Member Functions
MusicLicenseCore (QObject *parent=0)
bool checkLicense (const QString &str)
QString getCharacteristicString ()
QString getCharacteristicStringNormal ()
QString getEncodeKey (const QString &key)
Private Member Functions
QStringList getCharacteristicStrings ()
QString splitString (const QByteArray &data, const QByteArray &key)
Detailed Description
The class of the license core module.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musiclicensecore.h.
Constructor & Destructor Documentation
MusicLicenseCore::MusicLicenseCore (QObject * parent = 0) explicit
Object contsructor.
Definition at line 10 of file musiclicensecore.cpp.
Member Function Documentation
bool MusicLicenseCore::checkLicense (const QString & str)
Check license string.
Definition at line 21 of file musiclicensecore.cpp.
References getCharacteristicStrings(), getEncodeKey(), and key.
QString MusicLicenseCore::getCharacteristicString ()
Get characteristic string.
Definition at line 33 of file musiclicensecore.cpp.
References splitString(), and VALUE0.
QString MusicLicenseCore::getCharacteristicStringNormal ()
Get characteristic normal string.
Definition at line 44 of file musiclicensecore.cpp.
References MusicUtils::Algorithm::hmackSha1(), and VALUE0.
Referenced by MusicSongListSharingWidget::createWriteKey().
QStringList MusicLicenseCore::getCharacteristicStrings () private
Get characteristic strings.
Definition at line 55 of file musiclicensecore.cpp.
References splitString(), and VALUE0.
Referenced by checkLicense().
QString MusicLicenseCore::getEncodeKey (const QString & key)
Get encode key.
Definition at line 16 of file musiclicensecore.cpp.
References splitString(), and VALUE1.
Referenced by checkLicense().
QString MusicLicenseCore::splitString (const QByteArray & data, const QByteArray & key) private
Split hmac string.
Definition at line 65 of file musiclicensecore.cpp.
References MusicUtils::Algorithm::hmackSha1().
Referenced by getCharacteristicString(), getCharacteristicStrings(), and getEncodeKey().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musiclicensecore.h
TTKModule/TTKCore/musicCoreKits/musiclicensecore.cpp