TTKMusicPlayer: TTKLogOutput Class Reference
TTKLogOutput Class Reference
Public Member Functions
void initialize (const QString &module)
void install ()
void uninstall ()
void setMaxSize (size_t maxSize) noexcept
void setExpireSecond (size_t maxSecond) noexcept
void setOutputPath (const QString &dir) noexcept
Static Public Member Functions
static void loggerHandler (QtMsgType type, const char *message)
Private Member Functions
TTKLogOutput ()
~TTKLogOutput ()
void open ()
void save (const QString &message)
void write (QtMsgType type, const QMessageLogContext &context, const QString &message)
Private Attributes
QFile m_file
qint64 m_maxSize
qint64 m_maxSecond
QString m_module
QString m_dateTime
QString m_outputDir
QMutex m_mutex
QtMessageHandler m_defaultHandler
Detailed Description
Definition at line 13 of file ttklogoutput.cpp.
Constructor & Destructor Documentation
TTKLogOutput::TTKLogOutput () private
Object constructor.
Definition at line 85 of file ttklogoutput.cpp.
TTKLogOutput::~TTKLogOutput () private
Object destructor.
Definition at line 102 of file ttklogoutput.cpp.
References m_file.
Member Function Documentation
void TTKLogOutput::initialize (const QString & module)
Initiailize log module.
Definition at line 110 of file ttklogoutput.cpp.
References m_module.
void TTKLogOutput::install ()
Install log output handler.
Definition at line 146 of file ttklogoutput.cpp.
References loggerHandler(), m_defaultHandler, m_maxSecond, m_outputDir, open(), qInstallMessageHandler, and removeFiles().
void TTKLogOutput::loggerHandler (QtMsgType type, const char * message) static
Log output handler.
Definition at line 200 of file ttklogoutput.cpp.
References TTKSingleton< T >::instance(), and message().
Referenced by install().
void TTKLogOutput::open () private
Open log output file.
Definition at line 206 of file ttklogoutput.cpp.
References m_dateTime, m_file, m_maxSize, m_module, m_outputDir, TTK_DATE_FORMAT, and TTK_ERROR_STREAM.
Referenced by install(), and write().
void TTKLogOutput::save (const QString & message) private
Save log output file.
Definition at line 229 of file ttklogoutput.cpp.
References m_file, and TTK_WLINEFEED.
Referenced by write().
void TTKLogOutput::setExpireSecond (size_t maxSecond) noexcept
Remove log file after max second.
Definition at line 184 of file ttklogoutput.cpp.
void TTKLogOutput::setMaxSize (size_t maxSize) noexcept
Set max size for log file.
Definition at line 179 of file ttklogoutput.cpp.
void TTKLogOutput::setOutputPath (const QString & dir) noexcept
Set log output dir path.
Definition at line 189 of file ttklogoutput.cpp.
References TTK_SEPARATOR.
void TTKLogOutput::uninstall ()
Uninstall log output handler.
Definition at line 168 of file ttklogoutput.cpp.
References m_defaultHandler, m_file, and qInstallMessageHandler.
void TTKLogOutput::write (QtMsgType type, const QMessageLogContext & context, const QString & message) private
Write log output file.
Definition at line 239 of file ttklogoutput.cpp.
References m_dateTime, m_file, m_maxSize, m_mutex, open(), QtNamespace, save(), and TTK_DATE_FORMAT.
Member Data Documentation
QString TTKLogOutput::m_dateTime private
Definition at line 78 of file ttklogoutput.cpp.
Referenced by open(), and write().
QtMessageHandler TTKLogOutput::m_defaultHandler private
Definition at line 80 of file ttklogoutput.cpp.
Referenced by install(), and uninstall().
QFile TTKLogOutput::m_file private
Definition at line 76 of file ttklogoutput.cpp.
Referenced by open(), save(), uninstall(), write(), and ~TTKLogOutput().
qint64 TTKLogOutput::m_maxSecond private
Definition at line 77 of file ttklogoutput.cpp.
Referenced by install().
qint64 TTKLogOutput::m_maxSize private
Definition at line 77 of file ttklogoutput.cpp.
Referenced by open(), and write().
QString TTKLogOutput::m_module private
Definition at line 78 of file ttklogoutput.cpp.
Referenced by initialize(), and open().
QMutex TTKLogOutput::m_mutex private
Definition at line 79 of file ttklogoutput.cpp.
Referenced by write().
QString TTKLogOutput::m_outputDir private
Definition at line 78 of file ttklogoutput.cpp.
Referenced by install(), and open().
The documentation for this class was generated from the following file:
TTKCommon/TTKLibrary/ttklogoutput.cpp