TTKMusicplayer: MusicDownloadQueueCache Class Reference
MusicDownloadQueueCache Class Reference
The class to download data from cache queue.
#include <musicdownloadqueuecache.h>
Public Slots
virtual void downLoadFinished () override
void readyReadSlot ()
void errorSlot (QNetworkReply::NetworkError code)
Public Slots inherited from MusicDownLoadThreadAbstract
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownloadQueueCache (Download_Type type, QObject *parent=0)
MusicDownloadQueueCache (const MusicDownloadQueueData &data, Download_Type type, QObject *parent=0)
MusicDownloadQueueCache (const MusicDownloadQueueDatas &datas, Download_Type type, QObject *parent=0)
~MusicDownloadQueueCache ()
void addImageQueue (const MusicDownloadQueueDatas &datas)
virtual void startToDownload () override
void abort ()
Public Member Functions inherited from MusicDownLoadThreadAbstract
MusicDownLoadThreadAbstract (const QString &url, const QString &save, Download_Type type, QObject *parent=0)
virtual ~MusicDownLoadThreadAbstract ()
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Member Functions
void startDownload (const QString &url)
void startOrderImageQueue ()
Protected Member Functions inherited from MusicDownLoadThreadAbstract
QString transferData () const
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes
bool m_isDownload
bool m_isAbort
QList< MusicDownloadQueueData > m_imageQueue
QNetworkRequest * m_request
Protected Attributes inherited from MusicDownLoadThreadAbstract
QFile * m_file
QString m_url
QString m_savePathName
Download_Type m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_timer
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicDownLoadThreadAbstract
enum Download_Type {
Download_Music, Download_Lrc, Download_SmlBG, Download_BigBG,
Download_Video, Download_Other
}
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Detailed Description
The class to download data from cache queue.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicdownloadqueuecache.h.
Constructor & Destructor Documentation
MusicDownloadQueueCache::MusicDownloadQueueCache (Download_Type type, QObject * parent = 0) explicit
Object contsructor.
Definition at line 6 of file musicdownloadqueuecache.cpp.
MusicDownloadQueueCache::MusicDownloadQueueCache (const MusicDownloadQueueData & data, Download_Type type, QObject * parent = 0)
Object contsructor.
Definition at line 12 of file musicdownloadqueuecache.cpp.
References getClassName(), m_isAbort, m_isDownload, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, m_request, MusicNetworkAbstract::setSslConfiguration(), and MusicDownLoadThreadAbstract::sslErrors().
MusicDownloadQueueCache::MusicDownloadQueueCache (const MusicDownloadQueueDatas & datas, Download_Type type, QObject * parent = 0)
Object contsructor.
Definition at line 30 of file musicdownloadqueuecache.cpp.
References addImageQueue().
MusicDownloadQueueCache::~MusicDownloadQueueCache ()
Definition at line 36 of file musicdownloadqueuecache.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), and m_request.
Member Function Documentation
void MusicDownloadQueueCache::abort ()
Abort current download thread.
Definition at line 59 of file musicdownloadqueuecache.cpp.
References MusicDownLoadThreadAbstract::m_file, m_isAbort, m_isDownload, and MusicNetworkAbstract::m_reply.
Referenced by MusicBackgroundRemoteWidget::abort(), and MusicBackgroundThunderWidget::buttonClicked().
void MusicDownloadQueueCache::addImageQueue (const MusicDownloadQueueDatas & datas)
Add image download url and save path to download queue.
Definition at line 73 of file musicdownloadqueuecache.cpp.
References m_imageQueue.
Referenced by MusicDownloadQueueCache(), and MusicBackgroundRemoteWidget::startToDownload().
void MusicDownloadQueueCache::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 120 of file musicdownloadqueuecache.cpp.
References MusicNetworkAbstract::downLoadDataChanged(), MusicDownLoadThreadAbstract::m_file, m_imageQueue, m_isAbort, m_isDownload, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, m_request, MusicDownLoadThreadAbstract::m_timer, and startOrderImageQueue().
Referenced by startDownload().
void MusicDownloadQueueCache::errorSlot (QNetworkReply::NetworkError code) slot
Download reply error.
Definition at line 149 of file musicdownloadqueuecache.cpp.
References MusicDownLoadThreadAbstract::m_file, m_isAbort, M_LOGGER_ERROR, MusicNetworkAbstract::m_reply, and startToDownload().
Referenced by startDownload().
QString MusicDownloadQueueCache::getClassName () static
Get class object name.
Definition at line 46 of file musicdownloadqueuecache.cpp.
Referenced by MusicDownloadQueueCache().
void MusicDownloadQueueCache::readyReadSlot () slot
Download received data ready.
Definition at line 138 of file musicdownloadqueuecache.cpp.
References MusicDownLoadThreadAbstract::m_file, and MusicNetworkAbstract::m_reply.
Referenced by startDownload().
void MusicDownloadQueueCache::startDownload (const QString & url) protected
Start to download data from url.
Definition at line 94 of file musicdownloadqueuecache.cpp.
References downLoadFinished(), errorSlot(), MusicDownLoadThreadAbstract::m_file, m_imageQueue, m_isDownload, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, m_request, MusicDownLoadThreadAbstract::m_timer, MT_S2MS, and readyReadSlot().
Referenced by startOrderImageQueue().
void MusicDownloadQueueCache::startOrderImageQueue () protected
Start to download data in order.
Definition at line 78 of file musicdownloadqueuecache.cpp.
References MusicNetworkAbstract::downLoadDataChanged(), m_imageQueue, M_NETWORK_PTR, and startDownload().
Referenced by downLoadFinished(), and startToDownload().
void MusicDownloadQueueCache::startToDownload () override virtual
Start to download data.
Implements MusicDownLoadThreadAbstract.
Definition at line 51 of file musicdownloadqueuecache.cpp.
References m_imageQueue, and startOrderImageQueue().
Referenced by errorSlot(), and MusicBackgroundRemoteWidget::startToDownload().
Member Data Documentation
QList<MusicDownloadQueueData> MusicDownloadQueueCache::m_imageQueue protected
Definition at line 102 of file musicdownloadqueuecache.h.
Referenced by addImageQueue(), downLoadFinished(), startDownload(), startOrderImageQueue(), and startToDownload().
bool MusicDownloadQueueCache::m_isAbort protected
Definition at line 101 of file musicdownloadqueuecache.h.
Referenced by abort(), downLoadFinished(), errorSlot(), and MusicDownloadQueueCache().
bool MusicDownloadQueueCache::m_isDownload protected
Definition at line 101 of file musicdownloadqueuecache.h.
Referenced by abort(), downLoadFinished(), MusicDownloadQueueCache(), and startDownload().
QNetworkRequest* MusicDownloadQueueCache::m_request protected
Definition at line 103 of file musicdownloadqueuecache.h.
Referenced by downLoadFinished(), MusicDownloadQueueCache(), startDownload(), and ~MusicDownloadQueueCache().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadqueuecache.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadqueuecache.cpp