TTKMusicPlayer: MusicFillItemTableWidget Class Reference
MusicFillItemTableWidget Class Reference
The class of the fill item table widget.
#include <musicfillitemtablewidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
TTKIntList uncheckedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList selectedIndexList () const
Protected Attributes
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const
Detailed Description
The class of the fill item table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicfillitemtablewidget.h.
Constructor & Destructor Documentation
MusicFillItemTableWidget::MusicFillItemTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file musicfillitemtablewidget.cpp.
References TTK::UI::CheckBoxStyle01, m_checkBoxDelegate, TTKAbstractItemDelegate::setStyleSheet(), TTK::Widget::setTransparent(), and TTK::UI::TableWidgetStyle02.
MusicFillItemTableWidget::~MusicFillItemTableWidget ()
Object destructor.
Definition at line 17 of file musicfillitemtablewidget.cpp.
References m_checkBoxDelegate, and TTKAbstractTableWidget::removeItems().
Member Function Documentation
TTKIntList MusicFillItemTableWidget::checkedIndexList () const
Get checked items.
Definition at line 23 of file musicfillitemtablewidget.cpp.
References TTK_CHECKED_ROLE.
Referenced by MusicSongSearchOnlineWidget::buttonClicked(), MusicItemQueryTableWidget::downloadBatchData(), and MusicItemQueryTableWidget::downloadDataFrom().
void MusicFillItemTableWidget::checkedItemsState (bool checked) slot
Checked items state.
Definition at line 72 of file musicfillitemtablewidget.cpp.
References TTK_CHECKED_ROLE.
Referenced by MusicAbstractItemQueryWidget::playAllButtonClicked().
void MusicFillItemTableWidget::checkedItemsStatus (bool checked) slot
Checked items status.
Definition at line 82 of file musicfillitemtablewidget.cpp.
References TTK_CHECKED_ROLE.
Referenced by MusicFileAssociationTableWidget::checkedItemsStatus().
void MusicFillItemTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 51 of file musicfillitemtablewidget.cpp.
References TTKAbstractTableWidget::m_previousClickRow, TTK_CHECKED_ROLE, and TTKStaticCast.
Referenced by MusicSongCheckToolsRenameTableWidget::itemCellClicked(), MusicQueryTableWidget::itemCellClicked(), MusicSongCheckToolsDuplicateTableWidget::itemCellClicked(), MusicSongCheckToolsQualityTableWidget::itemCellClicked(), and MusicLrcPosterTableWidget::itemCellClicked().
TTKIntList MusicFillItemTableWidget::uncheckedIndexList () const
Get unchecked items.
Definition at line 37 of file musicfillitemtablewidget.cpp.
References TTK_CHECKED_ROLE.
Referenced by MusicFileAssociationTableWidget::uncheckedDataList().
Member Data Documentation
TTKCheckBoxItemDelegate* MusicFillItemTableWidget::m_checkBoxDelegate protected
Definition at line 68 of file musicfillitemtablewidget.h.
Referenced by MusicConnectTransferTableWidget::MusicConnectTransferTableWidget(), MusicFillItemTableWidget(), and ~MusicFillItemTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicfillitemtablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicfillitemtablewidget.cpp