TTKMusicPlayer: MusicProcessServer Class Reference
MusicProcessServer Class Reference
The class of the process server.
#include <musicprocessmanager.h>
Public Member Functions
MusicProcessServer (QObject *parent=nullptr)
~MusicProcessServer ()
void run (const QStringList &args) const
Private Slots
void timeout ()
Private Attributes
QTimer m_timer
QSharedMemory m_memory
Detailed Description
The class of the process server.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 44 of file musicprocessmanager.h.
Constructor & Destructor Documentation
MusicProcessServer::MusicProcessServer (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 28 of file musicprocessmanager.cpp.
References m_memory, m_timer, MEMORY_KEY, MEMORY_SIZE, timeout(), and TTK_DN_S2MS.
MusicProcessServer::~MusicProcessServer ()
Object destructor.
Definition at line 44 of file musicprocessmanager.cpp.
References m_memory, and m_timer.
Member Function Documentation
void MusicProcessServer::run (const QStringList & args) const
Run.
Definition at line 50 of file musicprocessmanager.cpp.
References TTKCommandLineParser::addOption(), MusicApplication::importSongsByOutside(), MusicApplication::instance(), TTKCommandLineParser::isSet(), TTKCommandLineParser::process(), TTKCommandLineParser::showHelp(), TTK_INFO_STREAM, and TTKCommandLineParser::value().
Referenced by main(), and timeout().
void MusicProcessServer::timeout () private slot
Thread run now.
Definition at line 93 of file musicprocessmanager.cpp.
References m_memory, MEMORY_SIZE, run(), and TTK_SPLITER.
Referenced by MusicProcessServer().
Member Data Documentation
QSharedMemory MusicProcessServer::m_memory private
Definition at line 71 of file musicprocessmanager.h.
Referenced by MusicProcessServer(), timeout(), and ~MusicProcessServer().
QTimer MusicProcessServer::m_timer private
Definition at line 70 of file musicprocessmanager.h.
Referenced by MusicProcessServer(), and ~MusicProcessServer().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicprocessmanager.h
TTKModule/TTKCore/musicCoreKits/musicprocessmanager.cpp