TTKMusicplayer: MusicDownLoadQueryMGMovieThread Class Reference
MusicDownLoadQueryMGMovieThread Class Reference
The class to migu mv query download data from net.
#include <musicdownloadquerymgmoviethread.h>
Public Slots
virtual void downLoadFinished () override
void pageDownLoadFinished ()
void singleDownLoadFinished ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadQueryMGMovieThread (QObject *parent=0)
QJson import.
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToPage (int offset) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicDownLoadQueryMovieThread
MusicDownLoadQueryMovieThread (QObject *parent=0)
virtual void startToSearch (const QString &movie)
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
const MusicObject::MusicSongInformations & getMusicSongInfos () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryMovieThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Member Functions
void readFromMusicMVAttribute (MusicObject::MusicSongInformation *info, int bitrate, bool more)
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
QString mapQueryServerString () const
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadQueryMovieThread
void createMovieInfoItem (const MusicPlaylistItem &item)
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItems (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadMGInterface
void makeTokenQueryUrl (QNetworkRequest *request, const QString &id)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bit, const QString &format, int type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info, const QString &param)
Detailed Description
The class to migu mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadquerymgmoviethread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryMGMovieThread::MusicDownLoadQueryMGMovieThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 10 of file musicdownloadquerymgmoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::m_queryServer.
Member Function Documentation
void MusicDownLoadQueryMGMovieThread::downLoadFinished () override virtual slot
Download data from net finished.
Clear origin items
Empty the last search to songsInfo
Get all the data obtained by request
extra yyt movie
Definition at line 92 of file musicdownloadquerymgmoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicSemaphoreLoop::exec(), getClassName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicNetworkAbstract::Init, MusicDownLoadQueryThreadAbstract::m_currentType, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_queryExtraMovie, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MB_500, MB_750, MusicDownLoadQueryThreadAbstract::MovieQuery, QJson::Parser::parse(), readFromMusicMVAttribute(), and MusicDownLoadQueryYYTThread::startToSearch().
Referenced by startToSearch().
QString MusicDownLoadQueryMGMovieThread::getClassName () static
Get class object name.
Definition at line 16 of file musicdownloadquerymgmoviethread.cpp.
Referenced by downLoadFinished(), pageDownLoadFinished(), singleDownLoadFinished(), startToPage(), startToSearch(), and startToSingleSearch().
void MusicDownLoadQueryMGMovieThread::pageDownLoadFinished () slot
Download page data from net finished.
Get all the data obtained by request
Definition at line 174 of file musicdownloadquerymgmoviethread.cpp.
References MusicDownLoadQueryMovieThread::createMovieInfoItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicPlaylistItem::m_coverUrl, MusicPlaylistItem::m_id, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicPlaylistItem::m_name, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_reply, MusicPlaylistItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToPage().
void MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute (MusicObject::MusicSongInformation * info, int bitrate, bool more) protected
Read mv tags(size) from query results.
Definition at line 257 of file musicdownloadquerymgmoviethread.cpp.
References MusicUtils::String::artistName(), MusicSemaphoreLoop::exec(), MusicUtils::Core::fileSuffix(), MusicDownLoadQueryThreadAbstract::findUrlFileSize(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicNetworkAbstract::m_manager, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongAttribute::m_url, MusicDownLoadMGInterface::makeTokenQueryUrl(), MB_500, MusicUtils::Algorithm::mdII(), MG_MV_INFO_URL, QJson::Parser::parse(), and MusicUtils::String::songName().
Referenced by downLoadFinished(), and singleDownLoadFinished().
void MusicDownLoadQueryMGMovieThread::singleDownLoadFinished () slot
Download single data from net finished.
Clear origin items
Empty the last search to songsInfo
Definition at line 226 of file musicdownloadquerymgmoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_searchText, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MB_500, MB_750, and readFromMusicMVAttribute().
Referenced by startToSingleSearch().
void MusicDownLoadQueryMGMovieThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 49 of file musicdownloadquerymgmoviethread.cpp.
References ALG_UA_KEY, MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicUtils::Algorithm::mdII(), MG_AR_MV_URL, MG_UA_URL_1, pageDownLoadFinished(), MusicNetworkAbstract::replyError(), and MusicUtils::Core::toUtf8().
void MusicDownLoadQueryMGMovieThread::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicDownLoadQueryThreadAbstract.
Definition at line 21 of file musicdownloadquerymgmoviethread.cpp.
References ALG_UA_KEY, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicDownLoadQueryThreadAbstract::m_currentType, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicUtils::Algorithm::mdII(), MG_SONG_SEARCH_URL, MG_UA_URL_1, MusicNetworkAbstract::replyError(), and MusicUtils::Core::toUtf8().
void MusicDownLoadQueryMGMovieThread::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicDownLoadQueryThreadAbstract.
Definition at line 77 of file musicdownloadquerymgmoviethread.cpp.
References MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_searchText, MT_MS, and singleDownLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/mg/musicdownloadquerymgmoviethread.h
TTKModule/TTKCore/musicNetworkKits/mg/musicdownloadquerymgmoviethread.cpp