TTKMusicPlayer: TTKModule/TTKCore/musicPlaylistKits/musicplaylistmanager.cpp File Reference
musicplaylistmanager.cpp File Reference
#include "musicplaylistmanager.h"
#include "musicasxconfigmanager.h"
#include "musicm3uconfigmanager.h"
#include "musicplsconfigmanager.h"
#include "musicwplconfigmanager.h"
#include "musicxspfconfigmanager.h"
#include "musictkplconfigmanager.h"
#include "musicdbplconfigmanager.h"
#include "musicfplconfigmanager.h"
#include "musiccsvconfigmanager.h"
#include "musictxtconfigmanager.h"
#include "musicjspfconfigmanager.h"
Functions
static bool readTKPLConfig (const QString &path, MusicSongItemList &items)
static bool writeTKPLConfig (const QString &path, const MusicSongItemList &item)
static bool readM3UConfig (const QString &path, MusicSongItemList &items)
static bool writeM3UConfig (const QString &path, const MusicSongItemList &item)
static bool readPLSConfig (const QString &path, MusicSongItemList &items)
static bool writePLSConfig (const QString &path, const MusicSongItemList &item)
static bool readWPLConfig (const QString &path, MusicSongItemList &items)
static bool writeWPLConfig (const QString &path, const MusicSongItemList &item)
static bool readXSPFConfig (const QString &path, MusicSongItemList &items)
static bool writeXSPFConfig (const QString &path, const MusicSongItemList &item)
static bool readJSPFConfig (const QString &path, MusicSongItemList &items)
static bool writeJSPFConfig (const QString &path, const MusicSongItemList &item)
static bool readASXConfig (const QString &path, MusicSongItemList &items)
static bool writeASXConfig (const QString &path, const MusicSongItemList &item)
static bool readFPLConfig (const QString &path, MusicSongItemList &items)
static bool readDBPLConfig (const QString &path, MusicSongItemList &items)
static bool readCSVConfig (const QString &path, MusicSongItemList &items)
static bool writeCSVConfig (const QString &path, const MusicSongItemList &item)
static bool readTXTConfig (const QString &path, MusicSongItemList &items)
static bool writeTXTConfig (const QString &path, const MusicSongItemList &item)
Function Documentation
static bool readASXConfig (const QString & path, MusicSongItemList & items) static
Definition at line 86 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicASXConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readCSVConfig (const QString & path, MusicSongItemList & items) static
Definition at line 110 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicCSVConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readDBPLConfig (const QString & path, MusicSongItemList & items) static
Definition at line 104 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicDBPLConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readFPLConfig (const QString & path, MusicSongItemList & items) static
Definition at line 98 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicFPLConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readJSPFConfig (const QString & path, MusicSongItemList & items) static
Definition at line 74 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicJSPFConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readM3UConfig (const QString & path, MusicSongItemList & items) static
Definition at line 26 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicM3UConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readPLSConfig (const QString & path, MusicSongItemList & items) static
Definition at line 38 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicPLSConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readTKPLConfig (const QString & path, MusicSongItemList & items) static
Definition at line 14 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicTKPLConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readTXTConfig (const QString & path, MusicSongItemList & items) static
Definition at line 122 of file musicplaylistmanager.cpp.
References TTKFileInterface::fromFile(), and MusicTXTConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readWPLConfig (const QString & path, MusicSongItemList & items) static
Definition at line 50 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicWPLConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool readXSPFConfig (const QString & path, MusicSongItemList & items) static
Definition at line 62 of file musicplaylistmanager.cpp.
References TTKAbstractXml::fromFile(), and MusicXSPFConfigManager::readBuffer().
Referenced by MusicPlaylistManager::readSongItems().
static bool writeASXConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 92 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicASXConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeCSVConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 116 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicCSVConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeJSPFConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 80 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicJSPFConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeM3UConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 32 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicM3UConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writePLSConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 44 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicPLSConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeTKPLConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 20 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicTKPLConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeTXTConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 128 of file musicplaylistmanager.cpp.
References TTKFileInterface::load(), and MusicTXTConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeWPLConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 56 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicWPLConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().
static bool writeXSPFConfig (const QString & path, const MusicSongItemList & item) static
Definition at line 68 of file musicplaylistmanager.cpp.
References TTKAbstractXml::load(), and MusicXSPFConfigManager::writeBuffer().
Referenced by MusicPlaylistManager::writeSongItem().