TTKMusicplayer: MusicDownLoadXMInterface Class Reference
MusicDownLoadXMInterface Class Reference
The class to xiami query download interface.
#include <musicdownloadxminterface.h>
Public Member Functions
void makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariant &key, const QString &quality, bool all)
void readFromMusicSongLrc (MusicObject::MusicSongInformation *info)
Detailed Description
The class to xiami query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 83 of file musicdownloadxminterface.h.
Member Function Documentation
void MusicDownLoadXMInterface::makeTokenQueryUrl (QNetworkRequest * request, const QString & query, const QString & type)
QJson import.
Make token query url string.
Definition at line 16 of file musicdownloadxminterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), MusicTime::timeStamp(), MusicUtils::Codec::toUtf8(), XM_COOKIE_URL, XM_QUERY_DATA_URL, XM_QUERY_URL, and XM_UA_URL_1.
Referenced by MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), readFromMusicSongLrc(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryXMThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), and MusicDownLoadQueryXMAlbumThread::startToSingleSearch().
void MusicDownLoadXMInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, int bitrate)
Read tags(size) from query results.
Definition at line 106 of file musicdownloadxminterface.cpp.
References MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongAttribute::m_url, and MusicUtils::Number::size2Label().
Referenced by MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), readFromMusicSongAttribute(), and MusicDownLoadQueryXMThread::singleDownLoadFinished().
void MusicDownLoadXMInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariant & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 127 of file musicdownloadxminterface.cpp.
References MB_128, MB_192, MB_32, MB_320, MB_500, readFromMusicSongAttribute(), and MusicUtils::Number::transfromBitrateToNormal().
void MusicDownLoadXMInterface::readFromMusicSongLrc (MusicObject::MusicSongInformation * info)
Read tags(lrc) from query results.
Definition at line 52 of file musicdownloadxminterface.cpp.
References MusicSemaphoreLoop::exec(), MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongInformation::m_songId, makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), XM_LRC_DATA_URL, and XM_LRC_URL.
Referenced by MusicDownLoadQueryXMThread::downLoadFinished(), and MusicDownLoadQueryXMThread::singleDownLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/xm/musicdownloadxminterface.h
TTKModule/TTKCore/musicNetworkKits/xm/musicdownloadxminterface.cpp