TTKMusicplayer: MusicUtils::String Namespace Reference
MusicUtils::String Namespace Reference
Functions
MUSIC_UTILS_EXPORT QString lrcPrefix ()
MUSIC_UTILS_EXPORT QString musicPrefix ()
MUSIC_UTILS_EXPORT QString StringPrefix (const QString &name)
MUSIC_UTILS_EXPORT QString StringPrefix (const QString &name, const QString &prefix)
MUSIC_UTILS_EXPORT QString StringSuffix (const QString &name)
MUSIC_UTILS_EXPORT QString StringSuffix (const QString &name, const QString &suffix)
MUSIC_UTILS_EXPORT QString StringSplite (const QString &name)
MUSIC_UTILS_EXPORT QString StringSplite (const QString &name, const QString &prefix, const QString &suffix)
MUSIC_UTILS_EXPORT QString splitLineKey ()
MUSIC_UTILS_EXPORT QString removeStringBy (const QString &value, const QString &key=" ")
MUSIC_UTILS_EXPORT QStringList splitString (const QString &value, const QString &key="-")
MUSIC_UTILS_EXPORT bool isChinese (const QChar &c)
MUSIC_UTILS_EXPORT QString artistName (const QString &value, const QString &key="-")
MUSIC_UTILS_EXPORT QString songName (const QString &value, const QString &key="-")
MUSIC_UTILS_EXPORT QStringList illegalCharacters ()
MUSIC_UTILS_EXPORT bool illegalCharactersCheck (const QString &value)
MUSIC_UTILS_EXPORT QString illegalCharactersReplaced (const QString &value)
MUSIC_UTILS_EXPORT QList< QColor > readColorConfig (const QString &value)
MUSIC_UTILS_EXPORT QString writeColorConfig (const QColor &color)
MUSIC_UTILS_EXPORT QString writeColorConfig (const QList< QColor > &colors)
Function Documentation
QString MusicUtils::String::artistName (const QString & value, const QString & key = "-")
Get song artist name.
Definition at line 110 of file musicstringutils.cpp.
References M_SETTING_PTR, MusicSettingManager::OtherSongFormat, and splitString().
Referenced by MusicQueryItemTableWidget::actionGroupClick(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicDownloadWidget::getMatchMusicSongInformation(), MusicSong::getMusicArtistFront(), MusicDownloadStatusObject::musicHaveNoLrcAlready(), MusicBackgroundManager::setArtistName(), MusicLrcMakerWidget::setCurrentSongName(), MusicSongSharingWidget::setData(), MusicRemoteWidgetForComplexStyle::setLabelText(), MusicSongsListPlayWidget::setParameter(), MusicAlbumFoundWidget::setSongName(), MusicArtistFoundWidget::setSongName(), and MusicSongsListPlayWidget::updateCurrentArtist().
QStringList MusicUtils::String::illegalCharacters ()
Illegal characters check.
Definition at line 148 of file musicstringutils.cpp.
Referenced by illegalCharactersCheck(), illegalCharactersReplaced(), and MusicSongsToolItemRenamedWidget::textChanged().
bool MusicUtils::String::illegalCharactersCheck (const QString & value)
Illegal characters check.
Definition at line 155 of file musicstringutils.cpp.
References illegalCharacters().
Referenced by MusicSongsToolItemRenamedWidget::textChanged().
QString MusicUtils::String::illegalCharactersReplaced (const QString & value)
Illegal characters replaced.
Definition at line 170 of file musicstringutils.cpp.
References illegalCharacters().
Referenced by MusicMVRadioProgramThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicRadioSongsThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicSongTag::findLegalDataString(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), and MusicDownLoadQueryWYMovieThread::startMVListQuery().
bool MusicUtils::String::isChinese (const QChar & c)
Check the given char is or not chinese character.
Definition at line 101 of file musicstringutils.cpp.
Referenced by MusicLrcPosterItemWidget::drawTheme16().
QString MusicUtils::String::lrcPrefix ()
Get lrc dir prefix path.
Definition at line 6 of file musicstringutils.cpp.
References MusicSettingManager::DownloadLrcPathDir, LRC_DIR_FULL, and M_SETTING_PTR.
Referenced by MusicLrcLocalLinkWidget::confirmButtonClicked(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicWebMusicRadioPlayWidget::lrcDownloadStateChanged(), MusicDownloadStatusObject::musicCheckHasLrcAlready(), MusicApplication::musicCurrentLrcUpdated(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicDownloadStatusObject::musicHaveNoLrcAlready(), MusicApplication::musicLoadCurrentSongLrc(), MusicSysConfigManager::readSysConfigData(), MusicLrcLocalLinkWidget::searchInLocalMLrc(), MusicLrcMakerWidget::setCurrentSongName(), and MusicWebMusicRadioPlayWidget::startToPlay().
QString MusicUtils::String::musicPrefix ()
Get music dir prefix path.
Definition at line 23 of file musicstringutils.cpp.
References MusicSettingManager::DownloadMusicPathDir, M_SETTING_PTR, and MUSIC_DIR_FULL.
Referenced by MusicDownloadAbstractTableWidget::createDownloadItem(), MusicCloudManagerTableWidget::downloadFileToServer(), and MusicSysConfigManager::readSysConfigData().
QList< QColor > MusicUtils::String::readColorConfig (const QString & value)
Transform colors string to color list.
Definition at line 186 of file musicstringutils.cpp.
Referenced by MusicSettingWidget::initControllerParameter(), MusicLrcContainerForWallpaper::setItemStyleSheet(), MusicSoundKMicroWidget::setItemStyleSheet(), MusicLrcContainerForInterior::setItemStyleSheet(), MusicLrcMakerWidget::setItemStyleSheet(), and MusicLrcContainer::setSettingParameter().
QString MusicUtils::String::removeStringBy (const QString & value, const QString & key = " ")
Remove given key in string, default is space.
Definition at line 80 of file musicstringutils.cpp.
QString MusicUtils::String::songName (const QString & value, const QString & key = "-")
Get song name.
Definition at line 129 of file musicstringutils.cpp.
References M_SETTING_PTR, MusicSettingManager::OtherSongFormat, and splitString().
Referenced by MusicQueryItemTableWidget::actionGroupClick(), MusicSongsListTableWidget::createContextMenu(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicDownloadWidget::getMatchMusicSongInformation(), MusicSong::getMusicArtistBack(), MusicDownloadStatusObject::musicHaveNoLrcAlready(), MusicSongsListTableWidget::musicSearchQuery(), MusicLrcMakerWidget::setCurrentSongName(), MusicRemoteWidgetForComplexStyle::setLabelText(), MusicSongsListPlayWidget::setParameter(), MusicRecommendFoundWidget::setSongName(), MusicSimilarFoundWidget::setSongName(), and MusicSongsListPlayWidget::updateCurrentArtist().
QString MusicUtils::String::splitLineKey ()
Get new line split string key.
Definition at line 71 of file musicstringutils.cpp.
Referenced by MusicEMOJILabelWidget::MusicEMOJILabelWidget(), and MusicLrcAnalysis::transKrcFileToTime().
QStringList MusicUtils::String::splitString (const QString & value, const QString & key = "-")
Get split string value.
Definition at line 91 of file musicstringutils.cpp.
Referenced by artistName(), MusicSongsListTableWidget::createContextMenu(), MusicDownloadStatusObject::musicHaveNoLrcAlready(), MusicSongsListTableWidget::musicSearchQuery(), MusicRemoteWidgetForComplexStyle::setLabelText(), MusicDownLoadQueryKGAlbumThread::singleDownLoadFinished(), and songName().
QString MusicUtils::String::StringPrefix (const QString & name)
Get string prefix path.
Definition at line 40 of file musicstringutils.cpp.
Referenced by StringSplite().
QString MusicUtils::String::StringPrefix (const QString & name, const QString & prefix)
Get string prefix path.
Definition at line 45 of file musicstringutils.cpp.
QString MusicUtils::String::StringSplite (const QString & name)
Get string splite path.
Definition at line 60 of file musicstringutils.cpp.
Referenced by MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), and MusicXMTextDownLoadThread::startToDownload().
QString MusicUtils::String::StringSplite (const QString & name, const QString & prefix, const QString & suffix)
Get string splite path.
Definition at line 65 of file musicstringutils.cpp.
References StringPrefix(), and StringSuffix().
QString MusicUtils::String::StringSuffix (const QString & name)
Get string suffix path.
Definition at line 50 of file musicstringutils.cpp.
Referenced by StringSplite().
QString MusicUtils::String::StringSuffix (const QString & name, const QString & suffix)
Get string suffix path.
Definition at line 55 of file musicstringutils.cpp.
QString MusicUtils::String::writeColorConfig (const QColor & color)
Transform color to color string.
Definition at line 202 of file musicstringutils.cpp.
Referenced by MusicSettingWidget::saveResults(), and writeColorConfig().
QString MusicUtils::String::writeColorConfig (const QList< QColor > & colors)
Transform color list to colors string.
Definition at line 207 of file musicstringutils.cpp.
References writeColorConfig().