TTKMusicPlayer: MusicVideoControlWidget Class Reference
MusicVideoControlWidget Class Reference
The class of the video controller.
#include <musicvideocontrolwidget.h>
Public Slots
void pushBarrageClicked ()
void sendBarrageClicked ()
Signals
void mediaUrlChanged (const QString &data)
void sliderValueChanged (int value)
void pushBarrageChanged (bool on)
void addBarrageChanged (const MusicBarrageRecord &record)
Public Member Functions
MusicVideoControlWidget (QWidget *parent=nullptr)
~MusicVideoControlWidget ()
void setValue (qint64 position) const
void durationChanged (qint64 duration) const
void setButtonStyle (bool style) const
void mediaChanged (const QString &url)
void setFixedSize (int w, int h)
void setQualityActionState ()
Private Member Functions
QWidget * createVideoBarrageWidget ()
Private Attributes
QLabel * m_timeLabel
QPushButton * m_playButton
MusicMovingLabelSlider * m_timeSlider
MusicVolumePopWidget * m_volumeButton
MusicVideoQualityPopWidget * m_qualityButton
bool m_pushBarrageOn
QPushButton * m_pushBarrage
QPushButton * m_barrageSend
MusicVideoBarrageStylePopWidget * m_menuBarrage
MusicSearchEdit * m_searchEdit
Detailed Description
The class of the video controller.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 36 of file musicvideocontrolwidget.h.
Constructor & Destructor Documentation
MusicVideoControlWidget::MusicVideoControlWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicvideocontrolwidget.cpp.
References createVideoBarrageWidget(), m_playButton, m_qualityButton, m_timeLabel, m_timeSlider, m_volumeButton, mediaUrlChanged(), MusicUIObject::MQSSBackgroundStyle06, MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSSliderStyle01, MusicUIObject::MQSSVideoBtnPlay, MUSIC_TIME_INIT, MusicVolumePopWidget::setValue(), and sliderValueChanged().
MusicVideoControlWidget::~MusicVideoControlWidget ()
Definition at line 66 of file musicvideocontrolwidget.cpp.
References m_barrageSend, m_menuBarrage, m_playButton, m_pushBarrage, m_qualityButton, m_searchEdit, m_timeLabel, m_timeSlider, and m_volumeButton.
Member Function Documentation
void MusicVideoControlWidget::addBarrageChanged (const MusicBarrageRecord & record) signal
Add barrage text to mv.
Referenced by sendBarrageClicked().
QWidget * MusicVideoControlWidget::createVideoBarrageWidget () private
Create video barrage widget.
Definition at line 139 of file musicvideocontrolwidget.cpp.
References m_barrageSend, m_menuBarrage, m_pushBarrage, m_pushBarrageOn, m_searchEdit, MusicUIObject::MQSSLineEditStyle04, MusicUIObject::MQSSVideoBtnBarrageSend, MusicUIObject::MQSSVideoBtnBarrageStyle, pushBarrageClicked(), and sendBarrageClicked().
Referenced by MusicVideoControlWidget().
void MusicVideoControlWidget::durationChanged (qint64 duration) const
Set current video duration.
Definition at line 87 of file musicvideocontrolwidget.cpp.
References m_timeLabel, m_timeSlider, TTKTime::msecTime2LabelJustified(), MT_S2MS, and MUSIC_TIME_INIT.
Referenced by MusicVideoView::durationChanged().
void MusicVideoControlWidget::mediaChanged (const QString & url)
Set current media url.
Definition at line 98 of file musicvideocontrolwidget.cpp.
References m_qualityButton, and MusicVideoQualityPopWidget::setQualityText().
Referenced by MusicVideoView::mediaChanged().
void MusicVideoControlWidget::mediaUrlChanged (const QString & data) signal
Set current media url by selected quality.
Referenced by MusicVideoControlWidget().
void MusicVideoControlWidget::pushBarrageChanged (bool on) signal
Open barrage on or not.
Referenced by pushBarrageClicked().
void MusicVideoControlWidget::pushBarrageClicked () slot
Push barrage clicked.
Definition at line 114 of file musicvideocontrolwidget.cpp.
References m_barrageSend, m_menuBarrage, m_pushBarrage, m_pushBarrageOn, m_searchEdit, MusicUIObject::MQSSVideoBtnBarrageOff, MusicUIObject::MQSSVideoBtnBarrageOn, and pushBarrageChanged().
Referenced by createVideoBarrageWidget().
void MusicVideoControlWidget::sendBarrageClicked () slot
Send barrage clicked.
Definition at line 125 of file musicvideocontrolwidget.cpp.
References addBarrageChanged(), MusicVideoBarrageStylePopWidget::barrageColor(), MusicVideoBarrageStylePopWidget::barrageSize(), MusicBarrageRecord::m_color, m_menuBarrage, m_searchEdit, MusicBarrageRecord::m_size, and MusicBarrageRecord::m_value.
Referenced by createVideoBarrageWidget().
void MusicVideoControlWidget::setButtonStyle (bool style) const
Set current button style.
Definition at line 93 of file musicvideocontrolwidget.cpp.
References m_playButton, MusicUIObject::MQSSVideoBtnPause, and MusicUIObject::MQSSVideoBtnPlay.
Referenced by MusicVideoView::play().
void MusicVideoControlWidget::setFixedSize (int w, int h)
Resize width bound by given width and height.
Definition at line 103 of file musicvideocontrolwidget.cpp.
References m_timeSlider.
void MusicVideoControlWidget::setQualityActionState ()
Set quality action state enable or disable.
Definition at line 109 of file musicvideocontrolwidget.cpp.
References m_qualityButton, and MusicVideoQualityPopWidget::setQualityActionState().
Referenced by MusicVideoView::setMedia().
void MusicVideoControlWidget::setValue (qint64 position) const
Set current video play value.
Definition at line 80 of file musicvideocontrolwidget.cpp.
References m_timeLabel, m_timeSlider, TTKTime::msecTime2LabelJustified(), MT_S2MS, and MusicMovingClickedSlider::setValue().
Referenced by MusicVideoView::positionChanged().
void MusicVideoControlWidget::sliderValueChanged (int value) signal
Slider value changed at value.
Referenced by MusicVideoControlWidget().
Member Data Documentation
QPushButton * MusicVideoControlWidget::m_barrageSend private
Definition at line 114 of file musicvideocontrolwidget.h.
Referenced by createVideoBarrageWidget(), pushBarrageClicked(), and ~MusicVideoControlWidget().
MusicVideoBarrageStylePopWidget* MusicVideoControlWidget::m_menuBarrage private
Definition at line 115 of file musicvideocontrolwidget.h.
Referenced by createVideoBarrageWidget(), pushBarrageClicked(), sendBarrageClicked(), and ~MusicVideoControlWidget().
QPushButton* MusicVideoControlWidget::m_playButton private
Definition at line 108 of file musicvideocontrolwidget.h.
Referenced by MusicVideoControlWidget(), setButtonStyle(), and ~MusicVideoControlWidget().
QPushButton* MusicVideoControlWidget::m_pushBarrage private
Definition at line 114 of file musicvideocontrolwidget.h.
Referenced by createVideoBarrageWidget(), pushBarrageClicked(), and ~MusicVideoControlWidget().
bool MusicVideoControlWidget::m_pushBarrageOn private
Definition at line 113 of file musicvideocontrolwidget.h.
Referenced by createVideoBarrageWidget(), and pushBarrageClicked().
MusicVideoQualityPopWidget* MusicVideoControlWidget::m_qualityButton private
Definition at line 111 of file musicvideocontrolwidget.h.
Referenced by mediaChanged(), MusicVideoControlWidget(), setQualityActionState(), and ~MusicVideoControlWidget().
MusicSearchEdit* MusicVideoControlWidget::m_searchEdit private
Definition at line 116 of file musicvideocontrolwidget.h.
Referenced by createVideoBarrageWidget(), pushBarrageClicked(), sendBarrageClicked(), and ~MusicVideoControlWidget().
QLabel* MusicVideoControlWidget::m_timeLabel private
Definition at line 107 of file musicvideocontrolwidget.h.
Referenced by durationChanged(), MusicVideoControlWidget(), setValue(), and ~MusicVideoControlWidget().
MusicMovingLabelSlider* MusicVideoControlWidget::m_timeSlider private
Definition at line 109 of file musicvideocontrolwidget.h.
Referenced by durationChanged(), MusicVideoControlWidget(), setFixedSize(), setValue(), and ~MusicVideoControlWidget().
MusicVolumePopWidget* MusicVideoControlWidget::m_volumeButton private
Definition at line 110 of file musicvideocontrolwidget.h.
Referenced by MusicVideoControlWidget(), and ~MusicVideoControlWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideocontrolwidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideocontrolwidget.cpp