TTKMusicplayer: MusicArtistMvsQueryWidget Class Reference
MusicArtistMvsQueryWidget Class Reference
The class of the artist mvs query widget.
#include <musicartistquerywidget.h>
Public Slots
void createArtistMvsItem (const MusicResultsItem &item)
void currentItemClicked (const QString &id)
void buttonClicked (int index)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicArtistMvsQueryWidget (QWidget *parent=nullptr)
~MusicArtistMvsQueryWidget ()
virtual void setSongName (const QString &name) overridefinal
virtual void setSongNameById (const QString &id) overridefinal
virtual void resizeWindow () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
void initialize ()
Protected Attributes
QGridLayout * m_gridLayout
bool m_initialized
MusicPageQueryWidget * m_pageQueryWidget
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_songNameFull
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultsItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Type m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Detailed Description
The class of the artist mvs query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 75 of file musicartistquerywidget.h.
Constructor & Destructor Documentation
MusicArtistMvsQueryWidget::MusicArtistMvsQueryWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 97 of file musicartistquerywidget.cpp.
References MusicSongSharingWidget::Artist, createArtistMvsItem(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_container, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_shareType, and MusicAbstractItemQueryWidget::m_statusLabel.
MusicArtistMvsQueryWidget::~MusicArtistMvsQueryWidget ()
Definition at line 116 of file musicartistquerywidget.cpp.
References m_gridLayout.
Member Function Documentation
void MusicArtistMvsQueryWidget::buttonClicked (int index) slot
Page widget button has changed.
Definition at line 177 of file musicartistquerywidget.cpp.
References MusicPageQueryWidget::currentIndex(), m_gridLayout, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicPageQueryWidget::page(), MusicPageQueryRequest::pageSize(), MusicPageQueryRequest::startToPage(), and MusicPageQueryRequest::totalSize().
Referenced by createArtistMvsItem().
void MusicArtistMvsQueryWidget::createArtistMvsItem (const MusicResultsItem & item) slot
Create the current albums item.
Definition at line 150 of file musicartistquerywidget.cpp.
References buttonClicked(), MusicPageQueryWidget::createPageWidget(), currentItemClicked(), LINE_SPACING_SIZE, m_gridLayout, m_initialized, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_networkRequest, m_pageQueryWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicPageQueryRequest::pageSize(), MusicArtistAlbumsItemWidget::setMusicResultsItem(), and MusicPageQueryRequest::totalSize().
Referenced by MusicArtistMvsQueryWidget().
void MusicArtistMvsQueryWidget::currentItemClicked (const QString & id) slot
Current item clicked.
Definition at line 172 of file musicartistquerywidget.cpp.
References MusicRightAreaWidget::instance(), and MusicRightAreaWidget::musicMovieSearch().
Referenced by createArtistMvsItem().
void MusicArtistMvsQueryWidget::resizeWindow () final override virtual
Resize window bound by widget resize called.
Implements MusicAbstractItemQueryWidget.
Definition at line 133 of file musicartistquerywidget.cpp.
References LINE_SPACING_SIZE, m_gridLayout, and MusicAbstractItemQueryWidget::m_resizeWidgets.
Referenced by MusicArtistQueryWidget::resizeWindow().
void MusicArtistMvsQueryWidget::setSongName (const QString & name) final override virtual
Set current name to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 121 of file musicartistquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_songNameFull, MusicAbstractItemQueryWidget::setSongName(), MusicQueryMovieRequest::startToSearch(), and TTKStatic_cast.
Referenced by MusicArtistQueryWidget::initFourthWidget(), and setSongNameById().
void MusicArtistMvsQueryWidget::setSongNameById (const QString & id) final override virtual
Set current id to search founds.
Implements MusicAbstractItemQueryWidget.
Definition at line 128 of file musicartistquerywidget.cpp.
References setSongName().
Member Data Documentation
QGridLayout* MusicArtistMvsQueryWidget::m_gridLayout protected
Definition at line 114 of file musicartistquerywidget.h.
Referenced by buttonClicked(), createArtistMvsItem(), MusicArtistMvsQueryWidget(), resizeWindow(), and ~MusicArtistMvsQueryWidget().
bool MusicArtistMvsQueryWidget::m_initialized protected
Definition at line 115 of file musicartistquerywidget.h.
Referenced by createArtistMvsItem(), and MusicArtistMvsQueryWidget().
MusicPageQueryWidget* MusicArtistMvsQueryWidget::m_pageQueryWidget protected
Definition at line 116 of file musicartistquerywidget.h.
Referenced by buttonClicked(), createArtistMvsItem(), and MusicArtistMvsQueryWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.cpp