TTKMusicplayer: MusicAbstractDownloadTableWidget Class Reference
MusicAbstractDownloadTableWidget Class Reference abstract
The class of the download abstract table widget.
#include <musicabstractdownloadtablewidget.h>
Public Slots
void musicPlay ()
virtual void setDeleteItemAt () overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
void itemDoubleClicked (int row, int column)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Public Slots inherited from MusicAbstractSongsListTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumQueryWidget ()
void musicSimilarQueryWidget ()
void musicSongSharedWidget ()
void musicSongDownload ()
void musicSongPlayedMovieFound ()
void musicPlayedSimilarQueryWidget ()
void musicSongPlayedSharedWidget ()
void musicSongPlayedKMicroWidget ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Signals
void addSongToPlaylist (const QStringList &list)
void updateItemTitle (int index)
Signals inherited from MusicAbstractSongsListTableWidget
void isCurrentIndex (bool &state)
Public Member Functions
MusicAbstractDownloadTableWidget (QWidget *parent=nullptr)
~MusicAbstractDownloadTableWidget ()
virtual void updateSongsFileName (const MusicSongs &songs) overridefinal
Public Member Functions inherited from MusicAbstractSongsListTableWidget
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
~MusicAbstractSongsListTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void selectRow (int index)
int totalHeight () const
void setToolIndex (int index)
void setPlayRowIndex (int index)
int playRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
void clear ()
TTKIntList multiSelectedIndex () const
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void createItem (int index, const MusicSong &record)=0
Protected Member Functions inherited from MusicAbstractSongsListTableWidget
void createMoreMenu (QMenu *menu)
QString currentSongPath () const
QString songPath (int index) const
QString currentSongName () const
QString songName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
MusicProgressBarDelegate * m_delegate
MusicObject::RecordType m_type
Protected Attributes inherited from MusicAbstractSongsListTableWidget
int m_playRowIndex
int m_toolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_initialized
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_backgroundColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the download abstract table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicabstractdownloadtablewidget.h.
Constructor & Destructor Documentation
MusicAbstractDownloadTableWidget::MusicAbstractDownloadTableWidget (QWidget * parent = nullptr) explicit
Definition at line 9 of file musicabstractdownloadtablewidget.cpp.
References G_CONNECTION_PTR, itemDoubleClicked(), and m_delegate.
MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget ()
Definition at line 20 of file musicabstractdownloadtablewidget.cpp.
References MusicAbstractTableWidget::clear(), G_CONNECTION_PTR, m_delegate, MusicAbstractSongsListTableWidget::m_musicSongs, m_type, and MusicDownloadRecordConfigManager::writeDownloadData().
Member Function Documentation
void MusicAbstractDownloadTableWidget::addSongToPlaylist (const QStringList & list) signal
Add current selected song to playlist.
Referenced by musicPlay().
void MusicAbstractDownloadTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicCloudUploadTableWidget.
Definition at line 133 of file musicabstractdownloadtablewidget.cpp.
References MusicAbstractSongsListTableWidget::createMoreMenu(), MusicAbstractSongsListTableWidget::m_musicSongs, MusicUIObject::MQSSMenuStyle02, MusicAbstractSongsListTableWidget::musicAlbumQueryWidget(), MusicAbstractSongsListTableWidget::musicFileInformation(), MusicAbstractSongsListTableWidget::musicOpenFileDir(), MusicAbstractSongsListTableWidget::musicPlayClicked(), MusicAbstractSongsListTableWidget::musicSongDownload(), MusicAbstractSongsListTableWidget::setDeleteItemAll(), and setDeleteItemAt().
void MusicAbstractDownloadTableWidget::createDownloadItem (const QString & name, qint64 time) slot
Create download item from download name and total time.
Definition at line 116 of file musicabstractdownloadtablewidget.cpp.
References createItem(), MusicAbstractSongsListTableWidget::m_musicSongs, MusicAbstractSongsListTableWidget::m_toolIndex, MusicUtils::String::musicPrefix(), name, MusicSong::setMusicAddTimeStr(), MusicSong::setMusicName(), MusicSong::setMusicPath(), MusicSong::setMusicSizeStr(), and updateItemTitle().
virtual void MusicAbstractDownloadTableWidget::createItem (int index, const MusicSong & record) protected pure virtual
Create item by index and name and size and time.
Implemented in MusicCloudUploadTableWidget, MusicCloudDownloadTableWidget, and MusicDownloadRecordTableWidget.
Referenced by createDownloadItem(), and updateSongsFileName().
void MusicAbstractDownloadTableWidget::downloadProgressChanged (float percent, const QString & total, qint64 time) slot
Update download percent\ total time and current time progress.
Definition at line 100 of file musicabstractdownloadtablewidget.cpp.
References MUSIC_PROGRESS_ROLE, and MUSIC_TIME_ROLE.
void MusicAbstractDownloadTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 87 of file musicabstractdownloadtablewidget.cpp.
void MusicAbstractDownloadTableWidget::itemDoubleClicked (int row, int column) slot
Table widget item cell double click.
Definition at line 93 of file musicabstractdownloadtablewidget.cpp.
References musicPlay().
Referenced by MusicAbstractDownloadTableWidget().
void MusicAbstractDownloadTableWidget::musicPlay () slot
Add selected music song path to list.
Definition at line 50 of file musicabstractdownloadtablewidget.cpp.
References addSongToPlaylist(), and MusicAbstractSongsListTableWidget::m_musicSongs.
Referenced by itemDoubleClicked().
void MusicAbstractDownloadTableWidget::setDeleteItemAt () final override virtual slot
Delete item from list at current row.
Definition at line 61 of file musicabstractdownloadtablewidget.cpp.
References MusicMessageBox::exec(), MusicAbstractSongsListTableWidget::m_musicSongs, MusicAbstractSongsListTableWidget::m_toolIndex, MusicAbstractTableWidget::multiSelectedIndex(), MusicMessageBox::setText(), MusicAbstractSongsListTableWidget::totalHeight(), and updateItemTitle().
Referenced by contextMenuEvent(), and MusicCloudUploadTableWidget::contextMenuEvent().
void MusicAbstractDownloadTableWidget::updateItemTitle (int index) signal
Update item title.
Referenced by createDownloadItem(), and setDeleteItemAt().
void MusicAbstractDownloadTableWidget::updateSongsFileName (const MusicSongs & songs) final override virtual
Read all config from file and insert items.
Reimplemented from MusicAbstractSongsListTableWidget.
Definition at line 30 of file musicabstractdownloadtablewidget.cpp.
References createItem(), G_DOWNLOAD_MANAGER_PTR, MusicAbstractSongsListTableWidget::m_musicSongs, m_type, MusicSong::musicAddTimeStr(), MusicDownloadRecordConfigManager::readConfig(), and MusicDownloadRecordConfigManager::readDownloadData().
Member Data Documentation
MusicProgressBarDelegate* MusicAbstractDownloadTableWidget::m_delegate protected
Definition at line 89 of file musicabstractdownloadtablewidget.h.
Referenced by MusicAbstractDownloadTableWidget(), MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget(), and ~MusicAbstractDownloadTableWidget().
MusicObject::RecordType MusicAbstractDownloadTableWidget::m_type protected
Definition at line 90 of file musicabstractdownloadtablewidget.h.
Referenced by MusicCloudUploadTableWidget::MusicCloudUploadTableWidget(), MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget(), updateSongsFileName(), and ~MusicAbstractDownloadTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicabstractdownloadtablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicabstractdownloadtablewidget.cpp