TTKMusicplayer: MusicMPRISPlayerBase Class Reference
MusicMPRISPlayerBase Class Reference
The class of the app mpris player object.
#include <musicmprisplayer.h>
Public Slots
void Next ()
void Previous ()
void OpenUri (const QString &uri)
void Pause ()
void Play ()
void PlayPause ()
void Stop ()
void Seek (qlonglong offset)
void SetPosition (const QDBusObjectPath &trackId, qlonglong position)
Signals
void Seeked (qlonglong position)
Public Member Functions
MusicMPRISPlayerBase (QObject *parent=nullptr)
bool canControl () const
bool canGoNext () const
bool canGoPrevious () const
bool canPause () const
bool canPlay () const
bool canSeek () const
QString loopStatus () const
void setLoopStatus (const QString &value)
double maximumRate () const
QVariantMap metadata () const
double minimumRate () const
QString playbackStatus () const
qlonglong position () const
double rate () const
void setRate (double value)
bool shuffle () const
void setShuffle (bool value)
double volume () const
void setVolume (double value)
Properties
bool CanControl
bool CanGoNext
bool CanGoPrevious
bool CanPause
bool CanPlay
bool CanSeek
QString LoopStatus
double MaximumRate
QVariantMap Metadata
double MinimumRate
QString PlaybackStatus
qlonglong Position
double Rate
bool Shuffle
double Volume
Private Slots
void trackInfoChanged ()
void stateChanged ()
void volumeChanged ()
void elapsedChanged (qint64 elapsed)
void playbackModeChanged ()
Private Member Functions
void updateTrackID ()
void syncProperties ()
void sendProperties ()
Private Attributes
int m_prev_track
qint64 m_prev_pos
SoundCore * m_music
MusicApplication * m_player
QDBusObjectPath m_trackID
TTKVariantMap m_properties
Detailed Description
The class of the app mpris player object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 92 of file musicmprisplayer.h.
Constructor & Destructor Documentation
MusicMPRISPlayerBase::MusicMPRISPlayerBase (QObject * parent = nullptr)
Definition at line 100 of file musicmprisplayer.cpp.
References elapsedChanged(), MusicTime::initRandom(), MusicApplication::instance(), SoundCore::instance(), m_music, MusicApplication::m_musicPlaylist, m_player, m_prev_pos, m_prev_track, playbackModeChanged(), stateChanged(), syncProperties(), trackInfoChanged(), updateTrackID(), and volumeChanged().
Member Function Documentation
bool MusicMPRISPlayerBase::canControl () const
Definition at line 120 of file musicmprisplayer.cpp.
bool MusicMPRISPlayerBase::canGoNext () const
Definition at line 125 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicMPRISPlayerBase::canGoPrevious () const
Definition at line 130 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicMPRISPlayerBase::canPause () const
Definition at line 135 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicMPRISPlayerBase::canPlay () const
Definition at line 139 of file musicmprisplayer.cpp.
References MusicPlaylist::isEmpty(), MusicApplication::m_musicPlaylist, and m_player.
Referenced by syncProperties().
bool MusicMPRISPlayerBase::canSeek () const
Definition at line 144 of file musicmprisplayer.cpp.
References SoundCore::duration(), and m_music.
Referenced by syncProperties().
void MusicMPRISPlayerBase::elapsedChanged (qint64 elapsed) private slot
Tracks elapesed time.
Definition at line 386 of file musicmprisplayer.cpp.
References m_prev_pos, and Seeked().
Referenced by MusicMPRISPlayerBase().
QString MusicMPRISPlayerBase::loopStatus () const
Definition at line 149 of file musicmprisplayer.cpp.
References m_player, MusicObject::PlaylistLoop, MusicApplication::playMode(), and MusicObject::PlayOneLoop.
Referenced by syncProperties().
double MusicMPRISPlayerBase::maximumRate () const
Definition at line 175 of file musicmprisplayer.cpp.
Referenced by syncProperties().
QVariantMap MusicMPRISPlayerBase::metadata () const
Definition at line 180 of file musicmprisplayer.cpp.
References Qmmp::ALBUM, Qmmp::ALBUMARTIST, Qmmp::ARTIST, Qmmp::COMMENT, Qmmp::COMPOSER, Qmmp::DISCNUMBER, SoundCore::duration(), Qmmp::GENRE, MetaDataManager::getCoverPath(), MetaDataManager::instance(), m_music, m_trackID, TrackInfo::path(), SoundCore::path(), Qmmp::TITLE, Qmmp::TRACK, SoundCore::trackInfo(), TTK_SEPARATOR, TrackInfo::value(), and Qmmp::YEAR.
Referenced by syncProperties().
double MusicMPRISPlayerBase::minimumRate () const
Definition at line 250 of file musicmprisplayer.cpp.
Referenced by syncProperties().
void MusicMPRISPlayerBase::Next () slot
Definition at line 308 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicPlayNext().
void MusicMPRISPlayerBase::OpenUri (const QString & uri) slot
Definition at line 313 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicImportSongsPathOutside().
void MusicMPRISPlayerBase::Pause () slot
Definition at line 328 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicStatePlay().
void MusicMPRISPlayerBase::Play () slot
Definition at line 333 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicStatePlay().
void MusicMPRISPlayerBase::playbackModeChanged () private slot
Current play mode changed emit.
Definition at line 395 of file musicmprisplayer.cpp.
References sendProperties().
Referenced by MusicMPRISPlayerBase().
QString MusicMPRISPlayerBase::playbackStatus () const
Definition at line 255 of file musicmprisplayer.cpp.
References m_music, Qmmp::Paused, Qmmp::Playing, and SoundCore::state().
Referenced by syncProperties().
void MusicMPRISPlayerBase::PlayPause () slot
Definition at line 338 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicStatePlay().
qlonglong MusicMPRISPlayerBase::position () const
Definition at line 268 of file musicmprisplayer.cpp.
References SoundCore::elapsed(), and m_music.
void MusicMPRISPlayerBase::Previous () slot
Definition at line 303 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicPlayPrevious().
double MusicMPRISPlayerBase::rate () const
Definition at line 273 of file musicmprisplayer.cpp.
Referenced by syncProperties().
void MusicMPRISPlayerBase::Seek (qlonglong offset) slot
Definition at line 348 of file musicmprisplayer.cpp.
References SoundCore::elapsed(), m_music, and SoundCore::seek().
void MusicMPRISPlayerBase::Seeked (qlonglong position) signal
Referenced by elapsedChanged().
void MusicMPRISPlayerBase::sendProperties () private
Definition at line 426 of file musicmprisplayer.cpp.
References m_properties, and syncProperties().
Referenced by playbackModeChanged(), stateChanged(), trackInfoChanged(), and volumeChanged().
void MusicMPRISPlayerBase::setLoopStatus (const QString & value)
Definition at line 159 of file musicmprisplayer.cpp.
References m_player, MusicApplication::musicPlaylistLoop(), MusicApplication::musicPlayOneLoop(), and MusicApplication::musicPlayOrder().
void MusicMPRISPlayerBase::SetPosition (const QDBusObjectPath & trackId, qlonglong position) slot
Definition at line 353 of file musicmprisplayer.cpp.
References m_music, m_trackID, SoundCore::seek(), and TTK_LOGGER_WARN.
void MusicMPRISPlayerBase::setRate (double value)
Definition at line 278 of file musicmprisplayer.cpp.
void MusicMPRISPlayerBase::setShuffle (bool value)
Definition at line 288 of file musicmprisplayer.cpp.
References MusicApplication::m_musicPlaylist, m_player, MusicObject::PlayOrder, MusicObject::PlayRandom, and MusicPlaylist::setPlaybackMode().
void MusicMPRISPlayerBase::setVolume (double value)
Definition at line 298 of file musicmprisplayer.cpp.
References MusicApplication::m_musicPlayer, m_player, and MusicPlayer::setVolume().
bool MusicMPRISPlayerBase::shuffle () const
Definition at line 283 of file musicmprisplayer.cpp.
References m_player, MusicApplication::playMode(), and MusicObject::PlayRandom.
Referenced by syncProperties().
void MusicMPRISPlayerBase::stateChanged () private slot
When the state of the SoundCore has changed.
Definition at line 371 of file musicmprisplayer.cpp.
References m_music, m_prev_pos, Qmmp::Playing, sendProperties(), SoundCore::state(), and updateTrackID().
Referenced by MusicMPRISPlayerBase().
void MusicMPRISPlayerBase::Stop () slot
Definition at line 343 of file musicmprisplayer.cpp.
References m_player, and MusicApplication::musicStateStop().
void MusicMPRISPlayerBase::syncProperties () private
Definition at line 409 of file musicmprisplayer.cpp.
References canGoNext(), canGoPrevious(), canPause(), canPlay(), canSeek(), loopStatus(), m_properties, maximumRate(), metadata(), minimumRate(), playbackStatus(), rate(), shuffle(), and volume().
Referenced by MusicMPRISPlayerBase(), and sendProperties().
void MusicMPRISPlayerBase::trackInfoChanged () private slot
When new track information is available.
Definition at line 365 of file musicmprisplayer.cpp.
References sendProperties(), and updateTrackID().
Referenced by MusicMPRISPlayerBase().
void MusicMPRISPlayerBase::updateTrackID () private
Definition at line 400 of file musicmprisplayer.cpp.
References MusicPlaylist::currentIndex(), MusicApplication::m_musicPlaylist, m_player, m_prev_track, m_trackID, and MusicTime::random().
Referenced by MusicMPRISPlayerBase(), stateChanged(), and trackInfoChanged().
double MusicMPRISPlayerBase::volume () const
Definition at line 293 of file musicmprisplayer.cpp.
References MusicApplication::m_musicPlayer, m_player, and MusicPlayer::volume().
Referenced by syncProperties().
void MusicMPRISPlayerBase::volumeChanged () private slot
When the highest volume of the left and right channels has changed.
Definition at line 381 of file musicmprisplayer.cpp.
References sendProperties().
Referenced by MusicMPRISPlayerBase().
Member Data Documentation
SoundCore* MusicMPRISPlayerBase::m_music private
Definition at line 178 of file musicmprisplayer.h.
Referenced by canSeek(), metadata(), MusicMPRISPlayerBase(), playbackStatus(), position(), Seek(), SetPosition(), and stateChanged().
MusicApplication* MusicMPRISPlayerBase::m_player private
Definition at line 179 of file musicmprisplayer.h.
Referenced by canGoNext(), canGoPrevious(), canPause(), canPlay(), loopStatus(), MusicMPRISPlayerBase(), Next(), OpenUri(), Pause(), Play(), PlayPause(), Previous(), setLoopStatus(), setShuffle(), setVolume(), shuffle(), Stop(), updateTrackID(), and volume().
qint64 MusicMPRISPlayerBase::m_prev_pos private
Definition at line 177 of file musicmprisplayer.h.
Referenced by elapsedChanged(), MusicMPRISPlayerBase(), and stateChanged().
int MusicMPRISPlayerBase::m_prev_track private
Definition at line 176 of file musicmprisplayer.h.
Referenced by MusicMPRISPlayerBase(), and updateTrackID().
TTKVariantMap MusicMPRISPlayerBase::m_properties private
Definition at line 181 of file musicmprisplayer.h.
Referenced by sendProperties(), and syncProperties().
QDBusObjectPath MusicMPRISPlayerBase::m_trackID private
Definition at line 180 of file musicmprisplayer.h.
Referenced by metadata(), SetPosition(), and updateTrackID().
Property Documentation
bool MusicMPRISPlayerBase::CanControl read
Definition at line 96 of file musicmprisplayer.h.
bool MusicMPRISPlayerBase::CanGoNext read
Definition at line 97 of file musicmprisplayer.h.
bool MusicMPRISPlayerBase::CanGoPrevious read
Definition at line 98 of file musicmprisplayer.h.
bool MusicMPRISPlayerBase::CanPause read
Definition at line 99 of file musicmprisplayer.h.
bool MusicMPRISPlayerBase::CanPlay read
Definition at line 100 of file musicmprisplayer.h.
bool MusicMPRISPlayerBase::CanSeek read
Definition at line 101 of file musicmprisplayer.h.
QString MusicMPRISPlayerBase::LoopStatus read write
Definition at line 102 of file musicmprisplayer.h.
double MusicMPRISPlayerBase::MaximumRate read
Definition at line 103 of file musicmprisplayer.h.
QVariantMap MusicMPRISPlayerBase::Metadata read
Definition at line 104 of file musicmprisplayer.h.
double MusicMPRISPlayerBase::MinimumRate read
Definition at line 105 of file musicmprisplayer.h.
QString MusicMPRISPlayerBase::PlaybackStatus read
Definition at line 106 of file musicmprisplayer.h.
qlonglong MusicMPRISPlayerBase::Position read
Definition at line 107 of file musicmprisplayer.h.
double MusicMPRISPlayerBase::Rate read write
Definition at line 108 of file musicmprisplayer.h.
bool MusicMPRISPlayerBase::Shuffle read write
Definition at line 109 of file musicmprisplayer.h.
double MusicMPRISPlayerBase::Volume read write
Definition at line 110 of file musicmprisplayer.h.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musicmprisplayer.h
TTKModule/TTKCore/musicCoreKits/musicmprisplayer.cpp