TTKMusicplayer: MusicBarrageRecordConfigManager Class Reference
MusicBarrageRecordConfigManager Class Reference
The class of the barrage record manager.
#include <musicbarragerecordconfigmanager.h>
Public Member Functions
MusicBarrageRecordConfigManager (QObject *parent=nullptr)
bool readConfig ()
void readBarrageData (MusicBarrageRecords &records)
void writeBarrageData (const MusicBarrageRecords &records)
Public Member Functions inherited from MusicAbstractXml
MusicAbstractXml (QObject *parent=nullptr)
virtual ~MusicAbstractXml ()
bool readConfig (const QString &name)
bool writeConfig (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagNameValue (const QString &tagName) const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName) const
QString readXmlTextByTagName (const QString &tagName) const
TTKVariantMap readXmlAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const MusicXmlAttribute &attr)
QDomElement createRoot (const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const MusicXmlAttribute &attr)
QDomElement writeDomElementMutil (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const MusicXmlAttribute &attr, const QString &text)
QDomElement writeDomElementMutilText (QDomElement &element, const QString &node, const MusicXmlAttributes &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const MusicXmlAttribute &attr)
Additional Inherited Members
Protected Attributes inherited from MusicAbstractXml
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the barrage record manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicbarragerecordconfigmanager.h.
Constructor & Destructor Documentation
MusicBarrageRecordConfigManager::MusicBarrageRecordConfigManager (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicbarragerecordconfigmanager.cpp.
Member Function Documentation
void MusicBarrageRecordConfigManager::readBarrageData (MusicBarrageRecords & records)
Read datas from config file.
Definition at line 9 of file musicbarragerecordconfigmanager.cpp.
References MusicBarrageRecord::m_color, MusicAbstractXml::m_document, MusicBarrageRecord::m_size, and MusicBarrageRecord::m_value.
Referenced by MusicBarrageWidget::readBarrage(), and MusicBarrageWidget::writeBarrage().
bool MusicBarrageRecordConfigManager::readConfig () inline
Read barrage datas from xml file by given name.
Definition at line 51 of file musicbarragerecordconfigmanager.h.
References BARRAGEPATH_FULL, and MusicAbstractXml::readConfig().
Referenced by MusicBarrageWidget::readBarrage(), and MusicBarrageWidget::writeBarrage().
void MusicBarrageRecordConfigManager::writeBarrageData (const MusicBarrageRecords & records)
Write datas into config file.
Definition at line 22 of file musicbarragerecordconfigmanager.cpp.
References APP_NAME, BARRAGEPATH_FULL, MusicAbstractXml::createProcessingInstruction(), MusicAbstractXml::createRoot(), MusicAbstractXml::m_document, MusicAbstractXml::m_file, MusicXmlAttribute::m_value, MusicAbstractXml::writeConfig(), MusicAbstractXml::writeDomElementMutilText(), and MusicAbstractXml::writeDomNode().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicVideoKits/musicbarragerecordconfigmanager.h
TTKModule/TTKCore/musicVideoKits/musicbarragerecordconfigmanager.cpp