TTKMusicplayer: MusicNetworkSpeedTestWidget Class Reference
MusicNetworkSpeedTestWidget Class Reference
The class of the network speed test widget.
#include <musicnetworkspeedtestwidget.h>
Public Slots
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void resetFlag (MusicObject::ToolsType flag)
Public Member Functions
MusicNetworkSpeedTestWidget (QWidget *parent=0)
virtual ~MusicNetworkSpeedTestWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
void settingButton ()
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicNetworkSpeedTestWidget * m_ui
QTimer m_testTimer
ulong m_testAverage
ulong m_totalUp
ulong m_totalDown
MusicNetworkSpeedTestThread * m_thread
MusicDataDownloadThread * m_testDownload
MusicNetworkSpeedSuspensionWidget * m_suspension
QActionGroup * m_actionGroup
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Private Slots
void networkData (ulong upload, ulong download)
void suspensionOpen ()
void networkTestStart ()
void networkTestStop ()
void actionTriggered (QAction *action)
Detailed Description
The class of the network speed test widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 40 of file musicnetworkspeedtestwidget.h.
Constructor & Destructor Documentation
MusicNetworkSpeedTestWidget::MusicNetworkSpeedTestWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 15 of file musicnetworkspeedtestwidget.cpp.
References m_testAverage, m_testTimer, m_thread, m_totalDown, m_totalUp, m_ui, MusicUIObject::MPushButtonStyle04, MT_S2MS, MusicUIObject::MToolButtonStyle04, networkData(), networkTestStart(), networkTestStop(), settingButton(), MusicNetworkSpeedTestThread::start(), and suspensionOpen().
MusicNetworkSpeedTestWidget::~MusicNetworkSpeedTestWidget () virtual
Definition at line 61 of file musicnetworkspeedtestwidget.cpp.
References m_actionGroup, m_testDownload, m_testTimer, m_thread, and m_ui.
Member Function Documentation
void MusicNetworkSpeedTestWidget::actionTriggered (QAction * action) private slot
Select diff network interface action.
remove temp file
Definition at line 141 of file musicnetworkspeedtestwidget.cpp.
References m_actionGroup.
Referenced by settingButton().
void MusicNetworkSpeedTestWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 75 of file musicnetworkspeedtestwidget.cpp.
References resetFlag(), and MusicObject::TT_SpeedTest.
QString MusicNetworkSpeedTestWidget::getClassName () static
Get class object name.
Definition at line 70 of file musicnetworkspeedtestwidget.cpp.
void MusicNetworkSpeedTestWidget::networkData (ulong upload, ulong download) private slot
Get current upload and download speed data.
Definition at line 97 of file musicnetworkspeedtestwidget.cpp.
References m_testAverage, m_testTimer, m_totalDown, m_totalUp, m_ui, MusicUtils::Number::sizeByte2KByte(), and MusicUtils::Number::speed2Label().
Referenced by MusicNetworkSpeedTestWidget().
void MusicNetworkSpeedTestWidget::networkTestStart () private slot
Network test start.
Definition at line 127 of file musicnetworkspeedtestwidget.cpp.
References MusicDownLoadThreadAbstract::Download_BigBG, M_NETWORK_PTR, m_testDownload, m_testTimer, m_ui, MusicUtils::Algorithm::mdII(), MUSIC_NETWORK_TEST_FILE, MusicDataDownloadThread::startToDownload(), and testUrl.
Referenced by MusicNetworkSpeedTestWidget().
void MusicNetworkSpeedTestWidget::networkTestStop () private slot
Network test stop.
Referenced by MusicNetworkSpeedTestWidget().
void MusicNetworkSpeedTestWidget::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by closeEvent().
void MusicNetworkSpeedTestWidget::settingButton () protected
Set button popup menu.
Definition at line 81 of file musicnetworkspeedtestwidget.cpp.
References actionTriggered(), MusicNetworkSpeedTestThread::getNewtworkNames(), m_actionGroup, m_thread, m_ui, and MusicUIObject::MMenuStyle02.
Referenced by MusicNetworkSpeedTestWidget().
void MusicNetworkSpeedTestWidget::show () slot
Override show function.
void MusicNetworkSpeedTestWidget::suspensionOpen () private slot
Open suspension widget.
Definition at line 119 of file musicnetworkspeedtestwidget.cpp.
References MusicNetworkSpeedTestThread::getAvailableNewtworkNames(), m_suspension, m_thread, and MusicNetworkSpeedSuspensionWidget::setAvailableNewtworkNames().
Referenced by MusicNetworkSpeedTestWidget().
Member Data Documentation
QActionGroup* MusicNetworkSpeedTestWidget::m_actionGroup protected
Definition at line 106 of file musicnetworkspeedtestwidget.h.
Referenced by actionTriggered(), settingButton(), and ~MusicNetworkSpeedTestWidget().
MusicNetworkSpeedSuspensionWidget* MusicNetworkSpeedTestWidget::m_suspension protected
Definition at line 105 of file musicnetworkspeedtestwidget.h.
Referenced by suspensionOpen().
ulong MusicNetworkSpeedTestWidget::m_testAverage protected
Definition at line 102 of file musicnetworkspeedtestwidget.h.
Referenced by MusicNetworkSpeedTestWidget(), and networkData().
MusicDataDownloadThread* MusicNetworkSpeedTestWidget::m_testDownload protected
Definition at line 104 of file musicnetworkspeedtestwidget.h.
Referenced by networkTestStart(), and ~MusicNetworkSpeedTestWidget().
QTimer MusicNetworkSpeedTestWidget::m_testTimer protected
Definition at line 101 of file musicnetworkspeedtestwidget.h.
Referenced by MusicNetworkSpeedTestWidget(), networkData(), networkTestStart(), and ~MusicNetworkSpeedTestWidget().
MusicNetworkSpeedTestThread* MusicNetworkSpeedTestWidget::m_thread protected
Definition at line 103 of file musicnetworkspeedtestwidget.h.
Referenced by MusicNetworkSpeedTestWidget(), settingButton(), suspensionOpen(), and ~MusicNetworkSpeedTestWidget().
ulong MusicNetworkSpeedTestWidget::m_totalDown protected
Definition at line 102 of file musicnetworkspeedtestwidget.h.
Referenced by MusicNetworkSpeedTestWidget(), and networkData().
ulong MusicNetworkSpeedTestWidget::m_totalUp protected
Definition at line 102 of file musicnetworkspeedtestwidget.h.
Referenced by MusicNetworkSpeedTestWidget(), and networkData().
Ui::MusicNetworkSpeedTestWidget* MusicNetworkSpeedTestWidget::m_ui protected
Definition at line 100 of file musicnetworkspeedtestwidget.h.
Referenced by MusicNetworkSpeedTestWidget(), networkData(), networkTestStart(), settingButton(), and ~MusicNetworkSpeedTestWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkspeedtestwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicnetworkspeedtestwidget.cpp