TTKMusicPlayer: BLInterface Namespace Reference
BLInterface Namespace Reference
Functions
static void makeRequestRawHeader (QNetworkRequest *request)
static void parseFromMovieInfo (TTK::MusicSongInformation *info, QString &cid)
static void parseFromMovieProperty (TTK::MusicSongInformation *info, const QString &cid)
Variables
static constexpr const char * MODULE = "BL"
static const QString BUVID_URL = "NmozU2YzaW5JbFE0QnRHVHJheWFaWk5JbjE1QWdWdFpTWFU4aFoyZEt1RU5FdVZ0T1JsV3pscUlkbFdMYVVjT1ArYStiOG9yR1RZMFZ0UVY="
static const QString MOVIE_URL = "ZTRrNzB2YnIzbTVvRzZUdDZVeGllN09MM3J6TjhaVGplNUZUOHBFWnBtZ0FFWEh2MUN2STBWb2ZJUzlXRE5HcHo4RlhMQWZjRitha04rczNIcnlOVXpxcWVRQlp6YzBsNE9pVExuNWRDNS9zSnNKSjlyN0pOQUs2S3JOQjVkWmo="
static const QString MOVIE_DATA_URL = "ak5VTmcwemNhNXNpU1NCcXFTb28rWmo5TEdmMmtHNkh1ZUdHWWEveHFCWG80MnRyVkpHWHVNQ2VIN0dhUDJvOGRGVmdDei9paTFNPQ=="
static const QString MOVIE_PLAY_URL = "a0Y2MzNmVEFOd2JHN0xuaDBjVmJEYndRNkRmb2w1YUs3K0ZoNExpYXVYR3BjaEtSemgwdXVmem5GSDhpS29Cc0RDMStIR1RuWmF5RENKYWVxcmhCRXI0dE5JdGgwVTh5YW9YWVMvK1B3bWdNZFBMag=="
Function Documentation
void BLInterface::makeRequestRawHeader (QNetworkRequest * request) static
Make request query data.
Definition at line 34 of file musicunityquerymovierequest.cpp.
References BUVID_URL, TTK::makeContentTypeHeader(), TTK::Algorithm::mdII(), and TTK::setSslConfiguration().
Referenced by parseFromMovieInfo(), parseFromMovieProperty(), and MusicUnityQueryMovieRequest::startToPage().
void BLInterface::parseFromMovieInfo (TTK::MusicSongInformation * info, QString & cid) static
Read mv cid from query results.
Definition at line 41 of file musicunityquerymovierequest.cpp.
References TTK::MusicSongInformation::m_songId, makeRequestRawHeader(), TTK::Algorithm::mdII(), MOVIE_DATA_URL, QJson::Parser::parse(), qAsConst, and TTK::syncNetworkQueryForGet().
Referenced by MusicUnityQueryMovieRequest::downLoadUnityFinished().
void BLInterface::parseFromMovieProperty (TTK::MusicSongInformation * info, const QString & cid) static
Read mv tags(size) from query results.
Definition at line 78 of file musicunityquerymovierequest.cpp.
References TTKTime::formatDuration(), TTK::MusicSongProperty::m_bitrate, TTK::MusicSongInformation::m_duration, TTK::MusicSongProperty::m_format, TTK::MusicSongProperty::m_size, TTK::MusicSongInformation::m_songId, TTK::MusicSongInformation::m_songProps, TTK::MusicSongProperty::m_url, makeRequestRawHeader(), TTK::Algorithm::mdII(), MOVIE_PLAY_URL, MP4_FILE_SUFFIX, QJson::Parser::parse(), qAsConst, TTK::Number::sizeByteToLabel(), TTK::syncNetworkQueryForGet(), and TTK_BN_250.
Referenced by MusicUnityQueryMovieRequest::downLoadUnityFinished().
Variable Documentation
const QString BLInterface::BUVID_URL = "NmozU2YzaW5JbFE0QnRHVHJheWFaWk5JbjE1QWdWdFpTWFU4aFoyZEt1RU5FdVZ0T1JsV3pscUlkbFdMYVVjT1ArYStiOG9yR1RZMFZ0UVY=" static
Definition at line 13 of file musicunityquerymovierequest.cpp.
Referenced by makeRequestRawHeader().
constexpr const char* BLInterface::MODULE = "BL" static
Definition at line 12 of file musicunityquerymovierequest.cpp.
Referenced by MusicUnityQueryMovieRequest::startToPage().
const QString BLInterface::MOVIE_DATA_URL = "ak5VTmcwemNhNXNpU1NCcXFTb28rWmo5TEdmMmtHNkh1ZUdHWWEveHFCWG80MnRyVkpHWHVNQ2VIN0dhUDJvOGRGVmdDei9paTFNPQ==" static
Definition at line 15 of file musicunityquerymovierequest.cpp.
Referenced by parseFromMovieInfo().
const QString BLInterface::MOVIE_PLAY_URL = "a0Y2MzNmVEFOd2JHN0xuaDBjVmJEYndRNkRmb2w1YUs3K0ZoNExpYXVYR3BjaEtSemgwdXVmem5GSDhpS29Cc0RDMStIR1RuWmF5RENKYWVxcmhCRXI0dE5JdGgwVTh5YW9YWVMvK1B3bWdNZFBMag==" static
Definition at line 16 of file musicunityquerymovierequest.cpp.
Referenced by parseFromMovieProperty().
const QString BLInterface::MOVIE_URL = "ZTRrNzB2YnIzbTVvRzZUdDZVeGllN09MM3J6TjhaVGplNUZUOHBFWnBtZ0FFWEh2MUN2STBWb2ZJUzlXRE5HcHo4RlhMQWZjRitha04rczNIcnlOVXpxcWVRQlp6YzBsNE9pVExuNWRDNS9zSnNKSjlyN0pOQUs2S3JOQjVkWmo=" static
Definition at line 14 of file musicunityquerymovierequest.cpp.
Referenced by MusicUnityQueryMovieRequest::startToPage().