TTKMusicplayer: MusicBottomAreaWidget Class Reference
MusicBottomAreaWidget Class Reference
The class of the app bottom area widget.
#include <musicbottomareawidget.h>
Public Slots
void lrcWidgetShowFullScreen ()
void lockDesktopLrc (bool lock)
void desktopLrcClosed ()
void iconActivated (QSystemTrayIcon::ActivationReason)
Public Member Functions
MusicBottomAreaWidget (QWidget *parent=nullptr)
~MusicBottomAreaWidget ()
void setupUi (Ui::MusicApplication *ui)
void setDestopLrcVisible (bool status) const
void setCurrentPlayStatus (bool status) const
void setVolumeValue (int value) const
void setLabelText (const QString &name) const
void setSystemCloseConfig (bool status)
bool systemCloseConfig ()
bool systemTrayIsVisible ()
void showMessage (const QString &title, const QString &text)
void setWindowConcise ()
void resizeWindow ()
void applySettingParameter ()
bool isLrcWidgetShowFullScreen () const
Static Public Member Functions
static MusicBottomAreaWidget * instance ()
Protected Member Functions
void createSystemTrayIcon ()
Protected Attributes
Ui::MusicApplication * m_ui
bool m_systemCloseConfig
bool m_lrcWidgetShowFullScreen
QSystemTrayIcon * m_systemTray
MusicSystemTrayMenu * m_systemTrayMenu
MusicPlatformExtras * m_platformExtras
MusicRippleSpecturmModule * m_rippleModule
Static Protected Attributes
static MusicBottomAreaWidget * m_instance = nullptr
Detailed Description
The class of the app bottom area widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicbottomareawidget.h.
Constructor & Destructor Documentation
MusicBottomAreaWidget::MusicBottomAreaWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 13 of file musicbottomareawidget.cpp.
References createSystemTrayIcon(), m_instance, m_lrcWidgetShowFullScreen, m_platformExtras, m_rippleModule, and m_systemCloseConfig.
MusicBottomAreaWidget::~MusicBottomAreaWidget ()
Definition at line 26 of file musicbottomareawidget.cpp.
References m_platformExtras, m_rippleModule, m_systemTray, and m_systemTrayMenu.
Member Function Documentation
void MusicBottomAreaWidget::applySettingParameter ()
Apply settings parameters.
Definition at line 197 of file musicbottomareawidget.cpp.
References MusicSettingManager::CloseEventMode, G_SETTING_PTR, m_rippleModule, MusicSettingManager::RippleLowPowerMode, MusicSettingManager::RippleSpectrumEnable, setDestopLrcVisible(), setSystemCloseConfig(), MusicSettingManager::ShowDesktopLrc, and MusicRippleSpecturmModule::update().
Referenced by MusicApplication::applySettingParameter(), and MusicApplication::readSystemConfigFromFile().
void MusicBottomAreaWidget::createSystemTrayIcon () protected
Create system tray icon.
Definition at line 69 of file musicbottomareawidget.cpp.
References iconActivated(), MusicApplication::instance(), m_systemTray, and m_systemTrayMenu.
Referenced by MusicBottomAreaWidget().
void MusicBottomAreaWidget::desktopLrcClosed () slot
Set desktop lrc close state.
Definition at line 252 of file musicbottomareawidget.cpp.
References G_SETTING_PTR, m_systemTrayMenu, m_ui, MusicSystemTrayMenu::showDesktopLrc(), and MusicSettingManager::ShowDesktopLrc.
Referenced by MusicLrcContainerForDesktop::closeEvent().
void MusicBottomAreaWidget::iconActivated (QSystemTrayIcon::ActivationReason reason) slot
System tray icon activate.
Definition at line 50 of file musicbottomareawidget.cpp.
References MusicApplication::instance().
Referenced by createSystemTrayIcon().
MusicBottomAreaWidget * MusicBottomAreaWidget::instance () static
Get class object instance.
Definition at line 34 of file musicbottomareawidget.cpp.
References m_instance.
Referenced by MusicLrcContainerForDesktop::closeEvent(), MusicLrcContainerForInterior::contextMenuEvent(), MusicLrcContainerForInterior::createFloatPlayWidget(), MusicLrcContainerForInterior::lrcWidgetShowFullScreen(), MusicLrcContainerForInterior::mouseDoubleClickEvent(), MusicLrcFloatWidget::musicContainerForWallpaperClicked(), MusicLrcContainerForInterior::musicSongMovieClicked(), MusicDownloadStatusModule::networkConnectionStateChanged(), MusicLrcContainerForInterior::resizeWindow(), and MusicLrcContainerForDesktop::setWindowLockedChanged().
bool MusicBottomAreaWidget::isLrcWidgetShowFullScreen () const
Current is show full container.
Definition at line 215 of file musicbottomareawidget.cpp.
References m_lrcWidgetShowFullScreen.
Referenced by MusicLrcContainerForInterior::lrcWidgetShowFullScreen(), and MusicLrcContainerForInterior::musicSongMovieClicked().
void MusicBottomAreaWidget::lockDesktopLrc (bool lock) slot
Lock or not current desktop lrc.
Definition at line 247 of file musicbottomareawidget.cpp.
References MusicSystemTrayMenu::lockDesktopLrc(), and m_systemTrayMenu.
Referenced by MusicApplication::readSystemConfigFromFile(), and MusicLrcContainerForDesktop::setWindowLockedChanged().
void MusicBottomAreaWidget::lrcWidgetShowFullScreen () slot
Show full container or not.
Definition at line 220 of file musicbottomareawidget.cpp.
References G_SETTING_PTR, MusicApplication::instance(), MusicRightAreaWidget::instance(), m_lrcWidgetShowFullScreen, m_rippleModule, m_ui, MusicRightAreaWidget::musicLrcDisplayAllButtonClicked(), MusicSettingManager::OtherSideByInMode, and MusicRippleSpecturmModule::setVisible().
Referenced by MusicLrcContainerForInterior::mouseDoubleClickEvent(), MusicLrcFloatWidget::musicContainerForWallpaperClicked(), and MusicLrcContainerForInterior::musicSongMovieClicked().
void MusicBottomAreaWidget::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 190 of file musicbottomareawidget.cpp.
References G_SETTING_PTR, m_ui, and MusicSettingManager::WidgetSize.
Referenced by MusicApplication::resizeEvent().
void MusicBottomAreaWidget::setCurrentPlayStatus (bool status) const
Set current play state button.
Definition at line 87 of file musicbottomareawidget.cpp.
References m_platformExtras, m_systemTrayMenu, MusicPlatformExtras::setCurrentPlayStatus(), and MusicSystemTrayMenu::setCurrentPlayStatus().
Referenced by MusicApplication::musicStatePlay(), MusicApplication::readSystemConfigFromFile(), and MusicApplication::showCurrentSong().
void MusicBottomAreaWidget::setDestopLrcVisible (bool status) const
Set destop lrc visible by string.
Definition at line 82 of file musicbottomareawidget.cpp.
References m_systemTrayMenu, and MusicSystemTrayMenu::showDesktopLrc().
Referenced by applySettingParameter(), and MusicApplication::readSystemConfigFromFile().
void MusicBottomAreaWidget::setLabelText (const QString & name) const
Set current song text.
Definition at line 98 of file musicbottomareawidget.cpp.
References m_systemTray, m_systemTrayMenu, and MusicSystemTrayMenu::setLabelText().
Referenced by MusicApplication::showCurrentSong().
void MusicBottomAreaWidget::setSystemCloseConfig (bool status) inline
Set system close config or not.
Definition at line 76 of file musicbottomareawidget.h.
Referenced by applySettingParameter().
void MusicBottomAreaWidget::setupUi (Ui::MusicApplication * ui)
Set up app ui.
Definition at line 39 of file musicbottomareawidget.cpp.
References MusicRippleSpecturmModule::initialize(), m_rippleModule, m_systemTrayMenu, and m_ui.
Referenced by MusicApplication::MusicApplication().
void MusicBottomAreaWidget::setVolumeValue (int value) const
Set current play volume.
Definition at line 93 of file musicbottomareawidget.cpp.
References m_systemTrayMenu, and MusicSystemTrayMenu::setVolumeValue().
Referenced by MusicApplication::musicVolumeChanged(), and MusicApplication::musicVolumeMute().
void MusicBottomAreaWidget::setWindowConcise ()
Set window concise.
Definition at line 109 of file musicbottomareawidget.cpp.
References CONCISE_WIDTH_MIN, MusicPlatformExtras::disableBlurBehindWindow(), G_SETTING_PTR, MusicApplication::instance(), MusicPlatformExtras::isDisableBlurBehindWindow(), MusicApplication::isPlaying(), m_platformExtras, m_ui, MusicUIObject::MQSSBtnConciseIn, MusicUIObject::MQSSBtnConciseOut, MusicUIObject::MQSSBtnNext, MusicUIObject::MQSSBtnPause, MusicUIObject::MQSSBtnPlay, MusicUIObject::MQSSBtnPrevious, MusicUIObject::MQSSTinyBtnNext, MusicUIObject::MQSSTinyBtnPause, MusicUIObject::MQSSTinyBtnPlay, MusicUIObject::MQSSTinyBtnPrevious, MusicSettingManager::ScreenSize, WINDOW_HEIGHT_MIN, WINDOW_WIDTH_MIN, and MusicSettingManager::WindowConciseMode.
Referenced by MusicApplication::musicWindowConciseChanged().
void MusicBottomAreaWidget::showMessage (const QString & title, const QString & text)
Set system tray message show title and context.
Definition at line 104 of file musicbottomareawidget.cpp.
References m_systemTray.
Referenced by MusicApplication::closeEvent(), and MusicDownloadStatusModule::networkConnectionStateChanged().
bool MusicBottomAreaWidget::systemCloseConfig () inline
Get system close config state.
Definition at line 80 of file musicbottomareawidget.h.
Referenced by MusicApplication::closeEvent().
bool MusicBottomAreaWidget::systemTrayIsVisible () inline
Get system tray visible state.
Definition at line 84 of file musicbottomareawidget.h.
Referenced by MusicApplication::closeEvent().
Member Data Documentation
MusicBottomAreaWidget * MusicBottomAreaWidget::m_instance = nullptr static protected
Definition at line 139 of file musicbottomareawidget.h.
Referenced by instance(), and MusicBottomAreaWidget().
bool MusicBottomAreaWidget::m_lrcWidgetShowFullScreen protected
Definition at line 133 of file musicbottomareawidget.h.
Referenced by isLrcWidgetShowFullScreen(), lrcWidgetShowFullScreen(), and MusicBottomAreaWidget().
MusicPlatformExtras* MusicBottomAreaWidget::m_platformExtras protected
Definition at line 136 of file musicbottomareawidget.h.
Referenced by MusicBottomAreaWidget(), setCurrentPlayStatus(), setWindowConcise(), and ~MusicBottomAreaWidget().
MusicRippleSpecturmModule* MusicBottomAreaWidget::m_rippleModule protected
Definition at line 137 of file musicbottomareawidget.h.
Referenced by applySettingParameter(), lrcWidgetShowFullScreen(), MusicBottomAreaWidget(), setupUi(), and ~MusicBottomAreaWidget().
bool MusicBottomAreaWidget::m_systemCloseConfig protected
Definition at line 132 of file musicbottomareawidget.h.
Referenced by MusicBottomAreaWidget().
QSystemTrayIcon* MusicBottomAreaWidget::m_systemTray protected
Definition at line 134 of file musicbottomareawidget.h.
Referenced by createSystemTrayIcon(), setLabelText(), showMessage(), and ~MusicBottomAreaWidget().
MusicSystemTrayMenu* MusicBottomAreaWidget::m_systemTrayMenu protected
Definition at line 135 of file musicbottomareawidget.h.
Referenced by createSystemTrayIcon(), desktopLrcClosed(), lockDesktopLrc(), setCurrentPlayStatus(), setDestopLrcVisible(), setLabelText(), setupUi(), setVolumeValue(), and ~MusicBottomAreaWidget().
Ui::MusicApplication* MusicBottomAreaWidget::m_ui protected
Definition at line 131 of file musicbottomareawidget.h.
Referenced by desktopLrcClosed(), lrcWidgetShowFullScreen(), resizeWindow(), setupUi(), and setWindowConcise().
The documentation for this class was generated from the following files:
TTKModule/musicbottomareawidget.h
TTKModule/musicbottomareawidget.cpp