TTKMusicPlayer: TTKThirdParty/TTKExtras/qkugou/miniblink/wke.h File Reference
wke.h File Reference
#include <windows.h>
#include <stdbool.h>
Classes
struct wkeRect
struct wkeProxy
struct wkeSettings
struct wkeViewSettings
struct _wkeClientHandler
struct wkeWindowFeatures
struct wkeWebDragData
struct wkeWebDragData::Item
struct wkeWillSendRequestInfo
struct wkeMemBuf
struct wkePostBodyElement
struct wkePostBodyElements
struct wkeTempCallbackInfo
struct wkeMediaLoadInfo
struct wkeDraggableRegion
struct tagjsData
Macros
#define JS_CALL __fastcall
#define WKE_CALL_TYPE __cdecl
#define WKE_DEFINE_ITERATOR0(returnVal, name, description)
#define WKE_DEFINE_ITERATOR1(returnVal, name, p1, description)
#define WKE_DEFINE_ITERATOR2(returnVal, name, p1, p2, description)
#define WKE_DEFINE_ITERATOR3(returnVal, name, p1, p2, p3, description)
#define WKE_DEFINE_ITERATOR4(returnVal, name, p1, p2, p3, p4, description)
#define WKE_DEFINE_ITERATOR5(returnVal, name, p1, p2, p3, p4, p5, description)
#define WKE_DEFINE_ITERATOR6(returnVal, name, p1, p2, p3, p4, p5, p6, description)
#define WKE_DEFINE_ITERATOR11(returnVal, name, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, description)
#define WKE_DECLARE_ITERATOR0(returnVal, name, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name();
#define WKE_DECLARE_ITERATOR1(returnVal, name, p1, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1);
#define WKE_DECLARE_ITERATOR2(returnVal, name, p1, p2, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2);
#define WKE_DECLARE_ITERATOR3(returnVal, name, p1, p2, p3, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3);
#define WKE_DECLARE_ITERATOR4(returnVal, name, p1, p2, p3, p4, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4);
#define WKE_DECLARE_ITERATOR5(returnVal, name, p1, p2, p3, p4, p5, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4, p5);
#define WKE_DECLARE_ITERATOR6(returnVal, name, p1, p2, p3, p4, p5, p6, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4, p5, p6);
#define WKE_DECLARE_ITERATOR11(returnVal, name, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
#define WKE_GET_PTR_ITERATOR(name)
#define WKE_GET_PTR_ITERATOR0(returnVal, name, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR1(returnVal, name, p1, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR2(returnVal, name, p1, p2, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR3(returnVal, name, p1, p2, p3, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR4(returnVal, name, p1, p2, p3, p4, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR5(returnVal, name, p1, p2, p3, p4, p5, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR6(returnVal, name, p1, p2, p3, p4, p5, p6, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_GET_PTR_ITERATOR11(returnVal, name, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, description) WKE_GET_PTR_ITERATOR(name);
#define WKE_FOR_EACH_DEFINE_FUNCTION(ITERATOR0, ITERATOR1, ITERATOR2, ITERATOR3, ITERATOR4, ITERATOR5, ITERATOR6, ITERATOR11)
Typedefs
typedef unsigned short wchar_t
typedef char utf8
typedef void * jsExecState
typedef __int64 jsValue
typedef struct _tagWkeWebView * wkeWebView
typedef struct _tagWkeString * wkeString
typedef void * wkeWebFrameHandle
typedef void *(* FILE_OPEN_) (const char *path)
typedef void(* FILE_CLOSE_) (void *handle)
typedef size_t(* FILE_SIZE) (void *handle)
typedef int(* FILE_READ) (void *handle, void *buffer, size_t size)
typedef int(* FILE_SEEK) (void *handle, int offset, int origin)
typedef FILE_OPEN_ WKE_FILE_OPEN
typedef FILE_CLOSE_ WKE_FILE_CLOSE
typedef FILE_SIZE WKE_FILE_SIZE
typedef FILE_READ WKE_FILE_READ
typedef FILE_SEEK WKE_FILE_SEEK
typedef bool(* WKE_EXISTS_FILE) (const char *path)
typedef void(* ON_TITLE_CHANGED) (const struct _wkeClientHandler *clientHandler, const wkeString title)
typedef void(* ON_URL_CHANGED) (const struct _wkeClientHandler *clientHandler, const wkeString url)
typedef struct _wkeClientHandler wkeClientHandler
typedef bool(* wkeCookieVisitor) (void *params, const char *name, const char *value, const char *domain, const char *path, int secure, int httpOnly, int *expires)
typedef wkeWebDragOperation wkeWebDragOperationsMask
typedef void(* wkeTitleChangedCallback) (wkeWebView webView, void *param, const wkeString title)
typedef void(* wkeURLChangedCallback) (wkeWebView webView, void *param, const wkeString url)
typedef void(* wkeURLChangedCallback2) (wkeWebView webView, void *param, wkeWebFrameHandle frameId, const wkeString url)
typedef void(* wkePaintUpdatedCallback) (wkeWebView webView, void *param, const HDC hdc, int x, int y, int cx, int cy)
typedef void(* wkeAlertBoxCallback) (wkeWebView webView, void *param, const wkeString msg)
typedef bool(* wkeConfirmBoxCallback) (wkeWebView webView, void *param, const wkeString msg)
typedef bool(* wkePromptBoxCallback) (wkeWebView webView, void *param, const wkeString msg, const wkeString defaultResult, wkeString result)
typedef bool(* wkeNavigationCallback) (wkeWebView webView, void *param, wkeNavigationType navigationType, const wkeString url)
typedef wkeWebView(* wkeCreateViewCallback) (wkeWebView webView, void *param, wkeNavigationType navigationType, const wkeString url, const wkeWindowFeatures *windowFeatures)
typedef void(* wkeDocumentReadyCallback) (wkeWebView webView, void *param)
typedef void(* wkeDocumentReady2Callback) (wkeWebView webView, void *param, wkeWebFrameHandle frameId)
typedef void(* wkeWillMediaLoadCallback) (wkeWebView webView, void *param, const char *url, wkeMediaLoadInfo *info)
typedef void(* wkeOnOtherLoadCallback) (wkeWebView webView, void *param, wkeOtherLoadType type, wkeTempCallbackInfo *info)
typedef void(* wkeLoadingFinishCallback) (wkeWebView webView, void *param, const wkeString url, wkeLoadingResult result, const wkeString failedReason)
typedef bool(* wkeDownloadCallback) (wkeWebView webView, void *param, const char *url)
typedef void(* wkeConsoleCallback) (wkeWebView webView, void *param, wkeConsoleLevel level, const wkeString message, const wkeString sourceName, unsigned sourceLine, const wkeString stackTrace)
typedef void(* wkeOnCallUiThread) (wkeWebView webView, void *paramOnInThread)
typedef void(* wkeCallUiThread) (wkeWebView webView, wkeOnCallUiThread func, void *param)
typedef bool(* wkeLoadUrlBeginCallback) (wkeWebView webView, void *param, const char *url, void *job)
typedef void(* wkeLoadUrlEndCallback) (wkeWebView webView, void *param, const char *url, void *job, void *buf, int len)
typedef void(* wkeDidCreateScriptContextCallback) (wkeWebView webView, void *param, wkeWebFrameHandle frameId, void *context, int extensionGroup, int worldId)
typedef void(* wkeWillReleaseScriptContextCallback) (wkeWebView webView, void *param, wkeWebFrameHandle frameId, void *context, int worldId)
typedef bool(* wkeNetResponseCallback) (wkeWebView webView, void *param, const char *url, void *job)
typedef void * v8ContextPtr
typedef void * v8Isolate
typedef bool(* wkeWindowClosingCallback) (wkeWebView webWindow, void *param)
typedef void(* wkeWindowDestroyCallback) (wkeWebView webWindow, void *param)
typedef void(* wkeDraggableRegionsChangedCallback) (wkeWebView webWindow, void *param, const wkeDraggableRegion *rects, int rectCount)
typedef jsValue(* wkeJsNativeFunction) (jsExecState es, void *param)
typedef jsValue(* jsGetPropertyCallback) (jsExecState es, jsValue object, const char *propertyName)
typedef bool(* jsSetPropertyCallback) (jsExecState es, jsValue object, const char *propertyName, jsValue value)
typedef jsValue(* jsCallAsFunctionCallback) (jsExecState es, jsValue object, jsValue *args, int argCount)
typedef void(* jsFinalizeCallback) (struct tagjsData *data)
typedef struct tagjsData jsData
Enumerations
enum wkeMouseFlags {
WKE_LBUTTON = 0x01, WKE_RBUTTON = 0x02, WKE_SHIFT = 0x04, WKE_CONTROL = 0x08,
WKE_MBUTTON = 0x10
}
enum wkeKeyFlags { WKE_EXTENDED = 0x0100, WKE_REPEAT = 0x4000 }
enum wkeMouseMsg {
WKE_MSG_MOUSEMOVE = 0x0200, WKE_MSG_LBUTTONDOWN = 0x0201, WKE_MSG_LBUTTONUP = 0x0202, WKE_MSG_LBUTTONDBLCLK = 0x0203,
WKE_MSG_RBUTTONDOWN = 0x0204, WKE_MSG_RBUTTONUP = 0x0205, WKE_MSG_RBUTTONDBLCLK = 0x0206, WKE_MSG_MBUTTONDOWN = 0x0207,
WKE_MSG_MBUTTONUP = 0x0208, WKE_MSG_MBUTTONDBLCLK = 0x0209, WKE_MSG_MOUSEWHEEL = 0x020A
}
enum wkeProxyType {
WKE_PROXY_NONE, WKE_PROXY_HTTP, WKE_PROXY_SOCKS4, WKE_PROXY_SOCKS4A,
WKE_PROXY_SOCKS5, WKE_PROXY_SOCKS5HOSTNAME
}
enum wkeSettingMask { WKE_SETTING_PROXY = 1, WKE_SETTING_PAINTCALLBACK_IN_OTHER_THREAD = 1 << 2 }
enum wkeCookieCommand { wkeCookieCommandClearAllCookies, wkeCookieCommandClearSessionCookies, wkeCookieCommandFlushCookiesToFile, wkeCookieCommandReloadCookiesFromFile }
enum wkeNavigationType {
WKE_NAVIGATION_TYPE_LINKCLICK, WKE_NAVIGATION_TYPE_FORMSUBMITTE, WKE_NAVIGATION_TYPE_BACKFORWARD, WKE_NAVIGATION_TYPE_RELOAD,
WKE_NAVIGATION_TYPE_FORMRESUBMITT, WKE_NAVIGATION_TYPE_OTHER
}
enum WkeCursorInfoType {
WkeCursorInfoPointer, WkeCursorInfoCross, WkeCursorInfoHand, WkeCursorInfoIBeam,
WkeCursorInfoWait, WkeCursorInfoHelp, WkeCursorInfoEastResize, WkeCursorInfoNorthResize,
WkeCursorInfoNorthEastResize, WkeCursorInfoNorthWestResize, WkeCursorInfoSouthResize, WkeCursorInfoSouthEastResize,
WkeCursorInfoSouthWestResize, WkeCursorInfoWestResize, WkeCursorInfoNorthSouthResize, WkeCursorInfoEastWestResize,
WkeCursorInfoNorthEastSouthWestResize, WkeCursorInfoNorthWestSouthEastResize, WkeCursorInfoColumnResize, WkeCursorInfoRowResize,
WkeCursorInfoMiddlePanning, WkeCursorInfoEastPanning, WkeCursorInfoNorthPanning, WkeCursorInfoNorthEastPanning,
WkeCursorInfoNorthWestPanning, WkeCursorInfoSouthPanning, WkeCursorInfoSouthEastPanning, WkeCursorInfoSouthWestPanning,
WkeCursorInfoWestPanning, WkeCursorInfoMove, WkeCursorInfoVerticalText, WkeCursorInfoCell,
WkeCursorInfoContextMenu, WkeCursorInfoAlias, WkeCursorInfoProgress, WkeCursorInfoNoDrop,
WkeCursorInfoCopy, WkeCursorInfoNone, WkeCursorInfoNotAllowed, WkeCursorInfoZoomIn,
WkeCursorInfoZoomOut, WkeCursorInfoGrab, WkeCursorInfoGrabbing, WkeCursorInfoCustom
}
enum wkeWebDragOperation {
wkeWebDragOperationNone = 0, wkeWebDragOperationCopy = 1, wkeWebDragOperationLink = 2, wkeWebDragOperationGeneric = 4,
wkeWebDragOperationPrivate = 8, wkeWebDragOperationMove = 16, wkeWebDragOperationDelete = 32, wkeWebDragOperationEvery = 0xffffffff
}
enum wkeResourceType {
WKE_RESOURCE_TYPE_MAIN_FRAME = 0, WKE_RESOURCE_TYPE_SUB_FRAME = 1, WKE_RESOURCE_TYPE_STYLESHEET = 2, WKE_RESOURCE_TYPE_SCRIPT = 3,
WKE_RESOURCE_TYPE_IMAGE = 4, WKE_RESOURCE_TYPE_FONT_RESOURCE = 5, WKE_RESOURCE_TYPE_SUB_RESOURCE = 6, WKE_RESOURCE_TYPE_OBJECT = 7,
WKE_RESOURCE_TYPE_MEDIA = 8, WKE_RESOURCE_TYPE_WORKER = 9, WKE_RESOURCE_TYPE_SHARED_WORKER = 10, WKE_RESOURCE_TYPE_PREFETCH = 11,
WKE_RESOURCE_TYPE_FAVICON = 12, WKE_RESOURCE_TYPE_XHR = 13, WKE_RESOURCE_TYPE_PING = 14, WKE_RESOURCE_TYPE_SERVICE_WORKER = 15,
WKE_RESOURCE_TYPE_LAST_TYPE
}
enum wkeHttBodyElementType { wkeHttBodyElementTypeData, wkeHttBodyElementTypeFile }
enum wkeOtherLoadType {
WKE_DID_START_LOADING, WKE_DID_STOP_LOADING, WKE_DID_NAVIGATE, WKE_DID_NAVIGATE_IN_PAGE,
WKE_DID_GET_RESPONSE_DETAILS, WKE_DID_GET_REDIRECT_REQUEST, WKE_DID_POST_REQUEST
}
enum wkeLoadingResult { WKE_LOADING_SUCCEEDED, WKE_LOADING_FAILED, WKE_LOADING_CANCELED }
enum wkeConsoleLevel {
wkeLevelDebug = 4, wkeLevelLog = 1, wkeLevelInfo = 5, wkeLevelWarning = 2,
wkeLevelError = 3, wkeLevelRevokedError = 6, wkeLevelLast = wkeLevelInfo
}
enum wkeWindowType { WKE_WINDOW_TYPE_POPUP, WKE_WINDOW_TYPE_TRANSPARENT, WKE_WINDOW_TYPE_CONTROL }
enum jsType {
JSTYPE_NUMBER, JSTYPE_STRING, JSTYPE_BOOLEAN, JSTYPE_OBJECT,
JSTYPE_FUNCTION, JSTYPE_UNDEFINED, JSTYPE_ARRAY
}
Functions
typedef jsValue (JS_CALL *jsNativeFunction)(jsExecState es)
WKE_FOR_EACH_DEFINE_FUNCTION (WKE_DEFINE_ITERATOR0, WKE_DEFINE_ITERATOR1, WKE_DEFINE_ITERATOR2, WKE_DEFINE_ITERATOR3, WKE_DEFINE_ITERATOR4, WKE_DEFINE_ITERATOR5, WKE_DEFINE_ITERATOR6, WKE_DEFINE_ITERATOR11) typedef void(WKE_CALL_TYPE *FN_wkeInitializeEx)(const wkeSettings *settings)
__declspec (selectany) const wchar_t *kWkeDllPath
void wkeSetWkeDllPath (const wchar_t *dllPath)
void wkeInitializeEx (const wkeSettings *settings)
void wkeInit ()
void wkeInitialize ()
Macro Definition Documentation
#define JS_CALL __fastcall
Definition at line 446 of file wke.h.
#define WKE_CALL_TYPE __cdecl
Definition at line 579 of file wke.h.
#define WKE_DECLARE_ITERATOR0 (returnVal, name, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name();
Definition at line 615 of file wke.h.
#define WKE_DECLARE_ITERATOR1 (returnVal, name, p1, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1);
Definition at line 618 of file wke.h.
#define WKE_DECLARE_ITERATOR11 (returnVal, name, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
Definition at line 636 of file wke.h.
#define WKE_DECLARE_ITERATOR2 (returnVal, name, p1, p2, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2);
Definition at line 621 of file wke.h.
#define WKE_DECLARE_ITERATOR3 (returnVal, name, p1, p2, p3, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3);
Definition at line 624 of file wke.h.
#define WKE_DECLARE_ITERATOR4 (returnVal, name, p1, p2, p3, p4, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4);
Definition at line 627 of file wke.h.
#define WKE_DECLARE_ITERATOR5 (returnVal, name, p1, p2, p3, p4, p5, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4, p5);
Definition at line 630 of file wke.h.
#define WKE_DECLARE_ITERATOR6 (returnVal, name, p1, p2, p3, p4, p5, p6, description) extern "C" __declspec(dllexport) returnVal WKE_CALL_TYPE name(p1, p2, p3, p4, p5, p6);
Definition at line 633 of file wke.h.
#define WKE_DEFINE_ITERATOR0 (returnVal, name, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 581 of file wke.h.
#define WKE_DEFINE_ITERATOR1 (returnVal, name, p1, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 585 of file wke.h.
#define WKE_DEFINE_ITERATOR11 (returnVal, name, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 609 of file wke.h.
#define WKE_DEFINE_ITERATOR2 (returnVal, name, p1, p2, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1, p2); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 589 of file wke.h.
#define WKE_DEFINE_ITERATOR3 (returnVal, name, p1, p2, p3, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1, p2, p3); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 593 of file wke.h.
#define WKE_DEFINE_ITERATOR4 (returnVal, name, p1, p2, p3, p4, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1, p2, p3, p4); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 597 of file wke.h.
#define WKE_DEFINE_ITERATOR5 (returnVal, name, p1, p2, p3, p4, p5, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1, p2, p3, p4, p5); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 601 of file wke.h.
#define WKE_DEFINE_ITERATOR6 (returnVal, name, p1, p2, p3, p4, p5, p6, description)
Value:
typedef returnVal(WKE_CALL_TYPE* FN_##name)(p1, p2, p3, p4, p5, p6); \
    __declspec(selectany) FN_##name name = ((FN_##name)0);
Definition at line 605 of file wke.h.
#define WKE_FOR_EACH_DEFINE_FUNCTION (ITERATOR0, ITERATOR1, ITERATOR2, ITERATOR3, ITERATOR4, ITERATOR5, ITERATOR6, ITERATOR11)
Definition at line 672 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR (name)
Value:
name = (FN_##name)GetProcAddress(hMod, #name); \
    if (!name) \
        MessageBoxA(((HWND)0), "wke api not found", #name, 0);
Definition at line 641 of file wke.h.
#define WKE_GET_PTR_ITERATOR0 (returnVal, name, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 646 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR1 (returnVal, name, p1, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 649 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR11 (returnVal, name, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 667 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR2 (returnVal, name, p1, p2, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 652 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR3 (returnVal, name, p1, p2, p3, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 655 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR4 (returnVal, name, p1, p2, p3, p4, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 658 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR5 (returnVal, name, p1, p2, p3, p4, p5, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 661 of file wke.h.
Referenced by wkeInitializeEx().
#define WKE_GET_PTR_ITERATOR6 (returnVal, name, p1, p2, p3, p4, p5, p6, description) WKE_GET_PTR_ITERATOR(name);
Definition at line 664 of file wke.h.
Referenced by wkeInitializeEx().
Typedef Documentation
typedef void(* FILE_CLOSE_) (void *handle)
Definition at line 123 of file wke.h.
typedef void*(* FILE_OPEN_) (const char *path)
Definition at line 122 of file wke.h.
typedef int(* FILE_READ) (void *handle, void *buffer, size_t size)
Definition at line 125 of file wke.h.
typedef int(* FILE_SEEK) (void *handle, int offset, int origin)
Definition at line 126 of file wke.h.
typedef size_t(* FILE_SIZE) (void *handle)
Definition at line 124 of file wke.h.
typedef jsValue(* jsCallAsFunctionCallback) (jsExecState es, jsValue object, jsValue *args, int argCount)
Definition at line 464 of file wke.h.
typedef struct tagjsData jsData
typedef void* jsExecState
Definition at line 66 of file wke.h.
typedef void(* jsFinalizeCallback) (struct tagjsData *data)
Definition at line 466 of file wke.h.
typedef jsValue(* jsGetPropertyCallback) (jsExecState es, jsValue object, const char *propertyName)
Definition at line 462 of file wke.h.
typedef bool(* jsSetPropertyCallback) (jsExecState es, jsValue object, const char *propertyName, jsValue value)
Definition at line 463 of file wke.h.
typedef __int64 jsValue
Definition at line 71 of file wke.h.
typedef void(* ON_TITLE_CHANGED) (const struct _wkeClientHandler *clientHandler, const wkeString title)
Definition at line 136 of file wke.h.
typedef void(* ON_URL_CHANGED) (const struct _wkeClientHandler *clientHandler, const wkeString url)
Definition at line 137 of file wke.h.
typedef char utf8
Definition at line 64 of file wke.h.
typedef void* v8ContextPtr
Definition at line 425 of file wke.h.
typedef void* v8Isolate
Definition at line 426 of file wke.h.
typedef unsigned short wchar_t
Definition at line 57 of file wke.h.
typedef bool(* WKE_EXISTS_FILE) (const char *path)
Definition at line 133 of file wke.h.
typedef FILE_CLOSE_ WKE_FILE_CLOSE
Definition at line 129 of file wke.h.
typedef FILE_OPEN_ WKE_FILE_OPEN
Definition at line 128 of file wke.h.
typedef FILE_READ WKE_FILE_READ
Definition at line 131 of file wke.h.
typedef FILE_SEEK WKE_FILE_SEEK
Definition at line 132 of file wke.h.
typedef FILE_SIZE WKE_FILE_SIZE
Definition at line 130 of file wke.h.
typedef void(* wkeAlertBoxCallback) (wkeWebView webView, void *param, const wkeString msg)
Definition at line 364 of file wke.h.
typedef void(* wkeCallUiThread) (wkeWebView webView, wkeOnCallUiThread func, void *param)
Definition at line 416 of file wke.h.
typedef struct _wkeClientHandler wkeClientHandler
typedef bool(* wkeConfirmBoxCallback) (wkeWebView webView, void *param, const wkeString msg)
Definition at line 365 of file wke.h.
typedef void(* wkeConsoleCallback) (wkeWebView webView, void *param, wkeConsoleLevel level, const wkeString message, const wkeString sourceName, unsigned sourceLine, const wkeString stackTrace)
Definition at line 413 of file wke.h.
typedef bool(* wkeCookieVisitor) (void *params, const char *name, const char *value, const char *domain, const char *path,int secure,int httpOnly,int *expires)
Definition at line 144 of file wke.h.
typedef wkeWebView(* wkeCreateViewCallback)(wkeWebView webView, void *param, wkeNavigationType navigationType, const wkeString url, const wkeWindowFeatures *windowFeatures)
Definition at line 368 of file wke.h.
typedef void(* wkeDidCreateScriptContextCallback) (wkeWebView webView, void *param, wkeWebFrameHandle frameId, void *context, int extensionGroup, int worldId)
Definition at line 421 of file wke.h.
typedef void(* wkeDocumentReady2Callback)(wkeWebView webView, void *param, wkeWebFrameHandle frameId)
Definition at line 370 of file wke.h.
typedef void(* wkeDocumentReadyCallback)(wkeWebView webView, void *param)
Definition at line 369 of file wke.h.
typedef bool(* wkeDownloadCallback) (wkeWebView webView, void *param, const char *url)
Definition at line 402 of file wke.h.
typedef void(* wkeDraggableRegionsChangedCallback) (wkeWebView webWindow, void *param, const wkeDraggableRegion *rects, int rectCount)
Definition at line 443 of file wke.h.
typedef jsValue(* wkeJsNativeFunction) (jsExecState es, void *param)
Definition at line 449 of file wke.h.
typedef void(* wkeLoadingFinishCallback) (wkeWebView webView, void *param, const wkeString url, wkeLoadingResult result, const wkeString failedReason)
Definition at line 401 of file wke.h.
typedef bool(* wkeLoadUrlBeginCallback) (wkeWebView webView, void *param, const char *url, void *job)
Definition at line 419 of file wke.h.
typedef void(* wkeLoadUrlEndCallback) (wkeWebView webView, void *param, const char *url, void *job, void *buf, int len)
Definition at line 420 of file wke.h.
typedef bool(* wkeNavigationCallback) (wkeWebView webView, void *param, wkeNavigationType navigationType, const wkeString url)
Definition at line 367 of file wke.h.
typedef bool(* wkeNetResponseCallback) (wkeWebView webView, void *param, const char *url, void *job)
Definition at line 423 of file wke.h.
typedef void(* wkeOnCallUiThread) (wkeWebView webView, void *paramOnInThread)
Definition at line 415 of file wke.h.
typedef void(* wkeOnOtherLoadCallback) (wkeWebView webView, void *param, wkeOtherLoadType type, wkeTempCallbackInfo *info)
Definition at line 393 of file wke.h.
typedef void(* wkePaintUpdatedCallback) (wkeWebView webView, void *param, const HDC hdc, int x, int y, int cx, int cy)
Definition at line 363 of file wke.h.
typedef bool(* wkePromptBoxCallback) (wkeWebView webView, void *param, const wkeString msg, const wkeString defaultResult, wkeString result)
Definition at line 366 of file wke.h.
typedef struct _tagWkeString* wkeString
Definition at line 85 of file wke.h.
typedef void(* wkeTitleChangedCallback) (wkeWebView webView, void *param, const wkeString title)
Definition at line 360 of file wke.h.
typedef void(* wkeURLChangedCallback) (wkeWebView webView, void *param, const wkeString url)
Definition at line 361 of file wke.h.
typedef void(* wkeURLChangedCallback2) (wkeWebView webView, void *param, wkeWebFrameHandle frameId, const wkeString url)
Definition at line 362 of file wke.h.
typedef wkeWebDragOperation wkeWebDragOperationsMask
Definition at line 290 of file wke.h.
typedef void* wkeWebFrameHandle
Definition at line 120 of file wke.h.
typedef struct _tagWkeWebView* wkeWebView
Definition at line 82 of file wke.h.
typedef void(* wkeWillMediaLoadCallback) (wkeWebView webView, void *param, const char *url, wkeMediaLoadInfo *info)
Definition at line 382 of file wke.h.
typedef void(* wkeWillReleaseScriptContextCallback) (wkeWebView webView, void *param, wkeWebFrameHandle frameId, void *context, int worldId)
Definition at line 422 of file wke.h.
typedef bool(* wkeWindowClosingCallback) (wkeWebView webWindow, void *param)
Definition at line 436 of file wke.h.
typedef void(* wkeWindowDestroyCallback) (wkeWebView webWindow, void *param)
Definition at line 437 of file wke.h.
Enumeration Type Documentation
enum jsType
Enumerator
JSTYPE_NUMBER
JSTYPE_STRING
JSTYPE_BOOLEAN
JSTYPE_OBJECT
JSTYPE_FUNCTION
JSTYPE_UNDEFINED
JSTYPE_ARRAY
Definition at line 451 of file wke.h.
enum wkeConsoleLevel
Enumerator
wkeLevelDebug
wkeLevelLog
wkeLevelInfo
wkeLevelWarning
wkeLevelError
wkeLevelRevokedError
wkeLevelLast
Definition at line 404 of file wke.h.
enum wkeCookieCommand
Enumerator
wkeCookieCommandClearAllCookies
wkeCookieCommandClearSessionCookies
wkeCookieCommandFlushCookiesToFile
wkeCookieCommandReloadCookiesFromFile
Definition at line 155 of file wke.h.
enum WkeCursorInfoType
Enumerator
WkeCursorInfoPointer
WkeCursorInfoCross
WkeCursorInfoHand
WkeCursorInfoIBeam
WkeCursorInfoWait
WkeCursorInfoHelp
WkeCursorInfoEastResize
WkeCursorInfoNorthResize
WkeCursorInfoNorthEastResize
WkeCursorInfoNorthWestResize
WkeCursorInfoSouthResize
WkeCursorInfoSouthEastResize
WkeCursorInfoSouthWestResize
WkeCursorInfoWestResize
WkeCursorInfoNorthSouthResize
WkeCursorInfoEastWestResize
WkeCursorInfoNorthEastSouthWestResize
WkeCursorInfoNorthWestSouthEastResize
WkeCursorInfoColumnResize
WkeCursorInfoRowResize
WkeCursorInfoMiddlePanning
WkeCursorInfoEastPanning
WkeCursorInfoNorthPanning
WkeCursorInfoNorthEastPanning
WkeCursorInfoNorthWestPanning
WkeCursorInfoSouthPanning
WkeCursorInfoSouthEastPanning
WkeCursorInfoSouthWestPanning
WkeCursorInfoWestPanning
WkeCursorInfoMove
WkeCursorInfoVerticalText
WkeCursorInfoCell
WkeCursorInfoContextMenu
WkeCursorInfoAlias
WkeCursorInfoProgress
WkeCursorInfoNoDrop
WkeCursorInfoCopy
WkeCursorInfoNone
WkeCursorInfoNotAllowed
WkeCursorInfoZoomIn
WkeCursorInfoZoomOut
WkeCursorInfoGrab
WkeCursorInfoGrabbing
WkeCursorInfoCustom
Definition at line 171 of file wke.h.
enum wkeHttBodyElementType
Enumerator
wkeHttBodyElementTypeData
wkeHttBodyElementTypeFile
Definition at line 325 of file wke.h.
enum wkeKeyFlags
Enumerator
WKE_EXTENDED
WKE_REPEAT
Definition at line 36 of file wke.h.
enum wkeLoadingResult
Enumerator
WKE_LOADING_SUCCEEDED
WKE_LOADING_FAILED
WKE_LOADING_CANCELED
Definition at line 395 of file wke.h.
enum wkeMouseFlags
Enumerator
WKE_LBUTTON
WKE_RBUTTON
WKE_SHIFT
WKE_CONTROL
WKE_MBUTTON
Definition at line 28 of file wke.h.
enum wkeMouseMsg
Enumerator
WKE_MSG_MOUSEMOVE
WKE_MSG_LBUTTONDOWN
WKE_MSG_LBUTTONUP
WKE_MSG_LBUTTONDBLCLK
WKE_MSG_RBUTTONDOWN
WKE_MSG_RBUTTONUP
WKE_MSG_RBUTTONDBLCLK
WKE_MSG_MBUTTONDOWN
WKE_MSG_MBUTTONUP
WKE_MSG_MBUTTONDBLCLK
WKE_MSG_MOUSEWHEEL
Definition at line 41 of file wke.h.
enum wkeNavigationType
Enumerator
WKE_NAVIGATION_TYPE_LINKCLICK
WKE_NAVIGATION_TYPE_FORMSUBMITTE
WKE_NAVIGATION_TYPE_BACKFORWARD
WKE_NAVIGATION_TYPE_RELOAD
WKE_NAVIGATION_TYPE_FORMRESUBMITT
WKE_NAVIGATION_TYPE_OTHER
Definition at line 162 of file wke.h.
enum wkeOtherLoadType
Enumerator
WKE_DID_START_LOADING
WKE_DID_STOP_LOADING
WKE_DID_NAVIGATE
WKE_DID_NAVIGATE_IN_PAGE
WKE_DID_GET_RESPONSE_DETAILS
WKE_DID_GET_REDIRECT_REQUEST
WKE_DID_POST_REQUEST
Definition at line 384 of file wke.h.
enum wkeProxyType
Enumerator
WKE_PROXY_NONE
WKE_PROXY_HTTP
WKE_PROXY_SOCKS4
WKE_PROXY_SOCKS4A
WKE_PROXY_SOCKS5
WKE_PROXY_SOCKS5HOSTNAME
Definition at line 88 of file wke.h.
enum wkeResourceType
Enumerator
WKE_RESOURCE_TYPE_MAIN_FRAME
WKE_RESOURCE_TYPE_SUB_FRAME
WKE_RESOURCE_TYPE_STYLESHEET
WKE_RESOURCE_TYPE_SCRIPT
WKE_RESOURCE_TYPE_IMAGE
WKE_RESOURCE_TYPE_FONT_RESOURCE
WKE_RESOURCE_TYPE_SUB_RESOURCE
WKE_RESOURCE_TYPE_OBJECT
WKE_RESOURCE_TYPE_MEDIA
WKE_RESOURCE_TYPE_WORKER
WKE_RESOURCE_TYPE_SHARED_WORKER
WKE_RESOURCE_TYPE_PREFETCH
WKE_RESOURCE_TYPE_FAVICON
WKE_RESOURCE_TYPE_XHR
WKE_RESOURCE_TYPE_PING
WKE_RESOURCE_TYPE_SERVICE_WORKER
WKE_RESOURCE_TYPE_LAST_TYPE
Definition at line 292 of file wke.h.
enum wkeSettingMask
Enumerator
WKE_SETTING_PROXY
WKE_SETTING_PAINTCALLBACK_IN_OTHER_THREAD
Definition at line 105 of file wke.h.
enum wkeWebDragOperation
Enumerator
wkeWebDragOperationNone
wkeWebDragOperationCopy
wkeWebDragOperationLink
wkeWebDragOperationGeneric
wkeWebDragOperationPrivate
wkeWebDragOperationMove
wkeWebDragOperationDelete
wkeWebDragOperationEvery
Definition at line 279 of file wke.h.
enum wkeWindowType
Enumerator
WKE_WINDOW_TYPE_POPUP
WKE_WINDOW_TYPE_TRANSPARENT
WKE_WINDOW_TYPE_CONTROL
Definition at line 429 of file wke.h.
Function Documentation
__declspec (selectany) const
typedef jsValue (JS_CALL * jsNativeFunction)
WKE_FOR_EACH_DEFINE_FUNCTION (WKE_DEFINE_ITERATOR0 , WKE_DEFINE_ITERATOR1 , WKE_DEFINE_ITERATOR2 , WKE_DEFINE_ITERATOR3 , WKE_DEFINE_ITERATOR4 , WKE_DEFINE_ITERATOR5 , WKE_DEFINE_ITERATOR6 , WKE_DEFINE_ITERATOR11) const
void wkeInit () inline
Definition at line 1075 of file wke.h.
References wkeInitializeEx().
void wkeInitialize () inline
Definition at line 1081 of file wke.h.
References wkeInitializeEx().
Referenced by Miniblink::initialize().
void wkeInitializeEx (const wkeSettings * settings) inline
Definition at line 1062 of file wke.h.
References WKE_FOR_EACH_DEFINE_FUNCTION, WKE_GET_PTR_ITERATOR0, WKE_GET_PTR_ITERATOR1, WKE_GET_PTR_ITERATOR11, WKE_GET_PTR_ITERATOR2, WKE_GET_PTR_ITERATOR3, WKE_GET_PTR_ITERATOR4, WKE_GET_PTR_ITERATOR5, and WKE_GET_PTR_ITERATOR6.
Referenced by wkeInit(), and wkeInitialize().
void wkeSetWkeDllPath (const wchar_t * dllPath) inline
Definition at line 1057 of file wke.h.
Referenced by Miniblink::initialize().