TTKMusicplayer: MusicCloudSharedSongWidget Class Reference
MusicCloudSharedSongWidget Class Reference
The class of the cloud share song widget.
#include <musiccloudsharedsongwidget.h>
Public Member Functions
MusicCloudSharedSongWidget (QWidget *parent=0)
~MusicCloudSharedSongWidget ()
void getKey ()
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Attributes
QLabel * m_statusLabel
MusicCloudSharedSongTableWidget * m_tableWidget
Detailed Description
The class of the cloud share song widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 167 of file musiccloudsharedsongwidget.h.
Constructor & Destructor Documentation
MusicCloudSharedSongWidget::MusicCloudSharedSongWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 412 of file musiccloudsharedsongwidget.cpp.
References m_statusLabel, m_tableWidget, and MusicUIObject::MPushButtonStyle01.
MusicCloudSharedSongWidget::~MusicCloudSharedSongWidget ()
Definition at line 448 of file musiccloudsharedsongwidget.cpp.
References m_statusLabel, and m_tableWidget.
Member Function Documentation
void MusicCloudSharedSongWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 471 of file musiccloudsharedsongwidget.cpp.
QString MusicCloudSharedSongWidget::getClassName () static
Get class object name.
Definition at line 454 of file musiccloudsharedsongwidget.cpp.
void MusicCloudSharedSongWidget::getKey ()
Get query cloud id keys.
Definition at line 459 of file musiccloudsharedsongwidget.cpp.
References MusicCloudSharedSongTableWidget::getKey(), m_tableWidget, MusicToastLabel::popup(), MusicToastLabel::setFontMargin(), MusicToastLabel::setFontSize(), and MusicToastLabel::setText().
Referenced by MusicLeftAreaWidget::musicStackedCloudWidgetChanged().
Member Data Documentation
QLabel* MusicCloudSharedSongWidget::m_statusLabel protected
Definition at line 194 of file musiccloudsharedsongwidget.h.
Referenced by MusicCloudSharedSongWidget(), and ~MusicCloudSharedSongWidget().
MusicCloudSharedSongTableWidget* MusicCloudSharedSongWidget::m_tableWidget protected
Definition at line 195 of file musiccloudsharedsongwidget.h.
Referenced by getKey(), MusicCloudSharedSongWidget(), and ~MusicCloudSharedSongWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudsharedsongwidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudsharedsongwidget.cpp