TTKMusicPlayer: TTKDesktopWrapper Class Reference
TTKDesktopWrapper Class Reference
The class of the desktop screen wrapper.
#include <ttkdesktopwrapper.h>
Classes
struct TaskbarInfo
Static Public Member Functions
static TaskbarInfo screenTaskbar (int index=0)
static QRect availableGeometry (int index=0)
static QRect screenGeometry (int index=0)
static QRect geometry ()
static QPixmap grabWidget (QWidget *widget, const QRect &rect)
static QPixmap grabWindow (int x=0, int y=0, int w=-1, int h=-1)
Detailed Description
The class of the desktop screen wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file ttkdesktopwrapper.h.
Member Function Documentation
QRect TTKDesktopWrapper::availableGeometry (int index = 0) static
Get available geometry by given screen index.
Definition at line 44 of file ttkdesktopwrapper.cpp.
Referenced by screenTaskbar().
QRect TTKDesktopWrapper::geometry () static
Get all screen geometry.
Definition at line 67 of file ttkdesktopwrapper.cpp.
Referenced by grabWindow().
QPixmap TTKDesktopWrapper::grabWidget (QWidget * widget, const QRect & rect) static
Grab widget geometry pixmap by given rect.
Definition at line 83 of file ttkdesktopwrapper.cpp.
Referenced by MusicFunctionToolBoxTopWidget::mouseMoveEvent(), and MusicLrcPosterWidget::saveButtonClicked().
QPixmap TTKDesktopWrapper::grabWindow (int x = 0, int y = 0, int w = -1, int h = -1) static
Grab all screen geometry pixmap by given rect.
Definition at line 92 of file ttkdesktopwrapper.cpp.
References geometry().
QRect TTKDesktopWrapper::screenGeometry (int index = 0) static
Get screen geometry by given screen index.
Definition at line 56 of file ttkdesktopwrapper.cpp.
Referenced by TTK::Widget::adjustWidgetPosition(), MusicApplicationModule::cleanup(), TTKToastLabel::popup(), MusicApplicationModule::resetWindowGeometry(), MusicVideoPlayWidget::resizeGeometry(), MusicScreenSaverBackgroundWidget::runningTimeout(), screenTaskbar(), MusicApplicationModule::sideAnimationByOff(), and MusicApplicationModule::sideAnimationByOn().
TTKDesktopWrapper::TaskbarInfo TTKDesktopWrapper::screenTaskbar (int index = 0) static
Get screen taskbar info by given screen index.
Definition at line 10 of file ttkdesktopwrapper.cpp.
References availableGeometry(), TTK::Bottom, TTK::Left, TTKDesktopWrapper::TaskbarInfo::m_direction, TTKDesktopWrapper::TaskbarInfo::m_size, TTK::No, TTK::Right, screenGeometry(), and TTK::Top.
Referenced by MusicApplicationModule::sideAnimationByOn().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkdesktopwrapper.h
TTKCommon/TTKLibrary/ttkdesktopwrapper.cpp