TTKMusicPlayer: TTKClickedLabel Class Reference
TTKClickedLabel Class Reference
The class of the label widget that can click.
#include <ttkclickedlabel.h>
Signals
void clicked ()
Public Member Functions
TTKClickedLabel (QWidget *parent=nullptr)
TTKClickedLabel (const QString &text, QWidget *parent=nullptr)
void blockOption (bool block)
Private Member Functions
virtual void mousePressEvent (QMouseEvent *event) overridefinal
Private Attributes
bool m_blockOption
Detailed Description
The class of the label widget that can click.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file ttkclickedlabel.h.
Constructor & Destructor Documentation
TTKClickedLabel::TTKClickedLabel (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 5 of file ttkclickedlabel.cpp.
TTKClickedLabel::TTKClickedLabel (const QString & text, QWidget * parent = nullptr) explicit
Definition at line 12 of file ttkclickedlabel.cpp.
Member Function Documentation
void TTKClickedLabel::blockOption (bool block) inline
Set or not block clicked.
Definition at line 42 of file ttkclickedlabel.h.
void TTKClickedLabel::clicked () signal
Click the item.
Referenced by mousePressEvent(), MusicArtistListQueryItemWidget::MusicArtistListQueryItemWidget(), MusicLrcFloatPhotoItem::MusicLrcFloatPhotoItem(), MusicMobileDevicesWidget::MusicMobileDevicesWidget(), and MusicWebDJRadioCategoryItemWidget::MusicWebDJRadioCategoryItemWidget().
void TTKClickedLabel::mousePressEvent (QMouseEvent * event) final override private virtual
Override the widget event.
Definition at line 19 of file ttkclickedlabel.cpp.
References clicked(), and m_blockOption.
Member Data Documentation
bool TTKClickedLabel::m_blockOption private
Definition at line 56 of file ttkclickedlabel.h.
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttkclickedlabel.h
TTKCommon/TTKLibrary/ttkclickedlabel.cpp