TTKMusicplayer: MusicToolSetsWidget Class Reference
MusicToolSetsWidget Class Reference
The class of the tool sets widget.
#include <musictoolsetswidget.h>
Public Slots
void itemHasClicked (QListWidgetItem *item)
void addListWidgetItem ()
void resetFlag (MusicObject::ToolsType flag)
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicToolSetsWidget (QWidget *parent=0)
virtual ~MusicToolSetsWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
void clearAllItems ()
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicToolSetsWidget * m_ui
MusicObject::ToolsTypes m_toolsFlags
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the tool sets widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 23 of file musictoolsetswidget.h.
Constructor & Destructor Documentation
MusicToolSetsWidget::MusicToolSetsWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 32 of file musictoolsetswidget.cpp.
References addListWidgetItem(), itemHasClicked(), m_ui, MusicUIObject::MScrollBarStyle03, and MusicUIObject::MToolButtonStyle04.
MusicToolSetsWidget::~MusicToolSetsWidget () virtual
Definition at line 60 of file musictoolsetswidget.cpp.
References clearAllItems(), and m_ui.
Member Function Documentation
void MusicToolSetsWidget::addListWidgetItem () slot
Add tool sets list into list widget.
Definition at line 71 of file musictoolsetswidget.cpp.
References m_ui, MusicUIObject::MColorStyle12_S, and MUSIC_DECLARE_LISTS.
Referenced by MusicToolSetsWidget().
void MusicToolSetsWidget::clearAllItems () protected
Clear All Items.
Definition at line 211 of file musictoolsetswidget.cpp.
References m_ui.
Referenced by ~MusicToolSetsWidget().
void MusicToolSetsWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 216 of file musictoolsetswidget.cpp.
QString MusicToolSetsWidget::getClassName () static
Get class object name.
Definition at line 66 of file musictoolsetswidget.cpp.
void MusicToolSetsWidget::itemHasClicked (QListWidgetItem * item) slot
Tool sets list item has clicked.
Definition at line 106 of file musictoolsetswidget.cpp.
References MusicTimerWidget::exec(), MusicMessageBox::exec(), MusicSongRingtoneMaker::exec(), MusicTransformWidget::exec(), MusicConnectTransferWidget::exec(), MusicApplication::getCurrentPlayList(), MusicRightAreaWidget::IndentifyWidget, MusicApplication::instance(), MusicRightAreaWidget::instance(), m_ui, MusicRightAreaWidget::musicFunctionClicked(), NEW_OPERATOR, MusicTimerWidget::setSongStringList(), MusicMessageBox::setText(), MusicObject::TT_AudioRecord, MusicObject::TT_ConnectionTest, MusicObject::TT_GrabWindow, MusicObject::TT_LocalManager, MusicObject::TT_SoundGain, MusicObject::TT_SoundKMicro, MusicObject::TT_SoundTouch, MusicObject::TT_Spectrum, MusicObject::TT_SpeedTest, and MusicObject::TT_Wallpaper.
Referenced by MusicToolSetsWidget().
void MusicToolSetsWidget::resetFlag (MusicObject::ToolsType flag) slot
Reset window open flag.
Definition at line 200 of file musictoolsetswidget.cpp.
References m_toolsFlags.
void MusicToolSetsWidget::show () slot
Override show function.
Definition at line 205 of file musictoolsetswidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Member Data Documentation
MusicObject::ToolsTypes MusicToolSetsWidget::m_toolsFlags protected
Definition at line 69 of file musictoolsetswidget.h.
Referenced by resetFlag().
Ui::MusicToolSetsWidget* MusicToolSetsWidget::m_ui protected
Definition at line 68 of file musictoolsetswidget.h.
Referenced by addListWidgetItem(), clearAllItems(), itemHasClicked(), MusicToolSetsWidget(), show(), and ~MusicToolSetsWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musictoolsetswidget.h
TTKModule/TTKWidget/musicToolsKits/musictoolsetswidget.cpp