TTKMusicplayer: GaussianBlurPrivate Class Reference
GaussianBlurPrivate Class Reference
Public Member Functions
void boxBlurH (int *srcPix, int *destPix, int w, int h, int radius)
void boxBlurV (int *srcPix, int *destPix, int w, int h, int radius)
void boxBlur (int *srcPix, int *destPix, int w, int h, int r)
void boxesForGauss (float sigma, int *size, int n)
Public Member Functions inherited from TTKPrivate< GaussianBlur >
virtual ~TTKPrivate ()
void setPublic (GaussianBlur *pub)
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< GaussianBlur >
GaussianBlur * ttk_q () const
Detailed Description
Definition at line 8 of file gaussianblur.cpp.
Member Function Documentation
void GaussianBlurPrivate::boxBlur (int * srcPix, int * destPix, int w, int h, int r)
Definition at line 178 of file gaussianblur.cpp.
References boxBlurH(), and boxBlurV().
void GaussianBlurPrivate::boxBlurH (int * srcPix, int * destPix, int w, int h, int radius)
Definition at line 18 of file gaussianblur.cpp.
References int().
Referenced by boxBlur().
void GaussianBlurPrivate::boxBlurV (int * srcPix, int * destPix, int w, int h, int radius)
Definition at line 99 of file gaussianblur.cpp.
References int().
Referenced by boxBlur().
void GaussianBlurPrivate::boxesForGauss (float sigma, int * size, int n)
Definition at line 189 of file gaussianblur.cpp.
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qimage/gaussianblur.cpp