TTKMusicplayer: MusicPagingWidgetObject Class Reference
MusicPagingWidgetObject Class Reference
The class of the paging widget object.
#include <musicpagingwidgetobject.h>
Signals
void mapped (int index)
Public Member Functions
MusicPagingWidgetObject (QObject *parent=nullptr)
virtual ~MusicPagingWidgetObject ()
QWidget * getCreatePagingWidget ()
QWidget * createPagingWidget (QWidget *parent, int total)
void reset (int total)
void paging (int index, int total)
int currentIndex () const
Protected Attributes
int m_currentPage
QWidget * m_pagingWidget
QList< MusicClickedLabel * > m_pagingItems
Detailed Description
The class of the paging widget object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicpagingwidgetobject.h.
Constructor & Destructor Documentation
MusicPagingWidgetObject::MusicPagingWidgetObject (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicpagingwidgetobject.cpp.
References m_currentPage, and m_pagingWidget.
MusicPagingWidgetObject::~MusicPagingWidgetObject () virtual
Definition at line 18 of file musicpagingwidgetobject.cpp.
References m_pagingItems, and m_pagingWidget.
Member Function Documentation
QWidget * MusicPagingWidgetObject::createPagingWidget (QWidget * parent, int total)
Create paging items.
Definition at line 29 of file musicpagingwidgetobject.cpp.
References MusicUtils::Widget::fontTextWidth(), m_pagingItems, m_pagingWidget, mapped(), MusicUIObject::MColorStyle04, MusicUIObject::MFontStyle01, MusicUIObject::MFontStyle05, and PAGE_SIZE.
Referenced by MusicArtistListFoundWidget::createArtistListItem(), MusicArtistMvsFoundWidget::createArtistMvsItem(), MusicCommentsWidget::createPagingWidget(), MusicPlaylistFoundWidget::createPlaylistItem(), and MusicWebDJRadioFoundWidget::createProgramItem().
int MusicPagingWidgetObject::currentIndex () const
Get current page index.
Definition at line 218 of file musicpagingwidgetobject.cpp.
References m_currentPage, and m_pagingItems.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsFoundWidget::buttonClicked(), MusicArtistListFoundWidget::buttonClicked(), MusicPlaylistFoundWidget::buttonClicked(), and MusicWebDJRadioFoundWidget::buttonClicked().
QWidget * MusicPagingWidgetObject::getCreatePagingWidget ()
Get create paging widget.
Definition at line 24 of file musicpagingwidgetobject.cpp.
References m_pagingWidget.
void MusicPagingWidgetObject::mapped (int index) signal
Mapped the clicked page index.
Referenced by createPagingWidget().
void MusicPagingWidgetObject::paging (int index, int total)
Start to page by given index and total.
Definition at line 124 of file musicpagingwidgetobject.cpp.
References MusicUtils::Widget::fontTextWidth(), m_currentPage, m_pagingItems, MusicUIObject::MColorStyle04, MusicUIObject::MFontStyle01, and PAGE_SIZE.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsFoundWidget::buttonClicked(), MusicArtistListFoundWidget::buttonClicked(), MusicPlaylistFoundWidget::buttonClicked(), and MusicWebDJRadioFoundWidget::buttonClicked().
void MusicPagingWidgetObject::reset (int total)
Reset page to origin.
Definition at line 98 of file musicpagingwidgetobject.cpp.
References m_currentPage, m_pagingItems, and PAGE_SIZE.
Referenced by MusicArtistListFoundWidget::createArtistListItem(), MusicPlaylistFoundWidget::createPlaylistItem(), and MusicWebDJRadioFoundWidget::createProgramItem().
Member Data Documentation
int MusicPagingWidgetObject::m_currentPage protected
Definition at line 69 of file musicpagingwidgetobject.h.
Referenced by currentIndex(), MusicPagingWidgetObject(), paging(), and reset().
QList<MusicClickedLabel*> MusicPagingWidgetObject::m_pagingItems protected
Definition at line 71 of file musicpagingwidgetobject.h.
Referenced by createPagingWidget(), currentIndex(), paging(), reset(), and ~MusicPagingWidgetObject().
QWidget* MusicPagingWidgetObject::m_pagingWidget protected
Definition at line 70 of file musicpagingwidgetobject.h.
Referenced by createPagingWidget(), getCreatePagingWidget(), MusicPagingWidgetObject(), and ~MusicPagingWidgetObject().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicpagingwidgetobject.h
TTKModule/TTKWidget/musicWidgetKits/musicpagingwidgetobject.cpp