TTKMusicplayer: MusicUserManagerDialog Class Reference
MusicUserManagerDialog Class Reference
The class of the user manager.
#include <musicusermanagerdialog.h>
Public Slots
void musicUserLogoff ()
void popupUserRecordWidget ()
void resetUserName (const QString &name)
virtual int exec ()
Signals
void userStateChanged (const QString &uid, const QString &icon)
Public Member Functions
MusicUserManagerDialog (QWidget *parent=0)
~MusicUserManagerDialog ()
void setUserUID (const QString &uid)
void setUserModel (MusicUserModel *model)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void leaveEvent (QEvent *event) override
void createUserTime () const
void createButtonPopMenu ()
Protected Attributes
Ui::MusicUserManagerDialog * m_ui
MusicUserModel * m_userModel
QString m_currentUserUID
QTime m_time
QMenu m_popMenu
Detailed Description
The class of the user manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 25 of file musicusermanagerdialog.h.
Constructor & Destructor Documentation
MusicUserManagerDialog::MusicUserManagerDialog (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 11 of file musicusermanagerdialog.cpp.
References createButtonPopMenu(), m_ui, musicUserLogoff(), and popupUserRecordWidget().
MusicUserManagerDialog::~MusicUserManagerDialog ()
Definition at line 36 of file musicusermanagerdialog.cpp.
References MusicUserModel::getUserLogTime(), m_currentUserUID, m_time, m_ui, m_userModel, MT_S2MS, and MusicUserModel::updateUser().
Member Function Documentation
void MusicUserManagerDialog::createButtonPopMenu () protected
Create functions menu popup initialized.
Definition at line 72 of file musicusermanagerdialog.cpp.
References m_popMenu, m_ui, MusicUIObject::MMenuStyle02, musicUserLogoff(), and popupUserRecordWidget().
Referenced by MusicUserManagerDialog().
void MusicUserManagerDialog::createUserTime () const protected
Create current user all login time to show.
Definition at line 66 of file musicusermanagerdialog.cpp.
References MusicUserModel::getUserLogTime(), m_currentUserUID, m_ui, and m_userModel.
Referenced by setUserUID().
int MusicUserManagerDialog::exec () virtual slot
Override exec function.
Definition at line 114 of file musicusermanagerdialog.cpp.
References MStatic_cast.
QString MusicUserManagerDialog::getClassName () static
Get class object name.
Definition at line 47 of file musicusermanagerdialog.cpp.
void MusicUserManagerDialog::leaveEvent (QEvent * event) override protected virtual
Override the widget event.
Definition at line 122 of file musicusermanagerdialog.cpp.
void MusicUserManagerDialog::musicUserLogoff () slot
User logout clicked.
Definition at line 81 of file musicusermanagerdialog.cpp.
References MusicUserModel::getUserLogTime(), m_currentUserUID, m_time, m_ui, m_userModel, MT_S2MS, MusicUserConfigManager::readUserConfig(), MusicUserConfigManager::readUserXMLConfig(), MusicUserModel::updateUser(), userStateChanged(), and MusicUserConfigManager::writeUserXMLConfig().
Referenced by createButtonPopMenu(), MusicUserWindow::musicUserContextLogin(), and MusicUserManagerDialog().
void MusicUserManagerDialog::popupUserRecordWidget () slot
Popup user record widget clicked.
Definition at line 128 of file musicusermanagerdialog.cpp.
References MusicUserRecordWidget::exec(), m_currentUserUID, m_userModel, resetUserName(), MusicUserRecordWidget::setUserModel(), and userStateChanged().
Referenced by createButtonPopMenu(), and MusicUserManagerDialog().
void MusicUserManagerDialog::resetUserName (const QString & name) slot
Reset current user name.
Definition at line 141 of file musicusermanagerdialog.cpp.
References m_ui.
Referenced by popupUserRecordWidget().
void MusicUserManagerDialog::setUserModel (MusicUserModel * model)
Set user model.
Definition at line 61 of file musicusermanagerdialog.cpp.
References m_userModel.
Referenced by MusicUserWindow::MusicUserWindow().
void MusicUserManagerDialog::setUserUID (const QString & uid)
Set current user's uid.
Definition at line 52 of file musicusermanagerdialog.cpp.
References createUserTime(), MusicUserModel::getUserIcon(), MusicUserModel::getUserName(), m_currentUserUID, m_time, m_ui, and m_userModel.
Referenced by MusicUserWindow::userStateChanged().
void MusicUserManagerDialog::userStateChanged (const QString & uid, const QString & icon) signal
User login state changed.
Referenced by musicUserLogoff(), and popupUserRecordWidget().
Member Data Documentation
QString MusicUserManagerDialog::m_currentUserUID protected
Definition at line 89 of file musicusermanagerdialog.h.
Referenced by createUserTime(), musicUserLogoff(), popupUserRecordWidget(), setUserUID(), and ~MusicUserManagerDialog().
QMenu MusicUserManagerDialog::m_popMenu protected
Definition at line 91 of file musicusermanagerdialog.h.
Referenced by createButtonPopMenu().
QTime MusicUserManagerDialog::m_time protected
Definition at line 90 of file musicusermanagerdialog.h.
Referenced by musicUserLogoff(), setUserUID(), and ~MusicUserManagerDialog().
Ui::MusicUserManagerDialog* MusicUserManagerDialog::m_ui protected
Definition at line 87 of file musicusermanagerdialog.h.
Referenced by createButtonPopMenu(), createUserTime(), musicUserLogoff(), MusicUserManagerDialog(), resetUserName(), setUserUID(), and ~MusicUserManagerDialog().
MusicUserModel* MusicUserManagerDialog::m_userModel protected
Definition at line 88 of file musicusermanagerdialog.h.
Referenced by createUserTime(), musicUserLogoff(), popupUserRecordWidget(), setUserModel(), setUserUID(), and ~MusicUserManagerDialog().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicUserKits/musicusermanagerdialog.h
TTKModule/TTKWidget/musicUserKits/musicusermanagerdialog.cpp