TTKMusicplayer: MusicDownloadSourceRequest Class Reference
MusicDownloadSourceRequest Class Reference
The class of source data download request.
#include <musicdownloadsourcerequest.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownloadSourceRequest (QObject *parent=nullptr)
void startToDownload (const QString &url)
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of source data download request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdownloadsourcerequest.h.
Constructor & Destructor Documentation
MusicDownloadSourceRequest::MusicDownloadSourceRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdownloadsourcerequest.cpp.
Member Function Documentation
void MusicDownloadSourceRequest::downLoadFinished () override virtual slot
Download data from net finished.
redirection target url
Definition at line 19 of file musicdownloadsourcerequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadFinished(), MusicAbstractNetwork::downLoadRawDataChanged(), MusicAbstractNetwork::m_reply, startToDownload(), and TTK_LOGGER_ERROR.
Referenced by startToDownload().
void MusicDownloadSourceRequest::startToDownload (const QString & url)
Start to download data.
Definition at line 9 of file musicdownloadsourcerequest.cpp.
References downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, and MusicObject::setSslConfiguration().
Referenced by MusicWebFMRadioWidget::addListWidgetItem(), MusicAlbumQueryWidget::createAlbumInfoItem(), MusicArtistQueryWidget::createArtistInfoItem(), MusicWebDJRadioInfoWidget::createCategoryInfoItem(), MusicWebMVRadioInfoWidget::createCategoryInfoItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicCommentsItem::createSearchedItem(), MusicToplistQueryWidget::createToplistInfoItem(), downLoadFinished(), MusicDownloadTagDataRequest::downLoadFinished(), MusicSoundKMicroWidget::mediaUrlChanged(), MusicCloudManagerTableWidget::queryCloudKey(), MusicIdentifySongsRequest::queryIdentifyKey(), MusicSongSharingWidget::setData(), MusicArtistAlbumsItemWidget::setMusicResultsItem(), MusicWebMVRadioQueryItemWidget::setMusicResultsItem(), MusicWebDJRadioCategoryItemWidget::setMusicResultsItem(), MusicWebDJRadioQueryItemWidget::setMusicResultsItem(), MusicPlaylistQueryItemWidget::setMusicResultsItem(), MusicPlaylistQueryInfoWidget::setMusicResultsItem(), MusicKWDownloadBackgroundRequest::startToDownload(), MusicNetworkOperator::startToDownload(), MusicSourceUpdateRequest::startToDownload(), MusicDownloadBackgroundThunderRequest::startToDownload(), and MusicDownloadBackgroundBingRequest::startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadsourcerequest.h
TTKModule/TTKCore/musicNetworkKits/common/musicdownloadsourcerequest.cpp