TTKMusicplayer: MusicApplicationMPRISRoot Class Reference
MusicApplicationMPRISRoot Class Reference
The class of the app mpris root object.
#include <musicapplicationmprismodule.h>
Public Slots
void Quit ()
void Raise ()
Public Member Functions
MusicApplicationMPRISRoot (QObject *parent=nullptr)
bool canQuit () const
bool canRaise () const
QString desktopEntry () const
bool hasTrackList () const
QString identity () const
QStringList supportedMimeTypes () const
QStringList supportedUriSchemes () const
Properties
bool CanQuit
bool CanRaise
QString DesktopEntry
bool HasTrackList
QString Identity
QStringList SupportedMimeTypes
QStringList SupportedUriSchemes
Detailed Description
The class of the app mpris root object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicapplicationmprismodule.h.
Constructor & Destructor Documentation
MusicApplicationMPRISRoot::MusicApplicationMPRISRoot (QObject * parent = nullptr)
Definition at line 367 of file musicapplicationmprismodule.cpp.
Member Function Documentation
bool MusicApplicationMPRISRoot::canQuit () const
Definition at line 373 of file musicapplicationmprismodule.cpp.
bool MusicApplicationMPRISRoot::canRaise () const
Definition at line 378 of file musicapplicationmprismodule.cpp.
QString MusicApplicationMPRISRoot::desktopEntry () const
Definition at line 383 of file musicapplicationmprismodule.cpp.
References APP_NAME.
bool MusicApplicationMPRISRoot::hasTrackList () const
Definition at line 388 of file musicapplicationmprismodule.cpp.
QString MusicApplicationMPRISRoot::identity () const
Definition at line 393 of file musicapplicationmprismodule.cpp.
References APP_NAME.
void MusicApplicationMPRISRoot::Quit () slot
Definition at line 417 of file musicapplicationmprismodule.cpp.
References MusicApplication::instance(), and MusicApplication::quitWindowClose().
void MusicApplicationMPRISRoot::Raise () slot
Definition at line 422 of file musicapplicationmprismodule.cpp.
References MusicApplication::instance().
QStringList MusicApplicationMPRISRoot::supportedMimeTypes () const
Definition at line 398 of file musicapplicationmprismodule.cpp.
References AbstractEngine::contentTypes(), and Decoder::contentTypes().
QStringList MusicApplicationMPRISRoot::supportedUriSchemes () const
Definition at line 407 of file musicapplicationmprismodule.cpp.
References MetaDataManager::instance(), and MetaDataManager::protocols().
Property Documentation
bool MusicApplicationMPRISRoot::CanQuit read
Definition at line 39 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISRoot::CanRaise read
Definition at line 40 of file musicapplicationmprismodule.h.
QString MusicApplicationMPRISRoot::DesktopEntry read
Definition at line 41 of file musicapplicationmprismodule.h.
bool MusicApplicationMPRISRoot::HasTrackList read
Definition at line 42 of file musicapplicationmprismodule.h.
QString MusicApplicationMPRISRoot::Identity read
Definition at line 43 of file musicapplicationmprismodule.h.
QStringList MusicApplicationMPRISRoot::SupportedMimeTypes read
Definition at line 44 of file musicapplicationmprismodule.h.
QStringList MusicApplicationMPRISRoot::SupportedUriSchemes read
Definition at line 45 of file musicapplicationmprismodule.h.
The documentation for this class was generated from the following files:
TTKModule/musicapplicationmprismodule.h
TTKModule/musicapplicationmprismodule.cpp