TTKMusicplayer: MusicTranslationThread Class Reference
MusicTranslationThread Class Reference
The class of translation words thread.
#include <musictranslationthread.h>
Public Types
enum TranslationType {
Type_Auto, Type_Ara, Type_De, Type_Ru,
Type_Fra, Type_Kor, Type_Nl, Type_Pt,
Type_Jp, Type_Th, Type_Wyw, Type_Spa,
Type_El, Type_It, Type_En, Type_Yue,
Type_Zh
}
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicTranslationThread (QObject *parent=0)
virtual ~MusicTranslationThread ()
virtual void startToDownload (const QString &data) override
void startToDownload (TranslationType from, TranslationType to, const QString &data)
Public Member Functions inherited from MusicTranslationThreadAbstract
MusicTranslationThreadAbstract (QObject *parent=0)
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicTranslationThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Member Functions
QString mapTypeFromEnumToString (TranslationType type)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Additional Inherited Members
Signals inherited from MusicTranslationThreadAbstract
void downLoadDataChanged (const QString &data)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicTranslationThreadAbstract
QVariantMap m_rawData
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of translation words thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musictranslationthread.h.
Member Enumeration Documentation
enum MusicTranslationThread::TranslationType
Enumerator
Type_Auto
automatic detection
Type_Ara
Arabic
Type_De
German
Type_Ru
Russian
Type_Fra
French
Type_Kor
Korean
Type_Nl
Dutch
Type_Pt
Portuguese
Type_Jp
Japanese
Type_Th
Thai
Type_Wyw
Classical
Type_Spa
Spanish
Type_El
Greek
Type_It
Italian
Type_En
English
Type_Yue
Cantonese
Type_Zh
Chinese
Definition at line 31 of file musictranslationthread.h.
Constructor & Destructor Documentation
MusicTranslationThread::MusicTranslationThread (QObject * parent = 0) explicit
Object contsructor.
Definition at line 8 of file musictranslationthread.cpp.
MusicTranslationThread::~MusicTranslationThread () virtual
Definition at line 14 of file musictranslationthread.cpp.
References MusicTranslationThreadAbstract::deleteAll().
Member Function Documentation
void MusicTranslationThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 66 of file musictranslationthread.cpp.
References MusicTranslationThreadAbstract::deleteAll(), MusicTranslationThreadAbstract::downLoadDataChanged(), M_LOGGER_ERROR, MusicNetworkAbstract::m_reply, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicTranslationThread::getClassName () static
Get class object name.
Definition at line 19 of file musictranslationthread.cpp.
QString MusicTranslationThread::mapTypeFromEnumToString (TranslationType type) protected
Map type from enum to string.
Definition at line 41 of file musictranslationthread.cpp.
References Type_Ara, Type_Auto, Type_De, Type_El, Type_En, Type_Fra, Type_It, Type_Jp, Type_Kor, Type_Nl, Type_Pt, Type_Ru, Type_Spa, Type_Th, Type_Wyw, Type_Yue, and Type_Zh.
Referenced by startToDownload().
void MusicTranslationThread::startToDownload (const QString & data) override virtual
Start to translation data.
Implements MusicTranslationThreadAbstract.
Definition at line 24 of file musictranslationthread.cpp.
References Type_Auto, and Type_Zh.
void MusicTranslationThread::startToDownload (TranslationType from, TranslationType to, const QString & data)
Start to translation data.
Definition at line 29 of file musictranslationthread.cpp.
References downLoadFinished(), MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, mapTypeFromEnumToString(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), and TRANSLATION_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musictranslationthread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musictranslationthread.cpp