TTKMusicplayer: MusicCloudUploadTableWidget Class Reference
MusicCloudUploadTableWidget Class Reference
The class of the cloud shared song upload table widget.
#include <musiccloudtablewidget.h>
Public Slots
void uploadFileError (const MusicCloudDataItem &item)
void reuploadFile ()
void reuploadFiles ()
Public Slots inherited from MusicAbstractDownloadTableWidget
void musicPlay ()
virtual void setDeleteItemAt () override
virtual void itemCellClicked (int row, int column) override
void itemCellDoubleClicked (int row, int column)
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Public Slots inherited from MusicAbstractSongsListTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumQueryWidget ()
void musicSimilarQueryWidget ()
void musicSongSharedWidget ()
void musicSongDownload ()
void musicSongPlayedMovieFound ()
void musicPlayedSimilarQueryWidget ()
void musicSongPlayedSharedWidget ()
void musicSongPlayedKMicroWidget ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Signals
void reuploadFilesToServer (const QStringList &items)
Signals inherited from MusicAbstractDownloadTableWidget
void addSongToPlaylist (const QStringList &list)
void updateItemTitle (int index)
Signals inherited from MusicAbstractSongsListTableWidget
void isCurrentIndex (bool &state)
Public Member Functions
MusicCloudUploadTableWidget (QWidget *parent=nullptr)
~MusicCloudUploadTableWidget ()
Public Member Functions inherited from MusicAbstractDownloadTableWidget
MusicAbstractDownloadTableWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractDownloadTableWidget ()
virtual void updateSongsFileName (const MusicSongs &songs) override
Public Member Functions inherited from MusicAbstractSongsListTableWidget
MusicAbstractSongsListTableWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractSongsListTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void selectRow (int index)
int totalHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=nullptr)
~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar=nullptr)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
virtual ~MusicAbstractTableWidget ()
void clear ()
TTKIntList getMultiSelectedIndex () const
Protected Member Functions
virtual void createItem (int index, const MusicSong &record) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicAbstractSongsListTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Additional Inherited Members
Protected Attributes inherited from MusicAbstractDownloadTableWidget
MusicProgressBarDelegate * m_delegate
MusicObject::RecordType m_type
Protected Attributes inherited from MusicAbstractSongsListTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_initialized
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the cloud shared song upload table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 51 of file musiccloudtablewidget.h.
Constructor & Destructor Documentation
MusicCloudUploadTableWidget::MusicCloudUploadTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 72 of file musiccloudtablewidget.cpp.
References G_CONNECTION_PTR, MusicAbstractDownloadTableWidget::m_type, MusicUIObject::MQSSScrollBarStyle03, MusicObject::RecordCloudUpload, and MusicUtils::Widget::setTransparent().
MusicCloudUploadTableWidget::~MusicCloudUploadTableWidget ()
Definition at line 92 of file musiccloudtablewidget.cpp.
References G_CONNECTION_PTR.
Member Function Documentation
void MusicCloudUploadTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicAbstractDownloadTableWidget.
Definition at line 193 of file musiccloudtablewidget.cpp.
References MusicAbstractSongsListTableWidget::m_musicSongs, MusicUIObject::MQSSMenuStyle02, MusicAbstractSongsListTableWidget::musicFileInformation(), MusicAbstractSongsListTableWidget::musicOpenFileDir(), reuploadFile(), reuploadFiles(), MusicAbstractSongsListTableWidget::setDeleteItemAll(), and MusicAbstractDownloadTableWidget::setDeleteItemAt().
void MusicCloudUploadTableWidget::createItem (int index, const MusicSong & record) override protected virtual
Create item by index and name and size and time.
Implements MusicAbstractDownloadTableWidget.
Definition at line 161 of file musiccloudtablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSong::getMusicAddTimeStr(), MusicSong::getMusicName(), MusicSong::getMusicPath(), MusicSong::getMusicSizeStr(), MusicUIObject::MQSSColor01, MUSIC_DATA_ROLE, MUSIC_TIME_ROLE, and MusicAbstractSongsListTableWidget::totalHeight().
Referenced by uploadFileError().
void MusicCloudUploadTableWidget::reuploadFile () slot
Reupload failed file.
Definition at line 110 of file musiccloudtablewidget.cpp.
References MUSIC_DATA_ROLE, MusicToastLabel::popup(), and reuploadFilesToServer().
Referenced by contextMenuEvent().
void MusicCloudUploadTableWidget::reuploadFiles () slot
Reupload failed files.
Definition at line 131 of file musiccloudtablewidget.cpp.
References MusicAbstractTableWidget::getMultiSelectedIndex(), MUSIC_DATA_ROLE, MusicToastLabel::popup(), and reuploadFilesToServer().
Referenced by contextMenuEvent().
void MusicCloudUploadTableWidget::reuploadFilesToServer (const QStringList & items) signal
Reupload files to server.
Referenced by reuploadFile(), and reuploadFiles().
void MusicCloudUploadTableWidget::uploadFileError (const MusicCloudDataItem & item) slot
Upload file error occurred.
Definition at line 97 of file musiccloudtablewidget.cpp.
References createItem(), MusicCloudDataItem::m_dataItem, QSyncDataItem::m_name, MusicCloudDataItem::m_path, QSyncDataItem::m_size, MusicSong::setMusicName(), MusicSong::setMusicPath(), MusicSong::setMusicSizeStr(), and MusicUtils::Number::sizeByte2Label().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudtablewidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudtablewidget.cpp