TTKMusicplayer: MusicCloudSharedSongTableWidget Class Reference
MusicCloudSharedSongTableWidget Class Reference
The class of the cloud shared song table widget.
#include <musiccloudsharedsongwidget.h>
Public Slots
virtual void listCellClicked (int row, int column) override
void keyDownLoadFinished (const QByteArray &data)
void receiveDataFinshed (const QNDataItems &items)
void uploadFileFinished (const QString &name)
void deleteFileFinished (bool state)
void updateListToServer ()
void deleteFileToServer ()
void deleteFilesToServer ()
void downloadFileToServer ()
void uploadFileToServer ()
void uploadFilesToServer ()
void reuploadFileToServer ()
void openFileManagerDialog ()
void uploadProgress (qint64 bytesSent, qint64 bytesTotal)
void uploadDone ()
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void updateLabelMessage (const QString &text)
void getKeyFinished ()
Public Member Functions
MusicCloudSharedSongTableWidget (QWidget *parent=0)
virtual ~MusicCloudSharedSongTableWidget ()
bool getKey ()
const MusicUploadDatas & getUploadDatas () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
void createUploadFileWidget ()
void startToUploadFile ()
bool uploadHasFailed ()
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
bool m_uploading
int m_currentUploadIndex
MusicUploadDatas m_waitedFiles
QNSimpleListData * m_qnListData
QNSimpleDeleteData * m_qnDeleteData
QNSimpleUploadData * m_qnUploadData
QNetworkAccessManager * m_networkManager
MusicOpenFileWidget * m_openFileWidget
MusicCloudFileManagerDialog * m_fileDialog
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the cloud shared song table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musiccloudsharedsongwidget.h.
Constructor & Destructor Documentation
MusicCloudSharedSongTableWidget::MusicCloudSharedSongTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 30 of file musiccloudsharedsongwidget.cpp.
References deleteFileFinished(), m_currentUploadIndex, m_fileDialog, m_networkManager, m_openFileWidget, m_qnDeleteData, m_qnListData, m_qnUploadData, m_uploading, MusicUIObject::MScrollBarStyle03, receiveDataFinshed(), MusicUtils::Widget::setTransparent(), and uploadFileFinished().
MusicCloudSharedSongTableWidget::~MusicCloudSharedSongTableWidget () virtual
Definition at line 56 of file musiccloudsharedsongwidget.cpp.
References m_fileDialog, m_networkManager, m_openFileWidget, m_qnDeleteData, m_qnListData, and m_qnUploadData.
Member Function Documentation
void MusicCloudSharedSongTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 341 of file musiccloudsharedsongwidget.cpp.
References deleteFilesToServer(), deleteFileToServer(), downloadFileToServer(), m_uploading, MusicUIObject::MMenuStyle02, updateListToServer(), uploadFilesToServer(), and uploadFileToServer().
void MusicCloudSharedSongTableWidget::createUploadFileWidget () protected
Create upload file widget.
Definition at line 362 of file musiccloudsharedsongwidget.cpp.
References MusicOpenFileWidget::adjustRect(), m_openFileWidget, uploadFilesToServer(), and uploadFileToServer().
Referenced by receiveDataFinshed().
void MusicCloudSharedSongTableWidget::deleteFileFinished (bool state) slot
Delete data to qiniu finshed.
Definition at line 173 of file musiccloudsharedsongwidget.cpp.
References MusicMessageBox::exec(), MusicMessageBox::setText(), and updateListToServer().
Referenced by MusicCloudSharedSongTableWidget().
void MusicCloudSharedSongTableWidget::deleteFilesToServer () slot
Delete files to server.
Definition at line 223 of file musiccloudsharedsongwidget.cpp.
References MusicCloudFileManagerDialog::creatFilesManager(), QNSimpleDeleteData::deleteDataToServer(), m_currentUploadIndex, m_fileDialog, MusicUploadData::m_name, m_qnDeleteData, m_waitedFiles, and QN_BUCKET.
Referenced by contextMenuEvent().
void MusicCloudSharedSongTableWidget::deleteFileToServer () slot
Delete file to server.
Definition at line 193 of file musiccloudsharedsongwidget.cpp.
References MusicCloudFileManagerDialog::creatFilesManager(), QNSimpleDeleteData::deleteDataToServer(), m_currentUploadIndex, m_fileDialog, MusicUploadData::m_name, MusicUploadData::m_path, m_qnDeleteData, MusicUploadData::m_state, m_waitedFiles, QN_BUCKET, and MusicUploadData::Successed.
Referenced by contextMenuEvent().
void MusicCloudSharedSongTableWidget::downloadFileToServer () slot
Download file to server.
Definition at line 238 of file musiccloudsharedsongwidget.cpp.
References MusicDownLoadThreadAbstract::Download_Music, QNSimpleUploadData::getDownloadUrl(), m_qnUploadData, MusicUtils::Algorithm::mdII(), MusicUtils::Core::musicPrefix(), and QN_PRFIX.
Referenced by contextMenuEvent().
QString MusicCloudSharedSongTableWidget::getClassName () static
Get class object name.
Definition at line 66 of file musiccloudsharedsongwidget.cpp.
bool MusicCloudSharedSongTableWidget::getKey ()
Get query cloud id keys.
Definition at line 71 of file musiccloudsharedsongwidget.cpp.
References QNConf::ACCESS_KEY, MusicSemaphoreLoop::exec(), getKeyFinished(), keyDownLoadFinished(), MusicUtils::Algorithm::mdII(), QN_UA_URL, QNConf::SECRET_KEY, MusicDownloadSourceThread::startToDownload(), and updateListToServer().
Referenced by MusicCloudSharedSongWidget::getKey().
void MusicCloudSharedSongTableWidget::getKeyFinished () signal
Get key data from net finished.
Referenced by getKey(), and keyDownLoadFinished().
const MusicUploadDatas& MusicCloudSharedSongTableWidget::getUploadDatas () const inline
Get upload datas.
Definition at line 56 of file musiccloudsharedsongwidget.h.
void MusicCloudSharedSongTableWidget::keyDownLoadFinished (const QByteArray & data) slot
Download key data from net finished.
Definition at line 92 of file musiccloudsharedsongwidget.cpp.
References QNConf::ACCESS_KEY, getKeyFinished(), QJson::Parser::parse(), and QNConf::SECRET_KEY.
Referenced by getKey().
void MusicCloudSharedSongTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 86 of file musiccloudsharedsongwidget.cpp.
void MusicCloudSharedSongTableWidget::openFileManagerDialog () slot
Open file manager dialog.
Definition at line 316 of file musiccloudsharedsongwidget.cpp.
References MusicCloudFileManagerDialog::creatFilesManager(), m_fileDialog, m_waitedFiles, and MusicCloudFileManagerDialog::show().
void MusicCloudSharedSongTableWidget::receiveDataFinshed (const QNDataItems & items) slot
Receive data from qiniu finshed.
insert server datas into caches
Definition at line 106 of file musiccloudsharedsongwidget.cpp.
References MusicAbstractTableWidget::clear(), createUploadFileWidget(), MusicUtils::Widget::elidedText(), m_currentUploadIndex, QNDataItem::m_name, MusicUploadData::m_name, m_openFileWidget, MusicUploadData::m_path, QNDataItem::m_size, MusicUploadData::m_state, m_waitedFiles, MusicUIObject::MColorStyle12_S, MusicUtils::Number::size2Label(), MusicUploadData::Successed, and updateLabelMessage().
Referenced by MusicCloudSharedSongTableWidget().
void MusicCloudSharedSongTableWidget::reuploadFileToServer () slot
Reupload files to server.
Definition at line 310 of file musiccloudsharedsongwidget.cpp.
References m_currentUploadIndex, and startToUploadFile().
void MusicCloudSharedSongTableWidget::startToUploadFile () protected
Start to upload files to server.
Definition at line 375 of file musiccloudsharedsongwidget.cpp.
References m_currentUploadIndex, MusicUploadData::m_name, MusicUploadData::m_path, m_qnUploadData, MusicUploadData::m_state, m_uploading, m_waitedFiles, QN_BUCKET, MusicUploadData::Successed, updateLabelMessage(), QNSimpleUploadData::uploadDataToServer(), and uploadDone().
Referenced by reuploadFileToServer(), uploadFileFinished(), uploadFilesToServer(), and uploadFileToServer().
void MusicCloudSharedSongTableWidget::updateLabelMessage (const QString & text) signal
To update message label text.
Referenced by receiveDataFinshed(), startToUploadFile(), and updateListToServer().
void MusicCloudSharedSongTableWidget::updateListToServer () slot
Update list to server.
Definition at line 187 of file musiccloudsharedsongwidget.cpp.
References QNSimpleListData::listDataToServer(), m_qnListData, QN_BUCKET, and updateLabelMessage().
Referenced by contextMenuEvent(), deleteFileFinished(), getKey(), and uploadDone().
void MusicCloudSharedSongTableWidget::uploadDone () slot
All files upload finsihed.
Definition at line 331 of file musiccloudsharedsongwidget.cpp.
References MusicLeftAreaWidget::instance(), m_currentUploadIndex, m_fileDialog, m_uploading, m_waitedFiles, MT_MS, MusicCloudFileManagerDialog::setReuploadState(), updateListToServer(), and uploadHasFailed().
Referenced by startToUploadFile().
void MusicCloudSharedSongTableWidget::uploadFileFinished (const QString & name) slot
Upload data to qiniu finshed.
Definition at line 157 of file musiccloudsharedsongwidget.cpp.
References MusicUploadData::Errored, m_currentUploadIndex, m_fileDialog, MusicUploadData::m_name, MusicUploadData::m_path, MusicUploadData::m_state, m_waitedFiles, startToUploadFile(), MusicUploadData::Successed, and MusicCloudFileManagerDialog::updateItemProgress().
Referenced by MusicCloudSharedSongTableWidget().
void MusicCloudSharedSongTableWidget::uploadFilesToServer () slot
Upload files to server.
Definition at line 283 of file musiccloudsharedsongwidget.cpp.
References MusicCloudFileManagerDialog::creatFileManager(), MusicUtils::Core::findFile(), m_fileDialog, MusicUploadData::m_name, MusicUploadData::m_path, MusicUploadData::m_state, m_uploading, m_waitedFiles, startToUploadFile(), MusicFormats::supportFormatsFilterString(), and MusicUploadData::Waited.
Referenced by contextMenuEvent(), and createUploadFileWidget().
void MusicCloudSharedSongTableWidget::uploadFileToServer () slot
Upload file to server.
Definition at line 256 of file musiccloudsharedsongwidget.cpp.
References MusicCloudFileManagerDialog::creatFileManager(), MusicUtils::Widget::getOpenFilesDialog(), m_fileDialog, MusicUploadData::m_name, MusicUploadData::m_path, MusicUploadData::m_state, m_uploading, m_waitedFiles, startToUploadFile(), and MusicUploadData::Waited.
Referenced by contextMenuEvent(), and createUploadFileWidget().
bool MusicCloudSharedSongTableWidget::uploadHasFailed () protected
Check upload has failed.
Definition at line 398 of file musiccloudsharedsongwidget.cpp.
References MusicUploadData::m_state, m_waitedFiles, and MusicUploadData::Successed.
Referenced by uploadDone().
void MusicCloudSharedSongTableWidget::uploadProgress (qint64 bytesSent, qint64 bytesTotal) slot
Show upload progress.
Definition at line 322 of file musiccloudsharedsongwidget.cpp.
References m_currentUploadIndex, m_fileDialog, m_waitedFiles, MStatic_cast, and MusicCloudFileManagerDialog::updateItemProgress().
Member Data Documentation
int MusicCloudSharedSongTableWidget::m_currentUploadIndex protected
Definition at line 152 of file musiccloudsharedsongwidget.h.
Referenced by deleteFilesToServer(), deleteFileToServer(), MusicCloudSharedSongTableWidget(), receiveDataFinshed(), reuploadFileToServer(), startToUploadFile(), uploadDone(), uploadFileFinished(), and uploadProgress().
MusicCloudFileManagerDialog* MusicCloudSharedSongTableWidget::m_fileDialog protected
Definition at line 159 of file musiccloudsharedsongwidget.h.
Referenced by deleteFilesToServer(), deleteFileToServer(), MusicCloudSharedSongTableWidget(), openFileManagerDialog(), uploadDone(), uploadFileFinished(), uploadFilesToServer(), uploadFileToServer(), uploadProgress(), and ~MusicCloudSharedSongTableWidget().
QNetworkAccessManager* MusicCloudSharedSongTableWidget::m_networkManager protected
Definition at line 157 of file musiccloudsharedsongwidget.h.
Referenced by MusicCloudSharedSongTableWidget(), and ~MusicCloudSharedSongTableWidget().
MusicOpenFileWidget* MusicCloudSharedSongTableWidget::m_openFileWidget protected
Definition at line 158 of file musiccloudsharedsongwidget.h.
Referenced by createUploadFileWidget(), MusicCloudSharedSongTableWidget(), receiveDataFinshed(), and ~MusicCloudSharedSongTableWidget().
QNSimpleDeleteData* MusicCloudSharedSongTableWidget::m_qnDeleteData protected
Definition at line 155 of file musiccloudsharedsongwidget.h.
Referenced by deleteFilesToServer(), deleteFileToServer(), MusicCloudSharedSongTableWidget(), and ~MusicCloudSharedSongTableWidget().
QNSimpleListData* MusicCloudSharedSongTableWidget::m_qnListData protected
Definition at line 154 of file musiccloudsharedsongwidget.h.
Referenced by MusicCloudSharedSongTableWidget(), updateListToServer(), and ~MusicCloudSharedSongTableWidget().
QNSimpleUploadData* MusicCloudSharedSongTableWidget::m_qnUploadData protected
Definition at line 156 of file musiccloudsharedsongwidget.h.
Referenced by downloadFileToServer(), MusicCloudSharedSongTableWidget(), startToUploadFile(), and ~MusicCloudSharedSongTableWidget().
bool MusicCloudSharedSongTableWidget::m_uploading protected
Definition at line 151 of file musiccloudsharedsongwidget.h.
Referenced by contextMenuEvent(), MusicCloudSharedSongTableWidget(), startToUploadFile(), uploadDone(), uploadFilesToServer(), and uploadFileToServer().
MusicUploadDatas MusicCloudSharedSongTableWidget::m_waitedFiles protected
Definition at line 153 of file musiccloudsharedsongwidget.h.
Referenced by deleteFilesToServer(), deleteFileToServer(), openFileManagerDialog(), receiveDataFinshed(), startToUploadFile(), uploadDone(), uploadFileFinished(), uploadFilesToServer(), uploadFileToServer(), uploadHasFailed(), and uploadProgress().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudsharedsongwidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudsharedsongwidget.cpp