TTKMusicplayer: MusicFMRadioSongsRequest Class Reference
MusicFMRadioSongsRequest Class Reference
The class of fm radio request of song info.
#include <musicfmradiosongsrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicFMRadioSongsRequest (QObject *parent=nullptr)
virtual void startToDownload (const QString &id) overridefinal
const MusicObject::MusicSongInformation & songInfo () const
Public Member Functions inherited from MusicAbstractFMRadioRequest
MusicAbstractFMRadioRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Protected Attributes
QString m_cachedID
MusicObject::MusicSongInformation m_songInfo
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Detailed Description
The class of fm radio request of song info.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicfmradiosongsrequest.h.
Constructor & Destructor Documentation
MusicFMRadioSongsRequest::MusicFMRadioSongsRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicfmradiosongsrequest.cpp.
Member Function Documentation
void MusicFMRadioSongsRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 23 of file musicfmradiosongsrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), FM_LRC_URL, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongProperty::m_bitrate, m_cachedID, MusicObject::MusicSongInformation::m_coverUrl, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongInformation::m_lrcUrl, MusicAbstractNetwork::m_reply, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongProperty::m_size, m_songInfo, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicUtils::Number::sizeByte2Label(), startToDownload(), and TTK_LOGGER_ERROR.
Referenced by startToDownload().
const MusicObject::MusicSongInformation& MusicFMRadioSongsRequest::songInfo () const inline
Get music song information.
Definition at line 45 of file musicfmradiosongsrequest.h.
Referenced by MusicWebFMRadioPlayWidget::lrcDownloadStateChanged(), MusicWebFMRadioPlayWidget::picDownloadStateChanged(), MusicWebFMRadioPlayWidget::querySongInfoFinished(), and MusicWebFMRadioPlayWidget::radioResourceDownload().
void MusicFMRadioSongsRequest::startToDownload (const QString & id) final override virtual
Start to download data.
Implements MusicAbstractFMRadioRequest.
Definition at line 9 of file musicfmradiosongsrequest.cpp.
References downLoadFinished(), FM_PLAYLIST_URL, m_cachedID, MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, m_songInfo, MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and MusicObject::setSslConfiguration().
Referenced by downLoadFinished(), MusicWebFMRadioPlayWidget::radioNext(), MusicWebFMRadioPlayWidget::radioPrevious(), and MusicWebFMRadioPlayWidget::updateRadioSong().
Member Data Documentation
QString MusicFMRadioSongsRequest::m_cachedID protected
Definition at line 54 of file musicfmradiosongsrequest.h.
Referenced by downLoadFinished(), and startToDownload().
MusicObject::MusicSongInformation MusicFMRadioSongsRequest::m_songInfo protected
Definition at line 55 of file musicfmradiosongsrequest.h.
Referenced by downLoadFinished(), and startToDownload().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicfmradiosongsrequest.h
TTKModule/TTKCore/musicNetworkKits/radio/fm/musicfmradiosongsrequest.cpp