TTKMusicplayer: QSyncConf Struct Reference
QSyncConf Struct Reference
The class of the sync data config.
#include <qsyncconf.h>
Static Public Attributes
static QString HOST = QString("<Your Host Key>")
static QString NAME = QString("<Your Name Key>")
static QByteArray KEY = QByteArray("<Your Key>")
static QString VERSION = QString("1.0.0")
Detailed Description
The class of the sync data config.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file qsyncconf.h.
Member Data Documentation
QString QSyncConf::HOST = QString("<Your Host Key>") static
Definition at line 32 of file qsyncconf.h.
Referenced by QSyncDeleteData::deleteDataOperator(), QSyncDownloadData::downloadDataOperator(), QSyncDownloadData::downloadUrl(), QSyncListData::listDataOperator(), MusicApplicationModule::loadNetWorkSetting(), QSyncUtils::makeDataBucketUrl(), and QSyncUploadData::uploadDataOperator().
QByteArray QSyncConf::KEY = QByteArray("<Your Key>") static
Definition at line 34 of file qsyncconf.h.
Referenced by MusicCloudManagerTableWidget::downLoadFinished(), QSyncDownloadData::downloadUrl(), QSyncDataInterfacePrivate::insertAuthorization(), and MusicCloudManagerTableWidget::queryCloudKey().
QString QSyncConf::NAME = QString("<Your Name Key>") static
Definition at line 33 of file qsyncconf.h.
Referenced by MusicCloudManagerTableWidget::downLoadFinished(), QSyncDownloadData::downloadUrl(), QSyncDataInterfacePrivate::insertAuthorization(), and MusicCloudManagerTableWidget::queryCloudKey().
QString QSyncConf::VERSION = QString("1.0.0") static
Definition at line 35 of file qsyncconf.h.
The documentation for this struct was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncconf.h
TTKThirdParty/TTKExtras/qsync/qsyncconf.cpp