TTKMusicplayer: OSSConf Struct Reference
OSSConf Struct Reference
The class of the alioss data item.
#include <ossconf.h>
Static Public Member Functions
static QString generateDataBucketUrl ()
Static Public Attributes
static QString OSS_HOST = QString("<Your Host Key>")
static QString ACCESS_KEY = QString("<Your Access Key>")
static QByteArray SECRET_KEY = QByteArray("<Your Secret Key>")
static QString VERSION = QString("1.0.0")
Detailed Description
The class of the alioss data item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file ossconf.h.
Member Function Documentation
QString OSSConf::generateDataBucketUrl () static
Generate data bucket url.
Definition at line 14 of file ossconf.cpp.
References DATA_BUCKET, and OSS_HOST.
Referenced by MusicCloudManagerTableWidget::getKey(), MusicIdentifySongsThread::getKey(), MusicSourceUpdateThread::startToDownload(), and MusicSourceUpdateWidget::upgradeButtonClicked().
Member Data Documentation
QString OSSConf::ACCESS_KEY = QString("<Your Access Key>") static
Definition at line 35 of file ossconf.h.
Referenced by OSSDownloadData::getDownloadUrl(), MusicCloudManagerTableWidget::getKey(), OSSDataInterfacePrivate::insertAuthorization(), and MusicCloudManagerTableWidget::keyDownLoadFinished().
QString OSSConf::OSS_HOST = QString("<Your Host Key>") static
Definition at line 33 of file ossconf.h.
Referenced by OSSDeleteData::deleteDataOperator(), OSSDownloadData::downloadDataOperator(), generateDataBucketUrl(), OSSDownloadData::getDownloadUrl(), OSSListData::listDataOperator(), MusicApplicationObject::loadNetWorkSetting(), and OSSUploadData::uploadDataOperator().
QByteArray OSSConf::SECRET_KEY = QByteArray("<Your Secret Key>") static
Definition at line 36 of file ossconf.h.
Referenced by OSSDownloadData::getDownloadUrl(), MusicCloudManagerTableWidget::getKey(), OSSDataInterfacePrivate::insertAuthorization(), and MusicCloudManagerTableWidget::keyDownLoadFinished().
QString OSSConf::VERSION = QString("1.0.0") static
Definition at line 38 of file ossconf.h.
The documentation for this struct was generated from the following files:
TTKThirdParty/TTKExtras/qoss/ossconf.h
TTKThirdParty/TTKExtras/qoss/ossconf.cpp