TTKMusicplayer: MusicSongsListPlayedTableWidget Class Reference
MusicSongsListPlayedTableWidget Class Reference
The class of the songs played queue list table widget.
#include <musicsongslistplayedtablewidget.h>
Public Slots
virtual void listCellEntered (int row, int column) override
virtual void listCellClicked (int row, int column) override
virtual void setDeleteItemAt () override
Public Slots inherited from MusicSongsListAbstractTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
void musicSongMovieFoundPy ()
void musicSimilarFoundWidgetPy ()
void musicSongSharedWidgetPy ()
void musicSongKMicroWidgetPy ()
Public Slots inherited from MusicSmoothMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void setDeleteItemAt (int index)
Signals inherited from MusicSongsListAbstractTableWidget
void isCurrentIndexs (bool &state)
Public Member Functions
MusicSongsListPlayedTableWidget (QWidget *parent=0)
virtual ~MusicSongsListPlayedTableWidget ()
void clearPlayLaterState ()
void setPlayLaterState (int row)
virtual void updateSongsFileName (const MusicSongs &songs) override
void clearAllItems ()
virtual void selectRow (int index) override
void selectPlayedRow ()
void replacePlayWidgetRow ()
Public Member Functions inherited from MusicSongsListAbstractTableWidget
MusicSongsListAbstractTableWidget (QWidget *parent=0)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSmoothMovingTableWidget
MusicSmoothMovingTableWidget (QWidget *parent=0)
virtual ~MusicSmoothMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicSongsListAbstractTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicSmoothMovingTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from MusicSongsListAbstractTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSmoothMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
MusicSongsListPlayedWidget * m_musicSongsPlayWidget
Protected Attributes inherited from MusicSongsListAbstractTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSmoothMovingTableWidget
bool m_isFirstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the songs played queue list table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicsongslistplayedtablewidget.h.
Constructor & Destructor Documentation
MusicSongsListPlayedTableWidget::MusicSongsListPlayedTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 14 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::m_hasParentToolIndex, m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, and MusicUtils::Widget::setTransparent().
MusicSongsListPlayedTableWidget::~MusicSongsListPlayedTableWidget () virtual
Definition at line 35 of file musicsongslistplayedtablewidget.cpp.
References clearAllItems(), and m_musicSongsPlayWidget.
Member Function Documentation
void MusicSongsListPlayedTableWidget::clearAllItems ()
Clear All Items.
Definition at line 103 of file musicsongslistplayedtablewidget.cpp.
References MusicAbstractTableWidget::clear(), m_musicSongsPlayWidget, and MusicSongsListAbstractTableWidget::m_playRowIndex.
Referenced by MusicPlayedListPopWidget::clear(), MusicPlayedListPopWidget::insert(), and ~MusicSongsListPlayedTableWidget().
void MusicSongsListPlayedTableWidget::clearPlayLaterState ()
Clear play later state.
Definition at line 46 of file musicsongslistplayedtablewidget.cpp.
Referenced by MusicPlayedListPopWidget::cellDoubleClicked(), and MusicPlayedListPopWidget::setDeleteItemAt().
void MusicSongsListPlayedTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 295 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicUIObject::MMenuStyle02, MusicSongsListAbstractTableWidget::musicAlbumFoundWidget(), MusicSongsListAbstractTableWidget::musicFileInformation(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicPlayClicked(), MusicSongsListAbstractTableWidget::musicSongDownload(), and setDeleteItemAt().
QString MusicSongsListPlayedTableWidget::getClassName () static
Get class object name.
Definition at line 41 of file musicsongslistplayedtablewidget.cpp.
void MusicSongsListPlayedTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 245 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicSongsListAbstractTableWidget::m_playRowIndex, MusicSongsListAbstractTableWidget::musicSongDownload(), and setDeleteItemAt().
void MusicSongsListPlayedTableWidget::listCellEntered (int row, int column) override virtual slot
Table widget list cell enter.
clear previous table item state
draw new table item state
Definition at line 196 of file musicsongslistplayedtablewidget.cpp.
References MusicAbstractTableWidget::listCellEntered(), MusicSongsListAbstractTableWidget::m_musicSongs, and MusicAbstractTableWidget::m_previousColorRow.
void MusicSongsListPlayedTableWidget::replacePlayWidgetRow ()
Replace current play widget row.
Definition at line 158 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicUtils::Widget::elidedText(), MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, and MusicUIObject::MColorStyle12_S.
Referenced by MusicPlayedListPopWidget::remove(), selectRow(), MusicPlayedListPopWidget::setDeleteItemAll(), and setDeleteItemAt().
void MusicSongsListPlayedTableWidget::selectPlayedRow ()
Select the current played row.
Definition at line 153 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::m_playRowIndex, and selectRow().
Referenced by MusicPlayedListPopWidget::insert(), and MusicPlayedListPopWidget::popupMenu().
void MusicSongsListPlayedTableWidget::selectRow (int index) override virtual
Select the current play row by given index.
Reimplemented from MusicSongsListAbstractTableWidget.
Definition at line 122 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicSongsListAbstractTableWidget::m_musicSongs, m_musicSongsPlayWidget, MusicSongsListAbstractTableWidget::m_playRowIndex, MusicSmoothMovingTableWidget::m_scrollBar, replacePlayWidgetRow(), MusicSongsListAbstractTableWidget::selectRow(), and MusicSongsListPlayedWidget::setParameter().
Referenced by selectPlayedRow(), MusicPlayedListPopWidget::setCurrentIndex(), and MusicPlayedListPopWidget::setDeleteItemAt().
void MusicSongsListPlayedTableWidget::setDeleteItemAt (int index) signal
Delete item from list at current row.
void MusicSongsListPlayedTableWidget::setDeleteItemAt () override virtual slot
Delete item from list at current row.
Definition at line 272 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicSongsListAbstractTableWidget::m_playRowIndex, and replacePlayWidgetRow().
Referenced by contextMenuEvent(), and listCellClicked().
void MusicSongsListPlayedTableWidget::setPlayLaterState (int row)
Set play later state.
Definition at line 58 of file musicsongslistplayedtablewidget.cpp.
Referenced by MusicPlayedListPopWidget::insert().
void MusicSongsListPlayedTableWidget::updateSongsFileName (const MusicSongs & songs) override virtual
Update songs file names in table.
Reimplemented from MusicSongsListAbstractTableWidget.
Definition at line 72 of file musicsongslistplayedtablewidget.cpp.
References MusicSongsListAbstractTableWidget::allRowsHeight(), MusicUtils::Widget::elidedText(), and MusicUIObject::MColorStyle12_S.
Referenced by MusicPlayedListPopWidget::updateSongsFileName().
Member Data Documentation
MusicSongsListPlayedWidget* MusicSongsListPlayedTableWidget::m_musicSongsPlayWidget protected
Definition at line 101 of file musicsongslistplayedtablewidget.h.
Referenced by clearAllItems(), MusicSongsListPlayedTableWidget(), replacePlayWidgetRow(), selectRow(), and ~MusicSongsListPlayedTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplayedtablewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongslistplayedtablewidget.cpp