TTKMusicplayer: MusicSoundKMicroSearchWidget Class Reference
MusicSoundKMicroSearchWidget Class Reference
The class of the sound kmicro search widget.
#include <musicsoundkmicrosearchwidget.h>
Public Slots
void startToSearch ()
void setQueryMovieFlag (int flag)
void setCurrentSongName (const QString &name)
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicSoundKMicroSearchWidget (QWidget *parent=nullptr)
~MusicSoundKMicroSearchWidget ()
void connectTo (QObject *obj)
void startSeachKMicro (const QString &name)
Public Member Functions inherited from MusicAbstractMoveSingleWidget
MusicAbstractMoveSingleWidget (QWidget *parent=nullptr)
MusicAbstractMoveSingleWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveSingleWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
bool m_queryMovieMode
MusicItemQueryEdit * m_searchEdit
MusicSoundKMicroSearchTableWidget * m_searchTableWidget
Protected Attributes inherited from MusicAbstractMoveSingleWidget
QWidget * m_container
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
Protected Attributes inherited from MusicWidgetRenderer
QLabel * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
Detailed Description
The class of the sound kmicro search widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 101 of file musicsoundkmicrosearchwidget.h.
Constructor & Destructor Documentation
MusicSoundKMicroSearchWidget::MusicSoundKMicroSearchWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 183 of file musicsoundkmicrosearchwidget.cpp.
References MusicAbstractMoveWidget::blockMoveOption(), MusicItemQueryEdit::editor(), MusicAbstractMoveSingleWidget::m_container, m_queryMovieMode, m_searchEdit, m_searchTableWidget, MusicUIObject::MQSSBackgroundStyle06, MusicUIObject::MQSSBackgroundStyle11, MusicUIObject::MQSSColorStyle01, MusicUIObject::MQSSRadioButtonStyle01, setCurrentSongName(), setQueryMovieFlag(), and startToSearch().
MusicSoundKMicroSearchWidget::~MusicSoundKMicroSearchWidget ()
Definition at line 245 of file musicsoundkmicrosearchwidget.cpp.
References m_searchEdit, and m_searchTableWidget.
Member Function Documentation
void MusicSoundKMicroSearchWidget::connectTo (QObject * obj)
Connect to parent.
Definition at line 251 of file musicsoundkmicrosearchwidget.cpp.
References m_searchTableWidget.
Referenced by MusicSoundKMicroWidget::MusicSoundKMicroWidget().
void MusicSoundKMicroSearchWidget::setCurrentSongName (const QString & name) slot
Set current search song name.
Definition at line 272 of file musicsoundkmicrosearchwidget.cpp.
References MusicToastLabel::popup().
Referenced by MusicSoundKMicroSearchWidget().
void MusicSoundKMicroSearchWidget::setQueryMovieFlag (int flag) slot
Set query MV flag.
Definition at line 267 of file musicsoundkmicrosearchwidget.cpp.
References m_queryMovieMode.
Referenced by MusicSoundKMicroSearchWidget().
void MusicSoundKMicroSearchWidget::startSeachKMicro (const QString & name)
Start seach KMicro.
Definition at line 256 of file musicsoundkmicrosearchwidget.cpp.
References MusicItemQueryEdit::editor(), m_searchEdit, and startToSearch().
Referenced by MusicSoundKMicroWidget::startSeachKMicro().
void MusicSoundKMicroSearchWidget::startToSearch () slot
Start to search.
Definition at line 262 of file musicsoundkmicrosearchwidget.cpp.
References MusicItemQueryEdit::editor(), m_queryMovieMode, m_searchEdit, m_searchTableWidget, MusicSoundKMicroSearchTableWidget::setQueryMovieFlag(), and MusicSoundKMicroSearchTableWidget::startSearchQuery().
Referenced by MusicSoundKMicroSearchWidget(), and startSeachKMicro().
Member Data Documentation
bool MusicSoundKMicroSearchWidget::m_queryMovieMode protected
Definition at line 136 of file musicsoundkmicrosearchwidget.h.
Referenced by MusicSoundKMicroSearchWidget(), setQueryMovieFlag(), and startToSearch().
MusicItemQueryEdit* MusicSoundKMicroSearchWidget::m_searchEdit protected
Definition at line 137 of file musicsoundkmicrosearchwidget.h.
Referenced by MusicSoundKMicroSearchWidget(), startSeachKMicro(), startToSearch(), and ~MusicSoundKMicroSearchWidget().
MusicSoundKMicroSearchTableWidget* MusicSoundKMicroSearchWidget::m_searchTableWidget protected
Definition at line 138 of file musicsoundkmicrosearchwidget.h.
Referenced by connectTo(), MusicSoundKMicroSearchWidget(), startToSearch(), and ~MusicSoundKMicroSearchWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrosearchwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrosearchwidget.cpp