TTKMusicplayer: MusicPlaylistReader Class Reference
MusicPlaylistReader Class Reference
The class of the playlist reader.
#include <musicplaylistinterface.h>
Public Member Functions
MusicPlaylistReader ()
virtual ~MusicPlaylistReader ()
bool fromFile (const QString &name)
Protected Attributes
QFile m_file
Detailed Description
The class of the playlist reader.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicplaylistinterface.h.
Constructor & Destructor Documentation
MusicPlaylistReader::MusicPlaylistReader () inline explicit
Definition at line 30 of file musicplaylistinterface.h.
virtual MusicPlaylistReader::~MusicPlaylistReader () inline virtual
Definition at line 34 of file musicplaylistinterface.h.
Member Function Documentation
bool MusicPlaylistReader::fromFile (const QString & name) inline
Read datas from file by given name.
Definition at line 41 of file musicplaylistinterface.h.
Referenced by MusicPlaylistManager::readCSVConfig(), MusicPlaylistManager::readDBPLConfig(), MusicPlaylistManager::readFPLConfig(), MusicPlaylistManager::readM3UConfig(), MusicPlaylistManager::readPLSConfig(), and MusicPlaylistManager::readTXTConfig().
Member Data Documentation
QFile MusicPlaylistReader::m_file protected
Definition at line 48 of file musicplaylistinterface.h.
Referenced by MusicCSVConfigManager::readBuffer(), MusicFPLConfigManager::readBuffer(), MusicTXTConfigManager::readBuffer(), MusicM3UConfigManager::readBuffer(), MusicPLSConfigManager::readBuffer(), MusicDBPLConfigManager::readBuffer(), MusicCSVConfigManager::writeBuffer(), MusicTXTConfigManager::writeBuffer(), MusicM3UConfigManager::writeBuffer(), and MusicPLSConfigManager::writeBuffer().
The documentation for this class was generated from the following file:
TTKModule/TTKCore/musicPlaylistKits/musicplaylistinterface.h