TTKMusicPlayer: TTKThirdParty/Zlib/zlib/gzguts.h File Reference
gzguts.h File Reference
#include <stdio.h>
#include "zlib.h"
#include <fcntl.h>
#include <errno.h>
Classes
struct gz_state
Macros
#define ZLIB_INTERNAL
#define _POSIX_SOURCE
#define local static
#define zstrerror() strerror(errno)
#define DEF_MEM_LEVEL 8
#define GZBUFSIZE 8192
#define GZ_NONE 0
#define GZ_READ 7247
#define GZ_WRITE 31153
#define GZ_APPEND 1 /* mode set to GZ_WRITE after the file is opened */
#define LOOK 0 /* look for a gzip header */
#define COPY 1 /* copy input directly */
#define GZIP 2 /* decompress a gzip stream */
#define GT_OFF(x) (sizeof(int) == sizeof(z_off64_t) && (x) > gz_intmax())
Typedefs
typedef gz_state FAR * gz_statep
Functions
voidp malloc (uInt size)
void free (voidpf ptr)
ZEXTERN gzFile ZEXPORT gzopen64 (const char *, const char *)
ZEXTERN z_off64_t ZEXPORT gzseek64 (gzFile, z_off64_t, int)
ZEXTERN z_off64_t ZEXPORT gztell64 (gzFile)
ZEXTERN z_off64_t ZEXPORT gzoffset64 (gzFile)
void ZLIB_INTERNAL gz_error (gz_statep, int, const char *)
unsigned ZLIB_INTERNAL gz_intmax (void)
Macro Definition Documentation
#define _POSIX_SOURCE
Definition at line 29 of file gzguts.h.
#define COPY 1 /* copy input directly */
Definition at line 165 of file gzguts.h.
#define DEF_MEM_LEVEL 8
Definition at line 148 of file gzguts.h.
#define GT_OFF (x) (sizeof(int) == sizeof(z_off64_t) && (x) > gz_intmax())
Definition at line 217 of file gzguts.h.
Referenced by gz_skip(), gz_zero(), and gzseek64().
#define GZ_APPEND 1 /* mode set to GZ_WRITE after the file is opened */
Definition at line 161 of file gzguts.h.
Referenced by gz_open().
#define GZ_NONE 0
Definition at line 158 of file gzguts.h.
Referenced by gz_open().
#define GZ_READ 7247
Definition at line 159 of file gzguts.h.
Referenced by gz_open(), gz_reset(), gzbuffer(), gzclearerr(), gzclose(), gzclose_r(), gzdirect(), gzeof(), gzerror(), gzfread(), gzgetc(), gzgets(), gzoffset64(), gzread(), gzrewind(), gzseek64(), gztell64(), and gzungetc().
#define GZ_WRITE 31153
Definition at line 160 of file gzguts.h.
Referenced by gz_open(), gzbuffer(), gzclearerr(), gzclose_w(), gzeof(), gzerror(), gzflush(), gzfwrite(), gzoffset64(), gzprintf(), gzputc(), gzputs(), gzseek64(), gzsetparams(), gztell64(), and gzwrite().
#define GZBUFSIZE 8192
Definition at line 155 of file gzguts.h.
Referenced by gz_open().
#define GZIP 2 /* decompress a gzip stream */
Definition at line 166 of file gzguts.h.
#define local static
Definition at line 113 of file gzguts.h.
#define LOOK 0 /* look for a gzip header */
Definition at line 164 of file gzguts.h.
Referenced by gz_decomp(), gz_fetch(), gz_read(), gz_reset(), gzdirect(), and gzungetc().
#define ZLIB_INTERNAL
Definition at line 17 of file gzguts.h.
#define zstrerror () strerror(errno)
Definition at line 132 of file gzguts.h.
Referenced by gz_comp(), and gz_load().
Typedef Documentation
typedef gz_state FAR* gz_statep
Definition at line 202 of file gzguts.h.
Function Documentation
void free (voidpf ptr)
Referenced by BitStream_free(), BitStream_new(), MusicDeviceInfoModule::disksProperty(), TTKCryptographicHash::doXxteaDecrypt(), TTKCryptographicHash::doXxteaEncrypt(), QAlgorithm::DesPrivate::encrypt(), free_rs_char(), gz_error(), gz_init(), gz_look(), gz_open(), gzclose_r(), gzclose_w(), gzdopen(), init_rs_char(), Mask_mask(), MMask_mask(), MQRraw_free(), MQRraw_new(), QRcode_encodeMask(), QRcode_encodeMaskMQR(), QRcode_free(), QRcode_List_freeEntry(), QRinput_free(), QRinput_InputList_freeEntry(), QRinput_List_dup(), QRinput_List_freeEntry(), QRinput_List_newEntry(), QRinput_List_shrinkEntry(), QRinput_Struct_free(), QRraw_free(), QRraw_new(), QAlgorithm::GaussBlur::render(), Split_splitStringToQRinput(), unzRepair(), win32_close_file_func(), TTKCryptographicHash::xxteaDecrypt(), TTKCryptographicHash::xxteaEncrypt(), zipCloseFileInZipRaw64(), and QHttpConnectionPrivate::~QHttpConnectionPrivate().
void ZLIB_INTERNAL gz_error (gz_statep , int , const char *)
Definition at line 529 of file gzlib.c.
References free(), malloc(), Z_BUF_ERROR, Z_MEM_ERROR, and Z_OK.
Referenced by gz_comp(), gz_decomp(), gz_init(), gz_load(), gz_look(), gz_reset(), gzclearerr(), gzclose_r(), gzclose_w(), gzfread(), gzfwrite(), gzputs(), gzread(), gzseek64(), gzungetc(), and gzwrite().
unsigned ZLIB_INTERNAL gz_intmax (void)
Definition at line 571 of file gzlib.c.
ZEXTERN z_off64_t ZEXPORT gzoffset64 (gzFile)
Definition at line 443 of file gzlib.c.
References GZ_READ, GZ_WRITE, LSEEK, SEEK_CUR, and z_off64_t.
Referenced by gzoffset().
ZEXTERN gzFile ZEXPORT gzopen64 (const char * , const char *)
Definition at line 265 of file gzlib.c.
References gz_open().
ZEXTERN z_off64_t ZEXPORT gzseek64 (gzFile , z_off64_t , int)
Definition at line 339 of file gzlib.c.
References COPY, GT_OFF, gz_error(), GZ_READ, GZ_WRITE, gzrewind(), LSEEK, gzFile_s::pos, SEEK_CUR, SEEK_SET, Z_BUF_ERROR, z_off64_t, and Z_OK.
Referenced by gzseek().
ZEXTERN z_off64_t ZEXPORT gztell64 (gzFile)
Definition at line 420 of file gzlib.c.
References GZ_READ, GZ_WRITE, and gzFile_s::pos.
Referenced by gztell().
voidp malloc (uInt size)
Referenced by BitStream_new(), BitStream_toByte(), MusicDeviceInfoModule::disksProperty(), QAlgorithm::DesPrivate::encrypt(), TTKCryptographicHash::fixKeyLength(), gz_error(), gz_init(), gz_look(), gz_open(), gzdopen(), init_rs_char(), Mask_makeMask(), Mask_mask(), MMask_makeMask(), MMask_mask(), MQRraw_new(), MQRspec_createFrame(), QHttpConnectionPrivate::QHttpConnectionPrivate(), QRcode_encodeMask(), QRcode_encodeMaskMQR(), QRcode_List_newEntry(), QRcode_new(), QRinput_InputList_newEntry(), QRinput_List_dup(), QRinput_List_newEntry(), QRinput_List_shrinkEntry(), QRinput_new2(), QRinput_Struct_new(), QRraw_new(), QRspec_createFrame(), QAlgorithm::GaussBlur::render(), strdup(), unzRepair(), win32_build_iowin(), TTKCryptographicHash::xxteaToByteArray(), and TTKCryptographicHash::xxteaToUintArray().