TTKMusicplayer: MusicTimerSliderWidget Class Reference
MusicTimerSliderWidget Class Reference
The class of the timer slider widget.
#include <musictimersliderwidget.h>
Public Slots
void sliderMovedAt (int pos) const
void setSliderStyleByType (int type)
Public Member Functions
MusicTimerSliderWidget (QWidget *parent=0)
~MusicTimerSliderWidget ()
void setPlayState (bool state)
void setValue (qint64 value) const
void setRange (int min, int max)
void setObject (QObject *object) const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
Protected Attributes
MusicGifLabelWidget * m_label
MusicMovingLabelSlider * m_slider
Detailed Description
The class of the timer slider widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 23 of file musictimersliderwidget.h.
Constructor & Destructor Documentation
MusicTimerSliderWidget::MusicTimerSliderWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 8 of file musictimersliderwidget.cpp.
References MusicGifLabelWidget::Gif_Ballon_White, m_label, m_slider, MusicUIObject::MSliderStyle07, MusicGifLabelWidget::setType(), and MusicMovingLabelSlider::setValue().
MusicTimerSliderWidget::~MusicTimerSliderWidget ()
Definition at line 30 of file musictimersliderwidget.cpp.
References m_label, and m_slider.
Member Function Documentation
QString MusicTimerSliderWidget::getClassName () static
Get class object name.
Definition at line 36 of file musictimersliderwidget.cpp.
void MusicTimerSliderWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Definition at line 95 of file musictimersliderwidget.cpp.
References m_label, m_slider, and sliderMovedAt().
void MusicTimerSliderWidget::setObject (QObject * object) const
Set connect current object.
Definition at line 24 of file musictimersliderwidget.cpp.
References m_slider, and sliderMovedAt().
void MusicTimerSliderWidget::setPlayState (bool state)
Set current play state.
Definition at line 41 of file musictimersliderwidget.cpp.
References m_label, MusicGifLabelWidget::start(), and MusicGifLabelWidget::stop().
void MusicTimerSliderWidget::setRange (int min, int max)
Set current play range from min and max.
Definition at line 65 of file musictimersliderwidget.cpp.
References m_slider.
void MusicTimerSliderWidget::setSliderStyleByType (int type) slot
Set slider style diff by diff enhanced effect.
Definition at line 80 of file musictimersliderwidget.cpp.
References m_slider, and MusicUIObject::MSliderStyle07.
void MusicTimerSliderWidget::setValue (qint64 value) const
Set current play index value.
Definition at line 56 of file musictimersliderwidget.cpp.
References MusicMovingLabelSlider::isMoving(), m_slider, MusicMovingLabelSlider::setValue(), and sliderMovedAt().
void MusicTimerSliderWidget::sliderMovedAt (int pos) const slot
Current slider move at pos.
Definition at line 70 of file musictimersliderwidget.cpp.
References m_label, and m_slider.
Referenced by resizeEvent(), setObject(), and setValue().
Member Data Documentation
MusicGifLabelWidget* MusicTimerSliderWidget::m_label protected
Definition at line 71 of file musictimersliderwidget.h.
Referenced by MusicTimerSliderWidget(), resizeEvent(), setPlayState(), sliderMovedAt(), and ~MusicTimerSliderWidget().
MusicMovingLabelSlider* MusicTimerSliderWidget::m_slider protected
Definition at line 72 of file musictimersliderwidget.h.
Referenced by MusicTimerSliderWidget(), resizeEvent(), setObject(), setRange(), setSliderStyleByType(), setValue(), sliderMovedAt(), and ~MusicTimerSliderWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musictimersliderwidget.h
TTKModule/TTKWidget/musicWidgetCoreKits/musictimersliderwidget.cpp