TTKMusicplayer: MusicPlayBackModePopWidget Class Reference
MusicPlayBackModePopWidget Class Reference
The class of the play back mode pop widget.
#include <musicplaybackmodepopwidget.h>
Public Member Functions
MusicPlayBackModePopWidget (QWidget *parent=nullptr)
void initWidget ()
void setPlaybackMode (MusicObject::PlayMode mode)
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Additional Inherited Members
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the play back mode pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicplaybackmodepopwidget.h.
Constructor & Destructor Documentation
MusicPlayBackModePopWidget::MusicPlayBackModePopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicplaybackmodepopwidget.cpp.
References initWidget().
Member Function Documentation
void MusicPlayBackModePopWidget::initWidget ()
Create all widget in layout.
Definition at line 41 of file musicplaybackmodepopwidget.cpp.
References MusicApplication::instance(), MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicPlayBackModePopWidget().
void MusicPlayBackModePopWidget::setPlaybackMode (MusicObject::PlayMode mode)
Set current play mode.
Definition at line 12 of file musicplaybackmodepopwidget.cpp.
References MusicUIObject::MQSSBtnListLoop, MusicUIObject::MQSSBtnOnce, MusicUIObject::MQSSBtnOneLoop, MusicUIObject::MQSSBtnOrder, MusicUIObject::MQSSBtnRandom, MusicObject::PM_PlaylistLoop, MusicObject::PM_PlayOnce, MusicObject::PM_PlayOneLoop, MusicObject::PM_PlayOrder, and MusicObject::PM_PlayRandom.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaybackmodepopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaybackmodepopwidget.cpp