TTKMusicPlayer: TTKThirdParty/Zlib/ttkzip/zip.c File Reference
zip.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "zlib/zlib.h"
#include "zip.h"
#include <errno.h>
#include "crypt.h"
Classes
struct linkedlist_datablock_internal_s
struct linkedlist_data_s
struct curfile64_info
struct zip64_internal
Macros
#define local static
#define VERSIONMADEBY (0x0) /* platform depedent */
#define Z_BUFSIZE (64*1024)
#define Z_MAXFILENAMEINZIP (256)
#define ALLOC(size) (malloc(size))
#define TRYFREE(p) {if (p) free(p);}
#define MAKEULONG64(a, b) ((ZPOS64_T)(((unsigned long)(a)) | ((ZPOS64_T)((unsigned long)(b))) << 32))
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
#define SIZEDATA_INDATABLOCK (4096-(4*4))
#define LOCALHEADERMAGIC (0x04034b50)
#define CENTRALHEADERMAGIC (0x02014b50)
#define ENDHEADERMAGIC (0x06054b50)
#define ZIP64ENDHEADERMAGIC (0x6064b50)
#define ZIP64ENDLOCHEADERMAGIC (0x7064b50)
#define FLAG_LOCALHEADER_OFFSET (0x06)
#define CRC_LOCALHEADER_OFFSET (0x0e)
#define SIZECENTRALHEADER (0x2e) /* 46 */
#define INCLUDECRYPTINGCODE_IFCRYPTALLOWED
#define BUFREADCOMMENT (0x400)
Typedefs
typedef struct linkedlist_datablock_internal_s linkedlist_datablock_internal
typedef struct linkedlist_data_s linkedlist_data
Functions
local linkedlist_datablock_internal * allocate_new_datablock ()
local void free_datablock (linkedlist_datablock_internal *ldi)
local void init_linkedlist (linkedlist_data *ll)
local void free_linkedlist (linkedlist_data *ll)
local int add_data_in_datablock (linkedlist_data *ll, const void *buf, uLong len)
local int zip64local_putValue OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte))
local int zip64local_putValue (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte)
local void zip64local_putValue_inmemory OF ((void *dest, ZPOS64_T x, int nbByte))
local void zip64local_putValue_inmemory (void *dest, ZPOS64_T x, int nbByte)
local uLong zip64local_TmzDateToDosDate (const tm_zip *ptm)
local int zip64local_getByte OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi))
local int zip64local_getByte (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi)
local int zip64local_getShort OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
local int zip64local_getShort (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)
local int zip64local_getLong (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)
local int zip64local_getLong64 OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX))
local int zip64local_getLong64 (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX)
local ZPOS64_T zip64local_SearchCentralDir OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream))
local ZPOS64_T zip64local_SearchCentralDir (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)
local ZPOS64_T zip64local_SearchCentralDir64 (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)
int LoadCentralDirectoryRecord (zip64_internal *pziinit)
ZEXTERN zipFile ZEXPORT zipOpen3 (const void *pathname, int append, zipcharpc *globalcomment, zlib_filefunc64_32_def *pzlib_filefunc64_32_def)
ZEXTERN zipFile ZEXPORT zipOpen2 (const char *pathname, int append, zipcharpc *globalcomment, zlib_filefunc_def *pzlib_filefunc32_def)
ZEXTERN zipFile ZEXPORT zipOpen2_64 (const void *pathname, int append, zipcharpc *globalcomment, zlib_filefunc64_def *pzlib_filefunc_def)
ZEXTERN zipFile ZEXPORT zipOpen (const char *pathname, int append)
ZEXTERN zipFile ZEXPORT zipOpen64 (const void *pathname, int append)
int Write_LocalFileHeader (zip64_internal *zi, const char *filename, uInt size_extrafield_local, const void *extrafield_local)
ZEXTERN int ZEXPORT zipOpenNewFileInZip4_64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase, int zip64)
ZEXTERN int ZEXPORT zipOpenNewFileInZip4 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase)
ZEXTERN int ZEXPORT zipOpenNewFileInZip3 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting)
ZEXTERN int ZEXPORT zipOpenNewFileInZip3_64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, int zip64)
ZEXTERN int ZEXPORT zipOpenNewFileInZip2 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw)
ZEXTERN int ZEXPORT zipOpenNewFileInZip2_64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int zip64)
ZEXTERN int ZEXPORT zipOpenNewFileInZip64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int zip64)
ZEXTERN int ZEXPORT zipOpenNewFileInZip (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level)
local int zip64FlushWriteBuffer (zip64_internal *zi)
ZEXTERN int ZEXPORT zipWriteInFileInZip (zipFile file, const void *buf, unsigned int len)
ZEXTERN int ZEXPORT zipCloseFileInZipRaw (zipFile file, uLong uncompressed_size, uLong crc32)
ZEXTERN int ZEXPORT zipCloseFileInZipRaw64 (zipFile file, ZPOS64_T uncompressed_size, uLong crc32)
ZEXTERN int ZEXPORT zipCloseFileInZip (zipFile file)
int Write_Zip64EndOfCentralDirectoryLocator (zip64_internal *zi, ZPOS64_T zip64eocd_pos_inzip)
int Write_Zip64EndOfCentralDirectoryRecord (zip64_internal *zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
int Write_EndOfCentralDirectoryRecord (zip64_internal *zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
int Write_GlobalComment (zip64_internal *zi, const char *global_comment)
ZEXTERN int ZEXPORT zipClose (zipFile file, const char *global_comment)
ZEXTERN int ZEXPORT zipRemoveExtraInfoBlock (char *pData, int *dataLen, short sHeader)
Variables
const char zip_copyright [] =" zip 1.01 Copyright 1998-2004 Gilles Vollant - http://www.winimage.com/zLibDll"
Macro Definition Documentation
#define ALLOC (size) (malloc(size))
Definition at line 62 of file zip.c.
Referenced by allocate_new_datablock(), LoadCentralDirectoryRecord(), zip64local_SearchCentralDir(), zip64local_SearchCentralDir64(), zipOpen3(), zipOpenNewFileInZip4_64(), and zipRemoveExtraInfoBlock().
#define BUFREADCOMMENT (0x400)
Definition at line 472 of file zip.c.
Referenced by zip64local_SearchCentralDir(), and zip64local_SearchCentralDir64().
#define CENTRALHEADERMAGIC (0x02014b50)
Definition at line 104 of file zip.c.
Referenced by zipOpenNewFileInZip4_64().
#define CRC_LOCALHEADER_OFFSET (0x0e)
Definition at line 110 of file zip.c.
#define ENDHEADERMAGIC (0x06054b50)
Definition at line 105 of file zip.c.
Referenced by Write_EndOfCentralDirectoryRecord().
#define FLAG_LOCALHEADER_OFFSET (0x06)
Definition at line 109 of file zip.c.
#define INCLUDECRYPTINGCODE_IFCRYPTALLOWED
Definition at line 185 of file zip.c.
#define local static
Definition at line 45 of file zip.c.
#define LOCALHEADERMAGIC (0x04034b50)
Definition at line 103 of file zip.c.
Referenced by Write_LocalFileHeader().
#define MAKEULONG64 (a, b) ((ZPOS64_T)(((unsigned long)(a)) | ((ZPOS64_T)((unsigned long)(b))) << 32))
Definition at line 77 of file zip.c.
#define SEEK_CUR 1
Definition at line 80 of file zip.c.
Referenced by fseek64_file_func(), fseek_file_func(), gz_open(), gzoffset64(), and gzseek64().
#define SEEK_END 2
Definition at line 84 of file zip.c.
Referenced by fseek64_file_func(), fseek_file_func(), gz_open(), and zipOpen3().
#define SEEK_SET 0
Definition at line 88 of file zip.c.
Referenced by MusicAudioRecorderModule::addWavHeader(), fseek64_file_func(), fseek_file_func(), gzrewind(), gzseek64(), and unzOpenCurrentFile3().
#define SIZECENTRALHEADER (0x2e) /* 46 */
Definition at line 112 of file zip.c.
Referenced by zipOpenNewFileInZip4_64().
#define SIZEDATA_INDATABLOCK (4096-(4*4))
Definition at line 101 of file zip.c.
Referenced by allocate_new_datablock(), and LoadCentralDirectoryRecord().
#define TRYFREE (p) {if (p) free(p);}
Definition at line 65 of file zip.c.
Referenced by free_datablock(), LoadCentralDirectoryRecord(), zip64local_SearchCentralDir(), zip64local_SearchCentralDir64(), zipClose(), zipOpen3(), and zipRemoveExtraInfoBlock().
#define VERSIONMADEBY (0x0) /* platform depedent */
Definition at line 50 of file zip.c.
Referenced by zipOpenNewFileInZip(), zipOpenNewFileInZip2(), zipOpenNewFileInZip2_64(), zipOpenNewFileInZip3(), zipOpenNewFileInZip3_64(), and zipOpenNewFileInZip64().
#define Z_BUFSIZE (64*1024)
Definition at line 54 of file zip.c.
Referenced by zipCloseFileInZipRaw64(), zipOpenNewFileInZip4_64(), and zipWriteInFileInZip().
#define Z_MAXFILENAMEINZIP (256)
Definition at line 58 of file zip.c.
#define ZIP64ENDHEADERMAGIC (0x6064b50)
Definition at line 106 of file zip.c.
Referenced by Write_Zip64EndOfCentralDirectoryRecord().
#define ZIP64ENDLOCHEADERMAGIC (0x7064b50)
Definition at line 107 of file zip.c.
Referenced by Write_Zip64EndOfCentralDirectoryLocator().
Typedef Documentation
typedef struct linkedlist_data_s linkedlist_data
typedef struct linkedlist_datablock_internal_s linkedlist_datablock_internal
Function Documentation
local int add_data_in_datablock (linkedlist_data * ll, const void * buf, uLong len)
Definition at line 225 of file zip.c.
References allocate_new_datablock(), linkedlist_datablock_internal_s::avail_in_this_block, linkedlist_datablock_internal_s::data, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_data_s::first_block, linkedlist_data_s::last_block, linkedlist_datablock_internal_s::next_datablock, ZIP_INTERNALERROR, and ZIP_OK.
Referenced by LoadCentralDirectoryRecord(), and zipCloseFileInZipRaw64().
local linkedlist_datablock_internal* allocate_new_datablock ()
Definition at line 189 of file zip.c.
References ALLOC, linkedlist_datablock_internal_s::avail_in_this_block, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_datablock_internal_s::next_datablock, and SIZEDATA_INDATABLOCK.
Referenced by add_data_in_datablock().
local void free_datablock (linkedlist_datablock_internal * ldi)
Definition at line 203 of file zip.c.
References linkedlist_datablock_internal_s::next_datablock, and TRYFREE.
Referenced by free_linkedlist().
local void free_linkedlist (linkedlist_data * ll)
Definition at line 218 of file zip.c.
References linkedlist_data_s::first_block, free_datablock(), and linkedlist_data_s::last_block.
Referenced by zipClose().
local void init_linkedlist (linkedlist_data * ll)
Definition at line 213 of file zip.c.
References linkedlist_data_s::first_block, and linkedlist_data_s::last_block.
Referenced by zipOpen3().
int LoadCentralDirectoryRecord (zip64_internal * pziinit)
Definition at line 640 of file zip.c.
References add_data_in_datablock(), zip64_internal::add_position_when_writing_offset, ALLOC, zip64_internal::begin_pos, zip64_internal::central_dir, zip64_internal::filestream, zip64_internal::globalcomment, zip64_internal::number_entry, SIZEDATA_INDATABLOCK, TRYFREE, zip64_internal::z_filefunc, ZCLOSE64, zip64local_getLong(), zip64local_getLong64(), zip64local_getShort(), zip64local_SearchCentralDir(), zip64local_SearchCentralDir64(), ZIP_BADZIPFILE, ZIP_ERRNO, ZIP_OK, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, and ZSEEK64.
Referenced by zipOpen3().
local int zip64local_putValue OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte))
local void zip64local_putValue_inmemory OF ((void *dest, ZPOS64_T x, int nbByte))
local int zip64local_getByte OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi))
local int zip64local_getShort OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
local int zip64local_getLong64 OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX))
local ZPOS64_T zip64local_SearchCentralDir OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream))
int Write_EndOfCentralDirectoryRecord (zip64_internal * zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
Definition at line 1816 of file zip.c.
References zip64_internal::add_position_when_writing_offset, ENDHEADERMAGIC, zip64_internal::filestream, zip64_internal::number_entry, zip64_internal::z_filefunc, zip64local_putValue(), and ZIP_OK.
Referenced by zipClose().
int Write_GlobalComment (zip64_internal * zi, const char * global_comment)
Definition at line 1864 of file zip.c.
References zip64_internal::filestream, zip64_internal::z_filefunc, zip64local_putValue(), ZIP_ERRNO, ZIP_OK, and ZWRITE64.
Referenced by zipClose().
int Write_LocalFileHeader (zip64_internal * zi, const char * filename, uInt size_extrafield_local, const void * extrafield_local)
Definition at line 958 of file zip.c.
References zip64_internal::ci, curfile64_info::dosDate, zip64_internal::filestream, curfile64_info::flag, LOCALHEADERMAGIC, curfile64_info::method, curfile64_info::pos_zip64extrainfo, zip64_internal::z_filefunc, curfile64_info::zip64, zip64local_putValue(), ZIP_ERRNO, ZIP_OK, ZTELL64, and ZWRITE64.
Referenced by zipOpenNewFileInZip4_64().
int Write_Zip64EndOfCentralDirectoryLocator (zip64_internal * zi, ZPOS64_T zip64eocd_pos_inzip)
Definition at line 1755 of file zip.c.
References zip64_internal::add_position_when_writing_offset, zip64_internal::filestream, zip64_internal::z_filefunc, ZIP64ENDLOCHEADERMAGIC, zip64local_putValue(), and ZIP_OK.
Referenced by zipClose().
int Write_Zip64EndOfCentralDirectoryRecord (zip64_internal * zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
Definition at line 1777 of file zip.c.
References zip64_internal::add_position_when_writing_offset, zip64_internal::filestream, zip64_internal::number_entry, zip64_internal::z_filefunc, ZIP64ENDHEADERMAGIC, zip64local_putValue(), and ZIP_OK.
Referenced by zipClose().
local int zip64FlushWriteBuffer (zip64_internal * zi)
Definition at line 1363 of file zip.c.
References curfile64_info::buffered_data, zip64_internal::ci, curfile64_info::encrypt, zip64_internal::filestream, curfile64_info::keys, curfile64_info::method, curfile64_info::pcrc_32_tab, curfile64_info::pos_in_buffered_data, curfile64_info::stream, z_stream_s::total_in, curfile64_info::totalCompressedData, curfile64_info::totalUncompressedData, Z_BZIP2ED, zip64_internal::z_filefunc, zencode, ZIP_ERRNO, ZIP_OK, and ZWRITE64.
Referenced by zipCloseFileInZipRaw64(), and zipWriteInFileInZip().
local int zip64local_getByte (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, int * pi)
Definition at line 349 of file zip.c.
References int(), ZERROR64, ZIP_EOF, ZIP_ERRNO, ZIP_OK, and ZREAD64.
Referenced by zip64local_getLong(), zip64local_getLong64(), and zip64local_getShort().
local int zip64local_getLong (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, uLong * pX)
Definition at line 395 of file zip.c.
References zip64local_getByte(), and ZIP_OK.
Referenced by LoadCentralDirectoryRecord(), and zip64local_SearchCentralDir64().
local int zip64local_getLong64 (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, ZPOS64_T * pX)
Definition at line 426 of file zip.c.
References zip64local_getByte(), and ZIP_OK.
Referenced by LoadCentralDirectoryRecord(), and zip64local_SearchCentralDir64().
local int zip64local_getShort (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, uLong * pX)
Definition at line 373 of file zip.c.
References zip64local_getByte(), and ZIP_OK.
Referenced by LoadCentralDirectoryRecord().
local int zip64local_putValue (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte)
Definition at line 287 of file zip.c.
References ZIP_ERRNO, ZIP_OK, and ZWRITE64.
Referenced by Write_EndOfCentralDirectoryRecord(), Write_GlobalComment(), Write_LocalFileHeader(), Write_Zip64EndOfCentralDirectoryLocator(), Write_Zip64EndOfCentralDirectoryRecord(), and zipCloseFileInZipRaw64().
local void zip64local_putValue_inmemory (void * dest, ZPOS64_T x, int nbByte)
Definition at line 311 of file zip.c.
Referenced by zipCloseFileInZipRaw64(), and zipOpenNewFileInZip4_64().
local ZPOS64_T zip64local_SearchCentralDir (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream)
Definition at line 480 of file zip.c.
References ALLOC, BUFREADCOMMENT, TRYFREE, ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, ZSEEK64, and ZTELL64.
Referenced by LoadCentralDirectoryRecord().
local ZPOS64_T zip64local_SearchCentralDir64 (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream)
Definition at line 542 of file zip.c.
References ALLOC, BUFREADCOMMENT, TRYFREE, zip64local_getLong(), zip64local_getLong64(), ZIP_OK, ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, ZSEEK64, and ZTELL64.
Referenced by LoadCentralDirectoryRecord().
local uLong zip64local_TmzDateToDosDate (const tm_zip * ptm)
Definition at line 332 of file zip.c.
References tm_zip_s::tm_hour, tm_zip_s::tm_mday, tm_zip_s::tm_min, tm_zip_s::tm_mon, tm_zip_s::tm_sec, and tm_zip_s::tm_year.
Referenced by zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipClose (zipFile file, const char * global_comment)
Definition at line 1882 of file zip.c.
References zip64_internal::add_position_when_writing_offset, zip64_internal::central_dir, linkedlist_datablock_internal_s::data, zip64_internal::filestream, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_data_s::first_block, free_linkedlist(), zip64_internal::globalcomment, zip64_internal::in_opened_file_inzip, linkedlist_datablock_internal_s::next_datablock, zip64_internal::number_entry, TRYFREE, Write_EndOfCentralDirectoryRecord(), Write_GlobalComment(), Write_Zip64EndOfCentralDirectoryLocator(), Write_Zip64EndOfCentralDirectoryRecord(), zip64_internal::z_filefunc, ZCLOSE64, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, zipCloseFileInZip(), ZTELL64, and ZWRITE64.
Referenced by MusicExtractManager::inputData(), and MusicExtractManager::inputSkin().
ZEXTERN int ZEXPORT zipCloseFileInZip (zipFile file)
Definition at line 1750 of file zip.c.
References zipCloseFileInZipRaw().
Referenced by MusicExtractManager::inputData(), MusicExtractManager::inputSkin(), zipClose(), and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipCloseFileInZipRaw (zipFile file, uLong uncompressed_size, uLong crc32)
Definition at line 1509 of file zip.c.
References zipCloseFileInZipRaw64().
Referenced by zipCloseFileInZip().
ZEXTERN int ZEXPORT zipCloseFileInZipRaw64 (zipFile file, ZPOS64_T uncompressed_size, uLong crc32)
set internal file attributes field
Definition at line 1514 of file zip.c.
References add_data_in_datablock(), z_stream_s::avail_in, z_stream_s::avail_out, curfile64_info::buffered_data, zip64_internal::central_dir, curfile64_info::central_header, zip64_internal::ci, curfile64_info::crc32, curfile64_info::crypt_header_size, z_stream_s::data_type, deflate(), deflateEnd(), zip64_internal::filestream, free(), zip64_internal::in_opened_file_inzip, curfile64_info::method, z_stream_s::next_out, zip64_internal::number_entry, curfile64_info::pos_in_buffered_data, curfile64_info::pos_local_header, curfile64_info::pos_zip64extrainfo, curfile64_info::raw, curfile64_info::size_centralExtra, curfile64_info::size_centralExtraFree, curfile64_info::size_centralheader, curfile64_info::stream, curfile64_info::stream_initialised, z_stream_s::total_out, curfile64_info::totalCompressedData, curfile64_info::totalUncompressedData, Z_ASCII, Z_BUFSIZE, Z_BZIP2ED, Z_DEFLATED, zip64_internal::z_filefunc, Z_FINISH, Z_STREAM_END, zip64FlushWriteBuffer(), zip64local_putValue(), zip64local_putValue_inmemory(), ZIP_BADZIPFILE, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, ZLIB_FILEFUNC_SEEK_SET, ZSEEK64, and ZTELL64.
Referenced by zipCloseFileInZipRaw().
ZEXTERN zipFile ZEXPORT zipOpen (const char * pathname, int append)
Definition at line 948 of file zip.c.
References zipOpen3().
ZEXTERN zipFile ZEXPORT zipOpen2 (const char * pathname, int append, zipcharpc * globalcomment, zlib_filefunc_def * pzlib_filefunc32_def)
Definition at line 920 of file zip.c.
References fill_zlib_filefunc64_32_def_from_filefunc32(), and zipOpen3().
ZEXTERN zipFile ZEXPORT zipOpen2_64 (const void * pathname, int append, zipcharpc * globalcomment, zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 932 of file zip.c.
References zlib_filefunc64_32_def_s::zfile_func64, zipOpen3(), zlib_filefunc64_32_def_s::zseek32_file, and zlib_filefunc64_32_def_s::ztell32_file.
ZEXTERN zipFile ZEXPORT zipOpen3 (const void * pathname, int append, zipcharpc * globalcomment, zlib_filefunc64_32_def * pzlib_filefunc64_32_def)
Definition at line 849 of file zip.c.
References zip64_internal::add_position_when_writing_offset, ALLOC, APPEND_STATUS_ADDINZIP, APPEND_STATUS_CREATE, APPEND_STATUS_CREATEAFTER, zip64_internal::begin_pos, zip64_internal::central_dir, zip64_internal::ci, zip64_internal::filestream, fill_fopen64_filefunc(), zip64_internal::globalcomment, zip64_internal::in_opened_file_inzip, init_linkedlist(), LoadCentralDirectoryRecord(), zip64_internal::number_entry, SEEK_END, curfile64_info::stream_initialised, TRYFREE, zip64_internal::z_filefunc, ZCLOSE64, zlib_filefunc64_32_def_s::zfile_func64, ZIP_OK, ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, ZLIB_FILEFUNC_MODE_WRITE, ZOPEN64, zlib_filefunc64_32_def_s::zseek32_file, ZSEEK64, zlib_filefunc64_32_def_s::ztell32_file, and ZTELL64.
Referenced by zipOpen(), zipOpen2(), zipOpen2_64(), and zipOpen64().
ZEXTERN zipFile ZEXPORT zipOpen64 (const void * pathname, int append)
Definition at line 953 of file zip.c.
References zipOpen3().
Referenced by MusicExtractManager::inputData(), and MusicExtractManager::inputSkin().
ZEXTERN int ZEXPORT zipOpenNewFileInZip (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level)
Definition at line 1350 of file zip.c.
References DEF_MEM_LEVEL, MAX_WBITS, VERSIONMADEBY, Z_DEFAULT_STRATEGY, and zipOpenNewFileInZip4_64().
Referenced by MusicExtractManager::inputData(), and MusicExtractManager::inputSkin().
ZEXTERN int ZEXPORT zipOpenNewFileInZip2 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw)
Definition at line 1311 of file zip.c.
References DEF_MEM_LEVEL, MAX_WBITS, VERSIONMADEBY, Z_DEFAULT_STRATEGY, and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipOpenNewFileInZip2_64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int zip64)
Definition at line 1324 of file zip.c.
References DEF_MEM_LEVEL, MAX_WBITS, VERSIONMADEBY, Z_DEFAULT_STRATEGY, and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipOpenNewFileInZip3 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting)
Definition at line 1281 of file zip.c.
References VERSIONMADEBY, and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipOpenNewFileInZip3_64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting, int zip64)
Definition at line 1296 of file zip.c.
References VERSIONMADEBY, and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipOpenNewFileInZip4 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase)
Definition at line 1265 of file zip.c.
References zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipOpenNewFileInZip4_64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase, int zip64)
Definition at line 1055 of file zip.c.
References zip64_internal::add_position_when_writing_offset, ALLOC, z_stream_s::avail_in, z_stream_s::avail_out, curfile64_info::buffered_data, curfile64_info::central_header, CENTRALHEADERMAGIC, zip64_internal::ci, curfile64_info::crc32, curfile64_info::crypt_header_size, z_stream_s::data_type, deflateInit2, zip_fileinfo::dosDate, curfile64_info::dosDate, curfile64_info::encrypt, zip_fileinfo::external_fa, zip64_internal::filestream, curfile64_info::flag, get_crc_table(), zip64_internal::in_opened_file_inzip, zip_fileinfo::internal_fa, curfile64_info::keys, curfile64_info::method, z_stream_s::next_out, z_stream_s::opaque, curfile64_info::pcrc_32_tab, curfile64_info::pos_in_buffered_data, curfile64_info::pos_local_header, curfile64_info::pos_zip64extrainfo, curfile64_info::raw, curfile64_info::size_centralExtra, curfile64_info::size_centralExtraFree, curfile64_info::size_centralheader, SIZECENTRALHEADER, curfile64_info::stream, curfile64_info::stream_initialised, zip_fileinfo::tmz_date, z_stream_s::total_in, z_stream_s::total_out, curfile64_info::totalCompressedData, curfile64_info::totalUncompressedData, Write_LocalFileHeader(), Z_BINARY, Z_BUFSIZE, Z_BZIP2ED, Z_DEFLATED, zip64_internal::z_filefunc, Z_OK, z_stream_s::zalloc, z_stream_s::zfree, curfile64_info::zip64, zip64local_putValue_inmemory(), zip64local_TmzDateToDosDate(), ZIP_ERRNO, ZIP_INTERNALERROR, ZIP_OK, ZIP_PARAMERROR, zipCloseFileInZip(), ZTELL64, and ZWRITE64.
Referenced by zipOpenNewFileInZip(), zipOpenNewFileInZip2(), zipOpenNewFileInZip2_64(), zipOpenNewFileInZip3(), zipOpenNewFileInZip3_64(), zipOpenNewFileInZip4(), and zipOpenNewFileInZip64().
ZEXTERN int ZEXPORT zipOpenNewFileInZip64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int zip64)
Definition at line 1337 of file zip.c.
References DEF_MEM_LEVEL, MAX_WBITS, VERSIONMADEBY, Z_DEFAULT_STRATEGY, and zipOpenNewFileInZip4_64().
ZEXTERN int ZEXPORT zipRemoveExtraInfoBlock (char * pData, int * dataLen, short sHeader)
Definition at line 1951 of file zip.c.
References ALLOC, TRYFREE, ZIP_ERRNO, ZIP_OK, and ZIP_PARAMERROR.
ZEXTERN int ZEXPORT zipWriteInFileInZip (zipFile file, const void * buf, unsigned int len)
Definition at line 1402 of file zip.c.
References z_stream_s::avail_in, z_stream_s::avail_out, curfile64_info::buffered_data, zip64_internal::ci, curfile64_info::crc32, crc32(), deflate(), zip64_internal::in_opened_file_inzip, curfile64_info::method, z_stream_s::next_in, z_stream_s::next_out, curfile64_info::pos_in_buffered_data, curfile64_info::raw, curfile64_info::stream, z_stream_s::total_in, z_stream_s::total_out, Z_BUFSIZE, Z_BZIP2ED, Z_DEFLATED, Z_NO_FLUSH, zip64FlushWriteBuffer(), ZIP_ERRNO, ZIP_OK, and ZIP_PARAMERROR.
Referenced by MusicExtractManager::inputData(), and MusicExtractManager::inputSkin().
Variable Documentation
const char zip_copyright[] =" zip 1.01 Copyright 1998-2004 Gilles Vollant - http://www.winimage.com/zLibDll"
Definition at line 98 of file zip.c.