TTKMusicPlayer: MusicDJRadioCategoryRequest Class Reference
MusicDJRadioCategoryRequest Class Reference
The class of the music dj radio category request.
#include <musicdjradiocategoryrequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDJRadioCategoryRequest (QObject *parent=nullptr)
void startRequest ()
Public Member Functions inherited from MusicAbstractDJRadioRequest
MusicAbstractDJRadioRequest (QObject *parent=nullptr)
const MusicResultDataItemList & searchedItems () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicAbstractDJRadioRequest
void createProgramItem (const MusicResultDataItem &item)
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Member Functions inherited from MusicWYQueryInterface
QByteArray makeTokenRequest (QNetworkRequest *request, const QString &query, const QString &type) const
void parseFromSongProperty (MusicObject::MusicSongInformation *info, int bitrate) const
void parseFromSongProperty (MusicObject::MusicSongInformation *info, const QVariantMap &key, MusicObject::QueryQuality quality, bool all) const
void parseFromSongPropertyNew (MusicObject::MusicSongInformation *info, int bitrate) const
void parseFromSongPropertyNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, MusicObject::QueryQuality quality, bool all) const
Protected Attributes inherited from MusicAbstractDJRadioRequest
MusicResultDataItemList m_items
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the music dj radio category request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdjradiocategoryrequest.h.
Constructor & Destructor Documentation
MusicDJRadioCategoryRequest::MusicDJRadioCategoryRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdjradiocategoryrequest.cpp.
Member Function Documentation
void MusicDJRadioCategoryRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 23 of file musicdjradiocategoryrequest.cpp.
References MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractNetwork::downLoadFinished(), MusicResultDataItem::m_coverUrl, MusicResultDataItem::m_id, MusicAbstractDJRadioRequest::m_items, MusicResultDataItem::m_name, MusicAbstractNetwork::m_reply, QJson::Parser::parse(), and TTK_NETWORK_QUERY_CHECK.
Referenced by startRequest().
void MusicDJRadioCategoryRequest::startRequest ()
Start to download data from net.
Definition at line 9 of file musicdjradiocategoryrequest.cpp.
References MusicAbstractNetwork::deleteAll(), DJ_CATEGORY_URL, downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicWYQueryInterface::makeTokenRequest(), MusicUtils::Algorithm::mdII(), QtNetworkErrorConnect, and MusicAbstractNetwork::replyError().
Referenced by MusicWebDJRadioCategoryWidget::initialize().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicdjradiocategoryrequest.h
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicdjradiocategoryrequest.cpp