TTKMusicplayer: MusicCloudDownloadTableWidget Class Reference
MusicCloudDownloadTableWidget Class Reference
The class of the cloud shared song download table widget.
#include <musiccloudtablewidget.h>
Public Slots
virtual void listCellClicked (int row, int column) override
void listCellDoubleClicked (int row, int column)
virtual void setDeleteItemAt () override
void downloadProgressChanged (float percent, const QString &total, qint64 time)
void createDownloadItem (const QString &name, qint64 time)
Public Slots inherited from MusicSongsListAbstractTableWidget
void musicPlayClicked ()
virtual void setDeleteItemAt ()
void setDeleteItemAll ()
void musicOpenFileDir ()
void musicFileInformation ()
void musicSongMovieFound ()
void musicAlbumFoundWidget ()
void musicSimilarFoundWidget ()
void musicSongSharedWidget ()
void musicSongKMicroWidget ()
void musicSongTransferWidget ()
void musicSongDownload ()
void musicSongMovieFoundPy ()
void musicSimilarFoundWidgetPy ()
void musicSongSharedWidgetPy ()
void musicSongKMicroWidgetPy ()
Public Slots inherited from MusicSlowMovingTableWidget
void timeToAnimation ()
void valueChanged (int value)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void addSongToPlay (const QStringList &names)
Signals inherited from MusicSongsListAbstractTableWidget
void isCurrentIndexs (bool &state)
Public Member Functions
MusicCloudDownloadTableWidget (QWidget *parent=0)
virtual ~MusicCloudDownloadTableWidget ()
Public Member Functions inherited from MusicSongsListAbstractTableWidget
MusicSongsListAbstractTableWidget (QWidget *parent=0)
virtual ~MusicSongsListAbstractTableWidget ()
virtual void setSongsFileName (MusicSongs *songs)
virtual void updateSongsFileName (const MusicSongs &songs)
virtual void selectRow (int index)
int allRowsHeight () const
void setParentToolIndex (int index)
void setPlayRowIndex (int index)
int getPlayRowIndex () const
Public Member Functions inherited from MusicSlowMovingTableWidget
MusicSlowMovingTableWidget (QWidget *parent=0)
virtual ~MusicSlowMovingTableWidget ()
void setMovedScrollBar (QScrollBar *bar)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicSongsListAbstractTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicSlowMovingTableWidget
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Protected Member Functions
void musicSongsFileName ()
virtual void contextMenuEvent (QContextMenuEvent *event) override
void createItem (int index, const MusicDownloadRecord &record, qint64 time)
Protected Member Functions inherited from MusicSongsListAbstractTableWidget
void createMoreMenu (QMenu *menu)
QString getCurrentSongPath () const
QString getSongPath (int index) const
QString getCurrentSongName () const
QString getSongName (int index) const
Protected Member Functions inherited from MusicSlowMovingTableWidget
virtual void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
MusicProgressBarDelegate * m_progressBarDelegate
MusicDownloadRecords m_musicRecords
Protected Attributes inherited from MusicSongsListAbstractTableWidget
int m_playRowIndex
int m_parentToolIndex
MusicSongs * m_musicSongs
bool m_hasParentToolIndex
Protected Attributes inherited from MusicSlowMovingTableWidget
bool m_isFirstInit
int m_previousValue
int m_deltaValue
QScrollBar * m_scrollBar
QTimer * m_animationTimer
QPropertyAnimation * m_slowAnimation
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the cloud shared song download table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 61 of file musiccloudtablewidget.h.
Constructor & Destructor Documentation
MusicCloudDownloadTableWidget::MusicCloudDownloadTableWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 47 of file musiccloudtablewidget.cpp.
References MusicSongsSummariziedWidget::getClassName(), getClassName(), listCellDoubleClicked(), M_CONNECTION_PTR, m_progressBarDelegate, MusicUIObject::MScrollBarStyle05, and musicSongsFileName().
MusicCloudDownloadTableWidget::~MusicCloudDownloadTableWidget () virtual
Definition at line 71 of file musiccloudtablewidget.cpp.
References MusicAbstractTableWidget::clear(), MusicDownloadRecordConfigManager::Cloud, getClassName(), M_CONNECTION_PTR, m_musicRecords, MusicSongsListAbstractTableWidget::m_musicSongs, m_progressBarDelegate, and MusicDownloadRecordConfigManager::writeDownloadConfig().
Member Function Documentation
void MusicCloudDownloadTableWidget::addSongToPlay (const QStringList & names) signal
Add current selected song to play lists.
Referenced by listCellDoubleClicked().
void MusicCloudDownloadTableWidget::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 183 of file musiccloudtablewidget.cpp.
References MusicSongsListAbstractTableWidget::createMoreMenu(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicUIObject::MMenuStyle02, MusicSongsListAbstractTableWidget::musicAlbumFoundWidget(), MusicSongsListAbstractTableWidget::musicFileInformation(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicPlayClicked(), MusicSongsListAbstractTableWidget::musicSongDownload(), MusicSongsListAbstractTableWidget::setDeleteItemAll(), and setDeleteItemAt().
void MusicCloudDownloadTableWidget::createDownloadItem (const QString & name, qint64 time) slot
Create download item from download name and total time.
Definition at line 151 of file musiccloudtablewidget.cpp.
References createItem(), m_musicRecords, MusicDownloadRecord::m_name, MusicDownloadRecord::m_path, MusicDownloadRecord::m_size, and MusicUtils::Core::musicPrefix().
void MusicCloudDownloadTableWidget::createItem (int index, const MusicDownloadRecord & record, qint64 time) protected
Create item by index and name and size and time.
Definition at line 208 of file musiccloudtablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSongsListAbstractTableWidget::m_musicSongs, MusicDownloadRecord::m_name, MusicDownloadRecord::m_path, MusicDownloadRecord::m_size, MusicUIObject::MColorStyle12_S, MUSIC_PROCS_ROLE, and MUSIC_TIMES_ROLE.
Referenced by createDownloadItem(), and musicSongsFileName().
void MusicCloudDownloadTableWidget::downloadProgressChanged (float percent, const QString & total, qint64 time) slot
Update download percent\ total time and current time progress.
Definition at line 132 of file musiccloudtablewidget.cpp.
References m_musicRecords, MUSIC_PROCS_ROLE, and MUSIC_TIMES_ROLE.
QString MusicCloudDownloadTableWidget::getClassName () static
Get class object name.
Definition at line 82 of file musiccloudtablewidget.cpp.
Referenced by MusicConnectionPool::connectMusicDownload(), MusicCloudDownloadTableWidget(), MusicConnectionPool::poolConnect(), and ~MusicCloudDownloadTableWidget().
void MusicCloudDownloadTableWidget::listCellClicked (int row, int column) override virtual slot
Table widget list cell click.
Definition at line 87 of file musiccloudtablewidget.cpp.
void MusicCloudDownloadTableWidget::listCellDoubleClicked (int row, int column) slot
List cell double clicked.
Definition at line 93 of file musiccloudtablewidget.cpp.
References addSongToPlay(), and m_musicRecords.
Referenced by MusicCloudDownloadTableWidget().
void MusicCloudDownloadTableWidget::musicSongsFileName () protected
Read all config from file and insert items.
Definition at line 166 of file musiccloudtablewidget.cpp.
References MusicDownloadRecordConfigManager::Cloud, createItem(), DEFAULT_INDEX_LEVEL1, m_musicRecords, MusicSongsListAbstractTableWidget::m_musicSongs, MusicDownloadRecordConfigManager::readDownloadConfig(), and MusicDownloadRecordConfigManager::readDownloadXMLConfig().
Referenced by MusicCloudDownloadTableWidget().
void MusicCloudDownloadTableWidget::setDeleteItemAt () override virtual slot
Delete item from list at current row.
Definition at line 106 of file musiccloudtablewidget.cpp.
References MusicMessageBox::exec(), m_musicRecords, MusicSongsListAbstractTableWidget::m_musicSongs, and MusicMessageBox::setText().
Referenced by contextMenuEvent().
Member Data Documentation
MusicDownloadRecords MusicCloudDownloadTableWidget::m_musicRecords protected
Definition at line 120 of file musiccloudtablewidget.h.
Referenced by createDownloadItem(), downloadProgressChanged(), listCellDoubleClicked(), musicSongsFileName(), setDeleteItemAt(), and ~MusicCloudDownloadTableWidget().
MusicProgressBarDelegate* MusicCloudDownloadTableWidget::m_progressBarDelegate protected
Definition at line 119 of file musiccloudtablewidget.h.
Referenced by MusicCloudDownloadTableWidget(), and ~MusicCloudDownloadTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudtablewidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudtablewidget.cpp