TTKMusicPlayer: MusicServerPluginTableWidget Class Reference
MusicServerPluginTableWidget Class Reference
The class of the server plugin manager table widget.
#include <musicpluginwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) override
void checkedItemsStatus (bool checked)
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicServerPluginTableWidget (QWidget *parent=nullptr)
void save () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedItemRows () const
TTKIntList uncheckedItemRows () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
TTKIntList selectedRows () const
Private Member Functions
void addCellItems ()
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the server plugin manager table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 67 of file musicpluginwidget.h.
Constructor & Destructor Documentation
MusicServerPluginTableWidget::MusicServerPluginTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 339 of file musicpluginwidget.cpp.
References addCellItems(), and TTK::UI::ScrollBarStyle01.
Member Function Documentation
void MusicServerPluginTableWidget::addCellItems () private
Create cell items by input data.
Definition at line 434 of file musicpluginwidget.cpp.
References APPCACHE_DIR_FULL, QJsonParseError::error, QJsonDocument::fromJson(), G_SETTING_PTR, name, QJsonParseError::NoError, qAsConst, QtItemSetTextAlignment, QUERY_PLUGINS_URL, QJsonDocument::toVariant(), TTK_CHECKED_ROLE, TTK_ERROR_STREAM, TTK_INFO_STREAM, TTK_SPACE, and MusicSettingManager::UserPermission.
Referenced by MusicServerPluginTableWidget().
void MusicServerPluginTableWidget::checkedItemsStatus (bool checked) slot
Checked items status.
Definition at line 424 of file musicpluginwidget.cpp.
References MusicFillItemTableWidget::checkedItemsStatus().
void MusicServerPluginTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 411 of file musicpluginwidget.cpp.
References TTK_CHECKED_ROLE, and TTKStaticCast.
void MusicServerPluginTableWidget::save () const
Save data items.
Definition at line 358 of file musicpluginwidget.cpp.
References APPCACHE_DIR_FULL, QJsonParseError::error, QJsonDocument::fromJson(), QJsonDocument::fromVariant(), QJsonDocument::Indented, QJsonParseError::NoError, QUERY_PLUGINS_URL, QJsonDocument::toJson(), QJsonDocument::toVariant(), TTK_CHECKED_ROLE, TTK_ERROR_STREAM, and TTK_INFO_STREAM.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicpluginwidget.cpp