TTKMusicplayer: MusicAudioRecorderModule Class Reference
MusicAudioRecorderModule Class Reference
The class of the audio recorder core.
#include <musicaudiorecordermodule.h>
Classes
struct HEADER
The class of the audio file tag header.
Public Types
typedef struct TTK_MODULE_EXPORT MusicAudioRecorderModule::HEADER HEADER
The class of the audio file tag header.
Public Slots
void onRecordStart ()
void onRecordStop ()
void onRecordPlay ()
void onStateChange (QAudio::State state)
Public Member Functions
MusicAudioRecorderModule (QObject *parent=nullptr)
~MusicAudioRecorderModule ()
int addWavHeader (const char *filename)
void setVolume (int volume)
int volume () const
void setFileName (const QString &name)
QString getFileName () const
bool error () const
Protected Attributes
int m_inputVolume
QAudioFormat m_mFormatFile
QFile * m_mpOutputFile
QAudioInput * m_mpAudioInputFile
QAudioOutput * m_mpAudioOutputFile
Detailed Description
The class of the audio recorder core.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicaudiorecordermodule.h.
Member Typedef Documentation
typedef struct TTK_MODULE_EXPORT MusicAudioRecorderModule::HEADER MusicAudioRecorderModule::HEADER
The class of the audio file tag header.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Constructor & Destructor Documentation
MusicAudioRecorderModule::MusicAudioRecorderModule (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicaudiorecordermodule.cpp.
References m_inputVolume, m_mFormatFile, m_mpAudioInputFile, m_mpAudioOutputFile, m_mpOutputFile, MUSIC_RECORD_FILE, TTK_LOGGER_INFO, and TTK_LOGGER_WARN.
MusicAudioRecorderModule::~MusicAudioRecorderModule ()
Definition at line 47 of file musicaudiorecordermodule.cpp.
References m_mpAudioInputFile, m_mpAudioOutputFile, m_mpOutputFile, MUSIC_RECORD_FILE, MUSIC_RECORD_IN_FILE, and MUSIC_RECORD_OUT_FILE.
Member Function Documentation
int MusicAudioRecorderModule::addWavHeader (const char * filename)
Add the header of wav.
Definition at line 58 of file musicaudiorecordermodule.cpp.
References MusicAudioRecorderModule::HEADER::DATANAME, MusicAudioRecorderModule::HEADER::FMTNAME, m_mpOutputFile, MusicAudioRecorderModule::HEADER::nAudioFormat, MusicAudioRecorderModule::HEADER::nBitsPerSample, MusicAudioRecorderModule::HEADER::nBytesPerSample, MusicAudioRecorderModule::HEADER::nBytesPerSecond, MusicAudioRecorderModule::HEADER::nChannleNumber, MusicAudioRecorderModule::HEADER::nDataLength, MusicAudioRecorderModule::HEADER::nFMTLength, MusicAudioRecorderModule::HEADER::nRIFFLength, MusicAudioRecorderModule::HEADER::nSampleRate, OPEN_FILE_ERROR, qPrintable, REWRITE_FILE_ERROR, MusicAudioRecorderModule::HEADER::RIFFNAME, SAVE_FILE_ERROR, SEEK_SET, MusicAudioRecorderModule::HEADER::WAVNAME, and WRITE_FILE_ERROR.
Referenced by MusicIdentifySongsWidget::detectedTimeOut(), and MusicSoundKMicroWidget::playFinished().
bool MusicAudioRecorderModule::error () const
Current input device error or not.
Definition at line 167 of file musicaudiorecordermodule.cpp.
References m_mpAudioInputFile.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), and MusicSoundKMicroWidget::recordStateChanged().
QString MusicAudioRecorderModule::getFileName () const
Get output file name.
Definition at line 162 of file musicaudiorecordermodule.cpp.
References m_mpOutputFile.
void MusicAudioRecorderModule::onRecordPlay () slot
Recorder play play.
Definition at line 196 of file musicaudiorecordermodule.cpp.
References m_mFormatFile, m_mpAudioOutputFile, m_mpOutputFile, onStateChange(), and TTK_LOGGER_ERROR.
void MusicAudioRecorderModule::onRecordStart () slot
Recorder play start.
Definition at line 177 of file musicaudiorecordermodule.cpp.
References m_inputVolume, m_mFormatFile, m_mpAudioInputFile, m_mpOutputFile, and TTK_LOGGER_ERROR.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicAudioRecorderModule::onRecordStop () slot
Recorder play stop.
Definition at line 211 of file musicaudiorecordermodule.cpp.
References m_mpAudioInputFile, m_mpAudioOutputFile, and m_mpOutputFile.
Referenced by MusicIdentifySongsWidget::detectedButtonClicked(), onStateChange(), and MusicSoundKMicroWidget::recordStateChanged().
void MusicAudioRecorderModule::onStateChange (QAudio::State state) slot
Recorder play state changed.
Definition at line 230 of file musicaudiorecordermodule.cpp.
References onRecordStop().
Referenced by onRecordPlay().
void MusicAudioRecorderModule::setFileName (const QString & name)
Set output file name.
Definition at line 157 of file musicaudiorecordermodule.cpp.
References m_mpOutputFile.
void MusicAudioRecorderModule::setVolume (int volume)
Set volume by value.
Definition at line 141 of file musicaudiorecordermodule.cpp.
References m_inputVolume, m_mpAudioInputFile, and volume().
Referenced by MusicSoundKMicroSettingPopWidget::volumeChanged().
int MusicAudioRecorderModule::volume () const
Get volume by value.
Definition at line 152 of file musicaudiorecordermodule.cpp.
References m_inputVolume.
Referenced by setVolume().
Member Data Documentation
int MusicAudioRecorderModule::m_inputVolume protected
Definition at line 108 of file musicaudiorecordermodule.h.
Referenced by MusicAudioRecorderModule(), onRecordStart(), setVolume(), and volume().
QAudioFormat MusicAudioRecorderModule::m_mFormatFile protected
Definition at line 109 of file musicaudiorecordermodule.h.
Referenced by MusicAudioRecorderModule(), onRecordPlay(), and onRecordStart().
QAudioInput* MusicAudioRecorderModule::m_mpAudioInputFile protected
Definition at line 111 of file musicaudiorecordermodule.h.
Referenced by error(), MusicAudioRecorderModule(), onRecordStart(), onRecordStop(), setVolume(), and ~MusicAudioRecorderModule().
QAudioOutput* MusicAudioRecorderModule::m_mpAudioOutputFile protected
Definition at line 112 of file musicaudiorecordermodule.h.
Referenced by MusicAudioRecorderModule(), onRecordPlay(), onRecordStop(), and ~MusicAudioRecorderModule().
QFile* MusicAudioRecorderModule::m_mpOutputFile protected
Definition at line 110 of file musicaudiorecordermodule.h.
Referenced by addWavHeader(), getFileName(), MusicAudioRecorderModule(), onRecordPlay(), onRecordStart(), onRecordStop(), setFileName(), and ~MusicAudioRecorderModule().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicaudiorecordermodule.h
TTKModule/TTKCore/musicToolsSetsKits/musicaudiorecordermodule.cpp