TTKMusicPlayer: TTKSemaphoreLoop Class Reference
TTKSemaphoreLoop Class Reference
The class of the semaphore event loop.
#include <ttksemaphoreloop.h>
Public Slots
void quit ()
void exit ()
Public Member Functions
TTKSemaphoreLoop (QObject *parent=nullptr)
~TTKSemaphoreLoop ()
int exec (ProcessEventsFlags flags=AllEvents)
Private Attributes
QTimer m_timer
Detailed Description
The class of the semaphore event loop.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttksemaphoreloop.h.
Constructor & Destructor Documentation
TTKSemaphoreLoop::TTKSemaphoreLoop (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 3 of file ttksemaphoreloop.cpp.
References m_timer, quit(), and TTK_DN_S2MS.
TTKSemaphoreLoop::~TTKSemaphoreLoop ()
Object destructor.
Definition at line 10 of file ttksemaphoreloop.cpp.
References quit().
Member Function Documentation
int TTKSemaphoreLoop::exec (ProcessEventsFlags flags = AllEvents)
Event loop start.
Definition at line 27 of file ttksemaphoreloop.cpp.
References m_timer.
Referenced by MusicReplayGainWidget::addFileButtonClicked(), MusicReplayGainWidget::addFilesButtonClicked(), MusicReplayGainWidget::applyButtonClicked(), MusicSongSharingWidget::confirmButtonClicked(), MusicIdentifySongWidget::createDetectedSuccessedWidget(), MusicIdentifySongWidget::detectedTimeOut(), MusicLrcDownloadBatchWidget::downloadButtonClicked(), MusicDownloadMetaDataRequest::downLoadFinished(), TTK::fetchFileSizeByUrl(), MusicCloudManagerTableWidget::queryCloudKey(), MusicIdentifySongRequest::queryIdentifyKey(), MusicDeviceInfoModule::removableDrive(), MusicCommentsWidget::setCurrentSongName(), MusicWYTranslationRequest::startToRequest(), MusicKGDownloadBackgroundRequest::startToRequest(), MusicKGSongCommentsRequest::startToSearch(), MusicKWSongCommentsRequest::startToSearch(), MusicWYSongCommentsRequest::startToSearch(), TTK::syncNetworkQueryForGet(), TTK::syncNetworkQueryForPatch(), TTK::syncNetworkQueryForPost(), and TTK::syncNetworkQueryForPut().
void TTKSemaphoreLoop::exit () slot
Event loop exit.
Definition at line 21 of file ttksemaphoreloop.cpp.
References m_timer.
void TTKSemaphoreLoop::quit () slot
Event loop quit.
Definition at line 15 of file ttksemaphoreloop.cpp.
References m_timer.
Referenced by TTKSemaphoreLoop(), and ~TTKSemaphoreLoop().
Member Data Documentation
QTimer TTKSemaphoreLoop::m_timer private
Definition at line 59 of file ttksemaphoreloop.h.
Referenced by exec(), exit(), quit(), and TTKSemaphoreLoop().
The documentation for this class was generated from the following files:
TTKCommon/TTKLibrary/ttksemaphoreloop.h
TTKCommon/TTKLibrary/ttksemaphoreloop.cpp