TTKMusicplayer: MusicDownLoadQueryWYRecommendThread Class Reference
MusicDownLoadQueryWYRecommendThread Class Reference
The class to wangyi query recommend download data from net.
#include <musicdownloadquerywyrecommendthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadQueryWYRecommendThread (QObject *parent=0)
QJson import.
virtual void startToSearch (const QString &id) override
Public Member Functions inherited from MusicDownLoadQueryRecommendThread
MusicDownLoadQueryRecommendThread (QObject *parent=0)
virtual void startToSearch (QueryType type, const QString &id) override
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
virtual void startToSingleSearch (const QString &text)
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryRecommendThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to wangyi query recommend download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadquerywyrecommendthread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryWYRecommendThread::MusicDownLoadQueryWYRecommendThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 6 of file musicdownloadquerywyrecommendthread.cpp.
References MusicDownLoadQueryThreadAbstract::m_queryServer.
Member Function Documentation
void MusicDownLoadQueryWYRecommendThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 42 of file musicdownloadquerywyrecommendthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::Init, MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicObject::MusicSongInformation::m_lrcUrl, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_queryAllRecords, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchQuality, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicDownLoadWYInterface::readFromMusicSongAttribute(), and WY_SONG_LRC_URL.
Referenced by startToSearch().
QString MusicDownLoadQueryWYRecommendThread::getClassName () static
Get class object name.
Definition at line 12 of file musicdownloadquerywyrecommendthread.cpp.
Referenced by downLoadFinished(), and startToSearch().
void MusicDownLoadQueryWYRecommendThread::startToSearch (const QString & id) override virtual
Start to Search data from name and type.
Implements MusicDownLoadQueryRecommendThread.
Definition at line 17 of file musicdownloadquerywyrecommendthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), and WY_RCM_N_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicdownloadquerywyrecommendthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicdownloadquerywyrecommendthread.cpp