TTKMusicplayer: GaussianBlur Class Reference
GaussianBlur Class Reference
The namespace of the Gaussian Blur.
#include <gaussianblur.h>
Public Member Functions
void gaussBlur1 (int *pix, int w, int h, int radius)
void gaussBlur2 (int *pix, int w, int h, int radius)
Private Member Functions
void boxBlurH (int *srcPix, int *destPix, int w, int h, int radius)
void boxBlurV (int *srcPix, int *destPix, int w, int h, int radius)
void boxBlur (int *srcPix, int *destPix, int w, int h, int r)
void boxesForGauss (float sigma, int *size, int n)
Detailed Description
The namespace of the Gaussian Blur.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file gaussianblur.h.
Member Function Documentation
void GaussianBlur::boxBlur (int * srcPix, int * destPix, int w, int h, int r) private
Definition at line 293 of file gaussianblur.cpp.
References boxBlurH(), and boxBlurV().
Referenced by gaussBlur2().
void GaussianBlur::boxBlurH (int * srcPix, int * destPix, int w, int h, int radius) private
Definition at line 133 of file gaussianblur.cpp.
References int().
Referenced by boxBlur().
void GaussianBlur::boxBlurV (int * srcPix, int * destPix, int w, int h, int radius) private
Definition at line 214 of file gaussianblur.cpp.
References int().
Referenced by boxBlur().
void GaussianBlur::boxesForGauss (float sigma, int * size, int n) private
Definition at line 304 of file gaussianblur.cpp.
Referenced by gaussBlur2().
void GaussianBlur::gaussBlur1 (int * pix, int w, int h, int radius)
Definition at line 8 of file gaussianblur.cpp.
References int(), and PI.
Referenced by QImageWrap::GaussFilter().
void GaussianBlur::gaussBlur2 (int * pix, int w, int h, int radius)
Definition at line 114 of file gaussianblur.cpp.
References boxBlur(), and boxesForGauss().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qimage/gaussianblur.h
TTKThirdParty/TTKExtras/qimage/gaussianblur.cpp