TTKMusicPlayer: MusicRemoteWidgetForComplexStyle Class Reference
MusicRemoteWidgetForComplexStyle Class Reference
The class of the desktop complex remote widget.
#include <musicremotewidgetforcomplexstyle.h>
Public Member Functions
MusicRemoteWidgetForComplexStyle (QWidget *parent=nullptr)
~MusicRemoteWidgetForComplexStyle ()
virtual void setLabelText (const QString &value) overridefinal
Public Member Functions inherited from MusicRemoteWidget
MusicRemoteWidget (QWidget *parent=nullptr)
~MusicRemoteWidget ()
void setCurrentPlayState (bool state) const
void setVolumeValue (int index)
int mapRemoteTypeIndex ()
Public Member Functions inherited from TTKAbstractMoveWidget
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockOption (bool block)
Private Member Functions
bool showArtPicture (const QString &name)
Private Attributes
QLabel * m_iconLabel
QLabel * m_songName
QLabel * m_songArtist
Additional Inherited Members
Public Types inherited from MusicRemoteWidget
enum Module {
Null = 0, Square, Rectangle, SimpleStyle,
ComplexStyle, Ripple
}
Public Slots inherited from MusicRemoteWidget
void volumeSliderChanged (int value)
void show ()
bool close ()
Signals inherited from MusicRemoteWidget
void showMainWindow ()
void playStateChanged ()
void playPreviousChanged ()
void playNextChanged ()
void volumeChanged (int value)
void settingChanged ()
void remoteTypeChanged (QAction *type)
Protected Member Functions inherited from MusicRemoteWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
void adjustPosition (QWidget *w)
Protected Member Functions inherited from TTKAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Attributes inherited from MusicRemoteWidget
QPushButton * m_showMainWindowButton
QPushButton * m_preSongButton
QPushButton * m_nextSongButton
QPushButton * m_playButton
QPushButton * m_settingButton
QWidget * m_mainWidget
QWidget * m_volumeWidget
QToolButton * m_volumeButton
TTKClickedSlider * m_volumeSlider
Protected Attributes inherited from TTKAbstractMoveWidget
QPoint m_mousePressedAt
bool m_blockOption
bool m_shadowOption
bool m_mouseLeftPressed
Detailed Description
The class of the desktop complex remote widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicremotewidgetforcomplexstyle.h.
Constructor & Destructor Documentation
MusicRemoteWidgetForComplexStyle::MusicRemoteWidgetForComplexStyle (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file musicremotewidgetforcomplexstyle.cpp.
References MusicRemoteWidget::adjustPosition(), m_iconLabel, MusicRemoteWidget::m_mainWidget, MusicRemoteWidget::m_nextSongButton, MusicRemoteWidget::m_playButton, MusicRemoteWidget::m_preSongButton, MusicRemoteWidget::m_settingButton, MusicRemoteWidget::m_showMainWindowButton, m_songArtist, m_songName, MusicRemoteWidget::m_volumeWidget, and TTK::UI::WidgetStyle01.
MusicRemoteWidgetForComplexStyle::~MusicRemoteWidgetForComplexStyle ()
Object destructor.
Definition at line 50 of file musicremotewidgetforcomplexstyle.cpp.
References m_iconLabel, m_songArtist, and m_songName.
Member Function Documentation
void MusicRemoteWidgetForComplexStyle::setLabelText (const QString & value) final override virtual
Set current song text.
Reimplemented from MusicRemoteWidget.
Definition at line 57 of file musicremotewidgetforcomplexstyle.cpp.
References TTK::generateSongArtist(), TTK::generateSongTitle(), m_iconLabel, m_songArtist, m_songName, showArtPicture(), and TTK::String::split().
bool MusicRemoteWidgetForComplexStyle::showArtPicture (const QString & name) private
Show artist small picture, if no exsit there is default pic.
Definition at line 70 of file musicremotewidgetforcomplexstyle.cpp.
References ART_DIR_FULL, m_iconLabel, and SKN_FILE.
Referenced by setLabelText().
Member Data Documentation
QLabel* MusicRemoteWidgetForComplexStyle::m_iconLabel private
Definition at line 52 of file musicremotewidgetforcomplexstyle.h.
Referenced by MusicRemoteWidgetForComplexStyle(), setLabelText(), showArtPicture(), and ~MusicRemoteWidgetForComplexStyle().
QLabel * MusicRemoteWidgetForComplexStyle::m_songArtist private
Definition at line 52 of file musicremotewidgetforcomplexstyle.h.
Referenced by MusicRemoteWidgetForComplexStyle(), setLabelText(), and ~MusicRemoteWidgetForComplexStyle().
QLabel * MusicRemoteWidgetForComplexStyle::m_songName private
Definition at line 52 of file musicremotewidgetforcomplexstyle.h.
Referenced by MusicRemoteWidgetForComplexStyle(), setLabelText(), and ~MusicRemoteWidgetForComplexStyle().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforcomplexstyle.h
TTKModule/TTKWidget/musicRemoteKits/musicremotewidgetforcomplexstyle.cpp