TTKMusicplayer: MusicLrcPosterItemWidget Class Reference
MusicLrcPosterItemWidget Class Reference
The class of the lrc art poster maker item widget.
#include <musiclrcposterwidget.h>
Public Types
enum Type {
Type_01, Type_02, Type_03, Type_04,
Type_05, Type_06, Type_07, Type_08,
Type_09, Type_10, Type_11, Type_12,
Type_13, Type_14, Type_15, Type_16,
Type_17
}
Public Slots
void textChanged (const QStringList &data)
void currentTypeChanged (int type)
Public Member Functions
MusicLrcPosterItemWidget (QWidget *parent=nullptr)
bool hasScroll () const
void setImagePath (const QString &path)
void setCurrentSongName (const QString &name)
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
void drawTheme1 (QPainter *painter)
void drawTheme2 (QPainter *painter)
void drawTheme3 (QPainter *painter)
void drawTheme4 (QPainter *painter)
void drawTheme5 (QPainter *painter)
void drawTheme6 (QPainter *painter)
void drawTheme7 (QPainter *painter)
void drawTheme8 (QPainter *painter)
void drawTheme9 (QPainter *painter)
void drawTheme10 (QPainter *painter)
void drawTheme11 (QPainter *painter)
void drawTheme12 (QPainter *painter)
void drawTheme13 (QPainter *painter)
void drawTheme14 (QPainter *painter)
void drawTheme15 (QPainter *painter)
void drawTheme16 (QPainter *painter)
void drawTheme17 (QPainter *painter)
Protected Attributes
Type m_type
QStringList m_data
QPixmap m_pixmap
QString m_title
Detailed Description
The class of the lrc art poster maker item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musiclrcposterwidget.h.
Member Enumeration Documentation
enum MusicLrcPosterItemWidget::Type
Enumerator
Type_01
thmeme 1
Type_02
thmeme 2
Type_03
thmeme 3
Type_04
thmeme 4
Type_05
thmeme 5
Type_06
thmeme 6
Type_07
thmeme 7
Type_08
thmeme 8
Type_09
thmeme 9
Type_10
thmeme 10
Type_11
thmeme 11
Type_12
thmeme 12
Type_13
thmeme 13
Type_14
thmeme 14
Type_15
thmeme 15
Type_16
thmeme 16
Type_17
thmeme 17
Definition at line 38 of file musiclrcposterwidget.h.
Constructor & Destructor Documentation
MusicLrcPosterItemWidget::MusicLrcPosterItemWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 21 of file musiclrcposterwidget.cpp.
References G_BACKGROUND_PTR, MusicBackgroundImage::m_pix, m_pixmap, m_type, MusicExtractWrapper::outputSkin(), and Type_01.
Member Function Documentation
void MusicLrcPosterItemWidget::currentTypeChanged (int type) slot
Theme type changed.
Definition at line 57 of file musiclrcposterwidget.cpp.
References ITEM_HEIGHT, m_type, and TTKStatic_cast.
void MusicLrcPosterItemWidget::drawTheme1 (QPainter * painter) protected
Draw theme.
Definition at line 94 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme10 (QPainter * painter) protected
Draw theme.
Definition at line 461 of file musiclrcposterwidget.cpp.
References MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), QImageWrapper::SharpeImage::input(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, and QImageWrapper::GaussBlur::render().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme11 (QPainter * painter) protected
Draw theme.
Definition at line 497 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), hasScroll(), ITEM_BORDER, ITEM_HEIGHT, ITEM_SCROLL_WIDTH, ITEM_WIDTH, m_data, m_title, MusicUtils::String::songName(), and TTKStatic_cast.
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme12 (QPainter * painter) protected
Draw theme.
Definition at line 547 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), hasScroll(), ITEM_BORDER, ITEM_HEIGHT, ITEM_SCROLL_WIDTH, ITEM_WIDTH, m_data, m_title, MusicUtils::String::songName(), and TTKStatic_cast.
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme13 (QPainter * painter) protected
Draw theme.
Definition at line 597 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), hasScroll(), ITEM_BORDER, ITEM_HEIGHT, ITEM_SCROLL_WIDTH, ITEM_WIDTH, m_data, m_title, MusicUtils::String::songName(), and TTKStatic_cast.
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme14 (QPainter * painter) protected
Draw theme.
Definition at line 647 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), hasScroll(), ITEM_BORDER, ITEM_HEIGHT, ITEM_SCROLL_WIDTH, ITEM_WIDTH, m_data, m_title, MusicUtils::String::songName(), and TTKStatic_cast.
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme15 (QPainter * painter) protected
Draw theme.
Definition at line 697 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme16 (QPainter * painter) protected
Draw theme.
Definition at line 731 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), MusicUtils::String::isChinese(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme17 (QPainter * painter) protected
Draw theme.
Definition at line 782 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_title, MA_90, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme2 (QPainter * painter) protected
Draw theme.
Definition at line 128 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_title, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme3 (QPainter * painter) protected
Draw theme.
Definition at line 167 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, MA_90, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme4 (QPainter * painter) protected
Draw theme.
Definition at line 203 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, MA_90, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme5 (QPainter * painter) protected
Draw theme.
Definition at line 247 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme6 (QPainter * painter) protected
Draw theme.
Definition at line 276 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_pixmap, m_title, MA_90, MusicUtils::Image::pixmapToRound(), and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme7 (QPainter * painter) protected
Draw theme.
Definition at line 315 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_title, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme8 (QPainter * painter) protected
Draw theme.
Definition at line 347 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_title, MA_90, and MusicUtils::String::songName().
Referenced by paintEvent().
void MusicLrcPosterItemWidget::drawTheme9 (QPainter * painter) protected
Draw theme.
Definition at line 404 of file musiclrcposterwidget.cpp.
References MusicUtils::String::artistName(), MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), ITEM_BORDER, ITEM_HEIGHT, ITEM_WIDTH, m_data, m_title, MA_90, and MusicUtils::String::songName().
Referenced by paintEvent().
bool MusicLrcPosterItemWidget::hasScroll () const
Check widget has scroll or not.
Definition at line 35 of file musiclrcposterwidget.cpp.
References ITEM_HEIGHT.
Referenced by drawTheme11(), drawTheme12(), drawTheme13(), drawTheme14(), and MusicLrcPosterWidget::saveButtonClicked().
void MusicLrcPosterItemWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 65 of file musiclrcposterwidget.cpp.
References drawTheme1(), drawTheme10(), drawTheme11(), drawTheme12(), drawTheme13(), drawTheme14(), drawTheme15(), drawTheme16(), drawTheme17(), drawTheme2(), drawTheme3(), drawTheme4(), drawTheme5(), drawTheme6(), drawTheme7(), drawTheme8(), drawTheme9(), m_type, Type_01, Type_02, Type_03, Type_04, Type_05, Type_06, Type_07, Type_08, Type_09, Type_10, Type_11, Type_12, Type_13, Type_14, Type_15, Type_16, and Type_17.
void MusicLrcPosterItemWidget::setCurrentSongName (const QString & name)
Set current song name.
Definition at line 46 of file musiclrcposterwidget.cpp.
References m_title, and name.
Referenced by MusicLrcPosterWidget::setCurrentLrcs().
void MusicLrcPosterItemWidget::setImagePath (const QString & path)
Set image path.
Definition at line 40 of file musiclrcposterwidget.cpp.
References m_pixmap.
Referenced by MusicLrcPosterWidget::openButtonClicked().
void MusicLrcPosterItemWidget::textChanged (const QStringList & data) slot
Lrc text changed.
Definition at line 51 of file musiclrcposterwidget.cpp.
References m_data.
Member Data Documentation
QStringList MusicLrcPosterItemWidget::m_data protected
Definition at line 162 of file musiclrcposterwidget.h.
Referenced by drawTheme1(), drawTheme10(), drawTheme11(), drawTheme12(), drawTheme13(), drawTheme14(), drawTheme15(), drawTheme16(), drawTheme17(), drawTheme2(), drawTheme3(), drawTheme4(), drawTheme5(), drawTheme6(), drawTheme7(), drawTheme8(), drawTheme9(), and textChanged().
QPixmap MusicLrcPosterItemWidget::m_pixmap protected
Definition at line 163 of file musiclrcposterwidget.h.
Referenced by drawTheme1(), drawTheme10(), drawTheme15(), drawTheme16(), drawTheme3(), drawTheme4(), drawTheme5(), drawTheme6(), MusicLrcPosterItemWidget(), and setImagePath().
QString MusicLrcPosterItemWidget::m_title protected
Definition at line 164 of file musiclrcposterwidget.h.
Referenced by drawTheme1(), drawTheme11(), drawTheme12(), drawTheme13(), drawTheme14(), drawTheme15(), drawTheme16(), drawTheme17(), drawTheme2(), drawTheme3(), drawTheme4(), drawTheme5(), drawTheme6(), drawTheme7(), drawTheme8(), drawTheme9(), and setCurrentSongName().
Type MusicLrcPosterItemWidget::m_type protected
Definition at line 161 of file musiclrcposterwidget.h.
Referenced by currentTypeChanged(), MusicLrcPosterItemWidget(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcposterwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcposterwidget.cpp