TTKMusicplayer: MusicDownloadMgmtWidget Class Reference
MusicDownloadMgmtWidget Class Reference
The class of the download manager widget.
#include <musicdownloadmgmtwidget.h>
Public Member Functions
MusicDownloadMgmtWidget (QObject *parent=nullptr)
void setSongName (const QString &name, MusicAbstractQueryRequest::QueryType type)
Protected Attributes
QWidget * m_parentClass
Detailed Description
The class of the download manager widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 84 of file musicdownloadmgmtwidget.h.
Constructor & Destructor Documentation
MusicDownloadMgmtWidget::MusicDownloadMgmtWidget (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 84 of file musicdownloadmgmtwidget.cpp.
References m_parentClass, and TTKStatic_cast.
Member Function Documentation
void MusicDownloadMgmtWidget::setSongName (const QString & name, MusicAbstractQueryRequest::QueryType type)
Set current name to search and download musics.
Definition at line 90 of file musicdownloadmgmtwidget.cpp.
References MusicApplication::instance(), m_parentClass, MusicApplication::musicDownloadContains(), MusicAbstractQueryRequest::MusicQuery, MusicDownloadResetWidget::setSongName(), MusicDownloadWidget::setSongName(), MusicDownloadResetWidget::show(), and MusicDownloadWidget::show().
Referenced by MusicLeftAreaWidget::musicDownloadSongToLocal().
Member Data Documentation
QWidget* MusicDownloadMgmtWidget::m_parentClass protected
Definition at line 100 of file musicdownloadmgmtwidget.h.
Referenced by MusicDownloadMgmtWidget(), and setSongName().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadmgmtwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadmgmtwidget.cpp