TTKMusicplayer: MusicLrcContainerVerticalDesktop Class Reference
MusicLrcContainerVerticalDesktop Class Reference
The class of the desktop vertical lrc container.
#include <musiclrccontainerfordesktop.h>
Public Slots
virtual void setSingleLineTypeChanged () override
Public Slots inherited from MusicLrcContainerForDesktop
void setWindowLockedChanged ()
void setLrcBiggerChanged ()
void setLrcSmallerChanged ()
void toolStyleChanged ()
virtual void setSingleLineTypeChanged ()
Public Slots inherited from MusicLrcContainer
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
Public Member Functions
MusicLrcContainerVerticalDesktop (QWidget *parent=nullptr)
virtual void initCurrentLrc () const override
Public Member Functions inherited from MusicLrcContainerForDesktop
MusicLrcContainerForDesktop (QWidget *parent=nullptr)
~MusicLrcContainerForDesktop ()
virtual void startDrawLrc () override
virtual void stopDrawLrc () override
virtual void applySettingParameter () override
void setCurrentPlayStatus (bool status) const
void updateCurrentLrc (const QString &first, const QString &second, qint64 time)
bool isVerticalWindowType () const
void makeStatusCopy (MusicLrcContainerForDesktop *other)
Public Member Functions inherited from MusicLrcContainer
MusicLrcContainer (QWidget *parent=nullptr)
~MusicLrcContainer ()
void setLinearGradientColor (MusicLrcColor::LrcColorType lrcColorType)
void setLinearGradientColor (const MusicLrcColor &color)
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 getTotalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * getLrcAnalysisModel () const
Protected Member Functions
virtual void resizeLrcSizeArea () override
Protected Member Functions inherited from MusicLrcContainerForDesktop
void createColorMenu (QMenu &menu)
void setSelfPosition () const
void creatToolBarWidget ()
void resizeLrcSizeArea (bool resize)
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
virtual void closeEvent (QCloseEvent *event) override
Protected Member Functions inherited from MusicLrcContainer
void clearAllMusicLRCManager ()
void applySettingParameter (const QString &t)
Additional Inherited Members
Signals inherited from MusicLrcContainerForDesktop
void setWindowLockedChanged (bool lock)
Signals inherited from MusicLrcContainer
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Protected Attributes inherited from MusicLrcContainerForDesktop
bool m_verticalWindow
bool m_singleLineType
bool m_windowLocked
bool m_reverse
int m_currentLrcFontSize
int m_widgetWidth
QPoint m_offset
QPoint m_geometry
QBoxLayout * m_toolBarLayout
QWidget * m_toolBarWidget
QToolButton * m_toolPlayButton
Protected Attributes inherited from MusicLrcContainer
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_musicLrcContainer
MusicLrcSearchWidget * m_musicLrcSearchWidget
Detailed Description
The class of the desktop vertical lrc container.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 194 of file musiclrccontainerfordesktop.h.
Constructor & Destructor Documentation
MusicLrcContainerVerticalDesktop::MusicLrcContainerVerticalDesktop (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 515 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainerForDesktop::creatToolBarWidget(), G_SETTING_PTR, MusicLrcContainerForDesktop::m_currentLrcFontSize, MusicLrcContainerForDesktop::m_geometry, MusicLrcContainer::m_musicLrcContainer, MusicLrcContainerForDesktop::m_toolBarLayout, MusicLrcContainerForDesktop::m_toolBarWidget, MusicLrcContainerForDesktop::m_verticalWindow, MusicLrcContainerForDesktop::m_widgetWidth, MusicSettingManager::ScreenSize, MusicLrcContainerForDesktop::setSelfPosition(), TOOLBAR_HEIGHT, and TOOLBAR_MAIN_HEIGHT.
Member Function Documentation
void MusicLrcContainerVerticalDesktop::initCurrentLrc () const override virtual
Init current lrc when the first show.
Reimplemented from MusicLrcContainerForDesktop.
Definition at line 542 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainerForDesktop::initCurrentLrc(), MusicLrcContainer::m_currentTime, MusicLrcContainerForDesktop::m_geometry, MusicLrcContainer::m_musicLrcContainer, MusicLrcContainerForDesktop::m_singleLineType, and MusicLrcContainerForDesktop::m_widgetWidth.
void MusicLrcContainerVerticalDesktop::resizeLrcSizeArea () override protected virtual
Resize lrc size area by change size.
Implements MusicLrcContainerForDesktop.
Definition at line 574 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainerForDesktop::m_geometry, MusicLrcContainer::m_musicLrcContainer, MusicLrcContainerForDesktop::m_singleLineType, and MusicLrcContainerForDesktop::m_widgetWidth.
void MusicLrcContainerVerticalDesktop::setSingleLineTypeChanged () override virtual slot
Set single line type changed.
Definition at line 560 of file musiclrccontainerfordesktop.cpp.
References MusicLrcContainer::m_musicLrcContainer, MusicLrcContainerForDesktop::m_singleLineType, MusicLrcContainerForDesktop::m_widgetWidth, and MusicLrcContainerForDesktop::setSingleLineTypeChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerfordesktop.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerfordesktop.cpp