TTKMusicplayer: filter::filter_t Class Reference
filter::filter_t Class Reference
#include <imagefilter.h>
Public Member Functions
filter_t ()
filter_t (long radius, long size)
void set (long radius, long size)
long radius ()
Public Member Functions inherited from filter::auto_t< double >
auto_t ()
auto_t (long size)
virtual ~auto_t ()
void set (long size)
long size ()
double & operator[] (long num)
Protected Attributes
long _radius
Protected Attributes inherited from filter::auto_t< double >
double * _point
long _size
Detailed Description
Definition at line 113 of file imagefilter.h.
Constructor & Destructor Documentation
filter::filter_t::filter_t () inline
Definition at line 119 of file imagefilter.h.
Referenced by set().
filter::filter_t::filter_t (long radius, long size) inline
Definition at line 120 of file imagefilter.h.
Member Function Documentation
long filter::filter_t::radius () inline
Definition at line 128 of file imagefilter.h.
References _radius.
Referenced by filter::Blur1D(), filter::Blur2D(), filter::Gauss(), filter::Gauss2(), and filter::Linear().
void filter::filter_t::set (long radius, long size) inline
Definition at line 123 of file imagefilter.h.
References filter_t().
Referenced by filter::Average(), filter::Gauss(), filter::Gauss2(), and filter::Linear().
Member Data Documentation
long filter::filter_t::_radius protected
Definition at line 116 of file imagefilter.h.
Referenced by radius().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKImage/imagefilter.h