TTKMusicPlayer: MusicItemRenameEidt Class Reference
MusicItemRenameEidt Class Reference
The class of the item rename edit.
#include <musicitemrenameedit.h>
Public Slots
void textChanged (const QString &text)
void renameFinished ()
void animationCloseChanged ()
Signals
void renameFinished (const QString &text)
Public Member Functions
MusicItemRenameEidt (QWidget *parent=nullptr)
MusicItemRenameEidt (const QString &text, QWidget *parent=nullptr)
Private Member Functions
virtual void focusOutEvent (QFocusEvent *event) overridefinal
Private Attributes
bool m_focusBlock
Detailed Description
The class of the item rename edit.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicitemrenameedit.h.
Constructor & Destructor Documentation
MusicItemRenameEidt::MusicItemRenameEidt (QWidget * parent = nullptr) explicit
Object contsructor by index and origin name.
Definition at line 6 of file musicitemrenameedit.cpp.
References MusicUIObject::MQSSLineEditStyle01, renameFinished(), and textChanged().
MusicItemRenameEidt::MusicItemRenameEidt (const QString & text, QWidget * parent = nullptr) explicit
Definition at line 19 of file musicitemrenameedit.cpp.
Member Function Documentation
void MusicItemRenameEidt::animationCloseChanged () slot
Animation close changed.
Definition at line 45 of file musicitemrenameedit.cpp.
References m_focusBlock.
Referenced by textChanged().
void MusicItemRenameEidt::focusOutEvent (QFocusEvent * event) final override private virtual
Override the widget event.
Definition at line 51 of file musicitemrenameedit.cpp.
References m_focusBlock, and renameFinished().
void MusicItemRenameEidt::renameFinished (const QString & text) signal
Tool rename is finished it emit.
void MusicItemRenameEidt::renameFinished () slot
Tool rename is finished.
Definition at line 40 of file musicitemrenameedit.cpp.
Referenced by focusOutEvent(), and MusicItemRenameEidt().
void MusicItemRenameEidt::textChanged (const QString & text) slot
Input text data changed.
Definition at line 25 of file musicitemrenameedit.cpp.
References animationCloseChanged(), MusicUtils::String::illegalCharacters(), MusicUtils::String::isCharacterValid(), m_focusBlock, MusicToastLabel::popup(), and TTKToastLabel::setText().
Referenced by MusicItemRenameEidt().
Member Data Documentation
bool MusicItemRenameEidt::m_focusBlock private
Definition at line 65 of file musicitemrenameedit.h.
Referenced by animationCloseChanged(), focusOutEvent(), and textChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicitemrenameedit.h
TTKModule/TTKWidget/musicCoreKits/musicitemrenameedit.cpp