TTKMusicplayer: MusicWYDiscoverListThread Class Reference
MusicWYDiscoverListThread Class Reference
The class to wangyi discover toplist.
#include <musicwydiscoverlistthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYDiscoverListThread (QObject *parent=0)
QJson import.
virtual void startToSearch () override
Public Member Functions inherited from MusicDownLoadDiscoverListThread
MusicDownLoadDiscoverListThread (QObject *parent=0)
QString getToplistInfo () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadDiscoverListThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadDiscoverListThread
QString m_toplistInfo
Protected Attributes inherited from MusicDownLoadPagingThread
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to wangyi discover toplist.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwydiscoverlistthread.h.
Constructor & Destructor Documentation
MusicWYDiscoverListThread::MusicWYDiscoverListThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 6 of file musicwydiscoverlistthread.cpp.
Member Function Documentation
void MusicWYDiscoverListThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 40 of file musicwydiscoverlistthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_reply, MusicDownLoadDiscoverListThread::m_toplistInfo, and QJson::Parser::parse().
Referenced by startToSearch().
QString MusicWYDiscoverListThread::getClassName () static
Get class object name.
Definition at line 12 of file musicwydiscoverlistthread.cpp.
Referenced by downLoadFinished(), and startToSearch().
void MusicWYDiscoverListThread::startToSearch () override virtual
Start to Search data from toplist.
Implements MusicDownLoadDiscoverListThread.
Definition at line 17 of file musicwydiscoverlistthread.cpp.
References downLoadFinished(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), WY_SG_TOPLIST_N_URL, and WY_SG_TOPLIST_NDT_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicwydiscoverlistthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicwydiscoverlistthread.cpp