TTKMusicplayer: MusicTimerAutoModule Class Reference
MusicTimerAutoModule Class Reference
The class of the time auto run.
#include <musictimerautomodule.h>
Public Slots
void timeout ()
Public Member Functions
MusicTimerAutoModule (QObject *parent=nullptr)
~MusicTimerAutoModule ()
void runTimerAutoConfig ()
Protected Member Functions
void setShutdown ()
Protected Attributes
QTimer m_timer
MusicTimeDatas m_timeDatas
Detailed Description
The class of the time auto run.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 52 of file musictimerautomodule.h.
Constructor & Destructor Documentation
MusicTimerAutoModule::MusicTimerAutoModule (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 15 of file musictimerautomodule.cpp.
References MusicTimeData::m_index, m_timeDatas, m_timer, and timeout().
MusicTimerAutoModule::~MusicTimerAutoModule ()
Definition at line 27 of file musictimerautomodule.cpp.
References m_timer.
Member Function Documentation
void MusicTimerAutoModule::runTimerAutoConfig ()
Run time auto from local file config.
Definition at line 32 of file musictimerautomodule.cpp.
References G_SETTING_PTR, m_timeDatas, m_timer, MT_S2MS, MusicSettingManager::TimerAutoPlayHour, MusicSettingManager::TimerAutoPlayMode, MusicSettingManager::TimerAutoPlaySecond, MusicSettingManager::TimerAutoShutdownHour, MusicSettingManager::TimerAutoShutdownMode, MusicSettingManager::TimerAutoShutdownSecond, MusicSettingManager::TimerAutoStopHour, MusicSettingManager::TimerAutoStopMode, and MusicSettingManager::TimerAutoStopSecond.
Referenced by MusicApplicationModule::musicToolSetsParameter().
void MusicTimerAutoModule::setShutdown () protected
Set current system to shutdown.
Definition at line 113 of file musictimerautomodule.cpp.
References MT_S2MS, MusicUtils::Core::sleep(), TTK_LOGGER_INFO, and TTKStatic_cast.
Referenced by timeout().
void MusicTimerAutoModule::timeout () slot
Check current state by one minute.
Definition at line 58 of file musictimerautomodule.cpp.
References G_SETTING_PTR, MusicApplication::instance(), MusicTimeData::m_hour, MusicTimeData::m_index, MusicTimeData::m_minute, MusicTimeData::m_state, m_timeDatas, MusicApplication::musicStateStop(), MusicApplication::setPlaySongChanged(), setShutdown(), MusicSettingManager::TimerAutoPlayMode, MusicSettingManager::TimerAutoPlayRepeat, MusicSettingManager::TimerAutoPlaySongIndex, MusicSettingManager::TimerAutoShutdownMode, MusicSettingManager::TimerAutoShutdownRepeat, MusicSettingManager::TimerAutoStopMode, and MusicSettingManager::TimerAutoStopRepeat.
Referenced by MusicTimerAutoModule().
Member Data Documentation
MusicTimeDatas MusicTimerAutoModule::m_timeDatas protected
Definition at line 81 of file musictimerautomodule.h.
Referenced by MusicTimerAutoModule(), runTimerAutoConfig(), and timeout().
QTimer MusicTimerAutoModule::m_timer protected
Definition at line 80 of file musictimerautomodule.h.
Referenced by MusicTimerAutoModule(), runTimerAutoConfig(), and ~MusicTimerAutoModule().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musictimerautomodule.h
TTKModule/TTKCore/musicToolsSetsKits/musictimerautomodule.cpp