TTKMusicPlayer: MusicSongSearchPopWidget Class Reference
MusicSongSearchPopWidget Class Reference
The class of the search history Config.
#include <musicsongsearchpopwidget.h>
Public Slots
void clearButtonClicked ()
Signals
void setText (const QString &text)
Public Member Functions
MusicSongSearchPopWidget (QWidget *parent=nullptr)
~MusicSongSearchPopWidget ()
void initialize (QWidget *parent)
void selectRow (bool up)
void setControlEnabled (bool enabled)
void createSuggestItems (const QStringList &names)
Private Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
QString utcTimeToLocal (const QString &time) const
Private Attributes
QFrame * m_frame
QPushButton * m_clearButton
MusicSongSearchPopTableWidget * m_popTableWidget
Detailed Description
The class of the search history Config.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 75 of file musicsongsearchpopwidget.h.
Constructor & Destructor Documentation
MusicSongSearchPopWidget::MusicSongSearchPopWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 84 of file musicsongsearchpopwidget.cpp.
References TTK::UI::BackgroundStyle10, TTK::UI::BorderStyle01, clearButtonClicked(), TTK::UI::ColorStyle03, TTK::UI::ColorStyle05, TTK::UI::CustomStyle01, TTK::UI::FontStyle02, m_clearButton, m_frame, and m_popTableWidget.
MusicSongSearchPopWidget::~MusicSongSearchPopWidget ()
Object destructor.
Definition at line 116 of file musicsongsearchpopwidget.cpp.
References m_clearButton, and m_popTableWidget.
Member Function Documentation
void MusicSongSearchPopWidget::clearButtonClicked () slot
Clear the search history.
Definition at line 207 of file musicsongsearchpopwidget.cpp.
References TTKAbstractXml::load(), SEARCH_PATH_FULL, and MusicSongSearchRecordConfigManager::writeBuffer().
Referenced by MusicSongSearchPopWidget().
void MusicSongSearchPopWidget::createSuggestItems (const QStringList & names)
Create popup search suggest table items.
Definition at line 171 of file musicsongsearchpopwidget.cpp.
References MusicSongSearchPopTableWidget::addCellItem(), m_popTableWidget, MusicSongSearchPopTableWidget::removeItems(), setControlEnabled(), and TTK_ITEM_SIZE_M.
Referenced by MusicSongSearchInteriorEdit::suggestDataChanged().
void MusicSongSearchPopWidget::initialize (QWidget * parent)
Create popup search history table items.
Definition at line 122 of file musicsongsearchpopwidget.cpp.
References MusicSongSearchPopTableWidget::addCellItem(), TTKAbstractXml::fromFile(), m_popTableWidget, MAX_ITEM_COUNT, MusicSongSearchRecordConfigManager::readBuffer(), MusicSongSearchPopTableWidget::removeItems(), SEARCH_PATH_FULL, setControlEnabled(), setText(), TTK_ITEM_SIZE_M, and utcTimeToLocal().
Referenced by MusicSongSearchInteriorEdit::textChanged().
void MusicSongSearchPopWidget::paintEvent (QPaintEvent * event) final override private virtual
Override the widget event.
Definition at line 219 of file musicsongsearchpopwidget.cpp.
void MusicSongSearchPopWidget::selectRow (bool up)
Select search history table items.
Definition at line 151 of file musicsongsearchpopwidget.cpp.
References m_popTableWidget, and MusicSongSearchPopTableWidget::selectRow().
Referenced by MusicSongSearchInteriorEdit::keyReleaseEvent().
void MusicSongSearchPopWidget::setControlEnabled (bool enabled)
set control module enabled.
Definition at line 156 of file musicsongsearchpopwidget.cpp.
References m_clearButton, and m_frame.
Referenced by createSuggestItems(), and initialize().
void MusicSongSearchPopWidget::setText (const QString & text) signal
User click the current item.
Referenced by initialize().
QString MusicSongSearchPopWidget::utcTimeToLocal (const QString & time) const private
Transform utc time to local time before.
Definition at line 186 of file musicsongsearchpopwidget.cpp.
References TTKDateTime::currentTimestamp(), TTK_DN_D2S, TTK_DN_H2S, TTK_DN_M2S, and TTK_DN_S2MS.
Referenced by initialize().
Member Data Documentation
QPushButton* MusicSongSearchPopWidget::m_clearButton private
Definition at line 132 of file musicsongsearchpopwidget.h.
Referenced by MusicSongSearchPopWidget(), setControlEnabled(), and ~MusicSongSearchPopWidget().
QFrame* MusicSongSearchPopWidget::m_frame private
Definition at line 131 of file musicsongsearchpopwidget.h.
Referenced by MusicSongSearchPopWidget(), and setControlEnabled().
MusicSongSearchPopTableWidget* MusicSongSearchPopWidget::m_popTableWidget private
Definition at line 133 of file musicsongsearchpopwidget.h.
Referenced by createSuggestItems(), initialize(), MusicSongSearchPopWidget(), selectRow(), and ~MusicSongSearchPopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicsongsearchpopwidget.h
TTKModule/TTKWidget/musicSearchKits/musicsongsearchpopwidget.cpp