TTKMusicplayer: MusicDownLoadBDInterface Class Reference
MusicDownLoadBDInterface Class Reference
The class to baidu query download interface.
#include <musicdownloadbdinterface.h>
Public Member Functions
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &bit)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicPayAttribute (MusicObject::MusicSongInformation *info)
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
Detailed Description
The class to baidu query download interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 48 of file musicdownloadbdinterface.h.
Member Function Documentation
QString MusicDownLoadBDInterface::findTimeStringByAttrs (const MusicObject::MusicSongAttributes & attrs)
Find time string by attrs.
Definition at line 238 of file musicdownloadbdinterface.cpp.
References MusicObject::MusicSongAttribute::m_duration.
Referenced by MusicDownLoadQueryBDThread::downLoadFinished(), and MusicDownLoadQueryBDPlaylistThread::getDetailsFinished().
void MusicDownLoadBDInterface::readFromMusicLLAttribute (MusicObject::MusicSongInformation * info)
Read tags(size) from query results.
Definition at line 134 of file musicdownloadbdinterface.cpp.
References BD_SONG_INFO_URL, MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_duration, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), MusicUtils::Number::size2Label(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by readFromMusicSongAttribute().
void MusicDownLoadBDInterface::readFromMusicPayAttribute (MusicObject::MusicSongInformation * info)
Read tags(size) from query results.
Definition at line 188 of file musicdownloadbdinterface.cpp.
References BD_SONG_FMINFO_URL, BD_SONG_SSDOWN_URL, BD_SONG_YYDOWN_URL, MusicSemaphoreLoop::exec(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicUtils::Number::size2Label(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by readFromMusicSongAttribute().
void MusicDownLoadBDInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & bit)
QJson import.
Read tags(size) from query results.
Definition at line 15 of file musicdownloadbdinterface.cpp.
References BD_SONG_ATTR_PA_URL, BD_SONG_ATTR_URL, QAesWrap::encrypt(), MusicSemaphoreLoop::exec(), key, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_duration, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), readFromMusicPayAttribute(), MusicUtils::Number::size2Label(), MusicTime::timeStamp(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), and readFromMusicSongAttribute().
void MusicDownLoadBDInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & format, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 87 of file musicdownloadbdinterface.cpp.
References MB_128, MB_192, MB_320, MB_64, readFromMusicLLAttribute(), readFromMusicSongAttribute(), and MusicUtils::Number::transfromBitrateToNormal().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/bd/musicdownloadbdinterface.h
TTKModule/TTKCore/musicNetworkKits/bd/musicdownloadbdinterface.cpp