TTKMusicPlayer: MusicReplayGainWidget Class Reference
MusicReplayGainWidget Class Reference
The class of the replay gain widget.
#include <musicreplaygainwidget.h>
Public Slots
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
void show ()
Public Member Functions
MusicReplayGainWidget (QWidget *parent=nullptr)
~MusicReplayGainWidget ()
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=nullptr)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveWidget ()
Public Member Functions inherited from TTKAbstractMoveWidget
TTKAbstractMoveWidget (QWidget *parent=nullptr)
TTKAbstractMoveWidget (bool transparent, QWidget *parent=nullptr)
void setShadowOption (bool show) noexcept
void setBlockOption (bool block) noexcept
Private Slots
void addFileButtonClicked ()
void addFilesButtonClicked ()
void rmFileButtonClicked ()
void rmFilesButtonClicked ()
void analysisButtonClicked ()
void applyButtonClicked ()
void lineTextChanged (const QString &text)
void analysisOutput ()
void applyOutput ()
void confirmDataChanged ()
Private Member Functions
void initialize ()
void addItemFinished (const QString &track, const QString &album)
void setControlEnabled (bool enabled)
Private Attributes
Ui::MusicReplayGainWidget * m_ui
QProcess * m_process
QStringList m_paths
Light * m_replayGainWidget
int m_currentIndex
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label) noexcept
Protected Attributes inherited from TTKAbstractMoveWidget
bool m_mouseLeftPressed
bool m_blockOption
bool m_shadowOption
QPoint m_windowPos
QPoint m_pressedPos
Detailed Description
The class of the replay gain widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 49 of file musicreplaygainwidget.h.
Constructor & Destructor Documentation
MusicReplayGainWidget::MusicReplayGainWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 33 of file musicreplaygainwidget.cpp.
References addFileButtonClicked(), addFilesButtonClicked(), analysisButtonClicked(), analysisOutput(), applyButtonClicked(), confirmDataChanged(), initialize(), TTK::UI::LineEditStyle01, lineTextChanged(), m_process, m_ui, TTK::UI::ProgressBar01, rmFileButtonClicked(), rmFilesButtonClicked(), MusicWidgetRenderer::setBackgroundLabel(), TTK::UI::TabWidgetStyle01, and TTK::UI::ToolButtonStyle04.
MusicReplayGainWidget::~MusicReplayGainWidget ()
Object destructor.
Definition at line 114 of file musicreplaygainwidget.cpp.
References m_process, m_ui, and TTK_REMOVE_SINGLE_WIDGET.
Member Function Documentation
void MusicReplayGainWidget::addFileButtonClicked () private slot
Add input file button clicked.
Definition at line 190 of file musicreplaygainwidget.cpp.
References TTKEventLoop::exec(), TTK::File::getOpenFileNames(), m_currentIndex, m_paths, m_process, MAKE_GAIN_PATH_FULL, qAsConst, QtProcessErrorVoidConnect, QtProcessFinishVoidConnect, setControlEnabled(), and TTK_SLOT.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::addFilesButtonClicked () private slot
Add input files button clicked.
Definition at line 219 of file musicreplaygainwidget.cpp.
References TTKEventLoop::exec(), TTK::File::fileInfoListByPath(), TTK::File::getExistingDirectory(), m_currentIndex, m_paths, m_process, MAKE_GAIN_PATH_FULL, MP3_FILE_SUFFIX, QtProcessErrorVoidConnect, QtProcessFinishVoidConnect, setControlEnabled(), TTK_FILE_SUFFIX, and TTK_SLOT.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::addItemFinished (const QString & track, const QString & album) private
Create table item finished.
Definition at line 142 of file musicreplaygainwidget.cpp.
References TTK::Widget::elidedText(), GAIN_DEFAULT, m_currentIndex, m_paths, m_ui, and QtItemSetTextAlignment.
Referenced by analysisOutput().
void MusicReplayGainWidget::analysisButtonClicked () private slot
Analysis input files button clicked.
do nothing here
Definition at line 261 of file musicreplaygainwidget.cpp.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::analysisOutput () private slot
Analysis output by process.
Definition at line 311 of file musicreplaygainwidget.cpp.
References addItemFinished(), GAIN_ALBUMDB, GAIN_TRACKDB, m_process, and TTK_WLINEFEED.
Referenced by applyButtonClicked(), and MusicReplayGainWidget().
void MusicReplayGainWidget::applyButtonClicked () private slot
Apply input files button clicked.
Definition at line 266 of file musicreplaygainwidget.cpp.
References analysisOutput(), applyOutput(), TTKEventLoop::exec(), m_paths, m_process, m_ui, MAKE_GAIN_PATH_FULL, MusicToastLabel::popup(), QtProcessErrorVoidConnect, QtProcessFinishVoidConnect, rmFilesButtonClicked(), setControlEnabled(), and TTK_SLOT.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::applyOutput () private slot
Apply output by process.
Definition at line 338 of file musicreplaygainwidget.cpp.
References m_process, and m_ui.
Referenced by applyButtonClicked().
void MusicReplayGainWidget::confirmDataChanged () private slot
Confirm Data changed.
Definition at line 358 of file musicreplaygainwidget.cpp.
References m_replayGainWidget, m_ui, Light::open(), and qAsConst.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::initialize () private
Init widget and parameter.
Definition at line 121 of file musicreplaygainwidget.cpp.
References TTK::UI::CheckBoxStyle01, LightFactory::create(), TTK::UI::HeaderView01, m_replayGainWidget, m_ui, TTK::TTKQmmp::pluginPath(), MusicToastLabel::popup(), TTK::UI::ProgressBar01, TTK::UI::PushButtonStyle04, TTK::UI::ScrollBarStyle03, and TTKObjectCast.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::lineTextChanged (const QString & text) private slot
Media gain input value changed.
Definition at line 299 of file musicreplaygainwidget.cpp.
References m_ui.
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::rmFileButtonClicked () private slot
Remove input file button clicked.
Definition at line 243 of file musicreplaygainwidget.cpp.
References m_ui, and MusicToastLabel::popup().
Referenced by MusicReplayGainWidget().
void MusicReplayGainWidget::rmFilesButtonClicked () private slot
Remove input files button clicked.
Definition at line 254 of file musicreplaygainwidget.cpp.
References m_currentIndex, m_paths, and m_ui.
Referenced by applyButtonClicked(), and MusicReplayGainWidget().
void MusicReplayGainWidget::setControlEnabled (bool enabled) private
Enable or disable control state.
Definition at line 180 of file musicreplaygainwidget.cpp.
References m_ui.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), and applyButtonClicked().
void MusicReplayGainWidget::show () slot
Override show function.
Definition at line 370 of file musicreplaygainwidget.cpp.
References MAKE_GAIN_PATH_FULL, MusicToastLabel::popup(), and MusicAbstractMoveWidget::show().
Member Data Documentation
int MusicReplayGainWidget::m_currentIndex private
Definition at line 129 of file musicreplaygainwidget.h.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), addItemFinished(), and rmFilesButtonClicked().
QStringList MusicReplayGainWidget::m_paths private
Definition at line 127 of file musicreplaygainwidget.h.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), addItemFinished(), applyButtonClicked(), and rmFilesButtonClicked().
QProcess* MusicReplayGainWidget::m_process private
Definition at line 126 of file musicreplaygainwidget.h.
Referenced by addFileButtonClicked(), addFilesButtonClicked(), analysisOutput(), applyButtonClicked(), applyOutput(), MusicReplayGainWidget(), and ~MusicReplayGainWidget().
Light* MusicReplayGainWidget::m_replayGainWidget private
Definition at line 128 of file musicreplaygainwidget.h.
Referenced by confirmDataChanged(), and initialize().
Ui::MusicReplayGainWidget* MusicReplayGainWidget::m_ui private
Definition at line 125 of file musicreplaygainwidget.h.
Referenced by addItemFinished(), applyButtonClicked(), applyOutput(), confirmDataChanged(), initialize(), lineTextChanged(), MusicReplayGainWidget(), rmFileButtonClicked(), rmFilesButtonClicked(), setControlEnabled(), and ~MusicReplayGainWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicreplaygainwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicreplaygainwidget.cpp