TTKMusicPlayer: MusicDataSourceRequest Class Reference
MusicDataSourceRequest Class Reference
The class of the data source download request.
#include <musicdatasourcerequest.h>
Public Slots
virtual void downLoadFinished () overridefinal
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDataSourceRequest (QObject *parent=nullptr)
virtual void deleteAll () overridefinal
void startRequest (const QString &url)
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
~MusicAbstractNetwork ()
void setHeader (const QString &key, const QVariant &value)
const QVariant header (const QString &key) const
Additional Inherited Members
Signals inherited from MusicAbstractNetwork
void downLoadDataChanged (const QString &bytes)
void downLoadRawDataChanged (const QByteArray &bytes)
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile TTK::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Detailed Description
The class of the data source download request.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicdatasourcerequest.h.
Constructor & Destructor Documentation
MusicDataSourceRequest::MusicDataSourceRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdatasourcerequest.cpp.
Member Function Documentation
void MusicDataSourceRequest::deleteAll () final override virtual
Release the network object.
Reimplemented from MusicAbstractNetwork.
Definition at line 9 of file musicdatasourcerequest.cpp.
References MusicAbstractNetwork::deleteAll().
Referenced by downLoadFinished().
void MusicDataSourceRequest::downLoadFinished () final override virtual slot
Download data from net finished.
Definition at line 26 of file musicdatasourcerequest.cpp.
References deleteAll(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadFinished(), MusicAbstractNetwork::downLoadRawDataChanged(), MusicAbstractNetwork::m_reply, startRequest(), and TTK_ERROR_STREAM.
Referenced by startRequest().
void MusicDataSourceRequest::startRequest (const QString & url)
Start to download data.
Definition at line 15 of file musicdatasourcerequest.cpp.
References downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, QtNetworkErrorConnect, MusicAbstractNetwork::replyError(), and TTK::setSslConfiguration().
Referenced by MusicCommentsItem::addCellItem(), MusicAlbumQueryWidget::createAlbumItem(), MusicArtistQueryWidget::createArtistItem(), MusicWebMVRadioInfoWidget::createMVRadioProgramItem(), MusicWebDJRadioInfoWidget::createProgramCategoryItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicToplistQueryWidget::createToplistItem(), downLoadFinished(), MusicDownloadMetaDataRequest::downLoadFinished(), MusicCloudManagerTableWidget::queryCloudKey(), MusicIdentifySongRequest::queryIdentifyKey(), MusicSongSharingWidget::setData(), MusicArtistAlbumsItemWidget::setResultDataItem(), MusicWebMVRadioQueryItemWidget::setResultDataItem(), MusicWebDJRadioCategoryItemWidget::setResultDataItem(), MusicWebDJRadioQueryItemWidget::setResultDataItem(), MusicPlaylistQueryItemWidget::setResultDataItem(), MusicPlaylistQueryInfoWidget::setResultDataItem(), MusicDownloadBingSkinRequest::startRequest(), MusicNetworkOperator::startRequest(), MusicDownloadBirdSkinRequest::startRequest(), MusicSourceUpdateRequest::startRequest(), and MusicDownloadThunderSkinRequest::startRequest().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/tools/musicdatasourcerequest.h
TTKModule/TTKCore/musicNetworkKits/tools/musicdatasourcerequest.cpp