TTKMusicPlayer: MusicAlbumQueryWidget Class Reference
MusicAlbumQueryWidget Class Reference
The class of the album music query widget.
#include <musicalbumquerywidget.h>
Public Slots
void queryAllFinished ()
void queryAlbumFinished ()
void createAlbumItem (const MusicResultDataItem &item)
Public Slots inherited from MusicAbstractItemQueryWidget
void downLoadFinished (const QByteArray &bytes)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicAlbumQueryWidget (QWidget *parent=nullptr)
virtual void setCurrentValue (const QString &value) overridefinal
virtual void setCurrentID (const QString &id) overridefinal
virtual void resizeWidget () overridefinal
Public Member Functions inherited from MusicAbstractItemQueryWidget
MusicAbstractItemQueryWidget (QWidget *parent=nullptr)
~MusicAbstractItemQueryWidget ()
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Member Functions
void createLabels ()
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractItemQueryWidget
virtual void mousePressEvent (QMouseEvent *event) overridefinal
virtual void mouseMoveEvent (QMouseEvent *event) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *event) overridefinal
void initFirstWidget ()
void initSecondWidget ()
void setSongCountText ()
Protected Attributes inherited from MusicAbstractItemQueryWidget
QString m_value
QWidget * m_mainWindow
QPushButton * m_songButton
QLabel * m_iconLabel
QLabel * m_statusLabel
QLabel * m_infoLabel
QStackedWidget * m_container
MusicResultDataItem m_currentPlaylistItem
MusicItemQueryTableWidget * m_queryTableWidget
MusicAbstractQueryRequest * m_networkRequest
MusicSongSharingWidget::Module m_shareType
QList< TTKResizeWidget > m_resizeWidgets
Detailed Description
The class of the album music query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 52 of file musicalbumquerywidget.h.
Constructor & Destructor Documentation
MusicAlbumQueryWidget::MusicAlbumQueryWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 30 of file musicalbumquerywidget.cpp.
References MusicSongSharingWidget::Album, G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_shareType, and queryAllFinished().
Member Function Documentation
void MusicAlbumQueryWidget::createAlbumItem (const MusicResultDataItem & item) slot
Create the current album info item.
Definition at line 128 of file musicalbumquerywidget.cpp.
References createLabels(), MusicAbstractItemQueryWidget::downLoadFinished(), TTK::Widget::elidedText(), G_DOWNLOAD_QUERY_PTR, G_SETTING_PTR, TTK::isCoverValid(), MusicResultDataItem::m_category, MusicResultDataItem::m_count, MusicResultDataItem::m_coverUrl, MusicAbstractItemQueryWidget::m_currentPlaylistItem, MusicResultDataItem::m_description, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicResultDataItem::m_name, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicResultDataItem::m_updateTime, MusicCoverRequest::startToRequest(), TTK_DEFAULT_STR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by setCurrentID().
void MusicAlbumQueryWidget::createLabels () private
Create init interface lables.
Definition at line 179 of file musicalbumquerywidget.cpp.
References TTK::UI::CheckBoxStyle01, TTK::UI::ColorStyle04, TTK::UI::ColorStyle11, TTK::UI::FontStyle01, TTK::UI::FontStyle03, TTK::UI::FontStyle05, TTK::Widget::generateVScrollAreaFormat(), MusicAbstractItemQueryWidget::initFirstWidget(), MusicAbstractItemQueryWidget::m_container, MusicAbstractItemQueryWidget::m_iconLabel, MusicAbstractItemQueryWidget::m_mainWindow, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicAbstractItemQueryWidget::m_songButton, MusicAbstractItemQueryWidget::m_statusLabel, MusicAbstractItemQueryWidget::playAllButtonClicked(), TTK::UI::PushButtonStyle03, QtButtonGroupConnect, TTK::random(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), MusicAbstractItemQueryWidget::shareButtonClicked(), TTK_DEFAULT_STR, and TTK_SLOT.
Referenced by createAlbumItem().
void MusicAlbumQueryWidget::queryAlbumFinished () slot
Query album musics is finished.
Definition at line 109 of file musicalbumquerywidget.cpp.
References MusicAbstractQueryRequest::items(), MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_statusLabel, MusicQueryTableWidget::queryInput(), and MusicAbstractItemQueryWidget::setSongCountText().
void MusicAlbumQueryWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 82 of file musicalbumquerywidget.cpp.
References MusicAbstractQueryRequest::items(), MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractItemQueryWidget::m_statusLabel, MusicAbstractItemQueryWidget::m_value, qAsConst, and setCurrentID().
Referenced by MusicAlbumQueryWidget().
void MusicAlbumQueryWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 57 of file musicalbumquerywidget.cpp.
References TTK::Widget::elidedText(), G_SETTING_PTR, MusicAbstractItemQueryWidget::TTKResizeWidget::m_font, MusicAbstractItemQueryWidget::TTKResizeWidget::m_label, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicAbstractItemQueryWidget::m_resizeWidgets, MusicItemQueryTableWidget::resizeSection(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
void MusicAlbumQueryWidget::setCurrentID (const QString & id) final override virtual
Set current id to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 49 of file musicalbumquerywidget.cpp.
References createAlbumItem(), G_DOWNLOAD_QUERY_PTR, MusicAbstractItemQueryWidget::m_queryTableWidget, MusicQueryTableWidget::setQueryInput(), and MusicItemQueryTableWidget::startToSearchByText().
Referenced by queryAllFinished(), and MusicRightAreaWidget::showAlbumFound().
void MusicAlbumQueryWidget::setCurrentValue (const QString & value) final override virtual
Set current value to search founds.
Reimplemented from MusicAbstractItemQueryWidget.
Definition at line 41 of file musicalbumquerywidget.cpp.
References MusicAbstractItemQueryWidget::m_networkRequest, MusicAbstractQueryRequest::Meta, MusicAbstractQueryRequest::Music, MusicAbstractItemQueryWidget::setCurrentValue(), MusicAbstractQueryRequest::setQueryMode(), MusicAbstractQueryRequest::setQueryType(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicRightAreaWidget::showAlbumFound().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicalbumquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicalbumquerywidget.cpp