TTKMusicplayer: MusicArtistListQueryItemWidget Class Reference
MusicArtistListQueryItemWidget Class Reference
The class of the artist list music item widget.
#include <musicartistlistquerywidget.h>
Public Slots
void currentItemClicked ()
Signals
void currentItemClicked (const MusicResultsItem &item)
Signals inherited from MusicClickedLabel
void clicked ()
Public Member Functions
MusicArtistListQueryItemWidget (QWidget *parent=nullptr)
void setMusicResultsItem (const MusicResultsItem &item)
Public Member Functions inherited from MusicClickedLabel
MusicClickedLabel (QWidget *parent=nullptr)
MusicClickedLabel (const QString &text, QWidget *parent=nullptr)
Protected Attributes
MusicResultsItem m_itemData
Additional Inherited Members
Protected Member Functions inherited from MusicClickedLabel
virtual void mousePressEvent (QMouseEvent *event) override
Detailed Description
The class of the artist list music item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicartistlistquerywidget.h.
Constructor & Destructor Documentation
MusicArtistListQueryItemWidget::MusicArtistListQueryItemWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 16 of file musicartistlistquerywidget.cpp.
References MusicClickedLabel::clicked(), currentItemClicked(), HEIGHT_LABEL_SIZE, MusicUIObject::MQSSColorStyle09, and WIDTH_LABEL_SIZE.
Member Function Documentation
void MusicArtistListQueryItemWidget::currentItemClicked (const MusicResultsItem & item) signal
Current item clicked.
void MusicArtistListQueryItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 33 of file musicartistlistquerywidget.cpp.
References m_itemData.
Referenced by MusicArtistListQueryItemWidget().
void MusicArtistListQueryItemWidget::setMusicResultsItem (const MusicResultsItem & item)
Set music results item.
Definition at line 26 of file musicartistlistquerywidget.cpp.
References MusicUtils::Widget::elidedText(), m_itemData, MusicResultsItem::m_name, and WIDTH_LABEL_SIZE.
Referenced by MusicArtistListQueryWidget::createArtistListItem().
Member Data Documentation
MusicResultsItem MusicArtistListQueryItemWidget::m_itemData protected
Definition at line 61 of file musicartistlistquerywidget.h.
Referenced by currentItemClicked(), and setMusicResultsItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistlistquerywidget.cpp