TTKMusicplayer: MusicDownLoadQueryWYMovieThread Class Reference
MusicDownLoadQueryWYMovieThread Class Reference
The class to wangyi mv query download data from net.
#include <musicdownloadquerywymoviethread.h>
Public Slots
virtual void downLoadFinished () override
void pageDownLoadFinished ()
void singleDownLoadFinished ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownLoadQueryWYMovieThread (QObject *parent=0)
QJson import.
virtual void startToSearch (QueryType type, const QString &text) override
virtual void startToPage (int offset) override
virtual void startToSingleSearch (const QString &text) override
Public Member Functions inherited from MusicDownLoadQueryMovieThread
MusicDownLoadQueryMovieThread (QObject *parent=0)
virtual void startToSearch (const QString &movie)
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
const MusicObject::MusicSongInformations & getMusicSongInfos () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryMovieThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Member Functions
void startMVListQuery (int id)
void getArtistMvsCount (int id)
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
QString mapQueryServerString () const
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDownLoadQueryMovieThread
void createMovieInfoItem (const MusicPlaylistItem &item)
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItems (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to wangyi mv query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadquerywymoviethread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryWYMovieThread::MusicDownLoadQueryWYMovieThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 10 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::m_queryServer.
Member Function Documentation
void MusicDownLoadQueryWYMovieThread::downLoadFinished () override virtual slot
Download data from net finished.
Clear origin items
Empty the last search to songsInfo
extra yyt movie
Definition at line 92 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicSemaphoreLoop::exec(), getClassName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), MusicNetworkAbstract::Init, MusicDownLoadQueryThreadAbstract::m_currentType, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_queryExtraMovie, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicNetworkAbstract::m_stateCode, MusicDownLoadQueryThreadAbstract::MovieQuery, QJson::Parser::parse(), startMVListQuery(), and MusicDownLoadQueryYYTThread::startToSearch().
Referenced by startToSearch().
void MusicDownLoadQueryWYMovieThread::getArtistMvsCount (int id) protected
Get artist mvs count.
Definition at line 306 of file musicdownloadquerywymoviethread.cpp.
References MusicSemaphoreLoop::exec(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MU_MAX, QJson::Parser::parse(), WY_AR_MV_DATA_N_URL, and WY_AR_MV_N_URL.
Referenced by pageDownLoadFinished().
QString MusicDownLoadQueryWYMovieThread::getClassName () static
Get class object name.
Definition at line 16 of file musicdownloadquerywymoviethread.cpp.
Referenced by downLoadFinished(), pageDownLoadFinished(), singleDownLoadFinished(), startToPage(), startToSearch(), and startToSingleSearch().
void MusicDownLoadQueryWYMovieThread::pageDownLoadFinished () slot
Download page data from net finished.
Get all the data obtained by request
Definition at line 156 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadQueryMovieThread::createMovieInfoItem(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getArtistMvsCount(), getClassName(), MusicNetworkAbstract::Init, MusicPlaylistItem::m_coverUrl, MusicPlaylistItem::m_id, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicPlaylistItem::m_name, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicNetworkAbstract::m_stateCode, MusicPlaylistItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToPage().
void MusicDownLoadQueryWYMovieThread::singleDownLoadFinished () slot
Download single data from net finished.
Clear origin items
Empty the last search to songsInfo
Definition at line 211 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_searchText, MusicNetworkAbstract::m_stateCode, and startMVListQuery().
Referenced by startToSingleSearch().
void MusicDownLoadQueryWYMovieThread::startMVListQuery (int id) protected
Start to search mv list by id.
Definition at line 232 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicSemaphoreLoop::exec(), MusicUtils::Core::fileSuffix(), MusicDownLoadQueryThreadAbstract::findUrlFileSize(), MusicNetworkAbstract::Init, key, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songAttrs, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicObject::MusicSongAttribute::m_url, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MB_1000, MB_250, MB_500, MB_750, MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), QJson::Parser::parse(), WY_SONG_MV_N_URL, and WY_SONG_MV_NDT_URL.
Referenced by downLoadFinished(), and singleDownLoadFinished().
void MusicDownLoadQueryWYMovieThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 48 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), pageDownLoadFinished(), MusicNetworkAbstract::replyError(), WY_AR_MV_DATA_N_URL, and WY_AR_MV_N_URL.
void MusicDownLoadQueryWYMovieThread::startToSearch (QueryType type, const QString & text) override virtual
Start to search data from name and type.
Implements MusicDownLoadQueryThreadAbstract.
Definition at line 21 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicDownLoadQueryThreadAbstract::m_currentType, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicDownLoadWYInterface::makeTokenQueryQequest(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicUtils::Core::toUtf8(), WY_SONG_SEARCH_URL, and WY_SONG_SQUERY_URL.
void MusicDownLoadQueryWYMovieThread::startToSingleSearch (const QString & text) override virtual
Start to search data by given id.
Reimplemented from MusicDownLoadQueryThreadAbstract.
Definition at line 77 of file musicdownloadquerywymoviethread.cpp.
References MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_searchText, MT_MS, and singleDownLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicdownloadquerywymoviethread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicdownloadquerywymoviethread.cpp