TTKMusicplayer: MusicNetworkAbstract Class Reference
MusicNetworkAbstract Class Reference abstract
The class of abstract downloading data.
#include <musicnetworkabstract.h>
Public Types
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Public Slots
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of abstract downloading data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicnetworkabstract.h.
Member Typedef Documentation
typedef enum MusicNetworkAbstract::StateCode MusicNetworkAbstract::StateCode
Member Enumeration Documentation
enum MusicNetworkAbstract::StateCode
Enumerator
Init
Network state init
Success
Network state success
Error
Network state error
UnKnow
Network state unknow
Definition at line 33 of file musicnetworkabstract.h.
Constructor & Destructor Documentation
MusicNetworkAbstract::MusicNetworkAbstract (QObject * parent = 0) explicit
Object contsructor.
Definition at line 3 of file musicnetworkabstract.cpp.
References Init, m_interrupt, m_manager, m_reply, and m_stateCode.
MusicNetworkAbstract::~MusicNetworkAbstract () virtual
Definition at line 12 of file musicnetworkabstract.cpp.
References deleteAll(), m_stateCode, and Success.
Member Function Documentation
void MusicNetworkAbstract::deleteAll () virtual
Release the network object.
Reimplemented in MusicDownLoadThreadAbstract, MusicDJRadioThreadAbstract, MusicIdentifySongsThread, MusicAuthenticationThread, MusicDownLoadPagingThread, MusicQQBackgroundThread, and MusicTranslationThreadAbstract.
Definition at line 23 of file musicnetworkabstract.cpp.
References m_manager, and m_reply.
Referenced by MusicDownLoadThreadAbstract::deleteAll(), MusicRadioSongsThread::downLoadFinished(), MusicRadioPlayListThread::downLoadFinished(), MusicDownloadCounterPVThread::downLoadFinished(), MusicDownloadSourceThread::downLoadFinished(), MusicRadioChannelThread::downLoadFinished(), MusicDownloadSourceThread::replyError(), replyError(), MusicDownloadSourceThread::sslErrors(), sslErrors(), MusicDownloadCounterPVThread::~MusicDownloadCounterPVThread(), MusicDownloadSourceThread::~MusicDownloadSourceThread(), ~MusicNetworkAbstract(), MusicRadioChannelThread::~MusicRadioChannelThread(), MusicRadioPlayListThread::~MusicRadioPlayListThread(), MusicRadioSongsThread::~MusicRadioSongsThread(), and MusicRadioThreadAbstract::~MusicRadioThreadAbstract().
void MusicNetworkAbstract::downLoadDataChanged (const QString & data) signal
Send download data from net.
Referenced by MusicKWBackgroundThread::downLoadDataFinished(), MusicMVRadioCategoryThread::downLoadFinished(), MusicMVRadioProgramThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicKGDiscoverListThread::downLoadFinished(), MusicQQDiscoverListThread::downLoadFinished(), MusicBDDiscoverListThread::downLoadFinished(), MusicKWDiscoverListThread::downLoadFinished(), MusicBDArtistSimilarThread::downLoadFinished(), MusicKGSongSuggestThread::downLoadFinished(), MusicXMSongSuggestThread::downLoadFinished(), MusicTextDownLoadThread::downLoadFinished(), MusicXMTextDownLoadThread::downLoadFinished(), MusicQQArtistSimilarThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicQQSongSuggestThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicDJRadioCategoryThread::downLoadFinished(), MusicKWArtistSimilarThread::downLoadFinished(), MusicBDSongSuggestThread::downLoadFinished(), MusicKWSongSuggestThread::downLoadFinished(), MusicKWTextDownLoadThread::downLoadFinished(), MusicKGArtistSimilarThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicXMArtistSimilarThread::downLoadFinished(), MusicXMDiscoverListThread::downLoadFinished(), MusicWYDiscoverListThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicWYArtistSimilarThread::downLoadFinished(), MusicWYAuthenticationThread::downLoadFinished(), MusicWYSongSuggestThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicKGSongCommentsThread::downLoadFinished(), MusicQQSongCommentsThread::downLoadFinished(), MusicKWSongCommentsThread::downLoadFinished(), MusicBDSongCommentsThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicRadioSongsThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownloadCounterPVThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicRadioPlayListThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicWYSongCommentsThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicXMSongCommentsThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDataTagDownloadThread::downLoadFinished(), MusicDJRadioProgramThread::downLoadFinished(), MusicRadioChannelThread::downLoadFinished(), MusicDataDownloadThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicIdentifySongsThread::downLoadFinished(), MusicDownloadQueueCache::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicQQPlaylistCommentsThread::downLoadFinished(), MusicBDPlaylistCommentsThread::downLoadFinished(), MusicKWPlaylistCommentsThread::downLoadFinished(), MusicKGPlaylistCommentsThread::downLoadFinished(), MusicXMPlaylistCommentsThread::downLoadFinished(), MusicWYPlaylistCommentsThread::downLoadFinished(), MusicQQBackgroundThread::downLoadUrlFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::pageDownLoadFinished(), MusicDownLoadQueryXMMovieThread::pageDownLoadFinished(), MusicDownLoadThreadAbstract::replyError(), replyError(), MusicDownLoadQueryKGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryBDAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKWAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryXMAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryWYAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), MusicDownLoadThreadAbstract::sslErrors(), sslErrors(), MusicDownloadQueueCache::startOrderImageQueue(), MusicKWTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicDataDownloadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicDataTagDownloadThread::startToDownload(), MusicBDSongCommentsThread::startToSearch(), MusicQQSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicXMSongCommentsThread::startToSearch(), and MusicWYSongCommentsThread::startToSearch().
virtual void MusicNetworkAbstract::downLoadFinished () pure virtual slot
Download data from net finished. Subclass should implement this function.
Referenced by MusicMVRadioThreadAbstract::startToSearch().
QString MusicNetworkAbstract::getClassName () static
Get class object name.
Definition at line 18 of file musicnetworkabstract.cpp.
const QVariantMap& MusicNetworkAbstract::getRawData () const inline
Get the current raw data.
Definition at line 73 of file musicnetworkabstract.h.
Referenced by MusicQQSongCommentsThread::startToSearch().
bool MusicNetworkAbstract::networkAbort () inline
Get network block state.
Definition at line 64 of file musicnetworkabstract.h.
void MusicNetworkAbstract::rawDataChanged (const QVariantMap & data) signal
Send raw data changed.
void MusicNetworkAbstract::replyError (QNetworkReply::NetworkError error) virtual slot
Download reply error.
Definition at line 37 of file musicnetworkabstract.cpp.
References deleteAll(), downLoadDataChanged(), and M_LOGGER_ERROR.
Referenced by MusicQQBackgroundThread::downLoadUrl(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDJRadioCategoryThread::startToDownload(), MusicRadioSongsThread::startToDownload(), MusicWYTranslationThread::startToDownload(), MusicRadioPlayListThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicRadioChannelThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicTranslationThread::startToDownload(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicBDDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicDownLoadQueryYYTThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicMVRadioThreadAbstract::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), and MusicDownLoadQueryKWThread::startToSingleSearch().
void MusicNetworkAbstract::setNetworkAbort (bool a) inline
Set network block state.
Definition at line 60 of file musicnetworkabstract.h.
void MusicNetworkAbstract::setRawData (const QVariantMap & data) inline
Set the current raw data.
Definition at line 69 of file musicnetworkabstract.h.
Referenced by MusicWebMusicRadioWidget::addListWidgetItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), and MusicLrcAnalysis::getTranslatedLrc().
void MusicNetworkAbstract::setSslConfiguration (QNetworkRequest * request, QSslSocket::PeerVerifyMode m = QSslSocket::VerifyNone) protected
Set request ssl configuration.
Definition at line 69 of file musicnetworkabstract.cpp.
Referenced by MusicQQBackgroundThread::downLoadUrl(), MusicKWArtistSimilarThread::getArtistIdName(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), MusicDownLoadQueryThreadAbstract::getUrlFileSize(), MusicDownloadQueueCache::MusicDownloadQueueCache(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicDataDownloadThread::startRequest(), MusicWYTextDownLoadThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicDownloadSourceThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicDJRadioCategoryThread::startToDownload(), MusicWYTranslationThread::startToDownload(), MusicRadioSongsThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicRadioPlayListThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicRadioChannelThread::startToDownload(), MusicIdentifySongsThread::startToDownload(), MusicTranslationThread::startToDownload(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicBDDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicDownLoadQueryYYTThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicMVRadioThreadAbstract::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), and MusicDownLoadQueryKWThread::startToSingleSearch().
void MusicNetworkAbstract::sslErrors (QNetworkReply * reply, const QList< QSslError > & errors) virtual slot
Download ssl reply error.
Definition at line 45 of file musicnetworkabstract.cpp.
References deleteAll(), downLoadDataChanged(), and sslErrorsString().
Referenced by MusicDJRadioThreadAbstract::MusicDJRadioThreadAbstract(), MusicDownLoadPagingThread::MusicDownLoadPagingThread(), MusicIdentifySongsThread::MusicIdentifySongsThread(), MusicQQBackgroundThread::MusicQQBackgroundThread(), MusicTranslationThreadAbstract::MusicTranslationThreadAbstract(), MusicRadioSongsThread::startToDownload(), MusicRadioPlayListThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), and MusicRadioChannelThread::startToDownload().
void MusicNetworkAbstract::sslErrorsString (QNetworkReply * reply, const QList< QSslError > & errors) slot
Download ssl reply error strings.
Definition at line 52 of file musicnetworkabstract.cpp.
References M_LOGGER_ERROR.
Referenced by MusicDownloadSourceThread::sslErrors(), MusicDownLoadThreadAbstract::sslErrors(), and sslErrors().
Member Data Documentation
volatile bool MusicNetworkAbstract::m_interrupt protected
Definition at line 114 of file musicnetworkabstract.h.
Referenced by MusicMVRadioCategoryThread::downLoadFinished(), MusicMVRadioProgramThread::downLoadFinished(), MusicQQDiscoverListThread::downLoadFinished(), MusicBDDiscoverListThread::downLoadFinished(), MusicKGDiscoverListThread::downLoadFinished(), MusicKWDiscoverListThread::downLoadFinished(), MusicBDArtistSimilarThread::downLoadFinished(), MusicKGArtistSimilarThread::downLoadFinished(), MusicQQArtistSimilarThread::downLoadFinished(), MusicKGSongSuggestThread::downLoadFinished(), MusicQQSongSuggestThread::downLoadFinished(), MusicDJRadioCategoryThread::downLoadFinished(), MusicBDSongSuggestThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicKWArtistSimilarThread::downLoadFinished(), MusicKWSongSuggestThread::downLoadFinished(), MusicXMArtistSimilarThread::downLoadFinished(), MusicXMSongSuggestThread::downLoadFinished(), MusicWYDiscoverListThread::downLoadFinished(), MusicXMDiscoverListThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicWYArtistSimilarThread::downLoadFinished(), MusicWYAuthenticationThread::downLoadFinished(), MusicWYSongSuggestThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicKGSongCommentsThread::downLoadFinished(), MusicBDSongCommentsThread::downLoadFinished(), MusicQQSongCommentsThread::downLoadFinished(), MusicKWSongCommentsThread::downLoadFinished(), MusicDownLoadQueryBDArtistListThread::downLoadFinished(), MusicDownLoadQueryKWArtistListThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKGArtistListThread::downLoadFinished(), MusicDownLoadQueryXMArtistListThread::downLoadFinished(), MusicDownLoadQueryQQArtistListThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWYArtistListThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicWYSongCommentsThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicXMSongCommentsThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDJRadioProgramThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicQQPlaylistCommentsThread::downLoadFinished(), MusicKGPlaylistCommentsThread::downLoadFinished(), MusicBDPlaylistCommentsThread::downLoadFinished(), MusicKWPlaylistCommentsThread::downLoadFinished(), MusicWYPlaylistCommentsThread::downLoadFinished(), MusicXMPlaylistCommentsThread::downLoadFinished(), MusicDownLoadQueryThreadAbstract::findUrlFileSize(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicNetworkAbstract(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::pageDownLoadFinished(), MusicDownLoadQueryXMMovieThread::pageDownLoadFinished(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryKGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKWAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryWYAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryXMAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryBDAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), MusicDJRadioCategoryThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicQQDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicMVRadioThreadAbstract::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWMovieThread::startToSingleSearch(), MusicDownLoadQueryQQMovieThread::startToSingleSearch(), MusicDownLoadQueryBDThread::startToSingleSearch(), MusicDownLoadQueryBDMovieThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryKGMovieThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryWYMovieThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), MusicDownLoadQueryKWThread::startToSingleSearch(), and MusicDownLoadQueryXMMovieThread::startToSingleSearch().
QNetworkAccessManager* MusicNetworkAbstract::m_manager protected
Definition at line 116 of file musicnetworkabstract.h.
Referenced by deleteAll(), MusicQQBackgroundThread::downLoadDataFinished(), MusicMVRadioCategoryThread::downLoadFinished(), MusicMVRadioProgramThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicKGArtistSimilarThread::downLoadFinished(), MusicXMArtistSimilarThread::downLoadFinished(), MusicXMSongSuggestThread::downLoadFinished(), MusicKGSongSuggestThread::downLoadFinished(), MusicQQArtistSimilarThread::downLoadFinished(), MusicQQSongSuggestThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicBDArtistSimilarThread::downLoadFinished(), MusicBDSongSuggestThread::downLoadFinished(), MusicKWArtistSimilarThread::downLoadFinished(), MusicKWSongSuggestThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicWYArtistSimilarThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicWYAuthenticationThread::downLoadFinished(), MusicWYSongSuggestThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryQQArtistListThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKWArtistListThread::downLoadFinished(), MusicDownLoadQueryKGArtistListThread::downLoadFinished(), MusicDownLoadQueryBDArtistListThread::downLoadFinished(), MusicDownLoadQueryXMArtistListThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWYArtistListThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownloadQueueCache::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicQQBackgroundThread::downLoadUrl(), MusicQQBackgroundThread::downLoadUrlFinished(), MusicDownLoadQueryThreadAbstract::findUrlFileSize(), MusicKWArtistSimilarThread::getArtistIdName(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicKWArtistSimilarThread::getArtistNameById(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQPlaylistThread::getMoreDetails(), MusicDownLoadQueryKWPlaylistThread::getMorePlaylistDetails(), MusicDownLoadQueryQQMovieThread::getMovieKey(), MusicDownLoadQueryKGPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryBDPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryQQPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryKWPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), MusicAuthenticationThread::MusicAuthenticationThread(), MusicDJRadioThreadAbstract::MusicDJRadioThreadAbstract(), MusicDownLoadPagingThread::MusicDownLoadPagingThread(), MusicDownloadQueueCache::MusicDownloadQueueCache(), MusicIdentifySongsThread::MusicIdentifySongsThread(), MusicNetworkAbstract(), MusicQQBackgroundThread::MusicQQBackgroundThread(), MusicTranslationThreadAbstract::MusicTranslationThreadAbstract(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::pageDownLoadFinished(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryXMMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDLearnThread::readFromMusicLrcAttribute(), MusicMVRadioProgramThread::readFromMusicMVAttribute(), MusicDownLoadQueryYYTThread::readFromMusicMVAttribute(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryXMMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeYYT(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryKGMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryKWMovieThread::readFromMusicMVInfo(), MusicDownLoadQueryBDLearnThread::readFromMusicSongAttribute(), MusicDownLoadQueryKGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryBDAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryKWAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryWYAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryXMAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), MusicDownloadQueueCache::startDownload(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicDataDownloadThread::startRequest(), MusicTextDownLoadThread::startToDownload(), MusicDownloadSourceThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicQQTextDownLoadThread::startToDownload(), MusicDJRadioCategoryThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicDataDownloadThread::startToDownload(), MusicRadioSongsThread::startToDownload(), MusicWYTranslationThread::startToDownload(), MusicRadioPlayListThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicDataTagDownloadThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicRadioChannelThread::startToDownload(), MusicIdentifySongsThread::startToDownload(), MusicTranslationThread::startToDownload(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicDownLoadQueryYYTThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicMVRadioThreadAbstract::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryBDThread::startToSearch(), MusicDownLoadQueryQQThread::startToSearch(), MusicDownLoadQueryWYThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryXMThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryKGThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryKWThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryBDAlbumThread::startToSingleSearch(), MusicDownLoadQueryQQAlbumThread::startToSingleSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWMovieThread::startToSingleSearch(), MusicDownLoadQueryQQMovieThread::startToSingleSearch(), MusicDownLoadQueryKGMovieThread::startToSingleSearch(), MusicDownLoadQueryQQThread::startToSingleSearch(), MusicDownLoadQueryBDThread::startToSingleSearch(), MusicDownLoadQueryBDMovieThread::startToSingleSearch(), MusicDownLoadQueryWYMovieThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), MusicDownLoadQueryKGThread::startToSingleSearch(), MusicDownLoadQueryKWThread::startToSingleSearch(), and MusicDownLoadQueryXMMovieThread::startToSingleSearch().
QVariantMap MusicNetworkAbstract::m_rawData protected
Definition at line 112 of file musicnetworkabstract.h.
Referenced by MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistListThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownloadSourceThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownloadSourceThread::replyError(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownloadSourceThread::sslErrors(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicBDSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicQQSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicWYSongCommentsThread::startToSearch(), MusicXMSongCommentsThread::startToSearch(), MusicQQPlaylistCommentsThread::startToSearch(), MusicBDPlaylistCommentsThread::startToSearch(), MusicKGPlaylistCommentsThread::startToSearch(), MusicKWPlaylistCommentsThread::startToSearch(), MusicXMPlaylistCommentsThread::startToSearch(), and MusicWYPlaylistCommentsThread::startToSearch().
QNetworkReply* MusicNetworkAbstract::m_reply protected
Definition at line 115 of file musicnetworkabstract.h.
Referenced by MusicDownloadQueueCache::abort(), MusicTranslationThreadAbstract::deleteAll(), MusicQQBackgroundThread::deleteAll(), MusicDownLoadPagingThread::deleteAll(), MusicAuthenticationThread::deleteAll(), deleteAll(), MusicIdentifySongsThread::deleteAll(), MusicDJRadioThreadAbstract::deleteAll(), MusicQQBackgroundThread::downLoadDataFinished(), MusicMVRadioCategoryThread::downLoadFinished(), MusicMVRadioProgramThread::downLoadFinished(), MusicQQDiscoverListThread::downLoadFinished(), MusicBDDiscoverListThread::downLoadFinished(), MusicKWDiscoverListThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicKGDiscoverListThread::downLoadFinished(), MusicQQSongSuggestThread::downLoadFinished(), MusicQQTextDownLoadThread::downLoadFinished(), MusicDJRadioCategoryThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicKWArtistSimilarThread::downLoadFinished(), MusicBDSongSuggestThread::downLoadFinished(), MusicKWSongSuggestThread::downLoadFinished(), MusicBDArtistSimilarThread::downLoadFinished(), MusicKWTextDownLoadThread::downLoadFinished(), MusicWYTextDownLoadThread::downLoadFinished(), MusicXMArtistSimilarThread::downLoadFinished(), MusicXMSongSuggestThread::downLoadFinished(), MusicXMTextDownLoadThread::downLoadFinished(), MusicTextDownLoadThread::downLoadFinished(), MusicKGArtistSimilarThread::downLoadFinished(), MusicKGSongSuggestThread::downLoadFinished(), MusicQQArtistSimilarThread::downLoadFinished(), MusicWYDiscoverListThread::downLoadFinished(), MusicWYTranslationThread::downLoadFinished(), MusicXMDiscoverListThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicWYArtistSimilarThread::downLoadFinished(), MusicWYAuthenticationThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicWYSongSuggestThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicBDSongCommentsThread::downLoadFinished(), MusicKWSongCommentsThread::downLoadFinished(), MusicKGSongCommentsThread::downLoadFinished(), MusicQQSongCommentsThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryKGArtistListThread::downLoadFinished(), MusicRadioSongsThread::downLoadFinished(), MusicDownLoadQueryXMArtistListThread::downLoadFinished(), MusicDownLoadQueryBDArtistListThread::downLoadFinished(), MusicDownLoadQueryQQArtistListThread::downLoadFinished(), MusicDownLoadQueryKWArtistListThread::downLoadFinished(), MusicRadioPlayListThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWYArtistListThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicWYSongCommentsThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicXMSongCommentsThread::downLoadFinished(), MusicDownloadCounterPVThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownloadSourceThread::downLoadFinished(), MusicDJRadioProgramThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicRadioChannelThread::downLoadFinished(), MusicDataDownloadThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::downLoadFinished(), MusicTranslationThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicIdentifySongsThread::downLoadFinished(), MusicDownloadQueueCache::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicKWPlaylistCommentsThread::downLoadFinished(), MusicBDPlaylistCommentsThread::downLoadFinished(), MusicKGPlaylistCommentsThread::downLoadFinished(), MusicQQPlaylistCommentsThread::downLoadFinished(), MusicWYPlaylistCommentsThread::downLoadFinished(), MusicXMPlaylistCommentsThread::downLoadFinished(), MusicDataDownloadThread::downLoadReadyRead(), MusicQQBackgroundThread::downLoadUrl(), MusicQQBackgroundThread::downLoadUrlFinished(), MusicDownloadQueueCache::errorSlot(), MusicAuthenticationThread::MusicAuthenticationThread(), MusicNetworkAbstract(), MusicTranslationThreadAbstract::MusicTranslationThreadAbstract(), MusicDownLoadQueryQQMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKWMovieThread::pageDownLoadFinished(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryKGMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::pageDownLoadFinished(), MusicDownLoadQueryXMMovieThread::pageDownLoadFinished(), MusicDownloadQueueCache::readyReadSlot(), MusicDownloadQueueCache::startDownload(), MusicDataDownloadThread::startRequest(), MusicQQTextDownLoadThread::startToDownload(), MusicTextDownLoadThread::startToDownload(), MusicDJRadioCategoryThread::startToDownload(), MusicKWTextDownLoadThread::startToDownload(), MusicXMTextDownLoadThread::startToDownload(), MusicWYTextDownLoadThread::startToDownload(), MusicDownloadSourceThread::startToDownload(), MusicRadioSongsThread::startToDownload(), MusicWYTranslationThread::startToDownload(), MusicRadioPlayListThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicQQBackgroundThread::startToDownload(), MusicDownloadCounterPVThread::startToDownload(), MusicDataTagDownloadThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicRadioChannelThread::startToDownload(), MusicIdentifySongsThread::startToDownload(), MusicTranslationThread::startToDownload(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicKWSongCommentsThread::startToPage(), MusicQQSongCommentsThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicKGSongCommentsThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicBDSongCommentsThread::startToPage(), MusicDownLoadQueryQQThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryBDThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryKGThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicDownLoadQueryKWThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicKWPlaylistCommentsThread::startToPage(), MusicBDPlaylistCommentsThread::startToPage(), MusicKGPlaylistCommentsThread::startToPage(), MusicQQPlaylistCommentsThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicDownLoadQueryYYTThread::startToSearch(), MusicKWDiscoverListThread::startToSearch(), MusicKGDiscoverListThread::startToSearch(), MusicBDDiscoverListThread::startToSearch(), MusicQQDiscoverListThread::startToSearch(), MusicXMSongSuggestThread::startToSearch(), MusicKGArtistSimilarThread::startToSearch(), MusicDownLoadQueryBDLearnThread::startToSearch(), MusicMVRadioThreadAbstract::startToSearch(), MusicKWArtistSimilarThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicQQSongSuggestThread::startToSearch(), MusicKGSongSuggestThread::startToSearch(), MusicBDArtistSimilarThread::startToSearch(), MusicBDSongSuggestThread::startToSearch(), MusicXMArtistSimilarThread::startToSearch(), MusicKWSongSuggestThread::startToSearch(), MusicQQArtistSimilarThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicDownLoadQueryKWAlbumThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryQQAlbumThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryKWRecommendThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryKGRecommendThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryBDAlbumThread::startToSearch(), MusicDownLoadQueryQQToplistThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryKGToplistThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryBDToplistThread::startToSearch(), MusicDownLoadQueryKWToplistThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), and MusicDownLoadQueryXMMovieThread::startToSearch().
StateCode MusicNetworkAbstract::m_stateCode protected
Definition at line 113 of file musicnetworkabstract.h.
Referenced by MusicMVRadioProgramThread::downLoadFinished(), MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryThreadAbstract::findUrlFileSize(), MusicDownLoadQueryWYMovieThread::getArtistMvsCount(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYPlaylistThread::getPlaylistInfo(), MusicDownLoadQueryXMPlaylistThread::getPlaylistInfo(), MusicDJRadioProgramCategoryThread::getProgramInfo(), MusicNetworkAbstract(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryQQMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::startMVListQuery(), MusicDJRadioCategoryThread::startToDownload(), MusicWYAuthenticationThread::startToDownload(), MusicDJRadioProgramThread::startToDownload(), MusicDownLoadQueryWYThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicXMSongCommentsThread::startToPage(), MusicWYSongCommentsThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryXMThread::startToPage(), MusicWYPlaylistCommentsThread::startToPage(), MusicXMPlaylistCommentsThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicXMDiscoverListThread::startToSearch(), MusicWYDiscoverListThread::startToSearch(), MusicDownLoadQueryXMRecommendThread::startToSearch(), MusicDownLoadQueryWYAlbumThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicWYArtistSimilarThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicWYSongSuggestThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryXMToplistThread::startToSearch(), MusicDownLoadQueryWYToplistThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYAlbumThread::startToSingleSearch(), MusicDownLoadQueryWYThread::startToSingleSearch(), MusicDownLoadQueryXMThread::startToSingleSearch(), and ~MusicNetworkAbstract().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicnetworkabstract.h
TTKModule/TTKCore/musicNetworkKits/musicnetworkabstract.cpp