TTKMusicplayer: MusicLrcContainerForInline Class Reference
MusicLrcContainerForInline Class Reference
The class of the inline lrc container.
#include <musiclrccontainerforinline.h>
Public Slots
void lrcSizeChanged (QAction *action)
void lrcTimeSpeedChanged (QAction *action)
void revertLrcTimeSpeed ()
void saveLrcTimeChanged ()
void artBackgroundChanged ()
void showArtBackgroundUploadedWidget ()
void lrcOpenFileDir () const
void lrcCopyClipboard () const
void showLocalLinkWidget ()
void showSongCommentsWidget ()
void showSoundKMicroWidget ()
void showLrcPosterWidget ()
Public Slots inherited from MusicLrcContainer
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
void showLrcErrorWidget ()
Signals
void updateCurrentTime (qint64 time)
void artBgHasChanged ()
Signals inherited from MusicLrcContainer
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Public Member Functions
MusicLrcContainerForInline (QWidget *parent=0)
virtual ~MusicLrcContainerForInline ()
virtual void startTimerClock () override
virtual void stopLrcMask () override
virtual void setSettingParameter () override
void updateCurrentLrc (qint64 time)
bool transLyricFileToTime (const QString &lrcFileName)
QString text () const
qint64 setSongSpeedChanged (qint64 time)
bool findText (qint64 total, QString &pre, QString &last, qint64 &interval) const
void setLrcDisplayExpand (bool expand)
bool lrcDisplayExpand () const
bool artBackgroundIsShow () const
void setLrcSize (int size)
int getLrcSize () const
void resizeWindow ()
void createFloatPlayWidget ()
void lrcWidgetShowFullScreen ()
Public Member Functions inherited from MusicLrcContainer
MusicLrcContainer (QWidget *parent=0)
virtual ~MusicLrcContainer ()
void setLinearGradientColor (MusicLrcColor::LrcColorType lrcColorType)
void setLinearGradientColor (const MusicLrcColor &color)
QString getCurrentSongName () const
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 getTotalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * getLrcAnalysisModel () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicLrcContainer
static QString getClassName ()
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void resizeEvent (QResizeEvent *event) override
void createColorMenu (QMenu &menu)
void revertLrcTimeSpeed (qint64 pos)
void createNoLrcCurrentInfo ()
void showNoLrcCurrentInfo ()
void initCurrentLrc (const QString &str)
void initFunctionLabel ()
void setItemStyleSheet ()
void setItemStyleSheet (int index, int size, int transparent)
int mapLrcSizeProperty (int size)
void setLrcSizeProperty (int property)
void resizeWidth (int w, int h)
Protected Member Functions inherited from MusicLrcContainer
void clearAllMusicLRCManager ()
void setSettingParameter (const QString &t)
Protected Attributes
QPoint m_mousePressedAt
bool m_mouseLeftPressed
bool m_lrcChangeState
bool m_mouseMoved
int m_lrcChangeOffset
int m_lrcChangeDelta
bool m_lrcDisplayAll
bool m_showArtBackground
int m_animationFreshTime
int m_lrcSizeProperty
qint64 m_changeSpeedValue
QWidget * m_functionLabel
MusicLrcFloatWidget * m_lrcFloatWidget
MusicLrcFloatPlayWidget * m_floatPlayWidget
MusicClickedLabel * m_noLrcCurrentInfo
MusicLrcCommentsWidget * m_commentsWidget
MusicLrcTranslatedWidget * m_translatedWidget
MusicVLayoutAnimationWidget * m_layoutWidget
Protected Attributes inherited from MusicLrcContainer
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_musicLrcContainer
MusicLrcSearchWidget * m_musicLrcSearchWidget
Private Slots
void getTranslatedLrcFinished (const QString &data)
void musicSongMovieClicked ()
void updateAnimationLrc ()
Detailed Description
The class of the inline lrc container.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musiclrccontainerforinline.h.
Constructor & Destructor Documentation
MusicLrcContainerForInline::MusicLrcContainerForInline (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 35 of file musiclrccontainerforinline.cpp.
References MusicLayoutAnimationWidget::addWidget(), MusicLayoutAnimationWidget::connectTo(), createNoLrcCurrentInfo(), MusicLrcAnalysis::getLineMax(), initCurrentLrc(), initFunctionLabel(), m_animationFreshTime, m_changeSpeedValue, m_commentsWidget, MusicLrcContainer::m_containerType, m_floatPlayWidget, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, m_lrcChangeDelta, m_lrcChangeOffset, m_lrcChangeState, m_lrcDisplayAll, m_lrcFloatWidget, m_lrcSizeProperty, m_mouseLeftPressed, m_mouseMoved, MusicLrcContainer::m_musicLrcContainer, m_showArtBackground, m_translatedWidget, MUSIC_LRC_INLINE_MAX_LINE, and MusicLrcAnalysis::setLineMax().
MusicLrcContainerForInline::~MusicLrcContainerForInline () virtual
Definition at line 78 of file musiclrccontainerforinline.cpp.
References MusicLrcContainer::clearAllMusicLRCManager(), m_commentsWidget, m_floatPlayWidget, m_functionLabel, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, m_lrcFloatWidget, m_noLrcCurrentInfo, and m_translatedWidget.
Member Function Documentation
void MusicLrcContainerForInline::artBackgroundChanged () slot
The art background state has changed.
Definition at line 308 of file musiclrccontainerforinline.cpp.
References artBgHasChanged(), and m_showArtBackground.
Referenced by contextMenuEvent(), MusicLrcFloatSettingWidget::lrcArtBackgroundChanged(), and MusicLrcFloatSettingWidget::lrcMusicBackgroundChanged().
bool MusicLrcContainerForInline::artBackgroundIsShow () const inline
Get state of background is artist shown.
Definition at line 96 of file musiclrccontainerforinline.h.
Referenced by MusicLrcFloatSettingWidget::lrcArtBackgroundChanged(), and MusicLrcFloatSettingWidget::lrcMusicBackgroundChanged().
void MusicLrcContainerForInline::artBgHasChanged () signal
The art background state has changed emit.
Referenced by artBackgroundChanged(), and showArtBackgroundUploadedWidget().
void MusicLrcContainerForInline::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 411 of file musiclrccontainerforinline.cpp.
References artBackgroundChanged(), createColorMenu(), MusicLrcContainer::currentLrcCustom(), MusicLrcContainer::currentLrcUpdated(), MusicLrcAnalysis::getCurrentFileName(), MusicLeftAreaWidget::instance(), MusicTopAreaWidget::instance(), MusicLrcAnalysis::isEmpty(), MusicLrcContainer::linkLrcStateChanged(), lrcCopyClipboard(), lrcOpenFileDir(), lrcSizeChanged(), MusicSettingManager::LrcSizeChoiced, lrcTimeSpeedChanged(), lrcWidgetShowFullScreen(), M_BACKGROUND_PTR, MusicLrcContainer::m_linkLocalLrc, MusicLrcContainer::m_lrcAnalysis, M_SETTING_PTR, m_showArtBackground, MusicUIObject::MMenuStyle02, revertLrcTimeSpeed(), saveLrcTimeChanged(), MusicLrcContainer::searchMusicLrcs(), showArtBackgroundUploadedWidget(), showLocalLinkWidget(), MusicLrcContainer::showLrcErrorWidget(), MusicLrcContainer::showLrcMakedWidget(), and showLrcPosterWidget().
void MusicLrcContainerForInline::createColorMenu (QMenu & menu) protected
Create color menu.
Definition at line 641 of file musiclrccontainerforinline.cpp.
References MusicLrcContainer::changeCurrentLrcColor(), MusicLrcContainer::currentLrcCustom(), and M_SETTING_PTR.
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::createFloatPlayWidget ()
Create float play widget.
Definition at line 237 of file musiclrccontainerforinline.cpp.
References MusicLeftAreaWidget::instance(), m_floatPlayWidget, and MusicLrcFloatPlayWidget::resizeWindow().
void MusicLrcContainerForInline::createNoLrcCurrentInfo () protected
Create no lrc current information.
Definition at line 693 of file musiclrccontainerforinline.cpp.
References MusicObject::FT_Underline, m_noLrcCurrentInfo, MusicUIObject::MColorStyle06, MusicUtils::Widget::setLabelFontSize(), MusicUtils::Widget::setLabelFontStyle(), and MusicLrcContainer::showLrcMakedWidget().
Referenced by MusicLrcContainerForInline().
bool MusicLrcContainerForInline::findText (qint64 total, QString & pre, QString & last, qint64 & interval) const
Get current lrc and next lrc in container by current time.
Definition at line 183 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::findText(), MusicLrcContainer::m_currentTime, and MusicLrcContainer::m_lrcAnalysis.
QString MusicLrcContainerForInline::getClassName () static
Get class object name.
Definition at line 91 of file musiclrccontainerforinline.cpp.
int MusicLrcContainerForInline::getLrcSize () const
Get current lrc size.
Definition at line 214 of file musiclrccontainerforinline.cpp.
References MusicSettingManager::LrcSizeChoiced, and M_SETTING_PTR.
Referenced by MusicLrcFloatSettingWidget::lrcSizeLowChanged(), and MusicLrcFloatSettingWidget::lrcSizeUpChanged().
void MusicLrcContainerForInline::getTranslatedLrcFinished (const QString & data) private slot
Get translated lrc finished.
Definition at line 371 of file musiclrccontainerforinline.cpp.
References MusicLrcContainer::m_currentSongName, m_translatedWidget, MusicLrcTranslatedWidget::setPlainText(), and text().
void MusicLrcContainerForInline::initCurrentLrc (const QString & str) protected
Init current lrc when the first show.
Definition at line 716 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and MusicLrcContainer::m_musicLrcContainer.
Referenced by MusicLrcContainerForInline(), and resizeWidth().
void MusicLrcContainerForInline::initFunctionLabel () protected
Init function label widget.
Definition at line 725 of file musiclrccontainerforinline.cpp.
References m_functionLabel, MusicLrcContainer::m_lrcAnalysis, MusicUIObject::MKGInlineMessage, MusicUIObject::MKGInlineMicrophone, MusicUIObject::MKGInlineMovie, MusicUIObject::MKGInlineTranslation, musicSongMovieClicked(), showSongCommentsWidget(), and showSoundKMicroWidget().
Referenced by MusicLrcContainerForInline().
void MusicLrcContainerForInline::lrcCopyClipboard () const slot
Copy all lrcs to clipboard.
Definition at line 326 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getAllLrcString(), and MusicLrcContainer::m_lrcAnalysis.
Referenced by contextMenuEvent().
bool MusicLrcContainerForInline::lrcDisplayExpand () const inline
Get state of background is artist shown.
Definition at line 92 of file musiclrccontainerforinline.h.
void MusicLrcContainerForInline::lrcOpenFileDir () const slot
Open current lrc file location.
Definition at line 321 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getCurrentFileName(), MusicLrcContainer::m_lrcAnalysis, and MusicUtils::Url::openUrl().
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::lrcSizeChanged (QAction * action) slot
Set current lrc size by action.
Definition at line 261 of file musiclrccontainerforinline.cpp.
References setLrcSize().
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::lrcTimeSpeedChanged (QAction * action) slot
Set lrc time speed changed by action.
Definition at line 274 of file musiclrccontainerforinline.cpp.
References m_changeSpeedValue, MT_S2MS, and revertLrcTimeSpeed().
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::lrcWidgetShowFullScreen ()
Show full container or not.
Definition at line 248 of file musiclrccontainerforinline.cpp.
References MusicLeftAreaWidget::instance(), MusicLeftAreaWidget::isLrcWidgetShowFullScreen(), m_functionLabel, and MStatic_cast.
Referenced by contextMenuEvent().
int MusicLrcContainerForInline::mapLrcSizeProperty (int size) protected
Map lrc size property to line index.
Definition at line 859 of file musiclrccontainerforinline.cpp.
Referenced by mouseMoveEvent(), and setLrcSize().
void MusicLrcContainerForInline::mouseDoubleClickEvent (QMouseEvent * event) override protected virtual
Definition at line 635 of file musiclrccontainerforinline.cpp.
References MusicLeftAreaWidget::instance(), and MusicLeftAreaWidget::lrcWidgetShowFullScreen().
void MusicLrcContainerForInline::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 549 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::count(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), MusicLrcAnalysis::isValid(), LRC_CHANGED_OFFSET_LIMIT, MusicSettingManager::LrcSizeChoiced, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, m_lrcChangeDelta, m_lrcChangeOffset, m_lrcChangeState, m_mouseLeftPressed, m_mouseMoved, m_mousePressedAt, MusicLrcContainer::m_musicLrcContainer, M_SETTING_PTR, mapLrcSizeProperty(), MusicLrcAnalysis::setCurrentIndex(), setItemStyleSheet(), and MusicLayoutAnimationWidget::stop().
void MusicLrcContainerForInline::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 601 of file musiclrccontainerforinline.cpp.
References m_lrcChangeOffset, m_lrcChangeState, m_mouseLeftPressed, m_mouseMoved, and m_mousePressedAt.
void MusicLrcContainerForInline::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 615 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::isValid(), MusicLrcContainer::m_lrcAnalysis, m_mouseLeftPressed, m_mouseMoved, m_mousePressedAt, and updateCurrentTime().
void MusicLrcContainerForInline::musicSongMovieClicked () private slot
Video button clicked.
Definition at line 386 of file musiclrccontainerforinline.cpp.
References MusicLeftAreaWidget::instance(), MusicRightAreaWidget::instance(), MusicLeftAreaWidget::isLrcWidgetShowFullScreen(), MusicLeftAreaWidget::lrcWidgetShowFullScreen(), MusicLrcContainer::m_currentSongName, and MusicRightAreaWidget::musicVideoButtonSearched().
Referenced by initFunctionLabel().
void MusicLrcContainerForInline::paintEvent (QPaintEvent * event) override protected virtual
Definition at line 515 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::count(), MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getMiddle(), LRC_TIME_LABEL_POSITION, m_functionLabel, MusicLrcContainer::m_lrcAnalysis, m_mouseLeftPressed, and MusicTime::msecTime2LabelJustified().
void MusicLrcContainerForInline::resizeEvent (QResizeEvent * event) override protected virtual
Definition at line 543 of file musiclrccontainerforinline.cpp.
References resizeWindow().
void MusicLrcContainerForInline::resizeWidth (int w, int h) protected
Resize width bound by given width.
Definition at line 907 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), initCurrentLrc(), MusicLrcAnalysis::isEmpty(), m_commentsWidget, MusicLrcContainer::m_currentTime, m_floatPlayWidget, MusicLrcContainer::m_lrcAnalysis, m_lrcFloatWidget, MusicLrcContainer::m_musicLrcContainer, m_translatedWidget, MStatic_cast, MusicLrcFloatPlayWidget::resizeWindow(), MusicLrcFloatWidget::resizeWindow(), and showNoLrcCurrentInfo().
Referenced by resizeWindow().
void MusicLrcContainerForInline::resizeWindow ()
Resize window bound by widgte resize called.
Definition at line 219 of file musiclrccontainerforinline.cpp.
References MusicLeftAreaWidget::instance(), m_lrcDisplayAll, M_SETTING_PTR, resizeWidth(), MusicSettingManager::WidgetSize, WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), and setLrcSize().
void MusicLrcContainerForInline::revertLrcTimeSpeed () slot
Revert lrc time speed.
Definition at line 294 of file musiclrccontainerforinline.cpp.
References m_changeSpeedValue.
Referenced by contextMenuEvent(), and lrcTimeSpeedChanged().
void MusicLrcContainerForInline::revertLrcTimeSpeed (qint64 pos) protected
Revert lrc time speed by pos.
Definition at line 664 of file musiclrccontainerforinline.cpp.
References m_changeSpeedValue, MusicLrcContainer::m_currentTime, MusicLrcContainer::m_lrcAnalysis, MT_S2MS, MusicLrcAnalysis::revertLrcTime(), MusicToastLabel::setFontMargin(), MusicToastLabel::setFontSize(), setSongSpeedChanged(), MusicToastLabel::setText(), and updateCurrentLrc().
void MusicLrcContainerForInline::saveLrcTimeChanged () slot
Save lrc time changed to current lrc file.
Definition at line 303 of file musiclrccontainerforinline.cpp.
References MusicLrcContainer::m_lrcAnalysis, and MusicLrcAnalysis::saveLrcTimeChanged().
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::setItemStyleSheet () protected
Set per lrc line style sheet.
Definition at line 780 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getLineMax(), and MusicLrcContainer::m_lrcAnalysis.
Referenced by mouseMoveEvent(), setLrcSize(), and updateAnimationLrc().
void MusicLrcContainerForInline::setItemStyleSheet (int index, int size, int transparent) protected
Set per lrc line style sheet by index and size and transparent.
Definition at line 835 of file musiclrccontainerforinline.cpp.
References MusicLrcContainer::m_musicLrcContainer, M_SETTING_PTR, MStatic_cast, MusicUtils::String::readColorConfig(), MusicLrcManagerForInline::setFontSize(), MusicLrcManager::setFontTransparent(), MusicLrcContainer::setLinearGradientColor(), and MusicLrcManagerForInline::setTransparent().
void MusicLrcContainerForInline::setLrcDisplayExpand (bool expand) inline
Get state of background is artist shown.
Definition at line 88 of file musiclrccontainerforinline.h.
void MusicLrcContainerForInline::setLrcSize (int size)
Set current lrc size.
Definition at line 188 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getText(), MusicSettingManager::LrcSizeChoiced, MusicLrcContainer::m_lrcAnalysis, m_lrcSizeProperty, MusicLrcContainer::m_musicLrcContainer, M_SETTING_PTR, mapLrcSizeProperty(), resizeWindow(), MusicLrcAnalysis::setCurrentIndex(), setItemStyleSheet(), setLrcSizeProperty(), and startTimerClock().
Referenced by lrcSizeChanged(), MusicLrcFloatSettingWidget::lrcSizeLowChanged(), MusicLrcFloatSettingWidget::lrcSizeUpChanged(), and setSettingParameter().
void MusicLrcContainerForInline::setLrcSizeProperty (int property) protected
Set current lrc size property.
Definition at line 887 of file musiclrccontainerforinline.cpp.
References MusicLayoutAnimationWidget::addWidget(), m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, MUSIC_LRC_INLINE_MAX_LINE, MusicLayoutAnimationWidget::removeWidget(), and MusicLrcAnalysis::setLineMax().
Referenced by setLrcSize().
void MusicLrcContainerForInline::setSettingParameter () override virtual
Set setting parameter.
Reimplemented from MusicLrcContainer.
Definition at line 107 of file musiclrccontainerforinline.cpp.
References MusicSettingManager::LrcSizeChoiced, m_lrcChangeDelta, m_lrcSizeProperty, M_SETTING_PTR, setLrcSize(), and MusicLrcContainer::setSettingParameter().
qint64 MusicLrcContainerForInline::setSongSpeedChanged (qint64 time)
Set song speed by given time, return new time.
Definition at line 178 of file musiclrccontainerforinline.cpp.
References MusicLrcContainer::m_lrcAnalysis, and MusicLrcAnalysis::setSongSpeedChanged().
Referenced by revertLrcTimeSpeed().
void MusicLrcContainerForInline::showArtBackgroundUploadedWidget () slot
The art background has uploaded.
Definition at line 314 of file musiclrccontainerforinline.cpp.
References artBgHasChanged(), MusicLrcArtPhotoUploadWidget::exec(), and m_showArtBackground.
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::showLocalLinkWidget () slot
Show local link widget.
Definition at line 332 of file musiclrccontainerforinline.cpp.
References MusicLrcLocalLinkWidget::exec(), MusicLrcContainer::m_currentSongName, and MusicLrcLocalLinkWidget::setCurrentSongName().
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::showLrcPosterWidget () slot
Show lrc poster widget.
Definition at line 364 of file musiclrccontainerforinline.cpp.
References MusicLrcPosterWidget::exec(), MusicLrcAnalysis::getAllLrcList(), MusicLrcContainer::m_currentSongName, MusicLrcContainer::m_lrcAnalysis, and MusicLrcPosterWidget::setCurrentLrcs().
Referenced by contextMenuEvent().
void MusicLrcContainerForInline::showNoLrcCurrentInfo () protected
Show no lrc current information.
Definition at line 705 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and m_noLrcCurrentInfo.
Referenced by resizeWidth(), and transLyricFileToTime().
void MusicLrcContainerForInline::showSongCommentsWidget () slot
Show song comments widget.
Definition at line 339 of file musiclrccontainerforinline.cpp.
References MusicLrcCommentsWidget::initWidget(), m_commentsWidget, MusicLrcContainer::m_currentSongName, and MusicCommentsWidget::setCurrentSongName().
Referenced by initFunctionLabel().
void MusicLrcContainerForInline::showSoundKMicroWidget () slot
Show song KMicro widget.
Definition at line 354 of file musiclrccontainerforinline.cpp.
References MusicLeftAreaWidget::createSoundKMicroWidget(), MusicLeftAreaWidget::instance(), and MusicLrcContainer::m_currentSongName.
Referenced by initFunctionLabel().
void MusicLrcContainerForInline::startTimerClock () override virtual
Start timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 96 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and MusicLrcContainer::m_musicLrcContainer.
Referenced by setLrcSize().
void MusicLrcContainerForInline::stopLrcMask () override virtual
Stop timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 101 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getMiddle(), m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, and MusicLayoutAnimationWidget::stop().
QString MusicLrcContainerForInline::text () const
Get current lrc text in middle.
Definition at line 173 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and MusicLrcContainer::m_musicLrcContainer.
Referenced by getTranslatedLrcFinished().
bool MusicLrcContainerForInline::transLyricFileToTime (const QString & lrcFileName)
Analysis lyric file to map return the state.
hide error make lrc widget
Definition at line 132 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::LrcEmpty, m_layoutWidget, M_LOGGER_INFO, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, m_noLrcCurrentInfo, MusicLrcAnalysis::OpenFileFail, showNoLrcCurrentInfo(), MusicLayoutAnimationWidget::stop(), MusicLrcAnalysis::transKrcFileToTime(), and MusicLrcAnalysis::transLrcFileToTime().
void MusicLrcContainerForInline::updateAnimationLrc () private slot
Animation finished.
Definition at line 400 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), m_animationFreshTime, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, MusicLrcAnalysis::setCurrentIndex(), and setItemStyleSheet().
void MusicLrcContainerForInline::updateCurrentLrc (qint64 time)
Update current lrc by given time.
Definition at line 123 of file musiclrccontainerforinline.cpp.
References MusicLrcAnalysis::isValid(), m_animationFreshTime, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, m_mouseLeftPressed, and MusicVLayoutAnimationWidget::start().
Referenced by revertLrcTimeSpeed().
void MusicLrcContainerForInline::updateCurrentTime (qint64 time) signal
Update current play time when user adjust the progress.
Referenced by mouseReleaseEvent().
Member Data Documentation
int MusicLrcContainerForInline::m_animationFreshTime protected
Definition at line 255 of file musiclrccontainerforinline.h.
Referenced by MusicLrcContainerForInline(), updateAnimationLrc(), and updateCurrentLrc().
qint64 MusicLrcContainerForInline::m_changeSpeedValue protected
Definition at line 257 of file musiclrccontainerforinline.h.
Referenced by lrcTimeSpeedChanged(), MusicLrcContainerForInline(), and revertLrcTimeSpeed().
MusicLrcCommentsWidget* MusicLrcContainerForInline::m_commentsWidget protected
Definition at line 262 of file musiclrccontainerforinline.h.
Referenced by MusicLrcContainerForInline(), resizeWidth(), showSongCommentsWidget(), and ~MusicLrcContainerForInline().
MusicLrcFloatPlayWidget* MusicLrcContainerForInline::m_floatPlayWidget protected
Definition at line 260 of file musiclrccontainerforinline.h.
Referenced by createFloatPlayWidget(), MusicLrcContainerForInline(), resizeWidth(), and ~MusicLrcContainerForInline().
QWidget* MusicLrcContainerForInline::m_functionLabel protected
Definition at line 258 of file musiclrccontainerforinline.h.
Referenced by initFunctionLabel(), lrcWidgetShowFullScreen(), paintEvent(), and ~MusicLrcContainerForInline().
MusicVLayoutAnimationWidget* MusicLrcContainerForInline::m_layoutWidget protected
Definition at line 264 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), MusicLrcContainerForInline(), setLrcSizeProperty(), stopLrcMask(), transLyricFileToTime(), updateCurrentLrc(), and ~MusicLrcContainerForInline().
int MusicLrcContainerForInline::m_lrcChangeDelta protected
Definition at line 252 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), MusicLrcContainerForInline(), and setSettingParameter().
int MusicLrcContainerForInline::m_lrcChangeOffset protected
Definition at line 252 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and MusicLrcContainerForInline().
bool MusicLrcContainerForInline::m_lrcChangeState protected
Definition at line 251 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and MusicLrcContainerForInline().
bool MusicLrcContainerForInline::m_lrcDisplayAll protected
Definition at line 254 of file musiclrccontainerforinline.h.
Referenced by MusicLrcContainerForInline(), and resizeWindow().
MusicLrcFloatWidget* MusicLrcContainerForInline::m_lrcFloatWidget protected
Definition at line 259 of file musiclrccontainerforinline.h.
Referenced by MusicLrcContainerForInline(), resizeWidth(), and ~MusicLrcContainerForInline().
int MusicLrcContainerForInline::m_lrcSizeProperty protected
Definition at line 255 of file musiclrccontainerforinline.h.
Referenced by MusicLrcContainerForInline(), setLrcSize(), and setSettingParameter().
bool MusicLrcContainerForInline::m_mouseLeftPressed protected
Definition at line 251 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), MusicLrcContainerForInline(), paintEvent(), and updateCurrentLrc().
bool MusicLrcContainerForInline::m_mouseMoved protected
Definition at line 251 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and MusicLrcContainerForInline().
QPoint MusicLrcContainerForInline::m_mousePressedAt protected
Definition at line 250 of file musiclrccontainerforinline.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
MusicClickedLabel* MusicLrcContainerForInline::m_noLrcCurrentInfo protected
Definition at line 261 of file musiclrccontainerforinline.h.
Referenced by createNoLrcCurrentInfo(), showNoLrcCurrentInfo(), transLyricFileToTime(), and ~MusicLrcContainerForInline().
bool MusicLrcContainerForInline::m_showArtBackground protected
Definition at line 254 of file musiclrccontainerforinline.h.
Referenced by artBackgroundChanged(), contextMenuEvent(), MusicLrcContainerForInline(), and showArtBackgroundUploadedWidget().
MusicLrcTranslatedWidget* MusicLrcContainerForInline::m_translatedWidget protected
Definition at line 263 of file musiclrccontainerforinline.h.
Referenced by getTranslatedLrcFinished(), MusicLrcContainerForInline(), resizeWidth(), and ~MusicLrcContainerForInline().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforinline.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforinline.cpp