TTKMusicplayer: OSSUploadData Class Reference
OSSUploadData Class Reference
The class of the alioss cloud data item.
#include <ossuploaddata.h>
Signals
void uploadFileFinished (const QString &time)
void uploadProgressChanged (const QString &time, qint64 bytesSent, qint64 bytesTotal)
Public Member Functions
OSSUploadData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void uploadDataOperator (const QString &time, const QString &bucket, const QString &fileName, const QString &filePath)
Public Member Functions inherited from OSSDataInterface
OSSDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Protected Slots
virtual void receiveDataFromServer () override
void uploadProgress (qint64 bytesSent, qint64 bytesTotal)
Protected Slots inherited from OSSDataInterface
virtual void receiveDataFromServer ()=0
void handleError (QNetworkReply::NetworkError error)
Additional Inherited Members
Protected Member Functions inherited from OSSDataInterface
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
Detailed Description
The class of the alioss cloud data item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file ossuploaddata.h.
Constructor & Destructor Documentation
OSSUploadData::OSSUploadData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 18 of file ossuploaddata.cpp.
References TTK_D, TTK_INIT_PRIVATE, and TTK_INIT_PUBLIC.
Member Function Documentation
void OSSUploadData::receiveDataFromServer () override protected virtual slot
Receive data from server finshed.
Definition at line 69 of file ossuploaddata.cpp.
References MObject_cast, TTK_D, TTK_NAN_STR, and uploadFileFinished().
Referenced by uploadDataOperator().
void OSSUploadData::uploadDataOperator (const QString & time, const QString & bucket, const QString & fileName, const QString & filePath)
Get uplaod data operator.
Definition at line 27 of file ossuploaddata.cpp.
References OSSUtils::getGMT(), OSSDataInterface::handleError(), MusicObject::NetworkError, OSSConf::OSS_HOST, receiveDataFromServer(), TTK_D, uploadProgress(), and uploadProgressChanged().
Referenced by MusicCloudManagerTableWidget::startToUploadFile().
void OSSUploadData::uploadFileFinished (const QString & time) signal
Uplaod file finshed.
Referenced by receiveDataFromServer().
void OSSUploadData::uploadProgress (qint64 bytesSent, qint64 bytesTotal) protected slot
Show upload progress.
Definition at line 91 of file ossuploaddata.cpp.
References TTK_D, and uploadProgressChanged().
Referenced by uploadDataOperator().
void OSSUploadData::uploadProgressChanged (const QString & time, qint64 bytesSent, qint64 bytesTotal) signal
Show upload progress.
Referenced by uploadDataOperator(), and uploadProgress().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qoss/ossuploaddata.h
TTKThirdParty/TTKExtras/qoss/ossuploaddata.cpp