TTKMusicplayer: MusicSoundKMicroWidget Class Reference
MusicSoundKMicroWidget Class Reference
The class of the sound kmicro widget.
#include <musicsoundkmicrowidget.h>
Public Slots
void volumeChanged (int volume)
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void playFinished ()
void setPosition (int position)
void playButtonChanged ()
void stateButtonChanged ()
void tipsButtonChanged ()
void mvURLChanged (bool mv, const QString &url, const QString &lrcUrl)
void downLoadFinished (const QByteArray &data)
void updateAnimationLrc ()
void recordButtonClicked ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Signals
void resetFlag (MusicObject::ToolsType flag)
Public Member Functions
MusicSoundKMicroWidget (QWidget *parent=0)
virtual ~MusicSoundKMicroWidget ()
void setButtonStyle (bool style) const
void setStateButtonStyle (bool style) const
void startSeachKMicro (const QString &name)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
void multiMediaChanged ()
void setItemStyleSheet (int index, int size, int transparent)
void recordStateChanged (bool state)
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicSoundKMicroWidget * m_ui
qint64 m_intervalTime
bool m_stateButtonOn
bool m_queryMv
MusicCoreMPlayer * m_mediaPlayer
MusicSoundKMicroSearchWidget * m_searchWidget
MusicLrcAnalysis * m_analysis
QList< MusicLrcManagerForInline * > m_musicLrcContainer
MusicAudioRecorderCore * m_recordCore
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the sound kmicro widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 37 of file musicsoundkmicrowidget.h.
Constructor & Destructor Documentation
MusicSoundKMicroWidget::MusicSoundKMicroWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 25 of file musicsoundkmicrowidget.cpp.
References MusicSoundKMicroSearchWidget::connectTo(), durationChanged(), MusicLrcAnalysis::getLineMax(), MusicGifLabelWidget::Gif_Cicle_Blue, MusicGifLabelWidget::Gif_Record_red, m_analysis, m_intervalTime, m_mediaPlayer, m_musicLrcContainer, m_queryMv, m_recordCore, m_searchWidget, m_stateButtonOn, m_ui, MusicUIObject::MBackgroundStyle02, MusicUIObject::MBackgroundStyle06, MusicUIObject::MColorStyle03, MusicUIObject::MKGRecordTransfer, MusicUIObject::MKGTinyBtnWintopOff, MusicUIObject::MSliderStyle01, MusicUIObject::MToolButtonStyle04, playButtonChanged(), playFinished(), positionChanged(), recordButtonClicked(), recordStateChanged(), setButtonStyle(), MusicLrcAnalysis::setLineMax(), MusicLrcManagerForInline::setLrcPerWidth(), setPosition(), setStateButtonStyle(), stateButtonChanged(), tipsButtonChanged(), and volumeChanged().
MusicSoundKMicroWidget::~MusicSoundKMicroWidget () virtual
Definition at line 104 of file musicsoundkmicrowidget.cpp.
References m_ui.
Member Function Documentation
void MusicSoundKMicroWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 321 of file musicsoundkmicrowidget.cpp.
References m_analysis, m_mediaPlayer, m_musicLrcContainer, m_recordCore, m_searchWidget, resetFlag(), and MusicObject::TT_SoundKMicro.
void MusicSoundKMicroWidget::downLoadFinished (const QByteArray & data) slot
Receive download byte data from net.
Definition at line 269 of file musicsoundkmicrowidget.cpp.
References MusicLrcAnalysis::getLineMax(), m_analysis, m_musicLrcContainer, setItemStyleSheet(), and MusicLrcAnalysis::setLrcData().
Referenced by mvURLChanged().
void MusicSoundKMicroWidget::durationChanged (qint64 duration) slot
Set current video duration.
Definition at line 158 of file musicsoundkmicrowidget.cpp.
References m_ui, MusicTime::msecTime2LabelJustified(), MT_S2MS, and multiMediaChanged().
Referenced by MusicSoundKMicroWidget().
QString MusicSoundKMicroWidget::getClassName () static
Get class object name.
Definition at line 109 of file musicsoundkmicrowidget.cpp.
void MusicSoundKMicroWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicAbstractMoveWidget.
Definition at line 339 of file musicsoundkmicrowidget.cpp.
References m_searchWidget, and MusicAbstractMoveWidget::mouseMoveEvent().
void MusicSoundKMicroWidget::multiMediaChanged () protected
Multi media changed.
Definition at line 345 of file musicsoundkmicrowidget.cpp.
References m_mediaPlayer, m_queryMv, m_stateButtonOn, m_ui, MusicCoreMPlayer::setLeftVolume(), MusicCoreMPlayer::setMultiVoice(), MusicCoreMPlayer::setRightVolume(), and volumeChanged().
Referenced by durationChanged(), and stateButtonChanged().
void MusicSoundKMicroWidget::mvURLChanged (bool mv, const QString & url, const QString & lrcUrl) slot
Set current media url.
Definition at line 243 of file musicsoundkmicrowidget.cpp.
References downLoadFinished(), m_mediaPlayer, m_queryMv, m_ui, MusicCoreMPlayer::MusicCategory, MusicCoreMPlayer::play(), setButtonStyle(), MusicCoreMPlayer::setMedia(), SOUND_KMICRO_INDEX_0, SOUND_KMICRO_INDEX_1, MusicDownloadSourceThread::startToDownload(), and MusicCoreMPlayer::VideoCategory.
void MusicSoundKMicroWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicAbstractMoveWidget.
Definition at line 333 of file musicsoundkmicrowidget.cpp.
References m_searchWidget, and MusicAbstractMoveWidget::paintEvent().
void MusicSoundKMicroWidget::playButtonChanged () slot
Play button changed.
Definition at line 193 of file musicsoundkmicrowidget.cpp.
References MusicLrcAnalysis::getMiddle(), m_analysis, m_intervalTime, m_mediaPlayer, m_musicLrcContainer, m_queryMv, m_ui, MusicCoreMPlayer::play(), MusicObject::PS_PausedState, MusicObject::PS_PlayingState, setButtonStyle(), and MusicCoreMPlayer::state().
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::playFinished () slot
Play finished.
Definition at line 168 of file musicsoundkmicrowidget.cpp.
References MusicAudioRecorderCore::addWavHeader(), MusicMessageBox::exec(), MusicUtils::Widget::getSaveFileDialog(), m_mediaPlayer, m_recordCore, m_ui, recordStateChanged(), MusicMessageBox::setText(), MusicCoreMPlayer::stop(), and MusicUtils::Core::toLocal8Bit().
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::positionChanged (qint64 position) slot
Current position changed.
Definition at line 136 of file musicsoundkmicrowidget.cpp.
References MusicLrcAnalysis::findText(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::isEmpty(), MusicLrcAnalysis::isValid(), m_analysis, m_intervalTime, m_musicLrcContainer, m_queryMv, m_ui, MusicTime::msecTime2LabelJustified(), and MT_S2MS.
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::recordButtonClicked () slot
Record button clicked.
Definition at line 294 of file musicsoundkmicrowidget.cpp.
References MusicMessageBox::exec(), m_ui, recordStateChanged(), and MusicMessageBox::setText().
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::recordStateChanged (bool state) protected
Record state changed.
Definition at line 385 of file musicsoundkmicrowidget.cpp.
References MusicAudioRecorderCore::error(), m_mediaPlayer, m_recordCore, m_ui, MusicUIObject::MKGRecord, MusicUIObject::MKGRerecord, MusicAudioRecorderCore::onRecordStart(), MusicAudioRecorderCore::onRecordStop(), MusicObject::PS_StoppedState, and MusicCoreMPlayer::state().
Referenced by MusicSoundKMicroWidget(), playFinished(), and recordButtonClicked().
void MusicSoundKMicroWidget::resetFlag (MusicObject::ToolsType flag) signal
Reset window open flag.
Referenced by closeEvent().
void MusicSoundKMicroWidget::setButtonStyle (bool style) const
Set current button style.
Definition at line 114 of file musicsoundkmicrowidget.cpp.
References m_ui, MusicUIObject::MKGVideoBtnPause, and MusicUIObject::MKGVideoBtnPlay.
Referenced by MusicSoundKMicroWidget(), mvURLChanged(), and playButtonChanged().
void MusicSoundKMicroWidget::setItemStyleSheet (int index, int size, int transparent) protected
Set per lrc line style sheet.
Definition at line 359 of file musicsoundkmicrowidget.cpp.
References m_musicLrcContainer, M_SETTING_PTR, MusicLrcColor::mapIndexToColor(), MStatic_cast, MusicUtils::String::readColorConfig(), MusicLrcManagerForInline::setCenterOnLrc(), MusicLrcManagerForInline::setFontSize(), MusicLrcManager::setFontTransparent(), MusicLrcManager::setLinearGradientColor(), and MusicLrcManagerForInline::setTransparent().
Referenced by downLoadFinished().
void MusicSoundKMicroWidget::setPosition (int position) slot
Set current play pos.
Definition at line 187 of file musicsoundkmicrowidget.cpp.
References m_analysis, m_mediaPlayer, MT_S2MS, MusicCoreMPlayer::setPosition(), and MusicLrcAnalysis::setSongSpeedChanged().
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::setStateButtonStyle (bool style) const
Set current state button style.
Definition at line 120 of file musicsoundkmicrowidget.cpp.
References m_ui, MusicUIObject::MKGVideoBtnOrigin, and MusicUIObject::MKGVideoBtnOriginOff.
Referenced by MusicSoundKMicroWidget(), and stateButtonChanged().
void MusicSoundKMicroWidget::startSeachKMicro (const QString & name)
Start seach KMicro.
Definition at line 126 of file musicsoundkmicrowidget.cpp.
References m_searchWidget, and MusicSoundKMicroSearchWidget::startSeachKMicro().
Referenced by MusicLeftAreaWidget::createSoundKMicroWidget().
void MusicSoundKMicroWidget::stateButtonChanged () slot
State button changed.
Definition at line 221 of file musicsoundkmicrowidget.cpp.
References m_stateButtonOn, multiMediaChanged(), and setStateButtonStyle().
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::tipsButtonChanged () slot
Tips button changed.
Definition at line 229 of file musicsoundkmicrowidget.cpp.
References m_searchWidget, m_ui, MusicUIObject::MKGTinyBtnWintopOff, and MusicUIObject::MKGTinyBtnWintopOn.
Referenced by MusicSoundKMicroWidget().
void MusicSoundKMicroWidget::updateAnimationLrc () slot
Animation finished.
Definition at line 284 of file musicsoundkmicrowidget.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), m_analysis, m_intervalTime, m_musicLrcContainer, and MusicLrcAnalysis::setCurrentIndex().
void MusicSoundKMicroWidget::volumeChanged (int volume) slot
Current volume changed.
Definition at line 131 of file musicsoundkmicrowidget.cpp.
References m_mediaPlayer, and MusicCoreMPlayer::setVolume().
Referenced by multiMediaChanged(), and MusicSoundKMicroWidget().
Member Data Documentation
MusicLrcAnalysis* MusicSoundKMicroWidget::m_analysis protected
Definition at line 146 of file musicsoundkmicrowidget.h.
Referenced by closeEvent(), downLoadFinished(), MusicSoundKMicroWidget(), playButtonChanged(), positionChanged(), setPosition(), and updateAnimationLrc().
qint64 MusicSoundKMicroWidget::m_intervalTime protected
Definition at line 142 of file musicsoundkmicrowidget.h.
Referenced by MusicSoundKMicroWidget(), playButtonChanged(), positionChanged(), and updateAnimationLrc().
MusicCoreMPlayer* MusicSoundKMicroWidget::m_mediaPlayer protected
Definition at line 144 of file musicsoundkmicrowidget.h.
Referenced by closeEvent(), multiMediaChanged(), MusicSoundKMicroWidget(), mvURLChanged(), playButtonChanged(), playFinished(), recordStateChanged(), setPosition(), and volumeChanged().
QList<MusicLrcManagerForInline*> MusicSoundKMicroWidget::m_musicLrcContainer protected
Definition at line 147 of file musicsoundkmicrowidget.h.
Referenced by closeEvent(), downLoadFinished(), MusicSoundKMicroWidget(), playButtonChanged(), positionChanged(), setItemStyleSheet(), and updateAnimationLrc().
bool MusicSoundKMicroWidget::m_queryMv protected
Definition at line 143 of file musicsoundkmicrowidget.h.
Referenced by multiMediaChanged(), MusicSoundKMicroWidget(), mvURLChanged(), playButtonChanged(), and positionChanged().
MusicAudioRecorderCore* MusicSoundKMicroWidget::m_recordCore protected
Definition at line 148 of file musicsoundkmicrowidget.h.
Referenced by closeEvent(), MusicSoundKMicroWidget(), playFinished(), and recordStateChanged().
MusicSoundKMicroSearchWidget* MusicSoundKMicroWidget::m_searchWidget protected
Definition at line 145 of file musicsoundkmicrowidget.h.
Referenced by closeEvent(), mouseMoveEvent(), MusicSoundKMicroWidget(), paintEvent(), startSeachKMicro(), and tipsButtonChanged().
bool MusicSoundKMicroWidget::m_stateButtonOn protected
Definition at line 143 of file musicsoundkmicrowidget.h.
Referenced by multiMediaChanged(), MusicSoundKMicroWidget(), and stateButtonChanged().
Ui::MusicSoundKMicroWidget* MusicSoundKMicroWidget::m_ui protected
Definition at line 141 of file musicsoundkmicrowidget.h.
Referenced by durationChanged(), multiMediaChanged(), MusicSoundKMicroWidget(), mvURLChanged(), playButtonChanged(), playFinished(), positionChanged(), recordButtonClicked(), recordStateChanged(), setButtonStyle(), setStateButtonStyle(), tipsButtonChanged(), and ~MusicSoundKMicroWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrowidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrowidget.cpp