TTKMusicPlayer: MusicQueryTableWidget Class Reference
MusicQueryTableWidget Class Reference abstract
The class of the query table widget.
#include <musicquerytablewidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) override
virtual void itemDoubleClicked (int row, int column)=0
virtual void removeItems () override
virtual void createResultItem (const MusicResultInfoItem &result)=0
void createFinishedItem ()
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Signals
void startToQueryByText (const QString &text)
Public Member Functions
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * queryInput () const
virtual void startToSearchByValue (const QString &value)=0
virtual void downloadQueryResult (int row)=0
virtual void resizeGeometry () override
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedItemRows () const
TTKIntList uncheckedItemRows () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
TTKIntList selectedRows () const
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
void setLoadingStatus (bool status) const
bool isValid (int row) const noexcept
Protected Member Functions inherited from TTKAbstractTableWidget
virtual void leaveEvent (QEvent *event) override
void setRowColor (int row, const QColor &color) const
bool isValid () const noexcept
Protected Attributes
MusicGifLabelWidget * m_loadingLabel
TTKLabelItemDelegate * m_labelDelegate
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the query table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicquerytablewidget.h.
Constructor & Destructor Documentation
MusicQueryTableWidget::MusicQueryTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 4 of file musicquerytablewidget.cpp.
References TTK::UI::BackgroundStyle12, MusicGifLabelWidget::CicleBlue, itemDoubleClicked(), m_labelDelegate, m_loadingLabel, and TTKAbstractItemDelegate::setStyleSheet().
MusicQueryTableWidget::~MusicQueryTableWidget ()
Object destructor.
Definition at line 16 of file musicquerytablewidget.cpp.
References m_labelDelegate, m_loadingLabel, and m_networkRequest.
Member Function Documentation
void MusicQueryTableWidget::createFinishedItem () slot
Create the search finished item.
Definition at line 66 of file musicquerytablewidget.cpp.
References m_labelDelegate, m_networkRequest, MusicPageQueryRequest::pageValid(), setLoadingStatus(), and TTK_DISPLAY_ROLE.
Referenced by setQueryInput().
virtual void MusicQueryTableWidget::createResultItem (const MusicResultInfoItem & result) pure virtual slot
Create search result items. Subclass should implement this function.
Referenced by setQueryInput().
virtual void MusicQueryTableWidget::downloadQueryResult (int row) pure virtual
Download query result data. Subclass should implement this function.
Implemented in MusicVideoSearchTableWidget, MusicNewSongRecommendQueryTableWidget, MusicItemQueryTableWidget, MusicLrcSearchTableWidget, and MusicSongSearchTableWidget.
Referenced by MusicItemSearchTableWidget::searchActionClicked().
bool MusicQueryTableWidget::isValid (int row) const inline protected noexcept
Check item row is valid or not.
Definition at line 113 of file musicquerytablewidget.h.
void MusicQueryTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 37 of file musicquerytablewidget.cpp.
References MusicFillItemTableWidget::itemCellClicked(), m_networkRequest, MusicPageQueryRequest::pageIndex(), setLoadingStatus(), MusicPageQueryRequest::startToPage(), and TTK_DISPLAY_ROLE.
Referenced by MusicWebMVRadioInfoTableWidget::itemCellClicked(), MusicSongSearchTableWidget::itemCellClicked(), MusicLrcSearchTableWidget::itemCellClicked(), MusicItemQueryTableWidget::itemCellClicked(), MusicNewSongRecommendQueryTableWidget::itemCellClicked(), and MusicVideoSearchTableWidget::itemCellClicked().
virtual void MusicQueryTableWidget::itemDoubleClicked (int row, int column) pure virtual slot
Table widget item cell double clicked. Subclass should implement this function.
Referenced by MusicQueryTableWidget().
MusicAbstractQueryRequest * MusicQueryTableWidget::queryInput () const
Get network query input.
Definition at line 32 of file musicquerytablewidget.cpp.
References m_networkRequest.
Referenced by MusicSongSearchOnlineWidget::buttonClicked(), MusicToplistQueryWidget::categoryChanged(), MusicToplistQueryWidget::createLabels(), MusicAlbumQueryWidget::queryAlbumFinished(), MusicArtistQueryWidget::queryArtistFinished(), MusicToplistQueryWidget::setCurrentValue(), MusicAbstractItemQueryWidget::setSongCountText(), and MusicAbstractItemQueryWidget::shareButtonClicked().
void MusicQueryTableWidget::removeItems () override virtual slot
Remove all items.
Definition at line 56 of file musicquerytablewidget.cpp.
References TTKAbstractTableWidget::removeItems().
Referenced by MusicSongSearchTableWidget::removeItems(), MusicLrcSearchTableWidget::removeItems(), MusicItemQueryTableWidget::removeItems(), MusicNewSongRecommendQueryTableWidget::removeItems(), MusicVideoSearchTableWidget::removeItems(), and setQueryInput().
void MusicQueryTableWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicItemQueryTableWidget.
Definition at line 92 of file musicquerytablewidget.cpp.
References m_loadingLabel.
Referenced by MusicItemQueryTableWidget::resizeEvent().
virtual void MusicQueryTableWidget::resizeGeometry () inline override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Reimplemented in MusicNewSongRecommendQueryTableWidget, MusicItemQueryTableWidget, and MusicSongSearchTableWidget.
Definition at line 67 of file musicquerytablewidget.h.
void MusicQueryTableWidget::setLoadingStatus (bool status) const protected
Set loading label status.
Definition at line 98 of file musicquerytablewidget.cpp.
References MusicGifLabelWidget::execute(), and m_loadingLabel.
Referenced by createFinishedItem(), itemCellClicked(), MusicSongSearchTableWidget::startToSearchByID(), MusicVideoSearchTableWidget::startToSearchByID(), MusicLrcSearchTableWidget::startToSearchByValue(), MusicSongSearchTableWidget::startToSearchByValue(), and MusicVideoSearchTableWidget::startToSearchByValue().
void MusicQueryTableWidget::setQueryInput (MusicAbstractQueryRequest * query)
Set network query input.
Definition at line 23 of file musicquerytablewidget.cpp.
References createFinishedItem(), createResultItem(), m_networkRequest, and removeItems().
Referenced by MusicMainRecommendWidget::createContainerTopWidget(), MusicToplistQueryWidget::MusicToplistQueryWidget(), MusicWebDJRadioInfoWidget::MusicWebDJRadioInfoWidget(), MusicWebMVRadioInfoWidget::MusicWebMVRadioInfoWidget(), MusicAlbumQueryWidget::setCurrentKey(), MusicArtistQueryWidget::setCurrentKey(), MusicRecommendQueryWidget::setCurrentValue(), MusicPersonalRadioQueryWidget::setCurrentValue(), MusicSimilarQueryWidget::setCurrentValue(), MusicPlaylistQueryInfoWidget::setQueryInput(), MusicSongSearchTableWidget::startToSearchByID(), MusicVideoSearchTableWidget::startToSearchByID(), MusicLrcSearchTableWidget::startToSearchByValue(), MusicSongSearchTableWidget::startToSearchByValue(), and MusicVideoSearchTableWidget::startToSearchByValue().
void MusicQueryTableWidget::startToQueryByText (const QString & text) signal
Start to query by text.
Referenced by MusicItemSearchTableWidget::searchActionClicked(), and MusicSongSearchTableWidget::searchActionClicked().
virtual void MusicQueryTableWidget::startToSearchByValue (const QString & value) pure virtual
Start to search query by value. Subclass should implement this function.
Implemented in MusicVideoSearchTableWidget, MusicNewSongRecommendQueryTableWidget, MusicItemQueryTableWidget, MusicLrcSearchTableWidget, and MusicSongSearchTableWidget.
Member Data Documentation
TTKLabelItemDelegate* MusicQueryTableWidget::m_labelDelegate protected
Definition at line 119 of file musicquerytablewidget.h.
Referenced by createFinishedItem(), MusicNewSongRecommendQueryTableWidget::MusicNewSongRecommendQueryTableWidget(), MusicQueryTableWidget(), and ~MusicQueryTableWidget().
MusicGifLabelWidget* MusicQueryTableWidget::m_loadingLabel protected
Definition at line 118 of file musicquerytablewidget.h.
Referenced by MusicQueryTableWidget(), resizeEvent(), setLoadingStatus(), and ~MusicQueryTableWidget().
MusicAbstractQueryRequest* MusicQueryTableWidget::m_networkRequest protected
Definition at line 120 of file musicquerytablewidget.h.
Referenced by MusicWebMVRadioInfoTableWidget::actionChanged(), MusicSongSearchTableWidget::addSearchMusicToPlaylist(), MusicNewSongRecommendQueryTableWidget::addSearchMusicToPlaylist(), MusicItemQueryTableWidget::addSearchMusicToPlaylist(), MusicWebMVRadioInfoTableWidget::contextMenuEvent(), MusicItemQueryTableWidget::contextMenuEvent(), MusicItemSearchTableWidget::createContextMenu(), createFinishedItem(), MusicItemQueryTableWidget::downloadBatchData(), MusicItemQueryTableWidget::downloadDataFrom(), MusicNewSongRecommendQueryTableWidget::downloadDataFrom(), MusicVideoSearchTableWidget::downloadLocalMovie(), MusicSongSearchTableWidget::downloadQueryResult(), MusicItemQueryTableWidget::downloadQueryResult(), MusicLrcSearchTableWidget::downloadQueryResult(), MusicNewSongRecommendQueryTableWidget::downloadQueryResult(), MusicWebMVRadioInfoTableWidget::itemCellClicked(), itemCellClicked(), MusicNewSongRecommendQueryTableWidget::itemCellEntered(), MusicVideoSearchTableWidget::itemDoubleClicked(), MusicItemQueryTableWidget::menuActionChanged(), queryInput(), MusicVideoSearchTableWidget::queryMediaProps(), MusicSongSearchTableWidget::searchActionClicked(), setQueryInput(), MusicSongSearchTableWidget::startToSearchByID(), MusicVideoSearchTableWidget::startToSearchByID(), MusicItemQueryTableWidget::startToSearchByValue(), MusicSongSearchTableWidget::startToSearchByValue(), MusicLrcSearchTableWidget::startToSearchByValue(), MusicNewSongRecommendQueryTableWidget::startToSearchByValue(), MusicVideoSearchTableWidget::startToSearchByValue(), and ~MusicQueryTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicquerytablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicquerytablewidget.cpp