TTKMusicplayer: QKugouUrl Class Reference
QKugouUrl Class Reference
The class of the kugou url.
#include <qkugouurl.h>
Public Member Functions
QKugouUrl ()
Static Public Member Functions
static QString makeSongYuekuUrl ()
static QString makeSongRecommendUrl ()
static QString makeSongRankUrl ()
static QString makeSongSingerUrl ()
static QString makeSongCategoryUrl ()
static QString makeRadioPublicUrl ()
static QString makeRadioHighFmUrl ()
static QString makeRadioFxUrl ()
static QString makeListUrl ()
static QString makeMVRadioUrl ()
static QString makeMVRecommendUrl ()
static QString makeMVFanxingUrl ()
static QString makeWebPlayerUrl ()
static QString makeKuiSheUrl ()
Detailed Description
The class of the kugou url.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file qkugouurl.h.
Constructor & Destructor Documentation
QKugouUrl::QKugouUrl ()
Object contsructor.
Definition at line 3 of file qkugouurl.cpp.
Member Function Documentation
QString QKugouUrl::makeKuiSheUrl () static
Make KuiShe Url.
Definition at line 73 of file qkugouurl.cpp.
Referenced by QKugouWindow::createKugouSingleWidget().
QString QKugouUrl::makeListUrl () static
Make List Url.
Definition at line 48 of file qkugouurl.cpp.
Referenced by QKugouWindow::createKugouListWidget().
QString QKugouUrl::makeMVFanxingUrl () static
Make MV Fanxing Url.
Definition at line 63 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouMVIndexChanged().
QString QKugouUrl::makeMVRadioUrl () static
Make MV Radio Url.
Definition at line 53 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouMVIndexChanged().
QString QKugouUrl::makeMVRecommendUrl () static
Make MV Recommend Url.
Definition at line 58 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouMVIndexChanged().
QString QKugouUrl::makeRadioFxUrl () static
Make Radio Fx Url.
Definition at line 43 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouRadioIndexChanged().
QString QKugouUrl::makeRadioHighFmUrl () static
Make Radio High Fm Url.
Definition at line 38 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouRadioIndexChanged().
QString QKugouUrl::makeRadioPublicUrl () static
Make Radio Public Url.
Definition at line 33 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouRadioIndexChanged().
QString QKugouUrl::makeSongCategoryUrl () static
Make Song Category Url.
Definition at line 28 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouSongIndexChanged().
QString QKugouUrl::makeSongRankUrl () static
Make Song Rank Url.
Definition at line 18 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouSongIndexChanged().
QString QKugouUrl::makeSongRecommendUrl () static
Make Song Recommend Url.
Definition at line 13 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouSongIndexChanged().
QString QKugouUrl::makeSongSingerUrl () static
Make Song Singer Url.
Definition at line 23 of file qkugouurl.cpp.
Referenced by QKugouWindow::kugouSongIndexChanged().
QString QKugouUrl::makeSongYuekuUrl () static
Make Song Yueku Url.
Definition at line 8 of file qkugouurl.cpp.
QString QKugouUrl::makeWebPlayerUrl () static
Make Web Player Url.
Definition at line 68 of file qkugouurl.cpp.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qkugou/qkugouurl.h
TTKThirdParty/TTKExtras/qkugou/qkugouurl.cpp