TTKMusicplayer: MusicMarqueeWidget Class Reference
MusicMarqueeWidget Class Reference
The class of the marquee widget.
#include <musicmarqueewidget.h>
Public Member Functions
MusicMarqueeWidget (QWidget *parent=nullptr)
void setEffectOnResize (bool on)
void setText (const QString &newText)
QString text () const
QSize sizeHint () const
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) overridefinal
virtual void showEvent (QShowEvent *event) overridefinal
virtual void hideEvent (QHideEvent *event) overridefinal
virtual void timerEvent (QTimerEvent *event) overridefinal
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
QString m_text
int m_offset
int m_timerId
bool m_effectOnResize
Detailed Description
The class of the marquee widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicmarqueewidget.h.
Constructor & Destructor Documentation
MusicMarqueeWidget::MusicMarqueeWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 5 of file musicmarqueewidget.cpp.
References m_effectOnResize, m_offset, and m_timerId.
Member Function Documentation
void MusicMarqueeWidget::hideEvent (QHideEvent * event) final override protected virtual
Definition at line 81 of file musicmarqueewidget.cpp.
References m_timerId.
void MusicMarqueeWidget::paintEvent (QPaintEvent * event) final override protected virtual
Override the widget event.
Definition at line 35 of file musicmarqueewidget.cpp.
References MusicUtils::Widget::fontTextWidth(), m_offset, and m_text.
void MusicMarqueeWidget::resizeEvent (QResizeEvent * event) final override protected virtual
Definition at line 88 of file musicmarqueewidget.cpp.
References setText(), and text().
void MusicMarqueeWidget::setEffectOnResize (bool on) inline
Set effect on resize.
Definition at line 41 of file musicmarqueewidget.h.
void MusicMarqueeWidget::setText (const QString & newText)
Set marquee text.
Definition at line 13 of file musicmarqueewidget.cpp.
References MusicUtils::Widget::fontTextWidth(), G_SETTING_PTR, m_effectOnResize, m_text, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), MusicRemoteWidgetForStrip::setLabelText(), MusicRemoteWidgetForSimpleStyle::setLabelText(), MusicRemoteWidgetForRipple::setLabelText(), and MusicRemoteWidgetForRectangle::setLabelText().
void MusicMarqueeWidget::showEvent (QShowEvent * event) final override protected virtual
Definition at line 58 of file musicmarqueewidget.cpp.
References m_timerId.
QSize MusicMarqueeWidget::sizeHint () const
Override size hint.
Definition at line 30 of file musicmarqueewidget.cpp.
References m_text.
QString MusicMarqueeWidget::text () const inline
Get marquee text.
Definition at line 49 of file musicmarqueewidget.h.
Referenced by resizeEvent().
void MusicMarqueeWidget::timerEvent (QTimerEvent * event) final override protected virtual
Definition at line 64 of file musicmarqueewidget.cpp.
References MusicUtils::Widget::fontTextWidth(), m_offset, m_text, and m_timerId.
Member Data Documentation
bool MusicMarqueeWidget::m_effectOnResize private
Definition at line 68 of file musicmarqueewidget.h.
Referenced by MusicMarqueeWidget(), and setText().
int MusicMarqueeWidget::m_offset private
Definition at line 67 of file musicmarqueewidget.h.
Referenced by MusicMarqueeWidget(), paintEvent(), and timerEvent().
QString MusicMarqueeWidget::m_text private
Definition at line 66 of file musicmarqueewidget.h.
Referenced by paintEvent(), setText(), sizeHint(), and timerEvent().
int MusicMarqueeWidget::m_timerId private
Definition at line 67 of file musicmarqueewidget.h.
Referenced by hideEvent(), MusicMarqueeWidget(), showEvent(), and timerEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicmarqueewidget.h
TTKModule/TTKWidget/musicCoreKits/musicmarqueewidget.cpp