TTKMusicplayer: MusicScreenSaverHoverItem Class Reference
MusicScreenSaverHoverItem Class Reference
The class of the screen saver hover item.
#include <musicscreensaverwidget.h>
Signals
void itemClicked (int index, bool status)
Public Member Functions
MusicScreenSaverHoverItem (QLabel *parent=nullptr)
void setFilePath (const QString &path)
void setStatus (int index, bool status)
void showItem (const QPoint &point)
Protected Member Functions
virtual void leaveEvent (QEvent *event) overridefinal
virtual void focusOutEvent (QFocusEvent *event) overridefinal
virtual void paintEvent (QPaintEvent *event) overridefinal
Protected Attributes
int m_index
QString m_path
QLabel * m_parentClass
QPushButton * m_enableButton
Private Slots
void caseButtonOnAndOff ()
Detailed Description
The class of the screen saver hover item.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicscreensaverwidget.h.
Constructor & Destructor Documentation
MusicScreenSaverHoverItem::MusicScreenSaverHoverItem (QLabel * parent = nullptr) explicit
Object contsructor.
Definition at line 21 of file musicscreensaverwidget.cpp.
References caseButtonOnAndOff(), m_enableButton, MusicUIObject::MQSSScreenItemDisable, and OS_ITEM_SIZE.
Member Function Documentation
void MusicScreenSaverHoverItem::caseButtonOnAndOff () private slot
Case button on and off.
Definition at line 64 of file musicscreensaverwidget.cpp.
References MusicUtils::Image::grayScalePixmap(), itemClicked(), m_enableButton, m_index, m_parentClass, m_path, MusicUIObject::MQSSScreenItemDisable, and MusicUIObject::MQSSScreenItemEnable.
Referenced by MusicScreenSaverHoverItem(), and setStatus().
void MusicScreenSaverHoverItem::focusOutEvent (QFocusEvent * event) final override protected virtual
Definition at line 90 of file musicscreensaverwidget.cpp.
void MusicScreenSaverHoverItem::itemClicked (int index, bool status) signal
Current item clicked.
Referenced by caseButtonOnAndOff().
void MusicScreenSaverHoverItem::leaveEvent (QEvent * event) final override protected virtual
Override the widget event.
Definition at line 84 of file musicscreensaverwidget.cpp.
void MusicScreenSaverHoverItem::paintEvent (QPaintEvent * event) final override protected virtual
Definition at line 96 of file musicscreensaverwidget.cpp.
References OS_ITEM_SIZE, QtLablePixmap, and MusicUtils::Widget::setBorderShadow().
void MusicScreenSaverHoverItem::setFilePath (const QString & path)
Set item file name.
Definition at line 41 of file musicscreensaverwidget.cpp.
References m_parentClass, and m_path.
Referenced by MusicScreenSaverListItem::setFilePath().
void MusicScreenSaverHoverItem::setStatus (int index, bool status)
Set item status.
Definition at line 49 of file musicscreensaverwidget.cpp.
References caseButtonOnAndOff(), and m_index.
Referenced by MusicScreenSaverListItem::setStatus().
void MusicScreenSaverHoverItem::showItem (const QPoint & point)
show item.
Definition at line 58 of file musicscreensaverwidget.cpp.
Referenced by MusicScreenSaverListItem::enterEvent().
Member Data Documentation
QPushButton* MusicScreenSaverHoverItem::m_enableButton protected
Definition at line 81 of file musicscreensaverwidget.h.
Referenced by caseButtonOnAndOff(), and MusicScreenSaverHoverItem().
int MusicScreenSaverHoverItem::m_index protected
Definition at line 78 of file musicscreensaverwidget.h.
Referenced by caseButtonOnAndOff(), and setStatus().
QLabel* MusicScreenSaverHoverItem::m_parentClass protected
Definition at line 80 of file musicscreensaverwidget.h.
Referenced by caseButtonOnAndOff(), and setFilePath().
QString MusicScreenSaverHoverItem::m_path protected
Definition at line 79 of file musicscreensaverwidget.h.
Referenced by caseButtonOnAndOff(), and setFilePath().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicscreensaverwidget.cpp