TTKMusicplayer: MusicRadioPlayListThread Class Reference
MusicRadioPlayListThread Class Reference
The class of music radio thread of playlist.
#include <musicradioplaylistthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicRadioPlayListThread (QObject *parent=0, QNetworkCookieJar *cookie=0)
QJson import.
virtual ~MusicRadioPlayListThread ()
virtual void startToDownload (const QString &id) override
QStringList getMusicPlayList ()
Public Member Functions inherited from MusicRadioThreadAbstract
MusicRadioThreadAbstract (QObject *parent=0, QNetworkCookieJar *cookie=0)
virtual ~MusicRadioThreadAbstract ()
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicRadioThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Attributes
QStringList m_playList
Protected Attributes inherited from MusicRadioThreadAbstract
QNetworkCookieJar * m_cookJar
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Detailed Description
The class of music radio thread of playlist.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 18 of file musicradioplaylistthread.h.
Constructor & Destructor Documentation
MusicRadioPlayListThread::MusicRadioPlayListThread (QObject * parent = 0, QNetworkCookieJar * cookie = 0) explicit
QJson import.
Object contsructor.
Definition at line 9 of file musicradioplaylistthread.cpp.
MusicRadioPlayListThread::~MusicRadioPlayListThread () virtual
Definition at line 15 of file musicradioplaylistthread.cpp.
References MusicNetworkAbstract::deleteAll().
Member Function Documentation
void MusicRadioPlayListThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 56 of file musicradioplaylistthread.cpp.
References MusicNetworkAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), m_playList, MusicNetworkAbstract::m_reply, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicRadioPlayListThread::getClassName () static
Get class object name.
Definition at line 20 of file musicradioplaylistthread.cpp.
Referenced by startToDownload().
QStringList MusicRadioPlayListThread::getMusicPlayList ()
Get music playlist.
Definition at line 51 of file musicradioplaylistthread.cpp.
References m_playList.
Referenced by MusicWebMusicRadioWidget::getPlayListFinished().
void MusicRadioPlayListThread::startToDownload (const QString & id) override virtual
Start to download data.
Implements MusicRadioThreadAbstract.
Definition at line 25 of file musicradioplaylistthread.cpp.
References downLoadFinished(), getClassName(), MusicRadioThreadAbstract::m_cookJar, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicUtils::Algorithm::mdII(), PLAYLIST_URL, MusicNetworkAbstract::replyError(), and MusicNetworkAbstract::sslErrors().
Referenced by MusicWebMusicRadioWidget::updateRadioList().
Member Data Documentation
QStringList MusicRadioPlayListThread::m_playList protected
Definition at line 49 of file musicradioplaylistthread.h.
Referenced by downLoadFinished(), and getMusicPlayList().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/musicradioplaylistthread.h
TTKModule/TTKCore/musicNetworkKits/radio/musicradioplaylistthread.cpp