TTKMusicplayer: MusicHotKeyManager Class Reference
MusicHotKeyManager Class Reference
The class of the global hotkey setting manager.
#include <musichotkeymanager.h>
Public Member Functions
void setInputModule (QObject *object)
void setHotKeys (const QStringList &keys)
void setHotKey (int index, const QString &key)
void setHotKey (int index, int key)
QString hotKey (int index)
QObject * getHotKey (int index)
void addHotKey (const QString &key)
void addHotKey (int key)
void setEnabled (int index, bool enable)
bool enabled (int index)
void enabledAll (bool enable)
QString toString (int key, int modifiers)
int count () const
QStringList getDefaultKeys () const
QStringList getKeys () const
Protected Member Functions
void setDefaultKey ()
Protected Attributes
QList< QGlobalShortcut * > m_hotkeys
Detailed Description
The class of the global hotkey setting manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musichotkeymanager.h.
Member Function Documentation
void MusicHotKeyManager::addHotKey (const QString & key)
Add hotKey by given index and string key.
Definition at line 80 of file musichotkeymanager.cpp.
References m_hotkeys.
void MusicHotKeyManager::addHotKey (int key)
Set hotKey by given index and virtual key.
Definition at line 85 of file musichotkeymanager.cpp.
References m_hotkeys.
int MusicHotKeyManager::count () const
Get hotkey count.
Definition at line 139 of file musichotkeymanager.cpp.
References m_hotkeys.
bool MusicHotKeyManager::enabled (int index)
check the given hotkey is enabled or not.
Definition at line 99 of file musichotkeymanager.cpp.
References m_hotkeys.
void MusicHotKeyManager::enabledAll (bool enable)
Enable or disable all hotkeys.
Definition at line 108 of file musichotkeymanager.cpp.
References key, and m_hotkeys.
QStringList MusicHotKeyManager::getDefaultKeys () const
Get default key string.
Definition at line 144 of file musichotkeymanager.cpp.
Referenced by setDefaultKey().
QObject * MusicHotKeyManager::getHotKey (int index)
Get the object key by given hotKey index.
Definition at line 71 of file musichotkeymanager.cpp.
References m_hotkeys.
QStringList MusicHotKeyManager::getKeys () const
Get key string.
Definition at line 152 of file musichotkeymanager.cpp.
References key, and m_hotkeys.
QString MusicHotKeyManager::hotKey (int index)
Get the string key by given hotKey index.
Definition at line 62 of file musichotkeymanager.cpp.
References m_hotkeys.
void MusicHotKeyManager::setDefaultKey () protected
Set default key.
Definition at line 25 of file musichotkeymanager.cpp.
References getDefaultKeys(), m_hotkeys, setEnabled(), and setHotKey().
Referenced by setInputModule().
void MusicHotKeyManager::setEnabled (int index, bool enable)
Enable or disable the hotkey by index.
Definition at line 90 of file musichotkeymanager.cpp.
References m_hotkeys.
Referenced by setDefaultKey(), and setHotKeys().
void MusicHotKeyManager::setHotKey (int index, const QString & key)
Set hotKey by given index and string key.
Definition at line 44 of file musichotkeymanager.cpp.
References m_hotkeys.
Referenced by setDefaultKey(), and setHotKeys().
void MusicHotKeyManager::setHotKey (int index, int key)
Set hotKey by given index and virtual key.
Definition at line 53 of file musichotkeymanager.cpp.
References m_hotkeys.
void MusicHotKeyManager::setHotKeys (const QStringList & keys)
Set hotKey by given string list keys.
Definition at line 35 of file musichotkeymanager.cpp.
References m_hotkeys, setEnabled(), and setHotKey().
void MusicHotKeyManager::setInputModule (QObject * object)
Set input connection.
Definition at line 6 of file musichotkeymanager.cpp.
References m_hotkeys, and setDefaultKey().
QString MusicHotKeyManager::toString (int key, int modifiers)
Mapping the virtual key to string key.
Definition at line 116 of file musichotkeymanager.cpp.
Member Data Documentation
QList<QGlobalShortcut*> MusicHotKeyManager::m_hotkeys protected
Definition at line 105 of file musichotkeymanager.h.
Referenced by addHotKey(), count(), enabled(), enabledAll(), getHotKey(), getKeys(), hotKey(), setDefaultKey(), setEnabled(), setHotKey(), setHotKeys(), and setInputModule().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicCoreKits/musichotkeymanager.h
TTKModule/TTKCore/musicCoreKits/musichotkeymanager.cpp