TTKMusicplayer: MusicQQQueryToplistRequest Class Reference
MusicQQQueryToplistRequest Class Reference
The class of qq query toplist download data from net.
#include <musicqqquerytoplistrequest.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractQueryRequest
virtual void downLoadFinished () override
Public Slots inherited from MusicAbstractNetwork
virtual void downLoadFinished ()
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicQQQueryToplistRequest (QObject *parent=nullptr)
virtual void startToSearch (QueryType type, const QString &toplist) override
virtual void startToSearch (const QString &toplist) override
Public Member Functions inherited from MusicQueryToplistRequest
MusicQueryToplistRequest (QObject *parent=nullptr)
Public Member Functions inherited from MusicAbstractQueryRequest
MusicAbstractQueryRequest (QObject *parent=nullptr)
virtual void startToSingleSearch (const QString &text)
void setQueryQuality (const QString &qual)
QString getQueryQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getQueryText () const
void setMusicSongInfos (const MusicObject::MusicSongInformations &infos)
const MusicObject::MusicSongInformations & getMusicSongInfos () const
bool isEmpty () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicPagingRequest
MusicPagingRequest (QObject *parent=nullptr)
virtual void startToPage (int offset)
int getPageSize () const
int getTotalSize () const
int getPageIndex () const
Public Member Functions inherited from MusicAbstractNetwork
MusicAbstractNetwork (QObject *parent=nullptr)
virtual ~MusicAbstractNetwork ()
virtual void deleteAll ()
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Additional Inherited Members
Public Types inherited from MusicAbstractQueryRequest
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Signals inherited from MusicQueryToplistRequest
void createToplistInfoItem (const MusicResultsItem &item)
Signals inherited from MusicAbstractQueryRequest
void clearAllItems ()
void createSearchedItem (const MusicSearchedItem &songItem)
Signals inherited from MusicAbstractNetwork
void downLoadRawDataChanged (const QByteArray &bytes)
void downLoadDataChanged (const QString &bytes)
Static Public Member Functions inherited from MusicAbstractQueryRequest
static qint64 getUrlFileSize (const QString &url)
Protected Member Functions inherited from MusicAbstractQueryRequest
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
Protected Attributes inherited from MusicAbstractQueryRequest
MusicObject::MusicSongInformations m_musicSongInfos
QString m_queryText
QString m_queryQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
Protected Attributes inherited from MusicPagingRequest
int m_pageSize
int m_totalSize
int m_pageIndex
Protected Attributes inherited from MusicAbstractNetwork
QVariantMap m_rawData
volatile bool m_interrupt
volatile MusicObject::NetworkCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager m_manager
Private Member Functions inherited from MusicQQQueryInterface
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key)
QString getMusicPath (const QString &file, const QString &mid)
Detailed Description
The class of qq query toplist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicqqquerytoplistrequest.h.
Constructor & Destructor Documentation
MusicQQQueryToplistRequest::MusicQQQueryToplistRequest (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicqqquerytoplistrequest.cpp.
References MusicAbstractQueryRequest::m_queryServer, and QUERY_QQ_INTERFACE.
Member Function Documentation
void MusicQQQueryToplistRequest::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 40 of file musicqqquerytoplistrequest.cpp.
References MusicUtils::String::charactersReplaced(), MusicAbstractQueryRequest::createSearchedItem(), MusicQueryToplistRequest::createToplistInfoItem(), MusicAbstractNetwork::deleteAll(), MusicAbstractNetwork::downLoadDataChanged(), MusicAbstractQueryRequest::downLoadFinished(), MusicObject::MusicSongInformation::m_albumId, MusicSearchedItem::m_albumName, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicResultsItem::m_coverUrl, MusicResultsItem::m_description, MusicObject::MusicSongInformation::m_discNumber, MusicSearchedItem::m_duration, MusicObject::MusicSongInformation::m_duration, MusicObject::MusicSongInformation::m_lrcUrl, MusicAbstractQueryRequest::m_musicSongInfos, MusicResultsItem::m_name, MusicResultsItem::m_playCount, MusicAbstractQueryRequest::m_queryAllRecords, MusicAbstractQueryRequest::m_queryQuality, MusicAbstractNetwork::m_rawData, MusicAbstractNetwork::m_reply, MusicSearchedItem::m_singerName, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songName, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_trackNumber, MusicSearchedItem::m_type, MusicResultsItem::m_updateTime, MusicObject::MusicSongInformation::m_year, MusicAbstractQueryRequest::mapQueryServerString(), MusicUtils::Algorithm::mdII(), MusicTime::msecTime2LabelJustified(), name, QJson::Parser::parse(), QQ_SONG_LRC_URL, QQ_SONG_PIC_URL, MusicQQQueryInterface::readFromMusicSongAttribute(), TTK_LOGGER_INFO, and TTK_NETWORK_QUERY_CHECK.
Referenced by startToSearch().
void MusicQQQueryToplistRequest::startToSearch (QueryType type, const QString & toplist) override virtual
Start to Search data from name and type.
Reimplemented from MusicQueryToplistRequest.
Definition at line 9 of file musicqqquerytoplistrequest.cpp.
References MusicAbstractQueryRequest::MusicQuery.
void MusicQQQueryToplistRequest::startToSearch (const QString & toplist) override virtual
Start to Search data from name and type.
Implements MusicQueryToplistRequest.
Definition at line 21 of file musicqqquerytoplistrequest.cpp.
References MusicAbstractNetwork::deleteAll(), downLoadFinished(), MusicAbstractNetwork::m_manager, MusicAbstractNetwork::m_reply, MusicQQInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), MusicObject::NetworkError, QQ_TOPLIST_URL, MusicAbstractNetwork::replyError(), and TTK_LOGGER_INFO.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqquerytoplistrequest.h
TTKModule/TTKCore/musicNetworkKits/music/qq/musicqqquerytoplistrequest.cpp