TTKMusicplayer: MusicMovingLabelSlider Class Reference
MusicMovingLabelSlider Class Reference
The class of the slider that can show such as tooltip.
#include <musicmovinglabelslider.h>
Public Slots
void setValue (int value)
Signals
void sliderReleasedAt (int pos)
Public Member Functions
MusicMovingLabelSlider (QWidget *parent=0)
MusicMovingLabelSlider (Qt::Orientation orientation, QWidget *parent=0)
~MusicMovingLabelSlider ()
bool isMoving () const
void setMoving (bool m)
Public Member Functions inherited from MusicClickedSlider
MusicClickedSlider (QWidget *parent=0)
MusicClickedSlider (Qt::Orientation orientation, QWidget *parent=0)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicClickedSlider
static QString getClassName ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void enterEvent (QEvent *event) override
virtual void leaveEvent (QEvent *event) override
QPoint limitLableGeometry (int x, int y, int z)
Protected Member Functions inherited from MusicClickedSlider
virtual bool event (QEvent *event) override
Protected Attributes
bool m_isMoving
QLabel * m_textLabel
Qt::Orientation m_orientation
Protected Attributes inherited from MusicClickedSlider
int m_value
bool m_mousePress
Detailed Description
The class of the slider that can show such as tooltip.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 19 of file musicmovinglabelslider.h.
Constructor & Destructor Documentation
MusicMovingLabelSlider::MusicMovingLabelSlider (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 5 of file musicmovinglabelslider.cpp.
MusicMovingLabelSlider::MusicMovingLabelSlider (Qt::Orientation orientation, QWidget * parent = 0) explicit
Object contsructor by slider orientation.
Definition at line 11 of file musicmovinglabelslider.cpp.
References m_isMoving, m_orientation, m_textLabel, and MusicUIObject::MLabelStyle01.
MusicMovingLabelSlider::~MusicMovingLabelSlider ()
Definition at line 26 of file musicmovinglabelslider.cpp.
References m_textLabel.
Member Function Documentation
void MusicMovingLabelSlider::enterEvent (QEvent * event) override protected virtual
Definition at line 89 of file musicmovinglabelslider.cpp.
References m_textLabel.
QString MusicMovingLabelSlider::getClassName () static
Get class object name.
Definition at line 31 of file musicmovinglabelslider.cpp.
bool MusicMovingLabelSlider::isMoving () const inline
Slider is now moving or not.
Definition at line 41 of file musicmovinglabelslider.h.
Referenced by MusicTimerSliderWidget::setValue().
void MusicMovingLabelSlider::leaveEvent (QEvent * event) override protected virtual
Definition at line 97 of file musicmovinglabelslider.cpp.
References m_textLabel.
QPoint MusicMovingLabelSlider::limitLableGeometry (int x, int y, int z) protected
Set the tool tip gemetry.
Definition at line 103 of file musicmovinglabelslider.cpp.
Referenced by mouseMoveEvent().
void MusicMovingLabelSlider::mouseMoveEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicClickedSlider.
Definition at line 55 of file musicmovinglabelslider.cpp.
References limitLableGeometry(), m_isMoving, MusicClickedSlider::m_mousePress, m_orientation, m_textLabel, MusicClickedSlider::m_value, MusicClickedSlider::mouseMoveEvent(), and MusicTime::msecTime2LabelJustified().
void MusicMovingLabelSlider::mousePressEvent (QMouseEvent * event) override protected virtual
Override the widget event.
Reimplemented from MusicClickedSlider.
Definition at line 44 of file musicmovinglabelslider.cpp.
References m_isMoving, m_textLabel, MusicClickedSlider::m_value, and MusicClickedSlider::mousePressEvent().
void MusicMovingLabelSlider::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Reimplemented from MusicClickedSlider.
Definition at line 82 of file musicmovinglabelslider.cpp.
References m_isMoving, MusicClickedSlider::m_value, MusicClickedSlider::mouseReleaseEvent(), and sliderReleasedAt().
void MusicMovingLabelSlider::setMoving (bool m) inline
Set slider moving or not.
Definition at line 45 of file musicmovinglabelslider.h.
void MusicMovingLabelSlider::setValue (int value) slot
Set slider current value.
Definition at line 36 of file musicmovinglabelslider.cpp.
References m_isMoving.
Referenced by MusicTimerSliderWidget::MusicTimerSliderWidget(), MusicTimerSliderWidget::setValue(), and MusicVideoControlWidget::setValue().
void MusicMovingLabelSlider::sliderReleasedAt (int pos) signal
Slider handle release at pos emit.
Referenced by mouseReleaseEvent().
Member Data Documentation
bool MusicMovingLabelSlider::m_isMoving protected
Definition at line 73 of file musicmovinglabelslider.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), MusicMovingLabelSlider(), and setValue().
Qt::Orientation MusicMovingLabelSlider::m_orientation protected
Definition at line 75 of file musicmovinglabelslider.h.
Referenced by mouseMoveEvent(), and MusicMovingLabelSlider().
QLabel* MusicMovingLabelSlider::m_textLabel protected
Definition at line 74 of file musicmovinglabelslider.h.
Referenced by enterEvent(), leaveEvent(), mouseMoveEvent(), mousePressEvent(), MusicMovingLabelSlider(), and ~MusicMovingLabelSlider().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicmovinglabelslider.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicmovinglabelslider.cpp