TTKMusicplayer: ChineseHelper Class Reference
ChineseHelper Class Reference
The class of the simple and traditional chinese characters.
#include <chinesehelper.h>
Public Member Functions
ChineseHelper ()
QChar convertToSimplifiedChinese (const QChar &c) const
The single traditional Chinese characters into simplified Chinese characters.
QChar convertToTraditionalChinese (const QChar &c) const
The individual characters converted to traditional Chinese characters.
QString convertToSimplifiedChinese (const QString &str) const
The traditional Chinese characters into simplified Chinese characters.
QString convertToTraditionalChinese (const QString &str) const
Convert the simplified traditional characters.
bool isTraditionalChinese (const QChar &c) const
To determine whether a character is a traditional character.
bool isChinese (const QChar &c) const
To determine whether a character is a Chinese character.
bool containsChinese (const QString &str) const
Determine whether the string contains Chinese.
Detailed Description
The class of the simple and traditional chinese characters.
Author
jiangXiaoBai 24999.nosp@m.7190.nosp@m.6@qq..nosp@m.com
Definition at line 29 of file chinesehelper.h.
Constructor & Destructor Documentation
ChineseHelper::ChineseHelper ()
Object contsructor.
Definition at line 23 of file chinesehelper.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
bool ChineseHelper::containsChinese (const QString & str) const
Determine whether the string contains Chinese.
Parameters
str character string
Returns
Contains the Chinese characters to return to true, or return to false
Definition at line 77 of file chinesehelper.cpp.
References isChinese().
QChar ChineseHelper::convertToSimplifiedChinese (const QChar & c) const
The single traditional Chinese characters into simplified Chinese characters.
Parameters
c Need to convert the traditional Chinese characters
Returns
After the conversion of the simplified Chinese characters
Definition at line 28 of file chinesehelper.cpp.
References TTK_D.
Referenced by convertToSimplifiedChinese().
QString ChineseHelper::convertToSimplifiedChinese (const QString & str) const
The traditional Chinese characters into simplified Chinese characters.
Parameters
str Need to convert the traditional Chinese characters
Returns
Converted to simplified
Definition at line 42 of file chinesehelper.cpp.
References convertToSimplifiedChinese().
QChar ChineseHelper::convertToTraditionalChinese (const QChar & c) const
The individual characters converted to traditional Chinese characters.
Parameters
c The need to convert simplified Chinese characters
Returns
Converted to numerous fonts
Definition at line 35 of file chinesehelper.cpp.
References TTK_D.
Referenced by convertToTraditionalChinese().
QString ChineseHelper::convertToTraditionalChinese (const QString & str) const
Convert the simplified traditional characters.
Parameters
str The need to convert simplified Chinese characters
Returns
Converted to numerous fonts
Definition at line 52 of file chinesehelper.cpp.
References convertToTraditionalChinese().
bool ChineseHelper::isChinese (const QChar & c) const
To determine whether a character is a Chinese character.
Parameters
c Character needed to be judged
Returns
Is the Chinese character returns true, otherwise returns false
Definition at line 68 of file chinesehelper.cpp.
Referenced by containsChinese(), and MusicLrcPosterItemWidget::drawTheme16().
bool ChineseHelper::isTraditionalChinese (const QChar & c) const
To determine whether a character is a traditional character.
Parameters
c Character needed to be judged
Returns
Is the traditional character returns true, otherwise returns false
Definition at line 62 of file chinesehelper.cpp.
References TTK_D.
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qhz2py/chinesehelper.h
TTKThirdParty/TTKExtras/qhz2py/chinesehelper.cpp