TTKMusicplayer: MusicBDDiscoverListThread Class Reference
MusicBDDiscoverListThread Class Reference
The class to baidu discover toplist.
#include <musicbddiscoverlistthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicBDDiscoverListThread (QObject *parent=0)
QJson import.
virtual void startToSearch () override
Public Member Functions inherited from MusicDownLoadDiscoverListThread
MusicDownLoadDiscoverListThread (QObject *parent=0)
QString getTopListInfo () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadDiscoverListThread
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Protected Attributes inherited from MusicDownLoadDiscoverListThread
QString m_topListInfo
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class to baidu discover toplist.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicbddiscoverlistthread.h.
Constructor & Destructor Documentation
MusicBDDiscoverListThread::MusicBDDiscoverListThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 6 of file musicbddiscoverlistthread.cpp.
References MusicDownLoadPagingThread::m_pageSize.
Member Function Documentation
void MusicBDDiscoverListThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 44 of file musicbddiscoverlistthread.cpp.
References MusicDownLoadPagingThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_reply, MusicDownLoadDiscoverListThread::m_topListInfo, and QJson::Parser::parse().
Referenced by startToSearch().
QString MusicBDDiscoverListThread::getClassName () static
Get class object name.
Definition at line 12 of file musicbddiscoverlistthread.cpp.
Referenced by downLoadFinished(), and startToSearch().
void MusicBDDiscoverListThread::startToSearch () override virtual
Start to Search data from toplist.
Implements MusicDownLoadDiscoverListThread.
Definition at line 17 of file musicbddiscoverlistthread.cpp.
References ALG_UA_KEY, BD_SONG_TOPLIST_URL, BD_UA_URL_1, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicNetworkAbstract::m_reply, MusicDownLoadDiscoverListThread::m_topListInfo, MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), and MusicUtils::Core::toUtf8().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/bd/musicbddiscoverlistthread.h
TTKModule/TTKCore/musicNetworkKits/bd/musicbddiscoverlistthread.cpp