TTKMusicPlayer: MusicLrcFromInterface Class Reference
MusicLrcFromInterface Class Reference abstract
The class of the base lrc interface.
#include <musiclrcparser.h>
Public Member Functions
virtual ~MusicLrcFromInterface ()=default
virtual bool decode (const QString &input)=0
const QByteArray & data () const noexcept
Protected Attributes
QByteArray m_data
Detailed Description
The class of the base lrc interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musiclrcparser.h.
Constructor & Destructor Documentation
virtual MusicLrcFromInterface::~MusicLrcFromInterface () virtual default
Object destructor.
Member Function Documentation
const QByteArray & MusicLrcFromInterface::data () const noexcept
Get decode string.
Definition at line 10 of file musiclrcparser.cpp.
References m_data.
Referenced by MusicLrcFromQrc::decode(), MusicLrcFromTrc::decode(), MusicLrcFromYrc::decode(), and MusicLrcAnalysis::loadFromFile().
virtual bool MusicLrcFromInterface::decode (const QString & input) pure virtual
Decode file to lrc by input file.
Implemented in MusicLrcFromYrc, MusicLrcFromTrc, MusicLrcFromQrc, MusicLrcFromKrc, and MusicLrcFromPlain.
Member Data Documentation
QByteArray MusicLrcFromInterface::m_data protected
Definition at line 46 of file musiclrcparser.h.
Referenced by MusicLrcFromKrc::createLrc(), data(), MusicLrcFromPlain::decode(), MusicLrcFromKrc::decode(), MusicLrcFromQrc::decode(), MusicLrcFromTrc::decode(), and MusicLrcFromYrc::decode().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicLrcKits/musiclrcparser.h
TTKModule/TTKCore/musicLrcKits/musiclrcparser.cpp