TTKMusicplayer: MusicPlaylistFoundInfoWidget Class Reference
MusicPlaylistFoundInfoWidget Class Reference
The class of the playlist music found info widget.
#include <musicplaylistfoundinfowidget.h>
Public Slots
void queryAllFinished ()
void downLoadFinished (const QByteArray &data)
void playAllButtonClicked ()
void shareButtonClicked ()
void playButtonClicked ()
void downloadButtonClicked ()
void addButtonClicked ()
Public Member Functions
MusicPlaylistFoundInfoWidget (QWidget *parent=0)
virtual ~MusicPlaylistFoundInfoWidget ()
virtual void resizeWindow ()
void setMusicPlaylistItem (const MusicPlaylistItem &item, QObject *obj)
void setQueryInput (MusicDownLoadQueryThreadAbstract *query)
Public Member Functions inherited from MusicFoundAbstractWidget
MusicFoundAbstractWidget (QWidget *parent=0)
~MusicFoundAbstractWidget ()
virtual void setSongName (const QString &name)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicFoundAbstractWidget
static QString getClassName ()
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
void initFirstWidget ()
void initSecondWidget ()
Protected Member Functions inherited from MusicFoundAbstractWidget
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
Protected Attributes
QLabel * m_iconLabel
QLabel * m_infoLabel
QStackedWidget * m_container
QPushButton * m_songButton
MusicPlaylistFoundTableWidget * m_playlistTableWidget
Protected Attributes inherited from MusicFoundAbstractWidget
QString m_songNameFull
QWidget * m_mainWindow
QLabel * m_statusLabel
QList< QLabel * > m_resizeWidget
Detailed Description
The class of the playlist music found info widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 22 of file musicplaylistfoundinfowidget.h.
Constructor & Destructor Documentation
MusicPlaylistFoundInfoWidget::MusicPlaylistFoundInfoWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 20 of file musicplaylistfoundinfowidget.cpp.
References initFirstWidget(), initSecondWidget(), m_container, m_iconLabel, m_playlistTableWidget, and m_songButton.
MusicPlaylistFoundInfoWidget::~MusicPlaylistFoundInfoWidget () virtual
Definition at line 32 of file musicplaylistfoundinfowidget.cpp.
References m_iconLabel, m_infoLabel, m_playlistTableWidget, and m_songButton.
Member Function Documentation
void MusicPlaylistFoundInfoWidget::addButtonClicked () slot
Add button clicked now.
Definition at line 289 of file musicplaylistfoundinfowidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), and m_playlistTableWidget.
Referenced by initFirstWidget().
void MusicPlaylistFoundInfoWidget::downloadButtonClicked () slot
Download button clicked now.
Definition at line 281 of file musicplaylistfoundinfowidget.cpp.
References MusicFillItemTableWidget::getSelectedItems(), m_playlistTableWidget, and MusicQueryFoundTableWidget::musicDownloadLocal().
Referenced by initFirstWidget().
void MusicPlaylistFoundInfoWidget::downLoadFinished (const QByteArray & data) slot
Query all quality musics is finished.
Definition at line 255 of file musicplaylistfoundinfowidget.cpp.
References m_iconLabel.
Referenced by setMusicPlaylistItem().
QString MusicPlaylistFoundInfoWidget::getClassName () static
Get class object name.
Definition at line 41 of file musicplaylistfoundinfowidget.cpp.
void MusicPlaylistFoundInfoWidget::initFirstWidget () protected
Init the first widget.
Definition at line 300 of file musicplaylistfoundinfowidget.cpp.
References addButtonClicked(), downloadButtonClicked(), m_container, m_playlistTableWidget, and playButtonClicked().
Referenced by MusicPlaylistFoundInfoWidget().
void MusicPlaylistFoundInfoWidget::initSecondWidget () protected
Init the second widget.
Definition at line 351 of file musicplaylistfoundinfowidget.cpp.
References m_container, and m_infoLabel.
Referenced by MusicPlaylistFoundInfoWidget().
void MusicPlaylistFoundInfoWidget::playAllButtonClicked () slot
Play all button clicked now.
Definition at line 265 of file musicplaylistfoundinfowidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), m_playlistTableWidget, and MusicFillItemTableWidget::setSelectedAllItems().
Referenced by setMusicPlaylistItem().
void MusicPlaylistFoundInfoWidget::playButtonClicked () slot
Play button clicked now.
Definition at line 276 of file musicplaylistfoundinfowidget.cpp.
References MusicQueryFoundTableWidget::downloadDataFrom(), and m_playlistTableWidget.
Referenced by initFirstWidget().
void MusicPlaylistFoundInfoWidget::queryAllFinished () slot
Query all quality musics is finished.
Definition at line 249 of file musicplaylistfoundinfowidget.cpp.
References MusicQueryFoundTableWidget::getMusicSongInfos(), m_playlistTableWidget, and m_songButton.
void MusicPlaylistFoundInfoWidget::resizeEvent (QResizeEvent * event) override protected virtual
Override the widget event.
Definition at line 294 of file musicplaylistfoundinfowidget.cpp.
References resizeWindow().
void MusicPlaylistFoundInfoWidget::resizeWindow () virtual
Resize window bound by widgte resize called.
Implements MusicFoundAbstractWidget.
Definition at line 46 of file musicplaylistfoundinfowidget.cpp.
References MusicUtils::Widget::elidedText(), m_playlistTableWidget, MusicFoundAbstractWidget::m_resizeWidget, M_SETTING_PTR, MusicQueryFoundTableWidget::resizeWindow(), MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), and MusicPlaylistFoundWidget::resizeWindow().
void MusicPlaylistFoundInfoWidget::setMusicPlaylistItem (const MusicPlaylistItem & item, QObject * obj)
Set music playlist item.
Definition at line 68 of file musicplaylistfoundinfowidget.cpp.
References downLoadFinished(), MusicUtils::Widget::elidedText(), m_container, MusicPlaylistItem::m_coverUrl, MusicPlaylistItem::m_description, m_iconLabel, MusicPlaylistItem::m_id, m_infoLabel, MusicFoundAbstractWidget::m_mainWindow, MusicPlaylistItem::m_name, MusicPlaylistItem::m_nickname, m_playlistTableWidget, MusicFoundAbstractWidget::m_resizeWidget, m_songButton, MusicFoundAbstractWidget::m_statusLabel, MusicPlaylistItem::m_tags, MusicPlaylistItem::m_updateTime, MusicUIObject::MCheckBoxStyle01, MusicUIObject::MColorStyle04, MusicUIObject::MColorStyle05, MusicUIObject::MFontStyle01, MusicUIObject::MFontStyle03, MusicUIObject::MFontStyle06, MusicUIObject::MPushButtonStyle03, MusicUIObject::MScrollBarStyle01, playAllButtonClicked(), QRCodeQWidget::setIcon(), QRCodeQWidget::setMargin(), shareButtonClicked(), MusicQueryFoundTableWidget::startSearchQuery(), MusicDownloadSourceThread::startToDownload(), and MusicTime::timeSRand().
Referenced by MusicPlaylistFoundWidget::currentPlayListClicked().
void MusicPlaylistFoundInfoWidget::setQueryInput (MusicDownLoadQueryThreadAbstract * query)
Set network query input.
Definition at line 243 of file musicplaylistfoundinfowidget.cpp.
References m_playlistTableWidget, MusicPlaylistFoundTableWidget::setConnectObject(), and MusicPlaylistFoundTableWidget::setQueryInput().
Referenced by MusicPlaylistFoundWidget::currentPlayListClicked().
void MusicPlaylistFoundInfoWidget::shareButtonClicked () slot
Share button clicked now.
Definition at line 271 of file musicplaylistfoundinfowidget.cpp.
Referenced by setMusicPlaylistItem().
Member Data Documentation
QStackedWidget* MusicPlaylistFoundInfoWidget::m_container protected
Definition at line 97 of file musicplaylistfoundinfowidget.h.
Referenced by initFirstWidget(), initSecondWidget(), MusicPlaylistFoundInfoWidget(), and setMusicPlaylistItem().
QLabel* MusicPlaylistFoundInfoWidget::m_iconLabel protected
Definition at line 96 of file musicplaylistfoundinfowidget.h.
Referenced by downLoadFinished(), MusicPlaylistFoundInfoWidget(), setMusicPlaylistItem(), and ~MusicPlaylistFoundInfoWidget().
QLabel * MusicPlaylistFoundInfoWidget::m_infoLabel protected
Definition at line 96 of file musicplaylistfoundinfowidget.h.
Referenced by initSecondWidget(), setMusicPlaylistItem(), and ~MusicPlaylistFoundInfoWidget().
MusicPlaylistFoundTableWidget* MusicPlaylistFoundInfoWidget::m_playlistTableWidget protected
Definition at line 99 of file musicplaylistfoundinfowidget.h.
Referenced by addButtonClicked(), downloadButtonClicked(), initFirstWidget(), MusicPlaylistFoundInfoWidget(), playAllButtonClicked(), playButtonClicked(), queryAllFinished(), resizeWindow(), setMusicPlaylistItem(), setQueryInput(), and ~MusicPlaylistFoundInfoWidget().
QPushButton* MusicPlaylistFoundInfoWidget::m_songButton protected
Definition at line 98 of file musicplaylistfoundinfowidget.h.
Referenced by MusicPlaylistFoundInfoWidget(), queryAllFinished(), setMusicPlaylistItem(), and ~MusicPlaylistFoundInfoWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicplaylistfoundinfowidget.h
TTKModule/TTKWidget/musicWidgetKits/musicplaylistfoundinfowidget.cpp