TTKMusicPlayer: MusicLrcPosterWidget Class Reference
MusicLrcPosterWidget Class Reference
The class of the lrc art poster maker widget.
#include <musiclrcposterwidget.h>
Public Slots
void openButtonClicked ()
void saveButtonClicked ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Public Member Functions
MusicLrcPosterWidget (QWidget *parent=nullptr)
~MusicLrcPosterWidget ()
void setCurrentLrcs (const QStringList &lrcs, const QString &name)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void drawWindowShadow (bool show)
void blockOption (bool block)
Private Attributes
Ui::MusicLrcPosterWidget * m_ui
MusicLrcPosterItemWidget * m_itemWidget
MusicLrcPosterThemeListWidget * m_themeWidget
Additional Inherited Members
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label)
Detailed Description
The class of the lrc art poster maker widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 227 of file musiclrcposterwidget.h.
Constructor & Destructor Documentation
MusicLrcPosterWidget::MusicLrcPosterWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 975 of file musiclrcposterwidget.cpp.
References TTK::Widget::generateHScrollAreaFormat(), TTK::Widget::generateVScrollAreaFormat(), m_itemWidget, m_themeWidget, m_ui, openButtonClicked(), TTK::UI::PushButtonStyle04, saveButtonClicked(), MusicWidgetRenderer::setBackgroundLabel(), and TTK::UI::ToolButtonStyle04.
MusicLrcPosterWidget::~MusicLrcPosterWidget ()
Object destructor.
Definition at line 1007 of file musiclrcposterwidget.cpp.
References m_itemWidget, m_themeWidget, and m_ui.
Member Function Documentation
void MusicLrcPosterWidget::openButtonClicked () slot
Open button clicked.
Definition at line 1020 of file musiclrcposterwidget.cpp.
References TTK::File::getOpenFileName(), m_itemWidget, and MusicLrcPosterItemWidget::setImagePath().
Referenced by MusicLrcPosterWidget().
void MusicLrcPosterWidget::saveButtonClicked () slot
Save button clicked.
Definition at line 1031 of file musiclrcposterwidget.cpp.
References TTK::File::getSaveFileName(), TTKDesktopWrapper::grabWidget(), MusicLrcPosterItemWidget::hasScroll(), ITEM_SCROLL_WIDTH, JPG_FILE_SUFFIX, and m_itemWidget.
Referenced by MusicLrcPosterWidget().
void MusicLrcPosterWidget::setCurrentLrcs (const QStringList & lrcs, const QString & name)
Set current lrc and song name.
Definition at line 1014 of file musiclrcposterwidget.cpp.
References m_itemWidget, m_ui, and MusicLrcPosterItemWidget::setCurrentSongName().
Referenced by MusicLrcContainerForInterior::showLrcPosterWidget().
Member Data Documentation
MusicLrcPosterItemWidget* MusicLrcPosterWidget::m_itemWidget private
Definition at line 259 of file musiclrcposterwidget.h.
Referenced by MusicLrcPosterWidget(), openButtonClicked(), saveButtonClicked(), setCurrentLrcs(), and ~MusicLrcPosterWidget().
MusicLrcPosterThemeListWidget* MusicLrcPosterWidget::m_themeWidget private
Definition at line 260 of file musiclrcposterwidget.h.
Referenced by MusicLrcPosterWidget(), and ~MusicLrcPosterWidget().
Ui::MusicLrcPosterWidget* MusicLrcPosterWidget::m_ui private
Definition at line 258 of file musiclrcposterwidget.h.
Referenced by MusicLrcPosterWidget(), setCurrentLrcs(), and ~MusicLrcPosterWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcposterwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcposterwidget.cpp