TTKMusicPlayer: ReqUnityInterface Namespace Reference
ReqUnityInterface Namespace Reference
The namespace of the unity request interface.
Functions
void parseFromSongProperty (TTK::MusicSongInformation *info, const QString &type, const QString &id, int bitrate)
Detailed Description
The namespace of the unity request interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Function Documentation
void ReqUnityInterface::parseFromSongProperty (TTK::MusicSongInformation * info, const QString & type, const QString & id, int bitrate)
Read tags(size and bitrate and url) from query results.
Definition at line 158 of file musicunityqueryinterface.cpp.
References APPCACHE_DIR_FULL, key, makeModuleValue(), makeQualityValue(), TTK::Algorithm::mdII(), OS_MODULE_A, OS_MODULE_B, OS_PLUGINS_URL, QJson::Parser::parse(), parseSongPropertyA(), parseSongPropertyB(), qAsConst, TTK_ERROR_STREAM, and TTK_INFO_STREAM.
Referenced by parseSongPropertyV3().