TTKMusicplayer: MusicKGQueryInterface Class Reference
MusicKGQueryInterface Class Reference
The class of kugou query interface.
#include <musickgqueryinterface.h>
Public Member Functions
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, const QString &hash) const
void readFromMusicSongProperty (MusicObject::MusicSongInformation *info, const QVariantMap &key, MusicObject::QueryQuality quality, bool all) const
void readFromMusicSongLrcAndPicture (MusicObject::MusicSongInformation *info) const
void readFromMusicSongAlbumInfo (MusicResultsItem *info, const QString &album) const
Detailed Description
The class of kugou query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 75 of file musickgqueryinterface.h.
Member Function Documentation
void MusicKGQueryInterface::readFromMusicSongAlbumInfo (MusicResultsItem * info, const QString & album) const
Read tags(album info) from query results.
Definition at line 115 of file musickgqueryinterface.cpp.
References KG_ALBUM_INFO_URL, MusicResultsItem::m_description, MusicResultsItem::m_nickName, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicObject::syncNetworkQueryForGet(), and TTK_SPLITER.
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), and MusicKGQueryToplistRequest::downLoadFinished().
void MusicKGQueryInterface::readFromMusicSongLrcAndPicture (MusicObject::MusicSongInformation * info) const
Read tags(lrc) from query results.
Definition at line 81 of file musickgqueryinterface.cpp.
References KG_SONG_INFO_URL, KG_SONG_LRC_URL, MusicObject::MusicSongInformation::m_artistId, MusicObject::MusicSongInformation::m_coverUrl, MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongInformation::m_songId, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), and MusicObject::syncNetworkQueryForGet().
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), and MusicKGQueryRequest::downLoadFinished().
void MusicKGQueryInterface::readFromMusicSongProperty (MusicObject::MusicSongInformation * info, const QString & hash) const
Read tags(size) from query results.
Definition at line 11 of file musickgqueryinterface.cpp.
References KG_SONG_DETAIL_URL, MusicObject::MusicSongProperty::m_bitrate, MusicObject::MusicSongProperty::m_format, MusicObject::MusicSongProperty::m_size, MusicObject::MusicSongInformation::m_songProps, MusicObject::MusicSongProperty::m_url, MusicKGInterface::makeRequestRawHeader(), MusicUtils::Algorithm::md5(), MusicUtils::Algorithm::mdII(), QJson::Parser::parse(), MusicUtils::Number::sizeByte2Label(), MusicObject::syncNetworkQueryForGet(), and MusicUtils::Number::transfromBitrateToNormal().
Referenced by MusicKGQueryPlaylistRequest::downloadDetailsFinished(), MusicKGQueryArtistRequest::downLoadFinished(), MusicKGQueryRecommendRequest::downLoadFinished(), MusicKGQueryAlbumRequest::downLoadFinished(), MusicKGQueryToplistRequest::downLoadFinished(), MusicKGQueryRequest::downLoadFinished(), MusicKGQueryRequest::downLoadSingleFinished(), and readFromMusicSongProperty().
void MusicKGQueryInterface::readFromMusicSongProperty (MusicObject::MusicSongInformation * info, const QVariantMap & key, MusicObject::QueryQuality quality, bool all) const
Read tags(size) from query results.
Definition at line 54 of file musickgqueryinterface.cpp.
References MusicObject::LosslessQuality, readFromMusicSongProperty(), MusicObject::StandardQuality, and MusicObject::SuperQuality.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/kg/musickgqueryinterface.cpp