TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/qrencode.h File Reference
qrencode.h File Reference
#include "global.h"
Classes
struct QRcode
QRcode class.
struct _QRcode_List
Singly-linked list of QRcode.
Macros
#define QRSPEC_VERSION_MAX 40
Maximum version (size) of QR-code symbol.
#define MQRSPEC_VERSION_MAX 4
Maximum version (size) of QR-code symbol.
Typedefs
typedef struct _QRinput QRinput
Singly linked list to contain input strings.
typedef struct _QRinput_Struct QRinput_Struct
Set of QRinput for structured symbols.
typedef struct _QRcode_List QRcode_List
Singly-linked list of QRcode.
Enumerations
enum QRencodeMode {
QR_MODE_NUL = -1, QR_MODE_NUM = 0, QR_MODE_AN, QR_MODE_8,
QR_MODE_KANJI, QR_MODE_STRUCTURE, QR_MODE_ECI, QR_MODE_FNC1FIRST,
QR_MODE_FNC1SECOND
}
Encoding mode.
enum QRecLevel { QR_ECLEVEL_L = 0, QR_ECLEVEL_M, QR_ECLEVEL_Q, QR_ECLEVEL_H }
Level of error correction.
Functions
EXTRAS_EXPORT QRinput * QRinput_new (void)
Instantiate an input data object.
EXTRAS_EXPORT QRinput * QRinput_new2 (int version, QRecLevel level)
Instantiate an input data object.
EXTRAS_EXPORT QRinput * QRinput_newMQR (int version, QRecLevel level)
Instantiate an input data object.
EXTRAS_EXPORT int QRinput_append (QRinput *input, QRencodeMode mode, int size, const unsigned char *data)
Append data to an input object.
EXTRAS_EXPORT int QRinput_appendECIheader (QRinput *input, unsigned int ecinum)
Append ECI header.
EXTRAS_EXPORT int QRinput_getVersion (QRinput *input)
Get current version.
EXTRAS_EXPORT int QRinput_setVersion (QRinput *input, int version)
Set version of the QR code that is to be encoded.
EXTRAS_EXPORT QRecLevel QRinput_getErrorCorrectionLevel (QRinput *input)
Get current error correction level.
EXTRAS_EXPORT int QRinput_setErrorCorrectionLevel (QRinput *input, QRecLevel level)
Set error correction level of the QR code that is to be encoded.
EXTRAS_EXPORT int QRinput_setVersionAndErrorCorrectionLevel (QRinput *input, int version, QRecLevel level)
Set version and error correction level of the QR code at once.
EXTRAS_EXPORT void QRinput_free (QRinput *input)
Free the input object.
EXTRAS_EXPORT int QRinput_check (QRencodeMode mode, int size, const unsigned char *data)
Validate the input data.
EXTRAS_EXPORT QRinput_Struct * QRinput_Struct_new (void)
Instantiate a set of input data object.
EXTRAS_EXPORT void QRinput_Struct_setParity (QRinput_Struct *s, unsigned char parity)
Set parity of structured symbols.
EXTRAS_EXPORT int QRinput_Struct_appendInput (QRinput_Struct *s, QRinput *input)
Append a QRinput object to the set.
EXTRAS_EXPORT void QRinput_Struct_free (QRinput_Struct *s)
Free all of QRinput in the set.
EXTRAS_EXPORT QRinput_Struct * QRinput_splitQRinputToStruct (QRinput *input)
Split a QRinput to QRinput_Struct.
EXTRAS_EXPORT int QRinput_Struct_insertStructuredAppendHeaders (QRinput_Struct *s)
Insert structured-append headers to the input structure.
EXTRAS_EXPORT int QRinput_setFNC1First (QRinput *input)
Set FNC1-1st position flag.
EXTRAS_EXPORT int QRinput_setFNC1Second (QRinput *input, unsigned char appid)
Set FNC1-2nd position flag and application identifier.
EXTRAS_EXPORT QRcode * QRcode_encodeInput (QRinput *input)
Create a symbol from the input data.
EXTRAS_EXPORT QRcode * QRcode_encodeString (const char *string, int version, QRecLevel level, QRencodeMode hint, int casesensitive)
Create a symbol from the string.
EXTRAS_EXPORT QRcode * QRcode_encodeString8bit (const char *string, int version, QRecLevel level)
Same to QRcode_encodeString(), but encode whole data in 8-bit mode.
EXTRAS_EXPORT QRcode * QRcode_encodeStringMQR (const char *string, int version, QRecLevel level, QRencodeMode hint, int casesensitive)
Micro QR Code version of QRcode_encodeString().
EXTRAS_EXPORT QRcode * QRcode_encodeString8bitMQR (const char *string, int version, QRecLevel level)
Micro QR Code version of QRcode_encodeString8bit().
EXTRAS_EXPORT QRcode * QRcode_encodeData (int size, const unsigned char *data, int version, QRecLevel level)
Encode byte stream (may include '\0') in 8-bit mode.
EXTRAS_EXPORT QRcode * QRcode_encodeDataMQR (int size, const unsigned char *data, int version, QRecLevel level)
Micro QR Code version of QRcode_encodeData().
EXTRAS_EXPORT void QRcode_free (QRcode *qrcode)
Free the instance of QRcode class.
EXTRAS_EXPORT QRcode_List * QRcode_encodeInputStructured (QRinput_Struct *s)
Create structured symbols from the input data.
EXTRAS_EXPORT QRcode_List * QRcode_encodeStringStructured (const char *string, int version, QRecLevel level, QRencodeMode hint, int casesensitive)
Create structured symbols from the string.
EXTRAS_EXPORT QRcode_List * QRcode_encodeString8bitStructured (const char *string, int version, QRecLevel level)
Same to QRcode_encodeStringStructured(), but encode whole data in 8-bit mode.
EXTRAS_EXPORT QRcode_List * QRcode_encodeDataStructured (int size, const unsigned char *data, int version, QRecLevel level)
Create structured symbols from byte stream (may include '\0').
EXTRAS_EXPORT int QRcode_List_size (QRcode_List *qrlist)
Return the number of symbols included in a QRcode_List.
EXTRAS_EXPORT void QRcode_List_free (QRcode_List *qrlist)
Free the QRcode_List.
EXTRAS_EXPORT void QRcode_APIVersion (int *major_version, int *minor_version, int *micro_version)
Return a string that identifies the library version.
EXTRAS_EXPORT char * QRcode_APIVersionString (void)
Return a string that identifies the library version.
EXTRAS_EXPORT void QRcode_clearCache (void) __attribute__((deprecated))
Macro Definition Documentation
#define MQRSPEC_VERSION_MAX 4
Maximum version (size) of QR-code symbol.
Definition at line 141 of file qrencode.h.
Referenced by MQRspec_getFormatInfo(), MQRspec_newFrame(), QRcode_encodeDataMQR(), QRcode_encodeMaskMQR(), QRcode_encodeString8bitMQR(), QRcode_encodeStringMQR(), QRinput_newMQR(), and QRinput_setVersionAndErrorCorrectionLevel().
#define QRSPEC_VERSION_MAX 40
Maximum version (size) of QR-code symbol.
Definition at line 136 of file qrencode.h.
Referenced by QRcode_encodeMask(), QRinput_new2(), QRinput_setVersion(), QRinput_setVersionAndErrorCorrectionLevel(), QRspec_getMinimumVersion(), QRspec_getVersionPattern(), and QRspec_newFrame().
Typedef Documentation
typedef struct _QRcode_List QRcode_List
Singly-linked list of QRcode.
Used to represent a structured symbols. A list is terminated with NULL.
typedef struct _QRinput QRinput
Singly linked list to contain input strings.
An instance of this class contains its version and error correction level too. It is required to set them by QRinput_setVersion() and QRinput_setErrorCorrectionLevel(), or use QRinput_new2() to instantiate an object.
Definition at line 154 of file qrencode.h.
typedef struct _QRinput_Struct QRinput_Struct
Set of QRinput for structured symbols.
Definition at line 282 of file qrencode.h.
Enumeration Type Documentation
enum QRecLevel
Level of error correction.
Enumerator
QR_ECLEVEL_L
lowest
QR_ECLEVEL_M
QR_ECLEVEL_Q
QR_ECLEVEL_H
highest
Definition at line 126 of file qrencode.h.
enum QRencodeMode
Encoding mode.
Enumerator
QR_MODE_NUL
Terminator (NUL character). Internal use only.
QR_MODE_NUM
Numeric mode.
QR_MODE_AN
Alphabet-numeric mode.
QR_MODE_8
8-bit data mode
QR_MODE_KANJI
Kanji (shift-jis) mode.
QR_MODE_STRUCTURE
Internal use only.
QR_MODE_ECI
ECI mode.
QR_MODE_FNC1FIRST
FNC1, first position.
QR_MODE_FNC1SECOND
FNC1, second position.
Definition at line 111 of file qrencode.h.
Function Documentation
EXTRAS_EXPORT void QRcode_APIVersion (int * major_version, int * minor_version, int * micro_version)
Return a string that identifies the library version.
Parameters
major_version major version number
minor_version minor version number
micro_version micro version number
Definition at line 915 of file qrencode.c.
References MAJOR_VERSION, MICRO_VERSION, and MINOR_VERSION.
EXTRAS_EXPORT char* QRcode_APIVersionString (void)
Return a string that identifies the library version.
Returns
a string identifies the library version. The string is held by the library. Do NOT free it.
Definition at line 928 of file qrencode.c.
References VERSION.
EXTRAS_EXPORT void QRcode_clearCache (void)
Deprecated:
Definition at line 933 of file qrencode.c.
EXTRAS_EXPORT QRcode* QRcode_encodeData (int size, const unsigned char * data, int version, QRecLevel level)
Encode byte stream (may include '\0') in 8-bit mode.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Parameters
size size of the input data.
data input data.
version version of the symbol. If 0, the library chooses the minimum version for the given input data.
level error correction level.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
ERANGE input data is too large.
Definition at line 696 of file qrencode.c.
References QRcode_encodeDataReal().
EXTRAS_EXPORT QRcode* QRcode_encodeDataMQR (int size, const unsigned char * data, int version, QRecLevel level)
Micro QR Code version of QRcode_encodeData().
Warning
This function is THREAD UNSAFE when pthread is disabled.
Definition at line 710 of file qrencode.c.
References MQRSPEC_VERSION_MAX, and QRcode_encodeDataReal().
EXTRAS_EXPORT QRcode_List* QRcode_encodeDataStructured (int size, const unsigned char * data, int version, QRecLevel level)
Create structured symbols from byte stream (may include '\0').
Wholde data are encoded in 8-bit mode.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Parameters
size size of the input data.
data input dat.
version version of the symbol.
level error correction level.
Returns
a singly-linked list of QRcode. On error, NULL is returned, and errno is set to indicate the error. See Exceptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
Definition at line 890 of file qrencode.c.
References QR_MODE_NUL, and QRcode_encodeDataStructuredReal().
Referenced by QRcode_encodeString8bitStructured().
EXTRAS_EXPORT QRcode* QRcode_encodeInput (QRinput * input)
Create a symbol from the input data.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Parameters
input input data.
Returns
an instance of QRcode class. The version of the result QRcode may be larger than the designated version. On error, NULL is returned, and errno is set to indicate the error. See Exceptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
Definition at line 605 of file qrencode.c.
References _QRinput::mqr, QRcode_encodeMask(), and QRcode_encodeMaskMQR().
Referenced by QRcode_encodeDataReal(), QRcode_encodeInputStructured(), and QRcode_encodeStringReal().
EXTRAS_EXPORT QRcode_List* QRcode_encodeInputStructured (QRinput_Struct * s)
Create structured symbols from the input data.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Parameters
s input data, structured.
Returns
a singly-linked list of QRcode.
Definition at line 808 of file qrencode.c.
References _QRcode_List::code, _QRinput_Struct::head, _QRinput_InputList::input, _QRinput_InputList::next, _QRcode_List::next, QRcode_encodeInput(), QRcode_List_free(), and QRcode_List_newEntry().
Referenced by QRcode_encodeInputToStructured().
EXTRAS_EXPORT QRcode* QRcode_encodeString (const char * string, int version, QRecLevel level, QRencodeMode hint, int casesensitive)
Create a symbol from the string.
The library automatically parses the input string and encodes in a QR Code symbol.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Parameters
string input string. It must be NUL terminated.
version version of the symbol. If 0, the library chooses the minimum version for the given input data.
level error correction level.
hint tell the library how Japanese Kanji characters should be encoded. If QR_MODE_KANJI is given, the library assumes that the given string contains Shift-JIS characters and encodes them in Kanji-mode. If QR_MODE_8 is given, all of non-alphanumerical characters will be encoded as is. If you want to embed UTF-8 string, choose this. Other mode will cause EINVAL error.
casesensitive case-sensitive(1) or not(0).
Returns
an instance of QRcode class. The version of the result QRcode may be larger than the designated version. On error, NULL is returned, and errno is set to indicate the error. See Exceptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
ERANGE input data is too large.
Definition at line 647 of file qrencode.c.
References QRcode_encodeStringReal().
Referenced by QRCodeQWidget::paintEvent().
EXTRAS_EXPORT QRcode* QRcode_encodeString8bit (const char * string, int version, QRecLevel level)
Same to QRcode_encodeString(), but encode whole data in 8-bit mode.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Definition at line 701 of file qrencode.c.
References QRcode_encodeDataReal().
EXTRAS_EXPORT QRcode* QRcode_encodeString8bitMQR (const char * string, int version, QRecLevel level)
Micro QR Code version of QRcode_encodeString8bit().
Warning
This function is THREAD UNSAFE when pthread is disabled.
Definition at line 725 of file qrencode.c.
References MQRSPEC_VERSION_MAX, and QRcode_encodeDataReal().
EXTRAS_EXPORT QRcode_List* QRcode_encodeString8bitStructured (const char * string, int version, QRecLevel level)
Same to QRcode_encodeStringStructured(), but encode whole data in 8-bit mode.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Definition at line 894 of file qrencode.c.
References QRcode_encodeDataStructured().
EXTRAS_EXPORT QRcode* QRcode_encodeStringMQR (const char * string, int version, QRecLevel level, QRencodeMode hint, int casesensitive)
Micro QR Code version of QRcode_encodeString().
Warning
This function is THREAD UNSAFE when pthread is disabled.
Definition at line 652 of file qrencode.c.
References MQRSPEC_VERSION_MAX, and QRcode_encodeStringReal().
EXTRAS_EXPORT QRcode_List* QRcode_encodeStringStructured (const char * string, int version, QRecLevel level, QRencodeMode hint, int casesensitive)
Create structured symbols from the string.
The library automatically parses the input string and encodes in a QR Code symbol.
Warning
This function is THREAD UNSAFE when pthread is disabled.
Parameters
string input string. It must be NUL terminated.
version version of the symbol.
level error correction level.
hint tell the library how Japanese Kanji characters should be encoded. If QR_MODE_KANJI is given, the library assumes that the given string contains Shift-JIS characters and encodes them in Kanji-mode. If QR_MODE_8 is given, all of non-alphanumerical characters will be encoded as is. If you want to embed UTF-8 string, choose this. Other mode will cause EINVAL error.
casesensitive case-sensitive(1) or not(0).
Returns
a singly-linked list of QRcode. On error, NULL is returned, and errno is set to indicate the error. See Exceptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory for input objects.
Definition at line 902 of file qrencode.c.
References QRcode_encodeDataStructuredReal().
EXTRAS_EXPORT void QRcode_free (QRcode * qrcode)
Free the instance of QRcode class.
Parameters
qrcode an instance of QRcode class.
Definition at line 421 of file qrencode.c.
References QRcode::data, and free().
Referenced by QRCodeQWidget::paintEvent(), and QRcode_List_freeEntry().
EXTRAS_EXPORT void QRcode_List_free (QRcode_List * qrlist)
Free the QRcode_List.
Parameters
qrlist a head entry of a QRcode_List.
Definition at line 770 of file qrencode.c.
References _QRcode_List::next, and QRcode_List_freeEntry().
Referenced by QRcode_encodeInputStructured().
EXTRAS_EXPORT int QRcode_List_size (QRcode_List * qrlist)
Return the number of symbols included in a QRcode_List.
Parameters
qrlist a head entry of a QRcode_List.
Returns
number of symbols in the list.
Definition at line 781 of file qrencode.c.
References _QRcode_List::next.
EXTRAS_EXPORT int QRinput_append (QRinput * input, QRencodeMode mode, int size, const unsigned char * data)
Append data to an input object.
The data is copied and appended to the input object.
Parameters
input input object.
mode encoding mode.
size size of data (byte).
data a pointer to the memory area of the input data.
Return values
0 success.
-1 an error occurred and errno is set to indeicate the error. See Execptions for the details.
Exceptions
ENOMEM unable to allocate memory.
EINVAL input data is invalid.
Definition at line 221 of file qrinput.c.
References QRinput_appendEntry(), and QRinput_List_newEntry().
Referenced by QRcode_encodeDataReal(), QRcode_encodeDataStructuredReal(), QRinput_appendECIheader(), Split_eat8(), Split_eatAn(), Split_eatKanji(), and Split_eatNum().
EXTRAS_EXPORT int QRinput_appendECIheader (QRinput * input, unsigned int ecinum)
Append ECI header.
Parameters
input input object.
ecinum ECI indicator number (0 - 999999)
Return values
0 success.
-1 an error occurred and errno is set to indeicate the error. See Execptions for the details.
Exceptions
ENOMEM unable to allocate memory.
EINVAL input data is invalid.
Definition at line 274 of file qrinput.c.
References QR_MODE_ECI, and QRinput_append().
EXTRAS_EXPORT int QRinput_check (QRencodeMode mode, int size, const unsigned char * data)
Validate the input data.
Parameters
mode encoding mode.
size size of data (byte).
data a pointer to the memory area of the input data.
Return values
0 success.
-1 invalid arguments.
Definition at line 817 of file qrinput.c.
References QR_MODE_8, QR_MODE_AN, QR_MODE_ECI, QR_MODE_FNC1FIRST, QR_MODE_FNC1SECOND, QR_MODE_KANJI, QR_MODE_NUL, QR_MODE_NUM, QR_MODE_STRUCTURE, QRinput_checkModeAn(), QRinput_checkModeFNC1Second(), QRinput_checkModeKanji(), and QRinput_checkModeNum().
Referenced by QRinput_List_newEntry().
EXTRAS_EXPORT void QRinput_free (QRinput * input)
Free the input object.
All of data chunks in the input object are freed too.
Parameters
input input object.
Definition at line 292 of file qrinput.c.
References free(), _QRinput::head, _QRinput_List::next, and QRinput_List_freeEntry().
Referenced by QRcode_encodeDataReal(), QRcode_encodeDataStructuredReal(), QRcode_encodeStringReal(), QRinput_dup(), QRinput_InputList_freeEntry(), and QRinput_splitQRinputToStruct().
EXTRAS_EXPORT QRecLevel QRinput_getErrorCorrectionLevel (QRinput * input)
Get current error correction level.
Parameters
input input object.
Returns
Current error correcntion level.
Definition at line 172 of file qrinput.c.
References _QRinput::level.
EXTRAS_EXPORT int QRinput_getVersion (QRinput * input)
Get current version.
Parameters
input input object.
Returns
current version.
Definition at line 155 of file qrinput.c.
References _QRinput::version.
Referenced by QRinput_convertData().
EXTRAS_EXPORT QRinput* QRinput_new (void)
Instantiate an input data object.
The version is set to 0 (auto-select) and the error correction level is set to QR_ECLEVEL_L.
Returns
an input object (initialized). On error, NULL is returned and errno is set to indicate the error.
Exceptions
ENOMEM unable to allocate memory.
Definition at line 109 of file qrinput.c.
References QR_ECLEVEL_L, and QRinput_new2().
EXTRAS_EXPORT QRinput* QRinput_new2 (int version, QRecLevel level)
Instantiate an input data object.
Parameters
version version number.
level Error correction level.
Returns
an input object (initialized). On error, NULL is returned and errno is set to indicate the error.
Exceptions
ENOMEM unable to allocate memory for input objects.
EINVAL invalid arguments.
Definition at line 114 of file qrinput.c.
References _QRinput::fnc1, _QRinput::head, _QRinput::level, malloc(), _QRinput::mqr, QR_ECLEVEL_H, QRSPEC_VERSION_MAX, _QRinput::tail, and _QRinput::version.
Referenced by QRcode_encodeDataReal(), QRcode_encodeDataStructuredReal(), QRcode_encodeStringReal(), QRinput_dup(), QRinput_new(), QRinput_newMQR(), and QRinput_splitQRinputToStruct().
EXTRAS_EXPORT QRinput* QRinput_newMQR (int version, QRecLevel level)
Instantiate an input data object.
Object's Micro QR Code flag is set. Unlike with full-sized QR Code, version number must be specified (>0).
Parameters
version version number (1–4).
level Error correction level.
Returns
an input object (initialized). On error, NULL is returned and errno is set to indicate the error.
Exceptions
ENOMEM unable to allocate memory for input objects.
EINVAL invalid arguments.
Definition at line 136 of file qrinput.c.
References _QRinput::mqr, MQRspec_getECCLength(), MQRSPEC_VERSION_MAX, and QRinput_new2().
Referenced by QRcode_encodeDataReal(), QRcode_encodeStringReal(), and QRinput_dup().
EXTRAS_EXPORT int QRinput_setErrorCorrectionLevel (QRinput * input, QRecLevel level)
Set error correction level of the QR code that is to be encoded.
This function cannot be applied to Micro QR Code.
Parameters
input input object.
level Error correction level.
Return values
0 success.
-1 invalid argument.
Definition at line 177 of file qrinput.c.
References _QRinput::level, _QRinput::mqr, and QR_ECLEVEL_H.
EXTRAS_EXPORT int QRinput_setFNC1First (QRinput * input)
Set FNC1-1st position flag.
Definition at line 1616 of file qrinput.c.
References _QRinput::fnc1, and _QRinput::mqr.
EXTRAS_EXPORT int QRinput_setFNC1Second (QRinput * input, unsigned char appid)
Set FNC1-2nd position flag and application identifier.
Definition at line 1627 of file qrinput.c.
References _QRinput::appid, _QRinput::fnc1, and _QRinput::mqr.
EXTRAS_EXPORT int QRinput_setVersion (QRinput * input, int version)
Set version of the QR code that is to be encoded.
This function cannot be applied to Micro QR Code.
Parameters
input input object.
version version number (0 = auto)
Return values
0 success.
-1 invalid argument.
Definition at line 160 of file qrinput.c.
References _QRinput::mqr, QRSPEC_VERSION_MAX, and _QRinput::version.
Referenced by QRinput_convertData().
EXTRAS_EXPORT int QRinput_setVersionAndErrorCorrectionLevel (QRinput * input, int version, QRecLevel level)
Set version and error correction level of the QR code at once.
This function is recommened for Micro QR Code.
Parameters
input input object.
version version number (0 = auto)
level Error correction level.
Return values
0 success.
-1 invalid argument.
Definition at line 189 of file qrinput.c.
References _QRinput::level, _QRinput::mqr, MQRspec_getECCLength(), MQRSPEC_VERSION_MAX, QR_ECLEVEL_H, QRSPEC_VERSION_MAX, and _QRinput::version.
EXTRAS_EXPORT QRinput_Struct* QRinput_splitQRinputToStruct (QRinput * input)
Split a QRinput to QRinput_Struct.
It calculates a parity, set it, then insert structured-append headers. QRinput created by QRinput_newMQR() will be rejected.
Parameters
input input object. Version number and error correction level must be set.
Returns
a set of input data. On error, NULL is returned, and errno is set to indicate the error. See Exceptions for the details.
Exceptions
ERANGE input data is too large.
EINVAL invalid input data.
ENOMEM unable to allocate memory.
Definition at line 1483 of file qrinput.c.
References BitStream_free(), BitStream_new(), BitStream_reset, _QRinput::head, _QRinput::level, MAX_STRUCTURED_SYMBOLS, _QRinput_List::mode, _QRinput::mqr, _QRinput_List::next, QRinput_calcParity(), QRinput_dup(), QRinput_encodeBitStream(), QRinput_estimateBitStreamSizeOfEntry(), QRinput_free(), QRinput_lengthOfCode(), QRinput_new2(), QRinput_splitEntry(), QRinput_Struct_appendInput(), QRinput_Struct_free(), QRinput_Struct_insertStructuredAppendHeaders(), QRinput_Struct_new(), QRinput_Struct_setParity(), QRspec_getDataLength(), _QRinput_Struct::size, STRUCTURE_HEADER_SIZE, _QRinput::tail, and _QRinput::version.
Referenced by QRcode_encodeInputToStructured().
EXTRAS_EXPORT int QRinput_Struct_appendInput (QRinput_Struct * s, QRinput * input)
Append a QRinput object to the set.
QRinput created by QRinput_newMQR() will be rejected.
Warning
never append the same QRinput object twice or more.
Parameters
s structured input object.
input an input object.
Return values
>0 number of input objects in the structure.
-1 an error occurred. See Exceptions for the details.
Exceptions
ENOMEM unable to allocate memory.
EINVAL invalid arguments.
Definition at line 1391 of file qrinput.c.
References _QRinput_Struct::head, _QRinput::mqr, _QRinput_InputList::next, QRinput_InputList_newEntry(), _QRinput_Struct::size, and _QRinput_Struct::tail.
Referenced by QRinput_splitQRinputToStruct().
EXTRAS_EXPORT void QRinput_Struct_free (QRinput_Struct * s)
Free all of QRinput in the set.
Parameters
s a structured input object.
Definition at line 1415 of file qrinput.c.
References free(), _QRinput_Struct::head, _QRinput_InputList::next, and QRinput_InputList_freeEntry().
Referenced by QRcode_encodeInputToStructured(), and QRinput_splitQRinputToStruct().
EXTRAS_EXPORT int QRinput_Struct_insertStructuredAppendHeaders (QRinput_Struct * s)
Insert structured-append headers to the input structure.
It calculates a parity and set it if the parity is not set yet.
Parameters
s input structure
Return values
0 success.
-1 an error occurred and errno is set to indeicate the error. See Execptions for the details.
Exceptions
EINVAL invalid input object.
ENOMEM unable to allocate memory.
Definition at line 1588 of file qrinput.c.
References _QRinput_Struct::head, _QRinput_InputList::input, _QRinput_InputList::next, _QRinput_Struct::parity, QRinput_insertStructuredAppendHeader(), QRinput_Struct_calcParity(), and _QRinput_Struct::size.
Referenced by QRinput_splitQRinputToStruct().
EXTRAS_EXPORT QRinput_Struct* QRinput_Struct_new (void)
Instantiate a set of input data object.
Returns
an instance of QRinput_Struct. On error, NULL is returned and errno is set to indicate the error.
Exceptions
ENOMEM unable to allocate memory.
Definition at line 1371 of file qrinput.c.
References _QRinput_Struct::head, malloc(), _QRinput_Struct::parity, _QRinput_Struct::size, and _QRinput_Struct::tail.
Referenced by QRinput_splitQRinputToStruct().
EXTRAS_EXPORT void QRinput_Struct_setParity (QRinput_Struct * s, unsigned char parity)
Set parity of structured symbols.
Parameters
s structured input object.
parity parity of s.
Definition at line 1386 of file qrinput.c.
References int(), and _QRinput_Struct::parity.
Referenced by QRinput_splitQRinputToStruct(), and QRinput_Struct_calcParity().