TTKMusicPlayer: MusicFileAssociationTableWidget Class Reference
MusicFileAssociationTableWidget Class Reference
The class of the song item selected table widget.
#include <musicfileassociationwidget.h>
Public Slots
virtual void itemCellClicked (int row, int column) override
void checkedItemsStatus (bool checked)
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool checked)
void checkedItemsStatus (bool checked)
Public Slots inherited from TTKAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicFileAssociationTableWidget (QWidget *parent=nullptr)
void uncheckedDataList () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
TTKIntList uncheckedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from TTKAbstractTableWidget
TTKAbstractTableWidget (QWidget *parent=nullptr)
~TTKAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
void addCellItems ()
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractTableWidget
void setRowColor (int row, const QColor &color) const
bool isValid () const
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from TTKAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the song item selected table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musicfileassociationwidget.h.
Constructor & Destructor Documentation
MusicFileAssociationTableWidget::MusicFileAssociationTableWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 6 of file musicfileassociationwidget.cpp.
References addCellItems(), and TTK::UI::ScrollBarStyle01.
Member Function Documentation
void MusicFileAssociationTableWidget::addCellItems () private
Create cell items by input data.
Definition at line 65 of file musicfileassociationwidget.cpp.
References MusicSettingManager::FileAssociationValue, G_SETTING_PTR, QtItemSetTextAlignment, MusicFormats::supportMusicFormats(), and TTK_CHECKED_ROLE.
Referenced by MusicFileAssociationTableWidget().
void MusicFileAssociationTableWidget::checkedItemsStatus (bool checked) slot
Checked items status.
Definition at line 55 of file musicfileassociationwidget.cpp.
References MusicFillItemTableWidget::checkedItemsStatus().
void MusicFileAssociationTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 42 of file musicfileassociationwidget.cpp.
References TTK_CHECKED_ROLE, and TTKStaticCast.
void MusicFileAssociationTableWidget::uncheckedDataList () const
Get unchecked data items.
Definition at line 25 of file musicfileassociationwidget.cpp.
References MusicSettingManager::FileAssociationValue, G_SETTING_PTR, and MusicFillItemTableWidget::uncheckedIndexList().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicfileassociationwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicfileassociationwidget.cpp