TTKMusicPlayer: MusicSquareQueryItemWidget Class Reference
MusicSquareQueryItemWidget Class Reference
The class of the square query item widget.
#include <musicqueryitemwidget.h>
Public Slots
void downloadFinished (const QByteArray &bytes)
void renderFinished (const QPixmap &data)
void itemClicked ()
Signals
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicSquareQueryItemWidget (QWidget *parent=nullptr)
~MusicSquareQueryItemWidget ()
void setShowTime (bool v) noexcept
void setShowCount (bool v) noexcept
void setValueLabel (bool v) noexcept
void setResultDataItem (const MusicResultDataItem &item, MusicCoverRequest *cover)
Static Public Attributes
static constexpr int WIDTH_LABEL_SIZE = 150
static constexpr int HEIGHT_LABEL_SIZE = 200
static constexpr int LINE_SPACING_SIZE = 150
Private Attributes
bool m_showTime
bool m_showCount
TTKClickedLabel * m_iconLabel
QLabel * m_nameLabel
QLabel * m_valueLabel
QPushButton * m_listenButton
QPushButton * m_playButton
MusicResultDataItem m_itemData
Detailed Description
The class of the square query item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicqueryitemwidget.h.
Constructor & Destructor Documentation
MusicSquareQueryItemWidget::MusicSquareQueryItemWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicqueryitemwidget.cpp.
References TTK::UI::BackgroundStyle04, TTK::UI::BorderStyle01, TTK::UI::ColorStyle03, TTK::UI::ColorStyle06, HEIGHT_LABEL_SIZE, itemClicked(), m_iconLabel, m_listenButton, m_nameLabel, m_playButton, m_valueLabel, TTK::UI::PushButtonStyle01, TTK::UI::TinyBtnPlaylist, TTK_DEFAULT_STR, and WIDTH_LABEL_SIZE.
MusicSquareQueryItemWidget::~MusicSquareQueryItemWidget ()
Object destructor.
Definition at line 45 of file musicqueryitemwidget.cpp.
References m_iconLabel, m_listenButton, m_nameLabel, m_playButton, and m_valueLabel.
Member Function Documentation
void MusicSquareQueryItemWidget::currentItemClicked (const MusicResultDataItem & item) signal
Current item clicked.
Referenced by itemClicked().
void MusicSquareQueryItemWidget::downloadFinished (const QByteArray & bytes) slot
Download data from net finished.
Definition at line 102 of file musicqueryitemwidget.cpp.
References m_iconLabel, renderFinished(), MusicImageRenderer::setInputData(), TTKAbstractThread::start(), and TTK_ERROR_STREAM.
Referenced by setResultDataItem().
void MusicSquareQueryItemWidget::itemClicked () slot
Current item clicked.
Definition at line 123 of file musicqueryitemwidget.cpp.
References currentItemClicked(), and m_itemData.
Referenced by MusicSquareQueryItemWidget().
void MusicSquareQueryItemWidget::renderFinished (const QPixmap & data) slot
Image render finished.
Definition at line 116 of file musicqueryitemwidget.cpp.
References m_iconLabel, m_listenButton, and m_playButton.
Referenced by downloadFinished().
void MusicSquareQueryItemWidget::setResultDataItem (const MusicResultDataItem & item, MusicCoverRequest * cover)
Set media results item.
Definition at line 54 of file musicqueryitemwidget.cpp.
References downloadFinished(), TTK::Widget::elidedText(), TTK::isCoverValid(), MusicResultDataItem::m_count, MusicResultDataItem::m_coverUrl, m_itemData, m_listenButton, MusicResultDataItem::m_name, m_nameLabel, MusicResultDataItem::m_nickName, m_showCount, m_showTime, MusicResultDataItem::m_time, m_valueLabel, MusicCoverRequest::startToRequest(), and WIDTH_LABEL_SIZE.
Referenced by MusicArtistAlbumsQueryWidget::createArtistAlbumsItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), MusicItemRecommendQueryWidget::createResultItem(), and MusicItemMoreRecommendQueryWidget::createResultItem().
void MusicSquareQueryItemWidget::setShowCount (bool v) inline noexcept
Set show count label option.
Definition at line 56 of file musicqueryitemwidget.h.
Referenced by MusicArtistAlbumsQueryWidget::createArtistAlbumsItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), MusicItemRecommendQueryWidget::createResultItem(), and MusicItemMoreRecommendQueryWidget::createResultItem().
void MusicSquareQueryItemWidget::setShowTime (bool v) inline noexcept
Set show time label option.
Definition at line 52 of file musicqueryitemwidget.h.
Referenced by MusicArtistAlbumsQueryWidget::createArtistAlbumsItem(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), MusicItemRecommendQueryWidget::createResultItem(), and MusicItemMoreRecommendQueryWidget::createResultItem().
void MusicSquareQueryItemWidget::setValueLabel (bool v) inline noexcept
Set show value label option.
Definition at line 60 of file musicqueryitemwidget.h.
Referenced by MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicItemRecommendQueryWidget::createResultItem(), and MusicItemMoreRecommendQueryWidget::createResultItem().
Member Data Documentation
constexpr int MusicSquareQueryItemWidget::HEIGHT_LABEL_SIZE = 200 static
Definition at line 36 of file musicqueryitemwidget.h.
Referenced by MusicSquareQueryItemWidget().
constexpr int MusicSquareQueryItemWidget::LINE_SPACING_SIZE = 150 static
Definition at line 37 of file musicqueryitemwidget.h.
Referenced by MusicArtistAlbumsQueryWidget::createArtistAlbumsItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), MusicItemRecommendQueryWidget::createResultItem(), MusicItemMoreRecommendQueryWidget::createResultItem(), MusicArtistMvsQueryWidget::resizeGeometry(), MusicWebDJRadioQueryWidget::resizeGeometry(), MusicPlaylistQueryWidget::resizeGeometry(), MusicArtistAlbumsQueryWidget::resizeGeometry(), MusicItemRecommendQueryWidget::resizeGeometry(), and MusicItemMoreRecommendQueryWidget::resizeGeometry().
TTKClickedLabel* MusicSquareQueryItemWidget::m_iconLabel private
Definition at line 89 of file musicqueryitemwidget.h.
Referenced by downloadFinished(), MusicSquareQueryItemWidget(), renderFinished(), and ~MusicSquareQueryItemWidget().
MusicResultDataItem MusicSquareQueryItemWidget::m_itemData private
Definition at line 92 of file musicqueryitemwidget.h.
Referenced by itemClicked(), and setResultDataItem().
QPushButton* MusicSquareQueryItemWidget::m_listenButton private
Definition at line 91 of file musicqueryitemwidget.h.
Referenced by MusicSquareQueryItemWidget(), renderFinished(), setResultDataItem(), and ~MusicSquareQueryItemWidget().
QLabel* MusicSquareQueryItemWidget::m_nameLabel private
Definition at line 90 of file musicqueryitemwidget.h.
Referenced by MusicSquareQueryItemWidget(), setResultDataItem(), and ~MusicSquareQueryItemWidget().
QPushButton * MusicSquareQueryItemWidget::m_playButton private
Definition at line 91 of file musicqueryitemwidget.h.
Referenced by MusicSquareQueryItemWidget(), renderFinished(), and ~MusicSquareQueryItemWidget().
bool MusicSquareQueryItemWidget::m_showCount private
Definition at line 88 of file musicqueryitemwidget.h.
Referenced by setResultDataItem().
bool MusicSquareQueryItemWidget::m_showTime private
Definition at line 88 of file musicqueryitemwidget.h.
Referenced by setResultDataItem().
QLabel * MusicSquareQueryItemWidget::m_valueLabel private
Definition at line 90 of file musicqueryitemwidget.h.
Referenced by MusicSquareQueryItemWidget(), setResultDataItem(), and ~MusicSquareQueryItemWidget().
constexpr int MusicSquareQueryItemWidget::WIDTH_LABEL_SIZE = 150 static
Definition at line 35 of file musicqueryitemwidget.h.
Referenced by MusicSquareQueryItemWidget(), and setResultDataItem().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicqueryitemwidget.h
TTKModule/TTKWidget/musicCoreKits/musicqueryitemwidget.cpp