TTKMusicplayer: MusicDownLoadQueryThreadAbstract Class Reference
MusicDownLoadQueryThreadAbstract Class Reference abstract
The class to abstract query download data from net.
#include <musicdownloadquerythreadabstract.h>
Public Types
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals
void clearAllItems ()
void createSearchedItems (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
virtual void startToSearch (QueryType type, const QString &text)=0
virtual void startToSingleSearch (const QString &text)
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
void setQueryType (QueryType type)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
const MusicObject::MusicSongInformations & getMusicSongInfos () const
QString mapQueryServerString () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
virtual void startToPage (int offset)
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Protected Member Functions
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
bool findUrlFileSize (MusicObject::MusicSongAttribute *attr)
bool findUrlFileSize (MusicObject::MusicSongAttributes *attrs)
qint64 getUrlFileSize (const QString &url)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Detailed Description
The class to abstract query download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 83 of file musicdownloadquerythreadabstract.h.
Member Enumeration Documentation
enum MusicDownLoadQueryThreadAbstract::QueryType
Enumerator
MusicQuery
query music
MovieQuery
query movie
LrcQuery
query lrc
OtherQuery
query external
Definition at line 87 of file musicdownloadquerythreadabstract.h.
Constructor & Destructor Documentation
MusicDownLoadQueryThreadAbstract::MusicDownLoadQueryThreadAbstract (QObject * parent = 0) explicit
Object contsructor.
Definition at line 5 of file musicdownloadquerythreadabstract.cpp.
References m_queryAllRecords, m_queryExtraMovie, m_queryServer, m_querySimplify, and m_searchQuality.
MusicDownLoadQueryThreadAbstract::~MusicDownLoadQueryThreadAbstract () virtual
Definition at line 15 of file musicdownloadquerythreadabstract.cpp.
References MusicDownLoadPagingThread::deleteAll().
Member Function Documentation
void MusicDownLoadQueryThreadAbstract::clearAllItems () signal
Clear all items before the new query start.
Referenced by MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistListThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryXMArtistListThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryQQArtistListThread::downLoadFinished(), MusicDownLoadQueryKWArtistListThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDArtistListThread::downLoadFinished(), MusicDownLoadQueryKGArtistListThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryWYArtistListThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryWSPlaylistThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryMGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), and MusicDownLoadQueryXMMovieThread::singleDownLoadFinished().
void MusicDownLoadQueryThreadAbstract::createSearchedItems (const MusicSearchedItem & songItem) signal
Create the current items by song name\ artist name and time.
Referenced by MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryMGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), and MusicDownLoadQueryWYMovieThread::startMVListQuery().
QString MusicDownLoadQueryThreadAbstract::findTimeStringByAttrs (const MusicObject::MusicSongAttributes & attrs) protected
Find time string by attrs.
Definition at line 55 of file musicdownloadquerythreadabstract.cpp.
References MusicObject::MusicSongAttribute::m_duration.
Referenced by MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeIQY(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), and MusicDownLoadQueryBDMovieThread::singleDownLoadFinished().
bool MusicDownLoadQueryThreadAbstract::findUrlFileSize (MusicObject::MusicSongAttribute * attr) protected
Find download file size.
Definition at line 68 of file musicdownloadquerythreadabstract.cpp.
References getUrlFileSize(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, MusicNetworkAbstract::m_manager, MusicObject::MusicSongAttribute::m_size, MusicNetworkAbstract::m_stateCode, MusicObject::MusicSongAttribute::m_url, and MusicUtils::Number::size2Label().
Referenced by MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), findUrlFileSize(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryKWMovieThread::readFromMusicMVAttribute(), MusicDownLoadQueryBDMovieThread::readFromMusicMVAttributeWeb(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), and MusicDownLoadQueryWYMovieThread::startMVListQuery().
bool MusicDownLoadQueryThreadAbstract::findUrlFileSize (MusicObject::MusicSongAttributes * attrs) protected
Find download file size.
Definition at line 80 of file musicdownloadquerythreadabstract.cpp.
References findUrlFileSize().
QString MusicDownLoadQueryThreadAbstract::getClassName () static
Get class object name.
Definition at line 20 of file musicdownloadquerythreadabstract.cpp.
const MusicObject::MusicSongInformations& MusicDownLoadQueryThreadAbstract::getMusicSongInfos () const inline
Return the current song container.
Definition at line 165 of file musicdownloadquerythreadabstract.h.
Referenced by MusicSongSearchOnlineTableWidget::actionGroupClick(), MusicQueryFoundTableWidget::addSearchMusicToPlayList(), MusicSongSearchOnlineTableWidget::addSearchMusicToPlayList(), MusicSongSearchOnlineTableWidget::auditionToMusic(), MusicSongSharingWidget::confirmButtonClicked(), MusicQueryFoundTableWidget::contextMenuEvent(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicQueryFoundTableWidget::downloadBatchData(), MusicQueryFoundTableWidget::downloadDataFrom(), MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicVideoTableWidget::downloadLocalMovie(), MusicDownloadWidget::getMatchMusicSongInformation(), MusicVideoTableWidget::getMusicMvInfo(), MusicQueryTableWidget::getMusicSongInfos(), MusicVideoTableWidget::itemDoubleClicked(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicSoundKMicroSearchTableWidget::musicDownloadLocal(), MusicQueryFoundTableWidget::musicDownloadLocal(), MusicSongSearchOnlineTableWidget::musicDownloadLocal(), MusicDownloadStatusObject::musicHaveNoLrcAlready(), MusicSongSearchOnlineTableWidget::musicSongDownload(), MusicAlbumFoundWidget::queryAllFinished(), MusicArtistFoundWidget::queryAllFinished(), MusicQueryFoundTableWidget::searchChanged(), MusicWYTranslationThread::startToDownload(), MusicQQSongCommentsThread::startToSearch(), MusicMGSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicWSSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicBDSongCommentsThread::startToSearch(), MusicXMSongCommentsThread::startToSearch(), and MusicWYSongCommentsThread::startToSearch().
bool MusicDownLoadQueryThreadAbstract::getQueryAllRecords () const inline
Get query all records flag.
Definition at line 133 of file musicdownloadquerythreadabstract.h.
QString MusicDownLoadQueryThreadAbstract::getQueryServer () const inline
Return the current song query server.
Definition at line 157 of file musicdownloadquerythreadabstract.h.
Referenced by MusicSongSharingWidget::confirmButtonClicked(), MusicArtistListFoundWidget::createArtistListItems(), MusicToplistFoundWidget::createLabels(), MusicPlaylistFoundWidget::createPlaylistItems(), MusicDownLoadQueryFactory::getAlbumThread(), MusicDownLoadQueryFactory::getArtistListThread(), MusicDownLoadQueryFactory::getArtistThread(), MusicDownLoadQueryFactory::getMovieThread(), MusicDownLoadQueryFactory::getPlaylistThread(), MusicDownLoadQueryFactory::getQueryThread(), MusicDownLoadQueryFactory::getRecommendThread(), MusicDownLoadQueryFactory::getToplistThread(), MusicVideoTableWidget::itemDoubleClicked(), and MusicFoundAbstractWidget::shareButtonClicked().
bool MusicDownLoadQueryThreadAbstract::getQuerySimplify () const inline
Get query simplify flag.
Definition at line 141 of file musicdownloadquerythreadabstract.h.
QueryType MusicDownLoadQueryThreadAbstract::getQueryType () const inline
Return the current song query type.
Definition at line 153 of file musicdownloadquerythreadabstract.h.
QString MusicDownLoadQueryThreadAbstract::getSearchedText () const inline
Return the current song name.
Definition at line 161 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownloadWidget::getMatchMusicSongInformation(), and MusicLrcSearchTableWidget::musicDownloadLocal().
QString MusicDownLoadQueryThreadAbstract::getSearchQuality () const inline
Get search data quality.
Definition at line 125 of file musicdownloadquerythreadabstract.h.
Referenced by MusicSongSearchOnlineTableWidget::startSearchQuery(), and MusicSongSearchOnlineTableWidget::startSearchSingleQuery().
qint64 MusicDownLoadQueryThreadAbstract::getUrlFileSize (const QString & url) protected
Get download file size.
Definition at line 93 of file musicdownloadquerythreadabstract.cpp.
References MusicSemaphoreLoop::exec(), and MusicNetworkAbstract::setSslConfiguration().
Referenced by findUrlFileSize().
QString MusicDownLoadQueryThreadAbstract::mapQueryServerString () const
Map query server string.
Definition at line 30 of file musicdownloadquerythreadabstract.cpp.
References m_queryServer.
Referenced by MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryMGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), and MusicDownLoadQueryWYMovieThread::startMVListQuery().
void MusicDownLoadQueryThreadAbstract::setQueryAllRecords (bool state) inline
Set wheather query all quality of records.
Definition at line 129 of file musicdownloadquerythreadabstract.h.
Referenced by MusicToplistFoundWidget::categoryChanged(), MusicAlbumFoundWidget::setSongName(), MusicToplistFoundWidget::setSongName(), MusicDownloadWidget::setSongName(), MusicArtistFoundWidget::setSongName(), MusicQueryFoundTableWidget::startSearchQuery(), MusicSongSearchOnlineTableWidget::startSearchQuery(), MusicSongSearchOnlineTableWidget::startSearchSingleQuery(), MusicWYTranslationThread::startToDownload(), MusicQQSongCommentsThread::startToSearch(), MusicMGSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicWSSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicBDSongCommentsThread::startToSearch(), MusicXMSongCommentsThread::startToSearch(), and MusicWYSongCommentsThread::startToSearch().
void MusicDownLoadQueryThreadAbstract::setQueryExtraMovie (bool state) inline
Set query extra movie flag.
Definition at line 145 of file musicdownloadquerythreadabstract.h.
Referenced by MusicSoundKMicroSearchTableWidget::startSearchQuery().
void MusicDownLoadQueryThreadAbstract::setQuerySimplify (bool state) inline
Set query simplify mode.
Definition at line 137 of file musicdownloadquerythreadabstract.h.
Referenced by MusicAlbumFoundWidget::setSongName(), MusicArtistFoundWidget::setSongName(), MusicWYTranslationThread::startToDownload(), MusicQQSongCommentsThread::startToSearch(), MusicKGSongCommentsThread::startToSearch(), MusicMGSongCommentsThread::startToSearch(), MusicWSSongCommentsThread::startToSearch(), MusicBDSongCommentsThread::startToSearch(), MusicKWSongCommentsThread::startToSearch(), MusicXMSongCommentsThread::startToSearch(), and MusicWYSongCommentsThread::startToSearch().
void MusicDownLoadQueryThreadAbstract::setQueryType (QueryType type) inline
Return the current song query type.
Definition at line 149 of file musicdownloadquerythreadabstract.h.
Referenced by MusicVideoTableWidget::startSearchSingleQuery().
void MusicDownLoadQueryThreadAbstract::setSearchQuality (const QString & qual) inline
Set search data quality.
Definition at line 121 of file musicdownloadquerythreadabstract.h.
Referenced by MusicSongSearchOnlineTableWidget::setSearchQuality(), MusicSongSearchOnlineTableWidget::startSearchQuery(), and MusicSongSearchOnlineTableWidget::startSearchSingleQuery().
virtual void MusicDownLoadQueryThreadAbstract::startToSearch (QueryType type, const QString & text) pure virtual
Start to search data from name and type. Subclass should implement this function.
Implemented in MusicDownLoadQueryXMMovieThread, MusicDownLoadQueryKWThread, MusicDownLoadQueryBDPlaylistThread, MusicDownLoadQueryBDToplistThread, MusicDownLoadQueryKGPlaylistThread, MusicDownLoadQueryKGThread, MusicDownLoadQueryKGToplistThread, MusicDownLoadQueryKWPlaylistThread, MusicDownLoadQueryKWToplistThread, MusicDownLoadQueryMGPlaylistThread, MusicDownLoadQueryMGToplistThread, MusicDownLoadQueryQQPlaylistThread, MusicDownLoadQueryQQToplistThread, MusicDJRadioProgramCategoryThread, MusicDownLoadQueryWSPlaylistThread, MusicDownLoadQueryWSToplistThread, MusicDownLoadQueryWYPlaylistThread, MusicDownLoadQueryWYToplistThread, MusicDownLoadQueryXMPlaylistThread, MusicDownLoadQueryXMThread, MusicDownLoadQueryXMToplistThread, MusicDownLoadQueryBDMovieThread, MusicDownLoadQueryBDThread, MusicDownLoadQueryKGMovieThread, MusicDownLoadQueryMGMovieThread, MusicDownLoadQueryMGThread, MusicDownLoadQueryQQThread, MusicDownLoadQueryWSThread, MusicDownLoadQueryWYMovieThread, MusicDownLoadQueryWYThread, MusicDownLoadQueryBDLearnThread, MusicDownLoadQueryKWMovieThread, MusicDownLoadQueryAlbumThread, MusicDownLoadQueryArtistListThread, MusicDownLoadQueryArtistThread, MusicDownLoadQueryRecommendThread, MusicDownLoadQueryToplistThread, MusicDownLoadQueryQQMovieThread, MusicDownLoadQueryWSMovieThread, and MusicDownLoadQueryYYTThread.
Referenced by MusicToplistFoundWidget::categoryChanged(), MusicPlaylistFoundWidget::categoryChanged(), MusicSongSharingWidget::confirmButtonClicked(), MusicIdentifySongsWidget::createDetectedSuccessedWidget(), MusicDownloadStatusObject::musicCheckHasLrcAlready(), MusicArtistListFoundWidget::numberButtonClicked(), MusicAlbumFoundWidget::setSongName(), MusicToplistFoundWidget::setSongName(), MusicArtistListFoundWidget::setSongName(), MusicPlaylistFoundWidget::setSongName(), MusicDownloadWidget::setSongName(), MusicWebDJRadioFoundWidget::setSongName(), MusicArtistFoundWidget::setSongName(), MusicLrcSearchTableWidget::startSearchQuery(), MusicSoundKMicroSearchTableWidget::startSearchQuery(), MusicQueryFoundTableWidget::startSearchQuery(), MusicVideoTableWidget::startSearchQuery(), and MusicSongSearchOnlineTableWidget::startSearchQuery().
void MusicDownLoadQueryThreadAbstract::startToSingleSearch (const QString & text) virtual
Start to search single data from id. Subclass should implement this function.
Reimplemented in MusicDownLoadQueryXMMovieThread, MusicDownLoadQueryKWThread, MusicDownLoadQueryBDMovieThread, MusicDownLoadQueryKGMovieThread, MusicDownLoadQueryMGMovieThread, MusicDownLoadQueryWYMovieThread, MusicDownLoadQueryKWMovieThread, MusicDownLoadQueryQQMovieThread, MusicDownLoadQueryBDAlbumThread, MusicDownLoadQueryKGThread, MusicDownLoadQueryKWAlbumThread, MusicDownLoadQueryMGAlbumThread, MusicDownLoadQueryQQAlbumThread, MusicDownLoadQueryWYAlbumThread, MusicDownLoadQueryXMAlbumThread, MusicDownLoadQueryXMThread, MusicDownLoadQueryBDThread, MusicDownLoadQueryKGAlbumThread, MusicDownLoadQueryMGThread, MusicDownLoadQueryQQThread, and MusicDownLoadQueryWYThread.
Definition at line 25 of file musicdownloadquerythreadabstract.cpp.
Referenced by MusicArtistAlbumsFoundWidget::setSongName(), MusicArtistAlbumsFoundWidget::setSongNameById(), MusicVideoTableWidget::startSearchSingleQuery(), and MusicSongSearchOnlineTableWidget::startSearchSingleQuery().
Member Data Documentation
QueryType MusicDownLoadQueryThreadAbstract::m_currentType protected
Definition at line 202 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryYYTThread::startToSearch(), MusicDownLoadQueryWSMovieThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryWYThread::startToSearch(), MusicDownLoadQueryWSThread::startToSearch(), MusicDownLoadQueryMGMovieThread::startToSearch(), MusicDownLoadQueryQQThread::startToSearch(), MusicDownLoadQueryBDThread::startToSearch(), MusicDownLoadQueryMGThread::startToSearch(), MusicDownLoadQueryXMThread::startToSearch(), MusicDownLoadQueryKGThread::startToSearch(), MusicDownLoadQueryKWThread::startToSearch(), and MusicDownLoadQueryXMMovieThread::startToSearch().
MusicObject::MusicSongInformations MusicDownLoadQueryThreadAbstract::m_musicSongInfos protected
Definition at line 199 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryYYTThread::downLoadFinished(), MusicDownLoadQueryBDLearnThread::downLoadFinished(), MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryQQRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistListThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryXMArtistListThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryQQArtistListThread::downLoadFinished(), MusicDownLoadQueryKWArtistListThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDArtistListThread::downLoadFinished(), MusicDownLoadQueryKGArtistListThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryWYArtistListThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryKGPlaylistThread::downLoadFinished(), MusicDownLoadQueryXMPlaylistThread::downLoadFinished(), MusicDownLoadQueryMGPlaylistThread::downLoadFinished(), MusicDownLoadQueryQQPlaylistThread::downLoadFinished(), MusicDownLoadQueryWYPlaylistThread::downLoadFinished(), MusicDownLoadQueryBDPlaylistThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::downLoadFinished(), MusicDownLoadQueryWSPlaylistThread::downLoadFinished(), MusicDJRadioProgramCategoryThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryQQThread::singleDownLoadFinished(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), MusicDownLoadQueryXMThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryMGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), and MusicDownLoadQueryWYMovieThread::startMVListQuery().
bool MusicDownLoadQueryThreadAbstract::m_queryAllRecords protected
Definition at line 203 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryThreadAbstract(), and MusicDownLoadQueryXMThread::singleDownLoadFinished().
bool MusicDownLoadQueryThreadAbstract::m_queryExtraMovie protected
Definition at line 203 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), and MusicDownLoadQueryThreadAbstract().
QString MusicDownLoadQueryThreadAbstract::m_queryServer protected
Definition at line 201 of file musicdownloadquerythreadabstract.h.
Referenced by mapQueryServerString(), MusicDJRadioProgramCategoryThread::MusicDJRadioProgramCategoryThread(), MusicDownLoadQueryBDAlbumThread::MusicDownLoadQueryBDAlbumThread(), MusicDownLoadQueryBDArtistListThread::MusicDownLoadQueryBDArtistListThread(), MusicDownLoadQueryBDArtistThread::MusicDownLoadQueryBDArtistThread(), MusicDownLoadQueryBDLearnThread::MusicDownLoadQueryBDLearnThread(), MusicDownLoadQueryBDMovieThread::MusicDownLoadQueryBDMovieThread(), MusicDownLoadQueryBDPlaylistThread::MusicDownLoadQueryBDPlaylistThread(), MusicDownLoadQueryBDRecommendThread::MusicDownLoadQueryBDRecommendThread(), MusicDownLoadQueryBDThread::MusicDownLoadQueryBDThread(), MusicDownLoadQueryBDToplistThread::MusicDownLoadQueryBDToplistThread(), MusicDownLoadQueryKGAlbumThread::MusicDownLoadQueryKGAlbumThread(), MusicDownLoadQueryKGArtistListThread::MusicDownLoadQueryKGArtistListThread(), MusicDownLoadQueryKGArtistThread::MusicDownLoadQueryKGArtistThread(), MusicDownLoadQueryKGMovieThread::MusicDownLoadQueryKGMovieThread(), MusicDownLoadQueryKGPlaylistThread::MusicDownLoadQueryKGPlaylistThread(), MusicDownLoadQueryKGRecommendThread::MusicDownLoadQueryKGRecommendThread(), MusicDownLoadQueryKGThread::MusicDownLoadQueryKGThread(), MusicDownLoadQueryKGToplistThread::MusicDownLoadQueryKGToplistThread(), MusicDownLoadQueryKWAlbumThread::MusicDownLoadQueryKWAlbumThread(), MusicDownLoadQueryKWArtistListThread::MusicDownLoadQueryKWArtistListThread(), MusicDownLoadQueryKWArtistThread::MusicDownLoadQueryKWArtistThread(), MusicDownLoadQueryKWMovieThread::MusicDownLoadQueryKWMovieThread(), MusicDownLoadQueryKWPlaylistThread::MusicDownLoadQueryKWPlaylistThread(), MusicDownLoadQueryKWRecommendThread::MusicDownLoadQueryKWRecommendThread(), MusicDownLoadQueryKWThread::MusicDownLoadQueryKWThread(), MusicDownLoadQueryKWToplistThread::MusicDownLoadQueryKWToplistThread(), MusicDownLoadQueryMGAlbumThread::MusicDownLoadQueryMGAlbumThread(), MusicDownLoadQueryMGArtistListThread::MusicDownLoadQueryMGArtistListThread(), MusicDownLoadQueryMGArtistThread::MusicDownLoadQueryMGArtistThread(), MusicDownLoadQueryMGMovieThread::MusicDownLoadQueryMGMovieThread(), MusicDownLoadQueryMGPlaylistThread::MusicDownLoadQueryMGPlaylistThread(), MusicDownLoadQueryMGRecommendThread::MusicDownLoadQueryMGRecommendThread(), MusicDownLoadQueryMGThread::MusicDownLoadQueryMGThread(), MusicDownLoadQueryMGToplistThread::MusicDownLoadQueryMGToplistThread(), MusicDownLoadQueryQQAlbumThread::MusicDownLoadQueryQQAlbumThread(), MusicDownLoadQueryQQArtistListThread::MusicDownLoadQueryQQArtistListThread(), MusicDownLoadQueryQQArtistThread::MusicDownLoadQueryQQArtistThread(), MusicDownLoadQueryQQMovieThread::MusicDownLoadQueryQQMovieThread(), MusicDownLoadQueryQQPlaylistThread::MusicDownLoadQueryQQPlaylistThread(), MusicDownLoadQueryQQRecommendThread::MusicDownLoadQueryQQRecommendThread(), MusicDownLoadQueryQQThread::MusicDownLoadQueryQQThread(), MusicDownLoadQueryQQToplistThread::MusicDownLoadQueryQQToplistThread(), MusicDownLoadQueryThreadAbstract(), MusicDownLoadQueryWSAlbumThread::MusicDownLoadQueryWSAlbumThread(), MusicDownLoadQueryWSArtistListThread::MusicDownLoadQueryWSArtistListThread(), MusicDownLoadQueryWSArtistThread::MusicDownLoadQueryWSArtistThread(), MusicDownLoadQueryWSMovieThread::MusicDownLoadQueryWSMovieThread(), MusicDownLoadQueryWSPlaylistThread::MusicDownLoadQueryWSPlaylistThread(), MusicDownLoadQueryWSRecommendThread::MusicDownLoadQueryWSRecommendThread(), MusicDownLoadQueryWSThread::MusicDownLoadQueryWSThread(), MusicDownLoadQueryWSToplistThread::MusicDownLoadQueryWSToplistThread(), MusicDownLoadQueryWYAlbumThread::MusicDownLoadQueryWYAlbumThread(), MusicDownLoadQueryWYArtistListThread::MusicDownLoadQueryWYArtistListThread(), MusicDownLoadQueryWYArtistThread::MusicDownLoadQueryWYArtistThread(), MusicDownLoadQueryWYMovieThread::MusicDownLoadQueryWYMovieThread(), MusicDownLoadQueryWYPlaylistThread::MusicDownLoadQueryWYPlaylistThread(), MusicDownLoadQueryWYRecommendThread::MusicDownLoadQueryWYRecommendThread(), MusicDownLoadQueryWYThread::MusicDownLoadQueryWYThread(), MusicDownLoadQueryWYToplistThread::MusicDownLoadQueryWYToplistThread(), MusicDownLoadQueryXMAlbumThread::MusicDownLoadQueryXMAlbumThread(), MusicDownLoadQueryXMArtistListThread::MusicDownLoadQueryXMArtistListThread(), MusicDownLoadQueryXMArtistThread::MusicDownLoadQueryXMArtistThread(), MusicDownLoadQueryXMMovieThread::MusicDownLoadQueryXMMovieThread(), MusicDownLoadQueryXMPlaylistThread::MusicDownLoadQueryXMPlaylistThread(), MusicDownLoadQueryXMRecommendThread::MusicDownLoadQueryXMRecommendThread(), MusicDownLoadQueryXMThread::MusicDownLoadQueryXMThread(), MusicDownLoadQueryXMToplistThread::MusicDownLoadQueryXMToplistThread(), and MusicDownLoadQueryYYTThread::MusicDownLoadQueryYYTThread().
bool MusicDownLoadQueryThreadAbstract::m_querySimplify protected
Definition at line 203 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), and MusicDownLoadQueryThreadAbstract().
QString MusicDownLoadQueryThreadAbstract::m_searchQuality protected
Definition at line 200 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryWSThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryBDRecommendThread::downLoadFinished(), MusicDownLoadQueryKWArtistThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWSRecommendThread::downLoadFinished(), MusicDownLoadQueryKWRecommendThread::downLoadFinished(), MusicDownLoadQueryKGRecommendThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryWYRecommendThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryMGRecommendThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryXMRecommendThread::downLoadFinished(), MusicDownLoadQueryQQThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryBDThread::downLoadFinished(), MusicDownLoadQueryWYThread::downLoadFinished(), MusicDownLoadQueryMGThread::downLoadFinished(), MusicDownLoadQueryWSToplistThread::downLoadFinished(), MusicDownLoadQueryBDAlbumThread::downLoadFinished(), MusicDownLoadQueryQQToplistThread::downLoadFinished(), MusicDownLoadQueryMGAlbumThread::downLoadFinished(), MusicDownLoadQueryXMThread::downLoadFinished(), MusicDownLoadQueryKGThread::downLoadFinished(), MusicDownLoadQueryKWToplistThread::downLoadFinished(), MusicDownLoadQueryWYAlbumThread::downLoadFinished(), MusicDownLoadQueryXMAlbumThread::downLoadFinished(), MusicDownLoadQueryWYToplistThread::downLoadFinished(), MusicDownLoadQueryBDToplistThread::downLoadFinished(), MusicDownLoadQueryMGToplistThread::downLoadFinished(), MusicDownLoadQueryXMToplistThread::downLoadFinished(), MusicDownLoadQueryKGToplistThread::downLoadFinished(), MusicDownLoadQueryQQAlbumThread::downLoadFinished(), MusicDownLoadQueryKWAlbumThread::downLoadFinished(), MusicDownLoadQueryQQArtistThread::downLoadFinished(), MusicDownLoadQueryKWThread::downLoadFinished(), MusicDownLoadQueryKWPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWYPlaylistThread::getDetailsFinished(), MusicDownLoadQueryWSPlaylistThread::getDetailsFinished(), MusicDownLoadQueryQQPlaylistThread::getDetailsFinished(), MusicDownLoadQueryXMPlaylistThread::getDetailsFinished(), MusicDownLoadQueryKGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryMGPlaylistThread::getDetailsFinished(), MusicDownLoadQueryBDPlaylistThread::getDetailsFinished(), MusicDJRadioProgramCategoryThread::getDetailsFinished(), MusicDownLoadQueryThreadAbstract(), MusicDownLoadQueryWYThread::singleDownLoadFinished(), MusicDownLoadQueryBDThread::singleDownLoadFinished(), MusicDownLoadQueryMGThread::singleDownLoadFinished(), MusicDownLoadQueryKGThread::singleDownLoadFinished(), and MusicDownLoadQueryXMThread::singleDownLoadFinished().
QString MusicDownLoadQueryThreadAbstract::m_searchText protected
Definition at line 200 of file musicdownloadquerythreadabstract.h.
Referenced by MusicDownLoadQueryWSMovieThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::downLoadFinished(), MusicDownLoadQueryKGArtistThread::downLoadFinished(), MusicDownLoadQueryWSArtistThread::downLoadFinished(), MusicDownLoadQueryWYArtistThread::downLoadFinished(), MusicDownLoadQueryMGArtistThread::downLoadFinished(), MusicDownLoadQueryXMArtistThread::downLoadFinished(), MusicDownLoadQueryKGAlbumThread::downLoadFinished(), MusicDownLoadQueryQQMovieThread::downLoadFinished(), MusicDownLoadQueryKWMovieThread::downLoadFinished(), MusicDownLoadQueryBDMovieThread::downLoadFinished(), MusicDownLoadQueryWYMovieThread::downLoadFinished(), MusicDownLoadQueryKGMovieThread::downLoadFinished(), MusicDownLoadQueryMGMovieThread::downLoadFinished(), MusicDownLoadQueryXMMovieThread::downLoadFinished(), MusicDownLoadQueryBDArtistThread::getDownLoadIntro(), MusicDownLoadQueryKWArtistThread::getDownLoadIntro(), MusicDownLoadQueryWSArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYArtistThread::getDownLoadIntro(), MusicDownLoadQueryKGArtistThread::getDownLoadIntro(), MusicDownLoadQueryXMArtistThread::getDownLoadIntro(), MusicDownLoadQueryQQArtistThread::getDownLoadIntro(), MusicDownLoadQueryWYMovieThread::pageDownLoadFinished(), MusicDownLoadQueryBDMovieThread::readFromMusicMVCount(), MusicDownLoadQueryMGAlbumThread::singleDownLoadFinished(), MusicDownLoadQueryQQMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKWMovieThread::singleDownLoadFinished(), MusicDownLoadQueryBDMovieThread::singleDownLoadFinished(), MusicDownLoadQueryWYMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryMGMovieThread::singleDownLoadFinished(), MusicDownLoadQueryXMMovieThread::singleDownLoadFinished(), MusicDownLoadQueryKGArtistListThread::startToPage(), MusicDownLoadQueryBDArtistListThread::startToPage(), MusicDownLoadQueryMGArtistListThread::startToPage(), MusicDownLoadQueryXMArtistListThread::startToPage(), MusicDownLoadQueryQQArtistListThread::startToPage(), MusicDownLoadQueryKWArtistListThread::startToPage(), MusicDownLoadQueryWYArtistListThread::startToPage(), MusicDownLoadQueryQQMovieThread::startToPage(), MusicDownLoadQueryKWMovieThread::startToPage(), MusicDownLoadQueryWYMovieThread::startToPage(), MusicDownLoadQueryMGMovieThread::startToPage(), MusicDownLoadQueryBDMovieThread::startToPage(), MusicDownLoadQueryKGMovieThread::startToPage(), MusicDownLoadQueryQQPlaylistThread::startToPage(), MusicDJRadioProgramCategoryThread::startToPage(), MusicDownLoadQueryWSPlaylistThread::startToPage(), MusicDownLoadQueryKWPlaylistThread::startToPage(), MusicDownLoadQueryXMPlaylistThread::startToPage(), MusicDownLoadQueryWYPlaylistThread::startToPage(), MusicDownLoadQueryBDPlaylistThread::startToPage(), MusicDownLoadQueryMGPlaylistThread::startToPage(), MusicDownLoadQueryKGPlaylistThread::startToPage(), MusicDownLoadQueryXMMovieThread::startToPage(), MusicDownLoadQueryYYTThread::startToSearch(), MusicDownLoadQueryKWMovieThread::startToSearch(), MusicDownLoadQueryWSMovieThread::startToSearch(), MusicDownLoadQueryMovieThread::startToSearch(), MusicDownLoadQueryQQMovieThread::startToSearch(), MusicDownLoadQueryKGAlbumThread::startToSearch(), MusicDownLoadQueryQQThread::startToSearch(), MusicDownLoadQueryWYMovieThread::startToSearch(), MusicDownLoadQueryKGMovieThread::startToSearch(), MusicDownLoadQueryWYThread::startToSearch(), MusicDownLoadQueryMGMovieThread::startToSearch(), MusicDownLoadQueryWSThread::startToSearch(), MusicDownLoadQueryMGThread::startToSearch(), MusicDownLoadQueryBDMovieThread::startToSearch(), MusicDownLoadQueryBDThread::startToSearch(), MusicDownLoadQueryBDPlaylistThread::startToSearch(), MusicDownLoadQueryKWArtistThread::startToSearch(), MusicDownLoadQueryXMThread::startToSearch(), MusicDownLoadQueryKGPlaylistThread::startToSearch(), MusicDownLoadQueryMGArtistThread::startToSearch(), MusicDownLoadQueryQQPlaylistThread::startToSearch(), MusicDownLoadQueryXMAlbumThread::startToSearch(), MusicDJRadioProgramCategoryThread::startToSearch(), MusicDownLoadQueryWSArtistThread::startToSearch(), MusicDownLoadQueryBDArtistThread::startToSearch(), MusicDownLoadQueryWSPlaylistThread::startToSearch(), MusicDownLoadQueryWYArtistThread::startToSearch(), MusicDownLoadQueryBDRecommendThread::startToSearch(), MusicDownLoadQueryWYPlaylistThread::startToSearch(), MusicDownLoadQueryKWPlaylistThread::startToSearch(), MusicDownLoadQueryMGPlaylistThread::startToSearch(), MusicDownLoadQueryMGRecommendThread::startToSearch(), MusicDownLoadQueryQQRecommendThread::startToSearch(), MusicDownLoadQueryKGArtistThread::startToSearch(), MusicDownLoadQueryXMArtistThread::startToSearch(), MusicDownLoadQueryXMPlaylistThread::startToSearch(), MusicDownLoadQueryWYRecommendThread::startToSearch(), MusicDownLoadQueryKGThread::startToSearch(), MusicDownLoadQueryMGArtistListThread::startToSearch(), MusicDownLoadQueryBDArtistListThread::startToSearch(), MusicDownLoadQueryWSArtistListThread::startToSearch(), MusicDownLoadQueryKWArtistListThread::startToSearch(), MusicDownLoadQueryKGArtistListThread::startToSearch(), MusicDownLoadQueryQQArtistListThread::startToSearch(), MusicDownLoadQueryXMArtistListThread::startToSearch(), MusicDownLoadQueryWYArtistListThread::startToSearch(), MusicDownLoadQueryKWThread::startToSearch(), MusicDownLoadQueryQQArtistThread::startToSearch(), MusicDownLoadQueryXMMovieThread::startToSearch(), MusicDownLoadQueryMGAlbumThread::startToSingleSearch(), MusicDownLoadQueryKWMovieThread::startToSingleSearch(), MusicDownLoadQueryQQMovieThread::startToSingleSearch(), MusicDownLoadQueryKGMovieThread::startToSingleSearch(), MusicDownLoadQueryWYMovieThread::startToSingleSearch(), MusicDownLoadQueryMGMovieThread::startToSingleSearch(), MusicDownLoadQueryBDMovieThread::startToSingleSearch(), and MusicDownLoadQueryXMMovieThread::startToSingleSearch().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/musicdownloadquerythreadabstract.h
TTKModule/TTKCore/musicNetworkKits/musicdownloadquerythreadabstract.cpp