TTKMusicplayer: MusicDownloadStatusObject Class Reference
MusicDownloadStatusObject Class Reference
The class of the show download state object.
#include <musicdownloadstatusobject.h>
Public Slots
void musicHaveNoLrcAlready ()
void showDownLoadInfoFor (MusicObject::DownLoadMode type)
void showDownLoadInfoFinished (const QString &type)
void networkConnectionStateChanged (bool state)
Public Member Functions
MusicDownloadStatusObject (QObject *parent)
~MusicDownloadStatusObject ()
void musicCheckHasLrcAlready ()
bool checkSettingParameterValue () const
Static Public Member Functions
static QString getClassName ()
Protected Attributes
bool m_previousState
MusicApplication * m_parentWidget
MusicDownLoadQueryThreadAbstract * m_downloadLrcThread
Detailed Description
The class of the show download state object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicdownloadstatusobject.h.
Constructor & Destructor Documentation
MusicDownloadStatusObject::MusicDownloadStatusObject (QObject * parent) explicit
Object contsructor.
Definition at line 16 of file musicdownloadstatusobject.cpp.
References MusicNetworkThread::getClassName(), getClassName(), MusicSongSearchOnlineTableWidget::getClassName(), M_CONNECTION_PTR, m_downloadLrcThread, m_parentWidget, m_previousState, and MStatic_cast.
MusicDownloadStatusObject::~MusicDownloadStatusObject ()
Definition at line 30 of file musicdownloadstatusobject.cpp.
References m_downloadLrcThread.
Member Function Documentation
bool MusicDownloadStatusObject::checkSettingParameterValue () const
Check the setting has open inline or desktop lrc on or not.
Definition at line 95 of file musicdownloadstatusobject.cpp.
References M_SETTING_PTR, MusicSettingManager::ShowDesktopLrcChoiced, and MusicSettingManager::ShowInlineLrcChoiced.
Referenced by musicCheckHasLrcAlready().
QString MusicDownloadStatusObject::getClassName () static
Get class object name.
Definition at line 35 of file musicdownloadstatusobject.cpp.
Referenced by MusicDownLoadManager::connectNetworkMultiValue(), MusicDownloadStatusObject(), MusicLrcLocalLinkWidget::MusicLrcLocalLinkWidget(), and MusicConnectionPool::poolConnect().
void MusicDownloadStatusObject::musicCheckHasLrcAlready ()
Check the current song already has lrc or not, if not just download it.
Check there is no opening lyrics display mode
Check if the file exists
Start the request query
Definition at line 101 of file musicdownloadstatusobject.cpp.
References MusicApplication::checkMusicListCurrentIndex(), checkSettingParameterValue(), MusicObject::DW_Buffing, MusicObject::DW_DisConnection, MusicApplication::getCurrentFileName(), KRC_FILE, LRC_FILE, MusicUtils::Core::lrcPrefix(), M_DOWNLOAD_QUERY_PTR, m_downloadLrcThread, M_NETWORK_PTR, m_parentWidget, musicHaveNoLrcAlready(), MusicDownLoadQueryThreadAbstract::MusicQuery, showDownLoadInfoFor(), and MusicDownLoadQueryThreadAbstract::startToSearch().
Referenced by MusicRightAreaWidget::musicCheckHasLrcAlready().
void MusicDownloadStatusObject::musicHaveNoLrcAlready () slot
Download current music lrc from net.
download lrc
download art picture
download big picture
Definition at line 137 of file musicdownloadstatusobject.cpp.
References ART_DIR_FULL, MusicUtils::String::artistName(), MusicDownLoadThreadAbstract::DownloadLrc, MusicDownLoadThreadAbstract::DownloadSmallBG, MusicObject::DW_DisConnection, MusicApplication::getCurrentFileName(), MusicDownLoadQueryThreadAbstract::getMusicSongInfos(), LRC_FILE, MusicUtils::Core::lrcPrefix(), M_DOWNLOAD_QUERY_PTR, m_downloadLrcThread, MusicObject::MusicSongInformation::m_lrcUrl, M_NETWORK_PTR, m_parentWidget, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songName, showDownLoadInfoFinished(), showDownLoadInfoFor(), SKN_FILE, MusicUtils::String::songName(), and MusicUtils::String::splitString().
Referenced by musicCheckHasLrcAlready().
void MusicDownloadStatusObject::networkConnectionStateChanged (bool state) slot
Show current net connect state changed by net thread.
Definition at line 78 of file musicdownloadstatusobject.cpp.
References MusicObject::DW_DisConnection, MusicObject::DW_Null, MusicBottomAreaWidget::instance(), M_NETWORK_PTR, m_previousState, showDownLoadInfoFor(), and MusicBottomAreaWidget::showMessage().
void MusicDownloadStatusObject::showDownLoadInfoFinished (const QString & type) slot
Show download state string type. This is a slot by MusicSongSearchOnlineWidget's emit
If the lyrics download finished immediately loaded to display
Definition at line 65 of file musicdownloadstatusobject.cpp.
References m_parentWidget, MusicApplication::musicLoadCurrentSongLrc(), and MusicApplication::updateCurrentArtist().
Referenced by musicHaveNoLrcAlready().
void MusicDownloadStatusObject::showDownLoadInfoFor (MusicObject::DownLoadMode type) slot
Show download state type. This is a slot by MusicSongSearchOnlineWidget's emit
Definition at line 40 of file musicdownloadstatusobject.cpp.
References MusicObject::DW_Buffing, MusicObject::DW_DisConnection, MusicObject::DW_DownLoading, MusicObject::DW_Null, MusicObject::DW_Waiting, and M_LOGGER_INFO.
Referenced by musicCheckHasLrcAlready(), musicHaveNoLrcAlready(), and networkConnectionStateChanged().
Member Data Documentation
MusicDownLoadQueryThreadAbstract* MusicDownloadStatusObject::m_downloadLrcThread protected
Definition at line 78 of file musicdownloadstatusobject.h.
Referenced by musicCheckHasLrcAlready(), MusicDownloadStatusObject(), musicHaveNoLrcAlready(), and ~MusicDownloadStatusObject().
MusicApplication* MusicDownloadStatusObject::m_parentWidget protected
Definition at line 77 of file musicdownloadstatusobject.h.
Referenced by musicCheckHasLrcAlready(), MusicDownloadStatusObject(), musicHaveNoLrcAlready(), and showDownLoadInfoFinished().
bool MusicDownloadStatusObject::m_previousState protected
Definition at line 76 of file musicdownloadstatusobject.h.
Referenced by MusicDownloadStatusObject(), and networkConnectionStateChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadstatusobject.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadstatusobject.cpp