TTKMusicplayer: MusicSongSearchTableWidget Class Reference
MusicSongSearchTableWidget Class Reference
The class of the song search online table widget.
#include <musicsongsearchonlinewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) overridefinal
virtual void clearAllItems () overridefinal
virtual void createSearchedItem (const MusicSearchedItem &songItem) overridefinal
virtual void itemDoubleClicked (int row, int column) overridefinal
virtual void actionGroupClick (QAction *action) overridefinal
void musicSongDownload (int row)
Public Slots inherited from MusicItemSearchTableWidget
virtual void itemCellClicked (int row, int column) override
virtual void clearAllItems () override
virtual void actionGroupClick (QAction *action)
virtual void itemDoubleClicked (int row, int column)=0
void createFinishedItem ()
Public Slots inherited from MusicQueryTableWidget
virtual void clearAllItems ()=0
virtual void createSearchedItem (const MusicSearchedItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void setSelectedAllItems (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)=0
Public Member Functions
MusicSongSearchTableWidget (QWidget *parent=nullptr)
~MusicSongSearchTableWidget ()
void setQueryAllRecords (bool state)
virtual void startSearchQuery (const QString &text) overridefinal
void startSearchSingleQuery (const QString &text)
virtual void musicDownloadLocal (int row) overridefinal
void setSearchQuality (MusicObject::QueryQuality quality)
void resizeWindow ()
Public Member Functions inherited from MusicItemSearchTableWidget
MusicItemSearchTableWidget (QWidget *parent=nullptr)
~MusicItemSearchTableWidget ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
virtual void setQueryInput (MusicAbstractQueryRequest *query)
MusicAbstractQueryRequest * getQueryInput ()
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList selectedItems () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
void clear ()
TTKIntList multiSelectedIndex () const
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
void addSearchMusicToPlaylist (int row, bool play)
Protected Member Functions inherited from MusicItemSearchTableWidget
void createContextMenu (QMenu &menu)
QString randSimulation () const
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes
bool m_queryAllRecords
Protected Attributes inherited from MusicItemSearchTableWidget
MusicGifLabelWidget * m_loadingLabel
QActionGroup * m_actionGroup
MusicLabelDelegate * m_labelDelegate
Protected Attributes inherited from MusicQueryTableWidget
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
MusicCheckBoxDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_backgroundColor
int m_previousColorRow
int m_previousClickRow
Friends
class MusicSongSearchOnlineWidget
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void songBufferToPlaylist (const MusicResultsItem &songItem)
void restartSearchQuery (const QString &name)
Detailed Description
The class of the song search online table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 32 of file musicsongsearchonlinewidget.h.
Constructor & Destructor Documentation
MusicSongSearchTableWidget::MusicSongSearchTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 18 of file musicsongsearchonlinewidget.cpp.
References G_CONNECTION_PTR, and m_queryAllRecords.
MusicSongSearchTableWidget::~MusicSongSearchTableWidget ()
Definition at line 38 of file musicsongsearchonlinewidget.cpp.
References clearAllItems().
Member Function Documentation
void MusicSongSearchTableWidget::actionGroupClick (QAction * action) final override virtual slot
Left context menu action group click by action.
Definition at line 235 of file musicsongsearchonlinewidget.cpp.
References addSearchMusicToPlaylist(), MusicRightAreaWidget::instance(), MusicQueryTableWidget::m_networkRequest, MusicRightAreaWidget::musicAlbumFound(), MusicRightAreaWidget::musicArtistFound(), musicDownloadLocal(), musicSongDownload(), MusicQueryTableWidget::restartSearchQuery(), and MusicAbstractQueryRequest::songInfoList().
void MusicSongSearchTableWidget::addSearchMusicToPlaylist (int row, bool play) protected
Add search music to play list by index.
Definition at line 299 of file musicsongsearchonlinewidget.cpp.
References G_NETWORK_PTR, MusicResultsItem::m_description, MusicObject::MusicSongProperty::m_format, MusicResultsItem::m_id, MusicResultsItem::m_name, MusicQueryTableWidget::m_networkRequest, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicObject::MusicSongProperty::m_size, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, MusicObject::MusicSongProperty::m_url, MusicToastLabel::popup(), MusicAbstractQueryRequest::queryServer(), MusicQueryTableWidget::songBufferToPlaylist(), MusicAbstractQueryRequest::songInfoList(), TTK_DOT, and TTK_DOTDOT.
Referenced by actionGroupClick(), MusicSongSearchOnlineWidget::buttonClicked(), itemCellClicked(), and itemDoubleClicked().
void MusicSongSearchTableWidget::clearAllItems () final override virtual slot
Clear All Items.
Definition at line 170 of file musicsongsearchonlinewidget.cpp.
References MusicItemSearchTableWidget::clearAllItems().
Referenced by startSearchQuery(), startSearchSingleQuery(), and ~MusicSongSearchTableWidget().
void MusicSongSearchTableWidget::contextMenuEvent (QContextMenuEvent * event) final override protected virtual
Definition at line 278 of file musicsongsearchonlinewidget.cpp.
References MusicItemSearchTableWidget::createContextMenu(), and MusicItemSearchTableWidget::m_actionGroup.
void MusicSongSearchTableWidget::createSearchedItem (const MusicSearchedItem & songItem) final override virtual slot
Create searched items.
Definition at line 176 of file musicsongsearchonlinewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicSearchedItem::m_albumName, MusicSearchedItem::m_duration, MusicSearchedItem::m_singerName, MusicSearchedItem::m_songName, MusicSearchedItem::m_type, MusicUIObject::MQSSColor02, MUSIC_CHECK_ROLE, QtItemSetForegroundColor, and MusicItemSearchTableWidget::randSimulation().
void MusicSongSearchTableWidget::itemCellClicked (int row, int column) final override virtual slot
Table widget item cell click.
Definition at line 159 of file musicsongsearchonlinewidget.cpp.
References addSearchMusicToPlaylist(), MusicItemSearchTableWidget::itemCellClicked(), and musicDownloadLocal().
void MusicSongSearchTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 146 of file musicsongsearchonlinewidget.cpp.
References MusicAbstractTableWidget::itemCellEntered().
void MusicSongSearchTableWidget::itemDoubleClicked (int row, int column) final override virtual slot
Item has double clicked.
Definition at line 226 of file musicsongsearchonlinewidget.cpp.
References addSearchMusicToPlaylist().
void MusicSongSearchTableWidget::musicDownloadLocal (int row) final override virtual
Data download to local file.
Implements MusicQueryTableWidget.
Definition at line 106 of file musicsongsearchonlinewidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::MusicQuery, MusicDownloadWidget::setSongName(), MusicDownloadWidget::show(), and MusicAbstractQueryRequest::songInfoList().
Referenced by actionGroupClick(), and itemCellClicked().
void MusicSongSearchTableWidget::musicSongDownload (int row) slot
Open music song download widget.
Definition at line 259 of file musicsongsearchonlinewidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::MusicQuery, and MusicAbstractQueryRequest::songInfoList().
Referenced by actionGroupClick().
void MusicSongSearchTableWidget::resizeEvent (QResizeEvent * event) final override protected virtual
Override the widget event.
Reimplemented from MusicItemSearchTableWidget.
Definition at line 272 of file musicsongsearchonlinewidget.cpp.
References MusicItemSearchTableWidget::resizeEvent(), and resizeWindow().
void MusicSongSearchTableWidget::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 125 of file musicsongsearchonlinewidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), and MusicSongSearchOnlineWidget::resizeWindow().
void MusicSongSearchTableWidget::setQueryAllRecords (bool state) inline
Set wheather query all quality of records.
Definition at line 46 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchOnlineWidget::startSearchQuery(), and MusicSongSearchOnlineWidget::startSearchSingleQuery().
void MusicSongSearchTableWidget::setSearchQuality (MusicObject::QueryQuality quality)
Set search data quality.
Definition at line 119 of file musicsongsearchonlinewidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::setQueryQuality(), and MusicItemSearchTableWidget::startSearchQuery().
Referenced by MusicSongSearchOnlineWidget::researchQueryByQuality().
void MusicSongSearchTableWidget::startSearchQuery (const QString & text) final override virtual
Start search query by text.
Reimplemented from MusicItemSearchTableWidget.
Definition at line 43 of file musicsongsearchonlinewidget.cpp.
References clearAllItems(), MusicSongSearchRecordConfigManager::fromFile(), G_NETWORK_PTR, MusicItemSearchTableWidget::m_loadingLabel, MusicSearchRecord::m_name, MusicQueryTableWidget::m_networkRequest, m_queryAllRecords, MusicSearchRecord::m_timestamp, MusicAbstractQueryRequest::MusicQuery, MusicAbstractQueryRequest::queryQuality(), MusicSongSearchRecordConfigManager::readBuffer(), MusicGifLabelWidget::run(), MusicAbstractQueryRequest::setQueryAllRecords(), MusicAbstractQueryRequest::setQueryQuality(), MusicItemSearchTableWidget::startSearchQuery(), MusicAbstractQueryRequest::startToSearch(), MusicTime::timestamp(), and MusicSongSearchRecordConfigManager::writeBuffer().
Referenced by MusicSongSearchOnlineWidget::startSearchQuery().
void MusicSongSearchTableWidget::startSearchSingleQuery (const QString & text)
Start search query by given id.
Definition at line 82 of file musicsongsearchonlinewidget.cpp.
References clearAllItems(), G_NETWORK_PTR, MusicItemSearchTableWidget::m_loadingLabel, MusicQueryTableWidget::m_networkRequest, m_queryAllRecords, MusicAbstractQueryRequest::queryQuality(), MusicGifLabelWidget::run(), MusicAbstractQueryRequest::setQueryAllRecords(), MusicAbstractQueryRequest::setQueryQuality(), MusicItemSearchTableWidget::startSearchQuery(), and MusicAbstractQueryRequest::startToSingleSearch().
Referenced by MusicSongSearchOnlineWidget::startSearchSingleQuery().
Friends And Related Function Documentation
friend class MusicSongSearchOnlineWidget friend
Definition at line 112 of file musicsongsearchonlinewidget.h.
Member Data Documentation
bool MusicSongSearchTableWidget::m_queryAllRecords protected
Definition at line 111 of file musicsongsearchonlinewidget.h.
Referenced by MusicSongSearchTableWidget(), startSearchQuery(), and startSearchSingleQuery().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongsearchonlinewidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongsearchonlinewidget.cpp