TTKMusicplayer: MusicVideoBarrageStylePopWidget Class Reference
MusicVideoBarrageStylePopWidget Class Reference
The class of the video varrage style popup widget.
#include <musicvideobarragestylepopwidget.h>
Public Slots
void barrageSizeButtonClicked (int index)
void barrageColorButtonClicked (int index)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicVideoBarrageStylePopWidget (QWidget *MusicToolMenuWidget=nullptr)
~MusicVideoBarrageStylePopWidget ()
int barrageSize () const
QColor barrageColor () const
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initialize ()
Protected Attributes
int m_barrageSize
QColor m_barrageColor
QButtonGroup * m_sizeGroup
QButtonGroup * m_colorGroup
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the video varrage style popup widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicvideobarragestylepopwidget.h.
Constructor & Destructor Documentation
MusicVideoBarrageStylePopWidget::MusicVideoBarrageStylePopWidget (QWidget * MusicToolMenuWidget = nullptr) explicit
Object contsructor.
Definition at line 7 of file musicvideobarragestylepopwidget.cpp.
References initialize(), m_barrageColor, and m_barrageSize.
MusicVideoBarrageStylePopWidget::~MusicVideoBarrageStylePopWidget ()
Definition at line 15 of file musicvideobarragestylepopwidget.cpp.
References m_colorGroup, and m_sizeGroup.
Member Function Documentation
QColor MusicVideoBarrageStylePopWidget::barrageColor () const
Get barrage color.
Definition at line 26 of file musicvideobarragestylepopwidget.cpp.
References m_barrageColor.
Referenced by MusicVideoControlWidget::sendBarrageClicked().
void MusicVideoBarrageStylePopWidget::barrageColorButtonClicked (int index) slot
Barrage color button clicked by index.
Definition at line 65 of file musicvideobarragestylepopwidget.cpp.
References m_barrageColor, m_colorGroup, MusicUIObject::MQSSVideoBtnBlue, MusicUIObject::MQSSVideoBtnBlueOn, MusicUIObject::MQSSVideoBtnGreen, MusicUIObject::MQSSVideoBtnGreenOn, MusicUIObject::MQSSVideoBtnOrange, MusicUIObject::MQSSVideoBtnOrangeOn, MusicUIObject::MQSSVideoBtnPurple, MusicUIObject::MQSSVideoBtnPurpleOn, MusicUIObject::MQSSVideoBtnRed, MusicUIObject::MQSSVideoBtnRedOn, MusicUIObject::MQSSVideoBtnWhite, MusicUIObject::MQSSVideoBtnWhiteOn, MusicUIObject::MQSSVideoBtnYellow, and MusicUIObject::MQSSVideoBtnYellowOn.
Referenced by initialize().
int MusicVideoBarrageStylePopWidget::barrageSize () const
Get barrage size.
Definition at line 21 of file musicvideobarragestylepopwidget.cpp.
References m_barrageSize.
Referenced by MusicVideoControlWidget::sendBarrageClicked().
void MusicVideoBarrageStylePopWidget::barrageSizeButtonClicked (int index) slot
Barrage size button clicked by index.
Definition at line 31 of file musicvideobarragestylepopwidget.cpp.
References m_barrageSize, m_sizeGroup, MusicUIObject::MQSSVideoBtnBig, MusicUIObject::MQSSVideoBtnBigOn, MusicUIObject::MQSSVideoBtnMiddle, MusicUIObject::MQSSVideoBtnMiddleOn, MusicUIObject::MQSSVideoBtnSmall, and MusicUIObject::MQSSVideoBtnSmallOn.
Referenced by initialize().
void MusicVideoBarrageStylePopWidget::initialize () protected
Create all widget in layout.
Definition at line 127 of file musicvideobarragestylepopwidget.cpp.
References barrageColorButtonClicked(), barrageSizeButtonClicked(), m_colorGroup, MusicToolMenuWidget::m_containWidget, m_sizeGroup, MusicUIObject::MQSSVideoBtnBig, MusicUIObject::MQSSVideoBtnBlue, MusicUIObject::MQSSVideoBtnGreen, MusicUIObject::MQSSVideoBtnMiddle, MusicUIObject::MQSSVideoBtnOrange, MusicUIObject::MQSSVideoBtnPurple, MusicUIObject::MQSSVideoBtnRed, MusicUIObject::MQSSVideoBtnSmallOn, MusicUIObject::MQSSVideoBtnWhiteOn, MusicUIObject::MQSSVideoBtnYellow, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicVideoBarrageStylePopWidget().
Member Data Documentation
QColor MusicVideoBarrageStylePopWidget::m_barrageColor protected
Definition at line 64 of file musicvideobarragestylepopwidget.h.
Referenced by barrageColor(), barrageColorButtonClicked(), and MusicVideoBarrageStylePopWidget().
int MusicVideoBarrageStylePopWidget::m_barrageSize protected
Definition at line 63 of file musicvideobarragestylepopwidget.h.
Referenced by barrageSize(), barrageSizeButtonClicked(), and MusicVideoBarrageStylePopWidget().
QButtonGroup* MusicVideoBarrageStylePopWidget::m_colorGroup protected
Definition at line 66 of file musicvideobarragestylepopwidget.h.
Referenced by barrageColorButtonClicked(), initialize(), and ~MusicVideoBarrageStylePopWidget().
QButtonGroup* MusicVideoBarrageStylePopWidget::m_sizeGroup protected
Definition at line 65 of file musicvideobarragestylepopwidget.h.
Referenced by barrageSizeButtonClicked(), initialize(), and ~MusicVideoBarrageStylePopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicVideoKits/musicvideobarragestylepopwidget.h
TTKModule/TTKWidget/musicVideoKits/musicvideobarragestylepopwidget.cpp