TTKMusicplayer: MusicAbstractMoveResizeWidget Class Reference
MusicAbstractMoveResizeWidget Class Reference
The class of the moving resize widget base.
#include <musicabstractmoveresizewidget.h>
Public Types
enum Direction {
Direction_No = 0, Direction_Left = 1, Direction_Top = 2, Direction_Right = 4,
Direction_Bottom = 8, Direction_LeftTop = Direction_Left + Direction_Top, Direction_LeftBottom = Direction_Left + Direction_Bottom, Direction_RightTop = Direction_Right + Direction_Top,
Direction_RightBottom = Direction_Right + Direction_Bottom
}
Public Member Functions
MusicAbstractMoveResizeWidget (QWidget *parent=nullptr)
Protected Member Functions
virtual bool eventFilter (QObject *object, QEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void sizeDirection ()
void moveDirection ()
Protected Attributes
MoveResizeData m_struct
Direction m_direction
Detailed Description
The class of the moving resize widget base.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com Lverson what9.nosp@m.5100.nosp@m.6@163.nosp@m..com
Definition at line 41 of file musicabstractmoveresizewidget.h.
Member Enumeration Documentation
enum MusicAbstractMoveResizeWidget::Direction
Enumerator
Direction_No
no direction
Direction_Left
left direction
Direction_Top
top direction
Direction_Right
right direction
Direction_Bottom
bottom direction
Direction_LeftTop
left top direction
Direction_LeftBottom
left bottom direction
Direction_RightTop
right top direction
Direction_RightBottom
right bottom direction
Definition at line 46 of file musicabstractmoveresizewidget.h.
Constructor & Destructor Documentation
MusicAbstractMoveResizeWidget::MusicAbstractMoveResizeWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicabstractmoveresizewidget.cpp.
References Direction_No, m_direction, MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, and m_struct.
Member Function Documentation
bool MusicAbstractMoveResizeWidget::eventFilter (QObject * object, QEvent * event) override protected virtual
Override the widget event.
Reimplemented in MusicApplication.
Definition at line 21 of file musicabstractmoveresizewidget.cpp.
References TTKStatic_cast.
Referenced by MusicApplication::eventFilter().
void MusicAbstractMoveResizeWidget::mouseDoubleClickEvent (QMouseEvent * event) override protected virtual
Reimplemented in MusicApplication.
Definition at line 48 of file musicabstractmoveresizewidget.cpp.
Referenced by MusicApplication::mouseDoubleClickEvent().
void MusicAbstractMoveResizeWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 85 of file musicabstractmoveresizewidget.cpp.
References MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, MoveResizeData::m_mousePos, m_struct, MoveResizeData::m_windowPos, moveDirection(), and sizeDirection().
void MusicAbstractMoveResizeWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Reimplemented in MusicApplication.
Definition at line 58 of file musicabstractmoveresizewidget.cpp.
References DISTANCE, MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, MoveResizeData::m_mousePos, MoveResizeData::m_pressedSize, m_struct, and MoveResizeData::m_windowPos.
Referenced by MusicApplication::mousePressEvent().
void MusicAbstractMoveResizeWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Reimplemented in MusicApplication.
Definition at line 100 of file musicabstractmoveresizewidget.cpp.
References Direction_No, m_direction, MoveResizeData::m_isPressBorder, MoveResizeData::m_mouseLeftPress, and m_struct.
Referenced by MusicApplication::mouseReleaseEvent().
void MusicAbstractMoveResizeWidget::moveDirection () protected
Move direction to be.
Definition at line 159 of file musicabstractmoveresizewidget.cpp.
References Direction_Bottom, Direction_Left, Direction_LeftBottom, Direction_LeftTop, Direction_Right, Direction_RightBottom, Direction_RightTop, Direction_Top, m_direction, MoveResizeData::m_pressedSize, m_struct, and MoveResizeData::m_windowPos.
Referenced by mouseMoveEvent().
void MusicAbstractMoveResizeWidget::paintEvent (QPaintEvent * event) override protected virtual
Definition at line 32 of file musicabstractmoveresizewidget.cpp.
References Direction_No, DISTANCE, m_direction, MoveResizeData::m_isPressBorder, and m_struct.
void MusicAbstractMoveResizeWidget::sizeDirection () protected
Size direction detected.
Definition at line 109 of file musicabstractmoveresizewidget.cpp.
References Direction_Bottom, Direction_Left, Direction_LeftBottom, Direction_LeftTop, Direction_No, Direction_Right, Direction_RightBottom, Direction_RightTop, Direction_Top, DISTANCE, and m_direction.
Referenced by mouseMoveEvent().
Member Data Documentation
Direction MusicAbstractMoveResizeWidget::m_direction protected
Definition at line 84 of file musicabstractmoveresizewidget.h.
Referenced by mouseReleaseEvent(), moveDirection(), MusicAbstractMoveResizeWidget(), paintEvent(), and sizeDirection().
MoveResizeData MusicAbstractMoveResizeWidget::m_struct protected
Definition at line 83 of file musicabstractmoveresizewidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveDirection(), MusicAbstractMoveResizeWidget(), and paintEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicabstractmoveresizewidget.h
TTKModule/TTKWidget/musicCoreKits/musicabstractmoveresizewidget.cpp