TTKMusicplayer: MusicMGQueryInterface Class Reference
MusicMGQueryInterface Class Reference
The class to migu query interface.
#include <musicmgqueryinterface.h>
Public Member Functions
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const bool status, int bitrate, const QString &suffix)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &key, const QString &quality, bool all)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void setTimeLength (MusicObject::MusicSongInformation *info)
Detailed Description
The class to migu query interface.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 67 of file musicmgqueryinterface.h.
Member Function Documentation
void MusicMGQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const bool status, int bitrate, const QString & suffix)
Read tags(size) from query results.
Definition at line 10 of file musicmgqueryinterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), MusicObject::MusicSongInformation::m_albumId, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongAttribute::m_format, MusicObject::MusicSongInformation::m_lrcUrl, MusicObject::MusicSongAttribute::m_size, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongAttribute::m_url, MB_1000, MB_128, MB_192, MB_320, MB_750, MusicUtils::Algorithm::mdII(), MG_REFERER_URL, MG_SONG_LRC_URL, MG_SONG_PATH_URL, MG_UA_URL, MusicObject::NetworkError, QJson::Parser::parse(), MusicObject::setSslConfiguration(), and STRING_NULL.
Referenced by MusicMGQueryArtistRequest::downLoadFinished(), MusicMGQueryAlbumRequest::downLoadFinished(), MusicMGQueryRequest::downLoadFinished(), MusicMGQueryPlaylistRequest::getDetailsFinished(), readFromMusicSongAttribute(), readFromMusicSongAttributeNew(), and MusicMGQueryRequest::singleDownLoadFinished().
void MusicMGQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QString & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 105 of file musicmgqueryinterface.cpp.
References ALG_UA_KEY, MusicSemaphoreLoop::exec(), MusicUtils::Algorithm::mdII(), MG_REFERER_URL, MG_SONG_INFO_URL, MG_UA_URL, MusicObject::NetworkError, QJson::Parser::parse(), readFromMusicSongAttribute(), and MusicObject::setSslConfiguration().
void MusicMGQueryInterface::readFromMusicSongAttribute (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 144 of file musicmgqueryinterface.cpp.
References FLC_FILE_PREFIX, MB_1000, MB_128, MB_192, MB_320, MB_750, MP3_FILE_PREFIX, and readFromMusicSongAttribute().
void MusicMGQueryInterface::readFromMusicSongAttributeNew (MusicObject::MusicSongInformation * info, const QVariantMap & key, const QString & quality, bool all)
Read tags(size) from query results.
Definition at line 176 of file musicmgqueryinterface.cpp.
References FLC_FILE_PREFIX, MB_1000, MB_128, MB_192, MB_320, MB_750, MP3_FILE_PREFIX, and readFromMusicSongAttribute().
Referenced by MusicMGQueryToplistRequest::downLoadFinished().
void MusicMGQueryInterface::setTimeLength (MusicObject::MusicSongInformation * info)
Get music time length.
Definition at line 208 of file musicmgqueryinterface.cpp.
References MusicAbstractQueryRequest::getUrlFileSize(), MusicObject::MusicSongAttribute::m_bitrate, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_timeLength, MusicObject::MusicSongAttribute::m_url, MB_1000, MusicTime::msecTime2LabelJustified(), and STRING_NULL.
Referenced by MusicMGQueryArtistRequest::downLoadFinished(), MusicMGQueryToplistRequest::downLoadFinished(), MusicMGQueryAlbumRequest::downLoadFinished(), MusicMGQueryRequest::downLoadFinished(), MusicMGQueryPlaylistRequest::getDetailsFinished(), and MusicMGQueryRequest::singleDownLoadFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/music/mg/musicmgqueryinterface.h
TTKModule/TTKCore/musicNetworkKits/music/mg/musicmgqueryinterface.cpp