TTKMusicplayer: TTKThirdParty/TTKExtras/qrencode/mmask.h File Reference
mmask.h File Reference
Functions
unsigned char * MMask_makeMask (int version, unsigned char *frame, int mask, QRecLevel level)
unsigned char * MMask_mask (int version, unsigned char *frame, QRecLevel level)
Function Documentation
unsigned char* MMask_makeMask (int version, unsigned char * frame, int mask, QRecLevel level)
Definition at line 107 of file mmask.c.
References maskMakers, maskNum, MMask_writeFormatInformation(), and MQRspec_getWidth().
Referenced by QRcode_encodeMaskMQR().
unsigned char* MMask_mask (int version, unsigned char * frame, QRecLevel level)
Definition at line 147 of file mmask.c.
References maskMakers, maskNum, MMask_evaluateSymbol(), MMask_writeFormatInformation(), and MQRspec_getWidth().
Referenced by QRcode_encodeMaskMQR().