TTKMusicPlayer: TTKRun/TTKTools/GenerateFM/toolfm.cpp File Reference
toolfm.cpp File Reference
#include "toolfm.h"
Functions
static void makeRequestRawHeader (QNetworkRequest *request)
Variables
static constexpr const char * QT_BASE_URL = "TDNBRFd3S3lvRnVBNzFCblJSQmRHRFhrdVNnQk9qMlBEbzdjWUpSdS95VT0="
static constexpr const char * QT_CATEGORY_URL = "N2VwdWNwUGxOL0ZWZCtrN3V6ekd4SUZqUXVQZ3p1Y2pyeEpsc01RZzR6blNnK0o5L3Q4NWRPRCswVzkrTURKV1VvdzMvQkJ4VEVrPQ=="
static constexpr const char * QT_CHANNEL_URL = "UHJCNEJXWlZhQVowVE1ndXZnajFKQ2tsb1c1SDdlaEE0a0pDWEM2RGJMaktmWXpNZFR6WTcxbmRNb0ZTRTVwQXo5cE92REJOMlhjPQ=="
static constexpr const char * QT_SONG_URL = "OTB3emRpcnNRVDI3eVBtZ2Nwbk9jZXQyQ2hUZjJ1ZjdFdEJIN1V4WHU1WnUvMjk4MEtNWFYrUXRwUlZkWG96TA=="
Function Documentation
static void makeRequestRawHeader (QNetworkRequest * request) static
Definition at line 8 of file toolfm.cpp.
References TTK::makeContentTypeHeader(), TTK::Algorithm::mdII(), QT_BASE_URL, and TTK::setSslConfiguration().
Referenced by ToolFM::startToListRequest(), and ToolFM::startToRequest().
Variable Documentation
constexpr const char* QT_BASE_URL = "TDNBRFd3S3lvRnVBNzFCblJSQmRHRFhrdVNnQk9qMlBEbzdjWUpSdS95VT0=" static
Definition at line 3 of file toolfm.cpp.
Referenced by makeRequestRawHeader().
constexpr const char* QT_CATEGORY_URL = "N2VwdWNwUGxOL0ZWZCtrN3V6ekd4SUZqUXVQZ3p1Y2pyeEpsc01RZzR6blNnK0o5L3Q4NWRPRCswVzkrTURKV1VvdzMvQkJ4VEVrPQ==" static
Definition at line 4 of file toolfm.cpp.
Referenced by ToolFM::startToRequest().
constexpr const char* QT_CHANNEL_URL = "UHJCNEJXWlZhQVowVE1ndXZnajFKQ2tsb1c1SDdlaEE0a0pDWEM2RGJMaktmWXpNZFR6WTcxbmRNb0ZTRTVwQXo5cE92REJOMlhjPQ==" static
Definition at line 5 of file toolfm.cpp.
Referenced by ToolFM::startToListRequest().
constexpr const char* QT_SONG_URL = "OTB3emRpcnNRVDI3eVBtZ2Nwbk9jZXQyQ2hUZjJ1ZjdFdEJIN1V4WHU1WnUvMjk4MEtNWFYrUXRwUlZkWG96TA==" static
Definition at line 6 of file toolfm.cpp.
Referenced by ToolFM::startToListRequest().