TTKMusicplayer: MusicWebMusicRadioWidget Class Reference
MusicWebMusicRadioWidget Class Reference
The class of the web music radio widget.
#include <musicwebmusicradiowidget.h>
Public Slots
void radioPlay ()
void radioPrevious ()
void radioNext ()
void radioVolume (int num)
void getPlayListFinished ()
void getSongInfoFinished ()
void lrcDownloadStateChanged ()
void picDownloadStateChanged ()
void positionChanged (qint64 position)
void durationChanged (qint64 duration)
void show ()
Public Slots inherited from MusicAbstractMoveWidget
void backgroundChanged ()
Public Member Functions
MusicWebMusicRadioWidget (QWidget *parent=0)
virtual ~MusicWebMusicRadioWidget ()
void setNetworkCookie (QNetworkCookieJar *jar)
void updateRadioList (const QString &category)
Public Member Functions inherited from MusicAbstractMoveWidget
MusicAbstractMoveWidget (QWidget *parent=0)
MusicAbstractMoveWidget (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveWidget ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveWidget
static QString getClassName ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) override
void startToPlay ()
Protected Member Functions inherited from MusicAbstractMoveWidget
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicWebMusicRadioWidget * m_ui
int m_currentPlayListIndex
bool m_isPlaying
QTimer m_autoNextTimer
MusicLrcAnalysis * m_analysis
MusicCoreMPlayer * m_radio
MusicRadioPlayListThread * m_playListThread
MusicRadioSongsThread * m_songsThread
QStringList m_playListIds
Protected Attributes inherited from MusicAbstractMoveWidget
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the web music radio widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicwebmusicradiowidget.h.
Constructor & Destructor Documentation
MusicWebMusicRadioWidget::MusicWebMusicRadioWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 14 of file musicwebmusicradiowidget.cpp.
References m_analysis, m_autoNextTimer, m_currentPlayListIndex, m_isPlaying, m_ui, MusicUIObject::MBackgroundStyle01, MusicUIObject::MSliderStyle01, MT_S2MS, MusicUIObject::MToolButtonStyle04, radioNext(), radioPlay(), radioPrevious(), radioVolume(), and MusicLrcAnalysis::setLineMax().
MusicWebMusicRadioWidget::~MusicWebMusicRadioWidget () virtual
Definition at line 69 of file musicwebmusicradiowidget.cpp.
References m_analysis, m_autoNextTimer, m_playListThread, m_radio, m_songsThread, and m_ui.
Member Function Documentation
void MusicWebMusicRadioWidget::closeEvent (QCloseEvent * event) override protected virtual
Override the widget event.
Definition at line 84 of file musicwebmusicradiowidget.cpp.
References m_radio.
void MusicWebMusicRadioWidget::durationChanged (qint64 duration) slot
Current duration changed.
Definition at line 336 of file musicwebmusicradiowidget.cpp.
References m_radio, m_ui, MusicTime::msecTime2LabelJustified(), and MT_S2MS.
Referenced by startToPlay().
QString MusicWebMusicRadioWidget::getClassName () static
Get class object name.
Definition at line 79 of file musicwebmusicradiowidget.cpp.
void MusicWebMusicRadioWidget::getPlayListFinished () slot
Get playList finished.
Definition at line 185 of file musicwebmusicradiowidget.cpp.
References MusicRadioPlayListThread::getMusicPlayList(), m_currentPlayListIndex, m_playListIds, m_playListThread, m_songsThread, and MusicRadioSongsThread::startToDownload().
Referenced by setNetworkCookie().
void MusicWebMusicRadioWidget::getSongInfoFinished () slot
Get song information finished.
Definition at line 195 of file musicwebmusicradiowidget.cpp.
References m_isPlaying, and startToPlay().
Referenced by setNetworkCookie().
void MusicWebMusicRadioWidget::lrcDownloadStateChanged () slot
Lrc download state changed.
Definition at line 252 of file musicwebmusicradiowidget.cpp.
References MusicRadioSongsThread::getMusicSongInfo(), LRC_FILE, MusicUtils::Core::lrcPrefix(), m_analysis, MusicRadioSongInfo::m_artistName, MusicRadioSongInfo::m_songName, m_songsThread, MusicRadioSongInfo::m_songUrl, m_ui, and MusicLrcAnalysis::transLrcFileToTime().
Referenced by startToPlay().
void MusicWebMusicRadioWidget::picDownloadStateChanged () slot
Small pic download state changed.
Definition at line 271 of file musicwebmusicradiowidget.cpp.
References ART_DIR_FULL, MusicRadioSongsThread::getMusicSongInfo(), MusicRadioSongInfo::m_artistName, m_songsThread, MusicRadioSongInfo::m_songUrl, m_ui, MusicUtils::Widget::pixmapToRound(), and SKN_FILE.
Referenced by startToPlay().
void MusicWebMusicRadioWidget::positionChanged (qint64 position) slot
Current position changed.
Definition at line 294 of file musicwebmusicradiowidget.cpp.
References MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), MusicLrcAnalysis::isEmpty(), m_analysis, m_autoNextTimer, m_radio, m_ui, MusicTime::msecTime2LabelJustified(), MT_S2MS, and MusicLrcAnalysis::setCurrentIndex().
Referenced by startToPlay().
void MusicWebMusicRadioWidget::radioNext () slot
Set radio to next.
Definition at line 152 of file musicwebmusicradiowidget.cpp.
References m_currentPlayListIndex, m_isPlaying, m_playListIds, m_songsThread, m_ui, and MusicRadioSongsThread::startToDownload().
Referenced by MusicWebMusicRadioWidget().
void MusicWebMusicRadioWidget::radioPlay () slot
Set radio to play.
Definition at line 110 of file musicwebmusicradiowidget.cpp.
References m_isPlaying, m_radio, m_ui, startToPlay(), and MusicCoreMPlayer::stop().
Referenced by MusicWebMusicRadioWidget().
void MusicWebMusicRadioWidget::radioPrevious () slot
Set radio to previous.
Definition at line 127 of file musicwebmusicradiowidget.cpp.
References m_currentPlayListIndex, m_isPlaying, m_playListIds, m_songsThread, m_ui, and MusicRadioSongsThread::startToDownload().
Referenced by MusicWebMusicRadioWidget().
void MusicWebMusicRadioWidget::radioVolume (int num) slot
Set radio volume.
Definition at line 177 of file musicwebmusicradiowidget.cpp.
References m_radio, and MusicCoreMPlayer::setVolume().
Referenced by MusicWebMusicRadioWidget().
void MusicWebMusicRadioWidget::setNetworkCookie (QNetworkCookieJar * jar)
Set network cookie.
Definition at line 91 of file musicwebmusicradiowidget.cpp.
References getPlayListFinished(), getSongInfoFinished(), m_playListThread, and m_songsThread.
Referenced by MusicWebMusicRadioListView::itemHasClicked().
void MusicWebMusicRadioWidget::show () slot
Override show function.
Definition at line 345 of file musicwebmusicradiowidget.cpp.
References m_ui, and MusicAbstractMoveWidget::setBackgroundPixmap().
Referenced by MusicWebMusicRadioListView::itemHasClicked().
void MusicWebMusicRadioWidget::startToPlay () protected
Start to play music radio.
fix current play volume temporary
Definition at line 201 of file musicwebmusicradiowidget.cpp.
References ART_DIR_FULL, MusicDownLoadThreadAbstract::Download_Lrc, MusicDownLoadThreadAbstract::Download_SmlBG, durationChanged(), MusicRadioSongsThread::getMusicSongInfo(), LRC_FILE, lrcDownloadStateChanged(), MusicUtils::Core::lrcPrefix(), MusicRadioSongInfo::m_artistName, MusicRadioSongInfo::m_lrcUrl, m_radio, MusicRadioSongInfo::m_songName, MusicRadioSongInfo::m_songPicUrl, m_songsThread, MusicRadioSongInfo::m_songUrl, m_ui, MusicCoreMPlayer::MusicCategory, picDownloadStateChanged(), positionChanged(), MusicCoreMPlayer::setMedia(), SKN_FILE, MusicDataDownloadThread::startToDownload(), and MusicTextDownLoadThread::startToDownload().
Referenced by getSongInfoFinished(), and radioPlay().
void MusicWebMusicRadioWidget::updateRadioList (const QString & category)
Update radio list by given category.
Definition at line 102 of file musicwebmusicradiowidget.cpp.
References m_playListThread, and MusicRadioPlayListThread::startToDownload().
Referenced by MusicWebMusicRadioListView::itemHasClicked().
Member Data Documentation
MusicLrcAnalysis* MusicWebMusicRadioWidget::m_analysis protected
Definition at line 123 of file musicwebmusicradiowidget.h.
Referenced by lrcDownloadStateChanged(), MusicWebMusicRadioWidget(), positionChanged(), and ~MusicWebMusicRadioWidget().
QTimer MusicWebMusicRadioWidget::m_autoNextTimer protected
Definition at line 122 of file musicwebmusicradiowidget.h.
Referenced by MusicWebMusicRadioWidget(), positionChanged(), and ~MusicWebMusicRadioWidget().
int MusicWebMusicRadioWidget::m_currentPlayListIndex protected
Definition at line 120 of file musicwebmusicradiowidget.h.
Referenced by getPlayListFinished(), MusicWebMusicRadioWidget(), radioNext(), and radioPrevious().
bool MusicWebMusicRadioWidget::m_isPlaying protected
Definition at line 121 of file musicwebmusicradiowidget.h.
Referenced by getSongInfoFinished(), MusicWebMusicRadioWidget(), radioNext(), radioPlay(), and radioPrevious().
QStringList MusicWebMusicRadioWidget::m_playListIds protected
Definition at line 127 of file musicwebmusicradiowidget.h.
Referenced by getPlayListFinished(), radioNext(), and radioPrevious().
MusicRadioPlayListThread* MusicWebMusicRadioWidget::m_playListThread protected
Definition at line 125 of file musicwebmusicradiowidget.h.
Referenced by getPlayListFinished(), setNetworkCookie(), updateRadioList(), and ~MusicWebMusicRadioWidget().
MusicCoreMPlayer* MusicWebMusicRadioWidget::m_radio protected
Definition at line 124 of file musicwebmusicradiowidget.h.
Referenced by closeEvent(), durationChanged(), positionChanged(), radioPlay(), radioVolume(), startToPlay(), and ~MusicWebMusicRadioWidget().
MusicRadioSongsThread* MusicWebMusicRadioWidget::m_songsThread protected
Definition at line 126 of file musicwebmusicradiowidget.h.
Referenced by getPlayListFinished(), lrcDownloadStateChanged(), picDownloadStateChanged(), radioNext(), radioPrevious(), setNetworkCookie(), startToPlay(), and ~MusicWebMusicRadioWidget().
Ui::MusicWebMusicRadioWidget* MusicWebMusicRadioWidget::m_ui protected
Definition at line 119 of file musicwebmusicradiowidget.h.
Referenced by durationChanged(), lrcDownloadStateChanged(), MusicWebMusicRadioWidget(), picDownloadStateChanged(), positionChanged(), radioNext(), radioPlay(), radioPrevious(), show(), startToPlay(), and ~MusicWebMusicRadioWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musicwebmusicradiowidget.h
TTKModule/TTKWidget/musicToolsKits/musicwebmusicradiowidget.cpp