TTKMusicplayer: MusicArtistAlbumsItemWidget Class Reference
MusicArtistAlbumsItemWidget Class Reference
The class of the artist albums item widget.
#include <musicartistquerywidget.h>
Public Slots
void downLoadFinished (const QByteArray &bytes)
void renderFinished (const QPixmap &data)
void currentItemClicked ()
Signals
void currentItemClicked (const QString &id)
Public Member Functions
MusicArtistAlbumsItemWidget (QWidget *parent=nullptr)
~MusicArtistAlbumsItemWidget ()
void setMusicResultsItem (const MusicResultsItem &item)
Protected Attributes
MusicResultsItem m_itemData
QPushButton * m_playButton
QLabel * m_iconLabel
QLabel * m_nameLabel
QLabel * m_updateLabel
Detailed Description
The class of the artist albums item widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicartistquerywidget.h.
Constructor & Destructor Documentation
MusicArtistAlbumsItemWidget::MusicArtistAlbumsItemWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 19 of file musicartistquerywidget.cpp.
References currentItemClicked(), HEIGHT_LABEL_SIZE, m_iconLabel, m_nameLabel, m_playButton, m_updateLabel, MusicUIObject::MQSSPushButtonStyle01, MusicUIObject::MQSSTinyBtnPlaylist, and WIDTH_LABEL_SIZE.
MusicArtistAlbumsItemWidget::~MusicArtistAlbumsItemWidget ()
Definition at line 46 of file musicartistquerywidget.cpp.
References m_iconLabel, m_nameLabel, m_playButton, and m_updateLabel.
Member Function Documentation
void MusicArtistAlbumsItemWidget::currentItemClicked (const QString & id) signal
Current item clicked.
void MusicArtistAlbumsItemWidget::currentItemClicked () slot
Current item clicked.
Definition at line 90 of file musicartistquerywidget.cpp.
References MusicResultsItem::m_id, and m_itemData.
Referenced by MusicArtistAlbumsItemWidget().
void MusicArtistAlbumsItemWidget::downLoadFinished (const QByteArray & bytes) slot
Send recieved data from net.
Definition at line 70 of file musicartistquerywidget.cpp.
References m_iconLabel, renderFinished(), MusicImageRenderer::setInputData(), MusicAbstractThread::start(), and TTK_LOGGER_ERROR.
Referenced by setMusicResultsItem().
void MusicArtistAlbumsItemWidget::renderFinished (const QPixmap & data) slot
Image render finished.
Definition at line 84 of file musicartistquerywidget.cpp.
References m_iconLabel, and m_playButton.
Referenced by downLoadFinished().
void MusicArtistAlbumsItemWidget::setMusicResultsItem (const MusicResultsItem & item)
Set music results item.
Definition at line 54 of file musicartistquerywidget.cpp.
References downLoadFinished(), MusicUtils::Widget::elidedText(), MusicResultsItem::m_coverUrl, m_itemData, MusicResultsItem::m_name, m_nameLabel, m_updateLabel, MusicResultsItem::m_updateTime, MusicDownloadSourceRequest::startToDownload(), TTK_NULL_STR, and WIDTH_LABEL_SIZE.
Referenced by MusicArtistAlbumsQueryWidget::createArtistAlbumsItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), and MusicArtistSimilarQueryWidget::createArtistSimilarItem().
Member Data Documentation
QLabel* MusicArtistAlbumsItemWidget::m_iconLabel protected
Definition at line 66 of file musicartistquerywidget.h.
Referenced by downLoadFinished(), MusicArtistAlbumsItemWidget(), renderFinished(), and ~MusicArtistAlbumsItemWidget().
MusicResultsItem MusicArtistAlbumsItemWidget::m_itemData protected
Definition at line 64 of file musicartistquerywidget.h.
Referenced by currentItemClicked(), and setMusicResultsItem().
QLabel * MusicArtistAlbumsItemWidget::m_nameLabel protected
Definition at line 66 of file musicartistquerywidget.h.
Referenced by MusicArtistAlbumsItemWidget(), setMusicResultsItem(), and ~MusicArtistAlbumsItemWidget().
QPushButton* MusicArtistAlbumsItemWidget::m_playButton protected
Definition at line 65 of file musicartistquerywidget.h.
Referenced by MusicArtistAlbumsItemWidget(), renderFinished(), and ~MusicArtistAlbumsItemWidget().
QLabel * MusicArtistAlbumsItemWidget::m_updateLabel protected
Definition at line 66 of file musicartistquerywidget.h.
Referenced by MusicArtistAlbumsItemWidget(), setMusicResultsItem(), and ~MusicArtistAlbumsItemWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicartistquerywidget.cpp