TTKMusicPlayer: MusicLrcFromKrc Class Reference
MusicLrcFromKrc Class Reference
The class of the krc to lrc.
#include <musiclrcparser.h>
Public Member Functions
MusicLrcFromKrc ()
~MusicLrcFromKrc ()
virtual bool decode (const QString &input) overridefinal
bool decode (const QString &input, const QString &output)
Public Member Functions inherited from MusicLrcFromInterface
virtual ~MusicLrcFromInterface ()=default
const QByteArray & data () const noexcept
Protected Member Functions
int sncasecmp (const char *s1, const char *s2, size_t n)
int decompression (uchar *src, size_t srcsize, size_t *dstsize)
int isfilter (const char *tok)
void createLrc (uchar *lrc, int lrclen)
Protected Attributes
uchar * m_resultBytes
Protected Attributes inherited from MusicLrcFromInterface
QByteArray m_data
Detailed Description
The class of the krc to lrc.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 67 of file musiclrcparser.h.
Constructor & Destructor Documentation
MusicLrcFromKrc::MusicLrcFromKrc ()
Object constructor.
Definition at line 38 of file musiclrcparser.cpp.
MusicLrcFromKrc::~MusicLrcFromKrc ()
Object destructor.
Definition at line 45 of file musiclrcparser.cpp.
References m_resultBytes.
Member Function Documentation
void MusicLrcFromKrc::createLrc (uchar * lrc, int lrclen) protected
Create lrc by input data and length.
Definition at line 192 of file musiclrcparser.cpp.
References isfilter(), MusicLrcFromInterface::m_data, TTK_DN_H2MS, TTK_DN_M2MS, and TTK_DN_S2MS.
Referenced by decode().
bool MusicLrcFromKrc::decode (const QString & input) final override virtual
Decode file to lrc by input file.
Implements MusicLrcFromInterface.
Definition at line 50 of file musiclrcparser.cpp.
Referenced by MusicLrcAnalysis::loadFromFile(), and MusicTransformWidget::processTransform().
bool MusicLrcFromKrc::decode (const QString & input, const QString & output)
Decode krc file to lrc by input file and output file.
Definition at line 55 of file musiclrcparser.cpp.
References createLrc(), decompression(), key, MusicLrcFromInterface::m_data, m_resultBytes, qPrintable, QtNamespace, TTK_ERROR_STREAM, and TTKStaticCast.
int MusicLrcFromKrc::decompression (uchar * src, size_t srcsize, size_t * dstsize) protected
Decompress the krc file data to normal data.
Definition at line 149 of file musiclrcparser.cpp.
References m_resultBytes, TTK_SN_MB2BT, uncompress(), and Z_OK.
Referenced by decode().
int MusicLrcFromKrc::isfilter (const char * tok) protected
Check the input string is filtered or not.
Definition at line 159 of file musiclrcparser.cpp.
References sncasecmp().
Referenced by createLrc().
int MusicLrcFromKrc::sncasecmp (const char * s1, const char * s2, size_t n) protected
Sncasecmp by input and size n.
Definition at line 124 of file musiclrcparser.cpp.
Referenced by isfilter().
Member Data Documentation
uchar* MusicLrcFromKrc::m_resultBytes protected
Definition at line 106 of file musiclrcparser.h.
Referenced by decode(), decompression(), and ~MusicLrcFromKrc().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicLrcKits/musiclrcparser.h
TTKModule/TTKCore/musicLrcKits/musiclrcparser.cpp