TTKMusicplayer: MusicWYAuthenticationThread Class Reference
MusicWYAuthenticationThread Class Reference
The class to wangyi login authentication.
#include <musicwyauthenticationthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYAuthenticationThread (QObject *parent=0)
QJson import.
virtual void startToDownload (const QString &usr, const QString &pwd) override
Public Member Functions inherited from MusicAuthenticationThread
MusicAuthenticationThread (QObject *parent=0)
virtual ~MusicAuthenticationThread ()
virtual void deleteAll () override
const MusicUserInfoRecord & getInfoRecord () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAuthenticationThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicAuthenticationThread
MusicUserInfoRecord m_info
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Detailed Description
The class to wangyi login authentication.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicwyauthenticationthread.h.
Constructor & Destructor Documentation
MusicWYAuthenticationThread::MusicWYAuthenticationThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 9 of file musicwyauthenticationthread.cpp.
Member Function Documentation
void MusicWYAuthenticationThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 37 of file musicwyauthenticationthread.cpp.
References MusicUserInfoRecord::clear(), MusicAuthenticationThread::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), getClassName(), MusicUserInfoRecord::m_coverUrl, MusicAuthenticationThread::m_info, MusicNetworkAbstract::m_interrupt, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicUserInfoRecord::m_nickName, MusicNetworkAbstract::m_reply, M_SETTING_PTR, MusicSettingManager::NetworkCookieChoiced, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicWYAuthenticationThread::getClassName () static
Get class object name.
Definition at line 15 of file musicwyauthenticationthread.cpp.
Referenced by downLoadFinished().
void MusicWYAuthenticationThread::startToDownload (const QString & usr, const QString & pwd) override virtual
Start to translation data.
Implements MusicAuthenticationThread.
Definition at line 20 of file musicwyauthenticationthread.cpp.
References downLoadFinished(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), MusicNetworkAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), WY_AUT_N_URL, and WY_AUT_NDT_URL.
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicwyauthenticationthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicwyauthenticationthread.cpp