TTKMusicplayer: MusicDownloadBackgroundThread Class Reference
MusicDownloadBackgroundThread Class Reference abstract
The class of download art background image.
#include <musicdownloadbackgroundthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDownloadBackgroundThread (const QString &name, const QString &save, QObject *parent=nullptr)
virtual void startToDownload ()=0
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=nullptr)
virtual ~MusicNetworkAbstract ()
virtual void deleteAll ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
void setHeader (const QString &key, const QVariant &value)
const QVariant getHeader (const QString &key) const
Protected Attributes
int m_index
int m_counter
QString m_artName
QString m_savePath
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
QVariantMap m_headerData
MusicObject::NetworkCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Additional Inherited Members
Signals inherited from MusicNetworkAbstract
void downLoadRawDataChanged (const QByteArray &data)
void downLoadDataChanged (const QString &data)
Detailed Description
The class of download art background image.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadbackgroundthread.h.
Constructor & Destructor Documentation
MusicDownloadBackgroundThread::MusicDownloadBackgroundThread (const QString & name, const QString & save, QObject * parent = nullptr)
Object contsructor provide artist name and save local path.
Definition at line 7 of file musicdownloadbackgroundthread.cpp.
Member Function Documentation
void MusicDownloadBackgroundThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 13 of file musicdownloadbackgroundthread.cpp.
References BACKGROUND_DIR_FULL, MusicTopAreaWidget::instance(), m_artName, M_BACKGROUND_PTR, m_counter, m_index, m_savePath, MusicTopAreaWidget::musicBackgroundThemeDownloadFinished(), and SKN_FILE.
Referenced by MusicKWBackgroundThread::downLoadFinished(), MusicQQBackgroundThread::downLoadUrlFinished(), and MusicKWBackgroundThread::startToDownload().
virtual void MusicDownloadBackgroundThread::startToDownload () pure virtual
Start to download artist picture from net. Subclass should implement this function.
Implemented in MusicQQBackgroundThread, and MusicKWBackgroundThread.
Member Data Documentation
QString MusicDownloadBackgroundThread::m_artName protected
Definition at line 52 of file musicdownloadbackgroundthread.h.
Referenced by downLoadFinished(), MusicKWBackgroundThread::startToDownload(), and MusicQQBackgroundThread::startToDownload().
int MusicDownloadBackgroundThread::m_counter protected
Definition at line 51 of file musicdownloadbackgroundthread.h.
Referenced by MusicKWBackgroundThread::downLoadFinished(), downLoadFinished(), and MusicQQBackgroundThread::downLoadUrlFinished().
int MusicDownloadBackgroundThread::m_index protected
Definition at line 51 of file musicdownloadbackgroundthread.h.
Referenced by downLoadFinished().
QString MusicDownloadBackgroundThread::m_savePath protected
Definition at line 52 of file musicdownloadbackgroundthread.h.
Referenced by MusicKWBackgroundThread::downLoadFinished(), downLoadFinished(), and MusicQQBackgroundThread::downLoadUrlFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadbackgroundthread.h
TTKModule/TTKCore/musicNetworkKits/ztl/musicdownloadbackgroundthread.cpp