TTKMusicplayer: MusicWYTextDownLoadThread Class Reference
MusicWYTextDownLoadThread Class Reference
The class of downloading the type of wangyi txt.
#include <musicwytextdownloadthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicDownLoadThreadAbstract
virtual void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
virtual void replyError (QNetworkReply::NetworkError error) override
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors) override
virtual void updateDownloadSpeed ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicWYTextDownLoadThread (const QString &url, const QString &save, MusicNetwork::DownloadType type, QObject *parent=0)
QJson import.
virtual void startToDownload () override
Public Member Functions inherited from MusicDownLoadThreadAbstract
MusicDownLoadThreadAbstract (const QString &url, const QString &save, MusicNetwork::DownloadType type, QObject *parent=0)
virtual ~MusicDownLoadThreadAbstract ()
virtual void deleteAll () override
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
const QVariantMap & getRawData () const
Additional Inherited Members
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicDownLoadThreadAbstract
QString transferData () const
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Attributes inherited from MusicDownLoadThreadAbstract
QFile * m_file
QString m_url
QString m_savePathName
MusicNetwork::DownloadType m_downloadType
qint64 m_hasReceived
qint64 m_currentReceived
qint64 m_totalSize
QTimer m_timer
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
MusicNetwork::StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of downloading the type of wangyi txt.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicwytextdownloadthread.h.
Constructor & Destructor Documentation
MusicWYTextDownLoadThread::MusicWYTextDownLoadThread (const QString & url, const QString & save, MusicNetwork::DownloadType type, QObject * parent = 0)
QJson import.
Object contsructor provide download URL\ save local path and download type.
Definition at line 5 of file musicwytextdownloadthread.cpp.
Member Function Documentation
void MusicWYTextDownLoadThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 43 of file musicwytextdownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_ERROR, M_LOGGER_INFO, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_timer, QJson::Parser::parse(), and MusicDownLoadThreadAbstract::transferData().
Referenced by startToDownload().
void MusicWYTextDownLoadThread::startToDownload () override virtual
Start to download data.
Implements MusicDownLoadThreadAbstract.
Definition at line 12 of file musicwytextdownloadthread.cpp.
References MusicDownLoadThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), downLoadFinished(), MusicDownLoadThreadAbstract::downloadProgress(), MusicDownLoadThreadAbstract::m_file, M_LOGGER_ERROR, M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicDownLoadThreadAbstract::m_timer, MusicDownLoadThreadAbstract::m_url, MT_S2MS, MusicDownLoadThreadAbstract::replyError(), MusicNetworkAbstract::setSslConfiguration(), and MusicDownLoadThreadAbstract::sslErrors().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/wy/musicwytextdownloadthread.h
TTKModule/TTKCore/musicNetworkKits/wy/musicwytextdownloadthread.cpp