TTKMusicPlayer: QSyncDownloadData Class Reference
QSyncDownloadData Class Reference
The class of the sync cloud download data.
#include <qsyncdownloaddata.h>
Signals
void downloadFileFinished (const QString &time)
void downloadProgressChanged (const QString &time, qint64 bytesSent, qint64 bytesTotal)
Public Member Functions
QSyncDownloadData (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
void downloadDataOperator (const QString &time, const QString &bucket, const QString &fileName, const QString &filePath)
QString downloadUrl (const QString &bucket, const QString &fileName)
QString downloadUrl (const QString &bucket, const QString &fileName, const QString &contentType)
Public Member Functions inherited from QSyncDataInterface
QSyncDataInterface (QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Private Slots
virtual void receiveDataFromServer () overridefinal
void downloadProgress (qint64 bytesSent, qint64 bytesTotal)
Additional Inherited Members
Protected Slots inherited from QSyncDataInterface
virtual void receiveDataFromServer ()=0
void replyError (QNetworkReply::NetworkError error)
Protected Member Functions inherited from QSyncDataInterface
QString pathEncode (const QString &data) const
QString pathDecode (const QString &data) const
QSyncDataInterface (QSyncDataInterfacePrivate &pvt, QNetworkAccessManager *networkManager, QObject *parent=nullptr)
Detailed Description
The class of the sync cloud download data.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qsyncdownloaddata.h.
Constructor & Destructor Documentation
QSyncDownloadData::QSyncDownloadData (QNetworkAccessManager * networkManager, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 24 of file qsyncdownloaddata.cpp.
References TTK_D.
Member Function Documentation
void QSyncDownloadData::downloadDataOperator (const QString & time, const QString & bucket, const QString & fileName, const QString & filePath)
Get download data operator.
Definition at line 31 of file qsyncdownloaddata.cpp.
References downloadProgress(), downloadProgressChanged(), QSyncUtils::GMT(), QSyncConfig::HOST, QtNetworkErrorConnect, receiveDataFromServer(), QSyncDataInterface::replyError(), TTK_D, TTK_DOT, and TTK_SEPARATOR.
void QSyncDownloadData::downloadFileFinished (const QString & time) signal
download file finshed.
Referenced by receiveDataFromServer().
void QSyncDownloadData::downloadProgress (qint64 bytesSent, qint64 bytesTotal) private slot
Show download progress.
Definition at line 119 of file qsyncdownloaddata.cpp.
References downloadProgressChanged(), and TTK_D.
Referenced by downloadDataOperator().
void QSyncDownloadData::downloadProgressChanged (const QString & time, qint64 bytesSent, qint64 bytesTotal) signal
Show download progress.
Referenced by downloadDataOperator(), and downloadProgress().
QString QSyncDownloadData::downloadUrl (const QString & bucket, const QString & fileName)
Get download url request.
Definition at line 68 of file qsyncdownloaddata.cpp.
Referenced by MusicCloudManagerTableWidget::downloadFileToServer().
QString QSyncDownloadData::downloadUrl (const QString & bucket, const QString & fileName, const QString & contentType)
Get download url request by content type.
Definition at line 73 of file qsyncdownloaddata.cpp.
References QSyncUtils::authorizationCode(), QSyncConfig::HOST, QSyncConfig::KEY, QSyncConfig::NAME, QSyncDataInterface::pathEncode(), TTK_DOT, and TTK_SEPARATOR.
void QSyncDownloadData::receiveDataFromServer () final override private virtual slot
Receive data from server finshed.
Definition at line 91 of file qsyncdownloaddata.cpp.
References downloadFileFinished(), TTK_D, TTK_NAN_STR, and TTKObject_cast.
Referenced by downloadDataOperator().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncdownloaddata.h
TTKThirdParty/TTKExtras/qsync/qsyncdownloaddata.cpp