TTKMusicplayer: MusicLocalSongsInfoTableWidget Class Reference
MusicLocalSongsInfoTableWidget Class Reference
The class of the lcal songs info table widget.
#include <musiclocalsongstablewidget.h>
Public Slots
virtual void listCellClicked (int row, int column) override
void listCellDoubleClicked (int row, int column)
Public Slots inherited from MusicAbstractTableWidget
virtual void listCellEntered (int row, int column)
virtual void listCellClicked (int row, int column)=0
Signals
void updateFileLists (const QFileInfoList &list)
Public Member Functions
MusicLocalSongsInfoTableWidget (QWidget *parent=0)
void clear ()
void addItems (const MusicInfoData &data)
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=0)
virtual ~MusicAbstractTableWidget ()
void clear ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractTableWidget
static QString getClassName ()
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicAbstractTableWidget
QColor m_defaultBkColor
int m_previousColorRow
int m_previousClickRow
Detailed Description
The class of the lcal songs info table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 70 of file musiclocalsongstablewidget.h.
Constructor & Destructor Documentation
MusicLocalSongsInfoTableWidget::MusicLocalSongsInfoTableWidget (QWidget * parent = 0) explicit
Definition at line 104 of file musiclocalsongstablewidget.cpp.
References listCellDoubleClicked(), and MusicUtils::Widget::setTransparent().
Member Function Documentation
void MusicLocalSongsInfoTableWidget::addItems (const MusicInfoData & data)
Clear current items.
Definition at line 131 of file musiclocalsongstablewidget.cpp.
References ART_DIR_FULL, MusicUtils::Widget::elidedText(), MUSIC_INFO_ROLE, ROW_HEIGHT, and SKN_FILE.
void MusicLocalSongsInfoTableWidget::clear ()
Get class object name.
Definition at line 126 of file musiclocalsongstablewidget.cpp.
References MusicAbstractTableWidget::clear().
QString MusicLocalSongsInfoTableWidget::getClassName () static
Object contsructor.
Definition at line 121 of file musiclocalsongstablewidget.cpp.
void MusicLocalSongsInfoTableWidget::listCellClicked (int row, int column) override virtual slot
Update file lists.
Definition at line 168 of file musiclocalsongstablewidget.cpp.
void MusicLocalSongsInfoTableWidget::listCellDoubleClicked (int row, int column) slot
Table widget list cell click.
Definition at line 174 of file musiclocalsongstablewidget.cpp.
References MUSIC_INFO_ROLE, and updateFileLists().
Referenced by MusicLocalSongsInfoTableWidget().
void MusicLocalSongsInfoTableWidget::updateFileLists (const QFileInfoList & list) signal
Add show list item.
Referenced by listCellDoubleClicked().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musiclocalsongstablewidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musiclocalsongstablewidget.cpp