TTKMusicPlayer: MusicSearchEdit Class Reference
MusicSearchEdit Class Reference
The class of the search line edit widget.
#include <musicsearchedit.h>
Signals
void enterFinished (const QString &text)
Public Member Functions
MusicSearchEdit (QWidget *parent=nullptr)
Private Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) overridefinal
virtual void keyPressEvent (QKeyEvent *event) overridefinal
virtual void keyReleaseEvent (QKeyEvent *event) overridefinal
Detailed Description
The class of the search line edit widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicsearchedit.h.
Constructor & Destructor Documentation
MusicSearchEdit::MusicSearchEdit (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 6 of file musicsearchedit.cpp.
References TTK::UI::LineEditStyle02.
Member Function Documentation
void MusicSearchEdit::contextMenuEvent (QContextMenuEvent * event) final override private virtual
Override the widget event.
Definition at line 13 of file musicsearchedit.cpp.
References TTK::Widget::adjustMenuPosition(), and TTK::UI::MenuStyle02.
void MusicSearchEdit::enterFinished (const QString & text) signal
User input the enter key.
Referenced by keyReleaseEvent().
void MusicSearchEdit::keyPressEvent (QKeyEvent * event) final override private virtual
Definition at line 37 of file musicsearchedit.cpp.
void MusicSearchEdit::keyReleaseEvent (QKeyEvent * event) final override private virtual
Definition at line 42 of file musicsearchedit.cpp.
References enterFinished().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musicsearchedit.h
TTKModule/TTKWidget/musicSearchKits/musicsearchedit.cpp