TTKMusicPlayer: MusicSettingWidget Class Reference
MusicSettingWidget Class Reference
The class of the setting parameters widget.
#include <musicsettingwidget.h>
Public Types
enum Lrc { Interior, Desktop }
enum Proxy { Proxy::Test, Proxy::Apply }
enum SettingType {
Normal, Hotkey, Download, Spectrum,
Other, Desktop, Desktop, Interior,
Interior, SoundEffect, Audio, Network
}
Public Slots
void close ()
void changeDesktopLrcWidget ()
void changeInteriorLrcWidget ()
void changeDownloadWidget ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
virtual int exec ()
void show ()
Signals
void parameterSettingChanged ()
Public Member Functions
MusicSettingWidget (QWidget *parent=nullptr)
~MusicSettingWidget ()
void initialize ()
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
~MusicAbstractMoveDialog ()
Public Member Functions inherited from TTKAbstractMoveDialog
TTKAbstractMoveDialog (QWidget *parent=nullptr)
TTKAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
void setShadowOption (bool show) noexcept
void setBlockOption (bool block) noexcept
Private Slots
void clearFunctionTableSelection ()
void fileAssociationChanged ()
void globalHotkeyBoxChanged (bool state)
void downloadCacheClean ()
void downloadFileNameRuleChanged (QAction *action)
void serverPluginChanged ()
void downloadGroupCached (int index)
void downloadGroupSpeedLimit (int index)
void downloadDirChanged (int index)
void rippleVersionUpdateChanged ()
void rippleSpectrumColorChanged ()
void rippleSpectrumTransChanged (int value)
void rippleSpectrumEnableClicked (bool state)
void rippleLowPowerEnableBoxClicked (bool state)
void otherPluginManagerChanged ()
void interiorLrcFrontgroundChanged ()
void interiorLrcBackgroundChanged ()
void defaultLrcColorChanged (int value)
void interiorLrcTransChanged (int value)
void showInteriorLrcDemo ()
void resetInteriorParameter ()
void desktopFrontgroundChanged ()
void desktopBackgroundChanged ()
void defaultDesktopLrcColorChanged (int value)
void desktopLrcTransChanged (int value)
void showDesktopLrcDemo ()
void resetDesktopParameter ()
void setNetworkProxyControl (int enable)
void testNetworkProxy ()
void testProxyStateChanged (bool state)
void testNetworkConnection ()
void checkNetworkConnection ()
void testNetworkConnectionStateChanged (const QString &name)
void fadeInAndOutClicked (bool state)
void saveParameterSettings ()
void setScrollWidgetPageIndex (int index)
void scrollWidgetValueChanged (int value)
Private Member Functions
void initScrollWidgetPage ()
void initNormalSettingWidget ()
void initDownloadWidget ()
void initSpectrumSettingWidget ()
void initOtherSettingWidget ()
void initDesktopLrcWidget ()
void initInteriorLrcWidget ()
void initSoundEffectWidget ()
void initAudioSettingWidget ()
void initNetworkWidget ()
void selectFunctionTableIndex (int row, int column)
void lcrColorValue (Lrc key, const QString &type, QLabel *obj)
void lrcColorByDefault (Lrc key, int index)
void lrcTransparentValue (Lrc key, int value) const
bool setNetworkProxyByType (Proxy type)
Private Attributes
Ui::MusicSettingWidget * m_ui
QVector< MusicGlobalHotKeyEdit * > m_hotKeyEdits
Additional Inherited Members
Protected Member Functions inherited from TTKAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
Protected Member Functions inherited from MusicWidgetRenderer
void setBackgroundPixmap (const QSize &size)
MusicWidgetRenderer ()
void setBackgroundLabel (QLabel *label) noexcept
Protected Attributes inherited from TTKAbstractMoveDialog
bool m_mouseLeftPressed
bool m_blockOption
bool m_shadowOption
QPoint m_windowPos
QPoint m_pressedPos
Detailed Description
The class of the setting parameters widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 88 of file musicsettingwidget.h.
Member Enumeration Documentation
enum MusicSettingWidget::Lrc strong
Enumerator
Interior
lrc interior type
Desktop
lrc desktop type
Definition at line 92 of file musicsettingwidget.h.
enum MusicSettingWidget::Proxy strong
Enumerator
Test
proxy test type
Apply
proxy apply type
Definition at line 98 of file musicsettingwidget.h.
enum MusicSettingWidget::SettingType
Enumerator
Normal
Normal setting type
Hotkey
Hotkey setting type
Download
Download setting type
Spectrum
Spectrum setting type
Other
Other setting type
Desktop
Desktop setting type
Desktop
lrc desktop type
Interior
Interior setting type
Interior
lrc interior type
SoundEffect
SoundEffect setting type
Audio
Audio setting type
Network
Network setting type
Definition at line 104 of file musicsettingwidget.h.
Constructor & Destructor Documentation
MusicSettingWidget::MusicSettingWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 82 of file musicsettingwidget.cpp.
References clearFunctionTableSelection(), close(), initScrollWidgetPage(), m_hotKeyEdits, m_ui, TTK::UI::PushButtonStyle04, saveParameterSettings(), MusicWidgetRenderer::setBackgroundLabel(), setScrollWidgetPageIndex(), and TTK::UI::ToolButtonStyle04.
MusicSettingWidget::~MusicSettingWidget ()
Object destructor.
Definition at line 143 of file musicsettingwidget.cpp.
References m_ui.
Member Function Documentation
void MusicSettingWidget::changeDesktopLrcWidget () slot
Change to desktop lrc widget.
Definition at line 434 of file musicsettingwidget.cpp.
References selectFunctionTableIndex(), and setScrollWidgetPageIndex().
void MusicSettingWidget::changeDownloadWidget () slot
Change to download widget.
Definition at line 446 of file musicsettingwidget.cpp.
References selectFunctionTableIndex(), and setScrollWidgetPageIndex().
Referenced by MusicRightAreaWidget::changeDownloadCustumWidget().
void MusicSettingWidget::changeInteriorLrcWidget () slot
Change to interior lrc widget.
Definition at line 440 of file musicsettingwidget.cpp.
References selectFunctionTableIndex(), and setScrollWidgetPageIndex().
void MusicSettingWidget::checkNetworkConnection () private slot
Check current network connection available.
Definition at line 563 of file musicsettingwidget.cpp.
References TTK_GENERATE_SINGLE_WIDGET.
Referenced by initNetworkWidget().
void MusicSettingWidget::clearFunctionTableSelection () private slot
Clear all function tables selection.
Definition at line 325 of file musicsettingwidget.cpp.
References m_ui.
Referenced by MusicSettingWidget(), and selectFunctionTableIndex().
void MusicSettingWidget::close () slot
Override close function.
Definition at line 320 of file musicsettingwidget.cpp.
Referenced by MusicSettingWidget(), and saveParameterSettings().
void MusicSettingWidget::defaultDesktopLrcColorChanged (int value) private slot
Default desktop lrc color change by index.
Definition at line 504 of file musicsettingwidget.cpp.
References Desktop, and lrcColorByDefault().
Referenced by initDesktopLrcWidget().
void MusicSettingWidget::defaultLrcColorChanged (int value) private slot
Default lrc color change by index.
Definition at line 462 of file musicsettingwidget.cpp.
References Interior, and lrcColorByDefault().
Referenced by initInteriorLrcWidget().
void MusicSettingWidget::desktopBackgroundChanged () private slot
Desktop lrc background change.
Definition at line 499 of file musicsettingwidget.cpp.
References Desktop, lcrColorValue(), and m_ui.
Referenced by initDesktopLrcWidget().
void MusicSettingWidget::desktopFrontgroundChanged () private slot
Desktop lrc foreground change.
Definition at line 494 of file musicsettingwidget.cpp.
References Desktop, lcrColorValue(), and m_ui.
Referenced by initDesktopLrcWidget().
void MusicSettingWidget::desktopLrcTransChanged (int value) private slot
Desktop lrc transparent changed by value.
Definition at line 509 of file musicsettingwidget.cpp.
References Desktop, lrcTransparentValue(), and m_ui.
Referenced by initDesktopLrcWidget().
void MusicSettingWidget::downloadCacheClean () private slot
Set clean download cache.
Definition at line 345 of file musicsettingwidget.cpp.
References APPCACHE_DIR_FULL, ART_DIR_FULL, BACKGROUND_DIR_FULL, CACHE_DIR_FULL, MusicAbstractMoveDialog::exec(), message(), MusicToastLabel::popup(), TTK::File::removeRecursively(), and MusicMessageBox::setText().
Referenced by initDownloadWidget().
void MusicSettingWidget::downloadDirChanged (int index) private slot
Set select download dir or lrc dir.
Definition at line 389 of file musicsettingwidget.cpp.
References TTK::File::getExistingDirectory(), and m_ui.
Referenced by initDownloadWidget().
void MusicSettingWidget::downloadFileNameRuleChanged (QAction * action) private slot
Set download file name rules.
Definition at line 364 of file musicsettingwidget.cpp.
References m_ui, and MusicRulesAnalysis::rule().
Referenced by initDownloadWidget().
void MusicSettingWidget::downloadGroupCached (int index) private slot
Set enable or disable download cache.
Definition at line 378 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initDownloadWidget().
void MusicSettingWidget::downloadGroupSpeedLimit (int index) private slot
Set enable or disable download speed limit.
Definition at line 383 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initDownloadWidget().
void MusicSettingWidget::fadeInAndOutClicked (bool state) private slot
Music fade in and out changed.
Definition at line 574 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initSoundEffectWidget().
void MusicSettingWidget::fileAssociationChanged () private slot
File association changed.
Definition at line 332 of file musicsettingwidget.cpp.
References MusicAbstractMoveDialog::exec().
Referenced by initNormalSettingWidget().
void MusicSettingWidget::globalHotkeyBoxChanged (bool state) private slot
Set global hotkey box changed.
Definition at line 337 of file musicsettingwidget.cpp.
References m_hotKeyEdits, and qAsConst.
Referenced by initialize(), and initNormalSettingWidget().
void MusicSettingWidget::initAudioSettingWidget () private
Init audio setting stack widget.
Definition at line 1079 of file musicsettingwidget.cpp.
References TTK::UI::CheckBoxStyle01, TTK::Widget::generateComboBoxStyle(), m_ui, Qmmp::PCM_S16LE, Qmmp::PCM_S24LE, Qmmp::PCM_S32LE, QmmpSettings::REPLAYGAIN_ALBUM, QmmpSettings::REPLAYGAIN_DISABLED, QmmpSettings::REPLAYGAIN_TRACK, and TTK::UI::SpinBoxStyle01.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initDesktopLrcWidget () private
Init desktop lrc stack widget.
Definition at line 962 of file musicsettingwidget.cpp.
References TTK::UI::CheckBoxStyle01, defaultDesktopLrcColorChanged(), desktopBackgroundChanged(), desktopFrontgroundChanged(), desktopLrcTransChanged(), TTK::Widget::generateComboBoxStyle(), m_ui, TTK::UI::PushButtonStyle04, QtFontFamilies, resetDesktopParameter(), showDesktopLrcDemo(), and TTK::UI::SliderStyle06.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initDownloadWidget () private
Init download stack widget.
Definition at line 821 of file musicsettingwidget.cpp.
References downloadCacheClean(), downloadDirChanged(), downloadFileNameRuleChanged(), downloadGroupCached(), downloadGroupSpeedLimit(), TTK::Widget::generateComboBoxStyle(), TTK::UI::LineEditStyle01, LRC_DIR_FULL, m_ui, TTK::UI::MenuStyle02, MUSIC_DIR_FULL, TTK::UI::PushButtonStyle04, TTK::UI::PushButtonStyle08, QtButtonGroupConnect, TTK::UI::RadioButtonStyle01, MusicRulesAnalysis::rules(), serverPluginChanged(), TTK::UI::SpinBoxStyle01, and TTK_SLOT.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initialize ()
Init widget and parameter.
Definition at line 148 of file musicsettingwidget.cpp.
References QmmpSettings::bufferSize(), MusicSettingManager::CloseEventMode, MusicSettingManager::CloseNetWorkMode, MusicSettingManager::DLrcBackgroundColor, MusicSettingManager::DLrcColor, MusicSettingManager::DLrcColorTransparent, MusicSettingManager::DLrcFamily, MusicSettingManager::DLrcFrontgroundColor, MusicSettingManager::DLrcSingleLineMode, MusicSettingManager::DLrcSize, MusicSettingManager::DLrcType, MusicSettingManager::DownloadCacheEnable, MusicSettingManager::DownloadCacheSize, MusicSettingManager::DownloadDownloadLimitSize, MusicSettingManager::DownloadFileNameRule, MusicSettingManager::DownloadLimitEnable, MusicSettingManager::DownloadLrcDirPath, MusicSettingManager::DownloadMusicDirPath, MusicSettingManager::DownloadServerIndex, MusicSettingManager::DownloadUploadLimitSize, MusicSettingManager::EnhancedFadeEnable, MusicSettingManager::EnhancedFadeInValue, MusicSettingManager::EnhancedFadeOutValue, MusicSettingManager::FileAssociationMode, G_HOTKEY_PTR, G_SETTING_PTR, globalHotkeyBoxChanged(), MusicSettingManager::HotkeyEnable, MusicSettingManager::HotkeyValue, QmmpSettings::instance(), MusicSettingManager::LanguageIndex, MusicSettingManager::LastPlayIndex, LRC_COLOR_OFFSET, MusicSettingManager::LrcBackgroundColor, MusicSettingManager::LrcColor, MusicSettingManager::LrcColorTransparent, MusicSettingManager::LrcFamily, MusicSettingManager::LrcFrontgroundColor, MusicSettingManager::LrcSize, MusicSettingManager::LrcType, m_hotKeyEdits, m_ui, MusicSettingManager::OtherCheckUpdateEnable, MusicSettingManager::OtherHighDpiScalingEnable, MusicSettingManager::OtherLogTrackEnable, MusicSettingManager::OtherLrcKTVMode, MusicSettingManager::OtherPlaylistAutoSaveEnable, MusicSettingManager::OtherRandomShuffleMode, MusicSettingManager::OtherReadAlbumCover, MusicSettingManager::OtherReadFileInfo, MusicSettingManager::OtherScreenSaverEnable, MusicSettingManager::OtherSideByMode, MusicSettingManager::OtherWriteAlbumCover, MusicSettingManager::OtherWriteFileInfo, QmmpSettings::outputFormat(), TTK::readColorConfig(), QmmpSettings::replayGainDefaultGain(), QmmpSettings::replayGainMode(), QmmpSettings::replayGainPreamp(), QmmpSettings::replayGainPreventClipping(), rippleLowPowerEnableBoxClicked(), MusicSettingManager::RippleLowPowerMode, MusicSettingManager::RippleSpectrumColor, MusicSettingManager::RippleSpectrumEnable, rippleSpectrumEnableClicked(), MusicSettingManager::RippleSpectrumTransparent, TTK::Widget::setComboBoxText(), TTK::Algorithm::sha1(), MusicSettingManager::ShowDesktopLrc, showDesktopLrcDemo(), showInteriorLrcDemo(), MusicSettingManager::StartUpMode, MusicSettingManager::StartUpPlayMode, TTK_NORMAL_LEVEL, TTK_SPLITER, TTK_VERSION_STR, TTK_VERSION_TIME_STR, TTKStaticCast, QmmpSettings::useDithering(), QmmpSettings::useSoftVolume(), QmmpSettings::volumeStep(), and MusicSettingManager::WindowQuitMode.
Referenced by MusicRightAreaWidget::showSettingWidget().
void MusicSettingWidget::initInteriorLrcWidget () private
Init interior lrc stack widget.
Definition at line 1001 of file musicsettingwidget.cpp.
References defaultLrcColorChanged(), TTK::Widget::generateComboBoxStyle(), interiorLrcBackgroundChanged(), interiorLrcFrontgroundChanged(), interiorLrcTransChanged(), m_ui, TTK::UI::PushButtonStyle04, QtFontFamilies, resetInteriorParameter(), showInteriorLrcDemo(), and TTK::UI::SliderStyle06.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initNetworkWidget () private
Init network stack widget.
Definition at line 1106 of file musicsettingwidget.cpp.
References checkNetworkConnection(), TTK::Widget::generateComboBoxStyle(), TTK::UI::LineEditStyle01, m_ui, TTK::UI::PushButtonStyle04, setNetworkProxyControl(), testNetworkConnection(), and testNetworkProxy().
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initNormalSettingWidget () private
Init normal setting stack widget.
Definition at line 773 of file musicsettingwidget.cpp.
References TTK::UI::CheckBoxStyle01, fileAssociationChanged(), TTK::Widget::generateComboBoxStyle(), globalHotkeyBoxChanged(), m_ui, TTK::UI::PushButtonStyle02, and TTK::UI::RadioButtonStyle01.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initOtherSettingWidget () private
Init other setting stack widget.
Definition at line 927 of file musicsettingwidget.cpp.
References TTK::UI::CheckBoxStyle01, m_ui, otherPluginManagerChanged(), and TTK::UI::PushButtonStyle04.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initScrollWidgetPage () private
Init scroll widget page widget.
Definition at line 726 of file musicsettingwidget.cpp.
References initAudioSettingWidget(), initDesktopLrcWidget(), initDownloadWidget(), initInteriorLrcWidget(), initNetworkWidget(), initNormalSettingWidget(), initOtherSettingWidget(), initSoundEffectWidget(), initSpectrumSettingWidget(), m_ui, SCROLL_ITEM_HEIGHT, scrollWidgetValueChanged(), and selectFunctionTableIndex().
Referenced by MusicSettingWidget().
void MusicSettingWidget::initSoundEffectWidget () private
Init sound effect stack widget.
Definition at line 1035 of file musicsettingwidget.cpp.
References TTK::UI::CheckBoxStyle01, fadeInAndOutClicked(), TTK::Widget::generateComboBoxStyle(), MusicApplicationModule::instance(), m_ui, TTK::UI::PushButtonStyle04, TTK::UI::SpinBoxStyle01, and TTK_DN_S2MS.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::initSpectrumSettingWidget () private
Init spectrum setting stack widget.
Definition at line 903 of file musicsettingwidget.cpp.
References TTK::UI::CheckBoxStyle01, m_ui, TTK::UI::PushButtonStyle04, rippleLowPowerEnableBoxClicked(), rippleSpectrumColorChanged(), rippleSpectrumEnableClicked(), rippleSpectrumTransChanged(), rippleVersionUpdateChanged(), and TTK::UI::SliderStyle06.
Referenced by initScrollWidgetPage().
void MusicSettingWidget::interiorLrcBackgroundChanged () private slot
Interior lrc background change.
Definition at line 457 of file musicsettingwidget.cpp.
References Interior, lcrColorValue(), and m_ui.
Referenced by initInteriorLrcWidget().
void MusicSettingWidget::interiorLrcFrontgroundChanged () private slot
Interior lrc foreground change.
Definition at line 452 of file musicsettingwidget.cpp.
References Interior, lcrColorValue(), and m_ui.
Referenced by initInteriorLrcWidget().
void MusicSettingWidget::interiorLrcTransChanged (int value) private slot
Interior lrc transparent changed by value.
Definition at line 467 of file musicsettingwidget.cpp.
References Interior, lrcTransparentValue(), and m_ui.
Referenced by initInteriorLrcWidget().
void MusicSettingWidget::lcrColorValue (Lrc key, const QString & type, QLabel * obj) private
Set lrc color value by type and value type.
Definition at line 1150 of file musicsettingwidget.cpp.
References MusicLrcColorWidget::colors(), MusicAbstractMoveDialog::exec(), Interior, m_ui, MusicLrcColorWidget::setColors(), showDesktopLrcDemo(), showInteriorLrcDemo(), TTK_NORMAL_LEVEL, and TTKObjectCast.
Referenced by desktopBackgroundChanged(), desktopFrontgroundChanged(), interiorLrcBackgroundChanged(), and interiorLrcFrontgroundChanged().
void MusicSettingWidget::lrcColorByDefault (Lrc key, int index) private
Set lrc default color by type and index.
Definition at line 1168 of file musicsettingwidget.cpp.
References Interior, LRC_COLOR_OFFSET, MusicLrcColor::m_backColor, MusicLrcColor::m_frontColor, m_ui, TTK::mapIndexToColor(), showDesktopLrcDemo(), showInteriorLrcDemo(), and TTKStaticCast.
Referenced by defaultDesktopLrcColorChanged(), and defaultLrcColorChanged().
void MusicSettingWidget::lrcTransparentValue (Lrc key, int value) const private
Set lrc transparent by type and value.
Definition at line 1191 of file musicsettingwidget.cpp.
References Interior, m_ui, MusicPreviewLabel::setLinearGradient(), and MusicPreviewLabel::setTransparent().
Referenced by desktopLrcTransChanged(), and interiorLrcTransChanged().
void MusicSettingWidget::otherPluginManagerChanged () private slot
Plugin manager changed.
Definition at line 429 of file musicsettingwidget.cpp.
References MusicAbstractMoveDialog::exec().
Referenced by initOtherSettingWidget().
void MusicSettingWidget::parameterSettingChanged () signal
Parameters setting changed.
Referenced by saveParameterSettings().
void MusicSettingWidget::resetDesktopParameter () private slot
Reset desktop parameter.
Definition at line 527 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initDesktopLrcWidget().
void MusicSettingWidget::resetInteriorParameter () private slot
Reset interior parameter.
Definition at line 485 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initInteriorLrcWidget().
void MusicSettingWidget::rippleLowPowerEnableBoxClicked (bool state) private slot
Ripple low power mode enable changed.
Definition at line 423 of file musicsettingwidget.cpp.
References m_ui, and rippleSpectrumEnableClicked().
Referenced by initialize(), and initSpectrumSettingWidget().
void MusicSettingWidget::rippleSpectrumColorChanged () private slot
Ripple spectrum color changed.
Definition at line 403 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initSpectrumSettingWidget().
void MusicSettingWidget::rippleSpectrumEnableClicked (bool state) private slot
Ripple spectrum enable changed.
Definition at line 417 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initialize(), initSpectrumSettingWidget(), and rippleLowPowerEnableBoxClicked().
void MusicSettingWidget::rippleSpectrumTransChanged (int value) private slot
Ripple spectrum transparent changed by value.
Definition at line 412 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initSpectrumSettingWidget().
void MusicSettingWidget::rippleVersionUpdateChanged () private slot
Version update check changed.
Definition at line 398 of file musicsettingwidget.cpp.
References MusicSourceUpdateWidget::exec().
Referenced by initSpectrumSettingWidget().
void MusicSettingWidget::saveParameterSettings () private slot
Save the parameter setting results.
Definition at line 580 of file musicsettingwidget.cpp.
References Apply, close(), MusicSettingManager::CloseEventMode, MusicSettingManager::DLrcBackgroundColor, MusicSettingManager::DLrcColor, MusicSettingManager::DLrcColorTransparent, MusicSettingManager::DLrcFamily, MusicSettingManager::DLrcFrontgroundColor, MusicSettingManager::DLrcSingleLineMode, MusicSettingManager::DLrcSize, MusicSettingManager::DLrcType, MusicSettingManager::DownloadCacheEnable, MusicSettingManager::DownloadCacheSize, MusicSettingManager::DownloadDownloadLimitSize, MusicSettingManager::DownloadFileNameRule, MusicSettingManager::DownloadLimitEnable, MusicSettingManager::DownloadLrcDirPath, MusicSettingManager::DownloadMusicDirPath, MusicSettingManager::DownloadServerIndex, MusicSettingManager::DownloadUploadLimitSize, MusicSettingManager::EnhancedFadeEnable, MusicSettingManager::EnhancedFadeInValue, MusicSettingManager::EnhancedFadeOutValue, MusicAbstractMoveDialog::exec(), MusicSettingManager::FileAssociationMode, G_HOTKEY_PTR, G_NETWORK_PTR, G_SETTING_PTR, MusicSettingManager::HotkeyEnable, MusicSettingManager::HotkeyValue, QmmpSettings::instance(), MusicSettingManager::LanguageIndex, MusicSettingManager::LastPlayIndex, LRC_COLOR_OFFSET, MusicSettingManager::LrcBackgroundColor, MusicSettingManager::LrcColor, MusicSettingManager::LrcColorTransparent, MusicSettingManager::LrcFamily, MusicSettingManager::LrcFrontgroundColor, MusicSettingManager::LrcSize, MusicSettingManager::LrcType, m_hotKeyEdits, m_ui, message(), MusicSettingManager::OtherCheckUpdateEnable, MusicSettingManager::OtherHighDpiScalingEnable, MusicSettingManager::OtherLogTrackEnable, MusicSettingManager::OtherLrcKTVMode, MusicSettingManager::OtherPlaylistAutoSaveEnable, MusicSettingManager::OtherRandomShuffleMode, MusicSettingManager::OtherReadAlbumCover, MusicSettingManager::OtherReadFileInfo, MusicSettingManager::OtherScreenSaverEnable, MusicSettingManager::OtherSideByMode, MusicSettingManager::OtherWriteAlbumCover, MusicSettingManager::OtherWriteFileInfo, parameterSettingChanged(), MusicSettingManager::RippleLowPowerMode, MusicSettingManager::RippleSpectrumColor, MusicSettingManager::RippleSpectrumEnable, MusicSettingManager::RippleSpectrumTransparent, QmmpSettings::setAudioSettings(), QmmpSettings::setBufferSize(), setNetworkProxyByType(), QmmpSettings::setReplayGainSettings(), MusicMessageBox::setText(), QmmpSettings::setVolumeStep(), MusicSettingManager::ShowDesktopLrc, MusicSettingManager::StartUpMode, MusicSettingManager::StartUpPlayMode, TTK_SPLITER, TTKStaticCast, MusicSettingManager::WindowQuitMode, and TTK::writeColorConfig().
Referenced by MusicSettingWidget().
void MusicSettingWidget::scrollWidgetValueChanged (int value) private slot
Scroll widget index changed.
Definition at line 709 of file musicsettingwidget.cpp.
References SCROLL_ITEM_HEIGHT, and selectFunctionTableIndex().
Referenced by initScrollWidgetPage().
void MusicSettingWidget::selectFunctionTableIndex (int row, int column) private
Select function table index.
Definition at line 1138 of file musicsettingwidget.cpp.
References clearFunctionTableSelection(), and m_ui.
Referenced by changeDesktopLrcWidget(), changeDownloadWidget(), changeInteriorLrcWidget(), initScrollWidgetPage(), and scrollWidgetValueChanged().
void MusicSettingWidget::serverPluginChanged () private slot
Server plugin manager changed.
Definition at line 373 of file musicsettingwidget.cpp.
References MusicAbstractMoveDialog::exec().
Referenced by initDownloadWidget().
bool MusicSettingWidget::setNetworkProxyByType (Proxy type) private
Set network proxy by type.
Definition at line 1209 of file musicsettingwidget.cpp.
References Apply, MusicNetworkProxy::applyProxy(), m_ui, MusicToastLabel::popup(), MusicNetworkProxy::setHostName(), MusicNetworkProxy::setPassword(), MusicNetworkProxy::setPort(), MusicNetworkProxy::setType(), MusicNetworkProxy::setUser(), Test, MusicNetworkProxy::testProxy(), and testProxyStateChanged().
Referenced by saveParameterSettings(), and testNetworkProxy().
void MusicSettingWidget::setNetworkProxyControl (int enable) private slot
Set network proxy control enabled or not.
Definition at line 536 of file musicsettingwidget.cpp.
References m_ui.
Referenced by initNetworkWidget().
void MusicSettingWidget::setScrollWidgetPageIndex (int index) private slot
Set scroll widget page index.
Definition at line 704 of file musicsettingwidget.cpp.
References m_ui, and SCROLL_ITEM_HEIGHT.
Referenced by changeDesktopLrcWidget(), changeDownloadWidget(), changeInteriorLrcWidget(), and MusicSettingWidget().
void MusicSettingWidget::showDesktopLrcDemo () private slot
Show desktop lrc preview.
Definition at line 515 of file musicsettingwidget.cpp.
References MusicPreviewLabelItem::m_background, MusicPreviewLabelItem::m_family, MusicPreviewLabelItem::m_frontground, MusicPreviewLabelItem::m_size, MusicPreviewLabelItem::m_type, and m_ui.
Referenced by initDesktopLrcWidget(), initialize(), lcrColorValue(), and lrcColorByDefault().
void MusicSettingWidget::showInteriorLrcDemo () private slot
Show interior lrc preview.
Definition at line 473 of file musicsettingwidget.cpp.
References MusicPreviewLabelItem::m_background, MusicPreviewLabelItem::m_family, MusicPreviewLabelItem::m_frontground, MusicPreviewLabelItem::m_size, MusicPreviewLabelItem::m_type, and m_ui.
Referenced by initialize(), initInteriorLrcWidget(), lcrColorValue(), and lrcColorByDefault().
void MusicSettingWidget::testNetworkConnection () private slot
Test current network connection available.
Definition at line 556 of file musicsettingwidget.cpp.
References MusicNetworkOperator::startToRequest(), and testNetworkConnectionStateChanged().
Referenced by initNetworkWidget().
void MusicSettingWidget::testNetworkConnectionStateChanged (const QString & name) private slot
Test current network connection available changed.
Definition at line 568 of file musicsettingwidget.cpp.
References m_ui.
Referenced by testNetworkConnection().
void MusicSettingWidget::testNetworkProxy () private slot
Test current proxy available.
Definition at line 546 of file musicsettingwidget.cpp.
References setNetworkProxyByType(), and Test.
Referenced by initNetworkWidget().
void MusicSettingWidget::testProxyStateChanged (bool state) private slot
Test current proxy available changed.
Definition at line 551 of file musicsettingwidget.cpp.
References MusicToastLabel::popup().
Referenced by setNetworkProxyByType().
Member Data Documentation
QVector<MusicGlobalHotKeyEdit*> MusicSettingWidget::m_hotKeyEdits private
Definition at line 382 of file musicsettingwidget.h.
Referenced by globalHotkeyBoxChanged(), initialize(), MusicSettingWidget(), and saveParameterSettings().
Ui::MusicSettingWidget* MusicSettingWidget::m_ui private
Definition at line 380 of file musicsettingwidget.h.
Referenced by clearFunctionTableSelection(), desktopBackgroundChanged(), desktopFrontgroundChanged(), desktopLrcTransChanged(), downloadDirChanged(), downloadFileNameRuleChanged(), downloadGroupCached(), downloadGroupSpeedLimit(), fadeInAndOutClicked(), initAudioSettingWidget(), initDesktopLrcWidget(), initDownloadWidget(), initialize(), initInteriorLrcWidget(), initNetworkWidget(), initNormalSettingWidget(), initOtherSettingWidget(), initScrollWidgetPage(), initSoundEffectWidget(), initSpectrumSettingWidget(), interiorLrcBackgroundChanged(), interiorLrcFrontgroundChanged(), interiorLrcTransChanged(), lcrColorValue(), lrcColorByDefault(), lrcTransparentValue(), MusicSettingWidget(), resetDesktopParameter(), resetInteriorParameter(), rippleLowPowerEnableBoxClicked(), rippleSpectrumColorChanged(), rippleSpectrumEnableClicked(), rippleSpectrumTransChanged(), saveParameterSettings(), selectFunctionTableIndex(), setNetworkProxyByType(), setNetworkProxyControl(), setScrollWidgetPageIndex(), showDesktopLrcDemo(), showInteriorLrcDemo(), testNetworkConnectionStateChanged(), and ~MusicSettingWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsettingwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsettingwidget.cpp