TTKMusicPlayer: TTK::Widget Namespace Reference
TTK::Widget Namespace Reference
Functions
TTK_MODULE_EXPORT void setFontSize (QWidget *widget, int size)
TTK_MODULE_EXPORT void setFontStyle (QWidget *widget, TTK::FontStyleMode type)
TTK_MODULE_EXPORT QString elidedText (const QFont &font, const QString &text, Qt::TextElideMode mode, int width)
TTK_MODULE_EXPORT QString elidedTitleText (const QFont &font, const QString &text, int width)
TTK_MODULE_EXPORT int fontTextWidth (const QFont &font, const QString &text)
TTK_MODULE_EXPORT int fontTextHeight (const QFont &font)
TTK_MODULE_EXPORT void adjustMenuPosition (QMenu *menu)
TTK_MODULE_EXPORT void adjustWidgetPosition (QWidget *widget)
TTK_MODULE_EXPORT void setTransparent (QWidget *widget, int alpha)
TTK_MODULE_EXPORT void setTransparent (QWidget *widget, const QColor &color)
TTK_MODULE_EXPORT void setComboBoxText (QComboBox *widget, const QString &text)
TTK_MODULE_EXPORT void widgetToRound (QWidget *widget, int ratioX, int ratioY)
TTK_MODULE_EXPORT void generateComboBoxFormat (QComboBox *widget, const QString &style={})
TTK_MODULE_EXPORT void generateVScrollAreaFormat (QWidget *widget, QWidget *parent, bool background=true)
TTK_MODULE_EXPORT void generateHScrollAreaFormat (QWidget *widget, QWidget *parent, bool background=true)
Function Documentation
void TTK::Widget::adjustMenuPosition (QMenu * menu)
Adjust the menu position.
Definition at line 61 of file musicwidgetutils.cpp.
Referenced by MusicSearchEdit::contextMenuEvent(), MusicCloudManagerTableWidget::contextMenuEvent(), MusicSongsListPlayTableWidget::contextMenuEvent(), MusicLrcContainerForInterior::contextMenuEvent(), MusicSongsContainerWidget::contextMenuEvent(), MusicVideoView::createRightMenu(), MusicApplication::createRightMenu(), MusicApplication::importSongsPopup(), and MusicSongsToolBoxTopWidget::showMenu().
void TTK::Widget::adjustWidgetPosition (QWidget * widget)
Adjust the widget in screen center.
Definition at line 78 of file musicwidgetutils.cpp.
References TTKDesktopWrapper::screenGeometry().
Referenced by MusicDownloadWidget::MusicDownloadWidget(), MusicTTKFMRadioPlayWidget::MusicTTKFMRadioPlayWidget(), and MusicWebFMRadioPlayWidget::MusicWebFMRadioPlayWidget().
QString TTK::Widget::elidedText (const QFont & font, const QString & text, Qt::TextElideMode mode, int width)
Set text elided text by font.
Definition at line 34 of file musicwidgetutils.cpp.
Referenced by MusicCloudDownloadTableWidget::addCellItem(), MusicDownloadRecordTableWidget::addCellItem(), MusicDownloadBatchTableItem::addCellItem(), MusicSongSearchPopTableWidget::addCellItem(), MusicConnectTransferCompleteTableWidget::addCellItem(), MusicCloudUploadTableWidget::addCellItem(), MusicCloudManagerTableWidget::addCellItem(), MusicConnectTransferTableWidget::addCellItems(), MusicSongCheckToolsRenameTableWidget::addCellItems(), MusicSongItemSelectedTableWidget::addCellItems(), MusicLrcDownloadBatchTableWidget::addCellItems(), MusicMobileSongsTableWidget::addCellItems(), MusicLrcLocalLinkTableWidget::addCellItems(), MusicSongCheckToolsDuplicateTableWidget::addCellItems(), MusicSongCheckToolsQualityTableWidget::addCellItems(), MusicReplayGainWidget::addItemFinished(), MusicSongsListPlayedTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayTableWidget::adjustPlayWidgetRow(), MusicSongsListPlayWidget::changItemName(), MusicSongsListPlayTableWidget::closeRenameItem(), MusicAlbumQueryWidget::createAlbumItem(), MusicArtistQueryWidget::createArtistItem(), MusicWebMVRadioInfoWidget::createMVRadioProgramItem(), MusicWebDJRadioInfoWidget::createProgramCategoryItem(), MusicWebDJRadioProgramTableWidget::createProgramItem(), MusicLrcSearchTableWidget::createResultItem(), MusicItemQueryTableWidget::createResultItem(), MusicSongSearchTableWidget::createResultItem(), MusicVideoSearchTableWidget::createResultItem(), MusicToplistQueryWidget::createToplistItem(), elidedTitleText(), MusicSongsListItemInfoWidget::initialize(), MusicSongsListPlayedWidget::initialize(), MusicSongsListPlayWidget::initialize(), MusicSongSharingWidget::initialize(), MusicDownloadWidget::initialize(), MusicSongRingtoneMaker::initInputPath(), MusicTransformWidget::initInputPath(), MusicLrcSearchWidget::lrcSearchButtonClicked(), MusicWebDJRadioProgramTableWidget::resizeSection(), MusicCloudManagerTableWidget::resizeSection(), MusicItemQueryTableWidget::resizeSection(), MusicSongSearchTableWidget::resizeSection(), MusicVideoSearchTableWidget::resizeSection(), MusicPlaylistQueryInfoWidget::resizeWidget(), MusicWebDJRadioInfoWidget::resizeWidget(), MusicAlbumQueryWidget::resizeWidget(), MusicToplistQueryWidget::resizeWidget(), MusicWebMVRadioInfoWidget::resizeWidget(), MusicArtistQueryWidget::resizeWidget(), MusicConnectTransferWidget::setDeviceInfoItem(), MusicRemoteWidgetForStrip::setLabelText(), MusicRemoteWidgetForRipple::setLabelText(), MusicRemoteWidgetForRectangle::setLabelText(), MusicRemoteWidgetForSimpleStyle::setLabelText(), MusicSystemTrayMenu::setLabelText(), MusicSongSearchOnlineWidget::setResizeLabelText(), MusicArtistAlbumsItemWidget::setResultDataItem(), MusicArtistListQueryItemWidget::setResultDataItem(), MusicWebDJRadioQueryItemWidget::setResultDataItem(), MusicWebDJRadioCategoryItemWidget::setResultDataItem(), MusicWebMVRadioQueryItemWidget::setResultDataItem(), MusicPlaylistQueryItemWidget::setResultDataItem(), MusicFunctionToolBoxTopWidget::setTitle(), MusicVideoPlayWidget::setTitleText(), MusicSongsListPlayTableWidget::startToDrag(), MusicTransformWidget::transformFinish(), MusicConnectLocalWidget::updateDeviceDisplay(), MusicPlaylistBackupTableWidget::updateSongsList(), MusicSongsListPlayedTableWidget::updateSongsList(), and MusicSongsListPlayTableWidget::updateSongsList().
QString TTK::Widget::elidedTitleText (const QFont & font, const QString & text, int width)
Set title text elided text by font.
Definition at line 40 of file musicwidgetutils.cpp.
References elidedText(), fontTextWidth(), and TTK::String::suffix().
Referenced by MusicPlaylistBackupWidget::currentItemChanged(), MusicPlaylistBackupWidget::currentTimeChanged(), MusicPlaylistBackupWidget::resizeWidget(), and MusicFunctionToolBoxTopWidget::setTitle().
int TTK::Widget::fontTextHeight (const QFont & font)
Get font height by font.
Definition at line 55 of file musicwidgetutils.cpp.
Referenced by MusicBarrageWidget::createLabel(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme10(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), MusicLrcManagerForInterior::paintEvent(), MusicLrcManagerHorizontalDesktop::paintEvent(), MusicLrcManagerVerticalDesktop::paintEvent(), MusicPreviewLabel::paintEvent(), and MusicLrcContainerForInterior::showNoLrcCurrentInfo().
int TTK::Widget::fontTextWidth (const QFont & font, const QString & text)
Get text width by font.
Definition at line 49 of file musicwidgetutils.cpp.
References QtFontWidth.
Referenced by MusicCommentsItem::addCellItem(), MusicLrcFloatPhotoWidget::artistNameChanged(), MusicBarrageWidget::createLabel(), MusicPageQueryWidget::createPageWidget(), MusicLrcPosterItemWidget::drawTheme1(), MusicLrcPosterItemWidget::drawTheme10(), MusicLrcPosterItemWidget::drawTheme11(), MusicLrcPosterItemWidget::drawTheme12(), MusicLrcPosterItemWidget::drawTheme13(), MusicLrcPosterItemWidget::drawTheme14(), MusicLrcPosterItemWidget::drawTheme15(), MusicLrcPosterItemWidget::drawTheme16(), MusicLrcPosterItemWidget::drawTheme17(), MusicLrcPosterItemWidget::drawTheme2(), MusicLrcPosterItemWidget::drawTheme3(), MusicLrcPosterItemWidget::drawTheme4(), MusicLrcPosterItemWidget::drawTheme5(), MusicLrcPosterItemWidget::drawTheme6(), MusicLrcPosterItemWidget::drawTheme7(), MusicLrcPosterItemWidget::drawTheme8(), MusicLrcPosterItemWidget::drawTheme9(), elidedTitleText(), MusicSplitItemClickedLabel::mouseMoveEvent(), MusicLrcMakerWidgetItem::moveRight(), MusicLrcManagerForInterior::paintEvent(), MusicMarqueeWidget::paintEvent(), MusicLrcMakerWidgetItem::paintEvent(), MusicBackgroundListItem::paintEvent(), MusicMarqueeWidget::setText(), MusicLrcMakerWidgetItem::setText(), MusicLrcManager::setText(), MusicLrcContainerForInterior::showNoLrcCurrentInfo(), MusicLrcManager::startDrawLrcMask(), MusicMarqueeWidget::timerEvent(), and MusicPageQueryWidget::updateStatus().
void TTK::Widget::generateComboBoxFormat (QComboBox * widget, const QString & style = {})
Generate combobox format style.
Definition at line 119 of file musicwidgetutils.cpp.
References TTK::UI::ComboBoxStyle01, TTK::UI::ItemView01, and TTK::UI::ScrollBarStyle01.
Referenced by MusicBackgroundOnlineWidget::createFunctionsWidget(), MusicSettingWidget::initAudioSettingWidget(), MusicSettingWidget::initDesktopLrcWidget(), MusicSettingWidget::initDownloadWidget(), MusicTimerWidget::initFirstWidget(), MusicSettingWidget::initInteriorLrcWidget(), MusicSettingWidget::initNetworkWidget(), MusicSettingWidget::initNormalSettingWidget(), MusicTimerWidget::initSecondWidget(), MusicSettingWidget::initSoundEffectWidget(), MusicTimerWidget::initThreeWidget(), MusicDownloadBatchTableItem::MusicDownloadBatchTableItem(), MusicDownloadBatchWidget::MusicDownloadBatchWidget(), MusicEqualizerDialog::MusicEqualizerDialog(), MusicPlaylistBackupWidget::MusicPlaylistBackupWidget(), MusicSongRingtoneMaker::MusicSongRingtoneMaker(), MusicSoundEffectsWidget::MusicSoundEffectsWidget(), and MusicTransformWidget::MusicTransformWidget().
void TTK::Widget::generateHScrollAreaFormat (QWidget * widget, QWidget * parent, bool background = true)
Generate horizontal scrollArea format style.
Definition at line 143 of file musicwidgetutils.cpp.
References TTK::UI::ScrollBarStyle02, TTK::UI::ScrollBarStyle04, and TTKObjectCast.
Referenced by MusicLrcPosterWidget::MusicLrcPosterWidget().
void TTK::Widget::generateVScrollAreaFormat (QWidget * widget, QWidget * parent, bool background = true)
Generate vertical scrollArea format style.
Definition at line 126 of file musicwidgetutils.cpp.
References TTK::UI::ScrollBarStyle01, TTK::UI::ScrollBarStyle03, and TTKObjectCast.
Referenced by MusicArtistListQueryWidget::createArtistListItem(), MusicRecommendQueryWidget::createLabels(), MusicSimilarQueryWidget::createLabels(), MusicWebDJRadioInfoWidget::createLabels(), MusicAlbumQueryWidget::createLabels(), MusicToplistQueryWidget::createLabels(), MusicWebMVRadioInfoWidget::createLabels(), MusicArtistQueryWidget::createLabels(), MusicWebMVRadioQueryWidget::createMVRadioCategoryItem(), MusicPlaylistQueryWidget::createPlaylistItem(), MusicWebDJRadioQueryWidget::createProgramItem(), MusicCommentsWidget::initialize(), MusicSpectrumLayoutWidget::initialize(), MusicPlayedListPopWidget::initialize(), MusicBackgroundSkinDialog::MusicBackgroundSkinDialog(), MusicFunctionToolBoxWidget::MusicFunctionToolBoxWidget(), MusicLrcPhotoManagerWidget::MusicLrcPhotoManagerWidget(), MusicLrcPosterWidget::MusicLrcPosterWidget(), MusicLrcTranslatedWidget::MusicLrcTranslatedWidget(), MusicSoundEffectsWidget::MusicSoundEffectsWidget(), MusicWebDJRadioCategoryWidget::MusicWebDJRadioCategoryWidget(), MusicPlaylistFoundCategoryPopWidget::setCategory(), MusicWebMVRadioQueryCategoryPopWidget::setCategory(), MusicToplistQueryCategoryPopWidget::setCategory(), MusicArtistListQueryCategoryPopWidget::setCategory(), and MusicPlaylistQueryInfoWidget::setResultDataItem().
void TTK::Widget::setComboBoxText (QComboBox * widget, const QString & text)
Set ComboBox text.
Definition at line 98 of file musicwidgetutils.cpp.
Referenced by MusicSettingWidget::initialize().
void TTK::Widget::setFontSize (QWidget * widget, int size)
Set widget font.
Definition at line 10 of file musicwidgetutils.cpp.
Referenced by MusicBarrageWidget::createLabel(), MusicLrcContainerForInterior::createNoLrcCurrentInfo(), and MusicEqualizerDialog::initialize().
void TTK::Widget::setFontStyle (QWidget * widget, TTK::FontStyleMode type)
Set widget font style.
Definition at line 17 of file musicwidgetutils.cpp.
References TTK::Bold, TTK::FixedPitch, TTK::Italic, TTK::Kerningt, TTK::Overline, TTK::StrikeOut, and TTK::Underline.
Referenced by MusicLrcContainerForInterior::createNoLrcCurrentInfo(), MusicFunctionToolBoxTopWidget::MusicFunctionToolBoxTopWidget(), and MusicOpenFileWidget::MusicOpenFileWidget().
void TTK::Widget::setTransparent (QWidget * widget, int alpha)
Set widget transparent.
Definition at line 84 of file musicwidgetutils.cpp.
Referenced by MusicAbstractTableWidget::MusicAbstractTableWidget(), MusicCloudDownloadTableWidget::MusicCloudDownloadTableWidget(), MusicCloudManagerTableWidget::MusicCloudManagerTableWidget(), MusicCloudUploadTableWidget::MusicCloudUploadTableWidget(), MusicDownloadBatchTableWidget::MusicDownloadBatchTableWidget(), MusicDownloadRecordTableWidget::MusicDownloadRecordTableWidget(), MusicDownloadTableWidget::MusicDownloadTableWidget(), MusicFillItemTableWidget::MusicFillItemTableWidget(), MusicMobileSongsTableWidget::MusicMobileSongsTableWidget(), MusicSongSearchPopTableWidget::MusicSongSearchPopTableWidget(), MusicSongsListPlayedTableWidget::MusicSongsListPlayedTableWidget(), MusicSongsListPlayTableWidget::MusicSongsListPlayTableWidget(), and MusicWebFMRadioWidget::MusicWebFMRadioWidget().
void TTK::Widget::setTransparent (QWidget * widget, const QColor & color)
Set widget transparent.
Definition at line 91 of file musicwidgetutils.cpp.
void TTK::Widget::widgetToRound (QWidget * widget, int ratioX, int ratioY)
Set widget to round by ratioX and ratioY.
Definition at line 114 of file musicwidgetutils.cpp.
References TTK::Image::generateMask().