TTKMusicPlayer: TTKThirdParty/TTKExtras/qrencode/rscode.c File Reference
rscode.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include "rscode.h"
Classes
struct _RS
Reed-Solomon codec control block.
Macros
#define MODNN(x) modnn(rs,x)
#define MM (rs->mm)
#define NN (rs->nn)
#define ALPHA_TO (rs->alpha_to)
#define INDEX_OF (rs->index_of)
#define GENPOLY (rs->genpoly)
#define NROOTS (rs->nroots)
#define FCR (rs->fcr)
#define PRIM (rs->prim)
#define IPRIM (rs->iprim)
#define PAD (rs->pad)
#define A0 (NN)
#define A0 (NN) /* Special reserved value encoding zero in index form */
Typedefs
typedef unsigned char data_t
Functions
static int modnn (RS *rs, int x)
static RS * init_rs_char (int symsize, int gfpoly, int fcr, int prim, int nroots, int pad)
RS * init_rs (int symsize, int gfpoly, int fcr, int prim, int nroots, int pad)
void free_rs_char (RS *rs)
void free_rs_cache (void)
void encode_rs_char (RS *rs, const data_t *data, data_t *parity)
Variables
static RS * rslist = NULL
static pthread_mutex_t rslist_mutex = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
#define A0 (NN)
Definition at line 297 of file rscode.c.
Referenced by encode_rs_char(), and init_rs_char().
#define A0 (NN) /* Special reserved value encoding zero in index form */
Definition at line 297 of file rscode.c.
#define ALPHA_TO (rs->alpha_to)
Definition at line 78 of file rscode.c.
Referenced by encode_rs_char().
#define FCR (rs->fcr)
Definition at line 82 of file rscode.c.
#define GENPOLY (rs->genpoly)
Definition at line 80 of file rscode.c.
Referenced by encode_rs_char().
#define INDEX_OF (rs->index_of)
Definition at line 79 of file rscode.c.
Referenced by encode_rs_char().
#define IPRIM (rs->iprim)
Definition at line 84 of file rscode.c.
#define MM (rs->mm)
Definition at line 76 of file rscode.c.
#define MODNN (x) modnn(rs,x)
Definition at line 74 of file rscode.c.
Referenced by encode_rs_char().
#define NN (rs->nn)
Definition at line 77 of file rscode.c.
Referenced by encode_rs_char().
#define NROOTS (rs->nroots)
Definition at line 81 of file rscode.c.
Referenced by encode_rs_char().
#define PAD (rs->pad)
Definition at line 85 of file rscode.c.
Referenced by encode_rs_char().
#define PRIM (rs->prim)
Definition at line 83 of file rscode.c.
Typedef Documentation
typedef unsigned char data_t
Definition at line 39 of file rscode.c.
Function Documentation
void encode_rs_char (RS * rs, const data_t * data, data_t * parity)
Definition at line 299 of file rscode.c.
References A0, ALPHA_TO, GENPOLY, INDEX_OF, MODNN, NN, NROOTS, and PAD.
Referenced by RSblock_initBlock().
void free_rs_cache (void)
Definition at line 249 of file rscode.c.
References free_rs_char(), _RS::next, rslist, and rslist_mutex.
Referenced by QRcode_clearCache().
void free_rs_char (RS * rs)
Definition at line 241 of file rscode.c.
References _RS::alpha_to, _RS::genpoly, and _RS::index_of.
Referenced by free_rs_cache().
RS* init_rs (int symsize, int gfpoly, int fcr, int prim, int nroots, int pad)
Definition at line 210 of file rscode.c.
References DONE, _RS::fcr, _RS::gfpoly, init_rs_char(), _RS::mm, _RS::next, _RS::nroots, _RS::pad, _RS::prim, rslist, and rslist_mutex.
Referenced by MQRraw_new(), and RSblock_init().
static RS* init_rs_char (int symsize, int gfpoly, int fcr, int prim, int nroots, int pad) static
Definition at line 97 of file rscode.c.
References A0, _RS::alpha_to, _RS::fcr, _RS::genpoly, _RS::gfpoly, _RS::index_of, _RS::iprim, _RS::mm, modnn(), _RS::nn, _RS::nroots, _RS::pad, and _RS::prim.
Referenced by init_rs().
static int modnn (RS * rs, int x) static
Definition at line 65 of file rscode.c.
References _RS::mm, and _RS::nn.
Referenced by init_rs_char().
Variable Documentation
RS* rslist = NULL static
Definition at line 60 of file rscode.c.
Referenced by free_rs_cache(), and init_rs().
pthread_mutex_t rslist_mutex = PTHREAD_MUTEX_INITIALIZER static
Definition at line 62 of file rscode.c.
Referenced by free_rs_cache(), and init_rs().