TTKMusicplayer: MusicMessageBox Class Reference
MusicMessageBox Class Reference
The class of the messagebox widget.
#include <musicmessagebox.h>
Public Slots
void buttonClicked (int index)
virtual int exec ()
void show ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicMessageBox (QWidget *parent=0)
MusicMessageBox (const QString &text, QWidget *parent=0)
MusicMessageBox (const QString &title, const QString &text, QWidget *parent=0)
virtual ~MusicMessageBox ()
void setTitle (const QString &text) const
QString title () const
void setText (const QString &text) const
QString text () const
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=0)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=0)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicAbstractMoveDialog
static QString getClassName ()
Protected Attributes
Ui::MusicMessageBox * m_ui
int m_status
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the messagebox widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 21 of file musicmessagebox.h.
Constructor & Destructor Documentation
MusicMessageBox::MusicMessageBox (QWidget * parent = 0) explicit
Definition at line 8 of file musicmessagebox.cpp.
References buttonClicked(), m_status, m_ui, MusicUIObject::MPushButtonStyle04, and MusicUIObject::MToolButtonStyle04.
MusicMessageBox::MusicMessageBox (const QString & text, QWidget * parent = 0) explicit
Object contsructor.
Definition at line 44 of file musicmessagebox.cpp.
References setText().
MusicMessageBox::MusicMessageBox (const QString & title, const QString & text, QWidget * parent = 0)
Object contsructor by context text.
Definition at line 50 of file musicmessagebox.cpp.
References setTitle().
MusicMessageBox::~MusicMessageBox () virtual
Object contsructor by context text and title.
Definition at line 57 of file musicmessagebox.cpp.
References m_ui.
Member Function Documentation
void MusicMessageBox::buttonClicked (int index) slot
Get context text.
Definition at line 87 of file musicmessagebox.cpp.
References m_status.
Referenced by MusicMessageBox().
int MusicMessageBox::exec () virtual slot
Confirm or cancal button clicked, set the state.
Definition at line 98 of file musicmessagebox.cpp.
References m_status, m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicLocalSongsManagerWidget::addButtonClick(), MusicQueryFoundTableWidget::addSearchMusicToPlayList(), MusicSongSearchOnlineTableWidget::addSearchMusicToPlayList(), MusicVolumeGainWidget::applyButtonClicked(), MusicLocalSongsManagerWidget::auditionButtonClick(), MusicSongSearchOnlineTableWidget::auditionToMusic(), MusicSongSearchOnlineTableWidget::auditionToMusicStop(), MusicLrcMakerWidget::backToMakeLrcWidget(), MusicUserDialog::buttonClicked(), MusicSongSearchOnlineWidget::buttonClicked(), MusicLrcMakerWidget::checkInputValid(), MusicUserDialog::checkRegisterUser(), MusicUserDialog::checkUserForgotPasswd(), MusicUserDialog::checkUserLogin(), MusicApplicationObject::closeCurrentEqualizer(), MusicLrcErrorWidget::confirmButtonClicked(), MusicLrcLocalLinkWidget::confirmButtonClicked(), MusicUserRecordWidget::confirmButtonClickedT(), MusicDesktopWallpaperWidget::confirmButtonPressed(), MusicUserWindow::connectDatabase(), MusicCloudSharedSongTableWidget::deleteFileFinished(), MusicLrcLocalLinkWidget::deleteFoundLrc(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItems(), MusicSourceUpdateWidget::downloadProgressFinished(), MusicSongCheckToolsWidget::duplicateCheckFinished(), MusicSongRingtoneMaker::exec(), MusicTransformWidget::exec(), MusicLocalSongsManagerWidget::filterIndexChanged(), MusicSoundTouchWidget::finished(), MusicConnectTransferWidget::getSelectedFiles(), MusicBackgroundListWidget::itemCloseClicked(), MusicToolSetsWidget::itemHasClicked(), MusicLrcSearchWidget::lrcSearchDownloadClicked(), MusicPlayListManager::messageAlert(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicSoundKMicroSearchTableWidget::musicDownloadLocal(), MusicVideoTableWidget::musicDownloadLocal(), MusicRightAreaWidget::musicFunctionClicked(), MusicApplication::musicImportSongsSettingPath(), MusicFileInformationWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicFileInformationWidget::musicSaveTag(), MusicApplicationObject::musicToolSetsParameter(), MusicAudioRecorderCore::onRecordPlay(), MusicAudioRecorderCore::onRecordStart(), MusicSoundKMicroWidget::playFinished(), MusicTransformWidget::processTransform(), MusicSongSharingWidget::queryUrlTimeout(), MusicSoundKMicroWidget::recordButtonClicked(), MusicLrcMakerWidget::reMakeButtonClicked(), MusicSongCheckToolsWidget::renameCheckFinished(), MusicVolumeGainWidget::rmFileButtonClicked(), MusicLrcMakerWidget::saveButtonClicked(), MusicLrcMakerWidget::setCurrentThirdWidget(), MusicDownloadRecordWidget::setDeleteItemAt(), MusicCloudDownloadTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setDeleteItemAt(), MusicSettingWidget::setNetworkProxyByType(), MusicSoundTouchWidget::show(), MusicVolumeGainWidget::show(), MusicDownloadWidget::startToDownload(), MusicConnectTransferWidget::startToTransferWIFIFiles(), MusicVideoView::stop(), MusicSettingWidget::testProxyStateChanged(), and MusicLrcArtPhotoUploadWidget::uploadButtonClicked().
QString MusicMessageBox::getClassName () static
Definition at line 62 of file musicmessagebox.cpp.
void MusicMessageBox::setText (const QString & text) const
Get box title.
Definition at line 77 of file musicmessagebox.cpp.
References m_ui.
Referenced by MusicLocalSongsManagerWidget::addButtonClick(), MusicQueryFoundTableWidget::addSearchMusicToPlayList(), MusicSongSearchOnlineTableWidget::addSearchMusicToPlayList(), MusicVolumeGainWidget::applyButtonClicked(), MusicLocalSongsManagerWidget::auditionButtonClick(), MusicSongSearchOnlineTableWidget::auditionToMusic(), MusicSongSearchOnlineTableWidget::auditionToMusicStop(), MusicLrcMakerWidget::backToMakeLrcWidget(), MusicUserDialog::buttonClicked(), MusicSongSearchOnlineWidget::buttonClicked(), MusicLrcMakerWidget::checkInputValid(), MusicUserDialog::checkRegisterUser(), MusicUserDialog::checkUserForgotPasswd(), MusicUserDialog::checkUserLogin(), MusicApplicationObject::closeCurrentEqualizer(), MusicLrcErrorWidget::confirmButtonClicked(), MusicLrcLocalLinkWidget::confirmButtonClicked(), MusicUserRecordWidget::confirmButtonClickedT(), MusicDesktopWallpaperWidget::confirmButtonPressed(), MusicUserWindow::connectDatabase(), MusicCloudSharedSongTableWidget::deleteFileFinished(), MusicLrcLocalLinkWidget::deleteFoundLrc(), MusicSongsSummariziedWidget::deleteRowItem(), MusicSongsSummariziedWidget::deleteRowItems(), MusicSourceUpdateWidget::downloadProgressFinished(), MusicSongCheckToolsWidget::duplicateCheckFinished(), MusicSongRingtoneMaker::exec(), MusicTransformWidget::exec(), MusicLocalSongsManagerWidget::filterIndexChanged(), MusicSoundTouchWidget::finished(), MusicConnectTransferWidget::getSelectedFiles(), MusicBackgroundListWidget::itemCloseClicked(), MusicToolSetsWidget::itemHasClicked(), MusicLrcSearchWidget::lrcSearchDownloadClicked(), MusicPlayListManager::messageAlert(), MusicLrcSearchTableWidget::musicDownloadLocal(), MusicSoundKMicroSearchTableWidget::musicDownloadLocal(), MusicVideoTableWidget::musicDownloadLocal(), MusicRightAreaWidget::musicFunctionClicked(), MusicApplication::musicImportSongsSettingPath(), MusicMessageBox(), MusicFileInformationWidget::musicOpenFileDir(), MusicSongsListAbstractTableWidget::musicOpenFileDir(), MusicFileInformationWidget::musicSaveTag(), MusicApplicationObject::musicToolSetsParameter(), MusicAudioRecorderCore::onRecordPlay(), MusicAudioRecorderCore::onRecordStart(), MusicSoundKMicroWidget::playFinished(), MusicTransformWidget::processTransform(), MusicSongSharingWidget::queryUrlTimeout(), MusicSoundKMicroWidget::recordButtonClicked(), MusicLrcMakerWidget::reMakeButtonClicked(), MusicSongCheckToolsWidget::renameCheckFinished(), MusicVolumeGainWidget::rmFileButtonClicked(), MusicLrcMakerWidget::saveButtonClicked(), MusicLrcMakerWidget::setCurrentThirdWidget(), MusicDownloadRecordWidget::setDeleteItemAt(), MusicCloudDownloadTableWidget::setDeleteItemAt(), MusicSongsListTableWidget::setDeleteItemAt(), MusicSettingWidget::setNetworkProxyByType(), MusicSoundTouchWidget::show(), MusicVolumeGainWidget::show(), MusicConnectTransferWidget::startToTransferWIFIFiles(), MusicVideoView::stop(), MusicSettingWidget::testProxyStateChanged(), and MusicLrcArtPhotoUploadWidget::uploadButtonClicked().
void MusicMessageBox::setTitle (const QString & text) const
Get class object name.
Definition at line 67 of file musicmessagebox.cpp.
References m_ui.
Referenced by MusicMessageBox().
void MusicMessageBox::show () slot
Override exec function.
Definition at line 105 of file musicmessagebox.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
QString MusicMessageBox::text () const
Set context text.
Definition at line 82 of file musicmessagebox.cpp.
References m_ui.
QString MusicMessageBox::title () const
Set box title.
Definition at line 72 of file musicmessagebox.cpp.
References m_ui.
Member Data Documentation
int MusicMessageBox::m_status protected
Definition at line 78 of file musicmessagebox.h.
Referenced by buttonClicked(), exec(), and MusicMessageBox().
Ui::MusicMessageBox* MusicMessageBox::m_ui protected
Override show function.
Definition at line 77 of file musicmessagebox.h.
Referenced by exec(), MusicMessageBox(), setText(), setTitle(), show(), text(), title(), and ~MusicMessageBox().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetCoreKits/musicmessagebox.h
TTKModule/TTKWidget/musicWidgetCoreKits/musicmessagebox.cpp