TTKMusicplayer: QKugouWindow Class Reference
QKugouWindow Class Reference
The class of the kugou window widget.
#include <qkugouwindow.h>
Public Types
enum KuGouType {
KuGouSong, KuGouRadio, KuGouList, KugouMovie,
KuGouSingle
}
Public Slots
void goBack ()
void refresh ()
Public Member Functions
QKugouWindow (KuGouType type, QWidget *parent=nullptr)
void setUrl (const QString &url)
Protected Member Functions
void createWebViewer ()
void createKugouSongWidget ()
void createKugouRadioWidget ()
void createKugouListWidget ()
void createKugouMovieWidget ()
void createKugouSingleWidget ()
void changeClickedButtonStyle (int index)
Private Slots
void kugouSongIndexChanged (int index)
void kugouRadioIndexChanged (int index)
void kugouMVIndexChanged (int index)
Detailed Description
The class of the kugou window widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file qkugouwindow.h.
Member Enumeration Documentation
enum QKugouWindow::KuGouType
Enumerator
KuGouSong
KuGou Song
KuGouRadio
KuGou Radio
KuGouList
KuGou List
KugouMovie
Kugou Mv
KuGouSingle
KuGou Single
Definition at line 34 of file qkugouwindow.h.
Constructor & Destructor Documentation
QKugouWindow::QKugouWindow (KuGouType type, QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 56 of file qkugouwindow.cpp.
References createKugouListWidget(), createKugouMovieWidget(), createKugouRadioWidget(), createKugouSingleWidget(), createKugouSongWidget(), KuGouList, KugouMovie, KuGouRadio, KuGouSingle, KuGouSong, and TTK_INIT_PRIVATE.
Member Function Documentation
void QKugouWindow::changeClickedButtonStyle (int index) protected
Change clicked button style by index.
Definition at line 455 of file qkugouwindow.cpp.
References MusicUIObject::MQSSPushButtonStyle01, MusicUIObject::MQSSPushButtonStyle02, and TTK_D.
Referenced by kugouMVIndexChanged(), kugouRadioIndexChanged(), and kugouSongIndexChanged().
void QKugouWindow::createKugouListWidget () protected
Create kugou list widget.
Definition at line 352 of file qkugouwindow.cpp.
References createWebViewer(), QKugouUrl::makeListUrl(), TTK_D, and TTKObject_cast.
Referenced by QKugouWindow().
void QKugouWindow::createKugouMovieWidget () protected
Create kugou movie widget.
Definition at line 381 of file qkugouwindow.cpp.
References createWebViewer(), kugouMVIndexChanged(), MusicUIObject::MQSSPushButtonStyle01, MusicUIObject::MQSSWidgetStyle01, QtButtonGroupConnect, and TTK_D.
Referenced by QKugouWindow().
void QKugouWindow::createKugouRadioWidget () protected
Create kugou radio widget.
Definition at line 299 of file qkugouwindow.cpp.
References createWebViewer(), kugouRadioIndexChanged(), MusicUIObject::MQSSPushButtonStyle01, MusicUIObject::MQSSWidgetStyle01, QtButtonGroupConnect, and TTK_D.
Referenced by QKugouWindow().
void QKugouWindow::createKugouSingleWidget () protected
Create kugou single widget.
Definition at line 434 of file qkugouwindow.cpp.
References createWebViewer(), QKugouUrl::makeKuiSheUrl(), setUrl(), and TTK_D.
Referenced by QKugouWindow().
void QKugouWindow::createKugouSongWidget () protected
Create kugou song widget.
Definition at line 241 of file qkugouwindow.cpp.
References createWebViewer(), kugouSongIndexChanged(), MusicUIObject::MQSSPushButtonStyle01, MusicUIObject::MQSSWidgetStyle01, QtButtonGroupConnect, and TTK_D.
Referenced by QKugouWindow().
void QKugouWindow::createWebViewer () protected
Create web view widget.
Definition at line 210 of file qkugouwindow.cpp.
References TTK_D.
Referenced by createKugouListWidget(), createKugouMovieWidget(), createKugouRadioWidget(), createKugouSingleWidget(), and createKugouSongWidget().
void QKugouWindow::goBack () slot
Set web index go back.
Definition at line 116 of file qkugouwindow.cpp.
References TTK_D, and TTKObject_cast.
void QKugouWindow::kugouMVIndexChanged (int index) private slot
Kugou MV index changed.
Definition at line 195 of file qkugouwindow.cpp.
References changeClickedButtonStyle(), QKugouUrl::makeMVFanxingUrl(), QKugouUrl::makeMVRadioUrl(), QKugouUrl::makeMVRecommendUrl(), and setUrl().
Referenced by createKugouMovieWidget().
void QKugouWindow::kugouRadioIndexChanged (int index) private slot
Kugou radio index changed.
Definition at line 180 of file qkugouwindow.cpp.
References changeClickedButtonStyle(), QKugouUrl::makeRadioFxUrl(), QKugouUrl::makeRadioHighFmUrl(), QKugouUrl::makeRadioPublicUrl(), and setUrl().
Referenced by createKugouRadioWidget().
void QKugouWindow::kugouSongIndexChanged (int index) private slot
Kugou song index changed.
Definition at line 164 of file qkugouwindow.cpp.
References changeClickedButtonStyle(), QKugouUrl::makeSongCategoryUrl(), QKugouUrl::makeSongRankUrl(), QKugouUrl::makeSongRecommendUrl(), QKugouUrl::makeSongSingerUrl(), and setUrl().
Referenced by createKugouSongWidget().
void QKugouWindow::refresh () slot
Set web index refresh.
Definition at line 140 of file qkugouwindow.cpp.
References TTK_D, and TTKObject_cast.
void QKugouWindow::setUrl (const QString & url)
Set current web viewer url to show.
Definition at line 87 of file qkugouwindow.cpp.
References TTK_D, and TTKObject_cast.
Referenced by createKugouSingleWidget(), kugouMVIndexChanged(), kugouRadioIndexChanged(), and kugouSongIndexChanged().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qkugou/qkugouwindow.h
TTKThirdParty/TTKExtras/qkugou/qkugouwindow.cpp