TTKMusicplayer: MusicDownloadRecordConfigManager Class Reference
MusicDownloadRecordConfigManager Class Reference
The class of the download record manager.
#include <musicdownloadrecordconfigmanager.h>
Public Member Functions
MusicDownloadRecordConfigManager (MusicObject::RecordType type, QObject *parent=nullptr)
void setType (MusicObject::RecordType type)
MusicObject::RecordType type () const
bool fromFile ()
void readBuffer (MusicSongList &items)
void writeBuffer (const MusicSongList &items)
Public Member Functions inherited from MusicAbstractXml
MusicAbstractXml (QObject *parent=nullptr)
~MusicAbstractXml ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
bool toFile (const QString &name)
QString toString () const
QByteArray toByteArray () const
QString readXmlAttributeByTagNameValue (const QString &tagName) const
QString readXmlAttributeByTagName (const QString &tagName, const QString &attrName) const
QString readXmlTextByTagName (const QString &tagName) const
TTKVariantMap readXmlAttributesByTagName (const QString &tagName) const
void createProcessingInstruction ()
QDomElement createRoot (const QString &node)
QDomElement createRoot (const QString &node, const MusicXmlAttribute &attr)
QDomElement createRoot (const QString &node, const MusicXmlAttributeList &attrs)
QDomElement writeDomNode (QDomElement &element, const QString &node)
QDomElement writeDomElement (QDomElement &element, const QString &node, const MusicXmlAttribute &attr)
QDomElement writeDomMutilElement (QDomElement &element, const QString &node, const MusicXmlAttributeList &attrs)
QDomElement writeDomElementText (QDomElement &element, const QString &node, const MusicXmlAttribute &attr, const QString &text)
QDomElement writeDomMutilElementText (QDomElement &element, const QString &node, const MusicXmlAttributeList &attrs, const QString &text)
QDomElement writeDomText (QDomElement &element, const QString &node, const QString &text)
void writeAttribute (QDomElement &element, const MusicXmlAttribute &attr)
Protected Member Functions
QString mappingFilePathFromEnum () const
Protected Attributes
MusicObject::RecordType m_type
Protected Attributes inherited from MusicAbstractXml
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the download record manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 28 of file musicdownloadrecordconfigmanager.h.
Constructor & Destructor Documentation
MusicDownloadRecordConfigManager::MusicDownloadRecordConfigManager (MusicObject::RecordType type, QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 3 of file musicdownloadrecordconfigmanager.cpp.
References m_type, and type().
Member Function Documentation
bool MusicDownloadRecordConfigManager::fromFile () inline
Read datas from xml file.
Definition at line 50 of file musicdownloadrecordconfigmanager.h.
References MusicAbstractXml::fromFile().
Referenced by MusicDownloadBatchTableItem::startToDownloadMusic(), MusicDownloadWidget::startToDownloadMusic(), and MusicAbstractDownloadTableWidget::updateSongsFileName().
QString MusicDownloadRecordConfigManager::mappingFilePathFromEnum () const protected
Mapping file path from enum type.
Definition at line 45 of file musicdownloadrecordconfigmanager.cpp.
References CLOUD_DOWN_PATH_FULL, CLOUD_UP_PATH_FULL, m_type, NORMAL_DOWN_PATH_FULL, MusicObject::RecordCloudDownload, MusicObject::RecordCloudUpload, and MusicObject::RecordNormalDownload.
Referenced by writeBuffer().
void MusicDownloadRecordConfigManager::readBuffer (MusicSongList & items)
Read datas from config file.
Definition at line 9 of file musicdownloadrecordconfigmanager.cpp.
References MusicAbstractXml::m_document, MusicSong::setAddTimeStr(), MusicSong::setName(), MusicSong::setPath(), and MusicSong::setSizeStr().
Referenced by MusicDownloadBatchTableItem::startToDownloadMusic(), MusicDownloadWidget::startToDownloadMusic(), and MusicAbstractDownloadTableWidget::updateSongsFileName().
void MusicDownloadRecordConfigManager::setType (MusicObject::RecordType type) inline
Set config type.
Definition at line 41 of file musicdownloadrecordconfigmanager.h.
MusicObject::RecordType MusicDownloadRecordConfigManager::type () const inline
Get config type.
Definition at line 45 of file musicdownloadrecordconfigmanager.h.
Referenced by MusicDownloadRecordConfigManager().
void MusicDownloadRecordConfigManager::writeBuffer (const MusicSongList & items)
Write datas into config file.
Definition at line 23 of file musicdownloadrecordconfigmanager.cpp.
References APP_NAME, MusicAbstractXml::createProcessingInstruction(), MusicAbstractXml::createRoot(), MusicAbstractXml::m_document, MusicAbstractXml::m_file, mappingFilePathFromEnum(), MusicAbstractXml::toFile(), MusicAbstractXml::writeDomMutilElementText(), and MusicAbstractXml::writeDomNode().
Referenced by MusicDownloadBatchTableItem::startToDownloadMusic(), MusicDownloadWidget::startToDownloadMusic(), and MusicAbstractDownloadTableWidget::~MusicAbstractDownloadTableWidget().
Member Data Documentation
MusicObject::RecordType MusicDownloadRecordConfigManager::m_type protected
Definition at line 67 of file musicdownloadrecordconfigmanager.h.
Referenced by mappingFilePathFromEnum(), and MusicDownloadRecordConfigManager().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsKits/musicdownloadrecordconfigmanager.h
TTKModule/TTKCore/musicToolsKits/musicdownloadrecordconfigmanager.cpp