TTKMusicplayer: MusicUserRecordWidget Class Reference
MusicUserRecordWidget Class Reference
The class of the user record widget.
#include <musicuserrecordwidget.h>
Public Slots
void cityComboBoxIndexChanged (int index)
void confirmButtonClickedF ()
void openFileButtonClickedS ()
void saveFileButtonClickedS ()
void intersectedPixmap (const QPixmap &pix)
void changeVerificationCodeT ()
void confirmButtonClickedT ()
void checkPwdStrength (int code)
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Signals
void resetUserName (const QString &name)
void userIconChanged (const MusicUserUIDItem &uid, const QString &icon)
Public Member Functions
MusicUserRecordWidget (QWidget *parent=nullptr)
~MusicUserRecordWidget ()
void setUserModel (MusicUserModel *model, const MusicUserUIDItem &uid)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Static Public Member Functions
static QString avatarPixmapRender (const MusicUserUIDItem &item, const QPixmap &pix)
Protected Member Functions
void initTabF ()
void initTabS ()
void initTabT ()
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Protected Attributes
Ui::MusicUserRecordWidget * m_ui
MusicUserModel * m_userModel
MusicUserUIDItem m_userUID
QString m_iconLocalPath
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Detailed Description
The class of the user record widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 35 of file musicuserrecordwidget.h.
Constructor & Destructor Documentation
MusicUserRecordWidget::MusicUserRecordWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 12 of file musicuserrecordwidget.cpp.
References m_ui, MusicUIObject::MQSSTabWidgetStyle01, MusicUIObject::MQSSToolButtonStyle04, and MusicUtils::Widget::setLabelFontSize().
MusicUserRecordWidget::~MusicUserRecordWidget ()
Definition at line 32 of file musicuserrecordwidget.cpp.
References m_ui.
Member Function Documentation
QString MusicUserRecordWidget::avatarPixmapRender (const MusicUserUIDItem & item, const QPixmap & pix) static
Avatar pixmap render.
Definition at line 37 of file musicuserrecordwidget.cpp.
References AVATAR_DIR_FULL, JPG_FILE, MusicUserUIDItem::m_server, MusicUserUIDItem::m_uid, MusicUtils::Algorithm::md5(), name, and TTK_STR_SPLITER.
Referenced by saveFileButtonClickedS().
void MusicUserRecordWidget::changeVerificationCodeT () slot
Change verfication button clicked.
Definition at line 197 of file musicuserrecordwidget.cpp.
References m_ui.
Referenced by initTabT().
void MusicUserRecordWidget::checkPwdStrength (int code) slot
Check the new password strength.
Definition at line 240 of file musicuserrecordwidget.cpp.
References m_ui, MusicUIObject::MQSSBackgroundStyle14, and MusicUIObject::MQSSBackgroundStyle15.
Referenced by initTabT().
void MusicUserRecordWidget::cityComboBoxIndexChanged (int index) slot
City index has changed.
Definition at line 147 of file musicuserrecordwidget.cpp.
References MusicUserModel::getAllCountries(), m_ui, and m_userModel.
Referenced by initTabF().
void MusicUserRecordWidget::confirmButtonClickedF () slot
Save first information button clicked.
Definition at line 155 of file musicuserrecordwidget.cpp.
References MusicUserModel::getUserName(), m_ui, m_userModel, m_userUID, resetUserName(), and MusicUserModel::updateUser().
Referenced by initTabF().
void MusicUserRecordWidget::confirmButtonClickedT () slot
Modify third password button clicked.
Definition at line 204 of file musicuserrecordwidget.cpp.
References m_ui, m_userModel, m_userUID, MusicUserModel::passwordCheck(), MusicToastLabel::popup(), MusicUserModel::updateUserPwd(), and userIconChanged().
Referenced by initTabT().
int MusicUserRecordWidget::exec () virtual slot
Override exec function.
Definition at line 259 of file musicuserrecordwidget.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicUserManagerDialog::popupUserRecordWidget().
void MusicUserRecordWidget::initTabF () protected
init first infomation widget.
Definition at line 72 of file musicuserrecordwidget.cpp.
References cityComboBoxIndexChanged(), confirmButtonClickedF(), MusicUserModel::getAllCities(), MusicUserModel::getUserBirthday(), MusicUserModel::getUserCity(), MusicUserModel::getUserCountry(), MusicUserModel::getUserLogTime(), MusicUserModel::getUserName(), MusicUserModel::getUserSex(), MusicUserModel::getUserSignature(), m_ui, MusicUserUIDItem::m_uid, m_userModel, m_userUID, MusicUIObject::MQSSComboBoxStyle01, MusicUIObject::MQSSDateEditStyle01, MusicUIObject::MQSSItemView01, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle06, MusicUIObject::MQSSRadioButtonStyle01, MusicUIObject::MQSSScrollBarStyle01, MusicUIObject::MQSSTextEditStyle01, MUSIC_YEAR_FORMAT, and MusicUtils::Widget::setComboBoxText().
Referenced by setUserModel().
void MusicUserRecordWidget::initTabS () protected
init second change icon widget.
Definition at line 119 of file musicuserrecordwidget.cpp.
References MusicUserModel::getUserIcon(), intersectedPixmap(), m_ui, m_userModel, m_userUID, MusicUIObject::MQSSPushButtonStyle06, openFileButtonClickedS(), and saveFileButtonClickedS().
Referenced by setUserModel().
void MusicUserRecordWidget::initTabT () protected
init third security widget.
Definition at line 130 of file musicuserrecordwidget.cpp.
References changeVerificationCodeT(), checkPwdStrength(), confirmButtonClickedT(), m_ui, MusicUIObject::MQSSLineEditStyle01, MusicUIObject::MQSSPushButtonStyle06, MusicUserLineEdit::PasswdConfirm, and MusicUserLineEdit::PasswdNew.
Referenced by setUserModel().
void MusicUserRecordWidget::intersectedPixmap (const QPixmap & pix) slot
Send intersected pixmap if intersected flag set.
Definition at line 192 of file musicuserrecordwidget.cpp.
References m_ui.
Referenced by initTabS().
void MusicUserRecordWidget::openFileButtonClickedS () slot
Open selected new pic button clicked.
Definition at line 168 of file musicuserrecordwidget.cpp.
References MusicUtils::File::getOpenFileDialog(), m_iconLocalPath, and m_ui.
Referenced by initTabS().
void MusicUserRecordWidget::resetUserName (const QString & name) signal
Reset current user name.
Referenced by confirmButtonClickedF().
void MusicUserRecordWidget::saveFileButtonClickedS () slot
Save selected new pic button clicked.
Definition at line 179 of file musicuserrecordwidget.cpp.
References avatarPixmapRender(), m_iconLocalPath, m_ui, m_userModel, m_userUID, MusicUserModel::updateUserIcon(), and userIconChanged().
Referenced by initTabS().
void MusicUserRecordWidget::setUserModel (MusicUserModel * model, const MusicUserUIDItem & uid)
Set user model.
first tab
second tab
third tab
Definition at line 48 of file musicuserrecordwidget.cpp.
References initTabF(), initTabS(), initTabT(), m_ui, MusicUserUIDItem::m_uid, m_userModel, and m_userUID.
Referenced by MusicUserManagerDialog::popupUserRecordWidget().
void MusicUserRecordWidget::userIconChanged (const MusicUserUIDItem & uid, const QString & icon) signal
Reset current user icon.
Referenced by confirmButtonClickedT(), and saveFileButtonClickedS().
Member Data Documentation
QString MusicUserRecordWidget::m_iconLocalPath protected
Definition at line 121 of file musicuserrecordwidget.h.
Referenced by openFileButtonClickedS(), and saveFileButtonClickedS().
Ui::MusicUserRecordWidget* MusicUserRecordWidget::m_ui protected
Definition at line 118 of file musicuserrecordwidget.h.
Referenced by changeVerificationCodeT(), checkPwdStrength(), cityComboBoxIndexChanged(), confirmButtonClickedF(), confirmButtonClickedT(), exec(), initTabF(), initTabS(), initTabT(), intersectedPixmap(), MusicUserRecordWidget(), openFileButtonClickedS(), saveFileButtonClickedS(), setUserModel(), and ~MusicUserRecordWidget().
MusicUserModel* MusicUserRecordWidget::m_userModel protected
Definition at line 119 of file musicuserrecordwidget.h.
Referenced by cityComboBoxIndexChanged(), confirmButtonClickedF(), confirmButtonClickedT(), initTabF(), initTabS(), saveFileButtonClickedS(), and setUserModel().
MusicUserUIDItem MusicUserRecordWidget::m_userUID protected
Definition at line 120 of file musicuserrecordwidget.h.
Referenced by confirmButtonClickedF(), confirmButtonClickedT(), initTabF(), initTabS(), saveFileButtonClickedS(), and setUserModel().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicUserKits/musicuserrecordwidget.h
TTKModule/TTKWidget/musicUserKits/musicuserrecordwidget.cpp