TTKMusicplayer: QDesWrapper Class Reference
QDesWrapper Class Reference
The class of the des wrapper.
#include <qdeswrapper.h>
Public Types
enum Mode { ENCRYPT = 0, DECRYPT = 1 }
Public Member Functions
QDesWrapper ()
QByteArray encrypt (const QByteArray &in, const QByteArray &key)
QByteArray decrypt (const QByteArray &in, const QByteArray &key)
Detailed Description
The class of the des wrapper.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file qdeswrapper.h.
Member Enumeration Documentation
enum QDesWrapper::Mode
Enumerator
ENCRYPT
DECRYPT
Definition at line 32 of file qdeswrapper.h.
Constructor & Destructor Documentation
QDesWrapper::QDesWrapper ()
Object contsructor.
Definition at line 342 of file qdeswrapper.cpp.
References TTK_INIT_PRIVATE.
Member Function Documentation
QByteArray QDesWrapper::decrypt (const QByteArray & in, const QByteArray & key)
Decrypt des by input.
Definition at line 359 of file qdeswrapper.cpp.
References Base64::base64Decode(), DECRYPT, and TTK_D.
QByteArray QDesWrapper::encrypt (const QByteArray & in, const QByteArray & key)
Encrypt des by input.
Definition at line 347 of file qdeswrapper.cpp.
References Base64::base64Encode(), ENCRYPT, and TTK_D.
Referenced by MusicKWQueryInterface::readFromMusicLLAttribute(), and MusicKWQueryMovieRequest::readFromMusicMVAttribute().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qalgorithm/qdeswrapper.h
TTKThirdParty/TTKExtras/qalgorithm/qdeswrapper.cpp