TTKMusicplayer: MusicDJRadioProgramThread Class Reference
MusicDJRadioProgramThread Class Reference
The class of music dj radio program thread.
#include <musicdjradioprogramthread.h>
Public Slots
virtual void downLoadFinished () override
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Public Member Functions
MusicDJRadioProgramThread (QObject *parent=0)
QJson import.
void startToDownload (Program::Type type)
Public Member Functions inherited from MusicDJRadioThreadAbstract
MusicDJRadioThreadAbstract (QObject *parent=0)
virtual void deleteAll () override
MusicResultsItems getSearchedItems () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
void setNetworkAbort (bool a)
bool networkAbort ()
void setRawData (const QVariantMap &data)
QVariantMap getRawData () const
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDJRadioThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Signals inherited from MusicDJRadioThreadAbstract
void createProgramItem (const MusicResultsItem &item)
Signals inherited from MusicNetworkAbstract
void rawDataChanged (const QVariantMap &data)
void downLoadDataChanged (const QString &data)
Protected Member Functions inherited from MusicNetworkAbstract
void setSslConfiguration (QNetworkRequest *request, QSslSocket::PeerVerifyMode m=QSslSocket::VerifyNone)
Protected Member Functions inherited from MusicDownLoadWYInterface
void makeTokenQueryQequest (QNetworkRequest *request)
QJson import.
QByteArray makeTokenQueryUrl (QNetworkRequest *request, const QString &query, const QString &type)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate)
void readFromMusicSongAttributeNew (MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all)
QString encryptedId (qint64 id)
QString encryptedId (const QString &string)
Protected Attributes inherited from MusicDJRadioThreadAbstract
MusicResultsItems m_items
Protected Attributes inherited from MusicNetworkAbstract
QVariantMap m_rawData
StateCode m_stateCode
volatile bool m_interrupt
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Detailed Description
The class of music dj radio program thread.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 39 of file musicdjradioprogramthread.h.
Constructor & Destructor Documentation
MusicDJRadioProgramThread::MusicDJRadioProgramThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 7 of file musicdjradioprogramthread.cpp.
Member Function Documentation
void MusicDJRadioProgramThread::downLoadFinished () override virtual slot
Download data from net finished.
Definition at line 37 of file musicdjradioprogramthread.cpp.
References MusicDJRadioThreadAbstract::createProgramItem(), MusicDJRadioThreadAbstract::deleteAll(), MusicNetworkAbstract::downLoadDataChanged(), MusicResultsItem::m_coverUrl, MusicResultsItem::m_id, MusicNetworkAbstract::m_interrupt, MusicDJRadioThreadAbstract::m_items, MusicResultsItem::m_name, MusicResultsItem::m_nickName, MusicResultsItem::m_playCount, MusicNetworkAbstract::m_reply, MusicResultsItem::m_tags, MusicResultsItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToDownload().
QString MusicDJRadioProgramThread::getClassName () static
Get class object name.
Definition at line 13 of file musicdjradioprogramthread.cpp.
void MusicDJRadioProgramThread::startToDownload (Program::Type type)
Start to download data.
Definition at line 18 of file musicdjradioprogramthread.cpp.
References MusicDJRadioThreadAbstract::deleteAll(), DJ_HOT_N_URL, DJ_HOT_NDT_URL, DJ_RECOMMEND_N_URL, downLoadFinished(), MusicNetworkAbstract::Init, MusicNetworkAbstract::m_interrupt, MusicNetworkAbstract::m_manager, MusicNetworkAbstract::m_reply, MusicNetworkAbstract::m_stateCode, MusicDownLoadWYInterface::makeTokenQueryUrl(), MusicUtils::Algorithm::mdII(), Program::Recommed, MusicNetworkAbstract::replyError(), and MusicNetworkAbstract::setSslConfiguration().
Referenced by MusicWebDJRadioProgramTableWidget::init().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicdjradioprogramthread.h
TTKModule/TTKCore/musicNetworkKits/radio/dj/musicdjradioprogramthread.cpp