TTKMusicplayer: MusicTimerAutoObject Class Reference
MusicTimerAutoObject Class Reference
The class of the time auto run.
#include <musictimerautoobject.h>
Public Slots
void timeout ()
Public Member Functions
MusicTimerAutoObject (QObject *parent=0)
~MusicTimerAutoObject ()
void runTimerAutoConfig ()
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
void setShutdown ()
Protected Attributes
QTimer m_timer
MusicTimeObjects m_timeObjects
Detailed Description
The class of the time auto run.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 42 of file musictimerautoobject.h.
Constructor & Destructor Documentation
MusicTimerAutoObject::MusicTimerAutoObject (QObject * parent = 0) explicit
Object contsructor.
Definition at line 13 of file musictimerautoobject.cpp.
References MusicTimeObject::m_index, m_timeObjects, m_timer, and timeout().
MusicTimerAutoObject::~MusicTimerAutoObject ()
Definition at line 25 of file musictimerautoobject.cpp.
References m_timer.
Member Function Documentation
QString MusicTimerAutoObject::getClassName () static
Get class object name.
Definition at line 30 of file musictimerautoobject.cpp.
void MusicTimerAutoObject::runTimerAutoConfig ()
Run time auto from local file config.
Definition at line 35 of file musictimerautoobject.cpp.
References M_SETTING_PTR, m_timeObjects, m_timer, MT_S2MS, MusicSettingManager::TimerAutoPlayChoiced, MusicSettingManager::TimerAutoPlayHourChoiced, MusicSettingManager::TimerAutoPlaySecondChoiced, MusicSettingManager::TimerAutoShutdownChoiced, MusicSettingManager::TimerAutoShutdownHourChoiced, MusicSettingManager::TimerAutoShutdownSecondChoiced, MusicSettingManager::TimerAutoStopChoiced, MusicSettingManager::TimerAutoStopHourChoiced, and MusicSettingManager::TimerAutoStopSecondChoiced.
Referenced by MusicApplicationObject::musicToolSetsParameter().
void MusicTimerAutoObject::setShutdown () protected
Set current system to shutdown.
Definition at line 116 of file musictimerautoobject.cpp.
References M_LOGGER_INFO, and MStatic_cast.
Referenced by timeout().
void MusicTimerAutoObject::timeout () slot
Check current state by one minute.
Definition at line 61 of file musictimerautoobject.cpp.
References MusicApplication::instance(), MusicTimeObject::m_hour, MusicTimeObject::m_index, MusicTimeObject::m_minute, M_SETTING_PTR, MusicTimeObject::m_state, m_timeObjects, MusicApplication::setPlaySongChanged(), setShutdown(), MusicApplication::setStopSongChanged(), MusicSettingManager::TimerAutoPlayChoiced, MusicSettingManager::TimerAutoPlayRepeatChoiced, MusicSettingManager::TimerAutoPlaySongIndexChoiced, MusicSettingManager::TimerAutoShutdownChoiced, MusicSettingManager::TimerAutoShutdownRepeatChoiced, MusicSettingManager::TimerAutoStopChoiced, and MusicSettingManager::TimerAutoStopRepeatChoiced.
Referenced by MusicTimerAutoObject().
Member Data Documentation
MusicTimeObjects MusicTimerAutoObject::m_timeObjects protected
Definition at line 75 of file musictimerautoobject.h.
Referenced by MusicTimerAutoObject(), runTimerAutoConfig(), and timeout().
QTimer MusicTimerAutoObject::m_timer protected
Definition at line 74 of file musictimerautoobject.h.
Referenced by MusicTimerAutoObject(), runTimerAutoConfig(), and ~MusicTimerAutoObject().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musictimerautoobject.h
TTKModule/TTKCore/musicToolsSetsKits/musictimerautoobject.cpp