TTKMusicplayer: PinyinResource Class Reference
PinyinResource Class Reference
The class of the pinyin resource.
#include <pinyinresource.h>
Static Public Member Functions
static QMap< QString, QString > getPinyinResource ()
static QMap< QString, QString > getMutilPinyinResource ()
static QMap< QString, QString > getChineseResource ()
Static Private Member Functions
static QMap< QString, QString > getResource (const QString &resourceName)
Detailed Description
The class of the pinyin resource.
Author
jiangXiaoBai 24999.nosp@m.7190.nosp@m.6@qq..nosp@m.com
Definition at line 30 of file pinyinresource.h.
Member Function Documentation
QMap< QString, QString > PinyinResource::getChineseResource () static
Get chinese resource.
Definition at line 16 of file pinyinresource.cpp.
References getResource().
Referenced by ChineseHelperPrivate::ChineseHelperPrivate().
QMap< QString, QString > PinyinResource::getMutilPinyinResource () static
Get mutil pinyin resource.
Definition at line 11 of file pinyinresource.cpp.
References getResource().
Referenced by PinyinHelperPrivate::PinyinHelperPrivate().
QMap< QString, QString > PinyinResource::getPinyinResource () static
Definition at line 6 of file pinyinresource.cpp.
References getResource().
Referenced by PinyinHelperPrivate::PinyinHelperPrivate().
QMap< QString, QString > PinyinResource::getResource (const QString & resourceName) static private
Get resource.
Definition at line 21 of file pinyinresource.cpp.
Referenced by getChineseResource(), getMutilPinyinResource(), and getPinyinResource().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qhz2py/pinyinresource.h
TTKThirdParty/TTKExtras/qhz2py/pinyinresource.cpp