TTKMusicplayer: QSyncUtils Class Reference
QSyncUtils Class Reference
The class of the sync cloud utils.
#include <qsyncutils.h>
Static Public Member Functions
static QString authorizationCode (const QString &key, const QString &method, const TTKStringMap &headers, const QString &resource)
static QString createSignForNormalAuth (const QString &method, const QString &access, const QString &secret, const TTKStringMap &headers, const QString &resource)
static QString GMT ()
static QString makeDataBucketUrl ()
Detailed Description
The class of the sync cloud utils.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file qsyncutils.h.
Member Function Documentation
QString QSyncUtils::authorizationCode (const QString & key, const QString & method, const TTKStringMap & headers, const QString & resource) static
Get authorization code.
Definition at line 58 of file qsyncutils.cpp.
References formatHeader(), hmacSha1(), and self_define_header_prefix.
Referenced by createSignForNormalAuth(), and QSyncDownloadData::downloadUrl().
QString QSyncUtils::createSignForNormalAuth (const QString & method, const QString & access, const QString & secret, const TTKStringMap & headers, const QString & resource) static
Create sign for normal auth.
Definition at line 85 of file qsyncutils.cpp.
References authorizationCode().
Referenced by QSyncDataInterfacePrivate::insertAuthorization().
QString QSyncUtils::GMT () static
Get GMT.
Definition at line 91 of file qsyncutils.cpp.
References local.
Referenced by QSyncDeleteData::deleteDataOperator(), QSyncDownloadData::downloadDataOperator(), QSyncListData::listDataOperator(), and QSyncUploadData::uploadDataOperator().
QString QSyncUtils::makeDataBucketUrl () static
Make data bucket url.
Definition at line 97 of file qsyncutils.cpp.
References DATA_BUCKET, and QSyncConfig::HOST.
Referenced by MusicScreenSaverWidget::initialize(), MusicCloudManagerTableWidget::queryCloudKey(), MusicIdentifySongsRequest::queryIdentifyKey(), and MusicSourceUpdateRequest::startToDownload().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qsync/qsyncutils.h
TTKThirdParty/TTKExtras/qsync/qsyncutils.cpp