TTKMusicPlayer: MusicDownloadStatusModule Class Reference
MusicDownloadStatusModule Class Reference
The class of the show download state object.
#include <musicdownloadstatusmodule.h>
Public Slots
void currentMetaDataDownload ()
void showDownLoadInfoFinished (const QString &bytes)
void networkConnectionStateChanged (bool state)
Public Member Functions
MusicDownloadStatusModule (QObject *parent=nullptr)
void checkMetaDataValid (bool mode)
Private Member Functions
bool checkLrcValid () const
bool checkArtistCoverValid () const
bool checkArtistBackgroundValid () const
Private Attributes
bool m_previousState
MusicApplication * m_parent
Detailed Description
The class of the show download state object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicdownloadstatusmodule.h.
Constructor & Destructor Documentation
MusicDownloadStatusModule::MusicDownloadStatusModule (QObject * parent = nullptr) explicit
Object constructor.
Definition at line 10 of file musicdownloadstatusmodule.cpp.
References G_CONNECTION_PTR.
Member Function Documentation
bool MusicDownloadStatusModule::checkArtistBackgroundValid () const private
Check the current artist background meta data valid.
Definition at line 132 of file musicdownloadstatusmodule.cpp.
References BACKGROUND_DIR_FULL, MusicApplication::currentFileName(), TTK::generateSongArtist(), m_parent, and SKN_FILE.
Referenced by checkMetaDataValid(), and currentMetaDataDownload().
bool MusicDownloadStatusModule::checkArtistCoverValid () const private
Check the current artist cover meta data valid.
Definition at line 126 of file musicdownloadstatusmodule.cpp.
References ART_DIR_FULL, MusicApplication::currentFileName(), TTK::generateSongArtist(), m_parent, and SKN_FILE.
Referenced by checkMetaDataValid(), and currentMetaDataDownload().
bool MusicDownloadStatusModule::checkLrcValid () const private
Check the current lrc meta data valid.
Definition at line 120 of file musicdownloadstatusmodule.cpp.
References MusicApplication::currentFileName(), LRC_FILE, TTK::String::lrcDirPrefix(), and m_parent.
Referenced by checkMetaDataValid(), and currentMetaDataDownload().
void MusicDownloadStatusModule::checkMetaDataValid (bool mode)
Check the current song meta data valid.
Check there is no opening lyrics display mode
Definition at line 19 of file musicdownloadstatusmodule.cpp.
References checkArtistBackgroundValid(), checkArtistCoverValid(), checkLrcValid(), MusicApplication::checkMusicListCurrentIndex(), MusicApplication::currentFileName(), currentMetaDataDownload(), G_DOWNLOAD_QUERY_PTR, G_NETWORK_PTR, m_parent, MusicAbstractQueryRequest::Meta, MusicAbstractQueryRequest::Music, TTKAbstractNetwork::setHeader(), MusicAbstractQueryRequest::setQueryMode(), MusicAbstractQueryRequest::setQueryType(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicRightAreaWidget::checkMetaDataValid().
void MusicDownloadStatusModule::currentMetaDataDownload () slot
Download current music meta data from net.
download lrc
download art picture
download art background picture
Definition at line 45 of file musicdownloadstatusmodule.cpp.
References ART_DIR_FULL, checkArtistBackgroundValid(), checkArtistCoverValid(), checkLrcValid(), G_DOWNLOAD_QUERY_PTR, G_NETWORK_PTR, TTK::generateSongArtist(), TTK::generateSongTitle(), TTKAbstractNetwork::header(), MusicAbstractQueryRequest::items(), LRC_FILE, TTK::String::lrcDirPrefix(), TTK::MusicSongInformation::m_artistName, TTK::MusicSongInformation::m_coverUrl, TTK::MusicSongInformation::m_lrcUrl, qAsConst, MusicAbstractQueryRequest::queryValue(), showDownLoadInfoFinished(), SKN_FILE, TTK::String::split(), and TTKObjectCast.
Referenced by checkMetaDataValid().
void MusicDownloadStatusModule::networkConnectionStateChanged (bool state) slot
Show current net connect state changed by net request.
Definition at line 108 of file musicdownloadstatusmodule.cpp.
References G_NETWORK_PTR, MusicBottomAreaWidget::instance(), m_previousState, and MusicBottomAreaWidget::showMessage().
void MusicDownloadStatusModule::showDownLoadInfoFinished (const QString & bytes) slot
Show download state string type.
lyrics download finished immediately loaded to display
Definition at line 95 of file musicdownloadstatusmodule.cpp.
References DOWNLOAD_KEY_COVER, DOWNLOAD_KEY_LRC, MusicApplication::loadCurrentSongLrc(), m_parent, and MusicApplication::updateCurrentArtist().
Referenced by currentMetaDataDownload().
Member Data Documentation
MusicApplication* MusicDownloadStatusModule::m_parent private
Definition at line 73 of file musicdownloadstatusmodule.h.
Referenced by checkArtistBackgroundValid(), checkArtistCoverValid(), checkLrcValid(), checkMetaDataValid(), and showDownLoadInfoFinished().
bool MusicDownloadStatusModule::m_previousState private
Definition at line 72 of file musicdownloadstatusmodule.h.
Referenced by networkConnectionStateChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicdownloadstatusmodule.h
TTKModule/TTKWidget/musicWidgetKits/musicdownloadstatusmodule.cpp