TTKMusicPlayer: MusicItemQueryTableWidget Class Reference
MusicItemQueryTableWidget Class Reference
The class of the query item table widget.
#include <musicitemquerytablewidget.h>
Public Slots
virtual void itemCellEntered (int row, int column) overridefinal
virtual void itemCellClicked (int row, int column) override
virtual void itemDoubleClicked (int row, int column) override
virtual void removeItems () overridefinal
virtual void createSearchedItem (const MusicResultInfoItem &songItem) override
void createFinishedItem ()
void menuActionChanged (QAction *action)
Public Slots inherited from MusicQueryTableWidget
virtual void itemDoubleClicked (int row, int column)=0
virtual void createSearchedItem (const MusicResultInfoItem &songItem)=0
Public Slots inherited from MusicFillItemTableWidget
virtual void itemCellClicked (int row, int column) override
void checkedItemsState (bool check)
void checkedItemsStatus (bool check)
Public Slots inherited from MusicAbstractTableWidget
virtual void itemCellEntered (int row, int column)
virtual void itemCellClicked (int row, int column)
virtual void removeItems ()
Public Member Functions
MusicItemQueryTableWidget (QWidget *parent=nullptr)
~MusicItemQueryTableWidget ()
virtual void setQueryInput (MusicAbstractQueryRequest *query) override
virtual void startSearchQuery (const QString &text) overridefinal
virtual void musicDownloadLocal (int row) override
void downloadDataFrom (bool play)
void downloadBatchData (bool music)
void resizeSection ()
Public Member Functions inherited from MusicQueryTableWidget
MusicQueryTableWidget (QWidget *parent=nullptr)
~MusicQueryTableWidget ()
MusicAbstractQueryRequest * queryInput () const
Public Member Functions inherited from MusicFillItemTableWidget
MusicFillItemTableWidget (QWidget *parent=nullptr)
~MusicFillItemTableWidget ()
TTKIntList checkedIndexList () const
Public Member Functions inherited from MusicAbstractTableWidget
MusicAbstractTableWidget (QWidget *parent=nullptr)
~MusicAbstractTableWidget ()
TTKIntList multiSelectedIndexList () const
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
virtual void contextMenuEvent (QContextMenuEvent *event) override
void addSearchMusicToPlaylist (int row, bool play)
bool downloadDataFrom (const MusicObject::MusicSongInformation &info, bool play)
Private Attributes
TTKLabelItemDelegate * m_labelDelegate
Additional Inherited Members
Signals inherited from MusicQueryTableWidget
void songBufferToPlaylist (const MusicResultDataItem &songItem)
void restartSearchQuery (const QString &name)
Protected Member Functions inherited from MusicAbstractTableWidget
void setRowColor (int row, const QColor &color) const
Protected Attributes inherited from MusicQueryTableWidget
MusicAbstractQueryRequest * m_networkRequest
Protected Attributes inherited from MusicFillItemTableWidget
TTKCheckBoxItemDelegate * m_checkBoxDelegate
Protected Attributes inherited from MusicAbstractTableWidget
int m_previousColorRow
int m_previousClickRow
QColor m_backgroundColor
Detailed Description
The class of the query item table widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musicitemquerytablewidget.h.
Constructor & Destructor Documentation
MusicItemQueryTableWidget::MusicItemQueryTableWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicitemquerytablewidget.cpp.
References G_CONNECTION_PTR, m_labelDelegate, MusicUIObject::MQSSBackgroundStyle13, and TTKAbstractItemDelegate::setStyleSheet().
MusicItemQueryTableWidget::~MusicItemQueryTableWidget ()
Definition at line 34 of file musicitemquerytablewidget.cpp.
References G_CONNECTION_PTR, m_labelDelegate, and removeItems().
Member Function Documentation
void MusicItemQueryTableWidget::addSearchMusicToPlaylist (int row, bool play) private
Add search music to play list by index.
Definition at line 307 of file musicitemquerytablewidget.cpp.
References downloadDataFrom(), MusicQueryTableWidget::m_networkRequest, MusicToastLabel::popup(), and MusicAbstractQueryRequest::songInfoList().
Referenced by itemCellClicked(), itemDoubleClicked(), and menuActionChanged().
void MusicItemQueryTableWidget::contextMenuEvent (QContextMenuEvent * event) override private virtual
Reimplemented in MusicWebMVRadioInfoTableWidget.
Definition at line 172 of file musicitemquerytablewidget.cpp.
References MusicObject::MusicSongInformation::m_albumName, MusicQueryTableWidget::m_networkRequest, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, menuActionChanged(), MusicUIObject::MQSSMenuStyle02, and MusicAbstractQueryRequest::songInfoList().
void MusicItemQueryTableWidget::createFinishedItem () slot
Create the search finished item.
Definition at line 287 of file musicitemquerytablewidget.cpp.
References m_labelDelegate, and TTK_DISPLAY_ROLE.
Referenced by setQueryInput().
void MusicItemQueryTableWidget::createSearchedItem (const MusicResultInfoItem & songItem) override virtual slot
Create searched items.
Definition at line 238 of file musicitemquerytablewidget.cpp.
References MusicUtils::Widget::elidedText(), MusicResultInfoItem::m_albumName, MusicResultInfoItem::m_duration, MusicResultInfoItem::m_singerName, MusicResultInfoItem::m_songName, MusicResultInfoItem::m_type, MusicUIObject::MQSSColor02, QtItemSetTextAlignment, and TTK_CHECKED_ROLE.
Referenced by MusicRecommendQueryTableWidget::createSearchedItem(), and MusicSimilarQueryTableWidget::createSearchedItem().
void MusicItemQueryTableWidget::downloadBatchData (bool music)
Download batch data from net.
Definition at line 101 of file musicitemquerytablewidget.cpp.
References MusicFillItemTableWidget::checkedIndexList(), GENERATE_SINGLE_WIDGET_PARENT, MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::Movie, MusicAbstractQueryRequest::Music, MusicToastLabel::popup(), MusicDownloadBatchWidget::setSongName(), and MusicAbstractQueryRequest::songInfoList().
Referenced by MusicAbstractItemQueryWidget::downloadButtonClicked(), and MusicWebMVRadioInfoWidget::downloadMVsButtonClicked().
void MusicItemQueryTableWidget::downloadDataFrom (bool play)
Download data from net and just play or not.
Definition at line 82 of file musicitemquerytablewidget.cpp.
References MusicFillItemTableWidget::checkedIndexList(), MusicQueryTableWidget::m_networkRequest, MusicToastLabel::popup(), and MusicAbstractQueryRequest::songInfoList().
Referenced by MusicAbstractItemQueryWidget::addButtonClicked(), addSearchMusicToPlaylist(), MusicAbstractItemQueryWidget::playAllButtonClicked(), and MusicAbstractItemQueryWidget::playButtonClicked().
bool MusicItemQueryTableWidget::downloadDataFrom (const MusicObject::MusicSongInformation & info, bool play) private
Download data from net and just play or not.
Definition at line 324 of file musicitemquerytablewidget.cpp.
References G_NETWORK_PTR, MusicResultDataItem::m_description, MusicObject::MusicSongInformation::m_duration, MusicObject::MusicSongProperty::m_format, MusicResultDataItem::m_id, MusicResultDataItem::m_name, MusicQueryTableWidget::m_networkRequest, MusicResultDataItem::m_nickName, MusicResultDataItem::m_playCount, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongProperty::m_size, MusicObject::MusicSongInformation::m_songId, MusicObject::MusicSongInformation::m_songName, MusicObject::MusicSongInformation::m_songProps, MusicResultDataItem::m_tags, MusicResultDataItem::m_updateTime, MusicObject::MusicSongProperty::m_url, MUSIC_PLAY_LATER, MUSIC_PLAY_NOW, MusicAbstractQueryRequest::queryServer(), and MusicQueryTableWidget::songBufferToPlaylist().
void MusicItemQueryTableWidget::itemCellClicked (int row, int column) override virtual slot
Table widget item cell click.
Definition at line 215 of file musicitemquerytablewidget.cpp.
References addSearchMusicToPlaylist(), MusicFillItemTableWidget::itemCellClicked(), and musicDownloadLocal().
void MusicItemQueryTableWidget::itemCellEntered (int row, int column) final override virtual slot
Table widget item cell enter.
Definition at line 202 of file musicitemquerytablewidget.cpp.
References MusicAbstractTableWidget::itemCellEntered().
void MusicItemQueryTableWidget::itemDoubleClicked (int row, int column) override virtual slot
Table widget item cell double clicked.
Definition at line 72 of file musicitemquerytablewidget.cpp.
References addSearchMusicToPlaylist().
void MusicItemQueryTableWidget::menuActionChanged (QAction * action) slot
Menu action type changed.
Definition at line 143 of file musicitemquerytablewidget.cpp.
References addSearchMusicToPlaylist(), MusicRightAreaWidget::instance(), MusicObject::MusicSongInformation::m_albumId, MusicObject::MusicSongInformation::m_albumName, MusicObject::MusicSongInformation::m_artistId, MusicQueryTableWidget::m_networkRequest, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_songName, MusicRightAreaWidget::musicAlbumFound(), MusicRightAreaWidget::musicArtistFound(), musicDownloadLocal(), MusicRightAreaWidget::musicSongSearchedFound(), and MusicAbstractQueryRequest::songInfoList().
Referenced by contextMenuEvent().
void MusicItemQueryTableWidget::musicDownloadLocal (int row) override virtual
Data download to local file.
Implements MusicQueryTableWidget.
Reimplemented in MusicWebMVRadioInfoTableWidget.
Definition at line 59 of file musicitemquerytablewidget.cpp.
References MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::Music, MusicDownloadWidget::setSongName(), MusicAbstractMoveWidget::show(), and MusicAbstractQueryRequest::songInfoList().
Referenced by itemCellClicked(), and menuActionChanged().
void MusicItemQueryTableWidget::removeItems () final override virtual slot
Remove all items.
Definition at line 227 of file musicitemquerytablewidget.cpp.
References MusicAbstractTableWidget::removeItems().
Referenced by startSearchQuery(), MusicAlbumQueryTableWidget::~MusicAlbumQueryTableWidget(), MusicArtistQueryTableWidget::~MusicArtistQueryTableWidget(), ~MusicItemQueryTableWidget(), MusicPlaylistQueryTableWidget::~MusicPlaylistQueryTableWidget(), MusicRecommendQueryTableWidget::~MusicRecommendQueryTableWidget(), MusicSimilarQueryTableWidget::~MusicSimilarQueryTableWidget(), MusicToplistQueryTableWidget::~MusicToplistQueryTableWidget(), MusicWebDJRadioInfoTableWidget::~MusicWebDJRadioInfoTableWidget(), and MusicWebMVRadioInfoTableWidget::~MusicWebMVRadioInfoTableWidget().
void MusicItemQueryTableWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 166 of file musicitemquerytablewidget.cpp.
References resizeSection().
void MusicItemQueryTableWidget::resizeSection ()
Resize section bound by resize called.
Definition at line 126 of file musicitemquerytablewidget.cpp.
References MusicUtils::Widget::elidedText(), G_SETTING_PTR, MusicSettingManager::WidgetSize, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), MusicPlaylistQueryInfoWidget::resizeWidget(), MusicWebDJRadioInfoWidget::resizeWidget(), MusicAlbumQueryWidget::resizeWidget(), MusicToplistQueryWidget::resizeWidget(), MusicRecommendQueryWidget::resizeWidget(), MusicSimilarQueryWidget::resizeWidget(), MusicWebMVRadioInfoWidget::resizeWidget(), and MusicArtistQueryWidget::resizeWidget().
void MusicItemQueryTableWidget::setQueryInput (MusicAbstractQueryRequest * query) override virtual
Set network query input.
Reimplemented from MusicQueryTableWidget.
Reimplemented in MusicArtistQueryTableWidget, MusicToplistQueryTableWidget, MusicRecommendQueryTableWidget, MusicSimilarQueryTableWidget, MusicWebDJRadioInfoTableWidget, MusicWebMVRadioInfoTableWidget, MusicAlbumQueryTableWidget, and MusicPlaylistQueryTableWidget.
Definition at line 41 of file musicitemquerytablewidget.cpp.
References createFinishedItem(), and MusicQueryTableWidget::setQueryInput().
Referenced by MusicToplistQueryWidget::MusicToplistQueryWidget(), MusicWebDJRadioInfoWidget::MusicWebDJRadioInfoWidget(), MusicWebMVRadioInfoWidget::MusicWebMVRadioInfoWidget(), MusicWebDJRadioInfoTableWidget::setQueryInput(), MusicAlbumQueryTableWidget::setQueryInput(), MusicPlaylistQueryTableWidget::setQueryInput(), MusicWebMVRadioInfoTableWidget::setQueryInput(), MusicRecommendQueryTableWidget::setQueryInput(), MusicSimilarQueryTableWidget::setQueryInput(), MusicToplistQueryTableWidget::setQueryInput(), MusicPlaylistQueryInfoWidget::setQueryInput(), MusicArtistQueryTableWidget::setQueryInput(), MusicRecommendQueryWidget::setSongName(), MusicSimilarQueryWidget::setSongName(), MusicAlbumQueryWidget::setSongNameByID(), and MusicArtistQueryWidget::setSongNameByID().
void MusicItemQueryTableWidget::startSearchQuery (const QString & text) final override virtual
Start search query by text.
Implements MusicQueryTableWidget.
Definition at line 47 of file musicitemquerytablewidget.cpp.
References G_NETWORK_PTR, MusicQueryTableWidget::m_networkRequest, MusicAbstractQueryRequest::Music, removeItems(), MusicAbstractQueryRequest::setQueryAllRecords(), and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicPlaylistQueryInfoWidget::setResultDataItem(), MusicWebDJRadioInfoWidget::setSongName(), MusicRecommendQueryWidget::setSongName(), MusicSimilarQueryWidget::setSongName(), MusicWebMVRadioInfoWidget::setSongName(), MusicAlbumQueryWidget::setSongNameByID(), and MusicArtistQueryWidget::setSongNameByID().
Member Data Documentation
TTKLabelItemDelegate* MusicItemQueryTableWidget::m_labelDelegate private
Definition at line 109 of file musicitemquerytablewidget.h.
Referenced by createFinishedItem(), MusicItemQueryTableWidget(), and ~MusicItemQueryTableWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicitemquerytablewidget.h
TTKModule/TTKWidget/musicCoreKits/musicitemquerytablewidget.cpp