TTKMusicPlayer: MusicSongSearchRecordConfigManager Class Reference
MusicSongSearchRecordConfigManager Class Reference
The class of the search history Config.
#include <musicsongsearchrecordconfigmanager.h>
Public Member Functions
MusicSongSearchRecordConfigManager ()
virtual bool readBuffer (MusicSearchRecordList &items) overridefinal
virtual bool writeBuffer (const MusicSearchRecordList &items) overridefinal
Public Member Functions inherited from TTKAbstractXml
TTKAbstractXml ()
virtual ~TTKAbstractXml ()
bool load (const QString &name)
void save () const
bool reset ()
bool fromFile (const QString &name)
bool fromString (const QString &data)
bool fromByteArray (const QByteArray &data)
QString toString () const
QByteArray toByteArray () const
void createProcessingInstruction () const
QString readAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QString readTextByTagName (const QString &tagName) const
TTKXmlNode readNodeByTagName (const QString &tagName) const
QStringList readMultiAttributeByTagName (const QString &tagName, const QString &attrName="value") const
QStringList readMultiTextByTagName (const QString &tagName) const
TTKXmlNodeList readMultiNodeByTagName (const QString &tagName) const
QDomElement createRoot (const QString &node) const
QDomElement createRoot (const QString &node, const TTKXmlAttr &attr) const
QDomElement createRoot (const QString &node, const TTKXmlAttrList &attrs) const
QDomElement writeDomElement (QDomElement &element, const QString &node) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const QString &text) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlNode &attr) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttr &attr) const
QDomElement writeDomElement (QDomElement &element, const QString &node, const TTKXmlAttr &attr, const QString &text) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlNode &attrs) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttrList &attrs) const
QDomElement writeDomMultiElement (QDomElement &element, const QString &node, const TTKXmlAttrList &attrs, const QString &text) const
void writeAttribute (QDomElement &element, const TTKXmlAttr &attr) const
void writeAttribute (QDomElement &element, const TTKXmlAttrList &attr) const
Public Member Functions inherited from TTKAbstractReadWriteInterface< MusicSearchRecordList >
virtual ~TTKAbstractReadWriteInterface ()=default
Public Member Functions inherited from TTKAbstractReadInterface< MusicSearchRecordList >
virtual ~TTKAbstractReadInterface ()=default
Public Member Functions inherited from TTKAbstractWriteInterface< MusicSearchRecordList >
virtual ~TTKAbstractWriteInterface ()=default
Additional Inherited Members
Protected Attributes inherited from TTKAbstractXml
QFile * m_file
QDomDocument * m_document
Detailed Description
The class of the search history Config.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 38 of file musicsongsearchrecordconfigmanager.h.
Constructor & Destructor Documentation
MusicSongSearchRecordConfigManager::MusicSongSearchRecordConfigManager ()
Object constructor.
Definition at line 3 of file musicsongsearchrecordconfigmanager.cpp.
Member Function Documentation
bool MusicSongSearchRecordConfigManager::readBuffer (MusicSearchRecordList & items) final override virtual
Read datas from buffer.
Implements TTKAbstractReadInterface< MusicSearchRecordList >.
Definition at line 9 of file musicsongsearchrecordconfigmanager.cpp.
References TTKAbstractXml::m_document, MusicSearchRecord::m_name, and MusicSearchRecord::m_timestamp.
Referenced by MusicSongSearchPopWidget::initialize(), and MusicSongSearchTableWidget::startToSearchByText().
bool MusicSongSearchRecordConfigManager::writeBuffer (const MusicSearchRecordList & items) final override virtual
Write datas into buffer.
Implements TTKAbstractWriteInterface< MusicSearchRecordList >.
Definition at line 25 of file musicsongsearchrecordconfigmanager.cpp.
References TTKAbstractXml::createProcessingInstruction(), TTKAbstractXml::createRoot(), qAsConst, TTKAbstractXml::save(), TTK_APP_NAME, and TTKAbstractXml::writeDomElement().
Referenced by MusicSongSearchPopWidget::clearButtonClicked(), and MusicSongSearchTableWidget::startToSearchByText().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicSearchKits/musicsongsearchrecordconfigmanager.h
TTKModule/TTKCore/musicSearchKits/musicsongsearchrecordconfigmanager.cpp