TTKMusicplayer: MusicDownLoadQueryBDPlaylistThread Class Reference
MusicDownLoadQueryBDPlaylistThread Class Reference
The class to baidu query playlist download data from net.
#include <musicdownloadquerybdplaylistthread.h>
Public Slots
virtual void downLoadFinished () override
void getDetailsFinished ()
Public Slots inherited from MusicNetworkAbstract
virtual void downLoadFinished ()=0
virtual void replyError (QNetworkReply::NetworkError error)
virtual void sslErrors (QNetworkReply *reply, const QList< QSslError > &errors)
void sslErrorsString (QNetworkReply *reply, const QList< QSslError > &errors)
Signals
void createPlaylistItems (const MusicPlaylistItem &item)
Signals inherited from MusicDownLoadQueryThreadAbstract
void clearAllItems ()
void createSearchedItems (const MusicSearchedItem &songItem)
Signals inherited from MusicNetworkAbstract
void downLoadDataChanged (const QString &data)
Public Member Functions
MusicDownLoadQueryBDPlaylistThread (QObject *parent=0)
QJson import.
virtual void startToSearch (QueryType type, const QString &playlist) override
virtual void startToPage (int offset) override
void startToSearch (const QString &playlist)
Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
MusicDownLoadQueryThreadAbstract (QObject *parent=0)
virtual ~MusicDownLoadQueryThreadAbstract ()
void setSearchQuality (const QString &qual)
QString getSearchQuality () const
void setQueryAllRecords (bool state)
bool getQueryAllRecords () const
void setQuerySimplify (bool state)
bool getQuerySimplify () const
void setQueryExtraMovie (bool state)
QueryType getQueryType () const
QString getQueryServer () const
QString getSearchedText () const
const MusicObject::MusicSongInformations & getMusicSongInfos () const
Public Member Functions inherited from MusicDownLoadPagingThread
MusicDownLoadPagingThread (QObject *parent=0)
virtual ~MusicDownLoadPagingThread ()
virtual void deleteAll () override
QVariantMap getRawData () const
int getPageSize () const
int getPageTotal () const
Public Member Functions inherited from MusicNetworkAbstract
MusicNetworkAbstract (QObject *parent=0)
virtual ~MusicNetworkAbstract ()
Static Public Member Functions
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadQueryThreadAbstract
static QString getClassName ()
Static Public Member Functions inherited from MusicDownLoadPagingThread
static QString getClassName ()
Static Public Member Functions inherited from MusicNetworkAbstract
static QString getClassName ()
Additional Inherited Members
Public Types inherited from MusicDownLoadQueryThreadAbstract
enum QueryType { MusicQuery, MovieQuery, LrcQuery, OtherQuery }
Public Types inherited from MusicNetworkAbstract
enum StateCode { Init = 0xFFFFF00, Success = 0, Error = -1, UnKnow = 2 }
typedef enum MusicNetworkAbstract::StateCode StateCode
Protected Member Functions inherited from MusicDownLoadQueryThreadAbstract
QString mapQueryServerString () const
Protected Attributes inherited from MusicDownLoadQueryThreadAbstract
MusicObject::MusicSongInformations m_musicSongInfos
QString m_searchText
QString m_searchQuality
QString m_queryServer
QueryType m_currentType
bool m_queryAllRecords
bool m_querySimplify
bool m_queryExtraMovie
Protected Attributes inherited from MusicDownLoadPagingThread
QVariantMap m_rawData
int m_pageSize
int m_pageTotal
Protected Attributes inherited from MusicNetworkAbstract
StateCode m_stateCode
QNetworkReply * m_reply
QNetworkAccessManager * m_manager
Private Member Functions inherited from MusicDownLoadBDInterface
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &bit)
QJson import.
void readFromMusicSongAttribute (MusicObject::MusicSongInformation *info, const QString &format, const QString &quality, bool all)
void readFromMusicLLAttribute (MusicObject::MusicSongInformation *info)
void readFromMusicPayAttribute (MusicObject::MusicSongInformation *info)
QString findTimeStringByAttrs (const MusicObject::MusicSongAttributes &attrs)
Detailed Description
The class to baidu query playlist download data from net.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 18 of file musicdownloadquerybdplaylistthread.h.
Constructor & Destructor Documentation
MusicDownLoadQueryBDPlaylistThread::MusicDownLoadQueryBDPlaylistThread (QObject * parent = 0) explicit
QJson import.
Object contsructor.
Definition at line 6 of file musicdownloadquerybdplaylistthread.cpp.
References MusicDownLoadPagingThread::m_pageSize, and MusicDownLoadQueryThreadAbstract::m_queryServer.
Member Function Documentation
void MusicDownLoadQueryBDPlaylistThread::createPlaylistItems (const MusicPlaylistItem & item) signal
Create the current playlist item.
Referenced by downLoadFinished().
void MusicDownLoadQueryBDPlaylistThread::downLoadFinished () override virtual slot
Download data from net finished.
Clear origin items
Empty the last search to songsInfo
Definition at line 80 of file musicdownloadquerybdplaylistthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), createPlaylistItems(), MusicDownLoadPagingThread::deleteAll(), getClassName(), MusicPlaylistItem::m_coverUrl, MusicPlaylistItem::m_description, MusicPlaylistItem::m_id, M_LOGGER_INFO, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicPlaylistItem::m_name, MusicPlaylistItem::m_nickname, MusicDownLoadPagingThread::m_pageTotal, MusicPlaylistItem::m_playCount, MusicNetworkAbstract::m_reply, MusicPlaylistItem::m_tags, MusicPlaylistItem::m_updateTime, and QJson::Parser::parse().
Referenced by startToPage().
QString MusicDownLoadQueryBDPlaylistThread::getClassName () static
Get class object name.
Definition at line 13 of file musicdownloadquerybdplaylistthread.cpp.
Referenced by downLoadFinished(), getDetailsFinished(), startToPage(), and startToSearch().
void MusicDownLoadQueryBDPlaylistThread::getDetailsFinished () slot
Download details data from net finished.
Clear origin items
Empty the last search to songsInfo
Definition at line 135 of file musicdownloadquerybdplaylistthread.cpp.
References MusicDownLoadQueryThreadAbstract::clearAllItems(), MusicDownLoadQueryThreadAbstract::createSearchedItems(), MusicNetworkAbstract::downLoadDataChanged(), MusicDownLoadBDInterface::findTimeStringByAttrs(), getClassName(), MusicNetworkAbstract::Init, MusicObject::MusicSongInformation::m_albumId, MusicObject::MusicSongInformation::m_artistId, MusicSearchedItem::m_artistname, M_LOGGER_INFO, MusicObject::MusicSongInformation::m_lrcUrl, MusicNetworkAbstract::m_manager, MusicDownLoadQueryThreadAbstract::m_musicSongInfos, MusicDownLoadQueryThreadAbstract::m_queryAllRecords, MusicDownLoadQueryThreadAbstract::m_searchQuality, MusicObject::MusicSongInformation::m_singerName, MusicObject::MusicSongInformation::m_smallPicUrl, MusicObject::MusicSongInformation::m_songAttrs, MusicObject::MusicSongInformation::m_songId, MusicSearchedItem::m_songname, MusicObject::MusicSongInformation::m_songName, MusicNetworkAbstract::m_stateCode, MusicSearchedItem::m_time, MusicObject::MusicSongInformation::m_timeLength, MusicSearchedItem::m_type, MusicDownLoadQueryThreadAbstract::mapQueryServerString(), MObject_cast, QJson::Parser::parse(), and MusicDownLoadBDInterface::readFromMusicSongAttribute().
Referenced by startToSearch().
void MusicDownLoadQueryBDPlaylistThread::startToPage (int offset) override virtual
Start to search data from name and type bt paging.
Reimplemented from MusicDownLoadPagingThread.
Definition at line 31 of file musicdownloadquerybdplaylistthread.cpp.
References BD_PLAYLIST_URL, MusicDownLoadPagingThread::deleteAll(), downLoadFinished(), getClassName(), M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicDownLoadPagingThread::m_pageSize, MusicDownLoadPagingThread::m_pageTotal, MusicNetworkAbstract::m_reply, MusicDownLoadQueryThreadAbstract::m_searchText, MusicUtils::Algorithm::mdII(), and MusicNetworkAbstract::replyError().
Referenced by startToSearch().
void MusicDownLoadQueryBDPlaylistThread::startToSearch (QueryType type, const QString & playlist) override virtual
Start to Search data from name and type.
Implements MusicDownLoadQueryThreadAbstract.
Definition at line 18 of file musicdownloadquerybdplaylistthread.cpp.
References MusicDownLoadQueryThreadAbstract::m_searchText, MusicDownLoadQueryThreadAbstract::MusicQuery, and startToPage().
void MusicDownLoadQueryBDPlaylistThread::startToSearch (const QString & playlist)
Start to Search data.
Definition at line 57 of file musicdownloadquerybdplaylistthread.cpp.
References BD_PLAYLIST_ATTR_URL, getClassName(), getDetailsFinished(), M_LOGGER_INFO, MusicNetworkAbstract::m_manager, MusicUtils::Algorithm::mdII(), and MusicNetworkAbstract::replyError().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicNetworkKits/bd/musicdownloadquerybdplaylistthread.h
TTKModule/TTKCore/musicNetworkKits/bd/musicdownloadquerybdplaylistthread.cpp