TTKMusicPlayer: MusicQualityChoicePopWidget Class Reference
MusicQualityChoicePopWidget Class Reference
The class of the quality choice pop widget.
#include <musicqualitychoicepopwidget.h>
Public Slots
void itemCellClicked (int row)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Signals
void researchQueryByQuality (const QString &quality)
Public Member Functions
MusicQualityChoicePopWidget (QWidget *parent=nullptr)
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Private Member Functions
void initialize ()
Additional Inherited Members
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the quality choice pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 59 of file musicqualitychoicepopwidget.h.
Constructor & Destructor Documentation
MusicQualityChoicePopWidget::MusicQualityChoicePopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 128 of file musicqualitychoicepopwidget.cpp.
References initialize(), MusicUIObject::MQSSBtnQuality, and MusicUIObject::MQSSToolButtonStyle05.
Member Function Documentation
void MusicQualityChoicePopWidget::initialize () private
Create all widget in layout.
Definition at line 139 of file musicqualitychoicepopwidget.cpp.
References itemCellClicked(), MusicToolMenuWidget::m_containWidget, MusicToolMenuWidget::m_menu, MusicUIObject::MQSSMenuStyle04, and MusicToolMenuWidget::setTranslucentBackground().
Referenced by MusicQualityChoicePopWidget().
void MusicQualityChoicePopWidget::itemCellClicked (int row) slot
Current Table item clicked by index.
Definition at line 156 of file musicqualitychoicepopwidget.cpp.
References MusicObject::High, MusicRightAreaWidget::instance(), MusicObject::Lossless, MusicToolMenuWidget::m_menu, MusicRightAreaWidget::researchQueryByQuality(), MusicObject::Standard, and MusicObject::Super.
Referenced by initialize().
void MusicQualityChoicePopWidget::researchQueryByQuality (const QString & quality) signal
Research query by quality it changed.
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicqualitychoicepopwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicqualitychoicepopwidget.cpp