TTKMusicPlayer: MetaDataModel Class Reference
MetaDataModel Class Reference
The MetaDataModel is the base interface class of metadata access.
#include <metadatamodel.h>
Public Types
enum DialogHint { IsCoverEditable = 0x1, CompletePropertyList = 0x2, IsCueEditable = 0x4 }
Public Member Functions
MetaDataModel (bool readOnly, DialogHints hints=DialogHints())
virtual ~MetaDataModel ()
virtual QList< MetaDataItem > extraProperties () const
virtual QList< MetaDataItem > descriptions () const
virtual QList< TagModel * > tags () const
virtual QPixmap cover () const
virtual void setCover (const QPixmap &pix)
virtual void removeCover ()
virtual QString coverPath () const
virtual QString cue () const
virtual void setCue (const QString &content)
virtual void removeCue ()
virtual QString lyrics () const
bool isReadOnly () const
const DialogHints & dialogHints () const
Protected Member Functions
void setDialogHints (const DialogHints &hints)
void setReadOnly (bool readOnly)
Private Attributes
bool m_readOnly
DialogHints m_dialogHints
Detailed Description
The MetaDataModel is the base interface class of metadata access.
Author
Ilya Kotov forko.nosp@m.tov0.nosp@m.2@ya..nosp@m.ru
Definition at line 78 of file metadatamodel.h.
Member Enumeration Documentation
enum MetaDataModel::DialogHint
Details dialog settings.
Enumerator
IsCoverEditable
Enable cover editor.
CompletePropertyList
Show properties from extraProperties() only (ignore other sources)
IsCueEditable
Enable CUE editor.
Definition at line 84 of file metadatamodel.h.
Constructor & Destructor Documentation
MetaDataModel::MetaDataModel (bool readOnly, DialogHints hints = DialogHints()) explicit
Constructor.
Parameters
readOnly Open file in read-only mode (true - enabled, false - disable).
hints Details dialog settings.
virtual MetaDataModel::~MetaDataModel () virtual
Destructor.
Member Function Documentation
virtual QPixmap MetaDataModel::cover () const virtual
Returns cover pixmap. Subclass should reimplement this function. Default implementation returns empty pixmap.
Referenced by MusicSongMeta::readInformation().
virtual QString MetaDataModel::coverPath () const virtual
Returns path to cover pixmap.
virtual QString MetaDataModel::cue () const virtual
Returns CUE file or tag content if necessary. Default implementation returns empty string.
virtual QList<MetaDataItem> MetaDataModel::descriptions () const virtual
Returns a list of long descriptions. Default implemetation returns empty array.
Referenced by MusicSongMeta::readInformation().
const DialogHints& MetaDataModel::dialogHints () const
Returns details dialog hints.
virtual QList<MetaDataItem> MetaDataModel::extraProperties () const virtual
Returns extra properties of the media source (in addition to the Qmmp::TrackProperty values). Default implemetation returns empty array.
Referenced by MusicSongMeta::readInformation().
bool MetaDataModel::isReadOnly () const
Remove cue data.
virtual QString MetaDataModel::lyrics () const virtual
Returns song lyrics. Default returns empty string.
Referenced by MusicSongMeta::readInformation().
virtual void MetaDataModel::removeCover () virtual
Removes cover. Subclass should reimplement this function. Default implementation does nothing.
Referenced by MusicSongMeta::saveInformation().
virtual void MetaDataModel::removeCue () virtual
Removes CUE file or tag. Default implementation does nothing.
virtual void MetaDataModel::setCover (const QPixmap & pix) virtual
Sets cover.
Parameters
pix Cover pixmap. Subclass should reimplement this function. Default implementation does nothing.
Referenced by MusicSongMeta::saveInformation().
virtual void MetaDataModel::setCue (const QString & content) virtual
Updates CUE file or tag content. Default implementation doesn nothing.
void MetaDataModel::setDialogHints (const DialogHints & hints) protected
Changes details dialog hints to hints
void MetaDataModel::setReadOnly (bool readOnly) protected
Enables/Disables read only mode (true - enabled, false - disable).
Parameters
readOnly read only mode (true - enabled, false - disable).
virtual QList<TagModel*> MetaDataModel::tags () const virtual
Returns a list of available tags. Subclass should reimplement this function. Default implementation returns empty array.
Referenced by MusicSongMeta::saveInformation().
Member Data Documentation
DialogHints MetaDataModel::m_dialogHints private
Definition at line 174 of file metadatamodel.h.
bool MetaDataModel::m_readOnly private
Definition at line 173 of file metadatamodel.h.
The documentation for this class was generated from the following file:
TTKThirdParty/TTKqmmp/qmmp/metadatamodel.h