TTKMusicplayer: MusicNetworkTestThread Class Reference
MusicNetworkTestThread Class Reference
The class of thread to test input url network.
#include <musicnetworktestthread.h>
Public Slots
void start ()
virtual void run () override
Signals
void networkConnectionTestChanged (bool state)
Public Member Functions
MusicNetworkTestThread (QObject *parent=nullptr)
~MusicNetworkTestThread ()
void stopAndQuitThread ()
void setUrl (const QString &url)
Protected Attributes
QString m_currentUrl
bool m_run
Detailed Description
The class of thread to test input url network.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 10 of file musicnetworktestthread.h.
Constructor & Destructor Documentation
MusicNetworkTestThread::MusicNetworkTestThread (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 11 of file musicnetworktestthread.cpp.
References m_run, and MusicTime::timeSRand().
MusicNetworkTestThread::~MusicNetworkTestThread ()
Definition at line 18 of file musicnetworktestthread.cpp.
References stopAndQuitThread().
Member Function Documentation
void MusicNetworkTestThread::networkConnectionTestChanged (bool state) signal
Network connection test changed.
Referenced by run().
void MusicNetworkTestThread::run () override virtual slot
Thread run now.
Definition at line 44 of file musicnetworktestthread.cpp.
References m_currentUrl, m_run, MT_S2MS, MT_S2US, and networkConnectionTestChanged().
void MusicNetworkTestThread::setUrl (const QString & url)
Set current test url.
Definition at line 33 of file musicnetworktestthread.cpp.
References m_currentUrl.
Referenced by MusicNetworkConnectionItem::setUrl().
void MusicNetworkTestThread::start () slot
Strat thread now.
Definition at line 38 of file musicnetworktestthread.cpp.
References m_run.
Referenced by MusicNetworkConnectionItem::start().
void MusicNetworkTestThread::stopAndQuitThread ()
Stop and quit current thread.
Definition at line 23 of file musicnetworktestthread.cpp.
References m_run.
Referenced by MusicNetworkConnectionItem::stop(), MusicNetworkConnectionItem::~MusicNetworkConnectionItem(), and ~MusicNetworkTestThread().
Member Data Documentation
QString MusicNetworkTestThread::m_currentUrl protected
Definition at line 48 of file musicnetworktestthread.h.
Referenced by run(), and setUrl().
bool MusicNetworkTestThread::m_run protected
Definition at line 49 of file musicnetworktestthread.h.
Referenced by MusicNetworkTestThread(), run(), start(), and stopAndQuitThread().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicToolsSetsKits/musicnetworktestthread.h
TTKModule/TTKCore/musicToolsSetsKits/musicnetworktestthread.cpp