TTKMusicPlayer: MusicItemMoreRecommendQueryWidget Class Reference
MusicItemMoreRecommendQueryWidget Class Reference
The class of the item more recommend query widget.
#include <musicmainrecommendwidget.h>
Public Slots
void buttonClicked (int index)
void categoryChanged (int index)
void createResultItem (const MusicResultDataItem &item)
void currentItemClicked (const MusicResultDataItem &item)
Public Member Functions
MusicItemMoreRecommendQueryWidget (RecommendModule module, QWidget *parent=nullptr)
~MusicItemMoreRecommendQueryWidget ()
void resizeGeometry ()
Private Member Functions
void initialize ()
void removeItems (QLayout *layout)
Private Attributes
bool m_categoryChanged
RecommendModule m_module
QWidget * m_mainWidget
QGridLayout * m_gridLayout
QWidgetList m_resizeWidgets
TTKClickedGroup * m_areasGroup
MusicPageQueryWidget * m_pageQueryWidget
MusicAbstractQueryRequest * m_networkRequest
Detailed Description
The class of the item more recommend query widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 149 of file musicmainrecommendwidget.h.
Constructor & Destructor Documentation
MusicItemMoreRecommendQueryWidget::MusicItemMoreRecommendQueryWidget (RecommendModule module, QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 360 of file musicmainrecommendwidget.cpp.
References TTK::UI::BackgroundStyle01, TTK::Widget::generateVScrollAreaStyle(), initialize(), and m_mainWidget.
MusicItemMoreRecommendQueryWidget::~MusicItemMoreRecommendQueryWidget ()
Object destructor.
Definition at line 388 of file musicmainrecommendwidget.cpp.
References m_areasGroup, m_gridLayout, m_mainWidget, m_networkRequest, and m_pageQueryWidget.
Member Function Documentation
void MusicItemMoreRecommendQueryWidget::buttonClicked (int index) slot
Page widget button has changed.
Definition at line 417 of file musicmainrecommendwidget.cpp.
References MusicPageQueryWidget::currentIndex(), m_gridLayout, m_networkRequest, m_pageQueryWidget, MusicPageQueryWidget::page(), MusicPageQueryRequest::pageTotalSize(), removeItems(), and MusicPageQueryRequest::startToPage().
Referenced by createResultItem().
void MusicItemMoreRecommendQueryWidget::categoryChanged (int index) slot
Current category changed.
Definition at line 424 of file musicmainrecommendwidget.cpp.
References Album, Artist, key, m_categoryChanged, m_gridLayout, m_module, m_networkRequest, Playlist, PlaylistHQ, removeItems(), and MusicAbstractQueryRequest::startToSearch().
Referenced by initialize().
void MusicItemMoreRecommendQueryWidget::createResultItem (const MusicResultDataItem & item) slot
Create the current item info.
Definition at line 462 of file musicmainrecommendwidget.cpp.
References Artist, buttonClicked(), MusicPageQueryWidget::createPageWidget(), currentItemClicked(), MusicSquareQueryItemWidget::LINE_SPACING_SIZE, m_categoryChanged, m_gridLayout, m_mainWidget, m_module, m_networkRequest, m_pageQueryWidget, m_resizeWidgets, MusicPageQueryRequest::pageTotalSize(), QUERY_WIDGET_WIDTH, MusicPageQueryWidget::reset(), MusicSquareQueryItemWidget::setResultDataItem(), MusicSquareQueryItemWidget::setShowCount(), MusicSquareQueryItemWidget::setShowTime(), MusicSquareQueryItemWidget::setValueLabel(), and TTKObjectCast.
Referenced by initialize().
void MusicItemMoreRecommendQueryWidget::currentItemClicked (const MusicResultDataItem & item) slot
Current playlist item clicked.
Definition at line 493 of file musicmainrecommendwidget.cpp.
References Album, Artist, MusicRightAreaWidget::instance(), MusicResultDataItem::m_id, m_module, Playlist, PlaylistHQ, MusicRightAreaWidget::showAlbumFound(), MusicRightAreaWidget::showArtistFound(), and MusicRightAreaWidget::showPlaylistFound().
Referenced by createResultItem().
void MusicItemMoreRecommendQueryWidget::initialize () private
Init widget and parameter.
Definition at line 505 of file musicmainrecommendwidget.cpp.
References TTKClickedGroup::addWidget(), Album, Artist, TTK::UI::BackgroundStyle03, TTK::UI::BackgroundStyle13, categoryChanged(), TTK::UI::ColorStyle04, createResultItem(), TTK::UI::FontStyle01, TTK::UI::FontStyle03, TTK::UI::FontStyle06, G_DOWNLOAD_QUERY_PTR, m_areasGroup, m_gridLayout, m_mainWidget, m_module, m_networkRequest, Playlist, PlaylistHQ, and MusicAbstractQueryRequest::startToSearch().
Referenced by MusicItemMoreRecommendQueryWidget().
void MusicItemMoreRecommendQueryWidget::removeItems (QLayout * layout) private
Remove all items.
Definition at line 682 of file musicmainrecommendwidget.cpp.
References m_resizeWidgets.
Referenced by buttonClicked(), and categoryChanged().
void MusicItemMoreRecommendQueryWidget::resizeGeometry ()
Resize widget bound by resize called.
Definition at line 397 of file musicmainrecommendwidget.cpp.
References MusicSquareQueryItemWidget::LINE_SPACING_SIZE, m_gridLayout, m_resizeWidgets, qAsConst, and QUERY_WIDGET_WIDTH.
Referenced by MusicMainRecommendWidget::resizeGeometry().
Member Data Documentation
TTKClickedGroup* MusicItemMoreRecommendQueryWidget::m_areasGroup private
Definition at line 200 of file musicmainrecommendwidget.h.
Referenced by initialize(), and ~MusicItemMoreRecommendQueryWidget().
bool MusicItemMoreRecommendQueryWidget::m_categoryChanged private
Definition at line 195 of file musicmainrecommendwidget.h.
Referenced by categoryChanged(), and createResultItem().
QGridLayout* MusicItemMoreRecommendQueryWidget::m_gridLayout private
Definition at line 198 of file musicmainrecommendwidget.h.
Referenced by buttonClicked(), categoryChanged(), createResultItem(), initialize(), resizeGeometry(), and ~MusicItemMoreRecommendQueryWidget().
QWidget* MusicItemMoreRecommendQueryWidget::m_mainWidget private
Definition at line 197 of file musicmainrecommendwidget.h.
Referenced by createResultItem(), initialize(), MusicItemMoreRecommendQueryWidget(), and ~MusicItemMoreRecommendQueryWidget().
RecommendModule MusicItemMoreRecommendQueryWidget::m_module private
Definition at line 196 of file musicmainrecommendwidget.h.
Referenced by categoryChanged(), createResultItem(), currentItemClicked(), and initialize().
MusicAbstractQueryRequest* MusicItemMoreRecommendQueryWidget::m_networkRequest private
Definition at line 202 of file musicmainrecommendwidget.h.
Referenced by buttonClicked(), categoryChanged(), createResultItem(), initialize(), and ~MusicItemMoreRecommendQueryWidget().
MusicPageQueryWidget* MusicItemMoreRecommendQueryWidget::m_pageQueryWidget private
Definition at line 201 of file musicmainrecommendwidget.h.
Referenced by buttonClicked(), createResultItem(), and ~MusicItemMoreRecommendQueryWidget().
QWidgetList MusicItemMoreRecommendQueryWidget::m_resizeWidgets private
Definition at line 199 of file musicmainrecommendwidget.h.
Referenced by createResultItem(), removeItems(), and resizeGeometry().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.h
TTKModule/TTKWidget/musicWidgetKits/musicmainrecommendwidget.cpp