TTKMusicplayer: MusicSoundKMicroSettingPopWidget Class Reference
MusicSoundKMicroSettingPopWidget Class Reference
The class of the sound kmicro setting pop widget.
#include <musicsoundkmicrosettingpopwidget.h>
Public Slots
void volumeChanged (int value)
Public Slots inherited from MusicToolMenuWidget
virtual void popupMenu ()
Public Member Functions
MusicSoundKMicroSettingPopWidget (QWidget *parent=nullptr)
~MusicSoundKMicroSettingPopWidget ()
void setAudioCore (MusicAudioRecorderModule *core)
int audioInputIndex () const
int audioOutputIndex () const
Public Member Functions inherited from MusicToolMenuWidget
MusicToolMenuWidget (QWidget *parent=nullptr)
~MusicToolMenuWidget ()
void setTranslucentBackground ()
Protected Member Functions
void initWidget ()
Protected Attributes
QComboBox * m_inputComboBox
QComboBox * m_outputComboBox
MusicAudioRecorderModule * m_recordCore
Protected Attributes inherited from MusicToolMenuWidget
MusicToolMenu * m_menu
QWidget * m_containWidget
Detailed Description
The class of the sound kmicro setting pop widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 30 of file musicsoundkmicrosettingpopwidget.h.
Constructor & Destructor Documentation
MusicSoundKMicroSettingPopWidget::MusicSoundKMicroSettingPopWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musicsoundkmicrosettingpopwidget.cpp.
References initWidget().
MusicSoundKMicroSettingPopWidget::~MusicSoundKMicroSettingPopWidget ()
Definition at line 14 of file musicsoundkmicrosettingpopwidget.cpp.
References m_inputComboBox, and m_outputComboBox.
Member Function Documentation
int MusicSoundKMicroSettingPopWidget::audioInputIndex () const
Audio input index.
Definition at line 95 of file musicsoundkmicrosettingpopwidget.cpp.
References m_inputComboBox.
int MusicSoundKMicroSettingPopWidget::audioOutputIndex () const
Audio output index.
Definition at line 100 of file musicsoundkmicrosettingpopwidget.cpp.
References m_outputComboBox.
void MusicSoundKMicroSettingPopWidget::initWidget () protected
Create all widget in layout.
Definition at line 20 of file musicsoundkmicrosettingpopwidget.cpp.
References MusicUtils::Widget::generateComboBoxFormat(), MusicToolMenuWidget::m_containWidget, m_inputComboBox, MusicToolMenuWidget::m_menu, m_outputComboBox, m_recordCore, MusicUIObject::MQSSBackgroundStyle01, MusicUIObject::MQSSBackgroundStyle08, MusicUIObject::MQSSBorderStyle04, MusicUIObject::MQSSCheckBoxStyle05, MusicUIObject::MQSSColorStyle03, MusicUIObject::MQSSMenuStyle05, MusicUIObject::MQSSSliderStyle01, MusicToolMenuWidget::setTranslucentBackground(), and volumeChanged().
Referenced by MusicSoundKMicroSettingPopWidget().
void MusicSoundKMicroSettingPopWidget::setAudioCore (MusicAudioRecorderModule * core)
Set audio core.
Definition at line 89 of file musicsoundkmicrosettingpopwidget.cpp.
References m_recordCore, and volumeChanged().
void MusicSoundKMicroSettingPopWidget::volumeChanged (int value) slot
Volume changed.
Definition at line 105 of file musicsoundkmicrosettingpopwidget.cpp.
References m_recordCore, and MusicAudioRecorderModule::setVolume().
Referenced by initWidget(), and setAudioCore().
Member Data Documentation
QComboBox* MusicSoundKMicroSettingPopWidget::m_inputComboBox protected
Definition at line 66 of file musicsoundkmicrosettingpopwidget.h.
Referenced by audioInputIndex(), initWidget(), and ~MusicSoundKMicroSettingPopWidget().
QComboBox * MusicSoundKMicroSettingPopWidget::m_outputComboBox protected
Definition at line 66 of file musicsoundkmicrosettingpopwidget.h.
Referenced by audioOutputIndex(), initWidget(), and ~MusicSoundKMicroSettingPopWidget().
MusicAudioRecorderModule* MusicSoundKMicroSettingPopWidget::m_recordCore protected
Definition at line 67 of file musicsoundkmicrosettingpopwidget.h.
Referenced by initWidget(), setAudioCore(), and volumeChanged().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrosettingpopwidget.h
TTKModule/TTKWidget/musicToolsSetsKits/musicsoundkmicrosettingpopwidget.cpp