TTKMusicPlayer: MusicSongDailyWidget Class Reference
MusicSongDailyWidget Class Reference
The class of the song daily widget.
#include <musicsongdailywidget.h>
Public Member Functions
MusicSongDailyWidget (QWidget *parent=nullptr)
~MusicSongDailyWidget ()
virtual void resizeWidget () overridefinal
Public Member Functions inherited from TTKAbstractResizeInterface
virtual ~TTKAbstractResizeInterface ()=default
Private Slots
void downLoadImageFinished (const QByteArray &bytes)
Private Member Functions
virtual void resizeEvent (QResizeEvent *event) overridefinal
Private Attributes
QLabel * m_container
QLabel * m_note
QLabel * m_content
MusicCiBaRequest * m_networkRequest
Detailed Description
The class of the song daily widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 31 of file musicsongdailywidget.h.
Constructor & Destructor Documentation
MusicSongDailyWidget::MusicSongDailyWidget (QWidget * parent = nullptr) explicit
Object constructor.
Definition at line 7 of file musicsongdailywidget.cpp.
References TTK::UI::BackgroundStyle10, downLoadImageFinished(), m_container, m_content, m_networkRequest, m_note, and MusicCiBaRequest::startToRequest().
MusicSongDailyWidget::~MusicSongDailyWidget ()
Object destructor.
Definition at line 29 of file musicsongdailywidget.cpp.
References m_container, m_content, m_networkRequest, and m_note.
Member Function Documentation
void MusicSongDailyWidget::downLoadImageFinished (const QByteArray & bytes) private slot
Download image data from net finished.
Definition at line 57 of file musicsongdailywidget.cpp.
References TTK::Image::colorContrast(), MusicCiBaRequest::content(), m_container, m_content, m_networkRequest, m_note, MusicCiBaRequest::note(), resizeWidget(), and TTK_ERROR_STREAM.
Referenced by MusicSongDailyWidget().
void MusicSongDailyWidget::resizeEvent (QResizeEvent * event) final override private virtual
Override the widget event.
Definition at line 103 of file musicsongdailywidget.cpp.
References resizeWidget().
void MusicSongDailyWidget::resizeWidget () final override virtual
Resize widget bound by resize called.
Implements TTKAbstractResizeInterface.
Definition at line 37 of file musicsongdailywidget.cpp.
References TTK::Widget::fontTextHeight(), TTK::Widget::fontTextWidth(), G_SETTING_PTR, m_content, m_note, MusicSettingManager::WidgetSize, and WINDOW_HEIGHT_MIN.
Referenced by downLoadImageFinished(), and resizeEvent().
Member Data Documentation
QLabel* MusicSongDailyWidget::m_container private
Definition at line 62 of file musicsongdailywidget.h.
Referenced by downLoadImageFinished(), MusicSongDailyWidget(), and ~MusicSongDailyWidget().
QLabel * MusicSongDailyWidget::m_content private
Definition at line 63 of file musicsongdailywidget.h.
Referenced by downLoadImageFinished(), MusicSongDailyWidget(), resizeWidget(), and ~MusicSongDailyWidget().
MusicCiBaRequest* MusicSongDailyWidget::m_networkRequest private
Definition at line 64 of file musicsongdailywidget.h.
Referenced by downLoadImageFinished(), MusicSongDailyWidget(), and ~MusicSongDailyWidget().
QLabel* MusicSongDailyWidget::m_note private
Definition at line 63 of file musicsongdailywidget.h.
Referenced by downLoadImageFinished(), MusicSongDailyWidget(), resizeWidget(), and ~MusicSongDailyWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicWidgetKits/musicsongdailywidget.h
TTKModule/TTKWidget/musicWidgetKits/musicsongdailywidget.cpp