TTKMusicplayer: QDesWrapPrivate Class Reference
QDesWrapPrivate Class Reference
Public Member Functions
qint64 bitTransform (int *array, int len, qint64 source)
void DESSubKeys (qint64 key, qint64 *K, QDesWrap::Mode mode)
qint64 DES64 (qint64 *subkeys, qint64 data)
char * encrypt (char *src, int srcLength, char *key)
Public Member Functions inherited from TTKPrivate< QDesWrap >
TTKPrivate ()
virtual ~TTKPrivate ()
void setPublic (QDesWrap *pub)
Public Attributes
QDesWrap::Mode m_mode
Additional Inherited Members
Protected Member Functions inherited from TTKPrivate< QDesWrap >
QDesWrap * ttk_q () const
Detailed Description
Definition at line 173 of file qdeswrap.cpp.
Member Function Documentation
qint64 QDesWrapPrivate::bitTransform (int * array, int len, qint64 source)
Definition at line 184 of file qdeswrap.cpp.
References ARRAYMASK.
Referenced by DES64(), and DESSubKeys().
qint64 QDesWrapPrivate::DES64 (qint64 * subkeys, qint64 data)
Definition at line 221 of file qdeswrap.cpp.
References ARRAYE, ARRAYIP, ARRAYIP_1, ARRAYP, bitTransform(), int(), and MATRIXNSBOX.
Referenced by encrypt().
void QDesWrapPrivate::DESSubKeys (qint64 key, qint64 * K, QDesWrap::Mode mode)
Definition at line 199 of file qdeswrap.cpp.
References ARRAYLS, ARRAYLSMASK, ARRAYPC_1, ARRAYPC_2, bitTransform(), and QDesWrap::DECRYPT.
Referenced by encrypt().
char * QDesWrapPrivate::encrypt (char * src, int srcLength, char * key)
Definition at line 270 of file qdeswrap.cpp.
References DES64(), DESSubKeys(), and m_mode.
Member Data Documentation
QDesWrap::Mode QDesWrapPrivate::m_mode
Definition at line 181 of file qdeswrap.cpp.
Referenced by encrypt().
The documentation for this class was generated from the following file:
TTKThirdParty/TTKExtras/qalg/qdeswrap.cpp