TTKMusicplayer: MusicLocalSongSearchPopWidget Class Reference
MusicLocalSongSearchPopWidget Class Reference
The class of the search history Config.
#include <musiclocalsongsearchpopwidget.h>
Public Slots
void clearButtonClicked ()
Signals
void setText (const QString &text)
Public Member Functions
MusicLocalSongSearchPopWidget (QWidget *parent=0)
~MusicLocalSongSearchPopWidget ()
void createItems ()
void createSuggestItems (const QStringList &names)
Static Public Member Functions
static QString getClassName ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event) override
virtual void leaveEvent (QEvent *event) override
QString utcTimeToLocal (const QString &time) const
Protected Attributes
QPushButton * m_clearButton
MusicLocalSongSearchPopTableWidget * m_popTableWidget
Detailed Description
The class of the search history Config.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 71 of file musiclocalsongsearchpopwidget.h.
Constructor & Destructor Documentation
MusicLocalSongSearchPopWidget::MusicLocalSongSearchPopWidget (QWidget * parent = 0) explicit
Object contsructor.
Definition at line 64 of file musiclocalsongsearchpopwidget.cpp.
References clearButtonClicked(), m_clearButton, m_popTableWidget, MusicUIObject::MBackgroundStyle03, MusicUIObject::MBackgroundStyle17, MusicUIObject::MBorderStyle01, MusicUIObject::MColorStyle03, MusicUIObject::MCustomStyle01, MusicUIObject::MFontStyle02, and setText().
MusicLocalSongSearchPopWidget::~MusicLocalSongSearchPopWidget ()
Definition at line 99 of file musiclocalsongsearchpopwidget.cpp.
References m_clearButton, and m_popTableWidget.
Member Function Documentation
void MusicLocalSongSearchPopWidget::clearButtonClicked () slot
Clear the search history.
Definition at line 155 of file musiclocalsongsearchpopwidget.cpp.
References MusicLocalSongSearchRecordConfigManager::readSearchXMLConfig(), and MusicLocalSongSearchRecordConfigManager::writeSearchConfig().
Referenced by MusicLocalSongSearchPopWidget().
void MusicLocalSongSearchPopWidget::createItems ()
Create popup search history table items.
Definition at line 110 of file musiclocalsongsearchpopwidget.cpp.
References MusicLocalSongSearchPopTableWidget::clearAllItems(), MusicLocalSongSearchPopTableWidget::createItems(), m_clearButton, m_popTableWidget, MusicLocalSongSearchRecordConfigManager::readSearchConfig(), MusicLocalSongSearchRecordConfigManager::readSearchXMLConfig(), ROW_HEIGHT, and utcTimeToLocal().
Referenced by MusicLocalSongSearchInlineEdit::popWidgetChanged().
void MusicLocalSongSearchPopWidget::createSuggestItems (const QStringList & names)
Create popup search suggest table items.
Definition at line 134 of file musiclocalsongsearchpopwidget.cpp.
References MusicLocalSongSearchPopTableWidget::clearAllItems(), MusicLocalSongSearchPopTableWidget::createItems(), m_clearButton, m_popTableWidget, and ROW_HEIGHT.
Referenced by MusicLocalSongSearchInlineEdit::suggestDataChanged().
QString MusicLocalSongSearchPopWidget::getClassName () static
Get class object name.
Definition at line 105 of file musiclocalsongsearchpopwidget.cpp.
void MusicLocalSongSearchPopWidget::leaveEvent (QEvent * event) override protected virtual
Definition at line 175 of file musiclocalsongsearchpopwidget.cpp.
void MusicLocalSongSearchPopWidget::paintEvent (QPaintEvent * event) override protected virtual
Override the widget event.
Definition at line 166 of file musiclocalsongsearchpopwidget.cpp.
void MusicLocalSongSearchPopWidget::setText (const QString & text) signal
User click the current item, emit the current text.
Referenced by MusicLocalSongSearchPopWidget().
QString MusicLocalSongSearchPopWidget::utcTimeToLocal (const QString & time) const protected
Transform utc time to local time before.
Definition at line 149 of file musiclocalsongsearchpopwidget.cpp.
References MT_S2MS, MusicTime::normalTime2Label(), and MusicTime::timeStamp().
Referenced by createItems().
Member Data Documentation
QPushButton* MusicLocalSongSearchPopWidget::m_clearButton protected
Definition at line 118 of file musiclocalsongsearchpopwidget.h.
Referenced by createItems(), createSuggestItems(), MusicLocalSongSearchPopWidget(), and ~MusicLocalSongSearchPopWidget().
MusicLocalSongSearchPopTableWidget* MusicLocalSongSearchPopWidget::m_popTableWidget protected
Definition at line 119 of file musiclocalsongsearchpopwidget.h.
Referenced by createItems(), createSuggestItems(), MusicLocalSongSearchPopWidget(), and ~MusicLocalSongSearchPopWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchpopwidget.h
TTKModule/TTKWidget/musicSearchKits/musiclocalsongsearchpopwidget.cpp