TTKMusicPlayer: QJsonParser Class Reference
QJsonParser Class Reference
#include <QJsonParser.h>
Public Member Functions
QJsonParser (const char *begin, const char *end)
QJsonRoot * parse ()
QJsonParseError state () const
Private Member Functions
char peek ()
QJsonObject * getObject ()
QJsonArray * getArray ()
QJsonValue getValue ()
QString getString ()
QJsonValue getTrue ()
QJsonValue getFalse ()
QJsonValue getNull ()
QJsonValue getNumber ()
QPair< QString, QJsonValue > getPair ()
void throwError (QJsonParseError::ParseError e)
Private Attributes
QJsonParseError state_
const char *const begin_
const char *const end_
const char * p_
Static Private Attributes
static const char ArrayBegin = '['
static const char ArrayEnd = ']'
static const char NameSeparator = ':'
static const char ValueSeparator = ','
static const char ObjectBegin = '{'
static const char ObjectEnd = '}'
static const char Quote = '"'
Friends
class QJsonDocument
Detailed Description
Definition at line 36 of file QJsonParser.h.
Constructor & Destructor Documentation
QJsonParser::QJsonParser (const char * begin, const char * end)
Definition at line 57 of file QJsonParser.cpp.
References QJsonParseError::error, QJsonParseError::NoError, QJsonParseError::offset, and state_.
Member Function Documentation
QJsonArray * QJsonParser::getArray () private
Definition at line 190 of file QJsonParser.cpp.
References ArrayBegin, ArrayEnd, getValue(), QJsonParseError::IllegalValue, QJsonParseError::MissingValueSeparator, p_, peek(), throwError(), and ValueSeparator.
Referenced by getValue(), and parse().
QJsonValue QJsonParser::getFalse () private
Definition at line 369 of file QJsonParser.cpp.
References end_, QJsonParseError::IllegalValue, p_, and throwError().
Referenced by getValue().
QJsonValue QJsonParser::getNull () private
Definition at line 345 of file QJsonParser.cpp.
References end_, QJsonParseError::IllegalValue, p_, and throwError().
Referenced by getValue().
QJsonValue QJsonParser::getNumber () private
Definition at line 382 of file QJsonParser.cpp.
References end_, QJsonParseError::IllegalNumber, isdigit, p_, QJsonParseError::TerminationByNumber, and throwError().
Referenced by getValue().
QJsonObject * QJsonParser::getObject () private
Definition at line 153 of file QJsonParser.cpp.
References getPair(), QJsonParseError::IllegalValue, ObjectBegin, ObjectEnd, p_, peek(), throwError(), QJsonParseError::UnterminatedObject, and ValueSeparator.
Referenced by getValue(), and parse().
QPair< QString, QJsonValue > QJsonParser::getPair () private
Definition at line 226 of file QJsonParser.cpp.
References getString(), getValue(), key, QJsonParseError::MissingNameSeparator, NameSeparator, p_, peek(), and throwError().
Referenced by getObject().
QString QJsonParser::getString () private
Definition at line 241 of file QJsonParser.cpp.
References end_, QJsonParseError::IllegalEscapeSequence, QJsonParseError::IllegalUTF8String, p_, peek(), Quote, throwError(), and QJsonParseError::UnterminatedString.
Referenced by getPair(), and getValue().
QJsonValue QJsonParser::getTrue () private
Definition at line 357 of file QJsonParser.cpp.
References end_, QJsonParseError::IllegalValue, p_, and throwError().
Referenced by getValue().
QJsonValue QJsonParser::getValue () private
Definition at line 121 of file QJsonParser.cpp.
References ArrayBegin, getArray(), getFalse(), getNull(), getNumber(), getObject(), getString(), getTrue(), QJsonParseError::MissingObject, ObjectBegin, peek(), Quote, and throwError().
Referenced by getArray(), and getPair().
QJsonRoot * QJsonParser::parse ()
Definition at line 65 of file QJsonParser.cpp.
References ArrayBegin, begin_, end_, QJsonParseError::error, QJsonParseError::GarbageAtEnd, getArray(), getObject(), QJsonParseError::IllegalValue, ObjectBegin, QJsonParseError::offset, p_, peek(), and state_.
Referenced by QJsonDocument::fromJson().
char QJsonParser::peek () private
Definition at line 109 of file QJsonParser.cpp.
References end_, and p_.
Referenced by getArray(), getObject(), getPair(), getString(), getValue(), and parse().
QJsonParseError QJsonParser::state () const
Definition at line 441 of file QJsonParser.cpp.
References state_.
Referenced by QJsonDocument::fromJson().
void QJsonParser::throwError (QJsonParseError::ParseError e) private
Definition at line 448 of file QJsonParser.cpp.
References begin_, QJsonParseError::error, QJsonParseError::offset, and p_.
Referenced by getArray(), getFalse(), getNull(), getNumber(), getObject(), getPair(), getString(), getTrue(), and getValue().
Friends And Related Function Documentation
friend class QJsonDocument friend
Definition at line 37 of file QJsonParser.h.
Member Data Documentation
const char QJsonParser::ArrayBegin = '[' static private
Definition at line 49 of file QJsonParser.h.
Referenced by getArray(), getValue(), and parse().
const char QJsonParser::ArrayEnd = ']' static private
Definition at line 50 of file QJsonParser.h.
Referenced by getArray().
const char* const QJsonParser::begin_ private
Definition at line 74 of file QJsonParser.h.
Referenced by parse(), and throwError().
const char* const QJsonParser::end_ private
Definition at line 75 of file QJsonParser.h.
Referenced by getFalse(), getNull(), getNumber(), getString(), getTrue(), parse(), and peek().
const char QJsonParser::NameSeparator = ':' static private
Definition at line 51 of file QJsonParser.h.
Referenced by getPair().
const char QJsonParser::ObjectBegin = '{' static private
Definition at line 53 of file QJsonParser.h.
Referenced by getObject(), getValue(), and parse().
const char QJsonParser::ObjectEnd = '}' static private
Definition at line 54 of file QJsonParser.h.
Referenced by getObject().
const char* QJsonParser::p_ private
Definition at line 76 of file QJsonParser.h.
Referenced by getArray(), getFalse(), getNull(), getNumber(), getObject(), getPair(), getString(), getTrue(), parse(), peek(), and throwError().
const char QJsonParser::Quote = '"' static private
Definition at line 55 of file QJsonParser.h.
Referenced by getString(), and getValue().
QJsonParseError QJsonParser::state_ private
Definition at line 73 of file QJsonParser.h.
Referenced by parse(), QJsonParser(), and state().
const char QJsonParser::ValueSeparator = ',' static private
Definition at line 52 of file QJsonParser.h.
Referenced by getArray(), and getObject().
The documentation for this class was generated from the following files:
TTKThirdParty/TTKExtras/qjson/QJsonParser.h
TTKThirdParty/TTKExtras/qjson/QJsonParser.cpp