TTKMusicPlayer: MusicLrcFloatSettingWidget Class Reference
MusicLrcFloatSettingWidget Class Reference
The class of the lrc setting float widget.
#include <musiclrcfloatsettingwidget.h>
Public Slots
void show ()
void lrcSizeUpChanged ()
void lrcSizeLowChanged ()
void lrcMusicBackgroundChanged ()
void lrcArtBackgroundChanged ()
Signals
void widgetClose ()
Public Member Functions
MusicLrcFloatSettingWidget (QWidget *parent=nullptr)
void resizeGeometry (int width, int height)
Public Member Functions inherited from MusicAbstractFloatWidget
MusicAbstractFloatWidget (QWidget *parent=nullptr)
~MusicAbstractFloatWidget ()
void setBlockAnimation (bool b)
Private Member Functions
virtual void enterEvent (QtEnterEvent *) overridefinal
virtual void leaveEvent (QEvent *event) overridefinal
QPushButton * createPushButton (int index)
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractFloatWidget
virtual void contextMenuEvent (QContextMenuEvent *) overridefinal
virtual void mousePressEvent (QMouseEvent *) overridefinal
virtual void mouseMoveEvent (QMouseEvent *) overridefinal
virtual void mouseReleaseEvent (QMouseEvent *) overridefinal
void animationEnter ()
void animationLeave ()
Protected Attributes inherited from MusicAbstractFloatWidget
QPropertyAnimation * m_animation
QRect m_rectEnter
QRect m_rectLeave
bool m_blockAnimation
Detailed Description
The class of the lrc setting float widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musiclrcfloatsettingwidget.h.
Constructor & Destructor Documentation
MusicLrcFloatSettingWidget::MusicLrcFloatSettingWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musiclrcfloatsettingwidget.cpp.
References createPushButton(), lrcArtBackgroundChanged(), lrcMusicBackgroundChanged(), lrcSizeLowChanged(), lrcSizeUpChanged(), MusicUIObject::MQSSBackgroundStyle05, MusicUIObject::MQSSColorStyle01, MusicUIObject::MQSSCustomStyle02, MusicUIObject::MQSSInteriorFloatSetting, MusicUIObject::MQSSInteriorLrcBigger, MusicUIObject::MQSSInteriorLrcSmaller, MusicUIObject::MQSSPushButtonStyle06, and QtButtonGroupConnect.
Member Function Documentation
QPushButton * MusicLrcFloatSettingWidget::createPushButton (int index) private
Create pushButton by given index.
Definition at line 83 of file musiclrcfloatsettingwidget.cpp.
Referenced by MusicLrcFloatSettingWidget().
virtual void MusicLrcFloatSettingWidget::enterEvent (QtEnterEvent *) inline final override private virtual
Override the widget event.
Reimplemented from MusicAbstractFloatWidget.
Definition at line 76 of file musiclrcfloatsettingwidget.h.
void MusicLrcFloatSettingWidget::leaveEvent (QEvent * event) final override private virtual
Reimplemented from MusicAbstractFloatWidget.
Definition at line 144 of file musiclrcfloatsettingwidget.cpp.
References MusicAbstractFloatWidget::animationLeave(), MusicAbstractFloatWidget::m_animation, and widgetClose().
void MusicLrcFloatSettingWidget::lrcArtBackgroundChanged () slot
Change current background to artist.
Definition at line 129 of file musiclrcfloatsettingwidget.cpp.
References MusicLrcContainerForInterior::artistBackgroundChanged(), MusicLrcContainerForInterior::isShowArtistBackground(), and TTKObject_cast.
Referenced by MusicLrcFloatSettingWidget().
void MusicLrcFloatSettingWidget::lrcMusicBackgroundChanged () slot
Change current background to default.
Definition at line 120 of file musiclrcfloatsettingwidget.cpp.
References MusicLrcContainerForInterior::artistBackgroundChanged(), MusicLrcContainerForInterior::isShowArtistBackground(), and TTKObject_cast.
Referenced by MusicLrcFloatSettingWidget().
void MusicLrcFloatSettingWidget::lrcSizeLowChanged () slot
Change current lrc size down.
Definition at line 111 of file musiclrcfloatsettingwidget.cpp.
References MusicLrcDefines::findInteriorLrcIndex(), MusicLrcDefines::findInteriorPreSize(), MusicLrcContainerForInterior::lrcSize(), MusicLrcContainerForInterior::setLrcSize(), and TTKObject_cast.
Referenced by MusicLrcFloatSettingWidget().
void MusicLrcFloatSettingWidget::lrcSizeUpChanged () slot
Change current lrc size up.
Definition at line 102 of file musiclrcfloatsettingwidget.cpp.
References MusicLrcDefines::findInteriorLrcIndex(), MusicLrcDefines::findInteriorNextSize(), MusicLrcContainerForInterior::lrcSize(), MusicLrcContainerForInterior::setLrcSize(), and TTKObject_cast.
Referenced by MusicLrcFloatSettingWidget().
void MusicLrcFloatSettingWidget::resizeGeometry (int width, int height)
Resize geometry bound by given width and height.
Definition at line 76 of file musiclrcfloatsettingwidget.cpp.
References MusicAbstractFloatWidget::m_rectEnter, and MusicAbstractFloatWidget::m_rectLeave.
Referenced by MusicLrcFloatWidget::resizeGeometry().
void MusicLrcFloatSettingWidget::show () slot
Override show function.
Definition at line 138 of file musiclrcfloatsettingwidget.cpp.
References MusicAbstractFloatWidget::animationEnter().
Referenced by MusicLrcFloatWidget::showFloatSettingWidget().
void MusicLrcFloatSettingWidget::widgetClose () signal
Widget close it.
Referenced by leaveEvent().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatsettingwidget.h
TTKModule/TTKWidget/musicLrcKits/musiclrcfloatsettingwidget.cpp