TTKMusicplayer: MusicPagingWidgetModule Class Reference
MusicPagingWidgetModule Class Reference
The class of the paging widget object.
#include <musicpagingwidgetmodule.h>
Signals
void clicked (int index)
Public Member Functions
MusicPagingWidgetModule (QObject *parent=nullptr)
~MusicPagingWidgetModule ()
QWidget * createPagingWidget (QWidget *parent, int total)
void reset (int total)
void paging (int index, int total)
int currentIndex () const
Protected Attributes
int m_currentPage
QWidget * m_pagingWidget
QList< MusicClickedLabel * > m_pagingItems
Detailed Description
The class of the paging widget object.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file musicpagingwidgetmodule.h.
Constructor & Destructor Documentation
MusicPagingWidgetModule::MusicPagingWidgetModule (QObject * parent = nullptr) explicit
Object contsructor.
Definition at line 10 of file musicpagingwidgetmodule.cpp.
References m_currentPage, and m_pagingWidget.
MusicPagingWidgetModule::~MusicPagingWidgetModule ()
Definition at line 17 of file musicpagingwidgetmodule.cpp.
References m_pagingItems, and m_pagingWidget.
Member Function Documentation
void MusicPagingWidgetModule::clicked (int index) signal
Mapped the clicked page index.
Referenced by createPagingWidget().
QWidget * MusicPagingWidgetModule::createPagingWidget (QWidget * parent, int total)
Create paging items.
Definition at line 23 of file musicpagingwidgetmodule.cpp.
References clicked(), MusicUtils::Widget::fontTextWidth(), m_pagingItems, m_pagingWidget, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSFontStyle01, MusicUIObject::MQSSFontStyle05, and PAGE_SIZE.
Referenced by MusicArtistListQueryWidget::createArtistListItem(), MusicArtistMvsQueryWidget::createArtistMvsItem(), MusicCommentsWidget::createPagingWidget(), MusicPlaylistQueryWidget::createPlaylistItem(), and MusicWebDJRadioQueryWidget::createProgramItem().
int MusicPagingWidgetModule::currentIndex () const
Get current page index.
Definition at line 210 of file musicpagingwidgetmodule.cpp.
References m_currentPage, and m_pagingItems.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsQueryWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), and MusicPlaylistQueryWidget::buttonClicked().
void MusicPagingWidgetModule::paging (int index, int total)
Start to page by given index and total.
Definition at line 116 of file musicpagingwidgetmodule.cpp.
References MusicUtils::Widget::fontTextWidth(), m_currentPage, m_pagingItems, MusicUIObject::MQSSColorStyle04, MusicUIObject::MQSSFontStyle01, and PAGE_SIZE.
Referenced by MusicCommentsWidget::buttonClicked(), MusicArtistMvsQueryWidget::buttonClicked(), MusicArtistListQueryWidget::buttonClicked(), MusicWebDJRadioQueryWidget::buttonClicked(), and MusicPlaylistQueryWidget::buttonClicked().
void MusicPagingWidgetModule::reset (int total)
Reset page to origin.
Definition at line 90 of file musicpagingwidgetmodule.cpp.
References m_currentPage, m_pagingItems, and PAGE_SIZE.
Referenced by MusicArtistListQueryWidget::createArtistListItem(), MusicPlaylistQueryWidget::createPlaylistItem(), and MusicWebDJRadioQueryWidget::createProgramItem().
Member Data Documentation
int MusicPagingWidgetModule::m_currentPage protected
Definition at line 64 of file musicpagingwidgetmodule.h.
Referenced by currentIndex(), MusicPagingWidgetModule(), paging(), and reset().
QList<MusicClickedLabel*> MusicPagingWidgetModule::m_pagingItems protected
Definition at line 66 of file musicpagingwidgetmodule.h.
Referenced by createPagingWidget(), currentIndex(), paging(), reset(), and ~MusicPagingWidgetModule().
QWidget* MusicPagingWidgetModule::m_pagingWidget protected
Definition at line 65 of file musicpagingwidgetmodule.h.
Referenced by createPagingWidget(), MusicPagingWidgetModule(), and ~MusicPagingWidgetModule().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicCoreKits/musicpagingwidgetmodule.h
TTKModule/TTKWidget/musicCoreKits/musicpagingwidgetmodule.cpp