TTKMusicplayer: MusicCloudFileInformationWidget Class Reference
MusicCloudFileInformationWidget Class Reference
The class of the cloud file information widget.
#include <musiccloudfileinformationwidget.h>
Public Slots
virtual int exec ()
Public Slots inherited from MusicAbstractMoveDialog
void backgroundChanged ()
Public Member Functions
MusicCloudFileInformationWidget (QWidget *parent=nullptr)
~MusicCloudFileInformationWidget ()
void setFileInformation (QSyncDataItem *data)
Public Member Functions inherited from MusicAbstractMoveDialog
MusicAbstractMoveDialog (QWidget *parent=nullptr)
MusicAbstractMoveDialog (bool transparent, QWidget *parent=nullptr)
virtual ~MusicAbstractMoveDialog ()
void drawWindowShadow (bool show)
void blockMoveOption (bool block)
Protected Attributes
Ui::MusicCloudFileInformationWidget * m_ui
Protected Attributes inherited from MusicAbstractMoveDialog
QPoint m_pressAt
bool m_moveOption
bool m_showShadow
bool m_leftButtonPress
QWidget * m_background
Additional Inherited Members
Protected Member Functions inherited from MusicAbstractMoveDialog
virtual void paintEvent (QPaintEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
void setBackgroundPixmap (QLabel *label, const QSize &size)
void setBackgroundPixmap (const QSize &size)
Detailed Description
The class of the cloud file information widget.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 33 of file musiccloudfileinformationwidget.h.
Constructor & Destructor Documentation
MusicCloudFileInformationWidget::MusicCloudFileInformationWidget (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 8 of file musiccloudfileinformationwidget.cpp.
References m_ui, and MusicUIObject::MQSSToolButtonStyle04.
MusicCloudFileInformationWidget::~MusicCloudFileInformationWidget ()
Definition at line 22 of file musiccloudfileinformationwidget.cpp.
References m_ui.
Member Function Documentation
int MusicCloudFileInformationWidget::exec () virtual slot
Override exec function.
Definition at line 36 of file musiccloudfileinformationwidget.cpp.
References m_ui, and MusicAbstractMoveDialog::setBackgroundPixmap().
Referenced by MusicCloudManagerTableWidget::showFileInformationWidget().
void MusicCloudFileInformationWidget::setFileInformation (QSyncDataItem * data)
Set music file song path name.
Definition at line 27 of file musiccloudfileinformationwidget.cpp.
References QSyncDataItem::m_hash, QSyncDataItem::m_mimeType, QSyncDataItem::m_name, QSyncDataItem::m_putTime, QSyncDataItem::m_size, m_ui, and MusicUtils::Number::sizeByte2Label().
Referenced by MusicCloudManagerTableWidget::showFileInformationWidget().
Member Data Documentation
Ui::MusicCloudFileInformationWidget* MusicCloudFileInformationWidget::m_ui protected
Definition at line 56 of file musiccloudfileinformationwidget.h.
Referenced by exec(), MusicCloudFileInformationWidget(), setFileInformation(), and ~MusicCloudFileInformationWidget().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicToolsKits/musiccloudfileinformationwidget.h
TTKModule/TTKWidget/musicToolsKits/musiccloudfileinformationwidget.cpp