TTKMusicPlayer: TTKBaseStringView< _CharT, _Traits > Class Template Reference
TTKBaseStringView< _CharT, _Traits > Class Template Reference
The class of the string view modules.
#include <ttkstringview.h>
Public Types
using traits_type = _Traits
using value_type = std::basic_string< _CharT >
using pointer = _CharT *
using const_pointer = const _CharT *
using reference = _CharT &
using const_reference = const _CharT &
using const_iterator = const _CharT *
using iterator = const_iterator
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = const_reverse_iterator
using size_type = size_t
Public Member Functions
constexpr TTKBaseStringView () noexcept
template<size_type T>
constexpr TTKBaseStringView (const _CharT(&data)[T])
constexpr TTKBaseStringView (const _CharT *data, const size_type length)
constexpr TTKBaseStringView (const _CharT *data)
constexpr TTKBaseStringView (const TTKBaseStringView &) noexcept=default
TTKBaseStringView (const value_type &s) noexcept
constexpr TTKBaseStringView & operator= (const TTKBaseStringView &sv) noexcept
constexpr operator value_type () const
constexpr const_iterator begin () const noexcept
constexpr const_iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr const_reverse_iterator rbegin () const noexcept
constexpr const_reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
constexpr size_type size () const noexcept
constexpr size_type length () const noexcept
constexpr bool empty () const noexcept
constexpr const _CharT & operator[] (size_type o) const
const _CharT & at (size_type o) const
constexpr const _CharT & front () const noexcept
constexpr const _CharT & back () const noexcept
constexpr const _CharT * data () const noexcept
constexpr TTKBaseStringView substr (size_type a) const noexcept
constexpr TTKBaseStringView substr (size_type a, size_type b) const noexcept
constexpr size_type find (const _CharT c) const noexcept
constexpr size_type find (const value_type &c) const noexcept
constexpr size_type find (const TTKBaseStringView &sv) const noexcept
constexpr size_type find (const _CharT *c) const noexcept
constexpr size_type find (const _CharT *c, size_type sl) const noexcept
constexpr size_type rfind (const _CharT c) const noexcept
constexpr size_type rfind (const _CharT *s) const noexcept
constexpr size_type find_first_of (const value_type &s, size_type l=0) const noexcept
constexpr size_type find_first_of (const _CharT *s, size_type l=0) const noexcept
constexpr size_type find_first_of (_CharT c, size_type l=0) const noexcept
constexpr size_type find_first_not_of (const value_type &s) const
constexpr size_type find_first_not_of (const value_type &s, size_type o) const
constexpr size_type find_first_not_of (const _CharT *s) const
constexpr size_type find_first_not_of (const _CharT *s, size_type o) const
constexpr size_type find_first_not_of (_CharT c, size_type o=0) const
constexpr int compare (const TTKBaseStringView &sv) const noexcept
constexpr int compare (const _CharT *data) const noexcept
constexpr int compare (const value_type &s) const noexcept
value_type & operator<< (value_type &s)
bool operator== (const TTKBaseStringView &other) noexcept
bool operator== (const value_type &other) noexcept
bool operator== (const _CharT *other) noexcept
bool operator!= (const TTKBaseStringView &other) noexcept
bool operator!= (const value_type &other) noexcept
bool operator!= (const _CharT *other) noexcept
bool operator<= (const TTKBaseStringView &other) noexcept
bool operator<= (const value_type &other) noexcept
bool operator<= (const _CharT *other) noexcept
bool operator< (const TTKBaseStringView &other) noexcept
bool operator< (const value_type &other) noexcept
bool operator< (const _CharT *other) noexcept
bool operator>= (const TTKBaseStringView &other) noexcept
bool operator>= (const value_type &other) noexcept
bool operator>= (const _CharT *other) noexcept
bool operator> (const TTKBaseStringView &other) noexcept
bool operator> (const value_type &other) noexcept
bool operator> (const _CharT *other) noexcept
Static Public Member Functions
static TTKBaseStringView split (const _CharT *&cur, const _CharT *line_end, _CharT split_char)
Static Public Attributes
static constexpr size_type npos = size_type(-1)
Private Attributes
const_pointer m_data
size_type m_length
Friends
std::basic_ostream< _CharT > & operator<< (std::basic_ostream< _CharT > &os, const TTKBaseStringView &sv)
value_type & operator+= (value_type &s, const TTKBaseStringView &sv)
Detailed Description
template<typename _CharT, typename _Traits = std::char_traits<_CharT>>
class TTKBaseStringView< _CharT, _Traits >
The class of the string view modules.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 29 of file ttkstringview.h.
Member Typedef Documentation
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::const_iterator = const _CharT*
Definition at line 38 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::const_pointer = const _CharT*
Definition at line 35 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::const_reference = const _CharT&
Definition at line 37 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 40 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::iterator = const_iterator
Definition at line 39 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::pointer = _CharT*
Definition at line 34 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::reference = _CharT&
Definition at line 36 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::reverse_iterator = const_reverse_iterator
Definition at line 41 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::size_type = size_t
Definition at line 42 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::traits_type = _Traits
Definition at line 32 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> using TTKBaseStringView< _CharT, _Traits >::value_type = std::basic_string<_CharT>
Definition at line 33 of file ttkstringview.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView () inline noexcept
Definition at line 46 of file ttkstringview.h.
Referenced by TTKBaseStringView< _CharT, _Traits >::split(), and TTKBaseStringView< _CharT, _Traits >::substr().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> template<size_type T> constexpr TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView (const _CharT(&) data[T]) inline
Definition at line 54 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView (const _CharT * data, const size_type length) inline explicit
Definition at line 61 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView (const _CharT * data) inline
Definition at line 68 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView (const TTKBaseStringView< _CharT, _Traits > &) default noexcept
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView (const value_type & s) inline noexcept
Definition at line 76 of file ttkstringview.h.
Member Function Documentation
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> const _CharT& TTKBaseStringView< _CharT, _Traits >::at (size_type o) const inline
Definition at line 108 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::m_length.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const _CharT& TTKBaseStringView< _CharT, _Traits >::back () const inline noexcept
Definition at line 118 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::m_length.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_iterator TTKBaseStringView< _CharT, _Traits >::begin () const inline noexcept
Definition at line 95 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data.
Referenced by TTKBaseStringView< _CharT, _Traits >::crend(), and TTKBaseStringView< _CharT, _Traits >::rend().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_iterator TTKBaseStringView< _CharT, _Traits >::cbegin () const inline noexcept
Definition at line 97 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_iterator TTKBaseStringView< _CharT, _Traits >::cend () const inline noexcept
Definition at line 98 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::m_length.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr int TTKBaseStringView< _CharT, _Traits >::compare (const TTKBaseStringView< _CharT, _Traits > & sv) const inline noexcept
Definition at line 404 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTK::min().
Referenced by TTKBaseStringView< _CharT, _Traits >::operator!=(), TTKBaseStringView< _CharT, _Traits >::operator<(), TTKBaseStringView< _CharT, _Traits >::operator<=(), TTKBaseStringView< _CharT, _Traits >::operator==(), TTKBaseStringView< _CharT, _Traits >::operator>(), and TTKBaseStringView< _CharT, _Traits >::operator>=().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr int TTKBaseStringView< _CharT, _Traits >::compare (const _CharT * data) const inline noexcept
Definition at line 410 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTK::min().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr int TTKBaseStringView< _CharT, _Traits >::compare (const value_type & s) const inline noexcept
Definition at line 417 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTK::min().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_reverse_iterator TTKBaseStringView< _CharT, _Traits >::crbegin () const inline noexcept
Definition at line 101 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::end().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_reverse_iterator TTKBaseStringView< _CharT, _Traits >::crend () const inline noexcept
Definition at line 102 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::begin().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const _CharT* TTKBaseStringView< _CharT, _Traits >::data () const inline noexcept
Definition at line 119 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data.
Referenced by TTKBaseStringView< _CharT, _Traits >::compare(), TTKBaseStringView< _CharT, _Traits >::find_first_not_of(), and TTKBaseStringView< _CharT, _Traits >::operator<<().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr bool TTKBaseStringView< _CharT, _Traits >::empty () const inline noexcept
Definition at line 105 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_length.
Referenced by TTKBaseStringView< _CharT, _Traits >::find_first_not_of().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_iterator TTKBaseStringView< _CharT, _Traits >::end () const inline noexcept
Definition at line 96 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::m_length.
Referenced by TTKBaseStringView< _CharT, _Traits >::crbegin(), TTKBaseStringView< _CharT, _Traits >::rbegin(), and TTKBaseStringView< _CharT, _Traits >::split().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find (const _CharT c) const inline noexcept
Definition at line 131 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find (const value_type & c) const inline noexcept
Definition at line 146 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find (const TTKBaseStringView< _CharT, _Traits > & sv) const inline noexcept
Definition at line 167 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find (const _CharT * c) const inline noexcept
Definition at line 188 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find (const _CharT * c, size_type sl) const inline noexcept
Definition at line 209 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_not_of (const value_type & s) const inline
Definition at line 348 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::empty(), TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_not_of (const value_type & s, size_type o) const inline
Definition at line 359 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::npos, and TTKBaseStringView< _CharT, _Traits >::size().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_not_of (const _CharT * s) const inline
Definition at line 370 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::empty(), TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_not_of (const _CharT * s, size_type o) const inline
Definition at line 381 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::npos, and TTKBaseStringView< _CharT, _Traits >::size().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_not_of (_CharT c, size_type o = 0) const inline
Definition at line 392 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::npos, and TTKBaseStringView< _CharT, _Traits >::size().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_of (const value_type & s, size_type l = 0) const inline noexcept
Definition at line 292 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_of (const _CharT * s, size_type l = 0) const inline noexcept
Definition at line 313 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::find_first_of (_CharT c, size_type l = 0) const inline noexcept
Definition at line 334 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const _CharT& TTKBaseStringView< _CharT, _Traits >::front () const inline noexcept
Definition at line 117 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::length () const inline noexcept
Definition at line 104 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_length.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView< _CharT, _Traits >::operator value_type () const inline explicit
Definition at line 90 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::m_length.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator!= (const TTKBaseStringView< _CharT, _Traits > & other) inline noexcept
Definition at line 459 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator!= (const value_type & other) inline noexcept
Definition at line 460 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator!= (const _CharT * other) inline noexcept
Definition at line 461 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator< (const TTKBaseStringView< _CharT, _Traits > & other) inline noexcept
Definition at line 467 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator< (const value_type & other) inline noexcept
Definition at line 468 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator< (const _CharT * other) inline noexcept
Definition at line 469 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> value_type& TTKBaseStringView< _CharT, _Traits >::operator<< (value_type & s) inline
Definition at line 453 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::data(), and TTKBaseStringView< _CharT, _Traits >::size().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator<= (const TTKBaseStringView< _CharT, _Traits > & other) inline noexcept
Definition at line 463 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator<= (const value_type & other) inline noexcept
Definition at line 464 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator<= (const _CharT * other) inline noexcept
Definition at line 465 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView& TTKBaseStringView< _CharT, _Traits >::operator= (const TTKBaseStringView< _CharT, _Traits > & sv) inline noexcept
Definition at line 83 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, and TTKBaseStringView< _CharT, _Traits >::m_length.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator== (const TTKBaseStringView< _CharT, _Traits > & other) inline noexcept
Definition at line 455 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator== (const value_type & other) inline noexcept
Definition at line 456 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator== (const _CharT * other) inline noexcept
Definition at line 457 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator> (const TTKBaseStringView< _CharT, _Traits > & other) inline noexcept
Definition at line 475 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator> (const value_type & other) inline noexcept
Definition at line 476 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator> (const _CharT * other) inline noexcept
Definition at line 477 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator>= (const TTKBaseStringView< _CharT, _Traits > & other) inline noexcept
Definition at line 471 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator>= (const value_type & other) inline noexcept
Definition at line 472 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> bool TTKBaseStringView< _CharT, _Traits >::operator>= (const _CharT * other) inline noexcept
Definition at line 473 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::compare().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const _CharT& TTKBaseStringView< _CharT, _Traits >::operator[] (size_type o) const inline
Definition at line 106 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_reverse_iterator TTKBaseStringView< _CharT, _Traits >::rbegin () const inline noexcept
Definition at line 99 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::end().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr const_reverse_iterator TTKBaseStringView< _CharT, _Traits >::rend () const inline noexcept
Definition at line 100 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::begin().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::rfind (const _CharT c) const inline noexcept
Definition at line 230 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::npos.
Referenced by TTKBaseStringView< _CharT, _Traits >::rfind().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::rfind (const _CharT * s) const inline noexcept
Definition at line 245 of file ttkstringview.h.
References int(), TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::npos, TTKBaseStringView< _CharT, _Traits >::rfind(), and TTKBaseStringView< _CharT, _Traits >::size().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::size () const inline noexcept
Definition at line 103 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_length.
Referenced by TTKBaseStringView< _CharT, _Traits >::find_first_not_of(), TTKBaseStringView< _CharT, _Traits >::operator<<(), and TTKBaseStringView< _CharT, _Traits >::rfind().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> static TTKBaseStringView TTKBaseStringView< _CharT, _Traits >::split (const _CharT *& cur, const _CharT * line_end, _CharT split_char) inline static
Definition at line 435 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::end(), and TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView TTKBaseStringView< _CharT, _Traits >::substr (size_type a) const inline noexcept
Definition at line 121 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr TTKBaseStringView TTKBaseStringView< _CharT, _Traits >::substr (size_type a, size_type b) const inline noexcept
Definition at line 126 of file ttkstringview.h.
References TTKBaseStringView< _CharT, _Traits >::m_data, TTKBaseStringView< _CharT, _Traits >::m_length, and TTKBaseStringView< _CharT, _Traits >::TTKBaseStringView().
Friends And Related Function Documentation
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> value_type& operator+= (value_type & s, const TTKBaseStringView< _CharT, _Traits > & sv) friend
Definition at line 429 of file ttkstringview.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> std::basic_ostream<_CharT>& operator<< (std::basic_ostream< _CharT > & os, const TTKBaseStringView< _CharT, _Traits > & sv) friend
Definition at line 423 of file ttkstringview.h.
Member Data Documentation
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> const_pointer TTKBaseStringView< _CharT, _Traits >::m_data private
Definition at line 480 of file ttkstringview.h.
Referenced by TTKBaseStringView< _CharT, _Traits >::at(), TTKBaseStringView< _CharT, _Traits >::back(), TTKBaseStringView< _CharT, _Traits >::begin(), TTKBaseStringView< _CharT, _Traits >::cbegin(), TTKBaseStringView< _CharT, _Traits >::cend(), TTKBaseStringView< _CharT, _Traits >::compare(), TTKBaseStringView< _CharT, _Traits >::data(), TTKBaseStringView< _CharT, _Traits >::end(), TTKBaseStringView< _CharT, _Traits >::find(), TTKBaseStringView< _CharT, _Traits >::find_first_not_of(), TTKBaseStringView< _CharT, _Traits >::find_first_of(), TTKBaseStringView< _CharT, _Traits >::front(), TTKBaseStringView< _CharT, _Traits >::operator value_type(), TTKBaseStringView< _CharT, _Traits >::operator=(), TTKBaseStringView< _CharT, _Traits >::operator[](), TTKBaseStringView< _CharT, _Traits >::rfind(), and TTKBaseStringView< _CharT, _Traits >::substr().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> size_type TTKBaseStringView< _CharT, _Traits >::m_length private
Definition at line 481 of file ttkstringview.h.
Referenced by TTKBaseStringView< _CharT, _Traits >::at(), TTKBaseStringView< _CharT, _Traits >::back(), TTKBaseStringView< _CharT, _Traits >::cend(), TTKBaseStringView< _CharT, _Traits >::compare(), TTKBaseStringView< _CharT, _Traits >::empty(), TTKBaseStringView< _CharT, _Traits >::end(), TTKBaseStringView< _CharT, _Traits >::find(), TTKBaseStringView< _CharT, _Traits >::find_first_of(), TTKBaseStringView< _CharT, _Traits >::length(), TTKBaseStringView< _CharT, _Traits >::operator value_type(), TTKBaseStringView< _CharT, _Traits >::operator=(), TTKBaseStringView< _CharT, _Traits >::rfind(), TTKBaseStringView< _CharT, _Traits >::size(), and TTKBaseStringView< _CharT, _Traits >::substr().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> constexpr size_type TTKBaseStringView< _CharT, _Traits >::npos = size_type(-1) static
Definition at line 43 of file ttkstringview.h.
Referenced by TTKBaseStringView< _CharT, _Traits >::find(), TTKBaseStringView< _CharT, _Traits >::find_first_not_of(), TTKBaseStringView< _CharT, _Traits >::find_first_of(), and TTKBaseStringView< _CharT, _Traits >::rfind().
The documentation for this class was generated from the following file:
TTKCommon/TTKLibrary/ttkstringview.h