TTKMusicplayer: MusicLrcContainerForInterior Class Reference
MusicLrcContainerForInterior Class Reference
The class of the interior lrc container.
#include <musiclrccontainerforinterior.h>
Public Slots
void lrcSizeChanged (QAction *action)
void lrcTimeSpeedChanged (QAction *action)
void revertLrcTimeSpeed ()
void saveLrcTimeChanged ()
void artistBackgroundChanged ()
void showArtistBackgroundUploadedWidget ()
void lrcOpenFileDir () const
void lrcCopyClipboard () const
void showLocalLinkWidget ()
void showSongCommentsWidget ()
void showSoundKMicroWidget ()
void showLrcPosterWidget ()
Public Slots inherited from MusicLrcContainer
void currentLrcCustom ()
void changeCurrentLrcColor (QAction *action)
void changeCurrentLrcColor (int index)
void searchMusicLrcs ()
void showLrcMakedWidget ()
void linkLrcStateChanged ()
Signals
void updateCurrentTime (qint64 time)
void artistBackgroundHasChanged ()
Signals inherited from MusicLrcContainer
void currentLrcUpdated ()
void changeCurrentLrcColorCustom ()
void changeCurrentLrcColorSetting ()
void maskLinearGradientColorChanged ()
void linearGradientColorChanged ()
Public Member Functions
MusicLrcContainerForInterior (QWidget *parent=nullptr)
~MusicLrcContainerForInterior ()
virtual void startDrawLrc () override
virtual void stopDrawLrc () override
virtual void applySettingParameter () override
void updateCurrentLrc (qint64 time)
void updateCurrentLrc (int state)
QString text () const
qint64 setSongSpeedChanged (qint64 time)
void initFunctionLabel ()
void setLrcDisplayExpand (bool expand)
bool lrcDisplayExpand () const
bool artistBackgroundIsShow () const
void setLrcSize (int size)
int getLrcSize () const
void resizeWindow ()
void createFloatPlayWidget ()
void lrcWidgetShowFullScreen ()
Public Member Functions inherited from MusicLrcContainer
MusicLrcContainer (QWidget *parent=nullptr)
~MusicLrcContainer ()
void setLinearGradientColor (MusicLrcColor::LrcColorType lrcColorType)
void setLinearGradientColor (const MusicLrcColor &color)
void setCurrentSongName (const QString &name)
void setCurrentTime (qint64 time, qint64 total)
qint64 getTotalTime () const
void setLrcAnalysisModel (MusicLrcAnalysis *analysis)
MusicLrcAnalysis * getLrcAnalysisModel () const
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual void paintEvent (QPaintEvent *event) override
virtual void resizeEvent (QResizeEvent *event) override
void createColorMenu (QMenu &menu)
void revertLrcTimeSpeed (qint64 pos)
void createNoLrcCurrentInfo ()
void showNoLrcCurrentInfo ()
void initCurrentLrc (const QString &str)
void setItemStyleSheet ()
void setItemStyleSheet (int index, int size, int transparent)
int mapLrcSizeProperty (int size)
void setLrcSizeProperty (int property)
void resizeWidth (int w, int h)
Protected Member Functions inherited from MusicLrcContainer
void clearAllMusicLRCManager ()
void applySettingParameter (const QString &t)
Protected Attributes
QPoint m_mousePressedAt
bool m_mouseLeftPressed
bool m_lrcChangeState
bool m_mouseMoved
int m_lrcChangeOffset
int m_lrcChangeDelta
bool m_lrcDisplayAll
bool m_showArtistBackground
int m_animationFreshTime
int m_lrcSizeProperty
qint64 m_changeSpeedValue
QWidget * m_functionLabel
MusicLrcFloatWidget * m_lrcFloatWidget
MusicLrcFloatPlayWidget * m_floatPlayWidget
MusicClickedLabel * m_noLrcCurrentInfo
MusicLrcCommentsWidget * m_commentsWidget
MusicLrcTranslatedWidget * m_translatedWidget
MusicVLayoutAnimationWidget * m_layoutWidget
Protected Attributes inherited from MusicLrcContainer
bool m_linkLocalLrc
qint64 m_currentTime
qint64 m_totalTime
QString m_currentSongName
QString m_containerType
MusicLrcAnalysis * m_lrcAnalysis
QList< MusicLrcManager * > m_musicLrcContainer
MusicLrcSearchWidget * m_musicLrcSearchWidget
Private Slots
void queryTranslatedLrcFinished (const QString &bytes)
void musicSongMovieClicked ()
void updateAnimationLrc ()
void getTranslatedLrc ()
Detailed Description
The class of the interior lrc container.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 34 of file musiclrccontainerforinterior.h.
Constructor & Destructor Documentation
MusicLrcContainerForInterior::MusicLrcContainerForInterior (QWidget * parent = nullptr) explicit
Object contsructor.
Definition at line 34 of file musiclrccontainerforinterior.cpp.
References MusicLayoutAnimationWidget::addWidget(), MusicLayoutAnimationWidget::connectTo(), createNoLrcCurrentInfo(), LRC_INTERIOR_TPYE, m_animationFreshTime, m_changeSpeedValue, m_commentsWidget, MusicLrcContainer::m_containerType, m_floatPlayWidget, m_layoutWidget, m_lrcChangeDelta, m_lrcChangeOffset, m_lrcChangeState, m_lrcDisplayAll, m_lrcFloatWidget, m_lrcSizeProperty, m_mouseLeftPressed, m_mouseMoved, MusicLrcContainer::m_musicLrcContainer, m_showArtistBackground, m_translatedWidget, MUSIC_LRC_INTERIOR_MAX_LINE, and MusicLrcManager::setText().
MusicLrcContainerForInterior::~MusicLrcContainerForInterior ()
Definition at line 74 of file musiclrccontainerforinterior.cpp.
References MusicLrcContainer::clearAllMusicLRCManager(), m_commentsWidget, m_floatPlayWidget, m_functionLabel, m_layoutWidget, m_lrcFloatWidget, m_noLrcCurrentInfo, and m_translatedWidget.
Member Function Documentation
void MusicLrcContainerForInterior::applySettingParameter () override virtual
Set setting parameter.
Reimplemented from MusicLrcContainer.
Definition at line 97 of file musiclrccontainerforinterior.cpp.
References MusicLrcContainer::applySettingParameter(), G_SETTING_PTR, MusicSettingManager::LrcSize, m_lrcChangeDelta, m_lrcSizeProperty, and setLrcSize().
Referenced by MusicRightAreaWidget::applySettingParameter().
void MusicLrcContainerForInterior::artistBackgroundChanged () slot
The artist background state has changed.
Definition at line 274 of file musiclrccontainerforinterior.cpp.
References artistBackgroundHasChanged(), and m_showArtistBackground.
Referenced by contextMenuEvent(), MusicLrcFloatSettingWidget::lrcArtBackgroundChanged(), and MusicLrcFloatSettingWidget::lrcMusicBackgroundChanged().
void MusicLrcContainerForInterior::artistBackgroundHasChanged () signal
The art background state has changed emit.
Referenced by artistBackgroundChanged(), and showArtistBackgroundUploadedWidget().
bool MusicLrcContainerForInterior::artistBackgroundIsShow () const inline
Get state of background is artist shown.
Definition at line 90 of file musiclrccontainerforinterior.h.
Referenced by MusicLrcFloatSettingWidget::lrcArtBackgroundChanged(), and MusicLrcFloatSettingWidget::lrcMusicBackgroundChanged().
void MusicLrcContainerForInterior::contextMenuEvent (QContextMenuEvent * event) override protected virtual
Override the widget event.
Definition at line 386 of file musiclrccontainerforinterior.cpp.
References MusicUtils::Widget::adjustMenuPosition(), artistBackgroundChanged(), createColorMenu(), MusicLrcContainer::currentLrcCustom(), MusicLrcContainer::currentLrcUpdated(), G_BACKGROUND_PTR, G_SETTING_PTR, MusicLrcAnalysis::getCurrentFilePath(), MusicTopAreaWidget::instance(), MusicBottomAreaWidget::instance(), MusicLrcAnalysis::isEmpty(), MusicLrcContainer::linkLrcStateChanged(), lrcCopyClipboard(), lrcOpenFileDir(), MusicSettingManager::LrcSize, lrcSizeChanged(), lrcTimeSpeedChanged(), lrcWidgetShowFullScreen(), MusicLrcContainer::m_linkLocalLrc, MusicLrcContainer::m_lrcAnalysis, m_showArtistBackground, MusicUIObject::MQSSMenuStyle02, revertLrcTimeSpeed(), saveLrcTimeChanged(), MusicLrcContainer::searchMusicLrcs(), showArtistBackgroundUploadedWidget(), showLocalLinkWidget(), MusicLrcContainer::showLrcMakedWidget(), and showLrcPosterWidget().
void MusicLrcContainerForInterior::createColorMenu (QMenu & menu) protected
Create color menu.
Definition at line 636 of file musiclrccontainerforinterior.cpp.
References MusicLrcContainer::changeCurrentLrcColor(), MusicLrcContainer::currentLrcCustom(), and G_SETTING_PTR.
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::createFloatPlayWidget ()
Create float play widget.
Definition at line 203 of file musiclrccontainerforinterior.cpp.
References MusicBottomAreaWidget::instance(), m_floatPlayWidget, and MusicLrcFloatPlayWidget::resizeWindow().
void MusicLrcContainerForInterior::createNoLrcCurrentInfo () protected
Create no lrc current information.
Definition at line 687 of file musiclrccontainerforinterior.cpp.
References MusicObject::FT_Underline, m_noLrcCurrentInfo, MusicUIObject::MQSSColorStyle06, MusicUtils::Widget::setLabelFontSize(), MusicUtils::Widget::setLabelFontStyle(), and MusicLrcContainer::showLrcMakedWidget().
Referenced by MusicLrcContainerForInterior().
int MusicLrcContainerForInterior::getLrcSize () const
Get current lrc size.
Definition at line 179 of file musiclrccontainerforinterior.cpp.
References G_SETTING_PTR, and MusicSettingManager::LrcSize.
Referenced by MusicLrcFloatSettingWidget::lrcSizeLowChanged(), and MusicLrcFloatSettingWidget::lrcSizeUpChanged().
void MusicLrcContainerForInterior::getTranslatedLrc () private slot
Get all lrcs from tr container.
Definition at line 377 of file musiclrccontainerforinterior.cpp.
References G_DOWNLOAD_QUERY_PTR, MusicLrcAnalysis::getAllLrcString(), MusicLrcAnalysis::getCurrentFilePath(), MusicLrcContainer::m_lrcAnalysis, queryTranslatedLrcFinished(), MusicAbstractNetwork::setHeader(), and MusicTranslationRequest::startToDownload().
Referenced by initFunctionLabel().
void MusicLrcContainerForInterior::initCurrentLrc (const QString & str) protected
Init current lrc when the first show.
Definition at line 709 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and MusicLrcContainer::m_musicLrcContainer.
Referenced by resizeWidth().
void MusicLrcContainerForInterior::initFunctionLabel ()
Init function label widget.
Definition at line 718 of file musiclrccontainerforinterior.cpp.
References getTranslatedLrc(), m_functionLabel, MusicUIObject::MQSSInteriorMessage, MusicUIObject::MQSSInteriorMicrophone, MusicUIObject::MQSSInteriorMovie, MusicUIObject::MQSSInteriorTranslation, musicSongMovieClicked(), showSongCommentsWidget(), and showSoundKMicroWidget().
Referenced by MusicRightAreaWidget::setupUi().
void MusicLrcContainerForInterior::lrcCopyClipboard () const slot
Copy all lrcs to clipboard.
Definition at line 292 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getAllLrcString(), and MusicLrcContainer::m_lrcAnalysis.
Referenced by contextMenuEvent().
bool MusicLrcContainerForInterior::lrcDisplayExpand () const inline
Get state of background is artist shown.
Definition at line 86 of file musiclrccontainerforinterior.h.
Referenced by MusicRightAreaWidget::functionParameterInit(), and MusicRightAreaWidget::musicLrcDisplayAllButtonClicked().
void MusicLrcContainerForInterior::lrcOpenFileDir () const slot
Open current lrc file location.
Definition at line 287 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getCurrentFilePath(), MusicLrcContainer::m_lrcAnalysis, and MusicUtils::Url::openUrl().
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::lrcSizeChanged (QAction * action) slot
Set current lrc size by action.
Definition at line 227 of file musiclrccontainerforinterior.cpp.
References setLrcSize().
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::lrcTimeSpeedChanged (QAction * action) slot
Set lrc time speed changed by action.
Definition at line 240 of file musiclrccontainerforinterior.cpp.
References m_changeSpeedValue, MT_S2MS, and revertLrcTimeSpeed().
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::lrcWidgetShowFullScreen ()
Show full container or not.
Definition at line 214 of file musiclrccontainerforinterior.cpp.
References MusicBottomAreaWidget::instance(), MusicBottomAreaWidget::isLrcWidgetShowFullScreen(), m_functionLabel, and TTKStatic_cast.
Referenced by contextMenuEvent().
int MusicLrcContainerForInterior::mapLrcSizeProperty (int size) protected
Map lrc size property to line index.
Definition at line 852 of file musiclrccontainerforinterior.cpp.
Referenced by mouseMoveEvent(), and setLrcSize().
void MusicLrcContainerForInterior::mouseDoubleClickEvent (QMouseEvent * event) override protected virtual
Definition at line 627 of file musiclrccontainerforinterior.cpp.
References MusicBottomAreaWidget::instance(), MusicBottomAreaWidget::lrcWidgetShowFullScreen(), and m_functionLabel.
void MusicLrcContainerForInterior::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 546 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::count(), G_SETTING_PTR, MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), MusicLrcAnalysis::isValid(), LRC_CHANGED_OFFSET_LIMIT, MusicSettingManager::LrcSize, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, m_lrcChangeDelta, m_lrcChangeOffset, m_lrcChangeState, m_mouseLeftPressed, m_mouseMoved, m_mousePressedAt, MusicLrcContainer::m_musicLrcContainer, mapLrcSizeProperty(), MusicLrcAnalysis::setCurrentIndex(), setItemStyleSheet(), and MusicLayoutAnimationWidget::stop().
void MusicLrcContainerForInterior::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 523 of file musiclrccontainerforinterior.cpp.
References m_functionLabel, m_lrcChangeOffset, m_lrcChangeState, m_mouseLeftPressed, m_mouseMoved, and m_mousePressedAt.
void MusicLrcContainerForInterior::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 603 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::isValid(), MusicLrcContainer::m_lrcAnalysis, m_mouseLeftPressed, m_mouseMoved, m_mousePressedAt, and updateCurrentTime().
void MusicLrcContainerForInterior::musicSongMovieClicked () private slot
Video button clicked.
Definition at line 352 of file musiclrccontainerforinterior.cpp.
References MusicBottomAreaWidget::instance(), MusicRightAreaWidget::instance(), MusicBottomAreaWidget::isLrcWidgetShowFullScreen(), MusicBottomAreaWidget::lrcWidgetShowFullScreen(), MusicLrcContainer::m_currentSongName, and MusicRightAreaWidget::musicVideoButtonSearched().
Referenced by initFunctionLabel().
void MusicLrcContainerForInterior::paintEvent (QPaintEvent * event) override protected virtual
Definition at line 488 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::count(), MusicLrcAnalysis::findTime(), MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getMiddle(), LRC_TIME_LABEL_POSITION, m_functionLabel, MusicLrcContainer::m_lrcAnalysis, m_mouseLeftPressed, and MusicTime::msecTime2LabelJustified().
void MusicLrcContainerForInterior::queryTranslatedLrcFinished (const QString & bytes) private slot
Get translated lrc finished.
Definition at line 337 of file musiclrccontainerforinterior.cpp.
References MusicLrcContainer::m_currentSongName, m_translatedWidget, MusicLrcTranslatedWidget::setPlainText(), and text().
Referenced by getTranslatedLrc().
void MusicLrcContainerForInterior::resizeEvent (QResizeEvent * event) override protected virtual
Definition at line 517 of file musiclrccontainerforinterior.cpp.
References resizeWindow().
void MusicLrcContainerForInterior::resizeWidth (int w, int h) protected
Resize width bound by given width.
Definition at line 900 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), initCurrentLrc(), MusicLrcAnalysis::isEmpty(), m_commentsWidget, MusicLrcContainer::m_currentTime, m_floatPlayWidget, MusicLrcContainer::m_lrcAnalysis, m_lrcFloatWidget, MusicLrcContainer::m_musicLrcContainer, m_translatedWidget, MusicLrcFloatPlayWidget::resizeWindow(), MusicLrcFloatWidget::resizeWindow(), showNoLrcCurrentInfo(), and TTKStatic_cast.
Referenced by resizeWindow().
void MusicLrcContainerForInterior::resizeWindow ()
Resize window bound by widget resize called.
Definition at line 184 of file musiclrccontainerforinterior.cpp.
References G_SETTING_PTR, MusicBottomAreaWidget::instance(), LEFT_SIDE_WIDTH_MIN, m_lrcDisplayAll, resizeWidth(), MusicSettingManager::WidgetSize, WINDOW_HEIGHT_MIN, and WINDOW_WIDTH_MIN.
Referenced by resizeEvent(), MusicRightAreaWidget::resizeWindow(), and setLrcSize().
void MusicLrcContainerForInterior::revertLrcTimeSpeed () slot
Revert lrc time speed.
Definition at line 260 of file musiclrccontainerforinterior.cpp.
References m_changeSpeedValue.
Referenced by contextMenuEvent(), and lrcTimeSpeedChanged().
void MusicLrcContainerForInterior::revertLrcTimeSpeed (qint64 pos) protected
Revert lrc time speed by pos.
Definition at line 659 of file musiclrccontainerforinterior.cpp.
References m_changeSpeedValue, MusicLrcContainer::m_currentTime, MusicLrcContainer::m_lrcAnalysis, MT_S2MS, MusicToastLabel::popup(), MusicLrcAnalysis::revertLrcTime(), setSongSpeedChanged(), and updateCurrentLrc().
void MusicLrcContainerForInterior::saveLrcTimeChanged () slot
Save lrc time changed to current lrc file.
Definition at line 269 of file musiclrccontainerforinterior.cpp.
References MusicLrcContainer::m_lrcAnalysis, and MusicLrcAnalysis::saveLrcData().
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::setItemStyleSheet () protected
Set per lrc line style sheet.
Definition at line 773 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getLineMax(), and MusicLrcContainer::m_lrcAnalysis.
Referenced by mouseMoveEvent(), setLrcSize(), and updateAnimationLrc().
void MusicLrcContainerForInterior::setItemStyleSheet (int index, int size, int transparent) protected
Set per lrc line style sheet by index and size and transparent.
Definition at line 828 of file musiclrccontainerforinterior.cpp.
References G_SETTING_PTR, MusicLrcContainer::m_musicLrcContainer, MusicLrcColor::readColorConfig(), MusicLrcManagerForInterior::setFontSize(), MusicLrcManager::setFontTransparent(), MusicLrcContainer::setLinearGradientColor(), MusicLrcManagerForInterior::setTransparent(), and TTKStatic_cast.
void MusicLrcContainerForInterior::setLrcDisplayExpand (bool expand) inline
Get state of background is artist shown.
Definition at line 82 of file musiclrccontainerforinterior.h.
Referenced by MusicRightAreaWidget::musicLrcDisplayAllButtonClicked().
void MusicLrcContainerForInterior::setLrcSize (int size)
Set current lrc size.
Definition at line 153 of file musiclrccontainerforinterior.cpp.
References G_SETTING_PTR, MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getText(), MusicSettingManager::LrcSize, MusicLrcContainer::m_lrcAnalysis, m_lrcSizeProperty, MusicLrcContainer::m_musicLrcContainer, mapLrcSizeProperty(), resizeWindow(), MusicLrcAnalysis::setCurrentIndex(), setItemStyleSheet(), setLrcSizeProperty(), and startDrawLrc().
Referenced by applySettingParameter(), lrcSizeChanged(), MusicLrcFloatSettingWidget::lrcSizeLowChanged(), and MusicLrcFloatSettingWidget::lrcSizeUpChanged().
void MusicLrcContainerForInterior::setLrcSizeProperty (int property) protected
Set current lrc size property.
Definition at line 880 of file musiclrccontainerforinterior.cpp.
References MusicLayoutAnimationWidget::addWidget(), m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, MUSIC_LRC_INTERIOR_MAX_LINE, MusicLayoutAnimationWidget::removeWidget(), and MusicLrcAnalysis::setLineMax().
Referenced by setLrcSize().
qint64 MusicLrcContainerForInterior::setSongSpeedChanged (qint64 time)
Set song speed by given time, return new time.
Definition at line 148 of file musiclrccontainerforinterior.cpp.
References MusicLrcContainer::m_lrcAnalysis, and MusicLrcAnalysis::setSongSpeedChanged().
Referenced by revertLrcTimeSpeed(), and MusicRightAreaWidget::setSongSpeedAndSlow().
void MusicLrcContainerForInterior::showArtistBackgroundUploadedWidget () slot
The artist background has uploaded.
Definition at line 280 of file musiclrccontainerforinterior.cpp.
References artistBackgroundHasChanged(), MusicLrcArtPhotoUploadWidget::exec(), and m_showArtistBackground.
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::showLocalLinkWidget () slot
Show local link widget.
Definition at line 298 of file musiclrccontainerforinterior.cpp.
References MusicLrcLocalLinkWidget::exec(), MusicLrcContainer::m_currentSongName, and MusicLrcLocalLinkWidget::setCurrentSongName().
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::showLrcPosterWidget () slot
Show lrc poster widget.
Definition at line 330 of file musiclrccontainerforinterior.cpp.
References MusicLrcPosterWidget::exec(), MusicLrcAnalysis::getAllLrcList(), MusicLrcContainer::m_currentSongName, MusicLrcContainer::m_lrcAnalysis, and MusicLrcPosterWidget::setCurrentLrcs().
Referenced by contextMenuEvent().
void MusicLrcContainerForInterior::showNoLrcCurrentInfo () protected
Show no lrc current information.
Definition at line 699 of file musiclrccontainerforinterior.cpp.
References MusicUtils::Widget::fontTextHeight(), MusicUtils::Widget::fontTextWidth(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and m_noLrcCurrentInfo.
Referenced by resizeWidth(), and updateCurrentLrc().
void MusicLrcContainerForInterior::showSongCommentsWidget () slot
Show song comments widget.
Definition at line 305 of file musiclrccontainerforinterior.cpp.
References MusicLrcCommentsWidget::initWidget(), m_commentsWidget, MusicLrcContainer::m_currentSongName, and MusicCommentsWidget::setCurrentSongName().
Referenced by initFunctionLabel(), and MusicRightAreaWidget::musicSongCommentsWidget().
void MusicLrcContainerForInterior::showSoundKMicroWidget () slot
Show song KMicro widget.
Definition at line 320 of file musiclrccontainerforinterior.cpp.
References MusicLeftAreaWidget::createSoundKMicroWidget(), MusicLeftAreaWidget::instance(), and MusicLrcContainer::m_currentSongName.
Referenced by initFunctionLabel().
void MusicLrcContainerForInterior::startDrawLrc () override virtual
Start timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 86 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and MusicLrcContainer::m_musicLrcContainer.
Referenced by setLrcSize(), and MusicRightAreaWidget::startDrawLrc().
void MusicLrcContainerForInterior::stopDrawLrc () override virtual
Stop timer clock to draw lrc.
Implements MusicLrcContainer.
Definition at line 91 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getMiddle(), m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, and MusicLayoutAnimationWidget::stop().
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), and MusicRightAreaWidget::stopDrawLrc().
QString MusicLrcContainerForInterior::text () const
Get current lrc text in middle.
Definition at line 143 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getMiddle(), MusicLrcContainer::m_lrcAnalysis, and MusicLrcContainer::m_musicLrcContainer.
Referenced by queryTranslatedLrcFinished(), and MusicRightAreaWidget::updateCurrentLrc().
void MusicLrcContainerForInterior::updateAnimationLrc () private slot
Animation finished.
Definition at line 366 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::getCurrentIndex(), MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), MusicLrcAnalysis::getText(), m_animationFreshTime, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, MusicLrcAnalysis::setCurrentIndex(), and setItemStyleSheet().
void MusicLrcContainerForInterior::updateCurrentLrc (qint64 time)
Update current lrc by given time.
Definition at line 113 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::isValid(), m_animationFreshTime, m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, m_mouseLeftPressed, and MusicVLayoutAnimationWidget::start().
Referenced by MusicRightAreaWidget::loadCurrentSongLrc(), revertLrcTimeSpeed(), and MusicRightAreaWidget::updateCurrentLrc().
void MusicLrcContainerForInterior::updateCurrentLrc (int state)
Update current lrc by given state.
Definition at line 122 of file musiclrccontainerforinterior.cpp.
References MusicLrcAnalysis::Failed, MusicLrcAnalysis::getLineMax(), MusicLrcAnalysis::getMiddle(), m_layoutWidget, MusicLrcContainer::m_lrcAnalysis, MusicLrcContainer::m_musicLrcContainer, m_noLrcCurrentInfo, showNoLrcCurrentInfo(), and MusicLayoutAnimationWidget::stop().
void MusicLrcContainerForInterior::updateCurrentTime (qint64 time) signal
Update current play time when user adjust the progress.
Referenced by mouseReleaseEvent().
Member Data Documentation
int MusicLrcContainerForInterior::m_animationFreshTime protected
Definition at line 249 of file musiclrccontainerforinterior.h.
Referenced by MusicLrcContainerForInterior(), updateAnimationLrc(), and updateCurrentLrc().
qint64 MusicLrcContainerForInterior::m_changeSpeedValue protected
Definition at line 251 of file musiclrccontainerforinterior.h.
Referenced by lrcTimeSpeedChanged(), MusicLrcContainerForInterior(), and revertLrcTimeSpeed().
MusicLrcCommentsWidget* MusicLrcContainerForInterior::m_commentsWidget protected
Definition at line 256 of file musiclrccontainerforinterior.h.
Referenced by MusicLrcContainerForInterior(), resizeWidth(), showSongCommentsWidget(), and ~MusicLrcContainerForInterior().
MusicLrcFloatPlayWidget* MusicLrcContainerForInterior::m_floatPlayWidget protected
Definition at line 254 of file musiclrccontainerforinterior.h.
Referenced by createFloatPlayWidget(), MusicLrcContainerForInterior(), resizeWidth(), and ~MusicLrcContainerForInterior().
QWidget* MusicLrcContainerForInterior::m_functionLabel protected
Definition at line 252 of file musiclrccontainerforinterior.h.
Referenced by initFunctionLabel(), lrcWidgetShowFullScreen(), mouseDoubleClickEvent(), mousePressEvent(), paintEvent(), and ~MusicLrcContainerForInterior().
MusicVLayoutAnimationWidget* MusicLrcContainerForInterior::m_layoutWidget protected
Definition at line 258 of file musiclrccontainerforinterior.h.
Referenced by mouseMoveEvent(), MusicLrcContainerForInterior(), setLrcSizeProperty(), stopDrawLrc(), updateCurrentLrc(), and ~MusicLrcContainerForInterior().
int MusicLrcContainerForInterior::m_lrcChangeDelta protected
Definition at line 246 of file musiclrccontainerforinterior.h.
Referenced by applySettingParameter(), mouseMoveEvent(), and MusicLrcContainerForInterior().
int MusicLrcContainerForInterior::m_lrcChangeOffset protected
Definition at line 246 of file musiclrccontainerforinterior.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and MusicLrcContainerForInterior().
bool MusicLrcContainerForInterior::m_lrcChangeState protected
Definition at line 245 of file musiclrccontainerforinterior.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and MusicLrcContainerForInterior().
bool MusicLrcContainerForInterior::m_lrcDisplayAll protected
Definition at line 248 of file musiclrccontainerforinterior.h.
Referenced by MusicLrcContainerForInterior(), and resizeWindow().
MusicLrcFloatWidget* MusicLrcContainerForInterior::m_lrcFloatWidget protected
Definition at line 253 of file musiclrccontainerforinterior.h.
Referenced by MusicLrcContainerForInterior(), resizeWidth(), and ~MusicLrcContainerForInterior().
int MusicLrcContainerForInterior::m_lrcSizeProperty protected
Definition at line 249 of file musiclrccontainerforinterior.h.
Referenced by applySettingParameter(), MusicLrcContainerForInterior(), and setLrcSize().
bool MusicLrcContainerForInterior::m_mouseLeftPressed protected
Definition at line 245 of file musiclrccontainerforinterior.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), MusicLrcContainerForInterior(), paintEvent(), and updateCurrentLrc().
bool MusicLrcContainerForInterior::m_mouseMoved protected
Definition at line 245 of file musiclrccontainerforinterior.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and MusicLrcContainerForInterior().
QPoint MusicLrcContainerForInterior::m_mousePressedAt protected
Definition at line 244 of file musiclrccontainerforinterior.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
MusicClickedLabel* MusicLrcContainerForInterior::m_noLrcCurrentInfo protected
Definition at line 255 of file musiclrccontainerforinterior.h.
Referenced by createNoLrcCurrentInfo(), showNoLrcCurrentInfo(), updateCurrentLrc(), and ~MusicLrcContainerForInterior().
bool MusicLrcContainerForInterior::m_showArtistBackground protected
Definition at line 248 of file musiclrccontainerforinterior.h.
Referenced by artistBackgroundChanged(), contextMenuEvent(), MusicLrcContainerForInterior(), and showArtistBackgroundUploadedWidget().
MusicLrcTranslatedWidget* MusicLrcContainerForInterior::m_translatedWidget protected
Definition at line 257 of file musiclrccontainerforinterior.h.
Referenced by MusicLrcContainerForInterior(), queryTranslatedLrcFinished(), resizeWidth(), and ~MusicLrcContainerForInterior().
The documentation for this class was generated from the following files:
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforinterior.h
TTKModule/TTKWidget/musicLrcKits/musiclrccontainerforinterior.cpp