TTKMusicPlayer: MusicTXTConfigManager Class Reference
MusicTXTConfigManager Class Reference
The class of the txt playlist config manager.
#include <musictxtconfigmanager.h>
Public Member Functions
MusicTXTConfigManager ()
virtual bool readBuffer (MusicSongItemList &items) overridefinal
virtual bool writeBuffer (const MusicSongItemList &items) overridefinal
Public Member Functions inherited from TTKFileInterface
TTKFileInterface ()=default
virtual ~TTKFileInterface ()=default
bool load (const QString &name)
bool fromFile (const QString &name)
Public Member Functions inherited from TTKAbstractReadWriteInterface< T >
virtual ~TTKAbstractReadWriteInterface ()=default
Public Member Functions inherited from TTKAbstractReadInterface< T >
virtual ~TTKAbstractReadInterface ()=default
virtual bool readBuffer (T &items)=0
Public Member Functions inherited from TTKAbstractWriteInterface< T >
virtual ~TTKAbstractWriteInterface ()=default
virtual bool writeBuffer (const T &items)=0
Additional Inherited Members
Protected Attributes inherited from TTKFileInterface
QFile m_file
Detailed Description
The class of the txt playlist config manager.
Author
Greedysky greed.nosp@m.ysky.nosp@m.@163..nosp@m.com
Definition at line 27 of file musictxtconfigmanager.h.
Constructor & Destructor Documentation
MusicTXTConfigManager::MusicTXTConfigManager ()
Object constructor.
Definition at line 3 of file musictxtconfigmanager.cpp.
Member Function Documentation
bool MusicTXTConfigManager::readBuffer (MusicSongItemList & items) final override virtual
Read datas from buffer.
Definition at line 10 of file musictxtconfigmanager.cpp.
References TTKFileInterface::m_file, MusicSongItem::m_itemName, MusicSongItem::m_songs, qAsConst, TTK::String::split(), TTK_DEFAULT_STR, and TTK_LINEFEED.
Referenced by readTXTConfig().
bool MusicTXTConfigManager::writeBuffer (const MusicSongItemList & items) final override virtual
Write datas into buffer.
Definition at line 44 of file musictxtconfigmanager.cpp.
References TTKFileInterface::m_file, MusicSongItem::m_songs, qAsConst, and TTK_LINEFEED.
Referenced by writeTXTConfig().
The documentation for this class was generated from the following files:
TTKModule/TTKCore/musicPlaylistKits/musictxtconfigmanager.h
TTKModule/TTKCore/musicPlaylistKits/musictxtconfigmanager.cpp